### ISSUE TITLE
Error scanning file system with instanced glb

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#78242]
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Windows 10

### Issue description

I'm getting errors like this in one of my projects:

```
editor/editor_file_system.cpp:265 - Condition "split.size() != 9" is true. Continuing.
```

This didn't happen in Godot 4.1 beta 1 (and I was unable to reproduce the problem in that version).

The error comes from here: https://github.com/godotengine/godot/blob/33957aee69683cf1f542a8622e5a9efd23070f1c/editor/editor_file_system.cpp#LL265

Which led me to review the file "filesystem_cache8" where I found a line that indeed had more than 9 splits (when split by `"::"`). That allowed me to create a minimum reproduction project, attached below. In said reproduction project the line goes:

```
Scene.tscn::PackedScene::1357885261986312750::1686774267::0::1::::<><>::uid://d1o7xot6a82tm::::res://D/Duck.glb
```

### Steps to reproduce

You need an glb, and a scene that instances it. Which are included in the reproduction project attached below.

To get the error you would open the project in Godot 4.1 beta 2. If you don't get the error (for example because you previously opened the project in a different version of Godot) reload the project from the Project menu and you should get it.

### Minimal reproduction project

[test4.zip](https://github.com/godotengine/godot/files/11750296/test4.zip)

**Comment by akien-mga** [comment]
Sounds related to https://github.com/godotengine/godot/pull/73131, CC @KoBeWi.
