### ISSUE TITLE
Unrecoverable error when updating graphic driver while Godot editor is open

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#78247]
### Godot version

any

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

If you update a graphic driver while Godot is running, you will get a spam of this error:
```
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers\vulkan\vulkan_context.cpp:2357)
```
The editor becomes unresponsive and needs to be killed[.](https://i.kym-cdn.com/entries/icons/original/000/031/212/snipes.jpg) This can result in data loss.

### Steps to reproduce

1. Open Godot
2. Update graphic driver (e.g. using GeForce Experience)

### Minimal reproduction project

N/A

**Comment by DreamHollow** [comment]
For the record it is almost always a bad idea to update a major driver while using a program using those same drivers.

I'm not sure if this error can be rectified; it would require Godot having some predetermined access to the state of your GPU including it's update cycles.

Doesn't sound feasible.

**Comment by Calinou** [comment]
This likely depends on https://github.com/godotengine/godot-proposals/issues/6423 being implemented.

**Comment by KoBeWi** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/10269
