### ISSUE TITLE
Discussion: physics of apply_force

### ISSUE THREAD

**Issue by treapster** [godotengine/godot#78243]
### Godot version

v4.1.beta.custom_build.ae896bbd

### System information

Any

### Issue description

The current [implementation](https://github.com/godotengine/godot/blob/33957aee69683cf1f542a8622e5a9efd23070f1c/servers/physics_2d/godot_body_2d.h#L256) of apply_force violates the conservation of momentum. It does not account for tradeoff between angular and linear momentum, applying full force to the center of mass even when the force is applied far away from it - which means it creates angular momentum out of thin air when the force is applied outside of center of mass, and it's application of torque is 2x more than it would be according to physics. I propose a more realistic implementation and attach a demo to compare with current version. I understand that changing the implementation is a breaking change which will affect behavior of all rigid bodies, so let's discuss whether and how we want to do it.
I also created a [PR ](https://github.com/godotengine/godot/pull/78180) to show how it may look in godot's code.

<details>
<summary> New apply_force code </summary>

```gdscript
func apply_force_new(force: Vector2, pos: Vector2):
	var lever := pos - get_transform().basis_xform(center_of_mass)
	if (lever.is_zero_approx()):
		apply_central_force(force)
		return
	var torque := lever.cross(force) / 2
	var lever_normal_counterclockwise := -lever.orthogonal().normalized()
	var force_for_torque := torque / lever.length() * lever_normal_counterclockwise;
	apply_torque(torque)
	apply_central_force(force - force_for_torque)
```
</details>
<details>
<summary>Explanation of the new code</summary>

According to [wikipedia](https://en.wikipedia.org/wiki/Torque), "Torque is defined as the product of the magnitude of the perpendicular component of the force and the distance of the line of action of a force from the point around which it is being determined." The "point around which it is being determined" is the center of rotation, because measuring it in any other point means you're not just measuring torque, but linear force as well. When we push a floating rigid body to the side, it's center of mass is not the center of rotation since it starts to move. To measure torque around the center of mass, we have to add a coupled force on the other side with the same magnitude and opposite direction. This force will cancel out the movement of the center and now we get pure torque according to `r.cross(f)` (as used currently). This second force performs the same role as a pin joint in the center. But in original situation we do not have neither a second force nor a pin joint, hence we get half of that - `r.cross(f)/2.`
~~Then to compute the linear force we just compute the force produced by torque and subtract it from all force we have, and now we have accurate linear and rotational forces. If we don't do the substraction, we'll create angular momentum out of thin air.~~
</details>

### Video demo 
https://github.com/godotengine/godot/assets/71136698/fa7ca7d7-aded-43de-8bc8-e017baea2d17

The same force input is used for both objects and applied to the point near right end, just the implementation of apply_force is different. The excessive torque and momentum for the right body is very evident at high application angles.

### Steps to reproduce

1. Open the attached project
2. Run
3. Use WASD to apply force to two identical sticks. The focused one uses my implementation, the right one uses built-in. Observe the difference.
It is very clear that when pressing W the end of the left stick starts to realistically pull up and the other end slides in it's place when you pull it more. While the right stick gains a huge upwards and rotational momentum out of nowhere and tries to fly out of the frame

### Minimal reproduction project

[project](https://github.com/godotengine/godot/files/11737526/test.zip)

**Comment by AThousandShips** [comment]
Angular and linear momentum does not trade off, they are separate, see [here](https://van.physics.illinois.edu/ask/listing/24173#:~:text=A%3A,be%20converted%20to%20the%20other.) and [here](https://pubs.aip.org/aapt/ajp/article-abstract/79/10/1068/1043725/Student-understanding-of-the-angular-momentum-of?redirectedFrom=fulltext)

**Comment by treapster** [comment]
> Angular and linear momentum does not trade off, they are separate, see [here](https://van.physics.illinois.edu/ask/listing/24173#:~:text=A%3A,be%20converted%20to%20the%20other.) and [here](https://pubs.aip.org/aapt/ajp/article-abstract/79/10/1068/1043725/Student-understanding-of-the-angular-momentum-of?redirectedFrom=fulltext) and are conserved separately

They may be conserved separately, but you cannot create angular speed out of nothing. It is how it happens now.

**Comment by treapster** [comment]
@AThousandShips i do not see how my logic contradicts your references. All i'm saying is that we should divide r.cross(f) by 2 because we don't have a coupled force(as in pin joint case which is assumed by r.cross(f) formula), and substract the force which creates torque from the global force - which is just the obvious thing to do.

**Comment by treapster** [comment]
Okay, after some time googling and experimenting with the demo i got it: i was wrong about substracting "force for torque" from all force, and i understood that angular momentum does not really consume any part of linear momentum. Which makes sense if you think about angular momentum as two opposing linear momentums which equate to zero. I did not think of it in this way, and it was kinda cringe to propose substracting someting from a central force. But i think dividing the torque by 2 still makes sense for the same reason of not having a pinned center of mass. Do you agree?

**Comment by AThousandShips** [comment]
And that's what I've been saying, intuition and what seems obvious, without the actual factual details, is not a helpful tool for this. There's a reason rigid body dynamics is usually a college/university course, not a highschool one.

I still hold that the current formula is not only correct, but sufficient, breaking compat, and complicating the code, needs to be thoroughly justified.

I took a course, ten or so years ago, of dynamics and statics, and my otherwise plentiful intuition for science and mathematics was utterly unhelpful and I found the course extremely difficult, and unfortunately the textbooks I had (which were ridicu

**Comment by AThousandShips** [comment]
Read [this](https://www.google.se/url?sa=t&source=web&rct=j&url=https://www.brown.edu/Departments/Engineering/Courses/En4/Notes/Rigid_Bodies_1/Rigid_Bodies.pdf&ved=2ahUKEwif5Nuk8cT_AhW_Z_EDHSzqBOg4ChAWegQICRAB&usg=AOvVaw0R5Oi3d6Ju46___AW4lA4N), it's relatively straight forward, it's under section 6.7, page 48, it shows that the general equation is the correct one, without any scaling

**Comment by AThousandShips** [comment]
Closing due to lack of response and lack of sources

I see no reason to think that the current implementation is incorrect, it follows the textbook physics descriptions, and matches what other major open source physics engines do

If you can provide any source for your assumptions this can be reopened

**Comment by treapster** [comment]
I made a stackExchange question but currently without a clear answer https://physics.stackexchange.com/questions/771280/torque-on-body-when-force-applied-off-center-of-mass.

**Comment by AThousandShips** [comment]
From my reading of that it confirms what I've been saying:
> For your figure 1 a pin in the middle would constrain the rod to rotate about the centre of mass and the torque/couple would still be Fd

**Comment by treapster** [comment]
> From my reading of that it confirms what I've been saying:
> 
> > In Fig. 1 for example choose any point and you will find that the torque is always Fd
> 
I agree, but the question is about Fig 2 and it is not so clear. I hope it i'll find the answer eventually and share the results
