### ISSUE TITLE
Errors when using NavigationMesh.create_from_mesh()

### ISSUE THREAD

**Issue by eldidou** [godotengine/godot#78245]
### Godot version

4.0.2.stable

### System information

Linux Godot_v4.0.2-stable_linux.x86_64 Vulkan (forward+)

### Issue description

When using a custom mesh with create_from_mesh in some cases the following error is reported:

```
E 0:00:00:0287   sync: Attempted to merge a navigation mesh triangle edge with another already-merged edge. This happens when the current `cell_size` is different from the one used to generate the navigation mesh. This will cause navigation problems.
  <C++ Source>   modules/navigation/nav_map.cpp:692 @ sync()
```

This happen even for some simple meshes, like two touching, but not overlapping, triangles on the same plane.

Reading nav_map.cpp, it seems that it could be due to the _cell_size_ attribute of the NavigationMesh, but changing its value doesn't help.

### Steps to reproduce

- Create an ArrayMesh with these 2 triangles [(0.7, 0, 0.7), (0.7, 0, 1), (0.5, 0, 0.5)] and [(0.7, 0, 1.0), (0, 0, 1.0), (0.5, 0, 0.5)]
- Create a NavigationMesh with this ArrayMesh
- Create a NavigationRegion3D with this NavigationMesh
- The error should be produced

```
    var vertices = PackedVector3Array([Vector3(0.7, 0, 0.7),
                                       Vector3(0.7, 0, 1.0),
                                       Vector3(0.5, 0, 0.5),
                                       Vector3(0.7, 0, 1.0),
                                       Vector3(0.0, 0, 1.0),
                                       Vector3(0.5, 0, 0.5)]) 
    var indices = PackedInt32Array([0, 1, 2, 3, 4, 5])
    var arrays = []
    arrays.resize(Mesh.ARRAY_MAX)
    arrays[Mesh.ARRAY_VERTEX] = vertices
    arrays[Mesh.ARRAY_INDEX] = indices
    
    var arr_mesh = ArrayMesh.new()
    arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
    
    var nav_mesh = NavigationMesh.new()
    # nav_mesh.cell_size = 0.1 # doesn't help
    nav_mesh.create_from_mesh(arr_mesh)

    var nav_region := NavigationRegion3D.new()
    nav_region.navigation_mesh = nav_mesh
    add_child(nav_region)
```

### Minimal reproduction project

[custom_mesh.zip](https://github.com/godotengine/godot/files/11750588/custom_mesh.zip)

**Comment by smix8** [comment]
NavigationMesh `cell_size` and `cell_height` must match with the NavigationServer navigation map `cell_size` to not fail the rasterization of the navigation mesh vertices on the navigation map.

You can change the cell size either in the ProjectSettings for the default navigation map or by using the NavigationServer.map_set_cell_size() function at runtime.

All the `create_from_mesh()` function does is copy the vertices and indices over.
The function has zero validation if the data makes any sense for a navigation mesh.

**Comment by eldidou** [comment]
Small note, for godot 4.1 (beta2), the error can appear if the nav mesh `cell_size` doesn't match exactly the project setting `navigation/3d/default_cell_size`. Changing nav mesh `cell_size` is not required in 4.0.

Here is the updated version that works in 4.1, with the calls to `set_vertices()` and `add_polygon())` instead of `create_from_mesh()`

```
    var vertices = PackedVector3Array([Vector3(0.7, 0, 0.7),
                                       Vector3(0.7, 0, 1.0),
                                       Vector3(0.5, 0, 0.5),
                                       Vector3(0.7, 0, 1.0),
                                       Vector3(0.0, 0, 1.0),
                                       Vector3(0.5, 0, 0.5)])
    var indices = [PackedInt32Array([0, 1, 2]), PackedInt32Array([3, 4, 5])]

    var nav_mesh = NavigationMesh.new()
    nav_mesh.cell_size = 0.1 # needs to match exactly the project setting navigation/3d/default_cell_size, starting for godot 4.1
    nav_mesh.vertices = vertices
    for polygon in indices:
        nav_mesh.add_polygon(polygon)

    var nav_region := NavigationRegion3D.new()
    nav_region.navigation_mesh = nav_mesh
    add_child(nav_region)
```

**Comment by smix8** [comment]
> Should I close the issue?

If you don't have further questions, sure you can close it yourself.
