### ISSUE TITLE
C#: CSharpScript.CanInstantiate() returns true for abstract classes but .New() throws at runtime

### ISSUE THREAD

**Issue by juse4pro** [godotengine/godot#78244]
### Godot version

v4.1.beta1.mono.official [828ec2c5d]

### System information

Windows 11

### Issue description

When I call `.CanInstantiate()` on a CSharpScript object it returns true even though it can't be instantiated via `.New()` when the class is abstract. I get a runtime exception: `MemberAccessViolation: Cannot create an abstract class.` (see attachment)
![image](https://github.com/godotengine/godot/assets/7323098/b57dde1d-bc60-48b9-a21b-24838dd3a519)

I would expect that `.CanInstantiate()` only returns true when I actually can instantiate it.

### Steps to reproduce

* Get some kind of CSharpScript (e.g. via ResourceLoader)
* Call `.CanInstantiate()` on it / print it
* Call `.New()` on it
* Get exception

### Minimal reproduction project

[CanInstantiateBug.zip](https://github.com/godotengine/godot/files/11750566/CanInstantiateBug.zip)

**Comment by AThousandShips** [comment]
The script system doesn't seem to have any concept of abstractness, and the function doesn't test anything like that in `CSharpScript`, so seems like a missing functionality, would be supported if abstract classes were added to GDScript probably:
* https://github.com/godotengine/godot-proposals/issues/5641

**Comment by RedworkDE** [comment]
Also IIRC there was an issue for pretty much the same thing with gdscript where for core types can_instantiate returns true, but it is not actually possible to do so, can't find it rm tho,

**Comment by AThousandShips** [comment]
Was it:
* #77402

**Comment by juse4pro** [comment]
I can understand that GDScript does not support the concept of abstraction yet. But to be honest when a method says `Returns true if the script can be instantiated.` but I can't instaniate it I would expect that the `CSharpScript` implementation overrides it in a way that the abstract marking is checked. Because this way the API just delivers a wrong information.

So I think it more a bug seen from this perspective.
