### ISSUE TITLE
Texturerect, Stretch mode tile works with .PNG but not with .tres

### ISSUE THREAD

**Issue by Kiaazad** [godotengine/godot#78261]
### Godot version

4.0.3

### System information

windows 10

### Issue description

In texture rect, stretch more doesn't work when used with .tres atlastexure.
![image](https://github.com/godotengine/godot/assets/33455007/328d6e47-9aea-4903-9b2d-d2f7bc8aa68d)

### Steps to reproduce

Create texturerect,
Sdd a .tres atlasTrexture to it,
Set the tile mode to tile,
Stretch the texturerect,

### Minimal reproduction project

[tile bug report.zip](https://github.com/godotengine/godot/files/11754640/tile.bug.report.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/20472.
