### ISSUE TITLE
Batch rename won't check for duplicate unique name

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#78291]
### Godot version

v4.1.beta.custom_build [c0d8d91b1]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When batch renaming nodes it won't check for already used unique name. This will lead to the unique name being revoked with those warning. 
<img width="870" alt="Capture d’écran 2023-06-15 à 23 56 06" src="https://github.com/godotengine/godot/assets/66184050/8dbd861f-ca06-4217-9942-7f660dcbc76d">
Expected behavior would be a popup similar to this one being fired when doing the same rename with basic rename and preventing node rename.
<img width="439" alt="Capture d’écran 2023-06-15 à 23 56 21" src="https://github.com/godotengine/godot/assets/66184050/db77881b-fa6c-46b1-8746-e715b3846d9f">

### Steps to reproduce

1. create a scene with a root two child and one grand child
2. make unique name the scond child and the grand child
3. batch rename the two child to "Node"
4. see the warning and the unique name being revoked

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11763614/Test.zip)
with MRP start at step 3

**Comment by Calinou** [comment]
I've tried to reproduce this issue locally on v4.1.beta.custom_build [b6ba66483], but I don't see the batch rename dialog when selecting a child and a grandchild

![image](https://github.com/godotengine/godot/assets/180032/dc0970df-11c3-43e6-831d-78f293acaee2)

**Comment by ajreckof** [comment]
yeah this is why I precisely told two add two child and one grand child this is another bug #76069.
When I put to rename the two child I meant the root's child
