### ISSUE TITLE
Very noticeable performance issues when adding nodes to a scene that contains many scripted nodes (editor)

### ISSUE THREAD

**Issue by narren96c** [godotengine/godot#78295]
### Godot version

Godot 4.1-beta2

### System information

Manjaro Gnome, Intel Core i7-11800H

### Issue description

On a relatively modern laptop (Intel Core i7-11800H), in a scene with many scripted nodes (total of 900+ with roughly half of them scripted), adding or duplicating a node freezes the editor for several seconds. Godot 4.0.2 handles such scenes much better!

Here is a flame graph captured while repeatedly duplicating simple Marker2D nodes with Ctrl+D in a complicated scene:
![Screenshot from 2023-06-15 23-54-38](https://github.com/godotengine/godot/assets/2766569/d0019f17-9b82-4a26-9b47-71fa7a3bef3a)

Performance data file to use with hotspot v1.4.1 (relevant data starts at the 75-second mark and lasts about 20+ seconds):
[perf.data.perfparser.zip](https://github.com/godotengine/godot/files/11763700/perf.data.perfparser.zip)

### Steps to reproduce

1) Add 1000 nodes with a script attached.
2) Duplicate a node and witness lags.

Also affects scrolling the scene tree dock.

### Minimal reproduction project

[add_node_lags_repro.zip](https://github.com/godotengine/godot/files/11763731/add_node_lags_repro.zip)

**Comment by Calinou** [comment]
If you can [compile the engine from source](https://docs.godotengine.org/en/stable/development/compiling/index.html), you could look into [bisecting the regression](https://docs.godotengine.org/en/stable/community/contributing/bisecting_regressions.html) to greatly speed up troubleshooting.

**Comment by akien-mga** [comment]
CC @YuriSizov @KoBeWi

**Comment by KoBeWi** [comment]
Sounds similar #60127
Script icons are already cached, but `_get_class_or_script_icon()` doesn't fully utilize the cache probably.

**Comment by YuriSizov** [comment]
`EditorData` is responsible for caching all the information about scripts, and from the chart in the OP I can see that its methods get hit, but then continue into the GDScript module. Which means there were no cache entries for the scripts that it tried to check.

Also keep in mind that `EditorNode::_get_class_or_script_icon` is called for any type, including built-in types which are fetched directly from the theme. So it's going to be called a lot regardless of the scripted classes. But I don't believe that the changes made to it significantly modify the logic compared to 4.0.x.

**Comment by narren96c** [comment]
9fae65404a223a86816685b0b4036a57b8f976b7 is the first bad commit

**Comment by sketchyfun** [comment]
I've noticed this in my game too. Whenever I move a 3D object in the editor, it freezes for about a second. It definitely seems related to this script issue, as I was able to recreate the issue in a new scene with lots of duplicated nodes. The issue persisted until I finally tried removing the attached scripts, and then suddenly the issue went away.

**Comment by naturally-intelligent** [comment]
Just chiming in to say that I experience this with opening/switching to any large-ish scenes, which takes about 10 seconds in 4.1 and was nearly instant in 4.0. So I've stuck with 4.0.3. The issues for me started with 4.1-dev4.

**Comment by ValorZard** [comment]
Will this be solved for the 4.1 release?

**Comment by KoBeWi** [comment]
I think the problem is here:
https://github.com/godotengine/godot/blob/3710f069293f2fde8afe33fea898c4b36fa5e943/editor/editor_data.cpp#L1117
Before #75472 the icon could get cached as null and the script wouldn't be re-parsed, but that's not true anymore.

**Comment by narren96c** [comment]
I can confirm that #78670 improves performance. It is still worse than in version 4.0.2; however, the performance improvements are considerable and position it closer to 4.0.2 than beta 3.

**Comment by naturally-intelligent** [comment]
4.1-rc1 has eliminated the slowdown for me! :)
