### ISSUE TITLE
changing type of a node removes reference from `Node` properties

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#78299]
### Godot version

v4.1.beta.custom_build [dbd482faa]

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

Some editor action like changing type will replace the node by another node. Right now Node properties will still point to the old Node. 

### Steps to reproduce

1. create a scene with a root node 
2. attach a script that exports a node property
3. set the property to point to the root node 
4. change the type of the root node
5. look at the property it will error out and the editor will be blank

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11764206/Test.zip)
with MRP you can start at step 4

**Comment by Calinou** [comment]
I can reproduce this on 4.1.dev 33957aee6 but not 4.0.3, so this is a regression.

**Comment by ajreckof** [comment]
Yeah this is linked to the new way Node is linked since before Node we're not stored at all in the editor there was nothing to update.
