### ISSUE TITLE
GridMap painting does not capture mouse position properly when Half Resolution is enabled

### ISSUE THREAD

**Issue by Leandro-170** [godotengine/godot#78303]
### Godot version

4.0.3.stable

### System information

Windows 10 22H2 - Godot 4.0.3.stable, installed using Scoop - Compatibility backend (launched with --rendering-driver opengl3) - Dedicated low-end GPU (GT8600, latest 342.01 drivers)

### Issue description

While painting tiles in a Grid Map, if Half Resolution (inside the perspective menu) is enabled, the position of the next tile will not match the absolute position of the mouse on the viewport.

https://github.com/godotengine/godot/assets/73649765/4d3345f7-8408-45b8-918e-03551f46fdaa

As seen below, this is not exclusive to the orthogonal view.

https://github.com/godotengine/godot/assets/73649765/6d242555-c7e7-49ec-a993-2ccae03c33ae

### Steps to reproduce

1. In Godot, create a new scene, and put a GridMap either as the scene root or as a child of another node.
2. Assign a new MeshLibrary to it, and add a new item to that MeshLibrary, and assign any mesh and name to said item.
3. Inside the 3D view, go into the perspective menu, then enable Half Resolution
4. Select the item, then look at where it shows up relative to the mouse and try placing it

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/33937.
