### ISSUE TITLE
Editor `ThemeEditor` doesn't clip Tree "focus" state

### ISSUE THREAD

**Issue by AnidemDex** [godotengine/godot#78304]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Manjaro Linux

### Issue description

Title

### Steps to reproduce

1. Create a theme
2. Edit and select Tree
3. Scroll up or down
![image](https://github.com/godotengine/godot/assets/7025991/cfec95ba-96e6-46ee-9a06-dd4b82c5ef45)
![image](https://github.com/godotengine/godot/assets/7025991/ce28ba7b-7e6e-4ce0-a6f3-c7c83df8bf50)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/74670.
