### ISSUE TITLE
Question on multi Threading efficiency

### ISSUE THREAD

**Issue by Maveyyl** [godotengine/godot#7832]
**Operating system or device - Godot version:**
Processor quad core
Windows 7 and 10
Godot 2.1.2 stable
Godot legacy branch compiled 19/01/2017

**Issue description:**
I try to make a thread pool singleton. It creates a fixed count of Threads, I feed it with tasks and it tries to keep the threads busy as much as possible until every task is done. But I've met negative improvement of the computation time of my tasks.

I've then made an experiment:
use a simple function that takes lot of time, a for loop incrementing a variable.

I run it once, it takes 200ms to execute.
I run it in a thread, it takes 200ms.
I run it 4 times, it takes 800ms to finish. Normal.
I run it in 4 threads, it takes 550 ms. 0.66 times the previous result. Kinda disappointing.

I check in the profiler:
On the average, the function needs 200ms when executed single threaded.
On the average, the function needs 400ms when executed in many separate threads. The more threads, the slower will be the function.

I use a compiled version of godot that corresponds to the legacy branch of 19/01/2017, I also tried on the version 2.1.2 stable and the results were worse.

I open this issue to ask if this behaviour seems normal. I've already messed with multithreading in C and Java on quad-cores and cutting 2/3 of the computation time is not an usual result for me.

**Steps to reproduce:**
```gdscript
func _ready():
	var test_count = 4
	var arg1 = 500000
	var start
	var stop
	var test_time
	var test_multi_time

	start = OS.get_ticks_msec()
	for i in range(test_count):
		test(arg1)
	stop = OS.get_ticks_msec()
	test_time = stop-start
	
	var threads = []
	threads.append( Thread.new() )
	threads.append( Thread.new() )
	threads.append( Thread.new() )
	threads.append( Thread.new() )
	start = OS.get_ticks_msec()
	for i in range(test_count):
		threads[i].start(self, "test_multi", arg1)
	threads[0].wait_to_finish()
	threads[1].wait_to_finish()
	threads[2].wait_to_finish()
	threads[3].wait_to_finish()
	stop = OS.get_ticks_msec()
	test_multi_time = stop-start

	
	print("test : ", test_time)
	print("test multi: ", test_multi_time)
	print("ratio: ", float(test_multi_time)/test_time)
	

func test(arg1):
	var acc = 0
	for i in range(arg1):
		acc +=1
	return acc

func test_multi(arg1):
	var acc = 0
	for i in range(arg1):
		acc +=1
	return acc
```

**Link to minimal example project:**
:

**Comment by Zylann** [comment]
Is there anything in these functions that cause a global mutex to be locked?
Or could it be that threads are not evenly distributed, causing the overhead you are experiencing?

**Comment by Maveyyl** [comment]
What does trigger the global mutex lock?

You can see the functions in my example.

**Comment by reduz** [comment]
Godot 3.0 improves locking a lot already, would be interesting to check
there

**Comment by Zylann** [comment]
About the global lock I meant internally, not directly in the script. I was just suggesting because I saw that in several places of the engine, I have no idea if that script would involve such locking, probably not

**Comment by Maveyyl** [comment]
I've tried with 2, 3, 4, 8 threads. On a Quad-core, and another Quad-core with hyperthreading. The function is executed slower than normally in all cases.

**Comment by volzhs** [comment]
Godot 3.0 master 903a3aa / Ubuntu 16.04.1 / Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz - quad core
I got this result with sample code.
```
test : 183
test multi: 291
ratio: 1.590164
```

**Comment by razvanc-r** [comment]
@volzhs what do the numbers represent? Is it the time per function or the total running time of the program? in ms (I assume - if it's time)? if this is correct it means that in all cases the thread test is slower. How many threads did you use for `test_multi`? so many questions... :) you need better presentation :P

**Comment by Maveyyl** [comment]
@razvanc-r this is what the script I posted outputs. This is the total execution time. To see the time per function you need to use the profiler.

In his scenario, he uses 4 threads (like exposed in the script) and has a quad-core. In his case the multithreaded function is always slower to execute.

**Comment by razvanc-r** [comment]
Oright, I took your code and changed it to:

```py
extends Node

func _ready():
	var test_count = [1, 2, 4, 8, 10, 12]
	var arg = [10000, 50000, 100000, 5000000, 10000000]
	var start
	var stop
	var test_time
	var test_multi_time

	print('threads,arg,time_single,time_multi,time_multi/time_single')
	for tc in test_count:
		for a in arg:
			start = OS.get_ticks_msec()
			for i in range(tc):
				test(a)
			stop = OS.get_ticks_msec()
			test_time = stop-start

			var threads = []
			for i in range(tc):
				threads.append(Thread.new())
			start = OS.get_ticks_msec()
			for i in range(tc):
				threads[i].start(self, "test", a)
			for i in range(tc):
				threads[i].wait_to_finish()
			stop = OS.get_ticks_msec()
			test_multi_time = stop-start

			print(tc, ',', a, ',', test_time, ',', test_multi_time, ',', float(test_multi_time)/test_time)

func test(arg):
	var acc = 0
	for i in range(arg):
		acc += 1
	return acc
```

These are the results:
![v3 5e3fc7d06956 csv](https://cloud.githubusercontent.com/assets/1177508/23101635/5bc1c690-f698-11e6-9ac4-01ba30ae4cb2.png)
![v2 1 2 csv](https://cloud.githubusercontent.com/assets/1177508/23101639/6021e10c-f698-11e6-9ef1-8d34f033de04.png)

And here is the python script to make the plots:

```py
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

for f_name in ('v3.5e3fc7d06956.csv', 'v2.1.2.csv'):
    d = pd.read_csv(f_name)
    g = sns.FacetGrid(d, col='threads', hue='threads', col_wrap=3)
    g = (g.map(plt.axhline, y=1, ls=':', c='.5')
          .map(plt.plot, 'arg', 'time_multi/time_single', marker='o', ms=4)
          .set_axis_labels('arg', 't$_{M}$/t$_{S}$')
          .set(xlim=(1e4, 1e7), xscale='log'))
    g.fig.tight_layout(w_pad=1, rect=(0, 0, 1, 0.95))
    g.fig.suptitle(f_name)
    g.fig.savefig(f_name + '.png')
```

**Comment by hsdxpro** [comment]
Just rewrite the multithreading using fiber based job systems, and you will save tons of sync points + performance heavy kernel context switches. And the engine will not struggle on a 16 - 32 core machine in the near future.

**Comment by fire** [comment]
The performance hasn't changed. I tried c++ and gdscript.

Although the algorithm isn't work-stealing, it should be able to do the number of threads multiples of the single threaded version.

Any ideas?

**Comment by MightyPrinny** [comment]
I've noticed problems with threads only on windows, I have only two threads and the second thread slows down the main thread, this doesn't seem to happen on linux.

**Comment by fire** [comment]
The slowdown happens when you sync. 

wait_to_finish() slows things down. If you use a locked dictionary that sends to state of the queue, it runs better.

**Comment by MightyPrinny** [comment]
> The slowdown happens when you sync.
> 
> wait_to_finish() slows things down. If you use a locked dictionary that sends to state of the queue, it runs better.

yeah turns out the audio server was being locked, I only realized it when I read the source code of AudioSample, I'll have to make a gdnative lib with it's own audio player to do what I want

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/58279, which is a more up-to-date issue on the problem.
