### ISSUE TITLE
Control node anchors doesn't work inside a CanvasGroup

### ISSUE THREAD

**Issue by shBLOCK** [godotengine/godot#78337]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

(Irrelevant)

### Issue description

See #18166 for the exact cause.
With CanvasGroup though, I can't find an easy (not too messy) workaround since the CanvasGroup seems to ignore everything that's not a CanvasItem.

This issue makes it really hard to incorporate CanvasGroups into guis, which it's very useful for shader-based gui animations (the SubViewport approach doesn't play well with scaling).

I don't think many projects (if at all) is depending on the current behavior, so it's probably safe to just make the CanvasGroup a special case and let it pass the get_anchorable_rect() calls to its parent instead (or at least make this an option).

### Steps to reproduce

1. Create a new UI scene
2. Add a CanvasGroup
3. Add a control node as a child of the CanvasGroup
4. Try changing the control node's anchors

### Minimal reproduction project

![Godot_v4 1-beta1_win64_LHn8e4nCuQ](https://github.com/godotengine/godot/assets/50770712/c562002e-2b6a-4efe-b10c-5796b6e51768)

**Comment by AThousandShips** [comment]
Please see https://github.com/godotengine/godot/issues/18166#issuecomment-632404046

**Comment by shBLOCK** [comment]
Can we expose the get_anchorable_rect() function to be overridable via gdscript?
I'm not sure if that's going to be a performance issue or something.

**Comment by shBLOCK** [comment]
Okay, I guess there is a workaround for this.
I can use a dummy Control node with a script attached to sync its position and size with another Control node.
But it's still annoying since an extra layer of dummy node is involved.
![Godot_v4 1-beta1_win64_vPk5eiEclr](https://github.com/godotengine/godot/assets/50770712/04c46450-9f32-4c8d-8c0c-25cd61d14a94)

> Can we expose the get_anchorable_rect() function to be overridable via gdscript? I'm not sure if that's going to be a performance issue or something.
I've also tried to implement this, it kinda works, but it seems like the layout update doesn't propagate through a Node2D, which needs to be taken into account if someone wants to implement this. (I'm not familiar with C++ so I just imitated how it is done in other places, but I can't get things like editor support working, so I'm probably not gonna make a PR of this)

**Comment by AThousandShips** [comment]
I'd suggest opening a PR for this, either this specially or the more general topic in #18166, as it isn't necessarily a bug, and more importantly the specifics of how to accomplish it needs to be discussed and the proposals are much better suited to that, partially because we get far more issue reports than proposals and it's easy for this one thing to be drowned out by that

**Comment by AThousandShips** [comment]
* Closing in favour of https://github.com/godotengine/godot-proposals/issues/7102
