### ISSUE TITLE
Port raycast module to Embree 4

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#78332]
### Godot version

4.1.beta (598378513b256e69e9b824c36136774c41cc763c)

### System information

All

### Issue description

The `raycast` module uses the thirdparty Embree library, currently version 3.13.5.

Upstream released Embree 4 as a new major, compatibility breaking release, and we need to adapt our usage of the library API if we want to use it.

The current latest version is 4.1.0. Release notes:
- https://github.com/embree/embree/releases/tag/v4.0.0
- https://github.com/embree/embree/releases/tag/v4.1.0

#73631 was an attempt at adding support for both majors at the buildsystem level, but due to the API changes the embree4 variant wouldn't compile at all so I abandoned it.

Doing this upgrade is not urgent, and once evaluating it we might find reasons not to (e.g. I see 4.1.0 just re-added support for Linux ARM64 which 3.13.5 already had, so there might be other such downgrades for our use case). Anyone is welcome to have a look.

**Comment by quirkylemon** [comment]
Can I go ahead and attempt this? it probably won't go well but I might as well try.

**Comment by Calinou** [comment]
> Can I go ahead and attempt this? it probably won't go well but I might as well try.

Sure, feel free to open a pull request for this :slightly_smiling_face:

However, we aim to replace Embree with a simpler BVH/software raytracing implementation in the long run such as https://github.com/madmann91/bvh or https://github.com/lighttransport/nanort. This will allow decreasing binary size and compile times significantly, as Embree is a large, complex library.

**Comment by quirkylemon** [comment]
How long will it be until Embree is replaced?

**Comment by Calinou** [comment]
> How long will it be until Embree is replaced?

There's no ETA for replacing Embree, so I don't know.

**Comment by quirkylemon** [comment]
So currently it looks like we need to manually update `cpp_files[]` and `include_dirs[]` in `godot_update_embree.py` would it be helpful to include the script I am writing to automatically make these lists?

**Comment by akien-mga** [comment]
Probably not - those lists are written manually because we want to have precise control over which files we build, and not build any file that we don't need. It's the same for all thirdparty libraries, we trim them down to only include and compile what we will actually use.

**Comment by quirkylemon** [comment]
This was project is to hard for me right now. so I am going to give up.

**Comment by Chubercik** [comment]
> However, in the long run, we aim to replace Embree with a simpler BVH/software raytracing implementation such as https://github.com/madmann91/bvh or https://github.com/lighttransport/nanort. This will allow decreasing binary size and compile times significantly, as Embree is a large, complex library.

What about performance?

![image](https://github.com/godotengine/godot/assets/37378746/a400f03b-2921-4562-b010-bd31a4e64a8d "https://raw.githubusercontent.com/madmann91/bvh/master/chart.png")

(_source: https://github.com/madmann91/bvh?tab=readme-ov-file#performance_)

From what I understand, Embree is the fastest solution out of the (popular) available ones (at least it was in version 3, no idea how 4 compares, but I wouldn't expect much of a regression in this area).

**Comment by Calinou** [comment]
@Chubercik It's true that Embree is generally faster across the board, but smaller binary size and maintainability is something that tends to be valued a lot in Godot.
