### ISSUE TITLE
GridMap mesh "Cast Shadow" ignored

### ISSUE THREAD

**Issue by jerbrisebois** [godotengine/godot#78344]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10

### Issue description

GridMap meshinstances with "Cast Shadow: Off" in a 3D scene with a directional light that has "Shadow Enabled: On" will cast shadows.

### Steps to reproduce

Create a 3D scene with a MeshInstance3D plane (to receive the shadow) a GridMap, a DirectionalLight3D and a camera (to view the scene while playing).

Create a 3D scene with a MeshInstance3D cylinder (or any other shape to cast a shadow). In the GeometryInstance3D properties set "Cast Shadow" to "Off". Export the scene as a Mesh Library.

Back in the original scene, set up the GridMap to use the mesh library and add an instance of the mesh library shape in close proximity to the plane. In the DirectionalLight3D under "Light3D>Shadow", set "Enabled" to "On". Adjust the rotation so it will cause the mesh library mesh to cast a shadow on the plane.

Both in the editor and in the game the mesh library mesh will cast a shadow even though it is set to "Off".

### Minimal reproduction project

[GridmapShadow.zip](https://github.com/godotengine/godot/files/11772583/GridmapShadow.zip)

**Comment by smix8** [comment]
GridMap inherits Node3D and has no `cast_shadow` property, neither do the Mesh items in the MeshLibrary.
The property `cast_shadow` is part of the GeometryInstance3D class used by single visual instances.
Strictly technical there is also no such thing as an individual GridMap MeshInstance as it uses MultiMeshes.

Since GridMap uses Mesh resources from a MeshLibrary inside MultiMeshInstance(s) the only possible place to toggle shadows for the cell items would be through the individual MultiMeshInstances.

This would require additional properties to be added to the MeshLibrary items, as well as modifications of the GridMap internals and the Editor MeshLibrary scene exporter.

**Comment by Calinou** [comment]
MultiMeshInstance doesn't allow toggling shadow casting for a single instance, so this probably can't be fixed without increasing draw call count by using multiple multimeshes (one per shadow casting type, and one per quadrant).

**Comment by jerbrisebois** [comment]
And is it not possible to access the MultiMesh itself without modifications to the engine? Happy to do it in code but so far my digging hasn't produced anything. I'd be fine disabling shadows on all the multimesh instances.

**Comment by Calinou** [comment]
The MultiMeshInstance3D node inherits from GeometryInstance3D, which has a Cast Shadow property. However, GridMap inherits from Node3D and creates an internal MultiMesh without relying on the MultiMeshInstance3D node directly (it uses [low-level servers and RIDs](https://docs.godotengine.org/en/latest/tutorials/performance/using_servers.html)).

It should be technically possible to expose a **Cast Shadow** property in GridMap, but it's probably not easy.

**Comment by jerbrisebois** [comment]
> It should be technically possible to expose a **Cast Shadow** property in GridMap, but it's probably not easy.

Yeah, tried to handle this myself but it was my first venture into the engine code and .. it did not go well. I'll wait to see if this can be addressed by someone more proficient. I feel that GridMap is not a very commonly used module though so I won't hold my breath

**Comment by jerbrisebois** [comment]
Oops,. I figured out what the "close with comment" button does..

**Comment by Janders1800** [comment]
I never touched Godot code but cant be plugged this somewhere inside a foor loop for setting the multimesh shadows?

```
for (int i = 0; i < g.multimesh_instances.size(); i++)
{
		RS::get_singleton()->instance_geometry_set_cast_shadows_setting(g.multimesh_instances[i].instance, RS::ShadowCastingSetting::SHADOW_CASTING_SETTING_OFF)
}
```

**Comment by Calinou** [comment]
> I never touched Godot code but cant be plugged this somewhere for setting the multimesh shadows?

It can, but it requires adding a new property to GridMap and hiding the GeometryInstance3D Cast Shadow property in GridMap.

**Comment by Janders1800** [comment]
I don't understand, there is no GeometryInstance3D in Gridmap.

**Comment by Janders1800** [comment]
Ok, I've been trying things and nothing works, I can't manage to hide the GridMap shadows. So I've made a script that bakes the GridMap into a MeshInstance.

For now this will do for me.

_**NOTE:** This script will only work on 3.X, but it should be fairly easy to convert to 4.X_

```
tool
class_name StaticGridMap extends GridMap


export (bool) var btn_bake_meshes: bool setget bake_meshes


var material_counter: int

func bake_meshes(value):
	var data: Array = get_meshes()
	material_counter = 0
	
	if data:
		var new_mesh := ArrayMesh.new()
		var data_transform: Transform
		
		var baked_mesh := MeshInstance.new()
		get_parent().add_child_below_node(self, baked_mesh)
		baked_mesh.owner = get_tree().edited_scene_root
		
		for mesh_data in data:
			if mesh_data is ArrayMesh:
				new_mesh = extract_mesh(mesh_data, new_mesh, data_transform)
			else:
				data_transform = mesh_data
		
		new_mesh = combine_materials(new_mesh)
		
		baked_mesh.mesh = new_mesh
		baked_mesh.name = "Baked_" + name
		hide()


func extract_mesh(old_mesh: ArrayMesh,new_mesh: ArrayMesh ,mesh_transform: Transform):
	for i in range(old_mesh.get_surface_count()):
		var data = old_mesh.surface_get_arrays(i)
		var offset: PoolVector3Array = data[ArrayMesh.ARRAY_VERTEX]
		
		for o in range(offset.size()):
			offset.set(o, mesh_transform.basis.xform(offset[o]) + mesh_transform.origin)
		
		data[ArrayMesh.ARRAY_VERTEX] = offset
		
		new_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, data)
		new_mesh.surface_set_material(material_counter, old_mesh.surface_get_material(i))
		material_counter +=1
		
		return new_mesh


func combine_materials(mesh: ArrayMesh) -> ArrayMesh:
	var result_mesh := ArrayMesh.new()
	var mat_counter := 0
	var materials: Array
	
	for i in range(mesh.get_surface_count()):
		if not materials.has(mesh.surface_get_material(i)):
			materials.append(mesh.surface_get_material(i))
	
	for mat in materials:
		var surf_tool := SurfaceTool.new()
		
		for i in range(mesh.get_surface_count()):
			if mat == mesh.surface_get_material(i):
				surf_tool.append_from(mesh, i, transform)
		
		result_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, surf_tool.commit_to_arrays())
		result_mesh.surface_set_material(mat_counter, mat)
		mat_counter += 1
	
	return result_mesh
```

**Comment by Calinou** [comment]
> GridMap should inherit from GeometryInstance really.

Changing inheritance is a compatibility-braking change if I'm not mistaken.

**Comment by tetrapod00** [comment]
This was implemented by https://github.com/godotengine/godot/pull/85443, but not auto-closed.
