### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#7836]
**Operating system or device - Godot version:**
Godot version 2.1.2 Linux XUbuntu 16.04.1

**Issue description:**

Hi, I'm getting an suspicious behavior in a sub scene. Description:
When add an new scene named Barrier (an StaticBody2D with a sub child collision shape being a RectangleShape2D) it doesn't collide properly like it should. For example, if the player enter the Barrier shape in the right or the left or down side, the collision doesn't work. But, if the player enter by the top side of shape, so it collide with shape and the behavior is a collision. This kind of behavior of my Barrier with player it's like an One-way-platform, but I want that Barrier with full side collision.

I've try load my Barrier.tscn in other new project test, and... it works! Only in my main project do not. 
For this, I suspected be a bug.

**Steps to reproduce:**
I don't know the exactly steps, but it occurs in my project only.

**Link to minimal example project:**
If you want my project to give a try, download here:
https://www.dropbox.com/s/cz283ewraqcbwok/MeuPlatformer.tar.gz?dl=0
#

**Comment by eon-s** [comment]
You have set the one way collision on the vuxbody.gd script, on ready

**Comment by sam-leo** [comment]
hum, ok, please, can you give the number line? I've tried fix this error but I can't see trough my certainties. It's the first time learn godot

**Comment by eon-s** [comment]
@sam-leo line 235 of vuxbody.gd, the collision direction is set to (0,1)

**Comment by sam-leo** [comment]
@eon-s you are foda! (foda in pt_BR is like badass in English hehe)
Thank you man
