### ISSUE TITLE
Delay between debugger start and game first render of empty project

### ISSUE THREAD

**Issue by alexamy** [godotengine/godot#78369]
### Godot version

v4.0.3.stable.arch_linux

### System information

Arch Linux, Forward+, GeForce RTX 3060, NVIDIA driver 535.54.03, Vulkan 1.3.253

### Issue description

When running empty project:
1. Game window opens
2. "_--- Debugging process started ---_" is printed in console
3. **5-6 seconds passes**
4. Game first render happens

The delay before first render is a problem. 
I had Forward+ renderer as default. Strangely, if I switch renderer to Mobile / Compatible, and then back to Forward+ (which causes editor to restart), the delay disappears. If I close and open Godot manually, delay will be there again.

Video - First start of the project:
https://github.com/godotengine/godot/assets/596195/b85d3749-a654-4eca-a892-cfee7e015dde

Video - Start of the project after switching render to Compatible, when back to Forward+:
https://github.com/godotengine/godot/assets/596195/bb28b2a0-dd17-48dd-bfd0-24ff5313cea2

### Steps to reproduce

I dont know how to reproduce on other computer than mine.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/74292.

**Comment by alexamy** [comment]
@Calinou I've read some of the #74292, and checked this issue on `4.1 beta2`. Startup time is consistent between renderers and dont depend on godot restart or renderer switch.
It may be _**a little**_ slower overall, around 500 - 1000 ms vs 100 - 300 ms on stable build (without this issue bug). But it is my subjective thought, I dont know how to measure startup time exactly.

**Comment by Calinou** [comment]
> But it is my subjective thought, I dont know how to measure startup time exactly.

You can run the Godot project directly from the [command line](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) with the `--startup-benchmark` (4.0.3) or `--benchmark` (4.1) CLI argument.

**Comment by alexamy** [comment]
@Calinou Looks like it is measuring start time of the Godot itself. But I want to measure time between clicking "Play scene" button and first render of the project.

**Comment by Calinou** [comment]
> But I want to measure time between clicking "Play scene" button and first render of the project.

Running the project directly from the command line with `--quit` should do that well, although keep in mind that shutdown time will be taken into account too (if using the `time` method).

**Comment by alexamy** [comment]
With GL compatibility renderer:
4.0.3:
```
Godot Engine v4.0.3.stable.arch_linux - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 535.54.03 - Compatibility - Using Device: NVIDIA Corporation - NVIDIA GeForce RTX 3060
 
STARTUP BENCHMARK:
        - core :  0.00654  sec.
        - servers :  0.502533  sec.
        - scene :  0.069515  sec.
        - load_autoloads :  0  sec.
        - game_load :  0.005164  sec.
        - total_time :  0.584156  sec.
```

4.1 beta2:
```
Godot Engine v4.1.beta2.official.a2575cba4 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 535.54.03 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3060
 
BENCHMARK:
        - register_core_types :  0.003841  sec.
        - servers :  0.311025  sec.
        - register_editor_types :  0.001041  sec.
        - scene :  0.060893  sec.
        - load_autoloads :  0.000001  sec.
        - game_load :  0.005316  sec.
        - startup_begin :  0.383869  sec.
        - unregister_editor_types :  0.000002  sec.
        - unregister_core_types :  0.024608  sec.
        - Main::cleanup :  0.784555  sec.                                                
```

**Comment by alexamy** [comment]
```
Godot Engine v4.1.stable.arch_linux - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060
 
BENCHMARK:
        - register_core_types :  0.004101  sec.
        - servers :  0.772235  sec.
        - register_editor_types :  0.001086  sec.
        - scene :  0.069374  sec.
        - load_autoloads :  0  sec.
        - game_load :  0.015401  sec.
        - startup_begin :  0.863981  sec.
BENCHMARK:
        - register_core_types :  0.004101  sec.
        - servers :  0.772235  sec.
        - register_editor_types :  0.001086  sec.
        - scene :  0.069374  sec.
        - load_autoloads :  0  sec.
        - game_load :  0.015401  sec.
        - startup_begin :  0.863981  sec.
        - unregister_editor_types :  0.000001  sec.
        - unregister_core_types :  0.019195  sec.
        - Main::cleanup :  0.239296  sec.
```
