### ISSUE TITLE
sample_baked_with_rotation gives wrong transform

### ISSUE THREAD

**Issue by 0xafbf** [godotengine/godot#78361]
### Godot version

4.0.3.stable

### System information

Windows 10

### Issue description

evaluating a curve's `sample_baked_with_rotation` gives wrong Transform2D:

https://github.com/godotengine/godot/assets/1028756/078552a4-3965-4d36-9446-022054ade672

The texture should read A B C D correctly, you can see it flips the texture vertically

It is trying to match textures *Positive Y* to the path direction, and then *positive x* to the right of the path.

I think the two correct options would be:
* map *negative y* (which would be *up*) to the path direction
* map *positive x* to the path direction (which I would like better, but would like to know your opinion)

I found this while working on this PR https://github.com/godotengine/godot/pull/77819
I could give a shot at fixing this during the weekend

### Steps to reproduce

Just run the example project

### Minimal reproduction project

[PathSampleBug.zip](https://github.com/godotengine/godot/files/11778276/PathSampleBug.zip)

**Comment by AThousandShips** [comment]
I think this is because you are using the wrong coordinate system, see [here](https://docs.godotengine.org/en/stable/tutorials/math/vector_math.html#coordinate-systems-2d), you seem to be using a left handed coordinate system as opposed to a right handed one

**Comment by AThousandShips** [comment]
Will look into it, yes, it seems to flip the axes

**Comment by AThousandShips** [comment]
It appears the transform returned from the `Curve2D` is not a real transform, as the documentation shows to extract origin and rotation, but should be clearer, it works if you do:
```gdscript
target.position = tx.get_origin()
target.rotation = tx.get_rotation()
```

**Comment by capnm** [comment]
> It appears the transform returned from the Curve2D is not a real transform, as the documentation shows to extract origin and rotation, but should be clearer, it works if you do:

I'm not sure what you exactly mean.  The negative y-scale in transform seems to be the culprit or bug here...

print(tx.get_scale())
(1, -1)

I.e. this works as expected:
```
target.transform = curve.sample_baked_with_rotation(distance)
target.scale = Vector2(1,1)

**Comment by AThousandShips** [comment]
I mean no that gives a different result than the behaviour of `PathFollow2D`

**Comment by capnm** [comment]
I haven't had time to read/decipher the corresponding code. Other practical question, why it here manipulates the **scale** of the  target transform at all?

**Comment by AThousandShips** [comment]
This is as I said because it swaps the X and Y axes, meaning that it no longer follows the right hand convention, by default the Y axis is 90 degrees clockwise of the X axis, but in this case it is counter clockwise, because of the swapped axes

**Comment by capnm** [comment]
Thanks a lot. I'm starting to not know what my left and right hands are in the matrix.  :arrows_clockwise: :repeat: :arrows_counterclockwise:  Godot obviously prefers 3D and 2D objects from behind :) Personally, I would rather break whatever compatibility and fix it once forever ...

**Comment by AThousandShips** [comment]
No problems! I had a hard time getting my head around it for a while, and my right wrist is all sore from trying to work out the left and right hand rules, note that 3D in Godot is right hand, but 2D is left hand, very confusing 

Unfortunately we can't do that, at least not for some time, I suspect not until 5.0 as it's an easy thing to resolve with documentation clarification, and doesn't break anything, as long as you compensate for it, you don't really need the whole transform anyway as it doesn't scale or skew, we could just return a `Vector3` with a rotation alone

See if the documentation update in the linked PR is clear to you if you wouldn't mind

**Comment by 0xafbf** [comment]
I just tried the PathFollow2D Node and it indeed does what I expected to do. I guess I didn't try it because I was focused on the text transform effect PR.

I think we should just make this function just return a good transform and match the behavior of PathFollow2D. I get the idea of using a Transform2D and then reading Y and X axis as forward and right, but the convenience of just using the transform to slap it into some visual element is too good to let it pass.

I like that it chooses X+ for forward. , as it is my preferred way of solving the problem. It makes it seamless to integrate with the work I did in the linked PR for flowing the text over a path.

I think that, given the use case is currently broken, and the docs previously had no suggestion on how to use this. I feel we should do an appropiate fix now instead of documenting the quirkiness of current implementation.

I can do a PR later today or tomorrow with my suggested fix.

**Comment by AThousandShips** [comment]
The docs did have the proposal yes

This is a compatibility breaking change so I don't think it's going to be merged any time soon, at the very earliest for 4.2

**Comment by capnm** [comment]
Also you mean that fixing the **sample_baked_with_rotation** output transform would break something else?
```diff
diff --git a/scene/resources/curve.cpp b/scene/resources/curve.cpp
index 12ee36654d..bf3256a9c3 100644
--- a/scene/resources/curve.cpp
+++ b/scene/resources/curve.cpp
@@ -1025,6 +1025,8 @@ Transform2D Curve2D::sample_baked_with_rotation(real_t p_offset, bool p_cubic) c
        // 2. Sample rotation frame.
        Transform2D frame = _sample_posture(interval);
        frame.set_origin(pos);
+       frame.set_scale(Vector2(-1.0, 1.0));
+       frame.set_rotation(frame.get_rotation() + Math_PI);
 
        return frame;
 }
```

**Comment by AThousandShips** [comment]
It would break anyone's code that uses it, it would of course have to be adjusted in the code, like `PathFollow2D`

The change would instead be in the `_sample_posture`, swapping the order of the arguments

**Comment by capnm** [comment]
>  It would break anyone's code that uses it ...

If it`s broken, I doubt someone will actually use it directly?

**Comment by AThousandShips** [comment]
It isn't broken, it's just weird, you can use it fully

**Comment by AThousandShips** [comment]
> If it breaks the use case (see in the Minimal reproduction project)

It breaks *any* usecase, `get_rotation()` on the returned transform is *different* when using the corrected version

**Comment by capnm** [comment]
target.transform = curve.sample_baked_with_rotation(distance)
or
var tx = curve.sample_baked_with_rotation(distance)
target.position = tx.get_origin()
target.rotation = tx.get_rotation()

Works here in the MRP with same expected result.

**Comment by AThousandShips** [comment]
Not given the expected results of `PathFollow2D`, the expected results would be for it to be facing up on a flat curve, no? Which is what you get from the current code with `get_rotation`

**Comment by AThousandShips** [comment]
Realized that I had misinterpreted how it was used here, so changed the description in the documentation PR, a change to how the current implementation works would be good, but I still argue it would have to be delayed with consideration for compatability breaking

**Comment by 0xafbf** [comment]
As you suggested, this does it for me
```diff
-	return Transform2D(side, forward, Vector2(0.0, 0.0));
+ 	return Transform2D(forward, side, Vector2(0.0, 0.0));
```

I agree that it breaks behavior for current users, but I also think that the sooner this gets fixed the better. 

> Not given the expected results of PathFollow2D, the expected results would be for it to be facing up on a flat curve, no?
I think this is debatable, and it ends up being a lot about preference. 

> I'm not sure what the expected result is here, but it isn't:

Why? there are many arguments in favor of this:
- It is what PathFollow2D does. 
- It applies the least amount of transform for the simplest use case for example: a straight path from left to right wouldn't introduce any rotation.
- not rotating an element in a left-to-right path would follow the principle of least surprise
- nicely maps a positive value to a positive movement in an axis
- if used for procedurally placing content, things such as trees-fences wouldn't be awkardly facing forward, but instead would naturally face up
- it reduces the amount of code I need to write to lay out text with transforms in my other PR

Arguments in favor of keeping up as forward:
- In top-view games people draw sprites with forward as up


In the end, if needed, rotation can be introduced by the user (although this applies both sides)

Overall I think this fix is kind-of critical for good performance, because using the `get_rotation()` function uses trigonometry and assigning it back to the object uses trigonometry again, which may be a concern when placing hundreds of items by code (which is what could happen with the text transform PR)

**Comment by AThousandShips** [comment]
Agreed, realized that a scaling issue with the MRP caused me to fail to realize that the code as current does pointing along the path, not across it, as I thought, I was confused as to this part

**Comment by capnm** [comment]
> In top-view games people draw sprites with forward as up

Flat-universe games people too.  MRP + ship & rocket :) 
[78361-PathSample2.zip](https://github.com/godotengine/godot/files/11780872/78361-PathSample2.zip)
