### ISSUE TITLE
Label outline not following the text

### ISSUE THREAD

**Issue by NandoBroquiGames** [godotengine/godot#78366]
### Godot version

4.0,3

### System information

Windows 10

### Issue description

For some reason, the outline of the letter "B" of the text "Blobs" on the label named "points" is not following the text. I was converting my game to Godot 4 when this bug happened, have no idea why it is happening and how to fix it.

![label_outline_not_following_text](https://github.com/godotengine/godot/assets/130227631/d47a86fc-6fd8-40cb-afa3-5805a6373b12)

### Steps to reproduce

- Download the files of the Scene, Script and Text font(located on Minimal reproduction project)
- Fix the Scene and Script dependencies(if some dependencies are not in the zip file it's because i think they will not be important)
- Make a scene that the camera can go up and add the Hud scene to it
- Watch the bug

### Minimal reproduction project

Here are the files:
[textoutlinebug_files.zip](https://github.com/godotengine/godot/files/11778870/textoutlinebug_files.zip)

**Comment by AThousandShips** [comment]
Your minimum reproduction project is incomplete, you need to include the `project.godot` file as per the instructions, please do this next time to make this easier

**Comment by NandoBroquiGames** [comment]
> Your minimum reproduction project is incomplete, you need to include the `project.godot` file as per the instructions, please do this next time to make this easier

**Comment by NandoBroquiGames** [comment]
> Your minimum reproduction project is incomplete, you need to include the `project.godot` file as per the instructions, please do this next time to make this easier, it also won't run as you have removed parts that are needed, for example `res://scenes/misc_scenes/gameover.tscn`

Isn't it possible to make the Bug without the project?(Just creating a new project and importing the stuff), i also mentioned that some dependencies are not present because i think it should have no importance with the bug, those dependencies should be fixed manually, change it to another think just to debug.

**Comment by NandoBroquiGames** [comment]
> Your minimum reproduction project is incomplete, you need to include the `project.godot` file as per the instructions, please do this next time to make this easier, it also won't run as you have removed parts that are needed, for example `res://scenes/misc_scenes/gameover.tscn`, and seemingly a bunch of autoloads

So, sorry for not completing the requirements, i just tried now to create a project to replicate the bug but it's not happening, maybe i need to send the game's project to someone, but i'm scared of someone steeling my game, is there anyone trustable here? Again, sorry 😅

**Comment by AThousandShips** [comment]
If you are unable to make a project that shows this bug then we can't really help, and we can't just investigate your whole game so you need to remove everything unrelated and make it into a project you can show, what you keep in it is your choice, just as long as it actually works and shows the bug.

At minimum it needs to be possible to run it, and for the bug to show up. In your case the required parts are:
* `project.godot`, remove any autoloads or similar that use things that aren't included
* A scene that displays the error or bug

You can remove anything you're concerned will be stolen, and you need to remember that *you* might violate copyright by uploading things here if you have a limited licence, for example if you bought a font or image somewhere and you did not get the right to give it away to anyone.

If you are unable to do this we unfortunately can't help

To make *sure* that it works, please open the project yourself before uploading it, to prevent any issues

**Comment by NandoBroquiGames** [comment]
> If you are unable to make a project that shows this bug then we can't really help, and we can't just investigate your whole game so you need to remove everything unrelated and make it into a project you can show, what you keep in it is your choice, just as long as it actually works and shows the bug.
> 
> At minimum it needs to be possible to run it, and for the bug to show up. In your case the required parts are:
> 
> * `project.godot`, remove any autoloads or similar that use things that aren't included
> * A scene that displays the error or bug
> 
> You can remove anything you're concerned will be stolen, and you need to remember that _you_ might violate copyright by uploading things here if you have a limited licence, for example if you bought a font or image somewhere and you did not get the right to give it away to anyone.
> 
> If you are unable to do this we unfortunately can't help
> 
> To make _sure_ that it works, please open the project yourself before uploading it, to prevent any issues

Ok, i'll try to replicate the bug again.

**Comment by NandoBroquiGames** [comment]
> If you are unable to make a project that shows this bug then we can't really help, and we can't just investigate your whole game so you need to remove everything unrelated and make it into a project you can show, what you keep in it is your choice, just as long as it actually works and shows the bug.
> 
> At minimum it needs to be possible to run it, and for the bug to show up. In your case the required parts are:
> 
> * `project.godot`, remove any autoloads or similar that use things that aren't included
> * A scene that displays the error or bug
> 
> You can remove anything you're concerned will be stolen, and you need to remember that _you_ might violate copyright by uploading things here if you have a limited licence, for example if you bought a font or image somewhere and you did not get the right to give it away to anyone.
> 
> If you are unable to do this we unfortunately can't help
> 
> To make _sure_ that it works, please open the project yourself before uploading it, to prevent any issues

I did it! I recreated the bug on a separated project! YAyyyYyYyYyyyyYYYyYYy

**Comment by arkology** [comment]
I think I know that happens. Try to change children order in your hud and see what happens.
And then try to switch to Compatibility renderer👀

**Comment by NandoBroquiGames** [comment]
> I think I know that happens. @NandoBroquiGames Try to change children order in your hud and see what happens. And then try to switch to Compatibility renderer👀

Ok, I'll try that. But what is the logic? And also, ins't Compatibility renderer the same as GLES2 on Godot 3?(I heard that Godot 4 doesn't support it anymore but I'm asking due to the "colors" of each renderer)

**Comment by NandoBroquiGames** [comment]
> I think I know that happens. @NandoBroquiGames Try to change children order in your hud and see what happens. And then try to switch to Compatibility renderer👀

OMG! Thanks! This actually worked. I just changed to compatibility and it worked!

**Comment by akien-mga** [comment]
I can't reproduce the bug myself with the attached project (on Linux with AMD GPU), but if you still reproduce the bug on your device with the Vulkan renderer, this would still be a bug that we need to resolve.

**Comment by NandoBroquiGames** [comment]
> I can't reproduce the bug myself with the attached project (on Linux with AMD GPU), but if you still reproduce the bug on your device with the Vulkan renderer, this would still be a bug that we need to resolve.

I want to know what are the difference with the renderers. Like, what is the closest to Godot 3 "GLES3" renderer? I used mobile because I though it was the equivalent to that renderer.
Btw, should I reopen the report?

**Comment by NandoBroquiGames** [comment]
> * This is a duplicate of [Zero child of CanvasLayer (which is a child of Camera2D) may render with wrong transform [Windows, Intel HD 630 or lower] #58314](https://github.com/godotengine/godot/issues/58314).
> 
> > Like, what is the closest to Godot 3 "GLES3" renderer? I used mobile because I though it was the equivalent to that renderer.
> 
> The closest equivalent is Compatibility, not Mobile.

Ok, thank you!

**Comment by arkology** [comment]
> * This is a duplicate of [Zero child of CanvasLayer (which is a child of Camera2D) may render with wrong transform [Windows, Intel HD 630 or lower] #58314](https://github.com/godotengine/godot/issues/58314).

Yeah, my guess was right on target😄 Another day, another bug variation. This issue is getting more and more "popular", heh.
