### ISSUE TITLE
Export template error "There are no mirrors available"

### ISSUE THREAD

**Issue by Infini-Creation** [godotengine/godot#78375]
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Windows 7 64 bits

### Issue description

When trying to install export templates from Godot editor,

I got

> Error getting the list of mirrors.

error when opening the template manager and also when I click on "Download and install" button

and 

> There are no mirrors available.

for "open in web browser" and "copy Mirror URL" action.

Export template archive is located as the usual location:

https://downloads.tuxfamily.org/godotengine/4.1/beta2/Godot_v4.1-beta2_export_templates.tpz (this one may not work)

https://downloads.tuxfamily.org/godotengine/4.1/dev2/Godot_v4.1-dev2_export_templates.tpz (this one worked before)
https://downloads.tuxfamily.org/godotengine/4.1/dev4/Godot_v4.1-dev4_export_templates.tpz

install export templates from file work.

### Steps to reproduce

Open Godot editor
click on project/export
 try to load template from the web

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
@YuriSizov Seems like you forgot to copy the mirrorlist to the new website host (godotengine.org/mirrorlist).

**Comment by akien-mga** [comment]
I copied it manually from TF, should be fixed for now. We should discuss how we want to keep it properly synced going further.

**Comment by YuriSizov** [comment]
> We should discuss how we want to keep it properly synced going further.

I think we can just generate them with the website, it's all static information and we already track various version information with the website to generate download pages. I will implement it on Monday.

**Comment by FeralBytes** [comment]
Seeing this in 4.1.rc1.official.

**Comment by akien-mga** [comment]
That's weird, because the mirrorlist seems to be properly configured: https://godotengine.org/mirrorlist/4.1.rc1.json

**Comment by clayjohn** [comment]
GitHub was down for awhile earlier today. I wonder if that's the cause

**Comment by FeralBytes** [comment]
Retrying now. Yes it seems it was just temporary. Sorry about that. Thanks.

**Comment by rcorre** [comment]
I'm seeing this in `4.4.1.stable.arch_linux`. https://godotengine.org/mirrorlist/4.1.1.json does not seem to exist -- should it?

**Comment by YuriSizov** [comment]
> I'm seeing this in `4.4.1.stable.arch_linux`. https://godotengine.org/mirrorlist/4.1.1.json does not seem to exist -- should it?

The link would be https://godotengine.org/mirrorlist/4.4.1.stable.json.

**Comment by rcorre** [comment]
Ah, sorry, I typo'd. That link does in fact exist, yet the editor still cannot find them.

<img width="1096" height="573" alt="Image" src="https://github.com/user-attachments/assets/2956dbbf-923c-4e0b-ae42-173de16600f3" />

<img width="1089" height="522" alt="Image" src="https://github.com/user-attachments/assets/03a9ad48-f865-4c6d-81ad-84577a114d76" />

**Comment by celikj** [comment]
I also see it on 4.4.1.stable.arch_linux

**Comment by Calinou** [comment]
> I also see it on 4.4.1.stable.arch_linux

This is an unrelated issue:

- https://github.com/godotengine/godot/issues/107754

Using an official build, a self-compiled build or the Flatpak should avoid the issue.

See also https://github.com/godotengine/godot/issues/108952.
