### ISSUE TITLE
Godot chrashes with FATAL: Index p_index = 1 is out of bounds (size() = 0). when launching editor.

### ISSUE THREAD

**Issue by felanmalan** [godotengine/godot#78371]
### Godot version

v4.0.3.stable.flathub

### System information

Rhino linux (Based on ubuntu)

### Issue description

The editor chrashes when launching with the following error (Empty project):
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.3.stable.flathub (5222a99f5d38cd5346254cefed8f65315bca4fcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.3.stable.flathub (5222a99f5d38cd5346254cefed8f65315bca4fcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:155)
```

I expected it to not crash.

I am using the sway windowmanager.

### Steps to reproduce

1. Download the 4.0.3 flatpak version of Godot.
2. Launch it in swaywm
3. Choose a game to edit that has graphics higher than the compatibility setting.
4. Editor crashes 

It does not crash with the compatibility graphics.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> Choose a game to edit that has graphics higher than the compatibility setting.

What graphics card model do you have, and how recent are your graphics drivers?

**Comment by felanmalan** [comment]
I currently do not have acces to the device i got thet error on but i know i have a rather old gpu so that is probably the case.

**Comment by Calinou** [comment]
This is a duplicate of https://github.com/godotengine/godot/issues/58927, closing.
