### ISSUE TITLE
Editor subwindows disappear from view when attempting to interact

### ISSUE THREAD

**Issue by redpenguinyt** [godotengine/godot#78379]
### Godot version

4.0.3

### System information

Fedora 38 - Gnome - Wayland

### Issue description

when attempting to interact with the "add frames from spritesheet" menu of the spriteframes editor, the whole subwindow disappears from view. This makes adding frames impossible

[Screencast from 2023-06-17 21-05-03 (trimmed).webm](https://github.com/godotengine/godot/assets/79577742/4412f6c8-226a-40c1-ba14-68179c08c7ea)

attempting to switch to the window only leads back to the main godot window

this issue only takes place on the Wayland compositor, and doesn't happen in X11

### Steps to reproduce

on Linux running with the Wayland compositor, open the reproduction project, go to the AnimatedSprite and open the SpriteFrames menu. Press the "Add frames from sprite sheet" button, select the godot icon and attempt to change the number of horizontal or vertical frames in the Select Frames window

### Minimal reproduction project

[Reproduction Project.zip](https://github.com/godotengine/godot/files/11780067/Reproduction.Project.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/75515.

**Comment by adamscott** [comment]
> Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/75515.

Isn't this the wrong issue? It seems rather a duplicate of #77333
