### ISSUE TITLE
Missing functions asinh(), acosh() and atanh() (inverse hyperbolic functions) for GDScript

### ISSUE THREAD

**Issue by jynus** [godotengine/godot#78377]
### Godot version

4.0.3

### System information

any

### Issue description

GDScript has the following built-in trigonometry functions:

- `sin()`
- `cos()`
- `tan()`
- `asin()`
- `acos()`
- `atan()`
- `atan()`
- `sinh()`
- `cosh()`
- `tanh()`
 
However, it lacks the hyperbolic arc (also known as inverse hyperbolic) functions:

- `asinh()`
- `acosh()`
- `atanh()`
	

While this is not precisely an urgent issue-

C# contains a `Math.atanh()` function and it can be implemented in gdscript with:

    func atanh(x : float) -> float:
        """
        Implement missing arc tangent hyperbolic aka inverse of the
        tangent hyperbolic function, missing from Godot
        """
        return (float(1)/2 * log(float(1 + x)/float(1 - x)))

I think the lack of those 3 while implementing some, but not all trigonometric functions is a bit inconsistent. I personally needed `atanh()` to implement a catenary function (numerically simulate a rope).

Interestingly, the function is available for the Godot shader language, so it is not that of a weird request- it is useful for working with geometry.

I may try to implement these myself at a later time (as I am guessing either C++ have them or it is easy to implement them), but I want to file this because I was precisely working on a related Godot documentation and missed this feature, having to work around it.

References godotengine/godot-docs#7532

### Steps to reproduce

extends Node2D

func _ready():
    print(asinh(1))

-> Parser Error: Function "asinh()" not found in base self.

### Minimal reproduction project

[asinh.zip](https://github.com/godotengine/godot/files/11779841/asinh.zip)

**Comment by jynus** [comment]
For context, arc hyperbolic header functions were added to the shader language at #16794.

**Comment by dalexeev** [comment]
Feature requests should be opened here: https://github.com/godotengine/godot-proposals/issues. This tracker is for reporting bugs.

**Comment by jynus** [comment]
IMHO, I consider this a bug (albeit a very minor one), not a feature request- as there is a lack of consistency in the builin functions, and I intend to add the functionality myself. But I can close it if community disagrees, no problem.

**Comment by AThousandShips** [comment]
This is a feature request indeed, not a bug

**Comment by jynus** [comment]
Ok, sorry for the noise.

**Comment by AThousandShips** [comment]
No problem, make sure to follow the instructions when making a proposal, [here](https://github.com/godotengine/godot-proposals)

**Comment by jynus** [comment]
Marking it as "not a bug", not completed.

**Comment by jynus** [comment]
I would be glad if I could have your feedback on proposal godotengine/godot-proposals#7110, I've added a PR myself there. As it is very likely I have done something wrong again. 🫣
