### ISSUE TITLE
Vulkan: VoxelGI Indirect Lighting from Static Omni Light is broken until manually re-setting gi data in Rendering Server

### ISSUE THREAD

**Issue by Cammymoop** [godotengine/godot#78373]
### Godot version

4.0.3 stable, 4.1 beta 2

### System information

Windows 10 Vulkan forward+ Radeon RX 6700xt

### Issue description

VoxelGI doesn't seem to show any bounce light from a static baked omni light on loading a scene. This happens both in the editor and when running the game.

Immediately after baking the voxelGI data the bounce light is visible and working properly, but it breaks as soon as you reload the scene, switch to another scene tab in the editor, and is also broken in the game window when run.

Once the baked data exists and is saved to a resource file, the lighting can be fixed by simply using the "load" option on the VoxelGIData and selecting the file it's already assigned to.

Calling DisplayServer.instance_set_base() or just using the set_base() method of the voxelGI node to re-set the GI data works to fix the issue in a running game (after a short period of starting the game)

This does not happen with bounce lighting from directional lights. EDIT SpotLight3D also seems to be unaffected by this issue.
![il_scrnshots](https://github.com/godotengine/godot/assets/6477924/39a5129e-9a17-4498-b3f5-9fabac112c70)

### Steps to reproduce

Create new forward+ project

- In a 3d scene disable the preview sun and add 2 cube meshes positioned close enough to see bounce light.
- Add an omniLight3D set the bake mode to static and set the light energy high so that bounce light is easily visible, position it so that it doesn't directly illuminate the gap between the meshes.
- Add a VoxelGI node, create the voxelGIData resource and bake the GI
- bounce lighting is visible
- click Scene -> new scene, then click the tab to go back to the 3d scene with the GI
- bounce lighting is now gone
- bounce lighting is also not present when you run the scene

### Minimal reproduction project

[BrokenIL_MRP.zip](https://github.com/godotengine/godot/files/11779588/BrokenIL_MRP.zip)

The VoxelGI node in this scene has an exported checkbox that if selected does the fix of re-setting the gi data in the display server when the scene is run for comparison

**Comment by FelixNemis** [comment]
I came across #74134 which seemed similar but this seems to be specifically bounce light from static omni lights only

**Comment by bitsawer** [comment]
I'm actually currently working on a fix to this, I'll see if I can make a PR soon. I ran into this bug too.
