### ISSUE TITLE
Some glyphs from color OpenType SVG font are not rendered

### ISSUE THREAD

**Issue by 3dnikita** [godotengine/godot#78374]
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Godot v4.1.beta2 - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3179) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Description:

Most Emoji glyphs from color OpenType SVG font are not displayed in Control nodes, such as Label or RichTextLabel.
When using https://github.com/adobe-fonts/noto-emoji-svg/blob/main/fonts/NotoColorEmoji-SVG.otf, some emoji are rendered correctly, such as ☺️ (U+263A), but others are not visible at all, e.g. ❤️ (U+2764), 🏠 (U+1F3E0).

"Output" panel of Godot editor shows multiple error messages "_Failed to create SVG canvas._" 

### Additional info:

All these characters are rendered correctly by Firefox browser (as seen in https://github.com/adobe-fonts/noto-emoji-svg/blob/main/test.html)

Regular English text is visible when using OT SVG fonts, e.g. https://www.fontspace.com/icecreamy-font-f82130 (although rendered with some kerning issues).

Monochrome OT font https://github.com/adobe-fonts/noto-emoji-svg/blob/main/fonts/NotoEmoji.otf appears to be working correctly.

This limits usage of color fonts, since CBDT/CBLC TTF fonts are blurry if the font size is larger than PNGs which are embedded into the font, and Godot doesn't support COLR vector fonts.

Note: None of the glyphs of colorful OpenType SVG fonts are rendered at all in Godot 4.0

### Steps to reproduce

- Add Label control node to a scene
- Select Label node
- Import https://github.com/adobe-fonts/noto-emoji-svg/blob/main/fonts/NotoColorEmoji-SVG.otf as a Font value using Theme or Theme Overrides property (make sure)
- Input 🏠❤️☺️ as a value of "text" property
- Check visible characters in 2D panel of Godot editor

Expected result:
- all colorful characters are rendered correctly
- no error messages

Actual result:
- Only ☺️ (U+263A) is visible, other two are invisible (but occupy some space)
- Multiple error messages "_Failed to create SVG canvas._" are present in the Output panel of Godot editor

### Minimal reproduction project

[svg_font_sandbox_4_1.zip](https://github.com/godotengine/godot/files/11779682/svg_font_sandbox_4_1.zip)

**Comment by Calinou** [comment]
This is a ThorVG issue: https://github.com/godotengine/godot/blob/116f783db73f4bf7e9e96ae54dd3d0a20337cc8a/modules/text_server_adv/thorvg_svg_in_ot.cpp#L253-L257

**Comment by capnm** [comment]
ThorVG renders the svg images fine:
![image](https://github.com/godotengine/godot/assets/4047289/cda4c55a-808f-4cd3-9deb-6dea4e64003d)
Looks like the godot code around `modules/text_server_adv/thorvg_bounds_iterator.cpp:59`
(IteratorAccessor - private ThorVG API :hear_no_evil: ) is broken.

**Comment by bruvzg** [comment]
It might be able to render source SVG used to make font. But actual emoji fonts usually contain a single SVG for multiple glyphs (all overlapped), which do not have viewbox set.

ThorVG refuses to load SVG w/o viewbox and doesn't support rendering specific elements by id, only the whole image. Current Godot code is trying to remove all elements that aren't part of the glyph and use private API to calculate real bounding box and make a viewbox from it.

I suspect it might be removing some shared part of the SVG. Or ot's some optimization done when compiling the font that is not supposed by ThorVG.

**Comment by capnm** [comment]
It would be very nice if you could write a comment here why exactly we need this API, so that it could be possibly included in the official APIs in the next ThorVG1 release.
https://github.com/thorvg/thorvg/issues/1372

I suspect the problem in the incorrect xml syntax, you should have a closed tags, e.g. \<path ... /> or \<path>...\</path>, that's what Godot sends (and doesn't get recognized by any viewer):

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">
<defs>
<path d="M93.99,8.97 C72.08,8.97 64.03,31.36 64.03,31.36 C64.03,31.36 56.09,8.97 34.03,8.97 C17.45,8.97 -1.45,22.11 5.53,51.98 C12.51,81.85 64.09,119.06 64.09,119.06 C64.09,119.06 115.48,81.85 122.47,51.98 C129.45,22.11 111.91,8.97 93.99,8.97 Z"
fill="#F44336">
<path d="M30.65,11.2 C47.85,11.2 56.39,29.69 59.15,37.18 C59.54,38.25 61.03,38.28 61.48,37.24 L64,31.35 C60.45,20.01 50.69,8.97 34.03,8.97 C27.13,8.97 19.84,11.25 14.17,16.06 C19.18,12.77 25.05,11.2 30.65,11.2 Z" fill="#CC3333">
<path d="M93.99,8.97 C88.7,8.97 83.88,10.12 80.12,12.44 C82.76,11.42 86.03,11.2 89.27,11.2 C105.48,11.2 119.99,23.49 113.44,51.9 C107.82,76.29 74.98,105.88 64.95,117.17 C64.31,117.89 64.09,119.05 64.09,119.05 C64.09,119.05 115.48,81.84 122.47,51.97 C129.45,22.11 111.94,8.97 93.99,8.97 Z" fill="#CC3333"><path d="M17.04,24.82 C20.79,20.14 27.49,16.27 33.17,20.73 C36.24,23.14 34.9,28.08 32.15,30.16 C28.15,33.2 24.67,35.03 22.23,39.79 C20.77,42.65 19.89,45.78 19.44,48.97 C19.26,50.23 17.61,50.54 16.99,49.43 C12.77,41.95 11.57,31.65 17.04,24.82 Z" fill="#FF8A80"><path d="M77.16,34.66 C75.4,34.66 74.16,32.96 74.8,31.32 C75.99,28.3 77.53,25.38 79.38,22.78 C82.12,18.94 87.33,16.7 90.63,19.03 C94.01,21.41 93.57,26.17 91.2,28.47 C86.11,33.4 79.69,34.66 77.16,34.66 Z" fill="#FF8A80">
</svg>
```

if I rewrite it corectly - and clear the svg tag to see the picture, it gets the size properly recognised and works fine in Godot:

```svg
<svg>
<defs/>
<path d="M93.99,8.97 C72.08,8.97 64.03,31.36 64.03,31.36 C64.03,31.36 56.09,8.97 34.03,8.97 C17.45,8.97 -1.45,22.11 5.53,51.98 C12.51,81.85 64.09,119.06 64.09,119.06 C64.09,119.06 115.48,81.85 122.47,51.98 C129.45,22.11 111.91,8.97 93.99,8.97 Z" 
fill="#F44336"/>
<path d="M30.65,11.2 C47.85,11.2 56.39,29.69 59.15,37.18 C59.54,38.25 61.03,38.28 61.48,37.24 L64,31.35 C60.45,20.01 50.69,8.97 34.03,8.97 C27.13,8.97 19.84,11.25 14.17,16.06 C19.18,12.77 25.05,11.2 30.65,11.2 Z" fill="#CC3333"/>
<path d="M93.99,8.97 C88.7,8.97 83.88,10.12 80.12,12.44 C82.76,11.42 86.03,11.2 89.27,11.2 C105.48,11.2 119.99,23.49 113.44,51.9 C107.82,76.29 74.98,105.88 64.95,117.17 C64.31,117.89 64.09,119.05 64.09,119.05 C64.09,119.05 115.48,81.84 122.47,51.97 C129.45,22.11 111.94,8.97 93.99,8.97 Z" fill="#CC3333"/>
<path d="M17.04,24.82 C20.79,20.14 27.49,16.27 33.17,20.73 C36.24,23.14 34.9,28.08 32.15,30.16 C28.15,33.2 24.67,35.03 22.23,39.79 C20.77,42.65 19.89,45.78 19.44,48.97 C19.26,50.23 17.61,50.54 16.99,49.43 C12.77,41.95 11.57,31.65 17.04,24.82 Z" fill="#FF8A80"/>
<path d="M77.16,34.66 C75.4,34.66 74.16,32.96 74.8,31.32 C75.99,28.3 77.53,25.38 79.38,22.78 C82.12,18.94 87.33,16.7 90.63,19.03 C94.01,21.41 93.57,26.17 91.2,28.47 C86.11,33.4 79.69,34.66 77.16,34.66 Z" fill="#FF8A80"/>
</svg>

```

![test_direct4](https://github.com/godotengine/godot/assets/4047289/978f630a-c19a-43ad-a171-1cbdb0b7d3ef)
