### ISSUE TITLE
Parse error when attempting to export var of Callable type in a resource

### ISSUE THREAD

**Issue by A-Hugh-Mann** [godotengine/godot#78380]
### Godot version

4.1.beta.a83eb16fb

### System information

Arch Linux

### Issue description

When attempting to have a scene load a resource that uses a script that exports a var of Callable type, a parse error will occur due to Callable not being serializable.

### Steps to reproduce

Create new project.
create a resource script that exports a Callable type:

```
class_name BreakStuff
extends Resource
@export var something: Callable
```

create a .tres file that uses the script.

create a scene that uses that resource, such as with a script like

```
extends Node
@export var stuff: Resource
```

set that resource to that .tres file.

close project and reopen.

Be greeted with error message about a parse error and be unable to open that scene.

Within plain text of .tscn file you can see a line that reads
something =

which causes a parse error as something has nothing to be set to.

### Minimal reproduction project

N/A

**Comment by AnidemDex** [comment]
Happens from 4.0 to v4.0.3.stable.official [5222a99f5] aswell.

Probably is related to FormatResourceSaved not knowing how to handle Callable types, resulting in a serialization with an empty value? The script server allowing the user exporting Callables (and there's a `TYPE_CALLABLE` for property types so I don't think this is not allowed)?

**Comment by AThousandShips** [comment]
Should be handled more graciously, but yes it isn't, and shouldn't be, possible to serialise callable

**Comment by AThousandShips** [comment]
Got a PR open for solving the direct error, doesn't allow serializing `Callable`s, but that isn't supported in the binary format either so this brings parity to it
