### ISSUE TITLE
Linux + C# : "Failed to initialize context for app" on exported project

### ISSUE THREAD

**Issue by katian** [godotengine/godot#78385]
### Godot version

Godot Engine v4.0.3.stable.mono.official.5222a99f5

### System information

Ubuntu 22.04.2 LTS

### Issue description

when exported project is launch it crash :

```
Godot Engine v4.0.3.stable.mono.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1650
 
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1
Failed to initialize context for app: /mnt/nova/secure/workspace/wip/godot4/empty/build/data_empty_x86_64/empty.dll. Error code: 0x80008087
ERROR: hostfxr_initialize_for_dotnet_command_line failed with code: -2147450745
   at: initialize_hostfxr_self_contained (modules/mono/mono_gd/gd_mono.cpp:239)
ERROR: Parameter "load_assembly_and_get_function_pointer" is null.
   at: initialize_hostfxr_and_godot_plugins (modules/mono/mono_gd/gd_mono.cpp:316)
ERROR: Parameter "godot_plugins_initialize" is null.
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:411)
Erreur de segmentation (core dumped)
```

### Steps to reproduce

Linux export a simple project and run the .x86_64 binary

### Minimal reproduction project

Only one scene with one node with just one empty C# script

**Comment by raulsntos** [comment]
Please provide a MRP with the exported project. With the provided steps I'm unable to reproduce this issue.

What options are you using to export the project? Was the export process successful? What was Godot's console output after exporting? Did it contain any errors or warnings?

Also, can you provide the output of `dotnet --info`?

**Comment by katian** [comment]
[MRP.zip](https://github.com/godotengine/godot/files/11783199/MRP.zip)

default options for the export, export process successful, no console output after exporting, no errors, no warnings

```
$ dotnet --info
SDK .NET (reflétant tous les fichiers global.json) :
 Version:   6.0.118
 Commit:    b8b476fbe6

Environnement d'exécution :
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.118/

global.json file:
  Not found

Host:
  Version:      6.0.18
  Architecture: x64
  Commit:       c76ac56549

.NET SDKs installed:
  6.0.118 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

```

thanks @raulsntos

**Comment by raulsntos** [comment]
Thanks for the MRP. Unfortunately, I'm still unable to reproduce this issue. Could you upload the contents of the `build` directory after exporting?

Also, can you enable tracing and upload the output?
To do this use the command `COREHOST_TRACE=1 ./demo.x86_64 2> trace` then upload the `trace` file.

**Comment by katian** [comment]
compressed build directory take 90M can't upload it

[trace.txt](https://github.com/godotengine/godot/files/11790862/trace.txt)

**Comment by raulsntos** [comment]
Ah I see, it seems your exported project contains Windows DLLs. Maybe you exported for Windows after exporting for Linux and that replaced the contents of the `build/data_empty_x86_64` directory.

**Comment by katian** [comment]
@raulsntos thanks a lot
it's the solution
:heart:
