### ISSUE TITLE
DirectionalLight3D shadow blur works differently compared to OmniLight shadows by cutting the shadow off.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#78382]
### Godot version

4.1 b2

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

It's probably the simplest if you check the video below with the comparison.

Link: https://youtu.be/qHcdOJtZyuE

I tried to move the omnilight farther away and such too but it doesn't change the behaviour.

DirectionalLight3D cuts off the shadow while also bluring it while OmniLight3D's blur only blurs the shadow.
I'm a bit confused if this is a bug or if it's some strange limitation of DirectionalLight3D perhaps? I'd expect both work the same way as the OmniLight3D's blur, does blur on DirectionalLight3D changes shadow bias on its own behind the scene without changing it in the editor or something?

I think this is related to the whole godot 4 not just this particular beta version.

I'm sorry if it's not a bug but I didn't get much responses elsewhere to determine the nature of this.

### Steps to reproduce

Use DirectionalLight3D and OmniLight3D separately, turn the shadows on, change blur to observe the difference.

### Minimal reproduction project

I used this scene for testing: https://github.com/Jamsers/Bistro-Demo-Tweaked/tree/PCSS-test

**Comment by Calinou** [comment]
This is because shadow bias has to be increased at higher blur values to prevent shadow acne.
