### ISSUE TITLE
NavigationAgent stops working when unpausing and pausing in same frame

### ISSUE THREAD

**Issue by N3sbocaj** [godotengine/godot#78384]
### Godot version

v4.1.beta.custom_build [a83eb16fb]

### System information

Windows 11

### Issue description

NavigationAgent loses its map when unpausing and then pausing in the same frame.

### Steps to reproduce

1. Run minimal reproduction project
2. Press ui_up to pause game
3. Press ui_down to unpause, pause then unpause again at once
4. See that NavigationAgent stops moving since velocity_computed signal stops being called
5. See that the NavigationAgent's map is printed and is missing even after unpausing

### Minimal reproduction project

[NavigationAgentBug.zip](https://github.com/godotengine/godot/files/11780281/NavigationAgentBug.zip)

**Comment by smix8** [comment]
Would be fixed by PR https://github.com/godotengine/godot/pull/75888 adds a "true" pause mode for agents without removing the navigation map.
