### ISSUE TITLE
[3.0] Godot doesn't compile on Windows: missing return value

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7838]
Godot doesn't compile on Windows with MSVC:

In editor_import_export.cpp:
```
Error EditorExportPlatform::_save_pack_file(void *p_userdata,const String& p_path, const Vector<uint8_t>& p_data,int p_file,int p_total) {


}
```
What should this function return?

**Comment by punto-** [comment]
ERR_UNAVAILABLE

**Comment by RebelliousX** [comment]
Is this issue still valid? I just compiled the head of the master branch using VS2015 and linked successfully.

**Comment by bojidar-bg** [comment]
Yeah, it is invalid now, it was fixed by some commit that didn't reference it.
