### ISSUE TITLE
[3.0] Crash in audio engine when Godot closes

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7839]
Tested on Godot 3.0 master 5e3fc7d06956dcda8b50cd4f028c83cf967f7223
Windows 10 64 bits, debug run from QtCreator

I created an empty project, but as soon as I open it, the project manager crashes. It looks like it tries to access `buses[0]` but the vector is in a somehow invalid state.

Then the editor opens background after I stop debugging.
It also crashes the same way when I close it.

![image](https://cloud.githubusercontent.com/assets/1311555/23097458/ac2ba13c-f634-11e6-89a7-8addf70b83a9.png)

**Comment by hpvb** [comment]
I fixed this for Linux in #7833 I'll make a similar PR for win32
