### ISSUE TITLE
NavigationAgent2D debug path not showing

### ISSUE THREAD

**Issue by andypandy47** [godotengine/godot#78399]
### Godot version

4.0.3.stable.mono, 4.1.beta2.mono

### System information

Godot v4.1.beta2.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.2737) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

NavigationAgent2D debug path is not appearing when the debug option is enabled. This used to draw fine when I first started working on my current project. I'm not sure what happened or what setting I've changed, but debug paths are no longer being drawn for any agent. Even when the custom path colour and size values are used, no path is visible.

Strangely, in the minimal reproduction project I've attached, adding a call to the nav agent `is_target_reachable()` seems to cause the path to be drawn. However, this still does not work in my main project.

It may be that I'm missing something here and would appreciate any help or insight into whats gone wrong as the debug path functionality was suuuuper useful when it was working previously. I can't seem to find any other posts online about this issue.

### Steps to reproduce

- Setup a navigation agent 2D as described in the Godot docs https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationagents.html
- Enable the debug option.  
<img width="349" alt="image" src="https://github.com/godotengine/godot/assets/19389664/44509b1e-6b6e-480a-a03b-c0c8eb529e35">

When the nav agent target is set by code, this should trigger a path to be drawn from the nav agent position to the target position yet no line is drawn.

### Minimal reproduction project

Run the attached project and click around the screen. No debug path is drawn.

Go into one of the attached scripts, NavigationDebug.cs or NavigationDebug.gd and uncomment the line that prints `is_target_reachable()`, rerun the project and click aorund the screen again. For some reason, this causes the debug line to be drawn.

[TestNavDebug.zip](https://github.com/godotengine/godot/files/11781387/TestNavDebug.zip)

I've tried adding in this function call to my main project in the hopes that it would begin drawing the debug paths again but no luck.

**Comment by AThousandShips** [comment]
You have to query the navigation path by some means or it won't be computed, this is done by `is_target_reachable`, if you use it according to the instructions in the documentation it woks:
> After setting [target_position](https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#class-navigationagent2d-property-target-position) it is required to use the [get_next_path_position](https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#class-navigationagent2d-method-get-next-path-position) function once every physics frame to update the internal path logic of the NavigationAgent. The returned vector position from this function should be used as the next movement position for the agent's parent Node.

**Comment by smix8** [comment]
Not sure what I am looking at in the MRP project because it does not include all of the mentioned files and lines and it also draws the debug path just fine without me changing anything in Godot master.

The debug path is only drawn once when the path changes. The debug path uses the parent node canvas and visibility.

**Comment by andypandy47** [comment]
Thanks for your responses, I realise now that the MRP is working as expected. I've delved deeper into my main project trying to recreate the issue and managed to spot the cause of the debug line not being drawn. This attached MRP better represents the project where I've been seeing this issue.

[TestNavDebug.zip](https://github.com/godotengine/godot/files/11781711/TestNavDebug.zip)

In my actual project, I'm using a tilemap with navigation. I've also got an autoloaded scene with various controllers for game logic along with a Canvas Modulate node to create a day-night cycle. For some reason, the autoloaded canvas modulate node causes the debug path to be drawn behind the tilemap making it appear like there is no path drawn. Removing the canvas modulate node or moving into the same scene as the tilemap cause the line be drawn on top of the map again.

Debug line drawn behind the tilemap with autoload canvas modulate
<img width="581" alt="image" src="https://github.com/godotengine/godot/assets/19389664/b694118b-ec76-4881-a2b1-624f9b05224a">

Debug line with canvas modulate in the same scene
<img width="788" alt="image" src="https://github.com/godotengine/godot/assets/19389664/7f73c69f-d319-4f3e-a912-f3a539678150">

Does anyone know why this occurs? Seems odd that having an autoloaded node would cause debug lines to be drawn in a different order/layer. I'll experiment with different values on the canvas modulate as I would like to keep it autoloaded to more easily persist day/night between scenes.

**Comment by Muhammad-Fiqri** [comment]
> You have to query the navigation path by some means or it won't be computed, this is done by `is_target_reachable`, if you use it according to the instructions in the [documentation](https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#description) it woks:
> 
> > After setting [target_position](https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#class-navigationagent2d-property-target-position) it is required to use the [get_next_path_position](https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#class-navigationagent2d-method-get-next-path-position) function once every physics frame to update the internal path logic of the NavigationAgent. The returned vector position from this function should be used as the next movement position for the agent's parent Node.
> 
> Not sure if this is a bug, as the correct usage requires this, and if it is done it works correctly, this is also mentioned in the docs linked:
> 
> > On the next physics_frame, call get_next_path_position() again for the next position and repeat this until the path ends.

yup this fixed it for me, thanks

**Comment by Drbsy** [comment]
i also have the same bug in my game . its was working at first after a while its have stoped working , the path finding works fine but i cant see the path at all i use godot 4.6.3 stable
