### ISSUE TITLE
Y Sort does not work correctly for Control nodes.

### ISSUE THREAD

**Issue by ShadowMosesIsland** [godotengine/godot#78394]
### Godot version

4.0.3.stable.mono

### System information

Windows 10 Pro 64 bit - GTX 1660 Super (Drivers GRD version 536.23) - AMD Ryzen 5 3600

### Issue description

There is an issue with Y Sort for Control nodes (Such as Label or ColorRect) where they always appear below any Node2D node (Sprite2D, AnimatedSprite2D, or Tilemap), regardless of the Y Sort origin point*

**The Z Index property was not changed at all and is the same value for every Node related to this issue.**

**Y Sort Enabled property description says that it only affects children that inherit from CanvasItem, which Control nodes do, otherwise it wouldn't have this property in first place.**

**What I've tried**
- Making the Y Sort origin point below _everything_ else.
- Making a Node2D container for the Label, enabled Y Sort for the container and disabled for the label, and every other combination of this setting.
- Using a different renderer.

 _*The red orange cross, which position is changed with the offset settings)_

### Steps to reproduce

1. Create a Node2D scene
2. Enable Y Sort for it
3. Add a Sprite2D as child and give it any texture
4. Set its Y Offset property so that the Y Sort origin point is below the entire sprite texture
5. Enable Y Sort for it
6. Add a Label node as a child of the root
7. Set its text to anything
8. Set the Y Pivot Offset property so that the Y Sort origin point is below the entire text
9. Enable Y Sort for it
10. Go to the 2D editor
11. Move the Label in a vertical line across the Sprite2D

### Minimal reproduction project

[YSortBug.zip](https://github.com/godotengine/godot/files/11781086/YSortBug.zip)

**Comment by golddotasksquestions** [comment]
I cannot replicate your issue in Godot 4.0.3 on Windows. Everything works as expected (all CanvasItem nodes are Ysorted according to their origin position):


https://github.com/godotengine/godot/assets/47016402/bf4be1bc-ced2-4d25-bfad-927ad012f6a8

**Comment by Zireael07** [comment]
Simple solution: pivot cross differently colored to origin cross?

**Comment by kleonc** [comment]
`Control.pivot_offset` doesn't change the origin of the given Control's transform, it's a pivot only for the rotation/scale. The transform's origin (which is used for Y-sorting) is still the Control rect's position (its "top-left" corner).

What is indeed confusing is the in-editor gizmo which kinda suggests such pivot affects the position:

- Select tool:
![zEvPgD8KLw](https://github.com/godotengine/godot/assets/9283098/721a3d3d-7fe6-4af7-9c51-fc675bd09cea)
- Move tool:
![soky6Ji9zY](https://github.com/godotengine/godot/assets/9283098/720cf4d4-a960-4b8c-b60d-69650aaeeff4)

@ShadowMosesIsland So currently if you'd want to make e.g. a Label be Y-sorted based on a position different than the Label position then you could add an intermediate CanvasItem as a parent of such Label (with such CanvasItem having Y-sorting turned off so its children would be sorted based on such parent's position). And you could offset such Label within this parent however you want, by changing its position. Example: [YSortBug workaround.zip](https://github.com/godotengine/godot/files/11781528/YSortBug.workaround.zip).

**Comment by kleonc** [comment]
Related: https://github.com/godotengine/godot-proposals/issues/6367.

**Comment by ShadowMosesIsland** [comment]
Thank you all for your answers. So apparently it was just a confusion of the pivot offset usage. No bug here, issue resolved.
