### ISSUE TITLE
Android Export Bug

### ISSUE THREAD

**Issue by NJ0prod** [godotengine/godot#78408]
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

well when you try to export the project for for android u get error and warning but after u reopen godot and try to export it works fine then try re exporting for the second time u will get the same error and warning and sometime a different error and u have re open and re export again to make it work

### Steps to reproduce

followed the docs and didnt work at all then when I switched to JDK 17 it got that error but with JDK 11 it wont work at all

### Minimal reproduction project

.

**Comment by AThousandShips** [comment]
What error and warning? What settings are you using?

Please provide more information

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you respond with more information this can be reopened
