### ISSUE TITLE
Using `hint_normal_roughness_texture` on the forward mobile renderer causes shader compilation failure

### ISSUE THREAD

**Issue by lewiji** [godotengine/godot#78411]
### Godot version

Tested on 4.0.3 and 4.1 beta 2

### System information

Arch Linux

### Issue description

In a spatial shader, using the hint `hint_normal_roughness_texture` and then trying to sample that uniform in the `fragment` function, as outlined in the screen reading shader docs, while using the mobile renderer causes shader compilation failure. It can also freeze the editor requiring a SIGKILL to end the process if the shader is applied to a mesh and run.

```servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:182 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.```

It seems the shader compiler still validates the gdshader, generates the shader code, which references `normal_roughness_buffer`, but this is only defined in the glsl for the forward clustered renderer and is left undefined in mobile, causing an "undeclared identifier" error in the generated shader code.

The compatibility shader, by comparison, explicitly errors in the shader editor and will not try to compile the shader. If the mobile renderer is not intended to support this, it should probably use the same behaviour, and compatibility with the renderers explained in the docs.

### Steps to reproduce

Create a shader:

```
shader_type spatial;

uniform sampler2D normal_roughness_texture : hint_normal_roughness_texture, repeat_disable, filter_nearest;

void fragment() {
    vec3 screen_normal = texture(normal_roughness_texture, SCREEN_UV).xyz;
}
```

Switch to mobile renderer.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please use the issue template format to make it easier to follow in the future

**Comment by lewiji** [comment]
@AThousandShips updated, apologies using a 3rd party client which didn't offer the choice to use the template.

The minimum reproduction is just adding copying a few lines of shader code into a project (have now included the shader code as in the docs example), but I can create a zipped project later with that shader if desired.

**Comment by AThousandShips** [comment]
That should be enough, looked through the code and seems that it is not supported, so an error is the correct thing here

**Comment by Calinou** [comment]
Normal roughness buffer is not supported in the Mobile renderer, and we don't expect it to be implemented in the future due to the performance cost it would have on mobile devices.

**Comment by lewiji** [comment]
> Normal roughness buffer is not supported in the Mobile renderer, and we don't expect it to be implemented in the future due to the performance cost it would have on mobile devices.

Thanks for the clarification - I figured that was the case, but there was nothing official I could find saying this, and that the compatibility renderer explicitly warns you from using this hint in a shader via messaging/validation errors in the editor, with the mobile renderer it doesn't, it just goes ahead and tries to compile the shader despite it being invalid due to the missing uniform definitions in the mobile glsl.

If I get time later I'll see if I can just have the mobile renderer trigger the same behaviour as the compat renderer in the shader editor, and add a mention of this to the docs. If all the above is accurate, it should be as simple as that.

**Comment by clayjohn** [comment]
Indeed, the mobile renderer should get the same error check as the compatibility renderer for now to ensure that the normal_roughness texture isn't being accessed.
