### ISSUE TITLE
Cannot set Path3D as Path Node for CSGPolygon3D created by code

### ISSUE THREAD

**Issue by bt0rne** [godotengine/godot#78410]
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Godot v4.1.beta2 - Debian GNU/Linux 12 (bookworm) 12 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 Threads)

### Issue description

I want to generate a box shape along a Path3D by code, and i'm trying to do this by creating a CSGPolygon3D and set the Path3D as the Path Node.

However, when running the scene, i get this error message:
**Invalid set index 'path_node' (on base: 'CSGPolygon3D') with value of type 'Path3D'.**

I would assume this is a bug, considering it's supposed to be a Path3D node used for this purpose.

Screenshots:
![image](https://github.com/godotengine/godot/assets/123738491/6435af93-38a6-4d02-93d7-aa0e921fa72f)
![image](https://github.com/godotengine/godot/assets/123738491/7bc3ebef-8a82-4e4c-9c58-6e8fe8574cc1)

Context:
The box shape i'm generating will be converted to a mesh and then to a collision shape. See the steps to reproduce for clean exaple code creating the same problem.

### Steps to reproduce

1. Create a Node3D.
2. Add a Path3D child to Node3D.
3. Attact a script with this code to the Node3D:

```
extends Node3D

func _ready():
		
		var path = $Path3D
		var csg = CSGPolygon3D.new()
		
		csg.name = "csg"
		csg.mode = CSGPolygon3D.MODE_PATH
		csg.path_node = path
		
		path.add_child(csg)
```

4. Run the scene.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The property is a `NodePath` not a `Node`, you need to set the path, relative to the CSG node

**Comment by bt0rne** [comment]
I don't understand how i managed to miss that when reading the page earlier.
Working flawlessly as expected now, thanks!

![image](https://github.com/godotengine/godot/assets/123738491/3dd218ad-61ef-41ff-ac20-4aac54c035f3)
