### ISSUE TITLE
hint_screen_texture forces alpha to 1.0, also when using BackBufferCopy

### ISSUE THREAD

**Issue by bruce965** [godotengine/godot#78413]
### Godot version

v4.0.2.stable.mono.official [7a0977ce2]

### System information

Windows 10 - Vulkan API 1.3.217 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon(TM) Graphics

### Issue description

The screen texture read from inside a viewport with transparency enabled always has alpha = 1.0, even though it's not supposed to.

Expected result:
![image](https://github.com/godotengine/godot/assets/992536/c3234636-d704-48df-84fc-10735e7c65de)

Actual result:
![image](https://github.com/godotengine/godot/assets/992536/1e4a6d27-064e-404e-8bc0-ac919998ee37)

### Steps to reproduce

```glsl
shader_type canvas_item;

uniform sampler2D screen_texture : hint_screen_texture, filter_linear_mipmap;

void fragment() {
	COLOR = texture(screen_texture, SCREEN_UV);
	//COLOR = vec4(0., 1., 0., .25); // expected result
}
```

### Minimal reproduction project

[screen_reading_transparency.zip](https://github.com/godotengine/godot/files/11782128/screen_reading_transparency.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/78207.
