### ISSUE TITLE
@GlobalScope.clamp() gives wrong result on Vector2()

### ISSUE THREAD

**Issue by turqueschultz** [godotengine/godot#78425]
### Godot version

4.0.3

### System information

Windows 10

### Issue description

Clamping a `Vector2` with `@GlobalScope.clamp()` does not return the same value as `Vector2.clamp()`

### Steps to reproduce

Clamping the mouse's position between a `Rect2`'s position and end has different results when using `Vector2.clamp()` (black circle, expected result) and `@GlobalScope.clamp()` (red circle):

![top](https://github.com/godotengine/godot/assets/124798883/3a50b6b7-d36a-4c8c-9c70-42618391b7ff)
![bottom](https://github.com/godotengine/godot/assets/124798883/73114896-2f98-4d43-abc2-4744ae858f81)
![left](https://github.com/godotengine/godot/assets/124798883/8b33e314-547c-4dbe-b59b-ed4d8fdc3a61)
![right](https://github.com/godotengine/godot/assets/124798883/2f7c9ac3-1d1a-4450-9ec5-5f0093c179cd)
![center](https://github.com/godotengine/godot/assets/124798883/edc98358-c545-414e-a0d9-ab44c155747f)
(When the mouse's position is inside the `Rect2`, the result is the same, though)

### Minimal reproduction project

[clamp_on_vector2.zip](https://github.com/godotengine/godot/files/11783682/clamp_on_vector2.zip)

**Comment by theraot** [comment]
The global scope method uses the less than and greater than operators from whatever you pass. The code can only return the "minimum", the "maximum", the original value, or error (when the types are not compatible). Which will never behave as expected for vectors (regardless of how you define the "minimum" and the "maximum" - it uses lexicographic order btw).

**Comment by AThousandShips** [comment]
This is documented, so not a bug and not undocumented

**Comment by aaronfranke** [comment]
The global scope clamp() method using the greater than / less than operators is also [documented on master / latest](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-clamp).

**Comment by kleonc** [comment]
Note the current behavior is equivalent to:
```gdscript
func clamp(value, min, max):
	if value < min:
		value = min
	if value > max:
		value = max
	return value
```
Meaning when `min > max` the result might be unexpected too (even for non-vectors, e.g. `clamp(0, 1, -1)` returns `-1`). This should likely also be explicitly mentioned in the docs (that it's expected that `min <= max`, as their names suggest).

In such case the same clarification could be added for `clampi`/`clampf`, although their behavior is different as it's equivalent to:
```gdscript
func clampi_or_f(value, min, max):
	if value < min:
		return min
	if value > max:
		return max
	return value
```
E.g. `clampi(0, 1, -1)` returns `1`.

**Comment by dalexeev** [comment]
> Meaning when `min > max` the result might be unexpected too

* See #60615.
