### ISSUE TITLE
Cannot Launch OpenXR example on Oculus Quest 2: 

### ISSUE THREAD

**Issue by truedat101** [godotengine/godot#78427]
### Godot version

4.0.2 stable

### System information

Windows 10

### Issue description

When running an example Project for OpenXR based on https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html#doc-setting-up-xr

the launch shows an error in the console:

```
Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
Vulkan API 1.3.205 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Ti
 
[{ "id": 0, "name": &"Native mobile" }, { "id": 1, "name": &"OpenXR" }]
OpenXR not initialized, please check if your headset is connected
```

Are there additional steps needed to set up OpenXR for Quest2?  It would be worth referencing these docs if I knew exactly what they were.  I think the additional steps are:

- Setup the android as described here: [https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.htm](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html) ... can't mess that up
- then make sure you have SteamVR installed
- then enable the SteamVR beta in the properties in the beta tab
- make sure SteamVR is closed
- Look to see if SteamVR updates
- Launch SteamVR 
- Note the version should be 1.26.3 BETA or greater
- Edit Settings, and activate SteamVR as the OpenXR default

Is there anything else needed in Quest2 itself to activate OpenXR?  Would be worth documenting this somehow.  Do I really need SteamVR to make this all work?

### Steps to reproduce

1. Set up according to the referenced documentation for setting up xr
2. hit launch
3. note: a window will open, however, the project console says "OpenXR Not Initialized"

### Minimal reproduction project

Exactly the project sample used in the referenced URL : https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html#doc-setting-up-xr

It seems odd that there isn't a solid example downloadable from these documentation pages exactly for this purpose.

**Comment by akien-mga** [comment]
CC @godotengine/xr

**Comment by dsnopek** [comment]
Are you trying to make a native Quest 2 application? Or, something that runs on your desktop and is connected to your Quest 2 via air link or a link cable?

If the former, then after completing these steps:

https://docs.godotengine.org/en/stable/tutorials/xr/deploying_to_android.html

... if your headset is connected to your computer via USB and is correctly recognized, you should get a button in the upper-right corner of the editor to deploy and run on the headset.

However, you mention SteamVR a couple times, so perhaps you're trying to do the latter?

This error:

```
OpenXR not initialized, please check if your headset is connected
```

... makes it sound like you could have missed enabling the project setting shown in the screenshot here:

https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html#openxr

If that setting is enabled, then Godot will automatically try to initialize OpenXR when your app starts, which is required if you're using Vulkan.

Also, for link or air link to work you need to:

- Have the Windows Oculus app running (even if you're using the SteamVR runtime)
- Be connected to your PC via link or air link _before_ starting the app

If you've used link or air link to play PCVR games, you basically have to be doing the same things before starting your Godot app. I usually show my desktop in VR, and click the Play button from there.

> It seems odd that there isn't a solid example downloadable from these documentation pages exactly for this purpose.

The XR Tools project provides a nice demo project:

https://github.com/GodotVR/godot-xr-tools

**Comment by truedat101** [comment]
Thanks will re-review the settings again.  

I have verified

- ✔️ android install setup "deploying to android"
- ✔️ openxr setup in the project is done
- ✔️ verified Quest2 shows via ADB

I only mentioned SteamVR because I was grasping at straws for why I was seeing "OpenXR not initialized".  I will ignore that.

Will re-review docs as proposed.  

At the moment after fixing a checkbox under projects, I see: 

![image](https://github.com/godotengine/godot/assets/64202/93d98eca-3646-4b0e-b3b5-7e825843fa9a)

So my attempt is to run an openxr example from Godot.  Do I want steam VR off?

**Comment by dsnopek** [comment]
Ok, so that alert can only come up when trying to run on desktop (which for the Quest 2 means link or air link). Is it your intention to run your app this way? Or, are you looking to run natively on the Quest 2 as an Android app?

**Comment by truedat101** [comment]
Noting the debug output associated with the dialog:

Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   1.26.3
OpenXR: Failed to get system for our form factor [ XR_ERROR_FORM_FACTOR_UNAVAILABLE ]
Vulkan API 1.3.205 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Ti

**Comment by truedat101** [comment]
No my intent is not to use link or airlink.    Trying to do "android" / openxr development.

I will retry this set up using the openxr demo app.

**Comment by dsnopek** [comment]
> Noting the debug output associated with the dialog:

Yep, those messages confirm that you are running this on your desktop, and not on the Quest as an Android app.

> No my intent is not to use link or airlink. Trying to do "android" / openxr development.

Ok! So, I think you might just be clicking the wrong button :-)

You don't want to click the normal play button that will run the game on your local computer. You want to click the one in the middle, whose tooltip says "Remote Debug":

![Selection_052](https://github.com/godotengine/godot/assets/191561/5c3cc2fe-9502-43b4-a8e7-d1eae6b7f3c9)

Clicking that should show a dropdown with "Quest 2" in it. Select that!

If you're not seeing that button or there's no "Quest 2" in the dropdown, it could mean:

- You didn't check "Runnable" when setting up the export
- Godot isn't able to run adb for some reason. Double check your editor settings, and make sure the path to adb and your debug keystore is correct
- adb (or the "right adb" -- it's easy to end up with multiple adb daemons on your system) isn't recognizing your Quest

**Comment by truedat101** [comment]
I see ... definitely I missed the distinction between the "play" button and the remote debug button.  Will run through this again.  Also will confirm the runnable checkbox for export.  My Android stuff is set up on the system and I did verify the config, however, it is likely a checkbox missing .  Will confirm.
> > Noting the debug output associated with the dialog:
> 
> Yep, those messages confirm that you are running this on your desktop, and not on the Quest as an Android app.
> 
> > No my intent is not to use link or airlink. Trying to do "android" / openxr development.
> 
> Ok! So, I think you might just be clicking the wrong button :-)
> 
> You don't want to click the normal play button that will run the game on your local computer. You want to click the one in the middle, whose tooltip says "Remote Debug":
> 
> ![Selection_052](https://user-images.githubusercontent.com/191561/248031262-5c3cc2fe-9502-43b4-a8e7-d1eae6b7f3c9.png)
> 
> Clicking that should show a dropdown with "Quest 2" in it. Select that!
> 
> If you're not seeing that button or there's no "Quest 2" in the dropdown, it could mean:
> 
>     * You didn't check "Runnable" when setting up the export
> 
>     * Godot isn't able to run adb for some reason. Double check your editor settings, and make sure the path to adb and your debug keystore is correct
> 
>     * adb (or "the right adb" -- it's easy to end up with multiple adb daemons on your system) isn't recognizing your Quest

**Comment by truedat101** [comment]
Thank you, I can confirm based on the above explanation, that several things were wrong:

- I needed to add the Godot XR Android OpenXR Loader

![image](https://github.com/godotengine/godot/assets/64202/47649da5-921c-4fd5-95f3-936e5be17bdc)


- I needed to go back into the Project Export Profile https://docs.godotengine.org/en/stable/tutorials/xr/deploying_to_android.html and make sure that OpenXR is set up as exported, turn on gradle (it's written there but the picture doesn't show the box checked !!!) .
- in the export profile fill in the keystore + username + password for deb
- And still then the next thing is make sure the device is visible via ADB.  It will mysteriously get offline sometimes.  My solution is to start Android studio and it usually gets things kickstarted when you launch a device manager.  

- If it is visible via ADB, the "Remote Debugging" button is active and not disabled 
![image](https://github.com/godotengine/godot/assets/64202/60399e7f-db41-42f1-a8d2-fdf3924e76bf)


Then it works!

Thanks again.  I will write this up for my team, as we had one person run through it unsuccessfully (previously he had it working with Godot 3 a few years back) but there were about 4-5 things that weren't in the link that I sent him to follow.    So I got involved to try and see what was missing.  Probably I will post a gist somewhere for these steps because it is too easy to miss steps and Godot docs while complete are a bit spread out and not sequential in the steps.l  Plus some links are old out there on the Internets.

**Comment by truedat101** [comment]
Can close I think as this is resolved.

**Comment by truedat101** [comment]
I've added a gist here: https://gist.github.com/truedat101/8d1c9f5877ae0465e1f678327c5ef099

There might be some problems with the gist but the internet will correct me if so.

**Comment by dsnopek** [comment]
Thanks! I'm glad you got it working :-)

I've made a PR to attempt to fix the documentation around the specific points of confusion that you encountered:

https://github.com/godotengine/godot-docs/pull/7567

**Comment by truedat101** [comment]
> Thanks! I'm glad you got it working :-)
> 
> I've made a PR to attempt to fix the documentation around the specific points of confusion that you encountered:
> 
> [godotengine/godot-docs#7567](https://github.com/godotengine/godot-docs/pull/7567)

Thanks you guys are awesome for pitching in on help instead of saying to read the manual.   It's easy to forget the clean system problem is real for new users coming on board vs developer systems that are already staged.

**Comment by dsnopek** [comment]
Closing this issue now that the docs improvements have been merged.

Thanks again for reporting your experience! :-)
