### ISSUE TITLE
Shadows broken with orthogonal camera in 3d both in editor and in game

### ISSUE THREAD

**Issue by FXRoux** [godotengine/godot#78422]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10 (Version 10.0.19045 Build 19045) - Forward+ - Intel Core i7-7700K CPU - NVIDIA GeForce RTX 3080 (driver version 536.23)

### Issue description

Orthogonal camera in editor:
![Ortho](https://github.com/godotengine/godot/assets/8497977/9e6f1c41-b9e8-42a1-bab5-cbbc654ec781)

With the perspective camera:
![Perspective](https://github.com/godotengine/godot/assets/8497977/771e2d78-eb6d-4086-a4c1-80559f7a72f5)
I would expect the shadow to be of the same quality whether in perspective or orthogonal camera

Cinematic view orthogonal camera:
![CinematicPreviewOrtho](https://github.com/godotengine/godot/assets/8497977/4336736e-da81-4fc6-8471-576b6fc102d9)
This screenshot uses a camera further away to show that the LOD used to generate the shadow break the shadow.

### Steps to reproduce

Use the orthogonal camera.

### Minimal reproduction project

[MinimalProject.zip](https://github.com/godotengine/godot/files/11782773/MinimalProject.zip)

**Comment by felaugmar** [comment]
It looks like the shadow is picking a different LOD stage than the mesh.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/58332.

**Comment by golddotasksquestions** [comment]
Posting this here for documentation sake:

Many people who come new to Godot seem to have a problem with the Shadow Mesh showing a different LOD than the visible Mesh. 

https://www.reddit.com/r/godot/comments/170wqon/weird_shadows_in_godot_3d_tutorial/

It is about geometric LOD, not texture LOD, so I wonder if it is related to this issue here.

![image](https://github.com/godotengine/godot/assets/47016402/4cd4a410-7d1b-4598-9477-8f7594f799c8)

**Comment by Calinou** [comment]
This issue was confirmed on 4.2.1 in https://forum.godotengine.org/t/shadows-look-bad-in-orthogonal-view-and-decreasing-far-clipping-doesnt-work/50166.

**Comment by karlmacklin** [comment]
Not sure this helps, but I too was following the standard 3D tutorial and wound up with almost the exact thing as in the screenshot above, the orange 3D model has a boxy shadow.

I tried to disable the LOD generation for the import by editing the .import file directly and setting `meshes/generate_lods=false` but that did nothing sadly.

However, I went into my DirectionalLight3D > Directional Shadow and changed Pancake Size from 20 to down to 4 and boom - shadow is properly round 🤷‍♂️
