### ISSUE TITLE
LightmapProbes not selectable in the 3D editor viewport

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#78432]
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

As of currently, you cannot click-select them in 3D view and have to select them from scene tree. Considering that manually placing down light probes is already somewhat laborious(and using something to place them on a subdivided grid may not be enough), not being able to click-select them would be a huge pain.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It helps speed up the process of manually placing `LightmapProbe`s and moving them about. A huge QoL improvement in my opinion.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user clicks on a `LightmapProbe`'s gizmo(see the circular thing below), the `LightmapProbe` it belongs to will be selected and moved around easily. That's literally it.
![image](https://github.com/godotengine/godot-proposals/assets/25323231/aa223828-9352-4fbe-a109-4e81493b0f3d)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

`LightmapProbe` is implemented in core.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

**Comment by jcostello** [comment]
>That said, it may be intended as clicking LightmapProbes while trying to select something else could end up being annoying in the long run.

Actually it could be really useful. There is no mechanism to manually set up light probes, so selecting them with a click clould be really handy to copy them and moving them.
