### ISSUE TITLE
problem with ImageTexture created from image with FORMAT_RH

### ISSUE THREAD

**Issue by mohsenph69** [godotengine/godot#78445]
### Godot version

4.0

### System information

Linux manjaro gpu rx 6900 xt 

### Issue description

I am working on a terrain system which divide heightmap image
Also it change the resolution of heightmap depend on LOD

After converting the height map to texture with ImageTexture some of region have some white and black point at the end of texture
This will happen only when I use FORMAT_RH format, when I use full float or FORMAT_RF, there is no problem and everything will work
Also this will happen for some of the regions not for all of them
![Screenshot_20230619_204257](https://github.com/godotengine/godot/assets/52196206/287b9481-2d7e-400e-ae81-d1d4192cfa05)

This is a photo of what happening, you can see at the end of photo this strange pixels will apeare
![Screenshot_20230619_203749](https://github.com/godotengine/godot/assets/52196206/920fb1c8-e943-4bbd-8753-19f9a4a76ba3)

and this is my terrain, as you can see with this pixels I can not use half float images for my terrain
and for now I just use full float images

### Steps to reproduce

Create some half float images with FORMAT_RH format
resize them
use ImageTexture::create_from_image(image) to create a texture
Some of the texture that you have created has some black and white pixels at the end of texture

Also I am using GDExtension for this
I just generating different heightmap with PackedByteArray, and resize them with my algorithm to optimize GPU memory usage, and I have this problem
But I test this also with Image resize function and all of them get the same result when using FORMAT_RH format
As soon as I change the format to FORMAT_RF everything work again

Also I think the problem come from this: ImageTexture::create_from_image(image) 
because I saved those images to see if the problem is from image class but all images were ok

### Minimal reproduction project

N/A
[empty.zip](https://github.com/godotengine/godot/files/11792662/empty.zip)

**Comment by clayjohn** [comment]
Tagged as good first issue. This can be a very interesting thing to debug for someone with a bit of background in c++ and an understanding of types and type-conversion issues. 

To me it seems likely that someone in ``create_from_image()`` the image data is getting cast to the wrong type, resulting in either some clamping or overflow behaviour.

**Comment by kdiduk** [comment]
I can take this issue if no one has started working on it yet.

**Comment by mohsenph69** [comment]
I just test this with other Renderer
There is no problem with compatibilty
This problem happen only with Forward+ and Mobile

**Comment by mohsenph69** [comment]
This project is a little bit mess right now
But If you need to see my project I upload that in my google drive:
https://drive.google.com/file/d/1AYwmClRx606KJ8-2qi_o6APFFF2-fPbR/view?usp=sharing

**Comment by mohsenph69** [comment]
I get similar effect even by compressing image
You can see that in the image bellow
![bug_forward](https://github.com/godotengine/godot/assets/52196206/73cb5e15-7423-4ff1-bf04-127fb8becbac)

**Comment by mohsenph69** [comment]
This is a small project which I made with this
[Fbug.zip](https://github.com/godotengine/godot/files/11923653/Fbug.zip)

As you can see here I create 6 image and this bug happen only for one of them
If this thing not happen for you create some more of this, you may see them
I test this with compatibility and it is Ok there, this happen only in Forward and Mobile
Also I did not test this on windows, I work on linux manjaro
![fbug](https://github.com/godotengine/godot/assets/52196206/563877cc-46d7-4b1a-a8b3-bf399273676c)

**Comment by kdiduk** [comment]
@mohsenph69 Thank you! Now I can reproduce it, even with other images that I create myself. 

And indeed the bug is reproduced only when we convert the same image multiple times. No even need to scale/resize the image.

I'll try to debug it. It seems that there is some state retained deep inside `ImageTexture.create_from_image()` like static variables.

Just in case, I've tested in on Linux only yet. But I'll find someone with Windows (and maybe Mac) to test it :smiley:

**Comment by kdiduk** [comment]
@josefalanga you can work on it :slightly_smiling_face: Unfortunately I couldn't find time to dig into it yet and find out the reason :disappointed:

**Comment by ParsleighScumble** [comment]
I spent some time looking into this but I didn't manage to figure it out yet. It's at least nothing that's caught by Vulkan validation layers.

**Comment by jsjtxietian** [comment]
At least in mohsenph69's demo, it seems that the last assigned texture will trigger this bug no matter where this texture is.

**Comment by Alex2782** [comment]
`ImageTexture.create_from_image()` calls the function `set_image`

same bug
```
	$sp.texture = ImageTexture.new()
	$sp.texture.set_image(img)
```
I wanted to save the texture as a PNG file again afterwards, but after `get_image` the error is no longer there. 
Very strange. 🤯 

```
$sp.texture.get_image()
```

```
Ref<Image> ImageTexture::get_image() const {
	if (image_stored) {
		return RenderingServer::get_singleton()->texture_2d_get(texture);
	} else {
		return Ref<Image>();
	}
}
```

**Comment by jsjtxietian** [comment]
Renderdoc shows that the color texture itself is broken, I guess we need to check the cpu side, the image compress and assignment part.
![image](https://github.com/godotengine/godot/assets/8315986/59e2c167-c3f9-49c1-9361-af50d7694023)

**Comment by bitsawer** [comment]
I did some digging and there might be something weird going on in `RenderingDeviceVulkan::_texture_update()`. It updates textures in blocks using `RenderingDeviceVulkan::_staging_buffer_allocate()` and patching the function to always force flush current frame makes this bug go away:

```cpp
Error RenderingDeviceVulkan::_staging_buffer_allocate(uint32_t p_amount, uint32_t p_required_align, uint32_t &r_alloc_offset, uint32_t &r_alloc_size, bool p_can_segment) {
    // Determine a block to use.

    _flush(true); // <- Add this.

    r_alloc_size = p_amount;
```

However, this could also be a false lead if the problem is some kind of timing issue etc. Then again, `_texture_update()` command buffers and staging buffers are tied to frames to some extent, so using a debugger might affect the timing and thus results. I'm busy doing other stuff for a while, so anyone is free to investigate this more.

**Comment by jsjtxietian** [comment]
Thanks for your finding, that helped a lot! I suspected it could be a vulkan issue but didn't dig it since I'm new to the code base. I can help to dig more based on you and everyone else's findings.

**Comment by Alex2782** [comment]
Is it still a `good first issue` or is a `vulcan` expert necessary?

I experimented a bit with the code:

1. it is also enough to execute `_flush(true)` only 1 time `if (frames_drawn == 5) _flush(true);`
2. if the project `Fbug` is `_ready`, then the variable `frames_drawn` = 5
3. the function `_staging_buffer_allocate `also has a `worst case scenario`, there `_flush(true)` is forced, but it does not come to that
4. after `_ready` the first if-condition is always false 
5. --> `staging_buffer_blocks[staging_buffer_current].frame_used == frames_drawn`
