### ISSUE TITLE
String.get_slice return Raw String

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#78459]
### Godot version

v4.1.beta2.official [a2575cba4]

### System information

Windows 10, 64bit

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/45646095-d1fc-4cf6-b24e-4991b3795b32)
`String.get_slice()` returns an raw string if the slice does not exist, but the docs say:
![image](https://github.com/godotengine/godot/assets/35988767/2ce06a65-e6c4-4f5d-834e-412a00627865)

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by AThousandShips** [comment]
The documentation is arguably ambiguous here, it doesn't exactly state that it will return empty if *no* entry matches, only if the specific `slice` doesn't exist, so it's a matter of interpretation here, and arguably changing the code breaks compatibility, depending on the interpretation, so we can either clarify the documentation or update the code, the former is easier and safer

**Comment by timothyqiu** [comment]
`get_slice()` was an internal method and exposed later in #54453. The behavior is the same at that time, so it's the documentation that's wrong.

**Comment by AThousandShips** [comment]
It's been the same since before open source

Will update the documentation
