### ISSUE TITLE
Godot 4 Issue - Intellisense issue with variables inside Autoload Scripts

### ISSUE THREAD

**Issue by SoldierCantKill** [godotengine/godot#78454]
### Godot version

4.0.3.stable.official [5222a99f5]

### System information

Windows 10 - Godot 4.0.3.stable.official

### Issue description

Godot 4's intellsense is very buggy, but I think Godot 4's issue with autoloads makes it majorly more difficult to code in lots of scenarios.

First, let's analyze the Godot 4 autoload to make sure there is nothing wrong with it:
![image](https://github.com/godotengine/godot/assets/75461200/86040295-65e7-471c-a399-a4ff72e0190c)

As shown in the image, all (most) variables have been statically typed, so we should have no issues accessing them.

In Godot 4, variables inside of autoloads had no problem getting picked up by intellisense, as seen here:
![image](https://github.com/godotengine/godot/assets/75461200/5f1ea310-7e66-42b6-8566-219d9214054c)

As shown in the image, Godot 4 had no issues with loading the variables, it's just that trying to access the variables inside of these objects have issues.
![image](https://github.com/godotengine/godot/assets/75461200/dfbbfedc-6832-4cce-87d3-df4d51bc1060)

Here's a temporary solution, but very hacky and kind of ruins the clear (I am an autoload) that autoload variables give:
![image](https://github.com/godotengine/godot/assets/75461200/c09da7b5-163d-4402-9058-29c99fe68d89)

### Steps to reproduce

1. Create a script that has a variable, give it a class name
2. Create an autoload script, store a variable inside the autoload script that is statically casted to the script you created in step one
4. Create another script, try to access the autoload's variable's variable, you will see that the variable inside the autoload is picked up by intellisense, but the variable inside of the variable is not picked up by intellisense.

### Minimal reproduction project

[autoload_intellisense_issue.zip](https://github.com/godotengine/godot/files/11795196/autoload_intellisense_issue.zip)

**Comment by AThousandShips** [comment]
Think I saw something similar somewhere, will see if I can find it
