### ISSUE TITLE
GDScript: typed arrays are not empty after initialization

### ISSUE THREAD

**Issue by markusneg** [godotengine/godot#78461]
### Godot version

4.0.3-stable

### System information

Linux Mint 20.3

### Issue description

Typed arrays contain one element after initialization. The element has a foreign type as it is of type RefCounted when the array type is a built-in class without attached script and a Resource pointing to the script of the class when the array type is a custom GDScript class of the same type, respectively.

### Steps to reproduce

Reproducing the bug seems to be very straightforward: create a typed array in GDScript and observe it holding one element.

### Minimal reproduction project

[typed_array_not_empty.zip](https://github.com/godotengine/godot/files/11797151/typed_array_not_empty.zip)

**Comment by akien-mga** [comment]
Please provide a reproduction project or at least a clear code snippet. There are many ways to achieve what you describe and the details matter.

**Comment by markusneg** [comment]
> Please provide a reproduction project or at least a clear code snippet. There are many ways to achieve what you describe and the details matter.

Added it to the first post.

**Comment by akien-mga** [comment]
So yeah, the details did matter. It's not a bug, but you used the syntax wrong:
```gdscript
var typedArray := [MeshInstance3D]
```

This creates a valid named `typedArray` with an inferred type `:=`.
The type is inferred from the right hand side, which is `[MeshInstance3D]`, i.e. an untyped array containing a reference to the class `MeshInstance3D`. So it's expected that this array has size one.

With this code you could do:
```
typedArray[0].new()
```
and get an instance of MeshInstance3D.


What you wanted to do is:
```gdscript
var typedArray : Array[MeshInstance3D]
```
where `Array[MeshInstance3D]` is a type hint to make it a typed array of MeshInstance3Ds.

**Comment by markusneg** [comment]
> So yeah, the details did matter. It's not a bug, but you used the syntax wrong
Uh, kinda embarrassing. Sorry for wasting your time and thanks for the good explanation.
