### ISSUE TITLE
Skeleton causes error and project stops working when played when a camera3D is in the scene.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#78470]
### Godot version

4.1 b2

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

As you can see in the image:

![skeleton_error_41b2](https://github.com/godotengine/godot/assets/33526847/4003c5ef-b97b-4c00-986c-a085e6c285ef)

In the editor I have an imported model, no errors. The model has a skeleton. Moving bones moves the mesh accordingly no errors and nothing seems to be wrong as far as I can tell.

When I play the project without the camera I get no errors.
When I play the project with a Camera3D the project throws 12 errors (see the image above) and the whole project freezes without dispalying anything as you can see in the image it's just a gray window.

This model and import works just fine in 4.0.3, this is also not the only model I have issues with so it's not just this model.

I can't provide a test scene or models because these models are purchased but I hope the fact it works in 4.0.3 and the error could help?

I'll try anything you ask me to do to help to resolve this - hopefully before 4.1 get released.

NOTE: Same error and the following line as in the screenshot appear in the windows Console, no other errors.
NOTE2: This project was initiated from 4.1beta as brand new, nothing else is in as you can see.
NOTE3: I'll need to double check but I had some models working before so it might not be with every model but I'll check later on today.

### Steps to reproduce

Hard to tell, if you have a model with a skeleton give it a try, add the model t othe scene, camera3d and then see if it happens?

### Minimal reproduction project

~~For now check this one from another report: https://github.com/godotengine/godot/issues/77780~~

[TestMeshWithSkinGD.zip](https://github.com/godotengine/godot/files/11851108/TestMeshWithSkinGD.zip)

EDIT:
Related line where the editor takes me to: https://github.com/godotengine/godot/blob/a2575cba48121a9e31c3a550ebd29398a7facf3f/servers/rendering/renderer_rd/storage_rd/mesh_storage.h#L693

**Production team edit:** Added the non-mono MRP (reduced to fit Github's size limit) to the issue.

**Comment by enxas** [comment]
I have reported similar problem with `ERROR: Condition "skeleton->size == 0" is true. Returning: RID()` a while ago #77780. I have provided MRP there, so lets hope someone can figure it out.

**Comment by viksl** [comment]
@YuriSizov I'm not sure about the solution. I compiled the engine with the fix and it hides the errors but I still have issues, my character still doesn't render. It does render in the editor itself but when I hit the play button the 3D camera doesn't show the character.

Should I open a new bug report or ask to reopen this in case it's related?

**Comment by YuriSizov** [comment]
@viksl Make sure you have environment configured. If there is no source of light in the scene, you won't be able to see anything. There is a preview environment in the editor, but there is nothing at runtime, unless you add it yourself. (You can copy the preview environment, if you want).

**Comment by viksl** [comment]
@YuriSizov I have everything set up, the scene works just fine in 4.0.3 too. In the video I have it with and without environment just in case but the camera can see the model in the editor but not after I hit the play button for some reason and why it works in 4.0.3? I'm confused.

**Comment by YuriSizov** [comment]
If you upload an MRP, someone can take a look.

**Comment by viksl** [comment]
@YuriSizov That's the issue, the model's license doesn't allow that :'/. I'm not sure what to do exactly.

**Comment by bitsawer** [comment]
I'm starting to think that the skeleton errors maybe weren't the cause of the actual issue here, I guess they were just a visible thing to pin the visual error to, but looks like the real reason could be elsewhere.

So at least the issue title could probably be changed. And like YuriSizov says, it's hard to do anything without a test project, it would just be an endless guessing game.

**Comment by viksl** [comment]
@bitsawer well I wish I could provide the project as is.
I don't think the issues is the cullmask at least not from me since this is a fresh new project made only for this case so everything has default settings I did not change anything.
Second thing is that I opened this very project in 4.0.3 straight and it worked, if it was cull mask shouldn't it that also not work in 4.0.3 then?

OH! I can provide a test project, I just downloaded a character from mixamo and it has the same issue, so I'll quickly put together an MRP. Where do you want me to put it, new bug report or here and have someone reopen this or ...?

**Comment by bitsawer** [comment]
You can post the test project here, I can take a look. If it's not related to skeleton stuff we can always make a new issue later.

**Comment by viksl** [comment]
@bitsawer Here's the project: https://we.tl/t-DS8T1dlcbm, it's above the github file size limite so I had to upload it to wetransfer, is that ok with you?

**Comment by bitsawer** [comment]
I downloaded the test project and I can repro the issue. I'll try to dig a bit deeper and try report back in a few days or next week.

I think this could be re-opened for now, although the title can be a bit misleading if the issue is not actually caused by a skeleton bug (then again, maybe it is).

**Comment by viksl** [comment]
@bitsawer I guess that's up to @YuriSizov if he reopens it again? If you come later back figuring out it's not a skeleton issues than I can still change the name but for now this is the best I can tell since I have no idea what else to name it.

Btw, could be caused by the fbx importer in some way? Although I guess that should show in the editor as well, shouldn't it?

Thank you for checking it out so quickly and confirming the issue!

**Comment by viksl** [comment]
@bitsawer
1. I've tried reexporting the model through blender as GLTF2 and the issues is the same.
2. If I import without skin then the character gets rendered just fine so I assume the issue might be related to it somewhere.

**Comment by akien-mga** [comment]
Tested, the regression seems to start with 4.1-dev3 (both the skeleton error, and the fact that it doesn't render).
In 4.1-dev2 it works as expected.

Would be worth bisecting further, it's still a lot of changes: https://godotengine.github.io/godot-interactive-changelog/#4.1-dev3

**Comment by adamscott** [comment]
Added the `topic:rendering` label as this might be related to the rendering.

**Comment by adamscott** [comment]
@viksl Could you create a minimal reproduction project? The "MRP" you linked in #77780 is:

- using C# files and the mono release of Godot. We usually ask contributors and users to share a MRP that uses the base release of Godot, as this is easier to debug;
- is not a "minimal" project in itself. As a lot of factors can influence the existence of an issue, we suggest users reporting issues to create a project that contains the minimal setup to reproduce the issue.

> - A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the .godot folder in the archive (but keep project.godot).
> - Note for C# users: If your issue is not Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

Thank you!

**Comment by viksl** [comment]
@adamscott the #77780 is not mine project, that's someone else's. I linked an MRP here in the chat above (https://we.tl/t-DS8T1dlcbm) since the project file is larger than git limit it's on a temporary link which will expire in 6 days.

**Comment by adamscott** [comment]
@viksl I took your non-mono editor MRP and reduced the textures to the 1/4 of their original size.
[TestMeshWithSkinGD.zip](https://github.com/godotengine/godot/files/11851108/TestMeshWithSkinGD.zip)

**Comment by adamscott** [comment]
CC. @lyuma, @fire and @TokageItLab

**Comment by bitsawer** [comment]
Bisected the regression to https://github.com/godotengine/godot/pull/75901 and made a PR that fixes this: https://github.com/godotengine/godot/pull/78623 Feedback welcome, the logic there feels a bit weird.

**Comment by viksl** [comment]
@bitsawer in the https://github.com/godotengine/godot/pull/78623 you mentioned main thread but you can also set the group to sub thread and it will also work, I'm not sure if it means anything, is there at this point even a difference between the choice of main/sub thread or is it not yet implemented (since group order can't be changed anyway)?

Thanks for looking into this, I appreciate a lot!

**Comment by adamscott** [comment]
@viksl Forgot this detail about MRPs for your future reporting of issues. :slightly_smiling_face: 

Don't forget to delete the `.godot` directory from the zip before upload, because it takes a lot of space (like, in the zip you gave, it takes 50% of the size of the zip!) and that directory is not needed to open the project.

**Comment by viksl** [comment]
> @viksl Forgot this detail about MRPs for your future reporting of issues. 🙂
> 
> Don't forget to delete the `.godot` directory from the zip before upload, because it takes a lot of space (like, in the zip you gave, it takes 50% of the size of the zip!) and that directory is not needed to open the project.

Oh, I see. I should have also removed the textures to reduce the size. I was tuneled so much on the issue and trying it out that I failed to properly think about the rest. Thanks for the info, definitely nice to know .godot is not necessary ;).
