### ISSUE TITLE
Interpolated particles

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7850]
I found out that when a `Particles` node has an `amount` higher than FPS while moving (here set at 100 with a lifetime of 0.5), the result is not exactly as expected:
![image](https://cloud.githubusercontent.com/assets/1311555/23109463/d1ef5d92-f719-11e6-8c3d-2e1ee659733c.png)
As you can see, it emits "packets" of particles, instead of emitting through a continuous line, and will always be bound to that no matter how much is the `amount`.

The reason why is that the current Particles system emits particles only once per frame, and all at the same location, instead of compensating for the time spent between frames.

Would it be possible to have it interpolate particles emitted between frames?

**Comment by bojidar-bg** [comment]
Can confirm, and I'd say it's a bug...

**Comment by reduz** [comment]
will see how to address this in 3.0, i guess

**Comment by reduz** [comment]
this is addressed in current implementation, particles are intepolated, so closing this

**Comment by zhagsenkk** [comment]
The problem still exits now.
