### ISSUE TITLE
SpotLight3D turns negative, and creates black boxes on small angles with volumetric fog

### ISSUE THREAD

**Issue by Jonne-G** [godotengine/godot#78500]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10, AMD 5 5600G, RTX 3060, Forward+ Shading

### Issue description

When creating a SpotLight3D in a scene with fog, the light will first invert (e.g. opposite colours) and then create black splotches as seen in the screenshots below:

Angle of 2.0 degrees, range 15.0
![Godot_v4 0-stable_win64_WCqaG9lyQk](https://github.com/godotengine/godot/assets/60442130/2bf299a2-1046-424b-85b6-87dc3855af09)

Angle of 1.0 degrees, range 15.0, 
![Godot_v4 0-stable_win64_1cBv1k55nQ](https://github.com/godotengine/godot/assets/60442130/6bd6e7e2-4239-4f8a-96ef-3b41de9d17fb)

### Steps to reproduce

Create a spotlight with the following settings:

range: 15
angle: 1.0

Colour: ff3e00
Energy, Indirect Energy, and Volumetric Fog Energy: 500

Size: 1.0 m

And a world environment with volumetric fog on set to defaults.

Note that any angle below 3 seems to act strangely.

### Minimal reproduction project

Note for opening the project: The scene opens with the camera close to the center of the scene.
Make sure to toggle the volumetric fog off and on to reset the dark spots.

[SpotLight3DBugRepro.zip](https://github.com/godotengine/godot/files/11811412/SpotLight3DBugRepro.zip)

**Comment by clayjohn** [comment]
This looks suspiciously similar to a bug we already fixed. Could you try again with 4.0.3 to see if the bug has been fixed already?

**Comment by Jonne-G** [comment]
I tried with the latest available build, but the issue still persists.

**Comment by Calinou** [comment]
I can confirm this on v4.1.beta.custom_build [f2ce0b674] (Linux, GeForce RTX 4090 with NVIDIA 530.41.03). Disabling volumetric fog resolves the issue.

![image](https://github.com/godotengine/godot/assets/180032/8d316986-77c6-4fd6-b375-9293e9ac9202)

**Comment by viksl** [comment]
This happens not just with SpotLight3D but also OmniLight3D (, and I could almost swear directional light too), in 4.1rc3 win 10, 1660Ti.

**Comment by viksl** [comment]
I can reproduce this at least partially in 4.1.1 but not in 4.2 master, @Jonne-G can you please check? Though I think there are three issues included here.

**Comment by Jonne-G** [comment]
@viksl I tried in 4.2 with temporal reprojection turned off and on.
With it off, the black spot stays on the light, whilst with it on it will slowly cover the scene.

I don't think the reprojection is the issue, from what I can tell it is working as intended i.e. reprojecting lighting data from previous frames to new ones. It's just that it gets garbled data.

Unless I'm misunderstanding what you are referring to.

**Comment by viksl** [comment]
@Jonne-G interesting, for me it looks way different at this point and I've been testing it to see if it spreads or not for hours and nothing on my side (win 10, nvidia gpu too), I also had it tested on linux with nvidia gpu and nothing but neither of these GPUs were rtx ones.

The light turning negative on its own without checking negative checkbox also still happens?

**Comment by viksl** [comment]
I noticed that when I change the Volume Depth to at least 256 (in the video I use 512) and then up the Detail Spread to values above 5.5 I start getting similar issue (the black areas) which spread around.

Video here: https://youtu.be/Vz-fKhp5scQ

I also noticed going through the shader code that on line 426 I get INF and -INF values:
https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/servers/rendering/renderer_rd/shaders/environment/volumetric_fog_process.glsl#L426C8-L426C8

Particularly it comes from:
`normalize(view_pos)`

It happens only for one frame and then I get some float values but during this one frame NaN values spread later on where the total_light is used into prev_ textures and such and then keep spreading in frames afterwards.

Again the black areas are only visible with temporal reprojection on, if you turn it off it's hidden, if you turn it back on it shows just like it showed previously (meaning it's still storead in the texture I assume). The only way to get rid of this is either to quickly move the camera in the opposite direction or turning the volumetric fog itself on and then on again but if the `detail spread` values are still set above 5.5 (in my case) then it will start again and it will spread again (though the texture seems to get reset as expected).

**Comment by viksl** [comment]
I was finally able to reproduce this now after I made a HW upgrade (no idea why it does this only with certainl HW?), can you please test this:
https://github.com/godotengine/godot/pull/82546

It's the same fix which was used with gles3, I don't know if this is also ok for vulkan side or not? If nothing else it does fixes this issue on my side.
