### ISSUE TITLE
The Rider option does not start Rider, but Custom does.

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#78501]
### Godot version

4.1.beta2.mono

### System information

Godot v4.1.beta2.mono - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Sun Jun  4 18:26:12 UTC 2023 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 530.41.03) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

The Rider option does not start Rider, but Custom does.
https://github.com/godotengine/godot/assets/52148221/26ffbaa6-0835-4b5e-98a3-cfa137ee7252
error:
```modules/mono/glue/runtime_interop.cpp:1325 - Error when trying to run code editor: JetBrains Rider. Exception message: 'Cannot start process because a file name has not been provided.'```

### Steps to reproduce

1. External Editor select Rider and double click on the cs file.
2. External Editor select Custom and double click on the cs file.

### Minimal reproduction project

None

**Comment by raulsntos** [comment]
It looks like Godot can't find the path to JetBrains Rider. It tries to locate it from:

- The desktop file in: `$HOME/.local/share/applications/jetbrains-rider.desktop`.
- If installed using snaps: `/snap/rider/current/bin/rider.sh`.

Do any of those files exist in your computer? How did you install Rider?

Also, to be honest the error could be improved, we should check if the path is empty before attempting to start a process.

**Comment by scgm0** [comment]
> It looks like Godot can't find the path to JetBrains Rider. It tries to locate it from:看来 Godot 找不到通往 JetBrains Rider 的路径。它试图从以下位置找到它：
> 
> * The desktop file in: `$HOME/.local/share/applications/jetbrains-rider.desktop`.桌面文件在： `$HOME/.local/share/applications/jetbrains-rider.desktop` 。
> * If installed using snaps: `/snap/rider/current/bin/rider.sh`.如果使用快照安装： `/snap/rider/current/bin/rider.sh` 。
> 
> Do any of those files exist in your computer? How did you install Rider?您的计算机中是否存在这些文件？你是如何安装 Rider 的？
> 
> Also, to be honest the error could be improved, we should check if the path is empty before attempting to start a process.另外，老实说错误可以改进，我们应该在尝试启动进程之前检查路径是否为空。

My rider is a yay installation and the desktop is located at /usr/share/applications/jetbrains-idea.desktop

**Comment by raulsntos** [comment]
@van800 Should we add other hardcoded locations to check for a Rider installation to `RiderPathLocator`?

**Comment by van800** [comment]
I am planning to make an improvement in `RiderPathLocator`, which will be addressing a change in the JetBrains Toolbox app. Specifically Toolbox 2.0. I can add the paths mentioned above together with those changes. @raulsntos wdyt?

**Comment by van800** [comment]
I have to update my answer.
@scgm0 could you please recheck that the desktop file in your case is `jetbrains-idea.desktop` and not `/jetbrains-rider.desktop`
I would strongly suggest to use the JetBrains Toolbox App.

I am preparing a pull request with support for the Toolbox 2.0.

**Comment by scgm0** [comment]
> JetBrains Toolbox

Sorry, I've switched to using JetBrains Toolbox as I found that the rider it installed could be started properly.

**Comment by van800** [comment]
It makes total sense.

**Comment by van800** [comment]
I think this may be closed now. Since the improvement for Toolbox 2.0 was made. https://github.com/godotengine/godot/pull/78832

**Comment by scgm0** [comment]
> I think this may be closed now. Since the improvement for Toolbox 2.0 was made. #78832我想这可能现在已经关闭了。自 Toolbox 2.0 进行改进以来。 #78832

Thanks！

**Comment by akien-mga** [comment]
Fixed by #78832.

**Comment by alex-dearden** [comment]
I'm getting this error again with Godot 4.1.2 and Rider  2023.2.1. 
Rider is installed and the path is correct under DotNet Editor in project settings

**Comment by willschroeder** [comment]
Also encountering same issue as alex-dearden

**Comment by klianc09** [comment]
@alex-dearden it's important to note that in the Editor Settings the "Custom Exec Path" will be ignored unless you select "Custom" for External Editor. 

To provide another data point:
I've got rider installed via yay, I just pointed the custom exec path to "/usr/bin/rider" and that works fine, and I have a desktop file at "/usr/share/applications/rider.desktop"

**Comment by alex-dearden** [comment]
Yep, I understand that but my confusion comes from the fact that I shouldn't need to use Custom as Rider is installed in /Applications which is the default path. 

Even changing it to Custom didn't work. I had to change it to: `/Applications/Rider.app/Contents/MacOS/rider`

And that did the trick. Might be nice to have a hint for us Mac users in that property maybe?

**Comment by thisiskc** [comment]
> Yep, I understand that but my confusion comes from the fact that I shouldn't need to use Custom as Rider is installed in /Applications which is the default path.
> 
> Even changing it to Custom didn't work. I had to change it to: `/Applications/Rider.app/Contents/MacOS/rider`
> 
> And that did the trick. Might be nice to have a hint for us Mac users in that property maybe?

Just want to second that adding `/Contents/MacOS/rider` to the path worked for me after redownloading Rider via Toolbox (rather than directly, as I had before!) Thanks for this!

**Comment by willschroeder** [comment]
I had to set the `Custom Exec Path` field to `/Users/will/Applications/Rider.app/Contents/MacOS/rider`

My mac username being `will`, so replace it with yours

**Comment by bgiromini** [comment]
@willschroeder that worked for me as well. In my case, I have my user directory installed on an external drive.
