### ISSUE TITLE
Convex Decomposition not functional in Godot 4.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#78515]
### Godot version

4.0.3.stable

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

The "Create Multiple Convex Collision Siblings" option in the MeshInstance context menu does not actually create multiple Collisionshapes like it's supposed to. It always just creates a single shape no matter what the mesh is.
This worked fine Godot 3 so I'm guessing some regression has happened.

### Steps to reproduce

1. Download and open the MRP.
2. Select the suzanne MeshInstance3D node.
3. Open the MeshInstance3D context menu above the 3D editor viewport.
4. Select "Create Multiple Convex Collision Siblings" in the menu.

### Minimal reproduction project

[cd_mrp.zip](https://github.com/godotengine/godot/files/11816613/cd_mrp.zip)

**Comment by EzraT** [comment]
I just found out this has been fixed in v4.1-beta2, I wasn't able to find an issue on this, so I assumed it wasn't known yet.
This issue can be closed.

**Comment by smix8** [comment]
PR https://github.com/godotengine/godot/pull/72152
