### ISSUE TITLE
Inside parented _notifcation handle, attempt to start timer fails

### ISSUE THREAD

**Issue by ErgoPraxis** [godotengine/godot#78525]
### Godot version

v4.0.3.stable.custom_build [5222a99f5]

### System information

Linux

### Issue description

Issue: 
I have a Node2D where I handled the NOTIFICATION_PARENTED event. Inside that handle, I try starting a timer, which is a child of the Node2D in the scene tree. The timer does not start. 

Workaround: 
For now, instead of trying to start the timer directly, I set a boolean, queue_timer. During the _process method, I check if queue_timer is set, then clear it and start the timer. This effectively delays the execution to the next frame. 

I suspect the issues lies in how the timer node is reparented. Does it prevent starting until after the _notification method finishes? If so, is this a bug, or a feature? Though, my workaround works, I don't like that it has to check a condition every idle frame. 99% of the time this is wasted check.

### Steps to reproduce

Create scene tree,

* root_node : Node2D
  * timer_test : Timer
  * new_parent : Node2D

Attach a script to the root_node and add the following, and **connect the timeout signal to the last function**

NOTE: the _input event is just so you can click and know for certain that the "timer has timed out" message should print 1s later.
```
func _input(event):
	if event is InputEventMouseButton:
		var timer : Timer = $timer_test
		remove_child(timer)
		$new_parent.add_child(timer)

func _on_timer_test_timeout():
	# will never run
	print ("timer has timed out.")
```

Attach a script to the timer_test node and add the following,

```
func _notification (what):
	match what:
		NOTIFICATION_PARENTED:
			print ("parented: ", get_parent())
			start()
```

### Minimal reproduction project

[2023-06-21_timer_parented_start_bug_test.zip](https://github.com/godotengine/godot/files/11820966/2023-06-21_timer_parented_start_bug_test.zip)

**Comment by RedMser** [comment]
You're getting the error message "Timer was not added to the SceneTree. Either add it or set autostart to true." since the `NOTIFICATION_PARENTED` is emitted [before the SceneTree is assigned](https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L1366).

I am not sure why the order is this way, but in your specific example the best solution would be to simply use `autostart` to let the timer start after reparent.

Another solution would be to use `start.call_deferred()` inside of the notification instead of `start()`, which avoids doing the whole "polling a boolean value each frame".

**Comment by ErgoPraxis** [comment]
Ah, the ```start.call_deferred()``` is a genius solution! Thank you for the quick reply.

I assume the order of scene tree adding and _notification_parented was a design decision? ... I'll leave this issue open for a bit just in case it's not. 

Side note: I did try the autostart, but was unsuccessful in getting it to work. Since the call_deferred() works beautifully, I'll use this instead.

**Comment by YuriSizov** [comment]
Being parented doesn't mean it's in the scene tree, it just means it has a parent. I can still be a part of a branch that is detached and orphan. You can use the enter tree method or notification to detect when the node enters the tree.

**Comment by ErgoPraxis** [comment]
Oh, I see. Then, I'll go ahead and close the issue since this isn't a bug. Thank you all for the help!
