### ISSUE TITLE
Printing with print_rich a lot of colored text breaks formating after output overflow.

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#78520]
### Godot version

4.1 

### System information

Win 10

### Issue description

![image](https://github.com/godotengine/godot/assets/3350340/fb4d82dc-0301-46d4-85e8-032c32b09fcf)

When causing _"output oveflow"_ by printing a lot of text, formating breaks. Possible because enclosing tag get flushed.

Suggested solution: clear text formating after _output oveflow_ warning.

### Steps to reproduce

Print a lot of text with different text tags (like [color] or [bgcolor]) to console. For example in _process function.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@bruvzg Is there a way to reset formatting for all tags in RichTextLabel? We could use `print_rich()` for this before printing the "[output overflow, print less text!]" error.

**Comment by bruvzg** [comment]
There's no exposed function for this, but it should be easy to implement it, something like:
```c++
void RichTextLabel::pop_all() {
	_stop_thread();
	MutexLock data_lock(data_mutex);

	current = main;
	current_frame = main;
}
```
