### ISSUE TITLE
Engine freezes when calling Sprite.new() from joy_connection_changed callback

### ISSUE THREAD

**Issue by Minimuino** [godotengine/godot#78531]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Debian 11 - Intel Ivybridge Mobile - GLES3

### Issue description

Pretty much what the title says, the engine freezes when I call Sprite.new() from a method that I previously connected to `joy_connection_changed` signal. No errors are shown.

### Steps to reproduce

1. Run the minimal reproduction project, you will see the Godot icon moving around.
2. Connect or disconnect a gamepad and you will see the icon stops moving due to engine freeze.

### Minimal reproduction project

[minimal-reproduction-project.zip](https://github.com/godotengine/godot/files/11821885/minimal-reproduction-project.zip)

**Comment by rsubtil** [comment]
I recall having a similar issue on my addon, which required a hack to bypass (waiting a frame):
https://github.com/rsubtil/controller_icons/blob/db639c0288e3992c6f861b4f91041adfb5a2e2f4/addons/controller_icons/ControllerIcons.gd#L102-L111
This happened on Godot 3, but I never tested if it still happens on Godot 4. I can try to see what's going on.

In the meantime, to prevent this, you can yield for a frame:
```gdscript
func _on_joy_connection_changed(device, connected):
    yield(get_tree(), "idle_frame")
    # Now run your code, it should not freeze anymore
```

**Comment by Minimuino** [comment]
@rsubtil Thanks for the fix!
