### ISSUE TITLE
Non lowercase extension triggers silent error when importing FBX files

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#78535]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700S (Advanced Micro Devices, Inc.; 31.0.12024.2005) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When importing an FBX file if the path to FBX2gltF is not set Godot normally shows a popup indicating that, together with a link to download the converter. 
If the extension is uppercase (as is the case when exporting from Unreal) or anything other than lowercase, instead of the popup you get the following error.

```
- Could not create child process:  --pbr-metallic-roughness --input "C:/repos/FBX Import Fail/Room #1.fBx" --output "C:/repos/FBX Import Fail/.godot/imported/Room #1-408dbc91e4717f19e6488d2025606d51.glb" --binary
  modules/gltf/editor/editor_scene_importer_fbx.cpp:84 
- FBX conversion to glTF failed with error: 32758.
- Error importing 'res://Room #1.fBx'.
``` 

### Steps to reproduce

- Create a new project
- Add an an FBX file making sure it ends with .FBX and not .fbx
- Go back to Godot to trigger importing and getting the error
- Rename the file to .fbx to get the popup

Any capitalization other than lowercase triggers the bug

### Minimal reproduction project

The fbx file makes the mrp go over the maximum sized allowed by Github. 
You can download it here https://free3d.com/3d-model/low-poly-isometric-room-1-704614.html and add it to an empty project. Make sure to rename it so the extension is uppercase

**Comment by NiskashY** [comment]
Hi! I found that when reimporting we look at file extension without to_lower() specifier.
After i added it popup showed for .fbx files in different letter registers.

My PR:  #78567
