### ISSUE TITLE
[4.1.beta3][GDScript] Cannot call virtual function because it hasn't been defined.

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#78532]
### Godot version

4.1.beta3

### System information

Fedora Workstation 38 - Godot 4.1.beta3 - Vulkan (Forward+)

### Issue description

**This is an issue created by the production team, we're working on it**

Currently, it's impossible to call virtual functions within GDScript.

This currently returns an error:
```gdscript
# a.gd
extends Node

func _process(delta: float) -> void:
	pass
```

```gdscript
# main.gd
extends Node

var my_node: Node = preload("res://a.gd").new()

func _process(delta: float) -> void:
	my_node._process(delta)  # Cannot call virtual function "_process()" because it hasn't been defined.
```

### Steps to reproduce

1. Create a script (`a.gd`) based on `Node` that declares `_process()`;
2. Create a main node;
3. Attach a script to the main node;
4. Initialize a variable with a new `a.gd` instance;
5. Try to run `_process()` on that node;
6. Find out that it returns an error.

### Minimal reproduction project

[virtual_functions.zip (updated)](https://github.com/godotengine/godot/files/11823992/virtual_functions.zip)

**Comment by anvilfolk** [comment]
I think this might mean we need to partially revert #77324, without any replacement 😞 

The issue is that at compile-time we cannot check whether any `Object`, `Node` or otherwise, has a script attached. The script is the one responsible for implementing virtual functions, so the base type is simply not enough. I'll have a PR ready momentarily.

**Comment by hilfazer** [comment]
4.1.beta3 hasn't beed released yet.

**Comment by AThousandShips** [comment]
It was today

**Comment by hilfazer** [comment]
Ok, so the Gotot's front page wasn't up to date when i checked.
