### ISSUE TITLE
Wrong NodePath in tool mode

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot#78536]
### Godot version

3.5.2 stable

### System information

Kubuntu 22.04

### Issue description

An attempt to get a node using an absolute path in an editor with tool mode fails. The node has a strange path that doesn't match the scene hierarchy. 

The path looks like this:  /root/EditorNode/@@596/@@597/@@605/@@607/@@611/@@615/@@616/@@617/@@633/@@634/@@643/@@644/@@6618/@@6450/@@6451/@@6452/@@6453/@@6454/@@6455/Node2D/Icon

Instead of:  /root/Node2D/Icon

### Steps to reproduce

Open MRP and look at the output, then run the scene and compare the output with the previous one

### Minimal reproduction project

[path_in_editor.zip](https://github.com/godotengine/godot/files/11824311/path_in_editor.zip)

**Comment by theraot** [comment]
The editor is a scene, and the scene you are editing is instanced inside of it.

Although I understand it is unexpected, this is the way it works.

My opinion on the matter is that I'd rather not have this hidden, as having access to the editor scene can be very powerful for plugins. I believe it would a big change to offer means to hide it anyway.

Workaround by using relative `NodePath`s.

**Comment by vyshliy** [comment]
It looks useful. A little description in the documentation could clarify this point.

I would imagine that a separate property might exist to access the editor scene. It seems more logical for me to have the same behavior in the first place, and have access to the editor itself if necessary.
