### ISSUE TITLE
Hotzones of visual shader nodes are too small

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#78555]
### Godot version

4.1

### System information

Fedora, RX 590

### Issue description

Between 4.0.2 release and 4.0.3 RC1 the hotzone of the visual shader nodes have shrunk on the side that overlaps the node itself.
![Screenshot from 2023-06-22 12-14-19](https://github.com/godotengine/godot/assets/7917475/255feaf2-6e8c-4e7b-a1d9-0b86f28b1ec2)

### Steps to reproduce

Download 4.0.2 release and 4.0.3-rc1. 

Open MRP, navigate to hotzone.tres shader.

Zoom out to this level of zoom: 
![image](https://github.com/godotengine/godot/assets/7917475/5a3ffd5f-7760-4ced-a6aa-7861c2c1206f)

Try to extract a pin from ColorOp node.

In 4.0.3 you can observe how if you're not very precise you will drag the node around.

### Minimal reproduction project

[hotzone.zip](https://github.com/godotengine/godot/files/11832820/hotzone.zip)

**Comment by akien-mga** [comment]
Possibly a regression from #75595, CC @Geometror.

**Comment by QbieShay** [comment]
Attempted a quickfix with https://github.com/godotengine/godot/pull/78556. Fixes the issue for me. Consider merging for 4.1 because it significantly breaks UX for VS

**Comment by QbieShay** [comment]
It does however regress on the eye issue fixed by the original PR, but i personally think that clicking the eye is something that's done way less when developing VS.

**Comment by QbieShay** [comment]
Consider moving the eye instead 
![image](https://github.com/godotengine/godot/assets/7917475/97cc3236-7f10-4e77-9519-f42ffd1ee19f)
