### ISSUE TITLE
`window` node and `display/window/stretch/mode = canvas_items` malfunction 

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#78559]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

My monitor resolution is (3840, 2160)
project setting `display/window/size/viewport_width` , `viewport_height` is (1152, 648)
In `Control` node, stretch is correct. 
In `window` node, stretch is malfunction. 
When the window size is smaller, it will be even less clear.
![Control](https://github.com/godotengine/godot/assets/104408400/53aa6962-62d4-46a5-b110-d8c20e0591af)
![window](https://github.com/godotengine/godot/assets/104408400/36e7ba3b-8b44-448a-9b46-96d8a44b8eff)

### Steps to reproduce

look mini project

### Minimal reproduction project

[test_window.zip](https://github.com/godotengine/godot/files/11834014/test_window.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/54030, as this issue is due to the same cause.
