### ISSUE TITLE
Changing texture_normal.region causing TextureButton to became invisible until its howered by mouse

### ISSUE THREAD

**Issue by qwe3121** [godotengine/godot#78565]
### Godot version

4.0.3

### System information

not user specific I guess

### Issue description

Changing texture_normal.region causing TextureButton to became invisible (or not redrawn more likely) until its howered by mouse
But self.queue_redraw() fixes it
Not sure if its bug or not

### Steps to reproduce

All the things happens in minimal reproduction project

### Minimal reproduction project

[bug-or-feature.zip](https://github.com/godotengine/godot/files/11835048/bug-or-feature.zip)

**Comment by Sauermann** [comment]
I have testet the MRP and this got fixed between v4.1.dev3.official [a67d37f7c] and v4.1.dev4.official [5c2295ff5].
