### ISSUE TITLE
Duplicated geometry when importing .glb file

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#78564]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.2802) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

When importing an attached .blend file exported as .glb file, some of the triangles are duplicated. This effect appears as wrong light distribution and can be seen in overdraw debug view. All export and import setting are set as default. Exporting the same mesh to .dae or .obj works without problems.

![image](https://github.com/godotengine/godot/assets/7187363/ed16e130-8a22-4d15-840a-d6a6ef8b13d6)

![image](https://github.com/godotengine/godot/assets/7187363/a24e43ed-3590-4b4f-8656-a4299f215857)

![image](https://github.com/godotengine/godot/assets/7187363/c47d1dca-80ac-4fe5-b83d-849fa0ca41c6)

Source .blend file attached.
[corridor.zip](https://github.com/godotengine/godot/files/11834790/corridor.zip)

### Steps to reproduce

1. Export .glb file from Blender.
2. Import to Godot and switch to overdraw debug view.

### Minimal reproduction project

N/A

**Comment by mrjustaguy** [comment]
Unable to reproduce on Godot 3.5, 4.1 dev3, and 4.1 beta3, with glb, and both new and legacy obj. On Windows 11 and 1050 Ti

**Comment by shinyclaw** [comment]
Sorry - my mistake - closing issue.
