### ISSUE TITLE
In the scene tree dock, children of the inherited scene and of instantiated scenes lose their yellow text color when viewed by clicking on the scene tab.

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot#78577]
### Godot version

4.1-beta3

### System information

Windows

### Issue description

When an inherited scene's source has children, or when an instantiated scene is expanded with the editable children option in the scene tree dock, they are usually colored yellow. In beta3 this yellow color disappears under certain conditions. I've found it to happen when another scene is switched to through the tab menu, and then the current scene is opened again. It also happens when first opening the project. The text is colored yellow again when the scene is opened from file, or when it is edited from the scene tree dock.

### Steps to reproduce

https://github.com/godotengine/godot/assets/76705401/ae4a6314-873c-490d-9cc0-d85766702772

### Minimal reproduction project

Trivial

**Comment by AThousandShips** [comment]
Taken from #78751

### Steps to reproduce

1. Create a Node2D scene, add another Node2D node to it as a child
2. Create an inherited scene from that one (it opens in new tab, showing child nodes with yellow colored text)
3. Switch to a different tab
4. Switch back to the inherited scene tab

Similarly for editable children:
1. Create scene A, add a child node to it
2. Create another scene and add scene A as its child
3. Right click on scene A in the inspector and select Editable Children
4. Switch to another tab and then switch back
