### ISSUE TITLE
RenderingServer.LIGHT_PARAM_INTENSITY is not accessible to GDScript

### ISSUE THREAD

**Issue by cameron195** [godotengine/godot#78570]
### Godot version

4.0.3-stable

### System information

Linux 6.3.6-arch1-1

### Issue description

When using RenderingServer.light_set_param, the enum LIGHT_PARAM_INTESNITY is missing. It's usable in c++, as seen in [godot/scene/3d/light_3d.h](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/scene/3d/light_3d.h#L61), but isn't bound for GDScript in [godot/servers/rendering_server.cpp](https://github.com/godotengine/godot/blob/e74bf831c2d3ece79b849405f03999281f807648/servers/rendering_server.cpp#L1916) with the other LightParam enum values.

### Steps to reproduce

This code produces the error: Cannot find member "LIGHT_PARAM_INTENSITY" in base "RenderingServer".
```

var light_RID = RenderingServer.spot_light_create()
RenderingServer.light_set_param(light_RID, RenderingServer.LIGHT_PARAM_INTENSITY, 10)

```

### Minimal reproduction project

[MissingEnum.zip](https://github.com/godotengine/godot/files/11835811/MissingEnum.zip)

**Comment by AThousandShips** [comment]
Missed bind, straight forward to add

**Comment by brno32** [comment]
Does updating the documentation only entail updating `doc/classes/RenderingServer.xml`?
