### ISSUE TITLE
Grid view disappears

### ISSUE THREAD

**Issue by AlfonsoGrimaldo** [godotengine/godot#78588]
### Godot version

v4.1.beta.custom_build [522a2ea3f]

### System information

Windows 10, Vulkan, GTX 960 536.23

### Issue description

When the grid is disabled in a scene and subsequently closed, it will not be displayed again and will remain invisible unless you refresh it from the 'view' option. This doesn't happen with the origin, but sometimes its colors may appear faded if you try to activate the grid again.

### Steps to reproduce

https://github.com/godotengine/godot/assets/48926464/c31770de-55c3-403a-8d91-07fc1184cae1

Note: It is not necessary to open or create a scene, just follow the steps shown in the video.

### Minimal reproduction project

N/A

**Comment by Yadnesh-Kulkarni** [comment]
New contributor here. I have previous experience with GUI as well as graphics development. I would like to take this one.

**Comment by Loethor** [comment]
I can confirm the bug.

What would be the desired outcome? 
Should a new scene show both the grid and the origin even if they were disabled in the previous new scene?

**Comment by Yadnesh-Kulkarni** [comment]
@Loethor I think this should be the expected outcome. I have debugged through the code and found out the exact issue. Just trying to work on a solution.

**Comment by Yadnesh-Kulkarni** [comment]
@clayjohn if you can confirm that this is the expected outcome, it would be great.
