### ISSUE TITLE
The caret disappears from the text editor

### ISSUE THREAD

**Issue by AlfonsoGrimaldo** [godotengine/godot#78589]
### Godot version

v4.1.beta.custom_build [522a2ea3f]

### System information

Windows 10, Vulkan, GTX 960 536.23

### Issue description

When you open any of the File, Edit, Search, Go to, and Debug menus and then return to the script editor, the caret will become invisible. This also happens in the shader script editor.

### Steps to reproduce

https://github.com/godotengine/godot/assets/48926464/93345bae-7992-4bef-bd5f-920b7db733d1

### Minimal reproduction project

N/A

**Comment by lostminds** [comment]
Also just encountered this on macOS, 4.1.beta3, I've not seen it in previous versions.

**Comment by akien-mga** [comment]
Confirmed on Linux, seems to be a regression since 4.1 beta 3 (works fine in beta 2).

**Comment by Calinou** [comment]
I bisected the regression to 8cdab04d7fd57aaabd790349cd8a4e9ec21a7edd. cc @Sauermann 

Caret display and blinking is disabled when the window is unfocused. This likely occurs because opening a popup creates a separate window unless using **Single Window Mode** in the Editor Settings.

**Comment by akien-mga** [comment]
While I have no doubt @Sauermann could find a regression fix quickly, I wonder if it wouldn't be wisest to revert 8cdab04 for 4.1, and rework it for 4.2?
I was a bit trigger happy to merge a risky Window change so close to 4.1 RC 1, when it wasn't addressing a critical issue. WDYT @Sauermann?

**Comment by Sauermann** [comment]
@akien-mga I'm not opposed to reverting it, feel free to do so. That is likely the safer way.

**Comment by PIZZA-ALERT** [comment]
https://github.com/godotengine/godot/issues/93748
I'm having a similar issue where my mouse cursor is simply invisible when hovered over all text fields.
