### ISSUE TITLE
Project Settings freezes up Godot Engine

### ISSUE THREAD

**Issue by KelixKatz** [godotengine/godot#78594]
### Godot version

4.0.3.stable.mono

### System information

Windows 11 - 4.0.3.stable.mono - Forward+ - RTX 3070 - AMD Ryzen 5 5600X 6-Core Processor - 16.0 GB RAM

### Issue description

When I open project settings Godot engine freezes up

Clicking on anything, even trying to close godot does nothing, having to closing the console to close the program. Redownloading and Reinstalling godot does not fix the issue. I can still resize the godot engine window.

I expected the godot project settings window to pop up and godot to not just become unresponsive.

It only happens in one of my projects, which I cant list completely bellow because the problem or at least part of the problem is within the .godot folder.

I investigated the project folder and deleted the project_metadata file and that fixed it. I am not sure how it glitched out in the first place though, I did not manually edit that file and was not aware it existed until I encountered this problem.
The editor should check if the dialogs_bounds are off screen and reset them to normal. Otherwise, you cannot access them.

### Steps to reproduce

1. if you dont already have this problem, go into your .godot > editor > project_metadata.cfg file and set the project settings rect2 to something way off screen.
2. Click on Project on the upper left.
3. Click on Project settings

### Minimal reproduction project

N/A

**Comment by joehighton** [comment]
**Godot Version:** 4.0.3.stable using Forward+
Had the same issue, was able to resolve it the same way as stated in the orignal post by deleting the project_metadata.cfg

**Comment by sepTN** [comment]
I confirm that my Godot IDE freezing up when I have ridiculous value in my project_metadata.cfg

```
[dialog_bounds]

export=Rect2(510, 190, 900, 700)
search_help=Rect2(541, 191, 960, 540)
create_new_node=Rect2(267, 192, 900, 700)
editor_settings=Rect2(510, 190, 900, 700)
project_settings=Rect2(510, 190, 90000, 70000)
```

**Comment by Naradoxy** [comment]
This issue is still present in v4.2.1.stable. This issue also affects the "editor_settings" and potentially more under `[dialog_bounds]`.

Additionally, to manually fix this if it happens, in `project_metadata.cfg`, you can simply set the `[dialog_bounds]` values to something reasonable instead of deleting the file.
