### ISSUE TITLE
No EOF error in the editor at the start of a block

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#7859]
**Operating system or device - Godot version:** Linux Mint - Godot v2.1.2

**Issue description:** The editor (or lexer I think) doesn't notify for early EOF when the last line is a new block.

![screenshot from 2017-02-21 02-46-17](https://cloud.githubusercontent.com/assets/2700596/23147543/f97e6486-f7df-11e6-9580-6e9781545fd8.png)

It's nothing since we never do that, but for "pro aspect", this should be notifyed to the user.

**Comment by Calinou** [comment]
This seems to be fixed as of https://github.com/godotengine/godot/commit/b030834b6384d5f57e5fc63db21b643adc86b3da:

![image](https://user-images.githubusercontent.com/180032/63089721-1c577900-bf59-11e9-9516-d4a13d7d04a6.png)

(Notice how the last line doesn't have a line number.)
