### ISSUE TITLE
Script editor doesn't display font

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#7860]
**Operating system or device - Godot version:**
osx yosemite 10.10.5, Godot master

**Issue description:**
The script editor doesn't show any characters (except the tab indicator).
![osx_script_editor](https://cloud.githubusercontent.com/assets/8281916/23177339/b8215ec6-f866-11e6-8745-33e0f877c99f.gif)

**Comment by Hinsbart** [comment]
Update: this also seems to happen on windows. But not on linux, with a build of the same commit.

**Comment by akien-mga** [comment]
Duh, give steps to reproduce dude :P

Obviously this bug is no longer valid.
