### ISSUE TITLE
AutoComplete in GDScript not properly working for Nodes

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78606]
### Godot version

4.1.beta.3

### System information

Windows 11

### Issue description

In the editor if you are editing a script file in a different context of scene file than the script belongs, then autocomplete of node goes hay wire.

To clarify more: if you are in scene A and editing script of scene B, then autocomplete of scene nodes goes haywire.

https://github.com/godotengine/godot/assets/84369217/294adc6b-591e-4ecb-ba1e-5b0dd788cb0b

Note: This may be feature/limitation, but it happens too often in the workflow not to be fixed.

Additional Issue/ Limitation:
When typed $ in the script it should list down all the nodes and ignore all other values for autocompletion, which is not happening. 
I have not tested this 3.x but I think it worked in it.

### Steps to reproduce

Create a project with two scene(A and B) with attached scripts(A and B) respectively.
When you try to edit Script A while Scene B is selected, you will not be able to auto complete nodes.

### Minimal reproduction project

Will upload one if could not reproduce the issue

**Comment by ajreckof** [comment]
I think this will need a bit more details. What would happen if the script is attached to multiple scenes. And what about if the scene is not opened. Should it load it? Should it load all of the associated scene? Should it just ignore those that are not opened?
I think this could be a good feature to add but it would be more fitting in godot proposal with a detailed implementation at least answering the questions above

**Comment by dalexeev** [comment]
* See also godotengine/godot-proposals#1935.

**Comment by AThousandShips** [comment]
I was certain I saw an issue report for this exact issue before but can't find it right now

**Comment by tokengamedev** [comment]
I have tested this in 3.5.2 and it is the same scenario there, Hence It is a **limitation**.
Closing this as it will be addressed as part of proposal https://github.com/godotengine/godot-proposals/issues/1935 

I
