### ISSUE TITLE
Problem with displaying the popup (except the first time)

### ISSUE THREAD

**Issue by michaldev** [godotengine/godot#78605]
### Godot version

4.1 beta 3

The same project works fine on 4.1 **beta 1 and beta 2.**

### System information

Tested on MacOS, Fedora and HTML5

### Issue description

I have a problem in version 4.1 beta 3 with a popup (popup panel). The first time it always displays correctly. Every subsequent time, I only see a black spot. 

[Nagranie ekranu z 2023-06-23 11-35-28.webm](https://github.com/godotengine/godot/assets/5132385/f7a7ad08-754c-4b4b-b594-b6880eff5f3d)

*The same if I show popup by methods like popup_centered.

### Steps to reproduce

I'm trying to reproduce it with a clean and minimal example, but unfortunately, without success. Maybe someone else has this issue or knows a way to reproduce it?

### Minimal reproduction project

I'm trying to create it.

**Comment by akien-mga** [comment]
I don't see any changes to `PopupPanel` or `Popup` between 4.1-beta2 and beta3, but there have been changes to `Window` and `Viewport` which could maybe affect this. CC @Sauermann

**Comment by YuriSizov** [comment]
> I remember, that there have been some PRs that changed Control-minimal size calculations. I am just guessing, but perhaps it is related to that?

That was in beta 2 already.

**Comment by YuriSizov** [comment]
Can be rendering related? This project, judging by the screen capture, uses GL Compatibility and it manifests in a black screen. Similar to https://github.com/godotengine/godot/issues/78608 perhaps?

**Comment by akien-mga** [comment]
> Can be rendering related? This project, judging by the screen capture, uses GL Compatibility and it manifests in a black screen. Similar to #78608 perhaps?

@michaldev could test this hypothesis by temporarily running the project with the Forward+ renderer, to see if the bug disappears.

**Comment by michaldev** [comment]
> > Can be rendering related? This project, judging by the screen capture, uses GL Compatibility and it manifests in a black screen. Similar to #78608 perhaps?
> 
> @michaldev could test this hypothesis by temporarily running the project with the Forward+ renderer, to see if the bug disappears.

I just checked. On Forward+ there is no problem.

**Comment by YuriSizov** [comment]
cc @clayjohn

**Comment by michaldev** [comment]
Fixed in 4.1 RC 1.
