### ISSUE TITLE
Prior working project now builds to a black screen using the Compatibility Renderer

### ISSUE THREAD

**Issue by zapposh** [godotengine/godot#78608]
### Godot version

4.1 beta 3

### System information

Windows 11

### Issue description

Project builds and displays fine in all releases of Godot 4.x up until and including 4.1 beta 2.
When opening the project in 4.1 beta 3, it builds to a black screen, without crashing.

Switching from the Compatibility Renderer to Forward+ solves the issue.
Switching back to Compatibility breaks the build again

Reverting back to beta 2 also solves the issue, regardless of the renderer used.

### Steps to reproduce

- create a project in a version of Godot 4.x prior to beta 3, using the Compatibility renderer
- open and build the project in Godot 4.1 beta 3
- switch between different renderers to get the build to display 

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Could you run the project from the command line with the `--verbose` option (using the `_console.exe` binary so it properly shows output in the console), and paste the output here? Should be something like:
```
cd C:\path\to\project
C:\path\to\Godot_v4.1-beta3_win64_console.exe --verbose
```

**Comment by zapposh** [comment]
Godot Engine v4.1.beta3.official.ada712e06 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
NVAPI: Init OK!
NVAPI: Disabled OpenGL threaded optimization successfully
Using "wintab" pen tablet driver...
Shader 'CanvasSdfShaderGLES3' SHA256:
72cda41890bce2f09217c172023d31e735a3fee605bad83c8e63f1a981a36a77
Shader 'SkeletonShaderGLES3' SHA256:
add3f03e6eebdffdf0073fae42195857307eddada333b82998642329511917a2
Shader 'ParticlesShaderGLES3' SHA256:
9bf432d37b0b4792d67aa9f577258845d4047e3f98e990aeca6fd20a868c4db2
Shader 'ParticlesCopyShaderGLES3' SHA256:
c778843b0cd1c7ce4c621fa2b924f703ac4001faef0555114b81a76c264a6908
Shader 'CopyShaderGLES3' SHA256:
b1bc5a355ed9bda23f291956f121e0535b4e81b54cdac398412d200e6133161f
Shader 'CanvasShaderGLES3' SHA256:
007cddfcf35f7d57b219cffec53f6a7d9fe7a1979be4db64c6450cfac6000053
Shader 'CanvasOcclusionShaderGLES3' SHA256:
968915a469db9a7d505be274e8060c8288c15a5865baeb8362b3b0e2cacb16f3
Shader 'SceneShaderGLES3' SHA256:
7757391c487ac94cfa6418166bd5fdacce470f09394c1a2a875e878c8c5d8596
Shader 'SkyShaderGLES3' SHA256:
1fe105946e63973aecf5198091930c2bdb17778012ef0253e325ade3a297e6c8
Shader 'CubemapFilterShaderGLES3' SHA256:
2b651c285a02b7d4221af1827e1613c03e73e600ebc40b9e6a0b22bb855bd75f
OpenGL API 3.3.0 NVIDIA 535.98 - Compatibility - Using Device: NVIDIA -
NVIDIA GeForce GTX 1080 Ti
WASAPI: Activated output_device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 480
WASAPI: min_period_frames = 480
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite
(Built-in)".
CORE API HASH: 141380681
EDITOR API HASH: 546665002
Loaded system CA certificates

**Comment by clayjohn** [comment]
Could you provide a bit more information about your project? For example, what node types you use. I am not seeing the same problem in my projects, but I may be missing some crucial element that is causing the issue.

**Comment by zapposh** [comment]
![godot_project_structure](https://github.com/godotengine/godot/assets/9380614/bacddcdc-6e0e-4442-906d-9643d394328c)

Here is the basic project structure.
Levels are loaded in under the scene manager, but I cannot even get that far in beta 3. Other versions work fine.

Let me know if you need anything else.

**Comment by clayjohn** [comment]
@zapposh Is your SubViewportContainers filter mode set to nearest? I can reproduce a black screen with the following setup:
![image](https://github.com/godotengine/godot/assets/16521339/a5133432-2b28-4785-896b-b6b4fb17ada4)

So long as the SubViewportContainer is using nearest filtering

**Comment by zapposh** [comment]
Affirmative, Filter is set to Nearest.

**Comment by clayjohn** [comment]
Okay, most likely a regression from https://github.com/godotengine/godot/pull/78285. Should be a quick fix
