### ISSUE TITLE
Last line missing in the editor to edit a uniform mat4 

### ISSUE THREAD

**Issue by Tetane** [godotengine/godot#7861]
Godot 2.1.2.stable.official (from Steam) on windows

The menu to edit a "uniform mat4" in the editor is missing the 4th line.
`uniform mat4 MM;`
![image](https://cloud.githubusercontent.com/assets/13542748/23179846/9fa41a92-f86f-11e6-87e4-2982d12fec7b.png)

And the name of my variable is "MM" not "Mm" as displayed in the editor.
And in the editor, the letter that describe the 4th column is "o" but in the shader language it's "w".

**Comment by Zylann** [comment]
I think the reason is that this editor was meant for Matrix34, which itself was oriented to mean "model matrix" rather than a general purpose matrix (so the o here means origin).

**Comment by bojidar-bg** [comment]
Tagging for 3.0, since we might want to reconsider this in the new shading language.

**Comment by reduz** [comment]
Godot does not support 4x4 matrices, ao there is no way to expose this
datatype fully. It does not really have much practical use anyway.

**Comment by reduz** [comment]
this is a wontfix, since Godot does not support this datatype and supplying the missing line has no pratical use
