### ISSUE TITLE
CharacterBody2D infinite flipping on left move

### ISSUE THREAD

**Issue by Sethyh** [godotengine/godot#78613]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11 - Vulkan (Foward+) - NVIDIA GeForce GTX 1050 Ti

### Issue description

The CharacterBody2D node is constantly changing the x scale when I move the character to the left and the x scale to the right seems to preserve the current scale.

For example, if during movement the scale.x is alternating between -1 and 1, when stopping the character, if the scale x is negative (scale.x = -1), when moving to the right, it does not change the scale to 1 (making the character look to right), even though I say in the code that, if the character move to the right, the scale.x = 1.

### Steps to reproduce

Steps to reproduce:
1. create a structure like this:
![Captura de tela 2023-06-22 215824](https://github.com/godotengine/godot/assets/124723203/f345b643-074d-4215-b3cf-6c8f39f4237f)

2. Put this script atached to CharacterBody2D:
[CharacterBody2d script.txt](https://github.com/godotengine/godot/files/11849379/CharacterBody2d.script.txt)

### Minimal reproduction project

Project to test
[testes.zip](https://github.com/godotengine/godot/files/11849427/testes.zip)

**Comment by Roscomo** [comment]
My understanding is that this is just the nature of setting the scale of a 2D node. If you set `scale.x` to a negative It will rotate the node 180 degrees and give it a negative y scale (which is visually the same thing). Since `scale.x` itself is unchanged it will keep doing this transformation every time you set `scale.x` to a negative value hence the infinite flipping. 

This is what the documentation has to say about it:
![image](https://github.com/godotengine/godot/assets/24512892/1eacd639-7543-4b34-a334-7747883b3749)

If you want to simply flip the image you could just use `Sprite.flip_h = true\false`

**Comment by Sethyh** [comment]
Hi Roscomo and thanks for replying...

yes, I know the documentation talks about it, but that's not what's been happening to me... if I use the same commands and logic in the Sprite2D node, everything works fine. However, I need the CollisionShape2D aggregated to CharacterBody2D to be mirrored as well and I could achieve this by mirroring CharacterBody2D (since the child nodes mirror together with the parent node).

It's like if I gave the commands:
`$CharacterBody2D.scale.x = -1 #to the left`
`$CharacterBody2D.scale.x = 1 # to the right`

and Godot did:
`$CharacterBody2D.scale.x *= -1 #to the left`
`$CharacterBody2D.scale.x *= 1 #to the right`

**Comment by Sethyh** [comment]
Hi Cole and thanks for replying...

Yes, I know the documentation talks about it, but that's not what's been
happening to me... if I use the same commands and logic in the Sprite2D
node, everything works fine. However, I need the CollisionShape2D
aggregated to CharacterBody2D to be mirrored as well and I could achieve
this by mirroring CharacterBody2D (since the child nodes mirror together
with the parent node).

It's like if I gave the commands:
$CharacterBody2D.scale.x = -1 #to the left
$CharacterBody2D.scale.x = 1 # to the right

and Godot did:
$CharacterBody2D.scale.x *= -1 #to the left
$CharacterBody2D.scale.x *= 1 #to the right

Em sex., 23 de jun. de 2023 às 17:41, Cole ***@***.***>
escreveu:

**Comment by capnm** [comment]
```go
var direction = Input.get_axis("ui_left", "ui_right")
if direction:
       $Sprite2D.flip_h = direction > 0
```

**Comment by Calinou** [comment]
As mentioned above, you shouldn't flip the CharacterBody itself. Flip the visual representation instead.

**Comment by Sethyh** [comment]
Hi capnm and thanks for replying...

Maybe I'm not make myself clear: I need make a "flip_h" in a CharacterBody2D to flip all the children at same time but when I do a "scale.x = -1" in the CharacterBody2D node, seems that Godot executes a "scale.x *= -1" and stays flipping while I moves the character to the left (the "direction" from the code)

**Comment by Sethyh** [comment]
> As mentioned above, you shouldn't flip the CharacterBody itself. Flip the visual representation only instead (i.e. the Sprite2D node).

why not? can you explain me, please?

**Comment by Calinou** [comment]
> why not? can you explain me, please?

https://docs.godotengine.org/en/latest/tutorials/physics/troubleshooting_physics_issues.html#scaled-physics-bodies-or-collision-shapes-do-not-collide-correctly

**Comment by Sethyh** [comment]
the most of other nodes accept scale.x = -1
why not the CharacterBody?

**Comment by Sethyh** [comment]
My problem wasn't resolved....

Em sex., 23 de jun. de 2023 18:44, Hugo Locurcio ***@***.***>
escreveu:

**Comment by Calinou** [comment]
> the most of other nodes accept scale.x = -1 why not the CharacterBody?

PhysicsBody handles scale differently compared to other nodes. This was already explained above, as PhysicsBody needs to handle scale in some way to try to affect collision (but as you see, it often doesn't work out in practice).

The best way to avoid this issue is to avoid scaling PhysicsBody nodes and nodes that inherit from it, such as CharacterBody, RigidBody and VehicleBody.

**Comment by Sethyh** [comment]
> > the most of other nodes accept scale.x = -1
> > why not the CharacterBody?
> 
> PhysicsBody handles scale differently compared to other nodes. This was already explained above, as PhysicsBody needs to handle scale in some way to try to affect collision (but as you see, it often doesn't work out in practice).
> 
> The best way to avoid this issue is to avoid scaling PhysicsBody nodes and nodes that inherit from it, such as CharacterBody, RigidBody, StaticBody and VehicleBody. Scale the visual representations instead, and resize the collision shapes (but do not scale them).

Thanks, now I get it....

**Comment by F483** [comment]
I also have the same issue and I am sure more will come.

Solution to make an asymmetric character (boss with weak spot on the back) where I need to flip the hurt/hit box also.

Make a dedicated direction flipper component and put the relevant things under.

![image](https://github.com/godotengine/godot/assets/977605/f0bb57c4-cc24-41f6-abd4-c32fb011b427)

**Comment by Sethyh** [comment]
> I also have the same issue, my solution for an asymmetric character (boss with weak spot on the back) where you need to flip the hurt/hit box also.
> 
> Make a dedicated direction flipper component and put the relevant components under it.
> 
> ![image](https://github.com/godotengine/godot/assets/977605/f0bb57c4-cc24-41f6-abd4-c32fb011b427)
> 

Thanks... I've "solved" using the flip_h property of the Sprite2D, but your idea is very interesting... ^_^

**Comment by RedMune** [comment]
I also wanted to do what you originally asked and saw a bunch of posts saying you shouldn't do things that way but I did it anyways.
Warning: I just started learning how to code so this might be a really dumb thing to do.

First you need 2 variables. I used was_facing_right and is_facing_right
Then in my physics_process I run update_facing_direction() at the end and add these 2 functions to my script:

```
func update_facing_direction():
	if velocity.x < 0:
		was_facing_right = false
	elif velocity.x > 0:
		was_facing_right = true
	if is_facing_right != was_facing_right:
		flip()
```

```
func flip():
	is_facing_right = !is_facing_right
	scale.x = abs(scale.x) * -1
```

**Comment by jmkulakowski** [comment]
> I also wanted to do what you originally asked and saw a bunch of posts saying you shouldn't do things that way but I did it anyways. Warning: I just started learning how to code so this might be a really dumb thing to do.
> 
> First you need 2 variables. I used was_facing_right and is_facing_right Then in my physics_process I run update_facing_direction() at the end and add these 2 functions to my script:
> 
> ```
> func update_facing_direction():
> 	if velocity.x < 0:
> 		was_facing_right = false
> 	elif velocity.x > 0:
> 		was_facing_right = true
> 	if is_facing_right != was_facing_right:
> 		flip()
> ```
> 
> ```
> func flip():
> 	is_facing_right = !is_facing_right
> 	scale.x = abs(scale.x) * -1
> ```

Thank you! I searched everywhere for a solution to this issue. ChatGPT-40 and Gemini failed to figure it out. The logic in this video explained a solution, but the code implementation wasn't demonstrated in a game demo. 

the solution above was the only solution I could find that actually worked. So, thank you again. Kudos!
