### ISSUE TITLE
Objects not added to scene when code is in ready.

### ISSUE THREAD

**Issue by wagfeliz** [godotengine/godot#78627]
### Godot version

4.02.stable

### System information

Linux Ubunto 22.04

### Issue description

Related with duscussion on : https://godotforums.org/d/34891-objects-not-added-to-scene-when-code-is-in-ready
Code:
```
extends Node
@onready var ballmodel:MeshInstance3D = $"../BallModel"
@onready var rootNode:Node3D = $".."
func _ready():
	var nb = ballmodel.duplicate()
	nb.set_visible( true )
	rootNode.add_child( nb )
```
Basically, any attempt to create an object and add to scene on _ready(), for some reason dont work. It may be an expected behavior but I could not find a reason in documentation.
Same code using those approaches workaround this problem :
1) Create objects at the first frame : ( My suggestion of fix for this problem )
```
var firstframe:bool=true
func _process(delta):
	if(firstframe): _firstframe()
func _firstframe():
	firstframe=false
	... do anything you would put in _ready here and it will work ....
```
2) Suggestion from BroTa :
rootNode.call_deferred("add_child", nb) # This works ...

My point is that eater documentation should tell us that we should not create objects in _ready() function ( what removes the propouse of it in most cases ), and if this is the case, also we should have an _fisrtframe() vanila function also so we could avoid confusion and problems with this behavior. Or this is a bug that needs further investigation.

### Steps to reproduce

Just try to create an object in func _ready(), on gdscript. I didnt test on c# but I guess the result will be the same.
We expect something to point out why the object is not rendered in screen. 

### Minimal reproduction project

1) Create an basic 3D scene with camera and env, create an BallModel : MeshInstance3D with some ball mesh or anything in it, make it invisible. then white this script and atach to the main node : 

extends Node
@onready var ballmodel:MeshInstance3D = $"../BallModel"
@onready var rootNode:Node3D = $".."
func _ready():
	var nb = ballmodel.duplicate()
	nb.set_visible( true )
	rootNode.add_child( nb )
```

Expected result : 
The original ball is invisible, but the new created ball should be visible and shows in screen, but for some reason its in some kind of zombi state and dont render.
The expected result would be to see in screen this new ball.

**Comment by theraot** [comment]
You should be getting an error like this: `Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.` - Are you not?

**Comment by wagfeliz** [comment]
> You should be getting an error like this: `Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.` - Are you not?

I would be satisfied with an error, but no error.

**Comment by wagfeliz** [comment]
An notice, I was reviewing this case, and I notice I didnt add all the information, notice that the script is extend from NODE, what I did was to add a Node in the scene, and I attach the script in this Node.
The scene contains : 
WorldEnvironment
BallModel: MeshInstance3D -> containing some mesh, ex: box mesh
Camera3D -> pointing to the 0,0, in a way to see if the box is in the scene, like Vector3(0,0,3)
Node -> With this script attached

I did try with out this Node and it works , I have no idea why it dont work only if I use a Node...

**Comment by wagfeliz** [comment]
Another note, I test it with an Node3D and it works. Is this an intended behavior and should we always use call_deferred ?
If so, is this in the documentation ?

**Comment by Rindbee** [comment]
> > You should be getting an error like this: `Parent node is busy setting up children, add_node() failed. Consider using call_deferred("add_child", child) instead.` - Are you not?
> 
> I would be satisfied with an error, but no error.

This message appears in the Debugger instead of Output when running the scene. 

![1](https://github.com/godotengine/godot/assets/30386067/eae2a95e-1fc3-4ef1-b502-405810c2d625)

**Comment by YuriSizov** [comment]
As mentioned above, you should be getting an error about trying to add a child node to a node that is currently busy finishing its setup. There is no engine issue.

Also, please note that what you do is unreliable and is not recommended. When your node is ready you are attempting to access its parent and its sibling. Neither of these two nodes is guaranteed to be ready (in fact, the parent is guaranteed to not be ready at this point). So accessing them at this point can lead to errors and unpredictable behavior.

Your script should be instead on the parent node, or should be entirely deferred to run after the entire branch has been readied.
