### ISSUE TITLE
DocCache in the resource list

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#78647]
### Godot version

4.1.beta3 (again)

### System information

4.1.beta3 - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 Threads)

### Issue description

DocCache is listed in resources.
![image](https://github.com/godotengine/godot/assets/85438892/8a7bccab-a169-438f-b562-8b441396bf88)

If instantiated, it looks like this:
![image](https://github.com/godotengine/godot/assets/85438892/6e165950-19c7-4274-90e2-20527c48ef0d)

I can't find it in the Search Help menu. However, if I type it in the script editor and Ctrl+LMB, it leads to this documentation page:
![image](https://github.com/godotengine/godot/assets/85438892/ae79c3c1-01d8-4f25-a654-c53232968c24)

This is weird, as I just showed the class has properties. Normally, undocumented classes have fields for each undocumented property or method. This makes me think this is unintended. An undocumented class with members normally looks like this:

![image](https://github.com/godotengine/godot/assets/85438892/bbf1f47d-c947-44ac-8f34-c48f4fcad293)

### Steps to reproduce

Outlined above. F1 to open the Search Help menu. This button to create a resource:
![image](https://github.com/godotengine/godot/assets/85438892/e7b3f571-ad30-4b76-91ad-21918792af7b)

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/editor/editor_help.cpp#L2323-L2326

**Comment by akien-mga** [comment]
CC @RandomShaper 
It might not need to be registered at all?
