### ISSUE TITLE
[GLES3] Crash when initializing 2D texture array with mipmaps and nearest filtering

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#78644]
### Godot version

4.1.beta3 (anything after #77224), master (030c1a950e8cee19e72104b4fb79caba17a2d678)

### System information

GLES3 (compatibility renderer)

### Issue description

After #77224 Godot would crash for me on start with compatibility renderer.

I was getting `Access violation reading location 0x00000000` crash in the GPU driver after:
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/drivers/gles3/storage/texture_storage.cpp#L1319

when it was setting the `1`-level mipmap (`i == 1`) within:
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/drivers/gles3/storage/texture_storage.cpp#L78

After debugging a little the issue seems to be that the filtering is set by default to nearest, and this results in setting max mipmap level to 0. But for textures with mipmaps it shouldn't be done like that I guess. :thinking:
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/drivers/gles3/storage/texture_storage.cpp#L1252-L1253
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/drivers/gles3/storage/texture_storage.h#L260-L264
https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/drivers/gles3/storage/texture_storage.h#L306

Commenting out the `max_lod = 0;` so the max level ends up being the default `1000` fixes the crash for me.

cc @clayjohn Not sure what's the proper fix here. Whether it's just a matter of changing the filtering for mipmapped textures, or not limiting mipmap levels like that for nereast filtered etc. textures, or whatever else. But it should probably be fixed for 4.1.stable (hence the milestone).

### Steps to reproduce

Try to open Godot (project manager).

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
What hardware can you reproduce this crash on?

**Comment by clayjohn** [comment]
Also, can you try out this diff?

```
diff --git a/drivers/gles3/storage/texture_storage.cpp b/drivers/gles3/storage/texture_storage.cpp
index 8a57476a73..305be68706 100644
--- a/drivers/gles3/storage/texture_storage.cpp
+++ b/drivers/gles3/storage/texture_storage.cpp
@@ -1249,10 +1249,6 @@ void TextureStorage::_texture_set_data(RID p_texture, const Ref<Image> &p_image,
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(texture->target, texture->tex_id);
 
-       // set filtering and repeat state to default
-       texture->gl_set_filter(RS::CANVAS_ITEM_TEXTURE_FILTER_NEAREST);
-       texture->gl_set_repeat(RS::CANVAS_ITEM_TEXTURE_REPEAT_ENABLED);
-
 #ifndef WEB_ENABLED
        switch (texture->format) {
 #ifdef GLES_OVER_GL
@@ -1294,6 +1290,15 @@ void TextureStorage::_texture_set_data(RID p_texture, const Ref<Image> &p_image,
 
        int mipmaps = img->has_mipmaps() ? img->get_mipmap_count() + 1 : 1;
 
+       // Set filtering and repeat state to default.
+       if (mipmaps > 1) {
+               texture->gl_set_filter(RS::CANVAS_ITEM_TEXTURE_FILTER_NEAREST_WITH_MIPMAPS);
+       } else {
+               texture->gl_set_filter(RS::CANVAS_ITEM_TEXTURE_FILTER_NEAREST);
+       }
+
+       texture->gl_set_repeat(RS::CANVAS_ITEM_TEXTURE_REPEAT_ENABLED);
+
        int w = img->get_width();
        int h = img->get_height();
```

**Comment by kleonc** [comment]
> What hardware can you reproduce this crash on?

Prehistoric: AMD Radeon 6450, on Windows. I wonder whether it can be failing according to the specification (but other drivers luckily handle it gracefully) or whether that's just a buggy driver (of course no longer supported, last version from 2015). :thinking:

> Also, can you try out this diff?

Works like a charm! :+1: (with everything else as in `master`)
