### ISSUE TITLE
Scene editor doesn't grey out `process_mode = 4` nodes in opened scenes after editor start.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#78648]
### Godot version

4.1???- 4.1.beta1 - 4.1.beta3 - 030c1a950e8cee19e72104b4fb79caba17a2d678

### System information

Tested only Linux versions.

### Issue description

**Regression from 4.0.3.stable:**
In the editor UI set the  `Node->process_mode` to `Disabled` or `When Paused`-> in the scene editor the subtree is grayed out. Save the scene and close the editor. 
It doesn*t need to be the current scene. 
Start it again, the subtree in the scene is no longer gray. The *.tscn file is updated correctly, e.g.:
```
  [node name="Node2D" type="Node2D"]
+process_mode = 4
```
 Workaround is to toggle the process mode again,
 close and open or reload the scene,
(or disable the `interface/scene_tabs/restore_scenes_on_load` option ...)

### Image gallery
![image](https://github.com/godotengine/godot/assets/4047289/b6a90b34-c9ec-4380-b953-f1e64cf72934)
![image](https://github.com/godotengine/godot/assets/4047289/978d4ab1-553b-49e6-bb76-6b18c22a942b)
![image](https://github.com/godotengine/godot/assets/4047289/4254f160-75d5-4186-9802-53b487d8d2f3)

**Comment by bitsawer** [comment]
Possibly related: https://github.com/godotengine/godot/issues/78577?

**Comment by capnm** [comment]
> Possibly related: #78577?

Thanks, indeed the inherited child tag has the same issue:
 
![image](https://github.com/godotengine/godot/assets/4047289/49fb2c76-fbe1-4e42-b071-e47220d84d0d)
after editor restart
![image](https://github.com/godotengine/godot/assets/4047289/fef43d70-2f35-4360-9a80-4eeccb5378da)

**Comment by capnm** [comment]
**4.1.beta1** after editor restart :thinking: 
![image](https://github.com/godotengine/godot/assets/4047289/9ee4b2c2-156b-4b88-a7f2-f31b054c2fa9)

**Comment by capnm** [comment]
Triggered or caused in #72277 .
(e.g. it changes also in [editor/editor_node.cpp](https://github.com/godotengine/godot/pull/72277/files#diff-b88f0bde58b731e8dd353707c8011fb7a1e452f0db2c9f15f4b7905d60e5e52e) the `_load_open_scenes_from_config` implementation).

**Comment by akien-mga** [comment]
CC @Geometror @KoBeWi
