### ISSUE TITLE
Clicking `Override All` in the Theme Editor with no Type selected crashes the editor

### ISSUE THREAD

**Issue by twobitadder** [godotengine/godot#78651]
### Godot version

4.1 beta 3

### System information

Godot v4.1.beta3 - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.2824) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

This is a pretty specific reproduction but one that can accidentally happen (as happened to me). Clicking `Override All` on Theme Editor with no category selected will cause the editor to crash. ~~Opening the project back up shows no Types in the dropdown (despite the theme resource looking fine upon cursory inspection) and attempting to add any new types will crash the editor again. Also important to note that in the first project I had this on the theme was applied as the default theme to my project and it's still visible on elements in the project (fonts and panels and such), but attempting to _edit_ the theme will crash the editor.~~ This is actually because the theme editor is showing my theme but does not have a reference to it somehow. Selecting the theme again fixes this

This shouldn't normally happen under normal operation but it is still something that does, as it requires the `Override All` button to be available but no Type to be selected - as far as I know, the only condition which causes this is if you open up a project after having last edited a Theme. Then the button should be available, but no Type is selected by default.

### Steps to reproduce

- Create a new Theme
- Add some Type, doesn't matter what
- Close project
- Reopen Project, Theme editor should be open
- Click `Override All`
- Enjoy

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
This may be the same as https://github.com/godotengine/godot/issues/78281, which should be fixed in 4.1 RC1. Though the case that you describe in the reproduction steps may still be a problem.

**Comment by twobitadder** [comment]
👀 lookin forward to that RC1 - though I also wanted to correct myself and say that the theme isn't corrupted, I'm just a silly goose who did not realize that the currently edited theme was not actually pointing to anything, and the subsequent crashes were solved by actually selecting the theme. I'll try building from the latest `master` to see what comes up

**Comment by twobitadder** [comment]
Looks like [2930fbeec] will simply not open the Theme Editor by default when reopening a project, which solves that issue. The bottom tray is still expanded but the only way I can tell to be able to edit any theme is to have one selected, so I think we can call this closed!

**Comment by akien-mga** [comment]
Thanks, confirming as duplicate of https://github.com/godotengine/godot/issues/78281.
