### ISSUE TITLE
get_node() not correctly getting grandparent nodes

### ISSUE THREAD

**Issue by othd06** [godotengine/godot#78658]
### Godot version

4.0.3 Stable

### System information

Windows 11

### Issue description

using get_node("...") should return the grandparent node of the node it is being called from however it instead throws an error forcing the user to have to use get_node("..").get_node("..")

### Steps to reproduce

create a node. create a child for this node. create a child for this child node. attach a script to the grandchild node and in one of the prebuilt functions add get_node("...").name . When you try to run the program it will throw an error that it cannot get the property name on null instance.

### Minimal reproduction project

N/A

**Comment by RedMser** [comment]
Try using "../.." instead.

**Comment by othd06** [comment]
> instead.

Thanks, wish that were in the documentation somewhere.

**Comment by timothyqiu** [comment]
See the description of NodePath: https://docs.godotengine.org/en/stable/classes/class_nodepath.html#class-nodepath

`.` and `..` are common notations used in regular file system paths for "current" and "parent" folder.

**Comment by othd06** [comment]
> See the description of NodePath: https://docs.godotengine.org/en/stable/classes/class_nodepath.html#class-nodepath
> 
> `.` and `..` are common notations used in regular file system paths for "current" and "parent" folder.

Which kind of implies '...' should be grandparent folder making it unintuitive that it isn't, especially when the actual notation: "../.." isn't mentioned in the NodePath documentation.

**Comment by AThousandShips** [comment]
> especially when the actual notation: "../.." isn't mentioned in the NodePath documentation.

It follows from the basic logic, it's literally "parent of parent", we could add a line for that but there's limits for how much the documentation should explain every little detail

**Comment by AThousandShips** [comment]
Opened a PR to make the documentation a bit more clear, this should cover all the possible confusion going forward
