### ISSUE TITLE
Giving a custom name to an Autoloaded script will not let you print

### ISSUE THREAD

**Issue by RIH-Cellegen** [godotengine/godot#78650]
### Godot version

4.1 beta (any)

### System information

Linux Mint 21.1 Cinnamon

### Issue description

When you give an Autoloaded Script a custom name (using self.name), the IDE cannot decide what to do and won't print anything.

Replication success: **100%**
Engine: **Any (Compatibity, Mobile or Forward+)**
Tested on: **Godot 4.1 -> All beta versions**
Related to: **Autoload and Script name**
Language: **GDscript**
Issue pushed away by: **Removing the Autoload Script**

Additional info: It might be weird, but the Autoloaded script won't run either, so you cannot just print anything, but the Autoloaded script itself won't work for me. I wouldn't be able to find the root of the issue inside the Godot's source code, so I suggest someone to look into it. I would appreciate it.

### Steps to reproduce

- Have an **Autoloaded Script** ready
- Set the Script's name to any word inside an **_enter_tree()** function, using "self.name" -> for example: **self.name = "example"**
- Have a Scene with any object in it and attach any Script in it, which is not Autoloaded
- Write **print("example")** function inside **_ready(), _process(delta) or _physics_process(delta)** function
- Run the Scene with the attached Script in it
- See the results. You _should_ be able to see "example" once, or every frame, however following these steps, it'll not be the case. It should print nothing at all.

### Minimal reproduction project

[Test Project.zip](https://github.com/godotengine/godot/files/11857730/Test.Project.zip)

**Comment by AThousandShips** [comment]
* Related to/duplicate: #77610

There's issues at the moment with setting the name of things at certain times, see there for details
