### ISSUE TITLE
Directional Shadow Pancake Size breaks Automatic LOD

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#78664]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 Threads)

### Issue description

Pancake Size changes Directional Shadow LOD very aggressively, not representative of the used resolution of the object in shadow map

### Steps to reproduce

Open The Project, and Play around with Pancake Size and observe Human Dummy Shadows going to hell

### Minimal reproduction project

[Pancake.zip](https://github.com/godotengine/godot/files/11859346/Pancake.zip)

**Comment by fire** [comment]
Can you describe or put a video how the pancake size breaks the shadows?

**Comment by mrjustaguy** [comment]
Here's a Video

https://github.com/godotengine/godot/assets/50302479/193de32b-9ab0-4a5f-9290-beebbd09f91b

**Comment by mrjustaguy** [comment]
Tested 4.0 Alpha 1, the issue wasn't present, 4.0 Stable, issue is present, I'm continuing to narrow it down
