### ISSUE TITLE
Editor 4.0.3 closes randomly with no useful log information

### ISSUE THREAD

**Issue by SigmundTannhauser** [godotengine/godot#78679]
### Godot version

4.0.3

### System information

Windows 11 - Godot 4.0.3 - Vulkan Mobile

### Issue description

_Asked originally on https://ask.godotengine.org/155777/editor-4-0-3-closes-randomly-with-no-useful-log-information_

After opening project, editor stays open for a few seconds up to few minutes and then just closes. This started a few days after downloading 4.0.3, which did not behave so initially.

When launched from commandline with --verbose, it does not produce any information on the reason for closing.

1) Log from the commandline (looks weird in some places): https://pastebin.com/uhAB309t

2) Log from the user path:

```
Godot Engine v4.0.3.stable.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.246 - Forward Mobile - Using Vulkan Device #0: AMD - Radeon RX 580 Series

USER ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8388)
USER ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8388)
USER ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8388)
USER ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8388)
USER ERROR: Attempted to free invalid ID: 0
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8388)
USER ERROR: Condition "!shader" is true.
   at: shader_free (servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2453)
USER ERROR: Condition "!material" is true.
   at: material_free 
(servers/rendering/renderer_rd/storage_rd/material_storage.cpp:2686)
```

### Steps to reproduce

- Launch Editor by opening project
- Wait

### Minimal reproduction project

[project_copy.zip](https://github.com/godotengine/godot/files/11860344/project_copy.zip)

**Comment by Calinou** [comment]
Can you try to get a full backtrace by running a [debug build](https://github.com/Calinou/godot-debug-builds) from a terminal? This will tell you where the issue comes from.

**Comment by SigmundTannhauser** [comment]
@Calinou thank you, I ran the debug version and when the editor crashed it produced additional results.

`================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.3.stable.custom_build (5222a99f5d38cd5346254cefed8f65315bca4fcb)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] <couldn't map PC to fn name>
[3] <couldn't map PC to fn name>
[4] <couldn't map PC to fn name>
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
PS D:\GODOT_DEBUG>`

here's the complete console output for reference: https://pastebin.com/smDfwBW8

**Comment by clayjohn** [comment]
Is there any chance you updated your GPU driver in the time between downloading Godot 4.0.3 and when the issue started? Or did a Windows update?

**Comment by SigmundTannhauser** [comment]
- There were two Windows updates since I started on Godot 4.0.3:

![image](https://github.com/godotengine/godot/assets/2188047/5b5583cd-3ba8-4b7c-b1c8-15acce081295)
 
- Graphics driver version is driven by AMD Catalyst, and was updated via AMD Catalyst about a week before starting with Godot 4.0.3 as much as I can recall, here's the details:

![image](https://github.com/godotengine/godot/assets/2188047/6e65fe55-3528-4fef-bf7d-43da717e2d73)

**Comment by YuriSizov** [comment]
Did you happen to test newer version of Godot, 4.1.3 or 4.2 betas, since this was reported? Is the issue still present?
