### ISSUE TITLE
Xbox "Start" button name does not match the official one

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#78674]
### Godot version

v3.6.beta2.official [68c507f59]

### System information

w10 64

### Issue description

This image is from the official documentation.

![Captura](https://github.com/godotengine/godot/assets/19652075/dfcd9cb2-fec4-468b-99bf-bee786259bba)

Where is the "Menu" button?
What is the "Menu" button supposed to be?

![Captura4](https://github.com/godotengine/godot/assets/19652075/2d6a9fbb-78fc-421c-894e-e619522576c4)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Calinou** [comment]
The Menu button is the Start button. In practice, I rarely ever see anyone calling it a menu button on Xbox controllers.

**Comment by AThousandShips** [comment]
There's only so many variations on names that we can include, and note that on the 360 the button was officially called "Start"

**Comment by Calinou** [comment]
PS: Can you link to the page that you took a screenshot of (the one with a description of the Xbox controller buttons)?

**Comment by Torguen** [comment]
https://support.xbox.com/en-US/help/hardware-network/controller/get-to-know-your-xbox-series-x-s-controller

Well, my case was that I don't have an XBOX controller but I wanted to refer to that button, so I had to find out the name of the button (menu) and then I searched in the godot button list and the button didn't appear there and I didn't know what button should select.
