### ISSUE TITLE
Documentation issue with mutex

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#78686]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Linux/BSD

### Issue description

Documentation issue: it says that mutexes will return false if the thread already has ownership of the mutex 
![image](https://github.com/godotengine/godot/assets/69520693/7721fe79-e354-4035-9782-d2efaffe5e15)

### Steps to reproduce

```gdscript
func _ready():
	var mtx:=Mutex.new()
	mtx.lock()
	var v = mtx.try_lock()
	if v:
		print("knew docs were wrong <",v,">")
		mtx.unlock()
	else:
		print('the hell')
	mtx.unlock()
```

### Minimal reproduction project

N/A

**Comment by RadiantUwU** [comment]
The code above prints
![image](https://github.com/godotengine/godot/assets/69520693/082302a5-d392-4b82-8816-2a99648a4acf)

**Comment by AThousandShips** [comment]
This isn't how it works though, the current thread has ownership, so locking should return true, only if some other thread owns it should it return false, the `Note` is confusing though as it says to return an error rather than a bool

This doesn't look like an error at all

**Comment by AThousandShips** [comment]
Since the documentation is out of date and claims to return an error instead of a bool (this used to be the case) I will update it tomorrow, but there's no other error here
