### ISSUE TITLE
Multiplayer Spawner throws error on client

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#78687]
### Godot version

4.1.beta2

### System information

Windows 10, Intel icore7, NVIDIA 730, 16Gb RAM

### Issue description

When a server spawns something synchronized by the node MultiplayerSpawner, if the connected client does not have that MutliplayerSpawner in its scene, it throws an error on the client.
The server spawns an object on the scene_1, and the client, as it does not have the scene_1 in its tree, it throws an error.
The MultiplayerSpawner's spawn path is "scene_1"

ERRORS:
![image](https://github.com/godotengine/godot/assets/4398470/3df414bd-4143-422e-bed9-30eba71d633b)

Server scene tree:
root:
-- scene_root
---- scene_1
------ MutliplayerSpawner
---- scene_2
   
Client scene tree:
root:
-- scene_root
---- scene_2

I am approaching this through a "scene_root" scene, created by myself so that the server can have multiple scenes at the same time. Am I doing this wrong? Should I have a server for each scene that I want the clients to take part in? Or could it be done this way which is way simpler?

As I see this, there are two ways of fixing this, taking into account this behaviour might not be a bug.
Option 1:
   To not use MultiplayerSpawner nodes and use RPC function calls instead
Option 2:
   To open a server for each individual scene the client can get into (scenes that actually need interaction with the server) I find this to be too much time consuming, so I would go for the option 1.

Thanks in advance for all the answers and possible fixes to this issue.

### Steps to reproduce

Run the game with 2 debug scenes, create an object pressing the button on the server and see the error.

### Minimal reproduction project

[MinimalProject.zip](https://github.com/godotengine/godot/files/11860960/MinimalProject.zip)

**Comment by akien-mga** [comment]
For clarity, this was closed as duplicate of #78692.
