### ISSUE TITLE
CSGPolygon3D not respecting Curve3D tilt when path_rotation is set to 'PathFollow'

### ISSUE THREAD

**Issue by nickpolet** [godotengine/godot#78683]
### Godot version

4.1.beta [3710f06]

### System information

Ubuntu 22.04

### Issue description

When using CSGPolygon3D in 'Path' mode, setting the path_rotation doesn't seem to follow the Path3D's tilt on points. Expecting to see the extruded mesh twist to match up with the Path3D's tilt. I've tried changing all settings related to this, but can't seem to get anywhere.

![image](https://github.com/godotengine/godot/assets/5023909/7a5b1c15-e20a-42f4-a206-f295f853ab1a)
*Path3d with a twist in it, set with the tilt var on the points* 

![image](https://github.com/godotengine/godot/assets/5023909/4272c9eb-9c76-4a7e-b27d-439bf6bfba36)
*CSGPolygon3D shape, attached to the path with PathFollow set as the path_rotation*

![image](https://github.com/godotengine/godot/assets/5023909/cd136ba1-686c-489f-aad9-86bfe86702e2)
*Expected result, mocked up in blender*

### Steps to reproduce

I've created a simple minimal reproduction project, which shows a simple CSGPolygon3D attached to a path that has a twist in it. The path mode is set to `Path`.

This issue is also easy to create without the reproduction file. Just create a path, add some points, add some tilt, create a CSGPolygon3D, set it to Path mode, and assign the path to it. Changing the tilt doesn't affect the mesh in any way.

This happens on all versions of Godot 4 I've tried. I've tried a custom build, and version 4.1.beta3, with no luck. Unsure if this worked previously on v3.

### Minimal reproduction project

[godot-csgpolygon3d-pathfollow.zip](https://github.com/godotengine/godot/files/11860659/godot-csgpolygon3d-pathfollow.zip)

**Comment by fire** [comment]
As far as I know this enhancement wasn't part of the design for path follow, but I agree it makes sense it should work.

**Comment by nickpolet** [comment]
Closing this issue out as there's a another discussion on this that has a potential fix --> [65634](https://github.com/godotengine/godot/issues/65634)
