### ISSUE TITLE
"Close Other Tabs" Crashes Editor (4.1 Beta 3)

### ISSUE THREAD

**Issue by QueenOfSquiggles** [godotengine/godot#78682]
### Godot version

4.1.beta3.mono.official [ada712e06]

### System information

Manjaro (KDE) Vulkan Forward+

### Issue description

Using the "Close Other Tabs" option when multiple tabs are open causes editor to hitch and then crash.

### Steps to reproduce

Have multiple tabs open in editor
Right click on one tab
Click "Close Other Tabs"

### Minimal reproduction project

This only seems to occur in my project: [cute-farm-sim](https://github.com/QueenOfSquiggles/cute-farm-sim).

**Comment by KoBeWi** [comment]
Can't reproduce. I opened some random scenes in your project and Closed Other Tabs and there is no crash.

**Comment by QueenOfSquiggles** [comment]
I might just be more confused. I can't get it to crash anymore. I didn't change anything besides making more scenes and scripts and such that didn't affect much? I'm closing this until something more clearly engine related crops up. Sorry for wasting anyone's time
