### ISSUE TITLE
LIGHT color built-in appears to be multiplied by PI

### ISSUE THREAD

**Issue by dnsiltei** [godotengine/godot#78693]
### Godot version

4.0.3 stable

### System information

Ubuntu 22.04.2

### Issue description

The LIGHT_COLOR built-in  in a custom light function appears to be times PI higher then color*energy  

### Steps to reproduce

use this shader in a material
`shader_type spatial;
render_mode ambient_light_disabled;

void fragment() {ALBEDO=vec3(0.0,0.2,0.0);}
void light(){
	DIFFUSE_LIGHT=LIGHT_COLOR;
}`

### Minimal reproduction project

[light_color_test.zip](https://github.com/godotengine/godot/files/11862964/light_color_test.zip)

**Comment by clayjohn** [comment]
That is correct. Each color "unit" in the default configuration of lights/ material is PI. This is done in most PBR renderers to maintain compatibility between physically-based materials and non physically-based materials (because physically-based models of light include a division by PI)

**Comment by dnsiltei** [comment]
thanks for the info, its not in the docs

**Comment by clayjohn** [comment]
Re-opening. As I think the docs can be improved to mention this

**Comment by Calinou** [comment]
Out of curiosity, is this also done in 3.x GLES3 (and GLES2)?

**Comment by clayjohn** [comment]
> Out of curiosity, is this also done in 3.x GLES3 (and GLES2)?

Yep! It has been in place for as long as we have had a PBR pipeline
