### ISSUE TITLE
CharacterBody3D get_position_delta() includes global transform offset

### ISSUE THREAD

**Issue by skyfloogle** [godotengine/godot#78690]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10

### Issue description

If a `CharacterBody3D`'s parent node is in a position other than the origin, the difference will be included in its `get_position_delta()` value, and therefore also `get_real_velocity()`. This is because [the implementation](https://github.com/godotengine/godot/blob/3710f069293f2fde8afe33fea898c4b36fa5e943/scene/3d/physics_body_3d.cpp#L1782-L1784) subtracts the current **local** transform from the old **global** transform. I don't know if behaviour in this case is defined at all, but I would expect it to be consistent with everything else in the `CharacterBody3D` context, such that if `velocity` is zero, `get_position_delta()` is also zero. The same applies to `CharacterBody2D`.

### Steps to reproduce

1. Create a `Node3D` with a `CharacterBody3D` in it
2. Move the `Node3D`
3. Call `move_and_slide()` in the `CharacterBody3D` and observe `get_position_delta()`

### Minimal reproduction project

[godot cb3d.zip](https://github.com/godotengine/godot/files/11861307/godot.cb3d.zip)

**Comment by rburing** [comment]
Thanks for reporting! I've linked a PR fixing this (above).

The same does not apply to CharacterBody2D:

https://github.com/godotengine/godot/blob/1f9e540f14edbf2d496a1421f8d37e5b483c4c53/scene/2d/physics_body_2d.cpp#L1530-L1532

**Comment by skyfloogle** [comment]
> The same does not apply to CharacterBody2D:

Oops, I probably misread the code (it was 1AM after all). I hadn't actually tested 2D; I have now and can confirm it's 3D only.
Thanks for the PR!
