### ISSUE TITLE
What is an unsafe cast? (using the Unsafe Cast optional warning flag)

### ISSUE THREAD

**Issue by Darenn** [godotengine/godot#78697]
### Godot version

3.5.2.stable

### System information

Linux (manjaro OS with XFCE)

### Issue description

Find below an example triggering the _"The value is cast to 'Cell' but has an unknown type"_. I don't understand that warning and would like to know what it means.

Here is a method returning a custom class **Cell** (it does not make sense, just modified it for the example):
![image](https://github.com/godotengine/godot/assets/11272715/81dcdafe-f1da-4127-9fa5-64fbb02c447a)

Here are three different commented variable declarations (_board is a custom Class):
![image](https://github.com/godotengine/godot/assets/11272715/f6ec7430-b786-4e07-b392-b64105026b2e)

I think it's strange that it throws the warning on c1 and c2. Especially for c2 since it looks like the most verbose and safe way to declare the variable.

Thank you!

### Steps to reproduce

1. Activate the Unsafe Cast flag in GDscript.
2. Declare a variable in one of the three ways described below (does not have to be a custom type)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

I'm suspecting that `_board` is not statically typed as what ever custom class it is, meaning the method on it doesn't have any information

**Comment by Darenn** [comment]
Thanks for the quick reply! And sorry for posting in the wrong place! (I actually already posted questions on the discord and forum before but never got any replies unfortunately, I will be sure to insist next time!).

Thank you that was it! So If I understand well, since _board was not typed, the cast was unsafe because you don't know what type is returned by get_cell before execution.

I am not sure to understand why c3 does not trigger the warning then? It's still trying to cast from something unknown right?

**Comment by Darenn** [comment]
Sorry I'm actually gonna close the issue since it's not the good place for it. Thanks again for your help @AThousandShips!

**Comment by AThousandShips** [comment]
> since _board was not typed, the cast was unsafe because you don't know what type is returned by get_cell before execution

Exactly!

> I am not sure to understand why c3 does not trigger the warning then? It's still trying to cast from something unknown right?

I'm not familiar with the internals of 3.x unfortunately, but I suspect the warning is only there for explicit cases
