### ISSUE TITLE
Não Consigo Exportar Apk Na Godot 4 Mobile

### ISSUE THREAD

**Issue by Faelldev** [godotengine/godot#78695]
### Godot version

4.0

### System information

Android 11 - Godot 4.0 mobile

### Issue description

Quando vou exportar um apk na godot mobile, não aparece o botão de exportar

### Steps to reproduce

Só entrar no exportar

### Minimal reproduction project

Não aparece o botão de exportar

**Comment by Zireael07** [comment]
1) Please use English (even via Google Translate) in this bug tracker
2) Are you using Godot mobile editor or are you trying to export from desktop to Android?

If you're using Godot mobile editor, then exporting is not possible in the mobile version AFAIK

**Comment by YuriSizov** [comment]
Indeed, you currently cannot export an APK via the Android version of the editor.
