### ISSUE TITLE
TileMap node causes crash [Version 4.1Beta3]

### ISSUE THREAD

**Issue by ElementerTheDragon** [godotengine/godot#78708]
### Godot version

v4.1-beta3_win64

### System information

v4.1-beta3_win64

### Issue description

When using a Tilemap node, I have added 2 images, when manipulating the "terrain set" (only this), it has produced an error and has crashed GODOT (deleting everything NOT saved).
Previously I had passed my project from version 4.0.2-stable_win64 > v4.1-beta3_win64.
Now every time I go into the tilemap node and want to edit the terrain this happens:
Click tilemap node, put "tilemap">"terrain" and crash directly.

### Steps to reproduce

1- Create project in Version 4.0.2, then create Tilemap node (NO scripts at any time)
2- Add image 1 and edit the "terrain set" with the "tileset" brush.
3- add land to the project.
4- Update the project to version 4.1-beta3_Win_64.
5- Add the 2nd image to the same tilemap and edit the "terrain set".
6- Now it should crash.
The next time you log in, if you click the tile node and then click "tilemap" > "terrain" it should crash, deleting everything NOT saved.

### Minimal reproduction project

Select the tile node, and push tilemap > "terrain"

**Comment by akien-mga** [comment]
Could you provide a minimal reproduction project that matches step 3 outlined above? I.e. the project fully made and functional in 4.0.2, ready to be loaded into 4.1-beta3 to trigger the crash.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the MRP asked for this can be reopened
