### ISSUE TITLE
Apply vertex displacement to GeometryInstance

### ISSUE THREAD

**Issue by DxUr** [godotengine/godot#78704]
### Godot version

4.0.3

### System information

N/A

### Issue description

I cant apply a vertex displacement to a GeometryInstance (MeshInstance) without affecting the materials (override the entire material) , and it's imposible to use a custom shader to each surface for each GeometryInstance  in my project, if there is just a little idea of how I can solve this just tell me , I'm using C++ in my project so I dont have any issues with compiling custom  engine build.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

See also https://github.com/godotengine/godot-proposals/issues/1779.
