### ISSUE TITLE
why does rigidBody2d has a addForce function

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#7870]
**Why is there a addForce Function directly in rigidBody2d AND in Physics2DDirectBodyState**

`add_force ( Vector2 offset, Vector2 force )`
I'm wondering, because there is also a apply_impulse function and it makes much more sense to have apply_impulse since force has to be applied over a period of time to have an effect but since the physic is running in a different thread it is really hard to apply the force for the right periods of time especially if it's just a short interaction.

In addition there is also the `Physics2DDirectBodyState` which also allows for a add_force function. which makes a lot of sense. but both Is confusing. since force would be applied over a longer period of time anyways (I don't know how it would make sense otherwise especially considering the existence of apply_impulse) I think it would make the most sense to only give access to that function int the `_integraetd_forces` function.

Maybe that is not even an Issue since it has a reason but I would like to know the reason for it. and if someone tells me I also would be willing to document it :)

**To bring my question to a point**
It makes sense, that there is `apply_impulse` + `add_force` but why is there `add_force` in ** rigidBody2d** the `add_force` in **Physics2DDirectBodyState** makes sense though.

**Comment by Zylann** [comment]
I believe impulse and force have different meanings. Impulses are ponctual forces, like those coming from hits or explosions. Forces are usually applied over time as accelerations, like gravity, and can change during movement. Simply put, one acts as a setter, the other as an adder (but mass is also taken into account).

For an outside reference, Unity has the same kind of stuff: https://docs.unity3d.com/ScriptReference/ForceMode.html

**Comment by toger5** [comment]
Yea that is basically the same understanding I have. but why is there a add add_force in the rigid body 2d itself. I though the reason of the Physics2DDirectBodyState would be to apply those kind of over time forces. Is it just for simpler access? And basically a redundant function?

**Comment by hubbyist** [comment]
Impulse is accumulation of force over time which is change in momentum of object. You can stop an object in two ways, by applying a big force in a short time or applying a small force for a long time. As long as accumulated impulse is sufficient to bring momentum down to zero. 

So if you are able to set impulse directly you can set new momentum of object instantly. Like making a vector sum of two impulses. May be this can be used to shortcut some unending calculations.

**Comment by hubbyist** [comment]
I found a `CC` article about the subject as well. http://spiff.rit.edu/classes/phys311.old/lectures/impulse/impulse.html

**Comment by eon-s** [comment]
On the docs says that impulses are also affected by shape and mass, and if you don't want to use a custom integrator, the Physics2DDirectBodyState is not accessible from fixed process in a direct way from the body.

**Comment by toger5** [comment]
Why do you than only have access to apply impulse in the 3d rigid body and have to use the physicadirectbodystate for force?
It doesnt feel consistent

**Comment by Calinou** [comment]
Both RigidBody and RigidBody2D now expose `apply_impulse()` *and* `add_force()`, closing.
