### ISSUE TITLE
html5 mouse scrolling is inverted for control nodes with scroll bars. 

### ISSUE THREAD

**Issue by afftor** [godotengine/godot#7871]
**Operating system or device - Godot version:**
Html5 browsers

**Issue description:**
Mouse scroll for control nodes is inverted

**Steps to reproduce:**
Make RichTextLabel, fill with text, try scroll in html5 compiled version

**Comment by eska014** [comment]
Scrolling on Chromium is inverted due to Emscripten's GLUT implementation. We should use another API or fix it upstream (or hack it).
