### ISSUE TITLE
4.1 Crash when using SoftBody on mobile

### ISSUE THREAD

**Issue by dqdthanhthanh** [godotengine/godot#78715]
### Godot version

4.1 beta 3, 4.1 beta 1

### System information

Windows 10 - 4.1 beta 3 - Android 12

### Issue description

Crash when using SoftBody on android mobile.

### Steps to reproduce

- Simple scene setup using a plane softbody, camera.
- Export to android mobile.
- Immediate crash when open the app.

### Minimal reproduction project

[SoftbodyMobileTest.zip](https://github.com/godotengine/godot/files/11871734/SoftbodyMobileTest.zip)

**Comment by AThousandShips** [comment]
Can you confirm this crash doesn't happen when running on some other platform after export?

**Comment by Alex2782** [comment]
`USER WARNING: res://node_3d.tscn:3 - ext_resource, invalid UID: uid://rom6mlb4qicd - using text path instead: res://soft_body_3d.tscn`

Android Studio Logcat. My master branch, updated a few days ago. Also crashes with Godot 4.1.3.
![Bildschirmfoto 2023-11-04 um 00 53 11](https://github.com/godotengine/godot/assets/41921395/c08817d6-5971-415b-9097-1243d44ba08b)

https://github.com/godotengine/godot/blob/master/scene/resources/resource_format_text.cpp#L451
https://github.com/godotengine/godot/blob/master/core/templates/local_vector.h#L161

Can anyone do anything with it yet?

**Comment by Calinou** [comment]
This may be related to https://github.com/godotengine/godot/issues/80371.

**Comment by Alex2782** [comment]
Debug Android Studio

`print_line("p_indices:", p_indices);` many values are much too high, I compare it later with MacOS

![Bildschirmfoto 2023-11-04 um 14 56 25](https://github.com/godotengine/godot/assets/41921395/635180c5-c71a-4cde-ae18-a5a92e969614)

**Comment by Alex2782** [comment]
The problem could be identical to: #80371

I think already `RS::SurfaceData MeshStorage::mesh_get_surface` returns the data incorrectly on Android.

Executing `mesh_surface_get_arrays` in a loop changes the `SurfaceData` structure on Android. On the Mac, the structure remains the same.

![image](https://github.com/godotengine/godot/assets/41921395/e49b4d9d-390d-4976-b339-5946da82f7fa)


In this example, `index_data` was first overwritten with `attrib_data` under Android. 
Then (2nd pass in the loop) `attrib_data` and `index_data `were overwritten with `vertex_data`. 

https://github.com/godotengine/godot/assets/41921395/8c8baa39-1c5e-4513-9cc0-c72ae0e97861

**Comment by Alex2782** [comment]
maybe also #75599

**Comment by dqdthanhthanh** [comment]
Runs normally on iPhone 11. Still crashes on Android. Using godot 4.1.3

**Comment by Alex2782** [comment]
Today I tried with some 'breakpoints' and memory monitoring. Only 1 breakpoint in this function is enough and the app does not crash anymore and `index_buffer` is not overwritten.

https://github.com/godotengine/godot/blob/e5bacbc4716ce5b54bc2ab8b3053cd5e22ffe446/drivers/vulkan/rendering_device_vulkan.cpp#L6059

`_THREAD_SAFE_METHOD_` but not on Android?

**Comment by Alex2782** [comment]
I may have a solution, first I'll check other problems to see if they are also fixed.
https://github.com/godotengine/godot/commit/6a0fc73dc6f420f8253680ad4383c09a491c94c1

[google-hellovk](https://github.com/android/ndk-samples/blob/87bf557531f3d3d50fbba6d64ac4a601a865788a/hello-vulkan/app/src/main/cpp/hellovk.h#L363) -> if flag `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` is passed, then there are no more problems with the buffers. In the VMA-Lib [VMA_MEMORY_USAGE_CPU_ONLY](https://github.com/godotengine/godot/blob/64150060f89677eaf11229813ae6c5cf8a873802/thirdparty/vulkan/vk_mem_alloc.h#L3671C36-L3671C36)


https://github.com/godotengine/godot/assets/41921395/2205d045-2683-44f5-810c-bb7ac00053e1
