### ISSUE TITLE
Fullscreen is treated as an Exclusive Fullscreen on Windows

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#78723]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Godot v4.1.beta3 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Related: #77378 (Might be caused by this).

When a project is launched with `display/window/size/mode` set to `Fullscreen` the main window will instead open in `Exclusive Fullscreen`. Moving the window in place seems to fix this, but I'm hesitant to call that a proper solution:

I.e. add `MoveWindow(...)` after creating the window here (or during it):
https://github.com/godotengine/godot/blob/9d089fe6e501e4818fed1b0688631c4d65d1ba35/platform/windows/display_server_windows.cpp#L4311
It might be enough to send one of the messages that `MoveWindow` does https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-movewindow#remarks but I haven't tested.

### Steps to reproduce

Open a project on Windows with `display/window/size/mode` set to `Fullscreen`.

### Minimal reproduction project

N/A

**Comment by Lielay9** [comment]
> @Lielay9 The expected outcome for this should be to have a borderless fullscreen for Fullscreen mode and complete ownership of display for exclusive fullscreen mode right?

In practice, yes. You can find the details of how that is implemented here, where the window is created...: https://github.com/godotengine/godot/blob/1f9e540f14edbf2d496a1421f8d37e5b483c4c53/platform/windows/display_server_windows.cpp#L3884
... and here where the mode is changed: https://github.com/godotengine/godot/blob/1f9e540f14edbf2d496a1421f8d37e5b483c4c53/platform/windows/display_server_windows.cpp#L1374

**Comment by Yadnesh-Kulkarni** [comment]
Okay. I am halfway through debugging this. I will revert once I have any update.

**Comment by KoBeWi** [comment]
Sounds related to #60665

**Comment by Yadnesh-Kulkarni** [comment]
Looks fairly similar or may even be a duplicate. Once I can debug through play window, I can be sure. Will update here as soon as I have a lead.

**Comment by Yadnesh-Kulkarni** [comment]
Should Fullscreen mode have a Titlebar while displaying? If not then turning on Borderless Window property in property manager seems to have solved this. Though, I think turning on borderless window by default while turning on the Fullscreen mode should be the right solution for this.
