### ISSUE TITLE
Most code editor themes in Godot 4+ make the text unreadable

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78724]
### Godot version

4.0.3, 4.1.beta.3

### System information

Windows 11

### Issue description

Most of the **Editor Themes** provided by default in the release post 4.0+ is kind of not usable. This is also a bug if it is compared with 3.5.2, which I expected to have similar colors. 

Example for `One-Monokai`

**4.1.beta.3 (and 4.0.3 also):**

![image](https://github.com/godotengine/godot/assets/84369217/dbf2d08a-38b4-48c3-b7c5-6582e606709b)

Compared to:
**3.5.2:**
![image](https://github.com/godotengine/godot/assets/84369217/a7c0d4ce-922d-4d28-b3a3-984e00c6ebda)

One of the most difficult ones `Solarized-Dark`:

![image](https://github.com/godotengine/godot/assets/84369217/612b9691-673a-45ce-8293-06493d814602)

_Notice: You cannot read the keywords itself_

Apart from that, there is an additional bug IMO: There are two themes named "dracula" and darcula". I believe it is a spelling error.

### Steps to reproduce

Open the Editor Settings:
Goto **Editor -> Theme**
Change one of the values as mentioned in Color Theme.

Workaround: Only stick with default theme

### Minimal reproduction project

N.A

**Comment by YuriSizov** [comment]
Thanks for your report!

> Apart from that, there is an additional bug IMO: There are two themes named "dracula" and darcula". I believe it is a spelling error.

These are two different color schemes, it's not a typo.

> Open the Editor Settings:
Goto Editor -> Theme
Change one of the values as mentioned in Color Theme.

To be clear, you are reporting an issue with the code editor color schemes, not with the editor theme. So the correct instruction would be to go to **Text Editor -> Theme**.

**Comment by YuriSizov** [comment]
To avoid confusion you should probably delete your old themes. You can find them in your editor data directory (**Editor > Open Editor Data / Settings Folder**, `text_editor_themes`).

I'm going to close this issue, as this is not an engine bug.

**Comment by YuriSizov** [comment]
Actually, I completely forgot that we have this repo: https://github.com/godotengine/godot-syntax-themes/, and this is where you have probably gotten those themes from.

There is a 4.0 compatible branch in there that you can use, but we should probably update that repository to make the master version compatible instead. But you can get these, they should likely work:
https://github.com/godotengine/godot-syntax-themes/tree/4.0-dev

**Comment by Calinou** [comment]
> There is a 4.0 compatible branch in there that you can use, but we should probably update that repository to make the master version compatible instead. But you can get these, they should likely work:
[godotengine/godot-syntax-themes@4.0-dev](https://github.com/godotengine/godot-syntax-themes/tree/4.0-dev?rgh-link-date=2023-06-26T21%3A41%3A57Z)

I've moved the `4.0-dev` branch to `master`, and the old `master` branch to `3.x`.

**Comment by YuriSizov** [comment]
> It seems I cannot use Godot 3 and Godot 4 simultaneously for custom themes as both are using the same directory for themes.

You can put one of them into the [self-contained mode](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode). Then all of the editor service files will be placed next to the editor executable itself, instead of a global location.
