### ISSUE TITLE
Spatial editor front view wrong direction

### ISSUE THREAD

**Issue by yikescloud** [godotengine/godot#78733]
### Godot version

3.5stable

### System information

windows 10

### Issue description

Front view and rear view in spatial editor is wrong.
![image](https://github.com/godotengine/godot/assets/9168814/ac6f621d-b3e1-4fb1-89cf-92c6a8a79b26)

### Steps to reproduce

Press kp1 in spatial editor

### Minimal reproduction project

Only need a editor to reproduce.

**Comment by AThousandShips** [comment]
* See: #76052
