### ISSUE TITLE
Scene Panel: node names are overlapping icons

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#78741]
### Godot version

4.1 Beta 3

### System information

Win10

### Issue description

In the Godot 4.1. Beta3 Scene Panel, node names are overlapping the icons to the right. Like visibility icons, script icons ...
Especially apparent with longer node names:

https://github.com/godotengine/godot/assets/47016402/61cc8c75-efe5-4cfa-ac4f-5fcd4805140b

This is _not_ an issue in Godot 4.0.3:

https://github.com/godotengine/godot/assets/47016402/4035ea3f-80bd-479d-9d6f-761debdd6b49

### Steps to reproduce

Give long node names and resize the Scene Panel

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
See https://github.com/godotengine/godot/issues/77853#issuecomment-1605582247. It's my fault. I'll take a look, but it probably won't be included in 4.1 because when fixing regressions, it's important not to create an even bigger regression.
