### ISSUE TITLE
Disabled Sliders shouldn't be highlightable

### ISSUE THREAD

**Issue by nyxkn** [godotengine/godot#78748]
### Godot version

v4.1.rc.custom_build [1b3bf4852]

### System information

Godot v4.1.rc (1b3bf4852) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:19 +0000 - Vulkan (Compatibility) - AMD Radeon R9 380 Series (tonga, LLVM 15.0.7, DRM 3.52, 6.3.7-zen1-1-zen) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Sliders that are set to *not* editable will still be highlighted on hover, even if you cannot interact with them.

This seems counterintuitive (I'd expect to be able to interact with something that lights up on hover), and inconsistent (disabled buttons do not get highlighted on hover).

Screencap of hover behaviour:

https://github.com/godotengine/godot/assets/1187609/af9466ad-37d5-4d13-ace5-b6268166e2b6

In Godot 3, uneditable sliders behaved as you would expect and did not get highlighted on hover, same as buttons.

### Steps to reproduce

Add HSlider or VSlider, hover over with mouse.

### Minimal reproduction project

None.

**Comment by NiskashY** [comment]
Hello! I saw that if you do not touch the sliders - they are highlighted when you hover over them and then go back. But if you drag one of them - the highlighting remains after removing the mouse from it. Is this also supposed to be fixed?

**Comment by Calinou** [comment]
> Hello! I saw that if you do not touch the sliders - they are highlighted when you hover over them and then go back. But if you drag one of them - the highlighting remains after removing the mouse from it. Is this also supposed to be fixed?

This is the focus highlight, which is separate from hovering. Right now, it looks identical to the hover highlight, which is something we could tweak in a separate PR.
