### ISSUE TITLE
DDS textures appear solid black in TileSet, preview in editor works

### ISSUE THREAD

**Issue by Numbers11** [godotengine/godot#78755]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10

### Issue description

Worked in Godot 3, when I try to use a DDS file in a Tileset, the preview in the tileset editor shows the texture correctly, but in the game preview window or the game itself the texture is just solid black

### Steps to reproduce

1. Import a DDS file to your project
2. Add it to a tileset
3. Put it on a tilemap, see solid black

### Minimal reproduction project

Just try with a few of these DDS (they are from the CnC remake, hope there will be no copyright issue)
[D02.zip](https://github.com/godotengine/godot/files/11884490/D02.zip)

**Comment by clayjohn** [comment]
I can reproduce this issue both in 4.03 and 4.1 (master build from yesterday). 

The textures work fine everywhere except for in tilemaps. I tested them in a StandardMaterial3D and in a Sprite. 

When adding the texture as a texture to an Tile Atlas, the engine prints the following errors:
```
UndoRedo history mismatch: expected 0, got 3.
  Cannot blit_rect in compressed or custom image formats.
  Cannot blit_rect in compressed or custom image formats.
  Cannot blit_rect in compressed or custom image formats.
  Cannot blit_rect in compressed or custom image formats.
  Cannot blit_rect in compressed or custom image formats.
  Can't get_pixel() on compressed image, sorry.
  Can't set_pixel() on compressed image, sorry.
  Can't get_pixel() on compressed image, sorry.
  Can't set_pixel() on compressed image, sorry.
  Can't get_pixel() on compressed image, sorry.
  Can't set_pixel() on compressed image, sorry.
  Can't get_pixel() on compressed image, sorry.
  Can't set_pixel() on compressed image, sorry.
```

Accordingly, it looks like the tilemap editor makes the assumption that all textures are uncompressed. The way to properly handle compressed textures is to either decompress, edit, and recompress them. Or to provide a warning to the user, decompress them, and then leave them decompressed.

**Comment by akien-mga** [comment]
Related to #78743 ?

**Comment by clayjohn** [comment]
> Related to #78743 ?

They seem to have the same root cause. I.e. we are modifying the texture directly. But likely will have different solutions. Here we just need to decompress before doing our operations, but in #78743, we will likely need to do more work to preserve mipmaps
