### ISSUE TITLE
Instancing a couple CharacterBody3Ds will tank performance when using Godot Physics

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#78761]
### Godot version

4.0.3 stable, 4.1 Beta3, 4.1 RC1

### System information

Win 10

### Issue description

Unlike in Godot 3.5.X using KinematicBody, instancing and adding CharacterBody3D in Godot 4.0.3 stable and 4.1 versions (tested up to RC1) will quickly tank performance after just a few new instances  (10 - 40) have been added to the scene. The faster you spawn them, the faster the performance tanks. 

I have also noticed if I disable the collision mask bit of the CharacterBody3D, the performance issue is gone. It seems like there needs to be collision of some kind. 
Also when removing the walls and avoiding the to shoot the floor, instead just shooting into infinity the issue won't reproduce. However as soon as you start to shoot at the floor repeatedly, the performance tanks again. 

All those instances do is move forward until there is a collision:

```
extends CharacterBody3D

func _physics_process(delta):
	var collision = move_and_collide(velocity)
	if collision:
		velocity = Vector3.ZERO
```

spawn code:

```
func _physics_process(delta):
	if Input.is_action_just_pressed("shoot"):
		var new_bullet = bullet.instantiate()
		add_child(new_bullet)
		new_bullet.global_position = gun.global_position
		new_bullet.global_transform.basis = gun.global_transform.basis 
		new_bullet.velocity = -new_bullet.global_transform.basis.z * 0.5
```

In Godot 3.5.2 using the Default or Bullet physics engine I can spawn hundreds of those instances (250 - 300) before I notice any performance degradation. The difference feels massive, similarly to what is reported in https://github.com/godotengine/godot/issues/48978

In Godot 3.5.2 using GodotPhysics, the issue seems pretty much identical as in Godot 4.0.3 and Godot 4.1 versions, further indicating how the cause for this seems to be GodotPhysics.

Switching to [Godot Jolt](https://godotengine.org/asset-library/asset/1918) in Godot 4.0.3 allows me to spawn ~800 of these CharacterBody3D bullets before I notice any performance degragation.

### Steps to reproduce

Run the MRP below by shooting CharacterBody3D/KinematicBody bullets against a wall using left mouse button.

https://github.com/godotengine/godot/assets/47016402/062b361b-12e7-4aaf-a60e-fd8351ee128d

### Minimal reproduction project

MRP for Godot 4.1 RC1 (Godot Physics):
[instancing_performance_test_G41.zip](https://github.com/godotengine/godot/files/11885154/instancing_performance_test_G41.zip)

MRP for Godot 4.0.3 stable (Godot Physics):
[instancing_performance_test_G403.zip](https://github.com/godotengine/godot/files/11885167/instancing_performance_test_G403.zip)

MRP for Godot 3.5.2 stable (Default ... which is Bullet, I assume? Even though Bullet is a separate option?):
[Instancing Performance Test G3.5.zip](https://github.com/godotengine/godot/files/11885158/Instancing.Performance.Test.G3.5.zip)

MRP for Godot 4.0.3 stable (with Jolt):
[instancing_performance_test_G403_jolt.zip](https://github.com/godotengine/godot/files/11886870/instancing_performance_test_G403_jolt.zip)

**Comment by capnm** [comment]
The `Godot physics engine` does not like the convex collision shape of your projectile. Replace it with a simple BoxShape :)

**Comment by golddotasksquestions** [comment]
Well this is just a MRP example. There are other instances which will need simplified convex collision shapes which are not boxes. Only using boxes for collsion shapes is a bit absurd in 2023.

Besides if that's really a necessity, Godot should not allow to add anything but BoxShapes. However right now there is a whole range of other options.

**Comment by capnm** [comment]
You can see the same issue in 3.x, if you switch the engine.

**Comment by golddotasksquestions** [comment]
I have tested this extensively in Godot3.X as well as Godot 4 on three different Windows PC hardware configurations. As described in the original issue post, Godot3 does not have this issue.

**Comment by capnm** [comment]
Project settings -> physics/3d/physics_engine -> GodotPhysics

**Comment by golddotasksquestions** [comment]
> Did you try Project settings -> physics/3d/physics_engine -> GodotPhysics ?

I know we are using GodotPhysics in G4.0 and G4.1, but I did not test it yet with GodotPhysics in G3.5 and you are correct, I can replicate this in Godot3.5 as well when using Godot Physics. So that's further evidence the that the issue is with GodotPhysics.

**Comment by Calinou** [comment]
Thanks for the report! COnsolidating with https://github.com/godotengine/godot/issues/59738, as this is the same underlying issue
.

**Comment by golddotasksquestions** [comment]
@Calinou 
This MRP is obviously not the game I am making. In my game the CharacterBodie3Ds I'm instancing are not bullets. The point of these MRP is to reproduce the issue minimally and reliably, and show how a basic Godot feature is not working as it should.
"Users should use a different feature" does not seem to be the appropriate reaction.

Thanks for linking to the other issues, I was searching on Github for this issue quite a while because I could not quite believe it not already being reported, but could not find anything.
