### ISSUE TITLE
RigidBody2D mouse_entered, mouse_exited, on_input_event signals dont work

### ISSUE THREAD

**Issue by kritma** [godotengine/godot#78769]
### Godot version

4.0.3.stable

### System information

Fedora Linux 37

### Issue description

rigidbody is pickable, but signals dont fire

### Steps to reproduce

scene: 
RigidBody2D
---Sprite2D
---CollisionShape2D

rigidbody is pickable, connect mouse_entered, mouse_exited, on_input_event signals

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
This works fine for me on v4.0.3.stable.official [5222a99f5]
It is always helpful to provide a Minimal reproduction project, so that it is easier and quicker to pinpoint the problem.

Have you made sure, that the Viewport has Object Picking enabled?

**Comment by kritma** [comment]
my bad, connected signal body_entered was connected to method i deleted, so i disconnected it and everything works.
there was no warnings or errors shown, maybe add some errors when signal connected to nothing.

**Comment by Sauermann** [comment]
> maybe add some errors when signal connected to nothing

That sounds like a good idea for improving usability. Feel free to report this separately.

**Comment by kritma** [comment]
actually, i tested again, but this time it works even if signal connected to nothing. Problem in main project was Viewport Object Picking disabled.

**Comment by kritma** [comment]
> my bad, signal body_entered was connected to method i deleted, so i disconnected it and everything works
maybe script did not connected right then.
