### ISSUE TITLE
Low FPS editor

### ISSUE THREAD

**Issue by Miskler** [godotengine/godot#78770]
### Godot version

4.0.3.stable

### System information

Win 10, i5-11400H, 16GB RAM, RTX3050M

### Issue description

When I switch to another application and then return to Godot, the editor starts to slow down a lot, usually this is solved by choosing its window, but not always

Limiting the fps of the editor when the user does not interact with it is good, but relying on the standard windows selection system in Windows is not the best idea

https://github.com/godotengine/godot/assets/69055489/5253dc9b-79af-4efb-938d-6977b8a6b622

### Steps to reproduce

Select another application, and then try to interact with the editor so that the operating system does not think that you have now switched to the Godot window

### Minimal reproduction project

not required

**Comment by mrjustaguy** [comment]
I don't think This has anything to do with Godot, this is Nvidia's Background FPS Limiter, likely set to the minimum of 20 on a laptop to save battery. Go Into Nvidia Control panel and Turn Background FPS Limiter Off

**Comment by Calinou** [comment]
This is done by design to reduce CPU/GPU utilization. To disable the FPS cap when the window is unfocused, set **Unfocused Low Processor Mode Sleep Usec** to `6900` (same value as **Low Processor Mode Sleep Usec**).
