### ISSUE TITLE
Android exports with Use Gradle Build create larger outputs

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#78780]
### Godot version

4.0.3 stable

### System information

Windows 10, OpenGL 3.3

### Issue description

Hi
when I export my project, my export file is 100MB, after using a custom template my apk file becomes 30MB, but when use Gradle build it's become 100mb again, why? it is a bug or can not have both?

### Steps to reproduce

1. Build a custom template
2. Install the Android build template
3. Add Android export
4. Add your path of the custom template
5. check using gradle build
6. export

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Are you building an AAB with the Gradle build? If so, it's expected to be larger as it contains binaries for all architectures (rather than a single architecture in the APK as you've probably configured in the Android export preset).

**Comment by akien-mga** [comment]
How do you set up the custom template? The custom Release and Debug template fields are prebuilt APKs, and thus only used for APK export (not Gradle builds).

For a custom Gradle build, you should reinstall the *source* template that you compiled yourself. I don't remember if there's an option for a custom source template in the preset or if you should unzip it manually in your project's `res://android` folder.

**Comment by DexterFstone** [comment]
> Are you building an AAB with the Gradle build?

APK v7 and v8

**Comment by DexterFstone** [comment]
> How do you set up the custom template?

https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html
https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html

**Comment by akien-mga** [comment]
> [docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html) 

That page seems slightly outdated (or more like it lacks important information on the Gradle build source template).

When you compiled from source, it should have generated `bin/android_source.zip`.

Then you should remove any existing `res://android` folder, and reinstall the source template using that self-compiled zip.

You can do that by unzipping it manually as `res://android/build`, or copying `bin/android_source.zip` to the templates folder as described in that page, or use the "Install from File" option from that dialog if it shows up when pressing "Install Android Build Template..."

![image](https://github.com/godotengine/godot/assets/4701338/a5ebc736-b1d2-4d16-8b57-ace3fba6c266)

**Comment by DexterFstone** [comment]
> > [docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html)
> 
> That page seems slightly outdated (or more like it lacks important information on the Gradle build source template).
> 
> When you compiled from source, it should have generated `bin/android_source.zip`.
> 
> Then you should remove any existing `res://android` folder, and reinstall the source template using that self-compiled zip.
> 
> You can do that by unzipping it manually as `res://android/build`, or copying `bin/android_source.zip` to the templates folder as described in that page, or use the "Install from File" option from that dialog if it shows up when pressing "Install Android Build Template..."
> 
> ![image](https://user-images.githubusercontent.com/4701338/249444410-a5ebc736-b1d2-4d16-8b57-ace3fba6c266.png)

tnx but I get an error
![image](https://github.com/godotengine/godot/assets/92402263/4e91865b-8a8f-4c73-93ac-349290a4b506)

**Comment by akien-mga** [comment]
To be sure, can you check which version of Godot you compiled from source?

You mentioned using Godot 4.0.3.stable, so you need to make sure that the custom Android template that you compile is for that same version, otherwise it can lead to compilation errors like this.

The error could also be something else of course, CC @m4gr3d who might have more insights.

**Comment by DexterFstone** [comment]
> To be sure, can you check which version of Godot you compiled from source?

My Godot 4.0.3
My Godot source is 4.0.3 and everything needed for export is 4.0.3

**Comment by DexterFstone** [comment]
> To be sure, can you check which version of Godot you compiled from source?
> 
> You mentioned using Godot 4.0.3.stable, so you need to make sure that the custom Android template that you compile is for that same version, otherwise it can lead to compilation errors like this.
> 
> The error could also be something else of course, CC @m4gr3d who might have more insights.

`# Generated using https://godot-build-options-generator.github.io

disable_3d = "yes"
optimize = "size"
minizip = "no"
module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_bullet_enabled = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gdnative_enabled = "no"
module_gltf_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_jpg_enabled = "no"
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"
module_mobile_vr_enabled = "no"
module_navigation_enabled = "no"
module_multiplayer_enabled = "no"
module_noise_enabled = "no"
module_ogg_enabled = "no"
module_opensimplex_enabled = "no"
module_openxr_enabled = "no"
module_opus_enabled = "no"
module_pvr_enabled = "no"
module_regex_enabled = "no"
module_stb_vorbis_enabled = "no"
module_svg_enabled = "no"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_visual_script_enabled = "no"
module_vorbis_enabled = "no"
module_webm_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
`
this is my custom.py, can this make a problem?

**Comment by BITQinDynasty** [comment]
I encoutered the same problem. My source code version is 4.1.1.rc and I build android release template myself with and disable_3d=yes. the generated android_release.apk and android_source.zip are all around 30MB. 
1, when <use gradle build> is disabled, the output apk size is 16MB.
2, when <use gradle build> is enabled and <export format> is apk, the output apk size is 48MB
3, when <use gradle build> is enabled and <export format> is aab, the output aab size is 16MB again.
Can anyone figure out why this happen?

**Comment by BITQinDynasty** [comment]
I encoutered the same problem. My source code version is 4.1.1.rc and I build android release template myself with and disable_3d=yes. the generated android_release.apk and android_source.zip are all around 30MB.
1, when "use gradle build" is disabled, the output apk size is 16MB.
2, when "use gradle build" is enabled and "export format" is apk, the output apk size is 48MB
3, when "use gradle build" is enabled and "export format" is aab, the output aab size is 16MB again.
Can anyone figure out why this happen?

**Comment by DexterFstone** [comment]
today I export Android with Godot v4.1 and the file size is 38MB but when using gradle build it enables the size to go up to 121MB why size is so big?

**Comment by LegatusMarcus** [comment]
@BITQinDynasty I'm used [this tweak](https://stackoverflow.com/a/62470862), and it's shrink to 20.5mb (with custom android source).

**Comment by 54cz** [comment]
> android:extractNativeLibs="true"



> @BITQinDynasty我使用了[这个调整](https://stackoverflow.com/a/62470862)，它缩小到 20.5mb（使用自定义 android 源）。
> 
> UPD：但是，由于空指针取消引用，这会导致游戏崩溃。 UPD2：没关系，看起来这是我的自定义 Android 源中的问题。要去解决这个问题。 UPD3：使用默认的 android 构建模板并设置 android:extractNativeLibs="true" 我们得到 28.1mb，与 67.5mb 相反。

Adding Android: extractNativeLibs="true" has solved the problem, and I hope the default template can be added

**Comment by m4gr3d** [comment]
@DexterFstone Can you use the [Android Studio apk analyser](https://developer.android.com/studio/debug/apk-analyzer) to check what the generated apk contains.

**Comment by DexterFstone** [comment]
> > android:extractNativeLibs="true"
> 
> > @BITQinDynasty我使用了[这个调整](https://stackoverflow.com/a/62470862)，它缩小到 20.5mb（使用自定义 android 源）。
> > UPD：但是，由于空指针取消引用，这会导致游戏崩溃。 UPD2：没关系，看起来这是我的自定义 Android 源中的问题。要去解决这个问题。 UPD3：使用默认的 android 构建模板并设置 android:extractNativeLibs="true" 我们得到 28.1mb，与 67.5mb 相反。
> 
> Adding Android: extractNativeLibs="true" has solved the problem, and I hope the default template can be added

solved

**Comment by akien-mga** [comment]
Should we consider enabling this option by default @m4gr3d ?

**Comment by m4gr3d** [comment]
> Should we consider enabling this option by default @m4gr3d ?

There are tradeoffs in doing so, notably slower app load time

> Although your APK might be larger, your application loads faster because the libraries load directly from the APK at runtime.

https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs

https://developer.android.com/build/releases/past-releases/agp-4-2-0-release-notes#compress-native-libs-dsl

**Comment by scgm0** [comment]
> > Should we consider enabling this option by default @m4gr3d ?
> 
> There are tradeoffs in doing so, notably slower app load time
> 
> > Although your APK might be larger, your application loads faster because the libraries load directly from the APK at runtime.
> 
> https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs
> 
> https://developer.android.com/build/releases/past-releases/agp-4-2-0-release-notes#compress-native-libs-dsl

But now that the option is enabled in template, why is it not enabled in Gradle build?

**Comment by m4gr3d** [comment]
@scgm0 What's the `minSdk` value you set when using the `gradle` build?

**Comment by m4gr3d** [comment]
> But now that the option is enabled in template, why is it not enabled in Gradle build?

The reason for it is that `android:extractNativeLibs=true` used to be the default behavior up until api 23. So apks compiled with `minSdk < 23` default to that and have their native libraries compressed, while apks with `minSdk >= 23` have their native libraries uncompressed by default.

The minimum sdk we support is `21`. As such the template apks are generated with `android:extractNativeLibs=true` automatcially.
The gradle build on the other hand has a default min sdk of `24` (for proper vulkan support), so by `android:extractNativeLibs` is set to `false` for those builds.
