### ISSUE TITLE
AndroidManifest.xml can't change the default <activity>

### ISSUE THREAD

**Issue by Abab-bk** [godotengine/godot#78782]
### Godot version

Godot4.0.2 Stable

### System information

Windows11, Inter i3-8100, RX580 2048SP, GLES2.

### Issue description

I want to start my own Activity before .GodotApp starts because the Chinese app market requires users to read and agree to the privacy policy before applying for permissions.
When I checked "use_gradle_build" and modified the Activity corresponding to ".GodotApp" in android/build/AndroidManifest.xml, I removed the "intent-filter" from it and added it to my custom Activity. Then I built the app.
When I installed the app, two game icons appeared on my phone. I know this is because there are two "intent-filter" tags.

### Steps to reproduce

1. Open android/build/AndroidManifest.xml.
2. removed the "intent-filter".
3. added it to custom Activity.
4. built the app.
5. You will find that the previously deleted intent-filter in AndroidManifest.xml still exists, and two intent-filter exist at this time.

### Minimal reproduction project

I had one, but it was too big after packing.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/76963.

**Comment by Abab-bk** [comment]
I found a temporary solution: just set the AndroidManifest.xml automatically generated by release/debug to read-only.
