### ISSUE TITLE
Error on exit about pages still in use for Thread and WorkerThreadPool::Task

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#78790]
### Godot version

4.1.rc (9a09ee5d0217c4d5e5668fccddfa477bf16af357)

### System information

Mageia 9, Linux

### Issue description

On some projects (exact characteristics TBD, my MRP uses a VideoStreamPlayer that autoplays a video with sound), the following errors are printed in the console when closing the project:

```
ERROR: Pages in use exist at exit in PagedAllocator: 6Thread
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N16WorkerThreadPool4TaskE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

It happens both when closing the window with the cross button, or Alt+F4. It doesn't happen all the times, and might be related to quitting very early on (i.e. start, then close shortly after the scene starts).

### Steps to reproduce

- Run MRP directly, quit shortly after the window initialized and the scene starts rendering / playing the video.
- It may print the above errors in the terminal. If not, try again a few times.

### Minimal reproduction project

[VideoScene.zip](https://github.com/godotengine/godot/files/11893613/VideoScene.zip)
(MRP derived from https://github.com/godotengine/godot/issues/78788, but I've seen this in other scenes not using VideoStreamPlayer.)

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by akien-mga** [comment]
Simpler MRP:
```
$ Godot_v4.1-rc2_linux.x86_64 --dump-extension-api --dump-gdextension-interface
Dumping Extension API
Dumping GDExtension interface header file
Godot Engine v4.1.rc2.official.46424488e - https://godotengine.org
Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #1: AMD - AMD Radeon RX Vega M GL Graphics (RADV VEGAM)
 
ERROR: Pages in use exist at exit in PagedAllocator: 6Thread
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N16WorkerThreadPool4TaskE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

Like the OP, doesn't happen all the time, but run that command several times and it should happen ~50% of the time.

**Comment by germanbv** [comment]
for me, this started to happen 100% of the time after adding the Dialogue Manager addon to the project:

```
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1127)
ERROR: Pages in use exist at exit in PagedAllocator: 6Thread
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N16WorkerThreadPool4TaskE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

I'm on Windows 10, and I'm using 4.1 mono

**Comment by Quimerateck** [comment]
Just installed godot 4 mono, and ... got the same thing as the original post, with a mostly blank project

im using a n4000 with UHD  600 laptop

**Comment by Quimerateck** [comment]
Found something that could help,
using the following in my shortcut
`--rendering-driver opengl3`
seems to work and the error no longer shows up

**Comment by Zylann** [comment]
Just upgraded my fork to the 4.2 branch, got two of these when closing the editor with my project:
```
ERROR: Pages in use exist at exit in PagedAllocator: class Thread
   at: PagedAllocator<class Thread,0>::~PagedAllocator (D:\PROJETS\INFO\GODOT\Engine\godot4_fork\core/templates/paged_allocator.h:170)
D:\PROJETS\INFO\GODOT\Engine\godot4_fork\core/templates/paged_allocator.h:170 - Pages in use exist at exit in PagedAllocator: class Thread
ERROR: Pages in use exist at exit in PagedAllocator: struct WorkerThreadPool::Task
   at: PagedAllocator<struct WorkerThreadPool::Task,0>::~PagedAllocator (D:\PROJETS\INFO\GODOT\Engine\godot4_fork\core/templates/paged_allocator.h:170)
D:\PROJETS\INFO\GODOT\Engine\godot4_fork\core/templates/paged_allocator.h:170 - Pages in use exist at exit in PagedAllocator: struct WorkerThreadPool::Task
```

**Comment by bikemurt** [comment]
Also happening here. I use the OpenGL (compat) backend usually, but I also converted to Forward+ and getting the same errors. I am also using DialogueManager, so I am wondering if that is the culprit.
