### ISSUE TITLE
Function and const from shader include should ignore unused warning

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#78801]
### Godot version

4.0.3

### System information

Win7

### Issue description

As shader include contain a lot of function used in multiple shader, and shader usually do not use all function from shader include, so the unused warning should be ignored.

shader include:
![image](https://github.com/godotengine/godot/assets/28286958/c4367f31-0dee-4f1d-a16a-a76f26758bb1)

shader:
![image](https://github.com/godotengine/godot/assets/28286958/728c8d12-3e5f-45ba-9f87-e7f87b0793b8)

### Steps to reproduce

1. Create shader and shader include
2. Add multiple function to shader include
3. Add shader include to shader

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This sounds like proposal territory, I'd suggest opening one over at [proposals](https://github.com/godotengine/godot-proposals), make sure to follow all the directions

**Comment by AThousandShips** [comment]
* Closing in favour of https://github.com/godotengine/godot-proposals/issues/7172
