### ISSUE TITLE
Shader cannot use unsigned int suffix with hex

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#78800]
### Godot version

4.0.3

### System information

Win7

### Issue description

![image](https://github.com/godotengine/godot/assets/28286958/abec9d3c-e078-424c-9430-d9fe8897aad6)

### Steps to reproduce

1. Create shader
2. Add uint with hex, e.g. 0xffffu

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Is this valid in the GLSL specification?

**Comment by AThousandShips** [comment]
It is in GLSL 4.6 at least according to the specs

**Comment by Kinwailo** [comment]
I search some glsl code, it doesn't force to use "u" suffix assign to uint.
In gdshader, it don't allow to use: `uint a = 1;`
