### ISSUE TITLE
gdshader reload/hot_reload does not work

### ISSUE THREAD

**Issue by ooo-mmm** [godotengine/godot#78808]
### Godot version

4.0.3 stable mono

### System information

Windows 11

### Issue description

Changes done in .gdshader editor file are not being reflected in play mode. 

### Steps to reproduce

- Load a mesh in scene 3D
- add a shader material to it.
- add new shader file type of .gdshader type (in my case: https://godotshaders.com/shader/quick-procedural-floor-tiles/)
- play the scene and exit
- now change content of .gdshader and observe changes are only being reflected in editor not in play mode
- reload saved scene reset the changes done in above steps in editor as well even though .gdshader file is modified

### Minimal reproduction project

[issue_hotreload_gdshader.zip](https://github.com/godotengine/godot/files/11899106/issue_hotreload_gdshader.zip)

**Comment by bitsawer** [comment]
I don't think play-mode shader hot-reload has ever been implemented, at least not in Godot 4.x and I don't think it was in 3.x, either. Scripts and node-tree can be live-synced, but not shaders and similar resources as far as I know. However, it would be a nice feature, although there is a proposal for that with some extra details: https://github.com/godotengine/godot-proposals/issues/5269 That would turn this issue more into a feature request.

Interestingly, this is not the first time I have seen a bug report about shader live-reloading, but in that the user soon noticed that it had never been implemented at all and was just remebered it wrong. Although I think that report was in Godot Reddit, not in Github.

**Comment by bitsawer** [comment]
Closing this issue as new feature requests should be done in https://github.com/godotengine/godot-proposals

I previously linked https://github.com/godotengine/godot-proposals/issues/5269 which is a more general resource sync proposal, but it should also apply to shaders and to this issue.
