### ISSUE TITLE
C#: Editor restart needed for script properties to be exposed in the inspector

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#78804]
### Godot version

4.1.RC1

### System information

Windows 10

### Issue description

When assigning a script that exposes properties (using the `[Export]` attribute) to a resource, the Editor needs to be restarted in order for the properties to show up in the inspector.

### Steps to reproduce

Using the minimal repro project:

1) Delete the `.godot` cache folder
2) Assign `NodeResource.cs` to `node_resource.tres` script properties.
3) Notice that the inspector does not update to show the `Value` properties of class `NodeResource`
4) Restart the Editor.
5) Notice that now the inspector is exposing the properties `Value`

Before restarting the editor
![2](https://github.com/godotengine/godot/assets/11413364/43e57ac7-5d5c-44e1-acf0-6fac19eeec23)

After restarting the editor
![3](https://github.com/godotengine/godot/assets/11413364/246c4f4f-5370-4a07-a1e3-40e3f3b642e0)

### Minimal reproduction project

[Godot41Test.zip](https://github.com/godotengine/godot/files/11898333/Godot41Test.zip)

**Comment by duarteroso** [comment]
I should have played with the betas. Mea culpa.

**Comment by AThousandShips** [comment]
Duplicate of: #78765?

**Comment by duarteroso** [comment]
> Duplicate of: #78765?

Seems like it
