### ISSUE TITLE
Headless web export does not produce a runnable web artifact cause of not replaced project variables

### ISSUE THREAD

**Issue by scovillo** [godotengine/godot#78814]
### Godot version

Godot_v4.0.3-stable_linux.x86_64

### System information

Debian 11, Kernel 5.10.0-21-amd64, arch x86_64

### Issue description

Hello guys,

exporting a project to web in headless mode breaks the generated artifact, because several godot project variables are not replaced. Doing the same export through GUI, everything works like expected, the godot project variables are replaced and the artifact works deployed like a charm.

Command used:
`mkdir -p html && ~/Godot_v4.0.3-stable_linux.x86_64 --display-driver headless --export-debug "Web" html/web-export-project-variables-bug`

Firefox shows errors on loading the game:

```
GET https://xxxxxx.de/$GODOT_URL 
[HTTP/2 404 Not Found 24ms]

Laden fehlgeschlagen für das <script> mit der Quelle "https://xxxxxx.de/$GODOT_URL". Uncaught ReferenceError: $GODOT_CONFIG is not defined
```
The tab title is not set:
![grafik](https://github.com/godotengine/godot/assets/130607437/71c75e6b-494b-4b3b-9a2d-b7a1af9cb138)

Checking the index.html shows not replaced variables, e. g.:

```<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no">
<title>$GODOT_PROJECT_NAME</title>
<style>
...
</style>
$GODOT_HEAD_INCLUDE
</head>
...
```
Expected behavior: Like the GUI web export, the headless web export by command should also produce a runnable artifact with all project variables replaced.

Thank you for the work on this great engine, I love it pretty much!

### Steps to reproduce

1. Take a plain project
2. Setup web export with templates and default conf
3. Optional: Export to web and check how it is looking with replaced project variables
4. Run `mkdir -p html && ~/Godot_v4.0.3-stable_linux.x86_64 --display-driver headless --export-debug "Web" html/web-export-project-variables-bug`
5. Check the web-export-project-variables-bug.html and see the project variable placeholders are not replaced
6. Optional: Deploy the web artifact on a https server of your choice and read the errors on starting the game

### Minimal reproduction project

[web-export-headless-project-variables-bug.zip](https://github.com/godotengine/godot/files/11900316/web-export-headless-project-variables-bug.zip)

**Comment by svelezw4games** [comment]
Hey! I might know whats happening, for web export you need to write the full export path including the file extension .html , this means, you export command should be

`mkdir -p html && ~/Godot_v4.0.3-stable_linux.x86_64 --display-driver headless --export-debug "Web" html/web-export-project-variables-bug/index.html`

I tried with the project you gave as example, and all variables get resolved correctly

![image](https://github.com/godotengine/godot/assets/132154718/062c1f5c-11bf-4346-9b21-5f9e11bd77a8)

The command I used, was:

```
/linux_editor.x86_64 --headless -v --path /home/santiago/Documents/games/web-export-headless-project-variables-bug --export-release Web /home/santiago/Documents/games/repro_bug/index.html
```

That projetc still fails to run because it does not have a main scene

**Comment by scovillo** [comment]
Hi, thank you for the reply. Awesome! This fixed the problem and the build artifact works like a charm.

> for web export you need to write the full export path including the file extension .html 

This is the solution.
