### ISSUE TITLE
Tooltip panel has grey background behind corners

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#78823]
### Godot version

4.0.3-stable

### System information

Arch linux, i3 wm

### Issue description

I'm experiencing a 'bug' with tooltips. The moment you round the corners, you can see some grey box behind the tooltip. I don't think this is intended to be there, but correct me if I am wrong or if I'm doing something wrong here.

![BugGodot](https://github.com/godotengine/godot/assets/56970759/fbe2bf1f-9f55-45ec-aead-0682c8d09621)

### Steps to reproduce

Use a custom theme, change the panel property of the tooltip and add rounded corners.

### Minimal reproduction project

[tooltip_bug.zip](https://github.com/godotengine/godot/files/11903408/tooltip_bug.zip)

**Comment by akien-mga** [comment]
> Does not require a project.

That would actually be very helpful to make sure we can test the right scenario and reproduce the issue.

**Comment by voylin** [comment]
> > Does not require a project.
> 
> That would actually be very helpful to make sure we can test the right scenario and reproduce the issue.

I've added a test project, but it is basically what the reproduction steps say. I've been trying to figure out why this happens but I can't quite find why it does that. 

Maybe it inherits from window, like popup does, and it does not make the window itself transparent? if that is the case it would be an easy fix, but I don't have much time to actually check it out. I may give it a try tomorrow morning to see if that would fix it

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/78823.
