### ISSUE TITLE
Autocompletion does not work for Dictionary.get() return value

### ISSUE THREAD

**Issue by heppocogne** [godotengine/godot#78820]
### Godot version

4.0.3-stable

### System information

Windows 11, NVIDIA GeForce GTX 1650

### Issue description

When I assigned Dictionary.get() return value to a typed variable, autocompletion dialog did not show up.

### Steps to reproduce

Please try the following script. Autocompletion dialog is not shown up for `my_class_get` even if typing ".my_" or something.
```gdscript
extends Node

class MyClass:
	var my_var


	func my_func():
		pass


var dic:={
	"a":MyClass.new(),
}


func _ready():
	var my_class_get:MyClass=dic.get("a",MyClass.new())
	my_class_get	# autocompletion does not work
	var my_class_bracket:MyClass=dic["a"]
	my_class_bracket	# autocompletion works
```

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
Same in v4.1.rc1.official [1f9e540f1].

**Comment by heppocogne** [comment]
`Array.front()` and `Array.back()` have the same issue.
```
	var array:Array=[MyClass.new()]
	var my_class_array_bracket:MyClass=array[0]
	my_class_array_bracket	# autocompletion works
	var my_class_array_front:MyClass=array.front()
	my_class_array_front	# autocompletion does not work
	var my_class_array_back:MyClass=array.back()
	my_class_array_back	# autocompletion does not work
```
