### ISSUE TITLE
Gridmap doesn't perform far clip/distance draw culling

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#78825]
### Godot version

Godot_v3.6-beta2_win64

### System information

Windows 10

### Issue description

Gridmap doesn't inherit from VisualServer and uses MultiMeshes to optimise mesh placement, however distance draw/far clipping on the camera is ignored and this really should be possible (if not for performance, for aesthetic purposes).

### Steps to reproduce

* Add gridmap node
* Paint a mesh into the distance
* Set camera far shorter
* Gridmap won't be clipped at a distance

### Minimal reproduction project
[test_gridmap.zip](https://github.com/godotengine/godot/files/11903070/test_gridmap.zip)

**Comment by elvisish** [comment]
This is very weird and embarrassing, but making a test project it seems to be working. I'll try to figure out why it's not working on my main project, perhaps a shader material I'm using is interfering with the cull distance, I'll close this later if that turns out to be the cause of this.

**Comment by Calinou** [comment]
> This is very weird and embarrassing, but making a test project it seems to be working. 

Which octant size are you using in your other project? Larger octant sizes reduce culling opportunities, as each MultiMesh will span a larger area.

**Comment by elvisish** [comment]
> > This is very weird and embarrassing, but making a test project it seems to be working.
> 
> Which octant size are you using in your other project? Larger octant sizes reduce culling opportunities, as each MultiMesh will span a larger area.

The default size, that's what surprised me about my test.
