### ISSUE TITLE
Enabling 3D avoidance on a NavigationAgent3D causes a crash

### ISSUE THREAD

**Issue by ckaiser** [godotengine/godot#78826]
### Godot version

v4.1.rc.custom_build.c83f912bc

### System information

Godot v4.1.rc (c83f912bc) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Enabling "Use 3D Avoidance" on the editor makes it crash instantly.

Crash seems to be on `queryAgentTreeRecursive`, where `agentTree_ ` is empty and the 0 element is trying to be accessed, unsure if this is because the layout of the agent/navmesh tree is unexpected or what is the actual cause, I'm not familiar with the codebase.

![image](https://github.com/godotengine/godot/assets/138269/ade8db3c-acfe-49ce-9898-a3b195898cc9)

I've attached a minidump, an example project and some more exception details:

```
Exception thrown: read access violation.
**std::vector<RVO3D::KdTree3D::AgentTreeNode,std::allocator<RVO3D::KdTree3D::AgentTreeNode> >::operator[]**(...) returned nullptr.
```

```
godot.windows.editor.dev.x86_64.exe!RVO3D::KdTree3D::queryAgentTreeRecursive(RVO3D::Agent3D * agent, float & rangeSq, unsigned __int64 node) Line 191
	at K:\Dev\godot\thirdparty\rvo2\rvo2_3d\KdTree3d.cc(191)
godot.windows.editor.dev.x86_64.exe!RVO3D::KdTree3D::computeAgentNeighbors(RVO3D::Agent3D * agent, float rangeSq) Line 187
	at K:\Dev\godot\thirdparty\rvo2\rvo2_3d\KdTree3d.cc(187)
godot.windows.editor.dev.x86_64.exe!RVO3D::Agent3D::computeNeighbors(RVO3D::RVOSimulator3D * sim_) Line 373
	at K:\Dev\godot\thirdparty\rvo2\rvo2_3d\Agent3d.cc(373)
godot.windows.editor.dev.x86_64.exe!NavMap::compute_single_avoidance_step_3d(unsigned int index, NavAgent * * agent) Line 1110
	at K:\Dev\godot\modules\navigation\nav_map.cpp(1110)
godot.windows.editor.dev.x86_64.exe!WorkerThreadPool::GroupUserData<NavMap,void (__cdecl NavMap::*)(unsigned int,NavAgent * *),NavAgent * *>::callback_indexed(unsigned int p_index) Line 159
	at K:\Dev\godot\core\object\worker_thread_pool.h(159)
godot.windows.editor.dev.x86_64.exe!WorkerThreadPool::_process_task(WorkerThreadPool::Task * p_task) Line 91
	at K:\Dev\godot\core\object\worker_thread_pool.cpp(91)
godot.windows.editor.dev.x86_64.exe!WorkerThreadPool::_process_task_queue() Line 51
	at K:\Dev\godot\core\object\worker_thread_pool.cpp(51)
godot.windows.editor.dev.x86_64.exe!WorkerThreadPool::_thread_function(void * p_user) Line 195
	at K:\Dev\godot\core\object\worker_thread_pool.cpp(195)
godot.windows.editor.dev.x86_64.exe!Thread::callback(unsigned __int64 p_caller_id, const Thread::Settings & p_settings, void(*)(void *) p_callback, void * p_userdata) Line 63
	at K:\Dev\godot\core\os\thread.cpp(63)
```

### Steps to reproduce

1. Open the demo project
2. Go to the NavigationAgent3D node properties
3. Click on the "Use 3D Avoidance" checkbox

### Minimal reproduction project

[Example Project](https://github.com/godotengine/godot/files/11902989/avoidance_example.zip)

[Crash Minidump](https://github.com/godotengine/godot/files/11903055/godot.windows.editor.dev.x86_64.zip)

**Comment by akien-mga** [comment]
I can reproduce the issue on Linux, with a similar stacktrace.

It also prints this error before the crash:
```
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (./scene/main/node.cpp:2208)
```

**Comment by smix8** [comment]
Regression from https://github.com/godotengine/godot/pull/78099. Works fine again when reverting.

**Comment by akien-mga** [comment]
I'm fine reverting #78099 and reworking it for 4.2 if that's what you would recommend.

**Comment by smix8** [comment]
I am looking into it but if I can not find the issue I would say revert before you make RC2.
