### ISSUE TITLE
Array insert() function loses data from a dictionary

### ISSUE THREAD

**Issue by AlfonsoGrimaldo** [godotengine/godot#78822]
### Godot version

v4.1.rc.custom_build [c83f912bc]

### System information

Windows 11

### Issue description

When it comes to storing data in an empty array with specific data from a dictionary, some of them are not stored in the array.
Here is an example code:

```
extends Node

var dict_test = {
	"key1" : [1, false],
	"key2" : [2, true],
	"key3" : [3, false],
	"key4" : [4, false],
	"key5" : [5, true],
}

func _ready():
	var array_test : Array
	
	for i in dict_test.size():
		var key = dict_test.keys()[i]
		if dict_test[key][1] == false:
			array_test.insert(i, dict_test[key][0])
	print(array_test)
```
It should print [1, 3, 4] but it prints [1]

### Steps to reproduce

Run the sample code.

### Minimal reproduction project

N/A

**Comment by heppocogne** [comment]
This would be because the position of insertion is invalid.
https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-insert

**Comment by KoBeWi** [comment]
Yep, you even get an error:
![image](https://github.com/godotengine/godot/assets/2223172/2737fc6a-74bf-4a6b-a417-275d16f3243c)
You should be using `append()` here.

**Comment by AlfonsoGrimaldo** [comment]
I don't understand why this works on python but not in gdscript.
The code here is a bit different from the one I provided as an example, but it produces the same result.

```
dict_test = {
	"key1" : [1, False],
	"key2" : [2, True],
	"key3" : [3, False],
	"key4" : [4, False],
	"key5" : [5, True],
}

def _ready():
    array_test = []
    i = 0
    
    for key in dict_test:
        if dict_test[key][1] == False:
	        array_test.insert(i, dict_test[key][0])
        i += 1
    print(array_test)

_ready()
```

**Comment by AThousandShips** [comment]
Because GDScript isn't python? It doesn't work this way

**Comment by AlfonsoGrimaldo** [comment]
@AThousandShips I'm sorry for calling you "men," miss. Just to make it clearer, before reviewing the documentation, it was my mistake, and I apologize for that. I reviewed Python to verify that behavior because, in my opinion, it seemed like an error. However, I admit that I jumped to hasty conclusions.
