### ISSUE TITLE
Control node does not provide global position if placed under container

### ISSUE THREAD

**Issue by himaghnam** [godotengine/godot#78842]
### Godot version

4.1 RC1

### System information

Windows 10

### Issue description

Control node does not provide global position if placed under container

### Steps to reproduce

1. Create a Horizontal/Vertical box container
2. Create Texture Rect node inside it and duplicate 3-4 times
3. Check the last node global position ~ print($HBoxContainer/TextureRect3.get_global_rect()) or print($HBoxContainer/TextureRect3.global_position)
4. Result  = (0,0)

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Thanks @Sauermann, closing as duplicate then.
