### ISSUE TITLE
Executing `RichTextLabel.parse_bbcode` freeze Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#78849]
### Godot version

4.1.rc.custom_build. c83f912bc

### System information

Ubuntu 22.04 CI

### Issue description

When executing
```
extends Node
func _process(delta):

	var temp_variable35241 = RichTextLabel.new()
	add_child(temp_variable35241)
	temp_variable35241.set_fit_content(true)
	temp_variable35241.parse_bbcode("3188932498")
	temp_variable35241.queue_free()
```
this code freeze project in CI for at least 60 seconds

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by heppocogne** [comment]
What does "3188932498" mean?

**Comment by akien-mga** [comment]
It's just a random string to see what happens when passing invalid/unpredictable input to the API.
