### ISSUE TITLE
Far clip is based on depth, not distance from the camera

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#78855]
### Godot version

3.5

### System information

Windows 10, Vulkan, RTX 3060 (466.81)

### Issue description

When rotating the camera with a short far clip, meshes can be seen slicing as the rotation changes:

https://github.com/godotengine/godot/assets/16231628/8e8f84f9-9285-4c43-983b-ba1f6ebab38f

This is because the distance fade is going on the depth rather than the distance:
![image](https://github.com/godotengine/godot/assets/16231628/ff06addd-94ff-441b-be94-fc4ec1916114)

Similar to: https://github.com/godotengine/godot/issues/53853

### Steps to reproduce

* Add a camera
* Use a short far clip
* Rotate the camera

### Minimal reproduction project

[farclip_test.zip](https://github.com/godotengine/godot/files/11910655/farclip_test.zip)

**Comment by elvisish** [comment]
I feel as though there is a similar proposal, though I can't actually find it right now.

**Comment by Calinou** [comment]
This is expected. The "clip" in "far clip" stands for a clipping *plane*.

If you want things to fade out in a circular fashion, use [distance fog](https://github.com/godotengine/godot-proposals/issues/4619).
