### ISSUE TITLE
[2.1.2] why no direct character control in 2.1.x official releases ?

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#7886]
Is there a problem with its implementation or should we expect it for a new release ?

If it's not clear from the title, I'm referring to the missing kinematicbody functions for direct character control in the current stable official release (2.1.2).
- move_and_slide
- is_move_and_slide_on_floor() 
and so on.
It seems the 2.2 where all cool stuff used to be added, is not currently updated and the official 2.1.x branch is missing many feature from 2.2.  Some, I understand, were buggy (see Input.is_action_just_pressed() ), but some may not.

[edited to add examples of functions missing, since the title is still confusing]

**Comment by RebelliousX** [comment]
Unfortunately, I think all features added to 2.2 are shifted to 3.0. But this is good in a way that lets developers focus on 3.0.

Besides, the functions you mentioned are not critical since you can use the old way in the documentation and the character 2d demo.

**Comment by plucian** [comment]
many goodies have been left behind in 2.2.
3.0 doesn't sit well with me due to the higher requirements which leaves out half of the phone market and 3.1 is going to be long in the making .. So I'm pushing for a better 2.1.x.. not even for newer things, only for what's been done already.

**Comment by karroffel** [comment]
@plucian There are plans to include a GLES2 compatible renderer in 3.1, it won't be as powerful and not support all rendering features, but the rest of the engine will have 3.0 features.

Currently bug fixes have to be cherry picked to the 2.1 branch as well, there's no real interest in having the 2.2 branch updated, since that is just like a more incomplete version of 3.0 with a worse renderer.

So updating 2.2 will be more work for less gain, so if you really need/want GLES2 compatibility then you probably need to wait for 3.1 to use the new features. (or just use the legacy 2.2 branch without any dev support)

**Comment by plucian** [comment]
@karroffel I know about the plans for 3.1, and I'm not asking about 2.2 branch. Seems you missed some of my comments, or they were not clear enough. I'm just asking for everything good from 2.2 to be moved to 2.1 branch.

**Comment by marcelofg55** [comment]
I've ported locally the move_and_slide funcs for 2.1, @akien-mga should make a PR with the changes?

**Comment by akien-mga** [comment]
I think that would be worth at least testing, I know a @punto- that would be very interested :)

**Comment by marcelofg55** [comment]
@akien-mga @punto- I've added the move_and_slide changes on this branch: https://github.com/marcelofg55/godot/tree/move_and_slide

**Comment by marcelofg55** [comment]
@plucian #10306 was just merged so now the 2.1 branch now has the move_and_slide functions. Any other feature missing in 2.1 that the old 2.2 branch had?

**Comment by plucian** [comment]
most have been moved or upgraded, so this should be closed now. I'll compile now to see it in action ! Good work man !

**Comment by eon-s** [comment]
@marcelofg55 does this implementation of move_and_slide have a fixed floor angle? the one on 3 has it as a parameter.
