### ISSUE TITLE
Player Inconsistently Crashes when edit GlobalPosition without being in "tree" C# verified. Not GD Script verified. 

### ISSUE THREAD

**Issue by hislittlecuzin** [godotengine/godot#78863]
### Godot version

4.0.3

### System information

Windows 10 64 bit. Godot Mono. Ryzen 5, RX 6000, .Net 6 iirc

### Issue description

When you spawn nodes in C#, it can inconsistently crash when you edit the Global Position before adding it to the tree.. like so:

```cs
BB newBB = bb.Instantiate<BB>();
newBB.GlobalPosition = bbSpawn.GlobalPosition;
newBB.Rotation = bbSpawn.GlobalRotation;
GetParent().AddChild(newBB);
```

Circled in green. (Solved other bug. Not relevant to crash.)
![image](https://github.com/godotengine/godot/assets/32988055/28405fea-1f99-43b6-b490-18d066f48661)

![image](https://github.com/godotengine/godot/assets/32988055/55a8e2e6-e9f8-4295-9966-1f7a125eb62b)
![image](https://github.com/godotengine/godot/assets/32988055/4cf322a6-6d59-47bc-8a4d-9be3af4a98d6)

![image](https://github.com/godotengine/godot/assets/32988055/9e3f48f0-3b99-4420-bf93-6ae075d07a13)
![image](https://github.com/godotengine/godot/assets/32988055/92e61d05-e16e-4680-8173-c3d81ec5ddc4)

### Steps to reproduce

Edit the GlobalPosition before adding the node as a child of an object. 

This can take anywhere from 8 times to 1~200 times.

I noticed it because I made a machinegun. 

### Minimal reproduction project

Make a project where you can spawn nodes like a machinegun. 
Before they enter the tree make sure you edit a global property.
I only verified it crashes with globalposition.

**Comment by RedworkDE** [comment]
This needs an MRP, the stack trace involves a bunch of code that is not shown in your post.

Does the not gs script verified in your title mean that you tried this in gd script as well and it did not crash there or did you just not try with gd script?

Please do try with gd script (if you haven't already) and include that code in your MRP.

**Comment by RedworkDE** [comment]
> The unrelated code noted in the stack trace is irrelevant information.

If the stack traces are entirely unrelated why do you include them? They point at a crash related to `move_and_slide` and not the global position.

> One person said they tried it and didn't crash.

Tbh this most likely just means that the crash is more complicated than what you describe here, so again **THIS NEEDS AN MRP**.

**Comment by hislittlecuzin** [comment]
> > The unrelated code noted in the stack trace is irrelevant information.
> 
> If the stack traces are entirely unrelated why do you include them? They point at a crash related to `move_and_slide` and not the global position.
> 
> > One person said they tried it and didn't crash.
> 
> Tbh this most likely just means that the crash is more complicated than what you describe here, so again **THIS NEEDS AN MRP**.

Yeah, so I am getting crashes with something else. 
It might be because I removed something with Velocity. 

I'm not sure if there's a "put issue on hold" checkbox, but it's crashing probably from something else.

**Comment by hislittlecuzin** [comment]
It's likely not Steamworks... I compiled the latest version which is 3 years newer than the one I was using. 

I'm not sure if this script could cause it...
```cs
using Godot;
using System;

public partial class PlayerPawn : CharacterBody3D {
	public const float Speed = 5.0f;
	public const float JumpVelocity = 4.5f;

	// Get the gravity from the project settings to be synced with RigidBody nodes.
	public float gravity = ProjectSettings.GetSetting("physics/3d/default_gravity").AsSingle();

	Vector2 inputDir = Vector2.Zero;

	[Export]
	public Camera3D camera;
    [Export]
    float mouseSensitivity = .003f;
	[Export]
	PackedScene bb;
	[Export]
	Node3D bbSpawn;

	bool hitAndOut = false;

	bool shooting = false;
	static double[] shootingDelay = { .2, .4, .6 };

	public void SetHitAndOut(bool newValue) {
		hitAndOut = newValue;
    }

    public void ReceiveInput(ClientToServerControllerInput input, bool pressed) {

		if (hitAndOut) {
			shooting = false;
			inputDir = Vector2.Zero;
            return;
        }

        switch (input) {
			case ClientToServerControllerInput.MoveForward:
				if (pressed)
					inputDir.Y -= 1;
				else
					inputDir.Y += 1;
				break;
			case ClientToServerControllerInput.MoveBackward:
				if (pressed)
					inputDir.Y += 1;
				else
					inputDir.Y -= 1;
                break;
			case ClientToServerControllerInput.MoveLeft:
				if (pressed)
					inputDir.X -= 1;
				else
					inputDir.X += 1;
                break;
			case ClientToServerControllerInput.MoveRight:
				if (pressed)
					inputDir.X += 1;
				else
					inputDir.X -= 1;
                break;
			case ClientToServerControllerInput.Shoot:
				if (pressed) shooting = true;
				else shooting = false;
				break;
			default:
				break;
		}
	}

	public void ReceiveLookInput(Vector2 mouseMovement) {
        RotateObjectLocal(Vector3.Down, mouseMovement.X * mouseSensitivity);
        camera.RotateObjectLocal(Vector3.Left, mouseMovement.Y * mouseSensitivity);
    }

	double shootTimer = 0.0;
	public override void _PhysicsProcess(double delta) {
		

        #region shooting
        shootTimer += delta;
        if (shooting && shootTimer >= shootingDelay[0]) {
			shootTimer = 0.0;
			BB newBB = bb.Instantiate<BB>();
            newBB.Position = bbSpawn.GlobalPosition;
            newBB.Rotation = bbSpawn.GlobalRotation;
            GetParent().AddChild(newBB);
            //GlobalTransform.Basis.GetEuler();

        }
		#endregion


		#region movement
		//Vector3 velocity = Velocity;
		Vector3 velocity;
		velocity.X = inputDir.X;
		velocity.Z = inputDir.Y;
		velocity.Y = 0;

		// Add the gravity.
		if (!IsOnFloor())
			velocity.Y -= gravity * (float)delta;

        // Get the input direction and handle the movement/deceleration.
        // As good practice, you should replace UI actions with custom gameplay actions.
        //Vector2 inputDir = Input.GetVector("ui_left", "ui_right", "ui_up", "ui_down");
		Vector3 direction = (Transform.Basis * new Vector3(inputDir.X, 0, inputDir.Y)).Normalized();
		if (direction != Vector3.Zero) {
			velocity.X = direction.X * Speed;
			velocity.Z = direction.Z * Speed;
		}
		else {
			velocity.X = Mathf.MoveToward(Velocity.X, 0, Speed);
			velocity.Z = Mathf.MoveToward(Velocity.Z, 0, Speed);
		}

		velocity.Rotated(Vector3.Up, Rotation.Y);

		Velocity = velocity;
		MoveAndSlide();
        #endregion
    }
}

```

**Comment by hislittlecuzin** [comment]
Getting an error here for some reason
![image](https://github.com/godotengine/godot/assets/32988055/24c72337-4e11-4e1e-a777-a68ea5247de1)
I thought I handled it but I guess not? 
![image](https://github.com/godotengine/godot/assets/32988055/db40eda0-5849-4582-9252-521126c2a5b5)

**Comment by hislittlecuzin** [comment]
![image](https://github.com/godotengine/godot/assets/32988055/abfe5e2c-bc9c-4ff4-8941-0e8908b8dfba)
I have no idea what's going on.

Just upgraded to 4.1 RC.

**Comment by hislittlecuzin** [comment]
It is 100% the character mover. I will report it in a new issue. Thanks for your help!! 

`MoveAndSlide` causes it.
