### ISSUE TITLE
Export var not set when use setget

### ISSUE THREAD

**Issue by Miskler** [godotengine/godot#78862]
### Godot version

4.0.3.stable

### System information

Win 10, i5-11400H, 16GB RAM, RTX3050M

### Issue description

Code:
```
@tool
extends Node

@export var width:float = 10 :
	set(value):
		tool_width_set(value)
func tool_width_set(widt:float):
	if widt > 0:
		$Line2D.width = widt
		printt(widt, width)
```

https://github.com/godotengine/godot/assets/69055489/73e4cce1-6c98-4f60-9445-ef684996097f

The export variable does not change its value _(although the new value enters the bound function)_

If you add at the end of the function `return widt` it won't change anything

If you add at the end of the function `width = widt` this will cause an infinite recursion

**Comment by dalexeev** [comment]
> If you add at the end of the function `width = widt` this will cause an infinite recursion

This is expected, since you are changing the variable not in the setter, but in the function that is called in the setter. The following two options are correct:

```gdscript
var my_var:
    set(value):
        my_var = value
```

```gdscript
var my_var: set = set_my_var

func set_my_var(value):
    my_var = value
```

The following option results in an infinite recursion:

```gdscript
var my_var:
    set(value):
        set_my_var(value)

func set_my_var(value):
    my_var = value
```

> The export variable does not change its value _(although the new value enters the bound function)_

You don't change the `width` value in the code above, so the variable doesn't change.

**Comment by KoBeWi** [comment]
Try adding
```GDScript
	get:
		return $Line2D.width
```

**Comment by Miskler** [comment]
> > If you add at the end of the function `width = widt` this will cause an infinite recursion
> 
> This is expected, since you are changing the variable not in the setter, but in the function that is called in the setter. The following two options are correct:
> 
> ```gdscript
> var my_var:
>     set(value):
>         my_var = value
> ```
> 
> ```gdscript
> var my_var: set = set_my_var
> 
> func set_my_var(value):
>     my_var = value
> ```
> 
> The following option results in an infinite recursion:
> 
> ```gdscript
> var my_var:
>     set(value):
>         set_my_var(value)
> 
> func set_my_var(value):
>     my_var = value
> ```
> 
> > The export variable does not change its value _(although the new value enters the bound function)_
> 
> You don't change the `width` value in the code above, so the variable doesn't change.

Thank you! Would you consider the idea of making editor hints and syntax highlighting for such code? _(`set =` and the name of the `function_existent_name`)_
![image](https://github.com/godotengine/godot/assets/69055489/991c7354-c489-4173-b1d3-3f492f4512ee)
