### ISSUE TITLE
Intellisense on my custom class don't work when I assign a node to a variable of this class

### ISSUE THREAD

**Issue by Paprikatto** [godotengine/godot#78860]
### Godot version

4.0.3

### System information

Windows 10

### Issue description

So the issue is that when i assign a node to variable of class i created the intellisense is gone

![b](https://github.com/godotengine/godot/assets/72671804/bafd24af-94a4-45a9-9ec2-7505f4db524f)
it should show the init and input function as on the screenshot before
![c](https://github.com/godotengine/godot/assets/72671804/b1895b94-feea-4a51-8bdd-ed31deef509f)
this bug also appears when i assign node in ready function like this
![d](https://github.com/godotengine/godot/assets/72671804/b1a7f757-a35b-4fd6-9d96-eec666dc1c95)

### Steps to reproduce

1. Create a class with a class_name and function or variable inside
2. In any other script (that is attached to any node) create variable of class from first step (for example "var x: MyClassName" )
3. Create child node and attach to it script created in first step
4. In any function of parent script write "x." (and write at list first letter of the function inside this class) and it should show function or variable in a list
5. Now after "var x: MyClassName" add "= $node_name"
6. Now when you write "x." in script it won't show a function or variable you created

### Minimal reproduction project

N/A

**Comment by kaofelix** [comment]
I have a similar issue. In my case I have an autoload called `Globals` where I'm declaring a variable of type `Player`, which is a `class_name` I defined. 

![image](https://github.com/godotengine/godot/assets/223625/8622b701-a261-4f1f-bf14-710f45de2033)

When I try to use it with a typed variable, I don't get any kind of intellisense:

![image](https://github.com/godotengine/godot/assets/223625/98d69118-60bb-480d-8bd7-6d845b52921b)

However, if I cast  `Globals.player`, then I get intellisense:

![image](https://github.com/godotengine/godot/assets/223625/61ffb870-ed1e-4768-96ad-b88e54584028)

**Comment by HolonProduction** [comment]
@kaofelix your issue is tracked in #74888. Could you mark your comment as off topic?

The original issue consists of two problems:
- #73164 for global assignment
- I don't think there is a separate issue for the local assignment so we can keep this open
