### ISSUE TITLE
Justification flags properties of Label overriding the Scrollbar

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#78868]
### Godot version

4.1.rc.1

### System information

Windows 11

### Issue description

Text of Justification flags are overriding the scrollbar, It should be under.

![image](https://github.com/godotengine/godot/assets/84369217/88ee079e-e186-4955-a736-50d732a41edd)

The Justification flags are too much to the eye. I will create a proposal for it in case not there.

### Steps to reproduce

In any project open the settings of a Label. 
Reduce the size of property window if it is too large.

### Minimal reproduction project

N.A

**Comment by Calinou** [comment]
I don't think CheckBox text can wrap over multiple lines, or can it?
