### ISSUE TITLE
Area has one side overlighted or underlighted

### ISSUE THREAD

**Issue by pietru2004** [godotengine/godot#78879]
### Godot version

4.0 stable

### System information

Windows 10 Forward+

### Issue description

Whenever I try to make room or closed space one side is always with wrong light. it has too much light or too litle light on one side

Example 1
<details>
<Summary>How it looks on first side</Summary>
<img src="https://github.com/godotengine/godot/assets/51274570/e7a51dac-15ca-48b1-bb79-9795d124c5e9">
</details>
<details>
<Summary>How it looks on second side</Summary>
<img src="https://github.com/godotengine/godot/assets/51274570/cb5a87e6-7964-4c14-8369-a0f8e96089b8">
</details>

Example 2
<details>
<Summary>How it looks on first side</Summary>
<img src="https://github.com/godotengine/godot/assets/51274570/f92e570f-a810-4a6f-b9d4-d2eb838bbdc3">
</details>
<details>
<Summary>How it looks on second side</Summary>
<img src="https://github.com/godotengine/godot/assets/51274570/a94ed45a-4647-40af-bb85-8457a351417c">
</details>

Also when I enable SDFGI some of this is fixed, but not all. (my light sources are done using glow and emmision)

I found this in personal project, also Directional light is used in open areas so removing it is not option for me.

### Steps to reproduce

Have directional light in scene and in env disable ambient light source.

### Minimal reproduction project

[MRP_Light.zip](https://github.com/godotengine/godot/files/11917728/MRP_Light.zip)

**Comment by clayjohn** [comment]
Have you tried rotating your directional light to an angle you like better? 

The images look like the directional light is just facing one side of the room. In that case it is expected that the one side will light up more than the other. That's just how lighting works. 

In games, without global illumination, light doesn't bounce off of a surface. Whatever comes directly from the light source is what you get. You have to add in the bounced lighting yourself using tools like ambient light (which you disabled), VoxelGI, LightmapGI, or SDFGI

**Comment by pietru2004** [comment]
even when I enable SDFGI it feels like light travels throu mesh
(screens with SDFGI enabled)
![obraz](https://github.com/godotengine/godot/assets/51274570/2f39786c-b4aa-4bce-b2fd-81521955614c)
if you look at image you can say light is directed left forward, left side has more light then left
and the corridor is in this
![obraz](https://github.com/godotengine/godot/assets/51274570/c2ff88fe-02a3-4596-b8c5-07a2c42cc7e4)
and it should make shadow/remove any light going into building

this room would be fully dark
![obraz](https://github.com/godotengine/godot/assets/51274570/6f2ed688-bdac-42be-bc51-5e5ba36ef629)

**Comment by pietru2004** [comment]
also ambient and reflected light are disabled because of this
![obraz](https://github.com/godotengine/godot/assets/51274570/ca1677a0-de66-4b89-88cf-ea7dc1c2300e)

**Comment by Calinou** [comment]
Your scene's walls are infinitely thin:

![image](https://github.com/godotengine/godot/assets/180032/3525f13a-dbca-4873-b458-877074830fe6)

This causes problems when using global illumination techniques. You need to make your walls thicker in your 3D modeling software to prevent light leaking.

**Comment by pietru2004** [comment]
It is more like directional light does not care about walls

**Comment by pietru2004** [comment]
@Calinou if you look at this images you can see big cubes that shoulds block light from DirectionalLight3D (SUN) inside corridor
![obraz](https://github.com/godotengine/godot/assets/51274570/86a7a239-505d-4f84-9c7c-07f5d63ecc79)
Changing rotation
![obraz](https://github.com/godotengine/godot/assets/51274570/b9050712-6c95-4309-bdbf-9e5e733cdfc2)
Disabling SDFGI
![obraz](https://github.com/godotengine/godot/assets/51274570/4f3edc24-8a56-4528-a934-fb2efdfe4a94)


my understanding of DirectionalLight3D is that it can be SUN

**Comment by pietru2004** [comment]
erm seams I might have been blind and did not see ability to make it use shadows, but also depending on how I set culling it can sometimes just not generate shadow
![obraz](https://github.com/godotengine/godot/assets/51274570/a7f3e011-0a81-403c-9500-aafc61fd9170)
