### ISSUE TITLE
Editor: Node group flickering - Compatibility renderer

### ISSUE THREAD

**Issue by HaruYou27** [godotengine/godot#78875]
### Godot version

v4.0.3.stable.arch_linux

### System information

OpenGL API 4.2 (Core Profile) Mesa 23.1.3 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 2500 (IVB GT1)

### Issue description

Clicking on node group _panel_  and this happen

![20230630_21h43m27s_grim](https://github.com/godotengine/godot/assets/68549456/06c31ffd-c64e-4c68-9bf5-37cbc8c5e014)
![20230630_21h44m45s_grim](https://github.com/godotengine/godot/assets/68549456/b35f0b18-46e8-439a-b0a8-6607b7ef71b9)

### Steps to reproduce

1. Switch to Compatibility renderer.
2. Add some node group and click on it.

### Minimal reproduction project

Only happen in Compatibility renderer.

**Comment by capnm** [comment]
The same happens if you place the `FileSystem` editor on the right side.
![image](https://github.com/godotengine/godot/assets/4047289/58be4bc6-c38c-40d1-a50a-f2a47e33bd1d)

**Comment by HaruYou27** [comment]
This issue is no longer appears on V4.3.stable.
