### ISSUE TITLE
Import Hints are no Longer Processed if the Object Name ends with a Number

### ISSUE THREAD

**Issue by ATryder** [godotengine/godot#78881]
### Godot version

4.1 rc2

### System information

Manjaro GL-Compatibility

### Issue description

When using import hints, such as -col or -colonly, on object names Godot used to accept the hint even if it was followed by Blender's auto duplicate naming scheme such as .001 or .002. This is no longer the case, items name to the likes of "object-col.001" will not import with collision.

I noticed that, prior to 4.1, Godot would remove periods from imported object names. Object.001 would import as Object001, but now it would import as Object_001. Perhaps this change broke the import hint behavior.

### Steps to reproduce

Export a scene with object names using import hints, such as -col or -convcol, where some of the objects have '.001' or similar appended to the end of their names. Import the scene into Godot and create an inherited scene.

### Minimal reproduction project

[ImportHints.zip](https://github.com/godotengine/godot/files/11919131/ImportHints.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.1.rc 46424488e using https://github.com/godotengine/tps-demo. This does not occur on 4.0.3.stable.

**Comment by akien-mga** [comment]
> I bisected the regression to [223ce4f](https://github.com/godotengine/godot/commit/223ce4fcb958619d0f3c62e79a2b5846240e7ff3). cc @reduz

As pointed out in the OP, this commit made it so that `.` in node names gets replaced by `_` instead of simply removed.

So the logic here needs to be changed to take this into account:
https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/editor/import/resource_importer_scene.cpp#L313-L353

@godotengine/import

**Comment by fire** [comment]
I'm not able to rush fix this for a RC build. How to proceed?

**Comment by akien-mga** [comment]
I think this will have to be a known issue in 4.1 and we'll fix it in 4.1.1.
