### ISSUE TITLE
errors at godot 3.0 startup

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#7888]
getting these errors at the startup of godot (project manager starts correctly)

> ERROR: There are still MemoryPool allocs in use at exit!
>    At: core/dvector.cpp:71
> ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
>    At: core/class_db.cpp:279
> ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
>    At: tools/editor/editor_data.cpp:628
> ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
>    At: core/class_db.cpp:279
> ERROR: In Object of type 'VBoxContainer': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
>    At: core/object.cpp:1502
> ERROR: environment_set_tonemap: Condition ' !env ' is true.
>    At: drivers/gles3/rasterizer_scene_gles3.cpp:954
> ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
>    At: core/class_db.cpp:279

my opengl version is 3.3 pc specifications are (taken by CPU-Z & GPU-Z)
http://gpuz.techpowerup.com/17/02/25/z7a.png
[DESKTOP-PV7L1CS.txt](https://github.com/godotengine/godot/files/801437/DESKTOP-PV7L1CS.txt)

**Comment by bojidar-bg** [comment]
Can you retest with current master?

**Comment by karroffel** [comment]
possibly related to #8105

**Comment by Ahmed0425** [comment]
@bojidar-bg @karroffel 
That WAS the error on the startup but now it is #8174 & #8148

**Comment by Ahmed0425** [comment]
@karroffel Exactly
@bojidar-bg Tested and didn't work

**Comment by jedStevens** [comment]
Are you opening a previously created scenes with 3D meshes? I found my similar GL errors went away after creating a new project.

**Comment by Ahmed0425** [comment]
@jedStevens No ... I open a blank project

**Comment by Keetz** [comment]
Experiencing the same on Windows 8.1

ERROR: There are still MemoryPool allocs in use at exit!
At: core/dvector.cpp:68

At line 68 instead of 71 though

**Comment by Ahmed0425** [comment]
@Keetz the team mentioned this bug on twitter and will be fixed soon
try to resize godot window ... this worked for me

**Comment by akien-mga** [comment]
A long time has passed since, so assuming fixed in 3.0 beta 2 or later. Please comment if you still reproduce the exact same errors.

**Comment by Ahmed0425** [comment]
No, I do not reproduce this anymore

**Comment by tyoungjr** [comment]
I received this error with 3.1.1 stable branch when starting the 2d hdr example: 
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
Running: C:\Godot\godot\bin\3.1.1\godot.windows.tools.64.exe --path C:/Users/tyoun/src/Learning%20Godot/godot-demo-projects/2d/hdr --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 15328 --position 420,180
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:2095
ERROR: There are still MemoryPool allocs in use at exit!
   At: core\pool_vector.cpp:70
