### ISSUE TITLE
Scrollbar in output window does not work correctly

### ISSUE THREAD

**Issue by webskydavid** [godotengine/godot#78899]
### Godot version

4.1.rc2

### System information

MacOS 13.4.1

### Issue description

![image](https://github.com/godotengine/godot/assets/4489798/cf4d2074-7d8a-48d4-ba87-ba04d7f2dda1)
Scrollbar does not show when output values are provided after starting the game. Also, it does not scroll to the bottom automatically need to press the search button to show the scrollbar or any button that refreshes the output window.

### Steps to reproduce

1. Create a project
2. Run in _process function a `print()` with some values to output it in the `output window`
3. Turn the game on and off until the scrollbar stops appearing.

### Minimal reproduction project

[ScrollbarBug.zip](https://github.com/godotengine/godot/files/11924845/ScrollbarBug.zip)

**Comment by AThousandShips** [comment]
Seems related to #78434, which was supposed to be fixed

**Comment by bruvzg** [comment]
I can't reproduce it.

**Comment by AThousandShips** [comment]
Was reported by KoBeWi in rocketchat, though sporadic

**Comment by bitsawer** [comment]
Probably same as https://github.com/godotengine/godot/issues/78434 like AThousandShips commented. Interestingly, https://github.com/godotengine/godot/pull/78833 fixed the original issue for me and I can't reproduce this new one. Looks like the issue is sensitive to thread timing and computer speed, so it can be hard to track down.

**Comment by saierXP** [comment]
I can reproduce stably in the process on RC1, but it cannot be reproduced in the Ready function.The RC2 fixed it, I can't reproduce it.

After a lot of attempts, I found that these two combinations can reproduce the issue nearly 100%.

![Godot_v4 1-rc2_win64_uqr7kDPnpe](https://github.com/godotengine/godot/assets/45038185/aa7d38e1-bd4a-42f1-9e2f-e394adcbb922)

Then I also found that the output panel will reproduce steadily over a certain height, and if it is the minimum height, then about 20% of the time. 

<details><summary>System Details</summary>
<p>
Godot v4.1.rc2 - Windows 10.0.19044 - Vulkan (Compatibility) - AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.14051.5006) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)
</p>
</details>

**Comment by bruvzg** [comment]
> After a lot of attempts, I found that these two combinations can reproduce the issue nearly 100%.

I can reproduce it with the full height log, and I think I see what's wrong (I'll recheck all RTL processing code and open PR tomorrow).
