### ISSUE TITLE
XR Frames dip down to 60 when looking down on Oculus Quest 2

### ISSUE THREAD

**Issue by JD-The-65th** [godotengine/godot#78894]
### Godot version

4.1.rc2

### System information

Android (QuestOS v54, Vulkan Mobile)

### Issue description

When looking down at the floor, even in a basic environment, the frames will just dip down to around 60 for no reason.

### Steps to reproduce

Clone this repo https://github.com/JD-The-65th/cyberbreak

Use Android build preset to build for Oculus Quest 2 platform, push to Quest 2

Download OVR Metrics Tool ( from [sidequest](https://sidequestvr.com/app/17261/ovr-metrics-tool) or [official oculus site](https://developer.oculus.com/downloads/package/ovr-metrics-tool/) )

Open the game
Look Straight down for a few seconds
Look up and Observe the FPS Dip

### Minimal reproduction project

https://github.com/JD-The-65th/cyberbreak or https://gitlab.com/void-team/cyberbreak

**Comment by Calinou** [comment]
Looking down at the floor means that all pixels of the viewport have to render a shaded material, which is more expensive than looking at the sky.

**Comment by JD-The-65th** [comment]
Ah, well, that would make sense. Closing as a misunderstanding on my part.
