### ISSUE TITLE
how i can get all tile of a certain type?

### ISSUE THREAD

**Issue by nictaylr** [godotengine/godot#7891]
i have `TileMap` node, i want to get positions of all tiles of a certain type.

how can this be done in the go Dot engine:?

**Comment by plucian** [comment]
this is not a place for Q and A. 
try the official Q/A forum, I'm sure the question is already answered there.

[https://godotengine.org/qa/](https://godotengine.org/qa/)

**Comment by Hinsbart** [comment]
Yes, please open Issues here only for bug reports or other kinds of discussion about the development of the engine.
We have plenty of other communication channels if you want to get help with using the engine. See https://godotengine.org/community , thanks ^^

Now,  in regards to your question: you could do something like this I guess
```
func get_tiles_by_type(p_type):
	var ret = []
	var tile_id = get_tileset().find_tile_by_name(p_type)
	for cell in get_used_cells():
		if get_cellv(cell) == tile_id:
			ret.append(cell)
	return ret
```
