### ISSUE TITLE
Exception when sending code completion message for NodePath via GodotTools.IdeMessaging (C#)

### ISSUE THREAD

**Issue by jsbeckr** [godotengine/godot#78913]
### Godot version

4.1.rc2

### System information

Window 11/MacOS

### Issue description

We integrated `GodotTools.IdeMessaging` into the Rider Godot-Support plugin to get auto completion for `NodePath` and input actions to get more feature parity with VS Code and the Godot Editor itself (https://github.com/JetBrains/godot-support/pull/102). We tested against 4.0.3 and everything works fine. But with 4.1.rc2 we get an exception thrown in the Godot Editor:

```
Caller thread can't call this function in this node (/root/@EditorNode@17664/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@CanvasItemEditor@10090/@VSplitContainer@9915/@HSplitContainer@9917/@HSplitContainer@9919/@Control@9920/@SubViewportContainer@9921/@SubViewport@9922/player). Use call_deferred() or call_thread_group() instead.
```

I'm not really sure what's happening here but it seems to be a problem in the editor? 

### Steps to reproduce

- use Godot 4.1.rc2
- create new C# project
- build and run godot-support plugin
  - (in rider directory) `gradlew runIde`
- open Godot project in Rider
- try to get Code Completion for `GetNode("")`

### Minimal reproduction project

An Empty project with a single, empty C# script is enough.

**Comment by jsbeckr** [comment]
https://github.com/JetBrains/godot-support/issues/103

**Comment by akien-mga** [comment]
CC @RedworkDE @raulsntos @neikeq

**Comment by RedworkDE** [comment]
Random patch that might impact performance for the other completion types, but I don't think there is an easy way of returning data from a call_deferred in core, also this was probably one of the it worked *most* of the time cases that these guards exist to prevent.
Warning: untested
```
diff --git a/modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs b/modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs
index 62db6e3af5f..672e0b6b0c3 100644
--- a/modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs
+++ b/modules/mono/editor/GodotTools/GodotTools/Ides/MessagingServer.cs
@@ -379,16 +379,22 @@ namespace GodotTools.Ides
                 return Task.FromResult<Response>(new ReloadScriptsResponse());
             }
 
-            private static async Task<Response> HandleCodeCompletionRequest(CodeCompletionRequest request)
+            private static Task<Response> HandleCodeCompletionRequest(CodeCompletionRequest request)
             {
                 // This is needed if the "resource path" part of the path is case insensitive.
                 // However, it doesn't fix resource loading if the rest of the path is also case insensitive.
                 string scriptFileLocalized = FsPathUtils.LocalizePathWithCaseChecked(request.ScriptFile);
 
-                var response = new CodeCompletionResponse { Kind = request.Kind, ScriptFile = request.ScriptFile };
-                response.Suggestions = await Task.Run(() =>
-                    Internal.CodeCompletionRequest(response.Kind, scriptFileLocalized ?? request.ScriptFile));
-                return response;
+                TaskCompletionSource<Response> tcs = new TaskCompletionSource<Response>();
+
+                Godot.Callable.From(() =>
+                {
+                    var response = new CodeCompletionResponse { Kind = request.Kind, ScriptFile = request.ScriptFile };
+                    response.Suggestions = Internal.CodeCompletionRequest(response.Kind, scriptFileLocalized ?? request.ScriptFile);
+                    tcs.SetResult(response);
+                }).CallDeferred();
+
+                return tcs.Task;
             }
         }
     }
```

**Comment by raulsntos** [comment]
So is the `Task.Run` the problem here? If so, can't we try to start the `Task` with the current synchronization context (which I assume is `GodotSynchronizationContext`)?

```csharp
var response = new CodeCompletionResponse { Kind = request.Kind, ScriptFile = request.ScriptFile };
response.Suggestions = await Task.Factory.StartNew(() =>
    Internal.CodeCompletionRequest(response.Kind, scriptFileLocalized ?? request.ScriptFile),
    CancellationToken.None,
    TaskCreationOptions.None,
    TaskScheduler.FromCurrentSynchronizationContext());
return response;
```

Alternatively, I wonder if we could fix this on the C++ code instead (`gdmono::get_code_completion`). Adding some wait that synchronizes with the main thread before the code that iterates the scene (which seems to be the part that needs to be done in the main thread):

https://github.com/godotengine/godot/blob/46424488edc341b65467ee7fd3ac423e4d49ad34/modules/mono/editor/code_completion.cpp#L134-L139

Also, since this code completion is not C# related, it may be possible to use the GDScript LSP for this.

**Comment by neikeq** [comment]
> So is the `Task.Run` the problem here? If so, can't we try to start the `Task` with the current synchronization context (which I assume is `GodotSynchronizationContext`)?

Hmm, perhaps that's better than `ToSignal`. Both would execute on the next frame though, perhaps we should use the MessageQueue instead (an awaitable `CallDeferred`).
