### ISSUE TITLE
GDScript documentation comments: description tooltips are omitted when applied to @export variables with multiline arguments, as well as @export_category

### ISSUE THREAD

**Issue by Yerdun** [godotengine/godot#78934]
### Godot version

4.1.rc2.mono.official

### System information

Godot v4.1.rc2.mono - EndeavourOS #1 SMP PREEMPT_DYNAMIC Thu, 11 May 2023 16:40:42 +0000 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz (4 Threads)

### Issue description

When using [GDScript documentation comments](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html) to create description tooltips for [@export variables](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html), they do not show up in the editor if:

- The export variable requires arguments (eg. [@export_enum](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html#exporting-enums)), and the arguments are declared across more than 2 lines. [(recommended by GDScript style guide)](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#format-multiline-statements-for-readability)
- A description is applied to an [@export_category](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-category). 
  - This error also applies to all variables within the category

To illustrate, here are some screenshots from the included minimal reproduction project.

![working](https://github.com/godotengine/godot/assets/56048350/5fc45659-7a4d-4744-a7cd-1647497a0c97)

![nonworking_multiline](https://github.com/godotengine/godot/assets/56048350/8c2a1845-ca48-4484-a637-0af3d6b5582d)

![nonworking_category](https://github.com/godotengine/godot/assets/56048350/84ada88f-8a7b-49e7-9a6e-4cb188cc9dae)

### Steps to reproduce

Copy-paste this code into a new node's script. A minimal reproduction project with all this prepared is included below for convenience.

```
extends Node


## This shows up in the editor.
@export_enum("example1", "example2",) var good_enum


## [i]This shows up in the editor, but goes against recommended practices.[/i]
@export_enum(
	"example1", "example2",) var poor_practice_multiline


## THIS DOES NOT SHOW UP IN THE EDITOR.
@export_enum(
	"example1",
	"example2",
) var bad_enum

## THIS DOES NOT SHOW UP IN THE EDITOR.
@export_category("Categories truncate comments")

## THIS DOES NOT SHOW UP IN THE EDITOR.
@export var bad: int
```

### Minimal reproduction project

[tooltip-bug.zip](https://github.com/godotengine/godot/files/11928865/tooltip-bug.zip)

**Comment by akien-mga** [comment]
Confirmed reproducible with the MRP.

**Comment by LinqLover** [comment]
Description tooltips are also missing when the variable is exported by overriding `_get_property_list` instead of using `@export`.

**Comment by louis-vinchon** [comment]
While it apparently has been fixed when exactly one `@export_category()` is used, it is still broken when multiple are in use; all descriptions disappear as soon as you have two.

**Comment by TechnoLukas** [comment]
@louis-vinchon It also depends on placement of `@export_category()`. I described it here => https://github.com/godotengine/godot/issues/64432#issuecomment-1941676792

**Comment by dalexeev** [comment]
@louis-vinchon See #88318. For the future, feel free to open a new issue instead of commenting on a closed old one.
