### ISSUE TITLE
Touch buttons' graphics fail to convert to Godot 4

### ISSUE THREAD

**Issue by Koopa1018** [godotengine/godot#78930]
### Godot version

v4.1.beta1.official [828ec2c5d]

### System information

Godot v4.1.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 30.0.14.7247) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Converting a project from Godot 3.5 to Godot 4.1 fails to convert the texture references on TouchScreenButton nodes. Before, my TouchScreenButton scene has a Normal and a Pressed texture assigned; after, the scene has no textures assigned!

This seems to be because the converter fails to update the TouchScreenButton node's `normal` and `pressed` properties to `texture_normal` and `texture_pressed`.

Expected behavior is, of course, that the textures convert properly.

### Steps to reproduce

1. Open repro project in Godot 3.5.*. Observe the graphics on the button in `TouchScreenButton.tscn`.
2. Convert the project to Godot 4.1.*. Observe the lack of graphics on the same button.

### Minimal reproduction project

[GD4 Touch Button Convert.zip](https://github.com/godotengine/godot/files/11928549/GD4.Touch.Button.Convert.zip)

**Comment by AThousandShips** [comment]
This is a limitation of the converter, it cannot detect context so if can't convert general names like this because it cannot know it's attached to a specific type

Not a big but a limitation to the feature
