### ISSUE TITLE
Unable to initialize Vulkan video driver

### ISSUE THREAD

**Issue by TATAPNHOB** [godotengine/godot#78942]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 - Vulkan (Forward+) - NVIDIA GTX 1650 Ti, iGPU: AMD Radeon(TM) Graphics

### Issue description

I can create a project using Forward+, but not open/edit it. Every time I open it, an error pops up:
![image](https://github.com/godotengine/godot/assets/78953252/7526fc33-0651-4530-9c50-cdc9ce487d52)
I tried updating to the latest drivers, switching from Studio Drivers to Game Ready ones, disabling integrated graphics in the Device Manager, but no effect (in the last strive, I couldn't even open the Project Manager as it required OpenGL which I did not have, for some reason?). 
Compatibility mode works fine, but I do want to work out this issue.

### Steps to reproduce

1. Have problems like I do.
2. Open Project Manager.
3. Create or load a project, then open it.
4. Error pops up, Godot closes itself.

### Minimal reproduction project

The project can be as simple as the first created blank slate. It still wouldn't load on my system...

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/57708.
