### ISSUE TITLE
_process is still called after set_process(false) if done early

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7894]
Tested on Godot 2.1.2
Windows 10 64 bits

If `set_pocess(false)` is called on a node before its  `_process()` is called, it will still be called for the current frame. I expected it not to be called.
A few things in my game rely on _process() being turned on and off, and one of them had an error because the state of the script wasn't expecting _process to be called where it wasn't meant to. The fix in my scripts would be to add a defensive `if is_processing()` in `_process`, though it doesn't look right.

Should this be considered a bug? Is it hard to change?

Example project:
[ProcessFalse.zip](https://github.com/godotengine/godot/files/802191/ProcessFalse.zip)

Note: in that example you can also tweak the script so it makes things like that fail:
```gdscript
func _process(delta):
    assert(is_processing()) # will fail
```

**Comment by jjay** [comment]
Same thing for me =/

**Comment by reduz** [comment]
We could add an extra check i guess

**Comment by xag67** [comment]
Has it been fixed ?

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.
