### ISSUE TITLE
Integer division warning annotation sometimes fails

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#78957]
### Godot version

4.0.3.stable, 4.1.rc2

### System information

Linux (Pop!_OS 20.04)

### Issue description

The annotation `@warning_ignore("integer_division")` sometimes fails to suppress warning messages.

The issue seems to occur in compound expressions.

I found two similar existing issues, but the problems they report are somewhat different, so I'm posting this new issue.
#34623
#42966

This is a regression. The problem does not occur in 3.5.2.stable, when the corresponding warning-ignore annotation is used.

### Steps to reproduce

Import and run the attached MRP. The project was created in 4.1.rc2. Observe that there are warning messages, even though the annotations are present in the script.

### Minimal reproduction project

[IntegerDivisionWarningBug.zip](https://github.com/godotengine/godot/files/11930165/IntegerDivisionWarningBug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/56592, as the integer division warning not working above `if`/`for` blocks is already tracked there.
