### ISSUE TITLE
Passing const string into function gives error saying its not a const string

### ISSUE THREAD

**Issue by LeeWannacott** [godotengine/godot#78978]
### Godot version

v4.0.3.stable.official [5222a99f5] via Steam

### System information

Pop!_OS 22.04 LTS

### Issue description

I have preloads that take const strings and I decided to do a refactor that passes these const strings into the function set_pickup_props() but the linter is saying that "Preloaded path must be a constant string" which makes no sense because it worked in the _ready function (the commented out code works) the only thing that is different is I'm calling it from set_pickup_props() which seems to print out the string correctly and then if I do typeof it gives "4" which I don't really understand unless its like an enum for something (it prints the same before passing it into the function).

Sorry, I'm new to godot so this might not be a bug and just me being dumb? 

![image](https://github.com/godotengine/godot/assets/49783296/021260d2-5ae4-4a5f-83e4-0bb86ed54a54)

### Steps to reproduce

Pass const strings into a function (in this case atlas_path param of set_pickup_props()); then it ceases to be a const string  :shrug: 
``` gdscript

extends Area2D

@onready var resource_type = $"."
@onready var resource_image = $resourceImage
@onready var resource_gathered_text_image = $RichTextLabel/ResourceGatheredTextImage
@onready var rich_text_label = $RichTextLabel
const PICKUP_TEXT_SPACE = 11
const pickups_stick_atlas = "res://item/pickups/pickups_sticks_atlas.tres"
const pickups_stone_atlas = "res://item/pickups/pickups_stones_atlas.tres"

func set_pickup_props(atlas_path,pickup_text,spacing):
#    print(typeof(atlas_path), atlas_path) # prints 4 res://item/pickups/pickups_stones_atlas.tres
    resource_image.texture = preload(atlas_path)
    resource_gathered_text_image.texture = preload(atlas_path)
    rich_text_label.text = "+"+pickup_text.lpad(PICKUP_TEXT_SPACE," ")

# Called when the node enters the scene tree for the first time.
func _ready():
  if resource_type.name.contains("Stones"):
#    print("Stones")
#    resource_image.texture = preload(pickups_stone_atlas)
#    resource_gathered_text_image.texture = preload(pickups_stone_atlas)
#    rich_text_label.text = "+"+"Stone".lpad(PICKUP_TEXT_SPACE," ")
    set_pickup_props(pickups_stone_atlas,"Stone",PICKUP_TEXT_SPACE)
  elif resource_type.name.contains("Sticks"):
#    print("Sticks")
#    resource_image.texture = preload(pickups_stick_atlas)
#    resource_gathered_text_image.texture = preload(pickups_stick_atlas)
#    rich_text_label.text = "+"+"Stick".lpad(PICKUP_TEXT_SPACE," ")
    set_pickup_props(pickups_stick_atlas,"Stick",PICKUP_TEXT_SPACE)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
  pass

func _on_body_entered(body):
  var current_inventory = preload("res://inventory/resource_inventory.tres")
  print("body enter: ",resource_type.name)
  if resource_type.name.contains("Stone"):
          Signals.Gather_resource.emit(current_inventory.slot_datas[0], 0, resource_type)
  elif resource_type.name.contains("Stick"):
          Signals.Gather_resource.emit(current_inventory.slot_datas[1], 1, resource_type)
  self.queue_free()

func _on_picked():
#  print("has picked")
  pass # Replace with function body.
```

### Minimal reproduction project

I can put one together if it is actually a bug.

**Comment by AThousandShips** [comment]
Function arguments are never const, regardless of what called with, this function could be called from anywhere

**Comment by LeeWannacott** [comment]
> Function arguments are never const, regardless of what called with, this function could be called from anywhere
> 
> What you are trying to do isn't possible, and wouldn't be possible in other languages like C++

I don't know C++

@AThousandShips  Oh okay thanks!, Shall I close this issue then?

**Comment by AThousandShips** [comment]
I was merely giving an example :)

As this isn't a bug, and the error should be clear I'd say there's nothing more needed here

**Comment by LeeWannacott** [comment]
> I was merely giving an example :)

Yep got it; I'll try it out in other languages. :)

> As this isn't a bug, and the error should be clear I'd say there's nothing more needed here

Sweet thank you!

**Comment by LeeWannacott** [comment]
``` gdscript
func set_pickup_props(preloaded_atlas,pickup_text,spacing):
    resource_image.texture = preloaded_atlas
    resource_gathered_text_image.texture = preloaded_atlas
    rich_text_label.text = "+"+pickup_text.lpad(PICKUP_TEXT_SPACE," ")

set_pickup_props(preload(pickup_atlases.stone),"Stone",PICKUP_TEXT_SPACE)
```
For anyone's reference I ended up passing the preload in instead...
