### ISSUE TITLE
Indentation handled by number of characters, not indentation width

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#7898]
The following GDScript code is valid and accepted by the parser (emphasis is on the indentation):
```
										extends Tabs

func _ready():
	var x = 0
	if 1 == 1:
	 x = 10
		x = 20
  x = 30
 x = 40
	x = 50
```

This is impossible to understand without revealing the whitespace characters used:
```
[-TAB-][-TAB-][-TAB-][-TAB-][-TAB-][-TAB-][-TAB-][-TAB-][-TAB-][-TAB-]extends Tabs

func _ready():
[-TAB-]var x = 0
[-TAB-]if 1 == 1:
[-TAB-][SPACE]x = 10
[-TAB-][-TAB-]x = 20
[SPACE][SPACE]x = 30
[SPACE]x = 40
[-TAB-]x = 50
```

Obviously, the GDScript parser only handles indentation by counting the characters used to indent, not the visual width of them like Python does.
Then again it seems to ignore whitespace at the start of a file.

I think it would be better to handle it like Python, defaulting tabs to a specific number of equivalent spaces, and then using the resulting indentation width rather than character count. S. http://www.secnetix.de/olli/Python/block_indentation.hawk section "How does the compiler parse the indentation?" about the Python indentation implementation which I would recommend for GDScript aswell.

On a side note, multiple instances of this parser error popped up when opening such an indented file (though this was in a 2.2 build):
```
ERROR: GDParser::_reduce_expression: Method/Function Failed, returning: op
   At: modules\gdscript\gd_parser.cpp:1540
```

**Comment by Skaruts** [comment]
This is a bit of a bummer. Not that I like using spaces, but I started using them to make code look better on Github (because it, for some unfathomable reason, uses 8-wide tabs, as we all know). 

I noticed this while trying to line up these lines:
```
#..|...|...|...|...|...|x     <-- 'x' marks the spot
func pause():            paused = true
func unpause():            paused = false
func toggle_pause():    paused = !paused   # this one just so happens to be there
```

**Comment by Calinou** [comment]
> Not that I like using spaces, but I started using them to make code look better on Github (because it, for some unfathomable reason, uses 8-wide tabs, as we all know).

You can use the [Refined GitHub](https://github.com/sindresorhus/refined-github) add-on to decrease the tab width. Alternatively, you can use one of many userstyles, or even write your own:

```css
* {
  tab-size: 4;
}
```

**Comment by akien-mga** [comment]
> I think it would be better to handle it like Python, defaulting tabs to a specific number of equivalent spaces, and then using the resulting indentation width rather than character count. 

Note that AFAIK, while Python 2 worked this way, Python 3 just yells at you if you mix tabs and spaces. I think we should do the same.

Mixing indentation styles and relying on an arbitrary visual width for tabs is really asking for trouble.

**Comment by Skaruts** [comment]
@akien-mga I agree with your conclusion on that. But we're still left with the issue of, when using (exclusively) spaces, the tab key always adds 4 spaces instead of lining things up (in 3.1.1 stable). 

I was about to open an issue about that, but then i didn't because I interpreted this one as being about that.

**Comment by akien-mga** [comment]
That's a different issue, this one was about the GDScript language parser, what you ask for is an IDE feature.

**Comment by Skaruts** [comment]
Should I open one then?

**Comment by akien-mga** [comment]
If there isn't an existing issue about it, sure.

**Comment by Skaruts** [comment]
Well, I found #28811 from #28724, so I guess it's even already fixed!
