### ISSUE TITLE
Touchpad input detected as joypad input

### ISSUE THREAD

**Issue by HastagGuigui** [godotengine/godot#78985]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Linux (Zorin OS 16.1)

### Issue description

Essentially, moving the mouse/clicking/scrolling using a touchpad is detected as Joypad input. Unsure if this is the intended behavior or not because this is causing control to be detected even when the window isn't focused. This can, for example, cause buttons to be pressed when simply moving the mouse.

### Steps to reproduce

- Have a laptop with a touchpad, and Linux installed on it. (This doesn't seem to occur on Windows.)
- Go to Project > Project Settings > Controls
- Add a new event to any action
- Move the mouse using a touchpad, this will cause the "Joypad axis" options to be automatically selected, and rapidly switch between multiple joypad axis options depending on mouse movement.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/59250.
