### ISSUE TITLE
can no assign extern class var  if var is static type `Array[type]`

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#78984]
### Godot version

v4.1.rc.custom_build [e044e13d5]

### System information

debian stable

### Issue description

test.gd
```gdscript
@tool
extends EditorScript

var arr1:Array[int]

func _run():
	arr1=[0]
	var ex_arr=ExArray.new()
	ex_arr.arr1=[0]

````
ex_array.gd
```gdscript
class_name ExArray

var arr1:Array[int]=[0]
```

When extern class var is static type `Array[type]`, can not assign value

err info
```
 res://test.gd:9 - Invalid set index 'arr1' (on base: 'RefCounted (ExArray)') with value of type 'Array'.
```

### Steps to reproduce

just run test.gd

### Minimal reproduction project

[ex_array_bug.zip](https://github.com/godotengine/godot/files/11937732/ex_array_bug.zip)

**Comment by AThousandShips** [comment]
You can't assign a typed array with a non-typed array here I'd say

**Comment by dalexeev** [comment]
Use [`Array.assign()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-assign) method:

```gdscript
ex_arr.arr1.assign([0])
```

When a typed array is declared, the initializer array literal is automatically typed. We could do the same for assignment if the type of the left value is known, but that would be even more confusing since we can't do the same for an untyped assignment.

**Comment by ywaby** [comment]
> You can't assign a typed array with a non-typed array here I'd say
> 
>     * See: [Array `map`/`filter` fail with typed-array variables and functions #72566](https://github.com/godotengine/godot/issues/72566)

Ok, but why `arr1=[0]` can pass?

**Comment by dalexeev** [comment]
> Ok, but why `arr1=[0]` can pass?

Use a static type, then this will work:

```gdscript
var ex_arr := ExArray.new()
#          ^
ex_arr.arr1 = [0] # Will work.
```

**Comment by dalexeev** [comment]
* See also #71336. When/if the PR is merged you will be able to:

```gdscript
ex_arr.arr1 = Array[int]([0])
```

**Comment by kleonc** [comment]
Also an array literal can already be casted using `as`:
```gdscript
var ex_arr = ExArray.new()
ex_arr.arr1 = [0] as Array[int]
```

**Comment by ywaby** [comment]
Thanks for answering, I close this issue.
