### ISSUE TITLE
Simple scene with Control node eating up CPU

### ISSUE THREAD

**Issue by perry-blueberry** [godotengine/godot#78999]
### Godot version

4.0.3.stable.official

### System information

Ubuntu 22.04 Compatibility/Forward+

### Issue description

I've created a simple scene with just a Control node and it's eating up most of my CPU on a Ryzen 7 3700x. In comparison the Godot editor eats up ~50% (seen in `top`) while the game is running whereas the game eats up to ~1000%.

### Steps to reproduce

1. Create a new scene.
2. Add a Control node.
3. Run the scene.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is expected if you don't have low processor mode enabled in the project settings, as the project redraws continuously until V-Sync is reached.

**Comment by akien-mga** [comment]
> This is expected if you don't have low processor mode enabled in the project settings, as the project redraws continuously until V-Sync is reached.

This sounds more like V-Sync being disabled or not working. With V-Sync on it shouldn't use 1000% CPU, running a trivial project at 60 or even 240 FPS wouldn't use all CPU.

**Comment by Calinou** [comment]
@perry-blueberry What's the refresh rate of your monitor?

**Comment by perry-blueberry** [comment]
> @perry-blueberry What's the refresh rate of your monitor? Can you enable **Print FPS** in the project settings before running the project, so you can check the framerate the project runs at (or use **Debugger > Monitors** and tick the **FPS** checkbox)?
> 
> Also, what graphics card model are you using? Are you on a X11 or Wayland session (use `echo $XDG_SESSION_TYPE` to know)?

The refresh rate is 144Hz. FPS looks to be over 200. I have an RTX 3070. Using Wayland (to my surprise).

**Comment by Calinou** [comment]
> Using Wayland (to my surprise).

Try switching to a X11 session, as Godot has many issues under XWayland.

**Comment by perry-blueberry** [comment]
With Low Processor Mode the consumption low. By capping FPS to 60 it also reduces the CPU usage closer to "expected" levels.

**Comment by perry-blueberry** [comment]
> Try switching to a X11 session, as Godot has many issues under XWayland. This is doubly the case on NVIDIA drivers which have poor Wayland support.

That actually did not help (and turned my screen green as well for some odd reason).

**Comment by perry-blueberry** [comment]
I believe it might have been an issue with the graphics driver which I could only solve by doing `sudo ubuntu-drivers install` and then using X11. After that it runs much better. Thanks for the input!
