### ISSUE TITLE
Is there a way to change the text alignment to center using a RichTextLabel?

### ISSUE THREAD

**Issue by scovelme** [godotengine/godot#7899]
I'm using Godot Engine 2.1

**Comment by akien-mga** [comment]
Yes, see [RichTextLabel docs](http://docs.godotengine.org/en/stable/classes/class_richtextlabel.html) and [BBCode docs](http://docs.godotengine.org/en/stable/reference/bbcode_in_richtextlabel.html).

Also, you should not be asking such support questions here, this tracker is for bugs in the engine, not user support. The [Godot Q&A](https://godotengine.org/qa) would be the goto place for your question.
