### ISSUE TITLE
Darken the editor window if a pop-up window is open

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#7900]
To make the editor more polished, it would be a good idea to darken the editor window if a pop-up window is open, such as a file selection dialog or a progress action, especially since you can't interact with the background in this case (if you do, you usually close the pop-up window if it's closeable). Of course, it shouldn't be too dark to keep the background readable, a 50% darkening sounds good.

Similar behavior can be observed in eg. KDE.

**Comment by RayKoopa** [comment]
And please make it so that clicking the background does not close a window and discards all your hard-earned changes you made in the popup.

I *might* check on that anway when I implement resizable setting dialogs and storing their positions.
