### ISSUE TITLE
Callable.bind/bindv is not working

### ISSUE THREAD

**Issue by matheusmdx** [godotengine/godot#79008]
### Godot version

v4.1.rc2.official [46424488e]

### System information

Godot v4.1.rc2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 3 3200G with Radeon Vega Graphics (4 Threads)

### Issue description

The bind/bindv function is not binding the args in the callable, if you use get_bound_arguments_count() the result will be always zero

### Steps to reproduce

Just run the minimal project.

### Minimal reproduction project

```
extends Node2D

func _ready() -> void:
	var callable = _test
	callable.bind("Godot")
	#callable.bindv(["Godot"])
	print("Callable has %s args bounded" %[callable.get_bound_arguments_count()])
	callable.call()


func _test(a = "Test") -> void:
	print("Called with: ", a)

```

**Comment by Rindbee** [comment]
`bind()`/`bindv()` does not modify the original callable but a copy of it.
```GDScript
callable = callable.bind("Godot") # References the new copy.
```

**Comment by AThousandShips** [comment]
See the [documentation](https://docs.godotengine.org/en/stable/classes/class_callable.html#method-descriptions)

**Comment by matheusmdx** [comment]
> Please see the [documentation](https://docs.godotengine.org/en/stable/classes/class_callable.html#method-descriptions):
> 
> > Returns a copy of this Callable with one or more arguments bound

Sorry, totally my mistake here, i'll close right now.
