### ISSUE TITLE
Revert button don't restore the property to the original value

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#7901]
_bugsquad edit: according to https://github.com/godotengine/godot/issues/7901#issuecomment-380202514 the issue is still reproducible in https://github.com/godotengine/godot/commit/a7f6e093d84189f3da0d52cd095107be6bab5485_

----

**Operating system or device - Godot version:**
Xubuntu 16.04.2 LTS, Godot version: master 55ce8e6c, 2.1.2_stable, 

**Issue description:**

When editing the instance and change value, revert button don't restore property to the original value.
Works correct when a instance scene saved on a godot 1.1.

**Steps to reproduce:**
1) Create scene A with one node.
2) Create scene B with one node.
3) Instantiate a scene B to A.
4) Change a value and try the revert button.

![revert_bug](https://cloud.githubusercontent.com/assets/1049442/23376757/8e2bd538-fd57-11e6-9d27-ec42e75c66b9.gif)

**Link to minimal example project:**
[revert_bug_project.zip](https://github.com/godotengine/godot/files/804819/revert_bug_project.zip)

**Comment by bojidar-bg** [comment]
Does deselecting and reselecting the node workaround the issue?

**Comment by allkhor** [comment]
Selection and reselection the node does not solve this issue.

**Comment by allkhor** [comment]
Reproducible in stable 3.0.2, reproducible in master a7f6e09.

**Comment by allkhor** [comment]
Tested on master 5a5614e
Stable 3.0.6 8314054 
Demo projects:
[3.1.zip](https://github.com/godotengine/godot/files/2240261/3.1.zip)
[3.0.zip](https://github.com/godotengine/godot/files/2240262/3.0.zip)

Try to revert a value from the button:
Text value reverted to original instance.
Icon don't reverted.
Flat reverted to original instance.
Clip text not reverted.
And many other properties can't reverted to original value.

**Comment by DualMatrix** [comment]
Interesting, exported variables can't be reverted but the regular variables can't be reverted.

**Comment by akien-mga** [comment]
Tested the 3.1 project in the current master branch and it appears to be fixed by 6cc116d. The revert button properly reverts all properties to that of the base scene.
