### ISSUE TITLE
Pico Neo 3: The Pico Interaction Profile is not used

### ISSUE THREAD

**Issue by Wesmer** [godotengine/godot#79019]
### Godot version

v4.0.2.stable.official [7a0977ce2] and v4.0.3.stable.official [5222a99f5]

### System information

Pico Neo 3 Pro Eye; PUI Version 4.8.19; Android 10

### Issue description

When trying to use the controllers, only the menu button and trigger works because the Simple controller profile is used. The system refuses to use the Pico profile (or any other profile). Also creating a custom map and/or deleting the Simple Controller profile did not work.

I expected the Pico Profile to work on a Pico Neo 3.

For clarification, this is the controller I am using: https://sdk.picovr.com/docs/NativeSDK/en/chapter_five.html#id4

### Steps to reproduce

- Just create a Project as shown here: https://www.youtube.com/watch?v=ZckQ-6ocHrI 
- Add a script to the XRController3D node that outputs the signals. Export and start the project.

### Minimal reproduction project

[pico_.zip](https://github.com/godotengine/godot/files/11949055/pico_.zip)

Note: I have also deleted the Android folder.

**Comment by BastiaanOlij** [comment]
I'm planning to address this soon, PICO added an interaction profile specific to the neo3. It however requires OpenXR 1.0.27 which we're switching over to after 4.1 is released.

**Comment by BastiaanOlij** [comment]
OK now that we can merge stuff into 4.2 and we've updated to OpenXR 1.0.28 (this was available in 1.0.27 but we skipped that) this should be corrected. It would be good if this can be tested.
