### ISSUE TITLE
Crash when setting AnimationTree active with circular dependency (infinite loop)

### ISSUE THREAD

**Issue by Kantrull** [godotengine/godot#79012]
### Godot version

v4.1.rc2.official [46424488e]

### System information

Godot v4.1.rc2 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

When setting the AnimationTree to active, Godot crashes.

### Steps to reproduce

https://github.com/godotengine/godot/assets/46705245/dbe5eb81-1357-43e8-ac80-a4eb97eea9fc

### Minimal reproduction project

[Crash.zip](https://github.com/godotengine/godot/files/11945826/Crash.zip)

**Comment by Kantrull** [comment]
Im closing the issue, problem was that all the transitions were set to auto and it was in an infinite loop.

**Comment by akien-mga** [comment]
We should keep it open as it's still a bug which should aim to prevent, by detecting this kind of circular dependency and break out of it.

**Comment by Flynsarmy** [comment]
It's extremely easy to fall into this issue as auto progression is the default behaviour. So if the user makes all the connections with the intention of then configuring them, it's already too late.

**Comment by TokageItLab** [comment]
I remember adding a check to break out of this kind of infinite loop, but some check case may be not working.
