### ISSUE TITLE
Strange a button behaviour after commit f67881b

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#7902]
**Operating system or device - Godot version:**
Xubuntu 16.04.2 LTS x64, Godot version: 2.1.2 e9e5aff

**Issue description:**

Button work incorrect after f67881b
![btn_bug](https://cloud.githubusercontent.com/assets/1049442/23377134/f9008830-fd58-11e6-80c5-7530c78794f0.gif)

**Comment by bojidar-bg** [comment]
Ping @volzhs (no, not a sneaky ping, I guess)

**Comment by volzhs** [comment]
I guess that pr could make this bug.
I unfortunately can't check it right now. will check soon.

**Comment by RandomShaper** [comment]
I'm working with f67881bada003e4cd6341809d101642e2886c1e6 reverted and I'm still getting the same behavior (or almost, I can't tell for sure).

@allkhor, if you build Godot with that commit reverted, does it work well for you?

**Comment by allkhor** [comment]
@RandomShaper  without that commit everything works as it should. Regardless of the selected layer or the node properties, any buttons has pressed correctly.

**Comment by volzhs** [comment]
@RandomShaper @allkhor I'm looking into it now. I think I found solution and am testing it.

**Comment by volzhs** [comment]
hm. it's still partially solved.
Problem is all TreeItem nodes are reconstructed after editing node name.
So, `cache.click_item` refers wrong address.
I'm still working on it.

**Comment by RandomShaper** [comment]
Cheer up! :)

**Comment by allkhor** [comment]
Thank you! Now it works as it should!
