### ISSUE TITLE
`sign` returns `1` for NAN

### ISSUE THREAD

**Issue by lilizoey** [godotengine/godot#79036]
### Godot version

4.1.rc3

### System information

Linux 5.10.181-2-MANJARO

### Issue description

`sign(NAN)` and `signf(NAN)` both return `1`. But this doesn't seem right, as `NAN > 0` is false (as all other `NAN` comparison are). These should really return `NAN` not `1`.

### Steps to reproduce

run 
```gdscript
print(sign(NAN), " ", signf(NAN))
```
output is: 
`1 1`

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/core/typedefs.h#L110-L113

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/core/variant/variant_utility.cpp#L243-L275

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/core/variant/variant_utility.cpp#L277-L283

I'm not sure what behavior should be, it's probably implemented this way for performance. But perhaps we could add checks to the `@GlobalScope` utility functions without touching the core `SIGN()` function?

For comparison, in JavaScript:

```javascript
Math.sign(NaN) // NaN
```
