### ISSUE TITLE
RigidBody3D Cylinder gets caught on diagonal mesh seams when traversing slopes.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#79033]
### Godot version

godot 4.1 rc3

### System information

windows 10

### Issue description

Here is what it looks like when moving cylinders right and left on the slope. Notice how they get shifted when crossing the diagonal seams of the mesh (each square consists of two triangles). The cylinders get caught on the seams sporadically.
![slopemeshbug](https://github.com/godotengine/godot/assets/10412778/de73f03d-77ed-4cf4-ba4d-daaaf32815c4)

### Steps to reproduce

Run the scene and move the cylinders right and left on the slope.

### Minimal reproduction project

[collisionIssue.zip](https://github.com/godotengine/godot/files/11951354/collisionIssue.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/46712.
