### ISSUE TITLE
Trying to open the folder of a project from the Project Manager (or a project's `user://` from the editor) opens its parent folder instead

### ISSUE THREAD

**Issue by rblopes** [godotengine/godot#79044]
### Godot version

v4.1.rc3.official [cdd2313ba]

### System information

Godot v4.1.rc3 - KDE neon 5.27 22.04 - Vulkan (Forward+) - integrated AMD Radeon Vega 11 Graphics (RADV RAVEN) () - AMD Ryzen 5 3400G with Radeon Vega Graphics (8 Threads)

### Issue description

Trying to open the folder containing a project from the Project Manager, by clicking the small folder icon beneath the project's name, opens its parent folder in the file manager instead.

Likewise, trying to open the project's data folder from the game editor shows me its parent folder, either the one containing the data folders of all other Godot projects, or even my `~/.local/share` if I set a custom data folder in the project settings.

Using the shortcut menu to open any folder in the File System dock works as intended.

### Steps to reproduce

- In the Project Manager projects list, click the folder icon under the project name;
- Inside the game editor, use the `Project → Open User Data Folder` menu.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Confirmed on Linux (Mageia 9, KDE) with both 4.1-dev2 and 4.1-rc3. It doesn't happen in 4.0-stable, 4.0.3-stable, or 4.1-dev1.

So it's a regression in dev2, probably from #69698. CC @Daylily-Zeleen @KoBeWi @bruvzg

**Comment by KoBeWi** [comment]
Can't reproduce it on Windows.

**Comment by bruvzg** [comment]
Can't reproduce on macOS (but it's expected, there's custom `shell_show_in_file_manager` implementation).

It probably should do something like this, instead of using `ends_with("/")`.
```
	if (!DirAccess::dir_exists_absolute(p_path) && p_open_folder) {
		p_path = p_path.get_base_dir();
	}
```

**Comment by Daylily-Zeleen** [comment]
Currently `shell_show_in_file_manager` only implement on Windows and macOS, will fallback to `shell_open` on other platform.
The document is need updated.

**Comment by Daylily-Zeleen** [comment]
> It probably should do something like this, instead of using ends_with("/").
> 
> ```
> 	if (!DirAccess::dir_exists_absolute(p_path) && p_open_folder) {
> 		p_path = p_path.get_base_dir();
> 	}
> ```

It seem better, but I think we not need check `p_open_folder` here, if it is `false`, it will open the file when fallback to `shell_open`.

I will open and pr to fix this.
