### ISSUE TITLE
Error loading a text file (into a exported project)

### ISSUE THREAD

**Issue by GOOBLEAU** [godotengine/godot#79045]
### Godot version

v4.0.3-stable (commit: 5222a99)

### System information

Windows 10 - Godot v4.0.3-stable - Vulkan (Foward+)

### Issue description

Error when loading a text file in Godot 4.0.3, I have a scene that is responsible for showing the credits and in the script of this scene, a text file is loaded that is in res://assets/general/credits. txt, the content of this file is saved in a Label, when the project is put into test phase, everything is normal and good, but when I export the project to .exe (Windows), .out (Linux), etc, the file text is not loaded in the executable

### Steps to reproduce

![Captura de pantalla (4)](https://github.com/godotengine/godot/assets/135381038/bb558bd9-3309-4703-9b10-89beb1559540)

# Steps start
## Content of credits.txt file:
```
Game by:
<Author's name>

Music by:
<Author's name>
```
## Export project to Windows or Linux or MacOS or ...
# Steps end

# Code:
```
extends Control

func load_text_file(path: String) -> String:
	var file =  FileAccess.open(path,FileAccess.READ)
	return file.get_as_text()

func _ready():
	$Label.text = load_text_file("res://credits.txt")

func _process(_delta):
	var viewport_rect = $Label.get_viewport_rect()
	var label_rect = $Label.get_rect()
	
	$Label.position.y -= 1
	
	if !viewport_rect.intersects(label_rect):
		print("End of credits")
```

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/11953253/Example.zip)

**Comment by dalexeev** [comment]
Make sure that the required file or mask (`*.txt`) is specified in the export settings. See [the docs](https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#resource-options).

**Comment by GOOBLEAU** [comment]
> Make sure that the required file or mask (`*.txt`) is specified in the export settings. See [the docs](https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html#resource-options).

Thanks, that's works now.
