### ISSUE TITLE
Infinite loop freeze/crash in AnimationNodeStateMachine

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#79059]
### Godot version

4.1.rc3.official

### System information

Windows 11, Nvidia Geforce RTX 3070 TI

### Issue description

`AnimationNodeStateMachine` is capable of infinite looping resulting in a freeze and eventual crash. While this is happening, the console is being spammed with:

> ERROR: Failed method: EditorToaster::_error_handler_impl. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:96)

This happens when you point animations at each other with no conditions (ie the default state for connections). 

### Steps to reproduce

* Add a character to your scene with an AnimationPlayer (with some anims) and AnimationTree
* Set an AnimationNodeStateMachine as the AnimationTree root.
* Add two animations, point them at each other, then point Start at the first animation.

Godot will infinite loop and freeze then eventually crash.

### Minimal reproduction project

* Git clone https://github.com/Flynsarmy/gd-statemachine-crash
* In the `AnimationTree` window click 'Connect Nodes' and drag from 'Start' to 'female-locomotion_idle'.

https://github.com/godotengine/godot/assets/334808/8103bb3e-3201-42b8-acff-e807e818db98

**Comment by AThousandShips** [comment]
* Related: #79012

**Comment by Flynsarmy** [comment]
Ah, appears to be a duplicate. Closing
