### ISSUE TITLE
BlendSpace2D anmimations are not synced until reopening scene in editor

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#79057]
### Godot version

4.0.3.stable.arch_linux

### System information

Linux

### Issue description

When checking the `sync` box in the BlendSpace2D editor, animations are not synced until you close and reopen the scene.

https://github.com/godotengine/godot/assets/2496231/9e1b3418-0b50-44a1-92ac-07b304ae48c2

### Steps to reproduce

1. Open player.tscn
3. Check the `sync` box of the BlendSpace2D editor

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/11957081/example.zip)

**Comment by rcorre** [comment]
Possibly unrelated, but I see this error repeated over and over:

```
ERROR: Condition "!state->tree->property_parent_map.has(base_path)" is true.
   at: set_parameter (scene/animation/animation_tree.cpp:65)
ERROR: Condition "!state->tree->property_parent_map.has(base_path)" is true. Returning: Variant()
```

**Comment by TokageItLab** [comment]
This is the intended behavior, as there are cases where it is necessary to sync with an offset. FYI, re-sync is possible by switching between enable/disable Active property of AnimationTree.

**Comment by rcorre** [comment]
> there are cases where it is necessary to sync with an offset

This isn't _actually_ syncing with an offset though. It's appearing synced with an offset in the editor, but is synced without an offset when you play the scene. Then if you reload the scene, it appears synced without an offset.


https://github.com/godotengine/godot/assets/2496231/b957ac7a-d61d-48f1-95ac-255a187b20b2

**Comment by TokageItLab** [comment]
Yes, that is the intended behavior since it is re-activated at runtime. If you want to synchronize with the offset, you will need to set the offset after the run using Seek, etc., just as if the offset occurred on the editor.

**Comment by TokageItLab** [comment]
The editor and the runtime definitely work the same, and if you actually reproduce the Sync option being enabled at the same timing as the editor at runtime, there will be an offset synchronization there.

It may be possible to add something like a re-sync button in the editor, but forcing a re-sync when the Sync option is enabled would mean creating an inconsistency with the runtime. At the very least, the behavior should be make the same at runtime, and perhaps an additional argument to `set_use_sync()` is needed like `set_use_sync(bool enable, bool resync = false)`.

**Comment by rcorre** [comment]
I may have confused this by mentioning the `sync` checkbox. I have the same issue if `sync` is not checked -- the animations appear offset in the editor, but are fine if I play or reload the scene.

I only checked sync because I was confused why my animations didn't look right and was trying that to see if it helped (it didn't).
