### ISSUE TITLE
"Lookup Symbol" right-click menu option often does nothing, even when ctrl-clicking works normally

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#79060]
### Godot version

v4.1.rc3.official [cdd2313ba]

### System information

Windows 11

### Issue description

Right clicking on text in the code editor and selecting "Lookup Symbol" doesn't seem to work for properties and functions. Seems to work okay for class names. Thought this functionality was completely broken until I learned that you could ctrl+click on things. Menu seems to recognize which things are symbols it can look up (e.g. the menu option won't show up for a random string constant, but it will show up for a class method, even if clicking "Lookup Symbol" does nothing), but the functionality itself seems broken.

### Steps to reproduce

Right clicking on most methods or properties seems to trigger this, though it does seem to work on methods that are defined in the same file that you're editing?

### Minimal reproduction project

N/A: editor issue

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/73792.

**Comment by Calinou** [comment]
Consolidating in https://github.com/godotengine/godot/issues/73480, as this is the same issue.
