### ISSUE TITLE
Static memory grows slowly when call WorkerThreadPool.add_task 

### ISSUE THREAD

**Issue by vmagan** [godotengine/godot#79069]
### Godot version

4.0.3.stable

### System information

Windows 11

### Issue description

Hi, 

Calling `WorkerThreadPool.add_task` method on `_physics_process `without wait to finish the task, causes godot static memory go slowly up. However, if wait for task to finish memory leak does not happen.

Example:

### Steps to reproduce

```
func _physics_process(_delta):
	var _task_id = WorkerThreadPool.add_task(_task)
	#WorkerThreadPool.wait_for_task_completion(_task_id)

func _task() :
	pass
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11960098/test.zip)

**Comment by AThousandShips** [comment]
You're adding tasks and not completing them, that will cause a leak in memory, as the task is still tracked until you finish it

**Comment by vmagan** [comment]
ooh yes, you are right, it works then as the thread class. I close the issue, thanks
