### ISSUE TITLE
Fix copy transform shader

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#79063]
### Godot version

4.1 RC2

### System information

Fedora, RX 590

### Issue description

fxing the copy transform glsl shader to respect angles and add the rotate around local/global y as a mode. 

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by akien-mga** [comment]
> 4.0 RC2

I guess you meant 4.1 RC2?

**Comment by QbieShay** [comment]
Fixed, thank you!

**Comment by QbieShay** [comment]
Needs a better, more all-encompassing proposal on how to expand transform align properties to address this and other concerns (most notably billboarding)
