### ISSUE TITLE
OpenGL error:  GL_INVALID_OPERATION in DisableVertexAttribArray [intel, Windows]

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#7906]
**Operating system or device - Godot version:**

Godot 3.0 (0f8c6dd) – Windows 10 – Intel HD Graphics 4400

**Issue description:**

I'm getting a stream of the same error every time I do anything in the editor (even clicking or moving the mouse between docks trigger it). The editor is very slow due to the amount of prints.

```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error
   At: drivers\gles3\rasterizer_gles3.cpp:94
```

**Comment by ippan** [comment]
Godot 3.0 (c37fad6) - Windows 10 - Intel Iris Graphics 540

have same error

**Comment by robertdhernandez** [comment]
I'm getting this error too in my Godot 3.0 (000e873) MSVC build on an 8GB/128GB i5 Surface Pro 3. The editor is extremely slow and borderline unusable.

**Comment by reduz** [comment]
can you manage a batrace? just set error on where it prints that and show
the trace

**Comment by TotCac** [comment]
The same for me on my both Windows 10 platform. Editor is extremly low and unusable. 
What kind of trace do you need ?

**Comment by bojidar-bg** [comment]
@TotCac A backtrace, best if gdb. Set a breakpoint at the line making the error (drivers\gles3\rasterizer_gles3.cpp:94), then wait it to get to the line, and if it is the right error, get the backtrace.

**Comment by ippan** [comment]
Godot 3.0 (c37fad6) backtrace:

#0  _gl_debug_print (source=33350, type=33356, id=1282, severity=37190, length=115,
    message=0x64e544d0 "Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error", userParam=0x0) at drivers/gles3/rasterizer_gles3.cpp:122
#1  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by Tommel1234** [comment]
I got the same error with my laptop us ux305ca.. 
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error
   At: drivers/gles3/rasterizer_gles3.cpp:123

GPU: Intel 515
Os Windows 10

I have try even on linux and it got the same result. The editor is extremely slow and unusable.

**Comment by willt** [comment]
I'm getting the same error.
Windows 10
Intel 620
64 bit version of GoDot

**Comment by reduz** [comment]
I'm confident i fixed this, but please test again

**Comment by ippan** [comment]
yes, no more GL_INVALID_OPERATION.
thanks^^

**Comment by bojidar-bg** [comment]
Closing as fixed.
