### ISSUE TITLE
VoxelGI albedo color is white with custom shaders

### ISSUE THREAD

**Issue by Muini** [godotengine/godot#79068]
### Godot version

4.0.3

### System information

MacOS - 4.0.3 - Forward+ - Vulkan

### Issue description

![image](https://github.com/godotengine/godot/assets/6160740/02edd298-83df-45e0-8491-65933285986f)
<details>
  <summary>On a more complex scene</summary>
  
  ![image](https://github.com/godotengine/godot/assets/6160740/5ae53de2-528c-456e-b727-85de6172d38a)
</details>

VoxelGI does not take custom shader albedo into account, resulting in white voxels.

It's possible to fix it by setting the mesh as Dynamic, but I don't think it's a good solution.

### Steps to reproduce

- Add a MeshInstance3D with a Sphere geometry, and a custom shader material
- Set the albedo of the custom shader to red
- Add VoxelGI to the scene
- Bake VoxelGI
- Either use a reflective material, or use debug view VoxelGI albedo

### Minimal reproduction project

[VoxelGI bug.zip](https://github.com/godotengine/godot/files/11960035/VoxelGI.bug.zip)

**Comment by viksl** [comment]
Can confirm this on Windows 10, godot 4.1 RC3, nvidia GTX 1660Ti.

In the picture below it's three spheres, starting from left:
1. StandardMaterial3D
2. ShaderMaterial, visibility set to Dynamic
3. ShaderMaterial, visibility set to Static

![Screenshot 2023-07-06 003548](https://github.com/godotengine/godot/assets/33526847/552314a0-c72a-406a-b8ed-07d956408ba2)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/64124.
