### ISSUE TITLE
Sub Animation State Machine is reset upon outgoing travel

### ISSUE THREAD

**Issue by kq98** [godotengine/godot#79073]
### Godot version

4.0.3.stable.flathub [5222a99f5]

### System information

Linux Fedora Silverblue 38

### The Situation
I have an outer and an inner Animation Node State Machine.
outer state machine:
![Bildschirmfoto vom 2023-07-05 11-21-05](https://github.com/godotengine/godot/assets/87606259/89fa7e3b-2cf9-47b7-8bdd-838692a0b584)

inner state machine (terrestrial_locomotion_fsm)
![Bildschirmfoto vom 2023-07-05 11-21-24](https://github.com/godotengine/godot/assets/87606259/2f7a82a5-2bed-45a0-9c64-a4a15744841e)

When traversing from the inner state machine to an animation node in the outer state machine, the inner state machine is reset. 
Meaning that once the blending between the outer animation node and the inner animation state machine begins the inner state machine jumps to its internal "start" state, which is causing the targeted mesh to fallback to its unanimated form, a tpose in my case.  Although there are immediate travel paths from the "start" state to other ones without any blend time, the tpose is visible for a few frames. The effects length might depend on the users specs.

This is causing ugly transitions as seen here, where I travel from the inner state machine that handles jogging, walking and idling to a sprint animation in the outer animation state machine.(video is slowed down to make the problem more apparent)

https://github.com/godotengine/godot/assets/87606259/221b7389-baf7-4895-b6ae-8c5fece9bf60

### What I would have expected
The inner state machine should not be reset upon outgoing travel until the blending is completed.
### Workaround
Don't use sub state machines

### Steps to reproduce

Create an outer and an inner Animation Node State Machine. 
Have a looping animation inside the inner state machine and travel to a node in the outer animation state machine with an Xfade time > 0.
Notice how the model snaps to its unanimated form for a few frames upon outgoing travel.

### Minimal reproduction project

[DemoProjekt.zip](https://github.com/godotengine/godot/files/11960182/DemoProjekt.zip)

With this simple cube the effect is harder to see than with more complex models and animations, but notice the snapping that occurres when traveling from inner_state_machine to the move animation node

**Comment by TokageItLab** [comment]
Should be fixed in https://github.com/godotengine/godot/pull/75759 already.
