### ISSUE TITLE
Renaming unique node to the same name results in an error dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#79085]
### Godot version

4.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/852654b0-dadd-411e-8fe5-f9c00492a497

### Steps to reproduce

1. Add a Node to the scene
2. Right click it and mark it as unique name
3. Start renaming the node
4. Press Enter

### Minimal reproduction project

N/A

**Comment by theraot** [comment]
I'm pretty sure I reported this: https://github.com/godotengine/godot/issues/78922

**Comment by KoBeWi** [comment]
I'll close this as duplicate.
