### ISSUE TITLE
Version upgrade/downgrade confirmation dialog buttons misaligned

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#79096]
### Godot version

v4.1.stable.official [970459615]  < Steam

### System information

Godot v4.1.stable - Debian GNU/Linux trixie/sid trixie - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

After Godot got upgraded 4.0 -> 4.1, when opening a project from the earlier version, I noticed that the buttons in the confirmation dialog look a bit squiffy:

![Screenshot_20230706_123457](https://github.com/godotengine/godot/assets/441188/eb5dc8e3-9941-4cac-8cb8-17167d1f33bf)

(Somewhat aside, but that dialog should probably be able to deduce and be more precise about whether it's an upgrade or downgrade!)

### Steps to reproduce

1. Have a project from Godot 4.0
2. Upgrade Godot to 4.1
3. Open project manager

Alternatively:
1. Create a new project in 4.1
2. Quit Godot
3. Edit the `project.godot`'s `config/features` to read `4.0` instead of `4.1`
4. Open project manager

### Minimal reproduction project

[default.zip](https://github.com/godotengine/godot/files/11967512/default.zip)

**Comment by Calinou** [comment]
Note that the button offset is swapped around on Windows, as evidenced in the screenshot present in https://github.com/godotengine/godot-proposals/issues/7254.

**Comment by kleonc** [comment]
Same issue as in https://github.com/godotengine/godot/issues/50192#issuecomment-874785436. Such custom added button is being hidden:
https://github.com/godotengine/godot/blob/7030ac555f6af936174097c4642e60c1a6b0877b/editor/project_manager.cpp#L2257
but the spacer remains visible.
