### ISSUE TITLE
Setting `trail_lifetime`  of a particle below 0.1 will always result in an ERROR_COND

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [godotengine/godot#79091]
### Godot version

4.0.1.stable

### System information

Manjaro Linux

### Issue description

As the title mentions, setting the property `trail_lifetime` of `GPUParticles3D` below 0.1 will - as defined in `servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:424` - always result in the error message: 

`ERROR: Condition "p_length < 0.1" is true.`

This is true for setting it from the editor and from script. Since this is a hardcoded value, would it not be more user-friendly to limit the `p_length` and warn the user if they try to set it below this threshold? 

### Steps to reproduce

Create a scene with `GPUParticles3D` and set the property `trail_lifetime` below 0.1 from editor or script.

### Minimal reproduction project

Trivial

**Comment by hbread00** [comment]
4.4 still has this issue with GPUParticle2D. The minimum value set in the editor is 0.01, it still prompt error.

```
E 0:00:01:387   particles_set_trails: Condition "p_length < 0.01" is true.
  <C++ 源文件>     servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:442 @ particles_set_trails()
```

**Comment by Rudolph-B** [comment]
That has been reported in #92708
