### ISSUE TITLE
Menudialog freezes godot

### ISSUE THREAD

**Issue by IDDQD69** [godotengine/godot#79106]
### Godot version

v4.1.stable.official [970459615]

### System information

Arch linux, kernel 6.4.1, wayland, kde Plasma 5.27.6

### Issue description

Godot editor freezes when any menu dialog is opened.

### Steps to reproduce

Open editor, open project and right click on a node or in a editor. Menu opens, nothing can be selected and whole editor freezes.

### Minimal reproduction project

N/A

**Comment by IDDQD69** [comment]
This seems to be issue only with wayland.

**Comment by akien-mga** [comment]
- Duplicate of #78487
