### ISSUE TITLE
Unable to add Varyings in visual shader.

### ISSUE THREAD

**Issue by asciiboi** [godotengine/godot#79109]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When you press the `Manage Varyings` button and `Add varying` popup that shows up the window shows up as it should, but when you press anything inside of the window it just closes.

This happens in multi window mode and in single window mode.

### Steps to reproduce

1. Open godot
2. Create a new visual shader
3. Open the visual shader editor
4. Press the Manage Varyings button
5. Press Add varying
6. Do any action in the dialog box that pops up.
7. The window closes.

### Minimal reproduction project

N/A

**Comment by vrid** [comment]
> The varying should have been added internally. You must use GetVarying/SetVarying nodes to access them, the new varying will be added to the dropdown box list of those nodes.

It is possible to create only the default type of a varying(float). Changing the data type or whether its e.g. Fragment only closes the window so it's a bug.
Accessing and setting varyings isn't a problem here.

**Comment by EddyLuten** [comment]
Also seeing this behavior on: Godot v4.1.stable.mono - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - dedicated Intel(R) Arc(tm) A770 Graphics (DG2) () - 13th Gen Intel(R) Core(TM) i9-13900KF (32 Threads)

**Comment by Chaosus** [comment]
Yup, sorry about misunderstanding, I observe this bug on Windows too..

**Comment by Chaosus** [comment]
This seems to be fixed on 851bc640ddf7225a4b52bb15cc50c249df119953
![test_bug](https://github.com/godotengine/godot/assets/3036176/3773bdd2-4110-4f45-9e39-784e8f42e131)
@QbieShay can you check it?

**Comment by Chaosus** [comment]
Seems to be fixed in the 4.2 (see https://godotengine.org/article/dev-snapshot-godot-4-2-dev-1/). Closed.
