### ISSUE TITLE
Unable to delete files when project is on non-`/home` drive / mount point without pre-existing `.Trash` folder

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#79108]
### Godot version

v4.1.stable.official [970459615]  < Steam

### System information

Godot v4.1.stable - Debian GNU/Linux trixie/sid trixie - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

On this machine, I have my projects stored on a separate drive to my system and home directory. This drive is mounted at `/data`.

Since 4.1, if I attempt to delete a project file through the in-editor file browser, I get an error dialog (though the window opens much larger than this screenshot):

![Screenshot_20230706_161340](https://github.com/godotengine/godot/assets/441188/b343e807-83dd-41e9-9a2f-b7f2cc292989)

The editor output console shows the (misleading) error:

>   platform/linuxbsd/os_linuxbsd.cpp:968 - move_to_trash: No such file or directory as /data/src/godot/default/new_script.gd.

However, if Godot is run from the command-line, we also get the following additional information prior to that error output:

> gio: file:///data/src/godot/default/new_script.gd: Unable to find or create wastebasket directory /data/.Trash-1000 to move /data/src/godot/default/new_script.gd to

Indeed, the root of the `/data` mount point is not writeable by regular users, and there's no trash directory in there already.

Prior to 4.1, it appears that deleted files would be moved into my home dir's trash, across filesystems, since my `~/.local/share/Trash` is seemingly full of stuff I have previously deleted from my current project.

### Steps to reproduce

1. Use Linux
2. Create or open a project on a secondary drive (one which doesn't also contain your home dir).
3. Open the project in the Godot editor
4. Delete a file (eg. `icon.svg`) from the editor's FileSystem panel.
5. :eyes: :exclamation: 

### Minimal reproduction project

n/a

**Comment by starccy** [comment]
I have a similar situation. I am using Linux with Godot as the same version as @romlok. 

I created my project in a `tmpfs` type filesystem.
When I try to delete a file from the editor, I got a error:

```
ERROR: move_to_trash: No such file or directory as /mtmp/platformer/test.txt.
```

I also see the gio output from the console before the error message but different with @romlok:

```
gio: file:///tmp/test/test.gd: Trashing on system internal mounts is not supported
```
