### ISSUE TITLE
HiDPI scaling and setting issue

### ISSUE THREAD

**Issue by CaelRowley** [godotengine/godot#79113]
### Godot version

4.0.3

### System information

macOS Ventura 13.0

### Issue description

Sorry if this is not actually a bug but the `Allow hiDPI` setting is not behaving as expected for me. 

The first issue is with using `ProjectSettings.get_setting('display/window/dpi/allow_hidpi')` does not return the correct value, as you can see in my screenshot, I have the setting enabled, yet printing the setting in code is returning `false`. And following this, changing the setting with `set_setting` has no effect in game.

![image](https://github.com/godotengine/godot/assets/9076746/d0ec02b8-e806-4f70-af4f-a5fc92e2bf57)

The other issue is with the scaling itself. I have a 4k monitor and a windows and macOS device. 

**Windows I have zoom set to 150% (basically zoomed in)**
-      hiDPI enabled => game is rendered at the 4k native monitor resolution and appears crisp
-      hiDPI disabled => game is rendered at below the 4k  native monitor resolution and appears blurry (based to the os zoom)

**macOS I have the display set to More Space (basically zoomed out)**
-      hiDPI enabled => game is rendered at 7k much higher than the native monitor resolution (based to the os zoom)
-      hiDPI disabled => game is rendered at the 4k native monitor resolution and appears crisp

This means that to render the game at native monitor resolution I need to either enable/disable this setting depending on my os zoom level on the display. But I am unable to allow the user to toggle this setting because of the first issue I mentioned.

### Steps to reproduce

**Issue 1**
Enable the project settings -> Display -> Window -> Allow hiDPI -> true
In game call `print(ProjectSettings.get_setting('display/window/dpi/allow_hidpi'))` and you will see `false`

**Issue 2**
Run the game on a 4k monitor at different OS zoom levels and enable/disable hiDPI
In game call `print(get_viewport().size)` when fullscreen to see the resolutions

### Minimal reproduction project

You only need an empty project with the following code

```
# to check if the setting is enabled
print(ProjectSettings.get_setting('display/window/dpi/allow_hidpi')) 

# to enter fullscreen on your game for checking the resolution
get_window().mode = get_window().MODE_FULLSCREEN

# when fullscreen call this to check the viewport resolution
print(get_viewport().size)
```

**Comment by Calinou** [comment]
>  hiDPI enabled => game is rendered at 7k much higher than the native monitor resolution (based to the os zoom)

This is how hiDPI scaling at non-integer scale factors works on macOS. macOS does not support fractional scaling. If you specify a fractional scale factor in the macOS settings, it will scale up to the next integer value, then scale down the resulting rendering on your screen. This can easily lead to very high internal resolutions are you're seeing here.

**Comment by CaelRowley** [comment]
Thanks for the detailed explanation, so the scaling itself is expected behaviour and not a bug, but that still leaves the first issue I mentioned, which is important as this means that the user will need to be able to toggle this setting depending on the device they are using.

**Comment by Calinou** [comment]
**Allow hiDPI** needs to be left enabled by default for a good experience on most devices, such as MacBooks with Retina displays.

It might be possible to detect the scaling setting before creating the window and disable **Allow Hidpi** if the scale factor is set to a non-integer factor, but this is error-prone with multi-monitor setups. This would also require turning **Allow hiDpi** into an enum with the values **Disabled**, **Enabled** and **Auto** (in this order to preserve compatibility).

cc @bruvzg

**Comment by CaelRowley** [comment]
I think allowing the user themselves to toggle it in on/off game would be a fine solution. But the setting seems bugged when accessing it in code:

![image](https://github.com/godotengine/godot/assets/9076746/2eea4725-5b6e-48da-ab39-84b4eeb1b7e8)

**Comment by Calinou** [comment]
> I think allowing the user themselves to toggle it in on/off game would be a fine solution. But the setting seems bugged when accessing it in code:

The setting is only read when the project starts, so you'd have to write it to an `override.cfg` file in `user://` or in the same location as the executable.

**Comment by bruvzg** [comment]
> It might be possible to detect the scaling setting before creating the window and disable Allow hiDPI on macOS if the scale factor is set to a non-integer factor, but this is error-prone with multi-monitor setups.

macOS API supports only two scaled 1x and 2x, even if real display scale is non-integer, so it's not doable.

Using `ProjectSettings.get_setting("display/window/dpi/allow_hidpi")` seems to work fine and return correct value, buy you can't change it at runtime.

**Comment by CaelRowley** [comment]
@bruvzg in my screenshot you can see that I have the setting enabled, but printing it out is showing false.

**Comment by CaelRowley** [comment]
@Calinou thanks! I will setup an override config and ask the user to restart the game if they change this setting
