### ISSUE TITLE
Inconsistent build options in a generated Visual Studio project

### ISSUE THREAD

**Issue by CncealDVRflectN** [godotengine/godot#79127]
### Godot version

4.1dev [cdd2313]

### System information

Windows 11 22H2 - Visual Studio 2022 (17.6.4) - SCons 4.5.2 - Python 3.10.11

### Issue description

Multiple build options are ignored in a Visual Studio project generation step.

Build command line in Visual Studio project built with options `vsproj=yes dev_build=yes dev_mode=yes`:
![Screenshot 2023-07-04 224622](https://github.com/godotengine/godot/assets/22374549/78d629f3-9731-435c-a201-ef40fd70101f)

Build command line in Visual Studio project built with options `vsproj=yes dev_build=yes verbose=yes warnings=extra tests=yes`:
![Screenshot 2023-07-04 225646](https://github.com/godotengine/godot/assets/22374549/9f9b2452-1afe-4610-a5ad-b66779d11b3d)

As you can see in the second screenshot, options 'verbose' and 'warnings' are missing in the Visual Studio project. So is there any specific reason why only some options are transferred, or can I modify the `generate_vs_project` method to copy all original options (excluding `vsproj` of course) and create a PR? Also, I'm curious: why is the `progress` option explicitly set to `no` for Visual Studio projects?
https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/methods.py#L851-L874

### Steps to reproduce

1. Build the engine with options `vsproj=yes dev_build=yes dev_mode=yes`
2. Open the generated project in Visual Studio
3. Open projects's NMake properties (Project->Properties->NMake)
4. Check `Build Command Line` and `Rebuild All Command Line` properties
5. Close Visual Studio
6. Rebuild the engine with options `vsproj=yes dev_build=yes verbose=yes warnings=extra tests=yes`
7. Open the generated project in Visual Studio
8. Open projects's NMake properties (Project->Properties->NMake)
9. Check `Build Command Line` and `Rebuild All Command Line` properties

### Minimal reproduction project

N/A

**Comment by anvilfolk** [comment]
I can confirm this, I tried compiling with `scons vsproj=true dev_mode=true dev_build=true scu_build=true fast_unsafe=true verbose=true windows_subsystem=console` and only got the `dev_*=true` options.
