### ISSUE TITLE
Import .blend using Blender 4.0

### ISSUE THREAD

**Issue by hemulya** [godotengine/godot#79124]
### Godot version

4.1

### System information

Godot v4.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When importer detects blend file next window apears:
![image](https://github.com/godotengine/godot/assets/2434928/c1983283-900e-4fd1-9ef4-00682465c741)

I'm using Blender daily builds which recentrly updated to version 4.0

### Steps to reproduce

1. Install Blender daily build
2. Setup Godot blend import path to daily build
3. Add .blend file to Godot project directory

### Minimal reproduction project

Used newly created godot project

**Comment by AThousandShips** [comment]
Simple fact is that we don't currently support this version as it isn't guaranteed to be compatible, not really a bug here, but worth investigating the compatibility, but be aware that Blender 4.0 hasn't been released yet so there's no reason to support it until then

**Comment by hemulya** [comment]
Yes, agreed. But before 4.0 daily builds worked well. So you don't have check for maximum version. Also it is not possible check integration issues on blender development version. So all bugs will (if they will be) when new Blender release appears. In my opinion, there no reson to block dev blender version.

**Comment by akien-mga** [comment]
It took Blender two decades to go from 2.0 to 3.0, so I guess Juan didn't expect 4.0 to come so soon. The editor setting is even named `filesystem/import/blender/blender3_path` (and at the time Blender 2.8 or earlier were still common enough that 3.0+ was an important requirement to set).

But yeah the test is likely overeager and could be removed.

**Comment by AThousandShips** [comment]
One suggestion would be to add a warning when using recent versions, indicating that it might behave in unpredictable and undefined ways (as it's not yet released as far as I can tell, and I don't know that we've investigated compatibility) and prepare for the release and check the compatibility

While it should comply with the GLTF standard on the output, I assume there might be incompatibility with the command line interface or similar, or things like properties and things

**Comment by fracteed** [comment]
I really wouldn't recommend using Blender 4.0 for any serious work yet. There are massive breaking changes going on with the way mesh normals and smoothing work. These changes, when they are finalised, will have to be updated in the gltf exporter, which is what the Godot importer is using in the background for a blend file.

**Comment by hemulya** [comment]
People who install daily builds already know that it is unstable. I don't think that Godot should send another warning to the user. If something wrong with blender importer user should see an error in output and create a bug report here with included blender version. Godot developers will know all breaking changes before 4.0 release and will be ready.
Another situation, when users that using stable versions of programs get these errors and here will be created many bugs reports and user will get bad UX.

**Comment by Zireael07** [comment]
@hemulya the whole point is that Blender 4.0 itself is changing rapidly - no point engaging in a wild goose chase if some things end up reworked/dropped on their side

**Comment by hemulya** [comment]
This is correct. But as I see, you want block blender dev builds. So evere 2/3 monthes you need update Godot to not use version 4.0/4.1/.... And you will engaging goose chase.
In my propose no needs to update godot before stable Blender version release (if needed). And you will know what need to be fixed before release. All bugs for blender daily builds will be as reminder (I don't thinks that there will be many). 
Anyway you will need fix blender import issue. The differents as I see will be in people who will find the bug - who expect the bug or who will be blocked to update to new stable version before fix. And second group will be bigger.

**Comment by hemulya** [comment]
Hey, guys.
There are 4.0 release soon. This bug will appear for Godot dev more offen. Any plans to fix this ?

**Comment by fire** [comment]
This is being tracked in https://github.com/godotengine/godot/pull/82211

**Comment by akien-mga** [comment]
Fixed by #81194.
