### ISSUE TITLE
Transparent background breaks when setting window mode from script

### ISSUE THREAD

**Issue by jcronenberg** [godotengine/godot#79132]
### Godot version

3.5.2 3.6-beta2

### System information

Linux X11, AMD GPU, GLES2 and GLES3

### Issue description

When a transparent background is enabled and the project is set to launch in fullscreen, if I switch off fullscreen by calling `OS.set_window_fullscreen(false)` in a AutoLoad script's `_ready()` function, I get a black screen.
![image](https://github.com/godotengine/godot/assets/54934253/35fd480f-d756-4e78-8687-242d2d5eeea8)
Changing from windowed to fullscreen also produces a black screen.
~~This only occures in a AutoLoad script's `_ready()` function. If it is set in e.g. `_process()` it works.~~
Edit: Sorry, no this also occurs in `_process()` this was just a fault of trying a lot of different things :slightly_smiling_face: 

### Steps to reproduce

1. Set project to launch in fullscreen and enable transparent background.
1. Write a Autoload script that sets fullscreen off via `OS.set_window_fullscreen(false)` in its `_ready()` function
1. Launch project

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11972579/project.zip)

**Comment by jcronenberg** [comment]
I just tried it on my laptop which has a almost identical setup but an Intel iGPU.
There I had to add a `get_tree().get_root().set_transparent_background(true)` after changing away from fullscreen, but then it also blackscreened.
In case it is also relevant, I'm running picom as my compositor, though I don't have issues with any other transparent programs. And changing fullscreen mode via my window manager works without blackscreen.

**Comment by bruvzg** [comment]
> When a transparent background is enabled and the project is set to launch in fullscreen

This is expected behavior, you can't have exclusive full-screen window with transparent background (you can enable it, but OS will disable composition and won't draw any other windows or desktop when exclusive full-screen window is detected). In 4.x you can use non-exclusive full-screen mode, in 3.x make a borderless window which is a one pixel bigger or smaller than screen to prevent switching to exclusive full-screen.

> `OS.set_window_fullscreen(false)` in its `_ready()` function

Changing mode in `_ready` won't work reliably. Transition to/from full-screen take some time and usually is not finished when `_ready` is called.

**Comment by jcronenberg** [comment]
But the thing is if it is set to launch in "fullscreen" the transparent background works. Maybe it is in borderless then, though in project settings borderless is unchecked. If I then make a button that executes `OS.set_window_fullscreen(false)`, so it goes to window mode, transparent background breaks and it blackscreens.

**Comment by jcronenberg** [comment]
https://github.com/godotengine/godot/assets/54934253/eef9dc39-620e-4bae-8a03-678b1aeca87c

**Comment by jcronenberg** [comment]
Ah okay adding
```
OS.set_window_per_pixel_transparency_enabled(true)
```
to the button makes it work.
I still think the black screen shouldn't appear because the normal background should appear when the transparency somehow gets disabled, but that's less of an issue I guess.
