### ISSUE TITLE
POT generation with saved scenes loaded from another scene doesn't work

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#79144]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11

### Issue description

Godot doesn't recognize `auto_translate` nodes if they are from a saved scened.

### Steps to reproduce

Write a scene with two labels: the built-in `Label` and a custom scene that inherits from `Label`. Then try to generate the `.pot` file.

### Minimal reproduction project

[gettext_test.zip](https://github.com/godotengine/godot/files/11979493/gettext_test.zip)

**Comment by Okxa** [comment]
Looks to be same as: https://github.com/godotengine/godot/issues/74194
