### ISSUE TITLE
transform.looking_at(): target and Vector3.UP parallel even after doing the same checks as the source code

### ISSUE THREAD

**Issue by tateorrtot** [godotengine/godot#79146]
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

Trying to use transform.looking_at(). Even though I have the same check as the source code for 4.1, my check to see if my target_position and Vector3.UP are parallel never fire. The check inside of looking_at() fires then gives me an error.

### Steps to reproduce

I ran across this error while creating a real-time strategy game where units must slowly turn to face a direction.

I'm getting this error when the unit tries to look at itself. This is because its current and target position is parallel.
```

E 0:00:02:0629   rotation_component.gd:47 @ get_target_angle(): The target vector and up vector can't be parallel to each other.
  <C++ Error>    Condition "v_x.is_zero_approx()" is true. Returning: Basis()
  <C++ Source>   core/math/basis.cpp:1030 @ looking_at()
  <Stack Trace>  rotation_component.gd:47 @ get_target_angle()
                 rotation_component.gd:8 @ turn_to()
                 infantry_movement_component.gd:30 @ _process()
```

To add a check for the unit to not look at itself, I normalized the target position and then got the cross-product with Vector3.UP. Basically checking if they were parallel.

```
if target.normalized().cross(Vector3.UP) == Vector3.ZERO: 
    return
```

This wasn't working as expected so I got help from the Godot Discord.

https://discord.com/channels/212250894228652034/610347507222052867/1126772925719117954

The user .lewiji helped me replicate the same check that the source code does.

```
func get_target_angle(from_node3d : Node3D, target : Vector3):
...
	#Normalised target
	var v_z : Vector3 = target.normalized()
	#Perpendicular vector using up+front
	var v_x : Vector3 = Vector3.UP.cross(-v_z)
	
	if v_x.is_zero_approx():
		print("Too close to being parallel!")
		return
```

This check would never fire and I would get the exact same error as above.

### Minimal reproduction project

N/A

I can upload my project or a simplified version of it if needed!

**Comment by AThousandShips** [comment]
Are you taking the direction to the target from your position? Doesn't look like it from your code snippet

**Comment by tateorrtot** [comment]
No, I was not. So sorry!

If you don't mind clarifying, I was checking the vector from (0,0) to the target position instead of a vector originating from the node's current position to the target position, which is why my code wasn't working as expected?

![image](https://github.com/godotengine/godot/assets/86398489/fa19ad5d-feff-4fba-8b6b-0fffb750534b)

**Comment by AThousandShips** [comment]
Yes, look at the code in `Transform3D`, it should be from your position, not from `(0, 0)`
