### ISSUE TITLE
4.1 Mono Regression - Export via CLI is broken (not saving all required resources)

### ISSUE THREAD

**Issue by DillonSteyl** [godotengine/godot#79159]
### Godot version

v4.1.stable.mono

### System information

Windows 11

### Issue description

The automated build system I set up (via Gitlab CI/CD) for exporting my game is no longer working in 4.1.

The `.pck` file generated during export is orders of magnitude smaller than I'd expect, and the game doesn't get past the first frame of the splash screen due to the lack of resources. I've noticed the `savepack` part of the export process seems to skip some steps...
```
savepack: begin: Packing steps: 102
        savepack: step 2: Storing File: res://build/springdash.ico
        savepack: step 102: Storing File: res://.godot/global_script_class_cache.cfg
        savepack: step 102: Storing File: res://icons/spring_dash.png
        savepack: step 102: Storing File: res://.godot/uid_cache.bin
        savepack: step 102: Storing File: res://project.binary
```

Exporting through the UI works as expected, but exporting via CLI (e.g. via something like `godot4 --export-release windows-64bit export/test.exe`) results in the issue described above.

### Steps to reproduce

- Setup a basic project that relies on some resources (e.g. an image) in Godot 4.1 (or use the one provided)
- Export via the UI and notice that it works
- Export via the CLI and notice that it doesn't, and the `.pck` file is either not present or much smaller than expected

### Minimal reproduction project

[export-cli.zip](https://github.com/godotengine/godot/files/11983031/export-cli.zip)

**Comment by akien-mga** [comment]
Tested locally on Linux with the MRP, it seems to export fine for me:
```
$ Godot_v4.1-stable_linux.x86_64 --headless --export-release "Windows Desktop" export/test.exe
Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
 
WARNING: Custom cursor shape not supported by this display server.
     at: cursor_set_custom_image (servers/display_server.cpp:480)
reimport: begin: (Re)Importing Assets steps: 2
        reimport: step 1: icon.svg
WARNING: Resources Modification: Could not start rcedit executable. Configure rcedit path in the Editor Settings (Export > Windows > rcedit), or disable "Application > Modify Resources" in the export preset.
     at: add_message (editor/export/editor_export_platform.h:175)
savepack: begin: Packing steps: 102
        savepack: step 2: Storing File: res://.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn
        savepack: step 52: Storing File: res://.godot/imported/angry_stoat.png-bfae575bd6d10b21bd2f792e5f0e0912.ctex
        savepack: step 52: Storing File: res://angry_stoat.png.import
        savepack: step 102: Storing File: res://main.tscn.remap
        savepack: step 102: Storing File: res://.godot/global_script_class_cache.cfg
        savepack: step 102: Storing File: res://icon.svg
        savepack: step 102: Storing File: res://.godot/uid_cache.bin
        savepack: step 102: Storing File: res://project.binary
savepack: end
WARNING: Project export for preset "Windows Desktop" completed with warnings.
     at: _fs_changed (editor/editor_node.cpp:1006)
reimport: end
ERROR: 3 RID allocations of type 'N18RendererCanvasCull4ItemE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN13RendererDummy14TextureStorage12DummyTextureE' were leaked at exit.
ERROR: 6 RID allocations of type 'PN18TextServerAdvanced22ShapedTextDataAdvancedE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2045)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
```

The generated `.exe` and `.pck` seem to work as expected (I see the angry stoat :)).

**Comment by Calinou** [comment]
@DillonSteyl Can you try the same steps on 4.1 dev/beta/RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.1/).

**Comment by DillonSteyl** [comment]
That's interesting. I managed to get it to work using "Export selected resources (and dependencies)" as the export mode, and selecting all of the resources explicitly.

None of the other export modes I've tried will do it for me when I'm using the CLI, so maybe related to how resources are "discovered"?

**Comment by akien-mga** [comment]
CC @godotengine/dotnet

**Comment by DillonSteyl** [comment]
@Calinou The regression was introduced in `dev4`. Exporting works as expected in `dev3` and prior.

**Comment by YuriSizov** [comment]
`dev4` only contains one C#/.NET related change of note: https://github.com/godotengine/godot/pull/72619

**Comment by RedworkDE** [comment]
Reverting that seems to fix the issue, not sure how it is related.

**Comment by raulsntos** [comment]
> Update: just removing the EditorFileSystem::update() calls also fixes it.

That was going to be my guess. The MRP has the export filter `EXPORT_SELECTED_SCENES` which tries to find the dependencies from the selected scenes using `EditorFileSystem`, right? If so, maybe updating it causes it to somehow lose knowledge of other files.

But in the .NET module we are only calling `EditorFileSystem::update_file` with paths to script files (presumably only C# scripts). So I don't understand how this can affect PNG files.

**Comment by RedworkDE** [comment]
it calls them probably for the editor tools scripts, notably for those scripts `get_path()` returns an empty string which then presumably breaks things in update_file

**Comment by raulsntos** [comment]
I see, we should probably avoid calling it for editor scripts since they are not part of the project. And also, maybe `EditorFileSystem::update_file` should have `ERR_FAIL_COND(p_file.is_empty());`.

**Comment by RedworkDE** [comment]
I don't think we can (easily) avoid that since this is also part of the initial load and these scripts still need to work like scripts, or the editor just breaks.

**Comment by raulsntos** [comment]
I think what you've done in https://github.com/godotengine/godot/pull/79173 is good enough, since we only update EFS to update global classes and the only C# scripts that can be global classes must have a path.
