### ISSUE TITLE
Godot 4.1 uses higher CPU, and has lower performance in-editor.

### ISSUE THREAD

**Issue by squareverylong** [godotengine/godot#79160]
### Godot version

v4.1-stable

### System information

Linux Mint 21.1 Cinnamon (Cinnamon Version 5.6.8, Kernel 5.15.0-76-generic) - Godot v4.1.stable - Vulcan (Forward+) - NVIDIA GeForce GTX 1050   &   AMD FX-6300 Six-Core Processor x 3

### Issue description

Godot v4.1 seems to run more sluggishly on this computer, which I admit isn't exactly high end, but v4.0.3 ran significantly faster.

Here is my CPU performance in both :
![GODOT4 0 3ACTIVEUSE](https://github.com/godotengine/godot/assets/124287600/da8fbc48-6acc-4d31-8921-ed04275197f5)
"Active Use" here is me creating a control in the scene, and then just doing random stuff in the UI, such as hiding and unhiding catagories in the inspector or selecting and unselecting the node.

This is my computer with nothing but a single Nemo window and System monitor - same as what i had open for Godot.
![NOTHING_BUTFILEMANAGERANDSYSTEMMONITOR](https://github.com/godotengine/godot/assets/124287600/8196c580-ec3d-4989-954f-80d00201237c)

### Steps to reproduce

The project I used for testing was a completely empty project, with an unsaved scene and a single control, where i just messed around with hiding and showing and unselecting. Essentially just did menial tasks that did nothing to test it. 
However, I notice this no matter what project it is and what it contains.

Note : This may be somewhat specific to my hardware - or at least hardware with similar performance. I would try it on my PC with higher spec, but I currently cannot.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you try the same steps on 4.1 dev/beta/RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.1/).

**Comment by winston-yallow** [comment]
I think squareverylong mentioned on Discord that the issue is reproducible with beta1

**Comment by squareverylong** [comment]
yes, i tried beta-1 with the same result.

**Comment by winston-yallow** [comment]
I don't remember, did you try the dev builds too?

**Comment by NatGazer** [comment]
My project is running at **86 fps** in 4.0.3 and at **58 fps** 4.1. The performance loss is very noticeable. I'll might make a separate issue with a demo project for anyone to test

**Comment by squareverylong** [comment]
> I don't remember, did you try the earlier dev builds too?
I have not, no. I will do that soon and get back to you.

**Comment by Calinou** [comment]
> My project is running at **86 fps** in 4.0.3 and at **58 fps** in 4.1. The performance loss is very noticeable. I'll might make a separate issue with a demo project for anyone to test

For reference, this turned out to be an unrelated issue: https://github.com/godotengine/godot/issues/79222

**Comment by 451507056** [comment]
I had a similar problem when upgrading my project from 4.0.3 to 4.1.1. I have a large number of labels that are constantly being displayed and hidden every second. My cpu is not good is i5-7600, the occupancy rate of about 15% went up to 26%.

**Comment by squareverylong** [comment]
I'm no longer sure if my initial testing was accurate at all, so I will try again next time i am free ( and able ) to do so.
