### ISSUE TITLE
C# Getting Node3D Position/GlobalPosition in Thread will always return zero

### ISSUE THREAD

**Issue by Xyotic** [godotengine/godot#79164]
### Godot version

Godot 4.1 stable

### System information

Windows 10, RTX2080, i9-9900K

### Issue description

Trying to access the position with node3D.Position or node3D.GlobalPosition inside a thread will always return Vector3(0,0,0)  in 4.1
Worked without any issue in 4.0

### Steps to reproduce

Add a Node to your scene and attach a script to it like this: (same code in mrp)

```cs
using Godot;
using System;
using System.Threading.Tasks;

public partial class Demonstration : MeshInstance3D
{
	public override void _Ready()
	{
		var currentPosition = this.Position;
		GD.Print(currentPosition); // will print the correct position
		
		Task.Run(async() => 
		{
			await Task.Delay(100);
			var currentPositionInThread = this.Position;
			GD.Print(currentPositionInThread); // will print zero
		});
	}
}
```

If step into this code you will see that the information of the position will be lost as soon as you enter the Task.Run() block

### Minimal reproduction project

[GetPositionIssue.zip](https://github.com/godotengine/godot/files/11984052/GetPositionIssue.zip)

**Comment by raulsntos** [comment]
Accessing node members outside of the main thread is not allowed. The `Node3D::get_position` method has a thread guard:

https://github.com/godotengine/godot/blob/c3b0a92c3cd9a219c1b1776b48c147f1d0602f07/scene/3d/node_3d.cpp#L508-L511

You should be getting this error:

```
ERROR: This function in this node (/root/Node3D/MeshInstance3D) can only be accessed
       from either the main thread or a thread group. Use call_deferred() instead.
```

Take a look at the [Thread-safe APIs](https://docs.godotengine.org/en/4.1/tutorials/performance/thread_safe_apis.html) documentation for more information.

---

You can follow the error's suggestion and use `CallDeferred` or `Callable.CallDeferred` to avoid this error, here's an example using a `Callable`:

```csharp
using Godot;
using System;
using System.Threading.Tasks;

public partial class Demonstration : MeshInstance3D
{
	public override void _Ready()
	{
		var currentPosition = this.Position;
		GD.Print(currentPosition); // will print the correct position
		
		Task.Run(async() => 
		{
			await Task.Delay(100);
			Callable.From(() =>
			{
				var currentPositionInThread = this.Position;
				GD.Print(currentPositionInThread); // will print the correct position
			}).CallDeferred();
		});
	}
}
```

**Comment by Xyotic** [comment]
Thanks for clarification.
This change in 4.1 breaks a lot of my code.
Is there any way I can await getting the nodes position? i.e. awaiting CallDeferred?

**Comment by raulsntos** [comment]
Yes, you should also be able to await the `process_frame` signal on the `SceneTree`:

```csharp
await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame);
```

**Comment by RedworkDE** [comment]
Also consider if the `Task.Run` is even necessary, for example `_Ready` could be made `async` directly:

```cs
public override async void _Ready()
{
	var currentPosition = this.Position;
	GD.Print(currentPosition); // will print the correct position
	
	await Task.Delay(100);
	var currentPositionAfterWait = this.Position;
	GD.Print(currentPositionAfterWait); // will print the correct position
}
```

**Comment by Xyotic** [comment]
> Also consider if the `Task.Run` is even necessary, for example `_Ready` could be made `async` directly:
> 
> ```cs
> public override async void _Ready()
> {
> 	var currentPosition = this.Position;
> 	GD.Print(currentPosition); // will print the correct position
> 	
> 	await Task.Delay(100);
> 	var currentPositionAfterWait = this.Position;
> 	GD.Print(currentPositionAfterWait); // will print the correct position
> }
> ```

Would this not block the whole game? Considering you are awaiting on the main thread?

**Comment by RedworkDE** [comment]
That is the whole point of async, `await`ing will not block the thread, instead it can continue doing other stuff.
