### ISSUE TITLE
Crashed when working on AnimationTree

### ISSUE THREAD

**Issue by Pat4yczek** [godotengine/godot#79172]
### Godot version

4.1.stable.mono

### System information

Linux Mint 21.1 Cinnamon, 4.1.stable.mono, Mobile

### Issue description

During workin on animationTree, is some cases like playing animation state or updade some data, engine freezes, after a moment program iis shut down.

### Steps to reproduce

Crash was happened during development 2d game with sprite anmation on mobile settings.
game engine is located in /usr/local/bin
for animation i used [animation_lib]/Array(top/down/left/right) organization
just do some top, down, left, right animation, save as idle, attack and move lib, next upload them

### Minimal reproduction project

; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="IAmNinja2d"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.1", "Mobile")
config/icon="res://icon.svg"

[dotnet]

project/assembly_name="IAmNinja2d"

[input]

up={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":87,"key_label":0,"unicode":119,"echo":false,"script":null)
]
}
down={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":83,"key_label":0,"unicode":115,"echo":false,"script":null)
]
}
left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"key_label":0,"unicode":97,"echo":false,"script":null)
]
}
right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"key_label":0,"unicode":100,"echo":false,"script":null)
]
}

[rendering]

textures/canvas_textures/default_texture_filter=3
renderer/rendering_method="mobile"

**Comment by akien-mga** [comment]
The contents of the `project.godot` file which you pasted in this issue do not consistent a minimal reproduction project, that's just an empty Godot project with no AnimationTree.

I'm assuming this is the same bug as #79012 though, so closing as duplicate.
