### ISSUE TITLE
Windows Defender classifies 4.1 zip file as virus

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot#79170]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11 Home 64-bit (build 22621.1848 with experience pack 1000.22642.1000.0)

### Issue description

Trying to use the official download from the website results in windows defender putting the file into quarantine. This was reported at least 5 times today on discord, so I made an issue for this even though I don't use windows myself.

**Example 1**
This is the error that one of the users encountered:
> Unzipping was not a problem and i started the editor. Defender complained much later ... which i find strange[...]
> 
> I have just scanned my entire system with Defender and i have explicitly scanned the two files in the Godot folder - negative, no trojans detected. I also checked it with the virus total site - no trojans found. So it seems that something with the .zip file was weird, that is the one that Defender complained about later, the system has deleted the file

![windows_defender](https://github.com/godotengine/godot/assets/44872771/6ccf723c-2ebd-4110-8f45-e17bafdc1393)

**Example 2**
Another user extracted the file using 7zip (I think), and got this error directly during extraction:

![windows_7zip](https://github.com/godotengine/godot/assets/44872771/77bf70ad-ddbc-470c-b19f-31622ec0a1d3)

### Steps to reproduce

1. Download <https://github.com/godotengine/godot/releases/download/4.1-stable/Godot_v4.1-stable_win64.exe.zip>
2. Extract zip file
3. Run Godot (probably not needed to reproduce the issue)

### Minimal reproduction project

N/A

**Comment by pietru2004** [comment]
I gona add to this that I got this and after that I have checked zip with virus total, and it showed this - all green, might be windows defender error
![obraz](https://github.com/godotengine/godot/assets/51274570/d7de9fd4-bafe-47dd-9979-f83ebe5bfebf)

**Comment by winston-yallow** [comment]
I'm pretty confident it's a false positive. The question mostly is how can we prevent it?
- Is there a way to submit false positives to microsoft? A quick google search seems to suggests there is no way
- Can we build the zip so that the heuristic doesn't detect it? Sometimes it's just a specific byte sequence, so it may be enough to change the compression ratio of the zip file. I don't have windows though, so I can't test this approach.

**Comment by gmjosack** [comment]
I run into this regularly and submitting the file being detected to https://www.microsoft.com/en-us/wdsi/filesubmission/ usually results in it being removed as a false positive.

**Comment by YuriSizov** [comment]
For what it's worth, this is not a widespread issue (personally, it doesn't trigger anything for me, also on Windows 11). Though I have seen several mentions on Discord today.

Submitting this to MS is the way to go. The executable itself is digitally signed with an EV certificate, which Windows should already let through without any warnings.

**Comment by gmjosack** [comment]
In my experience with new releases you see mixed reports based on when people last had the local definitions updated so if it's in the latest versions you can start to see more reports over time.

**Comment by winston-yallow** [comment]
Do we have some microsoft Software Assurance ID (SAID) to submit this as software developer for faster evaluation?
I've already submitted it using my private account, but it says that it may take some time.

**Comment by winston-yallow** [comment]
Got a response from Microsoft:

![image](https://github.com/godotengine/godot/assets/44872771/5e7b3a39-8ff2-42b6-8399-2f3f1060a5d6)

It should not be detected as malware anymore.
