### ISSUE TITLE
Subviewport/TextureButton generate editor errors on re-open only if scene is instanced in another scene

### ISSUE THREAD

**Issue by wlsnmrk** [godotengine/godot#79176]
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3640)

### Issue description

With the following scene structure:

- Containing Scene
    - Main 3D Scene
    - Subviewport
        - Another 3D Scene
    - UI control container
        - TextureButton referencing the Subviewport via a ViewportTexture

If the containing scene is itself instanced as a child of another scene within the project, and that other scene is open, closing and re-opening the containing scene will generate several errors of the form `scene/main/viewport.cpp:143 - Viewport Texture must be set to use it.` If the button is visible, the editor will also generate infinite errors of the form

```
Texture (binding: 0) should provide one ID referencing a texture (IDs provided: 0).
drivers/vulkan/rendering_device_vulkan.cpp:7208 - Condition "!uniform_set" is true.
```

Additionally, the TextureButtons will not display the viewport contents.

These errors do not appear, and the TextureButtons will display correctly, if the containing scene is not instanced in another scene in the project, or if the scene in which the containing scene is instanced is not currently open.

May (?) be related to #66247 and/or #69469.

### Steps to reproduce

1. Reproduce the scene structure as described above, or open the attached MRP
2. If the scene instancing the containing scene (`main.tscn` in the attached MRP) is not open, open it
3. If the subviewport/button's containing scene (`game_screen.tscn` in the attached MRP) is not open, open it
4. Close the containing scene
5. Open the containing scene
6. If necessary, select a UI control node to make the button visible.

### Minimal reproduction project

`game_screen.tscn` is the containing scene for the Subviewport and TextureButton. `game_screen.tscn` is instanced as a child of `main.tscn` in `SubviewportBug.zip`. Closing and reopening `game_scene.tscn` in the version from `SubviewportBug.zip` generates errors as described above, until the editor is restarted or an entirely new ViewportTexture is assigned to the button.

In `SubviewportBugNoError.zip`, `game_screen.tscn` is not instanced as a child of any other scene. Closing and reopening `game_scene.tscn` in this version does not generate errors.

Alternatively, close `main.tscn` in the `SubviewportBug.zip` version, and closing and reopening `game_scene.tscn` will not generate errors.

[SubviewportBug.zip](https://github.com/godotengine/godot/files/11986495/SubviewportBug.zip)
[SubviewportBugNoError.zip](https://github.com/godotengine/godot/files/11986496/SubviewportBugNoError.zip)

**Comment by Rindbee** [comment]
After applying #79201, I followed the steps and couldn't reproduce it in MRP. Can you still follow the steps to reproduce?

If additional steps are required to reproduce, please provide steps or projects to reproduce the cases that #79201 does not resolve.

**Comment by wlsnmrk** [comment]
Yes I can, no additional steps necessary - just close and open `game_scene.tscn` a few times. If you're trying to reproduce, it happens more quickly and frequently when launched from the debugger (but the attached video is with the bare exe, no debugger).


https://github.com/godotengine/godot/assets/23439518/4e97d2a7-eadd-4dc8-9a6b-6d0398a7763e

**Comment by wlsnmrk** [comment]
I left a comment on the PR, but wanted to follow up over here and confirm that, after some changes, #79201 does appear to fix this issue.
