### ISSUE TITLE
Passing function as arguments?

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#7918]
**Operating system or device - Godot version: Windows 10, Godot 2.1.2 stable **

Is it possible to pass functions through variables?

Similar as in Javascript like this:

var MakeRain = function MakeRain(){
  bunchOfCodesToMakeRain();
}

Map(MakeRain);

-----

Inside the Map:

function Map(dosomething)
{
  dosomething() //which will cast MakeRain, or any function.
}

Is this possible in Godot? Sending function as arguments.

**Comment by akien-mga** [comment]
Please note that this issue tracker is for... issues, i.e. bugs or feature requests :)

For general support question you should use the Q&A, which happens to have the answer for your question: https://godotengine.org/qa/2551/function-calling-using-dictionaries?show=2562#a2562
