### ISSUE TITLE
When building version 4.1mono of Godot: Unable to find the specified SDK 'Godot. NET. Sdk/4.1.0'

### ISSUE THREAD

**Issue by baimao01** [godotengine/godot#79188]
### Godot version

4.1.stable

### System information

Godot v4.1.stable.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 2000 (SNB GT1) () - Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 Threads)

### Issue description

The following three messages appear during construction:
1.warning: Unable to load the service index for source https://api.nuget.org/v3/index.json.
2.error: Unable to find package Godot.NET.Sdk. No packages exist with this id in source(s): nuget
3.error: Unable to find the specified SDK 'Godot. NET. Sdk/4.1.0'.

### Steps to reproduce

1.Create a renderer as a compatible project and add C # scripts.
2.Press the build button in the upper right corner.

### Minimal reproduction project

Only one scene with one node with just one empty C# script

**Comment by raulsntos** [comment]
Are you able to restore packages in a non-Godot C# project? Judging from the warning you are getting about being unable to load the service index for NuGet.org, it seems like you have a broken NuGet configuration or connectivity issues.

Try adding a new `NuGet.config` file to the project (same folder that contains the `project.godot` file). You can create this configuration file with the `dotnet new nugetconfig` command, it should contain this configuration:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

Then try restoring packages again. If it still doesn't work, can you share the contents of the NuGet configuration file at `$HOME/.nuget/NuGet/NuGet.Config`? Also any files that may exist in the `$HOME/.nuget/NuGet/config` directory.

Also, are you using the [Azure Artifacts Credential Provider](https://github.com/Microsoft/artifacts-credprovider)?

**Comment by RedworkDE** [comment]
- See also #58955

**Comment by baimao01** [comment]
> Then try restoring packages again. If it still doesn't work, can you share the contents of the NuGet configuration file at $HOME/.nuget/NuGet/NuGet.Config? Also any files that may exist in the $HOME/.nuget/NuGet/config directory.

This is my `Nuget.Config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

There are several files in my `$HOME/.nuget/NuGet/config directory` directory:
.
├── config
│   └── Godot.Offline.Config
└── NuGet.Config

I am not using the [Azure Artifacts Credential Provider](https://github.com/Microsoft/artifacts-credprovider).

**Comment by baimao01** [comment]
I have resolved this issue because I did not install the `fastgithub` certificate in the system
