### ISSUE TITLE
Editor crashes silently while loading project

### ISSUE THREAD

**Issue by LasseSchnepel** [godotengine/godot#79186]
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3179) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

When I load my project, I see a blank editor window (sometimes with the Godot logo, sometimes without), the windows progress bar iterates over several scenes that need to be opened. It then stops at my main scene, gets unresponsive and stays there for a while.
Then Godot closes silently. When opened from the console, I see the following error (written very often):
`ERROR: Failed method: EditorToaster::_error_handler_impl. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.
   at: push_callablep (core/object/message_queue.cpp:96)`

### Steps to reproduce

I am not sure to what this relates, but it could a be C# [Tool] script that creates ~1200 voxels in _Ready (I could accept that this is not working, but I don't like the silent crash.). Starting the game works without issues though.

As I did not change this code for a while (and the editor startup was slow but worked), I assume there's something else accumulating. I just know that the editor starts when I disable the creation of the voxels, but tbh, I don't think this is the root cause.

### Minimal reproduction project

wasn't able to create a mrp

**Comment by LasseSchnepel** [comment]
PS: The editor is also starting when I set my voxel-creating node to operate in a subthread.

**Comment by Zireael07** [comment]
Your voxel script likely has many errors (maybe some API changes) that fill up the message queue

**Comment by LasseSchnepel** [comment]
It does not throw any errors when I run the game, nor does it show any errors when running in subthread. The error mentioned above is something with TCP, which I suppose is related to the subthreads (as I never touch anything with TCP in my script). But yes, it might be that my script causes some errors, but I would be happy if the editor would show them to me (or atleast they appear in some log)

**Comment by Sauermann** [comment]
Without any more details, it will be impossible to investigate this. Please try to create a MRP and upload it.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the above required information this can be reopened
