### ISSUE TITLE
Calling force_draw from a thread crashes compatibility renderer

### ISSUE THREAD

**Issue by WantToSignUp** [godotengine/godot#79190]
### Godot version

v4.1.stable.official.970459615

### System information

Windows 10 OpenGL API 3.3.0

### Issue description

Calling force_draw from a thread crashes compatibility renderer. Not sure if bug or this is not something that we should be doing, but it seems to not cause any issue with mobile/desktop forward+ renderer. Reason why i do this because it lets the engine run at a higher frame rate than the renderer.

### Steps to reproduce

🧵

### Minimal reproduction project

[forcedraw.zip](https://github.com/godotengine/godot/files/11988748/forcedraw.zip)

**Comment by clayjohn** [comment]
Calling "force_draw" from a thread other than the main thread isn't supported. This should be better documented.
