### ISSUE TITLE
On Android, the tr() function cannot translate keywords with chinese characters or japanese characters in the csv file

### ISSUE THREAD

**Issue by Dukethomas** [godotengine/godot#79192]
### Godot version

3.5.2

### System information

Android 11

### Issue description

on android device, the tr() function cannot translate the keywords with chinese characters or japanese characters in the CSV file

### Steps to reproduce

this project has a csv file with some keywords like this,
id,en,ja,zh_CN
KEY_TEST_1,Test 1,テスト 1,测试 1
KEY_测试_2,Test 2 ,テスト 2,测试 2
KEY_テスト_3,Test 3,テスト 3,测试 3
I use tr() function to translate, this function works fine on Windows.
but i export it to Android, the keywords with chinese characters and japanese characters will not be translated.

### Minimal reproduction project

[TranslationTesting.zip](https://github.com/godotengine/godot/files/11990085/TranslationTesting.zip)
[translation_testing_project.zip](https://github.com/godotengine/godot/files/11990087/translation_testing_project.zip)

**Comment by Zireael07** [comment]
Are you sure this is a translation problem and not a display problem? (The fallback font mechanism for CJK characters is wonky on Android)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77903.
