### ISSUE TITLE
Build error: ELF section name out of range

### ISSUE THREAD

**Issue by br3eze** [godotengine/godot#79193]
### Godot version

4.03, 4.1

### System information

Linux Arch

### Issue description

The same for GCC and LLVM 

![image](https://github.com/godotengine/godot/assets/5236855/9dde0d66-49fb-4908-a14d-be2c138e3443)

The second try after the error:

scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Linking Static Library modules/libmodule_astcenc.linuxbsd.editor.x86_64.a ...
[Initial build] Ranlib Library modules/libmodule_astcenc.linuxbsd.editor.x86_64.a ...
[Initial build] ranlib: modules/libmodule_astcenc.linuxbsd.editor.x86_64.a: malformed archive

### Steps to reproduce

Output:
Building for platform "linuxbsd", architecture "x86_64", target "editor"

### Minimal reproduction project

git clone --depth 1 https://github.com/godotengine/godot -b 4.0.3-stable 
or 4.1 branch

**Comment by Calinou** [comment]
Try cleaning all build files: `git clean -dfxi`

**Comment by br3eze** [comment]
@Calinou Same

**Comment by br3eze** [comment]
Does anybody know **ANY** workaround for this? It ruins all..
Please share.

**Comment by capnm** [comment]
> Does anybody know **ANY** workaround for this? It ruins everything.. Please share.

Maybe it's some hardware issue (RAM, HD) :thinking:. Try building it on an external hard drive or disabling the scons cache .

Or clone the the repo with
```
git clone https://github.com/godotengine/godot
git checkout origin/4.1 -b 4.1
```
etc...

**Comment by akien-mga** [comment]
Yes check that you're not running out of disk space in either your `$HOME` and the partition where you're compiling Godot.

If that's not disk space, then it sounds like memory corruption.

**Comment by Calinou** [comment]
I suggest running a [Memtest](https://memtest.org/) on your machine.

**Comment by br3eze** [comment]
- not disk space
- memtest86 showed green "passed"
- tried two ssd disks
- cache disabled

**Comment by br3eze** [comment]
At last, `badblocks -Bvsno` showed some issues on a brand new Samsung ssd! Can't say which files were involved, may be some libs.
Thanks everybody!
