### ISSUE TITLE
Input - key held down is not detected

### ISSUE THREAD

**Issue by rhighs** [godotengine/godot#79207]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 - Vulkan (Forward+) - dedicated AMD Radeon RX 6650 XT (RADV NAVI23) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Going through the demo tutorial for [player input](https://docs.godotengine.org/en/4.1/getting_started/step_by_step/scripting_player_input.html) I've stumbled upon a strange and unexpected `Input.is_action_pressed` behavior.

- Expected behavior: pressing and/or holding arrows Up, Left and Right should result in the sprite moving smoothly and consistently in the scene.
- Actual behavior: the sprite stutters occasionally and wont move at all when holding down keys. 

https://github.com/godotengine/godot/assets/37136851/93b020c9-14a3-4ca7-9a3b-07b1332a3c55

### Steps to reproduce

The code below seems to not detect keys being held down but rather detects them only in the first few frames.

Demo code:
```GDScript
extends Sprite2D

var speed = 400
var angular_speed = PI

func _init():
	pass

func _process(delta):
	var dir = 0
	if Input.is_action_pressed("ui_left"):
		dir = -1
	if Input.is_action_pressed("ui_right"):
		dir = 1

	var velocity = Vector2.ZERO
	if Input.is_action_pressed("ui_up"):
		velocity = Vector2.UP.rotated(rotation) * speed

	rotation += angular_speed * delta * dir
	position += velocity * delta
```

Print debugging code:
```GDScript
extends Sprite2D

var movedir = Vector2()
var speed = 100

func _process(delta):
	var LEFT = Input.is_action_pressed("ui_left")
	var RIGHT = Input.is_action_pressed("ui_right")
	var UP = Input.is_action_pressed("ui_up")
	var DOWN = Input.is_action_pressed("ui_down")

	movedir.x = -int(LEFT) + int(RIGHT)
	movedir.y = -int(UP) + int(DOWN)
	print(movedir)

	movedir = movedir * delta * speed
```

### Minimal reproduction project

Reference godot project: 
[SampleRotations.tar.gz](https://github.com/godotengine/godot/files/11990882/SampleRotations.tar.gz)

Open this project and start playing right away.

**Comment by rhighs** [comment]
Nevermind, I might have found the issue... I had my Dualshock 4 plugged in and nplugging it solved the issue. That still keeps me wondering if this is the expected behavior though. I'll keep this open in case someone has word to say on this.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/45628.
