### ISSUE TITLE
Bad collision against StaticBody2D with LineShape2D

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7920]
**Ubuntu 16.10 - Godot 2.1.2 stable**

**Issue description:**
A StaticBody2D with a LineShape2D get incorrect collision against other bodies (or bodies against the static line).

It was expected to get collisions checked against full shapes, not just the "lower" part.

**Steps to reproduce:**

 - Create a StaticBody2D with a horizontal LineShape2D, like a floor.
 - Create a RigidBody2D with a CircleShape2D over the line, rotate it a bit. 
 - Look how the RigidBody2D hangs below the line.

Happens with other shapes against a line.

![lineshapebug](https://cloud.githubusercontent.com/assets/10215987/23488124/6905559a-fec9-11e6-8b70-f15a513609a5.gif)

**Link to minimal example project:**
[StaticLineBug.zip](https://github.com/godotengine/godot/files/812469/StaticLineBug.zip)

**Comment by bojidar-bg** [comment]
Are you sure it isn't a feature? :wink:

**Comment by RebelliousX** [comment]
@bojidar-bg I was thinking the same way. That dangling Godot is priceless lol.

**Comment by eon-s** [comment]
Affects master too.

Project for Godot 3:
[StaticLineBugV3.zip](https://github.com/godotengine/godot/files/1465236/StaticLineBugV3.zip)

**Comment by eon-s** [comment]
Still valid for 3.0.2 or current master.

**Comment by eon-s** [comment]
@MutantOctopus you mean this #9332?

**Comment by MutantOctopus** [comment]
Maybe, but not exactly. In my own experience I've had no problems with *moving away* from the line - but so long as you hold *toward* the line, the KB keeps jittering as if it keeps getting pushed away. It's probably related.

**Comment by eon-s** [comment]
I would like confirmation if this is a bug or a feature (like with Plane), in the case of being the intended behavior this will need to be documented.

**Comment by reduz** [comment]
LineShape2D will most likely be removed in 3.2/4.0 due to difficulty in using it with other phyisc engine and everything in general.

**Comment by Xrayez** [comment]
I confirm I've stumbled upon this some time ago in 3.2, that's why I don't use this currently. 😕

**Comment by capnm** [comment]
> #42532 is there to fix this.

Indeed the patch fixes it. It took over 3 years to wait for a single line of code.
(We know why it's called Godot ;-)
