### ISSUE TITLE
Rotating 2D object in animation causes rotation to tare out

### ISSUE THREAD

**Issue by aberizrihays** [godotengine/godot#79219]
### Godot version

4.1.0

### System information

Linux 64-bit (Garuda/Arch)

### Issue description

When animating in 2D, I rotated an object and keyed it, but then the editor reset the rotation angle to 0, but kept the actual rotation. This is not only throwing off the rotation, but the positioning, too.

![Screenshot_1](https://github.com/godotengine/godot/assets/122324046/569765af-2698-4376-8ec3-09eb5df1596a)
![Screenshot_2](https://github.com/godotengine/godot/assets/122324046/3a53cfd8-8ca4-47fe-9028-aad8fabd2f2c)
![Screenshot_3](https://github.com/godotengine/godot/assets/122324046/d1740378-9fe4-4198-85f1-71e9e35e21da)

### Steps to reproduce

I haven't been able to reproduce it, but I also haven't been able to undo it.

What hasn't worked:
1. Turning it off and back on again
2. Right-click the object
3. Right-click drag the object
4. Right-click the rotation
5. Deleting and re-creating the same object (in this case, CollisionShape2D)
6. Disabling
7. Enabling One-Way Collision

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/11992232/BugReport.zip)

I kept the spiders just because the malfunctioning piece in question is a hitbox. One hit should kill them.

**Comment by kleonc** [comment]
No bug in here, that's a user error. The parent of the mentioned CollisionShape2D is rotated, hence the CollisionShape2D remains rotated if its own rotation is zero etc.
![Godot_v4 1-stable_win64_dgwL2R3bUN](https://github.com/godotengine/godot/assets/9283098/ec1a514c-835c-4df2-b6c6-54394d1b66a6)
![Godot_v4 1-stable_win64_h3J1wrZsX3](https://github.com/godotengine/godot/assets/9283098/b0dc2dd1-9f2d-493e-b831-56fc8e57bf50) ![Godot_v4 1-stable_win64_xfU2jLzqpO](https://github.com/godotengine/godot/assets/9283098/159434fe-3a41-4db6-a516-22c577e6cccc)
