### ISSUE TITLE
Make editor dialogs resizable and store their bounds

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#7921]
Since `WindowDialog`s can be resized now, the Editor dialogs should be made resizable and their location and size stored upon closing them, restoring it upon opening again (of course inside valid bounds).

Helps a bit against https://github.com/godotengine/godot/issues/6437
Obsoletes https://github.com/godotengine/godot/pull/7543

**Comment by bojidar-bg** [comment]
Closing as done (use `Closes #....` next time).
