### ISSUE TITLE
Shader and node instancing unexpected interaction

### ISSUE THREAD

**Issue by motizukilucas** [godotengine/godot#79224]
### Godot version

4.0.2.stable

### System information

MacOS Ventura

### Issue description

When animating a node with Sprite2D and a custom shader effect, the animation will play for all instanced nodes, while other layers of the same animation will play for the particular node

Setup a timer that will play the animation when time left for that instance is lower than 5, as soon the animation triggers shader is supposed to blink white, and then alternate between sprite visible and not visible. Shader will blink on all instances at the same time, but the visibility will alternate for the one which is supposed to

Shader code:

    shader_type canvas_item;
    
    uniform vec4 flash_color : source_color = vec4(1.0);
    uniform float flash_modifier : hint_range(0, 1);
    
    void fragment() {
	    vec4 color = texture(TEXTURE, UV);
	    color.rgb = mix(color.rgb, flash_color.rgb, flash_modifier);
	    COLOR = color;
    }
  

### Steps to reproduce

Mob node:
- Sprite2D (with shader)
- Timer
- AnimationPlayer

      extends Area2D
      
      @onready var anim_player = $AnimationPlayer
      @onready var timer = $Timer
      
      func _ready():
	      timer.timeout.connect(timeout)
      
      func _process(delta):
	      if timer.get_time_left() < 5:
		      anim_player.play("new_animation")
      
      func timeout():
	      queue_free()

World for instancing mobs:
- Timer

      extends Node2D
      
      @onready var timer = $Timer
      
      @onready var areaScene = preload("res://area_2d.tscn")
      
      @onready var spawn_x_axis = get_viewport_rect().size.x/4
      @onready var spawn_y_axis = get_viewport_rect().size.y/4
      
      # Called when the node enters the scene tree for the first time.
      func _ready():
	      timer.timeout.connect(spawn)
      
      func spawn():
	      var minion = areaScene.instantiate()
	      add_child(minion)
	      minion.position = Vector2(randf_range(spawn_x_axis, get_viewport_rect().size.x-spawn_x_axis), randf_range(spawn_y_axis, get_viewport_rect().size.y-spawn_y_axis))

### Minimal reproduction project

[shader_bug.zip](https://github.com/godotengine/godot/files/11992562/shader_bug.zip)

**Comment by AThousandShips** [comment]
Can you test this on 4.0.3 or 4.1?

**Comment by motizukilucas** [comment]
> Can you test this on 4.0.3 or 4.1?

Just tested it on 4.1.stable, and got same behavior

**Comment by clayjohn** [comment]
Are the various instances sharing a material? Remember that materials are resources, not nodes, so they are shared by all nodes that reference them. If you animate a shader uniform, then all nodes sharing that material will be affected.

**Comment by motizukilucas** [comment]
> Are the various instances sharing a material? Remember that materials are resources, not nodes, so they are shared by all nodes that reference them. If you animate a shader uniform, then all nodes sharing that material will be affected.

Yep, that's it

I have a node with Sprite2D and added a shader material to it

Then I created several copies of that node in another one

Well, I see that's something supposed to happen, but yet that's a bit counter intuitive with instancing, how should we have several copies of one node with shader material, that won't affect copies it is not supposed to?

**Comment by clayjohn** [comment]
Use the ``set_local_to_scene`` flag on the resource that you want to not be shared between different instances of the same scene https://docs.godotengine.org/en/latest/classes/class_resource.html#class-resource-property-resource-local-to-scene

**Comment by motizukilucas** [comment]
> Use the `resource_local_to_scene` flag on the resource that you want to not be shared between different instances of the same scene https://docs.godotengine.org/en/latest/classes/class_resource.html#class-resource-property-resource-local-to-scene

Added this property to packed scene but still I see same behavior

Maybe I'm using it wrong 

    extends Node2D
    
    @onready var timer = $Timer
    
    @onready var areaScene = preload("res://area_2d.tscn")
    
    @onready var spawn_x_axis = get_viewport_rect().size.x/4
    @onready var spawn_y_axis = get_viewport_rect().size.y/4
    
    # Called when the node enters the scene tree for the first time.
    func _ready():
	    timer.timeout.connect(spawn)
	    areaScene.resource_local_to_scene = true
	    areaScene.set_local_to_scene(true)
    
    func spawn():
	    areaScene.resource_local_to_scene = true
	    areaScene.set_local_to_scene(true)
	    print(areaScene.is_local_to_scene())
	    var minion = areaScene.instantiate()
	    add_child(minion)
	    minion.position = Vector2(randf_range(spawn_x_axis, get_viewport_rect().size.x-spawn_x_axis), randf_range(spawn_y_axis, get_viewport_rect().size.y-spawn_y_axis))

**Comment by clayjohn** [comment]
You need to set it on the resource that you want to be local to the scene, not on the scene itself. 

Additionally, the docs say to not set it at runtime. 

What you should do is check the tickbox in the material in the editor. When you select the material, the checkbox will be near the bottom of the material's properties, under the section titled "resource"

**Comment by motizukilucas** [comment]
> You need to set it on the resource that you want to be local to the scene, not on the scene itself.
> 
> Additionally, the docs say to not set it at runtime.
> 
> What you should do is check the tickbox in the material in the editor. When you select the material, the checkbox will be near the bottom of the material's properties, under the section titled "resource"

Cheers, it worked perfectly. Many thanks!

I would like to take this opportunity to clarify doubts about the usage of this property.

I saw packed scene in it's docs so I thought it was supposed to be used with this `areaScene = preload("res://area_2d.tscn")` for example. I understand that it is not meant to be set during runtime, but I wonder if I can set it programmatically someway.

Thanks again :)
