### ISSUE TITLE
Godot 4.1 "A number is required"

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#79241]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3168) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

When Godot starts it spams 40 timer a number is required error i tried in every project and it happenes in every project so that is not a project related issue.
![image](https://github.com/godotengine/godot/assets/78092286/a68135b3-065d-45e7-8cb1-e8107efca45f)

### Steps to reproduce

I opened godot
I opened a project
And it get that error

### Minimal reproduction project

null

**Comment by akien-mga** [comment]
Which language are you using for the Godot interface?

**Comment by NotRabug50** [comment]
> Which language are you using for the Godot interface?
gdscript

**Comment by Calinou** [comment]
> gdscript

akien-mga meant the editor written language, not the programming language :slightly_smiling_face:

**Comment by akien-mga** [comment]
I mean the speaking language :)
Inferring from your name I guess Turkish, with which I can reproduce the bug. There are a number of broken Turkish translations which can cause this error it seems.

Notably this one:
![image](https://github.com/godotengine/godot/assets/4701338/f03b381a-a9b1-4976-b56a-82188f6b71de)

The `%s` and `%d` from the English original shouldn't be swapped, as the substitution will be wrong. If you speak Turkish, would you have a suggestion for me to fix this translation by keeping `%s` first? An example with the substitutions would be "Set Position on 5 nodes".

**Comment by NotRabug50** [comment]
"%d düğüm üzerinde %s ayarla " is better way to translate

**Comment by akien-mga** [comment]
Sadly that can't be used, `%s` must come before `%d` like in the English version. So it might need to be rephrased to use that order, even if that makes it sound more awkward in Turkish (we can't swap the position of placeholders currently).

**Comment by AThousandShips** [comment]
Worth working towards implementing that as that's a major limitation for translation

**Comment by NotRabug50** [comment]
Then you can make "%s ayarını %d düğüme uygula"

**Comment by NotRabug50** [comment]
> Worth working towards implementing that as that's a major limitation for translation

i think this caused by c++ godot team probably used printf() function to write messages to console

**Comment by AThousandShips** [comment]
It's an internal function we use so we can change it to allow index, just work to do

**Comment by akien-mga** [comment]
Thanks! I fixed that translation on Weblate (and a few others which wrong changed `%s` to `% s`, as well as some which also had placeholders in the wrong order so I just marked them as "Needs editing" so translators review them again), and confirmed that it fixes the issue.

I'll sync translations with Weblate in coming days before the 4.1.1 RC 1 release, which should fix this.

**Comment by NotRabug50** [comment]
@akien-mga I changed the set to apply to make it look better, is that ok?

**Comment by akien-mga** [comment]
> @akien-mga I changed the set to apply to make it look better, is that ok?

Yes I used the translation you proposed above:

> %s ayarını %d düğüme uygula

**Comment by NotRabug50** [comment]
you're welcome, but if you want to get it exactly right, you can use "set %s to %d node". but I don't think Turkish people will misunderstand the translation

**Comment by akien-mga** [comment]
Thanks, I changed it. By the way if you're interested, you can also contribute to improve the Turkish translation on https://hosted.weblate.org/projects/godot-engine/godot/tr/

**Comment by NotRabug50** [comment]
yes I would love to help
