### ISSUE TITLE
Varying with default value in ShaderInclude trigger error

### ISSUE THREAD

**Issue by JonqsGames** [godotengine/godot#79240]
### Godot version

4.1

### System information

Windows 10

### Issue description

Trying to have a varying with default value in a ShaderInclude.
![image](https://github.com/godotengine/godot/assets/6182189/11444abf-7d94-42a5-a5dc-b58f4f138e46)
I wanted to define my light function to be shared by multiple shaders and need to pass a value using varying.
If do not set a value the ShaderInclude produce an error (varying need to be set in vertex or fragment)

Not sure if what i want to do is allowed but i see two possible solution:
- ShaderInclude should not trigger the error regarding if the varying is properly set, this is only the responsability of the final shader
- The error mentionned should not occured and allowing a default value for varying in ShaderInclude

**Note:**
_I was planning on fixing it myself but may need feedback on the best solution to choose_

### Steps to reproduce

Create a ShaderInclude with a 'varying' and give it a default value.

### Minimal reproduction project

[VaryingShaderInclude.zip](https://github.com/godotengine/godot/files/11995146/VaryingShaderInclude.zip)

**Comment by clayjohn** [comment]
I'm not sure that we even support default values for varyings in regular gd_shader files. Varyings need to be initialized in the vertex or the fragment function

**Comment by JonqsGames** [comment]
Not sure of the effect but i was using default value to avoid error during my tests and it worked in gd_shader.
Make sense if it's not allowed but could we allow ShaderInclude to unsafely use varying that are not initialized or is it a bad idea at all ?

**Comment by clayjohn** [comment]
> Not sure of the effect but i was using default value to avoid error during my tests and it worked in gd_shader. Make sense if it's not allowed but could we allow ShaderInclude to unsafely use varying that are not initialized or is it a bad idea at all ?

It's a bad idea as it is unsupported by GLSL. The GLSL shader compiler will fail instead and give the user a much more cryptic error than what we provide. In such cases, it is much better for users for us to aggressively enforce the GLSL specification, even if it feels limiting

**Comment by JonqsGames** [comment]
Thanks for the answer, i found a "workaround" by changing my light to function and implement the light in each shader calling that. A bit of a hassle to have to bind built-in property from light into my function but it works.
