### ISSUE TITLE
clampf and clampi not working properly

### ISSUE THREAD

**Issue by Berke-aras** [godotengine/godot#79256]
### Godot version

4.1

### System information

windows11 - Godot4.1

### Issue description

clampf and clampi always giving a  max value

### Steps to reproduce

**print(clampf(5, 15, 4))**

### Minimal reproduction project

A small Godot project only background and player 

**### Player code:**

`extends CharacterBody2D

var speed = 300

func _physics_process(delta):
	velocity = Vector2(0,0)
	if Input.is_action_pressed("player_right"):
		velocity.x = speed
	if Input.is_action_pressed("player_left"):
		velocity.x = -speed
	if Input.is_action_pressed("player_up"):
		velocity.y = -speed
	if Input.is_action_pressed("player_down"):
		velocity.y = speed 
	
	move_and_slide()
	#print(velocity)
	#print(global_position)
	
	#print(get_viewport_rect().size)
	
	var screen_size = get_viewport_rect().size
	
	if global_position.x < 0:
		global_position.x = 0
	if global_position.x > screen_size.x:
		global_position.x = screen_size.x

	if global_position.y < 0:
		global_position.y = 0
	if global_position.y > screen_size.y:
		global_position.y = screen_size.y

	print(clampf(5, 15, 4))
`

**Comment by KoBeWi** [comment]
The argument list is `value, min, max`. Try with `clampf(5, 4, 15)`.

**Comment by Berke-aras** [comment]
yeah it's working. My fault :/
