### ISSUE TITLE
Issue migrating projects created on Windows to Linux; related to casing

### ISSUE THREAD

**Issue by PersonGuyGit** [godotengine/godot#79251]
### Godot version

3.5.2

### System information

Debian Linux 11 "bullseye" bash - Godot 3.5.2

### Issue description

Our team and I are migrating our Godot Project that was created on Windows to our Linux server builds as well as Linux PC's used for development.

We have noticed issues related to missing dependencies, scattered throughout the entire project when we open our original windows based project, on a Linux machine. We have not experienced this issue on our Mac that we use for testing.

What is the desired casing standard, for working with cross-platform projects such as ours?

Here is an example of our error log. 

```
Godot Engine v3.2.3.stable.custom_build - https://godotengine.org/
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 4080 Laptop GPU/PCIe/SSE2

ERROR: load_interactive: Cannot open file 'res:[//Screens/MenuScreen.tscn](https://screens/MenuScreen.tscn)'.
   At: scene/resources/resource_format_text.cpp:1228.
ERROR: _load: Failed loading resource: res:[//Screens/MenuScreen.tscn](https://screens/MenuScreen.tscn). Make sure resources have been
imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:278.
ERROR: remove_scene: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   At: editor/editor_data.cpp:567.
ERROR: load_interactive: Cannot open file 'res:[//UserInterface/But_ChangeScene.tscn](https://userinterface/But_ChangeScene.tscn)'.
   At: scene/resources/resource_format_text.cpp:1228.
ERROR: _load: Failed loading resource: res:[//UserInterface/But_ChangeScene.tscn](https://userinterface/But_ChangeScene.tscn). Make sure resources
 have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:278.
ERROR: load_source_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:829.
ERROR: load: Cannot load source code from file 'res:[//Screens/MenuScreen.gd](https://screens/MenuScreen.gd)'.
   At: modules/gdscript/gdscript.cpp:2286.
ERROR: _load: Failed loading resource: res:[//Screens/MenuScreen.gd](https://screens/MenuScreen.gd). Make sure resources have been im
ported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:278.
ERROR: load_interactive: Cannot open file 'res:[//UserInterface/Title.tscn](https://userinterface/Title.tscn)'.
   At: scene/resources/resource_format_text.cpp:1228.
ERROR: _load: Failed loading resource: res:[//UserInterface/Title.tscn](https://userinterface/Title.tscn). Make sure resources have been
 imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:278.
```

### Steps to reproduce

To reproduce this error, we have opened our windows based project, on a Linux machine (either Debian or Manjaro).

### Minimal reproduction project

[bcirpg_mainMenu_20220220A.zip](https://github.com/godotengine/godot/files/11995904/bcirpg_mainMenu_20220220A.zip)

**Comment by quinnyo** [comment]
Have you tried opening the project again? From the error message: "Make sure resources have been imported by opening the project in the editor at least once."

Your log has a different version number (v3.2.3.stable.custom_build) to the one you listed (3.5.2) -- maybe something else has gone wrong?

From [the docs](https://docs.godotengine.org/en/stable/tutorials/best_practices/project_organization.html#style-guide) re: filenames:

> Use *snake_case* for folder and file names (with the exception of C# scripts). This sidesteps case sensitivity issues that can crop up after exporting a project on Windows.

**Comment by akien-mga** [comment]
You can use any case, but you need to be consistent. On a case sensitive system like Linux, `res://scene.tscn` and `res://Scene.tscn` would be two different paths.

**Comment by Calinou** [comment]
This isn't an issue Godot can resolve – Windows and macOS are case-insensitive, but Linux is case-sensitive. See the [Case sensitivity](https://docs.godotengine.org/en/latest/tutorials/best_practices/project_organization.html#case-sensitivity) section in the Project organization page for details, and what you can do to prevent this in the future.

> We have not experienced this issue on our Mac that we use for testing.

Recent macOS versions use a case-insensitive filesystem by default.
