### ISSUE TITLE
Corner collision error, queue_free() doesn't work

### ISSUE THREAD

**Issue by devmark404** [godotengine/godot#79259]
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.14046.0) - AMD Ryzen 7 7700 8-Core Processor (16 Threads)

### Issue description

Corner collision error, queue_free() doesn't work

When an object collides by the corners and it is tried to delete the object is not deleted

However, if it shows that the collision was done when I display the node in console

Here's an example where I pause the game at the time the collision takes place and the object should have already been destroyed

But it only works when it doesn't collide around the corners

Video Demo
[https://youtu.be/U1sOE1APkdI](url)

File
[ArkanoidRB.zip](https://github.com/godotengine/godot/files/11996094/ArkanoidRB.zip)

**Español**
Error al colisionar por las esquinas, no funciona queue_free() 

Cuando colisiona un objeto por las esquinas y se trata de eliminar el objeto no se elimina

Sin embargo, si se muestra que se hizo la colisión, cuando muestro el nodo en consola

Aquí hay un ejemplo en el que pauso el juego en el momento que se realiza la colisión y el objeto ya debería haberse destruido

Pero solo funciona cuando no colisiona por las esquinas

### Steps to reproduce

Run the project in godot and press play
When the ball collides with a block it should do the following
- Show that I hit the block
- Delete the block
- Pause the project.

To unpause you just have to press up

The error occurs in that when it collides from the corners it only shows that it collided with the block and pauses the project. **And the block is not removed**

**-- Español**
Ejecutar el proyecto en godot y presionar play
Cuando colisiona la bola con un bloque debería hacer lo siguiente
- Mostrar que choco con el bloque
- Eliminar el bloque
- Pausar el proyecto.

Para quitar la pausa solo hay que presionar arriba

El error ocurre en que cuando colisiona por las esquinas solo muestra que choco con el bloque y pausa el proyecto. **Y no se elimina el bloque**

### Minimal reproduction project

Just run the project in godot and press play
[ArkanoidRB.zip](https://github.com/godotengine/godot/files/11996101/ArkanoidRB.zip)

**Comment by KoBeWi** [comment]
You have a bunch of invisible tiles in your map:

https://github.com/godotengine/godot/assets/2223172/7a4510d9-5cf5-4bca-ac2b-f6ba54c6d7ab

(I changed it to set modulate instead of freeing)
The visible tiles disappear if you hit the same spot twice. On first hit the ball bounces off invisible tile.
