### ISSUE TITLE
Controller Triggers stay pressed on Android

### ISSUE THREAD

**Issue by Insane-Owl** [godotengine/godot#79263]
### Godot version

4.1.stable

### System information

Android 12, OneUI 4.1, Galaxy S10e | Godot 4.1.stable

### Description
On Android, Controller Triggers once pressed, stay pressed until the game is restarted 

### Video:
On Windows - everything works as intended.
https://github.com/godotengine/godot/assets/78328941/ee7976ab-b35a-4f91-888b-f3774c42e1b0

On Android - Once a Trigger is pressed, it stays pressed (Inverted triggers is a separate issue).
https://github.com/godotengine/godot/assets/78328941/981b514a-1c17-4490-9313-f72d89dec4d4

### The Setup
Input Map
![Screenshot 2023-07-09 190118](https://github.com/godotengine/godot/assets/78328941/60bfb2c0-6aec-4981-a957-114a9d3fca8d)

Scene
![Screenshot 2023-07-09 190138](https://github.com/godotengine/godot/assets/78328941/b8b0c21a-d82b-4979-8328-f7f07ae9140a)
![Screenshot 2023-07-09 190131](https://github.com/godotengine/godot/assets/78328941/80a2424b-6d18-4a40-bb20-1bba0c4bfc3a)

Code
![Screenshot 2023-07-09 190148](https://github.com/godotengine/godot/assets/78328941/d4712bce-30d7-4783-afac-ebda410b5cf4)

### Steps to reproduce

1. Set up triggers in Input Map
2. Make them do anything...
3. Export to Android
4. Press the Trigger, and thing only happens once, even if pressed multiple times.

### Minimal reproduction project

[controller trigger test.zip](https://github.com/godotengine/godot/files/11996634/controller.trigger.test.zip)

**Comment by Calinou** [comment]
Which device model are you using on desktop and Android? Is it the same controller model on both platforms?

**Comment by Insane-Owl** [comment]
I've tested it using both an XBox Series controller, and the 8BitDo Pro 2. The staying-pressed issue persists with both controllers, however it seems only the XBox controller has the Inverted Triggers problem (LT being RT, and RT being LT).

**Comment by Calinou** [comment]
The swapped triggers issue on an Xbox controller was already reported in https://github.com/godotengine/godot/issues/56181.

**Comment by Insane-Owl** [comment]
Thanks. I updated the post.

**Comment by johnnyw** [comment]
I've observed this bug on Android using an Xbox One X Bluetooth controller. The game in question was built with Godot 3.5.

I'd be interested in tackling this but I'm not sure where to start. I was looking around [here](https://github.com/godotengine/godot/blob/bc88dca176cef6b8943ded58c68a60f7c127baea/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L121) but I couldn't discern if the triggers are being treated differently from the other buttons in some way.

**Comment by johnnyw** [comment]
I wrote a minimal sample project to supplement the original one that displays the numerical joystick axis value for the R2 trigger. On PC it goes from 0 to 1 as expected. On Android, after the initial event trigger, it stays stuck with both a continuous read in `_process` and motion events.

[TriggerTest.zip](https://github.com/godotengine/godot/files/12515832/TriggerTest.zip)

**Comment by johnnyw** [comment]
Found the culprit! The platform-agnostic input handler is indiscriminately adding 0.5 to the analog triggers: https://github.com/godotengine/godot/blob/75de1ca76871fdf7f5a9e081aa57ec0e33061107/core/input/input.cpp#L1120C7-L1120C7

Android's motion event for L2 and R2 already have a range from 0 to 1, so this conversion is not necessary on Android and ends up breaking the value.

https://developer.android.com/reference/android/view/MotionEvent#AXIS_RTRIGGER

> For a joystick, reports the absolute position of the right trigger control. The value is normalized to a range from 0.0 (released) to 1.0 (fully pressed).

**Comment by johnnyw** [comment]
In the meantime, I was able to workaround this bug by changing the threshold value in the input map to something higher than 0.5 (I settled on 0.7 for my title).

**Comment by KatieZeldaKat** [comment]
I'm using Godot 4.3 and this issue seems to still exist. The triggers rest at 0.5 and go to 1.0 when pressed.

**Comment by penggrin12** [comment]
4.4 dev7, dualshock 4, android 12. still present
