### ISSUE TITLE
SoftBody3D: face normals aren't fully recalculated every frame for lighting purposes.

### ISSUE THREAD

**Issue by James103** [godotengine/godot#79265]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

When a `SoftBody3D` is receiving light from a `DirectionalLight3D`, any faces that start out fully lit by a `DirectionalLight3D` remain fully lit by it, as if the face remained pointing at the `DirectionalLight3D` light source the entire time.

Similarly, any faces of a `SoftBody3D` that start out without any lighting from a `DirectionalLight3D` are never lit by that light source, as if the face was always pointing away from the `DirectionalLight3D` light source.

The net result is that in a scene with a `PlaneMesh`-shaped `SoftBody3D` and a `DirectionalLight3D`, where the `SoftBody3D` has a material applied which allows both sides to render, one side of the `SoftBody3D` is significantly darker versus the other side, regardless of the current deformation.

### Steps to reproduce

1. Unzip, import and edit the attached project.
2. Open `main.tscn` for editing.
3. Run the attached project for a few seconds.
4. Notice the incorrect lighting of the `SoftBody3D` by the `DirectionalLight3D`. Example screenshot attached: 
![image](https://github.com/godotengine/godot/assets/37945304/3fd8b039-96af-4dce-80ff-487b03d84c5d)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/11997692/test.zip)

**Comment by Calinou** [comment]
> face normals aren't fully recalculated

Are they even recalculated in the first place?

**Comment by James103** [comment]
The exact behavior I'm observing in the test setup attached in the original project after some deformation of a `SoftBody3D` can be described as follows:
* You might not notice it, but there are some relative differences in shading between adjacent faces on the same side, based on the angle between the faces. See attached screenshot for a better example.
* However, the overall brightness of a given face of the `SoftBody3D` does not change significantly over time (bright faces remain bright, dark faces remain dark).

The material is a standard 3D material with a solid white color, with the only change being Transparency -> Cull Mode: Disabled (and all other properties default).

![image](https://github.com/godotengine/godot/assets/37945304/afa98375-05da-4715-804f-e550bba96f94)

**Comment by viksl** [comment]
Well, unless there are some extra settings needed then I think I can confirm this on my side too.
I tried adding omnilight to see what happens there but it's not ok too as you can see below.
1. Front plane having light
![obrazek](https://github.com/godotengine/godot/assets/33526847/41fb1071-7477-4b5f-90a7-6da9bb403f78)
2. Back plane no idea what exactly is happening
![obrazek](https://github.com/godotengine/godot/assets/33526847/e34df4e8-8431-4042-b7cc-56675ff3f2f4)

**Comment by LucidTaZ** [comment]
I noticed that all else being equal, the initial rotation of the SoftBody3D node matters too. As @viksl mentions, it doesn't happen in the editor.

Running:
<img width="1264" alt="Screenshot 2023-11-10 at 11 19 08" src="https://github.com/godotengine/godot/assets/10195108/ead33480-8757-484f-940e-e63a4a55fc10">

Editor:
<img width="788" alt="Screenshot 2023-11-10 at 11 19 18" src="https://github.com/godotengine/godot/assets/10195108/cfa29c51-acf1-4bdf-8bc2-7adb21e5017e">

Godot version: v4.1.3.stable.official [f06b6836a]
System: MacBook Pro M2, Sonoma 14.1.1
Reproduction project: [SoftBody3D Lighting Issue Reproduction.zip](https://github.com/godotengine/godot/files/13318244/SoftBody3D.Lighting.Issue.Reproduction.zip)

**Comment by LucidTaZ** [comment]
I'm no expert on Godot's source code, but I took a look at [godot_soft_body_3d.cpp](https://github.com/godotengine/godot/blob/master/servers/physics_3d/godot_soft_body_3d.cpp#L166). It seems that the face normals are recalculated while the node normals are always zero vectors.

The method _is_ being called from `GodotSoftBody3D::solve_constraints`, but I can't find any caller of that method. That's probably where my Godot knowledge falls short, or the method isn't actually used.

**Comment by LucidTaZ** [comment]
![Screenshot 2024-01-12 at 13 05 58](https://github.com/godotengine/godot/assets/10195108/cc7c0fd0-a9f1-47e5-b584-17378bbc63c0)

After upgrading from Godot 4.1.3 to 4.2.1, I noticed that the reproduction I posted above yields the expected (correct) result. See screenshot above.

I then tried it on the reproduction project of the issue's author, where it seems to work as expected too:
<img width="1264" alt="Screenshot 2024-01-12 at 13 10 01" src="https://github.com/godotengine/godot/assets/10195108/b4260e7c-880d-426f-a250-eb739778d27a">

**Comment by akien-mga** [comment]
Thanks for testing! Closing as fixed in 4.2.
