### ISSUE TITLE
Version number in conversion prompt is 4.0 but might be current version, or 4.x

### ISSUE THREAD

**Issue by timkrief** [godotengine/godot#79276]
### Godot version

4.1.stable.flathub

### System information

Ubuntu 22

### Issue description

I'm converting my project and just caught the version 4.0 in _`"to work in Godot 4.0"`_ instead of current version. I'm not sure if it's intended but I feel like it would make more sense to have current version or just 4.x

![image](https://github.com/godotengine/godot/assets/14089949/03411389-c0c2-4527-8946-b1fdf348abe8)

### Steps to reproduce

Try converting a project to Godot 4 from Godot 3

### Minimal reproduction project

Default Godot 3 project opened with Godot 4

**Comment by AThousandShips** [comment]
This could be done by just writing "4.x", or using the defines in `core/version.h` to get the version number as a string, using `VERSION_BRANCH`

**Comment by akien-mga** [comment]
Just "Godot 4" is likely fine.
