### ISSUE TITLE
UWP exporting is broken, APPX generated files are invalid

### ISSUE THREAD

**Issue by panreyes** [godotengine/godot#79278]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

When exporting a Godot 3.5 game with the UWP template, the generated APPX file is broken.

Extracting the file and repackaging it with makeappx.exe solves it.

### Steps to reproduce

1. Create a Godot 3.5 project
2. Download the templates
3. Create a UWP export
4. Fill the required info for generating the appx
5. Click on Export and save it

The APPX generated file is invalid. This can be confirmed from the command line trying to sign it with signtool.

### Minimal reproduction project

N/A

**Comment by panreyes** [comment]
I have tried to patch it by using makeappx.exe but I could not solve unzipping without requiring 7z.exe and I did not found a method to delete safely the temporary directory I created:

In platform/uwp/export/export.cpp, before ```// Sign with signtool```
```
// Repackage it with makeappx if available
String makeappx_path = EditorSettings::get_singleton()->get("export/uwp/makeappx");
if (makeappx_path != String()) {
	if (FileAccess::exists(makeappx_path)) {
		// Get tmp_path
		String tmp_path = EditorSettings::get_singleton()->get_cache_dir() + "\\uwptemp";
		
		// FIXME: Don't use 7z
		List<String> args_7z;
		args_7z.push_back("x");
		args_7z.push_back(p_path);
		args_7z.push_back("-o" + tmp_path);
		args_7z.push_back("-y");

		OS::get_singleton()->execute("7z", args_7z, true);
		
		// Call makeappx
		List<String> args_makeappx;
		args_makeappx.push_back("pack");
		args_makeappx.push_back("/d");
		args_makeappx.push_back(tmp_path);
		args_makeappx.push_back("/p");
		args_makeappx.push_back(p_path);
		args_makeappx.push_back("/o");
		
		OS::get_singleton()->execute(makeappx_path, args_makeappx, true);
		
		// PENDING: Delete tmp_path folder recursively
		// ...
	} else {
		ERR_PRINT("Could not find makeappx executable at " + makeappx_path + ", aborting.");
		return ERR_FILE_NOT_FOUND;
	}
}
```

And before ```EDITOR_DEF("export/uwp/debug_certificate", "");```
```
EDITOR_DEF("export/uwp/makeappx", "");
EditorSettings::get_singleton()->add_property_hint(PropertyInfo(Variant::STRING, "export/uwp/makeappx", PROPERTY_HINT_GLOBAL_FILE, "*.exe"));
```

This is a quick & dirty solution to that issue by repackaging the generated APPX file.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/30558.
