### ISSUE TITLE
Timer is_active/is_processing

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#7928]
How do I know that the Timer is running?

I can see is_active() but this is not changing when I use start() or stop() see #4175.

Can we add something like this? Otherwise it is always true.

```
void Timer::start() {
	time_left=wait_time;
	active = true;
	_set_process(true);
}

void Timer::stop() {
	time_left=-1;
	active=false;
	_set_process(false);
	autostart=false;
}
```

**Comment by cbscribe** [comment]
`active` indicates paused/unpaused state.  You can use:

    if get_time_left() > 0

to tell if the timer is running.  A oneshot timer will return 0 when it has stopped.

**Comment by AlexHolly** [comment]
Is this `if get_time_left() > 0` the same as `if is_processing()` ?

`is_active()` is a bit confusing when someone is looking for an `is_active()` that is actually a `is_paused()`.

Maybe we can add something like this to the `is_active()` docs

Return if the timer is active**(paused)** or not.

And add another predicate that is representing` if get_time_left() > 0`

```
func is_running():
   return get_time_left() > 0
````

So if someone sees is_active and is_running it will be easier to see the difference.

**Comment by cbscribe** [comment]
`is_processing()` refers to the `Node` property:
http://docs.godotengine.org/en/stable/classes/class_node.html#class-node-is-processing

See `set_process()` on the same page for details.

I agree the docs are a little terse and don't always have the best description.  The `set_active()` description does say "Set whether the timer is active or not. An inactive timer will be paused until it is activated again."  You have to sort of dig and experiment to understand what the pause/active behavior is.
