### ISSUE TITLE
Can no longer select contents of a WindowDialog using mouse (In Editor)

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#79289]
### Godot version

4.1

### System information

Linux Mint 21.1 Cinnamon, Graphics: Intel Corporation HD Graphics 620, Processor: Intel© Core™ i5-7200U CPU @ 2.50GHz × 2

### Unable to select anything using mouse inside "Window" and "SubViewport" nodes **In Editor**
In Godot 3 i was able to:

1. Select items/nodes IN the WindowDialog (and other popup nodes) **"Using the mouse"**
2. There was an **Orange-Yellowish boundary** that i used to "Visualize" the extents of the contents
Both of these were very useful to me :sob:  (I know i can do the same by changing values in properties but visualizing it is important too)

https://github.com/godotengine/godot/assets/77773850/61909bcf-9dc1-42dc-97dd-01e032bb7e58

And here's What happens in godot 4 (NO visual selection rectangle appearing in 2d viewport at all):

https://github.com/godotengine/godot/assets/77773850/5be91939-3eeb-4dc1-933e-955b071a3a13

I think this is due to Window now being child of Viewport
(In Viewport (for Godot 3) one was ALSO unable to do the above 2 things so it makes sense that Godot 4 "Window" node would do the same)

If it is possible please allow these 2 features (og Godot 3) to continue existing in Godot 4

### Steps to reproduce

(this doesn't require those)

### Minimal reproduction project

(not needed)

**Comment by AThousandShips** [comment]
* Related: #20619

**Comment by Variable-ind** [comment]
https://github.com/godotengine/godot/pull/74573 will solve what i wanted if it gets merged

**Comment by IvailoBurov** [comment]
It's still not fixed for Godot 4.2 version.

**Comment by jackcasey** [comment]
This seems to be pretty crippling? I'm upgrading from godot 3.5 to 4.2 and I have some UI in popups in my main scene and now they are very hard to interact with in the editor. (Not to mention all got resized to 100x100 pixels for some reason on upgrade).

Popups now being windows seems to have broken a few things for me. Is there a recommended alternative implementation for popup style modal UI?
