### ISSUE TITLE
Drag preview doesn't show in detached script editor

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#79282]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11

### Issue description

When dragging nodes from the scene tree onto a detached script editor, no drag preview is visible. This means there is no indication to the user that they're actually able to drop something into the script editor. Dropping the node still works, it's just the preview that doesn't show.

This still works fine when using the attached script editor.

### Steps to reproduce

- Create a scene with a script attached to some node
- With a detached script editor, drag a node from the scene tree into the script
- Observe that no drag preview is visible

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Thanks for the report. Currently the preview is only visible in the Viewport, where dragging started. This is already reported in #67186. Consolidating as duplicate with that bugreport.
