### ISSUE TITLE
`ResourceLoader::get_dependencies` breaking change in 4.1

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#79300]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon (TM) RX 470 Graphics (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD FX(tm)-8300 Eight-Core Processor (8 Threads)

### Issue description

`ResourceLoader::get_dependencies` returns a `PackedStringArray` with the resource's dependencies.

In **4.0.3**, each string is in the following format:
**uid://dvddbduy2au8w**.

But in **4.1**, each string is in the following format:
**uid://dvddbduy2au8w::::res://scenes/main_menu/main_menu_btn_pressed_style.tres**.

The change causes some errors that did not happen previously:

1. When fetching dependencies recursivelly, using the new output as input to `ResourceLoader::get_dependencies`;
2. When trying to load the new ouput with ``ResourceLoader::load``.

### Steps to reproduce

Run the **main** scene of the MRP.

### Minimal reproduction project

[get_dependencies.zip](https://github.com/godotengine/godot/files/12004931/get_dependencies.zip)

**Comment by KoBeWi** [comment]
This comes from #73131

The internal `get_dependencies()` method has a second argument `p_add_types`, which if true will add type to the returned string, so you'd get `uid://dvddbduy2au8w::TypeName`. Seems like the bound method always passes `false` to add types argument and it was consistently returning UID only. The aforementioned PR adds resource path to the string, in case the UID is invalid.

We could either make the exposed `get_dependencies()` work the same as before or document it. You can get the UID reliably by using `get_slice("::", 0)` on the returned String.

**Comment by felaugmar** [comment]
> We could either make the exposed `get_dependencies()` work the same as before or document it. You can get the UID reliably by using `get_slice("::", 0)` on the returned String.

I actually prefer it to be documented and kept as it is, it's nice to have more information about dependencies.
