### ISSUE TITLE
Slight position offset in rotated ColorRects

### ISSUE THREAD

**Issue by LuquinhasCarvalinhos** [godotengine/godot#79305]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated GeForce MX350 () - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 Threads)

### Issue description

When you rotate a ColorRect with a pivot offset by any angle divisible by 45 but not 90, including negatives(..., -135, -45, 45, 135, ...), the color gets slightly misaligned to the edges of the orange container box in the 2D inspector. It should just... not do that.

![image](https://github.com/godotengine/godot/assets/100634834/17768cc0-047a-4137-b8b6-b6500c0c1533)

### Steps to reproduce

1 - Rotate the ColorRect by a multiple of 45, but not 90, including negatives(..., -135, -45, 45, 135, ...);
2 - Set the pivot offset  to anything other than 0, 0, including negatives;
3 - Look closely at the edges of the container, preferably with more than 800% zoom to see that the color is outside of the border of the orange select container in some areas.

### Minimal reproduction project

[min reproduction.zip](https://github.com/godotengine/godot/files/12022660/min.reproduction.zip)

**Comment by Calinou** [comment]
I can reproduce this on 4.1.stable, but it's very hard to see in practice.

Does your project use any special settings such as 2D pixel snap? I've tested this on a blank project with the default project settings.

### Forward+

![image](https://github.com/godotengine/godot/assets/180032/a90fc417-8785-43ae-9c30-fe23246f0920)

### Compatibility

![image](https://github.com/godotengine/godot/assets/180032/8fbb6450-3b52-4371-ac08-9e570733f829)

**Comment by LuquinhasCarvalinhos** [comment]
edited to fix some of the mistakes you pointed out

**Comment by LuquinhasCarvalinhos** [comment]
oh ok you're right, didn't notice before because you need to move it a bit for it to apply. sorry!
