### ISSUE TITLE
Children stops to process when parent pause mode is PAUSE_MODE_PROCESS and tree is paused. Little fix

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#7931]
I was to create screens with godot when I tried to stop one node and keeping the other running.
get_tree().set_pause(false)
nodeA.set_pause_mode(PAUSE_MODE_STOP)
nodeB.set_pause_mode(PAUSE_MODE_PROCESS)
get_tree().set_pause(true)

NodeA and B are children from main scene. I discover that problem is when run nodeB.set_pause_mode(PROCESS) the children from nodeB are stopped like if the nodeB was stopped too, but no, nodeB is the ONLY running, while their children are paused! I tried to alert this but it seems nobody understand.

Now the solution:
Go to the scene/main/ in godot's source
Open the file node.cpp
Go to line 72 and where has the else with data.pause_owner=NULL;, just change to data.pause_owner=this;
The problem was the data.pause_owner stay lost in some part of the code, that above in my opinion.
It was because that the program NEVER GOES BEYOND of the "if (!data.pause_owner)" in the function "Node::can_process()" when pause mode of the node is PAUSE_MODE_INHERIT

NOTE: I don't know how to add the fix to godot code, so please, anyone do this for me.]

Espero ser mais ouvido na próxima vez.
Passar bem.

**Comment by sam-leo** [comment]
Oh and some little note: in the line 388 of the node.cpp in function set_pause_mode() if the node not has any parent so the pause_owner in the children will be lost because it's a NULL on the line 384. I put an else with "owner = this" and this could have some effect on the solution of the bug, please, give a look in that lines.

**Comment by akien-mga** [comment]
It would be nice if you could edit the issue title to actually describe the bug, and not a request :) People reviewing bug reports should not have to read everything before they can understand what the issue is talking about (even though reading it all is of course necessary to understand it fully - but the title should be a summary).

**Comment by sam-leo** [comment]
Man, the fix not change the physics of the game and not change the sample player, because to get this works you must have to set the pause to true. Well, I will try the old method to make screens.

**Comment by bojidar-bg** [comment]
@sam-leo Would you mind either making a sample project or a [PR (pull-request)](https://help.github.com/articles/about-pull-requests/) with your fix?

**Comment by sam-leo** [comment]
Sorry for the delay, @bojidar-bg I don't was able to reproduce the bug in a little example. I suppose it was just in my project. So, I will close this issue. Maybe the "bug" was for the way that I tried to use the screens: loading all nodes and hide the nodes and showing the actual screen. Thank you
