### ISSUE TITLE
Calling MultiplayerAPI in a thread results in crashes.

### ISSUE THREAD

**Issue by Leshy-YA** [godotengine/godot#79323]
### Godot version

4.1

### System information

Godot v4.1.stable - Fedora Linux 38 (KDE Plasma) - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

Whenever a MultiplayerAPI call is made in a function running in a thread, that thread will crash.

Issues started occurring in 4.1 in all 4.0 releases this worked fine.

### Steps to reproduce

Start a thread. 
Call `multiplayer.get_unique_id()` in that function.
The function will exit immediately.

NOTE: No debug information will be provided due to: https://github.com/godotengine/godot/issues/18330

### Minimal reproduction project

[multiplayer_thread_test.zip](https://github.com/godotengine/godot/files/12012785/multiplayer_thread_test.zip)

**Comment by Leshy-YA** [comment]
> Multiplayer is only supported from the main thread (...)

I can't find any information in the docs of that being the case. Is that by design or just a long-standing issue?

**Comment by AThousandShips** [comment]
Should probably be more clearly documented though

**Comment by Leshy-YA** [comment]
> APIs are non-thread safe unless stated otherwise, see [here](https://docs.godotengine.org/en/stable/tutorials/performance/thread_safe_apis.html)

Oh ok! It would have been useful to have that also in the MultiplayerAPI doc. 
Thanks for the info!

**Comment by AThousandShips** [comment]
To clarify, the crash comes not from the thread safety as such, but from accessing methods on `multiplayer` when that is null, fixing the errors on threads, and documenting this should be the plan IMO

**Comment by Chaosus** [comment]
> Multiplayer is only supported from the main thread

IMO, even if it's not possible it shouldn't crash, instead an error should be printed to console/output.

**Comment by AThousandShips** [comment]
The problem is that if you fetch the multiplayer and then call something on it how do you avoid a crash then? The returned value from `multiplayer` will be null

**Comment by AThousandShips** [comment]
Calling things like `is_multiplayer_authority` used to crash but was fixed, but since it's up to the user to add null checks we can't fix user code that doesn't do that with `multiplayer`
