### ISSUE TITLE
Static vars don't autocomplete when referencing class

### ISSUE THREAD

**Issue by Jay-Dorcat** [godotengine/godot#79339]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 10.0.19045

### Issue description

Static vars don't autocomplete when referencing class
This is useful when getting static variables of one class from a different class

### Steps to reproduce

```gdscript
class_name CustomClass

static var Variable : int = 10

func _process(delta):
    Variable #Valid, Does Autocomplete
    CustomClass.Variable #Valid, Doesn't Autocomplete
```
```gdscript
class_name DifferentClass

func _process(delta):
    CustomClass.Variable #Valid, Doesn't Autocomplete
```

### Minimal reproduction project

N/A

**Comment by EddieBreeg** [comment]
I just reproduced it, it seems that the class name itself doesn't autocomplete on my end, can you confirm this?

**Comment by Jay-Dorcat** [comment]
![image](https://github.com/godotengine/godot/assets/34311843/72df433e-f496-423a-b09a-ffc818a1954b)

**Comment by EddieBreeg** [comment]
Right yes I was just missing the extend directive, my bad

**Comment by EddieBreeg** [comment]
I found the enum which handles the lookup result types for autocompletion. It's unclear to me whether static variables are at all taken into consideration by the this enum:
https://github.com/godotengine/godot/blob/23318e877890029f35856036b9c4e0bfa09cacc6/core/object/script_language.h#L364-L375

**Comment by dalexeev** [comment]
Static variables can be treated as script properties, so I'm think a separate enum value won't be needed.
