### ISSUE TITLE
WE NEED OPENGL 2 SUPPORT AGAIN

### ISSUE THREAD

**Issue by AdamBosila** [godotengine/godot#79333]
### Godot version

v4.1.stable.official [970459615]

### System information

Android 11 - Honor 50 lite , Lubuntu linux - Samsung NP300E5V 

### Issue description

millions of people dont have opengl 3 support
thats why i cant migrate to godot 4

my laptop supports compatibility renderer
and my phone supports mobile renderer

but most people in my country doesn't have computers that are made after 2013
and a lot of other countries are worse

so as a game developer i want my games to be accessible for most people

please bring back opengl 2

Adam Bosila , Egypt

### Steps to reproduce

open the engine,
create a new project

### Minimal reproduction project

[project.godot.zip](https://github.com/godotengine/godot/files/12014006/project.godot.zip)

**Comment by AThousandShips** [comment]
This is for bugs, not proposals, please open one [here](https://github.com/godotengine/godot-proposals)

**Comment by akien-mga** [comment]
I would advise using Godot 3.x if you want to target old devices. Godot 4 is designed for devices which are less than 10 years old, to be suitable to support also the next 10 years of devices.

For devices older than 10 years old, Godot 3.x is a much more appropriate engine which requires less memory, works single threaded, etc.

**Comment by AThousandShips** [comment]
Also duplicate of #77795
