### ISSUE TITLE
class and node _ready functions fight

### ISSUE THREAD

**Issue by Insane-Owl** [godotengine/godot#79356]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

The code under the `func _ready()` function of a custom class gets ignored if the node that extends it also uses the `func _ready()` function.

### Example
If you make a custom class (e.g. "Movement") that has a `func _ready()` function that prints ***"I'm Moving around! Look at me!"*** to the console on ready, and an enemy node that has code that extends the Movement class, and ALSO uses the `func _ready()` function that prints ***"Imma attack you!"*** to the console on ready, only the enemy's ***"Imma attack you!"*** gets printed to the console

### Steps to reproduce

1. Create a custom class that does something on ready (`func _ready()`)
2. Create another node that has code that extends the custom class above, and also does something on ready (`func _ready()`)
3. Observe that only the node's _on ready_ function happens, and the function from the custom class never happens.

### Minimal reproduction project

[_ready bug.zip](https://github.com/godotengine/godot/files/12022430/_ready.bug.zip)

**Comment by felaugmar** [comment]
@Insane-Owl This is expected in **4.x**.

You need to call `super._ready()` to call base class implementation.
