### ISSUE TITLE
[Web] `WebSocketPeer.get_close_reason()` always returns empty string.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#79365]
### Godot version

4.1 and master

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 2050 (NVIDIA; 31.0.15.2656) - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

```gdscript
extends Control

var socket = WebSocketPeer.new()

# test on https://www.piesocket.com/websocket-tester
const WEBSOCKET_TEST_URL = "wss://demo.piesocket.com/v3/channel_123?api_key=123"

func _ready():
	set_process(false)

func _on_connect_pressed():
	set_process(true)
	$Connect.disabled = true
	socket.connect_to_url(WEBSOCKET_TEST_URL)

func _process(delta):
	socket.poll()
	var state = socket.get_ready_state()
	if state == WebSocketPeer.STATE_OPEN:
		while socket.get_available_packet_count():
			print("[WS]Packet: ", socket.get_packet().get_string_from_utf8())
			socket.close(1000, "my reason")
	elif state == WebSocketPeer.STATE_CLOSED:
		var code = socket.get_close_code()
		var reason = socket.get_close_reason()
		print("[WS]Closed. code: %d, reason: %s" % [code, reason])
		set_process(false)
		$Connect.disabled = false

```
On Windows(expected):
```
[WS]Packet: {"error":"Unknown api key"}
[WS]Closed. code: 1000, reason: my reason
```
On Web:
```
[WS]Packet: {"error":"Unknown api key"}
[WS]Closed. code: 1000, reason: 
```

### Steps to reproduce

Connect to WebSocket and then close it to get reason text. See reproduction below.

### Minimal reproduction project

[web_websocket_bug.zip](https://github.com/godotengine/godot/files/12025837/web_websocket_bug.zip)

**Comment by EddieBreeg** [comment]
I wasn't able to reproduce the bug on the latest master version, it seems like someone fixed it already

**Comment by zaevi** [comment]
> I wasn't able to reproduce the bug, neither on the latest master version or the stable 4.1, it's not as easy to reproduce as it seems

Have you tried on Web? Just run on web browser and press the test button.

**Comment by EddieBreeg** [comment]
Indeed, the web version doesn't set the connection close reason properly
