### ISSUE TITLE
Script editor Find in files finds duplicate results from android build folder

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#79375]
### Godot version

4.1.1rc1

### System information

macOS 13.4.1

### Issue description

If you export to Android (using a gradle build?) this generates an android/build folder in your project folder with a lot of processed files for your build. These persist after your export is finished (perhaps to be reusable for future exports?) and amongst other things it contains a copy of all your script files.

The issue is that if after the export you use the "Find in files" search in the script editor, this will show results in the android build folder, treating them as script files in your project. 

![Screenshot 2023-07-12 at 14 34 45](https://github.com/godotengine/godot/assets/17763524/5f04391b-9dd1-47c4-bd8a-1e0bf8667700)

While mostly harmless, it's confusing since it'll show duplicate results of all hits in the find results, and you might make the mistake to open and start editing the files in the android build folder instead of the active script files in your project.

### Steps to reproduce

- Make a project with at least one script file
- Make an android gradle export of this project 
- In the script editor, use "Find in files" on something in the script file
- Get find result from android build folder.

Expected would be no results from android/build. Either the search should disregard these, or perhaps the android build process should either clear out these files after the export process, or somehow automatically add a .gdignore or such to make sure they're not picked up by godot outside the export process.

### Minimal reproduction project

This is more of an issue with search in the script editor, or perhaps android export so any project exporting to android should do.

**Comment by KoBeWi** [comment]
AFAIK `build` folder is not supposed to be commited, so it could be renamed to `.build` to hide it.

**Comment by lostminds** [comment]
> AFAIK `build` folder is not supposed to be commited, so it could be renamed to `.build` to hide it.

If I remember correctly you sometimes currently need to remove the build folder manually (perhaps when setting up a new build for a new Godot version?) so it could be problematic if it's hidden in the file system. But then again I'm not sure why it can't be automatically overwritten in these cases.
