### ISSUE TITLE
Missing word in alert popup

### ISSUE THREAD

**Issue by WiseNoodle** [godotengine/godot#79380]
### Godot version

v4.1.stable.official

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) RX 480 (Advanced Micro Devices, Inc.; 31.0.14057.5006) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

There is a missing word in an alert popup. Will include a screenshot.

The alert should read, "Missing file '(filename' or one of its dependencies".

Instead it reads, "Missing file '(filename' or one its dependencies".

(it's missing the word "of").

NOTE: THE IMPORT ERROR IS NOT THE ISSUE, ITS THE WORDING IN THE ALERT POPUP.

This report should be of LOW priority.

(p.s. If I'm missing any info you'll have to forgive me; this is my first issue/bug report.

![image](https://github.com/godotengine/godot/assets/95942443/a2a9dd46-a34d-4209-b974-db10d29b7f8f)

### Steps to reproduce

Using your file manager, copy a scene with a script attached (just the .tscn and .gd files) into a different project's root res:// folder.

Then try opening the pasted scene and you will get the alert.

### Minimal reproduction project

N/A requires two projects.

**Comment by WiseNoodle** [comment]
Can I fix this myself and create a pull request? I've always wanted to become a contributor

**Comment by AThousandShips** [comment]
Go ahead! Make sure to follow the [guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)

**Comment by WiseNoodle** [comment]
No way! Sick!! And will do. So hyped
