### ISSUE TITLE
Could Not Create A Folder While Setting Up New Project - Ubuntu Mate 16.04 LTS

### ISSUE THREAD

**Issue by hermit8888** [godotengine/godot#7938]
**Operating system or device - Godot version:**
Ubuntu Mate 16.04 LTS - Godot_v2.1.2-stable_x11.64 

**Issue description:**

When clicking the "Create Folder" button, I get an Alert stating:
"Could not create folder."

If I manually create the folder and try to create a New Project, nothing happens, no files are created.

I installed Godot using the following procedure: 
http://cialu.net/blog/install-godot-engine-fedora-ubuntu.html

My **godot.desktop** file looks like the following: 

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Godot
Comment=Create different games
Exec=/opt/godot/godot
Icon=/opt/godot/godot_icon.png
Terminal=false
Type=Application
Categories=Graphics; Development; Games;
Name[en_US]=Godot
GenericName[en_US]=Game development platform
Comment[en_US]=Create different games!

**Comment by bojidar-bg** [comment]
Can you confirm that you have no simlinks on the path to the folder you are trying to create? (since we have reports that the current Godot code chokes on them)

**Comment by hermit8888** [comment]
No, I don't have any symbolic links on the path to the folder (I have no
symlinks at all).

**Comment by Calinou** [comment]
Does the path to the project folder contain non-ASCII characters (such as é, ö, …)? This may be a similar issue to https://github.com/godotengine/godot/issues/1708 (which is now fixed).

**Comment by hermit8888** [comment]
No, no  non-ASCII characters in the path.

**Comment by hermit8888** [comment]
I figured out the issue. My permissions for the folder where I wanted to create a new project was **root**. When I changed the folder's permissions to my home user name, I was able to create a folder and start a New Project.

**Comment by Jotonan** [comment]
How could i change the file permissions from root?
