### ISSUE TITLE
Godot window consistently steals focus when used with i3wm

### ISSUE THREAD

**Issue by cohen990** [godotengine/godot#79385]
### Godot version

4.1.stable.mono.official and 4.0.3.stable.arch_linux

### System information

Arch Linux v6.3.9-arch1-1, Godot 4.1.stable.mono.official and 4.0.3.stable.arch_linux, i3 v4.22

### Issue description

When moving windows around in a workspace, like my editor or chrome or whatever, Godot will always steal focus. Both the mono version and the normal version do this. Every time I try and move a window left, it will refocus to Godot meaning I need to shift my focus back to the window I'm trying to move in order to make another move. Very annoying.

Searching online finds that this can happen in i3 if clients are using `SetInputFocus` instead of `_NET_ACTIVE_WINDOW` and searching through the Godot codebase finds both in use. Not sure if that'll be the cause but that's what led me to believe this is arguably a Godot issue rather than an i3 issue.

### Steps to reproduce

- On a machine running I3WM as a window manager
- Set I3WM to the "split" layout (default mod + e)
- have both godot and any other program (e.g. google chrome, jetbrains rider, vscode etc). 
- Shift focus to the non-godot window. (default mod + arrow key)
- Move the non-godot window in any direction (default mod + shift + arrow key)

### Minimal reproduction project

This is an issue with the editor window itself. It happens before even loading a project.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74378 and https://github.com/godotengine/godot/issues/74587.
