### ISSUE TITLE
Node with wrong icon

### ISSUE THREAD

**Issue by Rissole781** [godotengine/godot#79397]
### Godot version

4.1 stable

### System information

Windows 10 - x64 

### Issue description

**Hello godot engine developers**
I wanted to report a small bug that is happening in godot 4.1

Randomly, node StaticBody2d has white node2d icon

But this is not at all uncomfortable,
it's just a design error

and when you close and open the tab, it goes back to normal

### Steps to reproduce

it's random

### Minimal reproduction project

N/A

**Comment by EddieBreeg** [comment]
Is it something that happens frequently or rather rarely? Could you provide a project in which the issue occurred?
I can't seem to reproduce it on my end

**Comment by dalexeev** [comment]
* Looks like related/duplicate of #79226. But you didn't change the node type, does the bug happen spontaneously?

**Comment by KoBeWi** [comment]
Might be duplicate of #76983

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/76983
