### ISSUE TITLE
Godot 4.1 Copy System Info doesn't copy the correct rendering driver when using ```--rendering-driver opengl3``` and Compatibility engine

### ISSUE THREAD

**Issue by jcovin293** [godotengine/godot#79391]
### Godot version

4.1.1rc1

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - OpenGL3 (Compatibility) - GeForce GT 630M () - Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 Threads)

### Issue description

When I run Godot using ```--rendering-driver opengl3```, **Help > Copy System Info** reports that I am using the Vulkan rendering engine, producing a message like this: **_Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 630M () - Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 Threads)_**, where I would expect it to say **_OpenGl3 (Compatibility)_** in place **_Vulkan Compatibility_**.

### Steps to reproduce

1. Open Godot using ```--rendering-driver opengl3```
2. Switch to Compatibility rendering engine
3. Go to **_Help > Copy System Info_**
4. Paste the system info and see that it reports Vulkan to be the rendering driver

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/pull/77929.

**Comment by Calinou** [comment]
The driver name is fetched from the `rendering/rendering_device/driver` project setting: https://github.com/godotengine/godot/blob/60f3b7967cbd00b4e1f52d33d372646f7bec02f6/editor/editor_node.cpp#L4379

However, this does not account for the Compatibility rendering method being selected, as it can *only* run with the `opengl3` driver, not any other drivers. Therefore, if the Compatibility rendering method is detected, it should be assumed that you're using OpenGL.
