### ISSUE TITLE
Tile preview not using texture filter of Tilemap

### ISSUE THREAD

**Issue by 4x32** [godotengine/godot#79399]
### Godot version

4.1.stable.mono.official [970459615]

### System information

Windows, Forward+, 4.1

### Issue description

The preview tile that is hovering under my mouse to be placed, is using a linear filter, even though the Tilemap and the parent node is using Nearest.

### Steps to reproduce

Empty project,
Make the Tilemap node,
Add a simple test tileset/texture,
Set set the Tilemap node's texture filter to nearest (or make it inherit from one that uses nearest)
Place some tiles, they should be using the nearest filter,

The problem is with the preview of the tile that is under your mouse that you select to be placed, it will always use the Linear filter.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52332.
