### ISSUE TITLE
Holding down certain action combinations disables certain other actions

### ISSUE THREAD

**Issue by Kalcen** [godotengine/godot#79394]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 10

### Issue description

I noticed that if you hold down S, then also hold down A, then certain other input actions don't register. The inputs that get ignored that I've found while doing this are: Esc, 1 (row-key), 2 (row-key), and 3 (row-key).

### Steps to reproduce

add this script to any node in a scene: 
```
func _process(delta):
	if Input.is_action_just_pressed("ui_cancel"):
		print("!!")
```
Hit run, and hold S then hold A then press Esc and check if the print message worked.

### Minimal reproduction project

[MultipleInputIssue.zip](https://github.com/godotengine/godot/files/12032796/MultipleInputIssue.zip)

**Comment by AThousandShips** [comment]
This sounds like keyboard ghosting, not a problem in the engine but a limitation of your keyboard, so nothing we can do about it

Please look it up online

**Comment by Kalcen** [comment]
> This sounds like keyboard ghosting, not a problem in the engine but a limitation of your keyboard, so nothing we can do about it
> 
> Please look it up online

I just tested it on my other keyboard, and you're right! It's probably time for a new keyboard lol.
