### ISSUE TITLE
Particles animate per frame per camera

### ISSUE THREAD

**Issue by fluffrabbit** [godotengine/godot#7939]
In Godot 2.1.2, with multiple cameras rendering at once, particles move at set speed * number of cameras. Probably related to #6578 (each viewport causes the whole rendering routine to be called each frame).

Possible solutions:
 • Set particle speed for all emitters to original speed / number of cameras (can be done in GDscript)
 • Make the renderer handle multiple cameras better

Anecdotal stuff:
 • I'm working on a VR game which is probably going to come out before Godot 3.0 hits beta. I know related features are on the eventual to-do list. I noticed this bug because I had a button to toggle between single-viewport and splitscreen. Demonstration attached.
 • I didn't see a 3D particle emitter in Godot 3.0 (at least with a build from a couple weeks ago), implying particles are under overhaul (explosiveness pl0x), possibly related to a renderer overhaul. Particles in Godot are tightly integrated with the renderer.

[particlizer.zip](https://github.com/godotengine/godot/files/818356/particlizer.zip) (5.5 kB)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by fluffrabbit** [comment]
Scope of particle timing is correct in Godot 3.0 rendering pipeline. Godot 2 pipeline is structured wrong, but is no longer maintained. Closing issue as it no longer applies.
