### ISSUE TITLE
4.1.1rc1 export templates missing, 404 error on template manager download

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#79410]
### Godot version

4.1.1rc1

### System information

macOS 13.4.1

### Issue description

Just tried installing the export templates via the panel in Godot and it seems they're missing, or at least no on the expected URL https://github.com/GodotBuilder/godot-builds/releases/download/4.1.1-prerelease-templates/Godot_v4.1.1-rc1_export_templates.tpz

![Screenshot 2023-07-13 at 09 11 22](https://github.com/godotengine/godot/assets/17763524/6c30c577-b36e-4c39-b2d3-12e91e47c6eb)

### Steps to reproduce

Open Export template manager
Click "Download and install"

### Minimal reproduction project

No project required, bug is with template distribution/downloads

**Comment by AThousandShips** [comment]
Seems to be a configuration error, looks like we've migrated from one page to another, the releases are on https://github.com/godotengine/godot-builds now, will take a look
