### ISSUE TITLE
Android export target sdk 33

### ISSUE THREAD

**Issue by SnailRabbids** [godotengine/godot#79423]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

Hi,
since August 31, Google requires target_sdk version 33 for Android apps (Android exports), but Godot 3.5 supports target sdk <=32. Can I expect target_sdk 33 in Godot 3.6 or should I use 4.1+?

I can set target_sdk 33 manually but there is a warning that it was not tested.

### Steps to reproduce

Export -> Android -> target sdk level 32.

### Minimal reproduction project

Is not needed.

**Comment by Sauermann** [comment]
Looks like the issue has been solved by #75205. That PR also has the "cherrypick-3.5" label, so it is likely that the change gets included in one of the next 3.5-releases.
I am closing this accordingly.
