### ISSUE TITLE
Blend file import warning is printed for every new project.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79428]
### Godot version

4.1.stable

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M - Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

When creating a new Godot project the following warning shows up in the editor:
```gdscript
modules/gltf/register_types.cpp:73 - Blend file import is enabled in the project settings,
but no Blender path is configured in the editor settings. Blend files will not be imported.
```
![image](https://github.com/godotengine/godot-proposals/assets/84321760/7dfc61a6-7173-403d-8eab-ecd9ed1358c0)

For any person who makes primarily 2D games, and for people new to game-dev, (who may not know what blend files are), it is a minor inconvenience, that forces them to go to project settings and switch blend import off.

The warning printed on every new project, can also look like something is wrong with the engine for a new user who doesn't understand what it means.

**Please note that even though FBX file import is also enabled by default on new projects, no warning gets printed for them.**

I believe that either the warning should not exist at all, or that the blend file import setting (filesystem/import/fbx/enabled) should be off by default on new projects.

### Steps to reproduce

1. Create a new project.
2. Check out the warning.

### Minimal reproduction project

Any new Godot 4.1 project.

**Comment by AThousandShips** [comment]
> all, or that the blend file import setting (filesystem/import/fbx/enabled) should be off by default on new projects.

This will cause major annoyance at having to enable it for every new project, and make new users confused over why they can't import files

**Comment by Ybaedbaenn** [comment]
Is it possible to move this to **editor** settings for all projects, as blender path is already being set there?
![image](https://github.com/godotengine/godot/assets/84321760/2dff2301-8aae-46b9-be98-03e8e2c7e8a9)
Other option would be to make the warning show up when the first .blend file is imported.

**Comment by capnm** [comment]
https://github.com/godotengine/godot-proposals/issues/7827

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/7827, as feature proposals are now tracked in the Godot proposals repository.
