### ISSUE TITLE
Godot 4.1 .Net freeze on "Building .Net project..."

### ISSUE THREAD

**Issue by SbhnP** [godotengine/godot#79437]
### Godot version

4.1 stable mono linux 

### System information

Ubuntu 22.04.2 LTS , Stoney [Radeon R2/R3/R4/R5 Graphics]  diver=amdgpu, Compatibility renderer ,

### Issue description

Godot 4.1 .net freeze in Ubuntu after clicking the Build button 
i have tested Godot4.0 and 4.0.3 and they both work well.

![Screenshot from 2023-07-13 22-14-10](https://github.com/godotengine/godot/assets/114316833/921ddc1c-0bed-452e-8465-e0810ea9b9a5)

### Steps to reproduce

1- Make a new project 
2- Make one main scene with Node2D
3-Add c# script
4-Click Build or run the project 

### Minimal reproduction project

[temp.zip](https://github.com/godotengine/godot/files/12043450/temp.zip)

**Comment by Calinou** [comment]
If you have access to another PC or a Windows installation, can you test it there?

Also, do you get any errors when running Godot from a terminal and building the project?
