### ISSUE TITLE
Clear() don't clear scene collections cells from the Tilemap

### ISSUE THREAD

**Issue by jamesfoxbr** [godotengine/godot#79432]
### Godot version

4..1

### System information

Windows 10 64 bit

### Issue description

I'm using a Tilemap not and instead normal sprite cells using the scene collections. The problem is clear() method only clear normal sprites tiles no the scenes inside cells. I don't found any other way to remove the scene from the cell and if I call in the scene a queue free() the tilemap will not fill the cell anymore when I try set_cell()

### Steps to reproduce

Create a Tilemap and use any scene collection to place cells instead normal tiles and try to clear it in a script using clear().

### Minimal reproduction project

[bug_tilemap.zip](https://github.com/godotengine/godot/files/12042571/bug_tilemap.zip)

**Comment by AThousandShips** [comment]
* Cuplicate of: #74867

Consolidating there, thank you for reporting
