### ISSUE TITLE
Multiple resource packs for Mod and Map support

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#7943]
I have been looking through the code in Globals::setup as I am investigating 3rd party mod and map support.

I see a few hurdles at the moment:
1) the code looks for data.zip, it does not search for *.zip
2) once it finds this zip, it does not then look for any other packaged files

now, in my code I look for a directory called "Maps" and want to iterate over all sub-directories there.
supposed data.zip has a "Maps" but a user drops in a mode that has its own "Maps" folder, it looks like godot will simply return the first pack file with the "Maps" directory, leaving one of the "Maps" as missed.

There seems to be no way to iterate over each package that has been loaded and then ask it to give me access to "Maps" directory?

pseduo code:

`
for each package:
    if (pack->has_path("Maps"))
          iterate over pack "Maps" directory as usual here
` 

the only solution I can think of at the moment is to release my game without any packaging which i really want to avoid.

**Comment by bojidar-bg** [comment]
Sorry, but I can't understand the actual issue -- is it in the Directory class not looping over merged directories from mutiple packs, or is it from misunderstanding of `Globals::load_resource_pack`?

If it is the former, then this is a bug.
If it is the latter, it might be better off on QA/forums or on [godotengine/godot-docs](https://github.com/godotengine/godot-docs).

(As a workaround of the former, you can potentially have an entry-point gdscript or text file which lists the maps available in the pack, and has an unique name, that can be inferred somehow. Then you can just read it.)

**Comment by supagu** [comment]
The issue is that there are numerous issues stopping me be able to use godot and have a project which uses packages where a user can drop in mods or maps which may be packaged up into my game so that my game can load the mods and maps.

primarily:
1. the code that searches for packages only looks for a data.zip and when it finds it it does not attempt to load other packages
2. there is no way to iterate over what packages are loaded and access data from them.

These are my conclusions from looking over the code, but I only spent a few hours investigating so I certainly may be incorrect.

**Comment by eon-s** [comment]
@supagu There is support for multiple packages for patching, DLC, et cetera (search the Q&A) and no, there is no way to iterate over content of a loaded package, you must provide a file with the contents or patch a existing file.

I have made a request for a tool that works like Directory on the "virtual" res filesystem to make things more easy to use #7845

**Comment by akien-mga** [comment]
There is actually support for exporting and loading multiple packs in the master branch now, which can typically be used for DLCs or mods.

See https://twitter.com/reduzio/status/833185781309177856 and https://twitter.com/reduzio/status/833439304571551744
