### ISSUE TITLE
TextureRect fails to tile when SubViewport node in the same tree

### ISSUE THREAD

**Issue by weavejester** [godotengine/godot#79447]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19044 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3179) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When a `SubViewport` node is in the same tree as a `TextureRect` with *Stretch Mode* (`stretch_mode`) set to *Tile*, the texture will fail to tile at runtime. Note that in Godot itself it displays correctly.

Without `SubViewport`:

![image](https://github.com/godotengine/godot/assets/8780/d41f73b0-65ad-40b2-8677-728a351dca0e)

With `SubViewport`:

![image](https://github.com/godotengine/godot/assets/8780/7583d185-5858-46df-88dd-684aebb0db8a)

I've also just discovered that this behavior **also** occurs when you resize the window:

![Recording 2023-07-13 at 23 53 53](https://github.com/godotengine/godot/assets/8780/ea2db189-b8fc-469b-b0f1-9b634e266a75)

### Steps to reproduce

1. Create a new project with a root `Node` object.
2. Add a `TextureRect`
3. Assign the `TextureRect` an image texture.
4. Set *Stretch Mode* to *Tile*
5. Make The `TextureRect` large enough to see tiling
6. Add a `SubViewport`
7. Run the project.

### Minimal reproduction project

[repro_project.zip](https://github.com/godotengine/godot/files/12044999/repro_project.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79315.
