### ISSUE TITLE
In C#, Polling for InputMap action that does not exist produces a difficult to debug error.

### ISSUE THREAD

**Issue by hudmarc** [godotengine/godot#79449]
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - macOS 13.4.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 5300M - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When polling for an InputAction that does not exist from C#, Godot produces the following error, which is so long that it is impossible to read on a normal display.
```
E 0:00:01:0823   Godot.NativeInterop.NativeFuncs.generated.cs:345 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* ): The InputMap action "Jump" doesn't exist.
```
The expected error in this case would be something along the lines of
```
Error: The InputMap action "Jump" doesn't exist.
```
But instead this is what the console ends up looking like:
<img width="1037" alt="image" src="https://github.com/godotengine/godot/assets/44267994/a64f7c29-706a-4b91-acab-09bf1ee789e5">

### Steps to reproduce

Poll an Action that does not exist in C#:
```
Input.GetActionStrength(action_name);
```
The resulting error should be very difficult to parse.

### Minimal reproduction project

This is a very simple error to reproduce (simply poll for a nonexistent Action with C#) so I don't think a reproduction project is necessary.

**Comment by hudmarc** [comment]
Perhaps an easy fix for this would be to truncate errors produced by C# interop up to the actual message, with the option to view the full stack trace when clicking on the error?

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/71943.
