### ISSUE TITLE
Windows 11 treats 4.1.1rc1 as a threat

### ISSUE THREAD

**Issue by danielbill** [godotengine/godot#79450]
### Godot version

Godot v4.1.1rc1

### System information

Godot v4.1.1rc1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.3114) - AMD Ryzen 9 7940H w/ Radeon 780M Graphics (16 Threads)

### Issue description

Windows 11 treats 4.1.1rc1 as a threat
![DCBPS`{%WX87FF7TLH`3A0W](https://github.com/godotengine/godot/assets/6269655/79d33979-4c9a-4c5e-af61-b808682636f6)
It only opened the project once, and then it was deleted by the system

### Steps to reproduce

in win11 , open project with it once , then ......

### Minimal reproduction project

...

**Comment by Calinou** [comment]
Please report the executable as a false positive, following the comments from https://github.com/godotengine/godot/issues/79170.

**Comment by funkkiy** [comment]
@Calinou I'd like to add that signing a binary usually gets rid of most AV false-positives in Windows.

**Comment by sonic2kk** [comment]
I'm by no means an expert (just an armchair Godot watcher) but I think the executable is already signed as noted by https://github.com/godotengine/godot/issues/79170#issuecomment-1625970234

> The executable itself is digitally signed with an EV certificate, which Windows should already let through without any warnings.

**Comment by thedyze** [comment]
After zipping my exported exe, defender detects it as a threat:
![image](https://github.com/godotengine/godot/assets/72066289/ac2615af-106f-4757-a466-14e1adf2ea09)

**Comment by akien-mga** [comment]
Please submit your zip as false positive to Windows Defender, see https://github.com/godotengine/godot/issues/79170#issuecomment-1625968219

AFAIk there's nothing we can do there, antivirus software detects known patterns by a sequence of bytes and when compressing a binary, the sequence of byte changes and may create a false positive. Reporting it to the antivirus company is the only thing we can do.
