### ISSUE TITLE
Node-based Area3Ds can't tell when overlapping with PhysicsServer instanced ones.

### ISSUE THREAD

**Issue by ffernn-dev** [godotengine/godot#79458]
### Godot version

v4.1.stable.official [970459615], Also tested on v3.5.2.stable.official [170ba337a]

### System information

Godot v4.1.stable - macOS 13.4.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When creating Area3Ds using `PhysicsServer.area_create()`, an Area3D node doesn't see them in `get_overlapping_areas()`, (it returns `[]`). Interestingly, the Node Area3D's `has_overlapping_areas()` shows true at the correct time.
I have ensured that I am setting the correct collision layer & mask on both, and I have tried using `area_set_area_monitor_callback()` on the PhysicsServer area to no avail. 
I tested and this also doesn't seem to be working in 3.5 (using the correct class names ofc), so this could be intended behaviour? Either way it would be really nice to be able to have these collisions detected without having to use PhysicsServer for everything.

### Steps to reproduce

Take a look at the projects uploaded. You can use the up/down arrow keys to move the Area3D node up and down, while the RichText gives info on what it's seeing.

### Minimal reproduction project

[Godot 4.1 PhysicsServer.zip](https://github.com/godotengine/godot/files/12047556/Godot.4.1.PhysicsServer.zip)
[Godot 3.5 PhysicsServer.zip](https://github.com/godotengine/godot/files/12047555/Godot.3.5.PhysicsServer.zip)

**Comment by AThousandShips** [comment]
Well it can't return an `Area3D` if one isn't associated, right? How would it do that?

It expects them to be associated with actual nodes, with `area_attach_object_instance_id` but it's simply not intended to work like this

**Comment by AThousandShips** [comment]
Correction, there might be a bug here will investigate

**Comment by ffernn-dev** [comment]
> It expects them to be associated with actual nodes, with `area_attach_object_instance_id` but it's simply not intended to work like this, you can't create `Area3D` from the physics server

Yeah I assumed as much, but I was more wondering if there's a way it can be done, maybe by creating a new function? I think it's fair to say that there should be a way to do this.

**Comment by AThousandShips** [comment]
You'll have to manually track it with the monitoring signals, as that's what the `Area3D` is for, if you don't want to use it directly then you'll have to write your own code

If you attach an object id correctly, then it'll work at least partially, but the mechanisms with the server directly are simple by design, and if you want complex behaviour you will need to add it yourself

**Comment by ffernn-dev** [comment]
Alright that makes sense, thankyu :>
However, in my testing now it seems like `area_entered` signal isn't being emitted, while  `area_shape_entered` is. This is really strange behavior that I don't think is intended, or should at least be properly documented if it is.

**Comment by AThousandShips** [comment]
No that's exactly intended, it is triggered when an `Area3D` enters, and your custom area isn't one

**Comment by ffernn-dev** [comment]
Ah ok. Thanks so much for your time and explanations. I can get past a huge roadblock now, I thought I was going insane heheh. Have a good afternoon <3
