### ISSUE TITLE
Godot weird light issues

### ISSUE THREAD

**Issue by TKHDev21** [godotengine/godot#79463]
### Godot version

v4.1.1.rc1.official [e709ad4d6]

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 630M () - Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 Threads)

### Issue description

As you can see in the picture, there is something weird about the floor, and sometimes when i look at a light it the light dies

![Godot_light_issue](https://github.com/godotengine/godot/assets/116759222/9fc1dfe0-e8cf-4ec9-9ce8-3c70f1b7f894)

more info's:

max light pre object: 1024

max renderable lights : 256

### Steps to reproduce

when opening the game, only care about the "lvl 0 " scene, then when you respawn, go forward. and then you will see the floor error , and for the light error, its the same path except you will see to big blocks, stand front of them and look at a light.

### Minimal reproduction project

[Kenophobia remake.zip](https://github.com/godotengine/godot/files/12050073/Kenophobia.remake.zip)

**Comment by Calinou** [comment]
> max renderable lights : 256

Your scene has over 300 light nodes in practice, so some of them are bound to flicker in and out.

**Comment by TKHDev21** [comment]
alr thx, i will test it

**Comment by TKHDev21** [comment]
it worked, vut now the floor thing remains

**Comment by AThousandShips** [comment]
What is the floor problem? I don't see anything wrong in the image

**Comment by TKHDev21** [comment]
the light , you can see in the image some places have different colors

**Comment by AThousandShips** [comment]
I cannot see that no, the colour seems even to me, what is it supposed to look like?

**Comment by TKHDev21** [comment]
![IMG_20230714_184831](https://github.com/godotengine/godot/assets/116759222/7af2c7ef-3a29-44f0-b08c-b49382aaf53b)

you can see in this pic, the circled area is lighter than the rest of the area's

**Comment by AThousandShips** [comment]
My bad, it looked like the rest of the floor had a different texture

**Comment by TKHDev21** [comment]
yeah.. they have the same texture idk why

**Comment by AThousandShips** [comment]
I cannot replicate the bug, on either renderer
