### ISSUE TITLE
This item may not have a label readable by screen readers.

### ISSUE THREAD

**Issue by SnailRabbids** [godotengine/godot#79461]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

Hi,
I have 4 accessibility warnings in Google Play Console "Pre-launch report".
1. Element path: <package_id>:id/godot_fragment_container/FrameLayout[1]/EditText[3]
Recommendation: This item may not have a label readable by screen readers.
![image](https://github.com/godotengine/godot/assets/36141552/49f680ad-3383-40ac-a065-b87c3eddd3e5)
2. Element path: <package_id>:id/godot_fragment_container/FrameLayout[1]/GodotEditText[1]
Recommendation: This item may not have a label readable by screen readers.
![image](https://github.com/godotengine/godot/assets/36141552/49f680ad-3383-40ac-a065-b87c3eddd3e5)
3. Element path: <package_id>:id/godot_fragment_container/FrameLayout[1]/GodotView[2]
Recommendation: This item may not have a label readable by screen readers.
![image](https://github.com/godotengine/godot/assets/36141552/5cfe05a6-7916-4ab3-8b00-053b6512e46b)
4. Element path: <package_id>:id/godot_fragment_container/FrameLayout[1]/View[1]
Recommendation: This item may not have a label readable by screen readers.
![image](https://github.com/godotengine/godot/assets/36141552/d582aba6-5de6-4e9f-9458-24fbf5f7c81d)

I tried changing the first page and testing it again, but the warnings still appear. Do you have any ideas? Anyone else having this problem?

### Steps to reproduce

Export your app for Android -> upload to Google Play Console -> see "Pre-launch report"

### Minimal reproduction project

Do not have. Will try to create if needed.

**Comment by bruvzg** [comment]
Godot UI doesn't support screen readers, so probably nothing can be done here.

Adding support for 4.x is in progress - https://github.com/godotengine/godot/pull/76829, but AccessKit library currently does not support Android, iOS and Web, so it will work only on desktop platforms.

**Comment by SnailRabbids** [comment]
@bruvzg I see. So these warnings is a "normal behaviour" for now, right? Should I just ignore them?

**Comment by bruvzg** [comment]
> Should I just ignore them?

Yes.

**Comment by SnailRabbids** [comment]
> > Should I just ignore them?
> 
> Yes.

Ok, thanks :)

**Comment by YuriSizov** [comment]
I guess this is resolved then?

**Comment by sajjadheydari1401** [comment]
but how to ignore warnings? my app is not yet published and i dont see any option to ignore the warning and proceed with testing
