### ISSUE TITLE
Navigation region 3D not syncing

### ISSUE THREAD

**Issue by TKHDev21** [godotengine/godot#79468]
### Godot version

v4.1.1.rc1.official [e709ad4d6]

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 630M () - Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 Threads)

### Issue description

as you can see in the picture, When I run the game, this error shows up, wich leads to navigation region 3D not working.

![Godot error](https://github.com/godotengine/godot/assets/116759222/365b066b-2d63-4120-a3a4-ca09df08c71a)

more info's:

navigation region 3D's cell size: 30

navigation region 3D's agent height: 1

### Steps to reproduce

when opening the project , focus on only two scenes : "park_map" and "obunga" scene's

note: the "Obunga" scene is the enemy scene

note 2 : you can find the navigation region 3D at the bottom of the nodes tab in the "park_map" scene

### Minimal reproduction project

[Nextbot's engine.zip](https://github.com/godotengine/godot/files/12052137/Nextbot.s.engine.zip)

**Comment by AThousandShips** [comment]
You have incompatible navigation cell sizes, as the error says

**Comment by smix8** [comment]
The errors tell you that your navigation mesh `cell_size` and navigation map `cell_size` do not match and need to be brought to the same value.

You already set the cell_size manually from the default 0.25 to 1.3 on the NavigationMesh so set the same value for the navigation map either in the ProjectSettings navigation tab or by using the `NavigationServer3D.map_set_cell_size()` API function.

**Comment by TKHDev21** [comment]
alr thx, i will test it

**Comment by TKHDev21** [comment]
there is only2 option in the navigation 3D tab, Defult cell size and defult height size, idk how to set the navigation map thing

**Comment by smix8** [comment]
You need to enabled "Advanced Settings" in the top-right corner of the ProjectSettings menu.

**Comment by TKHDev21** [comment]
still, i see the same options

**Comment by TKHDev21** [comment]
oh alr, the issue is gone now to the other issue

**Comment by TKHDev21** [comment]
![image](https://github.com/godotengine/godot/assets/116759222/f72d0951-f3cc-4a75-b545-e22eac4769e5)

**Comment by TKHDev21** [comment]
![image](https://github.com/godotengine/godot/assets/116759222/0e2222d5-d7d9-4f9f-8f1c-5a80b09c7855)

**Comment by TKHDev21** [comment]
is this good?

**Comment by AThousandShips** [comment]
Are you asking us if things are working for you?

**Comment by TKHDev21** [comment]
well, kind of, cuz the Q&A web is  down and i cant post

**Comment by TKHDev21** [comment]
if it was open i would posted that there

**Comment by AThousandShips** [comment]
This isn't the Q&A though, no matter if it's down, please don't use this as it

**Comment by TKHDev21** [comment]
oh, alr

**Comment by AThousandShips** [comment]
You are still setting the target in `_ready` as was said wasn't supported, use `call_group_flags` with deferred instead, see [here](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-call-group-flags)

**Comment by TKHDev21** [comment]
i'm sorry to bother you, i'm kind of a new guy in godot btw, but i didn't undderstand so, please can you write it for me if you can?

info : enemy group "Nextbot"

**Comment by AThousandShips** [comment]
Just replace `call_group(` above with `call_group_flags(SceneTree.GROUP_CALL_DEFERRED`

**Comment by TKHDev21** [comment]
Yeah..  I still don't understand.. anyways thanks for your help I appreciate it, but idk why the tutorial that I followed ( by devloglogan) he did this ( called the group in the physic_procces(delta) )

**Comment by AThousandShips** [comment]
Try `get_tree().call_group_flags(SceneTree.GROUP_CALL_DEFERRED, "Nextbot", "update_target_location", player.gobal_transform.origin)`

**Comment by TKHDev21** [comment]
no errors, but still doesn't work

**Comment by AThousandShips** [comment]
What doesn't work, they don't go to the player position?

**Comment by TKHDev21** [comment]
yup

**Comment by TKHDev21** [comment]
but when I printed the "new_velocity.z"  it doesn't show "0", meaning the enemy is moving

**Comment by AThousandShips** [comment]
Please don't make multiple comments, as I asked before, edit your previous ones

**Comment by smix8** [comment]
Can be closed as isues are reserved for engine bugs or core documentation and there is nothing actionable here.

For project bugs see the community channels to ask for help https://godotengine.org/community/
