### ISSUE TITLE
Atlas Merging Tool not working

### ISSUE THREAD

**Issue by Jead-DC** [godotengine/godot#79473]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - Intel(R) HD Graphics 4600 (Intel Corporation; 20.19.15.5126) - Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz (4 Threads)

### Issue description

When I try to join 68 images of 128x128 resolution in an atlas it returns a transparent 1x1 image

I tried using few images and it doesn't work either

It doesn't work either with 16x16, 32x32, 64x64 resolutions

- Google Translate :)

### Steps to reproduce

https://github.com/godotengine/godot/assets/136469511/ca5f64c2-f0c5-486f-a13e-b941ae2dea7d

### Minimal reproduction project

N/A

**Comment by rakkarage** [comment]
There is usually an extra step (setup or create tiles) between... Once u drag the png to the tileset you can either select Setup and click on tiles u want to include or click on ... and "create tiles".

I tried it with the extra step and seems to work. Maybe there could be some inication that tiles are not created or empty or something...

**Comment by Jead-DC** [comment]
It would be a good idea to do it automatically because it would be tedious to have to manually configure so many tiles.

**Comment by jonathandw743** [comment]
I also have this problem, but creating the tiles does not change anything as creating tiles when there is only one tile causes no change.

**Comment by rakkarage** [comment]
Even after creating single tiles they not show up in tile atlas merge? Tested and they do for me... if they are solid tiles might be related to: https://github.com/godotengine/godot/issues/80870

**Comment by jonathandw743** [comment]
I think #80943 closes this

**Comment by jonathandw743** [comment]
I think #80943 closes this

**Comment by Levelleor** [comment]
I am still experiencing this issue. After merging I get that 1x1 atlas (on the right) with no tiles (on the left). 

![image](https://github.com/godotengine/godot/assets/11915185/6bf3f898-9691-4366-b98a-22190157a8f6)

**Comment by AThousandShips** [comment]
That's because this fix is not in 4.1.2, it will be cherry picked but has not been cherry picked yet, will hopefully be in 4.1.3

**Comment by bonsaipropaganda** [comment]
> That's because this fix is not in 4.1.2, it will be cherry picked but has not been cherry picked yet, will hopefully be in 4.1.3

I believe this is probably correct. I was just having this issue and I was on 4.1, so I upgraded to 4.1.3 and then the atlas merging tool worked for me as it should. thank you!
