### ISSUE TITLE
Hidden buttons stay processing input when overlapped by an active button

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#7948]
**Operating system or device - Godot version:**
Godot 2.1.2, Linux XUbuntu 16.04.1

**Issue description:**

When you hide an button and when you show another button overlapping the first, the hidden button takes the input from the second (not hidden).
NOTE: I'm speaking of the TouchScreenButton node

**Steps to reproduce:**
See the test

**Link to minimal example project:**
[TouchButtonBug.zip](https://github.com/godotengine/godot/files/818959/TouchButtonBug.zip)
Just click in the green button, and then click in the area from "Click Here" label of the X button. See the output in editor.

**Comment by freemanfromgodotengine** [comment]
I can confirm. I was able to reproduce this bug also in Godot **2.1-stable** on Ubuntu 16.04.1 64-bit
