### ISSUE TITLE
Cannot set the transition node for Animationtree statemachines

### ISSUE THREAD

**Issue by christianbecker3** [godotengine/godot#79486]
### Godot version

Godot Engine v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 Threads)

### Issue description

Hi,
unfortunately the ability to select the exit destination for an animation node to a statemachine inside the animationtree seems to be broken.
Before 4.1, there was a menu which let you select the destination node for the animationtree. But when you connect now in 4.1 any node to a statemachine, you won't see the menu to select any node as an exit destination. It seems like that the transition from the animation to the statemachine doesn't work either. Also, if you open up projects before 4.1, all connections to from animations to statemachines are removed.
I also attached a freshly made project in 4.1, where you see that I was able to connect an animationnode to the statemachine, but I couldn't set anything up.

### Steps to reproduce

- Create an Animationplayer with two animations
- Create an Animationtree
- Add an animation to the Animationtree
- Add a statemachine to the Animationtree
- Add one Animation inside the statemachine
- Connect the animation outside the statemachine to the statemachine
- No prompt/menu whatsoever to select which node will be connected inside the statemachine

### Minimal reproduction project

[AnimationTreeTestProject.zip](https://github.com/godotengine/godot/files/12053728/AnimationTreeTestProject.zip)

**Comment by TokageItLab** [comment]
That feature was deprecated in #75759 for the pointer safety. The procedure for porting is commented in https://github.com/godotengine/godot/pull/75759#issuecomment-1512806261.
