### ISSUE TITLE
RigidBody2D leaves CollisionShape2D behind when using move_toward()

### ISSUE THREAD

**Issue by KVELLER** [godotengine/godot#79491]
### Godot version

v4.1.stable

### System information

Windows 10.0.19044

### Issue description

When using the move_toward method to move a RigidBody2D, its CollisionShape2D seems to stay behind despite the "Visible Collision Shapes" debug option suggesting everything is in order. Even though from my own testing it seems to affect StaticBody2D as well (I haven't tested other related types), SB2D got rid of the issue entirely when RB2D was bugging out on a grid-based project of mine. I haven't included those examples in the MRP for the sake simplicity/avoiding redundancy, but let me know if it would be useful to provide examples of that.

I apologize if this is a duplicate (or if this is entirely my own fault somehow; my experience with gamedev is fairly limited still), but I couldn't find any similar issues.

### Steps to reproduce

In the example provided in the MRP, you can hover your cursor over the icon to see "Here it is!" displayed on the console (via _input_event), but if you then click somewhere to move the icon, you should notice how the message is now only displayed if you hover over the icon's initial position.

### Minimal reproduction project

[move_toward_bug.zip](https://github.com/godotengine/godot/files/12054199/move_toward_bug.zip)

**Comment by KoBeWi** [comment]
I'm not sure if you should be changing RigidBody position this way (although I'm a bit surprised that using `_physics_process()` doesn't work either).

This code works:
```GDScript
func _integrate_forces(state: PhysicsDirectBodyState2D) -> void:
	state.transform.origin = position.move_toward(new_pos, 300 * get_physics_process_delta_time())
```

**Comment by AThousandShips** [comment]
You are indeed not supposed to modify the position manually like this, it will yield unpredictable results, see [here](https://docs.godotengine.org/en/stable/tutorials/physics/rigid_body.html#doc-rigid-body)

**Comment by capnm** [comment]
> This code works:
> 
> ```gdscript
> func _integrate_forces(state: PhysicsDirectBodyState2D) -> void:
> 	state.transform.origin = position.move_toward(new_pos, 300 * get_physics_process_delta_time())
> ```

> You are indeed not supposed to modify the position manually like this, moving it every frame or too often won't work correctly, it will yield unpredictable results, see [here](https://docs.godotengine.org/en/stable/tutorials/physics/rigid_body.html#doc-rigid-body)

The documentation only mentions 3D. This could be improved...

**Comment by AThousandShips** [comment]
I mean, it say so [here](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d) and [here](https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#collision-objects) as well

**Comment by capnm** [comment]
Maybe just add there a link to "a similar phy. problem as in 2D ..."  https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#description

or include the "works" example in class_rigidbody2d.html

**Comment by AThousandShips** [comment]
Sure, but I think it being said in pretty much every place should give the indication of how things work

But a good example of how to do it right is always good

**Comment by KVELLER** [comment]
Thanks for all the help! I actually did read the RigidBody2D documentation where, as you guys pointed out, it explicitly says to not do what I did, but I managed to forget... Oh well...

**Comment by capnm** [comment]
> Sure, but I think it being said in pretty much every place should give the indication of how things work

This issue is the proof that it  isn't enough ;)
Moving the RigidBody* position directly could additionally give the user an info message `this doesn't work...`

**Comment by AThousandShips** [comment]
> This issue is the proof that it isn't enough

It isn't though, they forgot, so how could more detailed information safeguard against that?

Adding an error would create false positives, as it's possible to set the position, assuming you don't do it all the time, you still need to be able to position rigid bodies

**Comment by aaronfranke** [comment]
Closing because this behavior is intended and already explicitly documented in several places. Of course, if anyone thinks of a specific documentation improvement they are welcome to do so, but there isn't really anything actionable here.
