### ISSUE TITLE
'print_rich' saves text to log with tags converted to ANSI symbols what makes closing tags unreadable.

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#79508]
### Godot version

4.1

### System information

Win 10

### Issue description

When using _print_rich_ to print some logs.

This is what log looks like in godot:
![image](https://github.com/godotengine/godot/assets/3350340/8e225258-e42c-4530-8077-cfb2dc9bb664)

This is how its is saved in log file:
```
0:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> gameUnitSpawner.spawn_path:../Units
1:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> No 'Players' node. Creating.
2:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=firebrick]E:[39m [1mTheGameState:[Wrapped:0][22m:> Cant find Players MultiplayerSpawner with namePlayersSpawner
[bgcolor=palegreen][30m[Serv]:>[39m[49m [1mTheGameState:[Wrapped:0][22m:>No 'Players Spawner (miltiplayer)' node. Creating. 
3:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> PlayersSpawner.spawn_path:../Players
4:[color=deepSkyBlue][gds]:>[39m[color=palegreen][S]:>[39m[mi:1|a:1]:>[color=gold]W:[39m [1mTheGameState:[Wrapped:0][22m:> gravity 9.8
```

This is how it is displayed when i try to read it from log file and draw it with RichTextLabel:
![image](https://github.com/godotengine/godot/assets/3350340/47371522-e13a-4818-97bc-0b08ecbfccb6)

Expected behavior: 
Closing tags printed as text, not as ANSI symbols. 

### Steps to reproduce

Print something with print_rich and them open log file.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
RotatedFileLogger should be modified to strip ANSI codes in the saved files. See https://github.com/godotengine/godot/pull/77263 for an example of a PR that modifies logger classes.

**Comment by Calinou** [comment]
I can still reproduce this as of 4.3.dev b091162a9.
