### ISSUE TITLE
SpinBox resets text when tooltip is showed

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#79507]
### Godot version

4.1

### System information

win 10

### Issue description

If you type text (not pressing enter) and hover mouse so tooltip shows up, then text dissapears.

![bug](https://github.com/godotengine/godot/assets/3350340/38c7904b-4e0c-4267-8cec-fca08da87013)

### Steps to reproduce

1. Add a SpinBox
2. Add a Tooltip Text
3. Run
4. type some text. DON'T PRESS ENTER
5. wait a second until tooltip will show up
6. Observe how text dissapeared.

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Can confirm on Linux Xfce X11 with embedding Windows and without embedding Windows in v4.2.dev.custom_build [a7583881a].

**Comment by AntonioDell** [comment]
Bisecting indicated, that the following commit introduced the issue:

[9500f8e69ae798c070c4daca9c46beaf8db18bd4] Fix Range-derived nodes not redrawing

**Comment by jsjtxietian** [comment]
> [[9500f8e](https://github.com/godotengine/godot/commit/9500f8e69ae798c070c4daca9c46beaf8db18bd4)] Fix Range-derived nodes not redrawing

Yes, in this commit it added `_update_text();` to `NOTIFICATION_DRAW`. Insided `_update_text();` it uses the shared range value which will not sync with use input if not submited.

https://github.com/godotengine/godot/blob/9500f8e69ae798c070c4daca9c46beaf8db18bd4/scene/gui/spin_box.cpp#L231-L235
