### ISSUE TITLE
Godot 4 fps performance regression

### ISSUE THREAD

**Issue by godtmilk** [godotengine/godot#79514]
### Godot version

4.0, 4.0.3, 4.1

### System information

linux-ubuntu20-xorg / windows 10    gtx 1070

### Issue description

If the same scene is used in Godot 3 and 4, then there is an undesirable disparity in performance with Godot 4 producing less fps.

Example 1.

A scene with multimesh and many instanced grass:

engine: godot 3.5
renderer: gles3
display window: 1024 x 600		
grass triangles: 600,000		
fps: ~600
![Screenshot from 2023-07-13 14-53-11](https://github.com/godotengine/godot/assets/139650648/052c9f01-5b9d-4b1f-91c7-d550cef9da41)

engine: godot 4.1
renderer: forward+
display window: 1024 x 600		
grass triangles: 600,000		
fps: ~330
![Screenshot from 2023-07-13 15-04-07_](https://github.com/godotengine/godot/assets/139650648/0b0b5da7-562f-4052-89d1-c0e2f0db0545)

engine: godot 4.1
renderer: mobile
display window: 1024 x 600		
grass triangles: 600,000		
fps: ~570

engine: godot 4.1
renderer: compatibility
display window: 1024 x 600		
grass triangles: 600,000		
fps: ~570

Also, in linux there is a huge difference between the fps when using an empty scene.

Example 2. 

An empty scene in linux:

engine: godot 3.5
renderer: gles3
display window: 1024 x 600
fps: ~5000
![Screenshot from 2023-07-13 11-33-02](https://github.com/godotengine/godot/assets/139650648/2bc954fe-bc35-4970-b5b3-7182c9694722)

engine: godot 4.1
renderer: forward+
display window: 1024 x 600
fps: ~1500
![Screenshot from 2023-07-13 11-38-02](https://github.com/godotengine/godot/assets/139650648/fbfe9dba-3dc9-4e33-a5d6-f9e5fecbbdfe)

engine: godot 4.1
renderer: mobile
display window: 1024 x 600
fps: ~1500

engine: godot 4.1
renderer: compatibiltiy
display window: 1024 x 600
fps: ~3200

- An empty scene in windows 10 did not have a big difference between the fps, both 
  3.5.2(gles3) and 4.1(forward+) having around 2500 fps.

### Steps to reproduce

Use the included projects or compare between godot 3 and 4 with your own scene.

### Minimal reproduction project

[Grass_Scene.zip](https://github.com/godotengine/godot/files/12062716/Grass_Scene.zip)

**Comment by Calinou** [comment]
Consolidating in https://github.com/godotengine/godot/issues/68959. Thanks for the report!

> Also, in linux there is a huge difference between the fps when using an empty scene.

On NVIDIA + Linux, fullscreen performance in Vulkan apps seems to be much lower in a maximized window compared to fullscreen. I noticed this when running `vkcube` in a maximized window versus actual fullscreen. As this is not exclusive to Godot, this isn't something we can fix.
