### ISSUE TITLE
Android export template not found

### ISSUE THREAD

**Issue by Cris-lml007** [godotengine/godot#79520]
### Godot version

4.0.3.stable.mono.official.5222a99f5

### System information

Kali GNU/Linux Rolling x86_64

### Issue description

it is not possible to download the export template for android, it is downloaded correctly for Linux, Windows and MacOs systems, I saw that this does not happen in the version of Godot 3.5.stable.mono.official.991bb6ac7.

### Steps to reproduce

# Files Godot 4.0.3.stable.mono.official.5222a99f5
![image](https://github.com/godotengine/godot/assets/83845332/f1f2305f-3f1f-4691-88b5-d095b2f3edfc)

### Minimal reproduction project

# Files Template Godot 3.5.stable.mono.official.991bb6ac7
![image](https://github.com/godotengine/godot/assets/83845332/0129c1df-203b-47fb-b5f9-7d31000bf958)

**Comment by bruvzg** [comment]
.NET version of 4.x doesn't support export for Android, iOS, and Web. See https://github.com/godotengine/godot/issues/70796#issuecomment-1618006609

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/68153.
