### ISSUE TITLE
Add support for glTF format

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7952]
Something to think about implementing. I'm not sure what collada supports as I haven't got to the animation and rigging side of things for my current project. But there is an interesting file format for 3d. It might be worth investigating for use in godot?

glTF github:
https://github.com/KhronosGroup/glTF

**Comment by set-killer** [comment]
I like it. It looks a nice replacement of the Collada format.

The good part is that the Blender GlTF exporter is aiming to become official ([source](https://www.khronos.org/rfq/request-for-quote-blender-gltf-exporter)).

Version 1.0 have been released on 2 June 2016, so maybe version 2.0 will be released soon. [Wikipedia](https://en.wikipedia.org/wiki/GlTF).

**Comment by set-killer** [comment]
It looks like the support for this format is increasing:

[Chromium/Chrome Browser Adds A glTF Parser](http://phoronix.com/scan.php?page=news_item&px=Chrome-Adds-glTF-Parser)

> ... Google adding a native glTF 1.0 parser appears to be related to their VR push with supporting VR content on the web.

> ... Microsoft has committed as well to even delivering glTF support within Microsoft Office ...

**Comment by reduz** [comment]
there was a discussion about this before, this is not a Collada replacement
and not an exchange format.

**Comment by set-killer** [comment]
But GLTF supports more features than the Collada format like PBR materials and shaders.

Autodesk have also [stated support](https://www.khronos.org/gltf) for this format.
Perhaps the Gltf will be widely adopted within the web, because of its json structure.

**Comment by Gibbz** [comment]
I noticed reduz was doimg some work on this. Looking forward to using it 😊

**Comment by akien-mga** [comment]
Indeed, to add more context to this issue: glTF 1.0 was not deemed very interesting for Godot, but the new 2.0 specification is pretty good and could really become a first class asset exchange format, so we decided to implement support for it.

**Comment by reduz** [comment]
glTF 2.0 is pretty much a completely different format than 1.0, so it was added. Closing this!
