### ISSUE TITLE
Text Drag and Drop Selection does not work for Control Nodes inside a SubViewport

### ISSUE THREAD

**Issue by danny88881** [godotengine/godot#79535]
### Godot version

v4.1.stable.official [9704596]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3598) - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 Threads)

### Issue description

For LineEdit, RichTextLabel, and TextEdit, the selected text drag-and-drop feature does not work. I am able to drag the text around, but when letting go, the text returns to its original position.

_might be duplicate of #28522_

### Steps to reproduce

Create two LineEdits and add them to a SubViewport.
Add a SubViewportContainer and move the SubViewport into the container.
Type some text inside one of the line edits and try dragging it into the other.

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Thank you for the report. This is a known issue and already reported in #28522.
#67531 is supposed to solve this problem.
Consolidating with #28522 as a duplicate.
