### ISSUE TITLE
is_input_handled() is True by default even though set_input_as_handled() has not been called

### ISSUE THREAD

**Issue by Gibdeck** [godotengine/godot#79539]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

is_input_handled() is returning True, even though set_input_as_handled() has not been called.

Example:
`func _input_event(viewport, event, shape_idx):
	print(viewport.is_input_handled())`

Returns 'True', should return 'False'

### Steps to reproduce

1. Create a new project and add a Node2D as the root
2. Add a child Area2D node containing a CollisionShape2D and a Sprite2D
3. Either create the _input_event(viewport, event, shape_idx) or connect _on_input_event(viewport, event, shape_idx)
4. Print viewport.is_input_handled()
5. True is printed.

### Minimal reproduction project

[input_test.zip](https://github.com/godotengine/godot/files/12063748/input_test.zip)

**Comment by Sauermann** [comment]
Currently `is_input_handled()` is by design only supported for `Control`-nodes, but not for `Node2D`-based nodes.
The reason is, that `Node2D`-based nodes are handled asynchronously and `_input_event` might even be called a frame later, than when the event was created.
related to #48788

**Comment by Zireael07** [comment]
This should be made clearer in the docs @Sauermann

**Comment by Gibdeck** [comment]
Hi, thanks for responding, yes the Docs advise that 

> Returns whether the current InputEvent has been handled. Input events are not handled until set_input_as_handled() has been called during the lifetime of an InputEvent.

Note that this working "correctly" in v4.0.3.stable.official [5222a99f5]: The viewport.is_input_handled() would return false with the example project. I was using it to prevent the click from propagating to Area2Ds that were under the one being clicked (i.e. a card game)

**Comment by Sauermann** [comment]
Please be aware, that this doesn't work "correctly" in all cases. For example, when you have more than a single event within a frame, then the input-handled-states of both events do interfere with each other with your approach.
The change `is_input_handled() == true` was introduced in #77595.

**Comment by Gibdeck** [comment]
Understood, I realise now that I've simply been using the incorrect node type from the very beginning. Thank you very much for your time and help.
