### ISSUE TITLE
"Lossless" Texture2D imports are not lossless on Mobile renderer

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#79532]
### Godot version

4.1.1 rc1

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Mobile:
![image](https://github.com/godotengine/godot/assets/40964335/f908a6b9-cfff-4702-a049-19ddc1b6a727)
![image](https://github.com/godotengine/godot/assets/40964335/36eea0ef-2237-4e04-9bdd-e406f9d8818e)

Forward+:
![image](https://github.com/godotengine/godot/assets/40964335/265174cb-fe0d-4c84-a63f-d588bd5e581a)
![image](https://github.com/godotengine/godot/assets/40964335/1e83f983-35f6-4614-bc06-ddb9996550b1)

This texture is set to lossless, yet is very compressed in the mobile renderer. Lossless is misleading 
![image](https://github.com/godotengine/godot/assets/40964335/a00b17b4-890d-4857-b8aa-836e4eacb840)

### Steps to reproduce

Import a texture in the mobile renderer and compare it to the forward plus renderer

### Minimal reproduction project

My sky as an example: 
![SkysphereNight](https://github.com/godotengine/godot/assets/40964335/a0dcac60-4cab-45ce-9ea4-eb603ed92231)

**Comment by clayjohn** [comment]
Lossless means that it is stored on the disk using a lossless image format like PNG or WebP. 

What you are seeing is a consequence of the mobile renderer using a lower precision viewport than the forward+ renderer. On mobile devices full HDR viewports really hurt performance, so you need to use a more limited format, it's just something you have to work around if you are targeting mobile.

**Comment by FireCatMagic** [comment]
> Lossless means that it is stored on the disk using a lossless image format like PNG or WebP.
> 
> What you are seeing is a consequence of the mobile renderer using a lower precision viewport than the forward+ renderer. On mobile devices full HDR viewports really hurt performance, so you need to use a more limited format, it's just something you have to work around if you are targeting mobile.

**Comment by Calinou** [comment]
For reference, this is documented in: https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#color-banding
