### ISSUE TITLE
RichTextLabel text padding options do not affect highlighted text

### ISSUE THREAD

**Issue by danny88881** [godotengine/godot#79534]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3598) - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 Threads)

### Issue description

Based on #63590 and the [documentation](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html#class-richtextlabel-theme-constant-text-highlight-v-padding) for text_highlight_h_padding and text_highlight_v_padding, changes to these values should affect the width and height of the color box created from highlighting text, but this is not the case as the size of the color box remains the same.

Note that these values do affect the size of the color box created by the [bgcolor] bbcode.

![image](https://github.com/godotengine/godot/assets/35647672/6c277402-2f43-4ec7-9f26-72d4717754d9)
This image depicts a RichTextLabel with both text_highlight_h_padding and text_highlight_v_padding set to 10, a magenta bgcolor, and the text being highlighted.

### Steps to reproduce

Add a RichTextLabel and enable text selection.
Change the values of  text_highlight_h_padding or text_highlight_v_padding to something non-zero.
Run the project and highlight the text.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I think this is by design. Text selection is generally expected to always look the same, for visual consistency within the project.
