### ISSUE TITLE
Dialog Minimises to dock

### ISSUE THREAD

**Issue by gemmomoh** [godotengine/godot#79536]
### Godot version

4.1 - stable

### System information

Godot v4.1.stable (970459615) - Freedesktop SDK 22.08 (Flatpak runtime) - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 4400 (HSW GT2) () - Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 Threads)

### Issue description

Popup dialogs are automatically minimized when opened

### Steps to reproduce

click on the add child node or instantiate child scene button, sometimes the dialog is visible, If it is, minimize it and close the dialog from the dock, the next time you try opening it, it will be minimized.

![image](https://github.com/godotengine/godot/assets/104901333/10f5d2ab-98fe-4301-949e-c12c7380d0f6)

The dialog opens in a minimized mode

![image](https://github.com/godotengine/godot/assets/104901333/0d6a46b0-0e60-43b0-940e-4b7bd687648b)
![image](https://github.com/godotengine/godot/assets/104901333/a6d28676-728f-4f92-b23d-157bb0ecb712)
[Screencast from 2023-07-16 10-20-12.webm](https://github.com/godotengine/godot/assets/104901333/61b7ae73-2dd8-40ce-a9ea-e83bb1fb68ce)

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/12063673/demo.zip)

**Comment by gemmomoh** [comment]
I'm using Ubuntu 23.04

**Comment by saierXP** [comment]
May be related to #77333

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77333.
