### ISSUE TITLE
Dragging a `Label` within a `PanelContainer` using the `Select` tool will cause a crash.

### ISSUE THREAD

**Issue by aawwaaa** [godotengine/godot#79548]
### Godot version

4.1 stable

### System information

Godot v4.1.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - Vulkan (Compatibility) - AMD HAINAN (DRM 2.50.0, 5.4.0-153-generic, LLVM 12.0.0) () - Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 Threads)

### Issue description

I experienced a crash in the editor when using the `Select` tool to drag a `Label` within the `PanelContainer`.
The `Select` tool should move the `PanelContainer` instead (as moving the `Label` doesn't make sense).

### Steps to reproduce

![2023-07-16 22-28-12 ScreenShot](https://github.com/godotengine/godot/assets/96404493/71feb7a8-2e83-4435-a7bb-accddb6dd59c)

### Minimal reproduction project

[label_crash.zip](https://github.com/godotengine/godot/files/12064282/label_crash.zip)

**Comment by KoBeWi** [comment]
Can't reproduce the crash. Dragging the label produces a warning, which is expected:
![image](https://github.com/godotengine/godot/assets/2223172/a3c506ef-b3b2-430a-8b25-ed868d0d53df)
Do you get any errors in the console? Maybe it's related to EditorToaster crashes for some reason (e.g. #79186)

> The Select tool should move the PanelContainer instead (as moving the Label doesn't make sense).

This should go to a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by aawwaaa** [comment]
console output:

    user@user-Lenovo-G500:~/桌面$ ./Godot_v4.1-stable_linux.x86_64 
    Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_utf32_to_keysym
    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_keymap_key_get_mods_for_level
    Found discrete GPU, setting DRI_PRIME=1 to use it.
    Note: Set DRI_PRIME=0 in the environment to disable Godot from using the discrete GPU.
    OpenGL API 4.5 (Core Profile) Mesa 21.2.6 - Compatibility - Using Device: AMD - AMD HAINAN (DRM 2.50.0, 5.4.0-153-generic, LLVM 12.0.0)
 
    Editing project: /home/user/godot/label_crash
    Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_utf32_to_keysym
    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0: undefined symbol: xkb_keymap_key_get_mods_for_level
    user@user-Lenovo-G500:~/桌面$ OpenGL API 4.5 (Core Profile) Mesa 21.2.6 - Compatibility - Using Device: AMD - AMD HAINAN (DRM 2.50.0, 5.4.0-153-generic, LLVM 12.0.0)
 
    ERROR: Condition "!texture_allocs_cache.has(p_id)" is true.
       at: texture_free_data (drivers/gles3/storage/utilities.h:111)
    ERROR: Cubemap Arrays are not supported in the GL Compatibility backend.
       at: texture_2d_layered_initialize (drivers/gles3/storage/texture_storage.cpp:763)
    ERROR: Attempting to use an uninitialized RID
       at: get_or_null (./core/templates/rid_owner.h:199)
    ERROR: Condition "!t" is true.
       at: texture_free (drivers/gles3/storage/texture_storage.cpp:705)
    WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
         at: _editor_init (modules/gltf/register_types.cpp:73)

(then it exited)

**Comment by KoBeWi** [comment]
Looks like some rendering-related crash. The error is similar to #79360.

**Comment by YuriSizov** [comment]
Note that these 4 errors happen before the editor is even loaded (since the Blend file warning is a part of the loading process). So this doesn't really tell us if there are any errors around the moment of crash. Still, those errors needs to be investigated, as they shouldn't happen.
