### ISSUE TITLE
CharacterBody3D with capsule collider stuck on edge of ramp with move_and_slide()

### ISSUE THREAD

**Issue by eldidou** [godotengine/godot#79542]
### Godot version

4.1.stable

### System information

Linux Vulkan (forward+)

### Issue description

When moving a CharacterBody3D with a CapsuleShape3D with move_and_slide() it can get stuck on the edge of a ramp sometimes. I would have expected the CharacterBody3D to slide past the edge.

![capsule](https://github.com/godotengine/godot/assets/7119609/6f55109a-0237-4c69-b236-f239c7b20864)

I could not reproduce it with a SphereShape3D, only with CapsuleShape3D.
I've tried playing around with different parameters like Motion Mode, Safe Margin, Snap Length, etc, but I could not find a setup that could prevent this issue reliably.

### Steps to reproduce

- create a CharacterBody3D with a CapsuleShape3D
- create a StaticBody3D with a ConvexPolygonShape3D in a shape of ramp
- move the CharacterBody3D toward the StaticBody3D so that it will move along and edge, using move_and_slide()
- When reaching the top of the edge the CharacterBody3D is stuck
See the Minimal reproduction project to have the positions and shapes details

### Minimal reproduction project

[capsule_collision.zip](https://github.com/godotengine/godot/files/12063855/capsule_collision.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/65596.
