### ISSUE TITLE
Editor crash with ERR_OUT_OF_MEMORY after a seemingly random amount of time

### ISSUE THREAD

**Issue by KMouratidis** [godotengine/godot#79555]
### Godot version

4.1, 4.1.1rc1

### System information

Windows 11, Forward+, Intel 13700k, 4070ti

### Issue description

The editor crashes without even being active. I tried running the editor like this: `Godot_v4.1.1-rc1_win64_console.exe --debug-paths --debug-stringnames -d -v` and got a ton of lines. I run the game once in debug mode and the final few lines are these (when the Quest disconnects):

```
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.0.0
OpenXR: Requested Vulkan version exceeds the maximum version this runtime has been tested on and is known to support.
- desired_version  1.2.0
- minApiVersionSupported  1.0.0
- maxApiVersionSupported  1.0.0
Vulkan API 1.3.242 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 4070 Ti
Requested V-Sync mode: Disabled

WARNING: res://addons/godot-xr-tools/hands/materials/caucasian_hand.material: In external resource #0, invalid UID: uid://dh7rys3who35c - usingg
     at: open (core/io/resource_format_binary.cpp:1053)
WARNING: res://addons/godot-xr-tools/hands/materials/caucasian_hand.material: In external resource #1, invalid UID: uid://c64s2fj3d1m8s - usingg
     at: open (core/io/resource_format_binary.cpp:1053)
ERROR: Viewport Texture must be set to use it.
   at: get_height (scene/main/viewport.cpp:133)
ERROR: Viewport Texture must be set to use it.
   at: get_width (scene/main/viewport.cpp:123)
ERROR: Viewport Texture must be set to use it.
   at: get_height (scene/main/viewport.cpp:133)
ERROR: Viewport Texture must be set to use it.
   at: get_width (scene/main/viewport.cpp:123)
ERROR: Interface not found.
   at: (servers/xr_server.cpp:227)
ERROR: 5 RID allocations of type 'N9OpenXRAPI18InteractionProfileE' were leaked at exit.
```

However, the editor does not crash at this point. It keeps going. I leave it open, go do something else (on the PC or even leave the PC completely) and then some seemingly random amount of time passes with no errors or warnings, and finally the editor crashes with these lines:

```
ERROR: Condition "!_ptrnew" is true. Returning: ERR_OUT_OF_MEMORY
   at: resize (./core/templates/cowdata.h:297)
ERROR: Condition "err" is true. Returning: true
   at: push_back (./core/templates/vector.h:317)
```

This has happened 3 times in a row with 4.1.1rc1 and I first noticed it on 4.1. I don't have split windows, and don't use multi-threading. I have 2 open scenes: one with lots of stuff ~including some instanced scenes with `@tool`~ and another that has some CSG meshes. I don't think it is really a memory error because Windows Task Manager reports ~20-25 GB / 64 GB being in use.

### Steps to reproduce

I open my project, run my game (debug / using Oculus+OpenXR), then disconnect the headset / close the oculus app, leave the editor running, and it crashes some time later (usually an hour or more later) even if I don't touch it. Not sure how much of this is related.

### Minimal reproduction project

The error occurs when I'm not using the editor, and some times when I'm away from the PC. I can't even think of how it can be reproduced 😞  Command-line flags or other debugging tips are appreciated.

**Comment by Calinou** [comment]
> This has happened 3 times in a row with 4.1.1rc1 and I first noticed it on 4.1.

Can you try following the same steps on 4.1 dev/beta/RCs? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.1/).

**Comment by KMouratidis** [comment]
Couldn't replicate, and it didn't happen again with 4.1/4.1.1rc1. I'll close this and if I stumble across it again, I'll spend more time and re-open. Thanks.
