### ISSUE TITLE
Godot Android editor custom themed monochrome icon doesn't show with the official APK

### ISSUE THREAD

**Issue by RustoMCSpit** [godotengine/godot#79552]
### Godot version

4 stablw

### System information

android 8+

### Issue description

the custom themed monochrome icon is not displaying

### Steps to reproduce

download .apk, look at icon

### Minimal reproduction project

n/a

**Comment by Calinou** [comment]
> download .apk, look at icon

Which APK are you referring to? Are you referring to the official Godot editor build?

**Comment by RustoMCSpit** [comment]
> > download .apk, look at icon
> 
> Which APK are you referring to? Are you referring to the official Godot editor build?

yes

**Comment by Ybaedbaenn** [comment]
I use: Godot v4.1.1.stable • LineageOS 18.1 • 20230614-NIGHTLY • a5y17lte • Vulkan (Mobile) • integrated Mali-T830 • (4 Threads)
My Files application is: com.android.documentsui • version 11

This is what the downloaded apk looks like for me:

![image](https://github.com/godotengine/godot/assets/84321760/09ba269b-ac02-43da-9a5b-1b835a90e7da)

**Comment by Ybaedbaenn** [comment]
Please correct me if I am wrong, but if I understand correctly, the apk icon should look like somewhat like this (https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/editor/icons/GodotMonochrome.svg - converted to dark mode):

![GodotMonochrome](https://github.com/godotengine/godot/assets/84321760/3eb2cc14-4a80-4ee0-9055-959d11a38882)
