### ISSUE TITLE
"Lookup Symbol" in editor does nothing to user-defined types

### ISSUE THREAD

**Issue by Spycemyster** [godotengine/godot#79565]
### Godot version

4.1

### System information

Windows 11

### Issue description

Right-clicking on a mention of a user-defined class and clicking "Lookup Symbol" does nothing. It should probably open up the referred to class.

### Steps to reproduce

`test_class.gd`
```gdscript
class_name TestClass
extends Node
...
```
`main.gd`
```gdscript
func test() -> TestClass:
   var test : TestClass = TestClass.new()
   return test
```

Right-clicking on any of the `TestClass` in `main.gd` and selecting "Lookup Symbol" should bring the editor to `test_class.gd` and bring the editor cursor to the class definition.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/73480.

**Comment by HolonProduction** [comment]
Closing this as it doesn't seem reproducible on 4.3.stable any more. If you are still experiencing the issue, please provide an MRP.
