### ISSUE TITLE
V-Sync doesn't limit FPS when switching virtual desktops

### ISSUE THREAD

**Issue by acadiansith** [godotengine/godot#79569]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - macOS 13.4.1 - Vulkan (Forward+, Mobile, Compatability) - integrated Apple M1, 60Hz display - Apple M1 (8 Threads)

### Issue description

When using V-Sync to limit FPS (the default), I noticed my CPU and GPU usage skyrocketing when I switched from Godot to other applications on other virtual desktops (e.g., to check documentation and tutorials, or to post this issue). My laptop would become quite warm, which is hard to do on an M1 chip unless you are maxing out the processor. This was quite surprising to me, as I only started using Godot last week, and I have only just begun a new project with maybe a dozen nodes and very light scripting, which should be light years away from approaching Godot's limitations.

I eventually determined that the same thing happens even for an empty scene, for both `Node2D` and `Node3D`. Concretely, I created a new scene, ran it (in focus), then switched desktops (triple finger scroll to the side, or triple finger scroll up, or selecting an app that lives on a different desktop). I tried this for all three Vulkan renderers, and the FPS always became unlimited upon desktop switch.

|Renderer|Expected FPS|Focused FPS|Switched Desktop FPS|
|-|-|-|-|
|Forward+|60|60|2000+|
|Mobile|60|60|2000+|
|Compatibility|60|120|~1000|

FPS has also appeared to be sometimes unstable when switching to other windows on the same virtual desktop, but it has been difficult to reliably reproduce this. However, the above steps will reliably cause the FPS to become unlimited every time, typically driving CPU and GPU usage to around 90%.

For what it's worth, if I switch to a different app on the same desktop, then move _that app_ to another desktop and follow it there, the FPS stays the same as when it was in focus 🤷.

If I manually limit the FPS to 60, the FPS remains limited as it should, so this is a V-Sync issue. 

Related issues/pull requests:

- #68269 
There, the CPU and GPU usage are high just from running the scene, but for me, the problem begins once I switch to another virtual desktop.
- #64475
- #56355
These two were both closed saying that V-Sync issues with Vulkan were solved in macOS 13, but my issue occurs on macOS 13. I also seem to be observing a similar effect to those issues in the Compatibility renderer (even in focus), since my FPS is twice the refresh rate of my display.
- #66367
Might help? It would be great to never see FPS above the monitor refresh rate, even if it isn't V-Sync.

### Steps to reproduce

1. Create a new project with any Vulkan renderer.
2. Create a new `Node2D` or `Node3D` scene.
3. Run the scene (V-Sync'd FPS).
4. Switch to a different virtual desktop (unlimited FPS).

### Minimal reproduction project

I display the FPS by adding a `Label` to the `Node2D` or `Node3D` with the following script:

```GDscript
extends Label

func _process(delta):
	text = "%s: %d" % [get_parent().name, Engine.get_frames_per_second()]
```

**Comment by Calinou** [comment]
cc @bruvzg
