### ISSUE TITLE
AABB for multimesh will calculated even with custom AABB `instance_set_custom_aabb`

### ISSUE THREAD

**Issue by mohsenph69** [godotengine/godot#79573]
### Godot version

4.1

### System information

Linux manjaro

### Issue description

This is a really unnecessary process which should be fixed

This is the file: `servers/rendering/rendering_rd/storage_rd`:
```cpp
void MeshStorage::multimesh_set_buffer(RID p_multimesh, const Vector<float> &p_buffer) {
	MultiMesh *multimesh = multimesh_owner.get_or_null(p_multimesh);
	ERR_FAIL_COND(!multimesh);
	ERR_FAIL_COND(p_buffer.size() != (multimesh->instances * (int)multimesh->stride_cache));

	if (multimesh->motion_vectors_enabled) {
		uint32_t frame = RSG::rasterizer->get_frame_number();

		if (multimesh->motion_vectors_last_change != frame) {
			multimesh->motion_vectors_previous_offset = multimesh->motion_vectors_current_offset;
			multimesh->motion_vectors_current_offset = multimesh->instances - multimesh->motion_vectors_current_offset;
			multimesh->motion_vectors_last_change = frame;
		}
	}

	{
		const float *r = p_buffer.ptr();
		RD::get_singleton()->buffer_update(multimesh->buffer, multimesh->motion_vectors_current_offset * multimesh->stride_cache * sizeof(float), p_buffer.size() * sizeof(float), r);
		multimesh->buffer_set = true;
	}

	if (multimesh->data_cache.size()) {
		float *cache_data = multimesh->data_cache.ptrw();
		memcpy(cache_data + (multimesh->motion_vectors_current_offset * multimesh->stride_cache), p_buffer.ptr(), p_buffer.size() * sizeof(float));
		_multimesh_mark_all_dirty(multimesh, true, true); //update AABB
	} else if (multimesh->mesh.is_valid()) {
		//if we have a mesh set, we need to re-generate the AABB from the new data
		const float *data = p_buffer.ptr();

		_multimesh_re_create_aabb(multimesh, data, multimesh->instances);
		multimesh->dependency.changed_notify(Dependency::DEPENDENCY_CHANGED_AABB);
	}
}
```

The problem is that even if you set a custom AABB the method `_multimesh_re_create_aabb(multimesh, data, multimesh->instances);` will be called, and this a really heavy process, and here we calculate something useless which we never use if we set a custom **AABB**
I tried different way to avoid that but unfortunatly it is not possible
I think someone who know how this is working should  

### Steps to reproduce

```cpp
    RenderingServer* rs = RenderingServer::get_singleton();
    RID scenario = get_world_3d()->get_scenario();
    RID multimesh = rs->multimesh_create();
    rs->multimesh_set_mesh(multimesh, mesh->get_rid());
    RID instance = rs->instance_create();
    rs->instance_set_base(instance, multimesh);
    Object* obj = memnew(Object);
    rs->instance_attach_object_instance_id(instance, obj->get_instance_id());
    rs->instance_set_custom_aabb(instance,AABB(Vector3(0,0,0),Vector3(1,1,1)));
    rs->instance_attach_object_instance_id(instance, 2);
    rs->instance_set_scenario(instance, scenario);
    rs->multimesh_allocate_data(multimesh, count, RenderingServer::MULTIMESH_TRANSFORM_3D, false, false);
    rs->multimesh_set_buffer(multimesh, buffer);
```
### This happen in CPU Particle too
Now If you debug Godot even you set a custom **AABB** method `_multimesh_re_create_aabb(multimesh, data, multimesh->instances)` will be called, and this method is so much heavy
This also bring down a lot **CPU Particle** performance, as this run many times when **CPU Particle**  is runing
I also want to change multiple **multimesh** during the run time and this is the biggest challenge in my way 

### Minimal reproduction project

"N/A"

**Comment by clayjohn** [comment]
It seems like the ``_multimesh_re_create_aabb()`` function should have an early out when a custom AABB is being used similar to what happens with ``mesh_get_aabb()``

https://github.com/godotengine/godot/blob/b8ed596769d2114797015833ce86f86ee872ecfa/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L600-L606

This might require adding an API for assigning a custom_aabb to the multimesh as right now it is only possible to assign an AABB to a mesh or to a GeometryInstance (to the node). The MultiMesh resource doesn't have a custom_aabb

**Comment by mohsenph69** [comment]
Yeah I look at **multimesh** it does not have custom AABB
But I think this will be easy to add
Specially this will be useful for **CPU Particle** as many use them in older devices

**Comment by clayjohn** [comment]
I agree. Recalculating the AABB is a very costly operation. Especially with high particle amounts

**Comment by ArdaE** [comment]
Related old issue: https://github.com/godotengine/godot-proposals/issues/957
