### ISSUE TITLE
Node2D visible change miss

### ISSUE THREAD

**Issue by rr13k** [godotengine/godot#79580]
### Godot version

4.1

### System information

macOs12.1

### Issue description

https://github.com/godotengine/godot/assets/45162461/b18743e4-97b9-423e-947b-868da0e432cc

### Steps to reproduce

frist be set   Node2D visible to hide,  command + s save scene， click reload scene 

### Minimal reproduction project

[pulseHero-main.zip](https://github.com/godotengine/godot/files/12068997/pulseHero-main.zip)

**Comment by dalexeev** [comment]
Could you please describe the bug in more detail? To me, it looks like unsaved changes were discarded when the scene was reloaded, so the node became visible, but this is correct. Note that not all contributors speak Chinese (sorry if I didn't guess the language) and therefore it may be difficult to understand the action in the video.

**Comment by KoBeWi** [comment]
You have an AnimationPlayer with a RESET animation that makes the node visible upon save.

**Comment by rr13k** [comment]
thank you,  i in AnimationPlayer  find `Reset On Save`  be set false .. Thank you very much for your help
