### ISSUE TITLE
Godot Editor does not import files correctly in web editor.

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#79594]
### Godot version

v4.1.1 stable

### System information

Windows 11 - Chrome & Firefox - Godot 4.1.1 - Web Editor

### Issue description

This issue also happens on Chromebook.

Every file won't import correctly and will always show an 'X' next to it. It is not possible to use these files basically making the editor worthless.

### Steps to reproduce

1. Open Godot Web Editor
2. Create Project
3. Open It
4. Check the FileSystem in the bottom-left

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> Every file won't import correctly and will always show an 'X' next to it. It is not possible to use these files basically making the editor worthless.

Which file type(s) did you test this with?

**Comment by Qainguin** [comment]
I tested with svg, png, and obj but I'm pretty sure every file won't work. Even the starting icon.svg doesn't load correctly.

**Comment by adamscott** [comment]
It's a regression introduced by #78347, found thanks to a git bisection. It seems that the modified file permissions mess with the web import process.
