### ISSUE TITLE
Character gets stuck and jitters when far from origin v4.0.3

### ISSUE THREAD

**Issue by Mschroeder95** [godotengine/godot#79592]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080, Windows 11 Home, x64, 12th Gen Intel(R) Core(TM) i9-12900K, 3200 Mhz, 16 Core(s), 24 Logical Processor(s)Installed Physical Memory, (RAM)	32.0 GB

### Issue description

Collisions become unstable when very far from world origin. Jittering and getting stuck are side effects.

Collisions in attached video are between a the ground StaticBody3D with ConcavePolygonShape3D and character CharacterBody3D with SphereShape3D.

Code uses move_and_slide().

Close to world origin:
https://github.com/godotengine/godot/assets/12117547/0bfbed5b-c9ea-44f6-9f8e-29ea00d21f7c

Far from world origin (586507)
https://github.com/godotengine/godot/assets/12117547/a95312ad-80de-4c9c-84c6-856206559315

### Steps to reproduce

Move map up on the y axis ~5000 units and character gets stuck sometimes.
Move map very far from world origin 586507 on the z axis and jittery unstable movement happens

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
I would guess, that you run into the problem described in https://godotengine.org/article/emulating-double-precision-gpu-render-large-worlds/
Using a double precision float build might help.

**Comment by Calinou** [comment]
This is expected when using single-precision builds, which is what official engine builds use for performance reasons. See [Large world coordinates](https://docs.godotengine.org/en/latest/tutorials/physics/large_world_coordinates.html) in the documentation.
