### ISSUE TITLE
FileSystem Tab Enhancements

### ISSUE THREAD

**Issue by grabiller** [godotengine/godot#796]
1) Fold folders by default. (*edit:* see #7488, fixed by #7492)
When you have a large amount of assets in folders trees you end up with the very long tree widget content.

2) An option to Unfold/Fold all Folders at once. (fixed by #7492)

3) Remember state of the FileSystem Tab (including the currently selected file, folded/unfolded folders,..) no matter what (saving a scene reset selection, refreshing reset folding,..)

4) Add ability to "tick" Folders as well as Files so we can isolate a Folder (and its content) with the "Star" icon.

5) CTRL+Tick a file or a folder would "untick" all other "ticked" files/folders
CTRL or wathever modifier.

**Comment by akien-mga** [comment]
The FileSystem tab has changed a bit for 2.0, so it would be worth checking again in the current master branch if those proposals are still relevant.

**Comment by akien-mga** [comment]
1), 2) and 3) are still valid, and would be nice enhancements.

**Comment by mateka** [comment]
I would like to try to resolve this issue. But I have one question: What would be the best way to invoke "unfold/fold all folders" action? Context menu in Tree? Button or context menu in filesystem_dock?

**Comment by TX256** [comment]
I've always liked how Intellij IDEA handles this: if you fold an item in the tree, all its children will also be recursively folded. So, to fold all, you simply fold the root node.

**Comment by chanon** [comment]
+1

**Comment by akien-mga** [comment]
1. and 2. were fixed by #7492.

**Comment by akien-mga** [comment]
Most points here have been fixed.
