### ISSUE TITLE
Panel scene works but doesn't display properly after its visibility is changed to true

### ISSUE THREAD

**Issue by moonsong96** [godotengine/godot#79601]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 11 OS Build 22621.1992 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

All of these panels (cards) below are changed from visibility being false to true. The last chosen panel always has display issue, but the buttons and everything is correct.

![image](https://github.com/godotengine/godot/assets/65817286/918911ab-d815-455d-bf6c-f00756ca81f4)
![image](https://github.com/godotengine/godot/assets/65817286/80ab4e75-2c21-4a2e-9bb8-09482b48463a)

### Steps to reproduce

1. Open BoardGame.tscn and run this scene
2. There are 7 panels (cards) which are instantiated, so click those buttons until 2 cards are left then reset to 7 cards
3. There will always one card with display problem as written, but those buttons are still there and work well

### Minimal reproduction project

[Panel Display Issue.zip](https://github.com/godotengine/godot/files/12076884/Panel.Display.Issue.zip)

**Comment by Rindbee** [comment]
The `visibility_changed` signal is used, and the method connected to that signal may modify `visible`, which causes a second `visibility_changed` signal to be emitted recursively.

```
visible = false
configured as invisible (A)
visibility_changed
    visible = true
    configured as visible (B, replacing A)
    visibility_changed
        ...
    configured as visible (C)
configured as invisible (D, replacing C)
```

This may cause the setting state **before** `visibility_changed` to be the setting state when **visible**, and the setting state **after** `visibility_changed` to be the setting state when **invisible**.

**Comment by moonsong96** [comment]
Sorry for late reply. Now I understand where my problem is. Thanks for pointing that out :)
