### ISSUE TITLE
Some inconsistencies in classDB's bindings

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#7960]
Hi,

I'm currently using classDB introspection system to generate bindings for godot-python.
I've found some troubles in the bindings:

- audio_server.cpp: `AudioServer.set_state` and `AudioServer.generate_state` are mark to return a `AudioServerState`, but there is no reference of this type anywhere
- core_bind.cpp: `_Marshalls::base64_to_raw` is marked to return a `RawArray` which is an out-of-date alias to `PoolByteArray` (i.e. `PoolVector<uint8_t>`)
- visual_script: `VisualScriptPropertySet` properties' names start with `property/...`, this is a pretty strange name given slash is not a valid variable character for most languages (including C++ and GDscript) so doing `VisualScriptPropertySet.property/set_mode` is impossible...
- control.cpp: `Control.get_minimum_size` is binded two times (has a virtual and a regular method)
- packet_peer.cpp: `PacketPeer.put_packet` is declared has returning an `Error` type which is never defined within classdb

I'm ready to send a PR to solve this (seems all minor issues to me, but some for them like the `property/...` stuff is more like something I didn't catch...)

**Comment by karroffel** [comment]
@touilleMan `Error` is an enum that's used almost everywhere and even core types use it (they just *say* it's an `int`). I just made Error a core type so my bindings don't try to include a file for it.

**Comment by karroffel** [comment]
@touilleMan Also you forgot [PoolFloatArray](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/core/variant.cpp#L169)

**Comment by karroffel** [comment]
@touilleMan I agree that the property naming situation isn't perfect, but you're not forced to use the property name as the property name (that sounds confusing). You could have your bindings transform the name so it's valid. (Just for as long the names are rubbish for most languages)

**Comment by touilleMan** [comment]
@karroffel you're right about this, however I thought it was worth mentioning given it's part of the papercuts I got working on the subject (i.e. if the API stays this way, I have to do a workaround for this case - for example using custom name as you said -)

**Comment by karroffel** [comment]
@touilleMan I fixed the ClassDB issues. I think the property names deserve an issue on their own. GDScript encourages the use of properties over getter and setter functions. This is problematic because you can't use many properties that way. So GDScript has the same problems
