### ISSUE TITLE
Strange game crash 4.1.1 stable

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#79608]
### Godot version

4.1.1 stable

### System information

windows 11

### Issue description

the game is crash with this error at console
![image](https://github.com/godotengine/godot/assets/13792627/a950eef5-4c6a-48be-943b-5edbbdf21043)
i have the same issue #77565 but with different index (3) this is happen with godot 4.0.3. but this time the crash causing by index (0) with version 4.1.1 stable
i assume the problem with 4.0.3 it already fixed by #79141 but 
as always godot is not pointing where is part of my code that causing it
![image](https://github.com/godotengine/godot/assets/13792627/61eb2398-de10-44d2-85c3-66e5430471cf)
the debugger show no red error anywhere only warning. 
as per by testing with debug build 4.0.3 suggested by dev the error is pointing at godot physic2d somewhere
![image](https://github.com/godotengine/godot/assets/13792627/9fadb28f-2c4d-4692-9690-322f84339bc6)
but at 4.1.1 it show pretty clear where it is. i hope this can be fixed. 
since the trigger is at different index i opened this new issue.

### Steps to reproduce

i have no idea it happened after 10 minute of game play

### Minimal reproduction project

not sure how to reproduce it but i hope the console print is enough to show where the error is.

**Comment by akien-mga** [comment]
Can you test if the issue is still reproducible in 4.2-beta3 or later?

**Comment by fian46** [comment]
> Can you test if the issue is still reproducible in 4.2-beta3 or later?

It is disapear in rc 1 can close this now
