### ISSUE TITLE
Can't access script methods of instanced scene

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#7961]
**Operating system or device - Godot version:**
Linux
latest git

**Issue description:**

I have a scene (a single button) with a script attached to its root:

`dock.tscn:`
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://addons/dock/dock.gd" type="Script" id=1]

[node name="Button" type="Button"]

margin_right = 12.0
margin_bottom = 20.0
rect_clip_content = false
mouse_filter = 0
toggle_mode = false
enabled_focus_mode = 2
shortcut = null
group = null
text = "Test Button"
flat = false
script = ExtResource( 1 )
```

`dock.gd:`
```gdscript
extends Button

func _ready():
	pass

func test():
	print("test")
```

 The methods of the instanced script aren't accessible.

**Steps to reproduce:**

Trying to access it like this

`dock_plugin.gd`
```gdscript
tool
extends EditorPlugin

var dock

func _enter_tree():
	dock = preload("res://addons/dock/dock.tscn").instance()
	dock.test()

	add_control_to_dock( DOCK_SLOT_LEFT_UL, dock)


func _exit_tree():
	remove_control_from_docks( dock )
	dock.free()
```
results in the following error:
```
SCRIPT ERROR: _enter_tree: Invalid call. Nonexistent function 'test' in base 'Button (dock.gd)'.
   At: res://addons/dock/dock_plugin.gd:8.
```

**Link to minimal example project:**

[dock-test.zip](https://github.com/godotengine/godot/files/820007/dock-test.zip)

**Comment by Zylann** [comment]
I think the "tool" keyword is being misunderstood. It looks like it means only tool scripts are being "loaded", instead of "executed". If you use the "tool" keyword in your other script it will be accessible.

**Comment by tagcup** [comment]
Thanks a lot for the clarification! This was meant to be a minimal project, demonstrating the issue, and yes, adding the tool keyword I "forgot" to add fixed the issue ("forgot" in quotes, because what actually happened is the editor crashed when I added the tool, and apparently it didn't save the script).

However, in my actual project, I'm having the same problem despite having tool in every single script. I'll try to isolate the issue further.

**Comment by tagcup** [comment]
After bisecting the issue, I found that the script has a syntax error! It seems editor plugin script errors don't appear in Debugger's Errors tab, so one has to pay close attention to stderr/stdout output.

I'm sorry about the invalid issue!
