### ISSUE TITLE
GPUParticles2D & GPUParticles3D flicker with PROCESS_MODE_DISABLED

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#79619]
### Godot version

4.1.1.

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3203) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When the process_mode is PROCESS_MODE_DISABLED gpu particles flicker between 2 frames at a rate it almost looks like 2x particles.
In the reproduction project I included also cpu particles and those are acting as expected.

### Steps to reproduce

Create a scene using gpu particles (2D or 3D)
Toggle process mode (scene or particles directly) to PROCESS_MODE_DISABLED

### Minimal reproduction project

[Particle process mode.zip](https://github.com/godotengine/godot/files/12083669/Particle.process.mode.zip)

ui_accept used for toggling process mode for particles.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/50824, as this is due to the same cause.
