### ISSUE TITLE
Editor : Scene Tree icons' tooltips dont match icon when narrow

### ISSUE THREAD

**Issue by toafloast** [godotengine/godot#79629]
### Godot version

4.1.stable

### System information

Windows 11 (x64), Intel(R) Core(TM) i5-9400 CPU, Vulkan,  NVIDIA GeForce GTX 1660 Ti driver version 528.24

### Issue description

When resizing the Scene Tree view, making it narrow, the tooltips of the icons no longer match the position of the icons. 
The tooltip rect is pushed off to the side.
Video showing bug:

https://github.com/godotengine/godot/assets/104696964/bc9918a0-4f4c-4722-aee3-7887d0e3dd5d

### Steps to reproduce

Make your Scene Tree view narrow. Hover over the icons. The tooltip activation area does not match the icon.

### Minimal reproduction project

N/A

**Comment by Ybaedbaenn** [comment]
I can confirm the bug for the version v4.1.1.stable.official.bd6af8e0e.

My system: 
Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)
