### ISSUE TITLE
Godot 4.1.1. Slow Project Launch

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#79628]
### Godot version

4.1.1.

### System information

Godot v4.1.1.stable - Windows 6.1.7601 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 1030 () - AMD Athlon(tm) II X2 250 Processor (2 Threads)

### Issue description

Nearly ago, i've started conversion of my project to Godot 4. This is not really a small-scale one, it does have quite a bunch of files, let me list amount of them by file types:
```
tres: 931 (that includes certain materials too)
tscn: 269 
material: 342
glb: 831
gd: 550 (GDScript, quite a bunch of the ones with class_name's)
png: 1187
tga: 587
wav: 120
mp3: 222
```

At first, i've got a lot of errors on launch, and, because of that, i thought that causes an issue with RAM (it used it entirely). Luckily i could split the game by parts and repair them separately. Some of them caused the issue by running editor logic that caused extreme RAM usage, which is fixed at this moment. One module after another, and i fixed all errors. Yet i still started to notice that launching times of this Godot project are still quite long (from 20 minutes, to 1 hour), with usage of almost entire RAM available. After experimenting a little, i started to see an issue in amount of the files that project has (10 GB, 10.357 files, 824 folders), the less files i had, the faster it worked. I've done as much troubleshooting as i could've done yet i'd be glad to hear more ways to check if i missed something.

I perfectly understand that i need to upgrade my hardware, and, believe me, i'd be glad to get one, but at this moment it is impossible. I'm pretty sure, more powerful hardware can resolve the issue, yet i'm still willing to report this issue with hope that issue may have other solutions as well!

### Steps to reproduce

Potentially, you need a project with the mentioned amount of resources. I'm not sure which one you need exactly, so that's why i mentioned the file types.

### Minimal reproduction project

I'd be glad to share my project, yet i'm not sure if contributors are willing to dive into this junkyard. I'm going to make a MRP once i will be sure that certain steps actually affect the launch times. Sorry!

**Comment by Dadaskis** [comment]
I have to add more info: I didn't have had this issue on 3.x branch. The issue occurs only on 4.x. branch for me.

**Comment by clayjohn** [comment]
Unfortunately we can't do anything with the information you have provided. Since you can't provide an MRP for someone else to test, you may need to do more testing to locate where the source of the slowdown is. 

In particular it would be useful to highlight which parts of the import process is slower than in 3.x (is it textures, scenes, meshes, audio?).

**Comment by Dadaskis** [comment]
I need to find time to make MRP, in some way to fill the project with all mentioned file types (to replicate the state of the project as close as possible). Just curious question, how to share such type of MRP? This can't be just .zip i think, so can i just make a public repository where i will upload the files to share with everyone here?

> In particular it would be useful to highlight which parts of the import process is slower than in 3.x (is it textures, scenes, meshes, audio?).

That's what scaring me a lot - i don't know, the only thing i noticed that the more files i've added (no matter which type of resource) it slowed it down more and more. I imported files once, everything is fine with all of them, importing times remain same for me (in comparison to 3.x). But each time i launch the project in editor (after picking it in project manager window), it is just launching really slowly while using abnormal amount of RAM (from 400 MB of Godot 3 to 3.2 GB of Godot 4). I have a feeling that file system is iterating through all files for some reason, yet i'm not sure how it works inside. Just curious question, it is said that Godot 4 is using more RAM due to certain new optimization techniques (which is totally understandable) yet, i wonder, are there any changes related to functionality of file system?

**Comment by Calinou** [comment]
> I have a question, how to share such type of MRP? This can't be just .zip i think, so can i just make a public repository where i will upload the files to share with everyone here?

Yes, a public repository is acceptable too :slightly_smiling_face:

**Comment by Dadaskis** [comment]
Couldn't replicate the problem in MRP, yet noticed one interesting detail that i missed.

So, the problem is fixed. How did i fix it? Simple.
- Locate .godot folder in your project folder.
- Locate .import folder in your project folder too.
And do following actions:
- Totally annihilate them.
- Put them in flames and watch them slowly burn down.
- Nuke them.
Or simply...
- Delete them both.

So, if anyone else having issues with suspiciously long project launch times, that can be helpful to try. And trust me, 1 hour of reimporting is much, much better than wasting more than a week on detecting obscure bug that started to drive me crazy.

.godot may not be needed to be removed, but... why not after all?

I'm sorry for writing not in a really polite, official way, it was a rough week.

Thank you all for responses and i'm really, really sorry for bothering you with providing confusing info, i just started to lose hope to fix it, and, of course, i hope this comment is going to be helpful for anyone who is going through conversion.
