### ISSUE TITLE
Помогите пожалуйста с проблемой!

### ISSUE THREAD

**Issue by N3TCX** [godotengine/godot#79635]
### Godot version

3.5

### System information

Windows 10

### Issue description

Я хотел повторить ролик на ютубе где он создает 2Д платформер за 10 минут.
Ссылка на ролик: https://www.youtube.com/watch?v=xFEKIWpd0sU
На просмотре 1:34 возникли проблемы.
Автор видео переносит файл .tres в Tile set. Когда я это повторял у меня выдало ПРЕДУПРЕЖДЕНИЕ где написано:
"Выбранные ресурсы (MeshLibrary) не соответствуют типам, ожидаемым для данного свойства (TileSet)."
Что делать?

### Steps to reproduce

![ошибка](https://github.com/godotengine/godot/assets/139920257/6f1923a5-ef59-4f54-bfcf-40d97c650d3c)

### Minimal reproduction project

![ошибка](https://github.com/godotengine/godot/assets/139920257/2bc480c6-ee53-41f7-9a67-20aa5fb4e3cd)

**Comment by AThousandShips** [comment]
Please make reports in English, use translation software if needed, English is the official language of these forums

**Comment by Ybaedbaenn** [comment]
**Translation:**

**Title:** Please help with the problem!

**Issue description:**
I wanted to replicate a YouTube video where he creates a 2D platformer in 10 minutes.
Link to the video: https://www.youtube.com/watch?v=xFEKIWpd0sU
When watching at 1:34 there was a problem.
The author of the video moves the .tres file to Tile Set. When I repeated this I got a WARNING where it says:
"The selected resource (MeshLibrary) does not match any type expected for this property (TileSet)."
What to do?

**Comment by Ybaedbaenn** [comment]
@N3TCX Please reopen the issue in English, and make sure to follow the guidelines that the bug report template provides.

**Comment by AThousandShips** [comment]
Or edit the issue, you can change the text and title

**Comment by KoBeWi** [comment]
It would be helpful if you attached the zip with your project as Minimal Reproduction Project instead of repeating the screenshot.

**Comment by dalexeev** [comment]
This tracker is for reporting bugs in the engine, not for tech support. Please use [Community channels](https://godotengine.org/community/) to ask for help. See also the [User Groups](https://godotengine.org/community/user-groups/) page, which lists Russian local groups too.

As for the error, I think you have created a resource of the wrong type `MeshLibrary`, while `TileSet` is expected.

**Comment by KoBeWi** [comment]
Ah now I noticed the resource icon. Yeah, this is a MeshLibrary. You used wrong type and the error says so correctly.
