### ISSUE TITLE
Forward+ projects don't open

### ISSUE THREAD

**Issue by donotforgetmycode** [godotengine/godot#79631]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - Intel(R) HD Graphics 610 (Intel Corporation; 22.20.16.4815) - Intel(R) Pentium(R) CPU 4415U @ 2.30GHz (4 Threads)

### Issue description

I cannot open projects that use the Forward+ renderer. If I try to open one, Godot just closes. I can only open Compatibility projects.

### Steps to reproduce

Try to open a project that uses the Forward+ renderer.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58927. (Intel Haswell IGPs do not support Vulkan in any form on Windows, and only in limited form on Linux. We don't expect the limited support to be sufficient to run Godot's Vulkan renderers.)
