### ISSUE TITLE
Editor : Right-clicking 'Filter Nodes' field duplicates 'Filters' section in dropdown

### ISSUE THREAD

**Issue by toafloast** [godotengine/godot#79630]
### Godot version

4.1.stable

### System information

Windows 11 (x64), Intel(R) Core(TM) i5-9400 CPU, Vulkan,  NVIDIA GeForce GTX 1660 Ti driver version 528.24

### Issue description

Every time you right click the Filter Nodes field, it duplicates the 'Filters' section in the dropdown.

https://github.com/godotengine/godot/assets/104696964/b8d867c9-ba31-47c5-91c8-23cfa02f1c89

### Steps to reproduce

Rightclick the Filter Nodes field.

### Minimal reproduction project

N/A

**Comment by Ybaedbaenn** [comment]
I can confirm the bug for the version v4.1.1.stable.official.bd6af8e0e.

My system:
Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

**Comment by toafloast** [comment]
With enough right-clicks it becomes quite silly

https://github.com/godotengine/godot/assets/104696964/be90176d-4fe6-4008-86ce-e64bffa6dfa9
