### ISSUE TITLE
Error when export to android

### ISSUE THREAD

**Issue by wozpi** [godotengine/godot#79649]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - macOS 12.6.0 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7516/@RichTextLabel@7518). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7516/@RichTextLabel@7518). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7516/@RichTextLabel@7518). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7516/@RichTextLabel@7518). Use call_deferred() or call_thread_group() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7516/@RichTextLabel@7518). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7520/@Button@7531) can only be accessed from either the main thread or a thread group. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7520/@Button@7531). Use call_deferred() or call_thread_group() instead.
  This function in this node (/root/@EditorNode@17640/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@PanelContainer@7501/@VBoxContainer@7502/@EditorLog@7532/@VBoxContainer@7520/@Button@7531) can only be accessed from the main thread. Use call_deferred() instead.
  Caller thread can't call this function in this node (/root/@EditorNode@17640). Use call_deferred() or call_thread_group() instead.

### Steps to reproduce

Error show after export to android

### Minimal reproduction project

<img width="1330" alt="Screen Shot 2023-07-19 at 13 02 52" src="https://github.com/godotengine/godot/assets/32153950/6dce8af5-531a-45f3-b887-674c89f9d31d">

**Comment by Calinou** [comment]
Can you reproduce this when exporting for another platform than Android?

**Comment by wozpi** [comment]
No i don't have error like that when exporting for another platform than Android

**Comment by LostShadowGD** [comment]
weird

**Comment by Calinou** [comment]
@wozpi Can you (or anyone else) still reproduce this bug in [Godot 4.2.1](https://godotengine.org/article/maintenance-release-godot-4-2-1/) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if anyone can provide the requested information this can be reopened
