### ISSUE TITLE
Multiple Sprite3D being rendered in weird order

### ISSUE THREAD

**Issue by dejaime** [godotengine/godot#7964]
Systems tested:
http://pasted.co/ca4970b9
http://pasted.co/d1a10e38

Version: v2.1.2.stable.official

**Issue description:**
Placing a big Sprite3D in front of a small Sprite3D may render the big one in front of the small one, depending on the view angle.

Adding a TestCube between both sprites creates a curious side-effect, here the big sprite on the back is rendered in front of the small sprite, except where the latter overlaps the TestCube, where the small sprite is rendered as expected.

It happens on both the editor and when running.

**Steps to reproduce:**
![Reproduce](http://i.giphy.com/l0IybikWcfYcFyoFO.gif)

**Link to minimal example project:**
[Issue.tar.gz](https://github.com/godotengine/godot/files/820131/Issue.tar.gz)

**Comment by bojidar-bg** [comment]
Hm, not sure if you can change the sprite3d's material, but if you can, could you try to set it's "depth draw" to "always" or to "pre-pass alpha"?

**Comment by dejaime** [comment]
Using a material override and using those settings seems to work.

![image](http://imgur.com/fFaaxxcl.png)
(don't mind the corners, alpha was disabled on the material override)

Still, it is definitely not the behavior I expected, when I used the two Sprite3D, where one is in front of the other. I would expect that in case those were billboards, when the small sprite is overlapped by the big one at around the same angle...

If I change the diffuse parameters on the material to add alpha this is what happens:
![material test](http://imgur.com/4YLFkscl.png)
The left one is a common Sprite3D, the one in the middle has _Depth Draw_ set to _Always_, and the one on the right to _Pre-Pass Alpha_.

**Comment by dc740** [comment]
Hi, why was this closed? I have quite a few textures in the same scene. It's basically the body with different parts of an armor, a shield, a weapon, all in Sprite3D. And I'm still hitting this. Is there any way to set the order?

Thank you

**Comment by hikari-no-yume** [comment]
Depth-sorting is inherently problematic. Turn on pre-pass alpha.

**Comment by dc740** [comment]
Thank you very much.
For future reference on anyone having a similar issue:
Click on the Sprite3D -> Flags -> Alpha Cut -> Select <Opaque Pre-Pass>
Move your textures slightly back and forth on Z to set the order

**Comment by dejaime** [comment]
> Hi, why was this closed?

Hi, I closed this since I moved on to another engnie for that specific project, as I did not have the time to wait nor the knowledge to contribute a fix. This is a really hard problem to tackle, in general. In the shadow of a the new engine version (what included a new renderer) this issue was not really all that useful for the project anymore, and it made sense to just close it.

I do believe this problem still exists in 3.1, but in case it happens to affect anyone, I'd say it would make more sense to open a new issue for it.

Sorry for the late reply.

**Comment by gerrywastaken** [comment]
@dejaime I don't think it should have been closed, even if it was no longer useful to you.

@hikari-no-yume Any idea why this wouldn't just be enabled by default if the transparency option above it is enabled?

**Comment by hikari-no-yume** [comment]
@gerrywastaken perhaos the pre-pass is somewhat expensive so Godot wants to avoid it unless we really need it?

**Comment by gerrywastaken** [comment]
> The general limitation around transparency sorting is now documented on the [3D rendering limitations page](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting).

I had actually just read that and honestly, it left me with more questions. :D

> Enabling opaque prepass by default isn't a good idea due to the added rendering cost. Only pay for the features you actually need slightly_smiling_face

That makes sense. The only problem is that when your sprites disappear behind something like a massive plane mesh, it can take quite some time before you discover what is actually happening. It wasn't until lowering my camera after an hour (or perhaps longer) that it became clear that it was just the ordering that was making the sprite vanish. Some sort of warning on the hover text of the transparency option, or a warning when it's enabled would be very helpful. It won't help me anymore, now that I know, but for others, it could save a lot of time.

> Either way, this should be addressed by [godotengine/godot-proposals#3986](https://github.com/godotengine/godot-proposals/issues/3986) and its implementation #60704.

Thank you for the link!

**Comment by dejaime** [comment]
@gerrywastaken maybe not, but this was a 2.1 bug. The minimal project does not work on current engine versions, the reproducing steps are not the same, and this might not even be an issue on 3.5 / 4.0 afaik. This to me means the issue was no longer relevant to the engine, except maybe for reference.

If someone were to face a similar problem and end up stumbling on this issue, this could give them some insight. But that's about it, they'd still be better off opening a new issue for their engine version, with new repro steps and example project.
