### ISSUE TITLE
Opening native file dialog on Windows makes the base window unresponsive

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#79642]
### Godot version

4.2 0c2144d

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you use `DisplayServer.file_dialog_show()`, Godot freezes until the dialog is closed:

https://github.com/godotengine/godot/assets/2223172/a2a33ab9-327f-4de3-a7ea-f8ef8bf8e117

For reference, here's how Chrome handles it (🔊):

https://github.com/godotengine/godot/assets/2223172/1fa0e742-a340-4be5-9220-223a375e134e

### Steps to reproduce

1. Run this on Windows
```GDScript
@tool
extends EditorScript

func _run() -> void:
	DisplayServer.file_dialog_show("Dialoog", "C:/", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_FILE, [], Callable())
```
2. Click Godot like crazy until it dies

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/79693
