### ISSUE TITLE
Old type names / inconsistency in typenames exposed to ClassDB

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#7965]
I'm doing stuff for the DLScript module. I'm generating wrapper classes in C++.

I noticed following problems:

`Control::get_minimum_size()` is registered twice: once as `virtual`, once as `const`. This is a problem because `ClassDB::get_method()` can't handle overloaded functions / functions with the same name.

[PoolFloatVector](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/core/variant.cpp#L169), that's `PoolRealArray` now.

[RawArray](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/core/bind/core_bind.cpp#L2081) is `PoolByteArray` now.

If a method returns `Variant` it's registered as `void` in ClassDB.

[AudioServerState](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/servers/audio_server.cpp#L991) is being passed to AudioServer::set_state, but the type `AudioServerState` does not exist.

--------------------------------

I'll fix this as soon as possible, just want to note it down here.

**Comment by bojidar-bg** [comment]
> If a method returns Variant it's registered as void in ClassDB.

Not all of them, just those which aren't bound properly.

**Comment by touilleMan** [comment]
@karroffel I was first on this #7960 :smiley:

**Comment by karroffel** [comment]
@touilleMan damn. I opened the issue at 7am, needed sleep, didn't check for old issues 😄 My bad
