### ISSUE TITLE
Assigning global_position it causes local rotation to be overridden by global rotation

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot#79651]
### Godot version

4.1

### System information

WIn 11

### Issue description

Assigning global_position seems to replace local rotation with global rotation on objects. When controlling a Camera without assigning global_position, the camera can rotate freely. However, if global_position is assigned, the camera rotation gets clamped when exceeding -90 or 90 degrees.

In summary: 
Assigning global_position affects object rotation
It causes local rotation to be overridden by global rotation

https://github.com/godotengine/godot/assets/52212525/f430694a-724c-47a9-893f-d9b2b26fea99

### Steps to reproduce

Commenting out the line rotate without errors.
func _process(delta):
	global_position = marker_3d.global_position

### Minimal reproduction project

[InputEventMouseMotion.zip](https://github.com/godotengine/godot/files/12092956/InputEventMouseMotion.zip)

**Comment by AThousandShips** [comment]
I suspect you're running into either precision errors or gimbal lock here, when assigning the global transformation (or any of the global transformation parameters, like position, rotation, scale, etc.) the local transform is recalculated from the new global, this means that it will re-compute the rotation, which probably leads to some issues

I would suggest not updating the global transform needlessly, instead you can update your local position based on the global one, I think by doing:
```gdscript
position += to_local(marker_3d.global_position)
```

This detail might need to be documented more clearly though

**Comment by Sauermann** [comment]
possibly related to #74162

**Comment by AThousandShips** [comment]
See also [here](https://docs.godotengine.org/en/stable/tutorials/3d/using_transforms.html#setting-information) for some tricks and suggestions
