### ISSUE TITLE
GIProbe drastically drops performance compared to 3.5 with equivalent settings.

### ISSUE THREAD

**Issue by yosoyfreeman** [godotengine/godot#79667]
### Godot version

4.1 stable

### System information

Fedora linux, Nvidia 1070 TI

### Issue description

Gi probe is exponentially less performant that i's Godot 3x equivalent under similar settings. 

### Steps to reproduce

I created a basic scene consisting in two CSG nodes to make a simple room. I put a light on the center. In godot 4.0 i made the baking options dynamic to match the 3.5 without the use in bake light option applied and set the resolution to 512 subdivisions. Once baked, i get no noticeable frame drop at all, while in 4.1 the fps tanks to 4 -8 FPS. 

Limit size is too low, so i can not upload the baked results, so just press bake in both of them and see the results.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/12096540/Test.zip)

**Comment by paskausks** [comment]
I don't get really noticable frame drops, but 4.1 does seem to run a bit worse after baking, for me. Also, I got a BSOD after saving the scene for the first time in 4.1, but that's probably unrelated.

Windows 10, NVIDIA GeForce RTX 3080, driver ver 531.79, v4.1.1.stable.official [bd6af8e0e]

**Comment by Calinou** [comment]
> In godot 4.0 i made the baking options dynamic

Meshes with dynamic mode are **not** supported in 3.x GIProbe. This is a new feature in 4.0, and it's pretty slow as noted in https://github.com/godotengine/godot/issues/55359.
