### ISSUE TITLE
Floating Editor Dock unusable in Single Window Mode

### ISSUE THREAD

**Issue by Sauermann** [godotengine/godot#79673]
### Godot version

v4.2.dev.custom_build [0c2144da9]

### System information

Debian Linux X11 Xfce

### Issue description

Prerequisite: Be in Single Window Mode in the Editor
The Filesystem Dock is unusable when it is floating, which is not expected.
It appears garbled in the top-left corner:
![image](https://github.com/godotengine/godot/assets/6299227/109f7922-97de-44c3-814a-ca7f970e0602)

The following errors are shown:
```
  editor/window_wrapper.cpp:220 - Condition "!is_window_available()" is true.
  editor/window_wrapper.cpp:202 - Condition "!get_window_enabled()" is true. Returning: Rect2i()
  editor/window_wrapper.cpp:207 - Condition "!get_window_enabled()" is true. Returning: -1
  editor/window_wrapper.cpp:207 - Condition "!get_window_enabled()" is true. Returning: -1
```

bisecting lead to #62378
possibly related to #44439

### Steps to reproduce

1. Start a project in the Editor
2. Switch to Single Window Mode in the Editor and reload (if necessary)
3. Make the Filesystem Dock floating

### Minimal reproduction project

Editor issue

**Comment by YuriSizov** [comment]
I definitely tested some things in the single window mode and floating docks recently and never noticed such an issue with the docks. I wonder if it can be platform specific.

**Comment by mieldepoche** [comment]
happens on my ubuntu with all docks

**Comment by trollodel** [comment]
That button shouldn't be available in single window mode (I forgot to disable it in #62378).
I'll make a PR soon to disable it.

As a side note: in #62378 I disabled the floating docks in single window mode as I thought it isn't very useful to move dicks while being contained in the window. This may be considered a regression, so I'd like to see opinions about that.
