### ISSUE TITLE
CanvasModulate not remembering what color assigned to 

### ISSUE THREAD

**Issue by alvinseptiano** [godotengine/godot#79679]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - Intel(R) HD Graphics 5500 (Intel Corporation; 20.19.15.4835) - Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 Threads)

### Issue description

CanvasModulate color reset to default when changing between scene that has CanvasModulate.

https://github.com/godotengine/godot/assets/55371083/ed6ca028-59c1-415d-9801-4965e52949dc

### Steps to reproduce

create two scene with CanvasModulate and switch back and forth.

### Minimal reproduction project

[canvas_modulate.zip](https://github.com/godotengine/godot/files/12100607/canvas_modulate.zip)

**Comment by Calinou** [comment]
This is actually a rendering error, not CanvasModulate "losing" the color it's supposed to have. You can check this by using `print($CanvasModulate.color)` in the subscene script's `_ready()` function (you need to create this script in the MRP).

**Comment by kleonc** [comment]
Adding such script to CanvasModulates in the MRP:
```gdscript
extends CanvasModulate

func _notification(what: int) -> void:
	match what:
		NOTIFICATION_ENTER_CANVAS:
			print("%s: %s" % [self, "NOTIFICATION_ENTER_CANVAS"])
		NOTIFICATION_EXIT_CANVAS:
			print("%s: %s" % [self, "NOTIFICATION_EXIT_CANVAS"])
		NOTIFICATION_ENTER_TREE:
			print("%s: %s" % [self, "NOTIFICATION_ENTER_TREE"])
		NOTIFICATION_EXIT_TREE:
			print("%s: %s" % [self, "NOTIFICATION_EXIT_TREE"])
```
shows what's the issue. For:
![ZctieYdnKa](https://github.com/godotengine/godot/assets/9283098/99254fa7-b473-454c-9b2a-a9f314ed4b74)
The output is:
```
CanvasModulate:<CanvasModulate#34242299056>: NOTIFICATION_ENTER_CANVAS
CanvasModulate:<CanvasModulate#34242299056>: NOTIFICATION_ENTER_TREE
CanvasModulate:<CanvasModulate#37513856215>: NOTIFICATION_ENTER_CANVAS
CanvasModulate:<CanvasModulate#37513856215>: NOTIFICATION_ENTER_TREE
CanvasModulate:<CanvasModulate#34242299056>: NOTIFICATION_EXIT_CANVAS
CanvasModulate:<CanvasModulate#34242299056>: NOTIFICATION_EXIT_TREE
```

As seen, the old CanvasModulate exits after the new one already entered. When exiting it clears the modulate color for the canvas, effectively clearing the modulate set by the new CanvasModulate.

I'll look into fixing the logic for these updates.

---

A workaround in the meantime is to ensure the previous CanvasModulate fully exited before the new one enters. E.g. this works for the MRP:
```gdscript
# main.gd
extends Node2D

func _on_button_pressed() -> void:
	var scene = preload("res://scene_1.tscn").instantiate()
	change_to.call_deferred(scene)

func _on_button_2_pressed() -> void:
	var scene = preload("res://scene_2.tscn").instantiate()
	change_to.call_deferred(scene)

func change_to(node: Node) -> void:
	if $Node2D.get_child_count() > 0:
		$Node2D.get_child(0).free()
	$Node2D.add_child(node)
```
