### ISSUE TITLE
Exporting specific resources is broken, includes resources it should not include

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#79684]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

To start, let me explain the setup:
![image](https://github.com/godotengine/godot/assets/40964335/d85426ca-620e-4e89-a18c-5f73c72d01d1)

Here I have a nearly empty project. I've added two folders. "Large" is for resources with a large file size, and "Small" is for resources with a small file size. 

Contained in the "Large" folder is two needlessly-large images, used to represent actual game assets with a justified file size.
![image](https://github.com/godotengine/godot/assets/40964335/525d6b9d-6470-4bf7-8469-0212606255e7)

Contained in the "Small" folder is a singular 4 kilobyte image.
![image](https://github.com/godotengine/godot/assets/40964335/cc503b3f-bf7b-49f8-8c45-458d9deef902)

Now that I have explained the project, lets export it!
We will be exporting using these four presets: (All have embedded pcks for convenience but issue does not rely on that)
![image](https://github.com/godotengine/godot/assets/40964335/1ef81e90-beb4-42bc-b47b-8d092dd4edb7)

**Small Images Only Dedicated Server** exports only the "Small" folder using the **"Export as dedicated server"** option.
**Everything Dedicated Server** exports the entire project, including the large folder, using the **"Export as dedicated server"** option.
**Small Images Only Desktop** exports only the small folder using **"Export selected resources (and dependencies)"**
**Everything Desktop** exports the entire project with everything selected using "**Export selected resources (and dependencies)"**

The expected file sizes should be:
Everything Desktop > Everything Server > Small Images Desktop > Small Images Server

Small Images Server the smallest because it only has the singular png file, being stripped. Small Images Desktop is next because it has only the small image, but unstripped. Then, Everything Server, because it has all of the images but they are stripped. And finally, Everything Desktop containing every resource unstripped.

![image](https://github.com/godotengine/godot/assets/40964335/ecf706c0-03a2-4102-94fb-dc436085c85e)
But this isn't the case.
![image](https://github.com/godotengine/godot/assets/40964335/cc1477ce-c6f9-4244-b44e-1b7d351c46a0)
(export without embedded pck version)

Everything Desktop > Small Images Only Dedicated Server > Everything Server > Small Images Only Desktop

Having only selected a **4 kilobyte image** in the small images dedicated server, it should not be 106 mb. The everything server has a proper file size, implying the images were stripped properly.

![image](https://github.com/godotengine/godot/assets/40964335/52538afe-109b-44a7-ab62-abbd3dbe25d8)

As you can see, only a singular folder with a 4kb image is selected. Yet the file size is the same as the builds with the images unstripped and in their raw form.

The expected behavior is that the dedicated server with only one file selected should only include the data for that one file, not the rest of the project.

### Steps to reproduce

Open the project, and then go to the export project menu. Observe the selected resources for each one to ensure they match the name, and then export them and observe their file sizes.

### Minimal reproduction project

[ResourceExportExample.zip](https://github.com/godotengine/godot/files/12101349/ResourceExportExample.zip)

*Note - I have reduced the file size of the large images from 20~ mb to 6~ mb in order to upload it.
![image](https://github.com/godotengine/godot/assets/40964335/aada8688-996b-48b7-8353-df3811029474)
The issue still stands regardless.

**Comment by FireCatMagic** [comment]
> 

This works, but I feel the current behavior is misleading. Not having items selected to me implies that they would be removed and not exported. I feel that either the ui should be made more clear, or it should treat unselected things as "remove".

**Comment by AThousandShips** [comment]
That's what I said 🙃
