### ISSUE TITLE
exporting image of the viewport isn't 'instant' and cannot be called chronologically in code.. (screenshot bug?)

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#79691]
### Godot version

4.1 stable

### System information

Windows 10

### Issue description

I'm trying to take a screenshot of my viewport. Before I take the screenshot, I want to hide the UI elements totally out of the frame, so we only get an image of the subject. (I'm making editor/app software in godot)

The code I am using:
```
func _hide_ui():
    $sidebar.hide()
    for node in %render.get_children():
        for child in node.get_children():
            if child.name == "parameters":
                child.hide()

func _show_ui():
    $sidebar.show()
    for node in %render.get_children():
        for child in node.get_children():
            if child.name == "parameters":
                child.show()
var captured = false
func capture_image():
    var screenshot_path = "res://screenshot-test.png"
    var img = get_viewport().get_texture().get_image()
    img.save_png(screenshot_path)
    captured = true  #### this bool turns on to later make a check

func _on_export_button_down():
    _hide_ui()
    queue_redraw()
    %export_frame_timer.start()

func _on_export_frame_timer_timeout(): # first timer = 1 second
    capture_image()
    %export_done_timer.start()

func _on_export_done_timer_timeout(): # second timer = 1 second
    if captured == true: #### this should work, but it doesn't, the UI will still be in the image
        _show_ui()
```
![image](https://github.com/godotengine/godot/assets/27631913/14a75ba3-b5b4-4242-8e3d-aabc727b31d5)

In my code I am even using TWO timers to give enough time to take the image, but I'd expect this to work without timers completely... However it will always have UI elements in the image, no matter how much I try and swap around these lines and try different things.

![image](https://github.com/godotengine/godot/assets/27631913/660ee65e-9e64-4b2f-a1d6-972ade59359d)

What did work? Making the first timer 3 seconds, yes, THREE seconds long. Then I got the result I wanted. 

Is this a bug?

### Steps to reproduce

1) make a scene with a subject that you want to take an image of (a sprite, or whatever you want)
2) add some UI elements like buttons etc that overlay this subject
3) try and hide the UI and take a screenshot
4) the UI won't hide in the way you expect, and the image will always have the UI elements baked in
5) grab your head with your hands and say "what the heck?"

### Minimal reproduction project

project is so small, small enough to create in a couple minutes

**Comment by AThousandShips** [comment]
Have you tried the instructions [here](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-method-get-texture)?

**Comment by yankscally** [comment]
> Have you tried the instructions [here](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-method-get-texture)?

Oh my gosh! It must be that.

I knew in my heart it's a race condition thing with RenderingServer

**Comment by AThousandShips** [comment]
If that solves it this can be considered resolved, as it is already documented
