### ISSUE TITLE
Godot 4.1's 3D Graphic Rendering issues for older GPUs

### ISSUE THREAD

**Issue by Rorutop** [godotengine/godot#79690]
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - AMD Radeon HD 6570 () - AMD A4-7300 APU with Radeon HD Graphics (2 Threads)

### Issue description

I really wanted to do texture extrude effect using shaders! Too bad I'm using AMD HD 6570 and it's 3D rendering are bugged, even when doing anything like adding CSGBoxes :(. Just when im editing a gdshader for testing and wait for the box to update, the box texture suddenly went invisible and I am seeing random black artefacts appearing on my screen. This only gets fixed when i close and open the game again. I'm hoping that the compatibility rendering gets fixed in the future...

https://github.com/godotengine/godot/assets/66291382/73d83c0a-1b45-4a36-94f4-903edb4f2578

### Steps to reproduce

apply a single spatial shader that modifies the vertex to ShaderMaterial of CSGBox3D, edit/add something in the shader and boom the rendering bug

Also happens sometimes when I try to add any 3D objects (except sprite ofc)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Could you please upload an MRP to make this easier for contributors to troubleshoot?

An MRP is a project that is as small as can be while still reproducing the bug you are reporting. We include the MRP in the bug reporting template as including one greatly increases the chance that a contributor will be able to reproduce the bug you reported and be able to fix it.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/78936.

**Comment by Rorutop** [comment]
> Could you please upload an MRP to make this easier for contributors to troubleshoot?
> 
> An MRP is a project that is as small as can be while still reproducing the bug you are reporting. We include the MRP in the bug reporting template as including one greatly increases the chance that a contributor will be able to reproduce the bug you reported and be able to fix it.

Ya sorry I was confused on how would i make an MRP project
[MRP Stuff.zip](https://github.com/godotengine/godot/files/12109227/MRP.Stuff.zip)

Another bug:
- Adding a new environment to camera 3d (with viewport node and sprite3d's texture being that viewport in a node3d) will make them invisible. I had to restart godot
