### ISSUE TITLE
`peer_disconnected` signal does not fire when game is exited via F8 (stop running project)

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#79703]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3179) - AMD Ryzen Threadripper 3970X 32-Core Processor (64 Threads)

### Issue description

I am using the `ENetMultiplayerPeer` with the `MultiplayerSpawner` node to create a simple test project, following along with this youtube tutorial: https://www.youtube.com/watch?app=desktop&v=n8D3vEx7NAE

It blows my mind how easily everything gets set up! Props to the Godot team.

The issue I ran into though is that closing a debug instance using F8 (Stop Running Project command) is not the same as sending a quit notification (i.e. Windows close button). If I close the game using the windows close button or by triggering `get_tree().quit()`, the `multiplayer.peer_disconnected` signal fires as expected. But if I use F8, nothing gets fired.

### Steps to reproduce

- Set Debug > Run Multiple Instances to 2
- Press (1) key in window 1 to host
- see "player has been added!" in console output
- Press (2) key in window 2 to join
- see "player has been added!" in console output
- Press (F8) key in window 2 to exit
- no output in console, which should appear if `peer_disconnected` signal fired (can compare this to trying window close button instead, which does fire the signal)

### Minimal reproduction project

[bug-repro.zip](https://github.com/godotengine/godot/files/12105359/bug-repro.zip)

**Comment by KoBeWi** [comment]
This is not really a bug. F8 stops the process immediately, so it works even if it's unresponsive. The running project does not even know it's being terminated.

**Comment by yoont4** [comment]
Ah I see! Thanks for clarifying, that makes sense for handling the unresponsive case.
