### ISSUE TITLE
Editor Crashes immediately on opening a new or existing project in mobile or forward plus rendering option

### ISSUE THREAD

**Issue by digiur** [godotengine/godot#79718]
### Godot version

4.0.3-stabe 4.1.1-stable 4.2-dev1

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - Radeon(TM) RX 580 (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

When opening a new project using mobile or forward plus rendering the editor immediately crashes and exits to windows with no errors logged to the console.

This also happens when opening an existing project that uses mobile or forward plus rendering. I've tried all three versions listed. Only setting the renderer to compatibility fixes the problem.

![image](https://github.com/godotengine/godot/assets/59296455/9403a0e2-544c-48d3-b9e0-acd607cf1620)

Using AppCrashView shows the crashes as Access Violations.

![image](https://github.com/godotengine/godot/assets/59296455/41cbf3fe-9a72-436e-b0e2-1f100ee95519)

### Steps to reproduce

Start a new project with either mobile or forward plus renderer. I don't expect others to be able to re-create it on their machine. I assume it's something to do with my environment but I'm at a loss. Every version I've tried is showing the same behavior.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Does your GPU support Vulkan?

**Comment by digiur** [comment]
Yes, it does. This only started happening today. I'm trying to install old drivers as well but nothing seems to be working.

**Comment by digiur** [comment]
This seems to have stopped happening with 4.2 Beta 2
