### ISSUE TITLE
since moving to Godot 4.x HeightMapShape3D shows a warning in the editor

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#79716]
### Godot version

4.1

### System information

Windows 10

### Issue description

the HeightMapShape3D only has a few parameters and seems relatively undoced/untalked about

as it only has a few parameters, the map_height, map_depth and the data as a serial array... presumably therefore i assumed the only way to change it's actual scale and size properly was to scale the CollisionShape3D

this now provides and editor warning.... maybe the HeightMapShape3D should have extra features? like scale? or maybe the editor is making a needless warning and it is correct to scale the CollisionShape3D

the docs do not provide much information on the correct usage

### Steps to reproduce

create a HeightMapShape3D, fill it with data

scaling any CollisionShape3D provides the same warning

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please include the actual warning

**Comment by RichardEllicott** [comment]
yes as i said "scaling any CollisionShape3D provides the same warning", that warning

in which case what is the correct way of using the HeightMapShape3D?

**Comment by RichardEllicott** [comment]
as i said in the issue i opened... it DOES work... and the only way to actually scale the heightmap is to scale the shape

please can you demonstrate how you change the heightmaps lateral (x z) scaling by interaction with any other parameter

**Comment by AThousandShips** [comment]
Yes, scale it in *all* axes

Just adjust the hight in the map so it works when scaled

**Comment by RichardEllicott** [comment]
yes for the height.... but what happens with this grid (undocumented)... it's actual size is based on the depth and the height values... it gets bigger the more squares you add

if you do your approach therefore you can't change the scaling of the grid, you will have to leave the squares all the same size... normaly you can scale a grid

**Comment by AThousandShips** [comment]
I mean, just change the height values?

If you want `(1, 2, 3, 4)` and you need to make it twice as wide and deep just make the values `(0.5, 1, 1.5, 2)`

**Comment by RichardEllicott** [comment]
sorry maybe someone else will get it... the height... okay i am fine with that yes just change height values

the actual lateral dimensions to scale these... there are no options... i tried to explain how it works to you i need to talk with someone who's used it i think sorry i can't convey it to you

**Comment by AThousandShips** [comment]
I know how it works, I've used it, there aren't any options because it's a simple type, you can't use it for more advanced cases, just like with `BoxShape3D`

**Comment by RichardEllicott** [comment]
well what i have works, but it only works with this scaling

look for example at the docs:
map_depth 

"Changing this will resize the [map_data](https://docs.godotengine.org/en/stable/classes/class_heightmapshape3d.html#class-heightmapshape3d-property-map-data)."

this is NOT the scaling, this and map_height is the size of the map data 

so the ONLY thing you can set in this heightmap is the data... the cells, and their heights... not scale... you have to make 4x as many squares to get coverage of an area that is 2x the height width

are you SURE you used it and you managed to scale it laterally like i said? how?!? there are 3 parameters

**Comment by AThousandShips** [comment]
> are you SURE you used it and you managed to scale it laterally like i said?

Yes, I'm sure I used it... If you're uninterested in my feedback because you think I'm lying to you then go ahead

**Comment by RichardEllicott** [comment]
okay providing some screenshots to demo what i mean so people can understand:

![image](https://github.com/godotengine/godot/assets/5873361/e8ae3ce8-1f4c-4dd7-b01d-9b60f616a380)

in this image... i have generated a heightmap and got it to fit my shader (a lot of hard work, like i say this object could be more intuitive)

in the image we can see i have had to scale the CollisionShape3D.. there are no other settings that achieve this

let's say i accept then it's supposed to be a limitation, lets scale to 1x1x1 as the warning says:

![image](https://github.com/godotengine/godot/assets/5873361/c7de263a-10ee-40ae-b42f-17e134d468e4)

now the HeightMapShape3D  could not even cover my whole mountain... because i'd need far too many squares

**Comment by AThousandShips** [comment]
Just set the scale to all same values, as instructed, and adjust the height values accordingly, that's all I can tell you

**Comment by RichardEllicott** [comment]
i will try seeing if i can refactor to change that okay i could see if i can make it so i need a "uniform scale", fair point i did not pay propper attention to "uniform scale" i will try that

still i don't actually get any issue with the current code, just a warning... indeed the warning saying "probabally"

**Comment by RichardEllicott** [comment]
thanks man i will shut this down actually i was missunderstanding the error so not communicating no worries i don't see what anyone else would be able to say

i want to for myself find out if maybe static collider scaled are okay, i should do that with another method thanks
