### ISSUE TITLE
Monitoring/Monitorable Not Working In Certain Scenes

### ISSUE THREAD

**Issue by sealionnn** [godotengine/godot#79715]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

For example, Area2D with monitoring set to true and checking mask 0 (TileMap) and 1 (Player). Area has body_entered connected to its script. The area will not register collision on the TileMap, but it will when it collides with player. Next, I set monitorable to true and layer 0, and it then registers collision with the TileMap. The really weird thing is it worked as intended the day before.

### Steps to reproduce

Unable to reproduce.

### Minimal reproduction project

Unable to reproduce.

**Comment by AThousandShips** [comment]
Please do not open issues without having at least basic steps for reliably replicating it, it won't be possible to investigate or fix

**Comment by AThousandShips** [comment]
Closing due to lack of response
