### ISSUE TITLE
GDScript export of C# class not working

### ISSUE THREAD

**Issue by wilfredjonathanjames** [godotengine/godot#79727]
### Godot version

4.1.1-mono

### System information

MacOS 12.3

### Issue description

When I do this:

```gdscript
extends Node

const InkStory = preload("res://addons/GodotInk/Src/InkStory.cs")

@export var story: InkStory
```

`InkStory` is of type `CSharpScript`, and the editor shows

<img width="401" alt="image" src="https://github.com/godotengine/godot/assets/5732688/c6c3cff7-b7d8-42a3-8375-f067f890df54">

This prevents me from narrowing the export, because I can use a `Resource` instead, but I can't verify that resource is the correct type. I'm left with duck typing and an export interface that accepts any resource in my project.

I know that this export would work in C#, so this appears to be an edgecase when loading C# classes into GDScript.

### Steps to reproduce

1. Create a C# script with a class in it, or Import the [ink](https://github.com/paulloz/godot-ink) addon.
1. Create a GDScript with the contents:
```gdscript
extends Node

const MyType = preload("res://path/to/csharp_script.cs") # change to the correct C# script path

@export var specific_resource: MyType
```

### Minimal reproduction project

-

**Comment by AThousandShips** [comment]
Does this work with [global classes](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_global_classes.html), exports are restricted to global classes I believe

Can you confirm that this works with a GDScript script loaded in the same way, i.e. without `class_name`?

**Comment by DipShtick** [comment]
I tried reproducing the bug with global class
`using Godot;
using System;

[GlobalClass]
public partial class script : Node
{
    
}`

`extends Node2D

const ScriptPath = preload("res://script.cs")

@export var thing: ScriptPath`

Same thing
![image](https://github.com/godotengine/godot/assets/110741996/d9d15aa8-dd18-4b2d-84b9-cecc4f398fc2)

**Comment by AThousandShips** [comment]
Just use the name, `script` and try

**Comment by paulloz** [comment]
Hello, I maintain the linked addon.  
I haven't moved to `[GlobalClass]` yet, since it is *very* recent. That's on my roadmap, though.

For now, you should still be able to export from GDScript as a simple resource. Duck typing will ensure everything from `InkStory` is still accessible anyway. There is a dedicated page about interoperability on our wiki: https://github.com/paulloz/godot-ink/wiki/Interop-with-GDScript
```gdscript
@export var story : Resource

# For instance:
if story.GetCanContinue():
    var current_text = story.Continue()
```

**Comment by paulloz** [comment]
> That's on my roadmap, though.

Just as a heads-up, this is now the case in our [v1.1.0](https://github.com/paulloz/godot-ink/releases/tag/v1.1.0).
