### ISSUE TITLE
[img] richtextlabel BBCode does not display with "Image" resource

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#79729]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

They simply do not display.
![image](https://github.com/godotengine/godot/assets/40964335/609b0762-3152-40b8-a239-ca7a7267216b)
![image](https://github.com/godotengine/godot/assets/40964335/d655f4d2-2dfc-4dab-8cbc-ed25cefeeb03)

I started typing random junk in, and it displays the "resource not found" error for all of it. Except it is successful for the image, proving it accepts it as valid. 
![image](https://github.com/godotengine/godot/assets/40964335/2526c537-787d-4d21-8e82-d9a7809794ad)

### Steps to reproduce

1. Create a RichTextLabel
2. Enable bbcode on the richtextlabel
3. Load a png file and change the import type to "Image"
4. . Enter it into the text slot with [img] PATH [/img]
5. Watch as it does not show up

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@FireCatMagic Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by FireCatMagic** [comment]
> @FireCatMagic Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

here
[broken_bbcode.zip](https://github.com/godotengine/godot/files/12114948/broken_bbcode.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.2.dev 0f7625ab4 and 4.0.3.stable (Linux). I'm not sure why it's not working on your end, considering it works in the [Rich Text BBCode](https://github.com/godotengine/godot-demo-projects/tree/master/gui/rich_text_bbcode) demo.

**Comment by felaugmar** [comment]
> I'm not sure why it's not working on your end, considering it works in the [Rich Text BBCode](https://github.com/godotengine/godot-demo-projects/tree/master/gui/rich_text_bbcode) demo.

The difference is the "import type" of the asset, `Image` is being used here, causing the error, instead of `Texture2D`.

**Comment by FireCatMagic** [comment]
> > I'm not sure why it's not working on your end, considering it works in the [Rich Text BBCode](https://github.com/godotengine/godot-demo-projects/tree/master/gui/rich_text_bbcode) demo.
> 
> The difference is the "import type" of the asset, `Image` is being used here, causing the error, instead of `Texture2D`.

I made it an Image resource rather than a Texture2D because of the docs:
![image](https://github.com/godotengine/godot/assets/40964335/a5f62db9-2c2d-4638-a391-00db1ec6a6e4)

https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#reference

**Comment by Calinou** [comment]
> I made it an Image resource rather than a Texture2D because of the docs:

That's why it doesn't work. Image resources can't be displayed as-is; only their pixel data can be queried on the CPU.
