### ISSUE TITLE
AnimationTree won't play continouus animated frame number in AnimationPlayer

### ISSUE THREAD

**Issue by nik-lampe** [godotengine/godot#79739]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.4.1 - Vulkan (Mobile) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

When I start this by just running it on the AnimationPlayer it works just fine. But when I try to run it with an AnimationTree, the animation is not playing. When I add keyframes in between an set the frame manually on each and then set the update mode to discrete, then it works.

Is this a bug? Or is this not the intended use?

### Steps to reproduce

In the provided Project activate the AnimationTree and test the BlendTree1D, left side should play down animation, and right side should play up.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/12116401/Bug.zip)

**Comment by TokageItLab** [comment]
Continuous and discrete modes cannot be blended because they have no precedence over them, and is intended behavior. Aren't there any warnings in console?

**Comment by nik-lampe** [comment]
Thanks! At least I don't see any warning.

Do I understand correctly, that I can't blend continuous and discrete animations into each other, but I should be able to blend two continuous or two discrete animations?
Also shouldn't it be possible to trigger the continouous animation, "down" in my example, not with a blendspace, but with a explicit animation state node in the tree? But this does not work either.

**Comment by TokageItLab** [comment]
The StateMachine internally does the same thing as a blend. If there are tracks with different playback modes, a warning should appear at the time of cache generation, but if it does not, it may be a bug. (The cache generation is instantaneous, so it is possible that the warning was missed.)

**Comment by nik-lampe** [comment]
> Also RESET track must be in the same playback mode.


Thanks! That was my mistake. 
The RESET track was set do discrete animation. Switching it to linear then showed me the warning that I'm mixing up different modes. Setting all my tracks to continuous mode then works as I wanted it.
