### ISSUE TITLE
simple 2D (pong) game guide docs suggestion

### ISSUE THREAD

**Issue by danboid** [godotengine/godot#7973]
IMHO, I don't think that the step-by-step intro to godot docs should assume the reader has any experience with Python. Whilst this page:

http://docs.godotengine.org/en/stable/tutorials/step_by_step/simple_2d_game.html

Does a good job of explaining each step of building up the script, it doesn't include a complete script code listing and nor does it explain that every line of code printed after 

`func _process(delta):`

Should be indented so as to be part of the _process function. Whilst this may be obvious to those who have experience with python, it likely won't be so obvious to those who don't.

**Comment by akien-mga** [comment]
Could you open this issue on the docs repository instead? https://github.com/godotengine/godot-docs

**Comment by danboid** [comment]
I didn't know it had a separate repo. Will do.
