### ISSUE TITLE
Editor: Cannot rename a file unless the FileSystem window is highlighted first

### ISSUE THREAD

**Issue by Spycemyster** [godotengine/godot#79745]
### Godot version

4.1

### System information

Windows 11

### Issue description

When using the editor, I can't rename a file by right-clicking and hitting "Rename" if I have a different part of the editor focused/highlighted. Right-clicking the file and clicking "Rename" just does nothing in that case.

### Steps to reproduce

https://github.com/godotengine/godot/assets/6189001/5682fba4-962d-4edc-931d-487024e3672b

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
This describes the same problem as in #78789.
Consolidating as a duplicate with that bugreport.
