### ISSUE TITLE
Export for ios

### ISSUE THREAD

**Issue by kpk-i710** [godotengine/godot#79757]
### Godot version

4.0, 4.1.1, 

### System information

Mac OS m1 air, godot 4.0., 4.1.1 stable

### Issue description

I have Mac m1 air 13.4.1 , Ventura stable, 16 gb ram, I export for iOS
In version 3.5 everything works.
All 4 and above versions have the same error when exporting .

Unable to export error open icons,
Can't open file from path 'res://new4.2/Images.xcassets/AppIcon.appiconset/Contents.json'.
   Can't open file from path 'res://new4.2/Images.xcassets/AppIcon.appiconset/Icon-40.png'.
   Can't open file from path 'res://new4.2/Images.xcassets/AppIcon.appiconset/Icon-58.png'.
<img width="1552" alt="image" src="https://github.com/godotengine/godot/assets/47340012/eff5b870-9a13-405b-b83e-0a06da6af0ce">

Does anyone even get to export for an iPhone with Godot 4?

### Steps to reproduce

1. Select export for iOS
2. select image icon 1024
3. Export ipa

### Minimal reproduction project

https://github.com/kpk-i710/arabic_godot

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
It seems like you accidentally exported it into a project folder, and errors are caused by Godot trying to load exported iOS files, you should always export to the empty folder outside the main project tree.

Your test project is exporting for iOS without any issues, if a valid App Store Team ID is set in the export settings. You can get it from developer account site - https://developer.apple.com/help/account/manage-your-team/locate-your-team-id, or from the developer certificate ("Organisational Unit" field).

**Comment by kpk-i710** [comment]
> It seems like you accidentally exported it into a project folder, and errors are caused by Godot trying to load exported iOS files, you should always export to the empty folder outside the main project tree.
> 
> Your test project is exporting for iOS without any issues, if a valid App Store Team ID is set in the export settings. You can get it from developer account site - https://developer.apple.com/help/account/manage-your-team/locate-your-team-id, or from the developer certificate ("Organisational Unit" field).

Thanks a lot, yes you are right. I didn't look carefully there it was necessary to specify idTeam,
I specified the first and last name, because when I did flutter (dart), the export always requested an account with a first name and last name

**Comment by Calinou** [comment]
> It seems like you accidentally exported it into a project folder, and errors are caused by Godot trying to load exported iOS files, you should always export to the empty folder outside the main project tree.

I remember Godot disallowed exporting a project within the project folder for this reason at some point.

Alternatively, could we write a `.gdignore` file within the exported folder? This approach can only be used with iOS exports though.
