### ISSUE TITLE
Button's StyleBox 'Content Margin' theme affects editor UI at startup when set to default custom theme

### ISSUE THREAD

**Issue by HolySkyMin** [godotengine/godot#79753]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.2802) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/30334834/8576f143-a9e1-4e08-b443-321e29321fa7)
![image](https://github.com/godotengine/godot/assets/30334834/3bc5f4f2-ac9c-43ed-8639-2c73ead2a7f9)

Scene tabs got bigger, top button groups moved to right, only because I set the default custom theme in project setting and modified Button's StyleBox 'Content Margin'.

### Steps to reproduce

1. Create new empty project
2. Create new theme
3. In new theme add Button theme, go to 'Styles - Normal' and override whatever StyleBox there
4. In StyleBox modify 'Content Margin' value (especially top and bottom) to some big value, then save theme
5. Go to Project Setting and search for 'theme', then in GUI - Theme set 'Custom' to theme we just created
6. Reload project (you are prompted to do this when you set default custom theme)

...or just download minimal reproduction project and open it.

### Minimal reproduction project

[ThemeDemon.zip](https://github.com/godotengine/godot/files/12131025/ThemeDemon.zip)

**Comment by KoBeWi** [comment]
The bug seems to be coming from the distraction free Button:
![image](https://github.com/godotengine/godot/assets/2223172/70deb6d7-b108-415d-bc69-e2cf14ea2cb7)
It has wrong minimum size at launch (likely editor theme is not initialized), but afterwards the size does not shrink. I tried shrinking it forcefully, but this doesn't shrink the overall top panel for some reason.
![image](https://github.com/godotengine/godot/assets/2223172/a44a8d1c-4214-49d5-b65f-cde2e5798475)

**Comment by HolySkyMin** [comment]
Does `scene_tab_add_ph` actually needed? I'm not sure what will happen if we completely remove it.

Anyway, left and right content margin affects title bar like this:
![image](https://github.com/godotengine/godot/assets/30334834/8047e08a-dec9-4c7a-8f04-14f6cc05adbd)
(left + right set to 140)

Looked into the code (editor_node) but couldn't figure out why this happens.
Maybe we can start from here...
https://github.com/godotengine/godot/blob/6588a4a29af1621086feac0117d5d4d37af957fd/editor/editor_node.cpp#L8161

**Comment by ninstar** [comment]
This problem doesn't seem to be limited "Button" margin values from what I tested, I mentioned this in an existing open issue ([60930](https://github.com/godotengine/godot/issues/60930)) related to default project themes and it affects multiple other (if not all) margin parameters inside and outside styleboxes.

**Comment by HolySkyMin** [comment]
Yes it seems not limited to certain properties like content margin, but all layout related properties (that is  _any types of_ margins).

I hope the PR I submitted being accepted since this problem starts to harm my production project 😇
