### ISSUE TITLE
When creating a new scene the default root node name doesn't respect the `editor/naming/node_name_casing` project setting

### ISSUE THREAD

**Issue by sfreed141** [godotengine/godot#79751]
### Godot version

4.1.stable

### System information

Windows 11

### Issue description

The Create New Scene dialog always defaults the scene root node name to the filename. If you're following the recommended (and default) naming conventions for filenames (snake_case) and node names (PascalCase), this default name always needs to be changed. It would be lovely if the default root node name respected the `editor/naming/node_name_casing` project setting.

Also, I have already implemented this in my fork and would be happy to contribute it. This was my "dip my toes" into Godot engine development idea since it was simple and has bothered me for a while. I consider this more of an oversight bug than a feature proposal which is why I'm opening the issue here instead of on the proposals repo.

### Steps to reproduce

1. Create and open new project
2. (only if you've changed this) In project settings set `editor/naming/node_name_casing` to PascalCase
3. In Filesystem view, right click | Create new | Scene
4. Enter a filename like "test_scene" and click Ok

Notice the root node of the new scene will also be named "test_scene" instead of "TestScene"

### Minimal reproduction project

N/A

**Comment by Ybaedbaenn** [comment]
This also affects the project root window.
```gdscript
print(get_tree().root.name)
```
```gdscript
root # should be Root to follow the node name casing
```

**Comment by dalexeev** [comment]
> This also affects the project's root window.

I believe it has nothing to do with the setting. The root node is created by the engine, you cannot specify its name. We should not change the name for the reason of absolute path compatibility.
