### ISSUE TITLE
Remove_and_skip crashes if the node have children

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7975]
**Ubuntu 16.10 - Godot version: 2.1.2 stable**

**Issue description:**
Using Node.remove_and_skip crashes and closes the game window if the node have children, this message is shown on the terminal:
```
ERROR: operator[]: Condition ' p_index<0 || p_index>=size() ' is true. returned: aux
   At: core/vector.h:132.
```

It was supposed to 

> Remove a node and set all its children as children of the parent node (if exists). All even subscriptions that pass by the removed node will be unsubscribed

according to docs http://docs.godotengine.org/en/stable/classes/class_node.html#class-node-remove-and-skip.

**Steps to reproduce:**
 - Use Node method `remove_and_skip` on a node with children.

**Link to minimal example project:**
Press any key to trigger remove_and_skip on the "parent" node.
[removeandskipbug.zip](https://github.com/godotengine/godot/files/824719/removeandskipbug.zip)

**Comment by AlexHolly** [comment]
Looks like one child is beeing removed and used with a wrong index a few lines later

https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L2023

Made a quick test and looks good

```
		for (int i = 0; i < data.children.size(); i++) {
			Node *c_node = data.children[i];
			if (!c_node->get_owner())
				continue;

			remove_child(c_node);
			c_node->_propagate_replace_owner(this, NULL);
			children.push_back(c_node);
			clear = false;
			break;
		}
```

Test result
![image](https://cloud.githubusercontent.com/assets/4741886/23825996/949d67c4-0694-11e7-9b16-ffb47da29cc3.png)

![image](https://cloud.githubusercontent.com/assets/4741886/23826000/b6fce86c-0694-11e7-9c86-600e3f912e69.png)

**Comment by eon-s** [comment]
Nice! 

-----------------

Tested this on 2.1 branch and when closing the window, only after using the fixed `remove_and_skip`, the console shows

```
ERROR: ~List: Condition ' _first!=__null ' is true.
   At: core/self_list.h:82.
ERROR: ~List: Condition ' _first!=__null ' is true.
   At: core/self_list.h:82.
```
Maybe there is a reference that needs to be cleaned somewhere.

Apart from that it looks like works fine, even on master where the problem was present too.

**Comment by AlexHolly** [comment]
Yes, on master it is this line.

https://github.com/godotengine/godot/blob/master/core/self_list.h#L79

The function looks complicated why not just do this?

```
void Node::remove_and_skip() {

	ERR_FAIL_COND(!data.parent);

	Node *new_owner = get_owner();

	bool clear = true;
	while (data.children.size()>0) {
		Node *c_node = data.children[0];

		remove_child(c_node);
		new_owner->add_child(c_node);
	}

	data.parent->remove_child(this);
}

```

Result looks the same and no error.

**Comment by eon-s** [comment]
On 2.1 the error on close persists but I guess you can do a PR to get it fixed at least on master.

------------------

And the `_propagate_replace_owner` is not needed? 
It looks like a lock.
