### ISSUE TITLE
Undescriptive "affine_invert: Condition det == 0 is true" error after minimizing a borderless window resized to full screen with display/window/stretch/mode set to viewport.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79759]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Making the root window borderless, resizing it to full screen size, and hen minimizing it with display/window/stretch/mode set to viewport in project settings, causes a weird "affine_invert: Condition det == 0 is true" error to appear from one to three times in the console.

https://github.com/godotengine/godot/assets/84321760/e753b201-d411-49d4-94fc-c2d5f331c68c

### Steps to reproduce

0. Use the minimal reproduction project.
1. Run the project.
2. Once the game resizes to full screen, defocus it to make the script minimize it.
3. Observe the error in the console.

### Minimal reproduction project

[Affine-Invert-Window-Problem-Test-4.1.1.zip](https://github.com/godotengine/godot/files/12131401/Affine-Invert-Window-Problem-Test-4.1.1.zip)

**Comment by Ybaedbaenn** [comment]
Please also note how the Windows preview changes to white at the end of the recording, what may be related to https://github.com/godotengine/godot/issues/79107.
