### ISSUE TITLE
Double-inheritance duplicates nodes

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7976]
**Operating system or device - Godot version:**
Godot 2.1.2 (and last 2.1 branch)

**Issue description:**
I have a scene hierarchy composed of three scenes: __C__ inherits __B__ which inherits __A__.
When opening __C__ in the editor I can see some (but not all) nodes from __A__ shown as if owned by __C__.
If I save the scene, then all those problematic nodes get saved to the __C__'s scene file.
If then I re-open __C__ I can see in the tree the nodes that were duplicated when saving. So every time I save my scene is getting additional copies of the nodes from __A__ being wrongly identified as owned (not inherited).

Strage enough, if I remove some nodes from __B__ and reload __C__, at a certain point the issue starts to apply to less nodes. Not every node I remove from __B__ has this effect.

Also when saving __C__ I get a bunch of errors like this:
```
ERROR: SceneState::get_property_value: Condition ' p_node<0 ' is true. returned: Variant()
   At: scene\resources\packed_scene.cpp:1032
```

Some clue about where is the problem in my scenes or in Godot's source?

**Please! This is a show stopper for me.**

EDIT: One more thing I've found is that I if write a script that loads __C__ and saves it, it gets saved correcly. So the process of packing/unpacking seems to be the place to look.

**Steps to reproduce:**
~~Haven't found yet. Just happens with my game. I've tried to create a minimal project that shows the issue, but this doesn't happen there.~~

UPDATE:
~~At least after applying the work-in-progress fix #7978, I can reproduce it by loading an scene and another that inherits indirectly from it. When saving the former, the latter is updated making a mess.~~

A possible reason is that when the scene is saved, its state is recreated and it no longer has a node path cache as when it's firstly loaded. See https://github.com/godotengine/godot/blob/master/scene/resources/packed_scene.cpp#L78

**Link to minimal example project:**
Haven't been able to isolate.

**Comment by RandomShaper** [comment]
@reduz, please have a look!

**Comment by bojidar-bg** [comment]
Can confirm on 2.2 and 2.1.X.

**Comment by RandomShaper** [comment]
I'm researching it.

Do you have any clue about how to reproduce?

**Comment by RandomShaper** [comment]
I think most cases are fixed with the PR. I've opened #7984 for the remaining cases so this one can be closed after the PRs get merged, as a whole.

**Comment by bojidar-bg** [comment]
Related to #7664. Also, closing as per above comment.
