### ISSUE TITLE
Sprite3D not showing when instantiated via code. (Compatabillity)

### ISSUE THREAD

**Issue by SupaSibs** [godotengine/godot#79768]
### Godot version

4.1.1.stable

### System information

Samsung Galaxy Tab A 10.1 2019 SM-T510, Android 11, Mali G-11, 4 1.8ghz cortex cores, 4 1.6ghz cortex cores (ARM). (Not sure about rendering backend)

### Issue description

[source code](https://github.com/SupaSibs/bmc2)
I have a "Bloon" scene (res://sprites/bloons/bloon.tscn) that consists of a Node3D parent and a Sprite3D child of the parent. I also have code that instantiates the Bloon scene to the main scene, Map. The Sprite3D is instantiated, all the values work, (i checked from code), but I expected the Sprite3D to show at co-ordinates 0,0,0, but the texture simply doesn't show. The same thing happened every time i tried instantiating a sprite3d.

### Steps to reproduce

1. Create an empty Godot project in Compatibillity renderer
2. Create a scene "BuggedScene" that consists of a Node3D and a Sprite3D. Use any texture for the sprite
3. Create a scene "MainScene" that consists of a Node3D and a Camera3D that has 0, 0, 0 in sight. Make it the main scene
4. Make a script that instantiates the BuggedScene in the MainScene like this (Please replace spaces with tabs in the code, I am on a mobile device right now): 
```
extends Node3D

func _ready():
    # Or load
     var BuggedScene = preload("res://BuggedScene.tscn").instantiate()
     add_child(BuggedScene)


``` 
5. Voila, there's the bug. The chosen texture for the Sprite3D should've shown in the MainScene but it doesn't.

### Minimal reproduction project

N/A (easy to recreate)

**Comment by SupaSibs** [comment]
Also, I'm not sure if it does the same thing on mobile and forward+, my tablet is too laggy

**Comment by Rindbee** [comment]
You should adjust the camera angle to be able to see the Bloon after it has been added to the scene. You can rehearse this process in the editor: by instantiating a Bloon scene.

**Comment by SupaSibs** [comment]
Oh I am extremely dumb lol. Thanks
