### ISSUE TITLE
Make Camera2D Works inside MainScreenEditorPlugin if inside a SubViewport

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#79773]
### Godot version

4.1.1-stable

### System information

Windows 10

### Issue description

Camera2D doesn't work inside a main screen plugin if inside a SubViewport. it should work as if in game and the reason is that is_current() returns false. and also if the root is Node2D it draws over the UI which is wrong because the root should always be a Control Node in MainScreenEditorPlugin.

### Steps to reproduce

add a main screen editor plugin
Control
__SubViewportContainer
____ViewportContainer
______Node2D
________Camera2D

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/12135241/New.Game.Project.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/33931.
