### ISSUE TITLE
Viewport background transparency not working with custom clear color in Mobile and Compatibility renderers

### ISSUE THREAD

**Issue by LRFLEW** [godotengine/godot#79778]
### Godot version

4.1.1.stable, 4.2.dev [6588a4a]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

This is related to #72602, but since this also affects the Mobile renderer, this is likely a separate issue.

Setting the "Transparent BG" setting on a viewport is supposed to always keep the background transparent. On the Forward+ renderer, this setting is respected for all Environment Background Modes . On both the Mobile and Compatibility renderers, using the "Clear Color" background mode works with the transparent background, but using a "Custom Color" background does not render it as transparent.

Using Custom Color:
![bug](https://github.com/godotengine/godot/assets/607715/63032a9b-be99-459e-a4f6-a84faa0d7dc0)

Using Clear Color:
![clear](https://github.com/godotengine/godot/assets/607715/5c839062-a3b0-4fd9-9a8d-ff169eec7bfd)

### Steps to reproduce

1. Add a SubViewport to render some 3D scene and a way to view it (eg. a Sprite2D using the viewport as its texture)
2. Enable the "Transparent BG" option on the SubViewport
3. Setup an Environment for the 3D scene being rendered to the SubViewport (either on the Camera3D node or on a WorldEnvironment node)
4. Change the Background Mode of the Environment to Custom Color.

### Minimal reproduction project

[SkyTest.zip](https://github.com/godotengine/godot/files/12135972/SkyTest.zip)

**Comment by freshBakedPie314** [comment]
would love to work on this as my first contribution!! But I have no idea where to start. Any suggestions would be helpful!

**Comment by lostminds** [comment]
This could also be related to the existing issue https://github.com/godotengine/godot/issues/72602 where having a sky environment makes the viewport background opaque instead of transparent. Could very well be the same issue as when rendering just having a custom color environment.

**Comment by LRFLEW** [comment]
Fixing this for the Mobile renderer can be its own PR most likely, and will likely be easier than fixing it for the Compatibility renderer. Fixing this for the Mobile renderer will be a matter of comparing `RenderForwardMobile::_render_scene` to its Forward+ counterpart `RenderForwardClustered::_render_scene` and figuring out which difference is responsible. The Compatibility equivalent to these functions, `RasterizerSceneGLES3::render_scene` is different enough that comparing them is a bit more of a challenge. I actually discovered this issue (as well as the cause of #74187) while trying to figure out the cause of #72602 by comparing these functions. When I have some time again, I want to take another stab at figuring out #72602 and the Compatibility part of this issue, but if someone else figures it out first, then that will work too.

**Comment by clayjohn** [comment]
I would just leave this open until the Compatibility backend is fixed as well.

**Comment by freshBakedPie314** [comment]
I know which comments you're referring to. I looked at it and didn't mess with it as I didn't know why they were commented out or what they did 


And as clayjhon said I think you should leave this open till compatibility is fixed as well
