### ISSUE TITLE
Navigation paths always stay visible

### ISSUE THREAD

**Issue by asafing** [godotengine/godot#79789]
### Godot version

4.0, 4.1

### System information

Godot v4.1.stable - Windows 10.0.18363 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

After turning the `Visible Navigation` option on & off several times, it's now consistently on and I can't turn it off no matter what I do... I have no solution for this
![image](https://github.com/godotengine/godot/assets/66164321/6353bd11-93e3-4ce2-927b-d56c87dac65f)

### Steps to reproduce

Not sure what the trigger was (most likely related to turning `Visible Navigation` on at least once`), but after it happened once it will never stop

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
Those debug paths are toggled with the `debug_enabled` property of the NavigationAgent2D.

**Comment by asafing** [comment]
Yup, my bad, sorry about that
