### ISSUE TITLE
defining variable in onready makes it the actual value null

### ISSUE THREAD

**Issue by whitestranger7** [godotengine/godot#79797]
### Godot version

4.1 - stable

### System information

Windows 10 - 4.1 stable (steam version) - Vulkan (Forward +)

### Issue description

I've bunch of nodes defined in the app:

cells_manager.gd - the parent that instantiates `Cell` node
```
extends Node


@export var cell_scene: PackedScene

const CELL_WIDTH: float = 64.0
const CELL_HEIGHT: float = 64.0
const BOARD_SIZE: int = 8


func _ready() -> void:
	generate_cells()


func generate_cells() -> void:
	for y in range(BOARD_SIZE):
		for z in range(BOARD_SIZE):
			var cell_instance = cell_scene.instantiate() as Cell
			cell_instance.set_color(Types.CELL_COLORS.BLACK)
```

cell.tscn - the scene that contains tree `<Cell(Node2D) -> Sprite(Sprite2D)>` with script
```
extends Node2D
class_name Cell


@onready var sprite = 5


func set_color(color: Types.CELL_COLORS) -> void:
	print(sprite)
        #this line will return null
```

function `set_color` is called in parent in `_ready` function and value of printed variable `sprite` is `<null>`

### Steps to reproduce

- create basic project
- create parent scene that accepts export packed variable of child scene
- define @onready variable in child scene
- in parent call try to get access to that @onready variable from `_ready` func
- result will be null

### Minimal reproduction project

[chess.zip](https://github.com/godotengine/godot/files/12137072/chess.zip)

**Comment by asafing** [comment]
`@onready` means the variable will be instantiated during the `_ready` phase of the node. \
A quick look at your code shows you instantied the cell, then immediately used `set_color`. \
`_ready` was never called, thus the variable never had value. \
BTW there's no reason to use `@onready` on a flat value

**Comment by AThousandShips** [comment]
`_ready` is called when the node enters the tree, not when instanced, see [documentation](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-ready)

**Comment by whitestranger7** [comment]
@asafing @AThousandShips thanks for answer, mates)
So how you guys think I can be sure that with defining new instance of scene I can be sure that some kind of constructor may be called? Or I can do it only manually in a place I create new instance?

Btw `@onready` in my case used for reference to sprite node, so no worries, I just simplified it for that particular example)

**Comment by AThousandShips** [comment]
Not a "guy" thank you

I'd recommend reading the documentation for `Object` and `Node` for this

**Comment by asafing** [comment]
`_init()` is called when you instantiate an object, I'd use that instead
