### ISSUE TITLE
Impossible to start the project window in any other possition than the center of the screen the editor is on.

### ISSUE THREAD

**Issue by Ybaedbaenn** [godotengine/godot#79799]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Changing the values of the project settings:

- display/window/size/initial_position_type
- display/window/size/initial_position
- display/window/size/initial_screen

As well as moving the editor between primary and secondary screen in multi monitor setup, has no effect on the position of the starting project's window - it will always appear on the centre of the screen that the editor is currently on.

Pleas check out the reproduction video.

https://github.com/godotengine/godot/assets/84321760/76348199-163e-4895-a9c9-0e35f6439579

### Steps to reproduce

0. Start a new project.
1. Set any of the project settings to a non-default value:

    - display/window/size/initial_position_type
    - display/window/size/initial_position
    - display/window/size/initial_screen

3. Run the project.
4. Observe if the project's window appears on the correct screen and position.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
When running from the editor, these settings are overridden by `Editor Settings` → `Run` → `Window Placement`.

**Comment by Ybaedbaenn** [comment]
Thank you for clarifying, I somehow managed not to notice this, I should have read the documentation.
