### ISSUE TITLE
Collision mask / layer  in editor differs from code

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#79790]
### Godot version

4.2.dev.1.mono

### System information

Windows 10

### Issue description

When i have an area at layer 20 but in code it wants the value of the layer (524288) if i only enter 20 like its in the editor it wont work, is this supposed to be like this? seems not that intuitive? 
Can be related with? #76883 

![Skärmbild 2023-07-22 155829](https://github.com/godotengine/godot/assets/13393087/2931669c-006c-454f-9654-fef2dbc0e6cb)

### Steps to reproduce

See picture.

### Minimal reproduction project

[CollisionMaskTest.zip](https://github.com/godotengine/godot/files/12136646/CollisionMaskTest.zip)

**Comment by felaugmar** [comment]
That's how it works, using bits of "integer" for each "mask id".

All values below are valid.

```gdscript
524288  
1 << 19
0b10000000000000000000 # "19 zeros" and "1 one"
```

**Comment by Norrox** [comment]
> That's how it works, using bits of "integer" for each "mask id".
> 
> All values below are valid:
> 
> ```gdscript
> 524288
> 0b10000000000000000000 # "19 zeros" and "1 one".
> 1 << 19 # This is like "move the digit one 19 times to the left", resulting in the same as above.
> ```

Yeah i understand that, but from a more userfriendly point of view, is there any reason we cannot use collision_mask = 20 instead of 524288?
Is there something like maskid(20) and that one convert it correctly to 524288 for the collision_mask , so it looks something like this collision_mask = maskid(20) ? :D

**Comment by AThousandShips** [comment]
You can just use [`set_collision_mask_value`](https://docs.godotengine.org/en/stable/classes/class_collisionobject2d.html#class-collisionobject2d-method-set-collision-mask-value)

**Comment by Norrox** [comment]
Thanks !
