### ISSUE TITLE
Callables and lambdas stored with FileAccess store_var() become null::null after get_var().

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79802]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Storing a callable or a lamba to a file with FileAccess.store_var(full_objects = true), and then reading it, causes it to be lost - printing it outputs it as null::null.

Calling the loaded callable results in an error: `Attempt to call function 'null::null (Callable)' on a null instance.`

Other types of variables can be stored in the same file, with the same method, and retrieved without problems.

### Steps to reproduce

0. Run the minimal reproduction script.
1. Read the print() outputs in the console.
2. Observe how the callable and the lambda are lost after loading.
3. Test the script again with `var allow_objects` changed to `false` - result should be the same.
4. Uncomment the call statements at the end of the script.
5. Observe the error appearing when a call on the loaded callable is attempted.

### Minimal reproduction project

```gdscript
var allow_objects = true


func test_func():
	print("ok")


func _ready():

	var text_before = "test_before"
	var callable = Callable(self, "test_func")
	var lambda = func(): print("success")
	var text_after = "test_after"

	print("Printing input to store_var(): ")
	print(text_before)
	print(callable)
	print(lambda)
	print(text_after)
	print()

	print("Calling functions before storing: ")
	callable.call()
	lambda.call()
	print()

	print("Saving and loading.")
	var file = FileAccess.open("user://save.dat", FileAccess.WRITE)
	file.store_var(text_before, allow_objects)
	file.store_var(callable, allow_objects)
	file.store_var(lambda, allow_objects)
	file.store_var(text_after, allow_objects)
	file.close()

	await get_tree().create_timer(1).timeout

	file = FileAccess.open("user://save.dat", FileAccess.READ)
	var loaded_text_before = file.get_var(allow_objects)
	var loaded_callable = file.get_var(allow_objects)
	var loaded_lambda = file.get_var(allow_objects)
	var loaded_text_after = file.get_var(allow_objects)
	file.close()
	print()

	print("Printing output from get_var(): ")
	print(loaded_text_before)
	print(loaded_callable)
	print(loaded_lambda)
	print(loaded_text_after)
	print()

	print("Calling functions after loading: ")
	#loaded_callable.call() # causes an error
	#loaded_lambda.call() # causes an error
```

**Comment by AThousandShips** [comment]
Yes, this is by design, and has been documented in at least some places, but might need to be clarified elsewhere

**Comment by Ybaedbaenn** [comment]
For example the documentation for FileAccess methods:
- store_var() https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-var
- get_var() https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-get-var

Does not have any mentions about this behavior, in fact searching the FileAccess documentation page for `callable` or `lambda` yields no results.

**Comment by AThousandShips** [comment]
It doesn't, it needs to be clarified there, it *is* documented for `var_to_str`, will look into the underlying code for these cases tomorrow

**Comment by AThousandShips** [comment]
Callables are indeed not stored, this is because they aren't reliably encodable, as callables can be bound methods in c++, will document this limitation
