### ISSUE TITLE
OS.set_low_processor_usage_mode not working and creating problems on Android

### ISSUE THREAD

**Issue by florix91** [godotengine/godot#7980]
**Operating system or device - Godot version:**Godot version : 2.1.2
Mac OS Sierra 10.12.3 

**Issue description:**

When the function "OS.set_low_processor_usage_mode" is in code it gives the scene a flashing-like effects corrupting the scene to work properly ( at least labels)

**Steps to reproduce:**
Write the function "OS.set_low_processor_usage_mode(true)" on the _ready or _process functions and export for Android

**Link to minimal example project:**

**Comment by RandomShaper** [comment]
I've not forgotten what was said on #6727 and will try to fix it when I have the time. Regardless, a separate issue report for this is a nice thing.

By the way, I can confirm.

**Comment by ganlub** [comment]
@kubecz3k I confirm this is still happening as stated by @florix91.

**Comment by akien-mga** [comment]
Closing as superseded by #19304, which was reported more recently against the stable version of Godot and is thus more visible.
