### ISSUE TITLE
Abysmal framerate on MacOS while dragging and dropping nodes in the Scene tree

### ISSUE THREAD

**Issue by craigostrin** [godotengine/godot#79817]
### Godot version

4.1 stable

### System information

Godot v4.1.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

When clicking-and-holding on a node in the scene tree, the framerate drops to like 5 fps or something.

I have tested this with all the basic node types (Node, Node2D, Node3D, Control). Same issue with all of them.

This is happening with all my projects, including brand-new projects.

I wish I could say when this issue started, but I only just got a Macbook a few months ago. I've been using exclusively Windows and Linux with Godot until now.

https://github.com/godotengine/godot/assets/40326682/37d4a00c-700c-45f1-b7e7-ff9da045809e

### Steps to reproduce

Create a new project.

Create a scene. Add any node to the scene. Pick it up and move it around.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39608./
