### ISSUE TITLE
Glitch Godot 4.1's Project Manager

### ISSUE THREAD

**Issue by PixelTeix** [godotengine/godot#79824]
### Godot version

Godot 4.1.1

### System information

Windows 10 - AMD Quad Core A-10-9620P - AMD Radeon R5 Graphics 26.20.12028.2

### Issue description

I have installed today the latest version of Godot (4.1.1) and follow the instructions of the site to install it. 
However, when opening Godot, I was presented with the project manager and a second window named "_Please Confirm..._" with an extended sentence cut by the window size (image 1). By extending the window, it showed the message "_You currently don't have any projects. Would you like to explore official example projects in the Asset Library?_" (Image 2) Then, after moving the cursor, the second glitch window changed into the project menu screen (image 3) and moving too much the cursor would change it to the original glitched window. Clicking a button of the project manager creates a window in blank (image4). When moving the cursor, the window changes between the menu screen or an extended version of the window that is supposed to open (image 5).
Besides that, in Godot 3.5, this bug doesn't happen and everything is normal, in opposite of Godot 4.1.1.
Due to this bug, I can't use Godot 4.1 and its project manager, or even create a project. 

Image 1:
![image](https://github.com/godotengine/godot/assets/140322934/2cdda01e-4420-4aea-9a41-c7f9b5bca21d)
Image 2:
![image](https://github.com/godotengine/godot/assets/140322934/9110c1df-df48-42a6-ab94-0315f59a8aeb)
Image 3:
![image](https://github.com/godotengine/godot/assets/140322934/be8cc994-e249-48ee-b130-b5883107a22e)
Image 4:
![image](https://github.com/godotengine/godot/assets/140322934/0d1c5043-ff24-44b2-ba37-0153806903ef)
Image 5:
![image](https://github.com/godotengine/godot/assets/140322934/7ea1b24a-4b5b-47fd-821c-480a26293010)
Image 6
![image](https://github.com/godotengine/godot/assets/140322934/20f56af6-ee0a-48bd-9b5e-a0e8f038c879)

### Steps to reproduce

Download Godot Engine 4.1.1, extract the zip folder and open Godot 4.1.1.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/72944.
