### ISSUE TITLE
Theme fonts are not affecting children 'button' nodes

### ISSUE THREAD

**Issue by Xerathe** [godotengine/godot#79822]
### Godot version

4.0.2 stable

### System information

Win 10 - Vulcan disabled (not supported)

### Issue description

Setting custom fonts for a Theme resource in a parent Control node does not affect Button nodes in it's children. However, Options buttons work just fine.

(I'm really sorry, but I have no clear idea how to export a scene or a project from Godot, and I'm really bad with GitHub, so if there is a problem with the archive in the reproduction project, here's the link to my repo with the same archive: https://github.com/Xerathe/Godot_Theme_Fonts_Bug.git)

### Steps to reproduce

1) Set a control node as the main one
2) Add a couple of child nodes/scenes (both are of the control type) with buttons
3) Create a new Theme resource for the parent
4) Add a custom font to the Theme
5) The change should be seen in the editor (only Options buttons are affected)

### Minimal reproduction project

[TEST_Button_Bug.zip](https://github.com/godotengine/godot/files/12138743/TEST_Button_Bug.zip)

**Comment by AThousandShips** [comment]
You're setting the default font, with a font already configured for the button, it won't use the default font if one is already configured for those buttons

**Comment by Xerathe** [comment]
> You're setting the default font, with a font already configured for the button, it won't use the default font if one is already configured for those buttons
> 
> You need to set the `Button/fonts/font` font property, set by `set_font("font", "Button", my_font)`, which I think can also be accessed as `teme.Button.fonts.font = my_font` but haven't used themes like that much
> 
> The reason it applies to `OptionButton` is that it doesn't have a font configured

You are genious, thank you) All I had to do was just delete that font in the theme editor for the button specifically and it loaded the default font correctly

**Comment by AThousandShips** [comment]
You probably created the theme and accidentally copied the defaults into your theme

**Comment by AThousandShips** [comment]
Closing as per the above responses
