### ISSUE TITLE
V4.1.1 windows_release_x86_64.exe missing

### ISSUE THREAD

**Issue by Piratux** [godotengine/godot#79825]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

V4.1.1 templates file "Godot_v4.1.1-stable_export_templates.tpz" at
https://github.com/godotengine/godot/releases/tag/4.1.1-stable
is missing windows_release_x86_64.exe file (windows export template for x64).

### Steps to reproduce

Download "Godot_v4.1.1-stable_export_templates.tpz" and look inside.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
It's in there, I'm not sure what's going on on your end but it is right there if you download it

**Comment by Piratux** [comment]
Alright, so apparently it's automatically flagged as a virus and removed from my folder.
https://imgur.com/a/vmiQHBT

**Comment by AThousandShips** [comment]
Then this is a problem with that, and the exports are correct, probably over active antivirus, the files are signed with a trusted key so the due diligence has been done on the Godot side to prevent this

**Comment by bruvzg** [comment]
> the files are signed with a verified certificate so the due diligence has been done on the Godot side to prevent this

Export template file are not signed, these files are modified during export and existing signature will interfere with rcedit operation, PCK embedding and new user signature.

**Comment by YuriSizov** [comment]
Seems like Windows' heuristics are getting jumpy lately. We've had a few reports recently about false positives. Please make sure to submit a request to Microsoft so they can add an exception to their database. See https://github.com/godotengine/godot/issues/79170.
