### ISSUE TITLE
Memory leak when resizing a Label node's font size

### ISSUE THREAD

**Issue by ScaredPenguinXXL** [godotengine/godot#79828]
### Godot version

4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Debian GNU/Linux 12 (bookworm) 12 - Vulkan (Mobile) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1255U (7 Threads)

### Issue description

Resizing a label's font size causes a memory leak. This issue is furthermore visible in projects with many label nodes being resized.

Prior to resizing:
![Screenshot from 2023-07-23 17-28-53](https://github.com/godotengine/godot/assets/89851117/370f4628-f55c-40f1-9e38-1112af75080d)
After resizing:
![Screenshot from 2023-07-23 17-29-33](https://github.com/godotengine/godot/assets/89851117/94a6f858-dc45-4c27-85a9-7654abc1f3ee)

### Steps to reproduce

Attach this script to a Label node:

```
extends Label

func _ready():
	get_tree().get_root().size_changed.connect(resize)
	resize()

func resize():
	var screenSize: Vector2 = get_window().size
	var m: float = min(screenSize.x, screenSize.y)
	label_settings.font_size = int(m / 20)
```

### Minimal reproduction project

[MemoryLeak.zip](https://github.com/godotengine/godot/files/12139016/MemoryLeak.zip)

**Comment by ScaredPenguinXXL** [comment]
I forgot to mention that you have to resize the window's size by pulling the borders to reproduce the issue.

**Comment by bruvzg** [comment]
Fonts keep all rendered glyphs cached until the font is unloaded, so this is expected behavior.

Usually only a small number of font sizes are uses and all of them are reused multiple times, so it is more beneficial to keep them instead of reloaded every time.

You can clean the cache manually:
```gdscript
...
	var m: float = min(screenSize.x, screenSize.y)
	var rids = label_settings.font.get_rids()
	for r in rids:
		TextServerManager.get_primary_interface().font_clear_size_cache(r)
	label_settings.font_size = int(m / 20)
...
```

**Comment by bruvzg** [comment]
But, since in 4.x changing fonts sizes is much easier, it probably should be changed to LRU instead of keeping in indefinitely.
