### ISSUE TITLE
Godot Building System Needs To Be Rewritten

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#79836]
### Godot version

4.1.stable

### System information

Windows 11 - Godot 4.1.stable - Vulkan (Forward+)

### Issue description

Godot building system has some issues like in android when you build an app and go look inside of apk you can see clearly game's assets/codes probably all source code you have can you use .pck also in android?

### Steps to reproduce

- opened godot 4.1
- enter a project
- build for android

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
In what way do you think it needs to be rewritten?

**Comment by NotRabug50** [comment]
> In what way do you think it needs to be rewritten?

We should be able to use a custom package extension instead of .pck, so the game engine is a little freer this way. and android building, everything looks open in the assets folder, elements such as the game's code, and this makes piracy much easier.

**Comment by NotRabug50** [comment]
> In what way do you think it needs to be rewritten?
> 
> Are you talking about the fact that you can extract the data from the exported project? That's a known limitation and why you should use encryption if you want to provide some degree of protection, but in the end there's no way to completely prevent this, as the game has to be able to access the resources, if this is the behavior you are talking about it isn't a bug, but a limitation, which is best served as a proposal for changing how some of these things work

but it is way easier than i it should be

**Comment by AThousandShips** [comment]
> We should be able to use a custom package extension instead of .pck, so the game engine is a little freer this way. 

Why? What is the use of this, what ways is `.pck` limited

**Comment by NotRabug50** [comment]
> > We should be able to use a custom package extension instead of .pck, so the game engine is a little freer this way.
> 
> Why? What is the use of this, what ways is `.pck` limited

not limited actually but it is good thing to have a custom things

**Comment by AThousandShips** [comment]
> not limited actually but it is good thing to have a custom things

That's not an argument, "it would be nice to have" is not a reason to add new complex features 🙃 

All this aside, this isn't the place for this, this is proposal territory, go [here](https://github.com/godotengine/godot-proposals) and follow the instructions

**Comment by NotRabug50** [comment]
> > not limited actually but it is good thing to have a custom things
> 
> That's not an argument, "it would be nice to have" is not a reason to add new complex features 🙃
> 
> All this aside, this isn't the place for this, this is proposal territory, go [here](https://github.com/godotengine/godot-proposals) and follow the instructions

but I still think the android build system needs to be rewritten because I like to use godot and I'm going to make a 2d rpg game my plan is to release the game on mobile but it's a bit bad that my code can be changed easily

**Comment by AThousandShips** [comment]
Then go and support those proposals, this can't be fixed for just android

For the argument about "good thing" see [here](https://docs.godotengine.org/en/latest/contributing/development/best_practices_for_engine_contributors.html) about the philosophy

**Comment by NotRabug50** [comment]
> Then go and support those proposals, this can't be fixed for just android, this isn't the place for it, so please take the issue over there
> 
> For the argument about "good thing" see [here](https://docs.godotengine.org/en/latest/contributing/development/best_practices_for_engine_contributors.html) about the philosophy

you got me wrong i sayed "good thing" for custom .pck name. in android it's a big problem

**Comment by AThousandShips** [comment]
Please, this is for bug reports, not new features or changes to features, please take it to the appropriate place, this isn't for new features

Please propose over there a feature of more custom `.pck` files, but this isn't the place, understand?

**Comment by NotRabug50** [comment]
> Please, this is for bug reports, not new features or changes to features, please take it to the appropriate place, this isn't for new features
> 
> Please propose over there a feature of more custom `.pck` files, but this isn't the place, understand?

ok thx
