### ISSUE TITLE
Ambient light not included in backlight material

### ISSUE THREAD

**Issue by WrobotGames** [godotengine/godot#79859]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

When using backlight/translucency ambient light (the background/hdri) is not used for the backlight effect. This results in, for example foliage materials looking really 'harsh' in Godot. 

The ambient light is included by default in the following software: blender cycles, blender eevee, unity hdrp and unreal engine. (This has been tested) Ambient light being included is basically the expected behavior, and that's why this is an issue that this isn't there is Godot.

### Example: plane against the sky, the reproduction project.
A white plane with 100% backlight against the sky.
Godot 4: 
![afbeelding](https://github.com/godotengine/godot/assets/66079814/dde8e925-60c3-4e3c-b9f6-a1c8caf34fa1)
Blender Eevee: 
![afbeelding](https://github.com/godotengine/godot/assets/66079814/e0065eb3-79fb-4a2f-b18d-e48863ee7119)

### Example: foliage (no download due to copyright)
In materials where the backlight is used, for example foliage, the lighting will often look too 'harsh' when the ambient light isnt used in the backlight. 
Godot 4 grass with 100% backlight:
![afbeelding](https://github.com/godotengine/godot/assets/66079814/f2149131-b684-4ed1-88cb-f79c42042b7f)
Blender Eevee grass with 100% backlight:
![afbeelding](https://github.com/godotengine/godot/assets/66079814/85e8dbe3-1011-44da-8d47-510b63f7cd10)
The lighting in Eevee looks notably more soft, and a bit brighter. This is the expected outcome with a 100% backlight. Its not possible to get this result in Godot without writing your own light shader. (Which is really complicated and should be the case here)

### Steps to reproduce

1. Create a plane.
2. disable the sun, so only the sky light is used.
3. observe how enabling backlight on the plane does nothing.

Do the same thing in other software and there will be a difference by enabling it. (Tested in: Cycles, Eevee, Unity, Unreal)

### Minimal reproduction project

[Backlight_Godot4.zip](https://github.com/godotengine/godot/files/12147887/Backlight_Godot4.zip)
[Backlight_Blender.zip](https://github.com/godotengine/godot/files/12147904/Backlight_Blender.zip)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by MightiestGoat** [comment]
Suppose I am getting this right. Do we need to bake the ambient light emission from the ground affected by directional light? I may be wrong here.

**Comment by clayjohn** [comment]
I guess this is more of an "enhancement" suggestion. Right now "backlight" is a setting that only applies to direct lights in Godot, it doesn't add anything to indirect lights/GI. 

For direct lights we add an extra term ``((1/PI) - BRDF) * backlight``.  So I tried adding a comparable term to the ambient sky light

```
diff --git a/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl b/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl
index 8a7008492e..28e989b3c2 100644
--- a/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl
+++ b/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl
@@ -1153,6 +1153,9 @@ void fragment_shader(in SceneData scene_data) {
                        vec3 cubemap_ambient = textureLod(samplerCube(radiance_cubemap, SAMPLER_LINEAR_WITH_MIPMAPS_CLAMP), ambient_dir, MAX_ROUGHNESS_LOD).rgb;
 #endif //USE_RADIANCE_CUBEMAP_ARRAY
                        cubemap_ambient *= scene_data.IBL_exposure_normalization;
+#if defined(LIGHT_BACKLIGHT_USED)
+                       cubemap_ambient += (vec3(1.0 / M_PI) - cubemap_ambient) * backlight;
+#endif
                        ambient_light = mix(ambient_light, cubemap_ambient * scene_data.ambient_light_color_energy.a, scene_data.ambient_color_sky_mix);
                }
        }
```
It certainly softens the lighting the way that backlight does, but I'm not sure if it is the correct approach. Can you test with the above patch and let me know if the result matches your expectations?

**Comment by WrobotGames** [comment]
This patch seems to be the solution. It is not perfect, but it is good enough of a solution. 
As can be seen from this image, the patch solves the main problem.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/2ca1998c-6971-427c-873d-4879e00bc759)
### Nitpicking and comparison
![afbeelding](https://github.com/godotengine/godot/assets/66079814/38de43cd-c589-49af-a784-70b644df9005)
_(Note: unreal uses a different HDRI and I don't know how to disable the specular reflection in Unity HDRP)_
There are still some differences between the pieces of software, but those seem to be coming from the way the mesh is lit by the HDRI, rather then how the backlight is calculated. 
Example: The underside of the sphere isn't black in Godot, and the sides are not that blue, this can be seen in the backlight.
![afbeelding](https://github.com/godotengine/godot/assets/66079814/278a7a0e-7e1e-4d79-bf5f-7bdeec4fd496)

### Foliage
The patch had really improved the look of the grass.
Without patch:
![afbeelding](https://github.com/godotengine/godot/assets/66079814/eb1f392d-6839-4428-8be9-afc580330011)
With patch:
![afbeelding](https://github.com/godotengine/godot/assets/66079814/4c120019-cea3-4361-9075-5855f2a1c45f)

### Issues
Some issues I've encountered:
- The backlight stays, even when the sun is disabled with a procedural sky:
![ezgif-4-79da37857b](https://github.com/godotengine/godot/assets/66079814/74813f42-0e3f-4f26-88b7-d536e6de4eaa)
- The backlight somehow darkens the mesh on some HDRI's (occurred on white cliff top hdri)
![ezgif-4-8ea26108c9](https://github.com/godotengine/godot/assets/66079814/80c3d571-44dc-45f8-9c9b-6c82ff48b42d)

**Comment by clayjohn** [comment]
Thanks for checking! Your analysis shows that the lines of code I posted are definitely not correct. So more investigation will be needed to figure out what a proper backlight formula for sky lighting looks like

**Comment by WrobotGames** [comment]
I am closing this issue, because the more I look into it, the more I realize a potential fix is a lot more complicated. I feel like this discussion should be moved to the Godot proposals repo.

For example: Bevy introduced backlighting in its 0.12 update. https://bevyengine.org/news/bevy-0-12/
> Diffuse transmission is implemented via a second, reversed and displaced fully-diffuse Lambertian lobe, which is added to the existing PBR lighting calculations. This is a simple and relatively cheap approximation, but works reasonably well.

This sounds fairly simple, but when I tried the demo it seemed like there are some changes made to the lighting of the non backlit side, when changing the backlighting intensity. Some kind of correction for the added lighting. (Energy Conservation.) 

Also, the backlighting currently implemented doesn't seem to handle normals correctly, with the sides of a sphere being lit even though the light is at an 90 degree angle. (This behavior does not occur in other game engines / in blender)
