### ISSUE TITLE
@export_category creates a variable that causes issues if another one has the same name

### ISSUE THREAD

**Issue by AlexCor1** [godotengine/godot#79861]
### Godot version

4.1.1stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3179) - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 Threads)

### Issue description

So, to make my code better I was using `@export_category("HEALTH")` to create categories in the editor.
Also, right under that, I had ```@export var HEALTH = 30; var current_health: float```. 

Turns out, the `@export_category` creates a boolean variable with the same name as my health variable with caused issues when I wanted to set `current_health` to `HEALTH`. 

Never in the editor this was said or implied by a console error.
I simply fixed it by removing `@export_category` even though I could have changed the name of the category instead.

Just wanted to point that out in case this wasn't intended.

### Steps to reproduce

Try the following code:

```gdscript
@export_category("NAME")
@export var NAME = 1
var my_name: int

func _ready():
    my_name = NAME

func _physics_process(delta):
    print(NAME)
    print(my_name)
```

### Minimal reproduction project

N/A

_Bugsquad edit:_ Fix formatting.

**Comment by timothyqiu** [comment]
See also #78252. Probably will be fixed by #78254.
