### ISSUE TITLE
When enabling MSAA in XR mode (Quest 2 or PICO 4), there are abnormalities in the effect.

### ISSUE THREAD

**Issue by maxiaoxr** [godotengine/godot#79868]
### Godot version

v4.1.2.rc.custom_build

### System information

Android9.0 - Godot_v4.0-rc3 - Vulkan and GL3(Mobile and Compatibility)

### Issue description

Enabling MSAA in Mobile mode on PICO4 and Quest2 results in a black screen, while enabling MSAA in Compatible mode has no effect. 

### Steps to reproduce

Scenario One
1. Project Settings -> Render -> gl_compatibility
2. Project Settings -> Anti-aliasing -> MSAA 3D (4x)

Scenario Two
1. Project Settings -> Render -> gl_moblie
2. Project Settings -> Anti-aliasing -> MSAA 3D (4x)

### Minimal reproduction project

[pico_test.zip](https://github.com/godotengine/godot/files/12156771/pico_test.zip)
This projection can run in Quest2,if you want to run in PICO4,you should change the option when you export apk.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/67204 and https://github.com/godotengine/godot/issues/69462.
