### ISSUE TITLE
Using `queue_free` after `Tween.Stop` causes a memory leak

### ISSUE THREAD

**Issue by dillyo09** [godotengine/godot#79869]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

Running the following code causes a memory leak:
```
var tween = get_tree().create_tween()
tween.stop()
queue_free()
```

### Steps to reproduce

1. Create a Tween
2. Use `tween.stop()` 
3. `queue_free()` the Node that created the Tween

### Minimal reproduction project

[TweenMemoryLeak.zip](https://github.com/godotengine/godot/files/12156855/TweenMemoryLeak.zip)

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by Marigem** [comment]
`var tween = get_tree().create_tween()`

This creates a tween attached to the tree instead of the node you are queue_free'ing.

`var tween = create_tween()` would be correct. Try and see if it still causes a memory leak with that.

**Comment by kleonc** [comment]
> `var tween = create_tween()` would be correct.

Or `var tween = get_tree().create_tween().bind_node(self)` which is equivalent.


So there's no bug in here indeed. I guess what could be done is maybe adding some warning in the docs saying that paused/stopped tween not binded to a node will not be freed unless it will be killed manually or it will finish the tweening (it would need to be resumed/played again).

Another improvement could be changing this line in the in-docs examples:
```gdscript
var tween = get_tree().create_tween()
```
to something like:
```gdscript
var tween = create_tween() # Or `get_tree().create_tween()` if auto-binding to the node is not wanted.
```
so both ways would be mentioned in each example. Hopefully this would make more users be aware of the difference between `SceneTree.create_tween` and `Node.create_tween` methods.

**Comment by kleonc** [comment]
@KoBeWi From `Tween.bind_node`'s docs:
>the [Tween] will be automatically killed when the bound object is freed

https://github.com/godotengine/godot/blob/f6187014ec1d7a47b7201f64f3a8376a5da2f42d/doc/classes/Tween.xml#L102

This is currently not the case, paused/stopped tweens are not freed. I think moving `if (!running)` after `if (is_bound)` should do the thing (it needs to be able to reach `return false;` before early returning if not running):
https://github.com/godotengine/godot/blob/f6187014ec1d7a47b7201f64f3a8376a5da2f42d/scene/animation/tween.cpp#L287-L300
