### ISSUE TITLE
Editor 3d transform snap parameters randomly become very small

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#79862]
### Godot version

since 3.x, still there in 4.1.1

### System information

ubuntu

### Issue description

Resulting from I don't know what, this sometimes happen automatically: 

![image](https://github.com/godotengine/godot/assets/71937306/6ee0bed1-f53d-478f-84a1-d0a508509d9e)

related: #39507
maaaybe related: #77414

### Steps to reproduce

I couldn't isolate it yet.
Update: I can't reproduce it yet, but it just happened just after I pressed the manual snap button. That is:
- I checked before, the value was okay
- I toggled the manual snap
- when I tried to move a mesh, it didn't snap
- I opened the snapping settings and indeed, it was all messed up again.

The way I find out this happened is I try to snap using Ctrl, and the thing doesn't visibly snap.

### Minimal reproduction project

none

**Comment by lentsius-bark** [comment]
I'd like to add, that this constantly happens also on 3.x, I haven't been able to pinpoint when and why it happens but it happens frequently. 

I have however talked to other users of the engine who have mentioned that this is not an issue for them (both on 3.x and 4.x).

**Comment by rcorre** [comment]
This happens to me regularly on Godot 4.1. I've never been able to consistently repro, but at some point in a project I always notice snap stops working, and the snap settings have changed to small values.

> it just happened just after I pressed the manual snap button

FWIW, I don't ever click the snap button. I just hold ctrl for snapping, and this still affects me.
