### ISSUE TITLE
Wrong lightining on objects with different rotation when using normal map

### ISSUE THREAD

**Issue by Anders333** [godotengine/godot#79877]
### Godot version

4.1.1 stable

### System information

Godot v4.2.dev (91258e52b) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3179) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

![Screenshot 2023-07-25 131326](https://github.com/godotengine/godot/assets/12541333/929c360d-ecc1-41be-b232-95e6866e820c)
Different lightining on object after rotation(tested on stable and dev)

### Steps to reproduce

Create cube, apply material with some normal map. Create directional light 3D. Dublicate cube and rotate at 180 degrees along y axis.

### Minimal reproduction project

[testmat.zip](https://github.com/godotengine/godot/files/12159929/testmat.zip)

**Comment by clayjohn** [comment]
It looks like the default direction in your normal map is (188, 188, 255) which is not oriented to point straight out from the surface. it points out at an angle, so when you rotate the object the lighting changes. 

The default normal direction should be (128, 128, 255) for a flat surface

**Comment by Anders333** [comment]
> It looks like the default direction in your normal map is (188, 188, 255) which is not oriented to point straight out from the surface. it points out at an angle, so when you rotate the object the lighting changes.
> 
> The default normal direction should be (128, 128, 255) for a flat surface
> 
> You can see the issue quite clearly when you put your normal map next to a correctly functioning normal map
> 
> ![Screenshot from 2023-07-25 12-29-11](https://user-images.githubusercontent.com/16521339/255871886-54309a8e-f830-4551-9dde-850059d13e61.png) ![Screenshot from 2023-07-25 12-29-02](https://user-images.githubusercontent.com/16521339/255871891-7e6d999e-5864-4710-ace1-4959e365f85b.png)

Thanks. My fault. I need to use bump map, but godot don't support it, so i just baked nm in blender. Looks like baking goes wrong.
