### ISSUE TITLE
Unable to compile a production template with LTO enabled

### ISSUE THREAD

**Issue by xana43** [godotengine/godot#79873]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 11 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

While compiling a template from the source, the compilation will eventually error out with

'C:/Users/(user)/AppData/Local/Temp/.....ltrans0.ltrans.o: No such file or directory' 

then it'll say a lot of ltrans files aren't found. 

based on some research these appear to be temporary files for LTO, and I am unsure as to why they seem to not be found while compiling. 

### Steps to reproduce

compile the templates with any flag enabled but 'use_lto=yes lto=full' needs to be present or 'production=yes' as this flag enables those flags as well

### Minimal reproduction project

N/A

**Comment by xana43** [comment]
I have 128 gb of RAM, and I've tried lto=thin, but all it does is outright disable lto regardless

**Comment by akien-mga** [comment]
Apologies for the delay following up.

Can you still reproduce this issue with recent Godot versions?

If so, please check that you have enough available disk space for the intermediate files to be written, and add details on which compiler and compiler version you are using (if MinGW, which distribution).

**Comment by xana43** [comment]
> Apologies for the delay following up.
> 
> Can you still reproduce this issue with recent Godot versions?
> 
> If so, please check that you have enough available disk space for the intermediate files to be written, and add details on which compiler and compiler version you are using (if MinGW, which distribution).

so in the time between then and now, I've moved off of windows to Fedora. However last I remember before I switched to Fedora I did try this again on 4.1.2 and 4.1.3 and it seems to have been fixed then. If I encounter this issue again either when compiling on another windows machine and/or cross compiling I will update this issue, but for now it appears to be resolved.
