### ISSUE TITLE
Godot editor prevents computer from going to sleep

### ISSUE THREAD

**Issue by curious-broccoli** [godotengine/godot#79870]
### Godot version

4.1.1.stable.official

### System information

Windows 10

### Issue description

While the Godot editor is open, the computer will not enter sleep mode. I am not talking about just the screen, that works https://github.com/godotengine/godot/issues/69167.

I did run `powercfg /requests` and it printed the following, while Godot was running. I believe the project was not playing any audio and an empty project causes the same output.
```
SYSTEM:
[DRIVER] Realtek High Definition Audio (HDAUDIO\FUNC_01&VEN_10EC&DEV_0B00&SUBSYS_10438797&REV_1000\5&a39a1ec&0&0001)
An audio stream is currently in use.
```

It also wasn't entering sleep in 4.0.

### Steps to reproduce

Set your Sleep setting (on Windows 10: Settings -> System -> Power & sleep) to 1 minute.
Open the Godot editor and leave the computer idle for 2 minutes.
The computer does not enter sleep mode.

### Minimal reproduction project

N/A

**Comment by curious-broccoli** [comment]
Closed because I can't cause my computer to sleep after 1 minute even when Godot is closed. But I am rather sure it usually would go to sleep, but doesn't when Godot is running

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/28039.
