### ISSUE TITLE
[C#] GlobalClass attribute not working from an addon

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#79887]
### Godot version

4.1.1

### System information

macOS

### Issue description

C# classes part of an addons that are marked with the `[GlobalClass]` attribute are not available in the Node/Resource selection menu.

### Steps to reproduce

1. Create a C# script inheriting from `Node`
2. Mark the script with the `[GlobalClass]` attribute
3. Place the script in an addon, i.e. `res://addons/my_plugin`
4. In any scene, add a node and search for our script created in step 1)
5. Notice that our script is missing from the selection

### Minimal reproduction project

[GlobalClassAddonsBug.zip](https://github.com/godotengine/godot/files/12162214/GlobalClassAddonsBug.zip)

**Comment by AThousandShips** [comment]
* Related: #78400

**Comment by duarteroso** [comment]
Funny, rebuilding just made it work. 
On a bigger project it doesn't seem to work... one of those things! Hopefully that issue will fix it :panic:

**Comment by duarteroso** [comment]
Right. The subfolder is the problem.
Closing
