### ISSUE TITLE
3D Child Node Visibility Bug When Instancing in Godot 4.2 Dev

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#79889]
### Godot version

4.2.dev [d69d4f1757]

### System information

Debian GNU/Linux trixie/sid x86_64

### Issue description

I am currently developing a Monopoly game using Godot 4.2 dev. In my project, I have a 3D node that acts as the child of another 3D node. In the scene, when the parent node is hidden, the child node is also hidden, which is the expected behavior.

However, I encountered a bug when I imported this scene as an instance into another 3D scene. In this new context, if the child node is set to be visible, but the parent node is hidden, the child node remains visible instead of inheriting the parent's visibility state.

##### Expected Behavior:

    Parent node hidden ➡️ Child node hidden
    Parent node visible ➡️ Child node visible

##### Actual Behavior (Bug):

    Parent node hidden ➡️ Child node still visible

This bug is causing unexpected visibility behavior in my project and may lead to inconsistencies in the game's rendering. Any help or insights on how to address this issue would be greatly appreciated.

### Video

[bug-3DObject-visibility-inheritance.webm](https://github.com/godotengine/godot/assets/6616005/3385836d-fef5-4fc2-abbe-cdc9d36b7cc4)

### Workaround
```gdscript
    for child_node in $building.get_children():
      child_node.visible = false

    for child_node in $wonder.get_children():
      child_node.visible = false
```

**Comment by Calinou** [comment]
@xsellier Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by xsellier** [comment]
You know what, forget it. Let's keep it like taht close the issue. someone's going to get it anytime soon so. thank you for answering @Calinou
