### ISSUE TITLE
From GUI bound NodePath is relative

### ISSUE THREAD

**Issue by enfyna** [godotengine/godot#79895]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Artix Linux 20230401 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 620 (KBL GT2) () - Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 Threads)

### Issue description

When binding a NodePath to a signal as an extra call argument the bound NodePath will be relative to the node. This behavior can be misleading and might lead to unreliable results if not used with caution.

### Steps to reproduce

- Create a root control node and a button node as a child.
![1](https://github.com/godotengine/godot/assets/91965312/d0d14620-5053-45e9-aa7c-38b61ceb975e)

-  Attach a simple script to the root node with the function that we will use to print the binded node.
![2](https://github.com/godotengine/godot/assets/91965312/a3fbd875-1c11-497a-b9f4-8ef2a3a44e7d)

- Bind the buttons pressed signal to the function we wrote.
![3](https://github.com/godotengine/godot/assets/91965312/015ae9fc-556d-4c3f-9d77-91e74a7d4451)

- Run the project and press the button. Function will print the root control node.
![4](https://github.com/godotengine/godot/assets/91965312/b7c6ff8c-407b-41dd-bf9e-bc6089476a80)

Also if we try to bind the root node the function will print the window node. This is why I think it is misleading.

And I think this is a bug too after we stop the project and try to change the node it will try to bind this :
![5](https://github.com/godotengine/godot/assets/91965312/c4670e29-9804-42da-be2d-3cacb6b65d24)

> /root/@EditorNode@17637/@Control@697/@Panel@698/@VBoxContainer@706/@HSplitContainer@709/@HSplitContainer@717/@HSplitContainer@725/@VBoxContainer@726/@VSplitContainer@728/@VSplitContainer@754/@VBoxContainer@755/@PanelContainer@800/MainScreen/@CanvasItemEditor@10090/@VSplitContainer@9915/@HSplitContainer@9917/@HSplitContainer@9919/@Control@9920/@SubViewportContainer@9921/@SubViewport@9922/Root/Button

This looks like a absolute path but when I run the project it will throw a node not found error and print <Object#null> .

### Minimal reproduction project

[minimal.zip](https://github.com/godotengine/godot/files/12163976/minimal.zip)

**Comment by Rindbee** [comment]
> Also if we try to bind the root node the function will print the window node. This is why I think it is misleading.

Not only the root node, but other nodes as well. Just open the connection dialog again after clicking the Connect button.

After clicking the Connect button, the edited object in the Inspector will become the script. When the connection dialog is opened again, the following code will return `nullptr`.

https://github.com/godotengine/godot/blob/031aa99d313ceec7cdb8263957d22cae10de0b95/editor/editor_properties.cpp#L2928

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/83700, which is more detailed.
