### ISSUE TITLE
acos() and asin() in particle shading language always return 0

### ISSUE THREAD

**Issue by maunesu** [godotengine/godot#79905]
### Godot version

4.1 stable

### System information

Godot v4.1.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3640) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

 acos() and asin() functions always return 0. I found and tested this issue in particle shading.

### Steps to reproduce

in a shading particle script, write something like:

acos(0.5) ->should return 60.0, but it  returns

float angle = <an angle in degrees>;
acos(cos(angle)) should return the angle, but it returns always 0.

same thing with asin() function

### Minimal reproduction project

as explained in"Steps to reproduce"

**Comment by clayjohn** [comment]
Testing locally with the following shader I get the correct output, totally white:
```
shader_type canvas_item;
render_mode blend_mix;

void fragment() {
	COLOR.rgb = vec3(acos(0.5));
}
```

I get the same results in a particles shader as well. 

My guess is you have made a mistake somewhere in your shader either in your inputs to the ``acos()`` function, or in displaying the output of it. However, you haven't provided enough information in your report to say one way or the other. 

In GLSL acos uses radians, not degrees. Maybe you are mixing those up somewhere and that is leading to the unexpected result?

**Comment by maunesu** [comment]
Thanks a lot for your answer.
Could be that I made a mistake, because I just started to learn shaders.
I have to check if the issue is due to those rad/degree conversions.

**Comment by maunesu** [comment]
Yeah. it was definitively a fault in my code due to rad/degrees conversion. Thanks for the support!
