### ISSUE TITLE
Node.set_global_pos(get_global_mouse_pos()) on Android is not working properly

### ISSUE THREAD

**Issue by Andevid** [godotengine/godot#7990]
**Operating system or device - Godot version:**
Build on Ubuntu 16.04 64 bit
Lenovo S880 Android 4.0.3
Godot 2.1.2 stable

**Issue description:**

Add a node to the parent according to the position of a mouse click.
when run on android device does not function like on the desktop.
with this code node.set_global_pos(get_global_mouse_pos())

**Steps to reproduce:**
Tap the screen to add a node on Android

**Link to minimal example project:**

Simple project https://github.com/Andevid/Flying-Fruity-Bird
Video https://web.facebook.com/doyanmulyana/videos/988087697991249/

**Comment by volzhs** [comment]
what about changing stretch mode to "2d" instead of "viewport"?

**Comment by Andevid** [comment]
Thank you for the advice.
I have tried it and the result is still the same for android devices.
Is there any other suggestions?

**Comment by Andevid** [comment]
I found this alternative
var pos_a = event.global_pos - get_global_transform_with_canvas().get_origin()
actor.set_global_pos(pos_a)

The problem is the first project was working, but the other projects that did not work, I have not found what distinguishes!!!

**Comment by vinod8990** [comment]
I also found this one, the global_mouse_pos is not updated when touching the screen. But it updates when we drag over the screen. After a drag, the global_mouse_pos will have the value of the last drag position. It stays like that until a next drag occurs.

**Comment by Hinsbart** [comment]
Closing as fixed in #8035
