### ISSUE TITLE
Godot doesn't ignore MacOS's hidden ._ (dot underscore) metadata files for C# files, leading to binary file errors

### ISSUE THREAD

**Issue by regimensocial** [godotengine/godot#79900]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - macOS 13.4.0 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

I use an external drive on my Mac due to the very stingy amount of storage they give you by default. It's an ExFAT drive so it'll work with the main Windows PC if need be. This is where I store my projects.

When writing C# code in an external editor, Visual Studio Code in this case, because it's on a non-Mac file system, it creates a complementary binary file which supposedly contains metadata. These have the same name as the file being created or edited, but it's prefixed by `._` (`file.cs` would be `._file.cs`).

Godot refuses to build when these files are present, you'll get an error like 
`CSC(0,0): '/Volumes/T7/Main/GodotProjects/Start/._Test.cs' is a binary file instead of a text file`
This only seems to be the case for `.cs` files; it doesn't matter if `._` GDScript files are present, the project still builds. 

In order to stop this, you need to remove the files. MacOS does have the functionality for this, you can run `dot_clean -m .` in the directory, but you have to do this every time you save a file.

The expected behaviour would be for Godot to specially ignore these MacOS hidden files.

### Steps to reproduce

1. On MacOS, create a project using Godot with Mono support on an external drive formatted to FAT32, ExFat, or NTFS.
2. Use an external editor like Visual Studio Code to write C# code, save it.
3. Run the project, you should get the error `CSC(0,0): '<file path>' is a binary file instead of a text file`

### Minimal reproduction project

N/A

**Comment by RedworkDE** [comment]
This is (almost certainly) not a Godot specific issue. Try creating a standalone C# project like that and compiling it with the `dotnet` command directly and you will see the same errors.

Also this seems to an issue that is very specific to your setup so I am not sure if Godot should try to work around it, especially since there could be projects that use such filenames for things that should be part of the project.

As a workaround you can try adding this to your `.csproj`:

```csproj
  <ItemGroup>
    <Compile Remove="**/._*" />
  </ItemGroup>
```

**Comment by Captain-AJ** [comment]
I have the exact same problem @regimensocial
