### ISSUE TITLE
Can't use get_thread_count() method in Thread

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#79924]
### Godot version

v4.1.stable.official [970459615]

### System information

window10 64bit

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/89276858-ccff-415a-a60c-0212f4963958)
Call `get_child_count()` method in a `Thread` ， It always return 0 and report error.
This function work well in 3.x and I need this method call in a thread.

### Steps to reproduce

/

### Minimal reproduction project

[GetChildCount.zip](https://github.com/godotengine/godot/files/12173429/GetChildCount.zip)

**Comment by bitsawer** [comment]
General node thread safety was made more strict in Godot 4.1. Generally, it's not safe to access node methods or properties in threads. In your case, you could pass the child count as argument to the thread.

In more complex cases, you can call `Thread.set_thread_safety_checks_enabled(false)` in the thread callback if you know what you are doing to enable old, unsafe behavior, but be aware that you might be doing something that is not supported and it just happens to work by coincidence.
