### ISSUE TITLE
The children of `RigidBody2D` do not apply scaling during runtime

### ISSUE THREAD

**Issue by Freedomax** [godotengine/godot#79929]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11- Godot v4.1.1.stable.official [bd6af8e0e] - Forward+

### Issue description

It's fine in the editor, but it's not working correctly when running the game.

![issue](https://github.com/godotengine/godot/assets/26040454/14f48194-f4a8-4001-b73f-f48da3baef5d)

### Steps to reproduce

Create a new 2D scene, add a `RigidBody2D` node to root `Node2D`, add a child node `Sprite2D` to the `RigidBody2D`, and then set the `Scale` of the Node2D's `Transform` to (2,2).

### Minimal reproduction project

[issue-scale.zip](https://github.com/godotengine/godot/files/12174798/issue-scale.zip)

**Comment by yosoyfreeman** [comment]
The scale of a RigidBody is intended to be always one.  If you scale the RigidBody 2D it sends this Warning:
![imagen](https://github.com/godotengine/godot/assets/64601424/e8bc26ca-82c7-4789-888a-dec308c77faf)

if you check the scale when the body is ready and in it's first physic's update the result is exactly the described by the warning: Is 1 when ready and 0.5 while it gets to the first physic's update. Is 0.5 to compensate of the parent distorting its transform to 2.  

so, technically is not a bug as is intended behavior. The question of scaling Rigid Bodies is often mentioned, some people think collision shapes should be scaled to counter act this, some not. But i think that's another debate.

**Comment by Freedomax** [comment]
Alright, now closing this question. I will avoid using scaling in Transform when using physics nodes.
