### ISSUE TITLE
Occluder node polygon handles disappear after release click

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#79939]
### Godot version

3.5.2 RC2

### System information

Windows 10

### Issue description

When clicking/click-dragging points on Occluder node polygons, the points disappear after each click release, a different node must be clicked first and the Occluder node reclicked before they will return.

### Steps to reproduce

* Add an occluder node
* Add an occluder polygon
* Click a parent node
* Click the occluder node
* Click and drag the polygon points to resize
* Repeat above steps each time after releasing the click

### Minimal reproduction project

N/A only an Occluder node is needed.

https://github.com/godotengine/godot/assets/16231628/21dbface-14c8-46cd-818b-c9c81cc36ec9

**Comment by lawnjelly** [comment]
Confirmed. This seems to be a regression, I haven't changed anything in the `Occluders` since implementing them so this seems caused by a general editor change. I'll see if I can bisect.
