### ISSUE TITLE
Clear color is lighter on mobile renderer

### ISSUE THREAD

**Issue by ChibiDenDen** [godotengine/godot#79931]
### Godot version

4.1.1

### System information

windows 11, mobile renderer

### Issue description

On Mobile Vulkan renderer, the clear color is 50% lighter than expected

See steps to reproduce and Minimal reproduction project below.

The box and background have the same color on Forward+ and compatibility, but not on Mobile
happens also in runtime on exported project, not only in editor preview

Images of the same scene from
compatibility:
![compatibility](https://github.com/godotengine/godot/assets/11915378/a874fa86-c16f-43ef-aed7-c2066b770ac1)
Forward+:
![forward](https://github.com/godotengine/godot/assets/11915378/e416f9a6-dfd4-4c47-bbc2-b552ca58f83c)
Mobile:
![mobile](https://github.com/godotengine/godot/assets/11915378/e28e2db8-f7c3-47e2-8c0a-44ce937c9270)

### Steps to reproduce

 - add a CSGBox3D with "unshaded" shading, and albedo of #545454
 - add environment with Background = Custom color and color of #545454

Box and background are not the same color

### Minimal reproduction project

[bg_color.zip](https://github.com/godotengine/godot/files/12174822/bg_color.zip)

**Comment by clayjohn** [comment]
This looks like a linear->sRGB conversion issue somewhere in https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp

**Comment by ChibiDenDen** [comment]
I think it has more to do with the _render_buffers_get_luminance_multiplierset to 2 in the mobile renderer here:

https://github.com/godotengine/godot/blob/41a7f6b38047773386710d5e49b64b173a3198de/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L342

adding a .darkened(0.5) at the end of this line fixed it for me:
https://github.com/godotengine/godot/blob/41a7f6b38047773386710d5e49b64b173a3198de/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L935

not sure if its the correct solution, I would love to create a pull request if you say it sounds right to you

**Comment by AndrewShobbrook** [comment]
Yeah it seems like they forgot to multiply the colours by 0.5 in this specific case (Comment in _render_buffers_get_luminance_multiplier says that it gets multiplied by 2 due to using a UNORM buffer and they just multiply by 0.5 when rendering)

**Comment by clayjohn** [comment]
> I think it has more to do with the _render_buffers_get_luminance_multiplierset to 2 in the mobile renderer here:
> 
> https://github.com/godotengine/godot/blob/41a7f6b38047773386710d5e49b64b173a3198de/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L342
> 
> adding a .darkened(0.5) at the end of this line fixed it for me:
> 
> https://github.com/godotengine/godot/blob/41a7f6b38047773386710d5e49b64b173a3198de/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L935
> 
> not sure if its the correct solution, I would love to create a pull request if you say it sounds right to you

Ya, that sounds right

**Comment by ywmaa** [comment]
I am having the same issue :

![image](https://github.com/godotengine/godot/assets/68971808/b1168d21-2a2e-4f2f-8bef-fedb2ff932b4)
![Uploading Screenshot from 2023-08-14 07-47-07.png
![Screenshot from 2023-08-14 07-47-29](https://github.com/godotengine/godot/assets/68971808/a37e17d3-1964-4c8d-884a-670182e4f513)
![Screenshot from 2023-08-14 07-47-36](https://github.com/godotengine/godot/assets/68971808/e52a61c9-6d76-49b7-b9e3-079800c000bd)
…]()


as you see a clear color is provided, still the actual color is brighter, and it messes my whole scene, so it makes it a totally different color than the forward plus
