### ISSUE TITLE
Raw Mouse Input

### ISSUE THREAD

**Issue by ericvoid** [godotengine/godot#7994]
Godot for Windows, Linux and MacOS.

`InputEventMouseMotion.relative_x`, `relative_y` and `relative_pos` provide the relative movement of the mouse processed by the Operating System. In other words, the OS read the raw input from the mouse, processes it (with sensitivity change, acceleration, and so on), and then the processed value is read from Godot mouse input api.

In Windows, for example, if you increase the mouse sensitivity setting in Control Panel, the values in Godot's `InputEventMouseMotion` is also amplified.

I'd like to be able to get the raw mouse movement data, without the OS processing. This is widely used in first person shooter games, such as CS, TF and OW. It is important when the gameplay requires accurate mouse tracking, and OS filters and biases are undesirable. The game may end up doing its own processing in the raw data, but its mechanics will be consistent across different OSes and OS settings.

**Comment by Zylann** [comment]
I would add that currently, the position of the mouse is always based on viewport pixels, never on screen pixels. As a result, if you downscale the game's viewport, mouse coordinates will also change, making FPS controllers less sensitive.
Related QA thread: https://godotengine.org/qa/13215/mouse-becomes-less-sensitive-in-low-res?show=13218#c13218

**Comment by ericvoid** [comment]
I did a little research on the subject, looking for the APIs for each platform. And it seems that this isn't something canonical.

On Windows, there are a few docs pages on the subject (although in the "Legacy User Interaction Features" section). By the way, it is the first result on google search: https://msdn.microsoft.com/en-us/library/windows/desktop/ms645543(v=vs.85).aspx

On X11 it becomes a bit hazy. Take a look at this QA: https://stackoverflow.com/a/24076974/385926

Now for OSX I couldn't find anything but people complaining about mouse issues and a guy offering a bounty for a hack: http://dae.me/blog/2243/

It seems that even CSGO/Valve has issues with Raw Mouse Input in X11 and OSX.

Still, it would be nice to see this implemented, even if it is a windows-only feature.

**Comment by quinnyo** [comment]
This would be a great feature to add. It's not particularly difficult to implement on windows or linux/x11 and it seems easy enough on mac but I don't have any experience there. 
 
I found this (zlib licensed) library which does all the core platform specific stuff: [https://icculus.org/manymouse/](https://icculus.org/manymouse/)
The readme/help has a good general overview. The library is only for mice, but the same OS features can be used for other input devices too.

**Comment by johnstt** [comment]
This would be really great to have when developing fps games for people who don't want mouse acceleration and all that jazz.

**Comment by cosmicchipsocket** [comment]
On Linux, libinput provides raw mouse deltas (including unaccelerated input): https://wayland.freedesktop.org/libinput/doc/latest/group__event__pointer.html

**Comment by fossegutten** [comment]
My FPS game and Breakout games both feel horrible to control with a mouse, without raw mouse input. Would be excellent if we had this as an option

**Comment by akien-mga** [comment]
Isn't this fixed already by #20523 and #19191?

**Comment by fossegutten** [comment]
Yes sorry, I did some more testing in Godot 3.1 beta 2. Seems like its working afterall :) 
I just saw that this issue was open and jumped on the bandwagon.
Probably some other issue with my projects.

**Comment by akien-mga** [comment]
I'm not sure how's the situation on macOS though, is raw input implemented there?

**Comment by johnstt** [comment]
So between those 2 PRs there's raw mouse support for Windows and Linux, right?
(and probably for macOS by the linux side if we're lucky?)

Really exciting and good news!

**Comment by Calinou** [comment]
Is this issue still relevant? Raw input is now implemented and used by default on Windows and Linux. According to the comments in this issue, it seems macOS doesn't provide any form of raw input to applications.

**Comment by Calinou** [comment]
Closing, as this has been implemented for Windows (#20523) and Linux (#19191) in Godot 3.1. macOS doesn't provide anything for raw input, so we can't implement it on that platform.

**Comment by xeonmc** [comment]
https://developer.apple.com/documentation/gamecontroller/gcmouse

**Comment by Calinou** [comment]
> [developer.apple.com/documentation/gamecontroller/gcmouse](https://developer.apple.com/documentation/gamecontroller/gcmouse)

Judging by the sidebar, this is only available on macOS Big Sur and later, so it would have to be used conditionally depending on the host OS version. Also, since this repository is now used for bug reports only, new features should be requested on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.

**Comment by prominentdetail** [comment]
> I would add that currently, the position of the mouse is always based on viewport pixels, never on screen pixels. As a result, if you downscale the game's viewport, mouse coordinates will also change, making FPS controllers less sensitive. Related QA thread: https://godotengine.org/qa/13215/mouse-becomes-less-sensitive-in-low-res?show=13218#c13218

I have been running into this issue too. I'm using godot 4.0 btw..
It causes the mouse movements to become janky at low resolutions (my game is designed to be low res).
One thing I found that improves the precision is to set:
Input.use_accumulated_input = false
https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-property-use-accumulated-input
With that set to false, the jankiness becomes less noticeable.
So if anyone reading is running into the jankiness, you can try that.
