### ISSUE TITLE
Can't see what I instantiated, but it is instantiated, I can print it's position and rotation etc., but can't see it in the scene, Top level checked and there's no background

### ISSUE THREAD

**Issue by El-Hazem** [godotengine/godot#79949]
### Godot version

v4.1.1.stable.official

### System information

Windows 10 - Forward+

### Issue description

I tried to instantiate it in the local position not the global , tried different project with different backend and non of them gave me different result  

### Steps to reproduce

```
if Input.is_action_just_pressed("Attack"):
		var bullet_markers = $Hit_Points.get_children()
		var selected_hit_point = bullet_markers[randi() % bullet_markers.size()]
		var ins_bullet = bullet.instantiate() as Area2D
		ins_bullet.position = selected_hit_point.global_position
		ins_bullet.rotation_degrees = rad_to_deg(direction.angle()) + 90
		# ins_bullet.direction = player_direction
		print(ins_bullet.global_position)
```

### Minimal reproduction project

[Jack'z Mistake.zip](https://github.com/godotengine/godot/files/12182218/Jack.z.Mistake.zip)

**Comment by clayjohn** [comment]
It looks like you are forgetting to add the bullet to the scene using ``add_child()``. You may want to take a look at the tutorial on instances: https://docs.godotengine.org/en/latest/tutorials/scripting/nodes_and_scene_instances.html#instancing-scenes

As a heads up. This space is for bug reports only. It is not a place to seek help with writing GDScript code. I suggest you ask for help in one of the [community channels](https://docs.godotengine.org/en/latest/community/channels.html).

**Comment by El-Hazem** [comment]
Sorry, i thought it was a bug , although thanks i appreciate it
