### ISSUE TITLE
Skeletal performance is very poor 

### ISSUE THREAD

**Issue by WOLFxxxxxx** [godotengine/godot#79956]
### Godot version

4.1.1

### System information

Window 10

### Issue description

Skeletal 3D performance is very poor
100 Skeletons = 50 FPS
The rest of the engines are 100 skeletons at 150 Fps

### Steps to reproduce

Skeletal performance is very poor
100 Skeletons = 50 FPS
The rest of the engines are 100 skeletons at 150 Fps

### Minimal reproduction project

Skeletal performance is very poor
100 Skeletons = 50 FPS
The rest of the engines are 100 skeletons at 150 Fps

**Comment by AThousandShips** [comment]
Just filling in the same thing three times isn't filling in the form properly

You need to provide more information, what skeleton setup are you using? What hardware are you on, what renderer are you using, etc.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/74540.

@WOLFxxxxxx Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by fire** [comment]
Can you fill in the form?

What gpu is this happening on?

Do you have a test case of 100 skeletons?

**Comment by AThousandShips** [comment]
Closing due to lack of response, can be reopened if you provide the details asked for
