### ISSUE TITLE
Add2 Blend Node in Animation Tree does not Add

### ISSUE THREAD

**Issue by bertodelrio256** [godotengine/godot#79963]
### Godot version

4.1 stable [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.1694) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

the Add2 node appears to simply blend instead of add. 

here is the blend happening in godot 4.1:

https://github.com/godotengine/godot/assets/98141558/57cdaddf-7f8c-41d1-81f2-7fc607fa8f75

here is what it looks like in blender:

https://github.com/godotengine/godot/assets/98141558/661d728f-e015-4fa5-b593-68eb5db58522

### Steps to reproduce

1. create a simple FK rig in blender and create a base animation.
2. create a additive animation setting the track blend mode to add in blender and position bones and keyframe them to create the animation
3. export the both animation as replace in blender for export to gltf.
4. open the glb in godot and create a animation tree and assign the the animation player as the target
5. add a blend tree and add the animations to the tree
6. add and Add2 node and blend the 2 animations
7. observe the issue

### Minimal reproduction project

ive attached a small reproduction project with a demo glb containing simple animations
[blendbug.zip](https://github.com/godotengine/godot/files/12185704/blendbug.zip)

**Comment by AThousandShips** [comment]
I suspect you need to filter out the bones to operate on, which Blended might do automatically

**Comment by bertodelrio256** [comment]
Yes, I do filter them. even if i didnt filter them it should not do that, there are no keyframes for the other bones.

**Comment by bertodelrio256** [comment]
sad to see this was never fixed

**Comment by jack27121** [comment]
it's not solved for me, on latest
