### ISSUE TITLE
Unexpected error message when creating alternate tiles

### ISSUE THREAD

**Issue by Walcygleicson** [godotengine/godot#79968]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce MX110 () - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

Whenever I create alternative tiles and I just hover the mouse cursor over that tile (in the editor) several errors are triggered in the terminal. I've never seen this happen before. The error says 'not all arguments converted during string formatting'. I don't know if I quit godot or if I go crazy
![Captura de tela 2023-07-27 162300](https://github.com/godotengine/godot/assets/113854464/87f7deaa-b8c2-4163-9139-2b8035a0e01d)

If this wasn't enough, another error message appears when I open the 'tile set' properties in the editor

![Captura de tela 2023-07-27 163349](https://github.com/godotengine/godot/assets/113854464/7a731182-6fe4-4032-a391-cd83e8cd2e47)

### Steps to reproduce

1 Create an Alternate Tile and then hover the cursor over the created tile, as long as the cursor is over the tile the terminal will trigger these errors

2 Create a tilemap and in the properties click on tile set, this is enough to trigger an error in the terminal

### Minimal reproduction project

none

**Comment by KoBeWi** [comment]
Hovering the tile displays a tooltip with formatting placeholders. What language do you use? It might be a translation error.

**Comment by Walcygleicson** [comment]
@KoBeWi 

I use GDScript. But I didn't make any script for this tilemap in question. In this case, the error is from the editor itself

**Comment by KoBeWi** [comment]
I meant editor interface language, not scripting. Some *editor translations* come with incorrect placeholders in translated strings.
There's a chance this is fixed in 4.2 dev, so you could give it a test.

**Comment by Walcygleicson** [comment]
@KoBeWi
oh okay, got it. I use Brazilian Portuguese. Maybe if I change the language of the editor it will stop?

**Comment by AThousandShips** [comment]
Probably due to this line:
https://github.com/godotengine/godot/blob/da81ca62a5f6d615516929896caa0b6b09ceccfc/editor/translations/editor/pt_BR.po#L1985-L1986

**Comment by KoBeWi** [comment]
I checked the language file and [indeed there was an error, but it's fixed in the newest version](https://hosted.weblate.org/translate/godot-engine/godot/pt_BR/?checksum=1101cefc841f76b0&q=alternative&sort_by=-priority%2Cposition#history). Try using 4.1.1 or 4.2 dev2.
