### ISSUE TITLE
get_drag_data() should not be hardcoded to activate only on left click

### ISSUE THREAD

**Issue by Saltlight-Studio** [godotengine/godot#79964]
### Godot version

4.1.stable.official

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 27.20.1028.1) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

This could end up being a scenario where I just completely missed the answer to this, but if so the docs are not immediately helpful, Is there currently some way of overriding it so mouse right click would instead or in addition to left click call get_drag_data()?

Been trying to look through both the documentation and source code and I cannot seem to find a way one could change this triggering input for get_drag_data(). To me so far it seems it is hardcoded to left click.

Currently I am working on a game where it might be useful to be able to start the interaction with right click and having to call force drag when there is a perfectly good virtual function system in place does not make a lot of sense.

If it is the case that this is hardcoded, I propose that one would have a setting in
Input Devices -> Pointing.
to activate data dragging on right click too.

Something like:
[X] "drag_data on mouse left"  -- This being set as default
[  ] "drag data on mouse right"

I imagine this could also help where a project that does not make use of drag and drop could have both of these settings turned off, maybe saving slightly on performance. 

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Hey. You are correct, there is no such feature. You should open a proposal about it: https://github.com/godotengine/godot-proposals

**Comment by Saltlight-Studio** [comment]
Went right ahead: https://github.com/godotengine/godot-proposals/discussions/7397

Thank you

**Comment by YuriSizov** [comment]
Closing in favor of the linked proposal discussion.
