### ISSUE TITLE
Renaming file without focusing on FileSystem doesn't work

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#79973]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

OpenGL API 4.1 Metal - 76.3 - Compatibility - Using Device: Apple - Apple M1 Max

### Issue description

If you right-click on a file on FileSystem panel without focusing, renaming file doesn't work (clicking on "Rename..." popup menu or pressing Enter).

https://github.com/godotengine/godot/assets/3025661/e5c7f833-78ea-47a8-b594-3c7548a75c50

### Steps to reproduce

- Click on another panel (eg. Scene, Inspector, Script)
- Right-click any file on FileSystem
- Click on "Rename..." popup menu (or press Enter)
- Nothing happens

### Minimal reproduction project

Doesn't need a specific project.

**Comment by Sauermann** [comment]
This is a known issue and already reported in #78789.
Consolidating with that bug-report as a duplicate.
