### ISSUE TITLE
Invalid Cast when using class keyword, but not class_name keyword

### ISSUE THREAD

**Issue by nicolas-scarrci** [godotengine/godot#79974]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Pop!_OS 22.04 LTS - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 3GB (nvidia; 535.54.03) - Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz (4 Threads)

### Issue description

If you preload and instantiate a .tscn you cannot save it in a variable whose type matches the scene's root's script if you used the 'class' keyword in the .gd. 
I expected this to work because the equivalent configuration works correctly if you use the 'class_name' keyword instead.

The specific error message is
assign a value of type Node to variable "notworking" with specified type res://UsingClass.gd.

If you attempt to cast the instantiated scene you get an Invalid Cast error
Invalid cast. Cannot convert from "Node" to "res://UsingClass.gd".

### Steps to reproduce

Check the demonstratebug.gd 

### Minimal reproduction project

[MRP - class invalid cast.tar.gz](https://github.com/godotengine/godot/files/12188905/MRP.-.class.invalid.cast.tar.gz)

**Comment by dalexeev** [comment]
This

```gdscript
class UsingClass extends Node:
    pass
```

is **not** the same as

```gdscript
class_name UsingClassName extends Node
```

Even if there is only one inner class in the file, there is still an outer class. Use this:

```gdscript
const UsingClassNameScene = preload("res://UsingClassName.tscn")
const UsingClass = preload("res://UsingClass.gd").UsingClass # <-- Inner class.
const UsingClassScene = preload("res://UsingClass.tscn")
```

**Comment by kleonc** [comment]
And to clarify further: omitting `extends some_class` for the given class (including script-class) is equivalent to making it `extends RefCounted`. So such script:
```gdscript
class UsingClass extends Node:
    pass
```
is equivalent to:

```gdscript
extends RefCounted # Script/outer class.

class UsingClass extends Node: # Inner class.
    pass
```

---

AFAICT all this info is already mentioned in the docs:
- [Classes](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#classes),
- [Inheritance](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance),
- [Inner classes](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inner-classes).

---

>I expected this to work because the equivalent configuration works correctly if you use the 'class_name' keyword instead.

As mentioned that's wrong assumption, they're not equivalent. AFAICT there's no bug in here. Not sure if there's anything to improve in the docs.

**Comment by dalexeev** [comment]
> Not sure if there's anything to improve in the docs.

We could mention the construct `preload("res://script.gd").InnerClass` for more clarity, but the GDScript Basics page is too big, I'm not sure if it's worth.

**Comment by nicolas-scarrci** [comment]
Thanks for getting back to me so quickly.
Between reading your comments and the linked documentation I see that there absolutely isn't a bug here. 
I've made a [pull request](https://github.com/godotengine/godot-docs/pull/7741) to change the docs that I hope will keep others from making the same mistake.
