### ISSUE TITLE
Extended class shows wrong icon

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#79979]
### Godot version

4.1.1

### System information

Linux Mint, Godot 4.1.1

### Issue description

Hi,

I've extended my own class, which extends "Node2D".
Now, in the create node menu, the icon from the "Node" class is displayed instead of the icon from the extended "Node2d"-class.

Here is a screenshot to show how it looks:
![Bildschirmfoto vom 2023-07-28 10-18-12](https://github.com/godotengine/godot/assets/34768615/378773cb-e47c-4cde-adeb-2444802058d7)

But after you create the node, the correct Icon is picked:

![Bildschirmfoto vom 2023-07-28 10-20-07](https://github.com/godotengine/godot/assets/34768615/3e8dc583-55fa-401e-a574-2d97297333a6)

Regards
abgenullt

### Steps to reproduce

Extend from a custom class and check the icon in the menu.

### Minimal reproduction project

[InheritTest.zip](https://github.com/godotengine/godot/files/12192148/InheritTest.zip)

**Comment by dalexeev** [comment]
The bug is reproducible in master, #79203 did not fix this. Maybe the reason is:

```
list=Array[Dictionary]([{
"base": &"Node2D",
"class": &"Base",
"icon": "",
"language": &"GDScript",
"path": "res://base.gd"
}, {
"base": &"Base",
"class": &"Extended",
"icon": "",
"language": &"GDScript",
"path": "res://extended.gd"
}])
```

As far as I understand, `base` should be a native class, even for inherited scripts.

**Comment by garychia** [comment]
It looks like `EditorNode::_get_class_or_script_icon` only works when the inherited script has a builtin base type. It does not try to find the icon for a non-builtin base type.
https://github.com/godotengine/godot/blob/90f90cbcb0cf2c44a3114048accfd5b407c4ac98/editor/editor_node.cpp#L4293-L4308
