### ISSUE TITLE
VoxelGI dynamic meshes linger in original position in GI data after bake, have lower energy when moved.

### ISSUE THREAD

**Issue by hanoixan** [godotengine/godot#79987]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3667) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When baking VoxelGI with a dynamic GI mesh, that mesh appears to stay in place in the GI data when moved. Furthermore, the mesh appears to emit less energy in the GI solution when it does move.

### Steps to reproduce

Open the repro project
Select VoxelGI to rebake
Move the box named Dynamic and notice 1) it's original GI data stays in place and 2) it is somewhat darker.

### Minimal reproduction project

[BugProject.zip](https://github.com/godotengine/godot/files/12195684/BugProject.zip)

**Comment by yosoyfreeman** [comment]
Hi there!

The problem happens exclusively with CSG shapes set as dynamic. This shapes are usually static and is probable that they are assumed to be always static. A coder should be able to allocate the problem better knowing it only affects CSG.

The reflection being darker when moved is just a secondary effect of the main problem: The shape is being baked _and_  computed in real time, so when the shape it's on the original place, the intensity is doubled.

I added a torus so is easy to see what is the common mesh shape and it works fine.

![csg bug](https://github.com/godotengine/godot/assets/64601424/212f92a5-6672-4e66-82f9-2360b0246b65)


Updated reproduction project: 

[CSGDynamicBug.zip](https://github.com/godotengine/godot/files/12198021/CSGDynamicBug.zip)

**Comment by hanoixan** [comment]
> The reflection being darker when moved is just a secondary effect of the main problem: The shape is being baked _and_ computed in real time, so when the shape it's on the original place, the intensity is doubled.

To clarify what I meant, I was referring to the dark artifacts/acne on the dynamic GI shape, which causes it to be darker than the static shape, not when they are overlapped.

Likely a separate problem due to the way dynamic GI is sampled.
