### ISSUE TITLE
AnimationNodeBlendTreeEditor: Missing Copy and Paste functionality.

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#80009]
### Godot version

4.x

### System information

Doesn't matter.

### Issue description

`animation_blend_tree_editor_plugin.cpp` has this code implying that you can paste data from clipboard. 
```
Ref<AnimationNode> clipb = EditorSettings::get_singleton()->get_resource_clipboard();
	if (clipb.is_valid()) {
		add_node->get_popup()->add_separator();
		add_node->get_popup()->add_item(TTR("Paste"), MENU_PASTE);
	}
```

But there is no copy functionality to be found. 
`Copy` option in menu is missing nor keyboard shortcuts exist.

### Steps to reproduce

N/A

### Minimal reproduction project

Repository Code.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/8146, as feature proposals are tracked on the godot-proposals repository.
