### ISSUE TITLE
Skeleton2D: adding modification SkeletonModification2DLookAt or SkeletonModification2DTwoBoneIK with default values causes error spam "skeleton_2d.cpp - Index p_idx = -1 is out of bounds (bones.size() = N)"

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#80012]
### Godot version

v4.1.stable.official [970459615]

### System information

Linux Ubuntu 22.04 with Unity desktop

### Issue description

I was following this tutorial at this time point: https://youtu.be/AMRjtW-3T0o?t=289
so I added a Modification Stack to my Skeleton2D, with a modification SkeletonModification2DTwoBoneIK

However, as soon as I did it, the Output window was spammed with errors:

> scene/2d/skeleton_2d.cpp:634 - Index p_idx = -1 is out of bounds (bones.size() = 16).

I verified that this happens with SkeletonModification2DLookAt, SkeletonModification2DTwoBoneIK, and this is due to default index values of -1. Setting `joint_one_bone_idx` to 0 in the inspector stops the error spam. After that, you cannot even come back to -1 or it will show:

> Bone index is out of range: The index is too low!

and reclamp back to 0, so it seems -1 is considered invalid anyway.

Either the default value should be 0, or we should avoid spamming errors.

This happens even if Modification Stack is not enabled.

### Steps to reproduce

1. Create a Skeleton 2D
2. Optional: add some bones. This is just so the skeleton actually makes sense, and setting index to 0 actually fixes the issue.
3. Create a Modification Stack on it.
4. Add a modification of type SkeletonModification2DLookAt or SkeletonModification2DTwoBoneIK
5. Observe error spam
6. Now set Bone Index / Joint One Bone Idx (depending on modification type) to 0. If you did 2, this will fix issue (otherwise it will cause error "Passed-in Bone index is out of range!" so index is stuck at -1 and error goes on)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Duplicate of?
*  #76712

**Comment by hsandt** [comment]
Indeed. And of course, now I manage to find the issue by searching "error spam skeleton_2d.cpp Index p_idx = -1 is out of bounds bones.size()" whereas I didn't find anything previously!

Their PR looks good too, I hope it can get integrated for next version.
