### ISSUE TITLE
HTML5 Nakama HTTPRequest failed!

### ISSUE THREAD

**Issue by ghghorbanzade** [godotengine/godot#80022]
### Godot version

4.1 & 4.1.1 stable

### System information

Windows 10 - NVIDIA GeForce RTX 2080 SUPER [Version 531.29] - Godot 4.1

### Issue description

Hi to all,
Unfortunately, I'm facing a weird situation exporting [the Nakama-WebRTC project](https://gitlab.com/snopek-games/godot-nakama-webrtc/-/tree/godot-4?ref_type=heads) on HTML5.
The Nakama server I used is SSL secured and has a reverse proxy that proxies the 443 port to the 7350 port.
But When I try to authenticate in the HTML5 export, I'm getting a 200 response code. Although Godot pushes RESULT_CANT_CONNECT = 2 as the HTTP response result, checking the response code on the Developer mode of the browser, it shows a 200 response code which means I'm getting the HTTP response successfully on my browser. I also checked the response and it has the right contents on it such as a token for establishing a WebSocket connection.
I have read the following issues which ended up on a Godot Core bugfix by @fabriceci:
[https://github.com/godotengine/godot/pull/47597](https://github.com/godotengine/godot/pull/47597)
[https://github.com/heroiclabs/nakama-godot/issues/66](https://github.com/heroiclabs/nakama-godot/issues/66)
P.S. My problem is the same as the mentioned issue above but in Godot 4. 

I also checked the Godot 3 branch of Nakama API with the Nakama server I configured, and it works fine.

### Steps to reproduce

1- export the project in [this link](https://gitlab.com/snopek-games/godot-nakama-webrtc/-/tree/godot-4?ref_type=heads) for HTML5. ( Test can be done by running the exported project locally or on a web host like itch.io.
2- configure a Nakama server with an SSL certificate and use port forwarding to secure the Nakama port 
3- try to authenticate on the exported app.

### Minimal reproduction project

NA (I didn't manipulate the original project except for port and server address)

**Comment by Sslaxx** [comment]
CC @dsnopek

**Comment by TheYellowArchitect** [comment]
@ghghorbanzade There are 2 WebRTC demos in [godot-demo-projects](https://github.com/godotengine/godot-demo-projects/tree/master/networking)
Can you try either? Chances are WebRTC broke on 4.1, instead of Nakama being responsible

**Comment by ghghorbanzade** [comment]
> @ghghorbanzade There are 2 WebRTC demos in [godot-demo-projects](https://github.com/godotengine/godot-demo-projects/tree/master/networking) Can you try either and confirm they work as expected? Chances are WebRTC broke on 4.1, instead of Nakama being responsible

The problem rises in email-authentication and it's before WebRTC signaling starts. The HttpRequest to Nakama server for authentication fails in WebApp with a RESULT_CANT_CONNECT error, while the developer mode of the browser gets the Nakama's response in the correct form (user token is recieved in the browser. But it doesn't pass to the webapp correctly).

**Comment by ghghorbanzade** [comment]
According to [this commit](https://github.com/godotengine/godot/pull/79846), this problem is solved in Godot 4.2 Dev2. 
Thanks to @fabriceci.
