### ISSUE TITLE
Texture repeat disables if window is resized using the compatibility renderer.

### ISSUE THREAD

**Issue by TomCatFort** [godotengine/godot#80027]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1070 Ti (nvidia; 470.199.02) - Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 Threads)

### Issue description

If a 3D scene is rendered using the Compatibility renderer where a repeated texture is displayed on a mesh, the texture repeating disables if the window is resized.
The issue may also present itself in the editor if the scene or project is reloaded.
Does not occur using the Mobile, or Forward+ renderer.

If a visible CanvasItem (eg.: Sprite2D, Button) is also present on the screen, the issue seemingly fixes itself until said CanvasItem is hidden and the window is resized again.

Before resize, texture is repeated correctly:
![repeat_ok](https://github.com/godotengine/godot/assets/784076/750b9c2a-76d8-4372-a1be-a0f7cbdd9e66)

After resize, texture repeat is disabled:
![repeat_not_ok](https://github.com/godotengine/godot/assets/784076/6329f630-3669-43de-a9f8-da33d6ee6870)

After enabling the Sprite's visibility, the texture repeating begins to work again:
![repeat_fixed_by_canvas_item](https://github.com/godotengine/godot/assets/784076/bb27536e-2159-4050-94a2-8deb4c9a1d37)

### Steps to reproduce

1. Set the renderer to Compatibility.
2. Create a new basic 3D scene.
3. Add mesh with a material that repeats textures.
   The easiest is to use an unshaded StandardMaterial3D with UV1 scaling and Repeat being enabled under the Sampling category.
4. Run your scene.
4. Resize the window using any method.

### Minimal reproduction project

[texture_repeat_repro_project.zip](https://github.com/godotengine/godot/files/12207836/texture_repeat_repro_project.zip)

This the project that I used to create the images for the description.
Uses both a StandardMaterial3D, and a ShaderMaterial to see if there is any difference.

To reproduce the issue with it, simply run the project and resize the window.

There is also a Sprite2D in the scene, by default hidden.
Simply change it's visibility while the project is running to see how it affects the issue.
The editor's Synchronize Scene Changes feature is perfect for this.
- While the sprite is visible, the issue can not be reproduced.
- If the issue is reproduced, setting the sprite from hidden to visible immediately fixes the issue.
- If the sprite becomes hidden, the next time the window is resized again, the issue is immediately reproduced.

**Comment by Calinou** [comment]
Can you test 4.2.dev2? See https://github.com/godotengine/godot/issues/79315.

**Comment by TomCatFort** [comment]
I have tested it with 4.2.dev2, and I was not able to reproduce the issue.
Looks like it is fixed in the dev version.

**Comment by Calinou** [comment]
> I have tested it with 4.2.dev2, and I was not able to reproduce the issue. Looks like it is fixed in the dev version.

Thanks for checking :slightly_smiling_face: Closing then. The fix is marked for a 4.1.x cherrypick.
