### ISSUE TITLE
Corrupted files because full harddrive

### ISSUE THREAD

**Issue by warsang** [godotengine/godot#80026]
### Godot version

4.1

### System information

Windows 10

### Issue description

Hi! I had a pretty stressful experience with Godot recently. I love the game engine and have been using it for the last couple of months. My project is stored on my SSD and I was getting closer and closer to that SSD being full without realizing. Last time I opened the project, I was getting errors about res imports failing and nothing super explicit. I close the project and the next time I open it, my project.godot file is corrupt, some of my tscn's are corrupted and I lose a lot of work...
I was able to get the files back by using file forensic tooling (autopsy); However, the whole experience was pretty stressful and I only realized when I opened the broken project the second time that the files had been corrupted because of low disk space.
I'm not really reporting a bug but I think it would be a big improvement to have some kind of warning pop-up when you're reaching low disk space mentioning files may become corrupted and you may lose work.

### Steps to reproduce

Get a full ssd and work/save an ongoing project. Close and open it a couple of times.

### Minimal reproduction project

NA

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/45354.
