### ISSUE TITLE
Navigation example in manual: "flush: Trying to execute a deferred call..."

### ISSUE THREAD

**Issue by Vivalzar** [godotengine/godot#80023]
### Godot version

v4.2.dev2.official [da81ca62a]

### System information

Godot v4.2.dev2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3667) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When executing the example in [2D Navigation Overview](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html#setup-for-2d-scene), the following error message appears twice in the output:

```
E 0:00:00:0485   flush: Trying to execute a deferred call/notification/set on a previously freed instance. Consider using queue_free() instead of free().
  <Source C++>   core/object/message_queue.cpp:327 @ flush()
```
No error appears with Godot 4.1.1. Maybe a small regression is lurking here.

### Steps to reproduce

Just follow the short example in [2D Navigation Overview](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html#setup-for-2d-scene).

### Minimal reproduction project

Just follow the short example in [2D Navigation Overview](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_introduction_2d.html#setup-for-2d-scene).

**Comment by smix8** [comment]
Those errors are for the most part false positive and appear all over the place in the engine since https://github.com/godotengine/godot/pull/78987 was merged and are indifferent towards navigation.

**Comment by smix8** [comment]
Closing as a duplicate as the problems with those false error msg are already tracked.
