### ISSUE TITLE
Missing Signal "button_selected" on "VBoxContainer"(ButtonGroup)

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8002]
Error on Project loading
Windows, master

```
ERROR: In Object of type 'VBoxContainer': Attempt to connect nonexistent signal
'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core/object.cpp:1416
````

https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/editor/plugins/canvas_item_editor_plugin.cpp#L3826

Can someone explain how to use ButtonGroup in 3.0
https://github.com/godotengine/godot/commit/a503f8aadcb8cbc85bde589fb25ea06e599b367b
EDIT found it see Group:
![image](https://cloud.githubusercontent.com/assets/4741886/23819519/c66eb2c2-0607-11e7-8a27-a1a4c045711e.png)
part of #7888

**Comment by volzhs** [comment]
fixed by #8017
