### ISSUE TITLE
instantiate scenes

### ISSUE THREAD

**Issue by Cris-lml007** [godotengine/godot#80030]
### Godot version

4.0.3.stable.official.5222a99f5

### System information

Kali Linux

### Issue description

I am trying to create a bubble game, create a scene containing a StaticBody2D with a CollisonShape2D node, Create a script for this one with a function that helps me modify its properties from another scene, works correctly for the first child node, but when creating two I see that these are linked, being that if I modify the property of one, the other is also modified, because this happens and how can I solve it.

### Steps to reproduce

I'm not sure if it should be done like this, but I printed the memory addresses of the objects and I see that they share or use the same object.
```
Godot Engine v4.0.3.stable.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.246 - Forward Mobile - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.7, 256 bits)
 
<CircleShape2D#-9223372011286297466>
<CircleShape2D#-9223372011286297466>
obj1:CollisionShape2D:<CollisionShape2D#25753027723>
obj2:CollisionShape2D:<CollisionShape2D#25786582157>
obj1:<CircleShape2D#-9223372011286297466>
obj2:<CircleShape2D#-9223372011286297466>
```
![image](https://github.com/godotengine/godot/assets/83845332/08b40fec-2216-4598-b3be-c26f232e3bbb)
Here you can see that of the main nodes, their shape subnode is compared between the two.
```
obj1:<CircleShape2D#-9223372011286297466>
obj2:<CircleShape2D#-9223372011286297466>
```

### Minimal reproduction project

This is the script of the object (scena) that I want to create several times in my main scene
```gdscript
extends StaticBody2D

class_name BubbleBase

@onready var colision=$CollisionShape2D

func _ready():
	colision.shape.radius=get_meta("radius");
	pass # Replace with function body.

func setRadius(radius:int):
	colision.shape.radius=radius
	print(colision.shape.radius)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

func _draw():
	draw_circle(Vector2(0,0),colision.shape.radius,Color.BROWN)
```
![image](https://github.com/godotengine/godot/assets/83845332/3dd884ef-fad8-451a-b9c4-3706ec5402ac)

---
the script for my main scene
```gdscript
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	$StaticBody2D/CollisionShape2D.shape.radius=50
	$StaticBody2D2/CollisionShape2D.shape.radius=100
	print("obj1:",$StaticBody2D/CollisionShape2D)
	print("obj2:",$StaticBody2D2/CollisionShape2D)
	print("obj1:",$StaticBody2D/CollisionShape2D.shape)
	print("obj2:",$StaticBody2D2/CollisionShape2D.shape)
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```
![image](https://github.com/godotengine/godot/assets/83845332/fa63e36c-6939-4954-9f47-04382b2e4eb0)

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

**Comment by Cris-lml007** [comment]
I put it here because I think it's a mistake, every node that is called should not create its own subnodes and not share them, or I'm wrong?

**Comment by Calinou** [comment]
> I put it here because I think it's a mistake, every node that is called should create its own subnodes and not share them, or I'm wrong?

Resources are shared by default for performance reasons. Enable **Local to Scene** on the CollisionShape resource in the inspector to automatically duplicate a resource upon instancing, or call `.duplicate()` on the resource in a script to duplicate it before you make any changes to it.

**Comment by Cris-lml007** [comment]
I understand, thank you very much for your prompt reply.
