### ISSUE TITLE
Load and Save issue Godot 4 :(

### ISSUE THREAD

**Issue by fatheroflead** [godotengine/godot#80048]
### Godot version

4.0

### System information

windows 

### Issue description

I have simple code to save and load the position of player and i know how to use them its easy to save the game and easy to load it but the issue is that i don't know how to load the game from the main menu.
I have a (New Game button) and (Load button), i just wanna know how to make a load button from the main menu , if i pressed it , it will change the scene to other scene and load the postion of player , and if i pressed on the new game it will start a new game and if i save the game from the new game i want to load it from the load button in the main menu.
"ITS 2 SCENES AND ONE OF THEM HAS THE LOAD BUTTON AND THE OTHER HAS THE SAVE BUTTON"
please help me with this :(

### The codes:

###Load code:

func _load() -> void:
	if !FileAccess.file_exists("saveFile"):
		print("Error 404, The file not exist")
		return
		
	var save_file = FileAccess.open("saveFile", FileAccess.READ)
	
	while save_file.get_position() < save_file.get_length():
		
		var json = JSON.new()
		json.parse(save_file.get_line())
		
		var node_data = json.get_data()
		if has_node(node_data["filepath"]):
			get_node(node_data["filepath"]).loadObject(node_data)
	
	save_file.close()
....................................................................................................................................................................................

###Save code:

func _save() -> void:
	var save_file = FileAccess.open("saveFile", FileAccess.WRITE) # Open File
	
	var save_nodes = get_tree().get_nodes_in_group("SaveLoad")
	for node in save_nodes:
		if !node.has_method("saveObject"):
			print("Node '%s' is missing a save function, skipped" % node.name)
			continue
			
		var node_data = node.call("saveObject")
		
		save_file.store_line(JSON.stringify(node_data))
		
	save_file.close() 
....................................................................................................................................................................................

###global save_file code:

var player_file = "user://save_file.save"

func _ready():
	pass

func save_file():
	var file = FileAccess.open(player_file, FileAccess.WRITE)
	var player_data = create_player_data()
	file.store_var(player_data)
	
func load_file():
	var file = FileAccess.open(player_file, FileAccess.READ)
	if file.file_exists(player_file):
		var loaded_file_data = file.get_var()
		
func create_player_data():
	var player_dict = {}

### Minimal reproduction project

:(

**Comment by Zireael07** [comment]
This is not the place to ask for help with your code. Use other community channels for this.

**Comment by AThousandShips** [comment]
Indeed, for support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.

**Comment by fatheroflead** [comment]
> This is not the place to ask for help with your code. Use other community channels for this.

im sorry idk but can u help with this issue?

**Comment by AThousandShips** [comment]
This is for bug reporting, not support, please go to the other channels, we do not provide this kind of support here

**Comment by fatheroflead** [comment]
> This is for bug reporting, not support, please go to the other channels, we do not provide this kind of support here

bro why so angry??!!!

**Comment by AThousandShips** [comment]
1) I'm not a "bro"
2) I'm not angry, I'm calmly explaining what the rules are, follow them

**Comment by fatheroflead** [comment]
> 1. I'm not a "bro"
> 2. I'm not angry, I'm calmly explaining what the rules are, follow them
> 
> Please follow instructions and rules

never mind,

the godot engine q&a is under maintenance

**Comment by AThousandShips** [comment]
Not a reason to use this channel, there are other channels for support, do not open these kind of issues in the future

Have a nice day
