### ISSUE TITLE
The engine crashes after changing the path to the node

### ISSUE THREAD

**Issue by RinF-UwU** [godotengine/godot#80041]
### Godot version

v4.1.1-stable_mono_win64

### System information

Windows 11

### Issue description

I removed the node to replace it with another, but when I change the path in the code, the engine crashes for me.

### Steps to reproduce

I did a screen recording as it happens:

https://github.com/godotengine/godot/assets/116289408/b2fd2689-8d82-44e8-8e02-be01674842e1

### Minimal reproduction project

[MixApo.zip](https://github.com/godotengine/godot/files/12208403/MixApo.zip)

**Comment by rsubtil** [comment]
Godot is entering an infinite loop here:
https://github.com/godotengine/godot/blob/f7bc653cbe81018fe362472a0143b7153a52f929/scene/gui/code_edit.cpp#L3151-L3168

Reverting https://github.com/godotengine/godot/pull/75746 fixes the problem (cc @ajreckof)

**Comment by ajreckof** [comment]
I'll take a look at it tomorrow but to be sure is Godot crashing or is it freezing?

**Comment by rsubtil** [comment]
> I'll take a look at it tomorrow but to be sure is Godot crashing or is it freezing?

It doesn't crash. When poking around in `gdb` it seems like it never exits this loop.

**Comment by ajreckof** [comment]
Okay so it is not really freezing it is just taking way way way way way way too long. What is actually happening is that it is trying to find all possible way to match the query inside way too long options. Just to give an idea of how bad this becomes here the query is around 40 characters long and options are often 200-300 long. which means at some steps it can go up to 10000000 matches which slow down the whole process. 
With that said I have a quick and easy fix that do make it quicker not really perfect but still usable it uses an altered version that gives more precedence to grouped by not looking further if the next character matches. Beware that this means the altered algorithm will take the first c in  "MaincartoonCanvas" even for a queryy like "MainCanvas", this obviously mean it will rank differently option that show this behaviour . This is the worst case I could think of.

I made a quick PR there it runs smoothly even with OP really astronomical example (around a hundred or even more options with a size of around 300 for some).
