### ISSUE TITLE
Infinite Import Loop Bug with renaming folders with blend-files inside

### ISSUE THREAD

**Issue by nano13** [godotengine/godot#80049]
### Godot version

v4.2.dev.custom_build [75f9c97de]

### System information

Linux. However this should not matter here ...

### Issue description

Renaming Folders with Blender-Files inside does not work. 

The result is an infinite loop of trying to import the blender models searching the models still on the old path and not the updated one.

E.g. using my project:
https://github.com/nano13/GodotFirstPersonController/blob/main/README.md

And trying to rename the folder `Models` to `models` gives error messages like these in the console:

```
ERROR: Can't find file 'uid://c2xnrl0gkw8ix::::res://Models/textures/dv222.tga'.
   at: _reimport_file (editor/editor_file_system.cpp:1937)
ERROR: Can't find file 'uid://cqce5bblylj5e::::res://Models/textures/intlights222.tga'.
   at: _reimport_file (editor/editor_file_system.cpp:1937)
ERROR: Can't find file 'uid://c82vttiixik57::::res://Models/textures/drevco222.tga'.
   at: _reimport_file (editor/editor_file_system.cpp:1937)
ERROR: Can't find file 'uid://d0mq5yjphyh8s::::res://Models/textures/leather222tga.tga'.
   at: _reimport_file (editor/editor_file_system.cpp:1937)
ERROR: Can't find file 'uid://dkqxa3anhto25::::res://Models/textures/velbag222tga.tga'.
   at: _reimport_file (editor/editor_file_system.cpp:1937)
```

Which is true as the folder name `Models` in the path has not been updated, but the folder is actually renamed

(I will however try to fix this issue for my example project by manually renaming the path in all the configs)

### Steps to reproduce

Checkout my project from the URL above, and try to rename the folder called `Models`/`models`.

### Minimal reproduction project

See the URL above.

**Comment by AThousandShips** [comment]
Thank you for reporting, please add the specific commit hash to your issue description, "latest" moves constantly

**Comment by nano13** [comment]
In the import-files, e.g. `models/mercedes_s500_wheel.blend.import` it did not update the renamed folder `Materials` to `materials` either ...

**Comment by nano13** [comment]
After fixing the blender-issue (https://github.com/godotengine/godot/issues/76338) by upgrading to blender 3.6.1 this seems not to be a problem anymore.

So as far as I can currently tell, it would be safe to close this issue now.

**Comment by nano13** [comment]
After fixing the blender-issue (https://github.com/godotengine/godot/issues/76338) by upgrading to blender 3.6.1 this seems not to be a problem anymore.

So as far as I can currently tell, it would be safe to close this issue now.
