### ISSUE TITLE
Image bigger than 5000px renders black in Android Chrome when running Web exported project

### ISSUE THREAD

**Issue by fguillen** [godotengine/godot#80050]
### Godot version

4.1.1.stable

### System information

MacOS - Ventura 13.1 - Godot 4.1.1.stable

### Issue description

When I add an image bigger than 5000px to my project (I tried in Sprite2D and in AnimatedSprite2D) the image renders black when I open the project, web exported, in Android Chrome (don't know other devices)

![Screenshot 2023-07-30 at 12 08 29](https://github.com/godotengine/godot/assets/23043/0bf5d0fb-435d-4dd8-a25a-489d1dcee392)
![Screenshot_20230730-121036](https://github.com/godotengine/godot/assets/23043/f8750fea-b81f-467c-9000-470e70efb97d)

### Steps to reproduce

Create an image bigger than 5000px (I tried with PNG).
Add it to a Sprite2D
Export to web
Open it in an Android Chrome

### Minimal reproduction project

[TestingBigImage.zip](https://github.com/godotengine/godot/files/12208906/TestingBigImage.zip)

You can test it online here:

- https://arturitoproductions.itch.io/testingimageissue (password: godot)

**Comment by AThousandShips** [comment]
This sounds like a platform limitation to me

**Comment by fguillen** [comment]
In deed: 

> Mobile GPUs are typically limited to 4096×4096 textures

Closing
