### ISSUE TITLE
Control set_pos -> set_position

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8005]
Since Node2D set_pos() has changed to set_position() in 3.0 I think Control set_pos() should also be renamed to keep everything consistent.

 
![image](https://cloud.githubusercontent.com/assets/4741886/23815773/d4c091d8-05e9-11e7-9937-d5156779e40b.png)

![image](https://cloud.githubusercontent.com/assets/4741886/23815744/ba44d724-05e9-11e7-9869-3418a3bde340.png)

https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/core/math/math_2d.h#L207
https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/scene/gui/control.cpp#L60

See also that Node2d has a set_rotation_in_degrees(value) and set_rotation(value)
Control has only set_rotation(radians).

**Comment by spusnei-pbsc** [comment]
when validating please take note of #8197

**Comment by sergey-push** [comment]
do we have to also change (global_)mouse_pos to mouse_position?

**Comment by akien-mga** [comment]
> do we have to also change (global_)mouse_pos to mouse_position?

I think that would be good yes.

**Comment by akien-mga** [comment]
I think it would be fine in the same commit.
