### ISSUE TITLE
GDScript: inconsistencies in constants

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#8006]
**Operating system or device - Godot version:**
Godot 2.1.x, probably 3.0 as well

**Issue description:**
GDScript recognition of constants is still not universal. There are certain cases that I think it should handle:

You can do this:
```
# Built-in functions by themselves work
const a = deg2rad(90.0)

# Some built-ins work with a const argument although not a literal
const b = sin(a) 

# Involvement of built-ins in binary operators work with a literal argument
const c = sin(1.57) + cos(1.57)
```

But you can't do any of these:
```
# Composition of built-in functions fails
const d = sin(deg2rad(90.0))

# Certain built-ins fail with a non-literal argument (though constant))
const e = 32
const f = pow(2, e)

# Involvement of built-ins in binary operators don't work with a non-literal constant argument
const g = 3.14
const h = sin(1.57) + cos(g)
```

I think all these non-working cases fit the const world so it would be nice for GDScript to generalize it's handling of constants-

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by qarmin** [comment]
This is really frustrating, because  I expected that this code should work:
```
const W : float = 128.0
const Q : Vector2 = Vector2(W,1)
```
but instead shows this error:
```
 res://Battle.gd:6 - Parse Error: Expected constant expression
 modules/gdscript/gdscript.cpp:580 - Method/Function Failed, returning: ERR_PARSE_ERROR
```

**Comment by bojidar-bg** [comment]
Retested the sample code on master-ish (v3.2.dev.custom_build. 4cb088766)

The following work:
```gdscript
# Built-in functions by themselves work
const a = deg2rad(90.0)

# Involvement of built-ins in binary operators work with a literal argument
const c = sin(1.57) + cos(1.57)

# Composition of built-in functions *now works*
const d = sin(deg2rad(90.0))

# Involvement of built-ins in binary operators works if there are no built-ins around the other constants used
const i = 3.14
const j = sin(1.57) + g
```

The following don't:
```gdscript
# Certain (all?) built-ins fail with a non-literal argument (though constant))
const e = 32
const b = sin(e)
const f = pow(2, e)

# Involvement of built-ins in binary operators don't work with a non-literal constant argument
const g = 3.14
const h = sin(1.57) + cos(g)
```
