### ISSUE TITLE
Editor's "Report System Info" should report more critical info

### ISSUE THREAD

**Issue by darksylinc** [godotengine/godot#80061]
### Godot version

master [75f9c97deaa8378477441e07ea1782ecab6d2eca]

### System information

Godot v4.2.dev (262d1eaa6) - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Follwing what I said in https://github.com/godotengine/godot/issues/71929#issuecomment-1657193151 Godot does not print enough data we need to troubleshoot some problems.

Right now on my system it prints:

```
Godot v4.2.dev (262d1eaa6) - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)
```

Whereas it should print:

```
Godot v4.2.dev (262d1eaa6) - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

Vulkan devices:
#0: AMD AMD Radeon RX 6800 XT - Supported, Discrete - Vulkan API 1.3.208 - Driver Version 2.0.221.0 (0x8000dd)
#1: AMD AMD Radeon RX 6800 XT (RADV NAVI21) - Supported, Discrete -  Vulkan API 1.3.238 - Driver Version 23.0.4.0 (0x5c00004)
#2: Unknown llvmpipe (LLVM 12.0.0, 256 bits) - Supported, CPU - Vulkan API 1.x.x - Driver Version x.x.x.x (0xxxxxxxx)
#3: Unknown llvmpipe (LLVM 15.0.7, 256 bits) - Supported, CPU - Vulkan API 1.x.x - Driver Version x.x.x.x (0xxxxxxxx)
#4: AMD AMD Radeon RX 6800 XT (RADV NAVI21) - Supported, Discrete - Vulkan API 1.x.x - Driver Version x.x.x.x (0xxxxxxxx)

Vulkan API 1.3.208 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6800 XT
```

This is important because on some Optimus laptops the version of the Intel driver is relevant even though they're using the NVIDIA card. Users should be advised to update to the latest drivers **for both NV and Intel**, not just the NV one.

### Steps to reproduce

1. In Editor Go to -> Help -> Copy System Info

### Minimal reproduction project

No need.

**Comment by AThousandShips** [comment]
Thank you, but this should be a [proposal](https://github.com/godotengine/godot-proposals), this is for bugs

**Comment by darksylinc** [comment]
Ok, I'll repost there. Closing this one.
