### ISSUE TITLE
Sprite3D can't be one-sided

### ISSUE THREAD

**Issue by hikari-no-yume** [godotengine/godot#8007]
`Sprite3D` nodes have a backface, they're two-sided. Unfortunately, you can't disable this if you want to, say, have a different sprite for the reverse. This is easy enough to work around by using a `Quad` instead, but a simple “One-sided” or “No backface” checkbox would be simpler.

**Comment by TazeTSchnitzel** [comment]
What I'm actually after here is a two-sided sprite, however, so a two-sided mode for `Sprite3D` where it uses a different part of the texture for front and back would be even better, to avoid needing two different objects. That said, using two one-sided `Sprite3D` nodes isn't that burdensome, so it might be better to avoid overcomplicating it.

**Comment by TazeTSchnitzel** [comment]
If you're using a sprite in billboard mode, omitting the backface geometry avoids having two polygons that'll never be drawn. That's probably more worthwhile as an engine optimisation than a user option, though.

**Comment by bojidar-bg** [comment]
@TazeTSchnitzel I agree for all except your last point, since I bet we don't make backface geometry, but a backface material (thus it doesn't really affect performance much).

**Comment by TazeTSchnitzel** [comment]
Ah! Yes, that makes sense.

(re: the junior job tag, I was thinking this is probably simple enough for me to implement myself)

**Comment by TazeTSchnitzel** [comment]
Oh,`Sprite3D` is currently broken in `master`, probably due to the graphics rewrite. If anyone else wants to try their hand at implementing this, check if this has been fixed first.

**Comment by hikari-no-yume** [comment]
Implemented for 2.1.x here: https://github.com/godotengine/godot/pull/8434
