### ISSUE TITLE
Player's legs jitter when moving left and right (both Sprite2D and Sprite3D)

### ISSUE THREAD

**Issue by dark-elf1** [godotengine/godot#80082]
### Godot version

v3.5.2.stable.openSUSE [170ba337a] and v3.5.2.stable.official [170ba337a]

### System information

openSUSE Tumbleweed 20230729, AMD RX 550 4GB, Mesa 23.1.4, GLES2 & GLES3, KDE Plasma Wayland & X11

### Issue description

https://github.com/godotengine/godot/assets/110809639/6c67523c-5a08-4888-a6f8-495b200a5b1c
(not sure if you can see when the jitter happens on video, minimal reproduction project is a better bet)
Both 2D and 3D sprite have this issue. The player's legs and feet jitter only when he is moving. If he is static and the animation is playing then the jitter doesn't happen. Also if the camera is actively following the player then the jitter doesn't happen. In other words if the camera is static but the player is moving the described issue happens. Player sprite is 1080px X 1080px.
Tried both GLES2 & GLES3 renderers, Wayland and X11 session and same result.

### Steps to reproduce

Place either the 2D or 3D sprite and add it as a child to the kinematic body
Give the sprite texture (in my case sprite sheet with walk animation) and animate it with animation player
Attach the standard script for kinematic body movement on X axis
Or open the 2D and 3D scenes from minimal reproduction project

### Minimal reproduction project

[mrp_sprite_issue.zip](https://github.com/godotengine/godot/files/12213874/mrp_sprite_issue.zip)

**Comment by blade7seven** [comment]
the issue exist on my windows 10  

https://github.com/godotengine/godot/assets/138454281/814766c7-3813-47cd-af1f-86945a875342

**Comment by dark-elf1** [comment]
> I tried a couple of things.
> 
>     * First to note the texture size is huge (6480 x 6480). Just be aware that a lot of GPUs may not cope with this well. I tried scaling down the texture x 4 but was still seeing something in the legs.
> 
>     * I noticed the thread mode was set to multithread, I would go for single safe unless there is a particular reason not to (multithread just isn't as tested, and could introduce problems itself).
> 
>     * I changed the parent node from `KinematicBody` to `Node2D` to eliminate physics as influencing.
> 
> 
> I was getting tearing even with vsync on my PC, whether that is contributing I don't know.
> 
> But I suspect this thing you are describing may not actually be the engine, it could just be the 2D artwork is not hiding motion jitter (i.e. you are effectively using stop frame animation), and it is being exacerbated when the whole body is in motion. Motion blur is typically used to hide this kind of thing afaik, so if you are pre rendering, maybe you can do this with motion blur. I can't be sure of course, but I'm aware technical artists spend a lot of time perfecting this kind of thing.
> 
> For 3D versions of this, animation players / and or physics interpolation can tween between rotations which tends to hide this kind of thing.
> 
> This is all assuming we are talking about the same "jitter". There's lots of things that are considered jitter in games / engines.

Thanks for the info! Much appreciated.

I was talking about that shaking/jittering, I don't know what else to call it. It's very noticeable around the lower area of sprite where the legs are during motion.

Actually @blade7seven is the artist for this animation i just packed it into sprite sheet. So your suggestion is to actually use motion blur when rendering the animation. We'll try it out.

We set the limit for textures to 8K and I tried running it on my Android phone and that went well, so there should be no problem with the texture size for modern devices.

**Comment by dark-elf1** [comment]
> I tried a couple of things.
> 
>     * First to note the texture size is huge (6480 x 6480). Just be aware that a lot of GPUs may not cope with this well. I tried scaling down the texture x 4 but was still seeing something in the legs.
> 
>     * I noticed the thread mode was set to multithread, I would go for single safe unless there is a particular reason not to (multithread just isn't as tested, and could introduce problems itself).
> 
>     * I changed the parent node from `KinematicBody` to `Node2D` to eliminate physics as influencing.
> 
> 
> I was getting tearing even with vsync on my PC, whether that is contributing I don't know.
> 
> But I suspect this thing you are describing may not actually be the engine, it could just be the 2D artwork is not hiding motion jitter (i.e. you are effectively using stop frame animation), and it is being exacerbated when the whole body is in motion. Motion blur is typically used to hide this kind of thing afaik, so if you are pre rendering, maybe you can do this with motion blur. I can't be sure of course, but I'm aware technical artists spend a lot of time perfecting this kind of thing.
> 
> For 3D versions of this, animation players / and or physics interpolation can tween between rotations which tends to hide this kind of thing.
> 
> This is all assuming we are talking about the same "jitter". There's lots of things that are considered jitter in games / engines.


Edit: may I trouble you to try this one also with different sprites since it seems that shaking is still happening?
[jitter_issue.zip](https://github.com/godotengine/godot/files/12216326/jitter_issue.zip)

**Comment by lawnjelly** [comment]
> And if the camera follows player then the shaking does not happen.

> Also just found out that If the sprite is not flipped when going backwards it seems smooth to me

This is all consistent with it being a visual effect from the brain noticing that there is too much movement of the leg without motion blur. When the player is moving right relative to the camera, the leg moves a relatively large distance each animation frame. When the camera matches the player movement, it is the same as the player being on the spot, there is less relative movement.

When the player walks in reverse, the movement of the legs is compensating for the backward movement of the player.

The brain / eye is very good at noticing things like this that are "wrong", especially when motion is involved. You have to give the brain what it expects to see, or try to fool it in some way. Low resolutions hide this kind of thing, but high resolution stop frame motion is very unforgiving.

It would be interesting to try the same experiment in another engine. If this hypothesis is correct you'll see the same issue.

**Comment by dark-elf1** [comment]
> > And if the camera follows player then the shaking does not happen.
> 
> > Also just found out that If the sprite is not flipped when going backwards it seems smooth to me
> 
> This is all consistent with it being a visual effect from the brain noticing that there is too much movement of the leg without motion blur. When the player is moving right relative to the camera, the leg moves a relatively large distance each animation frame. When the camera matches the player movement, it is the same as the player being on the spot, there is less relative movement.
> 
> When the player walks in reverse, the movement of the legs is compensating for the backward movement of the player.
> 
> The brain / eye is very good at noticing things like this that are "wrong", especially when motion is involved. You have to give the brain what it expects to see, or try to fool it in some way. Low resolutions hide this kind of thing, but high resolution stop frame motion is very unforgiving.
> 
> It would be interesting to try the same experiment in another engine. If this hypothesis is correct you'll see the same issue.
> 
> There is also some tearing going on for me. I'm not sure why this is happening with vsync, it could be my setup with dual monitors.

Interesting! We'll also try with lower resolution sprites. Thanks for the suggestion.

Now that you mention it, I also have dual monitors but I'm not sure If I see any screen tearing..

**Comment by lawnjelly** [comment]
Closing as I don't think there is anything actionable from our side currently.
If anything comes up suggesting an engine bug, just post and we can reopen. :+1:
