### ISSUE TITLE
On start, screen does not redraw after Xmonad resizes.

### ISSUE THREAD

**Issue by tm-nihonsuki** [godotengine/godot#8008]
**Operating system or device - Godot version:**
Editor running on Linux (Arch or Ubuntu) in the Xmonad tiling window manager.

**Issue description:**

When the editor is launched in Xmonad, a tiling window manager, the screen is drawn small even though the workspace is increased to fill available screen area.  Moving the window, or changing the tiling configuration causes a redraw and all is well.  The editor (or project manager) responds to mouse clicks on the new size, not on the drawn size.  Clearly, all that is needed is a later (repeat?) redraw, but I wouldn't know where to look in the code.

**Steps to reproduce:**
Launch the editor in Xmonad tiling window manager (maybe other tilers also problematic?)

**Link to minimal example project:**

n/a

**Comment by william01110111** [comment]
This bug also happens in sway window manager, and presumably i3.

**Comment by jmf** [comment]
I can confirm that for i3wm.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by wmww** [comment]
I can not reproduce on i3 gaps with Godot v3.0.2 stable on Ubuntu. Id say its likely fixed.

**Comment by kubecz3k** [comment]
Thank you @wmww ! Closing as stated in above comment
