### ISSUE TITLE
RPC Config is not properly inherited when a script is loaded

### ISSUE THREAD

**Issue by Dragoncraft89** [godotengine/godot#80087]
### Godot version

3fa8fad

### System information

Debian Linux x86

### Issue description

#79205 introduces a regression to the way rpc configs are inherited, causing this error:

```
ERROR: Unable to get the RPC configuration for the function "foo" at path: "/root/Node". This happens when the method is missing or not marked for RPCs in the local script.
```

even though the function exists both in the server and the client. If you `print(self.foo)`, it even tells you that it's rpc: `Node(client.gd)::foo (rpc)` 

Before #79205 `GdScriptCompiler::_populate_class_members` used `GDScriptCache::get_full_script` to access the base script. This causes the parent script to be compiled (if it is not compiled yet), which in turn initializes the `rpc_config` property with a copy of the base value in [gdscript.cpp::_init_rpc_methods_properties](https://github.com/godotengine/godot/blob/3fa8fad26b97a8af20e7996b7e17d8f23fc04b89/modules/gdscript/gdscript.cpp#L1398-L1412)

However, `GDScriptCache::get_shallow_script` does not compile and thus does not initialize the `rpc_config` of the base script, causing the rpc functions not being included in the rpc config.

### Steps to reproduce

Extend a gdscript with a `@rpc` function annotation and try to do a network call:

server.gd:
```gdscript
extends Node

func _ready():
	var peer := ENetMultiplayerPeer.new()
	peer.create_server(1337)
	multiplayer.multiplayer_peer = peer

@rpc("any_peer") func foo():
	print("Server")
```

parent.gd:
```gdscript
extends Node

@rpc func foo(): pass
```

client.gd:
```gdscript
extends "parent.gd"

func _ready():
	var peer := ENetMultiplayerPeer.new()
	peer.create_client("localhost", 1337)
	multiplayer.connected_to_server.connect(func (): self.foo.rpc_id(1))
	multiplayer.multiplayer_peer = peer
```

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12215814/test.zip)

**Comment by Sauermann** [comment]
CC @anvilfolk

**Comment by anvilfolk** [comment]
I knew there had to be some regressions with _something_ :) I'll try to take a look sometime soon, but don't let that stop anyone else from trying!

Really good report @Dragoncraft89!

Now the question is how hard is it going to be to get this to work without force-compiling the dependency, which is what led to the other serious bug 🤔

**Comment by marcol1** [comment]
OP, could your issue possibly be related to mine? Here's mine: https://github.com/godotengine/godot/issues/80087.

In my bug, the nodes facing the issue are being instantiated using preload(). I'm wondering if it could be caused by the same problem. Only thing is I'm not sure if we're running the same version of Godot since I don't know what the PR version corresponds to.

**Comment by anvilfolk** [comment]
I'm coming up on a little more free time so I hope to take a look at this relatively soon! They do sound very related, and it's possible fixing this one will fix that one, so we can try that first :) Thanks for linking the issues!

**Comment by Dragoncraft89** [comment]
@marcol1 I just tested version 4.1.1 and my issue does not occur in that release. Therefore it seems the linked PR hasn't made it to that release.

It seems that you experience a different issue. Would you mind uploading a minimal example project to your issue? I'm having trouble to recreate your issue from the description alone and I would take a look if I have something to test :)

**Comment by marcol1** [comment]
@Dragoncraft89 Sure, I'll make one when I get the chance and ping you once I upload it.
