### ISSUE TITLE
Getting errors and warnings when using SkeletonModificationStack2D with SkeletonModification2DLookAt

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#80080]
### Godot version

4.2

### System information

MacBook Air with m1 latest update

### Issue description

I am getting a lot of errors and warnings when using SkeletonModificationStack2D.

At runtime:

`W 0:00:00:0537   set_bone_index: Cannot verify the bone index for this modification...
  <C++ Source>   scene/resources/skeleton_modification_2d_lookat.cpp:255 @ set_bone_index()
`
`E 0:00:00:0537   update_bone2d_cache: Cannot update Bone2D cache: modification is not properly setup!
  <C++ Source>   scene/resources/skeleton_modification_2d_lookat.cpp:199 @ update_bone2d_cache()
`
`E 0:00:00:0537   update_target_cache: Cannot update target cache: modification is not properly setup!
  <C++ Source>   scene/resources/skeleton_modification_2d_lookat.cpp:264 @ update_target_cache()
`

At load time, when I load the scene in the editor:

`scene/resources/skeleton_modification_2d_lookat.cpp:255 - Cannot verify the bone index for this modification...`
`scene/main/node.h:412 - Condition "!data.tree" is true. Returning: nullptr`

### Steps to reproduce

Simply create a scene with a Skeleton2D node and 2 Bone2D nodes. Add a SkeletonModificationStack2D to the Skeleton2D node and add a SkeletonModification2DLookAt node to it. For bone_2d_path put the first bone and for target_nodepath put the second bone.

### Minimal reproduction project

[SkeletonModificationStack2D issue.zip](https://github.com/godotengine/godot/files/12212633/SkeletonModificationStack2D.issue.zip)

**Comment by Ughuuu** [comment]
Yes, sorry for opening.

**Comment by AThousandShips** [comment]
No problems, thank you for reporting
