### ISSUE TITLE
TextureButton and Custom Theme Button Displaying on Pressed Action the custom Focused Atlas Texture 

### ISSUE THREAD

**Issue by kamyabnazari** [godotengine/godot#80110]
### Godot version

4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.5.0 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

The TextureButton and even Custom Theme custom buttons with textures for focused, normal, hover, pressed state, behaves wrong when pressed action is triggered. The button with a Focused Custom atlas texture and a Pressed Atlas Texture displays the Focused Texture on Click and not the pressed atlas texture, but it retains its margins and size, as such the button  texture will even be stretched on click. I have also uploaded an example project for this issue. The problem has been tested on all 3 rendering modes and is the same on all. 

### Steps to reproduce

1. Create a new Godot 4.1.1 project on any rendering mode
2. Create a control node (scene)
3. Create textureButton node
4. Add your pressed, focused, hover, and normal buttons texture as Atlas textures to the textureButton node
5. Duplicate the button
6. Start the game and try out Tab (The focus works on changing the two buttons)
7. Now pressed the button --> Texture should now still be the focus texture

### Minimal reproduction project

[example-button-pressed-bug-project.zip](https://github.com/godotengine/godot/files/12226570/example-button-pressed-bug-project.zip)

**Comment by AThousandShips** [comment]
This is by design, see the [documentation](https://docs.godotengine.org/en/stable/classes/class_texturebutton.html#class-texturebutton-property-texture-focused), the texture has to be transparent

**Comment by kamyabnazari** [comment]
Thank you for your explanation, so when there is this case, it is almost impossible to display if the content of the button is focused correct ? so it should be the whole button texture that has to be designed around ? here is an example after your message I have created.

Focused:
![button-focused](https://github.com/godotengine/godot/assets/32940190/ab5ffad5-a5a8-47f5-9604-32f954999bff)

Pressed:
![button-focused-pressed](https://github.com/godotengine/godot/assets/32940190/60b7427c-839e-4b9a-93d9-b52e20218af8)

**Comment by AThousandShips** [comment]
The way `TextureButton` works unfortunately doesn't support the kind of button design you want here, they work for buttons that use a top-down design, you can achieve a lot of this with custom button usage though, but it'll be a bit more complicated

The reason for this change is to simplify the number of textures, having five different textures is already quite a lot, having to juggle more combinations would make for a lot of extra work, when for most users the method of drawing focused over the rest is more than sufficient

Feel free to open a [proposal](https://github.com/godotengine/godot-proposals) for new designs or ideas for this, but remember to fill out everything, and also keep in mind that the current usage has to be retained

**Comment by AThousandShips** [comment]
You can achieve your own design by extending from `Button` (I think `BaseButton` is inaccessible to extend from atm) and doing your own drawing using [`get_draw_mode`](https://docs.godotengine.org/en/stable/classes/class_basebutton.html#class-basebutton-method-get-draw-mode) together with the [`has_focus` ](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-has-focus) method

**Comment by kamyabnazari** [comment]
@AThousandShips Thank you for the clarification, I will probably create a proposal for this, because I think, just for the focused texture to have the ability to change the margin H value  on pressed would make it possible to have custom focused textures on different part of the content of the buttons. Here is an example I have created. A margin normal and margin pressed. 

The code:
![Screenshot 2023-08-01 at 12 26 37](https://github.com/godotengine/godot/assets/32940190/d1d05cee-d514-4ada-a63c-6db6ca9cbd93)


The focused button - Atlas texture - Margin height 15:
![Screenshot 2023-08-01 at 12 27 00](https://github.com/godotengine/godot/assets/32940190/3af23e5e-443e-4053-8538-5b8d15ed0a90)


The pressed button - Atlas texture - Margin height 5:
![Screenshot 2023-08-01 at 12 27 06](https://github.com/godotengine/godot/assets/32940190/7996abb8-b334-4451-82a3-c3701c72f32d)

**Comment by AThousandShips** [comment]
Note that the fact that this can be done so easily is a strong reason to not add it as a feature to the engine, and remember to add your code to your proposal if you make one as a workaround

**Comment by kamyabnazari** [comment]
You may actually be right regarding that, I have found at least a solution to my problem thanks to you, thank you for the clarification that this was not a bug. I will close this issue for that reason 😆
