### ISSUE TITLE
AnimationTree: animation_started signal is always emitted twice

### ISSUE THREAD

**Issue by Coxcopi** [godotengine/godot#80118]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 Threads)

### Issue description

When connecting the `animation_started` signal from an animation tree, the connected method is always called twice.
This only occurs with the `animation_started` signal, the `animation_finished` signal is only emitted once.

This unfortunately makes relying on the signal impossible.

### Steps to reproduce

(See minimal production project)
- Use `animation_started.connect()`
- Print something out in the connected method (the example project prints the `anim_name` parameter)
- method is called twice -> two prints in the console

### Minimal reproduction project

[anim_tree_signal_bug.zip](https://github.com/godotengine/godot/files/12229864/anim_tree_signal_bug.zip)

The animation tree travels to the 'move' animation when `ui_accept` is pressed (see `anim_tree.gd`) and has print statements inside the methods connected to both the `animation_started` and `animation_finished` signal.

**Comment by abmarnie** [comment]
I am still experiencing this in v4.2.0.stable.mono. If someone else would like to double check (or make an MRP for me 😄), that would be nice.

**Comment by krumplespiff** [comment]
> I am still experiencing this in v4.2.0.stable.mono. If someone else would like to double check (or make an MRP for me 😄), that would be nice.

I can confirm I am having this issue in 4.2.1 stable. Very annoying because now I need to move every single signal emit and method call to my input commands (redundant) instead of having it linked to the animations

**Comment by CrayolaEater** [comment]
me too

**Comment by valkyrienyanko** [comment]
Where is the new issue for this? I'm still experiencing this on v4.2.1.stable.mono.official [b09f793f5]
(side note: `animation_finished` works just fine)

**Comment by oxeron** [comment]
I confirm I still have the issue in 4.2.2

**Comment by TheSofox** [comment]
Was able to confirm in v4.2.1.stable.official [b09f793f5]
![image](https://github.com/godotengine/godot/assets/3089525/38020c05-9f32-4a8e-9494-4836be2d8cd9)

But when trying in latest ( v4.3.beta.custom_build [25ff1306d] ) it doesn't seem present:
![image](https://github.com/godotengine/godot/assets/3089525/a966c9af-acdb-4f09-bbd7-54b3725abf55)
