### ISSUE TITLE
When connecting a signal from an autoload in a @tool script, this signal is triggered twice

### ISSUE THREAD

**Issue by TheRealSlander** [godotengine/godot#80128]
### Godot version

4.2.dev1

### System information

Manjaro Linux (DE: Cinnamon v5.8.4) 64 bits

### Issue description

In a project I use an autoload for my signals and I also have some tools that use this autoload for the signals.

The problem is that when a signal is emitted, the tools receive it twice...

I provide a MRP below, I don't know if this is intended, I just wanted to pop that out just in case...

### Steps to reproduce

Get the MRP below, and once the project is loaded into Godot, go to the "Double_Signals" button next to the "AssetLib" one in the center view of the editor. There, click on the button with the Output panel opened.

### Minimal reproduction project

A simple project only containing an autoload and a tool :
[MRP.zip](https://github.com/godotengine/godot/files/12232514/MRP.zip)

**Comment by TheRealSlander** [comment]
Well... It seems that deleting the **.godot** folder makes this MRP useless as the problem does not arise anymore... While it was in the archive, the problem was there... But since I removed the **.godot** folder from the archive, the signals work as expected...

**Comment by kleonc** [comment]
The signal is emitted once. When you think it is emitted twice what happens is there are two instances of the `addon_panel.gd` script running, and both of them are connected to that signal. And this is indeed the case when:
- the addon is enabled,
- and the `addon_panel.tscn` is opened.
E.g. closing the `addon_panel.tscn` tab will make only the in-addon instance be left and hence only one method will be left connected to the signal.

I don't see a bug in here, hence closing.

**Comment by TheRealSlander** [comment]
Yeah, all is clear now indeed. My bad, I'm so sorry for the misunderstanding.
