### ISSUE TITLE
A string from the standard input is incorrectly compared with another

### ISSUE THREAD

**Issue by comminux** [godotengine/godot#80136]
### Godot version

v4.1.1.rc.custom_build.e709ad4d6

### System information

Arch Linux x86_64

### Issue description

The following condition will never be true, even if the user enters the value of another string correctly.

```
func _process(delta):
	print(OS.read_string_from_stdin() == "test")
```

### Steps to reproduce

1. Export the minimal reproduction project in zip or pack file.
2. "godot --main-pack stdin-exported.zip"
3. Enter the word "test" into the console and press enter.

### Minimal reproduction project

[stdin-mrp.zip](https://github.com/godotengine/godot/files/12233739/stdin-mrp.zip)

**Comment by AThousandShips** [comment]
Have you tried if it matches "test\n"?

**Comment by comminux** [comment]
"test\n" is also not true

**Comment by AThousandShips** [comment]
Can confirm that it does include a linebreak, and the actual line is "test\r\n", you need to strip the newlines

**Comment by comminux** [comment]
I read the description of the pull request for this method and figured out my problem. You need to use OS.read_string_from_stdin().strip_edges() and then string comparison will be correct.

I think it will be enough to leave a mention in the documentation for the strip_edges method for OS.read_string_from_stdin()

**Comment by AThousandShips** [comment]
As I was saying, you didn't need to figure it out yourself 🙃

**Comment by comminux** [comment]
After Godot 4.4 dev 5 stdin handling will work via OS.read_string_from_stdin(1024).strip_edges()
