### ISSUE TITLE
Changing the locale breaks remapped fonts

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#80130]
### Godot version

4.1.stable.official

### System information

Arch Linux

### Issue description

I'm porting part of an old project that uses remapped font resources over to Godot 4. When the locale is changed, these fonts break, and an error is logged.

In the minimal project I've attached the error looks like:

```
E 0:00:00:0730   main.gd:4 @ _ready(): Condition "!font_owner.get_or_null(p_fonts[i])" is true. Returning: false
  <C++ Source>   modules/text_server_adv/text_server_adv.cpp:4031 @ _shaped_text_add_string()
  <Stack Trace>  main.gd:4 @ _ready()
```

In my full project I get many many errors that look like this (but I think the cause is the same):

```
E 0:00:05:0248   _font_draw_glyph: Condition "!fd" is true.
  <C++ Source>   modules/text_server_adv/text_server_adv.cpp:3370 @ _font_draw_glyph()
```

I remap the font resources to change the font that gets used when playing in Chinese, Japanese, or Korean. (Setting CJK fonts as fallbacks would be suboptimal, since the same unicode code point can often look different in Japanese vs Simplified Chinese.)

### Steps to reproduce

1. Download the attached minimal reproduction project.
2. Run the `main.tscn` scene.
3. Note that the text of the `RichTextLabel` node does not display.
4. Note the error that gets logged.

### Minimal reproduction project

[godot4-font-remap.zip](https://github.com/godotengine/godot/files/12232624/godot4-font-remap.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/69431.

**Comment by akien-mga** [comment]
Confirmed reproducible in 4.2-beta5. CC @bruvzg
