### ISSUE TITLE
Can't focus plane translation handle of 3D gizmo in some cases/angles

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#80139]
### Godot version

v4.2.dev2.official [da81ca62a] (Applys to the whole 4.x branch)

### System information

Godot v4.2.dev2 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When trying to make a plane translation (moving an object along multiple axis at once with the 3D transform gizmo) in the 3D editor, the boxes that trigger a plane translation are hard/ impossible to click on.

For reference; Blenders Gizmo handles this fine even on tight angles

I made this small video to further explain the issue. The first few examples may be not an issue (but they are a bit on the edge of being one), but the last few make the part of the gizmo unusable.

https://github.com/godotengine/godot/assets/111653551/2a06afec-2016-440d-b615-5f19131d784f

### Steps to reproduce

1) Create a 3D scene
2) Add any 3D Node that comes with a gizmo (for example a MeshInstance3D)
3) Try to make a planar translation on the before added Node (This works fine if the angle is right)

### Minimal reproduction project

[Gizmo Issues.zip](https://github.com/godotengine/godot/files/12234167/Gizmo.Issues.zip)

**Comment by fire** [comment]
@TokageItLab any ideas?

**Comment by TokageItLab** [comment]
I remember that the priority of these focuses was dependent on the raycast, but that invisible margin may be too large. It may be necessary to separate the invisible margin from the actual object and give priority to each individually. cc @JFonS

**Comment by xxSeys1** [comment]
Was this fixed? Because using 4.2.beta4 I feel like I no longer have the issue or it has gotten better.

I tested some of the issues I showed in the video and some of them seem completely fixed, some partially.

**Comment by TokageItLab** [comment]
Maybe related by https://github.com/godotengine/godot/pull/56946.
