### ISSUE TITLE
Nearest texture filtering not working

### ISSUE THREAD

**Issue by blitpxl** [godotengine/godot#80147]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11, Vulkan, RTX 2060 (31.0.15.2824)

### Issue description

For some reason, setting the default texture filter in `rendering/textures/canvas_textures/` doesn't do anything.

I want to apply a low res texture (128x128) hoping it will look sharp

![grass](https://github.com/godotengine/godot/assets/72286622/ac90277e-0afc-4538-a4b7-b661eba5651e)

Instead, I got a blurry mess that I suppose is caused by the texture filter

![image](https://github.com/godotengine/godot/assets/72286622/ea319ad0-3514-4452-9699-bd362a0d5ba4)

### Steps to reproduce

1. go to `rendering/textures/canvas_textures/` and set the default texture filter to "Nearest"
2. apply a low res texture (in my case 128x128) to a CSGBox3D

### Minimal reproduction project

N/A

**Comment by saierXP** [comment]
This is not a bug.
![godot-fixed-nested-4 2-new_nt03ahtzqG](https://github.com/godotengine/godot/assets/45038185/679442ba-7693-4e96-abca-c4fb87eb736e)
![godot-fixed-nested-4 2-new_u0o2vQTiFs](https://github.com/godotengine/godot/assets/45038185/bfb9de11-50bb-42c4-beb8-79aee9dce9f1)

See more:
* [Add a Default Texture Filter project setting for BaseMaterial3D, SpriteBase3D and Label3D #5228](https://github.com/godotengine/godot-proposals/issues/5228)

**Comment by blitpxl** [comment]
That was it! somehow it never occurred to me to look into the Sampling part of the texture. Thanks!
