### ISSUE TITLE
Accessing to the signal of the Control class reports an error.

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#80157]
### Godot version

4.2 (c5da2e54fe50cad34b5f93fa10538978b33af88d)

### System information

Windows 11

### Issue description

Attempting to run a scene with the following script report Identifier not found error:

![image](https://github.com/godotengine/godot/assets/3036176/3a63b930-0588-499d-80a2-4f88f5f07116)

This does not happen on 4.1.1 so this is a regression.

### Steps to reproduce

Create a script derived from Control and try to get access to the mouse_entered signal.

### Minimal reproduction project

[TestBug.zip](https://github.com/godotengine/godot/files/12237764/TestBug.zip)

**Comment by akien-mga** [comment]
Just came back from holidays so I haven't reviewed all merged PRs from July yet, but sounds related to #67791 ? @Sauermann

**Comment by dalexeev** [comment]
* Probably a regression from #79880.
