### ISSUE TITLE
Godot loads only one core and hangs

### ISSUE THREAD

**Issue by jdafij12** [godotengine/godot#80169]
### Godot version

4.1

### System information

Pop_OS!, NVIDIA GeForce RTX 3050 Ti, AMD Ryzen 5 5600H

### Issue description

As already written in the title, Godot loads only one core to 100% before hanging ( cores can vary ). Also after a hang, Godot outputs the following:

drivers/vulkan/vulkan_context.cpp:1970 - Condition "err" is true. Returning: ERR_CANT_CREATE
drivers/vulkan/vulkan_context.cpp:1698 - Condition "err != OK" is true. Returning: ERR_CANT_CREATE
Can't create a Vulkan window
platform/linuxbsd/x11/display_server_x11.cpp:2453 - Condition "!windows.has(p_window)" is true.
platform/linuxbsd/x11/display_server_x11.cpp:2453 - Condition "!windows.has(p_window)" is true.
scene/main/window.cpp:566 - Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.

CPU load ( https://imgur.com/a/MdcdKKg )

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by Calinou** [comment]
> Godot loads only one core to 100%

Loading is mostly single-threaded, so this is expected.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
