### ISSUE TITLE
[3.x] Clicking on script in scene tree in editor takes you to 3D view instead of the script

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#80179]
### Godot version

v3.6.beta.custom_build [d5a56f023] (bug introduced today 2 Aug 2023)

### System information

All

### Issue description

Open editor for a scene, click on a script in the tree view. It takes you to 3D window instead of the script.

### Steps to reproduce

As above.

### Minimal reproduction project

N/A.

**Comment by lawnjelly** [comment]
Looks like a regression from #79947 .

**Comment by akien-mga** [comment]
Fixed by #80197.
