### ISSUE TITLE
Godot4 steals focus while moving other windows under i3

### ISSUE THREAD

**Issue by unlessgames** [godotengine/godot#80170]
### Godot version

4.1 stable

### System information

Arch Linux with i3 window manager

### Issue description

Under the i3 window manager on Linux, Godot 4 grabs the focus while moving other windows over it, this breaks the workflow on i3 (and possibly other tiling window managers like it) in an rather annoying way.

Below is a clip where the window on the left is moved towards the right over a godot window with the keyboard (Win+Shift+Right by default). 

https://github.com/godotengine/godot/assets/38718816/8de8cad2-07de-4264-84c3-112681c61f2a

First one (green) is with Godot 3 which works as expected, the second one (red) is with Godot 4 where I start moving a window I want and Godot steals the focus mid-way and becomes the moved window itself.

Most likely related to #74378

### Steps to reproduce

Use i3-wm and try to move something around a Godot4 window with keyboard.

### Minimal reproduction project

Project content doesn't matter.

**Comment by Calinou** [comment]
Thanks for the repport! Consolidating with https://github.com/godotengine/godot/issues/68305, https://github.com/godotengine/godot/issues/74378 and other related issues.

**Comment by ckdarby** [comment]
Will close as I have left my comment that it is still an issue [in the main issue.](https://github.com/godotengine/godot/issues/68305#issuecomment-2326894344)
