### ISSUE TITLE
Calls to RenderingServer.global_shader_parameter_get* functions aren't working; unclear what the intended method to get the value of a global shader parameter in code is

### ISSUE THREAD

**Issue by Zorochase** [godotengine/godot#80180]
### Godot version

4.2.dev2.mono

### System information

Godot v4.2.dev2.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 with Max-Q Design (NVIDIA; 30.0.15.1179) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

RenderingServer.global_shader_parameter_get* functions and their C# counterparts produce the error "this function should never be used outside the editor, it can severely damage performance" when called, even when running the project from the editor. I have not tested an exported build, but I assume these functions are not supposed to work outside editor builds. However, I'm not sure what, then, the proper way to get the value of a global shader uniform through code would be. I've tried using ProjectSettings.get_setting, but it seems that's just to get the initial value stored in the menu.

### Steps to reproduce

Try calling RenderingServer.global_shader_parameter_get[_list/_type] in GDScript or its counterpart in C# and run the project. Notice that, if you try to print the return values of these methods, nothing will be printed.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Its intended to be a one-way relationship. You are responsible for setting the value and for storing the value that you set. This goes the same for any interaction you have directly with a server in Godot. You are free to push information to the server whenever you want, but you should never request data back from a server. If you do, you will pay a steep performance penalty.

**Comment by Zorochase** [comment]
> Its intended to be a one-way relationship. You are responsible for setting the value and for storing the value that you set. This goes the same for any interaction you have directly with a server in Godot. You are free to push information to the server whenever you want, but you should never request data back from a server. If you do, you will pay a steep performance penalty.

I apologize, I have little experience working with Godot servers so I assumed `get` would work without issue as `set` does and forgot to double-check the docs. It might be a good idea to warn users in the docs of the `set` function about this relationship, incase they too are unaware of it. Thank you for your clarification.
