### ISSUE TITLE
Unsupported Xinerama library version on Linux, Nvidia card with 2 monitors NOT running Twinview

### ISSUE THREAD

**Issue by blaskey** [godotengine/godot#80194]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Linux Gentoo Nvidia GeForce GTX 1660 SUPER

### Issue description

When I try to start Godot 4.1.1 I get:
```
Xlib:  extension "XINERAMA" missing on display ":0".
ERROR: Unsupported Xinerama library version.
   at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5527)
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:2216)
```

My config is a single Nvidia card with two identical monitors. I run in a non-twinview mode which is essentially like two video cards and two screens run independently of each other (no moving windows between monitors). I've run this setup for years.  xorg.conf is attached. I CAN run Godot 3.5.2 (though I see errors in the output like 'ERROR: Index p_screen = 0 is out of bounds (get_screen_count() = 0).')

My guess is Godot is seeing two screens and automatically requiring xinerama to be present. AFAIK xinerama should not be enabled on Nvidia multi-monitor setups. Another clue is if I enable xinerama in the xorg.conf (Nvidia warns me this is a really bad idea and that randr is now disabled in the xorg.logs) I get something like ``` extension RandR missing on display ":0"```

[xorg.conf.txt](https://github.com/godotengine/godot/files/12245470/xorg.conf.txt)

### Steps to reproduce

Execute Godot_v4.1.1-stable_linux.x86_64 which was downloaded from the Godot site.

### Minimal reproduction project

Can't start Godot, so project is not involved.

**Comment by Calinou** [comment]
> I've run this setup for years. 

Out of curiosity, why not use TwinView?

**Comment by blaskey** [comment]
> > I've run this setup for years.
> 
> Out of curiosity, why not use TwinView?

It's been a while since I tried it, but when I did, lots of apps didn't behave. I'd constantly get popups split between screens. Certain games would try to stretch across both monitors when fullscreen.

**Comment by Calinou** [comment]
> Certain games would try to stretch across both monitors when fullscreen.

In my experience, this is only really a thing with SDL1 games, and using sdl2-compat on those might fix it.

**Comment by bruvzg** [comment]
Xinerama is only used for getting screen count / rects, so we should be able to make it optional and fallback to X screen info.
