### ISSUE TITLE
Can't set TreeItem check status

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#80196]
### Godot version

v4.1.dev2.official [668cf3c66]

### System information

Windows 10, 64bit

### Issue description

I want set `TreeItem`'s check status recursive with this code:
![image](https://github.com/godotengine/godot/assets/35988767/f10009cf-44fd-411b-ab03-61008a4a7cd5)
But when the  `TreeItem` no children, it can't change check status:
![GIF](https://github.com/godotengine/godot/assets/35988767/2452a941-fc51-4938-98a0-55c5d0a826ef)

### Steps to reproduce

/

### Minimal reproduction project

[TreeTest.zip](https://github.com/godotengine/godot/files/12246012/TreeTest.zip)

**Comment by timothyqiu** [comment]
I believe your code on line 26 should be `i.set_checked` instead of `item.set_checked` :stuck_out_tongue:
