### ISSUE TITLE
The name of the scenes in the tab sometimes shows its path?.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#80207]
### Godot version

v3.6.beta2.official [68c507f59]

### System information

w10 64

### Issue description

What the title says, I think only the .tscn scene name should be displayed.
Why does the route also appear in some tabs?.

![image2](https://github.com/godotengine/godot/assets/19652075/e5c7dc2b-c26a-4ecd-848d-6ea10d18a1d8)

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Torguen** [comment]
Ok, I think that happens because the scenes are called the same, so to differentiate "Frame1" from "Frame1" the path is used.

**Comment by Calinou** [comment]
Indeed, this is done by design to disambiguate between identically named scenes. This only occurs if more than one tab has the same scene name.
