### ISSUE TITLE
OptionButton Item Shortcut is broken

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#80201]
### Godot version

4.1.1-stable

### System information

Windows 10

### Issue description

OptionButton items shortcut is not working

**Comment by WhalesState** [comment]
I already have fixed and tested it, will open a pull request soon

**Comment by dalexeev** [comment]
@WhalesState Please follow the issue template, do not remove sections, especially "Steps to reproduce". Describe the issue in more detail so that other contributors can reproduce it. If the MRP is not needed, just type "N/A" as the field description says. Thanks!

**Comment by WhalesState** [comment]
@dalexeev, thank you, this issue was added twice before and closed with no replies or fixes, simply when you assign a shortcut to an OptionButton menu item it doesn't work, to produce the issue just assign a shortcut to OptionButton item and it won't work, i have made it simple to not waste anyone's time since i already have fixed it before opening the issue, thank you ^^
