### ISSUE TITLE
CylinderShape3D CharacterBody3D gets stuck on edges of ConcavePolygonShape3D colliders

### ISSUE THREAD

**Issue by wjagodfrey** [godotengine/godot#80202]
### Godot version

4.1.1-mono

### System information

MacOS 12.3

### Issue description

When strafing past and against the edges of a `ConcavePolygonShape3D` body, a `CharacterBody3D` with a cylinder collider gets stuck.

### Steps to reproduce

1. Clone the repro repo.
1. Run it.
1. Strafe past the edges of the cube on the left.

### Minimal reproduction project

Repro repo is [here](https://github.com/wjagodfrey/godot-4-1-1-cylinder-collider-edge-issue).

**[EDIT]** Notably the issue doesn't exist when using Jolt Physics.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/57476.
