### ISSUE TITLE
Crash after change the dynamic font size by a mouse click+dragging 

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#8021]
**Operating system or device - Godot version:**
Xubuntu 16.04.2 LTS x86_64, **Godot version**: master 52ddd9a, 2.1 branch 8ea4413, 2.1.1-2.1.2 stable
**Issue description:**

Godot crash when change a dynamic font size by a mouse click+dragging.
Some time a size value has changed to a negative value, like: -2500 or lower.
![godot_dyn_font_size_crash](https://cloud.githubusercontent.com/assets/1049442/23869275/8c0116e2-084c-11e7-8bc9-5e2d55e3f19f.gif)
[godot_backtrace.txt](https://github.com/godotengine/godot/files/839273/godot_backtrace.txt)

**Steps to reproduce:**
1) Add a node with a font support like a btn or label.
2) New DynamicFont.
3) Enter inside(edit it).
4) Font --> New DynamicFontData or Load some font.  Without this step godot work correct.
5) Try to change font size by a mouse click+dragging, up - down, several times.
6) Crash.

**Link to minimal example project:**

[bug_test.zip](https://github.com/godotengine/godot/files/839303/bug_test.zip)

**Comment by bojidar-bg** [comment]
Could confirm once (with some difficulty), but not when running inside `gdb`. Process was terminated by `SIGSEGV` (Arch linux, Godot 15c4d5006ee6982223777ababfbc2c040f3e344f)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by allkhor** [comment]
Reproducible in 2.1.5 a524cc9, not reproducible in stable 3.0.2, not reproducible in master a7f6e09.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
