### ISSUE TITLE
MacOS notarization (export step 4) should use notarytool instead of altool

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot#80213]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

MacOS (Ventura 13.5)

### Issue description

While today it's still possible to export to MacOS, at step 4, when the archive is being sent for notarization the following warning is shown:

**Warning: altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)**

I haven't found a GitHub issue mentioning this, and I'm hoping this update will also affect Godot 3.x, as same projects -- mine, for instance -- are stuck on 3.x (Mine cannot be migrated to 4.x, because the migration crashes without any meaningful output, but I believe I'm also using features not supported in 4.x, so it would be nice to keep being able to ship MacOS updates for my 3.x game.)

### Steps to reproduce

Just export a project for MacOS.

### Minimal reproduction project

Irrelevant, affects all projects targeting MacOS.

**Comment by akien-mga** [comment]
Related to https://github.com/godotengine/godot-proposals/discussions/6514 - notarytool support was implemented for 4.0 but not backported yet.

Could you do a backport of #69638 for `3.x`? (And I'd cherry-pick for 3.5.3 as this seems worth pushing an update for.)

**Comment by bruvzg** [comment]
> Could you do a backport of https://github.com/godotengine/godot/pull/69638 for 3.x?

I'll backport it (and App Store distribution related export improvements) tomorrow.

**Comment by lawnjelly** [comment]
Should be fixed by #80239 .
