### ISSUE TITLE
Window Reloading on every click

### ISSUE THREAD

**Issue by Loneliiii** [godotengine/godot#80210]
### Godot version

3.5,4.0,4.1

### System information

Windows 11, Ryzen 7 5000Series, Amd HD Graphics, GTX 1650, Laptop Asus Rog Flow x13

### Issue description

Since a few days, everywhere I click in Godot, doesn't matter what project, in the editor and project screen, it seems like godot is reloading (flashing white) for a second. Even the Logo in the Taskbar is Reloading (like Godot is reopened). (Example in the Video)

What I tried:
- trying other Godot versions: Steam version, standalone 3.5/4.0/4.1
- reinstalling windows,
- geting newest driver and windows updates
- changing from forward+ to mobile and compatible

The weird thing, this only happend with my laptop and Godot. I tried it on a second device (ROG ALLY), but everything works fine on it.

https://github.com/godotengine/godot/assets/141322052/e51d62ff-00fa-427e-bd00-8c9475e38958

### Steps to reproduce

not reproducable

### Minimal reproduction project

not reproducable out of the box

**Comment by Loneliiii** [comment]
I tested a bit. A redditor told me to use the startoption "--rendering-driver opengl3". This does not work. Then I activated "compatability mode: Windows 8" and it works, no more flickering but super worse performance :(

**Comment by Calinou** [comment]
- Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?
- Do you have any third-party applications that may interfere with window managemnt or tooltips, such as shell extensions?

**Comment by Loneliiii** [comment]
Hey Calinou, I couldn't wait any longer and completly reinstall windows with a full wipe of data. Now it works without problems.
I know it would have been nice to know what was causing this. But iw was a bit annoying that I couldn't work on my game.
Can we close this issue?

and no, I didn't install extra shell extensions. The only thing running in the background was "lightshot", "steam" and "amoury crate"

**Comment by RainbowAlpacas** [comment]
I just encountered the exact same problem but I really don't want to reinstall windows and wiping my data. I enabled Single Window Mode in the Editor Settings and it still persist.

https://github.com/user-attachments/assets/a0ed6620-4363-4a89-aa29-07e6bcf7454e

**Comment by ronykax** [comment]
Did you ever find a fix to this @Loneliiii ?

**Comment by ronykax** [comment]
hey @Loneliiii I just updated my windows and its fixed it!!
