### ISSUE TITLE
Distance field fonts are blurry

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8022]
Tested on Godot 2.1.2
Windows 10 64 bits

I created a theme with a custom font, and it looks fine with Labels. However, every other control gets blurry text instead. I expected the same result as the label, because I see the text appears to be the same size.

![image](https://cloud.githubusercontent.com/assets/1311555/23879326/a3386cfc-084c-11e7-954d-40582407fcf3.png)

[ItemListFontBlurry.zip](https://github.com/godotengine/godot/files/839877/ItemListFontBlurry.zip)

Related QA thread I investigated from: https://godotengine.org/qa/13127/itemlist-font-is-scaled-and-blurry

**Comment by eon-s** [comment]
Seems to affect just distance field fonts, by the way.

**Comment by Laseph** [comment]
I've had the same problem. I've looked through the code and although I'm not a programming expert at all, I found this piece of code that can only be found in the label.cpp. This is probably why it doesn't render correctly.
`VisualServer::get_singleton()->canvas_item_set_distance_field_mode(get_canvas_item(), font.is_valid() && font->is_distance_field_hint());`

**Comment by Zylann** [comment]
Well, maybe it's why only the label renders correctly, in fact^^

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment]
Is there a way to create distance field fonts? It do not seem possible on godot 3.

**Comment by Zylann** [comment]
Just try to import the same font as in the example project?

**Comment by Zylann** [comment]
Argh I need to find the original, I believe that one was imported with 2.x

**Comment by Zylann** [comment]
Importing that font in 3.0.2 works:

![image](https://user-images.githubusercontent.com/1311555/38577522-7a9ca67e-3d01-11e8-987a-2096056ab61d.png)

**Comment by eon-s** [comment]
@Zylann how do you managed to import it? (and as .tres)

**Comment by Zylann** [comment]
@eon-s the original is a TTF, I created a DynamicFont from it.

**Comment by eon-s** [comment]
Oh, I was able to replicate only with that font, I will see if I can get one and try again later

**Comment by eon-s** [comment]
This issue is not solved, still valid for distance field fonts,

Example using the font on the SFF demo.
[ItemFontBlurryV3.zip](https://github.com/godotengine/godot/files/1896899/ItemFontBlurryV3.zip)

**Comment by Zylann** [comment]
Bumped again into this after upgrading my game from Godot 2 (where it worked) to Godot 3.0.6 (no longer works), still with the same font.
It should be noted that the difference is not like the first example I posted, and what I thought was working actually isn't. See this comparison:

![image](https://user-images.githubusercontent.com/1311555/47970187-0b004880-e07a-11e8-9439-40b45877a944.png)

**Comment by KoBeWi** [comment]
Still valid in 3.2.3
In 32be929 the font isn't even loaded.

**Comment by filipworksdev** [comment]
I fixed this in my custom build. Took me about 1 day. Works perfectly for GLES2 and GLES3 just like it did in Godot 2. This feature was never properly implemented in 3 and over the years it kinda got moved around bits and pieces everywhere and some lines completely gone. I had to use Godot 2.1 as reference, fix the shaders, touch up some controls, and put all the pieces back together or completely re-implement some sections. I guess I'm 5 years too late nobody really cares about this feature anymore but here it is working in Godot 3.x latest.  
![image](https://user-images.githubusercontent.com/36826319/145559202-c87ad081-cec5-4750-bb13-f9f6f7908a43.png)

**Comment by Zireael07** [comment]
@filipworksdev  Can you make a PR?

**Comment by filipworksdev** [comment]
Hi @Zireael07  I can try but can't guaranteed I'll be approved. It only implements it for some controls. I skipped all the advanced stuff because I don't think they were meant to work with bitmap fonts like a TextEditor for ex. The main issue is I could not make it work for the new  Theme Editor Plugin pewview. It only works when you do a popup but not in the actual theme.  
![image](https://user-images.githubusercontent.com/36826319/145560334-85799800-ba9d-46c5-aa4d-571b1fd4b334.png) .

**Comment by Zireael07** [comment]
I can't guarantee it will be approved either, but as it is a bugfix chances are it will and/or someone will take a look at the other places that need the fix, like the Theme Editor you mentioned,

**Comment by Calinou** [comment]
@filipworksdev If you don't have time to finish this work, could you push your work to a branch so others can improve it and open a pull request based on it? Thanks in advance :slightly_smiling_face:

**Comment by filipworksdev** [comment]
@Calinou  Sorry!  I did push it to a branch but is using my custom build of Godot for educational purpose. I am doing more core changes and more basic work to learn C++. 

This is the commit with all the changes. Is compatible with 3.x branch https://github.com/goblinengine/goblin/commit/66c4f2fbd2e32b1deb8bad9753d96efd01d3d8d8

It works but has a number of issues which need to be addressed.

**Comment by Calinou** [comment]
I ported filipworksdev's changes above to a branch: https://github.com/Calinou/godot/tree/fix-sdf-font-rendering-3.x

**Comment by eon-s** [comment]
It would be great if this could land on 3.5, even as experimental because is a huge improvement.

**Comment by filipworksdev** [comment]
Thanks @Calinou  ! Looks great.  Sorry it says Ghost above I'm still here I had some issues with my old account so I ported everything to a new account same usename and same repots. Still here :) Did you manage to fix the theme preview and I think there are also batching issues.

**Comment by Calinou** [comment]
> Did you manage to fix the theme preview and I think there are also batching issues.

No, as I didn't look into fixing those issues yet (though the batching issue is probably too difficult for me to figure out).

**Comment by akien-mga** [comment]
Thanks!
