### ISSUE TITLE
"Icon" and "Console Wrapper Icon" are swapped when a wrapper icon is specified (Windows)

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#80238]
### Godot version

4.1.1stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

An incredibly minor issue - when exporting with a console wrapper icon specified it gets applied to the wrong one.

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/40964335/d3bc3cd2-6e25-402d-802d-6d87ab142f7f)
![image](https://github.com/godotengine/godot/assets/40964335/4a3e14d5-535e-45ae-88e7-b55c5ea9e46f)
As you can see, the purple godot is the main icon. The gray one is the wrapper icon.
![image](https://github.com/godotengine/godot/assets/40964335/59883a9e-bde1-4094-a4d5-372ee031e936)
Yet when we export, they are flipped.
![image](https://github.com/godotengine/godot/assets/40964335/877ec766-0b5b-4e92-b3c9-50dd05b3be39)
![image](https://github.com/godotengine/godot/assets/40964335/1dcad3c7-b036-40ee-b05d-1f3be4e16341)
They both are the main one when only the main icon is specified.

### Minimal reproduction project

N/A

**Comment by OXTyler** [comment]
I can try to fix this, but since this is my first time working on godot, can someone give a suggestion on where to start looking for the bug?

**Comment by Calinou** [comment]
> I can try to fix this, but since this is my first time working on godot, can someone give a suggestion on where to start looking for the bug?

It's probably around here: https://github.com/godotengine/godot/blob/16a93563bfd3b02ca0a8f6df2026f3a3217f5571/platform/windows/export/export_plugin.cpp#L413-L418

In the future, to find source code matching a location in the editor, search for the string that appears in the editor across the whole codebase :slightly_smiling_face: 
If you don't find anything this way, it's because the displayed name is automatically converted from snake_case. In this case, search for the string in lowercase with spaces replaced with underscores. Here, I searched for `console_wrapper_icon`.

**Comment by OXTyler** [comment]
so I found the issue, and I have a bandaid fix at the moment, so I swapped how the icons are assigned:
![image](https://github.com/godotengine/godot/assets/24878321/4f245dfb-5881-4d8a-8ace-ecab89ba68b8)
vs the original code: 
![image](https://github.com/godotengine/godot/assets/24878321/990bb0cd-4754-431f-8658-61bf376b5384)
this works, it gets the wrapper icon to the right exe, however it doesnt address the real issue of the variables being backwards, im not sure how to address that or if I should care, if its fine as it is I can go ahead and pr, but if now where should I look to fix that?

**Comment by OXTyler** [comment]
ignore last comment, I realized underlying issue and am working on it

**Comment by OXTyler** [comment]
alright it should be fixed, just gotta make a pull request for it
