### ISSUE TITLE
Tips blocks input from keyboard ( Color Picker )

### ISSUE THREAD

**Issue by 908760230** [godotengine/godot#80235]
### Godot version

4.2 dev, 4.1.1

### System information

windows 11 Godot 4.2 dev

### Issue description

![can't input](https://github.com/godotengine/godot/assets/18512367/1b370b82-c72f-4c8b-8f9c-fb2760742396)

### Steps to reproduce

None

### Minimal reproduction project

None

**Comment by Sauermann** [comment]
This is a known issue.
Closing as a duplicate of #73926
