### ISSUE TITLE
3.x Renderer - Ambient Light for Materials?

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8024]
Would be great if we could setup different Ambient Light for materials to blend them with World Env Ambient Light.
Mostly for stylized art style.

**Comment by Llcoolsouder** [comment]
Couldn't you just change the albedo color of the material itself? To my understanding, ambient light is just a multiplier.

**Comment by Calinou** [comment]
@Llcoolsouder Configuring the Emission property could likely achieve what OP wants here, in addition to disabling ambient lighting on a per-material possible (which is now possible as of 3.1).

**Comment by Llcoolsouder** [comment]
@Calinou so both of these things are already implemented in the engine?

**Comment by Calinou** [comment]
@Llcoolsouder Yes, emission has been supported for a long time now, and disabling ambient light was implemented by https://github.com/godotengine/godot/pull/20140. I suppose this issue can be closed :slightly_smiling_face:
