### ISSUE TITLE
Godot 4 running in 5fps randomly

### ISSUE THREAD

**Issue by SwaftStudios** [godotengine/godot#80253]
### Godot version

4.1

### System information

Windows 10 no vulkan support

### Issue description

Hi there,

I've started using godot 4 for the last couple of days but for the last 2 days my godot 4 is running 0 - 5fps it was working with no issues before the last 2 days and it really frustrated me.

I've tried restarting pc, restarting godot and even tried an empty project but whatever I've done it's the same result.

I do not know the reason for this. Thanks

My specs are 

I5-3340 with 4 cores and integrated gpu (4th gen)
500gb hdd

### Steps to reproduce

I've tried restarting godot

### Minimal reproduction project

Do not have a file

**Comment by Calinou** [comment]
Can you reproduce this if you enable **Update Continuously** in the Editor Settings?

**Comment by Magmastorm3007** [comment]
Did you see task manager if there are heavy apps running in background.Do a malwarebyte check.Try using CoreTemp to assess CPU temperature and also is there any performance downgrade in other applications.See if you can downgrade or restore your pc as well.

**Comment by SwaftStudios** [comment]
Hi

**Comment by SwaftStudios** [comment]
Sorry for the late replies,

I've tried everything mentioned above and seen no improvement, my cpu temperatures are very low as you can see in the image attached, it was very random that its running at 5 fps

All other games run absolutely no issues what so ever.

![Snapchat-317236068](https://github.com/godotengine/godot/assets/109307973/b47c9a7d-32ca-41dd-833d-a51e68a423da)

**Comment by Calinou** [comment]
Does this occur after uninstalling RTSS? It tends to cause trouble with Godot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
