### ISSUE TITLE
Error "flush: Trying to execute a deferred call/notification/set on a previously freed instance. Consider using queue_free() instead of free()." On a scene with a Tab

### ISSUE THREAD

**Issue by SerialXComputer** [godotengine/godot#80250]
### Godot version

4.2.dev2

### System information

Windows 11 - Ryzen 7 7640HS - RTX 4060 8GB Mobile- Rendering mode Forward + (Vulkan)

### Issue description

I found a bug with Godot when you try to queue_free() a scene with a tab inside a Tab container the Game Engine return:
 
"flush: Trying to execute a deferred call/notification/set on a previously freed instance. Consider using queue_free() instead of free()."

...https://1drv.ms/u/s!Ap0EQhzVRX9VhepQ_rnOzrl7F-bCTA?e=TI1oYN  ...

### Steps to reproduce

Create a new project, create a scene with a control add a TabContainer add a Tab Node and add a code like this one on the 
Control Node :
extends Control

func _ready():
	queue_free()# Replace with function body.

func _process(delta):
	pass

and run it with and without the Tab Node

...https://1drv.ms/i/s!Ap0EQhzVRX9Vhewi-xHso0-mr2cCkg?e=vOs9YT...

### Minimal reproduction project

[test4.2.zip](https://github.com/godotengine/godot/files/12260223/test4.2.zip)

**Comment by YuriSizov** [comment]
Thanks for your report. This has been addressed already and won't be an issue in dev3.
