### ISSUE TITLE
Collision slowdown/stuck in objects

### ISSUE THREAD

**Issue by IceNineOcean** [godotengine/godot#80268]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

I'm working on an immersive sim type project, and part of that is being able to pick up and throw objects, however, when the objects are near a wall and the play rubs up against the wall while on these objects, collision has a really bad tendency to slow down significantly, or for the player to get stuck entirely (at which point the slowdown seems to stop).

### Steps to reproduce

WASD movement, tab to enable/disable mouse, space to jump, right click to pick up/throw boxes.

Jump around the boxes and walk into the corners formed between the boxes and wall. Boxes can be thrown to create new, more natural angles that would be relevant for real use applications.

### Minimal reproduction project

[BugReproductionProject.zip](https://github.com/godotengine/godot/files/12262996/BugReproductionProject.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/65596.
