### ISSUE TITLE
Fog Depth missing in Godot 4?

### ISSUE THREAD

**Issue by Krasapan** [godotengine/godot#80274]
### Godot version

4.1.1.stable

### System information

Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce MX330 (NVIDIA; 31.0.15.1640) - 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 Threads)

### Issue description

Seems that Fog Depth feature is missing in Godot 4:
![FogParameters](https://github.com/godotengine/godot/assets/50244497/cdafd523-2f1c-4b63-818b-8b1afaa43334)

Why do I need Fog Depth?
To fix such artifacts that occur when anything in the distance is on the same distance as camera's render limit:
![FogDepth2](https://github.com/godotengine/godot/assets/50244497/af33a32c-39a0-4998-958d-3fba283d38a0)

Depth hides that "seam" pretty well.

I tried to hide that seam with Volumetric Fog, but it doesn't work that well as with Fog Depth, it's either don't hide the seam or hides it if I make general volumetric fog density insanely high that significantly obstructs vision

Why was Fog Depth removed?
If yes, then why?
If no, where it was moved?

Any ways I can fix my problem (smoothly hide camera render limit seam) without Godot 3's Fog Depth in Godot 4?

### Steps to reproduce

Download reproduction project (Godot 3.5.1), press arrows Up and Down to move mesh and observe how fog with Fog Depth smoothly reveals mesh in camera's sight

### Minimal reproduction project

[Fog Depth.zip](https://github.com/godotengine/godot/files/12263944/Fog.Depth.zip)

**Comment by clayjohn** [comment]
This will be fixed by https://github.com/godotengine/godot/pull/66030

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/4619.
