### ISSUE TITLE
`ScriptExtension` produces missing virtual error on editor run

### ISSUE THREAD

**Issue by voidedWarranties** [godotengine/godot#80275]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Fedora Linux 38 (Workstation Edition) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.54.03) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When starting a project that utilizes `ScriptExtension` with the editor, the following error occurs:

```
E 0:00:00:0703   _gdvirtual__get_language_call: Required virtual method ScriptExtension::_get_language must be overridden before calling.
  <C++ Source>   ./core/object/script_language_extension.h:106 @ _gdvirtual__get_language_call()
```

even though the method is implemented and registered.

From my debugging, I believe this is the condition under which the error happens:

1. Project starts from editor.
2. Godot attempts to load a script.
3. When the `Script` is constructed, [`Wrapped`'s constructor](https://github.com/godotengine/godot-cpp/blob/5834e16a221fde8dc0b6ca4b7a6721cc4b258037/src/classes/wrapped.cpp#L51-L53) creates the Godot-side object, `postinitialize_handler` is called from the Godot side, and `NOTIFICATION_POSTINITIALIZE` is fired.
4. [`Script`'s notification handler](https://github.com/godotengine/godot/blob/16a93563bfd3b02ca0a8f6df2026f3a3217f5571/core/object/script_language.cpp#L49-L55) fires, which attempts to call `get_language`.
5. [The virtual call](https://github.com/godotengine/godot/blob/16a93563bfd3b02ca0a8f6df2026f3a3217f5571/core/object/make_virtuals.py#L18-L22C1) attempts to find the `Script`'s corresponding extension. It cannot find it, so the call fails and the error is printed.
6. `postinitialize_handler` is called on the GDExtension side and [the `Script`'s extension is finally set](https://github.com/godotengine/godot-cpp/blob/5834e16a221fde8dc0b6ca4b7a6721cc4b258037/src/classes/wrapped.cpp#L43-L61).
7. Virtual calls outside of `postinitialize_handler` are successful.

I'm not 100% sure this is correct, but it seems fairly likely.

### Steps to reproduce

1. Install any extension that utilizes `ScriptExtension`.
2. Create a script.
3. Run the project from the editor.

### Minimal reproduction project

[MRP_ScriptExtension_virtual.zip](https://github.com/godotengine/godot/files/12264450/MRP_ScriptExtension_virtual.zip)

I've attached binaries from [my implementation](https://github.com/Fumohouse/godot-luau-script) as I don't think a different extension will produce a different result. You can verify that `get_language` is implemented [here](https://github.com/Fumohouse/godot-luau-script/blob/v0.8.0/src/luau_script.cpp#L425-L427).

Usage:

1. Unzip the archive and start the editor.
2. The editor will crash on import due to an unrelated issue.
3. Open the editor again.
4. Start the main scene.

**Comment by Naros** [comment]
I can also reproduce this on the latest 4.2 dev builds.

**Comment by tarragonfly** [comment]
Reproducable in Godot 4.2.1 stable.

**Comment by Naros** [comment]
Fixed in https://github.com/godotengine/godot/pull/90776.
