### ISSUE TITLE
Changing GridContainer's columns variable, resets the scaling of all its children

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#80273]
### Godot version

4.1 stable

### System information

Artix (tl;dr: Arch Linux) - Vulkan

### Issue description

I try to scale down the gridContainer children, and at the same time change GridContainer's columns to accomodate the change, visually (more columns can fit in the same space with smaller items)
Scaling prevents columns changing, and vice versa.
See MRP.
![tree](https://github.com/godotengine/godot/assets/25630803/d7eb2e3d-f58c-4f6e-ab3d-da446b4b03ef)

As for my use-case, I basically want to zoom out/in cards in a grid container, I don't think that's rare for a game - to scale up/down items in a grid container.

### Steps to reproduce

Create a GridContainer with many control node children In the same frame, try to scale down those control nodes, then change the columns variable of GridContainer. The columns variable remains true but the scale of the control nodes is reverted! If you don't change the column variable, the scale down is preserved.

### Minimal reproduction project

Press Enter to test ("ui_accept")
Note that scale should be halved, yet it is not. Columns are changed ofc.

Now, open ```CardsPanel.gd``` and comment out either line 22 or 43. 
Run again, press Enter. Scale is halved, but ofc no columns change (since they are commented out)

[grid-container-bug-MRP.zip](https://github.com/godotengine/godot/files/12263744/grid-container-bug-MRP.zip)

**Comment by YuriSizov** [comment]
You can't change position, size, or scale of children within a container. Container fully controls and resets those properties. The moment that you make the container update anything about itself, you see this happening. This is not a bug, it's just what containers are designed to do.

**Comment by TheYellowArchitect** [comment]
>You can't change position, size, rotation, or scale of children within a container. Container fully controls and resets those properties. The moment that you make the container update anything about itself, you see this happening. This is not a bug, it's just what containers are designed to do.

@YuriSizov I can change the scale of gridcontainer's children just fine though. The bug is when on the same frame I change the columns variable.

**Comment by YuriSizov** [comment]
@TheYellowArchitect Yes, you can change them, but you shouldn't do that. There is no way to prevent you from doing it. Both public API and internal API use the same methods. When containers override these properties, they call the same setters. That is, however, expected and documented, and the entire point of containers. There is no bug.

> Even when the gridcontainer's size changes (viewport change signal trigger), the gridcontainer items' scales are not reset.

Every container does it whenever they need to update they layout of their children, see `fit_child_in_rect`. It's called, resetting rotation and scale, and overriding the rect, when the size of the node changes too. I'm not sure what you mean by "viewport change signal".

> That said, how would you solve my use-case

As always, if you need to animate children of containers the recommended way is to use an intermediate control that takes the exact amount of space your item would normally take. Then your actual item, being a child of a normal control, can be animated however you want.

You can also write a custom container.

**Comment by TheYellowArchitect** [comment]
Alright, thank you for the answer, I will look into both of these solutions.

**Comment by YuriSizov** [comment]
> I wish I knew how, there is no tutorial anywhere for this, and I assume I have to touch C++ to get something worthy. I will try the other 2 solutions first

You don't need to touch C++. It's a fully supported part of the scripting. It's briefly mentioned [here](https://docs.godotengine.org/en/stable/tutorials/ui/gui_containers.html#creating-custom-containers). Basically what you need to do is to extend `Container` and then handle the `NOTIFICATION_SORT_CHILDREN` notification. Use the aforementioned `fit_child_in_rect` to update children.

Implement `_get_minimum_size` too if you need custom logic for determining container's own minimum size (say, children contribute to it, like in `BoxContainer`). If you need to handle size flags with your container, make sure to implement `_get_allowed_size_flags_horizontal/vertical` too.

Here's an example of a custom container: https://github.com/GDQuest/learn-gdscript/blob/main/ui/components/Revealer.gd

**Comment by TheYellowArchitect** [comment]
Thanks. I figured out how to make custom container and got it mostly working, so with 1 more hour of work I would finish it. But the father's ScrollContainer scroll bar doesn't show anywhere nor can I scroll, so I will pause this for now and try the original 2 solutions you mentioned.
