### ISSUE TITLE
Multi touch compatibility on desktop platforms

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#8028]
Multi touch works perfectly on Android but not on Windows or Linux,  I tried this demo:

https://cdn.discordapp.com/attachments/212251562553114624/275760789309095936/2017_01_30_23_48_46.mp4

https://cdn.discordapp.com/attachments/212251562553114624/275763149007880192/multi_touch_test.zip

As expected this should work on Android (maybe on IOS as well) but not on desktop platform. These days there's plenty of Windows tablets with multi-touch support, it would be good to have the multi touch functionality from mobile devices extended to desktop platforms as well. I work for a company that uses multi touch devices and Unreal 4 to show the content and if I have Godot with multi-touch support on Windows/Linux I might be able to convince my superiors to change from UE4 to Godot.

**Operating system or device - Godot version:**
Windows 8, Linux Redhat
Godot Engine 2.1.2-stable

**Comment by raymoo** [comment]
This is relevant to me since I am developing a game with touchscreen controls and would like it to be possible (at least theoretically, since I don't have a desktop touchscreen) to play without running an Android device.

**Comment by bojidar-bg** [comment]
(needs testing tag is for platform:osx)

**Comment by raymoo** [comment]
Based on searching around, it seems like we would have to convert X11 input stuff to all use XInput, is that right?

**Comment by samvila** [comment]
I don't know if this could be of any help but it seems like Unreal Engine 4 is using Chromium to handle the multi-touch, we tried the latest version of UE4 and on windows works perfectly using the official build but on linux there was a problem, we submitted a patch to make it work but we never hear anything from epic about our patch. I would check the source code from UE4 to see how they implemented this and maybe try something simiarl, what do you think?

**Comment by raymoo** [comment]
Isn't Chromium a little heavy for this?

**Comment by raymoo** [comment]
While searching I saw that X11 supports both multiple touch events and multiple mouse pointers, which you can get if you plug in two mice and configure them a certain way. I personally don't have a use for multiple pointers, but it could be useful for a game that wants to be controlled by two mice.

**Comment by punto-** [comment]
Did anyone try the old multitouch code in os_windows.cpp that was commented
out because it only worked on windows 7 and up? now that microsoft is
abandoning Vista it should be fine..

**Comment by StraToN** [comment]
Duplicate or related to #7612 ?

**Comment by raymoo** [comment]
Seems like this is a dupe except the other issue has more focus on editor support.

**Comment by samvila** [comment]
I think is similar but my report is more oriented into extending multi-touch functionality from IOS/Android into desktop devices. The #7612 seems more focus on user interface on the editor.

**Comment by raymoo** [comment]
Related? https://godotengine.org/article/let-people-touch-godot

**Comment by reduz** [comment]
@RandomShaper guess this can be closed?

**Comment by RandomShaper** [comment]
Yeah! I forgot. Closing it myself.

**Comment by raymoo** [comment]
Is it supported on OSX too?
