### ISSUE TITLE
Scene file became corrupted/invalid.

### ISSUE THREAD

**Issue by carllacan** [godotengine/godot#80324]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Manjaro Linux #1 SMP PREEMPT Tue Jul 25 07:09:46 UTC 2023 - Vulkan (Forward+) - dedicated AMD Radeon RX 550 / 550 Series (RADV POLARIS12) () - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I was working on a game and all of a sudden I started getting a warning about a certain scene file being corrupted/invalid. As far as I remember I had recently done any changes on that file. When running the game the scene continues to be successfully instantiated, but I can't open it to edit because the aforementioned error message pops up.

### Steps to reproduce

Unknown.

### Minimal reproduction project

As GitHub does not allow me to attach .tscn files I attach the scene file with a .txt extension: [base_ship.txt](https://github.com/godotengine/godot/files/12269031/base_ship.txt)

**Comment by KoBeWi** [comment]
The scene seems to be missing dependencies.
Especially GDScript dependencies can break if you use preload inside global classes, see #79840

**Comment by dalexeev** [comment]
Or cyclic dependencies. See https://github.com/godotengine/godot/issues/74253#issuecomment-1564227775, try to replace `preload()` with `load()`.

**Comment by jivvy** [comment]
This has been happening consistently to me recently. v4.2.dev.custom_build [ 691634969 ].

Logs:

```
ERROR: res://scenes/ui/end_screen.tscn:12 - Parse Error:
   at: _parse_node_tag (scene/resources/resource_format_text.cpp:284)
ERROR: Failed loading resource: res://scenes/ui/end_screen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:141)
ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:141)
```

**Comment by RayJJ** [comment]
Similar behaviour in 4.2.rc1 - I have 'Restore Scenes on Load' selected in the Editor Settings.

Opening the editor often reports one or more of the previously open scenes as corrupt/invalid and refuses to reopen them from the FileSystem dock. Running diffs of the .tscn files with their latest git commits shows no changes.

As @carllacan reported, running the game in the editor is unaffected. In my case after running the game once I can open and edit the .tscn files again, so this is a great workaround.

**Comment by KoBeWi** [comment]
I checked again if any of the scene opening fixes would resolve this issue and no, the scene still can't be opened.
This is some weird case. When you try to open it, you get a missing dependency error listing only the shader:
![image](https://github.com/godotengine/godot/assets/2223172/996aad68-aa32-4da6-af94-4b872d1d9a51)
Clicking Open Anyway will result in a corrupted error and fails.

However if you remove only the shader, you get this instead:
![image](https://github.com/godotengine/godot/assets/2223172/72464adf-0769-492e-8839-f8e15ce21dfb)
Suddenly the editor sees all other dependencies. Opening it (at least with #86781 applied) will succeed.

Looks like some bug specific to shaders.
