### ISSUE TITLE
ResourceLoader can't load glb files that not located in project directory

### ISSUE THREAD

**Issue by meisamsafavi** [godotengine/godot#80328]
### Godot version

4.1, 4.1.1

### System information

Widows 10

### Issue description

I was trying to use ResourceLoader to background load my resources and it works perfectly when resource files(in my case .glb files) are in project directory, but my goal is to background load resources which are not located in project directory, and load them in runtime.
Unfortunately it's not happening, even ResourceLoader's `exists()` function returns false.

### Steps to reproduce

1.Use FileDialog to get your .glb file path or hard code it inside your script.
2.Check file exists or not
3.Use ResourceLoader to background load it.

### Minimal reproduction project

[Background_loading.zip](https://github.com/godotengine/godot/files/12269144/Background_loading.zip)

**Comment by KoBeWi** [comment]
ResourceLoader can only load resources inside the project directory, although it only applies to importable resources (textures, audio, models). This is even mentioned in the description.
There is currently no way to import models at runtime.

**Comment by meisamsafavi** [comment]
> ResourceLoader can only load resources inside the project directory, although it only applies to importable resources (textures, audio, models). This is even mentioned in the class description. There is currently no way to import models at runtime.

OK, so actually I imported glb models at runtime using `FileAccess`, `GLTFDocument` and `GLTFState` classes.
This is about background loading the same models at runtime.

**Comment by AThousandShips** [comment]
You can't *import* anything at runtime, loading is a different matter

**Comment by meisamsafavi** [comment]
> You can't _import_ anything at runtime, loading is a different matter

Ok, Is there anyway to background LOAD the glb models which there are not located in project directory?

**Comment by AThousandShips** [comment]
You can do it on a thread possibly, I haven't used it myself

**Comment by meisamsafavi** [comment]
> You can do it on a thread possibly, I haven't used it myself

tried that already but not working.
I'm getting these:
![Capture](https://github.com/godotengine/godot/assets/74149722/72201665-bb6f-4db4-99f1-fa7b79726086)

**Comment by meisamsafavi** [comment]
> You can use a buffer of a glb. That is tested.

Didn't catch what you said
Is it possible to background load it?

**Comment by fire** [comment]
A buffer is called a PackedByteArray. Glb is a format of gltf.

**Comment by meisamsafavi** [comment]
> A buffer is called a PackedByteArray. Glb is a format of gltf.

would you please provide some example code?
are you talking about GLTFDocument and GLTFState classes?
cause I have already use them but couldn't use them to background load the resources

**Comment by fire** [comment]
You already know about this thread https://github.com/godotengine/godot-docs/issues/6385

**Comment by lyuma** [comment]
I am closing this since this is not an issue with Godot: GLTF files not in the project directory will not be imported into native resources, and hence you cannot use ResourceLoader to load them. You *must* use GLTFDocument.

@meisamsafavi since it seems like there was a misunderstanding about what fire meant by "buffer", here is some example code I copied from #85960 showing how to use [GLTFDocument.append_from_buffer](https://docs.godotengine.org/en/stable/classes/class_gltfdocument.html#class-gltfdocument-method-append-from-buffer)
```gd
var gltf := GLTFDocument.new()
var gltf_state := GLTFState.new()
var path = "res://3D_model/4/4.glb"
var snd_file = FileAccess.open(path, FileAccess.READ)
var fileBytes = PackedByteArray()
fileBytes = snd_file.get_buffer(snd_file.get_length())
gltf.append_from_buffer(fileBytes, "base_path?", gltf_state, 8)
var node = gltf.generate_scene(gltf_state)
add_child(node)`
```
I added that `, 8` there to force ENABLE_TANGENTS since it is required for mesh compression since 4.2

**Comment by meisamsafavi** [comment]
@lyuma 
thanks for responding and correcting the code too.
