### ISSUE TITLE
worldenvironment glow not work properly

### ISSUE THREAD

**Issue by Nms-12** [godotengine/godot#80321]
### Godot version

4.0.3

### System information

linux

### Issue description

Currently, this only been tested in 4.0.3, but should be the same in 4.1+

from what I have told before, HDR threshold can prevent any node which raw number is under the threshold to glow, and only let the one who raw number is above  the threshold to glow.

But in 4.0.3, I cannot replicated that. higher raw number with higher threshold, you need more glow strength to make the glow work, but it also make node that under the threshold glow as well.

And sometimes the object will only glow in inspector, but not in game, at least not visible,  you can't tell it has glow.

### Steps to reproduce

add 2 line2d
add world environment and setup glow property(increase threshold ), adjust glow strength
change one of the line2d raw color higher than threshold

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12268896/test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/62110.
