### ISSUE TITLE
Godot 3.0 Collisions Shapes (CollisionShape2D / CollisionPolygon2D) dont get drawn on the editor or debug, except RectangleShape2D, RayShape2D or LineShape2D

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#8033]
**Operating system or device - Godot version:**
Ubuntu 16.04
Godot 3.0
gcc 5

**Issue description:**
When adding a CollisionShape2D different than a RectangleShape2D to a KinematicBody2D or StaticBody2D the CollisionShape2D is not drawn on the editor or when debugging collision shapes, except if it is a RectangleShape2D, RayShape2D or LineShape2D.
CapsuleShape2D, CircleShape2D, ConcavePolygonShape2D, ConvexPolygon2D dont get drawn
CollisionPolygon2D also dont get draw correctly, just the outline, but never the "blue" area inside the polygon

**Steps to reproduce:**
.--For CollisionShape2D:
1.-turn on see collision shapes for debug
2.-create a KinematicBody2D
3.-add a CollisionShape2D
4.-set the CollisionShape2D to capsule
5.-the CollisionShape wont be draw

.--For CollisionPolygon2D:
1.-turn on see collision shapes for debug
2.-create a StaticBody2D
3.-add a CollisionPolygon2D
4.-set the CollisionPolygon2D to Array Size 4 and add 4 vertexs:
(-10,-10),(-10,10),(10,10),(10,-10)
5.-the CollisionShape wont be draw

**Comment by bojidar-bg** [comment]
Can confirm they didn't draw in editor a few weeks ago, so I would assume it is the same issue...

**Comment by novemberist** [comment]
I can also confirm this. NavigationPolygons also don't have the blue tinted fill, they used to have in 2.1

**Comment by chaosdrop** [comment]
Same issue here, effects every computer I have so:
Modern and old AMD and Intel CPUs, Older AMD, Newer Nvidia, and Newer and Older Intel GPUs
Windows 7 Pro and Windows 10 Pro

The only CollisionShape that renders correctly is the rectangle.

**Comment by toger5** [comment]
this is related to: #8425
The PR should really get merged. In 3.0 the circle and poly draw functions of the current master are just commented out. because the draw poly function does not work. #8425 fixes the draw poly function and by doing so fixes color picker, collision shapes...

**Comment by ficoos** [comment]
I've suggested #9035 as a quick fix for now until @reduz finishes the GLES3 renderer.

**Comment by toger5** [comment]
what is the difference of  #9035  and  #8425.

**Comment by reduz** [comment]
this should be closed now, as i fixed _draw_polygon
