### ISSUE TITLE
top_level cause  editor gizmo and in game transform not same

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#80332]
### Godot version

v4.1.rc.custom_build [e044e13d5]

### System information

debian stable

### Issue description

transform in editor gizmo location  is local value, but in game is global transform. So it cause this problem,
![image](https://github.com/godotengine/godot/assets/12198203/5e2a3344-323e-49ac-b5b2-031153ce5405)
![image](https://github.com/godotengine/godot/assets/12198203/6a462b8a-c1bc-4fb6-a1ad-e5197e47f316)

### Steps to reproduce

just try it

### Minimal reproduction project

[set_toplevel.zip](https://github.com/godotengine/godot/files/12269640/set_toplevel.zip)

**Comment by kitbdev** [comment]
- fixed by https://github.com/godotengine/godot/pull/84643
