### ISSUE TITLE
Errors when scaling for mobile renderer (FSR and Bilinear)

### ISSUE THREAD

**Issue by adammikulis** [godotengine/godot#80340]
### Godot version

v4.2.dev2.official [da81ca62a]

### System information

Godot v4.2.dev2 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

Using FSR 1.0 or Bilinear scaling (any factor besides 1) with the Mobile renderer creates errors:

Error with FSR 1.0 and Scale < 1:

> servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp:232 - Condition "target_size != internal_size" is true. Returning: RID()

Error with FSR 1.0 and Scale > 1:

> All textures in a framebuffer should be the same size.
> ./servers/rendering/renderer_rd/effects/../storage_rd/..framebuffer_cache_rd.h:170 = Condition "rid.is_null()" is true. Returning: rid

Error with Bilinear and Scale < 1:

> All textures in a framebuffer should be the same size.
> ./servers/rendering/renderer_rd/effects/../storage_rd/..framebuffer_cache_rd.h:170 = Condition "rid.is_null()" is true. Returning: rid

Error with Bilinear and Scale > 1:

> All textures in a framebuffer should be the same size.
> ./servers/rendering/renderer_rd/effects/../storage_rd/..framebuffer_cache_rd.h:170 = Condition "rid.is_null()" is true. Returning: rid

### Steps to reproduce

Create a new project with Mobile renderer. Navigate to Project Settings > General > Rendering > Scaling 3D and change the Scale.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/70093
