### ISSUE TITLE
Nintendo Switch Pro controller does not trigger actions when created via code

### ISSUE THREAD

**Issue by liabilityluke** [godotengine/godot#80349]
### Godot version

4.1.1

### System information

Windows 11

### Issue description

When you add an event to an action via code, and add a button event to it, the Nintendo Switch Pro Controller will not trigger the event, even though an Xbox controller will. It's especially weird because this is exclusive to events created from code. 

### Steps to reproduce

Add an event to an action using code (my code is 	`InputMap.action_add_event("jump", (func(): var event := InputEventJoypadButton.new(); event.button_index = JOY_BUTTON_A; return event).call())`). A Nintendo Switch pro controller will not trigger this, but an Xbox controller will.

I have made modifications to the 2d platformer demo to show this. At runtime, the script "game" erases the jump events and replaces them with their original buttons. If it works like it does for me, the jump button will not work with a Nintendo Switch pro controller, but it will work with a xbox one controller.

### Minimal reproduction project

[pro_controller_code_action_test.zip](https://github.com/godotengine/godot/files/12270269/pro_controller_code_action_test.zip)

**Comment by Calinou** [comment]
You probably need to change the device ID of the events created from code. By default, only the first controller is matched. Use the special ID that matches all events.

Events created in the editor default to all devices, but this is not done for events created from code for backwards compatibility reasons.

**Comment by liabilityluke** [comment]
that's it! looks like it's -1 that matches with all events
