### ISSUE TITLE
Black screen when anti-aliasing is enabled when deploying to Oculus Quest

### ISSUE THREAD

**Issue by skooter500** [godotengine/godot#80341]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.2737) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When deploying a scene using remote debug, the scene shows up as as black on the Quest 2. This happens when any value above MSAA3D Disabled (Fastest) is set. I.e if  MSAA3D is Disabled, the scene runs with jaggies. If value is 2x, 4x, 8x, the scene renders all black 

### Steps to reproduce

Here is a minimal project that will demonstrate the problem

https://github.com/skooter500/Test-Godot-XR

Remote debug will deploy the scene to the quest, which is just a grey plane. However if you go to project settings and set anti-aliasing to any of the settings and do a remote depoly, you get a black screen on the quest

### Minimal reproduction project

https://github.com/skooter500/Test-Godot-XR

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73384.
