### ISSUE TITLE
UWP games crashing

### ISSUE THREAD

**Issue by blebs527** [godotengine/godot#80344]
### Godot version

3.5.2 Stable

### System information

Windows 10 - Godot v3.5.2 Stable

### Issue description

I tried exporting a simple game to UWP, just for testing purposes, but every time I try to run the game it shows the splash screen for a second, then crashes and closes. Same thing happens on my Xbox, when running it in development mode. 
(Godot 3.5.2 stable)

### Steps to reproduce

just export the game to UWP and run it.
video bellow:

https://github.com/godotengine/godot/assets/101520426/4ce9de30-0186-4dc6-886d-871b9b956692

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
The UWP port is known to be broken: https://github.com/godotengine/godot/issues/30558

**Comment by panreyes** [comment]
Hi! It should work with a few workarounds. Try to follow these steps, they might help you:
https://www.rawrlab.com/blog/2023/07/24/how-to-play-your-godot-3-x-game-on-your-xbox/

**Comment by blebs527** [comment]
> Hi! It should work with a few workarounds. Try to follow these steps, they might help you: https://www.rawrlab.com/blog/2023/07/24/how-to-play-your-godot-3-x-game-on-your-xbox/

Thank you for your help. I tried this method before publishing the problem, but unfortunately the same thing happens.

**Comment by panreyes** [comment]
> > Hi! It should work with a few workarounds. Try to follow these steps, they might help you: https://www.rawrlab.com/blog/2023/07/24/how-to-play-your-godot-3-x-game-on-your-xbox/
> 
> Thank you for your help. I tried this method before publishing the problem, but unfortunately the same thing happens.

I'd like to find out why is not working for you.
Ping me at Discord (@panreyes) and we'll find out why.
