### ISSUE TITLE
Exclusive fullscreen doesnt start focused if resizable is false

### ISSUE THREAD

**Issue by zigaliro** [godotengine/godot#80350]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3179) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

If you set the window mode to "Exclusive Fullscreen" in the project settings and if you have resizable set to "false", when you run your project, the window will not start focused meaning it wont be receiving any keyboard input until you click with your mouse. This issue goes away if you set resizable to "true".

### Steps to reproduce

1. Go to project settings
2. Set mode to Exclusive fullscreen
3. Set resizable to false if its true
4. Start the project

### Minimal reproduction project

[fullscreenBug.zip](https://github.com/godotengine/godot/files/12270331/fullscreenBug.zip)

**Comment by Calinou** [comment]
This was supposed to be fixed in 4.1.1 as per https://github.com/godotengine/godot/issues/74286 and https://github.com/godotengine/godot/pull/78151.

cc @jpcerrone

**Comment by Calinou** [comment]
Closing per the above comment. Please comment if you can still reproduce this on the latest Godot version.

**Comment by Alidonis** [comment]
Reproduced on [v4.3.stable.mono.official.77dcf97d8](https://github.com/godotengine/godot/commit/77dcf97d82cbfe4e4615475fa52ca03da645dbd8) 

see [my comment](https://github.com/godotengine/godot/issues/83470#issuecomment-2429914362)
