### ISSUE TITLE
Godot Editor/Built Games/Downloaded Games Start Slowly

### ISSUE THREAD

**Issue by Charpurrr** [godotengine/godot#80352]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11 - Godot 4.1.1

### Issue description

Doing anything related to Godot, (i.e. selecting a scene tab, running a downloaded game made within Godot engine, opening the Godot project manager, running a project) will cause the program to freeze (not respond) for around 30 seconds before returning to normal. I can't find any way to work around this and it makes using Godot impossible. I can't identify a clear cause, and it seems to affect the entire engine rather than a specific project.

### Steps to reproduce

Unknown

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Which graphics card model do you have? Are you on a laptop with hybrid graphics?

**Comment by Charpurrr** [comment]
Yeah I do have hybrid graphics on this laptop, a combination of NVIDEA GeForce GTX 1650 and Intel(R) Iris(R) Xe Graphics (Core i5)

**Comment by Charpurrr** [comment]
Issue seems to have been fixed by updating video drivers. However, uncertain if having outdated drivers was the problem, since Godot and all of the related issues I mentioned worked fine *without* updating them before.
