### ISSUE TITLE
printraw() not working on editor console

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#80353]
### Godot version

v4.1.1.stable.gentoo [bd6af8e0e]

### System information

Godot v4.1.1.stable (bd6af8e0e) - Gentoo 2.14 (llvm/clang toolchain musl libc)

### Issue description

`printraw` is not working in editor output window

Output:
```bash
Godot Engine v4.1.1.stable.gentoo.bd6af8e0e - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 23.1.5 - Compatibility - Using Device: Intel - Mesa Intel(R) HD Graphics 620 (KBL GT2)
 
3
--- Debugging process stopped ---
```

### Steps to reproduce

- Add root Node2D to project
- Attach script `node_2d.gd`
- set main scene to current scene
- run the project

### Minimal reproduction project

`node_2d.gd`:
```gdscript
extends Node2D
func _ready():
	printraw("1")
	printraw("2")
	print("3")
```

**Comment by KoBeWi** [comment]
> Prints one or more arguments to strings in the best way possible to the OS terminal.

It's not supposed to appear in the editor.

**Comment by LinuxUserGD** [comment]
> > Prints one or more arguments to strings in the best way possible to the OS terminal.
> 
> It's not supposed to appear in the editor.

Ok, thought it was a bug, closing then as duplicate of https://github.com/godotengine/godot/issues/33255
