### ISSUE TITLE
errors  on  export to  html5 

### ISSUE THREAD

**Issue by relaxslow** [godotengine/godot#80351]
### Godot version

4.1

### System information

macos

### Issue description

see screenshot 
<img width="1084" alt="Screenshot 2023-08-06 at 3 53 19 PM" src="https://github.com/godotengine/godot/assets/5476899/c7091b4f-f769-45c5-845a-e32d8b946626">
the engine seems started 
but there is something wrong with the audio

### Steps to reproduce

This error occurs each time when I connect to my server via https protocol
I have edit the template html and pointed all the resources include .pck and .wasm and .js to the correct path

### Minimal reproduction project

[minimalProject.zip](https://github.com/godotengine/godot/files/12270468/minimalProject.zip)

please export this little project to Html5 
and host on a server

**Comment by Calinou** [comment]
As the warning message says, you aren't allowed to play audio if no matching user input (such as a mouse click or touch input) was performed. This is a browser security measure you can't override.

**Comment by relaxslow** [comment]
thanks for response, 
but I did not play any audio in the project. please check the minimal project . there is only a button there, and I want to test if the application can be safely export to html

**Comment by Calinou** [comment]
>  Is there any way I can config the engine not to use audio or like

You can set the audio driver to `Dummy` in the Project Settings, which will make the engine not initialize any kind of audio playback.

**Comment by Calinou** [comment]
> and I can not return to the default setting

You can click the Revert button, which will remove the modified project setting from `project.godot` (and therefore revert to the default value for each platform).

**Comment by relaxslow** [comment]
any update here? the graphic was showing after a long waiting , I still got error 
<img width="470" alt="image" src="https://github.com/godotengine/godot/assets/5476899/e5e45f32-b4d0-40da-b3b1-dc4d307221eb">
