### ISSUE TITLE
Path for Engine/Editor/Plugin-used scenes/files?

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#8036]
Writing a plugin may require a gui-scene. EDIT: in c++
But where save that?
as example:
lets say i write a terrain module,
i did this in the modules folder.
the plugin to edit the terrain, currently is there too.
but the plugin uses a gui-scene for display (in the dock)
now where put that tscn file?
in res:// it is now, but i dont want users of the plugin to always copy it there...
user:// seems completly wrong...

i think i need some sort of engine:// mapped to somewhere (loc of binary or $binaray/enginedata)?
but this breaks with "godot is a single file", 
if no such folder, i forced to hack my own, or limited to create the scenes programmatically only

**Comment by bojidar-bg** [comment]
If you are making a gdscript plugin (but it seems like you aren't) then #6023 - current idea is that one should keep everything (except readme/license, but that's under consideration), in `res://addons/<author>.<name>/...`

If you are making a module, you can only create the nodes by hand, not use a scene for that (yeah, I know, it's ugly, but...) That's how it is done in the engine ATM, and I am not sure it is going to change anytime soon.

**Comment by CharlesWoodhill** [comment]
its in c++

**Comment by Zylann** [comment]
How about making a converter .tscn to C++? Just an idea ;D I agree it's ugly, we loose the flexibility of the editor...

**Comment by CharlesWoodhill** [comment]
i know simple is nice, but sooner or later godot will need additional engine files, think about plungins or modules as dll, or wouldnt it be simpler to just add a folder including a dll+files to ..../plugins... and then it simply works? no need to compile the whole engine after u chosen ur set of addons/plugins, this should work for c++ too, not only for godot projects. maybe not wanted but, what if a developer want to use 2 modules, both coded by guys not wanting to expose their code? currently u cant...

**Comment by Zylann** [comment]
Dynamic modules are being worked on here if that's what you mean: https://github.com/GodotNativeTools/dlscript_module

**Comment by CharlesWoodhill** [comment]
in principle i talking about this(if i understood it by my quick view)
beside the fact that this still needs a standard-path to look for the dlib (could be different on plattforms) 

concerns about the project:
1. it need capsules around the godot classes, otherwise not visible to plugin/module
2. if godot changes somewhere or adds features, the project needs to be reworked too.
3. the name dlscript implies that it uses the script/binding system, so u cant simply call funtion pointers, u have to seek the function in a hash everytime u call it, so very often called functions may be slow/impossible.
4. try to call VisualServer::get_singelton()->instance_create2(wireMeshRid, parentSpatial->get_world()->get_scenario() );

u have to remember that im talkin about c++ developement where low lvl access is needed/wanted.
i dont talk about scripters/gamecreators who should stick to scripting.
example:
godot_low_lvl_api <--- TerrainEngine <--- godot_scripting
and not:
godot_low_lvl_api <--(impossible,cumbersome,needless?)-- godot_scripting <-- TerrainEngine <-- godot_scripting

visual server is a good example for how done: non oo api (to make a dll border possible)
then usage classes provided (Mesh, ....) u simply include those .h files and can start develop,
even if vs would be a dll.
a bad example is the Scene-System and godot itself, only classes, no api.
from a technical point of view, "modules" and "plugins" only exist on paper, since they are no libraries, they are a part of the progam, and cant be plugged in/out.
at least u can choose the modules, but u still need to compile befor use...unnecessary.

**Comment by Calinou** [comment]
I'll close this, as this issue isn't actionable as it's currently worded. If you still have a need for this, please open a proposal on the [Godot Proposals](https://github.com/godotengine/godot-proposals) repository.
