### ISSUE TITLE
Using multiple VoxelGI causes shadow popping, wrong lighting and other inconsistencies.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#80361]
### Godot version

4.2, 4.1.1

### System information

Windows 10, Nvidia GTX 1660Ti, Vulkan

### Issue description

I've noticed that when I use multiple VoxelGI nodes the shadows get messed up, the best would be to check the video here (with sound - sorry for the cat crying in the background it's unavoidable in my current situation): https://youtu.be/6sENhQ0UoMk
*(the issues happens both in the editor and when you play the project through the play button too, same does not happen to shaddows when GIs are hidden)*

I'm not sure if this is how it's supposed to work and using this amount of VoxelGI nodes is just wrong or not so I'm not providing a test project for now, if it actually is a bug I'll try to put something together, please let me know.

If it's not a bug I think it would be better to add a note to VoxelGI's documentation about it.
If it is a bug it pretty much makes VoxelGI use impossible unless you use a single node it seems?

### Steps to reproduce

Place multiple VoxelGI nodes in a scene, bake them and observer the issues.

### Minimal reproduction project

None for now, check the Issue description above please.

**Comment by Calinou** [comment]
You can only have up to 8 VoxelGI instances in view, and each mesh may only be covered by 2 VoxelGI instances at most (results will be blended together):

https://github.com/godotengine/godot/pull/58389

**Comment by OctagonalHexy** [comment]
https://github.com/godotengine/godot/assets/85406370/9c1cf9bc-86ab-4da8-b526-4618281a1b03

Can confirm. After 8 in your frustum, one stops showing.
It appears to always be that one that started in the top left of the video regardless of how close the camera is, but that was the last one I baked so its likely choosing based on that.
