### ISSUE TITLE
Android touch blind spots

### ISSUE THREAD

**Issue by rcmz** [godotengine/godot#80369]
### Godot version

v3.5.2.stable.official [170ba337a], v4.1.1.stable.arch_linux, v4.2.dev.custom_build [16a93563b]

### System information

Fairphone 3 running Android 13 (LineageOS 20)

### Issue description

I have some touch "blind spots" in the corners of my screen. When I touch these spots, no InputEvent is generated. When I release the touch, a pressed InputEvent is generated followed by a non-pressed InputEvent. I tried using mouse events, deactivating immersive (fullscreen) mode, running it in portrait mode, but I always get the blind spots. See the picture for an approximate location of the spots. 

![touch_blindspots](https://github.com/godotengine/godot/assets/40456553/dbd8e6f2-e785-4c06-a868-216cfc4a07e5)

### Steps to reproduce

Run the linked project on Android and see if the screen turns red when you touch it.

### Minimal reproduction project

[AndroidTouchBlindspots.zip](https://github.com/godotengine/godot/files/12277973/AndroidTouchBlindspots.zip)

**Comment by Zireael07** [comment]
Have you tried another Android device? I had such "blind spots" on an old handmedown tablet that was, well, old... hardware fault...

**Comment by rcmz** [comment]
Oh well you're right, the blind spots are also present in other apps so this is not a Godot issue. Surprising that I never noticed it before.
