### ISSUE TITLE
NavigationMesh gravity

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#80376]
### Godot version

4.1.1

### System information

Any platform

### Issue description

Sorry for creating a bug, just want to ask a question.
Trying to create a NavigationRegion 3D with "enemy" chasing player on a vertical playground, so player and enemy moving along X and Y (Z locked) here is couple screenshots for better understanding.
<img width="692" alt="Screenshot 2023-08-07 at 6 58 41 AM" src="https://github.com/godotengine/godot/assets/3720229/433394d0-f3b9-492a-9b75-2dafe2e89299">
<img width="189" alt="Screenshot 2023-08-07 at 6 58 56 AM" src="https://github.com/godotengine/godot/assets/3720229/c4ce9060-fd12-4794-bf88-abacf8bc12de">
Trying to use NavigationRegion3D for it, but seems like it only uses Z as a gravity direction, please help me to find solution for my problem.

### Steps to reproduce

Any NavigationRegion3D with gravity direction other than Z

### Minimal reproduction project

Can be a project with gravity other than Z

**Comment by AThousandShips** [comment]
I'd recommend reading the [documentation](https://docs.godotengine.org/en/latest/tutorials/navigation/index.html)

**Comment by theromis** [comment]
@AThousandShips I've checked it and I can't find right approach, btw, I can't post any questions to the "channels"
<img width="917" alt="Screenshot 2023-08-07 at 7 19 55 AM" src="https://github.com/godotengine/godot/assets/3720229/178fe760-c009-45c2-87fe-c963a1bda3eb">

**Comment by AThousandShips** [comment]
Yes, the Q&A is down at the moment, pleas try other channels such as discord or the forums, that's not the only other channel

Please don't ping me, it's only me here
