### ISSUE TITLE
If Button Icon is aligned Center, but Text is aligned Left/Right, the text will still avoid the space the icon would take.

### ISSUE THREAD

**Issue by ch0m5** [godotengine/godot#80386]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

When a Button has an icon and the icon is set to be aligned to the center, but the Button Text is aligned to the Left or Right, the text will avoid the space the icon would take as if the icon was aligned Left or Right, respectively. In other words, the text is expected to be centered if the icon is, otherwise the behavior that the text alignment follows is somewhat strange.

The expected behavior should be that the text does not align according to an Icon that isn't there. It should align to the Left or Right of the button walls, ignoring the icon, given that the icon will be centered and therefore behind the text.

**Note**: I've created this Issue after #80385, which shows similar UI problems involving CheckBox and CheckButton.

### Steps to reproduce

1. Create Button
2. Set Icon to button. Any will do, such as placeholder texture.
3. Set Icon Alignment to Center. (Node Properties -> Button -> Icon Behavior -> Icon Alignment)
4. Set Text Alignment to Left or Right. (Node Properties -> Button -> Text Behavior -> Alignment)

The text will align as if the icon was aligned Left or Right, respectively with the text. However, there is no icon there, and instead just a blank space of the same dimensions. The icon is instead centered behind the text.

### Minimal reproduction project

[Button_Text_Bug.zip](https://github.com/godotengine/godot/files/12283440/Button_Text_Bug.zip)

**Comment by Rindbee** [comment]
I feel it is necessary to point out that Text Overrun Behavior is not "Trim Nothing" or Clip Text is enabled.
