### ISSUE TITLE
GLES3: Color.WHITE or Color(1, 1, 1, 1) is black when used inside _draw() function

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#80396]
### Godot version

4.1.1-stable

### System information

Windows 10

### Issue description

this will draw black rect

```gdscript

func _draw():
	draw_rect(Rect2i(Vector2i.ZERO, img.get_size()), Color(1, 1, 1, 1), false)

func _draw():
	draw_rect(Rect2i(Vector2i.ZERO, img.get_size()), Color.WHITE, false)

```

![image](https://github.com/godotengine/godot/assets/53877170/dda910f2-e767-47bf-b3f9-7d194fcc7085)

while this will draw white rect

```gdscript

func _draw():
	draw_rect(Rect2i(Vector2i.ZERO, img.get_size()), Color(0.99, 1, 1, 1), false)

```

while this is weird but making circle draws Color(0.99, 1, 1, 1) makes also the _draw_rect to get fixed!

![image](https://github.com/godotengine/godot/assets/53877170/e84862be-0652-49ee-a5f9-435a234bd354)
 

### Steps to reproduce

use Color.WHITE inside any _draw() function or Color(1, 1, 1, 1) and it will draw black color instead of white color

### Minimal reproduction project

N/A

**Comment by WhalesState** [comment]
using one more draw method after the draw_rect method makes it gets fixed! so the issue happens only on the first draw call when the color is white

![image](https://github.com/godotengine/godot/assets/53877170/089c856d-123b-4d3e-b582-f96901167508)

**Comment by WhalesState** [comment]
Hint for tracking the issue:

it works with no issue inside `MainScreenEditorPlugin`, this issue only appears after running the game.

**Comment by clayjohn** [comment]
Can you please upload an MRP so that other users can try to reproduce this issue without having to fully recreate your test project from scratch?

**Comment by AThousandShips** [comment]
Could be blending related, as your image is full of `Color(0, 0, 0, 0)` the blending with the alpha could cause this

**Comment by WhalesState** [comment]
I hid the Image and used the same line on node2d, same result, also have tried to move it one pixel far from the image, nothing was working, the issue happens only when the rect size is -1 but when i change to 1 or greater it draws white color
![image](https://github.com/godotengine/godot/assets/53877170/e59f001a-2861-411e-b74d-d0aa9eb47529)

**Comment by AThousandShips** [comment]
Please provide an MRP:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by WhalesState** [comment]
> Could be blending related, as your image is full of `Color(0, 0, 0, 0)` the blending with the alpha could cause this
> 
> Also I cannot replicate this on 4.2.dev from just these instructions

did you try those line in 4.2.dev ?

func _draw():
	draw_rect(Rect2i(Vector2i.ZERO, img.get_size()), Color(1, 1, 1, 1), false)

func _draw():
	draw_rect(Rect2i(Vector2i.ZERO, img.get_size()), Color.WHITE, false)

**Comment by AThousandShips** [comment]
Yes I tried them, didn't cause your issue, so please provide an MRP to make this possible to test

**Comment by WhalesState** [comment]
> Yes I tried them, didn't cause your issue, so please provide an MRP to make this possible to test

can you change the renderer to gles3 and try again ? most of issues appears cuz it seems most of the tests was done using vulkan only.

**Comment by AThousandShips** [comment]
I used compatibility, I followed your steps as I said

**Comment by WhalesState** [comment]
then it may have been fixed already in 4.2, i will provide a test scene just to make sure it was fixed then you can close the issue ^^

**Comment by WhalesState** [comment]
closing since it was produced because of running an unreviewed code that was not merged. sorry again -_-

**Comment by WhalesState** [comment]
fixed this issue already in another pull request! you can reproduce the issue only when you build with Vulkan disabled and use only gles3, will link this issue to the pull request

![image](https://github.com/godotengine/godot/assets/53877170/71ce5649-93ea-48dd-9bca-1e89668c5b20)

**Comment by AThousandShips** [comment]
Can you please confirm it outside a custom build and on either `master` or some stable branch, both times you have had this happen when on custom builds

**Comment by WhalesState** [comment]
am afraid i can't because I do the fixes on github online vscode space, but i can explain why the issue happens when we disable Vulkan renderer

when we use white color in the first draw function, those two checks will not update the polygon buffer color inside Gles3, while any other color will do it because the color will not be equal (1.0, 1.0, 1.0, 1.0), remember when i said that using (0.99, 1.0, 1.0, 1.0) draws white ?
![image](https://github.com/godotengine/godot/assets/53877170/209eeda3-0a9e-43b4-be76-1dbbfa9eb3f4)

and to fix this i have updated the gl vertex color to be white by default instead of black, because the check will not update the gl vertex color when the color is white as shown in the previous image.
![image](https://github.com/godotengine/godot/assets/53877170/094ba80d-46c6-45bd-88b1-265c1f70ff5f)
