### ISSUE TITLE
Minor Issue - Tooltips are not Reactivating Correctly Upon Hover Over new Items in the Tree Control (Node and Filesystem Panes)

### ISSUE THREAD

**Issue by jtwine** [godotengine/godot#80398]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.14.7311) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

In the _Inspector_ tab the tooltip continuously tracks the mouse position and resets once it is no longer over the rect for the control that a tooltip is currently being shown for, and awaits a new hover event to be shown again for a new control.  This also behaves similarly in the _History_ tab.

However, in the _Node_ tab, the tooltip is not reset once the mouse leaves the rect of the underlying tree item and will continue to show the old/incorrect content even though the user has moved to something else.  You have to move the mouse outside of the _Node_ tab's tree control's rect and then back in again in order to get a new, refreshed tooltip.

This might be an issue with the tree control being used if it is not generating hover events correctly (or however it works internally) because the tree control used on the _Filesystem_ tab has similar behavior.

The tooltip should respond to new hover events as they are generated from the tree control (or respond to the mouse being moved over the rect of a new item) and refresh with new content without having to leave the client area of the entire tree control.  

This should be possible because the tree control used on the _Scene_ pane _kinda-sorta-almost_ works as expected: if you move to another item, the tooltop does not immediately update, but seems to wait for a new hover event and then is updated.  Not perfect, but definitely better than how the _Node_ pane's tree behaves.

N.b. - although this issue talks about multiple panes, and the recreation scenario also uses multiple panes to demonstrate the differing behaviors, I believe the problem is with the underlying tree control itself, which I believe qualifies as the **one bug** discussed in this issue: **Tooltips do not work correctly in the tree control**.

### Steps to reproduce

In Godot, select any Node in the _Scene_ pane and go to the _Node_ tab.  Hover over an item in the _Node_ pane's tree control and them move the mouse to another item and hover.  The tooltip will not update to reflect the new item being hovered over.

Now activate the _Inspector_ pane and try again.  On this pane, the tooltip updates as you move to different items on that pane.

Try those steps again with the tree on the _Filesystem_ pane and again with the tree on the _Scene_ pane and notice the different behaviors.

### Minimal reproduction project

N/A

**Comment by JustusPan** [comment]
exactly same issue here. this problem will cause the review of asset info in FileSystem quite hard and tedious.
