### ISSUE TITLE
Handling Player Desktop Resolution

### ISSUE THREAD

**Issue by grabiller** [godotengine/godot#804]
Currently in Godot, we have to choose a pre-determined resolution for our games. On PC platforms this leads to an issue where you render your game at a higher resolution than the player screen resolution. For instance if you choose 1920x1080 for your game and the player has a 1280x720 or 1600x.. screen, it would be display with stretch mode, but it would also be a big waste of resources.

What we would need to address this kind of situations is to have at least two functions:
- one for querying the player desktop resolution
- another another one so we can change the project settings -> display -> width/height at runtime (or at least at boot time).

This way we could choose the appropriate resolution for the game and use the "fullscreen" option without the need (at least on Windows) to change the player screen actual resolution (which most players do not like).

**Comment by akien-mga** [comment]
> one for querying the player desktop resolution

```OS.get_screen_size()```

> another another one so we can change the project settings -> display -> width/height at runtime (or at least at boot time).

```OS.set_window_size( Vector2 )```
