### ISSUE TITLE
Visual Scripting broken on latest builds?

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8040]
I noticed that having a visual script attached to any node, even if it doesn't contain any complicated logic, will cause the game window to close immediately after running the project without any error messages in the debugger. This must be a new issue, since i remember visual script working just fine a couple of weeks back.

Steps to reproduce:
1. create a new project and add a node to it
2. attach a visual script to it and add some logic (or none at all)
3. run the project

**Comment by algorev** [comment]
Seen on MacOS el capitan 10.11.6

**Comment by Hinsbart** [comment]
Can't reproduce this anymore, so seems fixed.

**Comment by novemberist** [comment]
Can't even try to reproduce this, because the new "Multiscript"-Entry in the latest build won't let me create a new Vscript and i can't select the "visual script" entry directly. I tried an older project with an existing visual script and I'm getting the same behavior as before (project window closing instantly)

**Comment by akien-mga** [comment]
> Can't even try to reproduce this, because the new "Multiscript"-Entry in the latest build won't let me create a new Vscript and i can't select the "visual script" entry directly.

cc @karroffel

**Comment by novemberist** [comment]
@Hinsbart I dont't think this is fixed. I just compiled a fresh built of godot master (with multiscript disabled for testing purposes) and can still reproduce this. I also haven't seen any commits lately, that would have adressed this issue. I'm appending my console output here:
```

running: /opt/godot-bin/godot3 -path /home/alex/Godot/vs_test -rdebug localhost:6007 -epid 16925 -p 0x0 res://Node2D.tscn
ERROR: load: No loader found for resource: res://test.vs
   At: core/io/resource_loader.cpp:213.
ERROR: poll: res://Node2D.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://test.vs
   At: scene/resources/scene_format_text.cpp:182.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:144.
ERROR: load: Failed loading resource: res://Node2D.tscn
   At: core/io/resource_loader.cpp:213.
ERROR: start: Failed loading scene: res://Node2D.tscn
   At: main/main.cpp:1460.
shit?: Connection reset by peer
ERROR: read: Server disconnected!

   At: drivers/unix/stream_peer_tcp_posix.cpp:275.

```

**Comment by karroffel** [comment]
@novemberist can you test if VS was broken before the MultiScript PR as well?

**Comment by novemberist** [comment]
@karroffel I can't test it right now, but I am pretty sure that it was, since I've been testing visual script regularly ever since i opened this issue back in march and it hasn't worked ever since.

**Comment by eon-s** [comment]
Found this between lot of spam, trying on windows a build before multiscript

```
path not recognized
ERROR: No loader found for resource: res://visualscript.vs
```

**Comment by vnen** [comment]
Seems like it's still broken and not related to the MultiScript PR.

**Comment by novemberist** [comment]
Awesome. Thank you very much.
