### ISSUE TITLE
The API to create a trimesh collision shape is confusing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8041]
Creating collision shapes in 3D works the same as in 2D, except when it comes to trimesh collisions (aka mesh colliders).

The only way I found to produce a collider from a generated Mesh / tool is to call `MeshInstance.create_trimesh_collision()`, which returns nothing, and generates a StaticBody as child of the node, supposedly at last position. If the mesh changes, the node has to be found and `queue_free`d so `create_trimesh_collision` has to be called again to recreate them. It leads to code like this https://github.com/Zylann/godot_terrain_plugin/blob/master/addons/zylann.terrain/terrain_chunk.gd#L12

While it looks easy at first glance, it feel confusing and limited compared to what I was used to in 2D.
Instead of having to forcibly use a helper, I thought I could do something like:

```gdscript
var body = StaticBody.new()
var shape = TrimeshShape.new()
shape.set_mesh(mesh)
body.set_shape(shape)
parent.add_child(body)
```

In Unity it works the same, by simply assigning a Mesh to a MeshCollider.

But there is no TrimeshShape, but Concave and Convex polygon shapes. I understand they mostly are per-case optimized choices, but they are hard to deal with (they also require raw faces instead of a Mesh). Does it mean one or the other are built with the helper too?

The main things I don't like is that I'm forced to create a MeshInstance to create a mesh collider, that I'm unable to choose where the nodes go, and that I have to destroy and recreate them if I want to modify the mesh (assuming I can tell them apart).
It also makes it difficult if you need a high-poly MeshInstance with a low-poly collider.

**Comment by kubecz3k** [comment]
Guess it would be good to change this api before 3.0, as 3.0 is good release to break backward compatibility :)

**Comment by tagcup** [comment]
Having access to [`Mesh::create_trimesh_shape`](https://github.com/godotengine/godot/blob/master/scene/resources/mesh.h#L180) from GDScript should allow doing [it](https://github.com/godotengine/godot/blob/master/scene/3d/mesh_instance.cpp#L200) manually, right?

**Comment by tagcup** [comment]
That function is public already, but somehow, functions with `Ref<>` return values aren't exposed to GDScript?
