### ISSUE TITLE
Normal and motion vector debug views are broken in a particular project

### ISSUE THREAD

**Issue by DarioSamo** [godotengine/godot#80416]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 Ti (NVIDIA; 31.0.15.3640) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

While testing the project attached on #67287 (and re-attached here) I noticed the debug views for normal and motion vectors are broken. While the contents themselves are correct, the view seems to be broken up in an odd way.

This issue does not happen on any other projects I tested and it's still present in the latest `master` as of eca6f0eb545166708c56633152974f40f51de2be. I haven't investigated further into the cause of the issue yet or what particular setting is enabled in this project that causes it.

The problem is also visible during runtime if the script forces the debug view, not just the editor. This is not a high priority issue that will affect most end users but it did make debugging the project a bit harder.

![image](https://github.com/godotengine/godot/assets/538504/e2cffcb6-a763-4608-895f-285045a88f43)

### Steps to reproduce

- Open the **Perspective** menu
- Open the **Display Advanced...** option
- Toggle **Normal Buffer** on

### Minimal reproduction project

[Multimesh.Flicker.Godot4.Beta2.zip](https://github.com/godotengine/godot/files/12291795/Multimesh.Flicker.Godot4.Beta2.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/62955 (8× MSAA is used in the MRP linked here).
