### ISSUE TITLE
When scene is reloaded after changing instance, ViewportTextures break

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#80417]
### Godot version

4.2 eca6f0e

### System information

Windows 10 x64

### Issue description

https://github.com/godotengine/godot/assets/2223172/a2796263-4e2e-4b14-a080-b3ad034cc141

### Steps to reproduce

1. Add SubViewport
2. Add Sprite2D
3. Set spirte's texture to ViewportTexture
4. Create new scene
5. Instance the new scene inside the scene with viewport
6. Make sure both scenes are opened
7. Go to instance scene and save it
8. Go to viewport scene

You will see error spam. Reloading the scene fixes it.

### Minimal reproduction project

[vip.zip](https://github.com/godotengine/godot/files/12292386/vip.zip)

**Comment by YuriSizov** [comment]
Again? 😩 Well I guess it's between you (https://github.com/godotengine/godot/pull/75751), @Rindbee (https://github.com/godotengine/godot/pull/77209, https://github.com/godotengine/godot/pull/78728), and maybe @RandomShaper if it's related to RID and core more than the editor.

**Comment by KoBeWi** [comment]
> Again?

This seems like new bug, different from all other issues (though not sure if it's a regression or something old).

**Comment by Rindbee** [comment]
Similar to #79176. But with different messages.

**Comment by KoBeWi** [comment]
When I originally encountered the issue there was no errors about bindings (only the `Viewport Texture must be set to use it.` part). They appear only in the MRP for some reason.

**Comment by Rindbee** [comment]
If you make the Sprite2D outside the visible area, the error message just outputs `Viewport Texture must be set to use it.`

**Comment by mikatomik** [comment]
Not sure if it's related, but I'm currently struggling with Viewport Texture as well.

I'm using a SubViewport to render a ColorRect with a shader on it. The SubViewport texture is being fed to the UI theme to be used in a SyleboxTexture. It works great, then sometimes it will start throwing errors.

Here, you can see I get the ViewportTexture error as above even though it is set?
![image](https://github.com/godotengine/godot/assets/109499937/505371ad-90c4-48aa-89f5-6ff4544be391)

But then sometimes without even changing anything, just launching and closing the project, I get this instead:
![image](https://github.com/godotengine/godot/assets/109499937/81bb7dac-f721-403b-9371-a5d0fcbd35cb)

And the way that I've discovered to "fix" it is to go to the StyleboxTexture, unassign the ViewportTexture, then reassign it. Then it works fine for the next 5 minutes.

![image](https://github.com/godotengine/godot/assets/109499937/0e518410-e5b5-4a2a-8acd-2bc4a8296908)
![image](https://github.com/godotengine/godot/assets/109499937/84466e4d-0b3d-42a3-b583-412cb9d0058f)

(Yes, the background says mountain dew. I was testing a shader and needed a quick logo and was thirsty lmao)

**Comment by Rindbee** [comment]
@mikatomik Can you provide an MRP?  You seem to provide a `ViewportTexture` through the editor, and get one directly through the code. 

> But then sometimes without even changing anything, just launching and closing the project, I get this instead: ![image](https://user-images.githubusercontent.com/109499937/259382546-81bb7dac-f721-403b-9371-a5d0fcbd35cb.png)

`viewport_path` is `.`, which seems a bit strange. Unless the scene root node is a `Viewport`.

**Comment by mikatomik** [comment]
> @mikatomik Can you provide an MRP?  You seem to provide a `ViewportTexture` through the editor, and get one directly through the code. 
> 

Yeah, I should have removed that before posting the screenshot, I was trying to set it in code and see if it made a difference versus setting it in the editor. I saw on another viewport troubleshooting thread that some people fixed their issues by assigning in code.

I do not have an MRP on hand, but I can see if I can replicate it in one this evening.

Also, the root node in my scene is a CanvasLayer. The SubViewport is a direct child of that, and sibling to the GUI that's using it.
