### ISSUE TITLE
Godot errors when generating LOD for a too big GLB file

### ISSUE THREAD

**Issue by janosdebugs** [godotengine/godot#80431]
### Godot version

4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 Threads)

### Issue description

When loading [this GLB file](https://github.com/janosdebugs/godot-glb-import-issue/blob/main/grass.zip), Godot crashes without any error message. (ZIP-ed for file size reasons.)

When loading Godot in debug mode, the following error is issued:

```
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2060 SUPER

ERROR: Condition "!_ptrnew" is true. Returning: ERR_OUT_OF_MEMORY
   at: resize (./core/templates/cowdata.h:297)
```

However, according to the resource monitor Godot doesn't consume anywhere near the 64 GB of RAM in this machine:

![image](https://github.com/godotengine/godot/assets/86970079/6ed1b9c9-576e-405c-9044-9aeed567da88)

The GLB has 2.7M vertices, which loads without problems in other 3D engines.

### Steps to reproduce

Drag the attached GLB file into any Godot project.

### Minimal reproduction project

None necessary, but included [here](https://github.com/janosdebugs/godot-glb-import-issue).

**Comment by fire** [comment]
I haven't inspected the file yet, but when the byte count exceeds the 32 bit length limit godot fails to load the binary.

**Comment by aaronfranke** [comment]
The crash is in the LOD generator. I opened a PR to replace the crash with a warning: #80467

**Comment by fire** [comment]
Fixed by: https://github.com/godotengine/godot/pull/80467
