### ISSUE TITLE
[3.0] Mouse cursor stuck in "resizing" icon when the mouse exits window border

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8043]
Tested on Godot master 3ceefab232604b09d3fff843c24a13e99f50912b
Windows 10 64 bits

Repro steps:
1) Open Editor Settings (or any other resizeable editor window)
2) Move the mouse to a border, see it changes to a resizing icon
3) Move the mouse away from the window: notice the cursor stays a resizing icon (wrong behaviour).
4) Click outside of the window: notice the cursor becomes normal again

When doing 3), I expected the mouse to go back to a normal pointer.

**Comment by akien-mga** [comment]
Duplicate of #7622.
