### ISSUE TITLE
Can't get method name from named lambda

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#80434]
### Godot version

4.2 f7bc653

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

`get_method()`:
```
Returns the name of the method represented by this Callable. If the callable is a lambda function, returns the function's name
```
However calling it on a named lambda results in
```
Can't get method on CallableCustom "test(lambda)".
```
(ironically the error even contains the function's name...)

`get_method()` in GDScriptLambdaCallable is likely unimplemented or is wrong. It should work for named lambdas.

### Steps to reproduce

```GDScript
var fun = func test(): pass
print(fun.get_method())
```

### Minimal reproduction project

N/A

**Comment by ElMikosch** [comment]
I want to try to fix this bug if nobody minds

**Comment by akien-mga** [comment]
Feel free to give it a try!

The relevant class is https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_lambda_callable.h, which is an implementation of https://github.com/godotengine/godot/blob/master/core/variant/callable.h#L134

It seems not to implement the virtual `get_method` indeed.
