### ISSUE TITLE
Renaming a unique-name node with its own name in the editor gives an error message

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80438]
### Godot version

4.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-08-09_07.02.43.webm](https://github.com/godotengine/godot/assets/71937306/37e25ff0-d697-4d21-95ef-c53465dcd833)

### Steps to reproduce

1. make a node uniquely named
2. rename it with its own name

### Minimal reproduction project

any

**Comment by arkology** [comment]
Already fixed in 4.2dev.
