### ISSUE TITLE
Do not repeat the fate of Unity! (Compatibility violation)

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot#80449]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

I like your engine, but I am shocked at the state of the engine versions that you call RELEASE, experimental features that break backwards compatibility, a video player that is generally added for the sake of formality, and much more.

Godot favorably differed from the unity in that he could work with a multi-thread regularly, without additional gestures.
Now, starting with 4.1, I have to smear all my call_defered code, which is extremely ugly and inconvenient.
It also breaks backwards compatibility with 4.0.
And, since this feature of the engine is marked as experimental, it would be nice to be able to turn it off.

I chose the title not by chance, it's in the style of Unity to make some kind of feature and release it still unfinished, breaking compatibility, without the possibility of turning it off. This greatly spoils the impression of the engine!

Thank you!

### Steps to reproduce

Open any project, add a node and access it from another thread.

### Minimal reproduction project

"N/A"

**Comment by AThousandShips** [comment]
This is not a bug report, don't make statements in issue reports, this is for bug reporting

**Comment by Calinou** [comment]
You can disable messages related to SceneTree thread safety using `Thread.set_thread_safety_checks_enabled(false)`. However, this can hide the cause of bugs in your cause, so using it is not recommended. Only report a bug *after* removing that particular line code, so that thread-safety checks are enabled.

**Comment by Hromon** [comment]
@YuriSizov 
I have a project written on 4.0.4 that works great without any problems, but on 4.1.1 it crashes due to calls from another thread.

**Comment by Zireael07** [comment]
@Hromon: You should have made a MRP and an issue related to your precise project, not a vague "compatibility violation" thing

**Comment by Hromon** [comment]
@Zireael07 Maybe it's not in my particular project if we get the same problems when moving from ANY project from 4.0 to 4.1?

**Comment by clayjohn** [comment]
Could you write a proper bug report? It sounds like you may be running into a bug that hasn't been reported.

**Comment by AThousandShips** [comment]
Make sure to add an MRP and specific details, and open it as a new report instead of reopening this one

**Comment by YuriSizov** [comment]
Followed up with https://github.com/godotengine/godot/issues/80455
