### ISSUE TITLE
Renaming functions in VisualScript doesn't work. (3.0)

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8045]
Right now you can not rename user created functions in Visual Script through the UI. Renaming them in the "Members:" dialog makes them uneditable in the graph editor and trying to rename them in the resource tab in the inspector doesn't really seem to do anything.

steps to reproduce:
1. create a visual script
2. hit "+" to create a new function
3. try to rename "new_function"

**Comment by reduz** [comment]
this is fixed now
