### ISSUE TITLE
Tilemap animation for different frames separation

### ISSUE THREAD

**Issue by punsie** [godotengine/godot#80454]
### Godot version

Godot_v4.1-stable_win64

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I am working with many types of atlases for tilemaps and while some have ordered tiles, some do not have a constant separation between them and here's where the problem appears. I cannot give the same separation for these tiles because they re not ordered in a way I could select them as frames with a constant separation between them.
When I change the separation it affects past frames too.

![tilemap_animation_2](https://github.com/godotengine/godot/assets/20566000/1836d262-72f9-4427-92a7-6c73626a3789)
I think a better approach would be to give atlas coordinates for frames? I think this would solve this bug and also make it more user friendly when trying to animate?

### Steps to reproduce

Example tilemap with different separations between tiles

### Minimal reproduction project

-

**Comment by KoBeWi** [comment]
Sounds like this proposal?
https://github.com/godotengine/godot-proposals/issues/7290

**Comment by punsie** [comment]
You're right! Sorry for that.
Duplicate of this proposal https://github.com/godotengine/godot-proposals/issues/7290
