### ISSUE TITLE
Errors and crashes when accessing godot objects from another thread

### ISSUE THREAD

**Issue by Hromon** [godotengine/godot#80455]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

I have a LuaState that runs on its own thread, it generates commands and accesses godot objects.
The problem is that when working on 4.0 everything works fine, except for the video player, but more on that later. When switching to version 4.1.1, I catch a lot of errors that the call is not safe, followed by a crash. Although I repeat, everything works fine on 4.0.

The reason for the transition was a bug with the video player.
When switching quickly (we are talking about an interval of 1-2 frames), the godo crashes without logs. Although the reason became clear to me immediately, but it is difficult to do something about it.

### Steps to reproduce

Create a 4.0 project with a call from another thread.
Move it to 4.1.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide an MRP to make this easier to test, as instructed

**Comment by Hromon** [comment]
> Please provide an MRP to make this easier to test, as instructed, to ensure that others actually can confirm your issue (as I have had no problem with crashes for this context)

Now it is not convenient to do it, only if tomorrow.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you upload an MRP this can be reopened
