### ISSUE TITLE
Resizing CSG nodes using the editor handles while holding ctrl doesn't scale them and snaps back to last value

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#80453]
### Godot version

Godot 4.1

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) R7 Graphics (Advanced Micro Devices, Inc.; 27.20.1034.6) - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

When scaling a CSG node using the editor handles while holding ctrl key, it doesn't scale and snaps back to its last saved value. (as shown in the video). It works sometimes when i drag mouse and release both mouse button and ctrl key at the same time, but not always. 

https://github.com/godotengine/godot/assets/94475453/34a5ee85-b9fb-4a8f-8217-5c93a72705e9

### Steps to reproduce

- Add Any CSG Node in the scene
- Try to scale the csg node using the in-editor handles while holding ctrl.
- It will snap back to its last value and will not scale or sometimes scale but snaps back

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Your video is from 4.0.4, but you're mentioning 4.1, can you try 4.1.1?

**Comment by AdilDevStuff** [comment]
> Your video is from 4.0.4, but you're mentioning 4.1, can you try 4.1.1?

its actually happening with all 4.X builds, i have tried 4.1, 4.0.4, 4.1.1 and some beta builds as well

**Comment by rayzorite** [comment]
real jhoot bol rha ye

**Comment by underscorerx** [comment]
can confirm this didn't work in 4.0 and persists in 4.1.2

**Comment by Calinou** [comment]
Can you reproduce this in 4.2.1? The CSGBox resizing code was remade to resize from one side only unless you hold <kbd>Alt</kbd>.

**Comment by AdilDevStuff** [comment]
Its working fine now after 4.2!
