### ISSUE TITLE
GDScript: No autocomplete when overriding user-defined functions

### ISSUE THREAD

**Issue by FractalDiane** [godotengine/godot#80469]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3179) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Autocomplete does not seem to work when overriding a parent class's function in a user-made script. I seem to remember this working in Godot 3, but I don't recall it working for any version of Godot 4 I've tried.

![image](https://github.com/godotengine/godot/assets/3895119/430c5fb7-1ecb-427e-aef5-d84abd9284c7)
![image](https://github.com/godotengine/godot/assets/3895119/62c1ac37-6e36-4492-88d4-e915b0b8ac76)

### Steps to reproduce

1. Create the following script:
```gdscript
class_name BaseClass
extends Node

func _virtual_function() -> void:
    pass
```

2. Create the following second script:
```gdscript
class_name DerivedClass
extends BaseClass
```

3. In the second script, type `func _` and see that autocomplete does not suggest `_virtual_function` from the parent class in the list. Typing more also does not suggest it.

### Minimal reproduction project

[autocomplete.zip](https://github.com/godotengine/godot/files/12308866/autocomplete.zip)

**Comment by KoBeWi** [comment]
This is a missing feature and was never supported.
Proposal: https://github.com/godotengine/godot-proposals/issues/5896
