### ISSUE TITLE
Tiny spelling error in NavigationAgent2D Tooltip

### ISSUE THREAD

**Issue by hunterbk** [godotengine/godot#80468]
### Godot version

4.1.stable.mono

### System information

Godot v4.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3203) - Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/36772761/abe5ab98-cf16-4839-b6d1-c6c5129e0fa7)
Path desired distance has a small spelling mistake in the tooltip, it uses "too" instead of "to"

https://github.com/godotengine/godot/blob/master/doc/classes/NavigationAgent2D.xml
Line 183

### Steps to reproduce

Go into the engine
Make a NavigationAgent2D Node
Hover over the field "Path Desired"
Read the info and notice the mistake
Cheer because you're contributing to making Godot Engine a better place, one o at a time

### Minimal reproduction project

N/A

**Comment by sepTN** [comment]
How about 

"If this value is set too high, the NavigationAgent will skip points on the path, which can lead **_to_** leaving the navigation mesh **_altogether_**."

**Comment by harshitkandpal** [comment]
Hi i am eager to work on this issue please assign to me

**Comment by AThousandShips** [comment]
This is already worked on, see the linked issue
