### ISSUE TITLE
Zstandard compression library

### ISSUE THREAD

**Issue by silverkorn** [godotengine/godot#8047]
Greetings!

I'm just raising a flag about an interesting (de-)compression library that could optimize any operations using compression features:

[Zstandard](https://github.com/facebook/zstd) from Facebook (BSD-licensed), see their comparison in their `README.md`.

I'm not sure about the platform portability but it deserves a quick check. 😄

**Comment by Calinou** [comment]
They do say Zstandard is not really suited to small data compression (unless you train it beforehand), probably making it less than ideal for network compression (we already support range coder, FastLZ and zlib compression for the high-level multiplayer API).

**Comment by reduz** [comment]
network compression for games is difficult, due to packet loss being
normal.
right now godot uses enets range coder, which works better than anything
else for small things

**Comment by silverkorn** [comment]
I totally see your point from the networking and small data perspective but I think it could be a good option for the `.pck` files.

Is it preferred to focus on one library to all (de-)compression operations?

**Comment by reduz** [comment]
Many godot (and third party) file types require seeking, so zipping all the
pck will make loading slower. Binary scenes are zipped and most other file
types have compression so gain is not much overall anyway

**Comment by silverkorn** [comment]
Alright! Feel free to close the ticket if you don't see much fit in the project.
Thanks!

**Comment by silverkorn** [comment]
Apparently it has been added by @tagcup (https://github.com/godotengine/godot/commit/f177c1534757973063f244450df063def879d7db).
Closing this!
