### ISSUE TITLE
Innacurate get_pixel (GDScript) vs texture (shader) reading

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#80477]
### Godot version

4.1.stable.official

### System information

Windows 10

### Issue description

Doing a simple terrain displacement with a simple PNG file, the resulting displacement on shader is one, the heightmap done for it using get_pixel on the same PNG gives another result so the collisions don't match with the terrain displacement at all.
Oddly enough, changing the loaded file from a PNG to a generated noise works normally.

![bad_geometry](https://github.com/godotengine/godot/assets/106078/9d26bb9c-3dbe-48d7-9b85-b8dc3e839074)
![good_geometry](https://github.com/godotengine/godot/assets/106078/062c4ee0-7037-4d04-aeeb-24f852d7e75c)

### Steps to reproduce

I uploaded the project folder, but basically:

Shader:
```c++
void vertex() {
	float world_height = texture(heightmap, UV).r * height_level;
	
	VERTEX.y = world_height;
}
```

GDScript:
```gdscript
var material = mesh_instance_3d.get_surface_override_material(0)
var texture = material.get("shader_parameter/heightmap")
var height_level = material.get("shader_parameter/height_level")
var heightmap_image = texture.get_image()
var image_size = Vector2(heightmap_image.get_size())
	
...

for y in verts:
	for x in verts:
		...
		var height = heightmap_image.get_pixelv(pos * image_size).r * height_level
		points.append(height)
collision_shape_3d.shape.map_data = points
```

### Minimal reproduction project

[get_pixel_inaccurate.zip](https://github.com/godotengine/godot/files/12310758/get_pixel_inaccurate.zip)

**Comment by bitsawer** [comment]
You need to remove `source_color` from this shader line:

`uniform sampler2D heightmap: source_color, filter_linear_mipmap, repeat_enable;`

If you have `source_color` enabled, the color read from the texture can go through SRGB to linear conversion which will affect the values.

Correct look after removing `source_color`:

![pixel](https://github.com/godotengine/godot/assets/22456603/9ab1d4ad-2f01-4ba0-90ac-a54d310fe3a7)
