### ISSUE TITLE
simple svg file improperly rendered

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80483]
### Godot version

4.1

### System information

linux

### Issue description

Godot doesn't render this file correctly.

```svg
<?xml version="1.0"?>
<svg width="110" height="110">
	<path fill-rule="evenodd" fill="#ffffffff" d="M 0 0 L 0 110 110 110 110 0 z M 50 50 L 60 50 60 60 50 60 z " />
	<path fill="none" stroke="#000000ff" stroke-width="8" d="M 46 46 L 60 46 60 60 46 60 z " />
</svg>
```

| drawn by editsvgcode.com, vectr.com, gimp, my image viewer, etc.                                                 | imported in godot                                                                                   |
|-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| ![image](https://github.com/godotengine/godot/assets/71937306/e748c1b2-18a2-4cdb-8257-119b48536229) | ![image](https://github.com/godotengine/godot/assets/71937306/9dc242f9-756f-4832-975f-218b9535e28a) |

It's a bit strange because krita doesn't import it properly either, but in a way different than godot :thinking: although that's of course totally unrelated.

### Steps to reproduce

- import the provided file in godot
- notice how it differs from what  [editsvgcode.com](https://editsvgcode.com/) (or your image viewer) draws.

### Minimal reproduction project

Paste above content in an svg, or download it: ![cell.svg](https://github.com/godotengine/godot/assets/71937306/012721d5-a390-4687-9bdb-363e1a5a4305)

**Comment by AThousandShips** [comment]
It doesn't open correctly in my browser, so I think this file is broken and it's not an issue with the engine, possibly the engine not being lenient and accepting it
