### ISSUE TITLE
Vulkan Mobile error with OpenXR at Scale 1: "Draw command lacks indices, but pipeline format does not use vertices"

### ISSUE THREAD

**Issue by adammikulis** [godotengine/godot#80493]
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

When I open my OpenXR mobile project in 4.2.dev3 I get the error 

> "Draw command lacks indices, but pipeline format does not use vertices". 

The 3D Viewport is completely black when this error is going. The error disappears and 3D Viewport works again as soon as scaling (both bilinear and FSR) are changed to anything other than 1. It only happens when Project Settings > Rendering > Scaling 3D > Scale == 1

This error also disappears when switching to the Foward+ renderer. I tried to see if disabling OpenXR Shaders would fix things but it crashes the editor and makes a project unopenable. This occurs with the base Godot XR Template (which is what my XR project is based on).

Additionally, at the beginning of opening the project there will be several errors when loading various scripts from the godot-xr-tools addon: 

> Failed to load script "res://addons/godot-xr-tools/functions/movement_sprint.gd" with error "Compilation failed".

This may have been introduced by the fix in: https://github.com/godotengine/godot/pull/80368

### Steps to reproduce

Open the [OpenXR template](https://github.com/GodotVR/godot-xr-template) and set renderer to Mobile

### Minimal reproduction project

[Open XR Template](https://github.com/GodotVR/godot-xr-template)

**Comment by BastiaanOlij** [comment]
Let me have a look, I must have forgotten a condition where a 4-subpass framebuffer doesn't work. Thats the problem with the catch-all solution we had, hides multiple problems...

**Comment by BastiaanOlij** [comment]
OK, turns out to have been #80311, @darksylinc missed one tiny change :)

**Comment by adammikulis** [comment]
I'm glad that I could help find an issue and thank you for being so responsive!
