### ISSUE TITLE
Can't set font size in themes for BMFont/Angelcode fonts (.fnt)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#80497]
### Godot version

4.1

### Issue description

The **Normal/Bold/Italic/Bolt Italic/Mono Font Size** options under **Theme Override > Font Sizes** do not appear to have any effect for `.fnt` Angelcode/BMFont bitmap fonts.

Same for outlines and probably some other theme font settings, but that makes more sense.

### Steps to reproduce

1. Use `.fnt` type font
2. Try to increase font size
3. Nothing changes

**Comment by Calinou** [comment]
I can confirm this on 4.2.dev 16a93563b (on https://github.com/godotengine/godot-demo-projects/pull/849).

**Comment by bruvzg** [comment]
Why is this an issue? Bitmap fonts can have only one size, and usually are pixel art fonts not intended for scaling.

**Comment by Calinou** [comment]
> Bitmap fonts can have only one size, and usually are pixel art fonts not intended for scaling.

Fonts displayed with filtering enabled can be freely scaled up and down, although they will look blurry when upscaled and pixelated when downscaled (if mipmaps aren't enabled on the texture). That said, this is also an issue when using the `canvas_items` stretch mode with a window size different than the base resolution. So I don't think it's that much of a problem for non-pixel art fonts.

For pixel art fonts, it's OK to scale them if using a size that is an integer multiple of the original size. We already document this caveat on the Using fonts page, so I think it would be fine to support scaling for pixel art fonts as well.

**Comment by mhilbrunner** [comment]
> Why is this an issue? Bitmap fonts can have only one size, and usually are pixel art fonts not intended for scaling. Besides this, a lot of bitmap fonts do not have size information, so there's no clear way to tell how exactly "size" property should affect them. Adding some sort of scaling with size will likely result in a lot of confusion and incorrectly scaled fonts.

As Calinou outlines, I expected to be able to (up)scale pixel art fonts at least by even integers or powers of two or something. Even if results are not optimal, for prototyping that is still better than the theme size options plainly doing nothing. :)

**Comment by bruvzg** [comment]
It should be easy to enable scaling, but we should avoid the situation when user set custom font, but not font size, and it is auto-scaled (most people will likely expect it to use correct font size automatically).
