### ISSUE TITLE
Couldn't compile on Yosemite.

### ISSUE THREAD

**Issue by llhbadboy** [godotengine/godot#805]
➜  godot git:(master) ✗ scons platform=osx
scons: Reading SConscript files ...

scons: warning: EnsureSConsVersion is ignored for development version
File "/Users/Alex/Dev/godot/SConstruct", line 1, in <module>
sh: i586-mingw32msvc-gcc: command not found
sh: i686-w64-mingw32-gcc: command not found
scons: done reading SConscript files.
scons: Building targets ...
g++ -o platform/osx/os_osx.osx.tools.32.o -c -g3 -Wall -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -DFREETYPE_ENABLED -arch i386 -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DAPPLE_STYLE_KEYS -DUNIX_ENABLED -DGLES2_ENABLED -DGLEW_ENABLED -DOSX_ENABLED -DMUSEPACK_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/osx -Itools/freetype -Itools/freetype/freetype/include -Iplatform/osx/vorbis platform/osx/os_osx.mm
couldn't understand kern.osversion `14.0.0'
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:55,
                 from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:12,
                 from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:80,
                 from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12,
                 from platform/osx/os_osx.mm:29:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected `}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected `}' before '__attribute__'
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414: error: expected unqualified-id before '=' token
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:481: error: expected declaration before '}' token
scons: *** [platform/osx/os_osx.osx.tools.32.o] Error 1
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
Assuming it has been fixed due to the age of the report.
