### ISSUE TITLE
HingeJoint3D has wrong inspector unit type.

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#80505]
### Godot version

4.1

### System information

Win10

### Issue description

The unit is meters per second, rather than radians per second.
![image](https://github.com/godotengine/godot/assets/38119387/08d0e7b4-c741-4bf8-9066-f8b8aac37c6d)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The new hint should be:
U"-200,200,0.01,or_greater,or_less,radians,suffix:\u00B0/s"

Assuming it is correct that it is an angle

**Comment by akien-mga** [comment]
To be clear as there's some confusion in the linked PRs, most angles in the API are in radians in code, but exposed to the inspector to be edited in degrees. IIRC this is done using the (confusingly named) `radians` hint.

But to be sure about what this should be like, the code should be checked to see what it does with the value.

**Comment by AThousandShips** [comment]
By testing it does indeed seem to be in radians, I'd suggest adding the `radians` hint to make it more useful, assuming it does not change the value
