### ISSUE TITLE
skybox render issue

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#8050]
skybox draws very ugly gradients. it can be easily checked by creating a gradient (even 2048 of size) and applying it as skybox. it will have very obvious transitions between steps (much more noticeable then it should be). enabling hdr does not help tho.
![gradient](http://i.imgur.com/ZXzI2vC.png)
and this thing also results in strange lightning.
![cube](http://i.imgur.com/EgLj90k.png)
레이 쿠파 - from discord looked at the source of drawing procedure and said that it really needs reviewing.

**Comment by Zylann** [comment]
I noticed the same color artifacts when I enabled shadows:
![image](https://cloud.githubusercontent.com/assets/1311555/24083495/f54b7c5c-0cd7-11e7-9093-a331d1caff9f.png)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
I can't see this anymore with SSAO.

**Comment by kubecz3k** [comment]
@Zylann cool, thanks for checking!
