### ISSUE TITLE
Some Control Type not auto translate when enable auto_translate

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#80549]
### Godot version

v4.2.dev2.official [da81ca62a]

### System information

window10 64bit

### Issue description

I'm create a translate file like this:
![image](https://github.com/godotengine/godot/assets/35988767/e6e027af-bd39-48fa-9e84-6c28685f503d)

And coding like this:
![image](https://github.com/godotengine/godot/assets/35988767/bc8252d9-6997-4c85-9c3b-2631a26d45b2)

And enable all Control's `Auto Translate` property:
![image](https://github.com/godotengine/godot/assets/35988767/568b7375-f26d-466f-9099-be3ed26192dc)

Then I found some Control Type (Tree, GraphNode) not translated.
![image](https://github.com/godotengine/godot/assets/35988767/7a0352b9-f4d3-4920-af25-a6bdfbcdce68)

### Steps to reproduce

/

### Minimal reproduction project

[NewTest.zip](https://github.com/godotengine/godot/files/12327503/NewTest.zip)

**Comment by KoBeWi** [comment]
The translated controls are internal controls of the node. `auto_translate` only affects the main node, not its internal children.
We should make `auto_translate` propagate to internal nodes (probably by making it virtual and manually setting it).

**Comment by YeldhamDev** [comment]
@akien-mga The `GraphEdit` instance is fixed, but the `Tree` one isn't. Looking into the code, its items aren't taken into account on translation changes.
