### ISSUE TITLE
Wrong Axes. When scale Quad in 3.0

### ISSUE THREAD

**Issue by sezit** [godotengine/godot#8054]
**Operating system or device - Godot version:**
Windows 10 Godot 3.0

**Issue description:**

Small issue, all objects have orientation XYZ but Quad XZY. When you scale, you will see a problem :3

**Comment by tagcup** [comment]
Can you be more specific, maybe post an example project?

**Comment by sezit** [comment]
lol, sorry its was late night and i think its bug or something different. Its my bad, all work good.
