### ISSUE TITLE
Control Tree range slider not working (also affects input action deadzone editor)

### ISSUE THREAD

**Issue by Drarch** [godotengine/godot#80556]
### Godot version

4.1.1-stable_win64

### System information

Windows 10

### Issue description

Range cell within Tree control not update when using slider.

Also it would be nice, if I could  change few settings for range mode:
1. Visibility of slider. Not always is necessery.
2. Visibility of spin box. As above
3. Slider theme variant. Now it takes default variant, but I would want to set dedicated variant for it.
4. Turn off context menu under RMB. Editable cells in general. Not only range

### Steps to reproduce

1. Create Tree control
2. Add TreeItem. Set it's cell in range mode and editable
3. Run scene. Try to change value of cell using slider.

### Minimal reproduction project

[TreeRange.zip](https://github.com/godotengine/godot/files/12327982/TreeRange.zip)

**Comment by Calinou** [comment]
> Also it would be nice, if I could change few settings for range mode:

Please open a [proposal](https://github.com/godotengine/godot-proposals) for this, with detailed rationale on why you need these properties/theme items to be exposed.

**Comment by BlueCube3310** [comment]
This can be partially fixed by modifying the `value_editor_changed` function in tree.cpp 
from
```cpp
text_editor->set_text(String::num(c.val, Math::range_step_decimals(c.step)));
```
to
```cpp
line_editor->set_text(String::num(c.val, Math::range_step_decimals(c.step)));
```

Doing this fixes the range issue with most trees, but the one in the action editor still doesn't work as the window gets unfocused and the 
```cpp
if (!popup_edited_item) {
	return;
}
```
condition is met, so the function returns prematurely.
