### ISSUE TITLE
App Menu missing the quit item so my application has been reject by Mac App Store !

### ISSUE THREAD

**Issue by TrueMisterJeanP** [godotengine/godot#8055]
**Operating system or device - Godot version:**
MacOS Sierra  - Godotengine 2.1.2

**Issue description:**
My application build with Godoengine 2.1.2 is refused by Mac App Store. The reason the menu bar does not conform with apple applications because it lacks the quit menu.

How to fix it ? Thank you.

<img width="1440" alt="capture" src="https://cloud.githubusercontent.com/assets/26481111/24038142/76dd727c-0b00-11e7-9ad3-bf3727dc1c6d.png">

Mail from Apple:
------------------------
Before you Submit
The user interface of your app is not consistent with the OS X Human Interface Guidelines. Specifically:
We found that the App Menu is missing the quit item.
Next Steps
Please revise your app to address all instances of this type of issue.
------------------------

**Steps to reproduce:**
Send app to Apple.

**Comment by TrueMisterJeanP** [comment]
Here is an example of an application menu with the quit item accepted by apple in its Mac AppStore.
This is what godotengine is missing.

![quit_item](https://cloud.githubusercontent.com/assets/26481111/24075516/49a8db7a-0c1d-11e7-9bb2-4928919f609b.png)
![windows_menu](https://cloud.githubusercontent.com/assets/26481111/24075517/52217cf8-0c1d-11e7-8264-7afd5276b20a.png)

**Comment by lexum0** [comment]
@TrueMisterJeanP do you have information on publishing to the Mac App Store? I'm having problems with running the engine on an Xcode project for archiving and publishing

**Comment by kubecz3k** [comment]
This should be fixed now since https://github.com/godotengine/godot/pull/9812 was merged. Let us know if the issue still persists.
