### ISSUE TITLE
Blender file import doesn't support emmission strength

### ISSUE THREAD

**Issue by ColormaticStudios** [godotengine/godot#80563]
### Godot version

4.0.3.stable.official.5222a99f5

### System information

Debian 11

### Issue description

When I import a Blender file into Godot, it resets the emission strength of the shader to 1. In blender I have a light source that is supposed to illuminate the whole room, but in Godot it only lights up itself and a few inches around it.

### Steps to reproduce

Create a very simple scene in blender with a mesh as a light source (use an emission material).
Set the emission value to properly light up the whole room.
Import the scene into Godot using the built in scene importer.
Notice how the light is not as bright as it is in Blender.

### Minimal reproduction project

N/A, should be really easy to re-create.

**Comment by clayjohn** [comment]
This requires a GLTF extension to work. Support was added in https://github.com/godotengine/godot/pull/78621 which means that this issue will be fixed in 4.2. 

Closing as fixed by https://github.com/godotengine/godot/pull/78621
