### ISSUE TITLE
Download and install export templates?

### ISSUE THREAD

**Issue by ShashankaNataraj** [godotengine/godot#8056]
Im on OSX el captain

**Issue description:**

In https://github.com/godotengine/godot/issues/1105, the link in godot engines post redirects to the main github page itself, it isnt accessible anymore.

**Steps to reproduce:**
1. Go to Export -> Android
2. fill in path to adb, debug.keystore
3. Im getting 

<img width="315" alt="screen shot 2017-03-17 at 3 30 51 pm" src="https://cloud.githubusercontent.com/assets/650317/24038275/bcb203be-0b26-11e7-9a38-a20dad982f1b.png">

when I try to export to android. I searched for this info on the wiki as well but to no avail. How do I go about downloading the export template and installing it?

**Comment by akien-mga** [comment]
Try the download page :) https://godotengine.org/download

See also http://docs.godotengine.org/en/stable/tutorials/asset_pipeline/exporting_projects.html#export-templates

**Comment by Calinou** [comment]
What about adding a clickable link to https://godotengine.org/download in the error, with steps on how to install export templates as well?

**Comment by Hinsbart** [comment]
@Calinou or maybe even add the ability for the editor to download the templates by itself.

**Comment by akien-mga** [comment]
> or maybe even add the ability for the editor to download the templates by itself.

That's the plan already for 3.0.
