### ISSUE TITLE
Usability when saving positioned branch as new scene

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#80560]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

While prototyping it may happen, that a positioned node, e.g. an obstacle, should be saved as scene to reuse it. While doing so one still want's to preserve the position of the original obstacle in the level. 
After saving the branch to a scene, the root node is offset in the new scene. For reusability most often the root node should be positioned at zero. When setting the position in the new scene, the position in the original level changes and one needs to reposition the obstacle.

### Steps to reproduce

- create scene A
- add a `Node2D`
- change the position of the node
- save the node 2d as new scene
- reset the position to zero in the new scene
- the node is now positioned at zero in the original scene as well

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Another problem with the current behavior, which often annoys me, is that when you create a scene with shifted origin and then decide to reset it to 0, your original instance will be moved, because it's using the default value of the position. Resetting the position automatically is a good idea.
