### ISSUE TITLE
Provide Windows installers for the Godot editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#8057]
Windows installers will allow for a better out-of-the-box user experience, providing things such as start menu entries, easier installation and uninstall procedures, built-in export templates, registering file associations and more.

Possible candidates for this are:

- [NSIS](http://nsis.sourceforge.net/Main_Page)
- [Inno Setup](http://www.jrsoftware.org/isinfo.php)
- MSI package (the "official" Windows installer system)

Export templates may or may not be bundled (it will make the installer size grow significantly). They could also be downloaded in the installer, if the user chooses to install them.

As a bonus, we could also provide guidance or scripts for packaging Godot projects in Windows installers.

**Comment by Calinou** [comment]
After some experimentation, I'm mostly convinced by InnoSetup - it's easy to set up, and the installer works well. Uninstalling works flawlessly as well, and users can opt in and out of desktop icon and start menu entry creation.

Once I get around to updating my [unofficial builds](https://archive.hugo.pro/godot/), I will include Windows installers made using InnoSetup as the recommended option for Windows users.

**Comment by tomuxmon** [comment]
I beg a pardon for interruption. But in my humble opinion [Wix Toolset](http://wixtoolset.org/) is a way to go if you need MSI. I have some experience with it and I love it. In windows community it is considered de facto tool for that purpose. I could help prepare MSBuild scripts if you would pick Wix Toolset.  :)

**Comment by vnen** [comment]
This would be great to have for 3.0, it would add familiarity layer to Windows users. It seems not hard to make and maintain, should be easy to update for each release.

**Comment by tomuxmon** [comment]
Ok I have played a bit with WIX (after some long time 😄 ). I have prepared minimalist script in my [repo](https://github.com/tomuxmon/godot.msi). It appears you are actually not forced to use MSBuild and can instead use CLI tools directly. 
To go forward (if that is needed) I need directions. 
* Should *godot.exe* be installed in program files folder (requires elevated permissions) or in app data folder. 
* What shortcuts are required. Start menu shortcut , desktop shortcut or both.
* Should export templates be included and how. 

To my understanding WIX allows bundling more then one MSI in a single bootstrapper in a [Bundle](http://wixtoolset.org/documentation/manual/v3/xsd/wix/bundle.html) / [Chain](http://wixtoolset.org/documentation/manual/v3/xsd/wix/chain.html) / [MsiPackage](http://wixtoolset.org/documentation/manual/v3/xsd/wix/msipackage.html) combination.. 
Further MsiPackage allows supplying DownloadUrl so basically your installer boostrapper could be like 1 meg and instead download stuff on demand. But ALAS I have not played with that yet..

**Comment by vnen** [comment]
Answering the points:

* IMO installing in AppData with self contained mode is the most useful option.
* Both desktop and start menu (I guess it can be an option for the user, right?)
* No export templates. The user can download and install with the editor interface.

**Comment by tomuxmon** [comment]
I have updated my [repo](https://github.com/tomuxmon/godot.msi) a bit. 
* Resulting msi installs under *..\AppData\Local\Godot*
* Both shortcuts are included
* Editor is launched after install

So far there is no UI whatsoever. I think there is no need so far. Unless install path configuration or icon preference is really needed.

If we need UI after all, I could include [default Wix toolset UI](http://wixtoolset.org/documentation/manual/v3/wixui/wixui_customizations.html), but then we would need to replace (supply) default bitmaps (or use default scary red discs 😄).

**Comment by Hinsbart** [comment]
@tomuxmon cool, can you also make it register the *.godot project files with the editor?

**Comment by tomuxmon** [comment]
It seems [it is possible](https://www.firegiant.com/wix/tutorial/getting-started/beyond-files/), but I am not sure if it does not require elevation. will test tomorrow.

**Comment by tomuxmon** [comment]
It is well possible in per user install 😀. But with obvious limitations: *.godot files will be opened with Godot editor only for current use; file association can not be [advertised](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367548(v=vs.85).aspx) (most probably not relevant);
Check my repo if you want to test build msi.
Do you guys see anything else needed?

**Comment by Calinou** [comment]
I've tested your installer locally (with several installs and uninstalls), it works well, some comments:

- An installer containing a 28.8 MB binary compresses down to 10.5 MB in the `.msi` file. In comparison, placing the binary in a `.zip` file compresses it down to 12.5 MB. This makes the download smaller, which is always nice to see.
- The installer is quite long to create (about 17 seconds here), but is very fast to install (about 1 second). End users don't have to create installers anyway, so this is probably fine.
- Uninstalling works well and is fast (about 1 second here too).
- No administrator rights are required for installation (which is a good thing).
- The start menu entry is located in `%APPDATA%\Microsoft\Windows\Start Menu\Programs`, which works fine for user-wide start menu entries.
- The actual Godot binary is located in `%LOCALAPPDATA%\Godot`, which makes sense for user-wide installation.
- The project manager automatically starts as soon as Godot is installed. This is a bit strange, but these days, I see more and more programs (such as Atom) doing this, so I guess it's fine.
- The icon should be supplied with 256² and 128² variants as well. This is easy to do (and adds about 80 KB to the icon file), just modify the icon sizes passed to ImageMagick. This way, the desktop icon looks good even when it's huge and on hiDPI displays (and it also removes the border around the icon in Add/Remove Programs):

![hidpi_huge_desktop_icon](https://user-images.githubusercontent.com/180032/27176362-827440d0-51c2-11e7-99b7-80865d47a96a.png)

I suggest not using the self-contained mode, as `%APPDATA%` is the standard location for user data. If users have trouble finding it, we can add a button in the editor to open the user data location in a file manager (which is very easy to do, using `OS.shell_open()`).

**Comment by vnen** [comment]
My suggestion for self-contained mode is mostly for the possibility of installing multiple versions. I guess it might not be really needed.

One question: how does updates works with this installer? Can a new installer be ran and automatically update?

**Comment by tomuxmon** [comment]
@vnen The most precious [Product](http://wixtoolset.org/documentation/manual/v3/xsd/wix/product.html) UpgradeCode is used to identify installer package (and item in add/remove programs). So if you have for example version 3.0.0 installed and you run 3.0.1 or later msi, older version will be uninstalled first (with all components that included the msi).

So when building production msi you have to settle down on your GUID and NEVER change it. If you want to have side by side installs you just change UpgradeCode and you basically have new product (chnaging name too would help user a bit..).

**Comment by vnen** [comment]
I'm using @Calinou's installers, but I do miss an actual wizard. The thing runs to fast and closes on its own. If it weren't for Godot open right afterwards, it would seem as it didn't work.

**Comment by tomuxmon** [comment]
I can add default UI (with possibility to opt out when building?). I will need images to replace defaults (mentioned in defaul WIX UI link). Currently I am in military service and will be awailable after one week.

-----Pradinis laiškas-----
Nuo: "George Marques" <notifications@github.com>
Išsiųsta: ‎2017-‎07-‎22 05:17
Kam: "godotengine/godot" <godot@noreply.github.com>
Kopija: "Tomas Dambrauskas" <tomuxmon@gmail.com>; "Mention" <mention@noreply.github.com>
Tema: Re: [godotengine/godot] Provide Windows installers for the Godoteditor (#8057)

I'm using @Calinou's installers, but I do miss an actual wizard. The thing runs to fast and closes on its own. If it weren't for Godot open right afterwards, it would seem as it didn't work.

**Comment by Calinou** [comment]
After using [Inno Setup](http://www.jrsoftware.org/isinfo.php) with the Godot editor, it turns out to be a decent solution as well, especially since it can be run in WINE, allowing for compiling *and* packaging Godot for Windows from Linux (using MinGW), unlike the WiX Toolset which currently doesn't run in WINE.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
