### ISSUE TITLE
High polling-rate mouse movement causes stuttering/hitching/FPS-drops

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#80583]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3699) - AMD Ryzen Threadripper 3970X 32-Core Processor (64 Threads)

### Issue description

I've attached a video of the issue:
https://github.com/godotengine/godot/assets/7411742/ae9c6f4c-bdf5-491d-ba10-ac61d05cf2f4

High-polling rate mouse inputs seem to cause Godot to freeze/stutter/hitch/drop FPS randomly. My video included a smoothing node and look-at sprites for the sake of clearly demonstrating the issue, but I can replicate it by simply shaking my mouse with nothing on the screen. Going from 1000HZ mouse input to 125HZ makes the issue go away, so it seems reasonable that it has to do with the polling rate.

I saw there was an old bug already tracking this: #57599 

But using `Input.use_accumulated_input = true` does not fix it for me, so I think this is a different issue.

### Steps to reproduce

- Create a sprite that moves left/right and have a camera attached to it
- Shake the mouse with 1000HZ polling rate
- There is intermittent stuttering
- Set mouse polling rate to 125HZ and repeat mouse shaking
- There is no stuttering

### Minimal reproduction project

[MouseStutteringIssue.zip](https://github.com/godotengine/godot/files/12328920/MouseStutteringIssue.zip)

**Comment by yoont4** [comment]
I've also found that running multiple instances highlight the issue even further. The weird thing being that the _**active**_ window is what gets the most frame hitching, whereas the out-of-focus windows (which are still tracking input!) are running smoothly.

In this video, you can see that the active window is stuttering insanely compared to the non-focused window, and it switches as I change window focus.
https://github.com/godotengine/godot/assets/7411742/4d02c4b7-fea6-48c8-ad90-38248ebc86d5

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/60646.

**Comment by yoont4** [comment]
No problem, been really enjoying using Godot so far!

One thing to note on my bug and #60646, it seems they are hitting frame drops when V-Sync is turned ON, but in my case it is worsened when V-Sync is OFF. Just wanted to clarify. Could be related to mine being a 4.x issue and there's being on 3.x.

**Comment by IneedHelp** [comment]
Sorry to bump this, but as of now
_Godot Engine v4.4.1.stable.mono.official.49a5bc7b6 - https://godotengine.org
Vulkan 1.4.303 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 2080 Ti_

the issue still exists. Is there a fix for this?

**Comment by Zireael07** [comment]
https://github.com/godotengine/godot/pull/109639, in which you commented too, is a proposed fix

**Comment by IneedHelp** [comment]
@Zireael07 yes, I found that a bit later, but I don't understand how to implement the proposed fix. The export template executable crashes if I try to use it in my own project (I'm not even sure if that's what I'm supposed to do), and I was trying to get some clarification there.
