### ISSUE TITLE
CollisionShape3D Shape Size handles missing when Script editor floating

### ISSUE THREAD

**Issue by tomellwood-github** [godotengine/godot#80588]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 30.0.15.1295) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

When undocking the script editor so that it's floating, CollisionShape3D Shape Size handles stop working.

If they were visible on a Shape, they remain visible on that shape and still work for that shape; but they will not appear on any other collision object when selecting it.

If you launch the editor with the Script panel already in a floating state, no shape handles ever become visible.

If you dock the Script editor again, everything goes back to normal and works fine.

### Steps to reproduce

Create a 3D scene with some collision shapes.
Undock the Script editor

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
I can help with this bug if no one has started working on it.
