### ISSUE TITLE
.gdextension is not loading if compatibility_minimum mentions patch version

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#80590]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

The .gdextension file tells Godot how to connect with the gdextension executable.
Here `compatibility_minimum` is used to support the execution backwards compatibility.

Most times it is set to the major and minor version x.x
I noticed when changing it to the patch version x.x.x, the following error occurs.
`Failed loading resource: res://bin/icospheremesh.gdextension. Make sure resources have been imported by opening the project in the editor at least once.`

### Steps to reproduce

open atached project
open bin/icospheremesh.gdextension
change "compatibility_minimum = 4.1"  to "compatibility_minimum = 4.1.1"

Try setting Meschinstance3D/Mesh to IcoSphereMesh

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/12329615/demo.zip)

**Comment by AThousandShips** [comment]
Compatibility is not supposed to ever be broken within a minor version, so there's no reason to have a minimum compat for 4.1.1, so this sounds like something that needs to be documented clearly, or handled gracefully

**Comment by AThousandShips** [comment]
The MRP contains only a windows debug version, and no source for the plugin, this makes it very hard to test, please provide an MRP which can be built or provide more platforms

**Comment by Gallilus** [comment]
Here is the source for the Extension.
https://github.com/Gallilus/icospheremesh-gdextension
Sorry, I have not built for other platforms.

**Comment by AThousandShips** [comment]
Does it work if you put the version in quotes?

**Comment by AThousandShips** [comment]
This seems to be caused by the incorrect parsing of `4.1.1` as a float, changing to using `"4.1.1"` should fix the issue, please confirm
