### ISSUE TITLE
InputEventShortcut, ERROR: Condition "shortcut.is_null()" is true. Returning: "None"

### ISSUE THREAD

**Issue by 1xch** [godotengine/godot#80623]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - Vulkan (Forward+) 

### Issue description

Run in Debug (F5), loads and shutdown with no message

On inspection through stepping through will get this on InputEventShortcut.new():

ERROR: Condition "shortcut.is_null()" is true. Returning: "None"
   at: to_string (core/input/input_event.cpp:1781)

It is just returning a String "None", a quick glance shows no gdscript binding func for in InputEvent.cpp, but I don't know. Is it removed, deprecated, do I need to implement my own or what. My first time using InputEventShortcut.

### Steps to reproduce

Run in Debug (F5) where somewhere calling InputEventShortcut.new()

### Minimal reproduction project

not applicable

**Comment by 1xch** [comment]
For anyone who has stumbling on this: InputEventShortcut seems to be deprecated, inactive, or incomplete

**Comment by AThousandShips** [comment]
It's not deprecated, inactive, or incomplete, the issue is that the method to render it in the inspector causes an error because the shortcut is invalid at that point

**Comment by Sauermann** [comment]
I have tried to replicate this issue in v4.2.dev.custom_build [bc88dca17] (on Debian Linux)
I was unable to cause the error-message with this MRP: [ShortcutTest.zip](https://github.com/godotengine/godot/files/12479607/ShortcutTest.zip)

@1xch please provide more detailed steps of how to reproduce this issue and also a minimal reproduction project.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
