### ISSUE TITLE
Certain unicode surrogate pair emoji are not recognized

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#80621]
### Godot version

4.2.dev

### System information

MacOS

### Issue description

These emoji are not recognized correctly by `Button`, `Label`, `TextEdit` or `RichTextLabel`. They do render correctly in the editor, however:

U+2764 U+FE0F U+200D U+1F525 ; 13.1 # ❤️‍🔥 heart on fire
U+2764 U+FE0F U+200D U+1FA79 ; 13.1 # ❤️‍🩹 mending heart
U+0023 U+FE0F U+20E3 ; 0.6 # #️⃣ keycap: #
U+002A U+FE0F U+20E3 ; 2.0 # *️⃣ keycap: *
U+0030 U+FE0F U+20E3 ; 0.6 # 0️⃣ keycap: 0
U+0031 U+FE0F U+20E3 ; 0.6 # 1️⃣ keycap: 1
U+0032 U+FE0F U+20E3 ; 0.6 # 2️⃣ keycap: 2
U+0033 U+FE0F U+20E3 ; 0.6 # 3️⃣ keycap: 3
U+0034 U+FE0F U+20E3 ; 0.6 # 4️⃣ keycap: 4
U+0035 U+FE0F U+20E3 ; 0.6 # 5️⃣ keycap: 5
U+0036 U+FE0F U+20E3 ; 0.6 # 6️⃣ keycap: 6
U+0037 U+FE0F U+20E3 ; 0.6 # 7️⃣ keycap: 7
U+0038 U+FE0F U+20E3 ; 0.6 # 8️⃣ keycap: 8
U+0039 U+FE0F U+20E3 ; 0.6 # 9️⃣ keycap: 9

They do render if a smiley face precedes them in the text string, so it appears to be a bug in the unicode surrogate parsing.

![Screenshot 2023-08-14 at 9 37 24 AM](https://github.com/godotengine/godot/assets/33969780/dd0d894b-492c-4499-b3c4-792f8ace4dcf)

### Steps to reproduce

See MRP.

### Minimal reproduction project

[emoji_rendering_bugs.zip](https://github.com/godotengine/godot/files/12336048/emoji_rendering_bugs.zip)

**Comment by AThousandShips** [comment]
Does your font contain these emoji?

**Comment by Calinou** [comment]
Godot uses system fonts as a fallback, but support depends on the OS: https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#using-emoji

**Comment by bruvzg** [comment]
The editor directly includes default system emoji fonts as a fallback. Project use automatic fallback, so this should be an issue with auto fallback.

**Comment by Koyper** [comment]
Here's a running project with the complete set - you can see only the mentioned emoji fail to render. The failing ones are all available in the OS. By-the-way, this is brilliant that this works in Godot 4 so well already!

![Screenshot 2023-08-14 at 10 01 28 AM](https://github.com/godotengine/godot/assets/33969780/911a40c0-1d78-4284-b6cd-d7265aab8fc3)

**Comment by Koyper** [comment]
@bruvzg Is there a `String` method that can return characters whereas an emoji is handled as a single character rather than a compound unicode? For example, simply to find how many emoji's are within a given string? This is related to how in `TextEdit`, it can take multiple caret shifts to cross certain emoji's.

Also, can the filter type currently applied to fallback system emoji be set somewhere? Godot emoji are slightly blurry as compared to the natively displayed emoji on MacOS.

**Comment by bruvzg** [comment]
> Is there a String method that can return characters whereas an emoji is handled as a single character rather than a compound unicode?

No, but I take a look at implementing it, it should be possible to do with ICU.

The issue itself can be fixed by using a full script run to search for fallback (currently it's using first char to select font, that's why it's not working with multichar emojis), but this need to be tested to make sure it works with the strings that require multiple fallback fonts on all systems. So detecting a composite icon and using only it might be a better solution.

```diff
diff --git a/modules/text_server_adv/text_server_adv.cpp b/modules/text_server_adv/text_server_adv.cpp
index b92082ee1b..85d7087384 100644
--- a/modules/text_server_adv/text_server_adv.cpp
+++ b/modules/text_server_adv/text_server_adv.cpp
@@ -5444,7 +5444,7 @@ void TextServerAdvanced::_shape_run(ShapedTextDataAdvanced *p_sd, int64_t p_star
 		// Try system fallback.
 		RID fdef = p_fonts[0];
 		if (_font_is_allow_system_fallback(fdef)) {
-			String text = p_sd->text.substr(p_start, 1);
+			String text = p_sd->text.substr(p_start, p_end - p_start);
 			String font_name = _font_get_name(fdef);
 			BitField<FontStyle> font_style = _font_get_style(fdef);
 			int font_weight = _font_get_weight(fdef);
```

**Comment by Koyper** [comment]
Can project emoji font fallback also be set to use the default system emoji like the editor? The rendering works correctly if I set the font to the system emoji font, in this case `Apple Color Emoji`, but then we have to set for every platform.
