### ISSUE TITLE
Sprite 3D doesnt work with Viewport texture on android.

### ISSUE THREAD

**Issue by KeiMuriKoe** [godotengine/godot#80636]
### Godot version

4.1.1

### System information

Windows 10, Godot 4.1.1 Latest, Vulkan API 1.3.206 - Forward Mobile. 

### Issue description

I was trying to make ProgressBar for 3d Object. I used Sprite3D with SubViewPort as a texture. In edit page it works correctly, in run page too. After exporting to android device its not. It works not only with ProgressBar, with all textures to sprite3D with SubViewPort as a texture.

### Steps to reproduce

1. Create godot(4.1.1) project Mobile.
2. Add 3D Node and any 2d stuff, for ex, ColorRect, u can choos button, progressbar, sprite2d etc.
3.Join it as a child to SubViewport
4.Create Sprite3D and pick texture to it as SubViewport, and choose SubViewport with 2d stuff as a child.
5.place camera 3D so when u run scene u can see our 2d stuff in 3d space.
![image](https://github.com/godotengine/godot/assets/106619492/4c7ea961-20e8-4ff6-ad0a-2168ab7e780c)
![image](https://github.com/godotengine/godot/assets/106619492/51c27be8-1928-4b72-938d-0bcf2bae9659)

6. As we can see, all works properly. Then export it to android, and check. We see nothing.

### Minimal reproduction project

-

**Comment by KeiMuriKoe** [comment]
[git_issue.zip](https://github.com/godotengine/godot/files/12339347/git_issue.zip)

UPD : Minimal reproduction project

**Comment by Calinou** [comment]
What device model did you test this on? Can you reproduce this after switching the rendering method to `gl_compatibility` in the Project Settings (specifically for the `.mobile` override)?

**Comment by KeiMuriKoe** [comment]
> What device model did you test this on? Can you reproduce this after switching the rendering method to `gl_compatibility` in the Project Settings (specifically for the `.mobile` override)?

android 13. Google Pixel 7 pro. And yes, i reproduce this on Compatibility. And Still...

**Comment by EIREXE** [comment]
after testing, it appears like viewport update mode `VIEWPORT_UPDATE_WHEN_VISIBLE` is the cause of the issue, switching it to `VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE` fixes the issue, is this a bug or an intentional design?

**Comment by KeiMuriKoe** [comment]
> after testing, it appears like viewport update mode `VIEWPORT_UPDATE_WHEN_VISIBLE` is the cause of the issue, switching it to `VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE` fixes the issue, is this a bug or an intentional design?

Yeah, you right switching to VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE helped. Intuitively, it's not clear because with the VIEWPORT_UPDATE_WHEN_VISIBLE mode enabled in the viewport (which is the default setting), everything appears to be working correctly, but after rendering, it's not the case. But in principle, yes, the issue was indeed with this.
