### ISSUE TITLE
AnimationPlayer seek() does not skip Call Method Track Keys

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#80640]
### Godot version

4.1.1 stable 4.2. dev3

### System information

Win 10

### Issue description

[seek()](https://docs.godotengine.org/en/stable/classes/class_animationplayer.html?rtd_search=add_color_override#class-animationplayer-method-seek) is supposed to skip the keys inbetween current Timestamp and it's argument value Timestamp.

When playing an Animation in the AnimationPlayer which has a Call Method track key somewhere in the middle section for example, and then the user tries to "skip" that middle section using `seek()`, the Call Method track keys in the middle section are still handled, even though animation has skipped the middle section and the `update` argument is `false`.

So it basically behaves like [advance()](https://docs.godotengine.org/en/stable/classes/class_animationplayer.html?rtd_search=add_color_override#class-animationplayer-method-advance) should behave.
However, advance also does not behave as it should, since it advances further than it should and when setting Update in the seek() method to `true`, the Call Method track key is actually called twice!

### Steps to reproduce

Create an AnimationPlayer Animation of 5 seconds,
Add a script with two functions: One to seek(4.0) and another one to print("hi")
Add a Call Method Track and at Timestamp second 1.0 add a key to the seek() method and on Timestamp 2.5 add a key to print().
Play the scene and observe "hi" being printed
![image](https://github.com/godotengine/godot/assets/47016402/41f6dab0-9af6-46cd-95f1-e680a398e6af)

Set seek(4.0, true) to enable Update (like in advance method), and observe "hi" being printed twice!
Maybe related: https://github.com/godotengine/godot/issues/76773

### Minimal reproduction project

4.2. dev3 (issue is the same in 4.1.1 stable)
[animation_seek_bug.zip](https://github.com/godotengine/godot/files/12340066/animation_seek_bug.zip)

**Comment by rt9391** [comment]
4.2.1.stable is still bugged.
![image](https://github.com/godotengine/godot/assets/91177204/c5bba49a-47fb-4444-86b9-f9c6c49ab1f5)
![paseuresumbug](https://github.com/godotengine/godot/assets/91177204/8148a70e-eb18-4f19-9cbd-8b4edc952cfb)
#86147

**Comment by golddotasksquestions** [comment]
I can also still replicate this in Godot 4.2.1 stable.

**Comment by AThousandShips** [comment]
Please open a new issue for this as it's likely a different bug so should be tracked on it's own
