### ISSUE TITLE
Offline Debugging/Inspector

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#8064]
**Operating system or device - Godot version:**
Windows 10 x64

**Issue description:**

No remote inspector support when offline. Not very helpful when your not connected.

**Steps to reproduce:**
turn of internet connection.

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
@vonflyhighace2 Can you mention your Godot version?

**Comment by eon-s** [comment]
Remote inspector works fine here, at least on 2.1.2, Win 10 x64.

Maybe your firewall is blocking Godot?

**Comment by Zylann** [comment]
Maybe similar to #5828?

**Comment by vonflyhighace2** [comment]
@bojidar-bg I'm on 2.1.2 official. Without a Internet connection I can never get the debugger to work. Is the remote debugger online only? Be weird if it was.

**Comment by efornara** [comment]
See #7544 and #8179

**Comment by akien-mga** [comment]
Duplicate of #7544.
