### ISSUE TITLE
When dragging node scene on open blank node window entire engine crashes

### ISSUE THREAD

**Issue by Xedoes** [godotengine/godot#80655]
### Godot version

4.0 stable

### System information

linux arch manjaro

### Issue description

After dragging an scene file on empty node scene entire engine crashes

### Steps to reproduce

Honesty it would be better for engine to not crash

### Minimal reproduction project

the files i mentioned was ending with .tscn

**Comment by rsubtil** [comment]
Can't reproduce the issue. Can you submit a MRP and/or record this behavior happening? Also try launching godot from the terminal to check the backtrace.
