### ISSUE TITLE
Some editor fields don't accept comma as a decimal separator

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#80664]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

Most numerical fields in editor like inspector properties and settings accept comma as input (eg. `5,5` gets parsed to `5.5`). However, there's some inconsistency in this support. Color picker doesn't support this and also Input Map's deadzone fields.
![comma](https://github.com/godotengine/godot/assets/1621768/ce2aa211-5b13-4cec-82c5-b8aec3b30e0c)

### Steps to reproduce

Open any color picker in inspector or Input Map settings, try to input value like `0,5` in it.

### Minimal reproduction project

Any project

**Comment by Calinou** [comment]
Accepting commas as decimal separator was special-cased in EditorSpinSlider, but not SpinBox: https://github.com/godotengine/godot/pull/42376

This is because valid Expressions may contain commas, such as `pow(2, 16)` = `65536`.

**Comment by aXu-AP** [comment]
Nice to hear that there's some reasoning behind this. Your suggestion sounds like win-win. Using keyboard layout (finnish here) where numpad has comma, not period, I always end up filling these field twice - first with comma, only then notice the mistake. I'm infinitely grateful that inspector parses commas also 👍
