### ISSUE TITLE
.gltf & .dae & .fbx & .glb Disappear on phones without snapdragon chipset.

### ISSUE THREAD

**Issue by sopdevv** [godotengine/godot#80668]
### Godot version

4.1 & 4.1.1 * 4.2 dev3

### System information

Windows 10, AMD Ryzen 7 5700X 8-Core Processor, 3070

### Issue description

I have a wired problem in my game, any Chipset except **Snapdragon** have problems in rendering my character, the character disappears or glitch.

It happens when closing the game and starting it again, and cannot be fixed until deleting the game from the phone and installing it again.

This is the game, if you have a phone with a Mediatek chipset or Exynos you can try it and see the error by yourself: https://play.google.com/store/apps/details?id=org.godotengine.OnlyUpLite

I tried exporting it with Godot 4.1 & 4.1.1 & 4.2 dev3, and I tried all of the Godot renders backends, and even I tried changing some of the import settings of the model.

the entire game is fine only the player model has this issue, when I changed it with a box from the same engine it doesn't disappear, so it's only the imported model problem (it's an FBX model, and I tried also .gltf & .dae & .fbx & .glb)

the only format that worked it's .obj, but I want the **ANIMATIONS !!** 

https://github.com/godotengine/godot/assets/96385910/38a472c2-e44c-45dd-ba38-b26c2b7c4b80

![image](https://github.com/godotengine/godot/assets/96385910/038aa4d8-8f0e-42f0-b3b3-2955b7a67c0b)

### Steps to reproduce

1- import any .gltf & .dae & .fbx & .glb to Godot.
2- make a simple scene and put the imported model.
3- export it for android

### Minimal reproduction project

the file is big so i upload it to wetransfer.

https://we.tl/t-rDOMe3R5sn

**Comment by Calinou** [comment]
> [we.tl/t-JVtZUokNM](https://we.tl/t-JVtZUokNM)

That link doesn't appear to work.

**Comment by sopdevv** [comment]
@Calinou updated the link

**Comment by sopdevv** [comment]
@Calinou I tried your way before and it didn't work, I tried it now, and also it didn't work :(

**Comment by Calinou** [comment]
This sounds like an issue with the shader cache. I'm surprised it happens with both Mobile and Compatibility rendering methods though.

**Comment by adamscott** [comment]
@sopdevv I'm very concerned by the unauthorized use of the `org.godotengine` prefix for your game.

**Comment by akien-mga** [comment]
> @sopdevv I'm very concerned by the unauthorized use of the `org.godotengine` prefix for your game.

That's the default app id when users don't specify one, it's ok.

**Comment by StormEx** [comment]
Could someone take a look on it? Looks like a real blocker for android apps which used skinned meshes (skeletons). Even box with one bone will be broken in case of more than one launch of application on device.

**Comment by brcontainer** [comment]
@sopdevv maybe caused by **Shader Cache**: https://github.com/godotengine/godot/issues/82419

I provisionally solved it like this (while the bug is not fixed): https://github.com/godotengine/godot/issues/82419#issuecomment-1736617963

![image](https://github.com/godotengine/godot/assets/4368952/bdd69f61-8f07-4e1e-888e-9d0914532dce)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82419, as this is due to the same cause.
