### ISSUE TITLE
Dropping files from native filemanager to filesystem dock ignores destination folder

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#80667]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700S (Advanced Micro Devices, Inc.; 31.0.12024.2005) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When you drop a file from the OS filemanager into the filesystem dock, the file is not dropped inside the folder under the cursor. It seems to use whatever folder was clicked last. This might be by design but looks more likely to be a bug, since moving files withing the filesystem dock and withing the scene dock works as expected

### Steps to reproduce

- On any project create a new folder
- make sure that folder is not selected in the filesystem dock
- drag any file from the OS filemanager and drop it on top of the new folder

Expected:
The file is added to the project inside the folder where it was dropped
Actual:
The file is added to the project in the last selected folder

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Saw the same in 4.x

**Comment by noidexe** [comment]
Something interesting I noted:
On 3.5.2 Windows 11, if you print get_global_mouse_position() inside the files_dropped callback, you can notice that the mouse position you get is the current one if the "Project Name (DEBUG)" window is on top, but not if the windows explorer window is on top. It seems it only updates when the game window is on focus
On 4.2-dev3 Windows 11 get_global_mouse_position() always gives you the right coordinates. 

If this behavior affects the editor itself it might be the reason why dropping to the filesystem works the way it works. So at least on 4.x there is a way to know where you dropped the files and the standard behavior could be implemented, while on 3.x it might require deeper changes.
