### ISSUE TITLE
Replacing the Googleplay Target API version to 33 in Godot 3.x.Stable

### ISSUE THREAD

**Issue by AlonJu** [godotengine/godot#80672]
### Describe the project you are working on

An android mobile game

### Describe the problem or limitation you are having in your project

Google Play Store will require target API to be set to 33 starting on August 31st (https://developer.android.com/google/play/requirements/target-sdk). The current default target API for Godot 3.5.2 is 32. Are there any maintenance updates planned for Godot 3.X with target API set to 33 for Android?

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Changing the target API from 32 to 33.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Unsure, just a suggestion since Godot 3.x uses the OpenGL2 renderer.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Uncertain

### Is there a reason why this should be core and not an add-on in the asset library?

Because it affects mobile development.

**Comment by lawnjelly** [comment]
See: #75205 which is already merged in 3.x.

Godot 3.6 beta 3 will be released soon, which will have this. It may already be in 3.6 beta 2. It is also marked for cherry picking so should make its way to latest 3.5 (if it isn't there already).

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by zaddok** [comment]
I heard a rumor that 3.5.3 might be skipped. Does this patch need to be cherry picked for 3.6.x?

**Comment by akien-mga** [comment]
Don't believe rumors when the project manager wrote a week before that this change was integrated in the upcoming 3.5.3...

**Comment by gnuchanos** [comment]
we need target sdk 34 now this is funny man
