### ISSUE TITLE
Position moves when resizing BoxShape3D using grab handles

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#80685]
### Godot version

4.2.dev3

### System information

Windows 10

### Issue description

Testing 4.2 dev 3, when I resize a BoxShape3D (as seen in https://github.com/godotengine/godot/pull/71092) , the position of the BoxShape moves as well. If the parent of the BoxShape3D is located at (0,0,0), then the BoxShape resizes (but doesn't move) as expected.
If the parent of the BoxShape3D is not (0,0,0), resizing the shape sees the position change unexpectedly.

Resize works as expected if the parent node is at (0,0,0)
Resize works correctly if you edit the size values in the inspector, it's only grabbing the handles with the mouse that causes the position to change.

### Steps to reproduce

Create a new 3D scene.
Move the Node3D root to any location (eg. (1,0,1))
Create a CollisionShape3D child of the Node3D
Configure the CollisionShape3D as a BoxShape3D
Pull any of the grab handles to resize the Box
The Box will move as well as resize when it should only resize

### Minimal reproduction project

![boxshape-resize](https://github.com/godotengine/godot/assets/5151242/64379566-83b8-4da3-b61c-9bae95bb26ea)

**Comment by AThousandShips** [comment]
Caused by a typo in the editor, fix up
