### ISSUE TITLE
Inherited scene not updating correctly their collision layers in the instantiated scene (2D)

### ISSUE THREAD

**Issue by Mathieu-Roux** [godotengine/godot#80683]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Compatibility) 

### Issue description

The first time you update the collision layer from an inherited scene, it does not update on others scenes where it is instantiated ('level' as exemple)  unless you update it directly in 'level'.  Updating the collision layer from the parent scene doesn't work either. 
In addition to that the detecting behaviour seems to change depending on wherever it is an Area2D, StaticBody2D or CharacterBody2D. 
If you play around like creating multiple inherited scenes, deleting the instantiated scenes and instantiating them again, enabling/disabling the specific collision layer sometimes it fixes the bug, sometimes not, maybe I am just missing something ?

### Steps to reproduce

- create a StaticBody2D parent scene with an empty Sprite2D and an empty CollisionShape2D as children of it
- create an inherited scene from the previous step with a texture and a shape
- create an Area2D scene with a Sprite2D and CollisionShape2D as children of it with a script to make it move forward (you can try to use CharacterBody2D or StaticBody2D instead) 
- create a 'main' scene where you instantiate the inherited StaticBody and the Area2D
- remove the collision layer (default 1) from either the parent StaticBody or the inherited StaticBody (not directly in the main scene)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/43032 and/or https://github.com/godotengine/godot/issues/65193.

**Comment by Skip8** [comment]
This is still happening. Please reopen.
