### ISSUE TITLE
Export dictionary with named Enums as keys display integers in editor 

### ISSUE THREAD

**Issue by 2fd5** [godotengine/godot#80681]
### Godot version

v4.1.1.stable.flathub [bd6af8e0e]

### System information

Linux pop-os 6.4.6-generic

### Issue description

Given the exported dictionary with named enum as a key like here:
```
@export var storage: Dictionary = {
	Types.RESOURCES.H2O: 0.0,
	Types.RESOURCES.ENERGY: 0.0,
	Types.RESOURCES.MINERALS: 0.0,
	Types.RESOURCES.CARBON: 0.0,
}
```
Note: named enum is defined in global 'Types'. But it does not make a difference if named enum is in the same script. 

Editor displays integer values of these keys rather then text representation, like below

![image](https://github.com/godotengine/godot/assets/64538990/bea29c35-81b6-46d4-97c5-55feb8f3978b)

I would expect to see named enum text representation, or at least this would be more useful in editor.
I understand that dictionaries do not have fixed type for the key and the value and they can be different for each record in dictionary, still would be useful to have named enums displayed their name.

Not sure if this should go to proposals or can stay here

### Steps to reproduce

Add 
```
@export var storage: Dictionary = {
	Types.RESOURCES.H2O: 0.0,
	Types.RESOURCES.ENERGY: 0.0,
	Types.RESOURCES.MINERALS: 0.0,
	Types.RESOURCES.CARBON: 0.0,
}
```

to a node script and investigate the node in the editor.

### Minimal reproduction project

not included, not required

**Comment by Calinou** [comment]
> Not sure if this should go to proposals or can stay here

This should be opened on godot-proposals indeed, as this isn't a bug.

Implementing this isn't trivial, as this relies on ClassDB reflection (which may have some caveats, especially with subclasses or named classes).
