### ISSUE TITLE
Misleading error message when attempting to create an instance of a singleton

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#80728]
### Godot version

0511f9d9a7d56c742d87fafdcea8785d40ad14b3 4.2.dev (current master as of writing)

### System information

macOS 13.4.1 (this issue affects all systems)

### Issue description

When trying to construct a built-in singleton (ex: `DisplayServer.new()`), this error message is misleading:

<img width="800" alt="Screenshot 2023-08-17 at 11 30 46 AM" src="https://github.com/godotengine/godot/assets/1646875/74965bb3-ba26-43dc-8b1b-12046551f421">

The error message says it's abstract, which seems like it should indicate that you need to use a derived class. However, this is a singleton, and you are meant to use its methods directly. Instead of the current error text, it should say something about how it's a singleton and you should use its methods directly.

### Steps to reproduce

Write `DisplayServer.new()` in the script editor.

### Minimal reproduction project

Since it's one line I am not going to bother making a MRP.

**Comment by dalexeev** [comment]
* Fixed by #82098.

![](https://github.com/godotengine/godot/assets/47700418/ee00ec4e-83d4-47b7-a232-58ad9f5dc668)
