### ISSUE TITLE
DirectionalLight3D currently has no Specular property

### ISSUE THREAD

**Issue by jonathon-green** [godotengine/godot#80737]
_Note: This issue was transferred from the godot_docs repository. What appeared to be an issue with the documentation turned out to be an issue with the feature itself. clayjohn has commented below a bit of background. Ultimately, the ghost documentation highlights that we removed a setting by mistake. The solution is to restore the setting._

**Your Godot version:** 4.1 Stable

**Issue description:** DirectionalLight3D missing Specular property, current documentation states this should exist

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/lights_and_shadows.html
https://docs.godotengine.org/en/stable/tutorials/3d/global_illumination/faking_global_illumination.html

**Additional information:**

https://github.com/godotengine/godot-docs/blob/05fe756d9d1e6abab198da4721ba8f0407f0e45e/tutorials/3d/lights_and_shadows.rst?plain=1#L44

According to the text (from Godot Engine 4.1 - 3D Lights and Shadows, linked above) and the screenshot of common light properties above it, `DirectionalLight3D` (like Omni and Spot lights) should have a `Specular` property but currently doesn't (4.1 Stable). Not sure if this is a bug, a documentation issue or due to on going work.

![directionallight3d_missingspecular](https://github.com/godotengine/godot-docs/assets/68268537/704dba21-ea98-4006-8bbd-b50df071a6fe)
<sub>specular property missing from DirectionalLight3D</sub>

Due to this, currently unable to remove the specular blob from DirectionalLights when following "Godot Engine 4.1 - Faking global illumination". Which specifically mentions setting `Specular: 0.0` on `DirectionalLight3D`.

https://github.com/godotengine/godot-docs/blob/05fe756d9d1e6abab198da4721ba8f0407f0e45e/tutorials/3d/global_illumination/faking_global_illumination.rst?plain=1#L48

**Comment by dheerajd5** [comment]
Hey, can I take up this issue?

**Comment by AndrewShobbrook** [comment]
I think I might've fixed the issue just through Clayjohns advice, but I can't figure out how to change the default value for it back to 1.0 (Default is 0.5 for some reason)

Also am I supposed to ask beforehand for something like this? I haven't contributed here before so sorry if I acted too early
