### ISSUE TITLE
Dock windows are empty if they were hidden when loading a layout that make them floating

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80748]
### Godot version

4.1.1

### System information

linux

### Issue description

If a dock isn't visible in the editor (in an unshown tab), loading an editor layout that undocks it will result in this behavior:

[simplescreenrecorder-2023-08-18_08.58.08.webm](https://github.com/godotengine/godot/assets/71937306/08aea47c-e948-4345-9943-71fc0bbadd3e)

This also happen *sometimes* when the docks are visible before undocking, but I can't reproduce it :upside_down_face: 

### Steps to reproduce

See video above:

1. save a layout with a floating dock,
2. restore the default layout or manually close the dock window,
3. hide this particular dock,
4. load the previously created layout.

### Minimal reproduction project

Here's the editor layout I use in the clip, though it needs to be recreated locally because of monitors and coordinates etc.:

<details>

append to `~/.config/godot/editor_layouts.cfg`

```
[test]

dock_1_selected_tab_idx=0
dock_2_selected_tab_idx=0
dock_3_selected_tab_idx=0
dock_4_selected_tab_idx=0
dock_5_selected_tab_idx=0
dock_6_selected_tab_idx=0
dock_7_selected_tab_idx=0
dock_8_selected_tab_idx=0
dock_floating={
"FileSystem": {
"window_rect": Rect2i(2669, 319, 228, 302),
"window_screen": 0,
"window_screen_rect": Rect2i(1990, 27, 2490, 1413)
},
"Inspector": {
"window_rect": Rect2i(2927, 323, 270, 300),
"window_screen": 0,
"window_screen_rect": Rect2i(1990, 27, 2490, 1413)
},
"Scene": {
"window_rect": Rect2i(2388, 315, 252, 300),
"window_screen": 0,
"window_screen_rect": Rect2i(1990, 27, 2490, 1413)
}
}
dock_split_2=0
dock_hsplit_1=0
dock_hsplit_2=337
dock_hsplit_3=-337
dock_hsplit_4=0
dock_filesystem_split=0
dock_filesystem_display_mode=0
dock_filesystem_file_sort=0
dock_filesystem_file_list_display_mode=1
dock_filesystem_selected_paths=PackedStringArray("res://")
dock_filesystem_uncollapsed_paths=PackedStringArray("res://")
dock_3="Import,Scene"
dock_5="Node,History,Inspector"
dock_4="FileSystem"
dock_split_3=0
```

</details>

**Comment by moritz-t-w** [comment]
whenever I open a godot project that I had previously used with floating windows, the node window is always blank. I have made a layout that keeps the node window attatched and only if I then manually make it floating does it work.

**Comment by ColtonRamos** [comment]
I can confirm that this issue or something very similar occurs every time I reopen my project with floating/undocked windows. My current workaround is to close and reopen/reposition those windows, which is really annoying.

**Comment by ColtonRamos** [comment]
After reading this post again, I found a quicker workaround: Set up a "fixer" editor layout by arranging all the windows I want undocked in a new layout by going to Editor => Editor Layout => Save Layout. Then I flip to the "fixer" before I flip to my actual multi-monitor layout.

However, this doesn't work every time. About 1/3 of the time when I do this, Godot hard crashes to desktop (Windows 11, Godot v4.1.1.stable.mono.official).

**Comment by moritz-t-w** [comment]
That's what I've been doing too

**Comment by mieldepoche** [comment]
This still happened at least once after #82742 (v4.2.beta.custom_build [a574c0296]).
The exact same behavior, where the dock that was hidden showed up empty when detached.
Restarting the editor fixed it the time it happened (and I didn't manage to make it happen again...).
