### ISSUE TITLE
DAE material import issue 

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8075]
**Operating system or device - Godot version:**
3.0 alpha

**Issue description:**
I have a mesh in blender with material called "VertexColor"
In godot I have a material called "VertexColor.tres"
I place my dae mesh in the godot project, it auto imports. But it does not apply that material.
It would be useful to have this automatically apply the material to the mesh, to save having to make an instance of each new mesh just for the sake of applying a material.

**Comment by reduz** [comment]
This is tested and working now (you even have an option in the importer to choose behavior).

**Comment by adamspruijt** [comment]
This still happens for me on DAE files that reference textures using file protocol. I'm on windows if it matters. This is currently the format the Qubicle Constructor uses so it has personally had a major impact on my workflow. I'm no DAE expert so I don't know if they are using the wrong format (example below) or if Godot is just missing this support.
```
  <library_images>
    <image id="door-image" name="door-image">
      <init_from>file:///door.png</init_from>
    </image>
  </library_images>
```
