### ISSUE TITLE
Editor view can be moved to infinity, making the scene permanently uneditable

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#80755]
### Godot version

4.2 ff5c884

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Using expressions, you can move a node to infinity. When you focus on the node afterwards, the 2D editor becomes unusable:

https://github.com/godotengine/godot/assets/2223172/ed4c252a-39e8-46a1-a513-340b26216210

You can't pan or center on other objects, no node is visible in the viewport. If you save the scene in this state, the edit state file saves `ofs = Vector2(nan, nan)`, making the scene uneditable until you fix the edit state file in the `.godot` folder.

### Steps to reproduce

1. Add some 2D node
2. Change it's position to infinity (can't be directly entered; use `pow()` method)
3. Focus on that object by pressing F

### Minimal reproduction project

N/A

EDIT:
Apparently #80699 is required to use `pow()`. Not sure how to make `inf` otherwise.

**Comment by MewPurPur** [comment]
It's possible to make `inf` otherwise, I've done it for fun and broken Godot. Try `tan(PI/2)`

**Comment by KoBeWi** [comment]
`tan(PI/2)` gives `16331239480885248`

**Comment by MewPurPur** [comment]
Oh, true. It does break Godot though but it's probably a different bug.

`log(0)` tho I'm sure did an infinity
