### ISSUE TITLE
`FileDialog` considers `/path/to/dir/`'s parent directory to be `path/to/dir`

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80750]
### Godot version

4.1.1

### System information

linux

### Issue description

- When favoriting a path in a `FileDialog`, clicking on it travels to `path/to/dir/`.
- When going up a level from there, it doesn't go to `path/to` but to `path/to/dir` (without the `/`).

[simplescreenrecorder-2023-08-18_09.38.37.webm](https://github.com/godotengine/godot/assets/71937306/00c20ad3-292f-4961-84ed-dbc64906df52)

The problem is either (or both) that:
 - loaded path has a trailing `/`
 - parent dir of `stuff/` is considered to be `stuff`

### Steps to reproduce

favorite a directory and use the feature to navigate to it

### Minimal reproduction project

any (i.e. the project manager's "new project" dialog has one)

**Comment by AThousandShips** [comment]
Can you confirm this on 4.1.1? Please make sure bugs are present on an up to date version

**Comment by mieldepoche** [comment]
> Can you confirm this on 4.1.1

ah, missed that one. It does.

**Comment by aXu-AP** [comment]
I couldn't replicate on Windows 10, so maybe this is dependent on OS?

**Comment by Alex2782** [comment]
Can the function `_go_up()` be modified for this?

I believe `get_base_dir()` is working as it should be. (190 results in 80 files)
The function `change_dir` exists 4 times, also for Android.

https://github.com/godotengine/godot/blob/5444afae63f37cb4b890c781e5679a3b7ee5a392/editor/gui/editor_file_dialog.cpp#L1530

**to:**

```cpp
void EditorFileDialog::_go_up() {
	String cur_dir = get_current_dir();

	if (cur_dir.ends_with("/")) {
		cur_dir = cur_dir.substr(0, cur_dir.length() - 1);
	}

	dir_access->change_dir(cur_dir.get_base_dir());
	update_file_list();
	update_dir();
	_push_history();
}
```

**Test on MacOS:**

https://github.com/godotengine/godot/assets/41921395/29fbd623-aa8c-4c36-9ecf-8f18cfb3d143
