### ISSUE TITLE
Debanding stops applying when the project restarts or TAA is toggled

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#80751]
### Godot version

4.2 dev 3

### System information

Windows 11, i3-10105f, RX6600 23.7.2, Forward+

### Issue description

Debanding doesn't seem to apply when the Project is loaded. Both in Editor and Running Project.
Haven't found any other settings that seem to behave like that (Soft Shadows, Shadow Resolution, MSAA, FXAA, TAA...)

### Steps to reproduce

Turn Debanding On
Debanding is Applied
Save
Close Editor
Start Editor
Load Project
Debanding is not Applied but Project settings state On
Turn it off and on again
Debanding is Applied

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I've noticed an issue where debanding stops applying if you toggle TAA.

**Comment by mrjustaguy** [comment]
Ok the issue happened between 4.2 dev1 and 4.2 dev2

**Comment by mrjustaguy** [comment]
at a glance, the most likely culprit is https://github.com/godotengine/godot/commit/4874b96033131e4489d9d843ea226479ce32ff8b#diff-f4e00c86801fc9d6de91424a8310c96c4581d0c681db4d2050b6e44a3d78b39c though I have not tested yet

**Comment by Calinou** [comment]
I bisected the regression to 4874b96033131e4489d9d843ea226479ce32ff8b (which confirms mrjustaguy's guess).

**Comment by BastiaanOlij** [comment]
owh i think I already see what I did wrong, let met test

**Comment by BastiaanOlij** [comment]
@Calinou not sure if this is enough because I'm not sure what I'm looking for visually, but it wasn't copying the debanding flag so that would definately explain it not working.

Let me know if #82766 fixes the issue or if there is more too this.
