### ISSUE TITLE
Crash on editor startup when choosing forward or mobile rendering - 4.0.3-stable onward

### ISSUE THREAD

**Issue by Alireza-Ta** [godotengine/godot#80760]
### Godot version

v4.0.3.stable.official.5222a99f5

### System information

Windows 10.0.19045 - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD FX-9830P RADEON R7, 12 COMPUTE CORES 4C+8G (4 Threads)

### Issue description

Hi there!
I can't create new projects with forward or mobile rendering with versions after 4.0.3-stable onward(tested 4.0.4-stable, 4.1-stable, and 4.1.1-stable).
When I hit the create button it only shows a blank editor screen and crashes.

Actually Godot 4.1-stable shows the wrong Vulkan API version. The 1.2.170 below is for my integrated GPU, however, Godot 4.0.3-stable console output is correct.

```
Godot Engine v4.1.stable.official.970459615 - https://godotengine.org
Vulkan API 1.2.170 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560 Series
```
```
Godot Engine v4.0.3.stable.official.5222a99f5 - https://godotengine.org
Vulkan API 1.3.250 - Forward Mobile - Using Vulkan Device #0: AMD - Radeon RX 560 Series
```
I also updated my GPU driver and nothing changed!
Maybe this #73450 is the culprit!

Thanks!

### Steps to reproduce

Crash if I choose forward or mobile rendering at the project creation.

### Minimal reproduction project

Crash if I choose forward or mobile rendering at the project creation.

**Comment by Calinou** [comment]
The workaround in https://github.com/godotengine/godot/pull/73450 likely needs to be made optional, so that you can set the value to `0` explicitly to disable it on problematic hardware/software combinations.

Are your drivers for the integrated graphics *and* the dedicated GPU fully up-to-date (from the AMD website, not your OEM, not Windows Update)?

**Comment by Alireza-Ta** [comment]
> Are your drivers for the integrated graphics and the dedicated GPU fully up-to-date (from the AMD website, not your OEM, not Windows Update)?

Yes. I updated through AMD Sofware: Adrenalin Edition. (Version 23.7.2, July 20th, 2023)

> You can also try running Godot with the --verbose command line argument, and use --gpu-index N to force a specific GPU to be used.

Actually tried it before and still crashes with different indices (0,1,2)!

**Comment by Calinou** [comment]
See this comment: https://github.com/godotengine/godot/issues/82840#issuecomment-1757022360

**Comment by Alireza-Ta** [comment]
4.2.beta2 seems solved the issue! No need to reinstall GPU drivers.

Thanks!
