### ISSUE TITLE
Wrong characters displayed in runtime with translations and Montserrat font

### ISSUE THREAD

**Issue by brane-games** [godotengine/godot#80762]
### Godot version

4.1.1

### System information

Linux

### Issue description

![image](https://github.com/godotengine/godot/assets/116460113/4725b3f5-e6be-4d08-a26c-5953732e42de)

In runtime, the characters are different than in the editor.

I could only reproduce with Montserrat font, and when Settings/Locale/test is set to **sr**

### Steps to reproduce

Can be reproduced in the small project I uploaded.

### Minimal reproduction project

[font_issue.zip](https://github.com/godotengine/godot/files/12380309/font_issue.zip)

**Comment by akien-mga** [comment]
Serbian locale can typically be either Latin or Cyrillic. I think with our `OS.get_locale()` formatting this would be `sr_Latn` or `sr_Cyrl` (following https://en.wikipedia.org/wiki/ISO_15924). Not sure which one is used by default if you specify on `sr`, but your test seems to show that it would be `sr_Latn`, while your OS/editor locale might be `sr_Cyrl`?

CC @bruvzg

**Comment by brane-games** [comment]
When printing out OS.get_locale() I get en_US which makes sense because my OS is in english

**Comment by bruvzg** [comment]
These substitutes for Serbian are set in the font file itself, so Godot (it's done by HarfBuzz library in particular) is doing what font designer intended to be done:

Substitution list:
<img width="843" alt="Screenshot 2023-08-21 at 11 14 13" src="https://github.com/godotengine/godot/assets/7645683/7a061873-2a27-4ad6-af69-0c88980a2373">

Target glyphs:
<img width="905" alt="Screenshot 2023-08-21 at 11 20 06" src="https://github.com/godotengine/godot/assets/7645683/0d9d2206-bab3-45c6-bb55-64417135d1fe">

As a workaround, you can change language value (force it to `en`) in the `Label`s BiDi properties, it will affect rendering only and should not interfere with localization.

<img width="659" alt="Screenshot 2023-08-21 at 11 25 14" src="https://github.com/godotengine/godot/assets/7645683/a146e2de-112a-42f6-8b48-c5c885b20321">

**Comment by bruvzg** [comment]
Also, I take a quick look at the Wikipedia, and this glyph style might be actually correct:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Cyrillic_cursive.svg/1920px-Cyrillic_cursive.svg.png">
