### ISSUE TITLE
crashing on TileMap editor window resizing

### ISSUE THREAD

**Issue by AdamsAGD** [godotengine/godot#80775]
### Godot version

4.11 4.1 4.0

### System information

windows 11 Corei5 13500H

Edition	Windows 11 Home
Version	22H2
Installed on	‎7/‎20/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

### Issue description

godot just crahses every time i reisize the window. ive deleted the tilemap node and that doesnt help. i switch sprite sources, doesnt help.

### Steps to reproduce

i cerated a new project and added a NODE and then TILEMAP  and it still crashes just trying to resize the window... i dont understand why.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
How is it related to TileMap if deleting TileMap did not fix it?
Does the issue occur in a new project? Try deleting `.godot` folder.
If it still doesn't help, please attach a minimal reproduction project.

**Comment by AdamsAGD** [comment]
i deleted the .godot folder and it didnt help.

update.
 when i resize the tilemap window in script viewer.. this doesnt happen, but when i switch to 2d mode it crashes.

**Comment by KoBeWi** [comment]
If you don't have minimal project can you at least attach some video?

**Comment by AdamsAGD** [comment]
make a new project, add a node, add a tilemap as a child of that node. i dont understadn MRP.  i thought my description was the MRP was.  minimal steps to reproduce the error.

didnt expect this fast of a response.. anyways another update to the issue.  if i switch to 3d view and start draggin the window up and down its kinda laggy then the 3d area starts to flicker black n white noise till finally crashes on a white screen. only the 3d view is white.
![Screenshot (16)](https://github.com/godotengine/godot/assets/142645524/962ac6b6-fdf6-40f5-9026-973672d2f65f)

**Comment by KoBeWi** [comment]
> make a new project, add a node, add a tilemap as a child of that node

Well I certainly can't reproduce the crash using these steps alone. It can be project-specific or system-specific issue.
Can you test in [4.2](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-3/)?

**Comment by AdamsAGD** [comment]
it still crashes in 4.2 but i was able to move the 2d screen around a little bit before it crashed.

the thing was when i was moving the 3d screen around my ram usage spiked from 900 to 1300, i moved it again and spiked to1600... and it was staying at 1300 and 1600..   

same thing is happening in the 2d screen, my ram is spiking up to 2400mb usage.

**Comment by AdamsAGD** [comment]
I downloaed 3.5.2 and it doesnt crash on me.  my ram spikes up to 1900 on the 3d and i was wiggling the window pretty hard for 15 seconds.  in 4.0 i wiggle up n down for less than a second and it crashes.

**Comment by AdamsAGD** [comment]
bump/update

ok so it doesnt crash anymore, i havnt done anything, microsoft updates my computer automatically and i cant stop it so ill never know what happened.

i did however go into 3d view and scroll the debug window up and down alot but it took like 20 seconds of just spamming it up and down, the 3d view went all white but i was still able to enlarge and shrink the window, then i went into 2d view and kept moving the window up and down, it didnt crash but got a bit laggy.  Then i alt+f4 and it crashed.

anyways im pretty sure this is a unique issue to my laptop so no worries.

**Comment by KoBeWi** [comment]
Sounds like it can be closed then.
