### ISSUE TITLE
FileSystem dock ignores "Rename" when pressing right click with another dock focused.

### ISSUE THREAD

**Issue by IIGreed** [godotengine/godot#80790]
### Godot version

4.1.1

### System information

W10

### Issue description

With another dock focused right clicking on the FileSystem dock fails to rename anything, all the other submenu options work.

### Steps to reproduce

- Left click the script editor
- Right click icon.svg on the FileSystem dock
- Select Rename

### Minimal reproduction project

^^^^^^

**Comment by Sauermann** [comment]
This is a known issue and has already been reported.
Consolidating as a duplicate with #78789
