### ISSUE TITLE
Focus is not changed to the debugger when an error or breakpoint is hit

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#80799]
### Godot version

4.2.dev3

### System information

Windows 10

### Issue description

Run your game with a breakpoint in it
When Godot reaches the breakpoint, the game window stays active instead of swapping to the debugger. You need to manually change focus to the Godot editor window.
Happens for both windowed and fullscreen projects.

Similarly if your game hits an error, focus does not change to the editor/debug window.

### Steps to reproduce

As above

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/44913.
