### ISSUE TITLE
The hover area of files in FileSystem is sometimes smaller than the text

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#80793]
### Godot version

The "Copy System Info" button does this already, but whatever... Godot 4.2 dev3

### System information

Godot v4.2.dev3 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/a57313e5-ba65-4d84-83c8-7b2354e717aa)

If you look at the hovered file, you'll see the text stretches lower than its bounds.

This seems to not happen 80% of the time:

![image](https://github.com/godotengine/godot/assets/85438892/607e9c75-51d7-41fd-a9b6-1154e81802cd)

But after a lot of going in various folders, I have still not found out when this occurs.

### Steps to reproduce

Click Import in the project manager (the window that opens when you launch Godot, I'm not speaking of Akien or Yuri) and start going in various folders on your computer - You'll likely find this soon. Or copy my folder setup.

Would be cool to find out the exact reproduction steps though.

### Minimal reproduction project

N/A

**Comment by coumcashier** [comment]
reproduced with these conditions

- The icons in the first row all has single line of text
- it only happens in the last row 
- there are more than one rows in total (at lease 2)
