### ISSUE TITLE
Dragging an object does not respect selection.

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#80795]
### Godot version

3.6 Beta 3

### System information

Ubuntu 22

### Issue description

When I drag an object from the file system of the engine, the selected object is ignored, it is added to the scene end.

In Godot 3.5.2, everything works correctly, when you drag an object, it becomes a child of the selected object.

This is how it worked before (3.5.2)

https://github.com/godotengine/godot/assets/13809475/fc951a11-33f4-4c08-b02b-f595cbb4375d

This is how it works now (3.6)

https://github.com/godotengine/godot/assets/13809475/fb88e5c1-289e-4fa9-987c-e6c1acfcacd2

### Steps to reproduce

Drag an object (in 3D, *.mesh) into the workspace from the engine's file system.

### Minimal reproduction project

Does not trumpet, because works in any project.

**Comment by SkanerSoft** [comment]
Small addition: The problem is observed in all versions 3.6 (beta 1, 2, 3).

**Comment by garychia** [comment]
The problem seems to be reproducible in the master branch.

**Comment by matheusmdx** [comment]
Bisecting the issue leads to #55626, but after check the code is possible to see that is not a regression, but a behavior change, now you need to hold ctrl before drop the 3d object to have the same behavior, so this is most a documentation issue. 


https://github.com/godotengine/godot/blob/1d7a417affca4d239b8ca64e839318d6ef811bc4/editor/plugins/spatial_editor_plugin.cpp#L4223-L4240

**Comment by SkanerSoft** [comment]
I tried this method and it solves this problem but creates another one. The snapping is completely lost and I can't position the new object in the right place.

https://github.com/godotengine/godot/assets/13809475/23aacdbf-e72f-496b-a84c-6c4eef574ed2

**Comment by SkanerSoft** [comment]
I don’t quite understand the reasons to change long-standing functionality, instead of expanding it with use cases without changing basic things.

**Comment by Calinou** [comment]
> Bisecting the issue leads to https://github.com/godotengine/godot/pull/55626, but after check the code is possible to see that is not a regression, but a behavior change, now you need to hold ctrl before drop the 3d object to have the same behavior, so this is most a documentation issue.

I think this is a regression, as the behavior is only supposed to change if there is no node present in the current scene.

**Comment by SkanerSoft** [comment]
So, I tried using CTRL and dragging, but the convenience was greatly reduced because... CTRL enables snapping to the grid, you have to make a lot of movements to adjust positions. It is also very inconvenient that this differs in behavior from 3.5. Temporarily returning to 3.5.

**Comment by SkanerSoft** [comment]
We kindly ask you to return the previous behavior of dragging objects, or make it customizable. This behavior is unintuitive and differs from all versions of the engine. It became bad to use it. Also, CTRL does not allow you to position the object due to snapping to the grid.

**Comment by Calinou** [comment]
> Bisecting the issue leads to https://github.com/godotengine/godot/pull/55626, but after check the code is possible to see that is not a regression, but a behavior change, now you need to hold ctrl before drop the 3d object to have the same behavior, so this is most a documentation issue.

This should not be affecting non-root nodes in the scene (in other words, if you already have an existing node, the behavior should be the same as 3.5).

**Comment by SkanerSoft** [comment]
3.6 B4, problem persists.
