### ISSUE TITLE
Editor crashes if trying to highlight part of a really long line of text.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#80801]
### Godot version

4.1

### System information

Windows 10

### Issue description

I have this config file and thought I'd try and edit it. The editor opens the .cfg file with no issue but highlighting the text crashes the editor.
Also adding and deleting text is very delayed.

This is probably a performance issue, I'm not sure if the editor would unfreeze if I waited a while.

Note:
The text highlights fine but crashes when I let go of the mouse.

### Steps to reproduce

Try highlighting some of the text from this file, I dare you!
[AStar Data.zip](https://github.com/godotengine/godot/files/12387133/AStar.Data.zip)

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
I tested it with Godot v4.2.dev (0511f9d9a) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)

Same here, adding and deleting text is very delayed and double click (hightlighting) will crash the editor. I can help to check what's going wrong first.
