### ISSUE TITLE
NavigationServer3D.map_set_cell_size has no effect

### ISSUE THREAD

**Issue by LasseSchnepel** [godotengine/godot#80805]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

The maps settings are not updated after set methods are called.
`var map = NavigationServer3D.map_create()
	NavigationServer3D.map_set_cell_size(map, 0.1)
	print(NavigationServer3D.map_get_cell_size(map))`
outputs "0.25" instead of the expected 0.1. This also doesn't change after some frames (to allow sync or something).

### Steps to reproduce

See the code in the issue description or use the provided MRP.

### Minimal reproduction project

[NavServerIssue.zip](https://github.com/godotengine/godot/files/12387366/NavServerIssue.zip)

**Comment by jsjtxietian** [comment]
I can reproduce this bug, I can take this issue if no one has started working on it yet.

**Comment by jsjtxietian** [comment]
@LasseSchnepel I can reproduce the bug, but the result will get correct after a frame as the image below. 

`map_get_cell_size` will query the map and give you the cell size immediately, but `map_set_cell_size`  will go through a command queue and triggered by `GodotNavigationServer::flush_queries` probably once a frame. I think it's why you can't get it's result 

![image](https://github.com/godotengine/godot/assets/8315986/4b7b1c19-5c26-4d3c-af8e-2272afa1c15d)

btw, I'm using I'm using Godot v4.2.dev (0511f9d9a) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)

**Comment by LasseSchnepel** [comment]
Oh, yes, that works! Sorry for the ticket!
