### ISSUE TITLE
[3.0][Feature] Highlight properties

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8080]
Since we got properties in 3.0, it would be nice to highlight them in the script editor (like class names), because it's hard to tell them apart from local variables. Or more generally, highlighting member variables could be of great help (Visual Studio and Eclipse do that and its very handy).

Screenshot of current state:
![image](https://cloud.githubusercontent.com/assets/1311555/24083376/29cacb1a-0cd6-11e7-9eab-11af530bd7c7.png)
Here, `transform` is actually a class property, 
`_roll` and `stabilizer_speed` are custom members.

**Comment by Calinou** [comment]
I'll close this in favor of #16799 since that issue has more details.
