### ISSUE TITLE
CSGShape3D Gizmo Breaks When Detaching Script Editor

### ISSUE THREAD

**Issue by Snaiel** [godotengine/godot#80816]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 22.04.2 LTS 22.04 - Vulkan (Forward+) - integrated AMD Radeon Vega 8 Graphics (RADV RAVEN) () - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

The gizmos to resize a CSGShape3D do not show up if the script editor is detached.

### Steps to reproduce

1. Create project
2. Create 3D scene
3. Add a  CSGShape3D
4. Select the shape in the scene editor (the orange gizmo to resize the shape shows and the shape is shaded with a blueish color)
5. Detach script editor
6. Deselect the shape
7. Select the shape again (The orange gizmo and blue shading is gone)

### Minimal reproduction project

[CSG-Test.zip](https://github.com/godotengine/godot/files/12388083/CSG-Test.zip)

**Comment by Eisendroid** [comment]
I have the same issue, but for me it's EVERY Gizmo. After detaching the script editor, the Gizmo handles of CollisionShape3D, Light3D, CSGShape3D, FogVolume, etc. are gone.

System:
EndeavourOS (Arch), Linux 6.1.50-1-lts, Nvidia GTX1080ti

**Comment by Snaiel** [comment]
The issue I specified was fixed in 4.1.3
