### ISSUE TITLE
External Editor (Language Server) - Could not find base class / Could not find type in the current scope

### ISSUE THREAD

**Issue by michaelschufi** [godotengine/godot#80822]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

An external editor (in my case VS Code) cannot resolve classes. Even though it's working in the Godot Editor:

![image](https://github.com/godotengine/godot/assets/2805598/24210327-612b-4ef6-8f65-e5417473cd29)

The same is happening for type annotations:

![image](https://github.com/godotengine/godot/assets/2805598/2978fb19-1112-42c0-8d6b-4cf9b982ae1d)

I may be just doing something wrong. But the editor can definitely connect to the language server ...

#### 1. Create three scripts

`foo.gd`
```gdscript
extends Node
class_name Foo

var foo_variable = "foo"
```

`bar.gd`
```gdscript
extends Foo
class_name Bar

func _physics_process(delta: float) -> void:
  print(self.foo_variable)
```

and `baz.gd`
```gdscript
class_name Baz

func my_function(foo: Foo):
  foo.foo_variable = 5
```

#### 2. Open them in VS Code
(Make sure you have VS Code configured correctly, as per the README.md of the Godot VS Code extension.)

Open the `bar.gd` and `baz.gd` and hover over the errors.

### Minimal reproduction project

https://github.com/michaelschufi/godot_base_class_not_found_repro

**Comment by ainformatico** [comment]
Same issue here using VScode and Godot 4.1.
I discovered the issue when creating `@export` vars in the parent class and then trying to use them in a child class.
VScode shows the errors, but the game runs without problem and the variables are available.

This is a real PITA.
While looking for solutions, found the following issues in https://github.com/godotengine/godot-vscode-plugin and they seem to point to a LSP bug:

* https://github.com/godotengine/godot-vscode-plugin/issues/487
* https://github.com/godotengine/godot-vscode-plugin/issues/431
* https://github.com/godotengine/godot-vscode-plugin/issues/266 

Issues form this repo that seem related:

* https://github.com/godotengine/godot/issues/68711
* https://github.com/godotengine/godot/issues/39713

**Comment by HolonProduction** [comment]
The MRP isn't available anymore and I can't find a cached version, but creating a new project with just those three scripts, I can't reproduce the issue in v4.4.dev.custom_build [92e51fca7]

**Comment by syrezone** [comment]
I'm still running into this issue on 4.4.1.

The repro project works until I rename a class, i.e.:

![Image](https://github.com/user-attachments/assets/60bf269b-f712-4014-91ab-7ea7c3de5233)

The workaround is restarting the LSP

![Image](https://github.com/user-attachments/assets/8e7fc517-8c39-4991-bd14-f0f73bfe0b05)

![Image](https://github.com/user-attachments/assets/3fc43663-db59-43a5-af2b-e3c1c33fc5ee)

**Comment by syrezone** [comment]
This fixed it:

https://github.com/godotengine/godot-vscode-plugin/issues/487#issuecomment-2817941748

**Comment by HolonProduction** [comment]
Yeah to reproduce this issue you need to change the name (or add it) through the external editor. It won't happen when opening an existing MRP project.

I have a fix lying around that triggers a resource reload in those cases regardless of editor settings but I'm not sure yet, whether this is save to do.

(Not reopening this since it is tracked with a better description in https://github.com/godotengine/godot/issues/105751)

**Comment by syrezone** [comment]
@HolonProduction yeah, that's the issue that I was running into and how I ended up here.

But as mentioned above with the Editor settings linked, it actually seems to work now. You can change class_name and it will not error out anymore.
