### ISSUE TITLE
Crash when opening default lighting config dialog

### ISSUE THREAD

**Issue by MarianoGnu** [godotengine/godot#8082]
**Operating system or device - Godot version:**
Xubuntu - Godot 3.0 (master)

**Issue description:**
When i wanted to change the default lighting on a 3D project the engine crashed with a segfault, i found the exact reason for this but could not fix it since i have no idea of what the value of these variables are suposed to be:
crash happens in rasterizer_scene_gles3.cpp line 3066:
glBindFramebuffer(GL_DRAW_FRAMEBUFFER, storage->frame.current_rt->effects.mip_maps[0].sizes[0].fbo);
the reason of the crash is because storage->frame.current_rt->effects.mip_maps[0].sizes is a null Vector<MipMaps::Size>

**Steps to reproduce:**
Open a new, or any project, go to Spatial Editor and open the View menu and select Configuration

**Comment by reduz** [comment]
This is fixed now
