### ISSUE TITLE
Running `godot scene.tscn` not working while being in subdirectory

### ISSUE THREAD

**Issue by exigow** [godotengine/godot#80825]
### Godot version

v4.1.1.stable.arch_linux

### System information

Godot v4.1.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Tue Jul 25 09:17:30 UTC 2023 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 535.86.05) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

In previous versions of Godot (for example 3.5.2 - tested), scenes could be run if the working directory was different from the root directory of the project file (where `project.godot` is placed). 

For example, you cloud just enter subdirectory using terminal (e.g. `scenes/`) and simply start scene by typing `godot scene.tscn` (note that `project.godot` is in parent directory). If we try to do something like this in Godot 4, it's not working and the project starts in editor mode (command is ignored).

Currently, the only way to run a specific scene is to be in the same directory as `project.godot` and write the full path to the scene, for example `godot scenes/test.tscn`.

Is this behavior expected or is it a regression?

### Steps to reproduce

1. Create empty project
2. Add `main.tscn` and set as main scene
3. Add `scenes/test.tscn`
5. Start terminal, go do `scenes/` subdirectory
6. Run `godot test.tscn`

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
You need to use `--path ..` or `--upwards` to automatically find a `project.godot` in parent directory.

**Comment by exigow** [comment]
Thank you for the quick response. Explicit `--upwards` solves my problem.
