### ISSUE TITLE
Strange error message: "Method expected 0 arguments, but called with 0"

### ISSUE THREAD

**Issue by johnny-byte** [godotengine/godot#80826]
### Godot version

Godot v4.1.1.stable

### System information

Windows 10

### Issue description

Get strange error message "Method expected 0 arguments, but called with 0" while generating signal
![image](https://github.com/godotengine/godot/assets/52435334/2c3e2772-8a93-4ffc-b8f4-249ae342badd)
 

### Steps to reproduce

1. clone https://github.com/johnny-byte/godot_issue/tree/master
2. run
3. click mouse button right
4. get error message

### Minimal reproduction project

[BugScene.zip](https://github.com/godotengine/godot/files/12388945/BugScene.zip)

**Comment by AcatXIo** [comment]
I can confirm that the following error is printed with Godot version v4.2.dev3.official.013e8e3af when right-pressing the button from the attached zip file.
```php
ERROR: Error calling from signal 'right_button_click' to callable: 'Control(Button.gd)::_on_my_color_picker_right_pressed': Method expected 0 arguments, but called with 0.
   at: emit_signalp (core/object/object.cpp:1084)
```

**Comment by KoBeWi** [comment]
Your `emit()` does not provide the required argument.
But yeah, the error is strange.
