### ISSUE TITLE
Add semantic versioning for Class API and modules

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#8083]
With the addition of dynamic libraries as scripts (soon, hopefully 😜 ) it would be nice to have a proper versioning system for the class API and also different modules in use.
This could also benefit custom modules, as those have no proper versioning system and might or might not work across Godot versions. 

I suggest using semantic versioning for that as it's super cool to programmatically check for compatibility between versions.

For example an "API version" could be defined as (arbitrary versions)
```gdscript
{
    "version": "3.0.2",
    "modules": {
        "my_custom_module": "1.1.0",
        "enet": "1.3.0"
    }
}
```

A script (or even modules) could then check if the API they need to properly work is compatible with the one Godot currently offers.

```GDScript
var required_version = {
    "version": "3.0.0",
    "modules": {
        "my_custom_module": "1.0.0"
    }
}

if not Engine.is_version_compatible(required_version):
    # warn the user or something like that
```
In this case those versions would be compatible because the major version is compatible and every module that's required is present and the version is matching.

The asset lib could check for those versions as well and refuse to download assets or plugins (or at least give a warning) if versions don't match etc.

WDYT?

**Comment by bojidar-bg** [comment]
@karroffel BTW, there is already `version.h`, maybe it does what it is needed for core? (not for modules though).

**Comment by hubbyist** [comment]
I support semvar idea but semvar may be to restrictive or demanding for a fast evolving project like Godot may be, especially If semvar will be used to check against Godot version directly. There may be a possibility of reaching Godot42 and beyond too quickly I think. 

I read in a post somewhere in net (couldn't find it now) about using a numbered product name and then using semvar as versioning of this numbered product to avoid having to change product name to often.

Like `Godot3.0.0.0` where `0.0.0` is semvar part and `Godot3` is product name. This way, major version number may be updated more often to reflect feature additions and big fixes more precisely. So making major version 42 like `Godot3.42.30.245` will mean a new feature size functionality has been added. This may make version management more granular IMO.

WDYT?

**Comment by reduz** [comment]
You can already request an API checksum.. not sure what else can be there,
as incrementing a version each time a function is added is kind of a hassle

**Comment by karroffel** [comment]
@reduz the checksum changes with additional modules. If the script depends only on one additional module but There are 3 installed, then the checksum won't match

**Comment by reduz** [comment]
That is expected, module changes api and api changes checksum..

**Comment by karroffel** [comment]
yes, but the script/module would still work because the modules that changed the API aren't relevant in that case.

**Comment by Anutrix** [comment]
Any updates?

**Comment by Calinou** [comment]
GDNative has been removed in favor of GDExtension in 4.0, closing.
