### ISSUE TITLE
STDOUT Output randomly doesn't work, preview takes long to open,  without any information

### ISSUE THREAD

**Issue by OWL4C** [godotengine/godot#80853]
### Godot version

v4.1.stable.flathub [970459615]

### System information

Godot v4.1.stable (970459615) - Freedesktop SDK 22.08 (Flatpak runtime) - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1070 Ti (nvidia) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When trying to play a scene the debug output just is randomly empty. Stopping and starting again have in the past helped as well as closing the engine and reopening the project. In the MRP i found it to reliably not output when uncommenting the last print statement at line 33 `print((1000.0/(average_time_between))*60)`. Less reliable is uncommenting any of the other lines, but the func convert time to bpm should work too. If the function is broken, there is no debug output stating such.
https://github.com/godotengine/godot/assets/124401812/ca99fc73-db0a-46c8-b18e-aaf040f5e351

### Steps to reproduce

Just open the script of the Song Editor Node in the Only tscn in the project.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/12397957/Archive.zip)

**Comment by Calinou** [comment]
Can you reproduce this in a [non-Flatpak build of the editor](https://godotengine.org/download/linux/)?

**Comment by OWL4C** [comment]
Yes, i have been able to reproduce it with the steam latest and the official download (linux x86_64, v4.1.1.stable.official [bd6af8e0e])

**Comment by OWL4C** [comment]
You might have to start and restart the scene multiple times to get it to fail. Make sure line 33 is not commented, start the scene. If it works, click the button a few times, it should produce output. Now restart the scene until the error happens. For me it was 4 times at most until change was visible.

**Comment by witchpiggie** [comment]
Using the current windows x64 build and even with the most basic project, the print function does nothing.

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.dev 541674d10 (Linux).

Remember that your code doesn't print anything if `beats` is lower than 200. This means you need to wait some time until pressing the button will appear to do anything.

**Comment by OWL4C** [comment]
First of all i don't understand why this would be the case, could you please explain, secondly that should not impact the debug statement not showing in the console, if i understand correctly?

**Comment by Calinou** [comment]
> First of all i don't understand why this would be the case, could you please explain, secondly that should not impact the debug statement not showing in the console, if i understand correctly?

What I mean is, the code won't print anything if the block in question is never reached. Try putting a print statement in `_ready()` instead. If you don't see that print in the console either, then this is likely the same cause as https://github.com/godotengine/godot/issues/81102.

**Comment by OWL4C** [comment]
Same issue in other project. Looking at #81943 i have identified portmaster as the culprit. Deactivating seems to fix the issue. Will try to find out how to setup portmaster to not interfere, but closing for now.

**Comment by OWL4C** [comment]
The only way that works consistently is to change the debug port under "Editor Settings" to something like 7007 instead of 6007. Have no idea why this happens with portmaster.
