### ISSUE TITLE
TileSet `Separation` missing "px" like similar values?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#80869]
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

TileSet->Setup->Separation maybe should have "px" like rest?
![Screenshot 2023-08-21 162202](https://github.com/godotengine/godot/assets/962340/3c6b9a97-7520-4610-8153-7882cc9c303f)
I know this is pixels from testing it.

TileSet->Select is this Animation Separation "px" too? idk
![Screenshot 2023-08-21 162131](https://github.com/godotengine/godot/assets/962340/fcb580e3-9ff7-41d8-92d3-e585841d3803)
I tried setting up animation separation and got a not enough room error, so maybe not "px". idk

Thanks.

### Steps to reproduce

- open TileSet->Setup->Separation, note some have "px" and one doesn't
- open TileSet->Select, is this separation "px" too?

### Minimal reproduction project

n/a

**Comment by dalexeev** [comment]
https://github.com/godotengine/godot/blob/8e0346badefcd69656e1ae3ba12d6eaafd7a4fae/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L114-L115

**Comment by philippesic** [comment]
If this is open, I'll add a suffix and submit a pr

**Comment by dalexeev** [comment]
> If this is open, I'll add a suffix and submit a pr

@philippesic Feel free to open a PR!
