### ISSUE TITLE
Godot 4 games on web, crash the Browser on Macbook air's.

### ISSUE THREAD

**Issue by StarFlashGames** [godotengine/godot#80876]
### Godot version

4.1.1

### System information

Macos Sonoma beta 14.0

### Issue description

When I was on **Itch.io** and was **exporting** my game to the **web** but when I tested the game it **crashed** the **browser** I don't know why but I could not **export** my game to the web.

### Steps to reproduce

Idk 

### Minimal reproduction project

https://star-flash-games.itch.io/super-space-shooter-x

If you are on mac.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70691 and https://github.com/godotengine/godot/issues/74512.
