### ISSUE TITLE
Preparing for 2.1.3-stable

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8087]
It's time to work on stabilising the 2.1 branch again so that we can release 2.1.3-stable.

2.1.2 was two months ago, and since 3.0 is taking its time, many devs have pushed some development work to the 2.1 branch directly, so we'll need to do some more extensive testing - we have more than just bug fixing commits :)

This issue is meant to gather initial feedback on pre-release binaries, so that we can spot regressions (either from new developments or from bad cherry-picks I might have done).

You'll find binaries from yesterday here: https://github.com/GodotBuilder/godot-builds/releases/tag/2.1_20170319

Known issues:
- CanvasItemEditorPlugin tries to access `set_position` instead of `set_pos`: fixed in 4230b22 (but not in above binaries)
- CanvasItemEditorViewport tries to connect to non-existing CheckBox signal: https://github.com/godotengine/godot/commit/a9d8da91b72fe8493f9087563056bb4ade4ca2c7#diff-3910e354cfb3848e417581c47035e5c5R3777
- Something was fishy with iOS templates in 2.1.2-stable? Help welcome to know exactly how the zip should be setup.
- add yours :)

Note: as always I'm only interested in *regressions* (i.e. bugs that did not affect earlier 2.1.x versions), including to some extent bugs in new features if there are any. Packaging issues with the templates, etc., are of course also interesting :)

**Comment by akien-mga** [comment]
Regarding android binaries, I couldn't build them successfully on Travis because our logs are spammed with warnings and Travis kills the build when the log exceeds 4 MB... https://travis-ci.org/GodotBuilder/godot-builds/jobs/212575435

So if someone can work on either fixing warnings, or adding a scons option I could use to silence them (or some of them) during Travis builds on GodotBuilder, that would be great.

**Comment by AlexHolly** [comment]
Never used scons but looks like this removes the target info and shows only warnings

SConstruct

Line 250

```
def print_cmd_line(s, targets, sources, env):
        sys.stdout.write("")

    env['PRINT_CMD_LINE_FUNC'] = print_cmd_line
```

I tried this for the warnings but no luck maybe I did something wrong.
http://stackoverflow.com/questions/10147079/disable-all-scons-warnings

**Comment by florix91** [comment]
If can help I have some bugs to mention:
1-On iOS templates the executables files are zero bytes while those in folder are correct size and working so to make it working we have to replace those 0 bytes files with the correct ones inside the inner folder.
2- There is a bug with audio drivers on iOS. If an app that uses sample player is running, after the iPhone receive an incoming call or even a siri function, sample player does not work anymore and no audio is outputted from device. I think that is very important bug to be fixed because a lot of users may have some game on the App store.
3- Function "OS.set_low_processor_mode_usage" makes the app when runned on the android phones to a flashing mode like, even tough the function doesn't even work at the moment like Juan told somewhere. On iOS i don't know how this affects the app.
4- Not very sure. However I have an old project made in godot and it compiles correctly on my android phone on 2.0.3 but not on later versions of the engine. I really don't know what this can be because all options and settings are the same, so maybe can be a bug in export template for android. I think that more or less the problem has began after the OpenSSL issue was fixed. In fact my app on the Play store of google still has that problem because i couldn't compile it after that time.

**Comment by akien-mga** [comment]
Blocking for the release: #8090

(I'm nevertheless preparing some RC1 binaries right now that I will soon publish).

**Comment by akien-mga** [comment]
Here are the binaries (properly packed as normal releases) for 2.1.3-rc1, please test extensively and report any regression: http://download.tuxfamily.org/godotengine/2.1.3/rc1/

I *think* I've fixed the iOS template issue, please confirm.

**Comment by volzhs** [comment]
Go forward and backward is not working

1. Settings > Editor Settings > Shortcuts > Search > "indent"
2. clear key bind "Indent Left" and "Indent Right"
3. select several files on script editor
4. try go forward or backward with <kbd>Alt</kbd>+<kbd>Left (Right)</kbd>

**Comment by volzhs** [comment]
Found how to fix it.
1. Settings > Editor Settings > Shortcuts > Search > "indent"
2. clear key bind "Indent Left" and "Indent Right"
3. Search > "history"
4. assign key <kbd>Alt</kbd>+<kbd>Left (Right)</kbd> on History Prev / Next

I don't know why Godot can't recognize Ctrl + Alt + Arrow.
I tried to assign Ctrl + Alt + Arrow for shortcut but only recognize Ctrl + Alt (not arrow)

but still Ctrl + Tab or Ctrl + Shift + Tab doesn't work for me. :cry:

**Comment by volzhs** [comment]
Damn...
it's because of shortcuts for switching workspace on ubuntu. never mind my comments. :disappointed:

**Comment by akien-mga** [comment]
Once #8090 is fixed (found the regression), I'll make RC2 binaries. It will probably be early next week though, I won't have time over the week-end.

**Comment by eon-s** [comment]
#8177 and #8178, both related to TouchScreenButton shapes, the latter in particular, even if it is not a "bug" it could bug users.

**Comment by akien-mga** [comment]
We should probably check that #7696 gets fixed before that release too, a crash is never good in a stable release.

**Comment by FuzzyRhombus** [comment]
Testing the RC2 binary for OSX I'm getting parser errors relating to inner classes:

I was initially getting `Parser Error: Expected indented block after 'for'` in block of code in an inner class. I suspected it has to do with the inner class, so I added the following to another file as a test:
```
func _input(event):
	pass

# inner class test
class TestInner:

	var foo = 1

	func bar():
		pass
```

which results in `Parser Error: Error parsing expression, misplaced: class`

For the former I can keep commenting out code and it will just complain about the next block being unexpected. This is code with no changes that is properly indented and worked fine as-is in **2.1.2**

**Comment by bojidar-bg** [comment]
@FuzzyRhombus Probably #8315, which was my fault. The offending changes have been reverted.

**Comment by akien-mga** [comment]
@FuzzyRhombus Thanks for the report, it's likely the same bug as #8315. It's fixed in the 2.1 branch now as I reverted the problematic change, so 2.1.3-rc3 should be good.

**Comment by FuzzyRhombus** [comment]
Good to know 👍 

Sorry I didn't look through the existing issues =O

**Comment by eon-s** [comment]
Found this :bug:  #8323
Is the new flip texture for Particles2D.

**Comment by eon-s** [comment]
ALL WAS GOOD until I started testing something else and saw #8090 again, it looks worse now but at least I know how to trigger it, that may give some hint :sweat_smile:

**Comment by akien-mga** [comment]
> ALL WAS GOOD until I started testing something else and saw #8090 again, it looks worse now but at least I know how to trigger it, that may give some hint 😅

Could you test the current 2.1 HEAD branch? I just merged a PR that should improve this stuff further.

**Comment by eon-s** [comment]
@akien-mga the main issue seems to be gone :+1: , now the only thing that do not work is the button to reload default value if you disable monitoring on the instanced scene (stays disabled), clicking the checkbox works.

**Comment by akien-mga** [comment]
So, as far as I'm concerned it's starting to look release ready. Any objection? :)
