### ISSUE TITLE
[3.x] Physics Interpolation - `CPUParticles2D` local transform is applied twice

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#80880]
### Godot version

3.6 beta 3

### System information

All

### Issue description

Two issues here (in one as they are very related and I am lazy):

1) When a local transform is applied to `CPUParticles2D` (in global mode) it is applied to the particles twice. Move the particle system to `100, 0` and it will appear at `200, 0`.
2) Any children of `CPUParticles2D` don't have their rendered transform as expected - it is relative to only the particle system and doesn't inherit transforms of grandparents. 

![double_transform](https://github.com/godotengine/godot/assets/21999379/6e7cb032-a714-461b-aaa2-3b78f922a157)

### Steps to reproduce

1) With physics interpolation on, move a `CPUParticles2D` directly using the node itself, rather than a parent.
2) Attach a child to a moving `CPUParticles2D`.

### Minimal reproduction project

[CPUPartlcles2D_DoubleTransform.zip](https://github.com/godotengine/godot/files/12406280/CPUPartlcles2D_DoubleTransform.zip)

Switch physics interpolation off and on. Notice that with interpolation on:
* The particle system moves twice as far as the reference point.
* The child sprite is incorrectly positioned relative to the particle system.

## Discussion
I first mentioned this problem in https://github.com/godotengine/godot/pull/80827#issuecomment-1686047096 , but it deserves its own issue.

While testing, I was only moving particle systems via their parent node, which works fine providing the particle system local transform is identity (i.e. 0). However when the transform is applied directly to the particle system rather than the parent, even though the particles are already in global space, the local transform is still applied during rendering. This is incorrect, and the fix is to not apply the local transform during rendering.

 The second problem is a slight oversight I should make sure the _expected_ transform is propagated to children of `CPUParticles2D` (because they currently override the propagated transform).

I have fixes for these coming but this issue is for reference and anyone encountering same problem in 3.6 beta 3.

**Comment by akien-mga** [comment]
Fixed by #80887.
