### ISSUE TITLE
Geometry2D.triangulate_delaunay returns non clockwise triangles since 4.1

### ISSUE THREAD

**Issue by davidsillou** [godotengine/godot#80886]
### Godot version

4.1,4.2

### System information

windows 10

### Issue description

since godot 4.1, Geometry2D.triangulate_delaunay returns non clockwise triangles

### Steps to reproduce

```
var points : Array[Vector2] = []
points.append(Vector2(-584.713012695313,-148.372039794922))
points.append(Vector2(107.9462890625,22.7720947265625))
points.append(Vector2(752.789916992188,-536.875854492188))
points.append(Vector2(-251.754272460938,142.069213867188))
	
var tris : PackedInt32Array = Geometry2D.triangulate_delaunay(points)
print("triangles : ",tris)
	
for i in range(0,tris.size(),3):
	var a : Vector2 = points[tris[i]]
	var b : Vector2 = points[tris[i+1]]
	var c : Vector2 = points[tris[i+2]]
	
	var clockwise : bool = Geometry2D.is_polygon_clockwise([a,b,c])
	
	print("clockwise : ",clockwise)
```

### Minimal reproduction project

[delaunay_tmp.zip](https://github.com/godotengine/godot/files/12407605/delaunay_tmp.zip)

**Comment by AThousandShips** [comment]
While this can be considered an issue there's no guarantee that they be clockwise from the documentation

**Comment by davidsillou** [comment]
The problem (I think) lies in the change since version 4.0.

I got stuck on 4.0.4 for a while before taking the time to look for the cause of my problems with 4.1+

I agree that this is not strictly speaking a bug but an undocumented change that can confuse

:-)

**Comment by AThousandShips** [comment]
Are the triangles both clockwise and anticlockwise? Or only anticlockwise?

**Comment by davidsillou** [comment]
we get both (as in the minimal reproduction project)

**Comment by AThousandShips** [comment]
The input polygon is invalid and self intersects, so the result of it isn't really a good indication

**Comment by davidsillou** [comment]
I am surely missing something;
Shouldn't triangulate_delaunay accept arbitrary point sets (ie : not defining a polygon) ?

**Comment by AThousandShips** [comment]
That is true, but the ordering is dependent on the input for performance reasons, checking orientation for each triangle is costly, and no guarantees are made

If the triangles are desired to be ordered that's for the user to ensure I'd say, as no guarantees are made, if it's not specified you can't rely on it, so relying on it being a specific ordering isn't safe

**Comment by AThousandShips** [comment]
No problem!

You could open a [proposal](https://github.com/godotengine/godot-proposals) to enforce ordering for this, but since it is trivial to check and enforce the ordering, and the performance cost involved, it's probably best left as is

**Comment by davidsillou** [comment]
I think so

**Comment by davidsillou** [comment]
I think so too
