### ISSUE TITLE
Particles2D fails sometimes - 2.1.3 pre-stable 

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8089]
**Ubuntu 16.10 - Godot version: pre-2.1.3 from https://github.com/GodotBuilder/godot-builds/releases/tag/2.1_20170319**

**Issue description:**
Sometimes Particles2D does not emit particles.

**Steps to reproduce:**
Open and run a project with many (instanced in runtime?) particle emitters.

**Link to minimal example project:**
Player bullets on the platformer demo are a good example.

**Comment by akien-mga** [comment]
Just to be sure - does it work properly in 2.1.2-stable?

**Comment by eon-s** [comment]
Yes, is fine on 2.1.2, tested on a couple of projects

**Comment by akien-mga** [comment]
Potential culprit for a regression: 7e90b98 (@RandomShaper).

**Comment by akien-mga** [comment]
I can't seem to reproduce, for me the platformer demo behaves exactly the same in 2.1.2-stable (optimised editor build) and current 2.1/HEAD (debug editor build). The "fire" particle effect is properly emitted, unless you fire many times in a row and then some are skipped, but that happens in both versions for me. (Linux x86_64, Mageia 6).

**Comment by eon-s** [comment]
I can fire many times here and can make particle intensive scenes with no problem on the stable...

This project, a bit more complex but with slow spawning objects, shows the same issue https://gitlab.com/eon-s/tbplane/ , sometimes enemy planes appear without smoke particles.

**Comment by akien-mga** [comment]
Alright, I can reproduce the bug with your game.

**Comment by RandomShaper** [comment]
Debugging right now...

**Comment by akien-mga** [comment]
Not sure why GH failed to parse "Fixes #8089." in #8091.

Anyway, fixed by #8091.
