### ISSUE TITLE
Extra Spacing in a nested FontVariation does not work

### ISSUE THREAD

**Issue by kimkanu** [godotengine/godot#80907]
### Godot version

4.2.dev3

### System information

Godot v4.2.dev3 - macOS 13.4.0 - Vulkan (Mobile) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Probably related to https://github.com/godotengine/godot/issues/58340

When a FontVariation has a FontVariation in it as a fallback font, Extra Spacing values are overriden by the parent's one. Transforms and Embolden values seem to be fine.

### Steps to reproduce

1. Create a `Label`.
2. Create and set a `FontVariation` as the font of the label node.
3. Create and set another `FontVariation` as a fallback font of the font of the label node.
4. Manipulate Extra Spacing values of the fallback font (such as Glyph) and there are no visible changes. If the parent has changed extra spacing values, then it affects the child fallback font too.

<img width="2032" alt="Screenshot 2023-08-23 at 7 44 49" src="https://github.com/godotengine/godot/assets/22598138/c2ac76df-b391-422c-8504-c87c8095edcc">

### Minimal reproduction project

[font_variation_bug.zip](https://github.com/godotengine/godot/files/12413487/font_variation_bug.zip)

**Comment by gu-fan** [comment]
in 4.2.1 stable, this issue seems still remains.
Changing `spacing_top` or `spacing_bottom` in subresource does not working
