### ISSUE TITLE
Vulkan Mobile renderer - Decals sometimes ignore cull mask and draw over everything

### ISSUE THREAD

**Issue by GameBeastProductions** [godotengine/godot#80901]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Manjaro Linux - Vulkan (Mobile) - integrated AMD Radeon Vega 10 Graphics (RADV RAVEN) - AMD Ryzen 7 3700U

### Issue description

When adding a decal using the Vulkan Mobile renderer, it will initially render over anything (Sprite3Ds, MeshInstance3Ds etc.) that are inside its AABB regardless of the cull mask set on it and the meshes.  Moving the decal slightly will temporarily fix this, but if the affected meshes are moved or hidden then shown again, the bug reappears.

This does not happen with the Forward+ renderer.

The decal setup - cull mask is set to only layer 1:
![image](https://github.com/godotengine/godot/assets/142923558/8df918a4-a99b-4f13-bf06-f0852141391f)

The sprite setup - layer is clearly set to 2 but the decal is still visible over it:
![image](https://github.com/godotengine/godot/assets/142923558/5b56e84d-4964-4019-a9e4-a9b365fe65b4)

After moving the decal slightly, it no longer affects the sprite (as expected):
![image](https://github.com/godotengine/godot/assets/142923558/b292911d-fbbf-46fb-9f63-3f1617a613ad)

But after hiding and showing the sprite, the decal appears over it again:
![image](https://github.com/godotengine/godot/assets/142923558/d6fe0abc-b02e-4277-b56e-28b35aaf2abf)

### Steps to reproduce

1. Create a 3D scene with a plane mesh in visibility layer 1 and a sprite or other mesh in layer 2
2. Add a decal with a cull mask set to only layer 1
3. Once the decal is added, and before it has been moved, it will render over the mesh in layer 2 even though the cull mask is set to layer 1

### Minimal reproduction project

[Mobile Decals Test.zip](https://github.com/godotengine/godot/files/12410894/Mobile.Decals.Test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70774.
