### ISSUE TITLE
Godot 2.1.3 pre-stable can change the monitoring status of Area2D scenes

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8090]
**Ubuntu 16.10 - Godot version: pre-2.1.3 from https://github.com/GodotBuilder/godot-builds/releases/tag/2.1_20170319**

**Issue description:**
Opening projects with area based scenes on the tree, can change the "monitoring" value for no apparent reason, scene files appear with "monitoring = false" on the tscn where they are added but the inspector shows "checked" mark and works fine (as if monitoring is true) on 2.1/HEAD 
Opening back in 2.1.2 gives the expected result of all scenes with monitoring disabled.

**Steps to reproduce:**
I have no idea how to trigger the issue on a small project, appears to affect only Area2D scenes added as child of a scene.
A way to see the issue could be editing a scene file to change the monitoring status to false, it should appear as true/checked on the editor.

**Comment by eon-s** [comment]
Not exactly what started the issue but maybe could help to find the problem.

Load test1.tscn on both, stable and one of the 2.1 binaries from the link, the monitoring status on one of the areas should be different on both, the disabled one is the correct.

[brokenareas.zip](https://github.com/godotengine/godot/files/855926/brokenareas.zip)

**Comment by akien-mga** [comment]
I can confirm the issue using the test project in https://github.com/godotengine/godot/issues/8090#issuecomment-287848651.

If someone feels like bisecting the issue, that would be very welcome :)

**Comment by akien-mga** [comment]
That's probably a regression from 5b556ca, ping @lonesurvivor.

**Comment by akien-mga** [comment]
The fix should be trivial, if someone feels like working on it :)

**Comment by akien-mga** [comment]
Fixed with #8242 and #8317.
