### ISSUE TITLE
[Android][C#] Startup crash when C# script assign to node

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#80904]
### Godot version

4.2.dev.mono.custom_build.8e0346bad

### System information

macOS

### Issue description

If a C# script is attached to a node, the Android export will crash at startup.
Error: 
```
2023-08-22 23:01:39.630   680-680   audit                   auditd                               E  type=1400 audit(1692738099.618:201185): avc:  granted  { execute } for  pid=22924 comm="VkThread" path="/data/data/com.godot.game/cache/data_AndroidTest_android_arm64/libhostfxr.so" dev="sda29" ino=3147479 scontext=u:r:untrusted_app:s0:c44,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c44,c257,c512,c768 tclass=file SEPF_SM-A805F_11_0010 audit_filtered
2023-08-22 23:01:39.631   680-680   audit                   auditd                               E  type=1327 audit(1692738099.618:201185): proctitle="com.godot.game"
2023-08-22 23:01:39.632   680-680   audit                   auditd                               E  type=1400 audit(1692738099.628:201186): avc:  granted  { execute } for  pid=22924 comm="VkThread" path="/data/data/com.godot.game/cache/data_AndroidTest_android_arm64/libhostpolicy.so" dev="sda29" ino=3147480 scontext=u:r:untrusted_app:s0:c44,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c44,c257,c512,c768 tclass=file SEPF_SM-A805F_11_0010 audit_filtered
2023-08-22 23:01:39.926 22924-23668 godot                   com.godot.game                       E  USER ERROR: .NET: GodotPlugins initialization failed
2023-08-22 23:01:39.926 22924-23668 godot                   com.godot.game                       E     at: initialize (modules/mono/mono_gd/gd_mono.cpp:431)
2023-08-22 23:01:40.346 22924-23668 libc                    com.godot.game                       A  FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7779eb9704)
2023-08-22 23:01:40.431  1094-1919  InputDispatcher         system_server                        E  channel '87ad991 com.godot.game/com.godot.game.GodotApp (server)' ~ Channel is unrecoverably broken and will be disposed!
```

### Steps to reproduce

1) Create a scene
2) Make it the startup scene
3) Create a Node
4) Attach a C# script to that Node
5) Export to Android
6) Run Android
7) The application will crash on startup
8) Remove the C# script from the Node
9) Export to Android
10) Run Android
11) Notice that part of the error is there, but no crash happens

### Minimal reproduction project

[AndroidTest.zip](https://github.com/godotengine/godot/files/12413013/AndroidTest.zip)

**Comment by scgm0** [comment]
My c# project export to android runs fine, is use_gradle_build one of the requirements?

**Comment by scgm0** [comment]
Minimal reproduction project：
Not using use_gradle_build
![图片](https://github.com/godotengine/godot/assets/52148221/e86f18c0-7c7d-445d-a548-b0036d6dc21e)
运行良好

https://github.com/godotengine/godot/assets/52148221/b8afeb11-32b0-410d-ba60-1bfba9b08ca5

**Comment by scgm0** [comment]
Using use_gradle_build

https://github.com/godotengine/godot/assets/52148221/b4acc71a-2dba-44b8-ab3c-45c78fdc5f75

No crash.

![图片](https://github.com/godotengine/godot/assets/52148221/06d46828-3321-4c56-860b-3c76ff3713f8)

**Comment by scgm0** [comment]
Here's my info.

v4.2.dev.mono.custom_build [8e0346bad]

Godot v4.2.dev.mono (8e0346bad) - Arch Linux #0~20230817.g1d10c33 SMP PREEMPT_DYNAMIC Thu Aug 17 10:29:41 UTC - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.98) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

HarmonyOS 3.0.0 (Android 12)

**Comment by duarteroso** [comment]
Interesting.
Just tried from Windows and I get the same crash.
Will have to try on Linux later on.

On both I'm using:
- Godot 4.2.dev.mono.custom_build.8e0346b
- .NET7 (7.0.400)
- Android Studio Flamingo (2022.2.1)
- Android 11 (Samsung A80)

Systems:
macOS 13.5.1
Windows 10

**Comment by GeorgeS2019** [comment]
@Faolan-Rad 

Can your approach provide a path of making Android Export with Godot4 c# (using [**LibGodot GDExtension**](https://github.com/godotengine/godot/pull/72883#issuecomment-1689552035)) Solving this in near Future?

What can we do when it is merged?
What steps yet needed to merge it?

**Comment by Faolan-Rad** [comment]
well it could help it would make it where it is not godot exporting for android it is you building your c# application for android

**Comment by duarteroso** [comment]
Tried on Linux, exact same crash.
If @scgm0 manages to build and run, it must be the way I build the whole toolchain?

---

### macOS

#### Start by building the editor and the Android template

```sh
scons p=macos target=editor module_mono_enabled=yes
scons p=android target=template_debug module_mono_enabled=yes
```

#### Build the Android template
```sh
cd platform/android/java
./gradlew generateGodotTemplates
cd ../../..
```

#### Generate the glue
```sh
./bin/godot.macos.editor.x86_64.mono --generate-mono-glue modules/mono/glue
```

#### Build the .NET assemblies
```sh
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos
```

#### Copy the Android binaries to 
```sh
cp ./bin/android_source.zip $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
cp ./bin/android_build.apk $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
```

---

Do these steps sound about right?

**Comment by scgm0** [comment]
> Tried on Linux, exact same crash. If @scgm0 manages to build and run, it must be the way I build the whole toolchain?
> 
> ```
> Godot v4.2.dev.mono (6758a7f8c) - macOS 13.5.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 5500M - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 Threads)
> ```
> 
> ### macOS
> #### Start by building the editor and the Android template
> 
> ```shell
> scons p=macos target=editor module_mono_enabled=yes
> scons p=android target=template_debug module_mono_enabled=yes
> ```
> 
> #### Build the Android template
> 
> ```shell
> cd platform/android/java
> ./gradlew generateGodotTemplates
> cd ../../..
> ```
> 
> #### Generate the glue
> 
> ```shell
> ./bin/godot.macos.editor.x86_64.mono --generate-mono-glue modules/mono/glue
> ```
> 
> #### Build the .NET assemblies
> 
> ```shell
> ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos
> ```
> 
> #### Copy the Android binaries to
> 
> ```shell
> cp ./bin/android_source.zip $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
> cp ./bin/android_build.apk $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
> ```
> 
> Do these steps sound about right?

This is the build script I used:
```
cd ./godot
scons platform=linuxbsd -j 8 target=editor module_mono_enabled=yes lto=full linker=mold
bin/godot.linuxbsd.editor.x86_64.mono --headless --generate-mono-glue modules/mono/glue
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd

scons platform=android target=template_release arch=arm64v8 -j 8 module_mono_enabled=yes
scons platform=android target=template_debug arch=arm64v8 -j 8 module_mono_enabled=yes
cd platform/android/java
./gradlew generateGodotTemplates
```

Then the custom_template configured in godot：
![图片](https://github.com/godotengine/godot/assets/52148221/3289936d-4f78-4bda-9955-0f496aabe37f)

**Comment by duarteroso** [comment]
> > Tried on Linux, exact same crash. If @scgm0 manages to build and run, it must be the way I build the whole toolchain?
> > ```
> > Godot v4.2.dev.mono (6758a7f8c) - macOS 13.5.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 5500M - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 Threads)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### macOS
> > #### Start by building the editor and the Android template
> > ```shell
> > scons p=macos target=editor module_mono_enabled=yes
> > scons p=android target=template_debug module_mono_enabled=yes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Build the Android template
> > ```shell
> > cd platform/android/java
> > ./gradlew generateGodotTemplates
> > cd ../../..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Generate the glue
> > ```shell
> > ./bin/godot.macos.editor.x86_64.mono --generate-mono-glue modules/mono/glue
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Build the .NET assemblies
> > ```shell
> > ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Copy the Android binaries to
> > ```shell
> > cp ./bin/android_source.zip $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
> > cp ./bin/android_build.apk $HOME/Library/Application Support/Godot/export_templates/4.2.dev.mono
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do these steps sound about right?
> 
> This is the build script I used:
> 
> ```
> cd ./godot
> scons platform=linuxbsd -j 8 target=editor module_mono_enabled=yes lto=full linker=mold
> bin/godot.linuxbsd.editor.x86_64.mono --headless --generate-mono-glue modules/mono/glue
> ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=linuxbsd
> 
> scons platform=android target=template_release arch=arm64v8 -j 8 module_mono_enabled=yes
> scons platform=android target=template_debug arch=arm64v8 -j 8 module_mono_enabled=yes
> cd platform/android/java
> ./gradlew generateGodotTemplates
> ```
> 
> Then the custom_template configured in godot： ![图片](https://user-images.githubusercontent.com/52148221/262832169-3289936d-4f78-4bda-9955-0f496aabe37f.png)

No luck 😞

**Comment by duarteroso** [comment]
Running the game no longer crashes, but another error occurs #81242

**Comment by akien-mga** [comment]
To be clear, you need to generate the Mono glue before building Android export templates, otherwise they don't know any of the Godot API.

**Comment by duarteroso** [comment]
> To be clear, you need to generate the Mono glue before building Android export templates, otherwise they don't know any of the Godot API.

Is it not this step?
´´´
./bin/godot.macos.editor.x86_64.mono --generate-mono-glue modules/mono/glue
´´´

And then this?
´´´
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --godot-platform=macos
´´´

**Comment by akien-mga** [comment]
Yes, but these should be run before `scons p=android ...` so that the build can use the generated files.
