### ISSUE TITLE
GDShader Render_Mode world_vertex_coords requires referencing VERTEX

### ISSUE THREAD

**Issue by Dabnabbit** [godotengine/godot#80917]
### Godot version

4.1.1 Stable

### System information

Windows 11, RTX 3070TI, Vulcan

### Issue description

Here's another odd-ball one for y'all. 

When using a Spatial GDShader, if you apply the render_mode 'world_vertex_coords', the shader will produce really bad artifacts on the material/mesh surface UNTIL you attempt to assign a value to the VERTEX variable in the vertex() shader portion. Oddly enough you do not have to set it, and it never even has to be called or evaluated to eliminate the artifacts, see the following example:
![image](https://github.com/godotengine/godot/assets/8258356/39cef9dc-1a31-4e34-9efd-669a6a2a7b7e)
uncommenting the 
```
	if(false) {
		VERTEX = VERTEX;
	}
```
will result in the artifacts disappearing, even though logically the code is never executed and a value should never be assigned. 

Comment the if statement back out and the artifacts return.
[MRP_WorldVertexCoords.zip](https://github.com/godotengine/godot/files/12415916/MRP_WorldVertexCoords.zip)

### Steps to reproduce

Create a new Spatial shader, and add the line
```render_mode world_vertex_coords;```

You will not see artifacts on the material/mesh.

### Minimal reproduction project

open the main.gdshader and comment/uncomment the if(false) statement to demonstrate the issue.

**Comment by bitsawer** [comment]
I can repro this on NVIDIA GTX 970. Some similarities to Godot 3 issue https://github.com/godotengine/godot/issues/33165, see clayjohn's comment: https://github.com/godotengine/godot/issues/33165#issuecomment-1657836418

Looks like writing to VERTEX is required to avoid this issue, only reading it is not enough. There are some cases where Godot detects when certain builtins (like COLOR, NORMAL etc.) are used and generates different shader code, but that doesn't seem to apply here (but I didn't check very deeply).

Would be interesting if anyone with ATI or Intel GPU can reproduce this issue.

**Comment by Dabnabbit** [comment]
Hey @bitsawer thanks for the verification, however, as a slight correction you do NOT need to write to VERTEX, as can be demonstrated in the MRP by changing it to only get VERTEX, you only need to reference/evaluate it to resolve the artifacts. 

Stranger yet, you don't even have to actually ever have the logic that references the VERTEX line ever execute, it only needs to exist, again, reference the MRP and see that the if(false) {} condition should NEVER actually run the line that evaluates VERTEX, however it will still resolve the artifacts. Super weird one.

**Comment by bitsawer** [comment]
Interestingly, on my machine a write to VERTEX needed to avoid those artifacts. For example, this doesn't fix things and still shows artifacts:

```glsl
void vertex() {
    if (false) {
        vec3 test = VERTEX;
    }
}
```

This works (also read+write  like `VERTEX *= 1.0;` also works):

```glsl
void vertex() {
    if (false) {
        VERTEX = VERTEX;
    }
}
```

Considering this might be some NVIDIA driver/device oddity, it's not too unusual to have different behavior between devices or driver versions. Also disabling depth prepass fixes this for me, so it might be some issue with `invariant gl_Position` handling in Godot shader code or just some driver bug, there are a few known NVIDIA specific shader isses here if you search for them. So depending on what causes it just referencing or writing to it might help NVIDIA shader compiler/analyzer to fix something. 

Also, sometimes in shaders when branching if the branch is divergent the device can execute both branches and then it simply throws away the result that didn't happen. However, in this case I would assume even the simplest shader compiler could optimize away a branch using a constant expression, so there might be some weird analyzer trickery etc. going on.

**Comment by clayjohn** [comment]
This is a fascinating issue. We check if a shader does any number of vertex modifications, if it doesn't, then we can fallback to the default shader for doing the depth prepass (and thus most of our objects in the depth prepass share a shader!). Accordingly, we have a check for if VERTEX is written to. It appears we don't check if ``world_vertex_coords`` therefore, the depth pass is falling back to the default shader and causing a clash with the user shader.

The solution will be to check for the presence of ``world_vertex_coords`` here:

https://github.com/godotengine/godot/blob/6da4ad16624484398331f393b503f8b5e2888c51/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L3477-L3478

**Comment by Dabnabbit** [comment]
Glad it sounds like a potential solution has been found, and interesting to hear what the cause was. Thanks @clayjohn, hope you guys are getting some good use out of the multitude of MRPs I've been producing to get some much needed polish and love on Godot for use as a 3D engine. I have a few more to post for the NavMesh in general, including the A-star pathing algorithm, honestly it may have dire need of an overhaul completely.
