### ISSUE TITLE
ANDROID_SDK_ROOT is deprecated, use ANDROID_HOME instead

### ISSUE THREAD

**Issue by Mrcubix** [godotengine/godot#80910]
### Godot version

all | 6758a7f

### System information

Windows 10 21H2

### Issue description

Building export templates with scons requires user to define the `ANDROID_SDK_ROOT` variable, which has been made deprecated long ago, `ANDROID_HOME` should be used instead.

This will avoid people having to figure out why android isn't considered a valid platform when having a proper setup.

see [this section](https://developer.android.com/tools/variables#:~:text=ANDROID_SDK_ROOT%2C%20which%20also%20points%20to%20the%20SDK%20installation%20directory%2C%20is%20deprecated.%20If%20you%20continue%20to%20use%20it%2C%20Android%20Studio%20and%20the%20Android%20Gradle%20plugin%20will%20check%20that%20the%20old%20and%20new%20variables%20are%20consistent.) | [fallback](https://developer.android.com/tools/variables#envar)

They may not check for `ANDROID_SDK_ROOT` in the future, so it's advised to use this newer variable instead.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by philippesic** [comment]
Should just be replacing all instances of ```ANDROID_SDK_ROOT``` with ```ANDROID_HOME``` if I'm not mistaken. 

Will open a pr upon confirmation.

**Comment by Calinou** [comment]
For reference, `ANDROID_HOME` used to be read as a fallback until https://github.com/godotengine/godot/commit/48efd563e4bac896cbc4b11df08f1841cd2877f6.

**Comment by Mrcubix** [comment]
Note that the SDK & the MAUI check tool for example, does not require the path to be strictly of the root, they may also check for the presence of an additional folder called `android-sdk` in the case the specified folder isn't exactly the root

**Comment by duarteroso** [comment]
Had some issues building because of just that 👍🏽 
https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/platform/android/detect.py#L46

**Comment by Calinou** [comment]
> Should just be replacing all instances of `ANDROID_SDK_ROOT` with `ANDROID_HOME` if I'm not mistaken.
> 
> Will open a pr upon confirmation.

Feel free to open a PR for this, but please read `ANDROID_SDK_ROOT` as a fallback to avoid breaking existing builds (especially on CI).
