### ISSUE TITLE
`GridContainer` does not position and resize its children in a grid

### ISSUE THREAD

**Issue by SandroMaglione** [godotengine/godot#80922]
### Godot version

v4.1.stable.official.970459615

### System information

MacBook Pro - macOS 13.3.1

### Issue description

I am having an hard time with layouts in general, and in this case specifically with `GridContainer`.

I tried to recreate the [same example shown in the docs](https://docs.godotengine.org/en/stable/tutorials/ui/gui_containers.html#grid-container):

![containers_grid](https://github.com/godotengine/godot/assets/10065056/a64e93fa-6c4d-4138-b15b-cefee1fcc8d9)

I create the same node tree, but the result looks different:

<img width="903" alt="Screenshot 2023-08-23 at 11 05 59" src="https://github.com/godotengine/godot/assets/10065056/b6c1007d-6d24-4194-83d2-8748a9f393a2">

I expect that the `GridContainer` would size its child nodes to fit the available space in 2 equally sized columns. As you can see, the buttons are not resized at all.

This is even worst when the child node is a custom layout. The `GridContainer` does not reside its children and they all have a 0px width, making the scene look empty.

### Steps to reproduce

Try to recreate the example in the docs in a new Godot project should be enough to test the issue.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
You need to enable set alignment with Expand flag (in the menu at the top toolbar).

**Comment by SandroMaglione** [comment]
After some attempts at changing the expand values of both container and child nodes I was able to achieve horizontal stretching:

<img width="1064" alt="Screenshot 2023-08-23 at 13 00 38" src="https://github.com/godotengine/godot/assets/10065056/605e832d-cee4-4202-b556-22777903fdd0">

The idea is to have `Horizontal alignment` set to `fill` and `expand` **for child nodes** (no need on the container):

<img width="241" alt="Screenshot 2023-08-23 at 13 02 45" src="https://github.com/godotengine/godot/assets/10065056/1913611d-5af2-4070-86c3-516335b25acf">

<img width="1035" alt="Screenshot 2023-08-23 at 13 02 06" src="https://github.com/godotengine/godot/assets/10065056/12b6f052-2d6d-480c-ac0e-15841afc861c">

@KoBeWi Is this correct?

**Comment by KoBeWi** [comment]
Yes.

**Comment by SandroMaglione** [comment]
Great! Thanks @KoBeWi 

**Extra note**: In my case I wanted the horizontal layout to stretch (`expand`), while keeping the same height vertically. This can be achieved by setting a `Custom Minimum Size` in `Layout` for child nodes:

<img width="449" alt="Screenshot 2023-08-23 at 13 09 28" src="https://github.com/godotengine/godot/assets/10065056/553dc114-9d4f-42b7-b6d8-7a41f0141b7c">

<img width="881" alt="Screenshot 2023-08-23 at 13 09 46" src="https://github.com/godotengine/godot/assets/10065056/f327fe95-6dd4-4d73-b938-11c53fef5cec">
