### ISSUE TITLE
AnimationTreePlayer: animation blend/mix slider is not working in the editor

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#8093]
**Operating system or device - Godot version:**
In Godot 2.1 everything is working fine. In Godot 2.1.1 bug is present already.

**Issue description:**
Blending is working properly in Godot 2.1: 
![blend_good](https://cloud.githubusercontent.com/assets/6129594/24119250/d05dcae2-0db0-11e7-962c-885d43fbdf1f.gif)

Since Godot 2.1.1 it's not working anymore:
![blend_bad](https://cloud.githubusercontent.com/assets/6129594/24119261/dc246f7a-0db0-11e7-938f-0280e5587765.gif)

Also this is an editor bug, during runtime everything seems to work fine, so it might be possible it's just something with ui of blend/mix node.

**Steps to reproduce:**
1. Download Platformer 3D demo
2. Open "Player.scn"
3. Select AnimationTreePlayer node
4. Try to change animation blending in "gun" node of Animation Tree Player

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
I was trying to track which commits could introduce this behavior, I think it was maybe a https://github.com/godotengine/godot/commit/cfa11777c0a031c0f3f556b27240dc4d789e3cd6 or https://github.com/godotengine/godot/pull/7000/files#diff-f829b9442a4bdc69228ad6d794c58986
but it's based only on a fact that merging those was done more-less in proper time to cause this in 2.1.1

**Comment by kubecz3k** [comment]
@m4nu3lf maybe you could take a look? :)

**Comment by m4nu3lf** [comment]
@kubecz3k This looks like an UI bug to me, when I made that change I made extensive testing, I would have noticed something like that, I'll have a look when I get a change though

**Comment by m4nu3lf** [comment]
I've not been able to reproduce it on the current 2.1 branch

**Comment by kubecz3k** [comment]
Super strange, I compiled 2.1 opened platformer demo and bug is still there :(
![blend_ui_bug](https://user-images.githubusercontent.com/6129594/27927450-11c37d9e-628c-11e7-9f2a-7a7fbb5fba3a.gif)

**Comment by bojidar-bg** [comment]
Regression of #6833 / #5773?

**Comment by kubecz3k** [comment]
@bojidar-bg thanks! That's it exactly! After setting `step` to 0.01 it works nice again. But I'm not sure if this fix is good, or maybe I should look somewhere inside `AnimationTreePlayer` code to set that variable only for those nodes. Will look into it.

**Comment by kubecz3k** [comment]
Ok I think I gathered enough informations to propose a pr and raise some questions :P :)

**Comment by Ranoller** [comment]
I can confirm that the regression was in https://github.com/godotengine/godot/commit/e3dc319f78c16b6f24081ae28c868242fcaed4ed. Bug is still present in 2.1.4 compiled at 29/11/2017
