### ISSUE TITLE
Creating a C# plugin results in cyclic inclusion errors

### ISSUE THREAD

**Issue by Renari** [godotengine/godot#80946]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Attempting to activate a newly created C# plugin will trigger this error:
```
  Another resource is loaded from path 'res://addons/Test/Test.cs' (possible cyclic resource inclusion).
```
 

### Steps to reproduce

1. Project -> Plugins -> Create New Plugin
2. ![image](https://github.com/godotengine/godot/assets/1839179/da9548ba-1d60-416c-8eaa-2486db4c3e13)
3. The new plugin cannot be enabled due to a cyclic resource inclusion error.

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/12423675/Example.zip)

**Comment by duarteroso** [comment]
Could be related to #80883 
See https://github.com/godotengine/godot/issues/80883#issuecomment-1687783240
Please vote up 😅   https://github.com/godotengine/godot/issues/80883#issuecomment-1688246083

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80883.
