### ISSUE TITLE
Undoing guide creation makes empty array in scene file

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#80947]
### Godot version

4.2 dev3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Basically variation of #33995

### Steps to reproduce

1. Open 2D scene
2. Drag a guide
3. Undo
4. Save

### Minimal reproduction project

N/A

**Comment by coumcashier** [comment]
relevant code

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/editor/plugins/canvas_item_editor_plugin.cpp#L1143
