### ISSUE TITLE
web apps removing https and custom port

### ISSUE THREAD

**Issue by pietru2004** [godotengine/godot#80949]
### Godot version

4.1

### System information

Windows 10 Forward+

### Issue description

I use httpRequest to recive data from API
url is something like https://testdb.example.com:port/apipath
godot as web app sends fetch requests as http://testdb.example.com:80/apipath

it causes mixed content errors

Using godot web app + nginx proxy manager + nginx + pocketbase
Tested on browsers: firefox, chrome

Also if I copy that request into console and send it after fixing url it returns 200 - success

Also my port for https is not 443 cause router I have at home is occupying it and it is not possible to be changed atm

### Steps to reproduce

have domain that you can add subdomains to

host godot web app on one sub domain, host api on second

example code for http request (works with pocketbase)

```
const db_base_adress := "https://testdb.example.com:port"

func _ready():
	connect("request_completed",_request_completed)

func get_records(collection,token:="",options:={})->Dictionary:
	var body = JSON.stringify(options)
	var error = request(db_base_adress+"/api/collections/"+collection+"/records", ["content-type: application/json", "Authorization: "+token], HTTPClient.METHOD_GET, body)
	if error != OK:
		push_error("An error occurred in the HTTP request.")
	return await self.response_recived

signal response_recived(response:Dictionary)
func _request_completed(_result, _response_code, _headers, body):
	var json = JSON.new()
	json.parse(body.get_string_from_utf8())
	var response = json.get_data()
	if _response_code!=200:
		pass
	#print(response)
	emit_signal("response_recived",response)
```

### Minimal reproduction project

N/A

**Comment by coumcashier** [comment]
v4.1.stable.official [970459615]

Hi [pietru2004](https://github.com/pietru2004)

I am a little unclear on what is the error.
I am unable to reproduce the error.
I tested the scenario with 2 domains and self signed certificate.
As you can see from the screenshot. The request which uses a custom port and HTTPS works correctly.

Godot making a HTTPS request on port 4443

![Screenshot 2023-08-24 131301](https://github.com/godotengine/godot/assets/122149176/6e79276b-a658-4506-b6d4-8975a16c318e)

The Godot app is served from https://fake1.local:4443/godot-test.html
The app makes a request to https://fake2.local:4443

   	extends Node2D

	func _ready():
		$HTTPRequest.request_completed.connect(_on_request_completed)
		$HTTPRequest.request("https://fake2.local:4443")

	func _on_request_completed(result, response_code, headers, body):
		var asdf = body.get_string_from_utf8()
		print(asdf)


My server configuration

    import http.server, ssl
    from http.server import HTTPServer, SimpleHTTPRequestHandler, test

	class CORSRequestHandler (SimpleHTTPRequestHandler):
		def end_headers (self):
			self.send_header('Access-Control-Allow-Origin', '*')
			self.send_header('Cross-Origin-Opener-Policy', 'same-origin')
			self.send_header('Cross-Origin-Embedder-Policy', 'require-corp')
			SimpleHTTPRequestHandler.end_headers(self)

	server_address = ('localhost', 4443)
	httpd = http.server.HTTPServer(server_address, CORSRequestHandler)
	httpd.socket = ssl.wrap_socket(httpd.socket,
								server_side=True,
								certfile='C:/Users/asdf/localhost.pem',
								ssl_version=ssl.PROTOCOL_TLS)
	httpd.serve_forever()

The app is able to read and print the response HTML.

**Comment by pietru2004** [comment]
I get error about mixed content while asking pocketbase for answer, also it asks for aplication/json

Also it might be because you connect on localhost and browser treats it diffrently

Gona send screen when I sit at pc, also I use lets encrypt cert.

**Comment by pietru2004** [comment]
okay error changed now it shows
![obraz](https://github.com/godotengine/godot/assets/51274570/9410bc14-eabd-4f43-8464-05fd9962f73c)
and some more errors, and when in "private" window it fully works... it might have been mayby some header or cookies now updating that did not reload on client side when uploading new project files into web server, gona try reloading browser

**Comment by pietru2004** [comment]
Screens - left is normal window, right is firefox private mode window

![obraz](https://github.com/godotengine/godot/assets/51274570/89271dfb-be0a-4c2b-914e-42c9c295c3ee)
![obraz](https://github.com/godotengine/godot/assets/51274570/8c8c4a67-82e5-43e5-819d-2920bb2eaf22)

**Comment by pietru2004** [comment]
I think my browser must be caching web app making it not reload properly when I upload new build
