### ISSUE TITLE
custom export variable descriptions don't show if in a category.

### ISSUE THREAD

**Issue by Insane-Owl** [godotengine/godot#80942]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When exporting a variable, you can usually add a custom description to it by adding `## this variable does that` above it, and when hovered over it shows the description. (like so)
![Screenshot 2023-08-23 144615](https://github.com/godotengine/godot/assets/78328941/e1d617be-d1da-410e-b915-8a7561fc8cbe)

But when you export a custom category, the variables under it say "no description." (like so)
![Screenshot 2023-08-23 150139](https://github.com/godotengine/godot/assets/78328941/c579957f-94d8-46a3-8723-01f69e0f55ce)

Here's the code
![Screenshot 2023-08-23 150206](https://github.com/godotengine/godot/assets/78328941/0f8d2dbb-d34b-4b32-9caa-7f3a0fbb0871)

### Steps to reproduce

1. export a category
2. add a variable below it
3. add a custom description to said variable

### Minimal reproduction project

[custom description bug.zip](https://github.com/godotengine/godot/files/12422519/custom.description.bug.zip)

**Comment by dalexeev** [comment]
* See also #78934.
