### ISSUE TITLE
StandardMaterial3D inherited class/resource: "Godot 3.x SpatialMaterial remapped parameter not found" printed on setting custom properties defined with _get_property_list()

### ISSUE THREAD

**Issue by Okxa** [godotengine/godot#80958]
### Godot version

v4.1.stable.arch_linux

### System information

Arch Linux

### Issue description

Each time a custom property that is defined with `_get_property_list()` is set, this warning is printed:

`scene/resources/material.cpp:3187 - Godot 3.x SpatialMaterial remapped parameter not found: /some_prop`

This line comes from this function, which seems to remap 3.x properties to 4.x properties.

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/scene/resources/material.cpp#L3098-L3100

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/scene/resources/material.cpp#L3190-L3190

This warning is not printed when `@export` is used.

### Steps to reproduce

1. Create a class inheriting from `StandardMaterial3D` and Define a custom property with `_get_property_list()` (And use `@tool`):

```gdscript
@tool
class_name CustomMaterial3D
extends StandardMaterial3D

# getters/setters not required for demonstration

func _get_property_list():
    var property_list = []
    property_list.append({
        "type": TYPE_STRING,
        "name": "/some_prop",
        "hint": PROPERTY_HINT_NONE,
        "hint_string": "",
        "usage": PROPERTY_USAGE_DEFAULT
    })
    return property_list
```

2. create a resource from that class
3. Set the property in editor
4. Error is spammed in the output.

### Minimal reproduction project

-

**Comment by AThousandShips** [comment]
This error still happens if you add setters and getters?

**Comment by Okxa** [comment]
> This error still happens if you add setters and getters?

Yes, but happens without them too. I guess the function is called before that.

For completeness, here is a class with _get/_set:
```gdscript
@tool
class_name CustomMaterial3D
extends StandardMaterial3D

var some_var: String = ""

func _get(property):
    if property == "/test":
        return some_var

func _set(property, value):
    if value:
        if property == "/test":
            some_var = value

func _get_property_list():
    var property_list = []
    property_list.append({
        "type": TYPE_STRING,
        "name": "/test",
        "hint": PROPERTY_HINT_NONE,
        "hint_string": "",
        "usage": PROPERTY_USAGE_DEFAULT
    })
    return property_list
```

**Comment by AThousandShips** [comment]
Add `return true` after `some_var = value`

**Comment by Okxa** [comment]
Well consider this as not a bug then, as per [docs](https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-method-set) `_set` should return boolean:

>Should set the property to value and return true, or false if the property should be handled normally.

I guess I just assumed my implementation was correct as with no other class else errors were not printed when not returning anything from `_set()`
