### ISSUE TITLE
Subwindows do not recieve events when unfocused when gui_embed_subwindows is enabled

### ISSUE THREAD

**Issue by Mazianni** [godotengine/godot#80953]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.1694) - AMD Ryzen 7 3800XT 8-Core Processor (16 Threads)

### Issue description

When utilizing the Window node with gui_embed_subwindows set to true in project settings, events are not passed to it or it's children unless the window is focused.

### Steps to reproduce

See Reproduction Project:
1. Run
2. Click Subwindow
3. Wiggle mouse around subwindow.
4. Observe console output. There should be printed messages.
5. Click off subwindow
6. wiggle mouse around subwindow
7. There is no output.

### Minimal reproduction project

[WindowBugReport.zip](https://github.com/godotengine/godot/files/12426716/WindowBugReport.zip)

**Comment by Sauermann** [comment]
In your MRP you show this bug for `mouse_entered` & `mouse_exited` signals.
`mouse_entered` & `mouse_exited` signals have been fixed in #67791 in current master.
Can you please try Godot v4.2-dev3 to to verify if your problem has been already fixed?

**Comment by Mazianni** [comment]
I'll give that a shot later today.

**Comment by akien-mga** [comment]
Assuming fixed by #67791.
