### ISSUE TITLE
Can't run an x86_32 game that was exported from an x86_64 bit host machine

### ISSUE THREAD

**Issue by fatduckling** [godotengine/godot#80963]
### Godot version

v4.1.1 bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5

### System information

Build machine: Debian GNU/Linux 11 (bullseye) 64 bit
Testing machine: Debian GNU/Linux 12 (bookworm) 32 bit

### Issue description

Hi,

I built a simple game with Godot 4.1.1 on my host machine `Debian GNU/Linux 11 (bullseye) 64 bit`. The game uses GDExtension. When I export the game to `x86_64` and copy the files to another Linux x64 computer, it works fine. However, when I export the game to `x86_32` architecture (while also compiling the C++ game library in `x86_32` arch), and copy the files to a Linux x32 computer, I can't run the game. I get the following error on the 32 bit machine:

```
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
OpenGL API 4.5 (Core Profile) Mesa 22.3.6 - Compatibility - Using Device: Mesa/X.org - llvmpipe (LLVM 15.0.6, 256 bits)
 
================================================================
handle_crash: Program crashed with signal 8
Engine version: Godot Engine v4.1.1.stable.official (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] linux-gate.so.1(__kernel_sigreturn+0) [0xb7f86564] (??:0)
[2] godot::ClassDB::bind_virtual_method(godot::StringName const&, godot::StringName const&, void (*)(void*, void const* const*, void*)) (??:0)
[3] void godot::ClassDB::_register_class<BoxObject2, false>(bool) (??:0)
[4] initialize_game_module(godot::ModuleInitializationLevel) (??:0)
[5] godot::GDExtensionBinding::initialize_level(void*, GDExtensionInitializationLevel) (??:0)
[6] ./game.x86_32() [0xabbe68c] (??:0)
[7] ./game.x86_32() [0x878e641] (??:0)
[8] ./game.x86_32() [0x86a4074] (??:0)
[9] /lib/i386-linux-gnu/libc.so.6(+0x232c5) [0xb7c232c5] (??:0)
[10] /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x88) [0xb7c23388] (??:0)
[11] ./game.x86_32() [0x86c6444] (??:0)
-- END OF BACKTRACE --
================================================================
```

In my host machine (x64), I make sure to set the binary format architecture to x86_32 (see screenshot):
![Screenshot from 2023-08-25 01-10-57](https://github.com/godotengine/godot/assets/3345706/8dc3bf3e-f43c-4a3b-a506-cc8a17257f5e)

This is the contents of my `game.gdextension`

```
[configuration]

entry_symbol = "game_init_extension"
compatibility_minimum = 4.1

[libraries]

linux.x86_64 = "res://libGameLibrary64.so"
linux.x86_32 = "res://libGameLibrary32.so"
```

I've attached a sample reproducible game (with a simple C++ library) so you can test it.
 

### Steps to reproduce

1. Make sure you have godot-cpp set up for both Linux 32 and 64 bit libraries. https://github.com/godotengine/godot-cpp
2. Download the reproducible project in this ticket
### Compile the simple game library
I provided the 32 and 64 bit game library inside the `game/` folder, but you can compile it yourself using the following commands:
    1. First, change `set(GODOT_ROOT /home/saleem/software/godot/godot-cpp)` in the `CMakeLists.txt` file to point to your godot-cpp installation path
    2. Compile the 32 bit library first:
```
saleem@saleem-Z790:/tmp/Empty2$ mkdir build
saleem@saleem-Z790:/tmp/Empty2$ cd build
saleem@saleem-Z790:/tmp/Empty2/build$ cmake ..
...
-- Build files have been written to: /tmp/Empty2/build
saleem@saleem-Z790:/tmp/Empty2/build$ make -j23
...
[100%] Linking CXX shared library libGameLibrary.so
[100%] Built target GameLibrary
```
 

1. This will produce a library `libGameLibrary.so`. Rename that `libGameLibrary32.so` and put that inside the `game/` folder.
2. Compile the 64 bit version. In the `CMakeLists.txt`, delete the lines associated with the `-m32` and uncomment out the 64 bit lines so your `CMakeLists.txt` looks like this:
```
...
set(CMAKE_CXX_FLAGS_RELEASE "-O3")

set(GODOT_LIBRARY ${GODOT_ROOT}/bin/libgodot-cpp.linux.template_debug.x86_64.a)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -m64")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -m64")

set(CMAKE_CXX_STANDARD 17)
...
```
Re-run `cmake` with the `make` command and rename the generated `.so` file to `libGameLibrary64.so` and put it inside the `game/` folder.
### Export the game
In the host machine (x64), export the game, both 64 and 32 bit versions and copy the generated game files to the respective architecture machines. You'll notice the 64 bit version works fine, but you'll see when you run the 32 bit version, you'll get the error. I'm just running Debian 11 x32 on Virtualbox to reproduce the error, but the issue also happens on my x32 laptop.

I understand that the reproducible steps are a bit challenging to follow, so I'm happy to assist developers with anything they need. Here is a **Video recording** of the steps to reproduce the issue:
[2023-08-25 02-12-16.mp4.zip](https://github.com/godotengine/godot/files/12431429/2023-08-25.02-12-16.mp4.zip)

### Minimal reproduction project

[Empty2.zip](https://github.com/godotengine/godot/files/12430864/Empty2.zip)

**Comment by fatduckling** [comment]
Here is the screenshot of the `lscpu` command on the 32 bit machine

![VirtualBox_Debian 11 32 bit_25_08_2023_01_38_10](https://github.com/godotengine/godot/assets/3345706/f4a69bf0-f569-406e-8a08-43df581b3203)

**Comment by Mrcubix** [comment]
This is not specific to linux

```log
Starting program: E:\Godot\Color Tiles\build\win-x86\Color-Tiles-win-x86.exe
[New Thread 9760.0x24b0]
[New Thread 9760.0x1f98]
[New Thread 9760.0x1914]
[New Thread 9760.0x4d9c]
[New Thread 9760.0x2d74]
[New Thread 9760.0x27a8]
[New Thread 9760.0x4d38]
[New Thread 9760.0x1148]
[New Thread 9760.0x3be4]
[New Thread 9760.0x20e0]
[New Thread 9760.0x480]
[New Thread 9760.0x22ec]
[New Thread 9760.0x2734]
[New Thread 9760.0x48b4]
[New Thread 9760.0x5520]
[New Thread 9760.0x2b00]
[New Thread 9760.0x38c]
[New Thread 9760.0x4508]
[New Thread 9760.0x18b4]
Godot Engine v4.1.1.stable.mono.official.bd6af8e0e - https://godotengine.org
[New Thread 9760.0x37a4]
[New Thread 9760.0x4e0c]
[New Thread 9760.0x2480]
[Thread 9760.0x4e0c exited with code 0]
[Thread 9760.0x2480 exited with code 0]
[New Thread 9760.0x32c4]
[Thread 9760.0x37a4 exited with code 0]
[New Thread 9760.0x53bc]
[New Thread 9760.0x499c]
[New Thread 9760.0x454c]
OpenGL API 3.3.0 NVIDIA 536.67 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1060 6GB
[New Thread 9760.0x4474]

[New Thread 9760.0x521c]
[New Thread 9760.0x3f34]
[New Thread 9760.0x3d18]
warning: Profiler was prevented from loading notification profiler due to app settings.
  Process ID (decimal): 9760.  Message ID: [0x2509].
[New Thread 9760.0xe9c]
[New Thread 9760.0x53f8]
[New Thread 9760.0x2060]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000008 in ?? ()
```

**Comment by fatduckling** [comment]
Hi @Calinou After upgrading my project to 4.2 RC2, this seems to have been fixed. I'm able to compile on Debian 11 x64 using the `-m32` flags and then run it on debian 11 x32

@Mrcubix Please confirm if the issue still persists for you on 4.2 RC2. 
Thanks

**Comment by Mrcubix** [comment]
Can't confirm as i don't have access to a 32 bits machine anymore

**Comment by dsnopek** [comment]
Seems like we can close this one now! If there are still any issues, we can re-open
