### ISSUE TITLE
Can't set tab's hover color by theme

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#80989]
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Windows 10, 64bit

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/ccdac68c-a60d-491b-a406-d6e3bc1c95ae)
![GIF](https://github.com/godotengine/godot/assets/35988767/7d230faf-0260-4bc3-92e8-11cd026931a8)

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by MewPurPur** [comment]
You mean font hovered color?

@Calinou
