### ISSUE TITLE
 Web export fails to display Gridmap that works well in editor and Windows export

### ISSUE THREAD

**Issue by isaaccp** [godotengine/godot#80980]
### Godot version

4.1.1-stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated GeForce GTX 1050 () - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 Threads)

### Issue description

I have a project that I have been developing for a while. It uses a gridmap with a meshlib to display stages and it works fine in the editor and on Windows exports. Today I tried to run it in Web 5 for the first time and everything works okay except the gridmap is not displayed at all.

The javascript console in Chrome shows the following error 256 times:
[.WebGL-00001640BE358700] GL_INVALID_OPERATION: Vertex shader input type does not match the type of the bound vertex attribute.
(even with a single tile in the gridmap)

The problem occurs in both Chrome (116.0.5845.110 (Official Build) (64-bit) (cohort: M116_Respin)) and Firefox (116.0.3).

Scene when run from the editor:
![image](https://github.com/godotengine/godot/assets/8712/a8672db1-eade-4b42-996f-97303de6153a)

Scene using Web 5 in Chrome:
![image](https://github.com/godotengine/godot/assets/8712/dbd3c7ef-65cd-4fe1-b2be-97c71319d08d)

### Steps to reproduce

Run the attached scene from the editor or a Windows export and it'll display a cylinder and a gridmap (with a single tile).

Run the attached scene on a web export (e.g. by using the editor Run in Browser or doing a full web export) and only the cylinder is displayed, with the error mentioned above.

### Minimal reproduction project

[web5_gridmap_bug.zip](https://github.com/godotengine/godot/files/12435058/web5_gridmap_bug.zip)

**Comment by isaaccp** [comment]
These are all the logs in the Chrome javascript console.

![image](https://github.com/godotengine/godot/assets/8712/4dac7665-cb3a-4216-bea9-e9eb3b4f467c)

**Comment by baptr** [comment]
I was able to repro this in v4.2.dev2.official [da81ca62a], and found that it would run and render cleanly in a web5 export if I disabled `vertex_color_use_as_albedo` for each material in the mesh library. Hopefully that helps narrow down the issue.

**Comment by isaaccp** [comment]
I can confirm that disabling vertex_color_use_as_albedo in the materials in the mesh library also fixes it for me (but this is not very convenient and hopefully we can have a fix that addresses the issue without having to do that).
