### ISSUE TITLE
Converting NAN to int outputs -9223372036854775808.

### ISSUE THREAD

**Issue by AcatXIo** [godotengine/godot#80995]
### Godot version

v4.2.dev3.official.013e8e3af

### System information

Windows 10, GLES3 (Compatibility)

### Issue description

```gdscript
print(int(NAN))
```
outputs
```gdscript
-9223372036854775808
```
that is, the minimum int value.

I believe trying to convert NAN to int should result in an error instead, since there is no real int counterpart of float NAN in GDScript currently.

For reference in Python:
```python
print(int(float('nan')))
```
outputs
```python
Traceback (most recent call last):

  File "main.py", line 1, in <module>

    print(int(float('nan')))

ValueError: cannot convert float NaN to integer
```

### Steps to reproduce

0. Run the MPR code.
1. Observe the output.

### Minimal reproduction project

```gdscript
print(int(NAN))
```

**Comment by Chaosus** [comment]
Guess it's the same as https://github.com/godotengine/godot/issues/33017?

**Comment by AcatXIo** [comment]
Basically, yes, but the extensive "steps to reproduce" section of that issue does not include the NAN case.
I'm not sure if the comment that I added there about it is sufficient, as it might be missed.
If you do consider so, feel free to close this issue.

**Comment by akien-mga** [comment]
Consolidating in #33017.
