### ISSUE TITLE
Attach node script dialogue window proposes filenames inconsistent with GDScript syle guide.

### ISSUE THREAD

**Issue by Null-Ping** [godotengine/godot#80993]
### Godot version

v4.2.dev3.official.013e8e3af

### System information

Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

When attaching a new script to a node with the "attach node script" dialogue window, it proposes a default script file name based on the name of the node the script is being attached to.
So for example: when attaching a new script to a node named "Test", the proposed script file name is Test.gd.

This is inconsistent with the [GDScript style guide (file names section)](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#file-names), which states: "Use snake_case for file names."
To follow the guide, the proposed name should be converted to snake_case instead, in this case: "test.gd".

### Steps to reproduce

0. Create a new project.
1. Add any node.
2. Rename the node to any name, or leave the default one.
3. Right click the node and click "Attach Script".
4. Observe the value in the "Path" field not following the GDScript style guide.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
There is `editor/naming/scene_name_casing` project setting. Unfortunately, the name is not successful, since there are many other types of files besides scenes. Perhaps we should add a `file_name_casing` setting? Also C# uses PascalCase.

![](https://github.com/godotengine/godot/assets/47700418/9cd72088-cf7f-499f-8c51-8163ebbfc386)

**Comment by jsjtxietian** [comment]
Maybe add a setting for `gdscript_name_casing` instead of `file_name_casing` ?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39441.
