### ISSUE TITLE
Cannot add sampler2DArray as shader global due to strict class selection

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#81008]
### Godot version

v4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 750 Ti (NVIDIA; 31.0.15.3623) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

When creating a Shader Global of type sampler2DArray:
![image](https://github.com/godotengine/godot/assets/40964335/6363c4c7-3c75-4ede-ab41-e92490502d4c)
The expected resource is Texture2DArray.
![image](https://github.com/godotengine/godot/assets/40964335/a0273932-6dae-46d4-a826-af3daa75d7a3)

Using an imported Texture2DArray does not work as they are actually imported as a CompressedTexture2DArray, and to my knowledge a normal Texture2DArray is impossible to create
![image](https://github.com/godotengine/godot/assets/40964335/73569f7e-b8f8-4dcc-a060-3c5833d06ffc)

### Steps to reproduce

1. Import a spritesheet as a Texture2DArray
2. Notice the file is imported as a CompressedTexture2DArray resource
3. Create a Shader Global of type sampler2DArray
4. Try to add your texture array but notice that it only accepts Texture2DArray, while our import is CompressedTexture2DArray. To my knowledge, a Texture2DArray is impossible to import, it will always be a compressed array.

Expected behavior: sampler2DArray lets you select both Texture2DArray and CompressedTexture2DArray resources

All of the following types should be able to used in this field:
![image](https://github.com/godotengine/godot/assets/40964335/a182110b-d160-4edd-8eb4-a01d1010c490)

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
We might need to allow some more subclasses to be used or adjust the type checks if they are too strict. Meanwhile, you might be able to use `RenderingServer.global_shader_parameter_set()` to set the CompressedTexture2DArray object directly during runtime (or in a tool script if running in editor).

**Comment by FireCatMagic** [comment]
I focused this post on the CompressedTexture2DArray but after looking at the suggested resources for a sampler2DArray that is not global, it applies to more than just the singular class i was talking about if that wasn't obvious already
Pic of all the classes a sampler2DArray spot should have:
![image](https://github.com/godotengine/godot/assets/40964335/eaf39c55-493d-45ce-8234-9c057ade7d89)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/70649 and https://github.com/godotengine/godot/issues/71789.
