### ISSUE TITLE
When using integer scaling, resizing the window to be smaller than `content_scale_size` (the original viewport size) will clip the contents.

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot#81024]
### Godot version

master

### System information

Windows

### Issue description

Follow-up to https://github.com/godotengine/godot/pull/81012#pullrequestreview-1596954975.

This causes contents of the viewport to be clipped out of the window, which is not desirable, and also causes a problem with the implemented `Window.move_to_center()` when used with embedded windows.

### Steps to reproduce

Create a 2D scene, set the window stretch mode to `canvas_items` and stretch scale mode to `integer` in the project settings, and resize the window to be smaller than the original viewport size. Result demonstrated in linked comment.

### Minimal reproduction project

In linked comment.

**Comment by Jordyfel** [comment]
In my opinion, the reasonable solution is to force the window minimum size to be equal to `content_scale_size` while using integer scaling, since integer scaling is supposed to be used with small content sizes anyway.

**Comment by dalexeev** [comment]
Perhaps we could note in the docs that with integer scaling it is recommended to set a minimum window size?
