### ISSUE TITLE
Shape2D not showing in 2D editor when used as export resource

### ISSUE THREAD

**Issue by Nebulean** [godotengine/godot#81023]
### Godot version

4.1.1.stable

### System information

macbook pro m1 pro base model (MacOS 13.5)

### Issue description

If a node has a Shape2D as export value, then, this shape will not show up in the 2D editor. I don't know if this is a bug or if it's on purpose, but it seems weird to me that there is no way of showing this shape in the 2D editor. Here is an image illustrating it. On the right, one have the Shape2D inserted in a Node2D export value, but this shape is not showing up in the 2D editor.

<img width="1624" alt="image" src="https://github.com/godotengine/godot/assets/9269185/f02e944d-fab8-45d2-875a-883a2f45ebc6">

### Steps to reproduce

Append a script on any node, put @export shape: Shape2D in that script and manually add a Shape2D resource to that variable.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/12446647/Archive.zip)

**Comment by KoBeWi** [comment]
It's not a bug, the editor plugin for editing shapes is specifically for CollisionShape2D.

**Comment by Nebulean** [comment]
Thank you very much for the answer! I was not aware of that technicality, I guess I am using it wrongly then. :)

**Comment by KoBeWi** [comment]
Shape2D has a `draw()` method if you want to just display it.

**Comment by servel333** [comment]
> It's not a bug, the editor plugin for editing shapes is specifically for CollisionShape2D.
- @KoBeWi 

I'm not sure I understand. Why?

Why not open that functionality up.

It will still work for the CollisionShape2d, but it will have the added value of working on anything else.

Seems like a win-win to me.
