### ISSUE TITLE
Transparent mesh occluding other transparent meshes behind it

### ISSUE THREAD

**Issue by jrockett6** [godotengine/godot#81029]
### Godot version

4.1.stable, Vulkan Forward Plus

### System information

Mac M1

### Issue description

Depending on camera angle, fully transparent sections of a mesh occlude other transparent meshes behind them.

https://github.com/godotengine/godot/assets/34614301/2b76d7fe-57d2-405e-ad91-edf1a95a35ea

https://github.com/godotengine/godot/assets/34614301/0486d5c5-a322-411b-abd5-1eac27474015

Using `depth_prepass_alpha` results in incorrect depth sorting in this case. In the video, the character has an alpha of 0.9 (`0.9 * albedo_tex.a`):

https://github.com/godotengine/godot/assets/34614301/c339362e-4b3a-4ee1-bf5a-b32d2c97ab97

### Steps to reproduce

Create 2 quadmeshes and shader materials with the following code:

```
shader_type spatial;
render_mode depth_draw_always, cull_back, diffuse_burley, specular_schlick_ggx;

uniform sampler2D texture_albedo : source_color;

void fragment() {
	vec4 albedo_tex = texture(texture_albedo, UV);
	
	ALBEDO = albedo_tex.rgb;
	ALPHA = 0.5 * albedo_tex.a;
}
```

### Minimal reproduction project

Can create if needed.

**Comment by Zireael07** [comment]
Looks like transparency sorting limitation that's common to other engines too

**Comment by Calinou** [comment]
This is a [transparency sorting issue](https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting) which can't be fully resolved. See the link for possible workarounds.

**Comment by clayjohn** [comment]
I agree with the other responses here. This is a limitation of 3D rendering. You are hitting an edge case by giving the renderer a tough combination of objects. 

Without having access to the assets in question it's tough to say how to fix this behaviour. But it should be possible to fix with the tools already available. 

Sorting offset and render priority likely won't be helpful in this case as you want the character to seamlessly appear in front of the tree. I suggest changing the depth pivot between origin and center to see if that helps. Also you should evaluate the AABB of the objects and see if it matches their real size. Improper AABBs can cause sorting issues.

**Comment by jrockett6** [comment]
Thank you all for the insight and suggestions. 

I am having trouble experimenting with some of the workarounds as I am a bit confused as to why this is a sorting issue - which is what most of the workarounds relate to.

As far as I can tell, sorting appears to be correct. In the first video, the character pops in front of the tree at the correct moment according to distance from the camera. However, when it does pop in front of the tree, the tree becomes occluded by portions of the transparent mesh that have an alpha value of 0.

It does certainly seem to be _related_ to sorting - because in the same way the alpha value of 0 portions of the tree mesh are _not_ occluding the character when the character is behind it - despite the shader materials being the same. But I don't understand how any workaround that changes the sorting order would resolve this - because one way or another 0 alpha portions are causing occlusion (dependent on camera angle, as illustrated in the second video).

As a side note: If there was a way to enable alpha scissoring _and_ send the remaining (potentially non-opaque) portions above the scissor threshold to the transparent pipeline I feel that would fix this issue. But I am not familiar with the render pipeline or how alpha scissoring is accomplished to know if this is possible.

**Comment by clayjohn** [comment]
> I am having trouble experimenting with some of the workarounds as I am a bit confused as to why this is a sorting issue - which is what most of the workarounds relate to.

Most of the issue comes from the fact that you have forced the shader to always write to depth by using `depth_draw_always`. That means that other objects will be occluded by your entire mesh even if your mesh is transparent. 

> As a side note: If there was a way to enable alpha scissoring and send the remaining (potentially non-opaque) portions above the scissor threshold to the transparent pipeline I feel that would fix this issue. But I am not familiar with the render pipeline or how alpha scissoring is accomplished to know if this is possible.

The option to do this is called `TRANSPARENCY_ALPHA_DEPTH_PRE_PASS`. Set your transparency mode to alpha depth prepass and change your depth draw mode back to opaque_only

**Comment by jrockett6** [comment]
Using that configuration (`depth_draw_opaque`, `depth_prepass_alpha`) and disabling the AABB sorting (`use_aabb_center`), and then setting the `MeshInstance3D` `center_offset` such that the origin of the mesh is at the feet of the sprite - the behavior is perfect. Thank you so much!
