### ISSUE TITLE
Lowering screen resolution  scales Godot to be bigger

### ISSUE THREAD

**Issue by SupaSibs** [godotengine/godot#81031]
### Godot version

4.1.1.stable

### System information

32 bitm Android 11, Godot 4.1.1, Galaxy Tab A 10.1 2019 (SM T510) with an unlocked bootloader, Exynos 7904 64 bit processor (2 Cortex M73 + 6 Cortex A73), Mali G-71

### Issue description

Using ADB/other apps to scale the display resolution scales Godot with it. For example; this is with me using
860x1344 VS 1920x1200
![Screenshot_20230827-085929_Godot Editor 4](https://github.com/godotengine/godot/assets/92636078/c580fd33-0477-4888-8b44-84aedcc6f98d)
![Screenshot_20230827-085033_Godot Editor 4](https://github.com/godotengine/godot/assets/92636078/3e4dc34c-d97c-417a-b832-52858eb192eb)

### Steps to reproduce

1. Download Godot for Android
2. Create ane empty project
3. Install the "Purr" resolution changing app
4. Use ADB to set up Purr
5. Lower the screen resolution using Purr
6. Open your empty project in Godot Android

### Minimal reproduction project

N/A (Purr resolution changes cannot be synced through a project)

**Comment by Calinou** [comment]
This is not a bug – it's rendering at the exact same UI scale in both. If you reduce rendering resolution, UI elements are expected to look larger in this case.

Adjust **Display Scale** in the Editor Settings to prevent this (you need to open a project first).
