### ISSUE TITLE
Trying to open a project crashes godot if gui/theme/default_theme_scale project setting is set to NAN.

### ISSUE THREAD

**Issue by Null-Ping** [godotengine/godot#81038]
### Godot version

v4.2.dev3.official.013e8e3af

### System information

Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

Setting `gui/theme/default_theme_scale` project setting to `NAN` (by typing `NAN` into the field in the Godot editor) makes a project crash and spam the console with the following errors when it is ran:
```python
USER ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:113)
USER ERROR: Failed generating icon, unsupported or invalid SVG data in default theme.
   at: generate_icon (scene/resources/default_theme/default_theme.cpp:92)
```
Additionally, closing the editor without changing the setting back makes the project virtually non-openable, by crashing the editor every time it tries to open the project.

### Steps to reproduce

0. Create a new project.
1. Set `gui/theme/default_theme_scale` project setting to `NAN` (by typing `NAN` in).
2. Try to run the project.
3. Close the editor.
4. Try to open the project again.

### Minimal reproduction project

Warning: non-openable because of the crash.
[default_theme_scale_nan_test.zip](https://github.com/godotengine/godot/files/12447832/default_theme_scale_nan_test.zip)

**Comment by akien-mga** [comment]
Fixed by #81076.

It can likely be reproduced from code by setting `nan` manually to that project setting, but I'm not sure we want to go that far into preventing users from shooting themselves in the foot :)
