### ISSUE TITLE
Error message "expected indented block" on misleading line

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#81046]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

When a function body is missing, you get the following error message:

![kuva](https://github.com/godotengine/godot/assets/49998025/496f3073-3218-4315-8326-8aed62b5b42f)

From the user's perspective the line displayed as an error line is totally wrong. I know that that is the line where the error is detected, but for the user it is a wrong line. At Godot subreddit it is quite often that users are stuck with these errors.

Another example where line 39 would be the most logical error location for the user. This is a little bit easier for the user as the error message tells that "for" block is missing something.

![kuva](https://github.com/godotengine/godot/assets/49998025/db317415-a135-4eee-adcc-f1f75f1067aa)

In my opinion the best fix would be to move the error location to the line that the error message refers to, in these examples function declaration line and for line. A small improvement would be to display the function name in the first example: `Error at (41, 1): Expected inteded block after function declaration 'foo()'`

### Steps to reproduce

```gdscript
func foo():

func bar():
	pass
```

```gdscript
func foo():
	for i in range(2):

func bar():
	pass
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is probably because empty lines are valid indentation, so the first like that actually violates the indentation is the line indicated, though confusing it isn't wrong as such 

It could be improved by backtracking over these empty lines though

**Comment by dalexeev** [comment]
We could mark as error the node after which an indent is expected, in this case `func` or `for`.
