### ISSUE TITLE
Setting interface/editor/custom_display_scale editor setting to NAN crashes the editor on restart and makes project manager totally unusable.

### ISSUE THREAD

**Issue by Null-Ping** [godotengine/godot#81041]
### Godot version

v4.2.dev3.official.013e8e3af

### System information

Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

# Warning: it is impossible to undo the following changes the same way that they are set!
Setting `interface/editor/display_scale` to "Custom" and `interface/editor/custom_display_scale` to `NAN` and then clicking "Save & Restart" button makes the editor crash with the following errors being printed:
[editor.log](https://github.com/godotengine/godot/files/12447970/editor.log)

Trying to open Godot project manager again results in the following errors:
[project-manager.log](https://github.com/godotengine/godot/files/12447975/project-manager.log)
As well as causes the project manager to display a blank window.

Here's a reproduction video:

https://github.com/godotengine/godot/assets/141347595/9dfe4085-1831-4a85-be51-04f228db530a

### Steps to reproduce

0. Open Godot editor.
1. Set `interface/editor/display_scale` to "Custom".
2. Set `interface/editor/custom_display_scale` to `NAN`.
3. Click "Save & Restart".
4. Try to reopen the editor.

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Fixed by https://github.com/godotengine/godot/pull/81076.
