### ISSUE TITLE
SpinBox accepts NAN as input.

### ISSUE THREAD

**Issue by AcatXIo** [godotengine/godot#81057]
### Godot version

4.2.dev3.official

### System information

Windows 10 - GLES3 (Compatibility)

### Issue description

When using the SpinBox node, it is possible for a user to input `NAN` into it (by clicking it and writing "NAN" as text).

I believe this should either be prevented (for example with an `allow_nan` property), or [documented](https://docs.godotengine.org/en/latest/classes/class_spinbox.html), as developers might not know that they should be checking the SpinBox's value against it.

![image](https://github.com/godotengine/godot/assets/141344817/ba1455e2-36b8-45f1-940d-32b9da92f1c4)

### Steps to reproduce

0. Create a new project.
1. Add a SpinBox node.
2. Run the project.
3. Click the SpinBox.
4. Type "NAN".
5. Press enter.

### Minimal reproduction project

[SpinBox NAN - MPR.zip](https://github.com/godotengine/godot/files/12448902/SpinBox.NAN.-.MPR.zip)

**Comment by akien-mga** [comment]
It should likely also not accept `inf` (so only accept `is_finite()` numbers).

**Comment by AcatXIo** [comment]
SpinBoxes also allow `PI` and `TAU`, which may or may not be desired in a game.

**Comment by AThousandShips** [comment]
They allow expressions so we should still allow constants like `PI`, so you can easily do trigonometry

**Comment by Jordyfel** [comment]
Instead of changing this here, wouldn't it be better for the inherited `Range` control's `value` property to only accept `is_finite` values instead, since it is supposed to be a number in a range.
