### ISSUE TITLE
godot window freezes up completely if switching workspaces while busy

### ISSUE THREAD

**Issue by ana-rchy** [godotengine/godot#81099]
### Godot version

v4.1.1.stable.mono.official [bd6af8e]

### System information

arch linux (6.4.11-arch2-1), bspwm (0.9.10-3)

### Issue description

if you switch workspaces (unsure if only applies to bspwm) while a floating window is open that is for example, exporting a project, and switch back to the godot workspace, it will 1. hide the godot window completely, and 2. be completely frozen up (cant give any input) if you unhide it such as with `bspc node any.hidden -g hidden=off` on bspwm

this also happened to me while downloading export templates

### Steps to reproduce

1. export a project
2. switch workspaces off of godot
2.5. (if on bspwm) `bspc node any.hidden -g hidden=off`
3. switch back

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating as part of https://github.com/godotengine/godot/issues/68471 and https://github.com/godotengine/godot/issues/74378, as the underlying cause is the same.
