### ISSUE TITLE
Allow multiplication and division between integer and float Vectors

### ISSUE THREAD

**Issue by ciqven** [godotengine/godot#81095]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Void Linux, amd64

### Issue description

I just tried to multiply a `Vector2i` by a `Vector2`. I expected this to do the Vector equivalent of multiplying an `int` by a `float` - that is, return a `Vector2` with the result of the (float) multiplication. instead, I got an editor error.

A quick search here lead me to https://github.com/godotengine/godot/pull/57607
In this PR, reduz comments:
> I also noticed you can't do vector operators between vec2i and vec2 (and vec3i and vec3), I never added those operators and it seems nobody asked for them, but it should not be super difficult to add if somebody asks for it.

With this issue, I'd like to ask for these operators to be added. It is true it can be worked around by doing `Vector2(vec2i) * vec2` or something among those lines, but this looks ugly (in my opinion) and is not required when multiplying `int` by `float`.

Of course, the same goes for the 3 and 4 dimensional Vector types, and for other operators (division).

### Steps to reproduce

1. `Vector2i(100,100) * Vector2(2.0, 2.0)`
2. `> Invalid operands to operator *, Vector2i and Vector2.`

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This should be a [proposal](https://github.com/godotengine/godot-proposals), not a bug report, I am sorry I did not make that more clear when you asked

**Comment by ciqven** [comment]
Ah, once again apologies. Should this be migrated by someone with the permissions, or should I close this one and open a new issue in the Proposals repo?

**Comment by AThousandShips** [comment]
Should open a new one, as there are specific fields to fill in

**Comment by ciqven** [comment]
Thank you for the guidance, I'll be closing this one with this comment and opening a new one in proposals.
