### ISSUE TITLE
Inconsistent `Signal.is_connected` behaviour for callables that combine `bind` and `unbind`

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#81118]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Debian GNU/Linux trixie/sid trixie - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

:+1: For `Callable`s which have had `bind` *xor* `unbind` called on them, `Signal.is_connected` will return `true` so long as the base callable is the same.
:warning: For `Callable`s which have had `bind` *and* `unbind` called on them, `Signal.is_connected` seems to only return `true` for the exact `Callable` object.

I would expect `is_connected` to return `true` in the same manner for either case.

### Steps to reproduce

```gdscript
extends Node2D

signal boop(doot)
signal beep(doot)
signal baap(doot)

func _ready():
    boop.connect(translate.bind(Vector2.ZERO))
    print(boop.is_connected(translate)) # true
    print(boop.is_connected(translate.bind(Vector2.ZERO))) # true
    boop.disconnect(translate.bind(Vector2.ZERO))

    beep.connect(translate.unbind(1))
    print(beep.is_connected(translate)) # true
    print(beep.is_connected(translate.bind(Vector2.ZERO))) # true
    print(beep.is_connected(translate.unbind(1))) # true
    beep.disconnect(translate.unbind(1))

    var handler = translate.bind(Vector2.ZERO).unbind(1)
    baap.connect(handler)
    print(baap.is_connected(translate)) # false
    print(baap.is_connected(translate.bind(Vector2.ZERO))) # false
    print(baap.is_connected(translate.unbind(1))) # false
    print(baap.is_connected(translate.bind(Vector2.ZERO).unbind(1))) # false
    print(baap.is_connected(handler)) # true
    # Attempting this `disconnect` triggers "Attempt to disconnect a nonexistent connection..."
    baap.disconnect(translate.bind(Vector2.ZERO).unbind(1))
```

### Minimal reproduction project

Self-contained _scene_: [test.zip](https://github.com/godotengine/godot/files/12463837/test.zip)

**Comment by AThousandShips** [comment]
This is indeed incorrect behavior, the `is_connected` check should not care at all about binds/unbinds, unsure what happens here

**Comment by AThousandShips** [comment]
@dalexeev

**Comment by kleonc** [comment]
Making these:
https://github.com/godotengine/godot/blob/922689c801047c63902b190f402cd6207c83e7da/core/variant/callable_bind.cpp#L90-L92
https://github.com/godotengine/godot/blob/922689c801047c63902b190f402cd6207c83e7da/core/variant/callable_bind.cpp#L224-L226
return `callable.get_base_comparator()` instead should make it work as suggested I think. It should result in returning the original method-Callable for nested binds/unbinds:

https://github.com/godotengine/godot/blob/922689c801047c63902b190f402cd6207c83e7da/core/variant/callable.cpp#L194-L204

**Comment by dalexeev** [comment]
What matters is not what both `bind()` and `unbind()` are used, but the chain length. Two `bind()` will give the same:

```gdscript
print(s.is_connected(f)) # true
print(s.is_connected(f.bind(11))) # true
print(s.is_connected(f.unbind(1))) # true
print(s.is_connected(f.unbind(1).bind(1))) # false
print(s.is_connected(f.bind(11).bind(22))) # false
print(s.is_connected(f.unbind(1).unbind(1))) # false
```
