### ISSUE TITLE
`NoiseTexture2D.noise.get_noise_2d` returns negative values with `NoiseTexture2D.normalize` set to true

### ISSUE THREAD

**Issue by Mohamed-Kr** [godotengine/godot#81115]
### Godot version

4.1 stable, 4.2.dev3

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

With `NoiseTexture2D.normalize` set to true, the `NoiseTexture2D.noise.get_noise_2d` function (I did not try with others) returns negative values for all values of `NoiseTexture2D.noise.noise_type` except `FastNoiseLite.NoiseType.TYPE_CELLULAR`.

### Steps to reproduce

runnig this prints [4, 3, 0, 1, 5] which corresponds to all types except `FastNoiseLite.NoiseType.TYPE_CELLULAR = 2`
```
func _ready() -> void:
	var types := [FastNoiseLite.NoiseType.TYPE_VALUE_CUBIC, FastNoiseLite.NoiseType.TYPE_PERLIN, FastNoiseLite.NoiseType.TYPE_CELLULAR, FastNoiseLite.NoiseType.TYPE_SIMPLEX, FastNoiseLite.NoiseType.TYPE_SIMPLEX_SMOOTH, FastNoiseLite.NoiseType.TYPE_VALUE]
	var non_working_types := []
	
	for seed in [0, 10, 20, 30, 42, 50] :
		for type in types :
			
			var hm := NoiseTexture2D.new()
			hm.noise = FastNoiseLite.new()
			hm.noise.noise_type = type
			hm.noise.seed = seed
			hm.normalize = true
			await hm.changed
			
			if not type in non_working_types :
				for x in hm.get_width() :
					for y in hm.get_height() :
						if hm.noise.get_noise_2d(x, y)>0 :
							non_working_types.push_back(type)
							break
					if type in non_working_types :
						break
	
	print(non_working_types)
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The settings on `NoiseTexture2D` do not affect `Nose`, so that setting isn't relevant for this, where is the range for `get_noise_2d` guaranteed to be non-negative?

**Comment by AThousandShips** [comment]
Also your check breaks when the value *is* positive

**Comment by Mohamed-Kr** [comment]
Sorry, I wrongfully assumed that `NoiseTexture2D.get_image()` was an utility function that uses `Noise.get_noise_2d()` to generate the image.
And the fact that the ranges on the `Noise.get_noise_*` functions isn't explicit in the docs made me think that `NoiseTexture2D` was responsible for the range which also isn't a good assumption now that I consider the fact that `Noise` is intended to enable the use of third party library like in the case of `FastNoiseLite`.

Also I'm sorry for the confusion between `<` and  `>`.

Thanks a lot for your indications.
I'm letting this issue open as I don't know if I should close it myself, or if it can turn into documentation changes considerations.

**Comment by AThousandShips** [comment]
I don't think there's anything actionable here, the documentation isn't lacking, as the specific range returns of `get_noise_2d` is unspecified, you can make some new noise class that does its own thing, so I think there's nothing to do here

**Comment by Mohamed-Kr** [comment]
Yes, this makes sense - I don't see what can actually be changed too.
Thank you

**Comment by AThousandShips** [comment]
Thank you for reporting and if you come up with any ways the documentation can be made clearer don't hesitate to suggest them, closing this issue for the moment but if you think of any ways it is lacking please comment again here and we can reopen it and investigate!
