### ISSUE TITLE
Vector3.angle_to produces NaNs

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8111]
Tested on Godot 3.0 (not latest, a few days old)
Windows 10 64 bits

In some cases, Vector3.angle_to produces NaN angles, even if the vectors are normalized.
By narrowing down the issue:

```cpp
real_t Vector3::angle_to(const Vector3 &p_b) const {

	return Math::acos(this->dot(p_b) / Math::sqrt(this->length_squared() * p_b.length_squared()));
}
```

I found it's because the value sent to `Math::acos` is sliiiigtly greater than 1, to the point that when printed in GDScript, the console just says `1`, but x > 1.0 outputs `true`.
I added a workaround function in my project that performs a `clamp`, and it worked perfectly.

Sorry I don't have a small repro project, as this happened to me by doing some specific 3D camera movements in this test project: https://github.com/Zylann/godot_flyer_test
See this line of script where my problem occurred: https://github.com/Zylann/godot_flyer_test/blob/master/flyer.gd#L48
It happened by starting the game, doing small mouse movements, and then I got a few occurrences of NaN.

**Comment by tagcup** [comment]
Could you tell me the contents of the input Vector3 which triggers this precision issue? (I'm wondering if the entries are too large or not).

**Comment by tagcup** [comment]
Also, does `projected_y.normalized().angle_to(current_basis.y.normalized())` work as a work-around?

**Comment by Zylann** [comment]
I instrumented the code this way:

```gdscript
var angle = projected_y.angle_to(current_basis.y) # BROKEN
if angle != angle:
	print("NAN!")
	print(projected_y, projected_y.length() > 1.0)
	print(current_basis.y, current_basis.y.length() > 1.0)
```
I got the following occurences (and more):
```
NAN!
(-0.00002, 1, 0.001007)False
(-0.000015, 0.999999, 0.001007)False
NAN!
(-0.000152, 0.999938, 0.011141)False
(-0.000267, 0.999938, 0.01114)False
NAN!
(-0.004558, 0.990229, 0.139376)False
(-0.004551, 0.990229, 0.139376)False
```
Normalizing `basis.y` doesn't help, I still get some occurrences:
```
NAN!
(0.000099, 0.999937, 0.011217)False
(-0.000024, 0.999937, 0.011218)False
```

**Comment by tagcup** [comment]
Thanks for the test cases!
Maybe a IEEE754 wizard can come up with something better (anyone?), although for now, we can work around it by clamping the cosine between -1 and 1:

```cpp
real_t Vector3::angle_to(const Vector3 &p_b) const {
	ERR_FAIL_COND(length()==0);
	ERR_FAIL_COND(b.length()==0);
	real_t cos_ab = dot(p_b) / Math::sqrt(length_squared() * p_b.length_squared());
	return Math::acos(CLAMP(cos_ab, -1.0, 1.0));
}
```

**Comment by tagcup** [comment]
Alternatively, we can do, which might actually be a little faster

```cpp
real_t Vector3::angle_to(const Vector3 &p_b) const {
	return Math::atan2(cross(p_b).length(), dot(p_b));
}
```
