### ISSUE TITLE
Crash on exit, probably caused by audio

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8112]
Tested on Godot master c37fad650f92845a6f59740fea2fea1b46f56db1
Windows 10 64 bits

Everytime I close the editor or sometimes a game, Godot crashes.
In QtCreator I get this exception:

vector.h, line 113, read access violation
![image](https://cloud.githubusercontent.com/assets/1311555/24226131/f3630d62-0f64-11e7-850a-3e84b7bf95f7.png)

The crash is not visible when Godot is run without debugging.

This is the full console log, no particular error when the crash occurred:
```
EXEC PATHP??: D:\PROJETS\INFO\GODOT\ENGINE\godot_fork\bin\godot.windows.tools.64.exe
DETECTED MONITORS: 1
Activated GL 3.3 contextgetting extensions
total 330
max ubo light: 409
max ubo reflections: 455  ubo size: 144
EXEC PATHP??: D:\PROJETS\INFO\GODOT\ENGINE\godot_fork\bin\godot.windows.tools.64.exe
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: editor\editor_data.cpp:599
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: In Object of type 'CheckBox': Attempt to connect nonexistent signal 'button_selected' to method 'CanvasItemEditorViewport._on_select_type'
   At: core\object.cpp:1416
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:923
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
WARNING: not found: editor_plugins/enabled
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:272
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
ERROR: ConfigFile::get_value: Condition ' !values.has(p_section) ' is true. returned: p_default
   At: core\io\config_file.cpp:85
loading scene DEFERED
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
path not recognized
width: 64
height: 64
flags: 4
df: 51380224
request detect 3D at res://.import/terrain.png-84a626877af7de08ecf24965bda52835.stex
request detect srgb at res://.import/terrain.png-84a626877af7de08ecf24965bda52835.stex
mipmaps: 1
mipmap read total: 1
elements: 72
ERROR: PopupMenu::set_item_checked: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:639
ERROR: PopupMenu::get_item_text: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:691
ERROR: PopupMenu::set_item_checked: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:639
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
ERROR: FileAccessWindows::close: Condition ' rename_error ' is true.
   At: drivers\windows\file_access_windows.cpp:138
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
1490223593 vs 1490223593
1490223593 vs 1490223593
erasing atlas
erasing atlas
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
erasing atlas
```

**Comment by karroffel** [comment]
I debug the editor and games frequently as well, never had this crash. But I don't use any audio for my tests, so it really seems to be caused by using the audio system.

**Comment by Zylann** [comment]
I don't use audio as well, but it happens anyway. Maybe it's Windows-specific?

**Comment by Zylann** [comment]
Edit: another callstack, got it when debugging a scene directly, from QtCreator.
![image](https://cloud.githubusercontent.com/assets/1311555/24584051/e6e7e294-175f-11e7-8c9f-7cfb6cbff30e.png)

**Comment by neikeq** [comment]
Can anyone still reproduce this after 231fa92?

**Comment by Ahmed0425** [comment]
still getting these errors :(

> DETECTED MONITORS: 1
Activated GL 3.3 contextGLES3: max extensions: 265
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
OPENING: D:/Apps/Labled Apps/Development/Godot/Projects/3.0 (D:::Apps::Labled Apps::Development::Godot::Projects::3.0)
running cmdline: "C:\Users\Ahmed94\Downloads\Compressed\godot-master\bin\godot.windows.tools.64.exe" "-path" "D:/Apps/Labled Apps/Development/Godot/Projects/3.0" "-editor"
DETECTED MONITORS: 1
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
Activated GL 3.3 contextGLES3: max extensions: 265
ERROR: There are still MemoryPool allocs in use at exit!
   At: core\dvector.cpp:69
GLES3: max ubo light: 409
GLES3: max ubo reflections: 455, ubo size: 144
ERROR: Invalid new child position: 2
   At: scene\main\node.cpp:318
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: editor\editor_data.cpp:600
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: RasterizerSceneGLES3::environment_set_tonemap: Condition ' !env ' is true.
   At: drivers\gles3\rasterizer_scene_gles3.cpp:923
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: Invalid new child position: 2
   At: scene\main\node.cpp:318
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
save presets
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
ERROR: ClassDB::get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core\class_db.cpp:274
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool
EditorSettings::_get - Warning, not found: import/pvrtc_texture_tool

**Comment by Hinsbart** [comment]
@Ahmed0425 Sorry, but this is not about those errors but about a crash that you only notice when debugging (or maybe checking the return value of godot.exe :p).

**Comment by Zylann** [comment]
The editor shut cleanly, with only these errors at the end:
```
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:1910
ERROR: There are still MemoryPool allocs in use at exit!
   At: core\dvector.cpp:69
```

**Comment by Ahmed0425** [comment]
My issue was described in detail here #8489
I've also described the issues I encounter in the last 2 comments (I encounter your second error in the startup of the editor btw)

**Comment by neikeq** [comment]
@Zylann that's most likely a separate issue. Can this one be closed then?
