### ISSUE TITLE
`Index p_gutter = -1 is out of bounds` error when saving file in external editor

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#81135]
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Godot v4.2.dev3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

You get these errors when saving file in external editor:

![kuva](https://github.com/godotengine/godot/assets/49998025/a0f9ff6b-31f3-4436-bfad-2ca6ea99a2dd)

```gdscript
Godot Engine v4.2.dev3.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
[LSP] Connection Taken
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
  scene/gui/text_edit.cpp:5900 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
```

### Steps to reproduce

`Text Editor | Appearance | Highlight Type Safe Lines` setting must be on.

My external editor is vscode version 1.18.1 with godot-tools version 1.3.1.

1. Open attached minimal reproduction project (Project is created from a large project by chopping off stuff that didn't seem to affect the error.)
2. Open `stages.gd` in vscode
3. Press Ctrl-S to save `stages.gd` in vscode
4. Change focus back to Godot 

Sometimes the errors are displayed immediately after step 3, sometimes step 4 is needed.

### Minimal reproduction project

I left some files in the `.godot` folder as I suspect that the editor layout might have something to do with the bug.

[g42_p_gutter.zip](https://github.com/godotengine/godot/files/12467771/g42_p_gutter.zip)

**Comment by jsjtxietian** [comment]
I can reproduce it with Godot v4.2.dev (c5719fa31) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

**Comment by ryanabx** [comment]
I can reproduce it on my personal project with Godot v4.2.dev (fcbd899b2) - Windows 10.0.22621 - GLES3 (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

**Comment by LeotomasMC** [comment]
can also reproduce on linux. using Godot v4.1.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 - Vulkan (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

**Comment by theraot** [comment]
Closing open scripts in the Godot editor seems to work around the error (i.e. no error spam when editing scripts in an external editor).

**Comment by Silabear** [comment]
Still a bug. Is this being worked on? It's quite annoying. :P

**Comment by miv391** [comment]
Still happens with v4.2.dev6.official [57a6813bb]
```
scene/gui/text_edit.cpp:5889 - Index p_gutter = -1 is out of bounds (gutters.size() = 4).
```

I found out that if the "Highlight Type Safe Lines" editor setting is turned off, this bug doesn't happen. 

![kuva](https://github.com/godotengine/godot/assets/49998025/2ac90962-b1aa-4a42-91c1-6b0e9c39ad77)

This is the line mentioned in the error message (in master): https://github.com/godotengine/godot/blob/51f81e1c88499f04d2ebdcc0be0b34e73f5e90eb/scene/gui/text_edit.cpp#L5884

The only suspicious calls to the function (`set_line_gutter_item_color`) where the error message is printed, are made from here: https://github.com/godotengine/godot/blob/51f81e1c88499f04d2ebdcc0be0b34e73f5e90eb/editor/plugins/script_text_editor.cpp#L684-L694

The default value of `line_number_gutter` is -1 and it seems it is never changed and we get the error.

This is the only place where `line_number_gutter` is changed: https://github.com/godotengine/godot/blob/51f81e1c88499f04d2ebdcc0be0b34e73f5e90eb/editor/plugins/script_text_editor.cpp#L1213-L1225

Either `_update_gutter_indexes()` is not called at all or it is called too late or for some reason it doesn't change `line_number_gutter `.

**Comment by MorningBeverage** [comment]
I'm getting a similar issue, but instead of "gutter" it's "line"
`scene/gui/text_edit.cpp:5300 - Index p_line = -1 is out of bounds (text.size() = 2).`
un-checking "Highlight Type Safe" Lines doesn't prevent it from happening.

**Comment by Jagholin** [comment]
Can confirm the issue on 4.2.1. The editor also crashes often with a similar message, might be related
![grafik](https://github.com/godotengine/godot/assets/4126782/fbf4acac-cc91-4637-8570-992c5aeea34b)

**Comment by dannyking** [comment]
Confirming the issue on 4.2.1 stable too. Happens when I save in an external editor (VSCode)

**Comment by haowg** [comment]
When you have configured Visual Studio Code as an external editor in Godot 4, but it's not activated, this error will occur.

**Comment by miv391** [comment]
I cannot reproduce this bug anymore with v4.3.dev2.official.

**Comment by akien-mga** [comment]
Would be good to identify what fixed the bug in 4.3 so we could cherry-pick the fix to 4.2.
Alternatively we can go with #84907 as a workaround for 4.2.x.

I didn't manage to reproduce the bug in 4.2.1.stable myself to try to assess which dev snapshot first fixed the issue, but I'm not usually using VS Code as external editor so I might not have the appropriate configuration to trigger the bug.

**Comment by theraot** [comment]
Idk, what you are about... I have this issue in v4.3.dev2.official [352434668]:

![image](https://github.com/godotengine/godot/assets/1212509/9304d9b0-d98a-44de-b57b-e601fd305fe0)

And in v4.3.dev3.official [36e943b6b]

![image](https://github.com/godotengine/godot/assets/1212509/276409f5-add5-4d40-b1c2-7f0fe2c0c1d0)

Could we be looking at two bugs with the same sympton?

This is how I reproduce: Have multiple scripts open in the Godot editor, open the project in Visual Studio (I have the extensions installed, I don't think that makes a difference), and I edit one script, one space added will do.

**Comment by miv391** [comment]
I tested this again and yes, I can reproduce this after all. Now I used 4.3 dev3. I failed to reproduce the bug yesterday because I had set the `Text Editor | Appearance | Highlight Type Safe Lines` setting off. (Because then you do NOT get the "Index p_gutter" errors.)

**Comment by AlighaThor** [comment]
@miv391 Thanks! That workaround works good. This was driving me crazy... 😁
