### ISSUE TITLE
Generating the C# project fails when .Net 8 Sdk is installed.

### ISSUE THREAD

**Issue by Summpot** [godotengine/godot#81133]
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - Windows 10.0.23531

### Issue description

When I install .Net 8 on my system (I'm using the preview version of Visual Studio, so I can't uninstall .Net 8), I get the message "Failed to create C# project." when I create a C# script file, and it doesn't generate the corresponding project files.
```
modules/mono/glue/runtime_interop.cpp:1324 - System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. System cannot find the specified file.
  File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at GodotTools.ProjectEditor.ProjectGenerator.GenAndSaveGameProject(String dir, String name)
     at GodotTools.CsProjOperations.GenerateGameProject(String dir, String name) in /root/godot/modules/mono/editor/GodotTools/GodotTools/CsProjOperations.cs:line 13
  Transient parent has another exclusive child.
```

### Steps to reproduce

1. Install the latest preview version of .Net 8 Sdk.
2. Create a new godot project.
3. Add a scene root node.
4. Attach a C# script to the node.

### Minimal reproduction project

N/A

**Comment by Summpot** [comment]
I apologize that this bug should be a misreporting, it has nothing to do with .Net 8 and may not even be related to Godot at all, I couldn't reproduce the issue in a virtual machine, but I noticed that the package System.Runtime was last updated in 2019 and it doesn't have a version 8.0.0.0 at all, so I searched for a similar issue, which is more than likely a Nuget global cache bug, after I cleared the nuget cache, the C# project file could be created successfully.
I will close this issue.
By the way, do you guys have a tendency to design Godot to be framework-agnostic? I noticed that I couldn't compile the project after changing the TargetFramework in csproj to net7.0 or net8.0, but logically this shouldn't be the case, hostfxr doesn't seem to care about the runtime version.

**Comment by akien-mga** [comment]
Godot currently supports net6.0 and net7.0, I don't think net8.0 has been tested yet.

**Comment by RoyAwesome** [comment]
Hi, I also have this issue.  I updated my visual studio version which automatically installed .net 8, and I can no longer create C# solutions for godot.  

Uninstalling .net 8 and restarting the editor worked as a workaround, but this was an unexpected error.

**Comment by MarioLiebisch** [comment]
Yep, this definitely should be reopened. Running into the very same issue with Visual Studio 2022 17.8 (still in preview, though).

**Comment by Summpot** [comment]
> Hi, I also have this issue. I updated my visual studio version which automatically installed .net 8, and I can no longer create C# solutions for godot.
> 
> Uninstalling .net 8 and restarting the editor worked as a workaround, but this was an unexpected error.

Can you try deleting all the files under `%USERPROFILE%\.nuget\packages`? I no longer have this problem after deleting the nuget cache, if this can be reproduced on other people's computers then this is most likely a .Net issue.

**Comment by MarioLiebisch** [comment]
I only tried deleting the cache before (using the VS Settings), but no, manually deleting the packages folder doesn't help either.

**Comment by raulsntos** [comment]
Do you have other SDKs installed? Can you show the output of running the `dotnet --info` command in a terminal?

Also, when running Godot, try to execute it from a terminal using the `--verbose` option and see which path it's trying to use for hostfxr, it should print a message like this: `Found hostfxr: /usr/share/dotnet/host/fxr/7.0.11/libhostfxr.so`.

**Comment by devingoble** [comment]
I had this issue as well on a fresh workstation where I only had .NET 8 bits installed. Installing the latest .NET 7 SDK resolved it.

**Comment by Summpot** [comment]
> Do you have other SDKs installed? Can you show the output of running the `dotnet --info` command in a terminal?
> 
> Also, when running Godot, try to execute it from a terminal using the `--verbose` option and see which path it's trying to use for hostfxr, it should print a message like this: `Found hostfxr: /usr/share/dotnet/host/fxr/7.0.11/libhostfxr.so`.

Found hostfxr: C:\Program Files\dotnet\host/fxr/8.0.0-rc.1.23419.4/hostfxr.dll
Found .NET Sdk version '7.0.401': C:\Program Files\dotnet\sdk\7.0.401

I didn't have the same problem after I deleted the nuget cache, but Godot found hostfxr for .Net 8 and Sdk for .Net 7, and since the reproduction process as well as the interim solutions to the problems that people have fed back above are quite different, perhaps we could consider having Godot use the same versions of hostfxr and Sdk.

**Comment by MarioLiebisch** [comment]
So yep, seems to be related to the Visual Studio update replacing the .NET SDK 7 with version 8:
```
.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
```
Manually reinstalling 7.0x in addition fixed the issue:
```
.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]
```

**Comment by Summpot** [comment]
Yes, you are right, I reproduced it on my computer by following the steps you mentioned.
But can we investigate further why the problem occurs, the code that creates the project seems to be independent of the Sdk version, can it be run directly with .Net 8?

**Comment by raulsntos** [comment]
> perhaps we could consider having Godot use the same versions of hostfxr and Sdk

That's what it tries to do first, it looks for the same major version and only falls back to something else if it can't find it. I think this is happening because the version `8.0.100-rc.1.23455.8` can't be parsed by [`Version.TryParse`](https://learn.microsoft.com/en-us/dotnet/api/system.version.tryparse).

https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/modules/mono/editor/GodotTools/GodotTools/Build/DotNetFinder.cs#L100-L101

> the code that creates the project seems to be independent of the Sdk version

The C# project is created using the `Microsoft.Build` APIs. I believe this requires registering the SDK.

**Comment by MineCommanderCN** [comment]
I have the same issue in Godot 4.2 Beta 1 with .NET SDK 8.0.100-rc.2.23502.2, even after cleaning NuGet cache. It only occurs in Godot projects and standalone .NET projects work well.

**Comment by akien-mga** [comment]
We merged a likely fix for this issue, but it still needs testing. Please give it a try in 4.2 beta 3 which should be released today or tomorrow.

**Comment by tbhb** [comment]
> We merged a likely fix for this issue, but it still needs testing. Please give it a try in 4.2 beta 3 which should be released today or tomorrow.

I'm afraid that fix didn't end up working for me (on a local build with #83325 included). Still experiencing the same issue:

```
.NET: Initializing module...
Found hostfxr: /usr/local/share/dotnet/host/fxr/8.0.0-rc.2.23479.6/libhostfxr.dylib
.NET: hostfxr initialized
.NET: GodotPlugins initialized
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

SDKs installed:

```
$ dotnet --list-sdks                                    
6.0.413 [/usr/local/share/dotnet/sdk]
6.0.414 [/usr/local/share/dotnet/sdk]
7.0.400 [/usr/local/share/dotnet/sdk]
7.0.401 [/usr/local/share/dotnet/sdk]
8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]
```

I'll give it a try with 4.2 beta 3 as well once it's fully released.

**Comment by MarioLiebisch** [comment]
@tbhb This might be a different issue on your end triggering the same error. Previously installing a 7.x version fixed this (at least on Windows). But it could also be a platform difference.

**Comment by raulsntos** [comment]
@tbhb It doesn't seem like your output contains the `Found .NET Sdk version` message, which makes me think it's a different issue. The original issue was about generating a C# project, is that also the case for you? I would recommend opening a new issue so we can follow-up on your specific issue.

---

If anyone here still has issues with .NET 8.0 in [Godot 4.2 beta 3](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/), please open a new issue and make sure to include:
- The output of `dotnet --info`.
  I ask specifically about `--info` because it includes the installed **SDKs**, the installed **runtimes**, and **environment variables** that may affect the process of locating .NET.
- A minimal reproduction project.
  This is mostly so I can take a look at the **csproj**, in case you modified it (e.g.: Did you change the `<TargetFramework>`?), but also because it greatly helps troubleshooting.

**Comment by tbhb** [comment]
> @tbhb It doesn't seem like your output contains the `Found .NET Sdk version` message, which makes me think it's a different issue. The original issue was about generating a C# project, is that also the case for you? I would recommend opening a new issue so we can follow-up on your specific issue.

Ah my apologies here, my case was actually a bit different. I was trying to set my `TargetFramework` to `net8.0` to try out some things in 8.0.0.rc2 :) Your comment in https://github.com/godotengine/godot/issues/83915#issuecomment-1779661812 actually fixed things for me though, setting `DOTNET_ROLL_FORWARD_TO_PRERELEASE` and now I'm able to run my .NET 8-compiled assembly!

**Comment by jasonswearingen** [comment]
FYI Godot 4.2Beta3 does work with DotNet8 installed, but DotNet8 is not a supported runtime for godot projects.  see https://github.com/godotengine/godot/pull/83325#issuecomment-1781420008

**Comment by FyiurAmron** [comment]
@jasonswearingen .net8.0 is fully supported, just not it's prerelease (as you already know) :D

**Comment by bamyazi** [comment]
I am seeing this error with Godot 4.2 stable, building  the project from the Godot IDE fails with error

The build method threw an exception.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (0,0)

However the project will build and run fine if i build it within Jetbrains Rider which i have set as my code editor.

**Comment by HarryDC** [comment]
Saw the same error, v4.2.2 rc1, was fixed after a cache clear with `dotnet nuget locals -c`
