### ISSUE TITLE
Vulkan Mobile: Decal Rendering Issues, Doubling Up?

### ISSUE THREAD

**Issue by SeanH-CB** [godotengine/godot#81143]
### Godot version

4.1.1.stable

### System information

Windows 11 - Vulkan (Mobile) - NVidia GTX 1070 537.13

### Issue description

When placing more decals equal to or around the max of 8 decals for a surface, issues begin to occur.
Setting a decal to be slightly transparent, depending on the viewing angle decals are rendered twice which means they are no longer blended with the surface correctly.

Also when moving the camera around, sometimes a decal will also move around along the surface.
This issues occurs on both StandardMaterial3D & ShaderMaterial.

Screenshot:
![image](https://github.com/godotengine/godot/assets/112617916/6222c1f6-da3d-43db-a89c-d9b303c4ad7f)

https://github.com/godotengine/godot/assets/112617916/ead9fae0-762f-4002-9b0e-e1f181a8d78b

### Steps to reproduce

- Make a New 3D Project
- Set rendering Mode to Mobile
- Add a MeshInstance3D
- Place around 8 decals on the surface
- Move the camera around until you see issues described/shown in video

### Minimal reproduction project

[Mobile Decal Issues.zip](https://github.com/godotengine/godot/files/12469892/Mobile.Decal.Issues.zip)

**Comment by Calinou** [comment]
cc @BastiaanOlij 

https://github.com/godotengine/godot/pull/80911 may have surfaced a bug that previously wasn't noticeable.

> Place around 8 decals on the surface

Does this occur with only 7 decals?

**Comment by jcarlosrc** [comment]
I have noticed that decals move with the camera without achieving the 8 amount limit.

**Comment by HatAndTie** [comment]
It also seems to happen when the decal isn't in the cull-mask of the camera, while the mesh it is projected on is.

**Comment by coobenguy** [comment]
Still having this issue in the latest 4.2 beta

**Comment by Calinou** [comment]
@coobenguy Please open a new issue with a minimal reproduction project attached.
