### ISSUE TITLE
Interaction with gitignore check and case-insensitive check

### ISSUE THREAD

**Issue by fire** [godotengine/godot#81151]
### Godot version

4.2 custom branch https://github.com/V-Sekai/godot/commit/b563083686255f881fa7362815117af940f8506b

### System information

Mac Mini, Apple Silicon, Firefox

### Issue description

https://github.com/godotengine/godot/pull/78908 enabled case insensitive git checks

```
# .gitignore
st[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]
# ./misc/scripts/gitignore_check.sh
output=$(git -c core.ignorecase=false check-ignore --verbose --no-index **/* | \
    awk -F ':' '{ if ($3 !~ /^!/) print $0 }')
```

Will fail cicd when a path like `thirdparty/eigen/Eigen/StdDeque` is given to it. 

Note that this isn't a path in Godot Engine git, but I was triggering it elsewhere.

The assumption is that "st" for a total of six characters after cannot be in git. "st" in this is matched by "St" which fails the build.

### Steps to reproduce

The cicd would fail if I didn't reverse the case in-sensitive check.

Explanation of the regex pattern by gpt4.

```
The regular expression `st[A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9][A-Za-z0-9]` is already case sensitive. It matches any string that starts with 'st' followed by exactly six alphanumeric characters, where the alphabetic characters can be either uppercase or lowercase.

Here's a breakdown of the pattern:

- `st`: Matches the exact sequence of characters "st".
- `[A-Za-z0-9]`: Matches any single character in the range A-Z (uppercase), a-z (lowercase), or 0-9.
- The following five `[A-Za-z0-9]` expressions: Each one matches another single character in the same range, for a total of six characters after the "st".

If you want to match only lowercase or only uppercase letters, you can modify the pattern like so:

- Only lowercase: `st[a-z0-9][a-z0-9][a-z0-9][a-z0-9][a-z0-9][a-z0-9]`
- Only uppercase: `st[A-Z0-9][A-Z0-9][A-Z0-9][A-Z0-9][A-Z0-9][A-Z0-9]`

These will match strings that start with 'st' followed by exactly six characters that are either all lowercase letters and digits, or all uppercase letters and digits, respectively.
```

### Minimal reproduction project

I posted the git commit as a reproduction project with a patch to set ignorecase=false.

**Comment by fire** [comment]
@zorbathut poke

**Comment by zorbathut** [comment]
The issue is that Windows users have case-insensitivity essentially enforced by the environment. Turning the ignorecase option off doesn't fix anything for Windows users, it just makes bugs on Windows impossible to detect from within Linux.

The right solution here is to fix the .gitignore files so they don't cover files in the repo; if that gitignore line is overzealous then it should be reduced to cover only the things that are relevant.

**Comment by akien-mga** [comment]
Yeah I looked into how temporary file names are generated by binutils ld and glibc, I don't think we have much control over that and it seems to be a pretty random alphanumeric `XXXXXX` pattern after the `st` prefix.

So this can't be solved by tweaking the regex.

If we need to add exceptions to the `.gitignore` for paths like `StdDeque`, we can do it.
