### ISSUE TITLE
Theme.get_theme_item_list returns empty list, but Theme.get_theme_item shows that entries exist

### ISSUE THREAD

**Issue by AntonWedemeier** [godotengine/godot#81154]
### Godot version

v4.1.1.rc1.official [e709ad4d6]

### System information

Godot v4.1.1.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 660 Ti () - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

I am trying to get Theme information for each Control type.
Theme.get_theme_item_list() should give the entries inside the Theme information for a specific combination of data-type and control-type. But I get an empty array for serveral combinations I tried.
There exist entries, which I confirmed myself with a call to Theme.get_theme_item().
Is this a bug or am i doing something wrong?

### Steps to reproduce

I made new project. I added a scene consisting of a Node2d with a Control as child. I added a script to the Control node:
```
extends Control

# Called when the node enters the scene tree for the first time.
func _ready():
	var _theme_default = ThemeDB.get_default_theme()
	prints("1", _theme_default.get_theme_item_list(Theme.DATA_TYPE_COLOR, "BUTTON"))
	prints("2", _theme_default.get_theme_item(Theme.DATA_TYPE_COLOR, "normal", "BUTTON"))
```
Running gives the output:
```
Godot Engine v4.1.1.rc1.official.e709ad4d6 - https://godotengine.org
Vulkan API 1.2.142 - Forward+ - Using Vulkan Device #0: NVIDIA - GeForce GTX 660 Ti
 
1 []
2 (0, 0, 0, 1)
--- Debugging process stopped ---
```

I expected output '1' at least to be ["normal"]

### Minimal reproduction project

[theme_test.zip](https://github.com/godotengine/godot/files/12473587/theme_test.zip)

**Comment by YuriSizov** [comment]
There is no type `"BUTTON"` in the default theme. Both calls return the expected result. The `get_theme_item_list` call returns you the list of available items for the type in this theme, so it returns nothing. The `get_theme_item` doesn't find any matching theme item in the theme and returns you a fallback value, which is opaque black.

All methods that return specific items fall back on some valid value so the result is always there and your code doesn't break (also not all types are nullable, so these methods need to return something).

There is no bug.

**Comment by AntonWedemeier** [comment]
My mistake.

Thank you for a quick response.

Anton

 

Van: Yuri Sizov ***@***.***> 
Verzonden: woensdag 30 augustus 2023 11:29
Aan: godotengine/godot ***@***.***>
CC: Anton ***@***.***>; Author ***@***.***>
Onderwerp: Re: [godotengine/godot] Theme.get_theme_item_list returns empty list, but Theme.get_theme_item shows that entries exist (Issue #81154)

 

There is no type "BUTTON" in the default theme. Both calls return the expected result. The get_theme_item_list call returns you the list of available items for the type in this theme, so it returns nothing. The get_theme_item doesn't find any matching theme item in the theme and returns you a fallback value, which is opaque black.

All methods that return specific items fall back on some valid value so the result is always there and your code doesn't break (also not all types are nullable, so these methods need to return something).

There is no bug.
