### ISSUE TITLE
Particles rendered incorrectly with a gradient texture

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#81166]
### Godot version

9f9210e60cddb2fa82ce5f7d71fcba340f2edbd1

### System information

Windows 11

### Issue description

I found that one of particles shaders in my project begin working incorrectly after the recent fixes. I've bisected it to 9f9210e60cddb2fa82ce5f7d71fcba340f2edbd1.

Before:
![image](https://github.com/godotengine/godot/assets/3036176/556bb0ed-6214-42ce-b194-8b54b0349b18)

After:
![image](https://github.com/godotengine/godot/assets/3036176/b3fa0b8a-20a6-4c5a-aea7-3e1ec465ea3e)

### Steps to reproduce

Download the provided test project and compare changes with different version.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/12476303/bug.zip)

**Comment by YuriSizov** [comment]
cc @KoBeWi @Geometror

**Comment by KoBeWi** [comment]
When I convert the material to ShaderMaterial it works correctly 🤔
