### ISSUE TITLE
Have tha latest 4.1.2rc Source Godot version, where can I find the HTML export template for it?

### ISSUE THREAD

**Issue by RDaneelOlivav** [godotengine/godot#81165]
### Godot version

4.1.2rc

### System information

Ubuntu 20, NVidia 1680, 32 GB RAM

### Issue description

I can't seem to find a compatible export template for the version of Godot 4.1.2rc, the highest ios the 4.1.1.
Where can I find it ? And if not, how can I download the source version for 4.1.1 which is the one it has those templates available for export?

### Steps to reproduce

Download the branch 4.1 of godot
Try to export to HTML5

### Minimal reproduction project

[ai_realm.zip](https://github.com/godotengine/godot/files/12476275/ai_realm.zip)

**Comment by YuriSizov** [comment]
Version 4.1.2rc doesn't exist, no official builds were published for the 4.1.2 release. If you're compiling from source, you need to compile export templates from source as well. Please follow the [documentation](https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html).
