### ISSUE TITLE
Buggy slider in action deadzone editor

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81171]
### Godot version

4.1.1

### System information

linux

### Issue description

This slider shows up when editing an action's deadzone:

[simplescreenrecorder-2023-08-30_17.19.56.webm](https://github.com/godotengine/godot/assets/71937306/69b7ed34-d6fb-4ce0-98b6-585fb835479b)

### Steps to reproduce

edit an action's deadzone

### Minimal reproduction project

none

**Comment by BlueCube3310** [comment]
This also happens with every Tree Item with cell mode set to range: [TreeCellSliderBug.zip](https://github.com/godotengine/godot/files/12477967/TreeCellSliderBug.zip)
