### ISSUE TITLE
On Vulkan, Sprite3D with ViewportTexture and SubViewport doesn't work in exported project.

### ISSUE THREAD

**Issue by Jordyfel** [godotengine/godot#81173]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

Even though everything is fine in the editor, exporting with either the debug or release template breaks `Sprite3D` nodes with `ViewportTexture`. The problem is present in forward and mobile renderer, not on compatibility. I have an AMD GPU on Windows 11. Tests on other operating systems and GPU vendors are appreciated.

### Steps to reproduce

Create a 3D scene with `WorldEnvironment` and `Camera3D`.
Add a `Sprite3D` node in view of the camera.
Create a `SubViewport` node and place something as it's child.
Create a new `ViewportTexture` in the sprite texture property and select the viewport.
Run the scene, it works fine.
Export the project and run it, the sprite is broken.

### Minimal reproduction project

[empty_project.zip](https://github.com/godotengine/godot/files/12477738/empty_project.zip)

**Comment by tcoxon** [comment]
Same issue in my project (4.1.1 on Linux). Only affected template_release and template_debug builds, not editor builds. I was unable to create a working reproducer, however. The workaround posted in #80636 (`VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE`) worked for me.

**Comment by akien-mga** [comment]
CC @Rindbee @KoBeWi

**Comment by Rindbee** [comment]
It seems that `render_target_update_mode = UPDATE_WHEN_VISIBLE` has no effect in 3D scenes.

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/221884e6bc260c38f16422081b7d4efd49a71375/servers/rendering/renderer_viewport.cpp#L664-L666

`RSG::texture_storage->render_target_was_used(vp->render_target)` has different results after exporting.

This may be a regression bug from #70132. CC @clayjohn 

https://github.com/godotengine/godot/blob/221884e6bc260c38f16422081b7d4efd49a71375/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L934-L937
