### ISSUE TITLE
Creating an APK on Android.

### ISSUE THREAD

**Issue by mesflit** [godotengine/godot#81179]
### Godot version

4.0

### System information

Android

### Issue description

Is there a way to create an APK on Android?

### Steps to reproduce

Is there a way to create an APK on Android?

### Minimal reproduction project

Is there a way to create an APK on Android?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/discussions/4324. This isn't technically feasible given what's available on Android (outside of workarounds with poor UX such as using Termux).
