### ISSUE TITLE
str_to_var(var_to_str("-")) returns 0 instead of "-"

### ISSUE THREAD

**Issue by AcatXIo** [godotengine/godot#81183]
### Godot version

4.2.dev3.official

### System information

Windows 10 - GLES3 (Compatibility)

### Issue description

As documented [here](https://docs.godotengine.org/en/latest/classes/class_@globalscope.html#class-globalscope-method-str-to-var), using `str_to_var()` on a string created with `var_to_str()` is supposed to return back the original `Variant`.

Running:
```gdscript
print(str_to_var(var_to_str("-")))
```
Reveals, that this is not the case for the string `-` (minus/hyphen), as the code returns integer `0` instead of the text.

### Steps to reproduce

Run the MPR code.

### Minimal reproduction project

```gdscript
extends Node


func _ready():
	print(str_to_var(var_to_str("-")))
```

**Comment by AcatXIo** [comment]
This was a mistake of mine, it works correctly, sorry.

**Comment by Calinou** [comment]
@AcatXIo Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by AcatXIo** [comment]
There wasn't any problem after all, just 3 of my mistakes:
- I forgot that `"text"` printed in console meant that the value was actually `"\"text"\"`,\.
- I used `var_to_str(str_to_var())` while it should be `str_to_var(var_to_str())`.
- I miss-clicked and sent the issue before I finished typing.

I removed the issue text so that nobody get's confused.
