### ISSUE TITLE
My Godot is crashing

### ISSUE THREAD

**Issue by LuizHenriqueAmaralSoares-lab** [godotengine/godot#81182]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Pop!_OS 22.04 compatibilitie

### Issue description

when i do anything from saving a scene or creating a script it crashes out of nowhere

### Steps to reproduce

There is no correct way to reproduce the bug, I just do normal game development activities and then godot just stops working and I need to terminate the process on the gnome system monitor

### Minimal reproduction project

My project file of my game
[project.zip](https://github.com/godotengine/godot/files/12480178/project.zip)

**Comment by Calinou** [comment]
What graphics card model and driver are you using? Use **Help > Copy System Info** at the top of the editor.

> My project file of my game
> [project.zip](https://github.com/godotengine/godot/files/12480178/project.zip)

This is not a minimal reproduction project, as it doesn't include project files.

**Comment by LuizHenriqueAmaralSoares-lab** [comment]
Godot v4.1.1.stable - Pop!_OS 22.04 LTS - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 600 (GLK 2) () - Intel(R) Celeron(R) N4000 CPU @ 1.10GHz (2 Threads)
