### ISSUE TITLE
Gizmos lose their colors

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8118]
Tested on Godot 3.0 master c37fad650f92845a6f59740fea2fea1b46f56db1
Windows 10 64 bits 

Sometimes gizmos get coloured in very transparent black, making it hard to tell which axis is which. I don't know yet how it happened but that was quick, after I started adding a few meshes to a scene and creating materials. Closing the scene and reopening doesn't fix it. It also affects the grid.

![image](https://cloud.githubusercontent.com/assets/1311555/24227464/84f80022-0f6d-11e7-9201-76658d6b6e48.png)

**Comment by UgisProductMadness** [comment]
It also happens when you turn off default lightning. Gizmos and grid are affected the same way as regular objects placed in the scene; for example using dof, gizmos and grid get blurred as well.

**Comment by UgisBrekis** [comment]
It also happens when you turn off default lightning. Gizmos and grid are affected the same way as regular objects placed in the scene; for example using dof, gizmos and grid get blurred as well.

**Comment by akien-mga** [comment]
Likely related to #8485.

**Comment by reduz** [comment]
I think this is fixed, gizmos should stay on top and colored always..

**Comment by ShadeVivid** [comment]
I can confirm that it works now on my Win10 a8a1f2e2a864e6b58d5bcf1c7e53a43cdb6d95d9

**Comment by reduz** [comment]
yeah!
