### ISSUE TITLE
SSAO doesn't apply under a plane

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8120]
Tested on Godot 3.0 c37fad650f92845a6f59740fea2fea1b46f56db1
Windows 10 64 bits

~~I'm trying to get SSAO working, but I can't get any result so far. The best I could get were a few rare noisy dots on a model, but on trivial stuff like cubes and planes I get nothing. Not sure if it's badly configured, but so far I didn't find a way to make it work...~~ 

![image](https://cloud.githubusercontent.com/assets/1311555/24228408/49aa1d64-0f74-11e7-9add-027d6c925b25.png)

EDIT: I actually forgot to set the light affect parameter, so SSAO is actually visible now. However there is a "glitch", some parts are unexpectingly not darkened, and the viewport border is darkened:

![image](https://cloud.githubusercontent.com/assets/1311555/24267488/bcb10778-100a-11e7-9c3c-1c371a7f0e41.png)

While they are correct in the non-blurred buffer:

![image](https://cloud.githubusercontent.com/assets/1311555/24267526/d7130990-100a-11e7-8ba8-482712abac78.png)

**Comment by reduz** [comment]
I've seen this bug before, clearly the blur is fucking up something

**Comment by volzhs** [comment]
yeap. maybe this is why some people feels like box is floating.
https://twitter.com/reduzio/status/832068789177040897

**Comment by reduz** [comment]
Ah I understand what's going on... this will need more research and probably better depth reconstruction code to detect dicontinuities

**Comment by reduz** [comment]
@volzhs that's not using SSAO, that's just GI probe, and amazingly it's just an optical illusion because all shadowing is correct there.

**Comment by reduz** [comment]
will move this to 3.1, unless someone wants to spend some hours to tackle the problem, 
if you are such person, let me know and i will explain what could be done.

**Comment by volzhs** [comment]
@reduz i thought that screen has ssao also. i think i was wrong or misunderstood. i just said because i saw similar result with ssao like that from my test.

**Comment by reduz** [comment]
@volzhs heh yeah it is indeed an optical illusion, you can see here up close that it does not have the typical ssao pattern:

![image](https://user-images.githubusercontent.com/6265307/27111707-6c6cc004-5088-11e7-98ff-b2413db50bc6.png)

**Comment by Zylann** [comment]
Still looks weird with after the screen borders fix.

Without blur:
![image](https://user-images.githubusercontent.com/1311555/29844142-9794e2e4-8d0e-11e7-9a68-781d1c163e6f.png)

With blur:
![image](https://user-images.githubusercontent.com/1311555/29844181-b06fb762-8d0e-11e7-8d2d-049262d935cd.png)

Is there anything doable about this?

**Comment by reduz** [comment]
Sorry, I don't get what you mean..

**Comment by reduz** [comment]
@Zylann I did not fix this bug yet, it requires reading the normalmap texture to fix the discontinuities. Will fix it another time as this one is more complex.

**Comment by reduz** [comment]
This is fixed on master branch, in fact I think it was fixed for 3.0 but this issue was never closed.
