### ISSUE TITLE
The AAB package contains the source code even after creating custom export templates with the pck key

### ISSUE THREAD

**Issue by TheJustRusik** [godotengine/godot#81203]
### Godot version

4.1.1

### System information

Android

### Issue description

The aab package contains the source code even after creating custom export templates with the pck key. The official wiki had a warning that encryption would not be enabled on the APK, and the game's source code would be in the assets file. However, this also happens with the AAB package. Is this a bug, or is it really impossible to fully protect your game code on android?

### Steps to reproduce

1. Generate custom android exports templates with some pck key
2. Set this templates in export page in Godot. then set pck key in Encryption page and choose *.gd for encrypt scripts
3. Build AAB and then open it with any archiver like 7-zip. in installTime's folder you will see everything in your game (such as .tscn .gd .gdshader etc.)

### Minimal reproduction project

[android_aab_encryption_bug.zip](https://github.com/godotengine/godot/files/12489216/android_aab_encryption_bug.zip)

**Comment by Calinou** [comment]
Android exports (APK or AAB) don't us a PCK, so there is no PCK to encrypt within.
