### ISSUE TITLE
The scene's default save name missing

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#81225]
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

window10 64bit

### Issue description

![GIF 2023-9-1 22-39-07](https://github.com/godotengine/godot/assets/35988767/d7be4a45-f5f0-4408-8758-f4bf9f3c9c5d)

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by AThousandShips** [comment]
Does this happen when there *isn't* a file already named `Test.tscn`?

**Comment by AThousandShips** [comment]
This is a regression from:
* #51478
