### ISSUE TITLE
Resource is not exported correctly to PCK file

### ISSUE THREAD

**Issue by tobeks** [godotengine/godot#81234]
### Godot version

4.1.1.stable and previous

### System information

Windows 10

### Issue description

During working on my big project I have noticed that Godot cannot export project correctly to pck or exe file.

After running project using release template on Windows I got following error:

```
G:\Godot>Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070

ERROR: No loader found for resource: .
   at: (core/io/resource_loader.cpp:281)
ERROR: Failed loading resource: res://gfx/cwirka.png. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:273)
ERROR: Can't load dependency: res://gfx/cwirka.png.
   at: (core/io/resource_format_binary.cpp:458)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-f582aaee991195987df126394c37c52f-level_3.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:273)
ERROR: Failed loading scene: res://scenes/level_3.tscn
   at: (main/main.cpp:3223)
ERROR: 2 RID allocations of type 'N10RendererRD12LightStorage11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD12LightStorage15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'N18RendererCanvasCull6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N16RendererViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RendererSceneCull8ScenarioE' were leaked at exit.
WARNING: 4 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9441)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2047)
```

But running application from editor works fine without errors or warnings on console:

![obraz](https://github.com/godotengine/godot/assets/13313981/98c8729a-924d-4583-a0df-99a8fdc62776)

### Steps to reproduce

I am unable to reproduce it manually but I am attaching minimal project. It was reduced from bigger project.

Attached project is made of:
- single Scene3D with Camera3D and PlaneMesh. 
- StandardMaterial3D is attached to this plane.
- StandardMaterial3D has albedo_texture set from provided texture.

### Minimal reproduction project

[export.zip](https://github.com/godotengine/godot/files/12499900/export.zip)

**Comment by AThousandShips** [comment]
Do you mean PCK files?

**Comment by rsubtil** [comment]
Can reproduce on Windows, but not on Linux.

**Comment by rsubtil** [comment]
After looking more closely into your export preset configs, looks like the issue is that you disabled the BPTC texture format.

Related to https://github.com/godotengine/godot-proposals/issues/7230.
