### ISSUE TITLE
Godot dialogs starts minimized, and minimize automatically when i try giving them back focus.

### ISSUE THREAD

**Issue by Pshy0** [godotengine/godot#81236]
### Godot version

4.1.1.stable.official.bd6af8e0e

### System information

Ubuntu 23.04 23.04 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (CML GT2) () - Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (4 Threads)

### Issue description

When Godot opens a dialog, it starts minimized.
If i switch to a different window while a dialog is open, it will minimize itself upon giving it back focus, and it will be impossible to open the dialog back, it will be minimized forever, and godot itself unable to get focus (then no choice but to kill godot).

This includes the new node dialog (when opened from the context menu), the node deletion confirmation dialog, the open scenes dialogs.
This does not include the save as dialog, which works as expected, nor the new node dialog when using the "+" icon.

https://github.com/godotengine/godot/assets/44928041/c930ba6c-5d39-4cb8-9eeb-13baa58bae04

### Steps to reproduce

Open the new node dialog with a right click (the + button may not trigger the bug).
Sometime this does not happen on the first try.

### Minimal reproduction project

This is happening in all projects.
For instance, [packed scene](https://github.com/godotengine/godot-docs-project-starters/releases/download/latest-4.x/instancing_starter.zip) from the tutorial.

**Comment by saierXP** [comment]
* Duplicate of https://github.com/godotengine/godot/issues/77333

Please test [4.2.dev4](https://github.com/godotengine/godot-builds/releases/tag/4.2-dev4)

**Comment by Pshy0** [comment]
No longer happening in the linked version.
