### ISSUE TITLE
Compilation of HTML5 export template gives ERROR missing -frtti

### ISSUE THREAD

**Issue by RDaneelOlivav** [godotengine/godot#81233]
### Godot version

3.5.2.stable

### System information

Ubuntu 20, NVidia 1680, 32 GB RAM

### Issue description

I'm trying to compile the HTML5 export template with a custom module that uses ROS2.

When compiling, it gives many errors, that seem that I'm not giving the correct compilation flags?

Gives the following errors:

```
  In file included from /opt/ros/galactic/include/rclcpp/executor.hpp:33:
  /opt/ros/galactic/include/rclcpp/context.hpp:294:28: error: use of typeid requires -frtti
    294 |     std::type_index type_i(typeid(SubContext));
        |                            ^
  In file included from /opt/ros/galactic/include/rclcpp/duration.hpp:20:
  In file included from /opt/ros/galactic/include/builtin_interfaces/msg/duration.hpp:7:
  In file included from /opt/ros/galactic/include/builtin_interfaces/msg/detail/duration__struct.hpp:8:
  /opt/ros/galactic/include/rosidl_runtime_cpp/bounded_vector.hpp:87:7: error: cannot use 'throw' with exceptions disabled
     87 |       throw std::length_error("Exceeded upper bound");
        |       ^
  /opt/ros/galactic/include/rosidl_runtime_cpp/bounded_vector.hpp:106:7: error: cannot use 'throw' with exceptions disabled
    106 |       throw std::length_error("Exceeded upper bound");
```

The command I'm using is this:

`scons platform=javascript tools=no target=release CCFLAGS=-frtti`

### Steps to reproduce

Clone the 3.5.2.stable tag repo of godot.
Install ROS2 galactic [INSTALL ROS2](https://docs.ros.org/en/galactic/Installation/Alternatives/Ubuntu-Install-Binary.html)
source /opt/ros/galactic/setup.bash
copy the module godot_ros ( added as file here) inside the modules folder
Execute the command:

cd godot
scons platform=javascript tools=no target=release CCFLAGS=-frtti

### Minimal reproduction project

[godot_ros.zip](https://github.com/godotengine/godot/files/12499921/godot_ros.zip)

**Comment by akien-mga** [comment]
The web platform on 3.x explicitly disables RTTI to keep binary size small:
https://github.com/godotengine/godot/blob/3.x/platform/javascript/detect.py#L91L93

You'd have to patch this away to compile this module.

I guess we could add an optional to keep RTTI (for Web, Android and iOS I believe).

**Comment by akien-mga** [comment]
I don't have ROS headers installed locally to confirm, but as mentioned above, the solution should be to pass `-frtti` explicitly, which should override the existing `-fno-rtti`, so in `modules/godot_ros/SCsub`:
```python
# ROS needs RTTI
env.Append(CCFLAGS=["-frtti"])
```

In case the compiler complains about having both `-fno-rtti -frtti`, you could remove the `-fno-rtti` manually from `platform/javascript/detect.py`, or also add this in the `godot_ros/SCsub`:
```python
env["CCFLAGS"].remove("-fno-rtti")
```
