### ISSUE TITLE
[C#][Android] Resources not exported 

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#81242]
### Godot version

4.2.dev4.mono

### System information

macOS

### Issue description

When running and Android mono project, errors are thrown in a loop about missing resources.
```
godot com.godot.game E  USER ERROR: Failed loading resource: res://.godot/exported/133200997/export-5c1b5421b3a3843354800198f9326b19-node.scn. Make sure resources have been imported by opening the project in the editor at least once.
godot com.godot.game E     at: _load (core/io/resource_loader.cpp:274)
godot com.godot.game E  USER ERROR: Failed loading scene: res://node.tscn
godot com.godot.game E     at: start (main/main.cpp:3301)
godot com.godot.game E  USER ERROR: Condition "default_certs != nullptr" is true.
godot com.godot.game E     at: load_default_certificates (modules/mbedtls/crypto_mbedtls.cpp:342)
godot com.godot.game E  USER ERROR: No loader found for resource: res://node.cs (expected type: Script)
godot com.godot.game E     at: _load (core/io/resource_loader.cpp:281)
godot com.godot.game E  USER ERROR: Can't load dependency: res://node.cs.
godot com.godot.game E     at: parse_variant (core/io/resource_format_binary.cpp:458)
godot com.godot.game E  USER ERROR: Error when trying to parse Variant.
godot com.godot.game E     at: parse_variant (core/io/resource_format_binary.cpp:502)
godot com.godot.game E  USER ERROR: Error when trying to parse Variant.
godot com.godot.game E     at: parse_variant (core/io/resource_format_binary.cpp:489)
```

### Steps to reproduce

1. Open the MRP
2. Export to Android. Either:
    a. Android Studio project
    b. APK
3. Run the game on device
4. Notice the error being thrown in a loop

### Minimal reproduction project

[AndroidTest.zip](https://github.com/godotengine/godot/files/12503367/AndroidTest.zip)

**Comment by akien-mga** [comment]
Are you sure that you're exporting with the mono build? Does the game run fine on PC?

**Comment by scgm0** [comment]
Minimal reproduction project missing .csproj configuration file.

**Comment by scgm0** [comment]
I still don't have a problem.
![图片](https://github.com/godotengine/godot/assets/52148221/ba39f6a8-d544-435e-94c8-3327ba7e4d33)
![图片](https://github.com/godotengine/godot/assets/52148221/c853b709-bfcd-4db9-a6c4-3c8a49efb5d1)
![图片](https://github.com/godotengine/godot/assets/52148221/3969db4f-2b14-4ef6-96fb-805258d25e74)

**Comment by Mrcubix** [comment]
untick gradle build, runs on my side without it

**Comment by duarteroso** [comment]
> Are you sure that you're exporting with the mono build? Does the game run fine on PC?

My mistake missing out the `.mono` in the build version, it is definetly the mono version I am using.

> Minimal reproduction project missing .csproj configuration file.

I've attached an updated MRP, with the csproj this time. Hope it helps
[AndroidTest-with-csproj.zip](https://github.com/godotengine/godot/files/12505328/AndroidTest-with-csproj.zip)

> 
> * untick gradle build
> 
> The two things that allowed me to make my game run fine on android

When I was building from source, I followed the same steps. Testing dev4.mono, even unticking gradle didn't do it for me... 😞

**Comment by duarteroso** [comment]
Does one need to target `net7.0-android` by any chance?
Got different errors when doing so, and they seem to be more nailed on on things I might be missing (i.e. missing PluginName.get from GodotPlugin)

**Comment by scgm0** [comment]
> dev4.mono

It's strange, I still have no problem exporting with dev4.mono...

**Comment by scgm0** [comment]
[test.apk](https://drive.google.com/file/d/1-VEs_dNBfrgcFJnU5g2zMb8IAipTCypT/view?usp=drive_link)
Here's the apk I exported, can you run it?

**Comment by duarteroso** [comment]
This is the log, do you see anything that is off?
In particular, does this sound correct?
```
Copy: Copying file from "/Users/duarteroso/.nuget/packages/godotsharp/4.2.0-dev.4/lib/net6.0/GodotSharp.dll" to "/var/folders/4v/7l9_zl1d3qxb4mcmspkp0m580000gn/T/godot-publish-dotnet/3109-ExportDebug-android-arm64/GodotSharp.dll"
```
Shouldn't there be a `net7.0` version of the **GodotSharp.dll**?

[msbuild_log.txt](https://github.com/godotengine/godot/files/12535989/msbuild_log.txt)

**Comment by scgm0** [comment]
> This is the log, do you see anything that is off? In particular, does this sound correct?
> 
> ```
> Copy: Copying file from "/Users/duarteroso/.nuget/packages/godotsharp/4.2.0-dev.4/lib/net6.0/GodotSharp.dll" to "/var/folders/4v/7l9_zl1d3qxb4mcmspkp0m580000gn/T/godot-publish-dotnet/3109-ExportDebug-android-arm64/GodotSharp.dll"
> ```
> 
> Shouldn't there be a `net7.0` version of the **GodotSharp.dll**?
> 
> [msbuild_log.txt](https://github.com/godotengine/godot/files/12535989/msbuild_log.txt)

It looks like there is no problem, my logs are also .net6.0 GodotSharp.dll
![图片](https://github.com/godotengine/godot/assets/52148221/37164970-6854-4231-88c8-05d6d3a0ffac)
But that doesn't seem to be in your log? I'm not sure if it's relevant since I'm still a c# rookie (
![图片](https://github.com/godotengine/godot/assets/52148221/5b138807-eea8-4183-a51e-67952fb007bb)

**Comment by duarteroso** [comment]
Thanks for sharing access to your `test.apk` @scgm0 !

Comparing both of them, they don't seem to have much of a difference (test.apk is @scgm0 , build.apk is mine)
![image](https://github.com/godotengine/godot/assets/11413364/fbaec5d6-7308-454d-97b0-40b361c63c15)
perhaps the `libgodot_android.so` is due to different GodotEditor versions?

**Comment by akien-mga** [comment]
Are you using a self compiled version of the export templates? Can you test with the official 4.2-dev4 templates?

**Comment by duarteroso** [comment]
@akien-mga oh boy! I must have mixed the mono with the non-mono templates. After deleting the `export_templates` folder and installing it again from file, it worked 🥲 

Thanks you for the help @scgm0 @akien-mga

**Comment by akien-mga** [comment]
I'm surprised how that happened. How did you install the export templates?

The mono export templates go in `export_templates/4.2.dev4.mono/` and include a `version.txt` file that says `4.2.dev4.mono`. If those `mono` suffixes aren't found, the templates won't be used by Godot Mono and it should say that it's not finding them.

Did you install non-Mono templates, then manually rename the folder and change `version.txt`?

**Comment by WouterVandenputte** [comment]
> * make sure the android export modules have been built with mono enabled, just to make sure,
> 
> scons platform=android target=template_debug arch=armv7 module_mono_enabled=yes
> scons platform=android target=template_debug arch=arm64v8 module_mono_enabled=yes
> scons platform=android target=template_debug arch=x86 module_mono_enabled=yes
> scons platform=android target=template_debug arch=x86_64 module_mono_enabled=yes
> cd platform/android/java
> # On Windows
> .\gradlew generateGodotTemplates
> # On Linux and macOS
> ./gradlew generateGodotTemplates
>  * untick gradle build
> 
> The two things that allowed me to make my game run fine on android

But, where do we put this?
