### ISSUE TITLE
Input Mapping change position

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8126]
Would be nice to have a drag and drop feature for the Input keys like Autoload has.

![image](https://cloud.githubusercontent.com/assets/4741886/24272410/8891e724-101d-11e7-9676-990d8f59ed76.png)

**Comment by Calinou** [comment]
Note that this is about reordering *keys*, not actions. #31061 didn't implement this, so this is still relevant as of https://github.com/godotengine/godot/commit/f9e9cc94cdfcf1bc1dd43e9d61e1394908835099.

**Comment by Calinou** [comment]
This was implemented for both actions and events in https://github.com/godotengine/godot/pull/44181, closing.
