### ISSUE TITLE
Bug? EditorSpinSlider: Change input via ´down´ or ´up´ arrow key

### ISSUE THREAD

**Issue by Alex2782** [godotengine/godot#81272]
### Godot version

v4.1.1.stable.official [bd6af8e0e] and v4.2.dev4.official [549fcce5f]

### System information

macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

If the input is set to -1 and you want to change the value back to 0 by pressing the arrow key up, the value is increased by 0.001 only. This looks like a rounding error (see video below).  In version 3.5.2 it was still ok.

### Steps to reproduce

1. create `Node2D`
2. Inspector -> Transform -> x - Position
3. enter `-1`
4. press the arrow keys `up` several times, then `down` again.

https://github.com/godotengine/godot/assets/41921395/2ff82b7f-b24d-4039-88b3-30328258791d

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can't replicate, and the video doesn't show the same behavior as your description

**Comment by Alex2782** [comment]
now? new video and `Steps to reproduce`

**Comment by AThousandShips** [comment]
I cannot replicate this no, not without pressing other keys, like Alt

**Comment by Alex2782** [comment]
no, only `up` and `down`, on my mac keyboard

**Comment by AThousandShips** [comment]
Looks like you are accidentally dragging when selecting the edit, which modifies the value

Can you confirm this by having the mouse outside the area, and select it with tab instead of clicking on it?

**Comment by Alex2782** [comment]
- new video, now with keyboard events (bottom left)
- `mouse outside the area, and select it with tab`
- `alt (option)` changes the value by `0.1`, but from `-1` and `alt + arrow up` also from time to time by `0.001`

https://github.com/godotengine/godot/assets/41921395/ac921b2c-6180-4f29-a795-4ef8db1241aa

**Comment by AThousandShips** [comment]
Probably something either hardware specific on your end or Mac specific, as I cannot replicate this on Windows

**Comment by Alex2782** [comment]
I'll also check it later under WindowsOS.

I wanted to try to catch `mouse wheel events` and change the values. I could not yet find the logic for arrow keys (up / down). Does anyone know in which file? Via debugging I found out that the variable `text` is only adjusted much later after "_process". Not yet in the function 'LineEdit::gui_input'.

https://github.com/godotengine/godot/blob/fa3428ff25bc577d2a3433090478a6d615567056/scene/gui/line_edit.cpp#L241

**Comment by AThousandShips** [comment]
It's not a `LineEdit` it's an `EditorSpinSlider` under `editor/gui`

**Comment by Alex2782** [comment]
partially reproduced under Windows `v4.1.1.stable`

1. leave input at `0`
2. `alt + key down` reduced by `-0.001 `
3. `alt + key down` reduced by `-0.001 ` to `-0.002` 
4. `alt + key down` reduced by `-0.1 ` to `-0.102` 
5. `alt + key down` reduced by `-0.1 ` to `-0.202` 
6. `alt + key down` reduced by `-0.001 ` to `-0.203` 

that looks strange, or is it intentional?

**Comment by AThousandShips** [comment]
So you've now moved away from the original issue?

**Comment by Alex2782** [comment]
ok thx, I will check it more closely. I think macOS also has a "floating point problem", even with `-1`

**Comment by Alex2782** [comment]
I found out that the `CLAMP` condition is `true` even though the value is within `min / max limit`.
When I comment out the lines, I no longer see the "floating point problem". I think this is a real error `set_value(last_value + real_step)` and `set_value(last_value - real_step)` are executed unnecessarily. With `double`, the floating point problem should only occur after the 10th decimal place and not after 0.001.

https://github.com/godotengine/godot/assets/41921395/5b59f2b8-9224-46cd-9dbb-7f608fc110e5

**Comment by AThousandShips** [comment]
The floating point problem isn't related to floating point rounding, but to representing as text, as you can see it only represents to a fixed number of digits

**Comment by Alex2782** [comment]
I may already have a solution. 

**more questions:**
`get_min()` returns -99999 and `get_max()` +99999

but is it possible to enter larger values, should I still execute `CLAMP` after the normal input or remove it from `key up` / `key down`?
Note: if the values are too large, the input can no longer be changed via "key up" / "key down".
![image](https://github.com/godotengine/godot/assets/41921395/80429bcd-9ec5-4f13-9f38-20bb2b4e5a8c)

**Comment by AThousandShips** [comment]
It is based on the range provided, for `Node2D` the range is `-99999` to `99999`, it depends, other properties have different ranges
