### ISSUE TITLE
Calling get_children() on a Node2D with too many children returns null

### ISSUE THREAD

**Issue by ChrisLR** [godotengine/godot#81271]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 10

### Issue description

In this project, I add multiple Sprite2D to a Node2D via GDScript.
Locally, having 1040 children will return a proper array, but 1041 will return null.
I have set the MVP to 2000 in case it changes from pc to pc.

If you then call get_children() on the sprites parent you get null,
but you can still access the children one by one if you use get_child(i)

Pausing in debug mode to see the remote nodes display them as children as expected.

### Steps to reproduce

In a 2d scene from a Node2D add at least 1041 Sprite2D nodes via GDScript and another Node2D named Listing (or whatever)
Add a Button to the scene.
Add a Script to the Button
Bind the Button pressed to the Button Script
From this function access the Listing and call get_children(), the array will be null despite the sprites being children.

### Minimal reproduction project

[mvpbugchildren.zip](https://github.com/godotengine/godot/files/12566202/mvpbugchildren.zip)

**Comment by AThousandShips** [comment]
If you look at the error messages you will see:
```
Button.gd:8 @ _ready(): Parent node is busy adding/removing children, `remove_child()` can't be called at this time. Consider using `remove_child.call_deferred(child)` instead.
```

You can't manipulate the children in the `_ready` method

**Comment by ChrisLR** [comment]
@AThousandShips thank you for looking into this.
In my main project, there is no such error and the fact that I can see while debugging that the sprites are where they are expected should prove that they have been moved right?
Maybe the issue here is that I don't see the error or that the move only suceeds partially?

**Comment by AThousandShips** [comment]
That is very strange, I haven't tested specifically with 4.1 but the code is the same and moving nodes like this isn't supported, can you try with [4.1.1](https://godotengine.org/article/maintenance-release-godot-4-1-1/)?

**Comment by ChrisLR** [comment]
@AThousandShips yes I see it on the MRP but not in the main project, I will do more testing to try and isolate the bug and update the MRP.
It still occurs with 4.1.1.
And just to confirm in the main project the call to get_children() returns null but get_child works.

```
var children = nody.get_children()
var child1 = nody.get_child(0)
var child2 = nody.get_child(1)
```

children will be null, both child will be properly set.

The sprites themselves were added by GDScript during a button press.

**Comment by AThousandShips** [comment]
Then it is not an MRP, an MRP has to show the bug, so please create an MRP where the bug you reported does happen

**Comment by ChrisLR** [comment]
@AThousandShips I have found out additional info, it seems to be based on the amount of children.

This code here
```
var root_node = get_node("/root/Node2D/")
var list_node = $"../SpriteList"
for i in range(1041):
    list_node.add_child(Sprite2D.new())

var children = list_node.get_children()
```

Will return null for the children list, if I change this number to 1040 I get the array as usual.
Should I update the description or is it a known limitation?

**Comment by AThousandShips** [comment]
Please provide an MRP displaying this behaviour

**Comment by ChrisLR** [comment]
Issue updated with more accurate description and MRP

**Comment by Zireael07** [comment]
Are you sure it's actually **returning** null as opposed to debugger falsely claiming it's null? The debugger has problems with variables _or arrays_ exceeding some sort of size in memory (IIRC 1 GB?)

**Comment by ChrisLR** [comment]
@Zireael07 that might be it, I did hit an error related to the array being empty at first which prompted me to debug and see it was null but using the MRP I can see it prints the good length so it is not actually null.
Closing this, TIL the debugger was sometimes lying.
Thanks for your help
