### ISSUE TITLE
False positive INT_AS_ENUM_WITHOUT_CAST with user-defined enum and class

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#81285]
### Godot version

4.1.1.stable.arch_linux

### System information

Linux 6.4.12-arch1-1

### Issue description

```
extends Node

enum Thing {
	A = 1 << 1,
	B = 1 << 2,
}

class Stuff:
	var thing: Thing

func whatever():
	var s := Stuff.new()
	s.thing |= Thing.B # warning
```

This gives the warning `(INT_AS_ENUM_WITHOUT_CAST): Integer used when an enum value is expected.`. This is similar to https://github.com/godotengine/godot/issues/74593, but that is fixed in 4.1, and that involved a signature taking an `int`. In this case, the operator and operand are both typed as an enum, so there should be no warning. 

### Steps to reproduce

1. Write the above script
2. Ensure `(INT_AS_ENUM_WITHOUT_CAST)` warning is enabled
3. See a warning via the LSP

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/12507934/example.zip)

**Comment by dalexeev** [comment]
GDScript does not have a `BitField[T]` type (maybe we will add it in the future), for bitmasks you should use `int` instead of enum `T` (the `|` operator always returns `int`, even if both operands are `T`).

**Comment by rcorre** [comment]
Hmm, that makes sense after thinking about it more. The result of `|=` is not going to be one of the predefined constants. I was going to argue this just works in languages like C++, but it in fact does not!
