### ISSUE TITLE
Impossible to format `StringName` directly

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#81281]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

You cannot format a `StringName` using `%s` or `.format`.

### Steps to reproduce

Try:
```
print(typeof(&"{0}".format({0: "a"})))
print(typeof(&"%s" % "a"))
```

They are converted into `String`.

If you assing them to a `StringName` variable, they are converted into `StringName`.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
I think this is an active choice, creating a `StringName` is much much more expensive than creating a plain `String`, so it is probably better to let the user decide if they want to then convert the result of some operation on a `StringName` to a new `StringName` or keep it as a `String`

**Comment by YuriSizov** [comment]
StringNames should be used for immutable strings which are accessed often. It's a way to improve performance at a cost of memory consumption, and as a trade-off it needs to be used with considerations. As mentioned above, the behavior is documented and it's not a bug of any sort.
