### ISSUE TITLE
{Feature Request]  Overlapping Tabs

### ISSUE THREAD

**Issue by JimmyJames707** [godotengine/godot#8129]
Hi,
Perhaps add an option to increase the width of Tabs, so the selected Tab overlaps the others? Overlapping tabs is a cool and not uncommon visual effect.

Here's some pictures of a game that uses them. Follow the yellow arrow in the screenshots.
http://tinypic.com/view.php?pic=e6o9bb&s=9
http://tinypic.com/view.php?pic=30t2om1&s=9

**Comment by bojidar-bg** [comment]
I'm pretty sure that this can already be done via StyleBoxeTextures (and maybe a Theme), by using their Expand settings.
Would you mind confirming if this is not the case?

**Comment by JimmyJames707** [comment]
@bojidar-bg
I was able to get the effect following your suggestion. The only issue is the texture was stretched. Thank you.

**Comment by bojidar-bg** [comment]
Closing as resolved then (and yeah, you can totally fix the stretching issue, just test the margins). Next time use the QA/forums

**Comment by JimmyJames707** [comment]
@bojidar-bg 
"Next time use the QA/forums"

Yeah I tried there and they suggested a feature request. Thanks again.
