### ISSUE TITLE
Folder color is not retained after editor restart

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#81342]
### Godot version

4.2.dev.4

### System information

Windows 11

### Issue description

With the new feature in 4.2, user can color folder in different colors. You can change the color in the editor, and it reflects it in the file system dock.
When you restart the editor with the same project or reload the project the color changes to the folders are lost.

### Steps to reproduce

- Create a project
- Add a folder in the file system.
- Change the color of the folder by right clicking and setting the folder color.
- Now reload the project using menu `Project > Reload Current Project `or simply close the editor and reopen the project again.
- The color changes will be lost

### Minimal reproduction project

N.A

**Comment by YuriSizov** [comment]
cc @the-sink

**Comment by AThousandShips** [comment]
Reading the code there isn't actually any code to save it as far as I can see, it calls for the settings to be set, but doesn't actually assign any data anywhere
