### ISSUE TITLE
Can't set font size from code

### ISSUE THREAD

**Issue by gejza74** [godotengine/godot#81341]
### Godot version

4.1, 4.2-dev

### System information

Godot v4.2.dev4 - Debian GNU/Linux 12 (bookworm) 12 - Tty - Vulkan (Mobile) - integrated Intel(R) HD Graphics 4000 (IVB GT2) () - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 Threads)

### Issue description

Hi, i try to set some properties of a label, and it looks like there is some bug in font_size. I can set h or v alignment, color, outline, font, etc,  but the font size change don't do anything. Is it a bug, or I didn't understand something correctly? Thank you

### Steps to reproduce

You can set every relevant thing on the main scene's 2 type of children (both are labels), but not the font size.

### Minimal reproduction project

[LabelTest.zip](https://github.com/godotengine/godot/files/12524564/LabelTest.zip)

**Comment by YuriSizov** [comment]
Thanks for opening a bug report. Your MRP contains too much unrelated stuff, please remove everything that is not necessary to reproduce the bug. Also make sure you're using `add_theme_*_override` methods.

**Comment by gejza74** [comment]
I send again the example project with direct access to Label's size too, it works correctly,
and with exported access what don't works.

Maybe some export function name difference exists.

But here is the important part:

Used directly, and works:
$Label.add_theme_font_size_override("font_size", currenntSize)


Used as object (MyLabel on main scene) through exported value, and dont works:
add_theme_font_size_override("font_size", textFontSize)

Exported variable declaration:
var textFontSize : int = 26
@export var textFontSize_proxy : int = 26 :
	get:
		return textFontSize
	set(value) :
		set_textFontSize(value)

func set_textFontSize(value: int) -> void:
	if(0 < value):
		textFontSize = value
		add_theme_font_size_override("font_size", textFontSize)


I don't see any problem with this code.

But what is strange if I look on the hover text of
Theme overrides/Font Sizes/ the text:
Property: theme_override_font_sizes/font_size

The function what exists:
add_theme_font_size_override

Not sizes.
Any idea?

[LabelTest.zip](https://github.com/godotengine/godot/files/12527522/LabelTest.zip)

**Comment by bruvzg** [comment]
You are using both theme overrides and `LabelSettings` at the same time, `LabelSettings` have higher priority and will override font size with its value, so use it to set font size as well.

**Comment by gejza74** [comment]
I see. Thank you.

**Comment by YuriSizov** [comment]
Closing per comments above.
