### ISSUE TITLE
Crash when stopping the project.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#81351]
### Godot version

v3.6.beta3.official [21ab700f2]

### System information

w10 64

### Issue description

When I press Stop to stop the execution of the Godot project, it sometimes crashes.
The video shows the state in which Godot is left.
Godot freezes, godot must close because a crash occurred.
The console window goes into an infinite loop and shows the error seen in the video.

https://github.com/godotengine/godot/assets/19652075/4b1aa57c-9a51-4604-9aad-d2666bcaa3f7

![Captura4](https://github.com/godotengine/godot/assets/19652075/9db879ae-d0db-4d62-ab13-f4578aefdf1b)

### Steps to reproduce

...

### Minimal reproduction project

It is a big project and it is difficult to isolate the error.
It is necessary?

**Comment by rsubtil** [comment]
Looks related to #43705 and #38058.

**Comment by Torguen** [comment]
Yes, it's the same error.

**Comment by YuriSizov** [comment]
Closing as a duplicate then, thanks for opening a report. If you manage to isolate the issue and provide an MRP that demonstrates it's a different problem, this can be reopened.
