### ISSUE TITLE
Mouse position unknown until mouse moved

### ISSUE THREAD

**Issue by spusnei-pbsc** [godotengine/godot#8136]
**Operating system or device - Godot version:**
GoDot v2.1.2

**Issue description:**
If the mouse didn't move the system doesn't know the position, even after a button was clicked. I am not sure about the behavior on touchscreen, have to test it yet.
related to https://github.com/godotengine/godot/issues/1212

**Steps to reproduce:**
- Create a 2D node
- add `func _input(event):
	if event.type == InputEvent.MOUSE_BUTTON:
		print(get_global_mouse_pos())`
- launch application, don't move the cursor and click mouse button

**Link to minimal example project:**
[bug-mouse-move.zip](https://github.com/godotengine/godot/files/868955/bug-mouse-move.zip)
launch the app, don't move the mouse and click any button, you will see that global position remains 0,0

**Comment by bojidar-bg** [comment]
Can confirm on linux.

@spusnei-pbsc Would you mind sharing your OS too?

**Comment by sergey-push** [comment]
Ubuntu 16.04
