### ISSUE TITLE
Manual / PlugINS / Running Code in the Editor

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#81367]
### Godot version

Godot_v4.2-dev3

### System information

Windows 10

### Issue description

https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html#what-is-tool

- Following the manual instructions
- in Editing variables
- Infinite loop of errors 
![image](https://github.com/godotengine/godot/assets/77213594/4ac1bb2c-5cf8-4a76-92e2-d2c0c46791e8)

### Steps to reproduce

- Create new scene sprite 2D
- add script, add @tool, rotation += PI * delta
- @export var speed = 1, or follow the manual:
- @export var speed = 1:
    # Update speed and reset the rotation.
    set(new_speed):
        speed = new_speed
        rotation = 0

- multiply delta and speed
- Infinite loop off errors 

![GDerror](https://github.com/godotengine/godot/assets/77213594/318853da-0909-490c-86e6-73750f668ce1)

### Minimal reproduction project

fgasfdsaf

**Comment by YuriSizov** [comment]
I'm pretty sure you need to reopen your scene after exporting a new property in a tool script, otherwise you cannot use it. This is due to hot reloading not being able to update existing instances of the node.

Also, it's not an infinite loop, you're calling the code in the `_process` method which is called every frame (so the error is printed every frame).

**Comment by jonSP12** [comment]
the var speed was set to 0 in the 2D editor
changed it to 1  and it works
closing and opening the scene or Reload Saved Scene, didnt worked


![GDerror](https://github.com/godotengine/godot/assets/77213594/a5fcff0b-8455-4a1c-9310-f981036f8a88)

**Comment by rsubtil** [comment]
Can you try this without having any setter defined?

Also, can you upload this example as a MRP to make testing easier?

**Comment by Calinou** [comment]
Closing per the above comment.
