### ISSUE TITLE
Incorrect GDScript highlighting of variables passed as values in dictionary function arguments.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#81362]
### Godot version

4.2.dev4

### System information

Godot v4.2.dev4 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/cd9f31f3-3b65-4433-a24b-9c59204ead47)

I noticed the bug in a real use case here. Note that `w` and `h` are highlighted like they are types.

### Steps to reproduce

```gdscript
var a = 3
f({"a": a})
```

Paste this into a script

### Minimal reproduction project

N/A

**Comment by adeneve** [comment]
Looks like this is happening because it thinks it's a function argument hint (because of the colon ':"). I have a potential fix here (tested and seems to work) https://github.com/adeneve/godot_fork/tree/gdscript_dict_highlighter_fix. Let me know what you guys think!

**Comment by MewPurPur** [comment]
Make a PR please!

**Comment by adeneve** [comment]
Ok, PR created. FYI, I made a slight change to try to account for nested dictionaries.
