### ISSUE TITLE
Export save dialogue doesn't prefill will set export path

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#81363]
### Godot version

4.2.dev4

### System information

macOS 13.5.1

### Issue description

A small new issue, in 4.2.dev4 with exports. When exporting the game using an export preset the Save dialogue you get no longer prefills the name field in the save dialogue with the filename set in the export path. Instead it's left empty, but if you press save you get a warning that you have to fill in a name for your export.

### Steps to reproduce

- Create an export template (seems to be the same for any platform I've tried), for example Android, specifying an export path with a filename.
- Click "Export project..."
- Observe that the export save dialogue file name field is empty.

### Minimal reproduction project

Not specific to project, general export issue

**Comment by YuriSizov** [comment]
Thanks for the report. Seems to be the same issue as https://github.com/godotengine/godot/issues/81225.
