### ISSUE TITLE
The initial position of the main window does not work when running within the editor.

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#81373]
### Godot version

v4.2.dev.mono.custom_build [0a7f75ec7]

### System information

Godot v4.2.dev.mono (0a7f75ec7) - Arch Linux #0~20230903.g20dcd95 SMP PREEMPT_DYNAMIC Sun Sep  3 05:16:45 UTC - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.104.05) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

Even if the initial position type is set to absolute position, the main window remains centered when running in the editor.
![图片](https://github.com/godotengine/godot/assets/52148221/ecc23186-cebe-4708-9ab5-2aed591753ba)
![图片](https://github.com/godotengine/godot/assets/52148221/88f319af-2058-407e-a88a-6c87089137ae)
Exporting and itemizing lists work fine when run.

### Steps to reproduce

1.Sets the main window initial position type to absolute.
2.Run the project in the editor.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
When running from the editor, initial window position is overridden by `Editor Settings` → `Run` → `Window Placement`.

**Comment by scgm0** [comment]
> When running from the editor, initial window position is overridden by `Editor Settings` → `Run` → `Window Placement`.

Strange setup, but it does work, thanks!
