### ISSUE TITLE
Clear color alpha value affects 2D editor in Compatibility renderer

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#81382]
### Godot version

4.1.1.stable, 4.2.dev (2282fc5de)

### System information

Arch Linux - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 535.104.05) - 13th Gen Intel(R) Core(TM) i5-13400F (16 Threads)

### Issue description

When using Compatibility renderer, adjusting the Alpha component of clear color affects 2D editor content.

This does not happen when using Forward+ or Mobile renderer. Does not affect 3D editor and the running game.

https://github.com/godotengine/godot/assets/372476/e398522e-590a-4832-959f-ea8ba8e71c5d

### Steps to reproduce

1. Create a project using Compatibility renderer.
2. Adjust the clear color's alpha component in Project Settings.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
It looks like its making the 2D viewport transparent.

In the RD renderer, we don't include an alpha channel in the render target if transparency is not enabled https://github.com/godotengine/godot/blob/8449592d92eaeef990f5502b419d491ee3eeb7a6/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp#L3060

In the Compatibility renderer we always have a little transparency in the format:
https://github.com/godotengine/godot/blob/master/drivers/gles3/storage/texture_storage.cpp#L1665

The solution is going to be to force the alpha of the clear color to one when transparency is not enabled here https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_canvas_gles3.cpp#L2118
