### ISSUE TITLE
[3.0] The import dock doesn't update when a resource is accessed from the inspector

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8139]
Tested on Godot 3.0 master af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits

When the little arrow on the right of a resource is clicked in the inspector, it shows the resource but the import dock doesn't updates.
It only does when the resource is double-clicked in the file explorer.
I expected it to work when resources are accessed from the inspector too.

**Comment by nunodonato** [comment]
+1 for this, would be quite useful

**Comment by akien-mga** [comment]
Fixed by #9378.
