### ISSUE TITLE
Depth-of-field blur is applied on gizmos even when set far away

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8140]
Tested on Godot 3.0 master a0b0dff6fdbdc4be78087aa572f3da5dbb8daa01
Windows 10 64 bits nVidia GeForce 940M

DoF is applied in the editor on the gizmos, at any distance, even if set far away. Meshes don't seem to be affected by the issue.

![image](https://cloud.githubusercontent.com/assets/1311555/24316847/a18622d4-10f1-11e7-8a63-e16c4643ecb0.png)

![image](https://cloud.githubusercontent.com/assets/1311555/24316895/2639b748-10f2-11e7-876f-1f85600b0774.png)

**Comment by bojidar-bg** [comment]
Looks like some Z-buffer related issue (the gizmos are having Z=Infinity, since they don't write to the buffer).

**Comment by kubecz3k** [comment]
Can confirm on 3.0.2.

**Comment by MrCrowley2** [comment]
in 3.1 Beta the whole editor view window is blurred when enabling far blur, including all objects and gizmos. This only happens when the world environment node is not used in the camera but in the scene.

**Comment by KoBeWi** [comment]
The issue of gizmos blurring regardless of distance seems to be fixed in 3.2
![image](https://user-images.githubusercontent.com/2223172/84444836-ebaca280-ac42-11ea-8adf-b8fe3bd7b8d8.png)
And the blur alone is intentional according to https://github.com/godotengine/godot/issues/37560#issuecomment-608677129, so this can be closed I guess.

**Comment by dueddel** [comment]
I am not sure if I should create a new ticket for **Godot 3.3** or if I should just comment on this one. However

As far as I can remember (it's a small test project and I didn't work on it for 2 weeks as of writing this) the gizmo wasn't blurred in Godot 3.2.3. But now in Godot 3.3 the **gizmo manipulator** totally **blurred** when **Dof Far Blur** is activated.

These are my environment settings and a screenshot of a Spatial node's gizmo
![Bildschirmfoto 2021-04-23 um 09 33 22](https://user-images.githubusercontent.com/436636/115836382-b4d51a80-a417-11eb-9889-3ab839499490.png)
![Bildschirmfoto 2021-04-23 um 09 37 19](https://user-images.githubusercontent.com/436636/115836384-b56db100-a417-11eb-80a6-cafa76b5bc24.png)

And a sample MeshInstance with different zoom levels:
![dof-blur-1](https://user-images.githubusercontent.com/436636/115837707-2b264c80-a419-11eb-8eaf-20c2086e24c0.png)
![dof-blur-2](https://user-images.githubusercontent.com/436636/115837710-2bbee300-a419-11eb-95dc-18950c955b89.png)
![dof-blur-3](https://user-images.githubusercontent.com/436636/115837711-2c577980-a419-11eb-950a-9ef7006bea26.png)
