### ISSUE TITLE
about colour

### ISSUE THREAD

**Issue by wzc1392969921** [godotengine/godot#81427]
### Godot version

3.5

### System information

windows11

### Issue description

i have a pictures.It is composed of rgb mode, but now I need to convert it to cmky mode, similar to ps mode. What should I do in godot?

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by Calinou** [comment]
> i have a pictures.It is composed of rgb mode, but now I need to convert it to cmky mode, similar to ps mode. What should I do in godot?

For reference, Godot doesn't support CMYK color formats, which are only meant to be used for working with printers.
