### ISSUE TITLE
Godot 4 GPUParticles3D become choppy when using Engine.TimeScale, and Interpolate only smooths translation but not rotation

### ISSUE THREAD

**Issue by jamesdkay** [godotengine/godot#81429]
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

In Godot 4 setting Engine.TimeScale to less than 1 has a different effect on particle systems than it does in Godot 3. In Godot 3 the particle system just runs slow but remains smooth just like you'd expect. In Godot 4 the particle system starts updating more slowly as well, and so it becomes very choppy.

I suppose a workaround would be to keep track of all running particle systems and change their fixed_fps property proportionally whenever you change Engine.TimeScale...but I think how this worked in Godot 3 is much closer to what you'd expect and what you'd want nearly all the time. It seems like in Godot 3 Engine.TimeScale doesn't affect how often the particle system updates, only the time delta passed to it. In Godot 4 it seems like the time delta stays the same and it just updates less frequently?

In a related note, you can partially work around this by enabling Interpolate, as this will smooth the motion of the particles even if they are updated less often...but it seems like there is a bug in Interpolate as well because it only interpolates the translation but not the rotation of the particles.

See clips below for examples of how this looks in Godot 3 and Godot 4. First clip is Godot 3. A particle system is started and then Engine.TimeScale is used to slow down the action. Particles become slow but remain smooth:

https://github.com/godotengine/godot/assets/59898064/57d37fd6-d109-4655-a2cc-817ca15c985f

In Godot 4 the same thing is done. The particles become choppy as soon as Engine.TimeScale is set:

https://github.com/godotengine/godot/assets/59898064/4bcdc938-978f-49d5-a4e2-fe69a7c1f92a

In Godot 4 with Interpolate turned on, this smooths the slow updating but only for the particles' translation. The rotation remains choppy:

https://github.com/godotengine/godot/assets/59898064/ac654d11-7159-48e0-bc67-30e8be737b51

Note that I expect this probably affects other types of particle systems too, but I have only tested with GPUParticles3D

### Steps to reproduce

Create a GPUParticles3D system with some initial linear and angular velocity. While it's running change Engine.TimeScale to something like 0.05. The particle system will become very choppy as it starts updating infrequently. Enable interpolate and try again, and the linear motion gets somewhat smoothed but the rotation does not.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/50824.

As a workaround, disable **Interpolate** and set **Fixed FPS** to 0 on GPUParticles3D.
