### ISSUE TITLE
Physics and Process frames take a very long time in the profiler

### ISSUE THREAD

**Issue by Maimas2** [godotengine/godot#81435]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Linux Mint 21.2 (Victoria) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 860M (nvidia; 525.125.06) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When using the profiler, it always displays large values for “Physics Frame Time” and “Process Time.”
The Physics Frame Time is always 16.66ms, even when there are no physics nodes in the tree.
The Process Time is very large, even when there is nothing taking up processor time.
![image](https://github.com/godotengine/godot/assets/77930865/4a27fe97-b5c7-4951-ae64-eb2c1b47b66b)
In a full project, it still runs at a full 60 fps, despite the Frame Time also being above 16 milliseconds.

### Steps to reproduce

1. Create a new project, and a new, empty scene.
2. Run the scene.
3. Open the profiler. The Physics Frame Time and Process Time should be large.

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
At least I think the display for “Physics Frame Time” is intented behaviour, physics frame is constant, and is determined by a setting in Project Settings > Physics > Common.

**Comment by AThousandShips** [comment]
16.66 ms is 1/60 seconds, the default physics frame rate

**Comment by michaldev** [comment]
Why is it displayed in red?

**Comment by Calinou** [comment]
> Why is it displayed in red?

Colors are randomly chosen for each checked element. There's no particular meaning to each color in the profiler and visual profiler.

PS: Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
