### ISSUE TITLE
[C#] Plugin fails to load using suggested default plugin script folder

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#81431]
### Godot version

4.2-dev4.mono

### System information

macOS

### Issue description

In the new [Android plugin V2 documentation (draft)](https://github.com/godotengine/godot-docs/blob/c451d57eb11fe1e58069a008591adbdf37bc8d8c/tutorials/platform/android/android_plugin.rst#packaging-a-v2-android-plugin), it is suggested to place the editor script files in a folder called `.export`.
Doing so will make it impossible to load the said plugin.

### Steps to reproduce

1. Create a C# plugin
2. Place the plugin script in a folder called `.export` (or any .folder I think)
3. Update the plugin.cfg with the new path
4. Go to project settings
5. Load the plugin

![image](https://github.com/godotengine/godot/assets/11413364/6f9b00ec-cdc4-47ba-a4e1-90952e4b15de)

### Minimal reproduction project

[CSPlugin.zip](https://github.com/godotengine/godot/files/12552186/CSPlugin.zip)

**Comment by duarteroso** [comment]
Tagging @m4gr3d :)

**Comment by m4gr3d** [comment]
@duarteroso Does the issue go away when removing the `.` from the path (e.g: `res://addons/two/export/Two.cs`)?

Also note that the changes were landed after dev4, so will only be available starting with dev5.

**Comment by duarteroso** [comment]
> @duarteroso Does the issue go away when removing the `.` from the path (e.g: `res://addons/two/export/Two.cs`)?
> 
> Also note that some of the changes were landed after dev4, so will be available starting with dev5. Though it shouldn't affect what you're currently testing.

It does yes (it is not in the MRP but I tried locally right after). My best guess is that dot-folders are skipped during parsing

**Comment by m4gr3d** [comment]
> It does yes (it is not in the MRP but I tried locally right after). My best guess is that dot-folders are skipped during parsing
> 
> If this is fixed in dev5, feel free to close this issue 👍🏽

@duarteroso I've updated the recommended plugin directory structure in https://github.com/godotengine/godot-docs/pull/7884 to the following:

```
    MyPlugin/
    |
    +--MyPlugin.1.1.2.release.aar  # the release version of the aar file (naming standards is up to the creator)
    |
    +--MyPlugin.1.1.2.debug.aar  # the debug version of the aar file (naming standards is up to the creator)
    |
    +--export_plugin.gd         # export plugin tool script
    |
    +--plugin.cfg               # plugin INI file
```

Can you try the new approach and let me know if that resolves the issues you were seeing before.

**Comment by duarteroso** [comment]
I've settled for this layout, similar to your original one (with the .folder for the platform AARs) 👍
Seems to be working fine so far.

![image](https://github.com/godotengine/godot/assets/11413364/5d7b3f67-7c1f-4200-bb95-cc421cc76241)

**Comment by m4gr3d** [comment]
Looks good!
