### ISSUE TITLE
Error when typing in the script editor after text search

### ISSUE THREAD

**Issue by gokiburikin** [godotengine/godot#81441]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Windows 10

### Issue description

`scene/main/node.cpp:1757 - Parameter "p_node" is null.` when attempting to type after using find function. Does not happen in 4.2dev3.

https://github.com/godotengine/godot/assets/3820082/4a2818f7-cc3b-4b46-a0b1-5bc6a85b4abc

### Steps to reproduce

1) Open any script in the script editor
2) Ctrl+F to select some text that exists in the script
3) Hit escape to re-focus the script editor without placing the caret
4) Attempt to type

### Minimal reproduction project

[find-mrp.zip](https://github.com/godotengine/godot/files/12555561/find-mrp.zip)

**Comment by jsjtxietian** [comment]
Looks like `get_viewport()->gui_get_focus_owner()` is null after hitting escape, so it passed null to `is_ancestor_of`. 

`if ((find_replace_bar != nullptr && find_replace_bar->is_visible()) && (find_replace_bar->has_focus() || find_replace_bar->is_ancestor_of(get_viewport()->gui_get_focus_owner()))) {`
