### ISSUE TITLE
'Invalid get index' cyclic issues.

### ISSUE THREAD

**Issue by produno** [godotengine/godot#81447]
### Godot version

Godot v4.2.dev4

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

I am having a lot of what i think are cyclic issues since using Godot v4.2.dev1 through to Godot v4.2.dev4. Looking through the release notes i suspect it has something to do with #79205. 

Due to how large my project is i am unable to create an mrp so i will do my best to describe what is happening. I also make heavy use of custom classes as i use a lot of RefCounted only which i suspect is causing me issues.

### Steps to reproduce

In the video below you can see that upon loading the editor, the Asset class does not know it is inheriting from Entity. If i remove a referenced class on Entity (Or force it to reload) then it registers that it is now inherited from Entity, at least in the editor.
The problem now though is that when i run the game, once it gets to this script, it will not call any functions on the Entity class. Instead it shows the following error: `Invalid get index 'take_damage' (on base: 'Node2D (Asset)').` (take_damage is a method on Entity.)
If however i put the take_damage method onto the Asset class too, then it will run without throwing the error.

https://github.com/godotengine/godot/assets/8760003/4230317d-3892-4abf-b229-bf41f6f22b8b

This same issue seems to happen for quite a few of my classes so currently i cannot even get my project to run in v4.2.
I also notice on some classes i need to remove references to static classes, ie classes with just static variables and methods which i use for utility classes.
Sometimes i cannot call methods on the class itself either so it seems something is stopping the class from compiling at all. I get no errors in the editor, only when i run the game and it comes to the specific class/method.

### Minimal reproduction project

Unfortunately my project is quite large so i am unable to pinpoint the exact issue to create a Mrp. I was debating if i should file this report because of this reason.

**Comment by produno** [comment]
Just to note that everything is working fine in v4.1.1-stable so this is a regression introduced in v4.2-dev1.

**Comment by anvilfolk** [comment]
Always worth reporting! Worst case scenario it gets closed as a duplicate, but at least there is something to track! @dalexeev pointed me in this direction from #81548, which seems specifically to be about static functions, so hopefully a fix for that will also result in a fix for the static-related stuff here.

If you do happen to manage to create an MRP, that's the best way for us to track down what's happening. Cyclic dependencies are tough to test. Can you check out the MRP in #79205? Basically it creates a cyclic dependency where the "entrypoint" is halfway down the class hierarchy, which seems to highlight the issue. The entrypoint seems to be pretty important, and you can control that by having a single node in the project with the first script you want to load attached :)

**Comment by anvilfolk** [comment]
There is a chance that #81577 fixes this - would you be able to test it out once the artifacts are done building? :)

**Comment by produno** [comment]
> There is a chance that #81577 fixes this - would you be able to test it out once the artifacts are done building? :)

Yep, this seems to have fixed it. Thanks!

**Comment by anvilfolk** [comment]
Yessssss, that makes me so happy! These cyclic dependency compilations issues have been a whole thing! 😅 

Thank you so much for testing!

**Comment by produno** [comment]
> Yessssss, that makes me so happy! These cyclic dependency compilations issues have been a whole thing! 😅
> 
> Thank you so much for testing!

No worries! Thankyou for working on it :).
