### ISSUE TITLE
Setting Extra Spacing on a FontVariation with a bitmap font causes missing character symbols to appear

### ISSUE THREAD

**Issue by NewDefectus** [godotengine/godot#81455]
### Godot version

4.2.dev4

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

I have a scene in my game where I need some special spacing on a font. The font happens to be a bitmap font (it has to be in my case, to avoid rendering issues), which on its own renders fine:

![image](https://github.com/godotengine/godot/assets/36775845/80deb2cc-ab8d-493f-91ee-f131cb69e622)

However (and I believe this is new since 4.2.dev4, as I didn't see it happen in 4.2.dev3), setting any of the Extra Spacing settings causes the font to error and produce missing symbols:

![image](https://github.com/godotengine/godot/assets/36775845/38b91bf4-7dbe-4e39-bedf-0b36383baa4b)

### Steps to reproduce

Run the minimal reproduction project, and try setting/unsetting the Extra Spacing options (the font only renders when they are all set to 0)

### Minimal reproduction project

[FontVariationBug.zip](https://github.com/godotengine/godot/files/12560648/FontVariationBug.zip)

**Comment by matheusmdx** [comment]
Bisecting shows that started after #80954
