### ISSUE TITLE
cant have _ready(): if inherited scene has _ready():

### ISSUE THREAD

**Issue by AdamsAGD** [godotengine/godot#81468]
### Godot version

4.0

### System information

windows 11 Corei5 1350H

### Issue description

not a huge bug but semi annoying to have to assign var to everything.

i have an inherited script and in the base_script i have _ready(); function, i use it to set variables and make new classes.  but in my npc's main script if there is also a  _ready():  the base _ready(); wont work.

my ready looks like this
```
func _ready():
    attack = class_attack.new()
    attack.attack_damage = 12   <--  this cant be set outside of _ready unless i use a var to establish it. 
```

as soon as i deleted the _ready(): inside of the npcs inherited script, thats when the base scripts _ready started working. i put a print() inside that wouldnt even print when the NPC's inherited script had_ready inside it
### Steps to reproduce

make an inherited script both with _ready functions and the base script wont register anything inside the _ready

### Minimal reproduction project

none

**Comment by AttackButton** [comment]
Did you try to use `super()` or `super._ready()`?

**Comment by AThousandShips** [comment]
What exact version are you on? Are you on version 4.0 specifically?

**Comment by AThousandShips** [comment]
This is because you have to explicitly call the method in the super class, see [here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance)

**Comment by KoBeWi** [comment]
Yes, you need to call the method from base class. In case of `_ready()` it used to be done automatically in Godot 3, but isn't anymore.
