### ISSUE TITLE
3.5.2. - Audio Server performance issue

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#81461]
### Godot version

3.5.2.stable

### System information

Windows 7 - GLES3 - dedicated NVIDIA GeForce GT 1030 () - AMD Athlon(tm) II X2 250 Processor (2 Threads)

### Issue description

First things first... I'm quite unsure if this is a problem of the engine. Most likely i did something wrong. But after long time of analysis i couldn't figure out what exactly goes wrong.

![2023-09-08T19-57-55](https://github.com/godotengine/godot/assets/37717199/a48d55fb-1f9d-461b-9025-fa22e34378bc)
![image](https://github.com/godotengine/godot/assets/37717199/1367d740-9fb2-472e-a229-ab7b92e90dcc)

m_day1_1 is the first mission the player will participate in, and, somehow, it became the most heaviest game level in this project. I've done a lot of various things to optimize it, starting from game level geometry, ending with script-related logic of literally everything. But, sadly, currently i can't fix the "Audio Server" issue. Profiler shows it as the main user of CPU, 56 ms is for about 17 FPS, which is exact amount of FPS i've usually got on this level.

What i've attempted to do:
- Removing audio, somewhat that didn't help
- Removing scene file and copy-paste the contents
- Googled related issues yet i couldn't find the similar one
- Removed all audio effects from all buses

And all of this stuff didn't help. I missed something, but i don't know what exactly.

I've had similar performance issue in Garry's Mod, when i launch this game with AIMP working in background, this randomly results 1 FPS inside of game. I tried turning the AIMP down with task manager, and, yea, that didn't do anything much.

I know that my hardware is far from best, but i'm still wondering why Audio Server uses that much frame time.

### Steps to reproduce

Unknown yet.

### Minimal reproduction project

I don't know how to replicate it yet.

**Comment by Calinou** [comment]
> Removing audio, somewhat that didn't help

Does it occur if you set the audio driver to `Dummy` (case-sensitive) in the project settings? Alternatively, run the project with `--audio-driver Dummy` command line argument (this works with the exported project too).

**Comment by Dadaskis** [comment]
![0](https://github.com/godotengine/godot/assets/37717199/d8cb3d16-9d05-49a3-b716-86ec15557f41)
![1](https://github.com/godotengine/godot/assets/37717199/60d52fb9-2780-4794-801b-be1966deeeac)

@Calinou ^^^

Same issue remains. Should i check something else?

**Comment by Calinou** [comment]
> Same issue remains. Should i check something else?

This likely means the profiler readout is bogus. I'd suggest using a [debug build](https://github.com/Calinou/godot-debug-builds/releases/tag/v3.5.1) (I don't have one for 3.5.2 currently) and running it through a [C++ profiler](https://docs.godotengine.org/en/latest/development/cpp/using_cpp_profilers.html) while running the project directly using the `--path` [command line argument](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html).

**Comment by Dadaskis** [comment]
@Calinou 

Thanks for recommendations. I launched the project with your debug build of 3.5.1., used "Very Sleepy" as it is said in the documentation link you sent. Gotta say that the game had 2 fps when i was running it with debug build, but i've got profiling of the running game. As i understand, i need to send these to you? I've got the Very Sleepy profile file and the CSV export.

This archive contains all of the mentioned files. As i noticed, a lot of the process time in this case is taken by "sleep" process in my case, but other than that i can't notice anything else. Should i do something else with it?

[index_purger_debug.zip](https://github.com/godotengine/godot/files/12567756/index_purger_debug.zip)

**Comment by MJacred** [comment]
Please check the following (while still dummy selected)
* please do https://docs.godotengine.org/en/3.5/classes/class_audioserver.html#class-audioserver-property-bus-count and run for all busses and tell us your results
  * https://docs.godotengine.org/en/3.5/classes/class_audioserver.html#class-audioserver-method-is-bus-bypassing-effects
  * https://docs.godotengine.org/en/3.5/classes/class_audioserver.html#class-audioserver-method-get-bus-effect-count
* use files other than WAV, try e.g. ogg vorbis and mp3

**Comment by Dadaskis** [comment]
@MJacred 

> please do https://docs.godotengine.org/en/3.5/classes/class_audioserver.html#class-audioserver-property-bus-count and run for all busses and tell us your results ...

Alright, i've written a console command for this case.

Code (to avoid confusion):
```
func debug_print_audio_bus_data():
	Console.wrtie_line(":: Audio Bus Info ::")
	Console.write_line("bus_count :: " + str(AudioServer.bus_count))
	for index in range(AudioServer.bus_count):
		Console.write_line(":: Bus info, index: " + str(index))
		Console.write_line(
			"Bypass effects: " + str(
				AudioServer.is_bus_bypassing_effects(index)
			)
		)
		Console.write_line(
			"Amount of effects: " + str(
				AudioServer.get_bus_effect_count(index)
			)
		)
```

Output:
```

$ debug_print_audio_bus_data
:: Audio Bus Info ::
bus_count :: 15
:: Bus info, index: 0
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 1
Bypass effects: False
Amount of effects: 2
:: Bus info, index: 2
Bypass effects: False
Amount of effects: 2
:: Bus info, index: 3
Bypass effects: True
Amount of effects: 4
:: Bus info, index: 4
Bypass effects: True
Amount of effects: 4
:: Bus info, index: 5
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 6
Bypass effects: True
Amount of effects: 4
:: Bus info, index: 7
Bypass effects: True
Amount of effects: 4
:: Bus info, index: 8
Bypass effects: True
Amount of effects: 2
:: Bus info, index: 9
Bypass effects: True
Amount of effects: 2
:: Bus info, index: 10
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 11
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 12
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 13
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 14
Bypass effects: False
Amount of effects: 0
```

Gotta say that audio buses #3 and #4 have 8 effects in total that are bypassed. These were temporarily used by automatic reverb-type checker, yet i think these will be removed soon. Removing these effects didn't do much.

I will add images of audio buses just in case.

![image](https://github.com/godotengine/godot/assets/37717199/6fa1620c-9585-4e23-a547-39e97c8e4472)
![image](https://github.com/godotengine/godot/assets/37717199/446f8d8c-2724-4586-b1be-95deb3c59e8b)

I really need to clean it up. I didn't remove the buses themselves yet though, i wonder if that may effect the performance, yet i didn't check it yet.

> do you use Area3D with reverb?

Nope. I'm not using any "Area" nodes for audio. The only use-case of "Area" node in this game is "PlayerControllerWater" node, which is simulating water source. I'm using "Area" node in there to lower gravity to make props swim up. But i have to note: I have reverb/delay effect on audio bus, and i can change their parameters depending on current "soundscape", which is set by node that is checking a radius with additional ray-cast.

> use files other than WAV, try e.g. ogg vorbis and mp3

Hmm... I'm currently using .mp3 for almost all audio in this game, but for looped audio i've used .WAV, in this level i have looped music. It used 4 tracks (4 AudioStreamPlayer nodes as following) in total. All of the used music being preloaded when the location is loaded. 

I turned them to .ogg format. I played the level in 3.5.2.stable, didn't notice any significant performance changes. 

Playing the game with 3.5.2.stable built-in profiler gives that info:
![image](https://github.com/godotengine/godot/assets/37717199/f85acf45-ec31-4e6d-a919-3eab635de10c)

So, knowing that i have A MESS in audio buses, i will clean it up to see if it affecting the performance, there is a lot of outdated things that will not be used.

![image](https://github.com/godotengine/godot/assets/37717199/47d5dadc-a28f-4451-9eae-3679ef2e98a0)

So, after that, i checked m_day1_1 once again, that didn't do any performance impact as well. Here is profiler, as it follows:
![image](https://github.com/godotengine/godot/assets/37717199/ba2cee11-2bcb-44e9-83b7-dff466ab20c2)

~~I'm cursed!~~
But i still have one more thought to check. "Sound" auto-load class is helping me to handle sound in this game, it can change the volume of buses and so on. I'll check if disabling all logic in this class will help me.

So, i disabled all logic. Gotta say this is the only class in this project that works directly with "AudioServer" methods. And... Sadly that didn't do much, too. 
![image](https://github.com/godotengine/godot/assets/37717199/fe1f4a84-6648-4156-a143-b3c0d8339fff)

Jokes on you i seriously start to think that m_day1_1 is just cursed.

Anyway, i'm out of thoughts for now. I will post updated info of earlier console command since the audio buses were changed:
```
:: Audio Bus Info ::
bus_count :: 6
:: Bus info, index: 0
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 1
Bypass effects: False
Amount of effects: 4
:: Bus info, index: 2
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 3
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 4
Bypass effects: False
Amount of effects: 0
:: Bus info, index: 5
Bypass effects: False
Amount of effects: 0
```

**Comment by MJacred** [comment]
How many audio stream players are you spawning at any point and in what intervals (especially looking at sound effects)?

Could you try with latest build from 3.x branch, please? There was [this PR](https://github.com/godotengine/godot/pull/63430) which improved the AudioServer performance.

After that, please show your profiling again.
Plus the [C++ profiler](https://docs.godotengine.org/en/latest/development/cpp/using_cpp_profilers.html).

**Comment by MJacred** [comment]
> sounds are being instanced over and over again

Thought that is happening. Yes, caching your frequently sounds would be good.

> Also wanted to notice a fact that mentioned PR is already a part of 3.5.2. since it was merged at 2022, way before release of 3.5.2.

Afraid not, please see Godot 3.5.2: https://github.com/godotengine/godot/blob/3.5.2-stable/servers/audio_server.cpp#L263
That commit has not been cherry-picked.

> Definitely will do that after fixing the issue with constant Sound instancing of sounds

:+1:

After implementing your cache, you can further optimize by giving your sfx priorities, sort them accordingly and play a maximum of x (4-7) sfx at the same time. And looking at your log, you spawn the same sfx at the exact same second. That should be prevented. And if you use that to fake polyphony, you might want to wait for 1 second or so (depending on the type of sfx).

---

And: The code has been changed to suit more modern hardware that has multiple cores. Your system has only 2 Threads, so that in itself causes a penalty.

**Comment by MJacred** [comment]
@Dadaskis did you succeed in resolving the performance issue from your end?

**Comment by MJacred** [comment]
That's nothing to feel sorry about. Glad to be of help!

I'm looking forward to hearing what you'll do!

**Comment by Dadaskis** [comment]
So, i guess it's the end of this issue. What's the conclusion? My own blind stupidity is the cause of all problems once again! And even if it may sound negative, it doesn't sound like that for me for one simple reason: If that'd be actually a problem of this engine, that'd take much, much longer time to fix. Luckily, it is my fault, and i love it.

@Calinou thank you for starting activity on this issue with meaningful suggestions. Man, i see you everywhere, i think you are the most active community member right now

@MJacred once again, thank you for opening my eyes and providing a lot of information to process. You proved me that i cannot trust myself. Not sure if it's good, or bad, but it is a fact and it is good to recheck even existing info. It is nice to be paranoid.


Now, i want to tell, what exactly went wrong in my case.

This game is using code for a lot of various things. Even player controller node hierarchy for the most part is controlled by code. I love it simply because it has high extensibility, i've written like ~40.000 lines on GDScript and i never had to complain about how hard it is to add new things. Like, if i want to play a sound, i won't have to make a node in editor UI, i just write 5 lines to make it play. What is bad in case? It is making development more blind. So blind, i managed to miss how much new instances of sounds i made.

This project is featuring a lot of shooting. There is a sound of the NPC that is shooting a firearm. There is a sound of the bullet hitting the surface. There is a sound of suppression that player has if bullet is flying-by. If player is shooting, there is also a sound of falling casings. And etc.

I'll try to explain, what actually have used sounds that much.

- Soundscapes

They used random (one-shot) sounds and looped sounds. In case of m_day1_1, there are random sounds such as mega-mall alarm, military radio in distance, distant shooting. And also looped sounds of interior and outside police sirens. The main problem with these is my earlier usage of .wav format for looped sound. Somewhat, it was a discovery for me that .ogg can have seamless looped sound without that much performance impact (with a good compression too!), and i can't believe i missed it too. I think i got too used to work with .wav in Source that i started to miss other, modern opportunities.

What fixes in this case? Not much. Basically i re-exported all .wav to .ogg in FL Studio, now it works as it should.


- NPC (Human Model)

NPCs can shoot. NPCs can walk. And all of these things can have sounds. Should i say that instancing of each of them is one of the main points that harmed the performance? On top of that, i've used .wav for these, meaning completely screwed up optimization of run-time and game file-size.

Fixes?

Shooting: These sounds are not being instance each time anymore. Instead, it has a fixed array of sound nodes to play. In this case, you can find a good balance between having a nice sound on automatic firearms and overall performance. This helped very much.

Walking: Sadly, footsteps is quite complicated thing in this game, because sound depends on type of surface someone is walking (including player), so pre-instancing all sounds as nodes for all NPCs and player is overkill, this is going to be more than 2000 nodes for sure. Instead, now it is not playing sounds if nobody is near-by. I did quite an aggressive radius cut-down, yet on battlefield it is not really noticeable, as well as in overall game. I did this optimization long, long ago, yet it is still worthy to mention.


- Player

Player does have a lot of various things to mention, including "Viewmodels", but since i've got a good performance boost, i decided to leave these untouched. For many reasons, really.


- Audio Buses Layout

I missed this one. I had a lot of various buses used. You should not use them too much. Any DAW uses more CPU/RAM resources for these, Godot will do that too. Lowering amount of effects is a good thing too.


- Music

This one has a weird issue. In this project, music can be "stopped slowly", meaning the sound slowly decreasing the volume until it is fading away. It is useful for music blending, when you need to blend between different stages. What kind of problem i had? You can't hear music, but it is playing, and, of course, i ended up with like 4 .wav-s playing in background. What i did? Stopped the audio player if it is below certain volume... as well as re-exporting .wav as .ogg.


Conclusion

From crazy 40-60 ms it went down to acceptable 6-12 ms. There is still a room for optimization, there is always one. Will i continue? Honestly, knowing that my hardware is a hot garbage, nope i won't. By the way, fixing this exposed me critical issues with visibility checks of NPCs, when it is using way too much CPU.

And at this point, i have to answer one last potential question. How to see? How to start to see what is going wrong? How to see what kind of sounds you have? Time to code. I will try to transform the code i've used to be useful in any kind of project.

```
extends Spatial

func find_by_class(node: Node, node_class_name : String, result : Array) -> void:
	if not node:
		return
	if node.get_class() == node_class_name:
		result.push_back(node)
	for child_index in node.get_child_count():
		var child = node.get_child(child_index)
		find_by_class(child, node_class_name, result)

func find_nodes_by_class(node_class: String) -> Array:
	var result = []
	find_by_class(self, node_class, result)
	return result

func count_children(node, count = 0, types = {}):
	if not is_instance_valid(node):
		return count
	count += 1
	if types.get(node.get_class()) == null:
		types[node.get_class()] = 0
	if types.get("Sound Nodes") == null:
		types["Sound Nodes"] = 0
	if types.get("Sound Playing") == null:
		types["Sound Playing"] = 0
	types[node.get_class()] += 1
	if node.get_script() != null:
		var script: = node.get_script() as Script
		if "st_" in script.resource_path:
			types["STs amount"] += 1
	if node is AudioStreamPlayer3D:
		types["Sound Nodes"] += 1
		if node.playing:
			types["Sound Playing"] += 1
	if node is AudioStreamPlayer:
		types["Sound Nodes"] += 1
		if node.playing:
			types["Sound Playing"] += 1
	for child in node.get_children():
		var data = count_children(child, count, types)
		count = data[0]
		types = data[1]
	return [count, types]

func fill_print_order(path_map):
	var print_order = []
	for key in path_map.keys():
		var amount = path_map[key]
		var print_str = key + " :: " + str(path_map[key])
		print_order.append([amount, print_str])
	return print_order

func sort_print_order(print_order):
	for index0 in range(len(print_order)):
		for index1 in range(len(print_order)):
			var data0 = print_order[index0]
			var data1 = print_order[index1]
			var count0 = data0[0]
			var count1 = data1[0]
			if count0 > count1:
				print_order[index0] = data1
				print_order[index1] = data0

func debug_nodes_amount():
	var data = count_children(self)
	var count = data[0]
	var types = data[1]
	print("Nodes amount: " + str(count))
	var types_sort = []
	for key in types.keys():
		types_sort.append(key)
	for index0 in range(len(types_sort)):
		for index1 in range(len(types_sort)):
			var type0 = types_sort[index0]
			var type1 = types_sort[index1]
			var count0 = types[type0]
			var count1 = types[type1]
			if count0 > count1:
				types_sort[index0] = type1
				types_sort[index1] = type0
	for type in types_sort:
		var type_count = types[type]
		print(type + " :: " + str(type_count))
	print("---------")
	
	var audio_nodes = []
	audio_nodes.append_array(
		find_nodes_by_class("AudioStreamPlayer3D")
	)
	audio_nodes.append_array(
		find_nodes_by_class("AudioStreamPlayer")
	)
	var sample_path_map = {}
	var play_path_map = {}
	for node in audio_nodes:
		var stream = node.stream
		if stream == null:
			continue
		var path = stream.resource_path as String
		var use_count = sample_path_map.get(path, 0)
		use_count += 1
		sample_path_map[path] = use_count
		if node.playing:
			var play_count = play_path_map.get(path, 0)
			play_count += 1
			play_path_map[path] = play_count
	
	print(":: Audio Samples Used")
	var print_order = fill_print_order(sample_path_map)
	sort_print_order(print_order)
	for print_data in print_order:
		print(print_data[1])
	
	print("---------")
	print(":: Audio Samples Playing")
	print_order = fill_print_order(play_path_map)
	sort_print_order(print_order)
	for print_data in print_order:
		print(print_data[1])
	
	print("---------")
	print("Sound Nodes" + " :: " + str(types["Sound Nodes"]))
	print("Sound Playing" + " :: " + str(types["Sound Playing"]))

func _ready() -> void:
	for frame in range(3):
		yield(VisualServer, "frame_post_draw")
	debug_nodes_amount()
```

[child_check_demo.zip](https://github.com/godotengine/godot/files/12642092/child_check_demo.zip)

So, this code is more of an example of what i made for myself (in my case it is console command). Yet i hope others will find it useful to transform for their own needs, because it helps in analysis of used sounds, of playing sounds, and also gives more info about ALL node types, which can be incredibly useful to find bottlenecks.

Thanks everyone, closing the issue.

**Comment by MJacred** [comment]
Sorry for the delay.

There's no need to become paranoid. You already got the most important skill down: finding the problem area.

Now you need to collect some experience to understand what "expensive operations" are. (Now follows some stuff that you might or might not know, but I hope you find it useful) They fall in one of these categories "a lot of calculations in a short amount of time", "complex calculations" or "resource intensive operation". Loading a lot of files is pretty resource intensive. This was probably well hidden behind your autoload system. Most convenience systems pack a performance penalty.  
Many devs become infected with the "optimize everything from the start" disease. But if you lack the experience to tell whether some system/operation is expensive or not, it's ok to do the simple (and more expensive) implementation first and then optimize once you determined the performance cost of the simple system/operation is too high.  
Of course, once you know by experience (or your picked up the knowledge from somewhere) that a simple implementation has a too high of a performance cost, you can optimize the system right from the start. Unless you're prototyping, then it's ok as long as it runs good enough.

**Comment by Dadaskis** [comment]
@MJacred

> Sorry for the delay.

Glad to see you again!

> There's no need to become paranoid.

I love to be paranoid, but sometimes not of course

> This was probably well hidden behind your autoload system.

Oh, well, the main issue was related to actual creation of new nodes, which will be removed once the audio sample finished playing. However, i remember getting this issue earlier, and, yea, now `preload` (or similar, like loading all needed sounds at initializing) is used for many areas. `Sound` singleton is designed to not load anything, but to use the loaded sample

> Most convenience systems pack a performance penalty.

Sadly :(

> Many devs become infected with the "optimize everything from the start" disease.

"Premature optimization is the root of all evil"
I can't even tell how many times i've heard this during "competitive programming" events, and it is true simply because optimization from the start limits the vision of how to create a certain system if you never worked with it before (which is true for many cases i had to work with anyway). That doesn't mean i'm saying you can't optimize from the start, you pretty much can do that if you have experience with it for sure

> ... it's ok to do the simple (and more expensive) implementation first and then optimize once you determined the performance cost of the simple system/operation is too high.

Honestly, that's why i love making this project. When i started, i couldn't even realize how many possibilities out there to optimize the game. Like, especially the case of human models, when `AnimationTree` was replaced with 2 `AnimationPlayer` nodes, resulting in major performance improvement. Or simple 5 lines of code to remove `CollisionShape` while keeping the collisions (removed ~2000 nodes at m_day1_1 as result). And i hope to keep up making more of such discoveries!
