### ISSUE TITLE
Using SubViewport with own_world_3d = true causes memory leak.

### ISSUE THREAD

**Issue by MizunagiKB** [godotengine/godot#81476]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.5.2 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

Memory allocated when using SubViewport with own_world_3d = true is not released when own_world_3d = false or queue_free.

The set_use_own_world_3d function is called when own_world_3d is changed.
When true is given, it seems that own_world_3d is created, but the opportunity to destroy it is not given.

### Steps to reproduce

This bug can be reproduced with the following code.

```gdscript
func _process(delta):

    var v = SubViewport.new()

    for n in range(128):
        v.own_world_3d = true
        v.own_world_3d = false

    v.queue_free()
```

![ss_capture](https://github.com/godotengine/godot/assets/5047878/253f059e-8c43-4ad2-99e5-a70b9fe683a5)

### Minimal reproduction project

[viewport_memory_leak.zip](https://github.com/godotengine/godot/files/12564712/viewport_memory_leak.zip)

**Comment by TokageItLab** [comment]
I investigated this a bit and it seems that the memory freeing by `unref()` for `World3D` is not working properly in the first place.
