### ISSUE TITLE
Shadow quality depends on screen resolution when camera is orthographic

### ISSUE THREAD

**Issue by OwenMcNaughton** [godotengine/godot#81482]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.2802) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

https://github.com/godotengine/godot/assets/6430599/987e4c17-7502-4cf6-94bd-cbe58f42cdf6

When you change resolution, the quality of shadows changes.  Using the Orthogonal directional shadow mode.

I would expect that the shadow quality is independent of window size.

### Steps to reproduce

Run the sample project and resize the window.

### Minimal reproduction project

[ortho_shadow_bug.zip](https://github.com/godotengine/godot/files/12565423/ortho_shadow_bug.zip)

**Comment by bitsawer** [comment]
That's just mesh level-of-detail (LOD) changing based on how much the mesh takes space on the screen/shadow map and is normal and also affects the shadow. You can either disable automatic LOD generation on reimport, tweaks the LOD bias or manually create better LOD meshes. Closing as not bug, although there are some open issues related to automatic LOD generation quality etc.
