### ISSUE TITLE
Some editor icons are broken in the ui (master branch)

### ISSUE THREAD

**Issue by bitsawer** [godotengine/godot#81492]
### Godot version

Godot v4.2.dev (fc99492d3)

### System information

Godot v4.2.dev (fc99492d3) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

Some editor icons are broken and show a red placeholder icon in current master at fc99492d3. Looks like a recent regression, 4.2 dev4 shows these icons correctly.

### Steps to reproduce

Icons that I have noticed that are affected, there can be more:

* Path3D gizmo handle icons
* MeshInstance3D toolbar button icon
* VoxelGI toolbar button icon
* LightmapGI toolbar button icon

![icons](https://github.com/godotengine/godot/assets/22456603/7c083bbe-a6d1-4461-8e21-44865c7338f6)

![mesh](https://github.com/godotengine/godot/assets/22456603/8f1eb07b-d527-44de-b5b7-6799bccbd80a)

### Minimal reproduction project

Not needed.

**Comment by scgm0** [comment]
c# build icon
![图片](https://github.com/godotengine/godot/assets/52148221/2ecae544-c145-4e6b-acfd-05f102b6badd)

**Comment by AThousandShips** [comment]
Looks like a possible regression from:
* https://github.com/godotengine/godot/pull/80573

**Comment by Calinou** [comment]
Can we make it so requesting an unknown icon in the editor always prints an error at least once? This would make it easier to track down those issues in the future.
