### ISSUE TITLE
Vector2I is parsed as a string in Mono.

### ISSUE THREAD

**Issue by wadlo** [godotengine/godot#81502]
### Godot version

4.2

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

Json.ParseString of Vector2I is type `string`, not `Vector2I`.

### Steps to reproduce

Run the following code: 

`GD.Print(Json.ParseString(Json.Stringify(new Vector2I(10, 10))).VariantType);`

It will print `string`. It is expected to parse into the `Vector2I` variant type.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
JSON does not have native vector types. It only has boolean, integer, *number* (always float), array and object types.

**Comment by wadlo** [comment]
That makes sense. Maybe it's just the docs misleading me then. 

From the docs: "The JSON enables all data types to be converted to and from a JSON string."

**Comment by wadlo** [comment]
Actually, before I close this, why couldn't/shouldn't Godot have a built in function that serializes Godot Vectors into a parseable format?

**Comment by bitsawer** [comment]
There are several, for example [var_to_str()](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-var-to-str) and [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html). You can also create your own [Resource](https://docs.godotengine.org/en/latest/classes/class_resource.html) with any needed properties and serialize that.
