### ISSUE TITLE
scroll_started and scroll_ended signals don't get emitted for ScrollContainer on Windows but they do work on Android

### ISSUE THREAD

**Issue by enrikqose** [godotengine/godot#81512]
### Godot version

4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 27.21.14.6660) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

scroll_started and scroll_ended signals don't get emitted for ScrollContainer on Windows (haven't tested on linux or mac), but they do work on Android (haven't tested on iOS)

### Steps to reproduce

You can connect scroll_started or scroll_ended signal of a ScrollContainer control to a function and you will notice that the callback is never called on windows, but when tested on android it works.

### Minimal reproduction project

[scroll_event_issue.zip](https://github.com/godotengine/godot/files/12568250/scroll_event_issue.zip)

**Comment by AThousandShips** [comment]
What ways are you scrolling? With the scroll wheel? Dragging with the mouse?

**Comment by enrikqose** [comment]
Tried scrolling with the scroll wheel, dragging the scrollbar with the mouse and also using the scrolling gesture (Two finger scroll) on the touchpad.

**Comment by AThousandShips** [comment]
It only supports touch, as in screen touch, unsure if this is an oversight or by design though, if the latter it should be documented

**Comment by Calinou** [comment]
You need to enable **Emulate Touch From Mouse** in the Project Settings for these signals to be emitted. These signals are only emitted for drag-based scrolling.

**Comment by AThousandShips** [comment]
Note that this signal was originally added to solve a bug where buttons could be pressed while scrolling, so I'm unsure what use the signal has elsewhere
