### ISSUE TITLE
Switching scene tabs with many tabs may hide tabs

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#81513]
### Godot version

4.2 dev4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you have many tabs opened and they are overflowing with the < > buttons, when you switch scene tab it may hide some tabs in specific circumstances:

https://github.com/godotengine/godot/assets/2223172/e5904497-6e3f-48af-815a-3a156ca15018

I'd expect that simply switching to another tab has no effect on visibility.

### Steps to reproduce

1. Open many scene tabs
2. Repeat what I did on the video
May depend on tab names and window size.

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
I digged into the code a little bit, it seems everytime we click a scene, godot will clear all the scene tabs with `clear_tabs` and recreate them one by one, then call `scene_tabs->set_current_tab` to set the clicked scene as current tab. 

So it seems like scene tab did not remember the state it last called ? `clear_tabs` effects `offset` and make it 0. 

I think maybe we can make a special case for this and don't recreate everything when user is just switching scene tabs.

**Comment by YuriSizov** [comment]
> I think maybe we can make a special case for this and don't recreate everything when user is just switching scene tabs.

Well, there is an old code comment in there that highlights that the current approach is awful and we ought to fix it. So no need to special case it, it should be a straight fix 🙂

**Comment by jsjtxietian** [comment]
Aha I saw that comment, but changing the current approach will definitely need more test, I can give it a try :)
