### ISSUE TITLE
Directories cannot be entered by selecting items from a FileDialog on Android

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#8151]
**Operating system or device - Godot version:**
OS: Android 7.1.1 / LineageOS 14.1
Godot: Godot 2.1.2

**Issue description:**

There is no way for me to choose a folder from the directory listing and make it the current directory. If I want to change the current directory I need to enter the directory name in the top bar.

**Steps to reproduce:**
1) Make a new project with just one scene that is a FileDialog, set to filesystem access and MODE_OPEN_FILE.
2) Go to the export menu for Android and make sure to enable the "Read External Storage" permission.
3) Deploy the project to an Android device.
4) Make sure the app has been given its permissions.
5) Open the app.
6) If the currently displayed directory is empty or only contains the parent directory link, use the top bar to navigate to "/sdcard" for on-device storage.
7) Try to change the current directory to one of the listed directories by choosing it from the menu. I have tried tapping, double tapping, and hitting "Open" after tapping a directory. None of these have changed the current directory.

**Link to minimal example project:**

[filetest.zip](https://github.com/godotengine/godot/files/870390/filetest.zip) (ZIP-exported Godot project)
[filetest-apk.zip](https://github.com/godotengine/godot/files/870391/filetest-apk.zip) (Contains an exported APK)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by raymoo** [comment]
Seems to be reproducible on master: #18477

**Comment by raymoo** [comment]
I could see a few potential fixes:
* Allow touches to somehow enter directories in FileDialog
* Add a new class similar to FileDialog that is particularly suited to mobile devices (larger menu items and buttons, drag to scroll, etc.)
* Use the system file selector (I think there was an issue for this but I can't find it now)

**Comment by PonySchreck** [comment]
i have the same problem

OS: Android 7.0, Samsung Galaxy S6 Edge
Godot: 3.1.1

**Comment by ca3games** [comment]
Can confirm still exist.
Huawey Y5
Godot 3.1.1

**Comment by ffreling** [comment]
I still have this issue with the latest Godot versions: 3.2.1.stable.flatpak and 3.2.2.rc1.official

I made a sample app to exhibit the issue: http://code.ffreling.com/fabs/godot-sample-android-filedialog

My phone is a Pixel 3a with Android 10.

@akien-mga  would it be possible to reopen the issue?

**Comment by ondesic** [comment]
Just ran into this problem.  On android I can select a file, but no matter what I do, If I select a folder, it will not do anything.  It will not enter the folder to select the files inside. I am using 3.2.1.

**Comment by ondesic** [comment]
It seems on Android it is not recognizing a double tap on a folder.

**Comment by blurrred** [comment]
I have also just encountered this issue on 3.3.2.
It would be preferable to just be able to open Android's native file picker.

**Comment by ondesic** [comment]
Was this closed because it was fixed or has this issue been merged?  On the android device, I still cannot select and open a folder in the FileDialog node with 3.5.2 rc2.
