### ISSUE TITLE
Godot 4.2 Dev 4 breaks colour  ramp for GPU particles

### ISSUE THREAD

**Issue by mk56-spn** [godotengine/godot#81528]
### Godot version

4.1.1.stable.mono, 4.2dev3, 4.2dev4

### System information

Fedora Linux 38 (Workstation Edition)

### Issue description

Self explanatory title. GPUparticles shaders do not correctly apply their colour ramp or initlal colour ramp to the particles.

Stable 4.1.1
![Screenshot from 2023-09-11 01-11-24](https://github.com/godotengine/godot/assets/74463310/2a5f083a-8ab6-466c-adab-5a33c7aa52d8)

Dev3
![Screenshot from 2023-09-11 01-11-44](https://github.com/godotengine/godot/assets/74463310/8c2493eb-75cb-42ca-bf17-1c08f42244c8)

Dev4
![Screenshot from 2023-09-11 01-11-32](https://github.com/godotengine/godot/assets/74463310/36d0de1d-0ac8-458c-afc7-c9c4acc70e77)

The right side is a CPUParticle and is just there for comparison

### Steps to reproduce

Add a GPUParticles node with a default material, and adjust colour ramp to see the effect ( or lack thereof )

### Minimal reproduction project

Not necessary.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/81166, which was fixed by https://github.com/godotengine/godot/pull/81198 and will be in 4.2.dev5.
