### ISSUE TITLE
PopupMenu mouse wheel scrolling is broken in 3.6.beta

### ISSUE THREAD

**Issue by bloodmage18** [godotengine/godot#81522]
### Godot version

v3.6.beta2.official [68c507f59]

### System information

 Windows 10 Pro - nvidia NVS400M - core i5 2400 - 

### Issue description

the scrolling feature on the animation player : unable to scroll through [ list of animations ] .
this issue is the same when loading a resource in the script i am unable to scroll through the Resource list

### Steps to reproduce

steps:
try to load a resource
export (Resource) onready var scroll = get_node(scroll)

v3.6.beta2.official [68c507f59]

https://github.com/godotengine/godot/assets/93401685/e8f0c00f-c1ff-4cd1-9161-2d07bd051707

v3.4.4.stable.official [419e713a2] - v3.5.2.stable.official [170ba337a] works

https://github.com/godotengine/godot/assets/93401685/72325298-6d1b-4f46-ac38-8132c88a0cd4

### Minimal reproduction project

"N/A"

**Comment by Calinou** [comment]
Can you reproduce this on [3.6.beta1](https://downloads.tuxfamily.org/godotengine/3.6/beta1/)?

**Comment by timothyqiu** [comment]
This has been fixed by #77691 (fixed in 3.6.beta3).

**Comment by Calinou** [comment]
Closing per the above comment.

**Comment by bloodmage18** [comment]
thank you
