### ISSUE TITLE
Subviewport Pixel Snapping Issues

### ISSUE THREAD

**Issue by SoldierCantKill** [godotengine/godot#81524]
### Godot version

4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10 - Godot 4.1.1.stable.official

### Issue description

https://github.com/godotengine/godot/assets/75461200/04ec7c51-96e2-46af-a126-103867bd973a

I don't understand the EXACT problem, but it looks like the pixels in the subviewport are less smooth than when without using the viewport.

### Steps to reproduce

Create a Subviewport
Check canvas_item_default_texture_filter to Nearest.
Modify the Vertex of a sprite (via shader)

### Minimal reproduction project

[viewport_bug.zip](https://github.com/godotengine/godot/files/12570066/viewport_bug.zip)

**Comment by Calinou** [comment]
This is because of uneven pixel scaling. Your viewport zoom in the 2D editor is 211.9%, which is *not* an integer value. Use <kbd>Alt + Mouse wheel</kbd> to constrain zoom in the 2D editor to integer values (such as 100%, 200%, …).

**Comment by SoldierCantKill** [comment]
In a game where the subviewport is 640x480 and the game is 640x480, the pixel scaling is still extremely noticable.

**Comment by Calinou** [comment]
> In a game where the subviewport is 640x480 and the game is 640x480, the pixel scaling is still extremely noticable.

Remember that pixel snap project settings don't translate to subviewports. You need to enable them explicitly on the subviewport, regardless of whether you've changed project settings.

**Comment by SoldierCantKill** [comment]
Yes, check the example project, doesn't look as intended in editor or in game. Everything is default settings for the project except for canvas_item_default_texture_filter. Which I have also changed on the subviewport. This looks like a bug.

**Comment by Calinou** [comment]
Remember that 4.2 has built-in support for integer scaling. You can test this in [4.2.dev4](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/) :slightly_smiling_face:
