### ISSUE TITLE
CollisionShapes cannot be rotated

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8153]
Tested on Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits

Create a KinematicBody, then a CollisionShape with a CapsuleShape. Rotating the CollisionShape seems to have no effect. Rotating the body doesn't either. It is working in 2.1.2.
If you select another node then the CollisionShape again, the visual updates and shows the rotated shape.
However, that's not only a visual issue: I just tested a character controller and I get stuck earlier in one direction rather than another, suggesting that my capsule is still badly oriented.

A workaround is to rotate the shapes with a script instead:
```gdscript
	set_shape_transform(0, Transform().rotated(Vector3(1,0,0), PI/2.0))
```

**Comment by novemberist** [comment]
Not only rotating but also moving collision shapes using the gizmo currently doesn't work. But I think 3d physics in general are a heavy WIP right now.

**Comment by Zylann** [comment]
I don't think Physics as touched since 2.x. It definitely needs improvements but it should be working already.

**Comment by kubecz3k** [comment]
I think this should be fixed now. Can you recheck?

**Comment by reduz** [comment]
this is fixed now, as old code is gone
