### ISSUE TITLE
[3.0] Texture .flags file is still present

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8154]
Tested on Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits

When I created a new 3.0 project, I noticed the default icon.png came with an icon.png.import file, but also an icon.png.flags file. These should have been superseded by .import files.

**Comment by kubecz3k** [comment]
As far as I tested this is no longer the case in 3.0.2
