### ISSUE TITLE
Using the class_name of a subclass results in spurious 'nonexistent function' errors at runtime

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#81548]
### Godot version

4.2-dev4

### System information

Godot v4.2.dev4 - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 530.41.03) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I tried updating a project from Godot 4.1 to 4.2 using the dev snapshot and encountered this issue.

One of my editor plugins has a class called 'Table', that both preloads and uses the class_name of one of its subclasses (let's call it DerivedTable). This seems to trigger a bug in 4.2 that wasn't present in 4.1. At runtime, the engine reports an error that a static function doesn't exist, when it clearly does.

From the attached reproducer:

table.gd:

```GDScript
extends Resource
class_name Table

static func from_directory(path: String, extension := "tres"):
	return preload("derived_table.gd").some_method()

static func from_array(array: Array):
	var table := DerivedTable.new()
	table.set_data(array)
	return table
```

derived_table.gd:

```GDScript
extends Table
class_name DerivedTable

static func some_method():
	pass
```

Then when you call `Table.from_directory("")`, the engine reports:

```
SCRIPT ERROR: Invalid call. Nonexistent function 'from_directory' in base 'GDScript'.
```

### Steps to reproduce

1. Run the attached reproduction project.

### Minimal reproduction project

[Reproducer](https://github.com/godotengine/godot/files/12578722/4.2-static-methods.zip)

**Comment by dalexeev** [comment]
[7d29ac0bf271cf1c730465bbd76c05ecf8e1c6a0] GDScript: solve `_populate_class_members()` cyclic dependency problem

Regression from #79205. CC @anvilfolk

**Comment by anvilfolk** [comment]
Thank you for the heads up, @dalexeev, and @tcoxon MRP! Will take a look when I have some time!

Now that cyclic dependency bugs in compilation steps are fixed, it seems like a lot of things were relying on the previous solution :)
