### ISSUE TITLE
Vulkan: LightmapGI with Directional enabled exhibits negative-colored specular reflections on metallic materials

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#81556]
- *Related to https://github.com/godotengine/godot/issues/64645.*

### Godot version

4.2.dev 221884e6b

### System information

Godot v4.2.dev (221884e6b) - Fedora Linux 38 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.104.05) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

LightmapGI with **Directional** enabled exhibits negative-colored specular reflections on metallic materials:

![Screenshot_20230911_233509](https://github.com/godotengine/godot/assets/180032/15ab3ef8-f6d0-4961-b583-df4548942ff1)

![Screenshot_20230911_233555](https://github.com/godotengine/godot/assets/180032/67c0a389-af8c-428d-90f8-d8d84752414b)

This doesn't occur at low metallic values, even if roughness is kept to `0.0`:

![Screenshot_20230911_233527](https://github.com/godotengine/godot/assets/180032/5ab9c59e-5d71-45fd-9adc-24ebefa2ede3)

Disabling environment baking in LightmapGI doesn't resolve the issue.

### Steps to reproduce

- Create a MeshInstance3D with a metallic smooth material, and another one with a rough emissive material (or a bright material that reflects light).
- Enable **Directional** in LightmapGI. Bake lightmaps.
- Notice how reflections will take the opposite color of the light reflected by the other node.

### Minimal reproduction project

[test_lightmap_directional_metallic.zip](https://github.com/godotengine/godot/files/12580589/test_lightmap_directional_metallic.zip)

**Comment by clayjohn** [comment]
This comes from our fake code to add a little bit of specular from the lightmaps. The code produces invalid values when used with a directional light. I would just remove it entirely
