### ISSUE TITLE
Animation tools do not get hidden correctly when switching scenes

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#81558]
### Godot version

v4.2.dev (221884e6b)

### System information

Godot v4.2.dev (221884e6b) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

When you are switching between open scenes the animation toolbar above the viewport can appear out of context. One example is having an animation player in a 3D scene (there is no animation toolbar in the 3D viewport), then switching to a 2D scene. The toolbar would be visible and the bottom panel would be expanded, despite no animation player or active animation being present in the second scene. Toggling the bottom panel fixes the state.

### Steps to reproduce

https://github.com/godotengine/godot/assets/11782833/f60cef64-1abc-4908-91ef-a8d12204383c

### Minimal reproduction project

N/a

**Comment by jsjtxietian** [comment]
Do we need to keep the bottom panel open when switching to a scene without animation player? The toolbar above the viewport is definitely a bug and I can help fix it.
