### ISSUE TITLE
Texture color is randomly becoming brighter or darker, or different

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8155]
Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits, nVidia GeForce 940M

When upgrading a project, I found that textured meshes were randomly getting different colors than expected. Most of the time, they become brighter, either in the game, or in the editor. Sometimes they become darker but I've seen that only in the inspector yet. The texture is uncompressed and has no flags checked.

Toggling lights or changing nodes order had one-time effects on this, but it's still pretty random so I don't know how, when or why this happens.

![image](https://cloud.githubusercontent.com/assets/1311555/24328407/5d256e8a-11e9-11e7-85c7-78dddd6046ce.png)
![image](https://cloud.githubusercontent.com/assets/1311555/24328413/6f7b6dbe-11e9-11e7-8718-300d9f3e520b.png)

I've also found that if I remove all lights and WorldEnvironment, I get a blue color:
![image](https://cloud.githubusercontent.com/assets/1311555/24328430/b5dc5516-11e9-11e7-931a-9a1aadfc07dd.png)

The texture:
![terrain](https://cloud.githubusercontent.com/assets/1311555/24328433/d604f316-11e9-11e7-9360-ba1b609f41e9.png)

Project of the second screenshot:
[TextureColorBug.zip](https://github.com/godotengine/godot/files/870557/TextureColorBug.zip)

**Comment by volzhs** [comment]
did you turn off default light? Viewport > View > Use default light

**Comment by nunodonato** [comment]
I think this might be the same I get here https://www.youtube.com/watch?v=7qVzHHmAkYM

both the grass and rocks kind of flash between normal and lighter versions, randomly

**Comment by Zylann** [comment]
@volzhs I always turn the default light off. And even when it's on, it doesn't produce a difference that big. It'slike the brightness itself is doubled.
Also I did expect that no WorldEnvironment would make stuff have a default lighting, however I didn't expect it  to be blue (wasn't the case in 2.x).

**Comment by Zylann** [comment]
The same thing is happening again in 3.0.2, just as I started writing a GUI for my terrain plugin.
Everytime I want to draw a preview of the texture, it shows darker in the UI.

Then, in some of the dialogs I created, as soon as I switch one of the textures, it becomes brighter both in UI and 3D viewport.

This is extremely annoying, as if the editor intrusively modifies the texture just because I happen to draw it "not in 3D"...

**Comment by akien-mga** [comment]
May be related to #17574.

**Comment by reduz** [comment]
The original issue is gone with the old renderer.
The new one can't be fixed until porting to Vulkan happens, so kicking

**Comment by akien-mga** [comment]
Closing as the original issue is fixed. If there is a follow-up bug, it would be best reported in a new issue against the current master branch.
