### ISSUE TITLE
Area2D instancing causes unexpected effects on RigidBody2D

### ISSUE THREAD

**Issue by joshpk105** [godotengine/godot#81550]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3667) - 12th Gen Intel(R) Core(TM) i9-12900KF (24 Threads)

### Issue description

If I instance an Area2D scene with gravity effects into another scene overlapping a RigidBody2D, it will move the RigidBody2D as expected. However, if I remove that instance, then spawn a new Area2D instance in a different location not overlapping the RigidBody2D. The RigidBody2D will still behave as if it was overlapping. 

### Steps to reproduce

1. Startup the reproduction project with Godot 4.1.1
2. Play the area_2d_bug_demo scene
3. The scene will wait 4 seconds then spawn an Area2D on the right, not affecting the RigidBody2D ball
4. Then it will despawn on the right
5. Then on the left the Area2D will spawn and effect the RigidBody2D ball as expected
6. This spawn/despawn cycle will continue indefinitely and eventually(doesn't seem to always happen immediately) the RigidBody2D ball will be moved by Area2Ds that spawn on either side.

### Minimal reproduction project

[Area2DBugGodot4.1.1.zip](https://github.com/godotengine/godot/files/12579308/Area2DBugGodot4.1.1.zip)
https://github.com/joshpk105/Area2DBugGodot4.1.1

**Comment by voidiii** [comment]
Based on what I see, the bug is somewhere located in `GodotAreaPair2D::pre_solve` and the `area` member in `GodotBody2D`. I think it is not removing the `area` properly, the size of `Vector<AreaCMP> areas;` keeps increasing and at some point, there is an `AreaCMP` with `Refcount` of 2 shows up and I believe that the reason of this bug. 

Although I might be wrong, I am still very new to Godot and I havent found the fix to this bug yet.

**Comment by voidiii** [comment]
The function `bool GodotAreaPair2D::setup(real_t p_step)` is being called multiple times for the same body and area which is causing `has_space_override` to be false while it is supposed to be true thus disable `GodotAreaPair2D::~GodotAreaPair2D()` to remove the area correctly. Idk why it is being called so many times and I am pretty sure it is irregular because none of other body in the scene is calling it so many times

**Comment by voidiii** [comment]
I made a minor change to `bool GodotAreaPair2D::setup(real_t p_step)`:
`bool GodotAreaPair2D::setup(real_t p_step) {
	bool result = false;
	if (area->collides_with(body) && GodotCollisionSolver2D::solve(body->get_shape(body_shape), body->get_transform() * body->get_shape_transform(body_shape), Vector2(), area->get_shape(area_shape), area->get_transform() * area->get_shape_transform(area_shape), Vector2(), nullptr, this)) {
		result = true;
	}

	if (result && colliding) {
		process_collision = false;
		return process_collision;
	}

	process_collision = false;
	has_space_override = false;
	if (result != colliding) {
		if ((int)area->get_param(PhysicsServer2D::AREA_PARAM_GRAVITY_OVERRIDE_MODE) != PhysicsServer2D::AREA_SPACE_OVERRIDE_DISABLED) {
			has_space_override = true;
		} else if ((int)area->get_param(PhysicsServer2D::AREA_PARAM_LINEAR_DAMP_OVERRIDE_MODE) != PhysicsServer2D::AREA_SPACE_OVERRIDE_DISABLED) {
			has_space_override = true;
		} else if ((int)area->get_param(PhysicsServer2D::AREA_PARAM_ANGULAR_DAMP_OVERRIDE_MODE) != PhysicsServer2D::AREA_SPACE_OVERRIDE_DISABLED) {
			has_space_override = true;
		}
		process_collision = has_space_override;

		if (area->has_monitor_callback()) {
			process_collision = true;
		}

		colliding = result;
	}

	return process_collision;
}`

and it seems to be solving this bug, the area list and ref count is behaving normally now but I am not sure if there will be any other bugs to appear

**Comment by voidiii** [comment]
@joshpk105 do u have a bigger project or scene that I can use to test? I have tested my solution with the scene you posted and it is working nicely but I wanna give it a bit more tests.

**Comment by joshpk105** [comment]
@voidiii sorry, I don't have anything I can post quickly. I'll put some more stuff into that repo that I think are related to the idea I had when I found this.

**Comment by joshpk105** [comment]
I added two more scenes to https://github.com/joshpk105/Area2DBugGodot4.1.1  that I thought would demonstrate the bug using another Area2D instead of a RigidBody2D. However. neither of them seem to, I'm not sure how much more help I can be since I don't seem to understand the underlying problem.

**Comment by voidiii** [comment]
thats ok, it is a small bug should be easy to fix~

**Comment by Occalepsus** [comment]
I fixed this issue for the 3D engine, this is the PR if you want to fix it for the 2D engine @voidiii : https://github.com/godotengine/godot/pull/82961
