### ISSUE TITLE
PNG files colors are incorrect when imported as Texture2D

### ISSUE THREAD

**Issue by czlowiekimadlo** [godotengine/godot#81567]
### Godot version

4.0.4.stable, 4.1.1.stable

### System information

Windows 10 - Godot v4.1.1.stable - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080, Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads), same on Godot v4.1.1.stable - macOS 13.5.2 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads), also same on Steam Deck.

### Issue description

When a PNG file is being imported as Texture2D to be used in a material, the colors are interpreted wrong, making the model look completely different than in the modelling tool. Importing the same PNG as an Image makes the colors correct, but I don't know what are the performance consequences of such action.

A screenshot from the minimal reproduction project shows Texture2D PNG on the left (incorrect) and Image PNG on the right (colors as expected).
<img width="1032" src="https://github.com/godotengine/godot/assets/649405/2d89fa9f-94ef-473f-9c76-8f74ebb1565b">
Note: the imported meshes have material override on them so that I can apply two different albedo textures in the same manner. Removing the override material on the left model will not make a difference in it's appearance.

### Steps to reproduce

- Create a model in MagicaVoxel
- Export model as OBJ
- Import model into a MeshInstance in Godot
- Compare colors between Godot and MagicaVoxel

### Minimal reproduction project

https://github.com/czlowiekimadlo/Godot-texture-bug

**Comment by AThousandShips** [comment]
Does this happen if you import it without compression?

**Comment by czlowiekimadlo** [comment]
This example is without compression. If I select VRAM compressed, there is no difference. Selecting Basis Universal makes the colors different, but still incorrect.

**Comment by timothyqiu** [comment]
> This example is without compression. If I select VRAM compressed, there is no difference. Selecting Basis Universal makes the colors different, but still incorrect.

The texture on the left has Compress > Mode set to VRAM Compressed, so it's compressed.

You are probably checking Detect 3D > Compress To which works like a 3D override. When set to Disabled, it does not change the compress mode for 3D.

It's recommended to use Lossless compress mode for pixel art style textures in 3D. See https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_images.html#detect-3d

**Comment by Calinou** [comment]
This is likely a sRGB/linear conversion issue, as textures used in 3D use linear color space instead of sRGB.
