### ISSUE TITLE
Can't open scripts in JetBrains Rider from Godot 4.1.1 - Exception message: 'The FileName property should not be a directory unless UseShellExecute is set.'

### ISSUE THREAD

**Issue by harrybrokensha** [godotengine/godot#81566]
### Godot version

4.1.1.stable.mono

### System information

MacOS Ventura 13.4 - Godot 4.1.1.stable.mono - M2 Max

### Issue description

I'm currently trying to set up Godot with JetBrains Rider for C# development. However when trying to open a script in Rider from Godot, I'm getting the error:

`modules/mono/glue/runtime_interop.cpp:1324 - Error when trying to run code editor: JetBrains Rider. Exception message: 'The FileName property should not be a directory unless UseShellExecute is set.'`

Dotnet 7.0.400 SDK is installed on my Mac. My .NET CLI executable path is set to /usr/local/share/dotnet/dotnet in Rider, and my MSBuild version is set to 17.0.

Any idea what I'm doing wrong here? Thanks.

### Steps to reproduce

- Open Godot.
- Set External Editor to JetBrains Rider.
- Open JetBrains Rider.
- Create a .cs script in Godot and open it.
- Error: `modules/mono/glue/runtime_interop.cpp:1324 - Error when trying to run code editor: JetBrains Rider. Exception message: 'The FileName property should not be a directory unless UseShellExecute is set.'`

### Minimal reproduction project

N/A

**Comment by harrybrokensha** [comment]
Edit: this seems to be fixed in the latest Godot 4.2.dev4.mono.

**Comment by soloschenko-grigoriy** [comment]
Something that worked for me on macOs ventura and Godot v4.1.1 was setting `Editor Path Optional` under Editor -> Dotnet -> Editor to point _exactly_ to the rider's executable. In my case it was `/Applications/Rider.app/Contents/MacOS/rider`. 

Note, that `/Applications/Rider.app` is technically a folder but Godot mistakenly set it up as that bin path initially
