### ISSUE TITLE
Generated documentation for single line enum duplicates the same documentation for each enumeration

### ISSUE THREAD

**Issue by dhoverml** [godotengine/godot#81578]
### Godot version

v4.2.master.custom_build [98b50eb30]

### System information

Ubuntu 20.04 LTS

### Issue description

Reproducible on 4.2dev3, 4.2dev4, and master.
This is not reproducible on 4.1.1-stable and 4.2dev1 (4.2dev2 crashed).

By `single line enum` I mean:
```
## My documentation
enum MyEnum { A, B, C }
```
The generated documentation looks like this:
![enumdocumentationbug](https://github.com/godotengine/godot/assets/135338122/ecfa38cf-3914-4a87-8c87-3424645b16b7)

The generated documentation for an enum formatted like this
```
## My documentation
enum MyEnum {
  A,
  B,
  C
}
```
looks correct
![enumdocumentationbug_good](https://github.com/godotengine/godot/assets/135338122/b3c3ae16-030e-415e-b793-7f06c4138dbc)

### Steps to reproduce

1. Attach a script to a node
2. Add this:
```
## My documentation
enum MyEnum { A, B, C }
```
3. Open the documentation for that node

### Minimal reproduction project

N/A

**Comment by anvilfolk** [comment]
Thanks for the ping! Also @dalexeev who's done a _lot_ of wonderful fixes to the docgen lately, and might have a little more time :) But it's on my radar!

**Comment by dalexeev** [comment]
Thanks, I know that this bug exists and I know where it is caused. I wanted to take a look at this along with #78934 when I have time. This is a parser issue, not a DocGen issue.

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/modules/gdscript/gdscript_parser.cpp#L783-L798

**Comment by anvilfolk** [comment]
Since you already know where/what, I'll stay away from this one! :)
