### ISSUE TITLE
Moving 3D camera, DirectionalLight3D, and Gridmaps causing visual errors

### ISSUE THREAD

**Issue by SaintGeo** [godotengine/godot#81587]
### Godot version

v4.1.1.stable.custom_build [bd6af8e0e]

### System information

Godot v4.1.1.stable (bd6af8e0e) - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads) both forward + and Compatibility

### Issue description

When moving the camera I get horizontal lines appearing between my gridmap cells. This only occurs while I have DirectionalLight3D in the scene/active. This occurs for both forward +  and Compatibility mode. It looks like some Z-fighting or something but taking the light out fixes the problem. I have searched for other gridmap errors and none of the fixes I could get to work for me in my project.

When I am exporting my mesh library tscn I am getting the following error:
"drivers\gles3\storage\mesh_storage.cpp:487 - Condition "!mesh" is true. Returning: 0"
But it doesn't seem to be affecting any functionality - all my materials and sizes update correctly.

### Steps to reproduce

WASD to move camera in repro project

### Minimal reproduction project

[MinRepoProject.zip](https://github.com/godotengine/godot/files/12590285/MinRepoProject.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/16337.
