### ISSUE TITLE
In the PhysicsServer2D, at enum DampedSpringParam description for DAMPED_SPRING_DAMPING it states the default is 1.5, but it's 1

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#81591]
### Godot version

4.2

### System information

Macos with m1

### Issue description

In the class `PhysicsServer2D` at enum `DampedSpringParam`, the description for the enum value `DAMPED_SPRING_DAMPING` is:

```
● DAMPED_SPRING_DAMPING = 2
Sets the damping ratio of the spring joint. A value of 0 indicates an undamped spring, while 1 causes the system to reach equilibrium as fast as possible (critical damping).
The default value of this parameter is 1.5.
```

However it seems that the default value for damped spring damping is 1, not 1.5.

### Steps to reproduce

Read documentation of PhysicsServer2D.damped_spring_joint_set_param and go to DampedSpringParam.

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment]
The default value is 1.5 in the physics server. What you're referring to is the default value of the `DampedSpringJoint2D` node.

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/servers/physics_2d/godot_joints_2d.h#L155

https://github.com/godotengine/godot/blob/3ed4497113fa10611b90290ce22a751fb9d26e2e/scene/2d/joint_2d.h#L126

**Comment by AThousandShips** [comment]
For manually created springs, using `joint_create` + `joint_make_damped_spring`
