### ISSUE TITLE
Interacting with Godot viewport makes Godot unresponsive

### ISSUE THREAD

**Issue by umutbalkan** [godotengine/godot#81614]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

Selecting an object either from scenetree or from the viewport causes Godot to become unresponsive for over a minute, while in 4.0.4 it's an instant action. Same also applies for scrolling in scene panel or selecting a material (either from inspector or from FileSystem, or even resizing the main window. 

I only get to interact with Godot every one or two minutes.

from 4.0.4,
![first](https://github.com/godotengine/godot/assets/8284138/5b5583bf-3c0e-4386-aa17-368dbb2e86ee)
from 4.1.1,
![second](https://github.com/godotengine/godot/assets/8284138/ab9891b5-8129-4893-92dd-723149e54858)

### Steps to reproduce

- open the project
- resize the window / select an object either from scene panel or from viewport / select a material 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/72621 and https://github.com/godotengine/godot/issues/79160.

Can you reproduce this in an empty project? I've seen reports of Tree performance regressions for large trees, but can't find the exact issue right now.

**Comment by umutbalkan** [comment]
I did. It doesn't seem to be a problem anymore in 4.2.dev4, thanks.
