### ISSUE TITLE
Build failing on MSVC 2017

### ISSUE THREAD

**Issue by SlugFiller** [godotengine/godot#81618]
### Godot version

Applicable since #80095

### System information

MSVC 2017

### Issue description

The use of `min` and `max` macros breaks due to them being explicitly undefined (to prevent collision with Godot's `min` and `max` templates. This causes errors like this:
```
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(366): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(367): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(368): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(375): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(376): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(377): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(405): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(406): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(407): error C3861: 'min': identifier not found
```

Only this one file (`thirdparty/thorvg/src/lib/sw_engine/tvgSwCommon.h`) is affected. Manually defining `min` and `max` functions for this file makes the problem go away.

### Steps to reproduce

Get MSVC 2017
Build Godot

### Minimal reproduction project

Not applicable

**Comment by Chaosus** [comment]
> MSVC 2017

It's a pretty old version of MSVC. Did you try a MSVC 2022 instead?

**Comment by SlugFiller** [comment]
> > MSVC 2017
> 
> It's a pretty old version of MSVC. Did you try a MSVC 2022 instead?

When I said that, I was told 2017 is official supported, ergo it not building is a bug. I would rather build on LLVM, but my PR for that is in limbo.

**Comment by SlugFiller** [comment]
Yes and yes. Works as expected.

**Comment by akien-mga** [comment]
Just to be clear, you confirm that vanilla thorvg 0.10.6 still fails building without my diff?

**Comment by SlugFiller** [comment]
Yes, it fails without the patch. And applying the patch makes it build. And, just for completeness sake, I tried running it too, and that works.

**Comment by akien-mga** [comment]
Thanks, I've added it to the PR, and will submit upstream.
