### ISSUE TITLE
Dictionary copy-on-write can cause invalid memory accesses due to undefined subexpression ordering

### ISSUE THREAD

**Issue by elasota** [godotengine/godot#8162]
**Operating system or device - Godot version:**
Windows 10 - Godot 2.1 - VS2017

**Issue description:**
I ran into a problem with an optimized 64-bit build built with VS2017: Capsules were always radius 0.

The problem turned out to be this line in CapsuleShapeSW::set_data:
`_setup(d["height"], d["radius"]);`

Because C++ doesn't create a sequence point between parameters, the compiler can evaluate the parameters and their subexpressions (including the float conversions) in any order it feels like as long is the dependencies are in order.  The new VS C++ code generator apparently likes to schedule calls of the same function together, so now it emits that line as the equivalent of:

`Variant& temp1 = d["radius"];`
`Variant& temp2 = d["height"];`
`float temp3 = temp1.operator float();`
`float temp4 = temp2.operator float();`
`_setup(temp4, temp3);`

"d" is mutable, and indexing a mutable dictionaries always copies and deletes the original if it's unreferenced elsewhere, so by the time temp1 is converted, the lookup of "height" has already invalidated the memory location looked up from "radius", and the case I was seeing, its type was stomped with 0.

So, this might not be a problem in 3.0 since that functionality is gone in master, but it can affect 2.1.  It's hard to really tell how widespread it is, but searching for [" yields a decent number of cases.

The simplest solution I think is to just make dictionaries not copy if their reference count is 1, which would prevent it from relocating its contents after the first access as long as none of the other accesses insert a key.  It should probably do anyway since right now it's doing a copy of the entire dictionary on every mutable access.

**Comment by bojidar-bg** [comment]
Copy-on-write was removed on master, I think we can close this?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by elasota** [comment]
This doesn't apply to 3.0.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
