### ISSUE TITLE
Window transparency does not work

### ISSUE THREAD

**Issue by Drachenbauer** [godotengine/godot#81626]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 11 v4.0.stable.official

### Issue description

The window of the project run test becomes black instead of transparent with these transparency-settings (only visible in advanced project settings):
Project-Settings -> Window -> Size -> Transparent = on
Project-Settings -> Window -> per pixel Transparency -> Allowed = on
Project-Settings -> Rendering -> Environment -> Default Clear Color = 0,0,0,0 (fully transparent)
Project-Settings -> Rendering -> Viewport -> Transparent Background = on

### Steps to reproduce

Start a new project, open the project-settings and set the window to fullscreen, not resizable and no border and set the transparency settings from above as shown there.

### Minimal reproduction project

N/A

**Comment by Drachenbauer** [comment]
It still appears in Godot v4.1.1.stable.official [bd6af8e0e]

**Comment by Calinou** [comment]
Does it work if you switch the rendering method to **Compatibility** in the top-right corner of the editor?

**Comment by Drachenbauer** [comment]
with Compatibility the black disappears.

**Comment by Calinou** [comment]
> with Compatibility the black disappears.

Which graphics card model are you using?

**Comment by 0x0ACB** [comment]
There seems to be some issue with the latest nvidia and amd drivers. Prior to the september driver updates transparency with vulkan worked fine. Now only OpenGL is working on my dedicated GPU. However, if I switch to my iGPU Vulkan transparency is working.

I noticed that on my iGPU it does not matter if I set 
```
get_tree().get_root().set_transparent_background(true)
```
to true or false. As long as I have per pixel transparency enabled and 
```
DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_TRANSPARENT, true)
```
set to true the window is transparent.

I inspected the frames with Frame Doctor and the swapchain image always has a transparent background irrespective of `set_transparent_background`. For some reason the background color changes between black and grey though. Also reverting `WINDOW_FLAG_TRANSPARENT` to false does not make the background opaque again.

The only difference I could find so far is that my nvidia card only supports `VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR` while the iGPU also supports `VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR` however this is true with both the latest driver and the nvidia 531 driver where transparency still works

**Comment by 0x0ACB** [comment]
I did some further testing compiling the engine myself. Forcing https://github.com/godotengine/godot/blob/066e7d483a8f699fd94e7133ac23978cd460a72d/drivers/vulkan/vulkan_context.cpp#L2128 to 
`VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR` or `VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR` has no change on transparency on both th iGPU and my dedicated GPU. So this doesn't seem to be the culprit.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/76167, as this is likely the same underlying issue.

@0x0ACB I suggest you post your findings in the linked issue :slightly_smiling_face:

**Comment by 0x0ACB** [comment]
I have added it to the other issue. However I do not think this is necessarily related. I think the hybrid GPU issue is more of a Windows DWM problem since the transparency issues where fixed if you ran godot on the same GPU that was running the window manager.

**Comment by devmark404** [comment]
I found a solution, which could be considered temporary

You have to change the rendering mode to **compatibility**, since the others don't work

I don't know if it's because of vulcan or amd

![solution transparent](https://github.com/user-attachments/assets/388bec17-bb83-4da1-b077-18f74add7cd4)

**Comment by BlazarTira** [comment]
I tried switching to Compatibility but it still doesn't work for me

**Comment by 0x0ACB** [comment]
https://github.com/godotengine/godot/issues/76167#issuecomment-2042425498
