### ISSUE TITLE
Button text "Quit" is truncated to "Qui" under certain conditions

### ISSUE THREAD

**Issue by mogoh** [godotengine/godot#81624]
### Godot version

v4.1.1.stable.flathub.bd6af8e0e

### System information

Godot v4.1.1.stable (bd6af8e0e) - Freedesktop SDK 23.08 (Flatpak runtime) - Vulkan (Forward+) - dedicated AMD Radeon RX 5500 XT (RADV NAVI14) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

The button text label "Quit" is truncated to "Qui".

![screenshot1](https://github.com/godotengine/godot/assets/580975/aca48d09-c8ca-4fa4-bdbe-b1a95def5d12)
![screenshot2](https://github.com/godotengine/godot/assets/580975/15304743-6c35-4a0b-9cba-edd295fd3db1)

### Steps to reproduce

Project settings:

- window/size/viewport_width=1920
- window/size/viewport_height=1080
- window/stretch/mode="canvas_items"

Then:

- New Scene: User Interface
- Add Control Node
  - Set anchors_preset to Full Rect
- Add BaseButton
  - Set anchors_preset to Full Rect
  - Set Text to "Quit"
  - Set theme_override_font_sizes/font_size = 32

### Minimal reproduction project

Here is a minimal project with this issue: https://github.com/mogoh/godot-exercises/tree/main/button-label-bug

**Comment by Calinou** [comment]
I can confirm this on 4.2.dev4. This isn't an issue with the rendering method, as I can also reproduce this after switching to Compatibility.

Changing text overrun properties in Button doesn't affect this, but changing alignment to Left does make the `t` appear. The `t` isn't visible when using Right alignment either, just like the default Center alignment.

**Comment by 398utubzyt** [comment]
I can also confirm this. It also works on multiple lines as long the `Quit` line has the largest width.

![image](https://github.com/godotengine/godot/assets/46660281/898956dc-6553-4a00-9d35-cef68d291364) ![image](https://github.com/godotengine/godot/assets/46660281/9ae8c872-8996-4099-9a5a-434810fb9f11)

I've only gotten it to work with a large button size, though. However, I can get this to work in the editor by adjusting the width ever so slightly, even without the word `Quit`.

https://github.com/godotengine/godot/assets/46660281/34afa6fa-4683-4d75-9166-f024fb2f93fc

https://github.com/godotengine/godot/assets/46660281/54bd1eda-0497-4152-85ad-d55d85ba6851

This is also the case with RtL text direction.

https://github.com/godotengine/godot/assets/46660281/9ea5a0ca-e367-4e51-a91d-575929addaa9

**Comment by Rindbee** [comment]
It seems to be related to the rounding of `text_ofs`'s x. I'm not particularly familiar with `TextParagraph`.

https://github.com/godotengine/godot/blob/29116a81df9f07c52db4d33cebdc68c5557af5eb/scene/gui/button.cpp#L353

#64351 seems to be able to solve this issue, the difference is that a wider width is specified, and the `text_ofs`'s x is close to an integer. Probably mainly the wider width improve it.

**Comment by akien-mga** [comment]
CC @bruvzg
