### ISSUE TITLE
Some custom subresources not accessible after loading with ResourceLoader

### ISSUE THREAD

**Issue by orangebongo** [godotengine/godot#81635]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I've been trying to load a specific resource for a while and I just can't seem to do it. At this point I'm not sure what specifically causes the problem, but I know that the symptom is that I can successfully load the primary resource into the editor and inspect it, but when I try to access any of the inner parts of the resource's subresource, things become null and I get an error.

### Steps to reproduce

I had massive troubles recreating this from scratch so I simply copied parts of my current project into a minimal reproduction project, which seems to have worked.

The structure is as follows.
RecordingData contains an array of frames. A frame can either be a DemoFrame or a DemoKeyframe (extends DemoFrame).
DemoKeyframe contains a PersistenceData, basically the entire state of the game.
PersistenceData is a wrapper for a stack interface.
BinaryStack is the actual stack I am expecting, since I am storing everything in binary.

All of these classes are custom.

When I try to load the included res://demo_to_playback.tres, I successfully get a RecordingData and can inspect it completely. But when I try to access the persistence data of the first frame (which is a keyframe) then despite what the inspector told me the stack has become null and I get an error.

### Minimal reproduction project

Here's the minimal repro. Everything happens in the _ready function so add a breakpoint and step through it.
[TmpBugFinder.zip](https://github.com/godotengine/godot/files/12605348/TmpBugFinder.zip)

**Comment by orangebongo** [comment]
I just noticed an error in the debug log that is probably of interest, which happens during the loading of the actual resource.
![image](https://github.com/godotengine/godot/assets/95245710/606626ef-7213-4c30-bc13-c3d160840fca)

The copy-paste error looks like this
```
E 0:00:13:0856   test_scene.gd:5 @ _ready(): Error constructing a GDScriptInstance.
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   modules/gdscript/gdscript.cpp:188 @ _create_instance()
  <Stack Trace>  test_scene.gd:5 @ _ready()
```

It points to this code:
https://github.com/godotengine/godot/blob/bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5/modules/gdscript/gdscript.cpp#L188

So the resource seems to fail to construct, but I can't see a specific reason for it yet. Trying to find any way to get more information out of this...

**Comment by orangebongo** [comment]
I figured it out:

I was very sure I had optional parameters in all of my subresource _init methods, yet I had missed it for BinaryStack. It indeed needed a parameter which meant it failed to instantiate.

```py
func _init(max_size_in_bytes: int): # <---
	_max_size = max_size_in_bytes
	_data_stream.resize(_max_size)
```
Works fine once removed, d'oh.
Chalk this up to user error, my bad!

Is there any move one can take to make this easier to debug? Maybe a better error message?
This issue can otherwise be closed, I'm unsure what the routines are for further discussion.

**Comment by dalexeev** [comment]
See also:

* godotengine/godot-proposals#5899
* godotengine/godot-proposals#1513

**Comment by orangebongo** [comment]
Thank you @dalexeev ! Closing this then as discussion seems to have been consolidated pretty well in those two.
