### ISSUE TITLE
Nodes Order in Scene

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#8163]
in the graphics software, Upper layers are front and lower layers are back. But here is different, I think this should be reverse.

![node order](https://cloud.githubusercontent.com/assets/16509592/24333914/2ce17cfc-1250-11e7-9c72-ecd0b91999a3.png)

**Comment by CowThing** [comment]
Nodes don't represent the same thing as layers in graphics software. It's more like drawing on one layer, the first thing you draw will be in the very back, and anything you draw after that will be on top. Just like the nodes, start from the top and work down.

**Comment by 2dvision** [comment]
>  It's more like drawing on one layer, the first thing you draw will be in the very back, and anything you draw after that will be on top.

But you can move the node to up or down and change the order of the nodes like layers in graphic software. I think this is confusing for artists.

**Comment by nunodonato** [comment]
I think it's the order they are added to the scene, so it makes sense the way it is.

**Comment by DenisComtesse** [comment]
If you add new child node, it makes sense to expect that the new node is (1) listed below any existing children, and that it is (2) processed after (= drawn on top of) any existing children. And this is what Godot does.

So yes, nodes are not layers. Among other things the tree order determines in which order nodes are processed, in which order they receive notifications, and even trivial things like which child comes first when you do a Node.get_children()
If nodes on top of the tree were processed after nodes at the bottom, that would be completely counter-intuitive.

**Comment by bojidar-bg** [comment]
@2dvision But, the problem is that having nodes be drawn in reverse order would be confusing for programmers, and also designers who work with HTML/CSS, so I think this is going to be a no-go :confused:

**Comment by jedStevens** [comment]
could we have an option to show a tree with the root at the bottom for users that want to think of it like layers? Maybe a checkbox in settings or in the Scene tree viewer like "Bottom Up Scene Tree"
[http://imgur.com/a/G9013](url)

Pardon my spelling of "trangle"

**Comment by nunodonato** [comment]
you are trying to solve a non-existent problem, it seems you dont want to adjust to the way godot works, and are suggesting adding unnecessary complexity. This is not photoshop.

**Comment by 2dvision** [comment]
Unity3d have [Sorting Layers and Order in Layer](https://www.youtube.com/watch?v=ZzcyREamMUo). Is it possible to have this in godot? What do you think?

**Comment by bojidar-bg** [comment]
@2dvision There is Z index if that's what you are looking for. Other that that, it __might__ happen.
Looking at the transcript, it looks like a workaround of their way of handling 2D in 3D. 

Still, reopening since discussion hasn't ended yet :smiley:.

**Comment by reduz** [comment]
This is not going to change, and has never been a problem to users. At this
point i think discussing it is pointless.
Sorting Layers and Order in Layers happen because Unity is a 3D engine
only, which means objects are drawn in cull order.

Godot 2D engine is actually true 2D engine, which means objects are drawn
in tree order. It's not an image manipulation program like Photoshop. It's
not a 3D engine.

You also already have layers (via CanvasLayer node) and Z ordering (via Z
property) in Godot, so whathever you might need is covered.

**Comment by reduz** [comment]
I understand, but I honestly don think there needs to be a work around to
this. It's really not worth it.

**Comment by karroffel** [comment]
If someone really wants to see this they could write an editor plugin, this should be enough as well and everyone who wants it can download it via the asset lib.

**Comment by 2dvision** [comment]
OK, It seems this idea is not favored by some people. Somebody tag this to archive again.  :))
