### ISSUE TITLE
godot crash when I drag a glb model file to import it

### ISSUE THREAD

**Issue by brucemy** [godotengine/godot#81631]
### Godot version

v4.1.dev.custom_build

### System information

v4.1.dev.custom_build

### Issue description

![QQ图片20230914093913](https://github.com/godotengine/godot/assets/144520730/90fd2ec7-0ebb-4767-a8be-0953add66f3e)

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
What's the exact commit hash you're using?

**Comment by Sch1nken** [comment]
Also, if possible, provide the model file for testing.

**Comment by brucemy** [comment]
this issue has been solved by me,thank you all
