### ISSUE TITLE
TabBar metadata is not reassigned if the data is an empty Array or Dictionary

### ISSUE THREAD

**Issue by 4d49** [godotengine/godot#81647]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

If we assign empty arrays or dictionary to tab metadata, they will not be reassigned if new and old data is empty.

### Steps to reproduce

```gdscript
var tab_bar := TabBar.new()
tab_bar.add_tab()

var data_a : Array = [] # Old empty data.
tab_bar.set_tab_metadata(0, data_a)

var data_b : Array = [] # New empty data.
tab_bar.set_tab_metadata(0, data_b)

print(is_same(data_b, tab_bar.get_tab_metadata(0))) # false, but must be true.
print(is_same(data_a, tab_bar.get_tab_metadata(0))) # true, but must be false.
```

### Minimal reproduction project

[demo.zip](https://github.com/godotengine/godot/files/12608972/demo.zip)

**Comment by AThousandShips** [comment]
It checks for value comparison, which treats these as equivalent and doesn't update the value

The question is if relying on reference equivalence here is safe, and if this is a bug or just the way these types are usually treated

But removing the check would be trivial
