### ISSUE TITLE
PackedByteArray.decompress() incorrectly returns empty array

### ISSUE THREAD

**Issue by brokenbeta** [godotengine/godot#81649]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

Calling `decompress()` on this PackedByteArray seems to return an empty array. I've checked with equivalent C# code and it seems to be valid data, so I'm not sure why this is failing for godot.

### Steps to reproduce

    var compressed_data = PackedByteArray([
		237, 221, 65, 74, 195, 80, 20, 134, 209, 95, 81, 4, 29, 57, 113, 33, 110,
		168, 196, 18, 48, 180, 77, 74, 146, 253, 35, 129, 70, 164, 65, 16, 116, 32,
		151, 115, 6, 165, 220, 23, 50, 249, 134, 185, 36, 73, 242, 178, 252, 36, 121,
		78, 114, 147, 228, 49, 201, 220, 29, 219, 105, 247, 214, 236, 15, 151, 67,
		0, 0, 0, 0, 0, 0, 0, 128, 141, 101, 211, 224, 126, 221, 52, 184, 187, 252,
		185, 190, 200, 220, 252, 39, 115, 254, 63, 77, 235, 209, 180, 30, 77, 235,
		209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 209,
		180, 30, 77, 235, 209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 241, 92, 216,
		252, 55, 243, 117, 57, 163, 155, 219, 211, 116, 125, 8, 0, 0, 0, 0, 0, 0, 0,
		176, 90, 150, 12, 30, 214, 37, 131, 221, 235, 31, 220, 17, 0, 0, 0, 0, 0, 0, 0,
		40, 106, 93, 51, 56, 53, 227, 161, 29, 189, 205, 0, 0, 0, 0, 0, 0, 0, 0, 248,
		214, 109, 146, 167, 36, 251, 161, 239, 219, 253, 220, 13, 253, 244, 245, 104,
		249, 154, 194, 185, 153, 223, 55, 195, 113, 56, 183, 219, 97, 211, 29, 63,
		135, 31
	])
	var decompressed_data = compressed_data.decompress(
		41892, FileAccess.COMPRESSION_DEFLATE
	)
	print(decompressed_data)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Where did you get this particular data?

**Comment by brokenbeta** [comment]
It's level data from a custom level editor.

**Comment by AThousandShips** [comment]
And you are sure it was compressed correctly and with algorithm? Also the data might contain other details and markers so there's no guarantee it works

**Comment by brokenbeta** [comment]
I could be getting my wires crossed, but this C# code works and decompresses it correctly, so I don't think so:

        var compressedData = new byte[] {
            237, 221, 65, 74, 195, 80, 20, 134, 209, 95, 81, 4, 29, 57, 113, 33, 110,
            168, 196, 18, 48, 180, 77, 74, 146, 253, 35, 129, 70, 164, 65, 16, 116, 32,
            151, 115, 6, 165, 220, 23, 50, 249, 134, 185, 36, 73, 242, 178, 252, 36, 121,
            78, 114, 147, 228, 49, 201, 220, 29, 219, 105, 247, 214, 236, 15, 151, 67,
            0, 0, 0, 0, 0, 0, 0, 128, 141, 101, 211, 224, 126, 221, 52, 184, 187, 252,
            185, 190, 200, 220, 252, 39, 115, 254, 63, 77, 235, 209, 180, 30, 77, 235,
            209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 209,
            180, 30, 77, 235, 209, 180, 30, 77, 235, 209, 180, 30, 77, 235, 241, 92, 216,
            252, 55, 243, 117, 57, 163, 155, 219, 211, 116, 125, 8, 0, 0, 0, 0, 0, 0, 0,
            176, 90, 150, 12, 30, 214, 37, 131, 221, 235, 31, 220, 17, 0, 0, 0, 0, 0, 0, 0,
            40, 106, 93, 51, 56, 53, 227, 161, 29, 189, 205, 0, 0, 0, 0, 0, 0, 0, 0, 248,
            214, 109, 146, 167, 36, 251, 161, 239, 219, 253, 220, 13, 253, 244, 245, 104,
            249, 154, 194, 185, 153, 223, 55, 195, 113, 56, 183, 219, 97, 211, 29, 63,
            135, 31
        };
    
        int decompressedSize = 41892;
        int compressedSize = compressedData.Length;

        var decompressedData = new MemoryStream();
        using (var inputStream = new MemoryStream(compressedData))
        using (var decompressor =
            new DeflateStream(inputStream, CompressionMode.Decompress))
        {
            decompressor.CopyTo(decompressedData);
        }

        Debug.Log(decompressedData.Length);
        Debug.Log(string.Join(", ", decompressedData.ToArray()));

**Comment by AThousandShips** [comment]
You're using a different method so you can't compare those, please compare with the Godot methods

**Comment by brokenbeta** [comment]
But the reason I chose to use a standardized compression algorithm is to be cross-compatible with as many engines as possible...

**Comment by AThousandShips** [comment]
Yes, but this data could contain markers that other code accepts, or violate the standard in some way the library you're using there accepts because it's more lenient

**Comment by brokenbeta** [comment]
Even if this data is invalid, which i really don't think it is, returning an empty array is incorrect, surely?

**Comment by AThousandShips** [comment]
Like this, two options:
* The data is valid, and Godot is broken here
* The data is invalid, but the `System.IO` library is lenient and accepts the data, then Godot isn't broken

> returning an empty array is incorrect, surely?

What should it do instead?

**Comment by AThousandShips** [comment]
If you run `decompress_dynamic` it says "incorrect header check", so the data isn't valid seemingly

**Comment by brokenbeta** [comment]
I feel like if `decompress` returns an empty array and `decompress_dynamic` errors out then we have already established that one of those functions is misbehaving

>What should it do instead?

give an error, obviously

**Comment by AThousandShips** [comment]
Both return an empty array, the dynamic one prints an error, one can discuss the need for an error message in the `decompress` one, but it doesn't really relate to the fact that the provided data isn't confirmed to be valid

> give an error, obviously

How? What should it return instead of an empty array?

**Comment by AThousandShips** [comment]
To be clear, we can treat printing an error message when using `decompress` as an enhancement

But without evidence that this data is valid we can't treat it as a bug, understand?

**Comment by AThousandShips** [comment]
After some testing I suspect the issue is that this isn't a compatible deflate stream, it doesn't seem to have a correct header or a correct checksum, we only support a specific setup

Using GZIP is probably more compatible, but without further details on the source of this data I can't really tell any further details

**Comment by brokenbeta** [comment]
Alright, I guess I am doing it wrong. _Writing_ to a DeflateStream in C# also produces something that godot can't read. My C library can. The Rust library I tried can't. There must be multiple different ways of laying this out. I don't know, i'm just going to find another approach.

Here's me compressing some data, which then won't load in godot (or rust), but will in C using sdefl or C#.

            var originalData = new byte[] {
                90, 100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 42, 100 // some random junk
            };

            var compressedData = new MemoryStream();
            using (var inputStream = new MemoryStream(originalData))
            {
                using (var compressor =
                    new DeflateStream(compressedData, CompressionMode.Compress))
                {
                    inputStream.CopyTo(compressor);
                }
            }

            var result = compressedData.ToArray();
            Debug.Log(result.Length);  // 16
            Debug.Log(string.Join(", ", result));  // 139, 74, 97, 100, 98, 102, 97, 101, 99, 231, 224, 228, 210, 74, 1, 0

**Comment by AThousandShips** [comment]
Try compress the same data in Godot and see the difference

**Comment by brokenbeta** [comment]
Using godot gets me a completely different sequence (120, 156, 139, 74, 97, 100, 98, 102, 97, 101, 99, 231, 224, 228, 210, 74, 1, 0, 12, 16, 1, 132) but I think it's normal to get different results from compression depending on the approach of the algorithm. its only decompressing which has a guaranteed result, am I right?

**Comment by AThousandShips** [comment]
Yep exactly, and so does several other methods like online
