### ISSUE TITLE
Breakpoints are not showing in a script editor

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#81646]
### Godot version

3ed4497113fa10611b90290ce22a751fb9d26e2e

### System information

Windows 11

### Issue description

![breakpoints_bug](https://github.com/godotengine/godot/assets/3036176/8e5d4a92-8a31-4fc5-82f5-3b658f632251)

### Steps to reproduce

Open a script editor and try to set breakpoint.

### Minimal reproduction project

N/A (too easy to reproduce)

**Comment by akien-mga** [comment]
Haven't tested but probably related to #74843 @jmb462

**Comment by YuriSizov** [comment]
Nope, it's my bad. Fixed with https://github.com/godotengine/godot/pull/81551
