### ISSUE TITLE
Feature Request: Auto close (, ", and '

### ISSUE THREAD

**Issue by 2dvision** [godotengine/godot#8164]
in [Atom](https://atom.io/) when you typing "(" (Open parenthesis), Atom close that automatically.

![auto close](https://cloud.githubusercontent.com/assets/16509592/24333999/e8f21e96-1251-11e7-8ea5-85c9c5270c01.gif)

**Comment by vnen** [comment]
This already exists: Editor Settings -> Text Editor -> Auto Brace Complete.

Though it currently is off by default.

**Comment by 2dvision** [comment]
@vnen Oh! Sorry. Is it not better that this feature enabled by default?
