### ISSUE TITLE
Texture remaps don't work in exported project

### ISSUE THREAD

**Issue by tcoxon** [godotengine/godot#81660]
### Godot version

4.1.1.stable.official

### System information

Godot v4.1.1.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 530.41.03) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

My project contains some textures that contain text. I use localisation remaps to swap the textures that get used in-game so that the text displays in the player's own language. This works fine in the editor, but in exported builds (both release and debug) it only displays English text.

The exported builds log some warnings that seem relevant:

```
WARNING: Translation remap 'res://cassette_player_text_en.png' does not exist. Falling back to 'res://cassette_player_text_en.png'.
     at: _path_remap (core/io/resource_loader.cpp:921)
WARNING: Translation remap 'res://cassette_player_text_ja_JP.png' does not exist. Falling back to 'res://cassette_player_text_en.png'.
     at: _path_remap (core/io/resource_loader.cpp:921)
```

Might be related to #80130?

### Steps to reproduce

1. Download the attached reproducer and open in Godot 4.1.
2. Run it from the editor. A script in the main scene changes the locale to ja_JP in `_ready`, so you'll see Japanese text on the screen.
3. Export the game for your platform, and run that. English text will display instead.

### Minimal reproduction project

[missing-textures.zip](https://github.com/godotengine/godot/files/12612100/missing-textures.zip)

**Comment by profour** [comment]
Wanted to bump this. We are seeing this as well on the latest 4.2beta5 for our project.
