### ISSUE TITLE
BoneAttachment3D Generates Some Error Messages On Project Startup

### ISSUE THREAD

**Issue by Kalcen** [godotengine/godot#81661]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

When a project is opened that contains a scene that uses a BoneAttachment3D node, 3 possible error messages are generated. The first two occur if you closed the project without closing the scene containing the BoneAttachemnt3D node:
```
Attempt to disconnect a nonexistent connection from 'Skeleton3D:<Skeleton3D#1719681472865>'. Signal: 'bone_pose_changed', callable: 'BoneAttachment3D::on_bone_pose_update'.

Signal 'bone_pose_changed' is already connected to given callable 'BoneAttachment3D::on_bone_pose_update' in that object.
```
An third error is generated 3 consecutive times instead of the previous two if you close out of the scene before closing out of the project:
```
editor/editor_data.cpp:880 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
editor/editor_data.cpp:683 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
editor/editor_data.cpp:745 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
```
As far as I'm aware these bugs don't impact anything? But clicking the Clear Output button every time I open a project is kind of annoying lol.

### Steps to reproduce

Create a scene containing a Skeleton3D with bones, create a BoneAttachment3D that targets a bone, save the scene, then close and reopen the project.

### Minimal reproduction project

[BoneAttachmentError.zip](https://github.com/godotengine/godot/files/12612136/BoneAttachmentError.zip)

**Comment by bitsawer** [comment]
Thanks for the report. Looks like a duplicate or https://github.com/godotengine/godot/issues/69614 and https://github.com/godotengine/godot/issues/81552, so closing to keep discussion in one place.
