### ISSUE TITLE
steam version stops detecting godot when opening a project

### ISSUE THREAD

**Issue by Kayckbr** [godotengine/godot#81664]
### Godot version

4.1

### System information

Windows 10

### Issue description

minor bug, after opening a project from Godot Steam version, steam stops detecting godot which means hours wont be counting. Can be avoided by reopening godot again but this could be fixed.

### Steps to reproduce

Open godot from steam

open a project from godot steam

steam stops detecting godot.

### Minimal reproduction project

none.

**Comment by akien-mga** [comment]
Thanks for the report. Consolidating in this existing issue:

- #18233

**Comment by MasterKuby** [comment]
For me, it still doesn't detect Godot after a project is opened, but there's an easy work-around. I just open Godot again through Steam after a project is opened.
