### ISSUE TITLE
Project description and tag as project property

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8167]
If the project have an option like tag and description, apart from the name, it could help to make a better project manager and use external tools for other type of project management.

Also if using versioning tools, will be possible to have different description and/or tags for each branch.

I'm not talking about a readme but something short, more like the asset lib project descriptions (but shorter) and categories.

ps: I don't know if this issue exists because is really hard to find something with "project" and "description" :sweat_smile:

**Comment by Calinou** [comment]
If we add a tag system, we should probably restrict the characters that can be used for consistency across projects (similar to [GitHub topics](https://github.com/topics)). For instance, only lowercase characters, numbers and underscores could be allowed.

**Comment by eon-s** [comment]
@Calinou sounds good, the only problem is for languages that do not use ascii characters, maybe let the user choose from an editable list of tags?

**Comment by LightningAA** [comment]
Should probably be closed in favor of https://github.com/godotengine/godot-proposals/issues/2329

**Comment by eon-s** [comment]
I still think that text tags are more useful but since there is no interest in this I will close it. 
A better proposal can be made by somebody else.

**Comment by LightningAA** [comment]
> I still think that text tags are more useful but since there is no interest in this I will close it.
> A better proposal can be made by somebody else.

See
https://github.com/godotengine/godot-proposals/issues/2329#issuecomment-782939183
