### ISSUE TITLE
Drag and drop files from Windows explorer to Godot not working

### ISSUE THREAD

**Issue by Kelvym115** [godotengine/godot#81678]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 Threads)

### Issue description

I'm trying to import external assets into my project and I'm not succeeding. I tried to drag and drop the files from a folder straight to the Godot editor and nothing happened.

I tried several file formats: .jpg, .png, .txt, .shader, .mp3, .mp4, 

I tried navigating to other folders through the file manager, but I get stuck in the res:// folder

I also tried throwing the files directly into the project directory through Windows Explorer, but nothing changes either. I've closed and opened the editor several times and I simply can't import anything from outside of Godot.

I don't know if I'm doing something wrong but I believe that an import window should appear when I drop external files into the editor. I tried to download the same version from the official web page on another computer and that behaviour persists.

Sorry guys, I'm just new here and I don't know if this is the normal behaviour of Godot, but seems a little bit strange for me.

### Steps to reproduce

Download the 4.1.1 version from official web page, run Godot and try to import anything to the files viewport through drag and drop.

### Minimal reproduction project

[Pages.zip](https://github.com/godotengine/godot/files/12615077/Pages.zip)

**Comment by Kelvym115** [comment]
I tried in Godot 3.5.1 and I got it. Actually dragging and dropping the file directly into the editor doesn't work, but placing files directly through Windows Explorer the Godot editor 'updates' and shows me the file that I imported normally.

In Godot 4.1.1, even placing the files directly in the folder through the explorer, the editor does not update and does not show me the files, even after restarting.

**Comment by Calinou** [comment]
I don't think drag-and-drop of arbitrary files onto the FileSystem dock is implemented.

If you're not seeing files in the FileSystem dock in 4.x, double-check that `res://` is unfolded in the FileSystem dock (the arrow next to it should point downwards). By default, it may be folded, which means you won't see any files/folders contained within.

**Comment by Kelvym115** [comment]
![image](https://github.com/godotengine/godot/assets/51379236/602a6235-7a98-46f7-b3e6-085f891c9826)

I put the file in the folder like I did in 3.x but in the FileSystem dock the folder looks empty

**Comment by Calinou** [comment]
The `.shader` extension needs to be renamed in `.gdshader` in Godot 4.

**Comment by Kelvym115** [comment]
That worked! Sorry about this. I just couldn't find it anywhere. Really lame by me. Thank you very much!

**Comment by Calinou** [comment]
Closing per the above comment.
