### ISSUE TITLE
Color is incorrect for nodes with color property by setting the RGB hex values

### ISSUE THREAD

**Issue by conest** [godotengine/godot#81679]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

The color differs from ColorRect to texture with the same RGB hex value.
The texture's color is correct after I checked the screenshot in Photoshop, but the ColorRect's color seems to have some deviation.
<img width="638" alt="Screenshot 2023-09-14 at 22 42 18" src="https://github.com/godotengine/godot/assets/10446797/4e052ff9-38dc-4313-bcfa-ad8706207f6a">
In this screenshot, the left one is ColorRect, and the right one is texture with the same RGB hex value.

### Steps to reproduce

Compare a ColorRect or any nodes that can change color through theme or style, with a texture that has the same RGB value.

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/12615103/Archive.zip)

**Comment by Calinou** [comment]
Note that using a system color picker may result in slightly different colors. The macOS system color picker allows you to choose which colorspace should be used for picking colors. For Godot, this should be sRGB, rather than something like Adobe RGB.

**Comment by conest** [comment]
> Note that using a system color picker may result in slightly different colors due to color profiles. The macOS system color picker allows you to choose which colorspace should be used for picking colors. For Godot, this should be sRGB, rather than something like Adobe RGB.
> 
> Some web browsers will also display colors differently than others (including plain areas of color, as shown in your example). Chrome is notorious for doing this, and not just on macOS.

Thanks for your advice. I knew this might be some color space issue, but this took me hours with no luck. I never thought the problem was with Photoshop. I found the image created in Photoshop was not in sRGB by using the system color picker. But I didn't find anything wrong with the color setting. After I converted it into sRGB, the problem was solved. I guess there might be something with the embedded profiles due to the psd file was created on another Mac.
