### ISSUE TITLE
compatibility renderer: TextureRect switches to nearest filtering on Viewport.size_changed

### ISSUE THREAD

**Issue by Royerson** [godotengine/godot#81676]
### Godot version

4.1.1-stable

### System information

Godot v4.1.1.stable - Windows 10.0.19044 - Vulkan (Compatibility) - AMD Radeon(TM) RX 6500 XT () - AMD FX(tm)-8350 Eight-Core Processor (8 Threads)

### Issue description

When using the compatibility renderer a TextureRect will switch to nearest filtering when the viewport size changes.
This only happens with the compatibility renderer.
The texture_filter property doesn't actually change.
It is the viewport size change that triggers it, as it won't happen when changing window size with CONTENT_SCALE_MODE_VIEWPORT.
I tried, as a workaround, applying the texture in a shader, but the bug still occurs.
The TextureRect itself can change size without triggering the bug.
I tested Sprite2D and ColorRect (texture applied with shader) and the bug doesn't affect either.

https://github.com/godotengine/godot/assets/4461259/dc22d51a-d824-4211-abf9-fa3361cd22db

### Steps to reproduce

- set renderer to compatibility
- add TextureRect
- set texture to icon.svg
- set anchor preset to Full Rect
- run game and change the window size

### Minimal reproduction project

[godot_compatibility_texturerect_windowsize_bug.zip](https://github.com/godotengine/godot/files/12614679/godot_compatibility_texturerect_windowsize_bug.zip)

**Comment by bitsawer** [comment]
Thanks for the report. I can repro this on 4.1.1 stable but not with 4.2 dev4 or current master. There has been some fixes in Compatibility renderer texture filtering state updates, so one of them probably fixed this. Closing as solved in current master, but feel free to test the latest 4.2 beta to make sure the fixes work with your device too.
