### ISSUE TITLE
LineEdit secret character hard to change/enter

### ISSUE THREAD

**Issue by kit-solent** [godotengine/godot#81681]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 Threads)

### Issue description

LineEdits secret character property is hard to edit in the inspector. It won't let me input more or less than one character so when I try and delete the default `.` to input my own character it gives me an error in the Output panel and does not change the `.`. You can change it by highlighting the `.` and typing the new character but that feels unintuitive to me so it took me a while to work out how to change it. 

### Steps to reproduce

1. Create a `LineEdit` node
2. Try and edit its Secret Character property in the Inspector without highlighting the `.`.

### Minimal reproduction project

Not really required but I'll add one if anyone asks.

**Comment by timothyqiu** [comment]
FYI. `3.x` prints an error but keeps the invalid text. I'm not sure if we need a `regression` label for this.

**Comment by jsjtxietian** [comment]
Personally, I think if the user is deleting the secret char then give an error in console is fine. 

If the user is typing the new character maybe it should automatically replace the current one ?

**Comment by Calinou** [comment]
There are 2 things we can do:

- Allow values longer than 1 character in the property, but trim characters after the first one. Mention this behavior in the documentation.
- Allow empty strings (this will act like if a space was used as a secret character), so that an error isn't printed when you erase all characters in the property.

**Comment by Deozaan** [comment]
Would it be possible to force the character to be selected so that typing anything overwrites it?

**Comment by Calinou** [comment]
> Would it be possible to automatically force the character to be selected so that typing anything overwrites it?

This would mean adding dedicated inspector functionality just for a single property, which I think is overkill.
