### ISSUE TITLE
C#: Failed to load external .net7 DLL

### ISSUE THREAD

**Issue by qq576067421** [godotengine/godot#81680]
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

window10

### Issue description

I tried to load an external DLL (.net7 library class) as bytes.

    var dll_path = Path.GetFullPath( "hotfix.dll");
    var dllData = File.ReadAllBytes(dll_path);
    var assembly = Assembly.Load(dllData);

When debugging, it turns out that `dllData` is as expected. But the data in `assembly` is unexpected after `Assembly.Load`.

Of course, using `m_Assembly.CreateInstance` to instantiate the DLL's internal class doesn't work either.

When the same code is used in a separate environment created in Visual Studio (both the main program and the DLL are .net7) which is not related to Godot, ...

<details><summary>Chinese version</summary>

我使用字节的形式加载外部dll（net7的库类），

    var dll_path = Path.GetFullPath( "hotfix.dll");
    var dllData = File.ReadAllBytes(dll_path);
    var assembly = Assembly.Load(dllData);

调试发现，dllData数据是正常的，但是Assembly load之后，assembly变量的调试数据有异常。
当然使用m_Assembly.CreateInstance来实例化dll内部的类的时候也是不行的。
相同的代码我使用visual studio单独创建的环境（主程序net7   dll程序也是net7）（和godot没有关系的另外一个环境）

</details>

### Steps to reproduce

Same as above.

### Minimal reproduction project

N/A

---

_Bug Squad Edit:_ Cleared duplication. Added english translation. The last sentence in the Chinese version does not end either.
```[tasklist]
### Tasks
```

**Comment by MrBBBaiXue** [comment]
请使用英文（或者使用翻译）书写问题反馈，godot 仓库要求使用英文进行交流，谢谢。
Please write issue in English cause majority of godotengine’s devs use english, thanks.

**Comment by timothyqiu** [comment]
Edited OP. Like noted above, next time please write the issue in English.

Also, your last sentence did not end. Maybe a copy-paste error? :P
