### ISSUE TITLE
Cannot toggle editor output limit '[output overflow, print less text!]'

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#81694]
### Godot version

v3.5.2.stable.official

### System information

Win10

### Issue description

Cannot toggle the editor showing the message  [output overflow, print less text!] after it shows a certain amount of text.

Even something simple like print(get_tree().root.print_tree_pretty()) can trigger this message,so we cannot see results of a basic function.

### Steps to reproduce

1) Load an basic project with small number of nodes
2) add line print(get_tree().root.print_tree_pretty())
3)Note that you will be unable to see the printed tree as it shows " [output overflow, print less text!]" on output panel
4) Cannot toggle, or turn off this setting (solutions discussed in https://github.com/godotengine/godot/issues/4192 do not work)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
The overflow check uses `max_cps`, which is defined by **Max Chars Per Second** project setting

https://github.com/godotengine/godot/blob/98fe7f4a30d2bb4dbc8cb49dda5671302adc1bd1/scene/debugger/script_debugger_remote.cpp#L1203

https://github.com/godotengine/godot/blob/98fe7f4a30d2bb4dbc8cb49dda5671302adc1bd1/scene/debugger/script_debugger_remote.cpp#L1106

Remember to restart the editor after changing this setting.

**Comment by rick551a** [comment]
Yes, this worked, thanks Calinou.

**Comment by Calinou** [comment]
Reopening, as project settings hint need to be changed to reflect this.

**Comment by akien-mga** [comment]
Fixed by #81717.
