### ISSUE TITLE
FBX files that contain an animation (no mesh) can not be imported properly

### ISSUE THREAD

**Issue by MotasemZakarneh** [godotengine/godot#81691]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3168) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

As the title says
i have 2 animations attached, i tried applying them on any humanoid mesh i own, and they simply can not be applied
in fact they are not imported properly, and they do not even have a skeleton.

i used the as the humanoid, which comes with animations that work, but the SpearAtk_1 does not even work or get imported properly, despite being added to the library.

https://github.com/GDQuest/godot-3d-mannequin

[SpearAtk_1.zip](https://github.com/godotengine/godot/files/12619191/SpearAtk_1.zip)

### Steps to reproduce

Open the project
go to main.tscn
go to animation player of the humanoid
select SpearAtk_1
it does not run.

### Minimal reproduction project

[AnimsTest.zip](https://github.com/godotengine/godot/files/12619311/AnimsTest.zip)

**Comment by fire** [comment]
@lyuma I thought this was working?

**Comment by lyuma** [comment]
The "Import as Skeleton Bones" option is not present on ImportAs = Animation Library, so it is still broken on latest 4.3dev build.
