### ISSUE TITLE
Steam Deck PS4 Controller UI Buttion Skipping Focus

### ISSUE THREAD

**Issue by Mainman002** [godotengine/godot#81711]
### Godot version

3.5.2 LTS

### System information

GLES2

### Issue description

I noticed an issue when running my Steam game on my Steam Deck attached to a Dock with a PS4 bluetooth controller connected. My scene tree isn't too advanced. Start with a Control / Hbox / 2 VBox / with Button nodes in each VBox. When the game is played and press either UP / Down D-Pad / Left Joystick Y-Axis the buttons skip focus selection to every other button.

Basically Button Index 0 jumps to 2, then 4, etc
![Screenshot 2023-09-15 at 2 49 27 PM](https://github.com/godotengine/godot/assets/11281480/dc479840-514f-40b6-a253-87b7531feac2)
![Screenshot 2023-09-15 at 2 49 32 PM](https://github.com/godotengine/godot/assets/11281480/e4564990-3c3d-4841-8ad6-a584e48f8a11)

This is my Input mapping
![Screenshot 2023-09-15 at 2 42 21 PM](https://github.com/godotengine/godot/assets/11281480/8f22f354-c53f-4745-982a-7f962d8ab30b)

### Steps to reproduce

Create a scene starting with Node2D / Control / HboxContainer / 2 VBoxContainers / Buttons, Export to Linux 64bit, In Desktop mode transfer game export to the Steam Deck, mark app as executable, add game to Steam Library, Go back into Game Mode, connect Steam Deck to a Dock, connect Steam Deck to a bluetooth controller (PS4 or Nintendo Switch), Now run game from your Steam Library. You should notice button skipping focus when trying to navigate with the connected bluetooth controller

### Minimal reproduction project

[Godot_Input_Skip.zip](https://github.com/godotengine/godot/files/12623545/Godot_Input_Skip.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/66878.

**Comment by Mainman002** [comment]
I can confirm my bug is caused by setting UI input events to ALL instead of 0. For some reason there's a background event that mirrors when using bluetooth on Steam Deck / Linux

**Comment by Mainman002** [comment]
As far as I can tell this bug is fixed in 4.1.2+ I know this isn't a great question as it would probably be a huge amount of work but can the new input setup be back ported to the 3.5x as a maintenance release, and If not would there be any guidance / pointers on doing that myself?

Thank you for looking into this and fixing in future versions
