### ISSUE TITLE
FileDialog.FILE_MODE_OPEN_FILES doesn't allow selecting multiple files

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#81710]
### Godot version

4.1.1 and 3ed4497113fa10611b90290ce22a751fb9d26e2e

### System information

Fedora, X11, RX 590 and Windows

### Issue description

I am trying to port https://github.com/davidkbd/Godot_SpritesheetFromFiles and I'm hitting a blocker where i cannot port this plugin to 4.x because the file dialog option to open multiple files doesn't allow me to select multiple files.

https://github.com/godotengine/godot/assets/7917475/0178c687-2301-4181-9811-cde7405f5411

### Steps to reproduce

Open MRP, select the TestPopupFileDialog tab, press the button, you'll see that you cannot select multiple files.

### Minimal reproduction project

[open-files-bug.zip](https://github.com/godotengine/godot/files/12623569/open-files-bug.zip)

**Comment by KoBeWi** [comment]
Unrelated to the issue, but if you want a spritesheet generator that works with Godot 4 check https://github.com/KoBeWi/Godot-Spritesheet-Generator (I also have a branch where I'm making it into stand-alone app)

**Comment by Zylann** [comment]
I tested in a game and it works, however I confirm it doesnt work in 4.1.1, even after simplifying test.gd:
```
func _on_button_pressed():
	var dialog = FileDialog.new()
	dialog.mode = FileDialog.FILE_MODE_OPEN_FILES
	editor_interface.get_base_control().add_child(dialog)

	dialog.popup_centered(Vector2(1050, 700))
```

**Comment by QbieShay** [comment]
I think it was auto converted by the converter, may be an issue with that?

**Comment by KoBeWi** [comment]
You are setting `mode` instead of `file_mode`. The former is a property from Window.

**Comment by AThousandShips** [comment]
`mode` is probably too generic for the converter to handle automatically
