### ISSUE TITLE
C++: No way to sort with an external variable

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8171]
I am trying to sort a list of objects in C++ per distance to an object, as fast as possible.
The problem is, I cannot carry the object's position in the comparer, which is expected to be static:

```cpp
	// Same in List and Vector
	template <class C>
	void sort_custom() {
```

Last time I had to do this for an algorithm I wrote, I added two arguments instead, which allowed me to pass any data structure I wanted to carry for the callback, as if it was a lambda capture (this pointer, some struct etc).

```cpp
typedef bool(*Predicate)(Vector3i pos, void * context);
void some_algorithm(Predicate test, void * context);
```

In this case, sort_custom would looks like this:
```cpp
template <typename T>
typedef bool(*Comparer)(const T & item, void * context);

void sort_custom(Comparer<T> test, void * context);
```

Or alternatively, for header-only code, expect a struct with a `()` operator, nicer because type-safe:
```cpp
struct Comparer {
    bool operator()(int a, int b) {
        // ...
    }
    int some_var;
}

void sort_custom(T comparer);
```

Which is C++03-ish as well, but I don't know how C++11 lambdas can be used in Godot at the moment...
The only workaround I have at the moment is to use a global variable, which is really ugly.

Any ideas?

**Comment by elasota** [comment]
The last option is the safest.  If you want to use an outside function instead of making a class, you can always make a template helper like:

```c++
template<class C, class T, bool(*S)(C, const T&, const T&)>
class ContextualCompare
{
public:
	explicit ContextualCompare(C p_context)
		: context(p_context)
	{
	}

	ContextualCompare(const ContextualCompare<C, T, S> &other)
		: context(other.context)
	{
	}

	bool operator()(const T &a, const T& b)
	{
		return S(context, a, b);
	}

private:
	C context;
};

...

bool sortfunc(const Vector3 &p_point, const Object &p_a, const Object &p_b)
{
   ...
}

...

list.sort_custom(ContextualCompare<const Vector3&, Object, sortfunc> comparer(point));
```

**Comment by Zylann** [comment]
Hitting this again, however I noticed the presence of `SortArray`, which allows to do what I want that way:
```cpp
Vector<Vector3i> positions;
if(!positions.empty()) {
	SortArray<Vector3i, BlockUpdateComparator> sorter;
	sorter.compare.center = positions;
	sorter.sort(positions.ptrw(), positions.size());
}
```
