### ISSUE TITLE
3D Clutering issue when using Asset Library project, fixed with disabling SSAO?

### ISSUE THREAD

**Issue by superhylia** [godotengine/godot#81718]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated Radeon(TM) RX 580 (Advanced Micro Devices, Inc.; 31.0.21031.1005) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I was trying out Kenney's wonderful 3D Platformer Starter Kit. However, when I loaded into the game, the game would have clustering issues at certain angles. (the glitchy checkerboard pattern thingy as I thought, the lovely Qbieshay informed me of the proper term and helped me out.) I was able to fix it by going to the Environment node, editing WorldEnvironment, and disabling SSAO.
![image](https://github.com/godotengine/godot/assets/43157926/b191716e-0add-48c7-9b0a-70c6ed89f5c6)

### Steps to reproduce

I didn't change any settings outside of trying to fix it: I downloaded the starter kit from both GitHub and the in-app Asset Library in addition to a graphics driver update and had issues all 3 times. 

### Minimal reproduction project

N/A. The starter kit can be found at https://github.com/KenneyNL/Starter-Kit-3D-Platformer or in the Asset Library. I didn't change any settings in the engine outside of trying to fix it.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/61415.
