### ISSUE TITLE
Impossible to create GradientTexture1D textures in ShaderMaterials

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#81712]
### Godot version

4.2-dev4

### System information

Windows 11

### Issue description

When trying to create a GradientTexture1D for a ShaderMaterial sampler2D uniform, it just remains empty and does not create the texture at all.

It also retroactively messes up all ShaderMaterials that used a GradientTexture1D textures that worked in previous versions, so they just become empty and revert to the original sampler2D default color when no texture is used (either white or black).

Note: this seems to be only for ShaderMaterials. Other instances where you can add a GradientTexture1D, like a Sprite2D texture or a StandardMaterial3D texture seem to be working normally.

### Steps to reproduce

1 - Create a ShaderMaterial for anything that can receive a material.
2 - Add a uniform sampler2D to the shader parameters. You can just copy and paste this:
```
shader_type spatial;
uniform sampler2D gradient_texture_1d;
```
3 - Try to create GradientTexture1D in the now available texture parameter. It'll remain empty and not work at all.

### Minimal reproduction project

[GT1.zip](https://github.com/godotengine/godot/files/12623677/GT1.zip)

Open the only scene in the project, find the ShaderMaterial in the MeshInstance3D and try to create a GradientTexture1D in the Shader Parameters.

**Comment by AThousandShips** [comment]
Please provide a complete project, as opposed to just a single file, this makes it possible to investigate the setup and how settings are set and how you're using the scene file, to make sure it's not a configuration problem

**Comment by antourenein** [comment]
I've tested it in two different projects myself, so I'm fairly sure it's not a project thing, but I've updated the original issue with a minimal reproduction project anyway.

**Comment by bitsawer** [comment]
Thanks for the report. Fixed in master by https://github.com/godotengine/godot/pull/81198, so closing as completed.
