### ISSUE TITLE
"Paste as Sibling" behaves identically to "Paste" from context menu

### ISSUE THREAD

**Issue by ghmart** [godotengine/godot#81721]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Debian GNU/Linux 11 (bullseye) 11

### Issue description

"Paste as sibling" behaves identically to "Paste" from context menu for non-root nodes. When using keyboard shortcut "Ctrl+Shift+V" it behaves as intended.

### Steps to reproduce

1. Create new scene of any type.
2. Add child node.
3. Copy child node.
4. Right-click child node and choose "Paste as Sibling".

![sibling](https://github.com/godotengine/godot/assets/7192155/57e89394-665d-4471-9e82-532562be8206)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This was confirmed on the Godot Contributors Chat.

**Comment by ghmart** [comment]
There is no artifact for Linux editor for https://github.com/godotengine/godot/pull/81673, only Linux-editor-mono, which don't work on my OS (need to setup .net, etc.)

Tested on current master [5f1e56f](https://github.com/godotengine/godot/commit/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8), it's fixed now!

Should I close issue myself? Not sure about rules who is responsible for closing issues.

**Comment by Calinou** [comment]
Closing, as this is resolved in `master`.

> Should I close issue myself? Not sure about rules who is responsible for closing issues.

You can close any issue you've opened :slightly_smiling_face:
