### ISSUE TITLE
GLB Model is not imported correctly in Editor

### ISSUE THREAD

**Issue by srcnalt** [godotengine/godot#81744]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11, 64x, Vulkan API 1.3.224, NVIDIA GeForce RTX 3080 Ti Laptop GPU

### Issue description

I am downloading and appending a GLB file into the scene, the same code works and the result is visually correct. However when same code used modified to add the model to the current scene that is being edited, only bone structure is visible and just root bone is shown in the scene window.

Code for runtime:
```swift
extends Node

var http_request: HTTPRequest
var avatar: Node3D

func _ready():
	http_request = $HTTPRequest
	http_request.connect("request_completed", _request_completed)

func _on_pressed():	
	if avatar != null:
		avatar.free()
		
	if http_request.request("https://models.readyplayer.me/65059d4f7a4b5e00b4d9ea82.glb?textureAtlas=1024") != OK:
		push_error("An error occurred in the HTTP request.")

func _request_completed(result, response_code, headers, body):
	if response_code == 200:		
		var doc = GLTFDocument.new()
		var state = GLTFState.new()
		if doc.append_from_buffer(body, "", state) == OK:
			var avatar = doc.generate_scene(state)
			add_child(avatar)
```

Result:
![image](https://github.com/godotengine/godot/assets/3163281/0657b296-ebcf-4e40-9463-afe10a62d204)

***

Code for Editor tool:
```swift
@tool
extends Node

var http_request: HTTPRequest
var avatar: Node3D

func _process(delta):
	pass

func _ready():
	http_request = $HTTPRequest
	http_request.connect("request_completed", _request_completed)

func _on_pressed():
	if avatar != null:
		avatar.free()
		
	if http_request.request("https://models.readyplayer.me/65059d4f7a4b5e00b4d9ea82.glb?textureAtlas=1024") != OK:
		push_error("An error occurred in the HTTP request.")

func _request_completed(result, response_code, headers, body):
	if response_code == 200:
		var doc = GLTFDocument.new()
		var state = GLTFState.new()
		if doc.append_from_buffer(body, "", state) == OK:
			var avatar = doc.generate_scene(state)
			var parent = get_tree().edited_scene_root
			parent.add_child(avatar)
			avatar.set_owner(parent)
```

Result:
![image](https://github.com/godotengine/godot/assets/3163281/7e11eb95-d5e5-4070-af98-b5ca2e033251)

### Steps to reproduce

Steps to reproduce:
- Open project
- Open and run `node_3d.tscn` to observe avatar loading in runtime
- Enable plugin at `Project > Project Settings > Plugins > rpm-godot-sdk`
- click on load button on the docked plugin window
- observe bone structure only character loaded

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12641163/project.zip)

**Comment by bitsawer** [comment]
Looks like you need to manually enable `GLTFDocumentExtensionConvertImporterMesh` extension in editor tool scripts. Also, recursively set the owner nodes, setting just the root owner is not enough. 

Not sure why the textures are not loaded, might be another runtime / tool script different and possibly intentional. You might have to manually download them first and save them as resources using `ResourceSaver` so that they are found when loading the data.

So the new tool script is this:

```gdscript
@tool
extends Node

var http_request: HTTPRequest
var avatar: Node3D

func _process(delta):
	pass

func _ready():
	http_request = $HTTPRequest
	http_request.connect("request_completed", _request_completed)

func _on_pressed():
	if avatar != null:
		avatar.free()

	if http_request.request("https://models.readyplayer.me/65059d4f7a4b5e00b4d9ea82.glb?textureAtlas=1024") != OK:
		push_error("An error occurred in the HTTP request.")

func update_owner(node: Node3D, own: Node3D):
	node.set_owner(own)
	for n in node.get_children():
		update_owner(n, own)

func _request_completed(result, response_code, headers, body):
	if response_code == 200:
		var ext = GLTFDocumentExtensionConvertImporterMesh.new()

		var doc = GLTFDocument.new()
		doc.register_gltf_document_extension(ext)
		var state = GLTFState.new()

		if doc.append_from_buffer(body, "", state) == OK:
			var avatar = doc.generate_scene(state)
			var parent = get_tree().edited_scene_root
			parent.add_child(avatar)
			update_owner(avatar, parent)

```

**Comment by srcnalt** [comment]
Thank you @bitsawer! This did work indeed! 🙇 
I set the const for how binary images are handled in GLTFState to `HANDLE_BINARY_EMBED_AS_UNCOMPRESSED` and textures also showed up! However I wasn't able to use set method, which appears to be in the docs but not accusable.

```swift
...
var state = GLTFState.new()
state.handle_binary_image = GLTFState.HANDLE_BINARY_EMBED_AS_UNCOMPRESSED
...
```

**Comment by srcnalt** [comment]
One problem with this approach is it's impact on the scene size, it goes from 2kb to 61mb which must be due to uncompressed textures directly being saved in scene. I hope to replicate what happens when dragging and dropping a glb into the scene. Which has almost no impct in scene size, and uses file from local instead of memory.
