### ISSUE TITLE
Web editor: saving of seemingly everything is completely broken

### ISSUE THREAD

**Issue by hikari-no-yume** [godotengine/godot#81743]
### Godot version

v4.1.1.stable.official

### System information

Happens in:

* Firefox 117.0.1 (64-bit) on Windows 10 
* Chrome 116.0.5845.188 on Windows 10

### Issue description

Trying to save files within `/home/web_user` does not work. **Trying to load the file after saving it will always fail.**

The files show up in some places:

* The window where you select a project (but the project is "missing")
* The load and save dialogs

But not in others:

* The "File System"* panel
* Quick Load

This affects many types of files, e.g.:

* Scenes (see below)
* The project (shows up as missing)
* Scripts
* Changing language does not work
* Mesh resources (though caching may obfuscate this)
* Textures

This is enough to make the web editor almost completely useless.

### Steps to reproduce

1. Go to https://editor.godotengine.org/releases/latest/
2. Click "Start Godot Editor"
3. Click "New Project"*
4. Click "Create Directory"*
5. Click "Create and Edit"*
6. In the "Scene"* panel, under "Create Root Node:"\*, click "3D Scene"
7. In the "Scene"* menu, click "Save Scene"\*
8. Click "Save"*
9. In the "Scene"* menu, click "Reload Saved Scene"

You should then get this error:

> "Can't open file 'node_3d.tscn'. The file could have been moved or deleted." error.

You can also try to run the game, which fails because there is no default scene, and you can't set a default scene because saving does not work.

\* I can only guess what the English version is, since changing the language from Swedish to English does not work despite restarting several times.

**Comment by hikari-no-yume** [comment]
Can confirm this is also broken in Chrome 116.0.5845.188 for me. Same OS.

**Comment by hikari-no-yume** [comment]
[4.0.stable](https://editor.godotengine.org/releases/4.0.stable/) works. [4.1.stable](https://editor.godotengine.org/releases/4.1.stable/) does not. So it's a regression between 4.0 and 4.1.

[4.2.dev.4](https://editor.godotengine.org/releases/4.2.dev4/) does not seem to be affected. So it has already been fixed.

This is probably another dupe of #79866?

I would like to suggest that editor.godotengine.org should not default to 4.1.0, because it will give users a very bad impression of Godot.

**Comment by Qainguin** [comment]
Personally, using the web editor everyday, defaulting to 4.0.stable. It is the one that doesn’t have the axis sticking issue and it fixed this issue along with the import issue.

**Comment by akien-mga** [comment]
We "fixed" the issue by changing `editor.godotengine.org`'s default version (`latest`) to point to 4.2-dev5, which doesn't have this issue.

This issue should be fixed in 4.1.2 once #79866 is cherry-picked.

**Comment by hikari-no-yume** [comment]
@akien-mga Thanks, that's exactly what I wanted. Should I close this, or would you prefer I leave it open?

**Comment by Qainguin** [comment]
> We "fixed" the issue by changing `editor.godotengine.org`'s default version (`latest`) to point to 4.2-dev5, which doesn't have this issue.
> 
> This issue should be fixed in 4.1.2 once #79866 is cherry-picked.

The problem with using 4.2dev5 is that dev4 and dev5 have a sticking axis problem with keyboard. (This causes problems with the editor camera and wasd movement.) That is why I suggested 4.0.stable.

**Comment by Calinou** [comment]
Closing, as this is resolved in `master`.
