### ISSUE TITLE
_make_custom_tooltip with default theme is not rendering the PopUp Menu shadow in the tooltip

### ISSUE THREAD

**Issue by JoaquimAlfredoRibeiro** [godotengine/godot#81747]
### Godot version

4.1

### System information

Windows 10 - Godot 4.1 stable

### Issue description

Using a default theme for project tooltips is not showing a StyleBoxFlat shadow.
I would expect the custom tooltips to include previously defined shadows.

### Steps to reproduce

Run the sample project and mouse over the only label.

### Minimal reproduction project

[tooltip.zip](https://github.com/godotengine/godot/files/12641291/tooltip.zip)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/82108, which is more detailed.
