### ISSUE TITLE
Color8 Seems to not be in the GoDot C# library

### ISSUE THREAD

**Issue by hereandnowlive** [godotengine/godot#81745]
### Godot version

4.1.1 64 bit · C# support · 17 July 2023 

### System information

Windows 11

### Issue description

This maybe my mistake but for the life of me I can't find this Color8 function in c# that is suppose to take in and convert to a standard Color value or hold the byte values. I am a refugee of unity so I am used to using the convenient Color32 and I am surprised godot doesn't have something like this in the system. I might have just had the wrong library or referenced the wrong section any help with this is greatly appreciated!

https://docs.unity3d.com/ScriptReference/Color32.html
https://haxegodot.github.io/godot/godot/Color.html#color8

### Steps to reproduce

N/A since it's a script reference thing.

### Minimal reproduction project

N/A since it's a script reference thing.

**Comment by pulawskig** [comment]
> The global Color8 method to construct a Color from bytes is available as a static method in the Color type.

https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html

So it's `Color.Color8(255, 255, 255)`

**Comment by hereandnowlive** [comment]
Yup you are correct I am dumb. Thanks!

**Comment by hereandnowlive** [comment]
Looks like this issue has been resolved.
