### ISSUE TITLE
OS.find_keycode_from_string("KEY_1") returns 0

### ISSUE THREAD

**Issue by bitbutter** [godotengine/godot#81749]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3168) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

print(OS.find_keycode_from_string("KEY_1")) gives a 0, but i expected 49 based on the list here: https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#enumerations

i get the same 0 result if i try
print(OS.find_keycode_from_string("KEY_2"))
print(OS.find_keycode_from_string("KEY_3"))`

(apologies in advance if this is user error)

### Steps to reproduce

Open a new project, add a node and add this code to it.

`func _ready():
	print(OS.find_keycode_from_string("KEY_1"))
	print(OS.find_keycode_from_string("KEY_2"))
	print(OS.find_keycode_from_string("KEY_3"))`
	
output is
0
0
0

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
`KEY_1` is just the enumeration identifier name. To get keycode from `1`, simply use:

`print(OS.find_keycode_from_string("1"))`

which prints 49 as expected. The reverse version is `get_keycode_string()`:

`print(OS.get_keycode_string(KEY_1))`

which prints `"1"`.
