### ISSUE TITLE
Joypad analog triggers do not work on web export (Xbox One controller)

### ISSUE THREAD

**Issue by lapspider45** [godotengine/godot#81758]
### Godot version

4.1.1

### System information

Windows 10 version 22H2, Google Chrome 116.0.5845.188

### Issue description

Similar to #45535, the L and R triggers don't register any input on **web exported builds only**. Meanwhile they work fine on https://hardwaretester.com/gamepad, and also in non-web builds.
Tested with the above configuration and a Xbox One model 1708 gamepad.

### Steps to reproduce

see below

### Minimal reproduction project

```gdscript
func _input(event):
	print(event.as_text())
```

Simply run and see that there is no output in the web console when pressing the triggers. You can also use the [gamepad demo](https://github.com/godotengine/godot-demo-projects/tree/master/misc/joypads), if you can find a version that works on 4.1

**Comment by cjschmidt1494** [comment]
Does anyone know if this is fixed in 4.2?

**Comment by lapspider45** [comment]
Still present in 4.2.

**Comment by lapspider45** [comment]
It seems like the reported action strength is not always 0, but when pressing down the trigger quickly it briefly turns into a small positive value (like 0.05), and when releasing quickly it turns into a small negative value.

Maybe the reported value is actually the delta from the previous frame?

**Comment by CrispinStichart** [comment]
I uploaded a simple controller tester to itch to demonstrate the issue: https://crispinstichart.itch.io/godot-controller-test
