### ISSUE TITLE
@tool Viewport node in editor fails to get_texture(), returns solid purple image.

### ISSUE THREAD

**Issue by LunaticWyrm467** [godotengine/godot#81754]
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

Windows 11, RTX 3050 Laptop, 11th Gen i5, Vulkan, Nvidia GeForce Game Ready Driver 536.45

### Issue description

I am developing a small editor tool for meshing together some texture data created in a tilemap, saving it via a viewport into one big texture, and reprojecting said texture as a UV map for a box mesh.
The problem is that the viewport in the editor doesn't seem to work properly when get_texture() is called, as the returned image is just a solid purple color.
I saw that people were experiencing similar issues with the viewport node in-game, and so I'm not sure if this is a duplicate or not. However, I noticed that none of the solutions that were provided in those posts worked, so maybe this might be a different issue all together. Maybe a viewport feature isn't initializing properly in editor mode?

### Steps to reproduce

1) Open up the MRP, and click on the Viewport in the root scene.
2) You should see that the viewport does in fact show some kind of dummy texture in its preview.
3) Click the 'capture_screen' toggle to attempt to take a screenshot of the texture.
4) The outputted texture projected on a box mesh is outputted as a mesh instance. This is for some reason purple, and contains no traces of the original texture seen in the viewport's preview.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12641447/MRP.zip)

**Comment by sci-comp** [comment]
I have also encountered this while trying to automate icon generation of scenes through SubViewport's `get_texture().get_image()`

![PF_Rock_Riser_Tall](https://github.com/godotengine/godot/assets/7660069/979ffc67-859e-4086-bdb8-b6363dca5985)

**Comment by connor-lennox** [comment]
@LunaticWyrm467, the problem in your MRP is how you are constructing your ImageTexture.

You have the following lines in `main.gd`:
```gd
# Take a screenshot.
var dat: Image              = get_texture().get_image()
var tex: ImageTexture       = ImageTexture.new()
var mat: StandardMaterial3D = StandardMaterial3D.new()
tex.create_from_image(dat)
```
However, the function `ImageTexture.create_from_image(..)` is actually a static function which returns an ImageTexture. In your last line of the above snip you're actually discarding a _new_ ImageTexture that has what you want.

Updating the code to the following fixes it:
```gd
# Take a screenshot.
var dat: Image              = get_texture().get_image()
var tex: ImageTexture       = ImageTexture.create_from_image(dat)
var mat: StandardMaterial3D = StandardMaterial3D.new()
```

Note that I've changed the construction of the `ImageTexture` to immediately call the static `create_from_image` function, instead of using the constructor.

**Comment by LunaticWyrm467** [comment]
I don't know how I overlooked that. 😅 Thanks for the insight.
