### ISSUE TITLE
Visual helpers to see Camera2D limits

### ISSUE THREAD

**Issue by MattUV** [godotengine/godot#8175]
I think a great improvement for Camera2Ds would be to have visual helpers in the editor's 2D view to see the limits.

Today (2.1), you have to move around your camera node to see where the limits are.
If you could  see the four corners of the limits rectangle in the 2D would be easier. And even better: if there were handles to change them directly in the 2D view!

**Comment by Zylann** [comment]
I think you can see the rectangle already?
![image](https://cloud.githubusercontent.com/assets/1311555/24349521/3848384c-12d7-11e7-8385-f13e6c31200f.png)

**Comment by hubbyist** [comment]
I think MattUV is talking about camera movement limits when it is attached to a character node.

**Comment by MattUV** [comment]
Yes, that is what hubbyist is talking about.
When you move the camera around, you can see the purple rectangle move as well, until it reaches the limit. That is the only current way to visualize it.

**Comment by MattUV** [comment]
Here is what I'm thinking about:
![limits](https://cloud.githubusercontent.com/assets/13215043/24370876/461ebfde-1329-11e7-835e-82d108594ccb.png)

The same thing could be done for the margins, even in Control nodes.

**Comment by HummusSamurai** [comment]
This would be lovely!

**Comment by eon-s** [comment]
Is hard to set up multiple cameras for multiple viewports, I wonder if secondary cameras could have some optional (and grayed out maybe) helpers too.

**Comment by bojidar-bg** [comment]
@eon-s Yeah, it probably would be so, just like cameras currently draw thicker lines when they are "current".
