### ISSUE TITLE
[SpriteFrames ]Value of FPS field is applied to next selected animation while field is being focused.

### ISSUE THREAD

**Issue by Phanterm** [godotengine/godot#81767]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Quadro T2000 () - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When in the SpriteFrames animation editor, if the user clicks on the FPS field and sets a new value, that value will be applied to the next selected animation while this field remains focused. 

### Steps to reproduce

[Having installed the sample project]
1. Double-click on "new_sprite_frames.tres"
2. In the SpriteFrames editor that pops up, select "animA" in the list on the left. Each of these animations have their FPS value set to 5 by default.
3. Click on the FPS field, and set the value to 10.
4. While the FPS field is still focused, select "animB". You will see now that the FPS value from the previous animation has automatically been applied to the new one, and animB will have a value of 10 FPS.

Note that at this point if you select "animC" while the FPS field is still focused from earlier, it will *not* change the value to 10FPS, indicating that this problem only occurs for the next immediate animation selected.

### Minimal reproduction project

[godot-bug-animation.zip](https://github.com/godotengine/godot/files/12641602/godot-bug-animation.zip)

**Comment by Phanterm** [comment]
I see this is actually a duplicate report and will be fixed. Closing on your behalf; apologies! :)

**Comment by Calinou** [comment]
> I see this is actually a duplicate report and will be fixed. Closing on your behalf; apologies! :)

Can you link to the issue in question?

**Comment by Phanterm** [comment]
Certainly! https://github.com/godotengine/godot/issues/80575
