### ISSUE TITLE
AnimationPlayer: Editor crashes when clicking on "Interpolation Mode" with nonexistent node path

### ISSUE THREAD

**Issue by perry-blueberry** [godotengine/godot#81769]
### Godot version

4.1.1.stable

### System information

Ubuntu 22.04

### Issue description

The editor crashes when clicking on "Interpolation Mode" when a path points to a none-existing `NodePath`. I noticed this issue when I duplicated an `AnimationPlayer` from one scene to another.

I expect some sort of error message but not a crash.

### Steps to reproduce

Create a new project with a simple scene and add an `AnimationPlayer` as a child node. Change a path (tracks/0/path) to something that doesn't exist. Click on the button for "Interpolation Mode".

### Minimal reproduction project

[AnimationPlayerCrash.zip](https://github.com/godotengine/godot/files/12641629/AnimationPlayerCrash.zip)

**Comment by RealMadvicius** [comment]
That should be an easy fix, it is a null point not checked in animation_trackeditor.cpp line 2698 int he function
`void AnimationTrackEdit::gui_input(const Ref<InputEvent> &p_event) `
...
`Node *nd = ap->get_node(ap->get_root())->get_node(NodePath(npath.get_concatenated_names()));`

then we call this line without checking if the node pointer "nd" is not null

`ClassDB::get_property_info(nd->get_class(), prop, &prop_info);`

**Comment by RealMadvicius** [comment]
I will read a bit about the coding policy for the godot coding style etc and see if i find some free time to push a fix, then pull request , unless someone else do it first <_<
