### ISSUE TITLE
Max height for sprite preview in Inspector

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#8176]
As you can see in the image, Godot does not display Sprites with a big difference in width/height aspect ratio properly. At least very tall sprites messes up the inspector view. The image used here is 800x20 pixels. As you can see the Inspector is maxed out in size but the properties are not even visible below the preview. 

Solution: Make a max height for sprites displayed in the preview window.

![godottallimages](https://cloud.githubusercontent.com/assets/24936603/24355825/b87894ba-12f7-11e7-91cf-096c4cc62260.jpg)

Godot version 2.1.2

**Comment by nunodonato** [comment]
I couldn't replicate this in current master. Is this safe to close since it was already merged for 2.1?

**Comment by akien-mga** [comment]
Yes.
