### ISSUE TITLE
.cs files clicked in Godot that launch Visual Studio fail to load the project.

### ISSUE THREAD

**Issue by BldgBlocks** [godotengine/godot#81763]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

Visual Studio opens but fails to load the project correctly. Attempts to right click and reload fail to load project.

### Steps to reproduce

Unity Mover. Download new Godot 4.1.1 .net version. Download the .net 6.0 sdk. Visual Studio Installer Desktop environment and development with C++ modules. Project Settings > Tools > C# > Create C# Solution. Create a C# script. 

When I double click the script within Godot, Visual Studio launches but the project says unloaded. If I try to right click, Reload Project it fails with an error about SDK resolver fails, can not find System.Runtime Version.... , can not find xxx.csproj file.
 
What I have to do is open the file explorer, and double click either the .csproj or the .sln and Visual Studio opens and things appear to be working correctly.

![UnloadedProjectView](https://github.com/godotengine/godot/assets/122186550/460225ec-5941-4101-84a6-d9a2393f9b02)

![ErrorMessageView](https://github.com/godotengine/godot/assets/122186550/386aed49-8483-410b-8a0a-36eee8a2c7d6)

![LoadFailedView](https://github.com/godotengine/godot/assets/122186550/d0739165-b37f-43b1-ba5f-714326b1a9a9)

This is the IDE after just opening the .csproj or .sln from file explorer.

![ResolvedView](https://github.com/godotengine/godot/assets/122186550/f978f089-4a36-4df7-b3a1-4c4bd123373a)

### Minimal reproduction project

New C# installation as listed in steps to reproduce.

**Comment by RealMadvicius** [comment]
I tried to reproduce with the 4.1.1 stable.mono.official but for me it opens just fine the file and i didn't have to do generate a C# project, seems it generated by itself as soon as i created a new script.

1. I created a new project
2. right click in the file explorer section on the res:// tree item => create_new => script
3. select C# and create
4. it generates the CS file and the .csproj and the .sln

Then tested from the script tab

1. from main editor view click on top "script" button tab next to 3D view
2. from the script files browsing view click on file => new script
3. select C# and create
4. it generates the CS file and the .csproj and the .sln

In case I do twice one of these creation processes or the first then the second so ending up with several scripts, it still manages to update the .csproj and .sln and also allows me to open the script directly in visual studio when i double clic a script to open

**Comment by BldgBlocks** [comment]
Thank you for your testing. I had the same experience with the .csproj and .sln files being created automatically.

I couldn't find anything online and it took me a bit so I thought I was being more thorough including the C#>Create C# Solution command... I have also definitely had the Visual Studio option selected as Godot did open Visual Studio.

The files created appear correct, the project will build. But what I do notice is that in the images I attached, the paths and the name displays are capital, but when it is opened directly and things work, the paths are normal casing. Which I think normally wouldn't matter... For some reason, whatever data is being sent to Visual Studio is off for some reason... The solution is in quotes 'SECONDTESTPROJECT' vs 'SecondTestProject' assuming visual studio just inserts what it is given...

Just to include, I now have code completion, I can run in debug mode. Everything appears to work. As long as I open the project from the file explorer.

**Comment by RealMadvicius** [comment]
Could you show the content of the .csproj and .sln that didn't work/generated an error with all uppercase text from your first post?

**Comment by BldgBlocks** [comment]
Below is what I was writing... I had changed modules, uninstalled old versions, thought I ran repair. But anyway, I had a minor version update for VS 2022. I just did the update, no other changes, and now Godot opens the .cs fine...

I have multiple projects for testing and they all do it.  Here you go:
.sln
<Project Sdk="Godot.NET.Sdk/4.1.1">
	<PropertyGroup>
      <TargetFramework>net6.0</TargetFramework>
      <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>
</Project>
.csproj
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2012
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SecondTestProject", "SecondTestProject.csproj", "{AB48087E-154A-4B23-89AF-5B72D9A91BC1}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
	Debug|Any CPU = Debug|Any CPU
	ExportDebug|Any CPU = ExportDebug|Any CPU
	ExportRelease|Any CPU = ExportRelease|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.ExportDebug|Any CPU.ActiveCfg = ExportDebug|Any CPU
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.ExportDebug|Any CPU.Build.0 = ExportDebug|Any CPU
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.ExportRelease|Any CPU.ActiveCfg = ExportRelease|Any CPU
		{AB48087E-154A-4B23-89AF-5B72D9A91BC1}.ExportRelease|Any CPU.Build.0 = ExportRelease|Any CPU
	EndGlobalSection
EndGlobal

**Comment by looscolin** [comment]
Any update on this? I still have this problem

**Comment by AntonyHanna** [comment]
Not sure if this will necessarily be a solution for others but what worked for me was potentially one of two things:

Repairing my Visual Studio install using the Visual Studio Installer, followed by updating my Visual Studio to the latest version. Ever since doing that I can load my Visual Studio project even when launching it from within Godot.

Hopefully that works for others that come across this.
