### ISSUE TITLE
TouchScreenButton shape changes are not (visually) updated in the scene editor.

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8177]
**Ubuntu 16.10 - Godot version: 2.1.3 rc1**

**Issue description:**
TouchScreenButton draws a shape when creating it but don't update the shape in the editor when changing values.
It does show the correct shape when running and updates the shape in the editor when changing the "shape centered" property
It should update the shape in the scene editor when the resource changes.

**Steps to reproduce:**
- Add a TouchScreenButton.
- Create a Shape (like a CircleShape2D).
- Edit the shape in the inspector, changes won't be reflected in the light blue shape.
- Run with visible collision shapes to see the correct shape.
- Toggle the shape centered property to see the correct shape in the scene editor.

**Comment by akien-mga** [comment]
CC @RandomShaper.

**Comment by akien-mga** [comment]
Fixed by #8244.
