### ISSUE TITLE
Godot Editor freezes up after resuming from sleep mode

### ISSUE THREAD

**Issue by PrivateButts** [godotengine/godot#81786]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Ubuntu 23.04 23.04 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (nvidia; 525.125.06) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Whenever I leave Godot open on my laptop and it goes to sleep, it becomes unresponsive after logging back in. I usually have to open btop to kill it, as it doesn't respond to closing the window or even a control+c in the terminal I start Godot from. This is the error that floods my console when it happens:

```
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2360)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: prepare_buffers (drivers/vulkan/vulkan_context.cpp:2283)
```

### Steps to reproduce

1. Open Godot
2. Put the laptop to sleep
3. Wake it up

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52738 (this cannot be fixed without implementing https://github.com/godotengine/godot-proposals/issues/6423 first).
