### ISSUE TITLE
there's a thin separator line between filesystem items in split mode

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81787]
### Godot version

4.1.1

### System information

linux

### Issue description

![image](https://github.com/godotengine/godot/assets/71937306/9a9f3f33-4d57-44d0-bb8d-03f9c2f06024)

this line appears between each rows of icons, it shouldn't be visible.

### Steps to reproduce

- enable the FileSystem dock's split mode
- enable big icons
- create enough empty folders

### Minimal reproduction project

I think zipping 5 empty folders is silly

**Comment by KoBeWi** [comment]
This is because the grid is internally ItemList.
