### ISSUE TITLE
There is no way to hide the shape on a TouchScreenButton

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8178]
**Ubuntu 16.10 - Godot version: 2.1.3 rc1**

**Issue description:**
TouchScreenButton shape is a great feature, but is not possible to turn the shape visibility off without  hiding the button or removing the shape.
While seeing the shape is a good visual feedback for input design, it is also a problem for visual design, so a way to turn it visible/hidden will be nice to have.

**Steps to reproduce:**

- Add a TouchScreenButton.
- Create a Shape (like a CircleShape2D).
- There is no way to hide the shape.

**Comment by akien-mga** [comment]
CC @RandomShaper.

**Comment by akien-mga** [comment]
Fixed by #8244.
