### ISSUE TITLE
[ItemList] No way to get/set columns titles

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#81797]
### Godot version

ba54c34551d1bda5139515d74e7d614ccbc43cea

### System information

macOS Macbook Pro M1

### Issue description

There is no functionality in `ItemList` (a GUI component) to set column titles.

I want to create an ItemList with 3 columns and have their titles visible.

`Tree` GUI componenet however, does have this functionality.

### Steps to reproduce

Create `ItemList`.  Can't create columns.

### Minimal reproduction project

None

**Comment by AThousandShips** [comment]
This should be a [proposal](https://github.com/godotengine/godot-proposals) as it's not a bug but a potentially missing feature

**Comment by ShlomiRex** [comment]
> This should be a [proposal](https://github.com/godotengine/godot-proposals) as it's not a bug but a potentially missing feature

Thanks, proposed:
https://github.com/godotengine/godot-proposals/issues/7707
