### ISSUE TITLE
Move editor debug pseudolocalization to a dev-only setting

### ISSUE THREAD

**Issue by Ferhattepe** [godotengine/godot#81794]
### Godot version

Godot Engine v4.1.1

### System information

Windows 11 OpenGl Api 3.3.0 NVIDA 537.34 - Compatibility NVIDIA - NVIDIA GeForce GTX 1650

### Issue description

When I tried to open Godot editor looks broken like this:
![image](https://github.com/godotengine/godot/assets/9110485/9e1b6ff4-5697-4a6b-8afb-ec2c16b514be)

Console logs always write "Unicode parsing error, some characters were replaced with ∩┐╜ (U+FFFD): NUL character"

![image](https://github.com/godotengine/godot/assets/9110485/2e7e7ff7-cc04-42e1-9c47-9aad206e7e83)

### Steps to reproduce

Just open Godot engine

### Minimal reproduction project

This is not about my project, about the engine

**Comment by akien-mga** [comment]
I'm afraid your Godot version is haunted. You should take it to your nearest software exorcist.

**Comment by akien-mga** [comment]
More seriously, it's actually a feature called pseudolocalization, which you may have enabled by mistake in the editor settings:

![image](https://github.com/godotengine/godot/assets/4701338/0b19a3fe-67af-4e55-91ca-5ba7267e7565)

**Comment by 457205697** [comment]
Id 457205697

**Comment by Ferhattepe** [comment]
Thanks @akien-mga this is fixed my issue.

**Comment by Calinou** [comment]
There are clearly too many cases of editor pseudolocalization being enabled by accident, so we should move it to be available in dev builds only.

**Comment by mckbdsgn** [comment]
wait so how do i undo it?
