### ISSUE TITLE
"Invalid call. Nonexistent function '_ready'" error when I call super() in child class _ready

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#81799]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Switching my project from 4.1.1 to 4.2.dev4, I can't launch it anymore.

I have a BaseClass and an InheritedClass, both implementing _ready. InheritedClass::_ready calls super().
When I launch, I have a `Invalid call. Nonexistent function '_ready'` error on the super() line.

### Minimal reproduction project

[MRP_InvalidCallNonExistentReady.zip](https://github.com/godotengine/godot/files/12643270/MRP_InvalidCallNonExistentReady.zip)

**Comment by KoBeWi** [comment]
Can't reproduce in 4df80b0

**Comment by aaronfranke** [comment]
Fixed by #81577 (merged 1 day before this issue was opened, and 5 days after dev4)
