### ISSUE TITLE
Unable to play Godot mono project in 4.2.0-dev.4

### ISSUE THREAD

**Issue by AlexMeesters** [godotengine/godot#81791]
### Godot version

4.1.1 - 4.2.0-dev.4

### System information

Windows 10 - 4.2.0-dev.4 - Any renderer

### Issue description

When trying to play the project in Godot I get the error:

`
C:\Users\Alex\.nuget\packages\godot.net.sdk\4.2.0-dev.4\Sdk\Sdk.props(40,3): error : Could not resolve SDK "Microsoft.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
  SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
  The NuGetSdkResolver did not resolve this SDK because there was no version specified in the project or global.json.
  MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.Sdk" because directory "C:\Program Files\dotnet\sdk\3.1.201\Sdks\Sdks\Microsoft.NET.Sdk\Sdk" did not exist.
Project "Clean Project Test.csproj" (Restore target(s)):
	C:\Users\Alex\.nuget\packages\godot.net.sdk\4.2.0-dev.4\Sdk\Sdk.props(40,11): error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found. [F:\Godot4Projects\CleanProjectTest\Clean Project Test.csproj]
Done building project "Clean Project Test.csproj" -- FAILED.
`

I've attempted to install dot net core 3.1.201 to see if this would resolve the issue. But no success.
It may be worth mentioning that running through Rider does actually run the application.

### Steps to reproduce

* Install Godot 4.2.0-dev.4
* Install .Net 7 as recommended for android builds
* Add C# script
* Press play in the editor

### Minimal reproduction project

Happens in any new project

**Comment by raulsntos** [comment]
Can you share the output of running the `dotnet --info` command in a console? This should let us know what SDKs and Runtimes you have installed and have been detected by .NET.

Also, if you could upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) we can check if there's something wrong with the project.

**Comment by AlexMeesters** [comment]
> Can you share the output of running the `dotnet --info` command in a console? This should let us know what SDKs and Runtimes you have installed and have been detected by .NET.
> 
> Also, if you could upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) we can check if there's something wrong with the project.

Here is the full output:

`
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
`

**Comment by AlexMeesters** [comment]
[MinimalReproductionProject81791.zip](https://github.com/godotengine/godot/files/12642735/MinimalReproductionProject81791.zip)

**Comment by raulsntos** [comment]
Are you able to build the project from the console with the `dotnet build` command? Try also removing the `.godot` directory first.

Also, can you check if you are able to build non-Godot C# projects?

**Comment by AlexMeesters** [comment]
> Are you able to build the project from the console with the `dotnet build` command? Try also removing the `.godot` directory first.
> 
> Also, can you check if you are able to build non-Godot C# projects?

dotnet build gives me the error:

`
C:\Program Files\dotnet\sdk\7.0.401\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(14,3): error MS
B4019: The imported project "C:\Program Files\dotnet\sdk\3.1.201\Sdks\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.
Common.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.2
01\Sdks\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" is correct, and that the file exists on disk.
`

Also, I've just attempted to try to do the same with 4.1.1, seems like it happens there for me too. So its not specific to this version.

**Comment by akien-mga** [comment]
If you don't need it, you could try to uninstall .NET Core 3.1 which seems to confuse .NET 7 here.

It _should_ work with multiple versions installed in theory but so far I've found the dotnet SDK resolution fairly fragile.

**Comment by AlexMeesters** [comment]
I have managed to resolve the issue. 

In my environment variables (MSBuildSDKsPath) the wrong SDK was set.
It was solved by setting the path to: "C:\Program Files\dotnet\sdk\7.0.401\Sdks"

Found the solution here: https://dev.to/jozefchmelar/microsoft-net-sdk-common-targets-was-not-found-16dm

Maybe for any future (Unity) dev running into this issue, there can be a way to circumvent this from happening?
Altough I'm unsure how common this is.

**Comment by AlexMeesters** [comment]
> If you don't need it, you could try to uninstall .NET Core 3.1 which seems to confuse .NET 7 here.
> 
> It _should_ work with multiple versions installed in theory but so far I've found the dotnet SDK resolution fairly fragile.

For now I will close the issue, since it has been resolved. 
Although it may be worth looking into ways to prevent this from being a potential issue.
