### ISSUE TITLE
Godot 4.1.1 HTML5 export doesn't run on Chrome due to "wrong" headers that are actually there and correct

### ISSUE THREAD

**Issue by Morpheu5** [godotengine/godot#81806]
### Godot version

4.1.1

### System information

macOS 13.5.2, Google Chrome 117.0.5938.88 (Official Build) (arm64)

### Issue description

I am seeing the usual notice about Cross Origin Isolation and SharedArrayBuffer prompting me to set the right headers. I do set the right headers, as confirmed on the requests through Chrome's dev tools as

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: cross-origin
```

(can't remember where I got the last one from, maybe itch.io, but it doesn't seem to make a difference if it's there or not). Anyway, this used to work until not long ago (I think 4.0 used to).

This seems to satisfy Firefox and Safari but Chrome  refuses to play ball.

### Steps to reproduce

1. Export with standard HTML5 template
2. Set headers in your preferred HTTP server

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70691.

**Comment by Morpheu5** [comment]
> I suggest hosting on a server you control, or using [godotengine/godot-proposals#6616](https://github.com/godotengine/godot-proposals/issues/6616) to avoid this kind of issues.

Just to clarify, I am indeed using a server I fully control. The only reason I mentioned itch.io is because I copy-pasted the headers from their help page, so I may have copied an extra one. I'll try the other solution, thanks, I hadn't come across it!
