### ISSUE TITLE
PackedArrays shown as <null> when made too large

### ISSUE THREAD

**Issue by Ludmuterol** [godotengine/godot#81818]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Pop!_OS 22.04 LTS - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 535.104.05) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads) - 32GB Ram

### Issue description

running following code snippet prints 200000 in the console but when i set a breakpoint on the pass line i can see the arr is set to \<null\> but the array is still usable, it just a visual bug i guess
```swift
extends Node3D

var arr :PackedInt64Array = PackedInt64Array()
func _ready():
	for i in range(200000):
		arr.push_back(0.0)
	print(arr.size())
	pass
```
![Screenshot from 2023-09-17 19-28-27](https://github.com/godotengine/godot/assets/45458713/a4c8c0fa-6e54-4d9d-b56d-3f95333d0c19)

### Steps to reproduce

Create new project
add Node3D
attach script
copy code from above
(set breakpoint on pass or print)
Run Project

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/36801.
