### ISSUE TITLE
3.0 Poly Editor settings not in Editor settings category

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8182]
In Editor settings Poly Editor is outside of Editor category :)

**Comment by TwoOfDiamonds** [comment]
Hello @n-pigeon. Can you tell me where Poly Editor is at the moment ? 
Thank you

**Comment by bojidar-bg** [comment]
@TwoOfDiamonds Search for `"editors/poly_editor/point_grab_radius"`, and you will find it, I guess.
