### ISSUE TITLE
Build works with debug version, but has warnings and produces a non-functional binary for release version on Linux Mint.

### ISSUE THREAD

**Issue by atossell91** [godotengine/godot#81835]
### Godot version

Commit hash: 4df80b0e629e25653a706f6721c13a1f9d1da368

### System information

Linux Mint 21.2, GCC 11.4.0, Scons 4.0.1, Python 3.1.12

### Issue description

I'm trying to build Godot from source. When I use the default build, i.e

    scons platform=linuxbsd

It builds just fine and the resulting binary opens and runs normally. But I'd like to build the release version, instead of the debug version. When I run this command,

    cons platform=linuxbsd target=template_release production=yes lto=full

The build goes fine until linking, then I get a ton of warnings. It does eventually produce a binary though. However when I try to run it, I get an error about a missing .pck file at path ".".

But no .pck files are created during the build stage and the docs don't seem to mention that I have to download or create them myself. Also, the debug version doesn't have this issue and opens just fine.

I've attached a file containing the warnings.

[warnings.txt](https://github.com/godotengine/godot/files/12643878/warnings.txt)

### Steps to reproduce

Just try to build, like this:

    cons platform=linuxbsd target=template_release production=yes lto=full

### Minimal reproduction project

None. I haven't made any projects yet.

**Comment by Calinou** [comment]
Closing per @Riteo's comment.

Note that the editor is only available with debugging enabled, as it *needs* debugging functionality to work. Thus, there is no `editor_release` target.
