### ISSUE TITLE
3.0 Editor Settings - Scene Tree settings are missing option for different number separator for new nodes

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8183]
Scene Tree editor settings miss option to change default separator for numbers used when duplicating nodes. It was present in 2.x.

**Comment by eon-s** [comment]
That option is now at Project Settings>Node (between GUI and Layer names)

**Comment by n-pigeon** [comment]
Ahhh... my bad was looking in wrong place ^^' Closing.
