### ISSUE TITLE
Changing case when renaming a file or folder in FileSystem doesn't work

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#81832]
### Godot version

Godot v4.1.1.stable

### System information

macOS 13.5.2

### Issue description

Renaming a file or folder with different case doesn't work

https://github.com/godotengine/godot/assets/60579014/dc0e18ef-d34c-4052-9d07-b00db7aea3fe

### Steps to reproduce

1. Create a folder in the FileSystem panel, for example "test"
2. Try to rename it to "Test"
3. Get an error message

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/19592.
