### ISSUE TITLE
Mouse Events weird when using DisplayServer.window_set_window_event_callback

### ISSUE THREAD

**Issue by mournguard** [godotengine/godot#81830]
### Godot version

4.2 dev 4

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)

### Issue description

I have an issue that starts from 4.2 dev 4 and up where the mouse_entered/exited events just not trigger and after a bit of initial confusion I understand it comes from using `DisplayServer.window_set_window_event_callback`.

Now I might just be using that wrong but yeah basically it seems like you can't use your own callback anymore, I'm not sure. 

It might be related to #80334 ?

### Steps to reproduce

Check the script and toggle line 4.

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/12643757/mrp.zip)

**Comment by wouldntsavezion** [comment]
Note that the mrp doesn't even add any mouse_entered/exited events because this also breaks the base mouse over style switch from button.

**Comment by Calinou** [comment]
cc @Sauermann

**Comment by Sauermann** [comment]
Can confirm this on Linux.

As a workaround, instead of using `DisplayServer.window_set_window_event_callback` for accessing the window-events, you could overwrite the `_notification` function in the `Window`. 
A demo for how to do that for the root-window is available in: [RootSizeChange.zip](https://github.com/godotengine/godot/files/12022068/RootSizeChange.zip)

@mrTag You seem to experience a different bug. If you can provide a minimal reproduction project for that bog, it would be good, if you could open another bug-report for it.

**Comment by wouldntsavezion** [comment]
Thanks I'll try to set that up. Looks like it's a much better way to do it anyway !

**Comment by wouldntsavezion** [comment]
> As a workaround, instead of using `DisplayServer.window_set_window_event_callback` for accessing the window-events, you could overwrite the `_notification` function in the `Window`. A demo for how to do that for the root-window is available in: [RootSizeChange.zip](https://github.com/godotengine/godot/files/12022068/RootSizeChange.zip)

Thanks I'll try to set that up. Looks like it's a much better way to do it anyway.

**Comment by mrTag** [comment]
> @mrTag You seem to experience a different bug. If you can provide a minimal reproduction project for that bug, it would be good, if you could open another bug-report for it.

That was also what I thought and I could easily reproduce it in a simple fresh project. Here is the issue, @Sauermann : https://github.com/godotengine/godot/issues/81909
