### ISSUE TITLE
Using C# and Visual Studio Code doesn't recognize Global Variables created with Project Settings AUTOLOAD

### ISSUE THREAD

**Issue by edwit1971** [godotengine/godot#81840]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11 Pro

### Issue description

I created 2 Global Variables (AManager and DManager) inside AutoLoad in the Project Settings and ENABLED the Global Variable checkbox (which was enabled by default.)  But in any of my scripts attached to child Nodes of the Node attached to the Script containing the Global Variable Script, Visual Studio Code is highlighting either AManager or DManager references and saying the name doesn't exist in the current context.

### Steps to reproduce

Just open the Script files in Visual Studio Code and you'll see the Global Variables are marked as errors and they shouldn't be.

### Minimal reproduction project

[AutoLoad_Error.zip](https://github.com/godotengine/godot/files/12644076/AutoLoad_Error.zip)

**Comment by raulsntos** [comment]
That's not how C# works. If you want to access the autoloads you have to use `GetNode`:

```csharp
var dmanager = GetNode<DataManager>("/root/DManager");
```

Have you read the [_Singletons (Autoload)_](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html) documentation page? It's documented that this only applies to GDScript but maybe it's not clear enough.

**Comment by edwit1971** [comment]
@raulsntos Thank You. I did need to say:

var dManager = GetNode<DataManager>("/root/DManager");

That fixed the global variable being shown as an error by Visual Studio Code. However, DManager is not being created globally by AutoLoad as a node.

When I figure this out I will update here to show how I fixed it. I think I still might not know how to do this properly.

**Comment by raulsntos** [comment]
Your MRP is missing the `project.godot` file, but setting the autoloads like the documentation shows should instantiate them.

What makes you think that `DManager` is not being instantiated? What does the Scene Tree contain when running the game? You can check using the _Remote_ tab:

![image](https://github.com/godotengine/godot/assets/3903059/e81a6b7f-af78-4632-8b36-197a1f1fa379)

**Comment by edwit1971** [comment]
Okay this is the updated Project for this and everything works.
You are supposed to hit the REMOTE button during run-time to verify that DManager is created Globally.
I didn't know that.
https://github.com/edwit1971/AutoLoad
