### ISSUE TITLE
OpenXR can't find a viewport (can't mark one/dont know how)

### ISSUE THREAD

**Issue by InfGame** [godotengine/godot#81842]
### Godot version

4.1.1.stable.mono

### System information

Windows 11, XR Device: Valve index (steamVR), Programming language used: C#

### Issue description

I have switched over from unity since their whole pricing drama stuff and I have been trying stuff out and slowly getting used to the editor.

tho one thing i can't get working is OpenXR. this is pretty essential to me since i am mainly a VR game developer.

It sems like open XR is strying to find some kind of viewport since I am getting this error constantly: 
`OpenXR: No viewport was marked with use_xr, there is no rendered output!`

However when trying to search for "how to mark a viewport" i can't find an explanation anywhere to my problem.

Wierdly enough the head tracking and controller tracking seems to be working fine since I can see it in the desktop viewport. but there is no output to the headset.

I hope you can help me with this. thank you.

### Steps to reproduce

set up a small scene with a XROrigin, XRCamera and controllers.

have a script on the root note with this code in it:

```csharp
using Godot;
using System;

public partial class player : Node3D
{
    XRInterface xrInterface { get; set; }
    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        xrInterface = XRServer.FindInterface("OpenXR");

        if (xrInterface != null && xrInterface.IsInitialized())
        {
            GD.Print("XR Interface initialized and ready");

            DisplayServer.WindowSetVsyncMode(DisplayServer.VSyncMode.Disabled);

            GetViewport().UseXR = true;
        }
    }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
    public override void _Process(double delta)
	{
	}
}
```

Try to run it with the headset connected. tracking is working fine and there is an output on the desktop but the HMD remains black.

### Minimal reproduction project

[Reproduction_project.zip](https://github.com/godotengine/godot/files/12644485/Reproduction_project.zip)

**Comment by Chaosus** [comment]
cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
The code that should be enabling xr on the main viewport is `GetViewport().UseXR = true;`, is that getting executed? The script looks correct as far as I can see but I haven't tested C# myself.

**Comment by InfGame** [comment]
@BastiaanOlij I have a `GD.Print` in place to check that. seems like it does not appear to pop up in the console tho. Is there a way i can activate debugging using my external text editor (Visual studio)?

**Comment by InfGame** [comment]
Got it to work after a bit. it seems like the project didn't save right and it was still using a script i deleted a bit ago. fixed it by reassigning the script. ty for your help.

**Comment by BastiaanOlij** [comment]
@InfGame glad you found it, interesting that it would grab a cached version. I had asked some of the guys on the XR discord to look at it. 

Just in case you're not aware of it, please join the Godot Discord (https://godotengine.org/community/), we have an XR channel there where a lot more people are able to help out.
