### ISSUE TITLE
4.2-dev4 C# export to Android generates the APK fine, but fails finding .NET assemblies for arm64 at runtime

### ISSUE THREAD

**Issue by Oyama-Oyama** [godotengine/godot#81852]
### Godot version

4.2 dev 4

### System information

mac 12.6.7

### Issue description

![Screenshot_2023-09-20-15-48-42-963_org godotengine godot](https://github.com/godotengine/godot/assets/17978212/186c802d-e33e-49a6-a002-4683deefb3a4)
Why is this? What can I do to fix it?

### Steps to reproduce

.

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/12645613/godot.zip)

**Comment by akien-mga** [comment]
I assume you're actually testing **4.2** dev 4? 4.1 doesn't support Android for C# exports.

**Comment by raulsntos** [comment]
Your MRP doesn't contain a C# project.

**Comment by arnilsenarthur** [comment]
The same thing here, i cant build the project:

C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-arm64 with version (= 6.0.18)
       C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102:   - Found 24 version(s) in nuget.org [ Nearest version: 7.0.0-preview.5.22301.12 ]
       C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

And i cant install the nuget either cause it's not compatible with the project.
OS: WINDOWS 11

**Comment by arnilsenarthur** [comment]
Justing to give more information:
I'm using godot 4.2.dev4-mono
.net7.0 as recommended

Error:
       "C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj" (Restore target) (1) ->
       (Restore target) -> 
         C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-arm64 with version (= 6.0.18)
       C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102:   - Found 24 version(s) in nuget.org [ Nearest version: 7.0.0-preview.5.22301.12 ]
       C:\Users\AORUS\Documents\MyRPGGodot\MyRPG-Godot.csproj : error NU1102:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

    0 Warning(s)
    1 Error(s)

I can't build any architectures of android apk

**Comment by raulsntos** [comment]
> So it might be the old issue where exporting a non-C# project with a .NET enabled build still tries to initialize .NET but doesn't copy the libraries?

I slightly remember something like that but I can't find the issue now, I don't remember if it was resolved. It shouldn't copy any .NET libraries if there is no C# project, but then the exported project shouldn't attempt to load them, otherwise you can't export GDScript-only projects from the .NET version (this will become more important with _Editor unification_, maybe https://github.com/godotengine/godot/pull/74089 already solves this).

---

@arnilsenarthur You have to target .NET 7.0. Change `<TargetFramework>net6.0</TargetFramework>` in the .csproj file to `<TargetFramework>net7.0</TargetFramework>` and make sure you have the 7.0 SDK installed. Also, I believe only arm64 works at the moment.

**Comment by arnilsenarthur** [comment]
Not even arm64 works for me, but after I added <UseMonoRuntime>true</UseMonoRuntime> it worked, but the app open then crashes

**Comment by arnilsenarthur** [comment]
Not even arm64 works for me, but after I added <UseMonoRuntime>true</UseMonoRuntime>it worked, but the app open then crashes

**Comment by arnilsenarthur** [comment]
I already did this and still not worked.
after i added `<UseMonoRuntime>true</UseMonoRuntime>` it worked, but the app opens, then turn black and crashes.
tested on android device emulator and on a real device

**Comment by arnilsenarthur** [comment]
Yep, i give up by now. I created a empty project in a non-mono godot version then it installed and worked with no problems. but even an empty mono android project does not work

**Comment by rekliner** [comment]
Same experience here with the unmodified XR Tools demo and 4.2dev4.  Loads ok non-mono.  As you suspected @raulsntos I had not added any C# code yet.

**Comment by arnilsenarthur** [comment]
Using android studio log i tried to understand what's wrong and seems something about vulkan, but i'm not sure. 
I asked at discord if it's viable to use C# in a project aiming to launch it to mobile/desktop by december or should I just use gdscript, even when if i need to rewrote some code, I'll wait for the answer and halt my production for a while. But anyway if you need more info about the issue just ask  and I'll send it here

**Comment by sanform** [comment]
I'm seeing the same error in my project. I'm using the PlayFab C# SDK. It seems to happen on a call to that library.
