### ISSUE TITLE
Why does `PacketPeerStream::put_data` also explicitly prepends the size of the buffer

### ISSUE THREAD

**Issue by Dantsz** [godotengine/godot#81856]
### Godot version

v4.2.dev.custom_build [5f1e56ff2]

### System information

Godot v4.2.dev (5f1e56ff2) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 Threads)

### Issue description

I wanted to use godot with an external server but couldn't decide on TCP or UDP, found TCP uses StreamPeer while UDP uses PacketPeer. 

I found PacketPeerStream which adapts a stream to work like a PacketPeer, but found out the packets bewteen UDP and TCP where different.

Looking into it, `PacketPeerStream::put_data` method also prepends 4 bytes to the packet representing the size of the buffer, this is unlike the behavior of PacketPeerUDP.
The code:
```
Error PacketPeerStream::put_packet(const uint8_t *p_buffer, int p_buffer_size) {
	ERR_FAIL_COND_V(peer.is_null(), ERR_UNCONFIGURED);
	Error err = _poll_buffer(); //won't hurt to poll here too

	if (err) {
		return err;
	}

	if (p_buffer_size == 0) {
		return OK;
	}

	ERR_FAIL_COND_V(p_buffer_size < 0, ERR_INVALID_PARAMETER);
	ERR_FAIL_COND_V(p_buffer_size + 4 > output_buffer.size(), ERR_INVALID_PARAMETER);

	encode_uint32(p_buffer_size, output_buffer.ptrw()); //! also writes the p_buffer_size to the buffer!!!
	uint8_t *dst = &output_buffer.write[4];
	for (int i = 0; i < p_buffer_size; i++) {
		dst[i] = p_buffer[i];
	}

	return peer->put_data(&output_buffer[0], p_buffer_size + 4);
}
```

Is this intentional? If it is, I couldn't find a reference for it.
The `get_packet` function intentionally discards them, and seems to use another 4 bytes from before the packet one (but that encoded size does not includes the 4 bytes?, I am probably reading it wrong)
```
...
	ring_buffer.read(lbuf, 4); //get rid of first 4 bytes
	ring_buffer.read(input_buffer.ptrw(), len); // read packet

	*r_buffer = &input_buffer[0];
	r_buffer_size = len;
	return OK;
}
```

### Steps to reproduce

You can use the script in the following section paired with a  project to listen to the raw packet.

### Minimal reproduction project

Godot test node script:
```
extends Node2D

var _stream: StreamPeer = StreamPeerTCP.new();
var _packet_peer : PacketPeer;

# Called when the node enters the scene tree for the first time.
func _ready():
	if _stream.connect_to_host("127.0.0.1",3000) != Error.OK:
		print("failed to connect to server")
		return
	while _stream.get_status() != StreamPeerTCP.STATUS_CONNECTED:
		_stream.poll()
	var player_movement = get_node("Player/CharacterBody2D")
	player_movement.connect("movement_change",on_player_move)
	_packet_peer = PacketPeerStream.new()
	_packet_peer.stream_peer = _stream
			
func on_player_move(velocity : Vector2): 
	#_stream.put_data(("%s,%s" % [velocity.x , velocity.y]).to_ascii_buffer())
	var buffer := PackedByteArray(("%s,%s" % [velocity.x , velocity.y]).to_ascii_buffer())
	_packet_peer.put_packet(buffer)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass```

**Comment by timothyqiu** [comment]
About the difference between `put_data()` and `put_packet()`:

* `put_data()` is from `StreamPeer` and it has no concept of "packet".
* `put_packet()` is from `PacketPeer` and the format of a packet is implementation detail I believe.

About UDP has no leading packet size:

* TCP handles data streams. You may ask it to send a 100-byte packets twice, and the receiver might receive 128 bytes the first time it asks TCP to receive something, and receive the remaining 72 bytes the second time. So code interacting with raw TCP need to mark packet boundaries, thus packet size is prepended.
* UDP works differently. It either sends the data in one go or fails. And the receiver either receives what you send as-is or completely miss it. So there's no need to encode the packet size.
