### ISSUE TITLE
TextureButton and TextureRect have no way to set a maximum size

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8185]
In godot 2 I could somewhat set a maximum size in the TextureButton and TextureRect equivalents, this functionality looks to be lost in godot 3.0, My images are higher resolution than they need to be and so the TextureButton and TextureRect expands to be as big as my texture, instead of making my texture fit into the area I want.

I suspect the size of the canvas is being set to the texture size regardless of the size I am setting in the editor as I have tried a number of Stretch Modes, but all result in the same incorrect size.

**Comment by Gibbz** [comment]
Yes i've noticed this cannot be resized smaller than the source image anymore. So trying to get the image to scale down with the parent for example does not work.
The scale values also don't work. I guess these are all the same or related issue.

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
