### ISSUE TITLE
The engine interface not reflecting real values on Tilemap (not sure about other nodes)

### ISSUE THREAD

**Issue by Tugay72** [godotengine/godot#81863]
### Godot version

v4.1.1.stable

### System information

Windows 11 - Vulkan API 1.3.224 - Forward+ - NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

https://github.com/godotengine/godot/assets/101458041/6a499ed4-8c89-4486-a0ea-1a516e559d35

For a while I thought that was a position issue and couldn't find a solution then suddenly saw the reset button on "Scale". I think I accidently used scale mode while trying to save project. The "X" value probably was something like <1E-10 . Is this an issue? Am I missing something? or that is how is supposed to be? It's not a big problem, but it can sometimes cause confusion for new users, in my opinion the values are far more noticeable than reset button.

### Steps to reproduce

Select "Tilemap" node then use "Scale Mode" or press "S" then scale the tilemap a little bit.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
The inspector has a limited precision. If fractional part is very small (e.g. 0.00001) it's not displayed.
You can change the default precision in project settings.
