### ISSUE TITLE
TileSet cell grid has incorrect resolution.

### ISSUE THREAD

**Issue by Pugsworth** [godotengine/godot#81876]
### Godot version

4.1.1 stable (Steam)

### System information

Godot v4.1.1.stable - Windows 11.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

This is a rather weird one to me.

I have a 768px by 256px atlas of 16x16 tiles with zero padding or offset.
When I add the atlas image to the TileSet, the editor believes that the texture is actually four times bigger than it actually is. If I set both the [Tile Size] of the TileMap and [Texture Region Size] of the TileSet to 16x16, the editor shows a grid of 4x4 tiles as shown in this image.
![image](https://github.com/godotengine/godot/assets/2857928/992b0462-b819-49db-87a2-d9c2ba1427dd)

Now, if I instead set it to 64px by 64px, the grid is correct and painting terrain is correct. However, the image is then a little blurred as if there's some up scaling happening. (Zoom in, resized to not take up a lot of room in this post.)
<img src="https://github.com/godotengine/godot/assets/2857928/db9f18e6-7aec-494d-9791-e1c3c9fc3720" width="64"/>

This specific texture I'm using is 768px by 256px. I have tried to make it a square power of two texture at 1024px by 1024px. I've tried changing the image parameters when saving: removing the alpha channel, changing compression, etc.

Strangely, this bug doesn't present itself with another atlas that's only a 2x2 TileSet of 32px by 32px image.

### Steps to reproduce

- Create new Godot 4.1 Project
- Create 2D scene.
- Add TileMap node.
- In the inspector, add a new TileSet.
- Drag the image to the the TileSet editor to create a new one.
- Observe how it shows four times as many cells as it should.

### Minimal reproduction project

[Test_TileSet_Bug.zip](https://github.com/godotengine/godot/files/12651401/Test_TileSet_Bug.zip)

**Comment by KoBeWi** [comment]
But your tiles *are* 64x64...

**Comment by Pugsworth** [comment]
> But your tiles _are_ 64x64... The tileset you attached has 4x4 "pixels".

You are so right...

While editing the image, I must have forgotten that the image was scaled, even though it looked pixelated.
I feel pretty dumb for not checking that.

There seems to not actually be a bug here then, just smooth-brain.
