### ISSUE TITLE
Path3D Up Vector miscalculation

### ISSUE THREAD

**Issue by crmsncreates** [godotengine/godot#81879]
### Godot version

v4.2.dev4.mono.official [549fcce5f]

### System information

Godot v4.2.dev4.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3619) - Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz (20 Threads)

### Issue description

Since somewhere around 4.1, when a point on a Path3D is moved on the Y-axis, it flips itself and all points after it upside-down:
![image](https://github.com/godotengine/godot/assets/37983284/bb05a5f2-467e-49c8-8d82-fce8cdb420d7)

Moving one of the points that come before it on the X-axis seems to fix the problem?
![image](https://github.com/godotengine/godot/assets/37983284/57f167b3-efd7-4877-bea4-b1aae6ae9c00)

Though even this seems to have a few errors here and there: (from the repro project)
![record](https://github.com/godotengine/godot/assets/37983284/f6bc42ae-8033-44bf-bb98-279390ef3c99)

Expected no flipping, as it worked in previous versions such as v4.0.3.stable.mono.official [5222a99f5] here:
![image](https://github.com/godotengine/godot/assets/37983284/608e7bb4-7425-4263-b8ee-088f4db9d4ff)

### Steps to reproduce

1. Create a Path3D
2. Add 2 points at the same Y position
3. Move one of them on the Y-axis

### Minimal reproduction project

[PathBug.zip](https://github.com/godotengine/godot/files/12652576/PathBug.zip)

**Comment by rmmh** [comment]
The repro project let me bisect this to 42aa5398d951dc709c892ef9f7afef6a0cf5d9ca, part of #72842.

The changes to curve.cpp look relevant. 

@TokageItLab, can you have a look?

**Comment by kleonc** [comment]
> The repro project let me bisect this to [42aa539](https://github.com/godotengine/godot/commit/42aa5398d951dc709c892ef9f7afef6a0cf5d9ca), part of #72842.
> 
> The changes to curve.cpp look relevant.

Looking at these changes I think this line:
https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/scene/resources/curve.cpp#L1686
should have also been changed to accomodate the changed direction, specifically to something like:
```cpp
rotate.rotate_to_align(-frame_prev.get_column(2), forward);
```
as `-Z` basis vector should be now interpreted as forward.

(Haven't tested it at all, just looked at the changed code.)

**Comment by rmmh** [comment]
> Looking at these changes I think this line:
> 
> https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/scene/resources/curve.cpp#L1686
> 
> 
> should have also been changed to accomodate the changed direction, specifically to something like:
> ```c++
> rotate.rotate_to_align(-frame_prev.get_column(2), forward);
> ```

This fixes the repro case, I can try to figure out a regression test and make a PR?
