### ISSUE TITLE
Custom Sky Shader performance issue

### ISSUE THREAD

**Issue by vars1ty** [godotengine/godot#81871]
### Godot version

v4.1.1.stable.flathub [bd6af8e0e]

### System information

Arch Linux - Vulkan - Forward+ - AMD RX 6800 XT - i7 12700k

### Issue description

If you use the `TIME` float in a sky shader, locked behind an if-statement, the shaders performance drops, even if the if-statement isn't being executed.

### Steps to reproduce

1. Download the attached sample project with the custom shader
2. Check the visual profiler (and stdout) with clouds on
3. Remove the clouds code in the shader and save
4. Repeat Step 2 and notice performance being much better

### Minimal reproduction project

[SkyShaderPerf.zip](https://github.com/godotengine/godot/files/12649522/SkyShaderPerf.zip)

**Comment by Calinou** [comment]
This is because the sky and its radiance map need to be updated continuously when you use `TIME`. Godot cannot know whether your `if` statement will ever be reached, so it will consider the sky to be real-time.

> AFAIK many graphics cards execute both sides of an if before discarding the unused one.

They don't execute both branches, but registers are allocated for both branches. This can impact performance negatively.

**Comment by clayjohn** [comment]
Quoting from the docs: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/sky_shader.html

> When using the sky shader to update the radiance cubemap, the sky shader will be called for every pixel in the cubemap. On the other hand, the shader will only be called when the radiance cubemap needs to be updated. The radiance cubemap needs to be updated when any of the shader parameters are updated. For example, if TIME is used in the shader, then the radiance cubemap will update every frame. The following list of changes force an update of the radiance cubemap:
> 
> - TIME is used.
> 
> - POSITION is used and the camera position changes.
> 
> - If any LIGHTX_* properties are used and any [DirectionalLight3D](https://docs.godotengine.org/en/latest/classes/class_directionallight3d.html#class-directionallight3d) changes.
> 
> - If any uniform is changed in the shader.
> 
> - If the screen is resized and either of the subpasses are used.
> 
> Try to avoid updating the radiance cubemap needlessly. If you do need to update the radiance cubemap each frame, make sure your [Sky process mode](https://docs.godotengine.org/en/latest/classes/class_sky.html#class-sky-property-process-mode) is set to [REALTIME](https://docs.godotengine.org/en/latest/classes/class_sky.html#class-sky-constant-process-mode-realtime).
