### ISSUE TITLE
Texture filter is changing itself when resizing window

### ISSUE THREAD

**Issue by honix** [godotengine/godot#81880]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11, NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

The 2d or 3d sprites changing it's texture filter to nearest when window resize occurs. The problem seen when using "compatability" renderer.

### Steps to reproduce

1. Create a scene
2. Create a Sprite2d or Sprite2d
3. Attach an texture to it (godot logo for example)
4. Start the scene
5. Resize or fullscreen the window

### Minimal reproduction project

The repro is pretty easy. But can do if needed.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/81676, as this is fixed in 4.2.dev4.
