### ISSUE TITLE
Removal of C# MaterialOverride Functions

### ISSUE THREAD

**Issue by MangoDragonHub** [godotengine/godot#81882]
### Godot version

4.1.1 Stable

### System information

Tuxedo OS 2 (Ubuntu 22.04),  Vulkan Forward+ Renderer

### Issue description

I'm trying to make a character expression atlas and test to see if it can scroll through them. Apparently when I go to try and access the Albedo and UV coordinates of the Material it seems like those functions are not in the library. Were they removed or they were placed in another Node Class?

### Steps to reproduce

Just type in _Mesh.GetOverrideMaterial(). and all specific functions that only tied to Materials isn't available
![Screenshot from 2023-09-18 15-05-03](https://github.com/godotengine/godot/assets/7853845/364892c5-8249-4e4d-9b83-18889d155792)
,

### Minimal reproduction project

[DebugTest.zip](https://github.com/godotengine/godot/files/12653809/DebugTest.zip)

**Comment by bitsawer** [comment]
The type of `GeometryInstance3D.MaterialOverride` is `Material`, which does not have `AlbedoTexture` property. You need to cast it to `BaseMaterial3D`, `StandardMaterial3D` or similar to access them (assuming you have set the correct material type in that field in the first place).

**Comment by MangoDragonHub** [comment]
This is never explained in the manual. How do you get access to all the individual properties of that material?

**Comment by Calinou** [comment]
> How do you get access to all the individual properties of that material?
Cause even if you do cast a variable as a Material, you will still not get access to those elements.

You need to cast to BaseMaterial3D, as Material doesn't have a concept of an albedo texture in the first place.

**Comment by bitsawer** [comment]
See https://docs.godotengine.org/en/stable/classes/class_geometryinstance3d.html#class-geometryinstance3d-property-material-override and then https://docs.godotengine.org/en/stable/classes/class_material.html#class-material and **Inherited By** section.

Looks like you stored a `StandardMaterial3D` into the override slot in the editor inspector UI, so you need to cast the material into StandardMaterial3D type first if you want to access it's values in code. There are many types of materials, so you need to know which you are using. It's no different than setting and accessing any other type.

Probably something like this in C# (not tested or even compiled):

```
StandardMaterial3D material = (StandardMaterial3D)_mesh.MaterialOverride;
material .AlbedoTexture = VALUE;
```

**Comment by MangoDragonHub** [comment]
Okay, I'm getting the function now. Even so, I wouldn't have figured out recasting my Material variable again since the documentation for [Materials](https://docs.godotengine.org/en/stable/classes/class_material.html#class-material) doesn't mention any functions allowing to access individual parameters.
