### ISSUE TITLE
Object-less callables rejected by `Object::connect` et al

### ISSUE THREAD

**Issue by maiself** [godotengine/godot#81887]
### Godot version

master, e3e2528ba7f6e85ac167d687dd6312b35f558591

### System information

linux

### Issue description

Creating this issue to keep track of something discovered while working working on #79005.

Basically, in some places Godot has checks for `object` as a way to check if a callable is valid. This seems wrong, especially for custom callables, which may not actually have an associated object. While this doesn't seem to be a problem within the engine itself, it can be a problem for extensions. In my extension I had to use a [workaround](https://github.com/maiself/godot-python-extension/blob/master/src/variant/callable.cpp#L12) that creates an object that exists for no reason other than to pass those checks.

Here are some examples of object-less callables being rejected:

- [`Object::emit_signalp`](https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/core/object/object.cpp#L1100)
- [`Object::connect`](https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/core/object/object.cpp#L1303)
- [`Object::_disconnect`](https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/core/object/object.cpp#L1388)

I haven't looked to see if there are more cases (I merely searched `object.cpp` for `get_object()`). 

Original comments from #79005:
- https://github.com/godotengine/godot/pull/79005#issuecomment-1724109784
- https://github.com/godotengine/godot/pull/79005#issuecomment-1724579955

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Mickeon** [comment]
Does *simply* removing the check for a valid object completely fix this or is there something more going on?

**Comment by dsnopek** [comment]
> Does _simply_ removing the check for a valid object completely fix this or is there something more going on?

I think we probably want to replace those checks with `callable.is_valid()`.

The examples in the description seem to be doing their own manual version of a validity check by checking `callable.get_object()`. However, there's several types of callables, some of which are perfectly valid without objects (and those should have overridden `is_valid()`).

If I had to guess what happened here, maybe there didn't used to be a `is_valid()` function (so checking `get_object()` made sense), but after adding `is_valid()` some bits of the code didn't get updated?
