### ISSUE TITLE
cannot compile godot using msvc

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8189]
**Operating system or device - Godot version:**
visual studio community 2015 - windows 10 - godot 3.0

**Issue description:**

compiling always terminated due to errors (compiling via mingw works fine though)

**Steps to reproduce:**
tried to use vs2015 x64 native tools command prompt and cross tools and both have failed

**Link to minimal example project:**

**Comment by CharlesWoodhill** [comment]
vstudio 2015 - windows 7 - godot 3.0
using msvc
have no problems, beside of this new 2xxx warnings :)

**Comment by Ahmed0425** [comment]
@CharlesWoodhill 
> beside of this new 2xxx warnings :)
Indeed, there is lots and lots of warnings -_-
can you tell me what command prompt did you use? I've might used the wrong command prompt

**Comment by CharlesWoodhill** [comment]
im using:
`echo Starting SCons && cmd /V /C set "warings=no plat=$(PlatformTarget)" ^& (if "$(PlatformTarget)"=="x64" (set "plat=x86_amd64")) ^& set "tools=yes" ^& (if "$(Configuration)"=="release" (set "tools=no")) ^& call "$(VCInstallDir)vcvarsall.bat" !plat! ^& scons platform=windows target=$(Configuration) tools=!tools! -j2`

**Comment by Ahmed0425** [comment]
I did use the wrong command prompt
fixed by using "x64 x86 Cross Tools" and "x86 x64 Cross tools"

closed .

**Comment by karroffel** [comment]
@Ahmed0425 can this isse be closed then?

**Comment by Ahmed0425** [comment]
I wish to do but I'm new at dealing with github
