### ISSUE TITLE
It is not possible to run a c# script via command line in Windows 11 + Godot mono, the given error is always "Cannot instance script because the associated class could not be found"

### ISSUE THREAD

**Issue by ColtonRamos** [godotengine/godot#81894]
### Godot version

v4.1.1.stable.mono.official

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

**It is possible to run .gd scripts in a godot project folder via command line (using -s or --script argument), but not .cs scripts, as they fail with the error mentioned in the title and below.**

```
ERROR: Cannot instance script because the associated class could not be found. Script: 'res://SayHello.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
   at: (modules/mono/csharp_script.cpp:2388)
```

This bug occurs when trying to interpret and follow the command line tutorial in the official Godot documentation using C#:  https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html#running-a-script

I found a couple posts online touting a similar error in other contexts, but never any mention of the error occurring while running a command with -s, which seems like an obvious use case to me. This issue will affects users trying to automate parts of development involving libraries and source code written in C#.

### Steps to reproduce

**Repro steps**
1. Download Godot mono v4.1.1
2. Add the downloaded folder to Windows PATH environment variables, found in the Control Panel
3. Create a new empty Godot project
4. Add a "sayhello.gd" script to the project:
```
#!/usr/bin/env -S godot -s
extends SceneTree

func _init():
	print("Hello!")
	quit()
```
5.  Add a "SayHello.cs" script to the project:
```
using Godot;
using System;

public partial class SayHello : SceneTree
{
	public override void _Initialize()
	{
		GD.Print("Hello!");
	}
}
```
6.. Open a command line and navigate to the project directory.
7. Attempt to run the following command via the command line and note that this script works:
`Godot_v4.1.1-stable_mono_win64.exe -s sayhello.gd`
8. Attempt to run the following command via the command line and note that this script fails with the aforementioned error:
`Godot_v4.1.1-stable_mono_win64.exe -s SayHello.cs`

**Expected behavior:** The output of the two scripts ran from the command line should be the same.
**Actual behavior:** The .cs script fails to execute, giving the following error:
```
ERROR: Cannot instance script because the associated class could not be found. Script: 'res://SayHello.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
   at: (modules/mono/csharp_script.cpp:2388)
```

![image](https://github.com/godotengine/godot/assets/61305839/bac8bcee-6ff2-472e-9736-db63bce53144)

Other things of note:
 - Rebuilding the C# solution/project with Project => Tools => C# => Create C# Solution did not help.
 - I have verified the "EnableDynamicLoading" property is present in the .csproj `<EnableDynamicLoading>true</EnableDynamicLoading>`

### Minimal reproduction project

[Cmd.zip](https://github.com/godotengine/godot/files/12655283/Cmd.zip)

**Comment by ColtonRamos** [comment]
Oh, also: I've tried this with the project open and closed in Godot, and restarted Godot multiple times. Open/close/restart doesn't seem to matter, either.

**Comment by akien-mga** [comment]
C# is a compiled language, so you need to compile the script before you can execute it.

You do this in the editor by pressing the "Build" button in the top right corner (or it happens automatically when you press "Run").

From the command line, you can also just run `dotnet build` to compile the solution.

I've tested and confirmed this solves the issue.
