### ISSUE TITLE
[2.1] Scaling Issue on 96x96 display.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8190]
**Operating system or device - Godot version:**
Godot v2.1.2, on Fedora 25 Workstation.

**Issue description:**

Opening 'Godot v2.1.2' on Fedora 25 Workstation via a 96x96 display, leads to significant scaling issues; This seems to effect the version found on Steam, the akien/godot Copr Repo, & compiling from source.

![Project selector.](https://cloud.githubusercontent.com/assets/26415691/24433419/288121cc-13ee-11e7-85a9-12526e7211d7.png)
![Main screen.](https://cloud.githubusercontent.com/assets/26415691/24433422/307dc06a-13ee-11e7-99ec-831943baa4e3.png)

**Steps to reproduce:**
1. Open Godot.

**Comment by akien-mga** [comment]
It should be fixed if you compile the 2.1 branch from source, can you confirm?

**Comment by akien-mga** [comment]
It should be fixed if you compile the 2.1 branch from source, can you confirm?

Or you can test the 2.1.3 RC1 binaries too: http://download.tuxfamily.org/godotengine/2.1.3/rc1/

**Comment by bojidar-bg** [comment]
Bump, seems like author disappeared from github..

**Comment by akien-mga** [comment]
Should be fixed in 2.1.3.
