### ISSUE TITLE
Capturing a variable in a Callable prevents assembly unloading

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#81903]
### Godot version

4.1.1

### System information

Windows 10 / Windows 11

### Issue description

Constructing a `Callable` from an anonymous function that captures a variable prevents the assembly unloading and triggers #78513.  

Keep in mind this is currently our only way of handling bound values on `Callable` in the C# API.

### Steps to reproduce

The following script is a simple example of the issue.  
Basically:
- Have a script use a `Callable` where a variable gets captured.
- On solution rebuild, the error will show up.

```cs
[Tool]
public partial class Scene : VBoxContainer
{
	public override void _Ready()
	{
		for (var i = 0; i < 4; ++i)
		{
			var button = new Button
			{
				Text = $"Click me!",
			};

			// This will prevent unloading.
			var buttonIndex = i;
			button.Connect(Button.SignalName.Pressed, Callable.From(() => WhenButtonClicked(buttonIndex)));

			AddChild(button);
		}
	}

	private void WhenButtonClicked(int buttonIndex)
	{
		GD.Print($"Button #{buttonIndex} was clicked!");
	}
}
```

Note that, if `WhenButtonClicked` didn't take an argument, and `buttonIndex` wasn't captured, the unloading would occur just fine.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12656876/MRP.zip)

**Comment by ttencate** [comment]
Confirmed, commenting out the `checkBox.Toggled` handler in this function fixed it for me:

```cs
    private void BindCheckbox(string nodeName, Func<bool> getter, Action<bool> setter)
    {
        var checkBox = GetNode<CheckBox>(nodeName);
        checkBox.ButtonPressed = getter();
        checkBox.Toggled += (on) =>
        {
            setter(on);
            UpdateView();
        };
    }
```
