### ISSUE TITLE
Process time spikes constantly in empty project

### ISSUE THREAD

**Issue by polylemtea** [godotengine/godot#81908]
### Godot version

4.1.1 official

### System information

Fedora 38, Forward+/Mobile/Compatibility, intel i7-9750H, nvidia gtx 1660ti(laptop)

### Issue description

The process time weirdly jumps back and forth in every project, with Forward+, Mobile and Compatibility renderers.  
Normally it's around 8ms, but it constantly spikes to 20-28ms, causing the project cannot reach a stable 144 FPS.
  
![screenshot](https://github.com/godotengine/godot/assets/124504469/de1e2be0-32fc-4c47-8a93-fe7c098074c1)  

The project exported with release mode have similar behavior, but with a lower frequency:  

![out](https://github.com/godotengine/godot/assets/124504469/1ee290e9-aff4-45f9-be2f-269b80a23e19)

Tested with code:  
```gdscript

extends Node2D

func _ready():
	var timer := Timer.new()
	add_child(timer)
	timer.start()
	timer.timeout.connect(print_msg)

func print_msg():
	print(Performance.get_monitor(Performance.TIME_PROCESS) * 1000, " ms, ",
		Performance.get_monitor(Performance.TIME_FPS), " fps")
```

### Steps to reproduce

1. Create a new project
2. Run and see profile window

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12657837/test.zip)

**Comment by polylemtea** [comment]
> Printing to stdout can cause performance spikes if you have a terminal displaying the output, due to X11 stalling to display the updates.

I tried to display the frame time and fps by a label in game, also disable stdout in project settings after deleting the print code, and run the game without a terminal, but the issue still persist.

Here's an updated MRP, but I didn't add a way to view the history frame time, so it might be a little bit hard to discover.

[test.zip](https://github.com/godotengine/godot/files/12661628/test.zip)

**Comment by Calinou** [comment]
Are you using a X11 or Wayland session? Use `echo $XDG_SESSION_TYPE` to know.

Also, can you reproduce this when running the project in fullscreen?

**Comment by polylemtea** [comment]
> Are you using a X11 or Wayland session? Use `echo $XDG_SESSION_TYPE` in a terminal to know.

I'm under X11.

> Also, can you reproduce this when running the project in fullscreen?

After running a 30 sec test in full screen mode, no spike was discovered, so this is probably not a godot issue?

**Comment by Calinou** [comment]
> After running a 30 sec test in full screen mode, no spike was discovered, so this is probably not a godot issue?

Indeed, this is likely a compositor/window manager/graphics driver issue. This is also something I can reproduce on my Linux + KWin + NVIDIA + X11 setup, even with compositing disabled.

**Comment by Zireael07** [comment]
Can this be documented somewhere? IIRC this is like the fourth time such an issue (or a very similar one) gets raised

**Comment by Calinou** [comment]
> Can this be documented somewhere? IIRC this is like the fourth time such an issue (or a very similar one) gets raised

There is already a similar note for Windows in the Fixing jitter and stutter documentation. I guess we should extend it to be applicable to Linuw as well.
