### ISSUE TITLE
Android to download directory saved pictures only appear after restarting phone

### ISSUE THREAD

**Issue by MarcusDobler** [godotengine/godot#81907]
### Godot version

4.1.stable [970456615]

### System information

Godot v4.1.stable - macOS 13.5.1 - Vulkan (Compatibility) - Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When saving a picture with:

save_jpg(path)

to the Android download directory.  I geht the response code 0 for OK! But when I look in the downloads directory of my:

Google Pixel 7a - Android 13

there is no file. 

BUT(!) if I restart the device and look in the downloads folder then the image is there. 

Maybe there is some issue with closing the file in GODOT code?

### Steps to reproduce

Just look at the minimal reproduction project. 

### Minimal reproduction project

Press the save button. The GODOT logo should a will be saved in the Downloads directory. BUT you can only see it after restarting your Android device.
[23-09-19-02 Android save issue.zip](https://github.com/godotengine/godot/files/12657728/23-09-19-02.Android.save.issue.zip)

**Comment by bitsawer** [comment]
Thanks for the report. I don't think this is a bug or even a Godot issue, if I remember right you need to manually notify the Android OS so that it knows you have added a new image there. It will also do a full scan on reboot. See https://developer.android.com/reference/android/media/MediaScannerConnection and `scanFile()`.

**Comment by MarcusDobler** [comment]
> Thanks for the report. I don't think this is a bug or even a Godot issue, if I remember right you need to manually notify the Android OS so that it knows you have added a new image there. It will also do a full scan on reboot. See https://developer.android.com/reference/android/media/MediaScannerConnection and `scanFile()`.

Thank you for the answer! I've googled around I can't find how to scanFile() with Godot. Do I have to make a plugIn to make this work?
