### ISSUE TITLE
New 3D scaling gizmos not snapping to grid correctly

### ISSUE THREAD

**Issue by JamesC01** [godotengine/godot#81916]
### Godot version

v4.2.dev5.official

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 30.0.15.1179) - AMD Ryzen 3 1200 Quad-Core Processor (4 Threads)

### Issue description

When using the new 3D scaling gizmos and grid snapping, they seem to sometimes snap correctly, but occasionally, it will start moving in smaller increments until the size is completely off the grid. I also think that there are some problems due to the fact that the transform gizmo is in the centre of these types of nodes, so even if the edges of the node are snapped, the position will almost never be snapped. Maybe adding an option to switch between a centered transform gizmo, and a corner transform gizmo could solve some problems.

![Screenshot 2023-09-19 130445](https://github.com/godotengine/godot/assets/31216671/0cf382eb-b329-480a-9f17-4a549da34270)

### Steps to reproduce

Create a node that uses these gizmos, and with grid snapping on, keep moving the handles until it goes off the grid. You have to keep letting go of it, and click/dragging it again. When you initially grab the handle, and it snaps, it will continue to snap, it's when you click it again that it sometimes goes off.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @KoBeWi

**Comment by KoBeWi** [comment]
This problem was originally discovered in #71092, but it's difficult to solve.
Snapping should work properly when you hold Alt, i.e. use the old resizing behavior.
