### ISSUE TITLE
No nullptr check in cowdata - crash to desktop

### ISSUE THREAD

**Issue by ShlomiRex** [godotengine/godot#81911]
### Godot version

v4.2.dev.custom_build.ba54c3455

### System information

macOS M1

### Issue description

In `cowdata.h` line 314:

https://github.com/godotengine/godot/blob/571cd0eb791b37e9a8adda9f909251138170f6b7/core/templates/cowdata.h#L314

We can see:

`*_get_size() = p_size;`

The function `_get_size()` may return nullptr:

```
	_FORCE_INLINE_ uint32_t *_get_size() const {
		if (!_ptr) {
			return nullptr;
		}

		return reinterpret_cast<uint32_t *>(_ptr) - 1;
	}
```

I discovered this when investigating the issue: #63534

This is the cause of the issue and the cause of the crash.

Since I don't understand Copy-On-Write logic, I don't know how to fix it. So I leave it to you guys.

### Steps to reproduce

1. Get #63534 project (download the example)
2. Open (double click in godot editor)`res://godot_4_alpha_12_tileset_issue_2.log`
3. Crash into desktop

### Minimal reproduction project

Get #63534 project (download the example)

**Comment by AThousandShips** [comment]
I'm not sure how this could happen as all the paths leading to `*_get_size() = p_size;` are null checked?

**Comment by AThousandShips** [comment]
Might know, will do some checking later today

**Comment by ShlomiRex** [comment]
> I'm not sure how this could happen as all the paths leading to `*_get_size() = p_size;` are null checked?

I did small change to see the result of `_get_size()` and indeed it's zero-pointer:

<img width="652" alt="image" src="https://github.com/godotengine/godot/assets/17744127/52251caa-8319-4742-8109-0770cee81b2c">

**Comment by AThousandShips** [comment]
I've identified the error, looking into a fix
