### ISSUE TITLE
occlusion culling algorithm is wrong

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#81919]
### Godot version

4.0 and later

### System information

irrelevant

### Issue description

if i understood correctly Godot's occlusion culling uses raycasts to create the depth buffer, which is a wrong solution.
if the depth buffer's pixels are larger then the viewports pixels they can hide things which should be visible. (https://github.com/godotengine/godot/issues/53288)
if they're smaller (unlikely) they can not hide things which should be hidden.
it's only correct if the occluder buffer and viewport buffer have exactly matching pixels. (not practical)

instead of raycasting against occluders, rasterize the occluders' triangles.
this approach worked for Urho3D. introduction can be found [here](https://urho3d.io/documentation/HEAD/_rendering.html) in the "Optimizations" section.

### Steps to reproduce

see https://github.com/godotengine/godot/issues/53288

### Minimal reproduction project

see https://github.com/godotengine/godot/issues/53288

**Comment by Calinou** [comment]
Please post this as a comment of https://github.com/godotengine/godot/issues/53288 
:slightly_smiling_face:
