### ISSUE TITLE
Android build has no light 4.1.1

### ISSUE THREAD

**Issue by turkerfatih** [godotengine/godot#81923]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Android Pie, Xiaomi Mi Note 3, Adreno 512 (DirectX 12.1, OpenGL ES 3.2, Vulkan)

### Issue description

Tried very sample scene. There is no light in the game. Also has very low frame rate. 
 Tried on another phone which has Adreno 630 game has light and seems runs ok.

### Steps to reproduce

Just build apk containing a directional light

### Minimal reproduction project

"N/A"

**Comment by Zireael07** [comment]
@turkerfatih You'd be surprised how many "high graphics" games on mobile cut corners and fake things and almost certainly run on OpenGL (what we call Compatibility). Also this is not a matter of Godot itself, it's a matter of Vulkan being poorly supported by mobile GPUs

Anyway try Compatibility rendering first. There's only a couple advanced things it can't do, and it's capable of looking as good as Vulkan Mobile.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
