### ISSUE TITLE
Tilemap selection tool: can't remove from the current selection with ctrl+click

### ISSUE THREAD

**Issue by ershn** [godotengine/godot#81920]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21029.1006) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

## Problem

The documentation on the tilemap selection tool states that you can remove from the current selection by ctrl+click.
However doing so does nothing.

https://docs.godotengine.org/en/stable/tutorials/2d/using_tilemaps.html#selection
> To remove from the current selection, hold Ctrl then select a tile.

## Expectation

Ctrl+click on a tilemap selection should remove the clicked tile from the selection.

## Demonstration

![bug_reproduction](https://github.com/godotengine/godot/assets/7790167/735bd84d-9df1-4e9d-a4cb-23af6a917f82)

## Notes

I unsure if this is a bug with the engine or the documentation that is outdated (it's stated on the documentation page that `This page is up to date for Godot 4.1` though).

If it's a problem with the documentation, tell me so and I will file a bug there.

### Steps to reproduce

1. create a tilemap node
2. create a tileset with a single atlas, import a texture
3. paint some tiles in the 2d editor
4. select the tiles with the tilemap selection tool
5. try to remove a tile from the selection with ctrl+click

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/12659553/Bug.zip)

**Comment by BlueCube3310** [comment]
The documentation is likely outdated, ctrl + shift need to be both pressed to remove selected tiles.
