### ISSUE TITLE
Input Axis Sticking

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#81931]
### Godot version

4.2.dev5

### System information

ChromeOS - Godot v4.2dev5 - Web Editor

### Issue description

The issue is that sometimes when using an axis for left and right axis pushing them repeatedly will make the input stick in one direction and not let go. 

### Steps to reproduce

1. Open A New Project.
2. Add the built in 2D or 3D CharacterBody Node.
3. Run the project.
4. Start pressing left and right, it will randomly just stick in one direction even when not pressing any keys.

### Minimal reproduction project

N/A

**Comment by Qainguin** [comment]
#81170 This pull request is referenced on the patch notes for 4.2.dev5 but it didn’t fix the issue.

**Comment by Qainguin** [comment]
Also, I am using the keyboard.

**Comment by Qainguin** [comment]
I can’t test with anything else right now.

**Comment by akien-mga** [comment]
Can you test earlier dev snapshots and 4.1.1 to confirm which versions work and which versions have the bug?

**Comment by Qainguin** [comment]
I am using the keyboard in the laptop. It does not stick in any other apps, only Godot. I cannot test any version of Godot 4.1 in web because those versions are still broken in web.

**Comment by Qainguin** [comment]
I checked and 4.2dev3 doesn’t have the bug.

**Comment by Qainguin** [comment]
Neither does 4.2.dev2, have the bug. I’m guessing it was introduced in 4.2.dev4.

**Comment by Qainguin** [comment]
This also affects the editor’s camera. Sometimes it will stick one key so when you right click it moves forever in one direction.

**Comment by Qainguin** [comment]
> Can you test earlier dev snapshots and 4.1.1 to confirm which versions work and which versions have the bug?
> 
> 
> 
> Which controller are you using? Is it bluetooth or USB?

4.1.3 doesn't have the bug.
