### ISSUE TITLE
Importing FBX with empty animation doesn't create Skeleton3D node at root node

### ISSUE THREAD

**Issue by kxn** [godotengine/godot#81935]
### Godot version

Godot v4.1.1.stable

### System information

 Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3179) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

I have several .fbx files, one contains a mesh, others have one animations each.  All of them share the same hierarchy.
When importing the one contains mesh, the Skeleton3D node is not created at root node,  as the image below.
![1695134763023](https://github.com/godotengine/godot/assets/2174436/f8093efd-1949-43cb-a4f6-5c27a437cb2b)
Then when I import those animation fbx files as animation library,  it seems count the node path from root, as below
![1695134873678](https://github.com/godotengine/godot/assets/2174436/e79a1434-4c12-4f5b-bb57-0f5e86707dd1)
So the animations doesn't work because of wrong path.

### Steps to reproduce

Just open the project zip files using godot 4.1.1

open r_boy_01.tscn , the A_R_Boy_Run_01/Take 001 animation can not be played and reports a lot of errors

R_Boy_01.fbx is the one with mesh, while A_R_Boy_Run_01.fbx is the animation only one

### Minimal reproduction project

[GD3D.zip](https://github.com/godotengine/godot/files/12662570/GD3D.zip)

**Comment by fire** [comment]
We are working on another fbx importer here https://github.com/godotengine/godot/pull/81746

**Comment by lyuma** [comment]
I would like to add an import option to guarantee that the imported file is a skeleton3D (such as an animation file). I currently do this manually in Unidot Importer but it should be part of Godot.
