### ISSUE TITLE
Default C# script names do not match case, which prevents [Export] variables from appearing in the inspector

### ISSUE THREAD

**Issue by Rehrok** [godotengine/godot#81945]
### Godot version

v4.2.dev5.mono.official

### System information

Godot v4.2.dev5.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU (NVIDIA; 31.0.15.2756) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When you use "attach script" to a node, it auto-fills a lower-case version of the node name with the .cs suffix.  For instance, when following the tutorial here [https://docs.godotengine.org/en/stable/getting_started/first_2d_game/03.coding_the_player.html)], you create a "Player" node but the default name for the c# script is "player.cs".  The c# script needs to be named "Player.cs", otherwise you can't edit/see the [Export] fields.

This is a minor issue, but is very disruptive as an initial experience.

The auto-filled script name should use the correct case.

### Steps to reproduce

Create a node.  Click attach script.  Not the case of the auto-filled script name.  Observe that the [Export] variables do not work if the case is incorrect.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
Related:

- https://github.com/godotengine/godot-proposals/issues/1211
- https://github.com/godotengine/godot/issues/39441

Could probably be closed as duplicate of those other issues, there's also a PR that fixes them and it should make C# default to PascalCase for script file names.

- https://github.com/godotengine/godot/pull/78119

**Comment by Rehrok** [comment]
Duplicate issue, with an existing PR to fix it.  Thanks @raulsntos for the response.
