### ISSUE TITLE
Disabling Vsync on Wayland causes Vulkan renderer to instantly crash

### ISSUE THREAD

**Issue by Supreeeme** [godotengine/godot#81949]
### Godot version

v4.1.1.stable.arch_linux

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:16 +0000 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Disabling vsync (using `DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)`) causes the Vulkan renderer to instantly crash on Wayland, with the following lines of output:
```
ERROR: Condition "swapchainImageCount != sp_image_count" is true. Returning: ERR_BUG
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:1980)
free(): double free detected in tcache 2
```
I'm aware that currently you essentially can't disable vsync on Wayland, but [this was suggested in the OpenXR tutorial](https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html#setting-up-the-xr-scene) to prevent the scene from being locked to the monitor's refresh rate (which doesn't make a lot of sense since AFAIK, XR runtimes are essentially supposed to manage VSync themselves with xrBegin/EndFrame).

### Steps to reproduce

Run example project in a Wayland session 

### Minimal reproduction project

[vsync.zip](https://github.com/godotengine/godot/files/12666611/vsync.zip)

**Comment by Calinou** [comment]
This is likely fixed by https://github.com/godotengine/godot/pull/80566. Please [test that PR](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) :slightly_smiling_face:

**Comment by Supreeeme** [comment]
That PR works great!

**Comment by Calinou** [comment]
Alright, closing in favor of https://github.com/godotengine/godot/issues/80550 then (as this is the underlying issue).
