### ISSUE TITLE
GUI Buttons Randomly Stop Working

### ISSUE THREAD

**Issue by APT-11** [godotengine/godot#81943]
### Godot version

Godot v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Fedora Linux 38 (Workstation Edition) (KDE Plasma Desktop on X11) - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue Description
There seems to be an intermittent issue regarding UI buttons in my projects. I created a dedicated project to test this (reproduction steps below). The project consists of a simple UI scene with a single button. The button down signal is connected to a function in the script attached to the parent of the button (Control). This function prints "Button pressed" to the console.

**Expected behavior:**
Clicking the button should result in `button pressed` being printed to the console. This behavior should be consistent every time the scene is run.

**Actual behavior:**
Sometimes when hitting play the game launches **almost instantly** and the button works. Other times, seemingly at random, the game takes **a few seconds** to launch and the button is broken. The input is definitely detected by the button, as it visually reacts as normal to the click. It seems, however, that the signal is not reaching my script as the print statement will not run. Restarting the editor fixes the issue temporarily but it comes back every couple of times I run the game.

When the issue occurs, it generally persists for the next 3-4 times I run the project, then goes away for a couple runs, then comes back. This cycle seems to repeat indefinitely. I have not been able to determine a pattern in the number of times the project needs to be run in order to create the issue, nor any other conditions surrounding the launching of the game window.

This issue is present in both GDScript and C#. I suspect it may be operating system related (Linux x86-64), as my friend was unable to reproduce the issue on MacOS (M1).

### Video
This video shows the simple project I'm using. I run the project twice. The first time everything works as expected. Then, without changing anything, I run the project again and now the button doesn't appear to send the signal to my script. This is despite the clear visual feedback from the button indicating that it has been pressed.

https://github.com/godotengine/godot/assets/101361000/cd4b9e1c-575d-4e65-8b32-44d452bcb9ff

### Steps to reproduce

Here are the steps I took in reproducing this issue:
- Create a new project
- Create a scene with the 'User Interface' template
- Add a gdscript to the 'Control' root node called 'Control.gd'
- Add a button as a child of the root node
- Select the button. Using the 'Node' section of the editor, connect the BaseButton.button_down() signal to the Control.gd script. Use the default function that the engine generates to handle the signal
- Replace the body of the new function with a basic print statement
- Run the project multiple times until the issue occurs. Usually happens in under 10 attempts.

The full contents of Control.gd:

```
extends Control

func _on_button_button_down() -> void:
	print('button pressed')
```

### Minimal reproduction project

N/A

**Comment by miv391** [comment]
Are you sure the `_on_button_button_down()` function is not called? In the video nothing is printed to the Output, not even the usual stuff like:
```
Godot Engine v4.2.dev5.official.e3e2528ba - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB
```

How about adding this to the signal handler to see if it is really called:

```gdscript
func _on_button_button_down() -> void:
	print('button pressed')
	position.x += 50
```

Or add a breakpoint to the signal handler function.

**Comment by APT-11** [comment]
Moving the button does work, however nothing prints. Might this be an issue with the console then?

**Comment by wouldntsavezion** [comment]
Most likely, have a look at #81102 and #80853, among others.

**Comment by APT-11** [comment]
Yeah, it seems consistent with #81102. I was running Portmaster which seems to have been blocking the connection to the debugger port. Closing now, thanks for the help folks!

**Comment by OWL4C** [comment]
Consistent fix without deactivating portmaster is changing the Debug port in Editor Settings from 6007 to something like 7007. No idea why.
