### ISSUE TITLE
There is no way to know if a cell is flipped or transposed in a TileMap

### ISSUE THREAD

**Issue by juancolacelli** [godotengine/godot#81942]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Fedora Linux

### Issue description

There is no way to know if a cell is flipped or transposed in a TileMap.
In Godot 3 I can access with `is_cell_transposed`, `is_cell_x_flipped` and `is_cell_y_flipped`.

### Steps to reproduce

Create a TileMap, add a basic TileSet, paint a flipped or transposed cell and try to read that information from GDScript.

### Minimal reproduction project

Reproduction steps are trivial and don't require any project files to be followed.

**Comment by KoBeWi** [comment]
This information is available, but the helper functions are not exposed.
As a workaround for now you can check if the tile is flipped by using `get_cell_alternative_tile() & 1 << 12` (12 is flip h, 13 flip v and 14 is transpose).

**Comment by juancolacelli** [comment]
> This information is available, but the helper functions are not exposed. As a workaround for now you can check if the tile is flipped by using `get_cell_alternative_tile() & 1 << 12` (12 is flip h, 13 flip v and 14 is transpose).

Thank you, you saved me. I'm getting different values than the ones you mention there but I can work with `get_cell_alternative_tile()`

**Comment by Zireael07** [comment]
Can the workaround get documented somewhere?

**Comment by GK-GreyGhost** [comment]
12, 13 & 14 didn't work for me but this does
```
var alt := tile_map.get_cell_alternative_tile(layer,coords)
var flip_h := alt & TileSetAtlasSource.TRANSFORM_FLIP_H
var flip_v := alt & TileSetAtlasSource.TRANSFORM_FLIP_V
var transpose := alt & TileSetAtlasSource.TRANSFORM_TRANSPOSE

**Comment by KoBeWi** [comment]
Somehow I forgot these constans were exposed 🙃
What's more, their description already shows example usage.
