### ISSUE TITLE
Error MSB4236: The SDK 'Godot.NET.Sdk/4.1.1' specified could not be found.

### ISSUE THREAD

**Issue by Effregy** [godotengine/godot#81940]
### Godot version

4.1.1-.Net

### System information

Windows 10

### Issue description

Running:  "C:\Program Files\dotnet\dotnet.EXE" build F:/Godot_Creation/Projects/TowerDefense/TowerDefense.csproj -c Debug -v normal -l:GodotTools.BuildLogger.GodotBuildLogger,F:/Godot_Creation/Godot/Godot_v4.1.1-stable_mono_win64/GodotSharp/Tools\GodotTools.BuildLogger.dll;C:/Users/Admin/AppData/Roaming/Godot/mono/build_logs\2fb057c39f6238b4465059f528ef43e6_Debug -p:GodotTargetPlatform=windows
MSBuild version 17.7.3+8ec440e68 for .NET
Build started 9/19/2023 12:17:21 PM.
X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
Restoring packages for C:\Users\Admin\AppData\Local\Temp\NuGetScratch\555e9b30298747a28452aecc398af7e0\f27903efe2ab45c9998a8f9946f6709c.proj...
     0>F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error : Could not resolve SDK "Godot.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   Unable to resolve 'Godot.NET.Sdk (= 4.1.1)' for '.NETStandard,Version=v0.0'.
F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Godot.NET.Sdk" because directory "C:\Program Files\dotnet\sdk\7.0.401\Sdks\Godot.NET.Sdk\Sdk" did not exist.
     1>Project "F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj" on node 1 (Restore target(s)).
     1>F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error MSB4236: The SDK 'Godot.NET.Sdk/4.1.1' specified could not be found.
     1>Done Building Project "F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

         F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error : Could not resolve SDK "Godot.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
       F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
       F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   Unable to resolve 'Godot.NET.Sdk (= 4.1.1)' for '.NETStandard,Version=v0.0'.
       F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Godot.NET.Sdk" because directory "C:\Program Files\dotnet\sdk\7.0.401\Sdks\Godot.NET.Sdk\Sdk" did not exist.

       "F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj" (Restore target) (1) ->
         F:\Godot_Creation\Projects\TowerDefense\TowerDefense.csproj : error MSB4236: The SDK 'Godot.NET.Sdk/4.1.1' specified could not be found.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.56

### Steps to reproduce

Create project.
Click 2D Node. 
Add Godot icon.svg
Add script to icon.
Set script to c#.

### Minimal reproduction project

[TowerDefense.zip](https://github.com/godotengine/godot/files/12664772/TowerDefense.zip)

**Comment by Zireael07** [comment]
Do you have NET Sdk installed? Do you have multiple versions of the SDK installed? Is the path in the error log correct?

**Comment by Minoxs** [comment]
Tested your code and could not reproduce the error. Game ran fine and showed the Godot logo in the game window.

From the error message it sounds like you either don't have the Godot SDK installed or .NET itself. 
Make sure to download the .NET version of Godot: https://godotengine.org/download/windows/
Which requires at least .NET 6.0: https://dotnet.microsoft.com/en-us/download

**Comment by Effregy** [comment]
The path is correct. There is no Godot folder in there. I tried uninstalling my version of dotnetSDK and installing 6, didn't change that it didn't work.
![dotnet](https://github.com/godotengine/godot/assets/90005755/79f390e8-cc3c-4e33-9736-4699c18de3f4)

**Comment by Effregy** [comment]
Godot SDK installed? Godot comes as a zip file, and there is no mention of such a file needing to be installed.

**Comment by Minoxs** [comment]
From my experience, yeah, you just download the .NET version of Godot and run it. The SDK is inside GodotSharp\Tools\nupkgs in the zip file.

**Comment by Minoxs** [comment]
I believe the C# basics documentation of Godot has the answer to your problems: https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html

> If you see an error like "Unable to find package Godot.NET.Sdk", your NuGet configuration may be incorrect and need to be fixed.
> 
> A simple way to fix the NuGet configuration file is to regenerate it. In a file explorer window, go to %AppData%\NuGet. Rename or delete the NuGet.Config file. When you build your Godot project again, the file will be automatically created with default values.

**Comment by Effregy** [comment]
Well now it seems to build, but when I try to open a script through Godot - using VS Code or ticking it to not use external, it causes:  modules/mono/glue/runtime_interop.cpp:1324 - System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'F:/Godot_Creation/Godot/godot.net.sdk.4.1.1.nupkg' with working directory 'F:\Godot_Creation\Projects\TD'. The specified executable is not a valid application for this OS platform.
     at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
     at GodotTools.Utils.OS.RunProcess(String command, IEnumerable`1 arguments) in /root/godot/modules/mono/editor/GodotTools/GodotTools/Utils/OS.cs:line 255
     at GodotTools.GodotSharpEditor.OpenInExternalEditor(Script script, Int32 line, Int32 col) in /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:line 246
     at GodotTools.GodotSharpEditor.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/editor/GodotTools/GodotTools/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/GodotTools.GodotSharpEditor_ScriptMethods.generated.cs:line 145
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24

**Comment by Minoxs** [comment]
I got an error kinda like that when I renamed my project, check under "Editor > Editor Settings > Dotnet" and "Project > Project Settings > Dotnet" if everything is configured correctly. Assembly name has to be the same as the ".sln" and ".csproj" I think.

If that doesn't work, try creating a new project. Could be some other broken thing that persisted from the initial one.

**Comment by Effregy** [comment]
I changed the dotnet Editor to VSCode, and now it runs and builds correctly. -- 

> I believe the C# basics documentation of Godot has the answer to your problems: https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html
> 
> If you see an error like "Unable to find package Godot.NET.Sdk", your NuGet configuration may be incorrect and need to be fixed.
> 
> A simple way to fix the NuGet configuration file is to regenerate it. In a file explorer window, go to %AppData%\NuGet. Rename or delete the NuGet.Config file. When you build your Godot project again, the file will be automatically created with default values.

I worked on & googled this for many hours yesterday, this finally solved the problem. Thank you.

**Comment by yalikes** [comment]
clear Nuget cache would help.
