### ISSUE TITLE
Editor: AnimationTree node font color is black

### ISSUE THREAD

**Issue by sash-rc** [godotengine/godot#81966]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Linux Ubuntu 22.04, GeForce 1060

### Issue description

Node labels in AnimationTree editor are black and thus unreadable, for default (dark theme).
![animation tree v4 2 dev5](https://github.com/godotengine/godot/assets/5348043/29ea04e1-15a2-4cbe-b497-5cd7e3ce181d)

Same for a Light theme
![light](https://github.com/godotengine/godot/assets/5348043/2ce36812-a953-4376-9f86-c1864bc49067)

Didn't happen before (in v4.2.dev4)

### Steps to reproduce

AnimationTree editor, with  root nodes, dark theme.

### Minimal reproduction project

N/A, just editor

**Comment by Zireael07** [comment]
IIRC nuking the shader cache helped with an extremely similar issue someone else had.

**Comment by sash-rc** [comment]
> IIRC nuking the shader cache helped with an extremely similar issue someone else had.

Alas, removal of  `/home/me/.local/share/godot/shader_cache/` doesn't fix.
And 4.2.dev4 side-by-side still works
