### ISSUE TITLE
C# script changes reverted without warning (upon first time saving/running scene after opening project)

### ISSUE THREAD

**Issue by entelec** [godotengine/godot#81976]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.3734) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

Any C# script changes made after opening a project are reverted without warning when the scene is saved or run for the first time, at least for me in the specific circumstances of the included project. [EDIT: Put another way, the script file is apparently overwritten with the previous version of itself.]

I could not find a way to intentionally reproduce the problem from scratch in a new project, so I am providing the specific project it happened in, which is an in-progress "Your first 2D game" tutorial (Dodge the Creeps) using C#. I first ran into the issue simply following the tutorial from the beginning, tabbing over to VS Code and noticing that the (already edited and once-built!) script file had somehow reverted to the default C# template it started from.

In my testing the choice of (external) script editor did not affect the issue as such, but I am using VS Code, and with the script file open in it the issue can handily be seen to happen in real time as the file's contents update. The script file has not been opened inside Godot's own script editor.

It does not seem to matter if a manual build of the C# solution is done before step 5 (below). However, saving or running the scene _before_ making the changes to the script seems to prevent the issue from occurring. Additionally, it seems that removing the .godot folder (as instructed for submission) also stopped the issue in the resulting stripped project, so I am including the folder as well (having removed the imported+mono+shader_cache subfolders which had no bearing on the issue).

### Steps to reproduce

1. Open Godot
2. Open _DodgeTheCreepsRepro_ project (should open directly into the scene _player.tscn_)
3. Open the script file _Player.cs_ in an external editor
4. Make any changes to the script (e.g. just delete all the contents) and save it
5. Save or run the current scene in Godot

### Minimal reproduction project

[DodgeTheCreepsRepro.zip](https://github.com/godotengine/godot/files/12672687/DodgeTheCreepsRepro.zip)
(.godot folder partly included, per issue description)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/50163.
