### ISSUE TITLE
`Input.is_action_just_pressed` flickers when action is tied to an input axis (joystick direction)

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81975]
### Godot version

4.2.dev5

### System information

linux, wired switch pro controller

### Issue description

may be related to https://github.com/godotengine/godot/pull/81170 (as before that, my axes were getting stuck, but since then I get this bug). (although I didn't bisect or anything, I just remember that)

I have an action tied to an input axis (a joystick direction).
This happens as I move my joystick in the direction of the action:

[simplescreenrecorder-2023-09-20_13.57.30.webm](https://github.com/godotengine/godot/assets/71937306/a0cb18dd-f66b-44f7-af75-6f20ba4cf877)

(red circle is deadzone)

### Steps to reproduce

1. assign a controller axis to an action
2. print `Input.is_action_just_pressed("your_action")` in `_process`
3. wiggle your stick

### Minimal reproduction project

[axis_jittering.zip](https://github.com/godotengine/godot/files/12672834/axis_jittering.zip)

**Comment by ErezShahaf** [comment]
Took a brief look at #81170, I think that there is a bug that updates the pressed tick number even when it shouldn't, I will get into fixing that soon.

By the way, I'm not too familiar with the engine and didn't read the whole input system, but based on this commit it looks like it is counting the amount of times that a certain action is pressed at the same time, in which platforms is it relevant?

**Comment by ErezShahaf** [comment]
> > it is counting the amount of times that a certain action is pressed at the same time
> 
> not 100% sure but I think that if you assign two keys to an action (say, the left key on your keyboard and the left dpad of a controller), pressing them together can only be tracked correctly that way.

I was about to edit my comment and accidently deleted it.

Anyway, I can't understand intentions some of the developers:

`// If axis is already pressed, don't increase the pressed counter.`

Then what is the point of having this counter anyway? 
I'll wait to hear from others what the original intentions are before trying to fix it.

**Comment by Sauermann** [comment]
> Then what is the point of having this counter anyway?

The counter tracks how many different keys are pressed, that are bound to the same Action.

> `// If axis is already pressed, don't increase the pressed counter.`

That is to make sure that input from a single Axis can affect the counter only once.

The jittering likely got introduced in this PR: https://github.com/godotengine/godot/pull/80859#discussion_r1305760609 CC @KoBeWi.

**Comment by ErezShahaf** [comment]
> > Then what is the point of having this counter anyway?
> 
> The counter tracks how many different keys are pressed, that are bound to the same Action.
> 
> > `// If axis is already pressed, don't increase the pressed counter.`
> 
> That is to make sure that input from a single Axis can affect the counter only once.
> 
> The jittering likely got introduced in this PR: [#80859 (comment)](https://github.com/godotengine/godot/pull/80859#discussion_r1305760609) CC @KoBeWi.

Makes sense, I'll look into it.

**Comment by KoBeWi** [comment]
> That is to make sure that input from a single Axis can affect the counter only once.

To expand on this, an axis can press an action multiple times in a row without releasing it. This is because axis events come with a strength and they count as pressed when the strength is above deadzone. You can get multiple events with strength above deadzone.
This condition checks only axis input, as buttons and keys are unaffected.

**Comment by ErezShahaf** [comment]
It ended up being a fairly simple issue, the assignment of pressed_frame was in the wrong scope.

Btw, unrelated question - when I tried to debug the issue from source whenever I open the test project of miel it would detach the debugger. Is there a way to solve it?

**Comment by KoBeWi** [comment]
Use `--path` and provide path to the project.
