### ISSUE TITLE
[3.5.2] Darker sprite using GLES3

### ISSUE THREAD

**Issue by Drakenroft** [godotengine/godot#81977]
### Godot version

3.5.2

### System information

Windows 11, i9 11900k, RTX 3060 Ti 

### Issue description

Imported a simple 20x20 sprite, disabled compression and sRGB but the sprite looks darker both in-editor and in-game, switched to GLES2 (which is anycase more appropiate for this game since is a PS1-style game, so i had no trouble with it), and the sprite appeared as it should be.
The sprite has alpha only in the background (i thounght it could be some transparency problem of the sprite but it isn't)
Also i know that there is lighting difference between GLES2 and GLES3 but it doen't affect the sprite, if i make the two render have the same lightning the problem persist.
Small note is that the same sprite is applied through a Sprite3D over the Enemy head and it seems to be render more precisely, the UI heart instead is render through a normal Sprite (Node2D) 

![Immagine 2023-09-20 124502](https://github.com/godotengine/godot/assets/35116091/451c42d8-56a9-4878-8046-6966ee5bc776)
![Immagine 2023-09-20 124105](https://github.com/godotengine/godot/assets/35116091/623c320a-149e-402a-ac3b-4ee9e5017c84)

![image](https://github.com/godotengine/godot/assets/35116091/4141c148-ae73-4cd2-993a-b18ac21d930b)
![image](https://github.com/godotengine/godot/assets/35116091/233ca334-11e9-49d7-ba09-5a5995da5c3b)

### Steps to reproduce

import a simple sprite (mine is 20x20) disable compression and sRGB

### Minimal reproduction project

/

**Comment by lawnjelly** [comment]
See https://docs.godotengine.org/en/3.5/tutorials/assets_pipeline/importing_images.html#srgb

This is common in GLES3 I believe, although usually setting to sRGB results in being darker in 2D. You need to click "reimport" in the import inspector for it to take effect.

I'm not sure this is a bug, more intended behaviour.

Would always benefit from MRP.

**Comment by Calinou** [comment]
> Small note is that the same sprite is applied through a Sprite3D over the Enemy head and it seems to be render more precisely, the UI heart instead is render through a normal Sprite (Node2D)

If you use the same texture in both 2D and 3D, you must make two copies of it in the project. Use one of them in 2D only, and the other in 3D only.

**Comment by Drakenroft** [comment]
@lawnjelly sRGB is turned off, turning it on kinda broken the sprite, also i clicked reimport after every change to a property (restarted the editor multiple timess too since i noticed that sometimes a restart is needed for changes to take effect)

@Calinou can't the fix be backported to 3.x? Since the 3.x will still be supported for 3.6.x would be amazing to have it as stable as possible

**Comment by Calinou** [comment]
> @Calinou can't the fix be backported to 3.x? Since the 3.x will still be supported for 3.6.x would be amazing to have it as stable as possible

This is not technically feasible, as Godot 3.x *needs* different texture files to be used, so that one is imported as sRGB and the other one is not. This is required because OpenGL ES 2.0 has essentially no proper support for sRGB texture formats, and Godot 3.x needs to support GLES2.

**Comment by Drakenroft** [comment]
@Calinou Yeah have at least a workaround is stille fine too me, if it works, it works, even if the sprite needs to be duplicated. 
Anyway in GLES2 it works correctly with one sprite, is in GLES3 that i needed to duplicate it to fix the issue
