### ISSUE TITLE
MSDF Generator leaves holes in Tilt Fonts

### ISSUE THREAD

**Issue by thygrrr** [godotengine/godot#81974]
### Godot version

4.1.1.stable

### System information

Windows 11 - 4.1.1.stable

### Issue description

Certain fonts generate with holes in the faces of some of the types. 
This bug is possibly specific to Tilt Fonts, https://github.com/googlefonts/Tilt-Fonts
I have only tested the TrueType format. 

A reproduction project is attached.

An example Font is is TiltNeon, the font rendered in the picture and sample project, it is available under the SIL Open Font License here for testing and reproduction: https://fonts.google.com/specimen/Tilt+Neon

![image](https://github.com/godotengine/godot/assets/8904620/befb3ad7-d720-4e25-9e65-4ae68c03934e)

### Steps to reproduce

1. Import the Attached Reproduction Project and open reproduction.tscn

OR: 

2. Import the TiltNeon-Regular.ttf font, available here:  https://fonts.google.com/specimen/Tilt+Neon

3. Write a word like "Metis" in large type.

4. Observe holes int he letters M and e.

### Minimal reproduction project

[godot-tilt-font-reproduction.zip](https://github.com/godotengine/godot/files/12672602/godot-tilt-font-reproduction.zip) (52kb)

**Comment by bruvzg** [comment]
This is usually caused by self-intersections in the font, which is a font bug.

**Comment by thygrrr** [comment]
"It's a feature" - the font is actually not self-intersecting, the glyph is 3 dimensional.
(though indeed, its 2D projection is likely self-intersecting)

The source is originally https://github.com/googlefonts/Tilt-Fonts

I can totally understand that this is probably so specific this can get closed as "won't fix", but maybe there is some interest in this by the community. It is probably outside the scope of the engine to make the fonts render as intended (3D), but their desired 2D behaviour could be achieved.

**Comment by Zireael07** [comment]
I assume groud meant 2d profile when he said the font is self-intersecting - AFAIK the 3d mesh/msdf generator works based on 2d profiles.

**Comment by bruvzg** [comment]
There's a fix, but it requires a lot of code to fix a rare issue with non-compliant fonts (self intersections are not allowed by OpenType standard), so it's unlikely it will be ever merged - https://github.com/godotengine/godot/pull/61555

**Comment by thygrrr** [comment]
I actually shipped the repro project with the 2D version of this font, not the YROT/XROT version, so - yes, that font file apparently self-intersects. (but the 3D version displays the same issue)

Since OpenType covers this as in violation of the standards, I'll just close this, as that's the killer argument.

**Comment by RaresKeY** [comment]
I ran into a similar issue with MSDF `Label3D` text using a Google Fonts variable font. Some glyphs showed holes/shards, and it turned out to correlate with overlapping or self-intersecting outlines.

Could Godot show an import-time warning when MSDF is enabled on a font that appears to have problematic outlines? A warning in the Import dock would save users from debugging this as a 3D material, z-fighting, or lighting issue.
