### ISSUE TITLE
Polygon2D/Skeleton2D rendering bug when the polygon's rest pose is outside the viewport

### ISSUE THREAD

**Issue by SaffronStreams** [godotengine/godot#81983]
### Godot version

4.1.1.stable

### System information

Windows 10

### Issue description

Using Skeleton2D and Bone2D to animate Polygon2D can lead to the Polygon2D no longer being shown, probably being culled, when it is actually still supposed to be on the screen.

Minimum project, everything is shown:
![image](https://github.com/godotengine/godot/assets/50481103/33cd0038-f626-4b47-9a84-aef6e6d0dbcf)

Zooming in a little makes the lower leg and foot getting culled
![image](https://github.com/godotengine/godot/assets/50481103/123cae2e-3f3f-4980-9348-16d83d97fe41)

Rotating the hips Bone node also makes all the leg nodes getting culled.
![image](https://github.com/godotengine/godot/assets/50481103/3695ce9f-bf9f-4716-8076-2e5849b1a421)

This was also an issue in Godot 3 that then luckily got fixed: https://github.com/godotengine/godot/issues/35726

It has the same behavior so a similar solution might solve the problem in 4 as well?

### Steps to reproduce

Add some Polygon2D nodes, attach a texture to them and use UV points to put it on screen. Add a Skeleton2D with some bone2Ds. Connect the UV of the Polygon2D to the bones 
![image](https://github.com/godotengine/godot/assets/50481103/3c4fab19-7315-4e87-9272-b1401589a059)
This has been set up in minima project.

Now move the bones around a bit, move the root node around on the screen so it gets to the edge. You will see the Polygon2D's getting culled before they are off the screen. 

### Minimal reproduction project

[MinimumCulling.zip](https://github.com/godotengine/godot/files/12674037/MinimumCulling.zip)

**Comment by lawnjelly** [comment]
See #76184, #74656, #78177 . Likely duplicate bug.

**Comment by SaffronStreams** [comment]
The old workaround (using the new Class names) still works once the game is running:

`func enlarge_all_visual_rects():
	var custom_rect = Rect2(Vector2.ZERO, Vector2(1500,1500))
	for polygon in _node_under_which_your_polygons_are.get_children():
		print("check: " + polygon.name)
		RenderingServer.canvas_item_set_custom_rect(polygon.get_canvas_item(), true, custom_rect)`

However, this does not work in the editor, unless you use "@tool" to load/run your scene in the editor, but that's not ideal when you're dealing with characters subject to gravity for instance.

Is this impacted by the new SkeletonModificationStack perchance?
