### ISSUE TITLE
Area2D mouse_enter and mouse_exit signals emit in wrong order

### ISSUE THREAD

**Issue by srcnalt** [godotengine/godot#82016]
### Godot version

v4.1.1.stable.official [bd6af8e]

### System information

Windows 11, 64x, Vulkan API 1.3.224, NVIDIA GeForce RTX 3080 Ti Laptop GPU

### Issue description

I have 2 Area2D nodes with rectangle CollusionShape2D children. The distance of collusion shapes are 1 pixel.
I have a script that changes the sprite of the cursor when it enters and exits these regions.

<img width="380" alt="image" src="https://github.com/godotengine/godot/assets/3163281/622b5984-f6c5-4516-ae75-8cf0805e8e1c">

I have a script that changes the sprite of the cursor when it enters and exits these regions. Red region is `exit` and blue region is `walk` zone, when cursor exits these both areas its set to a + shapes `target` cursor.

```swift
func _ready():
	scene_manager = get_parent()
	
	walk_zone.mouse_entered.connect(_on_mouse_entered_walk_zone)
	walk_zone.mouse_exited.connect(_on_mouse_exited_walk_zone)
	
	exit_zone.mouse_entered.connect(_on_mouse_entered_exit_zone)
	exit_zone.mouse_exited.connect(_on_mouse_exited_exit_zone)

func _on_mouse_entered_walk_zone():
	scene_manager.cursor_manager.set_cursor(Enums.CursorType.WALK_AREA)
	print("walk zone entered")

func _on_mouse_exited_walk_zone():
	scene_manager.cursor_manager.set_cursor(Enums.CursorType.TARGET)
	print("walk zone exited")

func _on_mouse_entered_exit_zone():
	scene_manager.cursor_manager.set_cursor(Enums.CursorType.EXIT_AREA)
	print("exit zone entered")

func _on_mouse_exited_exit_zone():
	scene_manager.cursor_manager.set_cursor(Enums.CursorType.TARGET)
	print("exit zone entered")
```

In this given setup, when mouse moves from one region to another the expected behaviour is to have in following way, where when mouse is in region a and moves to region b, region a exit signal is emitted before region b enter.

```
region a entered
region a exited
region b entered
region b exited
```

However the behaviour is as follow:

https://github.com/godotengine/godot/assets/3163281/fe91e997-8339-436b-b516-ce265874f1be

### Steps to reproduce

- Open the project
- Open node_2d scene and run it
- Move cursor slowly and then quickly between 2 Gray cubes on left top corner
- Observe the logs

### Minimal reproduction project

[area_test.zip](https://github.com/godotengine/godot/files/12677753/area_test.zip)

**Comment by awardell** [comment]
This occurs when both the enter and exit happen in the same physics frame.

The code responsible is Viewport::_process_picking in Viewport.cpp.
At line 830, we call `co->_mouse_enter();` from within a loop over our colliders. Later, at line 856, we call `_cleanup_mouseover_colliders(false, false, frame);`
_cleanup_mouseover_colliders eventuall calls `co->_mouse_exit();` at line 2585.

It appears to me that fixing this issue would require massive refactor. Not only are these things currently performed sequentially, but the Viewport has no way of even determining which happened first in a single physics frame. If that were added, it would probably require implementing continuous collision detection for mouse movement. This seems like it would add unnecessary complexity and processing.

The documentation for [CollisionObject2D](https://docs.godotengine.org/en/stable/classes/class_collisionobject2d.html) already warns users of this behavior.

> Note: Due to the lack of continuous collision detection, this signal may not be emitted in the expected order if the mouse moves fast enough and the CollisionObject2D's area is small. This signal may also not be emitted if another CollisionObject2D is overlapping the CollisionObject2D in question.

My humble suggestion, as someone with no authority, is not to bother fixing this issue. @srcnalt I'm sorry that would mean you're left in the lurch, but there are other much more reliable ways to achieve what you are attempting with the mouse cursor.

**Comment by RoyBerube** [comment]
Agreed that it is caused by processing multiple mouse events in one frame, with no way to control the priority.

Here is a possible way to handle the problem in script. The key is to suppress processing the exit signal when it would be regressive.

```gdscript
enum Zone{WALK, EXIT, NONE}
var current_zone

func _on_mouse_entered_walk_zone():
	current_zone = Zone.WALK
	print("walk zone entered")	

func _on_mouse_exited_walk_zone():
	if current_zone == Zone.WALK:
		current_zone = Zone.NONE
		print("walk zone exited")	
```
