### ISSUE TITLE
Web projects crash on load with Google Chrome 117 on some Android phones (regression, worked fine in Chrome 116)

### ISSUE THREAD

**Issue by wojr1963** [godotengine/godot#82015]
### Godot version

v3.5.2.stable.official [170ba337a]

### System information

OS Name	Microsoft Windows 11 Home Version	10.0.22621 Build 22621

### Issue description

I have an application running in HTML5 for over a year. Today I started to get an error on my Android device, in the Chrome browser. 
This is only happening in Chrome on the Android phone and the impression starts with a Chrome update, as this did not happen yesterday.
The application is open to anyone who wants to enter and everyone has a different browser, it happens that it started giving this error since yesterday. never had any error beforeThe application is open to anyone who wants to enter and everyone has a different browser, it happens that it started giving this error since yesterday. never had any error before.
![tela](https://github.com/godotengine/godot/assets/5972107/661aaffb-54ff-4120-b08f-3a65e7b2f023)
I generated the application again and it still gives the same error. I reduced the size, made some modifications and it doesn't run.

### Steps to reproduce

https://jobijogos.com/tv/
This is the link to my application. When running on Chrome android phone it gives the error. On the same cell phone running on Firefox, this error does not occur. in safari it doesn't give the error. In Chrome on the Windows desktop, the error does not appear.

### Minimal reproduction project

https://jobijogos.com/tv/

**Comment by lawnjelly** [comment]
Under system information, it would be more useful to tell us the system on which the problem is occurring, i.e. what Android hardware, what android version, and what chrome version.

Caveat I'm not really a web guy, but having a look:

It runs fine on my tablet, but takes ages to load (seems quicker to load on desktop). Maybe you can get some debug logging / console to tell you what is going wrong (I don't know how this works on android in chrome, maybe you would need to use adb logcat).

Also changes to security settings can be a thing, if the latest chrome has tightened up security and the app is doing something without the correct permission.

In particular it seems to be doing some php access, that might be triggering security errors (I'm not really a web guy but I'm aware there are a lot of cross site things that are blocked). I would try turning off anything that might cause permission error, see if it runs, then gradually bring back in features to find the culprit.

```
index.js:354 Godot Engine v3.5.2.stable.official.170ba337a - https://godotengine.org
index.js:9 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
init @ index.js:9
index.js:9 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
create @ index.js:9
index.js:354 OpenGL ES 2.0 Renderer: WebKit WebGL
index.js:354  
index.js:354 https://jobijogos.com/
index.js:354 lk00:https://jobijogos.com/pxx1.php?tk=pea!peec&idchamada=59697.965215
index.js:354 POSTESTE
index.js:354 GANHOU  200,00
index.js:354 SORTEIO: 100026
index.js:354 100028 status:0 hora local:2023-09-21 02:50:39
index.js:354 falta minutos:8
index.js:354 falta horas..:0
index.js:354 falta dias...:0
index.js:354 =======>>>>>>lkcart:https://jobijogos.com/fc.php?st=100028&id=0&tp=0
index.js:354 idx --------------------
index.js:354 0
index.js:354 ==========>>>> JANELA:(2520, 1331)
index.js:354 ======>>>>carregaCartelasst:1
index.js:354 lk12:https://jobijogos.com/pxx1.php?tk=pea!peec&idchamada=72106.775721 st:0
index.js:354 BONUS
index.js:354 GANHOU  200,00
index.js:354 SORTEIO: 100027
index.js:354 100028 status:0 hora local:2023-09-21 02:50:44
index.js:354 falta minutos:8
index.js:354 falta horas..:0
index.js:354 falta dias...:0
index.js:354 =======>>>>>>lkcart:https://jobijogos.com/fc.php?st=100028&id=0&tp=0
```

**Comment by De-Panther** [comment]
Noticed the same issue in other existing Godot based games.
Happens to me on Chrome Android 117.0.5938.60.

After testing a few times with the Chrome DevTools attached, I managed to get the error message "memory access out of bounds".
But couldn't trace when it happens.

When the DevTools attached, the games works as they should, only when I detach the DevTools I can get the page to crash.

**Comment by De-Panther** [comment]
I tested some games on itch, seems like games made with Godot 3.5 crash while games using Godot 3.2 worked fine.
Maybe something with the loading process?

**Comment by Zireael07** [comment]
> It runs fine on my tablet, but takes ages to load 

Ages to load on mobile/tablet was already a preexisting issue in  Godot 3 that I once reported.

**Comment by wojr1963** [comment]
> I tested some games on itch, seems like games made with Godot 3.5 crash while games using Godot 3.2 worked fine. Maybe something with the loading process?



> Chrome Android 117.0.5938.60

The version of Chrome that gives the error is Chrome Android 117.0.5938.60

I exported the project in the Godot 3.34 version and now there is no more error when opening the page, so it is something in the 3.52 export template that after updating to Chrome Android 117.0.5938.60 started giving an error

**Comment by danilw** [comment]
> I tested some games on itch, seems like games made with Godot 3.5 crash while games using Godot 3.2 worked fine.

This why I do not update my Godot web-projects to Godot 3.5 export template,
Godot 3.5 web export template require some "most latest" WASM features, I forgot how ti called, basically work only in second half of 2022+ Chrome version browsers.

My Godot web export stay on 3.3 version.

**Comment by 457205697** [comment]
Stop pls unlock my payment page and give access give unsuccessful
tranjection re completely successfull pls
 I'd 457205697

**Comment by idoadler** [comment]
I built my game once with Godot 3.5.3 and once with Godot 3.5.3 **Mono**.
The second build (mono) works correctly, no problem on my Android Chrome. The problem only occurs on the regular build. 
[this one](https://ido.wtf/sunbird/bibirun/353mono) works, [this one](https://ido.wtf/sunbird/bibirun/353reg) crash after loading.

**Comment by akien-mga** [comment]
> [this one](https://ido.wtf/sunbird/bibirun/353reg) crash after loading.

Tested on my phone (Xiaomi Pocophone running MIUI 11 / Android 10), and it seems to work fine.
Tested Chrome 117.0.5938.60 and Firefox Beta 118.0b9.

**Comment by De-Panther** [comment]
> I built my game once with Godot 3.5.3 and once with Godot 3.5.3 **Mono**. The second build (mono) works correctly, no problem on my Android Chrome. The problem only occurs on the regular build. [this one](https://ido.wtf/sunbird/bibirun/353mono) works, [this one](https://ido.wtf/sunbird/bibirun/353reg) crash after loading.

Both crashed on my device

**Comment by lia12345kimo** [comment]
Some of the devices I've come across so far work, some don't. Some Android systems work, some have stuck sounds, and some have stuck screens.

**Comment by bakyeono** [comment]
same issue here

**Comment by Zireael07** [comment]
#82356 has a better description of the issue. Looks like it's NOT related to the device itself but to version of Google Chrome for Android

**Comment by akien-mga** [comment]
> #82356 has a better description of the issue. Looks like it's NOT related to the device itself but to version of Google Chrome for Android

It's related to both, as discussed above (and in that issue).

Chrome 117 introduced a regression which only seems to affect some (underpowered?) devices.

**Comment by mununki** [comment]
I encounter the same issue with Godot 3.5, then I downgraded to 3.3.4 then issue is resolved.

**Comment by mununki** [comment]
One thing very weird is that the crash was not happened when I connected the chrome dev tools.

**Comment by akien-mga** [comment]
Can someone who can reproduce the issue retrieve Chrome logs for when it crashes? Can you confirm that it would crash on an empty Godot project too, or is it specific to projects using certain features?

This needs to be reported upstream to Google, but we need more data for them.

If someone has time, testing intermediate Chromium releases listed in https://vikyd.github.io/download-chromium-history-version/#/ would be great to pinpoint when the regression happened.
We know it seems to be failing in 117.0.5938.60, that would be worth confirming with a Chromium build, then test newer versions to check if it's resolved already, and older versions to pinpoint when the regression was introduced.

**Comment by De-Panther** [comment]
> Can someone who can reproduce the issue retrieve Chrome logs for when it crashes? Can you confirm that it would crash on an empty Godot project too, or is it specific to projects using certain features?
> 
> This needs to be reported upstream to Google, but we need more data for them.
> 
> If someone has time, testing intermediate Chromium releases listed in https://vikyd.github.io/download-chromium-history-version/#/ would be great to pinpoint when the regression happened. We know it seems to be failing in 117.0.5938.60, that would be worth confirming with a Chromium build, then test newer versions to check if it's resolved already, and older versions to pinpoint when the regression was introduced.
> 
> Since apparently Godot 3.3.4 works, it could also be helpful to check which is the first version of Godot 3.4 or 3.5 (include betas/RCs) where the problem happens. Godot 3.5.x used to work fine, so the actual bug is still in Chromium and should be fixed there, but it can be helpful to know which Godot change triggers it.

It fails on Chrome Beta on Android as well, 118.0.5993.21
But on 118. It doesn't crash, just displays a message "table index is out of bounds", and prints it to the console as well.
If someone can create a version that have the stack trace of the fail message, I can give more details, but currently this is the only thing that was printed to the log on the games I tested.

**Comment by mununki** [comment]
I've tried to test with 3.4 at the same time, but the crash was happened.

**Comment by lawnjelly** [comment]
I haven't got android SDK etc installed yet on my new PC, but I figured google must have some tools, and turns out they have remote debugging tools for chrome:
* Put tablet in developer mode
* Enabled USB debugging on tablet
* Connect via USB cable to desktop
* On desktop type `chrome://inspect/#devices`
* Click `inspect` for your device.

Running the Minecraft2D website from #82356 it didn't work the first few times I ran, but it did manage to run and here is a log:
<details>

```
[Violation] Forced reflow while executing JavaScript took 49ms
js?id=G-36R7NPBMLS:402 [Violation] 'setTimeout' handler took 87ms
lib.min.js?1695675245:2 Unrecognized feature: 'monetization'.
xe @ lib.min.js?1695675245:2
He @ lib.min.js?1695675245:2
replaceWith @ lib.min.js?1695675245:2
(anonymous) @ game.min.js?1695675245:1
Deferred @ lib.min.js?1695675245:2
o.load_frame @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ bundle.min.js?1695675245:1
dispatch @ lib.min.js?1695675245:2
v.handle @ lib.min.js?1695675245:2
lib.min.js?1695675245:2 Unrecognized feature: 'xr'.
xe @ lib.min.js?1695675245:2
He @ lib.min.js?1695675245:2
replaceWith @ lib.min.js?1695675245:2
(anonymous) @ game.min.js?1695675245:1
Deferred @ lib.min.js?1695675245:2
o.load_frame @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ bundle.min.js?1695675245:1
dispatch @ lib.min.js?1695675245:2
v.handle @ lib.min.js?1695675245:2
lib.min.js?1695675245:2 Allow attribute will take precedence over 'allowfullscreen'.
xe @ lib.min.js?1695675245:2
He @ lib.min.js?1695675245:2
replaceWith @ lib.min.js?1695675245:2
(anonymous) @ game.min.js?1695675245:1
Deferred @ lib.min.js?1695675245:2
o.load_frame @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ game.min.js?1695675245:1
(anonymous) @ bundle.min.js?1695675245:1
dispatch @ lib.min.js?1695675245:2
v.handle @ lib.min.js?1695675245:2
index.js:347 Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
index.js:9 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
create @ index.js:9
_godot_audio_script_create @ index.js:9
$func21124 @ 032e5f4a:0x6c1f4a
$func21988 @ 032e5f4a:0x6e301e
$func23452 @ 032e5f4a:0x721f05
$fk @ 032e5f4a:0x47858b
$gk @ 032e5f4a:0x6ed677
Module._main @ index.js:9
callMain @ index.js:9
(anonymous) @ index.js:694
(anonymous) @ index.js:689
Promise.then (async)
(anonymous) @ index.js:688
Promise.then (async)
start @ index.js:667
(anonymous) @ index.js:727
Promise.then (async)
startGame @ index.js:726
(anonymous) @ index.html:223
(anonymous) @ index.html:243
index.js:347 OpenGL ES 3.0 Renderer: WebKit WebGL
index.js:347 OpenGL ES Batching: ON
index.js:347  
index.js:9 [Violation] 'requestAnimationFrame' handler took 198ms
```

</details>
Still looking!

**Comment by danilw** [comment]
> I've tried to test with 3.4 at the same time, but the crash was happened.

try Godot 3.3 https://godotengine.org/download/archive/

because Godot 3.4 is same as 3.5 in context of used web-related features

**Comment by lia12345kimo** [comment]
I am using version 3.5.3, and even after compiling the html version, some devices will still crash.

**Comment by ChronoDK** [comment]
The error have spread to Edge for Android now. They have the same problem as Chrome for Android. Reported by our players and confirmed on our own devices.

We have tested building our games with the old 3.3.4-stable and now they DO load in Chrome for Android! So something that changed after 3.3.4 is causing the problem it seems.

**Comment by akien-mga** [comment]
@danilw You're referring to Godot 4 documentation.

SharedArrayBuffer is only used in Godot 3.x if you export with the "Threads" mode. I'm assuming that's not the case of users here who export with "Regular", and thus single threaded.

**Comment by De-Panther** [comment]
AGAIN: I can test on my device, but I need someone to build a version that crash and has stack trace for error messages. (I'm not a Godot developer)
And if it's possible compile the builds with `--profiling-funcs` for the emscripten (or something similar that makes sure that the wasm functions will have readable names).
The projects linked so far were with no stack trace, so there's no helpful info on the logs.

**Comment by danilw** [comment]
> @danilw You're referring to Godot 4 documentation.
> 
> SharedArrayBuffer is only used in Godot 3.x if you export with the "Threads" mode. I'm assuming that's not the case of users here who export with "Regular", and thus single threaded.

Then it just AudioWorklet - https://godotengine.org/article/godot-3-4-is-released/#html5 that released in 3.4.

But I mention/included SharedArrayBuffer as source of crashes - because it is, and ppl need to know about it.

**Comment by ChronoDK** [comment]
Is there a way to create a 3.5 export without the AudioWorklet? To test this hypothesis.

**Comment by ChronoDK** [comment]
This is getting really strange. We tried exporting from the mono version of 3.5.3 and now the games actually run on Chrome Android 117! No more Aw Snap message. The same game, no code changes at all. Still using GDScript. What does the mono version do differently?

**Comment by lawnjelly** [comment]
> This is getting really strange. We tried exporting from the mono version of 3.5.3 and now the games actually run on Chrome Android 117! No more Aw Snap message. The same game, no code changes at all. Still using GDScript. What does the mono version do differently?

Don't discount that it could simply be a timing difference. Same with running under the chrome remote debugger. Threading bugs / heisenbugs can often exhibit like this.

**Comment by kultuk** [comment]
> Don't discount that it could simply be a timing difference. Same with running under the chrome remote debugger. Threading bugs / heisenbugs can often exhibit like this.

While it is possible to be a timing thing, my team experienced the same thing while exporting with mono, with the caveat that on one specific device it still didn't work.

**Comment by danielsasakiIGS** [comment]
I have the same problem with my game crashing or taking forever to load =/
I'm using Godot 3.5.2 and this issue happens by testing on low, mid and high-end Androids.
The game only loaded normally after I reset my Chrome to versions below 116.

**Comment by ChronoDK** [comment]
@danielsasakiIGS Can you try building the game in the .NET / mono version? In our testing that version does work.

**Comment by akien-mga** [comment]
> This is getting really strange. We tried exporting from the mono version of 3.5.3 and now the games actually run on Chrome Android 117! No more Aw Snap message. The same game, no code changes at all. Still using GDScript. What does the mono version do differently?

The main difference between the Mono and non-Mono builds is the Emscripten version used to build them. The Mono build is stuck an old Emscripten 1.39.9, while classical builds use Emscripten 3.1.14 for Godot 3.5.x.

**Comment by ChronoDK** [comment]
We tried building export templates will most of the emscripten releases (took a while, heh), and the latest working version is 2.0.16. With that version of emscripten we now have regular Godot 3.5.3 export templates that works on Android Chrome 117.

**Comment by akien-mga** [comment]
Thanks for taking the time to bisect it!

Here's the changelog for Emscripten 2.0.17: https://github.com/emscripten-core/emscripten/blob/2.0.17/ChangeLog.md#2017-04102021

**Comment by De-Panther** [comment]
Upload a build if you want me to test on my device.
The mono builds were flaky on it as well.

**Comment by Faless** [comment]
For reference, this is the upstream issue in the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1485475

**Comment by jknightdoeswork** [comment]
We're using Emscripten version 3.1.18 with no problems.

**Comment by Faless** [comment]
@jknightdoeswork are you referring to Rocket Bot Royale?
I'm unable to test it on Chrome Android as it force-redirect me to the play store to download the app when it detects I'm on mobile.

**Comment by jknightdoeswork** [comment]
https://gooberdash.winterpixel.io

**Comment by De-Panther** [comment]
> https://gooberdash.winterpixel.io


Works for me both with Chrome Android 117 and 118

**Comment by RByers** [comment]
Chrome team here: very sorry for the regression! I'm sorry we hadn't seen or acted this issue - the bug wasn't filed with the metadata needed to indicate it was a regression or a report from a developer. It looks like a code generation bug in V8 which is potentially very serious. I've marked the Chrome bug appropriately and you should expect traction in the next 24 hours or so (since it's currently the weekend).

**Comment by SysError99** [comment]
Chrome Canary 119.0.6038.2 works for some reason. Tested with all 3.5.x projects I got hands on.

![Screenshot_20231002-063208.jpg](https://github.com/godotengine/godot/assets/17522480/9d1b8a8c-fd78-4f7d-ad20-5f6da3234890)

Additional report, disabling many of components (including unused third-party modules) seemed to temporarily makes working on 117, 118 (I had one on my production works). Building it with very old Emscriptem also seemed to be temporary solution at the moment.

**Comment by RByers** [comment]
Yes, I've also confirmed it seems to be fixed in Chrome 118 (in beta now, [scheduled](https://chromiumdash.appspot.com/schedule) for stable in 1-2 weeks). We're still trying to identify the root cause and fix, but regardless you should expect this to be addressed in the next major Chrome update. It would be good if others could test their scenarios in Chrome Beta just to confirm there are some cases still broken.

**Comment by RByers** [comment]
Also our testing team has [found](https://bugs.chromium.org/p/chromium/issues/detail?id=1485475#c20) the issue no longer reproduces in our latest 117 build which will start pushing to users tomorrow! We'll continue to investigate, but it would definitely be good to get confirmation from folks here that Chrome 118 (beta) is fine. We have maybe a few more days to get any last minute emergency fixes in the 118 release if necessary.

**Comment by RByers** [comment]
I tested on 118.0.5993.32, but I was looking only at the crash (sad tab) which was due to a SIGILL (illegal instruction) in generated code. Perhaps "table index out of bounds" is a separate issue?

**Comment by ChronoDK** [comment]
It seems the latest Android Chrome 117 has fixed the problem. Godot 3.5.3 once again seems able to run in all relevant browsers, yay! 
I guess we should close this thread and go back to worrying about how to get Godot 4 games running on iOS Safari for longer than 5 seconds now? :-D

**Comment by kaiharuto** [comment]
> It seems the latest Android Chrome 117 has fixed the problem. Godot 3.5.3 once again seems able to run in all relevant browsers, yay! I guess we should close this thread and go back to worrying about how to get Godot 4 games running on iOS Safari for longer than 5 seconds now? :-D

I'm currently running Chrome 117.0.5938.141, still experiencing the problem. Which version were you referring to?

**Comment by Keetz** [comment]
Had the same issue, my Chrome updated 01:23am today to version 117.0.5938.153 and now everything works again.
Also tested Beta and Canary version which also works.

Stable: 117.0.5938.153 - Works
Beta: 118.0.5993.488 - Works
Canary: 120.0.6049.0 - Works

**Comment by Faless** [comment]
Closing as fixed upstream.
