### ISSUE TITLE
Moving Path3D does not trigger a CSGPolygon draw update

### ISSUE THREAD

**Issue by NeoWordire** [godotengine/godot#82024]
### Godot version

4.1.1.stable, 4.2.dev5.offical

### System information

Arch Linux

### Issue description

Update after deeper understanding:
I believe the core issue I see is that Path3D takes it's global position and applies it as an offset to it's CSGPolygon Mode:Path transform. but moving the Path3D in code or the editor does not seem to trigger a redraw of the CSGPolygon with the new offset until you force an update with other notification. 

Original Report:
> If you move a node with a child CSGPolygon and Path3D in the Editor or during ready(). The visual of the CSGPolygon will move twice as far as expected and desync its reported position with it's visual position. The child CSGPolygon moves with and further than the parent visually but reports the same position/global_position as the parent moved. Only occurs with CSGPolygon's in mode: Path and only when moving a parent to both the path and CSG.
> 
> Also seen in ready() if you move the parent to x = 4.0, the CSGPolygon will visually move double distance of what the parent moves, making the CSGPolygon appear at 8.0, the extra shift is not reported in the inspector position.
> 
> Doing the SAME MOVE in process(): appears at the expected 4.0. It keeps the offset from above bug if it was seen, but if all moves are done here it all works as expected and the visual moves with the parent
> 
> Enabling Path Local does remove this issue and the moves match the parent
> 
> The expected Behavior is the CSGPolygon visual moves with the parent and matches it's position value. Moving the parent should not cause the CSG visual to move "twice" and stay offset even when resetting all the positions involved to 0,0,0
> 
> ![bugreport1](https://github.com/godotengine/godot/assets/107330723/04cb8b0b-29b8-48cd-8e6c-3cbca3eb1137)
> In this picture the redball and the right Block are supposed to be at 0,0,0 in the parent but visually the CSGPolygon has been shifted by the parent's move away from 0,0,0

### Steps to reproduce

Grab either NodeEdited* node3d and move them in editor. (this moves the Path3D global position)
Note the wrong position of the CSG. cause a CSG update and see the correct position
Also run the project, the code should set both parent nodes to position.x = 2.0  and keep the CSGPolygons overlapping but the code in the ready runs before the draw and the process does not trigger another draw

### Minimal reproduction project

[CSGPolygonBug.zip](https://github.com/godotengine/godot/files/12680049/CSGPolygonBug.zip)

**Comment by NeoWordire** [comment]
One idea might be since both the path3D and CSG are under same parent both get transformed when the parent does?

**Comment by fire** [comment]
Maybe the csg node isn't properly being notified of the change in the _notification function.

**Comment by NeoWordire** [comment]
Okay, actually it does seem like this is all weirdness not from being a parent at all, but the if the path3D is not at global 0,0,0. all CSGs get offset by the path's global whenever path local is turned on.

So its possible moving the parent it's expected the csg moves twice as far. But moving the parent and thus the path during _process() does not move twice as far?

**Comment by vasiliy1337** [comment]
not sure if this is the same problem, but I get something similar when I change path3d in code
![1](https://github.com/godotengine/godot/assets/89994562/c4fb3b65-9df6-463e-bf5d-ce9c94444b87)
![2](https://github.com/godotengine/godot/assets/89994562/7775403e-337e-4c2c-8c24-9ff6fa5e00f1)

**Comment by fire** [comment]
@SaracenOne related to refreshing?
