### ISSUE TITLE
CanvasItem `draw_rect()`, `draw_line()`, etc. functions not drawing thin-lines below `-1px`

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#82022]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

v4.1.1.stable.official [bd6af8e0e]

### Issue description

I'm making some tool scripts, and I want to have varying line-width widgets which are unaffected by zoom in the editor.

The docs say negative widths are treated as non-scaling primitive thin lines, which should be able to work at sizes above 1px right? i.e. 3px-wide primitive lines should still work AFAIK.

### Steps to reproduce

**Steps:**
- Create a `@tool` script for a scene
- Give it the following `_draw()` function

**Expected Result:**
`-10` line width should draw at 10px wide regardless of zoom (just like the default `-1`)

**Actual:**
line is drawn at 1px width (image attached)
![image](https://github.com/godotengine/godot/assets/7411742/8ffadd3c-0b65-45f0-9fa8-8425950407fc)

**Code:**
```gdscript
func _draw() -> void:
	draw_rect(frame, Color(Color.BLUE, 0.05))
	draw_rect(frame, Color.BLUE, false)
	
	var top_left_pos = frame.position
	draw_polyline([
		top_left_pos + Vector2.DOWN * CORNER_SIZE_PX,
		top_left_pos,
		top_left_pos + Vector2.RIGHT * CORNER_SIZE_PX
	], Color.GREEN)
	
	var bottom_right_pos = frame.position + frame.size
	draw_polyline([
		bottom_right_pos + Vector2.LEFT * CORNER_SIZE_PX,
		bottom_right_pos,
		bottom_right_pos + Vector2.UP * CORNER_SIZE_PX
	], Color.GREEN, -10)
```

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
> `-10` line width should draw at 10px wide regardless of zoom (just like the default `-1`)

I don't see a bug here. Any negative value is treated as a thin line, there is no difference between `-1` and `-10`. The default width is `-1` unless you explicitly specify a different value. That's why all your lines are thin. If you specify a positive value for one of the lines, you will see the difference:

```gdscript
func _draw() -> void:
    draw_rect(frame, Color(Color.BLUE, 0.05))
    draw_rect(frame, Color.BLUE, false)
    
    var top_left_pos = frame.position
    draw_polyline([
        top_left_pos + Vector2.DOWN * CORNER_SIZE_PX,
        top_left_pos,
        top_left_pos + Vector2.RIGHT * CORNER_SIZE_PX
    ], Color.GREEN, 1) # <--
    
    var bottom_right_pos = frame.position + frame.size
    draw_polyline([
        bottom_right_pos + Vector2.LEFT * CORNER_SIZE_PX,
        bottom_right_pos,
        bottom_right_pos + Vector2.UP * CORNER_SIZE_PX
    ], Color.GREEN, -10)
```

![](https://github.com/godotengine/godot/assets/47700418/37f11a2a-a7d3-472d-96b1-8c8d0faec7d6)

**Comment by Calinou** [comment]
Thick unscaled lines are not supported, as Godot draws thick lines using polygons (since not all hardware supports line widths greater than 1).

**Comment by yoont4** [comment]
Ah I see, that is my bad then I misunderstood how the thin-line drawing works. I think I can work around this by drawing on a `CanvasLayer` instead which applies the transforms for each widget but then draws at a constant thickness, will give that a shot.

Could be worth specifying in the documentation that a thin line will always be specifically 1px wide. I understand "thin line" seems pretty obvious in hindsight, but I read in other places (like `draw_line()`) that it is scale-agnostic, so I inferred that it could also mean it's just a scale-agnostic width that happens to default at 1px.

**Comment by yoont4** [comment]
Also thanks for taking the time to correct me! I'm sure this repo is getting blasted right now 😆
