### ISSUE TITLE
Spatial Shader - Unexpected behavior with using OpenEXR 4 channel image as texture

### ISSUE THREAD

**Issue by Scoppio** [godotengine/godot#82027]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

My spatial shader to implement pre-rendered background needs today 2 texture files, one is the color render of the scene, the other is a depth render.

The depth render has pixel values as unbounded 32 bits floating numbers, it describes distance from the camera in meters.
The color render has pixel values ranging from 0 to 1.0 written in 32 bits floating numbers. Its the render of the scene.

Both images are in the OpenEXR format, both images have 3 channels (RGB), the Depth image repeats the same values in its 3 channels.

The following shader works perfectly (See image 01)
![image](https://github.com/godotengine/godot/assets/12498073/b811e35a-14fb-46dc-bbb4-e5fc0cfe07a2)

```
shader_type spatial;
render_mode unshaded, depth_draw_always;

uniform sampler2D _albedo : source_color;
uniform sampler2D _depth : source_color;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}


void fragment() {
	float depth = -texture(_depth, SCREEN_UV).x;
	vec4 temp = vec4(0, 0, depth, 1);
	vec4 clip_space = PROJECTION_MATRIX * temp;
	clip_space.z /= clip_space.w;

	DEPTH = clip_space.z;
	ALBEDO = texture(_albedo, SCREEN_UV).rgb;
}
```

However this is wasteful in disk space (two images at 15MB, a single image with all data size is 8MB), so to improve I went and changed the compositing on Blender to generate a single image, putting the Depth in place of the Alpha channel.

```
shader_type spatial;
render_mode unshaded, depth_draw_always;

uniform sampler2D _T: source_color;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}


void fragment() {
	float depth = -texture(_T, SCREEN_UV).a;  // alpha channel has DEPTH values
	vec4 temp = vec4(0, 0, depth, 1);
	vec4 clip_space = PROJECTION_MATRIX * temp;
	clip_space.z /= clip_space.w;

	DEPTH = clip_space.z;
	ALBEDO = texture(_T, SCREEN_UV).rgb;
}
```

This refuses to work.
As long as depth and albedo come from the same file, this simply does not work and there is nothing in my power to fix this problem.

For some reason, the value that I retrieve from A channel it returns a garbage value instead. acting as if the value that I pickup is 1.0
See, if I take the old code and do `ALBEDO = clip_space.zzz` I will have n interesting image with depth of everything. However with the new variation of the shader, it will instead of paint the depth, will paint everything white, as if the value were 1.0

So far, no EXR renders with 4 channels resulted in any kind of success.
I then tried to evaluate the functionality of the files themselves.

```
shader_type spatial;
render_mode unshaded, depth_draw_always;

uniform sampler2D _T: source_color;
uniform sampler2D depth: source_color;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}


void fragment() {
	float depth = -texture(depth, SCREEN_UV).a;  // alpha channel has DEPTH values
	vec4 temp = vec4(0, 0, depth, 1);
	vec4 clip_space = PROJECTION_MATRIX * temp;
	clip_space.z /= clip_space.w;

	DEPTH = clip_space.z;
	ALBEDO = texture(_T, SCREEN_UV).rgb;
}
```

Now I took the 4 channels image and repeated it in both sampler2D, depth and _T, and again depth failed miserably.

To make sure the problem was NOT with the image, I recreated the EXR file, but this time I switched the channels alpha and red in place, this way the first channel contains DEPTH, and I can just remap the alpha as red for the albedo.

Again I had exactly the same failure, again the value in DEPTH was understood as a uniform value.

As a last measure I created a depth image that had the same thing in 4 channels and used that as input for the depth sampler2D and picked the alpha channel, once again, it failed.

example of the failure state, compared to the previous image, the character is not in the image anymore, thats the failure state, the depth is homogenous 1.0 value.
![image](https://github.com/godotengine/godot/assets/12498073/11153eb5-f581-4378-951b-f79ba7a33dd1)

Just to be sure, I mage another image with the DEPTH in the red layer, green and blue in their normal places, thats all, no red, and it did work correctly with the following code in the fragment:
```
void fragment() {
	float depth = -texture(depth, SCREEN_UV).r;  // red channel has DEPTH values
	vec4 temp = vec4(0, 0, depth, 1);
	vec4 clip_space = PROJECTION_MATRIX * temp;
	clip_space.z /= clip_space.w;

	DEPTH = clip_space.z;
	ALBEDO = texture(_T, SCREEN_UV).ggb; // missing red channel
}
```

My tests bring me to conclude that Sampler2D or texture are misbehaving with EXR images with 4 channels and cant grab the correct value present in the A channel. Or DEPTH is broken if there is an image with 4 channels as input in the sampler 2D

### Steps to reproduce

Load the optimzed version of the shader.

```
shader_type spatial;
render_mode unshaded, depth_draw_always;

uniform sampler2D _T: source_color;

void vertex() {
	POSITION = vec4(VERTEX, 1.0);
}


void fragment() {
	float depth = -texture(_T, SCREEN_UV).a;  // alpha channel has DEPTH values
	vec4 temp = vec4(0, 0, depth, 1);
	vec4 clip_space = PROJECTION_MATRIX * temp;
	clip_space.z /= clip_space.w;

	DEPTH = clip_space.z;
	ALBEDO = texture(_T, SCREEN_UV).rgb;
}
```

Load a render with 4 chanells (attached here [test_image.zip](https://github.com/godotengine/godot/files/12680527/test_image.zip)), with the depth layer in the alpha channel.

Add the shader into a quad and load that quad in front of the camera as you would a spatial shader (dont forget to flip the quad faces), load the image to the T sampler2D of the material/shader.

Add a cube to the scene and try to have it hide behind the tree.

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/12680552/example.zip)

**Comment by danilw** [comment]
I think this your problem come from you not noticing
```uniform sampler2D _T: source_color;```

> source_color

https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html

> It's important to understand that textures that are supplied as color require hints for proper sRGB->linear conversion (i.e. source_color), as Godot's 3D engine renders in linear color space.

when you need "raw texture data" - you dont use `source_color` - this why you losing your alpha 32-bit value.

**Comment by danilw** [comment]
> example.zip

... share working godot project not just scene to save everyone else time...

I tested your project:
1. remove source_color
2. re-import texture with Lossless parameter instead of vram compression.
3. it seems to work now

on screenshot leaves intersect with cube, before change cube was not visible

Before:
![image](https://github.com/godotengine/godot/assets/24825887/63f405a5-44dc-4867-920b-57f471261caf)


After:
![image](https://github.com/godotengine/godot/assets/24825887/14abb2ea-e414-46ce-86ea-e07531b191c6)

**Comment by Scoppio** [comment]
You are so correct I cannot even state how correct you are, it took 7 people and 38 hours of total work hours and before we gave up and created this issue, and you hit the mark perfectly.

Thanks alot!
