### ISSUE TITLE
ArrayMesh Normals apear to be incorrect in StandardMaterial3D

### ISSUE THREAD

**Issue by dlsloan** [godotengine/godot#82028]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10 - Godot v4.1.1.stable - Forward+

### Issue description

Rendering a material with Albedo, Roughness, Normal Map, Ambient Occlusion, and Height maps does not seem to render a face in the -z direction (all pixels on face are black)

![image](https://github.com/godotengine/godot/assets/5439583/89ed6a98-5cf7-4457-a444-3bd05558065c)
![image](https://github.com/godotengine/godot/assets/5439583/f1722fd7-c246-44f0-bad6-8cdebf2e2b8f)

The light sources are marked by the two spheres in the scene. The scripted MeshInstance3D is instantiated in a Node3D instance which is rotated with:
`$TestNode.transform.basis = Basis(Vector3(1, 0, 0), 0.2 * delta) * $TestNode.transform.basis`
inside the top level _process() function.

MeshInstance3D node script:
```
extends MeshInstance3D

func _ready():
	var mesh = ArrayMesh.new()
	var surface_array = []
	surface_array.resize(Mesh.ARRAY_MAX)

	# PackedVector**Arrays for mesh construction.
	var verts = PackedVector3Array()
	var uvs = PackedVector2Array()
	var normals = PackedVector3Array()
	var indices = PackedInt32Array()

	verts.append(Vector3(-0.5, 0.5, -0.5))
	verts.append(Vector3(0.5, 0.5, -0.5))
	verts.append(Vector3(0.5, 0.5, 0.5))
	verts.append(Vector3(-0.5, 0.5, 0.5))
	normals.append(Vector3(0, 1, 0))
	normals.append(Vector3(0, 1, 0))
	normals.append(Vector3(0, 1, 0))
	normals.append(Vector3(0, 1, 0))
	uvs.append(Vector2(1, 1))
	uvs.append(Vector2(1, 0))
	uvs.append(Vector2(0, 0))
	uvs.append(Vector2(0, 1))

	indices.append(0);
	indices.append(1);
	indices.append(2);

	indices.append(0);
	indices.append(2);
	indices.append(3);

	verts.append(Vector3(-0.5, 0.5, 0.5))
	verts.append(Vector3(0.5, 0.5, 0.5))
	verts.append(Vector3(0.5, -0.5, 0.5))
	verts.append(Vector3(-0.5, -0.5, 0.5))
	normals.append(Vector3(0, 0, 1))
	normals.append(Vector3(0, 0, 1))
	normals.append(Vector3(0, 0, 1))
	normals.append(Vector3(0, 0, 1))
	uvs.append(Vector2(1, 0))
	uvs.append(Vector2(1, 1))
	uvs.append(Vector2(0, 1))
	uvs.append(Vector2(0, 0))

	indices.append(4);
	indices.append(5);
	indices.append(6);

	indices.append(4);
	indices.append(6);
	indices.append(7);

	# This face renders black
	verts.append(Vector3(-0.5, -0.5, -0.5))
	verts.append(Vector3(0.5, -0.5, -0.5))
	verts.append(Vector3(0.5, 0.5, -0.5))
	verts.append(Vector3(-0.5, 0.5, -0.5))
	normals.append(Vector3(0, 0, -1))
	normals.append(Vector3(0, 0, -1))
	normals.append(Vector3(0, 0, -1))
	normals.append(Vector3(0, 0, -1))
	uvs.append(Vector2(1, 1))
	uvs.append(Vector2(1, 0))
	uvs.append(Vector2(0, 0))
	uvs.append(Vector2(0, 1))

	indices.append(8);
	indices.append(9);
	indices.append(10);

	indices.append(8);
	indices.append(10);
	indices.append(11);

	surface_array[Mesh.ARRAY_VERTEX] = verts
	surface_array[Mesh.ARRAY_TEX_UV] = uvs
	surface_array[Mesh.ARRAY_NORMAL] = normals
	surface_array[Mesh.ARRAY_INDEX] = indices

	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, surface_array)
	self.mesh = mesh

```

### Steps to reproduce

- Setup a simple Sceen with a MeshInstance3D inside a Node3D with the script in the description attached to the MeshInstance3D
- Assign a StandardMaterial3D with  Albedo, Roughness, Normal Map, Ambient Occlusion, and Height maps to the Node3D's Material Override
- Place Omni lights in the scene

In the attached project, run the node_3d scene and wait for the 3rd face to rotate into view

### Minimal reproduction project

[NormalBug.zip](https://github.com/godotengine/godot/files/12680683/NormalBug.zip)

**Comment by bitsawer** [comment]
Thanks for the report. This is not a bug, you need to also set the tangent array (Mesh.ARRAY_TANGENT) or call `mesh.regen_normal_maps()` after `mesh.add_surface_from_arrays()` to calculate tangents (the method is poorly named) if you want to use normal mapping.
