### ISSUE TITLE
Get_tree code not working and cant get out of game testing.

### ISSUE THREAD

**Issue by BubaalCat** [godotengine/godot#82047]
### Godot version

4.1.1.stable

### System information

Realme C11

### Issue description

The get_tree codes dont work. I've tried the exact same thing on my brothers phone (Realme C31) and it works. It should be working for me because the game engine dosent lag and almost every other thing works absolutely fine. The get_tree codes are really important. And i just started game-dev. I cannot learn if this happens. Please try to fix this problem! Another thing i cant get out of the game testing. The screen dosent get frozen or anything but when i click the back button of my phone it dosent go back to editing. 

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by dalexeev** [comment]
Please describe the problem more clearly (code, error message, screenshot, etc.), provide steps to reproduce and MRP. If the issue only occurs on a specific device, please add more system information: CPU model and architecture; GPU model, driver version, and the rendering backend (GLES2, GLES3, Vulkan).

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you add the requested details this can be reopened
