### ISSUE TITLE
Output window doesn't scroll with certain editor scale settings

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#82041]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

#79975 closed his issue too early, it's a separate issue to #78434.

I'll just repost his same gif:
![256703477-a7db18c1-eccf-42af-85ef-1a1472f30c73](https://github.com/godotengine/godot/assets/15337628/1a7926ea-a9d8-4eb3-a857-8d34df23228f)

### Steps to reproduce

I had a theory it was related to editor settings and I tracked it down:

1. Editor -> `Display Scale` = Custom
2. Editor -> `Custom Display Scale` = 1.15
3. Click Save & Restart
4. Print stuff

```
var number := 0
func _process(delta: float) -> void:
	number += 1
	print(number)
```

The scale number matters, 1.1 seems to be fine but smaller decimal places such as 1.15 are what cause the issue.

### Minimal reproduction project

[printbug.zip](https://github.com/godotengine/godot/files/12683758/printbug.zip)

**Comment by dalexeev** [comment]
CC @bruvzg

**Comment by Calinou** [comment]
@Swarkin Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/82079

**Comment by Swarkin** [comment]
@Calinou the artifacts are expired sadly and dont have the time to compile right now
The editor is maximized and im using normal scale (100%) both editor and OS.
I have 2 screens (secondary 4k 60hz / main 2560x1440 144hz), using the main one.
`v4.2.rc1.official - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.22023.1014) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)`

**Comment by AThousandShips** [comment]
Re-running so artifacts will be available

**Comment by Swarkin** [comment]
That build seems to fix the issue
