### ISSUE TITLE
Can't use short cuts to copy and paste hexadecimal colour codes for Node modulations

### ISSUE THREAD

**Issue by MJones3035** [godotengine/godot#82053]
### Godot version

4.1

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22623 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When copying a hexadecimal value for colours the shortcuts doesn't work on a node in the Visibility/Modulate.

### Steps to reproduce

Copy the hexadecimal value in the modulate property and try and paste it into the self modulate hexadecimal value. The value won't be copied nor pasted.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
I can't reproduce this in either 4.1.1 or 4.2 dev. Please describe the steps for reproduction in more detail, including which editor widgets are currently open (2D/3D/Script screen, bottom panel tab, etc.), and whether you are using editor plugins. Perhaps some unfocused widget is processing input incorrectly.

**Comment by dalexeev** [comment]
* See #82106.

Thanks for the contribution nonetheless!
