### ISSUE TITLE
Fix multi project support for Godot C#

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#82060]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

MacOS

### Issue description

Currently it is partially possible work with multiple projects in C# solution generated by Godot.
You can add existing projects or create new one, but when you add new cs script in Godot editor the sln file is regenerated and all attached projects are lost. 

Sln file should not be regenerated every time, only on demand. And the Godot.csproj should be only regenerated.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by raulsntos** [comment]
Are you changing the value of the `dotnet/project/solution_directory` project setting?

The sln and csproj files are generated when you first create a C# script. If Godot can't find them, it assumes your project is not a C# project, and these files need to be created.

**Comment by p10tr3k** [comment]
I will close this as I cannot reproduce it anymore. If I will encounter this problem again I will reopen it.
