### ISSUE TITLE
TS->shaped_text_prev_character_pos ignored by LineEdit and TextEdit in exports only

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#82062]
### Godot version

4.2dev5

### System information

macOS

### Issue description

For exports only, for `LineEdit` and `TextEdit`, the new `TS->shaped_text_prev_character_pos` and `TS->shaped_text_next_character_pos` act as if `caret_mid_grapheme_enabled` is enabled, whereas the cursor moves across the composite character in steps.

When the project is run in-editor, the cursor moves across the entire character as expected.

https://github.com/godotengine/godot/assets/33969780/f82e08a6-ef9b-457f-b5af-bb6ed2c4f856

https://github.com/godotengine/godot/assets/33969780/dd0fbacf-c5b3-4733-b074-77fa2c14f2b7

### Steps to reproduce

See MRP.

### Minimal reproduction project

[TS Previous Char Export Bug.zip](https://github.com/godotengine/godot/files/12689076/TS.Previous.Char.Export.Bug.zip)

**Comment by bruvzg** [comment]
This function require ICU database, which is not included in exports by default, you can enable exporting it in the `Project Settings` → `Internatialization` → `Lcoal` → `Include Text Server Data` (adds 5 MB to export size).

**Comment by Koyper** [comment]
Ah ha! Is there a document anywhere regarding what else requires the ICU database?

Also, I'm duplicating part of that information with an emoji unicode lookup dictionary - is there an exposed way to check if a unicode (or composite) is an emoji via the ICU database?

Thanks!

**Comment by Koyper** [comment]
@bruvzg 

It still doesn't work with `Include Text Server Data` enabled - also after restart and with `Text Driver` set to ICU/HarfBuzz.

Is there another Project Setting required?
