### ISSUE TITLE
Cannot chain multiple screen commands (command line)

### ISSUE THREAD

**Issue by cidwel** [godotengine/godot#82071]
### Godot version

4.2.dev4.mono

### System information

MacOS Ventura 13.5.1

### Issue description

When trying to run a game from console, it seems there's no way to chain different "Display option" commands found in this [guide](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) in the same command

Some example: 

Executing...
`/Applications/Godot_mono.app/Contents/MacOS/Godot --path "/Users/javier/projects/godot/test2mono" --screen 3 --position 300,300`

it displays the window in the position 300,300 but in screen 0. If I remove the "position" command the window displays in the screen 3

### Steps to reproduce

- Open a game in command line, like 
`/Applications/Godot_mono.app/Contents/MacOS/Godot --path "/Users/javier/projects/godot/test2mono" --screen 3 --position 300,300`

Expected: should display in position 300,300 of screen 3
Result: displays in position 300,300

Remove the "position 300x300"
Result: displays in screen 3

### Minimal reproduction project

Can be tested in any new project.

**Comment by Calinou** [comment]
Window position is absolute (relative to 0,0 origin which is shared across all displays), not relative to the screen specified.

**Comment by cidwel** [comment]
It's okay. I understand the behavior. I haven't found any documentation related to that. But I guess feels natural to have an absolute position. 

I'm closing this issue as users can just use --screen to set the position (and monitor).

Many thanks
