### ISSUE TITLE
OpenGL3 bug in 3D

### ISSUE THREAD

**Issue by pliniopvv** [godotengine/godot#82070]
### Godot version

4.1 to 4.2dev5

### System information

Windows 10 with AMD Radeon HD 5670

### Issue description

Does this only happen to me?
( the 3D part is simply completely bugged, and I constantly need to switch to advanced mode to be able to fix the problem )

https://github.com/godotengine/godot/assets/4421060/ee54b8c9-b3b2-4b39-aec4-9acc2b9e71df

### Steps to reproduce

Only open a new file or a old file (with the convertion to the new version)

### Minimal reproduction project

only a new project.

**Comment by danilw** [comment]
> AMD Radeon HD 5670

most likely this is AMD drivers being broken in OpenGL as usual - nothing surprising in it
I do not think Godot can fix it.

As solution if you need OpenGL - try Godot 3.5 - GLES2/GLES3 and look if there same bug.

**Even if Godot 3.5 have same bug** - you can make WebGL-export from Godot 3.5 and then launch in webbrowser - WebGL will use translation to DX11 on Windows - and by integrating Godot3.5 web-export to Electron you can avoid OpenGL-driver-being-broken bugs.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79115.

As for Godot not falling back to OpenGL automatically when Vulkan isn't available, see https://github.com/godotengine/godot/issues/58927.
