### ISSUE TITLE
regex in linker detection for template builds fails sometimes to recognize correct ld version

### ISSUE THREAD

**Issue by cunyx** [godotengine/godot#82078]
### Godot version

3.5.2.stable

### System information

openSUSE Tumbleweed

### Issue description

While seeing in distro compiled godot 3.5.2 exports with PCK embedded working
on openSUSE Leap, it fails on Tumbleweed.

Currently i suspect the regular expression at
https://github.com/godotengine/godot/blob/fc32e066af1cd6766762dec31c7d2224f3d42c5f/platform/x11/detect.py#L411
to not recognize the linker.

As code in master branch seems to be the same
https://github.com/godotengine/godot/blob/fe5b1c8d49313d63fbe91cb7cdf463e10fb86afa/platform/linuxbsd/detect.py#L458
and i see the
```
"Warning: Creating export template binaries enabled for PCK embedding is currently only supported with GNU ld, not gold, LLD or mold"
```
with godot 4.1.1 as well,
current godot has perhaps the same issue.

This seems to be introduced with
https://github.com/godotengine/godot/pull/35444
in order to detect the version as seen in
https://github.com/godotengine/godot/issues/35100#issuecomment-577171157

The output of
```
ld --version
```
for example is
in openSUSE Leap 15.2
```
GNU ld (GNU Binutils; openSUSE Leap 15.2) 2.37.20211103-lp152.4.9
Copyright (C) 2021 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
in openSUSE Leap 15.5
```
GNU ld (GNU Binutils; SUSE Linux Enterprise 15) 2.39.0.20220810-150100.7.43
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```
while Tumbleweed produces
```
GNU ld (GNU Binutils; openSUSE Tumbleweed) 2.40.0.20230412-5
Copyright (C) 2023 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

The current regex finds these results/versions:
```
openSUSE Leap 15.2: 4.9
openSUSE Leap 15.5: 7.43
Tumbleweed: no match
```
This does seem to be correct for the used regex but might not be
what was intended.

By changing
```
"^GNU ld [^$]*(\d+\.\d+)$"
```
to
```
"^GNU ld \(GNU Binutils.*\) (\d+\.\d+)"
```
i get with a python script by parsing mentioned string output:
```
openSUSE Leap 15.2: 2.37
openSUSE Leap 15.5: 2.39
Tumbleweed: 2.40
linked Mageia example: 2.32
```

Of course i am not a regex or godot expert and may have missed many things.
It might be useful to know, how the version string looks like in other distributions.

### Steps to reproduce

build engine

### Minimal reproduction project

-

**Comment by akien-mga** [comment]
Fixed by #87464.
