### ISSUE TITLE
There was no way to set GraphNode's title font color

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#82085]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Windows 10, 64bit

### Issue description

There was no way to set GraphNode's title font color

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by YuriSizov** [comment]
See https://github.com/godotengine/godot/pull/82129#issuecomment-1732362685.
