### ISSUE TITLE
error NU1101: Package not found Microsoft.NETCore.App.Runtime.linux-bionic-arm. A package with this ID does not exist in source nuget.org

### ISSUE THREAD

**Issue by Oyama-Oyama** [godotengine/godot#82095]
### Godot version

4.2 dev5

### System information

mac 12.6.7

### Issue description

I ran into this issue when exporting apk to Android armeabi-v7a. 
error NU1101: Package not found Microsoft.NETCore.App.Runtime.linux-bionic-arm. A package with this ID does not exist in source nuget.org

### Steps to reproduce

.

### Minimal reproduction project

.

**Comment by raulsntos** [comment]
@aligmayu Make sure you are targetting .NET 7.0, see https://docs.godotengine.org/en/4.2/tutorials/scripting/c_sharp/index.html#c-platform-support.
