### ISSUE TITLE
Plugin VGamePad for touchscreen gamepad can only process single touch

### ISSUE THREAD

**Issue by Chatto** [godotengine/godot#8210]
**Operating system or device - Godot version:**
I'm f***ing awesome so I use Ubuntu Studio. All other Operating Systems are inferior and "stoopid"

**Issue description:**

So I know this is probably in the wrong place, so link me to where I can post this and it will be done!

**Steps to reproduce:**
Load and install the VGamePad plugin via the asset library, and publish to a mobile device(I used android on my HTC One). It can only process the currently focused control. I have this plugin used to move a 3d character around with the analog stick and an "A Button" for jump...having to release the analog stick to perform a jump is worse than "ET Adventures" and I don't even have a successful movie franchise to fall back on...

**Link to minimal example project:**

<minimal example>
I double dog dare you to pick a fight with that rabid possum in the dumpster!
</minimal example>

I know Godot is capable of multitouch, so I suppose this isn't so much an "Issue" as it is me asking for help making multitouch work with this plugin. If it's not a simple edit and is an involved task, can you find me a link to the author's GIThub maybe? Thanks!

**Comment by akien-mga** [comment]
You can find the upstream URL in the assetlib, both in editor or the web frontend: https://godotengine.org/asset-library/asset/50

Namely, it's this GitLab repo: https://gitlab.com/DigiGodotPlugins/DigiVGamepad
