### ISSUE TITLE
solved: EditorPlugin (CONTAINER_CANVAS) mouse

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#82104]
### Godot version

4.2 Dev5

### System information

Windows 10

### Issue description

In plugIn editor / @tool / extends EditorPlugin
adding a scene to: add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT)

The mouse coordinates are related to the main screen, and not the  ( CONTAINER_CANVAS_EDITOR_SIDE_RIGHT )

All the button's are working with the mouse, 
but its impossible to get the mouse to interact with any other node, in  ( CONTAINER_CANVAS_EDITOR_SIDE_RIGHT )

There is no info about it in the manual, or the web. 

![plugINmouse](https://github.com/godotengine/godot/assets/77213594/c9bbfb66-c10c-4176-bd92-9da4c03a9ebc)

.

### Steps to reproduce

create a scene, with:
control node,
SubViewportContainer,
SubViewport,
camera2D,
sprite;

create a script EditorPlugin:
add the scrip to autoLoad,
load the scene in the script,
add the scene to a container canvas: add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT, scene );

cant find the mouse in the right panel

### Minimal reproduction project

[DockError.zip](https://github.com/godotengine/godot/files/12698950/DockError.zip)

**Comment by jonSP12** [comment]
fixed
var mG = dockedScene.get_local_mouse_position();

dont know why... it never worked before, but it worked now

**Comment by Sauermann** [comment]
Closing this Issue as noted in the post above.
It is possible, that this has been solved by #71768.
