### ISSUE TITLE
Memory Leak in Godot C#

### ISSUE THREAD

**Issue by tex111** [godotengine/godot#82112]
### Godot version

4.1.1

### System information

Windows 11

### Issue description

I was working on porting over a game from GDScript to C# and noticed that when I was moving a character around the tile map the godot monitor showed objects and memory usage steadily increasing over time.

This issue did not exist in the GDScript version of the code.

### Steps to reproduce

In the included project. Launch the game and move the blue square with WASD and watch the godot monitor. Objects will settle around 1305 at the start and, after some quick noodling left and right, will rise to 1500+ and not decrease after waiting for a minute.

### Minimal reproduction project

[MemoryLeak.zip](https://github.com/godotengine/godot/files/12700390/MemoryLeak.zip)

**Comment by Zireael07** [comment]
Most likely something in the input? IIRC it was reported a couple times

**Comment by raulsntos** [comment]
C# uses a [Garbage Collector](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/) so objects won't be immediately disposed. To check if this is an actual memory leak, try adding this code and see if it makes a difference:

```csharp
GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
GC.WaitForPendingFinalizers();
```

If this fixes the issue then there is no memory leak, it's just the normal behavior of the GC.

**Comment by tex111** [comment]
> C# uses a [Garbage Collector](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/) so objects won't be immediately disposed. To check if this is an actual memory leak, try adding this code and see if it makes a difference:
> 
> ```cs
> GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
> GC.WaitForPendingFinalizers();
> ```
> 
> If this fixes the issue then there is no memory leak, it's just the normal behavior of the GC.

I added this to physics process and it does indeed seem to fix the issue. I am puzzled why these objects were lingering in memory for more than a minute in my unedited test project. At scale that will be unacceptable. How often does the c# GC run or is something not getting flagged correctly for deletion? It would feel hacky to force the gc to run every physics frame in order to keep memory from ballooning.

**Comment by tex111** [comment]
> The GC is not time-based, collections are triggered when it runs out of memory. I wouldn't recommend triggering collection manually other than for debugging, if you need to dispose of the objects right away use `Dispose` (but keep in mind that disposed objects can't be used after they've been disposed).

Then we return to the original issue memory leak issue. Something about my fairly basic use case is creating memory and not freeing it and I don't know why. If you look at the code you will see I am not allocating something that I can really call dispose on each time the player moves. 

`private void Move(Vector2I targetTile)
	{
		Game.Level.Tiles[Tile].Character = null;
		Game.Level.Tiles[targetTile].Character = this;
		GlobalPosition = Game.Level.GetGlobalFromTile(targetTile);
		Tile = targetTile;
	}`

**Comment by raulsntos** [comment]
> Something about my fairly basic use case is creating memory and the garbage collector is not freeing it unless I run your command and I don't know why.

The reason is likely that the GC has not decided that its worth collecting yet. A collection is performed when the allocated memory surpasses some threshold, so maybe you haven't reached it. The GC is a complicated topic, but if you want to learn more about how it works and how it determines when to collect, you may read the [_Fundamentals of garbage collection_](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals) page in Microsoft's documentation.

> Taking another look at my code I'm not seeing anything that I could call dispose on.

It's probably the `InputEvent` objects, but you don't have to, they'll eventually be released if they have to. If you do dispose them, be careful not to use them afterwards or it'll throw an exception. In general, I wouldn't bother disposing these events and just let the GC do its job.

**Comment by Zireael07** [comment]
This is like the third or fourth similar issue where InputEvents disposal is slightly problematic to people new to C# . Could this be better documented?

**Comment by raulsntos** [comment]
I think so, I mention a few ideas in https://github.com/godotengine/godot/issues/78065#issuecomment-1585564014. I'll close as duplicate to consolidate in https://github.com/godotengine/godot/issues/78065.

**Comment by TarjeiM** [comment]
> C# uses a [Garbage Collector](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/) so objects won't be immediately disposed. To check if this is an actual memory leak, try adding this code and see if it makes a difference:
> 
> GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
> GC.WaitForPendingFinalizers();
> If this fixes the issue then there is no memory leak, it's just the normal behavior of the GC.

This saved me.
