### ISSUE TITLE
Remove Patch9Frame

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#8212]
Patch9Frame and a Panel with a StyleBoxTexture are effectively the same thing, so I think it should be removed since they're the same thing. I find it redundant to have two things that do the same thing, and only makes maintaining them more of a hassle.

**Comment by blurymind** [comment]
doesnt one take more effort to set up than the other?

Also many developers know what patch9frame means, the word "patch9" is used in other game engines and people know what it does.
Getting the same functionality in godot via two nodes is not something many people coming from other engines will easily figure out. That is one con I can think of - using two nodes in a specific conguration vs using one specialized node seems like a workaround and doesnt allow for forking to add specific patch9 features

Those are the pros in keeping patch9frame node imo
What are the pros and cons of the two approaches?

**Comment by bojidar-bg** [comment]
Adding to the 3.0 milestone so that it isn't forgotten.

**Comment by reduz** [comment]
Theres is NinePatchRect in 3.0

**Comment by toger5** [comment]
what about making the NinePatchRect a node2D? I haven't thought a lot about it yet, but than it would be have like other 2d nodes and simpler to use for people who mostly use node2d for there games. (controls are strong with GUI but not that often used in games so ppl might be more familiar with the concept of scaling instead of `rect_size`)

**Comment by reduz** [comment]
Well, it's a GUI control. We could make a NinePatchSprite if you want

**Comment by toger5** [comment]
what I'm proposing is removing the ninePatchControl and adding the 9patchSprite.
Ppl who do Gui know about themes, are familiar how to use them and don't mind the extra click on: `new styleBoxTexture`.
ppl who are just searching for a 9patch node, have everything they need with a sprite.

**Comment by reduz** [comment]
It doesnt make sense to remove it from GUI, as a lot of people asked for it
in the past. It's in line with TextureButton, TextureProgress and the like
for simpler UIs. It's also a very small class, no harm in having both.

**Comment by reduz** [comment]
closing this. If anyone wants a nine patch sprite, just do a PR..but honestly current control should work fine for 2D anyway and is easier to edit.
