### ISSUE TITLE
Lightmap set to directional bake normal with too little strength 

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#82125]
### Godot version

Build from PR (Calinou:lightmapgi-static-directional-fix-brightness) To have the correct energy

### System information

Ubuntu with Nvidia 2060

### Issue description

Lightmap set to directional bakes the normal with little to non strength 

Directional
![image](https://github.com/godotengine/godot/assets/1168582/8ccb10a0-b935-4f88-b767-1a04c1fca57a)

Off
![image](https://github.com/godotengine/godot/assets/1168582/0f36d813-dc2b-4e0b-8ba5-f450b28019dd)

### Steps to reproduce

Bake lightmap from MRP with directional set to true

### Minimal reproduction project

[Lightmap.zip](https://github.com/godotengine/godot/files/12702198/Lightmap.zip)

**Comment by jcostello** [comment]
Seems that the normal map is not baked at all. If I remove the normal from the material (disabled or I lover the intensity) after the bake, there is no normal information

**Comment by jcostello** [comment]
Seems to be working in master [4c5a14845]. IDK if something change but if someone whats to try this before I close the issue

**Comment by Calinou** [comment]
I don't see any normal map after baking lightmaps in 4.2.rc2 with Directional **disabled**:

![image](https://github.com/godotengine/godot/assets/180032/3587fb6a-ded1-4fda-b29c-7624ac9e3d54)

I only see it before baking lightmaps.

**Comment by Calinou** [comment]
Indeed, it works as of 4.2.rc2:

![Screenshot_20231129_150649](https://github.com/godotengine/godot/assets/180032/d5fed798-0886-4fc3-9133-d24f35546f6c)

SDFGI for comparison:

![Screenshot_20231129_150726](https://github.com/godotengine/godot/assets/180032/8409f95f-69ca-4d34-9334-cb2dee310084)
VoxelGI:

![Screenshot_20231129_150745](https://github.com/godotengine/godot/assets/180032/8ffdcc97-df99-4f02-969a-7caa9db77803)

**Comment by atirut-w** [comment]
Directional lightmap seems significantly weaker :/

**Comment by Calinou** [comment]
> Directional lightmap seems significantly weaker :/

I don't know if it's weaker, or if VoxelGI/SDFGI's normal influence is too strong. SDFGI has known issues on this aspect in particular.

Ideally, this should be compared against a ground truth reference renderer like Blender Cycles or Mitsuba.
