### ISSUE TITLE
Add Child Error when entering godot window (on ANY project)

### ISSUE THREAD

**Issue by AcoAlexDev** [godotengine/godot#82120]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 11 - Mobile or Forward+ - v4.1.0 and 4.1.1

### Issue description

For the past three days, I have been encountering a message in the **output** whenever I entered the screen or launched the game on one project:

>  Parent node is busy setting up children, `add_child()` failed. Consider using `add_child.call_deferred(child)` instead.
  scene/main/window.cpp:1565 - Condition "!is_inside_tree()" is true.

Initially, I updated from 4.1.0 to 4.1.1, but that did not resolve the error.

Then I assumed that I had made some mistake on that project and I had to tolerate the error.

However, today I created a brand new project and simply added a control node and now the same error is displayed in the output again when entering the Godot window or running the project:

![godot-error](https://github.com/godotengine/godot/assets/130444898/2aebb3c5-a9be-4fd3-9496-9b5d4ca45d95)

The error occurs regardless of whether the project is new or old.
And it also appears in older Godot versions now, such as v4.0.0.

### Steps to reproduce

I am perplexed by the appearance of this error, which seems to affect every project regardless of its status. It does not make a difference whether the project is new or old. Moreover, the error persists in older versions of Godot, such as v4.0.0.

### Minimal reproduction project

[Add_child error.zip](https://github.com/godotengine/godot/files/12701330/Add_child.error.zip)

This is a sample project where the error is visible. It originally occurred in a very large project, but I have no idea what causes the error.

**Comment by Calinou** [comment]
Can you reproduce this if you enable [self-contained mode](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode) for the editor, so that it uses default editor settings?

If not, please post the contents of `%APPDATA%/Godot/editor_settings-4.tres`.

**Comment by AcoAlexDev** [comment]
Dear Sir Locurico,

I am writing to inform you that I have identified the cause of the bug that we encountered in our project. After testing the program in self-contained mode and verifying that it worked correctly, I proceeded to reset each setting one by one and observe the effect. I discovered that the option 'interface/editor/save_on_focus_loss' was responsible for triggering the 'add_child' bug when set to true. I am not sure if this is an intended feature or a design flaw, but it is certainly confusing and misleading.

I hope this information helps you to resolve the issue. Please let me know if you have any questions or concerns
________________________________
Von: Hugo Locurcio ***@***.***>
Gesendet: Freitag, 22. September 2023 19:03
An: godotengine/godot ***@***.***>
Cc: AcoAlexDev ***@***.***>; Author ***@***.***>
Betreff: Re: [godotengine/godot] Add Child Error when entering godot window (on ANY project) (Issue #82120)


Can you reproduce this if you enable self-contained mode<https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#self-contained-mode> for the editor, so that it uses default editor settings?

If not, please post the contents of %APPDATA%/Godot/editor_settings-4.tres.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73765.

**Comment by mcdz** [comment]
Turning off --> editor settings > interface > editor > save on focus loss
This fixed it for me too. thanks.
