### ISSUE TITLE
Blender import error Returning: ERR_FILE_CANT_OPEN

### ISSUE THREAD

**Issue by Felina-Lain** [godotengine/godot#82143]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 10 & Blender 3.6.3

### Issue description

When importing a blender file in Godot, it won't import and instead gives me an error message:

modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Mesh/sol.blend'.

I looked up on google, and it was mentioned as a Linux error, but I'm not on Linux, or an error due to having downloaded not from blender website, but I did just that.

### Steps to reproduce

Create blend file, leave the default cube in it to serve as test
import blend file into godot
Watch the error messages pour in as godot will attempt to re-import every so often, with no success

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you test this with Blender 3.5.x? Blender 3.6 isn't supported yet as per https://github.com/godotengine/godot/issues/76338.

**Comment by Felina-Lain** [comment]
> Can you test this with Blender 3.5.x? Blender 3.6 isn't supported yet as per #76338.

I just tried, fresh 3.5.0 download, created new blend file, saved it, tried to import it, same error

**Comment by mieldepoche** [comment]
blender 3.6.3 works on my end (Ubuntu, godot 4.1.1).

**Comment by Felina-Lain** [comment]
> blender 3.6.3 works on my end (Ubuntu, godot 4.1.1).

Following this, I decided to try with a non-portable install of 3.6.3, and this time it worked!
I think I messed something with my portable install, sorry for the false report
