### ISSUE TITLE
Scrolling over code suggestions not working using macbook trackpad

### ISSUE THREAD

**Issue by juju8e** [godotengine/godot#82149]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

macOS Ventura 13.4.1

### Issue description

Scrolling suggestions list inside code editor scrolls the entire page instead if using macbook trackpad. 
I tried it with regular mouse and find out that it works like expected so it is definetly trackpad-related issue.

Expected behaviour:
- if mouse is over suggestions -> scroll suggestions
- otherwise -> scroll the entire page

Attaching two videos. On the one I'm using mouse and everything works well, on another one I'm trying to do the same with trackpad.

https://github.com/godotengine/godot/assets/67281067/879534cb-36e7-4b26-a1d6-78cc3433380a
https://github.com/godotengine/godot/assets/67281067/4b7184a9-b301-4c6f-8cb6-6c1be36b16db

Even though it looks like a minor issue it is still super annoying and ruins experience using code editor, making suggestions almost useless if you are using macbook. Aiming that tiny little scrollbar as a fallback is one of the hardest things I've ever encountered.

### Steps to reproduce

- open godot project on macbook laptop
- create gdscript
- open it with built-in code editor
- try typing anything to make suggestions appear
- make sure suggestion list is long enough to scroll
- hover mouse over it and try scrolling
- see the entire page scrolling instead of suggestions

### Minimal reproduction project

No setup required. Editor issue.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/28149 and https://github.com/godotengine/godot/issues/49873.

**Comment by juju8e** [comment]
> Thanks for the report! Consolidating in #28149 and #49873.

Thanks! I also took a look at those issues and want to point out that this is not smoothness issue . In my case it just doesn’t  work, so hope you guys will fix it all at once at some point I guess.
