### ISSUE TITLE
Inconsistent snapping intervals when resizing cubes using the new gizmo

### ISSUE THREAD

**Issue by ashelleyPurdue** [godotengine/godot#82153]
### Godot version

4.2.dev5.mono.official

### System information

Godot v4.2.dev5.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

If you hold CTRL while resizing a cube(or any object, for that matter), the interval that it snaps to will change depending on what size the cube was when you started resizing.

### Steps to reproduce

* Create a CSGBox3D node at (0, 0, 0), with a size of (1, 1, 1).
* Select the cube
* While holding CTRL, click and drag the top face's "handle" and move it upwards until the box's size is (1, 2.5, 1).  Notice that while you were doing this, the size was snapping to multiples of 0.5 (1.5, 2, 2.5, etc.)
* Release the left mouse button
* While still holding CTRL, click and drag the same "handle" again, and try to move it upwards until the box's size is (1, 4, 1).  Notice that this is now impossible; it will end up snapping to the values 2.75, 3.25, 3.75, 4.25.
* Release the left mouse button
* While still holding CTRL, click and drag the same "handle" again, and try to move it upwards until the box's size is (1, 5, 1).  Now it will snap to even _weirder_ values.

Expected result: the size stays snapped to a grid of 0.5, hitting the values 1.5, 2, 2.5, 3, 3.5, 4, 4.5, and 5.  This should be consistent even when you let go of the left mouse button and then click again.

Actual result: Every time you release the left mouse button and re-click, the size will become progressively more misaligned from the grid.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/81916.
