### ISSUE TITLE
Fully Metallic Materials Disable AO Map

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#82164]
### Godot version

4.1.1 Stable

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

The effect of an AO map is diminished as metalness of a Standard Material increases. It loses its effect entirely once Metallic reaches 100%.
This does not affect the Light Affect property.

### Steps to reproduce

- Create a Standard Material with an AO map and Metallic set to 1
- Reduce Metallic to reveal the AO

### Minimal reproduction project

[AOLightAffectBug.zip](https://github.com/godotengine/godot/files/12705397/AOLightAffectBug.zip)

**Comment by briansemrau** [comment]
https://github.com/godotengine/godot/blob/2048fe5df5f19a5467a6fc61b9c00fe41886b134/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L2251-L2254

Looking through the git history, it looks like this was intentionally implemented.

I'm not a professional in 3D rendering, but I just did a quick read from Real Time Rendering, and to my understanding, ambient occlusion is intended for diffuse materials. It is dependent on approximations that assume a totally diffuse scene with simple lighting. If you want to create more realistic metallic surfaces, you should use metallic/normal map textures to introduce detail. And consider enabling SSR(+SDFGI) which are a better physical model for glossy/metallic surfaces.

**Comment by WickedInsignia** [comment]
Ahhh this makes sense.
I think it's still useful to have for artistic purposes since you'll naturally have a decrease in light/reflections in crevices, even if they're fully metallic. It's not _entirely_ physically accurate but it is an approximation of the way that light behaves on a macro scale that SDFGI and SSR can't accurately predict. It's also just a nice technique to create more readability and depth.

Might be good to expose an "affect metallic" option? I'm not sure how possible it is to enable AO on metallic surfaces in VisualShaders either, maybe that would be a less bloat-inducing option.

**Comment by Calinou** [comment]
What you probably want is https://github.com/godotengine/godot/pull/50601 :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/pull/89988, as feature proposals are tracked on the godot-proposals repository.
