### ISSUE TITLE
ENet packet is implicitly rejected if too big

### ISSUE THREAD

**Issue by manglemix** [godotengine/godot#82160]
### Godot version

v4.1.1.stable

### System information

Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.2802) - AMD Ryzen 9 5900HS with Radeon Graphics (16 Threads)

### Issue description

My use-case is quite complicated, so I am not fully sure that the packets are being rejected because they are too big. However, based on what my `ENetConnection.pop_statistic(ENetConnection.HOST_TOTAL_RECEIVED_DATA)` returns, I can in fact prove that the large packets are reaching `ENet` itself. However, while calling `host.service(200)`, I do not receive any event, nor any error. I have also verified that my client is in fact the one sending these large packets. Also, by large I mean above 800 bytes (800 seems to be about the maximum receivable size). Removing compression is not possible on the client end. The added complexity of my use case is described in **Steps to reproduce**. Since it is so complicated, I am simply looking for debugging advice.

### Steps to reproduce

Here are the steps:

1. Start a default ENet server binded to localhost in Godot
2. Start an SSH tunnel from localhost to a remote computer
3. On the remote computer, connect with an ENet client using the `pyenet` library
4. Repeatedly send large packets from the client and verify that they are or are not being received in Godot. For packet flags, use unsequenced and unreliable_fragment

The added complexities include converting the TCP SSH Tunnel to and from UDP, and the fact that my actual SSH Tunnel goes through a Unix Socket. I am fairly certain that despite all this, all traffic is passing through the the server, but I can't be sure that that is not having an effect.

### Minimal reproduction project

[My repo](https://github.com/utahrobotics/lunadev-2024)
The client side code may not be of any use to anyone as it is in pure Python

**Comment by Faless** [comment]
> 4\. or packet flags, use unsequenced and unreliable_fragment

By using these settings you are telling ENet to transmit the packet unreliably after fragmentation.
This means that the data will be fragmented to N packets of at most MTU size.
For ENet the MTU is `1392` bytes, so e.g. a 1MiB packet will be fragmented into **754 small packets**.
If any of those packets is lost, or arrive out of order, the whole message will be discarded.

You may want to use reliable transfer/fragmentation or, if that is not sustainable by your network, implement your own fragmentation and flow control algorithm.
