### ISSUE TITLE
Visual Shader Arrange Nodes button crashes Godot

### ISSUE THREAD

**Issue by CarlisleJonah** [godotengine/godot#82166]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 10

### Issue description

In the Visual Shader editor, clicking Arrange Nodes crashes Godot.

### Steps to reproduce

Click Arrange Nodes in the Visual Shader editor with the reproduction project. Sometimes it works on first click, sometimes it takes a few clicks. Below is an image of the shader I was fiddling with that caused this to happen (I assume).

![image](https://github.com/godotengine/godot/assets/52836391/9836be2a-6f27-4142-b3dc-5cace0053b78)

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/12705425/Test.zip)

**Comment by fire** [comment]
I want to investigate the Arrange button, but I'm not able for a few days. Help welcome.

**Comment by qycyfjy** [comment]
https://github.com/godotengine/godot/blob/c12d63556b5c1da03a00dd4c45c40e60bd8d68c2/scene/gui/graph_edit_arranger.cpp#L106

It seems that `_layering` function is causing the problem.

Assume that layer one includes two nodes, "3" and "13", but in the layers returned by `_layering()`, the elements of that layer may be "3", "3", "13", which means a "3" is repeated (interesting, if repetition happens, that is the repetition of the first element, I'm not sure if it's always like this, I haven't dug into the algorithm of `_layering()` carefully). 

One dirty workaround is to remove all repeated elements in every entry of the returned HashMap, i.e., Vector("3", "3", "13")->Vector("3", "13")

![动画](https://github.com/godotengine/godot/assets/93075932/12953268-fe7e-4ced-87b7-94ce21da09b1)
