### ISSUE TITLE
Export members are duplicated on Inspector when using @tool

### ISSUE THREAD

**Issue by sepTN** [godotengine/godot#82169]
### Godot version

4.2.dev

### System information

Windows 11

### Issue description

There's a bug on `4.2.dev` where the Inspector will shows the duplicated exported members of a child class that extends its parent class. 

- Only happens in the latest `4.2.dev` 
- Reopening the same project in  **4.1.1.stable**, works as expected
- Removing the @tool and then reopening the project again, doesn't trigger the bug

### Steps to reproduce

- Make a new scene call it `animal.tscn`
- Attach new script to it `animal.gd` with this content
```gdscript
@tool
class_name Animal extends Node2D

@export var height := 50
@export var weight := 10
@export var limbs := 4
```
- Make a new scene call it `dog.tscn`
- Attach a new script to it `dog.gd` that extends the animal.gd with this content
```gdscript
@tool
class_name Dog extends Animal

@export var dog_name := "Barkie"
@export var owner_name := "Joe"
```
- Open the project using **4.2.dev** and you will see the exported members are duplicated
![image](https://github.com/godotengine/godot/assets/13846022/5a7ae2af-c299-431f-b544-c809e005c650)

- Open the same project using the **4.1.1.stable** and you will see that it works as intended, no exported members duplication
![image](https://github.com/godotengine/godot/assets/13846022/00b9cdd9-5d1f-48a3-8180-96c0110a2d6e)

### Minimal reproduction project

[sample.zip](https://github.com/godotengine/godot/files/12705726/sample.zip)

**Comment by kleonc** [comment]
Fine in v4.2.dev4.official [549fcce5f].
Broken since v4.2.dev5.official [e3e2528ba].

**Comment by tokengamedev** [comment]
I also faced the issue but, could not reproduce it. For me it was calling the setter method twice also.
