### ISSUE TITLE
`is_connected` not return correctly

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#82170]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Windows 11, Vulkan API 1.3.205 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

I'm working on a plugin. The project has a singleton which contains some singals. When I open the project, it seems that these singals have been connected twice even I use `is_connected` to check first. This problem happens when the scene tab (which has a script to connect singals) is actived by Engine when openning project.

```
@tool
extends Control

func _ready():
	var global_conf: GlobalConfClass = Engine.get_singleton("GlobalConf")
	printt("11111", global_conf.get_signal_connection_list("signal_foo"))
	
	if not global_conf.signal_foo.is_connected(deal_foo):
		printt("22222", "connect signal")
		global_conf.signal_foo.connect(deal_foo)
	
func deal_foo():
	pass
```

output:
```
11111	[]
22222	connect signal
11111	[{ "signal": Node(global_conf.gd)::[signal]signal_foo, "callable": Control(my_plugin_main.gd)::deal_foo, "flags": 0 }]
22222	connect signal
```

These logs shows that the script runs twice which can be understood: first time is for the plugin actived (by `EditorInterface.get_editor_main_screen().add_child(main_panel_instance)`
![image](https://github.com/godotengine/godot/assets/42859362/29ac75f1-158e-4502-a69f-5a322b45fa75)
), second time is for the scene tab is actived(
![image](https://github.com/godotengine/godot/assets/42859362/fb07f06c-0e21-4074-a100-03d80360dfff)
)

But the second `11111 ...` shows that the signal was already connected however it fails to check `global_conf.signal_foo.is_connected(deal_foo)` so that the signal was connected twice.

### Steps to reproduce

1. download Minimal reproduction project.
2. open project.
3. check console outputs

If you do not see this issue:
4. make sure the tab of `my_plugin_main.tscn` is actived
5. close project
6. reopen project

### Minimal reproduction project

[test_tool_signal.zip](https://github.com/godotengine/godot/files/12705738/test_tool_signal.zip)

**Comment by timothyqiu** [comment]
A `Callable` consists of an `Object` instance and a method name. `global_conf.signal_foo.is_connected(deal_foo)` is checking whether the signal is connected to the `deal_foo` function **of current instance**.

The node the plugin is using and the node the current scene is editing are two different instances.
