### ISSUE TITLE
Changing type of node loses the export variables in the inspector

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#82187]
### Godot version

4.2.dev.5

### System information

Windows 11

### Issue description

When a node type changed for a Node inheriting from `Control` like `TextureRect `to a node type inheriting from `Node2D` like `Sprite2D`. Inspector stops displaying the export Variables.
It requires scene reloading, whereas changing node from `TextureRect `to `Control` does not require scene reloading. 

Similar issues I have reported earlier like https://github.com/godotengine/godot/issues/81972 

### Steps to reproduce

Create a Node inherting from Control or Control itself.
Save the scene and attach a script
add a export variables like below
```gdscript
@export var count:int = 0
```
This will display the export variables in inspector.
Now change the type to `Node2D `or `Sprite2D`
Change the script's `extends `value appropriately.

Now the Export variables will not be displayed anymore in inspector.

Even after trying to rewrite the code or revert back the Type change also.

It will only be shown when scene is reloaded.

### Minimal reproduction project

If required I can provide it.

**Comment by tokengamedev** [comment]
Reproducible in 4.2.dev.6 also

**Comment by tokengamedev** [comment]
This issue can be closed as it seems it is working as designed in 4.2.beta.2

The way it is working is as follows:

- If you change the type from A to B and the script is extending/inheriting the Type B, then it holds the export variables.
- If you change the type from A to B and the script is **not** extending/inheriting the Type B, then it does not hold the variables.
It throws up an error.
`Script inherits from native type 'B', so it can't be assigned to an object of type 'A'.`

I think it is the right approach. No fix required here in my perspective.

**Comment by Calinou** [comment]
Closing per the above comment. (In the future, remember that you can close your own issues :slightly_smiling_face:)

**Comment by tokengamedev** [comment]
Thanks I will do.
