### ISSUE TITLE
Theme type variations don't work for Panel, Label, Button, Tree, etc.

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#82199]
### Godot version

4.2.dev5(c12d635)

### System information

MacOS

### Issue description

Theme type variations stopped working somewhere between 4.2dev4 and 4.2dev5.

### Steps to reproduce

Add and assign a new type variation to any of the title classes.

### Minimal reproduction project

[theme_variation_bug.zip](https://github.com/godotengine/godot/files/12706905/theme_variation_bug.zip)

**Comment by kleonc** [comment]
cc @YuriSizov

**Comment by YuriSizov** [comment]
Right, so it kind of worked by accident originally, since it's a fixed bug in logic that caused this regression. The fix is going to make things a bit slower, but I guess there is no way around it.
