### ISSUE TITLE
The Default theme should correspond to the system theme.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [godotengine/godot#82208]
### Godot version

> 4.1.1.stable.official

per

> ![Screenshot_20230923_204349](https://github.com/godotengine/godot/assets/42837531/8404a27c-6d84-47b2-b16b-a84096fb1872)

### System information

Linux s1e8h4 6.5.3-1-default #1 SMP PREEMPT_DYNAMIC Thu Sep 14 08:46:53 UTC 2023 (786e0d6) x86_64 x86_64 x86_64 GNU/Linux

### Issue description

**https://godotforums.org/d/36365-should-the-default-theme-correspond-to-my-system-theme**

<blockQuote>

It doesn't, for me.

![image](https://github.com/godotengine/godot/assets/42837531/4c6e5db1-2d22-41ab-82cd-5f68f87fc815)

It should correspond to Breeze Dark.

![image](https://github.com/godotengine/godot/assets/42837531/6b0fcb16-8f40-40ba-9b3e-2c48d28d55ee) ![Screenshot_20230923_204255](https://github.com/godotengine/godot/assets/42837531/2eb54a64-da3e-45ef-aabe-74de71c18329)

</blockQuote>

### Steps to reproduce

Install from Steam.

### Minimal reproduction project

Not relevant.

**Comment by YuriSizov** [comment]
We can't realistically have a set of editor themes that would fit any give system color theme. Instead, we offer a number of pre-configured themes as well as an easy way to tune the base and the accent color as you see fit.

And the default theme is Godot's own main theme. It's part of the engine's identity and style. It's not supposed to color match the environment. Instead it provides a neutral but unique look that is at the same time pleasant to use but sets Godot apart.

If you want to propose changes to the editor themes, please [open a proposal](https://github.com/godotengine/godot-proposals/discussions).

**Comment by RokeJulianLockhart** [comment]
<blockQuote>

Thanks for your suggestion! We can't realistically have a set of editor themes that would fit any give system color theme. Instead, we offer a number of pre-configured themes as well as an easy way to tune the base and the accent color as you see fit.

And the default theme is Godot's own main theme. It's part of the engine's identity and style. It's not supposed to color match the environment. Instead it provides a neutral but unique look that is at the same time pleasant to use but sets Godot apart.

</blockQuote>

Then you've misinterpreted the request, @YuriSizov. The theme *which the aforeplaced images depict* is already provided by Godot - it already adheres to the system theme if the user merely tells it which *is* the system theme. All that is absent is the code to determine which theme *corresponds* to the colouration in use by the system. It's a very trivial addition.

**Comment by YuriSizov** [comment]
The editor theme is simply inspired by its namesake. There is no mechanism nor intended feature for the editor to be able to pick a system theme with the same name and automatically set the editor to use its namesake.

Hence there needs to be a proposal that describes how such feature could be implemented, and why.

**Comment by RokeJulianLockhart** [comment]
~~And yet it perfectly reads the values of that same theme, knowing that it is in fact the current theme? If I switch to Breeze Light, it offers~~

Apologies, you appear correct. Since it offers Breeze Dark, I expected that it was reading those values dynamically, rather than there being a statically defined theme with the same name. I should have tested activating Breeze Light and ascertaining whether it could see that theme too.
