### ISSUE TITLE
Godot crashing after a few moments in the editor.

### ISSUE THREAD

**Issue by SatoTsukasaCode** [godotengine/godot#82206]
### Godot version

4.1.1 from steam and from the website

### System information

Windows 10 (foraward+) gpu: Intel UHD Graphics

### Issue description

Hello.
I have tried to start a new project and faced a concerning issue.
every time i open the project or any other project, Godot becomes unresponsive and crashes after a bit.
Happened both on the Steam version and the website version. I have checked the integrity of the files, they were fine.

I did clear the cache and the editor worked for a bit but then crashed again.

### Steps to reproduce

open the project and let it run for a few moments.

### Minimal reproduction project

[prototype.zip](https://github.com/godotengine/godot/files/12707162/prototype.zip)

**Comment by dalexeev** [comment]
I can't reproduce the bug. Please run the editor from command line, reproduce the crash, and post the crash dump here. This will greatly simplify finding and fixing the bug.

Note that you need a build with debug symbols. See [the docs](https://docs.godotengine.org/en/stable/contributing/development/compiling/introduction_to_the_buildsystem.html#dev-build) or [Calinou/godot-debug-builds](https://github.com/Calinou/godot-debug-builds/releases) (but it not updated from 4.0.3, which may not have the bug).

**Comment by SatoTsukasaCode** [comment]
Seems like a graphics issue.
```
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
OpenGL API 3.3.0 - Build 31.0.101.2125 - Compatibility - Using Device: Intel - Intel(R) UHD Graphics

Editing project: C:/Users/Sato/Documents/prototypes
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.215 - Forward+ - Using Vulkan Device #0: Intel - Intel(R) UHD Graphics

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2360)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2360)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2360)
```

**Comment by SatoTsukasaCode** [comment]
Same error on the 4.0.3 debug build.
I also forgot to mention, before I posted the issue, i tried using the LTS 3.5.2 and had no issues.

**Comment by Zireael07** [comment]
Not surprising that 3.5 works since this is a Vulka n problem.

**Comment by SatoTsukasaCode** [comment]
yup

**Comment by jw-0** [comment]
Couldn't replicate this one. Sounds like it might be an issue with your GPU. Can you try updating your drivers?

**Comment by SatoTsukasaCode** [comment]
They are a updated. it might be the new version that is causing the problem...

**Comment by Calinou** [comment]
Please [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/80566 locally and see if it resolves the issue on your end.

**Comment by SatoTsukasaCode** [comment]
#80566 work.

**Comment by SatoTsukasaCode** [comment]
issue seems to be fixed on the stable version on steam.
