### ISSUE TITLE
"Play" shortcut variation that doesn't restart project

### ISSUE THREAD

**Issue by elasota** [godotengine/godot#8222]
It's not currently possible to bind shortcuts in a way that mimics Visual Studio's F5 behavior, where the key launches the project if it's inactive and continues the code debugger if it's active because the "Play" shortcut remains active while the project is running, and using it restarts the project.  It also takes priority over "Continue" if the two are bound to the same key.

This could be improved by adding a separate shortcut that plays the project if it's not running, and does nothing if it is running.  Maybe rename "Play" to "Restart" or "Play/Restart" and name the new option "Play?"

**Comment by kubecz3k** [comment]
I'm in the process of revisiting old issues. It has been more than year since this proposal was published and it don't seems to get any interest, will close for now.
