### ISSUE TITLE
Applying ragdoll physics to an imported model causes the model to scale 10x and freak out

### ISSUE THREAD

**Issue by jonko0493** [godotengine/godot#82223]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 27.20.100.9268) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 Threads)

### Issue description

I added a model with a skeleton, selected its Skeleton3D node, and did Create Physical Skeleton. I then addded `PhysicalBonesStartSimulation()` to the `_Ready` method of the script attached to the Skeleton3D node in order to create a ragdoll. Upon running, this results in the model increasing about 10 times in size and behaving erratically.

### Steps to reproduce

1. Add a model with a Skeleton3D
2. Create Physical Skeleton
3. Attach a script to the Skeleton3D and add `PhysicalBonesStartSimulation()` to the `_Ready` method
4. Run game, observer very large model

### Minimal reproduction project

[MinimalRepro.zip](https://github.com/godotengine/godot/files/12707841/MinimalRepro.zip)

**Comment by jonko0493** [comment]
Okay!! I think I figured this out. The issue was just that the physical bones seemed to ignore the transform changes i was making to the model and resized it.

**Comment by GeekzGamingz** [comment]
How did you fix it?

**Comment by AnxiousGorilla** [comment]
@jonko0493 Could you please tell us how you fixed this issue?
