### ISSUE TITLE
Pixel font has some characters in the middle thicker

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#82220]
### Godot version

v4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4502) - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/69117768/d08a0007-6d51-40c7-a7b0-4ac01fe03d3f)

It gets thicker in the middle. Is there no setting that will make the letters snap to pixels so this can be avoided? I have turned off all subpixel settings. If I change the font size it looks even worse, this is the best it gets.

### Steps to reproduce

Use some pixel art fonts.

### Minimal reproduction project

it won't let me upload a ttf file, but you can probably find one yourself

**Comment by Calinou** [comment]
The screenshot uses integer pixel scaling, so it's not due to uneven pixel scaling:

![image](https://github.com/godotengine/godot/assets/180032/491403a9-9ca0-4a5d-bc2d-bcf5c3baa04a)

> it won't let me upload a ttf file, but you can probably find one yourself

Please upload the entire minimal reproduction project, as the TTF file on its own wouldn't suffice to reproduce the issue anyway.

**Comment by ShatReal** [comment]
[test.zip](https://github.com/godotengine/godot/files/12721271/test.zip)

**Comment by inhalt120g** [comment]
Doubleclick on the font resource.
Find the "Subpixel positioning".
Disable it.
Click Reimport.

https://github.com/godotengine/godot/assets/106015575/2db490a6-eaa1-41a5-a717-e3e8097446b4

**Comment by ShatReal** [comment]
Huh that fixed it. I swear, you could write a page in the docs about how to properly use pixel art fonts lol

**Comment by Calinou** [comment]
> Huh that fixed it. I swear, you could write a page in the docs about how to properly use pixel art fonts lol

You said in OP that you disabled subpixel-related settings…

**Comment by Zireael07** [comment]
Tons of people get caught out by having to click Reimport after changing Import settings - can this be made more clear in the interface?

**Comment by Calinou** [comment]
> Tons of people get caught out by having to click Reimport after changing Import settings - can this be made more clear in the interface?

I was thinking about displaying a confirmation dialog if you leave the dialog with unapplied changes (e.g. if you select another file in the FileSystem dock, or attempt to run the project), but this may prove to be annoying.
