### ISSUE TITLE
Terrible performance in Godot 3D using Forward+ in a simple scene

### ISSUE THREAD

**Issue by SaadTheGlad** [godotengine/godot#82238]
### Godot version

v4.1.1

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce MX110 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

I have terrible performance when running a very simple scene which contains one box, a simple player controller and a simple skybox _without glow_ (I will explain why this is important). Here is the scene tree: 
![image](https://github.com/godotengine/godot/assets/39242060/1148fd60-887d-440a-b3b3-05b56d619eca)

When I run the game, and this is without the glow post processing, without V-Sync and these antialiasing settings and world environment settings: 
![image](https://github.com/godotengine/godot/assets/39242060/9fc1bc16-e487-4f55-bc0a-ab0c6e2cdf14)
![image](https://github.com/godotengine/godot/assets/39242060/edad5584-14f9-4a77-81cc-c4d02b9a89c5)

I get around 85fps: 
![image](https://github.com/godotengine/godot/assets/39242060/8fd486c8-7002-4de2-9cf0-1472d583cf54)

Now, this is already terrible as I have practically added nothing yet, but if I add glow as a post processing effect, I get this: 
![image](https://github.com/godotengine/godot/assets/39242060/9d1f1cae-4a1f-4901-a96c-8dae2b8d972e)

It drops to 50fps.

Here is the player movement script that I'm using: https://pastebin.com/8FiraqV6 

This probably has to do with the fact that Godot is using Vulkan, which I hear has some problems, but I'm unsure if it should be causing this much of a performance hit. I can run other games perfectly fine that are much more demanding than a skybox and a CSGbox.

Finally here is my profiler data with the last settings I mentioned: 
![image](https://github.com/godotengine/godot/assets/39242060/f1f278d6-300c-4ff1-9444-fcc3d8ed6651)
_The change in the middle is caused by me alt-tabbing to the game and back_

And the visual profiler: 
![image](https://github.com/godotengine/godot/assets/39242060/c0ebdb80-41de-4f44-9adb-b2298bd58483)

### Steps to reproduce

- Start a basic scene
- Add directional light, the world environment, antialiasing 
- Add basic player movement
- Add FPS counter

### Minimal reproduction project

[minimal reproducation project.zip](https://github.com/godotengine/godot/files/12708418/minimal.reproducation.project.zip)

This project is written in C#. I could not write it in GDScript as I do not know how. Sorry.

**Comment by rsubtil** [comment]
I happen to have an old laptop this this exact CPU and GPU, so I tried this out of curiosity. I've tested launching your scene, staying idle for 5 seconds, and then collect the average FPS values on this laptop, as well as my main setup:

| Testing Settings | Intel i5-8250U / Nvidia MX 110 | Ryzen 5600G / AMD RX 6500 XT |
|------------------|--------------------------------|------------------------------|
| Forward+ Renderer, Glow On | 114 FPS | 687 FPS |
| Forward+ Renderer, Glow Off | 209 FPS (+83%) | 911 FPS (+32%) |
| Compatibility Renderer, Glow Off \* | 343 FPS (+64%) | 2776 FPS (+304%) |

\* *the compatibility renderer still hasn't support for glow* 

I'm getting substantially more performance than in your setup. I'm also getting similar graphs in the visual profiler without any outlier when compared to yours. Might there be any hardware/software issue that's costing you performance?

Regardless of it, in your case it might be better to switch to the compatibility renderer anyways if its current drawbacks don't affect you (lack of glow and 3D shadows are the biggest ones I believe). This was an already entry-level graphics card at the time, and I had some notable performance issues when running Vulkan games when compared to OpenGL, so I think this card has some poor Vulkan driver support.

**Comment by SaadTheGlad** [comment]
@rsubtil Hmm that data you have means that there is definitely something else happening because a difference of almost 60fps between my rig and yours (where they should be identical) is pretty weird. The problem is that I do need shadows and compatibility just doesn't seem viable. It's a shame that Godot only has Vulkan support because not all cards support it properly. I've updated my drivers and everything else so I'm not sure what else I could try at this point...

**Comment by rsubtil** [comment]
Yeah, the compatibility renderer is not a drop-in replacement right now. It will improve in the coming future, but there will still be features that'll be exclusive to the new one.

There's also the possibility of using Godot 3; it should give you more performance and it will still be supported for the foreseeable future.

**Comment by SaadTheGlad** [comment]
Hmm Godot 3 is an option but 4.1 does have all the new features and is much more convenient I've heard. Anywho, I'll keep looking into this problem and see if I can find a fix. Follow up question, will the compatibility renderer gain as much functionality as Forward+? Wouldn't it be best if there was a Vulkan and OpenGL renderer with the same functionality in the same engine or is that not feasible right now?

**Comment by rsubtil** [comment]
> Hmm Godot 3 is an option but 4.1 does have all the new features and is much more convenient I've heard. Anywho, I'll keep looking into this problem and see if I can find a fix. Follow up question, will the compatibility renderer gain as much functionality as Forward+? Wouldn't it be best if there was a Vulkan and OpenGL renderer with the same functionality in the same engine or is that not feasible right now?

I believe they are fundamentally different renderers, going beyond just changing API from OpenGL to Vulkan. So it's very likely some newer features won't be possible on the Compatibility renderer. The team has wrote a few blog posts ([here](https://godotengine.org/article/about-godot4-vulkan-gles3-and-gles2/) and a whole series detailling it's progress [here](https://godotengine.org/article/vulkan-progress-report-1/)) if you want to find more details about this.

**Comment by Calinou** [comment]
Using MSAA on such bandwidth-constrained GPUs is a bad idea. You also don't want to be running 3D games at 1920×1080 on those GPUs (1600×900 or preferably 1366×768 are more viable targets).
