### ISSUE TITLE
Laptop touchpad repeatedly triggers input events, prevents setting keys in the input map tab

### ISSUE THREAD

**Issue by Syngeo** [godotengine/godot#82239]
### Godot version

4.1.1.stable, master branch (4.2.dev, c12d6355)

### System information

Godot v4.1.1.stable + Godot 4.2.dev, Kubuntu 23.04 with Plasma session (Wayland and X11, same result)

### Issue description

When trying to add an input in the "Input map" section, the touchpad was constantly being picked up as a joypad input mirroring where my fingers are on the touchpad (top of the touchpad is up, bottom is down, and so on) and replacing whatever I put in the key (same thing happens for the "Filter by event" field). I can't use Tab to switch focus to the "OK" button either either as that will input "Tab" in the event field.

I tested this with master (commit c12d6355) and 4.1.1, both had the same result. 3.5 didn't have this issue, and it's the same result in both Wayland and X11.

![InputMapBug](https://github.com/godotengine/godot/assets/18536210/c01f59bc-9885-4dd9-a389-66351ee21305)

### Steps to reproduce

- Create a new Godot project
- Go to Project > Project Settings > Input Map
- Click the "Filter by event" field and move the touchpad

In case it helps, I also included a very basic scene I was using in the repro project to measure the axis values for ui_left/right/up/down actions while moving the cursor

### Minimal reproduction project

[MouseTest.zip](https://github.com/godotengine/godot/files/12708399/MouseTest.zip)

**Comment by Zireael07** [comment]
Duplicate/related to already reported issues where touchpads are picked up by SDL as joysticks.

**Comment by Syngeo** [comment]
Ok thanks, I tried looking but couldn't find one. I'll close this one off

**Comment by Zireael07** [comment]
Dupe of #59250
