### ISSUE TITLE
Cannot create and send mouse clicks to viewport

### ISSUE THREAD

**Issue by fluffrabbit** [godotengine/godot#8224]
The docs [advise](http://docs.godotengine.org/en/stable/tutorials/engine/inputevent.html) a little bit of code that looks like:

>var ev = InputEvent()
>ev.type = InputEvent.MOUSE_BUTTON
>ev.button_index = BUTTON_LEFT

Well, just try it! Use cases might include something like [this](https://github.com/fluffrabbit/TestVRGUI). Imagine playing Marathon (you know, the game where you have to read a bunch of shit) with all the glory of Godot's BBcode support, clicking links and such, in virtual reality! Problem is, I'm not sure if those links can be clicked because in VR one does not use a mouse. One does not simply *mouse* into VR.

I modified the GUI in 3D example to continuously send mouse clicks inside the _on_area_input event, rather than just *whatever* you *actually* do with the mouse. On the Web, which those fruitcakes at Mozilla seem to be pushing for, you can send a click event and you can do this or that to your heart's content because it's for babies, but Godot's GUI system is really stripped down. Holy shit, why even use it? I kid, I kid. It's April Fools' Day so I think I'm entitled to a little verbal kickboxing. So when you comment out line 33, suddenly no trabaja.

Anyways, I hope I'm getting the point across. Need to generate MOUSE_BUTTON event from scratch in order to replace mouse with (for instance) key, cannot do so, angry. Above mentioned modified GUI in 3D example attached below.

[broken_gui_in_3d.zip](https://github.com/fluffrabbit/TestVRGUI/blob/master/broken_gui_in_3d.zip?raw=true)

EDIT: Sorry, these fonts are TINY. If you have trouble reading it you can send me an email @ AOL and I'll send it to you in big fonts.

**Comment by Hinsbart** [comment]
So apparently `Viewport` [skips](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1722) events that have an ID of [zero](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L181), which unfortunately is the default value for newly constructed `InputEvent`s :/
A quick workaround would be to set `ev.ID = 1` in your code. (Might also want to do `ev.pressed = true` to actually see an effect)

**Comment by fluffrabbit** [comment]
Unfortunately, setting ID to 1 does not work, nor does setting it to 2. I look forward to any feedback that comes on April 2nd.

**Comment by fluffrabbit** [comment]
and yeah yes ID =1 and pressed = true

works for me but may need to be documented

**Comment by fluffrabbit** [comment]
so things work and sense we're on the subject

there seems to be a special case for text fields
clicking and dragging scroll controls not affected
clearly Godot has not been idiot-proofed

 >var ev = InputEvent()
 >var ev = event # try commenting this out and see how it affects 
selecting text
 >ev.type = event.type
 >ev.ID = 1
 >ev.pos = pos
 >if event.type == InputEvent.MOUSE_BUTTON:
 >>ev.button_index = BUTTON_LEFT
 >>ev.pressed = event.pressed
 >viewport.input( ev )

**Comment by fluffrabbit** [comment]
I mean you can't select text

**Comment by fluffrabbit** [comment]
I'm hoping that somebody has a mobile device and bluetooth controller to 
experience how text fields do not get defocused when clicking in then 
out of them in TestVRGUI. It seems that there are missing pieces here in 
the generation of mouse click events. Aside from an inability to 
click-and-drag-highlight text, there are basically no bugs when it's an 
actual mouse event getting sent (and modified), but when generating a 
new mouse event it's a nightmare.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
