### ISSUE TITLE
Vulkan device lost

### ISSUE THREAD

**Issue by ksubox** [godotengine/godot#82247]
### Godot version

v4.2.dev5.official.e3e2528ba

### System information

Godot v4.2.dev5 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated Radeon RX 560X (Advanced Micro Devices, Inc.; 31.0.21902.5) - AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Try to create empty project, add 3D scene and try to save = crash!

```
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560X

ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2028)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2429)
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2286)
```

### Steps to reproduce

Create new project, than create first 3D scene and try to save...

### Minimal reproduction project

Can't even save first scene... - no project

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot/issues/52112
* https://github.com/godotengine/godot/issues/82206

**Comment by stilestr** [comment]
Unable to reproduce this on an RX 7900XTX. Have been using this build to work on a 3D game for a few days and hasn't crashed at all

**Comment by ksubox** [comment]
I use latest available drivers: 23.9.2

**Comment by Calinou** [comment]
Please [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/80566 locally.

**Comment by ksubox** [comment]
I tested with VS 2022 on Windows and unfortunately issue is not resolved.

**Comment by ksubox** [comment]
I made some experiments and got this:
```
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560X

ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2051)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers\vulkan\vulkan_context.cpp:2452)
ERROR: Condition "err" is true.
   at: VulkanContext::flush (drivers\vulkan\vulkan_context.cpp:2309)
```
And I found out it happens often when some popup/overlay window appear over main screen (like save progress for example).
While I just move objects/rotate scene/click here and there on main window looks like OK. But when I start to add nodes/materials or save scene - this error happens on my comp.

And I checked with debug output - for every popup show Godot call fpCreateSwapchainKHR 5 times!!!
So, for example, when I slowly move mouse over object tree for every object popup is appearing and every time I see 5 calls of fpCreateSwapchainKHR.
And finally die...

Here is full example session (I put WARNING about fpCreateSwapchainKHR on 2049 line of vulkan_context.cpp to see):

```
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560X
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)

WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
WARNING: fpCreateSwapchainKHR
     at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2049)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_update_swap_chain (drivers\vulkan\vulkan_context.cpp:2051)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::_window_create (drivers\vulkan\vulkan_context.cpp:1770)
ERROR: Failed to create Vulkan Window.
   at: (platform\windows\display_server_windows.cpp:4267)
ERROR: Failed to create sub window.
   at: (platform\windows\display_server_windows.cpp:972)
ERROR: Condition "window_id == DisplayServer::INVALID_WINDOW_ID" is true.
   at: Window::_make_window (scene\main\window.cpp:585)
ERROR:            vkCreateBuffer: Invalid device [VUID-vkCreateBuffer-device-parameter]

```
[crash.zip](https://github.com/godotengine/godot/files/12721838/crash.zip)

**Comment by Calinou** [comment]
> And I checked with debug output - for every popup show Godot call fpCreateSwapchainKHR 5 times!!!
So, for example, when I slowly move mouse over object tree for every object popup is appearing and every time I see 5 calls of fpCreateSwapchainKHR.
And finally die...

Every window needs its own swapchains.

If you enable **Single Window Mode** in the Editor Settings, you won't see new swapchains being created while using the editor as everything will be a single window.

**Comment by ksubox** [comment]
And setting **Single Window Mode** - remove multiple fpCreateSwapchainKHR. And for my comp it's 100 times more stable.
But it doesn't solve original problem - why extensive fpCreateSwapchainKHR produce ERR_CANT_CREATE?
May be Godot has parallel rendering thread or something like that?

**Comment by hpvb** [comment]
I found that Linux when you're using a non-default Vulcan device the "device lost" message appears because of some wrong assumptions in amdgpu for cards with no displays plugged in.

I was able to work around this issue by adding `amdgpu.lockup_timeout=60000,60000,60000,60000` to my kernel command line.

It seems that what happens is that the default timeouts for non-connected GPUs is 10000 for all rings, while on the primary one it is 60000 for compute.

Not sure if it'll help you in this case!

**Comment by dev-tripathi-satosi** [comment]
> I found that Linux when you're using a non-default Vulcan device the "device lost" message appears because of some wrong assumptions in amdgpu for cards with no displays plugged in.
> 
> I was able to work around this issue by adding `amdgpu.lockup_timeout=60000,60000,60000,60000` to my kernel command line.
> 
> It seems that what happens is that the default timeouts for non-connected GPUs is 10000 for all rings, while on the primary one it is 60000 for compute.
> 
> Not sure if it'll help you in this case!

 
Hey, I also have a same issue, but the only error I have was about "Vulkan Device lost" . I'm using Intel i5 laptop on windows 11. Any way to fix it? 

Moreover, the software crashes unknowingly

**Comment by Calinou** [comment]
> Hey, I also have a same issue, but the only error I have was about "Vulkan Device lost" . I'm using Intel i5 laptop on windows 11. Any way to fix it?
>
> Moreover, the software crashes unknowingly

See this comment: https://github.com/godotengine/godot/issues/82247#issuecomment-1732677729

**Comment by ksubox** [comment]
Beta 4 - still crashing!

**Comment by ksubox** [comment]
Beta5 still bad - whenever I resize editor window it crashes.

```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2536)
```

**Comment by ksubox** [comment]
Some new information if somebody is interested:
The real error is VK_ERROR_OUT_OF_HOST_MEMORY (-1)!
```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2135)
```

**Comment by Opalie** [comment]
Putting the Editor in Single Window Mode fixes the issue for me but I did get this error once while working, and then forced me to close the engine. No log because of that (or none that I can find), sorry about that.

![image](https://github.com/godotengine/godot/assets/31365045/f1676df1-d835-4810-b972-defd2f6614dc)

Godot Engine v4.1.3.stable.mono.official.f06b6836a - Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560X

If this is in any shape or form interesting for you, here are the logs I got when I was using PR #80566 with no Single Window Mode, i didn't try since with it but I can if needed :

![Clipboard - November 15, 2023 6 18 PM](https://github.com/godotengine/godot/assets/31365045/a03165ee-85c7-4411-b1ed-e6e403bea013)

And this was 4.1.3 before Single Window Mode:

![Clipboard - November 15, 2023 6 17 PM](https://github.com/godotengine/godot/assets/31365045/76ba49f4-fdcf-4d95-92f5-2882f55a2d5e)

Note that a lot of the time the vulkan errors would happen randomly, sometimes right after it opened the project window, sometimes after it loads the main scene in the engine, sometimes when I try to build my project...
(I am still a beginner, if any information lacks details please do ask.)

**Comment by emirljuca** [comment]
> Putting the Editor in Single Window Mode fixes the issue for me but I did get this error once while working, and then forced me to close the engine. No log because of that (or none that I can find), sorry about that.
> 
> ![image](https://private-user-images.githubusercontent.com/31365045/283404768-f1676df1-d835-4810-b972-defd2f6614dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjcwODEsIm5iZiI6MTcwMTM2Njc4MSwicGF0aCI6Ii8zMTM2NTA0NS8yODM0MDQ3NjgtZjE2NzZkZjEtZDgzNS00ODEwLWI5NzItZGVmZDJmNjYxNGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE3NTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMGNmNGQyODM4YzU1Y2MwNjJhM2Y2ZGI2MjM3MmMyMjY4MDkyODEwNTdhMjU1Yzg2YTMzOTZjYzdhZWE2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eUEd89fcGvzgDf_xjRc8jyocHFeKptb9wxIaKuTdzN0)
> 
> Godot Engine v4.1.3.stable.mono.official.f06b6836a - Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon RX 560X
> 
> If this is in any shape or form interesting for you, here are the logs I got when I was using PR #80566 with no Single Window Mode, i didn't try since with it but I can if needed :
> 
> ![Clipboard - November 15, 2023 6 18 PM](https://private-user-images.githubusercontent.com/31365045/283407851-a03165ee-85c7-4411-b1ed-e6e403bea013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjcwODEsIm5iZiI6MTcwMTM2Njc4MSwicGF0aCI6Ii8zMTM2NTA0NS8yODM0MDc4NTEtYTAzMTY1ZWUtODVjNy00NDExLWIxZWQtZTZlNDAzYmVhMDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE3NTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYTg0NWEyOTc5OTYzZTIwNmNlOThkMjAzNjI1YTUxMWVlYzE1ZTlmODE0MTE0YzFmOTA0NjBmN2EyZmRhNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JEC2aounHtC6Ze8ISolhW9eD0XbnRmQYeyzBkjfNwxU)
> 
> And this was 4.1.3 before Single Window Mode:
> 
> ![Clipboard - November 15, 2023 6 17 PM](https://private-user-images.githubusercontent.com/31365045/283408346-76ba49f4-fdcf-4d95-92f5-2882f55a2d5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjcwODEsIm5iZiI6MTcwMTM2Njc4MSwicGF0aCI6Ii8zMTM2NTA0NS8yODM0MDgzNDYtNzZiYTQ5ZjQtZmRjZi00ZDk1LTkyZjUtMjg4MmY1NWEyZDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE3NTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZGRkMjM1MTcyMTNiZGMyZjIwZWQ4Zjc4OGU1ZjhhOTE3NWQwYjZkODdhNTJmOWYxNjZmMGNlNmQ4ODNkZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kG8Pe9da5hdqVyV1rw2EFVik6IELTPA6qDPUSuw3GXk)
> 
> Note that a lot of the time the vulkan errors would happen randomly, sometimes right after it opened the project window, sometimes after it loads the main scene in the engine, sometimes when I try to build my project... (I am still a beginner, if any information lacks details please do ask.)
> 
> EDIT: On Godot 4.1.3 (+ Single Window Mode) I can reproduce this exact same error every single time if I Restore Down the godot window, and try to change its size.
> 
> ![image](https://private-user-images.githubusercontent.com/31365045/283852359-d888770e-56fa-4697-964e-61d810999c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjcwODEsIm5iZiI6MTcwMTM2Njc4MSwicGF0aCI6Ii8zMTM2NTA0NS8yODM4NTIzNTktZDg4ODc3MGUtNTZmYS00Njk3LTk2NGUtNjFkODEwOTk5YzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE3NTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Y2MwMDU2NWNmZGM0MjkwMGZmYzhlODlmY2Y5NGIzNzdjMTA3NjI1MzdiOWQ5MTk5ZjJmMzVhNjUxMjdmODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8eiREtBBDgoIVsiW90gBNGXSPU505Ej2-grGHqQTTR0)

Getting the same issues here. Was able to reproduce with just creating a GPU particle node with 500 particles when launching the scene. Seems to work in editor funnily enough. I have a Lenovo Yoga C940-14IIL

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.
