### ISSUE TITLE
FontFile's cached images are always duplicates of set images, and are bundled with resource when saved to disk.

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#82254]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

I am trying to make my own custom **FontFile**, by porting over an existing addon in 3.x called [Texture Fonts](https://github.com/ElectronicBlueberry/Texture-Fonts). After several days, it mostly works, surprisingly.

But there's one glaring, annoying flaw. When assigning an Image resource to the fon with `set_texture_image()`, a NEW **Image** is created, every time.
The reason as to why can be a problem is because when saving the custom **FontFile** as .tres, raw copies of the images _I already have saved on disk_ are bundled as sub-resources. Not just that, they're all saved as a **PackedByteArray** in pure, plain text. The bloat is ridiculous, and even if they were pure binary it'd be an unnecessary waste.

<img width="50%" src=https://github.com/godotengine/godot/assets/66727710/d7f2e53f-1d1c-4277-8ec2-68e31f370783/>

There is no easy way to replace this newly created **Image** with the original one. Even if you do, it will be overridden when the resource is saved again. I have tried numerous ways and gotten close at one point. If the Resource knew it was being saved, that may be doable.
This renders any way of doing what the original addon did impossible, without huge bloat.

<details>
<summary><h4>Click here for helevant piece of code(!?)</h4></summary>
https://github.com/godotengine/godot/blob/58f0cae4af47adcac121cc220749ddbf778f4a81/modules/text_server_adv/text_server_adv.cpp#L2606-L2626
</details>

It's possible that someone knowledgeable in this part of the font code may give more insight as to why this is the case.

### Steps to reproduce

The steps to reproduce this are a bit complex and I recommend taking a look at the MRP.
- Create a script extending **FontFile** with, say, the following piece of code:
    ```GDScript
    @tool
    extends FontFile
    class_name MyFont


    const FONT_SIZE = Vector2i(16, 16)

    func _init():
    	clear_cache()
	
    	var image := Image.load_from_file("res://icon.svg")
    	set_texture_image(0, FONT_SIZE, 0, image)
    ```
- Create a new **FontFile** resource on disk, and attach this script.
- Create a test scene with a **Label**, and assign this font Resource to the label.
- Open the **FontFile** resource with an external program and look inside. You may notice the `icon.svg` image has been saved, bundled with the resource, even though on the surface it's entirely unnecessary.

### Minimal reproduction project

[FontFile Image cache bloat.zip](https://github.com/godotengine/godot/files/12709138/FontFile.Image.cache.bloat.zip)

**Comment by bruvzg** [comment]
Not sure what's the best solution here, if it will be keeping images it will waste memory for every loaded font which is much worse than a disk space. For all built-in supported types of fonts FontFile is imported resource, so it's not an issue and original files should not be saved, or images are generated during the import process.

I guess making a custom importer (similar to https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_imagefont.cpp) instead of subclassing FontFile might be one way to solve it without changes to the engine.

**Comment by Mickeon** [comment]
> I guess making a custom importer (similar to https://github.com/godotengine/godot/blob/master/editor/import/resource_importer_imagefont.cpp) instead of subclassing FontFile might be one way to solve it without changes to the engine.

That's exactly what I didn't want to do. There's already an [Allegro Bitmap Font Importer](https://gitlab.com/snoopdouglas/abfi) that does this, and it certainly... works.
The importer approach loses a lot, however. Tweaking the settings is not very user friendly, it cannot easily support more than one image at once, and most importantly, does not change in real time.

If this were capable to be done in practice, just before a save, I'd not have to find massive loopity-loops to get this working.
![image](https://github.com/godotengine/godot/assets/66727710/6800fe6f-c662-42c0-91ba-43dfa7839e73)

This is quite the shame. The addon for this... TextureFont (ImageFont now, I suppose) for Godot 4 is so close to being actually doable, but because of this issue it's almost not worth it.

**Comment by Mickeon** [comment]
If it is of interest, my current workaround (which is not even fully working) revolves around static variables and a bunch of particularly unpleasant code.

The plugin emits a signal when `_apply_changes()` is called by the engine.
When the plugin loads, assign itself as static reference to TextureFont's class.
When a TextureFont resource is initialised, connect the signal. When emitted, the TextureFont will:
- Swiftly replace all cached images with dummy images that occupy much less space;
- Save itself on disk;
- Replace all cached images with the images they're meant to be.

This is just to allow me to even see the font in the editor, instead of black squares.
And it's all incredibly, incredibly unreliable.

At runtime, less of a burden. When the property storing these images is set, replace all cached images with the images they're meant to be.

**Comment by bruvzg** [comment]
> For all built-in supported types of fonts FontFile is imported resource, so it's not an issue and original files should not be saved, or images are generated during the import process.

Actually, it is an issue for the `AngelCode` BMFont importer as well. I'll try a few things to fix it.

>  if it will be keeping images it will waste memory for every loaded font which is much worse than a disk space.

Might be not as bad, it's probably won't be copied since it's COW, so image just need to be cleaned if font is changing textures.

**Comment by bruvzg** [comment]
I think something like this actually will never work as an external resource, it doesn't matter if it's returning the same image or have `PROPERTY_USAGE_RESOURCE_NOT_PERSISTENT` flag:

```
	var image := Image.load_from_file("res://icon.svg")
	set_texture_image(0, FONT_SIZE, 0, image)
```

It might work only if image is imported as `Image` and using `load`/`preload`, but this will break BMFont importer (unless all associated images are imported as Image first).
```
	var image := load("res://icon.svg")
	set_texture_image(0, FONT_SIZE, 0, image)
```

**Comment by Mickeon** [comment]
> I think something like this actually will never work as an external resource, it doesn't matter if it's returning the same image or have `PROPERTY_USAGE_RESOURCE_NOT_PERSISTENT` flag:
> 
> ```
> 	var image := Image.load_from_file("res://icon.svg")
> 	set_texture_image(0, FONT_SIZE, 0, image)
> ```

This is expected behavior. Those may not be resources compiled after exporting the project, so they may not even exist. They need to be bundled with the FontFIle Resource.


> It might work only if image is imported as `Image` and using `load`/`preload`. 

This is the exact behavior necessary for at least the addon I'm porting to work. The image already exists in the project, so making a whole duplicate sub-resource for it seem to be completely unnecessary.
Importing them as **Image** first looks like a necessary evil that was not the case in Godot 3.x, but it is what it is, and can be worked around with an **ImageTexture** if necessary.
