### ISSUE TITLE
Godot Crashes Immediately Upon Opening Project

### ISSUE THREAD

**Issue by stilestr** [godotengine/godot#82255]
### Godot version

4.2-dev5

### System information

Windows 11 - Ryzen 7 5800x - RX7900XTX

### Issue description

I have a project that I created and have been working on in 4.0, then 4.1. No issues between the two versions. The project still works fine in both versions. However, in 4.2-dev5, the project will not even open, and crashes with the following error.

![image](https://github.com/godotengine/godot/assets/4535064/be8a7e9c-cc29-4221-b117-d7e3acba54b2)

![Screenshot 2023-09-24 130432](https://github.com/godotengine/godot/assets/4535064/1885744b-3c79-47bf-8d7a-e4763cc1edcb)
![Screenshot 2023-09-24 130408](https://github.com/godotengine/godot/assets/4535064/a8d15c0e-5d9d-4fe2-bd61-7ad211c6c829)

### Steps to reproduce

Not sure how I could upload reproduction steps without sharing my entire game, so I've linked the full project below.

### Minimal reproduction project

[See this. ](https://drive.google.com/file/d/1Uzjte8vv5ZZAx7UVB9m1zmGWzB5OmbeI/view?usp=drive_link)

**Comment by stilestr** [comment]
Additionally, I tried converting other projects to 4.2 and launching them in the latest dev snapshot and they've all worked fine so far, this is the only one that doesn't work

**Comment by rsubtil** [comment]
The link for your MRP requires access.

**Comment by stilestr** [comment]
Thanks, fixed it.

https://drive.google.com/file/d/1Uzjte8vv5ZZAx7UVB9m1zmGWzB5OmbeI/view?usp=sharing

**Comment by rsubtil** [comment]
Bisected to b1eb737719b88702ec3ca3eed211582e9188e38e (cc @dalexeev)

**Comment by stilestr** [comment]
Just adding to confirm that https://github.com/godotengine/godot/pull/82294 does fix this issue for me
