### ISSUE TITLE
"Lookup Symbol" or "Ctrl+LMB" not working for functions defined in script of another node

### ISSUE THREAD

**Issue by nagidev** [godotengine/godot#82258]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.2.beta1.official [b1371806a]

### System information

Windows 10 - Godot v4.1.1.stable.official

### Issue description

![Lookup symbol option not available](https://github.com/godotengine/godot/assets/38583283/f5c1e4ad-236a-4954-9fed-70b9a29221e0)

Including a reference to a child node, and accessing a function on the child node works in game.
However, trying to use the "Lookup symbol" option or CTRL+LMB on the function from the script editor does not work at all.

This works fine in Godot 3.5.

Additionally, the functions defined in the child node are not suggested in auto-complete in the parent node's script.

### Steps to reproduce

1. Create a scene with a parent node and a child node (type does not matter).
    ParentNode
        ChildNode
2. Attach scripts to both nodes.
3. Define a function (say, foo) in the child node's script.
4. Reference the child node in the parent node's script (say, `@onready var child = $ChildNode`) Note: the issue only happens when onready is used.
5. Call the function foo from the child anywhere in the parent node's script.
6. Firstly, the function "foo" is not suggested in the auto-complete. Second, "lookup symbol" or "CTRL+LMB" don't open the function definition.

### Minimal reproduction project

[lookupBug.zip](https://github.com/godotengine/godot/files/12709418/lookupBug.zip)

**Comment by eterlan** [comment]
As far as I know, if you don't declare class_name, you can't get any intellisense for your custom function.
The workaround is to declared class_name, and field with type.
I make some test and find some quite interesting behaviour.
case 1: child node has declared class_name, it has intellisense from parent if I declare the field as `var child : Child`
case 2: child node has declared class_name, it has no intellisense from parent if I declared the field as `@onready var child: Child = $child`

**Comment by nagidev** [comment]
Getting the same results. This code seems to be working as expected and Lookup symbol is working.
`extends Node

var child_node : ChildNode

func _ready():
	child_node = $ChildNode

func parent_function():
	child_node.child_function()`

**Comment by API-Beast** [comment]
It seems like 4.1 has trouble deducing the type of $ expressions, while in 3.x it did that just fine.

**Comment by nagidev** [comment]
Turning the script into a tool script doesn't change the issue. In fact, I originally noticed the issue while working on tool scripts.

**Comment by willnationsdev** [comment]
I would guess that it's because `$Name` can return anything extending Node and it can ascertain definitively whether or not the returned node will be a valid reference for the hinted type. Is it also the same (with `@onready`) if you do `$ChildNode as ChildNode` or perhaps `= ($ChildNode as ChildNode)` (should both be equivalent, but just in case the parser is making a distinction)?

**Comment by dalexeev** [comment]
Generally speaking, autocompletion with dynamic typing is not always possible. But in this case, we could infer a weak type using the editor's information about the current scene, just as we autocomplete node paths. (The same script can be attached to multiple scenes, so autocompletion is not possible without an open scene.)

**Comment by nagidev** [comment]
Godot 3 managed to pull this off quite reliably. Is there a way to bring back that feature?

**Comment by API-Beast** [comment]
![image](https://github.com/godotengine/godot/assets/1295635/ec30d8c6-0886-48a9-8e87-f4f7b5795849)
This is a general issue regarding $ syntax that also affects auto-complete. Here for example in 3.x it would show me the "aim_at" function, but in 4.x it will only show me generic Node functions.

**Comment by KoltPenny** [comment]
I'm also having this issue! We'll see how it goes.

**Comment by HolonProduction** [comment]
It is definitely possible in this context to interfere the script. I added code for this in #79386 however the sorting seems to be broken currently.
