### ISSUE TITLE
[3.0] Memory leak in Mesh.add_surface_from_arrays()

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8225]
Tested on Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits

The following script shows a memory leak:

```gdscript
extends Node


func _process(delta):
	var mesh = Mesh.new()
	var arrays = [
		[Vector3(0,0,0)],
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null
	]
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_POINTS, arrays)

	get_node("Label").set_text(str(OS.get_dynamic_memory_usage()))
```

The memory doesn't increase if I remove `add_surface_from_arrays`.

I found it because it has a massive impact on my voxel game, where meshes are generated at runtime, 1 Mb is leaked at each chunk update.

**Comment by bd339** [comment]
I ran Valgrind's memcheck on your example. Here's a paste of some of its output [https://pastebin.com/WQtTGhTk](https://pastebin.com/WQtTGhTk)
Perhaps it's helpful to someone knowledgeable about that code.

**Comment by Zylann** [comment]
Ported terrain sculpting to Godot 3.0, and now this leak makes Godot run out of memory in less than 30 seconds. @reduz any idea?

**Comment by Zylann** [comment]
I narrowed it down further, and I found this line causes a leak on its own in `ArrayMesh::add_surface_from_arrays()`:

```cpp
		PoolVector<Vector3> vertices = p_arrays[ARRAY_VERTEX];
```

**Comment by Zylann** [comment]
After some midnight debugging I found that PoolVector ends up doing copy-on-write in its own destructor, due to an atttempt to call destructors of all items using a Write access:

![image](https://user-images.githubusercontent.com/1311555/27160820-3fea56b4-5177-11e7-9023-c783d51a4bf4.png)

The test done is the following, put directly into Node's PROCESS notification, and debugging the whole process of resizing, then destruction at scope exit:

```cpp
{
	PoolVector<Vector3> pv;
	pv.push_back(Vector3());
}
```

**Comment by HumanSheeple** [comment]
Solution: Change line 150 to         if (old_alloc->refcount.unref() == false) {
yup that was it a true to a false.
Well done HumanSheeple you have done it again :)

**Comment by Zylann** [comment]
Not sure what the real fix is, needs @reduz confirmation. Also keep in mind this happens because of copy on write, so not only the alloc was leaked, but PoolVector is calling destructors of copied objects instead of the originals.
