### ISSUE TITLE
GDScript: "Cannot find property emit on base Signal"

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#82251]
### Godot version

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

```gdscript
extends Node

signal lmofa
signal yeet

func _ready():
    lmofa.connect(yeet.emit)
```

This results in a "Cannot find property emit on base Signal" error. This is either a bug or a weird error text.

### Steps to reproduce

Copy the script above.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Probably because the method is vararg, unsure if you can get a callble to that

**Comment by dalexeev** [comment]
This is not a bug, but a limitation. A `Callable` can only represent `Object` methods and `CustomCallable`s (for example lambdas in GDScript). `Callable` cannot represent methods of built-in `Variant` types.

* See also #58912.

**Comment by MewPurPur** [comment]
Cool, so better bug text, and/or the limitation is going to get lifted eventually?

**Comment by AThousandShips** [comment]
Unsure what the error detection could do with the partsed/analyser

**Comment by dalexeev** [comment]
I'll try to implement a `CutomCallable` for built-in `Variant` types.
