### ISSUE TITLE
BIND_VIRTUAL_METHOD in GDextensions doesn't create a virtual function in GDscript

### ISSUE THREAD

**Issue by TrickyFatCat** [godotengine/godot#82267]
### Godot version

4.1.1

### System information

Pop!_OS 22.04

### Issue description

Using `BIND_VIRTUAL_METHOD` script in `_bind_methods()` doesn't create a virtual function in GDScript.

### Steps to reproduce

1. Create simple GDextension
2. Build it
3. Add to the project

```C++
//MyClass.h
#ifndef MYCLASS_H
#define MYCLASS_H

#include <godot_cpp/classes/node.hpp>

namespace godot{
class MyClass : public Node{
	GDCLASS(MyClass, Node)

protected:
	static void _bind_methods();

	void foo();

};
}

#endif

//MyClass.cpp
#include "my_class.h"

#include <godot_cpp/core/class_db.hpp>
#include <godot_cpp/variant/variant.hpp>

using namespace godot;


void MyClass::_bind_methods(){
	BIND_VIRTUAL_METHOD(MyClass, foo);
}


void MyClass::foo(){

}
```
After building the extension, you can `MyClass` in the editor. However, you can't override `foo()` function as GDscript doesn't see it and it isn't shown in documentation section.

### Minimal reproduction project

N/A

**Comment by SilicDev** [comment]
Related issues:
[godot/godot-cpp#910](https://github.com/godotengine/godot-cpp/issues/910)
[godot/godot-cpp#1072](https://github.com/godotengine/godot-cpp/issues/1072)
[godot/godot-cpp#1199](https://github.com/godotengine/godot-cpp/issues/1199)

[godot/godot-cpp#910](https://github.com/godotengine/godot-cpp/issues/910) mentions a possible work around by using `call("_virtual_func")` instead but even that isn't ideal when dealing with multiple related classes (and might not even work when overriding it in C++.)

This is especially annoying as documentation is also broken for GDExtension if I'm not mistaken and makes defining extendable classes quite difficult.

Reimplementing the `GDVIRTUAL` macros is impossible as `Object::get_script_instance` and the `ScriptInstance` class aren't exposed.

**Comment by RudyFisher7** [comment]
Am I running into this with 4.4.1-stable? Perhaps I'm doing something wrong. Here are my files and the build error:

![Image](https://github.com/user-attachments/assets/c409318c-1feb-426c-b8f7-1855d399a6b9)

**Comment by RudyFisher7** [comment]
> Howdy,
> 
> Am I running into this with 4.4.1-stable? Perhaps I'm doing something wrong. Here are my files and the build error. Both component and gdextensioncomponent are in a gdextension.
> 
> ![Image](https://github.com/user-attachments/assets/c409318c-1feb-426c-b8f7-1855d399a6b9)

Update: Indeed, it looks like the macros are working for GDScript overrides but not native (c++) overrides within the gdextention. This certainly can be worked around, but just FYI if consistency with Godot is desirable. ✌
