### ISSUE TITLE
Android game rapidly loses FPS when shaded+alpha opaque 3DSprites/Planes with alpha textures, get closer to the Camera3D

### ISSUE THREAD

**Issue by rmichaluszek** [godotengine/godot#82261]
### Godot version

4.2.dev-5, 4.1.1_Stable

### System information

Android 11 RP1A.200720.011 - [Redmi Note 9](https://www.gsmarena.com/xiaomi_redmi_note_9-10192.php) - Compatible Mobile (GLES3)

### Issue description

Game loses FPS on really simple scenes, but only when Alpha/Shaded Textures (either 3DSprite or Plane with same alpha Texture) get closer to the 3D Camera.

Scene contains: 3D Camera, OmniLight with disabled shadows (They're not supported anyways yet on compability) and several 3DSprites with shaded and transparent flags enabled, or Plane meshes with the same texture and trensparency enabled.

Problem is I can have a big amout of these 3DSprites and keep normally 60FPS which is rather normal with such small resolution textures and one light source:

![Screenshot_2023-09-24-21-46-57-721_com cyfrogen hellspedition](https://github.com/godotengine/godot/assets/20546844/726f1b5a-9133-45ae-bae4-29cbfeef978b)

But when they get closer to the Camera3D, i start to rapidly lose fps, even when i leave only 4 3DSprites:

![Screenshot_2023-09-24-21-45-43-601_com cyfrogen hellspedition](https://github.com/godotengine/godot/assets/20546844/5a26468d-8381-43f8-920f-78c2d94b28a2)

And even bit closer results in another 5FPS drop:

![Screenshot_2023-09-24-21-46-07-111_com cyfrogen hellspedition](https://github.com/godotengine/godot/assets/20546844/f048accf-1856-4e54-97da-f2fc8db96396)

Disabling either shaded flag on 3DSprites, or setting transparency to disabled, results in stable 60FPS
When enabling the transparency, I've tried every option (Alpha, Alpha-scissor, Opaque-Pre pass on Plane, and Discard/Opaque pre-pass on 3DSprite) with the same result beeing low fps when closer to the Camera3D

### Steps to reproduce

Minimal reproduction project is made on Godot 4.2.dev-5 version have everything except SDK libraries,

1. Configure exporting for android on your machine
2. Just run. If you have better phone than me, you can increase the number of the 3DSprites a bit.
3. App starts losing FPS when 3DSprites are getting closer to the camera.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/12709608/project.zip)

**Comment by Calinou** [comment]
This is expected due to shading cost requirements increasing as sprites get closer to the camera. This is why using unshaded rendering gives you a stable 60 FPS.

If you want a stable 60 FPS without having to make materials unshaded, decrease the 3D rendering resolution by using the `viewport` stretch mode and a lower viewport resolution.

**Comment by shiouhuamien** [comment]
> 這是令人期待的，因為隨著精靈越來越接近相機，著色成本要求隨之增加。這就是為什麼使用無陰影渲染可穩定的 60 FPS。
> 
> 如果您想要穩定的 60 FPS，而不需要使材質無遮擋，請在「`viewport`專案設定」中使用尺寸拉伸模式和較小的視窗（例如 720×1280）來降低 3D 渲染解析度。

I think I ran into a similar problem,
If 3D particles send particles to the camera and across the screen,
This can cause severe frame drops.
What settings should be made to avoid this problem?
![未命名-1](https://github.com/godotengine/godot/assets/114559078/f0db8e13-09db-4dfa-ba2e-e036eca96057)

**Comment by Calinou** [comment]
> This can cause severe frame drops.
What settings should be made to avoid this problem?

You have 3 options:

- Reduce the amount of particles.
- Cull particles if they are too close to the camera. You can use the GeometryInstance3D Visibility Range properties for this.
- Reduce rendering resolution in the Project Settings. With the Forward+ or Mobile rendering methods, adjust the **Scaling 3D > Scale** project setting to be between `0.5` and `0.7`.

**Comment by rmichaluszek** [comment]
> This is expected due to shading cost requirements increasing as sprites get closer to the camera. This is why using unshaded rendering gives you a stable 60 FPS.
> 
> If you want a stable 60 FPS without having to make materials unshaded, decrease the 3D rendering resolution by using the `viewport` stretch mode and a lower window size in the Project Settings (such as 720×1280).

The shaded rendering works perfectly fine in 60FPS even when there is 30 3DSprites close to the screen. The issue inly occurs when both transparency and shaded rendering on the sprite are enabled at the same time.
I've read something about overdraw with transparent pixels, and i understand it can get heavy for rendering, but it's laggy for 4 sprites?? I don't believe it's so demanding, I am probably doing something wrong and there is a better way of optimalizing this

I would like to avoid changing rendering resolution if possible, if that will be only resort i would rather swap this whole project to 2d.

**Comment by shiouhuamien** [comment]
> > 這可能會導致嚴重的丟幀。
> > 應該做哪些設定來避免這個問題呢？
> 
> 您有多種選擇：
> 
> * 減少顆粒量。一般來說，避免重疊的透明效果。
>   
>   * 如果您希望視覺效果保持相似，請使用_更多的_粒子，但使用更小的紋理，從而透過完全透明的像素浪費更少的空間（或使粒子本身更小）。
> * 如果粒子離相機太近，請剔除它們。為此，您可以使用 GeometryInstance3D Visibility Range Begin 屬性。
> * 降低專案設定中的渲染解析度。使用 Forward+ 或 Mobile 渲染方法，將**「縮放 3D」>「縮放」**項目設定調整為 和`0.5`之間`0.7`。

OK, after my constant testing and reading the documentation, I finally found the reason.
Just turn off "Global Illumination" in "Geometry Settings" of "Particles" and the problem will be solved

Thanks

**Comment by Zireael07** [comment]
@rmichaluszek Probably a combo of mobile drivers doing badly with transparency/overdraw AND the card's fillrate

**Comment by rmichaluszek** [comment]
@Zireael07 Well i don't doubt that mobile is way worse than PC, but would be good to know what can i disable/change to even render 4 images without having 30fps

I'm not near my computer atm but i believe global illumination in particle settings won't be helpful for my case

**Comment by rmichaluszek** [comment]
Using the 3DSprite rather than Plane with transparent texture, and setting its Alpha Cut to Discard, Alpha Antialiasing to 0 makes the game run good on my android device ( 60fps with 32 3DSprites )

Thanks for help anyway!
