### ISSUE TITLE
Emitting external custom signals in C# causes an error

### ISSUE THREAD

**Issue by SanctusAnimus** [godotengine/godot#82268]
### Godot version

4.1.1 stable mono win64

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3742) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

So i've been following docs on signals, while implementing Signal Bus pattern (a.k.a Event Bus) - trivial pattern when implemented in GDScript, but faced a set of issues

Signals defined using `[Signal]` attribute are local to the class and it's subclasses, and therefore cannot be called externally.

Docs on the website don't mention anything on that, but `EmitSignal` description does, and states that you have to add a "User Signal", and provides example, which i simply pasted, but it does not work either - i'm still getting `Can't emit non-existing signal "CustomHurt".`, emitting both as a string or using StringName from subclass (when defined as a delegate).

Both "kinds" of signals only work when emitted from their parent class.

### Steps to reproduce

Following C# script is attached to a Node, child of a Root on main scene, supposed to be used as a singletone via `Instance`.
`CustomHurt` signal is defined as an EventHandler and as a User Signal in _EnterTree.
Defining same signal as a delegate doesn't work - as names clash, but defining User Signal here means (even if it works correctly) - no type support at all.

```csharp
using csharp_test;
public partial class EventBus : Node
{
    public static EventBus Instance { get; private set; }

    // [Signal]
    // public delegate void CustomHurtEventHandler(int damage, string source);

    public override void _EnterTree()
    {
        if (Instance != null)
        {
            GD.PushWarning("Attempted to re-create another instance of signal bus!");
            return;
        }

        Instance = this;

        AddUserSignal("CustomHurt", new Godot.Collections.Array() { new Godot.Collections.Dictionary() { { "name", "damage" }, { "type", (int)Variant.Type.Int } }, new Godot.Collections.Dictionary() { { "name", "source" }, { "type", (int)Variant.Type.String } } });
        GD.Print("Signal created");
    }
}
```

Then we have Listener, which connects using string name of a custom signal

```csharp
using csharp_test;

public partial class Listener : Node
{
    public override void _Ready()
    {
        GD.Print("Listener ready!");
        Connect("CustomHurt", new Callable(this, nameof(OnHurt)));
    }

    public void OnHurt(int damage, string source) {
        GD.Print($"Hurt received ${damage} from ${source}");
    }
}
```

And this is the place where something strange happens, as console log, when script is executed, says
```
Signal created
Listener ready!
ERROR: In Object of type 'Node': Attempt to connect nonexistent signal 'CustomHurt' to callable 'Node(Listener.cs)::OnHurt'.
```
Even though signal bus was initialized and print emitted afterwards, listenter failed to find same name?

```csharp
namespace csharp_test
{
    public partial class dispatcher : Node
    {
        public override void _Process(double delta)
        {
            EmitSignal("CustomHurt", 11, "source");
        }
    }
}
```
And code for dispatcher, fairly straightforward to test signals being emitted - but every tick throws `ERROR: Can't emit non-existing signal "CustomHurt". at: (core/object/object.cpp:1026)` errors instead.
![image](https://github.com/godotengine/godot/assets/43399078/3bb6da89-be78-49a8-9847-7f37858784a1)

Exact error doesn't fit into editor console, and full traceback is not emitted into engine console - if i can somehow extract it and it's useful, LMK.

I'm not sure if this is related, but VSCode fails to find Signals defined as delegates as well (doesn't affect Rider though)
![image](https://github.com/godotengine/godot/assets/43399078/7eb7cf7b-691c-4982-a68b-98d87b63ecd8)

### Minimal reproduction project

Since this is a C# specific issue (signals work reliably in GDScript), project is for C# too.
[csharp_test.zip](https://github.com/godotengine/godot/files/12709673/csharp_test.zip)

**Comment by zaevi** [comment]
I think you forgot to access the EventBus singleton like:
 `EventBus.Instance.Connect("CustomHurt", new Callable(this, nameof(OnHurt)));`

Also, you should emit it via the singleton:
`EventBus.Instance.EmitSignal("CustomHurt", 11, "source");`

**Comment by ice-ko** [comment]
@zaevi In the event bus singleton mode, each grid in the backpack is bound to a click signal. How to bind the signal in this way?
