### ISSUE TITLE
[3.0] TestCube can't be placed where it should

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8226]
Tested on Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits, nVidia GeForce 940M

I made a scene with 7 TestCubes, but one of them just doesn't want to show where it should.

![image](https://cloud.githubusercontent.com/assets/1311555/24583875/afcba24c-1759-11e7-9bbb-e3d27ed22104.png)

Reproduction steps:

1) Open this scene: [cube_doesnt_show.zip](https://github.com/godotengine/godot/files/888140/cube_doesnt_show.zip).
Notice TestCube2 is at the same place as TestCube1, at (-20, 0, 20)
1) Move TestCube2 at (20, 0, -20)
2) Save and close the scene
3) Reopen it: notice the cube teleported back to where it was before

The console output mentions a script error as soon as I translate the cube, although there is no script in the scene. There was one in the screenshot before I find this odd behaviour, but I removed it since:

```
ERROR: Script inherits from native type 'Reference', so it can't be instanced in object of type: 'PropertyValueEvaluator'
   At: modules\gdscript\gd_script.cpp:394
ERROR: Script inherits from native type 'Reference', so it can't be instanced in object of type: 'PropertyValueEvaluator'
   At: modules\gdscript\gd_script.cpp:394
ERROR: Script inherits from native type 'Reference', so it can't be instanced in object of type: 'PropertyValueEvaluator'
   At: modules\gdscript\gd_script.cpp:394
```

**Comment by karroffel** [comment]
Maybe this is related to the `print(Vector3(-1, 0, -1)` => Vector3(1, 0, 1) bug in #8188 ?

Probably not, but it could be possible that the Vector3 is just borked

**Comment by bojidar-bg** [comment]
This is somehow related to saving the scene, since manually editing the file and rerunning _without_ saving works just fine.

**Comment by Zylann** [comment]
The scene was old given the presence of TestCubes, so I remade it from scratch, the could not reproduce.

**Comment by kubecz3k** [comment]
Thank you @Zylann for testing this
