### ISSUE TITLE
Input.get_axis(...) behaves erratically when using keyboard input after using controller via Steam Input

### ISSUE THREAD

**Issue by leetNightshade** [godotengine/godot#82269]
### Godot version

4.1.1.stable.official AND  v4.1.1.stable.custom_build [5e6c3a3b8]

### System information

SteamOS 3.4.10

### Issue description

I noticed when running Godot Editor through Steam, using WASD keyboard input, then controller input, then WASD keyboard, that `Input.get_axis()` would stop returning `1.0 -> -1.0` range, and input would randomly be dropped. 

Before touching the controller left stick WASD would work flawlessly as expected. But the second used Steam Deck controller left stick, `Input.get_axis(...)` for `W` and `S` I'd see `0.91 -> -0.99`, depending on the deadzone. Increasing the deadzone to 0.5 when callilng get_axis I still only saw `0.96 -> -0.99`. And using debug prints even while holding down `W` key, the axis result would zero out on and off, Godot didn't maintain my button press, it behaved erratically. Sometimes non-Deck controller axis input would stop entirely, or activate in spurts. 

I noticed this because during SteamDeck desktop mode the normal Deck controller input is mapped to various Desktop functions, so to get Deck controller input I had to run Godot Editor through Steam. That is, SteamInput is normally kicking in and remapping things. 

For me this reproduces both in Steam Deck's Desktop Mode and in Gaming Mode. And it reproduces both in my game and also the First Person Starter Project that's on GitHub.

I also just noticed I don't tend to *start* seeing this when using external controller, just Steam Deck Controller input. However, an external controller's joystick's input via Input.get_axis(...) *also* starts behaving erratically after using Steam Deck controller input. Only the Steam Deck input seems to remain unaffected.

### Steps to reproduce

1. Add Godot Editor as Non-Steam game (I haven't tested with the Windows version included in the Steam Store)
2. Download and extract [First Person Starter](https://godotengine.org/asset-library/asset/424)
3. Open Godot Editor via Steam and scan directory to find First Person Starter. 
4. Play/hit F5 to start playing First Person Starter
5. Press any WASD keyboard input, notice movement feels smooth, expected
6. Now use Steam Deck controller left stick to move character around
7. Go back to trying WASD keyboard input, notice it may behave erratically. ❌
8. Try using an external controller, notice it may behave erratically. ❌
9. Try using the Steam Deck left stick again, notice it's buttery smooth. 

### Minimal reproduction project

[godot-FirstPersonStarter-c9f77c321f63d37ad2d6067107c9c930aa1fae18.zip](https://github.com/godotengine/godot/files/12709717/godot-FirstPersonStarter-c9f77c321f63d37ad2d6067107c9c930aa1fae18.zip)

**Comment by Calinou** [comment]
Please test 4.2.dev5, as this should be at least partially fixed (see https://github.com/godotengine/godot/issues/45628#issuecomment-1668990636).

**Comment by leetNightshade** [comment]
> Please test [4.2.dev5](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-5/), as this should be at least partially fixed (see [#45628 (comment)](https://github.com/godotengine/godot/issues/45628#issuecomment-1668990636)).

Heyy, that seemed to do the trick! Seems like it's working well. Cheers~
