### ISSUE TITLE
Enabling use_xr breaks OmniLights in gl_compatibility

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#82278]
### Godot version

4.1.2-rc.1

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

The Godot XR Dungeon Demo project has a single OmnlLight3D for the player:
![image](https://github.com/godotengine/godot/assets/1863707/524496ab-9ff3-4fa2-b418-f41366904b80)

When the renderer is switched over to gl_compatibility the OmniLight3D stops working:
![image](https://github.com/godotengine/godot/assets/1863707/6a3bc8ca-a4ca-4988-910e-2732500189c5)

This was tracked down to `get_viewport().use_xr = true`. When this is performed, the OmniLight3D fails on both the PC and the headset. If it's commented out then the PC renders correctly and no output goes to the headset.

### Steps to reproduce

This can be replicated by:
- Check out https://github.com/Malcolmnixon/godot-xr-dungeon-template
- Open with Godot 4.1.2
- Switch renderer over to gl_compatibility
- To go directly to broken scene:
  - Set game/zones/level1/level1.tscn as main scene
  - Add Godot XR Tools StartXR node
- Run project on PC and observe failure
- Comment out `get_viewport().use_xr = true` in the Godot XR Tools start_xr.gd script
- Run project on PC and observe light working on PC (but no headset output)

### Minimal reproduction project

A smaller demo project can be constructed if needed; however it still requires enough machinery to start an XR instance in the headset, so it wouldn't be "small".

**Comment by dsnopek** [comment]
This appears to be fixed by PR https://github.com/godotengine/godot/pull/92186 in my testing
