### ISSUE TITLE
Links within docs page can't be navigated back

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#82293]
### Godot version

v4.2.dev5.official [e3e2528ba] (or any 4.x)

### System information

Windows 10

### Issue description

Using links that points to another anchor within a docs page doesn't count as navigation ie. pressing back button takes you out of the page instead of the point where you clicked.
![docs](https://github.com/godotengine/godot/assets/1621768/adb4b1d7-4d6e-4442-9a71-8d380063cdf2)

### Steps to reproduce

1. Open docs page in script editor.
2. Press any link that navigates within the same page (for example property name).
3. Press back.

### Minimal reproduction project

N/A

**Comment by git-kush** [comment]
can you assign me this issue?

**Comment by Zireael07** [comment]
Godot engine does not practice assigning issues. Just create a PR.

**Comment by aXu-AP** [comment]
> can you assign me this issue?

Thanks for looking into it! If you figure it out, you might be interested in #82292 too, which is quite similiar problem.

**Comment by aXu-AP** [comment]
Can't reproduce in latest build, it seems that this got fixed somewhere around 4.3 beta phase (altough I couldn't find the exact pr).
