### ISSUE TITLE
Shader causing crashes

### ISSUE THREAD

**Issue by Mr-Pineapples** [godotengine/godot#82299]
### Godot version

4.1

### System information

Windows 10 Enterprise

### Issue description

Godot crashes whenever attempts to edit or run my shader are made. I sent the file to a friend on better hardware, he could replicate similar outcomes. Results vary from millions of repetitions of the same 50 or so error lines (doesn't seem to be lines I wrote) to Godot simply crashing to the project failing to open properly.

### Steps to reproduce

[DoG_Shader.txt](https://github.com/godotengine/godot/files/12714505/DoG_Shader.txt)

Just run this as a shader within Godot (copy the text from this file into a blank shader) and try to run, edit, or just interact with it in almost any way 

Don't worry about what the parameters are, they don't effect the error. Sorry for messy code, I thought I should leave everything I had as it was when I first encountered the bug.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Why close?

**Comment by bitsawer** [comment]
Looks like a double post https://github.com/godotengine/godot/issues/82301.

**Comment by 457205697** [comment]
Nuzrulislamrohit@gmail.com

Id 457205697

Sir ami vule id two factor authenticator code harai fhelci ektu help kore payment method gula unlocked kore unsuccessful tranjection re success kore access den
