### ISSUE TITLE
export keyword dosen't work

### ISSUE THREAD

**Issue by kshitijaucharmal** [godotengine/godot#82303]
### Godot version

v4.1.1.stable.arch_linux

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 21 Sep 2023 11:06:39 +0000 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz (4 Threads)

### Issue description

New to godot, moving from unity.
Every tutorial shows the way to expose variables in the inspector is to use the export keyword.
Getting an error when using the export keyword:
`Parse Error: Unexpected "Identifier" in class body.`
Is this changed in godot 4, or is it a bug?

### Steps to reproduce

add export keyword before variable name in any script
Example:
export var move_speed : float = 10.0

### Minimal reproduction project

N/A

**Comment by kshitijaucharmal** [comment]
Yeah works now :), could you please link me to these tutorials?

**Comment by AThousandShips** [comment]
[Here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_exports.html)

**Comment by YuriSizov** [comment]
You can start with the step by step guide: https://docs.godotengine.org/en/stable/getting_started/step_by_step/index.html
And check the GDScript syntax reference: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html

In Godot 4 `export` is no longer a keyword, it's an annotation. Annotations are prefixed with `@`. And it's no the only one.
