### ISSUE TITLE
Vulkan: Geometric artifacts in LightmapGI texture when baking with Directional enabled

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#82307]
### Godot version

v4.2.dev.custom_build [609473805]

### System information

Godot v4.2.dev (609473805) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 27.20.21034.37) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Baking lightmaps with directional enabled causes these artifacts to appear:
![image](https://github.com/godotengine/godot/assets/25323231/90dc3af1-6bdf-484c-8f96-4da01821f701)

### Steps to reproduce

Me and @jcostello have yet to figure out (not together) how to reproduce the issue in an isolated project, since it seem to only appear in bigger scenes and the cause is unclear, but it *can* be reproduced on an existing demo project (see MRP below) by doing the following:

1. Open the Hangar scene
2. Enable `Directional` in its `LightmapGI` node
3. Bake
4. Geometric artifacts will appear after baking.

### Minimal reproduction project

https://github.com/perfoon/Abandoned-Spaceship-Godot-Demo

@jcostello: please send your MRP when available. I cannot seem to replicate it with just the Sponza model from the [glTF Sample Models repository](https://github.com/KhronosGroup/glTF-Sample-Models).

**Comment by bitsawer** [comment]
This comment might be related to this issue: https://github.com/godotengine/godot/issues/73124#issuecomment-1475056574.

**Comment by BlueCube3310** [comment]
Should be fixed by #90848.
