### ISSUE TITLE
Godot doesn't render objects correctly

### ISSUE THREAD

**Issue by hormoz1** [godotengine/godot#8231]
Hello.
Godot doesn't render correctly all the objects created in here:
https://ghostbin.com/paste/quj9s
I found this issue to happen in version 2.2 of godot, haven't tested the other versions but I think the issue will happen in other versions except version 3 because it has new renderer too (maybe it will happen is version 3 too).
It uses this library: https://github.com/Zylann/godot_opensimplex but i don't think it is a problem of the library.
here is the problem that occurs:
https://gfycat.com/NegativeValuableBaleenwhale
Seems like it only occurs when the number goes more than a specific number, when testing, the number for me and someone else was different but at 100*100 we both had this problem.
Here is also a scene that you can download and shows this issue:
https://cdn.discordapp.com/attachments/212250894228652034/297829430015819776/tester.tscn
To see the problem, rotate the camera with your mouse.
Why is this happening?
Thank you.

**Comment by bojidar-bg** [comment]
I think there was something related to this in the project settings (max drawn objects)...

**Comment by hormoz1** [comment]
what is it?

**Comment by hormoz1** [comment]
it is rasterizer -> max_render_elements, but seems like it is limited and you can increase it or easily increase it(because i played it with a little and seemed like like if you put a number like 999999999999999999999 it won't change it to that number and maybe you have to play around with a little to increase more than a value) more than a value.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
