### ISSUE TITLE
Triplanar World mapping - incorrect normal direction for normal map

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#82311]
### Godot version

4.1.1 stable

### System information

Windows 10

### Issue description

When setting up a material using triplanar world mapping, the normal map is correctly rotated and applied.
However, the direction that the light is calculated is screwed.

**Here is the expected behaviour in Godot 3.5.2:**

https://github.com/godotengine/godot/assets/9423774/d8f0d600-cd73-4435-85f1-227922060150

**Here is the current, bugged behaviour:**

https://github.com/godotengine/godot/assets/9423774/8f639c3c-be89-4993-97c8-bc55d13a5fb7

### Steps to reproduce

- Create a mesh (e.g. plane)
- Place a light source
- Create a new material
- Under UV1 use the following settings:
![image](https://github.com/godotengine/godot/assets/9423774/eb219286-e4d0-482e-9f48-2b22e2657d4a)
- Rotate the mesh

### Minimal reproduction project

[triplanar-world-normalmaps.zip](https://github.com/godotengine/godot/files/12717396/triplanar-world-normalmaps.zip)

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/pull/49949, which originally attempted to fix a similar issue.

**Comment by RPicster** [comment]
> See #49949, which originally attempted to fix a [similar issue](https://github.com/godotengine/godot/issues/46363).

I'm not sure if this is really related.

I tried to switch to the shader code that was replaced in #49949 : the normals were inverted, but it did not change the behaviour of rotating the mesh, creating the difference between a rotated meshs' normals and an unrotated one.
