### ISSUE TITLE
Editor plugin size doesn't work

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#82319]
### Godot version

4.2 Dev5

### System information

Windows 10

### Issue description

print( dockedScene.size ); # it shows the size changing when dragging the window in the editor

dockedScene.size = Vector2(5, 0);  only works if the user doesnt click and drag the editor window border

### Steps to reproduce

create editor plugin

```gdscript
@tool
extends EditorPlugin

func _enter_tree():
	dockedScene = editorAddon.instantiate();
	add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT, dockedScene );


func _input(event):
	if ( bt3.button_pressed == true ):
		bt3.text = ">"
		dockedScene.custom_minimum_size = Vector2(300,0);
		#dockedScene.set_size(Vector2(300,0), true );
			
	elif ( bt3.button_pressed == false ):
		bt3.text = "<"
		dockedScene.size = Vector2(5, 0);
		dockedScene.custom_minimum_size = Vector2(5,0);
		
		
	print( dockedScene.size );
```

### Minimal reproduction project

fdgfd

**Comment by Calinou** [comment]
@jonSP12 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`gdscript
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by jonSP12** [comment]
theres no info about moving the editor dock via code
the only command that works found in the manual is "custom_minimum_size"
custom_minimum_size doesnt have a max size, the button(expand/hide) stops working once the user manual slides the dock

the function exists in godot editor its used to hide and show panels...

test, proj
[dockSlide2.zip](https://github.com/godotengine/godot/files/12725298/dockSlide2.zip)


dock slide:
![dockSlide](https://github.com/godotengine/godot/assets/77213594/3b62aec9-9780-42ca-b1fe-5d5e93ac1277)

**Comment by YuriSizov** [comment]
You are using a plain `Control` as the root node of your dock widget. You should use a container, like `MarginContainer` or `PanelContainer`, instead. In fact, you should rely on containers pretty much throughout all your UI if you want it to work correctly in the editor.

**Comment by Zireael07** [comment]
@YuriSizov Is that clearly enough documented?

**Comment by YuriSizov** [comment]
@Zireael07 What do you think needs to be documented? This is just how controls and containers work, there is nothing editor specific about their issue.

**Comment by Zireael07** [comment]
The fact that they need containers for editor plugin to work properly *is* editor specific and will catch out people unawares.

**Comment by jonSP12** [comment]
> You are using a plain `Control` as the root node of your dock widget. You should use a container, like `MarginContainer` or `PanelContainer`, instead. In fact, you should rely on containers pretty much throughout all your UI if you want it to work correctly in the editor.

but i rebember trying several other nodes aside from control, before posting the issue, ( PanelContainer included )
i think the problem is related to this:
```
func _enter_tree():
	dockedScene = editorAddon.instantiate();
	add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT, dockedScene );
	pass
```
"CONTAINER_CANVAS_EDITOR_SIDE_RIGHT" is a panel in the created editor, not the insteance "dockedScene". 
Changing the node type in dockedScene doesnt reach the "add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT"

**Comment by jonSP12** [comment]
> > You are using a plain `Control` as the root node of your dock widget. You should use a container, like `MarginContainer` or `PanelContainer`, instead. In fact, you should rely on containers pretty much throughout all your UI if you want it to work correctly in the editor.
> 
> but i rebember trying several other nodes aside from control, before posting the issue, ( PanelContainer included ) i think the problem is related to this:
> 
> ```
> func _enter_tree():
> 	dockedScene = editorAddon.instantiate();
> 	add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT, dockedScene );
> 	pass
> ```
> 
> "CONTAINER_CANVAS_EDITOR_SIDE_RIGHT" is a panel created in the editor, not the insteance "dockedScene". Changing the node type in dockedScene doesnt reach the "add_control_to_container(CONTAINER_CANVAS_EDITOR_SIDE_RIGHT"
