### ISSUE TITLE
Audio changes not reflected while game is running

### ISSUE THREAD

**Issue by stilestr** [godotengine/godot#82315]
### Godot version

4.2-dev5

### System information

Windows 11

### Issue description

When modifying the audio bus levels, changes are not reflected in-game if you have the scene running.
I'm referring to these:
![image](https://github.com/godotengine/godot/assets/4535064/03506abb-fd03-4642-b1b8-1ad144b9b912)

This does not seem to be consistent with the general design of the editor, where changing most properties instantly updates it in your running game. 

The same applies to other audio things, like editing an effect's properties. Godot's audio system, especially the bus, is very intuitive and works great, however, it is difficult to mix and master your game's audio without the game running.

### Steps to reproduce

1. Create a new project and add an AudioStreamPlayer and AudioListener
2. Add an AudioStream to the AudioStreamPlayer and set it to autoplay
3. Run the scene
4. Tab out of the scene and return to the editor, then try to change any of the settings on the "Audio" tab at the bottom of Godot.
5. Nothing happens

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/1186.
