### ISSUE TITLE
VOX to Godot errors

### ISSUE THREAD

**Issue by salciunas** [godotengine/godot#82314]
### Godot version

4.1.1stable

### System information

Godot v4.1.1.stable - Linux Mint 21.2 (Victoria) - Vulkan (Compatibility) - GeForce GT 525M (nvidia; 390.157) - Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 Threads)

### Issue description

Cant use VOX models in Godot, getting this errors:  
res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:205 - Invalid get index '0' (on base: 'Dictionary').
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:50 - Unable to iterate on object of type 'Nil'.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-mesh.gd:62 - Invalid get index '0' (on base: 'Nil').
  core/io/file_access.cpp:762 - Condition "f.is_null()" is true. Continuing.
Importing: res://stand1.vox (scale: 0.1, file version: 200, greedy mesh: true, snap to ground: false)
  Cannot open file 'res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh'.
  Failed loading resource: res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://stand1.vox. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:205 - Invalid get index '0' (on base: 'Dictionary').
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:50 - Unable to iterate on object of type 'Nil'.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-mesh.gd:62 - Invalid get index '0' (on base: 'Nil').
  core/io/file_access.cpp:762 - Condition "f.is_null()" is true. Continuing.

When im trying to drag object to scene getting this errors:   
Cannot open file 'res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh'.
  Failed loading resource: res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh. Make sure resources have been imported by opening the project in the editor at least once.

I'm not sure what's wrong. I'm just a newcomer from Unity Windows to Godot Linux; everything is new for me. I tried an older version of Godot 3, and it was still the same. By the way, I'm using Wine for MagicaVoxel to create VOX models, if this says something.

### Steps to reproduce

res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:205 - Invalid get index '0' (on base: 'Dictionary').
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:50 - Unable to iterate on object of type 'Nil'.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-mesh.gd:62 - Invalid get index '0' (on base: 'Nil').
  core/io/file_access.cpp:762 - Condition "f.is_null()" is true. Continuing.
Importing: res://stand1.vox (scale: 0.1, file version: 200, greedy mesh: true, snap to ground: false)
  Cannot open file 'res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh'.
  Failed loading resource: res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh. Make sure resources have been imported by opening the project in the editor at least once.
  Failed loading resource: res://stand1.vox. Make sure resources have been imported by opening the project in the editor at least once.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:205 - Invalid get index '0' (on base: 'Dictionary').
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-common.gd:50 - Unable to iterate on object of type 'Nil'.
  res://addons/MagicaVoxel_Importer_with_Extensions/vox-importer-mesh.gd:62 - Invalid get index '0' (on base: 'Nil').
  core/io/file_access.cpp:762 - Condition "f.is_null()" is true. Continuing.
Cannot open file 'res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh'.
  Failed loading resource: res://.godot/imported/stand1.vox-f54938a4187fbe5528391b5c7c5cb083.mesh. Make sure resources have been imported by opening the project in the editor at least once.

### Minimal reproduction project

[Bicicle.zip](https://github.com/godotengine/godot/files/12717732/Bicicle.zip)

**Comment by AThousandShips** [comment]
This is an addon, not a feature, please report your issues to the addon instead
