### ISSUE TITLE
ResourceName not saved

### ISSUE THREAD

**Issue by BorisTheBrave** [godotengine/godot#82333]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 30.0.14.9613) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

Setting the resource name of a packed scene does nothing. It displays in the editor, but checking the resource_name field just gives "" and if you restart the editor your setting is gone.

This is rather unreliably to reproduce, but I eventually got the attached minimal project where it happens reliably.

This is probably the cause of https://github.com/godotengine/godot/issues/56177 and https://github.com/godotengine/godot/issues/41619, but it's hard to be sure.

### Steps to reproduce

1) Open attached project
2) open test_scene, select the Sprite2d node in editor.
3) Enter some_value in the name of the resource of the `asdf` field of the attached script.
![image](https://github.com/godotengine/godot/assets/183773/9106a215-29d1-41e8-908b-64fefa445a2d)
4) Run scene. 
Expected: Console Prints "resource_name is some_value"
Actual: Conole Prints "resource_name is "
5) Save everything, restart the editor
6) inspect the Sprite2d again
Expected: Resource name should be some_value
Actual: Resource name is empty

NB: Saving the scene or saving the resource seem to make no difference.

### Minimal reproduction project

[ResourceNameIssue.zip](https://github.com/godotengine/godot/files/12719515/ResourceNameIssue.zip)

**Comment by dylancusson** [comment]
I can't find any reference to `resource_name` in packed_scene, node, or resource.cpp or .h files. Each file has some references to a `name` property though and associated set/get functions.

The name can be set by calling `asdf.set_name("nametoset")` in the script and then read with `asdf.get_name()`.

I'm guessing we'd either need to add a set/get function for resource_name, or change the Inspector behavior to reference the established name properties.

**Comment by ErezShahaf** [comment]
> I can't find any reference to `resource_name` in packed_scene, node, or resource.cpp or .h files. Each file has some references to a `name` property though and associated set/get functions.
> 
> The name can be set by calling `asdf.set_name("nametoset")` in the script and then read with `asdf.get_name()`.
> 
> I'm guessing we'd either need to add a set/get function for resource_name, or change the Inspector behavior to reference the established name properties.



> I can't find any reference to `resource_name` in packed_scene, node, or resource.cpp or .h files. Each file has some references to a `name` property though and associated set/get functions.
> 
> The name can be set by calling `asdf.set_name("nametoset")` in the script and then read with `asdf.get_name()`.
> 
> I'm guessing we'd either need to add a set/get function for resource_name, or change the Inspector behavior to reference the established name properties.

I don't think that there is anything missing, as far I can tell the name setters in resource_name should be enough to set the name property and "emit the changes". Also, the creator of the issue said that "This is rather unreliably to reproduce, but I eventually got the attached minimal project where it happens reliably." Implying that it does work in other project, but sometimes a project can get this bug.

**Comment by dalexeev** [comment]
Not all resource formats support storing the resource name. For example, if you enter a name in the following field, save the resource, and restart the editor, the name will be lost because `*.gd` files only store the source code and no other metadata.

![](https://github.com/godotengine/godot/assets/47700418/49226039-c908-4ecd-ab0e-1ca6436bd368)

Resource (`*.tres`):

```tres
[gd_resource type="Resource" format=3 uid="uid://c4k36vqy48njh"]

[resource]
resource_name = "test"
```

Scene (`*.tscn`):

```tscn
[gd_scene load_steps=2 format=3 uid="uid://wg043njbrkf3"]

[ext_resource type="Script" path="res://test.gd" id="3_1geoe"]

[node name="Node" type="Node"]
script = ExtResource("3_1geoe")
```

We could add an optional `name` attribute:

```tscn
[gd_scene load_steps=2 format=3 uid="uid://wg043njbrkf3" name="test"]
```

**Comment by BorisTheBrave** [comment]
Ok, so it's impossible to fix for *all* resources (as it'll never work for script resources?). Perhaps it would be better to disable the field if it's not going to work?

**Comment by BorisTheBrave** [comment]
In fact, all this has been discussed before.
https://github.com/godotengine/godot/issues/43809
https://github.com/godotengine/godot/issues/13358

Resolution then was "docs already explain this, we don't want to remove it, and we don't want to support it everywhere". Not very satisfying in my opinion, particularly as imho it is not documented.

**Comment by dalexeev** [comment]
> Perhaps it would be better to disable the field if it's not going to work?

To do this properly, a `_is_support_resource_name()` virtual method would be required for `ResourceFormatLoader`/`ResourceFormatSaver`.
