### ISSUE TITLE
Resource.duplicate(true) does not duplicate subresources in arrays

### ISSUE THREAD

**Issue by RolandMarchand** [godotengine/godot#82348]
### Godot version

v4.2.dev.custom_build [2048fe5df]

### System information

Godot v4.2.dev (2048fe5df) - Gentoo 2.14 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

#### Issue description

When duplicating `Resource`s with `duplicate()`, a new `Resource` with its properties copied over is returned. Though, if there are other `Resource`s as properties, only the references to them are copied, not their contents. Unless the argument `true` is given to the function, in which case the `Resource`s contained in the new are unique, not referencing the same ones as the original.

This statement is not true when those `Resource`s are contained within an array. Here are screenshots comparing two resources duplicated with `duplicate(true)` at runtime.

__Note:__ Notice how the `subresource`s are different, duplicated as they should be, but not the elements of `array_of_subresources`.

##### Original resource:
![Screenshot from 2023-09-25 22-33-47](https://github.com/godotengine/godot/assets/90345171/dd532b4c-6b96-4751-8e17-c8f2de8db7f3)
##### Duplicated resource:
![Screenshot from 2023-09-25 22-33-50](https://github.com/godotengine/godot/assets/90345171/f8133290-ffa2-4d2b-ba31-47fdc81ad44e)

### Steps to reproduce

1) Create a custom resource:
```gdscript
extends Resource
class_name CustomResource

# All the resources this array is containing won't be duplicated when using `duplicate(true)`
@export var array_of_subresources: Array[Resource]

# This resource will be duplicated with `duplicate(true)`
@export var subresource: Resource
```
2) Populate its array with any resource, duplicate it with `duplicate(true)`, and compare the two resources from the arrays:
```gdscript
extends Node2D

func _ready():
	var cr := CustomResource.new()
	cr.array_of_subresources = [Resource.new()]
	cr.subresource = Resource.new()
	
	var cr_dup := cr.duplicate(true)
	
	# Success
	assert(cr.subresource != cr_dup.subresource)
	# Failure					
	assert(cr.array_of_subresources[0] != cr_dup.array_of_subresources[0])
```

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/12721343/godot.zip)

**Comment by lyuma** [comment]
Interesting.

I am quite concerned that AnimationLibrary is a resource which holds Animation sub-resources in a Dictionary. Could it have the same issue, or does it only affect arrays.

It would be interesting to test duplicating an AnimationLibrary with Animations inside and see if it possibly has the same issue.

**Comment by aviboddu** [comment]
Taking a look at the [array](https://github.com/godotengine/godot/blob/master/core/variant/array.cpp) and [dictionary](https://github.com/godotengine/godot/blob/master/core/variant/dictionary.cpp) code, it looks like the core issue is that Array::duplicate calls Array::recursive_duplicate, which in turns calls recursive_duplicate for the object.

Seems like that's implemented in the [variant_setget.cpp](https://github.com/godotengine/godot/blame/master/core/variant/variant_setget.cpp#L1891) file. There, we can see that the object duplication does not occur since it 'breaks stuff'.

**Comment by bitsawer** [comment]
@lyuma Looks like your concern about AnimationLibrary duplication might have been answered in https://github.com/godotengine/godot/issues/82421 if I understood that right. I guess the recursive duplication is currently commented out as mentioned by aviboddu in previous message.

**Comment by AnidemDex** [comment]
Is this related to https://github.com/godotengine/godot/issues/74918 ?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74918.
