### ISSUE TITLE
Error spam when undoing deleting a singleton in the editor

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#82363]
### Godot version

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev5 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

```
Remove Autoload
Undo: Remove Autoload
  core/object/undo_redo.cpp:334 - Error calling UndoRedo method operation 'set_persisting': 'ProjectSettings::set_persisting': Method not found
  core/object/undo_redo.cpp:334 - Error calling UndoRedo method operation 'set_order': 'ProjectSettings::set_order': Method expected 0 arguments, but called with 0
```

### Steps to reproduce

Project Settings > Autoloads > Press the trash can button > Press Undo

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
At least the first one refers to a method which no longer exists indeed:
```
$ rg set_persisting
editor/editor_autoload_settings.cpp
342:                    undo_redo->add_undo_method(ProjectSettings::get_singleton(), "set_persisting", name, true);
799:    undo_redo->add_undo_method(ProjectSettings::get_singleton(), "set_persisting", name, true);
```

**Comment by jsjtxietian** [comment]
Looks like there is already a pr for this : #79832
