### ISSUE TITLE
Hotkey for save does not work for saving current scene when script editor is in focus.

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#82367]
### Godot version

4.2.dev.5

### System information

Windows 11

### Issue description

When you have a scene open with some export variables and script editor is active. If the scene is modified by modifying the export variables in the inspector.  Pressing `Ctrl + S` will not save the scene, when the focus and cursor active in script editor.

This is working fine in 4.1.1

This may have been solved by a PR I don't remember. Raised to make sure the issue is addressed.

### Steps to reproduce

- Open a scene with an export variable and a script attached.
- Switch to the script editor.
- Modify the export variables so that scene is modified. 
- Now focus on the script editor by clicking inside the script editor (Important Step) 
- Now press `Ctrl + S`
Expected the scene and any changes in the script is saved.
It will not.

### Minimal reproduction project

Not Applicable

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/78672

**Comment by AThousandShips** [comment]
My bad wrong duplicate, but duplicate, finding the correct issue

**Comment by AThousandShips** [comment]
This is a case of a contextual shortcut, see https://github.com/godotengine/godot/pull/79337

When inside the script editor the script editor has focus, by design, so that you can save a script instead of a scene

To work around this if you like you can add a shortcut for save scene, under `Editor > Save Scene`

**Comment by mieldepoche** [comment]
- `Editor > Save Scene` is <kbd>Ctrl + S</kbd> by default.
- `Script Editor > Save` was apparently modified to <kbd>Ctrl + S</kbd> by default in 4.2, which takes over the save scene shortcut I assume, so to get the old behavior back you have to change it back to what it was: <kbd>Ctrl + Alt + S</kbd> (or any other thing).

As a long time user, stumbling upon this was really frustrating. It can be easily worked around though but I don't really have a usecase for saving the script alone and not the currently modified scene.

**Comment by AThousandShips** [comment]
The previous behaviour was because of a limitation:
> Makes sense to me. The only reason why this setting differed from the Save Scene one is because before 4.0, we didn't support shortcut contexts.

**Comment by tokengamedev** [comment]
So if I understand correctly, if I `Ctrl +S` outside script editor the script should not be saved. because contextually they are different now.

**Comment by tokengamedev** [comment]
Let me know if that is the case, then I will raise a bug again.

**Comment by tokengamedev** [comment]
> Script Editor > Save was apparently modified to Ctrl + S by default in 4.2, which takes over the save scene shortcut I assume, so to get the old behavior back you have to change it back to what it was: Ctrl + Alt + S (or any other thing).

Thanks,  you are life saver. I did change and it worked fine. 

Closing this issue as this is a default value change as mentioned in https://github.com/godotengine/godot/pull/79337
