### ISSUE TITLE
SSAO doesn't play well with smooth shading

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8237]
Tested on Godot 3.0 af282b56feb8d84049f911dd1d91d82bd2211727
Windows 10 64 bits nVidia GeForce 940M

I generated a smooth mesh out of voxels, it looks smooth, but SSAO makes its edges appears anyway:

![image](https://cloud.githubusercontent.com/assets/1311555/24593525/aca75f4a-1824-11e7-8cf5-6bc9adc628a8.png)

I understand it's based on depth, in which case it will indeed make "edges" stand out. But what's the point of having a smooth mesh then? Is there any way of using the normals to improve this?

Also, borders of the screen got affected by SSAO too, it doesn't looks right.

Could be related to https://github.com/godotengine/godot/issues/8120

**Comment by reduz** [comment]
This is a known limitation of SSAO, unfortunately there is not much it can be done. You can even see this happen in blockbuster titles like Zelda BOTW. Best you can do is create geometry that is not affected by this, make the SSAO radius bigger or not use SSAO.

**Comment by Zylann** [comment]
I had a look at Unity terrains which are a soup of triangles like the one I shown, but somehow I don't see such artefacts.

**Comment by reduz** [comment]
It is most likely related to the SSAO radius, did you try changing it?

**Comment by Zylann** [comment]
Hmm after more testing with a very similar mesh, Unity does have the same issue, though it looks slightly different (this is an Obscurance image effect, in case it matters):

Enabled:
![image](https://user-images.githubusercontent.com/1311555/27097977-e1bf28bc-506d-11e7-9293-cb588d3678d0.png)

Disabled:
![image](https://user-images.githubusercontent.com/1311555/27097966-d781f8b6-506d-11e7-9169-742f8c789907.png)

**Comment by reduz** [comment]
looks like the same thing you have on Godot with less intensity..
