### ISSUE TITLE
Imported .glb armature, some wrong offset bone connections, can't filter them when blending

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#82383]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

in Blender, pelvisL and pelvisR are offset from spine01, not children of spine, but Godot combines spine, pelvisR and pelvisL, still shows pelvisL and pelvisR as different bones but can't filter those two when blending. Many other bones can't be selected either.

![imagen](https://github.com/godotengine/godot/assets/98270528/9905ab60-6c05-48c5-a074-bff6b454968d)

those bones work fine in Blender

![imagen](https://github.com/godotengine/godot/assets/98270528/94344945-f04c-4560-81c1-671032b06490)

### Steps to reproduce

.

### Minimal reproduction project

[test_animations.zip](https://github.com/godotengine/godot/files/12735163/test_animations.zip)
[test-animations-blender.zip](https://github.com/godotengine/godot/files/12735165/test-animations-blender.zip)

**Comment by venilark** [comment]
added test project and also blender file if necessary

**Comment by naelstrof** [comment]
Bones have no inherent length or direction.

Bone orientation in godot is displayed from root to leaf.
Bone orientation in Blender is displayed by creating fake "tail" representations that the user can edit. These are discarded on export.

Internally bone orientations for both are computed via a transformation matrix. What you're seeing is a difference in display, functionally they are identical.

As for selecting them in blends, I'm not familiar enough with godot to know for sure, but have you tried creating a bone map? It allows you to intricately describe aspects of the character.

![image](https://github.com/godotengine/godot/assets/1131571/c2718789-d3cb-4d90-8e10-77a8d0e3ede3)

You can even specify tail direction there, which might help with displaying the bone orientation in the way that you expect.

**Comment by TokageItLab** [comment]
This has been reported many times before, but it is not a bug.

It is due to the difference between Blender's Head-Tail format and glTF's Node format. As for the missing bones, this is because Blender-glTF-io lacks the ability to output leaf bones, so please send your request there https://github.com/KhronosGroup/glTF-Blender-IO/issues/1261.
