### ISSUE TITLE
Edge detection shader?

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8239]
As godot 3.0 has ssao, I thought it might be possible to include something similar that does the opposite.... A shader which adds a highlight on edges, with a blur as like ssao would be pretty cool!

I found the following code:
http://ikstewa.blogspot.com.au/2012/07/real-time-image-based-edge-detection.html
https://github.com/ikstewa/edge-detection

**Comment by Zylann** [comment]
I wrote a similar shader once in 2.1 by taking an example on the screen-reading shaders demo. I think it wouldn't be hard to do it using depth :)

**Comment by groud** [comment]
@akien-mga, @reduz : isn't this corresponding to the cell shader (the "toon" one) ?

**Comment by Zylann** [comment]
Yeah now in Godot 3.0 you have two ways of achieving this:
- Add a next pass with grown mesh, inverted normals and black albedo, cheap but easy (as seen in material testers demo)
- Do the 2.1 thing I mentionned, which is a screen-reading shader that performs edge detection on pixel level (so you can achieve Rust-like sharpening for example). Might look better but is also more expensive.

**Comment by kubecz3k** [comment]
I'm revisiting old issues. As stated above I'm not sure if this one is still valid, and if yes than I'm not sure if the request should not be created in demo repository: https://github.com/godotengine/godot-demo-projects/issues

**Comment by nagasawamaki** [comment]
> 
> 
> Yeah now in Godot 3.0 you have two ways of achieving this:
> 
>     * Add a next pass material with grown mesh, inverted normals and black albedo, cheap but easy (as seen in material testers demo)
> 
>     * Do the 2.1 thing I mentionned, which is a screen-reading shader that performs edge detection on pixel level (so you can achieve Rust-like sharpening for example). Might look better but is also more expensive.

For method 1. I can only get the below result:
![圖片](https://user-images.githubusercontent.com/24987226/66658747-b0517280-ec74-11e9-9833-b98c3f03ba8a.png)
But I want the below:
![圖片](https://user-images.githubusercontent.com/24987226/66658768-bc3d3480-ec74-11e9-9726-76c9b2f11305.png)

For method 2, can it get  the above result?
If yes, it would be great if you can share the code.

PS. [Images source](https://www.reddit.com/r/godot/comments/7ljop3/trying_to_make_an_edge_detector_postprocess_effect)
