### ISSUE TITLE
Game exported to android with Immersive mode enabled is not hiding status bar

### ISSUE THREAD

**Issue by rmichaluszek** [godotengine/godot#82407]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3699) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

I have immersive mode enabled, but the game is still not fullscreen on android device ( Redmi Note 9 )

![obraz](https://github.com/godotengine/godot/assets/20546844/2eb3939c-2add-479f-a059-6098959edfb8)

The same project exported from Godot 4.1.1_stable works fine ( it hides the status bar )

### Steps to reproduce

1. Create any project with literally nothing and export it to android ( immersive mode is enabled by default )
2. Game runs with status bar shown, and should be otherwise. Disabling the immersive mode also shows the status bar but this is correct.

### Minimal reproduction project

Empty project, you can see that gray background doesn't cover whole screen, and the status bar with clock is shown when the immersive mode is enabled ( it is by default )

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80574.
