### ISSUE TITLE
Theme items that don't exist in the default theme are not listed in the editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#82402]
### Godot version

4.2 251fb83

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Button has `icon` theme item:
![image](https://github.com/godotengine/godot/assets/2223172/2afa6926-940a-4811-ad46-c9140fee31ee)
But it does not appear in the overrides:
![image](https://github.com/godotengine/godot/assets/2223172/6bbbdda8-63c7-407b-9f39-f2bbeda22319)
Nor in the theme editor:
![image](https://github.com/godotengine/godot/assets/2223172/19d1e782-df37-4082-93ee-eeafed282157)

### Steps to reproduce

1. Add Button
2. Try to find `icon` theme property (not the Button's own property)
3. It exists only in theory (documentation)

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
By the way, there is also `get_argument_options` which uses the default theme right now, which should also be fixed to address this issue.
