### ISSUE TITLE
Android Export, renderer gl_compatibility: glb with skeleton3d and GPUParticles3D invisible on the second run of the app

### ISSUE THREAD

**Issue by robertomollo** [godotengine/godot#82419]
### Godot version

4.1.1

### System information

ubuntu 22.04.3

### Issue description

The 3D objects con huesos and particles are not visible in the second run of the exported app, they are only visible in the first run after installing the app.
This only happens when Godot 4.1.1 is configured with "Rendering Method.mobile: **gl_compatibility**" and not with "Rendering Method.mobile: **mobile**". This only happens when exporting to Android and not to Linux or Windows.
I realized the following:
-On Android in the "Applications > Storage" section of my app, if I **delete "application data**" not "**cache**", the app works without problems, but on the second run after "**delete data**", it appears again the problem. Apparently if there is data, it resubmits the reported failure, until "delete data".
The problem is replicated in: Samsung A22 with Android 13, Samsung SM-T220 with Android 13, in Samsung A20s with Android 11, the reported problem does not occur.
-With Godot 3.5.2 this problem does not occur. Also note that on Android in the "Applications>Storage, **Data**" section this is always at **0 B** unlike with Godot 4.1.1 in the second execution of the app, it has data and it is necessary to "Delete data" so that it does not present the reported failure.

### Steps to reproduce

The second time the app is run, the reported failure appears.

### Minimal reproduction project

[prueba_linux.zip](https://github.com/godotengine/godot/files/12733240/prueba_linux.zip)

**Comment by bitsawer** [comment]
Does fully clearing the app data or uninstalling it and then disabling shader cache and re-exporing it help?  You can disable shader cache by unchecking **Project Settings -> General -> Rendering -> Shader Compiler -> Shader Cache -> Enabled**.

**Comment by SirTodd** [comment]
I have a published app since Godot 4.0, and I am almost sure this started happening in 4.1. In older devices it will crash the app entirely instead of not displaying the particles, even though the first time it appears correctly. Most likely shader issue.

**Comment by robertomollo** [comment]
> Does fully clearing the app data or uninstalling it and then disabling shader cache and re-exporing it help? You can disable shader cache by unchecking **Project Settings -> General -> Rendering -> Shader Compiler -> Shader Cache -> Enabled**.

Thank you very much for your prompt response and accurate response. I tried it many times and the error did not appear again.
Would this only be a temporary solution for the reported problem?

**Comment by robertomollo** [comment]
> I have a published app since Godot 4.0, and I am almost sure this started happening in 4.1. In older devices it will crash the app entirely instead of not displaying the particles, even though the first time it appears correctly. Most likely shader cache issue.

Greetings. Confirmed with what you say. In Godot 4, I did not have these problems, they appeared from version 4.1. "Shadown", "glow", "DOF BLUR" are not yet available for "Opengl"

**Comment by Zireael07** [comment]
This needs to be labeled as a regression then

**Comment by AndyAstrand** [comment]
Visiting here from issue #80057, I can confirm that disabling the Shader Cache does fix the problem. The skeleton both stationary and animated is now visible on the device with or without remote debug in use. I'll track this issue to be aware of when the issue gets fixed and I can re-enable it again. It would be nice to know what the consequences are for having it turned off.

**Comment by Calinou** [comment]
> It would be nice to know what the consequences are for having it turned off.

Disabling shader cache means that shader compilation stutter (when seeing new shaders, particles, etc) will occur every time the project runs, instead of only occurring the first time you run a project.

**Comment by Arthas92t** [comment]
@Calinou @robertomollo i fixed this issue, tested on vivo 1907, vsmart active 3, samsung a12 and few more devices. Pls check if it will work for you.
here is the fix #88549

**Comment by SinaZK** [comment]
Is there any chance this fix get cherry picked for next 4.1 maintenance release?
