### ISSUE TITLE
First button drawn in wrong position when Camera2D is zoomed and in Forward+/Mobile mode

### ISSUE THREAD

**Issue by MBoffin** [godotengine/godot#82410]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 27.20.100.8681) - Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 Threads)

### Issue description

When on my laptop, I noticed the first button of the buttons in my project was being drawn in totally the wrong location, but only on my laptop. And if I switched it to Compatibility mode, it worked correctly. See the following screenshots of Forward+ and Compatibility mode, respectively.

![forwardmode](https://github.com/godotengine/godot/assets/673691/03c2747d-d16c-4330-97da-e331fe3243cf)
![compatibilitymode](https://github.com/godotengine/godot/assets/673691/a7f49994-6286-4ec0-8aa1-9a51324ed3a0)

In playing around with things, I determined that the zoom of the Camera2D is what causes the first button to be drawn in the wrong position. It's not the button itself either. If I switch the order of the two buttons, so the other button is first, it will now happen to the other button instead. Additionally, the text of the button is drawn in the correct position. The rest of the button, however, is what gets drawn in the incorrect position.

My laptop has no dedicated GPU, which I suspect is where the problem lies. It does not happen when using either of my desktops, both of which have a dedicated GPU (2070 SUPER and 3090).

I created a sample project that successfully reproduces this bug and have attached it. I tried to make it match what I had in my original project in terms of layout, though stripped out anything else irrelevant.

### Steps to reproduce

1) Place two buttons as children of a CanvasLayer, positioned some place where it overlaps the camera's viewport.
2) Make sure the Camera2D has a non-(1,1) zoom.
3) Run the project and notice the first button is drawn in the wrong position, and seems to be relative to the camera and its zoom.

### Minimal reproduction project

[ButtonBug.zip](https://github.com/godotengine/godot/files/12732191/ButtonBug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.
