### ISSUE TITLE
Disappearing Decals

### ISSUE THREAD

**Issue by stilestr** [godotengine/godot#82417]
### Godot version

Godot v4.1.1.stable 

### System information

Windows 11 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.21029.6002) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

This is probably a documentation issue more than an engine issue, but I think it is still worth mentioning as some clarity on this might help others.

I have a scene where a ball bounces around a room, and leaves behind one decal each time it bounces. This works great and is very performant (and it looks very cool), except for when I have about 800 decals. Then, they start to disappear and reappear as you move the camera. I assume this is due to a limitation in how many decals can be rendered at once, however that limit does not appear to be documented anywhere, only the 8 decal limit for mobile rendering.

- Is this a glitch, or is there a hard coded cap to the amount of decals rendered?
- If there is a cap, what is that cap?
- Is there a way to modify that cap, or was that cap chosen for a reason? If I have the hardware to spam thousands of decals, I would like to be able to do that, even if it's a bad idea, as there are some really cool effects you can make with decals (for non-game applications, in my case).

If there is a cap I would be happy to modify the documentation to explain the cap.

### Steps to reproduce

1. Create a 3D scene
2. Place 800 or more decals, spread across a surface
3. Move the camera around, and see that decals appear and disappear 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
For performance reasons, the limit is 512 clustered elements by default. A clustered element includes omni/spot lights, reflection probes and decals. You can increase it in the Project Settings.

**Comment by stilestr** [comment]
Thank you!
