### ISSUE TITLE
Theme Font Size Causing Massive Slow Downs while entering play mode or opening project.

### ISSUE THREAD

**Issue by mcdz** [godotengine/godot#82425]
### Godot version

4.1.1 stable official

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3742) - AMD Ryzen 3 3100 4-Core Processor (8 Threads)

### Issue description

Theme for button, increasing the font size make editor busy when entering play mode or opening the project.

### Steps to reproduce

Create a theme for button.
override all
then in font section, increase the font size (64) and use this theme on a button.
enter play mode.

### Minimal reproduction project

empty project with a single scene and a button will do. (I'm new to Godot, but encountered this)

**Comment by YuriSizov** [comment]
Please provide an MRP, no matter how trivial you think it is to reproduce.

**Comment by desastreger** [comment]
I came in here because I ran into the same bug.  I noticed that if I install the font and load it to the themet from SystemFont instead of font file, slowdown goes away. I can only describe the bug as it's running a full import of the font each time I hit debug

**Comment by Calinou** [comment]
@mcdz @desastreger Please upload a minimal reproduction project to make this easier to troubleshoot.

**Comment by rodimusX** [comment]
I had this issue in 4.1.1. In File Explorer you'll see any .tscn files with new Labels have blown up in size. My workaround is:
-> Select your scene in Godot
-> For each Label go to theme_overide -> Font and clear the font file
-> From the Font dropdown select New FontFile
->Go back to the Font dropdown and select QuickLoad.  Load your font
->Repeat for all Labels
My load in time went from 42 seconds to 5 seconds after updating.
Good Luck.
