### ISSUE TITLE
VK_ERROR_DEVICE_LOST - Crash when opening a 3d project

### ISSUE THREAD

**Issue by dweinbaum** [godotengine/godot#82433]
### Godot version

v4.1.2.rc1

### System information

Godot v4.1.2.rc1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21018.6011) - 12th Gen Intel(R) Core(TM) i3-12100F (8 Threads)

### Issue description

Opening a 3d project (started fresh three times) after a few hours of 3d tinkering (adding meshes, lights, cameras, baking GI) creates a 100% crash for me, yielding this in the console:

```
Godot Engine v4.1.2.rc1.official.58f0cae4a - https://godotengine.org
OpenGL API 3.3.0 Core Profile Context 22.20.27.09.230823 - Compatibility - Using Device: ATI Technologies Inc. - AMD R0

Editing project: C:/Users/DJWei/OneDrive/Documents/Test2
Godot Engine v4.1.2.rc1.official.58f0cae4a - https://godotengine.org
Vulkan API 1.3.250 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon RX 6600

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor setting.
     at: _editor_init (modules/gltf/register_types.cpp:73)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2360)
```

If I delete the .godot folder, I can open this new project exactly once. Then attempting to reopen it (even after doing nothing) gets me the vulkan error and the crash 100% of the time. I have attached the contents of a crashing project.

### Steps to reproduce

1. paste the contents of VulkanBugProject.zip into a fresh project, overwriting any default files.
2. try to open the project from the project manager

### Minimal reproduction project

On my system, I can open this project exactly once with a fresh .godot folder. I save, exit, and try to repopen, I get a 100% crash on opening.

VulkanBugProject.zip](https://github.com/godotengine/godot/files/12736840/VulkanBugProject.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.

In the meantime, you can test https://github.com/godotengine/godot/pull/80566 lmocally or use the Compatibility rendering method.
