### ISSUE TITLE
Memory leaks when playing 3d skeleton animation while TAA or FSR2.2 is enabled

### ISSUE THREAD

**Issue by maidopi-usa** [godotengine/godot#82446]
### Godot version

4.2.dev5

### System information

Windows11 - Godot v4.2.dev5 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 527.56 - AMD Ryzen 7950X 

### Issue description

When anti-aliasing option that needs motion-vector buffer is enabled (TAA or FSR2.2), and then playing skeleton animation through an AnimationPlayer node will lead to memory consumption keeping growing up, which can be inspected on the debugger panel. 
And toggle these AA options off, everything goes well.

It seems that this issue has appeared since v4.2.dev4 in my rough tests and compare, and v4.2.dev3 works fine.

I guess maybe related to [Add motion vector support for animated surfaces](https://github.com/godotengine/godot/pull/80618)?

And there's some little extra information that might be helpful or not. In my experiment, sometimes randomly switching through [stop] status and animation clips during runtime can temporarily stops memory consumption growing up.
![growing_memory](https://github.com/godotengine/godot/assets/33864304/1f5295b2-5490-4b18-b1fa-b1c0f0baefb9)

### Steps to reproduce

1. Open MRP.
2. Run Project.
3. Toggle checkbutton on top-left to enable or disable TAA.
4. Look at memory usage displayed in bottom-right.

### Minimal reproduction project

[SkeletonAnimation.zip](https://github.com/godotengine/godot/files/12739840/SkeletonAnimation.zip)

**Comment by DarioSamo** [comment]
Found the reason, will PR a fix.
