### ISSUE TITLE
Windows CLI export hangs

### ISSUE THREAD

**Issue by ashtonmeuser** [godotengine/godot#82452]
### Godot version

4.1.1-stable

### System information

Microsoft Windows Server 2022 10.0.20348

### Issue description

Exporting a project via CLI in Windows Bash hangs indefinitely. The same project exported via CLI succeeds on macOS and Linux.

Command used to export:
```
./Godot_v4.1.1-stable_win64.exe --verbose --headless --no-window --export-release --path examples/wasm-test "Windows" ../../WasmTest.exe
```

This was encountered when exporting in GitHub Actions. Failed run can be found [here](https://github.com/ashtonmeuser/godot-wasm/actions/runs/6321400774/job/17165403457). The errors found in the logs are only produced on termination of the job. Repo can be cloned to repro issue. Note that the same action succeeds for macOS and Linux.

### Steps to reproduce

1. Clone https://github.com/ashtonmeuser/godot-wasm
2. Run `./Godot_v4.1.1-stable_win64.exe --verbose --headless --no-window --export-release --path examples/wasm-test "Windows" ../../WasmTest.exe` (replacing Godot executable path as necessary)

### Minimal reproduction project

https://github.com/ashtonmeuser/godot-wasm

**Comment by bruvzg** [comment]
> ./Godot_v4.1.1-stable_win64.exe

Are you sure it is hanging? This is GUI binary, it's not taking control from console, and therefore the shell won't redraw the prompt when it's done (but you can press Enter once and continue to use shell). For the same reason, it won't work in scripts or CI, shell won't get exit code and won't be able to wait for completion. For console operations, you should use console wrapper binary (one with `console` suffix in the name).

**Comment by ashtonmeuser** [comment]
@bruvzg Thanks for the suggestion! I will test with the console Windows executable and report back.

Interestingly, the other action runs successfully with the same (non-console) executable. This action runs the command `./Godot_v4.1.1-stable_win64.exe --headless --no-window --debug --path examples/wasm-test` and can be seen successfully completing [here](https://github.com/ashtonmeuser/godot-wasm/actions/runs/6321400774/job/17165403653). Perhaps this exits as expected because it is running a project directly (which, in addition, has a call to `OS.exit()`) rather than the editor.

**Comment by ashtonmeuser** [comment]
Same thing happens with the console executable. Command run `./Godot_v4.1.1-stable_win64_console.exe --verbose --headless --no-window --export-release --path examples/wasm-test "Windows" ../../WasmTest.exe`. Job and logs [here](https://github.com/ashtonmeuser/godot-wasm/actions/runs/6341819587/job/17226339557).

**Comment by ashtonmeuser** [comment]
Unable to repro on a personal Windows machine. There were, however, several warnings related to inaccessible rcedit. Disabling the Modify Resources option in the Windows export preset (`application/modify_resources=false`) solves this issue. My best guess is that the Windows GitHub Actions runner has a failsafe if an action even attempts to access rcedit. Closing this issue.
