### ISSUE TITLE
Vs code Godot extension 

### ISSUE THREAD

**Issue by Samyak-Bumb** [godotengine/godot#82460]
### Godot version

4.0

### System information

Windows 10

### Issue description

Hello, I'd like to suggest the creation of a dedicated section for feature requests. The current issue is not a significant problem but rather a request for a new feature.

I propose the development of an official Godot extension for Visual Studio Code, packed with comprehensive GDScript features, syntax highlighting, code snippets etc. Many members of the Godot community recommend using Visual Studio Code for code/script writing, and with the community's growth, I believe this would be a valuable addition. I kindly request you to consider this idea and explore the possibility of its implementation.

### Steps to reproduce

Not a bug

### Minimal reproduction project

Not a bug

**Comment by YuriSizov** [comment]
Hey there! We already have a [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools), and here's it's repo: https://github.com/godotengine/godot-vscode-plugin. You can leave bug reports and feature proposals in there. 

> I'd like to suggest the creation of a dedicated section for feature requests.

For the engine feature requests go into the proposals repository: https://github.com/godotengine/godot-proposals. Make sure to read the readme file to learn how to make one.
