### ISSUE TITLE
Disabling and re-enabling the plugin you have selected in-editor crashes Godot.

### ISSUE THREAD

**Issue by CantyCanadian** [godotengine/godot#82461]
### Godot version

v4.1.1.stable.mono.official

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

If you have a plugin selected in the top bar, then disable and re-enable it, it crashes Godot.

![crash](https://github.com/godotengine/godot/assets/7960042/8f435d23-27f1-4888-9302-b3c9a0c666c9)

### Steps to reproduce

1. Load and enable a plugin.
2. Select that plugin in the top bar to enter its window.
3. Disable then re-enable that plugin.
4. Close the settings window and try clicking another item in the top bar. 

### Minimal reproduction project

[Repro.zip](https://github.com/godotengine/godot/files/12742439/Repro.zip)

**Comment by jsjtxietian** [comment]
I did some test with current master branch and it did not crash. Maybe it's already fixed ?

**Comment by CantyCanadian** [comment]
I've been overall having a lot of issues with C# developing anything editor-related, so it might be a mix of "on my machine", "due to my code" and "because it's C#". For all I know, moving C# to a GDExtension will be my savior.
