### ISSUE TITLE
AudioStreamRandomizer.random_volume_offset_db not working

### ISSUE THREAD

**Issue by thalestale** [godotengine/godot#82469]
### Godot version

Godot v4.2dev5

### System information

Godot v4.2.dev5 - Windows 11- GLES3 (Compatibility) - NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3742) - AMD 4700S 8-Core Processor Desktop Kit (16 Threads)

### Issue description

AudioStreamRandomizer's random_volume_offset_db does not make any audio volume variations playing an WAV file through an AudioStreamPlayer.

### Steps to reproduce

- Create an AudioStreamPlayer node
- Load an AudioStreamRandomizer
- Load an WAV file
- Set Volume Offset to any value

Playing it gives the same audio level everytime

### Minimal reproduction project

[ASRandomizer Bug.zip](https://github.com/godotengine/godot/files/12745215/ASRandomizer.Bug.zip)

**Comment by jsjtxietian** [comment]
Confirmed. Looks like the value is set but not used when play the audio.

**Comment by thalestale** [comment]
I don't know if it's worth mentioning, but I also checked the stable Godot v4.1.1 and the issue is also occuring there.
