### ISSUE TITLE
GPULightmap doesn't take into account transparent materials

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#82467]
### Godot version

v4.2.dev.custom_build [4c3dc2636]

### System information

Ubuntu with Nvidia 2060

### Issue description

Lightmap doesn't work well with transparent materials

![image](https://github.com/godotengine/godot/assets/1168582/4fe9dd2c-a9b4-4b9e-bb9e-a7452e4f2a59)

### Steps to reproduce

Bake MRP

### Minimal reproduction project

[LightmapTransparent.zip](https://github.com/godotengine/godot/files/12744879/LightmapTransparent.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77590.
