### ISSUE TITLE
OpenGL: Debug draw modes are not working

### ISSUE THREAD

**Issue by doegee** [godotengine/godot#82485]
### Godot version

4.1.1 Macos

### System information

M1 Macbook Air big sur

### Issue description

Wireframe mode does not work in 4.1.1 WHEN COMPATIBILITY RENDERER IS ENABLED
<img width="1100" alt="image" src="https://github.com/godotengine/godot/assets/72935900/589db942-e1a2-421e-8416-a4c09646d393">
this is godot 3.5 ^
<img width="1162" alt="image" src="https://github.com/godotengine/godot/assets/72935900/ebd69864-3505-4337-a191-671e3b55f4c1">
this is godot 4.1.1 ^

### Steps to reproduce

have a 3d mesh

set perspective to display wireframe

enable the compatibility renderer

be on mac (?)

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
Compatibility mode is still under development, cc @clayjohn

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/55900.

None of the debug draw modes are implemented in OpenGL currently.
