### ISSUE TITLE
CONTRIBUTING.md link to editor translations readme is broken

### ISSUE THREAD

**Issue by UFCarlosMartinez** [godotengine/godot#82495]
### Godot version

4.1.1-stable

### System information

Windows 11

### Issue description

When clicking "translation readme" in the "CONTRIBUTING.md" file:
![image](https://github.com/godotengine/godot/assets/109010812/ac4fffcb-cf32-4380-ab02-67d540055f49)

It shows:
![Screenshot 2023-09-28 151721](https://github.com/godotengine/godot/assets/109010812/f7fac82b-fa59-4047-97b3-fb921c92887d)

 This means important information for new translators wanting to contribute is missing.

I believe, this issue is cause by not having the proper link attached. The current link seems to taken from an old file that is no longer present in the current version of the project (editor/translations/README.md).

I think the intended link is:
https://docs.godotengine.org/en/latest/contributing/documentation/editor_and_docs_localization.html
My reasoning is because the information in this link seems to be intended to be read by new translators but can only be found by diving deeper into other links, making the instructions confusing.

Perhaps, a possible solution would be to simply change the link to the one I provided in the CONTRIBUTING.md file, or just removing it entirely until a new README file is created.

### Steps to reproduce

In the "CONTRIBUTING.md" file go to the headline that says "Contributing to Godot's translation" and click on "translation readme"

### Minimal reproduction project

N/A

**Comment by MatheusPese** [comment]
The actual intended link is a [readme.md](https://github.com/godotengine/godot/blob/3.5/CONTRIBUTING.md) file that is present all versions of godot but [4.0](https://github.com/godotengine/godot/tree/4.0/editor/translations/README.md) and [4.1](https://github.com/godotengine/godot/tree/4.1/editor/translations/README.md).

Should be an easy fix if there is not any change in the way godot handles translations from 3.x to 4.x.
