### ISSUE TITLE
Profiler buttons, Project Camera Override are not working. Godot does not detecting project instance

### ISSUE THREAD

**Issue by umutbalkan** [godotengine/godot#82492]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/8284138/b063fe62-4a30-475f-b7f8-7849f0fbd177)

I can't use the profiler, buttons are greyed out even though project is running. Am I missing something?
Also,
- remote / local tab under the Scene tab does not appear when the scene is running and rendered.
- Project camera override button does not work

### Steps to reproduce

- Press F5
- Click on Debugging
- Unable to click Start Stop buttons

### Minimal reproduction project

[ahey.zip](https://github.com/godotengine/godot/files/12752731/ahey.zip)

**Comment by rsubtil** [comment]
It looks like the launched instance is not being able to connect to the editor. Can you see any output over on the Output tab when you launch your game?

Check your host/port as well on **Editor Settings** > **Network** > **Debug**, especially if some other app in your system is using the default port.
![image](https://github.com/godotengine/godot/assets/6501975/22dee3d6-00ac-4fd3-a263-5ea7cb3e30e2)

**Comment by umutbalkan** [comment]
Aaah I am using VPN with split tunneling, that might be the issue here. Thanks
