### ISSUE TITLE
No obvious way to delete `AnimationNodeBlendTree` node in `AnimationTree` editor

### ISSUE THREAD

**Issue by wjagodfrey** [godotengine/godot#82501]
### Godot version

4.2-mono-rc5

### System information

MacOS 12.3

### Issue description

When adding a new node to an `AnimationNodeBlendTree` in the `AnimationTree` editor, I can't find a way to remove it again other than undo.

- `Ctrl+Delete` removes the `AnimationTree` node.
- Right click on the node opens the `Add Node` menu.
- `Delete`/`Backspace` does nothing.
- Macbook Pro keyboard doesn't have a `Del` key.
- `Fn+Delete` (Mac `Del` emulation) does nothing.

<img width="999" alt="image" src="https://github.com/godotengine/godot/assets/5732688/7408e89e-0d11-4b2e-8b13-1947fa75cf56">

### Steps to reproduce

1. Add an `AnimationTree` node with an `AnimationNodeBlendTree`
2. Open the `AnimationTree` editor
3. Add a node
4. Try to remove it

### Minimal reproduction project

Should be easily reproducible without an MRP

**Comment by SaNeOr** [comment]
Select Node -> Press Delete Key
seems to work!

**Comment by wjagodfrey** [comment]
> Select Node -> Press Delete Key seems to work!

That does nothing on my platform (Macbook Pro). Possibly because the `Delete` key is actually backspace?

**Comment by SaNeOr** [comment]
> > Select Node -> Press(出版社) Delete Key seems to work!
> 
> That does nothing on my platform (Macbook Pro). Possibly because the `Delete` key is actually backspace?

Sorry, I didn't realize you meant mac.


Editor -> Editor Setting -> Shortcuts -> ui_graph_delete, change binding to Backspace (or your like)
![image](https://github.com/godotengine/godot/assets/22307698/98d0ba75-f003-4759-9a1a-dca4f4f7e14a)

**Comment by wjagodfrey** [comment]
That does fix my immediate problem, but I'm leaving this bug open because I believe something like the statemachine node editor bin button is required here:
<img width="233" alt="image" src="https://github.com/godotengine/godot/assets/5732688/83d042b0-a4a2-4729-af02-daeed294fdda">

**Comment by snougo** [comment]
I got same issue when I want delete Node in AnimationTree
without delete button, makes me confused

**Comment by timothyqiu** [comment]
This is a regression. Close buttons are available in 4.1 versions.
