### ISSUE TITLE
Fail to import some .blend files (with shader composed of Principled BSDF only) from Blender (ERR_FILE_CANT_OPEN) [ArchLinux]

### ISSUE THREAD

**Issue by PaoDerDoktor** [godotengine/godot#82507]
### Godot version

4.1.1.stable.arch_linux from AUR

### System information

Godot v4.1.1.stable unknown - Arch Linux \#1 SMP PREEMPT_DYNAMIC Thu, 21 Sep 2023 11:06:39 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (nvidia) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

I'm having issued with Blender's (3.6.4) and Godot's (4.1.1.stable.arch_linux) latest versions available on ArchLinux.

Most `.blend` files "behave as expected" (they are correctly imported, can be displayed, made local, etc), but today I was modelling a cute burger *(yes it is.)* and it's `.blend` file could not be loaded into godot as I usually do it (saving the `.blend` file in a subfolder of the root of my Godot project called "Blender Meshes").

Instead, it keeps on failing to import said file (marking it with a red cross on it's icon in the resource panel) and retrying to import it.

Trying to put the result of a `.escn` created by exporting the `.blend` file with the [Escn Exporter](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/escn_exporter/index.html) plugin from Blender works as expected (though my materials are missing), same goes if I just export them as `.gltf`.

I don't have a lot of logs sadly, but the minimal recreation project I created to post the issue logs as follow :

```
Godot Engine v4.1.1.stable.arch_linux (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
  modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. 
[...]
Returning: ERR_FILE_CANT_OPEN
  Error importing 'res://Burger.blend'.
```

I'm a bit at loss as to what to do. I already tried `chmod` and other POSIX permissions-related things, but none worked. As I said, other files work perfectly well. Changing the name of the file, or even putting it directly at the root of my project, won't change anything. Same goes for deleting materials/objects from the Blender scene.

Cute burger `.blend` file included in minimal example.

### Steps to reproduce

- Be on ArchLinux
- Have Blender 3.6.4 installed
- Have Godot 4.1.1.stable.arch_linux
- Setup `Blender Path` in Godot's editor settings (`/usr/bin` in my case)
- Create a Godot project (I used Forward +)
- Build a mesh
- Save it as a `.blend` file in the created Godot project
- Go back to the Godot Window, which should show errors in the console and cross out the `.blend` file n the FileSystem panel.

### Minimal reproduction project

[BlendImportIssueMin.zip](https://github.com/godotengine/godot/files/12754361/BlendImportIssueMin.zip)

**Comment by Calinou** [comment]
Thanks for the report! COnsolidating in https://github.com/godotengine/godot/issues/80530.
