### ISSUE TITLE
Color value changes on update of alpha values in color Editor

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#82514]
### Godot version

4.2.dev.5

### System information

Windows 11

### Issue description

After entering the color value if you update the alpha value in raw section of color editor as shown in the video. the color value changes in the RGB text field.

### Steps to reproduce

https://github.com/godotengine/godot/assets/84369217/52ea6bec-b2ec-47ee-a9be-852236eeeada

Notice in the video after entering the alpha as 0.8 the color value changed from #484848 to #474747 

Apologies for tumbling in entering the value in the video as it is another issue https://github.com/godotengine/godot/issues/73926

### Minimal reproduction project

N.A

**Comment by rsubtil** [comment]
It's likely some float imprecision due to using RAW mode, as this doesn't happen on RGB/HSV modes.

**Comment by aXu-AP** [comment]
Raw tab uses 0.01 as step value for sliders, hence they have 100 different states. Other tabs' sliders have 256 states (0...255), so setting color in raw tab loses some precision, enough to be noticed as a change on other representing modes (hex, for example).

Simple way to fix this: Use 0.001 as a step value. For this to be more user friendly, spinboxes' arrow step should be set to 0.01.

I've been thinking if Ranges should allow `value` to be more precise than `step` (maybe with property `allow_precise`). Spinbox would show only stepped value, but when it gets focus, it would show precise value (kind of like spreadsheet apps do it). This would also solve this problem (and similiar problem I'm currently having in my project).

**Comment by tokengamedev** [comment]
Awesome fix !!
