### ISSUE TITLE
Attempting to rename file does nothing when file system panel lacks explicit focus.

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#82510]
### Godot version

4.1.1 stable (non-mono)

### System information

Windows 11

### Issue description

When you try to rename a file when the file system panel does not have focus (but the editor itself **does** have focus), nothing happens. You need to first click in the file system panel to explicitly grab focus before you can rename files.

### Steps to reproduce

https://github.com/godotengine/godot/assets/1424843/e1d90cbe-dfe7-47da-87bd-eaa12e67d004

### Minimal reproduction project

Just see the above video.

**Comment by YeldhamDev** [comment]
Fixed in 4.2, but still reproducible in 4.1.2 RC1.

**Comment by Sauermann** [comment]
This is a known issue and has been reported in #78789.
Closing as a duplicate accordingly.

**Comment by jonbonazza** [comment]
Sorry! I did a search and couldn't find it. Apologies for the noise. Thanks!
