### ISSUE TITLE
Elements in export variable array[Node2D] in custom resource disappears when project is reloaded

### ISSUE THREAD

**Issue by AfthenDEV** [godotengine/godot#82511]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 Threads)

### Issue description

So in Godot, i have created a custom resource. in that resource, there is an export variable. that export variable is an array[Node2D].
now, i have created a Node2D. in that node's script, there is an export variable that is expecting the custom resource that I have made. now the issue is this: when I add elements to the array in the editor, save it, then reload the project, the elements in the array disappears. just blank.

Before reloading (this is what I expect it to be):
![image](https://github.com/godotengine/godot/assets/94941720/1a3be736-2c30-4c3b-b055-72aa43890ccc)

After reloading (this is not what I expect it to be):
![image](https://github.com/godotengine/godot/assets/94941720/26a91dbd-0c6f-42ce-b486-3af26cb03144)

### Steps to reproduce

I have provided a minimal reproduction project down below:

1. Open the project.
2. Go to `res://sample_node_2d/sample_node_2d.tscn` and open it.
![image](https://github.com/godotengine/godot/assets/94941720/7a408ba0-20cd-40d0-a679-972daa694010)
3. Click on the `Sample Resource` to expand it. 
![image](https://github.com/godotengine/godot/assets/94941720/b154e835-59a4-4f78-bab2-7ad6e3fc7394)
4. Click on `Add Element` to add an element to the array.
![image](https://github.com/godotengine/godot/assets/94941720/0e9870b0-9036-4aa0-b6de-b520641cdc4c)
5. Add as many as you want and assign a `Node2D` to each one of them.
![image](https://github.com/godotengine/godot/assets/94941720/af024627-4d9d-4366-a816-00221ff5e8d8)
6. Save the project.
7. Reload the project. Go to `Project/Reload Current Project` and click it.
8. Wait for the project to reload.
9. Look at the array. This is what you might see: 
![image](https://github.com/godotengine/godot/assets/94941720/52108dbf-b933-45fa-9f6b-368d392e2bac)

### Minimal reproduction project

[minimal project reproduction.zip](https://github.com/godotengine/godot/files/12755732/minimal.project.reproduction.zip)

**Comment by SaNeOr** [comment]
You can refer to #80538

**Comment by akien-mga** [comment]
This is not a supported use case, Resources don't know about the scene tree so they can't handle Nodes properly. See #70610.
