### ISSUE TITLE
SpinBox resets to min_value or max_value when right-clicked with a disabled context menu

### ISSUE THREAD

**Issue by dreadpon** [godotengine/godot#82524]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 10 4.1-stable Forward+

### Issue description

After calling `SpinBox.set_context_menu_enabled(false)`, any right click from unfocused state to this `SpinBox` will reset its value to either `min_value` or `max_value` (what affects this choice is unclear to me).

This seems connected to https://github.com/godotengine/godot/issues/31069 and possibly https://github.com/godotengine/godot/issues/79507

### Steps to reproduce

1. Launch the scene `res://spinbox_input/spinbox_input.tscn`
2. Type a number (`1`- `99998`) in leftmost `SpinBox`
3. Select the `SpinBox`in the middle
4. Right click the leftmost `SpinBox`
5. Observe how it resets to either `0` or `99999` (its min and max values)
6. You can try the same with the middle `SpinBox` (with enabled context menu) and rightmost `LineEdit` (with disabled context menu); both will behave as expected

### Minimal reproduction project

[spinbox_reset.zip](https://github.com/godotengine/godot/files/12764948/spinbox_reset.zip)

**Comment by jackwilsdon** [comment]
This appears to be intentional, right clicking the bottom half of a `SpinBox` sets the value to minimum, right clicking the top half sets the value to maximum: https://github.com/godotengine/godot/blob/19890614c6a78ec36030ce65c7da05f07fcdb9ed/scene/gui/spin_box.cpp#L161-L164

**Comment by dreadpon** [comment]
This seems very unintuitive, not to mention undocumented
It's also a pretty drastic functionality that cannot be turned off

This dates back all the way to open sourcing of Godot, so perhaps we could review this functionality?
Perhaps it's no longer needed?
Or at the very least we could introduce a flag to disable this?

I'm sure I'm not the only one who would be weirded out by this functionality in a user-facing application

**Comment by jackwilsdon** [comment]
@dreadpon it does sound like this should be an optional setting - it's worth opening a proposal: https://github.com/godotengine/godot-proposals

**Comment by jackwilsdon** [comment]
In the meantime, you can attach the following script to a `SpinBox` to disable this functionality:

```gdscript
extends SpinBox

func _gui_input(event):
	if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_RIGHT:
		get_viewport().set_input_as_handled()
```

**Comment by jsjtxietian** [comment]
I think we should update the document to mention this for now.
