### ISSUE TITLE
Encountered issues with program crashes when modifying image file names, as well as issues with setting rollback, such as tilemap's collision area setting

### ISSUE THREAD

**Issue by wsqrin** [godotengine/godot#82520]
### Godot version

4.2 dev5 mono

### System information

win11 22H2

### Issue description

Encountered issues with program crashes when modifying image file names, as well as issues with setting rollback, such as tilemap's collision area setting

### Steps to reproduce

Nothing to preview

### Minimal reproduction project

Nothing to preview

**Comment by Mickeon** [comment]
There's not enough information on what happened or how to reproduce any of this. Please do not include multiple issues in one, and try to describe what and how it could've happened.

**Comment by dalexeev** [comment]
Please add details here or open a new issue following the template. See also [Contributors guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs). Without details, contributors cannot help you. Thanks!
