### ISSUE TITLE
Lightmap artifacts around geometry edges.

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#82526]
### Godot version

v4.2.dev.custom_build [19890614c]

### System information

Godot v4.2.dev (19890614c) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 27.20.21034.37) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

I've been poking at @DarioSamo's JNLM denoiser for the past few days and I've been noticing these strange artifacts around the edge of lightmaps not present pre-JNLM:

![image](https://github.com/godotengine/godot/assets/25323231/cbb80a74-7e66-4302-95d1-a9700a8639a1)
![image](https://github.com/godotengine/godot/assets/25323231/d2ffdb1f-1910-447e-9cb6-22bde943bc57)

I also may have identified a fix: accounting for the half-pixel offset added in 2c125bf9c0fa870c5af9a753a6b85295f01f0728 in the JNLM denoiser. I took a look at https://github.com/godotengine/godot/pull/81872 recently and tried reverting it on a guess, and the artifacts disappears completely (see below). Of course, it also unfixes the issue it solved, so reverting it isn't the right fix.

Lightmap with 2c125bf9c0fa870c5af9a753a6b85295f01f0728 reverted, for comparison:
![image](https://github.com/godotengine/godot/assets/25323231/fc2e5102-e46d-4623-aa4d-492d12c08769)
![image](https://github.com/godotengine/godot/assets/25323231/7654b4c2-8db9-456f-b13f-03d6e3f6fd33)

### Steps to reproduce

I have been unable to accurately reproduce the problem, but I've identified a (freely available) model that can trigger the issue (MRP).

1. Open MRP
2. Bake lightmap
3. Artifacts can be seen throughout the scene.

### Minimal reproduction project

[lightmap_seams.zip](https://github.com/godotengine/godot/files/12766068/lightmap_seams.zip)

**Comment by DarioSamo** [comment]
I think I noticed this and have a couple of theories as to the probable causes, but I'm surprised the half pixel offset has such an effect. Let's experiment for a bit as this should be easily traceable.

**Comment by atirut-w** [comment]
> reverting the denoiser

If push comes to shove, we can always drop an `if` into the half-pixel offset parts. Not that it's the best fix, though.

**Comment by DarioSamo** [comment]
Seems like it has to do with the fact the noisy pixels don't have a valid normal or position whatsoever, so they don't get denoised. I'm confused as to how exactly the pixel is getting lighting in the first place under those conditions but that explains it.

**Comment by DarioSamo** [comment]
It's not related to the denoiser. I turned it off and forced it to set all invalid pixels to this green color. I think the noise you're seeing is from previous bakes (will need to check if the texture is getting cleared as it should).

![image](https://github.com/godotengine/godot/assets/538504/a08fe372-4f51-467b-900d-99495234f74f)

**Comment by atirut-w** [comment]
> I think the noise you're seeing is from previous bakes (will need to check if the texture is getting cleared as it should).

I nuked the light data (`*.lmbake` and `*.exr`) before baking. No joy.

**Comment by DarioSamo** [comment]
Okay I think I figured it out.

The invalid data came from the dilate step. I'm not sure how it landed there, but there's a dilate step before the denoising, which means it just expands a bunch of noise.

The dilate is required for the seams at the edges of the UV2.

Can you test the commit in this branch and see if it fixes the problem? It did at least for me.

https://github.com/DarioSamo/godot/tree/no-dilate-before-denoise

**Comment by atirut-w** [comment]
It seem to have fixed the issue for me, too
