### ISSUE TITLE
RigidBody interpolation

### ISSUE THREAD

**Issue by Smellyhobo101** [godotengine/godot#8253]
Like in Unity:

https://docs.unity3d.com/ScriptReference/Rigidbody-interpolation.html
https://docs.unity3d.com/ScriptReference/Rigidbody2D-interpolation.html

My game looks so much smoother if I change the physics framerate to 144fps, but that's a bit overkill considering most people don't have 144hz monitors. Rigidbody interpolation would be a nice alternative.

**Comment by bojidar-bg** [comment]
Note: fixed frame interpolation was discussed in https://github.com/godotengine/godot/issues/2043#issuecomment-115000788

**Comment by kubecz3k** [comment]
Closing as a duplicate of https://github.com/godotengine/godot/issues/10388
