### ISSUE TITLE
Ideas for future

### ISSUE THREAD

**Issue by berserk82** [godotengine/godot#8254]
I reopen this issue because I was told some of these features are planned for 3.1, but no one told me which.
So, here's the original issue:

issue start
Please, add some AI facility such as: neural networks, behaviour trees. These should not be full implementations, but allow these to be implemented in scripting with ease.
Also, I don't know if terrains are still used today, but it would be cool to see them in.
Finally, physics should be enhanced with fluids and soft bodies.

Please, share your toughts.
issue end

Please, tell me what is planned for 3.1 from these.

Thanks in advance.

Bye, Ivano.

**Comment by akien-mga** [comment]
Sorry, that's not how this issue tracker works. We use issues to document specific bugs that can be fixed, or specific (singled out) feature proposals that could be implemented. Broad issues like this one are very difficult to work with.

If you want to discuss the roadmap, hop on the IRC channel. If you want specific features to be implemented, first make sure that they would be relevant (reading [this FAQ entry](http://docs.godotengine.org/en/latest/about/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think) is a good starting point) and then open an issue for each such feature.

**Comment by akien-mga** [comment]
BTW you were told exactly the same in #8124. Please take it into account next time.

**Comment by berserk82** [comment]
No, I were told some of these are going to be implemented, but not which.

**Comment by akien-mga** [comment]
Physics are going to be improved for 3.1, terrains will be implemented one day. For the rest I don't know of any plans.

**Comment by berserk82** [comment]
Thanks
