### ISSUE TITLE
OpenGL Version Error

### ISSUE THREAD

**Issue by Lufims** [godotengine/godot#82556]
### Godot version

Idk, I'm trying to play Yomi Hustle

### System information

Windows 10, Supports OpenGL 1.1 (Because of incompatible drivers (But i'm using microsoft basic driver to make my pc run directx 12 (even if it runs just dx 9) and using the MESA GL to make it run OpenGL 2.1 (and 4.1 if i need) using the directx 12), Intel Pentium III 2.6 GHz, 4Gb of RAM

### Issue description

Basically, It Should work, becuase my pc even if it doesn't run opengl 2.1 or 4.1, just opengl 1.1, i'm using MESA GL to "emulate" these versions of opengl using directx 12, yes, the processor do all the job of rendering, but, it should at least open the game, I don't know if it's that way, but, probably the engine is trying to see if the pc can run a version of opengl (like 4.1, idk), and not testing if it runs, but, I could be wrong, becuause i just don't know. Probably i'm not using the correct version of opengl.

### Steps to reproduce

use an intel Pentium III without a graphic card and 4Gb of RAM with windows 10, and use MESA GL to "Emulate" the necessary version of opengl to run the game.

### Minimal reproduction project

hmmmm, I can't i think

**Comment by Lufims** [comment]
Nevermind, I was "Emulating" OpenGL 3.1 not 3.3, it worked now.

**Comment by FeralBytes** [comment]
Since you resolved this,  please close your issue.
