### ISSUE TITLE
SpotLight3D Compatibility Web Engine Crash

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#82565]
### Godot version

4.1.1.stable

### System information

Linux Mint 21.2; Kernel: 5.15.0-84; CPU: AMD Ryzen 9 3900X; GPU: AMD 5700XT, Compatability, Firefox 118.0

### Issue description

Adding a SpotLight3D to a scene and running it in compatibility mode works fine. But if you try to run the same scene in the web it will crash the engine. Tested in Firefox and Chromium.

### Steps to reproduce

Run the attached project in a web browser and observe the crash.

### Minimal reproduction project

[SpotLight3D-WebLightTest.zip](https://github.com/godotengine/godot/files/12773330/SpotLight3D-WebLightTest.zip)

**Comment by FeralBytes** [comment]
Spot Light Crash Log from Firefox: 
[SpotLightCrashFirefox.txt](https://github.com/godotengine/godot/files/12773383/SpotLightCrashFirefox.txt)

**Comment by FeralBytes** [comment]
Further digging and I see some commonality with this issue here: #75913 
So I noticed that the users there are using Linux and have AMD GPUs as I do. 
So then I ran it on my other machine which is the same version of Linux but has a Nvidia GPU and even running it in Firefox on the machine with the lights turned on, it does not crash. This is an issue specific to AMD GPUs on Linux well running in the browser. I hope this helps to narrow it down.
Not that this adds much but I also ran a SpotLight3D scene on Android in Chrome browser without issue.

**Comment by akien-mga** [comment]
Please test latest 4.2 dev snapshots, this might be fixed by https://github.com/godotengine/godot/pull/80909 already.

**Comment by FeralBytes** [comment]
@akien-mga Tested 4.2.0-dev5 and the game plays fine without a crash. Also tested 4.1.2-rc1 and the game plays fine without a crash. I see that both have that merge from the interactive change-log. Thank you all for immediately having a fix ready. That was unexpected and awesome!
