### ISSUE TITLE
OmniLight3D Compatability Web Crashes Engine

### ISSUE THREAD

**Issue by FeralBytes** [godotengine/godot#82564]
### Godot version

4.1.1.stable

### System information

Linux Mint 21.2; Kernel: 5.15.0-84; CPU: AMD Ryzen 9 3900X; GPU: AMD 5700XT, Compatability, Firefox 118.0

### Issue description

Adding a OmniLight3D to a scene in compatibility mode runs fine when run natively. However running the scene in a web browser results in a Engine Crash. Tested with both Firefox and Chromium.

### Steps to reproduce

Run the Attached example in Web Browser.

### Minimal reproduction project

[OmniLight3D-WebLightTest.zip](https://github.com/godotengine/godot/files/12773309/OmniLight3D-WebLightTest.zip)

**Comment by FeralBytes** [comment]
[OmniLightCrashFirefox.txt](https://github.com/godotengine/godot/files/12773373/OmniLightCrashFirefox.txt)
Crash Log From Firefox for OmniLight3D.

**Comment by bitsawer** [comment]
Probably fixed by https://github.com/godotengine/godot/pull/80909, can you try latest Godot 4.1.2 stable where this might be fixed?

**Comment by FeralBytes** [comment]
@bitsawer Tested 4.2.0-dev5 and the game plays fine without a crash. Also tested 4.1.2-rc1 and the game plays fine without a crash. I see that both have that merge from the interactive change-log. Thank you all for immediately having a fix ready. That was unexpected and awesome!
