### ISSUE TITLE
Using viewport as render target and setting it as a texture leads to corrupt tscn file

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8258]
**Operating system or device - Godot version:**
Godot 2.1 branch

**Issue description:**
I'm using a render target as a diffuse texture for a fixed material assigned in GDScript. Once the scene gets saved with this setup a sub_resource rendertargettexture entry gets added to the tscn but it is empty. After this the tscn file won't load until your remove the entry.

**Steps to reproduce:**
1) create a new scene
2) add some stuff so you have something to render
3) add a viewport and set it as a render target
4) add a camera for the viewport
5) create a quad in your scene, create a new fixed material for it
6) add a script to your scene, add tool at the start so code gets run and add the following line of code to _ready():
get_node("Quad").get_material_override().set_texture(FixedMaterial.PARAM_DIFFUSE, get_node("Viewport").get_render_target_texture())
7) reload the scene so the render targets output texture gets set to our quads material. The quad should now show a result.

Once the scene gets saved in this new state you end up with a broken tscn. I'm guessing the problem is that the rendertargettexture isn't setup and not linked to the viewport. Possibly I'm forgetting a step to make this work correctly..

**Comment by bojidar-bg** [comment]
@BastiaanOlij Sure it isn't 3.0/master branch?

**Comment by BastiaanOlij** [comment]
@bojidar-bg yeah pretty sure but I'll try on 2.1.3 tonight just to see if its something that just snuck in recently.

Note that what I'm doing is a bit odd. I haven't found a way to link the output of the viewport as a texture for a fixed material in the interface hence adding the code. Normally you'd run that in runtime, not as a tool in the editor, I'm just doing that because I'm working on showing some techniques in the editor for a video I'm working on. I'm guessing it introduces something into the tree in the background that the code that saves the scene to disk isn't expecting.

I might try a shader material to see if I can work around it that way, I need to get some experience with those anyway:)

**Comment by BastiaanOlij** [comment]
Was able to reproduce this on 2.1.3

This is the project I'm playing around with. Unzip it, make a copy of mono.tscn so you can compare the difference. Open the project in the editor, move something, save the scene.
You won't be able to open it again.
https://www.dropbox.com/s/spbuvyycka79j8k/DemoCamera.zip?dl=0

**Comment by RandomShaper** [comment]
I remember I hit that issue when I was playing with the 3D stuff some time ago.

An error message was printed in the console. Could you post it here?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
