### ISSUE TITLE
ShapeCast creating MeshInstances when "Visible Collision Shapes" is checked

### ISSUE THREAD

**Issue by orangebongo** [godotengine/godot#82586]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Reporting as a bug since it's a similar issue to https://github.com/godotengine/godot/issues/48085 which was resolved by https://github.com/godotengine/godot/pull/48175#pullrequestreview-645745811

![image](https://github.com/godotengine/godot/assets/95245710/d2060076-b426-480f-866a-de8b8b9dcd6c)

ShapeCasts (and other collision related nodes) creating MeshInstances risks them getting picked up through calls to "get_children", which can interfere with game logic. In my case, it's only causing visual issues as I am moving all children to a specific location similar but not exactly like a SpringArm, which now happens to include the debug mesh. This caused some confusion as I was wondering why my shapecast was not where it should be and negated the usefulness of the visible debug shapes.

As I understood it from the previously mentioned resolution all debug shapes should preferably be handled directly by the rendering server going forward, so I figured I'd raise this as a possible minor oversight.

Alternative solution would be to mark debug nodes somehow to make them distinguishable through code, such as using the meta field, but that feels like it introduces unnecessary logic on the part of the game that would likely end up in production.

### Steps to reproduce

Create a scene with a shapecast with any shape. Run the game and look through the Remote tree, a generated MeshInstance will be there.

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
While not directly a bug using a child MeshInstance node for debug is very old-school Godot and should be reworked to use the RenderingServer directly instead.
