### ISSUE TITLE
When setting Region, the bitmap and margin markings are often positioned incorrectly

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#82583]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When redefining a region for a bitmap used in Atlas texture, the margin marker lines, the bitmap and the region are all misaligned, so it looks like this:
![image](https://github.com/godotengine/godot/assets/106015575/9f0edca5-ba0b-440b-a010-613be33d3bf0)

### Steps to reproduce
Open any node that uses an atlas as resource and try to change the region.
Try to adjust it in any way and the bitmap will shift on it's own.

Here is a video showing the bug in action:
https://archive.org/download/ShowFlowFleetingWorld/godot%20region%20offset.mp4

### Minimal reproduction project

N/A

**Comment by inhalt120g** [comment]
After using build
v4.2.1.stable.official [b09f793f5]
Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)
for a few months: just to confirm this is not happening anymore, meaning I haven't seen it even once (in the old build it was happening every time I tried to align the marks).

**Comment by akien-mga** [comment]
Thanks for updating the issue!
