### ISSUE TITLE
Default Node GDScript Template has Warnings/Errors with new Untyped Declaration Warning

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#82587]
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.2.dev5 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When creating a new GDScript with the default Node template, untyped declarations are used:
```
extends Node3D


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```
I believe this is a bug because a template that has untyped declarations will cause warnings or errors if the new "[Untyped Declaration](https://github.com/godotengine/godot/pull/81355)" warning is enabled in the project settings. Additionally, the [default template described in the documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template) uses typed declarations and does not match the default template currently used by the editor.

### Steps to reproduce

1. Ensure that no [Editor-defined templates](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#editor-defined-templates) exist
2. Create a new project
3. Under Project Settings (Advanced Settings) -> Debug -> GDScript -> Untyped Declaration: Set to `Warn` or `Error`
4. Create a new GDScript through the FileSystem panel or by choosing Attach Script on a new scene's root node
5. Note that the new GDScript uses untyped declarations and does not match the [documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template)

![image](https://github.com/godotengine/godot/assets/17506573/572934f2-8962-48b1-9190-aca1ed3f0a3a)
![image](https://github.com/godotengine/godot/assets/17506573/11f99277-7625-4cd9-91a9-0e07cecbfbf8)

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
Make sure the `text_editor/completion/add_type_hints` editor setting is enabled:

![](https://github.com/godotengine/godot/assets/47700418/2fe219a0-ee9f-44e2-9b4c-fb65faa1d85c)

**Comment by Maran23** [comment]
> Make sure the `text_editor/completion/add_type_hints` editor setting is enabled:

Maybe it makes sense to have this enabled by default now?

**Comment by dalexeev** [comment]
> Maybe it makes sense to have this enabled by default now?

Note that the `UNTYPED_DECLARATION`, `INFERRED_DECLARATION`, and `UNSAFE_*` warnings are **disabled** by default. We assume that if users want static typing, they will enable the desired settings themselves. The documentation and demo projects also use untyped GDScript by default, although there is a [suggestion](https://github.com/godotengine/godot-demo-projects/issues/868) to use static typing in demo projects.

**Comment by allenwp** [comment]
> Make sure the `text_editor/completion/add_type_hints` editor setting is enabled:

Confirmed that setting "Add Type Hints" to `On` changes the default template to use typed declarations.

But I think there is still a usability issue that exists here... When a project has the new Untyped Declaration set to `Warn` or `Error` it is not obvious to the user that they need to change additional editor settings to play nice with this project setting.

I found out about the Untyped Declaration warning when searching for a way to disable dynamic typing in GDScript, but I had no idea that I might need to make additional editor settings changes to make the script editor play nicely with my new project settings.

Additionally, if a project is shared between multiple developers, all developers may not intuitively understand that they need to adjust their editor settings to play nice with the project settings.

I think it would be good to brainstorm a way to make this a bit more intuitive to new users, either in this issue thread or maybe  in a new proposal...

**Comment by allenwp** [comment]
Here are a couple of options that could address the usability issue relating to Untyped Declaration warnings/errors and Add Type Hints:

1. Type Hints are always `on` when Untyped Declaration is set to `warn` or `error` in the current project. The "Add Type Hints" editor setting is ignored and has a note saying that the setting is only respected when Untyped Declaration is set to `ignore` in the current project settings.
2. Type hints default is changed to `on`. (This sounds like a bad idea because it conflicts with the default dynamic typing behaviour of Godot.)
3. The default Node GDScript template is updated to always use type declaration, similar to how it is [currently shown in the documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template).
4. The Untyped Declaration documentation/tooltip is updated to say something like "When setting this to Warn or Error, consider changing the Add Type Hints setting to On in the Editor Settings".

Unless option 3 is implemented, the documentation should be updated to match the default Godot behaviour.

I think, at the very least, option 4 should be implemented. Maybe even before 4.2 launches as stable. This way when the new Untyped Declaration project setting is officially launched, users will know how best to configure their Editor Settings when using it.

**Comment by allenwp** [comment]
Regarding the [default template described in the documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#default-template), I've made a separate docs [issue](https://github.com/godotengine/godot-docs/issues/8151) and [PR](https://github.com/godotengine/godot-docs/pull/8152).

**Comment by allenwp** [comment]
It looks like the original issue was that I didn't read the [final section](https://docs.godotengine.org/en/latest/tutorials/scripting/creating_script_templates.html#type-placeholders) on the page that describes how type hints will be removed if the Add Type Hints editor settings is turned off.

**Comment by allenwp** [comment]
Whoops, accidentally commented on the wrong issue.
