### ISSUE TITLE
Building Web export templates for 3.5.3 on Windows fails parsing emcc version

### ISSUE THREAD

**Issue by AnnA-Ayms** [godotengine/godot#82585]
### Godot version

3.5.3

### System information

Windows 10

### Issue description

Can't build a web template (at least under Windows 10) with the current 3.5.3 build as is (necessary if Compiling project with PCK encryption key).
relates to changes after https://github.com/godotengine/godot/pull/81340

Commenting out line 189 "cc_semver = tuple(get_compiler_version(env))" of \godot-3.5\platform\javascript "detect.py"
and I was able to compile the template since neither
"if env["use_thinlto"] or env["use_lto"]:" nor "if env["gdnative_enabled"]:"
apply to my use but investigation by someone more competent on these matters than me would be good.

results before the comment out
Z:\godot-3.5>scons platform=javascript tools=no target=release
scons: Reading SConscript files ...
Auto-detected 4 CPU cores available for build parallelism. Using 4 cores by default. You can override it with the -j argument.
Couldn't parse CXX environment variable to infer compiler version.
TypeError: 'NoneType' object is not iterable:
  File "Z:\godot-3.5\SConstruct", line 449:
    detect.configure(env)
  File "Z:\godot-3.5\./platform/javascript\detect.py", line 189:
    cc_semver = tuple(get_compiler_version(env))

### Steps to reproduce

Just trying to build a Web Export Templates for version 3.5.3 under Windows 10 caused it.
"scons platform=javascript tools=no target=release"

### Minimal reproduction project

N/A

**Comment by eggnot** [comment]
Same error for me.
Win10, Visual Studio 2022, emsdk 3.1.46

**Comment by yikescloud** [comment]
Same issue here, Vscode 2022, emsdk 3.1.14

**Comment by akien-mga** [comment]
Fixed by #87739.
