### ISSUE TITLE
Exporting for macOS from Windows fails

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#82594]
### Godot version

v4.2.dev.custom_build [4c3dc2636]

### System information

Godot v4.2.dev (4c3dc2636) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21023.2010) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

Trying to use my compiled macOS export templates fails with the following error.
```
  CodeSign/CodeResources: Unsigned nested executable file.
  CodeSign: Failed to process nested resources.
  editor/export/editor_export_platform.h:179 - Code Signing: Built-in CodeSign failed with error "Failed to process nested resources.".
```
I am not sure if this is an engine bug, or something is failing with the templates I compiled on my macOS machine. 

### Steps to reproduce

1. Start a new project (and add anything to the scene and save it)
2. Go to Project > Export
3. Add the macOS template and fill the required fields.
4. Use the built-in ad-hoc signature
5. Wait for it to export until it fails.

### Minimal reproduction project

[3D Rotating Cube.zip](https://github.com/godotengine/godot/files/12775599/3D.Rotating.Cube.zip)

**Comment by MBCX** [comment]
OK, after downloading and testing 4.2.dev5.official, I can confirm that it's a problem on my end. I wonder what it might be.

**Comment by MBCX** [comment]
So, after some more investigation, it appears to be more of an engine bug. I re-compiled the templates and even sign them with my own certificate because I though that would fix it. But that was not the case:
![macOS export error](https://github.com/godotengine/godot/assets/63003002/13c7c37e-5347-4244-93f9-802d90e3404e)

Exporting without using the built-in ad-hoc works though.

**Comment by bruvzg** [comment]
I can't reproduce it.

Looking at your MRP it seems like you are exporting it into the subfolder of the project, you should never do it, since it might be picking up some of the files from the previous export as resources (this is true for exporting to all platforms and might cause problems). Try exporting to the empty folder outside the project tree.

**Comment by MBCX** [comment]
All right, so after many, many misadventures, I **finally** fixed it!

I had to create a self-signed certificate (using the Keychain Access app and specifying the type of Code Sign), and then with the following command, I signed the entire .app file before zipping it:
```bash
codesign --deep --force --timestamp --options=runtime --sign "godottemplates" macos_template.app
```
This **somehow** fixed it. I will keep it open just in case!

**Comment by MBCX** [comment]
All right, so after many, many misadventures, I **finally** fixed it!

I had to create a self-signed certificate (using the Keychain Access app and specifying the type of Code Sign), and then with the following command, I signed the entire .app file before zipping it:
```bash
codesign --deep --force --timestamp --options=runtime --sign "godottemplates" macos_template.app
```
This **somehow** fixed it! I will keep this issue open just in case.
