### ISSUE TITLE
Cant add a cell on the same position as an erased scene tile

### ISSUE THREAD

**Issue by TheKassaK** [godotengine/godot#82597]
### Godot version

4.2 dev 4

### System information

Godot v4.2.dev4.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 Super (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 Threads)

### Issue description

It is the continuation of #80658 

Now we when use EraseCell() on a scene tile, the instance is removed and the tile disappears BUT after that, if we add a "classic tile" on the same position, we erase this tile and we try to set the scene tile again on the same position, nothing happens.

If I modify the tileset, like **TileSet.TileShape = TileSet.TileShapeEnum.Square**, it works, the tile I add is displayed well, but it is not a solution because it refresh everything and all my scene tiles instances are recreated

### Steps to reproduce

- use SetCell() to put a scene tile on runtime
- use EraseCell() to delete that scene tile on runtime
- use SetCell() to put a classic tile at the same position
- use EraseCell() to delete that classic tile on runtime
- use SetCell() to put a scene tile on runtime at the same position **=> nothing happens**

So if you open the linked project, its : 

- Left Click
- Right Click
- Space
- Right click
- Left Click **=> nothing happens**

### Minimal reproduction project

[Scene.Collection.issue.zip](https://github.com/godotengine/godot/files/12775652/Scene.Collection.issue.zip)

**Comment by KoBeWi** [comment]
> 4.2 dev 4

Tested in dev5 and it's fixed. Try updating the engine.
