### ISSUE TITLE
TextureRect Stretching Breaks With SubViewport

### ISSUE THREAD

**Issue by duane-r** [godotengine/godot#82606]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Gentoo 2.14 - Vulkan (Compatibility) - AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.49, 6.1.53-gentoo-r1-x86_64) () - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

When I create a TextureRect background that repeats a smaller texture, then place a SubViewportContainer and Subviewport, the TextureRect glitches.

![bug](https://github.com/godotengine/godot/assets/14078065/143072c2-2814-48e1-b50d-61c89ae1169a)

### Steps to reproduce

1) Add a TextureRect with stretch_tile and expand_keep_size.
2) Add a SubViewportContainer and SubViewport.

However, this may be an issue with compatibility mode or my specific settings, so please run the attached project. Uncomment the lines at the bottom of game.gd for my work-around.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/12775994/bug.zip)

**Comment by duane-r** [comment]
I've tried all the different texture_repeat settings. They had no effect. However, if I preload the texture instead of loading, it works fine.

**Comment by KoBeWi** [comment]
Looks correctly for me.
![image](https://github.com/godotengine/godot/assets/2223172/1b5e709f-64e7-4de1-8c12-28767b489abd)
Try in 4.2 dev. Might be broken in older version.

**Comment by duane-r** [comment]
Looks like it's fixed. Thanks.
