### ISSUE TITLE
[4.2-rc5] Regression - AnimationNodeStateMachine Editor node text invisible

### ISSUE THREAD

**Issue by wjagodfrey** [godotengine/godot#82600]
### Godot version

4.2-rc5

### System information

MacOS 12.3

### Issue description

On upgrading from `4.1.1` to `4.2-rc5` I found that I can no longer see the text on `AnimationNodeStateMachine` editor nodes:

<img width="1000" alt="image" src="https://github.com/godotengine/godot/assets/5732688/e33895fd-e59c-469a-aa53-bf7a2b4b789d">

Because the text is black.

Compared to `AnimationNodeBlendTree` editor nodes:
<img width="997" alt="image" src="https://github.com/godotengine/godot/assets/5732688/a47da178-503a-42c3-a0f0-ffc035fbc56b">

Where the text is white.

### Steps to reproduce

1. Create an AnimationTree
2. Create a `AnimationNodeStateMachine` as `tree_root`
3. Observe that the `Start` and `End` nodes are hard or impossible to read when using a dark theme
4. Add additional nodes to confirm that they are also affected

### Minimal reproduction project

I don't think an MRP is necessary.

**Comment by bitsawer** [comment]
Thanks for the report. Looks like a duplicte of https://github.com/godotengine/godot/issues/81966. This has been fixed in master by https://github.com/godotengine/godot/pull/82210, so closing as solved.
