### ISSUE TITLE
3D Editor do not display details like shapes and icons of instanced scenes

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8261]
**Ubuntu 16.10 - Godot version: 2.1.2**

**Issue description:**
Unlike 2D, 3D editor hides details of icons and shapes of instanced scenes.
For some nodes, like Area nodes used as triggers or nodes for sound effects, the possibility to see the shapes/icons will be really useful on level design.

I don't know if this could be solved by an editor option or an option in the dropdown menu on instanced scenes (and could be used for 2D too). 

**Steps to reproduce:**
 - Instance a 3D scene with icons and/or shapes on another 3D scene.
 - The shapes/icons are not visible in the editor.

**Link to minimal example project:**
Platformer 3D demo scenes like the coins are a good example of this issue.

ps: It is possible to make everything visible turning on editable children, changing current scene and going back, but I don't know if that is a bug.

**Comment by kubecz3k** [comment]
still valid

**Comment by JFonS** [comment]
Closing as it should be fixed in 3.1
