### ISSUE TITLE
Naming inconsistency in METHOD_FLAGS_DEFAULT

### ISSUE THREAD

**Issue by PadraigK** [godotengine/godot#82612]
### Godot version

Exists in master branch @ 0ca8542

### System information

N/A

### Issue description

These's a tiny inconsistency in the naming of the default case in the [MethodFlags](https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/core/object/object.h#L217) enum. This is causing some weirdness in a downstream code generator. 

We can just special-case it in our generator, but if you would take a PR to change it I am happy to submit one. Please let me know if this would be welcome.

### Steps to reproduce

Look at https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/core/object/object.h#L217

Observe that `METHOD_FLAGS_DEFAULT` is the only case using plural `METHOD_FLAGS` instead of singular `METHOD_FLAG`

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
`METHOD_FLAGS_DEFAULT` is supposed to use multiple flags, but coincidentally it defaults to NORMAL only.
Also renaming it would break compatibility, so it's not like it can be fixed now.

**Comment by Zireael07** [comment]
> Also renaming it would break compatibility, so it's not like it can be fixed now.

Quoting for visibility, as this is the most important part.

**Comment by PadraigK** [comment]
Got it, thanks for the quick response!
