### ISSUE TITLE
When material Distance Fade is set to PixelAlpha, object will render over editor icons/gizmos

### ISSUE THREAD

**Issue by notPelf** [godotengine/godot#82610]
### Godot version

Godot Engine v4.1.1.stable.mono.official.bd6af8e0e

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.2824) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I have a ground plane that I want to fade away in the distance. I have the material set to use Distance Fade to achieve this effect, however it causes the ground plane to render over top of the editor icons/gizmos/grid. This behavior occurs when Min Distance > Max Distance and also when Max Distance > Min Distance.

Mode = PixelAlpha (particles icon & raycast gizmo not drawing over plane as expected)
![pixelalpha](https://github.com/godotengine/godot/assets/4753958/3cb8b820-2475-4ef7-ad74-cf8b3c4de13c)

Mode = PixelDither (expected behavior where icons/gizmos draw over top of plane with Distance Fade material)
![pixeldither](https://github.com/godotengine/godot/assets/4753958/3dd4cddf-d152-4717-98e4-8a52143f8494)

### Steps to reproduce

1. Create new 3D scene
2. Add a MeshInstance3D, set mesh to new PlaneMesh
3. Add a CPUParticles3D (or any other Node which will have a gizmo/icon shown in the editor... a raycast 3d also works)
4. Move the CPUParticles3D upward (e.g. y=0.2)
5. Select the MeshInstance3D > Surface Material Override > New StandardMaterial3D
6. Change albedo to some dark color to make it easier to see what's happening
7. Set Distance Fade to PixelAlpha, Min Distance to 4, Max Distance to 3

Zoom the camera in and out to see how the plane is rendering over top of the CPUParticles3D icon even though the CPUParticles3D is higher up. Now change the Distance Fade mode to PixelDither and observe the intended rendering order.

### Minimal reproduction project

[DistanceFadeBugMinRepo.zip](https://github.com/godotengine/godot/files/12776063/DistanceFadeBugMinRepo.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/47606, as this is due to the same cause.
