### ISSUE TITLE
Assets library rendering got broken

### ISSUE THREAD

**Issue by germangp088** [godotengine/godot#82623]
### Godot version

4.1.1 stable oficial

### System information

Windows 11 - 4.1.1 stable oficial

### Issue description

When I navigate to the second page of assets library the rendering got broken getting the IDE width larger than my notebook screen.
Display resolution: 2560 x 1440.
<img width="1280" alt="image" src="https://github.com/godotengine/godot/assets/6310953/c7a1a96b-b4ae-4fe0-bd0b-e9224b73eaaf">

### Steps to reproduce

1 - Open assets library
2 - Select page 2
3 - The IDE doesn't adapt to the screen size.

### Minimal reproduction project

It doesn't apply, the issue occurs on any project

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80507.
