### ISSUE TITLE
The Asset Library Editor is incorrectly laid out.

### ISSUE THREAD

**Issue by gay-chicken** [godotengine/godot#82626]
### Godot version

v4.0.4.stable.official [fc0b241c9],  v4.1.stable.official [970459615],  v4.1.1.stable.official [bd6af8e0e],  v4.2.dev.custom_build[0ca8542329888e8dccba89d59d3b728090c29991]

### System information

Godot v4.2.dev unknown - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 27.20.11044.7) - AMD Ryzen 5 4500U with Radeon Graphics (6 Threads)

### Issue description

There is a slight problem with the layout of the Asset Library interface, which does not adapt to the width of the window for layout.
When I widen the window to a certain point, the layout of the interface suddenly changes to try to adapt to my current window width. When I narrow the window, the layout of the interface does not change.

**This is the normal editor.**
![4](https://github.com/godotengine/godot/assets/68856897/82d819c2-820d-4486-ba11-f4f34f0d921d)

**This is the editor where the error occurred.**
![3](https://github.com/godotengine/godot/assets/68856897/7fd542c8-16d4-406f-9a6b-80cc598b55d6)

### Steps to reproduce

1. Open Godot and go to the Asset Library screen.
2. Click on "Support", Tick "community" or "testing".
![1](https://github.com/godotengine/godot/assets/68856897/ece6aaa5-fa6b-4df5-9de4-1c9d080c6a3d)
3. Resizing the window
![2](https://github.com/godotengine/godot/assets/68856897/b7fefffb-91f3-4610-9d0a-622b72df7d1b)

### Minimal reproduction project

N/A

**Comment by gay-chicken** [comment]
I found an issue with a similar error to mine, but in a different place, and I wasn't quite sure if this issue was consistent with me, so I reopened it.

**Comment by gay-chicken** [comment]
I found an issue with a similar error to mine, but in a different place, and I wasn't quite sure if this issue was consistent with me, so I reopened it.[https://github.com/godotengine/godot/issues/82623#issue-1920797328](Assets library rendering got broken)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80507.
