### ISSUE TITLE
Hollow square svg displayed as filled in Godot 4

### ISSUE THREAD

**Issue by AsperTheDog** [godotengine/godot#82628]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

When importing the provided simple hollow square svg file made inAdobe Illustrator, Godot will interpret it as filled incorrectly.

### Steps to reproduce

1. Open sample project
2. See how square.svg file shows as filled up completely in black
3. Open square.svg file in external program
4. See that it is actually hollow

### Minimal reproduction project

[MRP - wrong svg.zip](https://github.com/godotengine/godot/files/12777689/MRP.-.wrong.svg.zip)

**Comment by Calinou** [comment]
Please check if the issue occurs when using https://thorvg.github.io/thorvg.viewer/ and report the issue to ThorVG developers accordingly.

**Comment by AsperTheDog** [comment]
@Calinou It does. I will report it there then!
Thanks for the quick answer
