### ISSUE TITLE
Project won't open AnimationFiles (errors: invalid AnimationLibraryFile)

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot#82625]
### Godot version

Godot v4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Project started rejecting FBX Animation files...

Was working fine for converting Synty assets, then suddenly stopped importing animations.

I only included one animation to keep the sample small, but it doesn't matter what animation file you use, it rejects all animation files as invalid, including files verified to load and operate in other projects.

For this specific project, not a big deal, but if this happened to a project well underway, this could be a big problem.

![animationerror](https://github.com/godotengine/godot/assets/79280460/e75e7441-687f-4805-a14c-42fec57309c4)

### Steps to reproduce

Within the attached project:

1. in the scene hierarchy, select AnimationPlayer
2. Click the Animation Button in the Animation Frame
3. Select Manage Animations...
4. Load Library button
5. Choose walking.fbx, or any other animation fbx file.
6. See Error popup window.

### Minimal reproduction project

[Synty Assets.zip](https://github.com/godotengine/godot/files/12777609/Synty.Assets.zip)

**Comment by scotmcp** [comment]
This ended up being a procedural error on my part....closing the bug.

**Comment by Calinou** [comment]
> This ended up being a procedural error on my part....closing the bug.

Could you describe the error in detail? This may be useful for people stumbling upon this issue from a web search :slightly_smiling_face:

**Comment by scotmcp** [comment]
Yes, I forgot to import the FBX file as a library before trying to attach it to the anim player.

Image here:
![Untitled](https://github.com/godotengine/godot/assets/79280460/5fecb049-62ad-4469-a20a-bd2aaefd5241)
