### ISSUE TITLE
Remote Debugger does not work on Oculus Quest headsets

### ISSUE THREAD

**Issue by dominiccooney** [godotengine/godot#82630]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU () - 13th Gen Intel(R) Core(TM) i9-13980HX (32 Threads)

### Issue description

[Related Discord thread.](https://discord.com/channels/212250894228652034/418572953912082432/1158025140051923044)

Various users reported on 4.1.1 and  4.2dev5 that the debugger fails to connect when Remote Debugging Oculus Quest 2 and Quest Pro.

Godot logs contain:

```
0 param: --remote-debug
1 param: tcp://localhost:6007
...
--- Device API >= 21; debugging over USB ---
--- DEVICE API >= 21; DEBUGGING OVER USB ---

6007

Reverse result: 0
Starting: Intent { act=android.intent.action.MAIN cmp=org.godotengine.helloxr/com.godot.game.GodotApp }
```

Running the target with `--verbose`, logcat contains: `I godot   : Remote Debugger: Connected!` but when hitting breakpoints, logs `E godot   : USER ERROR: Script Debugger failed to connect, but being used anyway.`

There's a reverse tunnel on the device, ie `adb reverse --list` prints `UsbFfs tcp:6007 tcp:6007`.

### Steps to reproduce

1. [Set up XR prerequisites an XR scene](https://docs.godotengine.org/en/4.1/tutorials/xr/setting_up_xr.html#prerequisites-for-xr-in-godot-4)
2. [Set up Oculus Quest exporters](https://docs.godotengine.org/en/4.1/tutorials/xr/deploying_to_android.html)
3. Set a breakpoint at startup.
4. Attach a headset, deploy with Remote Debugging.

Expect the breakpoint to be hit. The breakpoint is not hit.

### Minimal reproduction project

N/A

**Comment by dominiccooney** [comment]
Update: After restarting Windows, Godot, and reconnecting the headset, making some changes to the project and re-exporting debugging is now working, scene changes are reflected immediately, breakpoints hit, etc.

I suspect there's a race condition with setting up the debugger and when the deployment happens quickly, something goes wrong with attaching the debugger.

**Comment by decacis** [comment]
In my case, this is an issue in 4.2 but not in 4.1 or 4.1.1

**Comment by decacis** [comment]
I believe this was the same issue as #82764 so it can be closed.
