### ISSUE TITLE
Text in Non-embedded subwindow breaks when main window is resized in canvas-items stretch mode

### ISSUE THREAD

**Issue by AsperTheDog** [godotengine/godot#82632]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

Given a project with one or more subwindows that are **not embedded** and where the stretch mode of the window is set to **canvas-items** any text inside any subwindow will break and show as white squares until updated again when the **main window** is resized.

![fontCorrupt](https://github.com/godotengine/godot/assets/45227294/72a9d28b-4d3e-4cd9-b3cc-822f69693133)

### What I expect:
The text should not break 

### Steps to reproduce

1. Open sample project
2. Run main scene
3. See that text in subwindow is readable and showing correctly
4. Resize main window in any way
5. See that text in subwindow is now just a bunch of white squares

### Minimal reproduction project

[MultiWindow Font.zip](https://github.com/godotengine/godot/files/12777771/MultiWindow.Font.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/76450, as this is due to the same cause.
