### ISSUE TITLE
Extremely Poor Framerate/Performance in a Simple Template Project

### ISSUE THREAD

**Issue by DoubleBrackets** [godotengine/godot#82644]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.3222) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 Threads)

### Issue description

I downloaded the [Kenney 3D Platformer Template ](https://github.com/KenneyNL/Starter-Kit-3D-Platformer) to start learning Godot, but noticed that the framerate of the editor as a whole was extremely poor while the main game scene was open.

Trying to play the game through the editor yielded around 10 FPS, with a release build giving 10-20 FPS. The template is minimal, with only some platforms, physics objects, and a player controller, so I would expect the framerate to be fine, even on my fairly mid performance laptop. 

Disabling the visuals for the platforms and environment did not improve performance noticeably, and the profiler shows that most of the frame time goes to "Process Time"
![image](https://github.com/godotengine/godot/assets/29745653/c93d8a31-d4ea-41c8-8f58-acad87f8accb)

Since this seemed to be unrelated to rendering, I tried disabling the player controller (commenting it out), which did not improve performance noticeably. 

### Steps to reproduce

Open the project in godot and try panning the editor camera/playing the game. All aspects of the editor seem to be affected by the low framerate (on my end at least)

### Minimal reproduction project

Note: This has a few changes from the default Kenney Template, such as an FPS label and the environment set to non-visible.
[Kenney3DPlatformerAsset.zip](https://github.com/godotengine/godot/files/12778445/Kenney3DPlatformerAsset.zip)

**Comment by Calinou** [comment]
That project uses 8× MSAA, which is *very* demanding and should never be used on integrated graphics. Disable it in the project settings, and you should see FPS more than double.

**Comment by DoubleBrackets** [comment]
Thanks so much for the reply!

I did as you suggested:
- Disabled glow, SSAO, SSR, SSIL, SDFGI
- Disabled MSAA
- No VoxelGI nodes, from what I can tell
- Turned on half resolution anyways

This gets me to around 30 fps with the scene visible, and setting the rendering scale to 0.5 gets me to 45 fps. Release build is identical. Is this performance about expected? 
My past experience with Unity makes me feel like this is still quite a bit below expectations, especially on minimum settings, but I'm assuming my knowledge is lacking somewhere.

**Comment by Calinou** [comment]
>  Is this performance about expected?

With the Forward+ rendering method, it sounds expected. You can get better performance by switching to the Mobile rendering method (or Compatibility, but it currently lacks support for rendering shadows).

**Comment by DoubleBrackets** [comment]
Switching to mobile seemed to make the biggest impact. Thanks for all the help!
