### ISSUE TITLE
Array.fill() with a Script Class based variant parameters make them linked like you filled with a reference to one object.

### ISSUE THREAD

**Issue by Rebell10n** [godotengine/godot#82646]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 7, yeah I know that old, but not relevant imo, CPU : Intel i-5-4200H, 2.80GHz, GPU : GeForce 840M DDR3 2 Go

### Issue description

Heya there, I hope that this time it isn't just me who did shit the way I coded the thing, like I misunderstood or used badly the fill() method, or used a Class.new() while I shouldn't lol.

So here we go : The bug is if you use `Array.fill( Class.new() )` the Array may be filled with certainly, copies of this Class with default propriety.

But when you change one propriety of one Array member (class specified attribute), it change it for all array members.

### Steps to reproduce

Create a Class with a script (one with a class_name, easier this way)
Add an variable in that class, anything you like

In another script, you gonna create an Array. And instantiate it in the `func _init()`.
With a resize, any size.
Then fill it with your previously created class from that another script (so I guess Class.new() and not just Class cuz else it just refuse to change anything cuz I guess that the object instantiated from the class you want in multiples examplaries, not the class itself right ?)

Then try changing the propriety previously put in that Class, with a `for i in Array.size()` for example, changing for each different id.

Then do a second `for i in Array.size()`, just to be sure you see the END result, and not the while rewriting the array result, and print each Array members attribute.
And then you will see that first they're all the same, and the last result possible from your previous `for`

Well I don't have real proof that this is indeed a reference to the same object that is in each Array members, but that look very similar at least, and even if it's not, it a very indesirable behavior.

### Minimal reproduction project

[ArrayFill() Bug.zip](https://github.com/godotengine/godot/files/12778470/ArrayFill.Bug.zip)

**Comment by AnimePenguin** [comment]
This is intended behavior, if you want to fill the array with unique values use a for loop or .map()
```
# Example:
var array = range(num_of_elements).map(func(__): return Class.new())
```

**Comment by Rebell10n** [comment]
Oh.
Well I guess I was false once again...
Thanks for the answer.

Well I would still end up with a small suggestion, to add that ... somewhere, maybe in the docs, just to avoid misunderstanding and errors like that again I guess.

**Comment by kleonc** [comment]
> Well I would still end up with a small suggestion, to add that ... somewhere, maybe in the docs, just to avoid misunderstanding and errors like that again I guess.

It's already documented:
https://github.com/godotengine/godot/blob/0ca8542329888e8dccba89d59d3b728090c29991/doc/classes/Array.xml#L282

See: #68032, #68051.

**Comment by Rebell10n** [comment]
Right, I missed that one, my bad. Then I guess I once again opened a topic for a false alert on my side...
Thanks for the answers.
