### ISSUE TITLE
Directional lightmap doesn't work correctly with Desnoiser.

### ISSUE THREAD

**Issue by AwesomeJuniorMiss** [godotengine/godot#82655]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP () - Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 Threads)

### Issue description

![Denoiser Off](https://github.com/godotengine/godot/assets/9027530/3f85f897-4a25-41c5-8713-1f53aa7ada11)
Directional On, Denoiser Off

![Denoiser On](https://github.com/godotengine/godot/assets/9027530/6d9c72d6-556c-4a5e-ba05-0c6057c0f102)
Directional On, Denoiser On

The lighting result just looks incorrect while using Directioal and Denoiser simultaneouly. But using each of them alone, the result would be correct. No mater how high quality setting used for LightmapGI and how large lightmap size used, this issue remains.

### Steps to reproduce

Create a box mesh on the ground. Add UV2.
Assign a standard gray material to box and floor. No reflection, roughness is 1, metallic is 0.
Setup a simple custom sky or color background as environment lighting.
Bake lightmaps using high or ultra quality preset.

### Minimal reproduction project

[Box_4.1.zip](https://github.com/godotengine/godot/files/12779380/Box_4.1.zip)

**Comment by Calinou** [comment]
It looks like this in `master` with the [new denoiser](https://github.com/godotengine/godot/pull/81659):

![image](https://github.com/godotengine/godot/assets/180032/91b37adf-8a59-4bb1-9f89-3f5430254330)

This appears to be correct.

**Comment by Calinou** [comment]
Closing, as this should be fixed as of [4.2.dev6](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-6/) per the above comment.
