### ISSUE TITLE
Children of instance limited access. 

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#8265]
**Operating system or device - Godot version:**
Win 10 
Godot version 2.1.1

**Issue description:**

Created an instance inside main scene but cannot access properties of other sprite nodes

**Steps to reproduce:**
In the best detail I can give:

I created a scene with a node called "Player".
I added 3 children under this node called "RigidBody2D", "Sprite", and "AnimationPlayer"

I saved the scene.

Next, I opened my main scene that has a Node and a child Background sprite in it called " Background "
I add the Player scene to the Main scene as an Instance.
*I had to click on the Player node and select "Editable Children" to gain access to the RidigBody2D inside Player.
Next I added a script to the RigidBody2D.

It is in this script that no matter what I do I cannot access the Main scene's Background sprite's properties like "get_width" .

It is strange because if I add a node directly to the Main scene (not an instance), I can access the background spite's properties. However, I can't access background sprite's properties  through the children of the Instantiated Player node. Does that make sense? 

**Link to minimal example project:**

**Comment by Zylann** [comment]
When does this happen? Is it when you run the game?

**Comment by bojidar-bg** [comment]
To me at least, it looks like some autocompletion issue, though I'm not exactly sure if it is fixable with ease.
If it isn't an autocompletion issue though, then it is probably with your own script :wink:

@ondesic Mind if you share some example stripped-down project?

**Comment by ondesic** [comment]
I'll create a stripped down project

**Comment by ondesic** [comment]
Here is the project.  I am also including a screenshot of my project to show that the autocomplete does not show any properties of the sprite.  

In my humble opinion I don't think it is an autocomplete issue.  When I force the code and use `get_texture` or `get_width` it throws an error.

thanks for looking into this.  I really look forward to continuing development with Godot
[test.zip](https://github.com/godotengine/godot/files/900179/test.zip)

**Comment by eon-s** [comment]
The script is attached to a node in another scene, it can be instanced anywhere so `get_parent().get_parent().get_node("Back")` could be anything, I don't think autocomplete can help you there.

And since you are getting a Node, better add it on ready (or do `onready var`) instead.

**Comment by ondesic** [comment]
I added the script to RigidBody2D after I added the instance to the main scene.
If you get rid of `.get_node("Back")` then print() will say "Node" so I believe it is reading the tree correct.  As well, if I spell "Back" wrong it will give me an error.  So, if it can see the Back sprite, shouldn't it be able to access the properties of the Back sprite?

Again, if I just type `get_width()` on variable "bk" and run it, it throws an error.  Even though it says bk is a sprite, it isn't treating it like a sprite.

**Comment by bojidar-bg** [comment]
@ondesic http://docs.godotengine.org/en/stable/classes/class_sprite.html -- Sprite has no `get_width` function...

**Comment by ondesic** [comment]
shouldn't it have a `get_texture`?

**Comment by ondesic** [comment]
I did a test and added the script directly to the Player Node.  I just removed one `get_parent()`  Everything works as expected.
For some reason, children of an "instantiated" node cannot access properties of the main node.  Can this be fixed?

**Comment by bojidar-bg** [comment]
@ondesic There is __nothing__ special done for instanced or noninstanced nodes at while the game is running by the engine. The difference exists only while you are in the edtior.

Thus, there is nothing like "unable to access main/parent/some other node's properties", since the nodes node aren't that much different from one another for the purpose for accessing properties or calling methods.

Checking the project you gave, here is a fixed script with comments about the changes: 
```gdscript
extends RigidBody2D

onready var bg = get_parent().get_parent().get_node("Back")
# ^-- changed here, since `var` accepts only _constants_, while `get_parent()...` isn't constant
# `onready` would calculate the expression just right before calling `_ready()`

func _ready():
	print(bg.get_type())
	print(bg.get_texture())
	# bg.get_tex... doesn't autocomplete, but this doesn't mean get_texture won't work at runtime
```
Since GDScript is a dynamically-typed language, and the current autocompleter doesn't go through every possibility, it happens from time to time that it won't be able to autocomplete a method/property, since it failed to guess the type of a variable. In those cases, you can still write the name of that method and use it just fine, and if you managed to make some errors, it would tell you while running the game. 
(Don't worry, the exported version would just ignore the invalid stuff and continue on, instead of crashing.)

**Comment by kubecz3k** [comment]
I'm revisiting old issues, Closing this one since as far as I understand from above comment there were no issue in the end on the engine side.
