### ISSUE TITLE
Context menu doesn't close and re-opens when pressing ESC to close it (ESC opening context menu in general it seems)

### ISSUE THREAD

**Issue by RoyBeer** [godotengine/godot#82659]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

When writing code in the editor, I run into this issue frequently.

Sometimes the context menu opens, i.e. when I type '.' 
However, if I don't intend on using anything from it, I need to mouse click to close it again, as pressing ESC closes the list of suggestions, however, the context menu is opened up instantly and keeps open until I close it with the mouse again.

This severely hinders my workflow

### Steps to reproduce

Open Script Editor Tab

Press '.' anywhere

Context Menu with list of suggestions opens

Press ESC

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
You're referring to the autocompletion popup, not a context menu. A context menu is something you see when right-clicking a GUI element.

**Comment by RoyBeer** [comment]
> You're referring to the script editor's autocompletion popup, not a context menu. A context menu is something you see when right-clicking a GUI element.

I'm referring the menu that opens when right clicking. That's the context menu that opens when pressing ESC.
https://youtu.be/S_puIaPflEo

**Comment by Calinou** [comment]
> I'm referring the menu that opens when right clicking. That's the context menu that opens when pressing ESC.
[youtu.be/S_puIaPflEo](https://youtu.be/S_puIaPflEo)

I can't reproduce this on 4.2.dev fe8a58b9d (Linux). Pressing <kbd>Escape</kbd> discards the autocompletion popup but doesn't make any context menu appear.

**Comment by kitbdev** [comment]
Is your `ui_menu` shortcut in Editor Settings set to escape? It should be set to Menu by default

**Comment by RoyBeer** [comment]
> Is your `ui_menu` shortcut in Editor Settings set to escape? It should be set to Menu by default

Oh my god, that was indeed the case. I must've set that when I started to mess around with menus and didn't realize my mistake.

Bug was sitting in front of the keyboard
