### ISSUE TITLE
Setting GlobalPosition takes multiple frames to take effect

### ISSUE THREAD

**Issue by MattSayer** [godotengine/godot#82662]
### Godot version

v4.1.1.stable.mono.official.bd6af8e0e

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 Threads)

### Issue description

Setting GlobalPosition of an AnimatableBody3D (in this case) does not apply for multiple frames. For example, I read the GlobalPosition of a projectile and print it out, then set a new _different_ global position, then print that out. The result is the same Vector3.

```csharp
GD.Print(projectile.GlobalPosition);
projectile.GlobalPosition += Vector3.Forward * 5f;
GD.Print(projectile.GlobalPosition);
```

By deferring a small time (0.1s in my test) before reading GlobalPosition, the changes _do_ apply. This bug prevents setting an object's GlobalPosition then immediately moving it, since the subsequent move will apply to the original GlobalPosition, not the one just set.

### Steps to reproduce

```csharp
GD.Print(projectile.GlobalPosition);
projectile.GlobalPosition += Vector3.Forward * 5f;
GD.Print(projectile.GlobalPosition);
```

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/76685.

Is **Sync to Physics** enabled on the AnimatableBody3D?

**Comment by MattSayer** [comment]
Bah, I'm so sorry! I will remember the backticks for the future.

Also, yes, I'm a doofus and literally just noticed that checkbox and came back to close this issue. So sorry to bother you!

**Comment by MattSayer** [comment]
Was a result of having Sync To Physics checked on the AnimatableBody3D
