### ISSUE TITLE
Usability issue with exported node types when a scene is Duplicated in the editor

### ISSUE THREAD

**Issue by sszigeti** [godotengine/godot#82686]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11

### Issue description

It's great to be able to directly export nodes instead of having to export them as NodePaths, or to use `get_node` even with a unique scene name.

This works as expected when a scene with an exported node is instantiated in the editor. But, if I use the <kbd>Control+D</kbd> shortcut (or select this command from the popup menu), the node refence breaks, and the duplicated scenes will refer to the original node, instead of the nodes in their own hierarchy.

I think I understand why this might work like this, but I doubt the current behavior would be useful in any case. An exported node is hardly some outer resource which could act as a "static" member. I'd rather expect that when I lazily duplicate a node, then all its inner node references also updated, as it happens when using a NodePath.

### Steps to reproduce

Please check out the attached minimal reproduction project, and/or take a look at the code repository and the screenshot:

https://github.com/sszigeti/Godot_Exported_node_duplication_behavior

![Screenshot](https://raw.githubusercontent.com/sszigeti/Godot_Exported_node_duplication_behavior/master/screenshot.png)

### Minimal reproduction project

[Godot_Exported_node_duplication_behavior-1.zip](https://github.com/godotengine/godot/files/12784958/Godot_Exported_node_duplication_behavior-1.zip)

**Comment by warriormaster12** [comment]
https://github.com/godotengine/godot/issues/82670 sounds related to this

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82670.
