### ISSUE TITLE
Godot crushes when file deletes from res by code in editor hint

### ISSUE THREAD

**Issue by iRumba** [godotengine/godot#82687]
### Godot version

4.1.1.stable MONO

### System information

Windows 10, GLES2, Intel(R) UHD Graphics 630

### Issue description

I have tool, that creates new metadata file for my level scene with name same as tscn file but with tres extension, when level scene creates.

Also, when scene file renames, tool script see it and executes this

```
            ResourceSaver.Save(Metadata, expectedMetadataFilePath);
            Metadata = LoadLevelMetadata(expectedMetadataFilePath);
            DirAccess.RemoveAbsolute(currentMetadataFilePath);
```

- Creates new file
- Loads new file to variable
- Deletes old file

Script works fine (file renamed in the end), but godot terminated without some errors messages.

It happenes when file deleted.

File is in res:// scope

Maybe is there more safely method for file deleting?

UPDATE:
Godot terminates not after deleting file, but because it.

After deleting file is in resources manager. But it is not exists physically. So, godot terminates when I move mouse pointer to file in res (in this moment godot tries get file size and type).

UPDATE2:
My problem solved by `_editorPlugin.GetEditorInterface().GetResourceFilesystem().Scan();` after file deleting

But it is bug I think. Because godot crashes after deleting file from file system.

### Steps to reproduce

Nothing

### Minimal reproduction project

Nothing

**Comment by dalexeev** [comment]
@iRumba Please add Steps to reproduce and MRP. A crash dump with debug symbols would also be helpful.
