### ISSUE TITLE
Node names autoincrement not working

### ISSUE THREAD

**Issue by fkrauthan** [godotengine/godot#82709]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.21031.1005) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When spawning instantiated objects via the following code:

```
var laser = laser_scene.instantiate() as Area2D
$Projectiles.add_child(laser)
```

while `laser_scene` is defined as `var laser_scene: PackedScene = preload("res://scenes/projectiles/laser.tscn")`.

The `laser.tscn` root node is an area2d called `Laser`. The first time I instantiate the area2d it shows up correctly as `Laser`. However all subsequent instantances are falling back to `@Area2d@xx` format even though based on all documents I would have expected to have `Laser@xx`. See screenshot below:

![Screenshot 2023-10-02 212936](https://github.com/godotengine/godot/assets/1679841/6def93ce-aa40-4609-b2ef-b29bb93c8875)

### Steps to reproduce

1. Create simple 2d project
2. Create a 2d scene with a root node (e.g. `Area2D`) and call it e.g. `Laser`
3. Create a second 2d scene with a script attached to the root and on input (e.g. mouse click) initiate that first scene and add it to the scene tree
4. Observe the `Scene` -> `Remote` view

### Minimal reproduction project

na

**Comment by Mickeon** [comment]
> However all subsequent instantances are falling back to `@Area2d@xx` format even though based on all documents I would have expected to have `Laser@xx`.

I don't see the issue. This is probably a misunderstanding. See the documentation of [`add_child()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child):

> If `force_readable_name` is **`true`**, improves the readability of the added `node`. If not named, the `node` is renamed to its type, and if it shares [`name`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-property-name) with a sibling, a number is suffixed more appropriately. This operation is very slow. As such, it is recommended leaving this to **`false`**, which assigns a dummy name featuring `@` in both situations.

For what you may expect, like the editor does, you need to set the second parameter of `add_child` to true.

**Comment by fkrauthan** [comment]
Oh I see. So it is expected that the first node uses the actual node name and everything else (if there is a conflict) it uses the type name? Thanks for clarifying it. Somehow based on tutorials and docs I assumed the default behaviour suppose to always be the node name plus a number if required.

**Comment by KoBeWi** [comment]
Assigning human readable names is more expensive, so it's done only in the editor. By default nodes are added with `@` autonaming, which uses a global counter and guarantees the name is unique without much overhead.

Closing, as this is intended.

**Comment by fkrauthan** [comment]
@KoBeWi But that is the part I don't understand. The FIRST node uses the Node Name. Only subsequent instances uses the node type name so it still feels like based on your explanation to be a strange behaviour. As you said it should ALWAYS use node type name when calling `add_child` the screenshot above all instances where created with add_child and none added via editor inside the `Projectiles` node.

**Comment by KoBeWi** [comment]
The name is modified only in case of conflict. With readable names, you need to count all nodes. With "unreadable" names you can just slap `@` and a number, without doing any checks. The initial uniqueness check is done in both cases.

**Comment by fkrauthan** [comment]
Ah perfect that makes sense. Thanks for clarifying it.
