### ISSUE TITLE
Can't preload resource uid for PackedScene.

### ISSUE THREAD

**Issue by SUPERIONtheKnight** [godotengine/godot#82701]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Ubuntu 20.04.2 LTS (Focal Fossa) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 525.125.06) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

In an attempt to learn how loading differing scenes work, I attempted to load/preload a PackedScene from a simple gdscript. Loading things seems to work fine regardless of whether or not I use a path like "res://whatever", or a resource uid such as "uid://clm7c2mtievx2".

The same does not appear to be true for preloading which only can seem to take "res://whatever", and not the resource uid. Instead we get errors such as:
"Condition "nc == 0" is true. Returning nullptr",
"Parameter "p_child" is null".

As I could not figure out what was causing this, I took to discord asking for help. Someone kindly helped me out, and found that the problem code seems to be [here](https://github.com/godotengine/godot/blob/master/scene/resources/packed_scene.cpp#L1916-L1919) and recommended I make an issue.

### Steps to reproduce

Create an empty project. Create a main scene with a Node called Main, and attach a script to it containing the following:
`extends Node`
`var loadGame = load("UIDHERE")`
`func _ready():`
`    var game = loadGame.instantiate()`
`    self.add_child(game)`

Now create another packed scene, and save it. Right click this packed scene to "Copy UID", and replace "UIDHERE" in the script we just made a moment ago with the UID we just copied. Observe that upon playing the game, it works fine. Now change `load("uid://...")` out with `preload("uid://...")`. You should now receive the errors mentioned above.

### Minimal reproduction project

[PreloadUIDPackedSceneBug.zip](https://github.com/godotengine/godot/files/12787640/PreloadUIDPackedSceneBug.zip)

**Comment by KoBeWi** [comment]
Looks like a bug in ResourceLoader. It assigns UID as path.
