### ISSUE TITLE
Clearing one of the values of TypedArray in the inspector makes the value unable to be found by the find function

### ISSUE THREAD

**Issue by kus04e4ek** [godotengine/godot#82716]
### Godot version

v4.1.2.rc1.official [58f0cae4a] and v4.2.dev5.official [e3e2528ba]

### System information

Godot v4.1.2.rc1 - Windows 10.0.19044 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Clearing one of the values of a typed array in the inspector seems to just unreference value and not set it to `<null>`, so the value becomes `<Object#null>`. Array's find function seems to look for the `<null>` value and doesn't accept `<Object#null>`, even if in GDScript `<Object#null>` == `<null>`. So, when calling array.find(null) in the tool script, the function can't find anything. When the project is restarted or you run it, the values that were equal to `<Object#null>` will become `<null>`.
![image](https://github.com/godotengine/godot/assets/118438257/208dbf2c-19ea-4d97-9e46-646662cb5122)

### Steps to reproduce

1. Export a typed array of Resource or any of the types that inherit from it;
2. Set one of the values of a typed array to anything;
3. Clear the value;
4. Use array.find(null) in any of the tool scripts.

### Minimal reproduction project

[ArrayBug.zip](https://github.com/godotengine/godot/files/12789530/ArrayBug.zip)

**Comment by kus04e4ek** [comment]
Still a problem in v4.2.dev6.official [57a6813bb]

**Comment by KoBeWi** [comment]
The MRP crashes on master.
