### ISSUE TITLE
No get_close_button() method in Godot4 ?

### ISSUE THREAD

**Issue by cyberpsyche** [godotengine/godot#82721]
### Godot version

Godot 4.2 dev5

### System information

MacOS 10.15.7 (19H2) Intel Iris Graphics 6100 1536 MB

### Issue description

There is no get_close_button() method in Godot4.2 ? 

How to get the close button of a Window or a Dialog if I want to hide it ? 

Thanks.

### Steps to reproduce

sorry, no content here...

### Minimal reproduction project

sorry, no content here...

**Comment by Mickeon** [comment]
You can set its `visible` property to `false` if hiding is the intention. Or, you use the appropriately named method.
![image](https://github.com/godotengine/godot/assets/66727710/9e0d197b-9948-48d4-bb30-7c19ee53f843)

This is not the right place for asking assistance, by the way. But I'm sure Calinou will have more to say about that.

**Comment by YuriSizov** [comment]
For help questions please refer to one of our [community channels](https://godotengine.org/community/).
