### ISSUE TITLE
Godot 4.1.1 gridmap doesn't update from meshlibrary properly when saving meshlibrary as .tres file

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#82726]
### Godot version

4.1.1 stable

### System information

Windows 10

### Issue description

Updating the gridmap meshlibrary scene and updating the meshlibrary changes the scene in the editor, but doesn't reflect the changes when running the scene or re-opening it:

https://github.com/godotengine/godot/assets/16231628/94f433c8-6599-4e39-8e42-626c514b8d52

### Steps to reproduce

- Create a gridmap scene
- Create a meshlibrary from the gridmap scene
- Change the transforms on a mesh in the gridmap scene
- Update the meshlibrary
- Run the scene/reopen the scene and see the changes reverted

FIX: don't save the meshlibrary as a .tres file, keep it embedded in the scene:
![image](https://github.com/godotengine/godot/assets/16231628/66ce060d-63e3-4467-8a49-d6740765ab17)

### Minimal reproduction project

N/A

**Comment by elvisish** [comment]
I wonder if the MeshLibrary resource needs to be updated when the Gridmap is updated, perhaps the changes are just not being saved back to the resource file?

**Comment by KoBeWi** [comment]
Can't reproduce in 4.2.

**Comment by akien-mga** [comment]
@elvisish Can you check if it's also fixed for you in 4.2-rc1 or later?

**Comment by elvisish** [comment]
> @elvisish Can you check if it's also fixed for you in 4.2-rc1 or later?

It's still broken in RC1:
* Save the MeshLibrary as a resource file
* Change the position of a mesh and save
* Update the MeshLibrary with applied transforms in the scene
* Save the scene, close and reopen
* Positions will be back to original position

Repeating the steps above with the MeshLibrary embedded into the gridmap will work.

**Comment by elvisish** [comment]
This needs reopening, Import From Scene does nothing if the meshlibrary is saved as a resource, it needs to be unique to the gridmap:

<img width="702" height="121" alt="Image" src="https://github.com/user-attachments/assets/321f4c29-9a82-4330-8f70-5b6f12a3feab" />

Also, Update from Scene does nothing, only "Import From Scene (with transformations)" works now.

**Comment by AThousandShips** [comment]
Please open a new issue, this has been resolved long ago and should be kept closed as originally resolved

**Comment by elvisish** [comment]
> Please open a new issue, this has been resolved long ago and should be kept closed as originally resolved

It's the exact same issue as before, but sure thing I'll open a new one anyways.

**Comment by AThousandShips** [comment]
Even if the original assumption that the issue was solved back in 4.2 was wrong a new issue would be required, it's far too old and out of date (and obviously if it was actually resolved and resurfaced it should remain closed anyway)
