### ISSUE TITLE
MultiMesh.SetBuffer seems to be non-existent in C#

### ISSUE THREAD

**Issue by Nemecle** [godotengine/godot#82744]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (RADV NAVI23) () - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

The "set" function of the `Buffer` property (`set_buffer` in GDScript) in MultiMesh seems to be non-existent in **C#**.

In accordance with the page [C# API differences to GDScript](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html), the function should be `SetBuffer`. Trying to use it, as well as case-variants like setBuffer, snake_case `set_buffer` or even its [previous name](https://github.com/godotengine/godot/blob/f5696c311cdb09e0a34fa4ba7ef5d2524c515b89/editor/renames_map_3_to_4.cpp#L915) `SetAsBulkArray` yields an error Code CS1061 (_"does not contain a definition [...]"_)

I am more or less new to Godot so it might be my own fault, but digging around the documentation and even the code doesn't seem to help.

### Steps to reproduce

```
MultiMesh mMesh = new(); //doesn't contain any instance information, but it doesn't matter
System.Collections.Generic.List<float> transformBuffer = new();
Transform3D trans = new();

transformBuffer.Add(trans.Origin.X);
transformBuffer.Add(trans.Origin.Y);
transformBuffer.Add(trans.Origin.Z);
	
transformBuffer.Add(trans.Basis.X.X);
transformBuffer.Add(trans.Basis.X.Y);
transformBuffer.Add(trans.Basis.X.Z);
	
transformBuffer.Add(trans.Basis.Y.X);
transformBuffer.Add(trans.Basis.Y.Y);
transformBuffer.Add(trans.Basis.Y.Z);
	
transformBuffer.Add(trans.Basis.Z.X);
transformBuffer.Add(trans.Basis.Z.Y);
transformBuffer.Add(trans.Basis.Z.Z);

mMesh.SetBuffer(transformBuffer); // CS1061
```

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
We don't expose the property accessors in C#. Use the `Buffer` property directly. Also, the property is of type `float[]` so make sure the list is converted to an array first.

```csharp
mMesh.Buffer = transformBuffer.ToArray();
```

**Comment by Nemecle** [comment]
Noted, thank you for your reactivity
Regards,
