### ISSUE TITLE
Gridmap cursor clear rotation hotkey doesn't work in 4.1.1

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#82746]
### Godot version

4.1.1 stable

### System information

Windows 10

### Issue description

The gridmap "Cursor Clear Rotation" hotkey does not work work in Godot 4.1.1

### Steps to reproduce

- Select a gridmap mesh item
- rotate it with a hotkey
- press W to clear cursor rotation
- it won't work

### Minimal reproduction project

N/A

**Comment by Anutrix** [comment]
Based on https://github.com/godotengine/godot/pull/79529, it seems like it was fixed/refactored for 4.2 not 4.1.

**Comment by KoBeWi** [comment]
Yep, already fixed in 4.2
