### ISSUE TITLE
Sliced 3D animations that are saved as external resources aren't processed by the scene importer bone renamer

### ISSUE THREAD

**Issue by dpalais** [godotengine/godot#82753]
### Godot version

4.2 dev f5696c311cdb09e0a34fa4ba7ef5d2524c515b89

### System information

Linux

### Issue description

Assuming the fix from #82300 is in in order to save the animation slices to files, the resulting animation resources are saved prematurely and don't feature remapped bones.

It seems to be the case because animation slices are saved during `_pre_fix_animations`, before the skeleton renamer plugin has a chance to process the animations in `_post_fix_node`.

```cpp
ResourceSceneImporter::import(...)
{
/// ...
	_pre_fix_animations(scene, scene, node_data, animation_data, fps);
	_post_fix_node(scene, scene, collision_map, occluder_arrays, scanned_meshes, node_data, material_data, animation_data, fps, apply_root ? root_scale : 1.0);
	_post_fix_animations(scene, scene, node_data, animation_data, fps);
/// ...
}
```

### Steps to reproduce

1. Apply the fix from #82300
2. Save an sliced animation to external resources.
3. The external animation resources use the unremapped skeleton/bone names.

### Minimal reproduction project

Not available due to constraints to redistribution of third party resources.

**Comment by Calinou** [comment]
cc @jsjtxietian

**Comment by jsjtxietian** [comment]
I will take a look tomorrow.

**Comment by jsjtxietian** [comment]
@dpalais I move the related function to `_post_fix_animations`, can you help test this code since I don't have a MRP. Many thanks.

**Comment by dpalais** [comment]
@jsjtxietian It works as expected. The sliced animations are saved after the bone renamer has processed them, and after my own animation processing scene import plugin has processed them too.
