### ISSUE TITLE
Asset Library causes Project Manager UI to extend beyond visible window

### ISSUE THREAD

**Issue by Arctyc** [godotengine/godot#82761]
### Godot version

4.1.1.stable.official

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 Threads)

### Issue description

What doesn't work:

When viewing community asset library projects, the UI can extend off the visible window to the right, it appears to be caused by projects with long names combined with the action of resizing the window.

The full UI only becomes visible at an extremely wide window size.

How it should work:

The entire UI should be visible regardless of window size or shape.

![Godot_v4 1 1-stable_win64_m21Bns34Co](https://github.com/godotengine/godot/assets/62357807/a156422d-a327-4d27-b074-b54fa4924f72)
![Godot_v4 1 1-stable_win64_UQeTX5Tm7L](https://github.com/godotengine/godot/assets/62357807/1dfea2b6-f864-45ab-a433-eefc696da1ee)

### Steps to reproduce

1. open Godot project manager
2. click Asset Library Projects tab
3. Click support
4. check "community"
5. if the problem is not immediately present, resize window

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80507 (this is fixed in 4.2.dev6).
