### ISSUE TITLE
Render mode ensure_correct_normals seemingly not working

### ISSUE THREAD

**Issue by OhiraKyou** [godotengine/godot#82763]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Fedora Linux 38 (Workstation Edition) - Vulkan (Compatibility) - AMD Radeon RX 560 Series (polaris11, LLVM 16.0.6, DRM 3.54, 6.5.5-200.fc38.x86_64) () - Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 Threads)

### Issue description

Quick note first: It's possible that I've just been calculating world space normals wrong in spatial shaders. But, assuming I haven't, I would consider this to be a pretty significant bug or feature gap in any renderer mode.

Shader code, for reference:

```glsl
shader_type spatial;
render_mode unshaded, ensure_correct_normals;


void fragment() {
	// Edit: using vec4(NORMAL, 1.0) here causes some view-dependent results.
	// So, something is happening, and I may just be using it wrong. I dunno.
	// I'd leave matrix math up to utility functions if I could.
	// `get_world_normal()` and similar functions would be great.
	vec3 world_normal = (INV_VIEW_MATRIX * vec4(NORMAL, 0.0)).xyz;
	vec3 world_up = vec3(0.0, 1.0, 0.0);
	float alignment_alpha = dot(world_normal, world_up) * 0.5 + 0.5;
	ALBEDO = vec3(alignment_alpha);
}
```

Also, potentially related issues I found were for Godot 3.x rather than 4.x and involved negative scaling (which this issue does not).

#### Current behavior

The screenshot below was taken from the attached project, in Godot v4.1.1.stable.official [bd6af8e0e]. I have also opened the project in Godot v4.2.dev5.official [e3e2528ba] and found no difference. The project uses the Compatibility renderer. I have not tested the Forward+ or Mobile renderers, because I have not found either to run acceptably on my hardware/software combo.

In the project's included test scene, there are two sets of three instances of the built-in sphere mesh, with different scales. One set uses the `ensure_correct_normals` render mode. The other set does not.

Notice the following:

- Both sets look identical, despite one set using the `ensure_correct_normals` render mode in its shader.
- Contrast is focused onto the top-center of the squashed spheres, despite their top surfaces being relatively flat throughout in world space.
- Contrast is focused onto the center of the stretched spheres, despite their curvature being relatively smooth across their length in world space.

![Normals Scaling - Godot 4 1 1 stable - 1](https://github.com/godotengine/godot/assets/7255919/fd6042c1-2c9e-4a3c-9e3c-86ec4a643e50)

#### Expected behavior

The screenshot below was taken from a similar scene, made in Unity. Notice how brightness correlates to flatness. A shelf made from a flattened sphere is almost entirely flat throughout. Therefore, its visualized normals are also relatively flat throughout. Tops read as tops (white), and sides read as sides (grey)—even when the ratio of their surface area changes.

I would also expect this to be the default behavior (opt-out rather than opt-in), because it results in significantly improved direction alignment calculation accuracy in world space, where design takes place and quite a lot of arbitrary scaling of assets is done. During both level design and shader authoring, one expects a relatively flat surface to catch light like a relatively flat surface, regardless of how it became that way.

![Normals Scaling - Unity 2022 2 1f1 - 1](https://github.com/godotengine/godot/assets/7255919/0786e0a6-2fc2-4d92-9119-18690d254ef8)

### Steps to reproduce

1. Open the attached project.
2. Open the scene at `res://scenes/test_scene_1.tscn`
3. Observe that there are significant differences in color contrast (lightness gradient harshness) between different sizes of the same mesh instances in the scene.
4. Observe no perceivable differences between same-size pairs in the two sets of mesh instances, despite only one set additionally being assigned the `ensure_correct_normals` render mode.

### Minimal reproduction project

[Godot 4.1.1.stable - Normals Scaling.zip](https://github.com/godotengine/godot/files/12798514/Godot.4.1.1.stable.-.Normals.Scaling.zip)

**Comment by clayjohn** [comment]
This indeed looks like an issue with non-uniform scaling which should be fixed by using ``ensure_correct_normals`` However, it seems that it hasn't been implemented yet in 4.x. Should be an easy fix. 

The internal scene shader has a ``ENSURE_CORRECT_NORMALS`` defines when ``ensure_correct_normals`` is used. This is the same as in 3.x. So we need to copy and paste that code from 3.x into the 3 scene renderer glsl files in 4.x

**Comment by BlueCube3310** [comment]
Curiously, even though the Mobile and Forward+ modes ignore the ENSURE_CORRECT_NORMALS define, they appear to use corrected normals regardless of whether the define is present:
<img width="1079" alt="aa" src="https://github.com/godotengine/godot/assets/53150244/5651522e-61b3-4892-869e-08fa8573217a">
<img width="660" alt="aaaaaaa" src="https://github.com/godotengine/godot/assets/53150244/f9cfea28-b62f-4f13-8331-0a35bfac888d">

Is this the intended result? If so, could the Compatibility renderer be modified to use the same method for correcting normals, and the ENSURE_CORRECT_NORMALS  define deprecated?

**Comment by BlueCube3310** [comment]
After examining the GLES3 code, it appears that the instance flags never get passed to the scene shader and instead are only used on the CPU side, and the instancing is also done in a different way. A new attribute in the scene shader would have to be added to store information about the flags, but that would result in a slight increase in VRAM usage, which does not seem like a good idea. 
Maybe the Compatibility renderer could use the `ensure_correct_normals` define like it did in 3.x?

**Comment by Calinou** [comment]
> but that would result in a slight increase in VRAM usage, which does not seem like a good idea.

I doubt we are *that* VRAM-starved when using the Compatibility rendering method, given its low-end focus. I'd favor better usability and consistency across rendering methods over having to bother about this flag from the 3.x era again :slightly_smiling_face:

**Comment by OhiraKyou** [comment]
I agree with @Calinou about consistency. Ideally, switching renderers should produce identical results where their features overlap, and that requires shared defaults.

Also, the PR results look good! Meanwhile, for anyone seeking a quick fix, here's a version of the normals visualization shader that includes a fixed normal transformation:

```glsl
shader_type spatial;
// Enable manual transformation with skip_vertex_transform
render_mode unshaded, skip_vertex_transform;

// Perform manual transformation, but with the normals fix
void vertex() {
	// Usual position
	VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;

	// Fixed normal
	mat3 model_to_view_normal_matrix = transpose(inverse(MODELVIEW_NORMAL_MATRIX));
	NORMAL = model_to_view_normal_matrix * NORMAL;
}

// Visualize normals
void fragment() {
	vec3 world_normal = (INV_VIEW_MATRIX * vec4(NORMAL, 0.0)).xyz;
	vec3 world_up = vec3(0.0, 1.0, 0.0);
	float alignment_alpha = dot(world_normal, world_up) * 0.5 + 0.5;
	ALBEDO = vec3(alignment_alpha);
}
```
