### ISSUE TITLE
`print()` is no longer sent to Output panel when running project on Android due to debugger connection not working

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#82764]
### Godot version

4.2 dev f5696c311cdb09e0a34fa4ba7ef5d2524c515b89

### System information

Android

### Issue description

When running an Android application with "remote debug" ticked, Godot would always output print and error messages to the log in the Godot IDE.

We use this extensively in XR where alongside the "verbose" tickbox, we add a lot of extra information through `print_verbose`.
Even without that a standard Android project would atleast output the standard print lines (such as the "Godot Engine v4.1.1stable..." line).

So for instance running a simple XR project in Godot 4.1.1 stable with verbose enabled and remote debug enabled gives us:
![image](https://github.com/godotengine/godot/assets/1945449/59a59e7b-5fb8-48aa-8b61-6bc498f20c4d)

Doing the same in master:
![image](https://github.com/godotengine/godot/assets/1945449/43f36485-8901-4489-a2b8-4e5b9a6e02db)

No more log. Same issue applies to normal Android. I have only tested this with gradle builds.

### Steps to reproduce

Take a Godot project that can run on Android.

Enable remote debug

Run project on an Android device.

### Minimal reproduction project

I think any simple project will do, but I used this for testing: 
https://github.com/GodotVR/godot-xr-template

**Comment by Baryonics** [comment]
Same here. Here is the Output when running adb logcat. Maybe it helps somone to figure it out.

![logcat](https://github.com/godotengine/godot/assets/96073324/39c305df-870d-4db4-9e17-767136ee6620)

**Comment by Geometror** [comment]
I just experienced this bug while doing some particle benchmarks on mobile. (no gradle build)
It's not only the print messages: it seems like the debugger wouldn't attach at all (so no profiling, pausing, stopping at breakpoints).

**Comment by m4gr3d** [comment]
> I just experienced this bug while doing some particle benchmarks on mobile. (no gradle build)
> It's not only the print messages: it seems like the debugger wouldn't attach at all (so no profiling, pausing, stopping at breakpoints).

Thanks for the info! This actually gives me an insight into what the issue may be.

**Comment by akien-mga** [comment]
I wonder if this would have been fixed by #84102? Worth checking in 4.2-beta4 when it's out.

**Comment by akien-mga** [comment]
Seems to work fine for me on 4.2-beta5.

Note that I had to enable Deploy With Remote Debug manually, it seems to default to off.

**Comment by altamkp** [comment]
I am on 4.2 stable and the problem still exists, I am using gradle build and have turned on "Deploy With Remote Debug" already.

**Comment by patrykkalinowski** [comment]
This is an error from adb logcat on 4.2 stable:

`USER ERROR: Script Debugger failed to connect, but being used anyway.`
`at: debug (core/debugger/remote_debugger.cpp:406)`

**Comment by Ekaitzsegurola** [comment]
Same error here with 4.2.1, it was returning print messages and i was trying to make work OS.request_permissions (imposible). I tryied set "use gradle build" and sice installation does not matter if i activate or not, it doesnt return any more print message

**Comment by ArchLinus** [comment]
I have this same issue on 4.2.1. I notice when I start up the editor that it says that there is a failure to bind to port 6007.

```
  Cannot listen on port 6007, trying 6008 instead.
  Cannot listen on port 6008, trying 6009 instead.
  Cannot listen on port 6009, trying 6010 instead.
```

In the android export code (`EditorExportPlatformAndroid::run`) the port retrieved through:

```cpp
int dbg_port = EDITOR_GET("network/debug/remote_port");
```

This doesn't account for retries if the editor fails to bind to 6007.

### Workaround

Go to `Editor Settings -> Network -> Debug` and changing the port to the actual debug port.

**Comment by ArchLinus** [comment]
There might be some deeper underlying bug here. These ports remain open even after the editor is closed. I can't even find any process running with these PIDs.

![image](https://github.com/godotengine/godot/assets/126534522/948de1e0-4706-4e02-af6c-2bc5cdad25ce)

![image](https://github.com/godotengine/godot/assets/126534522/a56577cf-d723-42a4-816d-4f9615621ff7)

Searching for the PID in process hacker, it seems that ADB is still running after the editor is closed?

![image](https://github.com/godotengine/godot/assets/126534522/d04c0034-8989-438c-ab2a-67a9ad9cdb76)

**Comment by ernestofs1** [comment]
> I have this same issue on 4.2.1. I notice when I start up the editor that it says that there is a failure to bind to port 6007.
> 
> ```
>   Cannot listen on port 6007, trying 6008 instead.
>   Cannot listen on port 6008, trying 6009 instead.
>   Cannot listen on port 6009, trying 6010 instead.
> ```
> 
> In the android export code (`EditorExportPlatformAndroid::run`) the port retrieved through:
> 
> ```c++
> int dbg_port = EDITOR_GET("network/debug/remote_port");
> ```
> 
> This doesn't account for retries if the editor fails to bind to 6007.
> ### Workaround
> 
> Go to `Editor Settings -> Network -> Debug` and change `Remote Port` to the actual debug port. Before closing the editor switch it back to 6007.

Any one can explain what would the 'actual debug port' be?

**Comment by ArchLinus** [comment]
> Any one can explain what would the 'actual debug port' be?

The actual debug port is the last port last port it attempts to connect to, so in my example log the actual debug port would be 6010.

**Comment by ernestofs1** [comment]
> > Any one can explain what would the 'actual debug port' be?
> 
> The actual debug port is the last port last port it attempts to connect to, so in my example log the actual debug port would be 6010.

Oh ok. I'm doing this on mac. Any idea where I can check for the last port it attempts to connect?

**Comment by Connor-McCloskey** [comment]
Still a problem in 4.2.2. All things Godot and Android, man...just a nightmare.

**Comment by Yolwoocle** [comment]
I'm losing my mind to this issue. This is still a problem in 4.3. Restarting my computer works in order to fix this, but only for a short while. It's getting excruciating at this point, I wonder if there's any workaround before I actually go insane.
