### ISSUE TITLE
Godot leaking massive memory just by itself

### ISSUE THREAD

**Issue by Sighan** [godotengine/godot#82769]
### Godot version

4.1.1 stable

### System information

macOS Montery 12.5.1, 16GB RAM, Forward+ Renderer

### Issue description

When running a project from godot (pressing the play button), the new window will just keep leaking memory, regardless of project size.

The Tests:
I set up a new project, added a scene and tested the following:
- Just a single Node as the scene root, nothing else
- Just a single Node2D as the scene root, nothing else
- Node as Scene Root, then 20 Node2Ds as children
- Node as scene root, then 20 Node2Ds with processing disabled as children
- Finally another run with just a node, to see if it would yield different results as the first run with a single node (it did)

While running the tests I didn't do anything else, just kept the Godot window open in the background.

The Results:
<img width="512" alt="data" src="https://github.com/godotengine/godot/assets/7499888/544bb4dd-3da4-495f-894c-3fb8364d11a7">

I tested every configuration for at least 2 hours, some longer (except for the last one, ran out of time)

As you can see even just an empty scene in an empty project will keep growing in memory usage, my guess is indefinetly. Notably the last test (with an empty scene, containing just an empty Node) grew the fastest. Likewise the tests with 20 Node2Ds yielded similar resuts, regardless of processing being turned on or of. **This leads me to believe that godot itself is leaking memory, not the nodes.**

I will also attach all screenshots I took during those tests, showing my activity monitor (which is apples task manager). You can see how the memory usage changed over time. I tried to take a screenshot about every 30 minutes.

Single Node:

![node-01](https://github.com/godotengine/godot/assets/7499888/58634c10-ffd7-4af6-9406-91e0d3bdefbc)
![node-02](https://github.com/godotengine/godot/assets/7499888/37d03863-53b1-473a-a9bf-be3b69777f23)
![node-03](https://github.com/godotengine/godot/assets/7499888/7beb6239-2f8a-4235-8ee2-d8e422b0acfa)
![node-04](https://github.com/godotengine/godot/assets/7499888/501d11d2-c306-4460-93b0-2a88a6529120)
![node-05](https://github.com/godotengine/godot/assets/7499888/ddd1fe1d-f647-44d2-8fe5-2142ed95ac7c)
![node-06](https://github.com/godotengine/godot/assets/7499888/3bcc371b-f897-47e2-b27d-4759747b1b68)

Single Node2D:

![node2d-1](https://github.com/godotengine/godot/assets/7499888/92ae2108-68e5-49c1-a68b-f0c886b2165c)
![node2d-2](https://github.com/godotengine/godot/assets/7499888/715356b6-9b54-4668-b20c-275d2e582a49)
![node2d-3](https://github.com/godotengine/godot/assets/7499888/e62e75b3-95ac-4e6f-95fe-5ff4c5f5bed6)
![node2d-4](https://github.com/godotengine/godot/assets/7499888/61602a58-0838-47d5-ac63-ce13b756db08)
![node2d-5](https://github.com/godotengine/godot/assets/7499888/601682e4-b659-414d-a7ef-1efab979bdb2)
![node2d-6](https://github.com/godotengine/godot/assets/7499888/fee55d98-1701-452d-a0c1-b255a6861375)
![node2d-07](https://github.com/godotengine/godot/assets/7499888/353f0767-e65d-41c1-a4eb-82d5f3da4dbe)
![node2d-08](https://github.com/godotengine/godot/assets/7499888/86f02f75-00b5-48b6-8945-09f40e799083)
![node2d-09](https://github.com/godotengine/godot/assets/7499888/64065ecf-224d-474d-bfad-66aa7f4c02ff)
![node2d-10](https://github.com/godotengine/godot/assets/7499888/53e54818-844c-4362-9d22-76988d943a42)

20 Node2Ds:

![20node2ds-01](https://github.com/godotengine/godot/assets/7499888/4a28c195-d222-43ba-87b3-02fe357688a3)
![20node2ds-02](https://github.com/godotengine/godot/assets/7499888/fa8ff175-539c-41cf-8a19-e75eb75ce722)
![20node2ds-03](https://github.com/godotengine/godot/assets/7499888/1a6c7770-0212-4264-9cbc-ee4d2246c990)
![20node2ds-04](https://github.com/godotengine/godot/assets/7499888/d1cd68f2-a732-4e54-b87a-efeeffff7121)
![20node2ds-05](https://github.com/godotengine/godot/assets/7499888/7597cd9a-47d9-4805-89d6-047d3d800be0)

20 Node2Ds with processing turned off:

![20node2ds-no-processing-01](https://github.com/godotengine/godot/assets/7499888/eda86a7a-8363-43e6-89e2-9370e887c1f7)
![20node2ds-no-processing-02](https://github.com/godotengine/godot/assets/7499888/3a756b8b-e8b7-4e7c-9d08-ab49c3cd8d6f)
![20node2ds-no-processing-03](https://github.com/godotengine/godot/assets/7499888/d4850045-757c-4a52-b12b-2c90873f39db)
![20node2ds-no-processing-04](https://github.com/godotengine/godot/assets/7499888/4c0453a0-708c-4420-9807-396a479a3194)
![20node2ds-no-processing-05](https://github.com/godotengine/godot/assets/7499888/e5191597-894f-4e42-9a2f-81be9f579471)

Single Node (again after all other tests)

![single-node-finale-01](https://github.com/godotengine/godot/assets/7499888/b95daf3c-7fec-45ae-8972-b26e36668fea)
![single-node-finale-02](https://github.com/godotengine/godot/assets/7499888/5facbf96-1e1d-4c3b-b4a0-521cb3e12939)
![single-node-finale-03](https://github.com/godotengine/godot/assets/7499888/f80bf171-75f2-4dd4-b7c6-06c8156b4c37)
![single-node-finale-04](https://github.com/godotengine/godot/assets/7499888/16067f66-64d9-4d87-bee3-7404d5f166fa)

### Steps to reproduce

Create an empty project. Create an empty scene. Run that project. Observe memory usage growing.

### Minimal reproduction project

[empty-game.zip](https://github.com/godotengine/godot/files/12800252/empty-game.zip)

**Comment by bitsawer** [comment]
Tested on Windows, doesn't seem to leak after a pretty quick test so could be a MacOS issue. Possibly related to https://github.com/godotengine/godot/issues/62507

If you change the renderer to Compatibility (editor button on top right), does the leaking stop or change? When running the project, do the memory stats in bottom panel `Debugger -> Monitors` grow or stay even?

**Comment by Sighan** [comment]
I did a quick test with compability renderer, same result (memory usage starts out lower, but keeps growing regardless). Memory stats in the debugger are steady with both renderers. I will try out the other builds later today and post the results.

**Comment by lostminds** [comment]
Tested in 4.2.dev6 on a M2 Pro macOS 13.6 now and I can see the same issue using both Compatibility and Mobile renderer. Memory seems to be leaking at about 0.1MB/sec according to macOS Activity monitor, both from the run project and just the Godot Project manager when you that. If I toggle on the Update continuously editor setting I can see a similar memory increase for the editor, but not if it's disabled. The leak rate also seems to vary with update rate, as it appears to leak quicker at 120fps than 60fps.

**Comment by bruvzg** [comment]
It seems to be macOS bug, leak seem to happen inside the following calls:
```obj-c++
[NSScreen visibleFrame]
[NSWindow isOnActiveSpace]
```
Both are called every frame, relevant code (`visibleFrame` is called inside `window_get_mode`):
https://github.com/godotengine/godot/blob/b931a6e5ce9897b5716923680dc1c6618312ab3e/platform/macos/display_server_macos.mm#L3564-L3577

**Comment by bruvzg** [comment]
Stack traces for the leaks:

```obj-c++
__CFAllocateObject	
__NSArrayM_new	
+[NSArray array]	
-[NSConcreteMapTable allValues]	
+[_NSFullScreenSpace fullScreenSpaces]	
+[_NSFullScreenSpace visibleFullScreenSpaces]	
+[_NSFullScreenSpace visibleFullScreenSpaceOnScreen:]	
-[NSScreen _hasMenuBar:]	
-[NSScreen _layoutMenuBarHeight]	
-[NSScreen _layoutFrame]	
-[NSScreen visibleFrame]	
DisplayServerMacOS::window_get_mode(int) const	
```

```obj-c++
__CFAllocateObject	
__NSSingleObjectArrayI_new	
+[NSArray arrayWithObjects:count:]	
-[NSWindow _isInSomeVisibleSpace]	
-[NSWindow isOnActiveSpace]	
DisplayServerMacOS::window_can_draw(int) const	
```

**Comment by lostminds** [comment]
Perhaps an option could be to use NSWindows [visible](https://developer.apple.com/documentation/appkit/nswindow/1419132-visible?language=objc) and [occlusionState](https://developer.apple.com/documentation/appkit/nswindow/1419321-occlusionstate?language=objc) properties instead of using the screen visibleFrame and isOnActiveSpace? They seem like a good fit to determine if the window can be drawn to, and might also let us catch some other issues like https://github.com/godotengine/godot/issues/64708

**Comment by bruvzg** [comment]
> Perhaps an option could be to use NSWindows [visible](https://developer.apple.com/documentation/appkit/nswindow/1419132-visible?language=objc) and [occlusionState](https://developer.apple.com/documentation/appkit/nswindow/1419321-occlusionstate?language=objc) properties

This seems to be working, not sure if both `isVisible` and `occlusionState` checks are necessary (`occlusionState` check alone seems to be enough), will test various scenarios a bit later. But it's not leaking.

https://github.com/godotengine/godot/pull/83096

**Comment by PMach17** [comment]
> > I am still experiencing this memory leak, using Compatability on Macbook Pro
> > I'm on: monitor.v4.2.stable.official
> 
> This is not related leak, ANGLE Compatibility backend is broken and causing it, ANGLE was disabled in 4.2.1.
> 
> If you want to use Compatibility renderer in 4.2 (why?), go to the `Project settings` → `Rendering` → `GL Compatibility` → `Driver.macos` and set it to `opengl3`.


_I'm experiencing similar problem. Even with simple scene with timer, label and a script that changes the label every 10s._

<img width="305" alt="screenshot1" src="https://github.com/godotengine/godot/assets/33704010/4afd61a6-a342-4024-a824-b61ad344013b">

I tried this and it did help to a point where it didn't stop the growth of memory usage but it did slow it down to around 0.1Mb/5s. Before changing this it was about 10Mb/5s.
