### ISSUE TITLE
Missing cases of Variant type syntax highlighting

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#82775]
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

The type Variant is does not get highlighting in the following situations:

```
signal my_signal(arg:Variant)
```
![image](https://github.com/godotengine/godot/assets/1212509/8a06dbc1-cced-4d3f-8dc8-bedba345232b)

```
func _ready() -> void:
	var _x := func(a:Variant) -> void:
		prints(a)
```

![image](https://github.com/godotengine/godot/assets/1212509/36a325b6-ec5d-4cab-b507-093ceae9ea18)

### Steps to reproduce

In any script declare a signal with a explicitly typed Variant parameter, or declare an anonymous "lambda" method with a Variant parameter as shown above, and observe the lack of syntax highlighting for the Variant token.

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
* Fixed by #82516 (not included in 4.2 dev 6).
