### ISSUE TITLE
Startup error messages: `GDScript bug: Native class "" not found`

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#82771]
### Godot version

57a6813bb8bc2417ddef1058d422a91f0c9f753c

### System information

Windows 11

### Issue description

![image](https://github.com/godotengine/godot/assets/3036176/0424573b-f391-4e12-8e70-a248c35bbb4b) 
spawns at startup in my project after the https://github.com/godotengine/godot/pull/82294 got merged.

### Steps to reproduce

Currently, I don't want to publish the whole project source (and it's huge), and I didn't find the code part which cause this bug. (It has lots of global classes and tool scripts).
Perhaps other users have encountered this too and they can clarify about what cause this.

### Minimal reproduction project

N/A

**Comment by produno** [comment]
I am also getting the same. Not entirely sure where the issue is yet though. If i manage to find anything i will update.

**Comment by dalexeev** [comment]
Do you have an autoload scene with no script attached to the root node, with Singleton checkbox enabled, and (probably) the identifier should be used in GDScript?

**Comment by produno** [comment]
> Do you have an autoload scene with no script attached to the root node, with Singleton checkbox enabled, and (probably) the identifier should be used in GDScript?
> 
> MRP: [EmptyNativeClass.zip](https://github.com/godotengine/godot/files/12803267/EmptyNativeClass.zip)

Just an FYI @dalexeev, the linked pull request does fix the issue, but i don't have any autoload scenes without any scripts attached. I do however have lots of autoloads that are just scripts.

I also now get this error ```ERROR: Parameter "common_parent" is null.```
