### ISSUE TITLE
range(n) allocates reals instead of integers

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8278]
Why do I have to cast r?
`print(rs.find(1))` will return -1 without it.

```
func _ready():
	var rs = []
	
	for r in range(2):
		rs.append(int(r))
		#rs.append(r)
		
	print(rs.find(1))
```

Ubuntu
Master branch

**Comment by akien-mga** [comment]
I don't know if that's truly a bug, as range does support floats with e.g. `range(0, 2, 0.1)`, but indeed when using `range(n)` one would expect integers I guess.

```
func _ready():
	for i in range(2):
		print(typeof(i) == TYPE_INT)
		print(typeof(i) == TYPE_REAL)
```
outputs
```
False
True
False
True
```

**Comment by akien-mga** [comment]
After discussing with @bojidar-bg and @StraToN, actually `range` is not supposed to support floats, so `range(0, 2, 0.2)` would not work as one would expect (`0.2` would be cast to int). And that's good this way.

But then I don't know why the returned value is an array of floats. The implementation uses ints: https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_functions.cpp#L710

**Comment by reduz** [comment]
it's not returning an array of floats, it' s using the values inside a
Vector3 to iterate :P It's kind of a hack.. maybe it should simply convert
the iterator to integer upon return.
