### ISSUE TITLE
FSR 2.2 causes CPU Time to continuously increase until editor becomes unusable.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#82791]
### Godot version

4.2 dev 6

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

Firstly I have no idea how to reproduce this. I just don't know which combination of settings it is.

It happens almost 100% of times, sometimes it just doesn't happen immediately until I reload the project.

If I leave my project open and go take a shower it slowly climbs up to 40ms for the cpu time and then the project is unusable since it's very slow to do anything in it.

If I switch scaling to FSR 1 or bilinear then it doesn't happen but I can also disable some settings such as MSAA and Screen Space AA (it has to be both enabled together with FSR2.2 to start increasing the CPU Time that's the least I can tell right now) and then the CPU time goes slowly down. Though I'm not 100% sure the MSAA and SSAA have anything to do with it, it's hard to tell right now.

You definitely need to ahve something on screen, couple models otherwise I don't really know if it even kicks in or more like it might be taking hours just to see small change in the cpu time.

It happens in just couple seconds/minutes.

I can show a video if you want to see it in action, I really can't pinpoint how to make a minimal reproduction project with this issue.

### Steps to reproduce

Currently no idea.
(I maxed all rendering settings I could find, world environment maxed out too, panorama sky included, but even if I turn the world environment stuff off it doesn't change the issue, only FSR2.2 consistently makes this happen or not as far as I can tell.)

### Minimal reproduction project

None for now and who knows if I'll even be able to make one. My current project uses models which I can't share.

EDIT: I don't know how to reproduce this but if needed I can stream it and show you whatever you need in my small test project as you ask.

**Comment by DarioSamo** [comment]
It sounds like it's probably related to https://github.com/godotengine/godot/pull/82451 if you can test it out.

**Comment by viksl** [comment]
I'll try it just in case it matters though, I have TAA disabled in my project. The fix seems to be related to TAA though, should I still give it a try?

**Comment by DarioSamo** [comment]
> I'll try it just in case it matters though, I have TAA disabled in my project. The fix seems to be related to TAA though, should I still give it a try?

Absolutely, both shared the same problem as the code path is shared between them.

**Comment by viksl** [comment]
I downloaded the windows editor artifact and I can no longer reproduce it as far as I can tell from couple tests right now. If anything I think the scene is even slightly faster than it was before :D.

So for now thank you very much!

I'll be testing it more when it gets merged into the next dev version I assume in couple weeks but so far it's great apart from a bit of shimmering on models which I assume is related to fsr itself and not this and probably normal artifact of the algorithm I assume (?).

Again, thanks a lot!

**Comment by DarioSamo** [comment]
> I'll be testing it more when it gets merged into the next dev version I assume in couple weeks but so far it's great apart from a bit of shimmering on models which I assume is related to fsr itself and not this and probably normal artifact of the algorithm I assume (?).

I've not been able to find a way to reduce the shimmering so I believe similarly it's inherent to it as DLSS doesn't exhibit the same issues with the same jittering configuration. That said, if FSR 3 rolls out with any improvements to the upscaling part, maybe we'll be lucky and get some progress there.

**Comment by viksl** [comment]
Should I close this as resolved?

--------------
Btw, what I meant by shimmering is this: https://youtu.be/R9q7rnSjtgo
(Unfortunately the video did not capture it entirely, most of the shimmering is not ivisble in the video but check what is visible and then look at the areas I highlight with the mouse cursor, the entire area does it)

**Comment by DarioSamo** [comment]
> Should I close this as resolved?

You can just leave it open until the fix is merged. That way other people can see it if they run into the same problem.

> Btw, what I meant by shimmering is this: https://youtu.be/R9q7rnSjtgo (Unfortunately the video did not capture it entirely, most of the shimmering is not ivisble in the video but check what is visible and then look at the areas I highlight with the mouse cursor, the entire area does it)

Yup, for the most part this is pretty much on FSR's side as the implementation only links the resources it asks for and runs the library. It's not much unlike the artifacts that show up in other games that use it. We might look into ways of improving it if it's doable though.
