### ISSUE TITLE
Godot 4.2 dev6, Compatibility mode, shadows opacity not working

### ISSUE THREAD

**Issue by salciunas** [godotengine/godot#82807]
### Godot version

4.2 Dev 6

### System information

Godot v4.1.1.stable - Linux Mint 21.2 (Victoria) - Vulkan (Compatibility) - GeForce GT 525M (nvidia; 390.157) - Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz (8 Threads)

### Issue description

**Shadows** are still not working in **compatibility mode**; when **changing opacity**, _it's only visible on the editor_; when running _DEBUG mode, opacity becomes darkness_. Attaching images and project files

P.S. I only worked in compatibility mode with Godot, so maybe I don't know what to press to make shadows work. Sorry then.

### Steps to reproduce

![Screenshot from 2023-10-04 20-47-47](https://github.com/godotengine/godot/assets/98655671/7c2682d5-e795-4ff3-b623-00401e6eac24)
![Screenshot from 2023-10-04 20-47-59](https://github.com/godotengine/godot/assets/98655671/a879eb36-8588-42f5-a826-27f01a89fc07)

### Minimal reproduction project

[Test level.zip](https://github.com/godotengine/godot/files/12806817/Test.level.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82503. Shadow opacity does work, but directional shadow rendering only works in the editor currently.
