### ISSUE TITLE
GLTF importer does not read the "matrix" property for nodes

### ISSUE THREAD

**Issue by karai17** [godotengine/godot#82825]
### Godot version

4.1.2

### System information

Godot 4.1.2

### Issue description

I am generating valid GLTF files from raw model data. The Node transforms in my data come in mat4 format so I have been using the `node.matrix` property to dump that data in. My GLTF file loads perfectly fine in Blender, but does not load properly in Godot. After many, many hours of tinkering, of which I will spare the details, the primary issue ended up being that Godot just doesn't read the `matrix` property and I had to decompose my matrix into the TRS values. I suspect this omission is due to Blender spitting out GLTF files with TRS properties and never the matrix property, and an assumption that Godot users will primarily be using Blender.

### Steps to reproduce

1. Generate or modify a valid GLTF file such that the nodes use the `matrix` property rather than the TRS properties
2. Import model into Godot
3. Model should now have a very strange structure presumably from default TRS values being used rather than the provided matrix

### Minimal reproduction project

TRS model (expected behaviour)
[buma.zip](https://github.com/godotengine/godot/files/12811820/buma.zip)

Matrix model (unexpected behaviour)
[buma (2).zip](https://github.com/godotengine/godot/files/12811839/buma.2.zip)

Ignore the orientation of the model~

**Comment by aaronfranke** [comment]
This seems to be specifically a problem with skeletons. And the current code is bogus:

```cpp
			skeleton->set_bone_rest(bone_index, node->xform);
			skeleton->set_bone_pose_position(bone_index, node->position);
			skeleton->set_bone_pose_rotation(bone_index, node->rotation.normalized());
			skeleton->set_bone_pose_scale(bone_index, node->scale);
```

There is no reason where we would ever read these properties separately. In fact, I think they should be unified, with `GLTFNode` only storing one transform.
