### ISSUE TITLE
vehicleWheel.get_translation() return wrong position

### ISSUE THREAD

**Issue by x-channel** [godotengine/godot#82822]
### Godot version

3.6 custom build.

### System information

Windows 11 on OpenGL ES 3

### Issue description

I'm try to implement force feedback in Godot, the single difference between master branch and my FFB branch is input_default.h input_default.cpp, input.h, input.cpp, joypad_windows.h and joypad_windows.cpp to send data to joystick.

For track wheel direction collision I need to get wheel position, but all wheel return same position, the Rear Right Wheel's position.

You could try this downloading from my github.

![godot bug](https://github.com/godotengine/godot/assets/6591496/fa3a38f3-d697-468b-9530-f84696f2b941)

### Steps to reproduce

Build car, add 4 wheel in different positions, add this car in main scene.

Try to printt() position of the wheels.

### Minimal reproduction project

If previous steps work property, try to download this project and click pause button.
[Force Feedback Test Minimal.zip](https://github.com/godotengine/godot/files/12810979/Force.Feedback.Test.Minimal.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/63657.

> I'm try to implement force feedback in Godot, the single difference between master branch and my FFB branch is input_default.h input_default.cpp, input.h, input.cpp, joypad_windows.h and joypad_windows.cpp to send data to joystick.

If you are looking to upstream this work, consider joining the [Godot Contributors Chat](https://chat.godotengine.org/)'s `#input` channel :slightly_smiling_face:

**Comment by x-channel** [comment]
> Thanks for the report! Consolidating in #63657.
> 
> > I'm try to implement force feedback in Godot, the single difference between master branch and my FFB branch is input_default.h input_default.cpp, input.h, input.cpp, joypad_windows.h and joypad_windows.cpp to send data to joystick.
> 
> If you are looking to upstream this work, consider joining the [Godot Contributors Chat](https://chat.godotengine.org/)'s `#input` channel 🙂

I need to solve too much things before Pull Request.
