### ISSUE TITLE
Invalid call. Nonexistent function 'new' in base 'JNISingleton'

### ISSUE THREAD

**Issue by yan88a** [godotengine/godot#82827]
### Godot version

4.1.1

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 27.20.100.9664) - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

When creating a new image and debugging it on android device - get the following error:
Invalid call. Nonexistent function 'new' in base 'JNISingleton'

### Steps to reproduce

create - 
var image = Image.new()
run it anywhere in code via android device.

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
`Image` instances are intended to be created from `Image.create`, `Image.create_from_data` static functions or `Texture.get_image`, calling the constructor make no sense now.

**Comment by yan88a** [comment]
@Chaosus  well,
the Image.create and Image.create_from_data()
return the same error..

**Comment by bouncymarble** [comment]
@yan88a I had the exact same error when testing my app with the GodotGetImagePlugin. I believe this is due to the minSdkVersion you set in the .aar file you gave me, it's set to 24. When testing back the old plugin (v0.1.2 - the one that doesn't work on android 13) and setting minSdkVersion to 21 in the export template, Image.new() works again. So I think you just have to change the AndroidManifest of the plugin (v0.1.2 has minSdkVersion="18"), unless your app requires a higher sdk version.

**Comment by yan88a** [comment]
@bouncymarble  - thanks! - ill give it a shot :)
if it will work -> ill send the new version ;)

**Comment by yan88a** [comment]
@bouncymarble  - nope - its not that...
tried with a lower sdk (both project & plugin..)
seems that its more of an editor issue - since it happens unrelated as well (trying to create an image out of context)

in any case - i sent you the updated gdap in the other tread. 
fingers crossed it will work (for me on 4.1.2 it returns an object)

**Comment by bouncymarble** [comment]
@yan88a Hmm yeah it has nothing to do with the min sdk version, I didn't know you named the photo picker plugin "Image", I'm pretty sure it's because of that. It works for me when I disable the plugin. So as I told you in the other thread, you should rename it. Hope it works.

**Comment by akien-mga** [comment]
Closing as this seems to be specific to a thirdparty plugin. This should be reported on that plugin's repository.

**Comment by yan88a** [comment]
fair.
thanks @bouncymarble - will update in the plugin repository. 
sorry for the white noise here
