### ISSUE TITLE
AnimationPlayer now resets on every frame it is called

### ISSUE THREAD

**Issue by zapposh** [godotengine/godot#82828]
### Godot version

4.2 dev 6

### System information

Windows 11

### Issue description

Prior to Godot 4.2 dev 6, calling play("animation") on an animation repeatedly simply continues playback of the animation.

In Godot 4.2 dev 6, repeatedly calling a looping animation causes it to restart/reset every time it is called.

`func _process(delta):
$AnimationPlayer.play("animation_name")`

For ex. the above example now restarts at 0 on every frame.

### Steps to reproduce

- Create a new project in Godot 4.2 dev 6
- Add an AnimationPlayer node to your scene, and create a looping animation for a parameter of your choice.
- Playing the animation in the editor works as expected
- Create a script to call the animation at regular intervals (for ex. every frame)
- Press F5 to launch run the project -> now the animation player resets to 0 on every call

### Minimal reproduction project

N/A

**Comment by sepTN** [comment]
I'm hit by this bug as well. When I tried to open my project with 4.2 dev 6 I noticed that my pawns aren't properly animating. But when I switch on my older compile, it does properly animating and no longer freeze in their frame 0. Could be a regression somewhere.
