### ISSUE TITLE
Deterministic chain of random values in particle shader can be broken when turbulence is used

### ISSUE THREAD

**Issue by greycheeked** [godotengine/godot#82837]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 SUPER (NVIDIA; 31.0.15.3130) - Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 Threads)

### Issue description

The error is basically known: A random value is generated within an IF-THEN-block. As soon as the condition for IF changes, all subsequent random values change once.
This concerns the following location (turbulence):

```
if (!COLLIDED) {
	float vel_mag = length(VELOCITY);
	float vel_infl = clamp(mix(turbulence_influence_min, turbulence_influence_max, rand_from_seed(alt_seed)) * turbulence_influence, 0.0, 1.0);
	VELOCITY = mix(VELOCITY, normalize(noise_direction) * vel_mag * (1.0 + (1.0 - vel_infl) * 0.2), vel_infl);
}
```
I think the right thing to do would be to pull the random value before IF:
```
float turbulence_influence_rand = rand_from_seed(alt_seed);
if (!COLLIDED) {
	float vel_mag = length(VELOCITY);
	float vel_infl = clamp(mix(turbulence_influence_min, turbulence_influence_max, turbulence_influence_rand) * turbulence_influence, 0.0, 1.0);
	VELOCITY = mix(VELOCITY, normalize(noise_direction) * vel_mag * (1.0 + (1.0 - vel_infl) * 0.2), vel_infl);
}

```

### Steps to reproduce

I found the error directly in the source code.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
cc @RPicster @QbieShay

**Comment by clayjohn** [comment]
Will be fixed by https://github.com/godotengine/godot/pull/79527
