### ISSUE TITLE
Sub-nodes/child nodes added by plugin tool script are invisible

### ISSUE THREAD

**Issue by jgao222** [godotengine/godot#82836]
### Godot version

4.1.1stable

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 30.0.101.1692) - Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 Threads)

### Issue description

I want to dynamically create some nested nodes after pressing a button in a dock added by a plugin. I have a tool script attached to a button in a dock scene with the following:
```gdscript
@tool
extends Button

func _on_pressed():
    var p = Node3D.new()
    p.name = "parent"
    var c = Node3D.new()
    c.name = "child"
    var root = EditorPlugin.new().get_editor_interface().get_edited_scene_root()

    root.add_child(p)
    p.set_owner(root)
    p.add_child(c)
    c.set_owner(p)

    print("root has " + str(root.get_child_count()) + " children")
    print("p has " + str(p.get_child_count()) + " children")
```

The second print confirms that `p` has 1 child, but the editor tree shows:
![image](https://github.com/godotengine/godot/assets/35200140/7bc2c40b-0930-4100-9f8e-a259c312390c)

### Steps to reproduce

1. Create a new project with a plugin script and a button in the bottom panel (`add_control_to_bottom_panel`)
2. Create a new scene with a Node3D root and open it.
3. Set button `pressed()` signal to a new script for the button
4. In the script, create two `Node3D`s with `.new()`
5. As in code snippet in description, add the first node to the scene root and set its owner to scene root. Then add second node as child of first node and set its owner to the first node.
6. Reload the editor
7. Navigate to the bottom panel, press the button, observe that only one additional node is shown in the editor tree and there is no dropdown to expand.

### Minimal reproduction project

[reprod_example.zip](https://github.com/godotengine/godot/files/12815064/reprod_example.zip)

**Comment by jgao222** [comment]
Just found that `c.set_owner(root)` results in the expected behavior. I can't find any documentation saying that one has to set the node's owner to the root node though. Docs for `set_owner` say
> The node owner. A node can have any ancestor node as owner (i.e. a parent, grandparent, etc. node ascending in the tree).
and that
> If a new node is added to the tree without setting its owner as an ancestor in that tree, it will be visible in the 2D/3D view, but not in the scene tree (and not persisted when packing or saving).
I think it is reasonable that the direct parent of a node would count as an ancestor of it, so it is still confusing that it doesn't show up in the editor.

**Comment by Mickeon** [comment]
This is intentional...

> Just found that `c.set_owner(root)` results in the expected behavior. I can't find any documentation saying that one has to set the node's owner to the root node though. 

...And it would be better documented by https://github.com/godotengine/godot/pull/68560
