### ISSUE TITLE
Always crashes 

### ISSUE THREAD

**Issue by PUNKMAN07** [godotengine/godot#82840]
### Godot version

4.1

### System information

Windows 10

### Issue description

It's just craches I don't know 

### Steps to reproduce

Opening or just doing enething 

### Minimal reproduction project

I don't know what to put here

**Comment by YuriSizov** [comment]
Hey there! I'm sorry to hear that, but based on this report we can do nothing. You need to provide a minimal reproduction project that causes crashes for you. It would also be useful if you could run the `.console.exe` executable and see what it prints when the engine crashes.

Other details about your system can be helpful as well, such as your CPU and GPU, how old your drivers are, etc.

**Comment by YuriSizov** [comment]
> Using godot console, it closed so fast because both godot editor and console crashing to desktop.

Thanks for reporting. You need to open the command line interface (CMD, PowerShell, Windows Terminal) and launch it from that. Then the logs will persist.

**Comment by muraqqi** [comment]
> > Using godot console, it closed so fast because both godot editor and console crashing to desktop.
> 
> Thanks for reporting. You need to open the command line shell (CMD, PowerShell, Windows Terminal) and launch it from that. Then the logs will persist.

hi, i found that this is happen on forward+ and mobile renderer mode. Here i attaching the console log of both renderer. I thinking this is happen on new updated win 10 os and newest amd driver version 23.9.3. Will check if rolling back to previous driver will eliminate the error.

[Godot Forward Plus Console.txt](https://github.com/godotengine/godot/files/12864944/Godot.Forward.Plus.Console.txt)
[Godot Mobile Console.txt](https://github.com/godotengine/godot/files/12864945/Godot.Mobile.Console.txt)

**Comment by muraqqi** [comment]
Hi, after uninstall and reinstall GPU driver from 23.9.1 to 23.9.3. Finally found the culprit, because i using APU with vega based architecture. Turn out i haven't installed the APU driver for Vega. After installing it godot works and can use Forrward+ and Mobile renderer. Maybe it can happen to intel graphic too, beside installing GPU driver for discrete gpu try to install igpu driver too.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

**Comment by IvanSt24** [comment]
I have this problem and i am concerned that the gpu and the cpu arent working well together because the gpu is almost brand new(Ryzen 5 7600) and the gpu is rx 570 8GB i updated the amd driver to the latest but i cant run the engine in mobile renderer.

**Comment by Calinou** [comment]
@IvanSt24 Make sure your graphics drivers are up-to-date from AMD's website, and double-check that your monitor is connected to your dedicated graphics card (and not the port on your motherboard).
