### ISSUE TITLE
Disabling depth prepass in the Project Settings breaks opaque material rendering

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#82860]
- *Related to https://github.com/godotengine/godot/issues/82637.*

### Godot version

4.0.stable, 4.1.1.stable, 4.2.dev fe8a58b9d

### System information

Godot v4.2.dev (fe8a58b9d) - Fedora Linux 38 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.113.01) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Disabling depth prepass in the Project Settings breaks opaque material rendering. All opaque objects will no longer be rendered until the project is reloaded.

This occurs both in the editor and running project (if toggling the project setting's value with a script).

https://github.com/godotengine/godot/assets/180032/1c7f0d3c-e963-4cf7-a87e-741f495d7dcb

### Steps to reproduce

- Use the Forward+ rendering method. (I can't reproduce this when using the Compatibility rendering method, but toggling the setting makes no performance difference there. Does the setting have an effect when using Compatibility?)
- Disable **Rendering > Driver > Depth Prepass > Enable** in the Project Settings, or use the following in a script:

```gdscript
ProjectSettings.set_setting("rendering/driver/depth_prepass/enable", not bool(ProjectSettings.get_setting("rendering/driver/depth_prepass/enable")))
```

### Minimal reproduction project

[test_depth_prepass.zip](https://github.com/godotengine/godot/files/12820548/test_depth_prepass.zip)

**Comment by clayjohn** [comment]
Is the setting set to restart when changed (I.e. using GLOBAL_DEF_RST)? It requires a restart after changing or else all opaque materials will be broken

**Comment by Calinou** [comment]
> Is the setting set to restart when changed (I.e. using GLOBAL_DEF_RST)? It requires a restart after changing or else all opaque materials will be broken

No, but I remember the setting being changeable without having to restart. I guess this is no longer the case due to changes done around `discard;` in materials.

**Comment by clayjohn** [comment]
> > Is the setting set to restart when changed (I.e. using GLOBAL_DEF_RST)? It requires a restart after changing or else all opaque materials will be broken
> 
> No, but I remember the setting being changeable without having to restart (this was [when I initially added the option](https://github.com/godotengine/godot/pull/55386)). I guess this is no longer the case due to some internal optimizations.

Ya, that's right

**Comment by Lunarisnia** [comment]
I would love to fix this. Can I get assigned to this issue?

**Comment by Calinou** [comment]
> I would love to fix this. Can I get assigned to this issue?

For future reference, we only use the assignees feature for core contributors (and we don't always use it in the first place). Since contributors can leave at any time for any reason, we'd rather avoid a situation where nobody is working on an issue because it's assigned to someone who is no longer active.

**Comment by Lunarisnia** [comment]
Sounds great. Thank you for the info
