### ISSUE TITLE
Cannot set mouse mode in autoload script C#

### ISSUE THREAD

**Issue by bar-ji** [godotengine/godot#82862]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3203) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Setting the value of Input.MouseMode inside of an autoload script's "_Ready" method seemingly does nothing.

### Steps to reproduce

*INSIDE OF AUTOLOADED SCRIPT*

public override void _Ready()
{
    Input.MouseMode = Input.MouseModeEnum.Captured;
}

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I can't reproduce, it works fine for me with this script:
```csharp
using Godot;
using System;

public partial class AutoLoad : Node
{
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		GD.Print("loaded");
		Input.MouseMode = Input.MouseModeEnum.Captured;
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
	}
}
```

Note that autoloaded scripts need to inherit Node (and of course should be compiled).

**Comment by bar-ji** [comment]
Weirdly works today. Must've been a restart that fixed it.
