### ISSUE TITLE
Cannot select an AnimatedSprite3D node by clicking on it in the scene view

### ISSUE THREAD

**Issue by lorenzokerbrat** [godotengine/godot#82873]
### Godot version

Godot v4.1.1.stable.mono

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

An AnimatedSprite3D node (with a SpriteFrames) cannot be selected by clicking on its sprite in the scene view.

It can be selected by clicking on it in the node hierarchy. This issue is essentially about usability/QOL.
The use case would be, for example, making a 2.5D-style game where a lot of AnimatedSprite3Ds are its main actors and props.

It is still possible to select a Sprite3D node by clicking on it in the scene view, which is why I'm reporting this as a bug.

### Steps to reproduce

In the reproduction project,

1. Open the scene named node_3d.tscn => It should have an AnimatedSprite3D visible at the origin.
2. In the scene view, click on the sprite => The node is not selected.

### Minimal reproduction project

[AnimatedSprite3DBug.zip](https://github.com/godotengine/godot/files/12821341/AnimatedSprite3DBug.zip)

**Comment by Mickeon** [comment]
Can a normal Sprite3D be selected just fine?

**Comment by lorenzokerbrat** [comment]
> Can a normal Sprite3D be selected just fine?

Yes, but not AnimatedSprite3D
