### ISSUE TITLE
Can disconnect inherited signals

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#82874]
### Godot version

0ca8542329888e8dccba89d59d3b728090c29991

### System information

Windows 11

### Issue description

In the node menu under the signals option, the 'disconnect' is clickable for signals which are inherited from other scenes, which is not correct behaviour since those signals cannot actually be deleted (they will reappear upon scene reload).
![godot windows editor dev x86_64_6HDNxCBgBk](https://github.com/godotengine/godot/assets/12756047/38084a6c-0044-46ef-a403-8a676b6ac3d3)

### Steps to reproduce

* Create a scene.
* Connect a signal to another node
* Create a new scene which inherits from the previous scene.
* Attempt to disconnect the signal.

### Minimal reproduction project

N/A

**Comment by Mickeon** [comment]
Heh. I remember last year KoBeWi pointed it out to me.
