### ISSUE TITLE
Importing Blender .blend Files Softlocks Godot Editor (Arch Linux)

### ISSUE THREAD

**Issue by Jazztache** [godotengine/godot#82888]
### Godot version

v4.1.1.stable.arch_linux

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.104.05) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

On Arch Linux, Godot cannot import Blender files directly.
Blender path is `/usr/bin/`.

It instead tries to repeatedly import the Blender file, to no avail. 

This error is outputted repeatedly.
```
modules/gltf/gltf_document.cpp:7432 - Condition "err != OK" is true. Returning: ERR_FILE_CANT_OPEN
Error importing 'res://cube.blend'.
```

Can confirm this works with an without launching Godot with `sudo` privileges

### Steps to reproduce

1. Run Godot with or without `sudo` privileges; Make sure your path is `/usr/bin/` so it can find Blender.
2. Create a new Godot project.
3. Create the default Blender cube as a file. Literally just open Blender and save the default file.
4. Import the default cube file using the system file manager.
5. Godot softlocks with the error message above. It repeats until the program is closed.

Attached is a reproduction video

https://github.com/godotengine/godot/assets/97380337/c205c463-1a6b-4a66-911f-e0926eb6a08f

### Minimal reproduction project

[Godot 4.1 Cannot Import Blend Files.zip](https://github.com/godotengine/godot/files/12826113/Godot.4.1.Cannot.Import.Blend.Files.zip)

**Comment by Jazztache** [comment]
Side note: Even copying the Blender binary to a new folder, giving it user perms, and then setting the binary's folder to to be the Blender path for Godot causes the bug to happen. Doesn't matter what Blender file you give it, or where the binary is, and it doesn't seem like which user the binary file is assigned to matters. It just does this softlock.

**Comment by aaronfranke** [comment]
I did a quick test and it imports fine on macOS, so it may be a platform-specific issue.

**Comment by chefnaphtha** [comment]
can repro, also on arch

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/76338.
