### ISSUE TITLE
mouse_enter signal doesn't fire when mouse is held

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8288]
**Operating system or device - Godot version:**
2.1 stable

**Issue description:**
Title

**Steps:**
Create two buttons with 2 signals
```
	var button = Button.new()
	button.set_text("Tests")
	add_child(button)
	button.connect("mouse_enter", self, "tab_over", [button])

func tab_over(button):
	print("Fire!!!")
```

Click on one button and hold down the left mouse button, then slowly go over over the adjacent button. `mouse_enter`'s signal isn't emitted.

Can't think of this being intended, but posting this because it seems to me anyway that it should still fire.

**Comment by Hinsbart** [comment]
@Dillybob92 You already opened #6362 for this a few months ago :P
So closing..

**Comment by Dillybob92** [comment]
@Hinsbart Oh wow, 8 months ago... time flies. Oops
