### ISSUE TITLE
Memory leak for the objects storing self reference

### ISSUE THREAD

**Issue by giddycodedev** [godotengine/godot#82882]
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.3623) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Hi,
I have created custom class extending RefCounted type. Mentioned class does have a variable storing the reference to itself. 

```
class_name Mem
extends RefCounted


var a := "a"
var b : Mem


func _init() -> void:
    b = self

```

When I create an object of that class in _process i can see the number of objects growing. 

```
func _process(delta: float) -> void:
    var mem : Mem
    var memfine : MemFine
    print("OBJ COUNT BEFORE: ",Performance.get_monitor(Performance.OBJECT_COUNT))
    # Self referencing triggers memory leak
    mem = Mem.new()
    #memfine = MemFine.new()
    print("OBJ COUNT AFTER : ",Performance.get_monitor(Performance.OBJECT_COUNT))

```

I would expect Godot to clear the references and keep  the number of objects at the same level.

### Steps to reproduce

Run the scene from attached project and observe how object count is growing

### Minimal reproduction project

[MemLeak.zip](https://github.com/godotengine/godot/files/12825215/MemLeak.zip)

**Comment by dalexeev** [comment]
I think this is intentional, self references is no different than other ones. Use `weakref()` or don't store the reference in a variable.

**Comment by giddycodedev** [comment]
I see,
If this is an expected behavior of reference counting GC, maybe would be good to mention in official doc the fact that self-referential constructs are prone to memory leaks. If we feel this is not needed we can close this issue
