### ISSUE TITLE
4.2dev6 GraphNode no close button and close_request signal

### ISSUE THREAD

**Issue by cyberpsyche** [godotengine/godot#82909]
### Godot version

Godot 4.2 dev6

### System information

MacOS 10.15.7 (19H2) Intel Iris Graphics 6100 1536 MB

### Issue description

There is a show_close option on GraphNode in 3.X ，but cannot find a counterpart in 4.2dev6. And there is no close_request signal on GraphNode while the latest 4.2 Document said there is a close_request() signal in GraphElement. 

How to handle this issue?  

### Steps to reproduce

no content

### Minimal reproduction project

no content

**Comment by kleonc** [comment]
Seems these were removed intentionally in #79311, see: https://github.com/godotengine/godot/pull/79311#issuecomment-1701027224. cc @Geometror

**Comment by YuriSizov** [comment]
The button was removed intentionally. You can add it if you need it using the new HBoxContainer used for the titlebar.
And the signal has been renamed to `delete_request`, the online documentation is just slightly out of date with all the recent changes.

**Comment by cyberpsyche** [comment]
> The button was removed intentionally. You can add it if you need it using the new HBoxContainer used for the titlebar.
> 
> And the signal has been renamed to `delete_request`, the online documentation is just slightly out of date with all the recent changes (we usually synchronize it over the weekend). You can find the most accurate documentation in the class reference directly in the editor.

Thank you so much~
