### ISSUE TITLE
Functional improvement error "unable to initialize vulkan video driver"

### ISSUE THREAD

**Issue by ximokom** [godotengine/godot#82908]
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

v4.2.dev6.official [57a6813bb]

### Issue description

When you run godot 4 on a poor graphics you get this error and how to solve it to force opengl3.

That forces you to create a shortcut, which is not a problem but I have seen some users who only see that godot does not work for them.

I think it would be interesting if once the error screen was displayed, pressing ok would force godot to load in opengl3.

If the user does not want the annoying message, they just have to follow the instructions in the message. :-)

### Steps to reproduce

Running a project from Godot with an old graphics card.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Thanks for the suggestion!

This seems to be the same proposal as #58927 so I'll close it as duplicate to consolidate there.
