### ISSUE TITLE
Cannot Unwrap UV2 of PrimitiveMeshes

### ISSUE THREAD

**Issue by sandsalamand** [godotengine/godot#82904]
### Godot version

Godot v4.1.1.stable.mono

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 30.0.15.1123) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

The GUI option to "Unwrap UV2 for Lightmap/AO" doesn't work. A popup appears saying "Contained mesh is not of type ArrayMesh".

### Steps to reproduce

1. Place a MeshInstance3D in the scene. Click on its mesh property, and choose any primitive shape.
2. Click the mesh button in the top bar, then click "Unwrap UV2 for Lightmap/AO".

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/latest/tutorials/3d/global_illumination/using_lightmap_gi.html#generating-uv2-for-primitive-meshes)

**Comment by sandsalamand** [comment]
@AThousandShips I instinctively closed this because I wasn't at a computer to check, but there is no option to "Add UV2" in the inspector for a primitive mesh.
![image](https://github.com/godotengine/godot/assets/38278077/85abf994-c99e-4fc6-8a7b-721dfb010fc1)

**Comment by Calinou** [comment]
You need to click the Mesh property's value in the inspector to expand the PrimitiveMesh properties.

**Comment by sandsalamand** [comment]
@Calinou Got it. Could that be added to the "Mesh" dropdown like the "Unwrap UV2" button, or does that dropdown have to be the same for all MeshInstance3Ds?

**Comment by Calinou** [comment]
> @Calinou Got it. Could that be added to the "Mesh" dropdown like the "Unwrap UV2" button, or does that dropdown have to be the same for all MeshInstance3Ds?

Done: https://github.com/godotengine/godot/pull/82937
