### ISSUE TITLE
Editor: Startup stuck on Black Screen (before seeing Projects)

### ISSUE THREAD

**Issue by brill12** [godotengine/godot#82919]
### Godot version

4.1.1 (default steam branch and mono)

### System information

Windows 11 Home (10.0.22621 Build 22621), I7 10870H (64bit) + 3080 Laptop, 

### Issue description

The Editor is stuck on a black screen. This happens even after reinstall and BEFORE a project can / is selected. Console shows no additional information.

This happens both with the latest Steam branch version as well as with the Godot mono Distribution. see attached Image:
![image](https://github.com/godotengine/godot/assets/29479224/a2e68589-e7f6-4625-8a93-f713545e9cf1)

Steps taken so far:
- delete everything under AppData/local/Godot
- Delete Everything under AppData/romaing/Godot
- Reinstall (Steam Version only)

### Steps to reproduce

For me start Godot. This will however likely be insufficent for anyone else. Last Known Actions:
- Set up InputActions under ProjectSettings in the Attached Project.
- Go into player.gd and edit it (Additional to the things you can see in the script, I tried around with the gd script trinary Operator ("hey" if x = 0 else "bye")
- play around with on runtime InputMapping.
- Run the project in godot (via "play" Button)
- - close it again
- - after this was the first time Godot did no longer react.

### Minimal reproduction project

last loaded Project. 
[projectIssuebbr.zip](https://github.com/godotengine/godot/files/12833611/projectIssuebbr.zip)

**Comment by MarioLiebisch** [comment]
* Does it just take a while to continue or is it stuck permanently?
* Can you try installing Godot on a second drive and see if it still happens?
* When it happens, can you check Task Manager to see if any of your drives is stuck at 100% load or if there are any other curiosities?

I've had prerelease versions of 4.0 randomly hang at startup for 1-10 seconds, which might have been related to Vulkan. It would randomly appear and disappear with revisions. This could be related, this could be something completely different.

**Comment by brill12** [comment]
- highest drive is at 34%
- CPU is stuck at high single core load through (Godot only uses about 16% though)
- waiting about 15 minutes does nothing
- changing drives (from D (a HDD) to G (an SSD) same here (waiting ~23 min this time)

**Comment by Calinou** [comment]
Can you reproduce this if you open a project directly from the [command line](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html)?

**Comment by brill12** [comment]
runing godot using [Godot.exe] --path [directory to project] results in the same.
(this is the same Project as provided in the Bug report)

**Comment by brill12** [comment]
Ok one more thing I tried (without success): Opening Godot with a different Project (see attached) this is an old empty Projekt, so this should now be the minimal setup.
[issueGodotBBR2.zip](https://github.com/godotengine/godot/files/12837140/issueGodotBBR2.zip)

**Comment by brill12** [comment]
Output for verbose:
![image](https://github.com/godotengine/godot/assets/29479224/40a4e86d-2a11-4c86-b429-dea319338e66)

Open Project Verbose: 
![image](https://github.com/godotengine/godot/assets/29479224/b0d5753e-baa5-4e1d-a0df-9eba710ab745)

**Comment by brill12** [comment]
build godot myself and run it Output:
![image](https://github.com/godotengine/godot/assets/29479224/784d56ca-d1bb-4666-a430-0974f552b9ff)

still no difference ...

**Comment by bruvzg** [comment]
Do you have any unusual USB devices plugged? Might be related to https://github.com/godotengine/godot/issues/20566.

**Comment by brill12** [comment]
No new ones since it worked, unplugging all mices, keyboards and headphones also doesn´t fix it. Furthermore I let Godot run for about 6 hours once nothing changed so seems unlikely (as this talks about things taking minutes not hours).

Either way there are a lot of USB devices attached so could be.

**Comment by brill12** [comment]
Updated Windows now everything works again ... strange either way issue closed.
