### ISSUE TITLE
4.2 dev6 .NET -- (Exporting to Android)  error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-arm

### ISSUE THREAD

**Issue by architeer** [godotengine/godot#82920]
### Godot version

v4.2.dev6.mono.official [57a6813bb]

### System information

Godot v4.2.dev6.mono - Windows 10.0.19045 - GLES3 (Compatibility) - Quadro 2000M () - Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz (8 Threads)

### Issue description

Error shows up during exporting to Android, when the "armeabi-v7a" is checked on.

Exporting with "arm64-v8a" alone by itself works fine, but when the "armeabi-v7a" is also checked, that is when the error shows up.

Error message:
error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.linux-bionic-arm. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

### Steps to reproduce

1.  Create a new project
2.  Add a simple default C# script to project file system
3.  Open Visual Studio 2022 and edit project to target .NET 7.0
4.  Godot Editor ... Project > Export
5.  Add Android preset
6.  Select Android preset
7.  Under "Architectures", tick the "armeabi-v7a" to be on
8.  Export Project

### Minimal reproduction project

[TEST_2.zip](https://github.com/godotengine/godot/files/12833741/TEST_2.zip)

**Comment by raulsntos** [comment]
The `armeabi-v7a` architecture is currently not supported by the C# Android exports. Only `arm64` and `x86_64` are supported.
