### ISSUE TITLE
Frame delay project setting affects the editor as well

### ISSUE THREAD

**Issue by SirTodd** [godotengine/godot#82922]
### Godot version

4.1.1.stable.official

### System information

Windows 10 - Vulkan

### Issue description

I don't know if this is intended or not, but some settings in the Project Settings will also affect the editor, which is super unintuitive.
I realized this after setting the physics ticks per second to 1 and suddenly all scrolls in the editor would only update once every second. You can also make the editor freeze by setting a large amount of frame delay msec.
This will only happen after you reopen the project with that setting.

### Steps to reproduce

Set physics/common/physics_ticks_per_second to 0 in the Project Settings
Close the editor and open it again
Try scrolling the script editor with your mouse scroll

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/28385.
