### ISSUE TITLE
Duplicated Code in Window::move_to_foreground() and Window::grab_focus()

### ISSUE THREAD

**Issue by Ryan-000** [godotengine/godot#82936]
### Godot version

4.1.2.stable.mono

### System information

Desktop

### Issue description

The Window::move_to_foreground() and Window::grab_focus() methods in the Window class contain duplicated code that serves the same purpose.

```cpp
void Window::move_to_foreground() {
	ERR_MAIN_THREAD_GUARD;
	if (embedder) {
		embedder->_sub_window_grab_focus(this);
	} else if (window_id != DisplayServer::INVALID_WINDOW_ID) {
		DisplayServer::get_singleton()->window_move_to_foreground(window_id);
	}
}

void Window::grab_focus() {
	ERR_MAIN_THREAD_GUARD;
	if (embedder) {
		embedder->_sub_window_grab_focus(this);
	} else if (window_id != DisplayServer::INVALID_WINDOW_ID) {
		DisplayServer::get_singleton()->window_move_to_foreground(window_id);
	}
}
```

### Steps to reproduce

Open [scene/main/window.cpp](https://github.com/godotengine/godot/blob/master/scene/main/window.cpp)

### Minimal reproduction project

not needed

**Comment by Chubercik** [comment]
I assume the correct solution would be to keep one of them and change all calls to the other method to the one kept; this leaves the question of which of these methods' name is a better fit for what it does - I believe `grab_focus()` to be the better one.

**Comment by jsjtxietian** [comment]
I did some quick code clone detection , I should point out that duplicate code is not rare, maybe we can do something about it.

**Comment by Chubercik** [comment]
@jsjtxietian maybe you could open an aggregate issue with all the duplicated code examples you found, the recently merged PR set a precedent on what we might do in similar situations.

**Comment by jsjtxietian** [comment]
> maybe you could open an aggregate issue with all the duplicated code examples you found

Certainly but maybe not now as I'm a little busy recently. But I can share the tool I used: https://github.com/terryyin/lizard 
Anyone interested in this can use this tool to investigate more.
