### ISSUE TITLE
Debugger Crashes when hovering over a big Array variable 

### ISSUE THREAD

**Issue by geoffw123** [godotengine/godot#82931]
### Godot version

Crashes on 4.1.1 and tested on lastest 4.2 dev version

### System information

Windows 10 Godot 4.1.1

### Issue description

The editor crashes and disappears when hovering over a largish array variable that I want to inspect.  The Game window remains and seems to be working OK. This bug is extremely reproducible, so much so it is making it very difficult to debug code as I am trying to make sure i dont hover in the wrong place and crash it.  I checked on latest 4.2 dev version, bug still present :(

### Steps to reproduce

make a big Array and try and inspect it in the debugger

### Minimal reproduction project

havent got a minimal project sorry. I can make one if you cant reproduce bug

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80959.

**Comment by geoffw123** [comment]
ah hi, you were too fast in replying :) I have now  made a sample test project to show the problem. It crashes even on the simplest ever project if you set a breakpoint and hover over the array
[Crasher.zip](https://github.com/godotengine/godot/files/12835314/Crasher.zip)

**Comment by Calinou** [comment]
> ah hi, you were too fast in replying :) I have now made a sample test project to show the problem. It crashes even on the simplest ever project if you set a breakpoint and hover over the array

The array has 400 items with large numbers (that therefore need a lot of characters to be represented), so this is the same cause as the issue I linked.

**Comment by geoffw123** [comment]
thats good then, just the one bug to fix for the 2 issues. Thanks for speedy reply
