### ISSUE TITLE
Spurious animation transition warning: "aborts the transition by detecting one or more looped" for `switch_mode = at_end`

### ISSUE THREAD

**Issue by moribellamy** [godotengine/godot#82935]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

Spurious error message in what is a valid transition through a valid state machine.

### Steps to reproduce

This issue is pretty subtle so IDK what a good fix would warrant.

This animation tree repros the issue:

![Screenshot 2023-10-06 at 2 52 27 PM](https://github.com/godotengine/godot/assets/13877974/09021dab-746b-4ca7-8e9d-a76e3e932644)

I suspect the salient properties are:
* A transition from idle -> slash, based on `Advance` having `switch_mode = immediate`, `mode = auto` and `condition = slash` (or any other boolean)
* A transition back from slash -> idle, based on `Advance` having `switch_mode = at_end`, `mode = auto` and `condition = idle`

In the game, the following code should result in a valid transition:

```gdscript
	animation_tree[
		"parameters/conditions/slash"
	] = Input.is_action_just_pressed("attack")
	animation_tree[
		"parameters/conditions/idle"
	] = velocity.x == 0
	animation_tree[
		"parameters/conditions/run"
	] = velocity.x != 0
```

However, the godot animator executes this branch from `scene/animation/animation_node_state_machine.cpp

```cpp
if (transition_path.has(next.node)) {
			WARN_PRINT_ONCE_ED("AnimationNodeStateMachinePlayback: " + base_path + "playback aborts the transition by detecting one or more looped transitions in the same frame to prevent to infinity loop. You may need to check the transition settings.");
			
```

I found this confusing, so I instrumented the code to confirm that the machine is attempt to transition from `idle -> slash -> idle`.

```cpp	
	while (true) {
		next = _find_next(p_tree, p_state_machine);
		if (transition_path.has(next.node)) {
			WARN_PRINT_ONCE_ED("AnimationNodeStateMachinePlayback: " + base_path + "playback aborts the transition by detecting one or more looped transitions in the same frame to prevent to infinity loop. You may need to check the transition settings.");
			for (auto x : transition_path) {
				WARN_PRINT("XXX " + x);
			}
			WARN_PRINT(next.node);
			break; // Maybe infinity loop, do nothing more.
		}
```

I suspect the author forgot to consider a transition of `switch_mode = at_end`. Conceptually, there is no error here. As long as an animation takes one frame to play, it is not a candidate for immediate transition back to idle.

In my case the game still works as intended, but I suspect this could cause a multi-node transition to abort prematurely.

### Minimal reproduction project

I hope you find the repro good enough. My project has art files that are not open licensed.

**Comment by TokageItLab** [comment]
I can't tell without taking a closer look at the MRP, but I would guess that the Idle <-> Run loop is the problem and I don't think there are any problems with the other transitions.

**Comment by Stalker2106x** [comment]
I'm having this exact same issue. My AnimationTree get trapped and never goes out of the animation "At End" as its supposed to.
I successfully reproduced a MRP that does trigger the warning in console, but curiously, the animation is working on it.
Might be useful to check why the warning does appear tho.
[AnimBugMRP.zip](https://github.com/godotengine/godot/files/13048259/AnimBugMRP.zip)

**Comment by tudor07** [comment]
I noticed the same problem many times, it breaks all my animations when it happens

**Comment by AlexCZhou** [comment]
The 4.2 stable version also has the same problem

**Comment by tudor07** [comment]
@moribellamy do you have any condition for your `[slash] => [idle]` or `[slash] => [run]` transitions?

**Comment by InfiniteDistraction** [comment]
I also have begun receiving this issue upon switching from 4.0 to 4.2. My animation tree is messier but the issue happens just in Bike -> BikeIdle which is the only "at end" transition in the tree. Bike idle is a single keyframe animation. It works find if I change the transition to immediate but I want the players peddle feet to return to neutral naturally. I have confirmed with print statements that the tree is correctly receiving the command to transition, it just doesn't because of this error.

![image](https://github.com/godotengine/godot/assets/146476352/d711344a-8bf9-4103-a051-912f97ed83c3)

**Comment by conde2** [comment]
This might help,

![image](https://github.com/godotengine/godot/assets/2137569/85c56302-8d59-42d4-a113-0cf4c5e76f5e)

**Comment by AThousandShips** [comment]
@conde2 Please don't add a screenshot of a comment, add the text of the comment instead so everyone can read it (including people using screen readers, or translation)

**Comment by robbertzzz** [comment]
@dandeliondino 

> As was noted earlier in this thread, Godot also doesn't appear to be doing what it says it is (aborting the transitions), unless the effect of that is very subtle. Everything seems to be working as expected visually, the animation automatically transitions to the next one at the end

This isn't the case for me. In the editor the animation tree refuses to play the animations and shows the warning once the very first time I try to transition. When playing the game the animation gets stuck on the first frame of the animation that has the at_end switch mode, so it refuses to play the animation but does make the transition to it.

@conde2  

Changing this setting to anything else doesn't do anything for me. Have you been able to make this work?

**Comment by conde2** [comment]
After changing to disable it worked for me, you need to change on every arrow you don't want it to auto transition. But not sure if is the same problem, I'm just saying that I had a similar problem and this was the fix.
