### ISSUE TITLE
Rigidbody lose bounce enegy with bounce 1

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [godotengine/godot#82945]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Sep 13 14:10:57 UTC 2023 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 535.104.05) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Well i created simple test project to test bounces and found that physics calculations in my opinion work not right. 
I am not sure is it a bug but i almost sure that exist calculation mistake which in my opinion too big. And due to it Rigidbody loose energy too fast than it have to be in case if used bounce property = 1. In ideal situation i expect that Rigidbody have to bounce endless to same height. I attached simple project which illustrate issue.

### Steps to reproduce

1) load and start attached project.
2) wait 5-10 seconds 
3) See that ball loose height quite fast

### Minimal reproduction project

[sidegame1.zip](https://github.com/godotengine/godot/files/12836981/sidegame1.zip)

**Comment by mrcdk** [comment]
This isn't a bug per se. By default there's a global linear and angular dampening values.

You can change the default values in the project settings under `Physics/3D` and enabling `Advanced settings`. You can also control each `RigidBody3D` dampening mode in the inspector under `Linear/Damp Mode` and `Angular/Damp Mode` Set them to `Replace` and the `Damp` values to 0 to remove any dampening and the ball will bounce infinitely.
