### ISSUE TITLE
"Parser bug" - Error Message Asked to be Reported

### ISSUE THREAD

**Issue by dawsonc623** [godotengine/godot#82960]
### Godot version

4.1.1.stable

### System information

Windows 11

### Issue description

While working on a project, I noticed the following error message appear:

```
Parser bug (please report): Trying to check compatibility of unset value type
```

Unfortunately, the Output panel has no extra info I can pass on, but if there are logs somewhere on my computer I can grab extra info from I am happy to do so. I just need pointed in the right direction.

### Steps to reproduce

It happened once while I was scripting, and I am not sure how to make it happen again. Normally, I would not report issues I cannot reproduce, but this one asked to be reported.

### Minimal reproduction project

I am happy to plop the triggering project on GitHub if it helps, but I would not call it a "minimal reproduction project".

**Comment by AThousandShips** [comment]
Please try identify more information about what is triggering this, even if it asks to be reported there needs to be some information about what you did when it happened

**Comment by dawsonc623** [comment]
@AThousandShips Thanks for the response. To reiterate, it happened once while I was scripting, and I am not sure how to make it happen again. Specifically, I was writing code in VS Code, and when I went back into Godot the red message was there with nothing else in the Output (I had cleared the Output after fixing the previous scripting errors I had). I realize on its own this information is not super helpful, which is why if there are editor / engine logs somewhere with more context I am more than happy to grab those. I just do not know where to look.

Again, the only reason I came here to report with such little information on hand is because it asked me to report, which I took to mean its occurrence at all is something that should be reported. If that is not a proper approach, then I can avoid reporting without more information if it happens again. However, as it happens while I am scripting it might be hard for me to ever catch exactly what I wrote to trigger it, so perhaps updating the error message to avoid useless reports could help reduce issue clutter.

**Comment by AThousandShips** [comment]
I understand, but making a report should still be with information, the assumption is that people know to provide information about what they did, as it is a requirement as per the instructions:
> List of steps or sample code that reproduces the issue. Having reproducible issues is a prerequisite for contributors to be able to solve them.

Please don't tag people you are already having a conversation with, it's just me here

**Comment by dawsonc623** [comment]
> Please don't tag people you are already having a conversation with, it's just me here

I apologize, I will avoid doing so.

> I understand, but making a report should still be with information

Also noted. This is not reproduceable for me at least. The Output was not even visible whenever it popped up, so I struggle to know what more information to provide. I apologize for the inconvenience, but if there is nowhere else I can look for information then maybe it is best to close this issue. I know now not to report this (or any issue) I see without being able to trigger it reliably regardless of messaging. Again, I apologize for the inconvenience.

**Comment by AThousandShips** [comment]
I mean you can test with your project and try to trigger it, and it's not an inconvenience, just that we can't do anything unless we know how to make it happen

**Comment by dawsonc623** [comment]
Understood. Now that I think about it I have been working in the same script file for a while now (that game dev life, right?), so perhaps I can see if undoing and redoing any of my changes triggers it. Let me give that a go and report back.

**Comment by dalexeev** [comment]
The `is_type_compatible()` function that prints the error is used in many places in the GDScript analyzer. Without steps to reproduce (like in #82765), there is no way to fix this bug (other than review the entire analyzer). Please write here or open a new issue if you find a way to reproduce the bug. Thanks for reporting the bug nonetheless!
