### ISSUE TITLE
Mono project fails to build because of incorrect file type

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot#82977]
### Godot version

v4.2.dev6.mono.official [57a6813bb]

### System information

Godot v4.2.dev6.mono - macOS 10.15.7 - Vulkan (Forward+) - integrated Intel HD Graphics 5000 - Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 Threads)

### Issue description

Mono projects can fail to build because missing a props file

### Steps to reproduce

Create a C# project
Create a C# script
An error might show up when building the project

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
> An error might show up when building the project

This is far too vague, more details are needed

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
