### ISSUE TITLE
SVGs with <mask> in them broke, affecting the display of several editor icons

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#82982]
### Godot version

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Our SVG icons that use the `<mask>` element broke.

![image](https://github.com/godotengine/godot/assets/85438892/b70570be-8e16-466d-84c2-b113f44c1ebd)

Most likely caused by #82542 but I haven't tested it. Technically, `<mask>` is not required for these SVGs, but it allows for easy clean cutouts which is why I used them here.

### Steps to reproduce

Open Godot and find them

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment]
@capnm

**Comment by capnm** [comment]
@MewPurPur  Thanks for the report. I can take a look next week.

**Comment by MewPurPur** [comment]
![image](https://github.com/godotengine/godot/assets/85438892/99d3bb4b-e363-41f8-b48a-5ebc13f3eb41)

From my slightly outdated dev build.

**Comment by capnm** [comment]
![upscaled-png-diff](https://github.com/godotengine/godot/assets/4047289/11210e72-3530-41b0-a88c-b785801e83b0)
