### ISSUE TITLE
Godot Editor allows using renderers incompatible with hardware

### ISSUE THREAD

**Issue by SkyfallWasTaken** [godotengine/godot#82997]
### Godot version

4.1.2.stable

### System information

Godot v4.1.2.stable - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 2000 (SNB GT1) () - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

When using a GPU that doesn't support Vulkan, but does support OpenGL 3.3, the editor will allow you to create and open. Forward+ and Mobile projects. However, the editor will crash when you open them due to lack of Vulkan support.

The editor should just not let you do that in the first place.

### Steps to reproduce

1. Use a GPU that doesn't support Vulkan, but does support OpenGL 3.3
2. Attempt to open a Forward+ or Mobile project
3. Editor will crash after Godot splash screen

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8006.
