### ISSUE TITLE
Highlight rect in "Whole search" is slightly offseted since 4.2.dev1

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#83009]
### Godot version

v4.2.dev1.official [0c2144da9]

### System information

Godot v4.2.dev1 - Linux Mint 21.1 (Vera) - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Since 4.2.dev1, the highlight rectangle of the whole search (Ctrl+Maj+F) is slightly offseted to the left : 
![godot_whole_search_highlight_issue](https://github.com/godotengine/godot/assets/60538144/b721ef69-6102-4356-b094-0b5848e40ac2)

Issue is still here on 4.2.dev6.

EDIT : Is it related to commit 92287c2 ?

### Steps to reproduce

1. In script editor : Ctrl+Maj+F, then search for a word
2. See the highlight rectangle

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> EDIT : Is it related to commit https://github.com/godotengine/godot/commit/92287c2cb21dcab237b59dca525383d47c7acf14 ?

That commit is in 4.0-stable, so it would affect 4.1.1 too.

**Comment by joao-pedro-braz** [comment]
One of my first contributions and it's bugged... way to go lol
