### ISSUE TITLE
When creating Node2D I get a Vulkan error (Steam Version)

### ISSUE THREAD

**Issue by AmokDev** [godotengine/godot#83007]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 10 - Godot v4.1.2.stable.official - Vulkan Instance Version: 1.3.250 - AMD Radeon 540x

### Steps to reproduce

I'm building Node2D, trying to save in project folder but getting error in terminal, provided below. Afterwards, the engine freezes.

### Minimal reproduction project

[New.zip](https://github.com/godotengine/godot/files/12841237/New.zip)

### Issue description

When creating a Node2D, the application freezes

```Godot Engine v4.1.2.stable.official.399c9dc39 - https://godotengine.org
OpenGL API 3.3.0 Core Profile Context 23.9.2.230827 - Compatibility - Using Device: ATI Technologies Inc. - Radeon 540X Series

Editing project: C:/Users/AmokDev/Desktop/Godot Projects/dddd
Godot Engine v4.1.2.stable.official.399c9dc39 - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - Radeon 540X Series

WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2360)```

**Comment by Calinou** [comment]
Thanks for the report! Consolidating with https://github.com/godotengine/godot/issues/71929.

In the meantime, use the Compatibility rendering method in the top-right corner of the editor.
