### ISSUE TITLE
Exported var in resource member set to node existing in scene triggers node not in tree errors

### ISSUE THREAD

**Issue by Klaim** [godotengine/godot#83011]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.1694) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

I observe this error:
```
E 0:00:00:0494   slot.gd:8 @ update(): Condition "!is_inside_tree()" is true. Returning: Transform3D()
  <C++ Source>   scene/3d/node_3d.cpp:324 @ get_global_transform()
  <Stack Trace>  slot.gd:8 @ update()
                 macguffin.gd:8 @ _physics_process()
```

This is triggered when trying to access `.global_position` on a `Node3D` inheriting node in a scene, which has been set to a field in a `Resource`-inheriting object. We try to access this node through the field, but this error triggers. Note that the node being accessed is defined in the scene, it's not a node that have been manually instantiated nor was it removed from the tree. Actually there is no node removal or addition being done in the whole project.

![image](https://github.com/godotengine/godot/assets/142265/2cb97484-c298-4018-a8ed-4d911314e9f9)

In addition, reloading the scene (or project) shows that the field in the inspector is set, but displays an empty string or something similar:

![image](https://github.com/godotengine/godot/assets/142265/eae6e0eb-fbb0-4dd9-bbfe-d2165bf36008)

## Manually reproduce:

I reduced the conditions to trigger this issue to the following, all in the same scene:
1. `a` is a node  which have is of a type `A` inheriting `Node3D`
2. `b` is a node which have an exported member `x` of type X which extends `Resource`
4. `X` (the type) have an exported member `a` of type `A` and a member function `update` that prints `a.global_position` (to access it)
5. Using the inspector, we set `b.x.a` to `a` in the scene.
6. `b._physics_process` calls `b.x.update()`, triggering the access to `a.global_position`

From this point:
- when running the scene, each frame we get the error about `is_inside_tree()` being false
- saving the project/scene and reloading it, we see that the inspector cannot display the name of the node that's set in the field of the resource.

## With the minimal reproduction:

1. Run the main scene: you'll see the errors in the debugger window.
2. Make sure that the `macguffin.Slot.Thing` field is set to `thing` (it's not when first openned), then run the scene again: same errors.
3. Reload the project: the `macguffin.Slot.Thing` field does not show the name of the refered node again.

### Minimal reproduction project

Repro: https://github.com/Klaim/godot-bugrepro-lost-node-reference

Note: you need to re-set the `macguffin` object of the se `main` scene so that it's `slot` parameter have it's `thing` field set to the `thing node. See previous instructions.

**Comment by Pennycook** [comment]
I recently encountered something similar, and convinced myself this isn't supposed to work (since a Resource doesn't exist in the SceneTree). I'm glad to see I'm not alone in trying this!

I changed my setup so that each Resource stored a NodePath.  It was a bit more awkward, but it was an acceptable workaround for my use-case.

**Comment by bitsawer** [comment]
Thanks for the report. Node export in a Resource is not supported, see https://github.com/godotengine/godot/issues/82809#issuecomment-1748374568

An explicit error message was added in https://github.com/godotengine/godot/pull/82843, which should be helpful in the future releases. Closing as duplicate.
