### ISSUE TITLE
The whole CompressedTexture2D is rendered instead of the correct Atlas Texture in the Sprite2D Region Editor

### ISSUE THREAD

**Issue by RobotoSkunk** [godotengine/godot#83021]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Debian GNU/Linux trixie/sid trixie - X11 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1650 (nvidia) - AMD FX-8800P Radeon R7, 12 Compute Cores 4C+8G (4 Threads)

### Issue description

When I opened the Region Editor of a Sprite2D node, the whole spritesheet of my game was rendered instead of the right Atlas Texture that was attached to the Sprite2D.

It should be displaying this:
![image](https://github.com/godotengine/godot/assets/49355293/c6ae3992-488f-4576-9be6-628cd8aad4d7)

But I got this instead:
![image](https://github.com/godotengine/godot/assets/49355293/26d1db7e-ec87-4b51-946b-62d24b2beb43)

I thought that I was selecting the whole spritesheet and rendering it, but in the game, it looks correct
![image](https://github.com/godotengine/godot/assets/49355293/99eed80e-17cb-4428-b77c-d80d33b2ecb3)

### Steps to reproduce

1. Add a new spritesheet or any image to test.
2. Create a new Atlas Texture from it.
3. Create a Sprite2D node and attach the Atlas Texture as the Texture of the node.
4. Enable `Region` in the Sprite2D node.
5. Open the Region Editor of the Sprite2D node.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This should be fixed in 4.2.dev6 as per https://github.com/godotengine/godot/pull/80435.

**Comment by RobotoSkunk** [comment]
> This should be fixed in [4.2.dev6](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-6/) as per #80435, please test.

Tested on 4.2-dev6, fixed as per #80435.

![image](https://github.com/godotengine/godot/assets/49355293/c1a881c9-f037-420b-b0e1-a75ad034bab4)
