### ISSUE TITLE
godot4 --headless --export-release should output a non-zero exit_code on errors

### ISSUE THREAD

**Issue by superherointj** [godotengine/godot#83042]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable (399c9dc39) - NixOS 23.11 (Tapir) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 535.113.01) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

On `--export-release` failing for *any* reason, godot4 application should output a non-zero [exit_code](https://faculty.cs.niu.edu/~hutchins/csci480/signals.htm).

It causes CI to not block pipelines.

Desired behavior: In the presence of errors in logs, Godot process should return a non-zero exit signal.

### Steps to reproduce

Start any new project. Just run:

> godot4 --headless --export-release "Linux/X11" junk/

Error output:

> Godot Engine v4.1.2.stable.nixpkgs.399c9dc39 - https://godotengine.org
>
> WARNING: Custom cursor shape not supported by this display server.
>      at: cursor_set_custom_image (servers/display_server.cpp:480)
> ERROR: This project doesn't have an `export_presets.cfg` file at its root.
> Create an export preset from the "Project > Export" dialog and try again.
>   at: _fs_changed (editor/editor_node.cpp:1003)

Then, check for signal error:

> echo $

0

### Minimal reproduction project

This error replicates with any new empty project. (So it is not necessary to provide a zip!)
I'm including a repo and a zip. But it is pointless. You can start a new project and works the same.

https://github.com/superherointj/godot-error-signal

[empty-project.zip](https://github.com/godotengine/godot/files/12846523/empty-project.zip)

**Comment by AThousandShips** [comment]
> On `--export-release` failing for any reason, godot4 application should output a non-zero error number.

Is this documented as a feature that's guaranteed?

**Comment by superherointj** [comment]
> Is this documented as a feature that's guaranteed?

This is a OS standard behavior for applications. All applications should comply. This is pretty basic.

**Comment by AThousandShips** [comment]
There are plenty of ways to respond to a particular event, that's what needs to be discussed and how to approach it

To confirm, the exporting here completely fails yes? No results are exported?

**Comment by AThousandShips** [comment]
I'll let others make the judgement on that, I don't consider this a bug but a missing feature

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/pull/81518.

**Comment by superherointj** [comment]
> This can likely be implemented by using `OS::get_singleton()->set_exit_code(EXIT_FAILURE);` just before an export-related error is printed (you'll need to modify individual instances where these messages are printed).

Agreed.

> Godot regularly prints errors due to internal issues (such as engine bugs or user scripts doing something invalid), so I don't think this makes sense. Non-zero exit code should only be returned if the main process failed in some way (such as exporting the project in your case).

Usually: Errors is what require to halt execution. Warnings don't.
From what you said, I understood that warnings (events that don't require to halt execution) are leaking to errors (events that require to halt execution), then it seems, there is another problem [in filtering?].
I believe you might have offered the pragmatic solution here. So, thanks for that. I take it.

> I'd just exit with `1`, which is the value of the `EXIT_FAILURE` C constant.

Agreed.

**Comment by kxn** [comment]
+1 for this one.  Call it a bug or a feature, whatever is ok. it is badly needed by projects depending on CI workflows. There is no way to find errors that prevent building currently. If other people need current exit code behaviour and changing may break them, please at least provide something like --return-non-zero-on-any-errors.

Thanks

**Comment by m21-cerutti** [comment]
This is clearly a bug, as it prevents CI systems from operating reliably.

Seems exit code is very random, I got error code -1073741819 when I export with a workaround to this error https://github.com/godotengine/godot/issues/77478, where I add global_script_class_cache.cfg to non ignored files. Make export work if we ignored this weird error coe.

![image](https://github.com/godotengine/godot/assets/23432929/88c208c9-7309-410b-8029-1ba22bd5ea16)

On second run however no code error anymore ^^'.
![image](https://github.com/godotengine/godot/assets/23432929/da2fecf8-73f6-430d-bf06-b5c02f9329f8)

It's really painfull we can't rely on exit code.

**Comment by superherointj** [comment]
For those wanting to export a Godot project in CI, the workaround I have been using to check for errors is:

```
    # 'command' is required to forward stderr to stdin.
    # 'unbuffer' is required to keep colors in logs.
    command 2>&1 ${expect}/bin/unbuffer godot4 --verbose --headless --export-release "Linux/X11" $out/bin/project_name | tee $TMPDIR/godot.logs

    # Manually check for errors
    [ `grep "ERROR:" $TMPDIR/godot.logs | wc -l` -eq 0 ]
```
(I happen to use [Nix](nixos.org) to do the build. So, `$out/bin/` is that. But you get the idea.)
