### ISSUE TITLE
MenuItem does not show MenuButtons on Mac

### ISSUE THREAD

**Issue by cyface** [godotengine/godot#83044]
### Godot version

4.1.2

### System information

Mac OS 14 / M2

### Issue description

When creating a new project with a MenuBar with nested PopupMenus, the MenuButtons appear in the 2D scene view, but are not there when you run the project.

The same project built in the same version of Godot on Windows 11 works fine.

### Steps to reproduce

1. New Project->Compatibility
2. Choose User Interface
3. Add MenuBar to root node
4. Add Popup menu child to MenuBar
5. Run project

### Minimal reproduction project

Trivial steps

**Comment by bruvzg** [comment]
On macOS `MenuBar` add child `PopupMenu`s as items of the macOS native global menu bar instead of showing them in the window. To disable this behavior, uncheck "Prefer Global Menu" in the `MenuBar` properties.

**Comment by cyface** [comment]
@bruvzg got it.  Might be a good thing to add to the documentation. Thank you for the quick response!
