### ISSUE TITLE
mesh_add_surface ignores the dictionary's "format" key

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#83055]
### Godot version

master (42425baa59956dc9d1e22341fe5e5d7f8fad5067)

### System information

Linux

### Issue description

Adding a mesh with `mesh_add_surface` causes the format key to be ignored unless `uv_scale` is set.

https://github.com/godotengine/godot/blob/master/servers/rendering_server.cpp#L1837

This was introduced by 51ed3aef63c0fdfc7666c004cc6d94dd15322d81

Is this intended or an oversight?

Paging @clayjohn 

### Steps to reproduce

Create a surface data from gdscript and try to add it to a mesh using mesh_add_surface

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Definitely a typo that should be fixed ASAP

**Comment by AThousandShips** [comment]
The check for `format` is already done above, so must be a mixup

Can fix unless you're on it

**Comment by AThousandShips** [comment]
Done

**Comment by AThousandShips** [comment]
I am however unsure why this doesn't crash, it should as it looks up in a dictionary with a non-existing key
