### ISSUE TITLE
OpenGL stereo render issue on Quest when shadow is enabled

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#83060]
### Godot version

4.2 dev6

### System information

Quest - Godot 4.2-dev6 - GL_compatibility renderer - OpenXR Loader 2.0.0 dev2

### Issue description

Enabling shadow when using the OpenGL renderer in stereo on Quest devices causes rendering issues. The issue only happens when XR is enabled. Running the same project without stereo doesn't cause rendering issues.

See videos below:
- With shadows enabled:

https://github.com/godotengine/godot/assets/914968/48c3331c-9931-424f-9cc1-16e6001913bb

- With shadows disabled:

https://github.com/godotengine/godot/assets/914968/7f20e820-a923-45c5-8f05-dd060f3a2cfb

### Steps to reproduce

- Create a new OpenXR project using gl_compatibility renderer
- Add directional lights with shadow enabled (the default setting)
- Export and run the project on a Quest device

### Minimal reproduction project

- Unzip and open the link repro project: https://drive.google.com/file/d/1TZuFhMVjankMpUpePADf5kIi0RjhTCgS/view?usp=sharing
- Install android build templates
- Export and run the project to a Quest device

**Comment by BastiaanOlij** [comment]
Just to rule it out as a cause, please see if this fixes the issue: https://github.com/godotengine/godot/pull/82752

Should already be merged into master.

**Comment by m4gr3d** [comment]
> Just to rule it out as a cause, please see if this fixes the issue: #82752
> 
> Should already be merged into master.

@BastiaanOlij I tested a couple days ago with that fix included, same issue.

**Comment by BastiaanOlij** [comment]
So this issue turned out to be far more serious than just impacting VR. We weren't loading our project settings and thus no shadow atlas was being created. This is masked during development because the editor build runs extra project settings code. I'll be submitting a PR for the settings related to shadow but I suspect there are others.
