### ISSUE TITLE
Parser fails to find and attach script to root node of a scene when running a specific scene (run current)

### ISSUE THREAD

**Issue by WAS-D** [godotengine/godot#83063]
### Godot version

whatever version came out around the end of September 

### System information

Windows 11

### Issue description

Okay so I have a script on the root node of an area, and the script will not attach it's self if I run the current scene, but only if there's any changing the scene, which is something that I had to point out, also sorry I couldn't provide more details, my desktop is currently dead and I won't be able to access it for a long time so I'm reporting the issue before I forget 

### Steps to reproduce

Have a node3d scene

Attach a script to the file

Preload another scene within the script, set it to change to said scene at a trigger

(Optional) add some visual elements to differentiate the scenes

Run the current scene

### Minimal reproduction project

Unable to provide currently

**Comment by WAS-D** [comment]
Running the full game mitigates the error, it's only when you run the current scene

**Comment by Zireael07** [comment]
This issue is impossible to act on as is and will be closed.

**Comment by akien-mga** [comment]
There's indeed nothing actionable in this issue.

It sounds like you're having a bug in your code, or wrong expectations that you can run a scene standalone while it has dependencies on other scenes not in the scene tree.

You should ask for support on other community platforms like Discord, Facebook or Reddit.

GitHub is only for bug reports, which clears steps to reproduce them.

**Comment by WAS-D** [comment]
nevermind, found the error, it was a cyclical error im a dumb
