### ISSUE TITLE
Exported properties left at their default values do not run their setters

### ISSUE THREAD

**Issue by nblackley** [godotengine/godot#83078]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3713) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Properties that are Exported only run their setters when the value is manually changed in the editor. 
Using the example code:
```
using Godot;
using System;

public partial class SetterTest2 : Node
{
    private int testVar;
	[Export] private int TestVar
	{
		get
		{
			return testVar;
		}
		set
		{
			testVar = value;
			GD.Print($"Setter was called.");
		}
	}

    public override void _Ready()
    {
        GD.Print(TestVar);
    }
}
```
The Editor will show the value of "Test Var" to be the C# default value of 0. However, when the program is run, the print does not run. 
### Editor:
![image](https://github.com/godotengine/godot/assets/3334325/480931c0-8203-4308-8ab0-0ded32733fa0)
### Output:
![image](https://github.com/godotengine/godot/assets/3334325/85b8f31c-308a-4846-bcbb-078dda33cc74)

However, if the "Test Var" is updated to be anything else, the Setter is run. 
### Editor:
![image](https://github.com/godotengine/godot/assets/3334325/99ce0564-959b-47c5-81f8-cbd07f859813)
### Output:
![image](https://github.com/godotengine/godot/assets/3334325/640ce095-45c0-4a56-b7e8-90a7819d06bd)

To me, this behavior is inconsistent. I would expect the editor to run the setter, regardless if the value is default or not since seeing the value `0` in the Editor is equivalent to putting `TestVar = 0` in the `_Ready()` function. However, this is only true for overridden values. This is particularly an issue for Exported enums, where the default value is the first value in the Enum. This means there is no way to "Set" the enum to the default value through the editor.

### Steps to reproduce

See issue description.

### Minimal reproduction project

Add the following Script to a basic `Node`

```
using Godot;
using System;

public partial class SetterTest2 : Node
{
    private int testVar;
	[Export] private int TestVar
	{
		get
		{
			return testVar;
		}
		set
		{
			testVar = value;
			GD.Print($"Setter was called.");
		}
	}

    public override void _Ready()
    {
		TestVar = 0;
        GD.Print(TestVar);
    }
}
```

### Example:
![image](https://github.com/godotengine/godot/assets/3334325/a8f76c4d-2f04-489e-9735-71ed476fabf5)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/62739 (this is not exclusive to C#).
