### ISSUE TITLE
Support for GDScript Memory Profiling and Debugging

### ISSUE THREAD

**Issue by elinfame** [godotengine/godot#83091]
### Godot version

3.5.stable

### System information

macOS 13.4.1 - Godot 3.5.stable

### Issue description

There is currently no way to debug memory issues or profile memory at the GDScript level (e.g. leaks, allocations, zombies). System tools on the target platform do not have visibility into GDScript objects and require a different tool per platform.

The expectation is that there would be a tool similar to Xcode Instrument's Leaks/Allocations/Zombies.

### Steps to reproduce

1. Run a project.
2. Open the debugger.
3. There are no facilities for inspecting memory allocations, frees, or a timeline.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.
