### ISSUE TITLE
Bug: HScrollbar slider cannot be grabbed when at leftmost side.

### ISSUE THREAD

**Issue by Zach777** [godotengine/godot#8309]
**Godot 2.1.2 Stable for Linux**

**Issue description:
 When the slider of the scrollbar is at the far left side, which
is the min value, I cannot grab the slider with the mouse.
    I insured that no other control node or selectable node was
obstructing selection of the slider.
    The slider is still highlighted when the mouse hovers
over the bar but the moment the mouse pointer is within
range of grabbing the slider the slider stops being highlighted.
    The issue caused by the bug is alleviated by setting the
sliders page value to a higher setting. Doing so lets the mouse
pointer grab the right portion of the slider but not the middle
or left side of the slider.
    I apologize if I formatted this incorrectly as this is my first
time reporting a bug for Godot.**

 

**Node: HScrollbar
Node Settings:

Custom Step: -1

Min: 0

Max: 255

Step: I set it to many different steps. 0-123

Page: 10 or less

Exp Edit: False or True

Rounded: False or True

Anchor
Left: Begin
Top: Begin
Right: Begin
Bottom: Begin

Rect
Size (154, 12)
Min Size(0,0)
Rotation 0
Scale(1, 1)

Ignore Mouse: True or false
Stop Mouse: True or False

Size Flags
Horizontal: Fill
Vertical: null
Stretch Ratio: 1

I have no theme installed

Margin
Left 0
top - 68
right 154
bottom -56

no custom icons or styles

Visible true
Opacity 1
Self Opacity 1
Behind Parent false
Blend Mode: Mix
Light Max: bit 0

No materials

process Inherit
Script null.

When the slider is small, I cannot grab the slider with the pointer when 
the slider is on the far left slide of the bar**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.
