### ISSUE TITLE
Add spritefonts support

### ISSUE THREAD

**Issue by Jbat1Jumper** [godotengine/godot#831]
The import font dialog is good and it works well with existing fonts. But when I have to draw my own font I actually find it hard to import it. 
The BMFont app from Angelcode to generate .fnt fonts doesn't work and one needs to script a little to create a custom font.

**Comment by akien-mga** [comment]
What's the status on this issue? Is there something we can do, or can someone confirm that there's no standard format to work with?

**Comment by vnen** [comment]
As a note Godot supports importing of BMFont format. There's no other standard AFAIK, but there's also the possibility to make custom import plugins (I even made one for old XNA SpriteFonts).

**Comment by Shadowblitz16** [comment]
@akien-mga lease reopen this issue. I would like to not have to use a 3rd party tool to make sprite fonts when I can just import a sprite texture and define the string map characters and v/h spacing.
