### ISSUE TITLE
Godot4/.NET: In-Project class (Plugin) can not be matched as base class of types (ConcretePlugin) in dynamically loaded .dll

### ISSUE THREAD

**Issue by MostWanted38** [godotengine/godot#83103]
### Godot version

4.2-dev6_mono (and lower), 4.1.1_stable_mono

### System information

Godot v4.2.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description
**The Idea and Goal:**
Add plugin/mod-support for a game or application😎

We want to know if a dynamically loaded type like "ConcretePlugin" (from a .dll file that has a dependency to our game's .dll file) inherits from the "Plugin" base type (which is part of our godot engine / .NET project)

**Explanation**:
We have 2 projects "A" (Godot Engine Project) and "B" (Class Library / DLL) 
- In Godot we want to provide a "Plugin" base class, that modders or plugin developers can inherit from if they want to mod the application. We also have a "PluginLoaderNode.cs" that utlizes its _Ready() to load all .dll files from a given folder path in order to check if their assemblies contain types that inherit from the base class "Plugin". If they do, we want to instantiate these types.
- In the Class Library project we have a dependency on the A.dll so that we can create a "ConcretePlugin" class with a default constructor. 

**Expectation**: 
As every plugin/mod.dll created this way has a dependency to the .dll file of the godot engine project (copy local disabled) and the plugin classes directly inherit from the "Plugin" class, the comparisons of their BaseType with the general Plugin type should result in true when launching the exported Godot project.

**Reality:**
Launching the Godot Project recognizes that there is a .dll file in that folder, but none of its types match with the given "Plugin" class from the Godot Project.
Testing this outside of Godot Engine with a regular NET 6 or 7 project works just fine in console, winform or even wpf applications.
![image](https://github.com/godotengine/godot/assets/45302427/9d2c6eaa-b91e-491a-883c-cc59cc5446db)

**The Code** regading the image above
```cs
using System;
using System.IO;
using System.Reflection;
using Godot;

namespace App.Plugins;

[GlobalClass]
public partial class PluginLoaderNode : Node
{
	[Export] public string PluginsFolderPath = "user://plugins/";

	public override void _Ready()
	{
		base._Ready();
		Type pluginType = typeof(Plugin);

		string pathToDllFiles = ProjectSettings.GlobalizePath("user://plugins/");
		//on Windows -> C:\Users\YourName\AppData\Roaming\Godot\app_userdata\A\plugins
		//using %APPDATA% to get into "Roaming" folder

		string[] dllFiles = Directory.GetFiles(path: pathToDllFiles, searchPattern: "*.dll");
                GD.Print($"Found {dllFiles.Length} .dll files in {pathToDllFiles}");

		foreach(var dllFilePath in dllFiles)
		{
			Assembly pluginAssembly = Assembly.LoadFrom(dllFilePath );
			GD.Print(pluginAssembly);
     
			Type[] assemblyTypes = pluginAssembly.GetTypes();
			if(assemblyTypes is null or { Length: 0 })
				continue;
     
			foreach(var loadedType in assemblyTypes)
			{
				GD.Print($"-------------- LoadedType: {loadedType} -----------------");
				GD.Print($"BaseType: {loadedType.BaseType}");
				GD.Print($"PluginType: {pluginType}");
	
				//1) Can a variable of type "pluginType" get assigned by a value of the type "loadedType"?
				var isAssignableFrom = pluginType.IsAssignableFrom(loadedType);
				//^ false
				//2) Can a value of the "loadedType" get assigned to a variable of type "pluginType"?
				var isAssignableTo = loadedType.IsAssignableTo(pluginType);
				//^ false
				//3) Does the pluginType match the BaseType (Inherited Type) of the "loadedType"?
				var typeMatches = pluginType == loadedType.BaseType;
				//^ false
				//4) same as 3, but with Equals()
				var typeEquals = pluginType.Equals(loadedType.BaseType);
				//^ false
        
				GD.Print(isAssignableFrom);
				GD.Print(isAssignableTo);
				GD.Print(typeMatches);
				GD.Print(typeEquals);

				if (!isAssignableFrom && !isAssignableTo && !typeMatches && !typeEquals)
					return;

				GD.Print("Loading Plugin...");
				
				Plugin plugin = (Plugin)Activator.CreateInstance(loadedType);
			}
		}
	}
}
```

This test fails both on 4.1.1 stable and all of the 4.2-dev versions.
I assume it fails also in the 4.0 Version (needs testing!)

The setup for this test is quite simple
1) you need a godot engine project "A" with the 2 classes "Plugin" and "PluginLoaderNode". When exported for Windows you get a A.exe, A.console.exe and the data folder with the A.dll inside

2) you need a .NET 6.0 class library project that has a dependency to the A.dll with copy local disabled. There you can create a "ConcretePlugin" class that inherits from "Plugin". When building the project you get a B.dll

3) you need to put the B.dll into the Plugin folder and run A.console.exe 

### Steps to reproduce

**Part 1 - Project A: Godot Engine / .NET**
1) Create a new Godot Engine 4.2 / 4.1 / 4.0 Project for C# / .NET and name it "A"
2) Create a scene using a "Other Node", hit Ctrl+S to save is as your main-scene.tscn and mark it as such
3) Start the Project once (F5) to generate the app_userdata folder
4) Create 2 new Resource "Scripts"
- Plugin.cs (regular class; no inheritance; When Created In Godot: let it inherit from Node and remove it later)
- PluginLoaderNode.cs (inherits from Node class)
5) Add the following code to Plugin.cs 
```cs
using System;

namespace App.Plugins;

public class Plugin
{
    public Plugin()
    {
    }
}
```
6) Add the following code to PluginLoaderNode.cs
```cs
using System;
using System.IO;
using System.Reflection;
using Godot;

namespace App.Plugins;

[GlobalClass]
public partial class PluginLoaderNode : Node
{
	[Export] public string PluginsFolderPath = "user://plugins/";

	public override void _Ready()
	{
		base._Ready();
		Type pluginType = typeof(Plugin);

		string pathToDllFiles = ProjectSettings.GlobalizePath("user://plugins/");
		//on Windows -> C:\Users\YourName\AppData\Roaming\Godot\app_userdata\A\plugins
		//using %APPDATA% to get into "Roaming" folder
		string[] dllFiles = Directory.GetFiles(path: pathToDllFiles, searchPattern: "*.dll");
                GD.Print($"Found {dllFiles.Length} .dll files in {pathToDllFiles}");

		foreach(var dllFilePath in dllFiles)
		{
			Assembly pluginAssembly = Assembly.LoadFrom(dllFilePath );
			GD.Print(pluginAssembly);
     
			Type[] assemblyTypes = pluginAssembly.GetTypes();
			if(assemblyTypes is null or { Length: 0 })
				continue;
     
			foreach(var loadedType in assemblyTypes)
			{
				GD.Print($"-------------- LoadedType: {loadedType} -----------------");
				GD.Print($"BaseType: {loadedType.BaseType}");
				GD.Print($"PluginType: {pluginType}");
	
				//1) Can a variable of type "pluginType" get assigned by a value of the type "loadedType"?
				var isAssignableFrom = pluginType.IsAssignableFrom(loadedType);
				//^ false
				//2) Can a value of the "loadedType" get assigned to a variable of type "pluginType"?
				var isAssignableTo = loadedType.IsAssignableTo(pluginType);
				//^ false
				//3) Does the pluginType match the BaseType (Inherited Type) of the "loadedType"?
				var typeMatches = pluginType == loadedType.BaseType;
				//^ false
				//4) same as 3, but with Equals()
				var typeEquals = pluginType.Equals(loadedType.BaseType);
				//^ false
        
				GD.Print(isAssignableFrom);
				GD.Print(isAssignableTo);
				GD.Print(typeMatches);
				GD.Print(typeEquals);

				if (!isAssignableFrom && !isAssignableTo && !typeMatches && !typeEquals)
					return;

				GD.Print("Loading Plugin...");
				
				Plugin plugin = (Plugin)Activator.CreateInstance(loadedType);
			}
		}
	}
}
```
7) Save your code, rebuild your project (Alt+B)
8) Assign the "PluginLoaderNode.cs" script to the root node of your scene
![image](https://github.com/godotengine/godot/assets/45302427/b2a5508a-0736-4895-93ca-08c330235ba6)

9.1) (If Export Templates are not installed) Editor > Manage Export Templates
9.2) Project > Export > Windows (doesnt matter if its debug or release), set "Modify resources" disabled and Build
10) Open the Export Folder and you will see a A.exe, A.console.exe and the data folder with a A.dll
11) Start A.exe or A.console.exe once to get the app_userdata folder

**Part 2 - Project B: Class Library (.NET 6.0)**
1) Create a new class library project (using your IDE or from console)
CLI (Cmd / PowerShell): dotnet new classlib --name B --framework net6.0
2) Add a dependency to the A.dll of the exported godot engine project and disable "Copy local"
(The contents of the .csproj should look like the following)
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="A">
        <HintPath>YourExportPathOfTheGodotProjectA\data_A_windows_x86_64\A.dll</HintPath>
        <Private>False</Private>
      </Reference>
    </ItemGroup>
</Project>
```
3) Modify the Class1.cs
Let it inherit from the Plugin class 
//<- namespace from GodotProjectName.DLL
```cs
using App.Plugins;

namespace GodotPlugin1;

public class Class1 : Plugin //<- Plugin class from GodotProjectName.DLL
{
    public Class1()
    {
         Console.WriteLine("Hello! I'm Class1 Plugin!");
         //when launching the A.console.exe , this will also work! 
         //This way we dont need the GodotSharp.dll dependency reference!
    }
}
```
4) Build the Project and get your B.dll 

**Part 3 - Modding the Application**
1) Go into the base folder where you want to place your plugins and create the "plugins" subfolder.
If youre using "user://" it will be on Windows -> C:\Users\YourName\AppData\Roaming\Godot\app_userdata\A\plugins (%APPDATA% for "Roaming" folder)
2) Copy the B.dll into the "plugins" Folder 
3) Run the A.console.exe and see what happens in the console
(Feel free to post a screenshot of the A.console.exe window in case you get the same problem or different ones)

### Minimal reproduction project

Unable to upload project, as it required about 67MB for the project and 107MB for the exports
So instead, here is a good old GDrive Link to them:
[https://drive.google.com/drive/folders/1QckKqsiylAfGzrVufEQJoy6u3830iTvg?usp=sharing](https://drive.google.com/drive/folders/1QckKqsiylAfGzrVufEQJoy6u3830iTvg?usp=sharing
)
with .zip content 
![image](https://github.com/godotengine/godot/assets/45302427/0d50087f-f81c-45fe-acd6-83c55cef880e)
![image](https://github.com/godotengine/godot/assets/45302427/f868bf81-e809-4e37-8725-83d3e7bcb23a)
![image](https://github.com/godotengine/godot/assets/45302427/db12ec05-82db-4952-85e9-e078c3f72419)

What you need to do:
1) Extract the "GodotProject_A_Export_WindowsLinux.zip" anywhere you like
2) Extract the "GodotProject_A_appUserdata_with_B.dll.zip" into "C:\Users\YourUsername\AppData\Roaming\Godot\app_userdata"
3) Run the A.console.exe 

Alternatively:
4) (How To Reproduce - Step 2) Create the .NET Class Library Project "B" as described and compile/build it
5) (How To Reproduce - Step 3) Inject the Plugin into your "Plugins" folder

Share your results as confirmation, like this
![image](https://github.com/godotengine/godot/assets/45302427/9d2c6eaa-b91e-491a-883c-cc59cc5446db)

**Comment by Chaosus** [comment]
The proposals like that should be created in a specified repository (https://github.com/godotengine/godot-proposals), and not at the bug tracker. Closed.
