### ISSUE TITLE
Significant pause in sync when switching `MultiplayerSynchronizer`'s authority

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#83112]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Debian GNU/Linux trixie/sid trixie - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

When the authority for a `MultiplayerSynchronizer` is changed from one peer to another, there is a significant and noticeable delay (I've seen up to several tens of seconds) before synchronisation with the new authority begins.

Note this appears to only be the case when using the `sync` mode. If a property is `watch`ed, there is no perceptible delay.

### Steps to reproduce

1. Run 3+ copies of the attached scene
2. In one instance, click "Host" to start the localhost server
![Screenshot_20231010_174629](https://github.com/godotengine/godot/assets/441188/b76536be-4ffc-49b7-8edf-dfbfbd0ffe31)

3. In the other instances, "Join" the server
4. Clients: Select a different type of sprite motion for each client instance
![Screenshot_20231010_174728](https://github.com/godotengine/godot/assets/441188/ea39cdb5-0946-4b3c-adc1-9f57f6584ff2)

5. Host: Use the "Authority" buttons on the server to change the `MultiplayerSynchronizer` authority between the peers:
![Screenshot_20231010_174850](https://github.com/godotengine/godot/assets/441188/26a394ca-61e8-4f5f-aacc-2378f24d53df)

6. Host: :warning: Observe that every authority change after the first will cause the sprite to immediately stop moving, before resuming some seconds later with the new authority's movement :warning: 

7. In the editor, change the `MultiplayerSynchronizer`'s replication mode for the sprite's position from `Sync` to `Watch`
![Screenshot_20231010_180359](https://github.com/godotengine/godot/assets/441188/ed5aecab-c6dd-4678-828c-8944284ff19d)

8. Host: Observe that there is no longer a delay when switching authority.

### Minimal reproduction project

Single self-contained scene file:
[authority_switcheroonie.zip](https://github.com/godotengine/godot/files/12859203/authority_switcheroonie.zip)

**Comment by Calinou** [comment]
cc @Faless
