### ISSUE TITLE
`ScriptEditor.reload_scripts()` not available in 4.x

### ISSUE THREAD

**Issue by KANAjetzt** [godotengine/godot#83118]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

In the process of porting a plugin from version 3.5 to 4.1, I encountered the following error message:

```
Invalid call. Nonexistent function 'reload_scripts' in base 'ScriptEditor'.
```

After reaching out for help on Discord, it seems that the method itself still exists in version 4.x but may not be accessible via GDScript?

https://github.com/godotengine/godot/blob/c5291a3555343e8aa5aefa1c7e17f2ad05ee1fc9/editor/plugins/script_editor_plugin.cpp#L3800-L3826

### Steps to reproduce

1. Call `.reload_scripts()` in Godot 4.1

### Minimal reproduction project

[reload_scripts.zip](https://github.com/godotengine/godot/files/12860537/reload_scripts.zip)

**Comment by AThousandShips** [comment]
This was done, technically, in https://github.com/godotengine/godot/pull/36426, but at that time it wasn't an exposed method, it wasn't done in 3.x until https://github.com/godotengine/godot/pull/53900, so when 4.x split off from 3.x it was internal method, it wasn't intended for users but internally in the engine

**Comment by KANAjetzt** [comment]
Thanks for the quick response and the background information. 
Now, the question is whether it's desirable to expose it for 4.x, or if not, can I replicate the behavior of `reload_scripts` using something currently available in GDScript?

**Comment by AThousandShips** [comment]
I'd suggest opening a [proposal](https://github.com/godotengine/godot-proposals) to expose this, as it was never exposed in the first place, and present your arguments there

**Comment by AThousandShips** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/8111
