### ISSUE TITLE
Godot crashes on MacOS M1 when opening certain scenes with Compatibility renderer

### ISSUE THREAD

**Issue by wayjack** [godotengine/godot#83110]
### Godot version

4.1.2.stable

### System information

Godot v4.1.2.stable - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I've had random crashes here and there on 4.1.1-4.1.2 but one that I encountered consistently last night is the entire editor crashing upon opening a certain scene file.

Neither the scene nor its dependencies are corrupt in any way - I've successfully opened the same scene and project on my Windows and Linux machines.

After trying to find similar cases online, I stumbled upon [this forum post](https://godotforums.org/d/33186-why-does-godot-40-keep-crashing/12) where the answer mentions switching away from Compatibility mode to solve the issue.

I tried this and I am now successfully able to open the scene, either in Mobile or Forward+ mode. Still, opening the scene in Compatibility mode will always crash Godot. Even when its tab is left open, Godot just crashes on startup now.

Apple Problem Report: https://pastebin.com/eaUz70Au

### Steps to reproduce

1. Open reproduction project on a MacOS M1 machine
2. Make sure renderer is set to Compatibility mode
3. Open item_drop.tscn

Crash should occur afterwards.

### Minimal reproduction project

[repro_1010.zip](https://github.com/godotengine/godot/files/12859253/repro_1010.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/72469.
