### ISSUE TITLE
Duplicating MeshInstance3D nodes with material resources ignores Local To Scene

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#83126]
### Godot version

4.1.1 stable

### System information

Windows 10

### Issue description

When duplicating MeshInstance3D nodes using Geometry Material Override, the material shares it's parameters between all instances, ignoring Local To Scene setting on the material and mesh.

### Steps to reproduce

- Add a MeshInstance3D
- Add a Geometry Material Override
- Set Geometry Material Override to Local To Scene
- Change a Geometry Material Override parameter
- All instances will be affected

### Current known workaround

- Create saved scene resource of mesh
- Individually drag each tscn into the scene (do not duplicate)
- Local To Scene will be respected

### Minimal reproduction project

[duplicate nodes.zip](https://github.com/godotengine/godot/files/12862105/duplicate.nodes.zip)

Making all MeshInstance3D Sub-resources unique, then re-adding the material resource to each manually with Local To Scene set also does not work:
[duplicate nodes with reapplied materials.zip](https://github.com/godotengine/godot/files/12862189/duplicate.nodes.with.reapplied.materials.zip)

Using Material Overlay with Local To Scene on duplicate nodes results in nothing happening (all material overlays change if Material Overlay not set to Local To Scene)
[material over from duplicates.zip](https://github.com/godotengine/godot/files/12864939/material.over.from.duplicates.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/45350.
