### ISSUE TITLE
Godot 3.5.3 - Browser crashes when running an html export in Apple M1 laptops

### ISSUE THREAD

**Issue by ehtd** [godotengine/godot#83121]
### Godot version

Godot_v3.5.3-stable_osx.universal

### System information

Mac OS Sonoma, Version 14.0 (23A344). GPU Apple M1 Pro rendering GLES3

### Issue description

when running HTML exports, it crashes the browser. Shows this warning and crashes after:

```
WARNING: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4

at: _render_target_allocate (drivers/gles3/rasterizer_storage_gles3.cpp:7025) - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4

ERROR: SceneShaderGLES3: Vertex Program Compilation Failed:
```

### Steps to reproduce

Run the project. I did this locally with:

`python3 -m SimpleHTTPServer 9000`

but first noticed the crash in a game hosted in itch.io

### Minimal reproduction project

[godot_bug.zip](https://github.com/godotengine/godot/files/12860841/godot_bug.zip)

**Comment by ehtd** [comment]
Tested running with MSAA in 4x and it still crashes

**Comment by ehtd** [comment]
Tested disabling MSAA and still crashes

**Comment by Calinou** [comment]
Which browser did you test? Can you test in other browsers?

**Comment by ehtd** [comment]
I used firefox and chrome, crashes in both. I will give it a try with 3.5.2 and report back

**Comment by ehtd** [comment]
Tested and also crashed:
```
Godot Engine v3.5.2.stable.official.170ba337a - https://godotengine.org
ERROR: SceneShaderGLES3: Program LINK FAILED:
index.js:369    at: _complete_link (drivers/gles3/shader_gles3.cpp:1033) - SceneShaderGLES3: Program LINK FAILED:
index.js:369 ERROR: SceneShaderGLES3: Vertex Program Compilation Failed:
```

**Comment by ehtd** [comment]
Someone in the godot discord linked me a similar issue https://github.com/godotengine/godot/issues/65696

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/65696.
