### ISSUE TITLE
Errors by godot dev 4.2 on project created in 4.1 version.

### ISSUE THREAD

**Issue by catafest** [godotengine/godot#83139]
### Godot version

 v4.2.dev6.official [57a6813bb]

### System information

Windows 10 Pro, NVIDIA GeForce GTX 950 

### Issue description

I tried to use a project created with the Godot version: v4.1.1.stable.official [bd6af8e0e]
but with the new Godot dev version: v4.2.dev6.official [57a6813bb]
Theoretically, I should not restart my project from the beginning to use a version without bugs and improved by Godot.
This is the error and project can't be edited: 
```
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2309)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2452)
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2309)
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2309)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2452)
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2309)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2452)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2452)
ERROR: Condition "err" is true.
   at: flush (drivers/vulkan/vulkan_context.cpp:2309)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
   at: (drivers/vulkan/vulkan_context.cpp:2375)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: (drivers/vulkan/vulkan_context.cpp:2452)`
```

### Steps to reproduce

Try to develop an old project created with v4.1.1.stable.official [bd6af8e0e] using the new v4.2.dev6.official [57a6813bb] Godot version.

### Minimal reproduction project

any basic project created with Godot 4.1

**Comment by akien-mga** [comment]
The errors point at a failure to initialize the Vulkan renderer. If you just updated your GPU drivers, this could be why and a reboot might solve it.

Otherwise, can you confirm that the same project can still be opened in 4.1.1 on the same computer?

Does the issue happen in a new project?

Could you try other 4.2 dev snapshots between 4.2-dev1 and 4.2-dev6 to pinpoint the first version that fails at opening this project?

**Comment by akien-mga** [comment]
Can you still reproduce this issue in 4.2-beta3 or later (beta4 should be released tomorrow)?

**Comment by akien-mga** [comment]
Assuming fixed, please let us know if this is still a problem in 4.2-beta6 or later.
