### ISSUE TITLE
Crash making new shader in editor

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8314]
_bugsquad edit_ : master at this time seems is a 36f568903b1e91f7cf66efb81620652ca971c686
1) in master branch, open the editor
2) in the inspector window click "create a new resource" button
3) select "ShaderMaterial"
4) select "New Shader" in the "Shader" field
5) press the ">" button
6) wait a moment.... crash in shader_language.cpp:3756

**Comment by dpiquet** [comment]
I can confirm this issue too

**Comment by eon-s** [comment]
Using Godot Master commit 5f15f03d3

When I touch the dropdown to create a new Shader, the console throws:

```
ERROR: can_instance: Condition ' !ti ' is true. returned: false
   At: core/class_db.cpp:472.
```

Then, creating it and when shader code editor opens (sometimes takes few seconds):

```
0 
SHADER ERROR: (null): Expected 'shader_type' at the begining of shader.
   At: :1.
ERROR: _update_shader: Condition ' err != OK ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:1492.
```

And the editor closes.

**Comment by eon-s** [comment]
This seems to be partially solved, still occurs with CanvasItems and with shader materials on a Particle's mesh.

**Comment by eon-s** [comment]
On 4d50c7ad8, creating shaders on Control and Node2D node seems to not crash anymore.

**Comment by Zylann** [comment]
Just occured to me when I tried to create a shader in 3D:

![image](https://user-images.githubusercontent.com/1311555/27051469-89359972-4fb6-11e7-8a11-9c3c1bf26555.png)

![image](https://user-images.githubusercontent.com/1311555/27051479-9181eac2-4fb6-11e7-99c3-1022c8c72cd2.png)

**Comment by reduz** [comment]
I can't really reproduce this anymore..

**Comment by reduz** [comment]
nevermind, just did
