### ISSUE TITLE
FSR 2.2 causes some shaders to glitch with 3d scaling below 1.0

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#83152]
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3742) - AMD FX(tm)-8350 Eight-Core Processor (8 Threads)

### Issue description

When using FSR 2.2 if the scaling is set below 1.0 it causes very noticeable glitches in some shaders

![image](https://github.com/godotengine/godot/assets/526829/0cf9ea10-75ea-4ebd-b245-2ef1e638186b)

### Steps to reproduce

- run the MRP
- use the slider to change Viewort.scaling_3d_scale below 1.0

### Minimal reproduction project

[FSR2 Shader Bug MRP.zip](https://github.com/godotengine/godot/files/12871368/FSR2.Shader.Bug.MRP.zip)

**Comment by DarioSamo** [comment]
Commenting as I will investigate this.

**Comment by DarioSamo** [comment]
Got a fix, will push a PR later.
![image](https://github.com/godotengine/godot/assets/538504/74dc3937-46bb-4225-961b-e295a9c13064)
