### ISSUE TITLE
DisplayServer file_dialog_show callable callback not firing.

### ISSUE THREAD

**Issue by MackyK** [godotengine/godot#83156]
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Windows 10, Forward+

### Issue description

Callable isn't called.

Tried function and lambda.

### Steps to reproduce

Simple, Use provided script.

### Minimal reproduction project

```gdscript
extends Node
	
func _ready():
	var error = DisplayServer.file_dialog_show("Select GDScripts", "C:/", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_FILES, PackedStringArray(["*.gd"]), process_files)
	if error == OK:
		print("file dialog is working")

func process_files(status, files, index):
	print("file dialog callback is working")
	print(status)
```

**Comment by KoBeWi** [comment]
Your callable has too many arguments.
Isn't there any error in the output?

**Comment by AThousandShips** [comment]
This calalble is supposed to take three arguments

**Comment by KoBeWi** [comment]
But the documentation says
> Callbacks have the following arguments: bool status, PackedStringArray selected_paths.

**Comment by AThousandShips** [comment]
It says:
> Callbacks have the following arguments: bool status, PackedStringArray selected_paths, int selected_filter_index.

**Comment by akien-mga** [comment]
This was changed intentionally in https://github.com/godotengine/godot/pull/81218.

It's a new feature in 4.2 so breaking compat between dev snapshots is ok.

**Comment by KoBeWi** [comment]
Well I don't see this in dev6, which explains this issue.

> Godot version
v4.2.dev6.official
