### ISSUE TITLE
Godot 4.1.1 bad quality on ortho camera and Forward+

### ISSUE THREAD

**Issue by atsd34** [godotengine/godot#83157]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

In a simple 3d scene with SDFGI enabled and shadows enabled there are two problems with orthographic camera which is not present on perspective camera
1- there is dot pattern on screen texture. seems like something is wrong with shadows.
2- My model has glowing parts, which causes lighter lines on ground.
Two screenshots with orthographic and perspective cameras;
Ortho:
![image](https://github.com/godotengine/godot/assets/37181550/6151aa48-c58f-40a4-b3c5-5bf1d405874c)
perspective (Which looks great):
![image](https://github.com/godotengine/godot/assets/37181550/a46ace1c-28af-4d66-9119-a68b61e5f50c)

### Steps to reproduce

you can use attached scene , change camera type to see difference

### Minimal reproduction project

[lowpoly.zip](https://github.com/godotengine/godot/files/12872687/lowpoly.zip)

**Comment by atsd34** [comment]
update:

**Comment by Calinou** [comment]
For future reference, this is a duplicate of https://github.com/godotengine/godot/issues/58332.
