### ISSUE TITLE
Bug report - Editor settings, error when set save on focus loss

### ISSUE THREAD

**Issue by josevictormoreno** [godotengine/godot#83164]
### Godot version

4.1.2 stable

### System information

Linux - Ubuntu 22.04

### Issue description

When set a configuration the project window close.

[image](https://github.com/godotengine/godot/assets/63269080/29ea991b-ffa7-4f32-a51f-a74f27ea414b)

### Steps to reproduce

1 - Open some project
2- Editor settings
3 - search for save
4 - set up the option "Save on focus loss"

### Minimal reproduction project

Project with the tutorial assets [Your First 2D game](https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html)
![image](https://github.com/godotengine/godot/assets/63269080/d1abeec8-3ca5-437a-bf28-0a4006e13206)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/78558.
