### ISSUE TITLE
[GDNative] GlobalConstants not exposed from ClassDB

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#8316]
I'm using dlscript to bind Godot with Python. However I couldn't find how to retrieve the globals constants (i.g. `KEY_ESCAPE`):

Given `GlobalConstants` class is not registered inside ClassDB, it is not possible to retrieve  `GlobalConstants.get_global_constant_*` methods with `godot_method_bind_get_method`.

On top of that, dlscript doesn't provide custom functions to access  `GlobalConstants.get_global_constant_*`.

I would feel the latter would be the simpler way to solve this, for example by adding to `dlscript/godot.cpp`:
```c
const int GDAPI godot_get_global_constant_count() {
       return GlobalConstants::get_global_constant_count();
}

const char GDAPI *godot_get_global_constant_name(int index) {
       return GlobalConstants::get_global_constant_name(index);
}

int GDAPI godot_get_global_constant_value(int index) {
       return GlobalConstants::get_global_constant_value(index);
}
```

**Comment by karroffel** [comment]
Oh yes, didn't think about the global scope yet. sounds good to me.

Your API proposal isn't that useful I think.

It would be better to have a `godot_dictionary GDAPI godot_get_global_constants();` that returns the constants.

Additionally I think the api.json should include those so language bindings can use those constants with 0 overhead.

**Comment by neikeq** [comment]
Yes, don't add getters for constants. Include them in `api.json` to generate actual constants in the bindings.

**Comment by touilleMan** [comment]
@neikeq I'd rather not to rely on `api.json` for this given I could bind all the rest dynamically with ldscript thanks to ClassDB's introspection ^^

So I would be more happy with @karroffel's `godot_dictionary GDAPI godot_get_global_constants();` (I can make a PR for it btw)

**Comment by neikeq** [comment]
As long as they are also included in `api.json`, sounds good.

**Comment by touilleMan** [comment]
@neikeq I'm not sure where to put the global constants in `api.json` (it's a list of dict of classes)

- Add a fake class entry called `GlobalConstants` (with `singleton=true, instanciable=false`) which `constants` field list the global constants (and all the `properties`, `signals` etc. empty).
- Add a top level dict with two entries `classes` (containing the current `api.json`'s list of dict of classes) and a `global_constants`

**Comment by karroffel** [comment]
@tuilleMan Option one is the better one. it enables stuff like `print` as well which Dlscript is currently lacking

**Comment by touilleMan** [comment]
Here #8329 😄
