### ISSUE TITLE
Base64 to UTF8 decode fails

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#83162]
### Godot version

v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.dev6 - Windows 10.0.22621 - GLES3 (Compatibility) - Intel(R) UHD Graphics 615 (Intel Corporation; 31.0.101.2115) - Intel(R) Core(TM) i3-10100Y CPU @ 1.30GHz (4 Threads)

### Issue description

The base64 encoded string of a username `8J2Tmm9uc3QzzI_Mgsy1zYjMncyyzJjNlsyxzLly` (should decode to `𝓚onst3r`) fails to decode using `Marshalls.base64_to_utf8` and `Marshalls.base64_to_raw`.
My guess is because it contains special characters that Godot cant decode for some reason.

### Steps to reproduce

Try to decode the b64-string above.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
It doesn't print any error?

**Comment by bitsawer** [comment]
Where did you get that string? I don't think `_` is a valid base64 character. Also, it lacks `=` padding at the end. This seems to work, although it gives some unicode parsing warnings:

`print(Marshalls.base64_to_utf8("8J2Tmm9uc3QzzIMgsy1zYjMncyyzJjNlsyxzLly="))`

Looks like some decoders accept/ignore `_` and allow dropping padding `=` for maximum comaptibility, but I'm not sure if it is in the specification.

**Comment by bruvzg** [comment]
String should be `8J2Tmm9uc3QzzI/Mgsy1zYjMncyyzJjNlsyxzLly`, padding is not required, but it should use standard base64 (with `+` and `/`), your string is likely base64url encoded (with `-` and `_`).

<img width="766" alt="Screenshot 2023-10-11 at 23 21 30" src="https://github.com/godotengine/godot/assets/7645683/6a1c1321-80d8-448c-974a-6fbc50d2cd20">

**Comment by Swarkin** [comment]
> It doesn't print any error?
@AThousandShips 

Sorry, the error is
```
E 0:00:03:0138   script.gd:90 @ get_hall_of_fame(): Condition "CryptoCore::b64_decode(&w[0], buf.size(), &len, (unsigned char *)cstr.get_data(), strlen) != OK" is true. Returning: String()
  <C++ Source>   core/core_bind.cpp:1148 @ base64_to_utf8()
```


> Where did you get that string?
@bitsawer 

From a game leaderboard API.


@bruvzg So should I be fine replacing `/` with `_`? From my quick test this decoded it properly.

**Comment by bitsawer** [comment]
I bruvzg is right and that is base64url encoded text (which seems likely), you need to be aware of the few differences between it and normal base64 encoding supported by Godot: https://base64.guru/standards/base64url. So just replacing `/` with `_` is enough with this specific string, but there is also potential `+` you might need to replace with `-`.

Considering this, I don't think there is a Godot bug here, so I'll close the issue for now. Feel free to comment if you still think there is a Godot issue somewhere.

**Comment by bruvzg** [comment]
> So should I be fine replacing / with _? From my quick test this decoded it properly.

If it's base64url (which is commonly used and probably), replacing `_`→`/` and `-`→`+` should be enough, but there are other base64 versions as well so add `,`→`/` as well, just in case.
