### ISSUE TITLE
Dialog content gets resized incorrectly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#83167]
### Godot version

4.2 9957f1a

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/65348e30-85f7-4b6b-aa08-3f3d9fca5a85

### Steps to reproduce

1. Add AnimationPlayer
2. Add Animation
3. Go to Animation -> Edit Transitions...
4. Change Next

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
I can't reproduce the issue like that, but this is just wrong....


https://github.com/godotengine/godot/assets/11782833/decd07ab-c470-461d-a31e-0a9531a4d0ed



> Godot v4.2.beta (dcbee437f) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.3742) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

Apparently you can call `popup*` methods on an already visible dialog and it retriggers everything. I'm not sure if this is supposed to be like that.

In this specific case this is called every time you change the value:
```
blend_editor.dialog->popup_centered(Size2(400, 400) * EDSCALE);
```
