### ISSUE TITLE
Dragging in the Mesh Preview editor creates a "drag and drop" action.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#83171]
### Godot version

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

https://github.com/godotengine/godot/assets/85438892/b46c7045-c50c-44ef-92c8-04c5f21342b8

### Steps to reproduce

I get this most of the time with mesh previews.

### Minimal reproduction project

N/A

**Comment by Stronkkey** [comment]
This is probably caused by the fact that the mesh editor preview is a standalone class while the material editor preview is part of the material editor (not standalone).

**Comment by MewPurPur** [comment]
In general I don't see this with any other editor previews, so MeshPreview probably does something different that can be investigated.

**Comment by akien-mga** [comment]
As this was reported against 4.2-dev6 I wrongly assumed it was a regression, but I just tested and it behaves the same in 4.1-stable.

I'm not even sure it's a bug actually, there's the same behavior for most properties, they can be dragged to the script editor to copy their name, which is what happens here.

**Comment by YuriSizov** [comment]
> I'm not even sure it's a bug actually, there's the same behavior for most properties, they can be dragged to the script editor to copy their name, which is what happens here.

I don't think this should happen over the preview, though. Or we need to remove other interactions from it, because from the user perspective this doesn't work right.

**Comment by MewPurPur** [comment]
Yes, this should only happen when you drag the property, not the preview under it.

**Comment by KoBeWi** [comment]
Can't reproduce it in 4.3. Can you confirm it's fixed?

**Comment by MewPurPur** [comment]
Seems like I can't reproduce it anymore either.
