### ISSUE TITLE
C# cannot assign to exported type that inherits from some existing Godot types

### ISSUE THREAD

**Issue by naturalarch3r** [godotengine/godot#83170]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.3734) - AMD Ryzen 5 3600X 6-Core Processor (12 Threads)

### Issue description

What's broken:
Attempting to assign an exported property of a type that inherits from CharacterBody3D results in a typecast error, as does a type inheriting from RigidBody3D. I don't have time to test which types do and don't work, but Node3D I have confirmed working. This may be an issue with my particular hardware configuration, as some others that have tested this have not had an issue. But of course, "it works on my machine" does not mean that this is not a real issue.

This issue occurs even after a clean build by deleting both the .csproj and .sln file.

What should happen:
value is assigned without error.

### Steps to reproduce

Simply create any class that inherits from RigidBody3D, or CharacterBody3D, then export a property of that new type. Then, attempt to assign that from the editor.

In the small example project, simply try to assign either the rigid22 or character4d in either of the tester nodes, and it will throw an error.

### Minimal reproduction project

[export-failure-example-exported.zip](https://github.com/godotengine/godot/files/12866912/export-failure-example-exported.zip)

**Comment by tetrapod00** [comment]
I took a look at the project, and I believe you are missing required `[GlobalClass]` decorators on your classes deriving from RigidBody3D and CharacterBody3D. 

Additionally, since `TestingClass` is marked with a `[Tool]` decorator and it references your two derived classes, the two derived classes also need the `[Tool]` decorator.

**Comment by naturalarch3r** [comment]
> I took a look at the project, and I believe you are missing required `[GlobalClass]` attribute on your classes deriving from RigidBody3D and CharacterBody3D.
> 
> Additionally, since `TestingClass` is marked with a `[Tool]` attribute and it references your two derived classes, the two derived classes also need the `[Tool]` attribute.

This unfortunately is not the case. I have already extensively  tested everything I can think of, and this does not fix the issue.
