### ISSUE TITLE
Attaching CollisionShapes to bones

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#8318]
I understand that CollisionShape/CollisionPolygon nodes are being reworked for 3.0, so I wanted to add this request to the mix:
As far as I know, there is no direct way to attach a CollisionShape/CollisionPolygon etc. to a bone, since collision shapes have to be a direct child of a body to work (and of course they are editor-only helper nodes). For complex rigs, animating collision shapes can be a lot of work. So if there was a possibility to somehow tie the movement of a collision shape to a bone, it would become a lot easier to set up skeletal animations with collision shapes. 
That could be achieved like suggested in issue #2174, or by a node that works similar to the "joint" nodes (where you assign "Node A" and "Node B"). 
I guess something like this can already be done with scripting to a certain degree, by accessing the collision shapes of a body and messing with their transform. But an easy, direct solution for the editor would be great.

**Comment by kubecz3k** [comment]
this issue should be closed when https://github.com/godotengine/godot/pull/11973 will be merged

**Comment by AndreaCatania** [comment]
Implemented #11973
