### ISSUE TITLE
Horizontal scrollbar in multiline text editing

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#83186]
### Godot version

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.dev6 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/2a23e532-5069-4743-afb6-a5a82dc60ad7)

This horizontal scrollbar allows me to scroll a few pixels to the right. This is especially annoying since Godot textedits, being as they are, they hide the entire first character when you scroll to the right which can throw you off.

The text used here is `"When this box is checked, the SVG string will be reverted back after starting a new session."` but it works with any text, only at very specific inspector widths.

### Steps to reproduce

Write some normal text in a multiline text editor and try resizing the inspector. You'll see the horizontal scrollbar occasionally pop up for a moment.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Related to #81764
