### ISSUE TITLE
خلل في اداة tilemap

### ISSUE THREAD

**Issue by Ahmedalariqe** [godotengine/godot#83184]
### Godot version

4.2

### System information

Android

### Issue description

لا استطيع تحريك الصوره التي ادرتجتها على tilemap بحرية

### Steps to reproduce

A

### Minimal reproduction project

B

**Comment by AThousandShips** [comment]
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.
