### ISSUE TITLE
Tilemap has black regions when Y-Sort is not enabled after adding a `light2D`

### ISSUE THREAD

**Issue by crayonape** [godotengine/godot#83195]
### Godot version

4.1.2

### System information

Windows 11, Godot 4.1.2 stable, Vulkan Forword+

### Issue description

![image](https://github.com/godotengine/godot/assets/9478533/1a50badb-739d-4b03-882e-8bee370af937)
![image2](https://github.com/godotengine/godot/assets/9478533/122564c1-133a-435a-814d-d61d083f2309)
At first, the tilemaps worked fine. But when I add "light2D" to the character, there are some unexpected black areas when the character is near the tilemaps (walls, floor). I didn't enable shadows and didn't add any "LightOccluder2D", so this is really strange, because other same tilemaps work fine. After some testing, I found that if I enable Y-Sort of tilemaps, the black areas disappear. Is this a bug?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
> Is this a bug?

It may be.



> ### Minimal reproduction project
> 
> N/A

Please provide a minimal reproduction project though, so the issue could be investigated.

---

You could also test if you're having the same issue in some newer versions (like 4.2.beta1).
