### ISSUE TITLE
(Re)importing Assets breaks apart on GLB/GLTF materials at clean project import because of an CSV file

### ISSUE THREAD

**Issue by wp2000x** [godotengine/godot#83200]
### Godot version

4.1.2-stable

### System information

Windows 11

### Issue description

The auto (Re)Importing of assets breaks apart, when a CSV file is re-imported in a project?

I noticed that, when a clean git checkout of an project is made (without the .godot folder), the auto (re)import breaks apart at GLB/GLTF textures/materials. After some time i could narrow down the suspect to an CSV file in my project and the corresponding autogenerated `.csv.import` file. When the `.csv.import file` does not exist in the repo/project it gets successfuly imported, the file gets created and everything is fine. The problem starts when it gets commited and someone else checks it out and tries to rebuild the .godot folder. 

This will result in following error (MRP example red texture cube model):
`WARNING: glTF: Image index '0' couldn't be loaded with the name: Image_0. Skipping it.`
Screenshot of it:
![2023-10-12_17-33-58](https://github.com/godotengine/godot/assets/70962730/a503698d-701b-49ff-8c0d-3c4fab4b6f32)

The material is broken (at this state, only a manual reimport by hand can fix this):
![2023-10-12_17-45-12](https://github.com/godotengine/godot/assets/70962730/b38c3d70-f76d-46ad-9d55-b6d31abbfff2)
And here how the model looks when the csv files does not exist:
![2023-10-12_17-45-44](https://github.com/godotengine/godot/assets/70962730/cc0445c8-4b73-4cc7-a06d-866f17cd800d)

### Steps to reproduce

* Run both MRP projects
* MeshImportBug_OK should run fine and show a red textured cube at the dummy scene and the MeshImportBug_Broken one not.

### Minimal reproduction project

[MeshImportBug_OK.zip](https://github.com/godotengine/godot/files/12884441/MeshImportBug_OK.zip)
[MeshImportBug_Broken.zip](https://github.com/godotengine/godot/files/12884444/MeshImportBug_Broken.zip)

**Comment by fire** [comment]
I have no idea. Maybe there is a text comparison that treats .gltf.import and .gltf.csv.import the same

**Comment by bitsawer** [comment]
Can confirm, tested on current master (37ee293be82e625e68704a78477b841d0ba17b8f). The broken project starts working after deleting the .csv file, its generated .translation file and the .godot folder and letting Godot reimport everything.

Hard to say what exactly goes wrong, but it does seem that the .csv file does cause some import issues. Might be worth checking out if the ResourceImporterCSVTranslation does something weird or if this is a regression.

**Comment by mstarongithub** [comment]
Can confirm CSV imports to be at least weird, but in at least one case broken on v4.2.stable.official [46dc27791] (copied from about window).

Creating an empty project and adding a new csv with the content of 
```
foo
bar
this
fails
imports
```
will have the import of that csv fail with the error `editor/import/resource_importer_csv_translation.cpp:95 - Condition "line.size() <= 1" is true. Returning: ERR_PARSE_ERROR`

Extending the example csv file with an additional value per line "fixes" it. It shows up as a translation file, but trying to open it results in the error 
```
- Failed loading resource: res://example.csv. Make sure resources have been imported by opening the project in the editor at least once.
- editor/editor_node.cpp:1225 - Condition "!res.is_valid()" is true. Returning: ERR_CANT_OPEN
```
The extended csv file may look like this 
```
foo,bar
bar,adfsg
this,keysmash
fails,still
imports,fails
```

**Comment by RPicster** [comment]
I can also confirm this bug - in our case it's a working csv without problems and it it really a big impediment in our team.

**Comment by fire** [comment]
I'm having trouble thinking of a workaround for this. Any suggestions?

**Comment by Oplexitie** [comment]
Can confirm this is an issue with Godot 4.2.2 and Godot 4.3 dev 6.

Pretty problematic if you plan to share your project with other people.
I had to work around it by adding the .csv.import file into my .gitignore on Github.
