### ISSUE TITLE
[4.2 beta1] Relative paths in nodes referenced as PackedScenes cause errors in console

### ISSUE THREAD

**Issue by SanctusAnimus** [godotengine/godot#83209]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3742) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Having exported PackedScene (and any structure using them, such as Array[PackedScene]), which reference a complex scene that contains internal references (exports own nodes) will cause `Found invalid node path` spammed in console, specifically in this version of Godot

### Steps to reproduce

1. Make a separate scene, and 2 children of it (for example, AnimatedSprite2D, and Node2D that will be acting as a component)
2. Attach a script to Node2D, that exports variable of type AnimatedSprite2D, and assign previously made sprite to it, in that scene
3. Save that scene, and add it in any place that exports variable of type `PackedScene` (or contains it)
4. Add a child to the node exporting PackedScene and remove that child

At that point you'll get the following:
```
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 ```
 
 Presumably now there's a code that checks node paths, and as exported variables within scenes use relative paths - which cannot be resolved by node that contains references to them for some reason.
 
 MRP contains stuff above, all you really need to do is to add any child to `Main` (in `main.tscn`) and remove it afterwards.

### Minimal reproduction project

[bug_repro_1.zip](https://github.com/godotengine/godot/files/12886295/bug_repro_1.zip)

**Comment by SanctusAnimus** [comment]
Notably, issue does not happen in [Dev 6 build](https://github.com/godotengine/godot-builds/releases/tag/4.2-dev6), so this regression was added somewhere after that

**Comment by KoBeWi** [comment]
As noted in #83209, the same error appears when you have AnimationPlayer in your scene (the errors refer to animation track paths) or a TileMap with scene tiles.
