### ISSUE TITLE
Compatibility Renderer Scaling is Broken

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#83206]
### Godot version

4.2 beta 1

### System information

Windows 11 - I3-10105f with RX 6600 Adrenalin 23.9.1

### Issue description

Changing Resolution Scale ends up just increasing or decreasing the number of pixels, but not fitting it into the viewport properly, resulting in Gray bars if Render Scale is <1 and if above resulting in only the top left portion of the screen remaining visible, with the rest going off screen.

### Steps to reproduce

Change Scaling with Compatibility Renderer and observe how the window will scale incorrectly

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
We haven't implemented resolution scaling in the compatibility renderer. So this is expected right now. But we should implement it as it is very useful on mobile

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70142.
