### ISSUE TITLE
'Scene' tab of existing scenes can become stuck empty when creating new scenes

### ISSUE THREAD

**Issue by SirLich** [godotengine/godot#83213]
### Godot version

v4.2.beta1.official

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 Ti (NVIDIA; 30.0.15.1259) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When creating new scenes, it's possible for the 'Scene' tab of existing scenes to become stuck in an empty state, despite nodes being there. Graphically, it appears as if a "filter" text has been entered, and all elements are hidden, but this is not the case.

One this state has occurred, it's possible to recover by closing each scene, and reopening them.

![image](https://github.com/godotengine/godot/assets/18729296/be309f2e-01ba-4868-8206-909f7c71c026)

### Steps to reproduce

**Simpl repro (100% repro rate):**

1. Press `ctrl+n` twice in a row
2. See that your 'Scene' tab has become empty, even if you had nodes there

**More complex repro, if desired:**
1. Create a scene with some nodes in it, call it 'Test'
3. Create an empty scene
4. Create an empty scene (again)
5. Select 'Test' scene in the bar (it will default to [empty] which is the new scene)
6. Click the 'Scene' tab if not already selected (e.g., if 'Import was selected).

This issue occures in all ways to create scenes:

- Ctrl + n 
- The + button
- The 'New Scene' option in dropdown

### Minimal reproduction project

Not required. It's an editor functionality.

**Comment by SirLich** [comment]
Note: This issue cannot be reproduced in `Godot_v4.1-stable_win64`

**Comment by chrisl8** [comment]
I can confirm this issue:
![BetaIssue](https://github.com/godotengine/godot/assets/6188278/77849f5a-96c0-438d-8e4d-ce08650734fc)

**Comment by Rindbee** [comment]
May be related to #81513.
