### ISSUE TITLE
Vulkan Mobile: Radiance map rendering is broken after 4.2.dev2

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#83227]
### Godot version

4.2.dev4 and later (possibly 4.2.dev3 as well)

### System information

Fedora 38, GeForce RTX 4090 (NVIDIA 535.104.05)

### Issue description

Radiance map rendering is broken after 4.2.dev2, often causing it to look brighter than intended in practice. You can see the mipmaps shifting around as the camera moves away from the object:

https://github.com/godotengine/godot/assets/180032/8517f810-3b15-4102-8d9a-88eab0c73669

4.2.dev2 | 4.2.dev4 and later
-|-
![Screenshot_20231013_015948 webp](https://github.com/godotengine/godot/assets/180032/01144715-6558-4bcb-bc72-71196e85ae6b) | ![Screenshot_20231013_015958 webp](https://github.com/godotengine/godot/assets/180032/c27f6c85-1011-408d-9b27-37f5ea024de0)

Like https://github.com/godotengine/godot/issues/83175, I'm having trouble bisecting because I get a black screen in 4.2.dev3. The bisect points me to 715ebcc3f15301e6fef85cdecf5acd3cd10dac55 which is unlikely to be the cause for this issue.

This issue only affects the sky radiance map, not ReflectionProbe rendering. It occurs with both High Quality and Real-Time sky process modes. Forward+ and Compatibility aren't affected by this issue.

### Steps to reproduce

- Use a PanoramaSkyMaterial to make the issue more noticeable.
- Add a MeshInstance3D with a material that has roughness = 0.0 and metallic = 1.0.

### Minimal reproduction project

[test_radiance_map.zip](https://github.com/godotengine/godot/files/12888089/test_radiance_map.zip)

**Comment by akien-mga** [comment]
Still reproducible as of `master` (8c7e20d97e181823adf1bb00cfe0c188ba25fe6a).

**Comment by BastiaanOlij** [comment]
Can confirm that with renderdoc, this is not looking good. Radiance map at mip level 0:

![image](https://github.com/godotengine/godot/assets/1945449/9d60ebbc-be22-4112-a179-d996844d78a2)

And at mip level 1:
![image](https://github.com/godotengine/godot/assets/1945449/d5e631b1-b60d-452b-b3ec-d525134a0037)

Thats not supposed to be a uniform color...

**Comment by BastiaanOlij** [comment]
This was missed in #80311, turns out this shader had an extra multiply that didn't survive converting all the shaders to the new approach.
