### ISSUE TITLE
RenderingServer.canvas_set_item_mirroring fails

### ISSUE THREAD

**Issue by awardell** [godotengine/godot#83221]
### Godot version

v4.1.2.stable, v4.2.beta.custom_build [b1371806a]

### System information

Godot v4.2.beta (b1371806a) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen Threadripper 1950X 16-Core Processor (32 Threads)

### Issue description

Calling RenderingServer.canvas_set_item_mirroring results in an error and mirroring does not function.
```
E 0:00:00:0915   mirror.gd:9 @ update_mirroring(): Condition "idx == -1" is true.
  <C++ Source>   servers\rendering\renderer_canvas_cull.cpp:425 @ RendererCanvasCull::canvas_set_item_mirroring()
  <Stack Trace>  mirror.gd:9 @ update_mirroring()
                 mirror.gd:6 @ _ready()
```

Note: Both RIDs are valid and all other RenderingServer functions seem to affect CanvasItems correctly.

### Steps to reproduce

Add a CanvasItem-derived node to the scene tree. Attempt to call
`RenderingServer.canvas_set_item_mirroring(get_canvas(), get_canvas_item(), Vector2.ZERO)`

### Minimal reproduction project

[ReproProject.zip](https://github.com/godotengine/godot/files/12887462/ReproProject.zip)

**Comment by clayjohn** [comment]
It looks like the documentation for this is pretty much non-existent. 

Looking at the function it seems that the canvas_item needs to be a direct child of the canvas. 

In your example, the canvas_item (Sprite2D) is a child of a Node2D and not directly a child of a canvas. 

The only internal use of this function is for ParallaxLayers which must be direct children of the ParallaxBackground which inherits from the CanvasLayer (which is a "canvas" in RenderingServer speak). 

At the very least we need to document the restriction that this function can only be used on direct children of Canvases

**Comment by awardell** [comment]
> Looking at the function it seems that the canvas_item needs to be a direct child of the canvas.

Oh nice job figuring that out! It does work if I set it up as you say:
![image](https://github.com/godotengine/godot/assets/1361278/2b3ad092-fd8b-40cc-83b3-b3e2a88eddd0)

However the results are still not quite what I expected:
![image](https://github.com/godotengine/godot/assets/1361278/ed26884e-06fa-4eac-8f2d-baee1d816e7f)

This was with a `mirroring` parameter at (128, 128) and some rotation applied to the Sprite.

![image](https://github.com/godotengine/godot/assets/1361278/b8f1da39-f546-4bc4-830e-dc116413ed2f)
at (64, 256)

This behavior makes sense in service to ParallaxBackground's needs, but it's pretty wacky on its own.

>At the very least we need to document the restriction that this function can only be used on direct children of Canvases

You're right about this, and it also aught to be documented what exactly it performs.

**Comment by awardell** [comment]
I think it may still be worth considering the direct children requirement to be a bug, but on the other hand perhaps that change belongs in proposals rather than in issues. Idk. Not up to me.

**Comment by awardell** [comment]
I've added a proposal in place of this bug. See https://github.com/godotengine/godot-proposals/issues/8107

Closing this bug.
