### ISSUE TITLE
Texture flip on Particle2D do not flip the texture

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8323]
**Ubuntu 16.10 - Godot version:2.1.3-RC2**

**Issue description:**
The new texture flip for particles do not flip textures, it does something else but definitely not flip (H or V).

**Steps to reproduce:**
- Create a Particle2D with texture.
- Toggle the flip textures and watch.

**Link to minimal example project:**
Particle System demo can be used for this.

**Comment by akien-mga** [comment]
Implemented with fb217317, cc @Hinsbart.
