### ISSUE TITLE
Godot 4.2 beta 1 crashes on MacOS when quit using CMD + Q

### ISSUE THREAD

**Issue by umutseven92** [godotengine/godot#83241]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

MacOS 14.0 (23A344), Apple M1 Max

### Issue description

Godot 4.2 beta 1 crashes on MacOS if quit using CMD + Q. The editor quits as normal, but then the `Godot quit unexpectedly` error pops up afterwards. Occurs both on the project list, and when editing projects. This error didn't occur in 4.1.2.

Error screenshot:

<img width="263" alt="Screenshot 2023-10-13 at 07 34 07" src="https://github.com/godotengine/godot/assets/3675030/6484504e-cbe5-44c5-8b40-e75389d0e985">

Mac error log can be read here: [mac-error.txt](https://github.com/godotengine/godot/files/12890286/mac-error.txt)

Something to note is that this issue does not occur if quit using the `Quit Godot` button in the menu, and the crash seems to have no adverse effects, so this is a low priority issue. It is annoying though, as CMD + Q is a pretty standard way to close applications on Mac.

### Steps to reproduce

Open up Godot in version 4.2 beta 1, in a Mac running MacOS 14.0, then quit using CMD + Q, either in the project list, or when editing a project.

### Minimal reproduction project

No project is needed, as this error occurs on the project list as well.

**Comment by Cronos87** [comment]
I can confirm this issue. Every time I close my game, it crashes. On top of that, it seems to lead to crashes in Godot itself. I can't provide a workflow to reproduce it, but I can try it this evening.

**Comment by 0ceanlight** [comment]
I can confirm this issue as well. Closing the game always causes the editor to crash, as well as switching away to another window, among other things. I can hardly keep it open for a couple of seconds. A fix would be very much appreciated!

**Comment by AThousandShips** [comment]
What version are you on? This was fixed, if you still experience this behavior please open a new report as it's a different bug from this fixed one
