### ISSUE TITLE
EditorPlugin: handles, edit and make visible is being called twice for objects derived from Spatial

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8324]
**Operating system or device - Godot version:**
Debian Stretch 64bit, master branch at fce779a4ef02f1b14f95cab6a06e75db170f3448

**Issue description:**
In EditorPlugin scripts, handles, make_visible and edit get called multiple times for objects derived from Spatial.

**Plugin**

```
tool
extends EditorPlugin

func handles(object):
	print("handles: ", object)
	return true

func edit(object):
	print("edit: ", object)
	
func make_visible(visible):
	print("make visible: ", visible)
```

**Example output for Node**
```
handles: [Node2D:12866]
make visible: False
edit: [Node2D:12866]
make visible: True
```

**Example output for Spatial**
```
handles: [Spatial:12871]
make visible: False
edit: [Spatial:12871]
make visible: True
handles: [Spatial:12871]
make visible: False
edit: [Spatial:12871]
make visible: True
```

**Steps to reproduce:**

1. Open attached project in a console
2. Select Node, Control, Node2D or Viewport in the Scene Tree
3. Observe the output in the console - everything is fine here
4. Select Spatial, Camera or InterpolatedCamera in the Scene Tree
5. Observe the output in the console - now everything is being called twice

**Link to minimal example project:**
[double_signals.zip](https://github.com/godotengine/godot/files/907791/double_signals.zip)

**Comment by Calinou** [comment]
Closing due to lack of response (see @kubecz3k's comment above).
