### ISSUE TITLE
File name displayed in Enums from autoload scripts for docs inside editor

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#83246]
### Godot version

4.2.beta.1

### System information

Windows 11

### Issue description

Enums from autoload scripts displays the file name in place of node name defined in auto loads.

### Steps to reproduce

Create an auto load script having an enum with values
Use the enum value in a script with a default value.
Save and search for the script in documentation.

![image](https://github.com/godotengine/godot/assets/84369217/9837558a-c417-45c8-bc11-ee86ed09cdbb)

Note the Enum from auto load is properly displayed in the description. and Enums from scripts with class_names are displayed properly.

Here is the code
```gdscript

# Globals (autoLoad ) - globals.gd 
extends Node
enum STATUS { ACTIVE, INACTIVE }

# Local Constant File with class_name (Works Fine) - local_constants.gd
class_name LocalConstants extends Node
enum ACTION { SHOOT, PUNCH, THROW }


# Script File base_scene.gd
class_name BaseScene extends Node2D

## Base scene Description

## A local constant description [enum LocalConstants.ACTION]
var action : LocalConstants.ACTION = LocalConstants.ACTION.PUNCH

## A Global constant description [enum Globals.STATUS]
var state : Globals.STATUS = Globals.STATUS.ACTIVE
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is because you have no `class_name`, you can't define an enum in global scope like this AFAIK

**Comment by tokengamedev** [comment]
> This is because you have no class_name

are you saying we have to give class_name in autoload scripts. You cannot, you will get this error when you attach the autoload script to the Project `"Class "Globals" hides an autoload singleton"`

>  you can't define an enum in global scope like this AFAIK

I have released a game using this feature itself, although in 3.x, and now I am going to do it in 4.2 😄
Although Enums in autoload scripts (4.x) have issues in auto-completion., but who cares. love this feature.

Regarding the issue at hand. in my world It is a bug, because in description it is displaying correctly but in definition it is not.

**Comment by dalexeev** [comment]
For non-global classes, links may appear as invalid GDScript syntax (although `extends "script.gd".InnerClass` is valid).

> "Class "Globals" hides an autoload singleton"

The name of the singleton and its type must be different identifiers, for example `Signleton` and `SignletonType`.

* See also godotengine/godot-proposals#7722.

**Comment by tokengamedev** [comment]
I feel stupid by doing this. 😕 The proposal also is saying the same thing.

Registering the Autoload with one name(name of the node) and defining the class_name different name in the script **works**.
I could not find any documentation related to this. It looks like, it is a workaround for some limitation.

Having same name for node and class_name in script attached to the node works, but somehow it does not work for autoload scripts. Surprising😮. 

I am ok with closing the issue, as long as I found a work around to my problem. 

I still feel weird about mismatch between description and definition, but who cares. It is solved for me
