### ISSUE TITLE
`ResourceSaver.save` deletes UID from resource when not running inside the Editor

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#83259]
### Godot version

`master` branch at ee118e7ffd97f478de73f4b344fddc0203ef7cca

### System information

Arch Linux

### Issue description

`ResourceSaver.save` removes the UID when present in a resource.

I was expecting it to either keep the current UID or generate a new one.

### Steps to reproduce

1. Open the attached MRP and note that `resource_with_uid.tres` has an UID:
```toml
[gd_resource type="Resource" format=3 uid="uid://cm483l5h4cwi2"]
```
2. Run the attached project which will run: `ResourceSaver.save(load("res://resource_with_uid.tres"))`
3. The UID is now gone:
```toml
[gd_resource type="Resource" format=3]
```

### Minimal reproduction project

[ResourceSaverUIDNukeBug.zip](https://github.com/godotengine/godot/files/12892418/ResourceSaverUIDNukeBug.zip)

**Comment by KoBeWi** [comment]
Works correctly when run inside the editor.

**Comment by jsjtxietian** [comment]
The uid is set by `ResourceUID::ID uid = ResourceSaver::get_resource_id_for_path(local_path, true);` which will return -1 as uid when   `save_get_id_for_path` is null. `save_get_id_for_path` is set in `EditorFileSystem`'s constructor. So it's fine in editor but breaks when running.

**Comment by AThousandShips** [comment]
I'm not sure how this should be solved, or even treated, UID is an editor specific feature when assigning, and needs to be in editor to be handled correctly

I think this isn't so much a bug as it is a limitation, the one bug would be IMO that you can edit files in the project from a running project, and that this limitation should be documented or you shouldn't be allowed to modify the files this way

**Comment by jsjtxietian** [comment]
IMHO I do agree that we should not edit files (or edit resources) from a running project, tool script is built for that purpose. But the uid loss is a limition as it might make the user confuse.  

Also it seems hard to detect this problem as load and save are common operations.

**Comment by AThousandShips** [comment]
Yeah, could be done when editing in the `res` file scope, but I think this is more a documentation thing, unless we can find a clear way to error about this

**Comment by ChildLearningClub** [comment]
In 4.4.1.stable

This works:
```
  	if ResourceSaver.save(scene_data, "res://addons/scene_snap/resources/scene_data_cache.tres") != OK:
		if debug: push_error("Failed to save scene data to scene_data_cache")
```
This Fails:
```
	if ResourceSaver.save(scene_data, "uid://3as6dllcbl36") != OK:
		if debug: push_error("Failed to save scene data to scene_data_cache")
```

**Comment by KoBeWi** [comment]
You can only save Resource using a path, not UID.
