### ISSUE TITLE
Particles emit by GPUParticles2D disappear when tree is paused

### ISSUE THREAD

**Issue by tivec** [godotengine/godot#83258]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

GPUParticles2D that have process mode set to PROCESS_MODE_PAUSABLE disappear when the tree is paused (using `get_tree().paused = true`). The entire particle system restarts when the tree is then unpaused (with `get_tree().paused = false`). as seen in this video.

https://github.com/godotengine/godot/assets/717574/17a66bca-6759-456d-9c59-c589b228bbe6

Expected result is for the particles to stop moving and resume their velocity when the system is unpaused.

### Steps to reproduce

- Open the attached reproduction project
- Open test_scene.tscn and run the scene.
- Observe how both particle systems are playing properly
- Press space bar to pause the game and observe that the particles of the left particle system disappear.
- Press space bar again to unpause, and observe how the left particle system restarts emission.

### Minimal reproduction project

[GPUParticlesTest.zip](https://github.com/godotengine/godot/files/12892432/GPUParticlesTest.zip)

**Comment by akien-mga** [comment]
I can confirm the bug in 4.2-beta1, and it seems to work fine in 4.2-dev6, so it's very likely a regression from #79527. CC @QbieShay

**Comment by QbieShay** [comment]
Could you add a video of the expected behaviour?

**Comment by tivec** [comment]
https://github.com/godotengine/godot/assets/717574/3e3bab36-95d0-4ae1-a061-6a2626273e2f

In this video I pause the game on a 4.1.2 build, where it shows the expected behaviour of the particles stopping where they are when the game is paused, and resuming when the game is unpaused.

**Comment by QbieShay** [comment]
Thank you! Having a video is just simpler for me to know the target ^^ thanks for your patience. I'll need to investigate a little because I do not think i touched specifically in the way particles are emitted, so i'll need to first do a bisect and make sure I introduced that bug with the big PR (which is likely, but not sure)

**Comment by tivec** [comment]
> Thank you! Having a video is just simpler for me to know the target ^^ thanks for your patience. I'll need to investigate a little because I do not think i touched specifically in the way particles are emitted, so i'll need to first do a bisect and make sure I introduced that bug with the big PR (which is likely, but not sure)

Absolutely no problem, I know how hard it can be to understand how a random user sees how something should function, having the video should help you see the intended results the best way :)

**Comment by QbieShay** [comment]
Confirmed it's introduced by my PR. Now, why, it's something i'll try to figure out asap :D
