### ISSUE TITLE
[macOS 12 x86_64] 4.2 beta1+ crashes trying to launch Compatibility mode project due to ANGLE lib not being compatible

### ISSUE THREAD

**Issue by aitorciki** [godotengine/godot#83269]
### Godot version

v4.2.beta1.official[b1371806a]

### System information

Godot v4.2.beta1 - macOS 12.7.0 - Compatibility - integrated Intel(R) Iris(TM) Graphics 6100 - Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 Threads)

### Issue description

Godot 4.2 crashes when creating or opening a project using Compatibility rendering mode on Intel macOS (12.7):

```
Godot Engine v4.2.beta1.official.b1371806a - https://godotengine.org
ERROR: Can't create an EGL display.
   at: _get_gldisplay_id (drivers/egl/egl_manager.cpp:60)
ERROR: Condition "gldisplay_id < 0" is true. Returning: ERR_CANT_CREATE
   at: window_create (drivers/egl/egl_manager.cpp:188)
ERROR: Can't create an OpenGL context.
   at: _create_window (platform/macos/display_server_macos.mm:196)
ERROR: Condition "main_window == INVALID_WINDOW_ID" is true.
   at: DisplayServerMacOS (platform/macos/display_server_macos.mm:4470)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.beta1.official (b1371806ad3907c009458ea939bd4b810f9deb21)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff8110f9dfd _sigtramp + 29
[2] 2   ???                                 0x0000000000000001 0x0 + 1
[3] RendererCompositorRD::_create_current()
[4] RendererCompositorRD::_create_current()
[5] RendererCompositorRD::_create_current()
[6] 6   dyld                                0x000000011208a52e start + 462
-- END OF BACKTRACE --
================================================================
```

The same project opens successfully in Godot 4.1.2. Converting the project to Forward+ also results in a successful launch.

### Steps to reproduce

Creating a new project using Compatibility rendering mode from the manager results in the crash.

### Minimal reproduction project

`project.godot`:

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="MacOSGL"
config/features=PackedStringArray("4.1", "GL Compatibility")
config/icon="res://icon.svg"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
```

**Comment by aitorciki** [comment]
Error persists in 4.2 beta 4, I hoped #83988 could have helped, but I'm getting the same result:

```
Godot Engine v4.2.beta4.official.93cdacbb0 - https://godotengine.org
ERROR: Can't create an EGL display.
   at: _get_gldisplay_id (drivers/egl/egl_manager.cpp:65)
ERROR: Condition "gldisplay_id < 0" is true. Returning: ERR_CANT_CREATE
   at: window_create (drivers/egl/egl_manager.cpp:193)
ERROR: Can't create an OpenGL context.
   at: _create_window (platform/macos/display_server_macos.mm:196)
ERROR: Condition "main_window == INVALID_WINDOW_ID" is true.
   at: DisplayServerMacOS (platform/macos/display_server_macos.mm:4545)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.beta4.official (93cdacbb0a30f12b2f3f5e8e06b90149deeb554b)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff8110f9dfd _sigtramp + 29
[2] 2   ???                                 0x0000000000000001 0x0 + 1
[3] RendererCompositorRD::_create_current()
[4] RendererCompositorRD::_create_current()
[5] RendererCompositorRD::_create_current()
[6] 6   dyld                                0x000000011b2d252e start + 462
-- END OF BACKTRACE --
================================================================
```

**Comment by akien-mga** [comment]
This is probably the same issue as #83669, the ANGLE libraries might not be compatible with macOS 12.7.

The crash in RendererCompositorRD is a bit weird, I guess we're trying to fall back to Forward+ or Mobile but somehow this logic doesn't work properly.

Does it work if you run the project from the command line with:
```
path/to/Godot --path path/to/project --rendering-driver opengl3
```
This should force using the native OpenGL drivers instead of ANGLE (which is controlled by `opengl3_angle`).

If you can then open the project successfully in the editor, you can change the `rendering/gl_compatibility/driver.macos` setting to `opengl3` to enforce it.

**Comment by akien-mga** [comment]
Ah I misinterpreted the versions, I thought this was 10.12, not 12. So it may be a different issue to #83669 in the end.

**Comment by akien-mga** [comment]
@aitorciki Could you confirm if #83753 fixes the crash by testing this custom build I made after merging it?
https://downloads.tuxfamily.org/godotengine/testing/Godot_v4.2-beta_8fc215893_macos.universal.zip

I guess this wouldn't strictly fix this issue as we expect ANGLE to work fine on macOS 12.7, so this requires further investigation. But it would be good if OpenGL still works out of the box by falling back to the native driver.

**Comment by aitorciki** [comment]
Still the same error with your custom build 😞 

```
Godot Engine v4.2.beta.official.8fc215893 - https://godotengine.org
ERROR: Can't create an EGL display.
   at: _get_gldisplay_id (drivers/egl/egl_manager.cpp:65)
ERROR: Condition "gldisplay_id < 0" is true. Returning: ERR_CANT_CREATE
   at: window_create (drivers/egl/egl_manager.cpp:193)
ERROR: Can't create an OpenGL context.
   at: _create_window (platform/macos/display_server_macos.mm:196)
ERROR: Condition "main_window == INVALID_WINDOW_ID" is true.
   at: DisplayServerMacOS (platform/macos/display_server_macos.mm:4552)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.beta.official (8fc215893af3ea54a8fbd001caee0ce968d206d9)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x00007ff8110f9dfd _sigtramp + 29
[2] 2   ???                                 0x0000000000000001 0x0 + 1
[3] RendererCompositorRD::_create_current()
[4] RendererCompositorRD::_create_current()
[5] RendererCompositorRD::_create_current()
[6] 6   dyld                                0x000000011ab1952e start + 462
-- END OF BACKTRACE --
================================================================
```

**Comment by aitorciki** [comment]
I've compiled current master (6afd320984) with and without `angle_libs`, just to compare to beta and the provided custom build when building on macOS 12 + Intel:
* Compiling *with* `angle_libs` has the exact same result, Godot crashes not fallbacking to `opengl3` printing `ERROR: Can't create an EGL display` unless `opengl3` is forced.
* Compiling *without* `angle_libs` launches the project successfully with `opengl3` by default, and when forced to use ANGLE with `--rendering-driver opengl3_angle` if will fallback successfully to `opengl3` after printing `ERROR: Can't load EGL`.

**Comment by YuriSizov** [comment]
@aitorciki Could you see how the current master behaves, after https://github.com/godotengine/godot/pull/84288 was merged?

**Comment by aitorciki** [comment]
Looking good! Properly falls back to OpenGL displaying `ERROR: Can't create an EGL display.` in the terminal 👍

**Comment by YuriSizov** [comment]
Sweet! Let's assume the crash is fixed with https://github.com/godotengine/godot/pull/84288 which closes the issue. I think there are still some concerns about how ANGLE is behaving, but that should probably be tracked separately.
