### ISSUE TITLE
NavigationPolygon baking ignores inner polygons

### ISSUE THREAD

**Issue by 3lis4** [godotengine/godot#83261]
### Godot version

4.2.beta1

### System information

Linux Mint 21

### Issue description

NavigationRegion2D's NavigationPolygon ignores inner polygons: you can't obtain similar results to what's stated in the documentation (https://docs.godotengine.org/en/stable/_images/nav_polymatroschka.png).

Instead you'll get this result which ignores the inner polygon:
![navigation_polygon_issue](https://github.com/godotengine/godot/assets/45194613/1cdcaab6-7457-42e3-9737-2f8c68ddc4d2)

### Steps to reproduce

1. Open MRP navigation_region_2d.tscn
2. Click "Clear NavigationPolygon"
3. Click "Bake NavigationPolygon"

### Minimal reproduction project

[MRP_NavigationPolygon.zip](https://github.com/godotengine/godot/files/12892699/MRP_NavigationPolygon.zip)

**Comment by smix8** [comment]
You are on a beta version, the documentation has not been updated yet.

For now you can find information in the pr that added the 2D navigation mesh baking. https://github.com/godotengine/godot/pull/80796

For that specific issue here see the "Compatibility" section. If you want reliable holes add obstructions.

**Comment by 3lis4** [comment]
Thank you, I missed this new development and thought something had been unintentionally broken.

From the Compatibility section:
> This also means that outlines "nested" inside other outlines will no longer create holes by default

In previous versions (for instance 4.0.3-stable), I could draw inner polygons clockwise and non-clockwise, they all became holes. I thought inner polygons weren't detected at all in 4.2.beta1, but actually holes are created only from clockwise inner polygons. Is it intended?

Also, by "obstructions" you mean NavigationObstacle2D or something else?

Thanks!

**Comment by smix8** [comment]
> by "obstructions" you mean NavigationObstacle2D or something else?

I mean an obstruction polygon, can be anything. E.g. a StaticBody2D, a Polygon2D or just another outline array added with scripts to the SourceGeometryData obstruction array.

> In previous versions (for instance 4.0.3-stable), I could draw inner polygons clockwise and non-clockwise, they all became holes.

Until they didn't. The "hole" drawing is mostly a thing of the past. You can still try to force some holes with outline winding order but it is not recommended or actively supported. You can also bake the outlines with the old "hole" algorithm by using the NavigationPolygon.make_polygons_from_outlines() function.

**Comment by 3lis4** [comment]
Thank you for your answer. I have two questions:

1. As obstruction outline array needs scripting, what is now the supported in-editor way to draw polygons with holes/obstacles? 

2. Also, the Compatibility section of https://github.com/godotengine/godot/pull/80796 mentions it shouldn't create holes from inner polygons anymore (_"outlines "nested" inside other outlines will no longer create holes"_). But we can still create hole from clockwise inner polygons. If this behavior is not supported anymore, I think it should be completely removed. Is it something I should report on https://github.com/godotengine/godot/pull/80796 or is it intended?

**Comment by smix8** [comment]
1.) Preferably place obstruction objects like a StaticBody2D or Polygon2D for holes. Drawing polypath "holes" is inherently unreliable, more detail below, so if you absolutely have to use the draw tool, draw polygons around the hole instead of drawing the hole. E.g. do the same as the rendering does, because rendering can not draw polygon holes either, it draws multiple polygons around them just leaving that space empty.

2.) You can't remove the chance for "holes" completely. Complex polypath ops yield very different results depending on layout and fillrule and there is no one-size-fits-all because there is no fillrule that works for every layout. You can find more information about fillrules and polypath ops on the Clipper2 doc [here](https://angusj.com/clipper2/Docs/Units/Clipper/Types/FillRule.htm).
