### ISSUE TITLE
(Not a Bug)Copyed Scene content to a new Scene follows the originals scene components settings

### ISSUE THREAD

**Issue by FlyingJudgement** [godotengine/godot#83274]
### Godot version

4.1.1.stable.official

### System information

Win 10

### Issue description

Add an Area 2D, as a child add a Collision shape 2D  add a shape.
Make a Variant coppy the components and create a new scene, Paste the content. Give new name save it.
Change the Collision shape 2D in either of them, changes in the other.

### Steps to reproduce

Add an Area 2D, as a child add a Collision shape 2D  add a shape.
Make a Variant coppy the components and create a new scene, Paste the content. Give new name save it.
Change the Collision shape 2D in either of them, changes in the other.

### Minimal reproduction project

Add an Area 2D, as a child add a Collision shape 2D  add a shape.
Make a Variant coppy the components and create a new scene, Paste the content. Give new name save it.
Change the Collision shape 2D in either of them, changes in the other.
```[tasklist]
### Tasks
```

**Comment by zhagsenkk** [comment]
I think this isn't a bug. They use the same resourse(the same collision shape).

**Comment by AThousandShips** [comment]
You are indeed sharing the resources, this is not a bug, see [here](https://docs.godotengine.org/en/stable/getting_started/step_by_step/instancing.html#editing-scenes-and-instances)

**Comment by FlyingJudgement** [comment]
Isn't the copyed collision shape suppose to be a new collision shape component, and the pointer point to the newley created collision shape instead the original?   
They aren't the same instance, they are all live in new scenes with new commponents.
I guess is debatable and depends on use case. Thanks for the documentation I plan with this next time.

**Comment by AThousandShips** [comment]
The nodes are new, the resources are not :)

**Comment by AThousandShips** [comment]
You might be coming from another environment that is ECS based, we don't have "components" in Godot, so the approach is probably very different

**Comment by FlyingJudgement** [comment]
Yeah thought it through godot uses Resources, Got it! I suppose to create a new "resource" like a "material" or texture map, just by copy pasting something in the inspector cannot and should not duplicate files all ower the project. 
Thanks for the explanation and apology for my confusion, yes godot uses a lot more type of "Resources" than I'am used to.

**Comment by AThousandShips** [comment]
There's instructions in the link to how to stop them being shared
