### ISSUE TITLE
Drag-and-drop does not work in web editor.

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#83277]
### Godot version

4.2.beta1

### System information

Godot v4.2.beta1 - Web - GLES3 (Compatability) - WebKit WebGL - (2 Threads)

### Issue description

Whenever you try to drag and drop a file into the FileSystem on the web editor, it gives me this error “Failed to open /tmp/drop-(number)/(image file name).(file extension” (replace parentheses with file) I found out you can add files by downloading the project source, unzipping, adding the file, zipping, and then re-importing.

### Steps to reproduce

1. Create and open a new project
2. Try to drag a file onto the FileSystem

### Minimal reproduction project

N/A

**Comment by Qainguin** [comment]
I checked and it does not have this problem on Windows.

**Comment by MIfoodie** [comment]
Could not reproduce on Chromebook.

**Comment by Qainguin** [comment]
Somehow it was fixed. Closing.
