### ISSUE TITLE
The editor viewport with wrong size

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#8328]
**Operating system or device - Godot version:**
Godot 3.0 on Arch Linux - x86_64 compiled with 4286aef69313e048fa91710c35456c08a252fd3c

**Issue description:**

The window size in project settings is 1024x600 but the viewport of the editor canvas seems to be 1294x815.
* The panel should be the same size as viewport.
* The viewport size is not same with the rectange drawing in the canvas.
* The viewport size may be changed by other nodes.
![2017-04-09 11-21-10](https://cloud.githubusercontent.com/assets/6964556/24834414/cacf5594-1d16-11e7-8bc6-1186636d256c.png)
![2017-04-09 11-21-53](https://cloud.githubusercontent.com/assets/6964556/24834438/a6b5b396-1d17-11e7-98dc-6dea4071ebd4.png)

**Steps to reproduce:**
* Create a panel as the root node
* Set the size of the panel to be fill parent
* Zoom the canvas

**Comment by bojidar-bg** [comment]
Uhm. Sure it isn't a feature again?
