### ISSUE TITLE
Wrong padding of dropdown menu icons in Editor

### ISSUE THREAD

**Issue by bitbotzgames** [godotengine/godot#83282]
### Godot version

v3.6 beta3 official

### System information

Windows 10, OpenGL ES 3.0 Renderer

### Issue description

All icons in dropdown menus in the Editor are having wrong padding.

Here you see the file menu when rightclicking a file in the FileSystem (v3.6 beta3):
![File Menu 3 6](https://github.com/godotengine/godot/assets/83534976/e0890207-bbb6-40e8-9cc2-486066a9a899)

In Godot 3.5.3 the icons were still fine:
![File Menu 3 5 3](https://github.com/godotengine/godot/assets/83534976/b4bccf3c-e5f1-440d-b12e-472c9a171f7e)

### Steps to reproduce

Open the v3.6 beta3 official Editor and open a menu with icons in it.

### Minimal reproduction project

Only the Editor is needed for testing

**Comment by Calinou** [comment]
This appears to be the case since 3.6.beta1. I'll look into bisecting this.

**Comment by Chubercik** [comment]
If this was reported in `3.6.beta3` why is the milestone set to `4.x`?

**Comment by Calinou** [comment]
> If this was reported in `3.6.beta3` why is the milestone set to `4.x`?

Fixed.

**Comment by rsubtil** [comment]
This was fixed by https://github.com/godotengine/godot/pull/81409
