### ISSUE TITLE
Godot Incorrect Trimesh Collision Shape Warning

### ISSUE THREAD

**Issue by jcovin293** [godotengine/godot#83298]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When creating a trimesh collision shape from a ```MeshInstance3D```, a warning is given explaining that the scale should be uniform for it to work properly. I have tested this and the collision shape works properly and it will not work if I make all dimensions equal. This warning is incorrect and can be misleading although it may be correct in other situations.

### Steps to reproduce

1. Create a ```MeshInstance3D```
2. Add a ```StaticBody3D``` as the parent to the ```MeshInstance3D```
3. Add a trimesh as a sibling to the ```MeshInstance3D```
4. View the incorrect warning

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Do you mean this warning:
> A non-uniformly scaled CollisionShape3D node will probably not function as expected.
> Please make its scale uniform (i.e. the same on all axes), and change the size of its shape resource instead.

**Comment by AThousandShips** [comment]
How have you confirmed that there's no problems with this? Have you tried every situation?

The warning, assuming it's the one above, doesn't say it will not ever work, but warns that it isn't guaranteed to work, this is, as far as I know, correct, so the warning isn't incorrect

**Comment by jcovin293** [comment]
Currently, my scale is 20x1x20 as shown in the photo below where the trimesh collision shape is properly covering the mesh.
<img width="707" alt="Screenshot 2023-10-14 at 09 55 23" src="https://github.com/godotengine/godot/assets/111152655/ffb7580f-64b1-4594-9469-6f73c94cc7be"> 

When I change the scale to 20x20x20, it stretches and no longer collides correctly.
<img width="545" alt="Screenshot 2023-10-14 at 09 55 45" src="https://github.com/godotengine/godot/assets/111152655/9e011fd2-0915-49d9-a5a8-d3a99cdbef4e">

**Comment by AThousandShips** [comment]
Is the scale of the original model also 20x1x20?

**Comment by jcovin293** [comment]
Yes, should I change the scale to something else when I designed it in Blender?

**Comment by AThousandShips** [comment]
You shouldn't make the models you're going to use have to be scaled when you use them

Back to the original question:
How did you confirm that nothing is broken when scaled non uniformly?

**Comment by jcovin293** [comment]
When running my scene, the collision has no problems with my player so it has been working despite non uniform scale.

**Comment by AThousandShips** [comment]
That's not really enough to claim that the warning is incorrect though, right?

**Comment by jcovin293** [comment]
I agree, the warning is fully incorrect, but I believe that it should be able to be dismissed because my scene is properly working. Could you clarify, is the warning saying to make the ```CollisionShape3D``` uniformly scaled but the ```MeshInstance3D``` potentially uniformly scaled if needed?

**Comment by AThousandShips** [comment]
I don't know I asked above what warning it was, but if it is the warning I asked you to confirm them it says that it's the collision shape

**Comment by jcovin293** [comment]
Sorry, I forgot to confirm, the warning is the one you mentioned above:

> A non-uniformly scaled CollisionShape3D node will probably not function as expected.
Please make its scale uniform (i.e. the same on all axes), and change the size of its shape resource instead.

**Comment by AThousandShips** [comment]
Then yes, it says "CollisionShape3D" right there :)

**Comment by AThousandShips** [comment]
> I agree, the warning is partially incorrect

How can it be partially incorrect? It doesn't say "it never works"

**Comment by jcovin293** [comment]
I think before showing the warning, maybe it could be checked to see if the MeshInstance and CollisionShape have the same scale because in that case, it should work as expected. I do not think the message was incorrect but when it showed up was incorrect.

**Comment by AThousandShips** [comment]
No that's not how it works, it isn't about the mesh, it's about how scaled shapes might not work right with the physics, it doesn't have anything to do with the model 

It isn't saying "it might not match your mesh" it says "the physics engine might not work right for scaled shapes"

**Comment by jcovin293** [comment]
Sorry for the misunderstanding, should I close this issue?

**Comment by AThousandShips** [comment]
No problems, indeed as this warning is relevant

**Comment by AThousandShips** [comment]
See the [documentation](https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#collision-shapes) for more details
