### ISSUE TITLE
Pressing ESC from code search should give focus to the code editor

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#83303]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

When editing code in Godot, and searching with Ctrl+F we get a search bar at the bottom of the text editor. When pressing ESC it loses focus... But then - apparently - nothing has focus.

Pressing ESC should return focus to the code editor, as it did until v4.2.dev6.official [57a6813bb]

### Steps to reproduce

While editing code in any project, press CTRL+F to bring up the search bar, then press ESC, and try to write, observe you are no longer writing in the code editor because it does not have focus.

### Minimal reproduction project

N/A

**Comment by malucard** [comment]
I was about to submit this issue. To add though, I get this error in Output when I press anything while the focus is lost:
` scene/main/node.cpp:1766 - Parameter "p_node" is null.`
I guess the focus is being changed incorrectly.
