### ISSUE TITLE
All Godot related programs have a black screen

### ISSUE THREAD

**Issue by AlexCZhou** [godotengine/godot#83307]
### Godot version

4.1.1

### System information

Windows10

### Issue description

All Godot-related programs, including editors and packaged executable files, have a black screen when opened.

I checked #82919 and tried updating Windows 10 and the graphics card driver, but it didn't work and the result was still the same. Tried running version 4.0 of Godot and still the same problem.

I tried clicking on the editor. I just couldn't see the content, but the functions in the editor seemed to be normal. I successfully ran the game in the upper right corner, but they all had black screens.

![image](https://github.com/godotengine/godot/assets/33609801/ee1fe511-c34f-4060-a0a2-7ca9da579d26)
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 537.58 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3070

- - -
update: Try start with Vulkan. got error message after i quiting the black screen.
![cdefeacf119e4d6b174dd9a52fc3855a](https://github.com/godotengine/godot/assets/33609801/5fd31730-ebb0-4e4a-a80d-243e25751a14)
```
D:\TypeAlpha\Documents\Godot4\Godot_v4.1.1-stable_win64.exe>Godot_v4.1.1-stable_win64_console.exe --rendering-driver vulkan
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070

ERROR: Pages in use exist at exit in PagedAllocator: 6Thread
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N16WorkerThreadPool4TaskE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
```

### Steps to reproduce

Start the Godot project

### Minimal reproduction project

N/A

**Comment by darksylinc** [comment]
Chinese users are known to have problems because of #81652 where a WeChat layer injects into Godot.

Try setting VK_LOADER_LAYERS_DISABLE, you can see what layers you have installed with [VulkanCapsViewer](https://github.com/SaschaWillems/VulkanCapsViewer/releases/latest).

The other thing I see viable is that you build Godot from source, break with the Debugger after it gets stuck and post a callstack.

Post the output of running with `--verbose`.

Last but not least, I suspect this might be a Chinese locale issue.

**Comment by AlexCZhou** [comment]
> Chinese users are known to have problems because of #81652 where a WeChat layer injects into Godot.
> 
> Try setting VK_LOADER_LAYERS_DISABLE, you can see what layers you have installed with [VulkanCapsViewer](https://github.com/SaschaWillems/VulkanCapsViewer/releases/latest).
> 
> The other thing I see viable is that you build Godot from source, break with the Debugger after it gets stuck and post a callstack.
> 
> Post the output of running with `--verbose`.
> 
> Last but not least, I suspect this might be a Chinese locale issue.

Issues #81652 also created by me. I'm pretty sure it's not the same issue. Because I have uninstalled the program that was causing the problem before. 

But now I can't reproduce this problem. After I restarted tonight, the Godot editor worked normally. I'm not sure if it has something to do with me updating Win10 or the graphics card driver.

**Comment by saierXP** [comment]
> where a WeChat layer injects into Godot.

WeChat -> WeGame @darksylinc
