### ISSUE TITLE
Opening an exported project in Windows 11 gives a warning saying "This application cannot be executed in your PC"

### ISSUE THREAD

**Issue by InkONat** [godotengine/godot#83300]
### Godot version

4.2.beta1, 4.1.2.stable, 4.3.beta1

### System information

Windows 11, AMD Ryzen 7 5700X 8-Core Processor

### Issue description

![image](https://github.com/godotengine/godot/assets/61206149/3b8e43df-8b9d-44e2-9d32-56e6f7b4b3f7)
This image appears when I try to open an exported project, even if empty, in Windows 11.

Translation: 
This application cannot be executed in your PC.
To localize a version for your PC, see your software provider.

For the console version of the exported project, a console window just pops in and out, and the project doesnt open.

If Modify Resources is enabled, RCEdit shows this message:
![image](https://github.com/godotengine/godot/assets/61206149/a6bdd73e-b13e-41fe-aef8-0f30f98871f1)

### Steps to reproduce

1. Create an empty project in Windows 11
2. Make a new Export template from the best available mirror.
3. Open the Export tab and make a new Windows preset.
4. Use any configuration for the preset.
5. Export the project anywhere.
6. Try opening the exported project.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12900989/MRP.zip)

Reproduction steps are trivial, but here's an empty project with export_presets in it anyways.

**Comment by InkONat** [comment]
Answering questions that might appear:

- You forgot RCEdit
No. I tested this with both RCEdit x64 and RCEdit x86. Also, if I didn't have RCEdit, that message wouldn't appear.

- Your PC is x32 and you set the architecture to x86_64
My PC is x64.

- You forgot the icon
I tried using the godot .svg file as icon and it didn't work.

- You didn't set up the File Version and the Project Version correctly
I tried making both 1.0.0.0 and it didn't work.

**Comment by InkONat** [comment]
also, I forgot to set up the file version and project version correctly in the minimal reproduction project, sorry

**Comment by InkONat** [comment]
problem is gone for Godot 4.2.stable, but reappears on Godot 4.3.beta1 for some reason

**Comment by InkONat** [comment]
bump

**Comment by akien-mga** [comment]
Try to re-download export templates, it sounds like your Windows templates are corrupted.

**Comment by InkONat** [comment]
> Try to re-download export templates, it sounds like your Windows templates are corrupted.

When I exported for Windows last time (on version 4.3.beta1), I had downloaded the export templates just a few minutes before exporting, I don't really know how they couldve corrupted so fast

but I'll try that anyways

**Comment by akien-mga** [comment]
I don't mean that they would corrupt over time, but the download itself might have been corrupted (or the antivirus might have corrupted the binary when it was extracted from the export templates zip archive).

**Comment by InkONat** [comment]
> I don't mean that they would corrupt over time, but the download itself might have been corrupted (or the antivirus might have corrupted the binary when it was extracted from the export templates zip archive).

I reinstalled the export templates for 4.3.beta1 and the exported project did work correctly. Thanks!!

I think that there should be some type of warning to show the user that the export template is corrupted in some way and that you should try reinstalling the template.

**Comment by akien-mga** [comment]
> I think that there should be some type of warning to show the user that the export template is corrupted in some way and that you should try reinstalling the template.

Yeah that's a good point, we could validate the SHA-256 sums of all the templates after installing them, to verify whether they got corrupted in the process.

I'll open a proposal about this in coming days.

Closing as the bug was due to a corrupted download so not an engine bug.
