### ISSUE TITLE
specific Area2D nodes cannot emit signals such as "mouse_entered"

### ISSUE THREAD

**Issue by DocMine** [godotengine/godot#83315]
### Godot version

4.2beta1

### System information

windows10 CPU:AMD 5800X Vulkan

### Issue description

I used packedscene instantiation to create a circle of Area2d, and used code to generate the corresponding sector-shaped collision area;
All Area2d's mouse_entered() signals are connected to the same function, which is to update the label;
But the Area2d at the corresponding position in the list is always unable to trigger the signal. I tried other types of signals, but the corresponding Aera2D still cannot detect the status of the mouse;

Project runs as expected in godot 4.1stable
![vd](https://github.com/godotengine/godot/assets/83529333/62778e05-038c-4be6-9a0f-29f5f0232338)

### Steps to reproduce

run choose_plate.tscn as main scene,  and u can see the problem;(with godot 4.2beta1)

### Minimal reproduction project

[Choose_Plate_c.zip](https://github.com/godotengine/godot/files/12904186/Choose_Plate_c.zip)

**Comment by Mickeon** [comment]
There is no bug.  I'm not sure why the wheel has been built this way, but there is no bug.

In your project there's a Control called "_ChoosePlate_". By default Control nodes stop mouse inputs from propagating through. You need to set `mouse_filter` to either "Pass" or "Ignore".

![image](https://github.com/godotengine/godot/assets/66727710/b6edc3da-1f65-4dca-834f-d56befaf2ef0)

**Comment by DocMine** [comment]
oh! This is indeed an oversight on my part. Thank you for your answer. I should first look for answers on the community before submitting an issue; thank you again for your time.
