### ISSUE TITLE
Weblate lockdown issue

### ISSUE THREAD

**Issue by yilmazdurmaz** [godotengine/godot#83321]
### Godot version

any on Weblate

### System information

any

### Issue description

Last night all Weblate projects went down under a lockdown due to a communication problem with GitHub. all my lockdown notification went crazy, email provider marked them as spam (I work on many projects). 

Please check and remove the lockdown

````
fatal: unable to access 'https://github.com/godotengine/godot-editor-l10n/': Empty reply from server
````

example Editor component alert page: https://hosted.weblate.org/projects/godot-engine/godot/#alerts

let me also link another issue I opened on another project with the same problem: https://github.com/hedyorg/hedy/issues/4624

PS: interesting that documents component did not affected by this problem. you may want to check why it deflected the issue to enhance other component

(@timothyqiu, you are the most active admin on Weblate, so I am tagging you here)

### Steps to reproduce

It is a Weblate components issue I cannot reprodue

### Minimal reproduction project

no project is needed.

**Comment by akien-mga** [comment]
Thanks for the report. I've triggered a manual update and the repos are open again.

**Comment by yilmazdurmaz** [comment]
> Thanks for the report. I've triggered a manual update and the repos are open again.

great news, thanks
