### ISSUE TITLE
Autoplay animation of `AnimationPlayer` starts one frame late

### ISSUE THREAD

**Issue by TamerSoup625** [godotengine/godot#83326]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.3889) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

In Godot 4.2, autoplayed animations by `AnimationPlayer` no longer set properties on the frame the node enters the tree. It rather does it one frame later, which can cause visuals to "flash" for a frame if the default values of the properties are different from the ones of the first property keys of the autoplayed animation, which happened in my project when porting it to 4.2.

(Here I set Engine.max_fps to 15 to make the bug clearer)

https://github.com/godotengine/godot/assets/107559799/5972b8fc-1fe6-4f2f-9c3a-4c64e5862c69

### Steps to reproduce

1. Create an `AnimationPlayer` and a node to animate
2. Create a new animation in the newly created `AnimationPlayer`
3. Add a new property track in the animation with RESET keys
4. Set the first key's value to one different from the RESET animation's value
5. Set this animation to autoplay
6. Add a script which prints the property value on ready:
```gdscript
func _ready():
    print($<path to animated node>.<animated property>)
```
7. Run the scene and notice how it prints the default value

### Minimal reproduction project

[animation_autoplay_bug.zip](https://github.com/godotengine/godot/files/12905385/animation_autoplay_bug.zip)

**Comment by TamerSoup625** [comment]
I should note that this is a regression, I didn't have this problem while creating the project in Godot 4.1

**Comment by toxic-sludge-development** [comment]
This same thing is still happening when using an animation tree
