### ISSUE TITLE
Adding `@export_group("Texture")` adds `texture_filter` and `texture_repeat` properties

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#83336]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

Adding `@export_group("Texture")` in a script makes properties `texture_filter` and `texture_repeat` appear on Inspector.

![image](https://github.com/godotengine/godot/assets/96864661/beecc7fe-baeb-403a-b41b-e5472f2c4e94)

### Steps to reproduce

Create any node with these lines in the script:
```
@export_group("Texture")
@export var foo: String
```

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/12906167/bug.zip)

**Comment by AThousandShips** [comment]
These are inherited from `CanvasItem` seems that using a group already used in a parent class causes some weird behaviour
