### ISSUE TITLE
Shading errors on gltf imports

### ISSUE THREAD

**Issue by Faradax** [godotengine/godot#83345]
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Godot v4.2.beta1.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 Threads)

### Issue description

I'm using blender to export assets as gltf. When importing gltfs into Godot 4.2, I observe shading issues where parts of surfaces are darker or lighter in odd spots. 
As a minimal example, I can even reproduce this with blenders "default cube" as it appears at the startup of the application without any modifications to either mesh or material. Checking "Data>Mesh>Tangets" on export does not affect the outcome.

In the following two pictures, the left cube is the imported blender default cube, the right one is a MeshInstance3D with a 2x2x2 BoxMesh for comparison.

v4.2.beta1.mono.official [b1371806a]
![image](https://github.com/godotengine/godot/assets/5133378/9e83b6f2-f402-4d0c-af52-7567f1884474)

When I import the same gltf in v4.1.1.stable, the result looks correct, so I assume this to be a regression:
v4.1.1.stable.mono.official [bd6af8e0e]
![image](https://github.com/godotengine/godot/assets/5133378/e224460b-0443-4cf1-ac0b-390b0f531a5c)

Other simple examples of some subdivided/beveled cubes, as seen in the "Advanced Import Settings" dialog in v4.2.beta1.mono.official [b1371806a]:
![image](https://github.com/godotengine/godot/assets/5133378/6e6ae952-78c9-4d52-8627-30bb2b64b617)
![image](https://github.com/godotengine/godot/assets/5133378/80edb38d-2ace-4aa7-ab0d-9bc0df69fec5)

### Steps to reproduce

- Export blender default cube as gltf
- Import in v4.2.beta1.mono.official [b1371806a]

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Can you try reimporting with force disable compression enabled in the import settings?

**Comment by Faradax** [comment]
Enabling the "Force disable compression" option gives this difference (left with option disabled, right with option enabled):

v4.2.beta1.mono.official [b1371806a]
![image](https://github.com/godotengine/godot/assets/5133378/622b17a0-a983-4b4c-aeb0-deb5cb77fa82)

So it does indeed seem to prevent this issue.

**Comment by stevenctl** [comment]
Force disable makes a difference, things still look odd. 

<details>

<summary>Screenshots</summary>

**Force disable off:** 

![noforcedisable](https://github.com/godotengine/godot/assets/16195656/225b8722-e777-4138-8e50-7d7c88dd362c)

**Force disable on:**

![forcedisable](https://github.com/godotengine/godot/assets/16195656/9acb76c8-f0d7-45c8-b68e-74ebc311418b)

Here's 4.1.1

![orig](https://github.com/godotengine/godot/assets/16195656/60b6abb4-daba-4745-ad8d-c846c638fbb4)

</details>

**Comment by clayjohn** [comment]
@stevenctl are you able to share that mesh?

**Comment by stevenctl** [comment]
[bugmesh.zip](https://github.com/godotengine/godot/files/12908602/bugmesh.zip)

Looks like verts are duplicated on export from Blender. Trying to merge vertices and re-export/import yields the same separation of verts. Importing to 4.1.1 looks ok though.

**Comment by Faradax** [comment]
For the mesh @stevenctl provided, I get a correct-looking import if I disable "Ensure Tangets". "Force Disable Compression" doesn't affect the result after that.

**Comment by lyuma** [comment]
Is this the same issue as #84270 ?

Is this fixable in cases of incorrect normals or are we hitting some limit of mesh compression?

Also, is there a way to *detect* that we have significantly distorted normals with mesh compression and warn the user, disable compression or fail the import in such cases?
