### ISSUE TITLE
Compatibility Renderer Light Problems

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#83340]
### Godot version

4.2 Beta 1

### System information

Godot v4.2.beta (ee118e7ff) - Windows 10.0.22621 - GLES3 (Compatibility) - AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 Threads)

### Issue description

The lights start swimming along, typically when you reach the limit of lights you can render.

https://github.com/godotengine/godot/assets/50302479/96e153f5-e815-4ebd-adec-8d35b5e024cd

Another issue is that Light culling seems to be broken, as is evident given that you can look on a large object with 9 lights, and if you're in a position where only a few lights are in the view frustum it will still be trying to render the lights that should have been culled (on the vulkan renderers this works properly, and it is possible the issue above is related to this culling problem)

I remember the Mobile renderer had practically the same issue a while back

### Steps to reproduce

Move the camera around and observe what's happening on the Plane

### Minimal reproduction project

[Issue.zip](https://github.com/godotengine/godot/files/12906604/Issue.zip)

**Comment by AThousandShips** [comment]
There's because there's a limit, see `rendering/limits/opengl/max_lights_per_object`
