### ISSUE TITLE
Godot crash when "Close All Tabs" is selected in the editor

### ISSUE THREAD

**Issue by Salt-City** [godotengine/godot#83355]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.3.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

Whenever there is more than one tab open in the editor, selecting "Close All Tabs" will cause a hard crash to desktop
[System Crash Report](https://github.com/godotengine/godot/files/12908232/crash.txt)
[Video of the crash](https://youtu.be/oV2l3X8hDYk)

### Steps to reproduce

Open Godot 4.1.1 stable
Open more than one existing scenes as tabs
Right click on the first tab and select "Close All Tabs"

### Minimal reproduction project

N/A

**Comment by Stronkkey** [comment]
I was able to replicate this on v4.1.1stable but not on v4.2beta. Might have been fixed already.

**Comment by Calinou** [comment]
That PR was cherry-picked in 4.1.2, so please test 4.1.2.
