### ISSUE TITLE
SubViewport error happening in editor with no subviewports in scenes.

### ISSUE THREAD

**Issue by PixelDrennen** [godotengine/godot#83350]
### Godot version

Godot v4.1.2.stable.mono 

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3734) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

In my project, I'm getting:

```
Path to node is invalid: 'SubViewport'.
scene/main/viewport.cpp:165 - Viewport Texture must be set to use it.
```

I do have a packedscene that uses a subviewport, but this is added to the scene after running the build in the correct start scene. Outside that, I'm not using any subviewports. I get this error anytime I restart godot or sometimes after compiling. I also get it after saving.
The scenes I have open are a test scene and a game scene, neither of which have any subviewports in them. 
I couldn't find any other issues on this, but please feel free to point me to them if I missed it.
Thanks for any help

### Steps to reproduce

Unsure, but my context is that I have a packed scene with a tree that looks like: Camera3D > Subviewport > Camera3D 
This packed scene gets added in a function called InitializePlayer() where the packed scene is instantiated and added to the tree of the active scene.
That's all I know to put in the steps for repro, because outside of that my project doesn't have anything crazy going on. Hitting play just loads the Game scene and from there the player is instantiated along with the camera packed scene.
My subviewport is set to the size of the screen (full rect) and a rendertexture is used to display the results on an overlay camera.

Here are some contextual classes I am using that may or may not have something to do with this
[https://pastebin.com/wUFe3bAB](https://pastebin.com/wUFe3bAB )

### Minimal reproduction project

N/A

Edit: Found duplicate #27790

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/27790.

(In the future, please close the issue yourself if you find a duplicate.)

**Comment by PixelDrennen** [comment]
> Thanks for the report! Consolidating in #27790.
> 
> (In the future, please close the issue yourself if you find a duplicate.)

I was clicking just as you commented! Thanks :)
