### ISSUE TITLE
Change type node, delete all content

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#83358]
### Godot version

4.2 beta 1

### System information

openSUSE tumbleweed 

### Issue description

Click on a node, right click Change Type..., delete all content (all child nodes).

Also, have some a few more bugs, should have add them here or in other issue report?

### Steps to reproduce

Click on a node, right click Change Type..., delete all content.

### Minimal reproduction project

Mmm, my project is big. This also could be do it in a new proyect.

**Comment by kleonc** [comment]
> ### Steps to reproduce
> 
> Click on a node, right click Change Type..., delete all content.

I've just done this, no problems at all.


> ### Issue description
> 
> Click on a node, right click Change Type..., delete all content (all child nodes).

But what's the issue/bug? Seems like you forgot to describe it. You wrote the same thing as in "steps to reproduce" and it doesn't tell what's wrong.

> Also, have some a few more bugs, should have add them here or in other issue report?

Separate bugs should be reported in separate issues. But please be more descriptive/detailed.

**Comment by AThousandShips** [comment]
By "delete all content" do you mean "you should delete all content" or "it deletes all content"?

**Comment by Some1ls** [comment]
@AThousandShips I just experienced it. It deleted all child nodes.

**Comment by chriztheanvill** [comment]
> By "delete all content" do you mean "you should delete all content" or "it deletes all content"?

It deletes all content.

**Comment by YuriSizov** [comment]
Can you provide more detailed steps of what you do? Specific nodes that you use?

**Comment by chriztheanvill** [comment]
> Can you provide more detailed steps of what you do? Specific nodes that you use?

My enemy scene:
* CharacterBody3D <--- as Root
* CollisionShape3D
* 2 AnimatedSprite3D
* NavigationAgent3D
* 4 Area3D
* 2 Sprite3D

Also get noticed, when working with inherited scenes, if I add something, then delete it, sometimes does not delete it in inherited scenes, and godot shows errors about that.
To resolve this:
With a text editor, open that scene, and remove that component: Sometimes has weird names like `@asdasdasdasNode`

**Comment by CsloudX** [comment]
I'm meeting this bug too, but not found a minimal reproduction project yet.
![GIF](https://github.com/godotengine/godot/assets/35988767/4be402c9-fc8e-486c-a5bf-8989cd72c1e2)

And the ouput has this messages. Wish have some helpes.
![image](https://github.com/godotengine/godot/assets/35988767/5e956294-1097-4af9-a305-af46a70819e7)

**Comment by JeremyCarlsten** [comment]
Also experienced this with an Area2D that I changed to a Node2D while restructuring how it works. This was a "interface" type scene with multiple children. No errors in the output.  It did not actually change the type, just deleted all the child nodes and renamed it from Weapon to Weapon2.

**Comment by AThousandShips** [comment]
Anyone that can replicate this please provide an MRP, otherwise this is impossible to figure out

**Comment by KoBeWi** [comment]
This should've been fixed in 4.3. Can someone confirm?

**Comment by Cyberflunk2** [comment]
I can confirm this bug is fixed in Godot 4.3

I had the same problem changing a node2D into StaticBody2D.
