### ISSUE TITLE
Missing place to put not bug issues from end-users of the editor

### ISSUE THREAD

**Issue by mellonedain** [godotengine/godot#83352]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I want to add not bug related issue for the editor as a programmer. At the moment https://ask.godotengine.org/ in in maintenance mode and looks like inactive and it require to looking alternative ways. At the moment I've added it to the Asset Library as an Issue here: https://github.com/godotengine/godot-asset-library/issues/305. Place like this allow us to give You feedback e.g. from our experienced not only related with bugs directly. 

### Steps to reproduce

Writing game and using editor. For example copy code from website.

### Minimal reproduction project

Any Gotor project

**Comment by AThousandShips** [comment]
There are other community channels where people can ask questions while the Q&A is being worked out, like discord and social channels

**Comment by Calinou** [comment]
There is already a platform to submit feature proposals: https://github.com/godotengine/godot-proposals
