### ISSUE TITLE
Disabling filter in Project settings crashes Godot

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#8335]
**Operating system or device - Godot version:**
Godot 2.1.2 Linux 64 bit (from Steam)

**Issue description:**
Disabling filter option in project settings crashes Godot when checkbox on left side is disabled

**Steps to reproduce:**
- go to Projects Settings > General > Image Loader
- click on checkbox on right side of `filter`

**Workaround**
- turn on left checkbox

**Comment by akien-mga** [comment]
Duplicate of #7696, fixed in 2.1.3.
