### ISSUE TITLE
Godot Running Project Exit Error

### ISSUE THREAD

**Issue by LotusLegends** [godotengine/godot#83363]
### Godot version

4.1.2-stable , 4.2 beta

### System information

Android Infinix smart 5, 32-bit

### Issue description

When i run a project in godot android editor then for back
In editor i click back button of my mobile godot can exit
Fully not only running game.
How i fix it.

### Steps to reproduce

Open android godot editor and open a project then click
Run project button then when you click back button of android
Divice it back to android home screen not godot editor.

### Minimal reproduction project

That problem in godot not in project i tried
Alot of time.

**Comment by LotusLegends** [comment]
[New Game Project.zip](https://github.com/godotengine/godot/files/12908541/New.Game.Project.zip)

**Comment by ltecheroffical** [comment]
This affects versions other than mobile including all desktop platforms.

**Comment by EarthDLL** [comment]
Autually , #79291 did not fix this bug

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79291.
