### ISSUE TITLE
Folder color doesn't show up in file dialogs

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#83366]
### Godot version

v4.2.beta.custom_build [a574c0296]

### System information

linux

### Issue description

Folder colors don't show up in file dialogs: when saving a scene, etc.

### Steps to reproduce

1. color a folder
2. create and open the save scene dialog and navigate to the colored folder
3. notice it's not shown its color in the file dialog

### Minimal reproduction project

any

**Comment by synalice** [comment]
Thanks for pointing this out! The color of the folder is indeed not displayed in the save scene dialog. I'm working on it right now.
