### ISSUE TITLE
RCEdit fails on export if no version (FileVersion) is specified

### ISSUE THREAD

**Issue by m4rr5** [godotengine/godot#83379]
### Godot version

4.2 beta 1

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz (16 Threads)

### Issue description

If you try to export a project as a Windows Runnable and you have RCEdit configured (because for example you want to change the icon of the generated exe) it will fail to run unless you explicitly provide a version for your project. You used to be able to do this without filling out anything for version (in 4.x). This is a regression.

### Steps to reproduce

1. Create a new project. It can remain empty.
2. In editor settings, make sure under Export/Windows that you have rcedit configured correctly.
3. Under Project/Export create a Windows Desktop (Runnable) preset.
4. Click "Export Project..." and put the exe anywhere.
5. Under 4.1.2 that will work fine, under 4.2 beta 1 you will get a dialog with a warning caused by a fatal error (unable to parse version string for FileVersion).
6. The workaround is to to to Project/Project Settings... and under Application/Config fill out something for version, for example 0.0.0.0
7. If you try exporting it again, it now works.
8. If you make that version field empty again, it will fail again.
9. This is a regression from 4.x to 4.2 beta 1.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/27765.

This is likely a regression from https://github.com/godotengine/godot/pull/35555.

**Comment by m4rr5** [comment]
Even though this issue has already been closed, I just downloaded 4.2 beta 5 and can confirm that the bug was indeed fixed. Thanks @Calinou and everybody else involved for taking the time to address this.
