### ISSUE TITLE
Compatibility Renderer Soft Shadows at locked at PCF5 at runtime

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#83380]
### Godot version

4.2 beta 1

### System information

Godot v4.2.beta (ee118e7ff) - Windows 10.0.22621 - GLES3 (Compatibility) - AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 Threads)

### Issue description

Soft Shadows change in the editor properly, however when running the project, the Soft Shadows are locked at PCF5 (Directional and Spot, Omni doesn't have PCF implemented yet.)

### Steps to reproduce

Examine soft shadows and compare between editor and runtime

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Probably the same fix as https://github.com/godotengine/godot/pull/83141
