### ISSUE TITLE
font_hover_pressed_color doesn't work on Button

### ISSUE THREAD

**Issue by Andikki** [godotengine/godot#83393]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

Button's color `font_hover_pressed_color` seems to never be applied. Toggle button in pressed state is the most apparent element where hover+pressed should matter, but it always uses `font_pressed_color`, whether hovered or not.

![image](https://github.com/godotengine/godot/assets/10902643/0432ba1a-deda-40f2-92d5-f3d19701ef39)

(Here I expect the Toggle Button's text to be blue, since I'm hovering over it, but it stays orange. No combination of hover+focus+pressed makes the font blue.)

### Steps to reproduce

1. Create a new Theme resource and open theme editor.
2. Add Button type.
3. Set colors for the Button type so that `font_pressed_color` and `font_hover_pressed_color` are visibly different.
4. In the preview press Toggle Button so that it's in the pressed state.
5. Hover over pressed Toggle Button and see how nothing happens.

### Minimal reproduction project

[godot-sandbox-button-colors.zip](https://github.com/godotengine/godot/files/12909749/godot-sandbox-button-colors.zip)

**Comment by AThousandShips** [comment]
For these purposes I think `pressed` means input, not that it's toggled

**Comment by AThousandShips** [comment]
Correction, you need to assign the `hover_pressed` stylebox as well for this to work, should probably be documented more clearly

**Comment by Andikki** [comment]
> Correction, you need to assign the `hover_pressed` stylebox as well for this to work, should probably be documented more clearly

Do buttons have that?

![image](https://github.com/godotengine/godot/assets/10902643/349cb2e5-e4fb-4db2-88df-5676852971b9)

**Comment by AThousandShips** [comment]
Correction, this is only intended for `CheckButton` and `CheckBox`, only works with those, or if you have the `hover_pressed` stylebox

**Comment by Andikki** [comment]
> For these purposes I think `pressed` means input, not that it's toggled, seems to be the same in 3.x

Normal (non-toggle) button also never gets this font color. I'd expect it to be hover+pressed when clicking on it, but it only uses `pressed` color.

**Comment by AThousandShips** [comment]
That's seemingly by design, needs to be documented though

**Comment by Andikki** [comment]
Yeah, indeed, it applies to checkboxes.
I think buttons should also have it for accessibility, especially toggle buttons, since right now there's no visual cue that a toggled button is hovered over.

**Comment by Andikki** [comment]
Oh, I get it now. You're saying that manually adding `hover_pressed` stylebox to a button would enable this behaviour. That fixes it! Thanks.

**Comment by Andikki** [comment]
I created a `hover_pressed` stylebox, but it's still not ideal for buttons & toggle buttons (and even CheckBoxes & CheckButtons), because clicking with a mouse isn't considered hovering, so if I press down the button and hold, I see one style (`pressed`), but when I release the mouse button it changes to another style (`hover_pressed`).

Maybe clicking with a mouse should be considered `hover_pressed` when pressing/toggling/checking, and `hover` when unchecking/untoggling? And then should change to `pressed` or normal when moving the mouse away.
With the keyboard/controller it's never hovered, and should just go between `pressed` and normal.

(And focus is yet another beast that doesn't play nice. Focus color is only applied in unpressed state, so focus behaviour is inconsistent between checked/toggled elements and unchecked/utoggled.)
