### ISSUE TITLE
Godot will freeze when disabling VSync and loading intense-enough scene

### ISSUE THREAD

**Issue by programneer** [godotengine/godot#83390]
### Godot version

v4.2.beta [a574c0296]

### System information

Arch Linux 6.5.6-zen2-1-zen (64-bit)

### Issue description

When i ran the project in editor while disabling VSync and loading something big scene, the game will freeze after ~4-5 FPS.

### Steps to reproduce

1. Load any project.
2. Disable VSync by going to `Project Settings > Display > Window` and setting `VSync Mode` to `Disabled`.
3. Make sure you either unlocked FPS (should be by default) or set to something that's prone to it by checking `Project Settings > Application > Run > Max FPS`
4. Run the project by selecting somewhat (around 3KBs or more) big scene.
5. Check wherever the game is frozen or not.
5.5. If it's somehow not frozen, either try increasing FPS, try again and repeat until you see the frozen frame, or unlock FPS by setting `Max FPS` to 0.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
What error messages do you get in terminal output (when running Godot from a terminal)? This is likely due to the same cause as https://github.com/godotengine/godot/issues/71929.

**Comment by programneer** [comment]
Closing as it's not active anymore
