### ISSUE TITLE
Scene parse error

### ISSUE THREAD

**Issue by fljohnson** [godotengine/godot#83404]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Ubuntu 23.04 23.04 - X11 - Vulkan (Mobile) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 Threads)

### Issue description

"Parse Error" reading res://Tank.tscn line 244 upon opening the attached project

Expected: res://Tank.tscn opens normally, as no error is present on that line

From the command line:
```
ERROR: res://Tank.tscn:244 - Parse Error: 
   at: _parse_node_tag (scene/resources/resource_format_text.cpp:283)
ERROR: Failed loading resource: res://Tank.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:273)
ERROR: Condition "nc == 0" is true. Returning: nullptr
   at: instantiate (scene/resources/packed_scene.cpp:92)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: get_scene_path (editor/editor_data.cpp:880)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: get_scene_path (editor/editor_data.cpp:880)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: get_scene_path (editor/editor_data.cpp:880)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: get_scene_path (editor/editor_data.cpp:880)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: check_and_update_scene (editor/editor_data.cpp:683)
ERROR: Index p_idx = 2 is out of bounds (edited_scene.size() = 2).
   at: set_edited_scene (editor/editor_data.cpp:745)
ERROR: Pages in use exist at exit in PagedAllocator: 6Thread
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)
ERROR: Pages in use exist at exit in PagedAllocator: N16WorkerThreadPool4TaskE
   at: ~PagedAllocator (./core/templates/paged_allocator.h:170)

```

### Steps to reproduce

From the command line (IDE is in $HOME/"bin/Godot Engine"):
~/bin$ Godot\ Engine/Godot_v4.1.2-stable_linux.x86_64 
Choose "LightFighter" from the list of projects and edit 
The above error messages show up in the command line, and an alert appears in the IDE to the effect that "res://Tank.tscn may be corrupted"

### Minimal reproduction project

(Just in case it's a factor, I've included the Git repository for this project)
[LightFighter.zip](https://github.com/godotengine/godot/files/12910078/LightFighter.zip)

**Comment by Calinou** [comment]
How did you end up in this situation? What did you last do before saving the scene and it ended up corrupted?

**Comment by astillich** [comment]
This error appears because the tank has a script called "3_lwels" assigned which is not in the project tree. 

![image](https://github.com/godotengine/godot/assets/2734679/998e531d-a37f-4d3b-8a3f-ebbf981f8bee)

I have seen this, too and helped myself by deleting the reference to the missing script from the scene file using a text editor. It seems to (sometimes) happen when you delete a script file which is assigned to a node.

Here's a fixed version of the tank scene: [Tank.zip](https://github.com/godotengine/godot/files/12915274/Tank.zip)

**Comment by AThousandShips** [comment]
There's no reference there to a script called that, it's a reference to the external resources at the top of the file

**Comment by astillich** [comment]
Ah right, I'm not very familiar with the format. The parser complains specifically about this line (244 is script = ExtResource("3_lwels")): 

![image](https://github.com/godotengine/godot/assets/2734679/fc45f437-702b-48b3-b9c8-ca583d42c7f9)

So it fails to do the lookup here and does not find the definition on top of Tank.tscn?

**Comment by nicom7** [comment]
I got a similar issues on my project where I have a scene named `cell.tscn` that have a script reference to `cell.gd` and the scene fails to load with the same errors as yours.

However, in the script I was preloading a packed scene for this same scene `cell.tscn` so it was creating a kind of circular dependency:
```
static var _scene: PackedScene = preload("res://cell.tscn")
```
Removing the previous line and its references from the script fixed the problem.

**Comment by fljohnson** [comment]
Following a theory nicom7's post brought to mind, I just now tried changing MainScene.gd from
`var tank_proto = preload("res://Tank2.tscn")`
to
`var tank_proto #= preload("res://Tank2.tscn")`

Tank2.tscn refers to BetterTank.gd, which in turn contains references to static members of MainScene.

The thing seems to load without incident after I did that, suggesting that I'd technically introduced a circular dependency.

**Comment by fljohnson** [comment]
I answered the need to have that PackedScene ready to instantiate by using 
`tank_proto = load("res://Tank2.tscn")`
in a _ready() method

**Comment by fljohnson** [comment]
Yup, pursuing that "de facto circular dependency" premise seems to have solved my "scene file reported as corrupted" problem
