### ISSUE TITLE
[4.2.beta1] Registering custom signals on custom node displays icon of original size in the category tab

### ISSUE THREAD

**Issue by Lexpeartha** [godotengine/godot#83405]
### Godot version

4.2.beta1.mono

### System information

Godot v4.2.beta1.mono - Nobara Linux 38 (Thirty Eight) - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (nvidia; 535.104.05) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

Godot displays comically large icon (which seems to be original size) next to the category name when exposing custom signals:
![image](https://github.com/godotengine/godot/assets/43365376/0a5d572b-53d5-4a0e-a2e0-56a2937c1f10)

This does not happen on exported properties.

### Steps to reproduce

Made a plugin that adds custom node like this:
![image](https://github.com/godotengine/godot/assets/43365376/c4266999-b6af-42b6-8c89-d54f7660db92)

### Minimal reproduction project

It seems trivial, but I can provide my current project if others fail to reproduce it

**Comment by raulsntos** [comment]
Also reproducible with GDScript, here's an MRP:

[MRP_83405.zip](https://github.com/godotengine/godot/files/12918633/MRP_83405.zip)
