### ISSUE TITLE
The build method threw an exception

### ISSUE THREAD

**Issue by ALI3D69** [godotengine/godot#83407]
### Godot version

4.1.2stable, 4.2b1

### System information

Windoes 10

### Issue description

As soon as I create a C# file, I can't run my project anymore.
It says:
The build method threw an exception.

System.IO.FileNotFoundException: Cannot find the dotnet executable. (0,0)

I test it in 4.1.2 and 4.2b1.

How should I fix it?

### Steps to reproduce

1. Create a C# file
2. Run the project

### Minimal reproduction project

[13.zip](https://github.com/godotengine/godot/files/12910187/13.zip)

**Comment by ALI3D69** [comment]
I can Run the Project from the rider. but In the editor I get that Error.
When I run the project it compile my code correctly and show me a export variables in the inspector. but when I switch to Godot without clicking on build or run in rider, it dose not compile the code and I cant see my export variables. and when I click on run in the Godot, it says: Faild to build project and there is this error in MSBuild:
The build method threw an exception.
System.IO.FileNotFoundException: Cannot find the dotnet executable. (0,0)
and this error is in Output panel:
  editor/editor_node.cpp:6473 - An EditorPlugin build callback failed.

**Comment by raulsntos** [comment]
Godot can't find the dotnet CLI. Do you have `dotnet` in the PATH environment variable?
Can you try executing `dotnet --info` in a CMD?

**Comment by ALI3D69** [comment]
I added this in the environment variables of the system variables and it fixed my problem.
PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.WSF;.WSH;.MSC

**Comment by AThousandShips** [comment]
Closing as per the above comment, if there are any more problems please comment and it can be reopened
