### ISSUE TITLE
TextureRect, StretchMode:Tile, HTML, itch.io,  resize window issue

### ISSUE THREAD

**Issue by UnableMight** [godotengine/godot#83413]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Ubuntu 22.04.3 LTS 22.04 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) () - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

Resizing chrome browser window on HTML export uploaded on itch.io (on Google Chrome) breaks TextureRect tiling.
Here's a link to the uploaded test project
https://losinginterest.itch.io/test
Before resizing window:
![Screenshot from 2023-10-15 23-19-13](https://github.com/godotengine/godot/assets/60711282/b1eefc1b-48d2-4496-a935-3c1fa206d38e)
After resizing window:
![Screenshot from 2023-10-15 23-19-30](https://github.com/godotengine/godot/assets/60711282/528d1c84-2d64-424f-abed-e1327717fcf2)

Project (The two TextureRect have the same settings):
![image](https://github.com/godotengine/godot/assets/60711282/614168e5-8628-4ac0-ad1e-94730f3cbe37)

### Steps to reproduce

I created a TextureRect node, set StretchMode to Tile, set expand mode to Ignore Size, assigned it a texture.
After that, running the project in the editor results in a correct display behavior.
The window can be stretched without causing graphical issue.
After exporting it in HTML, I uploaded it on Itch.io.
In the "Embed options" of itch.io I set "Click to launch in fullscreen" and checked "SharedArrayBuffer support ".
After this I run the game on itch.io, Google Chrome, and everything works, until I resize the browser window, then the graphics breaks.
I'm using chrome, also happened on friend's PC.
I haven't tested on different sites/browsers/different export platforms.

### Minimal reproduction project

[bug_test.zip](https://github.com/godotengine/godot/files/12910719/bug_test.zip)

**Comment by Calinou** [comment]
Please test 4.1.2, as this should be fixed: https://github.com/godotengine/godot/issues/79315

**Comment by UnableMight** [comment]
Yes, solved after testing in 4.1.2.
