### ISSUE TITLE
Error when using `CTRL+/` on Windows

### ISSUE THREAD

**Issue by k0T0z** [godotengine/godot#83410]
### Godot version

v4.2.dev.custom_build [fba341ce4]

### System information

Godot v4.2.dev (fba341ce4) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 30.0.15.1179) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When using `CTRL+/`, the console outputs an error.

### Steps to reproduce

https://github.com/godotengine/godot/assets/74428638/ff4bd4c6-c5e3-4d6d-b6ce-08361839a42a

### Minimal reproduction project

N/A

**Comment by k0T0z** [comment]
I worked on this a little bit and here's what I figured out if anyone wants to help me with it:
 1. When the line has 13 characters in it (ex.: `#extends Node`), [line 4983](https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/gui/text_edit.cpp#L4983) sets the column to 13.
 2. When the same line has 12 characters in it (ex.: `extends Node`), the `selecting_column` inside `carets.write[p_caret].selection.selecting_column` still at column 13, it didn't get updated for some reason which means on the next call, it will fail in [line 4982](https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/gui/text_edit.cpp#L4982) because the line has only 12 characters now.

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.dev 42425baa5 (when using Toggle Comment while having the last character on the line selected, whether it's from the right or from the left).

**Comment by k0T0z** [comment]
@Calinou Did you completed the 4 steps?

1. Select the text with pointer
2. Use CTRL+/
3. Tap pointer's left button at the end of the line (as in video)
4. Repeat step 1
5. Repeat step 2
6. Repeat step 3. The error should show up here.

**Comment by Stronkkey** [comment]
Was able to replicate this on v4.2beta.
![2023-10-16T15:42:07,032716121+02:00](https://github.com/godotengine/godot/assets/92468390/3b4a03ce-cbc7-4215-abdb-5caa39757b2e)
