### ISSUE TITLE
AnimationTree spamming error when switching scene

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#83418]
_Originally posted by @darthstelz in https://github.com/godotengine/godot/issues/83401#issuecomment-1763506970_

> On upgrading project to 4.2 beta I'm getting tons of these errors on all my animations. First time posting here hope it's the right place, just seemed related. Note: The project runs fine, animations work fine. Just getting error spammed. Only pops up when moving my player scene around in the world scenes hierarchy window. 

![image](https://github.com/godotengine/godot/assets/147906517/7d568042-7469-4ba0-8ef5-5fffd7616e38)

**Comment by TokageItLab** [comment]
@darthstelz Please send MRP.

**Comment by akien-mga** [comment]
Thanks!
