### ISSUE TITLE
Slider Handle Moves With Mouse When Scrolling

### ISSUE THREAD

**Issue by jcovin293** [godotengine/godot#83414]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

In the Import Dock, when my mouse is hovered over the slider but not the handle and then I start to scroll using the MacBook scrolling gesture, the circle of the slider handle moves down with my mouse. I've attached a video to better describe the issue:

https://github.com/godotengine/godot/assets/111152655/a467c237-29fc-4ce6-a4c9-a92e547744ac

This happens in other panels besides the import panel, it seems to happen with all of these slider widgets such as in the inspector panel.

### Steps to reproduce

1. Go to any panel that scrolls and also has a slider
2. Hover over the slider but not the handle
3. Scroll downward using the scroll gesture

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/42497.
