### ISSUE TITLE
Using the same texture on TileMap and Sprite3D causes 'Cannot blit_rect in compressed or custom image formats.' and 'Can't get_pixel() on compressed image, sorry.'

### ISSUE THREAD

**Issue by lyhyl** [godotengine/godot#83423]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 Threads)

### Issue description

Using the same texture on TileMap and Sprite3D causes tons of
```
Cannot blit_rect in compressed or custom image formats.
Can't get_pixel() on compressed image, sorry.
```
and does not render correctly.

### Steps to reproduce

* create project (default settings)
* import texture
* create 3D scene
* add SubViewport to root
* add TileMap to SubViewport
  * new TileSet
  * add texture (x.png) as atlas
  * draw something on TileMap
* add Sprite3D to root
  * set Texture to ViewportTexture (from previous SubViewport)
* add Sprite3D to root
  * set Texture to x.png

Then, get tons of errors.

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12911688/MRP.zip)

**Comment by KoBeWi** [comment]
This is expected behavior.
In the Import settings of the texture there is Detect 3D section. Change "Compress To" to "Disabled".
The textures get compressed by default when used in 3D context.

**Comment by lyhyl** [comment]
> This is expected behavior. In the Import settings of the texture there is Detect 3D section. Change "Compress To" to "Disabled". The textures get compressed by default when used in 3D context.

Thank you!
So TileSet atlas does not support compressed image?
After scrolling up thousands of error messages, I noticed a gray line info telling me that the way of importing image had been changed, which I hadn't noticed before.

**Comment by KoBeWi** [comment]
> So TileSet atlas does not support compressed image?

It doesn't. Maybe we can detect that and display a single readable error instead of spamming unrelated messages.
