### ISSUE TITLE
Is it an expected behaviour for Godot 4.1.2 stable's Audio Animation Track Editor to behave like this?

### ISSUE THREAD

**Issue by VansonLeung** [godotengine/godot#83436]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

macOS 11.0+

### Issue description

This may or may not be a bug. 
Is it an expected behaviour? (See video)

https://github.com/godotengine/godot/assets/1129695/18f0c4bc-3764-4180-965d-635bc65aaf41

### Steps to reproduce

1. Put any audio "playing=true" key into animation track
2. Mouse drag the animation timeline

### Minimal reproduction project

[gd_anim_unittest_1 3.zip](https://github.com/godotengine/godot/files/12915550/gd_anim_unittest_1.3.zip)

**Comment by KoBeWi** [comment]
This is expected when animating `playing` property. You should use an Audio track instead.

**Comment by VansonLeung** [comment]
@KoBeWi oh, yes! thanks for your guidance, sorry my bad
