### ISSUE TITLE
Exit code 1 after importing in headless mode with --quit

### ISSUE THREAD

**Issue by InfinitiesLoop** [godotengine/godot#83449]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

macOS 13.0.1 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When running godot in headless mode to import a project for the first time (no .godot folder yet), it seems to succeed in that there are no errors, but the exit code is 1. This causes CI actions (e.g. a github action) to assume the step failed, preventing us from being able to produce exports as part of CI. For example, when using this github action, it will fail since it can't get passed the import step: https://github.com/marketplace/actions/godot-export

```
dreed ~/git/GodotTest
$ rm -rf .godot/

dreed ~/git/GodotTest
$ g project.godot --headless -e --quit
Godot Engine v4.1.1.stable.official.bd6af8e0e - https://godotengine.org

WARNING: Custom cursor shape not supported by this display server.
     at: cursor_set_custom_image (servers/display_server.cpp:480)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:73)

dreed ~/git/GodotTest
$ echo $?
1
```

### Steps to reproduce

1. Create a new blank project on MacOS with Godot 4.1.x
2. Close the Godot editor
3. Delete the .godot folder
4. Run godot in headless mode with -e --quit: `godot project.godot --headless -e --quit`
5. Echo the exit code with `echo $?`
6. --> Exit code is 1 even though there were no apparent errors

I tried this with --verbose as well and there's a lot more info provided, but still nothing that looks like an error or even a warning. 

### Minimal reproduction project

[GodotTest.zip](https://github.com/godotengine/godot/files/12920043/GodotTest.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/83042.

**Comment by dreed-sd** [comment]
I believe the platform matters. It maybe specific to MacOS Godot. CI that needs to sign exports with xcode need to be on a Mac, so not easy to work around.

**Comment by InfinitiesLoop** [comment]
I believe the platform matters. It maybe specific to MacOS Godot. CI that needs to sign exports with xcode need to be on a Mac, so not easy to work around.

**Comment by InfinitiesLoop** [comment]
I added logging to `OS::set_exit_code` and `SceneTree::exit`, nothing ever calls it on this code path. So I believe it is using exit code 1 simply because it's the default value and nothing ever sets it: https://github.com/InfinitiesLoop/godot/blob/master/core/os/os.h#L59

I don't know the code well enough to know where/what should be setting `EXIT_SUCCESS`, unless someone has an idea I'd be happy to submit a PR
