### ISSUE TITLE
Moving nodes around the tree in a scene with baked lightmap triggers lightmap reimport

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#83444]
### Godot version

v4.2.beta.custom_build [a60fc7f7c]

### System information

Godot v4.2.beta (a60fc7f7c) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 27.20.21034.37) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

When you move any node around within the tree of a scene with baked lightmap, a reimport of the lightmap file will be triggered.

### Steps to reproduce

1. Set up a scene with some lightmapped meshes. Also create one dynamically lit object for testing reason.
2. Bake lightmap
3. Move any node around in the scene tree
4. A reimport will be triggered.

### Minimal reproduction project

[Lightmap Reimport.zip](https://github.com/godotengine/godot/files/12918646/Lightmap.Reimport.zip)

**Comment by atirut-w** [comment]
I can reproduce this on 4.2 Beta 1.

**Comment by AThousandShips** [comment]
And further back?

**Comment by bitsawer** [comment]
There is a PR that might also improve this behavior, but I haven't tested it: https://github.com/godotengine/godot/pull/77788

**Comment by atirut-w** [comment]
Found a good commit. I'll start a `git bisect` and see what caused this bug. Will also check out #77788.

Commit SHA in case anyone want it: ce236a6d03bfb4ccd81fc60b859b28122edaa20d

**Comment by atirut-w** [comment]
It seems that this was exposed (read: not introduced) in 42a3108902da8caff7bce2f8798daf0d1fc48595, and that #77788 indeed fixes it.
