### ISSUE TITLE
ArrayMesh with flag USES_EMPTY_VERTEX_ARRAY still needs vertex array for rendering work

### ISSUE THREAD

**Issue by erickweil** [godotengine/godot#83446]
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Godot v4.2.beta1.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 1650 () - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

I was experimenting with reading geometry from a Texture when I come across #62046 and found some weird behaviours when creating a ArrayMesh with the MESH_ARRAY_FLAG_USES_EMPTY_VERTEX_ARRAY flag:

1. If no vertex array if provided, no rendering happen (buffer allocates memory but 0 primitives drawn)
2. If a 0-sized vertex array if provided, error is produced
3. If a vertex array with small size (3 for example) is provided, the rendering work as expected and all primitives are drawn from the indice array, even with thousands of indices with no problem, but fails with weird glitches with more than 65535 indices
4. If in the case of more than 65535 indices a vertex array with size 65537 (1 more) is provided, everything works as intended, even with millions of indices.

From this analisis, I conclude the most probable cause is that somewhere in the mesh creation phase there is a check that looks at vertice count to decide if should use or not 16-bit indices. So when no 
The main issue here is the requirement in providing a dummy 65k vertice array just to signal that a 16-bit index should not be used.

**Conclusion**

Vertex-less meshes should work out of the box without needing any vertex array to be created, basically the way it should work is that when the mesh has the empty vertex array flag the logic to decide if a 16 or 32 bit index should be used needs to be different, maybe the user could pass a flag overriding the underlying logic and specifying that 32 bit indices are needed

### Steps to reproduce

Look at the Minimal reproduction project.

The general steps are:

1. Have a custom gdshader that doesn't use VERTEX, instead using only VERTEX_ID and some math outputs a vertex position
2. Have a ArrayMesh with indices and with the flag MESH_ARRAY_FLAG_USES_EMPTY_VERTEX_ARRAY set
3. Observe the following behaviour:

If no vertex array is give to ArrayMesh, nothing is drawn
If a vertex array with size 1 is given, primitives are drawn but VERTEX_ID will be 16 bits, causing issues with big meshes, solving by giving a vertex array with size 65536+1

### Minimal reproduction project

[IssueVertexLessMesh.zip](https://github.com/godotengine/godot/files/12918783/IssueVertexLessMesh.zip)

**Edit: Added GDScript version**
[IssueVertexLessMeshGDScript.zip](https://github.com/godotengine/godot/files/12919204/IssueVertexLessMeshGDScript.zip)

**Comment by AThousandShips** [comment]
Please provide a GDScript version of your code, unless this is unique to C# this is preferred and otherwise few contributors will be able to help debugging this

**Comment by erickweil** [comment]
> Please provide a GDScript version of your code, unless this is unique to C# this is preferred and otherwise few contributors will be able to help debugging this

Ok I updated the issue with a GDScript version. It's not unique to C#.

**Comment by TokisanGames** [comment]
As of 4.2.1, the GDScript MRP with the no vertex array option works fine. The custom_aabb or extra cull margin do need to be non-zero so it doesn't get culled by the renderer.


Here's an updated, working MRP.

[test_vertex_less.zip](https://github.com/godotengine/godot/files/14628446/test_vertex_less.zip)

![image](https://github.com/godotengine/godot/assets/632766/05a9a40f-f477-4d47-b00c-6126f4d32dc9)

**Comment by Calinou** [comment]
> The custom_aabb or extra cull margin do need to be non-zero so it doesn't get culled by the renderer.

In this case, is this just a documentation issue?

**Comment by TokisanGames** [comment]
It appears to me that as of 4.2.1, this ticket is satisfied and can be closed, unless you want to add documentation.

**Comment by erickweil** [comment]
Looks good to me. It could be closed.
