### ISSUE TITLE
Texture pixel data is off by 1

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8344]
I have a png I am loading up in krita and setting a specific colour:
r:1, g:2, b:3
yet when I get this pixel inside godot:
r:0, g:1, b:2

some where along the lines a value of 1 has been subtracted.

my code looks like this:

        Image image = texture->get_data();
        r = image.get_data().read();
        uint32_t ofs = (p_y * width + p_x) * pixel_size;
        const uint8_t *data_ptr = r.ptr();
        uint8_t r = data_ptr[ofs];
        uint8_t g = data_ptr[ofs + 1];
        uint8_t b = data_ptr[ofs + 2];

**Comment by bojidar-bg** [comment]
Are you sure it is off by one _color amount_ and not off by one _position_? (e.g. can you retest with `rgb: (1,2,4)` and confirm you get `rgb:(0,1,3)` rather than `rgb:(0, 1, 2)` out?)

**Comment by supagu** [comment]
rgb: (1,2,4) comes in to godot as rgb: (0, 1, 3)

**Comment by karroffel** [comment]
Try to disable filtering for the image. Or disable mip maps.

filtering usually makes the image just a tiny tiny tiny tad smaller. This could be the problem

**Comment by supagu** [comment]
I tried turning "**premult alpha**" off and that has fixed the problem!

Is there a way in C++ if i can determine if the texture or image has this value set so I can throw an assertion message?

And what exactly is this option doing?

**Comment by tamkcr** [comment]
@supagu my guess is premult alpha causes an extra multiplication by 1.0f which makes the result slightly less in the range concerned due to precision, giving a difference of 1 when floored. 

Note I can't do floating point multiplication in my head so its also possible that I'm totally wrong if it actually produces values slightly larger that would be floored correctly.

**Comment by reduz** [comment]
oh, premult alpha was set as default a few weeks ago by mistake. This is fixed now, apologies.
