### ISSUE TITLE
Plugin: script parse errors after removing folder `.godot`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#83457]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows, Unix, MacOS

### Issue description

Loading plugin has an issue with classes using `class_name`, it shows up `Parse Error: ...` on startup.

This is a big problem when you store your project on GitHub with excluding the `.godot` folder
`.gitignore`
```
# Godot-specific ignores
.godot/
```
This is a big problem when you want to run a continuous integration test via GitHub workflows on your project.
It is virtually impossible to load a project when these errors occur.
Also there is no way to get Godot to rebuild the cache via command line.

I started to remove the `class_name` and do a `const MyClass := preload("..")` but is stopped for now because i use a huge amount of classes with `class_name`.
I can't remember such issues on Godot3.

### Steps to reproduce

* load the attached Project, see errors
![image](https://github.com/godotengine/godot/assets/347037/0e74fdaf-88f4-457e-92fd-ffaf78a3093f)
* close and reopen Godot, no errors
![image](https://github.com/godotengine/godot/assets/347037/accfe664-1f96-459b-adbc-78d15759b0d5)

### Minimal reproduction project

[plugin_load.zip](https://github.com/godotengine/godot/files/12920902/plugin_load.zip)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/81615, which mentions the same issue.

You can open the project twice as a workaround, which many plugins already advise to do in their documentation.
