### ISSUE TITLE
Grammar typo in GDScript error message

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#83453]
### Godot version

Godot v4.2.beta1 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.beta1 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Easy bugfix for grabs!

![image](https://github.com/godotengine/godot/assets/85438892/965cd3d9-6083-49e5-ae66-2ac4d6582b02)

> a "int"

The "a" is not correct here, which is convenient as it removes the need to worry between "a" and "an".

### Steps to reproduce

Not relevant

### Minimal reproduction project

N/A

**Comment by MewPurPur** [comment]
I'm speaking of "a int"

**Comment by MewPurPur** [comment]
I think it's wholly incorrect actually, there is no article before String or StringName.

**Comment by AThousandShips** [comment]
There it's valid agreed

**Comment by vnen** [comment]
Probably should replace the "a" by "type" so it relates to first part of the sentence.
