### ISSUE TITLE
Cannot close search bar in script editor

### ISSUE THREAD

**Issue by A-Hugh-Mann** [godotengine/godot#83456]
### Godot version

4.2.beta.3bc1c9b5e

### System information

Arch Linux

### Issue description

When attempting to close the search bar in script editor the error
```
core/object/object.cpp:1139 - Error calling from signal 'pressed' to callable: 'FindReplaceBar::FindReplaceBar::_hide_bar': Method expected 1 arguments, but called with 0.
```
will appear, and the bar will not close when clicking the X

### Steps to reproduce

open up godot, go into script editor.
press Ctrl + F.
attempt to close the search bar by clicking the X to the right.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
`_hide_bar` was added in #83335, CC @KoBeWi.

**Comment by KoBeWi** [comment]
That PR only modified the method signature (but that's what caused the bug 🙃).
