### ISSUE TITLE
Parallax backgrounds visual bug

### ISSUE THREAD

**Issue by Slowbro213** [godotengine/godot#83463]
### Godot version

4.2 beta

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 520 (Intel Corporation; 26.20.100.8142) - Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 Threads)

### Issue description

Very same problem occurred even with the previous version of godot. When i make a parallax layer and try to mirror it , this happens:

![Screenshot 2023-10-16 221342](https://github.com/godotengine/godot/assets/100229861/5438c398-e70e-4fed-a3aa-5789eaefb919)

also when i try to drag this scene onto another where there are buttons or other nodes present, some nodes shift to the right like so:
![Screenshot 2023-10-16 221610](https://github.com/godotengine/godot/assets/100229861/f81afcb5-436f-409b-8fd6-e56a95b2c505)

![Screenshot 2023-10-16 221550](https://github.com/godotengine/godot/assets/100229861/6c1d26ae-5073-4b49-94d0-a98279f50adc)

this only seems to be an issue with mobile and forward+. Compatibility works just fine in this regard.

### Steps to reproduce

simply create a parallax background node , make a parallax layer and add a png file to it, after that try to mirror the parallax layer.

### Minimal reproduction project

[Uploading Bug report.zip…]()

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.
