### ISSUE TITLE
"enable_object_picking" disables editor tooltips

### ISSUE THREAD

**Issue by FuzzyRhombus** [godotengine/godot#8347]
**Operating system or device - Godot version:**
Tested on OSX 10.10 latest and 10.11 latest; Godot **v2.1.2**. Tested with stable and custom builds. Also affects the latest 2.1.3 RC.

**Issue description:**

When a project that has `physics/enable_object_picking` set to false is opened in the editor, tooltips are disabled or no longer working **in the editor** 

**Steps to reproduce:**
1. Set `physics/enable_object_picking` to `false` in the Project Settings.
2. Close editor and reopen the project
3. As long as the setting continues to be off (false), when opening that project in the editor, tooltips do not work
4. Set `physics/enabled_object_picking` back to `true`
5. Close and reopen the project and tooltips will be working again

**Comment by akien-mga** [comment]
Fixed by #17140 in the master branch, and by #11837 in 2.1.
