### ISSUE TITLE
Breakpoints don't trigger in Autoload built-in scripts

### ISSUE THREAD

**Issue by schneediener** [godotengine/godot#83478]
### Godot version

4.1.stable

### System information

Windows 10

### Issue description

When calling a function from an Autoload that has a built-in script, breakpoints will not trigger.

If you convert this to a non-built-in script, and make no other changes, the breakpoint will start triggering.

### Steps to reproduce

- Open a new project
- Create a scene called Autoload and give it a built-in script with a function
- Set it as an autoload scene in Project Settings
- Make another node, which calls "Autoload.function()"
- Set a breakpoint in the function on Autoload
- Run the scene and note that the breakpoint doesn't trigger
- Make the script in Autoload not built-in and note that it now triggers breakpoints correctly

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12924507/test.zip)

**Comment by KoBeWi** [comment]
This is the same issue as #72854. Autoloaded scenes behave like preloaded and the built-in scripts lose their path at runtime, making debugger not recognize the file.

**Comment by schneediener** [comment]
> This is the same issue as #72854. Autoloaded scenes behave like preloaded and the built-in scripts lose their path at runtime, making debugger not recognize the file.

Worth closing this as a duplicate then?

**Comment by KoBeWi** [comment]
I have verified that both issues are fixed by the same PR, so closing.
