### ISSUE TITLE
Android editor: Somewhat random graphical corruptions when viewing meshes in inspector

### ISSUE THREAD

**Issue by TheRektafire** [godotengine/godot#83481]
### Godot version

4.2 beta 1 Android editor

### System information

Godot v4.2.beta1 - Android - Vulkan (Mobile) - Moto G Power 2021 - integrated Adreno (TM) 610 -  (8 Threads)

### Issue description

When viewing meshes in the inspector instead of seeing the actual mesh I see random VRAM garbage on certain screens but not on others, and the actual mesh in the 3d viewport is not effected, it's only the inspector views that are effected. It seems like messing with material settings seems to cause it to go away, if I apply.a default standard material it happens but when I change certain settings like transparency or detail it goes away for some reason, maybe it has to do with incorrect rendering of opaque objects?

![Screenshot_20231017-015746](https://github.com/godotengine/godot/assets/11543824/109a60e7-7339-4ab5-b365-fc8c0997268c)

### Steps to reproduce

1. Create new project
2. Add a mesh (I tested a BoxMesh)
3. Add a StandardMaterial3D to the mesh
4. Go into material settings

### Minimal reproduction project

N/A

**Comment by Alex2782** [comment]
- only steps 1 and 2 (without Material)
- show and hide mesh preview several times (video)

|Android| MacOS|
|--------|--------|
| ![image](https://github.com/godotengine/godot/assets/41921395/87ed593d-796a-4ef2-9a1d-d230b45f4e2a)  | ![Bildschirmfoto 2023-11-25 um 15 43 52](https://github.com/godotengine/godot/assets/41921395/783b3e0a-e2c6-44df-a183-eb1be026a550) |




https://github.com/godotengine/godot/assets/41921395/c002a783-b1bb-4807-a606-4b7dc59605e1

**Comment by Alex2782** [comment]
my PR 84852 (`HOST_COHERENT_BIT`) does not solve these problems

**Comment by Alex2782** [comment]
@Calinou are you familiar with the inspector? I am looking for the sources for "Mesh Preview", it is displayed via `EditorPropertyResource::update_property()`

**Comment by clayjohn** [comment]
@Alex2782 You may want to take a look at ``texture_get_data``
https://github.com/godotengine/godot/blob/fa4a65387ea41506ecc519fc61a06da110dce51c/drivers/vulkan/rendering_device_vulkan.cpp#L2754

This is likely where the issue comes from.

**Comment by Alex2782** [comment]
I have **not** yet been able to force the error via gdscript  _(Minimal reproduction project)_

```gdscript
@onready var viewport = %SubViewport
func _process(_delta):
	var texture := viewport.get_viewport().get_texture()
	%TextureRect.texture = texture

```

the sources are in the folder `.../editor/plugins/`

**Mesh:**
https://github.com/godotengine/godot/blob/master/editor/plugins/mesh_editor_plugin.cpp

**Material:** 
https://github.com/godotengine/godot/blob/master/editor/plugins/material_editor_plugin.cpp

**Comment by Alex2782** [comment]
maybe fixed:  https://github.com/godotengine/godot/pull/84169

> Vulkan mobile: MSAA 3D causes 3D viewport to render black on phone

https://github.com/godotengine/godot/issues/67204


--------------
`viewport->set_msaa_3d(Viewport::MSAA_4X);`
[mesh_editor_plugin.cpp](
https://github.com/godotengine/godot/blob/a0d764919276edfa1560a7c3d74fcd8708615398/editor/plugins/mesh_editor_plugin.cpp#L111C43-L111C43)


**minimal reproduction project**: [bug_83481_msaa.zip](https://github.com/godotengine/godot/files/13494504/bug_83481_msaa.zip)
![Bildschirmfoto 2023-11-29 um 00 43 54](https://github.com/godotengine/godot/assets/41921395/14da4d19-4332-41af-ac1b-f8fe45b66c2b)

**Comment by roalyr** [comment]
I can confirm artifacts happen on different Android devices on a `Mobile` renderer (compatibility works as intended).

Keep in mind that I am using a fork of a vanilla Godot 4.x with extended z-far and in this case, logarithmic depth buffer in a shader material.

Here is a test scene on laptop:
![IMG_20231202_181537_958.jpg](https://github.com/godotengine/godot/assets/46825200/54bc7b57-8cb8-485d-a3b2-2376c93d7f91)

Here is a test scene on a tablet (Lenovo TB350FU, ARM Mali-G57 MC2):
![IMG_20231202_181533_130.jpg](https://github.com/godotengine/godot/assets/46825200/142bbc56-cbcf-4c67-873d-c1d656c8e63b)

Here is a test scene on mobile (Motorola moto g(60), Adreno 618):
![IMG_20231202_181550_685.jpg](https://github.com/godotengine/godot/assets/46825200/3a664a34-c34b-476a-a4b5-6d9bfaae0850)

**Comment by roalyr** [comment]
The test scene itself: [test.zip](https://github.com/godotengine/godot/files/13536785/test.zip)
(Should be opened with: https://github.com/roalyr/godot-for-3d-open-worlds/releases/tag/4.x-2023.12.01)

**Comment by roalyr** [comment]
The omni light bug as demonstrated on the tablet:

https://github.com/godotengine/godot/assets/46825200/e3af339f-5c3d-4c1c-ad0f-4532a860b737

**Comment by Alex2782** [comment]
Now I'm not sure if it has anything to do with MSAA. Mesh error outputs like here: https://github.com/godotengine/godot/issues/80371

@roalyr  You could try this PR: https://github.com/godotengine/godot/pull/84852

**Comment by roalyr** [comment]
@Alex2782 will try in few days.

**Comment by roalyr** [comment]
> Now I'm not sure if it has anything to do with MSAA. Mesh error outputs like here: https://github.com/godotengine/godot/issues/80371
> 
> @roalyr  You could try this PR: https://github.com/godotengine/godot/pull/84852

No effect, all the same bugs.

**Comment by roalyr** [comment]
> I can confirm artifacts happen on different Android devices on a `Mobile` renderer (compatibility works as intended).
> 
> Keep in mind that I am using a fork of a vanilla Godot 4.x with extended z-far and in this case, logarithmic depth buffer in a shader material.
> 
> Here is a test scene on laptop:
> ![IMG_20231202_181537_958.jpg](https://github.com/godotengine/godot/assets/46825200/54bc7b57-8cb8-485d-a3b2-2376c93d7f91)
> 
> Here is a test scene on a tablet (Lenovo TB350FU, ARM Mali-G57 MC2)
> The issue is with how omni lights render. When spheres become larger than certain scale this glitch appears, otherwise it seems fine:
> ![IMG_20231202_181533_130.jpg](https://github.com/godotengine/godot/assets/46825200/142bbc56-cbcf-4c67-873d-c1d656c8e63b)
> 
> Here is a test scene on mobile (Motorola moto g(60), Adreno 618):
> ![IMG_20231202_181550_685.jpg](https://github.com/godotengine/godot/assets/46825200/3a664a34-c34b-476a-a4b5-6d9bfaae0850)
> 
> 
> 
> 

On motorola it now works, but there seems to be a bug related to omni light. At certain object size the light fails to render.

![Screenshot_20231217-024352.png](https://github.com/godotengine/godot/assets/46825200/343f42e4-ff0a-4e3f-9034-0687a77f9d51)

Video: https://imgur.com/a/fSqghHU

**Comment by roalyr** [comment]
On Lenovo tablet it is all the same, so I assume there is a dedicated issue related to omni light behavior on large objects, which is present in vulkan renderer, because in GLES3 all is good no matter the scale.

Video: https://imgur.com/a/MGLpjvq
