### ISSUE TITLE
Editor property selector does not clamp description

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#83495]
### Godot version

4.2 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/17fe3cb5-c852-4094-b1de-cfad9da6f04a

The description should be scrollable probably.

### Steps to reproduce

1. Add AnimationPlayer and animation
2. Click Add Track
3. Select some node and click a property with a long description

### Minimal reproduction project

N/A

**Comment by namedtoaster** [comment]
Idk if I'll be able to work on this, but I started looking into it. I found where the description is created and it uses a MarginContainer subclass. I think the solution is to just add it to a ScrollContainer, but when I tried that, I couldn't expand the width. Would that be a good way to fix this? If so, how do you set the width of the container so it expands like the margincontainer seems to already do?

**Comment by KoBeWi** [comment]
Set horizontal flags to EXPAND_FILL.

**Comment by quirkylemon** [comment]
I might have fixed it yesterday but then forgot to post about it. 

The issue was solved by disabling set_fit_content in the rich text label in help_bit
and setting a custom minimum size to it so it isn't to short.

but some questions are 

- is it OK to add more dependencies? this adds `core/math/vector2.h` to `editor/property_selector.cpp`
- should the height of the description be a set value or is it worth adding it to settings?

please have patience I am new to Github and c++ :)

![Screenshot from 2023-10-20 10-27-12](https://github.com/godotengine/godot/assets/43453305/2b5a8cfb-3b55-4ed0-b921-90eb7522df0f)

**Comment by AThousandShips** [comment]
It already has a reference to it so no need to add the include, all `Control` derived types do have access to it

**Comment by KoBeWi** [comment]
It would be nice if the box wasn't a fixed size. It should use minimum size and only grow when necessary, up to a certain height. Not sure how to achieve it though 🤔

**Comment by quirkylemon** [comment]
I am working on that now.

**Comment by namedtoaster** [comment]
https://github.com/godotengine/godot/assets/13757806/6a3f64fa-d01f-4d52-8160-360cc5124a4c

So NOT this, right? It's fixed clearly

**Comment by Aman7s** [comment]
@namedtoaster

> Screen.Recording.2023-10-20.at.6.12.17.PM.mov 
> So NOT this, right? It's fixed clearly

@namedtoaster I think you have solved the issue but not push it to repo and show us source code what you have done ?

**Comment by quirkylemon** [comment]
what should the height be clamped to?

**Comment by quirkylemon** [comment]
I think 135 is a good minimum height it cleanly holds 8 lines
![image](https://github.com/godotengine/godot/assets/43453305/aeb66c99-b2f3-4446-9741-780b68a25da6)

**Comment by namedtoaster** [comment]
@quirkylemon  just curious does your code change have the same effect as the one in my video? Like I said I probably won't push a PR but wanted to see if that's what the goal was or not

**Comment by quirkylemon** [comment]
yeah 
should I go ahead and do a PR?

**Comment by namedtoaster** [comment]
Go for it
