### ISSUE TITLE
Tilemap collision is disabled when not visible

### ISSUE THREAD

**Issue by ChloePrime** [godotengine/godot#83499]
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Windows 11 22H2

### Issue description

Expected: 
Tilemap still has collision when invisible.
This is how it works in 4.1.2

Actual:
Tilemap has no collision if set visible to false.

### Steps to reproduce

1. Add a tilemap to your level
2. Add a tileset and add collision
3. Add something that reacts upon the collison layer of said tilemap.
4. Set the tilemap to be invisible (via code)
5. See the "something" noclips at the invisible tilemap

### Minimal reproduction project

[Tilemap Collision MRP.zip](https://github.com/godotengine/godot/files/12929391/Tilemap.Collision.MRP.zip)

**Comment by groud** [comment]
Well, this was a bug that got fixed.

If you need that feature again you can set the TileMap `modulate` property to have an alpha of 0 for now, that should do the trick. There's demand for it, I guess we could implement a "disable rendering only" feature though.

**Comment by Zireael07** [comment]
Please add a "disable rendering only" feature - this is a problem that caught me out with other nodes too, not just Tilemaps.

**Comment by AThousandShips** [comment]
In this case the behavior of TileMap breaks with how other sources of physics works, so documentation is important, and an option to make it match other code (and old code) would be good

**Comment by Mickeon** [comment]
Yeah. If I make the player invisible it's not like he'd start spontaneously falling onto the ground. Are we sure this should qualify as a bug being fixed here?

**Comment by groud** [comment]
I've just checked and indeed you are right that physics node still work when being made invisible.
So yeah, for consistency this should be working as other physics nodes. I'll fix that.
