### ISSUE TITLE
2D game exported to android 11 (vivo Y12 ) takes way too long to load after splash screen and just shows black screen (with mobile and compatibility renderer both)

### ISSUE THREAD

**Issue by depstr** [godotengine/godot#83506]
### Godot version

GODOT 4.2 BETA 1

### System information

Windows 10 , Exported to android 11 , with Both Mobile and Compatibility

### Issue description

Hi,

**INTRO**
I exported 2d mobile game from windows 10 Godot 4.2 beta 1 to android 11 ( vivo Y12)  (tried with both mobile and compatibility version)

**ISSUE**
 the Godot 4.3 beta1 when i start the game on android  firstly splash screen appears then just BLACK SCREEN appears for long time then game starts. Even if the project just have single node 2d 
The android  games in Godot 3.5 launches much faster.

**Expected behaviour**
Expecting the android  games built in Godot 4.2 beta 1 launch faster like the Godot 3.5 games do.

**_SCREEN RECORDING:_**
https://github.com/godotengine/godot/assets/148219774/9be054b8-1568-43ff-8622-ac2799f035cf

Please Fix this issue 👍 

### Steps to reproduce

- Create any minimum scene ( even just with single node 2d ) 
- Export to android with (Mobile or compatibility )
- launch the game on android

### Minimal reproduction project

Above mentioned

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74348.

PS: Regardless of this issue, it's still expected that Godot 4 to be heavier than Godot 3 which can be noticeable on old, low-end devices.
