### ISSUE TITLE
Advancing to a completed non-looping animation state with `reset = false` to show last frame does not perform in StateMachine since there is no remain time

### ISSUE THREAD

**Issue by adambiser** [godotengine/godot#83522]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 730 (NVIDIA; 30.0.14.7414) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

I have an AnimationTree state machine with two states: falling and attack.  Both are non-looping animations.

What I want to do is have a falling animation where the final key frame values are held until the player hits the ground.
The attack state can interrupt the falling state at any point and after playing completely through (switch mode = At End), returns to the falling animation state where it left off (reset = false).

However, if the falling state has reached its end when the attack state is started, returning to the falling state does not process the final key frame values.  I would expect the final key frame state to be set.

### Steps to reproduce

1) Run the attached project.
2) When the falling animation finishes and top text says to press Space, press Space,
3) Note that the attack animation is performed.
4) When the final attack frame displays, note that the text stays the same and does not return to the "falling 2" text despite the fact that the state machine transitions to the "falling" state.

Note: I used a TextEdit control instead of a Label by accident.  The behavior is the same though.

### Minimal reproduction project

[AnimationTreeTest.zip](https://github.com/godotengine/godot/files/12956566/AnimationTreeTest.zip)

**Comment by TokageItLab** [comment]
This is simply because there is nothing left to play there anymore, so there is no transition. I understand that there needs to be a case where the transition takes place even though the animation has stopped.

It is not impossible to implement that behavior and I agree with making it the default behavior, but conversely, is there a case where we do not want to transition? (an option needs to be added) How do you think? @SaracenOne

**Comment by SaracenOne** [comment]
I've had a look at this, and I agree, it is very strange and unexpected that the transition occurs but no animation occurs. At present, I can't think any scenarios where this behaviour might be desirable, but I understand wanting to exercise caution when making a change like this. I'll think about this some more and maybe even take a look at what other engines do in this situation to get some more grounding on what would be considered the most correct behaviour.

**Comment by TokageItLab** [comment]
I thought again about it, but if there is nothing to play there, skipping the transition is most desirable. However, there is use case where the anyone want to continue to show last frame, so I believe that a correct way would be to implement an option like `keep_last_frame` that explicitly displays and processes (like looping) the last frame.

**Comment by adambiser** [comment]
I believe I've only halfway demonstrated the issue.  It is not just the final frame.

In general, transitioning to a new state does nothing visually until a key frame is reached, if ever.  This is not always the desired behavior.

**Comment by TokageItLab** [comment]
> In general, transitioning to a new state does nothing visually until a key frame is reached, if ever. This is not always the desired behavior.

This is just your problem with InterpolationMode being Discrete. You should set it to Continuous.

**Comment by adambiser** [comment]
I was just getting ready to say that, but I think using an interpretation mode of Nearest messed with the timing.  Will have to see whether I can duplicate.

**Comment by TokageItLab** [comment]
FYI also keep in mind there is PR related to Discrete mode with blending.

- https://github.com/godotengine/godot/pull/86629

**Comment by adambiser** [comment]
Ah, that looks interesting.  Thanks for mentioning it.
Apologies, but despite my best intentions, this is looking like a noob problem.

**Comment by adambiser** [comment]
Heh, I can't seem to edit the text to add a new key frame while the track is in continuous mode.  Keeps reverting back to the previous frame's text.

**Comment by TokageItLab** [comment]
I expect that in most of such cases, you forgot to deactivate the AnimationTree.

**Comment by adambiser** [comment]
It appears that using Continuous update mode with Nearest interpolation produces the expected behavior and resolves the original "issue".  I remember trying this when I first created the issue, but I think it looks correct now.

Thank you for looking into this and the help.

I'm going to close this.
