### ISSUE TITLE
Invalid (or incomplete) hex number "0x" floods error messages

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#83521]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

When I start writing a hex number in GDScript code, parser starts flooding error messages when the hex number is not yet valid.

First a single error appears, but very soon there will be 2 or 3 more. Every save (Ctrl-S) adds 5 more error messages.

I would expect to get only one error message.

![kuva](https://github.com/godotengine/godot/assets/49998025/62818f24-814f-4678-91d5-ffb8957591aa)

### Steps to reproduce

Write `var i = 0` first and then add `x`. 

```gdscript
extends Node2D

func _ready() -> void:
	pass
	var i = 0x
```

Output:

```
  Invalid hexadecimal notation character "x" (U+0078) in string "0x".
  Invalid hexadecimal notation character "x" (U+0078) in string "0x".
  ...
```

### Minimal reproduction project

N/A

**Comment by Shadowblitz16** [comment]
I just ran into this too.
![image](https://github.com/godotengine/godot/assets/2453707/f06227e4-6507-4e6a-b12c-da99df5279b4)

**Comment by andrew-wilkes** [comment]
It's annoying, but not a serious bug I think.

**Comment by AThousandShips** [comment]
I believe I've found a solution will test it later today
