### ISSUE TITLE
Issue with new TileMap Rotated Pieces & Collisions

### ISSUE THREAD

**Issue by Andrew1431** [godotengine/godot#83550]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3734) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Rotated-on-the-fly pieces struggle with collision data, seems intermittent, but when messed up, is consistent.

![image](https://github.com/godotengine/godot/assets/9736372/d950460d-1545-4bd4-bc35-e80222248ea6)
![image](https://github.com/godotengine/godot/assets/9736372/fe359502-9751-4656-8c6c-e78fca2ae6a1)

Re-modifying the collision data temporarily fixes the problem visually:

![image](https://github.com/godotengine/godot/assets/9736372/5c5b43dd-bfbd-45f6-8715-ac4629932f50)

But upon reloading the scene again, my collisions are gone.

### Steps to reproduce

Rotate-on-the-fly (not an "alternate tile") any piece with collision data, with collision visibility mode set to force-show you should see some odd behaviour. 

Loading said scene directly should have the collisions as expected
Loading said scene indirectly should have incorrect collision data.

### Minimal reproduction project

[Godot 4.2 beta Tilemap Reproduction](https://github.com/Andrew1431/gd42b-tilemap-repro)

If you run the "start" scene (default) with DEBUG COLLIDERS VISIBLE, you will see only 1 collider on the corner piece.

If you run the "demo.tscn" scene manually, all colliders are visible.

**Comment by akien-mga** [comment]
It would help greatly if you could provide a reproduction project (can just be one simple scene that exhibits the issue).

CC @KoBeWi @groud

**Comment by Andrew1431** [comment]
> It would help greatly if you could provide a reproduction project (can just be one simple scene that exhibits the issue).
> 
> CC @KoBeWi @groud

I attached a min-repro. https://github.com/Andrew1431/gd42b-tilemap-repro

If you run the "start" scene (default) with DEBUG COLLIDERS VISIBLE, you will see only 1 collider on the corner piece. 

If you run the "demo.tscn" scene manually, all colliders are visible.

**Comment by KoBeWi** [comment]
I can't open the demo.tscn, getting spammed with
```
ERROR: The TileSetAtlasSource atlas has no tile at (68, 1).
   at: (scene/resources/tile_set.cpp:4584)
ERROR: TileSetAtlasSource has no tile at (68, 1).
   at: (scene/resources/tile_set.cpp:4532)
ERROR: Cannot create tile. The tile is outside the texture or tiles are already present in the space the tile would cover.
```

**Comment by Andrew1431** [comment]
> I can't open the demo.tscn, getting spammed with
> 
> ```
> ERROR: The TileSetAtlasSource atlas has no tile at (68, 1).
>    at: (scene/resources/tile_set.cpp:4584)
> ERROR: TileSetAtlasSource has no tile at (68, 1).
>    at: (scene/resources/tile_set.cpp:4532)
> ERROR: Cannot create tile. The tile is outside the texture or tiles are already present in the space the tile would cover.
> ```

This is on `v4.2.beta1.official` ?

**Comment by Andrew1431** [comment]
I just recloned the project using `v4.2.beta1.official.b1371806a` and didn't have any issues reproducing the error.

**Comment by Andrew1431** [comment]
So do with this issue what you will, I'm presently just using alternate tiles and it's working as expected.

**Comment by KoBeWi** [comment]
For me both the editor and the game become unresponsive.

**Comment by KoBeWi** [comment]
Closing in favor of #83825, which comes with a better project.
