### ISSUE TITLE
FileSystem Not Highlighted After Duplicating An Asset

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#83554]
### Godot version

4.2 Beta

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

When duplicating and naming an asset (such as a .tres material file) the filesystem is no longer highlighted/in focus.
This means a user cannot duplicate assets one after the other without clicking into the FileSystem window again first.
Assuming this is a bug because there's no reason this should become unfocused after an operation in the FileSystem.

### Steps to reproduce

Duplicate an asset in the FileSystem (forcing a rename). After hitting enter, the FileSystem will be unfocused.

### Minimal reproduction project

N/A

**Comment by miv391** [comment]
Same issue as https://github.com/godotengine/godot/issues/82774

**Comment by WickedInsignia** [comment]
Correct! Closing as a duplicate.
Thanks for heads-up!
