### ISSUE TITLE
Right stick joypad Input not working properly with Xbox Controller on Linux with 4.2.beta1

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#83552]
### Godot version

Godot_v4.2-beta1_linux.x86_64

### System information

PopOS 22.04, Linux 6.5.4-76060504-generic x86_64, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

When trying to map inputs on the right stick on an Xbox controller (Elite or non-elite), the mappings are incorrect still on Linux. 

This is related to https://github.com/godotengine/godot/issues/81816

I commented in the above issue when it was active but the changes made did not fix the issue in Linux.

This happens on two machines and also has happened across multiple Linux distros like Fedora, Ubuntu, PopOS, Manjaro.

This also happens regardless if I used xpadone, xone, etc... and regardless of if this is over bluetooth, wired, or xbox wireless dongle

Also, the Steam output is correct and I've attached a video of it below.

### Steps to reproduce

When moving the right joystick:

Down:

![joystick_down_outputs_random](https://github.com/godotengine/godot/assets/15805689/c6271d75-da19-420f-8946-a324c801e686)

Left:

![joystick_left_outputs_joystick_up](https://github.com/godotengine/godot/assets/15805689/bf1106d7-16d1-4b4a-89db-bb064a2af876)

Right:
![joystick_right_outputs_joystick_down](https://github.com/godotengine/godot/assets/15805689/0773f9ba-0d26-40f8-ad3f-dceb4dbd0ba2)

Up:

![joystick_up_outputs_joystick_2_left](https://github.com/godotengine/godot/assets/15805689/4419768f-7758-4616-ae7b-507709df91a5)

---

xinput output:

![Screenshot from 2023-10-18 07-18-31](https://github.com/godotengine/godot/assets/15805689/0c2a2210-d8fe-412c-88bb-cfffbfbf2af3)

Bluetooth:

![godot_4 2_beta1_controller_test_bluetooth](https://github.com/godotengine/godot/assets/15805689/56d4e135-6e31-468b-a5b1-8df3afc791c2)

Video of Steam Output which is correct:

https://github.com/godotengine/godot/assets/15805689/63b14c82-15c9-4fd2-8b90-e2abdea48d16

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
What's the exact model of the controller(s) you're testing with?

Can you retrieve the UUID(s) and mapping using one of the tools described here? https://github.com/gabomdq/SDL_GameControllerDB#mapping-tools

It might be that it's just missing in SDL_GameControllerDB, or that we need to sync the past couple of weeks of additions.

**Comment by akien-mga** [comment]
This mapping seems to be missing in https://github.com/gabomdq/SDL_GameControllerDB, so it should probably be PR'ed to add to their list, which we'll then also get in Godot next time I sync.

I'm just puzzled that it's described at "Xbox 360 Controller", this might be Steam Input giving it a generic name.
Might be worth checking if one of the other listed tools in https://github.com/gabomdq/SDL_GameControllerDB#mapping-tools would infer a more specific name. But the SDL_GameControllerDB might have further advice about how to ensure the mapping is as accurate as possible.

BTW, you can test that mapping in Godot by passing it via the `SDL_GAMECONTROLLERCONFIG` environment variable:

```
SDL_GAMECONTROLLERCONFIG="050000005e0400008e02000030110000,Xbox 360 Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,crc:f003,platform:Linux," godot
```

**Comment by akien-mga** [comment]
Seems like the `crc:` field is a known issue with one of the mapping apps: https://github.com/gabomdq/SDL_GameControllerDB/issues/476#issuecomment-1413186422

So the `crc:9d50,` part should just be removed.

Would you be able to make a PR to https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt with your mappings?

**Comment by akien-mga** [comment]
Thanks for the ping, I'll sync with the SDL repo.

**Comment by Shashlik25** [comment]
Guys, help me solve this error,please, what do I need to do to make it go away? xbox series gamepad, I'm a newbie

**Comment by Hikitile** [comment]
@Shashlik25 I use this workaround on flatpak with flatseal

1. Open /home/red/.var/app/com.valvesoftware.Steam/.local/share/Steam/config/config.vdf
1. Copy the last line in "SDL_GamepadBind" without crc:1234

    Example:

030082795e040000ea02000001030000,Xbox One S Controller,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b8,start:b7,leftstick:b9,rightstick:b10,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,~~crc:7982,~~ platform:Linux,

3. In Flatseal, add the environment variable GAMECONTROLLERCONFIG=\<The text without crc>
4. Start Steam

**Comment by Shashlik25** [comment]
@Hikitile Thanks, works for me. U saved my nervs
