### ISSUE TITLE
Forward+ rendering is black in XR

### ISSUE THREAD

**Issue by ikonnow** [godotengine/godot#83555]
### Godot version

Godot v4.2.beta1

### System information

Godot v4.2.beta1 - Windows 10.0.22000 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3758) - AMD Ryzen 9 5900HX with Radeon Graphics (16 Threads)

### Issue description

When using the newest version of Godot (before in 4.1 it was working), the forward+ rendering mode does not work properly in XR. The passthrough mode seems to work, but the regular output shows a black screen on the headset. In the editor, the scene looks as expected. This issue might be related to the GodotXR code or XR-kit update. I am using the current version from the AssetLib.

### Steps to reproduce

1. Create a new project in Godot and enable the forward+ rendering mode.
2. Add some 3D objects and lights to the scene.
3. Enable the XR plugin and relevant OpenXR settings.
4. Run the project and observe the output on the headset.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
Please test in 4.2-beta4 when it's released (probably tomorrow). It should fix issues exporting to Android, and there's been a number of XR and rendering fixes since beta 1.

**Comment by BastiaanOlij** [comment]
I need to do some more testing, but for me its working fine in Compatibility and Vulkan mobile. Vulkan Forward it is also working but for some reason I was having performance issues. This may however be an unrelated error.

This is all testing with todays master.

Note that a black screen in Quest usually means a step was overlooked, either the wrong plugin was installed (there are new plugins for 4.2, the 4.1 loader plugin no longer works) or initialisation failed.

Sadly logging in 4.2 on Android broke which makes it harder to debug.

**Comment by ikonnow** [comment]
> Please test in 4.2-beta4 when it's released (probably tomorrow). It should fix issues exporting to Android found in beta 3, and there's been a number of XR and rendering fixes since beta 1.

I've tested the 4.2-beta4 and it worked again - that's really awesome! I'm not sure though why my performance is so bad. I will do some further testing. Right now I'm down to 70FPS which is bad, and will need some further investigation maybe some scene optimizations.
