### ISSUE TITLE
iOS exports with plugins failing with Xcode 15 

### ISSUE THREAD

**Issue by stevencodeuk** [godotengine/godot#83556]
### Godot version

4.1.2.stable

### System information

Mac Mini M1

### Issue description

Newbie here, sorry if I have done anything wrong!
iOS export with Xcode 15 works fine when no plug-ins are enabled.
Enable a plug-in (Poing Studio's AdMob for instance, but I've tried others) and the export fails with "all symbols not found for architecture arm64" errors due to ld (linking?)

### Steps to reproduce

New project
Export to iOS with Xcode 15 and works fine
Enable an iOS plug-in and export fails

### Minimal reproduction project

Needs App Store Team ID and Bundle Identifier
[godot_testgodot.zip](https://github.com/godotengine/godot/files/13028048/godot_testgodot.zip)

**Comment by YuriSizov** [comment]
cc @bruvzg

**Comment by gumaciel** [comment]
@stevencodeuk this problem still happen?

**Comment by stevencodeuk** [comment]
Yes. Never been able to build with Xcode 15.

**Comment by stevencodeuk** [comment]
Don't think this is a Godot issue.
