### ISSUE TITLE
Problem with autotileing

### ISSUE THREAD

**Issue by Aronthata** [godotengine/godot#83565]
### Godot version

4.1.1

### System information

mobile

### Issue description

when deleting a tile layer  (ex, grass) that is in use godot crashes

### Steps to reproduce

create a terrain layer in Godot then create a layer named grass then add a layer to the tile in the tile map for auto-tiling and delete the grass layer

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can you please try this on a recent version like 4.1.2

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you add the requested details this can be reopened
