### ISSUE TITLE
No error thrown when accessing non-existent property or method

### ISSUE THREAD

**Issue by TheColorRed** [godotengine/godot#83567]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14037.17019) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When creating a class that doesn't extend anything, and you try to reference a property/method that doesn't exist no error is thrown.

This makes it hard to debug sometimes, especially if it is just a small typo such as switching two letters around by accident.

### Steps to reproduce

Create a class that doesn't extend anything:

```gdscript
class_name MyClass

var my_var: String = ''
```

Access the class from another class (such as one attached to a scene):

```gdscript
extends Node

func _ready():
	var c := MyClass.new()
	c.non_exist = '123'
	c.my_var = 123
	c.non_existing()
```

![image](https://github.com/godotengine/godot/assets/1571806/1bfceac4-4313-4d00-b5d3-d5b8e61776bf)

### Minimal reproduction project

[no_error.zip](https://github.com/godotengine/godot/files/13031474/no_error.zip)

**Comment by Calinou** [comment]
> Create a class that doesn't extend anything:

I didn't even know that was possible… if anything, I'd expect that to be an error on its own. Implicitly extending a class that isn't written isn't great from a documentation/UX perspective.

**Comment by TheColorRed** [comment]
Yeah, its `RefCounted` if I do `print(c)`. 

In my case, I changed to to `extend Resource`, but you are still able to set non-existent variables.

**Comment by YuriSizov** [comment]
> There's no way to know without reading the source code.

Or documentation 🙃

**Comment by KoBeWi** [comment]
See https://github.com/godotengine/godot-proposals/issues/8145

**Comment by TheColorRed** [comment]
@KoBeWi Setting `unsafe property access` to warn/error and disabling `Exclude Addons` solved this.

> I didn't even know that was possible…

However, for @Calinou comment, I am not sure if I should leave this open or not...

**Comment by YuriSizov** [comment]
This is old and documented behavior. A change to it would be breaking and can only be done in Godot 5, which is not planned yet. And it would need a proposal to justify the change. So if you consider your issue resolved, feel free to close it.
