### ISSUE TITLE
[Android 13] Immersive mode don't work on Godot 4.2 beta1

### ISSUE THREAD

**Issue by dannygaray60** [godotengine/godot#83566]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Android 13 Samsung S20 5G

### Issue description

The Top bar is still visible in exported game with godot 4.2 beta1, this is no issue in 4.1.

![unnamed (1)](https://github.com/godotengine/godot/assets/30391210/46aa6165-2098-441f-b968-38192657a4e1)

And not matter if you have gesture nav or button nav, the result is the same:

![unnamed](https://github.com/godotengine/godot/assets/30391210/0535c9de-0a84-4354-957a-c970741cf9c9)

Maybe is related with the [PR#61472](https://github.com/godotengine/godot/pull/61472)

And in android settings the "show camera cut" is set on "hidden" but still visible

### Steps to reproduce

Export v4.2.beta1.official [b1371806a] android game with default export settings and play on Android 13
![Captura de pantalla 2023-10-18 101703](https://github.com/godotengine/godot/assets/30391210/62c40755-8d0f-49f4-b848-6481fd5eefd5)

### Minimal reproduction project

Not tested on empty project... But on godot 4.1 stable working with no problem.

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/80574.

**Comment by Zamir7** [comment]
godot 4.2 beta 3, immersive "on" don't work in android. Status bar is visible/
