### ISSUE TITLE
Duplicating a scene also duplicates child nodes' UIDs.

### ISSUE THREAD

**Issue by Ratslayer** [godotengine/godot#83575]
### Godot version

4.1.2.stable.mono

### System information

Windows 11

### Issue description

Duplicating a scene duplicates UIDs of all sub-nodes, such as MeshInstance3D.

### Steps to reproduce

There is a single script, PrintChildUID, that exposes a MeshInstance3D node and prints its UID in the _Ready method.
The scene print_node.tscn is a simple node3D scene with the PrintChildUID script and a single MeshInstance3D child
Repro steps:
Open main_scene.tscn
Duplicate any node in the scene
Launch the game
Observe that UIDs of duplicated nodes are all the same in the output, while they should be different.

### Minimal reproduction project

[uid-bug-repro.zip](https://github.com/godotengine/godot/files/13032880/uid-bug-repro.zip)

**Comment by Rindbee** [comment]
When copying a node, the exported variable `_mesh` on the new node will reference the original value. This doesn't seem to be a bug.
```C#
GD.Print($"_mesh UID: {_mesh.GetInstanceId()} ", $"child UID: {GetNode("MeshInstance3D").GetInstanceId()}");
```
Although the `_mesh` is exported as node type `MeshInstance3D`, it is recorded as `NodePath` in tscn.
```tscn
[node name="Node3" parent="." instance=ExtResource("1_vwf8e")]

[node name="Node4" parent="." instance=ExtResource("1_vwf8e")]

[node name="Node5" parent="." node_paths=PackedStringArray("_mesh") instance=ExtResource("1_vwf8e")]
_mesh = NodePath("../Node4/MeshInstance3D")
```

**Comment by Rindbee** [comment]
The problem is that you use `_mesh` to cache child node. Then you seem to be weird that the `_mesh` of the copied node has the same uid (refers to the same node) .

**Comment by Rindbee** [comment]
There are two ways to think about it:
1. Node instance: Saving the same instance is expected;
2. NodePath: Keeping the value (usually a relative path) is also expected;

Consider a case where the exported variable cache is a node in the main scene. If you copy the node, and then paste it in a different node tree depth, there may be problems with the relative path, keep the same instance may be better.

In my opinion: Node instance is suitable for the above case; and `NodePath` is used for cases where the relative path does not change, such as your case.

**Comment by Rindbee** [comment]
Please see [C# exports Nodes](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_exports.html#nodes) and [Node.GetNode*](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-get-node). Use `NodePath` type instead of `Node` type.

**Comment by Rindbee** [comment]
> It's only duplicate (Ctrl+D) which does not work the same way as everything else.
> I don't know how you can say that this is intended behaviour.

Overwriting the property `value`s of the copied node with the property `value`s of the source node is the **default** behavior.

> "Since Godot 4.0, nodes can be directly exported without having to use NodePaths.
> This reads like exporting Nodes is supposed to replace NodePaths and should work the same way.

If you are just using it in a simple scene (no sub-scene, or passing node references from the main scene into the sub-scenes), yes, they work the same.

> Exporting NodePaths like in Godot 3.x is still possible, in case you need it"

This is exactly the case where `NodePath` is needed. Because what you want is that they each reference nodes in the corresponding sub-scene, not nodes in the main scene.

**Comment by Leshy-YA** [comment]
I also encountered this bug. When duplicating, scenes, all duplicated scenes reference the internals of the source scene. Which is incorrect. They should retain their internal structure. The same issue occurs if the node is copy/pasted.

> Overwriting the property `value`s of the copied node with the property `value`s of the source node is the **default** behavior. So it's not unexpected behavior for them to reference the same node instance.

It is unexpected, because it doesn't make any sense from a usability perspective and there is no use case for which this would be useful. Furthermore for the most default use case this behaviour is simply **incorrect**.

**Comment by Leshy-YA** [comment]
It would seem the workaround for this is to make sure the exported properties are not in the top level node, but in a node further down the hierarchy. Then everything works as expected. 

But again, this is a serious usability issue, making duplicating nodes very error prone.

**Comment by KoBeWi** [comment]
Can't reproduce on master, I think #83343 fixed it.
Also you are confusing UIDs with Object IDs. They are 2 different things.
