### ISSUE TITLE
Translations that start with an `_` or `-` generate a file named `<translation>..translation`

### ISSUE THREAD

**Issue by IntangibleMatter** [godotengine/godot#83573]
### Godot version

4.1.1 stable

### System information

Linux Pop!_OS 22.04 LTS

### Issue description

When you create a CSV file to import for translation, if you have a locale that begins with an underscore or a hyphen, it will be semi-ignored, with all columns that have a hyphen or underscore being shoved into one translation file with the name <rootfile>..translation. 

Ideally this would be imported properly, or better yet work like godotengine/godot-proposals#8183.

### Steps to reproduce

Create a translation CSV and add a locale column that starts with an `_` or a `-`. Import it, and a translation file with no locale will be imported.

### Minimal reproduction project

[trtest.zip](https://github.com/godotengine/godot/files/13031642/trtest.zip)

**Comment by jsjtxietian** [comment]
Confirmed. I think for this bug fix we can just ignore the empty "lang" tags. As for that proposal, it may still need more discussion before implentation.

**Comment by bruvzg** [comment]
Locale code should have specific format, see - https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-locale
