### ISSUE TITLE
Script Text Editor Duplicate Lines shortcut acts wrong when cursor is at the top

### ISSUE THREAD

**Issue by kitbdev** [godotengine/godot#83589]
### Godot version

4.2.beta 

### System information

Godot v4.2.beta (7f884b4e0) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

related: https://github.com/godotengine/godot/pull/66553

Selecting text from top to bottom works as expected, but selecting text from bottom to top instead duplicates the first line then the rest.

![godot_duplicate_line_issue](https://github.com/godotengine/godot/assets/10054226/7d31ee80-b8f8-4e66-be79-33e2bdd22985)

### Steps to reproduce

Write at least 3 lines in text editor.
Select them from bottom to top, so that the blinking cursor is at the top.
Use duplicate lines shortcut (ctrl+alt+down/shift+alt+down).

### Minimal reproduction project

n/a

**Comment by MartinVacheron** [comment]
Hi, just got into the same problem in Godot 4.3 dev 5.
