### ISSUE TITLE
VoxelGI doesn't take shadows into account

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#83585]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Vulkan (Forward+), NVIDIA GeForce RTX 2060 SUPER (nvidia; 535.113.01)

### Issue description

VoxelGI doesn't take shadows into account, causing rooms that should be dark to be lit.

here's how it looks:

scene without SDFGI/VoxelGI:
![image](https://github.com/godotengine/godot/assets/7088062/4cc8efc1-b214-433a-aa77-7dfdc5cce4c9)

inside the room it's completely dark:
![image](https://github.com/godotengine/godot/assets/7088062/09496585-a2f2-441d-97d3-4fb03e1f2e12)

with SDFGI:
![image](https://github.com/godotengine/godot/assets/7088062/fb2a4216-adc3-4097-9d92-b9a6a8101320)

with VoxelGI:
![image](https://github.com/godotengine/godot/assets/7088062/bf027c69-72a4-4eba-a08d-27ad99a7e1a3)

with VoxelGI and the the directional light set to invisible:
(implying it has something to do with VoxelGI receiving light)
![image](https://github.com/godotengine/godot/assets/7088062/3834e124-0a09-4871-9cc9-c9acdf012ffc)

### Steps to reproduce

to make it noticeable in the scene's Environment disable ambient light.

create a light (any type) that casts shadows.

create a room with its interior being completely shadowed.

add VoxelGI and bake it.

### Minimal reproduction project

[voxelGI_shadow_bug.zip](https://github.com/godotengine/godot/files/13034630/voxelGI_shadow_bug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80123.
