### ISSUE TITLE
Update `_unhandled_key_input` documentation

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#83581]
### Godot version

v4.2-beta1

### System information

-

### Issue description

Currently, the documentation for `_unhandled_key_input` states that it will only receive `InputEventKey` events but there is no mention about `InputEventShortcut` which will be received by it as well.

At the end there is a mention about using `_shortcut_input()` instead for shortcut input events which would also benefit from some edits?

![image](https://github.com/godotengine/godot/assets/102416174/96162e4d-e3ad-465d-ad2b-b209c2383cf8)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by Sauermann** [comment]
Can you please provide a minimal reproduction project, where an `InputEventShortcut` is received by `_unhandled_key_input`?

The implementation suggests, that only an `InputEventKey` is sent to `_unhandled_key_input`:

https://github.com/godotengine/godot/blob/7f884b4e0017368e193d96f425aac6c2d8a86eb0/scene/main/viewport.cpp#L3233-L3237

**Comment by KoBeWi** [comment]
CommandPalette activates shortcuts using InputEventShortcut. The method was originally changed in #49417, though some details might've changed.
In any case, this can pretty much happen only in the editor, unless a user manually sends such event.

**Comment by Swarkin** [comment]
Ive received opposite information before but it seems its been changed/fixed in 56695
