### ISSUE TITLE
Tween doesn't work properly with dynamic nodes added to the three

### ISSUE THREAD

**Issue by claudio-cavalcante** [godotengine/godot#83598]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

In this attached project, I've created a card game. I'm trying to create a behavior where you put the mouse over the card and the card scales 120%. It works with the **card** node under the **Cards** node, but for cards added dynamically after starting the game this same tween doesn't work. Both cards (the card already included and the cards added dynamically are from the same scene. So they use the same script).

For the card that is initially in the tree, you can see it's scaling and only returning to the original size after the mouse exit.
For the three cards added dynamically, you can see that it returns to the original size without leaving the cursor.

### Steps to reproduce

1. Play the game
2. Put the cursor over the card on the top
3. See how the scale is kept while you are with the mouse over the card
4. Put the cursor over any other three cards
5. See how it returns to the original size while the mouse is over it.

### Minimal reproduction project

[physicsTest.zip](https://github.com/godotengine/godot/files/13036672/physicsTest.zip)

**Comment by claudio-cavalcante** [comment]
The problem is the tween of position is interfering in the tween of scale.

**Comment by ctonha-tricentis** [comment]
I think this needs to be reopened
