### ISSUE TITLE
GPUParticles jitter heavily when strong turbulence is applied

### ISSUE THREAD

**Issue by NitramiuZ** [godotengine/godot#83607]
### Godot version

4.2.beta1

### System information

Windows 11- Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.57003) - AMD Ryzen 7 7735U with Radeon Graphics (16 Threads)

### Issue description

When using turbulence the particles jitter (alternate) back and forth between two positions as they animate.

Short video of this happening in 4.2 beta1
https://github.com/godotengine/godot/assets/67265963/66d15363-809c-44b3-ac71-b48f6ebb3946
(It is not as noticable in the video, I would recommend check out the Minimal reproduction project) 

Compare this to 4.1.1 (same settings):
https://github.com/godotengine/godot/assets/67265963/104e4a84-c84e-4a41-8a80-2b9d14e5ea89
(It is even smoother without the framedropping in the video (sorry))

### Steps to reproduce

Use a GPU particles node with turbulence enabled and a strong influence

### Minimal reproduction project

Test scene with a simple GPUParticles with heavy turbulence (as shown in video) (for 4.2.beta1)
[ParticleJitterBug.zip](https://github.com/godotengine/godot/files/13040694/ParticleJitterBug.zip)

Same project but for 4.1.1 (for comparisons):
[ParticleBugStable.zip](https://github.com/godotengine/godot/files/13040750/ParticleBugStable.zip)

**Comment by akien-mga** [comment]
I confirm the bug in 4.2-beta1 and beta2. It seems to have been fixed as of beta3 and latest `master`.
