### ISSUE TITLE
Imported SVG semi-transparent areas become fully opaque

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#83611]
### Godot version

4.2beta1

### System information

macOS 13.6.0 - Vulkan (Mobile) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

Importing SVGs (via editor or in code using the Image.load_svg_from_string() etc) that have semi-transparent areas result in these areas being fully opaque instead of having the expected semi-transparent alpha values.

Left imported svg in Godot, right same svg in Firefox

![Screenshot 2023-10-19 at 12 48 35](https://github.com/godotengine/godot/assets/17763524/2db61fd8-dde7-47bc-9397-7b6c97fdee61)

This seems this is an issue with ThorVG as the same issue is present in their [viewer](https://thorvg.github.io/thorvg.viewer/). So I've opened an issue there as well ( https://github.com/thorvg/thorvg/issues/1716 ). But since this affects Godot I'm opening this here so it's known and we can keep track of the issue. 
If you don't want these kinds of double issues feel free to just close this. 

_EDIT: Here's a better example image showing off the issue, made by @capnm, where you can see that the alpha is also incorrect in the overlapping area._
![276603482-08b69b8c-1f4c-4319-ba18-c635c07db42b](https://github.com/godotengine/godot/assets/17763524/713dde84-8ec5-4661-b5b2-569a77f2d8d1)

### Steps to reproduce

Import the following svg image into a godot project

![OpacityTest](https://github.com/godotengine/godot/assets/17763524/12e2f2b2-feb5-49fa-9c44-cbd4914b4ecf)

### Minimal reproduction project

see image file above

**Comment by lostminds** [comment]
Looks like the issue has been fixed on the ThorVG side now and a [new 0.11.2 release is available](https://github.com/thorvg/thorvg/releases/tag/v0.11.2) that we can update to in Godot to hopefully fix this issue.

**Comment by capnm** [comment]
Godot + v0.11.2
![Screenshot from 2023-10-20 07-59-44](https://github.com/godotengine/godot/assets/4047289/fb0657b4-380a-483d-824b-5b9f326cf654)

PNG
![Screenshot from 2023-10-20 07-23-34](https://github.com/godotengine/godot/assets/4047289/e7cb04f9-7a3b-4725-8340-70c4e591f70a)

SVG
![83611_opacity_test](https://github.com/godotengine/godot/assets/4047289/fbf6a4d8-9cd0-49a8-8f3c-454914f82fc1)
