### ISSUE TITLE
Remote debugging with external editor only works if gdscript files are open in script editor

### ISSUE THREAD

**Issue by CNDW** [godotengine/godot#83614]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

### Issue description

I'm using vscode with the godot editor configured to use an external text editor. Everything is configured properly, I'm able to run the game and editor from vscode and vscode is able to connect to the language server and remote debugger without issues.

If I attempt to set a breakpoint from vscode, I see the following error in the godot console
```
editor/debugger/debug_adapter/debug_adapter_protocol.cpp:800 - Condition "!breakpoint_list.find(breakpoint)" is true. Returning: Array()
```

While keeping the game running, open the file inside of the godot script editor. the error stops reporting and setting breakpoints from within vscode works. Closing the files in the godot script editor causes the error to return and breakpoints to stop working.

### Steps to reproduce

1) Open a project with both vscode and the godot editor
2) Run the game using the vscode "run and debug" menu
3) ensure no files are open in the godot script editor and open the 2D editor
4) attempt to set a breakpoint in vscode

### Minimal reproduction project

N/A

**Comment by dainbrump** [comment]
Exact same error message with Godot 4.1.2 .NET edition in VSCode. This issue does not appear when using Godot 4.1.1.

**Comment by dainbrump** [comment]
I believe I stumbled on a workaround / fix. I'm able to get debugging in VSCode with functional breakpoints by doing the following.

In Godot editor:
1. Editor -> Editor Settings
2. Under Network -> Debug. Set Remote Port to 6007
3. Under Network -> Debug Adapter. Set Remote Port to 6008, Sync Breakpoints to On

In VSCode:
1. Edit the project's launch.json
2. Make changes to the `port` and `debugServer` values. Set the `port` value to what you used in Network->Debug in the Editor Settings. Set `debugServer` to the value you set in Network->Debug Adapter in the Editor Settings. Here's what mine looks like.

```json
"configurations": [
    {
        "name": "Godot Debug",
	"type": "godot",
	"request": "launch",
	"project": "${workspaceFolder}",
	"port": 6007,
	"debugServer": 6008,
	"address": "127.0.0.1",
	"launch_game_instance": true,
	"launch_scene": false
    }
]
```

Hopefully this helps.
