### ISSUE TITLE
NavigationObstacle3D node not behaving as in earlier stable version 4.0.3

### ISSUE THREAD

**Issue by Shigewara** [godotengine/godot#83625]
### Godot version

4.2.beta2

### System information

Godot v4.2.beta2 - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 30.0.100.9864) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/59742018/8623b8c0-563a-47ee-ab29-48e7efa5dde4

### Steps to reproduce

Having a functional NavMesh and a testunit coded to move to mouse along a baked Navigation Mesh over a plane mesh with a trimesh static body created, as in the linked video.
1. Create a NavigationObstacle3D node. 
2. Set radius to 2 meters.
3. Create a Node3D and make this the parent of the NavigationObstacle3D node.
4. The testunit will not avoid the obstacle, and only do so once the Node3D has been moved on the y-axis to approximately 0.25 meters

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
When is "before"? What version are you comparing to?

**Comment by Shigewara** [comment]
Right. Before was in this case Godot 4.0.3 rc1

**Comment by AThousandShips** [comment]
Does this behavior exist in a stable version, like 4.0.2 or 4.0.3, 4.0.3.rc1 is a development release and doesn't represent stable behavior

**Comment by smix8** [comment]
Whatever offset or scale change is hidden there:
![tc](https://github.com/godotengine/godot/assets/52464204/6337a35b-a761-4fb7-9efd-bcb3a4dc8706)

**Comment by Shigewara** [comment]
It has been uniformely scaled from 1 to 2. Changing that transform change back to default still leaves the same issue. Nothing changed. 
I made a simple test project in 4.0.3 stable and this issue does not exist in this stable version.

**Comment by Shigewara** [comment]
[4.0.3 Bug Test.zip](https://github.com/godotengine/godot/files/13045462/4.0.3.Bug.Test.zip)

**Comment by Shigewara** [comment]
This bug also persist if after opening "4.0.3 bug test" project in 4.2 you change radius to 1 meter

**Comment by smix8** [comment]
There is a bug with the NavigationObstacle3D `height` setter. Until fixed change the `height` of the obstacle slightly from the default value or use the `NavigationServer3D.obstacle_set_height()` function to set it directly.

That said the new avoidance introduced with 4.1 changed a lot so you might want to read up on that especially with the new documentation for NavigationAgents and NavigationObstacles.

**Comment by Shigewara** [comment]
Ok. Thanks for the advice! I'll look up on that documentation.

**Comment by smix8** [comment]
Closing as the two fix prs have been merged.

**Comment by ChildLearningClub** [comment]
4.2 beta 5 . I believe something may have broken again? I have tried changing heights and settings, but the NavigationObstacle3D is not avoided despite NavigationAgent3D avoidance enabled setting On.
