### ISSUE TITLE
3.0 Profiler is broken

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8363]
3.0 alpha (April 3rd build) x64 linux kubuntu 16.10

When running PBR demo with profiler you can see values for time taken on processes go all over the place (negatives too). 
![sc-20_28_23-1104](https://cloud.githubusercontent.com/assets/10696955/24922329/9d2f3316-1ef6-11e7-9c6a-d3ee4329207f.png)
Steps to reproduce: 
1. Launch g3 pbr test 2
2. Launch project
3. Go to Monitors tab
 

VideoMem tab doesn't show path to resource. 
![sc-20_45_00-1104](https://cloud.githubusercontent.com/assets/10696955/24922650/c17f61e0-1ef7-11e7-882c-45e674c36b03.png)

Steps to reproduce: 
1. Launch pbr test 2 project
2. Go to VideoMem tab of profiler
3. Click "Refresh"

Output is broken on overflow (?) 

![sc-20_42_07-1104](https://cloud.githubusercontent.com/assets/10696955/24922550/6df35aea-1ef7-11e7-9292-bc18aa5c5277.png)

Steps to reproduce: 
1. Go to WorldEnvironment node.
2. Edit Environment resource
3. Edit values by dragging slider

**Comment by kubecz3k** [comment]
Author of the issue deleted his account in mean time, so there is no one who could answer the questions, test the issue or provide reproduction sample. Please open new issue if you think the issue still persists.
