### ISSUE TITLE
Scroll begin and Scroll end notifications are not sent

### ISSUE THREAD

**Issue by AhNesh** [godotengine/godot#83633]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10

### Issue description

The NOTIFICATION_SCROLL_BEGIN and NOTIFICTION_SCROLL_END notifications are not propagated to child nodes of ScrollContainer. 

### Steps to reproduce

The MPR has a main scene with a ScrollContainer, a VBoxContainer and a bunch of Labels so it is tall enough to scroll. The first label has this script:
```GDScript
func _notification(what):
	if what == NOTIFICATION_SCROLL_BEGIN:
		print("scroll begin") #never happens
	elif what == NOTIFICATION_SCROLL_END:
		print("scroll end") #never happens
```

Scrolling in the ScrollContainer should trigger this notification, but it does not.

### Minimal reproduction project

[scroll notification.zip](https://github.com/godotengine/godot/files/13046357/scroll.notification.zip)

**Comment by AThousandShips** [comment]
Related to:
* https://github.com/godotengine/godot/issues/81512
