### ISSUE TITLE
Broken Collisions on Spiral Structure

### ISSUE THREAD

**Issue by cuppajoeman** [godotengine/godot#83640]
### Godot version

4.2.beta

### System information

Godot v4.2.beta (a574c0296) - Manjaro Linux #1 SMP PREEMPT Sat Sep 23 10:10:02 UTC 2023 - X11 - GLES3 (Compatibility) - Mesa Intel(R) HD Graphics 3000 (SNB GT2) () - Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 Threads)

### Issue description

When a spiral structure is imported from a blend file within godot, collisions do not work correctly; objects get stuck inside.

 

https://github.com/godotengine/godot/assets/19198104/75fb39d8-ad02-42ef-a121-777bedeebf74

### Steps to reproduce

Download and unzip the minimal reproduction project and import it into godot.

Install Blender 3.6.5

Launch godot, in editor settings specify the path to the blender executable.

Reload the project and make sure `spiral_staircase.blend` is visible in the main scene.

Run the project in godot and see the problem

### Minimal reproduction project

[spiral_staircase_test.zip](https://github.com/godotengine/godot/files/13047882/spiral_staircase_test.zip)

**Comment by Calinou** [comment]
Your spiral's normals are inside-out:

![image](https://github.com/godotengine/godot/assets/180032/27b54006-10cb-4936-bdeb-4d6955cd1539)

This is a modeling issue within Blender. You can fix it by selecting the spiral's vertices, pressing <kbd>Alt + N</kbd> then choosing **Flip**.

**Comment by cuppajoeman** [comment]
Ah ok, this totally fixes my problem, thanks Calinou :1st_place_medal:
