### ISSUE TITLE
Icon buttons are "jumpy" on hover in the editor (stylebox mismatch)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8364]
**Operating system or device - Godot version:**
Linux - Godot master/HEAD (faee2fb), 2.1/HEAD (8df5b71, fixed in subsequent revert d8ae244)

**Issue description:**
When you hover buttons with icons in the editor, such as the play/stop scene buttons at the top, or the buttons at the top of each docks, they seem like "jumping", i.e. they are drawn at an offset to their normal stylebox margins.

It's a regression from 98f01f914333eb5e70174c4adf4a5f910a38d645 by @RayKoopa. I've reverted it in 2.1 as I'm releasing 2.1.3-stable - for master maybe it can be fixed differently if we want to keep the patch.

**Steps to reproduce:**
- Move your mouse over one of the mentioned icon buttons

**Comment by RayKoopa** [comment]
Thinking about it every time I hover a button.
At least I don't understand styleboxes anymore, not seeing an error in them... and I found it hard to debug why it happens on some buttons and not others.

**Comment by volzhs** [comment]
@akien-mga we can revert the reverted d8ae244d51ed157d96346c510baeb637239e3200 with #8369

**Comment by alex9099** [comment]
Yea, also thinked about reporting that, but i was too lazy because it was not something that bother'd me :D

**Comment by akien-mga** [comment]
Fixed by #8370.
