### ISSUE TITLE
4.2.beta2 .Net -- Android build error

### ISSUE THREAD

**Issue by architeer** [godotengine/godot#83651]
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Godot v4.2.beta2.mono - Windows 10.0.19045 - GLES3 (Compatibility) - Quadro 2000M () - Intel(R) Core(TM) i7-2860QM CPU @ 2.50GHz (8 Threads)

### Issue description

There is an Android build error during Export or Remote Debug

"Cannot remove non-existent file or directory: C:/Users/{username}/AppData/Local/Godot/tmpexport.1697760517.apk"

This problem started happening with this 4.2.beta2 version.  Reverting back to Godot 4.2.beta1 works fine.  

### Steps to reproduce

1. Create new project using Godot .NET v4.2.beta2
2.  Install Android Build Template
3.  In Export, in "Android (Runnable", tick on the "Use Gradle Build" and select "Export AAB"
4. Run the Remote Debug on Android device
5. Build fails
6. Export Project for Android
7. Build also fails

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
The main change in beta 2 is that you now require Java 17 to build the AAB. That might be what's causing the error on your end (it should complain about something "17").

But the follow-up error about not being able to remove a temporary file is an editor bug that should be looked into.

**Comment by architeer** [comment]
Yes, upgrading to Java 17 works.

One thing that I observed, whenever there is a gradle build error, the window "Building Android Project (gradle)" that shows the build logs, closes immediately, so it is very difficult to see what the exact error message is.

Maybe in the future, if this window can remain for viewing, that would be great.  Or, just have 1 main build window with all the logging inside it.  Right now, I think there are at least 2 windows that popup one after another, "Building Android Project (gradle) " and the "Project Run", etc.

Thank you for the help!

**Comment by iwangxiaodong** [comment]
@akien-mga @architeer 
Workaround: Ctrl + S can see "Building Android Project (gradle) " error output window.

**Comment by akien-mga** [comment]
Closing as the issue was a user-side configuration issue.

For the bad UX of the gradle error window, this should have been improved too in 4.2 now with #84779.
