### ISSUE TITLE
Stylebox "bleeding" outside to the bottom

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#8365]
**Operating system or device - Godot version:**
Windows 10, AMD R9 390, 3.0 master

**Issue description:**
Unifying the drawing logic of Tabs and TabContainer, I'm experiencing weird `draw` results from the tab styleboxes.

The styleboxes aren't defined in any special way. The drawing padding / 9-patch thickness is 4-4-4-0, the content padded a bit further horizontally, and the shadows 2-2-2-0:
```cpp
t->set_stylebox("tab_fg", "Tabs", sb_expand(make_stylebox(tab_current_png, 4, 4, 4, 0, 8, 4, 8, 0), 2, 2, 2, 0));
```
![image](https://cloud.githubusercontent.com/assets/9631152/24925278/054167c0-1ef8-11e7-85e7-95e295a568f7.png)

Yet the inner part of the image somehow "bleeds" to the bottom - except for the margin parts at the side, resulting in very ugly errors:
- I marked the "bleeding" part red on the "Apple" tab.
- The `Rect2` passed to `draw` is the green rectangle on the "Banana" tab.
- On the `TabContainer` with the close buttons the effect is also noticeable, the shadowy part of the tabs does not extend under the content panel, but the inner part does (which it should'nt as I draw the content panel below the end of the tab rects).

![image](https://cloud.githubusercontent.com/assets/9631152/24925140/9959ff7c-1ef7-11e7-96f9-47feb7acf5b0.png)

**Comment by toger5** [comment]
Does changing the sb_exlands to 2,2,2,1 fix it?

**Comment by RayKoopa** [comment]
No, sadly not; I tried that already. Any number for the expand margin doesn't change the outcome.

**Comment by RayKoopa** [comment]
I close this at it is the same issue as https://github.com/godotengine/godot/issues/8366
