### ISSUE TITLE
Cannot compile for Windows ARM-64 on Linux

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#83654]
### Godot version

v4.2.beta.custom_build [a574c0296]

### System information

Godot v4.2.beta (a574c0296) - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - SVGA3D; build: RELEASE;  LLVM; () - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (4 Threads)

### Issue description

I want to get the Windows ARM64 export template. To achieve this, I set-up on my Linux VM a Ubuntu Focal (20.04) arm64 schroot environment. Installed all the required packages, used [mstorsjo's llvm-mingw](https://github.com/mstorsjo/llvm-mingw/releases/tag/20231017) as the mingw implementation, and set the `MINGW_PREFIX` path accordingly. It took a long while (**4 hours!**) to compile all the files, only to then error at the linking face with this long and big wall of errors.
```
[100%] ld.lld: error: undefined symbol: Main::test_entrypoint(int, char**, bool&)
>>> referenced by platform/windows/godot_windows.windows.template_debug.arm64.o:(widechar_main(int, wchar_t**))

ld.lld: error: undefined symbol: Main::setup(char const*, int, char**, bool)
>>> referenced by platform/windows/godot_windows.windows.template_debug.arm64.o:(widechar_main(int, wchar_t**))

ld.lld: error: undefined symbol: Main::start()
>>> referenced by platform/windows/godot_windows.windows.template_debug.arm64.o:(widechar_main(int, wchar_t**))

ld.lld: error: undefined symbol: Main::cleanup(bool)
>>> referenced by platform/windows/godot_windows.windows.template_debug.arm64.o:(widechar_main(int, wchar_t**))

ld.lld: error: undefined symbol: OS::get_exit_code() const
>>> referenced by platform/windows/godot_windows.windows.template_debug.arm64.o:(widechar_main(int, wchar_t**))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(vtable for OS_Windows)

ld.lld: error: undefined symbol: ScriptDebugger::set_depth(int)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(HandlerRoutine(unsigned long))

ld.lld: error: undefined symbol: ScriptDebugger::set_lines_left(int)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(HandlerRoutine(unsigned long))

ld.lld: error: undefined symbol: String::utf16() const
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(_error_handler(void*, char const*, char const*, int, char const*, char const*, bool, ErrorHandlerType))
>>> referenced 41 more times

ld.lld: error: undefined symbol: Char16String::get_data() const
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(debug_dynamic_library_check_dependencies(String const&, String const&, HashSet<String, HashMapHasherDefault, HashMapComparatorDefault<String>>&, HashSet<String, HashMapHasherDefault, HashMapComparatorDefault<String>>&))
>>> referenced 31 more times

ld.lld: error: undefined symbol: Memory::free_static(void*, bool)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::alert(String const&, String const&))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced 696 more times

ld.lld: error: undefined symbol: add_error_handler(ErrorHandlerList*)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())

ld.lld: error: undefined symbol: NetSocketPosix::make_default()
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())

ld.lld: error: undefined symbol: operator new(unsigned long long, char const*)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced 22 more times

ld.lld: error: undefined symbol: IPUnix::make_default()
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())

ld.lld: error: undefined symbol: is_print_verbose_enabled()
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced 12 more times

ld.lld: error: undefined symbol: Variant::Variant(char const*)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::get_memory_info() const)
>>> referenced 42 more times

ld.lld: error: undefined symbol: Variant::Variant(Variant const&)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced 11 more times

ld.lld: error: undefined symbol: stringify_variants(Variant)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced 8 more times

ld.lld: error: undefined symbol: __print_line(String)
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::OS_Windows(HINSTANCE__*))
>>> referenced 8 more times

ld.lld: error: undefined symbol: FileAccessWindows::initialize()
>>> referenced by platform/windows/os_windows.windows.template_debug.arm64.o:(OS_Windows::initialize())
```
I am not sure if I'm missing something, or the llvm-mingw that I downloaded is not compatible, or something else. But I am on a lost here.

### Steps to reproduce

**How to create the environment.**

1. On Ubuntu/Debian, do: `sudo apt install schroot debootstrap`
2. Navigate and add the environment `sudo nano/vim /etc/schroot/schroot.conf`
3. In the file, there's comments with some examples already. Go to the bottom of it, add the following and save the file:
```ini
[focalarm64]
description=Ubuntu 20.04 LTS (ARM64)
directory=/srv/chroot/focalarm64
root-groups=root,sudo
type=directory
users=linuxgodot
```
**linuxgodot** is the username of my vm, switch it to *your* username.
4. Initialise the environment: `sudo debootstrap --arch=arm64 focal /srv/chroot/focalarm64 http://ports.ubuntu.com/ubuntu-ports`.
5. Enter as sudo: `sudo schroot -c focalarm64`, then install the required packages and scons.

**How I got to compile:**
1. Download the latest version of [mstorsjo's llvm-mingw](https://github.com/mstorsjo/llvm-mingw/releases/tag/20231017) and extract it (I downloaded and used `ucrt-ubuntu-20.04-aarch64`).
6. Set the `MINGW_PREFIX` to be the folder where the downloaded mingw is.
7. Land to the root of the Godot source code.
8. The command I use is: `scons -j4 platform=windows target=template_debug/template_release module_raycast_enabled=no CCFLAGS="-stdlib=libc++" LINKFLAGS="-stdlib=libc++ -lc++abi -lc++"`.

I also compiled without modifying the **CCFLAGS** or **LINKFLAGS** compile flags, but that still failed in the linking phase.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Try adding `arch=arm64` to the build command.

ARM Windows is not officially supported, there's no reason to support in for now (until DX12 renderer is merged), ARM Windows have no Vulkan drivers and OpenGL is only supported via software emulation. Some support was added, but it's not actively tested or maintained, and is mostly for MSVC builds.

**Comment by akien-mga** [comment]
For the record, if you're cross compiling to Windows ARM64 with LLVM, I don't think your host platform needs to be Linux ARM64. So you might get it compiling faster on a desktop x86_64 system (but that wouldn't solve the linking issue).

**Comment by MBCX** [comment]
@akien-mga I already tried on my host system. However I don't have (and don't know) how to get the arm libraries. So (as expected) when I try to run `clang` or `gcc`, it fails.

**Comment by MBCX** [comment]
@bruvzg I will try, but I don't think that will change much. Inside the environment, scons already detects that the architecture is arm64.

**Comment by MBCX** [comment]
All right, **got it working!**

So, when I `verbose=yes`'d the output, I noticed it was using `g++` (GCC) to do the compilation by default. So I thought if I `use_llvm=yes` and set the `linker=lld` would do the trick, and it did.

![Screenshot 2023-10-21 084635](https://github.com/godotengine/godot/assets/63003002/01722578-0b6b-48e0-9e52-bfc1483ef962)
_(Those 14 hours was because I shut down the vm before continuing.)_

I also had to use llvm and clang to get RISC-V working as well. So I guess LLVM and clang really are the **best cross-compilation tools available**.

I will close the issue then, thanks!
