### ISSUE TITLE
StyleBoxTexture expand margins not working and bleeding out to bottom

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#8366]
**Operating system or device - Godot version:**
3.0 master. Working fine in 2.2

**Issue description:**
EDIT: It seems this issue only persists on my system, as toger5 and me found out now. The following discussion was made in the stance of thinking this is a general bug or was never implemented correctly.

On my system, I have issues with `StyleBoxTexture`s: The expand margin has absolutely no effect, and style boxes bleed out to the bottom.

Have a look at the `WindowDialog` image. Remember that [the titlebar at the top and the chrome of the window expand into negative coordinates and the inner panel ("client area") of the windows starts at (0,0), to the confusion of some users](https://github.com/godotengine/godot/issues/8298).
![image](https://cloud.githubusercontent.com/assets/9631152/24930511/04c84284-1f0a-11e7-9353-c469f088225d.png)

With the margins defined in `default_theme.cpp` visualized on the image, it will look like this:
```cpp
Ref<StyleBoxTexture> style_pp_win = sb_expand(make_stylebox(popup_window_png, 10, 26, 10, 8), 8, 24, 8, 6);
```
![image](https://cloud.githubusercontent.com/assets/9631152/24930700/b4fcd4a8-1f0a-11e7-8714-a6127c930fc7.png)
- The red lines are the margin (10, 26, 10, 8) to cut out the 9-patch frames determining the stretching parts of the image, those are fine and not in question here.
- The green area is an outset (8, 24, 8, 6), mostly used for all those tiny 2-pixel shadows around tabs, buttons (god I wish we get a flat design soon 👅 ) and in this case , as said, for the whole window chrome. They're easily configurable with `sb_expand()`.

Now if I retrieve this `StyleBoxTexture` and call `sb->draw(canvas, Rect2(0, 0, 100, 100))`, you expect the areas covered by the expand margins to be drawn outside of the `Rect2`. Sadly, this is not the case on my system.

On top of that, I have a "bleeding" issue, styleboxes extend towards the bottom with no sense:
![image](https://cloud.githubusercontent.com/assets/9631152/24957208/432ea0b4-1f8b-11e7-9879-b8de1e27d096.png)

Since I have this issue since some time, I unknowingly wrote ~~idiotic~~ hilarious `WindowDialog` drawing code like this to get that done:
```cpp
Ref<StyleBox> panel = get_stylebox("panel", "WindowDialog");
int margin_left = static_cast<int>(panel->get_margin(MARGIN_LEFT));
int margin_top = static_cast<int>(panel->get_margin(MARGIN_TOP));
int margin_right = static_cast<int>(panel->get_margin(MARGIN_RIGHT));
int margin_bottom = static_cast<int>(panel->get_margin(MARGIN_BOTTOM));

Rect2 rect;
rect.pos.x = -margin_left;
rect.pos.y = -margin_top;
rect.size.width = size.width + margin_left + margin_right;
rect.size.height = size.height + margin_top + margin_bottom;

panel->draw(canvas, rect);
```
I was stupid enough to not query the expanded margin with `get_expand_margin_size` and used the wrong 9-patch margins, but that's barely noticable in the buggy Godot UI on my PC.
Anyway, what's important is that all this ridiculous code is necessary for me draw the expanded / outset stuff really outside of the `rect` given.

PS: Someone recently fuzzled around with the `Panel` content margins I believe, everything looks thinned out and ugly, on my system now. This is possibly related.

**Comment by toger5** [comment]
Hm interesting...
I played with the expands a couple of times and they definitly have an effect, work... Somehow.
Maybe they dont increase the size of the drawn area and instead decrease the size where childnelements align too...
Example: control at 0,0 size 100,100 sb_expand 10,10,10,10
Child control with margins to 0,0,0,0 anchors: left-beginnign top-beginning right-end bottom-end
Now the frame rect maybe is: 10,10 size 80,80 ?
Just a guess?

**Comment by RayKoopa** [comment]
Don't we have the content margins for that? The second set of margins passed to `make_stylebox`, which is not used in the example above. Let me draw how I understood it (wow, this starts to become one of those annoying "which CSS boxing model is the right one" discussions in the past):

- Red is the sizing margin, the first 4 numbers passed to `make_stylebox`.
- Green is the (optional) content margin, where children start to align, the second set of 4 numbers passed to `make_stylebox`. I set it to 4,4,4,4 in the example here.
- Blue is the expanded margin set with `sb_expand`.
- The dashed black line is the area passed to `draw`. Let's say it spans (0,0) to (100,100).

This is how I expect it to be: Note how the blue lines align with the dashed ones; as the expanded stuff is outside of the rectangle passed to `draw`.
![image](https://cloud.githubusercontent.com/assets/9631152/24951098/8f1c66cc-1f73-11e7-95ed-377d5d887def.png)

This is how it actually is drawn at the moment: The blue lines seem to be used for nothing, and the whole texture is squashed into the rectangle given.
![image](https://cloud.githubusercontent.com/assets/9631152/24951350/60f5e4d4-1f74-11e7-9e64-326e92ea9cd9.png)

**Comment by toger5** [comment]
Can u confirm this behaviour: 
Everything is drawn inside the rect of the control? Never exeeds the border independent of the settings for the margins?

**Comment by toger5** [comment]
How do negative epands behave ?

**Comment by RayKoopa** [comment]
Here are some further tests with a clean new stylebox:
- No margins at all. Pretty clear it's shit, just for a start.
    ```cpp
    t->set_stylebox("test", "TabContainer", sb_expand(make_stylebox(popup_window_png, 0, 0, 0, 0,  0, 0, 0, 0), 0, 0, 0, 0));
    ```
    ![image](https://cloud.githubusercontent.com/assets/9631152/24952563/271edfaa-1f78-11e7-9919-0fd0cec97339.png)
- Using sizing margins.
   ```cpp
    t->set_stylebox("test", "TabContainer", sb_expand(make_stylebox(popup_window_png, 10, 26, 10, 8,  0, 0, 0, 0), 0, 0, 0, 0));
    ```
    ![image](https://cloud.githubusercontent.com/assets/9631152/24952662/914f2ca4-1f78-11e7-9e29-a9e48e04ea0f.png)
- Adding expand margins. No change.
    ```cpp
    t->set_stylebox("test", "TabContainer", sb_expand(make_stylebox(popup_window_png, 10, 26, 10, 8,  0, 0, 0, 0), 8, 24, 8, 6));
    ```
    ![image](https://cloud.githubusercontent.com/assets/9631152/24952714/c595ace0-1f78-11e7-904f-be157fe6a23c.png)
- Negating expand margins. No effect either.
    ```cpp
    t->set_stylebox("test", "TabContainer", sb_expand(make_stylebox(popup_window_png, 10, 26, 10, 8,  0, 0, 0, 0), -8, -24, -8, -6));
    ```
    ![image](https://cloud.githubusercontent.com/assets/9631152/24952733/e76107de-1f78-11e7-9845-c9b9331c412c.png)
- Negating sizing margins. Not recommend :P
    ```cpp
    t->set_stylebox("test", "TabContainer", sb_expand(make_stylebox(popup_window_png, -10, -26, -10, -8,  0, 0, 0, 0), -8, -24, -8, -6));
    ```
    ![image](https://cloud.githubusercontent.com/assets/9631152/24952780/0d6cce86-1f79-11e7-8d6c-a4ad32bdf753.png)

**Comment by toger5** [comment]
This looks really fucked up indeed...
I did another test (just with panels):
Screen Shot 2017-04-12 at 12.32.13.png

**Comment by RayKoopa** [comment]
I'm just using the default_theme.cpp definitions and get the styleboxes in the controls, then draw them in the editor. Can it be it somehow doesn't work in the editor?
I see your expand margin having an effect. Exactly what I needed, but what doesn't happen in the editor code.

**Comment by toger5** [comment]
You mean using the in editor theme creator also does not work for u ? 
Ehich godot?

**Comment by RayKoopa** [comment]
It's the current master. The editor-side created styleboxes are bugged aswell.

**Comment by toger5** [comment]
Intersting. So we need to find the commit which introduces those issues.
I also saw a screenshot recently which had really slim borders for docks. Is this the case in the master branch at the moment. Maybe thats also cause by it?
Do you know where it worked okay?
I tried did a pr recently. Checkout that branch i thjnk it worked back than...
I dont have time for the next few days so i cant really help.

**Comment by RayKoopa** [comment]
a4a12a2b seems to have changed the `draw` method. I check on that at the moment.

**Comment by toger5** [comment]
There we go:
![capture _2017-04-12-15-07-25](https://cloud.githubusercontent.com/assets/16718859/24959109/fb4c2af8-1f91-11e7-86b7-2f0de7ec64d5.png)
Oh you were faster... (as an excuse im on my phone...)

**Comment by RayKoopa** [comment]
Yeah, I changed it to
```cpp

	Rect2 rect = p_rect;
	Rect2 src_rect = region_rect;

	texture->get_rect_region(rect, src_rect, rect, src_rect);
	rect.pos.x -= expand_margin[MARGIN_LEFT];
	rect.pos.y -= expand_margin[MARGIN_TOP];
	rect.size.x += expand_margin[MARGIN_LEFT] + expand_margin[MARGIN_RIGHT];
	rect.size.y += expand_margin[MARGIN_TOP] + expand_margin[MARGIN_BOTTOM];

	VisualServer::get_singleton()->canvas_item_add_nine_patch(p_canvas_item, rect, src_rect, texture->get_rid(),
		Vector2(margin[MARGIN_LEFT], margin[MARGIN_TOP]), Vector2(margin[MARGIN_RIGHT], margin[MARGIN_BOTTOM]),
		VS::NINE_PATCH_STRETCH, VS::NINE_PATCH_STRETCH, draw_center, modulate);
```

**Comment by toger5** [comment]
Do you know how / (or why it doesnt work)  the content margin works?
In the example screenshot i posted it has no effect and the dochmentation is also weird.

**Comment by RayKoopa** [comment]
It should make the children align further padded into the control. I'm not sure if the controls itself have to respect that. The `TabContainer` does for sure as it layouts its children.

**Comment by RayKoopa** [comment]
@akien-mga Why is this archived?

**Comment by toger5** [comment]
So it only has an effect on specific controls? Container controls...

**Comment by akien-mga** [comment]
> @akien-mga Why is this archived?

Mistake, meant to archive #8365.

**Comment by RayKoopa** [comment]
@toger5 I'm not exactly sure about that, I haven't looked into other controls detailledly yet.
