### ISSUE TITLE
Normals/Lighting error with SurfaceTool generated mesh

### ISSUE THREAD

**Issue by IndigoBeetle** [godotengine/godot#83667]
### Godot version

v4.2.beta.custom_build [f8818f85e]

### System information

macOS Ventura 13.6 M1 Forward+

### Issue description

When generating a mesh with SurfaceTool in the latest beta/master build, on macOS M1, the lighting seems to fail when the light direction passes a certain point. The images below demonstrate this. Image 1 shows the lighting/shadowing working with the directional light x angle being between -90 and -180. The second shows that the lighting seems to flip the normals when the light angle goes beyond -90, i.e. between -90 and 0. The third image shows that the lighting/normals are flipped, as the lighting and shadows are applied on the opposite side of the surface, the surface has a material with culling turned off to show both sides.

Note: changing the winding order of the two triangles in the mesh flips the behaviour, it works correctly between -90 and 0, and flips between -90 and -180, suggesting it might be something to do with face normals and vertex normals getting mixed up.

<img width="2032" alt="Screenshot 2023-10-20 at 11 39 28" src="https://github.com/godotengine/godot/assets/47725713/47126785-f54c-4dfd-bded-42213c001a19">

<img width="2032" alt="Screenshot 2023-10-20 at 11 39 35" src="https://github.com/godotengine/godot/assets/47725713/769b1a48-4699-41e2-bef0-6a3e6cbe73e9">

<img width="2032" alt="Screenshot 2023-10-20 at 11 39 40" src="https://github.com/godotengine/godot/assets/47725713/03127128-79fb-48c6-a384-01b4760db2b9">

### Steps to reproduce

Load the provided sample project and spin the directional light on the X-axis to change the direction it is facing in Z. 

Note: I've found that making changes to the script and then regenerating the mesh (it's a @tool script) doesn't usually work, it requires reloading the project for some reason.

### Minimal reproduction project

[ShadingBug.zip](https://github.com/godotengine/godot/files/13053341/ShadingBug.zip)

**Comment by IndigoBeetle** [comment]
Not sure what you mean by "dev6" I can't find a tag or branch with that name.

**Comment by AThousandShips** [comment]
[This](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-6/)

**Comment by IndigoBeetle** [comment]
Confirmed, the problem is not evident in dev6.

**Comment by clayjohn** [comment]
I made a PR that might fix this, can you test it out? https://github.com/godotengine/godot/pull/83704

**Comment by IndigoBeetle** [comment]
I've applied your PR and rebuilt, unfortunately, it has no effect on the bug, it is still showing here on my mac in the sample project attached.

**Comment by akien-mga** [comment]
Sounds related to #83236 ?

**Comment by clayjohn** [comment]
@IndigoBeetle Could you test again with Beta4? https://godotengine.org/article/dev-snapshot-godot-4-2-beta-4/ There have been a number of fixes that might help here. 

> Sounds related to https://github.com/godotengine/godot/issues/83236 ?

I don't think so. In this case the project isn't relying on tangents (or normal maps or anything like that)

**Comment by IndigoBeetle** [comment]
Unfortunately, still not working, I sure hope it's not something I'm doing
wrong. Has anyone else been able to reproduce it from the attached test
project? I'm using an M1 mac mini if that matters.

**Comment by adjourn** [comment]
I feel like this issue could share the same cause with my project. **Only tried on 4.2-beta4.**

All imported meshes are fine but meshes generated by code have very odd shading.
These are basic planes, and the shading comes from directional light. (screenshot taken from top, these are flat on ground)

Ignore the difference in shading color, it's not another bug - lighter planes have material color `#fff`, darker ones `#bbb`.

![planes](https://github.com/godotengine/godot/assets/17890701/eccefde0-abaf-4deb-b877-3e59c2619909)

Since normals are as simple as they can be and it works perfectly in 4.1.1, I can only blame 4.2.
```csharp
Vector3[] normals = new Vector3[] {
  Vector3.Up, Vector3.Up, Vector3.Up, Vector3.Up
};
```

For completeness sake, here's the rendering logic as well:
```csharp
// basically default standard material
StandardMaterial3D material = new StandardMaterial3D();
material.AlbedoColor = color;

// using rendering server directly!
Rid mesh = RenderingServer.MeshCreate();
GArray meshArrays = Meshes.GetPlaneArrays(size); // generates mesh array for plane
RenderingServer.MeshAddSurfaceFromArrays(mesh, RenderingServer.PrimitiveType.Triangles, meshArrays);
RenderingServer.MeshSurfaceSetMaterial(mesh, 0, material.GetRid());

Rid instance = RenderingServer.InstanceCreate();
// commenting out shadow casting line doesn't make a difference
RenderingServer.InstanceGeometrySetCastShadowsSetting(instance, RenderingServer.ShadowCastingSetting.Off);
RenderingServer.InstanceSetScenario(instance, Global.World3D.Scenario);
RenderingServer.InstanceSetBase(instance, mesh);
RenderingServer.InstanceSetTransform(instance, transform);
```

My apologies if it's a different issue, please let me know and I'll submit a new issue with reproduction (C#).

**Comment by testman42** [comment]
is this post of mine relevant to this issue?
https://github.com/godotengine/godot/issues/68200#issuecomment-1793433168

**Comment by Zireael07** [comment]
Highly likely that it is

**Comment by stoofin** [comment]
> Unfortunately, still not working, I sure hope it's not something I'm doing wrong. Has anyone else been able to reproduce it from the attached test project? I'm using an M1 mac mini if that matters.

I tried the example, and it looks fine for me in 4.2.beta4 on kubuntu 23.10.  The script has both manual normals and `st.generate_normals()`, and if I comment out the `st.generate_normals()` line it looks goofy but that's because the winding order is currently backwards.
> Note: I've found that making changes to the script and then regenerating the mesh (it's a @tool script) doesn't usually work, it requires reloading the project for some reason.

I think the script has a typo, it looks like this
```
func _set_regen(value : bool) -> void:
	_gen
```
when surely it should be
```
func _set_regen(value : bool) -> void:
	_gen()
```

**Comment by IndigoBeetle** [comment]
I've fixed those issues in the script, I don't believe they contributed to the problem at all, here is a video of it on my M1 mac Mini, this is with generate_normals commented out and the winding as in the original project. Changing the winding just changes which side the shadow works and doesn't, i.e. flipping the winding just makes the shadow show on the negative Z side of the cube, and not on the positive Z side in the video.


https://github.com/godotengine/godot/assets/47725713/6da1ba61-e1af-48f2-bbf4-4e5103c72569

**Comment by clayjohn** [comment]
I think I have identified the cause of this issue (https://github.com/godotengine/godot/issues/84277#issuecomment-1798277801) and unfortunately it comes from Metal (Apple's rendering API) not supporting a basic Vulkan feature that we rely on. I am going to have to add some sort of fallback for Apple devices.

**Comment by clayjohn** [comment]
I've been able to emulate the problem with Apple devices on my device, I should have a fix coming in shortly
