### ISSUE TITLE
Crash when opening GL Compatibility project on macOS Mojave since 4.2 beta 1

### ISSUE THREAD

**Issue by PaperPat** [godotengine/godot#83669]
### Godot version

4.2 beta 2

### System information

Mac OS Mojave

### Issue description

When I try to create a new project in a new folder created by Godot, Godot crash.
After relauch, the project is present, but Godot 4.2 beta 2 crash again when I try to edit it. But this project can be edited by 4.2 dev6.
(This bug existed also in 4.2 beta 1, but not in 4.2 dev6)

The invisible folder ".godot" don't have the usual files. It contains : folder "editor" (empty), folder "imported" (empty), folder "Shader" (contains folder "EGL"(empty))

### Steps to reproduce

Just create a new project

### Minimal reproduction project

Just create a new project

**Comment by akien-mga** [comment]
How do you create the project exactly? Which renderer do you select? Can you check if it works with the GL Compatibility renderer?

**Comment by PaperPat** [comment]
I use Compatibility (not Forward+ or Mobile) when I create the project (and I have try with or without Version control Metadata), and Godot Crash.
If I use Forward+, it seems to work fine, the project is created and can be edited.

**Comment by akien-mga** [comment]
CC @bruvzg @clayjohn

**Comment by PaperPat** [comment]
This problem appear after the the version Godot 4.2 beta6...

**Comment by Zireael07** [comment]
@PaperPat In this case it's likely to be related to the addition of ANGLE

**Comment by akien-mga** [comment]
Consolidating in #83269 which is the same bug.

**Comment by akien-mga** [comment]
Reopening as this may not be exactly the same situation.

**Comment by akien-mga** [comment]
@PaperPat Could you confirm if #83753 fixes the crash by testing this custom build I made after merging it?
https://downloads.tuxfamily.org/godotengine/testing/Godot_v4.2-beta_8fc215893_macos.universal.zip

**Comment by PaperPat** [comment]
Sorry it doesn’t fixe the crash. Godot when creating a new project with compatibility. The project is created but Godot Crash when I try to edit it (Test0).
The project can be converted and open with Godot 4.1 (Test1). But when I try to open this converted project with Godot 4.2 it crash.

I don’t know if it is useful for you but I send you the archive of the two steps.

**Comment by Zireael07** [comment]
Note that you can't send attachments to GH issue threads from mail, which you apparently tried to do.

**Comment by YuriSizov** [comment]
@PaperPat Your test projects would be immensely helpful, but as noted above you can't send them via email. You need to upload them from the GitHub web. Could please do that, so contributors can investigate?

**Comment by PaperPat** [comment]
The project is created but Godot Crash when I try to edit it (Test0).
The project can be converted and open with Godot 4.1 (Test1). But when I try to open this converted project with Godot 4.2 it crash. I send you the archive of the two steps.
[Test0.zip](https://github.com/godotengine/godot/files/13250517/Test0.zip)
[Test1.zip](https://github.com/godotengine/godot/files/13250519/Test1.zip)

**Comment by PaperPat** [comment]
Done, I didn’t know I could do that with gitHub… Sorry for my ignorance…

**Comment by YuriSizov** [comment]
This was potentially fixed by https://github.com/godotengine/godot/pull/84288. You can try building from the master branch to confirm, or wait for beta 5 to be out.
