### ISSUE TITLE
Exit code 255 when running "--version", "--help" commands on Godot Server build

### ISSUE THREAD

**Issue by turbohz** [godotengine/godot#83661]
### Godot version

3.6.beta3.official.21ab700f2

### System information

Linux - Godot_v3.6-beta3_linux_headless.64

### Issue description

When running the `--version` and the `--help` command, the exit code is 255 (error).

The issue seems to have been introduced in https://github.com/godotengine/godot/pull/62618, or more precisely, when cherry-picking that to the 3.5 branch (`platform/server/godot_server.cpp` was not updated as needed).

I found the issue when trying to use Godot Server as LSP server, for the vscode extension (issue https://github.com/godotengine/godot-vscode-plugin/issues/517), which prevents the server from starting.

### Steps to reproduce

Run `Godot_v3.6-beta3_linux_headless.64 --version`.

> Observe that returned exit code is `255`

### Minimal reproduction project

NA

**Comment by akien-mga** [comment]
> The issue seems to have been introduced in #62618, or more precisely, when cherry-picking that to the 3.5 branch (`platform/server/godot_server.cpp` was not updated as needed).

Makes sense. Do you want to make a PR against the `3.x` branch to fix that? (which we'd then cherry-pick to `3.5` too)

**Comment by turbohz** [comment]
> Makes sense. Do you want to make a PR against the `3.x` branch to fix that? (which we'd then cherry-pick to `3.5` too)

Sure, looks simple enough.
