### ISSUE TITLE
Make editor splash screen dark like the editor

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#8367]
**Operating system or device - Godot version:**
3.0 master

**Issue description:**
Nice idea making the splashscreen super bright-white and then the editor theme dark, keeps people awake at night 👅 

Can we somehow make it as dark as the default editor theme, at least for the editor itself? It's really eye-straining (I hate sunlight so I always program in the dark... alone... that's another story).

**Steps to reproduce:**
Use a nice dark IDE. Turn off lights. Cancel all your friendships. Eat the kitten which always shits on your doormat. Compile Godot and let it run. Congratulations, you just made an appointment with your favorite oculist.

**Comment by Hinsbart** [comment]
Slightly related: how about making the splash screen borderless, to get a more "modern" feel?
Something like this: 
![screenshot 4](https://cloud.githubusercontent.com/assets/8281916/24932804/83aa413e-1f13-11e7-9aef-4e1fd8715814.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/8281916/24932820/968a2ecc-1f13-11e7-8c7d-b0dfeecbfcba.png)
or even this :P

**Comment by RayKoopa** [comment]
What about a layered, alpha-blended window which pulsates, and a super long startup sound composed by Brian Eno? :D

**Comment by ArcFutahito** [comment]
We obviously need more osu on startup https://www.youtube.com/watch?v=mw2dm0SyjKQ

**Comment by Zylann** [comment]
Borderless... nothing more annoying than a borderless window that can't be minimized or moved, especially if it crashes xD (yes I know it's supposed to stay a few seconds only, but what if your project is HUGE)

**Comment by RayKoopa** [comment]
Yeah, I'm not a fan of borderless aswell. Also because it requires a lot of new features we don't have at the moment, I think. It's funny how the Office 2010 splash was borderless and fancy and animated, but they manually put in minimize and close buttons on it, so much extra work just for stylistic choices. :D

**Comment by Noshyaar** [comment]
Fixed by #12080, unless you want light splash for light theme. :P
