### ISSUE TITLE
Update gamepad remapping system to reflect changes in SDL code.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8368]
**Operating system or device - Godot version:**
All

**Issue description:**
It seems like SDL2 has been updated and now has the ability to map only half of a gamepad axis.
https://hg.libsdl.org/SDL/rev/5ea5f198879f

While I haven't found any mappings in the wild using this feature yet, we should implement it in order to keep compatibility. Also it's a very useful feature imho :)

**Comment by salvob41** [comment]
As found out by @bruvzg in https://github.com/godotengine/godot/issues/26544#issuecomment-471161904 SDL mapping from 2.0.4 (presumably) onwards are not correctly imported in Godot - in the generated `main\default_controller_mappings.gen.cpp` there are a few lines with a generic error like this:
> // WARNING - DISCARDED UNSUPPORTED MAPPING TYPE FROM DATABASE .../gamecontrollerdb.txt: Mac OS X 030000008f0e00000300000009010000,2In1 USB Joystick,+leftx:h0.2,+lefty:h0.4,-leftx:h0.8,-lefty:h0.1,a:b2,b:b1,back:b8,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b3,y:b0,platform:Mac OS X,

Can we make `Input.add_joy_mapping()` returning an error if the mapping is not correctly added and maybe update the SDL changes ?

**Comment by salvob41** [comment]
I could do it if someone give me a heads up on where to focus in order to fix this.

**Comment by samdze** [comment]
Could this be cherry picked if resolved?

**Comment by salvob41** [comment]
@samdze was it? I don't think so

**Comment by akien-mga** [comment]
> Could this be cherry picked if resolved?

Yes, but we need to have it fixed first :)

**Comment by salvob41** [comment]
Back on this.
I would like to help out on this. 

But I need guidance. What should we do? How?

**Comment by Anutrix** [comment]
Any updates?

**Comment by salvob41** [comment]
https://www.youtube.com/watch?v=bWcASV2sey0
