### ISSUE TITLE
Selecting Nodes Improvement

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#837]
Since often nodes are layered or overlapping it may be hard to select the wanted node.
Blender offers a great solution for such things, by shift + clicking on an object which results in a dropdown list of all object names that are behind the mouse cursor. This makes selecting the objects much easier and especially if there are many object this is a great solution.

**Comment by akien-mga** [comment]
That would be very cool.

**Comment by neikeq** [comment]
I could do a PR about this issue if no one is yet assigned. Just wondering, what should be the input combination with Maya or Modo navigation scheme?

**Comment by akien-mga** [comment]
Fixed by #2786.
