### ISSUE TITLE
Material Not Rendering Correctly in Compatibility Renderer

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#83710]
### Godot version

v4.1.2stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21902.5) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

In this project, it works fine in the mobile renderer but in the compatibility renderer, it makes everything black. When I tested with the web, the meshes wouldn't even show up. This may be my fault, but if that is the case, please explain to me how to fix it.

### Steps to reproduce

Just use the repro project.

### Minimal reproduction project

https://drive.google.com/file/d/1LSF4byKlwcHCaxfhn0cVW5RIEKBE1w8S/view?usp=sharing

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74111, as this is fixed in 4.2.beta2. I tested the MRP locally to confirm this:

![image](https://github.com/godotengine/godot/assets/180032/525a83e0-a703-4dc1-8259-9b0c7ae367ba)
