### ISSUE TITLE
Cannot compile GDExtension when editor is on.

### ISSUE THREAD

**Issue by StellarH** [godotengine/godot#83711]
### Godot version

4.1.2.stable

### System information

Godot v4.1.2.stable - Windows 10.0.19041 - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 6800HS Creator Edition (16 Threads)

### Issue description

When editor is on, the share library of GDExtension is occupied. I cannot compile the share library unless I close the editor.

### Steps to reproduce

When editor is on, just compile the GDExtension.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Looks like a duplicate of:
* #66231

Which is solved in 4.2

**Comment by StellarH** [comment]
I have just tried `4.2.beta2`, the problem has been solved. Thanks.
But I still hope it can be fixed in 4.1 or earlier versions.

**Comment by AThousandShips** [comment]
Probably won't as this is a major enhancement that is unlikely to get cherry picked, not just a bug fix

**Comment by StellarH** [comment]
In that case, I think the issue should be closed.
