### ISSUE TITLE
Can not call existing function

### ISSUE THREAD

**Issue by funny-cat-happy** [godotengine/godot#83716]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 30.0.15.1289) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When my custon plugin call the the node's function of edit scene, it throws the error nonexistent function 'generate_tile' in base 'TileMap'.But the node has the function.With or without the tool keyword.

### Steps to reproduce

1. create a plugin
2. create a script inherit from EditorPlugin
3. write a new dock and bind a function to button like this
```
@tool
extends EditorPlugin

const editorAddon = preload("res://addons/MapGenerateEditor/MapEditor.tscn")

var dockedscene
@export var num: int = 1


func _enter_tree():
	dockedscene = editorAddon.instantiate()
	add_control_to_dock(DOCK_SLOT_RIGHT_UL, dockedscene)
	dockedscene.get_node("./Button1").pressed.connect(self.test)


func _exit_tree():
	remove_control_from_docks(dockedscene)
	dockedscene.free()


func test():
	var t = get_editor_interface().get_edited_scene_root()
	print(t.get_node("./TileMaps").has_method("generate_tile"))
	t.get_node("./TileMaps").generate_tile()
	# t.get_node("./TileMaps").set_cell(0, Vector2i(1, 0), 0, Vector2i(0, 0), 0) the code execute normally
```
4. create a new scene and add a tilemap node.
5. create a script to it and add any function.
6. click the button that just creates.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/13060313/project.zip)

**Comment by AThousandShips** [comment]
You cannot call a non-`@tool` method from a `@tool` method, the fact that `has_method` returns true doesn't really depend on that I'd say, and not sure it should

**Comment by funny-cat-happy** [comment]
> You cannot call a non-`@tool` method from a `@tool` method, the fact that `has_method` returns true doesn't really depend on that I'd say, and not sure it should

In Issue description, I write with or without the tool keyword.It still happens.

**Comment by KoBeWi** [comment]
The attached project works correctly for me, so not sure what's the problem?
As for the error, it's expected if you don't use `@tool`: #43853

**Comment by funny-cat-happy** [comment]
> The attached project works correctly for me, so not sure what's the problem? As for the error, it's expected if you don't use `@tool`: #43853

After I test many times, I find if the project's script itself has the tool keyword, then the plugin can access the method whether you remove it or keep it. If the open project doesn't have the tool keyword, then it won't help if you add it. Unless you reload the project.
```
@tool
extends TileMap


func _enter_tree():
	print(randi())
	# set_cell(get_layer_id_by_name("ground"), Vector2i(0, 0), 0, Vector2i(0, 0), 0)
	# set_cell(get_layer_id_by_name("ground"), Vector2i(0, 1), 0, Vector2i(0, 0), 0)
	# set_cell(get_layer_id_by_name("ground"), Vector2i(0, 2), 0, Vector2i(0, 0), 0)


func get_layer_id_by_name(name_to_find: String) -> int:
	var layer_id = -1
	for i in range(get_layers_count()):
		if get_layer_name(i) == name_to_find:
			layer_id = i
			break
	return layer_id


func generate_tile():
	print("generate_tile")
	set_cell(get_layer_id_by_name("ground"), Vector2i(0, 0), 0, Vector2i(0, 0), 0)
```

**Comment by KoBeWi** [comment]
Tool scripts are colored differently in the script editor (regular scripts have white icon). Normally you don't need to restart the editor for them to get enabled, though reloading the scene might be necessary.

**Comment by funny-cat-happy** [comment]
> Tool scripts are colored differently in the script editor (regular scripts have white icon). Normally you don't need to restart the editor for them to get enabled, though reloading the scene might be necessary.

yes, you are right.When I click reload saved scene menu, it runs normally.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/36592.
