### ISSUE TITLE
[4.1.2] godotsharp_internal_reload_registered_script throws when C# script methods contain GodotObject or subtype arguments

### ISSUE THREAD

**Issue by MihaMarkic** [godotengine/godot#83722]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Using .NET 7.0.
When a C# script method is using `GodotObject` or subclass as an argument, `Godot.NativeInterop.godotsharp_internal_reload_registered_script` throws when loading scene using `ResourceLoader.Load<T>`:

> 
> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
>    at Godot.Bridge.ScriptManagerBridge.GetMethodListForType(Type type) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 789
> 
>   This exception was originally thrown at this call stack:
> 
> Inner Exception 1:
> MissingMethodException: Method not found: 'Void Godot.Bridge.PropertyInfo..ctor(Type, Godot.StringName, Godot.PropertyHint, System.String, Godot.PropertyUsageFlags, Godot.StringName, Boolean)'.

Albeit the game will run if exception is ignored, there are subtle problems, like signals not firing upon EmitSignal.
I'd say this bug is a nasty hidden one.

### Steps to reproduce

Create a scene, link C# script, put a method into script, i.e. `void Test(GodotObject e) { }` and try loading it using `ResourceLoader.Load<MyCustom>("res://my_custom.tscn")` from within Visual Studio (make sure you catch all exceptions of "Common Language Runtime".). 

### Minimal reproduction project

[Repro.zip](https://github.com/godotengine/godot/files/13060680/TestInheritance.zip)

**Comment by MihaMarkic** [comment]
Looks like the problem happens on Windows but not on MacOS. .NET runtime is the same on both, while SDK is 7.0.402 (Windows) and 7.0.309 (Mac). Godot is 4.1.2 on both.

**Comment by raulsntos** [comment]
The exception `MissingMethodException` is usually thrown when a library breaks binary compatibility. In this case, it seems a `PropertyInfo` constructor is missing. Try removing the `.godot` folder and rebuild the project, and also if you are using any libraries that use the Godot packages make sure they are rebuilt against the same version of Godot.

**Comment by MihaMarkic** [comment]
@raulsntos Interesting, I think that could be the explanation. I've tried it (my sample) on another Windows machine and there it works fine as well. I guess there is something with the original Windows machine going on. I'll investigate more this weekend, but I guess the installation indeed is the issue.

**Comment by MihaMarkic** [comment]
That was indeed the case - project referenced some older assemblies.
