### ISSUE TITLE
 color picker doesn't display colors properly

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8372]
**Operating system or device - Godot version:** Linux, 3.0master

**Issue description:**
The color picker used in the inspector (and probably other places) is not showing the color selection rectangle.

Besides that, the hue selection (vertical bar) seems to have a different offset than the real color being selected. One of them appears to be the inverted value of the other.

**Comment by Shockblast** [comment]
It happens to me the same in windows, when I change the "color" (modulate?) of the sprites for example.

**Comment by alex9099** [comment]
Same here just a empty square with no colors, when clicking in that square the color is picked but there is no color on the square
![image](https://cloud.githubusercontent.com/assets/7517045/24974808/6bce08ae-1fbb-11e7-972e-c4ec8ded4a1f.png)

**Comment by avril-gh** [comment]
same as @alex9099 
tested under windows 7 32 bit

**Comment by eon-s** [comment]
All the time since the first buildable godot 3, also the invisible part of the color picker seems to be inverted respecting to the right bar (like, pink is yellow and yellow is pink).

**Comment by Gibbz** [comment]
yep same issue here for the color picker

**Comment by MarianoGnu** [comment]
This should fix ColorPicker and Polygon2D for now, but i believe some more fixes will be needed for other nodes like CollisionPolygon wich is not drawing neighter.

**Comment by remorse107** [comment]
The palette to the right is flipped upside down.  Not a big deal as the mouse coordinate logic is just a simple flip and all is good.

But the Polygon2D doesn't seem to work in Godot 3 at the moment.  Which is okay, because I ran the Polygon2D code in Godot 2 where it is working and the palette picker does not look good at all.

I have it nearly corrected, but I think that a fragment shader is the better solution to this versus a Polygon2D.

![capture](https://user-images.githubusercontent.com/7462993/27160529-91f4de1c-513a-11e7-972d-faa79f128f10.PNG)

**Comment by toger5** [comment]
@remorse107 pull the newest master. the draw polygon got finally fixed today

**Comment by remorse107** [comment]
Okay.  I pulled from the Master, and now it looks really good.  I guess I'll make a push request which I've never done before.

![capture](https://user-images.githubusercontent.com/7462993/27163516-80baa97a-514d-11e7-8f3a-9cd7b3aa85f8.PNG)

**Comment by MarianoGnu** [comment]
reduz recently fixed _draw_polygon function, wich was in charge of drawing the color picker, i did a fix long ago to replace shaders for polygons

**Comment by remorse107** [comment]
The polygon works great now.  There was still a couple of bugs related to
the color array bring sent to draw polygon and the reverse direction of the
how selection texture.

I made a push request that corrected toge items.

**Comment by akien-mga** [comment]
Fixed by #9192.
