### ISSUE TITLE
Raycast ignores RigidBody's children when colliding with bodies

### ISSUE THREAD

**Issue by Xstyler85** [godotengine/godot#83732]
### Godot version

4.1.1

### System information

WIndows 11

### Issue description

I have a rigid body with multiple child nodes - each od them has mash and collider.
I am using a raycast to detect a child inside that rigid body.
But, it only detects the rigid body (parent) and ignores its children.
I tried to change raycast collision mask and children’s collision layer, but it didn’t work - it works if I set “Collide with: Areas”, but it doesn’t work on “Collide with: Bodies”. I think that is a bug.

### Steps to reproduce

1. Open attached project 
2. Run the game and nothing will be printed in the console (children ignored)
3. On player raycast switch "Collide with: Bodies" to "Collide with: Areas"
4. Run the game and child area name with be printed (children not ignored)

### Minimal reproduction project

[CollisionIssue.zip](https://github.com/godotengine/godot/files/13060962/CollisionIssue.zip)

**Comment by AThousandShips** [comment]
Collision object only work when directly under a body, are you not getting a warning in the editor?

**Comment by AThousandShips** [comment]
This is not a bug but the way the code works currently, there is a proposal for changing this:
* https://github.com/godotengine/godot-proposals/issues/535

**Comment by Xstyler85** [comment]
This is not a problem, collider is directly under the RigidBody3D. The issue is that raycast is not detecting it, but can only detect Areas.

**Comment by AThousandShips** [comment]
Does it work if you change `collision_layer` of the RigidBody to `1`? Or change the `collision_mask` of the ray cast to `2`?

**Comment by AThousandShips** [comment]
After updating the layers to be correct it works fine for me

**Comment by Xstyler85** [comment]
I tried differant combinations. If they metch like you wrote the RigidBody is detected.
But, I'm trying to detect it's children (Child1, Child2). If I match Raycast mask with children layers it still doesn't work.

**Comment by AThousandShips** [comment]
What children layers? The detection is the body, not the collision shapes.

**Comment by AThousandShips** [comment]
The specifics here could be documented more clearly, but there's no bug here

**Comment by Xstyler85** [comment]
Ok thank you! The code you provided is working, so it's not a bug. I didn't know that CollisionShape3D is not recognized as a body. Can I add any other node inside the RigidBody that will be recognized as a body?

**Comment by AThousandShips** [comment]
You can, but it kind of defeats the purpose, you are colliding with bodies, will make a documentation update to help with this.

**Comment by Xstyler85** [comment]
So, for example if I'm shooting RigidBody3D car and I want to know that I hit the "door", not just a "car" I have to use your 3 lines of code and there is no other simpler way? Sorry I'm coming from Unity3D, maybe I'm thinking too much from the Unity user prespective :)

**Comment by AThousandShips** [comment]
That's the simple way :)

**Comment by AThousandShips** [comment]
You can open a [proposal](https://github.com/godotengine/godot-proposals) if one isn't opened already to suggest adding this method to `RayCast2D/3D` as a convenience

**Comment by AThousandShips** [comment]
Correction, the full code is:
```gdscript
var target = raycast.get_collider()
var shape_id = raycast.get_collider_shape()
var owner_id = target.shape_find_owner(shape_id)
var shape = target.shape_owner_get_owner(owner_id)
```
largely the same I believe, but to be fully clear

**Comment by Xstyler85** [comment]
Great, thank you again for your time and all the help!
I apologize for misunderstanding and reporting it as a bug.

**Comment by AThousandShips** [comment]
No worries! It brought to attention the limited documentation
