### ISSUE TITLE
Tilemap navigation cell_size with two navigation layers is unchangable

### ISSUE THREAD

**Issue by lolomap** [godotengine/godot#83739]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon(TM) RX Vega 10 Graphics (Advanced Micro Devices, Inc.; 31.0.14057.2005) - AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

I'm not sure if it is a bug or unclear behaviour but it seams strange. When several navigation layers are used in 2D,  wrong cell_size error appears despite NavigationServer2D.map_set_cell_size or Project Settings Default cell size values. If you check cell_size using NavigationServer2D.map_get_cell_size, you can see that cell_size is constantly 0.25 for both layers.
The text of an error:
```
E 0:00:00:0571   update_polygons: Navigation map synchronization error. Attempted to update a navigation region with a navigation mesh that uses a 'cell_size' of 0.25 while assigned to a navigation map set to a 'cell_size' of 1. The cell size for navigation maps can be changed by using the NavigationServer map_set_cell_size() function. The cell size for default navigation maps can also be changed in the ProjectSettings.
  <C++ Source>   modules/navigation/nav_region.cpp:118 @ update_polygons()
```
Also, the value in the error is changed depending on the default value or map_set_cell_size but only if it is not equal to one. If it should be one, you will see 0.25 in the text error.

### Steps to reproduce

1. Place Tilemap to your scene and create second layer for it
2. Configure Tileset for Tilemap with two navigation layers
3. Set some tiles from Tileset to first navigation layer and some others to second
4. Draw tiles assigned to first navigation layer on first tilemap layer
5. Draw tiles assigned to second navigation layer on second tilemap layer
6. Now you should see the error after scene run
7. Attach a script to Tilemap:

```gdscript
extends TileMap


func _ready():
	NavigationServer2D.map_set_cell_size(get_navigation_map(0), 1.0)
	NavigationServer2D.map_set_cell_size(get_navigation_map(1), 1.0)
	print(NavigationServer2D.map_get_cell_size(get_navigation_map(0)))
	print(NavigationServer2D.map_get_cell_size(get_navigation_map(1)))
```
8. Now you should see that cell_size was not changed. Play with different values in map_set_cell_size and Profect Settings default navigation cell size

### Minimal reproduction project

[TestGodot.zip](https://github.com/godotengine/godot/files/13061281/TestGodot.zip)

**Comment by smix8** [comment]
Thanks for reporting.

I think this was recently fixed with https://github.com/godotengine/godot/pull/83568 in master as it has the same bug source.
At least on master with the test project there is no error. So closing as an already solved duplicate.
