### ISSUE TITLE
Polygon2D's texture disappears after associated bone2d is deleted

### ISSUE THREAD

**Issue by qbqjtx** [godotengine/godot#83754]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 home 10.0.19045 Build 19045

### Issue description

`Polygon2D`'s texture disappears after the associated `bone2d` is deleted.

In the said `Polygon2D` node's inspector, the Texture is still set to the same image. In the `UV editor`, the texture is also visible with all the points and polygons, with weight painted on them. But in the main **_2D editor_** screen, the texture is absent (or invisible?).

### Steps to reproduce

1. a simple set up
    - create new project
    - create a simple tree scene structure as shown in the zip file.
    - what I did in creation: create new project > create root Node2D > create `polygon_folder` and `polygon2D` > create `Skeleton2D`, `Bone2D` and `Bone2D` as child and grandchild.
    - import the texture png to `polygon2D`
    - open UV editor, in `points` sub tab, draw the points.
    - move bones to proper position and overwrite `resting` pose.
    - set `polygon2D`'s `Skeleton` to `Skeleton2D`
    - open `UV` editor > `bones` > `sync bones` on the right, and start to pain weight.
    - move the bone around the verify the connection is established.
   
2. the bug
    - Everything should work fine so far. The procedure above is basically connecting `bone` and `skeleton` to a `polygon2d` and make sure they work.
    - Now to reproduce what I encountered, just delete the `bone`s. And `polygon2D`'s texture visually disappeared in the editor, but its polygon remains, and its painted weights remains.
    - But I'm unable to modify the polygon2D because I can't see it in the **_regular_** editor for animation, while I am still able to see the texture and modify the polygons in the UV editor.

### Minimal reproduction project

[reproducing bug.zip](https://github.com/godotengine/godot/files/13061833/reproducing.bug.zip)
 
I'm providing this barebone project just in case my steps aren't clear enough.

All you need to do after opening the project is to delete the `bone`s, and you will see the `polygon2d`'s texture disappear visually.

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by qbqjtx** [comment]
> For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels _first_ to see if this is a bug or user error.

It was indeed a well-written bug report until I figured out it wasn’t a bug. I didn’t ask for advice. I removed it to save people’s time since there doesn’t seem to be a way to completely delete it.

also. I can’t change title it seems.

**Comment by AThousandShips** [comment]
That's not what I meant, I meant as I said: "Please use other channels first to see if this is a bug or user error.", nowhere did I say this was for advice, I only commented this because you said sorry for making a mistake, so directed you for the future :)

**Comment by qbqjtx** [comment]
I see. Thanks.
