### ISSUE TITLE
how can i change msbuild path

### ISSUE THREAD

**Issue by gintering1000** [godotengine/godot#83755]
### Godot version

4.1.2.stable.mono

### System information

Apple M2 Max Somona 14.0(23A339)

### Issue description

**i use asdf for dotnet**
![image](https://github.com/godotengine/godot/assets/77244047/08e9f06a-9931-49ac-8556-ceb73796902b)

**dotnet is all installed**
![image](https://github.com/godotengine/godot/assets/77244047/28be8723-86d2-4058-913d-bff6fa53cfb2)

**but godot dont know about this dotnet**
![image](https://github.com/godotengine/godot/assets/77244047/0a450e51-67b1-43e1-89d3-970b9a268e05)

### Steps to reproduce

**install asdf and dotnet plugin**
- brew install asdf
- asdf plugin add dotnet
- append text .zshrc file > . ~/.asdf/plugins/dotnet/set-dotnet-env.zsh
  ( https://github.com/hensou/asdf-dotnet )

**install dotnet with asdf**
- asdf list all dotnet
- asdf install dotnet 7.0.402
- asdf global dotnet 7.0.402
- (go to godot project directory)
- asdf local dotnet 7.0.402 ( check .tool-version file )
- check installed > dotnet --info
- check installed > echo $MSBuildSDKsPath

### Minimal reproduction project

when i make project and open, error is showing.

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk.
