### ISSUE TITLE
Samsung phone will get unreadable code in game bug others are ok

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#83766]
### Godot version

4.1.2

### System information

Windows11, GLES3

### Issue description

I create a mobile game with no localization settings. 
But some people who use Samsung phone will encounter unreadable code, all text are unreadable. 
Other phones are totally ok.
So, I have no idea about it. 
Can any one give me some advice? 
Thank you so much!!!
<img width="877" alt="Snipaste_2023-10-22_12-53-32" src="https://github.com/godotengine/godot/assets/37371850/b34025fb-ce0f-4e3d-9233-0cf386696d8f">

### Steps to reproduce

1. use some texts with Chinese or some other unicode characters e
2. Export android to apk
3. use Samsung Zfold5 or Samsung s23 open it
4. the text will unreadable

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
You might be relying on system fonts, and Samsung's OS may not provide the ones that Godot tries to use for Chinese text. CC @bruvzg 

You should be able to work it around by actually configuring a font with support for these characters in your project.

**Comment by bruvzg** [comment]
It's likely system fonts. Android system font lookup is quite unreliable and vendor/OS version dependent. There's no official API for it, so Godot is trying to parse config files instead.

**Comment by SmallKi** [comment]
Thanks for all your guys, you saved my life
