### ISSUE TITLE
Adding the AudioStreamPlayer into the paused tree will let the music play

### ISSUE THREAD

**Issue by Wesmer** [godotengine/godot#83775]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 1050 (NVIDIA; 30.0.14.7111) - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 Threads)

### Issue description

If you play music and then pause the tree, the music stops. But if you then remove the node (in this case the parent, of the AudioStreamPlayer) and insert it again after a certain time, the music starts to play even though the tree is still paused.

When the tree is paused, the music should not start by itself.

### Steps to reproduce

- Start Music
- Pause Tree
- Remove Node (parent of AudioStreamPlayer)
- Add Node again
- (Music starts)

### Minimal reproduction project

[sound.zip](https://github.com/godotengine/godot/files/13063218/sound.zip)

(Please note that I did not provide a sound file.)

**Comment by KoBeWi** [comment]
Seems the same as #49153, but the issue was specific to Godot 3 🤔

**Comment by AThousandShips** [comment]
Will take a look at this, think I know what's going on
