### ISSUE TITLE
Use Snap inverts when saving scene with Ctrl+S in 3D Editor.

### ISSUE THREAD

**Issue by Skywolf285** [godotengine/godot#83777]
### Godot version

Godot_v4.2-beta2_linux.x86_64

### System information

Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 535.113.01) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When saving a scene using the CTRL+S shortcut (using the menu is unaffected) the transform snapping feature inverts. The button itself in the toolbar remains in the same state however making it "out of sync" with the snapping behavior. This seems to only happen in the 3D Editor.

Once inverted it stays this way even across other scenes. Pressing "Y" to toggle snapping does temporarily fix it until CTRL+S is used again. Using CTRL+S again without first pressing "Y" doesn't invert it make to normal.

![Godot Save Snap Issue](https://github.com/godotengine/godot/assets/49045791/dacc025e-8f77-4191-9a5a-4912bb5eae02)

### Steps to reproduce

1. Open a new or existing scene and make sure there is a Node3D (or a node that inherits from this) in it.
2. Save the scene using CTRL+S
3. Select the Node3D and move it a bit.
4. Save the scene again using CTRL+S 
5. Move the Node3D again.

### Minimal reproduction project

Any scene with a Node3D or a node that inherits from this is affected. Don't feel like this needs a MRP.

**Comment by AThousandShips** [comment]
Have you changed the shortcut for snap? It defaults to `Y`

**Comment by astillich** [comment]
I can confirm this on 4.1.2, with a default setup. So it's not a changed shortcut. I'll probably look into this tomorrow, because it has been annoying me since shortly after I started dabbling with Godot.

**Comment by Voidraizer** [comment]
This is still an issue. Is there any workaround anyone is aware of in the mean time?

**Comment by Calinou** [comment]
This has been a longstanding issue – I remember encountering it in Godot 3.x already. My guess is that the EditorProgress dialog that shows up when you press <kbd>Ctrl + S</kbd> intercepts the <kbd>Ctrl</kbd> key release, so the 3D editor viewport never "sees" the key being released.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/59687.
