### ISSUE TITLE
Signals are often unreliable and need to be connected manually through code

### ISSUE THREAD

**Issue by michelcastilho** [godotengine/godot#83784]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.18362 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.2824) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 Threads)

### Issue description

I've created a timer, set it to Autostart, connected its Timeout signal to my script through the Node tab, and it wouldn't ever trigger.

![image](https://github.com/godotengine/godot/assets/40428897/cd613d0e-ceb9-4608-9cb7-75110803416c)
![image](https://github.com/godotengine/godot/assets/40428897/9e80081d-fa9c-42db-9421-9990baaa54f0)
![image](https://github.com/godotengine/godot/assets/40428897/4ea4cbfb-fe01-482a-8b57-eeb01a5879b1)

I've used breakpoints and prints and I'm sure it was never triggered.

I've redone the connection, still nothing. Deleted the whole thing and did it again, nothing.

Then I connected the signal manually through code and it worked.

.TSCN file shows it like this, with no signal whatsoever:

![image](https://github.com/godotengine/godot/assets/40428897/579a9125-84ce-4ea1-a573-71b50b23d1af)

But as you can see from previous screenshots, the UI shows it as if it was connected, despite the .TSCN file having absolutely no signal information.

But there were other times where I've set it up exactly the same and it worked, so it's really unreliable for whatever reason.

### Steps to reproduce

Create a timer, set it to Autostart, connect its Timeout signal to a script through the Node tab, see if it triggers. In my experience, sometimes it doesn't.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
> But as you can see from previous screenshots, the UI shows it as if it was connected, despite the .TSCN file having absolutely no signal information.

That doesn't really show that, signal connections are at the very bottom of the file, not next to the node
