### ISSUE TITLE
Feature Request: Change default path on project manager

### ISSUE THREAD

**Issue by alex9099** [godotengine/godot#8378]
It would be better if the default path when searching for projects or creating new ones was the home dir (linux and mac: /home/<user> Windows: c:/Users/<user> [not sure about windows and mac])

In linux (at least) the default path is the path where godot binary is

**Comment by Zylann** [comment]
Are you searching for this?
![image](https://cloud.githubusercontent.com/assets/1311555/24971894/6bcee094-1fb1-11e7-9f1e-62e5fb45c380.png)

It was asked and answered on QA as well:
https://godotengine.org/qa/13994/new-project-location?show=13994#q13994
https://godotengine.org/qa/13157/create-project-always-applications-godot-contents-resources?show=13157#q13157

**Comment by alex9099** [comment]
Yea, that's it, thanks :)

Closing

**Comment by reduz** [comment]
In 3.0 the settings are much better organized

**Comment by alex9099** [comment]
Yea, on 3.0 they are under Editor Settings-> Filesystem -> Directories

BTW, i think that there should be a button to get into the editor settings on the project manager
