### ISSUE TITLE
Unique Names are not being hinted in the code editor when using %

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#83794]
### Godot version

4.2 beta 1

### System information

MacOS 11.7.4

### Issue description

If I set a node to "Access as Unique Name" and write % in the script editor I will not be given any suggestions of nodes with unique names. If I write $, I will get a list of all the node paths I can access in the scene tree.

**Expected behavior**
I expect the same behavior as with $ but typing % would give me suggestions of all the Unique Names I have access to in the scene tree to choose from. 

### Steps to reproduce

Set a node to "Access as Unique Name" and write % in the script editor.

### Minimal reproduction project

-

**Comment by KoBeWi** [comment]
This is a missing feature: https://github.com/godotengine/godot-proposals/issues/4593
