### ISSUE TITLE
Evaluate Expression shortcut is no longer working in 4.2 and also breaks the script editor

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#83795]
### Godot version

Godot v4.2.beta2 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.beta2 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Evaluate Expression in the script editor is no longer working in latest 4.2. It's still working from the context menu, but not when I do Ctrl+Shift+E.

Not only this, but it breaks the script editor and you can only navigate through it after that, like it's read-only.

### Steps to reproduce

Type `PI/2` in the script editor and do `Ctrl+Shift+E`.

Expectation: `1.57`

Reality: "(2) Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead."

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Can't reproduce in beta3.

**Comment by MewPurPur** [comment]
I can still reproduce this in beta3.

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot/assets/2223172/999d8711-8334-4d28-b1a4-1f9ed077ce65

Then maybe it requires some extra steps?

**Comment by MewPurPur** [comment]
It's exactly as I described and I can reproduce it consistently in every project. Maybe my machine has something to do with this?

**Comment by akien-mga** [comment]
I also can't reproduce on Linux (Mageia 9, KDE on X11, using default editor settings).

Could you test with default editor settings / in self-contained mode, to see if that's caused by an editor setting?

**Comment by MewPurPur** [comment]
I didn't do that, but I think I dug up what might have been the cause: https://askubuntu.com/questions/1083913/what-does-ctrl-shift-e-do-while-typing-text

I don't get the errors I mentioned in my original post, and I don't get easily locked out, and the underlined "e" appears as described in the linked post, though the functionality doesn't work as described.

When in this state, I can still find ways to lock myself out of the code editor, although again, not as easily as before. A lot of the same issues also happen when I press Ctrl+Shift+U.

Example of a softlock:

- Ctrl+Shift+U for entering a unicode.
- Right click somewhere.

**Comment by KoBeWi** [comment]
It doesn't look like Godot issue and thus could be closed. Just rebind the shortcut I guess.
It could've been resolved earlier if you'd test some earlier version 🙃(to rule out a regression)

**Comment by MewPurPur** [comment]
I don't think so, the softlock still exists, but the source is not what I thought it was.

**Comment by KoBeWi** [comment]
Right, but is it something we can fix, or it's another one of these magic Linux shortcuts that break everything (like the Alt+drag)?

**Comment by MewPurPur** [comment]
Seems like my initial report was two separate bugs: Godot not behaving properly for Ctrl+Shift+E (fixed in the meantime it looks like), and the editor breaking when you make certain actions while there's a special character (still not fixed).

The unfixed one I don't think can slide, I don't even think Ctrl+Shift+U is Linux-only.

**Comment by MewPurPur** [comment]
I'll test if this is now fixed.

**Comment by MewPurPur** [comment]
Ctrl+Shift+E now behaves in a way that's much closer to expected, but this issue still exists:

- Press Ctrl+Shift+E (or Ctrl+Shift+U for entering a unicode)
- Right-click somewhere in the code editor.
- Your inputs are now swallowed and you can't write code.

I'm closing this and opening a separate issue for that.

**Comment by MewPurPur** [comment]
https://github.com/godotengine/godot/issues/97035
