### ISSUE TITLE
Some times can't add node in visualshader editor

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#83805]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10, 64bit

### Issue description

Some times can't add node in visualshader editor

### Steps to reproduce

1. Open a VisualShader file for edit.
2. Click the `Add Node...` button, it will popup menu, it is OK.
3. Direct close the menu.
4. Clikd the `Add Node...` again, the menu can't popup.
![GIF](https://github.com/godotengine/godot/assets/35988767/1326c63e-3e05-4423-9ec7-7ce305b3f4f5)

### Minimal reproduction project

/

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.beta f8818f85e (Linux). I've tried both single-window mode enabled and disabled.

**Comment by CsloudX** [comment]
Oh, I'm found it, the menu was in backgound.
![GIF](https://github.com/godotengine/godot/assets/35988767/760aadf4-c8e4-4c97-97cf-b4c30c13a5fe)

**Comment by CsloudX** [comment]
> How are you closing the Add Node window? Are you pressing Escape or clicking outside? Clicking outside doesn't close the window for me.

clicking outside

**Comment by LiorArbel** [comment]
Happened to me too now, pretty confusing, if you started adding a node and then didn't add one, it would make sense to either automatically close the small window when you change the window back to Godot\another program, or to bring this window back to focus if you click add node and it's already open.

**Comment by jsjtxietian** [comment]
> Oh, I'm found it, the menu was in backgound. ![GIF](https://user-images.githubusercontent.com/35988767/277203374-760aadf4-c8e4-4c97-97cf-b4c30c13a5fe.gif) [ ![GIF](https://user-images.githubusercontent.com/35988767/277203374-760aadf4-c8e4-4c97-97cf-b4c30c13a5fe.gif) ](https://user-images.githubusercontent.com/35988767/277203374-760aadf4-c8e4-4c97-97cf-b4c30c13a5fe.gif) [ ](https://user-images.githubusercontent.com/35988767/277203374-760aadf4-c8e4-4c97-97cf-b4c30c13a5fe.gif)

Same for me, my pr fixes the problem, you can help test :)

**Comment by Zylann** [comment]
The same fate seems to have occurred for my graph editor, which uses a similar popup. What happened to the "click outside to close" behavior?
I can set my dialog to exclusive too I guess, just a bit more annoying to aim for the close button.

I also noticed in some circumstances that this popup can now get stuck unresponsive, eventually blocking the whole editor as a result (so far resolving with alt/tab). I haven't found the pattern to make it happen though, but had it occur a few times.
