### ISSUE TITLE
Exporting project to Windows

### ISSUE THREAD

**Issue by ElYaiko** [godotengine/godot#83807]
### Godot version

4.2.beta

### System information

MacOS 14 M1

### Issue description

When exporting to Windows I get (Failed) and in console:

ERROR: Failed to open
godot/modules/text_server_adv/gdextension_build/bin/libtextserver_advanced.windows.template_release.x86_64.dll
   at: copy (core/io/dir_access.cpp:346)

It seems to the file doesn't exist, but I have not idea if is necessary to be built and how
I use Godot compiled from source on MacOS 14 M1****

### Steps to reproduce

I build from source Godot and the templates for Windows and Mac but it seems some modules were not built.

### Minimal reproduction project

-

**Comment by Calinou** [comment]
Does this occur when you export an empty project, or only on a specific project?

> I build from source Godot and the templates for Windows and Mac but it seems some modules were not built.

TextServerAdvanced is a built-in module that is statically linked in the engine binary, and it's enabled by default. You can choose to build it as a GDExtension but this isn't required by default.

**Comment by ElYaiko** [comment]
> Does this occur when you export an empty project, or only on a specific project?
> 
> > I build from source Godot and the templates for Windows and Mac but it seems some modules were not built.
> 
> TextServerAdvanced is a built-in module that is statically linked in the engine binary, and it's enabled by default. You can choose to build it as a GDExtension but this isn't required by default.

Yes, only happens with a specific project for windows only.
I see, but the dll were not generated in the build, or do I have to compile Godot for Windows too?

**Comment by ElYaiko** [comment]
I fixed it, I had cloned the repo in the res:// and for some reason it was being included in the export, (half day trying to fix this 🤦‍♂️)
