### ISSUE TITLE
Setting up a zoomed-out minimap is surprisingly difficult

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8380]
Tested on Godot 2.1.2

I tried to make a simple example on how to make a minimap that shows a zoomed-out view of the world.
The split-screen example shows the required setup, which works well for split-screen.
However setting up a minimap using this technique is harder because:

It requires two active cameras to live under the same player node. Only one of them can be made current: clicking on both will disable the other one, and vice versa. Not sure how it affects the result, but it's a bit confusing in that situation.

Viewports also don't seem to bother about the project's stretch mode, because when I resize the window the field of view changes instead of stretching and staying centered on the player.

The minimap camera in fact does work, but due to the above, it also renders starting from its virtual top-left corner at 1:1 scale, clamping the rest. As a result, the tiny rectangle shows nothing, or a small part of the background. How can I make it so the center of what the camera sees matches the center of its viewport, and stretch the height to fit while keeping aspect?
Did this change in 3.0?

Project:
[ViewportZoom.zip](https://github.com/godotengine/godot/files/917824/ViewportZoom.zip)

(I also reproduced https://github.com/godotengine/godot/issues/1840 on the way, but fix is for 3.0)

**Comment by eon-s** [comment]
You can put the minimap camera on the second (third?) viewport and attach it with a remote transform to move it (also remove the second part of the main node script), camera and zoom works fine but is still messy and stretch options only affect the main viewport, it seems .

ViewportSprite don't work for the minimap? (not easy to set up either)

**Comment by eon-s** [comment]
Tried and I think it looks better with ViewportSprite (is not too different but less mess with camera bugs on the editor), also stretch mode on viewport seems to work fine for both.

Here is the example modified to use the sprite:
[ViewportZoomVPSPrite.zip](https://github.com/godotengine/godot/files/918199/ViewportZoomVPSPrite.zip)

----------------------------

If the viewports were able to get other viewports worlds as a property or a subclass for viewport that depends on other viewports (a subviewport?), could make all this just matter of set up the scene correctly and no extra scripting involved.

**Comment by kubecz3k** [comment]
Sorry guys, closing this one since there was no discussion here for a year now.
