### ISSUE TITLE
Jump Variable Got Bigger as window did 2d

### ISSUE THREAD

**Issue by TheOddDucky** [godotengine/godot#83808]
### Godot version

4.1 stable

### System information

mac os

### Issue description

There Was A 2d character that i got to jump by changing the velocity.y by a variable called jump_height.When i scaled the window the height he jumped increased but the variable stayed the same.

### Steps to reproduce

write code

### Minimal reproduction project

![Untitled](https://github.com/godotengine/godot/assets/148730100/f6a7ae3d-0a3b-43ce-bcee-08f4d407ebdb)
 this is just a blank text file as a png

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

This is likely a scripting error, or a misunderstanding of the stretch mode project settings (`canvas_items`/`viewport` makes everything appear larger if you resize the window to a larger size than the base viewport size).
