### ISSUE TITLE
Godot 3, Creating a particles node leads to console error spam

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#8381]
**Operating system or device - Godot version:**
Win10 64 bit; Ivy Bridge i7 CPU; ATI 77xx GPU with 2017 Crimson ReLive drivers

**Issue description:**
I add a particles node to an empty scene using a Godot 3 build, adding the required material and mesh instance does nothing (ie. no particles are produced like in the .gif images in the news feed) while the console spams error messages at a torrid pace (only stopping if I delete the node or disable its visibility).

**Steps to reproduce:**
Fire up an empty project in Godot 3 and add a particles node, the errors should already start to flow. Try anything, but don't expect anything to work. There's at least 3 unique errors when you delete the node and check the console.

**Link to minimal example project:**
Not needed, it should be fairly easy to do from scratch.

**Comment by Gibbz** [comment]
Yep, same, I cant get particles working no matter which settings I play with. Nothing at all draws...

**Comment by bojidar-bg** [comment]
Can confirm here with a Intel Integrated GPU (using master as of yesterday).

**Comment by alexzheng** [comment]
I also got console error spam, but not by a particle, the error did not stop even I close the running scene.
Godot version 2.1.3

**Comment by akien-mga** [comment]
Fixed by #8388.
