### ISSUE TITLE
InputEventGesture events branch dont working

### ISSUE THREAD

**Issue by KeiMuriKoe** [godotengine/godot#83813]
### Godot version

4.2 beta 2

### System information

Mobile, Compability, Vulkan, Android

### Issue description

All input events in Gesture branch dont working. 
InputEventGesture
InputEventMagnifyGesture 
InputEventPanGesture

this inputs doesnt emitet at all, i use my pixel 7 pro, even emulators, many vers of exports, etc...

(but only android)

### Steps to reproduce

func _input(event):
	if event is InputEventMagnifyGesture:
		$Label.text = event.get_factor()
	if event is InputEventPanGesture:
		$Label2.text = event.get_delta()
	if event is InputEventGesture:
		$Label3.text = str(event)
		
		
I used a lot variants of this code, and tested it.

### Minimal reproduction project

func _input(event):
	if event is InputEventMagnifyGesture:
		$Label.text = event.get_factor()
	if event is InputEventPanGesture:
		$Label2.text = event.get_delta()
	if event is InputEventGesture:
		$Label3.text = str(event)

**Comment by Calinou** [comment]
This is expected, as these classes are currently only implemented on macOS: https://github.com/godotengine/godot/issues/13139
