### ISSUE TITLE
Exported project is too heavy

### ISSUE THREAD

**Issue by ElYaiko** [godotengine/godot#83817]
### Godot version

4.2.beta

### System information

MacOS 14 M1

### Issue description

I have a small game for testing with Godot, and edited and downloaded all the resources in the res:// folder, so they were being imported.

Now I discovered Godot imports automatically all the files in the project, even if they're not used, now when exporting the game is almost 3gb where 90% of the files are not in the game, so I decided to move and delete the unused files but then I noticed there is a 'imported' folder too where Godot re saves the files in its format, now basically I don't know where to start to reduce the game's size since there are a lot of files in the imported folder, I think Godot should improve this system, for now I can only go file by file and delete the unused file so is not included in the PCK, it would be useful too a tool to list unused files or to remove them.

I hope this system can get improved so exported games are not very heavy.
Thanks!.

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by atirut-w** [comment]
Programmatically determining if an asset is "used" can be very complex. There are a lot of cases to check for:

- Is the asset referenced by any script?
- Is the asset referenced by any scene?

And that's just the tip of the iceberg. There's dependency checking, edge cases, etc. that can complicate things even more very quickly.

Unity combats this by having you specify scenes to include in a build and continuing from there, but it also has its own downsides.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/17733.
