### ISSUE TITLE
In 4.2 GPUParticles3D using Directed Points emission shape doesn't affect particle initial direction

### ISSUE THREAD

**Issue by jamesdkay** [godotengine/godot#83811]
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Godot v4.2.beta2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

When using GPUParticles3D the Directed Points emission shape doesn't seem to work, it just does the same thing that Points does. Using "Create Emission Points from Node" you can create an emission points texture and emission normal texture. The emission points texture works; the particles are emitted from the surface of the mesh. The emission normal texture doesn't seem to work though. The particles are just emitted in the direction set under velocity/direction. You can just clear the emission normal texture and nothing if affected.

### Steps to reproduce

New 3D scene.

Create MeshInstance3D and give it a mesh.

Create particles and give it a Draw pass. Give it a ParticleProcessMaterial and give the particles an initial velocity. Use "Create Emission Points from Node" and choose Surface Points + Normal (Directed) to create a Emission Points Texture and Emission Normal Texture.

Maybe I'm doing something wrong here, but I have been unable to find any combination of settings that causes the particles initial direction to be anything but the one set under Spawn>Velocity>Direction

### Minimal reproduction project

[particle emission normal test.zip](https://github.com/godotengine/godot/files/13065353/particle.emission.normal.test.zip)

**Comment by Calinou** [comment]
cc @QbieShay
