### ISSUE TITLE
Array slice behaviour difference 4.1 vs 3.5.3

### ISSUE THREAD

**Issue by gejza74** [godotengine/godot#83820]
### Godot version

3.5.3 4.1.2

### System information

Godot v4.2.dev4 - Debian GNU/Linux 12 (bookworm) 12 - Tty - Vulkan (Mobile) - integrated Intel(R) HD Graphics 4000 (IVB GT2) () - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 Threads)

### Issue description

Array slice behaviour is changed from version 3 to 4.

### Steps to reproduce

This code generates another result on version 4.x:
var testAry = [1, 2, 3, 4, 5]
var res = testAry.slice(0, 1)
On version 3.x the res is: [1, 2]
On version 4.x the res is: [1]

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment]
The change of behavior is expected, see #35901.

Documentation also described that the second parameter is exclusive in 4.x (it's described as inclusive in 3.x).

**Comment by dalexeev** [comment]
Worth mentioning [here](https://docs.godotengine.org/en/latest/tutorials/migrating/upgrading_to_godot_4.html#updating-scripts-to-take-backwards-incompatible-changes-into-account).

**Comment by gejza74** [comment]
Thank you!
