### ISSUE TITLE
Viewports don't want to render with a greater resolution than the window size.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8383]
**Operating system or device - Godot version:**
Linux, 2.1

**Issue description:**
I've set up a project with a window size of 1024x720 and a viewport with size 1920x1080. I display it using a ViewportSprite, it doesn't render correctly.

**Link to minimal example project:**
[viewport_platformer3D.zip](https://github.com/godotengine/godot/files/918811/viewport_platformer3D.zip)

**Comment by BastiaanOlij** [comment]
@Hinsbart I think I found it. 

In RasterizerGLES2::set_viewport it bottom aligns the viewport with the window size:
glViewport(viewport.x, window_size.height - (viewport.height + viewport.y), viewport.width, viewport.height);

I guess that makes sense for viewports that are on screen but not for render buffers. I think that might be what the current_rt pointer check is for... I'm going to try something out.

**Comment by reduz** [comment]
This is unfixable in 2.1… but works fine in 3.0

**Comment by BastiaanOlij** [comment]
@reduz whats causing it? it doesn't make sense to me, you create the render buffer at the correct size. There is no reason why you couldn't render at that resolution?

**Comment by kubecz3k** [comment]
According to @reduz comment it's solved now in 3.0
