### ISSUE TITLE
Can't open editor

### ISSUE THREAD

**Issue by Dynieczek** [godotengine/godot#83836]
### Godot version

4.0 stable

### System information

processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz   2.71 GHz, RAM: 8GB, x64

### Issue description

Whenever i click "Create And Edit" while creating a project, or click "Edit" in the local projects, the Godot app just closes and the editor doesn't open.

### Steps to reproduce

1. Create a project
2. Click "Create and Edit" or "Edit"

### Minimal reproduction project

I can't even open a project

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.0.4 or 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by jojorne** [comment]
- Download the [Godot_v4.2-beta2_win64.exe.zip](https://github.com/godotengine/godot-builds/releases/download/4.2-beta2/Godot_v4.2-beta2_win64.exe.zip)
- Right click the file and `Extract All...`
- Open the extracted folder
- Create a new file with the name `_sc_` or `._sc_`
- Run the `Godot_v4.2-beta2_win64_console.exe`

**Comment by Dynieczek** [comment]
> * Download the [Godot_v4.2-beta2_win64.exe.zip](https://github.com/godotengine/godot-builds/releases/download/4.2-beta2/Godot_v4.2-beta2_win64.exe.zip)
> * Right click the file and `Extract All...`
> * Open the extracted folder
> * Create a new file with the name `_sc_` or `._sc_`
> * Run the `Godot_v4.2-beta2_win64_console.exe`
> * Check `Compatibility` on the `Renderer` panel

Where is the renderer panel?

**Comment by jojorne** [comment]
![image](https://github.com/godotengine/godot/assets/18329136/38689201-93f8-43f9-9b47-5b94f8109a37)

**Comment by Dynieczek** [comment]
> ![image](https://user-images.githubusercontent.com/18329136/277358620-38689201-93f8-43f9-9b47-5b94f8109a37.png)

Thank you so much!
