### ISSUE TITLE
ResourceUID doesn't use `z` and `9`

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#83843]
### Godot version

c21c2706ad33c59295f6a3ac1e128db6fa7cce69

### System information

n/a

### Issue description

These lines have an off-by-one error:

https://github.com/godotengine/godot/blob/master/core/io/resource_uid.cpp#L38-L39

No big deal, but it makes encoded RIDs potentially longer than they need to be.

If fixing the bug would cause trouble reading older files, then at least it should be commented.

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

**Comment by Mickeon** [comment]
This is probably reading too deep into the semantics, but why is this not classified as a bug? It all works fine, but it clearly is not what the author intended. I'm aware it should not be fixed anytime soon, is that why?

**Comment by AThousandShips** [comment]
It's not really a bug that something is minorly inefficient, when said behaviour works with no issues, and changing it is destructive, nothing is broken

**Comment by akien-mga** [comment]
As discussed, changing this would break compatibility for a gain that's minimal aside from fixing a harmless off by one error.

We could consider doing that change for 5.0, but that release isn't planned for the time being, and even then we'd want to ensure we can still handle UIDs from 4.x project that get migrated to 5.0. So it's likely we might not fix this at all.

Next time one of us tweaks ResourceUID, we could add a comment pointing out the mistake, in case we figure out a good way to do this change without breaking projects in the future.
