### ISSUE TITLE
XR Preview on Quest 2 not working with any rendering backend

### ISSUE THREAD

**Issue by ikonnow** [godotengine/godot#83852]
### Godot version

Godot v4.2.beta2

### System information

Godot v4.2.beta2 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4584) - AMD Ryzen Threadripper 1950X 16-Core Processor (32 Threads)

### Issue description

I'm trying to use XR preview in Godot 4.2 beta 2 on my Oculus Quest 2, but it's not working at all - Forward+ / Mobile / Compatibility. 
I've noticed a similar issue with the first beta (see #83555 )

Again the exact same project works fine, converting it with 4.2.1

Console message:
--- Debugging process stopped ---

### Steps to reproduce

Open the project "godot-xr-tools-demo", make sure the headset is connected, click preview.

### Minimal reproduction project

"N/A"

**Comment by AThousandShips** [comment]
What is the difference between this and #83555?

**Comment by ikonnow** [comment]
> What is the difference between this and #83555?
In the first beta1 (mentioned in #83555 XR preview works with "Compatibility" in the new beta2 (this issue) not at all. Of course you could say the missing Vulkan rendering applies to both.

**Comment by akien-mga** [comment]
> Again the exact same project works fine, converting it with 4.2.1

Do you mean 4.1.2, or 4.2-beta1?

**Comment by ikonnow** [comment]
> > Again the exact same project works fine, converting it with 4.2.1
> 
> Do you mean 4.1.2, or 4.2-beta1?
> 
Yes 4.1.2. the current stable version. here all rendering modes work perfectly fine.
> Also to be clear, are you running on Quest as a native Android app, or are you using PC VR via Quest Link?
Yes, i did not try to export a android app yet. The Quest is connected via Quest Link (Cable).

**Comment by ikonnow** [comment]
Thank you for the adapted title. The new title doesn't quite reflect what I originally meant by the issue and now narrows it down to Compatibility. Actually, it is neither Compatibility, nor Forward+, nor Mobile. But this seems probably not expected :).

I understand from the renaming of my issue that there will be no update for Vulkan based preview with OpenXR? I am a bit worried because my project had already moved to beta1. Plus, without Vulkan, there is no way to extend the visuals with the Environment Settings. Are there any tips and tricks? - Once again thank you!

**Comment by akien-mga** [comment]
Well we established above that https://github.com/godotengine/godot/issues/83555 already covers the fact that XR preview doesn't seem to work for Vulkan, so it seems this bug finds that it's now also not working with OpenGL?

Anyway, if it's PC VR, this is likely a duplicate of #83674 which should be fixed in 4.2 beta 3. Could you confirm?

**Comment by ikonnow** [comment]
> Well we established above that https://github.com/godotengine/godot/issues/83555 already covers the fact that XR preview doesn't seem to work for Vulkan, so it seems this bug finds that it's now also not working with OpenGL?
> 
> Anyway, if it's PC VR, this is likely a duplicate of #83674 which should be fixed in 4.2 beta 3. Could you confirm?

Yes absolutely, thanks for pointing me to this issue though. I'd love to see the 4.2 beta3 containing a fix for sure! It's hard to see all those rendering improvements passing by... from XR perspective. Thanks for your help and keep up the good work!

**Comment by akien-mga** [comment]
4.2 beta 3 was released yesterday: https://godotengine.org/article/dev-snapshot-godot-4-2-beta-3/

Could you test and confirm if that solves this issue?

**Comment by ikonnow** [comment]
OK, I just tested 4.2.3beta3 in the exact same process with PC VR / Oculus Link - in all 3 rendering modes, I can confirm that the issue has been resolved. The fix is awesome! Thank you so much for your help and support throughout this process. I really appreciate it.
