### ISSUE TITLE
When setting a CanvasTexture for TileMap, there will be lighting errors

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot#83874]
### Godot version

4.2.beta2

### System information

WIn 11 

### Issue description

The problem does not exist in Beta1
Using ImageTexture can get normal results

https://github.com/godotengine/godot/assets/52212525/fe5fed08-e1f5-4e21-bcb0-74295366897f

The lights will only show half
The problem does not exist on Sprite2D

### Steps to reproduce

pass

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/13111238/bug.zip)

**Comment by AThousandShips** [comment]
Seems to come from:
* #83489

CC @groud

**Comment by groud** [comment]
> Seems to come from: https://github.com/godotengine/godot/pull/83489

It was not possible to use CanvasTexture in TileSets before at all, so it's not really this change that caused the issue. So it's not a regression either.

@Az-qianchen have you tried disabling "Use texture padding" ? Do you see any difference ?

**Comment by AThousandShips** [comment]
My bad, the issue title made it sound like it *made* it a CanvasTexture causing bugs, instead of that it happens when someone assigned one, updated the title

**Comment by Az-qianchen** [comment]
> have you tried disabling "Use texture padding" ? Do you see any difference ?

After the change, I got the right result
