### ISSUE TITLE
TileSetAtlasSource X and Y coordinates seem swapped in the editor tooltip

### ISSUE THREAD

**Issue by MatthiasBae** [godotengine/godot#83877]
### Godot version

4.1.1 stable

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.4584) - 13th Gen Intel(R) Core(TM) i9-13900KF (32 Threads)

### Issue description

I want to get the PeeringBit Data from my Tiles in the TileSet so I call the method "GetTileData" from the TileSetAtlasSource.

For example the method "GetTileId" returns Coordinates X:0 and Y:1 and I use them in the method "GetTileData", I get the tile data for Coordinates X:1 and Y:0. It seems it swapped X and Y.

I put a minimal reproducing code in the "Steps to reproduce" chapter.

**My TileSet**
<img width="1328" alt="image" src="https://github.com/godotengine/godot/assets/52577744/b98653ea-2037-4004-8431-88ee6519528f">

**As you can see i try to get atlas coordinate X:0 Y:1 and the terrain peering bit data is for tile X:1 Y:0**
<img width="881" alt="TileSetAtlasSource_1" src="https://github.com/godotengine/godot/assets/52577744/3aa48638-fe5e-4c89-bdb2-9205fef544fb">

**My exact code**
```
public static int[,] GetTerrainMask(TileData tileData) {
        
        var terrainMask = new int[3, 3];
        if (tileData == null) {
            return terrainMask;
        }
        
        for(var x = 0; x < 3; x++) {
            for(var y = 0; y < 3; y++) {
                var cellNeighborCoordinates = new Vector2I(x - 1, y - 1);

                if(cellNeighborCoordinates is {X:0, Y: 0}) {
                    terrainMask[x, y] = tileData.Terrain;
                    continue;
                }
                
                var cellNeighbor = CoordinatesToCellNeighbor(cellNeighborCoordinates);
                var neighbor = tileData.GetTerrainPeeringBit(cellNeighbor);
                
                terrainMask[x, y] = neighbor;
            }
        }
        return terrainMask;
    }

// it uses the offset of the center tile expecting the center is X:0 Y:0
public static TileSet.CellNeighbor CoordinatesToCellNeighbor(Vector2I coordinates) {
        return coordinates switch {
            { X: -1, Y: 0 } => TileSet.CellNeighbor.LeftSide,
            { X: 1, Y: 0 } => TileSet.CellNeighbor.RightSide,
            { X: 0, Y: -1 } => TileSet.CellNeighbor.TopSide,
            { X: 0, Y: 1 } => TileSet.CellNeighbor.BottomSide,
            { X: -1, Y: -1 } => TileSet.CellNeighbor.TopLeftCorner,
            { X: 1, Y: -1 } => TileSet.CellNeighbor.TopRightCorner,
            { X: -1, Y: 1 } => TileSet.CellNeighbor.BottomLeftCorner,
            { X: 1, Y: 1 } => TileSet.CellNeighbor.BottomRightCorner,
            _ => 0
        };
    }
```

### Steps to reproduce

Execute the Code I attached to check

```
public void GetTileBinaryMappings(TileMap tileMap) {

        var tileSet = tileMap.TileSet;
        var tileSetSourceCount = tileSet.GetSourceCount();
        for(var i = 0; i < tileSetSourceCount; i++) {
            var source = (TileSetAtlasSource)tileSet.GetSource(i);
            var tileCount = source.GetTilesCount();
            
            for (var j = 0; j < tileCount; j++) {
                var tileCoordinates = source.GetTileId(j);
                var tileData = source.GetTileData(tileCoordinates, 0);
// You can call the GetTerrainMask method in here from the Issue Description
                GD.Print($"Koordinate: {tileCoordinates}  Tile Data: {tileData}");
            }
        }
}
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by MatthiasBae** [comment]
> Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

I close the issue as I found out that I was wrong :) It was too early in the morning

**Comment by MatthiasBae** [comment]
I found out what caused my confusion and why I thought it would return me the wrong tiledata.

The methods works correct but in the inspector the atlas coordinates are swapped

This should be usually atlas coordinate X:0 Y:2 but (which it is when I call it via script) but is shows wrong in the tileset inspector

<img width="638" alt="image" src="https://github.com/godotengine/godot/assets/52577744/5490c720-5645-430b-bacd-90e34a44df07">

**Comment by MatthiasBae** [comment]
@AThousandShips for your info

**Comment by akien-mga** [comment]
CC @KoBeWi @groud

**Comment by MatthiasBae** [comment]
Sorry for all the confusion I caused but there is also something wrong when I call the TileAtlasSource.GetTileId() method so I think my initial thought is also true. It seems like the TileSetAtlasSource uses a completely different coordinate system like they swapped X and Y in general.

It really confused me but I think I got it now.

The following Code:
```
public static void GetTileBinaryMappings(TileMap tileMap) {
        var mappings = new Dictionary<int, SmartTilingAtlasMapping[]>();
        var tileSet = tileMap.TileSet;
        var tileSetSourceCount = tileSet.GetSourceCount();
        for(var i = 0; i < tileSetSourceCount; i++) {
            var source = (TileSetAtlasSource)tileSet.GetSource(i);
            var tileCount = source.GetTilesCount();
            GD.Print("--------------------");
            for (var j = 0; j < tileCount; j++) {
                var tileCoordinates = source.GetTileId(j);
                
                GD.Print($"Coordinate {tileCoordinates}");
            }
        }
        return mappings;
    }
```

produces me the following output:

```
Coordinate (0, 0)
Coordinate (0, 1)
Coordinate (0, 2)
Coordinate (0, 3)
Coordinate (1, 0)
Coordinate (1, 1)
Coordinate (1, 2)
Coordinate (1, 3)
Coordinate (2, 0)
Coordinate (2, 1)
Coordinate (2, 2)
Coordinate (2, 3)
Coordinate (3, 0)
Coordinate (3, 1)
Coordinate (3, 2)
Coordinate (3, 3)
Coordinate (5, 0)
Coordinate (5, 1)
Coordinate (5, 2)
Coordinate (5, 3)
Coordinate (6, 0)
Coordinate (6, 1)
Coordinate (6, 2)
Coordinate (6, 3)
Coordinate (7, 0)
Coordinate (7, 1)
Coordinate (7, 2)
Coordinate (7, 3)
Coordinate (8, 0)
Coordinate (8, 1)
Coordinate (8, 2)
Coordinate (8, 3)
Coordinate (10, 0)
Coordinate (10, 1)
Coordinate (10, 2)
Coordinate (10, 3)
Coordinate (11, 3)
Coordinate (12, 0)
Coordinate (12, 1)
Coordinate (12, 3)
Coordinate (13, 3)
Coordinate (14, 0)
Coordinate (14, 1)
Coordinate (14, 3)
Coordinate (15, 0)
Coordinate (15, 1)
Coordinate (15, 3)
```

So the output says the X coordinate in the Vector2I would be 15. Which is wrong as I do not have 15 rows. **I have 15 columns**

**Comment by groud** [comment]
> I think my initial thought is also true. It seems like the TileSetAtlasSource uses a completely different coordinate system like they swapped X and Y in general.

No, that is not the case. The coordinate system should be the same.

> the output says the X coordinate in the Vector2I would be 15. Which is wrong as I do not have 15 rows. I have 15 columns

The first coordinate is the column number (X coordinate), so that looks good to me.

**Comment by MatthiasBae** [comment]
> > I think my initial thought is also true. It seems like the TileSetAtlasSource uses a completely different coordinate system like they swapped X and Y in general.
> 
> No, that is not the case. The coordinate system should be the same.
> 
> > the output says the X coordinate in the Vector2I would be 15. Which is wrong as I do not have 15 rows. I have 15 columns
> 
> The first coordinate is the column number (X coordinate), so that looks good to me.

Yes if you use the default coordinate system like in the world / scene it is fine but I do not think it makes sense to use this coordinate system in a tileset because the TileSet is more like an 2D Array. So it would make more sense (in my opinion) to use the "array system" where a row = X and column = Y

**Comment by groud** [comment]
> Thats what caused my confusion. I always had like an array in my mind and not the world coordinate system.

Well, I mean, it's called "atlas coordinates". So I don't think swapping them would be good. That's also the same coordinate system we use to index pixels in an image. So I don't think it's very confusing TBH.

It's not clear to me what the issue is, is there a problem with the engine or is it just that you wrongly assumed the coordinates would be the other way around? If it's the second option, then this discussion about swapping the coordinates should be moved to a proposal, and we should remove the bug label from this issue. Otherwise, I'd like to have a minimal reproduction project so that I can understand what is wrong.

**Comment by MatthiasBae** [comment]
> > Thats what caused my confusion. I always had like an array in my mind and not the world coordinate system.
> 
> Well, I mean, it's called "atlas coordinates". So I don't think swapping them would be good. That's also the same coordinate system we use to index pixels in an image. So I don't think it's very confusing TBH.
> 
> It's not clear to me what the issue is, is there a problem with the engine or is it just that you wrongly assumed the coordinates would be the other way around? If it's the second option, then this discussion about swapping the coordinates should be moved to a proposal, and we should remove the bug label from this issue. Otherwise, I'd like to have a minimal reproduction project so that I can understand what is wrong.

It is just the second option but I think that is nothing which needs a proposal because it seems to be the default coordinate system so there is no reason to change it and I was just wrong with my expected behaviour :)
