### ISSUE TITLE
GraphNode's slot_index start from 1?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#83879]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10, 64bit

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/05c7f171-9ecf-46e7-88dd-49e8ae33c76f)

I'm add to slots:
first was enable left and disable right, so I think the slot_index should 0 but it is 1.
second was disable left and enable right, so I think the slot_index should 1 but it is 2.
I'm not sure is this a bug or is I'm used a error way?

### Steps to reproduce

/

### Minimal reproduction project

[GraphNodeTest2.zip](https://github.com/godotengine/godot/files/13111916/GraphNodeTest2.zip)

**Comment by AThousandShips** [comment]
You're on an outdated beta version, can you please try this with a supported version like 4.1.2 (you're on a beta version of 4.1.0)

**Comment by CsloudX** [comment]
> You're on an outdated beta version, can you please try this with a supported version like 4.1.2 (you're on a beta version of 4.1.0)

Sorry, I'm write a wrong version. I'm updated,  it should be 4.2 beta2

**Comment by akien-mga** [comment]
CC @Geometror @YuriSizov

**Comment by AThousandShips** [comment]
The index is that of the child control, including internal nodes, so might be a child that's not a control, or some internal node (not on my computer so can't check the MRP), was looking at the code from 4.1 but couldn't find any cause but since this was the wrong version that looks related

**Comment by YuriSizov** [comment]
There is indeed an inconsistency. It is true that the slot index refers, basically, to the child index of the owning control. However, whereas the index passed to `set_slot`, and other related methods, is considered with the exclusion of internal nodes (such as the `GraphNode`'s titlebar), the index that we return from `get_input/output_port_slot` includes internal nodes.

Basically, in `slot_table` we index slots by sans-internal index, and in the port cache we index slots by their with-internal index. Even if we need those values like that for some reason, what we return to users should be consistent with what users pass when setting up slots.

@Geometror Could you take a look and confirm?
