### ISSUE TITLE
Typed array function arguments don't accept typed arrays of subclass

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#83876]
### Godot version

4.2beta2

### System information

macOS 13.6.0

### Issue description

Function arguments using a typed array specify a base class, but called with a typed array of a sub class, for example:

```
func function(objects:Array[BaseClass]):
	pass

func _ready() -> void:
	var objects:Array[SubClass]
	function(objects)
```

Results in the following error: 
`Error Line 10:Invalid argument for "function()" function: argument 1 should be "Array[BaseClass]" but is "Array[SubClass]".`
Indicating the array needs to be the exact same class, even though SubClass extends BaseClass. I'd expect it to also accept subclasses, just like if you specify single variable arguments with classes:

```
func function(object:BaseClass):
	pass

func _ready() -> void:
	var object:SubClass
	function(object)
```
This works as expected, no error.

### Steps to reproduce

Create two classes:
```
class_name BaseClass
extends Object
...
```
and 
```
class_name SubClass
extends BaseClass
...
```

Then try the code above with a function argument set as a typed array for BaseClass. 

### Minimal reproduction project

The code above is hopefully enough and I don't think this relates to anything project specific as it seems to be an issue with validating typed array function arguments.

**Comment by dalexeev** [comment]
[GDScript reference - Typed arrays](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays):

![](https://github.com/godotengine/godot/assets/47700418/f75cea69-5544-40df-b111-f798cdb32901)

**Comment by lostminds** [comment]
I see, so this is more of a limitation of the current typed array implementation than a bug. 

Is this something that is on some list to improve in the future, or should I open a proposal to support using subclass typed arrays like in the example above?

**Comment by dalexeev** [comment]
This is not a bug. Arrays are passed by reference; they do not copy the entire content. Otherwise you would get:

```gdscript
var a: Array[Node2D]
var b: Array[Node]
b = a # Now `b` refers to the same array as `a`.
b.append(Label.new()) # Valid, `Label` is a subtype of `Node`.
print(a[0]) # Invalid, `Label` is **not** a subtype of `Node2D`.
```

Probably the only way this would work is if the GDScript supported [`read`/`write` qualifiers](https://github.com/godotengine/godot-proposals/discussions/7364#discussioncomment-6576975). But it's too difficult.

**Comment by lostminds** [comment]
Ah, I see, thank you for explaining. I guess what I'm missing is a way to define that function array arguments should be arrays with subclasses of a certain class, but I see now that this would introduce a lot of issues.
