### ISSUE TITLE
Plus Button Not Appearing In Scene Tree

### ISSUE THREAD

**Issue by TheOddDucky** [godotengine/godot#83871]
### Godot version

4.1

### System information

macOS Monterey

### Issue description

The Plus Button Doesn't Appear At All

### Steps to reproduce

I Don't Know What To Write Here

### Minimal reproduction project

![Screen Shot 2023-10-23 at 7 36 48 PM](https://github.com/godotengine/godot/assets/148730100/fcc235ce-bc31-40ce-8e60-b91793ed41d2)

**Comment by timothyqiu** [comment]
Does it occur in 4.1.2 and 4.2 betas?

**Comment by AThousandShips** [comment]
Indeed, can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by TheOddDucky** [comment]
I Tested It on 4.1.2 and it showed up
