### ISSUE TITLE
Reparenting an AnimationPlayer node to a higher node results in track information getting lost

### ISSUE THREAD

**Issue by gomaproi** [godotengine/godot#83908]
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Windows 10.0.23570 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21029.1006) - AMD Ryzen 5 4600G with Radeon Graphics (12 Threads)

### Issue description

When reparenting an AnimationPlayer node in the editor to a higher node, property tracks (unsure if the same happens in other track types) that was added to it will lose their information (including property name and keys, but not key positions). Can be undone with Ctrl+Z, but not by placing it back after changing parents.

https://github.com/godotengine/godot/assets/28575885/fec1726a-2068-4726-b330-689dc4f0042b

### Steps to reproduce

1. Create a new scene with a Node2D root;
2. Add a child Node2D to the **root**;
3. Add a child AnimationPlayer to the **child Node2D**;
4. Create a new animation in the AnimationPlayer node with any name;
5. Add a property track, pick the child Node2D and select any property (example: the modulate property);
6. Create a key in the newly created property track;
7. Reparent AnimationPlayer to the root Node2D;

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Probably regression from #83209
Animation paths are getting updated by scene tree dock., which ignores subpaths
