### ISSUE TITLE
Game doesn't load on Android, it only keep blinking on splash screen. 

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#8391]
**Operating system or device - Godot version:**
Fedora release 25 (Twenty Five)
Godot v2.1.3.stable.official

**Issue description:**
Game doesn't load on Android, it only keep blinking on splash screen. 
It works fine on editor. 
Same project loaded from v2.1.2.stable.oficial works fine.

**Steps to reproduce:**
1. Make a simple project with one scene and one script.
2. Try to run it on Android.

**Adb logcat output:**

```bash
ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
At: modules/gdscript/gd_script.cpp:720.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
At: modules/gdscript/gd_script.cpp:1859.
ERROR: load: Failed loading resource: res://asd.gd
At: core/io/resource_loader.cpp:218.
ERROR: poll: Can't load dependency: res://asd.gd
At: core/io/resource_format_binary.cpp:681.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
At: core/io/resource_loader.cpp:142.
ERROR: load: Failed loading resource: res://Node2D.tscn
At: core/io/resource_loader.cpp:218.
ERROR: start: Failed loading scene: res://Node2D.tscn
At: main/main.cpp:1471.
SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends
At: res://asd.gdc:2.
```
**Link to minimal example project:**

[not_load.zip](https://github.com/godotengine/godot/files/920042/not_load.zip)

https://drive.google.com/drive/folders/0B1QcObgYNJ_PTlZya09tYktzWGs?usp=sharing

**Comment by bojidar-bg** [comment]
@Rocket-Buddha Mismatched export templates' version by any chance?

**Comment by Rocket-Buddha** [comment]
@bojidar-bg  SOLVED with Godot_v2.1.3-stable_export_templates. We didn't know that we have to change templates. It could be a good idea that you guys allow a link in godot download page, release + templates, if change is required. Thanks a lot!

**Comment by volzhs** [comment]
@Rocket-Buddha godot binary and templates always have been provided at download page for every each version.

**Comment by Rocket-Buddha** [comment]
Yes I know, I mean, both in the same link. For example:

Godot Engine 2.1.3-stable
RELEASED 2017/04/12

- Linux 64-bit (Editor only) 
- Linux 64-bit + Export Templates
