### ISSUE TITLE
[4.2] textureLod no effect with SCREEN_TEXTURE

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#83919]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10, 64bit

### Issue description

3.5:
![image](https://github.com/godotengine/godot/assets/35988767/269fc9f5-cfd7-4339-821f-430fbf2b736e)
4.2:
![image](https://github.com/godotengine/godot/assets/35988767/d47fc827-5e07-4687-9e96-1976e401516b)

### Steps to reproduce

/

### Minimal reproduction project

[TLOD_Test.zip](https://github.com/godotengine/godot/files/13161756/TLOD_Test.zip)

**Comment by clayjohn** [comment]
In 4.x, you must specify if you want to use mipmaps on the sampler if you want mipmaps to be generated. E.g. using `filter_linear_mipmaps`

**Comment by CsloudX** [comment]
> In 4.x, you must specify if you want to use mipmaps on the sampler if you want mipmaps to be generated. E.g. using `filter_linear_mipmaps`

Thanks, should I close this issue?
OTHER: In VisualShader, how set the `filter_linear_mipmap`?

**Comment by clayjohn** [comment]
> > In 4.x, you must specify if you want to use mipmaps on the sampler if you want mipmaps to be generated. E.g. using `filter_linear_mipmaps`
> 
> Thanks, should I close this issue? OTHER: In VisualShader, how set the `filter_linear_mipmap`?

Please leave it open as we need to document this better. 

For Visual Shaders you use the texture parameter node https://docs.godotengine.org/en/latest/classes/class_visualshadernodetextureparameter.html
