### ISSUE TITLE
GUI Rendering issue

### ISSUE THREAD

**Issue by DavyMaldonado** [godotengine/godot#83910]
### Godot version

4.1.2 stable

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 530 (Intel Corporation; 21.20.16.5174) - Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 Threads)

### Issue description

Text and images on the main menu GUI are only rendering the top right corner of images and characters. This was not an issue first launch but after it was.
![image](https://github.com/godotengine/godot/assets/89171952/34f18f8d-48a5-4705-b065-07dd0b37a1d3)
![image](https://github.com/godotengine/godot/assets/89171952/b6a68142-fd69-4548-b03b-919852097241)

### Steps to reproduce

Happens when opened

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79955.
