### ISSUE TITLE
FileAccess can't load files as bytes when exported to Android (Godot Mono)

### ISSUE THREAD

**Issue by adarshcat** [godotengine/godot#83918]
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Windows 11 - Godot v4.2.beta2.mono - Forward Mobile - .NET 7

### Issue description

FileAccess **can** load files as bytes when not exported and in editor. The exported app crashes trying to do the same on android.

`byte[] data = Godot.FileAccess.GetFileAsBytes("xxx.bin");`

Code statement used which creates the problem.

The same problem also happens when trying to use any C# native functions for loading files. It works fine as long as in editor and then crashes once exported.

Note - By crash I mean the app keeps running but none of the C# code seems to get executed.

Also, the bug can be replicated when trying to open a "xxx.jpg" file as bytes confirming that the problem is not with godot not packaging unrecognized files.

### Steps to reproduce

- Try loading bytes of a jpg image file into a byte array
- Use the LoadJpgFromBuffer() function to convert it into an Image object
- Apply the Image as a ImageTexture to a Sprite node
- Works fine as long as in editor and crashes when exported to android

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
> "xxx.bin"

Where is this file located? It's not an absolute path or resource path (e.g., `res://xxx.bin` to read it from APK/PCK) it will try to load file from working directory. For the editor, the working directory is a project directory, but in the exported project it won't have any project files.

**Comment by adarshcat** [comment]
> > "xxx.bin"
> 
> Where is this file located? It's not an absolute path or resource path (e.g., `res://xxx.bin` to read it from APK/PCK) it will try to load file from working directory. For the editor, the working directory is a project directory, but in the exported project it won't have any project files.

The script trying to access it is stored in res://script/xxx.cs while the file to be opened is stored in "res://xxx.bin". Also I forgot to mention is that it works fine as long as I am using Image.Load() on a jpg file (since Load can only work on a recognized image format) but it breaks once I try to open it using a FileAccess.

**Comment by bruvzg** [comment]
> Also I forgot to mention is that it works fine as long as I am using Image.Load() on a jpg file (since Load can only work on a recognized image format) but it breaks once I try to open it using a FileAccess.

If it's JPG or other image which is imported resource, the original file is NOT included with the exported project (unless you have added it to the filters in the export dialog), Image. Load will read `res://xxx.jpg.import` (config) and `res://.godot/imported/xxx.jpg-hash.ctex` (converted image data).

**Comment by AThousandShips** [comment]
See the [documentation](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/import_process.html#importing-assets-in-godot) for details

**Comment by adarshcat** [comment]
@bruvzg 
Nvm, tried doing `Image.LoadFromFile("res://Rect.png")` today and it doesnt seem to work on android after being exported but it does work in the editor

**Comment by AThousandShips** [comment]
As said above, this is by design, and is documented

You are still attempting to load the same way, you need to use `load` or `ResourceLoader.load`

**Comment by adarshcat** [comment]
Thanks! Got it working. So if I get it correctly, Image.LoadFromFile() is supposed to load form a file on the storage and I have to use the GD.Load() is I want to load anything from the project's resources
