### ISSUE TITLE
Vector3.Rotated does not rotate around a normalized vector

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#83922]
### Godot version

4.1 .Net

### System information

Win10 x64 22H2

### Issue description

I have a Vector3 called `originPos` that I want to rotate about another vector called `endNormal`.
Documentation says the rotation axis must be normalized.
My code is `originPos.Rotated(endNormal.Normalized(),Mathf.Pi);`

However, I am still getting an error `Argument is not normalized. (Parameter 'axis')` even though the axis vector is normalized. Manually normalizing the vector by dividing it by the vector length/magnitude does not resolve.

However, changing the axis vector to one of the standard unit vectors like Vector3.Up works fine.

### Steps to reproduce

Described in issue.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Is there any chance that ``endNormal`` is (0,0,0)?

**Comment by yosimba2000** [comment]
> Is there any chance that `endNormal` is (0,0,0)?

Hi, nope, none of the endNormal values are (0,0,0).
endNormal is actually the surface normal of one the faces of a cube, and I GD.Printed the normal just in case, and it came out as (0,1,0).

**Comment by clayjohn** [comment]
> > Is there any chance that `endNormal` is (0,0,0)?
> 
> Hi, nope, none of the endNormal values are (0,0,0). endNormal is actually the surface normal of one face of a cube, and I GD.Printed endNormal just in case, and it came out as (0,1,0).

Well, that is troubling. Can you please upload an MRP so that other contributors can try to reproduce and (hopefully) resolve this issue?

**Comment by yosimba2000** [comment]
> > > Is there any chance that `endNormal` is (0,0,0)?
> > 
> > 
> > Hi, nope, none of the endNormal values are (0,0,0). endNormal is actually the surface normal of one face of a cube, and I GD.Printed endNormal just in case, and it came out as (0,1,0).
> 
> Well, that is troubling. Can you please upload an MRP so that other contributors can try to reproduce and (hopefully) resolve this issue?

Sorry, I think it's a false alarm. I seem to have fixed it by lowering the multiplier on my raycast destination.

This is my code
```
PhysicsRayQueryParameters3D raycastQuery = PhysicsRayQueryParameters3D.Create(kvp.Key.GlobalPosition,kvp.Key.GlobalPosition+-kvp.Key.Basis.Z*100f);
					raycastResult = physicsServer3D.IntersectRay(raycastQuery);

					if (raycastResult.Count>0){
						SoundBounceClass soundBounceClass = new SoundBounceClass();
						soundBounceClass.reflectDir=(soundBounceClass.endPos-soundBounceClass.originPos).Reflect(soundBounceClass.endNormal.Normalized());
```

**Comment by yosimba2000** [comment]
Sorry, did not resolve. I made a mistake. The raycast wasnt reaching far enough to get a hit, and thus didn't bother to attempt Vector3.Rotated. Working on MRP now...

**Comment by yosimba2000** [comment]
[Thief.zip](https://github.com/godotengine/godot/files/13163243/Thief.zip)
Attached is the MRP.

So just a quick overview of what's happening.
1) Scene comprises of a bunch of cubes with colliders so they can be raycasted onto, and one AudioStreamPlayer3D.
2) When currentBounce==1, AudioStreamPlayer3D is rotated randomly 10 times, each time raycasting along its forward and detecting any hits.
3) If hits are detected, record the results in a Dictionary. Most notably, calculating the reflection vector resulting from the hit.
Reflection direction calculated either using Vector3.Rotated by Pi radians, Vector3.Bounce, or Vector3.Reflect. This project uses Vector3.Rotated.
4) currentBounce is incremented.
5) When currentBounce is >1, use the previous Dictionary raycast results to continue propagating the rays according to the reflection vector.
6) When currentBounce >8, reset currentBounce =1, and start over again.

Something interesting to note:
Even though the raycast code is nearly the same between case `currentBounce =1` and `currentBounce >1`, there is no error generated when `currentBounce =1`. The error only starts to happen when `currentBounce = 2`. It cannot continue further higher numbers because of the error.
