### ISSUE TITLE
Vector3.Reflect and Bounce do not reflect/bounce from a normalized vector

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#83923]
### Godot version

4.1 .Net

### System information

Win10 x64 22H2

### Issue description

I have a Vector3 called `originPos `that I want to bounce/reflect about another vector called `endNormal`.
Documentation says the axis must be normalized.
My code is `originPos.Bounce(endNormal.Normalized());` and `originPos.Reflect(endNormal.Normalized());`

I get an error saying `Argument is not normalized. (Parameter 'normal')` even though the normal vector is normalized. Manually normalizing the vector by dividing it by the vector length/magnitude does not resolve.

However, changing the normal vector to one of the standard unit vectors like Vector3.Up works fine.

### Steps to reproduce

Described in issue.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Related: https://github.com/godotengine/godot/issues/83922 these are most likely the same issue

**Comment by yosimba2000** [comment]
Solved in https://github.com/godotengine/godot/issues/83922

It was user error, sorry!
