### ISSUE TITLE
empty_clicked signal doesn't fire if Tree has hide_root enabled

### ISSUE THREAD

**Issue by joeymanderley** [godotengine/godot#83928]
### Godot version

4.1.2.stable.mono

### System information

Windows 10 - Forward+ Vulkan

### Issue description

In GDScript, `empty_clicked` signal doesn't fire if Tree has `hide_root` enabled. Have not tested C#.

### Steps to reproduce

1) Make a scene with a tree. Add a root item. Connect `empty_clicked` signal to a print or something. It should print when empty space is clicked
2) Set `hide_root` to true. It no longer prints when empty space is clicked.

### Minimal reproduction project

N/A

**Comment by Beider** [comment]
I can confirm this, I just tried it in my project.

If the tree has no items and root is hidden then empty click will not trigger.
However it the tree has items and root is hidden then empty click will trigger.

So workaround for this is to not hide root if the tree is empty and also make sure you handle right click on empty / root item the same way. Then hide root once you add something to the tree.

**Comment by voylin** [comment]
Experiencing the same bug at the moment. Anybody working on fixing this at the moment?

**Comment by KoBeWi** [comment]
For me the signal is not emitted regardless of `hide_root`, if there are no items.

**Comment by voylin** [comment]
> For me the signal is not emitted regardless of `hide_root`, if there are no items.

I don't know if this is something that should matter. If there are no items to begin with, should root be hidden at that point? Because the first TreeItem which you'd create won't show up anyway. Maybe this should be an update to the documentation of the signal?
