### ISSUE TITLE
'PROPERTY_USAGE_NEVER_DUPLICATE' seems to be ignored, when duplicating in the Editor

### ISSUE THREAD

**Issue by meloonics** [godotengine/godot#83920]
### Godot version

4.1.2.stable

### System information

Windows 10

### Issue description

I want to assign unique Resources to Nodes, that keep track of some of the Node's information while working in the Editor. My goal is to store the resources' information in a file later on. 
This means, that if I duplicate a Node in the Editor, using Ctrl+D, I want the duplicate's custom resource property to be null, so a new, unique Resource can be assigned to it automatically. 
Here's where the usage flags for the 'my_resource' property seem to show unexpected behavior:
So I set PROPERTY_USAGE_DEFAULT, because I want the property to be stored in the scene and to be visible in the editor. I *also* set PROPERTY_USAGE_NEVER_DUPLICATE, because when duping the Node, I want this property to be null in the duplicate-Node. 
This does not work as I expected: When I instantiate a scene in the editor, assign my_resource, and then duplicate it, the my_resource property will be copied, which I do not want. 
However, when I use PROPERTY_USAGE_EDITOR instead of _DEFAULT, this would work as I expected. The downside is, that all information would be wiped when reloading the scene, which I also don't want. 

My goal is to quickly add many nodes to the scene (using ctrl+d), but at the same time assigning new, unique resources to each of them automatically. 

### Steps to reproduce

see sample project

### Minimal reproduction project

[resource_duplicate.zip](https://github.com/godotengine/godot/files/13161757/resource_duplicate.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment]
I think you misunderstand the meaning of this, it doesn't say anywhere in the documentation that it won't assign the new value, just that it won't duplicate it:
> When duplicating a resource with Resource.duplicate, and this flag is set on a property of that resource, the property should never be duplicated, regardless of the subresources bool parameter.

It will *copy* the value directly, instead of duplicating it

**Comment by meloonics** [comment]
Okay, that makes sense. So the properties of a duplicated Node will *always* be copied, and the usage flag only determines whether a new, separate object is created instead of directly copying the original's value?

Okay, so it seems the solution to my problem lies somewhere in setting the Resource local_to_scene, then?
This issue can be considered closed, thanks for the clarification.
