### ISSUE TITLE
Internal editor should not open when creating connections if external is enabled

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8392]
**Ubuntu 16.10 - Godot version: 2.1.2**

**Issue description:**
Setting an external code editor and creating a signal connection with function using the Node panel, opens the internal code editor and adds the created function there, then appears the external editor, without function added (of course).

I think that the connection creation should not open the internal editor if an external editor is active, even if than means no new function added.

**Steps to reproduce:**
 - Set up an external editor in editor settings.
 - Create a connection to a node with a script with "make function" enabled.
 - Both editors should open, the internal with the function, the external without it.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment]
This seems to be solved on 2.1 and 3.
