### ISSUE TITLE
Using the Color Picker screws up/desynchronises Undo History

### ISSUE THREAD

**Issue by TheSofox** [godotengine/godot#83945]
### Godot version

v4.2.beta2.official 

### System information

Windows 10

### Issue description

The Colour Picker seems to add Undo steps that do not appear in the Undo history. This can lead to you undoing several colour changes that you did while the Colour Picker was open, while your position in the Undo History moved onto events you did before even opening the Colour Picker.

Discovered while investigating Issue #83642

### Steps to reproduce

1. Create a 2D scene and add a simple sprite.
2. Open up the history tab (maybe move it so it and the Inspector are both visible at the same time)
3. Do some standard manipulation to the sprite (moving, visibility toggle, etc), observing how the actions get added in the History tab.
4. The open the color picker, and with the picker open, change the Modulate colour a several times, try different swatches, hues, etc.
5. Close the color picker.
6. Try to undo and redo the last few operations. While keeping an eye on the History windows

Expected:
Your position in the History list should correspond to the actions you are doing/undoing.

Actual:
Things get desynched. Somehow the history queue only lists about 2 modulate actions (despite only opening up the picker once). Yet you can undo through several different colour changes that you did while the picker was open. This leads to the history queue listing that you are undoing a move or visiblity operation, when you're still undoing modulate colour changes.

### Minimal reproduction project

N/A

**Comment by TheSofox** [comment]
Okay, it turns out, the exact same problem happens with text fields (for instance, on "Text" field for "Label"). The colour picker uses the same system as the Text field input (setting p_changing to true).

**Comment by TheSofox** [comment]
I've even got this bug to happen with checkboxes. It takes a bit of fiddling, and doesn't always work (I think you need to space out the time between clicks), but you'll get (for example) two "Set Visible" in History, but be able to undo yourself toggling visibility multiple times.

**Comment by TheSofox** [comment]
Video demonstrating issue.
https://github.com/godotengine/godot/assets/3089525/b855459b-fdaa-450b-a760-62e2cd2367c1

**Comment by TheSofox** [comment]
I believe I've found the issue. It stems from editor_undo_redo_manager.cpp (which handles History) and undo_redo.cpp (which handles actual Undo functionality) handle MERGE_ENDS slightly differently. The manager will simply merge (or at least not add a new action) if the recent actions have the same name, however the actual undo_redo.cpp has an additional requirement that the merge will only happen if the most recent action happened less than 800 milliseconds ago. (line 88)

Make the same action several times with gaps greater than 800ms, and the History won't add more actions, but the Undo queue will.

The question is how should this be fixed. Should the same 800ms check be added to the Manager, or should the manager directly question the undo_redo.cpp to keep its queue updated?

In addition, should checkboxes even have their actions merged in the first place? Funny how toggling the visibility in scene editor will create an action for each toggle, but doing the same in the Properties Panel will have the actions merged. In fact, everything in the Properties Planel will get merged if done repeatedly; Dropdowns, Masks, etc. For fast changing things like spinner, colour picker and textbox, this all makes sense, but for the others?

I'm tagging @KoBeWi and @akien-mga since they've both worked with Undo queue before.

**Comment by KoBeWi** [comment]
> should the manager directly question the undo_redo.cpp to keep its queue updated?

I think that would be the best, but the way EditorUndoRedoManager works makes it a bit difficult IIRC.

That 800ms thing is new to me, but it seems to have existed before EditorUndoRedoManager was implemented 🤔 Combined with History dock this issue can freeze the editor, so it's quite serious.

> In addition, should checkboxes even have their actions merged in the first place?

I think not. The inspector just merges undo for everything, but for some types/actions it shouldn't. That's a matter for a proposal  though.

**Comment by TheSofox** [comment]
So yeah, my above pull request should fix things by having the EditorUndoRedoManager query UndoRedo for whether the last action was merged or not. Had to add an API call, but much better than having two checks run in parallel.
