### ISSUE TITLE
Rendering defect when using the Compatibility Renderer, with a Plane MeshInstance

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#83968]
### Godot version

4.2beta2.mono

### System information

MacOs Sonoma

### Issue description

I get a strange shadow-like effect on a Plane Mesh instance when using the Compatibility Renderer.

 Compatibility
![2023-10-25_21-26](https://github.com/godotengine/godot/assets/27586088/24acd09d-8e03-4438-922d-94ce1012fd8d)

Forward+
![2023-10-25_21-27](https://github.com/godotengine/godot/assets/27586088/48526443-4bb1-4bb7-ad36-956f2c28f6a0)

### Steps to reproduce

- Create a Project
- Add a MeshInstance3D node
- Add a PlaneMesh
- Update its size to something like x:30 y:30
- add a Material to the Mesh and Update its Albedo Color to a Dark Grey Color ( to better see this shadow-like effect )
- Zoom in and out with the camera so you can be able to see it .

This happens when running the project as well .

### Minimal reproduction project

I have added a steps to reproduce it

**Comment by MrZak-dev** [comment]
This is valid and exist in Godot 4.2.beta3.mono

**Comment by clayjohn** [comment]
It looks like it may be shadow acne from the editor sun (which has shadows enabled by default). Can you add the preview sun to your scene and adjust the shadow bias options to see if the issue goes away?

**Comment by MrZak-dev** [comment]
> It looks like it may be shadow acne from the editor sun (which has shadows enabled by default). Can you add the preview sun to your scene and adjust the shadow bias options to see if the issue goes away?

Changing the shadow bias has no effect on this but when changing the Sun light mode to Orthogonal makes this shadow-like effect disappears.

**Comment by Calinou** [comment]
I can't reproduce this on 4.3.dev 5708a3a02 (Linux, GeForce RTX 4090 with NVIDIA 550.78):

https://github.com/godotengine/godot/assets/180032/02f55160-7288-484b-90cb-94c820bf1cd7

[test_shadow_plane_compatibility.zip](https://github.com/godotengine/godot/files/15366258/test_shadow_plane_compatibility.zip)

Please comment if you can still reproduce this **with a minimal reproduction project attached**.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
