### ISSUE TITLE
Bake NavigationPolygon in NavigationRegion2D ignores other Tilemap layers

### ISSUE THREAD

**Issue by ThePat02** [godotengine/godot#83967]
### Godot version

v4.2-beta3

### System information

Godot v4.2.beta3 - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 30.0.13044.14002) - AMD Ryzen 9 5900HX with Radeon Graphics (16 Threads)

### Issue description

When baking a `NavigationPolygon` in a `NavigationArea2D`, only the collision data of the first layer of a `TileMap` is used. For example: Tiles placed on the second layer that have collision will not be taken into account when baking. If you change the order of the layers, the same bug appears and only the first layer will be baked into the `NavigationPolygon`!

### Steps to reproduce

1. Create a `NavigationArea2D` and add a new `NavigationPolygon`.
2. Add a `TileMap` as a child and fill different layers with objects that have collision data.
3. Bake the `NavigationPolygon`.

### Minimal reproduction project

[minimal_reproduction_navigationbaking.zip](https://github.com/godotengine/godot/files/13170355/minimal_reproduction_navigationbaking.zip)

**Comment by smix8** [comment]
The 2D navigation mesh baking parses only the TileMap Layer0. This not a bug but an intentional limitation because the TileMap Layers system does not work for the navigation mesh system.

**Comment by ThePat02** [comment]
How would you suggest solving this issue in a project? Havin a dedicated layer on your tilemap where you only put collision tiles?

**Comment by smix8** [comment]
While this is not a provided feature of the TileMap users can work around the issue by using a NavigationMeshSourceGeometry2D object to parse the TileMap Layer0 with NavigationServer2D.parse_source_geometry_data(). The objects from the other TileMap Layers can be added on top manually to the source geometry for the baking.

**Comment by ThePat02** [comment]
> Or place the two TileMaps in a way that the parsing can read both into the same source geometry. The problem with many TileMap nodes will be that the parsing will run on the main thread because they are nodes in the SceneTree.

I just use two TileMap nodes for now. This is a quick and dirty solution for now.

**Comment by Pardok** [comment]
Hi, I made a small tool called [TileMapsChef](https://godotengine.org/asset-library/asset/2416) ([GitHub](https://github.com/Pardok/TileMapsChef)) following @smix8's suggestions. Maybe in the future I'll make it a bit more user-friendly (layer selection, proper UI). But if you just want to bake all colliders from all layers into your NavigationRegion2D, it will do the job.
