### ISSUE TITLE
Game takes a long time to launch for the first time or after moving it to another folder on MacOS

### ISSUE THREAD

**Issue by chutneyio** [godotengine/godot#83974]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - macOS 14.0.0 - Vulkan (Forward+) - dedicated AMD Radeon Pro 555X - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

Exported game seems to take a very long time to launch for the first time or after moving it to another folder.

### Steps to reproduce

- Create an empty project
- Export the game
- Run the game for the first time, observe that it takes > 10 seconds to launch. Launch the game again and it only takes < 1 seconds.
- Move the game to another folder, and it also takes more time to launch for the first time.

### Minimal reproduction project

Empty project

**Comment by Zireael07** [comment]
Most likely shader cache creation/shaders compiling?

**Comment by AThousandShips** [comment]
Indeed this sounds like shaded compilation

**Comment by chutneyio** [comment]
So this is essential then. I think we can improve the UX by letting the game show loading progress when doing that kind of heavy stuff at the beginning. Currently the game is unresponsive with a spinning wheel for almost 10s before splash screen appears. It would be better if we can show splash screen immediately upon launch while compiling the shaders in background.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/3657.
