### ISSUE TITLE
Visual shader node editor to come back?

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#8397]
In my first little round of testing with Godot 3, I noticed that we were back to more complex shaders being done by way of scripting only with no node-based shader builder like in Godot 2.1.

Is the Visual Shader Editor slated to come back, I find it very useful for cases like creating a terrain shader (with multiple textures) and other things such as using a colored black and white texture (which allows one to save space since they can have an unlimited combination of colors for use in many different materials)? There's also the whole thing of allowing a lot of different textures for additional detail.

That node-based workflow might work even better now with the improvements made for the visual logic editing, any chance that the VSE will be back in 3.0 final?

**Comment by reduz** [comment]
Yes, will eventually come back

**Comment by reduz** [comment]
but nor for 3.0, we are out of time. Will have to be for 3.1

**Comment by Zireael07** [comment]
Are 2.1 visual shaders usable in 3.0, then? (as in, are they converted somehow to a format that 3.0 understands?)

**Comment by reduz** [comment]
@Zireael07 No, shaders in Godot 3.0 are incompatible with 2.1, as they changed the way they work considerably. They will need to be rewritten

**Comment by Chaosus** [comment]
_Well, visual shader editor is implemented to 3.1. Closed_
