### ISSUE TITLE
VisibleOnScreenNotifier doesn't work with screen_entered signal when object is hidden

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot#83971]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Godot v4.2.beta2 - macOS 11.7.10 - Vulkan (Forward+) - integrated Intel HD Graphics 5000 - Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 Threads)

### Issue description

Godot 4 VisibliltyOnScreenNotifier will not alert unless shown, this makes it useless for showing and hiding objects when they enter and exit the screen.

### Steps to reproduce

1. Add a visibilty node to a scene
2. Configure the node
3. Hide the visiblity node in the scene

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
This is intended and documented behavior.
Why do you want to hide nodes out of screen?

**Comment by AThousandShips** [comment]
This is indeed [documented](https://docs.godotengine.org/en/stable/classes/class_visibleonscreennotifier3d.html)

If you want this to change you can open a [proposal](https://github.com/godotengine/godot-proposals) but given how this is implemented it's probably not going to change

**Comment by Zireael07** [comment]
@KoBeWi Likely an optimization technique so that scene culling has less to do

**Comment by AThousandShips** [comment]
Indeed, if the system was to be separated from the rendering related culling you'd have to make sacrifices for performance

Now you can use a single culling setup for both, otherwise you'd either have to reduce the performance of the rendering culling (not an option) or add a second culling setup *just* for visibility queries like this

**Comment by ltecheroffical** [comment]
What if the player looks away from a object, is that handled by culling?

**Comment by ltecheroffical** [comment]
Or what if the object is offscreen?

**Comment by KoBeWi** [comment]
> What if the player looks away from a object, is that handled by culling?

No, but you don't need VisibleOnScreenNotifier for that.

> Or what if the object is offscreen?

Yes.

**Comment by ltecheroffical** [comment]
If a player looks away from an object it doesn't need to renderer so the fact it only works when it's visible is crazy.

**Comment by KoBeWi** [comment]
See my edit, I thought you are talking about 2D.

**Comment by ltecheroffical** [comment]
still applies in 2D.

**Comment by KoBeWi** [comment]
It doesn't. What do you mean by "player looking away" in a 2D space? The object is still on screen in that situation, it has to be handled by the user if you want some visibility cone or whatever.

**Comment by ltecheroffical** [comment]
The visible on screen notifier is useless due to that factor so it's useful if it's removed or the bug is patched.

**Comment by AThousandShips** [comment]
There's no bug here, it's how it works

**Comment by ltecheroffical** [comment]
This can also break older compatibility with Godot 3 projects that use this because culling has to calculate every frame, but with the on-screen notifier, this can be averted. This will slow them down or prevent objects from appearing again after hidden.

**Comment by AThousandShips** [comment]
You don't need a notifier to help with culling, it handles it, no slow down will happen, you don't need to help the renderer

**Comment by ltecheroffical** [comment]
The culling still checks every frame or if the camera moves, with the on screen notifier then it can hook into the game functions to let objects know to check if their on screen but with culling, it doesn't know when it should check to cull so it culls whenever it assumes.

**Comment by AThousandShips** [comment]
It doesn't work that simply though, it's doing a spatial search

If you are having serious performance issues the cause is likely not the culling needing help and wouldn't be helped by some other culling based method

**Comment by ltecheroffical** [comment]
In godot 3 or older than it used to have it work even when the object is invisible, this also causes problems that the developer has to search and fix so this new change also breaks older godot 3 projects by making objects using that method simply not appear. Also culling is better when the dev has more control over culling and when it happens.

**Comment by AThousandShips** [comment]
Okay, but there's no compatibility between 3.x and 4.x, 4.x has improved the code

This isn't a bug, so if you want to discuss changing this behaviour you should open a proposal, this is for bugs

You can still control this, just use `Area2D` to hide parts of the game that are off screen

If you want to change the behaviour please open a proposal, this should be closed either way as it's not a bug

**Comment by AThousandShips** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/8458
