### ISSUE TITLE
GlobalClass inheriting from abstract non-GlobalClass shows error in Create New Node create_dialog.

### ISSUE THREAD

**Issue by CantyCanadian** [godotengine/godot#83981]
### Godot version

v4.1.1.stable.mono.official

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.4584) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

If I have a class that is marked as a GlobalClass for the purpose of being added as a node in the inspector, and that class inherits from an abstract class that is not marked as a GlobalClass, an error will be shown despite the whole process actually working successfully (derived note shows up and can be created).

![image](https://github.com/godotengine/godot/assets/7960042/56471644-ea7c-43fe-8353-da57ec599052)

The issue is logical, the engine has the top-most class showing up in its node list, yet it cannot determine its base class since the attribute is missing and thus the engine has no knowledge of what the base class is. If there was a way to check both a. Is a Node and b. inherit.isEmpty, then we can assume that the engine is missing a class and should show a proper error explaining that.

### Steps to reproduce

1. Create abstract base class inheriting from Node.
2. Create derived class inheriting from base class.
3. Make derived class [GlobalClass].
4. Try to create a child node in the editor.

### Minimal reproduction project

This project should show the error if the Create Node window is opened.

[Test.zip](https://github.com/godotengine/godot/files/13173085/Test.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by zaevi** [comment]
It works on 4.2.beta3, might be fixed by #81101.
