### ISSUE TITLE
InputEventMouseMotion not working with  ==

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#83993]
### Godot version

4.2 beta 3

### System information

windows 10 vulkan

### Issue description

InputEventMouseMotion only works with 'is'
In previous version godot 4.1 you could type '==' now it only works with 'is' 

### Steps to reproduce

```
func _input(event):
	
	if event is InputEventMouseMotion:
		print("its working")
	
	if event == InputEventMouseMotion:
		print("not working")
```

### Minimal reproduction project

na

**Comment by akien-mga** [comment]
You seem to be misremembering, `event == InputEventMouseMotion` is invalid code also in 4.1.
`event` is an object of type `InputEventMouseMotion`. It's not the type itself. The `==` operator can't be used for type checking. For example `4.0 == float` doesn't make much sense.

Tested with this code in 4.1-stable:
```diff
func _input(event):
	if event is InputEventMouseMotion:
		print("'is' check is working")
	
	if event == InputEventMouseMotion:
		print("'==' check is working")
```

`'==' check is working` is never printed, as expected.
