### ISSUE TITLE
Incorrect value set in ParticleProcessMaterial.

### ISSUE THREAD

**Issue by layton7362** [godotengine/godot#83995]
### Godot version

4.2.beta2.official

### System information

Windows 11

### Issue description

When creating the ParticleProcessMaterial, incorrect values are used (linear_accel_max and radial_accel_max).

Current:
![grafik](https://github.com/godotengine/godot/assets/43618510/0e0250f3-cdc7-49c6-ad0a-9d4e70b41e2d)

Fix:
![grafik](https://github.com/godotengine/godot/assets/43618510/59d8dedb-5a24-4337-9606-bf89a2bb7c49)

### Steps to reproduce

Just create a ParticleProcessMaterial and convert it to Shader.

### Minimal reproduction project

N/A

**Comment by rpgshooter** [comment]
Currently investigating this as well as confirmed that such an error occurs for the shader generation.

**Comment by AThousandShips** [comment]
This has not been fixed yet, we'll keep this open until the PR is merged
