### ISSUE TITLE
Can not open 4.1.1 project with 4.1.2 on Mac OS

### ISSUE THREAD

**Issue by walterpalladino** [godotengine/godot#83997]
### Godot version

4.1.2

### System information

Mac OS M1 Sonoma

### Issue description

I been working on a project using Godot 4.1.1 and I tryed to open it on 4.1.2 and it get stuck on a black screen.

### Steps to reproduce

-Open the project laucher
-Select project
-Double click on it

This is the project I'm using: https://github.com/walterpalladino/godot-shaders

### Minimal reproduction project

https://github.com/walterpalladino/godot-shaders

**Comment by akien-mga** [comment]
Can you confirm that the same project still works if you try to open it now with 4.1.1? Just to exclude issues caused by a system update independently from Godot's own update.

I don't reproduce the issue on Linux with Mesa drivers for AMD Radeon RX Vega M.

CC @bruvzg

**Comment by walterpalladino** [comment]
I was able to open the same project on Godot 4.1.1.

**Comment by bruvzg** [comment]
I can't reproduce it, neither with 4.1.2, nor with current master. Projects opens, and all test scenes under `shaders` subfolder looks functional (based on shader names, I have not compared rendering with other platforms).

Try deleting `.godot` folder and reimport resources after switching the versions.

**Comment by walterpalladino** [comment]
Yes, that did the trick.
Thank You.
