### ISSUE TITLE
Changing Terrain Set of one Tile changes Terrain of everything

### ISSUE THREAD

**Issue by lazy-paperboy** [godotengine/godot#83999]
### Godot version

4.1.2

### System information

Debian GNU/Linux 12

### Issue description

I have three Tilesets (orange, dark grey, light grey) in TileSet -> Tiles

Assigning each Terrain Set with a unique Terrain does not work. Changing the Terrain Set of the dark grey Tileset also changes the Terrain Set of the orange and light grey Tileset.

### Steps to reproduce

- TileSet -> Tiles:
- Add >1 Tileset
- assign each Tileset a different Terrain Set/Terrain
- change ONE setting
- all other Tilesets now have the same settings

### Minimal reproduction project

Assigning each Terrain Set with a unique Terrain does not work. Changing the Terrain Set of the dark grey Tileset also changes the Terrain Set of the orange and light grey Tileset.

**Comment by lazy-paperboy** [comment]
It's also probable I'm doing something wrong, but I can't find anything in the docs. I uploaded a Screenshot: https://i.imgur.com/bWCEFB4.png

I don't understand the usecase of having multiple Tilesets in multiple Terrain Sets if I can't change the Terrain Sets.

**Comment by lazy-paperboy** [comment]
This Tool is very, very confusing but I think I figured it out: changing the settings doesn't do anything, it's just visual. What matters is, that the bitmask is painted with the Terrain Set selected. I'm still not sure how to delete selected Tiles from a TileSet.

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.
