### ISSUE TITLE
Volumetric fog stops taking lights into account when changing scene under specific circumstances

### ISSUE THREAD

**Issue by ArtyIF** [godotengine/godot#83990]
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Godot v4.2.beta2.mono - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i3-1215U (8 Threads)

### Issue description

When changing from a scene with a WorldEnvironment with volumetric fog enabled to a scene with the same WorldEnvironment (not sure if it should actually be the same), volumetric fog stops taking lights (at least `DirectionalLight3D`s) into account. This is fixed if the first scene has a `DirectionalLight3D` with shadows on.

Expected:

![image](https://github.com/godotengine/godot/assets/8017858/ee9406ca-6f1f-4a9b-99fb-cdf1050a3f0b)

Result:

![image](https://github.com/godotengine/godot/assets/8017858/0e362442-750c-4d4b-8ed8-1507155a0393)

Might be related to #83685

### Steps to reproduce

1. Open the MRP
2. Run it normally
3. Hit the Load Scene button
4. See that the fog doesn't account for the directional light
5. Open `scene1b.tscn` and run it
6. Hit the Load Scene button
7. See that the fog works as expected

### Minimal reproduction project

[VolumetricFogBugMRP.zip](https://github.com/godotengine/godot/files/13175669/VolumetricFogBugMRP.zip)

**Comment by interpol-kun** [comment]
I also ran into similar problem: volumetric fog doesn't take in account the lights which were disabled at the start of the scene, but were enabled later by game logic.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83685, as this is due to the same cause. (The issue goes away in the MRP if you resize the window or change the 3D resolution scale factor, which causes buffers to be recreated.)
