### ISSUE TITLE
GDExtension web export fails to run

### ISSUE THREAD

**Issue by dkaste** [godotengine/godot#84008]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Fedora 38

### Issue description

Attempting to run a web export that uses GDExtensions gives the error "memory access out of bounds" on Chrome, and freezes on Firefox, pegging the CPU without an error message.

### Steps to reproduce

- Clone the [godot-cpp repo](https://github.com/godotengine/godot-cpp)
- Setup Emscripten environment with same version as Godot templates (3.1.45 as of writing) (`source ./emsdk_env.sh`)
- Build the test extension for web (`cd test && scons platform=web`)
- Open the test project in Godot
- Add a web export (make sure you enable "Extensions Support")
- Attempt `Remote Debug > Run in Browser`
- Observe the above error message

### Minimal reproduction project

https://github.com/godotengine/godot-cpp

**Comment by dsnopek** [comment]
> * Setup Emscripten environment with same version as Godot templates (3.1.45 as of writing) (`source ./emsdk_env.sh`)

I thought the official Godot templates were compiled with Emscripten 3.1.18?

@akien-mga Can you confirm the version?

**Comment by akien-mga** [comment]
We used 3.1.18 up until 4.2-beta2.
4.2-beta3 is using 3.1.39. Versions newer than 3.1.39 are known to be broken: https://github.com/godotengine/godot/issues/82865

**Comment by dkaste** [comment]
Ah, I was misled by the version I found [here](https://github.com/godotengine/godot/blob/09946f79bd8215b2c6332de8821737580909a91c/.github/workflows/web_builds.yml#L10). 

Thanks for the information, and sorry for the duplicate.
