### ISSUE TITLE
ParticleProcessMaterial ignores the value set for `particle_flag_damping_as_friction`

### ISSUE THREAD

**Issue by cherriesandmochi** [godotengine/godot#84009]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 Threads)

### Issue description

ParticleProcessMaterial will always generate a shader that uses the realistic friction formula for damping, wheter 'particle_flag_damping_as_friction' has been enabled or not.
It's pretty safe to assume that the bug got introduced with #79527.
Additionally, the check for that very flag seems to be inverted: https://github.com/godotengine/godot/blob/09946f79bd8215b2c6332de8821737580909a91c/scene/resources/particle_process_material.cpp#L961

### Steps to reproduce

- Create a GPUParticles3D node.
- Assign a new ParticleProcessMaterial to 'process_material'.
- Convert the ParticleProcessMaterial to a ShaderMaterial
- Open the shader and go to line 300 to see the "realistic friction" code, which shouldn't have been generated, as 'particle_flag_damping_as_friction' is disabled by default.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @QbieShay

**Comment by QbieShay** [comment]
Regression from https://github.com/godotengine/godot/pull/83831/files

**Comment by cherriesandmochi** [comment]
I don't think #84028 closes this issue.
Sorry, I probably wasn't very clear in my report, but the else-branch never gets taken, resulting in the same shader being generated, no matter the value set for 'particle_flag_damping_as_friction'.
I think I should have opened 2 separate issues.

particle_flag_damping_as_friction = false
![Screenshot 2023-10-27 144550](https://github.com/godotengine/godot/assets/5922740/ad5bb3c0-1323-4ac8-8949-1b2ca88bb5ea)

particle_flag_damping_as_friction = true
![Screenshot 2023-10-27 144604](https://github.com/godotengine/godot/assets/5922740/c6fb5280-68c8-4555-9f51-0d7c6eef4c11)

**Comment by QbieShay** [comment]
I also opened https://github.com/godotengine/godot/pull/84029

Could you verify if it changes by reloading the scene?

**Comment by cherriesandmochi** [comment]
Reloading the scene and then converting the it into a ShaderMaterial will still result in identical code, albeit the opposite branch:
![grafik](https://github.com/godotengine/godot/assets/5922740/03ed69c1-a6e7-4929-9f2b-6667b05657f1)

**Comment by QbieShay** [comment]
Then the two PR i created yesterday should address this issue :+1:
