### ISSUE TITLE
After close script:  next open script not relevant to the history hierarchy

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#8400]
**Operating system or device - Godot version:**
Xubuntu 16.04.2 LTS x64, Godot version: 2.1 d8ae244, master

**Issue description:**

When open a multiple scripts and we close a some script (Ctrl+W), in some case a next open script not relevant to the history hierarchy.

**Steps to reproduce:**
If "**highlight current script**" enabled and we try some...
Open files in this sequence:
1.gd -> 2.gd -> 3.gd -> 1.gd -> 3.gd
Now try to close **3.gd**.
Current a history hierarchy by:
1.gd -> 2.gd -> 1.gd
We are here ___**^**
Godot editor has highlight 1.gd, but open **2.gd.**
![close_script_bug](https://cloud.githubusercontent.com/assets/1049442/25026026/773ac0cc-20c6-11e7-8270-c0410ce5c86f.gif)

**Link to minimal example project:**

[close_tab_bug.zip](https://github.com/godotengine/godot/files/920986/close_tab_bug.zip)

**Comment by akien-mga** [comment]
Closing for now to reduce the PR backlog. Discussion can continue on #8400 about what should be the proper fix.

**Comment by akien-mga** [comment]
Oops, wrong issue.
