### ISSUE TITLE
When importing an asset, you can't deselect a partially selected folder.

### ISSUE THREAD

**Issue by Protowalker** [godotengine/godot#84021]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3141) - 11th Gen Intel(R) Core(TM) i7-11375H @ 3.30GHz (8 Threads)

### Issue description

When importing an asset, a file selection window line this appears: 
![image](https://github.com/godotengine/godot/assets/6126319/11e8eb64-0479-4d97-bc20-6f715b02c0df)  
You can select individual files or whole folders, and when a folder has some of its items selected but not all, it appears like this:
![image](https://github.com/godotengine/godot/assets/6126319/a357e76b-5747-452d-9062-c584d007695c)
Clicking on this checkbox will select all of the items in the folder, then clicking it again will deselect all of the items in the folder. This is working as intended. *However,* if some of the files can't be imported, due to file type, conflict, being gdignored, whatever, clicking this button does nothing.  It feels like a good idea to me that instead it should deselect all files, if the only files not selected *can't* be selected.
![image](https://github.com/godotengine/godot/assets/6126319/a656caf3-0351-4440-aaf5-4e7a7696efc1)

### Steps to reproduce

1. Open a project  
2. Go to AssetLib and hit import  
3. Select a zip file  
4. Find a folder with some unselectable files
5. Try to deselect the parent folder

### Minimal reproduction project

Open an empty godot project and attempt to import this zip:
[SignalUtilities.zip](https://github.com/godotengine/godot/files/13182622/SignalUtilities.zip)
then try to deselect the .godot folder or the `editor` folder inside of `.godot`.

**Comment by YuriSizov** [comment]
I think this was already reported somewhere because that's just how the intermediate mode works in Trees. It is annoying though.
