### ISSUE TITLE
CPUParticles2D missing Process Material tab

### ISSUE THREAD

**Issue by yesitsmattharris** [godotengine/godot#84024]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - macOS 13.3.1 - Vulkan (Compatibility) - Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

The Process Material tab is missing from the list of properties within the CPUParticles2D node.

<img width="1509" alt="Screenshot 2023-10-26 at 22 39 57" src="https://github.com/godotengine/godot/assets/9336959/5e58d5f4-8ba2-4de1-9418-336231728f15">

### Steps to reproduce

- Create a CPUParticles2D node
- Note missing tab in properties

### Minimal reproduction project

[CPUParticles2D.zip](https://github.com/godotengine/godot/files/13183120/CPUParticles2D.zip)

**Comment by Calinou** [comment]
This is expected. CPU particles nodes don't use process materials (which use Godot shader language internally). CPU particles are 100% processed in C++ in the engine itself, without any intervention from shaders.
