### ISSUE TITLE
GPU Particles orbit velocities are different between 2D, 3D and documentation on 4.2

### ISSUE THREAD

**Issue by WagnerGFX** [godotengine/godot#84035]
### Godot version

v4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

Each orbit behaves differently from one another and from the documentation hints.
- **Documentation:** orbits per second
- **Orbit 2D on 4.1.2:** Is the same as in the documentation
- **Orbit 2D on 4.2:** orbits per frame
- **Orbit 3D on 4.2 (new):** degrees per lifetime

They should all behave and display the same thing.

My personal suggestion is for orbit to use **degrees per second**. This is the same as other animated velocities, like Angular, Directional and Radial, that all use degrees/distance per second.

Alternatively, orbit could go back to use **full orbits per second** as to keep compatibility with the previous behavior. But I would suggest keeping Angular and Orbit in sync, as they use the same concept for speed.

I'd also suggest updating the Directional and Radial hints, as they don't tell the speed they use, and I had to estimate. (but I can open a new issue for that, since it's unrelated)

![Orbit Speed 3D](https://github.com/godotengine/godot/assets/16827309/b48a5373-0bc0-442f-8c76-a81d79c24d4d)

### Steps to reproduce

The reproduction project has "main_2d" and "main_3d" scenes that show the difference between them, even in the editor.

### Minimal reproduction project

[GPUParticles Orbit Speed.zip](https://github.com/godotengine/godot/files/13184386/GPUParticles.Orbit.Speed.zip)

**Comment by QbieShay** [comment]
Unfortunately I cannot break compat with 2D and 4.1

What's left to decide is if 2D and 3D should be different or not. I am leaning towards not and accepting that we have this weird "orbit per second" unit. But i'm open to suggestions.

**Comment by WagnerGFX** [comment]
> I am leaning towards not and accepting that we have this weird "orbit per second" unit.

Yeah, it's better to have 2D and 3D being in sync with a weird unit than behave differently or break compat unnecessarily.
It should not be hard for the users to convert degrees to a 0~1 range,

**Comment by YuriSizov** [comment]
> It should not be hard for the users to convert degrees to a 0~1 range,

We can still keep the inspector widget in degrees, if it makes more sense when people work visually.
