### ISSUE TITLE
GPU Particles 2D/3D Linear and Radial Max acceleration values are not being used in 4.2

### ISSUE THREAD

**Issue by WagnerGFX** [godotengine/godot#84030]
### Godot version

v4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

In 4.2 the GPU particle's Linear and Radial accelerations only change in behavior when the Min value is changed, while the Max value does nothing. There is no variation between each particle's acceleration when both values are different.

Tangential acceleration and dampening are still applying those values correctly.

4.1.2 seems to be working correctly.

### Steps to reproduce

The reproduction project has "main_2d" and "main_3d" scenes that show the issue, even in the editor.

### Minimal reproduction project

[GPUParticles Accelerations.zip](https://github.com/godotengine/godot/files/13183729/GPUParticles.Accelerations.zip)

**Comment by QbieShay** [comment]
Already closed by https://github.com/godotengine/godot/pull/84006/files
