### ISSUE TITLE
if "string" in ArrayMesh—Always returns true

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#84041]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.113.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

I hope the code explains it. 
```
@tool
extends Node2D

@export var tog:bool:
	set(b):
		test()

var r = load("res://suzanne.res")

func test():
	print("random_string" in r) # Why does this print true?

	# Some more sleuthing:
	#$ grep random_string suzanne.res
	# <no output>
	#$ strings suzanne.res | grep random_string
	# <no output>
```
I get that suzanne.res is a binary file, but perhaps the return should rather be false?

### Steps to reproduce

I have made a small repo for this too.

### Minimal reproduction project

Made a repo here:
https://gitlab.com/dbat/godot-res-property-in-issue

**Comment by AThousandShips** [comment]
This is an error in the `ArrayMesh` code, investigating

**Comment by donn-xx** [comment]
Just in case this might help, I did a loop over all resources:
```python
@tool
extends Node2D

@export var tog:bool:
	set(b):
		test()

func test() -> void:

	var erp = EditorResourcePicker.new()
	erp.base_type="Resource"

	var names:Array = erp.get_allowed_types()

	names = names.filter(func(i):
		return ClassDB.can_instantiate(i) and i != "Resource")

	for classname in names:
		var inst = ClassDB.instantiate(classname)
		if inst:
			if "Judge Dredd Is The Law" in inst:
				print(classname, " has issues")
```

### Result — Some more to have a look at!
SkeletonModificationStack2D has issues
SkeletonModification2DLookAt has issues
SkeletonModification2DCCDIK has issues
SkeletonModification2DFABRIK has issues
SkeletonModification2DJiggle has issues
SkeletonModification2DTwoBoneIK has issues
SkeletonModification2DStackHolder has issues
SkeletonModification2DPhysicalBones has issues
ArrayMesh has issues (fixed now)
SkeletonProfile has issues
SkeletonProfileHumanoid has issues
BoneMap has issues

HTH

**Comment by AThousandShips** [comment]
Most of these are addressed in:
* https://github.com/godotengine/godot/pull/84060
