### ISSUE TITLE
Incorrect error message when calling non @tool method from @tool script

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#84044]
### Godot version

4.2.beta.3

### System information

Windows 11

### Issue description

When you call a non @tool method from @tool script. It shows the error message.
` Invalid call. Nonexistent function 'some_func' in base 'Control (component_scene.gd)'`

It should be something like 
` Invalid call. Function 'some_func' in base 'Control (component_scene.gd) cannot be called from @tool script'`

### Steps to reproduce

Create a Scene with a child component as below with their attached script
![image](https://github.com/godotengine/godot/assets/84369217/00b57c83-6709-433b-a842-15110122998b)

Parent Script:
```gdscript
@tool
extends Control
@onready var component_scene: Control = $ComponentScene

func _ready() -> void:
	component_scene.some_func()
```
Component Script
```gdscript
extends Control

func some_func():
	print("inside some_func")
```
now save all the scenes and go to parent scene and reload the scene
you will get the error message

` Invalid call. Nonexistent function 'some_func' in base 'Control (component_scene.gd)'`

Now add the @tool annotation on the top of the component script the error will go away. This is a simple minor issue but to took me hours to figure what is wrong, due to error message.

### Minimal reproduction project

If required I will create and share one.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/36592.
