### ISSUE TITLE
 is_visible() possible bug?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8406]
**Operating system or device - Godot version:**
2.1.2 stable

For example, look at this hierarchy:

ScrollContainer
--HBoxContainer
&nbsp; &nbsp; --Button1
&nbsp; &nbsp; --Button2
&nbsp; &nbsp; --Button3
&nbsp; &nbsp; --Button4
&nbsp; &nbsp; --Button5
&nbsp; &nbsp; --Button6

Let's say all the buttons are 100x20.

ScrollContainer's max width is 200

And only Button1 and Button2 are visible. You need to scroll to see 3,4,5,6. Which is normal :D

Except If you call `is_visible()` on all the buttons. They all will return true.

Shouldn't only Button1 and Button2 return true? (as the rest are not visible unless you scroll)

**Comment by volzhs** [comment]
I guess it's related with #2194.
it seems what @reduz worried about `is_visible()` or `set_visible()` method.

@Dillybob92 
`is_visible()` represents the flag of visibility is on(true) or off(false).
it's not about `is_really_visible_on_screen()`

**Comment by Dillybob92** [comment]
@volzhs i see, i feel like i should close this then, don't want to waste devs time.  I could probably create a script that checks anyway if its `is_really_visible_on_screen()`, in a scroll container
