### ISSUE TITLE
Cannot create new Shader on ShaderMaterial 

### ISSUE THREAD

**Issue by layton7362** [godotengine/godot#84071]
### Godot version

4.2.beta.3.mono.official

### System information

Windows 11

### Issue description

![Screenshot 2023-10-27 202300](https://github.com/godotengine/godot/assets/43618510/aa3ae2f1-7849-47a8-9998-374ab603a985)

### Steps to reproduce

Just create an Object and give it a ShaderMaterial. Try to create a Shader. The Button is not clickable

But its still possible to convert a StandardMaterial to ShaderMaterial

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Seems to happen in newly created unsaved scenes. The path to shader is invalid. Try saving the scene.
