### ISSUE TITLE
Switching to opengl3_angle rendering backend fails to open projects in compatibility mode

### ISSUE THREAD

**Issue by WagnerGFX** [godotengine/godot#84075]
### Godot version

v4.2.beta.custom_build [b662d232a]

### System information

Windows 10.0.19045 - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4592) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

This has been happening on the latest artifact builds, but not on 4.2-beta3
![OpenGL Angle](https://github.com/godotengine/godot/assets/16827309/c632a537-236b-4beb-9fc6-bdda21e16806)

The drivers are updated and the PC rebooted.
The build console seems to recognize OpenGL API on 3.3.0 and [my GPU](https://www.techpowerup.com/gpu-specs/geforce-gtx-1650-gddr6.c3541) can run up to 4.6

![godot console](https://github.com/godotengine/godot/assets/16827309/13da925c-036e-4300-8b72-05a200a27f82)

I was planning to wait for beta4, as this could be due to different build settings, but decided to open the issue anyway, in case it's important. 👀

### Steps to reproduce

The MRP's contents are of little importance. Instead, it's a project in compatibility rendering using opengl3_angle for Windows.

### Minimal reproduction project

[GPUParticles Compatibility Angle.zip](https://github.com/godotengine/godot/files/13192783/GPUParticles.Compatibility.Angle.zip)

**Comment by bruvzg** [comment]
> This has been happening on the latest artifact builds, but not on 4.2-beta3

Official builds use statically linked ANGLE, CI build does not, so a compatible `libEGL.dll` and `libGLESv2.dll` should be placed in the executable folder for it to work. You can build ANGLE from source or extract required dlls from the minimal CEF distribution - https://cef-builds.spotifycdn.com/index.html

**Comment by WagnerGFX** [comment]
Oh. . . I was right on thinking it was about the build, I just didn't know how.
Now it's working normally, thank you. 😄

I did not find any mention to Angle in the latest docs for building godot. Should I open an issue in godot-docs about that?

**Comment by bruvzg** [comment]
> I did not find any mention to Angle in the latest docs for building godot. Should I open an issue in godot-docs about that?

Yes, docs weren't updated.

The relevant build flag is `angle_libs=/PATH/TO/STATIC/LIBS`, and pre-built static libs are available at https://github.com/godotengine/godot-angle-static/releases

**Comment by WagnerGFX** [comment]
Since the issue is pretty much solved, should I close this, or should it stay open for another reason?

**Comment by Calinou** [comment]
> Official builds use statically linked ANGLE, CI build does not, so a compatible libEGL.dll and libGLESv2.dll should be placed in the executable folder for it to work. You can build ANGLE from source or extract required dlls from the minimal CEF distribution - [cef-builds.spotifycdn.com/index.html](https://cef-builds.spotifycdn.com/index.html)

Could we include those DLLs in the CI artifacts?
