### ISSUE TITLE
Filesystem not showing all folders

### ISSUE THREAD

**Issue by ALoften** [godotengine/godot#84087]
### Godot version

4.1.1

### System information

Windows 11

### Issue description

I have an images folder and FileSystem in Godot has hidden it. Cannot recreate a folder named Images and cannot navigate to the folder by entering the path directly. The folder is available in the windows explorer but not in godot - so I cannot use my images folder. I considered moving it but I do not want to set up ALL my images again and all my references. Its a bit frustrating. 

I have tried reloading the project and now im out of ideas.

![image](https://github.com/godotengine/godot/assets/4909243/d992e008-d286-4d29-85b0-2b53c342cf4f)

### Steps to reproduce

I do not know what happened. The images were there one moment and hidden the next. I have no way to reproduce. Im sorry. But I did strip my project almost entirely, reload it several times and ensure the bug was still happening, and have uploaded it in the "Minimal reproduction project" field.

Load the project, check in both windows explorer and godot, they will not match.

### Minimal reproduction project

[Bug Log for github.zip](https://github.com/godotengine/godot/files/13193882/Bug.Log.for.github.zip)

Load the project, check in both windows explorer and godot, they will not match.

**Comment by ALoften** [comment]
Its worth mentioning that I have been using my script as a floating window. I notice weird things sometimes because of this(like collision shape anchors disappearing). I do not think its related but sometimes any details help. :) Lemme know if you need more details. I love godot and would love to help whereever possible.

**Comment by KirillGrigoriev** [comment]
Hello. It's because you have file named «.gdignore» in «Images» directory. This file literally tell Godot ignore this folder. Just delete this file.

**Comment by ALoften** [comment]
Thanks. It came with a plugin and I didnt realize it was even there. Youre entirely right.
![image](https://github.com/godotengine/godot/assets/4909243/8e5765cd-3594-4747-8141-1cedfe56c60b)

I appreciate your help.

**Comment by stephenmartindale** [comment]
This also happens if there's a `project.godot` file in a directory!

I'm writing that for other readers who might land on this issue report, trying to solve this problem. I had a copy of my `project.godot` file that landed in a directory because of a drag-and-drop failure that I had completely failed to notice and, yes, landed here.
