### ISSUE TITLE
Softbody doesn't work with custom mesh (4.2 beta)

### ISSUE THREAD

**Issue by kylewlacy** [godotengine/godot#84094]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Windows 11 - Ryzen 9 7950x - Vulkan Forward+

### Issue description

I'm trying to set up a softbody in my project. The built-in meshes all seem to work fine (well, as expected anyway), but I haven't had success in Godot 4.2 beta 3 using a custom mesh. I've been trying really simple meshes exported from Blender, but haven't had any luck. I've tried the same setup in Godot 4.1.2, which seems to work fine even following the same steps.

### Steps to reproduce

1. Unzip and import the sample project
2. Run the project by pressing F5

**Expected outcome**

A softbody cube should fall and hit the (invisible) static body mesh right below it

**Actual outcome**

It looks like you need to blow on the Godot cartridge! The points of the mesh move around randomly (or don't appear at all depending on the mesh). Here's a screenshot from this project:

![3D scene with a bunch of triangles arranged sporadically. It looks like a cube had been corrupted](https://github.com/godotengine/godot/assets/1362179/a46014be-f8f7-4b07-a29d-1ae80032879a)

---

Here are the steps I followed to create the sample project:

1. Create a new 3D scene
2. Add environment lighting, etc
3. Add a `StaticBody3D` node, and add a box collision shape
4. Open Blender, export the default cube as `.obj` into the Godot project directory
5. Add a `SoftBody3D` node, and load the mesh imported from the `.obj` as the softbody's collision mesh
6. Add a `Camera3D` node
7. Tweak the static body's collision shape, the softbody's position, and the camera's position so you can see what happens

### Minimal reproduction project

[SoftbodyTest2.zip](https://github.com/godotengine/godot/files/13194348/SoftbodyTest2.zip)

**Comment by rpgshooter** [comment]
Confirmed, with godot version Beta-4.2x,
Minimal repo project does not load,
the recreation shows an issue with array objects and none with godot generated objects.
Recreated Project:
[SoftBodyBug.zip](https://github.com/godotengine/godot/files/13199169/SoftBodyBug.zip)

**Comment by clayjohn** [comment]
Looks like another regression from the new mesh compression work. You can work around this issue for now by selecting "force disable compression" in the input settings for the .obj
