### ISSUE TITLE
EnetMultiplayerPeer only connect on localhost (Not LAN or Remote)

### ISSUE THREAD

**Issue by outercloudstudio** [godotengine/godot#84098]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 Threads)

### Issue description

# When it works
- Running two instances on the same computer. The port set to `8080`. The address set to `127.0.0.1`
- Running two instances on the same computer. The port set to `8080`. the address set to `192.168.86.37` (My local IPv4)

# When it doesn't work
- Running a server on my computer, and having another computer on the same wifi connect to `192.168.86.37`. The port is still set to `8080`
- Running a server on my computer and having another computer on another wifi network connect to my remote IP. The port is still set to `8080`

I expect situation 1 and 3 to work. It is interesting that 2 works as well I did not expect that. Scenario 4 should work but I may only have 8080 forwarded to TCP and not UDP.

An interesting thing, may be relevant, is when running the application the following error shows in the console on start:
```
ERROR: .NET: Failed to load hostfxr
   at: (modules/mono/mono_gd/gd_mono.cpp:388)
```

Also, while this could be an issue on my end with my router, I've made multiplayer games with Unity in the past and done custom networking with C# and scenarios like this have worked in the past so, while possible, I don't think it is my router.

### Steps to reproduce

1. Adjust `DEFAULT_SERVER_IP` in `manager.gd` to use your own local computer ip. You can find this on windows by doing `ipconfig`.
2. Build the project to whatever platform you have access to
3. Send the build to another machine on the same network
4. Click host on your machine.
5. Click join on the other machine.
6. Observe that on peer connected is never called. I assume connection failed would also be called, just didn't include it in the minimal project.

### Minimal reproduction project

[Minimal Networking Project.zip](https://github.com/godotengine/godot/files/13194517/Minimal.Networking.Project.zip)

All code is written in GDscript.

**Comment by Calinou** [comment]
> Scenario 4 should work but I may only have 8080 forwarded to TCP and not UDP.

You need to forward UDP (TCP isn't required), as ENet is UDP-only.

**Comment by outercloudstudio** [comment]
Thank you I will test all of these today. Multiplayer is one of those things where so much could go wrong on my end.

**Comment by outercloudstudio** [comment]
Turns out it was simple a bug with my firewall.
