### ISSUE TITLE
Editor tooltip doesn't show up when hovering if youtube video is running in chrome sometimes

### ISSUE THREAD

**Issue by eterlan** [godotengine/godot#84096]
### Godot version

Godot v4.2.beta (6543495b4)

### System information

Godot v4.2.beta (6543495b4) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Just as title said. Wondering if someone else meets this problem. The problem immdiate disappear if I close the video.

### Steps to reproduce

Open and youtube video in chrome.
Open Godot and hover mouse cursor over any property, there is no tooltip.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/32990.

**Comment by jadoc** [comment]
Is it possible that this was fixed by #95846? Does someone want to test?

**Comment by AThousandShips** [comment]
Can someone confirm? I couldn't confirm this originally so can't confirm it fixed either

**Comment by AThousandShips** [comment]
Assuming fixed, if someone can still replicate please comment here
