### ISSUE TITLE
Operator Precedence Error in GDScript

### ISSUE THREAD

**Issue by buraksaruhan** [godotengine/godot#84095]
### Godot version

4.1

### System information

Win11

### Issue description

I'm trying to generate some random numbers within an area.

```
	var x=414.5
	var firstNum = 1/2*x
	var secondNum = 0.5*x
	assert(firstNum == secondNum)
```

Should literally have the same mathematical outcome according to the operator precedence.
But it doesnt.

### Steps to reproduce

Run the following gdscript

`	var x=414.5
	var firstNum = 1/2*x
	var secondNum = 0.5*x
	assert(firstNum == secondNum)`

### Minimal reproduction project

Run

`	var x=414.5
	var firstNum = 1/2*x
	var secondNum = 0.5*x
	assert(firstNum == secondNum)`

**Comment by TilakChad** [comment]
@buraksaruhan `firstNum` would be evaluated to 0 due to integer arithmetic. Try writing `var firstNum = 1.0 / 2 * x`.
So its not an issue in GDScript. 

Also, floating point numbers should not be compared for equality. It would be better to compare them for approximate equality.
