### ISSUE TITLE
There is no maximum size for script custom icon in the Inspector

### ISSUE THREAD

**Issue by CrayolaEater** [godotengine/godot#84090]
### Godot version

4.1.1

### System information

Windows 11 pro - Vulkan (Forward +) - GPU AMD RX 7900 XTX - monitor Alienware AW3423DWF

### Issue description

Right now when exporting a variable of a type that holds a custom icon, that icon will take the whole available space inside the inspector.
![image](https://github.com/godotengine/godot/assets/38570835/263e46a2-081a-44ca-b9d7-83e6dfe3e3ed)
This is because the actual image is way bigger and its not scaled down.

### Steps to reproduce

Just open the reproduction and click on the Node2 and look in the inspector.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13194119/test.zip)

**Comment by Calinou** [comment]
This appears to be fixed in `master` since yesterday thanks to https://github.com/godotengine/godot/pull/84011.

![image](https://github.com/godotengine/godot/assets/180032/5067e8a5-3839-4a50-9ff3-4f22be685469)
