### ISSUE TITLE
Android release does not allow for decimal values on number or decimal type virt keyboard when using line edit with RegEx

### ISSUE THREAD

**Issue by GoldenReverie** [godotengine/godot#84091]
### Godot version

4.1.2 stable

### System information

Fedora 38 - 4.1.2 stable - compatibility - Android 13 Color OS 

### Issue description

Android release does not allow for decimal values on number or decimal type virt keyboard when using line edit with RegEx. when the keyboard type is set to default this functions correctly.

Not raised a bug request before so please explain if any additional information is required thanks.

### Steps to reproduce

using the attached minimal reproduction project as per below. Deploy to android platform and test the two boxes. Either should accept number but not  character values a-z however the decimal on the number virtual keyboard will not produce a decimal when the default will. (My export is based on target 33 and my phone is using Android 13 Color OS)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13194101/test.zip)

Project will need to be compiled into an android file to test I cannot include due to size restrictions  (26mb file) and security concerns for the sake of QA.

**Comment by fravan** [comment]
I can confirm having the same issue, with target 33 and an Android 13 phone.
I'm on PopOS with a very fresh install this morning of every android sdk and tools.

It seems to be a general bug and not related to the RexEx part.

My setup is very simple : 
- A line edit with default keyboard allows to write anything down
- A line edit with Number or Decimal virtual keyboard does not

The number virtual keyboard shows the number as well as the following operators / signs: `[",", "+", "-", "*", "."]`.
Only the `-` and `+` are doing something, ONLY when the line edit is empty. So i can enter "+6" or "-6" but not "6.0" no "6-5".
The dot and the comma does not do anything as well as the multiplier.

The backward and enter keys are functioning as usual.

I was expecting to have to handle the parsing of the final string, as-in : the input would take anything the user types, `6.0+5*3-+` and then it is up to me to handle what to do with it.

I began with a SpinBox component which already handles that but it looks there are no ways to choose the virtual keyboard on that node and thus it defaults to the full keyboard which I cannot use (accounting app with lots of numeric input fields)

**Comment by Calinou** [comment]
> I began with a SpinBox component which already handles that but it looks there are no ways to choose the virtual keyboard on that node and thus it defaults to the full keyboard which I cannot use (accounting app with lots of numeric input fields)

It sounds like SpinBox should always use numeric virtual keyboard type in the first place. It is possible to enter expressions in a SpinBox that use letters, but it's very unlikely on Android especially without a hardware keyboard connected.

**Comment by 1974LIO** [comment]
4.1.2 same issue. Is there a fix for that ?

**Comment by MarkoGrbec** [comment]
Uhm just wanted to report a bug but I see it has been closed.

Anyway on:
4.4Dev-7

This is still there.
I simply cannot type decimal if keyboard is decimal.
On android

**Comment by Alex2782** [comment]
@MarkoGrbec: On which hardware exactly and which Android version?

------------

It is operating system dependent. I couldn't find a solution on older Samsung Android devices: https://github.com/godotengine/godot/pull/86619#issuecomment-1873425766

... except use the gboard app from Google: https://github.com/godotengine/godot/pull/86619#issuecomment-1872545310

Maybe Samsung also has its own apps and only an update is necessary.
