### ISSUE TITLE
AnimationPlayer negative values of tracks are rounded inconsistently for both update modes

### ISSUE THREAD

**Issue by issork** [godotengine/godot#84106]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

After updating to 4.2.beta3, some animations in my project using the z_index broke. The z_index is no longer set on nodes if it is negative when the animation is playing.

Further investigation showed that compared to the version I previously used (4.2.dev5), the continuous update mode now rounds values differently, resulting in negative values always being off by 1.

![image](https://github.com/godotengine/godot/assets/12477395/6b7aa629-cf7f-4353-9d8f-08f7905c6000)

### Steps to reproduce

I don't have steps to reproduce it from an empty project, as the issue is inconsistent. Animations being added/removed changes the behavior sometimes, which is why these steps assume you are using the MRP below.

1. Play the 'walk_right' animation of the ArmLPlayer
- the z_index of the ArmL node does not change to -1 in either update mode

2. Play the 'walk_left' animation of the ArmRPlayer
- the z_index of the ArmR node changes to -1 in discrete update mode but not in continuous update mode

### Minimal reproduction project

[AnimPlayerMRP.zip](https://github.com/godotengine/godot/files/13207354/AnimPlayerMRP.zip)

Play the animation of the AnimationPlayer, the z_index value of the Sprite does not change.

**Comment by jsjtxietian** [comment]
Using the current master will give this error when open the animation tab:
```
Node not found: "Icon2:z_index" (relative to "/root/@EditorNode@17151/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@62/@VBoxContainer@63/@PanelContainer@110/MainScreen/@CanvasItemEditor@9493/@VSplitContainer@9312/@HSplitContainer@9314/@HSplitContainer@9316/@Control@9317/@SubViewportContainer@9318/@SubViewport@9319/Node2D/Icon2").

scene\animation\animation_mixer.cpp:635 - AnimationMixer: 'new_animation', couldn't resolve track:  'Icon2:z_index'.
```

**Comment by issork** [comment]
Updated the MRP with the scene taken directly from my current project, removing all unnecessary resources.

[AnimPlayerMRP.zip](https://github.com/godotengine/godot/files/13206374/AnimPlayerMRP.zip)

**Comment by issork** [comment]
And now I noticed that if I set the z_index in the MRP to -2, it is actually being set to -1.  It always seems to be off by 1 for negative values.

**Comment by AThousandShips** [comment]
Unsure how this should be approached, the continuous mode doesn't seem logical for an `int` variable, so unsure what to consider this

**Comment by issork** [comment]
This definitely needs more testing. After changing the update mode to discrete for every single track, the right arm now does work, but the left arm no longer does. The rounding seems to be very inconsistent for any update mode. For some nodes it works, for others it does not, even with same values.

The right arm animation player only works with discrete update mode, the left arm only works with continuous.

Will try to replicate this in the MRP and update it and the title again.

**Comment by akien-mga** [comment]
Part of #83401 (CC @TokageItLab).

**Comment by issork** [comment]
[AnimPlayerMRP.zip](https://github.com/godotengine/godot/files/13207104/AnimPlayerMRP.zip)

Here's the MRP, it behaves a little different than in my main project, which means it might behave different for you as well.

Playing the 'walk_right' animation in the ArmLPlayer AnimationPlayer node:
- z_index of the ArmL node does not change to -1 in either update mode

Playing the 'walk_left' animation in the ArmRPlayer AnimationPlayer node:
- z_index of the ArmR node changes to -1 in discrete update mode but not in continuous update mode

Deleting some tracks from the animation player changes this behavior as well, which is why I had to leave all animations inside the project.
