### ISSUE TITLE
LineEdit.right_icon is a Texture2D, but shows dropdown as if it's Texture

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#84104]
### Godot version

Godot v4.2.beta3 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

Godot v4.2.beta3 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/0f7c5bce-0569-4e6a-8fe0-d4d286f112fa)

![image](https://github.com/godotengine/godot/assets/85438892/742fac23-3bde-400b-818e-236641d31e7f)

### Steps to reproduce

Click right_icon on LineEdit

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
This can be changed here:
```
$ rg ADD_PROPERTY.*right_icon
scene/gui/line_edit.cpp
2646:   ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "right_icon", PROPERTY_HINT_RESOURCE_TYPE, "Texture"), "set_right_icon", "get_right_icon");
```

Would be worth checking if other Texture2D properties have a similar issue.

**Comment by BlueCube3310** [comment]
Besides this one, `Decal` and `Sprite3D` have properties like this.
