### ISSUE TITLE
GdScript documentation comments - enums always appear in the help window

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#84119]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Pop!_OS 20.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (CFL GT2) () - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

An enum always appears in the help window, even if it is not preceded by documentation and its name starts with an underscore .

This is not consistent with the behavior of other items.

```
# The below function isn't documented and its name starts with an underscore
# so it will treated as private and will not be shown in the help window.
func _internal() -> void:
	pass
```
Reference for GdScript documentation comments:
https://docs.godotengine.org/en/4.1/tutorials/scripting/gdscript/gdscript_documentation_comments.html

### Steps to reproduce

Create a script `test.gd` with contents:
~~~
enum _A {B, C}
~~~

Press the F1 key or click the Search Help icon, and type the name of the file.

### Minimal reproduction project

N/A

**Comment by quirkylemon** [comment]
2 questions 
should the enum show even if there is no doc comment above it? and should the same thing apply to elements of the enum? eg `enum A {B, _C}` should _C be visible?
