### ISSUE TITLE
Viewport Texture not working with Forward+ on export

### ISSUE THREAD

**Issue by local-interloper** [godotengine/godot#84110]
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2756) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I am using SubViewports and Sprite3D to render a 2D UI in 3D for an ingame device.
![image](https://github.com/godotengine/godot/assets/21021662/0bedd359-d2fd-4eb6-a6ed-e79c6b44a08d)

When running the project in the editor, all works just fine.
![image](https://github.com/godotengine/godot/assets/21021662/dbe69128-d8e6-4e49-b346-0349acd7b2ab)

Upon exporting and running the exported game, all the displays are black.
![image](https://github.com/godotengine/godot/assets/21021662/564a01a3-badb-41b5-a452-47c0675fe8f9)

### Steps to reproduce

1. Create a 3D scene
2. Add a Sprite3D to the scene
3. Create a subviewport
4. Attach some UI elements to the subviewport
5. Set the Texture of the Sprite3D to be a Viewport Texture and make it use the newly created subviewport as as source
6. Build and export it
7. Run it

### Minimal reproduction project

[viewport-texture-issue.zip](https://github.com/godotengine/godot/files/13195833/viewport-texture-issue.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment]
Looks like a duplicate of:
* https://github.com/godotengine/godot/issues/81173

**Comment by local-interloper** [comment]
> Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

The issue still persist on the newest version
![image](https://github.com/godotengine/godot/assets/21021662/df9b872f-85d6-4bb0-b162-72eb4a105865)


> Looks like a duplicate of:
> 
>     * [On Vulkan, Sprite3D with ViewportTexture and SubViewport doesn't work in exported project. #81173](https://github.com/godotengine/godot/issues/81173)

I would agree I will close it

**Comment by local-interloper** [comment]
Duplicate of  #81173
