### ISSUE TITLE
Android Openxr Export fails with 'Attempting to parent and popup a dialog that already has a parent'

### ISSUE THREAD

**Issue by SURA907** [godotengine/godot#84134]
### Godot version

4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.4584) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Some errors occur when exporting openxr demo project to Android
```
  Attempting to parent and popup a dialog that already has a parent.
0 param: --xr_mode_regular
1 param: --use_immersive
  editor/export/editor_export_platform.h:178 - Export: Building of Android project failed, check output for the error. Alternatively visit docs.godotengine.org for Android build documentation.
```

### Steps to reproduce

1. [Setup for export Android](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html#exporting-for-android)
2. Export Android use meta quest

### Minimal reproduction project

In order to be able to upload, I deleted the android build template and openxr loader (version: [v2.0.0-dev3](https://github.com/GodotVR/godot_openxr_vendors/releases/tag/2.0.0-dev3))
[Godot-projects.zip](https://github.com/godotengine/godot/files/13197527/Godot-projects.zip)

**Comment by technobaboo** [comment]
same issue for lynx export for me, no logs I can use to find the real issue that I can see, android sdk installed manually via sdkmanager and stereokit builds correctly

**Comment by SURA907** [comment]
> 对我来说，lynx 导出也有同样的问题，没有日志可以用来查找我所看到的真正问题，通过 sdkmanager 手动安装的 android sdk 和 Stereokit 可以正确构建

I tried using android studio and sdkmanager and got the same output, I don't know where to go to view more detailed logs......

**Comment by technobaboo** [comment]
I figured out it showed in the main build log then the log window disappeared, screen recording and going frame by frame worked to find the real issue.

**Comment by SURA907** [comment]
I successfully build the apk in linux
Looks like I need to clean the jdk and android sdk completely before trying again

**Comment by SURA907** [comment]
@technobaboo I did find the problem this way (a very, very simple little problem) and fixed it quickly

**Comment by SURA907** [comment]
In fact, we can get detailed logs by using powershell to run gradlew.bat under android\build
The few trivial issues that caused the build to fail did come from me, but the flashing build window complicated troubleshooting.
Anyway it's over and I'll close issue
