### ISSUE TITLE
Touch tracking on Android cannot register an initial movement less than many pixels

### ISSUE THREAD

**Issue by AndyAstrand** [godotengine/godot#84138]
### Godot version

v4.1.2.stable

### System information

Android 11

### Issue description

On Android neither InputEventScreenDrag, InputEventMouseMove or get_global_mouse_position() can detect the movement of a touch until it passes a pixel threshold (20+ pixels on minimal project included on my phone)

I'm attempting to have fine control of a screen element on mobile using touch. Specifically for controlling a pick in a lock picking mini-game. Current testing is on Android.

But regardless of the input methods I've tried after pressing on the pick there is no motion until the pick suddenly catches up with the touch once it has moved 20+ pixels from the starting location.

I appreciate this is standard behaviour on drag for a desktop UI but for a game it's not desirable so I went hunting for a setting either globally or specific to the scene that controls the drag threshold and found none. 

I then tried reimplementing using _input instead of _gui_input, I tried responding to InputEventMouseMove directly rather than the drag event. Eventually I put a call to get_global_mouse_position() in the process() function. But all show exactly the same behaviour. Although the InputEventScreenTouch event gives a precise location on touch and release, no Move or Drag events occur until the touch is moved by many pixels. Even get_global_mouse_position() shows no change in position until the touch has moved the same number of pixels.

This seems to mean fine touch control of a screen element is impossible on Android at the moment with Godot 4.
I'm hoping I'm missing something.

I can see there have been previous issues with people talking about a drag "lag" but this seems to be a different issue.

### Steps to reproduce

In the minimal reproducible project below, run the project on desktop, click on the white square and move the mouse.
The labels will register the relative movement of the mouse when movement was detected either using motion events, drag events or get_global_mouse_position(). On desktop this will immediate and can show motion of +/- 1 pixel.

Run the same project on Android and the labels will not register any motion until the touch has moved a significant distance.

### Minimal reproduction project

[BugReport.zip](https://github.com/godotengine/godot/files/13197907/BugReport.zip)

**Comment by GrandioseCoder23** [comment]
I had the same issue when i tried to make joysticks. As we all know, a joystick commonly detects when there's a simple touch or a drag inside itself. When i apply a slight drag on any space of the screen the game doesn't detect the drag until i move it a few more pixels, as a consequence i have to apply large drags into my joystick to make it detects the motion. I thought that issue was a problem of my phone.

**Comment by Alex2782** [comment]
`_unhandled_input`
https://github.com/godotengine/godot-demo-projects/blob/master/mobile/multitouch_view/TouchHelper.gd

I try to debug it in the next days, also under `_unhandled_input` 'InputEventScreenDrag' is triggered very late. When I move the finger very slowly I see in the demo app "multitouch_view" that the finger has to travel a certain distance first before 'InputEventScreenDrag' is always triggered even at smaller distances. 


`InputEventScreenDrag` is not generated directly on Android. 
Android Studio finds only on iOS, Linux, Web and Windows.
![Bildschirmfoto 2023-11-01 um 00 48 57](https://github.com/godotengine/godot/assets/41921395/46782263-d99c-40cd-9c4b-4adaf08c2a06)
