### ISSUE TITLE
`Expression` class always evaluates `if` expressions as true

### ISSUE THREAD

**Issue by runny-yolk** [godotengine/godot#84131]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3742) - AMD Ryzen 7 3800X 8-Core Processor (8 Threads)

### Issue description

When executing an `if` expression with the `Expression` class, it ignores the condition and just always considers it true. Apologies if this is a duplicate, I did look to see if it was and couldn't find it, but "expression", "class" and "if" are the keywords, and they're all very common words 😅 

### Steps to reproduce
In GDscript:
```
var e = Expression.new()
e.parse("1 if false else 0")
print(e.execute()) # running this code via Expression prints 1
print(1 if false else 0) # run normally, prints 0
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
The `if` ternary is not supported in the `Expression` so please check if the `parse` method returns an error

**Comment by runny-yolk** [comment]
> The `if` ternary is not supported in the `Expression` so please check if the `parse` method returns an error

`parse` does not return an error, it returns `OK`. Do you know why Expression doesn't support this? I'll add a note about it to the docs so other people can avoid this problem

**Comment by AThousandShips** [comment]
It's simple, it doesn't support complex operations, just simple expressions:
> An expression can be made of any arithmetic operation, built-in math function call, method call of a passed instance, or built-in type construction call.

Doesn't say anything there about the ternary

**Comment by runny-yolk** [comment]
Ah, gotcha. It's kind of unintuitive that an `Expression` and a GDscript expression are different things - personally, I skipped over that bit of the documentation because I thought "I know what an expression is", lol. 

I think it would be good to have an info/warning box that explains this to people, so I'll open a PR for the docs regarding this change. Thanks for the help!

**Comment by AThousandShips** [comment]
> It's kind of unintuitive that an Expression and a GDscript expression are different things

I don't think this assumption of similarity follows, but some clarification could be fone

**Comment by runny-yolk** [comment]
Fair. I also think that `parse` should probably return an error code and log an error in this scenario, but I'm not sure if I should re-open this issue for that or open a new one?

**Comment by AThousandShips** [comment]
I think there's possibly an error in the parsing, but the documentation clearly states what is supported so I don't think clarifying what *isn't* supported is required

**Comment by AThousandShips** [comment]
There's an issue tracking this already:
* #73816

**Comment by runny-yolk** [comment]
> I think there's possibly an error in the parsing, but the documentation clearly states what is supported so I don't think clarifying what _isn't_ supported is required

The way I understood that part of the docs was that it was trying to differentiate "an expression" in general (as distinct from "a statement"), rather than making clear "this class only supports a subset of GDscript expressions", and I think given that it uses the same syntax and globals as GDscript, and similar functionality in other languages (such as python/JS "eval") supports all the expressions that language supports, assuming that GDscript is the same isn't unreasonable. And based on the fact that there are multiple issues about this, and multiple proposals about expanding the functionality of `Expression`, it's not an uncommon assumption, either.

This also isn't helped by the fact that the documentation doesn't provide a complete list of what `Expression` supports - for example, `<`, `>`, `&&`, `and`, `||`, `or`, operators are all supported but not listed, so it's not unreasonable to think that the class may support other things that GDscript supports that aren't explicitly listed.

**Comment by AThousandShips** [comment]
Sure, but the ternary operator is not a `mathematical expression`, but the list of supported operators should be updated
