### ISSUE TITLE
Window width / height set drag min / max

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#8413]
![image](https://cloud.githubusercontent.com/assets/4741886/25063982/da70792c-21f0-11e7-8e83-4a66fb971371.png)

Master 3.0

**Comment by akien-mga** [comment]
A *slightly* more verbose issue description would be nice, it took me 10 s to understand what the issue was. It should have taken 0.5 s.

**Comment by Melix19** [comment]
This should be done with all the project settings parameters. But I think it would be better remove the sliders completely.

**Comment by bojidar-bg** [comment]
You mean you don't have a 1201904639 x 2136719359 (16:9) display? :smile:

**Comment by Melix19** [comment]
The problem is that you can set the resolution (and other parameters) to negative numbers, like -1280 x -720 and this sometimes produces weird glitches.

**Comment by AlexHolly** [comment]
#9431
