### ISSUE TITLE
Attempting to parent and popup a dialog that already has a parent.   editor/export/editor_export_platform.h:178

### ISSUE THREAD

**Issue by Ziizfak** [godotengine/godot#84147]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I creat .apk its run. But when i try aab every time after start creating is freez and wqrite me this.
Attempting to parent and popup a dialog that already has a parent.   
editor/export/editor_export_platform.h:178
![image](https://github.com/godotengine/godot/assets/131471900/6e06f357-554d-4a1f-b148-b87963f7927a)
I try look on JAVA_HOME all is fine.
I check names folders all fine.
JDKopen 11 key generate 

### Steps to reproduce

Problem with export to AAB format

### Minimal reproduction project

Problem with export to AAB format

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/84134

**Comment by Ziizfak** [comment]
> See also:
> 
> * [Android Openxr Export fails with 'Attempting to parent and popup a dialog that already has a parent' #84134](https://github.com/godotengine/godot/issues/84134)

I try this too and didnt work for me.

**Comment by Ziizfak** [comment]
I think this is my problem 

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html
Process command line: C:\Program Files\Eclipse Adoptium\jdk-21.0.1.12-hotspot\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx4536m -Dfile.encoding=UTF-8 -Duser.country=CZ -Duser.language=cs -Duser.variant -cp C:\Users\Zden?k\.gradle\wrapper\dists\gradle-7.4.2-bin\48ivgl02cpt2ed3fh9dbalvx8\gradle-7.4.2\lib\gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Please read the following process output to find out more:
-----------------------
Error: Could not find or load main class org.gradle.launcher.daemon.bootstrap.GradleDaemon
Caused by: java.lang.ClassNotFoundException: org.gradle.launcher.daemon.bootstrap.GradleDaemon


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Exit Code: 1

**Comment by akien-mga** [comment]
You're using JDK 21, not JDK 11: `C:\Program Files\Eclipse Adoptium\jdk-21.0.1.12-hotspot\bin\java.exe`

You should set your `JAVA_HOME` to point to your installation of JDK 11.

Note that the error about the popup is just an editor bug, not related to the failing Android export.
