### ISSUE TITLE
Editable Children cannot be drag-and-dropped into "@export var"s

### ISSUE THREAD

**Issue by jonathandw743** [godotengine/godot#84144]
### Godot version

4.1.2

### System information

Windows 10 - Godot v4.1.2 - Forward+

### Issue description

You can't drag and drop nodes that are in a scene, but editable as editable children cannot be dragged and dropped into the assign boxes created by "@export var".

### Steps to reproduce

create a "new scene" and add a new sub node.
go back into the main scene and add that "new scene "to it
then create a new node in the main scene and attatch a script.
in the script write @export var x: Node (or whatever type of node it was)
then select editable children on the "new scene"
try and drag and drop the sub node in the "main scene" into the assign box
it doesn't work
however clicking assign and selecting the sub-node does work

### Minimal reproduction project

[sdfdsf.zip](https://github.com/godotengine/godot/files/13198455/sdfdsf.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by KoBeWi** [comment]
Confirmed in 4.2.
Editable children are not draggable to prevent moving them in scene.

**Comment by jonathandw743** [comment]
> Confirmed in 4.2. Editable children are not draggable to prevent moving them in scene.

Not withing the scene, I mean from the node tree to the inspector.

**Comment by AThousandShips** [comment]
That's the same issue, they are prevented from drag-dropping for that reason which is to prevent moving them but also causes this

**Comment by jonathandw743** [comment]
> Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

This issue exists in 4.1.2 aswell

**Comment by jonathandw743** [comment]
Just to clarify, I don't think that the editable children should be able to be dragged and dropped in the node screen.
But they should be able to be dragged and dropped into the assign boxes (`@export var`) in the inspector.
