### ISSUE TITLE
Developing plugin in c++ sometimes make script mandatory, or require godot-code change

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#8415]
**Operating system or device - Godot version:**
2+

**Issue description:**
Some functions only use script-methods, the equivalent in C++ is missing.
So when developing a plugin in c++ only, 
this requires workarounds like generating a script by code or manipulate godot-code

example:
It is not possible to select a spatial derived object (by raycast) in the spatial editor, if the editor_plugin is done in C++ and the object is not one of the "built-ins".

**Expected**
all builtin-functions avail to scripting, should be avail to c++ too.
for this example:
maybe a virtual method similar to EditorPlugin::create_spatial_gizmo(..) 
which is called prior to "script"-solution.
or even better add a virtual method get_gizmo_type to spatial itself.

**Link to minimal example project:**
some detail to the above example:
workaround 1 (generate script in c++, so this works):
```
Ref<SpatialEditorGizmo> EditorPlugin::create_spatial_gizmo(Spatial *p_spatial) {
	//??
	if (get_script_instance() && get_script_instance()->has_method("create_spatial_gizmo")) {
		return get_script_instance()->call("create_spatial_gizmo", p_spatial);
	}

	return Ref<SpatialEditorGizmo>();
}
```
workaround 2 (edit godot code, my favorite solution):
one could add a virtual function to EditorPlugin and override it in the custom plugin
then call it in create_spatial_gizmo prior to script search.

workaround 3 (worst one, the whole method is unlucky design)
append the custom spatial to the case list of `SpatialEditorGizmos::get_gizmo(Spatial *p_spatial)`

**Comment by CharlesWoodhill** [comment]
sorry, it seems this is more a question than an issue...

**Comment by bojidar-bg** [comment]
BTW, related to #7779
