### ISSUE TITLE
Godot crashes on startup after Windows 10 Creator update

### ISSUE THREAD

**Issue by BE-NeverGames** [godotengine/godot#8416]
**Operating system or device - Godot version:** Windows 10 Creator Update - Both Godot 2.1.3 and 3.0 Alpha

**Issue description:** My decision to upgrade to Windows 10 Creator was a mistake for sure but I can at least report this issue now. After I updated Windows 10, Godot crashes on the startup immediately, It doesn't even reach the project manager. Unfortunately the console does not print any errors either. Both the stable and the master branch seem to be affected.

**Steps to reproduce:** I am not sure if it happens for everyone but the issue pretty much started after I updated to Windows 10 Creator. I can imagine this is not something anyone wanted to read today...

![yay](https://cloud.githubusercontent.com/assets/18212852/25065141/ec4c671e-2209-11e7-9e3a-aa4b7ac2993c.png)

**Comment by BE-NeverGames** [comment]
Actually, on second thought, does this issue even belong here? It is likely that this can't even be fixed in Godot, it is probably on Microsoft to fix this. I may have been a bit fast with creating this issue.

**Comment by 20kdc** [comment]
It could be either. I'd expect Microsoft to blame Godot at first no matter what, and I'd expect Godot to either fix the issue with their code or trace it back to Microsoft who would deny they were at fault.

**Comment by BE-NeverGames** [comment]
Alright, I guess we can close this already. They just realeased a patch which apparently fixed the problem. Godot seems to work again, we don't need to worry about this :)
