### ISSUE TITLE
get_global_mouse_position() updates delayed after initial tap

### ISSUE THREAD

**Issue by Baryonics** [godotengine/godot#84182]
### Godot version

v4.1.2.stable.official [399c9dc39], v4.2.beta3.official [e8d57afae]

### System information

Android, Galaxy Tab S6 Lite

### Issue description

Hey all,

I have encountered a weird bug on android. I want to make a handwriting app. But when it comes to drawing, weird stuff happens:

When touching and drawing with the pen, `event.position`, `get_global_mouse_position()` and `get_viewport().get_mouse_position()` return the correct position of the event, but while dragging, the next position has a 12px position from the initial tap. After that, the position updates just fine. This is't ideal for handwriting obviously.

This happens in godot 4.1.2 and 4.2 beta (using the beta, because some tablet stuff got optimised there)

The Tablet is a Samsung Galaxy Tab S6 Lite and it juses the non-bluetooth S-Pen (I'm affraid that it could be caused by the non active - active Pen type)

I don't have any additional devices for testing though.

### Steps to reproduce

- Just create a new Project on either 4.2 or 4.1.2
- Create Node2D and attach script below
- Debug on Android (won't work for 4.2 because the android debugger is not working currently see [this Issue](https://github.com/godotengine/godot/issues/82764#issue-1925350903)

### Minimal reproduction project

This is the Script that shows the problem. You can see the 12.xx px distance from the first position there. (zipped project bigger than 25MB)

```
extends Node2D
var activeLine = null
var dist_to_last: float
var last_mouse_pos = Vector2(0,0)
var current_mouse_pos = Vector2(0,0)

func _process(delta):
	if Input.is_action_pressed("mouse_click"):
		current_mouse_pos = get_global_mouse_position()
		dist_to_last = (current_mouse_pos - last_mouse_pos).length()
		if dist_to_last > 1:
			print(dist_to_last)
		last_mouse_pos = current_mouse_pos
```

**Comment by Alex2782** [comment]
i tried PR #84331, the changes are smaller in my test project on tablet and 'stretch' mode
`if dist_to_last > 0.1:`

![image](https://github.com/godotengine/godot/assets/41921395/8101415a-6746-4347-91f4-80a484d3bf20)
