### ISSUE TITLE
Vulkan: VoxelGI reflections appear to jitter when the camera rotates

### ISSUE THREAD

**Issue by krazyjakee** [godotengine/godot#84184]
### Godot version

4.1.2-stable

### System information

Windows 11 - Godot v4.1.2.stable - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 3090 (nvidia, 545.92) - AMD Ryzen 9 5900X 12-Core Processor 3.70 GHz

### Issue description

https://github.com/godotengine/godot/assets/623463/e88aea3e-3db2-4422-8e12-1a4e893f0ff0

Using voxelGI or reflectionprobe results in the reflected image stuttering when the camera rotates.

### Steps to reproduce

- Run a scene with voxelgi or reflection probe enabled
- Rotate the camera

### Minimal reproduction project

[godot-reflection-stutter-bug.zip](https://github.com/godotengine/godot/files/13204944/godot-reflection-stutter-bug.zip)

**Comment by krazyjakee** [comment]
Similar to https://github.com/godotengine/godot/issues/74633 except this issue is for reflections in general and not SDFGI related.

**Comment by Calinou** [comment]
This issue doesn't occur with reflection probes or environment lighting, only with VoxelGI and SDFGI. I renamed this issue accordingly as https://github.com/godotengine/godot/issues/74633 already tracks this with SDFGI.

**Comment by krazyjakee** [comment]
> This issue doesn't occur with reflection probes or environment lighting, only with VoxelGI and SDFGI

Incorrect. You can recreate this issue with any kind of 3D reflection in Godot along-side SDFGI. You can see a deeper description of the issue and potential fixes here: https://github.com/godotengine/godot/issues/74633#issuecomment-1795864044

> In the meantime, increase material roughness or use a normal map to make this less noticeable.

There are no configurations that are able to even slightly reduce the janky light movement on the objects when the camera is rotating, no matter how rough the surface is or what normal map is applied.

> VoxelGI/SDFGI reflections aren't ideal for mirror-like surfaces given the lack of detail in the reflection anyway.

What about the simple goal of **any** kind of reflection? Just a basic light reflection or something? Currently all known examples with SDFGI exhibit this issue.

**Comment by WickedInsignia** [comment]
That second point is exaggerating things a bit: a highly textural normal map or increasing roughness (especially beyond 0.5) does mask the jittering on both SDFGI and VoxelGI. This issue only really appears on very smooth surfaces with minimum roughness or very little map detail to diffuse the result.

You can get semi-reflective materials to a usable point, but highly reflective smooth materials will show the jitter along with the banding that VoxelGI exhibits [HERE](https://github.com/godotengine/godot/issues/50842).

This is an issue, but it's not quite so bad that glossy/reflective materials can't be used at all. Just not mirror-like or near mirror-like materials.
