### ISSUE TITLE
Regression: GPUParticles2D turbulence no longer works in 4.2

### ISSUE THREAD

**Issue by Novark** [godotengine/godot#84188]
### Godot version

v4.2.beta3.official

### System information

Windows 11 [Vulkan (Forward+)]

### Issue description

Recent particle improvements seem to have introduced a regression to particle turbulence behaviour when moving from 4.1 to 4.2.

The breaking change can be observed from 4.1.beta3 to 4.2.beta1, and the issue is still present in the latest 4.2.beta3.

Related Issues: #83607

### Steps to reproduce

Reproduction is pretty straightforward:

1. Make a GPUParticles2D node
2. Bump up the particle count for visibility (I used 1000)
3. Set gravity acceleration to 0
4. Set spawn velocity to 100, and spread to 180
5. Enable turbulence and just play around with the parameters - the behaviour is all over the place, and I wasn't able to create any turbulence

### Minimal reproduction project

[ParticleTurbulenceBug_v4.2.beta3.zip](https://github.com/godotengine/godot/files/13205925/ParticleTurbulenceBug_v4.2.beta3.zip)

**Comment by AThousandShips** [comment]
> No reproduction project necessary to observe issue.

Would appreciate if you provided one to make it easier for people to test it without having to set things up (and avoid confusion if your steps aren't clear enough for some)

**Comment by Novark** [comment]
> > No reproduction project necessary to observe issue.
> 
> Would appreciate if you provided one to make it easier for people to test it without having to set things up (and avoid confusion if your steps aren't clear enough for some)

Sure - I've attached a simple reproduction example to my original post.

**Comment by clayjohn** [comment]
Thanks for the report! 

I checked your MRP against 4.1.1, 4.2-beta3, and master and I can confirm that the bug exists in beta3 but not in master. It was most likely fixed by https://github.com/godotengine/godot/pull/84103

The fix will be in 4.2-beta4 which we intend to make shortly.
