### ISSUE TITLE
Gradle daemon process fails starting for user with non-ascii user name on Windows

### ISSUE THREAD

**Issue by Ziizfak** [godotengine/godot#84196]
### Godot version

3.5 and 4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Build .apk is ok in 4,1,2 and 3,5 but when i try .aab in bouth every time i get this. I try use JDK 11 also 21 nothink work. 
I set JAVA_HOME. Try change  gradle for 8,4 version. I wqatch 4Hrs videos in youtube and nothink work.

in program report is C:\Users\Zden?k\.gradle\wrapper\dists\gradle-7.4.2.......    But i am from czech and my user is Zdeněk can be this problem?

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
```
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html
Process command line: C:\Program Files\Eclipse Adoptium\jdk-11.0.21.9-hotspot\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx4536m -Dfile.encoding=windows-1252 -Duser.country=CZ -Duser.language=cs -Duser.variant -cp C:\Users\Zden?k\.gradle\wrapper\dists\gradle-7.4.2-bin\48ivgl02cpt2ed3fh9dbalvx8\gradle-7.4.2\lib\gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Please read the following process output to find out more:
-----------------------
Error: Could not find or load main class org.gradle.launcher.daemon.bootstrap.GradleDaemon
Caused by: java.lang.ClassNotFoundException: org.gradle.launcher.daemon.bootstrap.GradleDaemon
```

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Exit Code: 1

### Steps to reproduce

idk

### Minimal reproduction project

idk

**Comment by Ziizfak** [comment]
I try remove folder .grandle and same result

Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.4.2!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html
Process command line: C:\Program Files\Eclipse Adoptium\jdk-11.0.21.9-hotspot\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx4536m -Dfile.encoding=windows-1252 -Duser.country=CZ -Duser.language=cs -Duser.variant -cp C:\Users\Zden?k\.gradle\wrapper\dists\gradle-7.4.2-bin\48ivgl02cpt2ed3fh9dbalvx8\gradle-7.4.2\lib\gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Please read the following process output to find out more:
-----------------------
Error: Could not find or load main class org.gradle.launcher.daemon.bootstrap.GradleDaemon
Caused by: java.lang.ClassNotFoundException: org.gradle.launcher.daemon.bootstrap.GradleDaemon


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Exit Code: 1

**Comment by Ziizfak** [comment]
OK i find solution.

Its about EN. You cant have windows user name in your nation name as me in Czech my name is Zdeněk but when i use letter ě its bug this because godot understand only EN letters.

I must creat new windows user profile and now work. 

Ok you can close and archive for another foregin speak ppl.

**Comment by akien-mga** [comment]
This is likely a Gradle bug and not something we can fix. There are a lot of issues about this in the Android ecosystem, e.g. https://stackoverflow.com/questions/32171968/your-project-path-contains-non-ascii-characters-android-studio

@m4gr3d Is there a config option for gradle to fix the encoding it uses for paths on Windows? Or is that a known/documented "wontfix" on the Gradle side that we should link in our documentation?

**Comment by m4gr3d** [comment]
> This is likely a Gradle bug and not something we can fix. There are a lot of issues about this in the Android ecosystem, e.g. https://stackoverflow.com/questions/32171968/your-project-path-contains-non-ascii-characters-android-studio
> 
> @m4gr3d Is there a config option for gradle to fix the encoding it uses for paths on Windows? Or is that a known/documented "wontfix" on the Gradle side that we should link in our documentation?

@akien-mga Looks like using [`android.overridePathCheck=true`](https://stackoverflow.com/a/45771251) to `gradle.properties` should solve the issue.
