### ISSUE TITLE
TileMap editor background visibility issues

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#84192]
### Godot version

4.2 beta3

### System information

windows 10 vulkan

### Issue description

tileMap editor backgroud takes a long time in selecting shadow or light tiles... 
This happens because its hard and very confusing to the eyes.

A simple tile brick wall and a shadow
![tileShad2](https://github.com/godotengine/godot/assets/77213594/c2c927b6-b5bc-40c5-ad86-b6db3540eb7b)

Now combine the two
![tileShad3](https://github.com/godotengine/godot/assets/77213594/950a8b5a-7ff5-4196-b785-30cfe086be50)

Now in godot
![tileShad](https://github.com/godotengine/godot/assets/77213594/957ad9be-e68e-4612-a750-99cac35ac453)

Can you find the tiles for the shadow in TileMap zz_shadows.png ?
there is a way to do it, opening windows image preview and see were it is...

theres no option in the editor to change the background color or image, 
and in this image the black and grey squares get smaller when zooming in and bigger when zooming out, making it even more dificult to search.. ?!? 
Also the empty spaces in the tile seem to be 50 alpha

### Steps to reproduce

make a tileset node
add an image with black shadows or white lights

### Minimal reproduction project

na

**Comment by jonSP12** [comment]
great... so none will do this ?
Its a simple option in the editor, a plugIN could easly do this

![gridColor](https://github.com/godotengine/godot/assets/77213594/93242605-ecd3-4977-9837-b69a34845b10)

Ive been messing with plugINs and its very hard, to understand. I will end up more burned than what iam already am.
Someone popular from the godot chat, who has access to the dev's explaining them this things, could easly do this in 20min...

**Comment by synalice** [comment]
The color you may need to set can vary from Atlas to Atlas. Do you think it would be better to add this _background-color-picker-thingy_ right inside the TileMap? Somewhere in the right bottom corner, maybe?

![image](https://github.com/godotengine/godot/assets/61655860/127914fb-2e8d-4061-a0e4-198ce311aa91)

You would be able to see if the color is good for you right away. I think going into the Editor Settings every time would not be very convenient.

(sorry in advance for the ping)
While I'm here. Who may I ping with questions like these? Or should I avoid pinging altogether?
@AThousandShips, @Calinou, @YuriSizov.

**Comment by AThousandShips** [comment]
Avoid pinging unless you know someone who is likely to have an answer, otherwise it's mostly annoying and unhelpful

**Comment by jonSP12** [comment]
Color looks good, if the user can change it later on even better. Its getting close to the tiled editor.
I stumble on editor plugINs and saw a function to add options in the editor, i just dont know the tileSet works... I Problably would've not be able to do this. Thanks.

**Comment by akien-mga** [comment]
For the record, I closed this on behalf of the Code of Conduct team, as the OP was banned due to harassing contributors. They're restricted from further interacting so this issue cannot progress. If someone confirms that the issue is still reproducible, you can open a new issue.
