### ISSUE TITLE
("mods" in inputEvent) always false

### ISSUE THREAD

**Issue by artvel** [godotengine/godot#84195]
### Godot version

4.2.beta3.official [e8d57afae]

### System information

Windows 11

### Issue description

Works fine: `("pressed" in event)` 
 Always false:  ->>> `("mods" in event)` <<<-

I saw that it is not listed in the documentation:
https://docs.godotengine.org/en/latest/classes/class_inputeventkey.html

Maybe it isn't meant to be used from the gdscript lvl but it is being printed out with `print(event)`.
That's why it looks like a bug but maybe it isnt.

Someone who designed the events part should decide how to proceed here.

### Steps to reproduce

`if event is InputEventKey &&  ("mods" in event):`

### Minimal reproduction project

Minimal project not needed as it is simple to reproduce.

**Comment by MrBlockers** [comment]
I think this is because "mods" isn't a property on InputEventKey or any of its ancestor classes as far as I can see in 4.x. Did you find this in the class reference or somewhere else?

**Comment by artvel** [comment]
This is the printout on my Windows 11 machine:
`print(event)` -> `InputEventKey: keycode=67 (C), mods=Shift, physical=false, pressed=true, echo=false`

So it exists but maybe not meant to be used..

**Comment by zaevi** [comment]
This is not a property name. It actually prints the value of `InputEvent.as_text()`.

**Comment by akien-mga** [comment]
It's listing which modifiers are enabled. It's not a property that's directly accessible, but a human-readable summary of which modifiers are enabled. You can check which modifiers are actually enabled with the properties in `InputEventWithModifiers`: https://docs.godotengine.org/en/latest/classes/class_inputeventwithmodifiers.html#class-inputeventwithmodifiers (which is inherited by `InputEventKey`).
