### ISSUE TITLE
The animation in AnimationPlayer is jittering

### ISSUE THREAD

**Issue by vochsmann** [godotengine/godot#84209]
### Godot version

v4.1.3.rc1.official [f80c673cd]

### System information

Godot v4.1.3.rc1 - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000 - Tty - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 620 (KBL GT2) () - Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 Threads)

### Issue description

I'm trying to flip CharacterBody2D in the animation to change the object's direction by changing the value of scale.x to -2.5. However, instead of that, after reaching the scale.x of 0, the image starts to jitter.
Video: 

https://github.com/godotengine/godot/assets/81514669/5e75655e-894d-411b-9a99-c1811c9e1fb8

### Steps to reproduce

Just try adding two keyframes in the AnimationPlayer. The first keyframe with the initial size (for example, 2.5), and the second keyframe with -2.5.

### Minimal reproduction project

N/A

**Comment by issork** [comment]
Does this also happen if you scale just the sprite instead of the physics body? To me this looks like a physics issue due to scaling the shape to a negative width.

**Comment by vochsmann** [comment]
> Does this also happen if you scale just the sprite instead of the physics body? To me this looks like a physics issue due to scaling the shape to a negative width.

Yeah, if I scale just the sprite it scales without errors. But why does this happen?

**Comment by Calinou** [comment]
Do not scale the PhysicsBody itself. Scale its visual representation instead.

> Yeah, if I scale just the sprite it scales without errors. But why does this happen?

Non-uniform scaling of physics bodies and collision shapes is not supported, especially if it involves negative scaling.
