### ISSUE TITLE
Feature request: .= (dot equals) operator.

### ISSUE THREAD

**Issue by piece-o-ham** [godotengine/godot#8421]
When working with vector functions, you will sometimes encounter situations such as the following:

    some_vector = some_vector.floor()

It would be convenient if there was an operator that would simplify such operations in the same way that the += operator does.

    a = a + 5
    # Simplified...
    a += 5

Something similar could be done with the . operator. For example:

    laser_direction = laser_direction.reflect(normal)
    # Becomes...
    laser_direction.=reflect(normal)

**Comment by akien-mga** [comment]
Is there any mainstream programming language with such a feature? It looks pretty confusing to me.

**Comment by avril-gh** [comment]
Its not only very strange syntax. Since `.=` is also allready defined as `string concatenation assignment` in PHP it made me automaticaly read it this way - which confuses me even further.

**Comment by ArcFutahito** [comment]
I remember this from IRC chat. I have no idea how many times I have to tell people a thing is stupid before they understand it's actually stupid.

**Comment by piece-o-ham** [comment]
@akien-mga No. It made sense to me at the time so I thought I'd see what other people think of it. I now see that this issue isn't worth keeping around.

**Comment by bojidar-bg** [comment]
Closing as per comments above.
