### ISSUE TITLE
Drawing anything while Godot is offscreen freezes editor and leaks memory

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#84212]
### Godot version

reproducible in 4.1.2 stable, 4.2.1 stable, 4.2.2 stable

### System information

M1 Mac Mini, macOS Ventura/Sonoma, Forward and Mobile renderer

### Issue description

After porting our game from 3.5 to 4.1.2, I noticed the editor hanging for a long time (spinning beach ball on Mac) when switching back to Godot from other apps/desktops, often for so long I just have to force quit Godot. I found that it's triggered by any tool script drawing anything in _draw(), and also by certain built in nodes that draw extra things in the viewport, such as Path2D. The problem scales with both the amount of things drawn as well as the time Godot is offscreen. This also causes Godot to accumulate memory use while offscreen (_some_ of which seems to be reclaimed after the stall finishes).

The problem only occurs while the editor is not visible at all on the desktop, i.e. _fully_ hidden by other windows, minimized, on another desktop, etc. Also it only happens when using queue_redraw() repeatedly, just drawing once doesn't do it. Applies to both Vulkan renderers, compatibility seems okay. 

Somewhat similar to #64708 and #82769, but reproduced in 4.2 beta 3, so #83096 did not fix this.

### Steps to reproduce

Open (don't run) the MRP scene in editor. Minimize Godot for a minute or two, open Godot, it should be frozen for some time before becoming responsive again.

May only apply on macOS

### Minimal reproduction project

[QueueRedrawBug.zip](https://github.com/godotengine/godot/files/13210100/QueueRedrawBug.zip)

**Comment by stuartcarnie** [comment]
I suspect this is an issue with obtaining the [`nextDrawable`](https://developer.apple.com/documentation/quartzcore/cametallayer/1478172-nextdrawable), which will block until the window is no longer occluded, unless the `allowsNextDrawableTimeout` property is `true`. Even with a timeout, it will still block for 1 second, which could be a cause the hanging you are talking about.

This would require Godot's render loop skips presentation, if the window is fully occluded. Fortunately, this is also fairly easy to check by querying the window's [`occlusionState`](https://developer.apple.com/documentation/appkit/nswindow/1419321-occlusionstate)

**Comment by stuartcarnie** [comment]
![CleanShot 2024-06-28 at 06 44 18@2x](https://github.com/godotengine/godot/assets/52852/7bb4d991-9889-4360-8430-5479b1bd5a1b)

Seems to be an issue in cleaning up buffers in MoltenVK. I don't see the same problem in Metal.

It appears there is a _lot_ of churn allocating and destroying buffers when drawing those polygons.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/100257
