### ISSUE TITLE
Mesh UV Corruption when using SurfaceTool to copy mesh data

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#84228]
### Godot version

4.2-beta3

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

I've been working on mesh combining scripts to "bake" multiple meshes into a single mesh for accelerated rendering on lower powered hardware. The technique used is fairly common in these sorts of scripts:
1. Create an empty ArrayMesh
2. Use SurfaceTool to copy source meshes (by surface)
3. Commit the SurfaceTool surface to the ArrayMesh

This technique works reliably on Godot 4.0 and 4.1; however it's now producing meshes with corrupt UV coordinates on Godot 4.2 if the mesh data comes from an imported mesh such as a glb file.

In the following screen-shot; the meshes in the back are the "source" meshes, and the meshes in the front are the "copies":
![image](https://github.com/godotengine/godot/assets/1863707/be75afc1-cdc0-4326-9d60-6d52c60c9240)

### Steps to reproduce

A minimal reproducible project has been attached. To use it:
1. Open the project
2. Open main.tscn
3. Pick the "CopyGltfFile" node and click on the "Copy Mesh" boolean property to trigger mesh-cloning
4. Observe the duplicated mesh with corrupted UV coordinates - the mesh has been saved to "CopyGltfFile_export.mesh" for analysis
5. Replicate for the "CopyMeshFile" node and observe identical behavior
6. Replicate for the "CopyBuiltin" which uses a built-in BoxMesh and observe the UVs appear correct.

### Minimal reproduction project

[mesh_copy_bug.zip](https://github.com/godotengine/godot/files/13211336/mesh_copy_bug.zip)

**Comment by Malcolmnixon** [comment]
I'm saving the good and bad meshes to tres files and I'm noticing a difference in the format attributes:
* Good = `"format": 34359742487,` = 0x8_0000_1017
* Bad = `"format": 34896613399,` = 0x8_2000_1017

My immediate concern is the "format" field is defined in the SurfaceData struct as being a uint32_t; and these values are roughly 10x the size of numbers that would fit in a 32-bit value. I'm wondering why bit 35 of a 32-bit number is set high.

**Comment by BastiaanOlij** [comment]
cc @clayjohn

**Comment by Malcolmnixon** [comment]
Even more fun - if I export the entire scene to gltf and load it in blender to take a closer look then the original "good" meshes show the same corruption:
![image](https://github.com/godotengine/godot/assets/1863707/745b30c1-6eba-44d7-a637-ff1cbfb432a0)

As such this bug can probably be promoted to "Meshes are Broken" regardless of mesh combining/baking - it's visible in Blender on export, but only visible in Godot after mesh operations.

**Comment by Malcolmnixon** [comment]
Tested with Master build from 93cdacbb0a30f12b2f3f5e8e06b90149deeb554b and it's fixed - both the mesh copying and the Blender export.
