### ISSUE TITLE
Zero sized fontdata files 

### ISSUE THREAD

**Issue by scripturial** [godotengine/godot#84239]
### Godot version

3.5.3, 3.5.2

### System information

Mac OSX Sonara 14.0

### Issue description

When using custom fonts on Godot 3.5.2 and 3.5.3 it works on the desktop, (Mac OSX Sonara), but fails on iOS and android. 

It turns out that Zero sized fontdata files are being generated and placed in the android build folder, which results in deploying an app that is unable to display any words. iOS builds also result the same problem.

### Steps to reproduce

Im still trying to narrow down what causes this problem. I was not having a problem with the last build several weeks ago, and I am not sure what has changed. I have tried this on 3.5.3 and 3.5.2 on Sonara and the sam problem occurs.   I am posting this here in case anyone else stumbles across this problem and we can compare notes.

### Minimal reproduction project

Im still not quite sure what specific steps/configs/settings are needed to cause the fontdata files to be zero sized. There are no other errors appearing anywhere as far as I can see. I will update this issue if I can work out the problem.

Because of the ambiguous nature of this report, it might be best to close it, I realize it's a difficult thing for anyone to action without more information. I just wanted to throw the information out there for now while I investigate.

There are errors inside the console while exporting,

    --- Debugging process stopped ---
    Cannot get class 'FontFile'. 
    Cannot get class 'FontFile'. 
    Cannot get class 'FontFile'. 
    Cannot get class 'FontFile'. 
    Cannot get class 'FontFile'. 
    Resource file not found: res://.godot/imported/myfont.ttf-cab768305abef906ec195b5d076b3bb3.fontdata.

And Xcode prints the following in the Xcode console while running a build on iOS:

    ERROR: Cannot get class 'FontFile'.
       at: _get_parent_class (core/class_db.cpp:323) - Condition "!ti" is true. Returned: StringName()

When I run on android, I also see this in the console:

     Can't open file from path 'res://.godot/imported/fontname.ttf-6ed56f0d53cf0169db8e930304e44c42.fontdata'

Interestingly though the font data files are size zero, is that meant to be the case?

    # ls -haltr ./android/build/assets/.godot/imported/
    total 0
    drwxr-xr-x@ 3 name  staff    96B Oct 31 16:46 ..
    -rw-r--r--@ 1 name  staff     0B Oct 31 16:46 font1.ttf-cab768305abef906ec195b5d076b3bb3.fontdata
    -rw-r--r--@ 1 name  staff     0B Oct 31 16:46 font2.ttf-5b15a48858c9b95b06e0dabe6be37061.fontdata

Oddly enough, when I test exporting using Godot 4.1 the same files in the same folder are also zero sized. But running on android in Godot 4.1 doesn't have this problem.

**Comment by Calinou** [comment]
What font family did you try to import in Godot? This may help narrow down the issue (even if this font isn't publicly downloadable).

**Comment by scripturial** [comment]
I rolled back the code to the last successful build, and it won't generate the fonts on Godot 3.5.2 or 3.5.3, so I suspect perhaps it's something related to a change in OSX. Im 99.9% sure it's not related to the fonts.

(All together there are 6 fonts of different types. Some smaller and some larger, some only containing English, and some containing other languages. The strange thing is, my last build a few weeks ago worked fine.)

**Comment by scripturial** [comment]
Im closing this issue for now. I was able to solve the problem by quitting Godot, and manually removing every single .import file in the project. I also removed a font that, while it worked fine in Godot for  me, it had some warnings when opened with OSX Font Book.
