### ISSUE TITLE
Cannot run Editor Script EditorScript _run() with C# [External Editor]

### ISSUE THREAD

**Issue by cyraid** [godotengine/godot#84230]
### Godot version

4.2 beta 3 and 4.1
(Someone else not being able to run this with 4.1 https://www.reddit.com/r/godot/comments/16lis9p/how_do_i_run_an_editorscript_godot_41_jetbrains/)

### System information

Windows 11 Forward+

### Issue description

When Dotnet External Editor is set, you cannot seem to not run `EditorScript` scripts. Perhaps the scripts should be moved to Project->Tools or Project->Scripts Menu. A `_GetMenuName()` would also be handy to customize what it shows as a Menu Item.

### Steps to reproduce

Create C# Script and paste what you see in "Minimal reproduction project".

### Minimal reproduction project

```csharp
#if TOOLS

using Godot;
using System;

[Tool]
public partial class TestEditor : EditorPlugin {

  public override void _EnterTree() {
    GD.Print("Hi");
  } // Procedure //

} // Class //

#endif
```

**Comment by AThousandShips** [comment]
What version are you on? If you mean multiple versions of 4.x then please specify, otherwise provide the specific version

**Comment by cyraid** [comment]
Reason I put 4.x is others have had this issue with a different version of 4 I didn't know but used another person's version and also mine as it's identical, just couldn't find anyone else posting this bug report. Will this new information help you fix the bug?

**Comment by AThousandShips** [comment]
It will make it clearer, it's important to always provide the version the issue happens on, as it might be in one version but not another (or already fixed)

**Comment by cyraid** [comment]
> It will make it clearer, it's important to always provide the version the issue happens on, as it might be in one version but not another (or already fixed)

Okay, that makes sense. Thank you for the reply.

**Comment by AdriaandeJongh** [comment]
Note that this issue also applies to GDScript scripts if you're using an external editor! The larger issue here is that you can only execute the `run()` method from within Godot's internal script editor, which should probably change....

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39842, as this is due to the same cause.
