### ISSUE TITLE
rng functions always return 0 in godot3

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8423]
Arch Linux, Godot3 (latest master build)

Using any of the random functions in godot3 always returns 0. this is the case with randf(), randi() and rand_range() even if the seed was randomized with randomize() before.

The following code works as expected in Godot 2.1.3 but not in Godot 3:
```
var random_test
func _ready():
	randomize()
	random_test = rand_range(0,100)
	print(random_test)
```

console output in Godot 3 is always: 0

**Comment by bojidar-bg** [comment]
Looks related to 4c9004671af455a03acb4e2750b12d62b2b3c917 (@tagcup), according to git blame.

**Comment by tagcup** [comment]
@bojidar-bg It's the rand() in the previous seed() code, which was apparently handled as a special case earlier. I'll submit a fix ASAP.
