### ISSUE TITLE
After making changes to Project Settings, any changes are not saved to the project.godot file

### ISSUE THREAD

**Issue by nikywilliams** [godotengine/godot#84248]
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

After making a change to the Project->Project Settings->Import Defaults (tab)->Scene (option)->Embedded Image Handling value, and saving, the project.godot file did not update.

### Steps to reproduce

Create a new empty project

Go to this menu item
![image](https://github.com/godotengine/godot/assets/28369028/b391e574-88aa-4ae6-bcfc-952693c97ca7)

 Go to this tab and select this Importer
![image](https://github.com/godotengine/godot/assets/28369028/777bba22-dfeb-4833-88be-5c7984e30012)

Change this option, click Save, then click Close
![image](https://github.com/godotengine/godot/assets/28369028/be0563a1-1e0e-49a0-aa75-06ef4552f08b)

Close the project with Save & Quit and go back into the settings...the value did not update as expected
![image](https://github.com/godotengine/godot/assets/28369028/274c17f0-0e47-48e0-8bea-04ee8b61f2d4)

Video attached for reference

https://github.com/godotengine/godot/assets/28369028/efdca19b-c77d-47f8-8f74-d6b311d402e1

### Minimal reproduction project

Instructions above, don't believe an attached project is needed for this.
Please let me know if otherwise.

**Comment by jsjtxietian** [comment]
Confirmed. Will try to fix it.
