### ISSUE TITLE
Button, Label not recognized as such but just as Node so i cannot access settings through script

### ISSUE THREAD

**Issue by psych0noals** [godotengine/godot#84245]
### Godot version

4.1.2-stable, 4.2 beta 3

### System information

Godot v4.2.beta3 - Windows 10.0.22621 - GLES3 (Compatibility) - AMD Radeon RX 6800 XT (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 Threads)

### Issue description

i started to create my GUI using flowcontainers, boxcontainers, etc... but maybe because it make the tree a bit long, it doesn't recognize the nodes at the end of it.
I cannot change the setting of buttons or labels as if i try, it returns an error like they don't exist or they are null something or it doesn't have the function i'm using... through i can still change their setting like position or basic node object propriety.
i hope i'm not using functions or method incorrectly, i even tryed differents one, i tryed delete and recreated the node as well but nothing worked.

### Steps to reproduce

just build a tree of flowcontainers, referencerects, boxcontainers, put a button at the end of it and try to disable it via script.
![godot_screenshot](https://github.com/godotengine/godot/assets/44948930/6a891e72-c856-4b0b-b148-b7f3422669e2)

### Minimal reproduction project

[glitch.zip](https://github.com/godotengine/godot/files/13215649/glitch.zip)

**Comment by psych0noals** [comment]
![godotscreen2](https://github.com/godotengine/godot/assets/44948930/4e60abac-d9ff-4074-9f01-515302af6fa9)

**Comment by akien-mga** [comment]
That's normal, there's no `disable` property in Button/BaseButton. It's `disabled`, with a d. See the documentation: https://docs.godotengine.org/en/latest/classes/class_basebutton.html#class-basebutton

Please use other community platforms for user support, this issue tracker is for bug reports.
