### ISSUE TITLE
Buggy steam overlay

### ISSUE THREAD

**Issue by strainxx** [godotengine/godot#84251]
### Godot version

4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 (Windows 11) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Steam overlay so crazy. When i shift+tab i can't turn off overlay. Sometimes overlay overlapping godot ui elements 

![image](https://github.com/godotengine/godot/assets/100953533/69a46acc-c78a-4305-9a39-a4c7963e7620)

![image](https://github.com/godotengine/godot/assets/100953533/03b9a9a2-be21-4e74-a564-fa4309f16fab)

![image](https://github.com/godotengine/godot/assets/100953533/7fd2e4cc-9801-4c45-8961-ec71cf1809bc)

### Steps to reproduce

Use godot with steam overlay turned on

### Minimal reproduction project

It works in all my projects :(

**Comment by Qainguin** [comment]
This is an issue for me too. The "Shift+Tab" notification jumps around the screen whenever I run the project.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74772.

As a workaround, disable Steam overlay integration for Godot in the game properties in Steam.
