### ISSUE TITLE
Export to Android Target SDK 24 result in error for gradle task dexBuilderDebug.

### ISSUE THREAD

**Issue by NicolaasJKotze** [godotengine/godot#84253]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 10

### Issue description

**NOTE**: Exporting to Android SDK 33 works fine.

Exporting to Android SDK 24 throws the following error in the "**Building Android Project(gradle)**" window:

```
...
CIRCULAR REFERENCE: com.android.tools.r8.internal.nc: Unsupported class file version: 62
...
What went wrong:
Execution failed for task ':dexBuilderDebug'.
There was a failure while executing work items
A failure occurred while executing com.android.build.gradle.internal.dexing.DexWorkAction
Failed to process: E:\projects\Godot4\APKtest\android\build\build\intermediates\javac\debug\classes
```

and the following error is displayed in the Godot Output panel:

`
editor/export/editor_export_platform.h:178 - Export: Building of Android project failed, check output for the error. Alternatively visit docs.godotengine.org for Android build documentation.
`

-------------------------------------------------------------------------
**System Details:**

```
Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Compatibility) - Quadro M3000M () - Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 Threads)

E:\projects\Godot4\APKtest\android\build>echo %JAVA_HOME%
C:\jdk-18
...

gradlew --version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Oracle Corporation 18+36-2087)
OS:           Windows 10 10.0 amd64
```

![Godot4 Android SDK24 Gradle Err 2023-10-31 16 49 2](https://github.com/godotengine/godot/assets/33121021/7857212c-8c4a-4741-af84-88f3aeff127d)

### Steps to reproduce

1. Open **Project** -> **Export**.
2. Add an _Android_ **preset**.
3. Open the "**Options**" tab.
4. Under the "**Gradle Build**" section, add a check mark for "**Use Grade Build**" field.
5. Under the "**Gradle Build**" section, enter the value '_24_' in the "**Min SDK**" and "**Target SDK**" fields.
6. Under the "**Keystore**" section, provide the Debug details required for signing.
7. Click the "**Export Project...**" button.
8. Observe (_Take note, the "Building Android Projec(gradle)" will close automatically_)

![Godot4APKtest - Export Settings 2023-10-31 17 04](https://github.com/godotengine/godot/assets/33121021/b4c7ae51-97da-4991-a0e2-1d50d674589f)

https://github.com/godotengine/godot/assets/33121021/de040133-22bd-47c2-8a99-463f39c71a53

### Minimal reproduction project

[APKtest.zip](https://github.com/godotengine/godot/files/13217933/APKtest.zip)

**Comment by AThousandShips** [comment]
Please see the [documentation](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#doc-exporting-for-android) for the requirements, you need 33 or later

**Comment by akien-mga** [comment]
> Please see the [documentation](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#doc-exporting-for-android) for the requirements, you need 33 or later

That's the tools requirement to target API level 33, which is the minimum requirement to publish a game on Google Play. But it should still be possible to target lower API levels with older build-tools/platform components, albeit the APK won't be suitable for Google Play distribution.

@NicolaasJKotze Could you clarify why you want to target API 24? To be clear, that's not necessary for games to be able to run on Android 7, this is covered by the Min SDK. The Target SDK covers what APIs are available to be enabled conditionally when running on newer Android versions.

It might well be that Godot's current code has an undocumented minimal Target SDK version that we would need to clarify and enforce with the range hint in the export dialog. CC @m4gr3d

**Comment by NicolaasJKotze** [comment]
Hi @akien-mga , thank you for asking. 😃 

My motivation for supporting devices with an SDK as low as 24 is primarily aimed at broadening access in low-income countries, where these older devices are still in use. The primary objective in targeting these demographics is to facilitate the distribution of educational and serious games (socially-aware gaming) content. In these regions, we often share APKs with one another due to limited internet access and the associated high data costs.

Another motivation is we tend to obtain SDK 24+ devices easier and so helps with global resource sustainability drives. When using Godot in a classroom setting, being able to support these devices makes it also much-much more affordable to drive STEM/STEAM projects.

**Comment by akien-mga** [comment]
But the Min SDK should be the only thing you need to tweak to support those devices in my experience. The Target SDK being hire means that it *also* supports newer devices, but you don't need to build a specific APK for each Android version.

**Comment by NicolaasJKotze** [comment]
Hi @akien-mga ,

> But the Min SDK should be the only thing you need to tweak to support those devices in my experience. The Target SDK being hire means that it also supports newer devices, but you don't need to build a specific APK for each Android version.

Thanks. I assumed that as well. I tried to install it on my LG G5 SE Android 7 and it failed. _Screenshot at the bottom of this message._ That's when I assumed I should force the SDK to 24. 
I managed to dig out a different Android 7 device from storage and it installed the "**Minimal reproduction project**" fine. 
So, it would seem there is a bit of hit and miss now regarding compatibility. It could be related to this ticket, or perhaps something different.

Let me know if there is more I can do to help. 😃

**My test results:**
1. Android 13: PASS ✅ - Virtual Device using Android Studio.
2. Android 8: FAIL - Virtual Device using Android Studio. See screenshot of error below.
3. Android 7: FAIL - Physical Device. LG G5 SE. See screenshot of error below.
4. Android 7: PASS ✅ - Physical Device. Huawei P9 Lite.

**Android 8 Virtual Device screenshot:**
![APK Installer  SDK 26 Android 8 Virtual Device 202](https://github.com/godotengine/godot/assets/33121021/cde033d5-8080-4a5c-854c-a172016d6dd8)

**Android 7 LG G5 SE device screenshot**
![Android7-LG-G5-SE-install-err-2023-10-31-23-38-02](https://github.com/godotengine/godot/assets/33121021/476242dc-855f-473b-8b23-ea3bd7dcb55c)

**Comment by akien-mga** [comment]
What is the Android architecture for both devices where it's failing? (armeabi (v6), armeabi-v7a, arm64-v8a, x86, x86_64)

It sounds like it's just missing the library for the right architecture, which might just be an oversight when exporting:
![image](https://github.com/godotengine/godot/assets/4701338/b1153348-f449-448a-9c9c-ea8231fee8b1)

If you didn't select armeabi-v7a but those devices use a 32-bit ARM processor (or 32-bit OS on 64-bit ARM processor), the errors are expected.

**Comment by NicolaasJKotze** [comment]
Hi @akien-mga ,

Great news! All tests to get the default export builds to install and run pass now! 🥂 

1. LG G5 SE Android 7 = armeabi-v7a
2. Huawei P9 Lite Android 7 = arm64-v8a
3. Android 8 Virtual Device = x86/64

I am not 100% certain what the impact will be on larger projects with regards to file size (_smaller vs larger package and free space requirement for installing_) when exporting for a specific SDK. This is up to the team to decide if it will be of value to the Godot project.

**CONCLUSION:**
From my perspective, the way it works currently is good enough not having to "Use Gradle Build" as I can resume development.

Feel free to ask if there is anything I can help with. 😃

**Comment by akien-mga** [comment]
Great! If you distribute the projects on Google Play, you can include all 4 libraries (4 architectures), and Google Play will automatically remove the ones which are not necessary so that users only download the library that they need.

If you distribute projects directly through APK downloads, then it can make sense to make 4 separate exports, one for each architecture, but then you need to be able to teach your user to know which download is the right one for their device.

For the original issue reported here, what's needed for us is to see what's the actual lowest *target* SDK we can support, and set a minimum range to the spinbox so that users can't select a lower target SDK that won't compile.

**Comment by m4gr3d** [comment]
I'm unable to replicate the issue on `main` or with the latest beta. The build completes fine with the target sdk set to `24`.

It's possible that it may be a local configuration issue based on SO posts for this specific errors.
e.g: https://stackoverflow.com/questions/69188708/com-android-tools-r8-internal-q8-unsupported-class-file-version-60-in-android

**Comment by NicolaasJKotze** [comment]
Hi @m4gr3d ,

Thank you for checking the main branch.

I tested my original issue on the following build, **v4.2.beta4.official** [93cdacbb0], with success ✅ . 
So, it seems this issue is only for the build **v4.1.2.stable.official** [399c9dc39].

❌ _On a separate note which I will log as a new bug, once I managed to gather sufficient information, is that the game crash on load with an "AndroidRuntime" now on the test device using build **v4.2.beta4.official** [93cdacbb0]._

**Spec Details**
```
v4.2.beta4.official [93cdacbb0]
- Windows 10.0.19045 
- GLES3 (Compatibility) 
- Quadro M3000M ()
- Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 Threads)
```

**Screenshot of successful (with warnings) gradle build console output:**
![Godot4 2BETA-Export-Android-Gradle-page1-2023-11-01_14-40](https://github.com/godotengine/godot/assets/33121021/2fe5b764-02b5-4b45-b4a8-a8d250b48a72)
![Godot4 2BETA-Export-Android-Gradle-page2-2023-11-01_14-40](https://github.com/godotengine/godot/assets/33121021/db62013b-042f-40bb-9719-dd91e0345166)

**Comment by akien-mga** [comment]
Thanks for testing! If it works in 4.2, given that lowering the Target SDK is not a common use case, I think we can consider this solved for future Godot versions.
