### ISSUE TITLE
GPU Particles lacks info for the Velocity Pivot value

### ISSUE THREAD

**Issue by WagnerGFX** [godotengine/godot#84262]
### Godot version

v4.2.beta4

### System information

Windows 10.0.19045 - Vulkan (Forward+, Mobile) - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4592) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

Velocity Pivot is used to control the pivot point of Orbit and Radial animated velocities, but the description is currently empty.

![velocity_pivot](https://github.com/godotengine/godot/assets/16827309/7ff9a105-4b21-450d-8f07-3440f52c3c09)

### Steps to reproduce

You can use the MRP to check the value in action.

### Minimal reproduction project

[GPUParticle2D Orbit Pivot.zip](https://github.com/godotengine/godot/files/13210457/GPUParticle2D.Orbit.Pivot.zip) (from #84220)

**Comment by Chubercik** [comment]
The missing description ought to be added here:

https://github.com/godotengine/godot/blob/6afd320984cf14198368cc6c53752813a02169e3/doc/classes/ParticleProcessMaterial.xml#L386-L387
