### ISSUE TITLE
HDR 2D causes washout in a canvas_item shader's sampler2D textures

### ISSUE THREAD

**Issue by JohnPandich** [godotengine/godot#84260]
### Godot version

4.2 beta 4

### System information

Linux Mint, Forward+, ntel© Xeon© CPU E5-2650 v4 @ 2.20GHz × 12, 64gb ram

### Issue description

When using a canvas item shader, Sampler2D values appear washed out.

using the TEXTURE variable with no washout:
![image](https://github.com/godotengine/godot/assets/17765648/b12d5bca-19d1-4953-a892-915c2449b3fa)

using a sampler2D containing the same texture with washout:
![image](https://github.com/godotengine/godot/assets/17765648/615c6f7e-1fee-4598-91ff-f18535b82e1b)

### Steps to reproduce

To reproduce:

1) Enable "HDR 2D" in Rendering -> Viewport settings
2) Create a Sprite2D in a scene
3) Add a shader to that Sprite2D's material with a sampler2D
4) Set the COLOR in the fragment fragment function to a value from the sampler2D

To view this issue in the "minimal reproduction project", open the scene named "repro.tscn".

### Minimal reproduction project

[HDR_washout_issue.zip](https://github.com/godotengine/godot/files/13219556/HDR_washout_issue.zip)

**Comment by Calinou** [comment]
You need to use `: source_color` for your uniform sampler2D texture:

```glsl
uniform sampler2D diffuse_texture : source_color;
```

This hints the engine that it should perform the sRGB -> linear conversion for rendering, just like it's required in 3D. You have to do this after enabling 2D HDR because the engine will internally render 2D in linear color space as opposed to sRGB.

**Comment by JohnPandich** [comment]
Thank you very much! This has resolved the problem.

**Comment by Calinou** [comment]
Reopening, as this should be documented.
