### ISSUE TITLE
Can't change Resource variable to node in another script

### ISSUE THREAD

**Issue by Rextair** [godotengine/godot#84293]
### Godot version

4.1.1.stable

### System information

Windows 10

### Issue description

I'm trying to set a resource variable with a class name through the player script. After I preloaded resources in the player script, I tried to set the player variable to player self-node. It should be working, but it's not.

![image](https://github.com/godotengine/godot/assets/59028081/4b1365b6-cbb6-4fd2-866e-4bb18b072c5c)

It says "Cannot find member "player" in base "PlayerContainer".". But in the Resource script, there is a player variable and I set his variable to be null, so I can preload Resource to the player script. And then after that, I can set the player variable to the player's node.

![image](https://github.com/godotengine/godot/assets/59028081/21510ba4-76a4-466d-9888-624cdb073736)

### Steps to reproduce

The project: https://github.com/Rextair/arkanoidgodot
Godot Engine 4.1.1.stable;
Open pad.gd and PadContainer.gd in Object/Scripts
Check output for error.

### Minimal reproduction project

The project: https://github.com/Rextair/arkanoidgodot
Godot Engine 4.1.1.stable

**Comment by AThousandShips** [comment]
The provided project is not minimal, please provide a minimal project

Can you also please try this with a supported version, like 4.1.2 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you add the requested details this can be reopened
