### ISSUE TITLE
Several feature requests for improving the experience of making tile maps

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#843]
This is a feature request for improving the way Godot allows users to paint tiles in TileMap nodes. I hope these features make it before version 1.0 is released.
1.  brush sizes: Changing the brush size would be useful if you need to paint large extensions of your TileMap node.
2.  search by name TileSet palette: You have to scroll up or down to find the tile you want to use for painting, by writing the name of the tile you want you could narrow the collection of tiles shown to find the one you need, quickly.
3.  rectangular drawing: By clicking a place and dragging the mouse, making a rectangle, the user can paint large extensions of the TileMap node at will.
4.  eraser sizes and rectangular deleting: like feature 1 and 3 but for erasing things from your TileMap.
5.  Terrain Tool: This is a feature on Tiled. As they explain it in [their wiki](https://github.com/bjorn/tiled/wiki/Using-the-Terrain-Tool): _Starting with Tiled 0.9.0, a new tool was added specifically to make editing tile maps easier when using terrain transitions. There are of course multiple ways to do transitions between tiles. The Terrain tool in Tiled supports transition tiles that have a well-defined terrain type at each of their 4 corners, which seems to be the most common method._
6.  random tiles, a brush mode: A mode that allows the brush to use many different tiles to paint randomly an area of TileMap, Tiled have a brush specifically for this, but I think that allowing this to be use in both feature request 3 besides the usual brush (but able to change its size as asked in feature request 1) is way better.
7.  Automapping: This is another feature on Tiled. Again, as they explain it in [their wiki](https://github.com/bjorn/tiled/wiki/Automapping#what-is-automapping): _Automapping is an advanced tool to automatically search certain combinations of tiles across layers in a map and to replace these parts by other combination. This allows the user to draw structures with a minimum of time spent and the Automapping will be able to generate a rather complex scenario, which would need lots more time if manually crafted. So the goal of Automapping is that you only need to draw within one layer and everything else is setup for you. This brings some advantages:_
   -   _working speed - you need less time to setup a map._
   -   _less errors - the main reason is to reduce the error rate. If you have setup the rules properly, there is no hidden error._
8.  Stamp brush tool: another feature from Tiled, you can select many different tiles and paint such selection, as is, to paint the TileMap node. In Tiled you can [create brushes](https://github.com/bjorn/tiled/wiki/Best-Practices#creating-a-brush) (so you don't have to repeatedly select different groups of tiles).

don't forget to tag this issue as "whishlist". Thanks!

**Comment by shackra** [comment]
this wasn't forgotten, right? :)

**Comment by vichug** [comment]
hah, beginning to use Godot and was going to suggest the random tiles brush :)

**Comment by shackra** [comment]
I got you covered!

> El 25 de marzo de 2015 a las 04:11 PM vichug <notifications@github.com>
> escribió:
> 
> 
> hah, beginning to use Godot and was going to suggest the random tiles brush :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/843#issuecomment-86233448

--
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola
GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en
Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by vichug** [comment]
;) in the meantime, and thanks to that message, i began using Tiled which is quite a cool program ! Do you use it ? Do you know how the junction between Tiled and Godot easy is ?

**Comment by draxdeveloper** [comment]
i have rather a simpler request... have a shortcut in keyboard to erase a
tile, using the right click is good on a mouse but is a hell without it...
And sometimes instead of erasing it's moves the tilemap, so having a
keyboard combination (key + left mouse) would help a lot.

2015-03-26 12:39 GMT-03:00 vichug <notifications@github.com>:

> ;) in the meantime, and thanks to that message, i began using Tiled which
> is quite a cool program ! Do you use it ? Do you know how the junction
> between Tiled and Godot easy is ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/843#issuecomment-86577298>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by VictorSeven** [comment]
I hope the developers still remember this. Painting tilemaps with Godot is a bit slow. This recommendations are pretty good. I would add a "Fill" tool, which is useful often. 

Please don't forget this feature request. It's easy to implement and it will help a lot of people... Having the level editor inside the game engine is simply AWESOME, but the lack of tools make the design of the map very slow.

**Comment by reduz** [comment]
I suppose this could be a fun Junior Job (tm)

**Comment by neikeq** [comment]
I started working on a related plugin yesterday. The idea is that you can extend a base brush from gdscript to create custom brushes (which you could share with the community). Be it a random tile brush, a 9-slice brush, or whatever.
I got the idea from https://youtu.be/muRhea-JaIM?t=29m45s. I'll trying to keep it simple, let's see how it goes.

**Comment by shackra** [comment]
Why not implement this directly into Godot source code? is that out of your technical skills?

El viernes 25 de diciembre del 2015 a las 1157 horas, Ignacio Etcheverry escribió:

> I started working on a related plugin yesterday. The idea is that you can extend a base brush from gdscript to create custom brushes (which you could share with the community). Be it a random tile brush, a 9-slice brush, or whatever.
> I got the idea from https://youtu.be/muRhea-JaIM?t=29m45s. I'll trying to keep it simple, let's see how it goes.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/godotengine/godot/issues/843#issuecomment-167254166


-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by neikeq** [comment]
I am not sure if it's too crazy to be in Godot's source rather than as a plugin. But I guess it could be done.

**Comment by vichug** [comment]
Now i used Tiled, and this : https://github.com/MrGreenTea/GodotTiledImporter . The combination is quite great.

**Comment by VictorSeven** [comment]
Plugins are great, but I think this should be implemented into Godot source. We could start with a basic painting tools, such as a rectangle to paint the entire selection with the desired tile. 
However if somebody if able to implement something more advanced, that can be also very nice.

**Comment by akien-mga** [comment]
From @meniku in https://github.com/godotengine/godot/issues/343#issue-32391809: 

> - Tilemap Usage: SHIFT Selection and META+D should be available as Icons, else nobody knows that this optin exists
- Tileset creation: Would be nice if it would be possible to import an Tilemap without having to creat every tile by hand
- Tilemap: Would be nice if it would arrange the tiles in that left bar like I arranged them during the creation of the tilemap - also with multiple columns

**Comment by KioriSun** [comment]
I'd like to add an item to the feature request.
It would be cool if you could change the size of the icons in the tilemap palette through the editor. I saw there was a min size in the settings options, but that doesn't really affect the final size of the displayed sprites on the left.

**Comment by TheHX** [comment]
I'm interested on working in some of those features. There's those two related issues that are interesting too: https://github.com/godotengine/godot/issues/3829 and https://github.com/godotengine/godot/issues/2413.

**Comment by reduz** [comment]
Improving tilemap editor is always welcome.

The new Godot plugin system should make a Tiled importer much better
integrated

**Comment by shackra** [comment]
@TheHX ping, are you still interest on working in some of the features requested here or are you working on them?

**Comment by blurymind** [comment]
A lot of these are already in the editor :)

**Comment by girng** [comment]
> A lot of these are already in the editor :)

the main OP was made on Oct 29, 2014 :P

**Comment by akien-mga** [comment]
Many of these suggestions are implemented by now indeed. Some might still be relevant, but it would be better to move them to their own new tickets for better visibility and actionability.
