### ISSUE TITLE
Making a CSG Mesh visible again crashes Godot 4.2 beta4

### ISSUE THREAD

**Issue by bsil78** [godotengine/godot#84304]
### Godot version

4.2-beta4

### System information

Windows 10 - Godot 4.2 beta4 - NVIDIA GForce GTX 970 - Forward+

### Issue description

Switching visibility of a CSG Mesh back to visible makes Godot to crash.

This was not the case in beta3 or previous ones.

It could be related to #84174 of @jsjtxietian (merged by @akien-mga) as it touches [modules/csg/csg_shape.cpp](https://github.com/godotengine/godot/pull/84174/commits/173e2c7f29c6d4304bf02f895082a34cf30c0908#diff-a81f2e3a53dfacfdb0037de9538db28d5646ae0c3a11a52eca1caa5d665dfd1c).

### Steps to reproduce

In a simple 3D, adding any CSG mesh, hiding node, then showing it back crashes editor.

In example project, I put an editor script in order to test by script ; here is awaited output : 

hiding : MeshInstance3D OK
showing : MeshInstance3D OK
hiding : CSGMesh3D OK
showing : CSGMesh3D OK
hiding : CSGBox3D OK
showing : CSGBox3D OK

### Minimal reproduction project

[4.2-beta4-csg-mesh-visbility-bug.zip](https://github.com/godotengine/godot/files/13226896/4.2-beta4-csg-mesh-visbility-bug.zip)

**Comment by jsjtxietian** [comment]
Thanks for reporting, I will take a look asap.

**Comment by AThousandShips** [comment]
My suspicion is that `root_collision_shape` isn't guaranteed to be non-null and that causes the crash
