### ISSUE TITLE
Change Split Mode button icon missing

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#84309]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 11

### Issue description

The Change Split Mode button on the FileSystem tab is a white square, see image:

![image](https://github.com/godotengine/godot/assets/7684647/7277f44f-ba90-43f9-8962-05790d610ddc)

### Steps to reproduce

Open the editor and look at the button

### Minimal reproduction project

N/A

**Comment by timothyqiu** [comment]
It's not missing, it's showing an unsplit layout. Clicking on it cycles through unsplit / hsplit / vsplit.

But yeah, it's confusing to see a white square :rofl:

**Comment by YuriSizov** [comment]
A new icon design is welcome! cc @MewPurPur

**Comment by MewPurPur** [comment]
I wanted to tweak this one but I had no idea what to do with it.

**Comment by Calinou** [comment]
What about something like VS Code's split editor/terminal icon?

![image](https://github.com/godotengine/godot/assets/180032/378c692e-cfc6-4ea1-a379-0eb7615f244e)

It can be either vertical or horizontal.

**Comment by MewPurPur** [comment]
That can't be it. Here's the full family of icons:

![image](https://github.com/godotengine/godot/assets/85438892/a32bdfc9-133b-477b-b712-6f7e2f80595c)

**Comment by robbertzzz** [comment]
Those icons use negative space, can't you do the opposite?

![image](https://github.com/godotengine/godot/assets/7684647/2ff6f685-53ce-4c8c-9090-6f122834eb05)

**Comment by MewPurPur** [comment]
I like how this looks, I'll do that.

**Comment by MewPurPur** [comment]
Solved by #95344
