### ISSUE TITLE
GDScript 2.0: Cannot document inner class with doc comments

### ISSUE THREAD

**Issue by LeifintheWind** [godotengine/godot#84319]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Win 10

### Issue description

NOTE: I'm basically copying #70289 as I'm experiencing the same issue, and simply copied their minimal reproduction code as well for use here.

In the [official documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_documentation_comments.html), it states the inner classes can be documented as such:

```
## Documenting an inner class.
##
## The same rules apply apply here. The documentation must
## immediately precede the class definition.
##
## @tutorial: http://the/tutorial/url.com
class Inner:

    ## Inner class variable v4.
    var v4

    ## Inner class function fn.
    func fn(): pass
```

However, after having done that, no documentation page is created for the inner class.

### Steps to reproduce

Create a class_named script with an inner class.
Try to document the inner class and its properties.
Observe that you can find the documentation page for the outer class, but the inner class can not be found anywhere.

### Minimal reproduction project

[inner-doc-comments.zip](https://github.com/godotengine/godot/files/13229931/inner-doc-comments.zip)

**Comment by dalexeev** [comment]
I can't reproduce this in 4.1.2, 4.1.3, 4.2.1.

<details>
<summary>Screenshot</summary>

![](https://github.com/godotengine/godot/assets/47700418/f40f4cd8-cc51-4caa-bf07-e128f35dec86)

</details>

**Comment by dalexeev** [comment]
Closed as per comment above and lack of activity. Thanks for the contribution nonetheless!
