### ISSUE TITLE
VisualShader editor input screen_uv preview uses visual position of node in editor rather than a sample area

### ISSUE THREAD

**Issue by TZer0** [godotengine/godot#84311]
### Godot version

v4.1.2.stable.mono.official [399c9dc39], v4.2.beta4.mono.official [93cdacbb0]

### System information

Godot v4.2.beta4.mono - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Use the output section as positional reference:
![image](https://github.com/godotengine/godot/assets/431426/6bc43a5c-ce63-481f-9fa5-7222079d27d3)
![image](https://github.com/godotengine/godot/assets/431426/d1f04c48-3d8a-4300-b8f8-aaea843153e6)

Rather than using a sample range (0 to 1 in both x and y directions) such as for uv, screen_uv uses the visual position of the node in the editor. This has no effect on the shader in-game, but makes it more difficult to make a shader as this forces you to swap between uv while building a shader and screen_uv while testing it ingame.

### Steps to reproduce

1. Create new VisualShader.
2. Add a new input, set the type to be screen_uv, enable preview.
3. Drag the node around and observe that it changes colour.
Drag it to the top left and it starts going dark, drag it to the right to make it red, drag it to the bottom right to make it yellow and finally drag it to the bottom left to make it green.

### Minimal reproduction project

Reproduction is trivial, visual of bug has been provided.

**Comment by jsjtxietian** [comment]
Confirmed.

**Comment by Chaosus** [comment]
> Is it a good practice to hack some logic in VisualShaderNodeInput::generate_code when generating preview code? Tested locally it worked, can make a pr if it's ok to you.

Yes, why not? If it's lead to better results... It's not a critical part of the engine, after all.
