### ISSUE TITLE
[GDNative] `const` functions cannot be registered

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8431]
Godot 3.0 pre-alpha master
Windows 10 64 bits MSVC

When making a GDNative library using the C++ kit, I figured out C++ functions declared as `const` produce compilation errors when used in method bindings. As a result, none can be declared as such (mostly getters, calculations and things that should be guaranteed to be read-only). This is supported when making a module, I expected it to work in GDNative too.

**Comment by karroffel** [comment]
Ups, my bad. Report here, has nothing to do with GDNative, only with the bindings. https://github.com/GodotNativeTools/cpp_bindings
