### ISSUE TITLE
GODOT 4 C# Godot Objects not implement serializable

### ISSUE THREAD

**Issue by barrrettt** [godotengine/godot#84318]
### Godot version

4.1.2,stable.mono

### System information

Win11 x86

### Issue description

Some objects in Godot are not Serializable. It's a functionality I miss. I believe that some types like Vector3, Vector2, Transform... should be able to be serialized.

### Steps to reproduce

my case: I need to send a DTO to the Networking Peers, like this one:

``` cs
using System;
using System.Collections.Generic;
using Godot;

[Serializable]
public class PlayerDataDTO{
    public string PlayerToken { get; set; }
    public int NetId { get; set; }
    public string Name { get; set; }
    public Color Color { get; set; }
    public int Aspect { get; set; }

    //this for Vector3
    public Vector3 PlayerPositionSerialized { get; set; }
}
```

Dont work 😒 
I have to do a hack like this one.

``` cs
    //hack
    public string PlayerPositionSerialized { get; set; }

    //getter+setter for des/serialize vectors3
    public void SetPlayerPosition(Vector3 position){
        PlayerPositionSerialized = $"{position.X};{position.Y};{position.Z}";
    }

    public Vector3 GetPlayerPosition(){
        string[] parts = PlayerPositionSerialized.Split(';');
        if (parts.Length == 3 && 
            float.TryParse(parts[0], out float x) && 
            float.TryParse(parts[1], out float y) &&
            float.TryParse(parts[2], out float z))
        {
            return new Vector3(x, y, z);
        }
        return new();
    }
```

Thank in advance for addressing this issue 😃 

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is not a bug but a potentially missing feature, this is for tracking bugs, please open a [proposal](https://github.com/godotengine/godot-proposals) instead.

**Comment by barrrettt** [comment]
ok. but why does it work for Color and not for Vector3?
thanks

**Comment by AThousandShips** [comment]
I have no idea, but probably related to that the concept isn't directly supported and would need to be configured if supporting it for `Object`.
