### ISSUE TITLE
Editor: keyboard shortcuts in the tile Tile Set Polygon Editor don't work anymore

### ISSUE THREAD

**Issue by sandord** [godotengine/godot#84320]
### Godot version

4.2 beta 4

### System information

Windows 11

### Issue description

In the editor, the keyboard shortcuts in the tile Tile Set Polygon Editor don't work anymore.

### Steps to reproduce

- Make sure you have a project that has a tile map with a physics layer and a tile set
- Open the tile set
- Select or create a Tiles item
- Activate Select tiles mode
- Select a tile
- Expand Physics
- Expand the physics layer
- Press C if the layer already has a polygon or press F if it hasn't
- Observe that the polygon didn't get cleared or respectively set to default.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you try following the same steps on 4.2 previous dev beta builds? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.2/).

**Comment by sandord** [comment]
> Can you try following the same steps on previous 4.2 dev/beta builds? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.2/).

I just tried it again on beta 4 and the problem is gone. Perhaps the program got into an erroneous state somehow.

When the keys didn't work, I did smash all of my modifier keys on my keyboard to make sure none of them were stuck but that didn't help.

**Comment by sandord** [comment]
I just experience the same issue with 4.2 beta 4 again. Clicking the "Reset to default tile shape" option worked but pressing F didn't.

**Comment by sandord** [comment]
Okay, I figured it out: there are multiple layers in my case and the editor was updating a different layer than the one I was viewing.
