### ISSUE TITLE
Editor: expanded polygon view in the Tile Set Polygon Editor doesn't sync with subsequently selected tile

### ISSUE THREAD

**Issue by sandord** [godotengine/godot#84321]
### Godot version

4.2 beta 4

### System information

Windows 11

### Issue description

In the editor, when using the expanded polygon view in the Tile Set Polygon Editor, the view doesn't sync with subsequently selected tiles. I have to close the expanded editor and reopen it to see the polygon of the just selected tile.

### Steps to reproduce

- Make sure you have a project that has a tile map with a physics layer and a tile set
- Open the tile set
- Select or create a Tiles item
- Activate Select tiles mode
- Select a tile
- Expand Physics
- Expand the physics layer
- Press the Expand editor button above the polygon panel
- Draw a polygon
- Select another tile
- Observe that the polygon didn't update and still displays the one of the previously selected tile

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Same cause as in #86720
