### ISSUE TITLE
SubViewport: transparent BG with SSR enabled results in blank texture

### ISSUE THREAD

**Issue by miskatonicstudio** [godotengine/godot#84330]
### Godot version

v4.1.3

### System information

Ubuntu 22.04.3 LTS

### Issue description

Setting SSR enabled in a viewport with transparent background results in a blank texture. If only one is enabled (SSR or transparent background) everything works fine.

![viewport_4](https://github.com/godotengine/godot/assets/36821133/e66e7e21-6434-46f2-82ec-1464c4c99673)
![viewport_1](https://github.com/godotengine/godot/assets/36821133/6570f0a1-f02f-46fa-8489-8287687619f7)
![viewport_3](https://github.com/godotengine/godot/assets/36821133/8bca4a6e-44c4-4935-bb17-2d2f1802e99f)
![viewport_2](https://github.com/godotengine/godot/assets/36821133/847e4df6-82a7-4dc9-8fc5-d1d1a5ee2784)

### Steps to reproduce

Please check the screenshots above, or the attached reproduction project.

### Minimal reproduction project

[reflections-test.zip](https://github.com/godotengine/godot/files/13232127/reflections-test.zip)

**Comment by BOTLANNER** [comment]
Can confirm, experiencing this as well.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73817.
