### ISSUE TITLE
Can't rename files and folders that are already selected

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#84341]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Kubuntu 22.04

### Issue description

Since Godot 4.0 beta there has been a bug where I can't rename files that are already selected.

I thought it was a basic bug and it would be fixed but turns out I got used to it and it still exists.

### Steps to reproduce

- Select a file or folder in the file system tab
- Right click
- Try to rename

### Minimal reproduction project

This has nothing to do with godot projects, it happens in all of them.

**Comment by dalexeev** [comment]
I reproduced this in 4.1, but only on the second try, after I renamed the file/folder and tried it again without switching the selection. In master the bug is not reproducible for me. Please test this in 4.2 beta 4 and let me know if the bug is fixed.

**Comment by Shadowblitz16** [comment]
it's not reproducible for me in 4.2.

**Comment by akien-mga** [comment]
Thanks, closing as fixed in 4.2.
