### ISSUE TITLE
Surface Tool doesn't generate mesh on mobile renderer with Android 10

### ISSUE THREAD

**Issue by punaukko** [godotengine/godot#84355]
### Godot version

v4.2.beta4.official [93cdacbb0], 4.1.2.stable

### System information

Godot v4.2.beta4 - Android 10 - Vulkan (Mobile)

### Issue description

This happens only when trying to run it on Android 10 using the mobile renderer.

It fails on Samsung Galaxy S9+ (Android 10).
It works on Nokia 5.4 (Android 12).

The surface tool doesn't seem generate mesh at least not visible one. It also fails to generate collision mesh as a character will fall through it.

I included an example code. 

### Steps to reproduce

Export the attached reproduction project (remember to set the renderer to mobile) and install it on an Android phone. The phone I tested is Samsung Galaxy S9+ with Android 10.

### Minimal reproduction project

[SurfaceToolBug.zip](https://github.com/godotengine/godot/files/13237789/SurfaceToolBug.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/83381 and https://github.com/godotengine/godot/issues/80371.

**Comment by punaukko** [comment]
Also happens with v4.2.beta5.official

**Comment by punaukko** [comment]
And still happens with v4.2.beta6.official [64150060f]

**Comment by clayjohn** [comment]
Might be fixed by https://github.com/godotengine/godot/pull/84852

**Comment by punaukko** [comment]
Still happens with v4.2.rc1.official [ad72de508]

**Comment by clayjohn** [comment]
@punaukko #84852 will fix this bug. We are waiting to merge it until after we release 4.2, so it can get tested more. We are aiming to include it in the 4.2.1 release.

**Comment by punaukko** [comment]
It works with v4.2.1.rc1.official [daeb1c729]. Thanks!!
