### ISSUE TITLE
set_cell not working for SceneTiles in func _process(delta)

### ISSUE THREAD

**Issue by ThatFinnDev** [godotengine/godot#84362]
### Godot version

4.1.3 stable non C#

### System information

Ubuntu 23.10 - Editor - Mobile Renderer

### Issue description

When trying to set a scene Tile in a Tilemap it will work as long as it's not in the _process function. When trying to do so, it will simply erase the cell. Using non scene Tiles works. Also doing the same thing in for example _ready(), works.

It's not broken in Godot 4.2 beta 3, which is the Godot version I am using until this bug is resolved.

### Steps to reproduce

1. Create TileSet with a SceneAtlasCollection
2. Create a Tilemap
3. Attach the TileSet
4. Setup Tilemap Layers
5. Add a Scene to the SceneAtlasCollection in the TileSet
6. Try to set the scene Tile using set_cell in _process(delta)

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Wait, so this bug exists in 4.1, but not in 4.2? This means it's already resolved.
There was a big refactor of TileMap internals, which has likely fixed this, and it can't be cherry-picked.

**Comment by ThatFinnDev** [comment]
I'll close this issue since it's already fixed in Godot 4.2
