### ISSUE TITLE
Andoid APK can't be installed on my Phone

### ISSUE THREAD

**Issue by Stoniye** [godotengine/godot#84369]
### Godot version

c4.1.2-stable

### System information

Galaxy A52s 5G

### Issue description

I followed the istruction to export an APK from this video: [Export Your Game to Android in Godot 4 - Tutorial](https://www.youtube.com/watch?v=XqmzmYMhT7g&t)

I can export ma project as an APK, but when i open it on my phone, i have to accept the security warning, then its loading with the text ,,Istalling..." and then there is the text ,,App not installed", and i only can klick on Okay.

### Steps to reproduce

I think you have to follow this video: [Export Your Game to Android in Godot 4 - Tutorial](https://www.youtube.com/watch?v=XqmzmYMhT7g&t)

### Minimal reproduction project

[Test Project.zip](https://github.com/godotengine/godot/files/13242522/Test.Project.zip)

**Comment by AThousandShips** [comment]
Would have to confirm that the tutorial is correct, and that the error occurs when exporting *correctly*, hard to investigate a third party tutorial and verify the steps

I'd suggest attempting this with a minimal project and verifying it doesn't work with that, and upload that project here

**Comment by Stoniye** [comment]
I am already trying it in a minimal project, but its somehow to big to upload it

**Comment by AThousandShips** [comment]
Then it's not minimal, what does your minimal project contain?

**Comment by Stoniye** [comment]
Nothing, just a scene with nothing in it

**Comment by AThousandShips** [comment]
Are you including the `.godot` folder? You shouldn't

**Comment by Stoniye** [comment]
Ok now it worked, the exportet APK was in the Project folder

**Comment by AThousandShips** [comment]
You haven't included the icon, which will break things, please keep the icon in the MRP in the future :)

**Comment by Stoniye** [comment]
Okay i will try creating a new Project with the icon

**Comment by AThousandShips** [comment]
Just create a default project and don't remove anything, and do not include the `.godot` folder in the zip

**Comment by Stoniye** [comment]
So, i createt a new Project. Nothing in it, i tryed again exporting, and again the ,,App not installed" error. I uploded the new Project already

**Comment by AThousandShips** [comment]
I have no idea, please have patience until someone comes and investigates this, I can't export for Android at the moment so I can't investigate this, I just helped with making sure someone else can

**Comment by Stoniye** [comment]
Oh okay, nevertheless thank you

**Comment by Alex2782** [comment]
25 MB Download (apk), I could not find any problems
https://drive.google.com/file/d/1-FkUk2hj1UYDtFaS4uv1OuYIWhLctFyP/view

But first I ran Remote Debug (USB debug / dev mode), then downloaded and installed the APK file via Google Chrome
![Bildschirmfoto 2023-11-03 um 00 15 50](https://github.com/godotengine/godot/assets/41921395/dc0cb275-bf18-4260-af41-56f7edf004a8)

**Comment by Stoniye** [comment]
Okay, thats weard. How do you Export the APK
I downloaded the Android SDK and linked the Direction in Godot, then i generated a Debugkey and linked the Direction in Godot.
Then i activaded ETC2 ASTC import in the Project settings, i changed Unique name because it showed me an error with it. Then i Exported it as an APK and downloaded it on my phone. Then i get the ,,App not intsalled" error

**Comment by Stoniye** [comment]
I tryed to istall your APK, it also worked, so i did somethin wrong in the export process

**Comment by Alex2782** [comment]
Your TestProject already has 'export_presets.cfg' for Android, I just exported, but under MacOS. 
2 months ago I had to solve other problems, configure SDK / Java / environment variables etc. correctly. 

https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html

![image](https://github.com/godotengine/godot/assets/41921395/2db16283-3a41-4218-8e78-ea8e5b45e486)

**Comment by Alex2782** [comment]
my java version
```
java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)
```

my environment variables under macos
```
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"
export ANDROID_HOME="/Users/alex/Develop/Android/SDK"
export ANDROID_SDK_ROOT="/Users/alex/Develop/Android/SDK"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"

```

**Comment by Stoniye** [comment]
I already followed the official Godot Dokumentation, i already deistalled Android Studio, Java and Godot thre times and downloadet it again, i tryed the official Godot Documentation, i tryed different YT tutorials, everytime the same result ,,App not installed"

I don't know what i am doing wrong

My Java Version:
`openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK Client VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)`

**Comment by Alex2782** [comment]
**maybe try version 17**
https://github.com/godotengine/godot-docs/issues/7902

**Comment by Alex2782** [comment]
If it does not help then try to create a new project as "Empty Activity" with Android Studio. 
Android Studio should always display the problems and try to solve them automatically. 
Android Studio "Logcat" could perhaps also show more details as to why the Apk cannot be installed.

**Comment by Alex2782** [comment]
"Compare APK" might also be a possibility to check the errors. If you are not yet familiar with this, please share your faulty APK file with everyone, e.g. on Google Drive.

![image](https://github.com/godotengine/godot/assets/41921395/bcf8666a-2702-499f-a765-efe0aef0de69)

**Comment by Stoniye** [comment]
I am screaming, i don't know what i did now, i installed the version 17 JDK and now when i export it, it shows the error:
editor/export/editor_export_platform.h:175 - Code Signing: All 'apksigner' tools found in the Android SDK 'build-tools' directory could not be executed. Verify that the correct version for the current Target SDK has been installed. The resulting APK is currently unsigned.

**Comment by Alex2782** [comment]
This is no reason to panic, at least now the errors appear directly when exporting 😃 

https://github.com/godotengine/godot-docs/issues/7902#issuecomment-1721278661

`sdkmanager --list`
my tools: [sdkmanager.txt](https://github.com/godotengine/godot/files/13252927/sdkmanager.txt)

`"platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"`

installed that way, and because of `cmdline-tools;latest` OpenJDK 17 was necessary

**Comment by Stoniye** [comment]
Jea thats a bad situation right now, i deinstalled everithing again, because i thought i broke it.
Can you please guid me throug the process to setup the APK export, because i will download everything again and start by 0

**Comment by Alex2782** [comment]
Hard to say if I can help, I use MacOS and you Windows 10?
I also have Windows, but I haven't tried Android with Godot there yet.

https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_android.html

1. OpenJDK 17
2. https://developer.android.com/studio#command-line-tools-only
4. Environment variables might also have to fit

**Comment by Stoniye** [comment]
Okay thats bad,
neverminde i will try it again (for the fourth time), i pray to good that it works
I use Windows 11

**Comment by Stoniye** [comment]
Do i have to download the JDK 17 x86 or x64?

**Comment by Alex2782** [comment]
i have `OpenJDK 64-Bit`

**Comment by Stoniye** [comment]
I am right now at the step where i install the Android SDK, in the Godot Documentation it says i have to install the Android SDK Build-Tools version 33.0.2, but i can't find it in the Android Studio SDK Manager

![image](https://github.com/godotengine/godot/assets/81874364/2bbcf811-7a32-49a0-851f-9e36a3d725b0)

**Comment by Alex2782** [comment]
![Bildschirmfoto 2023-11-03 um 19 25 23](https://github.com/godotengine/godot/assets/41921395/a8c8e395-a767-4862-af6d-593a03d760de)

**Comment by Stoniye** [comment]
Oh well, now i understand the SDK Manager, i think i installed the whole time the false packages

**Comment by Alex2782** [comment]
I think this can be closed if there are no real errors

**Comment by Stoniye** [comment]
I do not know that yet, i am installing the packages right now, if it works now to install the APK i will close this

**Comment by Stoniye** [comment]
I am screaming, it is still not working, i don't know what i am doing wrong.
You sad it could be helpful if you have the APK which is't working, i uploadet it to Google Drive:
https://drive.google.com/file/d/1HeB4Om-p_E0gZnx-RQD7B-VkOG6F7MCL/view?usp=drive_link

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
