### ISSUE TITLE
Regression in lightmap UV unwrapping in godot 4.2.beta4

### ISSUE THREAD

**Issue by LimaneGaya** [godotengine/godot#84373]
### Godot version

4.2.beta4

### System information

Windows 11, Godot 4.2.beta4, Forward +

### Issue description

unwrapping UV in models imported shows error while it works fine in godot 4.1 
![Capture d'écran 2023-11-02 175424](https://github.com/godotengine/godot/assets/36268750/0469cc38-c4c7-4917-b1fe-3cfc9360acf6)

### Steps to reproduce

import model
extract meshes
place it in a scene
try to unwrap uv

### Minimal reproduction project

[lightmap beta4.zip](https://github.com/godotengine/godot/files/13242521/lightmap.beta4.zip)

**Comment by YuriSizov** [comment]
This error was added on purpose in https://github.com/godotengine/godot/pull/83498. It's supposed to tell you about something that would fail the unwrapping later regardless. cc @SaracenOne

**Comment by AThousandShips** [comment]
Can you confirm that it worked correctly in 4.1? As in more than just it not showing a popup? Is it free of error messages and produces a valid result?

**Comment by LimaneGaya** [comment]
Yes it works fine in Godot_v4.1.3-stable 

![Capture d'écran 2023-11-02 182109](https://github.com/godotengine/godot/assets/36268750/4e9f7b64-731d-4e25-94be-b0a69dcecf6c)

**Comment by AThousandShips** [comment]
Oh wait, it looks like the condition is invalid in the PR:
```
if (format & Mesh::ArrayFormat::ARRAY_FORMAT_NORMAL) {
```
Looks inverted

**Comment by AThousandShips** [comment]
I'll just throw together a fix
