### ISSUE TITLE
Shadows cannot be disabled in the material in the Compatibility renderer

### ISSUE THREAD

**Issue by nauta-turbidus** [godotengine/godot#84386]
### Godot version

Godot v4.2.beta (b733901e9)

### System information

Godot v4.2.beta (b733901e9) - Solus 4.4 - X11 - GLES3 (Compatibility) - Mesa Intel(R) HD Graphics 3000 (SNB GT2) () - Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 Threads)

### Issue description

The `shadows_disabled` render mode doesn't work at all with the Compatibility renderer, it simply isn't implemented.

### Steps to reproduce

-add any two MeshInstances to a 3D scene
-add a light so that shadow falls on one of the meshes
-add a new shader material to the shadowed mesh and create a shader
-add `render_mode shadows_disabled;` to the shader
-shadows are still visible

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Probably an oversight from https://github.com/godotengine/godot/pull/77496 ? cc @clayjohn
