### ISSUE TITLE
InputEventMagnifyGesture is not triggered on Android

### ISSUE THREAD

**Issue by Alex2782** [godotengine/godot#84387]
### Godot version

v4.2.beta4.official [93cdacbb0], and v4.1.3

### System information

Godot v4.2.beta4 - macOS 13.6.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Under Android Studio Logcat I see that `ScaleGestureDetector` recognizes the events.
https://github.com/godotengine/godot/blob/b733901e9e650fc2f1a43627be2379f5ba200f8d/platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt#L243

![Bildschirmfoto 2023-11-02 um 23 39 29](https://github.com/godotengine/godot/assets/41921395/7a5d8121-ec85-4297-b427-c8bbb0ee014a)

In the test app and also in other projects `InputEventMagnifyGesture` does not arrive, e.g. zooming is not possible in the [GodSVG app]( https://github.com/MewPurPur/GodSVG/blob/5a009656f999506e08077ab4ed2223dc40afe5da/src/ui_parts/viewport.gd#L79)

https://github.com/godotengine/godot/assets/41921395/d0008e2c-11ef-4b8f-b937-550cbe78f374

### Steps to reproduce

try to scale with 2 fingers as in the video

### Minimal reproduction project

[InputEventTest.zip](https://github.com/godotengine/godot/files/13245266/InputEventTest.zip)

**Comment by m4gr3d** [comment]
You need to enable the project setting to receive `InputEventMagnifyGesture` events.

See https://github.com/godotengine/godot/pull/82893
