### ISSUE TITLE
web build crash: vertex shader compliation failed

### ISSUE THREAD

**Issue by moribellamy** [godotengine/godot#84399]
### Godot version

4.1.3 stable

### System information

Godot v4.1.3.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

i've put together a demo project of a simple 2d platformer, where the hero slashes slimes

https://github.com/moribellamy/platonic-game

i've exported this game to itch.io. 

https://razielx.itch.io/godot-shader-crash

the chrome inspector window gives a ton of output, but this seems like the most important: 

<img width="678" alt="Screenshot 2023-11-03 at 12 31 03 AM" src="https://github.com/godotengine/godot/assets/13877974/3db1a3c7-ab24-46b0-b301-90f87b20999a">

### Steps to reproduce

load up the game (need to toggle fullscreen to fix the viewport for some reason), slash a slime, and watch your browser crash.

### Minimal reproduction project

https://github.com/moribellamy/platonic-game

**Comment by clayjohn** [comment]
Could you please copy-paste the entire error? Just below (in the section you cut off) the error reports exactly what the issue is. It should provide enough info for us to identify the cause

**Comment by Calinou** [comment]
This was already reported in https://github.com/godotengine/godot/issues/65696 (see comments at the bottom).

**Comment by moribellamy** [comment]
thanks. i'm pretty convinced this is a dupe, so closing accordingly
