### ISSUE TITLE
Godot crashes upon opening a project using OpenGL renderer

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot#84392]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Can't Open Project to access

### Issue description

I expected the project to open properly with OpenGL renderer instead it crashes and doesn't open the project.

### Steps to reproduce

1. Open Godot
2. Create or Open a project
3. Wait for it to init graphics

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
Please provide a proper system information: OS, CPU, Graphic Card, Driver Version.

**Comment by ltecheroffical** [comment]
Since I can't open the project with that renderer I'll copy this from another project `Godot v4.2.beta4 - macOS 11.7.10 - Vulkan (Forward+) - integrated Intel HD Graphics 5000 - Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 Threads)`

**Comment by Chaosus** [comment]
I guess it's a duplicate of https://github.com/godotengine/godot/issues/83669 or https://github.com/godotengine/godot/issues/83269 (almost same OS / GPU).

**Comment by ltecheroffical** [comment]
Wait, what's the difference between the issue numbers?

**Comment by YuriSizov** [comment]
This was potentially fixed by https://github.com/godotengine/godot/pull/84288. You can try building from the master branch to confirm, or wait for beta 5 to be out.
