### ISSUE TITLE
Godot Android Editor model import bug on Mobile Renderer

### ISSUE THREAD

**Issue by Orthos-Studios** [godotengine/godot#84400]
### Godot version

4.1.3

### System information

Android 11 Ram 4GB Snapdragon 665 Adreno 610 OpenGL 3.2

### Issue description

Everytime I export a model of format obj or gltf I get a visual bug.
![Screenshot_2023-11-03-13-45-00-625_org godotengine editor v4](https://github.com/godotengine/godot/assets/120662220/e579ae34-5d22-492e-83b6-26cceb49b875)

### Steps to reproduce

Import any obj or gltf model on Godot android editor v4.1.3 using mobile renderer.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Is the bug importing or exporting?

**Comment by Calinou** [comment]
> Is the bug importing or exporting?

Godot can't export OBJ and the "steps to reproduce" refer to importing, so this is actually related to importing.

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/80371
