### ISSUE TITLE
`SubViewport`: Any `msaa_2d` value other than Viewport.MSAA_DISABLED corrupts rendered contents

### ISSUE THREAD

**Issue by thygrrr** [godotengine/godot#84406]
### Godot version

Godot_v4.2-beta4_mono_win64
Godot_v4.2-beta4_win64
custom builds on 4.2 branch

### System information

Windows 11 Pro
Version	10.0.22631 Build 22631
(previous release, a.k.a. 23H1, is equally affected)
Nvidia Geforce 3080 with Studio Drivers 537.58 and 546.01

### Issue description

For both transparent and opaque `SubViewport` nodes, setting `msaa_2d` to any value other than `Viewport.MSAA_DISABLED` will cause its content to be corrupted or stop updating. 

Oftentimes, distorted or unrelated visual content it shown, such as the Godot logo. 

The bug does not occur on 4.1.2.stable, only on (more recent) 4.2 builds. I seem to recall that I was first encountering this issue in the wake of the "Disable 2D" feature and its reversion, https://github.com/godotengine/godot/pull/84109 - the actual code change may be an unrelated commit, this is just a temporal ballpark because the viewports appeared to be working as expected not long before.

### 4.2.x behaviour (bug)
https://github.com/godotengine/godot/assets/8904620/b677242b-df01-4206-b62c-ee0b03c0c518

In editor preview of the viewport, when manually setting the MSAA values, often parts of the editor GUI can be seen in the preview.

https://github.com/godotengine/godot/assets/8904620/f27a5b51-5866-43bf-b712-2c25b2a61b70

### 4.1.2 behaviour (works as expected)
https://github.com/godotengine/godot/assets/8904620/76deb1ac-3761-4664-9bb0-375e19f58bb5

### Steps to reproduce

Repro is 100% on Windows 11 64bit with
`Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080`
(both for latest beta and latest dev build of 4.2)

1. Open Project
2. Run reproduction scene
3. Observe: Different behaviours when cycling through the different `msaa_2d` values.
4. Manually toggle transparency on the viewport
5. Observee: But persists (but with different background color of the viewport, as expected)
6. Manually change the `msaa_3d` propety.
7. Observe: The bug is unrelated to this property, all values work as expected.

### Minimal reproduction project

[viewport-msaa2d-repro.zip](https://github.com/godotengine/godot/files/13250031/viewport-msaa2d-repro.zip)

**Comment by thygrrr** [comment]
There's also a scenario in which the viewport just stays blank (or is just the clear color, no geometry is visible), it appears related to the game's "main" MSAA settings.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84280, as this is due to the same cause.
