### ISSUE TITLE
Lightmap baking sometimes freezes on "integrate indirect lighting".

### ISSUE THREAD

**Issue by LimaneGaya** [godotengine/godot#84417]
### Godot version

4.2.beta4

### System information

Windows 11, Godot 4.2.beta4, Forward +, Integrated graphics

### Issue description

Godot freezes when baking lightmap after changing lightmap size hint property or size of the meshinstance.
lightmap works normally and fast for small scene, but freezes when increasins those values.

![Capture d'écran](https://github.com/godotengine/godot/assets/36268750/b9628d15-b18c-4173-8d92-2f7513f434a1)

I couldn't figure out if the issue is hardware related or a bug.

### Steps to reproduce

Setting up simple scene(plane, cube, sphere) and unabling uv2 on them.
Adding lightmapGI
Changing lightmap size hint or scale of the primitive mesh.
Clicking on bake lightmaps.

### Minimal reproduction project

[4.2.beta4lightmap.zip](https://github.com/godotengine/godot/files/13252179/4.2.beta4lightmap.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/54679.
