### ISSUE TITLE
Godot application won't launch.

### ISSUE THREAD

**Issue by DenisItStep** [godotengine/godot#84429]
### Godot version

4.1.3-stable

### System information

Windows 7x64, GLES3: OpenGL API 3.3.11672 Core Profile Forward-Compatible Context - Compatibility - Using Device:ATI Radeon HD 4800 Series

### Issue description

When you launch Godot version 4.0.2, the program starts. Starting from version 4.1, when you launch the application, the program closes after a few seconds. When running via the console with the --rendering-driver opengl3 switch, the console displays the following error.
```
ERROR: SceneShaderGLES3: Fragment shader compilation failed:
Fragment shader failed to compile with the following errors:
ERROR: 0:414: error(#185) Array size must be a constant integer expression
ERROR: 0:422: error(#185) Array size must be a constant integer expression
ERROR: error(#273) 2 compilation errors.  No code generated

   at: _display_error_with_code (drivers/gles3/shader_gles3.cpp:242)
ERROR: Method/function failed.
   at: _compile_specialization (drivers/gles3/shader_gles3.cpp:384)
```
![errors](https://github.com/godotengine/godot/assets/39519670/4ed873b7-a046-4e90-b996-5aa6785fc5d4)

### Steps to reproduce

run the command in the console:
`Godot_v4.1.3-stable_win64.exe --rendering-driver opengl3`

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/78888.
