### ISSUE TITLE
Internal error when adding multiple scenes into the 3D viewport

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#84422]
### Godot version

Master (4.2)

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

As you can see in the video when you try to add multiple scenes in to the 3D viewport (only with multiple scenes) the editor throws this error.

```
ERROR: Can't add child '@Node3D@18837' to '@SubViewport@9274', already has a parent '@SubViewport@9274'.
   at: (scene\main\node.cpp:1411)
```

Video: https://youtu.be/BVcCIigQJDw

This happens in the latest master (pulled on 2.11.2023).

### Steps to reproduce

Drag couple of the 3d mesh scenes into the 3D viewport and then select multiple scenes and drag them over and observer the error.

### Minimal reproduction project

[TestSceneDragAndDrop.zip](https://github.com/godotengine/godot/files/13253741/TestSceneDragAndDrop.zip)

**Comment by AThousandShips** [comment]
Please add the error in text, having to go through the video to find it and read it isn't accessible or convenient :)

**Comment by viksl** [comment]
@AThousandShips Thanks, I'm accidentally deleted it when I was making the report and did not notice at all after posting. I added what the output drops on me.

**Comment by Cereveloper** [comment]
I can reproduce this in 4.2 on Mac, it is triggered when mouse enters to 3D viewport while dragging.

**Comment by Cereveloper** [comment]
I think this could be the method triggering? https://github.com/godotengine/godot/blob/4c96e9676b66d0cc9a25022b019b78f4c20ddc60/scene/main/viewport.cpp#L2374C41-L2374C41

What do you think?

**Comment by akien-mga** [comment]
Confirmed in 4.2-rc1, as well as 4.1-stable and 4.0-stable.
