### ISSUE TITLE
get_viewport() == get_window() == get_tree().root

### ISSUE THREAD

**Issue by artvel** [godotengine/godot#84427]
### Godot version

4.1.3 stable, 4.2.beta4

### System information

Tested on Windows 11 and Macos

### Issue description

Currently all the methods return the same thing which is wrong.

I think, it should be like:
`get_window()` is supposed to return the reference of the outer window(where you have the bar with the x).
`get_viewport()` is supposed to return the reference of the inner game rect.
`get_tree().root` is supposed to return the root node reference of the main scene.

### Steps to reproduce

`print(str("Is it all the same? ", get_viewport() == get_window(), get_window()==get_tree().root))`
output:
`Is it all the same? truetrue`

Expected output:
`Is it all the same? falsefalse`

### Minimal reproduction project

Reproduction project not needed.

**Comment by YuriSizov** [comment]
No, this is correct. All three are supposed to return a node. At the top of the scene tree there is a Window, which is a type that extends Viewport. So all these methods return the same thing in the most basic context.

There can be many windows and viewports in the scene tree, so in more complex situations those methods will return something different (root is always the same though).
