### ISSUE TITLE
Creating a export named "scale" will change the actual scale of the Control node

### ISSUE THREAD

**Issue by valkyrienyanko** [godotengine/godot#84431]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Windows 11, RX 6600, 10400 CPU

### Issue description

If you create a [Export] named "scale" then the actual scale of the Control node will be reset.

![Untitled](https://github.com/godotengine/godot/assets/6277739/f05a5140-0214-461a-994d-aec43f4d53bc)

### Steps to reproduce

1. Create a new ColorRect node
2. Attach a script to it
3. In the script add the following
```cs
public partial class ColorRect : Node
{
    [Export] float scale;
}
```
4. Build the project
5. Notice in the inspector how the scale of the control node is now (0, 0)
6. Try commenting out the [Export] line and rebuild the project
7. Notice how the scale has gone back to normal (1, 1)

### Minimal reproduction project

[ScaleTest.zip](https://github.com/godotengine/godot/files/13255273/ScaleTest.zip)

**Comment by Calinou** [comment]
Can you reproduce this with GDScript?

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot/issues/75554
* https://github.com/godotengine/godot/issues/45961

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/75554 and https://github.com/godotengine/godot/issues/45961.
