### ISSUE TITLE
[4.2 beta 4] Pressing Enter after typing file name no longer confirms "Create Shader" dialogue

### ISSUE THREAD

**Issue by Goldenlion5648** [godotengine/godot#84433]
### Godot version

4.2 beta4

### System information

Godot v4.2.beta4 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.2647) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I just pressed the "new shader dropdown"
![image](https://github.com/godotengine/godot/assets/32916571/e2256d75-b752-4397-98a2-0e0712fda2bb)

and typed the name test123,, but when I pressed enter, the dialogue did not close (nothing happened). Doing this same thing in 4.1 does close the dialogue and create the file.

### Steps to reproduce

Create a sprite 2d

Add a new shader material

Add new shader

type a name for the shader file and press enter

notice nothing happens

### Minimal reproduction project

N/A

**Comment by DxUr** [comment]
@Goldenlion5648 It works fine on Arch/Linux

**Comment by synalice** [comment]
I've just tested it (Windows 10) and the issue isn't present is `v4.2-dev2` but does appear in `v4.2-dev3`. So it is somewhere between these two versions.

@DxUr, could you please maybe try running these two versions on your machine to verify this doesn't happen on Linux? 

[(4.2-dev2 download link)](https://godotengine.org/download/archive/4.2-dev2/)
[(4.2-dev3 download link)](https://godotengine.org/download/archive/4.2-dev3/)

**Comment by DxUr** [comment]
> I've just tested it (Windows 10) and the issue isn't present is `v4.2-dev2` but does appear in `v4.2-dev3`. So it is somewhere between these two versions.
> 
> @DxUr, could you please maybe try running these two versions on your machine to verify this doesn't happen on Linux?
> 
> [(4.2-dev2 download link)](https://godotengine.org/download/archive/4.2-dev2/) [(4.2-dev3 download link)](https://godotengine.org/download/archive/4.2-dev3/)
> 
> I'll try to [bisect](https://docs.godotengine.org/en/stable/contributing/workflow/bisecting_regressions.html). My hardware is not the best one out there, so any help is appreciated 🤕 I'll update this comment with info about what commits are good and bad!
> 
> **Good:** [da81ca6](https://github.com/godotengine/godot/commit/da81ca62a5f6d615516929896caa0b6b09ceccfc) **Bad:** [79e28e0](https://github.com/godotengine/godot/commit/79e28e091458b8f046b7e8b955790d1015faaad7)

No Issue

**Comment by synalice** [comment]
Updates on bisection:
```
d275a7487d6728a490184971589f5e4854965466 is the first bad commit
commit d275a7487d6728a490184971589f5e4854965466
Author: detomon <simon@monoxid.ch>
Date:   Fri Jul 28 13:09:02 2023 +0200

    Initialize MSDF parameters in BaseMaterial3D with default

 doc/classes/BaseMaterial3D.xml | 2 +-
 scene/resources/material.cpp   | 5 ++++-
 2 files changed, 5 insertions(+), 2 deletions(-)
```

**Comment by KoBeWi** [comment]
Related: #82328
The fix will likely be similar.

> Git says https://github.com/godotengine/godot/commit/d275a7487d6728a490184971589f5e4854965466 is the first bad commit.

Doesn't look related.
