### ISSUE TITLE
Backport some 2.2 features into 2.1 branch?

### ISSUE THREAD

**Issue by ArcOfDream** [godotengine/godot#8443]
As time went on, I ended up sticking with 2.2 for my current project because of it's rather handy features like the ternary operator or the no distraction mode. I kinda found it strange how most of the newer features weren't introduced in the 2.1 branch.

Would it be a hassle to backport some 2.2 features to the 2.1 branch? For example, for low-DPI screens the fullscreen/no distraction mode comes quite in handy, especially when it comes to script editing, so it'd be still a nice addition for the 2.1.4 release.

**Comment by magyar123** [comment]
Distraction free mode and the ternary operator (2.1.2+) can already be found in the latest release...

**Comment by ArcOfDream** [comment]
I have tested 2.1.3 thoroughly and... well, I stand corrected! in which case, the button for the distraction-free mode could still be added. Fullscreen mode shortcut is there, but doesn't actually seem to work compared to 2.2.

**Comment by magyar123** [comment]
Yeah the button could be added, otherwise, people just don't know about the feature 😄

**Comment by akien-mga** [comment]
If a contributor wants to backport the button for the distraction free mode, feel free to. :)
