### ISSUE TITLE
TouchScreenButton not triggering action assigned in the inspector on Android devices

### ISSUE THREAD

**Issue by cr98** [godotengine/godot#84436]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 11, Compatibility renderer

### Issue description

Action not triggering on TouchScreenButton when assigned the action in the Inspector's Action property and specifically the is_action_just_pressed() method. The is_action_pressed() is working normally but the former doesn't trigger when tested via remote debug and on apk export. only on the Android device. on the Run project on pc the button triggers normally.

### Steps to reproduce

add a TouchScreenButton node assign an action on it's action property in the Inspector, call the action in a script using Input.is_action_just_pressed() note it's not Input.is_action_pressed() that one is working ok, test it on an Android device not in the pc

### Minimal reproduction project

[android_input assign_bug.zip](https://github.com/godotengine/godot/files/13255667/android_input.assign_bug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70951.

**Comment by layallolo5050** [comment]
فعل كل التطبيقات في الاندرويد هذا الجهاز

**Comment by layallolo5050** [comment]
فعل

**Comment by layallolo5050** [comment]
_****_

**Comment by cr98** [comment]
> فعل كل التطبيقات في الاندرويد هذا الجهاز

I used translate, but what do you mean with "Activate all applications on this Android device" I don't understand can you elaborate
