### ISSUE TITLE
Can't edit bus volume while running the game

### ISSUE THREAD

**Issue by nicom7** [godotengine/godot#84430]
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

Adjusting the volume of an audio bus from the bus layout (Audio tab) doesn't change the volume in the running game. It only works when an audio stream is started manually in the editor.

### Steps to reproduce

- Open `node_2d.tscn` scene from attached project
- Activate the `Playing` property from the `AudioStreamPlayer` node to start playing sample sound
- Adjust the master bus volume from the bus layout in the Audio tab: notice how the volume of the playing sound changes
- Stop the `AudioStreamPlayer`
- Press F5 to run the scene
- Adjust the master bus volume: there's no change in volume of the currently playing sound

### Minimal reproduction project

[bug_audio_bus_layout.zip](https://github.com/godotengine/godot/files/13255205/bug_audio_bus_layout.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/1186.
