### ISSUE TITLE
Can't Compile Godot Master

### ISSUE THREAD

**Issue by DxUr** [godotengine/godot#84449]
### Godot version

Master

### System information

Arch

### Issue description

![image](https://github.com/godotengine/godot/assets/137767403/065a2e98-d65e-4971-a076-2bc79afceeb6)

### Steps to reproduce

Compile as always

### Minimal reproduction project

N/A

**Comment by DxUr** [comment]
I recompile it again and it works,  the issue is I ran out of memory.

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.
