### ISSUE TITLE
Parser Error: Native class "TTS" cannot be constructed as it is abstract.

### ISSUE THREAD

**Issue by hugarty** [godotengine/godot#84456]
### Godot version

4.1 and 4.2

### System information

Manjaro Linux,  Intel i5, NVIDIA GeForce GTX 1060 3GB, Vulkan

### Issue description

I tried to implement this [Custom modules in C++](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html) and this [Binding to external libraries](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/binding_to_external_libraries.html#doc-binding-to-external-libraries). 
The first one is working fine.  But _Binding to external libraries_ it's not.

I tried in 4.2 and 4.1, on both appears the error.
It's a simple project with only a Node2D and a child Sprite2D.
I created a simple lib instead of using TTS.

When i call **TTS.new()** appears: Parser Error: Native class "TTS" cannot be constructed as it is abstract.

GDScript
```
func _ready():
	var s = Summator.new()
	s.add(10)
	print(s.get_total())
	print('is_spoken: ', TTS.say_text())
	s.reset()
	# var x = TTS.new() !!!! ERROR HERE !!!! - Parser Error: Native class "TTS" cannot be constructed as it is abstract.
```
When i remover the line `TTS.new()` it works. 
Output: 
```
Godot Engine v4.2.beta.custom_build.6afd32098 - https://godotengine.org
Vulkan API 1.2.175 - Forward Mobile - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 3GB
 
10
is_spoken: 123
```

------------
> I tried to debug but I'm a cpp noob and my breakpoint don't stop in the line:
file: modules/gdscript/gdscript_analyzer.cpp
```
push_error(vformat(R"(Native class "%s" cannot be constructed as it is abstract.)", base_native), p_source);
```
> it's weird, because few lines before the breakpoint stops and show my class data TTS apparently correct:
```
} else if (p_is_constructor && !ClassDB::can_instantiate(base_native)) {
```
> it's like it don't stops in _push_error_()

### Steps to reproduce

The _Custom modules in C++_ is equal tutorial.

The _Binding to external libraries_ is different. Bellow I show how I did.

The `libFirst.a` also is in my `/usr/local/lib/`.

folder structure _godot/modules/tts_
```
tts
 | libpath/
 |   ` libFirst.a
 | src/
 |   ` include/
 |   |  ` Unidade.h
 |   ` Unidade.cpp
 | config.py
 | register_types.cpp
 | register_types.h
 | SCsub
 | tts.cpp
 | tts.h
```
Unidade.h
```
#ifndef UNIDADE_H
#define UNIDADE_H

class Unidade {

public:
    static int returnaUmDoisTres ();
};

#endif 
```

Unidade.cpp
```
#include "Unidade.h"

int Unidade::returnaUmDoisTres () {
    return 123;
}
```
config.py
```
def can_build(env, platform):
    return True

def configure(env):
    pass
```

register_types.cpp
```
#include "register_types.h"
#include "core/object/class_db.h"
#include "tts.h"

void initialize_tts_module(ModuleInitializationLevel p_level) {
	ClassDB::register_class<TTS>();
}

void uninitialize_tts_module(ModuleInitializationLevel p_level) {
	// Nothing to do here in this example.
}
```

register_types.h
```
#include "modules/register_module_types.h"

void initialize_tts_module(ModuleInitializationLevel p_level);
void uninitialize_tts_module(ModuleInitializationLevel p_level);

/* yes, the word in the middle must be the same as the module folder name */
```
> I don't know why, but in the godot tutorial they use `void register_tts_types();` and `void unregister_tts_types();` in the files `register_types.h` and `register_types.cpp`. 
But it doesn't compile. I recieved the error: `modules/register_module_types.gen.cpp:181:9: error: 'initialize_tts_module' was not declared in this scope; did you mean 'initialize_tga_module'?`.
So I started to use `void initialize_tts_module(ModuleInitializationLevel p_level);` and `void uninitialize_tts_module(ModuleInitializationLevel p_level);`. 

> I tried to use both `register_tts_types` and `initialize_tts_module`, but `TTS.new()` still didn't work .

SCsub
```
Import('env')

env_tts = env.Clone()
env_tts.add_source_files(env.modules_sources, "*.cpp") # Add all cpp files to the build

env_tts.Append(CPPPATH=["src/include"])

env.Append(LIBPATH=['libpath'])
env.Append(LIBS=['First'])
```

tts.cpp
```
#include "tts.h"
#include <Unidade.h>

int TTS::say_text() {
    return Unidade::returnaUmDoisTres();
}

int TTS::flow() {
    return _flow;
}

void TTS::_bind_methods() {
	ClassDB::bind_static_method("TTS", D_METHOD("say_text"), &TTS::say_text);

	ClassDB::bind_method(D_METHOD("flow"), &TTS::flow);
}

TTS::TTS() {
    _flow = 10;
}
```

tts.h
```
#ifndef GODOT_TTS_H
#define GODOT_TTS_H
#include "core/object/ref_counted.h"

class TTS : public RefCounted {
	GDCLASS(TTS, RefCounted);

	int _flow;
protected:
	static void _bind_methods();

public:
	static int say_text();
	int flow();
	TTS();
};

#endif 
```

### Minimal reproduction project

[godot.project.zip](https://github.com/godotengine/godot/files/13257369/godot.project.zip)
[test.zip](https://github.com/godotengine/godot/files/13257370/test.zip)

Build the libFirst.a, bind the libFirst.a in a module called tts.
Just start the project and run the scene.

**Comment by AThousandShips** [comment]
Does it work if you do:
```cpp
#include "register_types.h"
#include "core/object/class_db.h"
#include "tts.h"

void initialize_tts_module(ModuleInitializationLevel p_level) {
    if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
        return;
    }
    ClassDB::register_class<TTS>();
}

void uninitialize_tts_module(ModuleInitializationLevel p_level) {
	// Nothing to do here in this example.
}
```
You are registering the class several times in your code

**Comment by hugarty** [comment]
It's working! 

Thank you. I made the change and started to work.

Can I change the documentation of these _Binding to external libraries_ to add code you show here ?

---

Another question. Why can't I return `Unidade` in to GDScript ? Does it needs to extend some `Variant` or `Object` or `RefCount` to be able to create a instance inside GDScript? Why?


And again, thank you very much!

**Comment by AThousandShips** [comment]
The code there is out of date as it doesn't include the proper method as you discovered above, should be updated

> Another question. Why can't I return Unidade in to GDScript ? Does it needs to extend some Variant or Object or RefCount to be able to create a instance inside GDScript? Why?

It needs to extend `Object` or `RefCounted`, that's the only way you can connect them

**Comment by hugarty** [comment]
I think the documentation of [writing-custom-unit-tests  - custom modules in cpp](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#writing-custom-unit-tests) is outdated too. 

I tried to implement this tutorial too and didn't work.

1. Create a new directory named tests/ under your module's root.
2. Create a new test suite: `test_summator.h`.
3. Write some test cases
4. Compile the engine with scons tests=yes

It just don't run the test when I execute `./bin/godot.linuxbsd.editor.x86_64 --test --source-file="*test_summator*" --success --verbose`:
```
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
[doctest] test cases: 0 | 0 passed | 0 failed | 838 skipped
[doctest] assertions: 0 | 0 passed | 0 failed |
[doctest] Status: SUCCESS!
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2207)
```

I tried to use different filters but don't find the file. 
```
--test-suite | -ts | -ts="*[EXAMPLE]*"
--test-case | -tc | -tc="*[EXAMPLE]*"
--source-file | -sf | -sf="*EXAMPLE*"
``` 
 
Don't work, I think some SCsub need to be changed, but I don't know.

----

So I tried to ADD to summator module folder `modules/summator/tests/test_summator.h`, 
```
#include "tests/test_macros.h"
#include "modules/summator/summator.h"

namespace TestSummator {

TEST_CASE("[Modules][Summator] Adding numbers") {
	Ref<Summator> s = memnew(Summator);
	CHECK(s->get_total() == 0);

	s->add(10);
	CHECK(s->get_total() == 10);
```
I change `modules/summator/SCsub` to add tests files:
```
Import('env')

env.add_source_files(env.modules_sources, "*.cpp") # Add all cpp files to the build

if env["tests"]:
    env.Append(CPPDEFINES=["TESTS_ENABLED"])
    env.add_source_files(env.modules_sources, "./tests/*.cpp")
```

**And Work!** But it's too slow. 
```
===============================================================================
[doctest] test cases: 1 | 1 passed | 0 failed | 838 skipped
[doctest] assertions: 5 | 5 passed | 0 failed |
[doctest] Status: SUCCESS!

--- scons ---
[ 95%] Compiling core/input/default_controller_mappings.gen.cpp ...
[ 99%] progress_finish(["progress_finish"], [])
[100%] Linking Program bin/godot.linuxbsd.editor.x86_64 ...
[100%] scons: done building targets.
[Time elapsed: 00:11:12.407]
```
It LINK the entire engine every time I change the test. I believe it happens because of the SCsub change in `env`.
```
[100%] Linking Program bin/godot.linuxbsd.editor.x86_64 ...
[100%] scons: done building targets.
[Time elapsed: 00:02:09.532]
```
---

So I tried to Add to TTS, and put the change only for my  `env_tts`:
_modules/tts/SCsub_
```
Import('env')

env_tts = env.Clone()
env_tts.add_source_files(env.modules_sources, "*.cpp") # Add all cpp files to the build

env_tts.Append(CPPPATH=["src/include"])

env.Append(LIBPATH=['libpath'])
env.Append(LIBS=['First'])

if env_tts["tests"]:
    env_tts.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_tts.add_source_files(env.modules_sources, "./tests/*.cpp")
```

I create _modules/tts/tests_tts.h_

And when I execute `scons platform=linuxbsd tests=yes` 
```
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  8%] Generating modules tests header.
[ 99%] progress_finish(["progress_finish"], [])
[100%] Compiling tests/test_main.cpp ...
In file included from ./modules/tts/tests/test_tts.h:6,
                 from ./modules/modules_tests.gen.h:1,
                 from tests/test_main.cpp:128:
./modules/tts/tts.h:7: fatal error: Unidade.h: No such file or directory
    7 | #include <Unidade.h>
      | 
compilation terminated.
scons: *** [tests/test_main.linuxbsd.editor.x86_64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:11.060]
```
It can't find Unidade Inside `modules/tts/tts.h` and `modules/tts/tts.cpp`
```
#ifndef GODOT_TTS_H
#define GODOT_TTS_H

#include "core/object/ref_counted.h"
#include <Unidade.h>

class TTS : public RefCounted {
	GDCLASS(TTS, RefCounted);

	Unidade unidade_;

protected:
	static void _bind_methods();
...
```
When I remove `test_tts.h` and run ` scons platform=linuxbsd tests=yes` it compiles perfectly, but I don't have tests for Unidade anymore.
```
scons: Building targets ...
[  8%] Generating modules tests header.
[100%] progress_finish(["progress_finish"], [])
[100%] Compiling tests/test_main.cpp ...
[100%] scons: done building targets.
[Time elapsed: 00:02:08.551]
```
--- 
> I just want to unit test fast my custom module and use Godot hash_set, hash_map inside my `Unidade`. 2 Minutes for each compilation and don't be able to test it's kinda sad.

> I tried to use another STL (EASTL) library and GTEST in a custom module, it is fast to compile and run tests, but was very hard to bind with godot.

> STL and Unit Tests fast. How? 

Thank you, if you read until here.

**Comment by hugarty** [comment]
I create this [pull-request](https://github.com/godotengine/godot-docs/pull/8407) to update the documentation of [binding to external libraries](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/binding_to_external_libraries.html#doc-binding-to-external-libraries)

But [writing-custom-unit-tests - custom modules in cpp](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_modules_in_cpp.html#writing-custom-unit-tests) I didn't change.

How to improve this section? Do I need to create another issue?

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot-docs/pull/8407. Thanks for contributing! Feel free to open a separate PR for writing-custom-unit-tests.
