### ISSUE TITLE
Loss of Inherited Scene Status and Copying of import

### ISSUE THREAD

**Issue by martinruefenacht** [godotengine/godot#84457]
### Godot version

4.1.3.stable

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6950 XT (Advanced Micro Devices, Inc.; 31.0.23001.2007) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

There seems to be a loss of assocation of a inherited scene of a blend file. This causes the blend model/scene to update when a change occurs, but doesn't update the scene used in the inherited scene/it gets copied.

### Steps to reproduce

1. Create a scene
2. Place a blend file in the project
3. Create a new inherited scene of the blend file (right click in editor "New Inherited Scene")
4. In the created scene change the Node3D to any other node type (for example RigidBody3D), this is the step that destroys the association
5. Change the blend file
6. Reimport happens automatically, but doesn't updated the "inherited scene" (the old version stays)

### Minimal reproduction project

[InheritedSceneBug.zip](https://github.com/godotengine/godot/files/13257601/InheritedSceneBug.zip)

**Comment by Rindbee** [comment]
It seems that changing types on an inherited scene root should not be allowed.
