### ISSUE TITLE
Playing the project opens project manager instead of game window

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8445]
Arch Linux, Latest Godot3 master build (7088d9e)

Just compiled a fresh build from Godot3 master branch and I'm having some new weird issues, that may or may not be related to each other:

1. My project list is now empty and i can't seem to scan for or import any old projects (done with earlier godot3 builds)
2. Whenever I run my newly created project, the Project Manager keeps popping up instead of the game window

**Steps to reproduce:**
1. try to scan for or import any older (godot3) project
2. create a new project
3.  run it

Edit:
The Project Manger only pops up when playing the project(F5). Playing the edited scene(F6) works as expected.

**Comment by akien-mga** [comment]
You need to rename your `godot.cfg` to `<something>.godot`, see #8375. Be sure to check the `git log` when you live on the edge, the master branch is a moving target ;)

**Comment by novemberist** [comment]
hey. you are right. but this doesn't explain the main issue (project window popping up when playing the project) which happens with newly created projects, too.

**Comment by novemberist** [comment]
just in case my explanation wasn't good enough, I've made a gif of what i mean.
![godot_issue](https://cloud.githubusercontent.com/assets/7927471/25122618/dbfce88e-2425-11e7-88a6-8001cac4e9e4.gif)

**Comment by akien-mga** [comment]
Oops :) Probably still a consequence of #8375, the play function might still expect a godot.cfg.

**Comment by cliffrowley** [comment]
Damn this was quick, keep it up you awesome people :-)
