### ISSUE TITLE
Cannot create Resource with Inner Class

### ISSUE THREAD

**Issue by rbarongr** [godotengine/godot#84455]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 11 - Godot v4.2.beta4

### Issue description

I'm trying to use Inner Classes to create specific Resources. Why? Because the Resources are only a few lines of code of exported variables to be set in the editor directly and they can inherit properties from the Class that they are part as Inner Classes. This lets me have one bigger script instead of many little ones and have readable code.

In my case I'm using this approach to set Items properties for my game. On the Class `ItemProperty` I can create Inner Classes such as `Craftable` and `Consumable`. They specify the needed tools and materials for crafting (in `ItemProperty.Craftable` as exported Arrays) and the hunger/thirst points (`ItemProperty.Consumable` as exported floats).

To demo the problem I created a minimal reproduction project with the following scripts:

- my_class.gd: This is the script with the Inner Classes (just one for the example, but **could be more**).
```gdscript
class_name MyClass extends RefCounted

class MyInnerClass extends Resource:
	@export var my_inner_class_var: float
```
- my_resource.gd: This is the script that holds as many InnerClasses as needed (just one for the example, but **could be more**).
```gdscript
class_name MyResource extends Resource

@export var my_resource_var: MyClass.MyInnerClass
```
- my_node_script.gd: This scripts is attached to the Node that will be use to create the Resources in the editor.
```gdscript
extends Node

@export var my_node_resource: MyResource 
```

With a code like this, you can have the MyResource class to hold as many Resources as needed, and create them in the editor for each use case.

What I was expecting to happen is:

1. Create MyResource in the Node Inspector.
2. Create MyResourceVar as a Resource (that is declared in an Inner Class of MyClass).
3. Edit the MyReourceVar exported variables in order to set what I need for that Node.
4. Use the Node in game.

What is happening:
1. Create MyResource in the Node Inspector.
2. When I try to create a Resource in MyResourceVar, the Editor pushes and error that reads `Cannot get class 'MyInnerClass'.`
3. Cannot create the MyResourceVar for the Node.
4. Cannot use the Node properly in game.

You can see the error that happens when I try to create the Resource for My Resource Var in the next screenshot:
![ExportedInnerClassIssueScrenshot](https://github.com/godotengine/godot/assets/91340577/caffca9e-bc59-411a-b0eb-17b0a22998bc)

Note: A possible fix would be to create a script for every class, I'm just trying to avoid that because those scripts would be many scripts with just two or three lines of code.

**Note 2: I don't know if this is a limitation _by design_ of Inner Classes or just a bug or incomplete feature, that's why I'm reporting it.**

### Steps to reproduce

1. Open the Minimal Reproduction Project
2. In the `node.tscn` main scene, select the Node root.
3. In the Inspector, select the My Node Resource.
4. Try to create a new Resource for the My Resource Var.
5. Read the error in the Editor Output.

### Minimal reproduction project

[ExportedInnerClassIssue.zip](https://github.com/godotengine/godot/files/13257325/ExportedInnerClassIssue.zip)

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/70991

**Comment by TheDuriel** [comment]
Tentatively: This is to be expected and  at the least a consequence of the design rather than a bug. Inner classes are not available to the editor the same way normal classes are.

You'll note that you can not create the inner class resource through any new resource dialogue, because it is not seen by the editor.

**Comment by rbarongr** [comment]
Thank you for you clarification.

I feel like this _should_ work, but it's fine. I will just create one class / one script for every class that I need.

If I may say, I think that Inner Classes not being available to the editor reduces the use cases for Inner Classes. Take a look at what I was trying to actually do in my project.

I have my `ItemProperty` Class that has a enum Type and the Inner Classes for Craftable and Consumable:

```gdscript
## Base class for the properties of the items.
class_name ItemProperty

## The type of the item.
enum Type {
	MATERIAL, ## Raw materials for crafting
	FOOD, DRINK ## Consumables
}

## Craftable properties of items.
class Craftable extends Resource:
	@export var tools: Array[Pickable] ## Tools needed to craft.
	@export var materials: Array[Pickable] ## Materials needed to craft.

## Consumable properties of items.
class Consumable extends Resource:
	@export var hunger: float = 1.0 ## Hunger points given or taken.
	@export var thirst: float = 1.0 ## Thirst points given or taken.
```

Then, with `Item` Class, I can create new Items as Resources.

```gdscript
class_name Item extends Resource

@export var type: ItemProperty.Type ## The kind of item.
@export_group("Properties")
@export var craftable: ItemProperty.Craftable ## Craftable properties.
@export var consumable: ItemProperty.Consumable ## Consumable properties.
```

If I am correct, in Godot 4.2 you are able to hide and show some `@export` variables. That can be manage with the Type enum, showing just the correct properties for the Type selected.

With that kind of syntax what I was trying to achieve is the same syntax that enums have (`ItemProperty.Type`) but with a Resource that can have the variables that I need for every property (`ItemProperty.Craftable` has the proper item list needed in its declaration).

I though about using that syntax because at first I just had a enum that was like `enum Type { CRAFTABLE }` but I needed to specify the tools and materials needed to craft.

But as I said, it's ok! I can create a `ItemCraftable` class or something like that, I just wanted to share my thoughts just in case this helps. 😄
