### ISSUE TITLE
Possible bugs detected

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#84467]
### Godot version

`master` branch at 5ee983188de97ae027f9b9c1443438063f708a7e

### System information

Arch Linux

### Issue description

During the code review in #84445 we stumbled upon three code sections of the engine that have not been patched and may require closer inspection.

---

1. In `platform/macos/export/export_plugin.cpp` 

There's an attempt to copy an `Image` but instead its reference count is just increased:

https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/platform/macos/export/export_plugin.cpp#L588-L591

Original comment by Riteo:
- https://github.com/godotengine/godot/pull/84445#discussion_r1382390961

---

2. In `editor/import/resource_importer_scene.cpp` 

There's an attempt to duplicate the options but the duplicate seems unnecessary:

https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/editor/import/resource_importer_scene.cpp#L2372-L2374
Original comment by AThousandShips
- https://github.com/godotengine/godot/pull/84445#discussion_r1382419617

---

3. In `core/io/resource_saver.cpp`

There's an attempt to copy a `Resource` but instead its reference count is just increased:

https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/core/io/resource_saver.cpp#L123

Original comment by AThousandShips
- https://github.com/godotengine/godot/pull/84445#discussion_r1382423305

### Steps to reproduce

N/A - This issue is related to a possible engine bug or code clean up.

### Minimal reproduction project

N/A - This issue is related to a possible engine bug or code clean up.

**Comment by Rubonnek** [comment]
I won't be able to work on these anytime soon. They are up for grabs if anyone wants to look into these.

**Comment by jsjtxietian** [comment]
I can help look into these and test whether it causes potential bugs.

**Comment by jsjtxietian** [comment]
> There's an attempt to duplicate the options but the duplicate is seems unnecessary:

I believe it is unnecessary as we just read `options_dupe`'s content  in all `import_scene` function, and here is the same call with out a copy right below it:
https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/editor/import/resource_importer_scene.cpp#L2440C2-L2440C2

**Comment by bruvzg** [comment]
> So it looks like there is no bug here because at each loop we always do all the necessay ops, but in this way we do change p_icon's data all the time, and the change will be carried to next loop, so it might not look the same compared to if we do all the op on the origin p_icon.

It looks like a bug. This should be `Ref<Image> copy = p_icon->duplicate();`, it's subsequently resizing it one step down each iteration, so it's not broken as is, but downscaling from the source image should be better for image quality (and probably the intended way for it to work).

**Comment by jsjtxietian** [comment]
> but downscaling from the source image should be better for image quality (and probably the intended way for it to work).

Yes, a bug may not be easily observed.

**Comment by akien-mga** [comment]
Which of the reported issues are still valid? Might be worth changing it to a task list so the fixed ones can be checked.

**Comment by jsjtxietian** [comment]
I believe they are all tracked and fixed.
