### ISSUE TITLE
`SurfaceUpgradeTool` breaks using `--headless --editor --quit` in CI/CD to generate `.godot/extension_list.cfg` (and probably other things too) 

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#84460]
### Godot version

v4.2.beta.custom_build [be386e187]

### System information

Ubuntu 22.04

### Issue description

Godot needs some files in `.godot/` in order to run a game, so if you have a fresh checkout of your project's code, you need to run it in the editor at least once.

A common solution to this on CI/CD, is to run `godot --headless --editor --quit` and then run your tests or export your game. (This is used in the godot-cpp CI in order to generate the `.godot/extension_list.cfg` which is needed to load a project's GDExtensions, which is how I discovered this issue.)

After PR https://github.com/godotengine/godot/pull/84200 this no longer works

That PR delays when `EditorFileSystem::scan()` runs (which is what will generate `.godot/extension_list.cfg`) and so what appears to happen is that the editor is quitting before it has a chance to scan. The `--quit` causes Godot to quit after 1 frame, but now the `EditorFileSystem::scan()` doesn't happen until a later frame, so we're quitting too early.

I suspect that there may be other files in the `.godot/` directory that should be generated (for example `global_script_class_cache.cfg`), but aren't now after PR #84200.

### Steps to reproduce

1. Checkout [godot-cpp](https://github.com/godotengine/godot-cpp)
2. Run `godot --path test/project --headless --editor --quit`
3. List the `test/project/.godot/` directory, and notice that `extension_list.cfg` is not present

### Minimal reproduction project

Use [godot-cpp](https://github.com/godotengine/godot-cpp)

**Comment by dsnopek** [comment]
cc @clayjohn

**Comment by dsnopek** [comment]
cc @YuriSizov @akien-mga

**Comment by akien-mga** [comment]
Yeah that's a problem. We could maybe add a hack that sidesteps this delay (and the upgrade tool?) when running headless?

The proper fix should be to have a proper `--import` flag that properly ensures the scan happens and finishes before quitting the editor. But that's not a short term option for 4.2.

**Comment by dsnopek** [comment]
It looks like adding `--quit-after 100` works in my testing - see https://github.com/godotengine/godot-cpp/pull/1299

Locally, it wouldn't work with `--quit-after 10` but did with `--quit-after 12`, so just to be safe I put `--quit-after 100` in the CI.

**Comment by YuriSizov** [comment]
I think this would be acceptable for now, as there are already issues with the described trick, which are only solvable with `--quit-after`, as far as I know. If we really really need an engine-side hack, then as @akien-mga suggests we can check for the headless mode and do the scan at the previous position in the loading flow.

I'm going to look into streamlining the loading steps of the editor in 4.3. Hopefully having clear loading steps will make it easier to implement the `--import `flag.

**Comment by YuriSizov** [comment]
Addressed with https://github.com/godotengine/godot/pull/84570.
