### ISSUE TITLE
Object bounding boxes are always zero

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8446]
**Operating system or device - Godot version:** v3 master, Linux

**Issue description:**
I've been wondering why performance seems to be affected when I hide objects which are already outside the screen and eventually found out that the bounding boxes are not being calculated and/or used correctly.
get_aabb() always returns a rect with all zeros too.

**Comment by reduz** [comment]
The function fixed by the pr above just affects the visible aabb used for
the editor, it's unrelated to the internals

**Comment by akien-mga** [comment]
Copying from reverted #8538:

> @reduz commented:
> Let me try to explain the problem better (cellphone typing sucks). There
are two ways to add data to a mesh (both in Mesh and VisualServer) in 3.0.
>
> One is giving an array of arrays, which is userfriendly but inefficient.
This generates aabbs automatically.
>
> The other is providing a pooled array, which is low level and only
intended to be used for serialization. Does no generation of anything for
performance.
> 
> If I'm not mistaken, the mesh aabb should be saved, or pregenerated from
the aabbs of each surface, but never generated when supplying low level
data.
>
> Unfortunately I'm away from computers for two more weeks, so can't check
much :(

**Comment by reduz** [comment]
Nevermind the original fix was right, I was completely wrong on this one and had to end up doing the same.
It can be closed, in any way.
