### ISSUE TITLE
Asset importing fails on Windows when other invalid assets exist in project

### ISSUE THREAD

**Issue by mizarc** [godotengine/godot#84473]
### Godot version

4.1.3-stable

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.4601) - 13th Gen Intel(R) Core(TM) i5-13600K (20 Threads)

### Issue description

There is an issue that occurs when invalid assets exist in your project, which causes all other valid assets in the project to fail to import. The asset in question has to have been correctly imported previously, then corrupted through external means, such as through a reimporting of a model with textures.

This only appears to occur on Windows, as the same project on MacOS does not have the issue and does allow you to continue importing assets despite the presence of an invalid asset in the project.

In the provided image, `Beau_Text_base.png` is an invalid png file, while `image1.png` is a valid image file that has attempted to be imported. Console logs display an error trying to import `Beau_Text_base.png`, correctly identifying it as a corrupt file. The remaining log displaying ERR_CANT_OPEN is an attempt to open the new valid image that was imported into the project.

![image](https://github.com/godotengine/godot/assets/49742187/714c1112-b612-4e94-a2b9-6d078e2ac3d2)

Issue has been tested on current 4.1.3 as well as 4.2 beta.

### Steps to reproduce

1. Import an asset into the project that successfully imports.
2. Reimport said asset in a way that causes it to become corrupt.
3. Import new valid asset into the project.

### Minimal reproduction project

A reproducible project has been provided containing one invalid asset. All you need to do is try to import a valid asset such as an image file.

[Sandbox.zip](https://github.com/godotengine/godot/files/13258709/Sandbox.zip)

**Comment by ShlomiRex** [comment]
I agree, I can reproduce on Windows.

**Comment by akien-mga** [comment]
Fixed by #92320.
