### ISSUE TITLE
Engine keeps crashing

### ISSUE THREAD

**Issue by nemene21** [godotengine/godot#84476]
### Godot version

4.1.2

### System information

Windows 10 - Godot_v4.1.2-stable_win64 - AMD Radeon(TM) Vega 8 Graphics

### Issue description

When opening a project the engine crashes, if I get lucky and manage to open it, it likely crashes in the next 5-10 minutes.

I opened it with a terminal to get the error:
ERROR: Condition "!texture_allocs_cache.has(p_id)" is true.
   at: texture_free_data (drivers/gles3/storage/utilities.h:111)
ERROR: Cubemap Arrays are not supported in the GL Compatibility backend.
   at: (drivers/gles3/storage/texture_storage.cpp:763)
ERROR: Attempting to use an uninitialized RID
   at: (./core/templates/rid_owner.h:199)
ERROR: Condition "!t" is true.
   at: texture_free (drivers/gles3/storage/texture_storage.cpp:705)
   
This is a fresh project with just a ColorRect and a shader that has 2 float uniforms and does nothing.

### Steps to reproduce

It happens when I open the project.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/13259645/bug.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by nemene21** [comment]
> Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

Just dowloaded it, still crashes :(

**Comment by Jordyfel** [comment]
On windows 11 with amd gpu, it doesn't crash for me. I'm seeing the errors in the console on 4.1.3, but not on 4.2 beta 3

**Comment by nemene21** [comment]
Found out why it happened, I had an infinite while loop in my shader!
Sorry to bother...
