### ISSUE TITLE
Bad default options for Generate Physics on Scene mesh import

### ISSUE THREAD

**Issue by ricky-daniel13** [godotengine/godot#84489]
### Godot version

4.1.3

### System information

Windows 10

### Issue description

On the scene mesh import window, trying to generate physics for a mesh will deafult to the decompose convex option, and instantly begin to generate its physics. However, it may be an object not suitable to be converted to a decomposed convex physics object, stalling the program trying to generate the physics, or even freezing.

![image](https://github.com/godotengine/godot/assets/47061347/d00aa9f4-4c13-4d7a-ba55-2693c48d9540)

A possible solution could be defering the generation until a re-import, or defaulting to a Shape Type that doesnt actually analyze the shape.

### Steps to reproduce

- Add model to project.
- Change its "Import As" type to scene.
- Open the Advanced Import Options
- Select a MeshInstance3D in the scene.
- On the Generate group, tick on "Physics"
- Godot will begin generating Decomposed Convex physics

### Minimal reproduction project

[GenPhysRepro.zip](https://github.com/godotengine/godot/files/13260493/GenPhysRepro.zip)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/8059.
