### ISSUE TITLE
AnimationPlayer texture leaked at exit

### ISSUE THREAD

**Issue by asolux** [godotengine/godot#84483]
### Godot version

v4.2.beta4.official.93cdacbb0

### System information

Windows 10, 64bit, Vulkan API 1.3.242 - Forward+

### Issue description

If an AnimationPlayer is instantiated from another scene, the texture of the animation leaked at exit.
Stopping the animation manually and deleting the node does not seem to help.
Tested under v4.2-beta4 mono and gd-script. Leak occurs in both versions. However, the problem does not occur in version 4.1.3.

output:
```
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
WARNING: 2 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9623)
WEditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interfaceNative mobile
XR: Removed interfaceOpenXR
ERROR: 1 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
WARNING: 2 RIDs of type "Texture" were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:9623)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2207)
Leaked instance: CompressedTexture2D:-9167777430419476631 - Resource path: res://frames.png
Leaked instance: BitMap:-9166121016152231285 - Resource path:
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with `free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
Resource still in use: res://frames.png (CompressedTexture2D)
```

### Steps to reproduce

Run the minimal project under 4.2.beta4 with the verbose attribute and close the project after the animation has been started.

### Minimal reproduction project

[GD_Min_AnimLeak.zip](https://github.com/godotengine/godot/files/13260062/GD_Min_AnimLeak.zip)

**Comment by YuriSizov** [comment]
cc @TokageItLab @SaracenOne

**Comment by TokageItLab** [comment]
I think we need to convert Resource to ObjectID internally.

**Comment by akien-mga** [comment]
Confirmed in latest `master` (cc135c58218cfd48a2bc2a1fe4805578a3ae661c).
