### ISSUE TITLE
Android export fail to launch on android 12

### ISSUE THREAD

**Issue by LimaneGaya** [godotengine/godot#84484]
### Godot version

4.1.3, 4.2.beta4

### System information

Windows 11, Godot 4.2.beta4, Compatibility

### Issue description

The game does not launch on Android 12 :
Redmi 220733SL
Device ID: JFJZ5DM79DY54DDY
Chipset: mt6761
Build: 12 V13.0.19.0.SGMMIXM
Release: 12
OpenGL: 3.0.2
CPU: armeabi-v7a
Manufacturer: Xiaomi

Works on 3.5 and doen't on 4.1.3 and 4.2.beta4

### Steps to reproduce

- Making simple scene.
- Connecting android device.
- Launching the game.

### Minimal reproduction project

[android.zip](https://github.com/godotengine/godot/files/13260109/android.zip)

**Comment by YuriSizov** [comment]
Does it work with previous 4.1 versions or on 4.0.4?

**Comment by LimaneGaya** [comment]
I am not sure what happened but at first android export didn't work for all versions of godot (4.0 , 4.1, 4.2) then i installed build tools 32 wich were the default in 4.0 (i previously had build tools 33 installed only). after that somehow new projects worked in all 4.0 , 4.1, 4.2.

I still had and issue with one project i've been working on but never tried on android before, i managed to make it work after deleting project.godot and placing a new one.

I'm not sure but i think installing build tools 32 and reseting my setting fixed the issue.
