### ISSUE TITLE
Move official demos to the Assetlib

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8448]
**Issue description:**
I've been noticing that a lot of newcomers seek solutions/examples of things which are nicely available in the official demos. However, most people don't even know they exist due to the fact that - except in Steam -  they need to be downloaded separately. 

In line with what, for instance, UE4 provides, I think it would make sense to move the demos to the Asset Lib as part of our "Online Content". 

There are many advantages to this

- newcomers that see the assetlib on start can easily see the official demos
- no need for extra download and knowing where to unzip the demos to
- no need to install dozens of demos when you just want a specific one

**Comment by Zireael07** [comment]
I was lucky to have been directed to the demos (specifically to the truck town one) before being directed to godot engine repo itself. Otherwise I wouldn't even know where to look. +1.

**Comment by eon-s** [comment]
I believe that this was the plan but I think AssetLib need first to filter by Godot version and a better way to install "templates" because is too confusing to be of any use for newcomers.

**Comment by eon-s** [comment]
Forgot to mention there is a discussion about this on the demos repo https://github.com/godotengine/godot-demo-projects/issues/33

**Comment by kubecz3k** [comment]
This issue seems to be solved now (3.0.2)
