### ISSUE TITLE
Set attenuation by inputing numbers

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#8449]
**Operating system or device - Godot version:**
Win 7 64 bit Godot 2.1.3

I would like an ability to set attenuation for lights by inputing numbers (in addition to the existing way of dragging the curve around).

Use case: I have two headlights on my car, and for obvious reasons I want their parameters to be identical when tweaking them. Using presets, when I'm constantly changing values, is an overkill.

**Comment by aaronfranke** [comment]
Can you further describe this feature request? Are you saying that you want two values to be linked, so that changing one changes the other?

**Comment by Zireael07** [comment]
We have a number above the curve. So I'd like to be able to set the attenuation value by inputting the value instead of dragging the curve around.

**Comment by AnaDenisa** [comment]
Hello :) I would like to work on this enhancement

**Comment by AnaDenisa** [comment]
I'm working with a colleague on this, we would like to know if anyone knows where this issue is in the code, we've been looking for it since two weeks ago and we're having troubles finding it.
Thank you!

**Comment by akien-mga** [comment]
The proposal refers to this widget:
![screenshot_20181123_133043](https://user-images.githubusercontent.com/4701338/48943591-fa7a1a00-ef23-11e8-9666-cb3b667b5b2e.png)

To find out where its code is, you can start by checking the `SpotLight` class:
```
scene/3d/light.cpp
463:    ADD_PROPERTYI(PropertyInfo(Variant::REAL, "spot_attenuation", PROPERTY_HINT_EXP_EASING, "attenuation"), "set_param", "get_param", PARAM_ATTENUATION);
```

There you see that the property hint is `PROPERTY_HINT_EXP_EASING` which uses `EditorPropertyEasing` from `editor/editor_properties.cpp`.
