### ISSUE TITLE
reorder tabs around on the right dock (inspector, history, node) is bugged

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#84496]
### Godot version

4.2 beta3 mono

### System information

Windows 10

### Issue description

can't really add anything extra

### Steps to reproduce

do it

### Minimal reproduction project

n/a

**Comment by arkology** [comment]
Check latest beta, should be fixed now.

**Comment by kitbdev** [comment]
This was fixed by https://github.com/godotengine/godot/pull/83966

**Comment by AThousandShips** [comment]
Closing as fixed, if the problem still occurs in the latest version please comment here
