### ISSUE TITLE
reimport of glb file does not reimport the textures of the file

### ISSUE THREAD

**Issue by atornity** [godotengine/godot#84490]
### Godot version

4.1.2

### System information

Windows 11

### Issue description

when I export a glb file from blender and I've edited a texture on one of the materials, I then go to Godot to reimport the glb the textures are not replaced with the new one. Clicking reimport on the texture itself doesn't work either. 

To get around this I have to first delete the image in godot, ignore the warning and click reimport on the glb file. The problem with this work around is that the import settings of the image are then reset every time and also it's annoying.

### Steps to reproduce

- export glb with a material and texture from blender.
- import in Godot
- edit texture and re-export glb
- re-import in Godot

(using minimal reproduction project)

- open "gltf 1/test.glb" and "gltf 2/test.glb" in a program that can preview it and observe that the two files have different textures on the suzanne mesh.
- copy "gltf 1/test.glb" to the projcet folder and observe that suzanne has "1" written on the head.
- copy and owerwrite "gltf 2/test.glb" to the project folder and observe that suzanne still has "1" written on the head (it should be "2" now).

### Minimal reproduction project

https://github.com/atornity/godot_import_gltf_issue

**Comment by AThousandShips** [comment]
This sounds the same as:
* https://github.com/godotengine/godot/issues/83154

Please confirm

**Comment by atornity** [comment]
> This sounds the same as:
> 
>     * [glTF import won't update extracted texture #83154](https://github.com/godotengine/godot/issues/83154)
> 
> 
> Please confirm

No idea how I didn't see that. 
Yes, it seems to be the same issue although It's not at all "unpredictable" for me.

**Comment by AThousandShips** [comment]
Good, then a duplicate, please search for open issues in the future :) This one was easily found with "glb texture reimport".
