### ISSUE TITLE
Autoload flag AnimatorPlayer conflicts with AnimationTree and cause stutter

### ISSUE THREAD

**Issue by ca3gamedev** [godotengine/godot#84505]
### Godot version

4.1

### System information

Windows 10 x64

### Issue description

There's an unexplicable stutter on my 2D character.

After debug, It's caused by the autoload default animation button enabled on my animation player, and later I created an animation Tree with a basic blend shape.

Seems there's a conflict between Animation Tree when Animation Player has a default autoload animation.

### Steps to reproduce

Make an animation Player, set a default autoload animation.

Now make the animation Tree to control the previous Animation Player with a basic 2D blendshape of a character having idle, walk and dash 2D sprites animations.

Set animation Tree to enable at start.

### Minimal reproduction project

Not needed.

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
