### ISSUE TITLE
TileMaps cannot clip child CanvasItems

### ISSUE THREAD

**Issue by BrixsterPlanet** [godotengine/godot#84501]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - macOS 14.1.0 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

_Preface: We had a chat in the Godot Discord about whether this is a bug or just an unsupported feature. We concluded that because it was not explicitly stated in the docs that TileMap does not support clipping, I feel it's safe to assume this is a bug._

### Issue
TileMaps do not correctly function as clipping parents; individual tiles cannot clip child CanvasItem elements or other child TileMaps.

![image](https://github.com/godotengine/godot/assets/58347007/29b42a26-62aa-4780-947a-0dc353bb74d4)

### Steps to reproduce

1. Set a TileMap's clip_children value

The issue arises when a TileMap's clipping mode is set to either `Clip Only` or `Clip + Draw`, and clipping is attempted by parenting a child CanvasItem-inhered node to the tilemap. As TileMap inherits CanvasItem, this functionality is expected but not present.

### Minimal reproduction project

[clip children example (v4.2.dev4)](https://github.com/godotengine/godot/files/13262871/Clipping.Bug.zip)

**Comment by CodestarGames** [comment]
I've also come across a need for this functionality, as I want to mask a tilemap so I can draw paint splats on top of it.

**Comment by BrixsterPlanet** [comment]
confirmed duplicate of #72611
