### ISSUE TITLE
C#: Unhandled exceptions don't crash project in exported version

### ISSUE THREAD

**Issue by juse4pro** [godotengine/godot#84512]
### Godot version

v4.2.beta4.mono.official [93cdacbb0]

### System information

Windows 11

### Issue description

I can remember that Godot 3 C# projects were able to properly crash in exported projects (how it should be). I think it was even configurable via project settings.
Since Godot 4 exceptions are just printed to the console but no crash is happening. This makes sense when working with the editor locally but in an exported project I would expect that unhandled exceptions are crashing.

Therefore it is extremely hard to test e.g. our server made in Godot because we neve see the server crashing and have to manually search for errors prints.

### Steps to reproduce

* Create node with simple C# script attached where an handled exception is thrown, e.g.:
`public override void _Ready() { Node n = null; GD.Print(n!.Name); }`
* Export the game (Windows 11 in my case) in release mode
* Run... no crash... only errors messages in console
 

### Minimal reproduction project

[ExceptionNoCrash.zip](https://github.com/godotengine/godot/files/13265303/ExceptionNoCrash.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73515.
