### ISSUE TITLE
Static func causes class to not get resolved on run

### ISSUE THREAD

**Issue by martin951** [godotengine/godot#84514]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3640) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

I have classA which inherits from Node
I have classB which inherits from classA

classA has static array
classA has static function:
`static func(id : int) -> Node3D:
    return(array[id] as PackedScene).instantiate()
`  

having this function defined, causes godot to crash with **Could not resolve class "classB"** whenever I define:
`var variable : ClassB` in another script
Removing either this typed variable from another script, or the function from the class, makes application run

Removing this typed variable, and then accessing the static func in classA via classA.func in runtime works.

I am not a very experienced developer, I hope the way I describe it make sense

### Steps to reproduce

na

### Minimal reproduction project

na

**Comment by Chaosus** [comment]
Please provide a minimal reproduction project.

**Comment by martin951** [comment]
I have tried recreating all the related classes nodes scenes etc but am unable to reproduce

**Comment by AThousandShips** [comment]
That's not the purpose of a reproduction project, it is to provide an environment where you can reproduce the bug, to test what causes it and then confirm that it has been solved, it's not about proving the existence of the bug

**Comment by martin951** [comment]
I understand, and it is not how I meant it. The recreated environment does not reproduce the error, therefore I would like to show it to someone knowledgable in real time. It is hard to tell if this is a rare editor bug or something else that I might have missed. I just want to show where exactly the problem is because I have no clue

**Comment by AThousandShips** [comment]
But a lot of those factors can't really be shown in that way, and the fact that it isn't reproducible on a fresh project points to a complex case, which means it's extra important to be able to have a reproduction project

It's also a matter of time and resources, triagers have a limited time to be able to do such hands-on triaging, so it would be best if the person who experiences the bug to try to find the conditions by working backwards to find a minimal case

**Comment by martin951** [comment]
I mean if you have 5 minutes, I would just go through all the related files, perhaps theres some trivial error I missed and it could save time if anyone happens to investigate this deeply

**Comment by AThousandShips** [comment]
I unfortunately do not have the time right now, but I'd suggest asking in the other [community channels](https://godotengine.org/community) to help identify if it is a bug or user error, and to try to produce a reproduction project

**Comment by martin951** [comment]
Funny how you have time to discuss that you do not have time

**Comment by martin951** [comment]
Little update on the matter:
`static func myFunc(id : int) -> Node3D:
	print(array)
	return null`
- app crashes
`static func myFunc(id : int) -> Node3D:
	return null`
- app runs

**Comment by martin951** [comment]
array is:
static var array : Array [preload("myscene"),preload(.... ]

Changing preload to load fixed the problem, however using preload in the reproduction project did not cause any crashes

**Comment by AThousandShips** [comment]
> Funny how you have time to discuss that you do not have time

Well if you're going to be rude then you can have a nice day...

**Comment by martin951** [comment]
It is people like you who keep Godot Engine awesome, I am sorry for being rude, I just found it ironic. And because I am an idiot, irony makes me laugh. I am also pretty depressed and whenever I feel something I have a tendency to share it. 

Please accept this honest apology.

**Comment by AThousandShips** [comment]
Thank you, I understand!

**Comment by martin951** [comment]
> Thank you, I understand!

I just realized a weird coincidence
my real class names and functions are:
ShipModels
ShipModel

initShip() etc. What are the odds ?

**Comment by AThousandShips** [comment]
Looks like there's some issue with the way static variables are loaded and static methods operated on, there might be some compiler things going on, `preload` causing issues but only selectively might point to there being some error in the files being loaded

Will do some digging in the code later today

Could you try in your main project to remove the preloads one by one and maybe identify if one specific one is causing this?

**Comment by martin951** [comment]
It is populated by a single tscn file at the moment

**Comment by martin951** [comment]
I guess there is something wrong with custom classes overall.

another issue:
classB has:
var variable1

classC extends classB:
func getVar() -> float:
return variable1

When launching, godot throws Identifier not found error

**Comment by martin951** [comment]
Additionaly, in the inspector, you have to sometimes reassign the script to a given node for it to show exported variables from the parent custom class. Perhaps this has something to do with it ?

**Comment by sandygk** [comment]
Could you try making a copy of your project and start deleting stuff/checking if the issue persists until you get to the core of the issue with a bit of luck and a good deal of patience, then hopefully you can create a minimal project that reproduces the error. I have been able to successfully use this technique in the past to triage bugs

**Comment by martin951** [comment]
> Could you try making a copy of your project and start deleting stuff/checking if the issue persists until you get to the core of the issue with a bit of luck and a good deal of patience, then hopefully you can create a minimal project that reproduces the error. I have been able to successfully use this technique in the past to triage bugs

I would have to keep in too much code which I'd rather keep private. I would really like to help figuring out what went wrong but cannot do this sorry

**Comment by AThousandShips** [comment]
It's understandable if you don't want to share, but unless you provide a minimal project we can't help and this will likely be closed

**Comment by martin951** [comment]
I am few days in already anyways, got it to work using load instead of preload. I'll try to report properly if this happens again.
