### ISSUE TITLE
ColorPicker shape icon is invisible until shape is changed

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#84519]
### Godot version

4.2 beta4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Can't see icon:
![image](https://github.com/godotengine/godot/assets/2223172/bd03929e-9109-4f83-bd4b-1fe38b3ab229)
After change:
![image](https://github.com/godotengine/godot/assets/2223172/7c4d62f5-f3d2-4652-9363-cfc55db2f486)

### Steps to reproduce

1. Add any node property of type Color (e.g. Node2D)
2. Open color picker

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
`btn_shape->set_icon` is only set in the constructor (where it can't get any values since the theme hasn't been fetched yet) and in the setter. The setter in the constructor can be removed, and it needs to be updated in the notification handler right after all the `shape_popup->set_item_icon`s.
