### ISSUE TITLE
The "restore windows on load" option does not work on macOs

### ISSUE THREAD

**Issue by saminton** [godotengine/godot#84518]
### Godot version

4.1.3

### System information

macOs 14.0

### Issue description

The "restore windows on load" option does not restore the windows size and position on opening, or reloading a project.

### Steps to reproduce

- Open a project
- Change editor window's size
- Close and reopen or reload project

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
> The "restore windows on load" option does not restore the windows size and position on opening, or reloading a project.

This option restores previously opened detached windows (and their position/size for those windows), such as the script editor and shader editor. It doesn't aim to restore the previous window position and size for the main editor window.

Closing in favor of https://github.com/godotengine/godot-proposals/issues/8358.
