### ISSUE TITLE
Artifacts in unused window areas

### ISSUE THREAD

**Issue by optlink** [godotengine/godot#8452]
**Operating system or device - Godot version:** Arch Linux - Godot master build

**Issue description:**

I'm trying to create a game such that the viewport is always rendered in 320x240 and the result is upscaled while maintaining aspect ratio. The desired effect is achieved but it seems that the unused space isn't cleared properly and artifacts remain as can be seen in the screenshot. I am running i3 and compton if this matters at all.

![2017-04-18-214641_690x310_scrot](https://cloud.githubusercontent.com/assets/13008557/25163706/0f427726-2481-11e7-8b72-de52ed6352e5.png)

**Steps to reproduce:**
1. Set stretch mode to viewport and aspect ratio to keep.
2. Run project and attempt to resize window.

**Comment by bojidar-bg** [comment]
Is this still the case on master (there might have been changes fixing it)?

**Comment by maexono** [comment]
I am also experiencing this. Arch Linux, latest master.
For me it leads to a rapidly flashing remainder of the splash screen in the unused area.

**Comment by reduz** [comment]
oh this is because black bars are not being drawn.. need to add back,thanks for reminder

**Comment by reduz** [comment]
black bars are now being drawn, so closing this one
