### ISSUE TITLE
Node Dock is not cleared when deleting selected node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#84530]
### Godot version

4.2 beta4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you select a node, the Node dock's signals and groups will point to that node. When you unselect it, the dock is properly cleared. If you instead delete the node, the dock content will stay and you can still make changes, which will go into the void (there is no way to restore the node without undoing the changes). What's worse, if you make a new scene and do the same to root node, it will result in editor crash.

Related is that the inspector does not fully clear either. The node header stays, the content is empty:
![image](https://github.com/godotengine/godot/assets/2223172/611930e6-f845-4473-827e-1aad087c01a3)

### Steps to reproduce

1. Add node
2. Select it
3. Go to Node dock's Groups
4. Press Delete to delete the node (tested with the "no confirm" action, IIRC Shift+Delete by default?)
5. The node is removed, but dock stays
6. Add groups

### Minimal reproduction project

N/A

**Comment by Cereveloper** [comment]
I reproduced this in Macbook pro (2019) Ventura 13.3.1.

**Comment by AnidemDex** [comment]
Was this solved previously? I'm working on v4.0.3.stable.official [5222a99f5] and I can reproduce this:
Before pressing `Shift+Del` (or before pressing `Del` to confirm the deletion)
![image](https://github.com/godotengine/godot/assets/7025991/675f34f8-7469-4de0-8a73-b916fb9f2ab6)

After deleting the node (any of the methods above)
![image](https://github.com/godotengine/godot/assets/7025991/39f8923b-792b-481c-9ccb-8a1513a3ff9c)

**Comment by dnoftsger** [comment]
I think I have an idea of how to fix this issue, I'll look into coming up with a solution in the next week or two.
