### ISSUE TITLE
Feature request: separate fullscreen state for scene view and script editor

### ISSUE THREAD

**Issue by tr0q** [godotengine/godot#8453]
Most of the time using script editor is best in fullscreen mode (activated with shortcut).
Most of the time you would want to use scene editor in normal mode.
Currently you have to manually switch modes every time you switch between script and scene editors. It would be nice to have editors to remember their screen mode separately, so you won't have to do extra actions when switching between editors.

**Comment by RameshRavone** [comment]
But most people might think this as a bug, may be a Editor setting for default behavior

**Comment by nunodonato** [comment]
different habits, I guess. I would never use the editor full screen, because I like clicking nodes in the scene tree to switch to different scripts/scenes.

**Comment by RameshRavone** [comment]
Awkward: 

![distration-free](https://cloud.githubusercontent.com/assets/10124094/25378201/5a2d9eb4-29c7-11e7-955b-c3e1bf030bb4.gif)

**Comment by reduz** [comment]
For visual script or dragging nodes into code, having the docks visible is
needed.. so it could be an option..

**Comment by RameshRavone** [comment]
option, where to place them, `text_editor/theme/fullscreen_with_scene_editor` or ?

**Comment by akien-mga** [comment]
Fixed by #8532.
