### ISSUE TITLE
Godot game (sometimes) runs with a black screen on steam

### ISSUE THREAD

**Issue by SgtKazoo** [godotengine/godot#84531]
### Godot version

v4.1.3.stable.official [f06b6836a]
v4.1.1.stable.custom_build [bd6af8e0e]

### System information

Works fine on:
Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21001.45002) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

Has issues on:
PC with windows 10, geforec gpu, ryzen cpu

### Issue description

I just recently put up my first game to steam, which is really exciting, but I;m getting a report from someone that the game is loading for them, but the only get a black screen. They can still navigate the menu, but have no graphics. Any idea what could be causing this issue? This issue happens for them on both the GodotSteam 4.1.1 build as well as the official 4.1.3 build. 

### Steps to reproduce

They open up the game through Steam and have tried re-installing multiple times (for GodotSteam)
They have also tried opening the exported game through Itch.io (official 4.1.3 build)

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by AThousandShips** [comment]
Without further details there's nothing that can be done sorry

You need to provide some information on what this user is experiencing, their hardware, etc.

This report unfortunately doesn't provide any information at all

**Comment by SgtKazoo** [comment]
Update:

We've also tried using the official release of Godot 4.1.3 
Works fine on my end as well as for several others, but on their end the game starts, plays audio and responds to input, but has no visuals. 

Their specs are apparently 'a normal PC with windows 10, geforec gpu, ryzen cpu, has latest updates etc."

**Comment by Calinou** [comment]
Does your project use the `viewport` stretch mode? If so, forcing MSAA in the graphics driver control panel will break rendering if the window size doesn't match the viewport size: https://github.com/godotengine/godot/issues/18320

**Comment by SgtKazoo** [comment]
Yes, it does use view port stretching. I will ask them to change this setting and see if that helps. Should I usually default to try and use canvas stretching instead to avoid this issue in the future?

**Comment by Calinou** [comment]
> Should I usually default to try and use canvas stretching instead to avoid this issue in the future?

The `canvas_items` stretch mode isn't affected by this issue, so you can do that.

**Comment by SgtKazoo** [comment]
They finally got back to me and switching to canvas fixed it. Thanks again.
