### ISSUE TITLE
CollisionObject3D Gizmo not updated after changing collision with shape_owner_* functions in a @tool script

### ISSUE THREAD

**Issue by Okxa** [godotengine/godot#84540]
### Godot version

v4.1.2.stable.arch_linux

### System information

Arch Linux

### Issue description

When using `shape_owner_*` functions to add/remove collision shapes on a CollisionObject3D (and classes derived from it) in a tool mode script, the new shape is not visible in the editor until after deselecting & reselecting the node, or after the scene (tree) is reloaded. (Either by closing and reopening it, or by switching scene tabs.)

Most likely because the gizmo that handles showing this shape (CollisionObject3DGizmoPlugin) is not redrawn when the shape owners and their shapes change. The function responsible for drawing the shapes is:
https://github.com/godotengine/godot/blob/4c96e9676b66d0cc9a25022b019b78f4c20ddc60/editor/plugins/gizmos/collision_object_3d_gizmo_plugin.cpp#L60-L86

### Steps to reproduce

1. In a new scene, create a CollisionObject3D derived node (Like StaticBody3D) and attach the following script to it:
```gdscript
@tool
extends CollisionObject3D

var shape_owner:int
var shape
@export var collision:Shape3D:
    get:
        return shape
    set(value):
        shape = value
        if get_shape_owners().size() == 0: shape_owner = create_shape_owner(self)
        shape_owner_clear_shapes(shape_owner)
        if shape: shape_owner_add_shape(shape_owner, shape)
```
2. Set the exported variable in the editor by adding a collision shape.
    - Notice how the visualization of the collision shape has not changed
3. Deselect and reselect the node, or change scene tab between another scene and this scene, or save, close and reopen the scene
    - Notice that the new collision shape is now visible

### Minimal reproduction project

[collisionobject3d-gizmo-test.zip](https://github.com/godotengine/godot/files/13270399/collisionobject3d-gizmo-test.zip)

**Comment by jsjtxietian** [comment]
Confirmed.
