### ISSUE TITLE
Invisible Walls in Browser Export

### ISSUE THREAD

**Issue by nyrrrr** [godotengine/godot#84541]
### Godot version

4.1.3

### System information

Windows 11

### Issue description

I have a simple prototype where you can walk around and jump. If you go to the far right, in Chrome you will hit an invisible wall and you cannot continue walking:
![image](https://github.com/godotengine/godot/assets/2575407/703a13d5-54ef-4233-9aea-13ac07770f1a)

In Vivaldi Browser I do not even get that far:
![image](https://github.com/godotengine/godot/assets/2575407/d9a4d089-dfa3-413d-9fc7-0ba149b02e76)

In my Windows build I can keep walking and walk off the edge of  the screen
It also seems to work in Safari.

### Steps to reproduce

1. Open the project in Godot
2. Go to Project > Export and Select Web
3. Press Export project
4. Upload it to itch.io and make it runnable (and select SharedArrayBuffer support)
5. Open the game page and run the game.
6. Walk and jump as far right as you can
7. you should hit an invisible wall at some point

Note that it only appears on Web Export. Running it in Web Browser from the engine works.

### Minimal reproduction project

[github-issue.zip](https://github.com/godotengine/godot/files/13270711/github-issue.zip)

**Comment by Swarkin** [comment]
Can confirm this, it works fine playtesting from the editor but same issue happens on itch.io.
Console doesn't seem to contain any relevant output:
<details>
  <summary>Image</summary>

  ![image](https://github.com/godotengine/godot/assets/102416174/bb7600b3-3842-4024-9d0d-ac2a2f3417e3)
</details>

**Comment by PainfulYouth** [comment]
Probably an issue on itch.io side as the issue isn't  there while in full screen mode.

Godot v4.1.2 - Chrome OS 118.0.5993.86 -  Intel UHD 600 - Intel(R) Celeron(R)  N4020 CPU @ 1.1GHz (2 Threads)

**Comment by nyrrrr** [comment]
I just imported the project in the most recent version 4.2.1 and exported it to the web. Now, the issue is gone. So I will cose this issue.
