### ISSUE TITLE
UI: Unexpected Button hover states when using touch screen (mouse emulation on Android)

### ISSUE THREAD

**Issue by rtiemann** [godotengine/godot#84548]
### Godot version

4.1.2.stable.arch_linux

### System information

Godot v4.1.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 02 Nov 2023 12:57:06 +0000 - X11 - Vulkan (Compatibility) - Mesa Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 Threads)

### Issue description

UI buttons are easily stuck in hovered state when using a touch screen. Not sure if it's the mouse emulation or related to Android export or something else. See linked repository and videos found inside.

This bug is a blocker on touch-based devices for pretty much any project using `Button`, `CheckButton`, and possibly others. It gets triggered all the time and is really very confusing for end users.

### Steps to reproduce

1. See the linked demo project (just three `Button` instances in a `VBoxContainer`).
2. Export the project to Android.
3. On an Android device, touch the center button and drag to one of the other buttons.
4. The center button enters normal state, the other button enters hovered state, just the way it works on PC using the mouse.
5. Remove the finger/pen.

_Expected:_

- All buttons should be in normal state after having lifted the finger.

_Observed:_

- Behavior is like on PC when doing the equivalent actions and not moving the mouse pointer after releasing the mouse button: the button the finger is dragged to stays in hovered state. This makes sense on PC because there is still a mouse pointer hovering over the button, but it makes no sense on a touch screen, especially after the finger has been lifted.
- The hovered state is kept even when tapping any button or other parts of the screen.
- The button goes back to normal state when dragging a finger anywhere over the screen (see `Video/video_1.mp4` in demo repo).
- Bug also occurs when simply dragging a finger across a button (see `Video/video_2.mp4` in demo repo).
- Bug also occurs when dragging from outside a button into a button (see `Video/video_3.mp4` in demo repo).
- Bug also occurs when tapping anywhere on the screen while holding a button with another finger (see `Video/video_4.mp4` in demo repo).

### Minimal reproduction project

I'll keep this Git repository around until the issue is closed:
[https://github.com/rtiemann/GodotButtonTouchBug](https://github.com/rtiemann/GodotButtonTouchBug)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/47903 (possible duplicate?).

**Comment by rtiemann** [comment]
Yes, reading the comments, this seems to be a duplicate.

I also thought about "solving" this issue by hiding it via theming, but clearly some internal state is being messed up and I don't know what side-effects to expect. I'd really prefer a proper solution.

No idea how the current implementation works, but maybe an explicit hidden/inactive/disabled/invisible mouse cursor state would help. The mouse cursor would be active when a real mouse is moved or while the screen is touched, and would be inactive when the last finger is lifted from the touch screen. Hovering states would only be allowed while the mouse cursor is active.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/47903. I've posted your findings from this issue in the linked issue.
