### ISSUE TITLE
Feature request - get local rotation

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#8456]
**Operating system or device - Godot version:**
Windows 7 64 bit Godot 2.1.3

I would like a local equivalent to get_rotation()

Use case: need to know the angle of a child object compared to the parent (e.g. a wheel on a car, a gun on a tank, a thruster on a spaceship etc. etc.)

**Comment by reduz** [comment]
get_rotation is local

**Comment by Zireael07** [comment]
Docs and in-editor help led me to believe it was global.

**Comment by tagcup** [comment]
I can't find any in-editor documentation for `get_rotation`.
Which docs do you mean?

**Comment by bojidar-bg** [comment]
There is also `get_global_rotation`.

Links to _latest_ docs:
[`Node2D::get_rotation`](http://docs.godotengine.org/en/latest/classes/class_node2d.html#class-node2d-get-rotation)
[`Node2D::get_global_rotation`](http://docs.godotengine.org/en/latest/classes/class_node2d.html#class-node2d-get-global-rotation)

Compare docs with `get_position`, which also doesn't explicitly state it is local:
> * `Vector2 get_position ( ) const`
>
> Return the position of the 2D node.

---

> * `float get_rotation ( ) const`
>
> Return the rotation in radians of the 2D node.

Therefore I think this can be closed.

**Comment by tagcup** [comment]
Docs need improvement for sure.
I'll be updating math-related docs (along with a separate write up on docs.godotengine.org) before 3.0, so hopefully these will be clear.

**Comment by aaronfranke** [comment]
To be more specific, methods in Godot that do not contain the words "global" or "local" seem to always be relative to the parent object. With rotation, this is the only local that makes sense.
