### ISSUE TITLE
`Switch to Favorite Nodes` button tooltip doesn't change

### ISSUE THREAD

**Issue by synalice** [godotengine/godot#84564]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.21029.1006) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/61655860/432289b4-5130-45e3-b603-8dd8914245c6)
![image](https://github.com/godotengine/godot/assets/61655860/ff21163e-9ab0-4d63-b0b6-9c94b19ad262)

The tooltip should change depending on if it's pressed or not.

Pseudocode:
```
if not pressed:
    tooltip = "Switch to Favorite Nodes"
else:
    tooltip = "Switch to Default Nodes"
```

### Steps to reproduce

1. Click `Scenee > New Scene`;

2. Locate this window: 
<img src="https://github.com/godotengine/godot/assets/61655860/1bbd64ae-4bde-4aee-adc6-f06e0aa963ce" width="300px">

3. Hover over "star" button;

### Minimal reproduction project

Present in any new project.

**Comment by quirkylemon** [comment]
I am almost done but I won't be able to do a pr until sometime around 4
