### ISSUE TITLE
ToSignal(GetTree().CreateTimer(1.0f),"timeout") looks not release memory after timeout

### ISSUE THREAD

**Issue by TPEFenix** [godotengine/godot#84573]
### Godot version

Godot_v4.1.2-stable_mono_win64

### System information

Windows 11 Godot_v4.1.2-stable_mono_win64

### Issue description

in the manual
https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-create-timer

GetTree().CreateTimer
after timeout ,it will not release memory

### Steps to reproduce

just write this function and keep calling
public async void TEST()
{
    await ToSignal(GetTree().CreateTimer(0.2f), SceneTreeTimer.SignalName.Timeout);
}
and you can see the memory and object keep growing

### Minimal reproduction project

[Bugreport.zip](https://github.com/godotengine/godot/files/13279504/Bugreport.zip)

**Comment by viksl** [comment]
I'm just curious but since you are on mono how long were your tests? GC takes quite a while to kick in, maybe that's what you see?

**Comment by iamdannykl** [comment]
you don't need to use createTimer() to create a new Timer every times
instead,You can use a Timer that has already been created in Godot editor, so that just a Timer can do what you want
oneshot and autostart --->false
for example: 
            Timer timer = GetNode<Timer>("Timer");
            timer.Start();
            await ToSignal(timer, "timeout");
I use Godot C# but it's the same in GDscript
