### ISSUE TITLE
Updating UVs on a surface behave differently between v4.1.2 and v4.2-beta3

### ISSUE THREAD

**Issue by nikywilliams** [godotengine/godot#84578]
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

On v4.1.2 I was working on a process to combine all static meshes (glb) into 1 in order to improve performance. Additionally, each mesh needed to have their UVs adjusted so it could utilize a single material more efficiently. This involved collecting a list of surfaces, adjusting vertices, normals, and UVs, and then adding the surfaces back to a new ArrayMesh. 

This had been working fine in v4.1.2, but after upgrading to v4.2-beta3 I noticed all the colors were not correct.

I did notice that once I ticked the "Force Disable Compression" box on the mesh import, that it appears to be working again in v4.2-beta3.
Is this possibly related to bug https://github.com/godotengine/godot/issues/84270?

Left side is v4.1.2 and the right side is v4.2-beta3
![image](https://github.com/godotengine/godot/assets/28369028/3e8ffee4-a470-4530-8109-c06e95c685b4)

I've attached a zip which contains a very minimal project for both v4.1.2 and v4.2-beta3 that only focuses on the UVs. Line 11 is where I'm setting the Scale and Offset for the UV on the mesh.

### Steps to reproduce

See attached projects

### Minimal reproduction project

[godot.zip](https://github.com/godotengine/godot/files/13281168/godot.zip)

**Comment by AThousandShips** [comment]
Please try [beta5](https://godotengine.org/article/dev-snapshot-godot-4-2-beta-5/), several issues has been solved in the last weeks

**Comment by nikywilliams** [comment]
Understood, I'll try the updated beta and report back when I'm able.

**Comment by AThousandShips** [comment]
In the future make sure you have an up-to-date version when making a report :)

**Comment by clayjohn** [comment]
This is most likely fixed by https://github.com/godotengine/godot/pull/84159 which is included in Beta4 and Beta5.

**Comment by nikywilliams** [comment]
I can confirm it is fixed in a later beta. Will close this issue.
