### ISSUE TITLE
Mesh Space additive

### ISSUE THREAD

**Issue by WOLFxxxxxx** [godotengine/godot#84580]
### Godot version

4.1

### System information

Windows 10

### Issue description

Greetings everyone,

The reason Mesh Space must be selected instead of Local Space is because Mesh Space applies its additive effect in the space of the Skeletal Mesh Component. This causes rotations to move in the same direction, regardless of the orientation of the preceding Bone in the Skeletal Mesh. This is important for Aim Offsets because in some cases, you may want the rotations coming from the Blend Space to be applied consistently, regardless of the current base pose of the character.

For example, if your character has the ability to lean sideways while aiming, this can cause the Bones' overall local space to shift towards the lean direction. If your additive type is set to Local Space, then it can cause the upward-aiming pose to be skewed, and not correctly face up. Using Mesh Space as your additive type corrects this by applying the rotation offsets from the Blend Space in the expected way.

1.Base pose with leaning.

2.Leaning and aiming up when using Local Space additive.

3.Leaning and aiming up when using Mesh Space additive.

Does Godot have the same function?
https://docs.unrealengine.com/5.0/Images/animating-characters-and-objects/SkeletalMeshAnimation/AssetsFeatures/Blendspaces/AimOffset/Additive2.png

### Steps to reproduce

#

### Minimal reproduction project

#
```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment]
What is the bug here?

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot-proposals/issues/7907.
