### ISSUE TITLE
NavigationAgent3D halts at first NavPoint

### ISSUE THREAD

**Issue by unifica** [godotengine/godot#84596]
### Godot version

4.1.3 Stable [f06b6836a]

### System information

Godot v4.1.3.stable - macOS 14.1.0 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (12 Threads)

### Issue description

The NavigationAgent3D traverses across the NavigationRegion3D to the first Navigation Point of the path but then stops. Calls to **get_next_path_position()** of the NavigationAgent3D class within _physics_process() do not seem to update to the next NavPoint resulting in the mesh/node remaining at Index 1.

### Steps to reproduce

Run project, click Blue cylinder.

### Minimal reproduction project

[Group Dynamics.zip](https://github.com/godotengine/godot/files/13289903/Group.Dynamics.zip)

**Comment by smix8** [comment]
The NavigationAgent3D needs to be a child of the CharacterBody3D node of your "police_player" scene and the movement script needs to use that node.

Currently the script points to some arbitrary placed NavigationAgent3D node that uses an unrelated Node3D parent which is not how things are supposed to be set up. 

There are other bugs or things that are not correct in that project, like using _process() with a physics CharacterBody3D node that requires _physics_process().

**Comment by unifica** [comment]
Thanks @smix8. As you said; the issue was that the Agent needs to be a direct child of the CharacterBody3D node within the inherited scene; rather than a child of the linked scene.
