### ISSUE TITLE
OpenGL: Sky contribution fails in VR

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#84598]
### Godot version

4.2.dev 5ee983188de97ae027f9b9c1443438063f708a7e

### System information

Windows 10 - Compatibility renderer 

### Issue description

When running a VR project sky contribution is not working in the compatibility renderer:

![image](https://github.com/godotengine/godot/assets/1945449/7aa19569-95c8-41a2-913b-37b81f4728a7)

It is working fine in normal mode. Can be worked around by setting sky contribution to 0 and providing an ambient color.

### Steps to reproduce

Try any project with a proper sky setup in XR, just switch to compatibility renderer.

### Minimal reproduction project

I'll try and create an MVP soon that can be used without XR hardware, but for now this can be used:
https://github.com/BastiaanOlij/godot_openxr_demo

**Comment by dsnopek** [comment]
I definitely encountered this issue as well when working on my entry for the Godot XR jam. To workaround it, I changed everything that would otherwise take its color from the sky to take it from a specific color instead.
