### ISSUE TITLE
Add a portable way to prevent files/folders from being imported

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8461]
For a game project or plugin for the assetlib, it would be useful to tell Godot to ignore some files or directories from being imported, a bit like a `.gitignore` that applies to its own folder and child folders. Such a file would also make the feature portable because it doesn't need a project setting that would require projects to be intrusively modified.

Context: in 3.0, I am developing a GDNative plugin with an src/ folder for the C++ project. During development, compilation generates lots of files with various extensions, .obj among them, and Godot thinks they are meshes and chokes at importing them. Because the import is automatic it happens as soon as I focus Godot, which is really annoying. This is one reason why I think a `.godotignore` feature would be useful.

**Comment by Zylann** [comment]
@aaronfranke yes

**Comment by davincif** [comment]
> @aaronfranke yes

It didn't worked with me.
If I put a arquive ".gdignore" inside my directory like a __init__.py file in python, Godot keeps importing stuff in it.
If a put outside, like a .gitignore file in git, nothing happens ether.
.-. How it was supposed to work?
PS.: using 3.1 version

**Comment by aaronfranke** [comment]
@davincif The directory structure should look like this:

    your_project/
        project.godot
        some_folder_to_exclude/
            .gdignore
            some_files_to_exclude

**Comment by jdknox** [comment]
@davincif I had to close the project and reopen before Godot would ignore the folder.

**Comment by cgbeutler** [comment]
Note for posterity: I get this error a lot after following the GDNative tutorial. Had to add the `.gdignore` file to the `godot-cpp` folder
