### ISSUE TITLE
`await` on `tween.finished` not cleaning up properly when node is destroyed

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#84615]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3699) - AMD Ryzen Threadripper 3970X 32-Core Processor (64 Threads)

### Issue description

When `await`ing a `tween.finished` signal, a node can be destroyed before it finishes, and the parent `await` will hang forever. 

This is an issue because if there is sequential logic in a game that is driven by tweens (i.e. a turn-based game), the outer game-loop would hang indefinitely. When there are a lot of event-driven systems, it is difficult to manage when something might be destroyed as well, so it would be very useful to have a robust recovery for coroutines that are destroyed before finishing regardless of what triggers their completion.

### Steps to reproduce

**Steps:**
1. download repro project
2. run scene (f5)

**Expected result:**
it should print "before/after" coroutine statement

**Actual result:**
It only prints the "before" statement

### Minimal reproduction project

[coroutine-repro.zip](https://github.com/godotengine/godot/files/13296549/coroutine-repro.zip)

**Comment by yoont4** [comment]
In case anyone else runs into a similar design constraint, I've made a simple class that essentially represents an "awaitable" action that can resume immediately or later (similar to JS Promises, without the return types).

```gdscript
extends RefCounted

## Waitable is just a coroutine blocker essentially, which represents ONE UNIQUE
## awaitable instance to be complete before resuming.
## Example: function that returns Waitable could mark it as complete immediately
## if there's nothing to do, or defer the completion until after several animations
## have finished.
class_name Wait

signal completed

var _is_complete: bool = false

## lifetime_dependency is the node that this depends on. If it dies, this will mark itself as completed
func _init(lifetime_dependency: Node) -> void:
	lifetime_dependency.tree_exiting.connect(complete)

## Coroutine function that returns immediately if the instance is already marked
## complete. Otherwise, awaits on the signal which can be triggered by something else.
func wait_for_completion():
	if _is_complete: return
	await completed

func complete():
	_is_complete = true
	completed.emit()
```

**Comment by timothyqiu** [comment]
I believe this is expected behavior. This applies to all signals.

Code after `await` is usually based on the assumption that some criteria met. It's logically wrong to awake the coroutine as the signal is _not_ actually emitted, meaning the criteria are not met, so it'll eventually break somewhere else.

I suggest changing your `await` into a `tween_callback()`.

**Comment by yoont4** [comment]
Thanks for the feedback @timothyqiu, I realize now that what I originally wanted doesn't generalize well 😅 I'm basically running into a separate architectural problem of awaiting recursive side-effects to finish before moving on with some action, and isn't really related to coroutine behavior. Closing this.
