### ISSUE TITLE
Update issues with AnimationPlayer's string-tracks

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#84612]
### Godot version

v4.2.beta.custom_build [5ee983188]

### System information

Windows 10 - Vulkan (Forward+)

### Issue description

Handling of string-tracks seems to have been changed since Godot version 4.1.3:

- When using continuous update mode the string used is always fetched from the RESET-track
- When using discrete update mode the value is only updated when the cursor hits exactly the key. This causes the value to be never updated if the key is not in "Snap-divisible" location and using the cursor to skim through the animation.

Both of the update modes work as expected in Godot 4.1.3 and earlier (also tested with 4.1 stable).

Video:

https://github.com/godotengine/godot/assets/50438441/a8b0bcce-7a13-4484-9d6e-d90395ee0cc1

There is also a slight difference with the key handling related to floats when using discrete update mode and playing backwards (which isn't described but can be seen in the video since I noticed it after recording). In 4.1.3 the value seems to be the last value in "real time chronological order" (= in this case the lower progress bar "lags behind" in both playing directions), but in 4.2 the value seems to be fetched from the previous key (in "track order"). Personally I think the new 4.2-way is more logical as the animation works the same regardless of the playing direction and is consistent with how the editor works when using the cursor, though.

Might be related(?): https://github.com/godotengine/godot/issues/69591

### Steps to reproduce

Add a string-track with some keys to AnimationPlayer or open the MRP and move the cursor around the animation (or play it back).

### Minimal reproduction project

[AnimStringIssue_41.zip](https://github.com/godotengine/godot/files/13295684/AnimStringIssue_41.zip)
(The MRP is in 4.1-format as this is about changes in behavior and the project can also be opened with 4.2 (although it converts it when opening)).

**Comment by TokageItLab** [comment]
I'm working now as https://github.com/godotengine/godot/issues/83401
