### ISSUE TITLE
Feature request: Get position in viewport

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8462]
So local vs global coordinate systems were a bane of my existence for a pretty long time. Moving children of different parents to each other (for sick UI effects for example) can get insane with get_position_in_parent()+get_parent().get_position_in_parent() and so on for each parent you have. 

What I'm sure a lot of people will find use of is a quick and simple way to just grab coordinates of a node with viewport 0.0 being origin and move them based on that.

**Comment by volzhs** [comment]
we have `Control.get_global_pos()` and `Node2D.get_global_pos()`
isn't that enough for you?

**Comment by tamkcr** [comment]
global is not good enough for complex hierarchy, for 2d `canvasitem::get_viewport_transform ( )` should work per the docs.
> Get this item’s transform in relation to the viewport.

**Comment by ArcFutahito** [comment]
@volzhs no it's not. I can give you an example: You have CanvasLayer/Control/GridContrainer/Sprite and CanvasLayer/Control2/Sprite in different locations. Try to lerp one node to another with global_pos, you'll see why I brought up this issue. 
@tamkcr Yes, that's exactly what I was looking for. Thank you very much!
