### ISSUE TITLE
TransformVectorMult node in VisualShader return a vec3 instead of a vec4, causing the w component of the vector to get dropped.

### ISSUE THREAD

**Issue by americoperez49** [godotengine/godot#84622]
### Godot version

4.1.3.stable (I also tried on 4.2 Beta4 and I believe QbieShay tried on the lastest Master)

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4601) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Here at the request of QbieShay.

When using the TransformVectorMult node in VisualShader, the TransformVectorMult node outputs a vec3 instead of a vec4, causing the w component of the vector to get dropped.

![Example of truncation](https://github.com/godotengine/godot/assets/17209617/7b9fe37e-20c5-4151-af4c-15c1df9aabc2)

From mine and QbieShay's understanding, TransformVectorMult should output a vec4. This can be seen in the generated GDShader code that the editor generates when enabling Proximity Fade in a Material

https://github.com/godotengine/godot/assets/17209617/136ace4a-7dae-4a0e-8ea0-2296571f1d4d

### Steps to reproduce

In the visual shader editor, mulitply a vec4 by the INV_PROJECTION_MATRIX  using the TransformVectorMult node and you will see that a vec3 is the output instead of a vec4

### Minimal reproduction project

[Example Reproduction.zip](https://github.com/godotengine/godot/files/13298783/Example.Reproduction.zip)

**Comment by AThousandShips** [comment]
According to the [documentation](https://docs.godotengine.org/en/latest/classes/class_visualshadernodetransformvecmult.html) it is supposed to take a `Vector3`, not a `Vector4`

**Comment by americoperez49** [comment]
Right but then you lose the W component of a vector4, which you need in order to recreate proximity fade using visual shader.

**Comment by americoperez49** [comment]
As far as I know, there doesnt seem to be away to multiply the INV_PROJECTION_MATRIX and the Screen_UV to convert from screen space to world space. You lose the W component, which according to the generated GDShader code, is required to do the math correctly.

**Comment by americoperez49** [comment]
If TransformVectorMult is not the correct node that should be used, then what would be the alternative?

**Comment by AThousandShips** [comment]
Please do not make multiple comments in a row, instead edit your comments, that way you won't cause notifications unnecessarily

To your question my answer is I don't know, but the documentation says that it is not this way, could be an error there, but this node is documented

**Comment by americoperez49** [comment]
> Please do not make multiple comments in a row, instead edit your comments, that way you won't cause notifications unnecessarily
> 
> To your question my answer is I don't know, but the documentation says that it is not this way, could be an error there, but this node is documented
> 
> It is supposed to use a `Vector3`, see the code generating it:
> 
> ```c++
> 	if (op == OP_AxB) {
> 		return "	" + p_output_vars[0] + " = (" + p_input_vars[0] + " * vec4(" + p_input_vars[1] + ", 1.0)).xyz;\n";
> 	} else if (op == OP_BxA) {
> 		return "	" + p_output_vars[0] + " = (vec4(" + p_input_vars[1] + ", 1.0) * " + p_input_vars[0] + ").xyz;\n";
> 	} else if (op == OP_3x3_AxB) {
> 		return "	" + p_output_vars[0] + " = (" + p_input_vars[0] + " * vec4(" + p_input_vars[1] + ", 0.0)).xyz;\n";
> 	} else {
> 		return "	" + p_output_vars[0] + " = (vec4(" + p_input_vars[1] + ", 0.0) * " + p_input_vars[0] + ").xyz;\n";
> 	}
> ```

In this code, you are mulipltying a vector4 by something adn returning a vec3. Why the truncation?

**Comment by AThousandShips** [comment]
Because you are feeding a `Vector4` to a method that takes `Vector3`? The problem here is not the truncation but the lack of an error or warning because you are giving it an incorrect argument

**Comment by americoperez49** [comment]
> Because you are feeding a `Vector4` to a method that takes `Vector3`? The problem here is not the truncation but the lack of an error or warning because you are giving it an incorrect argument

I understand what the current documentation says and I understand that what I am doing is "incorrect" according to the documentation. But then how are you supposed to do this calculation using the visual shader?
` vec4 world_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV*2.0-1.0,depth_tex,1.0);`

**Comment by AThousandShips** [comment]
As I already answered, I don't know, all I know is that you are not using the method correctly *as it currently exists*

**Comment by americoperez49** [comment]
> As I already answered, I don't know, all I know is that you are not using the method correctly _as it currently exists_

Ok well that why I was asked to create this issue. To bring up the fact that you cant do this using the TransformVectorMult node  _as it currently exists_ and that the node might need changing, unless this is really the intended result and there is another more correct way to implement the calculation mentioned above

**Comment by AThousandShips** [comment]
Then that's the area for a [proposal](https://github.com/godotengine/godot-proposals) as there's no bug here (except possibly for the lack of a warning/error)

**Comment by americoperez49** [comment]
> Then that's the area for a [proposal](https://github.com/godotengine/godot-proposals) as there's no bug here (except possibly for the lack of a warning/error)

Ok. I was given incorrect instructions then. Can this be moved to [proposal](https://github.com/godotengine/godot-proposals) or do I have to recreate the post in [proposal](https://github.com/godotengine/godot-proposals)?

**Comment by AThousandShips** [comment]
You need to fill out the details in the proposal as it is different

I am sorry you got the incorrect instructions, make sure you look at the instructions in the report form and the issue form to ensure the instructions you got were correct :)

**Comment by AThousandShips** [comment]
Superseded by:
* https://github.com/godotengine/godot-proposals/discussions/8375
