### ISSUE TITLE
`DisplayServer.screen_get_refresh_rate()` doesn't take iOS power saving settings into account

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#84634]
### Godot version

4.1.2.stable

### System information

iOS 17 (iPhone 15 Pro) - vGodot 4.1.2.stable - Vulkan (Mobile) - Apple A17 Pro

### Issue description

Whether this is a bug or not is a matter of debate, but on iOS devices with ProMotion displays (iPhone 13, 14, and 15 Pro devices as well as the Pro iPads since 2018) lower their refresh rate to 60 when in low power mode. However, Godot will still return 120 when DisplayServer.screen_get_refresh_rate() is called. I am not sure what the behavior on Android is, my only test device has a screen that maxes out at 60.

This being "corrected" (if this is an error) could be useful in situations where you want a game to run at half the refresh rate of the display for energy saving purposes. Ex: 60 when battery saver is off and 30 when battery saver is on.

### Steps to reproduce

Create a project that displays DisplayServer.screen_get_refresh_rate(), run on an iPhone with low power mode enabled.

### Minimal reproduction project

[ScreenRefreshMinimal.zip](https://github.com/godotengine/godot/files/13301547/ScreenRefreshMinimal.zip)

**Comment by ztc0611** [comment]
I was browsing through the same pages when I got the notification for this haha. Maybe it could call for low power mode state (https://developer.apple.com/documentation/foundation/nsprocessinfo/1617047-lowpowermodeenabled#) and set it to 60 if true, however maybe it might be better to just add a function somewhere to call for low power mode state? 

I'm not certain if screen_get_refresh_rate() is intended to get the maximum refresh rate the screen supports, or just the maximum it is offering to the user. The docs stating `Returns the current refresh rate of the specified screen.` reads to me as the latter, but again that's a matter of opinion.

**Comment by ztc0611** [comment]
This page might provide a hint. I'm in the process of figuring out how to access the CADisplayLink of the project in order to see if this would provide a fix.
https://developer.apple.com/documentation/quartzcore/cadisplaylink
```Swift
// Calculate the actual frame rate.
let actualFramesPerSecond = 1 / (displaylink.targetTimestamp - displaylink.timestamp)
```

**Comment by bruvzg** [comment]
> let actualFramesPerSecond = 1 / (displaylink.targetTimestamp - displaylink.timestamp)

That's going to give actual frame rate (lower value is specific project is lagging or higher if VSync is off), not display frame rate which `screen_get_refresh_rate` supposed to return.

**Comment by ztc0611** [comment]
Is this an acceptable solution? I've tested it and it works.

```cpp
float DisplayServerIOS::screen_get_refresh_rate(int p_screen) const {
	float fps = [UIScreen mainScreen].maximumFramesPerSecond;
	if ([NSProcessInfo processInfo].lowPowerModeEnabled){
		fps = 60;
	}
	return fps;
}
```

**Comment by bruvzg** [comment]
> Is this an acceptable solution? I've tested it and it works.

It should be fine, if this behavior is the same on all models, which seems to be the case.

**Comment by ztc0611** [comment]
As far as I am aware, all iPhones and iPads exhibit the same behavior when it comes to low power mode. I scanned the docs and I didn't find anything that contradicts this. 

I'll send the PR now.
