### ISSUE TITLE
PointLight2D doesn't work on Tilemap that uses shader if you have an empty light function

### ISSUE THREAD

**Issue by dehboxturtle** [godotengine/godot#84639]
### Godot version

4.2 Beta 4

### System information

Windows 11

### Issue description

Hello! I ran into something that I thought was a bit confusing the other day. I wrote a shader for my tilemap and it stopped interacting with my PointLight2D Nodes. I spent quite a while trying to figure it out and then just by chance I noticed that my shader still had the empty light() function that the template creates. When I removed it it started working again.

It would be a nice QOL update to add a comment or something to that template function indicating to people that it is overriding ALL lighting behavior (as opposed to being additive or doing nothing if left empty). I'm sure this is obvious to more experienced developers, but since this is my first shader I only really found it by pure chance as I couldn't find this documented anywhere or in any videos.

### Steps to reproduce

Make any shader, leave the light function empty. Observe that Nodes that use that shader no longer interact with light sources.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
This will be fixed once we merge https://github.com/godotengine/godot/pull/84594

**Comment by dehboxturtle** [comment]
Nice, great to hear it is already taken care of :D
