### ISSUE TITLE
Using clamp(variant, min, max) with Vector3 returns incorrect values

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#84655]
### Godot version

4.1.3

### System information

Windows 11

### Issue description

clamp(variant, min, max) on a Vector3 does not return the correct value, you have to use Vector3.clamp(min, max).

### Steps to reproduce

Run the following code in a gdscript:
```
var vec := Vector3(5.0, 5.0, -1.0)
var clamp_variant = clamp(vec, Vector3(-4.0, -4.0, -4.0), Vector3(4.0, 4.0, 4.0))
var clamp_vector = vec.clamp(Vector3(-4.0, -4.0, -4.0), Vector3(4.0, 4.0, 4.0))

print("Vector3 is: " + str(vec))
print("Variant clamp to -4, 4 is: " + str(clamp_variant))
print("Vector3 clamp to -4, 4 is: " + str(clamp_vector))
```
It will print:
```
Vector3 is: (5, 5, -1)
Variant clamp to -4, 4 is: (4, 4, 4)
Vector3 clamp to -4, 4 is: (4, 4, -1)
```

### Minimal reproduction project

NA

**Comment by AThousandShips** [comment]
This is a different `clamp` it returns `min` if `v < min`, see:
> Clamps the value, returning a Variant not less than min and not more than max

The `Vector3.clamp` method instead does element wise clamping:
> Returns a new vector with all components clamped between the components of min and max, by running @GlobalScope.clamp on each component.

The difference is intentional, but could be documented more clearly

**Comment by AThousandShips** [comment]
I will look at writing some note in the documentation about this for those who do not notice the example code to clarify that the clamping is not element-wise

**Comment by Arnklit** [comment]
Ah ok. Sorry if this is dumb question. But is the clamping that the variant method does useful in some other way? I don't see what use it has.

**Comment by AThousandShips** [comment]
I don't either TBH, but we can't remove it without breaking things, it simply supports any `Variant` type that supports the `<` operator

**Comment by AThousandShips** [comment]
And to be clear the confusion is natural, the documentation was more unclear than I had first thought, please see the PR linked to this and see what you think about the changes to the documentation 🙂

**Comment by Arnklit** [comment]
Thanks a lot. Seems good to update the docs a bit.

I'm not sure I feel like the min/max operation makes any sense to do on a Vector3 at all. It looks like it's just operating on the first component for the comparison, I really don't see how this is useful at all, mostly just seems confusing that it's there at all.

Feel free to close this.

**Comment by AThousandShips** [comment]
Agreed, but it's simply a result of how the method is done, it just takes `min if value < min else max if value > max else value` or equivalent, it's convenient, and people might want it for various reasons as comparison is allowed 

Will be closed when the PR is merged

**Comment by voithos** [comment]
I recently noticed this for `Vector2` as well, which was surprising.

```
clamp(Vector2(0, -4), Vector2(-1, -1), Vector2(1, 1))
-> returns (0, -4)
Vector2(0, -4).clamp(Vector2(-1, -1), Vector2(1, 1))
-> returns (0, -1)
```

I agree that this is confusing, and it seems somewhat surprising that `clamp(Vector2, ...)` doesn't just call `Vector2.clamp(...)` under the hood. If it can't be changed due to backwards-compatibility, might be a good idea to emit a warning for typed code.
