### ISSUE TITLE
[Godot4.x] `get_system_time_msecs` was miss

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#84651]
### Godot version

v4.2.beta2.official [f8818f85e]

### System information

Windows 10, 64bit

### Issue description

I'm try convert a Godot3 project and found the api `get_system_time_msecs` was miss.

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by timothyqiu** [comment]
The equivalent is now `Time.get_unix_time_from_system()`, it returns a float in seconds.

**Comment by CsloudX** [comment]
Oh, Thanks.
