### ISSUE TITLE
TSCN files that embeds 2 images are not all loaded + side effects

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#8465]
**Operating system or device - Godot version:**
Mageia 5, Godot 2.1.3, probably affects master

**Issue description:**
Probably related to #4240 
Loading a TSCN file that embeds 2 images has the following effects:
- only the 1st image is loaded.
- the second is not (appears as null in Godot editor)
- certain following values are loaded either

**Steps to reproduce:**
1/ Clone the following branch : https://github.com/StraToN/escoria/tree/c-cesar-master
2/ Import project in Godot (device/ folder)
3/ Load scenes/test/test.tscn
4/ Confirm that:
- scales contains an image
- lightmap is null (should be an image)
- bitmaps_scale is 1,1 (should be 2.35, 1.5)

**Link to minimal example project:**
https://github.com/StraToN/escoria/tree/c-cesar-master

Fixing this would allow us to pull https://github.com/godotengine/escoria/pull/4 in Escoria
Another solution would be of course to use external resources, not embed in TSCN.

**Comment by eon-s** [comment]
I wonder if the >million collumns long lines break the resource loader.

**Comment by akien-mga** [comment]
A solution is not to embed raw image data in scene files.

**Comment by StraToN** [comment]
I kind of agree with @akien-mga . This bug could be simply avoided by forbidding it. Besides, it grows the TSCN file to a tremendous size, for almost no profit since it's even longer to load.

**Comment by eon-s** [comment]
As an alternative, a embedded resource of X size could be saved as external tres file instead (sometimes you want text) naming it after the scene, like `scenename.resid.tres`.

**Comment by bojidar-bg** [comment]
@eon-s This should go in #4240, plus, it would be a workaround (check the other issue too, since Image resources don't exhibit the problem when saved as .scn)

**Comment by eon-s** [comment]
Is correct the use of "Image" in that project?
And should be able to "export" it? because you can't do anything with Image, not even create a new one on the inspector, only load and it loads the image as text on the scene file.

A ImageTexture can be created or load as external resource that points to a file, but Image can't.

**Comment by punto-** [comment]
The reason why it was made with an Image is that we use the pixels from the
image as data (a lightmap, and scalemap), and you not all systems allow you
to retrieve the pixels from a Texture once it's registered in the
VisualServer

**Comment by StraToN** [comment]
@punto- That's a bit technical here, do you mean ImageTexture.get_data() (http://docs.godotengine.org/en/stable/classes/class_imagetexture.html?highlight=imagetexture#class-imagetexture-get-data) won't work on every platform?

**Comment by punto-** [comment]
It's not guaranteed to work on every platform, especially on a release
build. In general it's encouraged to use the get* methods, since the server
apis are supposed to be asynchronic

**Comment by StraToN** [comment]
@punto- I spoke with @reduz about this issue and he advised to close this issue since images are now Resources, not embedded in TSCN files anymore. Does this suits you for the current Escoria demo scene?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
