### ISSUE TITLE
Godot 3.0 bad default snake_case results with classes that have 2D in the name

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#8467]
**Operating system or device - Godot version:**
3.0 alpha

**Issue description:**
If you enable snake_case, and add for example "CollisionShape2D", it turns into "collision_shape2_d".
What is expected is "collision_shape_2d". 

**Steps to reproduce:**
1. Turn on snake_case
2. Add CollisionShape2D.

**Comment by toby3d** [comment]
Same effect after added Node2D as "node2_d" and others.

**Comment by RayKoopa** [comment]
Suddenly it's a bug, but when i mentioned it when testing the snakecase implementation, everybody said 'good enuff' :D
