### ISSUE TITLE
Godot UI is slow when trying to open file in attach script window on Linux, mobile and forward+ compatibility.

### ISSUE THREAD

**Issue by PHxxDragon** [godotengine/godot#84671]
### Godot version

v4.1.3.stable.mono.official [f06b6836a]

### System information

Godot v4.1.3.stable.mono - Ubuntu 22.04.3 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 Threads)

### Issue description

The open script / choose location window gets slower and slower after clicking on the panel several times.

There is a delay (a few seconds) until the window response after I click on one panel.

### Steps to reproduce

- Create an empty project, using forward+ or mobile renderer (compatibility renderer is fine).
- Create a node2D
- Click attach new script button to open "Attach Node Script" window
- Click on the folder icon on either the row labeled "Inherits" or "Path" (to choose a script file)
- Keep clicking on the panels (switching between 'Favorites', 'Recent', 'Directories & Files' panels) until the response is slow.

### Minimal reproduction project

N/A

**Comment by PHxxDragon** [comment]
I switched from Wayland to X11 / Xorg and there is no lags anymore. This only happens on Wayland it seems.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74168.
