### ISSUE TITLE
LightOccluder2D hides normal map

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8468]
https://godotengine.org/qa/14215/is-it-possible-to-have-a-normal-mapped-sprite-cast-shadows

Create a 2D light and a 2D sprite, attach a normal map. Add a light occluder 2D to the sprite to create shadows. The normal map is hidden.

Godot 2.1 - Ubuntu 16.04

**Comment by eon-s** [comment]
Have you tried different cull modes on the occluder?

**Comment by JarLowrey** [comment]
Wow you're amazing! Never heard of cull mode, sorry to bother. Clockwise worked.
