### ISSUE TITLE
Image size in vram reported is many times larger of it's original size

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8470]
**Operating system or device - Godot version:**
Godot 2.1 official linux kubuntu 16.10

**Issue description:**
When looking at reported image size in video memory it reports allocated memory in chunks from 3x and up of it's size.

**Steps to reproduce:**
1. Open project with any PNG images in scene. 
2. Open debugger "video memory" tab and hit refresh
3. Compare size of original image with reported size of allocated space for it in debugger. 

Example: Godot project icon size is 2kb. When loaded in the game it's 16 kb. 1900x1000 something screenshot is 1.3 mb. When loaded in the game it's reported size is 12 mb.

**Comment by ducdetronquito** [comment]
Same issue here !

**Operating system or device - Godot version:**
Godot 2.1.2, Linux Ubuntu Mate 16.10

If I assign a 4Mb texture (PNG image) to a sprite, the debugger tells me it uses 64Mb.

**Comment by eska014** [comment]
Textures aren't stored in VRAM in their original format, the GPU would waste a lot of time with decompression otherwise. That's why you're seeing a size difference.

**Comment by ArcFutahito** [comment]
Yeah, we figured it out. Increase in size is happening because PNG gets decompressed. Closing the issue now.
