### ISSUE TITLE
Auto-generated lightmap-probes have wrong colors

### ISSUE THREAD

**Issue by BernhardMt** [godotengine/godot#84714]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3713) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

When baking lightmaps for a scene, some of the lightmap probes have a bright colors (mostly green, sometimes yellow, red or blue) that are not correct for the given lighting situation. It seems that this is happening for probes that are inside geometry, but can also happen for probes that are outside (see image 2).

![lightprobes1](https://github.com/godotengine/godot/assets/23431415/848b5a4d-2d0d-42dd-b5b0-27e95a8da1c2)
![lightprobes2](https://github.com/godotengine/godot/assets/23431415/398a7775-897f-4c28-bc3b-3104a33a7bdc)

### Steps to reproduce

- Create a new 3D Scene
- Import .glb object with Lightbaking set to "Static Lightmaps" so that lightmap UVs are generated
- Add the objects to the scene
- Add a WorldEnvironment Node to the scene with background set to "Clear Color" or "Custom Color"
- Add a LightmapGI node
- Bake Lightmaps

### Minimal reproduction project

[LightprobeTest.zip](https://github.com/godotengine/godot/files/13319848/LightprobeTest.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77168.
