### ISSUE TITLE
Output tab very slow to activate when log is very long

### ISSUE THREAD

**Issue by thygrrr** [godotengine/godot#84718]
### Godot version

4.2.beta

### System information

Windows 11

### Issue description

When you have accumulated a lot of log lines, say, 500k lines, it takes a long time (10 seconds+) to activate the output tab.

### Steps to reproduce

1. generate a lot of log output
2. switch to debugger tab, then to output tab
3. observe: editor hangs
4. clear the output
5. observe: clearing also takes substantial time (but less than step 2)

### Minimal reproduction project

none needed, hopefully

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/84499.

**Comment by thygrrr** [comment]
This bug also results in long times waiting for the engine to close if a lot of output has accrued.

**Comment by TheSofox** [comment]
I'm trying to work on a fix for this, but need ran into Issue #85096 which I was kind relying on. I'm using a suggested fix for testing, but can't rely on it for the final push.

In the meantime, could I get some guidance on where the setting for changing the lines should be?
I'm thinking: Editor Settings -> Docks -> Log -> Max Lines.
Right now Docks only has Scene Tree, FileSystem and Property Editor, so I'd need to add "Log" to it as a category, even though I'll only be adding a single setting.

I'm running into another tiny thing where by removing lines at the start of the log, the whole log goes invisible for a brief moment while it refreshes, meaning if there's a flood of output you don't see anything until it calms down. May need to tweak something in RichTextLabel.

**Comment by Calinou** [comment]
> Right now Docks only has Scene Tree, FileSystem and Property Editor, so I'd need to add "Log" to it as a category, even though I'll only be adding a single setting.

The log isn't a *dock* but a *bottom panel*, so it should be in a different location. I'd personally reuse **Run > Output** for this.

**Comment by TheSofox** [comment]
Okay got it:
![image](https://github.com/godotengine/godot/assets/3089525/03974766-2437-4d57-ba04-f087ee9e2f0e)

Still waiting on #85096 before I'll do a push though.
