### ISSUE TITLE
Checkbox shows unchecked icon texture when toggled(true) is emitted

### ISSUE THREAD

**Issue by opyate** [godotengine/godot#84710]
### Godot version

4.1.3

### System information

Godot v4.1.3.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Compatibility) - NVIDIA RTX 6000 Ada Generation () - AMD Ryzen Threadripper PRO 5955WX 16-Cores (32 Threads)

### Issue description

This code shows that the checkbox gets the correct initial value (by virtue of the print statement), but the "unchecked" icon texture is still displayed.

```
extends CheckBox


var checkbox_initial_value = true

func _ready():
	toggled.connect(on_toggled)
	toggled.emit(checkbox_initial_value)


func on_toggled(val: bool):
	print("got this value for checkbox: ", val)

```

### Steps to reproduce

Import and run this project:

https://github.com/opyate/godot-checkbox-not-showing-correct-icon-texture

### Minimal reproduction project

[godot-checkbox-not-showing-correct-icon-texture.zip](https://github.com/godotengine/godot/files/13319144/godot-checkbox-not-showing-correct-icon-texture.zip)

([this repo](https://github.com/opyate/godot-checkbox-not-showing-correct-icon-texture) zipped)

**Comment by bruvzg** [comment]
> `toggled.emit(checkbox_initial_value)`

This code will directly call your function, it won't affect checkbox state in any way. Use `button_pressed = value` to set the state (and call `toggled` callback if state is changed).

**Comment by opyate** [comment]
> Identifier "button_pressed" not declared in the current scope.

**Comment by opyate** [comment]
Thanks, I got bitten by the classic problem of `button_pressed` not being documented in `CheckBox` and not checking the parent docs.

**Comment by opyate** [comment]
Devs, if you're reading this: We ought to really fix the docs to inherit the docs from parents, even if we put it in a different coloured DIV or something. The UX will be a lot better.
