### ISSUE TITLE
Editor: Cannot scroll Resource list popup

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#84725]
### Godot version

4.2 Beta5

### System information

Win 10 Nvidea

### Issue description

https://github.com/godotengine/godot/assets/47016402/f8a4ce1b-505c-433d-bbcf-541eaf3a81be

### Steps to reproduce

1. Go to the Inspector and click the + to add Metadata
2. Give it a name and chose the Resource type
3. Then click on "empty" to chose the Resource you want 
4. Observe how you can't scroll the list (neither with scroll wheel nor scrollbar), and also can't search the list or jump to sections with the keyboard by typing the name of the resource
5. Observe how the Inspector in the background is scrolled instead

### Minimal reproduction project

N/A MRP not required and faster to test without.

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot/issues/78760
* https://github.com/godotengine/godot/issues/74055
