### ISSUE TITLE
Some setting values without limit could cause crash

### ISSUE THREAD

**Issue by gshadows** [godotengine/godot#84727]
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Godot v4.2.beta5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 5500 XT (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD FX(tm)-6300 Six-Core Processor (6 Threads)

### Issue description

There's a number of project settings, that has no limit for possible values range. In some cases, setting invalid value (mostly zero or negative) could cause editor crash on project open or game crash on start.
I suppose such limitation should be added (also it was in 3.x at least for some of them).

I created a commit that fixes this issue by adding PROPERTY_HINT_RANGE to forbid negative or zero values. But using PROPERTY_HINT_RANGE also has highest value limit, which is unknown to me without knowledge of engine internals. Because of that, I created this issue report instead of PR, to discuss values correctness. Please take a look:
https://github.com/godotengine/godot/compare/master...gshadows:godot:fix_options_range

Example of possible values is on image below. I found this bug when actually set some of such options to -1 accidentally.
![Example of invalid values](https://github.com/godotengine/godot/assets/18046412/662e3113-29e0-4985-af7b-4ce2cec28636)

### Steps to reproduce

1. Create empty project or open existing (assuming you have backup).
2. Open project settings and enable Advanced Settings (not all affected settings are advanced, this is just a good example).
3. Select "Reflections" and set any values as on image above, for example roughness layers = -1.
4. After project save and attempt to re-open, editor will crash.
5. The only way to recover is manual edit of project.godot (or restore from backup/vcs).

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
The values in the commit look good to me. I'd remove `or_greater` from all the reflection settings though, as huge values outside the specified range are unsupported by GPUs or are extremely slow.

**Comment by gshadows** [comment]
Thank you for review! I've updated code according recommendations and created PR.
