### ISSUE TITLE
Clients can't connect to my ENet host, but other game server hosts work.

### ISSUE THREAD

**Issue by noche-x** [godotengine/godot#84730]
### Godot version

v4.1.2.stable.official.399c9dc39

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

People can't connect to my server hosted via `ENetMultiplayerPeer.create_server()`

Things I have done:
- Tested both on Linux and Windows
- Forwarded ports from 24000 to 30000 to the correct computer
- Enabled DMZ to point to the computer I host on
- Disable DMZ just in case
- Disable my routers Firewall
- Add firewall rules for both UDP and TCP on the specified port
- Disable my computers firewall
- Disable IPv6

I've tried every combination of toggling my firewall, adding ports inbound and outbound to my firewall, adding a range of ports that are around the port that I specify in `.create_server`, disable my routers and my computers firewall, enable and disable DMZ. But still people can't connect to my server.

Someone else tried to host and it worked, I was able to connect, so I thought it might be a network or ISP issue on my side but I can host another game's server (UDP) on the same port and It works fine. That other game uses a master server to put a entry of itself with its IP and port but when people connect it connects via that IP so it's not a proxy. 

Godot was trying to use IPv6 (`netstat -aon`) so I thought that might be the problem but after disabling IPv6, it started to use IPv4 and the entry was like the other game server. `0.0.0.0:27541`

I'm going to try to `strace` my exported game and that other game server to see the differences between system calls that relate to sockets.

### Steps to reproduce

- Create a peer via ENetMultiplayerPeer.new()
- Host a server with peer.server_create(27541, 32)
- On another client, create a peer and connect with peer.create_client(address_bar.text, 27541)

### Minimal reproduction project

N/A

**Comment by Irantwomiles** [comment]
Do you have any issues while testing with multiple clients locally? It sounds like a port forwarding issue.

**Comment by noche-x** [comment]
https://en.wikipedia.org/wiki/Carrier-grade_NAT was the issue, I opted into my ISPs static IP service and the problem got solved. Still wondering how that other game got hosted, maybe tunelling.
