### ISSUE TITLE
Missing/disappearing meshes when number of objects past ~16000 / mono / RenderingServer

### ISSUE THREAD

**Issue by andreisbarnea** [godotengine/godot#84744]
### Godot version

v4.1.3.stable.mono.official [f06b6836a] / v4.2.beta5.mono.official [4c96e9676]

### System information

Godot v4.2.beta5.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Reason: I need to reach more then 50 000 simple meshes (lets say triangles) visible at the same time in a scene of roughly double number of similar such meshes. 
In the following sample test triangle meshes seems to disappear once the number of objects grows past ~16000.
The test sample generates a number of triangles distributed uniformly within a cube (10 units edge). Camera is static looking at the cube. There is only one direction light. 
The test variable _res_ determines the resolution (number of triangles to generate within the cubic space). _res_ = 20 means 20x20x20 triangles (8000 in total). Camera _near = 0.01_ and _far = 400_. All other settings are default editor settings. 
A mesh is created for each triangle (this is intentional).
The variable sameMaterial allows for creating a material for each mesh (_sameMaterial = false_) or reusing only one material for all meshes (_sameMaterial = true_).
I tested both 4.1.3 and 4.2.beta5 with almost identical results.
| _res_ | Number of triangles/meshes | _sameMaterial_ | Monitor reported objects | Observations | Image |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 20  | 8000  | No | 17245 | seems ok | ![20](https://github.com/godotengine/godot/assets/9488772/0e9bf109-8fd5-4d5a-9fa5-ae23d5317edc)
| 23  | 12167 | No | 25581 | seems ok | ![23](https://github.com/godotengine/godot/assets/9488772/0c5ab543-9ac2-4ca5-b1a1-595a93801290)
| 24 | 13824 | No | 15981 | missing meshes |![24](https://github.com/godotengine/godot/assets/9488772/1b9e1554-3782-4d47-9e93-d03645c6a428)
| 25 | 15625 | No | 19542 | missing meshes |![25](https://github.com/godotengine/godot/assets/9488772/9301197d-6954-4adc-8a57-3c714f6964f2)
| 26 | 17576 | No | 23444 | missing meshes | ![26](https://github.com/godotengine/godot/assets/9488772/25e58dd8-c6eb-41ce-a5cd-cc8822439c2b)
| 27 | 19683 | No | 27660 | missing meshes |![27](https://github.com/godotengine/godot/assets/9488772/4a9df0c7-b23b-412c-8891-c81249307198)
| 20 | 8000 | Yes | 9246 | seems ok | ![20same](https://github.com/godotengine/godot/assets/9488772/3229c3d9-052a-41a3-a026-d3658231cdcb)
| 23 | 12167 | Yes | 13413 | seems ok | ![23same](https://github.com/godotengine/godot/assets/9488772/fb613304-ff4d-4967-a874-a416661c9d2b)
| 24 | 13824 | Yes | 15070 | seems ok |![24same](https://github.com/godotengine/godot/assets/9488772/d7650650-dab4-4c4d-b859-23da49bb3a95)
| 25 | 15625 | Yes | 16870 | seems ok | ![25same](https://github.com/godotengine/godot/assets/9488772/f5e65e9b-2423-4fa4-b647-70dcb143b4b9)
| 26 | 17576 | Yes | 3045 | missing meshes |![26same](https://github.com/godotengine/godot/assets/9488772/5d04452c-9d90-413c-9294-fd5b5a3035a3)
| 27 | 19683 | Yes | 5152 | missing meshes | ![27same](https://github.com/godotengine/godot/assets/9488772/085c03ca-c745-48a6-bd2b-ced766dd64ed)

### Steps to reproduce

Download the sample project and set different values for the 2 variables described above.

### Minimal reproduction project

[Sample.zip](https://github.com/godotengine/godot/files/13324903/Sample.zip)

**Comment by AThousandShips** [comment]
Can you please confirm this occurs only with mono, otherwise please prepare a reproduction project that doesn't depend on mono to make it easier to test for the people who do not use mono (most of us)

(Haven't looked at the reproduction project as I'm not on my computer but assuming it uses it from the title)

**Comment by andreisbarnea** [comment]
> Can you please confirm this occurs only with mono, otherwise please prepare a reproduction project that doesn't depend on mono to make it easier to test for the people who do not use mono (most of us)
> 
> (Haven't looked at the reproduction project as I'm not on my computer but assuming it uses it from the title)

I didn't check any non-mono build as I don't intend to learn GDScript (sorry for most of you). The attached sample project is using C# and produces the result described. I also copied the whole code here for ease of porting to GDScript if anyone wants to test those builds:
```csharp
public override void _Ready() {
        var scenario = GetWorld3D().Scenario;
        Random rand = new Random();
        float space = 10;
        int res = 25; // change resolution here
        float d = space / res;
        bool sameMaterial = false;
        StandardMaterial3D mat = null;
        GD.Print("Triangle meshes: " + res * res * res);
        for (int x = 0; x < res; x++) {
            for (int y = 0; y < res; y++) {
                for (int z = 0; z < res; z++) {
                    var arrMesh = new ArrayMesh();
                    var arrays = new Godot.Collections.Array();
                    arrays.Resize((int) Mesh.ArrayType.Max);
                    Vector3[] vertices = new[] {
                        new Vector3(-space/2 + (x * d), -space/2 + 0.1f + (y * d), -(z * d)),
                        new Vector3(-space/2 + 0.1f + (x * d), -space/2 + 0 + (y * d), -(z * d)),
                        new Vector3(-space/2 + -0.1f + (x * d), -space/2 + 0 + (y * d), -(z * d))
                    };
                    arrays[(int) Mesh.ArrayType.Vertex] = vertices;
                    var faceNormal = Vector3.Back;
                    var normals = new Vector3[] { faceNormal, faceNormal, faceNormal };
                    arrays[(int) Mesh.ArrayType.Normal] = normals;
                    arrMesh.AddSurfaceFromArrays(Mesh.PrimitiveType.Triangles, arrays);
                    if (mat == null || !sameMaterial) {
                        mat = new StandardMaterial3D();
                        mat.AlbedoColor = Color.FromHsv((float) rand.NextDouble(), 1f, 1f);
                    }
                    arrMesh.SurfaceSetMaterial(0, mat);
                    var instance = RenderingServer.InstanceCreate2(arrMesh.GetRid(), scenario);
                }
            }
         }
}
```

**Comment by AThousandShips** [comment]
You are much more likely to get someone to test this with GDScript, as I won't be able to or able to port the code

**Comment by andreisbarnea** [comment]
> You are much more likely to get someone to test this with GDScript, as I won't be able to or able to port the code

This is my first attempt to translate to a compiling GDScript , but it doesn't produce anything on screen. Maybe I am missing something, here it is:

```GDScript
func _ready():
	var scenario = get_world_3d().scenario;
	var rand = RandomNumberGenerator.new()
	var space = 10.0
	var res = 25
	var d = space / res
	var sameMaterial = false
	var mat = null
	print("Triangle meshes: %s" % (res * res * res))
	for x in range(res):
		for y in range(res):
			for z in range(res):
				var arrMesh = ArrayMesh.new()
				var arrays = []
				arrays.resize(Mesh.ARRAY_MAX)
				var vertices = PackedVector3Array()
				vertices.append(Vector3(-space/2 + (x * d), -space/2 + 0.1 + (y * d), -(z * d)))
				vertices.append(Vector3(-space/2 + 0.1 + (x * d), -space/2 + 0 + (y * d), -(z * d)))
				vertices.append(Vector3(-space/2 + -0.1 + (x * d), -space/2 + 0 + (y * d), -(z * d)))
				arrays[Mesh.ARRAY_VERTEX] = vertices
				var normals = PackedVector3Array()
				normals.append(Vector3.BACK)
				normals.append(Vector3.BACK)
				normals.append(Vector3.BACK)
				arrays[Mesh.ARRAY_NORMAL] = normals
				arrMesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES,arrays)
				if(mat == null || !sameMaterial):
					mat = StandardMaterial3D.new()
					mat.albedo_color = Color.from_hsv(rand.randf(),1,1)
				arrMesh.surface_set_material(0, mat)
				var instance = RenderingServer.instance_create2(arrMesh.get_rid(), scenario)
```

**Comment by clayjohn** [comment]
Thanks for the attempt. Here is updated code that draws stuff to screen. The underlying problem is that GDScript uses reference counting which means it cleans up objects once they are no longer referenced. So you need to keep a reference to your newly created resources or else they are destroyed at the end of the loop iteration. 

```
extends Node3D

var instances = Array()
var meshes = Array()

func _ready():
	var scenario = get_world_3d().scenario;
	var rand = RandomNumberGenerator.new()
	var space = 10.0
	var res = 25.0
	var d = space / res
	var sameMaterial = false
	var mat = null
	print("Triangle meshes: %s" % (res * res * res))
	for x in range(0, res):
		for y in range(0, res):
			for z in range(0, res):
				var arrMesh = ArrayMesh.new()
				var arrays = []
				arrays.resize(Mesh.ARRAY_MAX)
				var vertices = PackedVector3Array()
				vertices.append(Vector3(-space/2.0 + (x * d), -space/2.0 + 0.1 + (y * d), -(z * d)))
				vertices.append(Vector3(-space/2.0+ 0.1 + (x * d), -space/2.0 + 0 + (y * d), -(z * d)))
				vertices.append(Vector3(-space/2.0 + -0.1 + (x * d), -space/2.0 + 0 + (y * d), -(z * d)))
				arrays[Mesh.ARRAY_VERTEX] = vertices
				var normals = PackedVector3Array()
				normals.append(Vector3.BACK)
				normals.append(Vector3.BACK)
				normals.append(Vector3.BACK)
				arrays[Mesh.ARRAY_NORMAL] = normals
				arrMesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES,arrays)
				if(mat == null || !sameMaterial):
					mat = StandardMaterial3D.new()
					mat.albedo_color = Color.from_hsv(rand.randf(),1,1)
					mat.cull_mode = BaseMaterial3D.CULL_DISABLED
				arrMesh.surface_set_material(0, mat)
				meshes.push_back(arrMesh)
				instances.push_back(RenderingServer.instance_create2(arrMesh.get_rid(), scenario))
```

**Comment by clayjohn** [comment]
Running the script as-is (res: 25, same_material: false) gives me this:

![image](https://github.com/godotengine/godot/assets/16521339/5f988e37-176e-4128-99ce-b7789880ab4f)

``Triangle meshes: 15625`` 
Monitor: Reported objects: 32441
Monitor: Total objects drawn: 15625

From what I can tell, these results are correct. 

Running with res=45:

![image](https://github.com/godotengine/godot/assets/16521339/eb367c21-f33b-411c-bff1-aba0c3b02d39)

Still seems fine to me:

``Triangle meshes: 91125``
Objects: 183445
Objects drawn: 91125

Given that the issue in GDScript came from the reference counter freeing the objects (since they were referenced nowhere). I'm wondering if the issue in C# is the garbage collector? The garbage collector should view these instances and meshes as garbage and clean them up. That might be what is going on here? The number of meshes probably increases to the point that it triggers the garbage collector which conservatively cleans up a bunch of the meshes. 

Can you try the scene again but maintaining references to the Meshes and Instances as I did in GDScript?

**Comment by andreisbarnea** [comment]
The problem was that i kept the Rid(s) not the meshes themselves. Keeping the meshes not just their Rids works! This issue can be closed, thank you.
