### ISSUE TITLE
Expose PoolArray Read and Write to GDNative

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8475]
GDNative has currently only one Godotian way to fill an array and send it to the engine, which is to use one of the existing PoolArrays (Vector2, Vector3, Int, Float...), resize it, and assign every index one by one just like GDScript.
Problem: doing this frequently with many elements is inefficient, which is why Read and Write structures exist in C++ so that multiples values can be read or modified in one efficient transaction (unless I misunderstand them?).
However these structures aren't available to GDNative.
Having them in the API would speed up data transfer for procedural generation of meshes, signal processing or other tasks requiring to read or write in one of those arrays (especially Mesh generation in my case).

**Comment by reduz** [comment]
kicking to 3.1

**Comment by karroffel** [comment]
No need to kick to 3.0, implemented in #12612
