### ISSUE TITLE
Control node built in signals not working when in @tool script and edited with Editor 2D gizmo

### ISSUE THREAD

**Issue by SirPigeonz** [godotengine/godot#84755]
### Godot version

4.1.3

### System information

Windows 10

### Issue description

If you try to connect Control Nodes signal for example resized() signal to a metod in @tool script. it will not trigger the connected method when Control is resized or will throw errors. No matter if its by code or Editor 2D gizmo.

Important! Works only if the Control Node Scene is instantiaded in another scene.

---

Sometimes when connecting by Editor it will send signal but connected method will be not found producing and ERROR message.

![image](https://github.com/godotengine/godot/assets/6152134/d92b6410-7423-4675-b73b-f8e02bec9b70)

Usually no ERROR is dispalyed the signal method just doesn't work silently.

### Steps to reproduce

Test1
Create Scene with Control node.
Attach @tool script.
Connect 'resize' signal to Control node script metod.
Try to resize the Control.
It will have issues.

Test2
Add the scene from Test1 to new scene.
Resize the instance in new scene.
It will work.

### Minimal reproduction project

Contains 2 scenes control.tscn where resize signal will not work and vbox.tscn where it will.

[control_node_signal_bug.zip](https://github.com/godotengine/godot/files/13325813/control_node_signal_bug.zip)

**Comment by AThousandShips** [comment]
You have written your connect wrong, it should be:
```gdscript
connect("resized", _on_resized)
```

Not a bug

**Comment by SirPigeonz** [comment]
> You have written your connect wrong, it should be:
> 
> ```gdscript
> connect("resized", _on_resized)
> ```
> 
> Not a bug, for support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels _first_ to see if this is a bug or user error.
> 
> We could look into adding a dedicated test, causing a dedicated error with more info, but I don't think it'd be realistic as `connect` isn't a special function, could detect for `Callable` arguments but it's somewhat complex to do so

Ups you are right xD. Ok I deleted that part but rest still holds. In test project I connected using editor.

**Comment by SirPigeonz** [comment]
ok... for some reason it works now... even the example project... I'm closing it for now I will re open if I will figure out how to reproduce it again...
