### ISSUE TITLE
Implement get_model_name on iOS

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8476]
Looks like get_model_name is only implemented on Android.

Will look into implementing it on iOS, not 100% sure but implementing this may do the trick:
https://developer.apple.com/reference/uikit/uidevice/1620044-model

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by BastiaanOlij** [comment]
Would still be nice to see implemented some day but not a hot issue :)

**Comment by starryalley** [comment]
I reckon that I will probably need this so I just sent a PR. This will return model name like: "iPad6,7" instead of just "iPad" or "iPhone"

https://github.com/godotengine/godot/pull/32326
