### ISSUE TITLE
Unable to connect Navigation Regions 2d by edge proximity

### ISSUE THREAD

**Issue by sandygk** [godotengine/godot#84773]
### Godot version

4.2 beta 3

### System information

Godot v4.2.beta3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3699) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

According to [the documention](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_connecting_navmesh.html) we should be able to connect navigation meshes when two outside edges are close but not overlapping.

But I've been trying to do use this feature, and it never seems to connect the meshes, which leads me to believe there may be a bug in the code. Here is what I get:

![image](https://github.com/godotengine/godot/assets/6596836/5b6a12fa-b199-44b1-860a-e5d9b2914601)

Is it something I am doing wrong, or is this a genuine bug? I've tried, getting them very close, overlapping, no overlapping, one point in and the other out, nothing seems to work.

### Steps to reproduce

Open and run the attached project 

### Minimal reproduction project

[nav-agent-bug.zip](https://github.com/godotengine/godot/files/13326565/nav-agent-bug.zip)

**Comment by smix8** [comment]
The default navigation map `edge_connection_margin` is 1 default navigation map cell unit, which is 1 pixel for 2D and 0.25 m for 3D.

You can increase the default margin in the ProjectSettings in `Navigation->2D->Default Edge Connection Margin`.

**Comment by sandygk** [comment]
Yup, that was it, thanks!

<img width="1280" alt="image" src="https://github.com/godotengine/godot/assets/6596836/8e81a334-696a-4697-9d45-7474bd67fa20">

isn't 1px a bit too small for the default?

**Comment by smix8** [comment]
It was reduced to 1 pixel because beginners messed up their navigation map rasterization so commonly when doing lowres pixel art games. It is easier to explain from time to time that a user can increase the edge connection margin in the settings then to explain nearly every beginner why their navigation map is all messed up.

**Comment by sandygk** [comment]
Sounds good. We can probably close this

**Comment by sandygk** [comment]
Should we add a note like this to the documentation:

>The default navigation map edge_connection_margin is 1 default navigation map cell unit, which is 1 pixel for 2D and 0.25 m for 3D.
