### ISSUE TITLE
Failing to link while trying to build Godot on darwin/arm64

### ISSUE THREAD

**Issue by Volatus** [godotengine/godot#84776]
### Godot version

master

### System information

macOS 14.1, M1 SOC, LLVM 17, MoltenVK 1.2.6

### Issue description

Trying to compile Godot on `darwin/arm64` with MoltenVK fails at the linking step due to unresolved symbols. 

Here's a [link to the pastebin](https://pastebin.com/Pp0B4w0P) for the compilation logs, as it's over 3000 lines.

### Steps to reproduce

Try building with the following:
* LLVM 17
* MoltenVK 1.2.6
* macOS 14.1 arm64

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by akien-mga** [comment]
Please include the exact command you use to build Godot, and the exact commit you're building.

**Comment by bruvzg** [comment]
> LLVM 17

Is it custom LLVM build or Xcode (which version?). Usually errors like these indicate you have object files built by newer compiler version with older linker, try cleaning up build tree and making a full build. Or it's possible that MoltenVK you are using is built with newer Xcode (either update Xcode or use custom MoletnVK build).

**Comment by akien-mga** [comment]
AFAIK there's no Xcode version released based on LLVM 17 yet, the current 15.0 and 15.1 beta are still on LLVM 16: https://en.wikipedia.org/wiki/Xcode#Toolchain_versions

So indeed this sounds like an unsupported configuration.

**Comment by Volatus** [comment]
> AFAIK there's no Xcode version released based on LLVM 17 yet, the current 15.0 and 15.1 beta are still on LLVM 16: https://en.wikipedia.org/wiki/Xcode#Toolchain_versions
> 
> So indeed this sounds like an unsupported configuration.

The build also fails with the included LLVM 15 from XCode.

**Comment by Volatus** [comment]
> Please include the exact command you use to build Godot, and the exact commit you're building.

`scons platform=macos arch=arm64`

**Comment by Volatus** [comment]
@bruvzg @akien-mga This issue seems to be a duplicate of #82372 and is resolved by getting rid of `binutils` from `brew`.
