### ISSUE TITLE
Poor performance on Linux, acceptable on Windows, same computer

### ISSUE THREAD

**Issue by berserk82** [godotengine/godot#8478]
**Operating system or device - Godot version:**
Debian Stretch - Windows 10
Godot 2.1 official

**Issue description:**

Trying some demos, I get a small FPS on Linux and an acceptable on Windows

**Steps to reproduce:**
Open the editor and load any demo from the demo repository

Note I have a AMD Radeon 5400 with almost 512 Mb vram

**Comment by nunodonato** [comment]
How many fps do you get in glxgears?

**Comment by bojidar-bg** [comment]
Looks like a duplicate of #4799, no?

**Comment by berserk82** [comment]
@nunodonato 60 average, but it's set to give the same fps as the refresh rate
@bojidar-bg Yes, you're right. My bad

**Comment by Calinou** [comment]
This is a very low-end card whose Linux drivers have historically been slower than the Windows ones. Not a lot can be done for your hardware, which isn't really supported anymore by AMD anyway, not to mention it probably can't run a GLES 3.0 renderer like the one that will be in Godot 3.0.
