### ISSUE TITLE
Long time to run project when in a Discord voice channel

### ISSUE THREAD

**Issue by BaconEggsRL** [godotengine/godot#84780]
### Godot version

4.1.1.stable

### System information

Windows 10

### Issue description

Not sure where to post this, if others have the same issue -- couldn't find anything on the web... Maybe this?
https://github.com/godotengine/godot/issues/20566

Any time I join a voice channel in Discord it increases my project run times significantly:

No discord voice: nearly instant
Discord voice: 9-10 seconds

Thanks

### Steps to reproduce

1. Run project without having any Discord voice channels open. Record time to start.
2. Join any discord voice channel.
3. Run project again. Record time to start.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
If you print messages in the project, do they appear in the Output panel while you're in a Discord voice channel? If not, this indicates a debugger connection failure.

**Comment by KoBeWi** [comment]
Might be audio-related. Joining a voice channel can switch audio device on Windows.

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by BaconEggsRL** [comment]
> they appear in the Output panel while you're in a Discord voice channel? Does debugger interaction such as breakpoints work? If not, th

Print statements and breakpoints still work

Will try on newer version

**Comment by Calinou** [comment]
> I also noticed that if I unplug my USB headset, the issue no longer occurs.

Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/20566.
