### ISSUE TITLE
Wrong size info in texture preview window

### ISSUE THREAD

**Issue by verypleasentusername** [godotengine/godot#84790]
### Godot version

4.1.3 stable (or 4.1 branch  [2d3b2ab])

### System information

windows 10, 4.1.3 stable engine version, Forward+

### Issue description

Read the titile. Wrong Size in Texture preview.

![image](https://github.com/godotengine/godot/assets/63970682/2b571ede-bf29-4642-b332-5cebb9342b83)
![image](https://github.com/godotengine/godot/assets/63970682/79e6ea90-b937-467f-bdf6-49b58f66931c)

In fact, issue isn't .svg exclusive.

![image](https://github.com/godotengine/godot/assets/63970682/e576650a-8f13-4966-a757-ccbad25d7c88)
![image](https://github.com/godotengine/godot/assets/63970682/aba5ba7c-a214-4b2d-9229-629bd2a477f3)
48 MiB = 50.33 MB

Issue will be closed if it appears that i missunderstand something here.

### Steps to reproduce

Move any texture file in project `Res ` folder. Look at `Memory:` line and compare with Memory file takes in your Explorer (Or its analogs).

### Minimal reproduction project

N/A

**Comment by Deozaan** [comment]
I believe you are misunderstanding something. File size and memory are not the same thing. Memory is RAM. File size is how much HDD/SSD storage space gets used.

Godot converts the image from the format stored on disk to a format that will be loaded into memory during runtime. The amount of memory used is directly proportional to the number of pixels contained in the image and the number of bytes used to represent each pixel.

32x32 pixels x 4 bytes per pixel is 4096 bytes, or 4 KiB.
2048x4096 pixels x 6 bytes per pixel is 48 MiB.

**Comment by clayjohn** [comment]
As Deozaan says, the memory use reported in the editor is the memory usage in RAM/VRAM not on disk. Further, for assets like SVGs, the space they take on disk is different than the original SVG because Godot renders the SVG into a PNG (and that is what you ship with your game). To get the accurate size on disk, you need to look in the .godot/imported folder.
