### ISSUE TITLE
snap process to fixed process

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#848]
"there should be an option to snap process to fixed process" - reduz (on IRC)

This is related to jittering caused by process and fixed_process being "out of sync"

**Comment by akien-mga** [comment]
What would be the point compared to just using _fixed_process without _process?

**Comment by reduz** [comment]
I'm not sure how much does this avoid the jitter, in my tests it ended up creating more jitter. A better solution for this is fixed step interpolation but It's really hacky

**Comment by akien-mga** [comment]
I guess this won't be implemented then.
