### ISSUE TITLE
Can't copy node path with Ctrl+Shift+C

### ISSUE THREAD

**Issue by rarysson** [godotengine/godot#84808]
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Windows 11

### Issue description

When I try to copy a node path using Ctrl+Shift+C the path is not copied, only if I press right-click on the node and select the `Copy Node Path` option.

### Steps to reproduce

Select a Node and press Ctrl+Shit+C.

### Minimal reproduction project

N/A.

**Comment by AThousandShips** [comment]
Unsure if the shortcut works unless you have the menu open

**Comment by KoBeWi** [comment]
Can't reproduce.

https://github.com/godotengine/godot/assets/2223172/6d12e70e-5f98-4098-a150-146c84b42bda

**Comment by jsjtxietian** [comment]
I also ran into this issue, but later I found it's because I tend to use ctrl + shift + v to paste when I use ctrl + shift + c to copy...

**Comment by rarysson** [comment]
I finally got time to build the source code in debug mode and tried to see what it could be, and I found out why it wasn't working.

I've checked every app that was open in the background after the combination of `Ctrl+Shift+C` never being trigged and found this:

![image](https://github.com/godotengine/godot/assets/22689195/718b2164-2ee6-4cff-8c19-de36aa151d61)

The driver app from AMD (Adrenalin) has these keys as a shortcut, and for some reason their app "consumes" the event, and to the system, these keys were never pressed.

So yeah, it's not a bug from Godot 😃.
