### ISSUE TITLE
Changing the remote debugging icon

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8480]
I recently came across this [QA thread](https://godotengine.org/qa/6769/how-to-show-some-debugging-information-when-we-run-the-game) which says to click the debug icon in the top icon panel. It took me at least 30s to find the icon they were talking about - it's the far right icon. I haven't seen this icon before, what's it supposed to be?

![selection_085](https://cloud.githubusercontent.com/assets/7429786/25280212/249ec424-2677-11e7-929c-50367454df44.png)

I think this could be communicated better to users. Would it be possible to change this to a little bug icon instead? I found some options [here](http://stackoverflow.com/questions/3081106/where-can-i-get-a-good-set-of-ide-icons), [here](http://game-icons.net/) and [here](http://www.flaticon.com/search?word=bug&license=all&color=0&stroke=0).

**Comment by bojidar-bg** [comment]
@djrm Ping.

You might want to open this issue on https://github.com/djrm/godot-design instead/as well.

**Comment by nunodonato** [comment]
I think it's a kind of "remote" thing. Because you know, you can debug remotely, and sync changes while playing etc

**Comment by djrm** [comment]
I will try to make a remote bug

**Comment by eon-s** [comment]
It may need a separator and/or an indication that is a menu, not a button like the others.

**Comment by ArcFutahito** [comment]
Iconography definitely should be upgraded though. Icon doesn't really convey the meaning of action at all. Maybe it should be more like this to signify that you need a mobile device and you deploy to it?
![spectacle on3209](https://cloud.githubusercontent.com/assets/10696955/25304833/ef993302-2777-11e7-80a8-ad8c4500a425.png)

**Comment by RodeoMcCabe** [comment]
Since it's a menu perhaps it ought to go in the menu bar on the left with a label "Debug" instead of the icon.

**Comment by nunodonato** [comment]
`Since it's a menu perhaps it ought to go in the menu bar on the left with a label "Debug" instead of the icon.`

I think @RodeoMcCabe's comment makes a lot of sense, would rather have this as a menu

**Comment by JarLowrey** [comment]
Arc, its not debugging just for phones or remote stuff. Its just general debugging

**Comment by ArcFutahito** [comment]
@JarLowrey Wait, really? Oh shit, I never even bothered to look through the menu I just assumed it's some remote deployment. 
Something definitely should be changed then since icon obviously doesn't represent what's actually inside.

**Comment by JarLowrey** [comment]
![capture](https://cloud.githubusercontent.com/assets/7429786/25313914/dc06d8aa-2806-11e7-982b-d4686fc179ef.PNG)

**Comment by djrm** [comment]
@JarLowrey Most of that stuff is not even debugging, (only the first one has something to do with debugging), visible collision shapes and visible navigation is just inspecting what is happening at runtime it has little to do with bugs but rather with scene design, so now the remote icon makes sense since the runing scene is a remote process and you are sending commands to it, i dont think changing the icon to a debug icon its going to make things easier to understand or if it is even correct at all.

**Comment by JarLowrey** [comment]
Well making things visible to the developer that you'd want to hide from an end user smells like debugging, and is what I would call it. The other things I'm not as sure about. What does everyone else think?

**Comment by eon-s** [comment]
For me, showing debug shapes (as in Box2D) and syncing changes, sounds like part of the debugging process.

**Comment by reduz** [comment]
I agree.. I never really found a way to convey this functionality in a
clear way.
To me, it's the "remote" menu, and is inside the area with buttons to play
the game.

I agree that we should probably be moving these to text menus or more icons?

I suggest before doing any PR, let's work on a proposal.. any ideas?

**Comment by ArcFutahito** [comment]
Well, if you need some icons I sure can help.

**Comment by djrm** [comment]
here is my proposal for debuging icon, maybe we can also add a sync button that provides the sync submenu.

![screenshot from 2017-04-26 17-33-27](https://cloud.githubusercontent.com/assets/1103897/25462946/6c5e7866-2aa7-11e7-89ce-92953d70df19.png)

![screenshot from 2017-04-09 21-46-00](https://cloud.githubusercontent.com/assets/1103897/25462955/752ebff0-2aa7-11e7-8f5e-ee99dcb5d8e1.png)

**Comment by JarLowrey** [comment]
Looks great!

**Comment by toger5** [comment]
what do ppl from this thread think about the solution in this pr: #8891

should solve that issue

**Comment by akien-mga** [comment]
Yeah, IMO this remote debugging/deploy menu does not need an icon, a normal text menu is just fine. So fixed already.

**Comment by JarLowrey** [comment]
I think it looks good. @djrm 's icon is pretty cool but if it's already fixed as a text menu that sounds good too.
