### ISSUE TITLE
set_shader_param do not ignore capitalization

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8482]
I recently [discovered](https://godotengine.org/qa/14234/automatically-loading-normal-from-paths-normal-appearing) that the inspector auto-capitalizes all property labels (thanks @eons), but my shader variable was simply "normal". This led to scripting issues when I tried to reference the variable by what I saw in the inspector - `get_material().set_shader_param("Normal", load(normal_map_png_path))`. I had to use the string "normal" instead. 

To fix this, inspector capitalization could match parameter capitalization, or variants could ignore capitalization and make all reference strings lowercase before searching. I doubt someone would be using "Normal" and "normal" params on the same object, they certainly shouldn't be.

**Comment by eon-s** [comment]
Is ok to not ignore, the languages (GDScript and shader language) are case sensitive, and the tooltip shows the real variable name.
But I think custom properties (uniforms and exported variables) should have an (editor) option to let them have their original names in the inspector to help programmers (designers may prefer pretty formatting).

This could be related to #4222 .

**Comment by JarLowrey** [comment]
Yeah same thing, it can be confusing

**Comment by KoBeWi** [comment]
> But I think custom properties (uniforms and exported variables) should have an (editor) option to let them have their original names in the inspector to help programmers (designers may prefer pretty formatting).

This option exists since 3.1, but doesn't work on Resources in the new inspector (so shader params are still capitalized even with capitalization disabled).

**Comment by Calinou** [comment]
The `set_shader_param()`
 method no longer exists in the `3.2` and `master` branches, closing.
