### ISSUE TITLE
Cannot compile for architecure aarch64 when png builtin is enable

### ISSUE THREAD

**Issue by vrince** [godotengine/godot#84827]
### Godot version

4.1.3-stable

### System information

Linux cross compiling for switch (aarch64)

### Issue description

When `builtin_libpng` is enabled only arm architecture stating with "arm" actually adds neon specific (intrinsic) c files.
So for the `aarch64` arm architecture, the c files are missing resulting in an undefined reference at link time.

Fix is easy, line 40 of png Scub should go from:

```sh
    if env["arch"].startswith("arm") 
```

to

```sh
    if env["arch"].startswith("arm") or env["arch"].startswith("aarch"):
```

### Steps to reproduce

Compile with arm = `aarch64`

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
> Linux cross compiling for switch (aarch64)

Is that a thirdparty homebrew platform, Linux OS installed on a Switch, or an actual console port? This might be an issue in the platform port and not in Godot's buildsystem.

> Compile with arm = `aarch64`

Do you mean `arch=aarch64`? Could you give the exact command you're using to compile?

**Comment by vrince** [comment]
Your are right in detect arch is set to aarch64 because swithcbrew post fix is aarch64 so I figured using arch aarch64 was a good idea. Seems it's not. Please advice on what godot assumptions are. Are you using arm64 instead ?
