### ISSUE TITLE
Baking lightmaps with procedural sky using mobile renderer gives black lightmaps after second or third bake

### ISSUE THREAD

**Issue by sevenfivel** [godotengine/godot#84823]
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Godot v4.2.beta5 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 570 Series (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

In projects using the mobile rendering backend, lightmapped GI, and an environment with procedural sky, the generated lightmaps go all black after the lightmaps have been baked several times. The number of times varies. Usually, the first bake after opening the project will produce normal looking lighting, but typically by the second or third time the lightmaps are baked the lightmaps go all black. The Output window also shows the following warning: "Can't use the compute version of the copy_cubemap_to_panorama shader with the mobile renderer." The problem with the lightmaps does not occur if the Environment Mode in the LightmapGI node is set to "Disabled" or "Custom Color". It also does not occur with the Forward+ renderer.
![MobileBakeScreenshot](https://github.com/godotengine/godot/assets/29828824/f13dab1e-a02d-4d58-955c-e7bdfe7ec805)

### Steps to reproduce

-In the included reproduction project, select the LightmapGI node in the scene hierarchy.
-Click the "Bake Lightmaps" button at the top of the viewport window to bake the lightmaps.
-If the lightmaps have not gone black, bake the lightmaps again and repeat until the lightmaps go black.
-The lightmaps (and the cube) will usually go black after two or three bakes.
-It may help to disable "View Gizmos" in the viewport menu so that the light probes don't obscure the cube.

### Minimal reproduction project

[mobile_lm_test.zip](https://github.com/godotengine/godot/files/13329980/mobile_lm_test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/55868.
