### ISSUE TITLE
Godot Engine crash with Vulkan driver with AMD GPU

### ISSUE THREAD

**Issue by Bigaston** [godotengine/godot#84835]
### Godot version

4.2.beta5

### System information

Godot v4.2.beta5 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600M (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Sometimes, Godot Engine crash, and I had this error in the console, and nothing in the logs

<img width="550" alt="image" src="https://github.com/godotengine/godot/assets/28607342/08a37471-f332-42e4-8370-bf0bf5945d38">

### Steps to reproduce

It crash on different project but only on my computer with an AMD GPU

### Minimal reproduction project

It crash with different project sadly, so even an empty project crash sometimes

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.
