### ISSUE TITLE
tileMap Ctr + V ( paste ) not fully working

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#84834]
### Godot version

godot 4.2

### System information

windows 10

### Issue description

- When selecting a tile area pressing ctrl+c / ctrl + v, the tile area doesnt flip / rotate
- the flip / rotate starts working when the user presses the paint Icon (D)
- This consumes one click one the canvas leaving a painted tile on the layer.
- The flip / rotate then starts working

Ctrl + V isnt necessary, the tile can go automatically to the paint icon (D), once the user presses Ctrl + C, this is how its working in other tileMap editors.

### Steps to reproduce

create a tileMap / select an area of tiles / ctrl + C, ctrl + V / select paint icon / flip, rotate

1. select tiles on the editor area
![tileCopy01](https://github.com/godotengine/godot/assets/77213594/0e6b9626-bad2-4009-89c1-2378d0e1e361)

2. flip / rotate doesnt work
![tileCopy02](https://github.com/godotengine/godot/assets/77213594/b8953859-f570-4b7a-9ccf-908b7c14b370)

3. press the paint icon leaves a painted tile were the mouse click was made
![tileCopy03](https://github.com/godotengine/godot/assets/77213594/98e85812-022c-42a8-a15d-62176bb239c2)

4. the flip / rotate starts working
![tileCopy04](https://github.com/godotengine/godot/assets/77213594/0e040639-5527-40cb-89ef-924251768ec3)

### Minimal reproduction project

na

**Comment by AThousandShips** [comment]
> godot 4.2

Please list the specific version, either if you are on a specific pre-release like beta5, or the commit hash if you're building yourself

**Comment by jonSP12** [comment]
4.2 beta 5 and beta 4

**Comment by akien-mga** [comment]
For the record, I closed this on behalf of the Code of Conduct team, as the OP was banned due to harassing contributors. They're restricted from further interacting so this issue cannot progress. If someone confirms that the issue is still reproducible, you can open a new issue.
