### ISSUE TITLE
Vulkan Mobile: LightmapGI dynamic object lighting results in black objects

### ISSUE THREAD

**Issue by SpockBauru** [godotengine/godot#84846]
### Godot version

v4.1.3.stable.official [f06b6836a] and v4.2.beta5.official [4c96e9676]

### System information

Godot v4.1.3.stable and Godot v4.2.beta5 - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.2849) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)

### Issue description

Hey guys, Seems like Lightmap**Probes** are not working on **Mobile** renderer. They work well on **Forward+** but **not in Mobile**. 

https://github.com/godotengine/godot/assets/67930504/b3c681fa-061c-4e2e-bd4d-8b5b22cc4264

I've already:
- Tested on both Godot 4.1.3 and 4.2 beta 5.
  - Light**maps** don't work on Godot 4.1.2 on Mobile Renderer, but works in 4.2 beta 5. Light Probes don't work with Mobile Renderer on both.
- Set up lightmap UVs.
- Marked static and dynamic objects and lights.
- Set up all kinds of World Environment settings, even tried to delete and disable it.
  - In this node, the Background mode `Sky` have issues on Mobile, so I set up to `Custom Color` (seems related to https://github.com/godotengine/godot/issues/55868#issue-1077887433)
- Baked LightmapGI on both Forward+ and Mobile:
- Tried many combinations on the LightmapGI node.
- Tried a brand new project, now even the Lightmaps stopped working on Godot 4.1.2 (Still working on 4.2 beta 5)...
- Yes, I restarted my PC.
- Deleted all Godot config files in `AppData\Local` and `AppData\Roaming`

### Steps to reproduce

Bake a scene with LightmapGI and an object that transition between different lighting conditions. The Probes will work on Forward+ but not on Mobile.

### Minimal reproduction project

[LightmapProbes_Test.zip](https://github.com/godotengine/godot/files/13335324/LightmapProbes_Test.zip)

Edit: MRP for Godot 4.3.dev6
[Lightmap_Test_4.3.dev6.zip](https://github.com/godotengine/godot/files/15354314/Lightmap_Test_4.3.dev6.zip)

**Comment by KarthikHebbarMN** [comment]
+1

**Comment by Lasuch69** [comment]
Godot v4.3.dev6 - Fedora Linux 39.20240423.0 (Silverblue) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 550 / 550 Series (RADV POLARIS12) () - AMD Ryzen 5 3400G with Radeon Vega Graphics (8 Threads)

![Screenshot from 2024-05-17 15-39-34](https://github.com/godotengine/godot/assets/71460040/7ae8eeb5-dccd-471f-9b8e-0d56c255f567)

**Comment by Swarkin** [comment]
Same issue as OP 
Godot v4.3.dev6 - Windows 10.0.19044 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

**Comment by Lasuch69** [comment]
Baking the lightmaps myself results in visual difference:

![Screenshot from 2024-05-17 17-45-13](https://github.com/godotengine/godot/assets/71460040/34549a6a-50c4-457f-a97b-62034249968a)

**Comment by SpockBauru** [comment]
Edited the first comment to include the MRP I sent to [Lasuch69](https://github.com/Lasuch69) on Discord.
