### ISSUE TITLE
OpenXR was requested but failed to start

### ISSUE THREAD

**Issue by TrevorBlythe** [godotengine/godot#84855]
### Godot version

3.5-latest

### System information

Ubuntu 22.04

### Issue description

Trying to run a XR scene in Godot leads to error:
### "OpenXR was requested but failed to start"
Ive tried on many many different versions ranging from 3.5 to latest.
Ive tried installing steamvr and setting it as my OpenXR runtime. (not sure what that even does)
Ive verified my quest 2 connects to side quest correctly.

Things to note:
My quest 2 isn't showing up in my file explorer but it does connect in side-quest.
steamvr keeps saying "please plug in headset" even though its already plugged in.
I don't know if these issues are related to the main issue.

What else do you need to do to make it work?

### Steps to reproduce

Download "Godot XR Tools Demo" and import it and press run project with your quest 2 plugged in.
https://github.com/GodotVR/godot-xr-tools/releases

### Minimal reproduction project

https://github.com/GodotVR/godot-xr-tools/releases

**Comment by peteristhegreat** [comment]
Related: https://github.com/GodotVR/godot-xr-tools/issues/265

I found that switching the runtime fixed it for me.   Here's my comment on that thread:

https://github.com/GodotVR/godot-xr-tools/issues/265#issuecomment-1810307891

**Comment by Reelix** [comment]
For people coming across this error in 4.0

1.) Put on your Quest  
2.) Launch SteamLink  
3.) When you're inside the house in SteamVR, THEN hit play on Godot.
