### ISSUE TITLE
Calling super() in _init() when the base class does not define an _init() runs without issue in 4.1.2.stable but causes a parse error in 4.1.3.stable

### ISSUE THREAD

**Issue by blujai831** [godotengine/godot#84850]
### Godot version

4.1.3.stable

### System information

Godot v4.1.3.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu Nov  9 03:01:44 UTC 2023 - X11 - Vulkan (Forward+) - integrated AMD Radeon Vega 10 Graphics (RADV RAVEN) () - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Calling `super()` in `_init()` when the base class does not define an `_init()` runs without issue in 4.1.2.stable but causes a parse error in 4.1.3.stable.

As I'm not an expert on Godot internals and don't know whether internal classes expose any function to GDScript as `_init()` (though a quick `ag` on my end suggests they do not), I can't say whether I expect this to work on 4.1.3.stable, or to not work on 4.1.2.stable, but either way, this seems to be a breaking change.

### Steps to reproduce

The following GDScript code compiles and runs without issue in 4.1.2.stable, but in 4.1.3.stable, it causes a parse error and will neither compile nor run:

```
class_name MyNode extends Node
func _init() -> void:
    super()
```

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/13336625/repro.zip)

**Comment by YuriSizov** [comment]
This seems to be expected, this check was added on purpose in https://github.com/godotengine/godot/pull/81808. cc @anvilfolk @adamscott

**Comment by AThousandShips** [comment]
You still got an error when exporting in 4.1.2, see:
* https://github.com/godotengine/godot/issues/81804

**Comment by blujai831** [comment]
In 4.1.2 the error does not occur for `_init` specifically.

**Comment by AThousandShips** [comment]
So it won't have any problems when running the code?

**Comment by blujai831** [comment]
That's right. Pretty bizarre.

**Comment by AThousandShips** [comment]
Well then it is an exception to an otherwise valid rule, worth to keep safe with the other cases, so change is intentional and necessary

**Comment by anvilfolk** [comment]
Yes, I'm in agreement that this was an intentional change! 😊 

The idea is that if the GDScript user wrote a `super()` call expecting it to do something, but we can guarantee it will be a no-op since there is no base class method to call, then we should warn the user that there's some mismatch between what they intended to do and what is actually going to happen! 

Hope that makes sense! If it does, I'd recommend closing the issue :)
