### ISSUE TITLE
Tween.interpolate_value return error value when type was Vector2 ?

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#84869]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 10, 64bit

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/6bef9562-c544-4bcc-b0d5-e0362ef20a56)

### Steps to reproduce

/

### Minimal reproduction project

/

**Comment by timothyqiu** [comment]
The second parameter of `interpolate_value()` is delta, not the destination.

The example is interpolating between `(100,100)` and `(300,200)`.

**Comment by CsloudX** [comment]
Oh, Sorry!
