### ISSUE TITLE
sample library can not delete sample 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8486]
**Operating system or device - Godot version:**
Mac OS  godot versio 2.1.3

**Issue description:**

**Steps to reproduce:**
add a SamplePlayer2D node, create a SampleLibrary,edit the SampleLibrary
add sample file to the library
the file can not delete

**Link to minimal example project:**

**Comment by eon-s** [comment]
This may be already fixed on 2.1 by https://github.com/godotengine/godot/pull/8429
