### ISSUE TITLE
Godot 4.2 Beta 6 Hangs on Close

### ISSUE THREAD

**Issue by Bound2bCoding** [godotengine/godot#84865]
### Godot version

4.2 Beta 6 Mono 64

### System information

Windows 11 Godot 4.2 Beta 6 Visual Studio Community 2022 64-bit 17.7.4, Forward+

### Issue description

Just upgraded to Beta 6.  When I attempt to close my project, Godot hangs.  This has not happened previously.

### Steps to reproduce

Open a project in the beta 6 and try to close.  No response until Windows reports Not Responding.

### Minimal reproduction project

See above.

**Comment by akien-mga** [comment]
Thanks for the report. Consolidating in the existing https://github.com/godotengine/godot/issues/84728
