### ISSUE TITLE
Vulkan randomly crashing with VK_ERROR_DEVICE_LOST error in editor on low end hardware

### ISSUE THREAD

**Issue by ofoxsmith** [godotengine/godot#84864]
### Godot version

v4.1.2.stable.mono.official [399c9dc39]

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22622 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When rotating or moving the in-editor camera, Godot will randomly freeze before crashing with the message `ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST at: (drivers/vulkan/vulkan_context.cpp:2360)`.

The graphics settings ```
anti_aliasing/quality/msaa_3d=2
anti_aliasing/quality/screen_space_aa=1``` caused Vulkan to crash instantly on startup, but after disabling them the engine crashes randomly in the editor.

When I run the same project on my PC with a Nvidia 4070TI, there is no crashing and Vulkan runs fine.

### Steps to reproduce

1. Run forward-plus vulkan on a system with a low end GPU (I have been using Intel Integrated Iris Plus Graphics).
2. Either enable 3D MSAA or just rotate and pan the camera.
3. Godot should freeze and crash.

### Minimal reproduction project

N/A, Godot crashes even when opening a freshly made forward+ project.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.
