### ISSUE TITLE
Crash when attempting to pick a screen color using ColorPicker

### ISSUE THREAD

**Issue by afarber** [godotengine/godot#84861]
### Godot version

4.1.3

### System information

Mac

### Issue description

Clicking color-picker reproducibly crashes Godot 4.1.3 installed by Homebrew.

Screenshots:

<img width="1383" alt="Godot-version-homebrew" src="https://github.com/godotengine/godot/assets/1884458/fdc2db5c-cac5-4e0e-a8b6-51c40e6c61b4">
<img width="1383" alt="Color-picker-crash" src="https://github.com/godotengine/godot/assets/1884458/aa20fb32-2cf9-4d2e-998e-b65b70bdfc9c">

Bug dump:

[godot-color-picker-bug.txt](https://github.com/godotengine/godot/files/13342544/godot-color-picker-bug.txt)

### Steps to reproduce

To reproduce please check out my project:

https://github.com/afarber/SeaDefenderCourse/commit/47e47f8c3a08da939102ea30d9a21338e554b4a6

And then click the color-picker on the blue background as shown in the above screenshot

### Minimal reproduction project

Yes, the project is:

https://github.com/afarber/SeaDefenderCourse/commit/47e47f8c3a08da939102ea30d9a21338e554b4a6

**Comment by afarber** [comment]
Here a screen recording of the crash:


https://github.com/godotengine/godot/assets/1884458/cc2dedee-be7c-4732-9008-309af6d3236d

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83737.
