### ISSUE TITLE
4.2 beta resizing creates black bars around viewport, viewport doesn't change size

### ISSUE THREAD

**Issue by pinkkis** [godotengine/godot#84896]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Windows 11, Mac OS 14.0 - Forward+

### Issue description

In 4.2 Beta 6 (project was started in beta 4), the window resizing doesn't seem to work properly. I have mode set to "viewport", aspect set to "keep", and when I resize the window, the game viewport stays the same size, and only black bars are added around the game.

![image](https://github.com/godotengine/godot/assets/2265961/6750bc54-39f7-4675-b22a-e35506f2b633)

I opened the same exact project in 4.1.3 and the resizing works perfectly as expected.

Another note, when i maximize the window, the viewport _is_ resized, but there is still a little bit of black bars, as in there would be room to make it bigger.

This happens both on my Win 11 machine and my M2 Pro mac with Mac OS Sonoma (14.0)

## 4.1.3:

https://github.com/godotengine/godot/assets/2265961/f5ce164f-c974-41d6-953c-a6e8dff2e066

## 4.2-beta.6:

https://github.com/godotengine/godot/assets/2265961/a64a4c5d-cd96-4c26-821d-ba6a4abc2549

### Steps to reproduce

Attached is the project i'm using

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/13351331/repro.zip)

**Comment by Sauermann** [comment]
This was an intentional change done in #75784.

You can switch back to the previous behavior by changing Scale Mode from "integer" to "fractional" in Project Settings -> Display -> Window -> Stretch.

![image](https://github.com/godotengine/godot/assets/6299227/f501bcc9-02a4-4ecc-89aa-43fa7a53da54)

**Comment by pinkkis** [comment]
That seems to be it. Sorry, this seems to have been my misunderstanding what that meant. Thanks for the reply :)
Closing this as it doesn't seem a bug now
