### ISSUE TITLE
"Target Surface:" and "Source Mesh:" should only accept nodes that inherit Node3D

### ISSUE THREAD

**Issue by Stronkkey** [godotengine/godot#84893]
### Godot version

4.1.3 stable.arch_linux

### System information

Artix Linux Godot v4.1.3 stable.arch_linux

### Issue description

![2023-11-14T16:29:28,788232528+01:00](https://github.com/godotengine/godot/assets/92468390/a79027e2-1539-4ca9-9369-978c32dea26d)
Both "Target Surface:" and "Source Mesh:" accept non Node3D nodes which doesn't really make any sense as they need 3D geometry to function.

### Steps to reproduce

1. Add a MultiMeshInstance3D
2. Add a Node that doesn't inherit Node3D
3. Open the "Populate Surface" menu and click the right button of either "Target Surface:" or "Source Mesh:"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/84889.
