### ISSUE TITLE
Add support for the Meta XR Simulator

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#84904]
The Meta XR Simulator enables developers to simulate development on Meta devices. We should add support within the editor to improve the workflow of Godot XR developers

https://developer.oculus.com/documentation/native/xrsim-intro/

**Comment by BastiaanOlij** [comment]
@m4gr3d did you put this in the wrong repo? I was planning to build a plugin for this, just haven't gotten around to it yet

**Comment by m4gr3d** [comment]
@BastiaanOlij yeah, I accidentally created this issue when I was adding the entry to the XR roadmap project.

**Comment by jamie-pate** [comment]
Is this on some roadmap somewhere? :D it would be handy to run XR with no XR device for tests etc

**Comment by m4gr3d** [comment]
@jamie-pate It's already supported; see https://www.youtube.com/watch?v=znT4R-qSawg

**Comment by dsnopek** [comment]
On Linux, you can use Monado as an XR simulator, but it's harder to use than Meta's XR simulator (and I don't think it supports synthetic environments for MR, but I'm not sure)
