### ISSUE TITLE
Starting game in a minimized window causes Vulkan errors

### ISSUE THREAD

**Issue by synalice** [godotengine/godot#84905]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Godot v4.2.beta6 - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.21029.1006) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Happens even in `v4.1.3.stable.official [f06b6836a]`.

Starting a game with `display/window/size/mode` Project Setting set to `Minimized` causes the following errors to appear:

```
E 0:00:00:0540   draw_list_bind_render_pipeline: Parameter "dl" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7255 @ draw_list_bind_render_pipeline()

E 0:00:00:0540   draw_list_bind_index_array: Parameter "dl" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7402 @ draw_list_bind_index_array()

E 0:00:00:0540   draw_list_bind_uniform_set: Parameter "dl" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7329 @ draw_list_bind_uniform_set()

E 0:00:00:0540   draw_list_set_push_constant: Parameter "dl" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7436 @ draw_list_set_push_constant()

E 0:00:00:0544   draw_list_draw: Parameter "dl" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7454 @ draw_list_draw()

E 0:00:00:0544   draw_list_end: Immediate draw list is already inactive.
  <C++ Error>    Parameter "draw_list" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7759 @ draw_list_end()
```

This error don't appear only in `Compatibility` renderer _(most likely because it uses OpenGL instead of Vulkan)_.

**Forward+:**
`Vulkan API 1.3.250 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon(TM) Vega 8 Graphics`.
**Mobile:**
`Vulkan API 1.3.250 - Forward Mobile - Using Vulkan Device #0: AMD - AMD Radeon(TM) Vega 8 Graphics`.
**Compatibility:**
`OpenGL API 3.3.0 Core Profile Context 23.8.1.230810 - Compatibility - Using Device: ATI Technologies Inc. - AMD Radeon(TM) Vega 8 Graphics`.

### Steps to reproduce

1. Create new project.
2. Set `display/window/size/mode` Project Setting set to `Minimized`.
3. Run the project or any scene.

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
Looks like during `set_boot_image`,   minimized window does not have a swapchain (`swapchain_image_resources` is null), so the draw failed.
