### ISSUE TITLE
Reparenting nodes is extremely slow in certain situations

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#84910]
### Godot version

4.2 beta6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/8f2c5b00-f440-4403-9a62-07316a63cc10

The culprit is one of the recursive check PRs. I profiled the editor and in the case above most of the time is spent in `get_property_list()` method of TileAtlasSource, called by `_check_node_path_recursive()` in SceneTreeDock. Apparently this tile method is very slow and here it's called tens of times.

Not sure what the fix would be, maybe the editor should skip external resources (is it safe to assume they don't point to anything on the scene?). Or we could have a list of exceptions that are known to be slow and don't have NodePaths.

### Steps to reproduce

1. Open the MRP
2. Move Node2D under TileMap

### Minimal reproduction project

[LagSet.zip](https://github.com/godotengine/godot/files/13355862/LagSet.zip)

**Comment by atirut-w** [comment]
Reverting #80721 (might be "one of the recursive check PRs") using RC2 used as base commit fixes this problem and, for some reason, does *not* seem to reintroduce the bugs fixed in the PR. I have no earthly idea how this works, and it definitely have to be tested by some other people.

**Comment by atirut-w** [comment]
Would it be alright for 4.2 to depend on this issue getting fixed? I can imagine this being a huge productivity issue for any decently-sized project.

**Comment by KoBeWi** [comment]
> does not seem to reintroduce the bugs fixed in the PR

Reverting it *does* reintroduce #74155 and similar issues.
I think limiting it to built-in resources only is an acceptable compromise.
