### ISSUE TITLE
Adding Python-like max(), min(), all(), any() in GDScript

### ISSUE THREAD

**Issue by Chtobi** [godotengine/godot#8491]
**Issue description:**
It would be really nice to manipulate with GDScript arrays using max(), min()(instead of current min/max that takes only two floats), all() and any().
I know, that these functions are O(n) complexity, but still...

**Comment by Zylann** [comment]
Note: it boils down to adding some kind of function overloading, which is related to other issues as well. 
I wrote an issue about a similar idea but on different types h https://github.com/godotengine/godot/issues/8071

**Comment by suzumiyasmith** [comment]
Same feature requests for:
1. `join`
  ``` join([1,2,3], [4,5,6]) == join ([1,2,3,4,5,6])```
2. `is_sub_array`
  ``` is_sub_array([1,2,3], [1,2,3,5]) == true```
  ``` is_sub_array([1,2,3,4], [1,2,3,5]) == false```

**Comment by nhydock** [comment]
@suzumiyasmith I feel join would be better handled through the `+` operator like python.  Meanwhille, the `is_sub_array` function does not feel easily predictable.  It's hard to tell if that method is checking for the existence of all elements within the array to be in the other array and if ordering/sequence matters.

**Comment by vnen** [comment]
>  I feel join would be better handled through the `+` operator like python

`[1,2,3] + [4,5,6]` works already.

**Comment by suzumiyasmith** [comment]
@nhydock 
I find maybe new `match` feature works well for most cases using `is_sub_array`.
(But I am still using 2.1.3 stable version. Is there any release plan for 3.0 version?)

**Comment by RichardEllicott** [comment]
i use lists as a workaround:

    func _max(list):
    var ret
    for val in list:
        if not ret:
            ret = val
        else:
            if val > ret:
                ret = val
    return ret

func _min(list):
    var ret
    for val in list:
        if not ret:
            ret = val
        else:
            if val < ret:
                ret = val
    return ret

**Comment by RichardEllicott** [comment]
func _max(list):
	    var ret
	    for val in list:
	        if not ret:
	            ret = val
	        else:
	            if val > ret:
	                ret = val
	    return ret

	func _min(list):
	    var ret
	    for val in list:
	        if not ret:
	            ret = val
	        else:
	            if val < ret:
	                ret = val
	    return ret

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2926, as feature proposals are now tracked on the Godot proposals repository.
