### ISSUE TITLE
Blender file path on mac not accepted - when setting up blender import

### ISSUE THREAD

**Issue by Sjatplat** [godotengine/godot#84920]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Godot v4.2.beta6 - macOS 14.0.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Godot does not accept the Blender file path on mac under editor settings/File system/import/Blender 3 path
My blender app is installed under apps.
I have tried this with both blender 4 and blender 3.6

### Steps to reproduce

inital setup for the new blender import / workflow.

### Minimal reproduction project

N/A

**Comment by Much0L0c0** [comment]
I'm having the same problem but on Arch Linux.

**Comment by timothyqiu** [comment]
Note that `filesystem/import/blender/blender3_path` should be the path to the **directory** containing the `blender` executable.

For example, I'm on Arch Linux and my blender is located at `/usr/bin/blender`. Then this setting should be `/usr/bin`.

**Comment by AThousandShips** [comment]
This part is documented (and shows up on the tooltip)
> The path to the directory containing the Blender executable

**Comment by Calinou** [comment]
The macOS Blender detection logic is here: https://github.com/Calinou/godot/blob/dc3194f66880d2424692db5c40ac724346a201b1/modules/gltf/editor/editor_scene_importer_blend.cpp#L471-L508

**Comment by Sjatplat** [comment]
Hi. Tanks for the answer. I got it working. What I did wrong was using the file dialog in editor settings to find the blender.app. That resulted in this path:
/Users/myusername/Library/Application Support/Steam/steamapps/common/Blender

Rather I typed in the path in the settings manually with this path:
/Applications/Blender.app/Contents/MacOS

And now it works.

**Comment by Sjatplat** [comment]
Hi. Tanks for the answer. I got it working. What I did wrong was using the file dialog in editor settings to find the blender.app. 

Rather I typed in the path in the settings manually with this path:
/Applications/Blender.app/Contents/MacOS

And now it works.

**Comment by Much0L0c0** [comment]
> Note that `filesystem/import/blender/blender3_path` should be the path to the **directory** containing the `blender` executable.
> 
> For example, I'm on Arch Linux and my blender is located at `/usr/bin/blender`. Then this setting should be `/usr/bin`.

Well its working now, but like a month ago, more or less, I looked up this issue, saw other people give the same correction as you (point to the folder not the file) and it just still wouldn't find blender anywhere.

I used the `whereis blender` to find the locations and none of them worked on Godot.

Now it magically does, I didn't do anything... 
Thanks anyway.

**Comment by Catalin9090** [comment]
If you installed blender from steam : /Users/USERNAME/Library/Application Support/Steam/steamapps/common/Blende
