### ISSUE TITLE
GDNative: ability to handle "editor" and "export" versions of a library

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8492]
Currently GDNative allows only one version of a library for each platform, however it would be good for it to also support a version that will be used in editor with debug checks and messages (eventually editor tools), and have an optimized version of the library being used when it gets exported.

The first idea I have in mind is basically doubling the amount of paths to setup (per platform per mode), having one of them optional if the library doesn't need to. Another idea would be to use a naming convention.

**Comment by karroffel** [comment]
You can use custom feature tags, then #12586 will implement this
