### ISSUE TITLE
NavigationAgent's avoidance sometimes doesn't work

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#84938]
### Godot version

4.2 beta 6 + 4.1.3

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

Sometimes the navigation avoidance just doesn't work, watch the video for clarity (it might be tied to world axis or some whole numbers or something)

Link: https://youtu.be/1nCj8dZvNeA

In the video you can see the agents are trying to push each other rather than avoid. At the end I move the agents elsewhere to show that the avoidance works there, in the test file I set up 4 agents none of them really avoids each other.

### Steps to reproduce

Put two agents walking against each other, use avoidance in 3D, make sure the agents are not moved on any other axis then X-axis, navigation targets should also lie on the X-axis.

### Minimal reproduction project

[NavigationAvoidanceTest.zip](https://github.com/godotengine/godot/files/13367925/NavigationAvoidanceTest.zip)

**Comment by smix8** [comment]
That is a natural limitation of RVO / ORCA planes. 

When agents are started in perfect symmetrical situations and immediately go for exact collision course they have no defined passing sides.

If you change one of the two agents position only so slightly that they are not symmetrical  they gain their passing sides assigned and it works normally.
