### ISSUE TITLE
Cant close in Linux

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#84935]
### Godot version

4.2.-6

### System information

Godot v4.2.beta6.mono - Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

After open the engine, close the program, keeps open until force to close with a task manager. The thing, in the previous versions 4.2-1 to 4.2-4, works fine.

### Steps to reproduce

Open a project, then close the program.

### Minimal reproduction project

Just open a new project.

**Comment by YuriSizov** [comment]
Thanks for your report! This is a known issue with the mono builds and it will be fixed in the next official build (it's already fixed in `master`). See https://github.com/godotengine/godot/issues/84728.
