### ISSUE TITLE
Button.pressed is emitted twice every time a Button is pressed.

### ISSUE THREAD

**Issue by fish-food89** [godotengine/godot#84950]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Ubuntu 22.04.3 LTS 22.04 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 Threads)

### Issue description

When using the Button.pressed signal the signal is observed to be emitted twice for each "pressed" action. I tried finding an existing issue regarding this specific behaviour, but I couldn't find one with my brief searches. Pardon for possibly creating a duplicate issue.

I debugged the behaviour with the below simple GDScript.

```
extends Button

var _pressed_count: int = 0

func _ready() -> void:
    self.pressed.connect(_pressed)


func _pressed() -> void:
    _pressed_count += 1
    print('_pressed_count: ', _pressed_count)
```

When running that and pressing the Button object in question I get the following prints. Comments are for clarity of when each print was spat out to the Output dialog in the engine.

```
# First press.
_pressed_count: 1
_pressed_count: 2
# Second press.
_pressed_count: 3
_pressed_count: 4
# Third press.
_pressed_count: 5
_pressed_count: 6
# And so on and so forth.
```

### Steps to reproduce

Create a Button object and attach the the debug script given above in the description. At least I had an easy time to reproduce the behaviour with that.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by fish-food89** [comment]
[foo.zip](https://github.com/godotengine/godot/files/13370127/foo.zip)

Here's the minimal project to reproduce the issue with. Just tested it with 4.1.3.stable and the issue persists there as well.

**Comment by Mickeon** [comment]
This is a coincidence. Every Button has a [_pressed](https://docs.godotengine.org/en/stable/classes/class_basebutton.html#class-basebutton-method-pressed) virtual method you can override. You have happened to call the method the same.

So what happens is `_pressed` is called once by the Button itself, and another time by the connection as a callback.

**Comment by fish-food89** [comment]
Wow. That is such a coincidence. I did not even think of there being a privately typed method you can override for this case even though I am using `_ready`, which is one such method. Tested it out by renaming and indeed it solved the issue I was experiencing. Today I learned. I did not think of this angle to the experience.

Note to self: do a full search from documentation for any private methods you intend to use that you may accidentally override :rofl:
