### ISSUE TITLE
 transparent windows is work in windows but fail in android

### ISSUE THREAD

**Issue by ffoieoi** [godotengine/godot#84958]
### Godot version

4.0 dev

### System information

source code 4.0 version on github 

### Issue description

set Per Pixel Transparency ->Allowed is enable. 
and add fellow code in script 
'''
extends Node
func _ready():
	DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_TRANSPARENT,true) 
'''
it's ok windows
![image](https://github.com/godotengine/godot/assets/19278446/1644511a-ee44-42cc-b735-ee3b7b6d0bfe)
fail in android mobile
![img_v3_0258_146dea48-002f-4345-b6f3-2c95df21dbfg](https://github.com/godotengine/godot/assets/19278446/93b9e904-f390-404d-920f-902acd6fbef1)

### Steps to reproduce

....

### Minimal reproduction project

.....

**Comment by Qainguin** [comment]
I do not think that android support for transparent windows is implemented. Here is the quote from the docs. Thank you.

"Note: Transparency support is implemented on Linux (X11), macOS and Windows, but availability might vary depending on GPU driver, display manager, and compositor capabilities."

**Comment by ffoieoi** [comment]
Know the reason why android is not supported？

**Comment by ffoieoi** [comment]
> I do not think that android support for transparent windows is implemented. Here is the quote from the docs. Thank you.
> 
> "Note: Transparency support is implemented on Linux (X11), macOS and Windows, but availability might vary depending on GPU driver, display manager, and compositor capabilities."

Do you have a link to the article? I did not find it

**Comment by Sauermann** [comment]
Have you tried to use the search function of the online docs?
You can find it mentioned in different places:
- https://docs.godotengine.org/en/latest/classes/class_window.html#class-window-property-transparent
- https://docs.godotengine.org/en/4.0/classes/class_displayserver.html#enumerations

**Comment by ffoieoi** [comment]
Thank you. Yes, I have searched for it. I just found out that you need to add a colon when searching for godot. Otherwise, the search will not be correct.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/36860.
