### ISSUE TITLE
Godot compiled with `target=template_debug` throws error and closes upon running it.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#84962]
### Godot version

v4.2.beta.custom_build [575a5c858]

### System information

Windows 10

### Issue description

I synced my fork to the master branch, for all intents and purposes I am using the master branch considering my changes shouldn't affect the executable simply opening (I'll test it with the unedited master branch later but I doubt that will change anything).

I wanted to debug why the editor was crashing without error upon loading my project so I compiled godot with `target=template_debug` to test it, but when I try running it, it throws this error before closing:
```
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
```

I'm unsure as to the meaning of this error.
The engine runs without issue (besides when loading my project) when compiled without `target=template_debug`.

### Steps to reproduce

Compile godot master branch using: `scons platform=windows target=template_debug arch=x86_64`
and attempt to run it.

### Minimal reproduction project

"N/A"

**Comment by akien-mga** [comment]
`template_debug` gives you an export templates, not the editor. It can't be run standalone, it needs an exporter .pck file or project.godot source folder.

**Comment by KnightNine** [comment]
@akien-mga oh. I see. I thought `template_debug` gave me a version of the editor with more debugging info.

thanks for clarifying.

**Comment by akien-mga** [comment]
No that would be `target=editor` (same as not specifying it) and `dev_build=yes` (disables optimization, enables debug symbols, adds dev-only asserts).
