### ISSUE TITLE
Properties added to _get_property_list with usage PROPERTY_USAGE_NO_EDITOR are shown in editor.

### ISSUE THREAD

**Issue by ibe-denaux** [godotengine/godot#84971]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3197) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

![hidden_property_MPR](https://github.com/godotengine/godot/assets/70886156/e2a38a62-80cd-4452-abf7-c4dba760856d)

As shown in the MPR, properties that are marked to not be shown in the editor are still shown. Even after an editor restart the issue remains.

### Steps to reproduce

1. Declare a property.
2. Add the property to the property list with _get_property_list() and describe the usage as PROPERTY_USAGE_NO_EDITOR.
3. The property is serialized to the packed scene as expected, but also shown in the editor.

### Minimal reproduction project

[Hidden Editor Property MPR.zip](https://github.com/godotengine/godot/files/13377392/Hidden.Editor.Property.MPR.zip)

**Comment by AThousandShips** [comment]
You have a typo, it's "usage" not "useage"

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by ibe-denaux** [comment]
Thank you, I mistakenly assumed that properties added to the property list would be hidden from the editor and not serialized by default, so I thought I was properly overriding the 'usage' field.

**Comment by AThousandShips** [comment]
They use `PROPERTY_USAGE_DEFAULT` by default 🙂

**Comment by ibe-denaux** [comment]
That makes sense :sweat_smile:.
