### ISSUE TITLE
Inspector doesn't refresh after editing C# script

### ISSUE THREAD

**Issue by TomasZilinek** [godotengine/godot#84984]
### Godot version

4.1.2 - mono

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (NVIDIA; 30.0.15.1179) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

I edit a C# script (add/remove an export property) and save it. I come back to Godot but in the inspector I can still see the old version. The new exported property is not there. I tried to click on other nodes and click back but that doesn't help. Closing and opening the whole scene doesn't help either. I must either close and open Godot game editor or detach and re-attach the script or start the game from the engine. That's super annoying.

### Steps to reproduce

Explained in the Issue description

### Minimal reproduction project

.

**Comment by snoozedDev** [comment]
You need to build the project for exported value changes to show up on the inspector.

![CleanShot 2023-11-16 at 22 36 50](https://github.com/godotengine/godot/assets/40501327/b678b08e-c222-47aa-94bf-2efb63ce6796)

Does building your project result in what you expected to happen automatically?

**Comment by TomasZilinek** [comment]
> You need to build the project for exported value changes to show up on the inspector.
> 
> ![CleanShot 2023-11-16 at 22 36 50](https://user-images.githubusercontent.com/40501327/283642701-b678b08e-c222-47aa-94bf-2efb63ce6796.png)
> 
> Does building your project result in what you expected to happen automatically?

I didn't know about the build button. :) Thanks. But I think it should work automatically like in Unity. You save something and when the Godot editor program window gets focus it will automatically build the project. But yes my problem is solved, thanks.

**Comment by raulsntos** [comment]
- Closing as the problem was resolved.
- For the proposal about rebuilding the project on script changes see https://github.com/godotengine/godot-proposals/issues/2920.
