### ISSUE TITLE
4.2.0-beta.6 hanging indefinitely with  `--build-solutions` and `--quit`

### ISSUE THREAD

**Issue by definitelyokay** [godotengine/godot#84982]
### Godot version

4.2.0-beta.6

### System information

Ubuntu GitHub Runner

### Issue description

The critical CI/CD command used in all of my projects (which has worked up until now) to `--build-solutions` is hanging / stalling indefinitely now in 4.2.0-beta.6:

```sh
godot --headless --build-solutions --quit
```

This timed out after 360 minutes:
https://github.com/chickensoft-games/GodotGame/actions/runs/6867896338/job/18677210352

This happens every time, all the time. I can easily reproduce this locally on macOS with the same Godot version / environment (.NET 8)

### Steps to reproduce

Try to run `godot --headless --build-solutions --quit` in a C# project.

### Minimal reproduction project

Happens in any C# project. Here's one created through the editor.

[PlainCSharpProject.zip](https://github.com/godotengine/godot/files/13380770/PlainCSharpProject.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84728, as this is due to the same cause.
