### ISSUE TITLE
`Go to previous edited document` and `Go to next edited document` shortcuts are not customizable

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#84991]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

MacOS 14.1.1 (23B81)

### Issue description

Currently, this action can only be done using a mouse, indicating either a lack of shortcuts or that my system's shortcuts are overriding them. 
It's surprising this issue has been ongoing for so long. While many actions are customizable, this essential shortcut, commonly used in other editors, remains unconfigurable.

### Steps to reproduce

To reproduce the issue, attempt to configure shortcuts for actions: 
![image](https://github.com/godotengine/godot/assets/11059246/5b78e663-0cc2-4924-a9ef-dca7aab29feb)

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
What about these two?

![image](https://github.com/godotengine/godot/assets/8315986/8f0dc41e-9921-411c-a119-1b44ece9016a)

**Comment by p10tr3k** [comment]
Now I feel a bit silly. I don't know how I missed that. Thanks a lot  @jsjtxietian :)

**Comment by jsjtxietian** [comment]
Always happy to help ：）

在 2023年11月20日，20:23，P10tr3k ***@***.***> 写道：

﻿

Now I feel a bit silly. I don't know how I missed that. Thanks a lot @jsjtxietian<https://github.com/jsjtxietian> :)

**Comment by jsjtxietian** [comment]
﻿Always happy to help ：）

在 2023年11月20日，20:23，P10tr3k ***@***.***> 写道：

﻿

Now I feel a bit silly. I don't know how I missed that. Thanks a lot @jsjtxietian<https://github.com/jsjtxietian> :)
