### ISSUE TITLE
`GraphEdit`'s connection layer is not added as internal child

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#85005]
### Godot version

4.2b6

### System information

Linux/Manjaro

### Issue description

In my application, I add GraphNodes of a specific type. When getting all children with `include_internal` set to `false`, the `_connection_layer` is returned as the first child, which I don't think is intended; I expect the first non-internal child to be a user-added node.

https://github.com/godotengine/godot/blob/ad72de508363ca8d10c6b148be44a02cdf12be13/scene/gui/graph_edit.cpp#L2018

### Steps to reproduce

1. Add a GraphEdit
2. Add a GraphNode child to it at runtime
3. Try to access the node with `get_child(0)`

### Minimal reproduction project

[graphedit-non-internal-child.zip](https://github.com/godotengine/godot/files/13389335/graphedit-non-internal-child.zip)

**Comment by YuriSizov** [comment]
> 4.0b6

You probably mean 4.2?

**Comment by AThousandShips** [comment]
It was internal but seems to have been overlooked in https://github.com/godotengine/godot/pull/79308

CC @Geometror was this by design?

**Comment by Yagich** [comment]
> > 4.0b6
> 
> You probably mean 4.2?

Yes, changed to 4.2b6, thanks!

**Comment by Geometror** [comment]
I think I had to set it as a non-internal node when implementing `GraphFrame` (which was then postponed and removed from the refactoring PR) as frames need to be drawn below the connection layer (and we don't support internal nodes at arbitrary positions). Maybe this could be implemented utilizing the z index or another solution. Either way I agree the connection layer should be an internal node.
