### ISSUE TITLE
VisibleOnScreenNotifier2D events aren't triggered while the window is minimized.

### ISSUE THREAD

**Issue by DarkoreXOR** [godotengine/godot#85011]
### Godot version

4.1.2

### System information

Windows 10, Godot 4.1.2.stable.official - Vulkan

### Issue description

I have an object moving across the screen on a scene, which comes into the visibility of the screen and then disappears from the visibility area.

The events work correctly when the window is visible, but as soon as the window is minimized and disappears from the screen, the events from VisibleOnScreenNotifier2D stop working completely. 

Perhaps it's because nothing is drawn when the window is minimized, but I don't understand how to replace these events.

### Steps to reproduce

```gdscript
extends VisibleOnScreenNotifier2D

func _ready():
	connect("screen_entered", Callable(self, "_screen_entered"))
	connect("screen_exited", Callable(self, "_screen_exited"))

func _process(delta):
	position += Vector2.DOWN * delta * 500.0
	if position.y >= get_viewport_rect().size.y * 2:
		position.y = 0.0

func _screen_exited():
	print("on screen")

func _screen_entered():
	print("out of screen")
```

### Minimal reproduction project

[test_proj_gd4.zip](https://github.com/godotengine/godot/files/13391649/test_proj_gd4.zip)

**Comment by AThousandShips** [comment]
I'm not sure this is a bug, I'd say it's expected as the visibility checks here are rendering based so can't happen if the window isn't rendered

**Comment by DarkoreXOR** [comment]
I think we should write in the documentation that these events are triggered only when the window is visible / renderer is active.

Maybe we need some other way to get such events that do not depend on the renderer?

**Comment by AThousandShips** [comment]
That's not possible unless we add a lot of special case code that wouldn't be used in most projects

It should indeed be documented, but it *does* say it depends on the renderer already

**Comment by DarkoreXOR** [comment]
What can you recommend as a workaround? Check the intersection of viewport rectangle and object rectangle on the scene?

**Comment by AThousandShips** [comment]
No clue, that could work, but I'd suggest that you shouldn't try processing visual things when not visible, and that any workaround is risky, I don't see the logic in having this kind of thing work when the game is minimised, or any logic for that matter

**Comment by AThousandShips** [comment]
Also related:
* https://github.com/godotengine/godot/issues/83971

**Comment by DarkoreXOR** [comment]
Thanks for your help. These events were not very critical, and the engine knows how to optimize rendering behind the screen anyway.

I think we can close this issue if nobody needs it anymore, and since it is expected behavior of the engine.

**Comment by AThousandShips** [comment]
I'd suggest using an `Area2D` with the camera for this

Closing per the above

Thank you for discussing this 🙂
