### ISSUE TITLE
RayCast2D

### ISSUE THREAD

**Issue by yoryipoli** [godotengine/godot#85013]
### Godot version

3.5 estable

### System information

windows 10 NvidiaGforce

### Issue description

problemas con el RayCast2D al reproducir las escenas , en cambio cuando lo hago teniendo activada las formas de colision el problema desaparece , tambien me da problemas si lo hago  en la ventana minimizada al cambiarlo al zoom maximo de la ventana parace ir un poco mejor pero tambien falla. Soluciones por favor.

### Steps to reproduce

W 0:00:00.532   The argument 'delta' is never used in the function '_process'. If this is intended, prefix it with an underscore: '_delta'
  <Error de C++>UNUSED_ARGUMENT
  <Fuente>      Enemy1.1.gd:12

### Minimal reproduction project

W 0:00:00.532   The argument 'delta' is never used in the function '_process'. If this is intended, prefix it with an underscore: '_delta'
  <Error de C++>UNUSED_ARGUMENT
  <Fuente>      Enemy1.1.gd:12

**Comment by AThousandShips** [comment]
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.

**Comment by Mickeon** [comment]
I can understand some of this with, or without translation. The problem is described so vaguely it's not possible to help. The "submitted" warning is entirely unrelated, too.
