### ISSUE TITLE
Godot 3.0 ~ Compiling to uwp platform fails

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8501]
**Operating system or device - Godot version:**
Windows 10 - Godot 3.0 - MSVC compiler

**Issue description:**

getting this error when compiling to uwp platform

> c:\users\ahmed94\downloads\compressed\godot-master\platform\uwp\os_uwp.h(41): fatal error C1083: Cannot open include file: 'power_winrt.h': No such file or directory

Compiling to uwp sounds suitable for me ... especially if ".godot" files were auto associated with godot engine .. also won't worry if windows app were moved or path renamed
**Steps to reproduce:**

**Link to minimal example project:**

**Comment by nunodonato** [comment]
@vnen

**Comment by akien-mga** [comment]
Fixing the `power_winrt.h` issue is easy, it's just a rebase mistake from @StraToN. But then UWP needs further work to build against the new GLES3 renderer and likely for the new AudioServer too, so that's quite some work.

**Comment by vnen** [comment]
> Compiling to uwp sounds suitable for me ... especially if ".godot" files were auto associated with godot engine

Not sure what that means. The editor does not run as an UWP app, so associating `*.godot` files won't help.

**Comment by Ahmed0425** [comment]
I meant after fixing compiling bug then make godot appears in default programs in control panel with *.godot extension in defaults list

**Comment by vnen** [comment]
That much I got. I just don't think that the UWP app will be able to open projects from the file system outside the app package. For the editor, ideally we would have regular Windows installers (see #8057).
