### ISSUE TITLE
Wrong Java version in Android build template

### ISSUE THREAD

**Issue by cengiz-pz** [godotengine/godot#85010]
### Godot version

4.2.beta6

### System information

Windows 11, Android 13

### Issue description

In the Android build template that is installed by Godot 4.2.beta6, Java version is set to 17, while Android SDK version is set to 33.

See android/build/config.gradle:

```
ext.versions = [
    androidGradlePlugin: '7.2.1',
    compileSdk         : 33,
    // Also update 'platform/android/export/export_plugin.cpp#OPENGL_MIN_SDK_VERSION'
    minSdk             : 21,
    // Also update 'platform/android/export/export_plugin.cpp#DEFAULT_TARGET_SDK_VERSION'
    targetSdk          : 33,
    buildTools         : '33.0.2',
    kotlinVersion      : '1.7.0',
    fragmentVersion    : '1.3.6',
    nexusPublishVersion: '1.1.0',
    javaVersion        : 17,
    // Also update 'platform/android/detect.py#get_ndk_version()' when this is updated.
    ndkVersion         : '23.2.8568313'
]
```

However, in the Android documentation, the supported Java version for Android SDK v33 is 11.

See https://developer.android.com/build/jdks#compileSdk:

```
Use the table below to determine which Java version is supported by each Android API, and where to find details on which Java APIs are available.

Android	       Java
14 (API 34)	17
13 (API 33)	11
12 (API 32)	11
```

### Steps to reproduce

Install Android build template while using Godot version 4.2.beta6

### Minimal reproduction project

Android build template is too large to attach

**Comment by m4gr3d** [comment]
This is not a strict requirement otherwise the gradle build would fail. Does this create an issue in your project?

**Comment by cengiz-pz** [comment]
@m4gr3d, I am getting the following error when building various Android plugins with the 4.2.beta6 AAR library:

```
error: cannot access Godot
import org.godotengine.godot.Godot;
                            ^
  bad class file: C:\Users\x\.gradle\caches\transforms-3\e2d08578d3be354c6b4e8a6c1ec895a2\transformed\godot-lib-api.jar(/org/godotengine/godot/Godot.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by m4gr3d** [comment]
@cengiz-pz For Godot 4.2, we've bumped the JDK requirement to version 17 to match the rest of the Android ecosystem. The error suggests you may still be using JDK 11, so updating it to version 17 should fix the issue.

The compiling instructions documentation has been updated as well - https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html

**Comment by m4gr3d** [comment]
For additional context, we'll update the target SDK as well to `34` in Godot 4.3.

**Comment by cengiz-pz** [comment]
@m4gr3d, yes I'm using Android Studio, which automatically uses JDK 11 when target Android SDK version is set to 33.  I don't think it makes sense to use JDK 17 when target SDK version is 33.  In my opinion, it is clear that either target Android SDK version in Godot 4.2 should be bumped up to 34 or JDK version rolled back to 11.  Since you believe JDK 17 is needed for the "Android ecosystem," why don't we update the target SDK version to 34 in Godot 4.2?

cc: @akien-mga

**Comment by m4gr3d** [comment]
> @m4gr3d, yes I'm using Android Studio, which automatically uses JDK 11 when target Android SDK version is set to 33. I don't think it makes sense to use JDK 17 when target SDK version is 33. In my opinion, it is clear that either target Android SDK version in Godot 4.2 should be bumped up to 34 or JDK version rolled back to 11. Since you believe JDK 17 is needed for the "Android ecosystem," why don't we update the target SDK version to 34 in Godot 4.2?
> 
> cc: @akien-mga

Updating the target SDK version to 34 requires updating other dependencies and our build setup / logic; i.e: it's a more complex update hence why it's targeted to Godot 4.3.

> yes I'm using Android Studio, which automatically uses JDK 11 when target Android SDK version is set to 33

The JDK selection is tied to the version of Android Studio used, not the target Android SDK. If you download the latest version of Android Studio, you'll see that the default JDK is version 17, which is what I mean by matching the rest of the Android ecosystem.

In your setup, you can go to `Settings` -> `Build, Execution, Deployment` -> `Build Tools` -> `Gradle` in order to update the JDK used to version 17.

**Comment by cengiz-pz** [comment]
Closing as build of plugins is successful with JDK 17
