### ISSUE TITLE
4.2.beta6.mono iOS build crashes on iOS 12

### ISSUE THREAD

**Issue by aogden** [godotengine/godot#85025]
### Godot version

v4.2.beta6.mono.official [64150060f]

### System information

iOS 12.5.7

### Issue description

iOS 12 builds crash on launch with error
```
dyld: Library not loaded: @rpath/GodotiOS12Sandbox.dylib
  Referenced from: /var/containers/Bundle/Application/42C3A63F-4D55-4F2E-A5EF-44581F92994C/GodotiOS12Sandbox.app/GodotiOS12Sandbox
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/42C3A63F-4D55-4F2E-A5EF-44581F92994C/GodotiOS12Sandbox.app/Frameworks/GodotiOS12Sandbox.dylib: missing LC_DYLD_INFO load command
```

### Steps to reproduce

Example project included. Export to iOS and test on device running iOS 12 (iPhone 5S for me)

### Minimal reproduction project

[GodotiOS12Sandbox.zip](https://github.com/godotengine/godot/files/13395227/GodotiOS12Sandbox.zip)

**Comment by bruvzg** [comment]
Try it with RC1, .Net export for iOS was mostly broken in previous builds.

> iPhone 5S

Your project seems to be set to use `Mobile` Vulkan renderer, it's unlikely it will reliably run on devices with SoC older than A12, but OpenGL (Compatibility) renderer might work.

**Comment by aogden** [comment]
I will try with RC1, thanks saw you just posted it. Compatibility renderer is set for mobile in project settings.
<img width="886" alt="Screenshot 2023-11-17 at 11 14 41 AM" src="https://github.com/godotengine/godot/assets/1437894/f86ec2d9-5c4d-49d7-9d19-fcb6a3c44ad6">

**Comment by aogden** [comment]
Tested on RC1 and did not see the issue. Thanks
