### ISSUE TITLE
Texture repeating doesn't work

### ISSUE THREAD

**Issue by danilwhale** [godotengine/godot#85021]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.22635 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

For unknown reason when I set region and set texture_repeat to Enabled in Sprite2D, it doesn't repeat anything
Region has same size as image

![image](https://github.com/godotengine/godot/assets/61111955/5562bb48-d557-41b7-8265-0f1c646e69e5)

### Steps to reproduce

1. Place any Sprite2D with texture applied
2. Set region with same size as texture
3. Set texture_repeat (Texture->Repeat) to Enabled 

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/13394633/project.zip)

**Comment by kleonc** [comment]
> Region has same size as image
>
> ### Steps to reproduce
> 
>   1. Place any Sprite2D with texture applied
> 
>   2. Set region with same size as texture
> 
>   3. Set texture_repeat (Texture->Repeat) to Enabled

If region size equals texture size then there's no "room" for any repeating, not sure why would you expect repeating to happen in such case. Set region size to be bigger than the texture size and you're see texture repeat works:

![DmNqiGGWs6](https://github.com/godotengine/godot/assets/9283098/aa1aadad-52c1-4270-b02d-f7a6965206a7)

Closing as no bug.
