### ISSUE TITLE
[Request] Right-clicking a folder in the FileSystem panel should give an option to "Show In File Manager"

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#8503]
Right-clicking a file in FileSystem's Icon view will give you the option to Show In File Manager:

![image](https://cloud.githubusercontent.com/assets/27100585/25318230/ccd98180-28cd-11e7-94bc-39f43ae49414.png)

This is really useful for when you want to drop in some assets into the same folder, but I think this behaviour should be extended to folders in the folder tree view. As it is, Godot 2.1.3 shows no menu when right-clicking a folder, and 3.0 only gives the option to expand and collapse all folders:

![image](https://cloud.githubusercontent.com/assets/27100585/25318289/96f657fe-28ce-11e7-82b3-4335833480de.png)

**Comment by attilix** [comment]
I think that this would be useful in certain situations, I' m working on it.
