### ISSUE TITLE
Saving Resources Externally Requires Make Unique After Parent scene have been saved.

### ISSUE THREAD

**Issue by EroAxe** [godotengine/godot#85045]
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Windows 10

### Issue description

When creating a new Resource in a scene through the Inspector and then saving the scene it is in.  The Save button no longer prompts you with a dialogue to save the Resource externally.  

The workflow I'm used to in past versions is that this would pop up a "Save As" dialog equivalent and let me save it externally.  But it seems like saving now defaults to saving locally after the scene has been saved unless the resource has been made unique.  That's how it worked in 4.2 beta6 but the rc1 seems to have changed it.

### Steps to reproduce

- Add a Node with a Resource Property in the Inspector (I used Label with the Theme property)
- Set that Property to a New Instance of the Resource.
- Save the Scene
- Try to save the Resource through the Dropdown

### Minimal reproduction project

[Resource Save Dialog.zip](https://github.com/godotengine/godot/files/13399460/Resource.Save.Dialog.zip)

**Comment by Yagich** [comment]
This seems to be intended behavior, so a compromise would be to add a "Save As" button to the resource picker drop down.
May be related to #84931?

**Comment by Rindbee** [comment]
Related to #84630.
So reverting `resource_path` is also a solution.

**Comment by KoBeWi** [comment]
I think the solution would be adding Save As option to the menu.
