### ISSUE TITLE
`AnimationPlayer.advance()` does not work when called right after `play()` within 1-2 process frames

### ISSUE THREAD

**Issue by rt9391** [godotengine/godot#85052]
### Godot version

4.2.rc1

### System information

win11

### Issue description
If you call animation.advance() after play() within a single process frame, the animation will not work properly.
The advance function does not work.
![image](https://github.com/godotengine/godot/assets/91177204/0edd6d63-9bfb-4860-8e14-1f0767bc4346)
The advance function does not work either.
![image](https://github.com/godotengine/godot/assets/91177204/fa5397d4-4615-44c9-aa7e-c2eae0e59a5f)
The advance function works, but 2 frames have already shown
![image](https://github.com/godotengine/godot/assets/91177204/c2df992a-ab64-43af-b9c7-89abb005b1c2)

This bug is not present in 4.1.3.stable.

### Steps to reproduce

create a scene with animation and run code like below.
```
func _ready():
	animation_player.play("new_animation")   
	animation_player.advance(5.0)
```
the advance function did nothing.

### Minimal reproduction project

[animation_play_advence.zip](https://github.com/godotengine/godot/files/13400233/animation_play_advence.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/83522
and https://github.com/godotengine/godot/issues/48982.

**Comment by YuriSizov** [comment]
Can you confirm that it works correctly in 4.1.3? Or, alternatively, that it doesn't work correctly in 4.1.3, of course.

**Comment by rt9391** [comment]
> Can you confirm that it works correctly in 4.1.3? Or, alternatively, that it doesn't work correctly in 4.1.3, of course.

Yes, I can confirm it works in 4.1.3.
![image](https://github.com/godotengine/godot/assets/91177204/28df95a1-ab7a-4553-9e8b-284bac414caa)
