### ISSUE TITLE
Extensions for Godot

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#8505]
# Extensions

After talking to @touilleMan and @reduz in Paris (it was awesome!!!) I'm writing down this proposal.

GDNative is a nice way to use third party libraries in your game or just optimize performance critical code, but it *could* also be used to add "extensions" to Godot (for the lack of a better name, "plugin" and "add-on" are already taken 😛 )

## Current situation

A GDNativeScript represents *one class* in a GDNativeLibrary. To have any effect, this script must be attached to any object. This is cool to write game code or wrap third party code in a class.

The current way to "extend" Godot is via plugins (or more precisely, "editor plugins"). These plugins can do a lot of awesome things, but they all only run in the editor. GDNative scripts can be used to make plugins as well, but they can't do anything that will have an impact on the running game.

## Proposal

![extension](https://cloud.githubusercontent.com/assets/5209613/25318699/7d9c0810-2894-11e7-865f-c4ceae5f6c84.png)

Have a new project settings tab for "extensions". Extensions are GDNativeLibraries that don't need to expose any classes, they just get run and that's it.

These extensions get loaded at startup, in the editor as well as in a game.

### Implementation of an extension

A regular GDNativeLibrary, but it contains a special function `godot_native_extension_init` and `godot_native_extension_terminate` that get called at startup and shutdown of Godot.

The C API (modules/gdnative/godot.h and modules/gdnative/godot/*) will contain new functions, like `godot_extension_register_importer(godot_extension_importer *importer)`. The `godot_extension_importer` type would just be a struct with function pointers.

### Loading and installing

A new directory called "extensions" containing subfolders for the different extension. In those folders a file "extension.cfg" or something like that. This file specifies the GDNativeLibrary to use to load the extension.

```
- extensions
    - fbx_loader
        - extension.cfg
        - fbx_library.tres
    - python_language
        - extension.cfg
        - python_library.tres
```

When the editor or game starts the extensions get loaded.

The Asset Lib could feature a new type of asset: "extension" and install that in the right place.
Once installed then the extension would get initialized, editor restart should not be required. (the Asset Lib downloader needs to initialize the initialization process 😄 )

### Use cases

* downloadable scripting languages in the AssetLib (with editor support)
* new resource importers
* possibly more that I can't think of right now 😄 

-----

WDYT?

**Comment by reduz** [comment]
I think this would be better as something specific to gdnative. We could
call it "native modules" or something like that.

**Comment by reduz** [comment]
Maybe to make them totally clear and avoid confusion, they could be
"gdnative submodules"

**Comment by karroffel** [comment]
Oh yeah, "GDNative submodes" sounds good!

**Comment by reduz** [comment]
Could be shortened to submodules too..

**Comment by akien-mga** [comment]
Or maybe change "Plugins" to "Script plugins" and add "Native plugins"? That would be the most explicit regarding what they are, and how they are used: both can be plugged into the engine, the former are script-based and interpreted, the latter are native code.

**Comment by reduz** [comment]
The problem is that plugins are editor plugins, while submodules are
general purpose modules that extend engine support, and not really editor
related.. so they are not quite the same

**Comment by reduz** [comment]
As in, a plugin is on a higher level than a submodule, you could easily
make a plugin that uses a submodule

**Comment by reduz** [comment]
Example of the above: A minecraft like world editor. You can have a
submodule that generates the voxel terrain in C++. At the same time, an
editor plugin which contains an UI to edit it, which is written jn
gdscript. Both are part of a single addon that you get from asset lib.

So the relationship is like:

Addon -> Editor Plugin -> Submodule

**Comment by karroffel** [comment]
good example! "Plugins" are actually "Editor plugins", "submodules" (not that sure about the name though, of what are they a sub-part?) are not specific to the editor.

The Minecraft example could make use of a submodule because those are loaded before editor plugins are loaded.

**Comment by akien-mga** [comment]
So in the end those are just pluggable "modules", as we understand the stuff in `modules/`. Users have already been confused by our choice of terms with modules vs plugins, so it might be a good opportunity to rethink that a bit for 3.0 :)

**Comment by reduz** [comment]
Yeah, you can still perfectly use gdnative for editor plugins.. this is a
little lower level, so I suppose submodule conveys both that its a module
based off another module.

The main source of confusion is imo the addons folder, which needs to be
there because we can't install modules to custom locations... Which is
something that we can probably do change in 3.0, as we deprecated xml and
the remaining formats (scn and tscn) allow changing dependency location
with little hassle. (This was next to impossible in xml).

So.. for 3.0 we could get rid of the addons folder altogether and let godot
scan the plugins from EditorFilesystem normally.

With addons gone, we would be just left with EditorPlugin and SubModule (or
better name).

Does this sound right?

On Apr 24, 2017 10:28 AM, "Rémi Verschelde" <notifications@github.com>
wrote:

So in the end those are just pluggable "modules", as we understand the
stuff in modules/. Users have already been confused by our choice of terms
with modules vs plugins, so it might be a good opportunity to rethink that
a bit for 3.0 :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8505#issuecomment-296574581>,
or mute the thread

**Comment by karroffel** [comment]
sounds good to me!

I think we should choose the names carefully tough

**Comment by Zylann** [comment]
How is this different than having a regular GDNativeLibrary having an editor version and export version? Why does it need to be a specific thing?

You said plugins can't have an impact on the game, but it's wrong. My gdscript terrain plugin is able to run both in editor and in game. The only issue I had with it is about telling Godot not to export the editor-only part.

**Comment by reduz** [comment]
Editor just expects you to provide an EditorPlugin. For everything else
it's the same.

**Comment by bojidar-bg** [comment]
What's the issue of breaking compatibility with current plugins, and shipping the more-extensible "extensions"/"plugmodules"/"native plugins" with ability to add EditorPlugin nodes and to be made with GDScript?

That way, we would not be forced to use GDNative for simple importers (e.g. of a custom text-based format), while we can still do everything from the proposal. And, as an additional plus, one would be able to even use C# for import/export/stuff!

**Comment by reduz** [comment]
Breaking compatibility is only intended to install addons anywhere, and
nothing else...

**Comment by Zylann** [comment]
Installing addons anywhere is already a separate issue though https://github.com/godotengine/godot/issues/6023

**Comment by RameshRavone** [comment]
Just wanted to know the status (is it being developed or dropped)

**Comment by touilleMan** [comment]
@RameshRavone now that my Python binding is working, I'm going to start working on this feature

no promise on the eta though ;-)

**Comment by karroffel** [comment]
@touilleMan I started laying down the basics for that on my fork, if you want you could help develop it there. I wrote you a PM on Discord about that too

**Comment by reduz** [comment]
how is this going?

**Comment by touilleMan** [comment]
@reduz pretty well ^^

You can have a look [on my fork](https://github.com/touilleMan/godot/tree/pluginscript) and the corresponding [Python pluginscript module](https://github.com/touilleMan/godot-python/tree/pluginscript).

So far I got my Pong example written in Python working :smile: 
I still have to bind the editor and debugger functions though.

**Comment by karroffel** [comment]
This gets partially implemented by #10921, there's basically only a proper UI missing and then more APIs to actually use (like pluginscript)

**Comment by HummusSamurai** [comment]
Closed by https://github.com/godotengine/godot/pull/11953 ?

**Comment by karroffel** [comment]
Well it's more like an ongoing effort, PluginScript is only one application, GDNative singletons basically solve this issue.

But you are right, it can be closed now.
