### ISSUE TITLE
Cull 3D performance issue with animated model in Compatibility renderer

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#85053]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Ubuntu 22.04.3 LTS 22.04 - X11 - GLES3 (Compatibility) - AMD Radeon RX 560 Series (polaris11, LLVM 15.0.7, DRM 3.42, 5.15.0-88-generic) () - AMD Ryzen 3 1200 Quad-Core Processor (4 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/1330325/7a986599-5a68-42a4-beb1-5d3b4bf7db6b)
![image](https://github.com/godotengine/godot/assets/1330325/e8b8546b-b47b-4add-9567-7f70709ab03c)

Culling 3D goes bellow 60 fps even with just about 50 simple animated models. With v4.2.dev6.official [57a6813bb] many more models can be spawned without fps drop. However, both versions do show high cpu usage for culling 3D. Without animations there's barely any usage.

### Steps to reproduce

Spawn models with animation with the Compatibility renderer.

### Minimal reproduction project

[CullMRP.zip](https://github.com/godotengine/godot/files/13400514/CullMRP.zip)

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.beta da0b1eb12 (Linux, GeForce RTX 4090 with NVIDIA 535.113.01). That said, I don't see anything being animated in the MRP – do I need to do something specific?

![Screenshot_20231118_150234](https://github.com/godotengine/godot/assets/180032/db6179b4-e7da-4bb4-83fb-64b7a1797966)

PS: Add the following code to the script to make the benchmark more deterministic:

```gdscript
func _ready():
	seed(0)
```

This ensures blobs always spawn at the same positions every run.

**Comment by xix-xeaon** [comment]
@Calinou Sorry, I accidentially zipped with the animation play commented. Uncomment the ready function in slime.gd, I've updated the mrp.

**Comment by clayjohn** [comment]
Tested locally, in dev6 I can have 10X as many blobs in the scene before I drop below 60FPS (~700 in dev6, ~60 in beta1)
