### ISSUE TITLE
Stylus, Windows 10, left click and viewport rotation Gizmo not working

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot#85064]
### Godot version

v4.2.rc1

### System information

Windows 10.0.19045

### Issue description

There are 2 main issues when using a stylus in windows 10 that I have noticed:

- 1) the viewport rotation gizmo goes crazy when we try to use it
- 2) the buttons and the items in the menu lists cannot be clicked

Note that these issues are not happening in 3.5, although I seem to remember the viewport rotation gizmo suffered this issue in 3.0.

Note that the issue 2) is solved when disabling Windows Ink.

The hardware used is an XP Pen 16TP 4k.

I took some videos here, so you can better see what is happening:

https://github.com/godotengine/godot/assets/10520249/80654547-e7b2-4939-9d77-a71a58dcfc6b

https://github.com/godotengine/godot/assets/10520249/a2893e43-3bf0-4297-a7ce-ae531774c995

### Steps to reproduce

- install a xp pen tablet
- try to use the viewport rotation gizmo, or try to use the menus (e.g Editor -> Editor Settings...)
- enjoy the 🪲

### Minimal reproduction project

Default project

EDIT: I've made it! I downloaded Handbrake and .NET and got to resize the videos!

**Comment by Calinou** [comment]
> the viewport rotation gizmo goes crazy when we try to use it

The 3D editor supports touchscreen events for navigation, but it's only enabled on mobile platforms by default. It also won't handle pen events as these are separate events, and the exact UX should be different from a touch screen.

**Comment by Nodragem** [comment]
Hello! This bug has nothing to do with touchscreen. Pen tablets work rather like a mouse in terms of UX, and don't need a separate UX.

When the pen touches the Viewport Rotation Gizmo, the camera aligns with the world Y axis and starts to rotate very fast. In 3.5, the pen was working as expected. So I believe there was some support.

I tried the Viewport Navigation Gizmo, just to see, and it also does not work with the pen. When using the rotatiom controller, the cursor get stuck to the left of the circle, causing the camera to progressively align with Y, and rotate very fast. See below:


https://github.com/godotengine/godot/assets/10520249/b0dd7778-443b-436c-8054-9322c1b8884b

**Comment by Nodragem** [comment]
Hello, I tested it with Windows 11 and Godot 4.2.x and 4.3 dev 5 and the Viewport Rotation Gizmo is now working at intended with a pen tablet.

However, the left click is still not working in the menus. I will open a different issue for it.
