### ISSUE TITLE
Looped animation shows first frame if last one is selected.

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot#85068]
### Godot version

4.2 rc1

### System information

ubuntu 22.04

### Issue description

Looped animation in animation editor shows first frame if last one is selected. Selected last frame in the timeline is not relevant to its time and visually you don't know how last frame looks.

https://github.com/godotengine/godot/assets/72736632/76237f82-0e2e-42f2-993c-68c1c8860663

### Steps to reproduce

- Make looped animation.
- Add frame in the end of the timeline.
- Select last frame.

### Minimal reproduction project

N/A

**Comment by TokageItLab** [comment]
The end of the loop has two modes: trimming and replacing the first key. trimming mode should not cause this problem, so perhaps we should enforce trimming mode when seeking in only Editor

**Comment by vyshliy** [comment]
I didn't notice any difference when switching to clamp.


https://github.com/godotengine/godot/assets/72736632/7a4b41ae-1dd7-4c56-8887-74b675922e0d


And a little off topic. Apparently the wrap mod only has an effect on looped animation. It might be worth making it inactive, like the curves icon, for example, to make it clear when it makes sense to use it.

**Comment by TokageItLab** [comment]
Indeed, it did not matter sorry. This should not be a problem except in loop mode.

However, if you solve this in the editor only, the problem may be that there will be difference results between playbacking and seeking in the editor. Well, at least I think we can add a hack to revert to the seek results as of Godot 4.1 for editor only.
