### ISSUE TITLE
Input (get_vector, get_axis) returns wrong value when input changes rapidly

### ISSUE THREAD

**Issue by warent** [godotengine/godot#85076]
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Godot v4.2.rc1 - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 Ti (NVIDIA; 30.0.15.1216) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

NOTE: I also had this in 4.1

When you rapidly change the value sent to Input.action_press, sometimes the value spontaneously becomes wrong by a wide margin, and it maintains this wrong-offset until the action is released.

### Steps to reproduce

In this video, look out for two logs:
`TRANSFER! :: (action name) :: (value)` is the raw value that is being sent to `Input.action_press`

`STICK DIRECTION RECEIVED` is the value output directly from
```gdscript
var stick_vector = Input.get_vector("stick_left", "stick_right", "stick_up", "stick_down")
```

Notice at 20 seconds into the video (also briefly at 13 seconds), the value in "TRANSFER" is the expected value, but the "STICK DIRECTION RECEIVED" is suddenly completely wrong.

https://github.com/godotengine/godot/assets/13342266/99e8726b-c5ca-439a-a48b-ede9a420008b

### Minimal reproduction project

https://github.com/warent/godot-input-vector-bug

[InputVectorIssue.zip](https://github.com/godotengine/godot/files/13402344/InputVectorIssue.zip)

**Comment by warent** [comment]
I'm not sure if this is related, or a secondary issue, but at the very end of the video after releasing the stick,even though it _seems_ to be working again, notice that the floating point precision is lost in the action press (they're different by about 0.05)
![image](https://github.com/godotengine/godot/assets/13342266/c28ae6fb-7250-4b26-8035-0702a224977a)

**Comment by Calinou** [comment]
cc @aaronfranke @YeldhamDev

**Comment by aaronfranke** [comment]
This isn't a problem for me to solve. `Input.get_vector()` does not know about past inputs. So it's a problem with the underlying input system passing incorrect values to this function.

@warent Can you reproduce this with `Input.get_action_strength()`?
