### ISSUE TITLE
TileMap Painting by accident when switching between editor Select Mode (Q) and Move Mode (W)

### ISSUE THREAD

**Issue by EnderSyth** [godotengine/godot#85077]
### Godot version

4.2 RC1

### System information

Windows 11 

### Issue description

While working with the TileMap following a tutorial I've ran into several issues that turned out to be related to persistence of modes between tools (Select, Scale, Erase, and Move). I tried to write a report only to stumble on the reproduction steps, but solved most the issue myself when figuring out persistence of these modes. 

The remaining bug I've identified is when in paint mode in the tilemap, select mode in the editor, where you paint a large line between move positions when using hotkeys to switch between move and select mode.

### Steps to reproduce

1) Pain a tile line of tiles (any direction or length)
2) Press W to switch to move mode while having not released the left mouse button
3) Let got of left mouse, use move mode drag the screen to a new position (method doesn't matter middles click or left mouse)
4) Press Q to switch editor to select mode.
5) A line will be created for the entire path you have move the mouse through, further you'll be stuck active painting where ever the mouse moves until you left click again.

I've also observed some others behaviors that are odd such as snap moving to the mouse position when transitioning to move mode. I suspect its related.

### Minimal reproduction project

N/A

**Comment by Wiltof** [comment]
Reproducible on latest main branch commit, I'll look into it and see if I can do something
