### ISSUE TITLE
NavigationRegion2D Not Rendering Cutout Consistently

### ISSUE THREAD

**Issue by LeifintheWind** [godotengine/godot#85098]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 10

### Issue description

When adding another outline with `add_outline()` to the `NavigationRegion2D` to create a hole via `make_polygons_from_outlines()`, sometimes the renderer does not create a hole and instead layers another polygon on top. This issue is somehow location-dependent, and is shown in the minimal reproduction project when the `CollisionPolygon2D` is placed at (-256,120) vs (360,-100) for example. 

Unsure if this is necessary, but expanding the `Polygon` via `offset_polygon()` is used to create the outline in the project. I was unable to reproduce this bug without it. But I do not know if it's necessary.

Based on how the `NavigationRegion2D` is rendered with and without the hole, I believe this is not just a rendering issue but the hole is not actually created. As when the hole renders correctly it also is triangulated correctly, and when it doesn't the original `NavigationRegion2D` remains a single polygon.

![broken_cutout_screenshot](https://github.com/godotengine/godot/assets/114954877/cc46b9d4-29d6-4a36-87f1-d62aad9a8b68)
![Working_cutout_screenshot](https://github.com/godotengine/godot/assets/114954877/daf7c78d-cbde-48de-aecf-484e0b559c20)

### Steps to reproduce

1. Create a `NavigationRegion2D` with a `NavigationPolygon` large enough to encompass another shape inside of it.
2. Create another `Polygon` inside of the `NavigationRegion2D`
3. Expand the `Polygon`  via `offset_polygon()`
4. Add the `Polygon` vertices as an outline to the `NavigationPolygon` and then `make_polygons_from_outlines()`
5. Move the `Polygon` around until it does not render a hole correctly. This part is a bit of a mystery to me, but the minimal production project starts the `Polygon` in a position (-256,120) where it doesn't render correctly. Moving the `Polygon` to (360,-100) will cause the `NavigationPolygon2D` to render the hole correctly.

### Minimal reproduction project

[navigation_polygon_rendering.zip](https://github.com/godotengine/godot/files/13403988/navigation_polygon_rendering.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by smix8** [comment]
Same as https://github.com/godotengine/godot/issues/70823

The make_polygons_from_outlines() function has a lot of known problems that break the navigation mesh creation easily, hence why that function is deprecated in Godot 4.2 that adds 2D navigation mesh baking.

**Comment by LeifintheWind** [comment]
Looks like this issue is irrelevant! Thanks
