### ISSUE TITLE
Centering a scaled container centers relative to the original size of the container

### ISSUE THREAD

**Issue by Starkandco** [godotengine/godot#85091]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

I am expecting a scaled container to be correctly centered relative to its scaled size using center for anchor preset and alignment but it seems to retain the center coords for the original size

### Steps to reproduce

Tested with box containers:
1) Set up control for full screen size
2) Add box container 
3) Increase scale on box container
4) Center box container alignment and anchor preset

Expected:
Center is relevant to scaled container

Actual:
Center is relevant to original container size

Expected result would be similar to manually increasing container size and centering as below:
![image](https://github.com/godotengine/godot/assets/19207171/3c79efec-37f7-40c3-979e-375fe7c14f68)

Actual result is offset:
![image](https://github.com/godotengine/godot/assets/19207171/fe5cf776-5231-41b4-ab26-2e7b8f3024c2)

### Minimal reproduction project

![image](https://github.com/godotengine/godot/assets/19207171/9e32ee60-33f1-47f1-ac67-ab873ec954f7)

**Comment by Starkandco** [comment]
This also affects other canvas items - tested with panel, label

**Comment by Sauermann** [comment]
https://github.com/godotengine/godot/blob/80de898d721f952dac0b102d48bb73d6b02ee1e8/scene/gui/control.cpp#L1227-L1229

`data.anchor` is in the local coordinate system of the Control node.
`parent_rect.position` is in the coordinate system of the parent Control node.
Mixing different coordinate systems is never a good idea.

**Comment by Starkandco** [comment]
@Sauermann @AThousandShips I think this is a duplicate of 

https://github.com/godotengine/godot/issues/19068

Also I see a similar looking issue opened 14d ago

https://github.com/godotengine/godot/issues/85668

I guess mine and the more recent ticket can be closed

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/19068.

**Comment by cidwel** [comment]
I think this might be also related:
https://github.com/godotengine/godot/issues/56746
