### ISSUE TITLE
remove_paragraph(0) in RichTextLabel only works once

### ISSUE THREAD

**Issue by TheSofox** [godotengine/godot#85096]
### Godot version

80de898d721f952dac0b102d48bb73d6b02ee1e8

### System information

Window 10 - 4.2.rc

### Issue description

Calling "remove_paragraph(0)" on a RichTextLabel should remove the first line of text in the label. However, it doesn't seem to work more than once in a row. Even calling "remove_paragraph(1)" actually works better since it always removes the 2nd line even when called repeatedly.

### Steps to reproduce

1. Fill a RichTextLabel with several lines of text
2. Call "remove_paragraph(0)" on it multiple times.

**Expected:**
Each time you call "remove_paragraph(0)", the first line should be deleted.

**Actual:**
The first line is deleted the first time you call "remove_paragraph(0)", but each subsequent time you do it, nothing happens. 

Example project attached makes it easy to test. RichTextLabel has been set up already, along with buttons to call "remove_paragraph" when pressed.

### Minimal reproduction project

[RichTextRemoveParagraph.zip](https://github.com/godotengine/godot/files/13403919/RichTextRemoveParagraph.zip)

**Comment by jsjtxietian** [comment]
Confirmed. Related to https://github.com/godotengine/godot/blob/80de898d721f952dac0b102d48bb73d6b02ee1e8/scene/gui/rich_text_label.cpp#L3389-L3391

Comment them and it works as expected. cc @bruvzg

**Comment by nickyfoo** [comment]
Not sure if this is possibly related, but I have a [PR ](https://github.com/godotengine/godot/pull/84312) relating to crashes from RichTextLabel as well

**Comment by miv391** [comment]
If the `RichTextLabel`'s `text` property supposed to always return the current content? Now removing paragraphs (any paragraphs, with or without jsjtxietian's fix) doesn't change what `text` returns. The original content is always returned.
