### ISSUE TITLE
AnimationPlayer: Cubic interpolation of float properties gives wrong values

### ISSUE THREAD

**Issue by chardish** [godotengine/godot#85104]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700S (Advanced Micro Devices, Inc.; 31.0.12024.2005) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When using an AnimationPlayer to control a float property of an object between 0.0 and 1.0, I noticed the property was going way over 1.0. It looks like this only happens when the property is set to cubically interpolate. (Linear and nearest interpolations both provide values clamped between 0 and 1, as expected.

### Steps to reproduce

1. Create a script with a float property on it
2. Attach that script to a node
3. Create a new AnimationPlayer node, and set up a track to change the float property you just set up
4. Add keyframes to interpolate between 0 and 1, and set the interpolation type to cubic
5. Observe that the value of the float property reaches values outside of 0 and 1

### Minimal reproduction project

[animation-bug-minrepro.zip](https://github.com/godotengine/godot/files/13404563/animation-bug-minrepro.zip)

**Comment by vyshliy** [comment]
Probably related to #85066

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by chardish** [comment]
Still repros on v4.1.3.stable.mono.official [f06b6836a]

**Comment by TokageItLab** [comment]
This is a duplication of https://github.com/godotengine/godot/issues/57952, regardless of https://github.com/godotengine/godot/issues/85066. There is an overshoot problem with cubic completion.
