### ISSUE TITLE
Install Project popup's child controls reset their layout after changing project path, but the popup's size doesn't

### ISSUE THREAD

**Issue by Sylfa** [godotengine/godot#85118]
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Godot v4.2.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 30.0.14.7280) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When installing anything with a long name from the Asset Library Projects, the Install Project popup is wider than normal to fit the name comfortably in the popup. 

![Godot-bugreport-1](https://github.com/godotengine/godot/assets/4145461/66f5d1b1-5d53-460a-810d-4b96a9381118)

However, when you browse into a different folder, it resets to the 4.1.x layout while keeping the larger window size.

![Godot-bugreport-2](https://github.com/godotengine/godot/assets/4145461/5847e5c0-57a6-4aa5-8b58-38592870bed9)

This results in ghosts of the wider design still being visible to the right of the actual buttons. This is only a visual glitch and does not break the functionality of the popup, and the ghosts of the buttons to the right does not react to mouse input.

### Steps to reproduce

1. Open up Godot 4.2-rc1
2. Switch to Asset Library Projects
3. Search for "Shape Manipulation"
4. Click the asset "Shape Manipulation Basics - Line2D…"
5. Click download
6. Wait for download
7. Note the wide layout of the UI
8. Click Browse
9. Click Select Current Folder, you do not need to change folder to test this

![Godot-bugreport-2](https://github.com/godotengine/godot/assets/4145461/5847e5c0-57a6-4aa5-8b58-38592870bed9)

Note that the layout is now narrower, but has the ghosts of the wider layout still showing.
The ghost elements are just a visual glitch and cannot be interacted with.
Besides the visual glitch the popup still functions as normal.

This was confirmed to not happen in version v4.1.1.stable.mono.official [bd6af8e0e], in this version the layout is never widened when picking an asset with a long name.

### Minimal reproduction project

None possible, the bug is in the Project Manager

**Comment by akien-mga** [comment]
I don't seem to reproduce the issue on Linux/KDE with 4.2-rc1. It looks the same before and after using the "Browse" button.

![image](https://github.com/godotengine/godot/assets/4701338/22b68b39-e8a9-4eec-8d41-d34f64b0874b)

It might depend on HiDPI stuff though, what's your monitor resolution and Godot DPI scaling factor?

**Comment by Sylfa** [comment]
No HiDPI here, 1680 x 1050(p) (59.883Hz) monitor.
Godot settings

- Display Scale: 100%
- Custom Display Scale: 1.0
- Font Size: 14

Windows UI scaling is also at 100%

Not sure what could differ between the systems, other than the obvious Windows 10 vs Linux/KDE.
I could give you the dxdiag output, but I'm not so sure it'd help.

**Comment by YuriSizov** [comment]
Can confirm this happens for me on Windows. I'm not entirely sure why the dialog changes size in the first place. Line edits preset in the form should keep their size and the overflowing text should just be cut, because line edits have natural text overflow capability.
