### ISSUE TITLE
Lambda/Callable memory leak

### ISSUE THREAD

**Issue by gokiburikin** [godotengine/godot#85112]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Godot v4.2.beta6 - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

Was testing benchmarks on the latest RC and this snippet started leaking memory as of 4.2beta6 up to the master branch. Does not happen in any version I tested from 4.1 stable to 4.2beta5.

https://github.com/godotengine/godot/assets/3820082/86283a44-2ce9-46a0-a60b-3365c016fca8

### Steps to reproduce

```gdscript
func _process(delta: float) -> void:
	for i in 10000: (func(): randf()).call()
	print(OS.get_static_memory_usage())
```

### Minimal reproduction project

N/A

**Comment by gokiburikin** [comment]
Assuming I followed the bisecting steps correctly it leads back to this https://github.com/godotengine/godot/commit/271511726b02848783904429c8dde857f6266429.

**Comment by Chaosus** [comment]
cc @RandomShaper / @adamscott
