### ISSUE TITLE
Alert window on Android theme looks old

### ISSUE THREAD

**Issue by BQKdev** [godotengine/godot#85110]
### Godot version

4.1.2

### System information

Godot v4.1.2 stable / Debug device Oneplus 10 pro Android 13

### Issue description

I been testing the OS class, and I found out that the theme of the OS alert looks old and I want to use a new look for games that are for new devices.

### Steps to reproduce

![os_alert_test](https://github.com/godotengine/godot/assets/109998396/3a62e337-1ecc-4ad6-a9e9-d64071b8626b)

1. Add any node
2. Add a script file to the node

**In the script:** 

func _ready():
	OS.alert("Test alert!", "Alert")

### Minimal reproduction project

[OSalertTest.zip](https://github.com/godotengine/godot/files/13404833/OSalertTest.zip)

**Comment by Alex2782** [comment]
It probably won't be worth switching, I think the app will also be bigger.

-----------------------
`import android.app.AlertDialog`
https://github.com/godotengine/godot/blob/80de898d721f952dac0b102d48bb73d6b02ee1e8/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L629

-------------------

**new** dialog `import androidx.compose.material3.AlertDialog`

[androidx/compose/material3](
https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#AlertDialog(kotlin.Function0,androidx.compose.ui.Modifier,androidx.compose.ui.window.DialogProperties,kotlin.Function0))

**Comment by BQKdev** [comment]
I can change the version of the alert !? Thanks I didn't know I could do that. I'll check it and make sure I can change it, even though I'm not sure how to.

**Comment by Alex2782** [comment]
You could compile your own version of Godot.

https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/android_studio.html

**Comment by akien-mga** [comment]
As long as the Material3 API is supported on all Android versions we currently support, it would make sense to switch yeah.

**Comment by Calinou** [comment]
> As long as the Material3 API is supported on all Android versions we currently support, it would make sense to switch yeah.

[Material 3](https://developer.android.com/jetpack/compose/designsystems/material2-material3) isn't part of the core Android libraries but it's part of Jetpack instead, so it would mean having to integrate that library in the Godot export.

**Comment by BQKdev** [comment]
That means that we not only need to implement the code for the compile Godot version, but also the library for Godot to use it?

**Comment by BQKdev** [comment]
> That means that we not only need to implement the code for the compile Godot version, but also the library for Godot to use it?

I think that it would be useful for side projects, since I can code the Kit of the Godot. 

Since upgrading the theme, means more old devices, won't support the theme.

**Comment by Alex2782** [comment]
Material 3 - AlertDialog is [ExperimentalMaterial3Api](https://developer.android.com/reference/kotlin/androidx/compose/material3/ExperimentalMaterial3Api)

These changes are necessary as a minimum (without Material / Android 7+ Style?): https://github.com/godotengine/godot/compare/master...Alex2782:godot:androidx.alert

<details><summary>Android Studio, new downloads / libs / dependencies</summary>

```logs
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.6.1/appcompat-1.6.1.pom, took 337 ms (5,29 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.6.1/appcompat-1.6.1.module, took 41 ms (6,89 kB)
Download https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.6.0/activity-1.6.0.pom, took 30 ms (3,66 kB)
Download https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.6.0/activity-1.6.0.module, took 32 ms (5,58 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat-resources/1.6.1/appcompat-resources-1.6.1.pom, took 36 ms (3,02 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat-resources/1.6.1/appcompat-resources-1.6.1.module, took 37 ms (4,48 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.7.10/kotlin-stdlib-common-1.7.10.pom, took 185 ms (1,16 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.6.0/kotlin-stdlib-jdk7-1.6.0.pom, took 33 ms (1,39 kB)
Download https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.6.0/activity-1.6.0.aar, took 176 ms (111,23 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.6.0/kotlin-stdlib-jdk7-1.6.0.jar, took 110 ms (22,36 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.7.10/kotlin-stdlib-common-1.7.10.jar, took 170 ms (198,94 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.7.10/kotlin-stdlib-1.7.10.jar, took 1 s 533 ms (1,52 MB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat-resources/1.6.1/appcompat-resources-1.6.1.aar, took 45 ms (66,33 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.6.1/appcompat-1.6.1.aar, took 403 ms (1,14 MB)
Download https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.4.0/lifecycle-common-2.4.0.pom, took 105 ms (1,98 kB)
Download https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.4.0/lifecycle-common-2.4.0.module, took 32 ms (3,33 kB)
Download https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.6.0/activity-1.6.0-sources.jar, took 68 ms (43,79 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.7.10/kotlin-stdlib-1.7.10-sources.jar, took 115 ms (220,62 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.7.10/kotlin-stdlib-common-1.7.10-sources.jar, took 89 ms (299,8 kB)
Download https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.6.0/kotlin-stdlib-jdk7-1.6.0-sources.jar, took 30 ms (12,13 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat/1.6.1/appcompat-1.6.1-sources.jar, took 179 ms (502,83 kB)
Download https://dl.google.com/dl/android/maven2/androidx/appcompat/appcompat-resources/1.6.1/appcompat-resources-1.6.1-sources.jar, took 33 ms (40,96 kB)
```

</details>

What do you think @m4gr3d ?



When we changed our app at our company 6 years ago, the APK size was increased from 1.5 MB to 3.2 MB _(minifyEnabled = true / shrinkResources = true etc.)_ 


I personally find the old dialogs better, as you can see directly where the OK button is 😃 
I would program a dialog like this with Godot.

### R.style.Theme_AppCompat_Dialog_Alert
![image](https://github.com/godotengine/godot/assets/41921395/01ae3457-b7dc-4cc9-9941-2222cf7837f5)

### R.style.Theme_AppCompat_Light_Dialog_Alert
![image](https://github.com/godotengine/godot/assets/41921395/45b138fa-40d4-4c54-b79e-6193e2e0f982)

**Comment by m4gr3d** [comment]
> Material 3 - AlertDialog is [ExperimentalMaterial3Api](https://developer.android.com/reference/kotlin/androidx/compose/material3/ExperimentalMaterial3Api)
> 
> These changes are necessary as a minimum (without Material / Android 7+ Style?): [master...Alex2782:godot:androidx.alert](https://github.com/godotengine/godot/compare/master...Alex2782:godot:androidx.alert)
> 
> Android Studio, new downloads / libs / dependencies
> What do you think @m4gr3d ?
> 

@Alex2782 It makes sense to update to the new style; feel free to send a PR with your changes!

> When we changed our app at our company 6 years ago, the APK size was increased from 1.5 MB to 3.2 MB _(minifyEnabled = true / shrinkResources = true etc.)_
> 

I'm not too concerned with binary size at the moment as it's still small enough that we haven't had the need to enable resource shrinking or `minify` yet. If we get to that point, then enabling those features should give us the headroom we need.

**Comment by akien-mga** [comment]
If we get similar results though, adding 1.7 MB binary size just to get a slightly nicer looking `OS.alert()` dialog seems overkill to me.

A lot of users really care about keeping their APKs as lean as possible, and most don't ever use `OS.alert()` unless the engine itself is crashing and using it, and then it doesn't matter much if it's not pretty.

**Comment by Alex2782** [comment]
I have checked the debug/dev apks more closely. `+ 1.6 MB`

<details><summary>Some details</summary>

The download size of our app via PlayStore was only 300 KB more than usual (6 years ago). 
**Today:** _"From August 2021, new apps are required to publish with the Android App Bundle on Google Play"_ (maybe -100 KB)

![image](https://github.com/godotengine/godot/assets/41921395/1549a301-3960-4d05-afce-5ca5cd61afc1)


unpacked, memory usage on the phone  `+ 3.4 MB`

![Bildschirmfoto 2023-11-21 um 21 36 57](https://github.com/godotengine/godot/assets/41921395/1ba0d6fd-305a-4ca3-abf3-eb62c6ebf0f7)
</details>

We don't even use Kotlin, because the Apk becomes 1 MB larger. Some apps are not distributed via PlayStore because the Google services can cause a lot of traffic. Outside major cities, the mobile internet connection is often slow and unstable (in Germany), and our customers (taxi companies) pay up to 1000 euros a month for 100 x bundle rates for the vehicles. Every MB counts to reduce costs.

**Comment by BQKdev** [comment]
I forgot to close it😅
