### ISSUE TITLE
GPUParticles3D Spawn Incorrectly When Changing Scenes

### ISSUE THREAD

**Issue by blast-harbour** [godotengine/godot#85119]
### Godot version

4.2 RC 1

### System information

Godot v4.2.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.21018.5001) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

when using get_tree().change_scene_to_file(), all GPUParticles3D in the scene initially spawn at 0,0,0

this behavior only occurs when changing scenes, and not when initially booting the project from the scene.

https://github.com/godotengine/godot/assets/60982612/98709943-744e-4846-9ffc-0db3b09d9d91

In this video clip, the camera is near the 0,0,0 origin and all of the particles cover the screen upon reloading the scene

### Steps to reproduce

1. Create GPUParticles3D and have them emitting somewhere not at position 0,0,0
2. Reload the scene using get_tree().change_to_file()

### Minimal reproduction project

[4.2 rc1 particle issue.zip](https://github.com/godotengine/godot/files/13405847/4.2.rc1.particle.issue.zip)

**Comment by Calinou** [comment]
I bisected the regression to 4354cd8d41e044fba2dc5b63324388e01a786049. cc @RandomShaper

**Comment by YuriSizov** [comment]
I think the culprit is in the particle system somewhere, though, as it doesn't gracefully or timely finish the emission when the old scene is removed.

**Comment by akien-mga** [comment]
The same issue happens with GPUParticles2D. The whole transform is temporarily zero'ed, so things like scale and rotation also reset.

The problem doesn't happen with CPUParticles2D/3D.

**Comment by akien-mga** [comment]
> I bisected the regression to [4354cd8](https://github.com/godotengine/godot/commit/4354cd8d41e044fba2dc5b63324388e01a786049) (#78988). cc @RandomShaper

This works it around:
```diff
diff --git a/scene/main/scene_tree.cpp b/scene/main/scene_tree.cpp
index d3347bc304..cc15b8a169 100644
--- a/scene/main/scene_tree.cpp
+++ b/scene/main/scene_tree.cpp
@@ -552,8 +552,10 @@ bool SceneTree::process(double p_time) {
 
 	if (unlikely(pending_new_scene)) {
 		_flush_scene_change();
+		flush_transform_notifications();
 	}
 
+
 	return _quit;
 }
 
```

But I don't know if that's the right approach or what drawbacks it can have.

**Comment by RandomShaper** [comment]
I can't really pinpoint the pure underlying cause. It's interesting that only these node types exhibit such behavior, which is in line with @YuriSizov's intuition. All in all, @akien-mga's proposed fix makes sense, considering the point at which the scene switch happens is not truly between iterations (which would have been my ideal implementation), but near the end of one. That can explain why some callbacks/late-stuff are missed. I'd go @akien-mga's way until this can be reworked in the future with maybe a new `MainLoop` method that runs between iterations, when everything's flushed.
