### ISSUE TITLE
Sprite added to scene root instead of selected node.

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot#85113]
### Godot version

4.2 rc1

### System information

ubuntu 22.04

### Issue description

Dragging image from FileSystem dock to 2d viewport adds Sprite to scene, but it became a child of root node instead of selected node. 

### Steps to reproduce

- Select any child node of 2d Scene root
- Add Sprite to scene by dragging it from FileSystem, Sprite will appear in tree as child of root

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
You need to hold down ctrl/CMD, see the instructions on screen when dragging
