### ISSUE TITLE
Text renders incorrectly in 4.1

### ISSUE THREAD

**Issue by heroplay004** [godotengine/godot#85125]
### Godot version

4.1.3

### System information

windows 10 - godot 4.1.3 стабильная

### Issue description

Сломался текст, после того как поработал над проектом сохранил его и при следующим запуске текст стал таким, но пробовал позднее версию 3.5.3 там все работает нормально
![2023-11-20_12-18-00](https://github.com/godotengine/godot/assets/139123983/37e27dd0-0bcc-43b8-b488-4d75814d81bb)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by Zireael07** [comment]
Please use English when reporting bugs.

That said, this looks suspiciously like a duplicate of already reported issue (I forgot what the source of the problem was, buggy gfx drivers?)

Try 4.1.2 beta to see if it's fixed there

**Comment by heroplay004** [comment]
Godot_v4.1.2-stable_win64. 
in this version, this error is still present in the Godot_v3.5.3-stable version, it is no longer there
