### ISSUE TITLE
[Suggestion] attach more than one shader to the same node

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8513]
this can be extremely useful for some situations like : 
Making a 3D anaglyph effect (for 3D glasses) requires 2 shaders on the same node... the 1st is for the right eye and the 2nd is for the left eye ... beside the node-specific shader of course
and many other things you can imagine
I know it may require some hard work but (in my opinion) it deserves
what do you think?
Inspired from multiscript module

**Comment by bojidar-bg** [comment]
Related/duplicate of #8507 and #146?

**Comment by nunodonato** [comment]
can you be a bit more explicit on why would you ever want to use 2 shaders on the same material? For 3D anaglyphs I think you actually have 2 cameras to render the different perspectives of both eyes, its not just a shader effect.

**Comment by Ahmed0425** [comment]
> Related/duplicate of #8507 and #146?

Didn't notice that ... closed
