### ISSUE TITLE
XR Scene within the Meta Quest3 turns dark and unresponsive on M1 Pro

### ISSUE THREAD

**Issue by TAMustafa** [godotengine/godot#85132]
### Godot version

4.2-rc1

### System information

Apple M1 Pro - MacOS: 14.1.1 (23B81) - Memory: 16GB - Total Number of Cores: 8 (6 performance and 2 efficiency)

### Issue description

Building a basic XR scene using 4.2 rc-1 to my headset (Quest3) caused the following issues in sequence:

1. "Please confirm..." window pop up and not able to press the "Restart & Upgrade" button. So unable to deploy the build to the Quest.
<img width="634" alt="Screenshot_2023-11-20_at_08 20 21" src="https://github.com/godotengine/godot/assets/18684763/09f13df4-5e45-4ee5-82f0-b8f0b412a724">

2. After chatting with Bastiaan in discord I have run the `vignette.tscn` scene from the XR Tools Add-on Folder which triggered the same window. After closing and reopening Godot I was able to press the Restart & Upgrade button.

3. Next I deployed the scene to my Quest3 without any error messages in the console. For a brief moment I saw my scene but then the environment slowly went darker and darker until everything went black. No controls worked, so I had to restart the Quest to get out of the darkness.

### Steps to reproduce

No Code written since this was for a basic XR scene using XR Tools.

1. Opened new project in Compatibility render mode.
2. Enabled OpenXR and Shader
3. Installed XR Tools 4.2 and Android OpenXR Loaders
4. Installed and configured Android Build Template

### Minimal reproduction project

[Archive.zip](https://github.com/godotengine/godot/files/13413107/Archive.zip)

**Comment by YuriSizov** [comment]
The first half is tracked in https://github.com/godotengine/godot/issues/84171 and should be fixed by https://github.com/godotengine/godot/pull/85136

**Comment by TAMustafa** [comment]
Foobar404 in the XR discord channel kindly advised that there is a new godot xr vendor that should be used instead of the regular plugin. I followed the instruction and replaced the old plugin for the vendor plugin and it workks now!

So this ticket can be probably closed since the solution is to use the new XR vendor plugin.
