### ISSUE TITLE
i cannot get the fog in version 4 to look the same, what am i doing wrong?

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#85148]
### Godot version

4.13

### System information

Windows 10

### Issue description

Since moving to Godot 4 the only thing i have found missing is the fog.... the new fog if set strong enough to obscure the draw distance (say 4km draw)... it will look so washed out in the foreground like everything is foggy

the old fog could be used to obscure the draw distance, it was not "realistic"... am i the only one experiencing this frustration that my graphics looked better in Godot 3?

i do not know the technical reason for this but i hope to find it

i do not have any working Godot 3 code anymore however here are some screenshots i dug out, i think this old one showed how the unrealistic fog both has a nice bright look in foreground, has strong fog here to obscure popup:
https://www.facebook.com/photo/?fbid=10158498900213359&set=pcb.10158498900918359

this is a more recent one, sorry they are different scenes but this large scene would have liked the old fog... it has the new fog and i can get it to look nothing but dull:
https://www.facebook.com/photo/?fbid=10159496570933359&set=pcb.10159496572243359

i personally think this is a major overight that the new fog is "realistic"... is it because it's not expotential? which would be more physically accurate but would not work in the way we use fog in 3D video games (partly for a fog look, but also mainly to obscure the draw distance, if you ever see the draw distance, you know it's an amature product)

i cannot find the previous github complaints about this... surely it is a "BUG" not feature, the reason is because we were promised everything would be backwards compatible with Godot 3 and we would loose nothing.... this is a pretty massive loss to all scenes in open areas

Godot 3 fog, i cannot reproduce this anymore.... Source engine could, probabally GZDoom could, they all use the old fog
![273009841_10158498900198359_7432796729019583621_n](https://github.com/godotengine/godot/assets/5873361/e91fcaf3-30a3-4857-98fa-1041df1cdd8e)

Godot 4, not the same scene but i cannot find any examples of where i even got it close
![360094148_10159496570918359_1051173827848568356_n](https://github.com/godotengine/godot/assets/5873361/a1f78f48-55dd-4419-ab85-aae9864a15d4)

### Steps to reproduce

create scenes with fog... it is simple impossible to create fog like screenshot 1 without washing out the scene and causing the immediate foreground to become all blue

### Minimal reproduction project

na

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by bitsawer** [comment]
There are proposals for adding some Godot 3-like fog improvements, see https://github.com/godotengine/godot-proposals/issues/4619 and https://github.com/godotengine/godot-proposals/issues/3429. As AThousandShips already noted, this issue can probably be closed and discussed further in proposals if needed.

There is also an existing PR for implementing some of these features: https://github.com/godotengine/godot/pull/84792

**Comment by RichardEllicott** [comment]
i very much doubt anyone has stared at the fog settings and/or played with them more than me i wasn't gonna get an answer from a support channel was i.... it's to do with how the fog has been implemented  as realistic without regard for normal practice of obscuring draw distance

thanks for linking me to the PR anyway i'll go there
