### ISSUE TITLE
Saving inactive scene with RESET animation changing Control nodes will break their layout

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#85149]
### Godot version

4.2 rc1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Title.

https://github.com/godotengine/godot/assets/2223172/c7c65166-2520-4605-a43a-153484380943

### Steps to reproduce

1. Have AnimationPlayer with RESET animation
2. Animate Control node's position
3. Go to another scene
4. Save the first scene without switching to it (e.g. using Save All Scenes)

### Minimal reproduction project

[MRP_label_resize.zip](https://github.com/godotengine/godot/files/13418676/MRP_label_resize.zip)
Open LabelFieldValue.tscn, go to another scene and run project or use Save All Scenes.

**Comment by akien-mga** [comment]
Confirmed, seems reproducible in 4.1.3-stable too.

**Comment by YuriSizov** [comment]
A duplicate of https://github.com/godotengine/godot/issues/74047?

**Comment by KoBeWi** [comment]
Yes 🙃
