### ISSUE TITLE
Create and distribute a press kit on the Godot website

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#8514]
[It was suggested by a Q&A user](https://godotengine.org/qa/1702/can-anyone-give-ideas-on-how-increase-the-popularity-of-godot?show=14384#a14384) that there should be a downloadable press kit available somewhere on the Godot website. It could then be linked to in the site footer.

## What it could contain

- Logos (in color and monochrome versions, PNG and SVG formats at least)
  - Logo + Text (one with text besides the icon, one with text below the icon?)
  - Icon
- Logo usage guidelines

## Examples and inspiration

- [Blender](https://www.blender.org/about/logo/)
- [Unity](https://unity3d.com/public-relations/brand)

**Comment by fire** [comment]
https://github.com/godotengine/godot/blob/master/logo.svg

Coloured logo

https://github.com/godotengine/godot/blob/master/icon.svg

Coloured Icon

**Comment by fire** [comment]
Needs a black and white version. A) on white background B) on black background

**Comment by Kesnek** [comment]
**Done:**
- Icon, Logo, Logotype, Logotype subtitled
- All in color, black, white monochrome variants
- Exported as PNG in different resolutions
- Applied lossless optimization to PNGs
- Added license from website

**Download:**
[presskit.zip](https://github.com/godotengine/godot/files/1353202/presskit.zip)

**TODO:**
- Logo usage guidelines
- Engine screenshots
- Game/showcase screenshots
- Info text
- Add to website

**Comment by diowonderland** [comment]
**Done:**
- Icon, Logo, Logotype, Logotype subtitled
- All in color, black, white monochrome variants
- Exported as PNG in different resolutions
- Applied lossless optimization to PNGs
- Added license from website

**Download:**
[presskit.zip](https://github.com/godotengine/godot/files/1353202/presskit.zip)

**TODO:**
- Logo usage guidelines
- Engine screenshots
- Game/showcase screenshots
- Info text
- Add to website

**Comment by mhilbrunner** [comment]
Closing, moved to https://github.com/godotengine/godot-website/issues/44

**Comment by programaths** [comment]
I know it's not something to do on GitHub, but: THANK YOU VERY MUCH!
