### ISSUE TITLE
Select folder will delete the previous name established at the time of creating a project

### ISSUE THREAD

**Issue by alextkd2003** [godotengine/godot#85157]
### Godot version

4.2.rc1.official

### System information

Windows 10 Godot 4.2.rc1.official not Mono

### Issue description

When I want to create a new project I write the name of the same, then I select a folder. When I select the folder, the name previously established changes to "Godot"

### Steps to reproduce

1- Open Godot
2- Click on "New" to create a new project
3- Type a name
4- Select a folder location using Browse and Select Current Folder
5- Now the project Name is "Godot"

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
On my machine it becomes the name of the chosen folder.
