### ISSUE TITLE
GDExtension iOS export minimum OS version is hard coded 10.0

### ISSUE THREAD

**Issue by abcjjy** [godotengine/godot#85158]
### Godot version

Godot v4.1.1.stable

### System information

macOS 13.6.1 - Vulkan (Compatibility) - AMD Radeon Pro 560X OpenGL Engine - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

GDExtension code could use new c apis available in newer iOS. This hard coded minimum os version in Info.plist will cause rejection when submitting binary to App Store.

### Steps to reproduce

Create a gdextension using fmemopen(), which is a new api since iOS 11. And submit the app to App Store, the submission will fail with error:

<img width="653" alt="图片" src="https://github.com/godotengine/godot/assets/1791493/92e15756-10ae-4de4-8bf0-e2f079954c49">

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
4.1.1 is outdated, 4.1.3 and 4.2 defaults to `12.0`, for GDExtension you can use `ios_min_version=VERSION` command line argument. Also, you can use [`@available`](https://developer.apple.com/documentation/swift/marking-api-availability-in-objective-c) around your code. But it's probably enough to change min. version in the exported project (will be configurable on export in 4.3 - https://github.com/godotengine/godot/pull/84162).

**Comment by akien-mga** [comment]
Closing as per above comment, this seems resolved in 4.1.3 and 4.2.
