### ISSUE TITLE
When I use switch pro or PS5, I find that the vibration function is not working

### ISSUE THREAD

**Issue by kc991229** [godotengine/godot#85166]
### Godot version

3.5

### System information

windows10

### Issue description

When I use switch pro or PS5, I find that the vibration function is not working，please find an answer

### Steps to reproduce

use switch pro or ps5

### Minimal reproduction project

z

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot/issues/14634

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/14634.

**Comment by Yurinka** [comment]
The issue continues happening in v4.2.2.stable.official when running it (reproduced it in the editor, using Windows 10):

- Xbox compatible gamepads rumble properly
- DualShock4 (connected via USB) doesn't rumble
- DualSense (connected via USB) doesn't rumble
- Switch Pro controller doesn't rumble

**Comment by Calinou** [comment]
@Yurinka Please continue the discussion in https://github.com/godotengine/godot/issues/89136.
