### ISSUE TITLE
Bug: Using variables with set_layer_mask_bit in PhysicsBody2D

### ISSUE THREAD

**Issue by Diaspater** [godotengine/godot#8517]
**Operating system or device - Godot version:**
Windows 10
Godot 2.1.2-stable win64

**Issue description:**
When using a variable passed by another function to change a single mask bit it changes the layer equal to twice the variable value instead.

**Steps to reproduce:**
```
func set_physical_layer( layer)
    set_layer_mask(0)
    set_layer_mask_bit(layer, true)
    set_layer_mask_bit(2, false)
    var m = get_layer_mask()
```
I realize that this code does nothing practical, it is just an example to show the problem. If you were to call this function using the using an integer of 2, you should expect m to return 0. However, when a variable is used to set the mask bit instead of entering a specific value. it actually changes the bit equal to twice the integer value. For example if layer = 2 then set_layer_mask_bit(layer, true) actually sets bit 4 of the mask to be true instead of bit 2, layer = 1 sets bit 2 and so on with the pattern being twice the passed value. I don't think this is intended to work this way as the documentation indicates that an integer is the expected type of the function set_layer_mask_bit and even if it is supposed to change twice the value for some internal reason, then passing a hard value like 2 should change the same bit as layer = 2.

**Comment by bojidar-bg** [comment]
Can you print `typeof(layer) == TYPE_INT` and confirm it is True?

**Comment by akien-mga** [comment]
Can't reproduce here:
```
func _ready():
	# clear layer_mask to be sure
	set_layer_mask(0)
	print(get_layer_mask_bit(2))  # False
	print(get_layer_mask())  # 0

	set_layer_mask_bit(2, true)
	print(get_layer_mask_bit(2))  # True
	print(get_layer_mask())  # 4

	set_layer_mask_bit(2, false)
	print(get_layer_mask_bit(2))  # False
	print(get_layer_mask())  # 0
```

**Comment by akien-mga** [comment]
As @nunodonato pointed out on IRC, I guess you might be misunderstanding what a bitmask is. It's a way to encode which layers are enabled using a binary number. If you set the bit 2, that means that your binary number (if it was initially 0) becomes 100, i.e. 4 (1*2^2 + 0*2^1 + 0*2^0). If you set the bit 3, it will be 8. If you set the bits 2 and 3, it will be 12, etc.

**Comment by Diaspater** [comment]
@akien-mga
Thank you understanding what I was trying to describe and demonstrating that the issue isn't occurring  in 2.1.3 stable. I will update my version.
