### ISSUE TITLE
Trying to display motion vectors in Godot 4.2.rc1 spits out an error every frame

### ISSUE THREAD

**Issue by VDFOREVER** [godotengine/godot#85176]
### Godot version

Godot 4.2.rc1

### System information

Godot v4.2.rc1.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 570 Series (RADV POLARIS10) () - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

This is the error:
```
 Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
  Texture (binding: 0, index 0) needs the TEXTURE_USAGE_SAMPLING_BIT usage flag set in order to be used as uniform.
  ./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129 - Condition "rid.is_null()" is true. Returning: rid
  drivers/vulkan/rendering_device_vulkan.cpp:7336 - Parameter "uniform_set" is null.
  Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
```

### Steps to reproduce

Enabled "MSAA 3D"
Go to "Display Advanced" and select "Motion Vectors"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/84647.
