### ISSUE TITLE
.Net can not load scenes properly in plugin 

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#85179]
### Godot version

4.2 rc1

### System information

Windows10 

### Issue description

I can not get properly scenes by using GD.Load  function in plugin. 
The error:
 
![image](https://github.com/godotengine/godot/assets/37371850/af380fa3-08ed-4b1d-88e0-e9e59d82bab7)
It seems that the script is not be set properly to the scene after loading.
The script is totally right and if you run in the game, the scene will be loaded properly.  
 

### Steps to reproduce

1. open the project I uploaded
2. build the program 
3. activate the plugin, you will get errors in output 

You can run the "Scene1.tscn" scene which has same codes compared to plugin, and it is totally ok. 

### Minimal reproduction project

[TestPlugin.zip](https://github.com/godotengine/godot/files/13428271/TestPlugin.zip)

**Comment by YuriSizov** [comment]
@SmallKi Did you mean to close it?

**Comment by SmallKi** [comment]
Yes, I find the problem....,   I need to give [Tool] to the scene I want to load in plugin code
