### ISSUE TITLE
TileSet inconsistent UVs

### ISSUE THREAD

**Issue by awardell** [godotengine/godot#85182]
### Godot version

v4.2.rc.custom_build [80de898d7]

### System information

Godot v4.2.rc (80de898d7) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen Threadripper 1950X 16-Core Processor (32 Threads)

### Issue description

TileSets exhibit inconsistent UVs depending on if Margins.x and/or Separation.x are non-zero. This inconsistency is not exhibited with Margins.y or Separation.y.

This issue makes writing consistent shaders for Tilesets very difficult.

### Basic steps:
- Create a shader which renders UVs and apply a material with that shader to a TileSet.
- Modify Margins.x or Separation.x so that they are non-zero, and observe that the UVs change drastically.
- Modify Margins.y or Separation.y so that they are non-zero, and observe no drastic change in UVs.

### Steps with included minimal reproduction project:
- Open main.tscn and observe the two TileMaps with different TileSets.
- tileset_margins_separation has Margin and Separation values set to line up with colors.png
- tileset_no-margins_no-separation does not.
- Both TileSets are using the same ShaderMaterial, material.tres
- material.tres starts with shader_384x256, which assumes a 384x256 pixel resolution.
- Observe that both TileSets exhibit correct vertical UVs, but the one with no Separation or Margins exhibits incorrect horizontal UVs.
- Change the shader on material.tres to shader_512x272, which uses the resolution of colors.png
- Observe that both TileSets now exhibit incorrect vertical UVs, but the right one exhibits correct horizontal UVs.
- ~~Change the shader on material.tres to shader_pixel_size, which uses 1./TEXTURE_PIXEL_SIZE to calculate resolution.~~
- ~~Observe that both TileSets have incorrect UVs in both directions but are consistent with each other.~~

### Minimal reproduction project

[ReproProject.zip](https://github.com/godotengine/godot/files/13429381/ReproProject.zip)

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/85044

**Comment by awardell** [comment]
@AThousandShips This is not a duplicate. The issue of inconsistency persists regardless of Use Texture Padding and will still exhibit if turned off. Please re-open. TEXTURE_PIXEL_SIZE is not the focus of this bug, but is included to highlight the UV issues. I will remove mention of it in the description and steps if that is muddling things.

**Comment by AThousandShips** [comment]
The other bug report also talks about the UV, so seems the same, but will reopen

CC @kleonc

**Comment by awardell** [comment]
Correcting what I said: The issue does not exist if Use Texture Padding is turned off. My apologies. When I turned it off, UVs were simply still warped by the Margins and Separation amounts. This should be expected.

However, when Texture Padding is turned on, the behavior between modifying the X values between zero and non-zero is still inconsistent with the behavior of modifying the Y values. If these particular inconsistencies are simply necessary, then please close this issue. I believe however that ideally either:

A. The change between zero and non-zero should not drastically modify UV.x or
B. Changes in y should have the same characteristic.

**Comment by AThousandShips** [comment]
Then I'd say it *is* a duplicate, what do you mean warped?

**Comment by awardell** [comment]
Both have padding:

![image](https://github.com/godotengine/godot/assets/1361278/79c65e71-db4c-4e35-98f5-2a50fe1fc013)

![image](https://github.com/godotengine/godot/assets/1361278/83b430bd-1c9e-4c56-90b3-188e2de7c0cb)

Alright, did more testing. Issue appeared to come about not due to X vs Y but due to the specific dimensions of X being a power of 2 (i.e. the image was 512 width). I was not aware that increasing the margin or separation by an amount that would cause the total dimension to be larger than the next power of 2 would cause the total dimension to double (or however it resizes). Still not a duplicate issue, just an incorrect one. Thanks for your time @AThousandShips, I'll close this now.

**Comment by kleonc** [comment]
@awardell To clarify it has nothing to do with power of 2. Your original texture is 512x272. So for the texture region size set to 128x128:
- For no margins/separation it deduces that your texture contains 4x2 tiles (4x2 * 128x128 = 512x256), hence the generated padded texture is 520x260 = 4x2 * (128x128 + 2x2).
![Godot_v4 2-rc1_win64_l2myZ2ike9](https://github.com/godotengine/godot/assets/9283098/359b538a-14c5-49df-8c0c-e2423000c24c)

- For margin 4x4 and separation 8x8 it deduces that your texture contains 3x2 tiles (3x2 * 128x128 + 4x4 * 2 + 8x8 * 2x1= 408x272), hence the generated padded texture is 390x260 = 3x2 * (128x128 + 2x2).
![Godot_v4 2-rc1_win64_xa6ULjH16f](https://github.com/godotengine/godot/assets/9283098/cf65965f-7215-4379-b352-d551c56b28aa)
