### ISSUE TITLE
Added patterns to tilesets do not get reflected in function calls.

### ISSUE THREAD

**Issue by ultramarinebicycle** [godotengine/godot#85199]
### Godot version

4.1

### System information

Windows 11

### Issue description

I created a tilemap in the scene. Calling $TileMap.tile_set.get_patterns_count() returns 0 even after adding a pattern that is visible in the TileSet panel.

It's possible that this is how it is intended to function but I couldn't find any relevant documentation.

### Steps to reproduce

- Add a TileMap node to your scene.
- In the TileSet field, create New TileSet.
- Drag and drop a tileset atlas.
- Create a pattern in the viewport. Select it, copy it, and paste it into the patterns tab of the Tilemap panel at the bottom.
- Create a script referencing the tilemap and try to reference the pattern size or the pattern index.

### Minimal reproduction project

Not required.

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed), or specify that you are using 4.1.3 if that is the case

**Comment by ultramarinebicycle** [comment]
I just tested with 4.1.3, the bug is still there.

**Comment by kleonc** [comment]
> ### Steps to reproduce
> 
>   * Add a TileMap node to your scene.
>   * In the TileSet field, create New TileSet.
>   * Drag and drop a tileset atlas.
>   * Create a pattern in the viewport. Select it, copy it, and paste it into the patterns tab of the Tilemap panel at the bottom.
>   * Create a script referencing the tilemap and try to reference the pattern size or the pattern index.
>
> ### Minimal reproduction project
> 
> Not required.

Can't reproduce, v4.1.3.stable.official [f06b6836a]. The reproduction steps are not precise though and no MRP is provided.

![Godot_v4 1 3-stable_win64_hA3qfzNx5Y](https://github.com/godotengine/godot/assets/9283098/32b2887e-32ff-4ebe-b0c8-3ccf8438916c)

```gdscript
extends Node2D

@export var tile_map: TileMap

func _ready() -> void:
	print(tile_map.tile_set.get_patterns_count()) # Prints 1
```

**Comment by ultramarinebicycle** [comment]
Not sure what happened here. I was saving the scene as .scn and loading it during runtime. I deleted the scene and recreated everything and now it works.
