### ISSUE TITLE
Looped animation uses value from the beginning when it shouldn't

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#85218]
happens from code too... if seek to end, mod turns it to beginning

Issue: https://github.com/godotengine/godot/issues/37343

Fix: https://github.com/godotengine/godot/pull/85186

	extends Node2D

	@onready var _sprite = $Sprite2D
	@onready var _animation = $Sprite2D/AnimationPlayer

	func _ready():
		_animation.seek(0.9, true)
		_animation.pause()

**Comment by AThousandShips** [comment]
This has already been solved and the proposed fix rejected, please do not open issues to "compete" with other solutions

**Comment by rakkarage** [comment]
This has not been solved. This is the new issue.

**Comment by rakkarage** [comment]
"happens from code too... if seek to end, mod turns it to beginning"

**Comment by AThousandShips** [comment]
Please open a new issue with the details filled out

**Comment by rakkarage** [comment]
they are filled out.. it is the same issue

**Comment by AThousandShips** [comment]
Then if the original issue isn't solved it should be reopened, otherwise please open a new issue describing the details not fixed by the pr that solved the other issue

**Comment by rakkarage** [comment]
"please do not open issues to "compete" with other solutions"

I opened a pull for this four year old issue yesterday... and coincidentally gets "fixed" same day.

**Comment by AThousandShips** [comment]
No it was closed superseding yours, so linking this to that PR when it was superseded does seem like that, when all the issue contains is a link to said solved issue, and a closed PR, my bad 🙂
