### ISSUE TITLE
Project crashes on play, producing vulkan errors, caused by settings in world environment. Project sometimes unrecoverable.

### ISSUE THREAD

**Issue by aramanamu** [godotengine/godot#85212]
### Godot version

v4.1.3.stable.official.f06b6836a

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3734) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

***PLEASE NOTE: This issue seems to be fixed in Godot v4.2-rc1, however due to the potential to break projects, I (and others in the community) feel I should submit this report anyway, if not useful directly, then at the very least to have the issue tracked.***

1. the project debug window will hang, while in the console these errors are spammed:

E 0:00:03:0309   swap_buffers: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
  <C++ Error>    Condition "err" is true. Returning: ERR_CANT_CREATE
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:2360 @ swap_buffers()

E 0:00:03:0365   prepare_buffers: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
  <C++ Error>    Condition "err != VK_SUCCESS" is true. Breaking.
  <C++ Source>   drivers/vulkan/vulkan_context.cpp:2283 @ prepare_buffers()

Must hit stop, or close the window.

2. After further testing I found this much more serious problem with other specific settings:
same as above will happen, without the errors as it will also hang the editor - nothing drawn inside the window just the navy background.
After then closing the app and reopening the project, it sometimes will not run, just hangs.
This is sometimes recoverable by deleting the .godot folder, **but not always**.

### Steps to reproduce

Create new 3D scene >> add WorldEnvironment and Camera3D nodes.
Set up the environment settings as in the image:
(Doubtful that the colors or specific settings are relevant)
![Environment_Bug_Settings](https://github.com/godotengine/godot/assets/41204877/16a2b68c-e4a8-4ef8-8a66-917d2eea3cb9)

Click the play button and you should see the first issue as above. Disabling fog allows it to run without errors.

The same project can test the second error: Simply disable glow while fog is enabled, click play and it should hang without errors, and hang the editor after closing the window, etc.

These errors only seem to happen if the background mode is set to clear color. I tested custom and sky >> procedural and did not experience these problems.

### Minimal reproduction project

[Environment_Bug_Test.zip](https://github.com/godotengine/godot/files/13438829/Environment_Bug_Test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929, as this is due to the same cause.

> After then closing the app and reopening the project, it sometimes will not run, just hangs.
This is sometimes recoverable by deleting the .godot folder, but not always.

If this hang is due to specific project settings, edit `project.godot` to remove the offending settings.

If this hang is due to specific editor settings, remove `editor_settings-4.tres` from the [editor configuration folder](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html) while the editor is closed to reinitialize settings to their default values.

**Comment by aramanamu** [comment]
@Calinou Thank you, luckily I did not encounter the "unrecoverable" situation in any real project. Still, it's good to know that I can edit those settings if I encounter any similar issues.
