### ISSUE TITLE
html5 global_position not consistent with desktop behavior

### ISSUE THREAD

**Issue by sashton** [godotengine/godot#85211]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.2799) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

Setting either `global_position.x` or `global_position.y` of a new node prior to adding that node to the scene tree via `add_child` results in inconsistent behavior between html5 and desktop apps. 

The HTML5 behavior appears to be:
- when `global_position.x` is set prior to `add_child`, the `global_position.y` value is lost (defaults to 0)
- when `global_position.y` is set prior to `add_child`, the `global_position.x` value is lost (defaults to 0)
- when `add_child` is called before modifying `global_position`, neither value is lost

### Run as desktop app
Using the included project, run as desktop application.
Observe that the rectangle is drawn on the screen at (200,200) 
and the printed output is the following:
```
1: (0, 0)
2: (200, 200)
3: (200, 200)
```

### Run as HTML5 app
Using the included project, export the project as HTML5 using the default HTML5 template.
Run via a web browser (I tested using: https://gotm.io/upload)
Observe that the rectangle is drawn on the screen at (0,200)
and the browser console printed output is the following:
```
[GODOT] 1: (0, 0)
[GODOT] 2: (0, 0)
[GODOT] 3: (0, 200)
```

### Expected
The behavior of the desktop app matches my expectations.
The behavior of the html5 app appears incorrect.

I observe the same results in both Chrome and Firebox browsers.

### Minimal reproduction project

[global_position_bug.zip](https://github.com/godotengine/godot/files/13438664/global_position_bug.zip)

**Comment by kleonc** [comment]
Can't reproduce, tested v4.1.3.stable.official [f06b6836a] both debug/release in Firefox/Chrome. Tested via Run in Browser menu option:
![Godot_v4 1 3-stable_win64_ncvw6hP0uG](https://github.com/godotengine/godot/assets/9283098/d7a0c302-3b9a-426b-97db-f7292bf81488)
and by [manually using `serve.py` from the docs](https://docs.godotengine.org/en/4.1/tutorials/export/exporting_for_web.html#serving-the-files).

---

> ### Run as HTML5 app
> 
> Using the included project, export the project as HTML5 using the default HTML5 template. Run via a web browser (I tested using: https://gotm.io/upload)

In v4.1.1.stable.official [bd6af8e0e] and earlier versions the behavior is the bugged one, even on desktop. Which suggests that `gotm.io` might be using some older version for running? :thinking:

@sashton So please test v4.1.3.stable.official [f06b6836a] not using `gotm.io`.

**Comment by sashton** [comment]
@kleonc Thanks for showing the option to Run in Browser from the editor. I was unaware of that option (which is why I mentioned gotm). 
You are correct, this isn't an issue when running via Godot runner. Sorry for the mis-report.
