### ISSUE TITLE
Multiple GDExtensions can't be registered in iOS export

### ISSUE THREAD

**Issue by abcjjy** [godotengine/godot#85210]
### Godot version

Godot v4.2.rc1

### System information

macOS 13.6.1 - GLES3 (Compatibility) - ANGLE (AMD, ANGLE Metal Renderer: AMD Radeon Pro 560X, 版本13.6.1（版号22G313）) - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

v4.2rc1 can load a single GDExtension in iOS export successfully. But when two GDExtensions are added, one of them will be registered twice and the other won't get registered.

GDExtensions are statically linked. Xcode 15.0.1 is used. Tested on iOS 12.5.3 iPod touch 6.

GDExtensions work fine in macos editor.

### Steps to reproduce

Export the attached sample project to iOS and run it on an iOS device.

### Minimal reproduction project

[gdbug2.4.zip](https://github.com/godotengine/godot/files/13438598/gdbug2.4.zip)

There are two GDExtension libraries in this project: ext1 and ext2. They will print logs when registering classes.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by abcjjy** [comment]
I tried the fix in [bruvzg/static_multi](bruvzg:static_multiple_init) with my sample project. Both extensions are registered twice. Error messages are logged.

```
USER ERROR: Attempt to register extension class 'Foo', which appears to be already registered.
   at: _register_extension_class_internal (core/extension/gdextension.cpp:386)
USER ERROR: Attempt to register extension class 'Bar', which appears to be already registered.
   at: _register_extension_class_internal (core/extension/gdextension.cpp:386)
```
