### ISSUE TITLE
[4.1.3] C# async Task - no print error - Minor Bug

### ISSUE THREAD

**Issue by theicecrystal** [godotengine/godot#85234]
### Godot version

Godot_v4.1.3-stable_mono_win64

### System information

Windows 11 - Godot v4.1.3.stable - Vulkan (Forward+) - Editor

### Issue description

GD.print value

Start _Ready
Finish No_TryCatch
  System.IndexOutOfRangeException: Index was outside the bounds of the array.
     at Test.Have_TryCatch() in C:\Users\Ice\Godot\Bullet_Hell\Script\Test.cs:line 35
Finish Have_TryCatch

Problem:
There's no error report when script go broken.

As I try to make script I encounter this bug that my code not fully run and have to diagnose to fix it.
So I decide that to share this problem for future improvement of Godot.

Hope It Fix:
I hope that there'll be error report when script go broken in [async Task] function as default.

### Steps to reproduce

```csharp
using Godot;
using System;
using System.Threading.Tasks;

public partial class Test : Node
{
    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        GD.Print("Start _Ready");

        _ = No_TryCatch();

        GD.Print("Finish No_TryCatch");

        _ = Have_TryCatch();

        GD.Print("Finish Have_TryCatch");
    }

    private async Task No_TryCatch()
    {
        int[] test = new int[0];

        GD.Print(test[0]); // should crash and show as error

        await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame); // unnecessary, just have to keep async happy
    }
    private async Task Have_TryCatch()
    {
        try
        {
            int[] test = new int[0];

            GD.Print(test[0]); // should crash and show as error

            await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame); // unnecessary, just have to keep async happy
        }
        catch (Exception e)
        {
            GD.PrintErr(e);
        }
    }
}
```

### Minimal reproduction project

"N/A"

**Comment by markdibarry** [comment]
This is not a Godot issue. This is how context works in asynchronous tasks in C# by design.

You can test it here and see the same result without any Godot code: https://dotnetfiddle.net/Cg3lK5
If you turn your async methods to normal methods, it will crash as expected.
