### ISSUE TITLE
Animation window Edit -> Apply Reset fails because `AnimationMixer::_reset` is not exposed

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#85232]
### Godot version

4.2.rc 7022271

### System information

Godot v4.2.rc (702227129) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Attempting to run Edit -> Apply Reset on an animation player with a RESET track fails because the `AnimationMixer::apply_reset` method is called with `p_user_initiated` true.

In this case, it attempts to use UndoRedo to apply `"_reset"` which does not exist / is not exposed on AnimationPlayer.
```
Animation Apply Reset
  core\object\undo_redo.cpp:345 - Error calling UndoRedo method operation '_reset': 'AnimationPlayer::_reset': Instance is null
```
Other uses of `apply_reset` pass false which directly calls `AnimationMixer::reset()` and works fine.

Is there any reason that `reset` or `apply_reset` aren't exposed to scripting normally?

### Steps to reproduce

1. Import a model with a reset track
2. New Inherited Scene
3. Select the scene button in the hierarchy to open the base model directly.
4. Click "Open Anyway"
5. Select the AnimationPlayer
6. Choose the `_T-Pose_` animation or any animation other than `RESET`
7. Click the Edit menu -> `Apply Reset`. Nothing happens.
8. An error is printed in the log

### Minimal reproduction project

[ApplyReset.zip](https://github.com/godotengine/godot/files/13442920/ApplyReset.zip)

**Comment by akien-mga** [comment]
Same issue with `_restore` for the undo:
```cpp
EditorUndoRedoManager *ur = EditorUndoRedoManager::get_singleton();
ur->create_action(TTR("Animation Apply Reset"));
ur->add_do_method(this, "_reset");
ur->add_undo_method(this, "_restore", backup_current);
ur->commit_action();
```

Seems like neither `_reset` nor `_restore` exist, but there's `reset` and `restore` which are public but not bound indeed.
