### ISSUE TITLE
Undoing the change of the Anchors Preset of a Control will not restore it's offset/position

### ISSUE THREAD

**Issue by TheSofox** [godotengine/godot#85245]
### Godot version

4.2rc

### System information

Godot v4.2.rc (fa4a65387) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

If you change the Anchors Preset of a Control, and then hit Undo, the previous Control will have its previous Preset restored, but it won't restore its previous position unless it was the default position of that preset

Video:

https://github.com/godotengine/godot/assets/3089525/74500461-81b5-4eb4-bccc-47384d32dbad

### Steps to reproduce

1. Create a Container and put a Control in it. For example, create a Panel and put a Button in it.
2. Access the Button's Layout, ensure Layout Mode is set to Anchors, and then change Anchor Preset to Bottom Right.
3. Observe the Button is in the bottom right of the Panel
4. Move the Button from its default position. Observe this new position.
5. Set the Anchor Preset to Top Left (or any other). Note the button will change is position.
6. Hit Undo (Ctrl+Z)

**Expected:**
The Button should return to it's previous position, as at the end of step 4.

**Actual:**
The button is instead returned to default position for Bottom Right, the position it was at at the end of Step 3. 

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@thesofox Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL. I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by TheSofox** [comment]
Made a pull request for fixing this issue. Also noticed it affected Layout Mode too so included a fix for that in the pull request.

**Comment by hsandt** [comment]
Note that changing Layout Mode from Anchors to Position will also disable Anchors Preset (the field will disappear), causing the same effect.

**Comment by TheSofox** [comment]
Yes, my PR is coded to account for that. If either Layout Mode or Anchors Preset is changed, the undo operation will revert the control's entire state, instead of just reverting a single property. I did a quick test and seems to confirm it accounts for that.
