### ISSUE TITLE
Godot engine always start adb process

### ISSUE THREAD

**Issue by Infini-Creation** [godotengine/godot#85246]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Windows 10 (22H2 19045.3693)

### Issue description

Godot engine will always start, and restart if killed, _adb_ process even if there is no _Android_ export defined or wanted.

![godot-run-adb](https://github.com/godotengine/godot/assets/136735040/adb5bc9e-7536-45c9-9217-6bed2c74444f)

### Steps to reproduce

Launch Godot engine with a dummy project without even any export template installed
_adb_ process is launched by Godot (and launched again if killed)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/40366#issuecomment-1823511927.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/87823
