### ISSUE TITLE
The "Target Reached" signal on the NavigationAgent2D node does not reliably trigger when the path desired distance is set above the target desired distance

### ISSUE THREAD

**Issue by peter-rocchio** [godotengine/godot#85247]
### Godot version

4.2-rc1

### System information

Windows 11, Vulkan

### Issue description

When using the NavigationAgent2D the "target reached" signal usually does not trigger if the target desired distance value is below the path desired distance.  If, however, the navigation agent target position is set while the agent is within the desired distance then it will reliably trigger.

This can be simulated by either issuing a nearby move command or by setting (and thus recalculating) the target position every frame.

### Steps to reproduce

1. Implement a basic CharacterBody2D
2. Add a NavigationAgent2D node and leave the default values
3. Set up the CharacterBody2D to move when its NavigationAgent2D has its movement position set (based on the Using NavigationAgents documentation)
4. Connect the on_target_reached and on_navigation_finished signals
5. Move the character around and observe that navigation is finished before the target is reached when the target position is set beyond the target desired distance
6. Move the character a small distance within the target desired distance; observe the target reached signal reliably triggers
7. Set the target desired distance higher than the path desired distance (or vice versa); observe that the target reached signal more reliably triggers.

### Minimal reproduction project

[target-reached-test.zip](https://github.com/godotengine/godot/files/13444552/target-reached-test.zip)

**Comment by sandygk** [comment]
this seems to be related to: https://github.com/godotengine/godot/issues/82560

**Comment by smix8** [comment]
See pr https://github.com/godotengine/godot/pull/82561 that should fix that.
