### ISSUE TITLE
clip children doesn't work in CanvasGroup

### ISSUE THREAD

**Issue by LO-0116** [godotengine/godot#85243]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Compatibility) - Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9664) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

If a CanvasItem is a child of a CanvasGroup, all "clip children" options for the canvas item has no effect on its children besides changing the order in which they're drawn

### Steps to reproduce

Create a canvas group, add 2 ColorRect nodes to it as children, make one ColorRect a child of the other, try clip-children settings of the upper ColorRect. Effects visible in editor. (Also affects sprites etc.)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Quoting from the [CanvasGroup Documentation](https://docs.godotengine.org/en/latest/classes/class_canvasgroup.html)
> Note: Since CanvasGroup and [CanvasItem.clip_children](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-property-clip-children) both utilize the backbuffer, children of a CanvasGroup who have their [CanvasItem.clip_children](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-property-clip-children) set to anything other than [CanvasItem.CLIP_CHILDREN_DISABLED](https://docs.godotengine.org/en/latest/classes/class_canvasitem.html#class-canvasitem-constant-clip-children-disabled) will not function correctly.

This is a design constraint of CanvasGroup and clip_children.

I agree that it is a bit annoying and there is discussion on changing how CanvasGroup's work to remove this limitation.
