### ISSUE TITLE
Could you add an anchor point property for canvasitem?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8525]
**Operating system or device - Godot version:**

**Issue description:**

Godot have the offset property to shift the origin,but it use the absolute value, set the value depends on the size of the node, and it's not easy to use for some situations,for example,align frames for an animatedsprite by bottom.
Just like most engines did,the anchor point will accept value from (0,0) to (1,1)

**Link to minimal example project:**

**Comment by alexzheng** [comment]
When set the anchor point to (0.5,1), the frames will always align by center bottom,no matter the size of each frame texture,but the offset could not achieve this by set a value once,although we cound change the offset on each frame change event to align it,but it's not so handy.

**Comment by akien-mga** [comment]
Float anchors values are now available (see #9520), so this can be closed.
