### ISSUE TITLE
Failed to generate vsproj with scons 4.6.0

### ISSUE THREAD

**Issue by charlietsao** [godotengine/godot#85262]
### Godot version

4.1.3-stable

### System information

Windows 10

### Issue description

Scons build succeed. However, scons generate vsproj failed：
```
> scons p=windows vsproj=yes
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
Found MSVC version 14.2, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
KeyError: 0:
  File "E:\fdx\godot\SConstruct", line 971:
    methods.generate_vs_project(env, ARGUMENTS, env["vsproj_name"])
  File "E:\fdx\godot\methods.py", line 780:
    batch_file = find_visual_c_batch_file(env)
  File "E:\fdx\godot\methods.py", line 732:
    return find_batch_file(env, version, host_platform, target_platform)[0]
  File "C:\Users\fdx\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Tool\MSCommon\vc.py", line 929:
    vernum = float(get_msvc_version_numeric(msvc_version))
  File "C:\Users\fdx\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Tool\MSCommon\vc.py", line 504:
    return ''.join([x for x in msvc_version if x in string_digits + '.'])
  File "C:\Users\fdx\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Tool\MSCommon\vc.py", line 504:
    return ''.join([x for x in msvc_version if x in string_digits + '.'])
  File "C:\Users\fdx\AppData\Local\Programs\Python\Python310\lib\site-packages\SCons\Environment.py", line 586:
    return self._dict[key]
```

### Steps to reproduce

1. Install Visual Studio 2019
2. run `scons p=windows vsproj=yes`

### Minimal reproduction project

No project, just build.

**Comment by akien-mga** [comment]
Which scons version do you have installed?

**Comment by charlietsao** [comment]
> Which scons version do you have installed?

It's v4.6. Sorry I accidentally closed the issue just now.
```
> scons --version
SCons by Steven Knight et al.:
        SCons: v4.6.0.e5eef322a4a727b96358a436dca46e8085ac8692, Sun, 19 Nov 2023 17:22:20 -0700, by bdbaddog on M1Dog2021
        SCons path: ['C:\\Users\\fdx\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\SCons']
Copyright (c) 2001 - 2023 The SCons Foundation
```

**Comment by akien-mga** [comment]
I just tried on Windows with SCons 4.6.0 and I can reproduce the issue too. It must be a regression from the newly released 4.6.0.

**Comment by levidavidmurray** [comment]
For anyone else stumbling face first into this, run: `pip install SCons==4.5.2`

**Comment by mwichmann** [comment]
Looks like `find_batch_file` from `SCons.Tool.MSCommon.vc` in 4.6, which is called from `methods.py`, no longer takes an initial environment argument (the only usage of that was removed in SCons/scons@7082c53ff6 and so apparently the function signature was also adjusted):
```
-def find_batch_file(env, msvc_version, host_arch, target_arch):
+def find_batch_file(msvc_version, host_arch, target_arch, pdir):
```
Sounds a bit rude when I say it, but this function isn't a documented "public API" of SCons, so it doesn't come with API consistency promises. Nonetheless, apologies for the breakage.

**Comment by mhilbrunner** [comment]
@mwichmann Thanks for the help with this, and no worries, that seems absolutely fine. :)
