### ISSUE TITLE
A subclass of an GDExtension subclass of EditorPlugin cannot be used as an editor plugin

### ISSUE THREAD

**Issue by andreymal** [godotengine/godot#85268]
### Godot version

4.1.3

### System information

Linux

### Issue description

I'm trying to make an editor plugin on Rust:

```rust
#[derive(GodotClass)]
#[class(tool, editor_plugin, init, base=EditorPlugin)]
pub struct MyEditorPluginBase {}
```

But due to some limitations, I still have to use GDScript for some specific things.

So I tried to make a subclass of this Rust class:

```gdscript
@tool
class_name MyEditorPlugin
extends MyEditorPluginBase
```

This would work if `MyEditorPluginBase` was a GDScript class, but since it's a GDExtension class in my case, it doesn't work:

> Unable to load addon script from path: 'res://addons/my_addon/my_editor_plugin.gd' Base type is not EditorPlugin.

But it obviously **IS** EditorPlugin!

![godot-editorplugin-docs](https://github.com/godotengine/godot/assets/3236464/4665deeb-30f0-45cd-bfff-56101b9d4875)

![godot-editorplugin](https://github.com/godotengine/godot/assets/3236464/b1b6ecb4-de22-4abd-91a3-e180691f67ee)

If I understand correctly, this behavior is caused by this function, which checks some mysterious "instance base type" instead of real inheritance:

https://github.com/godotengine/godot/blob/fa4a65387ea41506ecc519fc61a06da110dce51c/editor/editor_node.cpp#L3456-L3458

https://github.com/godotengine/godot/blob/fa4a65387ea41506ecc519fc61a06da110dce51c/modules/gdscript/gdscript.cpp#L260-L263

Since the [documentation](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#the-script-file) doesn't say that the script must be a **direct** subclass of EditorPlugin (and an indirect subclass works fine in GDScript), I interpret this behavior as a Godot bug.

### Steps to reproduce

See above

### Minimal reproduction project

[gdext_editor_plugin_test.zip](https://github.com/godotengine/godot/files/13451014/gdext_editor_plugin_test.zip)

**Comment by AThousandShips** [comment]
Please provide a minimum project, there may be many different aspects of how you've set this up that might cause this

**Comment by YuriSizov** [comment]
`get_instance_base_type` is used correctly, but the check itself should likely be `ClassDB::is_parent_class(ibt, "EditorPlugin");`

**Comment by dsnopek** [comment]
FYI, it is also possible to directly register an `EditorPlugin` from GDExtension, you don't need to make an addon which necessitates the workaround you're using here, where you have a GDScript that extends your GDExtension class.

I don't know the API for how it's done from Rust, but in godot-cpp, you can have code like:

```
void register_my_extension(ModuleInitializationLevel p_level) {
#if defined(TOOLS_ENABLED) || defined(DEBUG_ENABLED)
	if (p_level == MODULE_INITIALIZATION_LEVEL_EDITOR) {
		GDREGISTER_CLASS(MyEditorPlugin);

		EditorPlugins::add_by_type<MyEditorPlugin>();
	}
#endif
}
```

This will cause the editor plugin to be registered as soon as the GDExtension is loaded.

There's probably a way to do this from Rust as well!

**Comment by andreymal** [comment]
@dsnopek I can't because of a godot-rust bug https://github.com/godot-rust/gdext/issues/494

(which can't be painlessly fixed until https://github.com/godotengine/godot-proposals/issues/2241 is implemented)

**Comment by andreymal** [comment]
There is another error in 4.2.1.rc1:

```
ERROR: Script inherits from native type 'MyEditorPluginBase', so it can't be assigned to an object of type 'EditorPlugin'.
   at: instance_create (modules/gdscript/gdscript.cpp:390)
```

Should I create a separate issue about this?

**Comment by YuriSizov** [comment]
@andreymal It maybe is just a continuation of this one, but feel free to open a new report. I would also appreciate if you could make an MRP that uses `godot-cpp` at least. It's unlikely that many contributors, myself included, have a Rust environment set up to reproduce and validate your report as it stands.
