### ISSUE TITLE
There is no method to rebuild the project(.Net) from code  

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#85272]
### Godot version

4.2 rc1

### System information

Windows10 

### Issue description

I found that there is no function in `EditorInterface` to rebuild the project for .net( or maybe in other place?). This feature is useful for plugin maker.  

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

**Comment by SmallKi** [comment]
ok, sorry, I will try.

**Comment by AThousandShips** [comment]
This suggestion is not safe as it depends on looking up the panel and tweaking like this, not a safe workaround
