### ISSUE TITLE
Ctrl-drag on Mac doesn't add `@onready` variable anymore

### ISSUE THREAD

**Issue by alex-dearden** [godotengine/godot#85276]
### Godot version

4.2 RC1

### System information

Mac OS

### Issue description

Ctrl-drag a node from the scene hierarchy to the GDScript editor no longer creates `@noready var` as it used to in 4.1

### Steps to reproduce

1. Create a node
2. drag it into the GDScript editor
3. hold Ctrl after you start dragging but before releasing
4. only the node's name will show in the inspector, along with the `$` for reference 

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
This is expected, see https://github.com/godotengine/godot/pull/71905. On MacOS it's more common to use Cmd for the same purpose where other platforms use Ctrl. So this was changed in https://github.com/godotengine/godot/pull/71905, and you need to press Cmd in 4.2.
