### ISSUE TITLE
Error al Configurar el Tamaño del Viewport

### ISSUE THREAD

**Issue by hbiblia** [godotengine/godot#85289]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Windows 10

### Issue description

Actualmente, en el panel de configuración del proyecto, es posible establecer un tamaño de viewport en cero. Sin embargo, esta acción es incorrecta y conduce a un error.

![image](https://github.com/godotengine/godot/assets/1939353/edda6eaf-235c-4e51-9308-30b70c49cf10)

![image](https://github.com/godotengine/godot/assets/1939353/798e0483-f000-4ca7-b7f3-ff26eabbc447)

Al realizar esta configuración alternativa, el funcionamiento se restablece correctamente.

![image](https://github.com/godotengine/godot/assets/1939353/cb68258d-a3e0-4a1a-8332-23ea78974eb3)

![image](https://github.com/godotengine/godot/assets/1939353/9100f08b-7825-4eb0-abff-c206793d3ef9)

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/1939353/edda6eaf-235c-4e51-9308-30b70c49cf10)

1. Abre la configuración del proyecto desde el menú 'Proyecto'.
2. Navega hacia 'Monitor' y selecciona 'Ventana'.
3. Ajusta el tamaño del viewport estableciéndolo en 0 en ambas dimensiones (ancho y alto).
4. Cierra la configuración del proyecto.
5. Reproduce la escena para aplicar los cambios.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84727, which is being addressed by https://github.com/godotengine/godot/pull/84800.

In the future, please use English for future bug reports (use a translator if needed).
