### ISSUE TITLE
Animation editor's Pin button wrong behavior.

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot#85285]
### Godot version

4.2 rc1

### System information

ubuntu 22.04

### Issue description

Small issue with Animation editor. It keeps pin button pressed when switching scenes, but edited player is replaced with player of another scene. The editor also simultaneously displays an inactive state with a prompt to select animation player.

### Steps to reproduce

- Create two scenes with AnimationPlayer on each and add animations for both.
- Select players on each scene.
- Pin one player and switch to another scene. If another scene has selected player issue should appear.

### Minimal reproduction project

N/A

**Comment by viksl** [comment]
I can sort of confirm this but for me the Animation dock doesn't display anything even when I press on the other AnimationPlayers until I go back to the scene where I pinned the AnimationPlayer and unpin it, it also keeps it disabled when I just leave and come back to the pinned scene (have to unpin it through the pin button next to the node in the scene tree).

**Comment by azuloo** [comment]
Another way to reproduce it is to follow these steps:

1. Select `AnimationPlayer` on the scene with created animation(s) in the animation list.
2. Pin the `AnimationPlayer`.
3. Select some other element on this same scene.
4. Switch to some other scene.
5. Switch back to the scene with pinned `AnimationPlayer`.
6. Observe that the animation list is empty (and `Animation Tools` is effectively disabled).

This issue doesn't reproduce if you skip the 3rd step from the list above.
