### ISSUE TITLE
Scene files are updated every time I save when animation is playing on a character with bones

### ISSUE THREAD

**Issue by mxaddict** [godotengine/godot#85287]
### Godot version

4.1.3.stable.arch_linux

### System information

Linux 6.6.1-arch1-1 Vulkan API 1.3.255 - Forward+

### Issue description

When saving a scene with a character with skeletan animations, the bone positions are saved in the scene as different values every time.

This is creating a huge chunk on changes that are being committed to GIT

### Steps to reproduce

1. Create a new scene
2. Add a character with a skeleton with skeleton animations
3. Save the scene
4. Commit the scene file to git repo
5. Save the scene again without making any changes
6. You will see in the git diff that the scene file will have updated positions in the skeleton bone positions based on the animation of the character that is in the scene

### Minimal reproduction project

N/A

**Comment by TokageItLab** [comment]
> Godot version
> 4.1.3.stable.arch_linux

It should be fixed in 4.2, please test it.

**Comment by mxaddict** [comment]
Nice
