### ISSUE TITLE
Can't run Navmesh demo on iOS

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8528]
**Operating system or device - Godot version:**
Godot 2.1.3
iPhone 7 running latest iOS

**Issue description:**
Running an unmodified version of the Navmesh, it runs fine on OSX but once running on iOS it looks like everything works but it doesn't render the main mesh nor robot. I can see the robot move as it is rendering the particles.

Checking the logs it complains it can't access a bunch of the fixedmaterial vertex shader attributes:
[1;31mERROR: get_current_version: [0m[1mMaterialShaderGLES2: Program LINK FAILED:
WARNING: Could not find vertex shader attribute 'instance_row1' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'color_attrib' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'instance_uv' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'instance_row2' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'bone_weights' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'tangent_attrib' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'instance_row3' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'uv_attrib' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'uv2_attrib' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'instance_row0' to match BindAttributeLocation request.
WARNING: Could not find vertex shader attribute 'bone_indices' to match BindAttributeLocation request.
ERROR: Implementation limit of 32 varying components exceeded. Unable to allocate 'shadow_coord'.

The log subsequently fills up with loads of errors as it tries to use these attributes. 

**Steps to reproduce:**
Run Navmesh on iOS

**Link to minimal example project:**
See Navmesh

**Comment by BastiaanOlij** [comment]
Note, I can get this to run when I turn shadows off so it seems to be an issue with shadows...

**Comment by BastiaanOlij** [comment]
Looks like the problem lies in the final line of that log:
ERROR: Implementation limit of 32 varying components exceeded. Unable to allocate 'shadow_coord'.

With all features enabled I count 40 varying variables in the main shader. I guess its just overloading what iOS can do..

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by vnen** [comment]
This is kind of relevant on 3.2-alpha3, this message still shows up:

`ERROR: Implementation limit of 32 varying components exceeded. Unable to allocate 'shadow_coord'.`

Though I haven't try the navmesh demo, it's showing in a project.

**Comment by akien-mga** [comment]
Might be worth opening a new issue about it, if only for better visibility. (And with a reproduction project attached.)
