### ISSUE TITLE
Animation Capture mode doesn't work in AnimationPlayer since 4.2.dev6

### ISSUE THREAD

**Issue by limbonaut** [godotengine/godot#85281]
### Godot version

v4.2.rc.custom_build [fa4a65387]

### System information

Manjaro GNOME, NVIDIA X11, Forward+

### Issue description

Animation Capture mode doesn't work as it used to in 3.x. I noticed that all animations in our project that used this mode stopped working as intended. Instead of smoothly interpolating towards a key on a track with capture, animation now jumps straight to it.
I can't reproduce it with v4.1.3. So it affects only v4.2.

### Steps to reproduce

Play some looping animation and then switch to an animation with a capture track.

### Minimal reproduction project

[animation_capture_bug.zip](https://github.com/godotengine/godot/files/13453510/animation_capture_bug.zip)

**Comment by limbonaut** [comment]
Related issue: #78234

**Comment by Calinou** [comment]
I can confirm this on 4.2.beta da0b1eb12 (Linux). This can be reproduced in https://github.com/godotengine/tps-demo by aiming with the right-mouse button (the camera smoothing transition is broken and snaps instantly to the final position).

This broke between 4.2.dev5 and 4.2.dev6. I'll bisect to the exact commit;

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83166.
