### ISSUE TITLE
Can't use PhysicsDirectSpaceState3D.intersect_shape as it's neither a static method, and PhysicsDirectSpaceState3D is an abstract class

### ISSUE THREAD

**Issue by CatarinaPBressan** [godotengine/godot#85291]
### Godot version

v4.1.3.stable.official [f06b6836a], v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3734) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads), Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3734) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

Can't use PhysicsDirectSpaceState3D.intersect_shape as it's neither a static method, and PhysicsDirectSpaceState3D is an abstract class.

![image](https://github.com/godotengine/godot/assets/3682178/20066772-9f9d-4886-9de5-e90a004e8652)

### Steps to reproduce

Try to use the PhysicsDirectSpaceState3D.intersect_shape method, the code editor will raise an error complaining that it's non-static, but the PhysicsDirectSpaceState3D class is abstract, so you can't instantiate it either.

### Minimal reproduction project

[PhysicsDirectSpaceState3D repro.zip](https://github.com/godotengine/godot/files/13454934/PhysicsDirectSpaceState3D.repro.zip)

The project contains a Node3D with the attached offending script (the project doesn't run anyway), but I initially found the issue in a script that ultimately inherited from RefCounted so I don't think the inheritance chain particularly matters in this case.

**Comment by Chevifier** [comment]
You need to get the state from the 3d world from any script connected to any 3D Node type 
`func get_intersection():
	var world_state = get_world_3d().direct_space_state
	var params = PhysicsShapeQueryParameters3D.new()
	params.shape = BoxShape3D.new()
	var result = world_state.intersect_shape(params)
`

**Comment by CatarinaPBressan** [comment]
Thanks! Is that documented somewhere?

**Comment by CatarinaPBressan** [comment]
Closing this as it's working. Would like to see it documented more clearly somewhere, ideally in the PhysicsDirectSpaceState3D class documentation...
