### ISSUE TITLE
Godot 4 ReflectionProbes are much glossier than default sky reflection

### ISSUE THREAD

**Issue by Arazalera** [godotengine/godot#85299]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i7-13620H (16 Threads)

### Issue description

Godot 4 ReflectionProbes are glossier than default sky reflection, so when you turn one on and off, the sky reflection becomes glossier when on, and rougher when off
![Screenshot (4051)](https://github.com/godotengine/godot/assets/149334681/4ebde826-7123-4082-b8b5-2b3224625b86)
The sphere has a roughness of 0.4, ReflectionProbe OFF, sky looks correct
![Screenshot (4052)](https://github.com/godotengine/godot/assets/149334681/7be260eb-9b8a-49d7-9d6f-f21a6cbf6fdb)
Reflection probe ON, sky and nearby cube is way too clear

Compared to godot 3, which is consistent
![Screenshot (4041)](https://github.com/godotengine/godot/assets/149334681/20b6e414-3908-4626-bd48-50e871de71a3)
Reflection probe OFF
![Screenshot (4042)](https://github.com/godotengine/godot/assets/149334681/00086141-8183-486a-b9de-6624519523d1)
Reflection probe ON, nearby cube looks blurry enough

### Steps to reproduce

Create a sphere with metallic 1 and moderate roughness (0.2-0.5)
Create a ReflectionProbe

### Minimal reproduction project

Godot 4:
[reflectionprobe test 4.zip](https://github.com/godotengine/godot/files/13457340/reflectionprobe.test.4.zip)
Godot 3:
[reflectionprobe test 3.zip](https://github.com/godotengine/godot/files/13457343/reflectionprobe.test.3.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.2.rc 066e7d483.

Decreasing **Reflection Size** to 32 in the Project Settings then restarting the editor will get you closer to the sky radiance look (especially when the sky update mode in Environment is set to **Real-Time**), but it'll still look noticeably different.
