### ISSUE TITLE
[3.x] Incorrect order in SceneTreeDock's context menu.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#85296]
### Godot version

3.6.beta3

### System information

Win11

### Issue description

Seems `Access as Unique Name` is remade from 4.0, but it's not in the correct position.

3.6.beta3:
![image](https://github.com/godotengine/godot/assets/12966814/18a78bfb-7b77-4067-ab61-bdb2ff5f2ae9)

3.5.x:
![image](https://github.com/godotengine/godot/assets/12966814/153d7ea9-ac72-4a37-9d37-c5c8acfaa137)

### Steps to reproduce

Right click nodes in SceneTreeDock.

### Minimal reproduction project

N/A

**Comment by lawnjelly** [comment]
Introduced in #66227 . @Mickeon

**Comment by Mickeon** [comment]
I could've sworn this was reported already but attempting to find it lead me to nothing.

The accidental irony is that this is exactly how https://github.com/godotengine/godot-proposals/issues/7631 proposed it should be.

**Comment by lawnjelly** [comment]
Looks like #81469 kind of fixes this (by removing the double separator).

There is no longer a line underneath the menu item (compared to 3.5), but at least it doesn't look objectionable now I guess. :grin:
