### ISSUE TITLE
SSAO Not functioning correctly on Mac builds with Radeon Pro 580X series card.

### ISSUE THREAD

**Issue by ALapidis** [godotengine/godot#85301]
### Godot version

4.1.3 & 4.2RC1

### System information

Retina 5K, 27-inch, 2019, 3.7 GHz 6-Core Intel Core i5, OS: Sonoma 14.1.1 (23B81), Video Card: AMD Radeon Pro 580X

### Issue description

![image](https://github.com/godotengine/godot/assets/16485257/4023b35a-3668-48f6-84cd-c3205521cab7)
_Shown here with 2 CSG Box's and default environment/lighting settings except for SSAO enabled and cranked up to illustrate issue._

Working on a project and noticed the SSAO simply did not work in any 4.0+ builds. 3.5 seems to work, but poor quality AO.
Tested on PC and AO works as expected, this issue seems unique to the Mac's Video card

### Steps to reproduce

1. Create any new project on a Mac with OS Sonoma and a Radeon Pro 580X video crd. 
2. Create 2 CSG box's or any geometry. 
3. Enable SSAO.

### Minimal reproduction project

N/A

**Comment by bruvzg** [comment]
Seems to be working on M1 Mac, are there any errors in the log?

**Comment by ALapidis** [comment]
After opening/closing the project several times it seems to have resolved itself. Unclear what factor changed. Cannot create the circumstances for this distorted AO again so closing the issue as a fluke. <Shrug>
