### ISSUE TITLE
Error appears in the console when performing simple operations

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#85300]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - macOS 14.1.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When making a new folder (and some other actions), I'm constantly getting error reports in the console.
![image](https://github.com/godotengine/godot/assets/106015575/fe0ae4c8-2e8d-43cf-a62f-01a659463ccb)

### Steps to reproduce

In any project, in File System, right click on an existing folder name. A menu will show up. Select "Create new", "folder". As soon as the name requester appears, the error will get printed.

(Or right click on a folder name, hold the rmb, and move to create new, folder and then release rmb.)

### Minimal reproduction project

Any project will do.

**Comment by lostminds** [comment]
Just tested in 4.2rc2 on macOS 14.1 and did not get these errors. @inhalt120g have you tested if you can reproduce this on 4.2rc2?

**Comment by inhalt120g** [comment]
Works fine in v4.2.rc2.official [1ba920fad]!
