### ISSUE TITLE
Animation cache errors immediately after deleting node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#85316]
### Godot version

4.2 rc1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you delete a node referenced by some animation tracks, you will get an error about invalid node, even if that animation is not currently playing.
This was introduced recently, probably after AnimationMixer was added.

### Steps to reproduce

1. Create AnimationPlayer
2. Create some tracks that refer to a node
3. In script, remove the node
4. Errors

### Minimal reproduction project

[cacherrors.zip](https://github.com/godotengine/godot/files/13461119/cacherrors.zip)

**Comment by dqanxy-umich** [comment]
Hope people don't mind if I investigate this issue for a school project. I'll update this thread with progress.

**Comment by dqanxy-umich** [comment]
Hello, I apologize if anything here is wrong, I'm new :)

Every time the cache is updated, it looks through all animations and all tracks, and finds each node associated with each track by calling get_node_and_resource. This process ends up returning two errors, one as the node cannot be found, and another by this block of code:
```
if (!child) {
	ERR_PRINT("AnimationMixer: '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'.");
	continue;
}
```
I too believe that these errors are rather confusing and unnecessary. Here is my workaround: 
```
Node *child = parent->get_node_or_null(path);

if (!child) {
	WARN_PRINT("AnimationMixer: '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'.");
	continue;
}
parent->get_node_and_resource(path, resource, leftover_path);
```
where we check if the node exists first. I hope that calling get_node twice is not too inefficient. I've also changed it from an error to a warning, I'm tempted to delete the posted error entirely but I left it as this. Please feel free to give any comments, I am unsure what is a good way to deal with this.

Here's the corresponding PR: https://github.com/godotengine/godot/pull/85368. Let me know if there are any problems with this!

**Comment by TokageItLab** [comment]
Does that error constantly show up in all frames? If it is only a problem for one frame after deletion, it sounds like a cache update issue, not an error issue as https://github.com/godotengine/godot/pull/85368.

**Comment by dqanxy-umich** [comment]
The error does not show up in all frames, and I have no clue if it existed in the old animation tree. It gives an error every time the cache is reloaded, which for instance, occurs every time an animation is started in the mixer, where it prints an error for every single animation in the mixer that has an invalid node, even if those animations aren't currently being used.

**Comment by Holosona** [comment]
Update: For me, the error occurs whenever i try to free the projectile from the animation player using a method call.

**Comment by TokageItLab** [comment]
As for memory leaks, that's another issue. See also https://github.com/godotengine/godot/pull/85001.
