### ISSUE TITLE
MultiMeshInstance2D is missing a useable populate feature similar to MultiMeshInstance3D

### ISSUE THREAD

**Issue by thisthrowaway** [godotengine/godot#85326]
### Godot version

4.1.3.stable

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3742) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

MultiMeshInstance2D's is missing its "populate" feature which works similar to it's 3D counterpart.
Adding any number of instances adds random PackedFloat32Array data to the buffer property. 
Although I reckon I can write code to manipulate the buffer to get the desired outcome, I don't think this is an intended way to use this node as populate exists in 3D. Also it hampers the user's ability to test things out in the editor as changing the instances randomizes the buffer.

![Godot Bug Report](https://github.com/godotengine/godot/assets/72639340/fd05ee72-c0cb-46a8-8511-8545e5fee6c6)

### Steps to reproduce

1. Add a MultiMeshInstance2D in the scene, set texture to godot icon and mesh to QuadMesh.
2. Add _n_ number of instances

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
> Adding any number of instances adds random PackedFloat32Array data to the buffer property.
> (...) Also it hampers the user's ability to test things out in the editor as changing the instances randomizes the buffer.

That's a bug, already reported/tracked in #75485.

>MultiMeshInstance2D's is missing its "populate" feature which works similar to it's 3D counterpart.
Although I reckon I can write code to manipulate the buffer to get the desired outcome, I don't think this is an intended way to use this node as populate exists in 3D. 

I think that's a material for a proposal, not for a bug report. See https://github.com/godotengine/godot-proposals#godot-improvement-proposals for more info. Also you'd need to provide more details as it's not clear/obvious what options such 2D populate tool would need, how exactly it should work, etc.

**Comment by thisthrowaway** [comment]
>Also you'd need to provide more details as it's not clear/obvious what options such 2D populate tool would need, how exactly it should work, etc.

Hey!
There already exists a populate feature within Godot's MultiMeshInstance3D!
If you change any of the buffer values on MultiMeshInstance2D  you can see that it corresponds to a Transform2D, serialized as a PackedFloat32Array, so clearly there is functionality already there, it's missing the connectors/a tab maybe for 2D.

Here is the tab/button that activates the feature in 3D
![populateMultiMeshInstance3D](https://github.com/godotengine/godot/assets/72639340/b8313fb8-e6c2-4763-b683-103c2a3281cc)


The options of the populate  and how it works in 3D
![populate in action - MultiMeshInstance3D](https://github.com/godotengine/godot/assets/72639340/36cf66ab-0083-4fc4-b51c-5dee9467d461)

Would it be a proposal if this already exists for 3D?
