### ISSUE TITLE
[Script Editor] "Clear" command: can't undo, permanent loss of code

### ISSUE THREAD

**Issue by tr0q** [godotengine/godot#8533]
2.1.3
Almost lost ~300 lines of code when accidentally clicked "clear" and couldn't "undo". Quitting editor or closing file would force save empty file, so only solution was to open [previously saved] file in external editor and re-save it from there.

**Comment by akien-mga** [comment]
Thought there was already an issue about this, but I can't find it.

Anyway, I think the whole "Clear" feature should just be dropped, I don't see it's point. If people need to empty their script, <kbd>Ctrl+A</kbd> followed by <kbd>Ctrl+X</kbd> or <kbd>Del</kbd> is simple enough.

**Comment by akien-mga** [comment]
BTW @tr0q, you should use version control to avoid such risks :)

**Comment by tr0q** [comment]
> BTW @tr0q, you should use version control to avoid such risks :)
I do, but it was a few hours since last commit. Anyway, I just thought it's dangerous behavior.

**Comment by Paulb23** [comment]
@akien-mga Its issue #6329, fixed in current master.

**Comment by akien-mga** [comment]
CC @Hinsbart in case he wants to cherry-pick f81d0095259c3affeec0de79e4ad1f38ea9bba39 or has another alternative.

**Comment by akien-mga** [comment]
Fixed by #16269.
