### ISSUE TITLE
FileAccess,FileExists() always return false when running on Android

### ISSUE THREAD

**Issue by Has-if36** [godotengine/godot#85352]
### Godot version

Godot v4.2.rc2.mono

### System information

Godot v4.2.rc2.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3114) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Somehow FileAccess,FileExists() always return false when I try running on Android. The device Im using is Infinix X6833B, Android 13.
![Window](https://github.com/godotengine/godot/assets/55189926/a092cc09-a52d-4942-9ba1-603d2cdf40a1)
It works well when running on Windows. Not sure how on other platform.
![Android](https://github.com/godotengine/godot/assets/55189926/aa20aae1-de10-4ef9-81c5-09ff853040cb)
However, for android I got this output

### Steps to reproduce

For test control, I used ResourceLoader.Load() to see if it's can actually load.

### Minimal reproduction project

[FileAccessTest.zip](https://github.com/godotengine/godot/files/13464923/FileAccessTest.zip)

**Comment by bruvzg** [comment]
> `[Export] string sfxFile = "res://Resources/Sheep1.ogg";`

That's expected behavior, on all platforms, source files or the imported resources (like `.ogg`) are not included in the exported project. `ResourceLoader` can still load imported resource using original path. `FileExists` will return true only when running from the editor.

**Comment by Has-if36** [comment]
Ouhhh I see. You're right, for window, I did run on editor and once I exported it breaks as you expected. Thanks for the clarification.
