### ISSUE TITLE
Exported executable crashes via Forward+ renderer

### ISSUE THREAD

**Issue by bonelike-pisc2** [godotengine/godot#85350]
### Godot version

v4.1.1.stable

### System information

Windows 10 - Vulkan API 1.1.120 - Intel(R) HD Graphics 620

### Issue description

When running .exe exported with Godot Editor in another machine, a window appears but nothing is drawn and the window closes automatically after a few seconds.
As far as I tried, I have confirmed that the .exe properly works if the file **pipelines.cache** exists in the folder **\%APPDATA\%\\Godot\\app_userdata\\${MyProject}\\vulkan\\**.
And then, the following have been detected:

- Download the Godot Editor of the same version (v4.1.1.stable) and import the source project of the .exe, then pipelines.cache was generated.
  After that the .exe works with no problem in this case.
  But when I delete pipelines.cache it becomes to crash again.
- At the machine where I exported the .exe originally (Windows 11 - Vulkan API 1.3.250 - AMD Radeon(TM) Graphics), it works even if pipelines.cache is missing. (sometimes it is automatically generated)
- It was OK when I switched the renderer of the project from "Forward+" to "Compatibility". (seems to use OpenGL instead of Vulkan)

Is that a matter of the version of Vulkan ?

### Steps to reproduce

- Export a project for Windows Desktop in Godot. Renderer config is set "Forward+". Export settings are the default.
- Transfer the exported .exe (and .pck) to another environment (noted in "System information" above), where Godot development environment is **NOT** set up.
- execute the .exe

### Minimal reproduction project

It seems like the issue has nothing to do with the content of projects.
I made a very simple project just containing an empty main scene and export_presets.cfg. It will be enough to reproduce the event.

[minimal_for_windows_export.zip](https://github.com/godotengine/godot/files/13464716/minimal_for_windows_export.zip)

**Comment by Calinou** [comment]
Can you run the exported project with console output enabled in the export preset, then look at the console output?
