### ISSUE TITLE
Editor stops updating the screen after resuming from sleep mode Linux/X11

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#85351]
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Godot v4.2.rc1 - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 545.29.02) - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

After resuming from sleep mode with godot already open, it takes a few seconds for my hard drive to spin back up and then i can log back in. Whenever i log back in, i always notice the editor being frozen. I have not tested it with a game in Godot already open.

NOTE: I know the editor didn't freeze, since if i press on close whenever it's in this state, if it's not saved it will still show a prompt, but that prompt doesn't render so it only shows a new blank window named "Please Confirm"

### Steps to reproduce

Open editor
Open project
Enter sleep mode
Resume from sleep mode
Log back in
The editor stopped updating the screen.

### Minimal reproduction project

N/A

**Comment by mortifia** [comment]
bug reproduce on linux manjaro
kernel 6.6

only the visual is hs (input interaction ok)
when the editor is hs opening a popup is also visually hs

**Comment by agi-creator** [comment]
bug reproduce on linux Pop Os
kernel 6.5.6

exactly as described in original issue description, editor visually freezes however it looks like it is responsive on keyboard and mouse events.

**Comment by RadiantUwU** [comment]
May be unrelated, may be not, blender fails CUDA compute initialization after same sleep mode

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52738. This is a NVIDIA issue we can't fix on our end.

**Comment by RadiantUwU** [comment]
NVIDIA RELATED ISSUE:
https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
