### ISSUE TITLE
Audio gets muted completely under specific conditions

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#85353]
### Godot version

4.2 rc2 / 4.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

In my project I managed to meet some very specific conditions that break the audio system. This looks like engine bug, because it requires all of the specific steps and makes the audio die completely.

Here's the bug (I'm using debug teleport to move faster):

https://github.com/godotengine/godot/assets/2223172/eca766cb-e9cd-42c1-b072-c486d048a32f

Note how in 0:10 the video goes completely silent and then after the gate animation the sounds plays normally. During that silence,  and audio track is supposed to play.

Here's video with the intended effects:

https://github.com/godotengine/godot/assets/2223172/2fa21898-f89e-494a-9d1c-5960923a5361

Note that this is the exactly the same build! The silence is 100% reproducible and the correct sounds is also 100% reproducible. If you look closely, the only thing that changed is that in the second video I didn't touch the save point.

Now, this is the interesting part. In order to trigger the bug I need to:
- start in the desert area. When I change areas, the music transition makes two music tracks play together and crossfade smoothly
- touch the save point to play its opening and closing animation
- when the gate closes, the music is silenced (I tween it to 0 volume)

If I skip *any* of these steps, the bug does not happen.

As for the bugged silence itself, it's not that the animation audio is not playing. All sound is completely disabled, I tried playing other sound affects at that moment and they are muted too.

EDIT:
After further investigation, silencing the music (`Jukebox.silence()` call) is the direct trigger of the bug, all other steps are just a setup. I tried silencing the music later and if I call the method mid-animation, the audio goes out immediately. Also it has something to do with 2 music players (see Jukebox.tscn). When I stop the unused one before calling `silence()` the bug does not happen.

### Steps to reproduce

Start the MRP and repeat what I did in the first video. You can use F1 to teleport character to cursor.

### Minimal reproduction project

Unfortunately, since the reproduction steps are extremely convoluted, I am not even sure how to extract it into a minimal project. I stripped down my game down to some essential files required to reproduce the bug. That's still 90MB though.

https://www.mediafire.com/file/pwz70vuxjtrqo86/repro_audio_oblivion.zip/file

**Comment by KoBeWi** [comment]
4.3 dev 6
![image](https://github.com/godotengine/godot/assets/2223172/ad868d9b-5325-4039-901b-d59d0f598412)
While the symptoms were fixed, I wonder if it's user error or I did something that triggered engine bug. I don't even know where the error comes from.

**Comment by KoBeWi** [comment]
Don't use `linear_to_db(0)`.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/61935
