### ISSUE TITLE
Crash on Exporting Android AAB using 'Hello World' Sample Android Plugin in Godot 4.2.rc2

### ISSUE THREAD

**Issue by luc4smoreira** [godotengine/godot#85395]
### Godot version

v4.2.rc2.official 

### System information

macOS Sonoma 14.0  - Mac Mini Apple M1 - Godot v4.2.rc2.official 

### Issue description

Testing the new system for Android plugins I found this bug when I tried to export the demo for Android using the **[Hello World plugin](https://github.com/m4gr3d/Godot-Android-Samples/blob/master/plugins/hello_world/README.md)** 

If I select the Gradle Build with **Export Format**:  **Export APK** it works. But when I change it to **Export AAB** Godot displays an error and then crashes, as mentioned in @https://github.com/godotengine/godot/issues/76497

### Steps to reproduce

Clone the project Godot-Android-Samples from:
`https://github.com/m4gr3d/Godot-Android-Samples.git` (commit 09386ad)

Build the  Hello World plugin: 

Using terminal go to 
`cd Godot-Android-Samples`

Run the gradlew command
`./gradlew :plugins:hello_world:assemble`

Using Godot v4.2.rc2, import the demo Godot project for Hello World plugin from:
`plugins/hello_world/demo`

If you haven't already installed the Android Build Template for Godot v4.2.rc2, install it.

Make sure the plugin is enabled 

> Project->Project Settings..-> Plugins

**HelloWorldPlugin** status Enable (checked)

Go to 

> `Project->Export`

Confirm that Android is already defined in Preset and select **Android (Runnable)**

Confirm **Use Gradle Build:** is On

Set **Export Format:** to **Export AAB**

In **Export Path** set the file extension with aab

![Screenshot 2023-11-26 at 15 08 45](https://github.com/godotengine/godot/assets/9322152/fc7664c5-2493-41a7-8c43-137dc1743d81)

Select **Export All...** and then **Debug**

Wait for the build to complete and check for the 'Build FAILED' message and Godot crashing.

The error only occurs with the 'Export AAB' option, not with the 'Export APK' option.

### Minimal reproduction project

[Godot-Android-Samples-master.zip](https://github.com/godotengine/godot/files/13467705/Godot-Android-Samples-master.zip)

**Comment by m4gr3d** [comment]
> * The editor crashing however seems to be an uncaught regression only happening on mac devices when multi-window is enabled; I was not able to reproduce the crash on a linux machine and on mac the crash stops when multi-window is disabled . cc @bruvzg @akien-mga

@akien-mga @bruvzg The reported issue was caused by the sample plugin and was successfully addressed. The regression mentioned above still remains however.
