### ISSUE TITLE
4.2 imported models have broken normals

### ISSUE THREAD

**Issue by Go-Ba** [godotengine/godot#85406]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Godot v4.2.beta6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When I import a model it will have anywhere from slightly to very messed up normals on surfaces which are completely flat. This happens both when importing the model into 4.2 or when using the automatic upgrade from 4.1 to 4.2.

The models show completely expected normals in blender, godot 4.1, and other 3D model viewers. They only get messed up specifically in godot 4.2. I tried pretty much every export option in blender and every import option within godot and could not find anything that would change this behaviour.

## Obviously wrong normals
![image](https://github.com/godotengine/godot/assets/64071930/d2002513-9ff5-4ccc-9d3d-9c09a396a1e2)
## Other versions
![image](https://github.com/godotengine/godot/assets/64071930/0732d138-80f5-4906-aaea-0f9fe77cea1d)
## Blender shows regular normals
![image](https://github.com/godotengine/godot/assets/64071930/ebf12cd6-ca04-4ac1-b176-c7ca1d6cfe10)

### Steps to reproduce

Import a .glb model with a complex flat face into a 4.2beta version and it may end up having messed up normals.

### Minimal reproduction project

[4.2b6_gltf_import_test_project.zip](https://github.com/godotengine/godot/files/13468337/4.2b6_gltf_import_test_project.zip)
[ProblematicModel.zip](https://github.com/godotengine/godot/files/13468335/ProblematicModel.zip)
[DebugNormalsShader.zip](https://github.com/godotengine/godot/files/13468340/DebugNormalsShader.zip)

**Comment by akien-mga** [comment]
I can confirm the issue on 4.2-rc2 on Linux (AMD Radeon RX Vega M).

On the other hand I also see normal issues on 4.1.3-stable, albeit not as bad, but still not all correct:
![image](https://github.com/godotengine/godot/assets/4701338/188e8336-d386-4335-844a-004c979918a9)

I also see these normal issues on https://modelviewer.dev/editor/
![image](https://github.com/godotengine/godot/assets/4701338/d4fed5e1-ada9-463c-8e69-cd1aa1eb63fa)

So I assume these are not the main problem to focus on, but the difference seen between 4.1.3 / Modelviewer and 4.2-rc2.

**Comment by clayjohn** [comment]
Early testing shows that the issue goes away when ``force_disabled_compression`` is used in the import settings. 

I'll see if I can find the root cause of the normal corruption though.

Another note: This is different than issues like https://github.com/godotengine/godot/issues/84270. While this model contains invalid UVs (for generating tangents), the issue is present even when "ensure tangents" is disabled. So the issue likely doesn't have to do with tangent generation.

**Comment by Go-Ba** [comment]
Originally when trying to fix this issue I was going through different export and import settings and somehow overlooked the "force disable compression"

I think that's because unlike other options in the import, it is a negatively stated option that is toggled off by default instead of a positively stated option toggled on by default like the others in the list. Compression is something that the engine is doing *to* the model which I want to turn *off* so toggling an option on is less intuitive. Changing it to something like "Enable Compression" which is on by default would be an improvement IMO. It would also shorten the name so it is easier to read on thinner windows.

![image](https://github.com/godotengine/godot/assets/64071930/10ca9fd9-8b5f-4471-b1ad-e208bde736fd)
Even though it is still cut off, I can much more easily intuit what this option does without knowing about it previously. This would make it easier for people to find the solution when their model looks broken and they just scan the import options.

-------------------

When it comes to exports, what blender export option did you use to disabled tangents? I have this option unchecked and it is like that by default, but I still get the issue. Is it a different export option?
![image](https://github.com/godotengine/godot/assets/64071930/ada2cdb2-ab05-42ed-b996-96f486cedc49)
What did work for me was taking the model into blender, doing a smart UV project and then exporting it. Seems to look fine even with `force_disable_compression` disabled. To be perfectly honest, I had no idea prior to this that the UV projection would affect rendering of normals in this way

**Comment by killercrash** [comment]
Hi, I was wondering if my issue is related to this issue :)
I believe things were fine on 4.1, and they are fine when I drop them in Unity.

![ae_house_05 tscn - Godot Engine](https://github.com/godotengine/godot/assets/2527035/216e713f-dceb-4631-9be1-f9e4ce6df2bd)
![ae_house_05 tscn - normal - Godot Engine](https://github.com/godotengine/godot/assets/2527035/e63cd319-9b33-4aa9-b9fc-6f3f8affe3e9)
![house_09 tscn - Godot Engine](https://github.com/godotengine/godot/assets/2527035/56a2ca97-f173-485c-af85-1483fdcf2b43)
![house_09 tscn - normal buffer - Godot Engine](https://github.com/godotengine/godot/assets/2527035/8b7d5ce5-b359-47d8-8497-637b949c7659)


I've been messing with import settings, disabling compression and tangent, but nothing has changed.
I'm a noob at 3d modeling, so I might not have spotted a problem on the models.
I would love to know if I just need to wait for a godot update or if I should retake things in Blender. (I'm bad at it, so I bought those .fbx of houses a long time ago, but I can manage to work on a fix if necessary.)

Thanks for your time and dedication!

**Comment by ijidau** [comment]
@killercrash your normals seem flipped, rather than this specific compression related issue. The blue surfaces on the apartment block normals are forward facing, but the red are backward facing. You need to check your normals in your 3d program to verify there is no issue there first.

**Comment by Calinou** [comment]
> the toggle for compression is expressed in the opposite way than expected.

It should be possible to rename the toggle and invert this behavior as long as we have a compatibility handler to port over the old value on existing resources.

**Comment by killercrash** [comment]
@ijidau I've tried to check the .fbx in Blender and the normals looks ok apparently :/

![normal_1](https://github.com/godotengine/godot/assets/2527035/946abc87-f929-4b9e-b5f8-020f6c227a97)
![normal_2](https://github.com/godotengine/godot/assets/2527035/c00bae57-3e80-4eaa-a67c-f22b9339ba50)

**Comment by ijidau** [comment]
@killercrash you've got quite a few overlapping edges in your mesh where I've marked yellow. These will cause the shading issues you are seeing.

![overlapping_edges](https://github.com/godotengine/godot/assets/3908991/de938cbe-bc15-4429-9e0a-a4928993f217)

**Comment by ijidau** [comment]
@killercrash actually I've just spotted some more. Check your mesh carefully, as you have connected edges in some strange ways that cause them to overlap. Also double check you haven't got any duplicated faces, edges, verts etc. A bit of mesh cleanup should solve your problems.

**Comment by rafrafek** [comment]
For me it's still broken on Godot 4.3, e.g. this model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/Fox/glTF-Binary
In the screenshot on the left the model imported to Blender and then .blend to Godot, on the right directly to Godot (broken shading).
![image](https://github.com/user-attachments/assets/173a8e22-9e6a-4b12-8178-7aed464db737)
Exporting to Android is also broken for this model. Even the Blender re-exported version has broken shading on Android.
I'm on MacOS (M1) and on the Mobile renderer.

**Comment by clayjohn** [comment]
@rafrafek Can you upload an MRP that reproduces the issue? When I download that model and import it into the engine it looks like the model on the left (on a M2 Mac).

**Comment by rafrafek** [comment]
Hi @clayjohn,

I tried to reproduce it in an MRP and now instead of having dark strips in becomes entirely darker when rotating:

https://github.com/rafrafek/normals-demo

![image](https://github.com/user-attachments/assets/47fa3485-a64f-44c5-9954-65df8f9c9dd7)

**Comment by clayjohn** [comment]
Thank you! I have copied your message into a new issue so we can track it https://github.com/godotengine/godot/issues/96484

**Comment by felixk525** [comment]
Got the same issue right now - godot 4.2.1 stable and i was wondering if there was a fix or workaround anyone knows off.
![image](https://github.com/user-attachments/assets/2e1f5d21-c17d-4f15-b20e-9993b4b64a3a)
![image](https://github.com/user-attachments/assets/2848292d-b197-43f3-afce-fd707f29425f)
Got an image from godot and blender - already checked in blender but the normals work out. If i disable normal map in the material in godot it looks uniform again but maybe there is a better way? Does updating godot fix this?

**Comment by clayjohn** [comment]
> Got an image from godot and blender - already checked in blender but the normals work out. If i disable normal map in the material in godot it looks uniform again but maybe there is a better way? Does updating godot fix this?

This issue is fixed in Godot 4.2.2 and Godot 4.3. I strongly recommend upgrading to one of those versions. 4.2.2 will be a totally seamless upgrade.
