### ISSUE TITLE
PSSM + Sky + Mesh crashes application (Forward+)

### ISSUE THREAD

**Issue by brcontainer** [godotengine/godot#85416]
### Godot version

- v4.2.beta1.official
- v4.2.beta2.official
- v4.2.beta3.official
- v4.2.beta4.official
- v4.2.beta5.official
- v4.2.rc1.official
- v4.2.rc2.official
- v4.2.stable.official
- v4.2.1.stable.official

### System information

Windows 10 - Godot v4.2.1 - Vulkan (Forward+) - GTX 1050 ti

### Issue description

The problem does not occur in Mobile mode, only in Foward+

The problem **does NOT** occur in versions:

- 4.1.3
- 4.2.dev1
- 4.2.dev2
- 4.2.dev3
- 4.2.dev4
- 4.2.dev5
- 4.2.dev6

When I add `MeshInstance3D`, `WorldEnvironment` with Sky and `DirectionalLight3D` with PSSM when running the project it simply crashes, and in the debuger or output there are no details.

### Steps to reproduce

- Create a project Foward+
- Create a scene 3D
- Add a MeshInstance3D with BoxMesh
- Add DirectionalLight3D with PSSM 2 or 4
- Enable Shadow in DirectionalLight3D
- Add WorldEnvironment with ProceduralSkyMaterial (no need to add SkyMaterial, even empty will cause the error)
- Run project

### Minimal reproduction project

[mcve.zip](https://github.com/godotengine/godot/files/13470316/mcve.zip)

> **NOTE:** I add a script that only enables shadows when running the project, because if you leave it enabled by default, the flaw mentioned in this issue will crashs the Godot editor, as well as crashs the game.

## Source:

**mcve.tscn**:

``` none
[gd_scene load_steps=6 format=3 uid="uid://bs7vlde3dow0m"]

[sub_resource type="GDScript" id="GDScript_fqg4w"]
script/source = "extends Node3D


func _ready():
	$DirectionalLight3D.shadow_enabled = true
"

[sub_resource type="ProceduralSkyMaterial" id="ProceduralSkyMaterial_2f6jt"]
sky_horizon_color = Color(0.64625, 0.65575, 0.67075, 1)
ground_horizon_color = Color(0.64625, 0.65575, 0.67075, 1)

[sub_resource type="Sky" id="Sky_r33d2"]
sky_material = SubResource("ProceduralSkyMaterial_2f6jt")

[sub_resource type="Environment" id="Environment_e7ls5"]
background_mode = 2
sky = SubResource("Sky_r33d2")

[sub_resource type="BoxMesh" id="BoxMesh_ia2ky"]

[node name="Node3D" type="Node3D"]
script = SubResource("GDScript_fqg4w")

[node name="DirectionalLight3D" type="DirectionalLight3D" parent="."]
transform = Transform3D(-0.866025, -0.433013, 0.25, 0, 0.5, 0.866025, -0.5, 0.75, -0.433013, 0, 0, 0)

[node name="WorldEnvironment" type="WorldEnvironment" parent="."]
environment = SubResource("Environment_e7ls5")

[node name="Camera3D" type="Camera3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2)

[node name="MeshInstance3D" type="MeshInstance3D" parent="."]
mesh = SubResource("BoxMesh_ia2ky")

```
**project.godot**:

``` none
config_version=5

[application]

config/name="4.2rc2"
run/main_scene="res://mcve.tscn"
config/features=PackedStringArray("4.2", "Forward Plus")
config/icon="res://icon.svg"
```

**Comment by akien-mga** [comment]
Tested on Linux with Intel HD 630 and AMD Radeon RX Vega M, I can't reproduce the issue.

Might be Windows / Nvidia or driver version specific.

Which Nvidia driver version do you have?

**Comment by mhilbrunner** [comment]
Tested and couldn't reproduce with my setup, neither with the attached MVP nor by following the steps manually.

Godot 4.2.rc2.official
Windows 10 Build 19045.3693
NVIDIA 545.92

**Comment by YuriSizov** [comment]
Can't reproduce the issue either, not in the editor or in a running scene, neither with the provided MRP nor by repeating the steps manually.

Godot v4.2.rc2 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.3742) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

**Comment by brcontainer** [comment]
@YuriSizov @mhilbrunner I downloaded 4.2 and the problem still exists. See video:

https://github.com/godotengine/godot/assets/4368952/2e7dfe19-8c25-43e2-9640-5823fbc728b4

In the video I show the following tests:

1. I turn off the shadow and the game works
1. I turn on the shadow the game crashes
1. I turn on the shade and switch to Orthogonal mode and the game works
1. I turn on the shadow and switch to PSSM 2 or 4 mode and the game crashes
1. I delete the Mesh, but keep the shadow in PSSM mode and the game works

I don't understand the Godot Core, but I believe the problem is related to Mesh or something related to an exclusive feature of "Forward+". Note that the problem does not occur in "Mobile" mode

**Comment by brcontainer** [comment]
@YuriSizov @mhilbrunner I updated the issue, with the specific versions that the bug occurs, but a relevant detail that I noticed, if you apply a `Timer` (https://docs.godotengine.org/en/stable/classes/class_timer.html) to load the scene that has the conditions to cause the failure configured `Timer.wait_time = 2.0`, the failure does not occur, but if decrease the time to `Timer.wait_time = 0.1` then the failure will occur. Here's the video of the problem:

https://github.com/godotengine/godot/assets/4368952/95c59104-06ed-4481-8575-39b9e6dedef7

**Comment by clayjohn** [comment]
@brcontainer Could you test again with the latest dev release ([4.3 dev 5](https://godotengine.org/download/archive/4.3-dev5/))? We have made a few fixes this dev cycle that may fix this issue for you. 

As a bit of background, this sort of bug is super tough to track down without being able to reproduce locally. Also, the fact that adding a wait time before setting the conditions was enough to stop the bug from happening indicates that it is a threading issue, which makes it even tougher to track down.

**Comment by Calinou** [comment]
@brcontainer Bump :slightly_smiling_face: See the above comment. Note that since the comment was made, [4.3.dev6](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-6/) was released.

**Comment by brcontainer** [comment]
@Calinou _I was waiting for the dev stage to finish_, considering that the next ones will be beta. First of all, yes, since 4.3dev1 the bug has apparently been resolved, which indicates that all the improvements in how they work with Vulkan are really going in a great direction. 🖖👽
