### ISSUE TITLE
Non-exclusive popup ConfirmationDialog fires `canceled` signal when pressing OK

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#85417]
### Godot version

4.2rc2

### System information

Linux/Manjaro

### Issue description

Pretty much stated in the title. An `AcceptDialog` with `exclusive` set to `false` and `popup_window` set to `true` will fire the `canceled` signal. This happens both on embedded and non-embedded subwindows.

### Steps to reproduce

1. Make an `AcceptDialog` with `exclusive` set to `false` and `popup_window` set to `true`
2. Subscribe to its' `canceled` and `confirmed` events
3. Show the dialog, press OK and observe that both signals get fired.

### Minimal reproduction project

[accept-dialog-cancel-confirm.zip](https://github.com/godotengine/godot/files/13470448/accept-dialog-cancel-confirm.zip)

Open the main scene and press OK and notice the prints.

**Comment by bruvzg** [comment]
> Make an AcceptDialog with exclusive set to false and popup_window set to true

`popup_window` should not be used with a normal dialog. It is intended specifically for popup menus, combo box dropdowns and similar temporary windows and enables special logic to auto-close the window in multiple conditions, which is likely what's interfering with dialog logic.
