### ISSUE TITLE
Breakpoint don't hit Custom modules in C++

### ISSUE THREAD

**Issue by hugarty** [godotengine/godot#85426]
### Godot version

v4.1.4.rc.custom_build.2d3b2abcf

### System information

Manjaro Linux, Intel i5, NVIDIA GeForce GTX 1060 3GB, Vulkan

### Issue description

Breakpoint hit another classes from engine like `scene/gui/button.cpp`, but don't hit custom module `modules/summator/summator.cpp`.

Searching for a solution, people said that GDExtensions can't has Breakpoint, but, I don't know if it should be valid for custom modules.

```
/* GDscript File  */

func _ready():
	var s = Summator.new()
	s.add(10)
	s.add(20)
	s.add(30)
	print(s.get_total())
	s.reset()



/* console output  */

60
```

![image](https://github.com/godotengine/godot/assets/18373512/f39de598-0b7a-4469-98b2-45159b824b6d)
![image](https://github.com/godotengine/godot/assets/18373512/1fc0262e-3c45-4322-b5d5-b94754094e2d)

### Steps to reproduce

I followed this tutorial [Custom modules in C++](https://docs.godotengine.org/en/4.1/contributing/development/core_and_modules/custom_modules_in_cpp.html#doc-custom-modules-in-c).

### Minimal reproduction project

Custom module
[summator.zip](https://github.com/godotengine/godot/files/13472913/summator.zip)

Project
[project_breakpoint_issue.zip](https://github.com/godotengine/godot/files/13472926/project_breakpoint_issue.zip)

**Comment by dpalais** [comment]
How are you building Godot? You need to instruct Scons to add or keep debugging information. Otherwise it's all optimized out.

See:
https://docs.godotengine.org/en/stable/contributing/development/compiling/introduction_to_the_buildsystem.html

**Comment by hugarty** [comment]
I'm using the infomation provided here [Engine development/ Configuring an IDE/ Visual Studio Code](https://docs.godotengine.org/en/stable/contributing/development/configuring_an_ide/visual_studio_code.html)

tasks.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "group": "build",
            "type": "shell",
            "command": "scons",
            "args": [
              // enable for debugging with breakpoints
              "platform=linuxbsd",
              "dev_build=yes"
            ],
            "problemMatcher": "$msCompile"
          }
    ]
}
```

launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "type": "lldb",
            "request": "launch",
            "program": "${workspaceFolder}/bin/godot.linuxbsd.editor.dev.x86_64",
            "args": ["--editor", "--path", "/home/hpca/game/project_breakpoint_issue"],
            "stopOnEntry": false,
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "build",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by bruvzg** [comment]
> "args": ["--editor", "--path", "/home/hpca/game/project_breakpoint_issue"],

This command will start the editor (and debugger will be attached to the editor), a project started from the editor is a fully separate process and won't be debugged. Try starting the project directly (without `--editor` argument).

**Comment by hugarty** [comment]
![image](https://github.com/godotengine/godot/assets/18373512/ee6eda92-8562-448d-91bd-4cb28b7da29e)
It worked, THANK YOU!
