### ISSUE TITLE
Exports become <null> in inspector and unable to be set when .csproj contains <DefineConstants> inside <PropertyGroup>

### ISSUE THREAD

**Issue by KarmyDev** [godotengine/godot#85441]
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Linux Mint 21.2 (Victoria) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Every Property of every script inside Inspector becomes uneditable, after adding `<DefineConstants>` to PropertyGroup inside `<project>.csproj` file.

![image](https://github.com/godotengine/godot/assets/32240709/40e1a322-6d66-46c5-b432-81a5fc5980f9)

### Steps to reproduce

1. Create new godot project
2. Create a simple scene with node and add C# script to it
Inside script add a simple `[Export] public string test = "hello :D";` inside class
3. build
4. modify `<project>.csproj` file, inside `<PropertyGroup>` add `<DefineConstants>TEST</DefineConstants>` and save
5. build

Inside your scene, click node you've created and inside inspector, the property Test should now turn its value from `hello :D` into `<null>` and become uneditable

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please try a recent version, your version is over a month old

**Comment by KarmyDev** [comment]
I downloaded latest release candidate (v4.2.rc2.mono.official [1ba920fad]) and unfortunately the issue still appears

**Comment by KarmyDev** [comment]
Hello again
It appears I found the issue, its kind of my fault and Microsoft's, basically `<DefineConstants>` replaces every constant value with whatever its inside this Property. Hence why adding any own constant, breaks Godot because it removes anything else thats already set.

In order to add any own constants, you have to add `$(DefineConstants);` before your constant inside `<DefineConstants>` Property.
