### ISSUE TITLE
Files not deleting - Godot 4.2rc2 - Web Editor

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#85445]
### Godot version

4.2.rc2

### System information

Godot v4.2.rc2 - Web - GLES3 (Compatibility) - WebKit WebGL -  (2 Threads)

### Issue description

Whenever I try to delete a file it says "Cannot Remove: (filepath)" This also happens on chromebook.

### Steps to reproduce

1. Open a project in the web editor.
2. Try to delete the built-in "icon.svg" file or any imported file.

### Minimal reproduction project

N/A

**Comment by Qainguin** [comment]
This seems to be a long-lasting issue on the web editor.

**Comment by Chaosus** [comment]
Nothing wondering, since any web-based applications have the strict rules and cannot change anything OS-related including a file system.

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/70975
