### ISSUE TITLE
Significant audio delay on games exported to mobile

### ISSUE THREAD

**Issue by kKapalka** [godotengine/godot#85442]
### Godot version

4.1.3, 4.2.0rc1

### System information

Android 11

### Issue description

AudioStreamPlayer plays sounds with a noticable latency (>0.5s) on mobile devices. It makes triggerable sounds not line up with the events on the screen that cause the sounds.

### Steps to reproduce

1. Create a clickable button, and make the button call AudioStreamPlayer.play() after clicking the button
2. Export game to mobile, and install the game on your device
3. Play game, click button. Notice the delay between clicking the button and the sound being played.

### Minimal reproduction project

[AudioStreamPlayer Issue Project.zip](https://github.com/godotengine/godot/files/13479567/AudioStreamPlayer.Issue.Project.zip)

**Comment by kKapalka** [comment]
If there's testing that needs to be done, lemme know, might be able to help.
But I don't have other actual physical mobile devices, might be forced to test different installations through emulators.

**Comment by djrain** [comment]
Been experiencing this too, and it is quite bad. But from googling it, audio latency on Android is a known issue in general. Fortunately I haven't noticed any delay on iOS devices.

**Comment by kKapalka** [comment]
Okay, I isolated the issue.
It is 100% related to bluetooth.
When using built-in phone speakers, there is no perceptible audio delay, but while I'm using my bluetooth speakers to play the sounds, there is the delay.

I'm no longer sure whether Godot can actually do something to fix this.

**Comment by djrain** [comment]
> When using built-in phone speakers, there is no perceptible audio delay

Interesting, afraid I can't say the same. There's definitely latency on our Pixel 4 XL (maybe 0.1 seconds or so after tapping the screen). But again, this seems normal from the Android data online

**Comment by kKapalka** [comment]
Maybe there is some delay, but certainly not in the degrees of 0.5 second or so, as you would experience with bluetooth speakers. 0.1s is still bearable, 0.5s - not even close.

**Comment by Calinou** [comment]
Can you reproduce this latency in other Android apps and games?

You may be able to get better Bluetooth audio latency by playing with the codec used in the device's developer settings, but not all devices support aptX or LDAC (which should be preferred over the standard SBC or even AAC).

**Comment by kKapalka** [comment]
Yes, I actually can.
I picked up another mobile game - Gems of War (it is similar to the current project I'm working on, so I wanted to study it and have a feel for what it does wrong and what it does right when it comes to gameplay and aesthetic), and I can see a noticable delay between clicks I make and click sounds the game emits (around 0.5s) only when using bluetooth headset.

I tried changing the codec, but I have access only to SBC and AAC codecs so no luck there.

**Comment by Alex2782** [comment]
I also noticed high latency via Bluetooth headphones on my new Samsung Android 13 tablet a few weeks ago.

------------
An example from Google (GameActivity) uses this library, what exactly does Godot use?

https://developer.android.com/games/sdk/oboe

- Achieve the lowest latency. 
- Use the best available native library.
- Avoid audio bugs.

**Comment by kKapalka** [comment]
so you're tellin me there's a chance...
< insert dumb&dumber gif here >

**Comment by desttinghim** [comment]
Going back through the OpenSL documentation, it appears it is possible to get low latency with OpenSL, but not all devices support it. The Android Documentation has a page on reducing latency: https://developer.android.com/ndk/guides/audio/audio-latency
Some things it looks like Godot isn't already doing in `audio_driver_opensl.cpp`:
- Query the device's optimal sampling rate instead of using a constant value (currently hard coded to use 44.1 khz)
- Query the device's optimal buffer size (currently hardcoded to 1024)
Unfortunately there are no NDK functions to get this info, it must be retrieved through the JNI. 

The equivalent AAudio code for this is much simpler as it will use the optimal values unless overriden explicitly.

**Comment by Alex2782** [comment]
if "oboe" is just a compatibility library, then it is probably better to look for a Godot solution for **AAudio**

> [AAudio](https://developer.android.com/ndk/guides/audio/aaudio/aaudio) was developed as a lightweight, native Android alternative to the OpenSL ES library. The AAudio API is smaller and easier to use than OpenSL ES.

<details>
<summary>liboboe.so filesize (Debug)</summary>

----------------------
up to 266 KB **Raw File Size**, in every subfolder (x86_64, x86, arm64, armeabi)


![Bildschirmfoto 2023-11-30 um 22 31 40](https://github.com/godotengine/godot/assets/41921395/cc6b922b-bfd0-4291-9944-f3750fd7428a)
</details>

**Comment by MJacred** [comment]
There's already a proposal to integrate Oboe, apparently opened by so. from Google: https://github.com/godotengine/godot-proposals/issues/2358. You can upvote the proposal to show your support or even take a crack at it

In that case, I'd say this issue could be closed

**Comment by kKapalka** [comment]
Yeah, good idea.
Closing this issue then.
