### ISSUE TITLE
Allow exporting without packing

### ISSUE THREAD

**Issue by Zephilinox** [godotengine/godot#8545]
Right now there are 3 different export options that involve various ways of packing data. An option to leave it unpacked, such as what the zipped option does but without zipping it, would be helpful for those of us who are interested in allowing end-users to mod the core data.

**Comment by eon-s** [comment]
Could be useful for project merge too (export many into the same directory).

**Comment by reduz** [comment]
The export options were removed in Godot 3. I will, however, tell you a little secret.
Just put a godot release binary in the root of your project and it will run the game fine without exporting, so there is nothing that needs to be done for this.

**Comment by akien-mga** [comment]
> Just put a godot release binary in the root of your project and it will run the game fine without exporting, so there is nothing that needs to be done for this.

Sadly in 3.0 and later, you still need to ship the `.import/` folder if you want this behaviour to work, as the template binary can't import the data itself.
