### ISSUE TITLE
Update ThorVG to 0.11.5 to fix a bug with clipped strokes

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#85465]
### Godot version

4.2.rc1

### System information

not relevant

### Issue description

ThorVG 0.11.5 fixed a bug causing strokes for basic shapes outside the canvas to be improperly invisible due to clipping. This bugfix helps resolve issues with results from the `Image.load_svg()` functions.

### Steps to reproduce

```<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><circle cx="8" cy="-4.001" r="4" stroke="#8da5f3" stroke-width="3"/></svg>```

^ Example of a SVG that doesn't display correctly.

### Minimal reproduction project

N/A

**Comment by capnm** [comment]
![gdi85465big](https://github.com/godotengine/godot/assets/4047289/44dd563a-1ea4-4ba0-8e13-ff6b26553e78)

![editor_screenshot_2023-11-29T105059](https://github.com/godotengine/godot/assets/4047289/6e88ce3e-13d7-4580-b7aa-7c41de1372af)

There is currently a minor issue that breaks some Godot CIs
https://github.com/thorvg/thorvg/pull/1738#issuecomment-1831782063
