### ISSUE TITLE
MouseEntered not detected on area2D with child CollisionShape2D

### ISSUE THREAD

**Issue by Benardus** [godotengine/godot#85469]
### Godot version

v4.2.rc2.mono.official [1ba920fad]

### System information

Godot v4.2.rc2.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

I am testing my project that works perfectly in 4.1.3 and I noticed that all Area2D nodes with CollisionShape2D as a child do not respond to MouseEntered and MouseExited 

- It doesn't fire the GD.Print
- I don't get any errors. 
- Nothing has changed (no control nodes added, no mouse signals blocked, monitoring and monitorable as enabled etc)
- All area2D nodes have this problem, within packed scenes, within the canvas of the scene itself etc.
- I am not using any subviewport or viewports.
- It worked flawlessy in Godot 4.1.3 so I suspect any mouse input changes like:  Make mouse enter/exit notifications match mouse events #84547, to be causing this.

I have added the current tree structure on which the code executes:
![Treestructure2](https://github.com/godotengine/godot/assets/151070874/330a1938-9f8d-416c-8ea1-506c42181898)

### Steps to reproduce

Example C# code on my Scene
```
// Create an array of your Area2D nodes
        Area2D[] areaNodes = { area1, area2, area3, area4, area5, area6, area7, area8,
                        area9, area10, area11, area12, area13, area14, area15, area16,
                        area17, area18, area19, area20, area21, area22, area23, area24,
                        };

        // Connect Area2D mouse signals for as many relics as the player has
        for (int i = 0; i < retrievedRelics.Count && i < 24; i++)
        {
            Area2D area = areaNodes[i];
            if (area != null)
            {
                area.SetMeta("relicID", retrievedRelics[i].RelicID);  // Setting metadata
                UpdateMouseEntered(area);
                UpdateMouseExited(area);
            }
else
            {
                GD.PrintErr("Area2D node is null for index ", i, " and RelicID ", retrievedRelics[i].RelicID);
            }
        }
```

```
public void UpdateMouseEntered(Area2D area)
    {
        // Check if an event handler already exists for this area
        if (mouseEnterHandlers.ContainsKey(area))
        {
            // Remove the old event handler
            area.MouseEntered -= mouseEnterHandlers[area];
        }

        // Create a new event handler
        Action newHandler = () => OnMouseEntered(area);

        // Add the new event handler to the button's Pressed event
        area.MouseEntered += newHandler;

        // Update the handler in our dictionary
        mouseEnterHandlers[area] = newHandler;
    }
```

```
public void OnMouseEntered(Area2D area)
    {
        GD.Print("Mouse enter detected");
    }
```

### Minimal reproduction project

N/A

**Comment by Chaosus** [comment]
Please provide a proper MRP in a zip archive.

**Comment by Sauermann** [comment]
Thanks for the MRP.

In your project, the `Area2D` doesn't receive mouse-enter/exited signals, because the `ColorRect` node consumes the event.
I can see two viable ways to make your use-case work:
1. In the `ColorRect` set `mouse_filter` to `Ignore`
2. Instead of using `Area2D`, use the `mouse_entered/exited` signals of the `ColorRect`.

**Comment by kitbdev** [comment]
related: [#54529](https://github.com/godotengine/godot/issues/54529)

**Comment by Benardus** [comment]
I had to change mouse settings on all panels and other elements to either PASS or IGNORE. They seem to be set to IGNORE as standard which is very aggressive. I was able to restore mouse signal functionality So the Area2D nodes seem to be working correctly and this ticket/issue can be closed

**Comment by hustlerman** [comment]
I'm still having this problem after upgrading from 4.1.3 to 4.2 - I have not found the way to fix my mouse detection issues, and either way IMO this is a breaking change.
