### ISSUE TITLE
Input screen isn't working on web AR mode

### ISSUE THREAD

**Issue by jeisoncp** [godotengine/godot#85482]
### Godot version

v3.5.3.stable.official [6c814135b]

### System information

Windows 10.0.19044 - GLES2 - NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.2737) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

None input on screen is being recognized in AR session in a web export application. The input is only detected in default web session, as we can see in the demonstration bellow: 

https://github.com/godotengine/godot/assets/7952798/ef88a617-6ee3-468d-baa0-174dd20f81d8

The expected behavior would be to play the cube animation, as played in the web session.

P.S.: This same demo was redone in Godot 4 and it's working. But it was needed downgrade to 3.5 because of iOS/Mac web support.

### Steps to reproduce

1. Open the project;
2. Insert your IP address in Editor Settings > General > Export > Web > HTTP Host;
3. Choose "Run in the browser" button;
4. Open the URL in your Android phone in a WebXR compatible browser (Brave, Chrome, etc.);
5. Touch in the "Enter AR" button;
6. Touch in the cube;
7. Touch in the "Animate!" button;
8. No animation is played.

### Minimal reproduction project

[DemoWebAR.zip](https://github.com/godotengine/godot/files/13491758/DemoWebAR.zip)

**Comment by dsnopek** [comment]
Thanks! I'm able to reproduce the issue with your MRP

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/85521 which fixes this issue in my testing

**Comment by akien-mga** [comment]
Fixed by #85521.
