### ISSUE TITLE
Roughness information is lost with ETC1

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8549]
Godot doesn't have any special workarounds to handle alpha channels with ETC1. This is just a statement of a trivia of course, but with new PBR textures, this is a real concern because alpha is used encode roughness in specular textures.

One solution could be to disable ETC1 for specular texture (in specular workflow). An alternative is to drop ETC1 altogether in favor of ETC2, since OpenGL ES 3.0 is a requirement for mobile.

**Comment by tagcup** [comment]
Of course this is also true for all other 4-channel textures like anisotropy, detail, ...

**Comment by reduz** [comment]
ETC1 kind of sucks, as no alpha is supported

**Comment by tagcup** [comment]
@reduz I have a feeling that this is fixed (after you modifications to etc2comp)?

**Comment by reduz** [comment]
I did not do any modification to etc2comp, but roughness is not any longer in the alpha channel so...
closing this.

**Comment by tagcup** [comment]
How about other RGBA textures?
