### ISSUE TITLE
GPU Lightmap: Baking directional with physical lights causes static lights to have excessive amount of energy compare with no directional bake 

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#85506]
### Godot version

v4.2.rc.custom_build [4c5a14845]

### System information

Ubuntu with Nvidia 2060

### Issue description

When physical lights are configured in the project and static lights are baked with directional, they receive a lot of energy compared with no directional bake

Direcional:
![Screenshot from 2023-11-29 10-29-06](https://github.com/godotengine/godot/assets/1168582/1193d865-1b46-4efc-8b3c-734ecf127975)

No directional:
![Screenshot from 2023-11-29 10-29-28](https://github.com/godotengine/godot/assets/1168582/b9fb5cc3-5674-4aa3-9594-a3255d98eeb5)

### Steps to reproduce

Use MRP

Set ligihts to phyisical in project configuration
Bake lightmap with `directional`

For comparison:
Set ligihts to non-phyisical in project configuration
Bake lightmap with `directional`

### Minimal reproduction project

[lightmap.zip](https://github.com/godotengine/godot/files/13501068/lightmap.zip)

**Comment by Calinou** [comment]
My guess is that `bake_params.exposure_normalization` isn't used where it should be in the directional lightmap baking shader. Here's an example where it's used correctly: https://github.com/godotengine/godot/blob/b3a0e077ebd29bc4e2456dea816b525b691932ab/modules/lightmapper_rd/lm_compute.glsl#L461-L531

**Comment by jcostello** [comment]
I added `* bake_params.exposure_normalization` to line 444 but that completelly eliminates direct light.

**Comment by jcostello** [comment]
https://github.com/godotengine/godot/pull/95888 Might fix it

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/95888 indeed fixes this:

Directional OFF | Directional ON
-|-
![Directional OFF](https://github.com/user-attachments/assets/5d66910d-bb8f-41a7-8738-e76c8edddd19) | ![Directional ON](https://github.com/user-attachments/assets/dc7d6803-16bb-4cc0-bdd1-5731419f1de9)

**Comment by clayjohn** [comment]
Thanks for checking! I had this issue in mind when I made https://github.com/godotengine/godot/pull/95888 but I wasn't able to find it for some reason!
