### ISSUE TITLE
S3TC textures appear with bad artifacts

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8550]
According to the current plans, Godot will require GL3.3 on desktop which doesn't mandate ETC texture support. Currently, only S3TC textures are used on desktop.

Current S3TC encoder can produce bad artifacts: (uncompressed vs VRAM for the 512x512 albedo texture, prepared in substance painter, from #8457)

![yuxocz](https://cloud.githubusercontent.com/assets/16531565/25206609/bf105d00-252e-11e7-897c-4b4281056796.jpg)
![cyv2qx](https://cloud.githubusercontent.com/assets/16531565/25206608/bceec3fe-252e-11e7-9122-6e21b61701f1.jpg)

**Comment by tagcup** [comment]
Godot currently uses an old version of libsquish, with a low quality setting (`kColourRangeFit`). The problem persist even with the latest version of libsquish (1.15), and using the best compression `kColourIterativeClusterFit`.

**Comment by akien-mga** [comment]
Actually Godot uses the latest version of libsquish: https://github.com/godotengine/godot/blob/master/thirdparty/README.md#squish
But it's almost the same as the previous 1.14: https://github.com/godotengine/godot/commit/fa2d5b91dc390a11262859e5309351ba58842901

**Comment by tagcup** [comment]
I think I got the version number from a wrong place: [this](https://github.com/svn2github/libsquish) is the repository link from the [original author's blog](http://sjbrown.co.uk/2006/01/19/dxt-compression-techniques/), and it adds nontrivial stuff on top of what currently comes with Godot.

But using it it still doesn't solve the issue. I'm not 100% sure about this yet but it seems like the output of libsquish is fine, the problem is somewhere else in Godot.

**Comment by tagcup** [comment]
So far I tried using squishpng (in sourceforge repo) on that texture, and it is indeed giving fair results at all quality settings. So it does seem like the problem is within Godot.

**Comment by tagcup** [comment]
Within Godot, I confirmed that the generated S3TC is OK, so the problem is definitely somewhere else, possibly within the renderer.

This, however, led me to discover that `Image::_decompress_bc` isn't working. I added a `image_decompress_squish` function which wraps squish's decompressor, registered that and used that instead. Not sure why there is an alternative decompressor there. I'll submit a PR for that later on.

**Comment by tagcup** [comment]
OK, found the problem: there is a typo on [this line](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L248): `_EXT_COMPRESSED_SRGB_S3TC_DXT1_NV` should actually be `_EXT_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_NV`.
Things work good as expected.

I'll submit another PR for that.

I'll also make sure VRAM quality settings (introduced in #8548) effect the squish quality settings.

Just as a note to myself so that I won't forget it: Image::save_png` should be const.
