### ISSUE TITLE
VisualScript: can't change bool parameter in function call.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8551]
**Operating system or device - Godot version:**
Linux -  5993a5f

**Issue description:**
When calling a function that takes a boolean parameter in VS, it defaults to `false` and can't be changed directly. If you want to call it with `true` you'll have to plug a bool constant in the slot.

So far it seems like only `bool` has this problem, other variant types are ok.

![vs_call_bug](https://cloud.githubusercontent.com/assets/8281916/25450286/b5016094-2abe-11e7-999e-ff948aacc54a.gif)

**Comment by akien-mga** [comment]
Fixed by #8702.
