### ISSUE TITLE
Editor UI scales poorly on a bigger monitor (blurred UI elements, including gizmos and fonts, flickering)

### ISSUE THREAD

**Issue by DanikVitek** [godotengine/godot#85538]
### Godot version

v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 11 23H2 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

I'm using my laptop for work and connected a separate monitor for better colors and convenience. Both displays have a resolution of 1920x1080 px, but the laptop's main display is upscaled to 125%, and the second one is 100%.
On the main display, Godot's editor's GUI and all its assets are sharp, crisp, and pretty, with no complaints.
But when I move any window to the second monitor, its assets look blurry and hard to read/look at, including icons, fonts, and gizmos, with some occasional flickering once in a few seconds. Also, when maximizing a window, it would sometimes have gaps on the edges.
I was trying to set the rendering settings of the editor's font and in general, it had no helpful effect.
When I set the scale of the second monitor to 125%, all the bad effects went away, but it's not a working option for me.
Unfortunately, the video does not capture the flickering, though it seems to capture the blurriness.

https://github.com/godotengine/godot/assets/25585136/34ed5b65-bc8d-47e7-8925-67aa21d0ad3c

https://github.com/godotengine/godot/assets/25585136/0874891e-5a76-415b-a50c-1a1948b29cea

### Steps to reproduce

Move a Godot window from the monitor with a 125% scale to the monitor with a 100% scale.

### Minimal reproduction project

N/A

**Comment by DanikVitek** [comment]
The issue disappears if I make the second monitor with 100% scaling to be my main in Windows settings.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/56341.
