### ISSUE TITLE
Characterbody2D mouse interactions not functioning

### ISSUE THREAD

**Issue by Starkandco** [godotengine/godot#85535]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Characterbody2D on_mouse_entered not functioning, works for areas

### Steps to reproduce

Set up charbody2d node with a collision shape and a script and attach on mouse entered/exit
run with visible collision shapes and hover mouse over shape

### Minimal reproduction project

[charbodytest.zip](https://github.com/godotengine/godot/files/13513342/charbodytest.zip)`

Includes comparison area node showing mouse entered/exit functionality working

**Comment by AThousandShips** [comment]
Have you set `input_pickable` to `true`? It is set to `false` on `PhysicsBody2D` by default, unlike `Area2D`

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error. 🙂

**Comment by Starkandco** [comment]
> Have you set `input_pickable` to `true`? It is set to `false` on `PhysicsBody2D` by default, unlike `Area2D`

This was the issue, apologies

**Comment by AThousandShips** [comment]
No worries 🙂 it's also a good idea to investigate the documentation when figuring things out
