### ISSUE TITLE
[4.2] Windows 11 window decoration shadows flicker constantly while Godot is running

### ISSUE THREAD

**Issue by HybridEidolon** [godotengine/godot#85547]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated AMD Radeon RX 6800 XT (Advanced Micro Devices, Inc.; 31.0.22023.1014) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 Threads)

### Issue description

In these conditions:

1. Running Windows 11 with AMD driver
2. on a display with Variable Refresh Rate/"Freesync" enabled (possibly unrelated)
3. Using the Forward+ or Mobile renderers (not Compatibility)

the shadow window decoration on _every_ window (not just Godot's) flickers _constantly,_ even when the game or editor itself is out of focus.

### Steps to reproduce

1. Make a scene in the Forward+ or Mobile renderers
2. Run the game

### Minimal reproduction project

[shadowflicker.zip](https://github.com/godotengine/godot/files/13514642/shadowflicker.zip)

**Comment by HybridEidolon** [comment]
Issue is still present in 4.3 dev 1.

**Comment by HybridEidolon** [comment]
This is almost entirely resolved by 3be3d50 (#87340). Not sure if I should close and create a new one. The shadows only flicker very rarely when dragging the window around, and more frequently when resizing it.

**Comment by akien-mga** [comment]
Thanks for testing!

Opening a new issue for the remaining symptoms would be good.

Let's close this one as fixed by #87340.
