### ISSUE TITLE
FSR 2.2 Sharpness slider is counterintuitively, inverted

### ISSUE THREAD

**Issue by NatGazer** [godotengine/godot#85552]
### Godot version

4.2 stable

### System information

Windows 10 - Vulkan (Forward+) - RTX 3060 laptop - AMD Ryzen 5 5600H - 24GB RAM

### Issue description

That's it, counterintuitively, if the sharpness is set to 0, the image is crisp, if it's 2 the image is blurry:

FSR 2.2 Sharpness set to 0 (look at the wall bricks):
![image](https://github.com/godotengine/godot/assets/67602607/83209ac0-9dd9-43d0-b9f0-c38bf9a4af52)

FSR 2.2 Sharpness set to 2:
![image](https://github.com/godotengine/godot/assets/67602607/a228462a-213a-4808-866d-cc527bbd1e8f)

To be honest, this is almost unnoticeable. If you devs can make this parameter more noticeable that's something to consider. Anyway just having FSR 2.2 in Godot is awesome!

### Steps to reproduce

Turn on FSR 2.2 in `Project Settings -> Rendering -> Scaling 3D -> Mode ` then change `FSR Sharpness` slider

### Minimal reproduction project

Too simple to need one

**Comment by clayjohn** [comment]
0-2 was the recommended scale for FSR1. Once we merged FSR2 we didn't want to break compatibility so we are stuck using `0.0 (sharpest) to 2.0 (least sharp)`
See the docs: https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-scaling-3d-fsr-sharpness
