### ISSUE TITLE
[4.2] Export Window Sized outside of screen, cannot be resized when export template is selected

### ISSUE THREAD

**Issue by martin951** [godotengine/godot#85551]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

![{73902E40-48C8-4573-A9D8-F4075EDDB875}](https://github.com/godotengine/godot/assets/15638012/e3732b96-1897-4444-81b7-34fae14606b3)
![{4337DBCF-2184-445A-9A41-D82DE05FB55E}](https://github.com/godotengine/godot/assets/15638012/1885728f-4b0d-4505-9e2e-bb28990c3806)
![{D6BE09FD-C644-49CB-894F-71F550415ABD}](https://github.com/godotengine/godot/assets/15638012/999f7783-8e0f-41b9-b518-88b0f83bd87b)

### Steps to reproduce

Just converted my 4.1 project to 4.2, wanted to export immediately as the given project is just a gateway for my server.

### Minimal reproduction project

n/a

**Comment by martin951** [comment]
Fixed it by clicking "Sources", which allowed me to resize the window, had to scroll resize it multiple times until it fitted my screen, then went back to "Options" and now I can resize all export windows in other projects too.

**Comment by YuriSizov** [comment]
I can't reproduce it, so exact conditions are unknown. It's probably another sizing bug with the window's contents, but to debug it we would need to figure out how to make this repeatable.

**Comment by hakro** [comment]
I have been consistently getting this issue by doing the following, even on a completely blank project : 
- Go to `Project` > `Export...`
- Add a Linux export (no need to even download the templates)
- Go to `Resources`
- Change the `Export Mode` to `Export as dedicated server`
- The export screen gets huge, and when in `Single Window Mode` there is no way to access the buttons all the way down.

Work around : From the editor settings, disable the `Single Window Mode` setting. It becomes easier to resize the Export window. You'll need to drag the top of the window down several times to bring it to a reasonable size.

**Comment by shahriarlabib000** [comment]
I'm also facing this problem on Android. How to fix? I could use it just fine before
