### ISSUE TITLE
`NavigationServer2D.bake_from_source_geometry_data` handles obstructions improperly

### ISSUE THREAD

**Issue by spikeyarmaku** [godotengine/godot#85550]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX Vega (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I want to create a navmesh from code. The setup is this:
- A rectangle of size 100x100, starting at (0, 0), marking a traversable area
- Another rectangle of the same size, starting at (-20, -20), marking an obstacle

Both rectangles have the same winding.

**Expected result:** an L-shaped traversable area
**Actual result:** an empty navmesh

This is the code that is responsible for creating the navmesh:

```gdscript
func _ready():
    var rect1 = [Vector2(0, 0), Vector2(100, 0), Vector2(100, 100), Vector2(0, 100)]
    var rect2 = [Vector2(-20, -20), Vector2(80, -20), Vector2(80, 80), Vector2(-20, 80)]
    var src = NavigationMeshSourceGeometryData2D.new()
    var navpoly = NavigationPolygon.new()

    src.add_traversable_outline(rect1)
    src.add_obstruction_outline(rect2)
    NavigationServer2D.bake_from_source_geometry_data(navpoly, src)

    $NavigationRegion2D.navigation_polygon = navpoly
```

### Steps to reproduce

- Open the attached project
- Enable `Debug` -> `Visible navigation`
- Run the project

There is a Line2D surrounding the area where the navmesh should appear.

### Minimal reproduction project

[polygon2d_bug.zip](https://github.com/godotengine/godot/files/13514944/polygon2d_bug.zip)

**Comment by smix8** [comment]
Bakes just fine but with that size you really need to zoom out to see the navigation mesh in the bottom right corner.

**Comment by spikeyarmaku** [comment]
You're right. Turns out I forgot to switch "Visible navigations" on when I restarted Godot.

**Comment by smix8** [comment]
> Turns out I forgot to switch "Visible navigations" on when I restarted Godot.

Happens to the best of us.

**Comment by smix8** [comment]
Closing as issue seems to be solved, feel free to reply if it isn't.
