### ISSUE TITLE
Script editor get stuck when using double quote with US International Keyboard

### ISSUE THREAD

**Issue by ddelvall** [godotengine/godot#85566]
### Godot version

4.2.stable

### System information

Linux (Fedora 39) with US International Keyboard configured

### Issue description

When using  US international keyboard layout, pressing the keyboard key `"` (double quote) first shows the character ¨ (the one used for this: ö) and then a space is needed to convert it into double quote " character. If I try doing this the Script editor will hang and won't recover until Godot editor is restarted. It shows the following error message:

`"Caller thread can´t call this function in this node (/node). Use call_deferred() or call_thread_group() instead."`

If I try the other combination to do double quote (`Shift` + `Alt` + Key `"`) this won´t happen since the character " is created without passing though the character ¨.

Switching to Normal US keyboard layout works fine, but I've used 4.0 and 4.1 and I don´t think I ever got into this problem.

More information about using special characters with US International layout: https://superuser.com/a/1142932

### Steps to reproduce

1. Create a new project
2. Create a 2d (or 3d) scene
3. attack a script to the node
4. On any function (in my case _process) write the character " with your system configured with US international keyboard
5. A message will appear saying "Caller thread can´t call this function in this node (/node). Use call_deferred() or call_thread_group() instead."

### Minimal reproduction project

N/A

**Comment by ddelvall** [comment]
➜  ibus version
IBus 1.5.29-rc2

**Comment by ddelvall** [comment]
somehow this was fixed when I updated from 4.2 to 4.2.1. I just tested the old version again (to see if it was a problem with my linux distribution) and the problem is still there. So I guess this is no longer necessary.

**Comment by pcmxms** [comment]
Still happening here. 
I'm using Ubuntu 24.04. Before updating, it was working fine.
Steps to reproduce: Open godot and wherever you can input a text on, write "á" or "ã" or any other letter with accent.
