### ISSUE TITLE
PCK file encryption does not work in Godot Engine 4.2!

### ISSUE THREAD

**Issue by InkRobert** [godotengine/godot#85560]
### Godot version

4.2 stable

### System information

Windows 11 Pro

### Issue description

Today after numerous attempts to encrypt my PCK file - I came to the conclusion that either the system has changed a bit, or it's broken and not working properly!

The source code I used: https://github.com/godotengine/godot/tree/46dc277917a93cbf601bbcf0d27d00f6feeec0d5

The documentation I used: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_script_encryption_key.html
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html

After following the instructions exactly, I get one of two outcomes: 
1) Error stating that exe cannot open the pck file
![Снимок экрана 2023-11-30 164156](https://github.com/godotengine/godot/assets/91805483/08e9b257-785f-4d26-a5e7-c8d9d4fdcce4)

2) The application closes immediately after startup!
Logs:
[game2023-11-30T17.58.27.log](https://github.com/godotengine/godot/files/13516708/game2023-11-30T17.58.27.log)

I would also like to clarify that I did pck file encryption earlier on Godot Engine 4.1 and everything worked fine then, but now for some reason it doesn't work anymore.

Perhaps the encryption method has changed, in which case - please indicate where exactly I make a mistake.

### Steps to reproduce

1) Installation of Visual Studio (c++), Python 3.12, Scons latest version
2) Downloading Godot engine 4.2 Source Code
3) Using console in the folder with the source code enter the command "set SCRIPT_AES256_ENCRYPTION_KEY=my_generated_key"
4) Enter the command: "scons platform=windows target=template_release arch=x86_32"
5) In the export settings I specify the path to the export template
![Снимок экрана 2023-11-30 210641](https://github.com/godotengine/godot/assets/91805483/d95c5052-7a7e-405c-bbdc-a063d5e8df8f)
6) In the encryption setting, I enter my generated key, and other settings
![Снимок экрана 2023-11-30 210727](https://github.com/godotengine/godot/assets/91805483/3b932fc5-c2b3-4786-bac3-fcc67fb56308)
7) Export and get one of the errors  :)

### Minimal reproduction project

any project

**Comment by AThousandShips** [comment]
Are you using the command prompt or power shell?

**Comment by InkRobert** [comment]
> Are you using the command prompt or power shell?

command prompt and power shell

**Comment by AThousandShips** [comment]
And you are using the correct *different* syntax in power shell?

**Comment by InkRobert** [comment]
> And you are using the correct _different_ syntax in power shell?

Most likely, at least I did everything the same way I did in 4.1

**Comment by InkRobert** [comment]
Сonsole outputs: " editor/export/editor_export_platform.cpp:759 - Parameter "node" is null@"

**Comment by LimaneGaya** [comment]
I did a compilation of master last couple of days ago and everything worked fine for me. i only got first error you mentionned when i only compiled export template with encription and not the editor. also maybe it's a mismatch of the encription key between the editor and export template in the encription key?

**Comment by InkRobert** [comment]
> I did a compilation of master last couple of days ago and everything worked fine for me. i only got first error you mentionned when i only compiled export template with encription and not the editor. also maybe it's a mismatch of the encription key between the editor and export template?

I'm using the latest version of VS 2022, python 3.12, and SCons which I installed via python pip! Maybe I'm missing something important?

**Comment by LimaneGaya** [comment]
> I'm using the latest version of VS 2022, python 3.12, and SCons which I installed via python pip! Maybe I'm missing something important?

I'm using the same tools, i'm doing a compilation of the latest commit too see if there is an issue, it might take some time

**Comment by InkRobert** [comment]
> It works for me

Oh, can you describe what steps you take to properly create an export template?

**Comment by LimaneGaya** [comment]
Here are the steps i took to compile it.

- Getting and encription key aes-256-cbc from [here](https://asecuritysite.com/encryption/keygen)
- Opening powershell and pasting these next commands:
`$env:SCRIPT_AES256_ENCRYPTION_KEY="your_generated_key"`
`scons platform=windows`
`scons platform=windows target=template_release`
`scons platform=windows target=template_debug`

After compilation:

- Oppening the compiled version of godot editor located bin/godot.windows.editor.x86_64.exe
- Configure it to use the costom export templates you compiled in  bin/godot.windows.template_release.x86_64.exe and godot.windows.template_debug.x86_64.exe:
![Capture d'écran 2023-11-30 231414](https://github.com/godotengine/godot/assets/36268750/bafcd092-ff29-43f6-bb87-b2173ef81602)

- Configure it to use the encription: 

![Capture d'écran 2023-11-30 231725](https://github.com/godotengine/godot/assets/36268750/0fca0b4e-96ec-4eef-82ba-624367947a40)

**Comment by InkRobert** [comment]
> Here are the steps i took to compile it.
> 
> * Getting an encription key aes-256-cbc from [here](https://asecuritysite.com/encryption/keygen)
> * Opening powershell and pasting these next commands:
>   `$env:SCRIPT_AES256_ENCRYPTION_KEY="your_generated_key"`
>   `scons platform=windows`
>   `scons platform=windows target=template_release`
>   `scons platform=windows target=template_debug`
> 
> After compilation:
> 
> * Oppening the compiled version of godot editor located bin/godot.windows.editor.x86_64.exe
> * Configure it to use the costom export templates you compiled in  bin/godot.windows.template_release.x86_64.exe and godot.windows.template_debug.x86_64.exe:
>   ![Capture d'écran 2023-11-30 231414](https://private-user-images.githubusercontent.com/36268750/287085216-bafcd092-ff29-43f6-bb87-b2173ef81602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODY5NjksIm5iZiI6MTcwMTM4NjY2OSwicGF0aCI6Ii8zNjI2ODc1MC8yODcwODUyMTYtYmFmY2QwOTItZmYyOS00M2Y2LWJiODctYjIxNzNlZjgxNjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIzMjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NGQ4NTM4Mjk3OTgyZjA4ZDQyMzI0NTcxMTA1YTM0ZTFmMDAzZGM5ZjRmNWRiODUzN2Q1MDE4ODgxNGMyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhFOtg0bWRfA1e4-Jgjhrl43-KU_cUGK71htr2IIROw)
> * Configure it to use the encription:
> 
> ![Capture d'écran 2023-11-30 232205](https://private-user-images.githubusercontent.com/36268750/287086989-ab4a7bf3-8bed-4c92-9423-e1934fad968d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODY5NjksIm5iZiI6MTcwMTM4NjY2OSwicGF0aCI6Ii8zNjI2ODc1MC8yODcwODY5ODktYWI0YTdiZjMtOGJlZC00YzkyLTk0MjMtZTE5MzRmYWQ5NjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIzMjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZGE2ZjA1YTE5NGJhNmI2OWE2NjQ3MTFkYzZjMGY4MjJiY2FlZWJkMzA4ZDMzOTU3ZjNkZDkxZGQyNTEzNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qR9A0e07_lpyALlCvczD3KKbyhmumres74mrKHBTvJo)

OMG, it realy worked! I was sure I was doing the same thing, but maybe I was wrong somewhere. Thank you so much for helping me solve this problem 😁

**Comment by Keyvan-Rostyslav** [comment]
What can't be done more concisely and accessible, and without messing with all these commands? People 2024 is ending, or are we still living in 2009?

**Comment by Calinou** [comment]
> What can't be done more concisely and accessible, and without messing with all these commands? 

It needs to be done this way, as embedding the PCK encryption key requires recompiling an executable to make recovering the key nontrivial. (It's still possible though.)

If the key was stored besides the PCK, anyone would be able to recover it just by opening the file and figuring out what kind of encoding it uses.
