### ISSUE TITLE
GpuParticles2D jitter when scene tree is paused for various different ProcessMaterial properties

### ISSUE THREAD

**Issue by SamDevelopsCode** [godotengine/godot#85570]
### Godot version

4.2

### System information

Linux Mint 21.1 Vera

### Issue description

Issue is similar to #85213, #65390, #50824 

Pausing the scene tree while particles are emitting displays jittering behavior. The jittering occurs using **various different** ParticleMaterial properties. The minimal test project uses **tangential accel** as an example but turbulence and gravity show jitter as well.

![particle_test](https://github.com/godotengine/godot/assets/122749374/213701a7-0bee-4eb1-8ffa-eadd613a448f)

### Steps to reproduce

Open the project and click play and watch the particles jitter when the game pauses after 5.0 seconds.

### Minimal reproduction project

[ParticleTest.zip](https://github.com/godotengine/godot/files/13517817/ParticleTest.zip)

**Comment by catslanderer** [comment]
I asked about this in the forums before figuring out to come here:
https://forum.godotengine.org/t/gpuparticles2d-does-not-seem-to-fully-pause/36174

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/65390.
