### ISSUE TITLE
Animation Player fails to run script functions.

### ISSUE THREAD

**Issue by Leshy-YA** [godotengine/godot#85571]
### Godot version

4.2

### System information

Godot v4.1.stable - Fedora Linux 38 (KDE Plasma) - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

When creating an animation in the Animation Player that is to call a script function, the player will not run the function if it also has other tracks for the node that has the said script (meaning if tries to run function f() for node x, as well as change position of node x).

### Steps to reproduce

Create animation player.
Attach script to parent node.
Create test function.
Add animation track to the player calling the function.
Add animation track to the player changing the position of the parent node.

### Minimal reproduction project

[anim_bug.zip](https://github.com/godotengine/godot/files/13517976/anim_bug.zip)

**Comment by Leshy-YA** [comment]
I love the changes to 4.2, but until this is fixed, I'm stuck on 4.1.2 :/

**Comment by TokageItLab** [comment]
It might be same cause with #48526 #43848.
