### ISSUE TITLE
.NET Godot 4.2 crashes when upgrading project from 4.1.3

### ISSUE THREAD

**Issue by Dirt410** [godotengine/godot#85581]
### Godot version

4.2.stable.mono

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

Attempting to open a project in 4.2 that was last edited in 4.1.3 causes the editor to crash on the splash screen.

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/42548886/a6261449-c424-40d5-9eff-92d39d561075)
- Open Godot 4.2 and select project
- "This project was last edited in 4.1..." warning pops up and click OK
- A new Godot window with splash screen opens for a few seconds, then crashes.

### Minimal reproduction project

Don't know what causes it and not sure what to provide. Can provide entire C# project if needed.

**Comment by akien-mga** [comment]
Are you using godot-jolt by any chance? If so you need to upgrade it or remove it to open in 4.2, the old version is not compatible and crashes.

**Comment by Muini** [comment]
@akien-mga I had the same issue on macOS m1, upgrade godot-jolt fixed the issue ✨

**Comment by Dirt410** [comment]
Deleting Jolt from my project worked. Thanks.
