### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Oyama-Oyama** [godotengine/godot#85591]
### Godot version

4.2

### System information

mac 12.6.7

### Issue description

![截屏2023-12-01 16 08 09](https://github.com/godotengine/godot/assets/17978212/efbf4b89-8c71-469f-8497-2a9470973059)

### Steps to reproduce

an empty project export to android

### Minimal reproduction project

.

**Comment by akien-mga** [comment]
Please provide more information, there's nothing we can do with so little.

**Comment by Sauermann** [comment]
Thank your for your report. Without any feedback about how to replicate the problem, unfortunately it is not possible to investigate the problem. Closing this issue accordingly. When you can provide additional details, feel free to reopen this or create a new bugreport.
