### ISSUE TITLE
Should use raw string literal in `particle_process_material` instead of adding statements line by line

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#85595]
### Godot version

Godot v4.2.beta (5ee983188)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

As @akien-mga mentioned in https://github.com/godotengine/godot/pull/83881#issuecomment-1776812824, we can probably do some clean up in `particle_process_material.cpp` in 4.3

For example, change the code from :
```
code += "uniform vec3 direction;\n";
code += "uniform float spread;\n";
code += "uniform float flatness;\n";
code += "uniform float inherit_emitter_velocity_ratio = 0;\n";
code += "uniform float initial_linear_velocity_min;\n";
code += "uniform float initial_linear_velocity_max;\n";
code += "uniform float directional_velocity_min;\n";
code += "uniform float directional_velocity_max;\n";
```

to something like:

```
code += R"
uniform vec3 direction;
uniform float spread;
uniform float flatness;
uniform float inherit_emitter_velocity_ratio = 0;
uniform float initial_linear_velocity_min;
uniform float initial_linear_velocity_max;
uniform float directional_velocity_min;
uniform float directional_velocity_max;"
```

Not only it will improve code style, but also more importantly, it can reduce string operation times which can help reduce the shuttering when `ParticleProcessMaterial::_update_shader` is called.

But while changing this requires all other related pr to rebase on this one, so there is a question about when to do this.

### Steps to reproduce

Check `particle_process_material.cpp`

### Minimal reproduction project

N/A

**Comment by QbieShay** [comment]
Yes I think it'd be nice to wait 2 weeks or so to fix immediate bugs, then this can be done. I'm willing to coordinate but in this period I don't have time to refactor the whole class. Lmk if there's someome willing to do it

**Comment by jsjtxietian** [comment]
> Lmk if there's someome willing to do it

IMHO it won't have a huge impact as we just `compress` the code, so maybe I can help resolve this at the appropriate time.

**Comment by QbieShay** [comment]
ok thank you!
