### ISSUE TITLE
Godot 4.2 can't find nodes that exist in the AnimationPlayer.

### ISSUE THREAD

**Issue by TheFoxKnocks** [godotengine/godot#85598]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - 12th Gen Intel(R) Core(TM) i9-12900KF (24 Threads)

### Issue description

When transitioning my project from 4.1 to 4.2, my console is now spammed with errors like this:

`get_node: Node not found "EnemyAppear:frame" (relative to "/root/level1d/Entities/EnemySlime")`

`_update_caches: AnimationMixer: 'Spawning/appear', couldn't resolve track: 'EnemyAppear:frame'.`

The issue here is that the animation still plays just fine in-game. It also plays just fine in the editor. What it's complaining about not being able to find is not only there, but being used, so why is it complaining?

Context: The enemy (EnemySlime) is created in a scene (level1d) on the Entities layer. When being created, it plays an animation regarding it spawning in. This is where it's having a problem.

![animframe](https://github.com/godotengine/godot/assets/113346534/6aa8ea7f-c215-4db0-8e77-5ad87913d24a)

Yet it exists as it did in 4.1, it plays properly, everything works. What do I need to do to appease it?

### Steps to reproduce

Unsure.

### Minimal reproduction project

N/A

**Comment by samuelware** [comment]
I'm experiencing the a similar problem. although I didn't import a pre-existing project into 4.2. I created my animations and they worked, and at some point I ended up deleting my AnimationPlayer's and recreating them in the same scene. The animations still work, but I'm getting similar errors, but with old node paths (that don't exist anymore). I think the old AnimationPlayer details could be lingering in the scene file, leading to the error.

**Comment by TokageItLab** [comment]
Related by https://github.com/godotengine/godot/issues/85316

**Comment by TheFoxKnocks** [comment]
Issue persists with 4.2.1, though I don't know if the goal was to have it fixed that soon to begin with. Wanted to mention it is all.

**Comment by chamons** [comment]
I've tried to reproduce it in a smaller project and have failed.

I can share privately shared a moderate sized project that reproduces it 100% of the time (many times in a row) if that is helpful.

**Comment by GGalizzi** [comment]
Here's a minimal repro project, though unlike the OP, the animation does not play at all - v4.2.1.stable.official [b09f793f5]

Animation plays if I do it through animation player editor in-editor. But play game and you'll see the errors popup when the animation attempts to play.

[AnimPlayerIssue.zip](https://github.com/godotengine/godot/files/14143393/AnimPlayerIssue.zip)

```
E 0:00:03:0930   get_node: Node not found: "StatUI/increase:visible" (relative to "/root/Control").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1638 @ get_node()
E 0:00:03:0930   _update_caches: AnimationMixer: 'pop', couldn't resolve track:  'StatUI/increase:visible'.
  <C++ Source>   scene/animation/animation_mixer.cpp:635 @ _update_caches()
```

**Comment by TheFoxKnocks** [comment]
This just spammed my console so hard it ran memory usage up to over 9,000MB and basically crashed my editor and most certainly totally lagged out the game I was playtesting. Seems like this issue can also happen live. Any news on when this might be fixed? Using 4.3dev2, so doesn't seem like it's going to be fixed there, either.

**Comment by OmarRinaz** [comment]
> Here's a minimal repro project, though unlike the OP, the animation does not play at all - v4.2.1.stable.official [[b09f793](https://github.com/godotengine/godot/commit/b09f793f564a6c95dc76acc654b390e68441bd01)]
> 
> Animation plays if I do it through animation player editor in-editor. But play project and you'll see the errors popup when the animation attempts to play.
> 
> [AnimPlayerIssue.zip](https://github.com/godotengine/godot/files/14143393/AnimPlayerIssue.zip)
> 
> ```
> E 0:00:03:0930   get_node: Node not found: "StatUI/increase:visible" (relative to "/root/Control").
>   <C++ Error>    Method/function failed. Returning: nullptr
>   <C++ Source>   scene/main/node.cpp:1638 @ get_node()
> E 0:00:03:0930   _update_caches: AnimationMixer: 'pop', couldn't resolve track:  'StatUI/increase:visible'.
>   <C++ Source>   scene/animation/animation_mixer.cpp:635 @ _update_caches()
> ```
> 
> edit: Fixes itself after I delete the `AnimationPlayer` node and recreate it (along with the animation)

At first, I deleted the nodes that were missing on the animations so the track wouldn't pop up any errors, but this didn't fix the 3d animations and skeletons, so I tried to rebuild everything, and no more errors.

What I had to do was delete everything, and build it from scratch, animation imports, skeleton profiles, animation libraries, and animation players and it took out the errors, it seems that the retargeting wasn't working... or something weird happened jumping versions, from 4.1 to 4.2 is when it started popping like crazy.

**Comment by joshuaandrewhoffman** [comment]
The issue persists with 4.2.2 -- It seems the same for me as other commenters:

- manifests upon upgrade from 4.1.x
- 100% reliable repro
- errors do not actually break functionality in-game

I tried poking at it with some basic things like:
- modifying a problem animation re-running, and checking error count
- deleting a problem animation, running, restoring the animation with git, and re-running

Unless there's something cached somewhere that I couldn't find, I don't know of any other way to fix this besides deleting all of the animations and remaking them, as Omar suggests above.

**Comment by akien-mga** [comment]
@TokageItLab Did #86608 solve this issue for 4.3 by any chance? If so, should it be cherry-picked?

**Comment by TokageItLab** [comment]
Close as it should be fixed in 4.3.

**Comment by sabslikesobs** [comment]
I ran into this today in 4.3. Isn't there some better solution than "turn off the warnings?" Is the issue really closed with _that_ as the fix?

**Comment by TokageItLab** [comment]
@sabslikesobs 
![image](https://github.com/user-attachments/assets/d5f4200c-98b7-47f4-8d91-639b85e9e74c)

**Comment by sabslikesobs** [comment]
Yes, I know of the setting to turn off the warnings. I'm asking: is the final solution for this problem going to be "just turn off the warnings if you get a lot of warnings?" I've seen a lot of instability in Godot, and seeing this kind of band-aid fix is disappointing.

**Comment by TokageItLab** [comment]
If the cache is actually corrupt, that is a different problem and you can send a new issue with MRP.

**Comment by sabslikesobs** [comment]
Okay, so Godot can randomly fuck up any user's animations for mysterious reasons, incur a frustrating debugging session, and the permanent solution is to turn off the warnings that Godot's fuckup generates, thus losing whatever value the warnings had. Good to know.

**Comment by TokageItLab** [comment]
Since the cache in .godot should have nothing to do with the cache that AnimationMixer dynamically generates, I would expect that it is actually the importer that is the problem in your case.

**Comment by Proggle** [comment]
> Close as it should be fixed in 4.3.

Seeing this error pop up after editing an animation in v4.3.stable.official [77dcf97d8].  Animations I made under 4.2 don't throw errors in 4.3, so it isn't just a version update conversion problem.

**Comment by berarma** [comment]
This happens still with 4.3 and it's not an updated project. Reloading the project fixed it but that's not an ideal solution. The error recommends disabling the warnings, but that's not a solution, it's a dirty workaround.

**Comment by Videonoises** [comment]
> This happens still with 4.3 and it's not an updated project. Reloading the project fixed it but that's not an ideal solution. The error recommends disabling the warnings, but that's not a solution, it's a dirty workaround.

I was trying to figure out why this was happening to me and you're totally right, restarting the project stopped the errors popping up.

**Comment by jedomed** [comment]
> This happens still with 4.3 and it's not an updated project. Reloading the project fixed it but that's not an ideal solution. The error recommends disabling the warnings, but that's not a solution, it's a dirty workaround.

I wanna add that this still happens in 4.4.1. I wasn't migrating between Godot versions or anything like in the OP, it just randomly started happening while I was working on a scene. Reloading the project fixed it.

**Comment by IntangibleMatter** [comment]
Running into this in 4.6.1

**Comment by jedomed** [comment]
> > This happens still with 4.3 and it's not an updated project. Reloading the project fixed it but that's not an ideal solution. The error recommends disabling the warnings, but that's not a solution, it's a dirty workaround.
> 
> I wanna add that this still happens in 4.4.1. I wasn't migrating between Godot versions or anything like in the OP, it just randomly started happening while I was working on a scene. Reloading the project fixed it.

Just got this warning again in 4.7.2. I don't know how it happened but I noticed the AnimationPlayer's "Root Node" was set to "../..", after resetting it and fixing the node paths (I opened the .tscn file and edited it there, it's way faster than fixing it in Godot) the warning disappeared.

<img width="337" height="50" alt="Image" src="https://github.com/user-attachments/assets/59287bbb-913d-45ed-9cac-ee760505287d" />
