### ISSUE TITLE
Light2D with shadows enabled near an occluder displays errors instead of shadows

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8560]
**Ubuntu 17.04 - Godot version: 3 master**
Using Nvidia 375.39 drivers.

**Issue description:**
Light2D starts spamming "meseges" when shadow is enabled and a LightOccluder2D is in range.
This happens in editor.

**Steps to reproduce:**
 - Create a LightOccluder2D.
 - Add a Light2D with the occluder in range.
 - Enable shadows on the Light2D.
 - Watch the terminal output get eclipsed by meseges.

--------------

The message spammed when turning shadows in editor is:
```
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 1282Severity: High	Message: GL_INVALID_OPERATION error generated. Array object is not active.
   At: drivers/gles3/rasterizer_gles3.cpp:123.

```

------------------

Turning on the shadow while running got an extra error sometimes between the other:
```
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Error	ID: 1282Severity: High	Message: GL_INVALID_OPERATION error generated. Invalid VAO/VBO/pointer usage.
   At: drivers/gles3/rasterizer_gles3.cpp:123.

```

--------------------

And this error too but saw it while running other things (sometimes while opening the editor) so I guess it is not related
```
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Performance	ID: 131218	Severity: Medium	Message: Program/shader state performance warning: Vertex shader in program 4 is being recompiled based on GL state.
   At: drivers/gles3/rasterizer_gles3.cpp:123.

```

**Comment by Zireael07** [comment]
"mesege" :D :D :D
