### ISSUE TITLE
RegEx not behaving as expected with positive lookahead

### ISSUE THREAD

**Issue by emil-nasso** [godotengine/godot#85605]
### Godot version

4.2.stable

### System information

Linux mint, up to date

### Issue description

The `RegEx` feature doesn't seem to behave as expected with positive lookahead.

### Steps to reproduce

Run this GDScript:

```
print_debug(len(RegEx.create_from_string(r'(?=(\d+))').search_all('12')))
```

I would expect this to print `2` but only one match is made.

The same regex can be tried here, and returns two results (as expected):
https://regex101.com/r/M0IUjQ/1

### Minimal reproduction project

`print_debug(len(RegEx.create_from_string(r'(?=(\d+))').search_all('12')))`

**Comment by MrBlockers** [comment]
It seems to me like this is correct behavior based on docstring for [search_all](https://docs.godotengine.org/en/stable/classes/class_regex.html#class-regex-method-search-all). 

> Searches the text for the compiled pattern. Returns an array of [RegExMatch](https://docs.godotengine.org/en/stable/classes/class_regexmatch.html#class-regexmatch) containers for each non-overlapping result. If no results were found, an empty array is returned instead.

Looking at the code, too, it seems like it's doing what it says on the tin. Maybe this could be added as an optional parameter (e.g. allow_overlaps) ?

**Comment by TheSofox** [comment]
Found the problem. Essentially 'search_all' wasn't handling zero length matches very well. Created a pull request that should fix the issue.

**Comment by emil-nasso** [comment]
@TheSofox Great find! Nice work! Thanks. :heart:
