### ISSUE TITLE
Meshes are not reimported on other developers machines after upgrade to 4.2

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#85607]
### Godot version

4.2

### System information

Windows 10

### Issue description

We upgraded our project from 4.1 to 4.2. And even though I ran the mesh surface fixer tool locally and commited all the changes, other developers on the team get this warning:

```
WARNING: At least one surface uses an old surface format and needs to be upgraded. The upgrade happens automatically at load time every time until the mesh is saved again or re-imported. Once saved (or re-imported), this mesh will be incompatible with earlier versions of Godot.
```

It seems the meshes are not reimported. Deleting the .godot folder fixed the issue.

### Steps to reproduce

- Upgrade a project from 4.1 to 4.2 (with meshes)
- Push changes to git
- Other developers that had worked on the project with 4.1 before will get warnings about surface format changes

### Minimal reproduction project

-

**Comment by 0x0ACB** [comment]
Yeah I figured, its not a huge issue anyways. But I think it might be a good idea to change the .import file on such changes. This should force a reimport on other developers machines. Atleast I would expect that.

**Comment by akien-mga** [comment]
That's not a feature currently indeed. See #60730.

#84974 might solve it.

I don't think we'll do more tweaks specifically for the 4.2 mesh compression change, deleting `.godot` or triggering the one-time conversion on each copy of the project source is doable as a one-time thing.

The part about changing import files not triggering a reimport is already tracked in #60730, so I think we can close this one.

**Comment by YuriSizov** [comment]
Also keep in mind that these were default values which had been added to the file. The reimport can only happen if a difference is detected, but here we would be unable to recognize that anything is different, I think.
