### ISSUE TITLE
AnimationTree's own libraries are duplicated when borrowed from an inherited (or editable) scene's AnimationPlayer

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#85602]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Windows 10

### Issue description

As previously mentioned on [RocketChat](https://chat.godotengine.org/channel/animation?msg=9HxXLyQ9KFTukNXTW).

Good, now **AnimationMixer** exists.

But, when combining the **AnimationPlayer** with an **AnimationTree**, the **AnimationTree** may store duplicates of the very same **AnimationLibrary**s for seemingly no reason. This happens specifically when the **AnimationTree** comes from an inherited or otherwise editable scene.

Note that editing the duplicate **AnimationLibrary**s works only temporarily and they WILL be overridden by the original source (the **AnimationPlayer**).

This is especially bad in any actual project because you may have many, many animations. It's _beyond awful_ if your animations are imported from GLTF because-
<img height=256px src="https://i.gyazo.com/9252d988ec27d86fedbd2184c82f064a.gif"/>

It seems like https://github.com/godotengine/godot/pull/85575 (@TokageItLab) would solve this, but more testing may be required to prevent it from spectacularly back-firing in some yet another unforeseen circumstance.

### Steps to reproduce

- Create a scene with an **AnimationPlayer** and at least one animation;
- Create an inherited scene from this one, and add an **AnimationTree**;
- Associate the AnimationTree with this **AnimationPlayer**;
- Look at the saved `.tres` files. You may notice that both the inherited scene also contains the animations for no reason.

![image](https://github.com/godotengine/godot/assets/66727710/c69b6161-36e3-43e9-ba4c-c6b8ff93c72a)

### Minimal reproduction project

[AnimationTree Duplication.zip](https://github.com/godotengine/godot/files/13523845/AnimationTree.Duplication.zip)

**Comment by YuriSizov** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/85575. Please let me know if it's still reproduceable, and then we can reopen it.
