### ISSUE TITLE
Tilemap expanded collision editor not editing tile collision

### ISSUE THREAD

**Issue by Large-Guy** [godotengine/godot#85611]
### Godot version

4.2

### System information

Godot v4.2.stable.mono - macOS 12.6.5 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When expanding collision editor and resetting to default shape, changes to the collision shape are applied.
<img width="741" alt="Screen Shot 2023-12-01 at 8 58 32 AM" src="https://github.com/godotengine/godot/assets/82416583/24e5f90d-99f3-480b-a5db-140eb6642cb6">

### Steps to reproduce

1. Create a tile
2. Go into the select menu
3. Expand the collision shape editor
4. Reset to default shape
5. Edit the shape (Edited shape will not be applied)

### Minimal reproduction project

N/A

I don't think a project is required to reproduce this, as it is quite simple. 

PS. This is my first issue that I've ever written so I hope I did it right.

**Comment by KoBeWi** [comment]
Closing in favor of #86720, which is more detailed.
