### ISSUE TITLE
Crash when renaming folder in FileSystem view panel

### ISSUE THREAD

**Issue by vettes86** [godotengine/godot#85617]
### Godot version

4.1.3 stable

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GT 750M () - Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 Threads)

### Issue description

Crash when renaming folder in FileSystem view panel.

### Steps to reproduce

Could not reproduce reliably; appears randomly.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can someone still replicate this?

**Comment by AThousandShips** [comment]
Closing due to lack of response, assuming fixed, if someone can still replicate this please comment
