### ISSUE TITLE
Local to Scene doesn't work when inside exported arrays

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot#85614]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 Ti with Max-Q Design (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

If I create a custom resource that has some runtime-mutable state (that is, the game modifies the resource during gameplay), and then store that resource in an Array used by multiple subscenes in my main scene, the mutable state ends up shared, _even if_ Local to Scene is checked. If the resource is top-level instead of inside an Array, it works as expected (unshared).

Unexpected sharing of state between instances:

https://github.com/godotengine/godot/assets/10625/2252bac5-8926-4c42-901f-c04769f09e97

---

What I'm looking for:

1. Is this a bug, or is this by design?
2. If it's by design...should it be by design? I think we know this area's a bit confusing already https://github.com/godotengine/godot-proposals/issues/1848
3. If it's not a bug and it's definitely by design, can we document this behavior somewhere? [Local to Scene](https://docs.godotengine.org/en/stable/tutorials/scripting/resources.html) isn't even mentioned in the Resources tutorial, but some kind of best practice callout should probably be added here. Either "be careful when using Resources in Arrays" or "avoid mutable state inside Resources"?

### Steps to reproduce

1. Create a custom resource. It should have at least one field modified by the game at runtime, e.g. a checkbox to indicate whether the animation it represents has completed.
2. Store this resource in an Array on a scene.
3. Write a script and attach to the scene that uses the resource.
4. Instantiate this scene multiple times and add it to the main scene.
5. Observe that the mutated state is shared across all instances.

For the attached project, just run the main scene, then click on the first image, then the second image.

### Minimal reproduction project

[LocalToScene_GD.zip](https://github.com/godotengine/godot/files/13528251/LocalToScene_GD.zip)

I've attached a simple project where there's a stateful animation resource that's in an array shared by two instances. Because I've chosen `Resource > Local to Scene` for the AnimNames resource (and tried `Make Unique` on that resource for good measure), I expect the AnimNames resource to be fully independent between the two images. But it's actually shared.

What I expect the behavior to be when clicking on the images:

https://github.com/godotengine/godot/assets/10625/0e69c0d3-5061-425e-a674-2da4e3daa8ca

What actually happens when clicking on different instances. The jerking behavior is because it's unexpectedly playing the wrong animation.

https://github.com/godotengine/godot/assets/10625/2252bac5-8926-4c42-901f-c04769f09e97

**Comment by nanodeath** [comment]
```diff
# my_area.gd

# ...

func _ready():
	input_event.connect(clicked)
	animation_player.animation_finished.connect(anim_done)
+	anim_names = anim_names.duplicate()
+	anim_names.assign((anim_names.map(func(anim_name): return anim_name.duplicate())))
```

This change makes the Resources work as I would expect.

**Comment by RedMser** [comment]
This is indeed a bug. Duplicate of #71243

**Comment by nanodeath** [comment]
Does indeed seem like a dupe. Thanks @RedMser.
