### ISSUE TITLE
Text to speech on windows is not working on godot 4.1 and 4.2

### ISSUE THREAD

**Issue by kppaiboo** [godotengine/godot#85613]
### Godot version

4.1 and 4.2

### System information

Windows 11

### Issue description

I use these this script in "func ready"
        # One-time steps.
	# Pick a voice. Here, we arbitrarily pick the first English voice.
	var voices = DisplayServer.tts_get_voices_for_language("en")
	var voice_id = voices[0]

	# Say "Hello, world!".
	DisplayServer.tts_speak("Hello, world!", voice_id)

	# Say a longer sentence, and then interrupt it.
	# Note that this method is asynchronous: execution proceeds to the next line immediately,
	# before the voice finishes speaking.
	var long_message = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur"
	DisplayServer.tts_speak(long_message, voice_id)

	# Immediately stop the current text mid-sentence and say goodbye instead.
	DisplayServer.tts_stop()
	DisplayServer.tts_speak("Goodbye!", voice_id)

and it show this in line "var voice_id = voices[0]"
![Screenshot 2023-12-01 221233](https://github.com/godotengine/godot/assets/30397310/22a13df6-6412-4bff-8cb3-8f56758d7fa8)

### Steps to reproduce

1. Create new scene
2. Add script to scene
3. Add this code to script

func _ready():
	text_to_speech()

func text_to_speech():
	# One-time steps.
	# Pick a voice. Here, we arbitrarily pick the first English voice.
	var voices = DisplayServer.tts_get_voices_for_language("en")
	var voice_id = voices[0]

	# Say "Hello, world!".
	DisplayServer.tts_speak("Hello, world!", voice_id)

	# Say a longer sentence, and then interrupt it.
	# Note that this method is asynchronous: execution proceeds to the next line immediately,
	# before the voice finishes speaking.
	var long_message = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur"
	DisplayServer.tts_speak(long_message, voice_id)

	# Immediately stop the current text mid-sentence and say goodbye instead.
	DisplayServer.tts_stop()
	DisplayServer.tts_speak("Goodbye!", voice_id)

4. Run scene
![Screenshot 2023-12-01 221233](https://github.com/godotengine/godot/assets/30397310/21f7449f-2eca-4808-b9ec-ecafbbc80f05)

### Minimal reproduction project

[Read_Text_Click_n_Read.zip](https://github.com/godotengine/godot/files/13528278/Read_Text_Click_n_Read.zip)

**Comment by bruvzg** [comment]
- Check if `audio/general/text_to_speech` project setting is enabled (and restart editor after setting it), by default TTS is disabled to avoid unnecessary overhead.
- Check output of `print(DisplayServer.tts_get_voices())`, voices for the specific language might be missing.

**Comment by kppaiboo** [comment]
As "bruvzg" described above, when I enable the "audio/general/text_to_speech" in Project Settings... It works.
![Screenshot 2023-12-05 085440](https://github.com/godotengine/godot/assets/30397310/4a5cc74a-71b6-41a8-a416-f91610ea572f)
![Screenshot 2023-12-05 090042](https://github.com/godotengine/godot/assets/30397310/b0bfcf31-b7d1-4d07-92d4-fd32427442ec)

**Comment by nightblade9** [comment]
Same problem here, and the same solution. I'll update the docs to add this to the instructions.
