### ISSUE TITLE
Player isn't colliding with scene tiles when they aren't visible.

### ISSUE THREAD

**Issue by dragon3025** [godotengine/godot#85625]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 630 (Intel Corporation; 31.0.101.2111) - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

I have a tileset that disables its visibility during it's `_ready()` function. The tileset is made up of scene tiles. I didn't have a problem with this until recently I discovered my player goes right through the tiles unless they're visible. This didn't happen before, it could be something to do with the 4.2 update.

### Steps to reproduce

In my minimal reproduction project I removed the script that disables the tileset's visibility.

- Run the game with the tileset visible and use wasd keys to move downward. The tileset should block the player (it's using `move_and_slide()`).
- Run the game with the tileset non-visible and use wasd keys to move downward. The tileset isn't block the player.

### Minimal reproduction project

[Bug Demo.zip](https://github.com/godotengine/godot/files/13531278/Bug.Demo.zip)

**Comment by kleonc** [comment]
Seems like a variation of #83499 but for scene tiles. cc @groud

Tested in v4.1.3.stable.official [f06b6836a] and both atlas/scene tiles have collision in there when hidden, hence that's a regression.
