### ISSUE TITLE
Rendering Baked LightmapGI 8 objects at once limit (Editor/Playing)

### ISSUE THREAD

**Issue by vgapchynski** [godotengine/godot#85630]
### Godot version

4.1.3 - 4.2 stable

### System information

Windows 11, Forward + / Mobile

### Issue description

I created 1 scene with simple box model from blender. Then add Omnilight3D and LightmapGI, baked scene. If you add more than 8 rooms in render, only 8 rooms will have lighting, all other rooms will be dark. This problem is reproduced in Edit and in "Playing"
Looks like there is some limit or something similar to this, but I can't find anything.
I made a simple project with 3d blender model and prepared problem, here is a screenshot:
![image](https://github.com/godotengine/godot/assets/32371251/c0491819-d515-4163-8951-af5a283c1ae1)

### Steps to reproduce

1. Create simple box (I used blender model). Update import setting for .blend file and set "Light Baking" to "Static Lightmaps"
2. Add light source (I added Omnilight3D). Set "Bake mode" to "Static"
3. Add LightmapGI and bake scene, then turn off Omnilight3D. Lighting should be presented only because of baked lightmap
4. Create new scene, add 8 instances of room. Everything is fine, all rooms have lighting
5. Add more than 8 rooms, and now only 8 rooms at once will be lighted. You can see it even in Editor. If you move your camera closer to dark rooms, they will be lighted, but some of other rooms will be in dark.

### Minimal reproduction project

[lightmapGI.zip](https://github.com/godotengine/godot/files/13532030/lightmapGI.zip)

**Comment by Calinou** [comment]
This is expected, as there's a limit of 8 LightmapGI instances that can be drawn at once on screen. [VoxelGI also has the same limitation.](https://github.com/godotengine/godot/issues/80361)

**Comment by vgapchynski** [comment]
@Calinou thank you for your answer! I'm interested in your solution related to 3d modeling software, as I understand, I can make baking in Blender and get already baked texture for my room and import room+texture in Godot, and with this approach I can get the same result as using baking/lightning in Godot, but without any limits, right?

**Comment by Calinou** [comment]
> as I understand, I can make baking in Blender and get already baked texture for my room and import room+texture in Godot, and with this approach I can get the same result as using baking/lightning in Godot, but without any limits, right?

Yes, that's the idea :slightly_smiling_face: Note that you won't need to use any LightmapGI nodes in this case.

**Comment by bitsawer** [comment]
Closing as the documentation update was implemented in https://github.com/godotengine/godot-docs/pull/8641. Looks like the PR missed the correct Github autolink syntax to this second issue.
