### ISSUE TITLE
AnimationNodeStateMachinePlayback.travel() gets stuck for nested state machines

### ISSUE THREAD

**Issue by Maaack** [godotengine/godot#85640]
### Godot version

4.2

### System information

Linux

### Issue description

A nested state machine isn't traveling to its animation in `_ready()` in 4.2 as it was in 4.1.3.

In the ready function, we make the `root` state machine travel to the state of the `Stages` nested state machine. Then we immediately call the `Stages` nested state machine to travel to `Stage2`. This works fine in Godot v4.1.3, but not in Godot v4.2, where it seems a delay is first needed for the second travel animation to work.

![image](https://github.com/godotengine/godot/assets/788630/f1582a99-a68e-45d9-82b8-8367e62a9cba)
![image](https://github.com/godotengine/godot/assets/788630/c7c1f9fa-c78b-4259-bd36-81ebd8cef9aa)

### Steps to reproduce

Run the MRP below in 4.1.3 and 4.2.

In 4.1.3, the animation tree will reach `Stage2` and show Finished on the screen.

In 4.2, the animation tree will only reach `Stage1` and show Stuck on the screen.

### Minimal reproduction project

[MRP-AnimationNodeStateMachinePlayback.zip](https://github.com/godotengine/godot/files/13533132/MRP-AnimationNodeStateMachinePlayback.zip)

**Comment by Maaack** [comment]
This could be related to https://github.com/godotengine/godot/issues/85600 ?

**Comment by TokageItLab** [comment]
As a result, it is due to a missing test_only flag by porting that caused the travel path to be generated in situations where it should not have been. This will be fixed https://github.com/godotengine/godot/pull/85794.
