### ISSUE TITLE
Instantiate

### ISSUE THREAD

**Issue by meinwaffe** [godotengine/godot#85655]
### Godot version

4.1.1

### System information

Godot 4.1.1

### Issue description

The instantiate isn't working

### Steps to reproduce

whats the replacement for this action?

### Minimal reproduction project

adassdaas

**Comment by YuriSizov** [comment]
Please use one of our [community channels](https://godotengine.org/community/) for support questions. If you have an actual bug report, please fill out the template diligently and provide a reproduction project.
