### ISSUE TITLE
Mouse Pickable on Area2D doesn't work on SubViewport (broke my game from 4.1 to 4.2)

### ISSUE THREAD

**Issue by stebulba** [godotengine/godot#85659]
### Godot version

4.2-stable

### System information

Ubuntu 22.04

### Issue description

- Mouse Pickable on Aera2D doesn't work on SubViewport.
- Godot 4.2 Broke my game after moving from 4.1
The problem look already exist https://github.com/godotengine/godot/issues/84258
But this new release did not seem ready for deployment, which is why I reported it as a new issue. At the very least, it is necessary to include this issue in the release information under **Critical and Breaking Changes.**

Also the `$SubViewportContainer.set_default_cursor_shape(Input.CURSOR_POINTING_HAND)` doesn't work anymore on 4.2.

### Steps to reproduce

make sure mouse_pickable is true on Aera2D
![image](https://github.com/godotengine/godot/assets/26193340/e244e1ab-a2b2-4355-bde5-7c743a52d80d)

### Minimal reproduction project

[Mouse_pickable-subviewport-4.2.zip](https://github.com/godotengine/godot/files/13536462/Mouse_pickable-subviewport-4.2.zip)

**Comment by AThousandShips** [comment]
Please open *one* report for *one* issue, the second of your issues already has a report so there's no need to open a new one

**Comment by Sauermann** [comment]
The two issues, that you describe are already reported:
- #84258
- #84810

Consolidating as duplicate with these dedicated bug-reports.

**Comment by stebulba** [comment]
> Consolidating as duplicate with these dedicated bug-reports.

My main point is that there is no release information addressing these well-known issues that completely break compatibility. Closing my duplicate without modifying [the godot release page](https://godotengine.org/article/godot-4-2-arrives-in-style/) doesn't help anyone. On the contrary, game developers will waste their time duplicating the issues again.

**Comment by AThousandShips** [comment]
This should be tracked in the respective issues or the original PRs instead IMO, this is still two different, unrelated issues

**Comment by stebulba** [comment]
I agree with you regarding the second issue. I have, in fact, adjusted the title accordingly. It's not the first time I've wasted a lot of time diagnosing a bug that already existed. In this case, the problem stems primarily from an early release of version 4.2 or simply a lack of information in the release notes.

**Comment by AThousandShips** [comment]
Then there's no need for this, as only one of the issues has this concern, so this is still a duplicate, and 4.2 was not released too early, but additional notes would be useful

**Comment by AThousandShips** [comment]
> It's not the first time I've wasted a lot of time diagnosing a bug that already existed.

**Comment by stebulba** [comment]
> and your opinion that 4.2 was released prematurely, but to me it's not constructive to make an issue report for these reasons

My opinion is NOT the reason of my post. A real issue is existing.
The release talk about Viewport mouse handling work from [Markus Sauermann](https://github.com/Sauermann)
How can we know that the bug I got is an old bug since the release is supposed to be functional?
If there is an existing old tracking about this bug, for general users, this looks like a new bug separate of the old tracking. And if this bug is not reported after the release of version 4.2, the confusion persists.
The main issue is the lack of information in the release notes. With more information, I wouldn't have downloaded this version.
I think my post can do the job for now. When this lack is fixed, for sure my post can be close.

I hope it is understandable.

**Comment by AThousandShips** [comment]
> If there is an existing old tracking about this bug, for general users, this looks like a new bug separate of the old tracking.

That's not helpful, we can't make new bug reports for all bugs found during 4.2 development once 4.2 releases, it says it's for 4.2 in the description

But sure, we can keep this open, but I'd suggest in the future to comment on the existing bug report to suggest this instead of adding extra bug reports for the same issue, adding work for bug triagers and clutter
