### ISSUE TITLE
calling TreeItem set_text() on a TreeItem that was removed via remove_child() causes debugging to end without any error message

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#85650]
### Godot version

4.2 Stable

### System information

Linux

### Issue description

Calling TreeItem set_text() on a TreeItem that was removed via remove_child() causes debugging to end and the application to close without any error message.

### Steps to reproduce

Run the included example to get the debugger to crash. Comment out "treeItem.remove_child(subTreeItem)" for normal behaviour. 

### Minimal reproduction project

[treeItemCrash.zip](https://github.com/godotengine/godot/files/13534005/treeItemCrash.zip)

**Comment by kleonc** [comment]
It crashes here:
https://github.com/godotengine/godot/blob/d76c1d0e516fedc535a2e394ab780cac79203477/scene/gui/tree.cpp#L310
https://github.com/godotengine/godot/blob/d76c1d0e516fedc535a2e394ab780cac79203477/scene/gui/tree.cpp#L72-L74

**Comment by AThousandShips** [comment]
A check in either place should be sufficient, possible leftover from allowing handling items without a tree and the previous assumption tree items were always in a tree

**Comment by AThousandShips** [comment]
That's not the error position, the tree is null, so it crashes when it calls the method on tree

**Comment by rsubtil** [comment]
> That's not the error position, the tree is null, so it crashes when it calls the method on tree

Yeah my bad, I failed to notice `tree` was null before going into this call :+1:
