### ISSUE TITLE
Scons generate vsproject don't work

### ISSUE THREAD

**Issue by njikmf** [godotengine/godot#85651]
### Godot version

4.2branch

### System information

Win10

### Issue description

![image](https://github.com/godotengine/godot/assets/96371060/e1fdc181-4a21-4742-8bbc-2ea2cdbd20ea)

As you see... it don't generate vs project files, and continue to compile code... ???

### Steps to reproduce

Clone 4.2 branch.
Install Scons
>scons vsproj=yes p=windows

### Minimal reproduction project

None

**Comment by akien-mga** [comment]
It's working as designed currently, it generates the vsproj files *and* compiles. There's ongoing work to rework this option and make it only generate the project with first compiling, but currently this is not a bug.
