### ISSUE TITLE
Anchor presets positions don't adapt to changed scale of object

### ISSUE THREAD

**Issue by AriBarzilai** [godotengine/godot#85668]
### Godot version

v4.1.3.stable.mono

### System information

Godot v4.1.3.stable.mono - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12042.2002) - AMD Ryzen 5 7520U with Radeon Graphics (8 Threads)

### Issue description

The anchor presets fail to take into account the new size of a node after changing it via scale, leading to things like the "center" preset anchor being off-center and often cut off the screen. 

### Steps to reproduce

Create a node. Change its scale. Set anchor preset to 'center' in the inspector

### Minimal reproduction project

Create new project. Create a node (and, for example, set its size to be the size of your viewport).
Now change its scale (for example, to scale 0.8, or to 1.5).
Set an anchor preset in the inspector (for example, set to anchor preset 'center')

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/19068.
