### ISSUE TITLE
AnimationTree BlendSpace2D node not working

### ISSUE THREAD

**Issue by Verszem** [godotengine/godot#85670]
### Godot version

4.2

### System information

Windows 10

### Issue description

I was using this AnimationTree BlendSpace2D node to strafe my running animation. It worked perfectly in the older version but as soon as I updated Godot the animation's directions are like random, and doesn't match the move_input(). When I print out the move_input it is perfect, and when I try to move the little cursor in the Node it works too.

### Steps to reproduce

```gdscript
move_input = Input.get_vector("balra","jobbra","hátra","előre")
strafe_dir += move_input.x* global_transform.basis.x;
strafe_dir -= move_input.y * global_transform.basis.z;
dir += move_input.x*head.global_transform.basis.x;
dir -= move_input.y*head.global_transform.basis.z;
velocity = lerp(velocity,dir*speed,acceleration*accel_multiplier*delta)
animtree.set("parameters/run/blend_position", Vector2(-strafe_dir.x, strafe_dir.z))
```

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
When adding code please use formatting, using three back ticks like so \```, I've fixed this for you but please keep in mind in the future

Please also provide a minimum reproduction project, repeating the suggested code again is not sufficient to test this:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested MRP this can be reopened
