### ISSUE TITLE
macOS mouse zoom (control+scroll) does not work in 2D

### ISSUE THREAD

**Issue by ztc0611** [godotengine/godot#85672]
### Godot version

4.2.stable

### System information

macOS 14.2, Godot 4.2.stable, Any, Apple M1

### Issue description

When in a 3D scene, you can zoom in/out by holding Control and scrolling with the mouse, but in 2D this does not work. 

### Steps to reproduce

Open a blank project and scroll with a mouse in a 3D scene and then try 2D. Happens on both the Magic Mouse and standard mice.

### Minimal reproduction project

Occurs in any project.

**Comment by AThousandShips** [comment]
Does it work holding down `CMD`?

**Comment by ztc0611** [comment]
> Does it work holding down `CMD`?

No, honestly it seems like macOS is a wild west when it comes to this. Did some testing...

Apple's own apps:
Maps - Shift
Photos - CMD
Preview - None
iMovie/iWork - None

Some other apps I have:
Pixelmator: Option
Blender: Control
Blockbench: Control
Lightroom: CMD

**Comment by luisrpfigueiredo** [comment]
Having the same issue.

3D scrolling works fine on the trackpad, but 2D scrolling simply does not work. This basically makes it impossible to work on 2D projects with just the trackpad.

**Comment by ztc0611** [comment]
@luisrpfigueiredo I have no issues at all with trackpad. I can pinch to zoom and pan with two fingers in 2D, which is the same behavior with all other macOS apps. 4.2.stable.

**Comment by Calinou** [comment]
Can anyone reproduce this on [4.3.rc1](https://godotengine.org/article/release-candidate-godot-4-3-rc-1/)?

**Comment by ztc0611** [comment]
@Calinou holding down CTRL now works correctly in 2D on the Magic Mouse.
