### ISSUE TITLE
Sound doesn't play in editor

### ISSUE THREAD

**Issue by gggdeff** [godotengine/godot#85682]
### Godot version

4.2 stable

### System information

win 10 

### Issue description

sound dont player in editor but sound work in exported game

### Steps to reproduce

...

### Minimal reproduction project

...

**Comment by Mickeon** [comment]
Works just fine for me under the same vague conditions described (Windows 10)

**Comment by Calinou** [comment]
@gggdeff Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by gaudimancer-creator** [comment]
Hello,
If someone got the same problem,
I got this problem with an audio driver Realtek High Definition Audio under Windows 11. I connected my headphones after the project loading and it seems like Godot 4 did not understand that there was now an audio driver. The solution is simple : when you connect your headphones, close the project, then reload Godot, or just connect your headphones before loading the project.
Have a good day.
