### ISSUE TITLE
When listening for an input in the Editor Settings -> Shortcuts menu, the escape key will close the menu. 

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#85688]
### Godot version

4.2

### System information

Windows 11

### Issue description

Title.

I don't believe this should be the desired behavior. It should search for shortcuts using the escape key, and key the menu open.

### Steps to reproduce

Press escape in the 'Listening for Input...' box.

![image](https://github.com/godotengine/godot/assets/105675984/84d5627a-dd2d-42b3-80ff-82291ebfe544)

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.3.dev cae759949 (Linux).
