### ISSUE TITLE
Editor spams "Class name cannot be empty." error when sorting by type.

### ISSUE THREAD

**Issue by Grix** [godotengine/godot#85698]
### Godot version

v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.2698) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Recently it started to happen that whenever I save my project in the editor, or other similar actions, the editor hangs for a second and I get hundreds of error messages in the log, saying "Class name cannot be empty".

When opening Godot from the terminal, the error message elaborates slightly that it comes from this line: https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L4441

One thing I noticed is that it only seems to happen when I sort by type in the filesystem window. When sorting by name (default), I have not seen it happen yet.

I have no idea where in my project this error comes from, because the message doesn't say. It seems to be from the editor trying to find an icon for custom classes? But which class, and what would be wrong with said class? I don't know if it's user error on my part but I'm reporting as a bug to be sure.

I was able to delete a lot of my assets from a test project and only keep some textures mostly, and it still happens (although with fewer messages). When I delete the textures folder also, the issue stops entirely. So we at least know that some of the textures are some of the culprits (but not all). You probably need a .NET version of Godot to open the project, but maybe not since you don't need to actually compile to see the bug.

### Steps to reproduce

1. Open the project
2. In the filesystem window, set sort to "Sort By Type" (either ascending or descending is fine).
3. Observe 108 error messages in the output window.

### Minimal reproduction project

https://mega.nz/file/gQ5DRRbB#NaxDQN5Tkk72C4w0j-ZCadYWQfY2aFfw0Kd40DN-RPg

**Comment by MrBlockers** [comment]
I started looking into this, adding this here for any contributors more savvy with the filesystem dock
https://github.com/godotengine/godot/blob/d76c1d0e516fedc535a2e394ab780cac79203477/editor/filesystem_dock.cpp#L860-L875

Interesting to me that the actual icon name is used as a sorting heuristic. I guess this is for when you have multiple of the same filetype, but imported as different resource types? Could it just be the FileInfo::type?

**Comment by jsjtxietian** [comment]
Is the mrp link still valid? For a simple fix we can just check if the type an empty string.

**Comment by Grix** [comment]
> Is the mrp link still valid? 

It should be, nothing has changed

**Comment by jsjtxietian** [comment]
> It should be, nothing has changed

Maybe it's due to my internet connection, but I can't open the link right now. I suspect it has something to do with your textures but can get them right now lol.

**Comment by Grix** [comment]
> > It should be, nothing has changed
> 
> Maybe it's due to my internet connection, but I can't open the link right now. I suspect it has something to do with your textures but can get them right now lol.

Does this work instead: https://drive.google.com/file/d/1Y1U62zis-4hGtvpwShk8OqJcIuF0zf-d/view?usp=sharing

**Comment by jsjtxietian** [comment]
Yes thank you!

**Comment by erik1801** [comment]
Thanks helped me a lot :)
