### ISSUE TITLE
Label3D font does not follow project default theme in editor anymore (in-game is fine)

### ISSUE THREAD

**Issue by amonroejj** [godotengine/godot#85693]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.3667) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

See screenshot.

In 4.1.3, Label3D shows custom theme font in editor.

In 4.2, Label3D shows a default sans-serif font in editor.

![image](https://github.com/godotengine/godot/assets/2057161/81125f8e-8bfe-410e-b511-d6a4f24fd27d)

### Steps to reproduce

* Start the project using 4.1.3
* Make a theme.
* Customize the theme's default font
* Make your theme the project default (must enable advanced settings to reach this setting)
* Add Label3D to scene
* Clone the project folder
* Open the clone in 4.2 (triggering the 4.1.3-to-4.2 one-way conversion on the project)

Result: Label3D will (probably) not show your custom font in the 4.2 editor.

### Minimal reproduction project

[Label3DFontBugMRP.zip](https://github.com/godotengine/godot/files/13537687/Label3DFontBugMRP.zip)

**Comment by Calinou** [comment]
This regressed between 4.2.dev4 and 4.2.dev5. I bisected the regression to 512182f1475fe54833056e534320832a0bb2156a.

cc @YuriSizov

**Comment by Mickeon** [comment]
As an addendum, it's worth noting that the Label3D _does_ follow the `gui/theme/custom_font` setting. The problem is that if it doesn't exist it doesn't fall back to the custom theme.
![image](https://github.com/godotengine/godot/assets/66727710/436c64c2-943f-4972-bb01-17d2cffec2d5)
