### ISSUE TITLE
editor automatically change image

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#8570]
## Operating system or device - Godot version:
Operating system: Windows 7
Godot version: 2.1.3

## Issue description:
**what happened**
Repo mark png as changed but external editor has only re-save the image.
![image](https://cloud.githubusercontent.com/assets/10463138/25533420/e2cb4850-2c30-11e7-9fa8-a1036a2ddd96.png)
![image](https://cloud.githubusercontent.com/assets/10463138/25532540/f870a928-2c2d-11e7-8444-027e55bcbf21.png)
![image](https://cloud.githubusercontent.com/assets/10463138/25534506/39ae24d2-2c34-11e7-91c0-cafcc90bdfdb.png)

I don't know if it has something to do with this editor setting:
```
on_save/compress_binary_resources = true
on_save/save_modified_external_resources = true
resources/save_compressed_resources = true
```

**what was expected**
If re-saving a image with an external editor without any changes, Godot should not change the image.

## Steps to reproduce:
1. create a image
2. save it inside open godot project
3. check in repo
4. re-save it with external editor
5. godot automatically change image

**Comment by volzhs** [comment]
any description why you closed this?

**Comment by puppetmaster-** [comment]
Need more test, not sure whether it is my image- or godot editor.
