### ISSUE TITLE
get_local_mouse_position does not work under certain circumstances

### ISSUE THREAD

**Issue by mogoh** [godotengine/godot#85705]
### Godot version

Godot v4.2.stable (46dc27791)

### System information

Godot v4.2.stable (46dc27791) - Freedesktop SDK 23.08 (Flatpak runtime) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 5500 XT (RADV NAVI14) () - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

If:

- Godot 4.2
- A scene transition happened first
- Click on a `TileMap`
- That `TileMap` has a `TileSet`
- That `TileSet` has an `Atlas`

Then:

- `get_local_mouse_position` is calculated wrong

More specific:

Under the said circumstances, to `get_local_mouse_position` the negated `offset_left` and negated `offset_top` is added which adds up to the wrong result.

However, this does not happen if the `TileMap` has not `TileSet` or the `TileSet` has not `Atlas` or if the scene is loaded directly.
The behaviour should be consistent.
If the TopLeft corner of a `TileMap` is clicked, `get_local_mouse_position` should return `(0, 0)`.

### Steps to reproduce

See the issue description or the minimal reproduction project.

### Minimal reproduction project

[get_local_mouse_position-test.zip](https://github.com/godotengine/godot/files/13539051/get_local_mouse_position-test.zip)

**Comment by kleonc** [comment]
Indeed seems like TileMap's global transform ends up in incorrect state. Recalculating it manually gives correct result which means it must be an issue with not marking it as dirty or something like that.

In the MRP:
```gdscript
var gt := Transform2D()
var ci: CanvasItem = tile_map
while ci:
	gt = ci.get_transform() * gt
	ci = ci.get_parent() as CanvasItem
prints(tile_map.global_position, gt.origin)
```

- In v4.1.3.stable.official [f06b6836a] it correctly outputs `(-284, -116) (-284, -116)`.
- In v4.2.stable.official [46dc27791] it outputs `(-860, -440) (-284, -116)`.

**Comment by mogoh** [comment]
This is my workaround for now:

```gdscript
extends TileMap

func get_local_mouse_position_() -> Vector2:
	var gt: Transform2D = Transform2D()
	var ci: CanvasItem = self
	while ci != null:
		gt = ci.get_transform() * gt
		ci = ci.get_parent() as CanvasItem
	return get_global_mouse_position() - gt.origin
```
