### ISSUE TITLE
The configure menu in the InputEventJoypadButton and InputEventJoypadMotion Resource is so big, it cannot be closed.

### ISSUE THREAD

**Issue by JHDev2006** [godotengine/godot#85727]
### Godot version

4.2.stable (most likely over versions aswell)

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.4592) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When creating a custom InputEventJoypadButton resource, you are able to configure what the button actually is. In the list, that appears of every single button, however because the list is so large, it cannot fit onto the screen vertically, and therefore cannot be closed, forcing the whole engine to be closed through task manager. This problem also applies to the InputEventJoypadMotion Resource too.

### Steps to reproduce

Create a new InputEventJoypadButton or InputEventJoypadMotion Resource.
Select the configure button, which will display a list of all possible buttons.
Observe how the popup menu is so big, it cannot be closed. double clicking a selection dosent close the menu either.

### Minimal reproduction project

n/a

**Comment by JHDev2006** [comment]
seems to simply be an issue with my current editor config, fixed when using a fresh build of the engine. closing, apologies!

**Comment by JHDev2006** [comment]
reopening, as trying it on a seperate device has the same issue, was wrong in it being fixed when resizing or reinstalling the engine.

**Comment by YuriSizov** [comment]
Can reproduce the issue as well. Will try to look into it.
