### ISSUE TITLE
Input.action_press() causes input to stay pressed when triggered from mouse

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#85729]
### Godot version

4.2 stable

### System information

macOS

### Issue description

Game's input broke after moving from 4.1.2 to 4.2. I found that if `action_press()` is triggered from mouse (e.g. through `is_mouse_button_pressed()`, or a button in my case) then `is_action_pressed()` afterwards returns true continuously, until the game window is unfocused and focused again. This does not happen with key inputs.

### Steps to reproduce

put this script somewhere, run and left click mouse, notice it keeps printing "true" even after release.

```
func _process(delta):
	
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		Input.action_press("ui_accept")
		prints("CLICKED")
		
	prints(Input.is_action_pressed("ui_accept"))
```

or run MRP scene

### Minimal reproduction project

[ActionPressIssue.zip](https://github.com/godotengine/godot/files/13540448/ActionPressIssue.zip)

**Comment by GreentheNinja** [comment]
I'm fairly sure this is intended behaviour? I think you need to use `Input.action_release` in order to cancel an `Input.action_press()` (or press and release the action physically).

I don't think specifically using `Input.is_mouse_button_pressed()` has any effect.

**Comment by AThousandShips** [comment]
Not a bug, as the explanation above makes clear, you need to release the action, since the related release method exists I think it should be clear that this doesn't simulate a click, but pressing down the action

I don't think any action needs to be taken, the documentation is sufficiently clear IMO

**Comment by djrain** [comment]
Okay, yeah I wasn't sure if the change was a regression. sounds good

**Comment by AThousandShips** [comment]
This hasn't changed, it has been the same since 4.0, I've used the same code and it hasn't changed in this way
