### ISSUE TITLE
NavigationObstacle3D no longer applies transform rotation to its vertices in 4.2

### ISSUE THREAD

**Issue by stechyo** [godotengine/godot#85722]
### Godot version

4.2

### System information

Linux

### Issue description

It seems that navigation obstacle vertices no longer follow the transform rotation in 4.2. Not sure if this is a regression or intentional, if it's intentional I'd consider documenting it [here](https://docs.godotengine.org/en/4.2/tutorials/migrating/upgrading_to_godot_4.2.html). This is evidently visible on the gizmo, but given it affected the AI in a project I was working on I assume it doesn't only affect the gizmo.

### Steps to reproduce

Open the minimal rep. project on 4.1 and then 4.2, or:

- Create a NavigationObstacle3D with some vertices on Godot 4.1
- Rotate it and check that the yellow vertex gizmo rotates 
- Save the scene
- Open on 4.2
- Rotation is no longer applied 

### Minimal reproduction project

[godot-navobs-issue.zip](https://github.com/godotengine/godot/files/13540216/godot-navobs-issue.zip)

**Comment by stechyo** [comment]
I see. Must be something else that's not working. Thanks.

**Comment by tracefree** [comment]
For anyone else running into this issue, here's a workaround: https://gist.github.com/tracefree/36fcd1aac7399a9d2ebf6aefc670f6d2

It seems like a strange limitation to me that obstacles can't be rotated. I add a NavigationObstacle3D as a child to scenes like chests that should affect navmesh baking, but in the current implementation there is no way to have that obstacle be affected by the parent transform. Could this issue be reopened?
