### ISSUE TITLE
[4.2] Editor starts to flicker when it's in fullscreen and there is a tooltip displayed or another window is focused

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#85721]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When enabling Fullscreen in the Godot editor with shift + F11, after a while the editor starts to flicker whenever there is a tool tip displayed or the main editor window is not the currently focused window.

This either happens after a certain time (before that there is no flicker) or is caused by a specific action which I haven't figured out yet. If I can reliably reproduce this issues then I'm going to update this report.

### Steps to reproduce

Like I state previously, I at the moment can't reliably reproduce this issue.

It happens after a certain time (I haven't measured yet).

1.) Open a project in the Godot editor
2.) Enable fullscreen with shift + F11
3.) Wait some time
4.) The issue should happen

### Minimal reproduction project

An empty Godot project will do the trick

**Comment by Loufe** [comment]
Expreriencing a lot of flicker myself, just normal navigation of the editor. Windows 10, RTX 3080, AMD 5600x, v4.2, happens regardless of window configuration.

**Comment by DarkMessiah** [comment]
How does it look like? Something like that?

https://github.com/godotengine/godot/assets/1756388/08e7dd6c-b0d6-40c8-b384-54beeb497bc6
