### ISSUE TITLE
Viewport clicks are offset for Path3D node's Curve editors

### ISSUE THREAD

**Issue by Wilker-uwu** [godotengine/godot#85735]
### Godot version

4.2.stable

### System information

Godot v4.2.stable - Fedora Linux 39 (KDE Plasma) - Wayland - GLES3 (Compatibility) - AMD Radeon Vega 8 Graphics (raven, LLVM 16.0.6, DRM 3.54, 6.6.2-201.fc39.x86_64) () - AMD Ryzen 3 2200G with Radeon Vega Graphics (4 Threads)

### Issue description

Creating points for the Path3D node's curves will have misaligned location proportions on clicks and therefore point locations are more offset the further away a click is from the top-left corner of the viewport. Not reproducible for Path2D nodes.

https://github.com/godotengine/godot/assets/10854855/b2018ae8-272a-4b10-9077-55da06f88839

### Steps to reproduce

1. Create a Path3D node
2. Create points
    - ~~Points made closer to the top-left corner of the viewport will be closer to the mouse position.~~
    - The relative coordinate the point is placed from will be a multiplication by 2 over the coordinate of the mouse from the top-left corner.

### Minimal reproduction project

N/A

###### edit:typo

**Comment by Calinou** [comment]
Can you reproduce this using a X11 session?

**Comment by Wilker-uwu** [comment]
i've already tried both monitors before reporting, but now i can also confirm that the proportion which the clicks are offset to is the same for both yes and no fractional scaling, regardless if i'm using Wayland or X11. 
![alt: screenshot: each click here covers double the distance covered by the last.](https://github.com/godotengine/godot/assets/10854855/bc742b5d-9563-470b-ae56-c6b3cdaeb205 "screenshot: each click here covers double the distance covered by the last.")

**Comment by Wilker-uwu** [comment]
forgot to give an update:

i cannot reproduce the bug anymore, and i'm not sure what happened since there were no updates made since this report.

**Comment by Calinou** [comment]
Closing per the above comment. Please comment if you can still reproduce this on the latest Godot version.
