### ISSUE TITLE
GPU particles 2D spread issue

### ISSUE THREAD

**Issue by Perpetuum1101** [godotengine/godot#85744]
### Godot version

4.2

### System information

Windows 11 Vulkan forward+

### Issue description

It seems to me that when spread is set to 180 and there is no random distribution set in any other parameters the particles should move towards random points on the edge of the circle with the same speed. But now it looks like particle distribution randomness is entangled with a speed so speed of the initial particle is also random. Also it seems that particle fail to form a circle at the end of the path.

### Steps to reproduce

1. Create GPUParticles2D node.
2. Set spread to 180.
3. Set initial texture.
4. Remove gravity.
5. Set initial speed to 75 (min and max).
6. Set damping to 35,
7. Set explosiveness to 1.
8. Set duration to 3.

Expected result:
All particles end their path at the edge of the circle.

Actual:
Particles distribute randomly in the area that is resembling rectangle with rounded edges.

### Minimal reproduction project

[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/13545562/GPUParticlesBug.zip)

**Comment by Rudolph-B** [comment]
I did some testing and was able to reproduce the issue. It is made more clear by converting the GPUParticles2D node into a CPUParticles2D and getting the expected result.
Actual result (Using GPUParticles2D):
![image](https://github.com/godotengine/godot/assets/52322745/ffbfb6c6-bcd8-4057-b6a8-d972e74e5c0b)

What I believe to be the expected result (Using CPUParticles2D):
![image](https://github.com/godotengine/godot/assets/52322745/cbae43d3-0d70-4297-aa6c-ad5ae73bbe40)

It is also not tied to any specific spread value. Setting a spread to 0 causes the the particle to be completely stationary. It is the same issue as #85620.

**Comment by Rudolph-B** [comment]
I believe the issue is caused by spread direction not being normalized and also still having a z component the when it should be restricted to only 2 Dimensions. This results in the particle direction value affecting the particle velocity value.

The issue is also not present int 4.1

Changing `get_random_direction_from_spread` in `scene/resources/particle_process_material.cpp` from:
```c++
	code += "	vec3 normal = cross(binormal, direction_nrm);\n";
	code += "	spread_direction = binormal * spread_direction.x + normal * spread_direction.y + direction_nrm * spread_direction.z;\n";
	code += "	return spread_direction;\n";
	code += "}\n";
``` 
to:
```c++
	code += "	vec3 normal = cross(binormal, direction_nrm);\n";
	code += "	spread_direction = binormal * spread_direction.x + normal * spread_direction.y + direction_nrm * spread_direction.z;\n";
	if (particle_flags[PARTICLE_FLAG_DISABLE_Z]) {
		code += "	spread_direction.z = 0.0;\n";
	}
	code += "	return normalize(spread_direction);\n";
	code += "}\n";
```
Resolves the issue.

**Comment by clayjohn** [comment]
@Rudolph-B Feel free to open a PR with those changes :)
