### ISSUE TITLE
Can't access custom data of tiles after setting them via code

### ISSUE THREAD

**Issue by olibombardier** [godotengine/godot#85755]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce MX130 (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

Calling `get_cell_tile_data` on a tileMap returns null after the tiles have been set with a script. I'm only using an atlas tileset and I know the tile exists because I get it's coords using `get_used_cells`. It did work with some maps but I could not recreate a map that worked. I'm also calling `update_internals` after setting the tiles (at line 115 in the reproduction project)

### Steps to reproduce

- Download the stripped down version of my project.
- Hit play, the scene will load the level from level_file.wwl and set the tiles of the tilemap
- It should stop at line 69 because `_floor.get_cell_tile_data(0, cell)` returns null

### Minimal reproduction project

[tilemap-bug.zip](https://github.com/godotengine/godot/files/13549968/tilemap-bug.zip)

**Comment by bs-mwoerner** [comment]
The tilemap cell (0, 13) exists, but it references tile (3, 20) in the tileset atlas, which doesn't exist (your atlas has 12x12 tiles). There may be some issue with how you fill that tilemap.

**Comment by olibombardier** [comment]
You are right, I discovered that the tiles id can be negative and I was saving them with `store_8`, witch does not handle negative values. The loaded level is still somehow visually the same but probably had invalid ids. Anyway, by saving them correctly, the problem is solved.

Thanks!
