### ISSUE TITLE
Unable to retrieve specific CollisionShape3D hit by RayCast3D

### ISSUE THREAD

**Issue by TurqW** [godotengine/godot#85756]
### Godot version

4.2.stable.official [46dc27791]

### System information

Windows 10

### Issue description

I have:

- RigidBody3D
  - CollisionShape3D
  - CollisionShape3D2
  - CollisionShape3D3
  - etc

and I'm using a RayCast3D. I need to get the specific CollisionShape3D (so I can remove it without removing the whole body, or position things relative to it) but none of the available methods seem to be able to get that.
I've tried:
```
var collider = get_collider()
var highlight = collider.shape_owner_get_owner(collider.shape_find_owner(get_collider_shape()))
```
which just sets both variables to the RigidBody3D, and
```
var collider = get_collider()
var highlight = collider.shape_owner_get_shape(collider.shape_find_owner(get_collider_shape()), get_collider_shape())
```
which gives me a "ConvexPolygonShape3D" instead of the CollisionShape3D. Either way I'm unable to call functions from custom scripts on the CollisionShape3D.

My understanding from the documentation and what I can figure out from [this issue](https://github.com/godotengine/godot-proposals/issues/8168) is that the former should work. If that's not the case, what's the intended methodology here?

### Steps to reproduce

Point a RayCast3D at a RigidBody3D or StaticBody3D containing a CollisionShape3D.

In a script on the RayCast3D, retrieve the CollisionShape3D and confirm that it is the expected node.

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
The owner is the body so there's no bug.

AFAIK ConvexPolygonShape3D *is* a subtype of CollisionShape3D, so the latter works.

**Comment by TurqW** [comment]
ConvexPolygonShape3D is a subtype of Shape3D, but not of CollisionShape3D: https://docs.godotengine.org/en/stable/classes/class_convexpolygonshape3d.html

As I said, I'm unable to access the scripts attached to the CollisionShape3D.

**Comment by AThousandShips** [comment]
`collider.shape_owner_get_owner(collider.shape_find_owner(get_collider_shape()))` is the correct code, I'm not sure what you are doing to confirm it?
