### ISSUE TITLE
Vulkan Mobile: Tilemap has rendering issues on MediaTek Dimensity SoC

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot#85750]
### Godot version

v4.2.stable.official [46dc27791]

### System information

Windows 11- Godot v4.2.stable.official [46dc27791] - Vulkan (Forward+)

### Issue description

When I used Godot's Tilemap to package it for mobile Android, I found that if your phone has a Dimensity processor, it will cause tearing of the screen.
<img width="639" alt="f43b320f90dbf74ebe678820676075a2" src="https://github.com/godotengine/godot/assets/46812028/65395f0d-92c9-4847-98ad-cb80afaaade2">
**I don't have this problem when running on a Snapdragon processor**
![42be6062a982868fcdf9c89b05f0b9c3](https://github.com/godotengine/godot/assets/46812028/317f0519-d010-4324-bb92-158ab678229b)

This problem exists in version 4.x
And this problem is randomly generated ,it is uncertain

### Steps to reproduce

Use Android emulator or Dimensity to run it and you can see the error effect.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/13549038/bug.zip)

**Comment by clayjohn** [comment]
I have a feeling that this is a similar issue to those fixed by https://github.com/godotengine/godot/pull/84852 (but for textures) It might even be the same issue as https://github.com/godotengine/godot/issues/83481

In other words, I think it is likely an issue with how we readback memory from the GPU

CC @Alex2782 You may be interested in this issue.

**Comment by Alex2782** [comment]
@ModuleCode:
- how were you able to test it in the emulator? _(as far as I know, the emulators do not have vulkan drivers)_
- what system information / API version does `adb` show (emulator and MediaTek Dimensity)? see `adb`-examples below

--------------------
**Emulator Android 11** on Windows 10:
`USER ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.  / vkEnumeratePhysicalDevices Failure`

**Settings -> Advanced**
![Bildschirmfoto 2023-12-05 um 17 13 00](https://github.com/godotengine/godot/assets/41921395/77e15acd-5dd7-4d0e-841c-a451f0dc19cc)


---------------------------------------------------------

`adb logcat -s godot`

**Emulator Android 11**
```logs
--------- beginning of main  
--------- beginning of system
12-05 16:07:06.777  7493  7538 I godot   : Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org        
12-05 16:07:07.203  7493  7538 E godot   : USER ERROR: vkEnumeratePhysicalDevices reported zero accessible devices.     
12-05 16:07:07.203  7493  7538 E godot   : 
12-05 16:07:07.203  7493  7538 E godot   : Do you have a compatible Vulkan installable client driver (ICD) installed?   
12-05 16:07:07.203  7493  7538 E godot   : vkEnumeratePhysicalDevices Failure
12-05 16:07:07.203  7493  7538 E godot   :    at: _create_physical_device (drivers/vulkan/vulkan_context.cpp:1186)      
12-05 16:07:07.204  7493  7538 E godot   : USER ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE        
12-05 16:07:07.204  7493  7538 E godot   :    at: _window_create (drivers/vulkan/vulkan_context.cpp:1837)
12-05 16:07:07.204  7493  7538 E godot   : USER ERROR: Failed to create Vulkan window.
12-05 16:07:07.204  7493  7538 E godot   :    at: DisplayServerAndroid (platform/android/display_server_android.cpp:573)
```

**Samsung Tab S7 (Snapdragon)**, I could **not reproduce** either
```
12-05 16:49:13.552 30227 30367 I godot   : Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
12-05 16:49:13.754 30227 30367 I godot   : Vulkan API 1.1.128 - Forward Mobile - Using Vulkan Device #0: Qualcomm - Adreno (TM) 650
```

**Comment by ModuleCode** [comment]
I tested many mobile phones (not simulators), but this problem does not occur on Snapdragon processors. This problem occurs on Dimensity processors, and it is uncertain. Sometimes the problem will occur, sometimes not. Running on a real phone requires a mobile phone with a Dimensity processor.
Emulator (Android 13)：
![image](https://github.com/godotengine/godot/assets/46812028/d8b91329-6958-496a-9e4d-1d2faa8b9859)

```
12-06 02:30:31.410 15680 15930 I godot   : Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
12-06 02:30:31.585 15680 15930 I godot   : Vulkan API 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G57 MC3
12-06 02:30:32.986 15680 15930 I godot   :
12-06 02:30:34.200 15680 15930 E godot   : USER ERROR: Error calling from signal 'body_entered' to callable: 'Node2D(test_scene.gd)::_on_area_2d_3_body_entered': Cannot convert argument 1 from Object to Object.
12-06 02:30:34.200 15680 15930 E godot   :    at: emit_signalp (core/object/object.cpp:1140)
```

OPPO A72(Dimensity):
![image](https://github.com/godotengine/godot/assets/46812028/96f0f7dc-8930-40a4-8a54-d2357c5df65d)
```
12-06 02:30:31.410 15680 15930 I godot   : Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
12-06 02:30:31.585 15680 15930 I godot   : Vulkan API 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G57 MC3
12-06 02:30:32.986 15680 15930 I godot   :
12-06 02:30:34.200 15680 15930 E godot   : USER ERROR: Error calling from signal 'body_entered' to callable: 'Node2D(test_scene.gd)::_on_area_2d_3_body_entered': Cannot convert argument 1 from Object to Object.
12-06 02:30:34.200 15680 15930 E godot   :    at: emit_signalp (core/object/object.cpp:1140)
```

**Comment by ModuleCode** [comment]
This problem is solved
![image](https://github.com/godotengine/godot/assets/46812028/24f6c34c-c79d-4d79-9d49-4822b3ea5808)
I set this option！！

**Comment by ModuleCode** [comment]
![IMG20231206194216](https://github.com/godotengine/godot/assets/46812028/200e9805-440c-4f87-a67e-2d05261e30ea)
The picture above shows the operation of the Dimensity processor. The picture below shows the operation of the Snapdragon processor.

**Comment by Alex2782** [comment]
@ModuleCode: please use `adb exec-out screencap -p > screen.png` [screenshot via ADB](https://stackoverflow.com/questions/27766712/using-adb-to-capture-the-screen), this way we can better compare the differences. 

Your last picture, above `Dimensity processor` with GL / OpenGL also has errors? Or was that Mobile / Vulkan API?
--> `adb logcat -s godot`

---------------
It is difficult to recognise errors in pixel art graphics. But I can now also see them on my Samsung Tab S7 (Vulkan API / Mobile)



v4.2.stable.official [46dc27791]. (Later I will try to check the last master branch.)

**A)** MacOS: Vulkan API 1.2.231 - Forward Mobile - Using Vulkan Device #0: Apple - Apple M1
**B)** Android (**Mobile**): Vulkan API 1.1.128 - Forward Mobile - Using Vulkan Device #0: Qualcomm - Adreno (TM) 650
**C)** Android (**GL**): OpenGL API OpenGL ES 3.2 V@0502.0 (GIT@193b2ee, I593c16c433, 1633593732) (Date:10/07/21) - Compatibility - Using Device: Qualcomm - Adreno (TM) 650


| A and C| B | 
|---|---|
|  ![Bildschirmfoto 2023-12-06 um 16 24 11](https://github.com/godotengine/godot/assets/41921395/cd7a97cc-4e46-4ee1-94af-2120fd13685d)|  ![Bildschirmfoto 2023-12-06 um 16 24 23](https://github.com/godotengine/godot/assets/41921395/cb4c336d-287d-4e20-978f-ad709de24900)|

**Comment by ModuleCode** [comment]
> @ModuleCode：请使用`adb exec-out screencap -p > screen.png` [ADB截图](https://stackoverflow.com/questions/27766712/using-adb-to-capture-the-screen)，这样我们可以更好地比较差异。
> 
> 你的最后一张图片，上面`Dimensity processor`用GL / OpenGL也有错误？或者是 Mobile / Vulkan API？ -->`adb logcat -s godot`
> 
> 识别像素艺术图形中的错误是很困难的。但我现在也可以在我的 Samsung Tab S7（Vulkan API / Mobile）上看到它们
> 
> v4.2.stable.official [ [46dc277](https://github.com/godotengine/godot/commit/46dc277917a93cbf601bbcf0d27d00f6feeec0d5) ]。（稍后我会尝试检查最后一个主分支。）
> 
> **A)** MacOS：Vulkan API 1.2.231 - 转发移动 - 使用 Vulkan 设备 #0：Apple - Apple M1 **B)** Android（**移动**）：Vulkan API 1.1.128 - 转发移动 - 使用 Vulkan 设备 #0：高通 - Adreno (TM) ) 650 **C)** Android ( **GL** ): OpenGL API OpenGL ES 3.2 V@0502.0 (GIT@193b2ee, I593c16c433, 1633593732) (日期:10/07/21) - 兼容性 - 使用设备: Qualcomm - Adreno (TM) 650
> 
> 甲和丙	乙
> ![图片摄影 2023-12-06 um 16 24 11](https://private-user-images.githubusercontent.com/41921395/288457556-cd7a97cc-4e46-4ee1-94af-2120fd13685d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODI5ODMsIm5iZiI6MTcwMTg4MjY4MywicGF0aCI6Ii80MTkyMTM5NS8yODg0NTc1NTYtY2Q3YTk3Y2MtNGU0Ni00ZWUxLTk0YWYtMjEyMGZkMTM2ODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE3MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MWYzMGE4M2EyMmM1NGZiNWVlNGVlM2Q5NGFlNjhjZDNmZTQ5ZTE3NGYzYjJjMmFkNzc2M2YxZWNiZjMzZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-dKZPUgFEis2qfZtrJyQ79OkDdgIS1IN-kp8xvyqA8)	![图片摄影 2023-12-06 um 16 24 23](https://private-user-images.githubusercontent.com/41921395/288457883-cb4c336d-287d-4e20-978f-ad709de24900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODI5ODMsIm5iZiI6MTcwMTg4MjY4MywicGF0aCI6Ii80MTkyMTM5NS8yODg0NTc4ODMtY2I0YzMzNmQtMjg3ZC00ZTIwLTk3OGYtYWQ3MDlkZTI0OTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE3MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTFiMzgwOGE2NDFmZTkwN2Q3ZGMyZjkzODUzY2NlY2VjMDE5ZDVjYzU5NTZhNmNhYzZhOTAwZGY2MmQ3M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oLikNU3eyiXH13bYLSxvP1AxEa65VsgZQHIMclPFiKI)

The last picture has no errors when using GL/OpenGL, but there are problems when using Mobile/Vulkan API

**Comment by ModuleCode** [comment]
1. The last picture has no errors when using GL/OpenGL, but there are problems when using Mobile/Vulkan API

2. All problems will not occur when set to GL/OpenGL, but problems will occur when set to Mobile/Vulkan API on devices with Dimensity processors and emulators

3. After I rewrite it according to your method, the problem still occurs in the case of (Mobile/Vulkan API)
![image](https://github.com/godotengine/godot/assets/46812028/bdbff8b8-53e3-4b67-bd33-de32efbd0662)
![screen](https://github.com/godotengine/godot/assets/46812028/1b4934d2-9a51-4ca0-ad78-e7abe2a43d4e)
（There will be stripes on the tree on the right）

**Comment by ModuleCode** [comment]
> @clayjohn的“感觉”是对的 😃 ，已由#84852修复，也许是同样的问题？#71020
> 
> @ModuleCode：您可以稍后`MediaTek Dimensity SoC`在 4.3 版本发布时使用 Vulkan API 重试。
> 
> **Godot Engine v4.3.dev**：我已经重新启动演示超过10次，并且无法再识别任何错误。（Samsung Tab S7）
> 
> ```
> 12-06 18:45:49.292 17074 17148 I godot   : Godot Engine v4.3.dev.custom_build.2f73a059c - https://godotengine.org
> 12-06 18:45:49.412 17074 17148 I godot   : Vulkan API 1.1.128 - Forward Mobile - Using Vulkan Device #0: Qualcomm - Adreno (TM) 650
> ```

ok

**Comment by Alex2782** [comment]
TODO [Tiles, Tiles, Tiles](https://github.com/orgs/godotengine/projects/46/views/1?filterQuery=-status%3ADone+label%3A%22platform%3Aandroid%22) + Android


maybe same: 
https://github.com/godotengine/godot/issues/61789
https://github.com/godotengine/godot/issues/71020

**Comment by ModuleCode** [comment]
I think my problem is same ：https://github.com/godotengine/godot/issues/71020

**Comment by clayjohn** [comment]
@Alex2782 Thank you very much for taking a look!

**Comment by ModuleCode** [comment]
> @Alex2782 Thank you very much for taking a look!



> TODO [Tiles, Tiles, Tiles](https://github.com/orgs/godotengine/projects/46/views/1?filterQuery=-status%3ADone+label%3A%22platform%3Aandroid%22) + Android
> 
> maybe same: #61789 #71020

Thank you very much, I tried to use 4.3 export Android running, the problem does not exist
