### ISSUE TITLE
TileMaps do not remove their tile occluders when the tile changes.

### ISSUE THREAD

**Issue by ThePhantomLemon** [godotengine/godot#85766]
### Tested versions

Reproducible in 4.2-stable 

### System information

Godot v4.2.stable (46dc27791) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.1640) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

If you have a tile_set with an occlusion layer, and you remove a tile with an occlusion shape at runtime, the occlusion shape will remain.

![image](https://github.com/godotengine/godot/assets/6132794/c9eed82b-94c4-4654-b33a-1a9c5be4d45c)

![image](https://github.com/godotengine/godot/assets/6132794/c43cc34b-d307-416e-8e3f-bf49d1421ae7)

### Steps to reproduce

- Setup a scene with CanvasModulate and a 2D Light
- Create a tilemap & tileset
- Add an occlusion layer
- Give one or more tiles an occlusion shape
- Make a script run sometime during process to randomly remove and add the tiles with occlusion shapes, and tiles without.
You should now see errant shadows.

Or, in the MRP, just play the scene and you should see the problem once tiles alternate.

### Minimal reproduction project (MRP)

[OccluderProblem.zip](https://github.com/godotengine/godot/files/13552364/OccluderProblem.zip)

**Comment by ThePhantomLemon** [comment]
Also, I was able to fix this by altering `TileMapLayer::_rendering_occluders_update_cell` to call `_rendering_occluders_clear_cell` before updating/creating occluders. However I don't know if that's an acceptable fix.

**Comment by itsmagu** [comment]
![Bug With Tilemaps](https://github.com/godotengine/godot/assets/95685391/f141594a-02dc-4807-aa92-7c079a85bc41)
Here is an example of this bug

**Comment by itsmagu** [comment]
![Stable 4 1 3](https://github.com/godotengine/godot/assets/95685391/03dd1358-b8e4-4510-bca6-38258dd372ca)
In Godot 4.1.3.stable this is not a issue
