### ISSUE TITLE
`match` with multiple patterns in parentheses raises parse error

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#85760]
### Godot version

4.3.dev [d76c1d0e516fedc535a2e394ab780cac79203477]

### System information

Linux Manjaro

### Issue description

When multiple patterns enclosed in parentheses are used for pattern matching within `match` statement branch the parse error is raised. It prevents the usage of multiple patterns spread across multiple lines as a side-effect:

```
func foo(x):
	match x:
		1, 2, 3:         # ok
			pass
		(4, 5, 6):	 # parse error
			pass
		(
			7,       # parse error
			8,
			9
		):
			pass
```

### Steps to reproduce

See above

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
If your problem is that the error message is unclear, please say so, if on the other hand you want this syntax to be allowed you need to open a [proposal](https://github.com/godotengine/godot-proposals) as this syntax not being available is not a bug

**Comment by Scony** [comment]
@AThousandShips I thought it may be a bug that it's not possible to put multiple patterns into multiple lines (without using backslash `\` which is not a solution). But technically you're right - syntax with parentheses is not documented and not supported so it's likely not intended to work at all.

**Comment by AThousandShips** [comment]
I mean that's not a bug, so I'd suggest to open a proposal for this

Also why is using line continuation not a solution? It's the correct way to split a line, it being mildly inconvenient doesn't make it not a solution 🙂, if you do open a proposal you will have to mention it as a workaround

**Comment by Scony** [comment]
> I mean that's not a bug, so I'd suggest to open a proposal for this
> 
> Also why is using line continuation not a solution? It's the correct way to split a line, it being mildly inconvenient doesn't make it not a solution 🙂, if you do open a proposal you will have to mention it as a workaround

Well, to me having a mildly inconvenient alternative is a no-go in that case, so I'd prefer not to use that syntax in that case myself. Ofc. one can use it as an inconvenient workaround which is fair enough.

Anyway, it's worthy of improvement but if this is not even implemented then very likely there's no real demand for that so there's no point in opening proposal.

**Comment by AThousandShips** [comment]
Well you do what you feel is best 🙂 I'm sure a proposal would be worth it to evaluate how to do it, implementing this shouldn't be too complicated depending on how it's done
