### ISSUE TITLE
Script Editor: Ctrl + Shift + Arrow Up or Arrow Down make no scroll

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#85772]
### Tested versions

Godot 4.2 stable

### System information

Windows 10, Godot 4.2

### Issue description

https://github.com/godotengine/godot/assets/92402263/3846662e-e90b-4744-9ae8-1bbefbf65307

### Steps to reproduce

just open a long script file and hold ctrl + shift + arrow down and keep holding arrow down and u can see scroll not happen.
https://github.com/godotengine/godot/assets/92402263/3846662e-e90b-4744-9ae8-1bbefbf65307

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- fixed in https://github.com/godotengine/godot/pull/86978

**Comment by DexterFstone** [comment]
> * fixed in [Overhaul multicaret editing and selection in TextEdit #86978](https://github.com/godotengine/godot/pull/86978)

v4.3?
