### ISSUE TITLE
texture set_data not working on android

### ISSUE THREAD

**Issue by dumitru-stama** [godotengine/godot#8577]
**Android - Godot 2.1.3 stable:**

**Issue description:**
get_texture().set_data(....) not doing anything on android.

**Steps to reproduce:**
- Create a scene with a Sprite node (2d)
- Add the following script to the node:
```
extends Sprite
var img
func _ready():
	img = get_texture().get_data()
	set_process(true)
	
func _process(delta):
	var i
	for i in range(64):
		img.put_pixel(i,i, Color(1,0,0,1)) 
	get_texture().set_data(img)

```
It works on linux but not on android

**Link to minimal example project:**

[set_data.zip](https://github.com/godotengine/godot/files/965998/set_data.zip)

**Comment by plucian** [comment]
See #2997  it seems like a limitation of gles2.

**Comment by karroffel** [comment]
Thanks @plucian, that's the same error source, so we can't do much about it as it's a driver/hardware limitation.

Maybe you can work around it loading the same texture from disk, modifying it and then setting it as the iamge texture.

**Comment by Listwon** [comment]
Workaround:
```
extends Sprite
var img = Image()
var texture = ImageTexture.new()
func _ready():
	img.load("res://texture.png")
	set_process(true)
	
func _process(delta):
	var i
	for i in range(64):
		img.put_pixel(i,i, Color(1,0,0,1)) 
	texture.create_from_image(img)
	set_texture(texture)
```
