### ISSUE TITLE
4.2 - Path3D Control Nodes - Cannot create bezier handles in top down ortho view.

### ISSUE THREAD

**Issue by OboShape** [godotengine/godot#85795]
### Tested versions

works correctly in v4.1.3.stable.official [f06b6836a] as it doesnt have the Tilt Handles in editor.

issue occurs in v4.2.stable.official [46dc27791] as tilt handles were introduced.

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.4592) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

with the path3d node and looking in top down orthgraphic view cannot use control point button to drag and create bezier handles.
only the tilt handle is selectable due to it being higher up and making the control point unclickable to drag.

### Steps to reproduce

all i done was in 4.2 was create a new 3d scene.
create a path3d node.
into top down ortho view.
created a few points with the ![image](https://github.com/godotengine/godot/assets/15170625/ce3d4b54-2909-4272-bf1c-5fe88f5b2c8b) button.

then, using the select control points button 
![image](https://github.com/godotengine/godot/assets/15170625/bae00fdb-b25b-43cd-b9d0-d0ee37c9f6a0)
to try and create bezier handles.

this only indicates that the tilt handle has been selected and cannot create beziers.

my only workaround was to look from bottom up ortho, create the bezier handles and then return to top down ortho view to adjust placements.

possible solution would maybe have another button that hides or only controls the tilt handles

![image](https://github.com/godotengine/godot/assets/15170625/1916548f-fdf4-4cf8-bfe7-4bf0247ac476)

### Minimal reproduction project (MRP)

N/A

**Comment by TokageItLab** [comment]
cc @xiongyaohua

**Comment by matricola787** [comment]
I hope this can be fixed soon, as I'd like to work a lot with paths.
I suggest to have another button that enables/disables working with tilt handles, enabling working on bezier handles and tilt handles separately.

**Comment by Wolfe2x7** [comment]
This issue is broader than just top down ortho view, really. Any time the camera is far enough away from path points that the tilt handles overlap with the points, it starts to become correspondingly difficult to create bezier handles instead of mistakenly tilting the path.

**Comment by Wolfe2x7** [comment]
Could anyone besides xiongyaohua fix this? I just wonder if it is waiting on one person's inbox. 😐 This is fairly high-priority for Path3D users, IMHO.

**Comment by matricola787** [comment]
I could probably take a look at it, but I'd go this route and avoid complications: 

> I hope this can be fixed soon, as I'd like to work a lot with paths. I suggest to have another **button** that **enables/disables** working with **tilt handles**, enabling working on bezier handles and tilt handles separately.

@Wolfe2x7 would that satisfy you?
This would eventually need a new icon for the button, not sure how to approach that (I can make one that follows the already existent style?).

Should we open a proposal?

I'm not sure if this issue could be already solved by https://github.com/godotengine/godot/pull/80753 and its proposal https://github.com/godotengine/godot-proposals/issues/7462

**Comment by Wolfe2x7** [comment]
> I could probably take a look at it, but I'd go this route and avoid complications:
A button like you described sounds fine to me. 👍

**Comment by GreenCrowDev** [comment]
@Wolfe2x7 I opened a proposal https://github.com/godotengine/godot-proposals/issues/8890

**Comment by jejopl** [comment]
Yeah, I have the same issue.
