### ISSUE TITLE
GetCollisionPolygonPoints() of TileData does not work C#

### ISSUE THREAD

**Issue by Crystelmarv** [godotengine/godot#85803]
### Tested versions

- Tested and reproducible in 4.1.1 and 4.2

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

The GetCollisionPolygonPoints() of the TileData class does not work in C#. Only an empty Vector2 Array is returned.
In GDScript everything works like intented and the returned array is not empty.

### Steps to reproduce

See MRP
Setup tilemap with one tile at 0,0 that does have an collision set on physics layer 0

```
TileMap tileMap = GetNode<TileMap>("/root/Node2D/TileMap");
TileData tileData = tileMap.GetCellTileData(0, new Vector2I(0, 0));
GD.Print("C#: " + tileData.GetCollisionPolygonPoints(0, 0));
```
<br>

Same coding in GDScript that does work:
```
var tileMap = get_node("/root/Node2D/TileMap")
var tileData = tileMap.get_cell_tile_data(0,Vector2i(0,0))
print("GDScript: " + str(tileData.get_collision_polygon_points(0,0)))
```
<br>

Output in console:
```
GDScript: [(-8, -8), (8, -8), (8, 8), (-8, 8)]
C#: Godot.Vector2[]
```

### Minimal reproduction project (MRP)

[TileDataPolygonNotWorking.zip](https://github.com/godotengine/godot/files/13572392/TileDataPolygonNotWorking.zip)

**Comment by raulsntos** [comment]
C# arrays, like most types, don't implement `ToString` which means they use the default implementation. The default implementation returns the type name (in this case `Godot.Vector2[]`). This doesn't mean the array is empty, check the [`Length`](https://learn.microsoft.com/en-us/dotnet/api/system.array.length) property of the array.

If you want to print the contents of the array you'll have to implement it yourself. If the array matches one of Godot's [packed arrays](https://docs.godotengine.org/en/4.2/tutorials/scripting/c_sharp/c_sharp_collections.html#packedarray) you can convert it to `Variant` which implements the `ToString` method:

```csharp
Vector2[] vectors = [new Vector2(4, 2), new Vector2(2, 4)];
GD.Print($"Vector contents: {(Variant)vectors}");
```
