### ISSUE TITLE
AMD R5 M330 graphic issues

### ISSUE THREAD

**Issue by JavRogu** [godotengine/godot#85804]
### Tested versions

- Reproducible: all godot 4 versions - Godot_v4.2-stable_win64 (last version I tested)
- Not reproducible: before godot 4 versions - I'm currently working on Godot_v3.5.3-stable_win64, and there is no issue

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) R5 M330 () - AMD A8-7410 APU with AMD Radeon R5 Graphics (4 Threads)

### Issue description

The bug appears as soon as I start godot, all the interface is not properly shown, when I move over any option on the interface with the mouse the interface start to blink and the options are not shown, and I've already tested other godot 4 versions and the problem persist, only on the godot 3 versions the problem is not happening.

### Steps to reproduce

There are not steps, the problem can be noticed on the interface where we create a new project or select an exiting one, any clickeable option triggers this problem.

### Minimal reproduction project (MRP)

https://youtu.be/VTGknO_ML-o

_Production edit: updated the system info_

**Comment by JavRogu** [comment]
Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) R5 M330 () - AMD A8-7410 APU with AMD Radeon R5 Graphics (4 Threads)

**Comment by adamscott** [comment]
Did you install the latest graphics driver? For your chipset, you should follow this link:
https://www.amd.com/en/support/graphics/amd-radeon-r5-series/amd-radeon-r5-300-series/amd-radeon-r5-m330

**Comment by JavRogu** [comment]
> Did you install the latest graphics driver? For your chipset, you should follow this link: https://www.amd.com/en/support/graphics/amd-radeon-r5-series/amd-radeon-r5-300-series/amd-radeon-r5-m330

Yes, I have the latest driver, also I run updates for all drivers just to be sure, but it doesn't work

**Comment by adamscott** [comment]
https://github.com/godotengine/godot/pull/85273 will certainly fix your issues.
