### ISSUE TITLE
Soft hyphen does not appear when line break is forced

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#85815]
### Tested versions

- Reproducible in 4.2 stable official [46dc27791]
- Reproducible in 3.5.2 stable official, but with a different visual result

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 with Max-Q Design (NVIDIA; 30.0.15.1272) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

A [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen) is a Unicode character that says that a word *may* be hyphenated there, but is itself not visible unless the line is actually broken there.

On Godot 4.2, the line break positions are correct, but a visible hyphen is not shown there.
![Godot_v4 2-stable_win64_F1F5zIYmEX](https://github.com/godotengine/godot/assets/8707990/60bdd34b-d348-49ce-8171-e2790e02ac43)
↑Note the lack of hyphen after "Lebensversicherungs".
![Godot_v4 2-stable_win64_dmR1A2UMkw](https://github.com/godotengine/godot/assets/8707990/2a9b6174-2884-4429-9da8-0a909c9a6b6f)
↑Note the lack of hyphen after "Lebens".

On my browser (Firefox), soft hyphens behave as intended:
![firefox_PYxAMSGcsG](https://github.com/godotengine/godot/assets/8707990/31f6c3fe-d64e-4537-93e7-0418dfaa128b)
↑Note that the hyphens only appear when the long word is broken.

In Godot 3.5.2, by the way, the added hyphen is always visible, and word wrap doesn't split the word there anyway.
![Godot_v3 5 2-stable_win64_pjXqPzGRFG](https://github.com/godotengine/godot/assets/8707990/a7809398-f193-4f0a-9f5b-fce59a3ac066)
![image](https://github.com/godotengine/godot/assets/8707990/75c9a0f9-882b-4116-94c9-44e696489fce)

### Steps to reproduce

1. Create a Godot 4.2 project
2. Create a scene containing a Label
3. Paste the test string into the Label (or any other suitable text with soft hyphens)
4. Resize the Label to see how it reflows

Test string:

    Swiss Life muss als Lebens­versicherungs­gesellschaft ihre eingegangenen Verpflichtungen gegenüber den Versicherten vollständig...

### Minimal reproduction project (MRP)

[fourtest.zip](https://github.com/godotengine/godot/files/13574880/fourtest.zip)

**Comment by TheSofox** [comment]
I've confirmed that this happens with Label and TextEdit, if anyone finds it on other controls, let me know.

It's worth mentioning that if you go to the context menu on TextEdit (right click), you can toggle "Display Control Characters." This will make **every** hyphen visible. This is obviously still not ideal behaviour, but does demonstrate that Godot recognises SHY as a line breaking special control character, but not the specific circumstance where it is to be rendered visible (even if "Display Control Characters" is off).
