### ISSUE TITLE
Animated Path2D doesn't update PathFollow2D progress when scene is running.

### ISSUE THREAD

**Issue by vyshliy** [godotengine/godot#85813]
### Tested versions

Reproducible in 4.2 stable, 4.0 stable, 4.1.2 

### System information

ubuntu 22.04

### Issue description

When a Path2D curve is animated, the PathFollow2D progress is not updated when the scene starts and retains its position. In the editor, animation works fine and PathFollow2D moves according to the updated curve.

One exception. This works fine if "Visible Paths" is enabled in Debug.

The problem can be solved by listening to the curve.changed signal and setting the same progress manually. Still looks like a bug, especially since Progress_ratio is updated (without updating the node position) but Progress is not.

https://github.com/godotengine/godot/assets/72736632/3f8f5a67-fc4a-42cd-91da-6b500e6afd8e

### Steps to reproduce

- Play animation in the editor. PathFollow2D moves along an animated curve.
- Start the scene. PathFollow2D is not moving.
- Enable Visible Paths in the Debug and run scene. PathFollow2D moves.
- Disable Visible Paths. Uncomment line 12 in the script and run the scene. PathFollow2D moves.

### Minimal reproduction project (MRP)

[AnimPath.zip](https://github.com/godotengine/godot/files/13574556/AnimPath.zip)

**Comment by ditiem-games** [comment]
Can I fix this one or is there someone working on it already?

**Comment by ditiem-games** [comment]
I got a fix, but the main branch is seriously broken, so we have to wait. I will do PR when I can test it.
