### ISSUE TITLE
Not able to change "Pan Mode"'s shortcut.

### ISSUE THREAD

**Issue by Herooyyy** [godotengine/godot#8582]
**Operating system or device - Godot version:**
Windows 10 64-bits. Godot_v2.1.3-stable_win64

**Issue description:**
    You are not able to change the shortcut of _Pan Mode_ from _MiddleMouse Button_ to another key e.g., _Control + LeftMouse Button + Drag_ or _Space + LeftMouse Button + Drag_.
    When using a Touchpad (_Trackpad_) it's really uncomfortable having to click _Control + Space + LeftMouse Button_.

![panmode](https://cloud.githubusercontent.com/assets/19430633/25557440/39385808-2d09-11e7-804f-28c268d44ba5.png)

**Comment by Zylann** [comment]
There is a touchpad pan mode for 3D, but it was renamed `emulate 3-button mouse`. It allows to use only the modifier to pan without having to click the middle button. You might want to do a similar thing in 2D, or make it a common setting.

**Comment by amireldor** [comment]
Would be happy to have this implemented in 2D.

**Comment by xarrynator** [comment]
It seems indeed very strange to me that Pan Mode is selectable on the toolbar above the 2D viewport like all the other modes, to make the left mouse button "drag" the screen (as mentioned, very nice for touchpads). Yet - contrary to the modes to its left and right - it cannot be assigned a shortcut... I really should learn some C++ to be able to look into things like this :)

**Comment by Calinou** [comment]
@xarrynator As of Godot 3.2, you can hold the right mouse button to pan. Isn't this sufficient?
