### ISSUE TITLE
Confirmation Dialog should not be able to maximized or minimized.

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#85835]
### Tested versions

- Reproducible in 4.1.3 and 4.2
- Not Reproducible in 3.5.3

### System information

Windows 11

### Issue description

When you delete a node in scene tree or delete a file from the files system. A confirmation dialog is shown. 
This dialog can be maximized or minimized, and even can be moved outside of the application (in windows).
this needs to be removed as these are not correct features for confirmation dialog.

![image](https://github.com/godotengine/godot/assets/84369217/dc1b4750-1909-4ba4-9403-08624b3e925e)
 

### Steps to reproduce

Delete a node from the scene tree and then dialog is shown
Delete a file from the file system in the editor and the dialog is shown
There are other ways dialog is shown also but this feature is not required in the above two conditions. 

### Minimal reproduction project (MRP)

N.A

**Comment by tokengamedev** [comment]
Additionally the text of buttons could be `Yes` and `No` or `Delete` and `Cancel` rather than `OK `and `Cancel`, but it is enhancement and requires a proposal.

**Comment by eugene87222** [comment]
Hi @akien-mga, is there any way to distinguish between this general type of confirmation dialog and some special-purpose dialogs, such as open file dialog, import project dialog, etc.? I noticed that in Godot, many dialogs inherit from `AcceptDialog` or `ConfirmationDialog`, so directly enabling `FLAG_RESIZE_DISABLED` in these two classes is not a good idea apparently. It might affect a lot of functionality. Currently, it seems that only the `Popup` class sets `FLAG_RESIZE_DISABLED` to true.

**Comment by tokengamedev** [comment]
I think it is working as designed, so closing it.
