### ISSUE TITLE
Debugging process stopped

### ISSUE THREAD

**Issue by DP0bl3t3** [godotengine/godot#85838]
### Tested versions

i am in 4.1.2

### System information

Windows 11

### Issue description

When i run a proyect it closed inmediatly and says debugging process stopped, i have closed the proyect and now, when i try to edit the proyect, all the scenes are deleted, 

### Steps to reproduce

idk

### Minimal reproduction project (MRP)

idk

**Comment by Sauermann** [comment]
Can you please check, if this also happens in Godot 4.2?
It would help, if you could share a minimal reproduction project, that causes this behavior. Without a reliable way to replicate the problem it is extremely difficult to debug the problem.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide more information this can be reopened

**Comment by josepvalls** [comment]
I know this has been closed for almost a year but I wanted to report that I encountered the same behavior in v3.6.stable.official [de2f0f147]. It started happening out of nowhere on a project I've been working on for weeks. I closed Godot, deleted .import and it's not happening anymore, or at least, has not happened yet (it was pretty frequent earlier).

**Comment by AThousandShips** [comment]
If you have detailed steps for how to reproduce the issue please open a new bug report
