### ISSUE TITLE
`self.` completion suggesting incorrect code

### ISSUE THREAD

**Issue by am45-001** [godotengine/godot#85833]
### Tested versions

Tested in v4.2.stable.official [46dc27791], v4.2.1.stable.official [b09f793f5].

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

The self keyword are assumed to be classes by code completion (unlike before in v4.1 and previous versions), and only display constants, static functions, and new().

Edit: After further investigation by @Vilcrow, I jumped the gun on Singletons suffering the same issue as the self keyword. Apologies to @MitrB for stealing your thunder on this one.

### Steps to reproduce

- In any project open in version 4.2, create or open a script.
- Type "self." and observe the code completion suggestions.
- You should see something like this:
![Screenshot 2023-12-06 061131](https://github.com/godotengine/godot/assets/111308069/4ea87ab5-9438-478b-a4f6-dafe6c27abfa)

### Minimal reproduction project (MRP)

[BugProject.zip](https://github.com/godotengine/godot/files/13581582/BugProject.zip)

**Comment by yosoyfreeman** [comment]
Confirmed in Linux too.

**Comment by dalexeev** [comment]
* See also #85568.

**Comment by MackyK** [comment]
I'm pretty sure this is a regression as I could use this before and waiting for 4.3 seems odd.

**Comment by AThousandShips** [comment]
It being marked for 4.3 doesn't mean you have to wait for 4.3, if a compatible bug fix can be made it can be cherry picked for 4.2.x

**Comment by am45-001** [comment]
> I'm pretty sure this is a regression as I could use this before and waiting for 4.3 seems odd.

as a workaround you can use an external code editor like VSCode, and it will get around the missing instance variable and method issues. It will still kind of treat self and singletons like classes, but you'll actually be able to code with it.

**Comment by am45-001** [comment]
> > I'm pretty sure this is a regression as I could use this before and waiting for 4.3 seems odd.
> 
> as a workaround you can use an external code editor like VSCode, and it will get around the missing instance variable and method issues. It will still kind of treat self and singletons like classes, but you'll actually be able to code with it.

Well, this is awkward, I just tried this again and it doesn't work lol

**Comment by HolonProduction** [comment]
Did a bisect. Was introduced in 56e2fad31927e40406bc888aab99fa8f3f417d1f. (#73196)
The changes to `gdscript_editor.cpp` don't make sense to me and don't seem to have gotten any discussion during the PR. Could you explain how they relate to the issue @Vilcrow

**Comment by Vilcrow** [comment]
@HolonProduction changes to `gdscript_editor.cpp` have been made to correct #72353 which led to the incorrect completion. I've tried to figure it out a little bit now, but so far there are no results. I will try to fix this bug as soon as I have time.

**Comment by HolonProduction** [comment]
Yeah I read the isssue and you also described what caused the issue in you PR. What I don't understand is how these changes:
```
if (p_context.type != GDScriptParser::COMPLETION_SUPER_METHOD) {
    r_type.type = p_context.current_class->get_datatype();
} else {
    r_type.type = p_context.current_class->base_type;
}
```
are related to the cause of the issue that you described in the PR (you said it had something todo with a wrong position being used in `CodeEdit`).

This issue (as in #85833) results from `p_context.current_class->get_datatype()` being a meta type (the class, not an instance of the class; that is why you only see `new`. So this should just be switched back to how the type was constructed before.

I also don't see what you are trying to do with `p_context.type != GDScriptParser::COMPLETION_SUPER_METHOD`. Could you give an example case were this would be `false`.

So yeah IMO I would just try to revert all changes to `gdscript_editor.cpp`. But you propably know better what this code is supposed to do.

**Comment by MitrB** [comment]
@am45-001 No need to apologise, I wasn't going to be very involved either way

**Comment by am45-001** [comment]
@Vilcrow would it be appropriate for me to upload the custom version of 4.2.1 with your fix here? Or would I need to publish it somewhere else while we wait for the next version?
