### ISSUE TITLE
Quick trails, vector fields and collisions for particles

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8583]
Unreal engine has very robust modular particle system which allows for some great stuff: https://docs.unrealengine.com/latest/INT/Engine/Rendering/ParticleSystems/Reference/index.html
It would be great to have some of these features available in godot right away without messing with shaders. 

Vector fields allow for some really funky and great particle spreading effects that I'm sure a lot of games would benefit from: https://docs.unrealengine.com/latest/INT/Engine/Rendering/ParticleSystems/Reference/Modules/VectorField/index.html 

Benefits of having collisions and trails quickly available I'm sure I don't even need to describe, that stuff is great.

**Comment by eon-s** [comment]
On Godot 3 particles can do that but a built-in particle editor with some preset shaders could be handy.
Related #4250

-----------------

Particle collisions are planned for 3.1, I think.
Related #3994 #6377 and #4250 again.

**Comment by ArcFutahito** [comment]
I'm pretty sure particles can't do vector fields, at least I've been looking through a build I found today and found nothing of sorts.

**Comment by eon-s** [comment]
@ArcFutahito can't test even trails because Godot crashes when I open the shader tab (but I don't know anything about the new shader language anyway), just have seen trails and I believe the "vector field" may be possible too because you can set emission points.

**Comment by ArcFutahito** [comment]
Vector field is less about emission and more about applying force to particle based on it's position. Here for example https://docs.unrealengine.com/latest/images/Engine/Rendering/ParticleSystems/Reference/TypeData/GPUSprites/GPUSprites.jpg
trails are the spaces in vector field with least resistance and empty spaces are formed when vectors push particles out of them to move through a 'better' area

**Comment by eon-s** [comment]
I know about the math vector fields (I love gradients even now that I'm rusty on the subject) but not used to that concept of trail, you refer as "trail" as something ahead, not behind?

**Comment by Zylann** [comment]
@eon-s the trails you've seen in the news post are in fact brute-force particles, many quads drawn one after another scaling down. Any particles drawn many times at close distance can look like trails, however I suspect this has a performance impact, even minor.

Vector field is doable in a particle shader, it can be a simple formula, some shader params, or a 3D texture (if supported?).

**Comment by eon-s** [comment]
@Zylann I see, I hope to be able to test it soon, my system likes to turn minor impacts into huge ones

**Comment by ArcFutahito** [comment]
There's actually an interesting thing in Unreal, it does trails by drawing SOME particles and then connecting them in engine, so it shouldn't be as taxing
https://docs.unrealengine.com/latest/INT/Engine/Rendering/ParticleSystems/Reference/TypeData/Ribbon/index.html

**Comment by ArcFutahito** [comment]
With this logic to make trailing particle you'd want to specify a "cut off" point which will get then get placed behind as something like billboard and stretched to the next close particle. It probably gets tessellated for sweet curves and alpha is applied as gradient between alpha of newer and older particle. 

At least that's what I think happens.

**Comment by eon-s** [comment]
Ah, saw the "trail divisor" property and made crazy things in a "I don't know what I'm doing" fashion, still is not what the OP refers as "trail", I think.

@ArcFutahito but particles don't know where are the others, may be more complex now that is GPU based (or more simple, I know less than zero about this).

**Comment by ArcFutahito** [comment]
@eon-s If you mean this comment: 
> trails are the spaces in vector field with least resistance
I just refer to tails that get formed. Think solar prominence https://en.wikipedia.org/wiki/Solar_prominence

As for quick trails I refer pretty much to these ribbons and what I said in the comment above.

**Comment by eon-s** [comment]
Weee

![parttest](https://cloud.githubusercontent.com/assets/10215987/25558856/b7133c1a-2d05-11e7-8325-022700d05c3a.gif)


I'm not sure what ribbons are, these seem doable.

I hope the experts make some demos showing the current system capabilities.

----------------

Something that I have noticed is that particle system is complicated to manage because particle emitter, process material and draw passes can't be edited on the same screen (lot of forwards and backwards until gets the desired effect), this may be another issue (or one of the related ones).

**Comment by ArcFutahito** [comment]
> I'm not sure what ribbons are, these seem doable.

Here's a link to unreal docs, you can sort of understand how those work just by looking at functions
https://docs.unrealengine.com/latest/INT/Engine/Rendering/ParticleSystems/Reference/TypeData/Ribbon/index.html

**Comment by KoBeWi** [comment]
We are moving to proposals repo, also there's official proposal for particle ideas: https://github.com/godotengine/godot-proposals/issues/815
Leave a comment in that issue if this feature wasn't already mentioned.
