### ISSUE TITLE
POT generation ignores subscripts

### ISSUE THREAD

**Issue by feiyunw** [godotengine/godot#85848]
### Tested versions

See "System information" below.

### System information

Godot v4.1.4.rc (2d3b2abcf) - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.2698) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

POT generation ignores tr() expression in dictionaries:
```python
var strDeclarer = { 'N':tr("North"), 'E':tr("East"), 'S':tr("South"), 'W':tr("West") }[declarer]
var strVulnerable = { 0:tr("none"), 1:tr("both"), 2:tr("NS"), 3:tr("EW") }[vulnerable]
```
Strings as tr() parameters do not show up in the POT file.

### Steps to reproduce

FYI: [Creating the PO template - Automatic generation using the editor](https://docs.godotengine.org/en/stable/tutorials/i18n/localization_using_gettext.html#automatic-generation-using-the-editor)

### Minimal reproduction project (MRP)

N/A

**Comment by timothyqiu** [comment]
As a workaround, you can break the expression into two lines:

```gdscript
# turn
var strDeclarer = { 'N':tr("North"), 'E':tr("East"), 'S':tr("South"), 'W':tr("West") }[declarer]
# into something like this:
var strDeclarerData = { 'N':tr("North"), 'E':tr("East"), 'S':tr("South"), 'W':tr("West") }
var strDeclarer = strDeclarerData[declarer]
```

**Comment by jsjtxietian** [comment]
May I ask why godot don't use simple pattern match to detect these strings ?  I guess with some extra `if` it can be quick and sufficent, using parser is a little overkill as we have to maintain it.
