### ISSUE TITLE
AStar weight scale applied to whole path during solve?

### ISSUE THREAD

**Issue by lehthanis** [godotengine/godot#8584]
**Operating system or device - Godot version:**
X11, 64 bits, 2.1.3 and 3.0

**Issue description:**
Trying to make a board game style hex tile map. Connecting points and giving most points a weight of 1, and some points a weight of 2. Expected solution would be to consider moving through 2-weighted cells to cost 2 move points and 1-weighted cells to cost 1 point.  Looks like weight gets multiplied to the whole distance calculation (*= used in line 194 or 222, etc). I saw it avoiding a path of 8 2-weighted cells and choosing instead 22 1-weighted cells.

**Steps to reproduce:**
Create a hex tile map and add only the hexes that have a tile on them as points in A-Star. connect all adjacent hexes. Give some cells a weight of 2 and some a weight of one, making some paths theoretically cost more. When path is solved, the shortest path often doesn't seem to properly factor cost as per cell, but cumulative instead. Pretty hard to explain, but it seems wrong to me.

**Link to minimal example project:**
I'll make a sample project and add it soon...it'll take a little extra time. Wanted to get issue raised first.

**Comment by tagcup** [comment]
Yes, there is a single weight scale, but this should be doable after @supagu's changes as far as I remember. Can you post your `_estimate_cost` and `_compute_cost` functions?

**Comment by raymoo** [comment]
You could exponentiate the fields as a hacky workaround, since exp distributes over multiplication (exp(w1)exp(w2) = exp(w1+w2))
