### ISSUE TITLE
Web Editor Preload doesn't automatically prompt to create folder

### ISSUE THREAD

**Issue by Rice-Tech** [godotengine/godot#85855]
### Tested versions

-Reproducible in all 4.x versions
-Not reproducible in 3.x

### System information

Chrome OS - Godot 4.2

### Issue description

When using the preload project zip option on the web editor, the user is not prompted to create a project for the preloaded zip. The zip is located in the /tmp folder and can be manually imported.

### Steps to reproduce

1. Open web editor
2. Download the provided example
3. Click Choose File and open the demo.zip
4. Dialoge to create folder does not appear

1. Click import
2. Navigate to /tmp
3. demo.zip is present there

### Minimal reproduction project (MRP)

Demo provided from the web editor's opening screen or any project.

**Comment by paulsinnett** [comment]
I just had this happen in 4.2.2 on the using Windows 11 and Edge browser 126.0.2592.81 (Official build) (64-bit)

More or less as the description above except in step 7 the file is called `preload.zip`

**Comment by paulsinnett** [comment]
I think maybe just the documentation needs changing. Instead of preloading the file before starting the editor, all you need to do is start the editor and then drag and drop the zip file into the loader window.

**Comment by paulsinnett** [comment]
I've put in a pull request with a fix
