### ISSUE TITLE
Window's width not changing to a lower value, do to an unknown min value.

### ISSUE THREAD

**Issue by OrlanRod** [godotengine/godot#85866]
### Tested versions

Godot 4.2 Stable

### System information

Windows 11 64 bit

### Issue description

When setting low resolutions on the width, it does not go below a certain unknown size. The height works fine.
I tried resolution of 96x72. It does not size to the width.
![Screenshot 2023-12-06 152344](https://github.com/godotengine/godot/assets/21212571/3a4b8548-7d23-442f-b42f-03e80b20fb3b)

### Steps to reproduce

-Create empty project and set a window resolution to 96x72, Windowed mode, Stretch: disabled, Aspect : Keep, Scale-Mode: integer.
-Add color rect to a Node2D scene and set the size  96x72.
-Run and watch as the grey backdrop is larger than the width of the rect.

### Minimal reproduction project (MRP)

[Res_Width_Issue_Repo.zip](https://github.com/godotengine/godot/files/13591258/Res_Width_Issue_Repo.zip)

**Comment by bruvzg** [comment]
There are two reasons that can restrict min. size:

1. Godot sets default window min. size to 64x64 (this is "client area" size, excluding title and borders), you can override it by using:
```
func _ready():
	get_window().min_size = Vector2()
```

2. OS usually do not allow windows that won't fit window control buttons, and will force bigger width (it depends on platform and version). You can make the window non-resizable (to remove minimize and maximize buttons) or borderless (to remove titlebar).

**Comment by OrlanRod** [comment]
> There are two reasons that can restrict min. size:
> 
> 1. Godot sets default window min. size to 64x64 (this is "client area" size, excluding title and borders), you can override it by using:
> 
> ```
> func _ready():
> 	get_window().min_size = Vector2()
> ```
> 
> 2. OS usually do not allow windows that won't fit window control buttons, and will force bigger width (it depends on platform and version). You can make the window non-resizable (to remove minimize and maximize buttons) or borderless (to remove titlebar).

Oh i see. Yeah that looks like it worked for me. Thanks.

**Comment by Sauermann** [comment]
Based on the comment above, this issue is resolved. Closing accordingly.
