### ISSUE TITLE
Internal script error! Opcode: 0 (please report).

### ISSUE THREAD

**Issue by Evanev7** [godotengine/godot#85878]
### Tested versions

Found in Godot 4.2, couldn't reproduce

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

Testing code, added a "to_local" and received this "Internal Script Error! Opcode: 0 (please report)." error, at function @implict_new in a script I wasn't testing, but would reasonably be loaded. 

### Steps to reproduce

Unable to reproduce.

### Minimal reproduction project (MRP)

Unable to reproduce.

**Comment by dalexeev** [comment]
Please provide more information on how to reproduce the bug. I'm guessing this has something to do with hot reloading (when you edit a script while the project is running).

**Comment by Jead-DC** [comment]
This happened me sometimes, but I couldn't reproduce it either.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/42379, as this is due to the same cause.
