### ISSUE TITLE
Reflection probes not working on Vulkan Mobile and Compatibility renderers in 4.2

### ISSUE THREAD

**Issue by victfv** [godotengine/godot#85873]
### Tested versions

Reproductible in 4.2 stable
Not reproductible in 4.1.3 stable

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 650 Ti (NVIDIA; 30.0.14.7444) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Reflection probes simply don't work on Vulkan mobile and Compatibility renderer.
Godot 4.1.3:
![image](https://github.com/godotengine/godot/assets/25274301/80ccb23c-8986-4662-a5e6-9846c361febe)
Godot 4.2:
![image](https://github.com/godotengine/godot/assets/25274301/f0fd93b0-a912-4f14-aa24-0cf6353c4484)

### Steps to reproduce

1. Create a sphere with a metallic material with low roughness.
2. Create some geometry to reflect off of the sphere
3. Add a reflection probe to the scene

### Minimal reproduction project (MRP)

[ReflectionProbes.zip](https://github.com/godotengine/godot/files/13592653/ReflectionProbes.zip)

**Comment by Calinou** [comment]
> Compatibility

ReflectionProbe rendering isn't implemented in Compatibility yet.
