### ISSUE TITLE
RPCs from client to server fail after node reparented on both ends

### ISSUE THREAD

**Issue by PieKing1215** [godotengine/godot#85883]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]
- Reproducible in v4.2.stable.official [46dc27791]
- Reproducible in v4.2.beta1.official [b1371806a]
- Not reproducible in v4.2.dev6.official [57a6813bb]
- Not reproducible in v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Say you have a server/client setup, and a node that calls an RPC from client to server when some input is pressed.
After upgrading to 4.2.stable I'm finding that the RPC works fine at first but if the node is reparented (*on both client and server*), future calls to that RPC from the client will fail.
Weirdly, the server outputs a "Node not found" error with the original path of the node, despite it not being there on either end.

For example, in the MRP there's a sphere that's reparented between two nodes (Container1/Container2) on click using RPCs.
Notice how when it isn't in the initial parent (Container1), the server errors when it receives the RPC from the client, which seems to send the wrong path (Container1) despite the sphere being in Container2 on both sides.

<details>
  <summary>Error messages</summary>
  
(note: the path of Object on both server & client is `/root/Main/Container2/Object` when this is output)
```
E 0:04:42:0701   get_node: Node not found: "/root/Main/Container1/Object" (absolute path attempted from "/root").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1635 @ get_node()

E 0:04:42:0701   get_cached_object: Failed to get cached path: /root/Main/Container1/Object.
  <C++ Source>   modules/multiplayer/scene_cache_interface.cpp:256 @ get_cached_object()

E 0:04:42:0701   process_rpc: Invalid packet received. Requested node was not found.
  <C++ Error>    Parameter "node" is null.
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:212 @ process_rpc()
```
</details>

https://github.com/godotengine/godot/assets/13819558/81d27cc7-18ad-467f-9a4a-eee8e3d99cc5

So far haven't found a way to work around this (replacing `reparent` with `remove_child`/`add_child` or swapping rpc reliable/unreliable behaves the same)

### Steps to reproduce

- Download MRP
- Run 2 instances on 4.2.stable
- Choose server for one and client for the other
- Once connected, click on the server window to swap the object however many times you want (should have no issue)
- Try the same on the client window and it should get stuck
- See server errors for message displaying wrong path to the object (different from displayed path on both client & server)
- If repeated on 4.1.3.stable there should be no issues

### Minimal reproduction project (MRP)

[rpc_reparent_repro.zip](https://github.com/godotengine/godot/files/13596911/rpc_reparent_repro.zip)

**Comment by Faless** [comment]
The regression was likely introduced by the optimizations to the multiplayer caching functions done in #82777 .
I'm looking into it.
