### ISSUE TITLE
@onready tag disables autocomplete for static typing 

### ISSUE THREAD

**Issue by ClaudioPaterniti** [godotengine/godot#85891]
### Tested versions

Repoducible on v4.1.1

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6650 XT (Advanced Micro Devices, Inc.; 31.0.14051.5006) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

When you declare a variable with a custom (class_name) static type and the `@onready `tag, the editor does not gives you code suggestions for that variable, also ctrl+click does not takes you to the definition. If you remove the `@onready` tag and initialize it in the _ready() everything works as intended.

### Steps to reproduce

In the appended project, in the _process() function of the Main scene, you cannot ctrl+click custom_method for the `@onready` var, but you can with the simple_var. Also typing `simple_var.` suggests you `custom_method`, the `@onready` var does not.

### Minimal reproduction project (MRP)

[onready_bug.zip](https://github.com/godotengine/godot/files/13601847/onready_bug.zip)

**Comment by Mickeon** [comment]
In 4.2, neither of the two issues exist, if I am understanding the bug report correctly.
![image](https://github.com/godotengine/godot/assets/66727710/cbea063f-1a06-422c-a3c3-41767186639b)

However, amusingly, the opposite of one does happen. `simple_var` doesn't seem to autocomplete properly.
![image](https://github.com/godotengine/godot/assets/66727710/7ab05f49-9787-4bae-862f-b856defb9bc3)

**Comment by arawup** [comment]
Using 4.2
Oddly enough I have slightly different behavior than Mickeon. 
<img src="https://github.com/godotengine/godot/assets/71040574/86aaa42e-d73d-41c2-9ad9-6113448fde81" width=40% height=40%>  <img src="https://github.com/godotengine/godot/assets/71040574/6973f8d9-d9fc-40a5-8912-18d4998cb97d" width=40% height=40%>
<img src="https://github.com/godotengine/godot/assets/71040574/ffbc25f4-8c0e-49ea-b767-16da7086e747" width=40% height=40%>  <img src="https://github.com/godotengine/godot/assets/71040574/a2220ac2-7f9c-4025-9f10-2ae0d90237cc" width=40% height=40%>

For the ctrl+click  it seems to work or maybe I'm not understanding
[Screencast from 2023-12-10 16-03-03.webm.mov](https://github.com/godotengine/godot/assets/71040574/d2a5ee7c-0f89-4987-aeef-5b2f1c309ce6)

As for the `@onready`  not having autocomplete in the line it applies. I do have issues with static typed variables not suggesting methods.
<img src="https://github.com/godotengine/godot/assets/71040574/4b1b9ae6-4a73-4eb3-9b0a-b986588f3dc3" width=40% height=40%>  <img src="https://github.com/godotengine/godot/assets/71040574/c2837ca9-70e3-4588-a335-add5fe3bd05b" width=40% height=40%>
[onready intellisense.zip](https://github.com/godotengine/godot/files/13629420/onready.intellisense.zip)

**Comment by ClaudioPaterniti** [comment]
@arawup with Ctrl+click I meant on the type properties, so in the example clicking on the method `f()`.

**Comment by HolonProduction** [comment]
This is fixed by #79386, which was cherry picked recently, so @Mickeon is probably using a pre release version which does not have the problem.

The issue with the local variable did exist before, but was masked by other behaviour which it isn't anymore. I will ask in the contributors chat, whether we can get a fixed merged before the PR makes it into an official release.

**Comment by TheSofox** [comment]
Testing on v4.4.dev.custom_build [efc7c628b] seems to confirm it was fixed. Ctrl+clicking the `f()` on both variable function calls took me to the source, and autocomplete works with both too.

![image](https://github.com/user-attachments/assets/ac0ef27b-a413-4c3a-a200-0478a4dcc0bd)
![image](https://github.com/user-attachments/assets/a4133599-6787-43af-b31e-5128cde581ff)

I recommend this bug be closed.
