### ISSUE TITLE
Keystore settings in export_presets.cfg are not saved/loaded in Godot Editor

### ISSUE THREAD

**Issue by gnils** [godotengine/godot#85898]
### Tested versions

Occured under 4.1 and reproducable under latest v4.2.stable.official [46dc27791]

### System information

Windows 11 Godot v4.2.stable.official [46dc27791]

### Issue description

The following settings seem not to be saved/loaded correctly from export_presets.cfg:
- keystore/debug
- keystore/debug_password
- keystore/debug_user
- keystore/release
- keystore/release_password
- keystore/release_user
In Editor under Project -> Export the key settings are actually saved (also when restarting Godot), but the export_preset.cfg remains unchanged. When adding these lines manually to the export_presets.cfg file, CLI build is successful, but lines get removed from the file once the Export window in Godot Editor is used.
Furthermore, there's a promt coming up if the cfg should be reloaded due to changes. Also showing up when the Export window is open. (not related to any manual editing of the cfg)

### Steps to reproduce

- Open a project
- Open the Project -> Export menu
- Create/select a Android export
- Enter keystore information for release and/or debug
- (Export project sucessfully)
- See if the cfg has changed (it has not)
- (Run CLI build and fail due to missing keystore information)

### Minimal reproduction project (MRP)

Can be reproduced using an empty new project, or probably any other project as it's related to the Editor.

**Comment by sanchitgulati** [comment]
keystore credentials are stored here at: \.godot\export_credentials.cfg

**Comment by AThousandShips** [comment]
Closing as this is intended to prevent sensitive information from being stored in the export preset

If there's some other issue around this please open a new report

**Comment by Calinou** [comment]
If you want to externally supply those variables, you can do so using [environment variables](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html#environment-variables).
