### ISSUE TITLE
Input.get_vector can get interfered with when the right and down arrow keys are held.

### ISSUE THREAD

**Issue by Mousedotexecutable** [godotengine/godot#85901]
### Tested versions

4.2.stable

### System information

Linux Fedora - v4.2.stable.official - Gles3 (Compatibility)

### Issue description

Input.get_vector will have it's input interfered with, if either the down or right arrow key is held, while it receives input from a keyboard.

It only seems to happen on Physical keyboards. Works surprisingly as intended on laptop keyboards? 
This issue also happens on Windows.

### Steps to reproduce

Open the reproduction project, run master.tscn. Move diagonally using the D and S keys, then hold the right arrow at the same time.

### Minimal reproduction project (MRP)

[InputGetVectorBug.zip](https://github.com/godotengine/godot/files/13605010/InputGetVectorBug.zip)

**Comment by AThousandShips** [comment]
This sounds like it could be keyboard ghosting, please confirm this by testing online, you can find apps to test it with online

**Comment by Mousedotexecutable** [comment]
I've tested my keyboard and I've found out that it is keyboard ghosting.
I didn't know about keyboard ghosting until now. Sorry about that.

**Comment by AThousandShips** [comment]
Closing as per the above
