### ISSUE TITLE
Plugin UI Scene corrupted after each project reload

### ISSUE THREAD

**Issue by FranzPantalon** [godotengine/godot#85902]
### Tested versions

Reproductible in: 
v4.2.stable.flathub [46dc27791]
v4.2.stable.official [46dc27791]
v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.2.stable (46dc27791) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 (nvidia) - Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 Threads)

### Issue description

I am new in the field of game development I am currently learning Godot. But I'm quite convinced this is a genuine bug. 

As I wanted to create my first plugin, I created a scene for the plugin's UI. This very scene gets corrupted a each reload of the project.  

### Steps to reproduce

1. Create a plugin with a new dock and a new button as explained in documentation https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#creating-a-plugin
2. (Re-)Activate plugin
3. Reload project or restart Godot

Result :
- Plugin don't run. 
- Attempt to open the UI-scene leads to message "Scene file [...] appears to be invalid/corrupt"
- Replacing the file by a new one and correcting dependencies only solve the problem once. Next time project is reloaded, problem occurs again.

### Minimal reproduction project (MRP)

[corruptScene.zip](https://github.com/godotengine/godot/files/13605101/corruptScene.zip)

**Comment by Swarkin** [comment]
Heres the console output
```
scene/resources/resource_format_text.cpp:284 - res://addons/godotsync/src/main.tscn:8 - Parse Error: 
Failed loading resource: res://addons/godotsync/src/main.tscn. Make sure resources have been imported by opening the project in the editor at least once.
Failed to instantiate scene state of "res://addons/godotsync/src/main.tscn", node count is 0. Make sure the PackedScene resource is valid.
editor/editor_data.cpp:880 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
editor/editor_data.cpp:683 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
editor/editor_data.cpp:745 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```
Scene file
[main.zip](https://github.com/godotengine/godot/files/13614027/main.zip)

**Comment by FranzPantalon** [comment]
So... As it could not be excluded, the inexperienced user that I am did make a mistake that lead to this issue.

I just had a new look at the project, and saw that I attached the plugin script (which extends EditorPlugin and preloads the scene) to the ui scene. 
When you do so, there is normally an error prompt _"Script inherits from native type 'EditorPlugin', so it can't be assigned to an object of type 'Control'."_ which I propably overlooked (or ignored) the last time.

Sorry for the disturbance, you may close the issue as far as I am concerned.

**Comment by AThousandShips** [comment]
You can close your own issues once you feel they are resolved
