### ISSUE TITLE
Moving a reflection probes origin offset gizmo while being up close to it causes the gizmo to jump around

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#85912]
### Tested versions

Reproduced in v4.2.stable.official [46dc27791]
Reproduced in v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When moving the 3D editors camera up close to the reflection probes origin offset gizmo and then draging the gizmo, it starts jumping around (see video). This jumping around is also reflected in the property in the inspector, so I assume that this is not only a visual bug.
Note that this does only happen when you do the before described, it works fine when the camera is not up close (see video).

https://github.com/godotengine/godot/assets/111653551/f1635a3b-8625-4d23-a988-40bb5ea8b822

### Steps to reproduce

Create a new Godot project
Add a reflection probe
Move the 3D editor camera up close to origin offset gizmo
Drag it around

### Minimal reproduction project (MRP)

-

**Comment by Calinou** [comment]
This is likely due to a precision issue and probably affects all 3D gizmo handles, not just ReflectionProbe's Origin Offset.
