### ISSUE TITLE
"Bug: Export PCK/ZIP Button Disappears on Godot Editor 4.2 Android Platform"

### ISSUE THREAD

**Issue by bitesgame** [godotengine/godot#85919]
### Tested versions

4.2 stable

### System information

Android 8.1 - Godot 4.2 stable - OpenGL ES 3.2 - Qualcomm Snapdragon 450 1,8GHz 14nm - Qualcomm Adreno(TM) 506 @ 600MHz - MIUI Global 11.0.2 | stable - Total Roma 32,00GB - Total Ram 3GB

### Issue description

and also the navigation button cannot be removed, it is menuupand also the navigation buttons cannot be removed it covers the editor

https://github.com/godotengine/godot/assets/65835193/b1cb309d-04f3-43f9-899a-ad380b3200b9

### Steps to reproduce

T/A

### Minimal reproduction project (MRP)

T/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73130.
