### ISSUE TITLE
Godot 4.2 deadlocks when opening projects

### ISSUE THREAD

**Issue by ltecheroffical** [godotengine/godot#85910]
### Tested versions

Producable in Godot 4.2

### System information

Godot v4.2.stable - macOS 11.7.10 - Vulkan (Mobile) - integrated Intel HD Graphics 5000 - Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 Threads)

### Issue description

when attempting to open a project then it just deadlocks and throws nasty errors in console. (Root cause is unknown and can't be found)

```
ERROR: Array is in read-only state.
   at: push_back (core/variant/array.cpp:267)
ERROR: Array is in read-only state.
   at: push_back (core/variant/array.cpp:267)
```

### Steps to reproduce

Just open a project and it won't even get past scene loading

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
Can you please provide more details of how to replicate this, like a minimal reproduction project? Without a clear method of how to replicate this issue, it is nearly impossible to debug this.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
