### ISSUE TITLE
Godot 4.1.3 Unable to Write to File "" File in use, locked or lacking permission (MacOS)

### ISSUE THREAD

**Issue by DailyNasrudin** [godotengine/godot#85927]
### Tested versions

Godot Version 4.1.1 Stable is what I typically use, but I haven't encountered this bug before. Not sure if this was always the case, but randomly glitched when I didn't touch my project for a week or two. I also moved some files out of folders but not Godot files to my knowledge. I also have Malwarebytes Protection installed.

### System information

Godot v4.1.1.stable - macOS 12.4.0 - Vulkan (Compatibility) - Intel(R) Iris(TM) Plus Graphics OpenGL Engine (1x6x8 (fused) LP - Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz (4 Threads)

### Issue description

Trying to load a godot project will cause it to show this error along with one of my scenes shown missing "Can't open file 'madeby.tscn'. This file could've been moved or deleted.

![Error1](https://github.com/godotengine/godot/assets/153311995/c935b6f6-57c3-406b-8ae1-ec3c8679ad5b)

### Steps to reproduce

Steps to Reproduce:
-Opening the Godot Project

### Minimal reproduction project (MRP)

N/A (When making a new project, every time I try to import a new scene, new node, new resource, it shows the same error screen in the screenshot)
![Error2](https://github.com/godotengine/godot/assets/153311995/f55d2b47-1f99-4cec-941e-4fada440c35d)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by DailyNasrudin** [comment]
Still sadly the same error, loaded the project and got the same file locked, already opened, or lacking permission.

**Comment by DailyNasrudin** [comment]
I'm currently looking at my output error and there are even more errors:

Godot Engine v4.1.3.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:73 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
  Cannot load editor settings from file 'res://.godot/editor/project_metadata.cfg'.
--- Debug adapter server started ---
--- GDScript language server started ---
  Cannot load editor settings from file 'res://.godot/editor/project_metadata.cfg'.
  Cannot load editor settings from file 'res://.godot/editor/project_metadata.cfg'.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  Cannot open file 'res://scenes/madeby.tscn'.
  Failed loading resource: res://scenes/madeby.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:626 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  Attempting to parent and popup a dialog that already has a parent.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  Attempting to parent and popup a dialog that already has a parent.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.
  drivers/unix/file_access_unix.cpp:171 - Condition "rename_error != 0" is true.

**Comment by DailyNasrudin** [comment]
I don't know what happened, but I rebooted my computer, and it suddenly works again. I have no clue how or why this happened, but I guess something corrupted. Thanks for your help anyways!

**Comment by chrisopher444** [comment]
Hello, were you able to solve it, I tried everything to uninstall and reinstall Godot but it works for a while and then repeats itself, do I use Linux, any solution?

**Comment by vaunakiller** [comment]
> Hello, were you able to solve it, I tried everything to uninstall and reinstall Godot but it works for a while and then repeats itself, do I use Linux, any solution?

I encounter it frequently on Windows 10, Godot: v4.2.1.stable.official [b09f793f5]

Closing the running instance of the game helps, albeit is annoying

**Comment by Asterdev-03** [comment]
The solution is to stop running the project in the background.
This problem occurred to me, when I run the scene and an error occurs in my script, I fix the error, but when I save it, a window pops up saying it's unable to write. To solve this, just stop running the project, then update or save the script. I hope this helps with your problem.

**Comment by ManikSharma69420** [comment]
Same issue. For me, whenever there is an error in the script and I save, I cannot save again. I have to reopen the project. Issue on Windows 11

**Comment by Proksimas** [comment]
Hi,
Each time i have this permission error, windows defender have to be update. After updating it's work perfectly.  Pretty sure it s the issue lol
