### ISSUE TITLE
Can not delete first line in script editor with delete line hotkey when script has only one line

### ISSUE THREAD

**Issue by xxSeys1** [godotengine/godot#85928]
### Tested versions

Reproduced in v4.2.1.rc1.official [daeb1c729]
Reproduced in v4.2.stable.official [46dc27791]

### System information

Godot v4.2.1.rc1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When using the delete line editor shortcut
![image](https://github.com/godotengine/godot/assets/111653551/8fddcef4-e9b5-4bad-a37f-3c4989f1dfea)
to delete the top line in a script that only has one line, the line is not deleted and the following error message is outputted to the output:
`scene/gui/text_edit.cpp:3581 - Index p_from_line = -1 is out of bounds (text.size() = 1).`

https://github.com/godotengine/godot/assets/111653551/5b49906b-eb47-403c-b4d9-40159c5fe728

### Steps to reproduce

1. Create a new Godot project
2. Create a new script
3. Delete every line but the first line
4. Make sure there are no empty lines in the script
5. Set the delete line shortcut in the editor settings to whatever you want
6. Try to delete the line in the script with the shortcut (Place the text cursor in the line you want to delete -> press shortcut)

### Minimal reproduction project (MRP)

See "Steps to reproduce"

**Comment by gokiburikin** [comment]
Problem is this section which when there's only 1 line attempts to access line -1.

https://github.com/godotengine/godot/blob/b94eb58d35b3dd8a9f522bc90df0db73862ef326/editor/code_editor.cpp#L1409-L1413

A potential solution:

```gdscript
if (line != text_editor->get_line_count() - 1) {
	text_editor->remove_text(line, 0, line + 1, 0);
} else if (text_editor->get_line_count() == 1) {
	text_editor->remove_text(line, 0, line, text_editor->get_line(line).length());
} else {
	text_editor->remove_text(line - 1, text_editor->get_line(line - 1).length(), line, text_editor->get_line(line).length());
}
```

Side effect being that you can call delete lines on an empty line and it adds an undo state despite no changes.
