### ISSUE TITLE
3D animation player with bone doesn't work at all

### ISSUE THREAD

**Issue by NRicode** [godotengine/godot#85920]
### Tested versions

version: 4.2 (last week release)

### System information

Godot v4.2.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.1691) - Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/106366188/dd8c5d21-fe44-4451-aeb2-60af188a9b1b)
[scene.zip](https://github.com/godotengine/godot/files/13614268/scene.zip)
using the 3d model above, it is not possible to animate anything at all, I have tried many different ways and nothing has worked. Trying to play the broken animation gives this error that I cannot read clearly
![image](https://github.com/godotengine/godot/assets/106366188/ed939b2b-9d20-4fd7-99a7-c4cbed6cac03)

### Steps to reproduce

1. Download the scene.zip above and try to animate anything (positon, rotation, scale, etc) of any of the **bone**, in my example I tried to animate the spine

Unrelated to the issue but I think that when we press add track -> 3d rotation, we should be able to select any individual bone inside the Skeleton3D node. But currently trying to animate any bone is only possible by selecting the bone itself in the Skeleton3D node then press the insert keyframe. This feels kinda unintuitive.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/godotengine/godot/files/13614374/Bug.zip)

**Comment by AThousandShips** [comment]
The error is printed under "Output", please see what it says there

**Comment by AThousandShips** [comment]
It says the problem, the quaternion isn't normalized, what are the actual key values?

**Comment by NRicode** [comment]
> It says the problem, the quaternion isn't normalized, what are the actual key values?

I already set the x y and z rotation to be between 0 and 1, still doesn't work. I'm not sure, not very experienced with these kind of stuff. Maybe you can help me check it out in the sample project I provided. I already setup everything there.

**Comment by NRicode** [comment]
> That's not what normalised means, it means the length is 1, I can't check it right now but you can just copy the values you entered and I can check them.

I tried to rotate the shoulder joint from it's default rotation state to y = 2. 
Honestly just try to do anything, the whole thing just doesn't work. Have tried for like 2 hours.

If you managed to do it please inform me the rotation axis sample animation, maybe I misunderstood how the whole thing works.

**Comment by NRicode** [comment]
Aight, got it. thank you

**Comment by NRicode** [comment]
btw It'll be appreciated if you can delete this issue thread for me. Thanks.

**Comment by AThousandShips** [comment]
We don't delete issues unless they are abusive content, and this can help others so we appreciate if you don't erase the information
