### ISSUE TITLE
Godot only recognizes first 4 Xbox controllers on Windows

### ISSUE THREAD

**Issue by zolrath** [godotengine/godot#85937]
### Tested versions

Reproducible in 4.2 and 4.2.1-RC1.

### System information

Windows 11 - Godot 4.2 - Compatibility

### Issue description

When connecting Xbox One controllers with an Xbox Wireless Adapter on Windows 11 the project only sees 4 of the 8 connected xbox controllers. The controllers are verified as working in Windows in general and show up in the Xbox Accessories app.

If I disconnect one of the detected controllers, the next controller "in line" is recognized.

I would expect to be able to play with all detected controllers.
XInput apparently has a limit of 4 XInput controllers, causing other platforms to swap additional controllers to DirectInput or the Windows.Gaming.Input API.

![image](https://github.com/godotengine/godot/assets/454563/a05eccdf-f800-4073-b24e-65e17e8a5d12)

Using non-XInput controllers such as Switch Pro controllers allows me to connect 4 xbox controllers + 3 (as I only have 3) Switch Pro controllers to test beyond this limit, though it is not a practical requirement for players.

As this may be beyond the scope of an issue, I've created a proposal here: https://github.com/godotengine/godot-proposals/issues/8620

### Steps to reproduce

1. Run the ControllerDetection project.
2. Connect more than 4 xbox controllers.
3. See only 4 controllers recognized.
4. Disconnect one of the recognized controllers - See one of the previously undetected controllers is now detected.

### Minimal reproduction project (MRP)

[ControllerDetection.zip](https://github.com/godotengine/godot/files/13621021/ControllerDetection.zip)

**Comment by Calinou** [comment]
Thanks for the report! Adding support for additional input APIs is proposal territory, which is being tracked in https://github.com/godotengine/godot-proposals/issues/8620.

As a result, this issue is considered a documentation issue which is being addressed by https://github.com/godotengine/godot-docs/pull/8594.
