### ISSUE TITLE
 Godot 4.2+ Error importing 'file.blend'. Blender 4+

### ISSUE THREAD

**Issue by moomoosic** [godotengine/godot#85932]
### Tested versions

-

### System information

Windows 10

### Issue description

 Godot 4.2+ Error importing 'file.blend'. Blender 4+

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
Please provide more information, this is not enough to do anything with

**Comment by moomoosic** [comment]
Blender version 4.0.2
![godot](https://github.com/godotengine/godot/assets/109451610/72bf66c7-1025-40b1-ac8d-703e68e1aa79)

**Comment by AThousandShips** [comment]
This gives zero info, please provide more, if unable there's nothing we can do to help, please turn to the other [community channels](https://godotengine.org/community) to help with this, this is not a support desk 🙂

**Comment by AThousandShips** [comment]
It does, generally, but you aren't providing *any* details for investigating this, others have used blender 4 without problems
