### ISSUE TITLE
4.2.1 - No GPUParticles2D in Compatibility Mode

### ISSUE THREAD

**Issue by zolrath** [godotengine/godot#85945]
### Tested versions

Reproducible in: 4.2.1 - RC1
Not reproducible in: 4.2

### System information

Windows 11 - Godot 4.2 - Compatibility

### Issue description

When using a GPUParticles2D in Godot 4.2.1-RC1 no particles are rendered on screen

### Steps to reproduce

Create a project using 4.2.1-RC1
Set the rending mode to Compatibility.
Create a GPUParticles2D system.
No particles are rendered.

### Minimal reproduction project (MRP)

[ParticlesTest.zip](https://github.com/godotengine/godot/files/13621559/ParticlesTest.zip)

**Comment by Ciapas-Linux** [comment]
Hello

The same thing happens under debian Linux, GPU and CPU particles do not work with the compatibility renderer

Godot Engine v4.2.1.rc1.official.daeb1c729 
OpenGL API 3.3.0 NVIDIA 470.223.02 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GT 740M

**Comment by Calinou** [comment]
I can confirm this on 4.2.1.rc1 (Linux, GeForce RTX 4090 with NVIDIA 535.129.03). This doesn't appear to be OS/vendor-specific.

**Comment by ChoO-T** [comment]
Same behavior on Godot 4.2.1RC1 on Compatibility on Windows 10, no particle rendered, neither in game or in editor.
