### ISSUE TITLE
built-in scripts do not show up in the navigator editor beside the other scripts when you reopen godot

### ISSUE THREAD

**Issue by ticnew** [godotengine/godot#8594]
Windows 10 64 bit - Godot version: Godot_v2.1.3-stable_win64

the built-in scripts do not appear with the other external scripts, (I'm talking here in the navigator that has all scripts name beside the code editor) 
I just start godot and i saw in some old tutorials that they show up just fine , but that not happen with me and i have to go for every single node that have buil-in script in it and open it from there every time i reopen godot

**Comment by Zireael07** [comment]
Why did you archive this immediately?

**Comment by ticnew** [comment]
I thought it's gonna fix from sitting but it's not

**Comment by ticnew** [comment]
Really sorry about that..

**Comment by reduz** [comment]
This is not a bug, Godot would be forced to open all scenes to load the built-in scripts if this were supported. Just don't use built-in scripts, they are more trouble than benefit.
