### ISSUE TITLE
HTTPRequest: TLS error with self signed certifcates configured in project settings

### ISSUE THREAD

**Issue by AahzBrut** [godotengine/godot#85953]
### Tested versions

Reproducible in Godot Engine v4.2.stable.official.46dc27791

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Quadro P620 () - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 Threads)

### Issue description

I created a web server with https support
Issued self signed ssl certificate (OpenSSL 3.2)
Added crt to Certificate bundle override in Godot
When trying to execute HttpRequest in gdscript got error:
E 0:00:14:0222   _do_handshake: TLS handshake error: -9984
  <C++ Source>   modules/mbedtls/stream_peer_mbedtls.cpp:89 @ _do_handshake()

Without https all works as intended
In browser and in postman all endpoints works with https with no issues

### Steps to reproduce

- create simple web server with 1 endpoint
- issue self signed certificate with openssl 3.2
- secure web server with ssl
- add certificate to godot project settings
- try to execute HttpRequest to web server

### Minimal reproduction project (MRP)

HttpRequest.request() will be enough

**Comment by saierXP** [comment]
In this MRP project #84559 , using Godot's HttpRequest node in c# to access https://www.example.com sometimes gives similar errors.
```
godot   : USER ERROR: TLS handshake error: -27648
godot   :    at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:89)
```

**Comment by Drwalin** [comment]
I am also experiencing the same issue with self signed certificates (which does not include website address obviously). I have https server set up on my machine. I am using this certificate for testing purposes on localhost/LAN networks/VPNs. Adding this certificate in project settings does not change anything.

System:
6.6.10-arch1-1, ryzen 5 3600

The problem is apparent in godot 4.1.3 and godot 4.2.1, both without mono.

I have tested my backend with curl and found out that my server required --insecure option for curl to perform a request, because it didn't work with --cacert option.

**Comment by Pshy0** [comment]
Happening in v4.3.beta2.official [b75f0485b]

**Comment by IGN-Styly** [comment]
Can confirm still happens on 3978628c6cc1227250fc6ed45c8d854d24c30c30

**Comment by IGN-Styly** [comment]
also seems to happen on rc3

**Comment by IGN-Styly** [comment]
something related to compiling is my best guess.

**Comment by IGN-Styly** [comment]
im only trying to use asset lib and this happens

**Comment by akien-mga** [comment]
@IGN-Styly Please edit your comment with more information instead of posting 4 updates in a row, this generates a lot of notification spam.

**Comment by Fifut** [comment]
I have the same issue in my project.

In Godot 4.2.2, to resolve it, I added `set_tls_options(TLSOptions.client_unsafe())` in my HTTPRequest node.

In Godot 4.3, the problem reappeared. The project is exactly the same.
In Godot 4.3, it seems that `set_tls_options(TLSOptions.client_unsafe())` is not being taken into account.

**Comment by Faless** [comment]
If the client certificate does not have the correct common name associated
with it, you need to use TLSOption.client_unsafe and specify the
certificate you want to pin (see
https://docs.godotengine.org/en/stable/classes/class_tlsoptions.html#class-tlsoptions-method-client-unsafe
)
Alternatively, you should give the proper common name (DNS name) to the
certificate.
If client_unsafe is not working in 4.3, it might be a regression.
I'll be AFK for another week, I'll try to investigate when I'm back.

**Comment by IGN-Styly** [comment]
Godot it self trying to access the asset lib gets tls handshake error. no code written make a project go to the asset lib and you get the error. tried mutiple compile options and prebuilt bin.

**Comment by Faless** [comment]
If your issue is with asset lib please open a new issue with the proper
information (Godot version, OS, etc).
This issue is about self signed certificates.

**Comment by IGN-Styly** [comment]
The issues are related, or the same one. can't make an issue as currently my mouse is broken.

**Comment by Faless** [comment]
I'm pretty confident they are not related (and definitely not the same).
One is about self signed certificates (which needs special handling).
Your issue is about the asset library, which has a valid (i.e. not self
signed certificate), and which we didn't get any other report about, so
it's probably something specific about your configuration.

**Comment by zorro0799** [comment]
> 我的项目里也存在同样的问题。
> 
> 在 Godot 4.2.2 中，为了解决这个问题，我添加了`set_tls_options(TLSOptions.client_unsafe())`HTTPRequest 节点。
> 
> 在 Godot 4.3 中，问题再次出现。项目完全一样。 在 Godot 4.3 中，似乎`set_tls_options(TLSOptions.client_unsafe())`没有考虑到这一点。

Same problem, same project just upgraded to godot 4.3, then RESULT_TLS_HANDSHAKE_ERROR error

**Comment by Faless** [comment]
Opened https://github.com/godotengine/godot/issues/96170 to track the 4.3 regression regarding `TLSOptions.client_unsafe` reported by @Fifut .

Updated the title of this PR to reflect the OP issue and opened https://github.com/godotengine/godot-docs/pull/9847 to update and clarify the documentation around TLS certificates in project settings.

We should track Asset Library related issue in https://github.com/godotengine/godot/issues/96103

**Comment by NervenCid** [comment]
> Opened #96170 to track the 4.3 regression regarding `TLSOptions.client_unsafe` reported by @Fifut .
> 
> Updated the title of this PR to reflect the OP issue and opened [godotengine/godot-docs#9847](https://github.com/godotengine/godot-docs/pull/9847) to update and clarify the documentation around TLS certificates in project settings.
> 
> We should track the issue reported around the Asset Library in #96103

I wonder if that works for Websockets served in wss
