### ISSUE TITLE
Typing anything in shader editor without node selected crashes godot

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8595]
Godot 3.0 april 30th build Kubuntu 17.04 x64

Godot exits with console message "type is:"

STR: Open shader editor by pressing "Shader" menu button on bottom panel. Type anything into editor.

**Comment by karroffel** [comment]
possibly the same bug as #8314

**Comment by suptoasty** [comment]
I found that this problem is only present with the shader tab when starting the project. Making a material then adding a shader still works just fine.

**Comment by Ahmed0425** [comment]
This bug had been mentioned many times #8489

**Comment by reduz** [comment]
Yeah, shader should just not be visible

**Comment by akien-mga** [comment]
Closing as duplicate of #8314.
