### ISSUE TITLE
Setget inconsistent behaviour when modified by whole variable v.s. single property

### ISSUE THREAD

**Issue by EviTRea** [godotengine/godot#85952]
### Tested versions

Reproduced in both 4.2 and 4.0

### System information

Godot v4.2.stable (46dc27791) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 Ti (nvidia) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

![圖片](https://github.com/godotengine/godot/assets/32661913/c8cbd50c-6f06-47d0-98a5-04cd64f9b89c)
In this example, the vec_2 variable will only accept changing itself to (1, 1).
If I try to assign any Vector2 other than (1, 1), the value won't be set, since the vec_2=new_vec was never called, which is the intentional behaviour of setter function.
HOWEVER. Setting vec_2 directly with the x or y value will set the value directly, but the setter function gets called nonetheless.

So, why would this be a problem?
I was making multiple variables that modify each other, to avoid infinite loop, I wrote 
"if new_vec != vec: vec = new_vec, modified == true" in the setter, 
then used the "modified" var to determined if it should modify the other values.
But since in the other variable, I directly modify the x y property, by the time it reaches the line, vec is always new_vec, because it got modified before the setter function was called, therefore my "modified" bool never went true. 

If instead of "vec.x = new_x", 
I write "vec = Vector2(new_x, vec.y)",
then it works as intended.
Which...is just unintuitive. I wasted an hour of my life figuring out this nonsense.
If this is somehow intentional, it should at least be a whole "WARNING!!" section in the documentation.

### Steps to reproduce

1.Open the project
2.Run, see the print output
3.Uncheck the bool or change it in script
4.Run again, compare the output

### Minimal reproduction project (MRP)

[ScriptTest.zip](https://github.com/godotengine/godot/files/13622737/ScriptTest.zip)

**Comment by Exerionius** [comment]
Interesting that for the second case the setter is called, but the value is already set:

```GDScript
print("Set function called. Current: %s, new: %s" % [vec_2, new_vec])
```

will print:

```
Set function called. Current: (2, 0), new: (2, 0)
(2, 0)
Set function called. Current: (2, 2), new: (2, 2)
(2, 2)
```

In other languages the setter won't be even called for that case. The members of Vector are modified, not the reference/value of the Vector itself, why is the setter called?

**Comment by AThousandShips** [comment]
> not the reference/value of the Vector itself, why is the setter called?

There is no reference to the values, the setter has to be called because `Vector2` is *not* a reference type

This works if you do:
```gdscript
var vec_2_inner := Vector2.ZERO

var vec_2: Vector2:
    set(new_vec):
        print(Set Function Called")
        if new_vec == Vector2(1, 1):
            vec_2_inner = new_vec
        print(vec_2_inner)
    get:
        return vec_2_inner
```
Which AFAIK is the recommended way if you need tight control over the updating

This being a bug or not is a difficult question, as it depends on how the exact behavior is expected to work

**Comment by Exerionius** [comment]
> the setter has to be called because Vector2 is not a reference type

Ah, now it makes total sense.

But it's still weird that the setter is called when the vector value has already been modified, not before.

**Comment by AThousandShips** [comment]
It seems that the version without the getter might do some manipulation in place and *then* calls the setter, might be a bug, but might be a limitation on the system, the safe solution is to always define both the getter and setter

CC @dalexeev @vnen is this a quirk, intended, or a bug?

**Comment by vnen** [comment]
Definitely a bug. I'm not sure why this is happening though, will have to test it.
