### ISSUE TITLE
Importing a OBJ mesh into a MeshInstance2D completely messes its transforms

### ISSUE THREAD

**Issue by Azagwen** [godotengine/godot#85963]
### Tested versions

Reproductible in v4.2.stable.mono.official [46dc27791]
Not Reproductible in v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 30.0.15.1165) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

I'm doing a 2D game in a very polygonal/vector style, and I was planning on using 2D Meshes.
However, upon re-importing my meshes in 4.2, I noticed that all of them were incorrectly scaled in the 2D Viewport, despite their actual (Node2D) scale not changing.

## The situation in Godot `v4.2.stable.mono.official [46dc27791]`
What I expected the mesh to look like (screenshot from Blender, the mesh is built on the XZ axis, and exported to use Y as up, so it should be on XY in Godot)
![image](https://github.com/godotengine/godot/assets/30528331/a1930506-bb45-4efa-a32a-3693b3c2074a)

The mesh in Godot's 2D viewport, it was clearly offset to the bottom left, and squished on one axis. Its visual scale is also immensely smaller than the export scale.
![image](https://github.com/godotengine/godot/assets/30528331/5bb6da5b-00d0-4f9c-a4f2-2b2eab670151)

The MeshInstance's full hitbox (the model isn't even visible anymore)
![image](https://github.com/godotengine/godot/assets/30528331/192bce3b-144c-418a-94ff-0fe26adae953)

## Double-checking
Now, to Check that I wasn't just going Insane or doing something wrong, I tried to create a completely new project AND a completely blank blend file with this mesh that I quickly cobbled together.
![image](https://github.com/godotengine/godot/assets/30528331/e3d27d49-dcd7-4479-b5bf-96e509c6b74c)

However, when I imported it to Godot, I was met with this, and to double check that it was also doing what I described above...
![image](https://github.com/godotengine/godot/assets/30528331/b88935ab-d317-44db-9010-1efb6c3188db)
... I superposed the blender viewport and Godot viewport, and this mesh seems to also be squished, with no intervention on my part 
![image](https://github.com/godotengine/godot/assets/30528331/8655da87-5597-4304-8ccb-6eae7c022882)

## Checking in Godot 4.1
To be fully sure, I imported the same OBJ meshes in Godot `v4.1.3.stable.official [f06b6836a]`.
Which seems to work as expected
![image](https://github.com/godotengine/godot/assets/30528331/90b50966-4a23-4223-9105-13038cdd222a)
![image](https://github.com/godotengine/godot/assets/30528331/14a914cb-4ee3-4b60-9762-195cb346731d)

### Steps to reproduce

- Create a flat mesh in Blender (or any software of your choice)
- Export that mesh as a OBJ, so that it should be aligned with the XY plane
- Import it in a fresh Godot project
- Create a 2D scene, and add a MeshInstance2D to it
- Assign your mesh to the MeshInstance2D's mesh field
- Verify that its Hitbox matches its bounds, and that it wasn't deformed or moved around by the importer

### Minimal reproduction project (MRP)

4.2 and 4.1 Projects used in this report linked below
[godot_4.1_bug_hunt.zip](https://github.com/godotengine/godot/files/13624429/godot_4.1_bug_hunt.zip)
[godot_4.2_bug_hunt.zip](https://github.com/godotengine/godot/files/13624431/godot_4.2_bug_hunt.zip)

**Comment by clayjohn** [comment]
This seems to be caused by the new mesh compression option. 

You can fix the problem by disabling mesh compression in the import settings:

![image](https://github.com/godotengine/godot/assets/16521339/783ee336-87c7-4551-80f8-d45265ca3989)

I can think of two possible engine changes that would help alleviate this issue:
1. We could detect if the z channel is used in the vertex positions, if z is always 0, we could assume the mesh is 2D and disable compression
2. We could add a callback that disables compression if the mesh is used in 2D (we do something similar for textures where we enable compression if used in 3D)

**Comment by Azagwen** [comment]
> This seems to be caused by the new mesh compression option.
> 
> You can fix the problem by disabling mesh compression in the import settings:
> 
> ![image](https://private-user-images.githubusercontent.com/16521339/289306282-783ee336-87c7-4551-80f8-d45265ca3989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNDg5NzMsIm5iZiI6MTcwMjE0ODY3MywicGF0aCI6Ii8xNjUyMTMzOS8yODkzMDYyODItNzgzZWUzMzYtODdjNy00NTUxLTgwZjgtZDQ1MjY1Y2EzOTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE5MDQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODVlZjhlM2U3MWM0ZWIzZGJkNWYzNTVkZDE0NzBmNGJiZmIzMGRmMzQ0OTU3ZGI2ZjAyNDcyOGRlMGRlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvaCsHlKBoTKsJWoL4OHof7HZv5lUwgrjOwWYPIN3as)
> 
> I can think of two possible engine changes that would help alleviate this issue:
> 
>     1. We could detect if the z channel is used in the vertex positions, if z is always 0, we could assume the mesh is 2D and disable compression
> 
>     2. We could add a callback that disables compression if the mesh is used in 2D (we do something similar for textures where we enable compression if used in 3D)

I can confirm that this seems to fix it! I hadn't thought of trying this 😅

**Comment by clayjohn** [comment]
> > This seems to be caused by the new mesh compression option.
> > You can fix the problem by disabling mesh compression in the import settings:
> > I can think of two possible engine changes that would help alleviate this issue:
> > ```
> > 1. We could detect if the z channel is used in the vertex positions, if z is always 0, we could assume the mesh is 2D and disable compression
> > 
> > 2. We could add a callback that disables compression if the mesh is used in 2D (we do something similar for textures where we enable compression if used in 3D)
> > ```
> 
> I can confirm that this seems to fix it! I hadn't thought of trying this 😅

To be fair, its a new option and it wasn't needed before. We are still figuring out how to make the option more visible to users as there are cases where it will be needed. 

In this case though, I think we can figure out an in-engine fix that won't require you to toggle the option. Its just a workaround for now

**Comment by GrauBlitz** [comment]
I can also confirm this issue in v4.3-dev5 with .glb files.
