### ISSUE TITLE
Editor rendering issue on Windows on ARM device since 4.2

### ISSUE THREAD

**Issue by Lenbot-QC** [godotengine/godot#85961]
### Tested versions

4.2.stable

### System information

Godot v4.2.stable - Windows 10.0.22621 - GLES3 (Compatibility) - D3D12 (Qualcomm(R) Adreno(TM) 685 GPU) () - Snapdragon (TM) 8cx Gen 2 @ 3.0 GHz (8 Threads)

### Issue description

well~ i have full interests in using godot engine and now i am a Chinese graduate which has more free time to learn it. but it seems that there is a bug when i use Godot 4.2 stable version - although the workspace might run well, i feel a bit confused when i **create a new project or add one node**, the places of settings will **show incorrectly** when i try to **maximize the setting window and restore it** (luckily, only show incorrectly, the settings can still run correctly).
i am using Windows 11 on ARM laptop to run Godot engine 3/4 - it can runs well in using OpenGL compatibility Pack in Microsoft Store (awesome!!! but of course, only GLES2/GLES3). but this bug **does not exist** in **Godot 4.1.3 stable version** or before (iMPORTANT...), and i have tried to restart many times, the bug didn't disappear. i will upload the main screenshot as well.
now i have rollbacked in Godot 4.1.3 stable. so i hope this bug can be solved in Godot 4.2.1 or as quickly as possible, or... i'd like to find everyone's help? (tears of joy~)

### Steps to reproduce

1. i try to create new project, or add one node.
2. i maximize the setting window.
3. i restore the setting window.
4. the places of settings show incorrectly.

### Minimal reproduction project (MRP)

it can appear when i try to create new project so there is no nessesary to upload a project.godot... maybe?

**Comment by Calinou** [comment]
Can you take a screenshot of the rendering issue and upload it here?

**Comment by Lenbot-QC** [comment]
i found that if i try to minimize the main window (godot workspace) and reopen it, the places of setting will be corrected. i feel OK but i think other people don't like this way perhaps haha. (tears of joy)

**Comment by Lenbot-QC** [comment]
approximately like this...
![Screenshot 2023-12-09 205445](https://github.com/godotengine/godot/assets/115386612/2a019287-a97d-4b34-ac5a-d996e700715a)
well i have tried your method already, and runs a little bit slower, luckliy there shows no errors, thanks a lot! (Victory~)

**Comment by Calinou** [comment]
@bruvzg It sounds like it may be worth forcing ANGLE on Windows on ARM, since it lacks any native OpenGL support.

**Comment by bruvzg** [comment]
There's OpenCL and OpenGL Compatibility Pack (ms-windows-store://pdp/?productid=9NQPSL29BFFF), but IIRC it's software Mesa based, so enabling ANGLE by default is probably better (and should work without installing extra packages).
