### ISSUE TITLE
NavigationAgent3D: target_desired_distance works relatively on path_desired_distance

### ISSUE THREAD

**Issue by evilenzo** [godotengine/godot#85970]
### Tested versions

Reproducible in 4.2

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4617) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

In 3d navigation target desired distance is ignored when path desired distance is greater than it. I don't think these two variables should be in such dependency

### Steps to reproduce

See the MRP. We have agent with `path desired distance` set to 5m and `target desired distance` set to 1m. But it stops on 5m before the last point (just click left mouse to start moving character to point). Use path debug visuals. You can also try to change path desired distance and see that it affects distance to target on navigation finish

### Minimal reproduction project (MRP)

[MRP Distance.zip](https://github.com/godotengine/godot/files/13625376/MRP.Distance.zip)

**Comment by evilenzo** [comment]
Short version: `target desired distance` less than `path desired distance` just doesn't work. It is being ignored. And I don't think anyone expects such behaviour

**Comment by evilenzo** [comment]
@Calinou no need in testing, I just checked Godot sources. 

As we can see you check target_desired_distance here
https://github.com/godotengine/godot/blob/b94eb58d35b3dd8a9f522bc90df0db73862ef326/scene/3d/navigation_agent_3d.cpp#L826

But it is in loop that works with condition that checks path desired distance
https://github.com/godotengine/godot/blob/b94eb58d35b3dd8a9f522bc90df0db73862ef326/scene/3d/navigation_agent_3d.cpp#L768

**Comment by evilenzo** [comment]
More than that
https://github.com/godotengine/godot/blob/b94eb58d35b3dd8a9f522bc90df0db73862ef326/scene/3d/navigation_agent_3d.cpp#L854
This event is never called. You will get `navigation_finished` event, but not `target_reached` event in that case

**Comment by smix8** [comment]
PR https://github.com/godotengine/godot/pull/82561

**Comment by evilenzo** [comment]
Duplicate
