### ISSUE TITLE
Console closes when error received with debugging enabled

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8597]
**Operating system or device - Godot version:**
v2.1.3 latest

**Issue description:**
Exporting a debugging enabled game when there is an error, causes you to NOT see the error, because it closes the console and game client.

Example: 
![](https://i.gyazo.com/6ec25d64496c4abf9708bdd01024a4eb.gif)
And these are two errors with that scene preview:
![image](https://cloud.githubusercontent.com/assets/10387670/25568084/56479a38-2db0-11e7-9dd7-db587c76b8a1.png)

And the game client still works fine. _This is good!_

## HOWEVER

If you try the same thing when exported **with debugging enabled**, look what happens:
![](https://i.gyazo.com/542f3a43b44f071a3ae2153d7fcc5bd5.gif)

I'm not sure if that is intended, but shouldn't the game client just close, and the console remain open so we can see the error messages still? Instead of everything closing?

**Comment by Dillybob92** [comment]
This is actually becoming pretty funny. Godot is trolling me I think :P. I originally thought those two errors were causing the client to crash but they weren't.. as I fixed those and the problem is still happening.

When I preview the game in the editor (works fine, no errors). Now, when I export, I get [this](https://camo.githubusercontent.com/bd2f2ca8d822bdf370ac7bf040e3bc85004a411a/68747470733a2f2f692e6779617a6f2e636f6d2f35343266336134336234346630373161336165323135336437666363356264352e676966) (same as above).

How in the world can I debug my game now lol! I can change the window position so I can see the console, then record the screen and replay it back in a video player frame by frame to read the messages?  Then post those here?

**Comment by vnen** [comment]
Mandatory question: does the export templates matches the editor version?

You can start the game using the command prompt, the errors will remain there after the program closes.

**Comment by Dillybob92** [comment]
@vnen, yeah, the same 2.1.3 export templates

Okay, so I did the cmd prompt -> game.exe

and it showed a bunch of resource loading errors it couldn't load because some folders were

textures/image.png

but the real directory was

Textures/image.png

So I went through all my tscn files and changed the lowercase `t` to a capital `T`.  Seems to be working now.

I wonder why when previewing the scene in the editor these errors don't show, but when you export the game, the directories are case sensitive. In any event, it's working now thanks @vnen, for the help

**Comment by vnen** [comment]
On Windows paths are case-insensitive, which is not the case within the `.pck` filesystem.

**Comment by Dillybob92** [comment]
But I am still using windows while previewing the game and the errors don't show? Also, I just don't want other people to run into this problem. I am suggesting that the console never closes for errors on exported games (when debugging is enabled). Other people will run into this same issue I'm pretty sure :P
