### ISSUE TITLE
Editor freezes on Linux after returning from Suspend to RAM

### ISSUE THREAD

**Issue by nwallenfang** [godotengine/godot#85997]
### Tested versions

- Reproduced on 4.2.stable

### System information

Ubuntu 22.04 - Vulkan API 1.3.224 - Forward+ -  NVIDIA GeForce 940MX

### Issue description

When waking up from suspend, the editor is frozen and this error gets printed in a loop:
`ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2536)
ERROR: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST
   at: swap_buffers (drivers/vulkan/vulkan_context.cpp:2536)
ERROR: Vulkan: Did not create swapchain successfully. Error code: VK_NOT_READY
`

### Steps to reproduce

- Open any project
- Suspend the machine to RAM ("Suspend" on Ubuntu)
- Wake up the machine
- The editor is frozen and the mentioned Vulkan error message gets printed in a loop

### Minimal reproduction project (MRP)

This issue already occurs with an **empty project**.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52738. This is a NVIDIA issue we can't fix on our end without [large sweeping changes](https://github.com/godotengine/godot-proposals/issues/6423). All other applications using Vulkan on Linux run into the same issue unless they can restart their rendering context entirely in a clean manner (preferably without losing any data).

You may try following the advice on this page at your own risk: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
