### ISSUE TITLE
UI Icons not rendering for `Group Editor` Window

### ISSUE THREAD

**Issue by KartikWatts** [godotengine/godot#85992]
### Tested versions

- Reproducible in: v4.2.stable.arch_linux
- Not Reproducible in: v4.1.3.stable.official [f06b6836a]

### System information

Garuda Linux (2.6.19-2)

### Issue description

A minor issue where UI Icons are not rendering on the Group Editor window, attaching a screenshot for reference:
![Screenshot_604](https://github.com/godotengine/godot/assets/22623256/c366164a-3d9a-4dcf-97a0-199b5a5a7ecc)

The icons were expected for Buttons like Add, Remove, Filter, etc.

### Steps to reproduce

Select any Node and go to the `Node` panel, click `Manage Groups` and the window will open.

### Minimal reproduction project (MRP)

Minor issue, easily reproducible following the above steps.

**Comment by Chaosus** [comment]
However, I cannot reproduce it on Windows:

![изображение](https://github.com/godotengine/godot/assets/3036176/d54d3409-2fbf-4ba4-948c-eb4e052516f7)

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.stable (Linux):

![image](https://github.com/godotengine/godot/assets/180032/54860729-d50d-4202-83f0-7531d951aa36)

Are you using a custom editor theme in the Editor Settings by any chance?

**Comment by YuriSizov** [comment]
It may be hard to trigger, but the code responsible for setting these icons is incorrect in a way that will lead to this kind of issue. I'll submit a PR shortly.
