### ISSUE TITLE
This code have problem

### ISSUE THREAD

**Issue by jhj2017** [godotengine/godot#85999]
### Tested versions

4.2.stable

### System information

Windows 11

### Issue description

#GDScript V4.2  ,  code problem

### Steps to reproduce

```gdscript
	var t1={
		a=0.0 as float
	}
	var t2=1.0
	for i in range(0,10):
		t1.a += 0.1
		print(t1.a)
	if t1.a >= t2:
		print("yes")
	else:
		print("no")
	print(t1.a ," " , t2)
```

#print result is   "no"   ,   but the right print is  "yes"

### Minimal reproduction project (MRP)

![20231210204910](https://github.com/godotengine/godot/assets/26403277/c99323dd-7899-4ac3-9c70-050f39c8782a)

**Comment by AThousandShips** [comment]
This is a simple case of floating point precision issues, you can't expect summing up of floating point values to exactly match due to rounding limitations

To see this do this for the last line:
```gdscript
print("%.20f" % t1.a ," " , "%0.20f" % t2)
```
And you will see

This is not a bug but a simple reality of floating point numbers

**Comment by Chaosus** [comment]
Comparison of floating-point numbers has been discussed several (thousand?) times, in short, you should use `is_equal_approx` function if you need such comparison. I think this issue should be closed since it is already been clearly documented.
