### ISSUE TITLE
NatigationRegion3D dont work bake NavMesh button

### ISSUE THREAD

**Issue by yatebyaeby** [godotengine/godot#85995]
### Tested versions

- Repruduce : v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 Threads)

### Issue description

NavMesh Bake button do nothing

### Steps to reproduce

Follow this tutorial 
https://www.youtube.com/watch?v=EOocBMBbL-E

Having this scene 
![image](https://github.com/godotengine/godot/assets/129945583/d89ad13c-0171-4cb0-b6d1-bad3205e4383)
Click for bake mesh
![image](https://github.com/godotengine/godot/assets/129945583/8e667837-953b-4230-bd7b-05a439da0e09)
(left button)

Nothing happen. Mesh not loads/creates

### Minimal reproduction project (MRP)

[NavigationRegion3D Test bake.zip](https://github.com/godotengine/godot/files/13627438/NavigationRegion3D.Test.bake.zip)

**Comment by smix8** [comment]
The source geometry needs to have enough surface area for your agent size.

Your source geometry is a single world unit box mesh while the NavigationMesh default agent_radius is 0.5 units, so there is not enough surface area left to have anything traversable.

**Comment by yatebyaeby** [comment]
> Your source geometry is a 1m box mesh while the NavigationMesh default agent_radius is 0.5m, so there is not enough surface area left to have anything traversable.
You are right and iam fool, i think topic may be closed
