### ISSUE TITLE
Exported android game crashes on change_scene_to_file

### ISSUE THREAD

**Issue by theBSH** [godotengine/godot#86002]
### Tested versions

4.2 stable mono

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

when using change scene in my game the game crashes and I don't know how to debug it or if there is even a way as there is no errors(if there  is in the mrp its bks i deleted assets with out really doing anything to the code).

### Steps to reproduce

i will put MRP but i just deleted all the extra levels in my main project , cus i could not reproduce in a new project.
1- export the project for android (.net 8 required)

### Minimal reproduction project (MRP)

[Export problem.zip](https://github.com/godotengine/godot/files/13628134/Export.problem.zip)

**Comment by AThousandShips** [comment]
Does it work if you comment out the `Label.hide()` line after changing scene?

**Comment by theBSH** [comment]
@AThousandShips after going throw hell to debug i found out that the problem is the player if you delete him the game does not crash, you have any idea on how i can fix this ?

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community)

**Comment by theBSH** [comment]
change net from 6 to 7 in .csproj file and now its fine

**Comment by AThousandShips** [comment]
Indeed, as per the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/index.html#c-platform-support)
