### ISSUE TITLE
Control::_size_changed() is slower than necessary

### ISSUE THREAD

**Issue by colugomusic** [godotengine/godot#86011]
### Tested versions

Reproducible in any Godot version AFAIK. I am using Godot 3.5 but I can see from looking at the code that the relevant code has not changed in Godot 4. I would submit a pull request but I only made the change for Godot 3.5 and can't figure out how to submit it, if that's even possible (sorry I'm dumb)

### System information

Any OS

### Issue description

`Control::_size_changed` needlessly propagates `NOTIFICATION_RESIZED` even when the control node is not visible. This can be fixed by simply checking `is_visible_in_tree()` as shown in this commit: https://github.com/colugomusic/godot/commit/7dc44b51be6d365802cb0086dd4058a1ec7a6dbd

In my test case this results in about a ~50% performance increase of `Control::set_size` and seems to break nothing (`_size_changed` is already re-fired anyway when the control becomes visible.) I assume the performance difference you will see depends on how deeply nested your control subscenes are.

My use case is probably not typical of the average Godot project (I am working on an application and not a game and make very heavy use of control nodes.) So that is maybe why nobody has flagged this up as an issue before.

### Steps to reproduce

Use control nodes.

### Minimal reproduction project (MRP)

Any project that uses control nodes.

**Comment by AThousandShips** [comment]
You should figure out the implications on 4.x first, a 3.x specific change if it appears on 4.x isn't going to be accepted

**Comment by colugomusic** [comment]
I won't be doing that as I don't use or care about Godot 4.

**Comment by AThousandShips** [comment]
Well, that's a shame, you can open a 3.x specific change but others will say the same, a 3.x exclusive improvement is unlikely to be accepted if it's not unique to 3.x

**Comment by colugomusic** [comment]
I will likely just be creating a fork of 3.5 for my own purposes but maybe there is someone out there who will feel that my claim of a 50% performance improvement by changing one line of code is worth investigating.

**Comment by colugomusic** [comment]
This can actually be optimized even further by moving the check to `is_visible_in_tree` to the very start of `_size_changed()` and just returning if the control is not visible. Again, when `NOTIFICATION_VISIBILITY_CHANGED` is handled then `_size_changed` will be re-fired anyway.
You might be thinking "can't the user just check visibility before calling `set_size`/`set_position`?" That doesn't help because `_size_changed` will be entered recursively for every child node, so if the root node is visible but it contains invisible children, they will all still be updated pointlessly.
Depending on how many nodes you are updating and how deeply nested they are this can be a severe performance bottleneck.

**Comment by jsjtxietian** [comment]
Yes the performance gain is pretty huge

> `_size_changed` is already re-fired anyway when the control becomes visible

And with this I think it's maybe safe to apply your change, but be careful, as `_size_changed` will change some internal state which maybe quried by user, so it's not safe to early return.

**Comment by colugomusic** [comment]
> Yes the performance gain is pretty huge
> 
> > `_size_changed` is already re-fired anyway when the control becomes visible
> 
> And with this I think it's maybe safe to apply your change, but be careful, as `_size_changed` will change some internal state which maybe quried by user, so it's not safe to early return.
> 
> In general if it's safe to do so I prefer the lazy approach, aka, when the control becomes visible then we propagates `NOTIFICATION_RESIZED`.

This is a good point. If a user is calling `get_size()` or `get_position()` to query the size and position of invisible controls then this might be a breaking change for them since the geometry will not be updated until the control is next made visible. Perhaps that is why the control class was written this way.

Personally it doesn't seem worth it to recursively calculate the geometries of every invisible child node just in case the user wants to query them. I have a pretty big (150,000 lines) godot project which uses control nodes for pretty much everything (because it's an application and not a game) and I can tell you that this optimization doesn't break anything, so apparently I am never querying the size/position of invisible things ever.

If the size of a control is actually relevant then usually I am connecting to the 'resized' signal anyway, which would be fired when the control becomes visible, so it makes sense that everything still works in my case.

**Comment by jsjtxietian** [comment]
Yes it depends on whether invisible control should affect other control immediately, let's wait for relevant godot member to decide :)

**Comment by colugomusic** [comment]
Closing this because i think the much better solution is for the user to remove nodes entirely from the scene tree when they are not visible, instead of using `hide()` and `show()`, which results in a far greater speedup than the optimizations i presented here.
