### ISSUE TITLE
Rounded rectangles in SVG files rendering incorrectly

### ISSUE THREAD

**Issue by Justin113D** [godotengine/godot#86012]
### Tested versions

- Reproductible in all 4.x versions, including 4.1.2 rc1
- Not reproductible in release version 3.5.3

### System information

Godot v4.2.1.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4617) - 12th Gen Intel(R) Core(TM) i9-12900KF (24 Threads)

### Issue description

Rectangles with rounded corners in SVG files are not rendered correctly.

### Steps to reproduce

1. Create a new project
2. Create a file called "test.svg" in the project
3. Paste the following SVG content into the file:

	```xml
	<svg width="256" height="256" xmlns="http://www.w3.org/2000/svg">
		<rect fill="white" width="256" height="256"/>
		<circle fill="black" cx="115" cy="115" r="115"/>
		<rect fill="white" width="256" height="256" rx="115"/>
	</svg>
	```
4. View the output

In 3.5.3 the white rectangle overlays the circle perfectly, as it should.
In all 4.x versions, the rounded corners of the white rectangle are not perfectly circular, exposing the black circle behind it.

| 3.5.3 	| 4.X 	|
|-------	|-----	|
| ![oldGodot](https://github.com/godotengine/godot/assets/41839896/74b767d8-ccd6-4d3c-8051-cfa88189b38c) | ![](https://github.com/godotengine/godot/assets/41839896/f1504eab-511c-4ed0-a8de-65a507532c4d) |

### Minimal reproduction project (MRP)

[SVGError_Project_3.5.3-stable.zip](https://github.com/godotengine/godot/files/13628985/SVGError_Project_3.5.3-stable.zip)
[SVGError_Project_4.2.1-rc1.zip](https://github.com/godotengine/godot/files/13628984/SVGError_Project_4.2.1-rc1.zip)

**Comment by Kiisu-Master** [comment]
thorvg issue probably : https://github.com/thorvg/thorvg/issues/1824

**Comment by MewPurPur** [comment]
It's inside a release of ThorVG now: https://github.com/thorvg/thorvg/releases/tag/v0.11.6

**Comment by Justin113D** [comment]
I recompiled 4.2.1-stable with ThorVG updated to 0.11.6 and can confirm that this fixes it! Thanks for the help!
