### ISSUE TITLE
Using method name without class fails to create static callable

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#86032]
### Godot version

v4.2.stable.official [46dc27791]

Using external editor Visual Code.

### System information

Windows 11

### Issue description

I preload a script from a `@tool` script where i try to call a static from another static function.

Resulting error:
>   res://non_tool.gd:8 - Invalid get index 'compare_ascending' (on base: 'Nil').

### Steps to reproduce

Minimal example attached.

---

Code used:

`non_tool.gd`
```gdscript
extends RefCounted

static func compare_ascending(lhs: String, rhs: String) -> bool:
	return lhs < rhs

static func get_engine_components() -> Array[String]:
	var engine_components: Array[String] = ["b", "c", "foo", "d"]
	engine_components.sort_custom(compare_ascending)
	return engine_components

```

`Control.gd`

> `@tool` can also be removed and is not required for it to fail.
```gdscript
@tool
extends Control

const NonTool := preload("non_tool.gd")


func _init():
	print(NonTool.get_engine_components())

```
### Minimal reproduction project

[invalid_index_base_nil.zip](https://github.com/godotengine/godot/files/13636907/invalid_index_base_nil.zip)

**Comment by AThousandShips** [comment]
Please fill in the issue template properly, do not erase any of the headings, this is not a proper report

**Comment by IceflowRE** [comment]
> Please fill in the issue template properly, do not erase any of the headings, this is not a proper report

I created an issue from a comment, thus the template was not available. Will add the template now.

**Comment by AThousandShips** [comment]
Please add all required details and don't link to some other comment for details 🙂, it should be as self contained as possible so people don't have to run around

Also it has to be related to the engine functioning, make sure the plugin is actually valid before reporting things here

**Comment by AThousandShips** [comment]
Does it work if you name the class and use:
```gdscript
static func get_engine_components() -> Array[String]:
	var engine_components: Array[String] = ["b", "c", "foo", "d"]
	engine_components.sort_custom(MyClass.compare_ascending)
	return engine_components
```

**Comment by IceflowRE** [comment]
> Does it work if you name the class and use:
> 
> ```gdscript
> static func get_engine_components() -> Array[String]:
> 	var engine_components: Array[String] = ["b", "c", "foo", "d"]
> 	engine_components.sort_custom(MyClass.compare_ascending)
> 	return engine_components
> ```
> 
> I suspect this might be an issue with anonymous classes

This works.

**Comment by AThousandShips** [comment]
Then this seems like an issue where it doesn't discover that this is a static callable, and instead try to use the non-static one

CC @dalexeev @vnen WDYT

**Comment by AThousandShips** [comment]
Does it work with a named class *without* the `MyClass`? To narrow down

**Comment by AThousandShips** [comment]
Then the bug seems to be that when creating a callable it doesn't check for static alternatives without the class name, I'd say this is a bug, but the principle of least astonishment

**Comment by IceflowRE** [comment]
> To confirm your note, `@tool` is not required yes?

yes
