### ISSUE TITLE
The UI is not on the far right when the color selector alpha value is 255

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot#86030]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Windows 11- Godot v4.2.stable.official [46dc27791] - Vulkan (Forward+)

### Issue description

![image](https://github.com/godotengine/godot/assets/46812028/f57e3f30-b3c4-4a83-8793-64a58bd18220)

### Steps to reproduce

Create a new project and select a color in modulate

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Can you reproduce this with **Interface > Editor > Display Scale** set to **100%** in the Editor Settings?

**Comment by ModuleCode** [comment]
![image](https://github.com/godotengine/godot/assets/46812028/b667adbe-5414-4af8-98c9-0fa9b688090e)
![image](https://github.com/godotengine/godot/assets/46812028/dccbf5ea-801d-40bd-808e-337d1151dfc9)
yes
