### ISSUE TITLE
Godot won't run on GLES2

### ISSUE THREAD

**Issue by Tabby152** [godotengine/godot#86048]
### Tested versions

4.2.stable 
Doesn't happen in 3.6.dev

### System information

Windows 10 - Intel i3 M370 - Intel HD Graphics 

### Issue description

People keep telling me godot 4.2 runs on opengl 2 ,However it doesn't work on my device which has opengl 2 , Godot 3.6 dev works but 4.2 doesn't I tried using the opengl32.dll trick but didn't work

### Steps to reproduce

no code

### Minimal reproduction project (MRP)

no project included in the issue

**Comment by AThousandShips** [comment]
4.x does not support GLES2, this is documented [here](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#disadvantages-of-upgrading)

Closing as this is a documented limitation and 4.x simply does not support GLES2, nor will it in the future

Thank you for your report
