### ISSUE TITLE
No picker mode is recorded after the next switchover

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot#86063]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Windows 11- Godot v4.2.stable.official [46dc27791] - Vulkan (Forward+)

### Issue description

When I switch picker mode the next time I open it should be the pick mode I selected last time but it's not

https://github.com/godotengine/godot/assets/46812028/522c8b55-14cf-4781-963f-a465a03c9432

### Steps to reproduce

Toggle a picker mode off and on again

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
The default color picker mode is set in the Editor Settings, but I agree it would be better to remember the last color picker mode across all color picker instances (also in running projects). This should also be persisted to disk (on projects, this would work on a per-project basis).

**Comment by TheSofox** [comment]
While this is being done, should it also remember the Color Mode too (RGB/HSV/etc.)?

**Comment by TheSofox** [comment]
Created pull request, it stores both values as it seemed to make sense.
