### ISSUE TITLE
Mobile renderer `light_cull_mask` is not respected

### ISSUE THREAD

**Issue by victorbstan** [godotengine/godot#86062]
### Tested versions

Godot 4.2

### System information

Mac OS 14.1.2 (23B92) (M2), Godot 4.2, Mobile renderer

### Issue description

Mobile renderer does not take into account light cull mask settings correctly

<img width="1796" alt="Screenshot 2023-12-12 at 8 04 16 AM" src="https://github.com/godotengine/godot/assets/315297/c5759d69-f761-4111-8fa2-a4e0d08e5a43">
<img width="1796" alt="Screenshot 2023-12-12 at 8 03 47 AM" src="https://github.com/godotengine/godot/assets/315297/f379f559-bd92-47c5-ac91-1a1bc232a096">

### Steps to reproduce

When using an OmniLight, with meshes on Layer 1 and 2, and setting OmniLight's `light_cull_mask` to Layer 2, and setting project renderer to Mobile, and playing the scene, (Editor may display correctly), see that OmniLight is displayed on mesh it is not supposed to. There also another problem, if you look closeley, you will see that lighting is brighter in Mobile renderer, because the light is both baked as well as displayed on top of baked meshes, It should not be displayed onto baked meshes, only onto dynamic/non-static meshes. (so there are at least two problems visible here)

### Minimal reproduction project (MRP)

[Light Cull Mask Mobile Issue.zip](https://github.com/godotengine/godot/files/13644796/Light.Cull.Mask.Mobile.Issue.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82263.

> There also another problem, if you look closeley, you will see that lighting is brighter in Mobile renderer, because the light is both baked as well as displayed on top of baked meshes, It should not be displayed onto baked meshes, only onto dynamic/non-static meshes. (so there are at least two problems visible here)

This is being tracked in https://github.com/godotengine/godot/issues/85145.

**Comment by amarraff** [comment]
I'm experiencing this problem right now in v4.2.1.stable.official [b09f793f5]

I'm trying to have an omni light only light a specific layer, but it's still lighting every layer.

**Comment by Calinou** [comment]
@amarraff As mentioned in my comment above, the issue is already being tracked in https://github.com/godotengine/godot/issues/82263.

**Comment by amarraff** [comment]
> @amarraff As mentioned in my comment above, the issue is already being tracked in #82263.

I did check it out, but my issue related more to the description of the one mentioned here than the one in #82263.
