### ISSUE TITLE
Collision shapes are drawn in wrong color and collision contact points are not drawn at all

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8607]
**Ubuntu - Godot version: 3.0 master**

**Issue description:**
Collision display debug options, draw collision shape in wrong color (gray instead one selected in Project Settings) and don't draw contact points at all.

**Comment by eon-s** [comment]
On master f527a6946 , 2D shapes (if correspond to this issue):

Shapes on KinematicBody2D do not draw points at all, on RigidBody2D is ok.
CircleShape2D and CapsuleShape2D do not show even on editor.

------------

On 3D shapes I see black on RigidBody shapes, white/gray on the rest, also lines seem to cast and receive shadows.

**Comment by reduz** [comment]
is this better now?

**Comment by karroffel** [comment]
Still have the problem

![wflg0lh](https://user-images.githubusercontent.com/5209613/27253115-96daa2e6-536e-11e7-8d54-d1af88795552.png)

**Comment by n-pigeon** [comment]
@reduz 
Still all are light grey and no collision contact dot. :<

**Comment by eon-s** [comment]
On 2D are fine (the visuals, not the polygon edition) and 3D are still affected by light (black/light color), I can see the collision point but is affected by light too.
