### ISSUE TITLE
Custom resource (ArrayMesh) icons are not displayed in resource selector menu and breaks the mesh preview.

### ISSUE THREAD

**Issue by MAGGen-hub** [godotengine/godot#86072]
### Tested versions

Reproducible in v4.2.stable.arch_linux

### System information

Arch Linux - Godot v4.2.stable.arch_linux

### Issue description

I am working on my custom ArrayMesh class (IcosphereMesh).
After adding `@icon("res://icon.svg")` and restarting the project I figured out that icon is displayed only when resource already set:
![image](https://github.com/godotengine/godot/assets/56871670/e69c2a14-a757-43f2-acf3-740b0ce8f60a)

But in selector menu it has standart resource icon:
![image](https://github.com/godotengine/godot/assets/56871670/b437efa8-c6c2-4d7b-8b59-d7dc791ef0bf)

Also as you can see on the first picture - custom ArrayMesh icon BLOCKS small preview of the mesh 
(preview window is empty) The same picture but with no icon `# @icon("res://icon.svg")` :
![image](https://github.com/godotengine/godot/assets/56871670/f2a8be58-848f-43c8-b9de-dfa5622fd673)

It is not very important bug but it make me feel quite uncomfortable...

Problem related to Resource icons also was mentioned in this issue: https://github.com/godotengine/godot/issues/82624

### Steps to reproduce

1. Create new project
2. Create 3d scene
3. Add MeshInstance3d to main scene node
4. Create custom class that `extends ArrayMesh`
6. Create a simple surface to be shown in mesh preview display windows
7. Set `MeshInstance3d.mesh` parameter to your custom mesh class
8. Put `@icon("res://icon.svg")`  at the start of class script
9. Reload project
10. Open main scene
11. Open Inspector of MeshInstance3d
12. Unwrap `MeshInstance3d.mesh` property in MeshInstance3d inspector
13. Right click `MeshInstance3d.mesh` to open mesh selector menu.

Results: 
1. Small preview window will be empty,it will show only setted icon and no more. (Bug not affects big preview window in `MeshInstance3d.mesh` inspector)
2. In menu selector your custom array mesh class will have default resource icon that is not equal to "res://icon.svg"

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/13648057/project.zip)

Thank you for your attention and sorry for my bad English. Good luck in engine development.

**Comment by alessandrofama** [comment]
I've looked into this and the reason the icons are not displayed (also true for gdextension classes) is that we try to get the editor theme icon for the type and default to the `Object` icon if our type isn't in there, which is true for custom resources with the '@icon' annotation and gdextension classes with the `icon` property specified in the .gdextension file :

https://github.com/godotengine/godot/blob/84e205b5a17bfe7ace96b78c410ec10aa52241d2/editor/editor_resource_picker.cpp#L519
Calling `EditorNode::get_class_icon` instead would fix this issue, but I'm sure if it has other implications.

**Comment by YuriSizov** [comment]
> Calling `EditorNode::get_class_icon` instead would fix this issue, but I'm sure if it has other implications.

This would be correct, and in fact the entire lookup routine before this call should be removed in favor of `EditorNode::get_class_icon`. (The whole thing with populating and using `custom_resources`).

**Comment by alessandrofama** [comment]
>the entire lookup routine before this call should be removed [...]

I believe currently the lookup routine before the call has no effect/will never set `is_custom_resource` to true. This is because custom resource types are not added to the allowed types in `_add_allowed_type`. It seems that this functionality was removed here: https://github.com/godotengine/godot/pull/71683.

As a result, custom resources added via `add_custom_type` in an editor plugin will never appear in the picker. The related issue can be found here: https://github.com/godotengine/godot/issues/75245. (I didn't know about this, found it now 👀). Might be worth looking into that issue first?

`class_name` resources work correctly, as the lookup does not involve them.

**Comment by YuriSizov** [comment]
> As a result, custom resources added via `add_custom_type` in an editor plugin will never appear in the picker.

Ah, right, this is what it's for. If these old school custom classes are not working currently, I think it's safe to remove the code as I initially suggested. If we ever want to fix the other issue, we'd need to integrate icon lookup in `EditorNode::get_class_icon`/`EditorNode::get_object_icon` anyway.
