### ISSUE TITLE
Script heat colors are not adjusted to new theme (they blend with background)

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8608]
** Godot version: 3.0 master**

**Issue description:**
![selection_086](https://cloud.githubusercontent.com/assets/6152134/25576626/f8abcf46-2e60-11e7-9d66-3f86a306cad8.png)

**Comment by ArcFutahito** [comment]
Having them exposed to theme resource would be great

**Comment by akien-mga** [comment]
Fixed by #8631.
