### ISSUE TITLE
--dump-extension-api-with-docs produces incorrect documentation for some data types

### ISSUE THREAD

**Issue by migueldeicaza** [godotengine/godot#86080]
### Tested versions

4.3-dev, d76c1d0e516fedc535a2e394ab780cac79203477 the first commit after 4.2

### System information

MacOS Sonoma 14.0

### Issue description

MacOS 

### Steps to reproduce

Run the Godot editor with the option --dump-extension-api-with-docs

And it seems to be filling some stubs for Vector operations with the stock documentation for it

Consider Vector4i, the operator '/' instead of producing this:

```
Divides each component of the [Vector4i] by the given [float].
```

Gets this node:

```
Divides each component of the [Vector4i] by the given [int].
```

Judging from my tool, this only happens for the Vector types:

```
 generated-builtin/Vector2.swift                     |   18 -
 generated-builtin/Vector2i.swift                    |   15 -
 generated-builtin/Vector3.swift                     |   30 --
 generated-builtin/Vector3i.swift                    |   15 -
 generated-builtin/Vector4.swift                     |   18 -
 generated-builtin/Vector4i.swift                    |   19 -
```

### Minimal reproduction project (MRP)

No need for a project.

**Comment by akien-mga** [comment]
CC @rburing

**Comment by AThousandShips** [comment]
> Consider Vector4i, the operator '/' instead of producing this:

*the* operator? There are two divide operators? Are you sure you are generating your output correctly?

**Comment by AThousandShips** [comment]
It does indeed use the same description for each operator, will look at the generation code and see if there's some issue there

**Comment by rburing** [comment]
Sorry, I overlooked this. I can fix it, but if you're already on it then go ahead.

**Comment by AThousandShips** [comment]
You go ahead, I was just looking into it 🙂

**Comment by AThousandShips** [comment]
Gave up on my tweaking with this, but one observation for fixing this:
The extension generates operators that *isn't* in the documentation, for example `String operator%` generates for each type, but the documentation only contains one, for `Variant` (so the check needs to do some check for this)
