### ISSUE TITLE
Drag & Drop intellisense with inferred type not working

### ISSUE THREAD

**Issue by Dharmang92** [godotengine/godot#86108]
### Tested versions

- Reproducible in: 4.2.1 Stable
- Testing working functionality in: 4.2 Stable and 4.1 Stable

### System information

Windows 11 - Godot v4.2.1-stable - Vulkan (Forward+)

### Issue description

I have a timer as shown in the attached image. When I tried to drag the timer to the script and use the dot notation to autocomplete the in-built functions of the Timer class, I didn't get suggestions.

While in v4.1 opening the same project gave intellisense.
![image](https://github.com/godotengine/godot/assets/29101013/5e5088d9-8e61-4d4b-a5b4-8deb37cd915b)

### Steps to reproduce

1. Create a Timer
2. Drag and drop in the gdscript editor.
3. Try to invoke the start method.

### Minimal reproduction project (MRP)

[Test DnD.zip](https://github.com/godotengine/godot/files/13658039/Test.DnD.zip)

**Comment by Dharmang92** [comment]
Tested in v4.2 stable in which it is working fine. There seems to be an issue between 4.2.1 and 4.2

**Comment by akien-mga** [comment]
Likely a regression from #79386, CC @HolonProduction @godotengine/gdscript
