### ISSUE TITLE
Godot Crashes when opening Scenes Containing GPUParticle2D Nodes in Compatibility Mode on Macs with M2 Chip

### ISSUE THREAD

**Issue by chemscobra** [godotengine/godot#86100]
### Tested versions

-Reproducible in Godot v4.2.1 stable
-Not reproducible in Godot v4.2 stable

### System information

Godot v4.2.1.stable - macOS 14.1.2 - GLES3 (Compatibility) - Apple M2 - Apple M2 (8 Threads)

### Issue description

Issue Description:
I am experiencing a consistent issue with Godot v4.2.1.stable  on my Mac with an M2 chip. Whenever I attempt to open scenes that contain GPUParticle2D nodes while in compatibility mode, the engine fails to load the scene and Godot Crashes.
It does not happens with Godot v4.2 stable

### Steps to reproduce

Steps to Reproduce:

Open Godot Engine on a Mac with an M2 chip.
Switch to compatibility mode (if not already in this mode).
Attempt to open a scene that includes a GPUParticle2D node.
Expected Behavior:
The scene should open normally, allowing for editing and interaction with the GPUParticle2D nodes.

Actual Behavior:
The scene fails to open, and the engine crashes.

### Minimal reproduction project (MRP)

Try to open de main.tscn scene file
[Test Project.zip](https://github.com/godotengine/godot/files/13654293/Test.Project.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/72469.

This is a consequence of https://github.com/godotengine/godot/pull/85785, as ANGLE is no longer used by default on macOS as it caused performance issues. As a result, GPU-based particles are broken again on macOS by default when using the Compatibiltiy rendering method.
