### ISSUE TITLE
3D Editor not work properly

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#86109]
### Tested versions

reproducible in 4.2.stable, 4.1.stable, 4.0.stable and all other 4.x

### System information

Windows 10 - Godot 4.2 stable - OpenGL 3 (Compatibility) - CPU Intel Pentium G2030 - Ram 8GB - AMD Radeon HD 5570

### Issue description

https://github.com/godotengine/godot/assets/92402263/40f1f7e2-cdee-4efe-909f-bdf0682a7206

for each change in the 3d Scene, I need to reload the project

### Steps to reproduce

just create a new project with Compatibility and import a new 3d model

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
> AMD Radeon HD 5570

This GPU is too old, try switching to ANGLE backend, in the `Project Settings` change `Rendering` → `GL Compatibility` → `Driver.windows` to `opengl3_angle` save and restart the editor (Note: in the current master, ANGLE should be auto selected for this GPU).

**Comment by Calinou** [comment]
Can you test 4.2.1, which includes https://github.com/godotengine/godot/pull/85273?
