### ISSUE TITLE
Can't load Jolt in Godot built from custom source.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#86126]
### Tested versions

4.3 from latest source

### System information

windows 10

### Issue description

I have to build my Godot from source (I can't use the prebuilt version), however, now Jolt won't work even with latest Jolt version.
I get this error:

> src\register_types.cpp:124 - Godot Jolt failed to load due to not supporting Godot 4.3. This version of Godot Jolt (0.11.0) only supports Godot 4.2.
>   core\extension\gdextension.cpp:748 - GDExtension initialization function 'godot_jolt_main' returned an error.
>   Failed loading resource: res://addons/godot-jolt/godot-jolt.gdextension. Make sure resources have been imported by opening the project in the editor at least once.

I was able to do it prior to 4.2.1

### Steps to reproduce

Built Godot from latest source and use Jolt in a project.

### Minimal reproduction project (MRP)

Any project, with Jolt and Godot from latest source.

**Comment by akien-mga** [comment]
That's not a bug, as the error message tells you:

> Godot Jolt failed to load due to not supporting Godot 4.3. This version of Godot Jolt (0.11.0) only supports Godot 4.2.

So you should use Godot 4.2 / 4.2.1 if you want to use Godot Jolt 0.11.0.
