### ISSUE TITLE
Can't import blend file over RPC

### ISSUE THREAD

**Issue by lukebitts** [godotengine/godot#86139]
### Tested versions

4.2-stable

### System information

Godot v4.2.stable.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 09:47:27 +0000 - Tty - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 660 (nvidia; 470.199.02) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

This error happens whenever I try to import a .blend file:

```
  Unexpected status during RPC connection: 4
  Failed to connect to Blender via RPC, switching to direct imports of .blend files. Check your proxy and firewall settings, then RPC can be re-enabled by changing the editor setting `filesystem/import/blender/rpc_port` to 6011.
 ```

This error is from a new godot project with a single blend file inside, with a single cube inside.

**What I tried so far**

- I ran Godot from the terminal using --verbose:

```
Socket error: 111
Connection to remote host failed!
ERROR: Unexpected status during RPC connection: 4
   at: do_import_rpc (modules/gltf/editor/editor_import_blend_runner.cpp:236)
```
(There were no other relevant messages after that)

- Then I tried to investigate the [editor_import_blend_runner](https://github.com/godotengine/godot/blob/master/modules/gltf/editor/editor_import_blend_runner.cpp) file, and came across the PYTHON_SCRIPT_RPC variable.
- I used the command "blender --background --python-expr" to run the same script as PYTHON_SCRIPT_RPC. This worked perfectly and I even managed to send a test rpc command from another script to generate a GLTF file (so I don't think its some internal network/firewall issue)

Is there anything else I can try before building and debugging Godot itself?

### Steps to reproduce

There are no steps, this happens on a new project importing a single .blend file.

### Minimal reproduction project (MRP)

N/A

**Comment by lukebitts** [comment]
That does fix the problem!

**Comment by AThousandShips** [comment]
This is not solved yet, but looks like this is a duplicate of:
* https://github.com/godotengine/godot/issues/85446

So leaving closed
