### ISSUE TITLE
Saving the code while a timer is still running results with a crash

### ISSUE THREAD

**Issue by kBlankii** [godotengine/godot#86159]
### Tested versions

v4.2.1.rc1.official [daeb1c729], v4.2.stable

### System information

Godot v4.2.1.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

When awaiting a timeout signal of a timer, should any modifications be made and saved to the code within the same script, the game will either freeze or hard-crash upon the signal's return. 
Subsequently, the Godot editor will display either an 'opcode: 0' or 'opcode: 53' error.

### Steps to reproduce

In the MRP, 
1. Press F5 to run the game
2. Hit Spacebar. now a "Timer Start" message should be outputted in the editor.
3. Modify any code within the "Node2D.gd" script (like simply adding another print() command), then save, before the timer ends and outputs "Timer End".
4. An error should occur when the timeout signal returns.

### Minimal reproduction project (MRP)

[await_crash_reproduction.zip](https://github.com/godotengine/godot/files/13674775/await_crash_reproduction.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/42379, as this is due to the same cause.
