### ISSUE TITLE
4.2 editor flickers on 164 Hz monitor (only)

### ISSUE THREAD

**Issue by kappa-ferro** [godotengine/godot#86162]
### Tested versions

The problem started in 4.2 and 4.2.1. 4.1.3 and Godot 3 did not have this issue.

### System information

Windows 10, Nvidia GPU

### Issue description

The screen flashes either white or black (can't see properly, it's too fast). Updating graphics drivers did not fix the issue. Moving and zooming around in the editor seems to agitate it. Haven't tested in-game. The issue immediately and completely disappears when I switch the editor to my 60 Hz screen. I read something about Windows variable refresh rate from earlier posts. Enabling or disabling the setting made no difference. I am using a DisplayPort connector.

### Steps to reproduce

Open the editor with a 164 Hz display, and wait a while, possibly zoom and move the viewport.

### Minimal reproduction project (MRP)

The issue is with the editor, as all projects suffer from it the same.

**Comment by sonic2kk** [comment]
Might indeed be specific to Windows, on Arch Linux using KDE Plasma Wayland on a 7900XTX (Mesa 23.2.1) Godot 4.2 runs fine for me on my 165Hz display via XWayland. I'm unsure if there's a way to see what rate the editor is running at, but it works fine.

**Comment by Maran23** [comment]
I have somewhat the same problem, but only in the game. 
The window flickers black sometimes.
I have a screen with 240 Hz.
Just changed the value to 60 Hz and indeed it disappeared.

Any idea what change may caused this?

**Comment by Calinou** [comment]
See this FAQ item: https://docs.godotengine.org/en/latest/tutorials/troubleshooting.html#the-editor-stutters-and-flickers-on-my-variable-refresh-rate-monitor-g-sync-freesync

**Comment by Maran23** [comment]
> @Maran23 Are you running the game in a window or fullscreen? If in fullscreen, are you using the Fullscreen or Exclusive Fullscreen window mode in the Project Settings?

No, only in window mode. It does not happen all the time. Like 1 out of 5 tries when starting the game.

I stripped down the game a bit and recorded it.

https://github.com/godotengine/godot/assets/66004280/03efd114-780a-4506-a620-49c055f1fef7

**Comment by kappa-ferro** [comment]
Turning off G-sync resolved the issue on my main monitor as well. Odd that this didn't come up until now. Should I close this issue now or wait for @Maran23's problem to be solved? Sorry, new to GitHub.

**Comment by kappa-ferro** [comment]
I just re-enabled G-sync, and the flicker either didn't return or is unnoticeable. Either way there is nothing more to ask on my end.

**Comment by Calinou** [comment]
Closing as this can't be reproduced consistently, and is likely a VRR-related issue. Maran23's issue should be tracked separately.

**Comment by Maran23** [comment]
> Closing as this can't be reproduced consistently, and is likely a VRR-related issue. Maran23's issue should be tracked separately.

I will experiment a bit and also check the AMD drivers. Then I will create an issue with as much information I can get.

**Comment by Maran23** [comment]
> Closing as this can't be reproduced consistently, and is likely a VRR-related issue. Maran23's issue should be tracked separately.

Update from me:
I updated the AMD drivers some days ago to the newest version which came out this year (11.01.2024).
No more flickering now. 

That was also my suspicion, that is why I waited before writing a report.
![image](https://github.com/godotengine/godot/assets/66004280/2e00e8a9-3fd2-4a0f-aa09-586a30b00480)

Cheers.
