### ISSUE TITLE
Exported Node in C# remains null despite being assigned in the inspector

### ISSUE THREAD

**Issue by dznnah** [godotengine/godot#86184]
### Tested versions

**Godot version**
v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When exporting a Node field in script, which is then placed on the node of that same type. It will remain null even when assigned.
This does not happen for nodes that are part of the children, only for the Nodes on the root itself.

node structure:
![Knipsel2](https://github.com/godotengine/godot/assets/145671403/db495eb2-7b8d-48e6-b5d6-afe5d5491869)

Assigning both export fields:
![Knipsel1](https://github.com/godotengine/godot/assets/145671403/2a716c83-9cfe-456f-b344-334158829007)

Trying to GD.Print() both fields:
![Knipsel3](https://github.com/godotengine/godot/assets/145671403/fa05746d-5af7-40da-845b-853dd823210b)

### Steps to reproduce

Open the repro project, run.

In the output will be a value for the AnimationPlayer, and a null where the CharacterBody3D should be.
It will also have a nullref in the Debugger, when the script tries to print a value from the CharacterBody3D.

### Minimal reproduction project (MRP)

[reproNullField.zip](https://github.com/godotengine/godot/files/13680776/reproNullField.zip)

**Comment by plyr0** [comment]
1. Repro: `public partial class testScript : Node3D`
changed to: `public partial class testScript : CharacterBody3D`
no error
```
Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org
<CharacterBody3D#23722984649>
(1, 0, 0)
```
2. 
```
public partial class testScript : Node3D
{
    [Export] private CharacterBody3D characterBody3D;
```
characterBody3D refs to itself(circular)?

Did You meant `CollisionShape3D`?

IMO no error, to be closed.

**Comment by dznnah** [comment]
Ah, I probably misunderstood the system then, was trying to have the testScript derive from a custom class, but that should probably then be its own node in the hierarchy.
Would still expect a warning instead of null though, as the inspector does show it's linked in

**Comment by dznnah** [comment]
Forgot to close this, my bad!
