### ISSUE TITLE
Unexpected crash when updating gui_embed_subwindows to false with extra windows active 

### ISSUE THREAD

**Issue by Starkandco** [godotengine/godot#86203]
### Tested versions

Reproducible in 4.1.3, 4.2 stable

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

NB: Tested on the root viewport.

gui_embed_subwindows being updated during runtime with windows active causes strange results. 

I see that this makes sense if you take it as given that this value represents that the root viewport should or should not have external windows, and we have some and are setting it to not be able to have any, so presumably there are some underlying functions that won't interact with the external windows as expected in this state. (And vice versa for embedded)

On the off chance someone else is having trouble with this: I have been able to workaround the issues by ensuring that any external windows are freed prior to updating the value when external windows are present. I assume alternatively you could reparent them to another viewport in the interim if your use case for some reason requires they be retained. 

```func _process(_delta):
	if Input.is_action_just_pressed("debug"):
		if get_child_count() > 0:
			get_child(0).queue_free()
			await get_tree().process_frame
		get_tree().root.get_viewport().gui_embed_subwindows = !get_tree().root.get_viewport().gui_embed_subwindows
	elif Input.is_action_just_pressed("debug_2"):
		if get_child_count() > 0:
			get_child(0).queue_free()
		var new_window = window_scene.instantiate()
		add_child(new_window)
```

Alternatively I feel that having multiple viewports and not relying on changing the gui_embed_subwindows value to manage external Vs. embedded windows in your game is probably the **sanest** approach.

### Steps to reproduce

See MRP

"1" - Spawns a window, freeing the previous
"2" - Change the gui_embed_subwindows value
"3" - Try to hide the first window in the list

Pressing 1, 2, and then 3 results in a crash as we start by spawning an external window, changing gui_embed_subwindows to true, then attempt to interact with the external window by hiding hiding it

Pressing 1, 2, and then 1 results in an orphaned window which godot doesn't have in the remote tree  This changes visually to being entirely full of black once it is refreshed by e.g. resizing it.

Starting by pressing 2 once and then any combination of 1 and 3 will seemingly not result in the same issues, nor will you run into an issue after pressing 2 again regardless of the embedded window state e.g. 2 - 1 - 2 - 1 or 2 - 1 - 3 - 1. 

Edit: With 2 - 1 - 2 - 3 - 3 - 3 we end up with our previously embedded window as an external window, while still retaining the embedded window. When toggling its visibility it switches between a broken embedded window and hidden external window, and a working embedded window with a working external window. 

So it seems like the first hide after switching from embedded windows to external toggles a new active external window representation of the node, and upsets the logic behind hiding the original embedded representation 

### Minimal reproduction project (MRP)

[Min_crash_repro.zip](https://github.com/godotengine/godot/files/13687858/Min_crash_repro.zip)

**Comment by Starkandco** [comment]
Obviously not a major priority. Crashing is not ideal so could use better error handling, but now the issue is clearer to me I know what to avoid and I don't think the system necessarily should function in the way I am trying to make it. I am happy that the value can be changed in some manner for my purposes :)

**Comment by AThousandShips** [comment]
That's what the discussion is for, there's likely no simple way to handle this, what happens if a window is outside the parent window? What about the data in it? Recreating a window embedded or non-embedded isn't entirely simple I'd say so it has some consequences

The simple solution would be to prevent this when there are child windows, but it needs to be investigated and discussed

**Comment by Starkandco** [comment]
I agree on your suggested approach - to prevent updates with child windows if possible sounds sensible to me
