### ISSUE TITLE
collision_disabled not working

### ISSUE THREAD

**Issue by nathantew14** [godotengine/godot#86201]
### Tested versions

reproducible on v4.2.stable.official [46dc27791]

### System information

macOS Ventura 13.6.1

### Issue description

https://github.com/godotengine/godot/assets/40333518/8733229f-6566-443f-9678-de11a9b0fceb

When I trigger `die` with a button, `collision_disabled` is set to true and it works as expected. Player can phase through the blocks and the enemy.

When the enemy triggers the `die` instead, although `collision_disabled` is seemingly also set to true, everything works as if it wasn't. Player can't phase through blocks and the enemy continues to hit the player.

And for some incomprehensible reason, if `die` is triggered by other means, such as using collision detection in the `enemy` script, then the bug does not happen:
```
if collider is Player:
	print('enemy hit player (collision)')
	collider.die()
```

### Steps to reproduce

As described above.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/13687183/test.zip)

**Comment by AThousandShips** [comment]
This is not the place to ask for help to debug your code, for support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error.

**Comment by AThousandShips** [comment]
As your bug report is about a feature you yourself added this isn't a valid bug report, please follow the instructions above and if you find a bug *in the engine* please open a *new* report with those details

We do not offer help to fix people's code 🙂
