### ISSUE TITLE
AnimationPlayerEditor doesn't preview the Animation when seeking Animation Playback Tracks

### ISSUE THREAD

**Issue by arose26** [godotengine/godot#86217]
### Tested versions

- Reproducible in 4.2 stable.
- Same error doesn't occur in 4.1.3 (previews work as they should)

### System information

Windows 11 - Godot 4.2 stable

### Issue description

When I create a regular animation of any property it will playback in the editor fine as I move the play head. However, if I add these individual animations as Animation Playback Tracks to a new AnimationPlayer, moving the head no longer plays previews.
This is inconvenient as I wish to sync different object animations and have to do it blind.

### Steps to reproduce

Create a regular animation, then add the entire Animation Player to a new animation player as 'Animation Playback Track'. Try to move playhead. The preview of the animation will not play.

### Minimal reproduction project (MRP)

N/A

**Comment by Helpsypoo** [comment]
The original submission covers it, but I made this gif before realizing the issue was reported already, so adding it in case it's helpful. The gif shows the scrubbing working on 4.0.2 but not 4.2.

![noscrubs](https://github.com/godotengine/godot/assets/3430112/98e45bec-476e-4b30-909d-8f11103f420c)
