### ISSUE TITLE
The "set_shader_parameter" method on ShaderMaterial does not appear as a valid method in the editor

### ISSUE THREAD

**Issue by Johnrobmiller** [godotengine/godot#86215]
### Tested versions

4.2

### System information

Windows 11

### Issue description

The simplest bugs are oftentimes the most frustrating and time-consuming to deal with.

In this scenario, valid methods on the `material` class do not appear in the autofill in the editor, as seen in the screenshot. This falsely informs the user that the method is invalid, essentially lying to them in a way.

Bugs like this ought to be high priority as they cause significant distress and are probably very quick to fix.

![image](https://github.com/godotengine/godot/assets/55205360/13856d1e-459a-45de-9e48-dba6afc36914)

### Steps to reproduce

see the screenshot above

### Minimal reproduction project (MRP)

see the screenshot above

**Comment by Johnrobmiller** [comment]
I think that no autofill is better than an unreliable autofill. Either way, you have to look up everything manually anyhow, and at least the no autofill version wouldn't mislead the user

**Comment by clayjohn** [comment]
Are you thinking of the function `set_shader()`? `set_shader_material()` doesn't exist. But `ShaderMaterial` does have a function called `set_shader()`. 

To me, it seems like the real issue is that the autofill doesn't show the name of a function if the name is fully typed out. In my opinion, the autofill should be showing `set_shader()` as the top option.

**Comment by Johnrobmiller** [comment]
> Are you thinking of the function `set_shader()`? `set_shader_material()` doesn't exist. But `ShaderMaterial` does have a function called `set_shader()`.
> 
> To me, it seems like the real issue is that the autofill doesn't show the name of a function if the name is fully typed out. In my opinion, the autofill should be showing `set_shader()` as the top option.

My apologies, I should have clarified. I was not referring to the `set_shader()` method, but rather the `set_shader_parameter()` method.

The method `set_shader_parameter()` exists on type `ShaderMaterial`. However, when I begin to type in `set_shader` into the edidor, it does not appear in the autofill, suggesting that it is a non-existing method.

**Comment by clayjohn** [comment]
I see. The fact that neither `set_shader()` or `set_shader_parameter()` are appearing might indicate that none of ShaderMaterial's methods are included. `inspect_native_shader_code()` is a method of `Material`, so maybe the only results that are appearing are those for `Material`

**Comment by Johnrobmiller** [comment]
Yes, that makes sense.

In the code snippet, I cast `mat` as a `ShaderMaterial`, but maybe the cast failed and it still thinks it is the base `Material` class.

Regardless, the editor ought to automagically know what type of Material is being used, because otherwise the user would be required to do those casts everytime they want to correctly type their matieral (and they would have no way of knowing they should do this to begin with, which is a problem)

**Comment by Calinou** [comment]
Does it work if you use `var mat := material as ShaderMaterial` instead of `var mat: ShaderMaterial = material? These are not strictly equivalent (what I suggest is considered type-safe in more scenarios).

**Comment by Chaosus** [comment]
@F3der1co Did you check it on the latest 4.3 beta? I see it was fixed:

![изображение](https://github.com/godotengine/godot/assets/3036176/36a24b75-192e-4a4d-8123-e59d320e4d3a)

**Comment by F3der1co** [comment]
I am super confused now, it works for me correctly in 4.3 beta 2. But where I encountered it was also in 4.3 beta 2. 
Either I was doing something incorrectly or there was a different cause. But I'd say this can be closed now as it seems to work for me as expected when I try it now.

**Comment by Chaosus** [comment]
Ok, closed as completed

**Comment by ToufouMaster** [comment]
and i have the same issue.
![image](https://github.com/godotengine/godot/assets/68186078/b763edae-4962-4b77-8c49-2f1a4c7e0357)
![image](https://github.com/godotengine/godot/assets/68186078/950bd794-6ede-4996-b2e6-343f4a35b643)
![image](https://github.com/godotengine/godot/assets/68186078/9878f1a3-a29a-49f5-8455-21cbd3f19662)
as you can see... and i have no idea why

**Comment by F3der1co** [comment]
you wrote `paramer` instead of `parameter`
You need to type the variable, because otherwise Godot doesn't know if the material is a ShaderMaterial or CanvasItemMaterial
