### ISSUE TITLE
When try to add GPUParticles2D, It breaks and close the engine. MacOs

### ISSUE THREAD

**Issue by ariannmichael** [godotengine/godot#86237]
### Tested versions

- Reproducible: 4.2.1, 4.1.3, 4.0.4

### System information

MacOs - Godot 4.2.1 - Compatibility

### Issue description

Try to add the GPUParticles2D node, either as a new scene or a used one.

<img width="1003" alt="Screenshot 2023-12-16 at 16 15 04" src="https://github.com/godotengine/godot/assets/16283747/71fe72bc-559e-4ba9-b7fb-244bc41565ce">
![image](https://github.com/godotengine/godot/assets/16283747/5e67100d-7331-4b95-9dfb-2bc3bc0462e7)

### Steps to reproduce

Try to add the GPUParticles2D node, either as a new scene or a used one.
![image](https://github.com/godotengine/godot/assets/16283747/53c95070-1fef-4c61-b487-0b0ccc1695fb)

### Minimal reproduction project (MRP)

[GPUParticles2D_Bug_Test.zip](https://github.com/godotengine/godot/files/13693734/GPUParticles2D_Bug_Test.zip)

**Comment by ariannmichael** [comment]
If I use it as Foward+, it works.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/72469.
