### ISSUE TITLE
Some decals do not rendered on mobile renderer

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#86230]
### Tested versions

4.2.1 / f8a2a9193662b2e8c1d04d65e647399dee94f31e

### System information

Windows 11, GTX 4080

### Issue description

Some decals do not render at all on Mobile renderer:

![изображение](https://github.com/godotengine/godot/assets/3036176/1685ac3c-1aa8-4467-829a-4e97417cef40)

while its correct on Forward+:

![изображение](https://github.com/godotengine/godot/assets/3036176/fb7893df-56e6-407d-bee6-c1ac40d6959c)

### Steps to reproduce

Create several decals and try to use them in mobile renderer.

### Minimal reproduction project (MRP)

[DecalTest.zip](https://github.com/godotengine/godot/files/13692311/DecalTest.zip)

**Comment by QbieShay** [comment]
For posterity: 8 decal is the intended limit for the mobile vulkan renderer https://docs.godotengine.org/en/stable/classes/class_decal.html
