### ISSUE TITLE
Godot Soft Shadows are Looking Weird

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#86231]
### Tested versions

-4.2.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.3742) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

Godot's soft shadows are looking bad and i think it is a good point to fix it.
![image](https://github.com/godotengine/godot/assets/78092286/8cdbfaad-5807-4f27-9059-8759b2f08fdb)
even in max settings:
![image](https://github.com/godotengine/godot/assets/78092286/df14c2b6-9b02-479e-8170-405daad96aa3)
you can notice the grainy shadow

### Steps to reproduce

-Open Godot
-Check shadows

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
These are limitations if the rendering methods and occur in any real time lighting, also I can't see any graininess in the max settings screenshot

Have you read [this](https://docs.godotengine.org/en/stable/tutorials/3d/lights_and_shadows.html)?

**Comment by NotRabug50** [comment]
> These are limitations if the rendering methods and occur in any real time lighting, also I can't see any graininess in the max settings screenshot
> 
> What are your suggestions for improvements? What methods should be used? 🙂
> 
> Have you read [this](https://docs.godotengine.org/en/stable/tutorials/3d/lights_and_shadows.html)?

idk too much about lighting but in other engines (flax unreal unity) shadows are looking soft and smooth. also if you look very closely you can see the grain

**Comment by AThousandShips** [comment]
Can you actually see the graininess from in actual usage? And did you read the instructions for how to modify and tweak shadows?

Generally improvements are welcome, but without any solid ideas it's not much that can be done, right? We aren't neglecting shadow quality, so some suggestions to how to fix it would be welcome, as you point out that "it is a good point to fix it" 🙂, assumed you had ideas for how to accomplish that

**Comment by NotRabug50** [comment]
> Can you actually see the graininess from in actual usage? And did you read the instructions for how to modify and tweak shadows?
> 
> Generally improvements are welcome, but without any solid ideas it's not much that can be done, right? We aren't neglecting shadow quality, so some suggestions to how to fix it would be welcome, as you point out that "it is a good point to fix it" 🙂, assumed you had ideas for how to accomplish that

i think better softing algorithms can be used like Variance Shadow Mapping (idk too much about it just did some research)

**Comment by AThousandShips** [comment]
I'm sure this is and has been researched by the rendering team, I'd suggest opening a [discussion](https://github.com/godotengine/godot-proposals/discussions) about this, as this is for bugs and there's not really a bug here, just a particular result quality, improvements can be done but without more concrete ideas of how to do it (and considering the results aren't especially bad) I'd say this is the wrong place for it 🙂

**Comment by NotRabug50** [comment]
> I'm sure this is and has been researched by the rendering team, I'd suggest opening a [discussion](https://github.com/godotengine/godot-proposals/discussions) about this, as this is for bugs and there's not really a bug here, just a particular result quality, improvements can be done but without more concrete ideas of how to do it (and considering the results aren't especially bad) I'd say this is the wrong place for it 🙂
> 
> Also while I get the limitations, the visual example is not entirely fair and realistic, as very uniform and flat surfaces show a lot of the imperfections in ways more usual rendering situations do, not to mention the very zoomed in image, that's not to say there aren't areas we can possibly improve, but in real application cases the rendering is very much competivtive, though it's very hard to compete with the AAA, closed source, proprietary engines (though we do dream)
> 
> Rendering has been a major focus during the 4.x cycle, compare with 3.x and you will see how far these improvements have come, so any ideas are welcome, but this isn't, in my opinion, very helpful 🙂

okay thanks for letting me know! see you

**Comment by Calinou** [comment]
For reference, this was already reported in https://github.com/godotengine/godot/issues/53534 and there are PRs to address it when TAA is enableD.
