### ISSUE TITLE
Add support for OpenSSL 1.1.0 or later

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8624]
**Operating system or device - Godot version:**
All, but mainly Linux/*BSD - master.

**Issue description:**
Godot currently can't build against OpenSSL 1.1.0, only against OpenSSL 1.0.x (we ship 1.0.2h in `thirdparty/openssl`).

`modules/openssl/stream_peer_openssl.cpp` should be updated to build against the new API. Ideally, it should be able to build against both 1.0.x and 1.1.0, we might be able to use conditional version checks to use the proper API. Eventually, the bundled source should also be updated so that we can continue benefiting from upstream security fixes.

**Workaround:**
For the time being we should probably default to using the bundled openssl code on X11 (`builtin_openssl=yes`). Most people providing unofficial binaries don't pay attention to this, and users of distros defaulting to OpenSSL 1.1.0 can't run those binaries without installing a compat package, when provided.

**Comment by TierraDelFuego** [comment]
Haven't tested this (I just got 3.0 built) but the problem now might additionally be that this old openssl client will not be able to talk to upgraded servers. More and more are disabling insecure ssl and all going to TLS.

**Comment by akien-mga** [comment]
OpenSSL 1.0.x is still supported, so I don't see why it would stop working.

**Comment by henri-nourel** [comment]
hello, 
when i try to build godot 3.0 on Fedora 26 : 
scons platform=x11
```
scons: Reading SConscript files ...
Error: Found system-installed OpenSSL 1.1.0f, currently only supporting version 1.0.x.
Aborting.. You can compile with 'builtin_openssl=yes' to use the bundled version.
```
and when i compile with  'builtin_openssl=yes' : 
scons platform=x11 builtin_openssl=yes
i have : 
```
[Initial build] Compiling ==> core/script_encryption_key.cpp
core/script_encryption_key.cpp:1:10: fatal error: global_config.h: No such file or directory
 #include "global_config.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [core/script_encryption_key.x11.tools.64.o] Error 1
scons: building terminated because of errors
```.

**Comment by akien-mga** [comment]
@henri-nourel Delete `core/script_encryption_key.cpp`, it's an old build artifact which is now replaced by `core/script_encryption_key.gen.cpp`

**Comment by henri-nourel** [comment]
@akien-mga 
i have delete  core/script_encryption_key.cpp, now i have this when i try to build : 
```
[Initial build] Compiling ==> core/global_defaults.cpp
core/global_defaults.cpp:1:10: fatal error: global_config.h: No such file or directory
 #include "global_config.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [core/global_defaults.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Delete `core/global_defaults.cpp` too, and any other that might give similar errors. Or clean all build artifacts with `git clean -fX` and build from scratch.

**Comment by henri-nourel** [comment]
ok thanks, it's work.

**Comment by akien-mga** [comment]
Great :) If you don't mind I will delete our messages as they're not related to adding support for OpenSSL 1.1.0.

**Comment by henri-nourel** [comment]
ok
