### ISSUE TITLE
`MenuButton` hover position does not scale with the scale factor multiplier

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot#86240]
### Tested versions

Reproducible in 4.2.1

### System information

Godot v4.2.1.stable - openSUSE Tumbleweed 20231210 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 6GB (nvidia) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

MenuBar and MenuButton's `switch_on_hover` property is not working properly when the scale factor multiplier is other than 1. The position the cursor needs to be in order for a PopupMenu to appear seems to be the one where the scale factor multiplier 1. In other words, the hover position is not scaling with the scale factor multiplier and remains constant. This results in a weird behavior, as seen in the below video.

https://github.com/godotengine/godot/assets/35376950/aa7cb8d6-fbe5-43b9-9b40-330ff65fa2c6

(Scale multiplier is set to 1.5 in the video)

The bigger the distance from 1, the weirder the behavior gets. Note that this also occurs when the scale is less than 1.

Interestingly, this doesn't seem to happen to the Godot editor itself.

### Steps to reproduce

Create a project with a MenuBar node with PopupMenu items, or multiple MenuButtons as siblings and enable "Switch on Hover". Go to the project settings, General tab, Display, Window and set the Scale to something other than 1. Run the project, click on a menu button and move your cursor around to switch on a sibling menu button on hover. You can see that the position is wrong.

### Minimal reproduction project (MRP)

[MenuButtonHoverBug.zip](https://github.com/godotengine/godot/files/13693910/MenuButtonHoverBug.zip)

**Comment by Calinou** [comment]
>  (This is a video, not sure why it isn't embedded. Scale multiplier is set to 1.5 in the video.)

Remember that for GitHub video previews to work, you need to have a blank line before *and* after the video URL.

**Comment by OverloadedOrama** [comment]
> > (This is a video, not sure why it isn't embedded. Scale multiplier is set to 1.5 in the video.)
> 
> Remember that for GitHub video previews to work, you need to have a blank line before _and_ after the video URL.

Oops, fixed it! Thanks for letting me know.
