### ISSUE TITLE
RichText + BBCode: background is rendered on non rendered characters

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#86251]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - macOS 14.2.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

To achieve the "typewriter effect" in my dialogue system (characters appearing on the screen gradually instead of all at once), I'm using Visible Characters / Visible Ratio property of RichTextLabel node. This works great with BBCode and it's very practical (thank you to whoever implemented it!) because I don't have to worry about calculating text size and adjusting the calculations for the length of BBCode tags.

But, when characters have background and I'm rendering them using "Visible characters behavior: After shaping", the whole background of the whole paragaph is rendered even though the actual glyphs aren't.

Here is what it looks like in practice:
![Godot render background ahead](https://github.com/godotengine/godot/assets/106015575/e26c80c6-336f-4fe1-b802-7f8e792e6248)

You can see that even when the Visible Ratio is set to 0, the area under the glyphs is colored in red.

### Steps to reproduce

Add this to any RichTextLabel:
[bgcolor=RED](Hit button A to skip Minimal reproduction project (MRP) text line.)[/bgcolor]

Now try to slide the "Visible Ratio" property of the RichTextLabel and you'll see that the background color stays on the screen.

### Minimal reproduction project (MRP)

RichTextLabel

**Comment by Calinou** [comment]
cc @bruvzg
