### ISSUE TITLE
Visual shader custom node can not set default value by overriding '_get_input_port_default_value' function

### ISSUE THREAD

**Issue by SmallKi** [godotengine/godot#86253]
### Tested versions

4.2.stable

### System information

Windows11, GLES3

### Issue description

I can not set VisualShaderCustomNode's default value by overriding '_get_input_port_default_value' .

The code below shows I want to set default values for two input ports, but had no effect. 
``` gdscript
func _get_input_port_name(port):
	match port:
		0:
			return "scale"
		1:
			return "offset_speed"

func _get_input_port_type(port):
	match port:
		0:
			return VisualShaderNode.PORT_TYPE_SCALAR
		1:
			return VisualShaderNode.PORT_TYPE_VECTOR_2D

func _get_input_port_default_value(port:int):
	match port:
		0:
			0.
		1:
			Vector2(1, 1)

```

If comment the '_get_input_port_default_value' func, and ues 'set_input_port_default_value' in '_init' func, it works!! 

```gdscript
func _init():
	set_input_port_default_value(0, 0.)
	set_input_port_default_value(1, Vector2(.5,.5))
	pass

#func _get_input_port_default_value(port:int):
#	match port:
#		0:
#			0.
#		1:
#			Vector2(1, 1)
```

You have must to comment the '_get_input_port_default_value' func and then the  `set_input_port_default_value` func will work. 

So I think the '_get_input_port_default_value' do take some effect, but not what I expected. 
Is this a bug? Or my misuesd this func?  
I cannot find more detailed document about this. 
![image](https://github.com/godotengine/godot/assets/37371850/896bef7e-c29f-4581-bed0-5e5ff57d2f4c)

### Steps to reproduce

Extends VisualShaderCustomNode and you will see

### Minimal reproduction project (MRP)

N/A

**Comment by SmallKi** [comment]
![image](https://github.com/godotengine/godot/assets/37371850/ebbce6ca-426c-482e-837d-81b827ff288d)
By the way, I want to ask how to achieve this (set default value to an input variable(like UV, TEXUTRE) ) through plugin.
THANKS!

**Comment by arkology** [comment]
You forgot `return`

**Comment by SmallKi** [comment]
> You forgot `return`
.... THANKS ...... my fault
