### ISSUE TITLE
Clarity with addon dependancy 

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#86262]
### Tested versions

All versions?

### System information

All OS’

### Issue description

Basically I have made an addon, and for it to work I have to use another addon.

similar to say, a python library, some of my addons can be used as-is and have no dependencies, but some rely on others I’ve made. 

How am I supposed to submit these to the assetlib? What is the correct architecture for doing this? I’m sure the answer is quite simple but I would prefer a definitive answer than just to guess.

There is no documentation about this anywhere, so I’m trying to find a definitive answer, and if there isn’t one, maybe this could be the start of that discussion. 

I’m using extends and class_name to make custom libraries

maybe there could be some dependency feature for the assetlib ?

### Steps to reproduce

Make an addon that uses another addon 

### Minimal reproduction project (MRP)

No

**Comment by yankscally** [comment]
Just want to note that this isn't a feature request or proposal, but rather a question of how I can correctly organise this kind of thing in the current state, from the engine. Once a definitive answer is reached from the actual engine, I will volunteer to update the docs about this topic. 


I see a proposal for package style addons here:

https://github.com/godotengine/godot-proposals/issues/142

**Comment by AThousandShips** [comment]
For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk or for asking support questions.
