### ISSUE TITLE
Precision-induced lighting failure on large objects on Android devices with Vulkan mobile renderer (solution provided)

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot#86275]
## Solution

Increase precision in fragment shader for `normal_interp`
https://github.com/roalyr/godot-for-3d-open-worlds/commit/c26f7ac775c13b9b630b3116a26f84995d8be110

### Tested versions

4.x as of https://github.com/godotengine/godot/commit/2d0ee20ff30461b6b10f6fdfba87511a0ebc6642 and official Android 4.2 build.

### System information

Lenovo TB350FU, ARM Mali-G57 MC2 and Motorola moto g(60), Adreno 618, all in Vulkan mobile mode.

### Issue description

On large 3D objects omni light either ceases to render at all, if an object is above some certain scale (Motorola), or is rendered with bugs (Lenovo). On GLES3 renderer everything works fine, same goes for desktop (both Forward+ and Mobile renderer).

Also the bug seems to affect `blend_add` fresnel shaders.

Intended look (on desktop):
![287460725-54bc7b57-8cb8-485d-a3b2-2376c93d7f91](https://github.com/godotengine/godot/assets/46825200/e810e891-6db7-4feb-bf11-310c141cf9ce)

Links to videos showing the bug:
https://imgur.com/a/fSqghHU
https://imgur.com/a/MGLpjvq
https://youtu.be/9AVLGC-C2-I?si=wsHlsaOSfbtplzsD

Remarks:
1. This issue persists for both editor and exported project on a mobile device (I included editor build below).
2. Models use shader material with log depth, but it doesn't seem to affect the bug (can be commented out).
3. My fork 4.x build ( [GF3DOW](https://github.com/roalyr/godot-for-3d-open-worlds) ) has increased z-far cap in order to be able to display objects at large scales, could increased z-far in Vulkan mobile cause this bug? Edit: same behavior on official 4.2 Android editor.
4. Behavior is different on different mobile GPUs.
5. Switching to compatibility makes scene appear normal, lighting works as intended.
6. Desktop GPU renders as intended on every renderer.
7. Only light, direction light behave the same.

### Steps to reproduce

Open test scene and navigate the view. Try gradually scaling down the models to see the threshold at which omni light starts to misbehave.

Or just create an empty 3D scene, add a spherical model and gradually scale it up.

### Minimal reproduction project (MRP)

The test scene itself: [test.zip](https://github.com/godotengine/godot/files/13536785/test.zip)
(Should be opened on a mobile device with  [Android editor build](https://github.com/roalyr/godot-for-3d-open-worlds/releases/tag/Test) because the scale is around 1e6-1e7 units, so it requires editor with larger z-far cap and double precision)

**Comment by roalyr** [comment]
On Motorola where light is either rendered or not, the size of a sphere above which the light fails is 256 meters.

![Screenshot_20231220-115754.png](https://github.com/godotengine/godot/assets/46825200/2bf1932e-922b-4852-a678-2eefac67b356)

![Screenshot_20231220-115744.png](https://github.com/godotengine/godot/assets/46825200/80dc1eb3-764b-4be4-8e81-b51ebba8049f)

**Comment by roalyr** [comment]
On the Lenovo tablet the size of a sphere at which light begins to glitch is about 65520...65522 meters.

![Screenshot_20231220-131109.png](https://github.com/godotengine/godot/assets/46825200/4e4785ce-a5ef-4f45-a173-a37fa14852fe)

![Screenshot_20231220-131051.png](https://github.com/godotengine/godot/assets/46825200/6348922e-19ed-4128-9c4c-767b3f9d77b6)

**Comment by roalyr** [comment]
The same bug happens on 4.2 official build, just tested.

**Comment by roalyr** [comment]
Suggested by @clayjohn, copying here from chat so as to not to lose:

clayjohn11:27 PM
The issue looks like it's coming from the scene shader itself. I would look at the shaders and ensure you are doing math in high precision. Then I would look at the inputs to the light shader. Try assigning NORMAL to ALBEDO as well as depth and see if you notice any issues. 

clayjohn11:28 PM
Also try a very simple light shader to see if the issue comes from the internal light shader or earlier in the pipe

**Comment by roalyr** [comment]
The bug appears to be affecting unshaded materials with `blend_add` mode too:

https://youtu.be/oILRIk3NxGU?si=ogyDSYxLFif3M804

**Comment by roalyr** [comment]
Some more, shows both lighting and blend_add fresnel material: https://youtu.be/9AVLGC-C2-I?si=wsHlsaOSfbtplzsD

Motorola moto g(60), Adreno 618

**Comment by roalyr** [comment]
## Solution

Increase precision in fragment shader for `normal_interp`
https://github.com/roalyr/godot-for-3d-open-worlds/commit/c26f7ac775c13b9b630b3116a26f84995d8be110

**Comment by Flarkk** [comment]
@roalyr can you make a PR ?

**Comment by roalyr** [comment]
I am sorry, I am in a poor state of mind as of late, please don't rely on me. I know you are doing important work on mobile renderer there, but I am not able to contribute these days.

**Comment by Flarkk** [comment]
No worries, take care
