### ISSUE TITLE
Addons used by other addons is not clear 

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#86282]
### Tested versions

All

### System information

All

### Issue description

Please read the entire post before closing my issue!

I have an addon that relies on another addon to work. How do I package the dependencies? What is the official way to do this?

I'm asking what the official recommendation is on this particular issue/what the best practice is. I'm not asking for help, as I could just simply make something up. But if everyone makes it up, it's eventually going to be a problem if all addons have their own dependency architecture.

Also, I can't ask for help, because there is no reference point for anyone to say what is the right or recommended way to do this. They are going to just make something up.

It's not something I can report to the docs, as it's the engines job to know how addons should interact with eachother.

I can't make a proposal, because I'm not asking to add anything.

If I ask this anywhere else, people simply say "I don't know" or, again, make something up.

I know this is quite out there for a bug report, but it genuinely feels like a bug that nobody really knows the answer.

I was told to use the community chat channel, but that’s not going to be an official recommendation; it’s going to be someone just making it up. 

With all that in mind, what do you suggest I do to resolve this issue?

this is continuing #86262 as it was closed.

### Steps to reproduce

Make an addon that uses another addon.

### Minimal reproduction project (MRP)

No

**Comment by yankscally** [comment]
Oh, and just to add. the point of the issue is so I can actually make a PR to the docs to update it to describe the best practice.

This issue can be referenced in the PR

**Comment by YuriSizov** [comment]
> It's not something I can report to the docs, as it's the engines job to know how addons should interact with eachother.

This is exactly the kind of issue that should be created in the docs repo, or as a discussion in the proposal repo. The main repo is for bug reports.

And to answer your question, there is no recommended way to create dependencies.

**Comment by yankscally** [comment]
OK, that makes sense. And thank you for elaborating. I have submitted bugs properly before but I found this issue particularly hard to categorise. 

I will report this to the docs. 

I will still be referring to this issue if anyone decides or requests that I should move this issue somewhere else.
