### ISSUE TITLE
C# Android export doesn't open on some devices, or does but has null refs that don't happen on desktop

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot#86295]
### Tested versions

Godot v4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - GLES3 (Compatibility)

### Issue description

I have 2 android devices:
1 - Alcatel 1S (2019) – Android 9 - [gsmarena link](https://www.gsmarena.com/alcatel_1s-9598.php)
2 - Samsung Galaxy A03 - Android 13 - [gsmarena link](https://www.gsmarena.com/samsung_galaxy_a03-11244.php)

On device 1, the game simply doesn't open. Device logs here: 
[device logcat.txt](https://github.com/godotengine/godot/files/13702885/device.logcat.txt)

On device 2, the game does open, but logs are spammed with nullrefs that do not appear on desktop, and I have no idea where to even start: 
[device logcat samsung.txt](https://github.com/godotengine/godot/files/13702949/device.logcat.samsung.txt)

On device 1, it seems like the render view can't be created? 
On device 2, It seems like exported nodes lose their reference somehow?

I am unable to pinpoint the problem. The game works on desktop as-is. In truth, these may be two separate issues, but considering I'm sharing my whole project here, I figured I'd turn this into 1 issue.

### Steps to reproduce

Export the attached project to an Android device.

### Minimal reproduction project (MRP)

I spent 4 hours trying to make MRPs but couldn't pinpoint the problem. Empty projects or projects with minimal code don't generate the issues I'm seeing, and so I'm dropping the entire project here so you can try it for yourself. Again, really sorry that this complicates debugging for you.

[td.zip](https://github.com/godotengine/godot/files/13703344/td.zip)

**Comment by AdriaandeJongh** [comment]
I have .NET 8.0 installed, but may have installed older versions in the past. Considering the .csproj defines the .NET versions, I assume it will use the latest?

**Comment by theBSH** [comment]
> I have .NET 8.0 installed, but may have installed older versions in the past. Considering the .csproj defines the .NET versions, I assume it will use the latest?

yes indeed it uses the one in the .csproj , I would recommend dotnet 7 for android.

**Comment by AdriaandeJongh** [comment]
Sorry, to be clear: Android targets .NET 7.0 and iOS targets .NET 8.0 in the .csproj. I assume that installing .NET 8.0 also 'includes' .NET 7.0?

**Comment by raulsntos** [comment]
I think these are 2 separate issues:

- In the log for device 1 I'm seeing `The vulkan hardware level does not meet the minimum requirement: 1`, try using the compatibility renderer. This would be unrelated to C#.
- In the log for device 2, you are getting a `NullReferenceException` in `Player._PhysicsProcess`.

**Comment by AdriaandeJongh** [comment]
I see. I'll close this issue treating it like a user error.
