### ISSUE TITLE
`UndoRedo history mismatch` when creating a new tile atlas

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#86291]
### Tested versions

Godot v4.3.dev (2d0ee20ff)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

When debugging https://github.com/godotengine/godot/issues/86226, I found that after dragging the image to create atlas, an internal error will show like the image below:

![image](https://github.com/godotengine/godot/assets/8315986/49ee0c38-df70-4d9b-8ebe-ba4aa50d49e3)

The log looks like this :

```
UndoRedo history mismatch: expected 0, got 1.
Add a new atlas source
```

### Steps to reproduce

Forme, just drag a random png file to create a tile atlas

### Minimal reproduction project (MRP)

N/A

**Comment by rockgem** [comment]
i was getting this errors as well when i was importing huge tilesets tho for me it just immediately crashes after this error pops up

**Comment by ATreeShine** [comment]
> i was getting this errors as well when i was importing huge tilesets tho for me it just immediately crashes after this error pops up

it probably has something to do with your gpu ig
