### ISSUE TITLE
[4.2.1] Engine crashes while loading projects with Forward+ or Mobile rendering mode

### ISSUE THREAD

**Issue by peachey2k2** [godotengine/godot#86303]
### Tested versions

- Reproducible in v4.2.1.stable.mono.official [b09f793f5]
- Also reproducible in older versions (tried 4.2.0 and 4.1.3, both crashed)

### System information

Godot v4.2.1.stable.mono - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:20 +0000 - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics (TGL GT1) () - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

First of all, since I cannot open a project without compatibility mode, the info in system information isn't exactly accurate. On other rendering modes, Godot uses my graphics card instead of my CPU. This following line in the logs prove that.
```
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3050 Ti Laptop GPU
```
I tried using both the standard and mono builds, and even tried compiling both by myself. This also happens with brand new projects, so I'm pretty sure it's GPU related.

As for drivers, I'm using the `nvidia-dkms` AUR package, which is at version `545.29.06-1` at the moment.

### Steps to reproduce

1. Open up the engine
2. Double-click a Forward+/Mobile project or create one
3. Crash.

### Minimal reproduction project (MRP)

[New Game Project.zip](https://github.com/godotengine/godot/files/13705585/New.Game.Project.zip)
This is a blank project and I cannot open it with v4.2.1

**Comment by ParsaGachkar** [comment]
any update on this? i'm expirincing the same thing on win 11! net 6, 7, 8 SDK installed!

**Comment by peachey2k2** [comment]
I realized I didn't include any logs, so here it is.
```
Godot Engine v4.2.1.stable.arch_linux - https://godotengine.org
glx: failed to create dri3 screen
failed to load driver: nouveau
OpenGL API 4.6 (Core Profile) Mesa 23.3.1-arch1.1 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics (TGL GT1)
 
Editing project: /home/p/New Game Project
Godot Engine v4.2.1.stable.arch_linux - https://godotengine.org
>> Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3050 Ti Laptop GPU

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.arch_linux
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e710) [0x7fcd5056f710] (??:0)
[2] /usr/lib/libnvidia-glcore.so.545.29.06(+0xd36564) [0x7fcd43736564] (??:0)
[3] /usr/lib/libGLX_nvidia.so.0(+0x9ccf0) [0x7fcd44acdcf0] (??:0)
[4] /usr/lib/libvulkan.so.1(+0x3c68a) [0x7fcd44b9668a] (??:0)
[5] /usr/bin/godot(+0x1088bd0) [0x5592538e0bd0] (??:?)
[6] /usr/bin/godot(+0x108d7fc) [0x5592538e57fc] (??:?)
[7] /usr/bin/godot(+0x6005f7) [0x559252e585f7] (??:?)
[8] /usr/bin/godot(+0x60b8a6) [0x559252e638a6] (??:?)
[9] /usr/bin/godot(+0x60d6c1) [0x559252e656c1] (??:?)
[10] /usr/bin/godot(+0x3ff5fdd) [0x55925684dfdd] (??:?)
[11] /usr/bin/godot(+0x60ead0) [0x559252e66ad0] (??:?)
[12] /usr/bin/godot(+0x40614ea) [0x5592568b94ea] (??:?)
[13] /usr/bin/godot(+0x582f12) [0x559252ddaf12] (??:?)
[14] /usr/lib/libc.so.6(+0x27cd0) [0x7fcd50558cd0] (??:0)
[15] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fcd50558d8a] (??:0)
[16] /usr/bin/godot(+0x58fda5) [0x559252de7da5] (??:?)
-- END OF BACKTRACE --
================================================================
```

**Comment by peachey2k2** [comment]
IDK what I did but it now works for me. It was probably some bug unrelated to engine, so sorry for bothering you all. I should do a complete reinstall anyway for good measure. As for @ParsaGachkar's issue, it's probably unrelated.

Here is a cat: 
![image](https://github.com/godotengine/godot/assets/100072467/c316b00d-4a51-42ef-9541-b2781a51c81c)

**Comment by ParsaGachkar** [comment]
looks like i just needed a driver update. sorry for inconvenience.
