### ISSUE TITLE
OpenGL: ReflectionProbe is not reimplemented yet

### ISSUE THREAD

**Issue by Lasuch69** [godotengine/godot#86318]
### Tested versions

Godot v4.2.1.stable

### System information

Fedora Linux 38.20231205.0 (Silverblue) - Wayland - GLES3 (Compatibility) - AMD Radeon RX 550 / 550 Series (polaris12, LLVM 16.0.6, DRM 3.54, 6.6.3-100.fc38.x86_64) () - AMD Ryzen 5 3400G with Radeon Vega Graphics (8 Threads)

### Issue description

Reflection Probe makes a huge difference in fidelity at a really low cost, which makes it a good choice for mobile games.

However Reflection Probe is still missing in Compatibility backend.

Compatibility backend:
![image](https://github.com/godotengine/godot/assets/71460040/ddc94aac-346e-49e1-bcd1-ff5f2560d340)

Mobile backend:
![image](https://github.com/godotengine/godot/assets/71460040/5d756186-1f0c-43e2-bcf8-1989403d9c4c)

### Steps to reproduce

Create Reflection Probe while using Compatibility backend to see that nothing happens. Which isn't the case with backends using RenderingDevice (Mobile and Forward+).

### Minimal reproduction project (MRP)

N/A

**Comment by Lasuch69** [comment]
Started working on this.

**Comment by Lasuch69** [comment]
Just a quick update on the progress.

I feel like I am so close to having anything rendered into the reflection probe, however I am not sure how to deal with render targets and framebuffers yet. I am literally learning OpenGL as I go.

**Comment by daustria** [comment]
how is this going? Feel free to share some of the implementation details, either here or maybe DMs on the contributors chat. i am really interested the implementation of this but seems overwhelming with my background, i hardly know where to start.

**Comment by Lasuch69** [comment]
> how is this going? Feel free to share some of the implementation details, either here or maybe DMs on the contributors chat. i am really interested the implementation of this but seems overwhelming with my background, i hardly know where to start.

I feel lost at shaders and atlases.

**Comment by daustria** [comment]
that's okay! it took me a long time to get comfortable with opengl, and im still new. you've only been at this for a couple of weeks or less. i hope you can stay motivated, seek help where you can, and do what you need to do, whether you decide to put this task on the backburner or keep at it.

**Comment by Lasuch69** [comment]
Now that I know how to bind reflection probe's data to a shader, getting the data into it is my main priority. However atlases are still the biggest problem for me lmao.

**Comment by Lasuch69** [comment]
Giving up on it for now. I will try to understand shader compiling process, if I do then I will work on it further and give an update.
