### ISSUE TITLE
Out of date image in documentation

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8632]
http://docs.godotengine.org/en/2.1/learning/step_by_step/singletons_autoload.html

On the above page the autoloader's parameter order has changed.

Current doc image:

![addglobal](https://cloud.githubusercontent.com/assets/7429786/25640000/f63c1558-2f5b-11e7-9147-a448a40a73df.png)

Current screenshot from Godot:

![capture](https://cloud.githubusercontent.com/assets/7429786/25640034/0e6b11f6-2f5c-11e7-89b5-ef0f7b14d01d.PNG)

Notice that the path and the node name params have switched place, which was annoying as I was following along

**Comment by karroffel** [comment]
Hey!

This belongs to [godot-docs](https://github.com/godotengine/godot-docs), could you open this issue there?

**Comment by kubecz3k** [comment]
Opened new issue in docs repo: https://github.com/godotengine/godot-docs/issues/1328
