### ISSUE TITLE
PointLight2D does not support dynamic Texture2Ds

### ISSUE THREAD

**Issue by JohnPandich** [godotengine/godot#86328]
### Tested versions

- Found in: Godot 4.2.1
- Reproducible in: Godot 4.0, 4.1, 4.2
- Not Reproducible in: Godot 3.5

### System information

Godot v4.2.1.stable - Linux Mint 20.2 (Uma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (nvidia; 545.29.06) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

When using a PointLight2D with a dynamic texture, like an AnimatedTexture or a ViewportTexture, the light texture does not update. I would expect the light to represent the current state of the texture it is using. 

Additionally, if another Light2D using a static texture has that texture is updated, the Light2D with a dynamic texture will be updated to the current value of the dynamic texture and remain in that state.

### Steps to reproduce

1) Add a light impacted node such as a Sprite2D ot a scene
2) Add a PointLight2D to the scene and place it over the node from step one
3) Add an AnimatedTexture as the texture of the PointLight2D
4) Add more than one frame to the AnimatedTexture
	- Initially no frames from the animated texture will show in the PointLight2D but it is important to add more than one frame so that the static nature of the texture can be seen even if the texture is updated via the second point in the issue description.

The included minimal reproduction project contains two scenes that reproduce the issue:
1) light_repro.tscn reproduces this issue with an AnimatedTexture
2) light_repro_with_viewport.tscn reproduces this issue with a ViewportTexture

### Minimal reproduction project (MRP)

[LightTextureRepro.zip](https://github.com/godotengine/godot/files/13716355/LightTextureRepro.zip)

**Comment by AThousandShips** [comment]
Thank you for your report

For AnimatedTexture (which is deprecated) this is tracked in:
* https://github.com/godotengine/godot/issues/67706

For ViewportTexture this is tracked in:
* https://github.com/godotengine/godot/issues/75868

Consolidating there

**Comment by JohnPandich** [comment]
My apologies, I am not sure how I did not find these
