### ISSUE TITLE
Godot 4 editor's interface is not displayed correctly

### ISSUE THREAD

**Issue by I3aga** [godotengine/godot#86329]
### Tested versions

I faced that issue in various 4.x.x versions (current version is v4.2.1.stable.official [b09f793f5]). Godot 3.5.3 works well. Don't know about other 3.x.x releases

### System information

Windows 10 - CPU AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G - GPU Graphics Chipset AMD Radeon(TM) R8 M445DX - OpenGL® Version 6.14.10.13447 - Vulkan Driver Version 1.2.0

### Issue description

I ran into this problem - the interface of the editor itself is not displayed correctly. For example, when I launch it, a confirmation dialog box opens, but inside it’s empty or repeats the image of the main manager window.

![photo_2023-12-19_09-38-37](https://github.com/godotengine/godot/assets/25429731/96b3da48-1e8c-4c8b-87a9-397dddeff036)

If I click New Project, the window that opens also simply repeats the image of the main manager window, but not the project creation window.

![photo_2023-12-19_09-39-02](https://github.com/godotengine/godot/assets/25429731/4459e80e-5ff5-4053-9c81-d40ece571941)

There is also a screen recording, but the dialog box I mentioned is not visible for some reason. But you can see problems when trying to change the language. Maybe this will help.

https://github.com/godotengine/godot/assets/25429731/c52bf958-0085-487f-b166-c4e7ce2c36df

How I tried to solve the problem. I deleted Godot folders from %TEMP% and %APPDATA%. That didn’t help.

This problem occurs only with 4.x versions (I tried different releases). Version 3.5 works without any problems.

### Steps to reproduce

There is no project. I can't even create one.

### Minimal reproduction project (MRP)

There is no project. I can't even create one.

**Comment by Kazuma640** [comment]
A similar problem. I've been looking for a solution myself for a long time

**Comment by Calinou** [comment]
Can you reproduce this if you start Godot with the `--rendering-driver opengl3` [command line argument](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html)? ANGLE is used by default on old AMD GPUs, as their OpenGL driver on Windows is pretty bad. That said, ANGLE can also introduce bugs on its own.

If all else fails, you'll have to switch to Linux which has much better OpenGL drivers on AMD GPus.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened

**Comment by IlyaBondarevDev** [comment]
I had the same problem, the following helped me:
1) open cmd in the engine folder
2) type: Godot_v4.x.x.x-stable_win64.exe --rendering-driver vulkan
3) if vulkan doesn't help, you can try other ones, for example 'opengl3', 'opengl3_angle', 'dummy'.

**Comment by I3aga** [comment]
Thanks, that worked! ("opengl3_angle" option in my case)
