### ISSUE TITLE
Possible issue with shader ported from 3.5 not displaying correctly.

### ISSUE THREAD

**Issue by ealione** [godotengine/godot#86332]
### Tested versions

4.2 stable

### System information

Windows 10, 4.2 stable, Forward+

### Issue description

I am not entirely sure if this is a bug or just a mistake on my part but just in case I'm posting it here.

This is what I get in 4.2
![image](https://github.com/godotengine/godot/assets/5569899/642924a8-2423-4650-95cc-38ac7d7e4f55)

This is what I get in 3.5
![image](https://github.com/godotengine/godot/assets/5569899/0060872d-675b-4e66-ae7b-fa81cd93e1f8)

### Steps to reproduce

Open any of the provided scenes in the attached project.

### Minimal reproduction project (MRP)

[examples.zip](https://github.com/godotengine/godot/files/13718097/examples.zip)

**Comment by Chaosus** [comment]
You can easily fix it by changing this line:

![изображение](https://github.com/godotengine/godot/assets/3036176/d0231380-bfec-44d5-b786-cd5c46ca7409)

to
 
```vec3 p = vec3(0);```

**Comment by ealione** [comment]
Small note here. It is definitely not a bug with godot, but indeed the behaviour has changed. Even with your proposed solution the result is not similar to the original shader from Godot 3.5:

![image](https://github.com/godotengine/godot/assets/5569899/c0205725-2b24-48e9-9ac4-3e132cc2d0c9)
