### ISSUE TITLE
Global/resource_local_to_scene property is duplicated

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#8634]
**Operating system or device - Godot version:**
Godot 3.0 alpha

**Issue description:**

There is `EditorSettings::_get - Warning, not found: Global/resource_local_to_scene` message when open Editor Settings.
and `Global/resource_local_to_scene` property is duplicated after checked once.

**Steps to reproduce:**
![global_resource_local_to_scene](https://cloud.githubusercontent.com/assets/8281454/25650013/ebd61262-3014-11e7-9b9a-54dbe8336350.gif)

**Comment by akien-mga** [comment]
Yeah, I'm not sure where it comes from, but it seems to be added by the code chunk: https://github.com/godotengine/godot/blob/5a6ccce97d350011b599e793cea95aa4e7899395/editor/property_editor.cpp#L4631-L4635

Maybe it's meant to be filtered out like other properties in this code chunk.

**Comment by volzhs** [comment]
I found that codes but had no clue. :(
