### ISSUE TITLE
Scan file selection font color broken

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8635]
Godot 3rd may build Kubuntu 17.04 x64

File selection dialog window shows files in black font in project manager (you can see font color set in theme resource on folders). Issue is present in default theme too.

Other file selection widgets display color properly.

STR: 1. Select "Scan" in project manager. 
2. Navigate to a folder that contains any files in it.

![spectacle j13328](https://cloud.githubusercontent.com/assets/10696955/25650511/07ee62f8-2fe6-11e7-93ea-1d6f0ab986c3.png)

![spectacle c13328](https://cloud.githubusercontent.com/assets/10696955/25650465/c66cef02-2fe5-11e7-8e7c-31ad87b14656.png)

**Comment by akien-mga** [comment]
That's actually a feature, it's only used in the scan dialog as files don't matter there, only directories.

Maybe the files could be hidden instead of being blacked out. It looked less buggy on 2.1 as the contrast was better, so it was clearer that those were "disabled" and not badly rendered.

**Comment by nunodonato** [comment]
@volzhs what do you think about improving the disabled filenames color like @akien-mga said above?

**Comment by volzhs** [comment]
I will check what I can do about it. :)

**Comment by volzhs** [comment]
@akien-mga @nunodonato 
![image](https://cloud.githubusercontent.com/assets/8281454/26305200/50e0655e-3f29-11e7-9511-fbfff6e91691.png)

how about this?

**Comment by akien-mga** [comment]
Looks good, it's clearer that it's greyed out on purpose.
