### ISSUE TITLE
OpenXR Errors After First Tutorial Page

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#86358]
### Tested versions

- Reproducible in: 4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

Just going trough the basic tutorial I run into 3 errors in the output and the debugger output.

From output when project is opened:
`modules/openxr/editor/openxr_interaction_profile_editor.cpp:260 - Parameter "profile_def" is null.`

From debugger output after game is run:
```
E 0:00:02:0890   is_top_level_path_supported: OpenXR: Unsupported toplevel path /user/eyes_ext
  <C++ Error>    Condition "required_extension == "unsupported"" is true. Returning: false
  <C++ Source>   modules/openxr/openxr_api.cpp:200 @ is_top_level_path_supported()
```
```

E 0:00:02:0918   is_interaction_profile_supported: OpenXR: Unsupported interaction profile /interaction_profiles/ext/eye_gaze_interaction
  <C++ Error>    Condition "required_extension == "unsupported"" is true. Returning: false
  <C++ Source>   modules/openxr/openxr_api.cpp:220 @ is_interaction_profile_supported()
```

Suspect that last one has something to do with me using a Valve Index and that even though the Eye Gaze Interaction setting is false in the project settings it tries to do something with it.

The errors don't prevent the game from running, but its not nice to run into any error messages while doing your first steps.

### Steps to reproduce

If you close and open the project again you will be presented with the first error. This one disappears after you run the game but shows up again if you close and open the project.

After every run you will encounter the 2 errors in the debugger ouput.

### Minimal reproduction project (MRP)

Go trough https://docs.godotengine.org/en/stable/tutorials/xr/setting_up_xr.html C# version and run the game using a Valve Index.

**Comment by paladinrose** [comment]
I'm having the exact same problem. All three errors. 

I'm on v4.3.dev.custom_build [d76c1d0e5]
Windows 10
NVIDIA GeForce GTX 1060 3GB
Intel(R) Core(TM) i5-10600KF CPU @ 4.10GHz

**Comment by opensky0** [comment]
Had the same issue and found [this](https://www.reddit.com/r/godot/comments/18c2g4z/godot_42_xr_errors/), now its fixed.

**Comment by Kiryonn** [comment]
same but with the basic version of godot (gdscript only) and mobile instead of forward+

**Comment by ForestKatsch** [comment]
Same issue on 4.2.1 Windows with Quest 3.

**Comment by chadulous** [comment]
This issue is definitely caused by something added in #82614

**Comment by akien-mga** [comment]
CC @godotengine/xr

**Comment by m4gr3d** [comment]
This is being tracked by https://github.com/GodotVR/godot_openxr_vendors/issues/86

**Comment by BastiaanOlij** [comment]
This is being caused by the eye gaze interaction profile being added to the default action map, while the eye gaze interaction extension is not enabled and we're thus missing the meta data that drives the action map editor.

We need to change this logic so the eye gaze interaction extension is instantiated but not activated so the right information is recorded in the meta data table. We've been a little overzealous in completely removing extensions when not enabled in the settings.

There is also a question whether it makes sense to add the eye gaze interaction to the default action map. I think we should remove that bit.

In the mean while the workaround to get rid of these errors is to edit the action map, remove the defunct entry, and save it.

**Comment by Muziwahuzie** [comment]
For all monkeys out there like me: 

When you delete the sub_resource you also need to delete the corresponding resource in [resource] section, using the [sub_resource] id to find it, from the array (resources loads subresource).
tip for proceeding:

- search for gaze in openxr_action_map.tres
- the found sub_resource containing gaze has id
- search for id
  - if id is found in [resource] 
    - delete the entry from [resource] array
- after that delete [sub_resources] containing gaze

this is not fool prove, but I hope it helps

btw: this took days for me to find (after upgrading from 4.1.2 to 4.2.1 my XR broke) maybe linking it to the tutorial would be a good idea? My old project still doesn't work and has no such eye gazing feature in the tres file. Should I open a new issue for this? Don't know how to perform a reproducabilty with Version changes, with this one.


Much love for your work :heart:
