### ISSUE TITLE
VisualShader DistanceFade inconsistent with StandardMaterial3D

### ISSUE THREAD

**Issue by EnlightenedOne** [godotengine/godot#86367]
### Tested versions

Godot v4.2.stable.mono
Godot v4.3.dev.mono (335ff0f1a)

### System information

Godot v4.3.dev.mono (335ff0f1a) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

I have noticed that some inconsistencies exist between what the VisualShader functions produce and what StandardMaterial3D generate/use. In most cases the VisualShader version is wrong or inherently worse.

The one I want to flag here to keep this a single unit is VisualShader DistanceFunction produces this (bad):
float n_out9p0 = clamp(smoothstep(n_in9p0, n_in9p1,**-VERTEX.z**),0.0,1.0);
![image](https://github.com/godotengine/godot/assets/1945825/bf372305-9864-4d07-af8e-23720422becd)

3dMaterial + converted shader produces this (good):
ALPHA *= clamp(smoothstep(distance_fade_min, distance_fade_max, **length(VERTEX)**), 0.0, 1.0);
![image](https://github.com/godotengine/godot/assets/1945825/2c76e633-6e53-4f36-82d3-da3f4e8b42e8)

Here they are side by side (left/blue=VisualShader right/yellow=3dMaterial:
![image](https://github.com/godotengine/godot/assets/1945825/73de8a98-c01f-4a05-aa06-aa28b66591cb)

### Steps to reproduce

Create StandardMaterial3D and use 
Create ShaderMaterial and use DistanceFunction

### Minimal reproduction project (MRP)

[DF_MRP.zip](https://github.com/godotengine/godot/files/13733299/DF_MRP.zip)

**Comment by bitsawer** [comment]
Could be that two distance fade versions got out of sync at some point or the difference is intentional. Changing it now will alter existing behavior, but it could be worth it.

As a workaround, it should be easy to get the desired behavior using a visual shader expression node with custom shader code snippet.

**Comment by EnlightenedOne** [comment]
> Could be that two distance fade versions got out of sync at some point or the difference is intentional. Changing it now will alter existing behavior, but it could be worth it.
> 
> As a workaround, it should be easy to get the desired behavior using a visual shader expression node with custom shader code snippet.

I thought about if this was intentional as for distance fog this is how you would want it to behave but I have to conclude it is a bug on the basis that having two things with the same name use different methods is not good practice. Fixing this VisualShader could contain two DistanceFade functions if both are useful out of the box? DistanceFace (matching the Material3D) and DistanceFadeZ.

Working around it is as easy as the code generated from the StandardMaterial3D can be converted:
![image](https://github.com/godotengine/godot/assets/1945825/382c7930-747c-4557-a74d-6eb86e6cbaf9)

If there is consensus on what fix is valid happy to take a look.

**Comment by Calinou** [comment]
The difference isn't intentional – these got out of sync as https://github.com/godotengine/godot/pull/50294 wasn't applied for visual shaders as well.

**Comment by EnlightenedOne** [comment]
Hi @jsjtxietian,

I loaded this in 4.3 (9e65c5c0f4f8944d17fc7f5b05682206e9348d81) and saw the nodes got scrambled, not sure what sort of breaking change did that but here is a working fresh one:
[DF_MRPv4.3.zip](https://github.com/godotengine/godot/files/13943962/DF_MRPv4.3.zip)

Thanks for beating me to it, please let me know if this works :)

**Comment by jsjtxietian** [comment]
> Thanks for beating me to it

Sorry for that, I should have asked you before creating a pr. Feel free to continue work on my pr or abolish it and make a new one!

**Comment by EnlightenedOne** [comment]
@jsjtxietian you have absolutely nothing to apologise for, I was literally thrilled to see such healthy activity on the repo!

Please continue I am glad to see it fixed, abandoning your PR is the last thing I want to encourage.
