### ISSUE TITLE
Allow hiDpi and hiDpi enabled

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8636]
**Godot version: 3.0**

**Issue description:**

To use hiDpi themes in your own project you need to enable `allow hiDpi` + `enable hiDpi`
Those two settings are at different locations and it might lead to frustration.
If they have different peruses it would be great if `enable hiDpi` would prompt a message which mentions, that `allow hiDpi` needs to be activated too.
If there is no reason in `allow hiDpi` it also would be possible to remove it.

**Comment by odyzzey** [comment]
+1 for removing `allow hiDpi` seems like a redundant setting to me when `enable hiDpi` is already a thing.

**Comment by fahall** [comment]
+1 for removing `allow hiDpi`

That said: in the current build, I see only `use hiDpi` in project settings under Gui/Theme/. Grepping through the code doesn't return anything with 'hiDpi', so it's possible I'm doing something wrong as a Godot newbie. 

Is this still an issue that needs to be resolved or can it be closed?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by sztomi** [comment]
I can confirm this is still relevant in 3.0.5.stable.official.6a88e22.

**Comment by toger5** [comment]
I finally figured out what the two options are supposed to do:
allow hiDpi is just telling the OS to not scale the godot window (bitmap based scaling. so turning it off, results in a blurry window on hiDpi screens)

enable hiDpi on the other hand, tells godot to use the hiDpi default theme. so the font/ buttons style boxes... are scaled bigger.

**Comment by Calinou** [comment]
Is **Enable hiDPI** still relevant in the current state of things? The old hiDPI image-based theme will be removed when the default project theme will be remade to use StyleBoxFlat and DynamicFont.
