### ISSUE TITLE
Slider drag_ended signal triggered with click interaction passes false as changed_value

### ISSUE THREAD

**Issue by KentaPanic** [godotengine/godot#86370]
### Tested versions

Reproducible in -4.2.1 stable Windows x64 forward+

### System information

Windows 10 x64 - Godot 4.2.1 stable forward+

### Issue description

I'm using a HSlider. I am using the signal drag_ended. when I click a point on the HSlider the value_changed is false even when the value is updated. this might effect sliders in general. when dragging a point to another point the value_changed is true. here is a video of my code and and a example of this happening. 

https://github.com/godotengine/godot/assets/154477152/e07d61f5-9618-44d9-abd7-5cc12ce844b2

### Steps to reproduce

make a HSlider and make a script and 2 functions inside the script. 1 called on_drag_started(): and 1 called on_drag_end():
in your function _ready(): make 2 lines. the first line will have slider.connect("drag_started",on_drag_started) and the second line will have slider.connect("drag_ended",on_drag_end) then in your on_drag_started(): function put print(slider.value) then in your on_drag_end(): function inside the () of the function add value_changed:bool and then inside the function add a line and put print(slider.value, value_changed) then run the game and test it out. 

### Minimal reproduction project (MRP)

https://github.com/KentaPanic/DragBugGodot

**Comment by timothyqiu** [comment]
It's technically correct because the value at `drag_started` is the same as the value at `drag_ended`.

I think the problem here is that `value_changed` is emitted after `drag_started`. This makes it unsafe to ignore `value_changed` during dragging.
