### ISSUE TITLE
ImageTexture3D saves image data in .tres and .tscn files, creating files hundreds of megabytes in size

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#86391]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Windows 10 - Mobile

### Issue description

I've created a custom resource which extends ImageTexture3D.  It loads its data from a file and then calls create() on its extended ImageTexture3D to set its data.  This worked in Godot 4.1, but since upgrading to Godot 4.2, .tres and .tscn files that were several kilobytes long are now hundreds of megabytes long.  This is causing noticeable lag during saves and I am no longer able to check my huge files into Git.

There needs to be a way to disable writing this data to disk so that file sizes can stay manageable.

### Steps to reproduce

Open the attached project.  Note that image_resource.tres has saved all its data to the resource.  This is happening even though it's unnecessary since I can generate the data through other means.  This also did not happen in Godot 4.1.

```

[sub_resource type="Image" id="Image_nfsrs"]
data = {
"data": PackedByteArray(0, 0, 0, 255, 25, 0, 0, 255, 51, 0, 0, 255, 76, 0, 0, 255, 102, 0, 0, 255, 127, 0, 0, 255, 153, 0, 0, 255, 178, 0, 0, 255, 204, 0, 0, 255, 229, 0, 0, 255, 0, 25, 0, 255, 25, 25, 0, 255, 51, 25, 0, 255, 76, 25, 0, 255, 102, 25, 0, 255, 127, 25, 0, 255, 153, 25, 0, 255, 178, 25, 0, 255, 204, 25, 0, 255, 229, 25, 0, 255, 0, 51, 0, 255, 25, 51, 0, 255, 51, 51, 0, 255, 76, 51, 0, 255, 102, 51, 0, 255, 127, 51, 0, 255, 153, 51, 0, 255, 178, 51, 0, 255, 204, 51, 0, 255, 229, 51, 0, 255, 0, 76, 0, 255, 25, 76, 0, 255, 51, 76, 0, 255, 76, 76, 0, 255, 102, 76, 0, 255, 127, 76, 0, 255, 153, 76, 0, 255, 178, 76, 0, 255, 204, 76, 0, 255, 229, 76, 0, 255, 0, 102, 0, 255, 25, 102, 0, 255, 51, 102, 0, 255, 76, 102, 0, 255, 102, 102, 0, 255, 127, 102, 0, 255, 153, 102, 0, 255, 178, 102, 0, 255, 204, 102, 0, 255, 229, 102, 0, 255, 0, 127, 0, 255, 25, 127, 0, 255, 51, 127, 0, 255, 76, 127, 0, 255, 102, 127, 0, 255, 127, 127, 0, 255, 153, 127, 0, 255, 178, 127, 0, 255, 204, 127, 0, 255, 229, 127, 0, 255, 0, 153, 0, 255, 25, 153, 0, 255, 51, 153, 0, 255, 76, 153, 0, 255, 102, 153, 0, 255, 127, 153, 0, 255, 153, 153, 0, 255, 178, 153, 0, 255, 204, 153, 0, 255, 229, 153, 0, 255, 0, 178, 0, 255, 25, 178, 0, 255, 51, 178, 0, 255, 76, 178, 0, 255, 102, 178, 0, 255, 127, 178, 0, 255, 153, 178, 0, 255, 178, 178, 0, 255, 204, 178, 0, 255, 229, 178, 0, 255, 0, 204, 0, 255, 25, 204, 0, 255, 51, 204, 0, 255, 76, 204, 0, 255, 102, 204, 0, 255, 127, 204, 0, 255, 153, 204, 0, 255, 178, 204, 0, 255, 204, 204, 0, 255, 229, 204, 0, 255, 0, 229, 0, 255, 25, 229, 0, 255, 51, 229, 0, 255, 76, 229, 0, 255, 102, 229, 0, 255, 127, 229, 0, 255, 153, 229, 0, 255, 178, 229, 0, 255, 204, 229, 0, 255, 229, 229, 0, 255),
"format": "RGBA8",
"height": 10,
"mipmaps": false,
"width": 10
}
```

### Minimal reproduction project (MRP)

[image_texture_3d.zip](https://github.com/godotengine/godot/files/13740503/image_texture_3d.zip)

**Comment by bitsawer** [comment]
This is intentional, ImageTexture3D serialization support was added in https://github.com/godotengine/godot/pull/82055 and was previously non-functional.

You should be able to customize what gets saved to resource files in your custom resource by overriding the serialization functions. Something like this could work to prevent serialization of ImageTexture3D _images array in your CustomImage3D class:

```gdscript
func _validate_property(property : Dictionary):
	if property.name == "_images":
		property.usage = PROPERTY_USAGE_NONE
```

See https://docs.godotengine.org/en/latest/classes/class_object.html#class-object-private-method-validate-property for more info.

**Comment by blackears** [comment]
Wow, that's a great solution.  I didn't realize Godot let you do that.

It might be useful to add this to the GDScript language as an annotation, just so its not so obscure.

**Comment by bitsawer** [comment]
Adding GDScript annotation for this could be useful in some cases, but they can be more limiting as the property handling callback functions can be used for more complex cases and logic.

If there are not other problems with this, you (or I) can probably close this issue as things seem to work as expected and the behavior is documented.

**Comment by blackears** [comment]
Yes, everything seems to be working now.

**Comment by KoBeWi** [comment]
Note that the fact that your textures get embedded is probably caused by #86187
If it was fine in 4.1 then it means they get saved when they shouldn't be. `_validate_property()` is a workaround for a bug.

**Comment by bitsawer** [comment]
I think in this specific case, using `_validate_property()` to drop `ImageTexture3D._images` works as intended as the image data is loaded from another source anyway. So basically disabling ImageTexture3D's own image data serialization is the intent here to avoid storing the same data two times (just in different formats). 

ImageTexture3D serialization was added for Godot 4.2 in https://github.com/godotengine/godot/pull/82055, previously (for example in Godot 4.1) ImageTexture3D data was not serialized at all. Of course https://github.com/godotengine/godot/issues/86187 could still also affect this issue somehow, I'm not an expert in the resource handling.
