### ISSUE TITLE
Profiler "Display internal functions" checkbox disappears

### ISSUE THREAD

**Issue by prvak** [godotengine/godot#86394]
### Tested versions

4.3.dev [9d1cbab1c]

### System information

Godot v4.3.dev (9d1cbab1c) - Linux Mint 21.2 (Victoria) - X11 - GLES3 (Compatibility) - Mesa Intel(R) HD Graphics 4600 (HSW GT2) () - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

I was hoping to check this cool new feature that allows profiling internal functions: #75623 
However, the checkbox that enables the feature disappears after running the project.

This is how it looks like after starting the editor:
![Screenshot from 2023-12-21 15-06-16](https://github.com/godotengine/godot/assets/2436340/463c364b-70cc-452b-84f8-f694bfc342ca)

This is how it looks like after starting the game:
![Screenshot from 2023-12-21 15-06-59](https://github.com/godotengine/godot/assets/2436340/2f678fdb-00ca-4055-a032-c2325ec7604c)

@reach-satori I am not sure what is the purpose of the following line but when I remove it, the checkbox does not disappear:
https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/editor/debugger/editor_profiler.cpp#L100

### Steps to reproduce

1. Open any project, go to the Debugger -> Profile tab and notice that "Display internal functions" checkbox is there.
2. Run the project, go to the Debugger -> Profile tab and notice that "Display internal functions" checkbox is gone.

### Minimal reproduction project (MRP)

Does not depend on any specific project.

**Comment by reach-satori** [comment]
Did you turn it on in the settings? Under the 'debugger' category. It's disabled by default. 
Not sure why it shows up at first, though.

**Comment by prvak** [comment]
When I create a new project, the checkbox is initially visible. I was looking for "debugger/profile_native_calls" in the settings everywhere and I cannot find it. I do not have "Debuger" category, only "Debug" category. Where should I look for it?

![Screenshot from 2023-12-21 16-35-47](https://github.com/godotengine/godot/assets/2436340/f75d68fc-c8f4-4d3e-bc3b-636dc6d9b528)

**Comment by reach-satori** [comment]
You're looking at the project settings. It's under Editor (in the menu bar) -> Editor settings -> debugger.

**Comment by YuriSizov** [comment]
If this checkbutton is visible initially even when the setting is disabled, it's a bug (so the other way around from what you expect).

**Comment by prvak** [comment]
OMG! I totally forgot that there are both Project settings and Editor settings :facepalm: 

So yes, it is the other way around. The checkbox is initially visible even when the Profile Native Calls is disabled in Editor settings.
