### ISSUE TITLE
Instance shader parameters behaving incorrectly for multi-surface array meshes

### ISSUE THREAD

**Issue by jakeh0916** [godotengine/godot#86397]
### Tested versions

Reproduced in release versions 4.1.3 and 4.2.1.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 1060 6GB () - Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 Threads)

### Issue description

In the attached MRP, we create an array mesh with two surfaces. Each surface has its own shader which declares an instance shader parameter. If both shaders declare both shader parameters (shown below), the result is correct:

Shader 1:
```
instance uniform vec4 color_1 = vec4(0,0,0,1);
instance uniform vec4 color_2 = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_1.rgb;
}
```

Shader 2:
```
instance uniform vec4 color_1 = vec4(0,0,0,1);
instance uniform vec4 color_2 = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_2.rgb;
}
```

Code run to set the shader parameters:
```
mesh_instance.set_instance_shader_parameter("color_1", Color.RED)
mesh_instance.set_instance_shader_parameter("color_2", Color.GREEN)
```

Resulting mesh:
![image](https://github.com/godotengine/godot/assets/90869314/5aa6fcec-cbbe-4cb5-90f2-584864f61896)

However, if the shaders are manipulated to declare *only the instance uniforms that they use*, the result is not what we would expect. 

Shader 1:
```
instance uniform vec4 color_1 = vec4(0,0,0,1);
// instance uniform vec4 color_2 = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_1.rgb;
}
```

Shader 2:
```
// instance uniform vec4 color_1 = vec4(0,0,0,1);
instance uniform vec4 color_2 = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_2.rgb;
}
```

Resulting mesh:
![image](https://github.com/godotengine/godot/assets/90869314/653761ae-cb03-41e6-898b-bafb23017761)

### Steps to reproduce

Reproducing within MRP

1. Run the project as-is
2. Comment out the unused shader parameters in each shader (as shown in the issue description) and run project again.

Reproducing outside of MRP

1. Create a new project in Godot v4.2.1.
2. Write code to create an array mesh with 2+ surfaces.
3. Write shaders for the 2+ surfaces, each making use of an instance shader parameter.
4. Note that the shader parameters will be set incorrectly if all shaders do not declare the same instance parameters.

### Minimal reproduction project (MRP)

[Test.zip](https://github.com/godotengine/godot/files/13743690/Test.zip)

**Comment by bitsawer** [comment]
Thanks for the report. This is not a bug, see instance uniform [documentation about multiple materials with different instance uniforms](https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html#per-instance-uniforms): 

>If your mesh uses multiple materials, the parameters for the first mesh material found will "win" over the subsequent ones, unless they have the same name, index and type. In this case, all parameters are affected correctly.

In this case, adding `instance_index(1)` and `instance_index(2)` etc. to each shader instance uniform should work:

```glsl
instance uniform vec4 color_1 : instance_index(1) = vec4(0,0,0,1);
// instance uniform vec4 color_2 = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_1.rgb;
}
```

and

```glsl
// instance uniform vec4 color_1 = vec4(0,0,0,1);
instance uniform vec4 color_2 : instance_index(2) = vec4(0,0,0,1);

void fragment()
{
	ALBEDO = color_2.rgb;
}
```

**Comment by jakeh0916** [comment]
Thanks for the info. Makes sense, if a bit quirky 👍
