### ISSUE TITLE
Tile picking is broken

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#86400]
### Tested versions

Reproducible in 4.3 dev1
Not reproducible in 4.2.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/cc82ce0f-9ec9-4ba6-8102-e6573fc8d526

Picking with draw tools (using Ctrl) doesn't display any preview.
Using selection tools shows weird grid.

4.2.1 for comparison:

https://github.com/godotengine/godot/assets/2223172/128e7efb-17ef-47bd-baba-cfa57aedf665

### Steps to reproduce

1. Add TileMap with TileSet
2. Draw some tiles
3. Try selecting them

### Minimal reproduction project (MRP)

N/A

**Comment by YuriSizov** [comment]
Reverting to c28a091a09c39ed45931cd7830ae418d369fd9e6 fixes the issue, so this must be a regression from https://github.com/godotengine/godot/pull/83452. cc @RandomShaper
