### ISSUE TITLE
VisibleOnScreenNotifier2D disables particles

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#86408]
### Tested versions

reproducible in 4.3 dev1
not reproducible in 4.2.1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/a2e1bcbe-c19b-47d9-a669-75b766f6d890

### Steps to reproduce

1. Add GPUParticles2D with some particle material
2. Add VisibleOnScreenNotifier2D
3. Place the notifier before the particles in the scene tree

### Minimal reproduction project (MRP)

[particles.zip](https://github.com/godotengine/godot/files/13746184/particles.zip)

**Comment by YuriSizov** [comment]
Interestingly, it's only the one particles node directly below. And other nodes in between do not affect it whatsoever.


https://github.com/godotengine/godot/assets/11782833/3dd46b62-06f0-4031-b5af-8f30bcfbeffc

**Comment by YuriSizov** [comment]
Reverting to c28a091a09c39ed45931cd7830ae418d369fd9e6 fixes the issue, so this must be a regression from https://github.com/godotengine/godot/pull/83452. cc @RandomShaper
