### ISSUE TITLE
Signal connections created through tool scripts don't show in the editor

### ISSUE THREAD

**Issue by Cre8or** [godotengine/godot#86406]
### Tested versions

Reproducible in: v4.2.stable.official [46dc27791]

### System information

Windows 10 - v4.2.stable.official [46dc27791] - Mobile - dedicated

### Issue description

When connecting functions to signals via tool scripts (in the editor), the newly created connections do not show up in the node's Signals tab. This is strange, because I'd expect *all* connections to show there - irrespective of how they were created.

This can be particularily frustrating, as signal callbacks can persist across script executions (sometimes even undo levels, but that's a different issue). With this behaviour, and the nature of tool scripts (and their many use cases) in mind, it becomes very easy to inadvertedly screw up a scene in the process, since signals may continue to trigger code when they shouldn't (due to these "invisible" connections).

This is my main issue.

---

My second, relevant issue (though more of a general question), is about programmatically disconnecting all connections for a given signal on a node. My current solution involves doing this:

```gdscript
var _signalVar: Variant
var _signal:    Signal

# No way to poll all incoming connections for a given signal name, so let's check them all
for signalDict in get_incoming_connections():

	# Get this connection's signal
	_signalVar = signalDict["signal"]

	# Ensure that the variant is valid (optional, but recommended)
	if not _signalVar is Signal:
		continue

	# Cast the variant to a Signal
	_signal = _signalVar as Signal

	# Finally, check if this connection concerns us
	if _signal.get_name() == "time_changed":
		_signal.disconnect(_on_time_changed)
```

...but this isn't very elegant or maintainable. It'd be much easier if there was a method such as:
```gdscript
func disconnect_signal_recipients(signal_name: String) -> int
```

So, my question here is: am I missing something obvious?

### Steps to reproduce

- In the attached MRP, open the main scene
- Notice how the "Signals" tab shows a connection for the "visibility_changed" signal, but none for the "renamed" signal
- Toggle the visibility of the scene's root `Node3D` and notice the corresponding debug print in the output
- Rename that same root to something else and notice the corresponding debug print in the output

Both signals have a valid connection (as per the debug prints), yet the programmatically added one does not show in the "Signals" tab.

### Minimal reproduction project (MRP)

[Invisible signal connections.zip](https://github.com/godotengine/godot/files/13746050/Invisible.signal.connections.zip)

**Comment by KoBeWi** [comment]
You need to connect with `CONNECT_PERSIST` flag.

**Comment by Cre8or** [comment]
Good input, I wasn't doing that. Unfortunately, that doesn't solve the signal connections not showing in the editor.

**Comment by KoBeWi** [comment]
It does solve the issue, make sure to reload the scene:
![image](https://github.com/godotengine/godot/assets/2223172/92fb0ee5-bbe9-49c7-9e5b-266d8eda317b)

**Comment by Cre8or** [comment]
I stand corrected. It works now - thanks!

Anything that can be done about the signal disconnecting part to make life easier?

**Comment by KoBeWi** [comment]
There is no better way to disconnect all connections currently. You could extract your code into a method, it can be easily reusable. If you think it should be in core, open a [proposal](https://github.com/godotengine/godot-proposals).

Closing.

**Comment by Zireael07** [comment]
This should be clearly documented in the signals page

**Comment by KoBeWi** [comment]
Which signals page?

**Comment by Zireael07** [comment]
Where signals are documented in the docs (I bet they are somewhere since they are a huge part of Godot)

**Comment by KoBeWi** [comment]
You should open an issue on the [doc repo](https://github.com/godotengine/godot-docs) then.
