### ISSUE TITLE
CheckBox and CheckButton don't change appearance when set to disabled.

### ISSUE THREAD

**Issue by SirPigeonz** [godotengine/godot#8640]
**Godot version: 3.0 master**

**Issue description:**
CheckBox and CheckButton don't dim or change color when set to disabled.
Probably they are not finished in new Theme but not 100% sure.

**Comment by n-pigeon** [comment]
@djrm Any clue about this issue?

**Comment by djrm** [comment]
i have no idea, there is no such image as checkbox_disabled, are you sure that it dimed before?

**Comment by n-pigeon** [comment]
Nope. It might be not theme issue after all. We have to investigate it.

**Comment by hickop** [comment]
Probably related to this issue, CheckBox and CheckButton hover style and font hover style are not showing when they are Checked/On.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ProbDenis** [comment]
I can confirm what hickop said: Checkboxes don't show their hover style when they are checked.

**Comment by akien-mga** [comment]
>  CheckBox and CheckButton don't dim or change color when set to disabled.

I can confirm this is still valid in the current master branch. The text next to the Box or Button does get dimmed, but the image itself doesn't change.

On the other hand it didn't change either in 2.1, so it's not a bug, it's just a missing feature :)

I'll retag as enhancement.

> Probably related to this issue, CheckBox and CheckButton hover style and font hover style are not showing when they are Checked/On.

That's a different IMO issue, I'll move it to a new ticket.

**Comment by squished-01** [comment]
Can confirm, still: CheckBox and CheckButton don't dim or change color when set to disabled.  Would be nice to have a fix

**Comment by KoBeWi** [comment]
In 328805ae3 CheckButton has a proper disabled theme, but CheckBox only grays out text. I guess the whole CheckBox should be greyed out?

Here's a PR #28548 for reference how this could be fixed.

**Comment by Calinou** [comment]
It makes sense to gray out the text (or make it semi-transparent) for disabled CheckBoxes, to be consistent with CheckButton behavior.
