### ISSUE TITLE
Forward plus unsupported error in 4.3 dev 1 for new projects

### ISSUE THREAD

**Issue by balloonpopper** [godotengine/godot#86411]
### Tested versions

4.3 dev 1

### System information

Windows 10

### Issue description

An error message pops up when you create a brand new project in an empty folder. 
The error is "The project uses the following features not supported by this build of Godot : Forward plus"

### Steps to reproduce

1. On the Godot project manager, select New 
2. Browse for a folder to put a new project in
3. Create a folder (right click in the browse window) and select the new folder as the project folder
4. Error message appears

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Same for me, I will take a look.
