### ISSUE TITLE
Font breaks when using oversampling and theme overriding on a viewport

### ISSUE THREAD

**Issue by ace24713** [godotengine/godot#86429]
### Tested versions

3.5.3 stable

### System information

Windows 10

### Issue description

Font rendering on some nodes breaks under some specific conditions. The white box here is supposed to be a "0"
![image](https://github.com/godotengine/godot/assets/753186/5a2ac6e7-06e2-4dce-9254-99ffb1ff0396)
These are the conditions I had to tweak to get it to break in my mrp, they might not all be necessary to reproduce, this is just how I personally ran into this:
oversampling needs to be enabled
the node needs to live inside a viewport node
the node needs to override the theme of a parent node
the stretch mode needs to be set to expand

### Steps to reproduce

launch the MRP and simply resize the window to get the pictured result

### Minimal reproduction project (MRP)

[OversamplingBug.zip](https://github.com/godotengine/godot/files/13751880/OversamplingBug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/76450, as this is due to the same cause.

**Comment by ace24713** [comment]
Oh it is? I saw that issue, but I wasn't confident it was the same since that was a 4.0 issue and for some reason my issue only crops up when a theme is overridden. But alright.
