### ISSUE TITLE
Godot doesn't respect window focus (i3wm, i3, tile manager)

### ISSUE THREAD

**Issue by ckdarby** [godotengine/godot#86438]
### Tested versions

- Godot Engine v4.2.1.stable.official [b09f79]
- i3 version 4.21.1 (2022-10-24) © 2009 Michael Stapelberg and contributors

### System information

Ubuntu 22.04 - v4.2.stable.official [b09f79]

### Issue description

Godot doesn't respect window focus (i3wm, i3, tile manager)

### Steps to reproduce

When using a tile manager such as i3 Godot will tell the tile manager it has focus even when it shouldn't.

An example: Would be moving a tile to the left/right of Godot, every application I have used with i3 for ~10 years never grabs focus back onto itself and always respects this, but Godot will instantly window focus itself.

Another example: Have Godot focus, but then use SUPER+ENTER (common) to open up a terminal, the tile manager will say it has focused the terminal, but Godot still maintains context and the typing will go to itself in the editor.

Another example: Show scratchpad in i3, which will focus that window, but again Godot will keep the key inputs on itself even though the window isn't focused.

This is **_VERY_** annoying. No other application in 10 years of using this tile manager has ever done this.

### Minimal reproduction project (MRP)

Any godot project. Just move a tile that has any indirect interactions with Godot.

**Comment by Sauermann** [comment]
Sounds related to #80170 and #68305. Could possibly be a duplicate.

**Comment by ckdarby** [comment]
Will close as I have left my comment that it is still an issue https://github.com/godotengine/godot/issues/68305#issuecomment-2326894344
