### ISSUE TITLE
Basic Navigation Server example doesn't work

### ISSUE THREAD

**Issue by Akamitori** [godotengine/godot#86432]
### Tested versions

v4.1.2.stable.mono.official [399c9dc39]

### System information

Windows 10 - 4.1.20 stable mono win 64 - Forward + - Vulcan api

### Issue description

Tried to get the basic navigation server example to work in C# but it wouldn't produce a viable path.

### Steps to reproduce

Just run this. Included the original gd script as well.
```
using System.Linq;
using Godot;
using Godot.Collections;

public partial class server_gen : Node3D {
    private Rid? map;

    // Called when the node enters the scene tree for the first time.
    public override void _Ready() {
    }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
    public override void _Process(double delta) {
        CallDeferred(server_gen.MethodName.GenerateMeshWithServer);
    }

    public override void _PhysicsProcess(double delta) {
        Dosomething();
    }

    public void GenerateMeshWithServer() {
        if (!map.HasValue) {
            NavigationServer3D.SetDebugEnabled(true);
            var navMesh = new NavigationMesh() {
                AgentHeight = 1,
                AgentRadius = 1,
                CellSize = 0.25f,
                GeometrySourceGroupName = "map",
                GeometrySourceGeometryMode = NavigationMesh.SourceGeometryMode.GroupsWithChildren,
                GeometryParsedGeometryType = NavigationMesh.ParsedGeometryType.StaticColliders,
            };


            var navigationMap = NavigationServer3D.MapCreate();
            NavigationServer3D.MapSetUp(navigationMap, Vector3.Up);
            NavigationServer3D.MapSetActive(navigationMap, true);


            var region = NavigationServer3D.RegionCreate();
            NavigationServer3D.RegionSetTransform(region, Transform3D.Identity);
            NavigationServer3D.RegionSetMap(region, navigationMap);


            navMesh = new NavigationMesh();
            navMesh.Vertices = new[] {
                new Vector3(0, 0, 0),
                new Vector3(9.0f, 0, 0),
                new Vector3(0, 0, 9.0f)
            };
            var x = (new[] { 0, 1, 2 }).Select(v=>Variant.From(v));
            navMesh.Polygons = new Array(x);

            NavigationServer3D.RegionSetNavigationMesh(region, navMesh);


            map = navigationMap;
            //GetTree().PhysicsFrame += Dosomething;
        }
    }

    private void Dosomething() {
        var start_position = new Vector3(0.1f, 0.0f, 0.1f);
        var target_position = new Vector3(1.0f, 0f, 1.0f);
        var     optimize_path = true;

        var path = NavigationServer3D.MapGetPath(
            map!.Value,
            start_position,
            target_position,
            false
        );

        var pathPoints = new Vector3[path.Length];
        for (int i = 0; i < path.Length; i++) {
            pathPoints[i] = path[i];
        }

        GD.Print("Path points: " + string.Join(", ", pathPoints));
    }
}
```

### Minimal reproduction project (MRP)

[MinimalProject.zip](https://github.com/godotengine/godot/files/13752219/MinimalProject.zip)

**Comment by AThousandShips** [comment]
What version are you on? 4.1.20 does not exist

**Comment by Akamitori** [comment]
> What version are you on? 4.1.20 does not exist

v4.1.2.stable.mono.official [399c9dc39]

![image](https://github.com/godotengine/godot/assets/78937210/ae2a432d-8269-46cf-8046-c57ca22f7c2a)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed)

**Comment by Akamitori** [comment]
@AThousandShips  Does 4.2 support it as well?

**Comment by AThousandShips** [comment]
Yes, testing with 4.2.1 would be appreciated as well 🙂, this was just to say that 4.1.2 isn't supported

**Comment by smix8** [comment]
Please try with GDscript first and if GDScript works and only C# doesn't double check all your C# types.

I am not a C# user so I can not tell you what is wrong with this C# code but it has been a common pattern in the recent past with C# specific navigation bugs that the wrong C# types where used so data arrays, especially the PackedArrays, got converted into empty arrays.

**Comment by Akamitori** [comment]
> Yes, testing with 4.2.1 would be appreciated as well 🙂, this was just to say that 4.1.2 isn't supported

@AThousandShips Tried the same with 
![image](https://github.com/godotengine/godot/assets/78937210/d47e2445-e826-42c7-9efc-9c383cd7be97)


 `Server_gen.gd` works as expected while `server_gen.cs` doesn't produce a path.

**Comment by Akamitori** [comment]
> Please try with GDscript first and if GDScript works and only C# doesn't double check all your C# types.
> 
> I am not a C# user so I can not tell you what is wrong with this C# code but it has been a common pattern in the recent past with C# specific navigation bugs that the wrong C# types were used so data arrays, especially the PackedArrays, got converted into empty arrays.

@smix8  Shouldn't the documentation in this case also provide a proper barebones C# example? If that is not possible at this point, having someone familiar with the C# API provide guidelines would be useful

**Comment by AThousandShips** [comment]
Anyone is welcome to write that code 🙂, we however do not require the C# code to be written when adding new documentation information as most people are more familiar with GDScript

**Comment by smix8** [comment]
@Akamitori
The problem of "not enough C# documentation. examples and support" is well known but a collective duty of the C# using community to fix.

**Comment by smix8** [comment]
Needs a C# user to verify or to convert example.

**Comment by smix8** [comment]
Closing as a C# version of that script exists in the documentation.
