### ISSUE TITLE
Race condition in GradientTexture2D.GetImage

### ISSUE THREAD

**Issue by Renari** [godotengine/godot#86489]
### Tested versions

4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When calling `GradientTexture2D.GetImage`, it seems it can return null, this is currently not documented as being possible.

### Steps to reproduce

```csharp
using Godot;
using System.Threading;

public partial class GenerateGradient : Node2D
{
	[Export] public int MapSize = 1024;
	
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
		new Thread(GenerateMap).Start();
	}
	
	private void GenerateMap()
	{
		var gradientTexture = new GradientTexture2D
		{
			Width = MapSize,
			Height = MapSize,
			Fill = GradientTexture2D.FillEnum.Radial,
			FillFrom = new Vector2(0.5f, 0.5f),
			FillTo = new Vector2(0, 0.5f),
			Gradient = new Gradient()
		};
		Image gradientImage;
		do
		{
			GD.Print("pass");
			Thread.Sleep(1);
			gradientImage = gradientTexture.GetImage();
		} while (gradientImage == null);
	}
}
```
In the above example `pass` can be printed out multiple times, based on the documentation I would expect this to only ever be printed once.

### Minimal reproduction project (MRP)

[GetTexture2DImage.zip](https://github.com/godotengine/godot/files/13761227/GetTexture2DImage.zip)

**Comment by jsjtxietian** [comment]
From the code that it can return a null when the texture is invalid. Should we update the document for this?

And it doesn't seem very related to the threading (maybe it's unsafe to call `texture_2d_get` in another thread? Idk )
```
Ref<Image> GradientTexture2D::get_image() const {
	const_cast<GradientTexture2D *>(this)->update_now();
	if (!texture.is_valid()) {
		return Ref<Image>();
	}
	return RenderingServer::get_singleton()->texture_2d_get(texture);
}
```
