### ISSUE TITLE
Game crashes unpredictably with no stack trace and message: "swap_buffers: Vulkan: Cannot submit graphics queue. Error code: VK_ERROR_DEVICE_LOST"

### ISSUE THREAD

**Issue by timcode77** [godotengine/godot#86485]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows 11 Home, Forward+, Intel(R) UHD Graphics

### Issue description

I run the game from the editor and very infrequently, and without any identifiable pattern, the game hangs. I get the familiar Windows "Close program" dialog. There is no stack trace. See screen grab for messages.

![godot_vulkan_error_24 12 23](https://github.com/godotengine/godot/assets/82291606/428c7f3e-44fe-4374-a79d-eaf91e3536ff)

### Steps to reproduce

I cannot provide this as it happens very infrequently (I estimate once approximately every 100 times I run it). It's therefore basically impossible to reproduce. It's a fully 2D game utilizing a lot of Line2Ds, Sprite2Ds, and Polygon2Ds, some lighting, a few shaders, and many dynamically instantiated and freed nodes.  

### Minimal reproduction project (MRP)

As above, I cannot provide this because I cannot work out what reliably reproduces the bug.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929, as this is due to the same cause.
