### ISSUE TITLE
Clicking Context Menus in Fullscreened Godot on Mac causes system menus to disappear

### ISSUE THREAD

**Issue by jalder89** [godotengine/godot#86480]
### Tested versions

Appears to have been introduced in v4.2.beta1.official [b1371806a] but I don't see how the particle system changes could cause this. Issue was not reproducible in v4.2.dev6.official [57a6813bb]

- Reproducible on Godot Engine builds:
  - v4.2.beta1.official [b1371806a]
  - v4.2.stable.official [46dc27791]
  - v4.2.1.stable.official [b09f793f5]
  - v4.2.1.stable.mono.official [b09f793f5]
  - v4.3.dev1.official [9d1cbab1c]
  - v4.3.dev1.mono.official [9d1cbab1c]
  - v4.3.stable.official [77dcf97d8]

- Not-Reproducible on Godot Engine builds:
  - v4.1.stable.official [970459615]
  - v4.1.1.stable.official [bd6af8e0e]
  - v4.1.2.stable.official [399c9dc39]
  - v4.1.3.stable.official [f06b6836a]
  - v4.2.dev6.official [57a6813bb]

### System information

Godot v4.2.1.stable.official - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M3 Max - Apple M3 Max (14 Threads)
Godot v4.3.stable.official - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

When Godot is fullscreened/maximized and you right-click to open a context menu, the system menus and window controls disappear until focus is moved to another app. For example, moving to Chrome and clicking inside the window and then moving back to fullscreen Godot restores the close/min/max buttons.

The issue is reproducible when opening dropdown boxes or dialog boxes as well. Maximize Godot, select a node, use inspector to open a dropdown menu. The menu won't open until moving the mouse off the selected element. 

Very similar to #81828 but that issue impacts older versions, this issue wasn't introduced until 4.2 stable. 

Unlike Issue 81828, screen recording does not block this problem:

https://github.com/godotengine/godot/assets/8131741/d0f5bbc0-773c-48a0-955a-5b78c4a903f3

### Steps to reproduce

1. Open one of the tested versions on MacOS
2. Create a new blank project
3. Maximize the Godot Editor
4. Open a context menu by right clicking a file in the file system
6. Check the system menu and window controls are now blank

### Minimal reproduction project (MRP)

N/A

**Comment by jalder89** [comment]
This is still present as of 4.3

**Comment by arisona** [comment]
Unable to reproduce this using above repro. Tried on laptop display as well as external display.

Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

**Comment by jalder89** [comment]
> Unable to reproduce this using above repro. Tried on laptop display as well as external display.
> 
> Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

I just tested after updating MacOS and the upgrade to 14.6.1 seems to have resolved this issue and the one we were seeing with dropdowns in #81828

**Comment by jalder89** [comment]
> Unable to reproduce this using above repro. Tried on laptop display as well as external display.
> 
> Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

I just tested after updating MacOS and the upgrade to 15.0 seems to have resolved this issue and the one we were seeing with dropdowns in #81828

Closing as resolved for Godot v4.3.stable - macOS 15.0.0 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)
