### ISSUE TITLE
The menu bar stops appearing after saving in the fullscreen editor on Mac

### ISSUE THREAD

**Issue by umutseven92** [godotengine/godot#86495]
### Tested versions

- Reproducible in 4.2.1

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

The menu bar is the bar at the top of the screen in macOS, that shows additional menu items for the current application. When an app is windowed the menu bar is always visible, and when an app is fullscreen, the app slides into view if the user drags their cursor to the top.

With Godot, this behaviour works until the user saves the project, after which the menu bar will not appear in fullscreen. Switching to another window, then switching back to Godot fixes this, until the user saves again.

A video showing the issue is attached below:

https://github.com/godotengine/godot/assets/3675030/77ea2c6d-3c44-40d7-a55b-648c1bf5def0

### Steps to reproduce

- Create or load a project. 
- Make sure the editor is in fullscreen. Drag mouse to the top of the screen and see the menu bar appearing.
- Do any change, and save using Cmd + S. Wait for the save modal to close.
- Drag mouse to the top of the screen again, and see that the menu bar is no longer appearing.

### Minimal reproduction project (MRP)

Reproducible with a new, clean project.

**Comment by Calinou** [comment]
This was confirmed on the Godot Forums: https://forum.godotengine.org/t/bugs-in-macos-4-2-version/44579
