### ISSUE TITLE
CAMERA_DIRECTION_WORLD shader built-ins does not yield the expected results

### ISSUE THREAD

**Issue by Solesaver** [godotengine/godot#86502]
### Tested versions

Reproduceable in v4.2.1.stable.official [b09f793f5]. Looking at the history, it looks like this has never been correct.

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.4633) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

CAMERA_DIRECTION_WORLD is filled with the incorrect vector, and appears to have been so when first implemented.

	actions.renames["CAMERA_DIRECTION_WORLD"] = "scene_data.view_matrix[3].xyz";

### Steps to reproduce

Create a Camera3D at the origin facing in the negative Z direction. Make a child plane facing the camera, and give it a shader material with the following fragment shader:

```
void fragment () {
    ALBEDO = (normalize(CAMERA_DIRECTION_WORLD) + vec3(1.0f)) / 2.0f;
}
```

Translate the camera without rotating it. See that the texture changes color despite the camera's world direction not changing and the other operations being constant.

Replace the shader with the following:

```
void fragment () {
    vec3 dir = normalize(INV_VIEW_MATRIX * vec4(0.0f,0.0f,1.0f,0.0f)).xyz;
    ALBEDO = (normalize(dir) + vec3(1.0f)) / 2.0f;
}
```

Translate the camera without rotation and notice that the color does not change as expected. Rotate the camera and note that the color does change.

I believe the relevant line in godot/drivers/gles3/storage/material_storage.cpp should be:
'actions.renames["CAMERA_DIRECTION_WORLD"] = "scene_data.inv_view_matrix[2].xyz";`

### Minimal reproduction project (MRP)

[mgp.zip](https://github.com/godotengine/godot/files/13764378/mgp.zip)

WASD to move. QE to turn left and right.
Feel free to delete the noise floor, but I find it helps me be sure that the camera is actually moving/rotation when necessary.

**Comment by jsjtxietian** [comment]
> actions.renames["CAMERA_DIRECTION_WORLD"] = "scene_data.view_matrix[3].xyz";

Yes  the `[3]` here is weird because normally the view matrix's forth column is `0 0 0 1`
