### ISSUE TITLE
Command + B not working on Macos Apple Chip

### ISSUE THREAD

**Issue by ilhomsoliev** [godotengine/godot#86506]
### Tested versions

Godot v4.2.1.stable - macOS 12.5.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### System information

Godot v4.2.1.stable - macOS 12.5.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

To run the project there is shortcut Command + B in macos but it is not working

### Steps to reproduce

Just press the shortcut

### Minimal reproduction project (MRP)

Any project can work

**Comment by bwiklund** [comment]
does this happen in the 2d/3d scene view or just the text editor? for me it works in the scene, although I would like it to work in the text editor as well.

**Comment by Listwon** [comment]
Fixed by https://github.com/godotengine/godot/pull/85527
