### ISSUE TITLE
Godot 4.2 BlendSpace2D/AnimationTree: Add Animation options are not showing up when using create points

### ISSUE THREAD

**Issue by alicemightbehere** [godotengine/godot#86510]
### Tested versions

Godot 4.2

### System information

windows 10 Godot 4.2.1 stable Steam version

### Issue description

When attempting to create points on the blendspace2D grid nothing shows up when I left click and hover over Add Animations, just a thin grey line. This has to be a bug.
![fe721df84e5fe182e9ac6db656bc6b7c](https://github.com/godotengine/godot/assets/154841990/11a506c8-3c38-456c-98ca-71716434bbcb)

### Steps to reproduce

Just trying to add animation using create point

### Minimal reproduction project (MRP)

[2d game practice.zip](https://github.com/godotengine/godot/files/13767339/2d.game.practice.zip)

**Comment by prollygon** [comment]
I just tried it and it works fine? Make sure you assign the Anim Player property to your AnimationPlayer node in the Inspector ... It wasn't assigned when I loaded up your project

**Comment by alicemightbehere** [comment]
Oh freaking hell okay I followed the tutorial wrong and did that in the
advanced expression node above it. Sorry for the trouble, thank you for
taking the time to look at it.

**Comment by Sauermann** [comment]
Closing this as resolved according to the comment above.
