### ISSUE TITLE
Raycast Using 2D Space Gives Empty Result

### ISSUE THREAD

**Issue by Cosmic-Phantom** [godotengine/godot#86529]
### Tested versions

- Reproducible in: 4.2.1.stable, 4.2.1.rc1, v4.1.3.stable.

### System information

Godot v4.2.1.stable - Ubuntu 22.04.3 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 (nvidia; 535.129.03) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I utilized the Godot Docs for 4.2 to learn how to create raycasts using physics space.
Using the code provided in the docs, I expected to get a dictionary of raycast information, however this yielded an empty dictionary instead. This occurred on all 2D physics engines.

### Steps to reproduce

Download the project below and press run. It should quickly start, run for around 5 physics frames, then quit. It will print results to the console, all return empty for me.

### Minimal reproduction project (MRP)

[Broken Raycast.zip](https://github.com/godotengine/godot/files/13772685/Broken.Raycast.zip)

**Comment by Lippanon** [comment]
Your MRP is nothing but a single Node2D. The raycast has nothing to hit.
I'll assume you mean these [docs](https://docs.godotengine.org/en/latest/tutorials/physics/ray-casting.html), it states `The result is a dictionary. If the ray didn't hit anything, the dictionary will be empty. If it did hit something, it will contain collision information:`.
The `intersect_ray` function also states `If the ray did not intersect anything, then an empty dictionary is returned instead.`.

As there is nothing to intersect, it returns an empty dictionary, so your code prints an error.

I modified your MRP to include a StaticBody2D at the position you cast the ray to, and behold, it returns the information.
Modified MRP: 
[Raycast is not broken.zip](https://github.com/godotengine/godot/files/13772776/Raycast.is.not.broken.zip)

**Comment by Cosmic-Phantom** [comment]
Ouch, now I feel silly. I somehow overlooked that line when reading it, I should have payed more attention. Thanks.
