### ISSUE TITLE
Visual bug. Renaming nodes placement in Scene section using keyboard.

### ISSUE THREAD

**Issue by PrinceMerluza** [godotengine/godot#8652]
Windows 7. Godot v2.1.3-stable

Here's an flv of it. The renaming shows on the original node you selected even if you've already selected a different one by the arrow keys on the keybaord.

[https://gfycat.com/ReadyZestyAdmiralbutterfly](https://gfycat.com/ReadyZestyAdmiralbutterfly)

**Comment by Gybes** [comment]
404 URL

**Comment by Zireael07** [comment]
@Gybes: copy the URL instead of clicking it (it works), the url upon clicking is indeed weird. I guess @hero2bash did something weird with GitHub's formatting.

**Comment by bojidar-bg** [comment]
(Fixed the url, next time don't do `[https://....](url)` but `[text about the link](https://...)`)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
As there was no answer to the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
