### ISSUE TITLE
Can't jump to definition when inside array square brackets

### ISSUE THREAD

**Issue by thiscris** [godotengine/godot#86524]
### Tested versions

- Reproducible in 4.1.stable

### System information

Godot v4.1.stable - Ubuntu 18.04.6 LTS (Bionic Beaver)

### Issue description

Using the built in text editor, variables inside array[] can not be traced to their definition. 
```
var array = []
var index = 1

func _ready():
	print(index)
	print(array)
	var b = array[index]
```
in the example above it is possible to go to the definition of index when it is inside print(index) , but not when inside array[index]

### Steps to reproduce

1. Open the built-in script editor
2. Find an array that uses a non-literal index (e.g. `arr[i]` )
3. Hold Ctrl key and hover over the index variable
**Expected behavior:**
The variable is underlined and clicking it sends the cursor to its definition
**Actual behavior:**
Nothing happens

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
I confirm this issue to happen in 4.2 (Windows 10) as well

**Comment by HolonProduction** [comment]
Related to #76955

The code lookup will search for `index` on `array` instead of the current scope, since the index is is parsed as subscript.
