### ISSUE TITLE
Spotlights with shadows enabled cast light between mesh faces

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8654]
**Godot version: Master f527a6946**

**Issue description:**
Spotlight with shadows (with default values) in some positions cast some light between mesh faces.

**Steps to reproduce:**

Add a spotlight with shadows enabled and put the center near a mesh face like this:
![spotlightshadow](https://cloud.githubusercontent.com/assets/10215987/25749147/e159c066-3183-11e7-96d2-d06e3512bc02.png)

That line on the "floor" should not be there.

**Comment by akien-mga** [comment]
Would be good to have a minimal reproducer project to be able to test easily.

**Comment by eon-s** [comment]
Here you go:
[spotlightshadow.zip](https://github.com/godotengine/godot/files/1011587/spotlightshadow.zip)


_Everything should look black instead of gray but that may be for another issue..._

**Comment by eon-s** [comment]
I'm unable to reproduce this in a late january build.
