### ISSUE TITLE
`OS.get_system_font_path` returns a path with mixed back and forward slashes

### ISSUE THREAD

**Issue by Pshy0** [godotengine/godot#86544]
### Tested versions

Happened in Godot v4.2

### System information

Windows 10

### Issue description

The call `OS.get_system_font_path("sans-serif")` returns `C:\WINDOWS\FONTS/arial.ttf`.
It should probably return `C:/WINDOWS/FONTS/arial.ttf` instead.

### Steps to reproduce

Run on windows:
```
print(OS.get_system_font_path("sans-serif"))
```

### Minimal reproduction project (MRP)

N/A, just do `print(OS.get_system_font_path("sans-serif"))`.

**Comment by AThousandShips** [comment]
This is handled in `platform/windows/os_windows.cpp`, it misses the required normalisation, see the neighboring methods for examples of how to do this

**Comment by RealMadvicius** [comment]
Using `std::filesystem::path` would solve the normalisation issue with path across all existing OS in theory

**Comment by AThousandShips** [comment]
We [don't use the STL](https://docs.godotengine.org/en/stable/about/faq.html#doc-faq-why-not-stl), also that part of the library in particular has had issues across compilers AFAIR
