### ISSUE TITLE
Geometry2D.offset_polygon not working v4.2.1 stable

### ISSUE THREAD

**Issue by bulupe** [godotengine/godot#86548]
### Tested versions

Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

MacOS Sonoma 14.2.1 v4.2.1.stable.official [b09f793f5]

### Issue description

Geometry2D.offset_polygon or Geometry2D.offset_polyline return either empty or one point(0,0) array. 

### Steps to reproduce

Trying to modify any Polygon2D.polygon or any PackedVector2D array results the same.

[(0, 0)]

Ps: Example includes both clockwise and counter clockwise polygons.

```

### Minimal reproduction project (MRP)

func _input(event):
	if (event is InputEventMouseButton):
		if (event.pressed):
			var dataClockwise:PackedVector2Array = [Vector2(50,50), Vector2(50,400), Vector2(250,400), Vector2(250,50)]
			var dataCC:PackedVector2Array = [Vector2(50,50), Vector2(50,250), Vector2(250,400), Vector2(400,50)]
			
			print(dataClockwise)
			print(dataCC)
			
			var resultClockwise:PackedVector2Array = Geometry2D.offset_polygon(dataClockwise, 20, 0)
			var resultCC:PackedVector2Array = Geometry2D.offset_polygon(dataCC, 20, 0)
			
			print ("Clockwise")
			print(resultClockwise)
			print ("Counter Clockwise")
			print(resultCC)
```

**Comment by AThousandShips** [comment]
Does it work if the polygon is clockwise? The example code uses a clockwise polygon

**Comment by bulupe** [comment]
Nope it's the same result actually it was Counter Clockwise. I have changed the MRP to include both.

**Comment by TheSkyOne** [comment]
i came across this issue just now. and i realized that offset_polygon and offset_polyline return an array of PackedVector2Array. and it seems that when you assign the result to a variable whose typed value is PackedVector2Array, it gives [(0, 0)].
essentially what you need to do is access the inner array, which can simply be done with result[0] (result is what offset_polyline or polygon give you)

**Comment by kleonc** [comment]
Here's the issue:

> var resultClockwise:PackedVector2Array = Geometry2D.offset_polygon(dataClockwise, 20, 0)
> 			var resultCC:PackedVector2Array = Geometry2D.offset_polygon(dataCC, 20, 0)

`Geometry2D.offset_polygon` returns an `Array[PackedVector2Array]`, not a `PackedVector2Array`. When statically typed like that the conversions from the inner `PackedVector2Array`s to `Vector2`s fail and thus the resulting array is empty. If untyped or typed properly the results are correct:
```gdscript
var dataCW:PackedVector2Array = [Vector2(50,50), Vector2(50,400), Vector2(250,400), Vector2(250,50)]
var dataCCW:PackedVector2Array = [Vector2(50,50), Vector2(250,50), Vector2(250,400), Vector2(50,400)]

var resultCW: Array[PackedVector2Array] = Geometry2D.offset_polygon(dataCW, 20, 0)
var resultCCW: Array[PackedVector2Array] = Geometry2D.offset_polygon(dataCCW, 20, 0)
```
```
CW:  [[(270, 41.71573), (270, 408.2843), (258.2843, 420), (41.71573, 420), (30, 408.2843), (30, 41.71573), (41.71573, 30), (258.2843, 30)]]
CCW: [[(270, 41.71573), (270, 408.2843), (258.2843, 420), (41.71573, 420), (30, 408.2843), (30, 41.71573), (41.71573, 30), (258.2843, 30)]]
```

So no bug in here, that's a user error.

---

The only question is whether the conversion should fail silently like that? :thinking:

**Comment by TheSkyOne** [comment]
definitely user error. but i do think the silent failing should be addressed somehow, considering how easy it is to miss the Array[] part of the return variable. just my opinion tho, i am not an experienced dev to know how these things need to be handled.

**Comment by kleonc** [comment]
The conversion issue is tracked in #60882, closing as duplicate then.
