### ISSUE TITLE
Running the game should commit the pending changes in textboxes in the Inspector

### ISSUE THREAD

**Issue by aspragg** [godotengine/godot#86558]
### Tested versions

Latest stable release on Windows 11

### System information

Latest stable release on Windows 11

### Issue description

If I make a change in a textbox in the Inspector, and I hit F5, my change is not included.  The change is only included by hitting Enter or tabbing out of the textbox.

This behavior is inconsistent with scripting changes.  I can change a script and hit F5 without first saving or committing in, and my changes are automatically included.

### Steps to reproduce

Create a scene with a Sprite2D.  Place it in the game world.  Note the X and Y coordinates.
Run the game, verifying the scene is at position X,Y.
Stop the game.
Change the Transform X value to a new value, but don't hit Enter or click anywhere else.
Hit F5 to run the game.

Expected behavior:  The game object is at the new X value
Actual behavior: The game object is at the original X value

### Minimal reproduction project (MRP)

Any trivial project will display this behavior

**Comment by AThousandShips** [comment]
Closing in favor of:
* https://github.com/godotengine/godot-proposals/discussions/8734
