### ISSUE TITLE
Audio Stream Importer playback position is not updated unless playhead is visible

### ISSUE THREAD

**Issue by PanForPancakes** [godotengine/godot#86550]
### Tested versions

- Reproducible in: v4.2.1.stable.official [b09f793f5] and v4.3.dev1.official [9d1cbab1c]

### System information

Godot v4.2.1.stable - Windows 10.0.22621

### Issue description

When imported audio is playing in Audio Stream Importer, unless the playhead is visible, current playback position is not updated.

### Steps to reproduce

- Import audio file into project (tested with >3 minute long .mp3)
- Double-click on imported file in File System tab to open Audio Stream Importer
- Press play in bottom-left corner, notice that current playback position in the bottom-right corner is updating
- Make playhead leave your screen by zooming in and etc., notice that current playback position is no longer updated

### Minimal reproduction project (MRP)

N/A

**Comment by alessandrofama** [comment]
The `_current_label` doesn't get updated since we return early here:
https://github.com/godotengine/godot/blob/179dfdc8d78b5bd5377dd115af026df58308bdaf/editor/import/audio_stream_import_settings.cpp#L280-L283

Any reason for this or could we set the text of the label before that check?

**Comment by akien-mga** [comment]
The label could be set before. The early return is presumably to avoid unnecessary computational if there's nothing to display, but I'd that prevents changing state for a future display, that's a bug.
