### ISSUE TITLE
The default Godot 4.2.1 application crashes in compatible mode on the Redmi 4X with OpenGL ES 3.2

### ISSUE THREAD

**Issue by 8Observer8** [godotengine/godot#86565]
Here is my topic on the Godot forum: https://forum.godotengine.org/t/run-time-error-on-android/36928

### Tested versions

Godot 4.2.1 in compatible mode:

![image](https://github.com/godotengine/godot/assets/3908473/2def57e4-e085-46d3-bed6-45b131164ff9)

### System information

Window 10, Redmi 4X (OpenGL ES 3.2)

![image](https://github.com/godotengine/godot/assets/3908473/e316ee6c-121a-4179-89e1-2d70444a3748)

I wrote a simple application in Qt that shows an OpenGL version:

![image](https://github.com/godotengine/godot/assets/3908473/23e296ec-a3b1-4c3d-a07e-98bd93d0bfdb)

### Issue description

The application crashes on the Redmi 4X with the message:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mygame/com.godot.game.GodotApp}: java.lang.IllegalStateException: Unable to initialize engine native layer
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6238)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.IllegalStateException: Unable to initialize engine native layer
at org.godotengine.godot.GodotFragment.performEngineInitialization(GodotFragment.java:191)
at org.godotengine.godot.GodotFragment.onCreate(GodotFragment.java:182)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
at org.godotengine.godot.GodotActivity.onCreate(GodotActivity.kt:84)
at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
at android.app.Activity.performCreate(Activity.java:6857)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
... 9 more
```

### Steps to reproduce

Build to the device with OpenGL ES 3.2. In my case I use Redmi 4X

### Minimal reproduction project (MRP)

[FirstProject.zip](https://github.com/godotengine/godot/files/13781499/FirstProject.zip)

**Comment by joined72** [comment]
From my tests on an old Android devices that works fine on GLES3 on others apps and crashes on Godot 4, I think the real problem with GLES3 Rendering AREN'T the old Android devices GLES buggy drivers but a Godot initialization bugs of the GLES3 Rendering.

**Comment by joined72** [comment]
How can I compile the Android Templates so to obtain in the call stack also the .cpp lines and not only the .java/.kt ones?

**Comment by Alex2782** [comment]
@8Observer8 could you run "logcat" without a filter, redirect the output to a file, compress it with zip and upload it here? 

`adb logcat > logs.txt `

----------------------

`Unable to initialize engine native layer` 

'OpenGL API OpenGL ES' is only initialized afterwards. (i think)

<details> <summary>my logcat / debug app</summary>

```
12-31 02:46:52.703 10245 10245 D Godot   : BEGIN onInitNativeLayer: 
12-31 02:46:52.703 10245 10245 D Godot   : GodotLib.initialize: 
12-31 02:46:52.707 10245 10245 I godot   : FileAccessAndroid::asset_manager: true
12-31 02:46:52.708 10245 10245 I godot   : p_directory_access_handler: true
12-31 02:46:52.708 10245 10245 I godot   : p_file_access_handler: true
12-31 02:46:52.708 10245 10245 I godot   : p_net_utils: true
12-31 02:46:52.708 10245 10245 I godot   : END Java_org_godotengine_godot_GodotLib_initialize
12-31 02:46:52.708 10245 10245 D Godot   : activity.assets: android.content.res.AssetManager@fde58a3
12-31 02:46:52.708 10245 10245 D Godot   : io: org.godotengine.godot.GodotIO@1bf97a0
12-31 02:46:52.708 10245 10245 D Godot   : netUtils: org.godotengine.godot.utils.GodotNetUtils@4867f59
12-31 02:46:52.708 10245 10245 D Godot   : directoryAccessHandler: org.godotengine.godot.io.directory.DirectoryAccessHandler@fe7871e
12-31 02:46:52.708 10245 10245 D Godot   : fileAccessHandler: org.godotengine.godot.io.file.FileAccessHandler@ff3dbff
12-31 02:46:52.708 10245 10245 D Godot   : useApkExpansion: false
12-31 02:46:52.708 10245 10245 D Godot   : GodotLib.setup: 
12-31 02:46:52.738 10245 10245 E godot   : USER ERROR: Couldn't load file 'res://project.binary', error code 19.
12-31 02:46:52.738 10245 10245 E godot   :    at: _load_settings_text_or_binary (core/config/project_settings.cpp:793)
12-31 02:46:52.748 10245 10245 D Godot   : nativeLayerInitializeCompleted: true
12-31 02:46:52.748 10245 10245 D Godot   : nativeLayerSetupCompleted: true
12-31 02:46:52.748 10245 10245 D Godot   : isNativeInitialized: true
12-31 02:46:52.748 10245 10245 D Godot   : END onInitNativeLayer: 

---------------

12-31 02:46:52.856 10245 10282 I godot   : Godot Engine v4.3.dev.custom_build.b80db260a - https://godotengine.org
12-31 02:46:53.095 10245 10282 I godot   : OpenGL API OpenGL ES 3.2 V@0502.0 (GIT@193b2ee, I593c16c433, 1633593732) (Date:10/07/21) - Compatibility - Using Device: Qualcomm - Adreno (TM) 650
12-31 02:46:53.095 10245 10282 I godot   :  
12-31 02:46:53.919 10245 10282 D Godot   : OnGodotSetupCompleted
12-31 02:46:53.928 10245 10282 D Godot   : OnGodotMainLoopStarted
```
</details>

For example, the following components are initialized in the 'Native Layer' (GodotLib): IO, network, AssetManager, TTS (Text-to-Speech). I might share my debug app for you later too, I'd probably have to add more logcat output.

**Comment by 8Observer8** [comment]
I ran "Remote Debug":

![image](https://github.com/godotengine/godot/assets/3908473/db4ea3dd-8a66-4e08-9f2c-c7b7c2684c71)

`adb logcat > result.txt`

[result.zip](https://github.com/godotengine/godot/files/13800301/result.zip)

**Comment by 8Observer8** [comment]
I uploaded APK file from the test above on DropBox and installed it on device: [apk-file](https://www.dropbox.com/scl/fi/uwv09uke1y8wiautycezo/android-build-debug-godot4.apk?rlkey=k1o09xavvxf68n1mmff2h4ak1&dl=1). This is a result:

![image](https://github.com/godotengine/godot/assets/3908473/34687735-6949-4bab-a6dd-79485c7816e4)

![image](https://github.com/godotengine/godot/assets/3908473/f82ac175-b258-4489-94d6-9ee2c1d65ce8)

**Comment by saierXP** [comment]
I was able to run it with your project after exporting it, but not with the apk you provided, it pops up a popup like yours.
After comparing the two apk files, I realized that you didn't set the main scene to run, and the scene is missing from your apk.
![7zFM_kRKna43NqA](https://github.com/godotengine/godot/assets/45038185/135f3541-a9fb-4b23-a747-17b7c98ace87)

**Comment by Alex2782** [comment]
`Unable to initialize engine native layer` **I could not find** ([result.zip](https://github.com/godotengine/godot/files/13800301/result.zip))


<details><summary>logcat</summary>

```
12-31 09:17:20.076  8813  8939 I Adreno  : QUALCOMM build                   : dd15ef5, Ic280a69317
12-31 09:17:20.076  8813  8939 I Adreno  : Build Date                       : 05/09/17
12-31 09:17:20.076  8813  8939 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
12-31 09:17:20.076  8813  8939 I Adreno  : Local Branch                     : 
12-31 09:17:20.076  8813  8939 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
12-31 09:17:20.076  8813  8939 I Adreno  : Remote Branch                    : NONE
12-31 09:17:20.076  8813  8939 I Adreno  : Reconstruct Branch               : NOTHING
12-31 09:17:20.113  8758  8758 I Finsky  : [1] sbr.ajn(13): DTU: Received onPackageAdded, replacing: false
12-31 09:17:20.213  8813  8938 W RegularContextFactory: creating OpenGL ES 3.0 context :
12-31 09:17:20.221  8813  8939 I OpenGLRenderer: Initialized EGL, version 1.4
12-31 09:17:20.221  8813  8939 D OpenGLRenderer: Swap behavior 1
12-31 09:17:20.233  8813  8813 W art     : Long monitor contention with owner GLThread 2654 (8938) at void org.godotengine.godot.gl.GLSurfaceView$GLThread.guardedRun()(GLSurfaceView.java:1330) waiters=0 in void org.godotengine.godot.gl.GLSurfaceView$GLThread.queueEvent(java.lang.Runnable) for 129ms
12-31 09:17:20.272  8813  8938 I godot   : Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
------------
12-31 09:17:20.689  1536  1561 I ActivityManager: Displayed com.example.test/com.godot.game.GodotApp: +10s266ms
------------
12-31 09:17:22.378  8813  8938 I godot   : OpenGL API OpenGL ES 3.2 V@145.0 (GIT@Ic280a69317) - Compatibility - Using Device: Qualcomm - Adreno (TM) 505
12-31 09:17:22.380  8758  8758 I Finsky  : [1] apcc.e(7): registerListener
12-31 09:17:22.425  8813  8938 I godot   :  
12-31 09:17:22.468  8813  8938 I libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
--------

12-31 09:17:24.997  8813  8938 D Godot   : OnGodotSetupCompleted
12-31 09:17:25.054  8758  8832 I Finsky  : [22667] mac.ain(129): [ContentSync] finished, scheduled=true
12-31 09:17:25.084  8813  8938 D Godot   : OnGodotMainLoopStarted

```
</details>

You could still try 'OpenGL Debug', maybe we will see more when the problem with the "native layer" is solved.  

![Bildschirmfoto 2023-12-31 um 14 50 31](https://github.com/godotengine/godot/assets/41921395/c394464d-a27b-4db2-9558-a081f77c408d)

**Comment by Alex2782** [comment]
On my Samsung Tab (2016, Android 8) no problems with 'MRP': [FirstProject.zip](https://github.com/godotengine/godot/files/13781499/FirstProject.zip)

but with your exported APK, what saierXP has already found out:


```
12-31 16:46:01.953 11228 11228 I godot   : Error: Can't run project: no main scene defined in the project.
12-31 16:46:02.155 11228 11228 E Godot   : Unable to setup the Godot engine! Aborting...
12-31 16:46:02.254 11228 11228 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.godot.game.GodotApp}: java.lang.IllegalStateException: Unable to initialize engine native layer
```



---------------

I find this error strange `ClassNotFoundException`, also seen in your logs. I can only reproduce this in my projects if I have not selected the appropriate CPU architecture. In your APK file I see "armeabi-v7a" (arm32), but my old Samsung tablet is also "arm32"
```
12-31 16:46:01.792 11228 11228 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.WindowInsetsAnimation$Callback" on path: DexPathList[[zip file "/data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/lib/arm, /data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
```

**Comment by joined72** [comment]
> On my Samsung Tab (2016, Android 8) no problems with 'MRP': [FirstProject.zip](https://github.com/godotengine/godot/files/13781499/FirstProject.zip)
> 
> but with your exported APK, what saierXP has already found out:
> 
> ```
> 12-31 16:46:01.953 11228 11228 I godot   : Error: Can't run project: no main scene defined in the project.
> 12-31 16:46:02.155 11228 11228 E Godot   : Unable to setup the Godot engine! Aborting...
> 12-31 16:46:02.254 11228 11228 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.godot.game.GodotApp}: java.lang.IllegalStateException: Unable to initialize engine native layer
> ```
> 
> I find this error strange `ClassNotFoundException`, also seen in your logs. I can only reproduce this in my projects if I have not selected the appropriate CPU architecture. In your APK file I see "/lib/armeabi-v7a" (arm32), but my old Samsung tablet is also "arm32"
> 
> ```
> 12-31 16:46:01.792 11228 11228 I zygote  : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.WindowInsetsAnimation$Callback" on path: DexPathList[[zip file "/data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/lib/arm, /data/app/com.example.test-XMzITyU375If57l4l3H8Qw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
> ```

Seems like the APK are trying to using an Android 11 WindowInsetsAnimation API on an old Android version. I found a similar bug too. I think this would be to investigate too.

**Comment by joined72** [comment]
My first thinking was a misconfigured Grande that used to build an Android version greater that 24, is this possible?

**Comment by 8Observer8** [comment]
> After comparing the two apk files, I realized that you didn't set the main scene to run

Yes, in `FirstProject` I forgot about setting the main scene but in this [apk-file](https://www.dropbox.com/scl/fi/uwv09uke1y8wiautycezo/android-build-debug-godot4.apk?rlkey=k1o09xavvxf68n1mmff2h4ak1&dl=1) I set the main scene. But it has the same errors like with `FirstProject`

**Comment by joined72** [comment]
> > After comparing the two apk files, I realized that you didn't set the main scene to run
> 
> Yes, in `FirstProject` I forgot about setting the main scene but in this [apk-file](https://www.dropbox.com/scl/fi/uwv09uke1y8wiautycezo/android-build-debug-godot4.apk?rlkey=k1o09xavvxf68n1mmff2h4ak1&dl=1) I set the main scene. But it has the same errors like with `FirstProject`

Ok but we need the source project to can debug it on Android studio.

**Comment by 8Observer8** [comment]
My USB cable doesn't work now. It is charging but it is unable to connect with device. Laptop doesn't see the phone. I tried to update drivers but it didn't help. I tried another USB ports. I restarted my laptop a few times. Sometimes laptop see a device but short period of time. I tried to use Emulator but it uses OpenGL ES 2.0. Godot 4 uses OpenGL ES 3.0

> Ok but we need the source project to can debug it on Android studio
[TestProject.zip](https://github.com/godotengine/godot/files/13802367/TestProject.zip)

**Comment by saierXP** [comment]
> > After comparing the two apk files, I realized that you didn't set the main scene to run
> 
> Yes, in `FirstProject` I forgot about setting the main scene but in this [apk-file](https://www.dropbox.com/scl/fi/uwv09uke1y8wiautycezo/android-build-debug-godot4.apk?rlkey=k1o09xavvxf68n1mmff2h4ak1&dl=1) I set the main scene. But it has the same errors like with `FirstProject`

I think you updated the same apk,their md5 is same.

**Comment by 8Observer8** [comment]
> I think you updated the same apk,their md5 is same.

Sorry, `FirstProject` doesn't have APK. I have only one for Godot 4.

I unable to debug with USB adapter but I can uploaded APK to device using DropBox.

I downloaded Godot 3.5.3. It is a project and APK: [TestProject-Godot3](https://www.dropbox.com/scl/fi/k00cd0igdoz6mn8aurqqx/TestProject-Godot3.zip?rlkey=jhksaz41aqa8yoqd6w9f2p328&dl=0)

The Godot3 APK crashes on `Redmi 4X` with the message:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/santoni/santoni:7.1.2/N2G47H/9.6.27:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 20406, tid: 20470, name: GLThread 3245 »> org.godotengine.testprojectgodot3 «<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x40
r0 8f8ab6eb r1 00000000 r2 cff66818 r3 00000000
r4 cff66828 r5 00000000 r6 00000000 r7 cff66818
r8 f44e0008 r9 f44e0008 sl 00000000 fp cff668f4
ip d1fafb2c sp cff667a0 lr d025c284 pc d1a40af0 cpsr 600e0010

backtrace:
#00 pc 017f6af0 /data/app/org.godotengine.testprojectgodot3-1/lib/arm/libgodot_android.so (offset 0x2e1000)
#01 pc 00012280 /data/app/org.godotengine.testprojectgodot3-1/lib/arm/libgodot_android.so (offset 0x2e1000)
```

**Comment by saierXP** [comment]
If you run project in pc with F5 key,it will let you select main scene.

**Comment by 8Observer8** [comment]
I added a main scene and updated the links for Godot3 above. It works on Redmi 4X!

**Comment by Alex2782** [comment]
@8Observer8 What happens with these 2 apps on Redmi 4X? Or can you no longer test it properly?
> My USB cable doesn't work now.

-----------------
`adb logcat > logs.txt`

[gles3jni.apk](https://drive.google.com/file/d/1mcJ-O0SkhF8foCcqgODjie_BIih1FsFV/view?usp=sharing) (815 KB, demo: [ndk-sample on github](https://github.com/android/ndk-samples/tree/main/gles3jni))

[godot_test_android_dev.apk](https://drive.google.com/file/d/1ICWa7zxRlj5fySiDgGz74WkiwhrEt5fa/view?usp=sharing)(284 MB download, arm32 + arm64, maybe 800 MB on phone)

**Comment by 8Observer8** [comment]
I can test but using DropBox only. I drop APK to DropBox and install in on the phone from DropBox.

**Comment by Calinou** [comment]
> The phone is connected via USB. Charging works. But adb usb says that no devices are found:

You need to enable USB debugging on the device. You can do this in the device's developer settings, which you need to enable by following [these instructions](https://developer.android.com/studio/debug/dev-options).

**Comment by 8Observer8** [comment]
I have used USB debugging already. `USB debugging` and `Install via USB` are enabled. USB debugging worked for a period of time. It tested USB debugging in Qt Creator IDE. But now it doesn't work. I tried to update drivers for USB. I tried to change USB ports. I tried to restart my laptop a few times. But it didn't help. I can only test on the emulator. But the emulator supports OpenGL ES 2.0 only. Godot 4 cannot to build for OpenGL ES 2.0. It builds for OpenGL ES 3.0. But I tested Godot 3 app with Redmi 4X. I think Godot 3 will work on Emulator because it supports OpenGL ES 2.0

**Comment by Alex2782** [comment]
Do you have any other USB cables? They may also be defective or damaged.

**Comment by 8Observer8** [comment]
Yes, I tried another cable. Charging works but my computer doesn't see the device.
```
>adb usb
error: no devices/emulators found
```

**Comment by joined72** [comment]
@8Observer8 I have just [fixed a bug](https://github.com/godotengine/godot/issues/86112#issuecomment-1896098062) that could be strict related to your, can you test the following .APK file and tell to me if works fine, please?

[GLES3_Test.apk](https://drive.google.com/file/d/1ke4UQG4zm3VFWZj6FRCJt3EVMsQYDjs3/view?usp=sharing)

**Comment by 8Observer8** [comment]
Yes, it works on Redmi 4X! Which version of Godot will not contain this bug?

**Comment by joined72** [comment]
> > When 4.2.2 will be released?
> 
> We don't have an ETA for releases, but note that no pull request has been opened yet to fix this issue (let alone have it merged in `master` and cherry-picked to the `4.2` branch).

I don't know how to open a **"pull request"**, it's my first time!

**Comment by Alex2782** [comment]
I will soon create a `Draft` Pull Request as soon as I have found a solution for the GL-Context problem. 
https://github.com/godotengine/godot/issues/86112#issuecomment-1898564926

So far we have tried 2D projects, we still need to test 3D projects with`spot light + shadow` https://github.com/godotengine/godot/issues/86112#issuecomment-1896098062

@joined72 if you have time:
https://github.com/godotengine/godot-demo-projects

**Note:** not all projects are optimized for OpenGL ES3. There are also Vulkan demos that do not work as they should on Android.

**Comment by joined72** [comment]
> @joined72 if you have time: https://github.com/godotengine/godot-demo-projects

I'm currently working on the "Wrong Rotation Bug" but I will try to do my best on this too.
