### ISSUE TITLE
Godot 4.2.1 - .APK installation size about 4X the .APK file size

### ISSUE THREAD

**Issue by joined72** [godotengine/godot#86571]
### Tested versions

Godot 4.2.1

### System information

Ubuntu 22.04 - AMD Ryzen 5 - Nvidia 750 Ti - 16 GB RAM - 512 SDD NVME - XFCE 4.18

### Issue description

The .APK Installation Size is about 4X the .APK file size.
Example: the attached MRP generate a release .APK file of about 20Mb that when installed takes up approximately 82Mb.

PS: I tested this on Godot 4.0.0 stable too, the issue was just presents. 

### Steps to reproduce

Simple use the attached MRP, export in Release mode, install it, and check its installation size form your Android Device from "Settings/App/APK_Install_SIze/Memory".

### Minimal reproduction project (MRP)

[APK_Install_Size.zip](https://github.com/godotengine/godot/files/13785065/APK_Install_Size.zip)

**Comment by rsubtil** [comment]
APK files are compressed ZIP archives, so it's normal to have size differences when installed on the device. Godot itself also has a ~30MB download size and ~110MB install size on my device. Unzipping it also shows a 3x difference in size:
![image](https://github.com/godotengine/godot/assets/6501975/655efcc0-a8b8-4462-8fb9-5626cd120d55)
If this size is too much, you can try to compile the engine with size optimizations: https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html

**Comment by rsubtil** [comment]
>  isn't soo, on Godot 3 the APK size and the Installation Size, ARE THE SAME! ;)

Godot 3 editor also takes ~26MB to download, and takes ~84MB when installed. In your MRP, these are the results I had:

- 4.x: 20.06MB APK size -> 82.6MB installed (x4.11)
- 3.x: 12.38MB APK size -> 45.97MB installed (x3.71)

Godot 3 ends up being slightly smaller, but still noticeably larger than the APK file.

**Comment by joined72** [comment]
> > isn't soo, on Godot 3 the APK size and the Installation Size, ARE THE SAME! ;)
> 
> Godot 3 editor also takes ~26MB to download, and takes ~84MB when installed. In your MRP, these are the results I had:
> 
>     * 4.x: 20.06MB APK size -> 82.6MB installed (x4.11)
> 
>     * 3.x: 12.38MB APK size -> 45.97MB installed (x3.71)
> 
> 
> Godot 3 ends up being smaller, but still noticeably larger than the APK file.

OK, I understand.
