### ISSUE TITLE
Scrollable Dialogue fix request for Android smartphones

### ISSUE THREAD

**Issue by orbiterFan** [godotengine/godot#86572]
### Tested versions

Android smartphone with res 2312 x 1080
Godot 4.1 and 4.2 for Android
Zylanns heightmap-terrain-plugin 1.7.2

### System information

Android smartphone - res 2312 x 1080

### Issue description

Hi Guys

I have been looking for a wyziwyg 3d level editor for Android, and finally fired up Godot for Android. Still getting a handle on Godot, and I appreciate the clean logic. Not as menu heavy as Unreal, and still has a tiny footprint once installed.

My typical use case is to thrash out 3d ideas on my phone without a laptop or PC.

I installed Zylanns plugin on my android setup, and there are two issues.

1) the generate terrain dialogue overflows the screen, so I can't get to the "apply" button. Will copy Zylann in on this.

2) When sculpting terrain on an android phone, the terrain stays flat without changes, no matter which sculpt tool I use.

See screenshot of terrain generation dialogue.
![Screenshot_godotengine editor v4](https://github.com/godotengine/godot/assets/110048434/985c6bbb-9e07-41fe-b633-15fd1018f281)

Hoping you can help. Season's greetings.

### Steps to reproduce

Use a android smartphone with screen res of 2312 x 1080
Install Godot android 4.1 or 4.2
Install Zylanns heightmap terrain plugin 1.7.2
Follow Kasper tut on YouTube -> https://www.youtube.com/watch?v=Af1f2JPvSIs
Try sculpt the terrain
Nothing happens to the terrain
Then
Try Generate terrain
Apply/cancel buttons hidden off screen

### Minimal reproduction project (MRP)

Too big to upload

**Comment by Calinou** [comment]
This is an issue with the plugin which should implement scrolling in its popup, not the editor.

**Comment by orbiterFan** [comment]
Thank you for your help
