### ISSUE TITLE
Popup's can't have transparent background anymore.

### ISSUE THREAD

**Issue by azagaya** [godotengine/godot#86580]
### Tested versions

Reproducible in 4.2.stable

### System information

Windows 11 and Ubuntu 23.04 Godot 4.2 stable, Vulkan Forward +

### Issue description

When using a stylebox (either texture, empty or flat) that does not cover the entire rect, the back of the popup will use the clear color instead of being transparent, which causes unpleasant results. This was working ok in 3.x.

This image is an example of an option button, whose popup panel has a style of a rounded flat box.

![image](https://github.com/godotengine/godot/assets/46932830/2b54c54b-e11e-4992-ae1f-8eec2f18daac)

### Steps to reproduce

1- Create option button
2- Add a StyleBoxFlat to the "panel" in the PopupMenu theme.
3- Round the corners of that StyleBox
4- Add items to the option button
5- Run the game and test the option button

### Minimal reproduction project (MRP)

[ThemeIssues.zip](https://github.com/godotengine/godot/files/13787688/ThemeIssues.zip)

**Comment by AThousandShips** [comment]
Have you set `transparent` true on the `Popup`?

**Comment by azagaya** [comment]
@AThousandShips hey, no i haven't. How do i set transparent to true in the popup of an optionbutton?

**Comment by AThousandShips** [comment]
You get the popup with `get_popup`

**Comment by azagaya** [comment]
@AThousandShips so if i want to use a theme that has a style like this, i need to also add a script that does this? I only want to have themes and be able to change them.

**Comment by azagaya** [comment]
Adding a script that sets `transparent_bg` to the popup returned by `get_popup` works. However this is a bit unusable for theming, as you would have to do this on everything that has a popup.

**Comment by AThousandShips** [comment]
(please don't tag me, it's just us here, I don't need the additional notifications)

This is a limitation, transparent backgrounds are expensive and it's not possible to just detect this easily, so it's something you need to do manually

If you want to change this you need to open a [proposal](https://github.com/godotengine/godot-proposals) as this isn't a bug, assuming it works with the correct fix

**Comment by azagaya** [comment]
Ok, sorry for the tag. I'll look into writing a proposal.

**Comment by AThousandShips** [comment]
Closing as per the above 🙂

**Comment by kleonc** [comment]
@azagaya See #76071, https://github.com/godotengine/godot/pull/81669#issuecomment-1757213606. For a potential workaround idea see https://github.com/godotengine/godot/issues/76071#issuecomment-1720189749 (you'd need to tweak it to your needs).
