### ISSUE TITLE
[Documentation] VisibilityNotifier2D signals out of date

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8659]
Docs:

http://docs.godotengine.org/en/stable/classes/class_visibilitynotifier2d.html

In-editor signals:

![selection_092](https://cloud.githubusercontent.com/assets/7429786/25760982/25059c4a-31a7-11e7-9ca8-80162e46410e.png)

**Comment by JarLowrey** [comment]
Wait no they're fine, idk what I was thinking lol

**Comment by akien-mga** [comment]
And as you were asked on your other issue, documentation issues should be opened on the https://github.com/godotengine/godot-docs repository :)
