### ISSUE TITLE
Is theres a way to split render queue for objects via shader????

### ISSUE THREAD

**Issue by lopkauna** [godotengine/godot#86595]
### Tested versions

4.2 steam

### System information

windows 11

### Issue description

I cant find single instance shader method. How i can use shader for 1 node specifically and not like this
![Снимок экрана 2023-12-29 053827](https://github.com/godotengine/godot/assets/126475600/a29a99b9-7d69-4565-90b9-e826efd3da9b)

### Steps to reproduce

just add 2 mesh instances and apply shader with that code for 1 of them

### Minimal reproduction project (MRP)

```
shader_type spatial;
render_mode unshaded;

uniform sampler2D SCREEN_TEXTURE : hint_screen_texture;
uniform vec4 outline_color : source_color;
uniform float outline_width = 1.0;

void fragment() {
	vec4 pixelatedtext = texture(SCREEN_TEXTURE, SCREEN_UV);
	vec2 pixel_size = 1.0 / VIEWPORT_SIZE;
	ALBEDO = pixelatedtext.rgb;
	for(int y = -1*int(outline_width); y <= 1*int(outline_width); y++)
	for(int x = -1*int(outline_width); x <= 1*int(outline_width); x++)
	{
		vec4 tex = texture(SCREEN_TEXTURE, SCREEN_UV + vec2(float(x),float(y)) * pixel_size );
		if(tex.a == 0.0)
		{
			ALBEDO = outline_color.rgb;
			ALPHA = 1.0;
		}
	}
	
}
```

**Comment by Calinou** [comment]
This is not currently supported in Godot, as it currently doesn't have stencil buffer support or a similar render layer system.

Closing in favor of https://github.com/godotengine/godot-proposals/issues/7174 and https://github.com/godotengine/godot-proposals/issues/7916.

**Comment by lopkauna** [comment]
sadge
