### ISSUE TITLE
Variable not properly increase a value in an while inside another while - GDscript - Godot 4.2.1

### ISSUE THREAD

**Issue by LeandroHPerez** [godotengine/godot#86593]
### Tested versions

Godot 4.2.1 regular (without .net) for MacOS 

### System information

Macbook Apple M2 Pro - MacOs  Sonoma 14.2.1

### Issue description

I believe I found a bug with Gdscript in this situation where there is a while inside another while. Index values ​​must range from -100 to 100. The line ix += 1 does not work in this context and is eternally stuck at -100 or -99

### Steps to reproduce

Steps:
1 -In any new scene add an Node2d with gdscript code:

```GDScript
extends Node2D


enum EnumTileTypeTest {
	tile_test1,
	tile_test2
}

# Called when the node enters the scene tree for the first time.
func _ready():
	var dic:= bug_with_inner_while(EnumTileTypeTest.tile_test1)
	print("ix value is -100 forever or -99")



# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass


func bug_with_inner_while(what_type_of_dic_value: EnumTileTypeTest) -> Dictionary:
	print("bug_with_inner_while")
	var tile_type:= what_type_of_dic_value
	var result_dic: Dictionary
	
	var ix: int = -100 #(minus 100)
	var jy: int = -100 #(minus 100)
	while ix < 100:
		ix = ix + 1 #this increase value not work - last -99 forever
		while jy < 100:
			result_dic[Vector2i(ix, jy)] = what_type_of_dic_value
			print("ix: " + str(ix) + ", jy: " + str(jy))
			jy += 1
		#ix += 1 #line commented - this increase value not work - here too -last -100 forever
	
	return result_dic
````

2- Run code and see that ix doesn't update, stucks forever in -99 or -100.

3- If de line is uncommented:
#ix += 1 #line commented - this increase value not work - here too -last -100 forever

And this line comment:
ix = ix + 1 #this increase value not work - last -99 forever

### Minimal reproduction project (MRP)

Yes, here:
[bug_while 2.zip](https://github.com/godotengine/godot/files/13789970/bug_while.2.zip)

**Comment by KoBeWi** [comment]
Your inner loop enters only once, because you never reset `jy`.
Try print `ix` before second while:
```GDScript
while ix < 100:
	ix = ix + 1 #this increase value not work - last -99 forever
	prints("ix", ix)
```
