### ISSUE TITLE
await destroys match

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#86606]
### Tested versions

v4.2.stable.official [46dc27791]

![match](https://github.com/godotengine/godot/assets/77213594/0dde7662-4c3f-4006-9d6c-eb3174ccb479)

### System information

windows 10 vulkan

### Issue description

using: await get_tree().create_timer(0.5).timeout
on a match ( switch ) alters to previous state, when pressing a key.

### Steps to reproduce

Use   "match", "await get_tree().create_timer", and "Input.is_action_just_pressed" togheter

### Minimal reproduction project (MRP)

[awaitDestroysMatch.zip](https://github.com/godotengine/godot/files/13793753/awaitDestroysMatch.zip)

**Comment by KoBeWi** [comment]
When you are awaiting in `_process()`, it will delay execution only of a single `_process()` call. The method will be called again in the next frame. What happens in your case is that pressing Up moves to the next state, but the previous awaiting call is executed afterwards "rewinding" the state.

Closing, as there is no engine bug here.
