### ISSUE TITLE
Glow covering screen on Android with single color

### ISSUE THREAD

**Issue by warent** [godotengine/godot#86621]
### Tested versions

This happens on 4.1, 4.2, and 4.3 (dev snapshot 1)

### System information

Godot v4.3.dev1 - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 Ti (NVIDIA; 30.0.15.1216) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Hey folks, I've been having an issue with my game not rendering any 3D viewport / display on Android 13 (Pixel 6 Pro), only 2D Canvases are showing (But not SubViewports).

Attached is a (low resolution) screenshot of the game on Windows showing the game correctly, and then on Android showing a blank color. When the camera moves in Android, the view behind the canvas flickers colors a lot. It seems like the entire view is just a single pixel of light/color. Meanwhile SubViewport in the top-left corner is not rendering anything. 

This seems like a bug, but I'm at a loss for troubleshooting steps.

![Screenshot_2023-12-28_161021](https://github.com/godotengine/godot/assets/13342266/5b0cf7ce-8596-450b-ba08-4fb02ffa04aa)
![Screenshot_20231228-161000](https://github.com/godotengine/godot/assets/13342266/73fa553f-49af-40b0-bfce-20a2700b470a)

![Screenshot_2023-12-28_163004](https://github.com/godotengine/godot/assets/13342266/0f4508aa-2401-4d6a-8a31-09096d42fa68)
![image](https://github.com/godotengine/godot/assets/13342266/d564dd48-2a04-48f9-add3-75c012808485)

### Steps to reproduce

Enable Glow

### Minimal reproduction project (MRP)

Thanks @etherealxx for creating an MRP
https://github.com/godotengine/godot/issues/86621#issuecomment-1885268576

**Comment by Alex2782** [comment]
Could you create **"Minimal reproduction project"?** 
Then I could compare on my Pixel 4a and maybe debug with Android Studio.

**Comment by clayjohn** [comment]
I think this is caused by glow on certain devices (pixel 7 reproduces, but pixel 4 doesn't).

**Comment by warent** [comment]
> I think this is caused by glow on certain devices (pixel 7 reproduces, but pixel 4 doesn't).

Thank you, it was the glow. Let me know if I should close this issue or if you want to track/merge it somewhere else

**Comment by clayjohn** [comment]
I don't think the issue has been reported elsewhere, so let's leave this open

**Comment by Janblu** [comment]
Can confirm that this issue appears on the Motorola Moto G14 (Android 13)

**Comment by etherealxx** [comment]
Confirmed on Pixel 7 with every rendering methods and this MRP: 
[godot4-3d-snapdragon-bug.zip](https://github.com/godotengine/godot/files/13890865/godot4-3d-snapdragon-bug.zip)

**Comment by warent** [comment]
> Confirmed on Pixel 7 with every rendering methods and this MRP: [godot4-3d-snapdragon-bug.zip](https://github.com/godotengine/godot/files/13890865/godot4-3d-snapdragon-bug.zip)
> 
> Also happening on Godot Android editor when running the scene.
> 
> **System Information:** Godot v4.2.1.stable - Android - Vulkan (Mobile) - integrated Mali-G710 - (8 Threads)

I updated the main post with your MRP, thank you

**Comment by MitchMakesThings** [comment]
Another confirmation for Pixel 6 (Exported from v4.2.1.stable.mono.official [b09f793f5])
Switching to compatibility renderer works with Glow enabled.
Mobile renderer just gives the blank screen with the default world colour (And UI drawn on top) when Glow is enabled.

Disabling glow makes everything work as expected.

**Comment by KeiMuriKoe** [comment]
Can confirm, on Google Pixel 7 Pro also cause invisible 3D, with Glow - True, in worldInviroment

**Comment by 0xnicholasc** [comment]
I can confirm that this is also impacting Pixel 8; when glow is enabled, the entire 3D scene is replaced by the color of whatever pixel is in 0,0.

**Comment by kuruk-mm** [comment]
Same it is happening to me

Device:
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.219 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G68

Data to add to the issue:
- If you change the Rendering Scale 3D to something different to 1.0, you have the same issue that is reported here (single colour on the screen)
- Looks like the hardware that has the following issue: https://github.com/godotengine/godot/issues/86707 doesn't have this issue (even for Rendering Scale 3D != 1.0)

**Comment by Alex2782** [comment]
> added to [Rendering Issue Triage](https://github.com/orgs/godotengine/projects/78) 2 weeks ago: Priority = High

Is anyone already checking the issue? I might have some time in the next few weeks. No guarantee of success.


-----------------

Only on Mali-GXXx GPUs **and** Vulkan API **1.3.xxx** ?

<details><summary>My Tests (almost all on Firebase Test Lab)</summary>

---------------------

**my MRP** (with less nodes):  [GlowTest.zip](https://github.com/user-attachments/files/15523757/GlowTest.zip)
I have also tried 'libVkLayer_khronos_validation' no warnings about this.

https://github.com/godotengine/godot/assets/41921395/e81eb418-7b73-4a47-9a40-954a91bdb384



-----------------

### BUG

**Pixel 8 (BUG)**
Vulkan 1.3.231 - Forward Mobile - Using Device #0: ARM - Mali-G715

**Pixel 7a (BUG)**
Vulkan 1.3.260 - Forward Mobile - Using Device #0: ARM - Mali-G710

**Galaxy A54 5G (BUG)**
Vulkan 1.3.219 - Forward Mobile - Using Device #0: ARM - Mali-G68

------------

### OK

**Pixel 6 (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Device #0: ARM - Mali-G78

**Pixel 4a (OK)**
Vulkan 1.1.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 618

**Galaxy S23 Ultra (OK)**
Vulkan 1.3.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 740

**Samsung Tab A 10.1 (OK)**
Vulkan 1.0.61 - Forward Mobile - Using Device #0: ARM - Mali-T830

**realme GT NEO 3 150W (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G610 MC6

**Galaxy A51 (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Device #0: ARM - Mali-G72

**OnePlus Nord2 5G (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G77 MC9

**Motorola G20 (OK)**
Vulkan 1.1.131 - Forward Mobile - Using Device #0: ARM - Mali-G52
</details>

**Comment by Alex2782** [comment]
- `blur_1` texture issue:  `create_texture(RB_SCOPE_BUFFERS, RB_TEX_BLUR_1, ...`
- **Camera3D -> depth of field** also uses the `blur_1` texture _(reproducible)_

<details><summary>screenshot</summary>

![image](https://github.com/godotengine/godot/assets/41921395/9203ebd8-a374-4f6f-aabe-936d13e6f316)



</details>



**new MRP:** [GlowTest.zip](https://github.com/user-attachments/files/15569761/GlowTest.zip)

<details><summary>Test on Firebase</summary>


https://github.com/godotengine/godot/assets/41921395/99b6f508-315a-4219-b359-0d465100021a




</details>

--------------------

I can also reproduce similar issue if `rendering/scaling_3d/scale` **!= 1.0**
<details><summary>screenshot</summary>

![image](https://github.com/godotengine/godot/assets/41921395/25b4c8f3-a424-4ab9-898a-0d13fc114ce5)

</details>

**Comment by akien-mga** [comment]
I confirm the issue on Pixel 7a too. It breaks the Android editor for 3D projects as the whole 3D viewport is grey.
Disabling glow in the default preview environment, or disabling the preview environment, works it around.

I would argue we should disable glow in the default preview environment for `mobile` until this is fixed.

I'll try to test #92817 and see if it solves it for Pixel 7a too.

**Comment by Alex2782** [comment]
> I would argue we should disable glow in the default preview environment for mobile until this is fixed.

Only on `Mali-GXXx GPU`s **and** `Vulkan API 1.3.xxx`

`MitchMakesThings` says:
> Another confirmation for Pixel 6
https://github.com/godotengine/godot/issues/86621#issuecomment-1885709553

But `Pixel 6` with `Vulkan 1.1.177` has no problems. 

<details><summary>My Tests (almost all on Firebase Test Lab)</summary>

---------------------


### BUG

**Pixel 8 (BUG)**
Vulkan 1.3.231 - Forward Mobile - Using Device #0: ARM - Mali-G715

**Pixel 7a (BUG)**
Vulkan 1.3.260 - Forward Mobile - Using Device #0: ARM - Mali-G710

**Galaxy A54 5G (BUG)**
Vulkan 1.3.219 - Forward Mobile - Using Device #0: ARM - Mali-G68

------------

### OK

**Pixel 6 (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Device #0: ARM - Mali-G78

**Pixel 4a (OK)**
Vulkan 1.1.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 618

**Galaxy S23 Ultra (OK)**
Vulkan 1.3.128 - Forward Mobile - Using Device #0: Qualcomm - Adreno (TM) 740

**Samsung Tab A 10.1 (OK)**
Vulkan 1.0.61 - Forward Mobile - Using Device #0: ARM - Mali-T830

**realme GT NEO 3 150W (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G610 MC6

**Galaxy A51 (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Device #0: ARM - Mali-G72

**OnePlus Nord2 5G (OK)**
Vulkan 1.1.177 - Forward Mobile - Using Vulkan Device #0: ARM - Mali-G77 MC9

**Motorola G20 (OK)**
Vulkan 1.1.131 - Forward Mobile - Using Device #0: ARM - Mali-G52
</details>
