### ISSUE TITLE
Godot_mono binary on macOS isn't possible to link in homebrew because of dependence on relative file paths

### ISSUE THREAD

**Issue by dannflor** [godotengine/godot#86625]
### Tested versions

4.2-mono

### System information

macOS 14.2

### Issue description

I noticed an asymmetry between the `godot` and `godot-mono` casks on homebrew, so I added the link to `godot-mono`'s binary to allow the user to invoke it from the command line in https://github.com/Homebrew/homebrew-cask/pull/163355. This hits a snag when you actually try to run the binary from the command-line, it fails with: `•NET assemblies not found. Unable to find the NET assemblies directory. Make sure the opt/homebrew/bin/GodotSharp/Api/Debug' directory exists and contains the NET assemblies.`. This is because the binary is looking for `GodotSharp` using a relative path, expecting to be executed from within the app bundle. I raised the issue [here](https://github.com/orgs/Homebrew/discussions/5012) wondering how I could make the link execute with the correct working directory, and I was told that it isn't acceptable for the calling location to be assumed and the fix needed to happen upstream. I assume one could put the .NET assemblies in some shared system directory, but that would run against the much-lauded portability/lack of an installer with Godot. I am hoping there is some other option to allow us to run `godot-mono` from the command line in a homebrew cask like we are currently able to with `godot`.

### Steps to reproduce

`brew install godot-mono`
`godot-mono project.godot`

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
> so I added the link to godot-mono's binary to allow the user to invoke it from the command line in

It's not a bug, there's absolutely no reason for the bundled app to look for resources anywhere except `[[NSBundle mainBundle] resourcePath]` (it can be relocated, and multiple versions can co-exist, so nothing outside the bundle should be directly referenced). Also, Godot is not intended to be used as a standalone executable, and you should not symlink part of the bundle. Instead, use a wrapper script (see what Blender or VS Codium casks do).

https://github.com/Homebrew/homebrew-cask/blob/e867f38d8e8a51c139fab025196a7ff84970e639/Casks/b/blender.rb#L22-L34

**Comment by dannflor** [comment]
Thanks for pointing me in the right direction!
