### ISSUE TITLE
Upgrading from 3 to 4 changes functions to invalid functions

### ISSUE THREAD

**Issue by Sean-Brown** [godotengine/godot#86646]
### Tested versions

Reproducible when upgrading from 3.5 to 4.2 (and possibly other versions, I was only upgrading from 3.5 to 4.2).

### System information

Windows 10, Godot 4.2

### Issue description

Upgrading the project with the `--convert-3to4` flag changes functions to invalid functions. For example, the SpriteFrame's `AddAnimation` method was supposedly updated to `AddAnimationLibrary`, however this results in a compile error saying:
> 'SpriteFrames' does not contain a definition for 'AddAnimationLibrary' and no accessible extension method 'AddAnimationLibrary' accepting a first argument of type 'SpriteFrames' could be found (are you missing a using directive or an assembly reference?)

When I look in the assembly for SpriteFrames (Assembly GodotSharp, Version=4.2.0.0), I see that it contains a definition for `AddAnimation` but not `AddAnimationLibrary`. There are several other upgraded methods that result in this same error.

Am I missing something? This [cheat sheet](https://godot-3to4.vercel.app/) seems to indicate that the upgrade was supposed to change that method to `AddAnimationLibrary`, but why does the assembly define the old method name and not the new one?

**URL to the documentation page:**
https://docs.godotengine.org/en/4.0/tutorials/migrating/upgrading_to_godot_4.html

### Steps to reproduce

Have a Godot 3.5 project and upgrade to 4.2

### Minimal reproduction project (MRP)

This is more a general question. The project in question is private, and I suspect this applies to any project upgrading from 3 to 4.

**Comment by AThousandShips** [comment]
This is because of a too general change, will remove the rename as it isn't valid anyway

**Comment by Sean-Brown** [comment]
Thanks, and while you're at it, these other ones are broken as well by the upgrade:
- TextureRect.Texture --> TextureRect.Texture2D
- System.IO.Path --> System.IO.Path3D
- System.IO.Directory --> System.IO.DirAccess

**Comment by AThousandShips** [comment]
I'll keep this one simple, it's complicated and would need to be investigated separately, please note these in this issue:
* https://github.com/godotengine/godot/issues/73960
