### ISSUE TITLE
Massive lag and OpenGL error spam on Windows with Intel graphics

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#8665]
**Operating system or device - Godot version:**
Device: Wacom Cintiq Companion 2
OS Name: Microsoft Windows 10 Pro
Version: 10.0.15063 Build 15063
System Type: x64-based PC
Processor: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz, 3101 Mhz, 2 Core(s), 4 Processors.

Graphics Render:
Renderer: Intel(R) Iris(TM) Graphics6100
Adapter RAM: 1024 MB

OpenGL Version: 4.4 / Driver version: 20.19.15.4531 29-Sep-16
DirectX Version: DirectX 9, 11.0 / Shader model vs_5_0, ps_5_0

Engine Used: **_GODOT Engine 3.0 Alpha_**

**Issue description:**
I wanted to try out the Alpha to see what new features are included, and I am aware that this engine is unstable. However, when I try to open up the engine it immediately starts to lag. This lag happens in both the viewport and any button hovered over by the mouse arrow, and the reason why this engine lags a lot is because of one error that keeps repeating in the Debug Window:

`ERROR: _gl_debug_print: GL ERROR: Source: OpenGL
	Type: Error     
	ID: 1282        
	Severity: High  
	Message: Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error
		At: drivers/gles3/rasterizer_gles3.cpp:123`

**Steps to reproduce:**
Not sure if anybody is suffering the same effect after starting up the engine but clicking and opening the engine editor is the only step required to reproduce the effect mentioned above. Hope somebody might offer opinions and answers to what is causing this to happen.

**Comment by Calinou** [comment]
This is mostly Windows-specific, and I can reproduce this on an Intel HD Graphics 620 (on an i7-7500U).

**Comment by Ahmed0425** [comment]
Duplicated many times #8489
see the 4th comment
and is being fixed #8622

**Comment by Corruptinator** [comment]
Bugs will be bugs, finding all of the annoying ones and squashing them all.  :)

**Comment by TheRadMatt** [comment]
I had the same problem and changing to not integrated GPU fixed the issue in my case (from HD Graphics 530 to Nvidia GF 950).

**Comment by Corruptinator** [comment]
How is this bug coming along?

**Comment by Corruptinator** [comment]
I can confirm that the patch has fixed this bug. Thanks for the fix! Time to enjoy what 3.0 is going to have!
*Messes around with 3D PBR*
