### ISSUE TITLE
ParallaxLayers do not follow Camera2D rotation

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#86656]
### Tested versions

4.3.dev [13a0d6e9b2]

### System information

Windows 10

### Issue description

`ParallaxLayer` is a special case because it follows the current camera even though it's in a separate `CanvasLayer` and `follow_viewport` is not enabled. However, when the current camera is rotated, each `ParallaxLayer` stays level with the camera.

### Steps to reproduce

Add a `ParallaxBackground`, `ParallaxLayer` and `Sprite2D` with any image to an empty scene.
Add a `Sprite2D` and image outside of the `ParallaxBackground`.
Add a `Camera2D` and run the scene.
Rotate the `Camera2D`.

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
I believe, that this is a duplicate of #30988. Can you please confirm this?

**Comment by markdibarry** [comment]
Yep! I'm not sure why it didn't show up when I searched the issues, but I'm also surprised to see it's such an old bug for how easy it is to reproduce! Closing. Thanks!
