### ISSUE TITLE
Multiple inputs are being ignored.

### ISSUE THREAD

**Issue by ImFlavo** [godotengine/godot#8666]
**Operating system or device - Godot version:**
Windows 10, godot version 2.1.2 issue presists in 3.0

**Issue description:**
I setup a basic input function with arrow keys. pressing LEFT, RIGHT, and DOWN, each input was acknowledged. however when i did LEFT, RIGHT, and UP, UP was ignored. i then tested by holding down some letter keys: G, H and L, and all arrow key inputs were ignored

**Steps to reproduce:**
```
func _process(delta):
	if Input.is_key_pressed(KEY_UP) && Input.is_key_pressed(KEY_LEFT) && Input.is_key_pressed(KEY_UP):
		print("this wont appear")
```

alternative:
```
func _input(event):
	if event.type == InputEvent.KEY && !event.is_echo():
		for v in buttons:
			if event.scancode == v:
				if event.is_pressed():
					emit_signal(str(buttons[v],"_key_pressed"))
				else:
					emit_signal(str(buttons[v],"_key_unpressed"))
				get_tree().set_input_as_handled()
```

**Comment by eon-s** [comment]
Can you test if your hardware can handle multiple presses? (keyboards are physically limited and there may be other factors too)

Here is a nice post about keyboard ghosting and a simple program to test it https://www.microsoft.com/appliedsciences/antighostingexplained.mspx

**Comment by ImFlavo** [comment]
This appears to be the issue then, thanks.

**Comment by reduz** [comment]
Hehe I think issues like this appeares a couple times already
