### ISSUE TITLE
Certain UI elements not showing in 2d editor

### ISSUE THREAD

**Issue by Odyssey8416** [godotengine/godot#86660]
### Tested versions

 Bug exists:
4.2.1-stable, 4.2-stable, 4.1.3-stable, 4.1.2-stable, 4.1.1-stable, 4.1-stable, 4.0.4-stable, 4.0.3-stable, 4.0.2-stable, 4.0.1-stable, 4.0-stable
Bug does not exist:
3.5.3-stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4617) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

When a popup node is selected, the bounding box is not displayed, as well as any other children of the popup node
They are also not directly editable except through the inspector
However when you remove the child from the parent object (popup), it works fine

### Steps to reproduce

Create a new UI scene
![image](https://github.com/godotengine/godot/assets/154958701/00ae8164-d46f-41ae-9e7d-6f9f2d3271e6)
It will look like this, and you can drag the edges
![image](https://github.com/godotengine/godot/assets/154958701/28aa6a5b-6d4d-4c70-ab56-9a6f1752e91d)
Add a popup node
![image](https://github.com/godotengine/godot/assets/154958701/1eac26ae-b4d7-41b3-9ba8-8963e4bb1187)
The popup node will not be interactable
![image](https://github.com/godotengine/godot/assets/154958701/04f12f0d-ce45-472e-928a-a6614719375f)
Any children also created are not interactable

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment]
Popups are not Control nodes and they aren't editable outside the inspector. Not being able to move children is a known issue (#20619). I remember there was a proposal to make Window nodes editable in the editor, but I can't find it 🤔

**Comment by Odyssey8416** [comment]
I understand if it isn't intended behavior, but in 3.5.3 you can edit popups within the editor or the inspector

**Comment by KoBeWi** [comment]
Because popups were Controls before, but they were changed for multiple windows support.

**Comment by Odyssey8416** [comment]
Got it, thank you, I'll find another way to do what I want
