### ISSUE TITLE
Is that PCKPacker already DEPRECATED ? PCK packed by PCKPacker can't load correctly.

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#86674]
### Tested versions

4.2-table

### System information

Windows11 - Godot 4.2-stable - vulkan

### Issue description

I'm looking for a way to handle the PCK export my self. I have a requirement to implement a fine-grained dynamic resource loading scheme similar to Unity Assetbundle. I know that exporting presets can export PCK, but I still need to control the granularity of the exported resources myself. 

So I found PCKPacker and try to use it to pack a resource in to PCK file.  

But I fail. ProjectSetting.load_resource_pack can't load PCK pack by PCKPacker.

It seemes that a good PCK which ProjectSetting.load_resource_pack can load it must have .godot .import .remap project.binary something dependency else. But PCKPacker only pack file into , it doesn't deal with dependency.

Then I research source code of Godot Engine.  Nobody use PCKPacker, even the EditorExportPlatform::export_pck. No reference. Document say it can use to pack PCK directly and load it, no example code. 

So is PCKPacker already DEPRECATED? 

Or I should just copy  implement of EditorExportPlatform::export_pck to reimplement GDScript version of PCK pack pipline to make my PCKPacker works?

For now I don't understand the what is PCKPacker used for. 

### Steps to reproduce

step1: I create this project for test
you can download it at attachment.
![image](https://github.com/godotengine/godot/assets/1620585/30d84603-d53e-4a1d-ad9c-af29d4ba63c1)

I create a launcher scene with 2 button and 1 texture rect.
![image](https://github.com/godotengine/godot/assets/1620585/1f43d305-dc5b-42fd-b892-268a4c917c51)
Don't Load button try to load res://tile.png without load PCK.
Load PCK button try to load PCK before load res://tile.png.

![image](https://github.com/godotengine/godot/assets/1620585/72ce57d8-54b1-49c7-a61f-f0d93d50bac3)
Export  preset setup launcher preset and tile.pck preset. luancher preset only export game.exe and game.pck which only contains Launcher.tscn  and launcher.gd.
 
![image](https://github.com/godotengine/godot/assets/1620585/328032bf-2d89-4589-800d-965583c30a7e)
Use godotpcktool , you can see title.png not conatains.

![image](https://github.com/godotengine/godot/assets/1620585/ebea4312-7c8e-4391-b8be-db327bfce9d3)
I make a only pck preset to export tile.png to tile.pck.

![image](https://github.com/godotengine/godot/assets/1620585/8212faaf-a910-4dc1-97f6-9236e9cfb46d)

Step2: Export all and  test it
![image](https://github.com/godotengine/godot/assets/1620585/d75ff823-c9d4-485d-8f38-bb067f616367)
![image](https://github.com/godotengine/godot/assets/1620585/3e8d562a-5ab3-4120-98db-223d7d5d2d89)

![image](https://github.com/godotengine/godot/assets/1620585/325b2f41-afc9-4ad5-bb40-46eb6502b36b)
![image](https://github.com/godotengine/godot/assets/1620585/748ea3e2-6575-42f5-89c4-a9419641564c)
It works fine.

Step3: Let's try pack tile PCK by PCKPaker
![image](https://github.com/godotengine/godot/assets/1620585/61b21642-73f6-4bb0-a531-75e2967f8fa8)
I make this EditorScript to pack tile.png into tile.pck. Run it.

![image](https://github.com/godotengine/godot/assets/1620585/157a2d32-a040-4c10-8385-5ca8558a9f93)

![image](https://github.com/godotengine/godot/assets/1620585/7e5f3097-792a-4700-ae62-685d64fa46b8)

### Minimal reproduction project (MRP)

[launcher.zip](https://github.com/godotengine/godot/files/13803752/launcher.zip)

**Comment by AThousandShips** [comment]
Not a bug, you can't load a resource if it's not imported, see [here](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#description) and [here](https://docs.godotengine.org/en/stable/tutorials/io/runtime_file_loading_and_saving.html#images)

**Comment by kaluluosi** [comment]
> Not a bug, you can't load a resource if it's not imported, see [here](https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#description) and [here](https://docs.godotengine.org/en/stable/tutorials/io/runtime_file_loading_and_saving.html#images)

The tile.png has indeed been imported. But the PCK file packed by PCKPacker doesn't contains tile.png's import file.
My question is PCKPacker doesn't pack a usable PCK file. Why it existed?

Look at `EditorExportPlatform::save_pack`. It reimplement a `PCKPaker` himself rather than use PCKPacker.
 
![image](https://github.com/godotengine/godot/assets/1620585/fd9d79ad-8762-4081-8b84-88babc24c63d)

**Comment by AThousandShips** [comment]
Yes it just contains the files you add, not the imported data, it can't because it's useable without all the editor things, this isn't done automatically

**Comment by kaluluosi** [comment]
> Yes it just contains the files you add, not the imported data, it can't because it's useable without all the editor things, this isn't done automatically
> 
> Try to open it with the methods I've linked to and see 

So If I want my PCK works, I should do like what EditorExportPlatform::save_pack do. 🤔To pack the meta files relatived to the resource all into PCK, keep the minimum file system mapping inside ? OK，I get it. 🤣It seems that PCKPacker not as what it call.

One more thing. Is there any document that explans the file system and PCK packaging of Godot? 

Thank 😁👍

**Comment by kaluluosi** [comment]
> Yes it just contains the files you add, not the imported data, it can't because it's useable without all the editor things, this isn't done automatically
> 
> The packer works just fine, it just doesn't do things automatically that it doesn't list it will do, this isn't how it's supposed to work 🙂
> 
> Try to open it with the methods I've linked to and see

I doing some research about how to make godot custom `export_pck`.  Because if my project has hundreds or thousands resource. Then my leader wants that the client just contains a luancher tscn, player download and load the rest PCK. There is too many resource ,event I pack by folder, I should define dozens PCK presets. If platforms are Windows, Android and IOS,  there is hundreds presets to define. It's  terrible.

It seems for now Godot can't handle it. And the PCK Patches, still a long way off.

**Comment by AThousandShips** [comment]
> It seems that PCKPacker not as what it call.

It is though? It's an object that packs PCK files, it isn't an export tool, it works just fine for what it's designed to do, it's not what the documentation says it does either, so this is just some confusion about what you expect it to do

Nowhere does it say that it handles these things for you, so there's no reason to expect that 🙂

This is a workflow thing, not a bug or a missing feature

For more information see [here](https://docs.godotengine.org/en/stable/tutorials/export/exporting_pcks.html)

**Comment by daniel080400** [comment]
You don't pack the yourimage.png files, Godot can't read it in runtime, instead you pack the yourimage.import files, and also the imported [res_id].ctex inside the .godot/ directory, which is specified in the .import file. So godot can load this pck correctly in runtime, that's what Godot have done with its pck exports. And yes, you'll have to write your own editor plugin to automate this.

**Comment by Shou** [comment]
To add to daniel's comment above, specifically you can load the `*.import` files using `ConfigFile.load` and then `ConfigFile.get_value("deps", "dest_files")` for an array of paths, which you then add with `PCKPacker.add_file` by just plugging the respective path in both `add_file` arguments. I personally do this from a tool script/node running in the engine editor which removes the need for writing a full plugin. (note: I'm using Godot 3.6, adjustments may be necessary for 4.x)

**Comment by kaluluosi** [comment]
> To add to daniel's comment above, specifically you can load the `*.import` files using `ConfigFile.load` and then `ConfigFile.get_value("deps", "dest_files")` for an array of paths, which you then add with `PCKPacker.add_file` by just plugging the respective path in both `add_file` arguments. I personally do this from a tool script/node running in the engine editor which removes the need for writing a full plugin. (note: I'm using Godot 3.6, adjustments may be necessary for 4.x)

Thank you, I will try it in the future.
