### ISSUE TITLE
Instancing new tilemap + getting nodes from a group problem

### ISSUE THREAD

**Issue by Visssarion** [godotengine/godot#86675]
### Tested versions

version - 4.2.1.stable

### System information

Godot v4.2.1.stable (b09f793f5) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 750 (nvidia) - Intel(R) Pentium(R) CPU G4500 @ 3.50GHz (2 Threads)

### Issue description

Getting nodes in a group right after instancing new TileMap gives me no results

If you place ``get_tree().get_nodes_in_group("coconut_platform")`` in ``_process()``, it will correctly give me the array of nodes.
So when the check right after instancing a TileMap, the child scenes of TileMap haven't been spawned in yet

### Steps to reproduce

```gdscript
extends Node2D

#tilemap scene
var scene: PackedScene = preload("res://spawnable_node.tscn")

func _ready():
	var instance = scene.instantiate()
	add_child(instance)
	print(get_tree().get_nodes_in_group("test_group"))
	#shows nothing

func _process(delta):
	print(get_tree().get_nodes_in_group("test_group"))
	#shows 1 node
```

### Minimal reproduction project (MRP)

[GroupBug.zip](https://github.com/godotengine/godot/files/13802359/GroupBug.zip)

**Comment by Visssarion** [comment]
Adding a ``await RenderingServer.frame_post_draw`` before ``get_tree().get_nodes_in_group(...)`` works as a workaround

**Comment by KoBeWi** [comment]
TileMap scenes are not instantiated immediately.

**Comment by Mickeon** [comment]
And that needs to be documented _nicely_.

**Comment by AThousandShips** [comment]
It is documented:
> For performance reasons, all TileMap updates are batched at the end of a frame. Notably, this means that scene tiles from a TileSetScenesCollectionSource may be initialized after their parent.

**Comment by AThousandShips** [comment]
Since this is by design, well documented, and has a way to force the update there's nothing to be done here IMO, should be closed

**Comment by AdamLearns** [comment]
I agree that nothing needs to be changed in the code here, but I think [the `TileSetScenesCollectionSource` documentation](https://docs.godotengine.org/en/stable/classes/class_tilesetscenescollectionsource.html) can be clearer. Right now, it says this:

> Scenes are instantiated as children of the TileMap when it enters the tree. If you add/remove a scene tile in the TileMap that is already inside the tree, the TileMap will automatically instantiate/free the scene accordingly.

This seems to contradict [the `TileMapLayer` documentation](https://docs.godotengine.org/en/stable/classes/class_tilesetscenescollectionsource.html#description):

> scene tiles from a TileSetScenesCollectionSource may be initialized after their parent

For those who land on the documentation for `TileSetScenesCollectionSource`, it's easy to wonder why their scenes aren't instantiated.

**Comment by Mickeon** [comment]
> I agree that nothing needs to be changed in the code here, but I think [the `TileSetScenesCollectionSource` documentation](https://docs.godotengine.org/en/stable/classes/class_tilesetscenescollectionsource.html) can be clearer.

Check https://github.com/godotengine/godot/pull/108166

**Comment by AdamLearns** [comment]
> Check https://github.com/godotengine/godot/pull/108166

Oh, excellent! I'd added it to my own TODO list to update the documentation, so now I don't have to do anything. 😛

(thanks for sharing, and thanks @KoBeWi for handling this 🙏)
