### ISSUE TITLE
[Vulkan] Polygon2D will hide when renderable objects hide in scene tree.

### ISSUE THREAD

**Issue by saierXP** [godotengine/godot#86678]
### Tested versions

v4.3.dev1.official [9d1cbab1c], not in 4.2.1.

### System information

Godot v4.3.dev1 - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 30.0.13023.4001) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

![polygon](https://github.com/godotengine/godot/assets/45038185/867f6606-f4d6-45d4-8668-57e8c27c91ee)

When Polygon2D above the renderable object in scene tree,it doesn't happen.

![Godot_v4 3-dev1_win64_qwZexGlW0i](https://github.com/godotengine/godot/assets/45038185/f20956ae-be4c-4f80-9770-c01c564ca080)

If CollisionShape above Sprite2D, it's also not visible.
Then run the scene,when rigidbody exits screen, Polygon2D will show again.
### Steps to reproduce

Open the node_2d.tscn in the attached MRP below.
Change the renderable object visible property.

### Minimal reproduction project (MRP)

[polygon-hidden.zip](https://github.com/godotengine/godot/files/13803651/polygon-hidden.zip)

**Comment by Rudolph-B** [comment]
I was able to replicate the issue on https://github.com/godotengine/godot/commit/9d1cbab1c432b6f1d66ec939445bec68b6af519e. I then tested on https://github.com/godotengine/godot/commit/04eafd557faa5fbe8f7f2634810a0d2f24f99770. The bug is not present in the newer commit.

**Comment by saierXP** [comment]
Thank you.I've confirmed that I can't reproduce it in the latest version.
