### ISSUE TITLE
2d sprites going black or having other visual issues

### ISSUE THREAD

**Issue by Armynator** [godotengine/godot#86680]
### Tested versions

Introduced with [12a519b], last version without this issue is [daa8942f41] for me

### System information

Godot v4.3.dev.mono (13a0d6e9b) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i9-14900K (32 Threads)

### Issue description

Sprites are not behaving as expected. They can go completely black or use a wrong shader. It seems to be affected by ordering and/or parenting of the sprite nodes.

See video: https://www.youtube.com/watch?v=LjBuUqDFFJY

### Steps to reproduce

1. add sprites to scene
2. use custom shader(s)
3. notice sprite(s) going black or other visual artifacts

### Minimal reproduction project (MRP)

The shaders are from a bigger project, where I first noticed this in. I created a minimal reproduction project which was used for the video I linked. Open node_2d.tscn and do the same as shown in the video. Testing the same project with an older build ([daa8942f41]) fixes the issue for me. With [12a519b] or later it's 100% reproducible.
[BugTestRepro.zip](https://github.com/godotengine/godot/files/13804039/BugTestRepro.zip)

**Comment by saierXP** [comment]
Maybe it's the same as this one. Same as OP, [daa8942f41c76bdc159731ef03053de4be68ba72] is OK.
* #86678

**Comment by Rudolph-B** [comment]
I was able to replicate the issue on https://github.com/godotengine/godot/commit/12a519bae232e2e4a37a243a4050edaa0d802687. I then tested on https://github.com/godotengine/godot/commit/04eafd557faa5fbe8f7f2634810a0d2f24f99770. The bug is not present in the newer commit.

**Comment by Armynator** [comment]
Fixed with #86522
