### ISSUE TITLE
Procedural Sky Shader - we love 'em, we need 'em.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8668]
We started discussing procedural Sky Shader for Godot on IRC.
Idea is to create at least basic one for starters.

Some refs:
https://threejs.org/examples/webgl_shaders_sky.html
https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/textures/sky.html
http://blog.camposanto.com/post/112703721804/this-blog-post-is-an-in-detail-explanation-of-part
https://blenderartists.org/forum/showthread.php?245954-preethams-sky-impementation-HDR

Papers:
http://www.cs.utah.edu/~shirley/papers/sunsky/sunsky.pdf
http://cgg.mff.cuni.cz/projects/SkylightModelling/HosekWilkie_SkylightModel_SIGGRAPH2012_Preprint_lowres.pdf
http://cgg.mff.cuni.cz/projects/SkylightModelling/

**Comment by n-pigeon** [comment]
Fire watch talk from GDC - useful insights how procedural skies and gradient fog was used:
https://youtu.be/ZYnS3kKTcGg?t=452

**Comment by n-pigeon** [comment]
This topic is also related to - #8060

**Comment by Zylann** [comment]
I think there is an asset-driven part, so we should look at what the engine lacks for them to be implemented.

**Comment by n-pigeon** [comment]
@Zylann
This is one of many pieces you refer too :) It's first step.

Sun will be part of Shader (at lest visual part) you will be able to control it's inclination and azimuth with Uniform shader params, so you then can connect it by script with DirectionalLamp.
Although I plan to make SunLamp node which will have DirectionalLamp node that will be easy to connect with SkyShader. This is sooo common task, that this type of node will be good to have as part of engine.

Clouds, stars, moon/planets will be added also but later :P

**Comment by nunodonato** [comment]
here's another one, for reference: https://github.com/Tw1ddle/Sky-Particles-Shader

**Comment by reduz** [comment]
You have custom particle code and asset lib anybody should be able to
contribute

**Comment by n-pigeon** [comment]
@reduz
Yup.
Initially I plan it as Asset Lib. When I will have something we can discuss - if or what we should move as default Godot toolset.
I'm open for discussion :)

**Comment by kubecz3k** [comment]
I'm not sure what's the status of this issue. We have procedural shader for the skybox in 3.0, is it solved then?

**Comment by Zylann** [comment]
I think the sky isn't a procedural shader though. Isn't it entirely generated on CPU? There is no way to make our own as well.

**Comment by bojidar-bg** [comment]
Isn't this obsoleted by #17510?

**Comment by BastiaanOlij** [comment]
The procedural sky just calculates the skytexture on the CPU. The thing to keep in mind is that it's not enough to just render the background with a shader like many engines do. You need to calculate the full 360 degree map from which Godot generates radiance maps to be able to do all the PBR lighting and such. That is a lot of overhead to do real time for each frame. You can get away with it when just rendering the sky color and sun as the sun generally doesn't move so you can recalculate once a minute or something like that, but if you want to add clouds that are animated you need to do add the clouds later on with some other technique.

@bojidar-bg is correct, the issues for making it work are fixed though there were more fixes, the last ones are in #19029, I don't know if that made it into the latest 3.0.3 RC yet but it has been cherry picked.

With that PR in place you can see it in action with with this project: https://github.com/BastiaanOlij/godot-sky-asset/tree/use_proxy_fix 
(I'll be merging that branch once 3.0.3 is released and submitting a new version to the asset library)

The shader itself could use a few improvements, it's getting the horizon wrong, but it shows how to do this all on the GPU

**Comment by BastiaanOlij** [comment]
Owh and note that this: #19030 would be a worthwhile improvement so things work more automatic.

**Comment by bojidar-bg** [comment]
Closing as per the above comment, since it is already possible to make procedural skies.

**Comment by Calinou** [comment]
This is now implemented in 4.0: https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/sky_shader.html

3.x doesn't have sky shaders, but you can use a MeshInstance with a ViewportTexture applied on it to create a real-time animated sky. However, the radiance map won't be updated in real-time when doing this.
