### ISSUE TITLE
Light problem when migrating from Godot 4.1.3 to the newest version (4.2.1)

### ISSUE THREAD

**Issue by krytoou** [godotengine/godot#86695]
### Tested versions

4.2.1 stable

### System information

Windows 10, Compatibility render mode

### Issue description

I just updated to the `Godot 4.2.1`
And found this light system a bit crazy in `Compatibility` mode:
just to compare:
Godot 4.1.3 (without shadows, because not supported)
![1704122903-822933-1](https://github.com/godotengine/godot/assets/135533212/56212b01-dd08-49b7-a778-f215176ec790)
Godot 4.2.1 (with shadows and **crazy** light)
![1704122912-618662-2](https://github.com/godotengine/godot/assets/135533212/7ac61581-ae9f-45f3-9d52-6148fe14346a)
Both have `1` on `Energy` parameter.
![1704122951-441286-image](https://github.com/godotengine/godot/assets/135533212/4a044b6d-1071-4f7c-9ca9-c5a1c9f84a3e)

If be short, **shadows is the problem**, exactly `Normal Bias`, but i dont know how to fix that.
![1704123579-326412-image](https://github.com/godotengine/godot/assets/135533212/03037023-54c1-4432-b905-457c4ba1743b)
Screen without Normal Bias looks like this and still some Hard light here:
![1704123625-421190-image](https://github.com/godotengine/godot/assets/135533212/fcee0df7-1d65-41fe-8f84-4eb034174d47)

Don't want to port my game to the newest version because of this. Please fix that!

### Steps to reproduce

1. Create new project
2. Add some objects
3. Add Light environment
4. Change render to `Compatibility` mode

### Minimal reproduction project (MRP)

[light_test.zip](https://github.com/godotengine/godot/files/13805691/light_test.zip)

**Comment by krytoou** [comment]
Also, add "Save Code Folding" option here:
![image](https://github.com/godotengine/godot/assets/135533212/da892aaf-5a86-48d9-9633-81d1111cde0c)

**Comment by clayjohn** [comment]
Lights with shadows won't look exactly the same as lights without shadows. Unfortunately, due to limitations with older mobile devices, we have to implement shadows in the compatibility renderer using a multi pass rendering approach. The result of that is that lights with shaders are rendered in sRGB space, instead of linear space. So enabling shadows on a light will change its appearance (sometimes quite drastically)

If you want to enable shadows on a light, you will need to tweak the energy to get something that looks the same as an unshadowed light

**Comment by krytoou** [comment]
> Also, add the "Save Code Folding" option here: ![image](https://private-user-images.githubusercontent.com/135533212/293771693-da892aaf-5a86-48d9-9633-81d1111cde0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjcyMzIsIm5iZiI6MTcwNDI2NjkzMiwicGF0aCI6Ii8xMzU1MzMyMTIvMjkzNzcxNjkzLWRhODkyYWFmLTVhODYtNDhkOS05NjMzLTgxZDExMTFjZGUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QwNzI4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2IyZjRkOTViMzk1ZjhkMzI4NmJhYjU5NTI4MDM5YmY3Zjg5YTNjN2Y4M2Y3MGRlZWZkYWU0ODU0Y2FhMzQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0LNRzzh2tk76SgkEsnhJ-BAH3bnJ2tk3pTx1bV9glZ0)

What about code folding? It is not saving the folded code.

**Comment by krytoou** [comment]
also, why this is still not fixed?
https://github.com/godotengine/godot/issues/67497
so many bugs...

**Comment by AThousandShips** [comment]
It is fixed, just not cherry picked for 4.1.x, it works fine in 4.2

**Comment by akien-mga** [comment]
Please don't mix unrelated issues in the same report. This bug report is about light issues, if you have a proposal to improve code folding, open a dedicated proposal on https://github.com/godotengine/godot-proposals. And don't reference unrelated bugs, especially if they're marked as fixed already in the last version.

**Comment by krytoou** [comment]
> fixed already in the last version.

the last version is bugged itself.
the more time i work in Godot, the more i see that it was delevoped unprofessionally.

**Comment by AThousandShips** [comment]
Code folding is already tracked here:
* https://github.com/godotengine/godot/issues/85780

**Comment by akien-mga** [comment]
I asked you to keep issues separate, and you edited this issue to go clearly against that, mixing unrelated issues affecting different versions of Godot. Then you call us unprofessional...

Take this as your last warning, we won't tolerate more breaches of our Code of Conduct. Either you behave professionally and follow our policies without insulting us, or you will be banned.

**Comment by krytoou** [comment]
@akien-mga yep, i called you unprofessional, not exactly you, but the whole team worked on these bugged updates.
even if you ban me, what next? you can be proud of yourself, ok...
what will prevent me from logging into another account? nothing? - right!

to be short, if you want to fix something, don't make 2 issues from the 1.

**Comment by akien-mga** [comment]
Making a new account to circumvent a ban is a breach of GitHub's Terms of Service, but go ahead.
