### ISSUE TITLE
Godot editor dropdown menu's interaction will be blocked when tooltip shows up

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#86700]
### Tested versions

Reproducible in current master and 4.2 stable

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

Here is the video:

https://github.com/godotengine/godot/assets/8315986/4dcd3170-7006-4795-90b2-3739fcb0a77a

As you can see, when hover the menu for a short time and the tooltip appears, I can't move my cursor to other menu item to hover them, looks like the input is blocked. I have to move the cursor out and in again to make the tolltip disappear, and then all is well.

### Steps to reproduce

* Open godot, click Debug menu
* hover one item until tooltip shows
* move the cursor inside the menu and observe

### Minimal reproduction project (MRP)

N/A

**Comment by saierXP** [comment]
It can only be reproduced in multi-window mode, plus it should be a duplicate of this one:
* https://github.com/godotengine/godot/issues/73926

**Comment by jsjtxietian** [comment]
Yes, closing it as duplicate.
