### ISSUE TITLE
Cannot access keyword values in json via "." notation

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#8671]
If you put a "min" key (for example) in some json and attempt to access it via `json.min` the following syntax error will arise `Parse Error: Expected ',' or ')'`. Not sure if this is intended behavior or not, `json["min"]` works fine. IDK if it is worth the reward/effort ratio to fix this in the GD Script editor.

**Comment by nunodonato** [comment]
just to double check, did you try with other key names? because 'min' is a keyword in gdscript and I believe you can't do dict.min or dict.max

**Comment by akien-mga** [comment]
That's indeed another symptom of #8085, which @bojidar-bg proposed to fix with #8217.

**Comment by bojidar-bg** [comment]
Closing in favour of #8085, since it is more active that this one, while the underlying problem is the same as in #7321.

P.S. Off to retitle the other issue...
