### ISSUE TITLE
C#, Casting issue with custom Resource.

### ISSUE THREAD

**Issue by weirdbeardgame** [godotengine/godot#86714]
### Tested versions

Tested in 4.2 stable

### System information

Arch Linux

### Issue description

I'm working on a custom resource that contains data for levels so Godot can distinguish a Level from a basic GameObjct or "Scene"

```csharp
[Tool]
public partial class SceneManagerData : Resource
{
    [Export]
    Godot.Collections.Dictionary<string, PackedScene> _Levels;

    [Export]
    string CurrentLevel = "Test1";
}
```

However, when attempting to deserialize Godot throws a casting error ```/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'SceneManagerData'.
     at SceneManagerPlugin._EnterTree() in /mnt/data/coding/weirdbeardMono4/addons/SceneManager/SceneManagerPlugin.cs:line 176```

```csharp
   // Note that I 've also attempted assigning ManagerData directly and making the loaded type the ManagerData
   var temp = ResourceLoader.Load<Resource>(SceneManagerPath);
   GD.Print(temp.GetType()); // This validly returns a Godot.Resource
   ManagerData = (SceneManagerData)temp; // Bad Cast!

  // ManagerData = ResourceLoader.Load<SceneManagerData>(SceneManagerPath); // Same Bad cast
```

### Steps to reproduce

Take custom Resource. Serialize using ResourceSaver
`ResourceSaver.Save(ResourceObject, FilePath)`
Then attempt to deserialize
`ResourceObject = ResourceLoader.Load<ResourceObjectType>(FilePath);`

### Minimal reproduction project (MRP)

https://github.com/weirdbeardgame/GodotSceneManager - link to the project I'm working on which features the minimum example. Note that level types are highly WIP and were ripped from another project. They will be fixed to make them more generic later.

**Comment by AThousandShips** [comment]
Your resource has to be `[Tool]`

Duplicate of https://github.com/godotengine/godot/issues/85459

**Comment by weirdbeardgame** [comment]
It is a tool script

**Comment by weirdbeardgame** [comment]
In my minimal example, my class is a Tool, https://github.com/weirdbeardgame/GodotSceneManager/blob/be16f7a0cc156904752b3d9ac2e2ac095a9d68c9/addons/SceneManager/SceneManager.cs#L6

**Comment by AThousandShips** [comment]
Well then that wasn't clear from the example code as it didn't use it, and I assumed it was accurate 🙂

Then this might be different, reopening for further testing

**Comment by AThousandShips** [comment]
Oh wait this is because you need each class to be in their own file, `SceneManagerData` must be in a `SceneManagerData.cs` file, please try that

**Comment by weirdbeardgame** [comment]
Seems having it in a different file fixed the issue. Perhaps a note on https://docs.godotengine.org/en/stable/tutorials/scripting/resources.html mentioning the need for Tool and the need for a resource to be a different file like that would be a good add.
