### ISSUE TITLE
Strange problem with a driver of Godot 4.2 stable

### ISSUE THREAD

**Issue by GioeleVasile** [godotengine/godot#86724]
### Tested versions

4.2 stable

### System information

Android 

### Issue description

Hello,

I am a beginner. Recently I asked help for create animations for my 2D game (the first, with sprites).
But the problem is that even if the programmation is do well Godot have a freeze at the loading screen when I want to run the game.
I intend Godot on Android, expecially on a tablet, but it do that even in a smartphone.
Pratically there is a problem with a driver 

Vulkan: Did not create swapchain successfully. Error code: VK_ERROR_SURFACE_LOST_KHR
Error code: VK_ERROR_SURFACE_LOST_KHR

In the smartphone it still doesn't work, but it even doesn't say there is an error when I restart.

I must force the closen of the app from Android when it freeze.

A person DM that saw my programming code and the project said it is weird, he never see this error before.

The game have 3 scenes, one for toucscreen controls, one for the protagonist and one for have beetwen in one scene.
It have a AnimationPlayer and a AnimationTree. 

If I decide to run only the control scene it work, if I decide to run the protagonist or the "All scenes" scene Godot freeze in the loading screen.

Even changing from "Mobile" to "Compatibility" doesn't work because Godot require a restart and after that it is still "Mobile" and have the same problem.

I use touchscreen control because I'm using Godot from Samsung Tab A8 and Godot doesn't see the bluetooth keyboard (because pratically it give commands with negative values, or I don't remember).

What is this error? What could I do?

![Screenshot_20240102_174658_Godot Editor 4](https://github.com/godotengine/godot/assets/32072504/473aa1c4-4103-48f9-ab1e-95fa1368be5b)
![Screenshot_20240102_174717_Godot Editor 4](https://github.com/godotengine/godot/assets/32072504/0160ee46-92c9-452d-8f26-d526070f9bb3)
![Screenshot_20240102_180415_Godot Editor 4](https://github.com/godotengine/godot/assets/32072504/76d1e9ba-36f5-49c4-aa4c-ef2ed326dbb5)

### Steps to reproduce

Use my project in a tablet or smartphone and press start.

You can see the script in the screenshot.
I used an AnimationTree with four animation for each direction or stop the protagonist.

Animations that I used are sprites so you can use what sprite you want.

### Minimal reproduction project (MRP)

I can't add the project file

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/71929

For other related issues

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71929.

In the meantime, use the Compatibility rendering method to avoid this issue. It's the most compatible rendering method and generally the fastest on mobile devices too. Make sure to change the `.mobile` override of the **Rendering Method** project setting, as the dropdown in the top-right corner doesn't affect it.

**Comment by GioeleVasile** [comment]
> Thanks for the report! Consolidating in #71929.
> 
> In the meantime, use the Compatibility rendering method to avoid this issue. It's the most compatible rendering method and generally the fastest on mobile devices too. Make sure to change the `.mobile` override of the **Rendering Method** project setting in the Project Settings dialog, as the dropdown in the top-right corner doesn't affect it.

The solution doesn't work, even in compatibility mode Godot doesn't run the game.

**Comment by Calinou** [comment]
> The solution doesn't work, even in compatibility mode Godot doesn't run the game.

What Android device model do you have? This may be due to the same cause as https://github.com/godotengine/godot/issues/86112.

**Comment by GioeleVasile** [comment]
> > The solution doesn't work, even in compatibility mode Godot doesn't run the game.
> 
> What Android device model do you have? This may be due to the same cause as #86112.

Samsung tab A8

**Comment by GioeleVasile** [comment]
> > The solution doesn't work, even in compatibility mode Godot doesn't run the game.
> 
> What Android device model do you have? This may be due to the same cause as #86112.

So Isn't there a solution? I want to create a game for mobile (as a beginner), we are speaking about few animations. 3 years for me seem very little time...

**Comment by Alex2782** [comment]
> I can't add the project file

@GioeleVasile 
Can you compress it with zip? (the whole project folder)
How big is the file? if > 10 MB then you have to share it on Google Drive, for example.

**Comment by GioeleVasile** [comment]
> > I can't add the project file
> 
> @GioeleVasile Can you compress it with zip? (the whole project folder) How big is the file? if > 10 MB then you have to share it on Google Drive, for example.

https://drive.google.com/file/d/12aFC13hyJKmQdXHfelO7QmspEiPVhTqX/view?usp=drivesdk

**Comment by GioeleVasile** [comment]
> > I can't add the project file
> 
> @GioeleVasile Can you compress it with zip? (the whole project folder) How big is the file? if > 10 MB then you have to share it on Google Drive, for example.

You can use the link for access to the project with .zip

**Comment by Alex2782** [comment]
ok, I'll try to test it next week and test it on my tablets (Android 8 and 13).

`.godot` folder is not necessary, mostly not compatible on other computers. This folder is usually hidden.

![Bildschirmfoto 2024-01-05 um 16 18 31](https://github.com/godotengine/godot/assets/41921395/d4383c70-9306-4d94-a11c-c2719ffe6a63)

**Comment by GioeleVasile** [comment]
> ok, I'll try to test it next week and test it on my tablets (Android 8 and 13).
> 
> `.godot` folder is not necessary, mostly not compatible on other computers. This folder is usually hidden.
> 
> ![Bildschirmfoto 2024-01-05 um 16 18 31](https://private-user-images.githubusercontent.com/41921395/294535598-d4383c70-9306-4d94-a11c-c2719ffe6a63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzI4MDQsIm5iZiI6MTcwNDQ3MjUwNCwicGF0aCI6Ii80MTkyMTM5NS8yOTQ1MzU1OTgtZDQzODNjNzAtOTMwNi00ZDk0LWExMWMtYzI3MTlmZmU2YTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE2MzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNWZjYzU1Nzk4MjgwMjAzMWFiNjBmYzE1ZjU0OTA5ZDg2MmMyZTdmOWU3M2U1ZWFlZWM1MjE5MmRkMmU3ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0l45ohCnE8DPQq-hjjZ3WFJqzWIwCOL2DZDWMUlY5hE)

In Godot there is an option for export the project, even if I don't know if I did good. If something isn't correct you can say to me. Well, I can wait, but before is better then after because every time there is an error I must to stop what I wabt to do for days or week.

**Comment by GioeleVasile** [comment]
> > I can't add the project file
> 
> @GioeleVasile Can you compress it with zip? (the whole project folder) How big is the file? if > 10 MB then you have to share it on Google Drive, for example.

This for me worked! But I don't know why in the other ways it didn't work, for others it should work.
![Screenshot_20240106_072300_Godot Editor 4](https://github.com/godotengine/godot/assets/32072504/f6ae9bb3-c990-428a-8e22-4ad2c791e10a)

**Comment by Alex2782** [comment]
> In Godot there is an option for export the project, even if I don't know if I did good. 

I also need `project.godot`. 

Please just open the folder outside of Godot Editor in File Explorer -> **select all files**, right mouse button, context menu -> compress files. If your system has it, otherwise copy all files and copy them to a new folder first. The zip file should be smaller than 2 MB, if you don't copy the hidden folder `.godot`, then you can also upload it here at Github.

-----------------------


![image](https://github.com/godotengine/godot/assets/41921395/b64680ce-e51d-491c-9c21-cf84a586c9ef)

**Comment by GioeleVasile** [comment]
> > In Godot there is an option for export the project, even if I don't know if I did good.
> 
> I also need `project.godot`.
> 
> Please just open the folder outside of Godot Editor in File Explorer -> **select all files**, right mouse button, context menu -> compress files. If your system has it, otherwise copy all files and copy them to a new folder first. The zip file should be smaller than 2 MB, if you don't copy the hidden folder `.godot`, then you can also upload it here at Github.
> 
> ![image](https://private-user-images.githubusercontent.com/41921395/294726846-b64680ce-e51d-491c-9c21-cf84a586c9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTA4NjYsIm5iZiI6MTcwNDYxMDU2NiwicGF0aCI6Ii80MTkyMTM5NS8yOTQ3MjY4NDYtYjY0NjgwY2UtZTUxZC00OTFjLTljMjEtY2Y4NGE1ODZjOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2NTYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZGNmN2Q1ZjA1OWYwMTZjZjY5YjI4OTg4NzNlNjU3YTE1MTEzYmRhOTJkNzA1NzY2NjgzMjdhMDZjNDY3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2PbOJc0xYr0PpA1kdBYcFODGvd-SJeqdC2jO88BAtV0)

Ok I will do it, but I am from Android not a pc

**Comment by GioeleVasile** [comment]
> > In Godot there is an option for export the project, even if I don't know if I did good.
> 
> I also need `project.godot`.
> 
> Please just open the folder outside of Godot Editor in File Explorer -> **select all files**, right mouse button, context menu -> compress files. If your system has it, otherwise copy all files and copy them to a new folder first. The zip file should be smaller than 2 MB, if you don't copy the hidden folder `.godot`, then you can also upload it here at Github.
> 
> ![image](https://private-user-images.githubusercontent.com/41921395/294726846-b64680ce-e51d-491c-9c21-cf84a586c9ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTUyMDksIm5iZiI6MTcwNDYxNDkwOSwicGF0aCI6Ii80MTkyMTM5NS8yOTQ3MjY4NDYtYjY0NjgwY2UtZTUxZC00OTFjLTljMjEtY2Y4NGE1ODZjOWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA4MDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTU3YWRkNzNkNDJkYmU2ZTI5NmU5MmYwYjJjYjQyNzZiNWU3ZDM3M2ZhMmU3NDg3MzExNTE1MjU1NDRjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yat7y_691ydKfjZtvVP1S2YRwj18MWtonek5TQQhEn8)

I don't know if there are unnecessary files, I say sorry, but here there is the link for "Thrue project". However, you must to write the code because I modificated it, so I have added 2 screenshots. You must even to create an Animation three.
Sorry for this but I can't write and rewrite the code every day. 

I'm sorry.
https://drive.google.com/drive/folders/1320xKXdB3aUD1PseJn_VvYdCMSiZoJ0f

**Comment by Alex2782** [comment]
Hmm ok, now I don't know if I'll even find enough time. Using Godot Editor on an Android is very cumbersome, finding the bugs is even more cumbersome especially on old hardware.


Next time you report a issue, please read carefully what is written under Inputs. **Menu > Help** also has Godot Editor on Android.
_______

**System information**
Specify the OS version, and when relevant hardware information.

Starting from Godot 4.1, you can copy this information to your clipboard by using **Help > Copy System** Info at the top of the editor window.

**Comment by GioeleVasile** [comment]
> Hmm ok, now I don't know if I'll even find enough time. Using Godot Editor on an Android is very cumbersome, finding the bugs is even more cumbersome especially on old hardware.
> 
> Next time you report a issue, please read carefully what is written under Inputs. **Menu > Help** also has Godot Editor on Android.
> 
> **System information** Specify the OS version, and when relevant hardware information.
> 
> Starting from Godot 4.1, you can copy this information to your clipboard by using **Help > Copy System** Info at the top of the editor window.

Don't worry, I found another way to bypassa momently this problem. For I don't know why reason, Godot doesn't crash if I use only AnimationPlayer in a certain way then the others way that other developers said to me, as what there is written in the screenshots.

However, pc is similar to tablet because the mouse is the touchscreen and I use a bluetooth keyboard for write.

**Comment by GioeleVasile** [comment]
> Hmm ok, now I don't know if I'll even find enough time. Using Godot Editor on an Android is very cumbersome, finding the bugs is even more cumbersome especially on old hardware.
> 
> Next time you report a issue, please read carefully what is written under Inputs. **Menu > Help** also has Godot Editor on Android.
> 
> **System information** Specify the OS version, and when relevant hardware information.
> 
> Starting from Godot 4.1, you can copy this information to your clipboard by using **Help > Copy System** Info at the top of the editor window.


Godot v4.2.1.stable - Android - Vulkan (Mobile) - integrated Mali-G52 -  (8 Threads)

Android 13, Samsung Tab A8.

Vulkan 1.1.191 and OpenGL ES 3.2

**Comment by Alex2782** [comment]
I checked your project again, it is much too big (40 MB, without '.godot' folder) **and buggy.**
`E 0:00:00:0482   Sprite2D.gd:2 @ _ready(): Node not found: "AnimationPlayer" (relative to "/root/CanvasLayer/Protagonist/Sprite2D").`

Without a reasonable 'Minimal reproduction project (MRP)' hardly anyone will be able to check your problems. 
I think there are comparable issues that can be checked more easily on normal PCs: https://github.com/godotengine/godot/issues/71929

**Comment by GioeleVasile** [comment]
> I checked your project again, it is much too big (40 MB, without '.godot' folder) **and buggy.** `E 0:00:00:0482 Sprite2D.gd:2 @ _ready(): Node not found: "AnimationPlayer" (relative to "/root/CanvasLayer/Protagonist/Sprite2D").`
> 
> Without a reasonable 'Minimal reproduction project (MRP)' hardly anyone will be able to check your problems. I think there are comparable issues that can be checked more easily on normal PCs: Error code: VK_ERROR_SURFACE_LOST_KHR -> #71929.

I wrote fo you code need to be rewrite because I modificated it. You can find two screenshot for that.

**Comment by Alex2782** [comment]
My recommendation would be **without** the entire '**NinjaAdventure**' folder (40MB), I can also see sounds there, for example. Try to create a 'Minimal reproduction project (MRP)' first and create a new report. Then there is a good chance that a volunteer will take a closer look at your problems.

**Comment by GioeleVasile** [comment]
> My recommendation would be **without** the entire '**NinjaAdventure**' folder (40MB), I can also see sounds there, for example. Try to create a 'Minimal reproduction project (MRP)' first and create a new report. Then there is a good chance that a volunteer will take a closer look at your problems.

Ok sorry now understand. I will do that, today or tomorrow.

Pratically, when there was the problem I used AnimationPlayer and AnimationTree indicating the animations that the tablet should run.

But it crashed at the start, in the loading screen with the Godot icon. Sometimes it said an error, maybe because after 10 minutes the tablet went to standby, but Godot didn't say there was an error.

You can see the code in the screenshots where there is the projetct in drive. My project is very simple, I cab rewrite it if you need this because I used only a sprite, a code, touchscreen buttons, AnimationPlayer and in that case even AnimationTree.

However, it is a 2D game. Someone on Discord said to me to write the code in that way, but he did a 3D game while I 2D so maybe things run in different ways.

**Comment by Alex2782** [comment]
I am currently creating an app with more debug information for Vulkan. I could add your project there later and then you could try a real exported app to see if it crashes that way.

**Comment by GioeleVasile** [comment]
> I am currently creating an app with more debug information for Vulkan. I could add your project there later and then you could try a real exported app to see if it crashes that way.
> 
> > Samsung Tab A8
> 
> @GioeleVasile:
> 
> * Which model number do you have exactly?
> * Android version?
> * Can you find your tablet on this page?: https://www.vulkan.gpuinfo.org/
> * maybe here? [Samsung Galaxy A8](https://www.vulkan.gpuinfo.org/listreports.php?devicename=Samsung+Galaxy+A8%282018%29)
> * App on Playstore: [CapsViewer](https://play.google.com/store/apps/details?id=de.saschawillems.vulkancapsviewer&hl=en_US)
> 
> **For example:** I have `Samsung Galaxy Tab A (2016)`, model number: `SM-T580`. Android 8.1.0 And I can't install the app "CapsViewer" because arm32, the app is only available for arm64. I can't find a report for my tablet.

Link for project without useless files, I have rewrite the code as it was when there was the  problem:

https://drive.google.com/file/d/13TgOS1FJA4lVNwJt4Bww7nXHXASUDxLw/view?usp=drivesdk

Android 13
Samsung Tab A8
Display name Samsung SM-X200
OpenGL ES 3.2 v1
Vulkan 1.1.191
Godot 4.2 stable
Device name Mali-G52
GPU integrated
Processor AArch64

**Comment by Alex2782** [comment]
I think it would be better if you find a friend with a PC to help you prepare a project smaller than 2 MB.  You could try remote debugging (USB cable + developer mode) to check whether an exported app is also causing problems.

-----------------
> Link for project without useless files, I have rewrite the code as it was when there was the problem:

**112 MB** is **not** a Minimal reproduction project (MRP). There are "simple" GdScripts errors, this is not the `VK_ERROR_SURFACE_LOST_KHR` error. Unfortunately, I can't help you until then. In an exported APK file, the project would not help you to check the error. 

<details><summary>Screenshot (click to expand)</summary>

![Bildschirmfoto 2024-01-08 um 16 04 29](https://github.com/godotengine/godot/assets/41921395/488c6879-e1a3-4910-b3b6-07ad4d428a49)
</details>

**Comment by GioeleVasile** [comment]
> I think it would be better if you find a friend with a PC to help you prepare a project smaller than 2 MB. You could try remote debugging (USB cable + developer mode) to check whether an exported app is also causing problems.
> 
> > Link for project without useless files, I have rewrite the code as it was when there was the problem:
> 
> **112 MB** is **not** a Minimal reproduction project (MRP). There are "simple" GdScripts errors, this is not the `VK_ERROR_SURFACE_LOST_KHR` error. Unfortunately, I can't help you until then. In an exported APK file, the project would not help you to check the error.
> 
> Screenshot (click to expand)

I don't know why Google drive say 112Mb, it is 41,53 Mb. If I donwload it from smartphone it is a little different then if I download it from tablet.

Hiwever, if you put the project in Godot you can see and understand easy what files are usefull and what files are useless, because it is only a sprite and few things that you can't be confuse.

**Comment by GioeleVasile** [comment]
> I think it would be better if you find a friend with a PC to help you prepare a project smaller than 2 MB. You could try remote debugging (USB cable + developer mode) to check whether an exported app is also causing problems.
> 
> > Link for project without useless files, I have rewrite the code as it was when there was the problem:
> 
> **112 MB** is **not** a Minimal reproduction project (MRP). There are "simple" GdScripts errors, this is not the `VK_ERROR_SURFACE_LOST_KHR` error. Unfortunately, I can't help you until then. In an exported APK file, the project would not help you to check the error.
> 
> Screenshot (click to expand)

It's strange, but when I compress the project I see it is 112Mb, without the compress 50kb.

Search to uncompress the files
