### ISSUE TITLE
No way to tile a texture on a surface with SpatialMaterial in a general way

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8672]
There is apparently no way to tile a texture on a surface in a general way in Godot 3.0 at the moment.

**Comment by tagcup** [comment]
I'm not certain whether this is a problem with UV mapping on the repeat flag.

Tiling a texture on a surface can be achieved in Godot 2.x by using UV Xform in conjunction with repeat flag. I haven't seen anything similar to UV Xform, so it seems it's not (yet) possible to tile a texture on a surface in Godot 3.0.

**Comment by nunodonato** [comment]
UV scale, its down on the bottom after the texture maps

**Comment by tagcup** [comment]
Oh, this is so embarrassing. Thanks for pointing that out, I missed that!

Unlike Godot 2.x, it's only scaling though, meaning no rotation or shear (not that I need it now). Was there any particular reason for that, or is it just temporary?

**Comment by nunodonato** [comment]
no idea, I guess only @reduz will know :)

one thing is for sure, using scale and offset instead of transforms is far more friendly for the most common use cases.

**Comment by reduz** [comment]
Its on purpose.. rotation and shear are a rare use case and providing a
transform makes things more complex.

3.0 will allow converting a spatialmaterial to a shadermaterial.. so you
can start with something as a base and then tweak the code a bit for what
you want.
