### ISSUE TITLE
Inconsistency: `"1a".to_snake_case() == "1a"`, but `"1aa".to_snake_case() == "1_aa"`.

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#86734]
### Tested versions

Reproducible in:
`3.5.3.stable` using `capitalize`
`4.2.1.stable` using `capitalize` and `to_snake_case`.

### System information

Linux on kernel 6.6.7-arch1-1

### Issue description

```gdscript
extends Node

func _ready():
	print("1a".capitalize())
	print("1aa".capitalize())
	print("1a".to_snake_case())
	print("1aa".to_snake_case())
```

Output:

```
1a
1 Aa
1a
1_aa
```

Expected:

```
1 A
1 Aa
1_a
1_aa
```

### Steps to reproduce

https://gd.tumeo.space/?KYDwLsB2AmDOAEA5A9tYAodAzArpAxvAPoBOwAhtAJ4AUAlAFzoCQADiQJaRg0BEAjOV4A6fOVYcw5ADYcAXsHp0W7LjwHkho8ZJnzFdZW07c+gkWGRFYkcgGtgRMbANHVpjVsvXbDp+RclIA

### Minimal reproduction project (MRP)

[to_snake_case_4.2.1.zip](https://github.com/godotengine/godot/files/13815827/to_snake_case_4.2.1.zip)

**Comment by dalexeev** [comment]
This is made to handle "2D"/"3D" and "str2var", "var2bytes", etc. (replaced by `_to_`). See test cases.

https://github.com/godotengine/godot/blob/07b88600b793104b21244aa36d0cc37b689e9b95/core/string/ustring.cpp#L1060-L1063

https://github.com/godotengine/godot/blob/07b88600b793104b21244aa36d0cc37b689e9b95/tests/core/string/test_string.h#L1312-L1337

**Comment by Mickeon** [comment]
A few small examples for the casing may do the trick, like `capitalize()`

**Comment by Mickeon** [comment]
I updated https://github.com/godotengine/godot/pull/86639 with some examples for this, as well. Feel free to suggest examples if necessary.
