### ISSUE TITLE
Different scroll navigations in 2d and 3d view

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8675]
**Operating system or device - Godot version:**
Any modern laptop.

**Issue description:**

Using the trackpad for 2 finger scrolling represents a drag in most applications nowadays (not zoom).
In godot scroll always zooms. (2d and 3d)
It would be amazing to be able to orbit (3d) + drag (2d) with the mouse pad two finger drag.

A modifier key would be used for zooming.

Proposed approaches:
add a device param to input event: enum Device (trackpad, mouse, (maybe touchscreen although the screen has different events anyways))
than in the input handler for the 3d/2d view scroll events from trackpad and mouse could be handled differently...

Just add a setting `use scrolling for pan and orbit` which than needs to be changed whenever the user switches from mouse to trackpad.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by toger5** [comment]
This is now detected at least on OS X and panning/scrolling -> 3d / 2d navigation work really well...
I think it is not as configurab le as it could be but the issue is defintly solved
