### ISSUE TITLE
Particle system broken in 4.3 dev 1

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#86757]
### Tested versions

4.3 dev 1

### System information

Windows 11 Godot 4.3 dev 1

### Issue description

I have a particle system in my prototype. When I have collision shapes visible in debug mode particle system is fine. When I disable it particles start to flicker.

![Godot_v4 3-dev1_win64_lcBxuj0ODM](https://github.com/godotengine/godot/assets/62170071/42fe8836-60e7-4f98-9eff-f84debc846d6)

Edit:
Wtf is going on...

![Godot_v4 3-dev1_win64_1lIa6i2oHn](https://github.com/godotengine/godot/assets/62170071/bb48a22c-1a30-4bea-bc1f-b8397f339729)

Edit2:
This is what causes it. If characterbody2d is below the particle node in the tree it does not display correctly. Dunno why :)
![image](https://github.com/godotengine/godot/assets/62170071/bb826593-b21b-45a4-92a6-a4e4793697e4)

And btw if I attach particle node to my player it breaks...

### Steps to reproduce

See MRP.

### Minimal reproduction project (MRP)

[Galaxy Prototype.zip](https://github.com/godotengine/godot/files/13822660/Galaxy.Prototype.zip)

**Comment by seppoday** [comment]
Wtf is going on...

![Godot_v4 3-dev1_win64_1lIa6i2oHn](https://github.com/godotengine/godot/assets/62170071/bb48a22c-1a30-4bea-bc1f-b8397f339729)

**Comment by seppoday** [comment]
This is what causes it. If characterbody2d is above the particle node in the tree it does not display correctly.
![image](https://github.com/godotengine/godot/assets/62170071/bb826593-b21b-45a4-92a6-a4e4793697e4)

**Comment by seppoday** [comment]
PS: Everything works fine in 4.2.1. No issue at all. So it is something in 4.3 dev 1 version.

**Comment by AThousandShips** [comment]
Please edit your previous messages or post instead of making several commits in a row, it just causes unnecessary notifications 🙂

**Comment by seppoday** [comment]
Sorry about that... I will try to remember it in the future.

**Comment by clayjohn** [comment]
Most likely fixed by https://github.com/godotengine/godot/pull/86522
