### ISSUE TITLE
Dialog content goes outside window

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#86767]
### Tested versions

4.3 fbaab3c
Does not happen in 4.2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/1378d93c-9b1f-4348-882e-607f50569051

Seems to be regression from #84151

### Steps to reproduce

1. Right click node -> Attach script
2. Enable Built-in Script

### Minimal reproduction project (MRP)

N/A

**Comment by YeldhamDev** [comment]
I'm unable to reproduce it on Fedora Linux 39 (Wayland), I wonder if it's a Windows-specific bug? Can someone with a mac try it?

**Comment by KoBeWi** [comment]
This also affects the progress dialog:
![image](https://github.com/godotengine/godot/assets/2223172/e70afef0-02c7-4164-8f3b-2d937513208e)

**Comment by sabvdf** [comment]
Unable to reproduce it on macOS Sonoma (latest, 14.2.1, M1, retina)

**Comment by Calinou** [comment]
I can reproduce this on Linux (Fedora 39 KDE X11).

**Comment by YeldhamDev** [comment]
@KoBeWi @Calinou Could you guys test if the following code section is reached when the contents of the dialog window grows? It does on my end.

https://github.com/godotengine/godot/pull/84151/files#diff-98ae49b43f623c9f779ac51456c6778f8a51f823ea7f83f60582e65d49ac2991R1145-R1148

**Comment by KoBeWi** [comment]
It's not reached.

**Comment by YeldhamDev** [comment]
```
Window::_update_viewport_size@0x0000000005345008 (/var/home/michael/Development/Projects/godot/scene/main/window.cpp:1197)
Window::_update_window_size@0x000000000534439a (/var/home/michael/Development/Projects/godot/scene/main/window.cpp:1051)
Window::_update_child_controls@0x0000000005347272 (/var/home/michael/Development/Projects/godot/scene/main/window.cpp:1555)
call_with_variant_args_helper<Window>(Window*, void (Window::*)(), Variant const**, Callable::CallError&, IndexSequence<>)@0x00000000044dd2a0 (/var/home/michael/Development/Projects/godot/core/variant/binder_common.h:304)
call_with_variant_args<Window>@0x00000000044dcd16 (/var/home/michael/Development/Projects/godot/core/variant/binder_common.h:418)
CallableCustomMethodPointer<Window>::call@0x00000000044dbe12 (/var/home/michael/Development/Projects/godot/core/object/callable_method_pointer.h:98)
Callable::callp@0x0000000006ffb3e9 (/var/home/michael/Development/Projects/godot/core/variant/callable.cpp:56)
CallQueue::_call_function@0x000000000731dfe7 (/var/home/michael/Development/Projects/godot/core/object/message_queue.cpp:221)
CallQueue::flush@0x000000000731e70c (/var/home/michael/Development/Projects/godot/core/object/message_queue.cpp:326)
SceneTree::physics_process@0x00000000052c51cd (/var/home/michael/Development/Projects/godot/scene/main/scene_tree.cpp:471)
Main::iteration@0x0000000002b3626d (/var/home/michael/Development/Projects/godot/main/main.cpp:3934)
OS_LinuxBSD::run@0x0000000002a7dfde (/var/home/michael/Development/Projects/godot/platform/linuxbsd/os_linuxbsd.cpp:938)
main@0x0000000002a76a90 (/var/home/michael/Development/Projects/godot/platform/linuxbsd/godot_linuxbsd.cpp:86)
```

**Comment by akien-mga** [comment]
For context, in the duplicate #88128 this was bisected as a regression from #84151.

**Comment by YeldhamDev** [comment]
Update:  Manage to finally reproduce this on my end to understand what's actually happening. The window contents themselves are not going outside as I thought they were, it's just that damn panel not shrinking back when its labels were removed, which is way the notification for size changing wasn't being triggered, because the size wasn't actually changed in the end.

The problem is that I don't have a clue on how to solve this besides reintroducing NOTIFICATION_WM_SIZE_CHANGED's old behavior.
