### ISSUE TITLE
3D Simple Collision Shapes Position and Scale isn't added correctly

### ISSUE THREAD

**Issue by Bat-Computer** [godotengine/godot#86762]
### Tested versions

4.2.1

### System information

Windows 11

### Issue description

When you wish to add a collision shape, such as Box, Sphere, Cylinder or Capsule the collision shape does not match the size of the imported model as it does with the more expensive collision shapes Decompose Convex, Simple Convex and Trimesh.

Additionally these more simple collision shapes align their centres to the origin/pivot of the imported 3D Model.

This seems like a bug as you would expect the simple collision shapes to 'fit' the imported models. This slows down production as you have to manually adjust these collision shapes when a simple 'shrink-wrap' method would be more straight-forward and precise.

This is especially truen as most 3D Models require their origin to be at the base of the model to help align it to the surfce.

![Screenshot 2024-01-03 203943](https://github.com/godotengine/godot/assets/40317509/2447bc6e-c342-4f88-b074-ba763bedfc00)

### Steps to reproduce

Just add a simple collision shape (Box, Sphere, Cylinder or Capsule) to a model that has an origin at it's base, either through the Inspector or the Advanced Import Settings window.

### Minimal reproduction project (MRP)

[3D Collision Shape Bug.zip](https://github.com/godotengine/godot/files/13823286/3D.Collision.Shape.Bug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8052.
