### ISSUE TITLE
Can't drag resources into property inspector.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8676]
**Operating system or device - Godot version:**
Linux - Master

**Issue description:**
Dragging a *.png file into a Sprites `Texture` slot doesn't change the texture.
It also doesn't draw that orange "hey, you can drop me here" helper box anymore. 

![dnd_bug](https://cloud.githubusercontent.com/assets/8281916/25778468/9c55cb32-32fe-11e7-8d00-53bfc3e06c44.gif)

**Comment by reduz** [comment]
Yeah previews are disabled for the moment, will come back later

**Comment by karroffel** [comment]
@reduz this isn't about previews.

It's about not being able to drag resources into the property inspector.
In the gif you can see that it's not possible to set the texture of a sprite this way.

**Comment by Hinsbart** [comment]
Can't reproduce anymore on latest master. However, someone on irc mentioned that it's still not working for them.

**Comment by vnen** [comment]
I still have this problem in master (f9fc2ef).

**Comment by akien-mga** [comment]
Can reproduce this too with current master on Linux.

**Comment by Noshyaar** [comment]
Can't reproduce on master 9a502d3. I think it's fixed?

**Comment by vnen** [comment]
I have problems only with textures, and not all of the time.

**Comment by eon-s** [comment]
Just got this issue, I've added a new image to the project directory and didn't let me to use it as a texture via drag and drop.

**Comment by Hinsbart** [comment]
Can confirm that it's reproducible by adding a new image. icon.png can be dropped just fine while the new image can't.

**Comment by reduz** [comment]
this is a duplicate, i remember seeing it before..

**Comment by reduz** [comment]
ah yeah, #8116
