### ISSUE TITLE
New Theme: Tree drag&drop visual helper is barely visible.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#8677]
**Operating system or device - Godot version:**
Linux - Master

**Issue description:**
Dragging a Node around the SceneTree draws very thin black lines/boxes which are hard to spot.

![tree_dnd](https://cloud.githubusercontent.com/assets/8281916/25778502/bca2308c-32ff-11e7-9aa6-8f26516a62ad.gif)

**Comment by volzhs** [comment]
![peek 2017-05-07 16-04](https://cloud.githubusercontent.com/assets/8281454/25778637/f5a7a7a6-333e-11e7-9934-060b772babde.gif)

this is current state of #8631 with high light color setting.
