### ISSUE TITLE
Sound files cant be deleted

### ISSUE THREAD

**Issue by Whyimsobroke** [godotengine/godot#8678]
Godot 2.1.3

When i add sound files in a Sampleplayer2D, and later try to delete them, either by pressing the garbage can icon, sound doesnt get deleted, nothing happens. However, if i do it in earlier versions you can delete sounds

**Comment by akien-mga** [comment]
Thanks for the report. That's the same issue as #8486 which was fixed by #8429 (will be in 2.1.4).
