### ISSUE TITLE
Please use CMake

### ISSUE THREAD

**Issue by berserk82** [godotengine/godot#8679]
Hello there.
My name is Ivano Arrighetta and I'm Italian.
I would like to suggest to use CMake for creating build projects for Windows and Mac OS, other than Makefiles for *nix.

I'm pretty sure everyone would benefit from this.

Bye, Ivano.

**Comment by volzhs** [comment]
duplicated with #81 ?

**Comment by berserk82** [comment]
Yes, indeed. Sorry, I would have to search first.
Pardon.

**Comment by akien-mga** [comment]
Won't happen, sorry. SCons is great.

**Comment by SC-One** [comment]
> Won't happen, sorry. SCons is great.

Just see how many Unlike this quote ...
and this too : https://github.com/godotengine/godot/issues/81#issuecomment-299699294

**Comment by Calinou** [comment]
@SC-One Please do not bump old issues that are duplicates of others.
