### ISSUE TITLE
Increment ranges while mouse held down.

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#868]
It would be great for all of the arrows on ranges in the property inspector to increment rapidly if the mouse click is held down for more than a certain threshold (half second?).

Two other related suggestions that may make sense: allow mouse wheel scroll to increment/decrement a range, and/or the up/down arrows to do the same when a range is selected.

Having to mouse click for every increment is sometimes a little tedious.

**Comment by mamarilmanson** [comment]
yes... really tedious... 

+1

**Comment by okamstudio** [comment]
this is all planned to be fixed for 1.1

On Sat, Jan 10, 2015 at 1:43 PM, Manson Mamaril <notifications@github.com>
wrote:

> yes... really tedious...
>
> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/868#issuecomment-69462108>.
>



-- 

*OkamStudio*
