### ISSUE TITLE
gdscript syntax highlighter colors some typed variable names with the same color as the type

### ISSUE THREAD

**Issue by radishes** [godotengine/godot#86802]
### Tested versions

bb1006b2acc00aae09d906fed65396508649502c  (master branch from today.) I've noticed this since 4.3 dev began.

### System information

Windows 10

### Issue description

If strong typing is used in a list of parameters in a function definition, variable names past the first will be colored with the same color as the types.

![image](https://github.com/godotengine/godot/assets/1106565/d9910078-25fa-4dbf-a253-2584e571c676)

In this screenshot, the coloration of `another_argument` by the syntax highlighter seems incorrect. In past versions of Godot, `another_argument` would have been the same color as `an_argument`.

### Steps to reproduce

Create a gdscript function which accepts two or more parameters which are strongly typed.

### Minimal reproduction project (MRP)

```
func my_func(an_argument:int, another_argument:Vector2):
	pass

```

**Comment by Maran23** [comment]
Probably related to https://github.com/godotengine/godot/issues/85812 as well. Fixed by the same PR.
