### ISSUE TITLE
{godot 3.0} what i faced while using it!

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#8680]
https://m.facebook.com/groups/377650389038228?view=permalink&id=1011791488957445

**Comment by n-pigeon** [comment]
Please, fix your title and message to something more descriptive.

You can paste screenshots on GitHub by dropping them on message window.

I also suggest changing your ways of writing descriptions of your problems if your want to be heard.
Godot 3.0 is in pre-alpha stage, so bugs are expected.
You can help us by creating valid bug reports here :)

**Comment by gamergamesz** [comment]
ok for sure as it's my first time of using github like this
