### ISSUE TITLE
Postinitialize hook on custom ScriptExtensions always produces an error in debug mode

### ISSUE THREAD

**Issue by Mercerenies** [godotengine/godot#86816]
### Tested versions

Reproducible in: Godot_v4.2.1-stable.linux.x86_64, Godot_v4.1.1-stable.linux.x86_64, Godot_v4.0-stable_linux.x86_64

### System information

Godot v4.2.1.stable - Fedora Linux 37 (Workstation Edition) - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 620 (WHL GT2) () - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

I write the following `ScriptException` class.

```
extends ScriptExtension


func _get_language():
    # I don't actually care what we return here. The point
    # is that this never even gets called.
    print("CALLED _get_language!")
    return null
```

Then I try to simply construct it from a main node.

```
extends Node2D


func _ready():
    var test_script = load("res://TestScript.gd")
    print(test_script.new())
```

I can run this simple example project from the command line with no problems. However, when running *specifically* from the editor (i.e., when opening the project in the editor and hitting the F5 key on my keyboard to run from within the editor), I get an error.

```
ERROR: Required virtual method ScriptExtension::_get_language must be overridden before calling.
   at: _gdvirtual__get_language_call (./core/object/script_language_extension.h:106)
```

It seems to me that this is originating from https://github.com/godotengine/godot/blob/master/core/object/script_language.cpp#L53

```
if (EngineDebugger::is_active()) {
	EngineDebugger::get_script_debugger()->set_break_language(get_language());
}
```

If the engine debugger is active, then the `Script` class responds to `NOTIFICATION_POSTINITIALIZE` by calling `get_language()`, which invokes the virtual function `_get_language()`. However, at the point that `NOTIFICATION_POSTINITIALIZE` fires, virtual functions have not been set up for the object. The description for that notification in [the docs](https://docs.godotengine.org/en/stable/classes/class_object.html) states (emphasis mine)

> Notification received when the object is initialized, **before its script is attached.** Used internally.

So, as far as I can tell, there's no way that this `get_language()` call can ever succeed, for a custom `ScriptExtension` class.

**Expected behavior:** I would expect to be able to construct custom `ScriptExtension` instances without producing an error.

**Actual behavior:** As far as I can tell, any attempt to construct a custom `ScriptExtension` while the editor debugger is active will result in the aforementioned error being printed to console.

Note: This is the most minimal reproducible example I could come up with, even if it is a bit silly. For what it's worth, I discovered this while writing a GDExtension library that actually constructs the `ScriptExtension` *properly*, rather than just instantiating one and `print`ing it like I do here.

### Steps to reproduce

I have provided a minimal project below. Open the project in the Godot editor and then hit the "Run Project (F5)" button or the corresponding keyboard shortcut to run the `Main.tscn` scene. You will immediately see a red error printed in the "Debugger" tab at the bottom of the screen.

If you run the project from the command line (NOT in the editor), the bug will not manifest. You *must* open the editor to observe this bug.

### Minimal reproduction project (MRP)

[virtual binding bug.zip](https://github.com/godotengine/godot/files/13837012/virtual.binding.bug.zip)

**Comment by Naros** [comment]
I can confirm this has been a problem throughout 4.2.dev builds and 4.2.1-stable.

**Comment by Mercerenies** [comment]
I found https://github.com/godotengine/godot/issues/80275 which is very similar. Might be close enough to be a duplicate.

**Comment by tarragonfly** [comment]
Reproducable in Godot 4.2.1 stable.
