### ISSUE TITLE
Various undefined shader problems

### ISSUE THREAD

**Issue by gamergamesz** [godotengine/godot#8681]
using windows 10, i7 6700k ,16gb , nvidia 960m

the problem iam facing is like pixelization of dark textures, reloading of textures, unfamilir roughness and metalness! light problems. roughness at full become white emitting shader! 3 relection shadow. Thanks in advance!
![screenshot 16](https://cloud.githubusercontent.com/assets/13883739/25781522/b54b9b9e-3358-11e7-843b-f01cc06dd878.png)
thanks in advance!
![screenshot 13](https://cloud.githubusercontent.com/assets/13883739/25781443/0fb25ace-3358-11e7-8537-00dc04acad6c.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/13883739/25781525/c4c1d1ec-3358-11e7-9f2a-954b803d0dae.png)
![screenshot 16](https://cloud.githubusercontent.com/assets/13883739/25781543/d2c2265c-3358-11e7-8cb0-d5d17cc1de98.png)
![screenshot 15](https://cloud.githubusercontent.com/assets/13883739/25781547/e088be7c-3358-11e7-8339-98f20ad48a8f.png)
![screenshot 14](https://cloud.githubusercontent.com/assets/13883739/25781555/edf467f0-3358-11e7-94b3-75e6919c5089.png)

**Comment by reduz** [comment]
this was fixed a while ago
