### ISSUE TITLE
Running Godot Android Editor setup for OpenXR on Quest 3 Cannot Connect to HMD

### ISSUE THREAD

**Issue by BC-Laboratories** [godotengine/godot#86817]
### Tested versions

Reproducible in v4.2.1, downloaded from the official website onto my Quest 3.

### System information

Android -Godot v4.2.1.stable -Meta Quest 3 -Snapdragon XR2 Gen 2

### Issue description

The Android port of the Godot editor does not seem capable of running a project targeting OpenXR directly from the Quest 3 it was created on. This seems technically feasible, however, every time the project is ran the HMD cannot be detected.

Edit: It appears I am running it "like desktop" even though the Godot Android Editor port seems to run "desktop" as android. I would imagine this would be the correct method, not Remote Debug, like as if you are developing on PC connected to a Quest device.

### Steps to reproduce

I followed the docs exactly (as far as I am aware) to set up Godot for OpenXR to Meta Quest. I know there are limitations to the Android version of Godot, but all the export details needed seem to be accessible, so theoretically, this should be possible.

1. Install Godot 4 onto Meta Quest 3 via Unknown Sources
2. Create a new project in Godot
3. Create expected structure of XROrigin, with XRCamera as a child. (As well as controllers)
4. Install OpenXR Vendor plugin from Asset Library
5. Setup export details following the suggestion for Quest under OpenXR setup in Godot Docs
6. Attempt to Run the project.

-No matter what I do, it can never get the HMD to connect. I imagine it has to do with the HMD not being exposed in an expected way, although it is possible I am missing some simple crucial step.
-Error text: 
![image](https://github.com/godotengine/godot/assets/52177636/700862f8-b102-443f-b9e7-de5d4be3ffa3)

### Minimal reproduction project (MRP)

N/A.

**Comment by akien-mga** [comment]
I'm not sure this is supported yet. It might need a custom build of the Godot editor with Meta XR capabilities enabled. CC @m4gr3d

**Comment by m4gr3d** [comment]
@BC-Laboratories The capability is not supported yet, but we are working on enabling it as well as other related XR features.
We'll provide more info when the feature is available for testing.
