### ISSUE TITLE
`@tool` added CollisionShape not rendering in editor

### ISSUE THREAD

**Issue by AjaniBilby** [godotengine/godot#86810]
### Tested versions

Godot_v4.2.1-stable_win64

### System information

Microsoft Windows [Version 10.0.22621.2861]

### Issue description

When you add a `CollisionShape3D` or `ShapeCast3D` to a scene manually, within the editor you can see a wireframe outline of the collision boundary. However if you use a `@tool` to create the `CollisionShape3D` or `ShapeCast3D` you do not get to see any such preview in the editor, however if you add a `MeshInstance3D` to the scene via a `@tool` you will see it rendered in the editor *thought of course in all cases you do not see it listed in the scene tree*

**Expected View After `@tool` adds child (manually added child)**  
![image](https://github.com/godotengine/godot/assets/11359344/17c55c9d-91d9-465a-a2c8-ce866d52ea9b)  
**Actual View After `@tool` added child**  
![image](https://github.com/godotengine/godot/assets/11359344/89ea1ffe-aa75-45e6-8b38-2d2f74eb000d)  
**Demo showing child MeshInstance does render**  
![image](https://github.com/godotengine/godot/assets/11359344/5067b0a4-e64f-450d-8391-2db1ff23f42c)

### Steps to reproduce

```gd
@tool
extends Node3D

@export var preview_bounds: bool = false:
	set(ticked):
		if not ticked: return
		preview_bounds = false
		build_bounding_preview()

@export var generate_bounds: bool = false:
	set(ticked):
		if not ticked: return
		generate_bounds = false
		build_bounding()

func remove_all_children():
	for child in get_children():
		child.queue_free()

func build_bounding():
	self.remove_all_children()
	
	var preview = CollisionShape3D.new()
	preview.shape = BoxShape3D.new()
	add_child(preview)
	print("ran build")
	# nothing is visible in this scene, though you should see the colision wireframe
	

func build_bounding_preview():
	self.remove_all_children()
	
	var preview = MeshInstance3D.new()
	preview.mesh = PrismMesh.new()
	add_child(preview)
	print("ran preview")
	# you can clearly see the MeshInstance3D
```

### Minimal reproduction project (MRP)

[collision-rendering-test.zip](https://github.com/godotengine/godot/files/13836825/collision-rendering-test.zip)

**Comment by AjaniBilby** [comment]
Putting the collision shape within an `Area3D` or equivalent parent does not help, hence why I did the minimum required that should render for the simplest example of the bug

**Comment by KoBeWi** [comment]
Try setting `owner` to be scene root.

**Comment by AjaniBilby** [comment]
If I just set the owner to `root` I get `Condition "!is_ancestor_of(p_node)" is true. Returning: false` errors:
```gd
func build_bounding():
	self.remove_all_children()
	
	var root = get_tree().root.get_child(0)
	var preview = CollisionShape3D.new()
	preview.shape = BoxShape3D.new()
	preview.owner = root
	add_child(preview)
	print("ran build")
	# nothing is visible in this scene, though you should see the colision wireframe
```

Doing `root.add_child(preview)` prevents the errors, but still doesn't resolve the issue

**Comment by KoBeWi** [comment]
Set the owner after `add_child()`.

https://github.com/godotengine/godot/assets/2223172/e255607c-ea32-4b37-a346-468bb114cc38

**Comment by AjaniBilby** [comment]
I did try before and after, but with after I got the error message while I was still looking at the code, so I didn't look at the viewport.

So it does display when I set the owner after adding the child, however then for every interaction in the editor *including just selecting an item in the scene tree*, I get a new instance of that error message, plus I get at least 5 instances at spawn. So if I spawn 10 instances I'm going to have over 50 error messages in my logs which then will make using the logs for actual useful information very annoying.

Is there anyway to fix this?
![image](https://github.com/godotengine/godot/assets/11359344/4d4e8bcd-9553-424d-8bb2-3160dacc996c)

**Comment by KoBeWi** [comment]
What did you set as owner? I did `preview.owner = self` and have no errors. Also try reloading the scene; a node still exists with no owner or wrong owner, even if it's invisible in the scene tree.

**Comment by AjaniBilby** [comment]
When you said root, I thought you meant the true root `get_tree().root.get_child(0)` which is what I had in the code [here](https://github.com/godotengine/godot/issues/86810#issuecomment-1879554100).

I thought owner was supposed to always been the parent node of a node, so `x.add_child(y)` would make `x` the owner of `y` - but I guess not?

**Comment by AThousandShips** [comment]
> I thought owner was supposed to always been the parent node of a node, so x.add_child(y) would make x the owner of y - but I guess not?

This is not the case, by design, the owner is used specifically to handle things, see [here](https://docs.godotengine.org/en/latest/classes/class_node.html#class-node-property-owner)
