### ISSUE TITLE
Color degradation with directional shadow

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8683]
Godot 3.0 master 
Windows 10 64 bits nVidia 940M

@reduz told me at Meet the Nodes that the  Dual Paraboloid was causing colors to degrade when in shadow, and that Cube was slower but better.
Problem is, that's also the case for directional lights:

![image](https://cloud.githubusercontent.com/assets/1311555/25783130/1fcb584e-3357-11e7-8de0-305e9de7d94e.png)

Notice how colors get degraded in dark spots. It's like the color space definition is getting smaller, as if `half` was used instead of `float`.
The issue is present wether Environment effects are enabled or not, and both in game and editor.

**Comment by reduz** [comment]
Yeah many reported this, I have no idea why it happens. Will check when I
get home

**Comment by reduz** [comment]
this is fixed now
