### ISSUE TITLE
Re-importing 4K .hdr for PanoramaSky takes a few minutes 

### ISSUE THREAD

**Issue by interpol-kun** [godotengine/godot#86832]
### Tested versions

- Reproducible in Godot v4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 Threads)

### Issue description

When re-importing .hdr texture after selecting it for PanoramaSky, editor hangs up for a few minutes, while consuming ~100% of CPU.

### Steps to reproduce

1. Create a new project, create a new instance of WorldEnvironment with PanoramaSky Sky Material.
2. Drag and drop any 4K .hdr file into FileSystem (it will run the initial import, it will take a few seconds)
3. Load the texture in Panorama property of PanoramaSky
4. See the editor making re-import, which will hang Godot for a few minutes.

### Minimal reproduction project (MRP)

Open the MRP, drag and drop HDR file to Panorama of scene SkyMaterial
[HDR_Problem.zip](https://github.com/godotengine/godot/files/13843472/HDR_Problem.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80456, as this is due to the same cause.
