### ISSUE TITLE
"Replace in files" floods console with error reports

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#86856]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

When find / replacing a string in files (some of which might be already opened), the operation results in the console window getting flooded with error messages:
scene/gui/text_edit.cpp.5886 - Index p_gutter = -1 is out of bouds (gutter.size() = 4).

### Steps to reproduce

Open a few script files, some of them can contain the string that will be replaced.
Attempt to replace some text.
Click "Replace all (no undo)."
The updates will be detected by the IDE, it will ask whether to reload the changed files, confirm.
The console will get flooded with errors.

Here is the video showing it in action:
https://archive.org/download/ShowFlowFleetingWorld/2024-01-06%2006-56-39.mp4

### Minimal reproduction project (MRP)

Godot project with files

**Comment by Andrewfeng123** [comment]
I'm unable to reproduce this on win64, Godot v4.2.1.stable. Would you be able to attach an MRP?

**Comment by inhalt120g** [comment]
I also can't reproduce it anymore, I tried both with my main project and with a new project. I will leave the video (from the first post) showing what used to happen for reference if it's ever needed. Thank you for looking into this!
