### ISSUE TITLE
3D selection box transforms incorrectly if object is being moved by PhysicsServer when made active in the editor

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#86861]
### Tested versions

Godot v4.2.1.stable.mono

### System information

Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Title.

Conditions: 

Collision and Mesh shape are just boxes.

![image](https://github.com/godotengine/godot/assets/105675984/8f908f20-8e17-4c0e-9977-b0185ed3c83a)

Top level transform is enabled on the RigidBody:

![image](https://github.com/godotengine/godot/assets/105675984/b24409f5-37c9-4740-bdc0-fb3d36fc82d3)

Parent Node is setup to "follow" the RigidBody

![image](https://github.com/godotengine/godot/assets/105675984/f85f0f89-1d05-465c-ab2b-1d520e5f259f)

Result:

![bug](https://github.com/godotengine/godot/assets/105675984/548be23a-debe-4289-9fcd-febf4d5c2b0a)

### Steps to reproduce

Open node_3d.tscn
Select RigidBody3D
Unfreeze
Select Parent Node3D
Observe Selection Box

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/godotengine/godot/files/13847929/bug.zip)

**Comment by ryevdokimov** [comment]
Scale is affected too. 

![image](https://github.com/godotengine/godot/assets/105675984/ffe7b12c-8450-4d95-a1d7-0b1290149ba2)

**Comment by Calinou** [comment]
cc @rcorre

**Comment by ryevdokimov** [comment]
Thanks for taking a look, just wanted to clarify due to the name change that the rigidbody itself has a correct selection box, it's the parent Node3D that is being programmatically forced to follow the rigidbody transforms that gets wonky.

**Comment by cooperra** [comment]
I'm working with @ryevdokimov on a fix for this.

**Comment by ryevdokimov** [comment]
This is confirmed nothing to do with the PhysicsServer, and simply how AABB bounds are calculated when using top-level nodes.
