### ISSUE TITLE
feature request: movement in 3d editor

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8686]
I am sure there should be request like this kicking around somewhere but right now 3d view of the scene is basically set in stone to 0,0. What I propose is to implement WASD movement. 

How this would work:
Pressing W or S moves camera on axis from camera center to pivot
![spectacle sl4998](https://cloud.githubusercontent.com/assets/10696955/25784434/b2611fc2-3375-11e7-95c3-3cf4b2f25040.png)
Pressing A or D moves camera on axis that horizontally forms 90 degree angle with WS axis
![spectacle ti4998](https://cloud.githubusercontent.com/assets/10696955/25784460/1f5627c6-3376-11e7-90e0-107d3213fcb2.png)

P.S. I know my chicken scratch drawings are kinda crap.

**Comment by akien-mga** [comment]
You mean like, #8616 ? :)

**Comment by ArcFutahito** [comment]
Yeah, like that xD
