### ISSUE TITLE
Transition request will only fire after oneshot node played in AnimationTree 

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#86877]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) 

### Issue description

I have a transition node and connected it to a oneshot node.

When I start the oneshot node by calling:

		animTree.set("parameters/Transition/transition_request", "transition 2")
		animTree.set("parameters/OneShot/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)

It will start playing the oneshot animation, which is fine.
But after the oneshot animation played, the transition node start to change the transition, which is not I expected.

I expect it will change the transition during the oneshot node is playing.

### Steps to reproduce

same as above

### Minimal reproduction project (MRP)

[transition_node_bug.zip](https://github.com/godotengine/godot/files/13849886/transition_node_bug.zip)

**Comment by TokageItLab** [comment]
This is the intended behavior, since changing the state immediately after the request would leave the request held. if sync is enabled, the transition will process the request even during OneShot.
