### ISSUE TITLE
Crash when selecting AnimationPlayer node with wrong root

### ISSUE THREAD

**Issue by Ryangr0** [godotengine/godot#8687]
_bugsquadedit: comment in which there are reproduction steps: https://github.com/godotengine/godot/issues/8687#issuecomment-299828866_

**Operating system or device - Godot version:**
Win 10 64 bit, Godot 2.1.3 stable 64 bit & 32 bit

**Issue description:**
Selecting AnimationPlayer node causes entire program to crash due to an unhandled exception.
This is what I see when I run the project. Don't know if that has anything to do with it, but I think this started after my main problem did.
![image](https://cloud.githubusercontent.com/assets/3602480/25784775/6cfd65c8-3373-11e7-98c7-2c4cfe2783fb.png)\

Maybe I'm being stupid and overlooking a simple detail, but I hadn't expected to be able to break the program completely.

**Steps to reproduce:**
* Start project
* Click on the only AnimationPlayer node in the project

**Link to minimal example project:**
[SpriteAnimation.zip](https://github.com/godotengine/godot/files/981899/SpriteAnimation.zip)

**Comment by Dillybob92** [comment]
Change 
`root/root = NodePath("../Sprite")` (line 89, in main.tscn)

to:

`root/root = NodePath("../PlayerSprite")`


Looks like something didn't get saved correctly when editing the scene or something 

Although, not sure if godot should crash if the root path is incorrect (so it can prevent from what you experienced)... did godot accidentally crash at first when editing your scene by chance? I've noticed sometimes when that happens, some stuff doesn't get saved to the .tscn properly. Or by unexpectedly logging off the os

**Comment by Ryangr0** [comment]
I'll try this when I get home @Dillybob92, thank you for your help. I think it's worth noting however, that I did not change anything in the actual script. This is a problem that occured solely out of using the IDE's drag and drop tools. I was restructuring the tree when this happened. Maybe some value wasn't saved correctly.

**Comment by eon-s** [comment]
Found a way to replicate the bug:

 - Set a root node for the AnimationPlayer (with a name, not . or ..).
 - Change the root name (at this point, running floods the output with errors)
 - Save the scene and revert it (to reload the scene), or close and open it again.
 - Select the AnimationPlayer to crash the editor.

------------------

The best way to avoid this (if you change node names a lot) is to leave the root as it is, you can reference another node on the tracks and the track will update if you change the node name or will be marked as invalid if you do something wrong.

**Comment by Ryangr0** [comment]
@Dillybob92 That seemed to have worked. Thank you for your quick reply.

Should I leave this ticket open so that the underlying problem can get fixed?

**Comment by eon-s** [comment]
@Ryangr0 yes, leave it open, Godot should not crash, maybe show a warning sign on the player node if root is wrong instead of crashing and error flooding.
