### ISSUE TITLE
Vector2 angle() function sometimes exceeds the range (-PI, PI]

### ISSUE THREAD

**Issue by JazzyMaxine** [godotengine/godot#86879]
### Tested versions

- Tested in Godot 4.2

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce MX110 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

When checking if the angle of a Vector2 is within a certain range, I excepted the result of the .angle() function of Vector2 to be clamped on the range -PI (exclusive) to PI (inclusive). It was not, and that caused unintended side effects.

I printed the vector, the result of calling angle() on that vector, and PI to the console and got the following results: 
```
(-1, 0)
3.14159274101257
3.14159265358979
```
As you can see, the angle of the vector is very slightly greater than PI. It should be strictly bound between -PI and PI. 

### Steps to reproduce

call the angle() function on Vector2(-1, 0), and compare it to PI. 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
These are likely just precision errors, you are working with single precision floating point where the error is somewhere around this, namely on the order of 10^-8, which is how far this is from PI, you only get about 7 digits of precision with single precision floating point values

This is to be expected, unsure what if anything should be documented here, but no bug (as we're just using the built-in standard library methods for this)

**Comment by JazzyMaxine** [comment]
@AThousandShips So the output of angle() is a float, whereas the constant PI is a double? 
And when comparing a float to a double, it upsamples the float rather than downsampling the double? 
When I print float(PI) it still outputs the more accurate and smaller value.

**Comment by AThousandShips** [comment]
It's a single precision value that's input, unsure how it handles that, `Vector2` is a single precision data type on single precision builds

**Comment by AThousandShips** [comment]
Instead try doing:
```gdscript
atan2(vec.y, vec.x)
```
If you need the full precision 🙂
