### ISSUE TITLE
Autocomplete suggests invalid methods, ignoring static typing

### ISSUE THREAD

**Issue by Mopsephu** [godotengine/godot#86871]
### Tested versions

Godot v4.2.1.stable (Steam)

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 3500 6-Core Processor (6 Threads)

### Issue description

I am currently working on a project allowing user to access files on the computer. I note suitable files in PackedStringArray to use less memory and fast-up the application. When it's time to not use these files anymore I want to erase them from PackedStringArray. The syntaxis hint showed me that the method I want can be used, but then for some reason debugger complains that such method does not exist in PackedStringArray. Later on, I checked up the embedded documentation and it indeed shows that 'erase' method does not exist.
I do not know if it was intended for the method to be absent, but I hope it was not as it would helped me a lot in my project.
![Report_1](https://github.com/godotengine/godot/assets/77295905/24835741-1a91-4e9f-8ad6-68907c20727a)
![Report_2](https://github.com/godotengine/godot/assets/77295905/8c497e76-de23-48ff-a245-3537460ed948)

### Steps to reproduce

Create a PackedStringArray and after that try to type ".erase()". The hint appears, but debugger complains.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
It doesn't have this method, see the [documentation](https://docs.godotengine.org/en/stable/classes/class_packedstringarray.html)

Not a bug, please open a [proposal](https://github.com/godotengine/godot-proposals) if you want to add this, otherwise there's no issue here 🙂

**Comment by AThousandShips** [comment]
There is no such method indeed, this is a bug in the autocompletion

**Comment by Mickeon** [comment]
Admittedly, for **PackedStringArray** specifically, the lack of of `erase` is a bit unfortunate.

**Comment by AThousandShips** [comment]
This would be a problem still regardless, as it's an editor bug not the lack of the method, off topic for this

**Comment by Mickeon** [comment]
Then the name of the issue should be changed.

**Comment by AThousandShips** [comment]
It's clear from the issue text but will do

**Comment by HolonProduction** [comment]
Pick your duplicate at #85224
