### ISSUE TITLE
Virtual function `EditorNode3DGizmoPlugin::begin_handle_action` not registered to ClassDB

### ISSUE THREAD

**Issue by alessandrofama** [godotengine/godot#86880]
### Tested versions

v4.2.stable.official, v4.3.dev.custom_build [89cc635c0]

### System information

Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 31.0.22017.5002) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

I'm working on implementing a gizmo plugin similar to `CollisionShape3DGizmoPlugin` in Godot using GDExtension (godot-cpp) for my custom node. 

However, I'm facing an issue where I cannot override [`EditorNode3DGizmoPlugin::begin_handle_action`](https://github.com/godotengine/godot/blob/89cc635c0554cb2e518c830969ca4c5eedda0f4e/editor/plugins/node_3d_editor_gizmos.h#L202C1-L202C97) because it is not registered to ClassDB with `GDVIRTUAL_BIND`. 

Although I've found a workaround in this [proposal](https://github.com/godotengine/godot-proposals/issues/5669), I believe it would be helpful to have this function exposed.

### Steps to reproduce

Create a class that inherits from `EditorNode3DGizmoPlugin` and try to override `begin_handle_action`.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Have you tried overriding `_begin_handle_action`?

**Comment by AThousandShips** [comment]
This is because the correct override isn't exposed, for some reason, will look into a fix

**Comment by alessandrofama** [comment]
> Have you tried overriding `_begin_handle_action`?

Yes, it is not exposed in the godot-cpp generated `EditorNode3DGizmoPlugin` class (editor_node3d_gizmo_plugin.hpp).
