### ISSUE TITLE
Comment node missing in Visual Shaders

### ISSUE THREAD

**Issue by kubaofc123** [godotengine/godot#86883]
### Tested versions

- Reproducible in: 4.2.1.stable - Not reproducible in 4.1.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3129) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

In Godot 4.2, the comment node in visual shaders is missing and cannot be added to graph, class VisualShaderNodeComment. Class still exists but is not usable
Below are images of version 4.1.1 and 4.2.1.

![image](https://github.com/godotengine/godot/assets/17231482/caa7497a-ea15-4ae6-bbf6-2892438b30c6)
![image](https://github.com/godotengine/godot/assets/17231482/b36f2784-f98a-40ed-9d5c-93c0cc6199a8)

### Steps to reproduce

Open Visual Shader graph and try adding node "Comment"

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
See https://github.com/godotengine/godot/pull/79307

**Comment by kubaofc123** [comment]
Understood, closing down
