### ISSUE TITLE
Create Debug Keystore for android using command line tools not working

### ISSUE THREAD

**Issue by Lernwilliger** [godotengine/godot#86886]
### Tested versions

I tried at the godot 4.1.1 stable with the stable export template only then I can export to android with this version.

### System information

Windows 10 - Godot 1.1 stable

### Issue description

i am in the jdk 17.09.9 hotspot bin folder in cmd admin. 
It says no support for storage and keys for PKCS12 keystores.  the keypass thing will be ignored.( So no password.)

I am trying to create the debug keystore file with this fancy command:

keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12

### Steps to reproduce

please look in the Issue description.

### Minimal reproduction project (MRP)

no file

**Comment by Lernwilliger** [comment]
I want to add that it happens when I use a custom password and name. It says does not support different pws for PKCS12 keystores. I ve also tried with the newer version of the jdk. Same. With the original pw and name it works.

**Comment by AThousandShips** [comment]
Is the keytool failing? Otherwise describe what is actually failing, if it's that tool this isn't a bug to report here but at the appropriate page of that tool 🙂

**Comment by Lernwilliger** [comment]
I recognized the issue. I think I was too stupid for that. The thing is I was told in the tutorials always:

"You need to type in a custom password and a custom username." So I always thought on changing 2 Parameters in the code.
The second thing was that I thought it was unable to create the password because of the password type PKCS12. The given password does not support the password type was what I read when I read and the error message was that both need to be the same.

but I figured out what the issue was.
There were 2 passwords I have to change to the same. The keypass and the storepass. 

 Now it works. But still thanks for your respond.
Sometimes we struggle and struggle with simple things. For example reading correctly.😄

**Comment by AThousandShips** [comment]
In the future, for support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. Please use other channels *first* to see if this is a bug or user error. 🙂 

Closing as this wasn't an error 🙂

**Comment by Lernwilliger** [comment]
well I thought this would be a bug 🤣. I thought it wouldn t recognize the type of my password that sth is missing in the jdk.

**Comment by AThousandShips** [comment]
Even if it was it doesn't belong here, we don't make that software 🙂, so unless it was something wrong in the documentation it'd not be our problem and should have been reported elsewhere

**Comment by Lernwilliger** [comment]
Alright. Then. Where could I ask if I get a difficult issue again? (but this time a issue with Godot itself, a issue which  is not a bug)

**Comment by AThousandShips** [comment]
I linked you above 🙂
