### ISSUE TITLE
Viewport-based loudness when 'Playing' (in Inspector) AudioStreamPlayer3D node does not work with Orthogonal views

### ISSUE THREAD

**Issue by CharlesShen** [godotengine/godot#86899]
### Tested versions

- Reproducible in: 4.2.1.stable (only one I tested in)

### System information

Godot v4.2.1.stable.mono - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

When you test out a sound effect attached to an AudioStreamPlayer3D node (by clicking the "Playing" checkbox in the Inspector tab) the loudness changes based on how close you are to the node in the viewport.  However, if the viewport is in the Orthogonal view mode, the loudness of the sound effect remains static regardless of how close you are to the node in the viewport.

### Steps to reproduce

1. Add a AudioStreamPlayer3D node and attach an audio file to it.
2. In the Inspector tab, test out the file by clicking the "Playing" checkbox. 
3. Test out the audio while closely zoomed in to the node in the viewport, and again while zoomed far out.  The loudness difference should be noticeable.
4. Switch viewport to the Orthogonal view mode
5. Test out the audio again and note the static loudness regardless of viewport distance to node. 

### Minimal reproduction project (MRP)

Due to the simplicity of the issue, I don't think a sample project is needed.  However, would be glad to attach one if desired.

**Comment by Calinou** [comment]
Does it work while the audio is running a project, as opposed to the editor?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
