### ISSUE TITLE
Framebuffer objects

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#869]
(This was given greenlight in #862 but I think it's a good thing to have a separate issue for this; reduz said they will arrive in 1.1 or 1.2)

Framebuffer objects ([render textures](http://docs.unity3d.com/Manual/class-RenderTexture.html) in Unity) are essential for many effects (including all effects that require depth and/or normal textures) like [this](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter09.html) or [this](http://willychyr.com/2013/11/unity-shaders-depth-and-normal-textures/).

In my case, I'm trying to reproduce Example 9-2 described [here](http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter09.html) BTW.

**Comment by akien-mga** [comment]
Fixed in 3.0.

**Comment by seadra** [comment]
@akien-mga Are you sure this is fixed in 3.0? Can you point me to a form of documentation or code which implements this?

**Comment by reduz** [comment]
This is not implemented and will likely not be implememted for now due to no demand. 3.0 allows accessing depth and nornal, though fullscreen process shaders will be done in 3.1 together with render layers.

**Comment by seadra** [comment]
That sounds very promising, I'm looking forward to get full screen post-process shaders in 3.1.

Are you sure we can access to normal buffer?
I see from the [docs that](http://docs.godotengine.org/en/latest/learning/features/shading/shading_language.html) we can access the depth buffer with `DEPTH_TEXTURE`, but I can't find `NORMAL_TEXTURE` for spatial (there is one for canvas item, however). Is it just not documented yet?

**Comment by reduz** [comment]
It's being generated now, I suppose it could be made accessible for shaders.

**Comment by seadra** [comment]
That'd be great!

**Comment by mth2610** [comment]
Is FrameBuffer implemented in the current version? I'm in stuck when trying implement smoke shader which is based on Navier Stokes equation. Is there another way to create it without using FrameBuffer?
