### ISSUE TITLE
Signal does not connect with a bool-check operand in an "if" statement. 

### ISSUE THREAD

**Issue by WolfeSpeider** [godotengine/godot#86905]
### Tested versions

Reproducible in: 4.2 Stable, 4.1.1 Stable 

### System information

Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060

### Issue description

On attempting to connect a signal in one script (checkpoint script) to another script (player script), adding a bool-check w/ "and" operand ("and [bool name] == true:") will for whatever reason break the connection of the signal, regardless if the bool in question returns as true/meets the conditions required to continue the "if" statement. This was tested in my main project (4.2 stable), and in a separate test project (4.1 stable). 

The bool condition in this case is set to true once the player body is within an Area2D of the checkpoint object; there is a print statement I have that returns "entered" and "exited" for when the player enters and leaves the Area2D, respectively. The Area2D is working as it should and is detecting the player entering/leaving. 

When removing the bool check conditional and leaving just the input check (in this case, the press of the "E" key), the signal connects as it should and executes everything in the "if" statement properly. With the bool check conditional however, everything seems to execute in the "if" statement, including the signal emitting, but the signal for whatever reason refuses to connect to the desired script. 

Checkpoint Script - Where the signal is emitted: 
![bool_bug1](https://github.com/godotengine/godot/assets/93102563/776fb4d0-5baf-441a-81d8-bfd6a12d87fd)

Output for print statements:
![bool_bug2](https://github.com/godotengine/godot/assets/93102563/24f973a7-a6e5-420f-9e1e-1fc818f7f176)

Player Script - Where the signal is connected:
![bool_bug3](https://github.com/godotengine/godot/assets/93102563/8ce0373e-1db9-4f8d-af83-cd893bb6503e)

### Steps to reproduce

For a new project:
Step 1:
- Create a 2D project with a basic left/right side-scrolling player (with gravity and physical collision) object & script for the player
- Create a static object with an Area2D component, make sure collision with the player is masked so the player does not collide physically, but can still be detected (basically a trigger component)
- Create a script for this static object and have it be autoloaded via project settings
- Create an "a _on_area_2d_body_entered" and "_on_area_2d_body_exited" function respectively on the Area2D of the static object, and check for if the player body enters or exits ("if body.name ==  "Player"")
- Have a print statement occur for when the player enters ("Entered") and leaves ("Exited") the Area2D to ensure the player is being detected properly 

Step 2: 
- In the static object script, add a "func _physics_process(delta: float) -> void:" if none exists. Within this, add a check for an input, such as "if Input.is_action_just_pressed("activate")" 
- Add a new signal in the static object script, and have this signal emit when the above input is entered 
- Connect the signal in the "_on_ready" function in the player script to execute a custom method ("Static_script.signal_name.connect(custom_method)"). In this custom method, print "Signal received!" 
-Play and press the input, observe the output log to make sure the "Signal received" string appears to indicate a connected signal on said input being entered

Step 3: 
- In the static object script, add a bool called "is_in_range"
- In the "a _on_area_2d_body_entered" function, set "is_in_range" to true, and to false in the "_on_area_2d_body_exited" function. Print the bool in these functions to see its value when entering and exiting the Area2D to ensure it is changing as it should 
- In the "if Input.is_action_just_pressed("activate")" statement, add a check for if the "is_in_range" bool is true ("if Input.is_action_just_pressed("activate") and is_in_range == true:")
- Play and make sure you are within the range of the Area2D of the static object, then press the input. Observe that now the signal is no longer connecting with the addition of this bool check with the input check 

For the included test project: 

- In the "Trigger" script, remove or add the "and is_in_range == true:" conditional to view the issue in question. Not having the conditional with the input check will allow the signal to connect and print "SIGNAL RECEIVED!" in the output log regardless if the player object is in the Area2D (since only the input is being checked here), whereas having the conditional will prevent this signal from connecting even if the conditions are met while the player is in the Area2D. Use the "E" key to test the input. 

### Minimal reproduction project (MRP)

[Bool_Signal_Issue.zip](https://github.com/godotengine/godot/files/13851750/Bool_Signal_Issue.zip)

**Comment by kleonc** [comment]
You have two nodes with `Trigger.gd` attached: one AutoLoaded, one from `world.tscn` scene. Only the latter has an Area2D child and is connected to its `body_entered`/`body_exited` signals. This means for the AutoLoaded one `is_in_range == false` all the time.
![Godot_v4 2 1-stable_win64_Qzd7ycPeBu](https://github.com/godotengine/godot/assets/9283098/9ef066b8-3141-4e59-97ba-ec7d2bb70387)


```gdscript
# Trigger.gd
extends Sprite2D

var is_in_range: bool = false
signal checkpoint_resting

func _physics_process(delta: float) -> void:
	if Input.is_action_just_pressed("activate"):# and is_in_range == true:
		print()
		print("%s (%s)" % [self, get_path()])
		print(" condition checked")
		print(" is_in_range = %s" % [is_in_range])
		print(" checkpoint_resting.get_connections() = %s" % [checkpoint_resting.get_connections()])
		if is_in_range == true:
			print(" emitting checkpoint_resting")
			checkpoint_resting.emit()

func _on_area_2d_body_entered(body):
	if body.name == "Player":
		print()
		print("%s (%s)" % [self, get_path()])
		print(" player entered")
		is_in_range = true

func _on_area_2d_body_exited(body):
	if body.name == "Player":
		print()
		print("%s (%s)" % [self, get_path()])
		print(" player exited")
		is_in_range = false

```
Output after walking into Area2D and pressing <kbd>E</kbd>:
```
Trigger:<Sprite2D#37765514686> (/root/World/Trigger)
 player entered

Trigger:<Sprite2D#23353885889> (/root/Trigger)
 condition checked
 is_in_range = false
 checkpoint_resting.get_connections() = [{ "signal": Sprite2D(Trigger.gd)::[signal]checkpoint_resting, "callable": CharacterBody2D(Player.gd)::rest_at_checkpoint, "flags": 0 }]

Trigger:<Sprite2D#37765514686> (/root/World/Trigger)
 condition checked
 is_in_range = true
 checkpoint_resting.get_connections() = []
 emitting checkpoint_resting
```

Closing, no bug in here.

---

In case you're not sure whether you're facing a bug please firstly try asking for help in some [other community channels](https://godotengine.org/community/) (Godot Forum, Discord, Reddit, etc.), this is a bug tracker.

**Comment by WolfeSpeider** [comment]
Thank you for the response. I put in the above code of yours and I too am
seeing the same results in the output log, however despite one of the
instances of "is_in_range" returning as true, and as such the signal is
emitted, the signal still does not connect to the other script. Would I
need to somehow autoload the node with the Area2D for the signal to
connect?
