### ISSUE TITLE
Lag spikes after exporting to the Web

### ISSUE THREAD

**Issue by mirodorr192** [godotengine/godot#86913]
### Tested versions

4.1.3 / 4.2.1

### System information

Windows 10, Compatibility mode

### Issue description

For some reason, when i have exported my project as `HTML`, i have noticed a lot of lags, especially when instantiating a new objects and adding them as childs using `add_child`. 

Tried to show it here:
![Animation](https://github.com/godotengine/godot/assets/155548981/fffe28b3-c65f-4f54-912d-f28607f05a35)

Generally it have **a lot of freezes / lags**, i would like to know how to fix it.
The lags appears only when exporting for Web.
on PC this lag seems very small (but in 4.2.1 it looks exactly like in browser)

* i'm NOT using any shaders at all here!

[ Browser testing (.html) ]
I'm getting **28-35** fps from 60 needed on my laptop.
Also, tested on high-res screen -> **22-24** / 60 fps

[ PC testing (.exe) ]
about **55/60** fps on laptop
about **40/60** fps on high-res screen

It's not a such big game to have such lags, it's not even a demo, it's just an test run.

upd. What i have noticed is when i creating the bullet (not only bullet but any node stored in var) at first time it have that lag.

```
@onready var hit_point = preload("res://scenes/weapons/bullets/bullet_hit.tscn")

func shoot():
   var hit = hit_point.instantiate()
   var world = get_tree().get_root()
   world.add_child(hit)
   *lag here*
```

### Steps to reproduce

1. create a new project
2. export to web (`html`)
3. open the game and try to create a new object on scene (using `add_child`)

### Minimal reproduction project (MRP)

no need, it works the same for all of my projects

**Comment by Mickeon** [comment]
What browser are you running these on?

**Comment by mirodorr192** [comment]
> What browser are you testing these on?

Chrome 120.0.6099.131

**Comment by mirodorr192** [comment]
seems that it will not be fixed in godot, the newer version i tested -> the more lag it have  :(

**Comment by AThousandShips** [comment]
I corrected it to the normal English phrase, "spike lags" isn't a phrase in English. No one will be confused by a commonly used term being used 🙂

**Comment by AThousandShips** [comment]
Please be professional and bringing my profile and my views into this is neither professional nor appropriate, keep on topic and be mature, read the code of conduct

Have a nice day

**Comment by Calinou** [comment]
This is standard shader compilation stutter, which is already being tracked in https://github.com/godotengine/godot/issues/61233 (and https://github.com/godotengine/godot/issues/86731 for Compatibility specifically). It's more pronounced on the web platform because most browsers go through ANGLE to translate OpenGL to Direct3D (on Windows) or Metal (on macOS).

You need to instance your objects to be visible in front of the camera for a single frame, so that the shader is compiled in advance, rather than during gameplay. The same applies to particle effects, etc.

**Comment by akien-mga** [comment]
> > constructive and positive
> 
> just seen your github profile description..

I consider this to be a clear breach of our [Code of Conduct](https://godotengine.org/code-of-conduct/), both from @mirodorr192 and from the (apparently sockpuppet account, already deleted by GitHub) @raceh25857 who upvoted it.

So this results in a ban. Have a nice further gamedev journey, aim to be more respectful of your peers.
