### ISSUE TITLE
XR: Sky-based ambient light does not work on Compatibility renderer on Quest

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#86912]
### Tested versions

Reproducible in 4.2.1 stable.

### System information

Quest 2, Godot 4.2.1

### Issue description

When using a WorldEnvironment with ambient light source set to `Sky` or `Background` does not work when building to Quest 2 on Compatibility renderer. The colors from the sky are not reflected in the ambient lighting. Changing the ambient source to `Color` _does_ work properly. The sky's colors also do show up properly in the sky itself.

### Steps to reproduce

- Make a VR project using the typical setup for Quest builds.
- Make an environment with a procedural sky.
- Set the ambient light mode to be sky.
- Add an object to the scene, and make sure the ambient light is showing up correctly in the 3D view.
- Remote debug the game on Quest, and note that the ambient light is not accurate.

### Minimal reproduction project (MRP)

N/A

**Comment by BastiaanOlij** [comment]
Should be fixed by #86018 :)
