### ISSUE TITLE
[Regression] TileMap grid in editor isn't displayed correctly

### ISSUE THREAD

**Issue by Vivalzar** [godotengine/godot#86924]
### Tested versions

- Reproducible in v4.3.dev1.official [9d1cbab1c]
- Works in previous versions

### System information

Godot v4.3.dev1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4629) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Before 4.3.dev1, the TileMap grid is displayed correctly. Here it is in the current Steam version (4.2.1):
![image](https://github.com/godotengine/godot/assets/29254513/d52bf1ca-bedf-48f8-973c-45329730693f)

Now in the latest dev version (4.3.dev1), it is displayed in the ruler, completely flattened into a 10px height:
![image](https://github.com/godotengine/godot/assets/29254513/b88d59b7-25bf-4fb0-8407-90b6298810cf)

### Steps to reproduce

- Create a new project
- Create a 2D scene
- Add a TileMap into it
- Create a TileSet to it
- The grid is not displayed correctly

### Minimal reproduction project (MRP)

See above section

**Comment by KoBeWi** [comment]
Likely same issue as #86400, will be fixed in dev2

**Comment by Vivalzar** [comment]
And the bug is absent when switching to compatibility mode.

**Comment by akien-mga** [comment]
Dev2 was released, could you confirm if it solves this issue?

**Comment by Vivalzar** [comment]
Yes, it works now. 👍
