### ISSUE TITLE
Dropping BlackBerry 10 platform for Godot 3.0+

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8692]
@reduz already said this should be done, but I'd like to have the go from that platform's main advocate, @punto-, before going ahead with the `git rm` :)

The platform support would of course be kept in the *2.1* branch, only removed from *master* and the upcoming *3.0* branch.

**Comment by reduz** [comment]
Let it burn in a fire.

**Comment by punto-** [comment]
I'm ok with dropping it if there's no maintainer..
