### ISSUE TITLE
Godot Buttons "D", Left Arrow, and Down Arrow Not Working

### ISSUE THREAD

**Issue by Ficeth** [godotengine/godot#86932]
### Tested versions

- Reproducible from 4.2-stable to 3.0-stable (I don't know how to ask for input in 2.0)

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 Ti (NVIDIA; 30.0.15.1278) - Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 Threads)

### Issue description

I was programming a game with 2D movement with A and D and a weapon that you could shoot with the arrow keys, Binding of Isaac style. When playing around with the movement, I noticed I could not shoot diagonally downwards while moving right. I assumed that I had done something wrong, so I made a test in a different project, and once again, it did not work when I used the keys D, down arrow, and left arrow. However, any other keys I tried it with all worked perfectly fine.

### Steps to reproduce

```
func _process(_delta):
    if Input.is_action_pressed("D"):
       if Input.is_action_pressed("Left Arrow"):
            if Input.is_action_pressed("Down Arrow"):
                print("Success")
```

If you hold D key, left arrow key, and down arrow key  at the same time, "Success" is only printed to the screen occasionally, which is very inconvenient for a game requiring precision. What I would like to have happen is to print "Success" continually. Also, I bound "F" to the D key, and holding F along with the arrow keys gives the intended result, whereas holding D does not.

### Minimal reproduction project (MRP)

[Issue Reproduction.zip](https://github.com/godotengine/godot/files/13854197/Issue.Reproduction.zip)

**Comment by Mickeon** [comment]
This may be yet another case of [keyboard ghosting](https://www.groovypost.com/explainer/what-is-keyboard-ghosting-and-how-to-stop-it/). Try testing this online with https://drakeirving.github.io/MultiKeyDisplay/ , for example.

**Comment by Mickeon** [comment]
I just downloaded the sample project and I am unable to reproduce the issue.
