### ISSUE TITLE
Addons terrain for phones does not work

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#86939]
### Tested versions

4.2.1

### System information

Phone / Android

### Issue description

There is a problem with the terrain on the phone. When I download an add-on to Godot, the terrain does not work. There is a problem where it is not possible, even when I touch, the ground becomes terrain, or even I want to add only terrain and terrain shader 

### Steps to reproduce

‌

### Minimal reproduction project (MRP)

‌

**Comment by AThousandShips** [comment]
This should be reported to the plugin developer, not here 🙁

**Comment by Calinou** [comment]
Assuming this is the Terrain3D add-on, this is already being tracked in https://github.com/TokisanGames/Terrain3D/issues/137. Also, note that most add-ons aren't developed with touch input in mind, so you need a hardware mouse and keyboard to be able to use them efficiently.

**Comment by Sorshx** [comment]
ok thanks
