### ISSUE TITLE
core/io/file_access.cpp:807 - Condition "f.is_null()" is true. Continuing.

### ISSUE THREAD

**Issue by LagowiecDev** [godotengine/godot#86938]
### Tested versions

- 4.2.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

```
  core/io/file_access.cpp:807 - Condition "f.is_null()" is true. Continuing.
Importing: res://addons/MagicaVoxel_Importer_with_Extensions/Metadata/vox-icon.vox (scale: 0.1, file version: 150, greedy mesh: true, snap to ground: false)
Vox Importer Common: Vox Nodes are null
Vox Importer Common: Voxel Data is null
Vox Importer Mesh: Mesh is null at path: 'res://addons/MagicaVoxel_Importer_with_Extensions/Metadata/vox-icon.vox'. 
```

### Steps to reproduce

Just install this addon:
https://github.com/LagowiecDev/Godot-MagicaVoxel-Importer-with-Extensions/tree/Godot4.2

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This isn't enough information to tell what's wrong, to tell if this is because the code in the plugin is wrong, or it's a bug in the engine

**Comment by Ville-** [comment]
I had the same issue while developing a import plugin when there was a mismatch between _GetSaveExtension and the generated file inside .godot/imported. In my case _GetSaveExtension returned "png" while the generated file had "md5" extension.  This also lead to constant re-importing of files with recognized extensions when switching between Godot and other windows. 

Both problems went away as soon as I changed return value of _GetSaveExtension to "md5".

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide more information this can be reopened
