### ISSUE TITLE
Compiling iOS export templates for Godot v4.2-stable fails on Macos

### ISSUE THREAD

**Issue by AlexBowring** [godotengine/godot#86944]
### Tested versions

Only tested with Godot 4.2.stable

### System information

Godot v4.2.stable - macOS 14.1.2 - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I am trying to compile the iOS export template binaries from source using the Godot 4.2.stable source code, following the instructions [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_ios.html#compiling-for-ios)

I get the following error when I try to compile with SCons:
```
scons p=ios target=template_debug 
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
Failed to find SDK path while running xcrun --sdk iphoneos --show-sdk-path.
CalledProcessError: Command '['xcrun', '--sdk', 'iphoneos', '--show-sdk-path']' returned non-zero exit status 1.:
  File "/Users/Alex/Downloads/godot-4.2-stable/SConstruct", line 572:
    detect.configure(env)
  File "/Users/Alex/Downloads/godot-4.2-stable/platform/ios/detect.py", line 111:
    detect_darwin_sdk_path("ios", env)
  File "/Users/Alex/Downloads/godot-4.2-stable/methods.py", line 984:
    sdk_path = subprocess.check_output(["xcrun", "--sdk", sdk_name, "--show-sdk-path"]).strip().decode("utf-8")
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571:
    raise CalledProcessError(retcode, process.args,
```

Further version information. SCons installed with brew:
```
scons --version                                             
SCons by Steven Knight et al.:
	SCons: v4.6.0.e5eef322a4a727b96358a436dca46e8085ac8692, Sun, 19 Nov 2023 17:22:20 -0700, by bdbaddog on M1Dog2021
	SCons path: ['/opt/homebrew/lib/python3.12/site-packages/SCons']
```

Xcode command line tools version:
```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables

package-id: com.apple.pkg.CLTools_Executables
version: 15.1.0.0.1.1700200546
```

I also found a related issue #43090 for Godot 3.2 which was said to have been fixed by #43091, so has this bug been re-introduced in Godot 4? 

### Steps to reproduce

```scons p=ios target=template_debug ``` 
within the top-level of the Godot 4.2.stable source code folder after following the instructions [here](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_ios.html#compiling-for-ios)

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Do you have full Xcode installed? Command line tool are OK for macOS build, but not sufficient for iOS. Make sure to open it at least once (after installing or updating) to accept license and allow it to install all necessary components.

Check what's the following commands output:

```
xcrun --sdk iphoneos --show-sdk-path
```
```
xcode-select -p
```
Both should point to the location in `Xcode.app`, if it's not, try running:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by AlexBowring** [comment]
Thanks @bruvzg, initially running ```xcrun --sdk iphoneos --show-sdk-path``` errored as it couldn't find the SDK path, but running ```sudo xcode-select -s /Applications/Xcode.app/Contents/Developer``` has fixed it and the iOS export templates are now compiling for me. Thanks for opening the PR to update the docs, I'm happy for the issue to be closed once thats addressed.
