### ISSUE TITLE
Strange Screen Artifacts while viewing 3D nodes in Godot 4 and above

### ISSUE THREAD

**Issue by Polypodiopsida** [godotengine/godot#86948]
### Tested versions

-Reproducible in Godot 4.04, Godot 4.1.3.stable and  4.2.1.stable

### System information

Godot v4.2.1.stable (b09f793f5) - Freedesktop SDK 23.08 (Flatpak runtime) - Wayland - Vulkan (Forward+) - (software emulation on CPU) llvmpipe (LLVM 17.0.6, 256 bits) () - AMD Ryzen 5 5500 (12 Threads)

### Issue description

When loaded into any 3D node in these Godot versions, there are strange artifacts on the screen. They tend to move around when the camera is moved around.
![image](https://github.com/godotengine/godot/assets/115055626/b30c33f2-a544-499d-b4e5-bd1c5202ec2f)
![image](https://github.com/godotengine/godot/assets/115055626/12aae269-d6ef-45a5-b241-e897feb1f712)
![image](https://github.com/godotengine/godot/assets/115055626/d164f89c-2c79-494d-98f6-0c635503feb4)
 It also has similar artifacts when working with projects made with Godot 4.0

### Steps to reproduce

1. Open or create new project
2. Create a scene with or load a scene with a 3D node

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/13856014/test.zip)

**Comment by clayjohn** [comment]
From your post it seems like you don't have GPU drivers installed for your GPU. 

The artifacts appear to be an issue with the way that LLVMPipe renders lines. 

I suggest you first download GPU drivers for your GPU and then test again.

**Comment by Polypodiopsida** [comment]
> From your post it seems like you don't have GPU drivers installed for your GPU.
> 
> The artifacts appear to be an issue with the way that LLVMPipe renders lines.
> 
> I suggest you first download GPU drivers for your GPU and then test again.

This ended up fixing it. Could've sworn I downloaded GPU drivers, but I guess not! Thank you! :)

**Comment by Calinou** [comment]
> The artifacts appear to be an issue with the way that LLVMPipe renders lines.

I'm surprised it fails to render lines, but even lines drawn using hardware line drawing seem to be broken. So this is an issue on LLVMpipe's side we can't work around.
