### ISSUE TITLE
A copy of PackedStringArray is being changed with original

### ISSUE THREAD

**Issue by Mopsephu** [godotengine/godot#86955]
### Tested versions

Godot v4.2.1.stable (Steam)

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 3500 6-Core Processor (6 Threads)

### Issue description

As Mickeon mentioned in #86871 I can use 
> allowed_files.remove_at(allowed_files.find(file_name)) to compensate the lack of 'erase' in PackedStringArray

And so I created a function, allowing me to do it:
![Report_1](https://github.com/godotengine/godot/assets/77295905/5c3c12ee-8038-49bc-b158-17fc4691873c)
It is being used in the following part of code:
![Report_2](https://github.com/godotengine/godot/assets/77295905/f117c81a-ffa5-43e3-8aab-4b568a950994)
I decided to create a copy of 'allowed_files' as 'files_before':
![Report_3](https://github.com/godotengine/godot/assets/77295905/4bf991fc-c943-4d55-a7e8-29d60086af68)
When I debugged the code, I found out that for some reason 'files_before' had changed out of nowhere. Moreover, it is being referenced without any attempt to change its value:
![Report_4](https://github.com/godotengine/godot/assets/77295905/ebb81dbe-8f3c-4dd5-bbd9-104f0d5dd264)
![Report_5](https://github.com/godotengine/godot/assets/77295905/ddbb82e5-0cea-4598-88d6-8e4f7b2d117e)
When I started debugging via breakpoints, I found out an interesting case: when 'allowed_files' is being changed, 'files_before' changes too:
1) At first everything seems okay:
![Report_6](https://github.com/godotengine/godot/assets/77295905/7ce20bac-473d-445f-af7d-0abc93bc0081)
2) The function is being executed as intended:
![Report_7](https://github.com/godotengine/godot/assets/77295905/df56aa80-2d7f-48e7-9935-650293b35491)
3) And then 'files_before' changes:
![Report_8](https://github.com/godotengine/godot/assets/77295905/012c0ef6-15a5-4dd7-9526-994d2f72105e)

### Steps to reproduce

1) Create a PackedStringArray and fill it with some elements;
2) Create a copy of the PackedStringArray. Make sure it has the same value as original one;
3) Remove an element from original PackedStringArray;
4) Check elements in the copy: the same element was removed there too.

### Minimal reproduction project (MRP)

N/A

**Comment by Zireael07** [comment]
PackedXXXArrays are passed by reference so they are shared

**Comment by Mopsephu** [comment]
So if I want to get a copy of Packed...Array, I need to create a function where elements will be transfered via 'return', right?

**Comment by Mopsephu** [comment]
The 'sharing' feature is not convenient. It's like creating a needless pointer to the same memory cell

**Comment by Zireael07** [comment]
PackedXXXArrays aren't designed for convenience but for extreme memory performance
