### ISSUE TITLE
Godot 4.2.1 closes instantly when opening  the _console.exe file.

### ISSUE THREAD

**Issue by lucassene** [godotengine/godot#86954]
### Tested versions

- The issue can be found with the 4.2.1-stable version.
- The issue was also detected in the 4.2-stable and 4.1.3-stable versions.
- I tested 3.4.3-stable _console.cmd file, and it opened as normal.
- I didn't test any other version.

### System information

Windows 10 - Godot 4.2.1-stable

### Issue description

Starting today, when I open Godot via the _console.exe, it results in the Engine closing instantly (I can see the console popping and closing). It worked fine yesterday (I always use the Engine via the _console.exe file).

The only thing I can think of that changed is that Avast was updated today. I tried adding Godot's folder to Avast's firewall exception, but it didn't do anything.

The Engine behaves as intended when opening it via the Godot_v4.2.1-stable_win64.exe file.

### Steps to reproduce

1) Try to open the Godot_v4.2.1-stable_win64_console.exe file.

### Minimal reproduction project (MRP)

It is unrelated to an individual project, and unfortunately, I don't know how to give any more information. Is there any log that might have been created somewhere when the crash happened? If you know any other test I can do to help identify the issue, please let me know.

**Comment by Lippanon** [comment]
Try opening a Command Prompt first (press windows key, type "cmd", should be the first result) and then run the _console.exe file through it (either drag it in, or navigate to the directory and type it). This way the console won't close and you should be able to see the output before Godot closes/crashes.

**Comment by Calinou** [comment]
Can you reproduce this after uninstalling Avast and sticking to Windows Defender? Third-party antivirus programs often get overly cautious.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
