### ISSUE TITLE
When zipping files with ZIPPacker, the extracted files do not honor the system's umask

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#86967]
### Tested versions

- Reproducible in all version since [#08b1354b36c14a9c72128d33db4dbe6e5864a0e2](https://github.com/godotengine/godot/pull/78732/commits/08b1354b36c14a9c72128d33db4dbe6e5864a0e2)
- Not reproducible in Godot 4.2-stable

### System information

Godot v4.2.1.stable - Ubuntu 22.04 - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (RPL-P) () - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

Since https://github.com/godotengine/godot/pull/78732/commits/08b1354b36c14a9c72128d33db4dbe6e5864a0e2, (official build after it is Godot_v4.2.1-rc1_linux), files packaged with `ZIPPacker` loose their permission flags, regardless of the system's `umask` setting.

### Steps to reproduce

- Check the umask
```
-> umask
0002
```
- Run the MRP **before** commit https://github.com/godotengine/godot/pull/78732/commits/08b1354b36c14a9c72128d33db4dbe6e5864a0e2 (for example, using Godot_v4.2-stable_linux)

- Unzip the generated `archive.zip` file and check permission : It looks good and the extracted file permissions match the umask
```
-> unzip archive.zip && ls -l
Archive:  archive.zip
  inflating: hello.txt               
total 20
-rw-rw-r-- 1 hak hak 129 Jan  8 18:52 archive.zip
-rw-rw-r-- 1 hak hak  11 Jan  8 18:52 hello.txt
```

- Run the MRP **after** commit https://github.com/godotengine/godot/pull/78732/commits/08b1354b36c14a9c72128d33db4dbe6e5864a0e2 (for example, using a custom build or any official build after 4.2-stable)

- Unzip the generated `archive.zip` file and check permission : 
```
-> unzip archive.zip && ls -l
Archive:  archive.zip
  inflating: hello.txt               
total 20
-rw-rw-r-- 1 hak hak 129 Jan  8 18:56 archive.zip
---------- 1 hak hak  11 Jan  8 18:56 hello.txt
```
The extracted file `hello.txt` does not have any permission flags and does not honor the umask.

This was encountered during some CI/CD job that zips some builds, where the behavior changed on the latest versions, but the work around was as simple as, just resetting the correct permissions as needed. So, nothing really critical.

### Minimal reproduction project (MRP)

[zipbug.zip](https://github.com/godotengine/godot/files/13864737/zipbug.zip)

**Comment by Calinou** [comment]
cc @timothyqiu
