### ISSUE TITLE
Global Methods from Godot Namespace are not found or not exist in C#

### ISSUE THREAD

**Issue by Sfoyarbide** [godotengine/godot#86965]
### Tested versions

- Reproducible in v4.2.1.stable.mono.official [b09f793f5].

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

The global methods from the Godot Namespace not exist or are not found. An example that I am aware of is GetGlobalMousePosition(). 

As you can see from these tutorials from the official documentation of Godot (in the C# code tab), should be possible to use it as Global Method from the Namespace of Godot, like GDscript works.

[Godot Documentation Example 1
](https://docs.godotengine.org/en/stable/tutorials/2d/2d_movement.html#rotation-movement-mouse)
[Godot Documentation Example 2
](https://docs.godotengine.org/en/stable/tutorials/scripting/instancing_with_signals.html#shooting-example)

Here is a screenshot of the problem in the Text Editor:
![image](https://github.com/godotengine/godot/assets/63980929/0d1d11f7-a335-4fca-a386-37e35eaa3a18)

Here is a screenshot ather trying to build:
![image](https://github.com/godotengine/godot/assets/63980929/02ea871f-9497-48a2-8a62-ef19b08db65b)

Here is where I tested the previous problem.
```
using Godot;

public partial class Player : CharacterBody3D
{
    public override void _Ready()
    {
        Vector3 globalMousePosition = GetGlobalMousePosition();
    }

```

### Steps to reproduce

1. Create a C# Script
2. Write the method GetGlobalMousePosition().

### Minimal reproduction project (MRP)

N/A

**Comment by bs-mwoerner** [comment]
`GetGlobalMousePosition()`/`get_global_mouse_position()` is not a global method. Those examples you referenced inherit it from `CanvasItem` (there's an implicit `this.` there). `CharacterBody3D` is not derived from `CanvasItem` and does not inherit this method.

**Comment by Sfoyarbide** [comment]
I see, my bad. Thank you for your explanation and for your patience. May I ask how then I should obtain in a 3D environment, the Global Mouse Position?

**Comment by AThousandShips** [comment]
There's no way to do that, as far as I know, you can use `GetWindow().GetMousePosition()`

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), and the documentation, this is for bug reporting, not a help desk. 🙂

**Comment by Sfoyarbide** [comment]
My bad again, It won't happend again.

**Comment by AThousandShips** [comment]
No worries, but better place to get general support! Happy to help 🙂
