### ISSUE TITLE
AudioFrame parameter name mismatch

### ISSUE THREAD

**Issue by aiaimimi0920** [godotengine/godot#86986]
### Tested versions

last code ： [84e205b](https://github.com/godotengine/godot/commit/84e205b5a17bfe7ace96b78c410ec10aa52241d2)

### System information

windows 11

### Issue description

I think AudioFrame parameter name mismatch,

in this code: https://github.com/godotengine/godot/blob/84e205b5a17bfe7ace96b78c410ec10aa52241d2/core/math/audio_frame.h#L55C1-L55C1
```
struct AudioFrame {
	//left and right samples
	float l = 0.f, r = 0.f;
}
```

the param name is l and r, 

but in this code:
https://github.com/godotengine/godot/blob/84e205b5a17bfe7ace96b78c410ec10aa52241d2/core/register_core_types.cpp#L295
```
GDREGISTER_NATIVE_STRUCT(AudioFrame, "float left;float right");
```
the param name is left and right, 

I think you need to modify one of them? If necessary, I can provide PR

### Steps to reproduce

null

### Minimal reproduction project (MRP)

null

**Comment by akien-mga** [comment]
Does this actually cause an issue using the GDExtension strucut, or is that just a code consistency issue?

**Comment by aiaimimi0920** [comment]
@akien-mga 
Sorry, I'm not sure if this will trigger a problem. 
However, inconsistent commands are not conducive to the development process. In my understanding, the variable names of the classes provided by godot and godot cpp should be consistent

I am developing my plugin, and the code currently generated through godot cpp is
`thirdparty\godot-cpp\gen\include\godot_cpp\classes\audio_frame.hpp`

```
#ifndef GODOT_CPP_AUDIO_FRAME_HPP
#define GODOT_CPP_AUDIO_FRAME_HPP

#include <godot_cpp/core/method_ptrcall.hpp>

namespace godot {

struct AudioFrame {
	float left;
	float right;
};

GDVIRTUAL_NATIVE_PTR(AudioFrame);

} // namespace godot

#endif // ! GODOT_CPP_AUDIO_FRAME_HPP
```

but in godot core cpp, the code is 
```
struct AudioFrame {
	//left and right samples
	float l = 0.f, r = 0.f;
}
```

Because AudioFrame is an internal type, it is not easy to test. Sorry for not providing valid test cases

**Comment by AThousandShips** [comment]
Could use a union:
```cpp
union {
    float l;
    float left;
};
```
Unless I'm mistaken

**Comment by AThousandShips** [comment]
This would also fix some other parts of the code tbh, will look at a PR for it
