### ISSUE TITLE
The CollisionShape3D ConcavepolygonShape3D mesh is mostly useless .

### ISSUE THREAD

**Issue by Lklklklk1** [godotengine/godot#86981]
### Tested versions

404

### System information

Windows 10 Godot Engine v4.0.4.stable.custom

### Issue description

The CollisionShape3D ConcavepolygonShape3D mesh is mostly useless, needs some guidance to get this working and how to get the mesh to work with the animation

### Steps to reproduce

![Screenshot (38)](https://github.com/godotengine/godot/assets/155923329/ada77d72-34ef-494b-b93d-20c6fe51ddb1)
![Screenshot (42)](https://github.com/godotengine/godot/assets/155923329/00203c41-74e0-4738-a6fc-a11660f1045c)

### Minimal reproduction project (MRP)

N/A

**Comment by Zireael07** [comment]
This is not a place to ask for assistance, use other community channels for that.

**Comment by Lklklklk1** [comment]
> This is not a place to ask for assistance, use other community channels for that.

This is a bug, the function barely works, I tried setting collision and it didn't work
![Capture](https://github.com/godotengine/godot/assets/155923329/c72d126f-9f64-47d4-982c-2255546015f5)

**Comment by Zireael07** [comment]
Again, most likely you're using it wrong. Concave shapes cannot collide with many other shape types, this is a known limitation.
