### ISSUE TITLE
the first UI is not showing correctly

### ISSUE THREAD

**Issue by sdproyi** [godotengine/godot#87005]
### Tested versions

4.2v

### System information

Windows 11 pro, x86, Vulkan, Processor Intel(R) Core(TM) i7-10510U CPU, System type 64-bit operating system,  Intel(R) UHD Graphics, NVIDIA GeForce MX250  Driver version: 26.21.14.4120 DirectX version: 12 (FL 12.1)

### Issue description

This is the structure of CanvasLayer and you can see that the first button doesn't follow the character ![Screenshot 2024-01-09 144548](https://github.com/godotengine/godot/assets/71813700/e5156c50-b196-415a-b29e-ec6b4f6a0ce5)
![image](https://github.com/godotengine/godot/assets/71813700/b57b08a4-3b6f-48f6-9866-a0f5552b5057)
![image](https://github.com/godotengine/godot/assets/71813700/de3605a1-f575-4f60-afc1-763219d441d0)

### Steps to reproduce

CanavasLayer with any button in a moving scene should make the first button to not follow

### Minimal reproduction project (MRP)

[.godot.zip](https://github.com/godotengine/godot/files/13874663/default.godot.zip)

**Comment by bs-mwoerner** [comment]
You uploaded the project's .godot folder, which contains only temporary data. Could you instead upload the project folder of your MRP (the one containing the .godot folder), preferably without the .godot folder? Thanks!

**Comment by sdproyi** [comment]
> Friendship ended with Forward and Mobile renderers, now Compatibility renderer is your best friend See #58314 I'm so trained now that I can recognize this bug by smell :D

![image](https://github.com/godotengine/godot/assets/71813700/db989c8f-b1a4-4a34-a4af-6c45805e8993)
interesting it works on compatibility renderer

**Comment by sdproyi** [comment]
![image](https://github.com/godotengine/godot/assets/71813700/e04f2687-9528-4796-bacd-c6d398bcb7a1)
INTERESTING so after changing folder (copy paste everything) it works again so I guess the issues is when u switch between mobile, forward, compability

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/58314.
