### ISSUE TITLE
NOTIFICATION_APPLICATION_FOCUS_IN/OUT does not work in web exports on browser losing focus

### ISSUE THREAD

**Issue by Algorithmus** [godotengine/godot#87014]
### Tested versions

Reproducible in 4.2.1.stable
Not reproducible in 3.5 and earlier (with `NOTIFICATION_WM_FOCUS_IN/OUT`)

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 16:20:41 +0000 - Tty - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 (nvidia; 545.29.06) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When detecting whether or not there is app focus on desktop builds, `NOTIFICATION_APPLICATION_FOCUS_IN/OUT` works as intended. It doesn't work in web builds though when the browser loses focus.

If there's another notification event I'm supposed to be listening on, I haven't found it or it hasn't been documented properly.

### Steps to reproduce

Have a pause screen somewhere that shows up when the app loses focus or print it somewhere so that it's obvious this is happening.
```
func _notification(what):
	match what:
		MainLoop.NOTIFICATION_APPLICATION_FOCUS_OUT:
			get_tree().paused = true
			...do stuff on focus out
		MainLoop.NOTIFICATION_APPLICATION_FOCUS_IN:
			get_tree().paused = false
			...do stuff on focus in
```

Run this code in desktop. Works as expected. Tree pauses on focus out and resumes on focus in.

Run it in web export. Nothing happens when the browser loses focus. Tried it with changing tabs, switching to another app, changing workspaces, nothing happens.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Your description lists `NOTIFICATION_APPLICATION_FOCUS_IN/OUT` but the title lists `NOTIFICATION_WM_FOCUS_IN/OUT`, which is it?

The former is only supported on desktop, not inluding Web

**Comment by Algorithmus** [comment]
> Your description lists `NOTIFICATION_APPLICATION_FOCUS_IN/OUT` but the title lists `NOTIFICATION_WM_FOCUS_IN/OUT`, which is it?
> 
> The former is only supported on desktop (as you can see in the documentation), not inluding Web AFAIK, and isn't the same as the latter, which is a distinct notification, can you try that one in 4.x? It is still there
> 
> Edit: updated the title to match the example code

No, it's not there anymore. There is `NOTIFICATION_WM_ABOUT` which is something else. The editor claims it can't find `NOTIFICATION_WM_FOCUS_IN/OUT` and won't build.

**Comment by AThousandShips** [comment]
My bad I meant `NOTIFICATION_WM_WINDOW_FOCUS_IN/OUT`, though it seems the 3.x version maps to the application version, however the application version isn't supported on Web, as per the documentation

**Comment by Algorithmus** [comment]
> My bad I meant `NOTIFICATION_WM_WINDOW_FOCUS_IN/OUT`, though it seems the 3.x version maps to the application version, however the application version isn't supported on Web, as per the documentation

It doesn't find that either.

**Comment by AThousandShips** [comment]
It's there, right in `Node`, see [here](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-constant-notification-wm-window-focus-in)

**Comment by Algorithmus** [comment]
Okay, that works, thanks.
