### ISSUE TITLE
Parallax Background messes with rendering *on some computers*

### ISSUE THREAD

**Issue by bibizu** [godotengine/godot#87017]
### Tested versions

- Reproducible in all versions tested, which includes v4.0.0, v4.1.1, v4.2.1, v4.3 Dev 1

### System information

Godot v4.3.dev1 - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 630 () - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

This ONLY occurs on forward+ rendering, and it works as intended with compatibility rendering.
It seems to exclusively be a rendering issue, as positions print out correctly for the camera and polygon. This is supported by the fact that different behaviors occur when only changing z index of some elements, and the fix mentioned above.

It is a complicated issue, but my guess is for some reason, on forward+ rendering, the system has an issue with rendering one or more of the sprites in the tree after the parallax sprite. The issue is visible in the editor as well.

In the MRP, the intended and expected behavior is the white square oscillating back and forth, staying in the center of the camera, as the parallax sprite and the background sprite stay stationary. This was captured using compatibility rendering:

https://github.com/godotengine/godot/assets/104801209/23eb4dcd-86a6-4d1c-bc9c-3116f2611dad

Running the MRP using forward+ rendering gives this--notice how the white square suddenly jumps to the top of the screen when the parallax sprite enters the camera window, and how intended behavior is observed when the parallax sprite leaves the window:

https://github.com/godotengine/godot/assets/104801209/8be07108-5471-45d4-a1ae-8bad8eb190ec

Changing the z-index of the "Background" node to -1 in the MRP gives a different behavior, where the white square does not even render (which seems to be a separate issue entirely, but more testing is needed), but the background sprite now also renders incorrectly when parallax sprite is within view:

https://github.com/godotengine/godot/assets/104801209/a459a605-579b-48e3-8760-0f56471c03f9

Making the parallax sprite invisible removes the issue entirely, confirming that the issue lies there.

### Steps to reproduce

This issue is strange as I and several others cannot reproduce the issue on different devices -- the MRP, for example, only has the issue on my PC, and runs fine on my laptop. If you check my issue history, you can see I have had system exclusive shader loading issues before that have since been fixed, so it might be related to that as well. I hope to be able to find someone that can reproduce the issue.

The MRP should showcase the issue if it exists on that specific computer. Default values are used everywhere except for sprite scale and color, so creating an identical tree is quick and produces the same result.

### Minimal reproduction project (MRP)

MRP is in version v4.3 Dev 1

[MRP_Parallax.zip](https://github.com/godotengine/godot/files/13878743/MRP_Parallax.zip)

**Comment by Sauermann** [comment]
This sounds very similar to #58314 which is caused by integrated intel GPUs.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82380.
