### ISSUE TITLE
Can't add description to a node created via `add_custom_type()`

### ISSUE THREAD

**Issue by synalice** [godotengine/godot#87036]
### Tested versions

- **Reproducible in:** v4.2.1.stable.official [b09f793f5]
-  **Reproducible in:** v4.3.dev1.official [9d1cbab1c]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.21029.1006) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

There is no way to add description to a Node created via plugin. See MRP.

### Steps to reproduce

In MRP try to create a new node and look at description box:

![image](https://github.com/godotengine/godot/assets/61655860/60901fd6-afa0-453d-8ed7-8bf202964c60)
![image](https://github.com/godotengine/godot/assets/61655860/fd5a1239-8dc2-43c3-a942-475b7725dbd0)
![image](https://github.com/godotengine/godot/assets/61655860/6603333d-8cc6-4dd2-b0ae-31065e991df9)
![image](https://github.com/godotengine/godot/assets/61655860/74b9d93a-68b7-49c6-a283-1baf6123d5d1)

### Minimal reproduction project (MRP)

[IssueWithDescriptions.zip](https://github.com/godotengine/godot/files/13886383/IssueWithDescriptions.zip)

**Comment by YuriSizov** [comment]
This is correct, as `add_custom_type()` is a legacy type system. For modern features you need to use class named scripts.

**Comment by synalice** [comment]
> This is correct, as `add_custom_type()` is a legacy type system. For modern features you need to use class named scripts.

Are you saying `add_custom_type()` is deprecated and only exists for backwards compatibility? A warning from an editor could have been useful. This is a first time I hear this.

I guess the issue is solved then.

**Comment by YuriSizov** [comment]
> Are you saying `add_custom_type()` is deprecated and only exists for backwards compatibility?

We have never officially deprecated it because it has one feature that class named scripts in plugins do not: you can unregister custom type classes if your plugin is disabled. But it is indeed an older system which predates typed GDScript. It is only supported as is right now.
