### ISSUE TITLE
Viewport transparent background doesnt work

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8703]
**Operating system or device - Godot version:** Linux, Godot Master

**Issue description:**
Rendering a viewport to a texture having the transparent flag on doesn't render a transparent image. There is always a grey background that occupies the entire viewport.
I tried with several different options (own world, setting up a new world environment, etc), but the background is always there.

**Comment by reduz** [comment]
I added this a few days ago, so closing

**Comment by nunodonato** [comment]
Still doesn't work for me. 
Also related, it seems to be vertically flipped, regardless of that property value
