### ISSUE TITLE
Godot 4.2.1 immediately asks for declared Android permissions upon launch.

### ISSUE THREAD

**Issue by blurrred** [godotengine/godot#87043]
### Tested versions

Bug is present in 4.2.1, absent in 4.1.1.

### System information

Godot v4.2.1.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu Dec 21 16:21:45 UTC 2023 - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU () - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Android apps should ask the user for permission when `OS.request_permissions()` is called.
Permissions are immediately asked upon installation/launching of the app, which is incorrect behavior.

### Steps to reproduce

Set up project for Android exporting.
Add permissions that will prompt the user, such as ACCESS_FINE and COARSE locations (use both for API compatibility reasons).
Observe how the permissions are asked for immediately upon launching the app. This does not occur in Godot 4.1.1, and rightfully so.

### Minimal reproduction project (MRP)

[Permissions Test 4.2.1.tar.gz](https://github.com/godotengine/godot/files/13890230/Permissions.Test.4.2.1.tar.gz)
[Permissions Test 4.1.1.tar.gz](https://github.com/godotengine/godot/files/13890231/Permissions.Test.4.1.1.tar.gz)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
It's an intentional behavior added in [`GodotActivity`](https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/platform/android/java/lib/src/org/godotengine/godot/GodotActivity.kt#L70) to request dangerous permissions on app start.

**Comment by Calinou** [comment]
> It's an intentional behavior added in [`GodotActivity`](https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/platform/android/java/lib/src/org/godotengine/godot/GodotActivity.kt#L70) to request dangerous permissions on app start.

For reference, this was added in https://github.com/godotengine/godot/pull/82614.

**Comment by tokengamedev** [comment]
> It's an intentional behavior added in [GodotActivity](https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/platform/android/java/lib/src/org/godotengine/godot/GodotActivity.kt#L70) to request dangerous permissions on app start.

Is it not against the best practices of android permissions that, the app/game needs to explain why it needs the permission, before asking for permission. Also, it should ask permission when it is required.
If user declines two times, the permission request dialog will not come up anymore, and the app/game cannot do anything about it anymore.

**Comment by AdriaandeJongh** [comment]
I very much agree with the OP and @tokengamedev that this should be considered a bug and not 'a feature that should be documented'. Developers should have the opportunity to pop these permission dialogs when they want instead of it being forced at start, so if a recent PR changed that behavior, I would call that a regression as @Calinou originally labeled this issue as.

**Comment by blurrred** [comment]
Yes, this is *entirely* against Google's recommending practices for requesting permissions.
Here's a guide that outlines how developers should implement permissions in their apps: https://developer.android.com/training/permissions/requesting#principles

First principle: "Ask for a permission in context, when the user starts to interact with the feature that requires it."

Please give developers the option to ask for permissions when appropriate.

**Comment by m4gr3d** [comment]
Thanks for the feedback all!

The feature is being reverted in https://github.com/godotengine/godot/pull/87080 which will restore the behavior in Godot 4.1

**Comment by tokengamedev** [comment]
> The feature is being reverted in https://github.com/godotengine/godot/pull/87080 which will restore the behavior in Godot 4.1

Thanks for listening to our feedbacks ❤️ .  Appreciate the change done. 👍
