### ISSUE TITLE
Dynamically created GDScripts don't work in @tool mode

### ISSUE THREAD

**Issue by brombres** [godotengine/godot#87046]
### Tested versions

- Reproducible in 4.2.1.stable (but does not crash editor)
- Reproducible in 4.3.dev1 (crashes editor after a two scene reloads)

### System information

Godot v4.3.dev1 - macOS 14.0.0 - Vulkan (Mobile) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

Dynamically creating a GDScript and assigning it to an object works fine at runtime but not in `@tool` mode. Here is a minimal example:

```
@tool
extends Node2D

func _ready():
	var source = """
extends RefCounted

func execute():
	print("success")
"""

	var gdscript = GDScript.new()
	gdscript.source_code = source
	gdscript.reload()

	var object:RefCounted = RefCounted.new()
	object.set_script( gdscript )
	prints( "has execute():", object.has_method("execute") )
	object.execute()
```

Here is the output when `@tool` is commented out and the app is run:
```
has execute(): true
success
```

Here is the output in `@tool` mode (an error bullet followed by a single line of console output):

- res://Test.gd:19 - Invalid call. Nonexistent function 'execute' in base 'RefCounted (-9223370345912668691.gd)'.

```
has execute(): true
```

Furthermore, 4.3-dev1 crashes if reloaded twice when `@tool` is enabled. 4.2.1 has the same bug but does not crash.

### Steps to reproduce

1. Open the MRP.
2. Observe the single line of output confirming that the `execute()` method exists. 
3. Observe the absence of the second line of output and the unexpected error similar to this: "res://Test.gd:19 - Invalid call. Nonexistent function 'execute' in base 'RefCounted (-9223370345912668691.gd)'".
4. Comment out `@tool` and reload the scene.
5. Run the app and observe the script works as expected.

### Minimal reproduction project (MRP)

[DynamicTest.zip](https://github.com/godotengine/godot/files/13890363/DynamicTest.zip)

**Comment by kleonc** [comment]
Your dynamically created script is not annotated with `@tool` itself hence it not running in the editor is correct/expected. Adding `@tool` to its source makes it work/run within the editor:
```gdscript
@tool
extends Node2D

func _ready():
	var source = """
@tool # <------------------------ADDED------------------------
extends RefCounted

func execute():
	print("success")
"""

	var gdscript = GDScript.new()
	gdscript.source_code = source
	gdscript.reload()

	var object:RefCounted = RefCounted.new()
	object.set_script( gdscript )
	prints( "has execute():", object.has_method("execute") )
	object.execute()
```

**Comment by brombres** [comment]
@kleonc - confirmed, that solves the issue. Thank you! Closing this issue.
