### ISSUE TITLE
Android 14: white stripe is displayed on top of the screen during game load

### ISSUE THREAD

**Issue by BZ1234567890** [godotengine/godot#87059]
### Tested versions

Reproducible in 3.5.3 stable

### System information

Android 14, Samsung Galaxy A32

### Issue description

Immediately after the splash screen and before the game loads, there is a short period where a black screen with a white stripe on top of the screen is displayed. On older versions of Android (e.g., Android 13), there was only a normal black screen shown while the game is loading. The white stripe on the top of the screen should not be there during game load.

![Screenshot_20240110_202343_In Sync](https://github.com/godotengine/godot/assets/39430507/ee965a7a-dc7c-48d7-8097-9a341acf9468)

### Steps to reproduce

1. Create a new project in Godot
2. Run it on an Android device

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Which rendering method are you using in the project (Mobile or Compatibility)?

**Comment by BZ1234567890** [comment]
> Which rendering method are you using in the project (Mobile or Compatibility)?
> 
> I don't have Android 14 on a device yet, so I can't test this.

This is on Godot 3.5.3 stable. I don't know it has Mobile/Compatibility rendering methods?

Instead, I suspect this has to do something with the Android themes that Godot 3.5.3 uses...

**Comment by bpfliegel** [comment]
Getting the same. Godot 3.6 beta 3. Android 14 - issue was not present on Android 13. Samsung Galaxy A23.

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by BZ1234567890** [comment]
I checked the latest master (Godot 4) branch, and there seems to be okay (there is no white stripe). Does anyone who has worked on Godot 4 know how they fixed this in Godot 4, so that we can back-port the fix to the 3.x branch?

**Comment by BZ1234567890** [comment]
After some digging into this issue, I found out that the white stripe on top of the screen is in fact a ```GodotEditText``` view that is added to the Godot's activity/fragment in function ```onVideoInit()``` in ```/platform/android/java/lib/src/org/godotengine/godot/Godot.java```.

This is a screenshot from the Android Studio's layout inspector that demonstrates the problem:

<img width="759" alt="Screenshot 2024-01-28 at 01 31 25" src="https://github.com/godotengine/godot/assets/39430507/83c669c5-485b-45e0-aeff-31f710ef0e5c">

The relevant code is this:

```
		// GodotEditText layout
		GodotEditText edittext = new GodotEditText(activity);
		edittext.setLayoutParams(new ViewGroup.LayoutParams(LayoutParams.MATCH_PARENT,
				(int)getResources().getDimension(R.dimen.text_edit_height)));
		// ...add to FrameLayout
		containerLayout.addView(edittext);
```

There are multiple solutions that seem to be suitable at the first glance. For example, setting background color to transparent as shown in the code snippet below seems to solve the problem.

```diff
		// GodotEditText layout
		GodotEditText edittext = new GodotEditText(activity);
		edittext.setLayoutParams(new ViewGroup.LayoutParams(LayoutParams.MATCH_PARENT,
				(int)getResources().getDimension(R.dimen.text_edit_height)));
		// ...add to FrameLayout
+		edittext.setBackgroundColor(Color.TRANSPARENT);
		containerLayout.addView(edittext);
```

There are other possible solutions (such as, setting alpha to zero, setting height to zero, etc.).

What is the purpose of this edit text in the splash screen?

If nobody has any objections, then I can prepare a pull request with the fix of setting the background color to transparent. 

Please let me know if anyone has a better solution.

**Comment by Calinou** [comment]
It's likely here for virtual keyboard handling, but I agree it doesn't need to be shown during the splash screen.

**Comment by BZ1234567890** [comment]
Cool. Okay. I'll prepare a fix. Godot 4 does not exhibit this problem (I've tested with the master branch), so this only applies to 3.x.
