### ISSUE TITLE
(Godot v4.2.1 Window) Godot crashes if you use a theme.tres add marginContainer values and edit them

### ISSUE THREAD

**Issue by Davitdon** [godotengine/godot#87055]
### Tested versions

Godot v4.2.1 stable Windows latest release 

### System information

Windows 11 Pro

### Issue description

Godot crashes if you use a theme.tres add marginContainer values and edit them

### Steps to reproduce

create a theme tres. create the margin container values, I added 5 to each of them, but any should work 

### Minimal reproduction project (MRP)

N/A

**Comment by YuriSizov** [comment]
Please provide a reproduction project and exact steps you took.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
