### ISSUE TITLE
AssetLib not Loading (repository configuration) In Godot 4?

### ISSUE THREAD

**Issue by BdahMagician** [godotengine/godot#87056]
### Tested versions

Trying to download from the assetlib in Godot 4, but its not working?? Im very beginner in Godot 4 and game dev in general. Please help??

### System information

Godot 4.1

### Issue description

Trying to download from the assetlib in Godot 4, but its not working?? Im very beginner in Godot 4 and game dev in general. Please help??

### Steps to reproduce

Trying to download from the assetlib in Godot 4, but its not working?? Im very beginner in Godot 4 and game dev in general. Please help??

### Minimal reproduction project (MRP)

Trying to download from the assetlib in Godot 4, but its not working?? Im very beginner in Godot 4 and game dev in general. Please help??

**Comment by arkology** [comment]
ATM godot website and asset library is  temporarily down. Just wait until they come back online.

**Comment by AThousandShips** [comment]
Indeed, the website is currently experiencing problems, this is not due to the website being broken but network related, closing as this is not something that was can fix

**Comment by gummycookie** [comment]
thank you!

**Comment by BdahMagician** [comment]
Thank you! I'm such a beginner and had no idea if it was software related or me-related ( if I was doing something wrong )
