### ISSUE TITLE
Code fold not remember state of the inside folds

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#87069]
### Tested versions

v3.6.beta3.official [21ab700f2]

### System information

w10 64

### Issue description

Code fold not remember state of the inside folds

![GIF](https://github.com/godotengine/godot/assets/19652075/589bef5f-68ef-419b-910a-b11a8f019cbe)

### Steps to reproduce

You can see the attached video to reproduce the problem

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/82032
