### ISSUE TITLE
Clip Children has weird behaviour with background image 

### ISSUE THREAD

**Issue by julianstys** [godotengine/godot#87060]
### Tested versions

- Reproducible in: 4.2.stable

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M2 Pro - Apple M2 Pro (12 Threads), also reproducible on Windows 10

### Issue description

I'm converting my project from Godot 3 to 4, and I've tried implementing a 2D sprite mask. Godot 3 implements this using PointLight2D, but Godot 4 needs to use a Sprite2D with Clip Children. But I get very strange behaviour when I have a background image behind the sprite mask, the mask copies the background image and moves around when moving the sprite mask or it's children around as well, even though the background image isn't a child of the mask. 

I've uploaded a preview video of what I mean as well as the sample project since it's hard to explain. This is only an issue when Clip Children is enabled. 

https://github.com/godotengine/godot/assets/36524720/29f6898e-159a-4ebd-aafd-e38842709a8d

### Steps to reproduce

I've uploaded the sample project, just move the mask, star and Label nodes around to see the issue. Also panning, and zooming in/out in the editor produces the same issue. 

### Minimal reproduction project (MRP)

[Godot_text_mask_bug.zip](https://github.com/godotengine/godot/files/13893952/Godot_text_mask_bug.zip)

**Comment by clayjohn** [comment]
Thank you for the report. This is a known issue and has an open report already: https://github.com/godotengine/godot/issues/75956

So I'll close this issue in favour of https://github.com/godotengine/godot/issues/75956 so we can track the issue in one place
