### ISSUE TITLE
Off-by-1 error in Camera2D + CanvasLayer logic

### ISSUE THREAD

**Issue by ThrosturX** [godotengine/godot#87074]
### Tested versions

Only reproduced in v4.2.1.stable.official [b09f793f5] ; no other versions tested.

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 30.0.101.1069) - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

The top-most `Sprite2D` in a `CanvasLayer` is moved as if it's not in the `CanvasLayer` when a `Camera2D` is active.

### Steps to reproduce

1. See MRP and run it
2. Double click on `HUD`
3. Rearrange the order of `Sprite2D` and `Sprite2D2` in the `HUD` scene
4. Run again, notice the other `Sprite2D` now moves instead of the one that moved last time

### Minimal reproduction project (MRP)

[Bug Testing.zip](https://github.com/godotengine/godot/files/13904387/Bug.Testing.zip)

**Comment by arkology** [comment]
ATM compatibility renderer is the solution
See https://github.com/godotengine/godot/issues/58314

**Comment by Sauermann** [comment]
Thank you for the report. Consolidating as a duplicate with #58314.
