### ISSUE TITLE
Godot 4.2 APK BUGS

### ISSUE THREAD

**Issue by orbiterFan** [godotengine/godot#87071]
### Tested versions

Godot 4.2.1 APK on smartphone with 2312 x 1080 screen res.

### System information

Android Godot 4.2 MOBILE

### Issue description

Using Android smartphone with screen res 2312 x 1080

Hi Devs

It has been a few weeks sinking in my teeth into Godot on Android and I am really impressed by the clean logic, useable editor, the GPL love, and the general experience for such a small footprint.

Just made my first contrib while editing on a smartphone, so you guys have now got a FULL ANALOG FPS based off two other projects on GAL. The project implements dual virtual joysticks. Needing some help how to post this project to GAL. Message me. Original thread -> https://forum.godotengine.org/t/gamepad-and-joystick-input-intensity-for-fps-with-soft-ranges/41045

I have run both Godot 3.5 and 4.2 for Android, and below is why I can't use 4.2 yet.

Godot 4.2 APK Issues 

1) When using bluetooth mouse, the keyboard is permanently hidden. Can't type at all. I gotta turn off Bluetooth, then the keyboard appears, them type, then turn on Bluetooth again. Godot 3.5 does not do this. It has a different quirk when using a mouse. See thread.

2) Some dialogue boxes spill beyond the window boundary. Can't click apply or cancel. Possible work around is to make  all dialogues scrollable or moveable (Linux style ALT + left mouse).

3) Launching the editor takes considerably longer than compared to Godot 3.5 APK.

4) Launching a project, whether from the project manager or the editor also takes considerably longer than Godot 3.5 APK.

5) Touch handles (editor joysticks) respond too slowly. Would be useful to have a quick slider for each (move and look) nearby that has x1, x2, x3, x4 to make moving and looking around a small or large scene more efficient. Would be very useful to set move speed separately from look speed.

6) Generally the editor is very functional, but if it had a magnifying glass widget for smaller screens, it could be very useable for little projects. I generally use a Bluetooth mouse, so in that scenario a magnifying widget would be very useful.

7) The graphics renderers have changed since Godot 3.5. In 3.5 there was GLES2 and GLES3. Can someone give me a breakdown of Godot 4.x MOBILE versus COMPATIBILITY. Would like to keep my little games highly optimised with broadest market access, so would like to use GLES2 as a benchmark. (Not concerned about FORWARD+ right now, since target platform is mobile(GLES2).

8) RUN launches the game is a seperate window. Launch is slow. Would be useful to RUN IN EDITOR as an option.

9) Can't resize any panels via touch, eg: Scene, Editor or Inspector. You can do this in Godot 3.5.

Hoping to port FULL ANALOG FPS from Godot 3.5 to 4.x when your current release becomes usable on Android.

### Steps to reproduce

As above.

### Minimal reproduction project (MRP)

Any.

**Comment by AdriaandeJongh** [comment]
I believe each issue will have to be its own separate issue here on Github for things to be properly tracked and managed by Godot contributors. More work for you, unfortunately, but that's how I believe things are handled here.

**Comment by AThousandShips** [comment]
Indeed, these needs to be separate issue reports, please make sure to search for existing issues before opening individual reports

**Comment by orbiterFan** [comment]
Thanks for the feedback.

**Comment by Calinou** [comment]
> Can someone give me a breakdown of Godot 4.x MOBILE versus COMPATIBILITY.

Mobile rendering method uses Vulkan, and has a feature set similar to 3.x GLES3.

Compatibility rendering method uses OpenGL ES 3.0, and has a feature set similar to 3.x GLES2. This is probably the one you want to use right now when targeting mobile platforms, given a lot of Android devices have broken Vulkan drivers.
