### ISSUE TITLE
Disabling shader cache gives _save_to_cache error in editor

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#87079]
### Tested versions

Reproducible in: 4.2.1

I also think it will happen in 4.2, 4.1.3, 4.1.2, 4.1.1, 4.1 but haven't tested there.

### System information

Windows 11 64-bit, Ryzen 5 5500U, 8GB RAM, Nvidia GTX 1650

### Issue description

Disabling shader cache from `Project -> Project Settings -> Rendering -> Shader Compiler -> Shader Cache -> Enabled` gives the error:

`_save_to_cache: Condition "f.is_null()" is true.`

Though, the game runs fine, but I keep getting this error.

The reason I'm disabling shader cache is because of the issue I had with 3D models not being rendered on certain Android devices. The fix to this issue was to disable shader cache, and doing this fixed the rendering problem. I had opened a issue (resolved now) for this earlier here - https://github.com/godotengine/godot/issues/86956

### Steps to reproduce

1. Download the MRP provided.
2. Extract the apk/project files to your desired location.
3. Open the project files using Godot.
4. Run `main.tscn`
5. Upon running, you'll see `_save_to_cache` error message shown 4 times.

### Minimal reproduction project (MRP)

[Android 3D Rendering Issue.zip](https://github.com/godotengine/godot/files/13905039/Android.3D.Rendering.Issue.zip)

**Comment by clayjohn** [comment]
Tagged as good first issue as it should be a quick fix. We are likely forgetting to check whether the cache is enabled before writing/reading to it at some point.
