### ISSUE TITLE
Xcode output console prints every message twice

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot#87073]
### Tested versions

Only tested with Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

Engine output and calls to `print()` produce two entries in the output log in Xcode. It's an inconvenience if you're debugging on iOS. I find myself regularly having to take measures to differentiate unique entries if the order and count of the entries matters.

![Screenshot 2024-01-11 at 14 45 03](https://github.com/godotengine/godot/assets/5611323/2c22f095-c2d3-4dce-a2e4-80f87dcc754a)

### Steps to reproduce

Build any project to iOS and run the game. Observe that the engine prints at startup are in the output twice.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Unsure if this is a Godot side issue, we don't send messages twice, so could be either a bug in xcode, or a configuration issue making it repeat or reuse a channel

**Comment by AdriaandeJongh** [comment]
Well, the Xcode projects I've exported from Unity don't print log entries twice, so it doesn't seem to be an Xcode bug. I have no idea where the fault lies.

**Comment by elinfame** [comment]
This is still happening in Godot 3.5, is there any chance that this fix can be backported into 3.6?
v3.5.3.stable.official [6c814135b], macOS 14.5
