### ISSUE TITLE
SSAO graphical issue with glitchy lines

### ISSUE THREAD

**Issue by honix** [godotengine/godot#8708]
**Operating system or device - Godot version:**
**OS:** Linux Arch 64
**Video:** Intel HD Graphics 5500
**Godot version:** Godot 3.0 custom self compiled from 6d0568d

**Issue description:**
SSAO draws glitchy lines. `Camera.Environment` with only ssao enabled. Same in editor and game-mode. There is shot without blur:

![godot-ssao](https://cloud.githubusercontent.com/assets/11596541/25894531/d5cd4d1c-3584-11e7-970d-b764e40bdc0c.png)

**Comment by akien-mga** [comment]
Does someone reproduce this issue on Windows or macOS?

**Comment by Calinou** [comment]
I can reproduce this on Intel HD Graphics 620 (i7-7500U) on Windows 10.

[Example project](https://github.com/godotengine/godot/files/1077810/test_gi.zip)

This happens regardless of the SSAO settings used.

**Comment by reduz** [comment]
Same hardware as Calinou, simple can't reproduce :\

**Comment by Shockblast** [comment]
Notebook HP 340 g1 (Intel Graphics HD 4400) can reproduce 
![ss](https://user-images.githubusercontent.com/5357217/27235473-fbc303f0-528e-11e7-9dd5-fc051d7d0f1a.jpeg)


PD: Godot alpha Unofficial Build 13 June in general is extreme slow in notebook (3 FPS approx)

**Comment by Calinou** [comment]
The screenshot above doesn't seem to display artifacts related to SSAO, but rather artifacts related to shadow bias being set to a slightly too low value (a mistake on my side while making the demo project).

> PD: Godot alpha Unofficial Build 13 June in general is extreme slow in notebook (3 FPS approx)

More recent builds should be much faster, as the OpenGL error spam was fixed on Intel on Windows.

**Comment by Shockblast** [comment]
> The screenshot above doesn't seem to display artifacts related to SSAO, but rather artifacts related to shadow bias being set to a slightly too low value (a mistake on my side while making the demo project).

wops! (i try same settings from screenshot adove).
![ss](https://user-images.githubusercontent.com/5357217/27242532-ac2fa1aa-52ab-11e7-9521-0487a1822396.jpg)

**Comment by reduz** [comment]
ssao seems fine in those pics, the scanline effect is indeed due to shadow
bias

**Comment by HummusSamurai** [comment]
Does that mean the issue is closed?

**Comment by honix** [comment]
I will recheck it today, and post a screenshoot.

**Comment by honix** [comment]
Same problem
**OS:** Linux Arch 64
**Video:** Intel HD Graphics 5500
**Godot version:** 3.0 July 4 nightly build
![ssao-s](https://user-images.githubusercontent.com/11596541/27859670-2be235d6-6182-11e7-9527-67d715e71617.png)
project - [ssao-test.zip](https://github.com/godotengine/godot/files/1124241/ssao-test.zip)

**Comment by reduz** [comment]
I tested on an Intel 520 and it works fine... wish I had older hardware to
test..

**Comment by novemberist** [comment]
Arch Linux, HD4000 (Mesa 17.1.4) also getting the scanline effect in Calinou's example project (and in the Material Tester demo). Increasing the SSAO bias setting indeed reduces or removes the effect, but the bias setting shouldn't be hardware/driver specific, should it? Because some people can run the Material Tester demo without the scanline effect and tweaking the bias setting. 

@honix Could you please upload your example project? I would like to try if I also get the glitchy lines.

**Comment by groud** [comment]
Should be fixed in current master. Could you check that ?

**Comment by novemberist** [comment]
Looks fine now.

![ssao_artifacts](https://user-images.githubusercontent.com/7927471/29604871-268f70fc-87e9-11e7-8e18-d1a83e27a668.png)

**Comment by akien-mga** [comment]
Are those red clouds of dots expected though?

**Comment by novemberist** [comment]
I think @Calinou used these exaggerated ssao settings (and the red color) on purpose in his example project for better visualization of the issue.

**Comment by groud** [comment]
> Are those red clouds of dots expected though?

I'm not the expert but I'd say yes. The really low value for the bias may cause that.

**Comment by gamergamesz** [comment]
ssao colour was changed here , blur option was turned off(blur has no slider) to such ssao

**Comment by honix** [comment]
Hm.. Can't build master or 591a892c to test. Maybe there is some working builds?
```
editor/editor_icons.cpp:1:10: fatal error: editor_icons.h: No such file or directory
```

**Comment by akien-mga** [comment]
@honix Run `git clean -fX` to remove your build artifacts and start from scratch.

**Comment by honix** [comment]
@akien-mga fresh ```git clone``` do the job.

![ssao-fixed](https://user-images.githubusercontent.com/11596541/29616676-ef6edd7e-881a-11e7-8a6e-5803ae0252f8.png)

It looks good for me. Blur option successfully reduces this noise.

I think issue is closed!
