### ISSUE TITLE
Warn as Error applies to Addons when executing addon-provided tools

### ISSUE THREAD

**Issue by dreed-sd** [godotengine/godot#87094]
### Tested versions

Reproducible in v4.2.stable.official [46dc27791]

### System information

MacOS - v4.2.stable.official [46dc27791]

### Issue description

If you want a warning as error, such as to enforce static type hints whenever possible, you can enable Untyped Declaration and Inferred Declaration as errors, for example. Thankfully Godot has a setting to ignore scripts in the addons directory, so you aren't bothered by code you don't typically control. This works fine.

However, it _does_ apply to addons when using a script provided by an addon on the command line. For example [GdUnit4](https://github.com/MikeSchulze/gdUnit4) provides a script to run unit tests from the command line, so CI servers can run tests:

```
./addons/gdUnit4/runtest.sh
```

Since this addon does not adhere to the rules I've enabled in my project, I cannot run this script without first disabling the settings.

### Steps to reproduce

1. Create a new Godot project
2. Install the `GdUnit4` addon available at: https://github.com/MikeSchulze/gdUnit4 (any addon would do, so long as it contains code you can run from the command line that has inferred types in it)
3. You will need to restart Godot due to other issues unrelated to this bug. The first import of the addon produces errors.
4. Enable the GdUnit4 addon in project settings.
5. Set `Untyped Declaration` and `Inferred Declaration` to `Error` in project settings.
6. Exit Godot
7. Execute a GdUnit4 utility from the command line: `GODOT_BIN=/Applications/Godot.app/Contents/MacOS/Godot ./addons/gdUnit4/runtest.sh`
8. The command line debugger will hit a stop. Type 'continue'.
9. --> Observe many violations of the inferred/untyped declaration rules in the addon's code.

### Minimal reproduction project (MRP)

[WarnAsErrorRepro.zip](https://github.com/godotengine/godot/files/13910468/WarnAsErrorRepro.zip)

**Comment by vnen** [comment]
> Additionally, I think its a good idea if you could report these warnings on the addon project too, as it is the addon's responsibility to ensure it doesn't cause warnings/errors in your project that then force you to have this workaround.

This issue is that you cannot really guarantee that for third-party code and you wouldn't want to be fixing their warnings. Because your warning settings might be different from theirs as well. As you can see, there is a project setting to show warnings on addons if you want to.

**Comment by rsubtil** [comment]
> This issue is that you cannot really guarantee that for third-party code and you wouldn't want to be fixing their warnings. Because your warning settings might be different from theirs as well. As you can see, there is a project setting to show warnings on addons if you want to.

Yes, I agree, and that's what I tried to convey with that comment; if there's warnings on an addon, it's not expected that the person using the addon must fix them, and options like ignoring addon warnings are needed on the project side.

But, ideally, the addon should not have any warnings at all, so its best to notify their developers when that happens, so they can hopefully fix it on their side.
