### ISSUE TITLE
Using undo shortcut doesn't work on Script Editor.

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#87101]
### Tested versions

Reproducible in : 352434668923978f54f2236f20116fc96ebc9173
not reproducible in : 4.2

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When pressing the shortcut it shows nothing to Undo even though there is clearly something as shown when doing undo through menu. 

https://github.com/godotengine/godot/assets/66184050/73675e7a-d2a5-4582-be80-94498016175a

### Steps to reproduce

- Open Script Editor
- Write something
- Press Ctrl + Z or whatever your undo shortcut
- it prints Nothing to undo
- go in menu Edit > Undo and it will properly Unod

### Minimal reproduction project (MRP)

N/A

**Comment by victorbstan** [comment]
It undoes changes in the scene editor instead of letting the focused script editor handle the undo...

**Comment by ajreckof** [comment]
So finally did bisect the regression #82900 seems to be the one that introduced this regresion

**Comment by samuelfine** [comment]
I'm also experiencing this issue in v4.3.dev3.official [36e943b6b], on multiple computers. Very eager to see the PR fix land (hopefully in 4.3.dev4?) as it's having a significant impact on my developer experience. I've accidentally Undo'd (undid?) editor changes while trying to Undo code changes in the Script editor at least a dozen or so times now. It's quite frustrating! 😞

**Comment by victorbstan** [comment]
@samuelfine are you sure? I've tested 4.3.dev3 on a Mac, traditional layout.

**Comment by samuelfine** [comment]
@victorbstan I can't confirm for 100% sure right now, but I'm 99% sure that I was indeed experiencing this bug in 4.3.dev3. (I copied the build details out of an open Godot project in which I was actively experiencing the bug, no other Godot versions running simultaneously.) Will test again later today to confirm, and will update my comments if I was mistaken!

**Comment by ajreckof** [comment]
This bug should be present in 4.3.dev3 as #82900 which introduced the regression was merged before 4.3.dev3. Whatever the case this is not really important as a fix has already been found

**Comment by ajreckof** [comment]
I can reproduce it again don't know how but it is back

**Comment by stuartcarnie** [comment]
When viewing the Script Editor, I can reproduce with ⌘+W (close), and undo / redo. Confirm it works on 4.2, but 4.3 dev 5, and building from master do not.

I am running macOS 14.4.1 on M1
