### ISSUE TITLE
Broken lighting on Collada mesh with normal map [Intel HD 3000]

### ISSUE THREAD

**Issue by khairul169** [godotengine/godot#8711]
**Operating system or device - Godot version:**
Ubuntu 16.04 - Intel HD 3000
Godot 3.0 custom from commit [6d0568d](https://github.com/godotengine/godot/commit/6d0568d8179f7dcca54b1c87ab199820a468ef2c)

**Issue description:**
Mesh imported from collada have a weird lighting.. But testcube are fine..
![screenshot from 2017-05-10 19-38-00](https://cloud.githubusercontent.com/assets/10296472/25899198/28066b48-35b9-11e7-9820-b749e8f27a36.png)

**Steps to reproduce:**
Create a simple mesh, uv unwrap, and export it with better collada exporter, with tangent arrays exported.. Give it material with normal map, and place some point light or directional light..

**Link to minimal example project:**
[Normal Map Test.zip](https://github.com/godotengine/godot/files/989749/Normal.Map.Test.zip)
normal map by Calinou btw

**Comment by bojidar-bg** [comment]
Are you sure that the normals of the mesh point outwards?

**Comment by bojidar-bg** [comment]
Related to #8673, #8004, #6440, and potentially a few others...

**Comment by khairul169** [comment]
yeah i'm sure about that
![screenshot from 2017-05-11 17-08-22](https://cloud.githubusercontent.com/assets/10296472/25944172/8a5d212a-366c-11e7-85b8-75adff0ed2f7.png)

**Comment by ippan** [comment]
commit a75623f
Mac Nvidia 755M
![s](https://cloud.githubusercontent.com/assets/2070604/26259575/33d20cee-3cfc-11e7-9b44-987df1830392.png)

**Comment by HummusSamurai** [comment]
Seems like the problem is solved?

**Comment by bojidar-bg** [comment]
Yes, but it would be nice if @khairul169 confirms so as well.

**Comment by khairul169** [comment]
Yeah with the latest commit, test project are works fine.. 👍 
Did i have to close this issue myself?

**Comment by akien-mga** [comment]
Great news :)
