### ISSUE TITLE
Images with big AtlasTextures are broken in systems with AMD GPUs

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#87119]
### Tested versions

4.2 stable

### System information

Windows 11 - 4.2 stable - AMD 7900xtx

### Issue description

For sprites embedded within large atlas textures, the visual gets corrupted. 

This issue only seems to occur with AMD GPUs, and not on any NVIDIA GPUs that have been tested. 

I've only been able to test and repro this with 'debug export' builds. 

Please export attached project and test on AMD GPU to repro. 

See attached video
![gpu_specs](https://github.com/godotengine/godot/assets/1243371/86592397-d67f-4edc-9ea6-7a16f72253fc)

### Steps to reproduce

https://github.com/godotengine/godot/assets/1243371/428f371e-5ae4-4940-83f4-d36c1bcb9eb5

![pc_specs](https://github.com/godotengine/godot/assets/1243371/93aa3f57-4864-49a5-9b10-f32cca0f6845)

### Minimal reproduction project (MRP)

[Sprite_Test.zip](https://github.com/godotengine/godot/files/13922078/Sprite_Test.zip)

**Comment by rsubtil** [comment]
Can confirm on my AMD setup, but also on a lowend Nvidia laptop.

I think this might actually be a hardware limit. Most graphics card can only go up to [16k resolution](http://vulkan.gpuinfo.org/displaydevicelimit.php?name=maxImageDimension2D&platform=all), and your image surpasses that. Both my GPUs can only work with 16k textures max. But I don't know how Godot handles this, whether it "cuts" image resolution down or not when working with atlas textures.

**Comment by quirkylemon** [comment]
if this is just a limitation of some graphics cards then it might be a good idea to add a warning in the editor. 
Also you might be able to fix the issue by making the texture atlas wider it is currently 2048 w x 16800 h

**Comment by AThousandShips** [comment]
The editor wouldn't work for this as it isn't helpful to just know the limitations of *your* hardware, you might end up running things on weaker hardware for example

See [here](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#texture-size-limits) for one recommendation, which your texture goes far over

Could you check the result of `RenderingServer.get_rendering_device().limit_get(LIMIT_MAX_TEXTURE_SIZE_2D)`?

**Comment by LakshayaG73** [comment]
This is interesting. 

The result I get is `32768`

I mainly use these huge atlases for the sake of convenience. One file, one enemy, done. That sort of a thing. 

I can split these up, the VRAM usage shouldn't increase *too* much. Let me try that.

**Comment by AThousandShips** [comment]
But you need to keep in mind the range of hardware you could run it on, granted the 8k suggestion is seemingly a bit out of date, but it's still a good safe suggestion I'd say, note that the numbers there aren't always representative due to duplicates etc.

So I'd suggest to at least restrict yourself to the 16k, and preferably lower to be able to cover more targets, don't rely on the things your own hardware can manage, it's hard to plan and test, but it's good to be conservative when you're able

**Comment by rsubtil** [comment]
To complement @AThousandShips's point, 16k textures are absolutely massive even for today's standards. Unity only [supports 16k as maximum size](https://docs.unity3d.com/ScriptReference/SystemInfo-maxTextureSize.html#:~:text=The%20largest%20texture%20width%20and,if%20you%20have%20enough%20memory.) too, and Unreal Engine is even lower at [8k textures](https://docs.unrealengine.com/5.0/en-US/texture-format-support-and-settings-in-unreal-engine/).

Using the AtlasTexture is not the wrong approach; your base image resolution is simply too big.

**Comment by AThousandShips** [comment]
Didn't realize that this was related to the generation of atlas textures from multiple input files, so this might be something to look into as a configuration thing to allow wider but less tall textures, as the current setup limits the width to `2048`, that would be something to discuss as an actionable change here

**Comment by AThousandShips** [comment]
Opened a draft PR for this, it works basically well, but needs some testing and discussion, let's keep the general topic here

With this PR and modifying the setting to `4096` the resulting texture is much more useful, forget the exact result but the height was somewhere around `7000`

**Comment by Calinou** [comment]
The `2048` limitation is definitely out of date nowadays as even low-end mobile devices support 4096×4096 textures, but I believe we have to keep it nonetheless to preserve compatibility.

**Comment by LakshayaG73** [comment]
@AThousandShips possible regression for this in 4.3? 

Some of my user's atlas textures are not respecting the new property that was introduced.

**Comment by AThousandShips** [comment]
Please open a new report, as this would be a different issue
