### ISSUE TITLE
GodotSharp deadlock in RemoveScriptBridge / CreateScriptBridgeForType on scene transition

### ISSUE THREAD

**Issue by DavidVonDerau** [godotengine/godot#87127]
### Tested versions

- Occurs in: v4.2.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

I believe this is a race condition between `GodotObject` `Dispose` and `load_threaded_request` but I'm not certain.

Very rarely on a scene transition where a new scene with C# scripts is loaded in the background using `load_threaded_request`, while simultaneously 1 or more Nodes with C# scripts has been `QueueFree()`'d from the `SceneTree`, the project will deadlock. 

A `GodotObject` calling `Dispose` (one of the nodes that had `QueueFree` called) will block on removing the attached C# script, while the new scene that is being loaded in the background will block on creating a new C# script.

The call stack for all threads looks like:
![image](https://github.com/godotengine/godot/assets/4888530/6ebea8c1-97ec-4223-ac2d-e287faaf5c4c)

### Steps to reproduce

The following is a hypothesis because I'm having trouble narrowing this down.
I'm mostly working off the stack trace above and looking at what my code is doing during the scene transition, but it's _possible_ that the actual issue is caused by something entirely unrelated.

1. Create a "scene container" master scene.
2. Create a function to transition scenes -- `QueueFree()` the current scene node, `load_threaded_request` the new scene, and then `Instantiate` + `AddChild` when the threaded request is complete.
3. Using two scenes that both have Nodes with C# scripts attached, transition repeatedly between the scenes.
4. **Rarely** the entire application will permanently deadlock during the transition on the stack trace shown above.

### Minimal reproduction project (MRP)

N/A (I haven't figured out the MRP steps yet)

**Comment by d6e** [comment]
This might be the same issue as this https://github.com/godotengine/godot/issues/87405

which apparently should be fixed in Godot 4.2.2: https://github.com/godotengine/godot/pull/87669

**Comment by akien-mga** [comment]
@DavidVonDerau Could you confirm whether 4.2.2-rc2 fixes the issue?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
