### ISSUE TITLE
GetNoise2D generates values above 1.0

### ISSUE THREAD

**Issue by jerbrisebois** [godotengine/godot#87120]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Sometimes GetNoise2D will generate values above 1.0. This should only return values between -1.0 and 1.0. I have seen values as high as 1.92.

### Steps to reproduce

Use the following code to see the issue

```
        _noiseTest = new FastNoiseLite();
        _noiseTest.NoiseType = FastNoiseLite.NoiseTypeEnum.Cellular;
        _noiseTest.Seed = 55418;
        _noiseTest.Offset = new Vector3(0, 0, 0);
        _noiseTest.Frequency = 0.5f;
        _noiseTest.FractalType = FastNoiseLite.FractalTypeEnum.None;
        _noiseTest.CellularDistanceFunction = FastNoiseLite.CellularDistanceFunctionEnum.Hybrid;

        Vector2 sampleCoords = new Vector2(3, 15);
        float noiseSample = _noiseTest.GetNoise2D(sampleCoords.X, sampleCoords.Y);
        GD.Print($"Value of {noiseSample} using seed {_noiseTest.Seed} with offset {_noiseTest.Offset} at coords {sampleCoords.X}, {sampleCoords.Y}");
```
        
 Note: This happens with many values for seed, offset and coordinates. I simply took one example to reliably reproduce. This may occur with other NoiseTypes and parameters as well.

The MRP is a C# project but I believe the problem to be easily-reproducible enough that if someone wanted to reproduce in GD script it would be trivial. I have not used GD script so I did not include it here.

### Minimal reproduction project (MRP)

[NoiseTest.zip](https://github.com/godotengine/godot/files/13922064/NoiseTest.zip)

**Comment by AThousandShips** [comment]
There's no guarantee it will return values in that range, where are you getting that it will be in this range?

**Comment by jerbrisebois** [comment]
> There's no guarantee it will return values in that range, where are you getting that it will be in this range?

https://docs.godotengine.org/en/stable/classes/class_noise.html

> Note: With normalize set to false, the default implementation expects the noise generator to return values in the range -1.0 to 1.0.

Am I misinterpreting this?

**Comment by jerbrisebois** [comment]
Did not mean to close

**Comment by jerbrisebois** [comment]
> It even says this in the documentation:
>Most generated noise values are in the range of [-1, 1], but not always. Some of the cellular noise algorithms return results above 1.

Could you clarify what documentation states this?

**Comment by AThousandShips** [comment]
[Here](https://docs.godotengine.org/en/stable/classes/class_fastnoiselite.html#class-fastnoiselite)

**Comment by jerbrisebois** [comment]
> [Here](https://docs.godotengine.org/en/stable/classes/class_fastnoiselite.html#class-fastnoiselite)

Thank you, closing
