### ISSUE TITLE
Error thrown when "<" or ">" is used in a file name.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#87134]
### Tested versions

v4.2.rc.custom_build [d34f1ec4b]

### System information

Windows 10

### Issue description

If you try to rename a file or create a file using these characters in the editor: `<>`
Godot will be unable to do so and throw load error popup:
```
Error Moving:
res://Scene.tscn
```

Could someone test if this is reproducible in later versions? ty.

### Steps to reproduce

N/A 
self explanatory.

### Minimal reproduction project (MRP)

N/A

**Comment by synalice** [comment]
Such special characters aren't supported on most operating systems. While Linux will allow you to use `<>` in filename, Windows will not.

You should strive to use only this `A–Z a–z 0–9 . _ -` set of characters to avoid any compatibility issues. This isn't a Godot issue at all.

**Comment by KnightNine** [comment]
@synalice oh ok! I didn't think windows would have such a restriction.
