### ISSUE TITLE
Tilemap editor adds extra pixel for odd numbered tile resolutions

### ISSUE THREAD

**Issue by IndieJoJo** [godotengine/godot#87138]
### Tested versions

Reproducible in Godot v4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

When adding a tilemap and setting layers with Reset to default tile shape, odd numbered tile resolutions like (9x9 and 5x5) have an additional pixel added which can mess with physics and navigation.
![image](https://github.com/godotengine/godot/assets/136153464/d318d84b-a25a-4d1d-99e7-3b281dd77468)

### Steps to reproduce

Try adding a layer and pressing reset to default tile shape for any odd numbered resolution.

### Minimal reproduction project (MRP)

[TilemapTest - Copy.zip](https://github.com/godotengine/godot/files/13927140/TilemapTest.-.Copy.zip)

**Comment by kleonc** [comment]
There are indeed truncations of floats to ints in few places resulting in incorrect offsets, PR fixing these incoming. AFAICT these affect only the debug drawing though.

---

What's a bigger problem is that `NavigationServer2D::bake_from_source_geometry_data` seems to produce incorrect navigation polygon.

Specifically here:
https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/editor/plugins/tiles/tile_data_editors.cpp#L2831-L2843
for a single outline `[(-2.5, -2.5), (2.5, -2.5), (2.5, 2.5), (-2.5, 2.5)]` it produces a navigation polygon with vertices `[(3.0, 3.0), (-3.0, 3.0), (-3.0, -3.0), (3.0, -3.0)]` (a single polygon with indices `[0, 1, 2, 3]`).

More specifically the rounding happens here when converting `Vector2` to `Point64`:
https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/modules/navigation/nav_mesh_generator_2d.cpp#L742-L745
https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/thirdparty/clipper2/include/clipper2/clipper.core.h#L165-L166
https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/thirdparty/clipper2/include/clipper2/clipper.core.h#L144-L152

No idea why it's using `Point64` over [`PointD`](https://www.angusj.com/clipper2/Docs/Units/Clipper/Types/PointD.htm) etc. cc @smix8

**Comment by smix8** [comment]
That the 2D navigation mesh baking only works with integers and "full pixels" was a decision for performance and robustness.

In my early tests PointD was not only significantly slower but also had far more polygon errors and caused edge seam problems due to float errors.
