### ISSUE TITLE
Why does LightOccluder2D after a sprite can affect that sprite?

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#87146]
### Tested versions

- Reproducible in: 4.2.1.stable

### System information

Windows11 Vulkan API 1.3.260 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Hi, I tested LightOccluder2D according to the documentation, but I have questions about the performance of this LightOccluder2D.

[2D lights and shadows](https://docs.godotengine.org/en/stable/tutorials/2d/2d_lights_and_shadows.html#occluder-draw-order)

### Steps to reproduce

https://github.com/godotengine/godot/assets/14236891/b403153f-e4eb-4df5-ad94-2cbc3fe8a025

### Minimal reproduction project (MRP)

[LightTest.zip](https://github.com/godotengine/godot/files/13928214/LightTest.zip)

**Comment by AThousandShips** [comment]
What are you asking about? What's not working correctly?

For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. 🙂

**Comment by gnenux** [comment]
> What are you asking about? What's not working correctly?
> 
> For support questions and help please first turn to the other [community channels](https://godotengine.org/community), this is for bug reporting, not a help desk. 🙂

OK, thanks!
