### ISSUE TITLE
[3.0] Setting particles lifetime to 0 breaks the particle system

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8715]
**Operating system or device - Godot version:** Linux, Godot 3 master

**Issue description:**
Setting the 3d particles lifetime to 0 (even though the inspector will set it to 0.1), will render the particle node useless as no particles will be shown again.
Even after restoring all values to a default, nothing will be emitted again

**Steps to reproduce:**

1. Add a 3d particles node
2. Add any mesh to the draw pass and a particle material
3. Set particle lifetime to 0 
4. try to make it work again :)

**Comment by HummusSamurai** [comment]
Can confirm this also exists with 2.1x branch for 2D Particles.

**Comment by bojidar-bg** [comment]
Reopening because of #8775.
