### ISSUE TITLE
Built-in range function returns Array instead of Array[int]

### ISSUE THREAD

**Issue by rehhouari** [godotengine/godot#87152]
### Tested versions

- Reporducible in Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 3 4300GE with Radeon Graphics (8 Threads)

### Issue description

```gdscript
var array_of_indicies: Array[int] = range(7)
```

This throws an error:
```
Trying to assign an array of type "Array" to a variable of type "Array[int]".
```

It should be by default Array[int] because it is an array of integers.

My use case: I am looping that `array_of_indicies` and using the values as indicies to access elements of another array.

### Steps to reproduce

```
var array_of_indicies: Array[int] = range(7)
```

### Minimal reproduction project (MRP)

[range_typed_array.zip](https://github.com/godotengine/godot/files/13928792/range_typed_array.zip)

**Comment by AThousandShips** [comment]
This, while a reasonable change I'd say, would break compatibility, and wouldn't in my opinion be justified as there's nothing broken about it being unspecific

**Comment by rehhouari** [comment]
Thanks that's a good workaround and the compatibility part is understandable.
