### ISSUE TITLE
"Reload the played scene" (F6) is launching the currently focused tab, not reloading the previously selected scene

### ISSUE THREAD

**Issue by PatientLightning** [godotengine/godot#87163]
### Tested versions

Reproducible in 4.2.1 Stable
Not Reproducible in 4.0.4

### System information

Godot v4.2.1.stable - Windows 10

### Issue description

I recently upgraded from 4.0.4 to 4.2.1 and suddenly the reload button is launching the currently focused scene tab instead of the scene previously selected to run.

This behavior is different than before when it would reload the previously selected scene.

It is important for this button to work correctly so I can deliberately test a (not main) scene while using the editor tabs to update and fix other scenes that are part of it.
For example, the main scene of my project is a "Menu" scene but I am developing an "Arena" scene with a "Character" and a new "Obstacle".
I select the Arena and press the "Run Current Scene (F6)" button so I can test the interaction between the Character and the Obstacle
I then use the editor tabs to inspect and make changes to the child scenes.
Previously I would then press the "Reload the Played Scene" button to re-launch the Arena and test my updates, but instead it will launch the currently focused tab, be it the Character or Obstacle, which is not helpful for testing interaction.

Is there a setting somewhere that I've overlooked? Thanks

### Steps to reproduce

Pick a scene, launch it.
Switch a tab.
Try to relaunch the scene you picked.
Notice that it launches the currently focused tab instead.

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
I've identified the cause of this bug, will write a fix

**Comment by PatientLightning** [comment]
I pulled your fix and applied it to the 4.2.1-stable branch, built it, and it works like a charm. Thank you so much for knowing right where to look! Looking forward to seeing your fix merged for future releases.

**Comment by AThousandShips** [comment]
This hasn't been fixed yet so please leave it open until merge
