### ISSUE TITLE
Is it a bug ? I made a simple test, 150 vs150 characterbody3d simple running(jsuts use 2D AnimatedSprite3D), got very poor performance.

### ISSUE THREAD

**Issue by xiaqii** [godotengine/godot#87174]
### Tested versions

Tested on three computers. version 4.2.1.Forward+

### System information

Windows 11 - Godot v4.2.1 Vulkan(Forward+)

### Issue description

![image](https://github.com/godotengine/godot/assets/629248/a87a8a90-26f6-482f-8627-a1dc06445472)
![image](https://github.com/godotengine/godot/assets/629248/8625be78-a707-4acb-809e-c02a1b3d8d41)
![image](https://github.com/godotengine/godot/assets/629248/1b8bb553-5348-4c38-babf-549c08ad5dad)

### Steps to reproduce

I love an old game, [sega dragon force I ],
it is an old game, almost 25 years ago, has a 100vs100 war.
i try to study godot to build a war like this,
when the amount bigger than 140vs140, got a FPS under 20...
and when the amount less than 100vs100, got a FPS normal at 60.
It is not a linear descent, It happens suddenly when the number is higher than 120vs120~

### Minimal reproduction project (MRP)

hard to read and write english . :(

**Comment by AThousandShips** [comment]
Please provide the full system details

**Comment by smix8** [comment]
You need to learn how to optimize for an RTS game, because that used node setup here is the antithesis of performance optimization. Nodes like Label3D, CharacterBody3D or AudioStreamPlayer3D are all super-highcost nodes that you can use in a game with hero assets with <20 actors on screen at the same time but not in an RTS with 100+ actors.

**Comment by xiaqii** [comment]
Thank you , 
I'll try remove audio and change node types, to find whese's the most cost.
maybe I should just test move 400 cubes.
