### ISSUE TITLE
VisibleOnScreenNotifier3D does not work with gles3

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#87176]
### Tested versions

4.2.0, 4.2.1

### System information

Windows 10, Godot 4.2.1, Gles3 compatibility

### Issue description

`VisibileOnScreen*` nodes do not work with the compatibility renderer (gles3).  This is because the needed functions are not actually implemented for the gles3 renderer:

https://github.com/godotengine/godot/blob/26b1fd0d842fa3c2f090ead47e8ea7cd2d6515e1/drivers/gles3/storage/utilities.cpp#L254

This was working with godot 3.x so no idea why it isn't anymore.

### Steps to reproduce

- Put a VisibilityEnabler3D node into a scene
- switch to compatibility mode

### Minimal reproduction project (MRP)

-

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by kus04e4ek** [comment]
Closed by #88684

**Comment by clayjohn** [comment]
> Closed by #88684

Thank you! I could have sworn there was an issue for this, but I couldn't find it when I made the PR!
