### ISSUE TITLE
freed object crash ( cant check for it ) ?!

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#87188]
### Tested versions

Godot 4.3 dev 2 

### System information

windows 10 vulkan

### Issue description

- In 4.2, object showed has null
- Now in 4.3 when changing level it shows freed Object

![freeError](https://github.com/godotengine/godot/assets/77213594/164f4691-de52-44cc-8ae5-0ed456da9f95)

![freeError2](https://github.com/godotengine/godot/assets/77213594/5bbeab37-92cf-40d9-8c70-df435e06d9ad)

### Steps to reproduce

download the project...

[freedERROR.zip](https://github.com/godotengine/godot/files/13933007/freedERROR.zip)

### Minimal reproduction project (MRP)

[freedERROR.zip](https://github.com/godotengine/godot/files/13933006/freedERROR.zip)

**Comment by jonSP12** [comment]
fixed with is_instance_valid instead of check for null

**Comment by AThousandShips** [comment]
Closing as per above, as this is the intended way of doing this, thank you for your report, but in the future please use the other community channels to ask for support 🙂
