### ISSUE TITLE
Visual Glitch with Normal maps

### ISSUE THREAD

**Issue by StanleySweet** [godotengine/godot#87182]
### Tested versions

Reproducible in Godot Engine v4.2.1.stable.official

### System information

Windows 10 - Godot v4.2.1.stable - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia, 2215886848) -Intel Core i7-8750H @ 2.20GHz, 2.21 GHz 12 threads

### Issue description

https://github.com/godotengine/godot/assets/6837402/9c770e1a-f3bb-4505-a7de-290241dececf

As you can see in the video, the light mapping is incorrect for certain angles of the mesh especially if the uvs are mirrored like the middle object. All artefacts disappear when disabling the normal map, so probably something fishy there, or some requirement I did not understand.

The normal map was made in material maker.

There might be more information here 

https://t.co/qMGpObMbPM

### Steps to reproduce

Load the test project and open the scene  and notice it

[userreport_hwdetect.txt](https://github.com/godotengine/godot/files/13932758/userreport_hwdetect.txt)

### Minimal reproduction project (MRP)

[materials.zip](https://github.com/godotengine/godot/files/13932776/materials.zip)

**Comment by reduz** [comment]
I have the feeling we (or however we use the mikktspace?) are not deduplicating vertices, hence the normals in the mirrored area looking bad. Or maybe it may have to do with how the asset was exported? Worth researching at least.

**Comment by ettiSurreal** [comment]
Had some spare time so I did a bit of testing, disabling "Ensure Tangents" in the import settings seems to get rid of the artifacts, but the normal map is inverted on the back side of the mesh.

**Comment by StanleySweet** [comment]
Possibly related/duplicate of #86131

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/86131, as this is due to the same cause.
