### ISSUE TITLE
ClassDB::bind_method(D_METHOD ... under VisualStudio 2022 not working. / C++ extension

### ISSUE THREAD

**Issue by TinoNug** [godotengine/godot#87198]
### Tested versions

Reproduceable in 4.2 stable. 

### System information

Windows 10, v4.2 table

### Issue description

reinterpret_cast in create_method_bind is not working in VS22 compiler.

I tried every SDK, Platformtoolset and C++ Lang back to 2017. Compiler is just not having it.

```
**Error:**

error C2440: "reinterpret_cast":  cannot convert from "void (__cdecl godot::MyCanvasLayer::* )(void) const" to "void (__cdecl godot::_gde_UnexistingClass::* )(void) const" 

*godot::ClassDB::bind_method<godot::MethodDefinition,void(__cdecl godot::MyCanvasLayer::* )(void) const,>(N,M)" der Funktions-Vorlage.
1>        with
1>        [
1>            N=godot::MethodDefinition,
1>            M=void (__cdecl godot::MyCanvasLayer::* )(void) const
1>        ]
1>	C:\Development\Godot\Projekte\SDKs\godot\include\godot_cpp\core\class_db.hpp(246,21):
```

**Function:**

File: godot\include\godot_cpp\core\method_bind.hpp
```cpp
template <class T, class... P>
MethodBind *create_method_bind(void (T::*p_method)(P...) const) {
#ifdef TYPED_METHOD_BIND
	MethodBind *a = memnew((MethodBindTC<T, P...>)(p_method));
#else
	MethodBind *a = memnew((MethodBindTC<P...>)(reinterpret_cast<void (MB_T::*)(P...) const>(p_method)));
#endif // TYPED_METHOD_BIND
	a->set_instance_class(T::get_class_static());
	return a;
}
```

### Steps to reproduce

Call ClassDB::bind_method(...).

You should be able just to build the added project with VisualStudio Community. 

Examle from https://github.com/godotengine/godot-cpp-template has also the same issue.

### Minimal reproduction project (MRP)

[Uploading LastJourney_3D - Kopie.zip…]()

**Comment by Sauermann** [comment]
Can you please reupload the MRP. It looks like the upload of the MRP got interrupted. Please make sure, that you don't select another input field until the project is done uploading.

**Comment by TinoNug** [comment]
[Godot-Minimal.zip](https://github.com/godotengine/godot/files/14364227/Godot-Minimal.zip)

**Comment by TinoNug** [comment]
Simply open .[..\Godot-Minimal\LastJourney_3D\LastJourney_3D.sln]

Then build in debug mode. Should compile out of the box.

The error message should be visible.

![grafik](https://github.com/godotengine/godot/assets/130935963/592fefb2-277e-45ac-a9bf-e0b74ab04d75)

So far my project has grown a bit and it works well in VS.
Can't really complain ;) In fact, it's great. ^^

**Comment by TinoNug** [comment]
Project Settings -> C/C++ -> Preprocessor -> Preprocessor definitions

solves the problem.

**Comment by TinoNug** [comment]
Project Settings -> C/C++ -> Preprocessor -> Preprocessor definitions

solves the problem.
