### ISSUE TITLE
reinterpret_cast Error in VisualStudio22 / C++ Extension / ClassDB::bind_method(...)

### ISSUE THREAD

**Issue by TinoNug** [godotengine/godot#87199]
### Tested versions

Reproduceable in 4.2 stable.
System information

### System information

Windows 10, v4.2 table Issue description

### Issue description

reinterpret_cast in create_method_bind is not working in VS22 compiler.

I tried every SDK, Platformtoolset and C++ Lang back to 2017. Compiler is just not having it.

Error:
```
error C2440: "reinterpret_cast": cannot convert from "void (__cdecl godot::MyCanvasLayer::* )(void) const" to "void (__cdecl godot::_gde_UnexistingClass::* )(void) const"

godot::ClassDB::bind_method<godot::MethodDefinition,void(__cdecl godot::MyCanvasLayer:: )(void) const,>(N,M)" der Funktions-Vorlage.
1> with
1> [
1> N=godot::MethodDefinition,
1> M=void (__cdecl godot::MyCanvasLayer::* )(void) const
1> ]
1> C:\Development\Godot\Projekte\SDKs\godot\include\godot_cpp\core\class_db.hpp(246,21):
```
Function:

File: godot\include\godot_cpp\core\method_bind.hpp
```cpp
template <class T, class... P>
MethodBind *create_method_bind(void (T::*p_method)(P...) const) {
#ifdef TYPED_METHOD_BIND
MethodBind *a = memnew((MethodBindTC<T, P...>)(p_method));
#else
MethodBind a = memnew((MethodBindTC<P...>)(reinterpret_cast<void (MB_T::)(P...) const>(p_method)));
#endif // TYPED_METHOD_BIND
a->set_instance_class(T::get_class_static());
return a;
}
```
### Steps to reproduce

[LastJourney_3D_err.zip](https://github.com/godotengine/godot/files/13933716/LastJourney_3D_err.zip)

You should be able just to build the added project with VisualStudio Community.

Examle from https://github.com/godotengine/godot-cpp-template has also the same issue.

### Minimal reproduction project (MRP)

[LastJourney_3D_err.zip](https://github.com/godotengine/godot/files/13933710/LastJourney_3D_err.zip)

The Godot source code compiled for Windows should be inserted by you: (Too big to upload)

LastJourney_3D_err\godot

(https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html#setting-up-the-project)

**Comment by bruvzg** [comment]
> added project with VisualStudio Community

What's the source of this VS project? `godot-cpp` template project use SCons build system, and your project doesn't seem to call code generation script or include any of the generated files.

**Comment by TinoNug** [comment]
Hey,

I have uploaded the entire project + dependencies and the compiled code of godod to this folder:

[(https://drive.google.com/file/d/1xokI_U-AuVwC94CEcARtdg9FJikJb3Cj/view?usp=sharing)]

Godot is compiled with SCons.

So far, everything works in VS. But the binding does not work. I tried to change the code, but to be honest ... it looks like voodoo to me. :D


Is it possible for you to download it?
Should be enough to open the solution and compile it.

**Comment by TinoNug** [comment]
I dont unterstand. 

I do not compile godot in VS. I only compile my extension.lib. 
I use godot only as a library. 

![grafik](https://github.com/godotengine/godot/assets/130935963/2d1c983a-b77b-41ff-93d4-616d5504c706)
![grafik](https://github.com/godotengine/godot/assets/130935963/d49394ae-9dc6-4fdf-bd75-0a9b1e8b7aac)


But I cant compile my lib because of the cast in this function "ClassDB::bind_method(D_METHOD(...." .

I will try a few things but, I dont think I can do much about it other then compile my lib with another compiler.

**Comment by whiletrue111** [comment]
did you find solution , im working with vc++ 2022 ..

**Comment by NugTino** [comment]
Not really. I accidentally opened 2 threads. Here is another thread: 

https://github.com/godotengine/godot/issues/87198#issuecomment-1953706861

**Comment by CatShot112** [comment]
I found a solution, you have to define TYPED_METHOD_BIND.
Project Settings -> C/C++ -> Preprocessor -> Preprocessor definitions

Reference:
Line [167](https://github.com/godotengine/godot-cpp/blob/98c143a48365f3f3bf5f99d6289a2cb25e6472d1/CMakeLists.txt#L167) in CMakeLists.txt in godot-cpp repo. (4.2)

**Comment by TinoNug** [comment]
I can confirm. It works. Signals are working now.

Thank you @CatShot112 !!

**Comment by TinoNug** [comment]
@CatShot112 found a solution: 

define TYPED_METHOD_BIND
Project Settings -> C/C++ -> Preprocessor -> Preprocessor definitions

**Comment by Lycoris-SF** [comment]
May I ask what kind of black magic is this?
I'v completely lose my sanity.

**Comment by whiletrue111** [comment]
@TinoNug  @CatShot112  
How did you create visual studio c++ sln project ? 
Currently im using only scons and "open directory" from VC++ . 
I like to be able to create native VSC++ sln project ..

**Comment by whiletrue111** [comment]
Hey thanks allot ! one more question how can i configure from within the VSC++ to use :
 https://github.com/godotengine/godot-cpp-template to use this dll , be able to run it also as sln ? is it possible

**Comment by CatShot112** [comment]
@whiletrue111 
If I understood correctly, you want to debug your godot project from Visual Studio?

Project Settings -> Debugging -> Command -> (path to your godot.exe)
Project Settings -> Debugging -> Command Arguments -> (your command line arguments)

Example:
Command:
C:\dev\my\godot\Godot_v4.2.1-stable_win64.exe\Godot_v4.2.1-stable_win64.exe

Command Arguments:
--windowed --resolution 700x1000 --path c:\dev\my\godot\godotcpp\2d\TappyPlan\godot-cpp-template-ready\demo

I also suggest putting path to the scene you want to debug after arguments, ex. res://Main.tscn
