### ISSUE TITLE
Reloading scene doesn't reload collision shape properties

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#87201]
### Tested versions

- v3.5.3.stable.official [6c814135b]
- v4.2.1.stable.official [b09f793f5]

### System information

Pop!_OS 22.04 LTS, GTX1060 545.29.06

### Issue description

Modified collision shape properties such as `extents`, `radius` doesn't reloaded when you call `get_tree().reload_current_scene`, however modified `position` can be reloaded into original one.

### Steps to reproduce

1. run attachment
2. press any node to modify it
3. press **F2** to reload scene

### Minimal reproduction project (MRP)

[New Game Project.zip](https://github.com/godotengine/godot/files/13933937/New.Game.Project.zip)

**Comment by timothyqiu** [comment]
Possible duplicate of #42400.

**Comment by boruok** [comment]
duplicate
