### ISSUE TITLE
Canvas layer stop click

### ISSUE THREAD

**Issue by KeiMuriKoe** [godotengine/godot#87220]
### Tested versions

4.2 stable

### System information

Windows 10, Godot 4.2 Stable, Forward Mobile. 

### Issue description

Not sure if it's a bug. I want one control node be in canvas layer and listen gui_input signal from it, and other control that overlap first control and also want to listen signal, but not on canvas layer, see pic next :

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/106619492/7a1f9795-cbb5-4503-bc8d-76e5cb5bdd0c)

reproduce is very simple, 2 full-screen control (to be sure they are overlapping), all controls to Pass mode(so they pass click).
connect signal. 

Ofc i can set layer on canvas layer to -1, and my signal will be heard. But than 1st - not. 

Not sure if it's a Bug, but I've read the documentation and forums, and everywhere they say to use a canvas layer. Oh, yes, one control node should be a static HUD on the screen, while the second one should stay in place after the camera moves. That's why I'm using Canvas Layer.

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
This works as designed. Pass only passes events to parent nodes, but not to sibling nodes in the scene tree.
You find a description of the current situation in https://github.com/godotengine/godot-proposals/issues/3613

**Comment by KeiMuriKoe** [comment]
> This works as designed. Pass only passes events to parent nodes, but not to sibling nodes in the scene tree. You find a description of the current situation in [godotengine/godot-proposals#3613](https://github.com/godotengine/godot-proposals/issues/3613)

Thank you for the response. The link to that discussion resolved my issues. Many thanks! I also shared my experience and the solution on the Godot forum, hoping it will be helpful to someone else besides me.
