### ISSUE TITLE
Editor: Out of bounds error in one of TabBars when you have floating docks

### ISSUE THREAD

**Issue by YuriSizov** [godotengine/godot#87234]
### Tested versions

Reproduced with the current master, 9e65c5c0f4f8944d17fc7f5b05682206e9348d81.

### System information

Godot v4.3.dev (9e65c5c0f) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.3742) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

If your editor layout has a floating dock, when you restart the editor you may be welcomed to this error:

```
scene\gui\tab_bar.cpp:643 - Index p_current = 0 is out of bounds (get_tab_count() = 0).
```

I tried to debug it, but this ended up being a deferred call, so I'm not entirely sure where it comes from. I quickly tried to find places that call this method deferred, but couldn't confirm any of them are responsible. So logging it here for now.

### Steps to reproduce

This is the layout that I have:

![image](https://github.com/godotengine/godot/assets/11782833/3c30a3c5-9d08-45bf-993f-4dfab841a947)

Make the Scene dock floating and then reload the project. Everything will restore correctly, but you will be greeted with an error in the output log.

### Minimal reproduction project (MRP)

N/a.

**Comment by kitbdev** [comment]
Can confirm, it happens for me with a similar layout.
I believe it is from `EditorDockManager::load_docks_from_config` line 625, where `set_current_tab` is deferred for a dock but then that dock is made floating after it so there are no more tabs in the tab container.
