### ISSUE TITLE
`to_global` doesn't work correctly on RayCast3D

### ISSUE THREAD

**Issue by tocruise** [godotengine/godot#87230]
### Tested versions

- I've only tested in Godot 4.2 Stable

### System information

Stable 4.2, Windows 10

### Issue description

I'll preface this by saying that I could totally not be understanding how `to_global` works, and I'm just misusing it.

I've been trying to get the end point (the target) of a 3D ray cast so that I can spawn a node at that position, however the position of the spawned node never seems to be correct, and I believe my testing shows it's because of a bug with `to_global` and/or `global_positions`

### Steps to reproduce

1. Create a 3D scene with a root node called `world`.
2. Create a Node3D called `player` (I've tested with a RigidBody too but for this example it'll work better as a Node3D)
3. Add a RayCast3D as a child of the `player`, and set the position to `(0, 2, 0)` - so about where the eyes would be if the player is 2m tall, for example. And then set the target to `(0, 0, -2)`, which sets the target 2m away on the Z-index, so it's effectively petruding 2m out in front of the player's eyes.

These were the values I expected:
`ray.global_position: (0, 2, 0)`
`to_global(ray.target_position): (0, 2, -2)`

But here's what I got instead:
`ray.global_position: (0, 2, 0)`
`to_global(ray.target_position): (0, 0, -2)`

You can see that the global position of the target is wrong. It's not accounting for the parent's Y position transform. 

Adding a new mesh to the root node in the editor, and setting it's position (which will be in global space) to `(0, 2, -2)` shows it line up exactly with the end of the ray (the target) which proves the target really is at `(0, 2, -2)` but isn't returning it as so.

### Minimal reproduction project (MRP)

[RayTest.zip](https://github.com/godotengine/godot/files/13942377/RayTest.zip)

**Comment by Sauermann** [comment]
This seems like it works as intended.
You call `to_global()` from the `World`-node and since the world node is at coordinates (0, 0, 0) with default rotation or scale, you get `to_global(pos) = pos`.

If you attach the xxxxx.gd script to the Player node and adjust the RayCast3D node path, then you should get your intended result.

**Comment by tocruise** [comment]
@Sauermann Thanks for responding so quickly.

I've tested this on my end, with the changes you mentioned, and the result is the same. I'm not sure if this is possible, but are you able to attach the project where you got it working? 

I'm also not sure If I'm following what you mean in regards to the `world` node. Does the context of `to_global` change depending on where it's called from? It's not a function I'm particularly familiar with, and the docs seem pretty limited in this regard, so I have absolutely no understanding of how it works :)

**Comment by Sauermann** [comment]
That is because my previous statement was wrong. You need to call `to_global` from the Ray itself and not from the Player.
Here is the adjusted working MRP: [RayTest.zip](https://github.com/godotengine/godot/files/13942763/RayTest.zip)

> Does the context of `to_global` change depending on where it's called from?

Yes it does. It is relative to the node from which it is called from.

> Does the same apply to `global_position` too?

No, when you access the global_position of a Node3d, then it doesn't matter, from where it is accessed.

**Comment by tocruise** [comment]
Okay, that project file seems to work. Thanks for your help.

In that case then, I suppose my petition would be to add a way to get the global_position of a raycast's target (similar to how other 3D points in space have a `global_transform` property) without having to manually create a getter/setter in a script attached to the Ray, but I'll make that argument in the godot-proposals. 

Happy for this to be closed if no further comments are to be made.
Thanks again.

**Comment by Sauermann** [comment]
> add a way to get the global_position of a raycast's target

You can do that by using:

``` gdscript
print(str('ray_target_global: ', ray.global_transform * ray.target_position));
```
This works also from scripts that are attached to other nodes.

> similar to how other 3D points in space have a `global_transform` property

3D points don't have a global_transform, but 3D Nodes do.

Feel free to close this issue, if you believe, that your problem is resolved.

**Comment by tocruise** [comment]
That works perfectly! Saves me having to setup a script on every Raycast.

Thanks again. Closed.

**Comment by jack27121** [comment]
I would like to add that it works in the inverse, in case others search for this.

In Godot, how to set Raycast3D target_position using global_position
`ray.target_position = desired_pos * ray.global_transform`
