### ISSUE TITLE
Godot Won't Open

### ISSUE THREAD

**Issue by Ussernam** [godotengine/godot#87237]
### Tested versions

Godot v4.1.3

### System information

Godot v4.1.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon (TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.45004) - AMD Ryzen 5 7530U with Radeon Graphics (12 Threads)

### Issue description

Godot won't open. It shows a popup the same size it normally would come up as but it's completely black and after a few seconds it says "Godot Engine is not responding".  It was just working the other day, and just saved and closed my project as normal. No messing of any sort of files or anything afterwards either.

Edit:
It wasn't downloaded through steam before, but after doing that it still wouldn't open and I faced the same issue

I deleted all godot files I had not from steam, and now at startup it flashes the startup screen with the godot logo but immediately stops responding

### Steps to reproduce

Open the desktop shortcut. That's all I do.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Could you try the latest stable version? i.e. 4.2.1 at the time of writing.

**Comment by Ussernam** [comment]
> Could you try the latest stable version? i.e. 4.2.1 at the time of writing.

I did when I downloaded it off of Steam and it still didn't work

**Comment by Ussernam** [comment]
I restarted my laptop and it fixed the issue

**Comment by akien-mga** [comment]
Then it was probably GPU drivers being in a broken stable after an update, which often needs a restart.
