### ISSUE TITLE
Editor Cursor is very slow and laggy on s separate window.

### ISSUE THREAD

**Issue by mifth** [godotengine/godot#87269]
### Tested versions

Godot 4.2, release, Windows 11.

### System information

Windows 11

### Issue description

Hi, I've found that if I have a separate window of a text editor then it will be slow and laggy. I recorded video.
[slow cursor issue.zip](https://github.com/godotengine/godot/files/13955163/slow.cursor.issue.zip)

### Steps to reproduce

- make a separate window of the editor
- reopen Godot

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/13955192/project.zip)

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Interface > Editor > Update Continuously** in the Editor Settings? If not, this may hint at the unfocused low processor mode sleep duration being incorrectly applied.

**Comment by mifth** [comment]
@Calinou after enabling "Update Continuosly" and restarting Godot the editor became about 2x faster but not as fast as after dragging the editor window and expanding it. So, it became faster but still slow. I hope I explained clearly. I can record a video if you need.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79290.
