### ISSUE TITLE
Editor crashes when re-baking NavigationMesh

### ISSUE THREAD

**Issue by AndresDavidCalderon** [godotengine/godot#87267]
### Tested versions

Reproducible in 4.2.1 stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21905.1001) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

The editor crashes when the souece geometry for a NavMesh is too big for the current cell size and cell height, and only is able to display the warning when opened using the command line.

Behaviour: Godot crashes and leaves a warning on the log giving instructions on what to do.

Expected behaviour: The editor does not crash and instead warns the user before action is taken.

### Steps to reproduce

Have a project with a source geometry with an area of (in my case) 1200(x)x1(y)x2500(z) units, and leave the navigation cell size to 0.25m, with blocks of around 600(x)x7(y)x220(z) that intersect the initial block, then try to bake the navigationmesh, and the editor will crash. 

### Minimal reproduction project (MRP)

[bignavigation.zip](https://github.com/godotengine/godot/files/13954952/bignavigation.zip)
Open main.tscn, try to bake the navigationMesh, and you will get an editor crash, and the warning won't display in the editor.

**Comment by smix8** [comment]
There is little that can be done here without modifying a thirdparty library. The crash happens inside the library black box when it runs out of resources due to the excessive layout that requires at least 48.000.000 voxels with those settings. It is an old issue that gets reported every other year and has been part of ReCast since forever. It is also part of the documentation.

**Comment by Scony** [comment]
As agreed with @smix8, I'll try implementing the idea proposed here: https://chat.godotengine.org/channel/navigation?msg=ZkocD7ZRbaDgTRCoB

**Comment by Scony** [comment]
I think we can close this as #89692 landed already.
