### ISSUE TITLE
[3.0] hbox container inside center container doesnt remember anchoring or expand to parent setting

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8726]
**Operating system or device - Godot version:**
3.0 git

**Issue description:**

I have a small setup:

panel
- center container
  - hbox container

Ive them all set to expand to parent, and anchor full rectangle.
Click save and it all looks ok. 
Change away from the prop, then change back and the hbox container has been reset to size of 0,0

**Comment by bojidar-bg** [comment]
It shouldn't remember anchors, since that doesn't mix with containers, but the children of the CenterContainer should remember and use the expand setting just fine :smiley:

**Comment by juan-garcia-m** [comment]
This issue actually happens in other setups too. For example using vbox container inside scroll container.
Adding a child node resets all the anchors and margins to 0.
When trying to resize the vbox container will glitches and resets to 0 after a certain amount. Setting the anchor right to end and margin right to 0, resets anchor right to begin and margin 0.
I am trying to setup a project with a "collection" of this kind of really annoying issues.

I am using workarounds like the following, but it stop working on the 3,0 Alpha 1 (it worked on custom 3.0 builds):

```
tool
extends VBoxContainer

func _process(delta):
	self.set_anchor_and_margin(MARGIN_RIGHT, ANCHOR_END, 0)

```

**Comment by dploeger** [comment]
I've made a screencast with this bug or sort of it as I also encountered this reset while loading the screen: 

[Screencast](http://take.ms/J0uMj)

This makes layouting unusable currently.

**Comment by divmgl** [comment]
I'm seeing all kinds of weird bugs with the GUI controls.

![another-bug](https://user-images.githubusercontent.com/5452298/35762959-68815f0a-0856-11e8-9282-6a2dd112b786.gif)

* Setting any other property of a GUI control resets its position
* Setting any property of a GUI control resets its parents positions as well
* You can't decrease the size under the initial minimum size even if you change the minimum size

**Comment by bojidar-bg** [comment]
> * Setting any other property of a GUI control resets its position

Containers are supposed to manage the positions and sizes of their children.

> * Setting any property of a GUI control resets its parents positions as well

Same as last point, it just triggers a minimum size changed event.

> * You can't decrease the size under the initial minimum size even if you change the minimum size

The min_size property is the custom minimum size. Nodes such as labels have some inherent minimum size as well (to fit text, styleboxes, other controls..), which is combined with the custom one.

**Comment by groud** [comment]
Closing, as now a message is displayed explaining that children of containers see their anchors and margins set by their parents.
