### ISSUE TITLE
Ability for godot to remember collapsed items in input map editor panel.

### ISSUE THREAD

**Issue by ni-code** [godotengine/godot#8728]
Godot v2.1.3

[Low priority]

Feature request:
Currently collapsed items in input map editor panel always get expanded when editing the remaps.
I'm asking the ability for godot to remember collapsed items in input map editor panel.

Because my english sucks I've recorded a gif showing the current behavior.
![gd_input_panel](https://cloud.githubusercontent.com/assets/10292929/25995712/8e87e9d4-370b-11e7-8d90-fdbe7baad25e.gif)

**Comment by volzhs** [comment]
maybe this could be fixed 2.1 also.

**Comment by kubecz3k** [comment]
This behavior is still present in 3.0.2

**Comment by KoBeWi** [comment]
This is fixed in 3.1

**Comment by BieniekAlexander** [comment]
I'm seeing this behavior today in 4.3 :(
