### ISSUE TITLE
_GuiInput() method captures control errors

### ISSUE THREAD

**Issue by airs1991** [godotengine/godot#87283]
### Tested versions

v4.3.dev2.mono.official [352434668]

### System information

MacOS 10.15.7 (19H2026)

### Issue description

When I drag the mouse from control A to control B and release it, A is still capturing the _GuiInput() event instead of B.

### Steps to reproduce

Run a minimal copy project.

### Minimal reproduction project (MRP)

[Input Test.zip](https://github.com/godotengine/godot/files/13957493/Input.Test.zip)

**Comment by Sauermann** [comment]
Thanks for the report. Consolidating as a duplicate with #84466.
