### ISSUE TITLE
Additional window blocks _input in script of main window

### ISSUE THREAD

**Issue by torbenvanassche** [godotengine/godot#87291]
### Tested versions

- Reproducable in v4.0, v4.1.3,  v4.2

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3758) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When opening a base `Window` node the main window loses focus.
This causes the main window's _input events to no longer trigger until that window is interacted with.

### Steps to reproduce

Open the project and run it. You will not see the input event being ran until you click on the main window.

### Minimal reproduction project (MRP)

[bugreport-input.zip](https://github.com/godotengine/godot/files/13963395/bugreport-input.zip)

**Comment by torbenvanassche** [comment]
> [godotengine/godot-proposals#7743](https://github.com/godotengine/godot-proposals/issues/7743)

Interesting, so it is a regression from godot 3 conversions. Glad to see this is being taken care of.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/7743.
