### ISSUE TITLE
should the api make_input_local take care of the scale of the node?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8729]
**Operating system or device - Godot version:**
Mac OS   godot 2.1.3

**Issue description:**

When a node is scaled, 
var ev = node.make_input_local(event)
the value of ev.pos is the coordinate multiply by the scale.
it's not the real coordinate in the node.
**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment]
I think this is a bug, not a discuss feature.

**Comment by karroffel** [comment]
Discussion doesn't mean feature request, it means "Discussion". For feature requests there's a label called "feature proposal"

**Comment by alexzheng** [comment]
Sorry for the trouble, 
the result  of Node.make_input_local is correct, 
I made a mistake by setting a sprite to scale(2,2), and call make_input_local by it's parent, the returned pos of the event is correct, it did not multiply by the scale.
