### ISSUE TITLE
Godot editor (or an exported application) doesn't respond after being minimized in the dock and restored with a mouse click on MacOS

### ISSUE THREAD

**Issue by OKGougou** [godotengine/godot#87309]
### Tested versions

- Reproducible in: 4.2.1-stable, 4.2-stable
- Not reproducible in: 4.1.3-stable

### System information

Godot v4.2.1.stable - macOS 13.6.3 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

After being minimized in the dock, the restored editor window becomes unresponsive if restored with a mouse click in the dock window list.

### Steps to reproduce

Open a Godot 4.2 or 4.2.1 project on MacOS.
Minimize Godot in the dock.
Click on the minimized window in the dock window list.
Try interacting with Godot.

Expected behavior:
Godot should respond to mouse and keyboard interactions.

Actual behavior:
The user interface does not respond to mouse and keyboard interaction.

The problem does not arise if the window is restored from the Godot application icon in the dock, nor if the window restore keyboard shortcut is used.
(To use the keyboard shortcut, select Godot with Command+Tab, hold down Command, press Option+Command, release Command while pressing Option).
If the unresponsive window is minimized in the dock and restored by a mouse-click on the Godot application icon in the dock or by a keyboard shortcut, the restored Godot window becomes active again and displays the changes it received when it was unresponsive.

### Minimal reproduction project (MRP)

No required project.

**Comment by lostminds** [comment]
Tested and confirmed the same issue is still present in Godot 4.3.dev2 on macOS 14.2.1. 

Using the newly added Window menu (https://github.com/godotengine/godot/pull/83987) items to expand the minimized window restores the interactivity as expected. But just clicking the minimized window in the Dock still leads to it being opened and activated, but not reacting to any input events (mouse or keyboard). 

However, when experimenting a little it seems that it is actually processing the input events, it's just not redrawing the window to reflect the changes, so it appears as if it's not reacting.
