### ISSUE TITLE
`Array` cannot be converted to generic type array.

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#87319]
### Tested versions

Godot 4.2.1

### System information

Windows 11 Pro - Godot 4.2.1

### Issue description

When you have an array of type `Array`, it cannot be casted to a generic type array (e.g. `Array[String]`). 

This becomes most annoying when dealing with built-in methods that return `Array` (which is fairly common). This means you cannot make use of generic typed arrays when working with these built-in methods.

It should also be noted that the other way around is not an issue. Meaning, you **can** cast an `Array[String]` as an `Array`.

### Steps to reproduce

Create a node and attach the following script:

```gdscript
extends Node

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	#print(get_keys())
	print(get_casted())

func get_casted() -> Array[String]:
	var arr := []
	return arr as Array[String]
```

### Minimal reproduction project (MRP)

Rather than downloading an entire project, just take the above code in "Steps to Reproduce" and throw it on a node. The issue will be apparent when running that scene.

**Comment by dalexeev** [comment]
The `as` operator cannot convert arbitrary array expressions (`array as Array[int]`, only literals (`[] as Array[int]`). Arrays are passed by reference, so it is not possible to convert an existing array, only create a new one - for this you can use the [`Array.assign()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-assign) method. But in the future we want to add a typed array constructor (`Array[int](array)`).

See also:
* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* godotengine/godot-proposals#7364

Thanks for the contribution nonetheless!
