### ISSUE TITLE
Select next ocurrence when value is inside a collapsed function

### ISSUE THREAD

**Issue by christianmateus** [godotengine/godot#87310]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5], v4.3.dev2.official [352434668]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (Advanced Micro Devices, Inc.; 27.20.22016.2) - Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (24 Threads)

### Issue description

Trying to select the next ocurrence of anything in the code editor, while it's inside a **collapsed** function, returns an error:

![image](https://github.com/godotengine/godot/assets/86802822/b6cfec0a-8d5e-4118-86cc-4fa302cd4d6d)

I believe it should expand the function, then select the ocurrence.

### Steps to reproduce

Select a word and press Ctrl + D to find and select the next ocurrence of it. A function must contain the word, and it must be collapsed.

### Minimal reproduction project (MRP)

[Select_next_Ocurrence.zip](https://github.com/godotengine/godot/files/13967995/Select_next_Ocurrence.zip)

**Comment by kitbdev** [comment]
This should be easy to fix after #86978 since it adds a `_unhide_carets()` method in TextEdit that can probably be used for this.
