### ISSUE TITLE
GDScript cannot infer type from new() for a declared class_name

### ISSUE THREAD

**Issue by MichaelMacha** [godotengine/godot#87315]
### Tested versions

- Reproducible in 4.1.3 Stable

### System information

KUbuntu 22.04

### Issue description

When declaring a class and giving it a `class_name` and defining `_init()`, you still cannot infer the type from that class's `new()`. You have to manually specify it.

### Steps to reproduce

I have a specific, bare-bones class:
```

class_name Fluid

func _init():
	pass
```

When I wish to instantiate this class, I can do this:

`var fluid : Fluid = Fluid.new()`

But not this:

`var fluid := Fluid.new()`

As it gives me the error `Cannot infer the type of 'fluid' variable because the value doesn't have a set type`.

I can kind of see how this could be the case, as `_init` does not return a value and `new` is carried over somewhat from Godot 3.x; but it does feel like a non-intuitive issue which should eventually be resolved.

Experimenting has shown me that `new` returns type `RefCounted`, and I cannot assign the value given to another random `RefCounted` like `WeakRef` or `RegExMatch`, but I can to `Fluid` (in this instance), so it seems the value knows its type well enough.

### Minimal reproduction project (MRP)

See above, and try it out on 4.1.3. It's likely still the case on more recent versions, but can't immediately confirm.

**Comment by dalexeev** [comment]
I can't reproduce this in 4.2.1 and 4.1.3. Try to update the script or restart the editor.

**Comment by AThousandShips** [comment]
Can you confirm this is still occuring?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
