### ISSUE TITLE
Crash when baking Lightmaps

### ISSUE THREAD

**Issue by verypleasentusername** [godotengine/godot#87325]
### Tested versions

4.2.2 Forward+ had same results in 4.1.3 Forward+ and 4.2. beta 5 Forward+. 

### System information

windows 10, 4.2.2, Forward+

### Main Problem

When baking lightmaps crash occures if scene is more complex than one house(look MRP project)

### Probable causes

low spec PC, Model corruption, cache corruption, GPU overload.

### Ways to fix

For me i found that sometimes re-placing models can help thought with more than 2 of them crash still occures.
GPU limiter implement https://github.com/godotengine/godot-proposals/issues/3867

### General Topic

So i had a problem with infinite freezing but when i buffed TdrDelay to 60 as i was recomended freeze switched to crash. Before crash there errors occur:

![image](https://github.com/godotengine/godot/assets/63970682/1c5c448c-0478-4b5b-ade8-b80a05bad084)

After which godot crashes.

### Steps to reproduce

Dowload MRP, open in godot, select LightmapGI and click "Bake". If successfull, enable all house models at once and click bake again.

### Minimal reproduction project (MRP)

[LighmapCrashMRP.zip](https://github.com/godotengine/godot/files/13972828/LighmapCrashMRP.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84664, as this is due to the same cause.

(For reference, I can't reproduce this issue with the MRP linked, both with the denoiser enabled and disabled.)
