### ISSUE TITLE
Cracking audio with Godot 4 no-threads Web builds

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#87329]
### Tested versions

Reproducible in 4.3.dev (1952f64b07b2a0d63d5ba66902fd88190b0dcf08) with a `threads=no` Web template.
The issue was "introduced" in #85939 since it wasn't possible to make single-threaded Web builds in Godot 4 before that.

### System information

Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

The newly reintroduced single-threaded Web export has audio issues, as expected.

On my Linux system, it's pretty dire on any demo that has background music, sfx, and any game logic or rendering effort that's non trivial (i.e. the CPU is kept busy).

Here's an example with the [GDQuest TPS demo](https://github.com/gdquest-demos/godot-4-3d-third-person-controller), uploaded to itch.io, with threads disabled (built from #85939):

https://akien.itch.io/godot4-nothreads-audio-test

(Ignore the weird rendering (Compatibility while the demo is designed for Forward+) and the fact that rotating the camera with the mouse seems to be broken in the Web build.)

Here's how the game sounds like on a native Linux build (editor):

https://github.com/godotengine/godot/assets/4701338/638685d6-553d-4755-92df-6658ea57245d

Here's the `threads=no` Web build (debug) on currently Firefox Nightly (123.0a1 (2024-01-17)) on the same Linux system:

https://github.com/godotengine/godot/assets/4701338/cc9d8aac-4fe0-4e2f-8c60-06b6b6a4e860

And the same on Chromium (120.0.6099.216) on the same Linux system:

https://github.com/godotengine/godot/assets/4701338/d35431cb-a6f4-4250-8db2-7e63813e9c74

---

The issue is likely linked to OS, browser, and CPU, so for testers who can or cannot reproduce it, please include full info about what platform you tested on.

```
$ inxi -CSG
System:
  Host: cauldron Kernel: 6.5.13-desktop-6.mga9 arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.5 Distro: Mageia 9
CPU:
  Info: quad core model: Intel Core i7-8705G bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 900 min/max: 800/4100 cores: 1: 900 2: 900 3: 900 4: 900
    5: 900 6: 901 7: 900 8: 900
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Device-2: AMD Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu v: kernel
  Device-3: Cheng Uei Precision Industry (Foxlink) HP Wide Vision FHD Camera
    type: USB driver: uvcvideo
  Display: x11 server: X.org v: 1.21.1.8 with: Xwayland v: 22.1.9 driver: X:
    loaded: intel,v4l dri: i965 gpu: i915 resolution: 2048x1152~60Hz
  API: OpenGL v: 4.6 Mesa 23.3.2 renderer: Mesa Intel HD Graphics 630 (KBL
    GT2)
```

### Steps to reproduce

- Export a project with audio and some non-trivial game logic to the Web, with threads disabled (in 4.3-dev3 or later, or custom builds from `master` with `threads=no`)
- Run it on an affected system. At least reproducible on my Linux laptop.

### Minimal reproduction project (MRP)

https://akien.itch.io/godot4-nothreads-audio-test

**Comment by akien-mga** [comment]
Same issue on Android 14 with a Pixel 7a, both with Firefox Beta 122.0b9 and Chrome 120.0.6099.210.

**Comment by popcar2** [comment]
Windows 11 v23H2 here (full specs later). I'm also getting audio cackling in your example project on Firefox, Chrome, and Edge. It sometimes sounds fine probably when the game is running at full speed though.
Chrome and Edge also have major artifacts on the intro screen. 

**Firefox 121.0.1:**

https://github.com/godotengine/godot/assets/16920817/53b808d0-1321-4c5e-a2c8-47ad6edcb13f

Notes: Similar results to the post above, but it runs a lot smoother on my end due to better specs.

**Microsoft Edge 120.0.2210.144 (WARNING: FLASHING COLORS):**

https://github.com/godotengine/godot/assets/16920817/22012fda-94e7-4348-9fd5-1009f1ab42d7

Notes:

* For some reason the intro screen is completely broken on Edge with lots of flashing and artifacting. This could possibly be its own issue, not sure if there is correlation between this and no-threads build.

* After compiling shaders the sound seems stable, **but** it completely breaks again when I leave fullscreen. Entering fullscreen again doesn't fix it. Could also be its own issue?

**Google Chrome Version 120.0.6099.225:**

Notes: Exact same results as Microsoft Edge (see video above). Broken intro screen, good audio after shader compilation, audio breaks when exiting fullscreen. 

Here are my specs:
```
Windows 11 Home - Version 23H2 / Build 22631.3007
Processor: AMD Ryzen 5 5600 @ 3.5GHz
GPU: RTX 3060 Ti - driver 546.33
RAM: 16GB
```

**Comment by starry-abyss** [comment]
I'm a newbie in this, but maybe we could use Web Audio backend code from miniaudio library in Godot?

**Comment by wojtekmal** [comment]
The audio in my game runs perfectly when I run the linux release export, but my game isn't cpu intensive so this isn't very significant. Anyway, two things caught my attention. Firstly, audio from MRP on itch.io is of low quality, but when I switch to another tab, the audio quality suddenly increases to near perfect. I use firefox 122.0 64 bit. Secondly, the game is completely silent when I launch my game from the editor with f5, however as I said previously, it works in the export.
Here are my specs:
![image](https://github.com/godotengine/godot/assets/100026278/1268fdf9-570e-4b08-9986-808ea1a25036)

**Comment by HamdyElzanqali** [comment]
One temporary workaround is to use a library like howler.js to handle sounds on the browser side.
I could achieve that by:

1) Exclude the audio from being exported in the web preset so it isn't duplicated by the end and use unnecessary space.

You can do that by going to `Project -> Export -> Web -> Resources tab -> Filter to exclude`, and maybe have all your audio in a folder called Audio, so you can write "Audio/*" to exclude the folder from being exported.

![image](https://github.com/godotengine/godot/assets/56981649/db04e79f-13d1-4586-aa0a-c7cbf15ab822)

2) Add howler.js to the headers, you can link the library or download it and add it to the export folder. I will explain in a bit how I could easily automate that.

You can get howler.js from [cdn](https://cdnjs.com/libraries/howler), [their website](https://howlerjs.com), or download this [howler.min.zip](https://github.com/godotengine/godot/files/14042543/howler.min.zip)

`Project->Export->Web-> Options tab -> HTML -> Head Include` and include it. I will have a folder in the web build folder called `Audio` where I will have howler.min.js and the rest of the Audio files. So, I need to make it like 
```js
<script src="Audio/howler.min.js"></script>
```

![image](https://github.com/godotengine/godot/assets/56981649/219a3b8f-045d-4096-82e3-c912129490b8)

3) You also need the `Audio` folder that you have in the Godot project to be in the web build so howler.js has access to the audio files. However, copying it manually every time is a massive pain and unnecessary work, so I wrote a simple addon that could spare you from doing that.

[copy_additional_folders.zip](https://github.com/godotengine/godot/files/14042622/copy_additional_folders.zip)

Copy it to your `addons/` folder and go to `Project -> Project Settings -> Plugins -> Enable Copy Additional Folders` 
Now go to `Project->Export->Web-> Options tab -> Copy Folders` and add `Audio` to the array.

![image](https://github.com/godotengine/godot/assets/56981649/0d1120ff-5133-4256-a21a-2b77fb5d119b)

Now `Audio` and all its content will be copied after the game is exported automatically. You can put the `howler.min.js` inside `Audio` so Godot copies it automatically with the audio. (Note that Godot won't show `.js` files in the `FileSystem` so it will be invisible inside Godot)

4) Finally, you should be able to call `Howler.js` functions through `JavaScriptBridge`.
For example, to run this JavaScript code
```js
var sound = new Howl({
  src: ['sound.mp3']
});
sound.play();
```

you should write something like this:

```gdscript
# only run on web
if OS.get_name() == "Web":
	# top dictionary
	var arg = JavaScriptBridge.create_object("Array", 0)
		
	# src array
	arg["src"] = JavaScriptBridge.create_object("Array", 1)
	arg["src"][0] = "Audio/floating-cat.mp3"
		
	# Howl obj
	var obj = JavaScriptBridge.create_object("Howl", arg)
	obj.play()
	
	# using JavaScriptBridge.eval is not recommended since most of online platforms doesn't have eval enabled
	# and might consider it a security risk
```

They have the documentation on their [Github repo](https://github.com/goldfire/howler.js#documentation).

This fixed the audio problems by not using the system inside Godot at all. Maybe someone can extend on this by making a plugin for `Howler.js` or any other library and implement audio nodes that works normally on other systems but falls back to howler on web.

**Comment by octanejohn** [comment]
pixel 6 android 13 Kiwi Browser 120.0.6099.116, cracking and missing textures

![Screenshot_20240203-192618](https://github.com/godotengine/godot/assets/156664637/3b3b4da2-a6ae-41d8-868d-910aa23d63b6)

**Comment by wojtekmal** [comment]
I noticed that audio is broken regardless of whether I export with the option "Thread support". Of course when I export from the normal editor with normal templates (built without --treads=no) it still works.

**Comment by ChronoDK** [comment]
If you increase audio output latency.web to 90 it mostly goes away.

**Comment by popcar2** [comment]
> If you increase audio output latency.web to 90 it mostly goes away.

This... Actually works, thanks! Hopefully that can help track down the issue.
Here's my testing with the no threads template:

**Latency.web 50 (default) - audio starts at 0:17** - Notice the insane crackling in the game over screen

https://github.com/godotengine/godot/assets/16920817/437bfbce-c991-4edb-9d1d-dfc7b1dd6e10

**Latency.web 90 - audio starts at 0:11** - Audio has minor skips on frame drops but does not crackle

https://github.com/godotengine/godot/assets/16920817/07944539-cadc-457e-a56f-ad3551a57221

**Comment by fire** [comment]
@jasonwinterpixel Mentioned using Latency.web 150 in Godot Engine 3, but I didn't get the complete details on what harm this causes.

**Comment by akien-mga** [comment]
Needs testing on several projects/devices, but I suggest we look into increasing the default audio latency for the Web export in 4.3, mitigating the current issues. I agree with @jasonwinterpixel that high latency is a bother, but it's better than the kind of cracking we have currently.

It's not a long term solution, but it should be a good first step to make things at least usable.

**Comment by graphific** [comment]
Just FYI changing the audio output latency.web from 50 to 90 fixed the crackling issue almost entirely (having about 4-6 audio players procedurally playing different sound layers and only sometimes a tiny bit hickup, but the sound stays clear), for this jam game: https://graphific.itch.io/bird-ruckus

**Comment by Silvanuz** [comment]
FYI too: 
Can confirm that changing the latency.web to 100 (max value) does nothing in my case. 
But the sound cracks only on the left channel on iOS. With a panner to the right channel only everything sounds clean.
