### ISSUE TITLE
Use correct error metrics for VRAM textures

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#8733]
(I'm writing this just as a TODO for after #8548 is merged)

Both etc2comp and libsquish allow using different error metrics, which we should take advantage of (RGBX for specular, NORMALXYZ for normalmap, and so on).

This will require communicate some hinting for the compressor, which is related to #8459.

**Comment by reduz** [comment]
I will close this, we will probably move to compressonator as soon as its available for Linux and Mac.

**Comment by tagcup** [comment]
Can we keep this open?

1. Compressonator is a *maybe* entirely depends on whether the upstream is willing to do the Linux port.
2. This is still valid with Compressonator since it also supports error metrics.

**Comment by reduz** [comment]
talked to them already and Linux port is underway

**Comment by tagcup** [comment]
Yes but again, "This is still valid with Compressonator since it also supports error metrics."

**Comment by reduz** [comment]
alright, if it makes you happy, but kicking to 3.1 since at this point it seems no one will do it this week..

**Comment by tagcup** [comment]
Sure although that shouldn't be a API-breaking change, so maybe I can do this before 3.0

**Comment by reduz** [comment]
if you want to do this, feel free, would be nice!

**Comment by reduz** [comment]
i think all information is there about intent for compression now

**Comment by tagcup** [comment]
Ah yeah this is actually one of the issues I opened as a to-do list for myself

**Comment by akien-mga** [comment]
As OP is now a ghost and @reduz was not particularly keen on this issue, closing.
