### ISSUE TITLE
Control.set_global_position(global_position) doesn't work after rotated around custom pivot

### ISSUE THREAD

**Issue by abcjjy** [godotengine/godot#87354]
### Tested versions

Godot v4.2.stable

### System information

Godot v4.2.stable - macOS 13.6.1 - GLES3 (Compatibility) - ANGLE (AMD, ANGLE Metal Renderer: AMD Radeon Pro 560X, 版本13.6.1（版号22G313）) - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

When a Control's pivot offset is set to somewhere other than (0, 0) and rotated, set_global_position(global_position) will move the Control far away. 

### Steps to reproduce

```GDScript
extends ColorRect

func _ready():
    pivot_offset = size
    rotation_degrees = 90
    for i in 36:
        set_global_position(global_position)
        await get_tree().process_frame
        print('%s %s %s'%[position, global_position, size])

```

### Minimal reproduction project (MRP)

N/A

**Comment by Rindbee** [comment]
By default, the upper left corner is used as the pivot point for transformation. This issue occurs when the pivot point is not in the upper left corner.

When the pivot point is not in the upper left corner, the correct transformation order is:

```GDScript
var ori : Vector2 = get_parent().get_global_transform() * position + pivot_offset
var t := Transform2D()
t = t.translated(-ori)
t = t.rotated(rotation)
t = t.translated(ori)
var t_aff_inv := t.affine_inverse()
```

The current transformation order seems to be:
```GDScript
var ori : Vector2 = get_parent().get_global_transform() *  position 
var t := Transform2D()
t = t.translated(-pivot_offset)
t = t.rotated(rotation)
t = t.translated(pivot_offset + ori)
var t_aff_inv := t.affine_inverse()
```
