### ISSUE TITLE
Using texelFetch on the screen texture with XR shaders enabled crashes Godot

### ISSUE THREAD

**Issue by CheesecakeCG** [godotengine/godot#87365]
### Tested versions

- Reproducible in 4.2.1 stable and 4.3.dev [2ababdcc06]

### System information

Godot v4.2.1.stable unknown - Arch Linux 6.7.0-zen3-1-zen #1 ZEN SMP PREEMPT_DYNAMIC - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 (nvidia; 545.29.06) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

When XR shaders are enabled, trying to read from the screen texture with texelFetch() causes the Godot editor to crash when the shader tries to compile. 

[Log from v4.3.dev](https://github.com/godotengine/godot/files/13986909/crash_with_texelFetch_and_xr_shaders.txt)

### Steps to reproduce

1. Enable `xr/shaders/enabled`

2. Use texelFetch() on a texture with the `hint_screen_texture` hint:
```glsl
shader_type spatial;
uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, filter_linear_mipmap;
void fragment() {
	ALBEDO = texelFetch(SCREEN_TEXTURE, ivec2(0, 0), 0).rgb;
}
```

3. Wait for the shader to try to compile

### Minimal reproduction project (MRP)

[texelFetch SCREEN_TEXTURE XR crashes.zip](https://github.com/godotengine/godot/files/13986896/texelFetch.SCREEN_TEXTURE.XR.crashes.zip)

**Comment by clayjohn** [comment]
When users sample from a Multiview screen texture we insert a little shim function `multiview_uv()` to properly include the view index in the UV. This way the same shader can be used in XR and non-XR environments.

However, `multiview_uv()` takes a `vec2` and returns a `vec3`. `texelFetch()` needs an `ivec2` or `ivec3`. I think all we need to do is define an overloaded version of `texelFetch()` that takes an `ivec2` as input and returns an `ivec3`

https://github.com/godotengine/godot/blob/0bcc0e92b3f0ac57d4c4650722f347593a258572/servers/rendering/shader_compiler.cpp#L1332

**Comment by BastiaanOlij** [comment]
@clayjohn indeed, seems like a fairly straight forward change :)

**Comment by BastiaanOlij** [comment]
@CheesecakeCG let us know if #87460 fixes the issue, it applies clayjohns suggestion.

**Comment by CheesecakeCG** [comment]
> @CheesecakeCG let us know if #87460 fixes the issue, it applies clayjohns suggestion.

It doesn't crash anymore, thanks!
