### ISSUE TITLE
Camera2D::get_screen_center_position() and Camera2D::get_target_position() return (0,0) if the camera is not currently active

### ISSUE THREAD

**Issue by Lertsenem** [godotengine/godot#87369]
### Tested versions

- Reproducible in 4.2 stable

### System information

Godot v4.2.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (nvidia; 470.223.02) - Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 Threads)

### Issue description

I tried to make a simple and cheap smooth player tracking node using an inactive `Camera2D`.
Unfortunately the methods `get_screen_center_position()` and `get_target_position` from the node `Camera2D` both always return `Vector2(0,0)` if the camera node is not the active camera.

Maybe this is intentional, but it does not appear so in the documentation.

### Steps to reproduce

Create an inactive Camera2D and enable smoothing as child of a moving node, the two methods return (0,0) when invoked.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please provide a minimum project to help investigating this, it is set under only some conditions, and depends on some other options

**Comment by WhalesState** [comment]
`Camera2D` functionality only works when they are enabled, if you need a smooth track to a node you can use linear interpolation `lerp` on a child node which is set as `top_level`. 
https://docs.godotengine.org/en/stable/tutorials/math/interpolation.html

**Comment by Lertsenem** [comment]
Thanks @WhalesState, that actually makes sense (maybe it could be made explicit in the `Camera2D` node doc though).

Issue feels resolved to me.
