### ISSUE TITLE
Godot permanently broken after importing font

### ISSUE THREAD

**Issue by taylormck** [godotengine/godot#87368]
### Tested versions

- Reproducible in 4.2.1-stable (mono version)
- Reproducible in 4.2.1-stable
- Reproducible in Godot_v3.5.3-stable_mono_win64
- Reproducible in Godot_v3.5.3-stable_win64

### System information

Windows 10 - Godot_v4.2.1-stable_mono_win64
Windows 10 - Godot_v4.2.1-stable_win64

### Issue description

After importing a font, setting it as the project theme's default and running a single scene with a single `Label` in it, Godot has completely ceased to function. The editor crashed immediately and any attempt to restart it ends with an unresponsive window being opened.

I'm not sure if it's important, but the font used was [Silver by Poppy Works on itch.io](https://poppyworks.itch.io/silver).

I've tried fixing it the following ways:
- Deleting the `.godot` folder and restarting the application
- Deleting the project and restarting the application
- Deleting all projects and restarting the application
- Deleting and reinstalling Godot, then starting the freshly installed application
- Deleting Godot and reinstalling via [GodotEnv](https://chickensoft.games/docs/setup/)
- Deleting the folder `C:\Users\<user>\AppData\Roaming\Godot`

Here's what it looks like when starting the editor from Windows Explorer:
![godot_broken](https://github.com/godotengine/godot/assets/2374670/739b7e99-b9b6-4f36-8c57-d56c197840ad)

Running from the command line produces a similar window, but in full screen for some reason.

I am completely flabbergasted as to how installing a font could do this, or how it could persist through a reinstall.

### Steps to reproduce

I'm not exactly sure which step may be the root cause of the issue, and the nature of the problem is such that I can't test further to find out. These are just the steps I did, recalled as best I can.

1. Download a font
2. Import the font into a Godot project
3. Set the font as the theme default in the project settings under `Project Settings > GUI > Theme > Default Font`
4. Run a scene with the font in it
5. Close the running scene
6. This is the point where the editor crashed for me

### Minimal reproduction project (MRP)

[Godot2dPlatformer-main.zip](https://github.com/godotengine/godot/files/13988061/Godot2dPlatformer-main.zip)

**Comment by bruvzg** [comment]
Can't reproduce it. Font seems to be importing and working correctly.

Imported font is stored locally in the project folder (hidden `.godot/imprted` subfolder) and should not be able to affect anything outside the project. So it's almost certainly not related to the font in any way.

It can be an issue with GPU driver (try rebooting and updating GPU drivers).

**Comment by taylormck** [comment]
Alright, I managed to get it running again. The secret was to open Explorer, search `This PC` for `godot`, and delete everything it returns. After that, restart the computer, reinstall Godot, and re-download the project from Github.

I've been able to reopen the project, import the font, and set it as the default.

I still have no idea what went wrong, or what was causing the issue.
