### ISSUE TITLE
Array.sort_custom did not work as expected sometimes

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8737]
**Operating system or device - Godot version:**
Mac OS  godot 2.1.3

**Issue description:**

func sot_array_rand(e1, e2):
	return randf() > 0.5

func test():
    randomize()		
    var array = [1,2,3]		
    array.sort_custom(self, "sot_array_rand")	
    print(array)

output
[3,2,1]
[3,1,2]
[3,2,1]
[[],2,1]   WHAT IS THAT???
**Steps to reproduce:**

**Link to minimal example project:**

**Comment by volzhs** [comment]
I did the samething :) #3327

**Comment by vnen** [comment]
`sort_custom()` function must be consistent in the comparison, so it can't be random. Check the issue mentioned by @volzhs.

Closing as duplicate.
