### ISSUE TITLE
Scene Dock script button unnecessarily restrictive and breaks backward compatibility

### ISSUE THREAD

**Issue by Naros** [godotengine/godot#87383]
### Tested versions

4.3.dev2

### System information

Windows 11

### Issue description

In Godot 4.2 and earlier, we relied on the `EditorPlugin::_edit` function call to open our Visual Scripting script attached to nodes within the scene in our GDExtension Plug-In.

In Godot 4.3, the change https://github.com/godotengine/godot/pull/84284 broke this functionality.  The change unnecessarily restricts implementations to having to register a `ScriptEditorBase` implementation; however, for GDExtensions, there is currently not an exposed way to contribute these, and so this breaks our user's ability to interact with the SceneTree Dock and to quickly jump from a node to a visual script that is attached.

### Steps to reproduce

1. Use Godot 4.3.dev2
2. Install Orchestrator Plugin https://github.com/Vahera/godot-orchestrator/releases (2.0.dev1)
3. Create an orchestration script, attaching it to a scene node in any scene.
4. Attempt to click on the script button next to the scene node, plugin does not react and show the graph window.

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
I wonder if there's an elegant solution to fix this and keep the PR's quality-of-life change. Although, on the surface it sounds better to revert #84284...

**Comment by Mickeon** [comment]
> The following idea works and restores the behavior, not sure if it would be acceptable though as it seems a bit hacky:

Hey. If it actually does fix it, it does not hurt to open a PR with it. It's a regression that does break compatibility to an extent, so it's fairly high priority. At worst it will not be merged as is, at best a better solution may be proposed.
