### ISSUE TITLE
LSP InputEvent.is_action_pressed have wrong and different completion behavior to Input.is_action_pressed

### ISSUE THREAD

**Issue by kaluluosi** [godotengine/godot#87398]
### Tested versions

4.2.1 -stable

### System information

Win10, Core I7-9700,RTX2080

### Issue description

When you type in event.is_action_pressed, it pops up an input action list for you to insert. After you press enter to insert, you find that it also inserts its own double quotes for you and doesn't clean up the double quotes that you input.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/5d9c676a-a587-43a4-8f2c-f4ad1b3975e5)

```gdscript
extends Control

func _ready():
	var event = InputEventKey.new()
	event.is_action_pressed(""ui_accept""
```

But it won't happen on Input.is_action_pressed.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/53c14abe-f752-427c-9b5a-e366ba6c9d75)

```gdscript
extends Control

func _ready():
	Input.is_action_pressed("ui_cancel")

```

PS: It not happens in Godot Editor, just happens in VSCode. 

### Steps to reproduce

While typing Input.is_action_pressed, it's LSP request and response
![Input request](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/5e7d5cae-7c42-4759-9ca8-d51eed2d8dbf)
It respondd the completion item kind is 2 -> lsp::CompletionItemKind::Method
![Input response](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/2e8ae793-a681-4090-976c-5bd7e2b608a5)
![Input lsp](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/50cd99de-a4df-4e0b-afcd-2cc7f420410a)

In the case of InputEvent.is_action_pressed, it's LSP request and response
![InputEvent request](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/7f20f056-355d-4827-afdf-372630573e04)
It responds the  completion item kind is 21 -> lsp::CompletionItemKind::Constant
![InputEvent response](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/152fdd05-fcee-455a-9f45-14f6889f72a2)
![InputEvent lsp](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/22495963-1fa2-420b-8559-3e2ff71738e0)

And I find something interesting in GodotScript LSP server.

While typing InputEvent.is_action_pressed. In the method _find_call_arguments：
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/e6807311-1c96-44d7-8129-e53b3c9692b9)
And because the base is nil, so it is not considered as a method.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/3b191d2a-4693-45ad-8243-17adee2690b1)

And this is the case of Input.is_action_presss：
The LSP server has identified the type of Input.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/83455043-3cb3-461a-8d61-42fae2f7b524)
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/b67c19a0-8c0b-4a5e-8669-948cc99e9ace)

It seems that there has a hard code to force fix the issue of InputEvent not identified. It force return the input action options as CODE_COMPLETION_KIND_CONSTANT.
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/fbff0eaa-7003-4a14-9eab-e77b88696e03)

I can simply fix it by change  CODE_COMPLETION_KIND_CONSTANT to  CODE_COMPLETION_KIND_FUNCTION
![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/dbd34ef3-6d16-4fbd-b241-cb72075fe082)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/1620585/61753c17-b192-41f1-bd2c-b46af7e26e1c)

But it may not the best way to fix it. The best way is to find out why LSP server can't identify the type of InputEvent and figure it,

### Minimal reproduction project (MRP)

no MRP

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot/issues/86488

**Comment by kaluluosi** [comment]
close this
