### ISSUE TITLE
Screen texture weird interaction with ScrollContainer

### ISSUE THREAD

**Issue by Defwentz** [godotengine/godot#87396]
### Tested versions

- Reproducible in 4.2.stable, 4.2.1.stable

### System information

Windows 10 - Godot v4.2.1.stable - Vulkan (GL Compatibility) - dedicated

### Issue description

Screen texture becomes empty (black) outside of ScrollContainer.
![屏幕截图(559)](https://github.com/godotengine/godot/assets/8059644/08bc839a-e101-419f-99c1-ec995e10c7c0)

### Steps to reproduce

In MRP, run the project and the display should be same as issue screenshot.

Other possibly important detail, if ScrollContainer is moved to the same level as ColorRect filter, the problem disappears. If just using `COLOR = texture(SCREEN_TEXTURE, SCREEN_UV);` in the filter shader, problem disappears. 

If a new Label node is added as sibling of ScrollContainer but below it in the node structure, problem disappears. But if it isn't visible or is a Control node for example, problem persists.

### Minimal reproduction project (MRP)

[screen_texture_ui.zip](https://github.com/godotengine/godot/files/13997040/screen_texture_ui.zip)

**Comment by clayjohn** [comment]
Thanks for the report. this was a really quick fix. I made a PR already https://github.com/godotengine/godot/pull/87489
