### ISSUE TITLE
get_total_character_count() returns incorrect count

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#874]
Label.get_total_character_count() is returning a higher count than it should.

To test, add a label, set set some text like 1234567890 (10 characters). Print out the total, and you get 12... Wrong.

**Comment by akien-mga** [comment]
Is this bug still valid in the current master branch? If so, which platform(s) do you reproduce it on?

**Comment by reduz** [comment]
i think this is valid, I merged so many PRs fixing this that I would close
it unless ayone complains again

**Comment by akien-mga** [comment]
Closing then.
