### ISSUE TITLE
Cannot override bone rotation and blend shape when using AnimationTree

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#87400]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

When using AnimationTree, I cannot override the bone rotation and blend shape in code.
Everytime it seems the AnimationTree will reset my overrided bone rotation and blend shape.

### Steps to reproduce

Import a animated model and set up AnimationTree node and active it.

write a script to override bone rotation and blend shape, like below:

```
func _physics_process(delta):
	test.get_node("Armature/Skeleton3D/Cube").set("blend_shapes/Key 1", 1.0)
	test.get_node("Armature/Skeleton3D").set_bone_global_pose_override(b_idx, Transform3D(), 1)
```

No any effect.

### Minimal reproduction project (MRP)

[anim_and_blendshape_override.zip](https://github.com/godotengine/godot/files/13997456/anim_and_blendshape_override.zip)

**Comment by TokageItLab** [comment]
This is a intended behavior. This can be avoided by using the Deterministic = false option. Also you can refer Unity's write default issue.

**Comment by nagasawamaki** [comment]
> This is an intended behavior and you can avoid it by using the Deterministic = false option. Also you can refer Unity's "write defaults" issue.

Thank you for your comment and it do work for the blendshape.

The Deterministic = false option still cant make the rotation work.
