### ISSUE TITLE
Godot Project Manager Layout is broken when trying to access asset library.

### ISSUE THREAD

**Issue by adfriz** [godotengine/godot#87407]
### Tested versions

Tested in 4.2.1 windows 64 bit.

### System information

Windows 10 - Godot 4.2.1 stable 64bit - CPU: i3 2330M - GPU: GT630M

### Issue description

As the title said.

I have record a screen capture.

https://github.com/godotengine/godot/assets/76892624/fc668d38-7f59-4367-8b7e-f0adb835bd4b

### Steps to reproduce

1. Download godot
2. Extract it.
3. Run it.
4. Open asset library.
5. Change the source to community or testing until the library loaded.
6. Look at the layout.

### Minimal reproduction project (MRP)

N/A

**Comment by adfriz** [comment]
In Godot v4.3.dev2.official [352434668] still broken.
![image](https://github.com/godotengine/godot/assets/76892624/1d587341-997f-498a-8c1b-4c5f21a3eb81)

**Comment by eugene87222** [comment]
I'm willing to look into this issue.😄
