### ISSUE TITLE
Full Rect MarginContainer does not work fine in the main scene plugin

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#87412]
### Tested versions

reproducible in 4.2.1.stable 

### System information

Windows 7, 10, Godot 4.2.1 Stable

### Issue description

I tried to make a [main scene plugin](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_main_screen_plugins.html) I put a margin container and made it fully rect but in plugin did not work at all
My scene:
![image](https://github.com/godotengine/godot/assets/92402263/c9c743dc-0f7c-4fe1-a6dc-35543b6061da)
result:
![image](https://github.com/godotengine/godot/assets/92402263/b9904ee6-e7b0-4f36-837f-dd9e54593d2e)
after that, I added some code to my scene script and now it's better
Code:
```
@tool
extends Control

@onready var data_container = $DataContainer
@onready var h = data_container.size.y

func _ready():
	await get_tree().create_timer(5).timeout
	data_container.position.y = 0
	data_container.size.y = h
```
result:
![image](https://github.com/godotengine/godot/assets/92402263/22e01271-0d16-4e97-9ab9-f2a6f598f070)

but why? Is it a bug or do I miss something?

### Steps to reproduce

1. create a main scene plugin
2. add the margin container as a child as the control node and make it a full Rect
3. add a label or anything to show content
4. Test result
or

1. test attached addon

### Minimal reproduction project (MRP)

[addons.zip](https://github.com/godotengine/godot/files/13998192/addons.zip)

**Comment by KoBeWi** [comment]
The MainScreen Control where you add your plugin is a VBoxContainer.
![image](https://github.com/godotengine/godot/assets/2223172/18e44e5a-a430-41a3-9eb0-59c6b47fec49)
You need to set vertical size flags to Fill + Expand to make your node use full size.

I see `get_editor_main_screen()` already returns a VBoxContainer, but maybe it could use an additional clarification somewhere 🤔

**Comment by DexterFstone** [comment]
> The MainScreen Control where you add your plugin is a VBoxContainer. ![image](https://private-user-images.githubusercontent.com/2223172/298306589-18e44e5a-a430-41a3-9eb0-59c6b47fec49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTQ5ODIsIm5iZiI6MTcwNTgxNDY4MiwicGF0aCI6Ii8yMjIzMTcyLzI5ODMwNjU4OS0xOGU0NGU1YS1hNDMwLTQxYTMtOWViMC01OWM2YjQ3ZmVjNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDUyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhMmIxODdkM2ZmMTQ0ZTZlZjNjNDMxNThkZjZlYWRkYzkxNzg5ZjQxOTJmNDRjNGY0ZjEyMzk3MDk3YzUwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jlB9NR600qC_UwfEeT6qRu2zaigI0t2DE3nTcMui4sw) You need to set vertical size flags to Fill + Expand to make your node use full size.
> 
> I see `get_editor_main_screen()` already returns a VBoxContainer, but maybe it could use an additional clarification somewhere 🤔

My Tree:
![image](https://github.com/godotengine/godot/assets/92402263/438d21f2-86e6-4fbd-90c2-5c972bf07db2)

Everything is expanded and fill

**Comment by DexterFstone** [comment]
I changed the type of marginContainer to Control node in problem is fix soo margin container has a problem and it is a bug

**Comment by KoBeWi** [comment]
You did not fix your problem, but you hid it. The Control has wrong size.

**Comment by DexterFstone** [comment]
> The Control has wrong size.

which one?

**Comment by KoBeWi** [comment]
The one you used instead of MarginContainer. You can see the content correctly, because non-Container nodes don't arrange their children.

**Comment by DexterFstone** [comment]
> The one you used instead of MarginContainer. You can see the content correctly, because non-Container nodes don't arrange their children.

I changed again to margin container
I want to know fix the problem
Can u edit my attached file and send it again?

**Comment by KoBeWi** [comment]
Instead of anchors, use the container sizing menu and set it to vertical fill with expand flag:
![image](https://github.com/godotengine/godot/assets/2223172/5aaf3def-16ec-41ed-85e4-65f182139130)
You need to set it in your root node, it will make it take the full available space.

**Comment by DexterFstone** [comment]
> Instead of anchors, use the container sizing menu and set it to vertical fill with expand flag: ![image](https://private-user-images.githubusercontent.com/2223172/298383238-5aaf3def-16ec-41ed-85e4-65f182139130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDEzNTQsIm5iZiI6MTcwNTg0MTA1NCwicGF0aCI6Ii8yMjIzMTcyLzI5ODM4MzIzOC01YWFmM2RlZi0xNmVjLTQxZWQtODVlNC02NWYxODIxMzkxMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMTI0NDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQxZWY1OTQ2MGI5NmM1MWM3MmVkZjM3ODE1YzE4Mjg0MTljOWJlZjY4YjBlN2I2MTIzNmE3NWUwYWRkYTNlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c7pkyVf8LnHRJsJTHa03EKWgyUMJkj_skh5gTEVfLR4) You need to set it in your root node, it will make it take the full available space.

nothing happened

**Comment by KoBeWi** [comment]
[addons.zip](https://github.com/godotengine/godot/files/14001656/addons.zip)

**Comment by DexterFstone** [comment]
> [addons.zip](https://github.com/godotengine/godot/files/14001656/addons.zip)

Do u just check Expand? why is your file working but when I do that is not work?

**Comment by KoBeWi** [comment]
Enable Expand and then click Fill.

**Comment by DexterFstone** [comment]
> Enable Expand and then click Fill.

![image](https://github.com/godotengine/godot/assets/92402263/d72c1d1e-d5e8-451f-9f42-c44d8e71bf94)
![image](https://github.com/godotengine/godot/assets/92402263/f7ec15ef-94ad-4a71-9835-1a7194ac855a)

**Comment by KoBeWi** [comment]
Did you set it for the *root* node? (Control)
Also when you change it, be sure to reload the plugin.

I used the toolbar menu when setting it, but it should be the same using the inspector.

**Comment by DexterFstone** [comment]
> Did you set it for the _root_ node? (Control) Also when you change it, be sure to reload the plugin.
> 
> I used the toolbar menu when setting it, but it should be the same using the inspector.

yes I do
one more thing I tested, I created a new scene and it worked fine so it is a bug but rare
