### ISSUE TITLE
The strange behavior exhibited by RigidBody2D when calling the move_and_collide() method.

### ISSUE THREAD

**Issue by Waiting-4-Godot** [godotengine/godot#87413]
### Tested versions

Reproducible in: 4.0.3.stable, 4.1.stable, 4.2.1.stable, 4.3.dev2

### System information

Windows 10 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz

### Issue description

https://github.com/godotengine/godot/assets/127111270/1258218c-5c2e-4a08-aa80-ae0093bf16c1

### Steps to reproduce

Running and moving the window may potentially reproduce the bug.
However, sometimes I can reproduce this bug just by doing nothing, simply by running it.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/13998300/MRP.zip)

**Comment by Waiting-4-Godot** [comment]
I retested it again and found that there is still an issue.
This time, I just call the method, move_and_collide(), in the _process().
```GDScript
func _process(delta: float) -> void:
	rigid_body.move_and_collide(Vector2.LEFT * 200 * delta)
```

https://github.com/godotengine/godot/assets/127111270/a0f94ee0-13d6-44e2-96de-056918c85069

**Comment by AThousandShips** [comment]
Does it work if you call it in `_pysics_process`?

**Comment by Waiting-4-Godot** [comment]
I tested it, and it works fine in the _physics_process function.

**Comment by AThousandShips** [comment]
Then that's the problem, you should always do physics in the right method I'd say, see [here](https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#physics-process-callback)

**Comment by Waiting-4-Godot** [comment]
Oh, I get it now!
