### ISSUE TITLE
Fix dragging materials onto meshes

### ISSUE THREAD

**Issue by suopsuop** [godotengine/godot#87425]
### Tested versions

- Reproducible in v4.2.stable.mono.official [46dc27791]
- Reproducible in v4.3.dev1.mono.official [9d1cbab1c]
- Not reproducible in v3.5.3.stable.official [6c814135b] (dragging materials not a feature then I don't think)

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.4629) - Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz (16 Threads)

### Issue description

When dragging materials onto meshes, other meshes in the path of your cursor while dragging will be reset to whatever they were originally. This only happens when dragging a material over the same material.

This can be bypassed by directly assigning the materials in the inspector but it's hidden under submenus, which is annoying for a task that needs to be repeated often. 

This does not happen with shader materials, but shader materials cannot be dragged. 

https://github.com/godotengine/godot/assets/62972779/049359b5-159a-45df-a979-c784fdfc6387

The meshes were created in Blender, exported in GLTF, and "made local" in the actual tscn file.

### Steps to reproduce

1. Open world.tscn
2. Drag a material (StandardMaterial3D) onto a mesh
3. Drag again, with your cursor movement crossing the path of the first mesh you changed the material off
4. It should reset the first meshes texture to whatever its default is.

### Minimal reproduction project (MRP)

[DragMaterialsBugProj.zip](https://github.com/godotengine/godot/files/13999697/DragMaterialsBugProj.zip)

**Comment by AlexOtsuka** [comment]
I can confirm this happens on 4.2.1.
Does not happen in 4.3, I believe it was fixed by https://github.com/godotengine/godot/pull/84486.

**Comment by suopsuop** [comment]
Ah sweet, thanks for your reply!
