### ISSUE TITLE
Names of ClassDB-bound methods changed

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#8742]
**Operating system or device - Godot version:**
Linux 4.11
Godot master e883cdafa6f3b98d1f30e555aed0044782f6a5c4

**Issue description:**
Some bound methods were renamed in 3.0. This brings issues, when those methods are called from C++ code. This is an example from scene/gui/tree.cpp:
```v_scroll->call_deferred("set_val", ofs - screenh + h);```
It fails (silently) because "set_val" was renamed into "set_value" in 3.0.

This probably happens in other files, too. Checking all occurrences of call_deferred() and related functions that call bound methods will be necessary.
Also displaying an error when a call fails would make debugging easier.

The example above is the cause for a bug, where trees don't scroll when using the arrow-down key to navigate.

**Comment by akien-mga** [comment]
That's typically something that any contributor could do by grepping for `call_deferred` and checking manually all of them. Have fun :)

**Comment by reduz** [comment]
that was the only one in all the source code..
