### ISSUE TITLE
Remote debugger unable to connect means unable to run project from editor

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#8744]
**Operating system or device - Godot version:**
Win 7 64 bit, Godot built from 2.1 branch

**Issue description:**
Can't start project from editor (neither F5 nor F6). Output only says debug process started, then debug process stopped.
Console reveals that connection to remote debugger failed (status 1, then status 3 twice, then 
Remote Debugger unable to connect.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Faless** [comment]
@Zireael07 can you provide the log of the output you get by running the editor from the command line?

**Comment by Zireael07** [comment]
@Faless: in 2 weeks, sorry, leaving for holidays as I type

**Comment by Zireael07** [comment]
I'm closing this as the issue seems to have fixed itself in the meantime.
