### ISSUE TITLE
Calling move_and_slide() within a script attached to CharacterBody3D node results in "det == 0" error logs

### ISSUE THREAD

**Issue by yashrahmed** [godotengine/godot#87457]
### Tested versions

Reproducible in 
- 4.2.1.stable.official.b09f793f5 
- 4.0.3.stable.official.5222a99f5

### System information

- Godot v4.2.1.stable
- Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+)
- dedicated NVIDIA GeForce GTX 1060 (nvidia; 525.147.05)
- Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

After setting up a world scene with a StaticBody3D and a Player character with CharacterBody3D nodes respectively, the character moves correctly in response to the user inputs but I see a ton of error logs that look like the following

```
E 0:00:00:0654   player.gd:22 @ _physics_process(): Condition "det == 0" is true.
E 0:00:00:0654   player.gd:22 @ _physics_process(): Condition "det == 0" is true.
 ```
The stack trace within the error looks like the following
```
 <C++ Source>   core/math/basis.cpp:47 @ invert()
 <Stack Trace>  player.gd:22 @ _physics_process()
```
Note that the game works just fine when I launch it from the editor. 
I did not attempt to test the exported version of the game.

### Steps to reproduce

1. Open and import the project into Godot 4.2.
2. Launch the main scene.
3. The errors log will continuously appear in the debugger.

![Screenshot from 2024-01-21 20-25-06](https://github.com/godotengine/godot/assets/8014511/143e45ed-6b9b-4cc1-8529-f385514d88e8)

### Minimal project
[3d_game_det_0_defect_MRP_upload.zip](https://github.com/godotengine/godot/files/14004183/3d_game_det_0_defect_MRP_upload.zip)

**Comment by AlexOtsuka** [comment]
Hello @yashrahmed,

This is due to the scale property of your CollisionShape3D being set to 0, which leads to an exception being thrown in `core/basis.cpp`:

```
void Basis::invert() {
	real_t co[3] = {
		cofac(1, 1, 2, 2), cofac(1, 2, 2, 0), cofac(1, 0, 2, 1)
	};
	real_t det = rows[0][0] * co[0] +
			rows[0][1] * co[1] +
			rows[0][2] * co[2];
#ifdef MATH_CHECKS
	ERR_FAIL_COND(det == 0);
#endif
	real_t s = 1.0f / det;

	set(co[0] * s, cofac(0, 2, 2, 1) * s, cofac(0, 1, 1, 2) * s,
			co[1] * s, cofac(0, 0, 2, 2) * s, cofac(0, 2, 1, 0) * s,
			co[2] * s, cofac(0, 1, 2, 0) * s, cofac(0, 0, 1, 1) * s);
}
```

Changing the scale to 1 will clear all the errors.

**Comment by Rindbee** [comment]
Maybe in the editor, setting a value like this should show a warning.

**Comment by yashrahmed** [comment]
@AlexOtsuka - Thanks a lot. That fixed the problem.

**Comment by troynall** [comment]
The same thing happened to me. However, The Scale property indeed reflect x =1 y=1 z=1 for the CollisionShape3D.
Even through it visually looks like 1 x 1 x 1. It is not. To fix the problem, I just manually re-entered the 1 x 1 x 1.
I am using Version 4.2.2.
