### ISSUE TITLE
Jitter issue when using the region editing area and animation tree together in sprite2D

### ISSUE THREAD

**Issue by wsqrin** [godotengine/godot#87455]
### Tested versions

godot 4.3dev2 
godot 4.2.1

### System information

win11 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

### Issue description

The region of sprite2D was used in AnimationPlayer_ Rect, where the idle animation has 6 frames and the running animation has 8 frames, this issue occurs when using the animation tree and region editing area together. If the region is not used, using the frame of the image directly will not cause any problems. So I guess that if the editing area size of idle is also equal to 8 frames, there may not be any issues. I don't know if there is any solution.

### Steps to reproduce

1. Use the region of sprite2D to select the editing area and create an animation

2. Use the animation tree to use AnimationNodeStateMachine and create a Move animation (add blendspace1D). Select the idle animation in the middle, select the running animation on the left and right sides, and then connect start and move

### Minimal reproduction project (MRP)

[Knight.zip](https://github.com/godotengine/godot/files/14003640/Knight.zip)

**Comment by timothyqiu** [comment]
In each animation, make sure to set the Update Mode of `region_rect` track to Discrete (the one using 3 dots as its icon).

![image](https://github.com/godotengine/godot/assets/372476/9733a14f-6b3a-4ed5-8e0e-8d7878f7d83a)

**Comment by wsqrin** [comment]
Sorry, after following your prompts to adjust, I encountered an exception and there was a flicker on the animation editing interface

https://github.com/godotengine/godot/assets/44998695/58133116-3506-4504-8089-a462b468d930

**Comment by timothyqiu** [comment]
In this case, change the Blend Mode of Move state in your AnimationTree:

![image](https://github.com/godotengine/godot/assets/372476/0ff4f3b8-3b24-47a5-aca1-3979de3016a1)

**Comment by wsqrin** [comment]
😂Thank you very much for your help
