### ISSUE TITLE
TextEdit minimap adds an extra space for tab characters compared to spaces

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#87453]
### Tested versions

Latest master at the time (0bcc0e92b3f0ac57d4c4650722f347593a258572)

### System information

Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Minimap is supposed to treat each space as 1 pixel. But my tab size is 3, and the TextEdit minimap displays it like it's 4.

![image](https://github.com/godotengine/godot/assets/85438892/2a3b82c8-28ed-4aca-8133-1e488b4cd2c0)

### Steps to reproduce

The issue is most visible when you use Ctrl+Shift+Y and Ctrl+Shift+I to toggle between spaces and tabs for indents.

### Minimal reproduction project (MRP)

N/A editor issue

**Comment by jsjtxietian** [comment]
For me it seems it's ok 

Tab size 1:
![image](https://github.com/godotengine/godot/assets/8315986/b56661f6-6863-432a-86a7-193f1b69cd0a)

Tab size 4:
![image](https://github.com/godotengine/godot/assets/8315986/68f67018-d654-4f2d-91d0-7cc5abec6786)

Reading the code it seems uses the correct tab size too:

```
int minimap_tab_size = minimap_char_size.x * text.get_tab_size();
```

**Comment by MewPurPur** [comment]
Oh, so I was misled.

**Comment by MewPurPur** [comment]
Edited to reflect the actual issue.

**Comment by Mickeon** [comment]
I... took a look at the code, I have no clue what is causing this, it may be a matter of the renderer rounding floating-point numbers up.
