### ISSUE TITLE
Open button gets disabled for some help classes when searching

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#87472]
### Tested versions

4.3 dev 0bcc0e9
Does not seem to happen in 4.3 dev2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/4d71ec7a-1749-4227-bb6e-644ada6fc937

Seems to affect abstract classes. You need to select another class and back to enable opening.

### Steps to reproduce

1. Press F1
2. Type "StyleBox"
3. Press Open

### Minimal reproduction project (MRP)

N/A

**Comment by YuriSizov** [comment]
If it's recent, then it's probably related to https://github.com/godotengine/godot/pull/77554 and https://github.com/godotengine/godot/pull/77471 by @AThousandShips

**Comment by AThousandShips** [comment]
Will take a look

**Comment by AThousandShips** [comment]
Found it, it's due to a quirk in `TreeItem` where it doesn't set itself as not selected when removed, causing the item when added back in and *then* selected to not select itself

Will make a PR
