### ISSUE TITLE
"AddRange" in "System.Collections.Generic.List" causes an exception

### ISSUE THREAD

**Issue by jlx-286** [godotengine/godot#87471]
### Tested versions

- Reproducible in: Godot v3.5.3.stable.mono.official [6c814135b]
- Not reproducible in: Godot v4.2.1.stable.mono.offical [b09f793f5]<del>, Unity 2018.4.13f1</del>

### System information

Windows 10 and Ubuntu 20.04.6 LTS - Godot v3.5.3.stable.mono and Godot v4.2.1.stable.mono

### Issue description

- "[AddRange](https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1.addrange)" in "[System.Collections.Generic.List](https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1)" causes an exception in "Ubuntu 20.04.6 LTS" always and in "Windows 10" sometimes.
- copied from "Debugger > Errors": 
```
E 0:00:00.638   void System.Array.Copy(System.Array , Int32 , System.Array , Int32 , Int32 ): System.RankException: Only single dimension arrays are supported here.
  <C++ Error>   Unhandled exception
  <C++ Source>  :0 @ void System.Array.Copy(System.Array , Int32 , System.Array , Int32 , Int32 )()
  <Stack Trace> :0 @ void System.Array.Copy(System.Array , Int32 , System.Array , Int32 , Int32 )()
                :0 @ void System.Collections.Generic.List`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].set_Capacity(Int32 )()
                :0 @ void System.Collections.Generic.List`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].EnsureCapacity(Int32 )()
                :0 @ void System.Collections.Generic.List`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InsertRange(Int32 , System.Collections.Generic.IEnumerable`1[System.Byte] )()
                :0 @ void System.Collections.Generic.List`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AddRange(System.Collections.Generic.IEnumerable`1[System.Byte] )()
                FluidManager.cs:225 @ System.Byte[] FluidManager.MidiToSamples(System.String , System.Int32& , System.Int32& )()
                Test.cs:18 @ void Test._Ready()()
```

### Steps to reproduce

play the (Godot) project. (libfluidsynth2 or libfluidsynth3 is required in Linux)

### Minimal reproduction project (MRP)

<https://github.com/jlx-286/lunatic-rave-3/tree/master/LR3_default(480p)> or <https://gitee.com/jlx-286/lunatic-rave-3/tree/master/LR3_default(480p)>

**Comment by bs-mwoerner** [comment]
It looks like the only relation to Godot is that you call `FluidManager.MidiToSamples()` from a Godot node? Other than that, this seems to run only user code, so I suppose there's little Godot can do to solve the problem. There's likely some kind of memory corruption in the `unsafe` part of the C# code, which overwrites the metadata of the .NET arrays.
