### ISSUE TITLE
SpatialMaterial - missing Ambient Light factor/Color

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8747]
3.0 SpatialMaterial and ShaderMaterial are affected by AmbientLight from WorldEnvironment node.
Problem is there is no way to control how much they are affected per material basis.

Additional property for materials should be added allowing to control how much they receive (or override) Ambient Light or how they tint it their way.
Very important for stylized rendering and not only.

**Comment by reduz** [comment]
Sorry, there is no longer any ambient light in PBR. This is not possible due to how it works, as it just lerps ambient with metalness.

**Comment by n-pigeon** [comment]
OK I understand :)

I can workaround it with custom shaders.
