### ISSUE TITLE
tool script won't print to console

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#8748]
macOS Sierra Godot 2.1.3

**Issue**
Adding the tool keyword to a script enables the script within the editor for custom functionality. In order to debug, you would expect to use print() and get information in the Output section but print() only works when running as a game and not when running in the editor

**Steps to reproduce:**
Create a new project, add a script, add the tool keyword at the beginning, restart godot or the project.
Add print("Hello") to the script. You would expect it to work in the editor like in a game, but only works in-game. 
Add a second scene and switching between 2 scene tabs in 2D mode triggers the _ready function. Any other code will execute except the print function

**Link to minimal example project:**
[Tool print.zip](https://github.com/godotengine/godot/files/998913/Tool.print.zip)

**Comment by karroffel** [comment]
in the editor, `print()` prints to the engine console, so it doesn't show up in the output tab but in the regular stdout of the editor.

**Comment by Tarocco** [comment]
@karroffel This seems to be a steep caveat more than an error. Basically, it would make more sense to print to the in-editor console, not the separate console window that sits in the background.
In fact, I don't even know if those show up on Mac or Linux unless Godot is called from a CLI. [Thanks to @neikeq for pointing this out!](https://github.com/godotengine/godot/issues/8903#issuecomment-303902340)

**Comment by Zireael07** [comment]
One more confirmation that tool scripts don't print to in-editor console.

**Comment by a-lexu** [comment]
@Tarocco the separate console window doesn't show up on Mac

**Comment by Tarocco** [comment]
@a-lexu does it help if you start Godot from CLI? It's not a perfect solution, but it could help!
This ought to be improved, though.

**Comment by a-lexu** [comment]
Yeah thanks, I just print to a label in the meantime
