### ISSUE TITLE
HTML Framerate Dependent on Window Size, Despite "viewport" stretch mode

### ISSUE THREAD

**Issue by pkmollman** [godotengine/godot#87496]
### Tested versions

- Reproduceable in: 3.5.3, 4.2.1

### System information

Windows 10, Godot 4.2.1 and 3.5.3, RTX 3070, Driver 546.01, Vulkan

### Issue description

If I set display stretch mode to "viewport" and stretch aspect to "keep", resolution 640x480. I get a loss of frames dependent on my browser window size. 44 fps for 1080p, 24 fps for 1440p. Since the game is render at 640x480 always, shouldn't the frames be the same? This is with a blank 3d scene, just a camera.

### Steps to reproduce

New project:
resolution = 640x480
stretch mode = viewport
stretch aspect = keep

make a 3d scene with a camera, and a canvas layer with a label, attach a script to the label with
```
func _process(delta):
	text = str(Engine.get_frames_per_second())
```

run web export, and change the size of the browser window to watch framerate go up and down.

### Minimal reproduction project (MRP)

[bezier.zip](https://github.com/godotengine/godot/files/14018551/bezier.zip)

**Comment by Sauermann** [comment]
related to:
- #36507
- https://github.com/godotengine/godot-proposals/issues/6221

**Comment by pkmollman** [comment]
I didn't have hardware acceleration on.... This issue is basically non-existent when you actually use your dang hardware.

**Comment by Calinou** [comment]
> I didn't have hardware acceleration on.... This issue is basically non-existent when you actually use your dang hardware.

For future reference, you can check whether hardware acceleration works in Chromium-based browsers by opening `chrome://gpu` in the browser's address bar.
