### ISSUE TITLE
Missing set_no_delay() for TLS streams

### ISSUE THREAD

**Issue by agorangetek** [godotengine/godot#87501]
### Tested versions

4.2.1 Stable

### System information

Windows 11 Pro

### Issue description

Missing set_no_delay() for TLS streams

### Steps to reproduce

No steps needed

### Minimal reproduction project (MRP)

Not required

**Comment by AThousandShips** [comment]
Missing how? When did this vanish? Is this a feature you're suggesting? Then it should be a [proposal](https://github.com/godotengine/godot-proposals)

**Comment by agorangetek** [comment]
> Missing how? When did this vanish? Is this a feature you're suggesting? Then it should be a [proposal](https://github.com/godotengine/godot-proposals)

My bad, yes it should be a proposal.

**Comment by Calinou** [comment]
- Proposal opened: https://github.com/godotengine/godot-proposals/issues/8946
