### ISSUE TITLE
Font size is not accurate

### ISSUE THREAD

**Issue by WhalesState** [godotengine/godot#87519]
### Tested versions

4.2.1 stable

### System information

win 10

### Issue description

with pixel fonts, it's hard to set the height of the font correctly!
this is a font that is just 8 pixels height and it renders correctly when the font size is 9 not 8

https://github.com/godotengine/godot/assets/53877170/44a74b01-8f43-4a86-8a5f-22c1f515bc49

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
For the reference, notes for the underlying API (from FreeType docs):

> **FT_Set_Pixel_Sizes**
>
> Call FT_Request_Size to request the nominal size (in pixels).
> ....
> You should not rely on the resulting glyphs matching or being constrained to this pixel size.

**Comment by AThousandShips** [comment]
Generally a font size *isn't* a guarantee for *any* size in the resulting output, it's a hint and each font applies the concept differently, it's *usually* a measure of some standard unit like the em space

**Comment by WhalesState** [comment]
Ok, it seems that it's based on the font itself, after making changes and aligning the points of each glyph the issue was solved and it is accurate now, the only issue is that sometimes it renders parts of the font outside the Label rect but it can be solved with clipping. thanks.
![image](https://github.com/godotengine/godot/assets/53877170/7bd8d467-8634-4202-9bee-ddec7ad4b666)
