### ISSUE TITLE
TabContainer Floating Tabs

### ISSUE THREAD

**Issue by wez470** [godotengine/godot#87511]
### Tested versions

- v4.2.stable.official [46dc27791]
- v4.1.stable.official [970459615]

### System information

Godot v4.2.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

TabContainer tabs render fine in the 4.1 version of Godot I've listed above. In 4.2, they float above the tab panel and seem to shrink as much as they can around the tab text. Toggling various settings (e.g. `Clip Tabs` on the `TabContainer`) seems to fix the issue.

https://github.com/godotengine/godot/assets/4305699/a07e822a-5dd2-4a9a-b982-735426f543d3

### Steps to reproduce

- Create a tab container with a couple tabs in 4.2
- Increase font size on the tab container
- Play the project
- Remote toggle Clip Tabs on the TabContainer to see the rendering fix itself.
- Open the project in 4.1 to see the issue is gone.

### Minimal reproduction project (MRP)

[TabContainerTest.zip](https://github.com/godotengine/godot/files/14027729/TabContainerTest.zip)

**Comment by WhalesState** [comment]
I'm using 4.2.1, and win 10, and the tab container works fine, can you please test it with the latest stable 4.2.1 editor ?

**Comment by devloglogan** [comment]
Using the MRP, issue appears present on 4.2 branch. Opening it with master, bug cannot be recreated.

**Comment by omgcraig** [comment]
I wanted to add that this issue is still present. Change the font size or add a custom font to a TabContainer and the tabs will be misaligned. Togging a setting will fix the issue, but it will return when you load the scene or run the project.

**Comment by Calinou** [comment]
@omgcraig Which Godot version did you test this on? @devloglogan's comment said that this issue can't be reproduced more on latest `master` (try [4.3.dev3](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-3/)).

**Comment by omgcraig** [comment]
I'm found that on Godot 4.3 Dev 3, if you create a TabContainter with a few tabs, add a theme then add a custom font, the tabs will pop out and be misaligned.

**Comment by WhalesState** [comment]
This issue is related to the `TabBar` node not the `TabContainer`. I will try to fix it.
