### ISSUE TITLE
Tween#follow_* method documentation confusing

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot#8752]
I'm trying to figure out what the documented [follow_*](http://docs.godotengine.org/en/stable/classes/class_tween.html) methods do, but some non-standard terminology is being used that makes it unnecessarily hard.

The only usages of "follow" I'm familiar with are 1. follow as in an object following a path, or 2. "follow" as in Twitter. What does it mean to follow a method? I've tried mentally replacing "follow" with "subscribe", but that doesn't make sense either. "Monitor" might also work, provided it can't possibly be confused with the synchronization construct.

And then...what does it mean to animate a method?

Lastly there are a couple spelling mistakes -- s/consequitive/consecutive/ and s/begining/beginning/).

---
I'm really just trying to figure out what this method does. If, for example, I have this code:

```
tween.follow_method(get_node("foo"), "calculate", 3, get_node("bar"), "pos_x", 5.0, Tween.TRANS_LINEAR, Tween.EASE_IN_OUT)
```

then that's is equivalent to the following pseudocode, right?
```
bar_node.pos_x(foo.calculate(3))
for i in 5 seconds:
    var tweened_value = 3 + calculate_tween(i, 5.0, TRANS_LINEAR, EASE_IN_OUT)
    bar_node.pos_x(foo.calculate(tweened_value))
```
Actually, I'm reasonably sure this is incorrect -- I'm not sure how to incorporate the `Methods are animated by calling them with consequitive values.` statement. Would appreciate some help 😄

**Comment by shackra** [comment]
For some reason follow_property does that the target object "jumps" to the place my "main" object was, I was expecting something like a smooth movement towards the "main" object.

**Comment by kubecz3k** [comment]
We now have description of `follow_property` method in the docs, which I believe should be less confusing: 
http://docs.godotengine.org/en/3.0/classes/class_tween.html?highlight=tween#member-function-description
