### ISSUE TITLE
Collision is broken when disabled after pausing

### ISSUE THREAD

**Issue by Stovehead** [godotengine/godot#87524]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5] and 4.0.stable.official [92bee43ad].

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4575) - 13th Gen Intel(R) Core(TM) i7-1360P (16 Threads)

### Issue description

If a game is paused while 2 CollisionBoxes are overlapped, then unpaused, and one of them is disabled, the other one will fail to recognize this, and it will believe that it is colliding with the other CollisionBox as long as they both exist.

### Steps to reproduce

Run the program. There are two timer nodes. When the first one, the one under the root Node2D node runs, it will briefly pause the game. When the other one runs, it will disable one of the Area2D's collision and print "disable". The other Area2D is continually printing `get_overlapping_areas()`. It will not ever change, even after the collision is disabled. If the pausing functionality is disabled, it works as expected.

### Minimal reproduction project (MRP)

[PauseBug2.zip](https://github.com/godotengine/godot/files/14031905/PauseBug2.zip)

**Comment by Sauermann** [comment]
Related to #60577, which describes a similar problem in 3.x.

**Comment by AThousandShips** [comment]
Can you test with [4.3-dev2](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-2/), might be fixed by:
* https://github.com/godotengine/godot/pull/81809

**Comment by Stovehead** [comment]
I tried it in 4.3-dev2, and it has a different issue instead. After the pause, the Area2D fails to recognize the overlapping area, even if it is not disabled.

**Comment by AThousandShips** [comment]
So then the original issue is solved, the other needs to be evaluated if it *is* a bug or not

I'd say to close this an open a new report for that issue as it's separate and different 🙂

**Comment by Stovehead** [comment]
Good call.
