### ISSUE TITLE
Baking lightmaps always prints a warning message about PSO caching

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#87532]
### Tested versions

4.3.dev 0bcc0e92b

### System information

Godot v4.3.dev (0bcc0e92b) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

When baking LightmapGI, I always get a warning message:

```
WARNING: There's already a RenderingDeviceDriverVulkan instance doing PSO caching. Only one can at the same time. This one won't.
     at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:2198)
```

Assuming this is a limitation we can't lift (and not a bug), I suggest silencing this particular instance when baking lightmaps since it's not relevant information for end users here. This could be done by moving it to `print_verbose()` or having a property to disable the warning in local RenderingDevices.

PS: The warning message could also mention which instance of the RenderingDevice it is (e.g. with an object ID), so you can distinguish it when multiple local RenderingDevices are printing it.

cc @DarioSamo @RandomShaper 

### Steps to reproduce

- Bake a LightmapGI node.

### Minimal reproduction project (MRP)

[test_lightmap_preview_bake_4.x.zip](https://github.com/godotengine/godot/files/14040292/test_lightmap_preview_bake_4.x.zip)

**Comment by DarioSamo** [comment]
Can you confirm if https://github.com/godotengine/godot/pull/87340 fixes it?

**Comment by Calinou** [comment]
> Can you confirm if https://github.com/godotengine/godot/pull/87340 fixes it?

That fixes it, thanks :slightly_smiling_face:
