### ISSUE TITLE
Lightmap denoiser breaks when using Physical Light Unit

### ISSUE THREAD

**Issue by atirut-w** [godotengine/godot#87531]
### Tested versions

Reproducible in v4.2.1.stable.official [b09f793f5] and v4.2.stable.official [46dc27791]

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

The lightmap denoiser seemingly stops doing its job when Physical Light Unit is enabled.

Without PLU:
![image](https://github.com/godotengine/godot/assets/25323231/7dc972a7-119d-48c4-904a-535460042ba3)

With PLU:
![image](https://github.com/godotengine/godot/assets/25323231/6e49c1b3-9516-4110-8074-87f8ccbe1d59)

### Steps to reproduce

1. Set up a lightmapped scene
2. Bake
3. Enable PLU
4. Bake again & compare results

### Minimal reproduction project (MRP)

[PLU Breakdown.zip](https://github.com/godotengine/godot/files/14039931/PLU.Breakdown.zip)

**Comment by Calinou** [comment]
The baked lightmap is much brighter when baked with physical light units, as evidenced by what happens if you disable physical light units then reload the project:

![image](https://github.com/godotengine/godot/assets/180032/71a5a445-64f0-4483-9a6c-a2802a90cfaf)

**Comment by atirut-w** [comment]
I tried something and then found out that LightmapGI does not default to using the scene's environment-set camera attributes when not assigned. Assigning a camera attribute to LightmapGI solves the issue.

Should I keep this issue open or open a proposal?

**Comment by clayjohn** [comment]
> I tried something and then found out that LightmapGI does not default to using the scene's environment-set camera attributes when not assigned. Assigning a camera attribute to LightmapGI solves the issue.
> 
> Should I keep this issue open or open a proposal?

This is the expected behaviour. The Lightmap will bake the input brightness without a CameraAttributes resource. Assigning a CameraAttributes resource will reduce the baked exposure to more reasonable levels.

Feel free to open a proposal if you have an idea on how to make this more clear for users!
