### ISSUE TITLE
Remote debug works only on "localhost", but not on "192.168.x.x"

### ISSUE THREAD

**Issue by Rult** [godotengine/godot#87547]
### Tested versions

- Reproducible in 4.2.1.stable, 4.0.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3640) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Remote debug (web game test) works only on ```http://localhost:8060/tmp_js_export.html``` but not on ```http://192.168.x.x:8060/tmp_js_export.html``` and even on ```http://127.0.0.1:8060/tmp_js_export.html``` on the same computer which hosts the HTTP server, not to mention web browsers on the Android phone, which were the goal platform to test the game.

For the record, I've also tested if nginx (another web server program) works, and both the host computer and the phone can access its default page. Ping works too.

### Steps to reproduce

1. Open some Godot project with HTML5 export set up (or just open MRP).
2. Run "Remote Debug" (in upper right corner) -> "Run in Browser".
3. Find your IP address (with ```ipconfig``` command in PowerShell, the IP is next to ```IPv4 Address```)
4. Replace ```localhost``` (on page opened in step 2) with ```127.0.0.1``` or the address found in step 3.

Expected result:
The game loads (and says "The game was successfully loaded!")

Actual result:
The browser doesn't load the game (and says "Unable to connect")

### Minimal reproduction project (MRP)

[MRP_RemoteDebug_source.zip](https://github.com/godotengine/godot/files/14043391/MRP_RemoteDebug_source.zip) (8 KB uncompressed)

**Comment by Rult** [comment]
It works! (Though the game gives "missing features" error, but that's an another issue)
Thank you, I'll close the issue now.

**Comment by Calinou** [comment]
Reopening, as this should be documented.
