### ISSUE TITLE
iphone build - dereferenced NULL

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8754]
This is purely nitpicking, when building for iOS (maybe also OSX, haven't checked) the build logs are filled with this warning repeating lots:
```
In file included from core/ustring.h:35:
core/vector.h:150:19:{150:20-150:28}: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference,2]
                        const T &aux = *((T *)0); //nullreturn

```

I'm wondering if its worth changing the build parameters to suppress this warning or rewrite the line of code. It makes it hard to find the actual errors in building :)

**Comment by Hinsbart** [comment]
Also happens on linux when compiling with clang.
Yeah, something has to be done about this... My IDE has trouble keeping up with all those warnings :P
For a full build, I get around 30k of those warnings then QtCreator just stops parsing compiler output, very annoying :p

**Comment by RandomShaper** [comment]
I'm working on it. Will submit a PR in a few hours.
