### ISSUE TITLE
DirAccess instance methods `file_exists` and `dir_exists` do not find files/dirs in exported projects 

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#87552]
### Tested versions

Godot Engine v4.2.stable.official.46dc27791

### System information

Apple - Apple M1 Pro: macOS Ventura 13.4.1

### Issue description

Instances of `DirAccess` return false for files that exist in exported projects.
Instances of `DirAccess` return false for directories that exist in exported projects.

The static methods work as expected.

### Steps to reproduce

The following does not add any files or directories
* `d.file_exists` always returns false when given a path to a file in an exported project (`res://some_script.gd`)
* `d.dir_exists` always returns false when given a path to a directory in an exported project (`res://tests`)

``` gdscript
var files = []
var directories = []
var d = DirAccess.open(path)
d.list_dir_begin()
var fs_item = d.get_next()
var full_path = ''
while(fs_item != ''):
	full_path = path.path_join(fs_item)

	if(d.file_exists(full_path)):
		files.append(full_path)
	elif(d.dir_exists(full_path)):
		directories.append(full_path)

	fs_item = d.get_next()
d.list_dir_end()
```

The following does work (changed to use `FileAccess` and `DirAccess` in `while` loop)
``` gdscript
var files = []
var directories = []
var d = DirAccess.open(path)
d.list_dir_begin()
var fs_item = d.get_next()
var full_path = ''
while(fs_item != ''):
	full_path = path.path_join(fs_item)

	if(FileAccess.file_exists(full_path)):
		files.append(full_path)
	elif(DirAccess.dir_exists_absolute(full_path)):
		directories.append(full_path)

	fs_item = d.get_next()
d.list_dir_end()
```

### Minimal reproduction project (MRP)

I didn't make a project, but this is what I had to change in GUT to get it to find files and directories in an exported project.  I can make a project if need be.

Notably I had to change 
```
d.file_exists(full_path) 
# to
FileAccess.file_exists(full_path)
```
and 
```
d.dir_exists(full_path)
# to 
DirAccess.dir_exists_absolute(full_path)
```

https://github.com/bitwes/Gut/pull/560/files

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/37646.
