### ISSUE TITLE
The velocity property is missing from the editor inspector in CharacterBody2D node.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#87556]
### Tested versions

v4.2.1.stable.official [b09f793f5]
Godot v4.2.1.stable - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-14-generic (64-bit)
Graphics Platform: X11
Processors: 16 × 12th Gen Intel® Core™ i7-1260P
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics

### System information

Godot v4.2.1.stable - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

### Issue description

The `velocity` property is missing from the inspector in `CharacterBody2D`

https://docs.godotengine.org/en/stable/classes/class_characterbody2d.html#properties

### Steps to reproduce

Create/add to a scene `CharacterBody2D` node. Search for `velocity` in inspector. Only way to see it's value while debugging is using print(). Does not show up in 

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
This is likely done by design, as changing velocity in the editor inspector would have no noticeable effect once you run the project. It could be displayed as read-only, but this would only be relevant in the remote inspector then.
