### ISSUE TITLE
Color picker in directionallight3d crashes godot.

### ISSUE THREAD

**Issue by MrNull1** [godotengine/godot#87557]
### Tested versions

I know it is for sure reproducible in 4.1.1.

### System information

Macos Sonoma, M1 chip.

### Issue description

Whenever you use the color picker in a directional light 3d, it crashes godot.

### Steps to reproduce

Add a directionallight3d,
use the color picker to change the color.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Does this occur with any color picker in the editor, or just with the DirectionalLight3D color property?

**Comment by MrNull1** [comment]
Yes, I can, and it happens with any color picker.
Also, I need to be on 4.1.1 because of a plugin that hasn't been updated for 4.2.1.

**Comment by AThousandShips** [comment]
Can you please test with 4.1.4?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
