### ISSUE TITLE
Renaming a Variable doesn't Rename other Instances (Language Server)

### ISSUE THREAD

**Issue by mifth** [godotengine/godot#87551]
### Tested versions

Godot version
4.2

VS Code version
1.85.2

Godot Tools VS Code extension version
1.3.1

### System information

Windows 11

### Issue description

I reported this issue to the [VSCode project](https://github.com/godotengine/godot-vscode-plugin/issues/577) but I was said that it's related to Godot.

I have this function:
```
func _check_default_live_text(node_to_check: NodeData, live_node_js):
	if node_to_check.node_class_key in DCGUtils.live_nodes_types and node_to_check.to_node_conns:
		for port_id in node_to_check.to_node_conns.keys():
			var port_type = get_input_port_type(live_node_js, port_id)
		
			if port_type == 1:
				var port_conns = node_to_check.to_node_conns[port_id]

				for conn_ids in port_conns:
					var conn = get_connections_js()[conn_ids]
					var from_node = self.nodes_by_name[conn["from_node"]] as NodeData

					if from_node.node_class_key == DCGUtils.TextNode:
						var from_node_js = get_node_js(from_node) 
						var from_text_slot = get_text_slot_by_port(from_node, from_node_js, conn["from_port"], false)

						var to_text_slot = get_text_slot_by_port(node_to_check, live_node_js, port_id, true)

						if from_text_slot and to_text_slot:
							to_text_slot["LiveText"] = from_text_slot["Text"]

						break

					elif from_node.node_class_key == DCGUtils.RerouteTextNode:
						if from_node.to_node_conns:
							var prev_con_id = from_node.to_node_conns[0][0]
							get_connections_js()[prev_con_id]
```

If I try to rename(F2) a variable "prev_con_id" then only one variable instance will be renamed.

![image](https://github.com/godotengine/godot-vscode-plugin/assets/2251298/397ee6eb-86e3-4590-a53e-e8dfb1d06e66)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/2251298/c213cfcb-231c-48c3-9bc4-a2feb85aa9cd)

![image](https://github.com/godotengine/godot-vscode-plugin/assets/2251298/5adab6f1-831a-406d-8145-d1a1981eb745)

### Steps to reproduce

Try to rename "prev_con_id" variable in VSCode

### Minimal reproduction project (MRP)

Try to rename "prev_con_id" variable in VSCode

**Comment by DaelonSuzuka** [comment]
I can confirm that F2 rename is not renaming the indicated instance of the variable, even though it *does* correctly rename several other variables in the same example.

Something is causing it to miss the second usage of `prev_con_id`.

**Comment by DaelonSuzuka** [comment]
@mifth RE: title change: it's not VSCode related, it's a problem in the Language Server.

**Comment by AlexanderFarkas** [comment]
@DaelonSuzuka Is it fixed? It's not reproducible for me on Godot v4.3.dev (7ebc86641)

**Comment by mifth** [comment]
If you provide a windows dev build I can test it.

**Comment by kus04e4ek** [comment]
> If you provide a windows dev build I can test it.

[Windows build](https://github.com/godotengine/godot/actions/runs/8949670138/artifacts/1472986315), taken from [here](https://github.com/godotengine/godot/actions/runs/8949670138).

This can be accessed from the [main page](https://github.com/godotengine/godot) by clicking here:
![image](https://github.com/godotengine/godot/assets/118438257/7fcbf5a0-5292-4a52-8d1b-2f56f6dc59a0)
Then click `Details` on any of the jobs and click `Summary` on the left.

**Comment by mifth** [comment]
Hi,
@kus04e4ek thank you so much for providing the builds. I've just tested the build and it seems realy the bug was fixed!
Thank you so much all. I'm closing the bug.

**Comment by mifth** [comment]
Just as a prove:
![image](https://github.com/godotengine/godot/assets/2251298/dcd4204e-a4a0-4203-a87b-5c2bba662dfb)

![image](https://github.com/godotengine/godot/assets/2251298/6a14fa82-d736-4a65-8736-ca0f5f2670eb)
