### ISSUE TITLE
Tab container sometimes does not display tabs correctly with expand margin.

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#87565]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Operating System: Kubuntu 22.04 KDE Plasma Version: 5.24.7 KDE Frameworks Version: 5.92.0 Qt Version: 5.15.3 Kernel Version: 6.5.0-14-generic (64-bit) Graphics Platform: X11 Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics Memory: 15.0 GiB of RAM Graphics Processor: RENOIR

### Issue description

Tab container sometimes does not display tabs with expand margin correctly.
![image](https://github.com/godotengine/godot/assets/2453707/bb22e14e-e9f7-40a6-aeb6-a1e0effe626a)

Here is the tab displaying correctly in the theme editor.
![image](https://github.com/godotengine/godot/assets/2453707/1e278e8b-c688-4133-a4eb-0d87209ccb85)

### Steps to reproduce

- Download the project
- Open it
- Run it with the run button not the debug button.
- If the scene doesn't run for some reason debug the scene at...
`res://Editor/Scenes/Forms/ActorEditor.tscn`

### Minimal reproduction project (MRP)

[SMB-GD-Edit.zip](https://github.com/godotengine/godot/files/14047775/SMB-GD-Edit.zip)

**Comment by Sauermann** [comment]
In your screenshots I can't identify the problem you are referring to. Can you please describe your problem in more detail?

For future reference, please don't include the `.godot/` folder in zip-files you share here, because they unnecessarily bloat the file size.

**Comment by Shadowblitz16** [comment]
@Sauermann the tab pixels overlap the panel in the first picture.

**Comment by Cammymoop** [comment]
Tested on master and this is fixed by #88293
