### ISSUE TITLE
Remote Debug - need to change network/debug/remote_port each time using remote debug deploy to Android to get remote print statement/crash point to console

### ISSUE THREAD

**Issue by gisburger** [godotengine/godot#87566]
### Tested versions

v4.2.1-stable_win64

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 6GB Laptop GPU () - 12th Gen Intel(R) Core(TM) i7-12650H (16 Threads)

### Issue description

When deploying to Android, with each deploy I must change the port network/debug/remote_port in order for print statements/crash points to appear in my PC's Godot console/code. The deploy works fine, just no printing through to the console unless its the first deploy or I change port each time. 
Please note I am using the Poing Admob Plugin (latest). 
I'm not sure if its related (but different) to this bug https://github.com/godotengine/godot/issues/58486, where in this scenario its using an old connection that has ended?

### Steps to reproduce

Install JDK / SDK as per command line tool docs: https://docs.godotengine.org/en/4.2/tutorials/export/exporting_for_android.html#install-openjdk-17
[Potentially] install Admob Poing Studios v3.1.0 and follow instructions
Create basic scene with a print statement
Remote deploy to Android device
see print statement in console
Remote deploy again to android device
no print statement in console
Change port #  network/debug/remote_port to 6009+
Remote deploy again to android device
see print statement in console

From reading online (which I can't find now) it sounded like this used to be an issue in Godot but it was since updated to automatically try a new port if comms were lost. I'm wondering if either A) its something to do on my end, or B) potentially a regression. This is my first time reporting a bug so I appologise in advance if I missed something. I have found at least one other person in the Godot Discord server having the same issue. 

### Minimal reproduction project (MRP)

N/A

**Comment by gisburger** [comment]
Found a previous issue, apologies this may be a doubleup https://github.com/godotengine/godot/issues/41650

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/41650.
