### ISSUE TITLE
Project Exported to IOS  error message in Xcode:  AudioOutputUnitStart failed, code: -50

### ISSUE THREAD

**Issue by darwinIcesurfer** [godotengine/godot#87560]
### Tested versions

Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

MacOS 14.2 - Godot v4.2.1.Stable.mono.official - IOS Export to Iphone 14 running IOS 17.2

### Issue description

App starts on iPhone and Godot created screen is displayed.  However the xcode console contains:
**USER ERROR: AudioOutputUnitStart failed, code: -50**

### Steps to reproduce

Steps to reproduce:
* Create a very simple Godot project
* Create a 2d Node with a Label "TEST"
* Export to IOS
*  * fix the import Target platform requires 'ETC2/ASTC' texture compression. Enable 'Import ETC2 ASTC' to fix
*  * Enter Apple Developer ID and bundle Identifier
*  Export Project
* Open `TestVeryBasic.xcodeproj` in Xcode
* Run project on iPhone running 17.2 operatiing system

### Minimal reproduction project (MRP)

VeryBasicApp.zip
[VeryBasicApp.zip](https://github.com/godotengine/godot/files/14046228/VeryBasicApp.zip)

**Comment by curlewrasblo** [comment]
Just got this issue, thought it had something to do with the fmod plugin we're using but I guess not! Hopefully we can get someone's eyes on this soon as its completely stops projects for ios :/

**Comment by WaterBoiledPizza** [comment]
Any update/fixes for this issue?

**Comment by akien-mga** [comment]
CC @bruvzg
