### ISSUE TITLE
Anything within Parallax Node does not respect modulation values

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#87564]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Changing modulation of a parent node is ignored for everything in the Parallax node. Here is a quick video showing it in action using three ColorRects (but same holds true for bitmaps) where I'm changing the color of the root node and only the ColorRect outside of the Parallax is respecting it:

https://github.com/godotengine/godot/assets/106015575/ec6b4759-d85f-4e80-9bf3-4b2c60f76965

### Steps to reproduce

Open the attached MRP.
Change the color (modulation).
Only the ColorRect outside of Parallax will be affected.

### Minimal reproduction project (MRP)

[engage parallax ignores modulation.zip](https://github.com/godotengine/godot/files/14047759/engage.parallax.ignores.modulation.zip)

**Comment by Mickeon** [comment]
This is entirely normal but the confusion is understandable.

**ParallaxBackground** (inheriting **CanvasLayer**) is **not** a **CanvasItem** itself. Only other children CanvasItem are affected by the parent's `modulate` property.
In a nutshell, a ParallaxBackground in the middle of the two like this "breaks" the `modulate` chain.
![image](https://github.com/godotengine/godot/assets/66727710/595fa394-45ed-4248-aabe-18e20b259be9)


You can add this "issue" to the list of ones that would be solved by https://github.com/godotengine/godot/pull/87391 @markdibarry

**Comment by inhalt120g** [comment]
Thank you, in that case it's best to close this.
