### ISSUE TITLE
With TextServer's fallback, type icons in built-in docs' inheritance tree are not attached to their class name

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#87573]
### Tested versions

- Present in v4.3.dev.custom_build [4b6ad3498]
- **NOT** present in 4.2

### System information

Windows 10

### Issue description

It seems like https://github.com/godotengine/godot/pull/65248 was reverted and I don't know if it's intentional or not. Did I do something wrong, perhaps?

In short, the icons used in the inheritance tree of the built-in documentation can sometimes cut off at the end of the line, with the associated class name on the next line:
![image](https://github.com/godotengine/godot/assets/66727710/473049dc-e2ba-4f4d-9136-ff943d662139)

This was addressed in https://github.com/godotengine/godot/pull/65248, but for some reason it came back, and it's not exactly pleasant.
To not have someone waste too much time on this, it seems like nothing about the documentation generation has really changed. **RichTextLabel** seems to ignore the Non-Breaking Space as a... **Non**-breaking space.

### Steps to reproduce

Look at the built-in documentation.

### Minimal reproduction project (MRP)

No need.

**Comment by Mickeon** [comment]
To not have someone waste some time on this, it seems like nothing about the generation has really changed. **RichTextLabel** seems to ignore the Non-Breaking Space as a... **Non**-breaking space.

**Comment by akien-mga** [comment]
> It seems like #65248 was reverted and I don't know if it's intentional or not. Did I do something wrong, perhaps?

I don't see a revert commit, and the code from #65248 is still present. So it's just another change that broke the behavior, not a revert.

Probably related to changes done by @AThousandShips recently.

**Comment by AThousandShips** [comment]
My change doesn't seem to touch any of the visible code there so don't think it's related, could be a regression in how the non breaking space is handled

**Comment by AThousandShips** [comment]
I suspect this might fall under the "complex text layout" caveat for the fallback server, it feels like an advanced feature tbh

**Comment by Mickeon** [comment]
Yyeah, possibly suggesting an enhancement here.

**Comment by bruvzg** [comment]
> So it seems like the TextServerFallback is currently not supporting this kind of character at all. I don't know what to make of it, but it's definitely unusual or a feature that has never existed in the first place.

Oh, this explains it, I'll take a look, non-breaking spaces should not be hard to implement.
