### ISSUE TITLE
RichTextLabel does not listen to an image's `changed` signal to redraw content

### ISSUE THREAD

**Issue by rsubtil** [godotengine/godot#87585]
### Tested versions

- Reproducible in: 4.3.dev (https://github.com/godotengine/godot/commit/4b6ad349886288405890b07d4a8da425eb3c97ec), 4.2.1.stable

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:37:14 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6500 XT (RADV NAVI24) () - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

The `RichTextLabel` node allows embedding images through BBCode, which internally loads any `Texture2D` resource on the project path. This can be used with custom `Texture2D` implementations as well.

However, unlike many other nodes such as `TextureRect`, `Sprite2D`, `Sprite3D` and `Button`, the label does not listen to the resource's `changed` signal. Thus, in a situation where the resource has changed and has emitted such signal, the label will not update and redraw it's content, unless forced to do so (by calling `queue_redraw` manually or something else that forces a redraw, like changing the window size).

https://github.com/godotengine/godot/assets/6501975/da50d07f-ffa0-4c7d-9b83-dd6a6d146a97

This can occur in the scenario where a custom `Texture2D` is created which has logic to swap texture files internally, and thus uses `emit_changed` to ensure a redraw is done:

### Steps to reproduce

- Create a custom resource inheriting ``Texture2D``
```gdscript
extends Texture2D
class_name CustomTexture2D

var tex : Texture2D
static var flip := false

func _init():
	choose_texture()

func choose_texture():
	if flip:
		tex = preload("res://icon.png")
	else:
		tex = preload("res://icon_2.png")
	flip = not flip
	emit_changed()

# 2D nodes
func _draw(to_canvas_item, pos, modulate, transpose):
	tex.draw(to_canvas_item, pos, modulate, transpose)

func _draw_rect(to_canvas_item, rect, tile, modulate, transpose):
	tex.draw_rect(to_canvas_item, rect, tile, modulate, transpose)

...
```
- Create a resource and store it in the project files
![image](https://github.com/godotengine/godot/assets/6501975/7e8d9db8-6462-4b83-af46-2ef2b7ad081f)
- Create a `RichTextLabel` that uses this new resource
![image](https://github.com/godotengine/godot/assets/6501975/c0d01240-5349-4f9d-a2ed-0929911d2244)
- Make the resource swap textures on some other object, like a `Button`:
```gdscript
extends Button

@export var resource : CustomTexture2D

func _on_pressed():
	if resource:
		resource.choose_texture()
```

### Minimal reproduction project (MRP)

[ReproRichTextBug.zip](https://github.com/godotengine/godot/files/14053938/ReproRichTextBug.zip)

**Comment by Calinou** [comment]
cc @bruvzg
