### ISSUE TITLE
Lightmap frustum culling on scaled objects

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#87604]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Lightmap culling doesn't seem to take object scale into account?

https://github.com/godotengine/godot/assets/60579014/9bc35026-243c-4d4e-9080-2146a6ea548f

### Steps to reproduce

Open MRP and scale LevelE_001

### Minimal reproduction project (MRP)

[MRP_Lightmaps.zip](https://github.com/godotengine/godot/files/14060425/MRP_Lightmaps.zip)

**Comment by clayjohn** [comment]
I feel like different iterations of this bug keep popping up randomly.

If I am remembering correctly, we've discussed this before and agreed that the ideal solution is to disable culling for lightmaps. They are registered with the meshes that were baked with them, so if those meshes are visible, the lightmap should be visible.

**Comment by passivestar** [comment]
> if those meshes are visible, the lightmap should be visible.

yeah that sounds reasonable to me

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71585, as this is due to the same cause.
