### ISSUE TITLE
Stop mouse not working for panel

### ISSUE THREAD

**Issue by lehthanis** [godotengine/godot#8760]
**Operating system or device - Godot version:**
2.1.3

**Issue description:**

Created a panel and it defaults to stop mouse being checked. Panel does not stop mouse. Hovering and clicking is still processed below panel. 

**Steps to reproduce:**
Create a panel (mine was over a tilemap) have mouse detection code in _input underneath panel. Check stop mouse on panel. Mouse motion and click is not stopped. 

**Link to minimal example project:**

**Comment by Zylann** [comment]
Try `_unhandled_input` instead http://docs.godotengine.org/en/stable/learning/features/inputs/inputevent.html#how-does-it-work

**Comment by Zylann** [comment]
If this is a bug, why `_unhandled_input` even exists?

**Comment by volzhs** [comment]
I think so too, but I'm just not 100% sure because I didn't do any test about it. :)

**Comment by Zylann** [comment]
Tested it and `_unhandled_input` works as expected.
I think `_input` is a bit misleading, sounds more like `_global_input`.

**Comment by eon-s** [comment]
Tested this script and works fine:

```
extends Panel

func _input_event(event):
	if event.type == InputEvent.MOUSE_MOTION:
		print("input event motion")
```

Maybe you are using Node's `_input ` instead of Control's `_input_event`

**Comment by lehthanis** [comment]
So you're saying if I use stop mouse, anything beneath it needs to use unhandled input, not input?

**Comment by Zylann** [comment]
If you are mixing interfaces with game elements, then it's better for game elements to use `_unhandled_input()`.

**Comment by lehthanis** [comment]
Yup that was it
