### ISSUE TITLE
Debugger shows null value for large strings and arrays

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#87606]
### Tested versions

v4.2.2.rc.custom_build [4061f306e]

### System information

Godot v4.2.2.rc (4061f306e) - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Fri Jan  5 17:38:36 UTC 2024 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) () - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

Stepping through the code with the debugger open, large strings and arrays display `<null>` instead of their actual contents. "Large" seems to be 1,048,568 as the upper limit (that's 0xfffff - 7).
![image](https://github.com/godotengine/godot/assets/53737317/b2a704c1-7c3b-46ba-9244-69f4edfcabb9)
Printing the values (or their length, in my test) does give me the actual value (e.g. 1,322,679), so it's only the debugger that fails to show the proper values.

Quick note: As I was looking for the maximum limit, I also noticed that the `max_buffer_size` variable I was using for this test sometimes showed as `<null>` even though I was *under* the limit.

### Steps to reproduce

I made a small MRP (see below). Passing a text file to the following function is enough to trigger this behavior:
```gdscript
func test(path: String) -> void:
    var file := FileAccess.open(path, FileAccess.READ)
    var error := FileAccess.get_open_error()
    if error != OK:
        return
    print("File length: ", file.get_length())
    var text := file.get_as_text()
    var buffer := file.get_buffer(file.get_length())
    var buffer_to_text := buffer.get_string_from_utf8()
    print("text length: ", text.length())
    print("buffer size: ", buffer.size())
    print("buffer to text: ", buffer_to_text.length)
```

### Minimal reproduction project (MRP)

[debugger_size_limit.zip](https://github.com/godotengine/godot/files/14061364/debugger_size_limit.zip)

I included 2 test files (1 million decimals of pi in test1.txt, and the same file arbitrarily truncated to a length below the issue threshold in test2.txt).
You can place a breakpoint at the end of the `test()` function to check the variables shown in the above screenshot.

**Comment by Zireael07** [comment]
It's a known, already reported problem.

**Comment by jsjtxietian** [comment]
See https://github.com/godotengine/godot/issues/80959
