### ISSUE TITLE
Using C# CanvasLayer Draw...xxx methods unavailable.  (it should have them since it inherits from CanvasItem)

### ISSUE THREAD

**Issue by darwinIcesurfer** [godotengine/godot#87605]
### Tested versions

Reproducible  in v4.2.1.stable.mono.official [b09f793f5]

### System information

MacOS 14.2 - Godot v4.2.1.Stable.mono.official 

### Issue description

Attempting to Create a clock face with tics and labels in a CanvasLayer.  Inside of the _Draw method which is being created, Intelisense does not provide any Draw..xxxx methods.  Compiling fails for the line `this.DrawLine(tickStart, tickEnd, TickColor, 2);`

The code to create a clock face **works on a Node2D** but **does not work on a CanvasLayer**

### Steps to reproduce

Create a scene with

- `Node2d
-    SubViewportContainer
-       SubViewport
-          TestOnCanvas [CanvasLayer node]`

Create a C# script for the TestOnCanvas Node
{try to write code to write on the canvas.  Code works if I write it to a node that inherits from Node2D, not CanvasLayer}

### Minimal reproduction project (MRP)

[GenericInstrument.zip](https://github.com/godotengine/godot/files/14061306/GenericInstrument.zip)

**Comment by bs-mwoerner** [comment]
A `CanvasLayer` [is not a `CanvasItem`](https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html), so it can't be drawn to directly. Just add a `CanvasItem` (or a `Node2D`) child as a container for the clock face and draw from there.
