### ISSUE TITLE
In Rendering  Advanced+, The First Element Of The CanvasLayer Does Not Follow Camera2D in Windows 11

### ISSUE THREAD

**Issue by kinmaster3** [godotengine/godot#87617]
### Tested versions

Tested on: Godot v4.1.3.stable, Godot v4.2.1.stable, Godot v4.3.dev2

### System information

Windows 11 Pro, version 23H2, compilation 22631.3007

### Issue description

In a 2D scene, when creating a CanvasLayer. The first visible element does not come with the camera.
It remains static on the map as if it were inside the 2D scene instead of the Canvas layer.
The expectation would be that all elements within the CanvasLayer would move along with the camera.
I run the project on Windows 10 and Windows 11, but the error only occurs on Windows 11.
The error only occurs in advanced rendering mode.

### Steps to reproduce

Create a 2D scene.
Create a CanvasLayer.
Insert two visible elements in the CanvasLayer, it can be of type ColorRect.
Create a 2D Camera and add some movement to it.
Both elements should move along with the Camera, but the element higher up in the scene tree remains static.

### Minimal reproduction project (MRP)

[teste_bug.zip](https://github.com/godotengine/godot/files/14065284/teste_bug.zip)

**Comment by Sauermann** [comment]
Which graphics card do you have? It is potentially a duplicate of #58314.

**Comment by kinmaster3** [comment]
> Which graphics card do you have? It is potentially a duplicate of #58314.

A minha é Intel UHD 630. É o mesmo problema. Obrigado.
