### ISSUE TITLE
Non-freelook shortcuts can be triggered during freelook

### ISSUE THREAD

**Issue by wgetJane** [godotengine/godot#87639]
### Tested versions

4.3.dev2

### System information

Godot v4.3.dev2 - Debian GNU/Linux 12 (bookworm) 12 - X11 - GLES3 (Compatibility)

### Issue description

The freelook shortcuts (WASD and etc) can still trigger other shortcuts simultaneously during freelook mode in a 3D viewport

This is most likely unwanted behaviour because keyboard shortcuts shouldn't trigger two different things in different contexts at the same time

### Steps to reproduce

1) Go to the 3D workspace
2) Create an AnimationPlayer node
3) Create an animation in its animation editor (just leave it empty)
4) Keep the animation editor open for the following steps
5) Enable multiple viewports through the View menu
6) Hold right-click on a 3D viewport to enter freelook mode
7) Move the freelook camera left or right with the A and D keys
8) Repeatedly perform steps 6-7 on multiple viewports
9) Notice that the A and D keys will also simultaneously cause the animation to be played in the animation editor

### Minimal reproduction project (MRP)

N/A

**Comment by ryevdokimov** [comment]
I can't replicate this:

Godot v4.3.dev2 - Windows 10.0.22631 - Vulkan (Forward+) 

https://github.com/godotengine/godot/assets/105675984/11c01203-674a-4856-880a-0841e892bb10

**Comment by wgetJane** [comment]
it seems like it only happens with multiple viewports and only after you use freelook on the leftmost topmost viewport:

https://github.com/godotengine/godot/assets/52103358/179a7560-786d-43ba-a39e-1a8ad5269a03

**Comment by ryevdokimov** [comment]
Yup, sure enough. Confirmed.

**Comment by wgetJane** [comment]
> Oh, I missed the multiple viewport part. Yup, sure enough. Confirmed.

oh i only edited those in afterwards, i didn't realise the issue was with multiple viewports yet

**Comment by ryevdokimov** [comment]
The PR mentioned above should fix it, if you'd like to test it.
