### ISSUE TITLE
Animation Player not applying cubic keyframes correctly in 4.3dev2

### ISSUE THREAD

**Issue by zolrath** [godotengine/godot#87637]
### Tested versions

Reproducible in 4.3dev2
Not reproducible in 4.3dev1
Not reproducible in 4.2

### System information

Windows 11 - Godot 4.3dev2 - Compatibility

### Issue description

I've got an AnimationPlayer from a 4.2 project animating the rotation of a PanelContainer at the root of my scene.

When opening my 4.2 project in 4.3dev2, the animation no longer works correctly and the first/last frame with 0 degrees rotation are left at odd rotations.
 
## 4.2 and 4.3dev2 Comparison

4.2             |  4.3dev2
:-------------------------:|:-------------------------:
 ![4 2-1](https://github.com/godotengine/godot/assets/454563/00e7f023-7fa8-4efc-8b2c-bcc6af0618c3) | ![4 3-1](https://github.com/godotengine/godot/assets/454563/10950261-3801-49f2-b4d5-365b5b94b105)
![4 2-2](https://github.com/godotengine/godot/assets/454563/a3fd669f-61d3-4b74-8bcf-bf71af235c47) | ![4 3-2](https://github.com/godotengine/godot/assets/454563/aac27ff6-dba7-417e-93fe-9cd41652170c)
![4 2-3](https://github.com/godotengine/godot/assets/454563/6c2abf6f-46ec-45c8-81eb-13e5fabebd39) | ![4 3-3](https://github.com/godotengine/godot/assets/454563/c47dccd6-4bb4-45c2-9499-414afeebf60f)
![4 2-4](https://github.com/godotengine/godot/assets/454563/b883a9f9-0ef7-4a10-88f4-05edb0b61cba) | ![4 3-4](https://github.com/godotengine/godot/assets/454563/959f9730-f28b-4b68-9837-80d8b52e27b4)

## Adding an extra frame to end
If I add an additional 0 degrees frame at the end, both the last and second to last frames properly show 0 degrees.

Extra Frame 1             |  Extra Frame 2
:-------------------------:|:-------------------------:
![4 3-extra1](https://github.com/godotengine/godot/assets/454563/4ace99e6-bb9d-400d-bb7e-4592cc2a686e) | ![4 3-extra2](https://github.com/godotengine/godot/assets/454563/f1aa1ca6-1953-47a9-ac89-d738e15899e6)

### Steps to reproduce

1. Create an Animation Player that rotates a panel container, 0.3 seconds long as shown above.
2. **IMPORTANT**: Use cubic interpolation, linear will not produce the error.
3. The rotation no longer matches the keyframe value.

I've copied over the offending panel into a MRP, along with a scene recreated in 4.3 using linear interpolation that doesn't seem to have the issue.

### Minimal reproduction project (MRP)

[AnimationPlayerBug.zip](https://github.com/godotengine/godot/files/14070208/AnimationPlayerBug.zip)

I've included two scenes.
`made_in_4_2_broken.tscn` has the scene that showed the original issue reduced to its base parts.
`made_in_4_3_seems_fine.tscn` shows the same setup but with linear interpolation.

**Comment by Calinou** [comment]
Did it work in [4.3.dev1](https://godotengine.org/download/archive/4.3-dev1/)?

**Comment by zolrath** [comment]
Seems to be fine in 4.3dev1


![image](https://github.com/godotengine/godot/assets/454563/713fd3b5-9a9c-4e46-97fe-a743734286c3)

**Comment by bs-mwoerner** [comment]
Might be caused by [e538ce38516ae0ed909dadd761352499094b272e]'s changes to cubic interpolation.

Before:
![grafik](https://github.com/godotengine/godot/assets/35597337/13fc927c-d1ff-4acb-814b-c66ecc3ad64f)

After:
![grafik](https://github.com/godotengine/godot/assets/35597337/c8a23e07-3fb3-445e-afbd-48b6390260f7)

**Comment by TokageItLab** [comment]
Sorry, I made a mistake in the argument there. Please test https://github.com/godotengine/godot/pull/87772 if you can.
