### ISSUE TITLE
`_validate_property()` and `_get_property_list()` do not get overridden.

### ISSUE THREAD

**Issue by MaxIsJoe** [godotengine/godot#87636]
### Tested versions

- Reproducible in Godot 4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4633) - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

Attempting to override `_validate_property` and  `_get_property_list()` to add custom inspector functionality seems to be not possible at the moment, as Godot ignores any changes made.

### Steps to reproduce

1- Attempt using one of these scripts:

```gdscript

@tool
extends StaticBody3D

@export var holding_hammer = false:
	set(value):
		holding_hammer = value
		notify_property_list_changed()
		

var hammer_type = 0

func _get_property_list():
	# By default, `hammer_type` is not visible in the editor.
	var property_usage = PROPERTY_USAGE_NO_EDITOR

	if holding_hammer:
		property_usage = PROPERTY_USAGE_DEFAULT

	var properties = []
	print("this should be printed")
	properties.append({
		"name": "hammer_type",
		"type": TYPE_INT,
		"usage": property_usage, # See above assignment.
		"hint": PROPERTY_HINT_ENUM,
		"hint_string": "Wooden,Iron,Golden,Enchanted"
	})

	return properties
```

```gdscript

@tool
extends Node

@export var is_number_editable: bool:
	set(value):
		is_number_editable = value
		notify_property_list_changed()
@export var number: int

func _validate_property(property: Dictionary):
        print("test test test")
	if property.name == "number" and not is_number_editable:
		property.usage |= PROPERTY_USAGE_READ_ONLY
```

2- Attempt changing the values in the inspector
3- Notice how none of the properties get updated, and nothing gets printed to the console.

### Minimal reproduction project (MRP)

[mpr-propertyValidate.zip](https://github.com/godotengine/godot/files/14074293/mpr-propertyValidate.zip)

**Comment by MaxIsJoe** [comment]
I should also mention that both these scripts are from the godot docs, https://docs.godotengine.org/en/stable/classes/class_object.html#class-object-private-method-get-property-list

**Comment by dalexeev** [comment]
* See #81139.

**Comment by Mickeon** [comment]
I have a feeling something else is going on. This works fine on my end. Could you provide a MRP? Perhaps you did not reload the scene you were currently editing?

**Comment by MaxIsJoe** [comment]
> I have a feeling something else is going on. This works fine on my end. Could you provide a MRP? Perhaps you did not reload the scene you were currently editing?

Updated the issue description with a MRP.

**Comment by Mickeon** [comment]
Testing the MRP, it all works completely fine. I am not sure of what could be the cause.
<img src=https://i.gyazo.com/0864fae539b4d2c475ff91f3b1a300bc.gif>

**Comment by MaxIsJoe** [comment]
>  Perhaps you did not reload the scene you were currently editing?

I looked into this again, apparently you need to reload all scenes that contain that @tool script for it to function.

These changes should be applied automatically imo without needing a full project restart or closing/opening scenes, but since it's not a bug and just weird UX; I'm closing this issue.

**Comment by Mickeon** [comment]
It has been like this for a while, and I am not sure if it can be easily fixed. But if it helps you can keep in mind that if the Node has a colored script button it is running in the editor.
