### ISSUE TITLE
Button signal is emitted several frames after input action is registered

### ISSUE THREAD

**Issue by cilerba** [godotengine/godot#87648]
### Tested versions

- Reproducible in: 4.3-dev2, 4.2.1stable, 4.1.2stable and 3.5.3stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

When an input action is pressed with a Button focused, there seems to be a noticeable delay between the moment that input action is registered and a Button emits its `pressed` signal. The delays vary per test usually about 3-5 frames. Expected behavior would be for there to be no delay at all. This was tested with print calls printing frame count via `get_tree().get_frame()`.

### Steps to reproduce

- Create a new Control scene
- Add a Button child Node
- Connect function to Button's pressed signal
- Call function on input action pressed (tested with `_process` and `_input`)
- Notice input's function gets called before Button's signal connection

### Minimal reproduction project (MRP)

[4.x_button_signal_test.zip](https://github.com/godotengine/godot/files/14073186/4.x_button_signal_test.zip)

**Comment by Mickeon** [comment]
This is not a bug. This behavior is dependant by the `action_mode` property. By default, the signal is emitted when the button is _released_.
![image](https://github.com/godotengine/godot/assets/66727710/8ccb83f8-ab2e-4b7c-8eac-03113b68a8c4)

**Comment by cilerba** [comment]
Oh! I spent so long trying to figure this out haha. Works as intended now, my apologies. Thanks for the quick and helpful response.
