### ISSUE TITLE
Importing a Mesh with Armature from Blender doesn't properly parent Empty objects

### ISSUE THREAD

**Issue by CrayolaEater** [godotengine/godot#87645]
### Tested versions

4.2.1 stable

### System information

Windows 11 pro - Vulkan (Forward +) - GPU AMD RX 7900 XTX

### Issue description

I have multiple meshes in blender for a specific limb on a character and I grouped them together using empty objects as seen below:
![image](https://github.com/godotengine/godot/assets/38570835/3d236347-d253-4fdb-9f80-ac894dad7ec7)
This makes it easier to find and clasify every mesh type.
However when importing into godot here is the result:
![image](https://github.com/godotengine/godot/assets/38570835/f5203ae3-6418-432a-8007-062cdedac828)
As you can see the empty objects are not parented inside the Armature node, also the Meshes are not children of it.

### Steps to reproduce

- create a mesh with armature in blender
- parent an empty object to the Armature
- parent the mesh to the empty object (keep transform)
- export to .glb
- import the .glb inside godot

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
Can you please provide a project, that demonstrates this issue. This will help people, who investigate this problem, to replicate your problem, which makes it easier to resolve the issue.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
