### ISSUE TITLE
Collision2D detection fails (most of the time) when CharacterBody2D Player is spawned on the scene.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#87649]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

I have a static platform with two StaticBody2D colliders on either end. When I spawn a Player scene(CharacterBody2D/Collider2D) and move_and_slide() towards either one using ui_left/ui_right, most times it will stop about the width of the Player before hitting the collider.

However if the same Player scene is visible, the move_and_slide() along the platform works perfect.

See the code below. I have attached the minimal project. 

### Steps to reproduce

**Test 1. Player Spawns (instantiated)**
1. Run the attached project.
2. Player spawns on platform. 
3. Use arrow keys to slide left or right.
4. You will notice that the Player does not collide on one or the other static colliders.
5. (Many times it may look like it works. Press ESC to quit and run it again.)

**Test 2 Make Player visible. (Not instantiated)**

1. Make Player visible, and and run attached project
2. Use arrow keys to slide left or right.
3. You will notice that the Player collides properly.

world.gd
```gdscript
extends Node2D
class_name World
@onready var Player:PackedScene = preload("res://player/player.tscn")
var player_anim: CharacterBody2D

func _ready():
	if !$Player.visible:
		player_anim = Player.instantiate()
		add_character_to_world(player_anim, $SpawnAt.position)
			
func add_character_to_world(actor: CharacterBody2D, position: Vector2):
	actor.position = position
	add_child(actor)
	pass
	
func _physics_process(delta):
	if Input.is_key_pressed(KEY_ESCAPE):
		get_tree().quit()

```
player.gd
```gdscript
extends CharacterBody2D

@export var speed = 600
@export var gravity = 30

# Called when the node enters the scene tree for the first time.
func _ready():
	velocity.y=0
	move_and_slide()
	
func _physics_process(delta):

	if  !is_on_floor():   
		velocity.y += gravity
		move_and_slide()
		return
			
	var input_movement = Input.get_vector("ui_left","ui_right","ui_up","ui_down")
	if input_movement != Vector2.ZERO:	
		velocity = input_movement * speed
		
	if Input.is_action_pressed("ui_left"):
		move_and_slide()
		
	#elif horizontal_direction < 0:
	if Input.is_action_pressed("ui_right"):

		move_and_slide()
		
	pass
```
**Additional Note**
Same issue happens if you replace move_and_slide() with move_and_collide(velocity)

**Screen shots**
![Screenshot_20240127_121002](https://github.com/godotengine/godot/assets/930478/75849519-6706-47c3-8395-96707c0ea859)
![Screenshot_20240127_121553](https://github.com/godotengine/godot/assets/930478/54028e8a-7d16-4a7c-a576-32b8c4da82cc)
![Screenshot_20240127_121143](https://github.com/godotengine/godot/assets/930478/a3f69692-ad75-4a5c-96e7-7f7213aa0d2d)

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/14073199/Archive.zip)

**Comment by bs-mwoerner** [comment]
Since there are two characters in your scene (the invisible one from the scene file and the visible one created in the script), how far the visible one can move depends on where the invisible one ends up. If it's to the right of the visible character, for instance, then you can't get closer to the right obstacle than the width of the invisible character. You can make the initial character visible and transparent to better see what's going on:

![grafik](https://github.com/godotengine/godot/assets/35597337/a860cc16-fe95-4052-a926-2d14a1a6f31f)

**Comment by wyattbiker** [comment]
Resolved. User error.
