### ISSUE TITLE
Why are the four diagonal directions in 8-way control so significantly offset?

### ISSUE THREAD

**Issue by geekros** [godotengine/godot#87646]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Window 11 v4.2.1.stable.official [b09f793f5]

### Issue description

I implemented an 8-directional movement of a character controlled by the mouse using the program below. The up, down, left, and right movements work very well, but when moving in diagonal directions, the offset is very large. I can't think of any solution to this problem. Could you please take a look and help?

```
func _physics_process(_delta):
	var player_position = position
	var mouse_position = get_local_mouse_position()
	# (0,1,2,3,4,5,6,7)
	var player_angle = wrapi(int(snapped(mouse_position.angle(), PI/4) / (PI/4)), 0, 8)
	var direction = Vector2(cos(player_angle * PI/4), sin(player_angle * PI/4))
	if player_action_speed > 0 and mouse_position.length() > 15:
		velocity = direction.normalized() * 100
		move_and_slide()
```

To demonstrate this issue, I have recorded a video.

https://cdn.geekros.com/example.mp4

![](https://cdn.geekros.com/20240127230504.png)

**I really need your help and guidance.**

### Steps to reproduce

My project source code is here: https://github.com/aithority/engine

### Minimal reproduction project (MRP)

My project source code is here: https://github.com/aithority/engine

**Comment by kleonc** [comment]
> I implemented an 8-directional movement of a character controlled by the mouse using the program below. The up, down, left, and right movements work very well, but when moving in diagonal directions, the offset is very large. I can't think of any solution to this problem. Could you please take a look and help?
> 
> ```
> func _physics_process(_delta):
> 	var player_position = position
> 	var mouse_position = get_local_mouse_position()
> 	# (0,1,2,3,4,5,6,7)
> 	var player_angle = wrapi(int(snapped(mouse_position.angle(), PI/4) / (PI/4)), 0, 8)
> 	var direction = Vector2(cos(player_angle * PI/4), sin(player_angle * PI/4))
> 	if player_action_speed > 0 and mouse_position.length() > 15:
> 		velocity = direction.normalized() * 100
> 		move_and_slide()
> ```

No sign of an in engine bug here - the behavior looks according to the code snippet above. Meaning that's a user logic error, nothing to be fixed within the engine. Basically the same issue as in #87224.

> I really need your help and guidance.

This is not a help-forum, please don't open issues when needing help with your own project. It's not the first time it's happening (#87224 - not the same GitHub account of the OP but the same project link).

For getting help with your project please use other [community channels](https://godotengine.org/community/) (Godot forum, Discord, Reddit, etc.). This is a bugtracker, not a help desk.

**Comment by Calinou** [comment]
Forum thread opened: https://forum.godotengine.org/t/why-are-the-four-diagonal-directions-in-8-way-control-so-significantly-offset/44772
