### ISSUE TITLE
spacing_top/spacing_bottom in fallback FontVariation does not change baseline

### ISSUE THREAD

**Issue by gu-fan** [godotengine/godot#87655]
### Tested versions

4.2.1.stable

### System information

Linux

### Issue description

When a FontVariation has a FontVariation in it as a fallback font

changing `spacing_glyph` in subresource seems does working after test as #80907 descripted.

But changing `spacing_top` or `spacing_bottom` in subresource does not working.

which I thought changing spacing_bottom/spacing_top will change the position of fallback font, so I can align the fallback font  with main font by baseline.

![Screenshot from 2024-01-28 05-07-33](https://github.com/godotengine/godot/assets/579129/50f878cf-845c-4795-87db-e1f15b4c36a5)

I don't know if this is a bug, or just as it is.
and a new align baseline for fallback font feature need to be implemented.

### Steps to reproduce

   1. Create a Label.
   2.  Create and set a FontVariation as the font of the label node.
   3.  Create and set another FontVariation as a fallback font of the font of the label node.
   4. changing fallback font's spacing_top and spacing_bottom takes no effect. but spacing_glyph works. 

### Minimal reproduction project (MRP)

[bug_font_fallback.zip](https://github.com/godotengine/godot/files/14073835/bug_font_fallback.zip)

**Comment by bruvzg** [comment]
It's not a bug, `top` and  `bottom` spacing should not affect baseline in any way, it's added to ascent/descent, and intended for line spacing control, baseline always remain the same. But I guess baseline offset can be added as an extra property.

**Comment by gu-fan** [comment]
yes, baseline offset looks good
