### ISSUE TITLE
On Godot v4.x.x, the Image generated using "image.createfromdata" is incomplete

### ISSUE THREAD

**Issue by Tang-1993** [godotengine/godot#87667]
### Tested versions

4.3

### System information

apple m1 14.1.1

### Issue description

On Godot v4.x.x, the Image generated by C# using "image.createfromdata" is incomplete
![4 3](https://github.com/godotengine/godot/assets/13973704/ec9e2af1-fa25-4e45-9105-820dd37d448c)

In Godoot v3.5, there is no problem with use
![3 5 3](https://github.com/godotengine/godot/assets/13973704/b8b6ebbe-4859-4838-aeee-63babe941eb6)

![WX20240128-173619@2x](https://github.com/godotengine/godot/assets/13973704/fdaef649-a461-4f6a-af6b-abcb0b191fea)

### Steps to reproduce

![代码](https://github.com/godotengine/godot/assets/13973704/69aea031-2330-427b-b179-48c74239a557)

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
Please upload a minimal reproduction project. That would help people to investigate the problem you are experiencing.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
