### ISSUE TITLE
EditorNode3DGizmo._redraw not called when more than 2 nodes are selected.

### ISSUE THREAD

**Issue by bbasics** [godotengine/godot#87666]
### Tested versions

4.2.1

### System information

Ubuntu 22.04, Vulkan forward+

### Issue description

The `EditorNode3DGizmo._redraw` method is not called whenever there is three or more nodes selected.

### Steps to reproduce

- If I select one node in the editor, it print a list of one node
- If I select two node, it prints a list of two node
- If I select three or more node, it does not print anything (Method not called?)

### Minimal reproduction project (MRP)

Frankly I have no time right now to build such a project, sorry, here is my script though

```
extends EditorNode3DGizmo

func _redraw():
    print(EditorInterface.get_selection().get_selected_nodes())
```

- If I select one node in the editor, it print a list of one node
- If I select two node, it prints a list of two node
- If I select three or more node, it does not print anything (Method not called?)

**Comment by Mickeon** [comment]
The Gizmo's `_redraw` method is called whenever the editor needs it to be redrawn. It is not guaranteed to be called every time new nodes are selected. That may just be a side-effect of it

**Comment by AThousandShips** [comment]
Closing as per the above, if you can find some specific behaviour that makes things unusable, rather than unexpected workflows, please open a new issue
