### ISSUE TITLE
Godot crashes when accessing static variables in @tool mode

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#87678]
### Tested versions

Reproducible in 
- 4.2.2 RC1
- 4.2.1 Stable

### System information

Windows 11

### Issue description

When you try to access static variables in `@tool` mode. The Godot editor crashes without any logs or messages

### Steps to reproduce

Create two files as given below:

```gdscript
# Scene file
@tool
extends Node2D
@export var setup: bool = false:
	set(value):
		setup = value
		print(Fluid.KIND[12]) # Cause of crash as KIND is null


# Fluid File (Note: No @tool annotation)
class_name Fluid

static var KIND := {12: "River" }
```

When you toggle the setup Godot will crash as it will try to print static variable. 
It should print error message like `Invalid get index '12' (on base: 'Nil').` rather than crashing

If you add `@tool` annotation it does not crash and gives the right values

### Minimal reproduction project (MRP)

If required will be provided

**Comment by IceflowRE** [comment]
Related #81250

**Comment by LeoDog896** [comment]
[A reply on that related issue was mentioned by @dalexeev](https://github.com/godotengine/godot/issues/81250#issuecomment-1703846164):

> If you add `@tool` to the preloaded script it will work. We have some inconsistency here: in some cases `@tool` is optional to run dependency code, in other cases it is required (usually `Node`s, but in some other cases too, [example](https://github.com/godotengine/godot/pull/78219#discussion_r1302070084)). I'm not sure if this is a bug as it prevents non-`@tool` code from being auto-executed.

While crashing is still (absolutely) a bug, should `GDScript` instead throw an error about not being able to depend on static variables from other non-tool scripts in a tool script?
