### ISSUE TITLE
Can't add elements to PackedStringArray properties in inspector

### ISSUE THREAD

**Issue by jefvel** [godotengine/godot#87671]
### Tested versions

- Reproducible 4.2.1

### System information

windows 11 - godot 4.2.1

### Issue description

It's not possible to add values to `PackedStringArray` properties in the inspector, since the input seems to have disappeared

### Steps to reproduce

Create a node, for example a `CodeEdit`, open the code completion section, try to add a prefix.

![image](https://github.com/godotengine/godot/assets/494817/90660508-3a98-456c-9c11-f918c9d1478a)

It doesn't seem possible to do. Clicking "Add element" will show the error `Code completion prefix cannot be empty.`.

### Minimal reproduction project (MRP)

[packedstringarray.zip](https://github.com/godotengine/godot/files/14075892/packedstringarray.zip)

**Comment by KoBeWi** [comment]
It's specific only to `prefixes` property of CodeEdit.

**Comment by nongvantinh** [comment]
It seems like this commit introduces the issue: 35264d5782de5feb72b4d3bd5e38fc175458d499.

Initially, when adding new `Prefixes`, we don't have any values for these `new prefixes` yet, so the error `Code completion prefix cannot be empty.`  incorrectly fires up.

**Comment by AThousandShips** [comment]
It also affects delimiters in the same class, it's specific to how it handles the empty/invalid cases, making it impossible to add

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/77358

**Comment by nongvantinh** [comment]
@AThousandShips I wonder how you can locate a bug report from months ago so quickly. Do you memorize them, or is there a tool to help you manage these bug reports?

**Comment by KoBeWi** [comment]
If you know what's wrong, finding another report is not difficult, assuming it was written properly.
Try searching "CodeEdit prefixes".

**Comment by AThousandShips** [comment]
I read it before in this case, but searched for it in this case, found it with just "CodeEdit", but I also have learned a lot of search skills across the years (the old Google days lol)
