### ISSUE TITLE
Use SoftBody3D lead to crash without any log

### ISSUE THREAD

**Issue by Caynet1997** [godotengine/godot#87683]
### Tested versions

v4.3.dev2.official [352434668]

### System information

Godot v4.3.dev2 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i7-12700 (20 Threads)

### Issue description

I want to use SoftBody3D and it just happened. No any code.

### Steps to reproduce

Add a SoftBody3D Node to your Scene and it will crash.

### Minimal reproduction project (MRP)

[softbodytest.zip](https://github.com/godotengine/godot/files/14077389/softbodytest.zip)

**Comment by Mickeon** [comment]
The MRP project contains a single `.tscn` file and is thus not a valid project, could you include a Godot project next time?

I have tested the scene in the latest dev build and I cannot reproduce the crash, myself.

**Comment by Caynet1997** [comment]
> 贡献
I tried again, but it still 
[SoftBodyTest.zip](https://github.com/godotengine/godot/files/14086159/SoftBodyTest.zip)

**Comment by Caynet1997** [comment]
> The MRP project contains a single `.tscn` file and is thus not a valid project, could you include a Godot project next time?
> 
> I have tested the scene in the latest dev build and I cannot reproduce the crash, myself.

[SoftBodyTest.zip](https://github.com/godotengine/godot/files/14086202/SoftBodyTest.zip)

**Comment by Mickeon** [comment]
Then this is a duplicate of https://github.com/godotengine/godot/issues/86790 . Thank you for submitting the issue, nonetheless.
