### ISSUE TITLE
Adding own <DefineConstant> in .csproj file causes nodes and resources to set values to null/default

### ISSUE THREAD

**Issue by SecondDegreePerm** [godotengine/godot#87681]
### Tested versions

Tested and reproducable in:
- Godot_v4.1.3-stable_mono_win64 
- Godot_v4.2.1-stable_mono_win64

Not tested in any other versions

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2070 with Max-Q Design (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

Setting your own defines in the .csproj folder and using them to disable code conditionally will cause the editor to set every value of scenes and resources to null/default in memory. It will also prevent you from editing these values to anything else. 

Interestingly, launching a build of the game directly from rider prevents this from happening. 

### Steps to reproduce

How to use the minimal reproduction project:
1.Edit the .csproj file and remove the commented out section seen below:
![image](https://github.com/godotengine/godot/assets/32390438/b553c32f-5058-4ac9-964e-4d93c9c772b5)
2. Save the change
3. Build the project with the godot editor
4. Close the Godot editor
5. Open the godot editor
6. That you can no longer edit the value of the string "Test" in the scene TestScene
7. Even if you edit the value of the scene in a test editor and save it, if you press play the value will still be null/empty

### Minimal reproduction project (MRP)

[CSProjTest.zip](https://github.com/godotengine/godot/files/14076977/CSProjTest.zip)

**Comment by KarmyDev** [comment]
Hello! Your Issue appears to be similiar to mine (#85441), which I managed to fix [here](https://github.com/godotengine/godot/issues/85441#issuecomment-1828355611). 
You have to add `$(DefineConstants);` inside `<DefineConstants>` property before your constant that you want to set.

In your example it'd be `<DefineConstans>$(DefineConstants);TEST_EXAMPLE</DefineConstants>`.

**Comment by SecondDegreePerm** [comment]
Looks like it's almost identical, down to using a test string with a value of 'hello'! That fixed it for me, thanks for the help!
