### ISSUE TITLE
Weird camera bug

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#87704]
### Tested versions

4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.4633) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

In the 2d viewport when i drag a node that has a camera viewport camera changes to that nodes camera.

https://github.com/godotengine/godot/assets/78092286/f4c67ace-59a5-4409-a803-6e2df1f5a520

### Steps to reproduce

-Open Godot and create a project
-Create 2 nodes and one of them should have camera 2d node
-Drag node that has camera 2d to other node

### Minimal reproduction project (MRP)

N/A

**Comment by kleonc** [comment]
Reproducible since v4.2.dev4.official [549fcce5f].
Regression from #79867, cc @WhalesState.

**Comment by WhalesState** [comment]
> Reproducible since v4.2.dev4.official [[549fcce](https://github.com/godotengine/godot/commit/549fcce5f8f7beace3e5c90e9bbe4335d4fd1476)]. Regression from #79867, cc @WhalesState.

Tracking the issue, mainly caused by `is_editing_in_editor()` returns false because it's not part of edited scene `is_part_of_edited_scene()`
