### ISSUE TITLE
Power/Battery management

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#8770]
This issue keeps track of current implementation of battery/power management in Godot. 
For reference, #314 

The code is ready to welcome implementations for all missing platforms (classes and methods ready but return a warning - not implemented on this platform)

Platforms:
- [ ] Android : needs testing
The code is directly adaptated from SDL to using Godot API. It probably diserves more attention.
- [ ] Haiku : not developed
- [ ] Iphone : not developed
- [ ] Javascript : not developed
Waiting for more information & specs
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API
https://w3c.github.io/battery/

- [ ] OSX : needs testing
- [ ] Server : partially tested, but shows obvious code flaws
- [ ] UWP : not developed
This could be of use https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/get-battery-info
- [ ] Windows : needs testing
- [ ] X11 : partially tested, but shows obvious code flaws

edit: adding a test project that may be used on every platform.
[godot-power-test.zip](https://github.com/godotengine/godot/files/1178139/godot-power-test.zip)

**Comment by Marqin** [comment]
I'd not call X11 `OK tested` if code contains explicit NULL pointer dereference. Seems you didn't tested it fully or ignored crashes.

see https://github.com/godotengine/godot/blob/master/platform/x11/power_x11.cpp#L178

**Comment by StraToN** [comment]
@Marqin Indeed, there's a big miss here. It's pretty old now, when I atempted to translate SDL code to Godot. I may have started this part and never finished it. But as you pointed it out, testing was obviously insufficient because I was lucky during my tests.

**Comment by StraToN** [comment]
Some fixes were brought by 411f09a512d5847fc9c6270439308d1e3093f211, my tests on X11 pass. I tried to take care of NULL pointer dereferences but I may have missed some. Also it is complicated to test all features as my laptop doesn't support a 'number of seconds remaining on battery' computation, thus it returns -1. However, un/plugging power cable does change the battery status and %. 

I am currently unable to test this on Android though, as the scene being ran in the export is all grey, I can't explain why.

Other platforms need attention too.

**Comment by Marqin** [comment]
I found it via Static Analyzer :D (I made our Scons generate clang's buils commands .json file and then run clang-tidy on that)

**Comment by williamd1k0** [comment]
I tried it on Manjaro and worked fine but it isn't working on Android.

I'm using master (9eb4d4a) and I added the `android.permission.BATTERY_STATS` on export.

**Comment by alex-evelyn** [comment]
Can confirm, battery level detection does not work on Android.

**Apparently my Screenshot Feature Is Low Quality When Used on My Game (and my game doesn't have permission to save the viewport screenshot to the sdcard).**
![photo5053350408013064292](https://user-images.githubusercontent.com/6305346/68367070-caab2e80-0102-11ea-9883-ec9f011b0e59.jpg)

Basically it says,
```
Battery: -1%
Seconds Left: -1
Battery State: Unknown
```

The battery and seconds left are raw values from Godot (`OS.get_power_percent_left()` and `OS.get_power_seconds_left()` respectively). The unknown is set from `OS.POWERSTATE_UNKNOWN`

**Comment by alex-evelyn** [comment]
OSX on Mojave works fine. My only complaint is the seconds left is not updated in real time and I cannot attest to the accuracy of seconds left. The percentage and battery state is correct.

**Comment by Calinou** [comment]
> Edit: I did not know there was a permission called android.permission.BATTERY_STATS. I'll have to retest it once I figure out how to add permissions for Android to my game.

Would it be possible to print an error message if trying to access battery status without the permission?

**Comment by williamd1k0** [comment]
@alex-evelyn 
> https://github.com/godotengine/godot/issues/27143#issuecomment-473599216
> Power management on Android was disabled by @reduz in b5a06ce, and nobody tried to reenable it since then.

**Comment by GeorgeS2019** [comment]
Can someone either close this OR assign this to milestone 4.0 just like [this](https://github.com/godotengine/godot/issues/20271) and [this](https://github.com/godotengine/godot/issues/19320)?

**Comment by akien-mga** [comment]
Since this was never finished (despite @StraToN's best intentions :)) and is current either not implemented or not thorough tested on all platforms, I suggest to drop this API in 4.0.

We can then consider reimplementing it either for 4.0 or for a later release, taking the time to ensure that most platforms have good support before merging.

**Comment by jamie-pate** [comment]
OS.get_power_state() This was useful on platforms where it worked :sob:
