### ISSUE TITLE
Negative values in match case don't work

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#87717]
### Tested versions

3.5.3

### System information

Windows 10

### Issue description

Using match case, this doesn't work:

```
var axis_dir = current_key.get_axis_value()
match axis_dir:
    -1:
        text += "Left"
    1:
        text += "Right"
```

Whereas this works:

```
var axis_dir = current_key.get_axis_value()
if axis_dir == -1:
    text += "Left"
elif axis_dir == 1:
    text += "Right"
```

### Steps to reproduce

Try using a negative value in match case.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
What type is `axis_dir`? Keep in mind `match` performs strict type matching, so floats won't match.

**Comment by elvisish** [comment]
> What type is `axis_dir`? Keep in mind `match` performs strict type matching unlike `if`, so floats won't match: #42224

Thanks, `axis_dir` is from `get_axis_value()` which returns a float, but forcing it to an int with `var axis_dir :int = current_key.get_axis_value()` makes it work. Is that intentional?

**Comment by Calinou** [comment]
Closing, as this is already being tracked in https://github.com/godotengine/godot/issues/42224.
