### ISSUE TITLE
Crash handler on macOS isn't triggered, even in official editor builds

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#87718]
### Tested versions

- Reproducible in: 3.5.3.stable, 4.1.3.stable, 4.2.1.stable, 4.3.dev 9ab5cedef6de32826b9184e960b3880df3888a5a

### System information

Godot v4.2.1.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

The crash handler on macOS isn't triggered, even in official editor builds. This also occurs with self-compiled builds not put in an `.app` bundle.

In comparison, the crash handler works on Linux and Windows (when compiled in MSVC and in debug builds only).

### Steps to reproduce

Run the editor from a terminal. Create a project with the following script attached on the root node, then run it:

```gdscript
func _ready():
    OS.crash("message")
```

Instead of seeing a crash backtrace (even if mangled due to a lack of debug symbols), you'll only see the following:

![image](https://github.com/godotengine/godot/assets/180032/4ba056e8-5245-4332-8084-82709c7328a8)

### Minimal reproduction project (MRP)

[test_crash_handler.zip](https://github.com/godotengine/godot/files/14090186/test_crash_handler.zip)

**Comment by bruvzg** [comment]
On macOS, `OS.crash` is emitting SIGTRAP, which is not handled by the crash handler. Not sure if it's an oversight or there are reasons for it.
