### ISSUE TITLE
Inconsistent File.file_exists(path) values through Desktop/Android

### ISSUE THREAD

**Issue by arypbatista** [godotengine/godot#8773]
**Operating system or device - Godot version:**
Android

**Issue description:**
On Android, File.file_exists(path) returns false for a scene resource. On Desktop I got that it exists.  ResourceLoader is able to load the path on both plataforms. ResourceLoader.has(path) returns True on both platforms.

I think File.file_exists(path) is not able to access `res://` path on Android, and that's why it always return false.

On the other hand, ResourceLoader.has(path) is inconsistent through desktop/android. As for Android, it seems to have the files on it's cache no matter if the file is loaded into memory or not.

**Steps to reproduce:**

Run `File.file_exists` over a path with `res://` prefix that you already know it exists and print in console. Deploy to Android and see logs. You will see print results tells you that file does not exist.
```
print('Path exists: ', File.new().file_exists(path))
```

**Comment by akien-mga** [comment]
I think it's the same issue as #1562. `File.file_exists` doesn't seem to translate the given paths to their converted equivalent when exported (e.g: `res://scene.tscn` -> `res://scene.converted.scn`).

**Comment by arypbatista** [comment]
@akien-mga Oh, let me test that!

I have seen that ResourceLoader.has(path) is inconsistent through desktop/android too. As for Android, it seems to have the files on it's cache no matter if the file is loaded into memory or not.

Should I open a separate issue?

**Comment by arypbatista** [comment]
Just for the record,

`File.new().file_exists(path)` doesn't work either when using `.scn` extension over a resource I know for sure it exist.

@akien-mga Do you know what's the `res://` directory on Android? Because on `data/data/org.godotengine.<app>` I only see the user data files. I imagine it's bound to apk.

**Comment by akien-mga** [comment]
But even you `.scn` resource will be converted. Try `File.file_exists()` on a `.txt` resource, it should work.

**Comment by arypbatista** [comment]
Ok. I will code a workaround using a combination of `ResourceLoader.has(path)` and `File.file_exists(path)`, but I think maybe it has sense for the programmer to ignore the fact that resources are converted and to still be able to access them as if they were the very same files.

**Comment by eon-s** [comment]
@arypbatista  If you save it as scn or don't convert the tscn, `File` finds it?

**Comment by arypbatista** [comment]
@eon-s Yes. If I save it as .scn then I have the inverse behavior on Android: `File.file_exists(path.scn)` returns `True` and `ResourceLoader.has(path)` returns `false`.

**Comment by arypbatista** [comment]
So, if using .scn, both `File.file_exists(<path.scn>)` and `ResourceLoader.has(<path.scn>)` are consistent through desktop/android platforms.

**Comment by volzhs** [comment]
@akien-mga 
hm. there are some people did it in same way so far.
what about getting remapped path on `file_exists`?

**Comment by akien-mga** [comment]
> what about getting remapped path on `file_exists`?

I think it should be the case, yes. From the point of view of the game programmer, the fact that some files get converted on export should be fully transparent.

**Comment by eon-s** [comment]
The remapping needs to check if the export does not convert scenes.

**Comment by volzhs** [comment]
2.x has `PathRemap::get_remap(path)` to get remapped path if it's remapped.
but it's gone with 3.0. is it moved somewhere?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
I wrote #18740 to better summarize the issue, so closing this one in favour of the new one.
