### ISSUE TITLE
Camera in frostum mode projects background incorrectly

### ISSUE THREAD

**Issue by Norodix** [godotengine/godot#87736]
### Tested versions

I don't think its specific to a version. I tested with:
v4.2.1.stable.official [b09f793f5]
v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Pop!_OS 22.04 LTS - Vulkan (Mobile) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - AMD Ryzen 5 5600G with Radeon Graphics (12 Threads)

### Issue description

The camera's frostum projection mode doesn't seem to correctly project the background.
As far as I know, environment projection is a separate process from all other projections and I suspect the necessary steps are not applied for the frostum mode.

I have a simple setup with a camera looking at a cube with frostum projection. The camera is somewhat below the cube.
With this simple setup:
![image](https://github.com/godotengine/godot/assets/36245389/660c0bfd-46fa-4bd6-87e2-a0a0082fa831)

I expect to see something like this (with a bit of distortion due to the frostum projection).
![image](https://github.com/godotengine/godot/assets/36245389/785ca6fa-627f-44ca-b652-836f8920ae4f)

But in preview and in-game I see this:
![image](https://github.com/godotengine/godot/assets/36245389/f5a153f1-a3ed-45ea-928a-366e3b5865e7)

The cube itself looks as expected, but the background does not. The camera is looking at the cube from below, yet the cube appears to be below the horizon because of the incorrect projection. When I add a large colored plane behind the cube everything appears normal.
![image](https://github.com/godotengine/godot/assets/36245389/21e4bd13-171f-4a4d-8d69-6a54e347b34d)
![image](https://github.com/godotengine/godot/assets/36245389/72c82ad7-5193-4d83-b322-1c534df68d65)
This is primarily the reason I suspect the background projection is the issue.

### Steps to reproduce

Add a camera with frostum projection and some objects to the scene. Move the camera slightly lower than the objects.
Make sure the frostum projection has some vertical offset and the camera can see the objects.
Observer the camera's preview or in-game image and see the incorrect offset relative to the background.

### Minimal reproduction project (MRP)

[Godot_Frostum_test.zip](https://github.com/godotengine/godot/files/14096406/Godot_Frostum_test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/63863.

**Comment by Norodix** [comment]
Oh yeah that is right. Sorry, I didnt find that its a duplicate because I misspelled frustum. My bad.
