### ISSUE TITLE
[3.0] Mesa - translation from TGSI failed

### ISSUE THREAD

**Issue by Elinvention** [godotengine/godot#8774]
**Operating system or device - Godot version:**
Debian testing - Godot 3.0 - Mesa 17.1 - AMD Radeon HD 6670
[glxinfo.txt](https://github.com/godotengine/godot/files/1001722/glxinfo.txt)

**Issue description:**
Everything 3D is rendered grey and the terminal shows a lot of this errors:
```
EE ../../../../../src/gallium/drivers/r600/r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE ../../../../../src/gallium/drivers/r600/r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=1) -1
```

**Steps to reproduce:**
Open any 3d scene, even the testcube is enough.

**Comment by bojidar-bg** [comment]
Duplicate of #8700?

**Comment by Elinvention** [comment]
Probably yes. @Gibbz please open godot in a terminal and verify.

**Comment by Gibbz** [comment]
yup same issue!

https://pastebin.com/78rCQhQJ

**Comment by Gibbz** [comment]
Found a post on mesa driver bug tracker:
https://bugs.freedesktop.org/show_bug.cgi?id=99349

**Comment by bojidar-bg** [comment]
Ok, closing as duplicate of #8700. You are invited to copy the discussions there :wink:
