### ISSUE TITLE
display/window/size/initial_position_type is ignored, project always starts on the screen not containing the editor

### ISSUE THREAD

**Issue by knochenhans** [godotengine/godot#87742]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Arch Linux, X-Org Server 21.1.11, XFCE 4.18.1

### Issue description

The actual value of display/window/size/initial_position_type is ignored, projects always start on the screen not containing the editor.

### Steps to reproduce

Set up a fresh project, set display/window/size/initial_position_type to "Center of Primary Screen" (or any other value, for that matter), make sure the editor is on the first screen.

Result: The project starts on the second screen.

Move the editor to the second screen, start the project.

Result: The project now starts on the first screen.

### Minimal reproduction project (MRP)

[ScreenTest.zip](https://github.com/godotengine/godot/files/14100084/ScreenTest.zip)

**Comment by KoBeWi** [comment]
This is a project setting. Running in the editor will use `run/window_placement/screen` *editor* setting.

**Comment by knochenhans** [comment]
Mea culpa, turns out I had set this editor setting to “Next Screen” at some point in the past and completely forgot about that layer of editor settings for window placement. Problem solved, thanks for pointing it out!
