### ISSUE TITLE
Exporting normal maps is broken in 4.3-dev but works in 4.2-stable

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#87770]
### Tested versions

Happens in the latest master 4.3-dev 313f623b9d102cc8c411ae7cab9518f98c2f87f2. A bisect led me to 1224129c50e64aafb86fd4c2241759c100a0d594 as the first bad commit. This means that first commit in master where this is broken is 4e29b16166cd6cf519952936c533f77a169699dd, which is PR #85967. CC @BlueCube3310 @clayjohn 

The previous commit in master, 671f59f9be2a823066054325497e4b185517738b, works fine. 4.2-stable works fine.

Reverting #85967 / 4e29b16166cd6cf519952936c533f77a169699dd also fixes the issue.

### System information

macOS 14.2.1, Apple M1 Pro

### Issue description

When exporting a GLTF file from 4.3-dev, normal maps are broken. This was working in Godot 4.2-stable.

This is an export issue, not an import issue, because the file is also broken when importing into Blender.

### Steps to reproduce

1. Download and open the minimal reproduction project.
2. Open the scene `source.tscn`.
3. Click Scene -> Export As... -> glTF 2.0 Scene...
4. Save it as `boom_box.glb` in the `exported` folder.
5. Close Godot.
6. Delete the .godot/ folder (to avoid caching issues and force a re-import)
7. Open Godot again to the same project.
8. With the broken commits, observe the broken behavior. With the working commits, observe the correct behavior.

The correct appearance of the boom box is this:

<img width="679" alt="Screenshot 2024-01-30 at 8 20 47 PM" src="https://github.com/godotengine/godot/assets/1646875/e601f57e-7b47-4e7c-a77f-d814b0bc4b56">

The broken appearance of the boom box is this:

<img width="679" alt="Screenshot 2024-01-30 at 8 19 15 PM" src="https://github.com/godotengine/godot/assets/1646875/8972caa8-f060-4ffb-8b17-4f09cac4d063">

The normal map with the correct appearance in Godot 4.2-stable is this:

![boom_box_2](https://github.com/godotengine/godot/assets/1646875/c3cae461-f2f9-4c84-bbfe-9bad81c9f638)

The normal map with the incorrect appearance in the latest master is this:

![boom_box_2](https://github.com/godotengine/godot/assets/1646875/8599a722-60e1-4691-a0a5-5132480d0832)

### Minimal reproduction project (MRP)

[NormalMapExportBroken.zip](https://github.com/godotengine/godot/files/14106672/NormalMapExportBroken.zip)

**Comment by clayjohn** [comment]
Looks like the exporter code is here:

https://github.com/godotengine/godot/blob/313f623b9d102cc8c411ae7cab9518f98c2f87f2/modules/gltf/gltf_document.cpp#L3817C7-L3831C7

Seems like it shouldn't be calling since that should be done by `decompress()`
