### ISSUE TITLE
[Arm64]Compiling godot3.5-arm64 with mono failed.msbuild error code -6/1

### ISSUE THREAD

**Issue by Rmtdi** [godotengine/godot#87777]
### Tested versions

4.3dev（I clone the master branch at the beginning and ran into another error）
3.5stable

### System information

Debian12-arm64, godot3.5-stable, virgl

### Issue description

I tried compiling the C# version of godot3.5 arm. I followed the documentation tutorial and compiled the mono glue, but at the end I got an error when I rebuilt with Mono glue.

### Steps to reproduce

`scons p=x11 tools=yes target=release_debug module_mono_enabled=yes mono_glue=yes mono_prefix=/opt/mono_6.12`
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
Checking for `thread_local` support... supported
Found Mono root directory: /opt/mono_6.12
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[  0%] build_api_solution(["bin/GodotSharp/Api/Debug/GodotSharp.dll", "bin/GodotSharp/Api/Debug/GodotSharp.pdb", "bin/GodotSharp/Api/Debug/GodotSharp.xml", "bin/GodotSharp/Api/Debug/GodotSharpEditor.dll", "bin/GodotSharp/Api/Debug/GodotSharpEditor.pdb", "bin/GodotSharp/Api/Debug/GodotSharpEditor.xml"], [])
MSBuild path: /usr/bin/dotnet
[  3%] No usable version of libssl was found
[  5%] Compiling ==> main/default_controller_mappings.gen.cpp
[  5%] Compiling ==> main/tests/test_gdscript.cpp
[  5%] Compiling ==> main/tests/test_gui.cpp
[  5%] Compiling ==> main/tests/test_main.cpp
[  5%] Compiling ==> main/tests/test_math.cpp
[  5%] scons: *** [bin/GodotSharp/Api/Debug/GodotSharp.dll] RuntimeError : 'msbuild' exited with error code: -6
Compiling ==> main/tests/test_oa_hash_map.cpp
Traceback (most recent call last):
  File "/home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/build_scripts/solution_builder.py", line 106, in run_command
    subprocess.check_call(args, env=env_override)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/dotnet', 'msbuild', '/home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharp.sln', '/restore', '/t:Build', '/p:Configuration=Debug', '/p:NoWarn=1591']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/SCons/Action.py", line 1318, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/build_scripts/api_solution_build.py", line 21, in build_api_solution
    build_solution(env, solution_path, build_config, extra_msbuild_args=extra_msbuild_args)
  File "/home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/build_scripts/solution_builder.py", line 148, in build_solution
    run_command(msbuild_path, msbuild_args, env_override=msbuild_env, name="msbuild")
  File "/home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/build_scripts/solution_builder.py", line 108, in run_command
    raise RuntimeError("'%s' exited with error code: %s" % (name, e.returncode))
RuntimeError: 'msbuild' exited with error code: -6
scons: building terminated because of errors.
[Time elapsed: 00:00:33.586]

### Minimal reproduction project (MRP)

compiling failed

**Comment by akien-mga** [comment]
Can you run this command manually after the build failed, and post the full output?

```
/usr/bin/dotnet msbuild /home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591
```

**Comment by Rmtdi** [comment]
`/usr/bin/dotnet msbuild /home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591`

`Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET`
`Copyright (C) Microsoft Corporation. All rights reserved.`

  `Determining projects to restore...`
  `Restored /home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj (in 1.09 sec).`
  `Restored /home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj (in 1.09 sec).`

**Comment by akien-mga** [comment]
Well it's weird that it wouldn't say more, it sounds like it succeeded. But that's the command which failed initially.

Does the build now finish properly if you re-run `scons p=x11 tools=yes target=release_debug module_mono_enabled=yes mono_glue=yes mono_prefix=/opt/mono_6.12` in the source folder?

**Comment by Rmtdi** [comment]
In fact, the command just now (`/usr/bin/dotnet msbuild /home/lerio/code/gitclone/godot-3.5.3-stable/modules/mono/glue/GodotSharp/GodotSharp.sln /restore /t:Build /p:Configuration=Debug /p:NoWarn=1591`) after running it it and it reported an error saying that libssl was missing (probably what it means?), and then I downloaded and installed libssl 1.1, and it ran successfully

**Comment by Rmtdi** [comment]
I found that as long as I kept repeating the compilation instructions, the compilation progress would continue to increase, error, increase, error, I repeated about seven or eight times, to the last step, the last step still appeared the same error, this error seems to cause the final compiled binary file does not recognize the GodotSharp folder

**Comment by akien-mga** [comment]
Did you solve the issue?

If so, please share how so that future users with the same problem can find the solution.

**Comment by Rmtdi** [comment]
The first issue was solved, but new problems followed.
The first problem can be solved by installing libssl, and I have filed a new issue for the new problem #87807
