### ISSUE TITLE
Godot editor on android doesn't copy over dependencies whent they're located on sdcard.

### ISSUE THREAD

**Issue by lemonJumps** [godotengine/godot#87785]
### Tested versions

- Tested in: 4.2.1

Most likely occurs in all versions due to dependencies not being touched by the code that loads a library.

### System information

Godot v4.2.1stable - Android - Vulcan (Mobile) - integrated Adreno (TM) 619 - (8 Threads)

### Issue description

When opening a project with gdextension in the android editor, that is located on an sdcard, the gdextension file is copied over into a cache, however other dependencies are not copied over, causing the library to not load.

### Steps to reproduce

Have a single project with one GDExtenension library, and another library that is its dependency next to it, and a Gdextension file that has both library and dependency describet inside of it.

With this project placed onto an android phone, opening it will cause the error.

### Minimal reproduction project (MRP)

Here's a minimal project, (I've used the library which I'm currently using and is causing the issue, but it's in total over 10 MB): [https://github.com/lemonJumps/gdextension-bug](https://github.com/lemonJumps/gdextension-bug)

**Comment by Calinou** [comment]
cc @m4gr3d

**Comment by m4gr3d** [comment]
@lemonJumps Can you update the minimal project and make the shared library use a relative path when loading its dependencies; for example `dlopen("./libopencv_calib3d.so", ...)` instead of `dlopen("libopencv_calib3d.so", ...)`

The app is unable to update the `LD_LIBRARY_PATH` path on Android, which prevents your shared library from finding its dependencies after they are copied.

**Comment by m4gr3d** [comment]
@lemonJumps I've added a draft PR in https://github.com/godotengine/godot/pull/88381. Once you're able to update your MRP, I can validate that it works as expected.

**Comment by lemonJumps** [comment]
> @lemonJumps I've added a draft PR in #88381. Once you're able to update your MRP, I can validate that it works as expected.

thanks! I'll update it as soon as i can. life is currently  very hectic, so it might take me a week or so. I'll let you know once i do it \o/

**Comment by BSChad** [comment]
I know it's not an MRP, but https://github.com/alessandrofama/fmod-for-godot also suffers from this issue and could be used in testing. (It's the one that made me search out and try to find this!)

**Comment by m4gr3d** [comment]
> I know it's not an MRP, but https://github.com/alessandrofama/fmod-for-godot also suffers from this issue and could be used in testing. (It's the one that made me search out and try to find this!)

Thanks @BSChad! Do you see any specific errors when trying to use the the fmod plugin besides not loading?

**Comment by m4gr3d** [comment]
![Screenshot_20240419_074723_Godot Editor 4 (debug)](https://github.com/godotengine/godot/assets/914968/7b8f70a6-7475-4aff-86a5-980a4dd66ccb)

@BSChad I've tested with the changes from the PR, and the plugin now loads fine!
