### ISSUE TITLE
LOD or LOD Bias not working

### ISSUE THREAD

**Issue by verypleasentusername** [godotengine/godot#87784]
### Tested versions

4.2.2 only.

### System information

windows 10, 4.2.2, Forward+

### Issue description

`LOD Bias` value change visually does nothing, no mesh detalization drop. When coverted to ArrayMesh (Make Unique button) LOD  didn't work either.
![image](https://github.com/godotengine/godot/assets/63970682/5cdfb80f-75f4-48f1-aed2-be152d8bc5cf)
![image](https://github.com/godotengine/godot/assets/63970682/89a69b0c-d823-4189-a67e-40244e9ddbef)

### Steps to reproduce

Download MRP, open the scene, switch to wireframe mode and try to spot any mesh changes.

### Minimal reproduction project (MRP)

[LOD_MRP.zip](https://github.com/godotengine/godot/files/14112048/LOD_MRP.zip)

**Comment by roalyr** [comment]
As far as I know, LODs are generated only when importing .gltf scene (not mesh, like .obj, and not when using built-in mesh primitives).

**Comment by Calinou** [comment]
Closing per @roalyr's comment. You can get LOD generation to work with OBJ files if you change its import type from the default **OBJ as Mesh** to **Scene**. See also https://github.com/godotengine/godot-proposals/issues/5600.
