### ISSUE TITLE
set_bone_global_pose_override can not deal raycast bind on bones on godot4.2.1

### ISSUE THREAD

**Issue by yythlj** [godotengine/godot#87791]
### Tested versions

4.2.1.release

### System information

windows10 godot4.2.1

### Issue description

In Godot 4.2.1, I use ![rotate_bones](https://github.com/godotengine/godot/assets/33251075/60d2051f-39b2-4672-8f2a-2e5cf6a388ad)to adjust the spine bone of a Skeleton3D in order to modify the upper body of a character. Ultimately, there is a Node3D node attached to the right_hang bone, which includes a RayCast node. When I enable debug mode, I notice that the RayCast moves along with the adjustments made to the bone, but the target_position returned by the raycast is 
![rotate_bones](https://github.com/godotengine/godot/assets/33251075/0dda1dc4-208e-4a01-8e93-e92656af0fd9)
incorrect (it does not account for these adjustments). This is strange, as seen in the debug mode screenshot, where the raycast is pointing towards the upper left direction, but the calculated target_position still points to the position without the bone adjustments.

### Steps to reproduce

a mixamo fbx import，and create a node bind the model bones
	var bone_node = BoneAttachment3D.new()
	add_child(bone_node)
	var bone_idx = skele.find_bone("RightHand")
	bone_node.set_use_external_skeleton(true)
	bone_node.set_external_skeleton(skele.get_path())
	bone_node.set_bone_name(bone_name)
	bone_node.set_bone_idx(bone_idx)
	bone_node.set_name(node_name)

and then add a scene as a child to the bone_node which like this
![weapon](https://github.com/godotengine/godot/assets/33251075/82c83071-961e-4954-8292-716befbe6a21)
then use the set_bone_global_pose_override to change the spine rotate
		var spine_rotate = 30
		var spine_bone_idx = 1
		var spine_trans = skele.get_bone_global_pose(spine_bone_idx)
		spine_trans.basis = spine_trans.basis.rotated(Vector3.LEFT, spine_rotate)
		skele.set_bone_global_pose_override(spine_bone_idx, spine_trans, 1, true)
and run in debug mode with open raycast see

the raycast position = raycast.global_transform * raycast.target_position
is not right

### Minimal reproduction project (MRP)

pass

**Comment by fire** [comment]
It would help us debug this if you can provide a stripped project that can help describe the problem.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
