### ISSUE TITLE
Godot becomes unresponsive when adding tiles of tile size 2x2

### ISSUE THREAD

**Issue by Jodios** [godotengine/godot#87808]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Windows 11 and MacOS 14.3

### Issue description

Godot becomes unresponsive when i try to add my tiles into a tilset of size 2x2. It works perfectly fine with 4x4.

Also found the same issue [here](https://github.com/godotengine/godot/pull/86568) that's marked as fixed though. 

https://github.com/godotengine/godot/assets/35905299/19d2b16f-adb2-4475-84a3-56b2e2bc973c

### Steps to reproduce

create a tilemap with a tileset of size 2x2, add physics layer, and then add tile assets.

Or clone my MRP and try to drag the asset into the tileset.

### Minimal reproduction project (MRP)

https://github.com/Jodios/GodotCrash
[zip](https://github.com/Jodios/GodotCrash/archive/refs/heads/master.zip)

**Comment by Zireael07** [comment]
dupe/related to #86496?

**Comment by AThousandShips** [comment]
Can you test with [4.3.dev2](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-2/) this might have been fixed

**Comment by Jodios** [comment]
@AThousandShips 
My bad. Looks like it works with 4.3.dev2. 

Closing this issue.
