### ISSUE TITLE
AudioStreamPlayer does not call "finished" signal

### ISSUE THREAD

**Issue by EnlightenedOne** [godotengine/godot#87802]
### Tested versions

Reproducible on 313f623b9d102cc8c411ae7cab9518f98c2f87f2
Introduced by https://github.com/godotengine/godot/pull/87061

### System information

Godot v4.3.dev.mono (313f623b9) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

AudioStreamPlayer never calls "finished" and emits no notifications, it also does not call AudioStreamPlayerInternal::process the impact beyond no notifications is not fully understood.

The cause is that AudioStreamPlayerInternal::play_basic now calls:
  _set_process(true);
Instead of:
  set_process_internal(true);

In the Node flow this triggers a different notification type but AudioStreamPlayerInternal::notification still uses
  case Node::NOTIFICATION_INTERNAL_PROCESS: {
  process();
  } break;

The 2D + 3D versions are fine as they use the internal physics loop notification to drive calls to process.

### Steps to reproduce

If you open the attached MRP in 4.2 stable it will repeat a small sound immediately as the main scene loads and log a message saying everything is looking good.

If you run a local build of 4.3+ and open the MRP it will play the sound once everytime you reopen the scene and you wont see any log message occuring.

### Minimal reproduction project (MRP)

[MRP_AudioFinished.zip](https://github.com/godotengine/godot/files/14118721/MRP_AudioFinished.zip)

**Comment by EnlightenedOne** [comment]
I dont yet understand what determines if you should use the internal notiifcation type so im not sure which way would be considered the right way to fix it alignment wise.

**Comment by Calinou** [comment]
cc @KoBeWi
