### ISSUE TITLE
Godot Crashed while click on edit GridMap

### ISSUE THREAD

**Issue by WithSJ** [godotengine/godot#87805]
### Tested versions

Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
i am only using this version

### System information

22.04.1-Ubuntu Linux

### Issue description

In my project, I'm using multiple hierarchical **grid maps.** When attempting to edit the **"gridmaplib"** within the editor, it unexpectedly crashes. Interestingly, this issue only occurs within the editor; there are no problems during gameplay. Upon investigation, I've observed that the crash specifically happens when trying to edit a nested grid map that is placed under another grid map. For instance, when attempting to edit the "PalaceTop" grid map directly, the crash occurs. However, if I first edit a grid map that is not nested within another grid map, such as "OutMapWall", and then proceed to edit "PlaceTop", the issue does not occur.

```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
ERROR: FATAL: Index p_index = 1 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:158)
```
![Screenshot from 2024-02-01 08-23-49](https://github.com/godotengine/godot/assets/44628192/dcbf6ea1-76b4-470d-a990-71fac3610f4c)

![Screenshot from 2024-02-01 08-24-19](https://github.com/godotengine/godot/assets/44628192/64e6bc25-e9bf-4ea4-a18e-2e631a00502e)

### Steps to reproduce

.

### Minimal reproduction project (MRP)

.

**Comment by WithSJ** [comment]
i clone repo and build it and the custom v4.3.dev.custom_build [9adb7c7d1] working perfectly there is no issue

**Comment by smix8** [comment]
Needs an MRP. A cowdata index error crash can be anything.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
