### ISSUE TITLE
Resizing Placeholder Texture requires reopen scene to take effect 

### ISSUE THREAD

**Issue by Hapenia-Lans** [godotengine/godot#87822]
### Tested versions

Godot Engine v4.2.1.stable.official.b09f793f5

### System information

Windows 11 Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3050 Ti Laptop GPU

### Issue description

<img width="1200" alt="image" src="https://github.com/godotengine/godot/assets/93276898/0f4f282f-30c5-48ea-b66d-41722faa64ad">

Then resize it to 128x:

<img width="1211" alt="image" src="https://github.com/godotengine/godot/assets/93276898/b99cbcfa-03d8-4292-b20f-5d300daa223a">

Reopen the scene:

<img width="1196" alt="image" src="https://github.com/godotengine/godot/assets/93276898/2c470831-fe0d-482d-a094-133195a277eb">

### Steps to reproduce

As above.

### Minimal reproduction project (MRP)

Very easy to reproduce.

**Comment by clayjohn** [comment]
Looks like we are just missing a call to `emit_changed();` in the `set_size()` function (for all Placeholder* types)
