### ISSUE TITLE
animation toolbar missing in 3D view

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot#87839]
### Tested versions

4.2.1.stable

### System information

Windows10 Godot 4.2.1

### Issue description

The animation toolbar for adding keyframes as well as autokeying is missing in 3D view.

This is the toolbar that's missing:
![image](https://github.com/godotengine/godot/assets/1812087/d85fd0f7-0b7a-41ae-9435-d8df175e0c50)

### Steps to reproduce

Open the animation panel in the 3D view, note the missing animation toolbar.

### Minimal reproduction project (MRP)

happens with any project

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/234, as autokeying is currently missing in the 3D editor.
