### ISSUE TITLE
Export variable value won't work if the scene is instanciated after value change

### ISSUE THREAD

**Issue by Vitorgus** [godotengine/godot#87837]
### Tested versions

- Reproducible in: 4.2.1, 4.0.4, 3.5.3, 3.4.5, 3.3.4, 3.2.3 (at this point I stopped testing in older versions)

### System information

Windows 10.0.22621 - Godot v3.5.3.stable (also present on v4.2.1.stable) - Godot 3: GLES2; Godot 4: GLES3 (Compatibility) - dedicated NVIDIA GeForce MX130 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 Threads)

### Issue description

I'm working on a space shooter, and the ship fires bullet every second automatically. The bullets have an exported variable `speed`. When the project is being executed, if I change the `speed` value, it will only update the speed of the bullets that are already in the scene, any bullet that spawns after the change will still have the old `speed` value.

### Steps to reproduce

- Create a scene with an exported variable
- Create another scene that spawn the first scene by code
- Run the project
- Change the value of the exported variable
- See that all new instantiated scenes won't have the updated value Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce MX130 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 Threads)

### Minimal reproduction project (MRP)

Godot 3 version: [export-variable-bug-godot-3.zip](https://github.com/godotengine/godot/files/14130275/export-variable-bug-godot-3.zip)
Godot 4 version: [export-variable-bug-godot-4.zip](https://github.com/godotengine/godot/files/14130290/export-variable-bug-godot-4.zip)

**Comment by dalexeev** [comment]
Are you changing the values in the Inspector or in the script? If in the Inspector, then the values should be updated, but only for one node/resource instance. If it's in a script, then perhaps it's really a bug/unimplemented feature related to hot reloading. Personally, I don't rely much on the feature for scripts, I just restart the project (for scenes it works well though).

**Comment by Vitorgus** [comment]
I'm changing in the inspector. Though it doesn't change for only one instance, it changes to all current instances of the node in the scene. But for any instance of the node created AFTER the change of value in the inspector, it won't have the updated value.

**Comment by Zireael07** [comment]
The point of exported variables is to let you change it for that one instance.

There's an open proposal for 'apply to base instance' which would solve your usecase

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8292.

**Comment by Vitorgus** [comment]
I'm still a little confused, and would love a bit more clarification if possible.

Are you talking about when there's an instance of a scene in the editor, let's say an `Enemy` scene inside a `Level` scene, and when you change an exported variable on `Enemy`, it will reflect only on this instance, and not on `Enemy2`, `Enemy3`, or even an `Enemy` instanciated another scene`Level2`? If so, then I agree that this behaviour makes sense.

But the situation I'm mentioning in this issue is slightly different. I have a `BaseBullet` that exports a `speed` variable, and an inherited scene `PlayerBullet` that can have a different `speed` value. Inside a `Level` scene, there are no instances of `PlayerBullet` when the scene starts, they will be instanciated on code when the player fires. What I'm doing is, when the game is running from the editor, I go to the `PlayerBullet` scene, and change the `speed` value. For all `PlayerBullet` currently instanciated on `Level`, they will have the changed `speed` value, and move faster. But if the player fires again, the newly instanciated `PlayerBullet` will run slower, it won't have the updated value of `speed` that was changed inside the `PlayerBullet` scene.

**Comment by Zireael07** [comment]
Ah! That would sound like a bug indeed!

**Comment by Vitorgus** [comment]
Then I apologize for my bad wording/description of the issue 😅

Since the issue has been closed, what should I do? Submit a new issue with better description, or will this issue be reopened, so I should update the description of this one?

**Comment by Vitorgus** [comment]
Also recently had the idea to test it a bit more, and it's happening with any property of the node, not only exported variables.

If you change modulation, scale, rotation, or any other in the editor when the game is running, the modifications won't happen for the new instances added by code after those changes were made.
