### ISSUE TITLE
Dictionary: Merging previous key (number that has a dictionary value) causes the entire dictionary to be wrongly altered

### ISSUE THREAD

**Issue by Lukaswbrr** [godotengine/godot#87852]
### Tested versions

Reproducible in: 4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045

### Issue description

When merging a previous key id and changing the add_id to a different value, it causes all the dictionary to be changed
when it needed to only change the specific add_id value.

In the output, it prints all keys being affected by the change.

![DictionaryBug1](https://github.com/godotengine/godot/assets/49600807/90784ea8-e9b0-4c1b-9af7-bf205fc67bb5)

![DictionaryBug2](https://github.com/godotengine/godot/assets/49600807/598f72c8-e1dd-4cfb-bf02-c1baa1962a36)

### Steps to reproduce

1. Create a Node2D scene
2. Create a GDScript
3. Paste the following code:

```gdscript
extends Node2D

var test_string = "TestString"

var dictionary_test = {}

var add_id = 1

func _ready():
	
	add_id = 1
	add_dict_key(test_string, "variable1", "value1")
	add_id = 2
	add_dict_key(test_string, "variable2", "value2")
	add_id = 3
	add_dict_key(test_string, "variable3", "value3")
	add_dict_key(test_string, "variable3", "value3other")
	add_dict_key(test_string, "variable3", "value3another")


func add_dict_key(key, arg1 = null, arg2 = null): 
	if !dictionary_test.has(add_id):
		dictionary_test[add_id] = {}
		print(dictionary_test)
		print("Created ID key")
	
	if dictionary_test.has(add_id - 1): # When this code is not used, the bug doesn't occur
		dictionary_test[add_id].merge(dictionary_test[add_id - 1])
		print(dictionary_test)
		print_id()
		print("Merged")
		
	if !dictionary_test[add_id].has(key):
		dictionary_test[add_id][key] = {}
		print(dictionary_test)
		print_id()
		print("Created key")
	
	dictionary_test[add_id][key][arg1] = arg2
	print(dictionary_test)

func print_id():
	print("Previous current add dialogue id: " + str(add_id - 1))
	print("Current add dialogue id: " + str(add_id))

```

4. Attach the GDScript to the Node2D
5. Run scene

### Minimal reproduction project (MRP)

[DictionaryMergeBug.zip](https://github.com/godotengine/godot/files/14133748/DictionaryMergeBug.zip)

**Comment by timothyqiu** [comment]
I think this is expected. Dictionaries are passed by reference.

```gdscript
if dictionary_test.has(add_id - 1):
    dictionary_test[add_id].merge(dictionary_test[add_id - 1])
```

This makes 1 and 2 referencing the same `{ "variable1": "value1" }` dictionary instance.

So `dictionary_test[add_id][key][arg1] = arg2` affects the content of both 1 and 2.

**Comment by Lukaswbrr** [comment]
> I think this is expected. Dictionaries are passed by reference.
> 
> ```gdscript
> if dictionary_test.has(add_id - 1):
>     dictionary_test[add_id].merge(dictionary_test[add_id - 1])
> ```
> 
> This makes `[1]["TestString"]` and `[2]["TestString"]` referencing the same `{ "variable1": "value1" }` dictionary instance.
> 
> So `dictionary_test[add_id][key][arg1] = arg2` affects the content of both 1 and 2.

I guess you're right, i added this at the end of the function and it works fine now

```gdscript
        var new_key_dictionary = {
		key: {}
	}
	
	var new_value_dictionary = {
		arg1: arg2
	}
	
	new_key_dictionary.merge(new_value_dictionary)
	
	dictionary_test[add_id].merge(new_key_dictionary, true)
	print(dictionary_test)
```

Sorry for the late response
