### ISSUE TITLE
Game hangs in editor while doing vector math on SurfaceTool point y-values

### ISSUE THREAD

**Issue by thely** [godotengine/godot#87853]
### Tested versions

- Reproducible in 4.1.2 and 4.1.4

### System information

Godot v4.1.2.stable - macOS 12.6.5 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

I'm using `SurfaceTool` to generate 3D polylines to do directional arrows in a tactics game in response to mouse movement. While trying to optimize polylines that need to move vertically, I noticed the game would randomly hang (spinning beachball). It happens when you're standing on a non-zero-height platform and move the mouse around to try and select a new path. But I'm completely out of ideas for what the issue could be, and I feel like I've printlined just about everywhere I could. Here are some things I know it *isn't*:

- It shouldn't be an infinite loop of my own doing. My one and only while loop is a Dijkstra movement range loop (in `MapNavigator.gd`). It calculates once after every click, but this problem is happening during an `InputEventMouseMotion`.
- The print statement on the other side of my polyline generator prints successfully, which is at the very end of my main `_input()` function. Based on print lines alone, it seems to never make it to the next iteration of `_input()`.
- I'm not getting any of the typical debug errors for `SurfaceTool` indicating that I'm using the wrong number of vertices for `PRIMITIVE_TRIANGLES`. There are no errors or debug warnings in the console whatsoever. The game also never crashes; it just hangs.
- Theoretically it could be `AStar3D` at fault (in `MapNavigator.gd`, but since `MapPathIndicator.gd` is somehow the cause (see below), and it generates the polyline off of points handed to it *by* `AStar3D`, this seems unlikely.

There are two back-to-back spots in `MapPathIndicator.gd` that are part the problem, I just can't figure out why. They're both just vector math. There are `#BUGREPORT` comments at both points, but for reference:

```gdscript
	# BUGREPORT1: comment out these two lines to remove the hang completely
	var off: Vector3 = pos1 if pos1.y < pos2.y else pos2
	off.y = pos2.y if pos2.y > pos1.y else pos1.y

	# BUGREPORT2: uncomment these four lines to really blow up the scene
#	var diff: Vector3 = pos2 - pos1
#	diff.y = 0
#	off += diff
#	print(diff)
```

### Steps to reproduce

- Run the project.
- Click on a 1-unit-high block, like (1,1,2), to walk to it. This will work fine.
- Hover randomly onto a number of other tiles to view their paths, but don't click on any of them. It shouldn't take more than 4-5 new path calculations for the game to hang.
- If you try going up to the 2-unit-high block and path downwards, it seems like it doesn't generate this bug. Same with exclusively walking around on the 0-level, and never ending your path on a 1-unit-high block.

To completely remove the bug:
- In `MapPathIndicator.gd`, find the comment labeled `BUGREPORT1` and comment out the two lines below it. Now, no matter what kind of path you select, the game will never hang. The pathing just looks worse.

To make things much stranger:
- In `MapPathIndicator.gd`, uncomment the two lines below `BUGREPORT1` and the four lines below `BUGREPORT2`. It's the same lines as the ones above in the issue description.
- Run the project. It should hang immediately, sometimes before even selecting a path.

### Minimal reproduction project (MRP)

[3D Pathing Test.zip](https://github.com/godotengine/godot/files/14134626/3D.Pathing.Test.zip)

**Comment by smix8** [comment]
You do not get a Godot error because it crashes inside the third-party lib for the mesh tangents generation with SurfaceTool.generate_tangents().

The project also crashes on other random array errors that are unrelated, like in the pathfinding when your rapid fire input events.

**Comment by thely** [comment]
@smix8 Thank you so much! Managing rapid-fire inputs is on my to-do list, but the tangent issue was beyond my current level of knowledge. Maybe this should be considered as an error to display inside Godot if possible, but otherwise I'd consider this closed.
