### ISSUE TITLE
Filesystem 4.x regression : Files/fodlers starting with "_" are displayed AFTER "a"/"z" instead of before as it works in other softwares (including Godot 3.X)

### ISSUE THREAD

**Issue by Hyrilorius** [godotengine/godot#87868]
### Tested versions

Reproducible in Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 () - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

In Godot 4.X, the filesystem now wrongly consider files/folders starting with an underscore \"_" should be displayed before files/folders starting with "a" or "z".

- This is a big issue because it prevents users to easily organize the files/folders by just adding \"_" before the files/folders we want to list first in their own folders.
- The workaround of renaming them "a\_" still doesn't work because for example "actions" would still be displayed before "a\_". So we need to do "aaaaaa_" instead, which is annoying to do and hurts readability
- An other issue with this is it means the order of files is different between Godot 4 and other softwares such as Windows Explorer, VSCode and even Godot 3 !

❌ The way it's currently displayed in Godot 4 ("\_" comes after "a" or any letter)

![image](https://github.com/godotengine/godot/assets/9054802/3cd9ccb2-8b7a-4154-8a7f-204e45cdc377)

✅ The way it should be displayed (as in Godot 3, Windows Explorer, VSCode, and almost any software)

![image](https://github.com/godotengine/godot/assets/9054802/39e11f6a-4fba-4e4b-bd43-e6876813a2c4)

### Steps to reproduce

1. Create several folders (or files)
2. Name one so it starts with an underscore "_"
3. The folder starting with "_" is displayed AFTER the other one starting with letters, while it should be displayed first

### Minimal reproduction project (MRP)

[FileSystem_4.X_OrderIssue.zip](https://github.com/godotengine/godot/files/14140758/FileSystem_4.X_OrderIssue.zip)

**Comment by AThousandShips** [comment]
Note that this was introduced in:
* https://github.com/godotengine/godot/pull/37796

As an intentional improvement to unify sorting
