### ISSUE TITLE
Arabic font not included when performing a web build

### ISSUE THREAD

**Issue by AlaDiab** [godotengine/godot#87879]
### Tested versions

Didn't really check other versions but its V4.2.1

### System information

Windows 11 - Godot 4,2,1 - Forward+

### Issue description

I'm adding Arabic text to a label node and in a Meshinstance to test export to HTML. When I build to desktop everything is fine but when I build to we and open it in a local server its all mangled.
![Screenshot 2024-02-02 141617](https://github.com/godotengine/godot/assets/7275396/80be6db7-0784-4a9a-ab92-0f729d349bff)
![Screenshot 2024-02-02 141648](https://github.com/godotengine/godot/assets/7275396/eda45301-615e-4dd4-9058-04022d1ce44f)

### Steps to reproduce

Just create a label and add any arabic text to it and build for web in version 4.2.1

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/14145210/project.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84590, as this is due to the same cause.

**Comment by Calinou** [comment]
> Thanks! So is there a solution in the making? Or is it something I can do on my side?

As described in the linked issue, load a custom font that contains Arabic characters in your Label3D properties. This way, you won't rely on system fallbacks to display Arabic characters.

**Comment by AlaDiab** [comment]
Ok. I was using Tahoma which supports arabic but I guess it's system font? So doesn't work?

I will check out the link thanks for all your help.

**Comment by Calinou** [comment]
> Ok. I was using Tahoma which supports arabic but I guess it's system font? So doesn't work?

Indeed, Tahoma is a system font and you're not allowed to redistribute it per Microsoft's EULA. This means you shouldn't copy it to your project folder, but use a font that can legally be redistributed and embedded in applications instead.

**Comment by AlaDiab** [comment]
Makes perfect sense.
Thanks again.
