### ISSUE TITLE
Certain editor operations rely on `NOTIFICATION_PHYSICS_PROCESS` without a good reason

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#87885]
### Tested versions

- Reproducible in: 4.2.1.stable, 4.3.dev cae759949

### System information

Godot v4.3.dev (cae759949) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Certain editor operations rely on `NOTIFICATION_PHYSICS_PROCESS` without a good reason. This is mainly seen through `canvas_item_editor_plugin.cpp` and `node_3d_editor_plugin.cpp`.

This has two consequences:

- At default physics ticks per second (60), moving around 2D elements in the editor results in the orange box being slightly behind and updating less smoothly on high refresh rate monitors.
- At custom physics ticks per second, editor behavior will differ with these elements appearing to lag behind more if the value is lower than 60.

### Steps to reproduce

See this 120 FPS video where a Sprite2D is being dragged around quickly (watch it at 0.5× speed or pause at certain moments to make the issue more noticeable):

https://github.com/godotengine/godot/assets/180032/ffc4cd67-29dc-4d41-aec7-f772d60e7ba8

If **Physics Ticks per Second** project setting is set to 10 and the editor is restarted, the issue becomes more extreme:

https://github.com/godotengine/godot/assets/180032/7bd95c3f-a865-4c9f-8c2d-e014aaed5801

### Minimal reproduction project (MRP)

N/A

**Comment by ryevdokimov** [comment]
I submitted a PR and tested the different things that were originally part of physics processes. I didn't notice a difference besides the stuff you mentioned not being broken anymore.
