### ISSUE TITLE
ImageLoader can't load grayscale JPEG image

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#87895]
### Tested versions

4.2.1

### System information

macOS 14.3

### Issue description

It seems the JPEG format supports multiple color space models, (The first answer here seems to give good information about this: https://stackoverflow.com/questions/50798014/determining-color-space-for-jpeg ) but it seems the Godot image_loader jpeg parser does at least not support Grayscale jpeg images. 

Trying to load/import such an image just fails with the following error:
`core/io/image_loader.cpp:101 - Error loading image: res://graphics/Amelia-Earhart.jpg`

### Steps to reproduce

Try to load a grayscale jpeg image, for example by adding it into your project. Like this sample file: [Amelia-Earhart.jpg](https://www.lostminds.com/godot/Amelia-Earhart.jpg)

### Minimal reproduction project (MRP)

Just the file above should be enough

**Comment by FantasmaGolicon** [comment]
Seems similar to issue #45523. Godot is using a [third-party library for loading JPEGs](https://code.google.com/archive/p/jpeg-compressor/). I debugged locally, and the loader is failing on the same error as reported on the issue. I believe this is just a limitation of the Engine for now.

**Comment by lostminds** [comment]
Thanks for looking into it @FantasmaGolicon, perhaps it is the same issue then. However, in #45523 it seems the sample file was using some unusual sampling factors. In this case I thought this file was just using a grayscale color space (single channel) which according to https://code.google.com/archive/p/jpeg-compressor/ should be supported in decompressing?

**Comment by FantasmaGolicon** [comment]
Grayscale should be supported. By looking in the debugger, it looks like the image has unexpected sampling factors. The jpeg decoder is expecting grayscale images to have a sampling factor of 1 for both horizontal and vertical sampling. The image you provided has a sampling factor of 2, and therefore it fails decoding the image with that same error (JPGD_UNSUPPORTED_SAMP_FACTORS)

Where is this image coming from? Do you have control of exporting the image?

**Comment by lostminds** [comment]
I see, then this is just a duplicate of https://github.com/godotengine/godot/issues/45523 so I'll close this issue. The grayscale colorspace was the only thing I could tell was different about this JPEG, so I assumed that was the issue. 

As for the source I'm afraid I'm not sure what it is encoded in. It's part of a set of old portrait photos I use as test files for various graphics apps, originally from various creative commons sources. Since they're so old it might be that the files are also quite old and were encoded in old software that used more unusual jpeg configurations.

If you think adjusting the sampling factor to an accepted value would fix the issue without corrupting the image that is decoding that would be great, I don't know enough about how the sampling factor is used in jpeg decoding to know if that's feasable. But since it's defined in the file and the decoder rejects non-1 instead of using the values I'd assume it has some non-trivial impact on how the data should be interpreted.
