### ISSUE TITLE
Add support for converting arbitrary BBCode colors to truecolor ANSI escape codes in `print_rich()`

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#87899]
### Tested versions

Present in all 4.x docs,
haven't checked 3.x.

### System information

N/A

### Issue description

The docs explicitly say only these colors are supported in `print_rich`:
![Godot_v4 3-dev2_win64_PzIxbWjGiJ](https://github.com/godotengine/godot/assets/102416174/f54ab08d-1735-4a5c-bc82-52ad0d92282a)
even though [all others](https://raw.githubusercontent.com/godotengine/godot-docs/master/img/color_constants.png) also seem to be working fine.

### Steps to reproduce

`print_rich('[color=tomato]tomato color![/color]')` - Works fine

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Docs are correct, `color=tomato` will only show in the editor log (since it's RichTextLabel and support all colors), but won't show in the OS terminal.

**Comment by Calinou** [comment]
I was working on implementing arbitrary color code conversion to truecolor ANSI escape codes, but I couldn't get it to work yet.

**Comment by Swarkin** [comment]
> Docs are correct, `color=tomato` will only show in the editor log (since it's RichTextLabel and support all colors, and other RTL features like `img`), but won't show in the OS terminal.

Oh okay I wasn't aware that this was related to the terminal! The fact about bbcode to ansi conversion is only mentioned a bunch of lines below so I thought that it applied to the Godot output.
