### ISSUE TITLE
GDScript classes can be replaced by anything

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8791]
The following code works:

```gdscript
	Sprite = 42
	print(Sprite)
```

And effectiveley replaces `Sprite` as if it was a normal global variable.
It looks like a bug, and a way to troll a game project really hard^^
Someone (maybe accidentally) did that in a QA thread: https://godotengine.org/qa/14991/extention-add_exception-nonexistent-function-add_exception

Might be related to https://github.com/godotengine/godot/issues/6221

**Comment by Zylann** [comment]
Still happens in Godot 3.0 stable.

**Comment by vnen** [comment]
Solved by #19264.
