### ISSUE TITLE
Alt + RMB lets you list select in any tool mode in 3D

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#87924]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]
v4.3.dev.custom_build [677bd9783]

### System information

Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

This is either a bug or needs a description for all the tools.

![image](https://github.com/godotengine/godot/assets/105675984/bf381a96-b001-477d-a518-d910d6a625d5)

![image](https://github.com/godotengine/godot/assets/105675984/a9321f2f-0a2e-4ce7-b097-c78f00291ccf)

![image](https://github.com/godotengine/godot/assets/105675984/26a224f5-d3f0-496a-9c63-2a34f43ab313)

### Steps to reproduce

Select any tool that isn't the 'Select Tool' and ALT + RMB on a position with multiple nodes. 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This seems to be by design, and very old, it allows any modes *except* transform:
https://github.com/godotengine/godot/blob/f427d2f0d35f27273e856871f8588652632d8ac2/editor/plugins/node_3d_editor_plugin.cpp#L1662-L1671

**Comment by ryevdokimov** [comment]
I couldn't find it documented anywhere (besides the code being it is what it is). It also doesn't match 2D behavior or what the tooltips say.

**Comment by ryevdokimov** [comment]
Hmm, after playing around with it just now I actually agree. Personally, I think you should always be always to select other things such as in the draft I made that I linked above, but that's a different topic.
