### ISSUE TITLE
Use signals in C# when run project will crush.

### ISSUE THREAD

**Issue by Misaka-Tang** [godotengine/godot#87921]
### Tested versions

4.2.1-stable

### System information

MacOS 14.2.1

### Issue description

when I creates signals using c# then after running it will crush.

### Steps to reproduce

Choosing two way 
```
  public override void _Input(InputEvent @event)
    {
        base._Input(@event);
        if (@event is InputEventMouseButton mouseButton && mouseButton.Pressed && mouseButton.ButtonIndex == MouseButton.Right)
        {
            hP -= 1;
            logStatus();
        }
        }
```
or 

```
public override void _Ready()
    {
        base._Ready();
        area2D.Connect("mouse_entered", new Callable(this, "logStatus"));
    }
```
will shutdown, but no any output from godot editor.

### Minimal reproduction project (MRP)

/

**Comment by Misaka-Tang** [comment]
not only 'Area2D' but 'collisionShape2D's signal functions will shutdown without tips code by c#.

**Comment by Calinou** [comment]
@Misaka-Tang Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:
