### ISSUE TITLE
Editor randomly crashes whilst working on plugin with GDScript.

### ISSUE THREAD

**Issue by OzgurLAPTOP** [godotengine/godot#87931]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19044 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 620 (Intel Corporation; 27.20.100.9664) - Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 Threads)

### Issue description

I normally use c#. But for this plugin i decided to go with GDScript. But the editor seems to randomly crash without any errors. 
I also tested it with the console version. The whole thing just crashes without displaying any errors.

### Steps to reproduce

Its a plugin that is added as a child of a Sprite2D to cast a shadow for it. It reads its parents texture and displays it back as a shadow. There is also an autoload which i add when creating a custom type. This autoload is intended to control the shadow direction and distance etc. Use mono version.

### Minimal reproduction project (MRP)

[ShadowSprite2DPlugin.zip](https://github.com/godotengine/godot/files/14155943/ShadowSprite2DPlugin.zip)

**Comment by FullDevMike** [comment]
I am using Godot v4.2.1.stable.mono - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.4633) - 13th Gen Intel(R) Core(TM) i9-13900KS (32 Threads) 

but your example project seems to work for me, is there something more than importing the project and having the autoload & plugin enabled? 
<img width="1922" alt="Screenshot 2024-02-04 011400" src="https://github.com/godotengine/godot/assets/1005054/3ff5c848-af8e-4397-8298-0602202e1c19">

**Comment by dalexeev** [comment]
> I also tested it with the console version. The whole thing just crashes without displaying any errors.

A crash means that the game/editor closes with an error. Soft locks and other bugs are not considered crashes. Usually, when a crash occurs, a dump like this is printed:

```
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42910) [0x7fb4db442910] (??:0)
[2] /home/danil/.local/bin/godot4() [0x773273] (??:0)
[3] /home/danil/.local/bin/godot4() [0x66e342] (??:0)
...
```

Is something being printed in your case? Please describe in more detail how and when the bug appears.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
