### ISSUE TITLE
UPNP does not find valid gateway

### ISSUE THREAD

**Issue by dtgreene** [godotengine/godot#87953]
### Tested versions

Godot v4.2.stable

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3742) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Calling `discover()` on a new UPNP instance works as expected and my router shows up as one of the devices found.  However, `get_gateway()` always returns null without any further messages.  UPNP is enabled on the router.

Router:

![image](https://github.com/godotengine/godot/assets/24302976/77adadbf-4b58-4b4e-bc01-b84526b67f7e)

Script:
```gdscript
extends Node3D

func _ready():
	var upnp = UPNP.new()
	var upnp_result = upnp.discover(2000, 2, "")
	
	if upnp_result == OK:
		for i in upnp.get_device_count():
			var device = upnp.get_device(i)
			print("Description URL: " + str(device.description_url))
			print("IGD Status: " + str(device.igd_status))
			print("Is Valid Gateway: " + str(device.is_valid_gateway()))
		
		print(upnp.get_gateway())
	else:
		print("UPNP discover not OK: " + str(upnp_result))
```

Godot reports the IGD status as 5 or "Not Connected".  I downloaded the miniupnpc client and added the mapping directly through the CLI.  It also reported the status as not connected but continued anyway and worked successfully.

![image](https://github.com/godotengine/godot/assets/24302976/60b082b7-0ccf-4a6b-96dc-9313cdcad298)

I'm not sure if this would still be considered a bug but I wonder if it's possible for Godot to behave this way as well since the mapping can still be added even with the not connected status.

### Steps to reproduce

1. Create a new UPNP instance
2. Call `upnp.discover()`
3. Check `upnp.get_gateway()`

### Minimal reproduction project (MRP)

[demo.zip](https://github.com/godotengine/godot/files/14157856/demo.zip)

**Comment by DanielKinsman** [comment]
I think it's not up to Godot to behave the same way, it's up to your gdscript code? Can you not just call the add port mapping function on the individual device?

https://docs.godotengine.org/en/stable/classes/class_upnpdevice.html#class-upnpdevice-method-add-port-mapping

**Comment by dtgreene** [comment]
I did try adding the port mapping but the result was the same, failed due to no gateway.  From what I can tell, this check happens in the thin wrapper Godot has around the underlying miniupnpc library:

https://github.com/godotengine/godot/blob/master/modules/upnp/upnp.cpp#L315-L323

**Comment by brunoCreator** [comment]
Is it your primary router or secondary, I have this problem when using my secondary router connected to another router that connects directly to the provider. When I use the primary router, it works fine.
My secondary router is a tp-link, and my primary router is ZTE.

**Comment by brunoCreator** [comment]
It is unfortunate that the only free alternative for networking is UPnP, that is disabled on most routers. There should be a better option, without having to expend money in a tunneling service.

**Comment by Calinou** [comment]
@dtgreene Do you have two routers in your network setup (i.e. behind double NAT)? If so, you won't be reachable from the Internet unless one of the routers is on the DMZ (i.e. has **all** its ports forwarded) to avoid a double NAT situation.

**Comment by dtgreene** [comment]
@Calinou I only have the one router setup in my house.  I was thinking maybe Godot's implementation with `miniupnpc` just needed tweaking since you can add the mapping through their CLI but not with Godot.  

Either way I learned that UPnP really isn't a great solution and I'd be better off with a NAT punchthrough or a relay server.  I left this issue open because I thought this was still a genuine bug.  I can close it though if it doesn't seem like a problem.

**Comment by steveoriol** [comment]
I agree with @dtgreene , even if we can do otherwise, it's still a bug and we can't use UPnP directly from Godot, and that's not frustrating.

**Comment by DanielKinsman** [comment]
IMO technically this is not a bug in godot, this is a bug in your router which is reporting the wrong status. If you really want Godot to work around this router bug you can implement that yourself but I don't think it needs to be standard.

In fact I'd go even further and suggest godot should deprecate upnp support altogether. People should also disable it on their routers for security reasons.

UPnP is not a workable solution for any game released to the general public in 2024 as many or even most ISPs these days use CGNAT by default and most routers disable upnp, or have buggy implementations as you have discovered. Your players are going to have a bad time wondering why multiplayer doesn't work for them. Or worse they are going to be encouraged to turn on upnp just to make your game work and then run into security issues later on which could have been avoided.

**Comment by steveoriol** [comment]
Ok, I agree, upnp should be removed from godot because it doesn't work for many routers (even big brand, known and up to date) [mine is a Synology RT2600ac]... and I don't think it's a router problem in my case, because I can create UPnP routers without any problem with an external tool like “[UPnP Router Control](https://gitlab.gnome.org/DnaX/upnp-router-control)”:
![Sélection_130](https://github.com/user-attachments/assets/2785e03c-46a8-4f93-bc50-f67684acbb14)
