### ISSUE TITLE
Label Nodes are displayed inconsistently when previewing and exporting to an exe file in the editor

### ISSUE THREAD

**Issue by DarkZ0528** [godotengine/godot#87965]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (Intel Corporation; 31.0.101.2111) - Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 Threads)

### Issue description

When adding a label node to a container, set its text content to some Chinese, and the length of the label node is larger than the container node, then set wrap-mode to word or word (smart).
in the editor preview,it works.Like this:
![bug (1)](https://github.com/godotengine/godot/assets/29927268/6b6cd8d7-39ea-4c78-8f10-b5508e380e46)
when I export the project to an exe file, run it.it works bad.
![bug (2)](https://github.com/godotengine/godot/assets/29927268/5ae7a10f-23eb-40bf-b2a2-a90532a45ed4)

### Steps to reproduce

run in ediror preview or export to an exe file,the bug will reproduce.

### Minimal reproduction project (MRP)

[LabelTest.zip](https://github.com/godotengine/godot/files/14159968/LabelTest.zip)

**Comment by bruvzg** [comment]
For some languages line breaking require ICU database, it's not exported by default. You can enable export by checking `Project Settings` → `Internationalization` → `Locale` → `Include Text Server Data`

**Comment by DarkZ0528** [comment]
> 对于某些语言，换行符需要 ICU 数据库，默认情况下不会导出。您可以通过选中→ → →来启用导出`Project Settings``Internationalization``Locale``Include Text Server Data`

Ohhh,thanks! It works!
I will close this issue.
Maybe I should have taken a deeper look at the usage of the godot engine.
