### ISSUE TITLE
Crash when using `get_gravity` from `_process` while running physics on separate thread

### ISSUE THREAD

**Issue by mihe** [godotengine/godot#87975]
### Tested versions

Reproducible in: 4.3-dev [acde2a81f]

### System information

Windows 11 (10.0.22631)

### Issue description

The new `get_gravity` method that was added in #84640 relies on `body_get_direct_state`, which is not accessible outside of `_physics_process` and `_integrate_forces` when using the `physics/*d/run_on_separate_thread` project setting.

As such, it ends up throwing an error here:

https://github.com/godotengine/godot/blob/63d6bda8e95ac992da74e84b2f3be62f3d85190b/servers/physics_3d/godot_physics_server_3d.cpp#L924

... and subsequently crashes due to a `nullptr` access in `get_gravity`.

### Steps to reproduce

- Run the MRP
- Observe crash

### Minimal reproduction project (MRP)

[GravityCrash.zip](https://github.com/godotengine/godot/files/14167306/GravityCrash.zip)

**Comment by AThousandShips** [comment]
I'm on it

**Comment by mihe** [comment]
I appreciate that an error is preferable to a crash, but this maybe wasn't the fix I had hoped for. :)

I'll make a new issue for the error I guess.

**Comment by AThousandShips** [comment]
This matches the rest of the code, wasn't going to add an additional error originally

But you can't avoid an error entirely

**Comment by mihe** [comment]
Fair enough. Maybe creating an issue wasn't the right tool to use here. Ideally I wouldn't have fumbled the review of #84640 and this could've been discussed prior to merging this change, but alas.

I agree that your fix was the pragmatic fix in this case, and lines up with how `get_contact_count` does it, and an error is absolutely better than no error. My issue was more with the usage of `body_get_direct_state` to begin with, but I guess that's a broader topic that's maybe better suited for elsewhere, as you point out.

(Also, I didn't mean for my previous comment to come off as snarky as it did. I appreciate the quick fix, of course.)

**Comment by AThousandShips** [comment]
Thank you! Making a report was the appropriate thing to make sure the crash was resolved, that shouldn't have been left untended to, but a broader improvement would be good to discuss too :)
