### ISSUE TITLE
HSlider with the joystick held to either left or right doesn't increment the step until we release the stick.

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#87986]
### Tested versions

Reproducible in 4.2.1, 4.2.2.rc1
Not reproducible in: 4.1.1, 4.1.2

### System information

Godot v4.2.2.rc1 - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) 

### Issue description

When using a gamepad to move a hslider with the joystick held to either left or right doesn't increment the step until we release the stick. It just moves one step and then stops. 

I understand this merged fix (https://github.com/godotengine/godot/pull/63168 and the linked proposal in there) the slider should increment the step until we release the stick but it doesn't. So I think this might be a regresssion

The fix also mentions popup_menu and I cant get it to work there either. 

_And d-pad also have issues with sliders not sure if it should be a separate issue or not. It works and then sometimes randomly stops incrementing the slider when held down._

### **4.2.1 and 4.2.2 rc1**

**HSlider** 
Joystick doesn't increment the step until we release the stick. 

**OptionButton** 
Joystick doesn't increment the step until we release the stick.

### **4.1.1 and 4.1.2**
**HSlider** 
Joystick is incrementing the step until we release the stick.

**OptionButton** 
Joystick is incrementing the step until we release the stick.

### Steps to reproduce

Add joypad axis left and right to ui_left, ui_right
Insert a HSlider and when it has focus try to move slider with the joystick held to either left or right.

### Minimal reproduction project (MRP)

[slider_test.zip](https://github.com/godotengine/godot/files/14170649/slider_test.zip)

**Comment by akien-mga** [comment]
CC @Levrault @KoBeWi @groud

**Comment by KoBeWi** [comment]
Can't reproduce in 4.3 on Windows.

**Comment by Giganzo** [comment]
Did a test with 4.3 dev 5 on Linux and haven't been able to reproduce it.

**Comment by KoBeWi** [comment]
So fixed. If you can find commit that fixed it, it could be possibly backported.
