### ISSUE TITLE
C++ MAKE_TYPED_ARRAY does not include newer Variant types

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#87991]
### Tested versions

4.2.1 tag, current master ( d3352813ea44447bfbf135efdec23acc4d1d3f89 )

### System information

N/A

### Issue description

`typed_array.h` has a number of lines that use the `MAKE_TYPED_ARRAY` macro for almost all `Variant` types. This was introduced back in 2020. But when the `VECTOR4`, `VECTOR4I`, and `PROJECTION` types were added, it seems that this list was never updated to include them.

https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/core/variant/typed_array.h#L91-L132

This means that it is not possible to write something like this:

`TypedArray<Vector4>`

...even though it is possible to write this:

`TypedArray<Vector3>`

I also noticed that the `OBJECT` type was never included in this list. I can only presume this was an intentional omission...?

### Steps to reproduce

Try to compile `TypedArray<Vector4> my_array;`. Note that this results in this compile error: `typed_array.hpp(53): error C2039: 'get_class_static': is not a member of 'godot::Vector4'`

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
`Object` is by design, as without a dedicated declaration it solves it by the `get_class_static` method that it fails with there

**Comment by allenwp** [comment]
> `Object` is by design, as without a dedicated declaration it solves it by the `get_class_static` method that it fails with there

Ah, thanks for the explanation!
