### ISSUE TITLE
Tab key can't be used in editor shortcuts.

### ISSUE THREAD

**Issue by 27thLiz** [godotengine/godot#8799]
**Operating system or device - Godot version:**
Linux - Master

**Issue description:**
When pressing an Editor shortcut that involves the `Tab` key, Godot will focus the next `control` instead of activating the shortcut. Easily testable with the default "next/prev scene" shortcut.

**Steps to reproduce:**
- Have 2 or more scenes open.
- Press `ctrl + tab` or `ctrl + shift + tab`
- ...
- Don't Profit :(

**Comment by thagberg** [comment]
This seems to stem from the "ui_focus_next" inputs being checked in the viewport code (and then set to handled), whereas the "editor/next_tab" shortcut is polled in `EditorNode::_unhandled_input`.

**Comment by Nallebeorn** [comment]
This might be related to #18793, as Viewport shouldn't really consume/handle tab key events if extra modifiers (like Ctrl) are held down.

**Comment by NilsIrl** [comment]
Working on it

**Comment by akien-mga** [comment]
Reopening as #30721 was reverted.
