### ISSUE TITLE
Editor Freezes on Dual Monitor Setup

### ISSUE THREAD

**Issue by yadavvishal1** [godotengine/godot#88007]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Main Display Resolution is 1920*1080(Landscape Mode), and Secondary Monitor is 1024*1280(Portrait Mode), Ideally, I would like to Have My Script Editor opened in Portrait Mode(1024*1280). But It crashes every time I try. Basically anything I try to do with dual monitor setup freezes and crashes.
I am not able to open one of my projects because I exited the engine while the engine was being Opened on Dual Monitors.

### Steps to reproduce

 #87238

### Minimal reproduction project (MRP)

#87238

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74261.
