### ISSUE TITLE
Editor freezes when zooming in or out in the code editor

### ISSUE THREAD

**Issue by Toma611** [godotengine/godot#88016]
### Tested versions

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### System information

Godot v4.2.1.stable - Windows 10.0.22621(its windows 11 for some reason it says 10 when I copy from godot) - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

when I zoom in or out using the scroll wheel(which is not smooth but I don't care that much) in the code editor, the entire editor freezes for like 2 seconds

### Steps to reproduce

zoom in or out in the code editor

### Minimal reproduction project (MRP)

[Test For Bug.zip](https://github.com/godotengine/godot/files/14180290/Test.For.Bug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/82144

This has been fixed in 4.3
