### ISSUE TITLE
Image -> *.stex conversion is broken since it was made a Resource.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#8801]
**Operating system or device - Godot version:**
linux, tip 787dad5ac4341a90ecf135884d8ca71bdbd5d252

**Issue description:**

The COMPRESS_LOSSLESS and COMPRESS_LOSSY GDSTs are (or are rendered as) black rectangles.

Reverting to d801ff2b3db2de105c1b36a74ce116e360143d4e fixes the issue.

**Comment by Rukiri** [comment]
any idea of when this will be fixed? compiled godot and was shocked and thought I was having rendering issues...

**Comment by bojidar-bg** [comment]
@Rukiri Yes, it would be fixed before official 3.0 alpha, as per #8805. If you need the old behaviour, you can revert your local clone.
