### ISSUE TITLE
Shader Editor: completion issues using Esc and Enter

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#88013]
### Tested versions

- Reproducible in Godot 4.2.1

### System information

Debian GNU/Linux 12.4

### Issue description

1. When the completion list shows, pressing Esc makes the cursor disappear. It seems the editor looses focus and I have to click on the editor to restore the cursor and hide the completion list.
2. It also suggests keywords in places where it's common to put a new line, for example, after a comma in an array initialization. If I'm not fast enough typing a comma and pressing enter results in `,bool` written in the editor instead of comma and newline.

I can workaround both by disabling completion and using the completion query shortcut. Also, changing the shortcut for accepting the completion keyword to Ctrl-Enter is a good workaround for 2 when keeping completion list enabled.

I think a shortcut should be added for hiding the completion list (default to Esc) and fixing the Esc key removing focus from the editor (I don't know if there's a use for this).

I think removing Enter as a shortcut for accepting completions would be a nicer default too.

### Steps to reproduce

I think it's straight-forward from the description above.

### Minimal reproduction project (MRP)

It's a shader editor issue. No MRP needed I guess.

**Comment by jsjtxietian** [comment]
> 1. When the completion list shows, pressing Esc makes the cursor disappear. It seems the editor looses focus and I have to click on the editor to restore the cursor and hide the completion list.

Did not reproduce in Godot v4.3.dev (907db8eeb) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4601) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)



> 2\. It also suggests keywords in places where it's common to put a new line, for example, after a comma in an array initialization.

Can you share the related code that triggers the situation? I tested locally in most cases the problem didn't occur, but I did see it one time but I did not manage to reproduce it :( I suspect that in some corner cases the suggestion will be to vague.

**Comment by berarma** [comment]
It seems that issue 1 was due to a editor plugin I had enabled. And I can't no longer reproduce issue 2. I'm not sure what happened. Sorry. I'll close in embarrassment to avoid tracker pollution.
