### ISSUE TITLE
Menu- and OptionButton item text strings don't get included in POT generation

### ISSUE THREAD

**Issue by Kiisu-Master** [godotengine/godot#88017]
### Tested versions

Probably reproducible in all Godot version , tested 4.0.3 , 4.2.2rc
Also looked at 3.5 and found the old scene file format that the POT generator is trying to use, bot no POT generator.

### System information

Windows 10

### Issue description

The POT generator is not including item texts from `MenuButton` or `OptionButton`, because its expecting an old scene file format. It's trying to find a `items` property with an array of items, which doesn't exist since 4.0. 

Old scene format POT gen is built for:
```gd
[node name="MenuButton" type="MenuButton" parent="."]
margin_right = 147.0
margin_bottom = 20.0
items = [ "Hello world!", null, 0, false, false, 0, 0, null, "", false ]
```
New scene format that POT gen doesn't know about:
```gd
[node name="MenuButton" type="MenuButton" parent="."]
layout_mode = 0
offset_right = 8.0
offset_bottom = 8.0
item_count = 1
popup/item_0/text = "Hello world!"
popup/item_0/id = 0
```
The solution would be to include properties that match the pattern "popup/*/text".

Relevant source code:
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L149
Note: Simply putting this in a check `if (!property_name.match("popup/*/text"))` fixes the problem, because it will find the property as a string value.
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L95-L97
https://github.com/godotengine/godot/blob/d3352813ea44447bfbf135efdec23acc4d1d3f89/editor/plugins/packed_scene_translation_parser_plugin.cpp#L111-L119

### Steps to reproduce

Make a MenuButton or OptionButton with items, include the scene in POT generation and generate POT.
-> The generated POT will not include item texts.

### Minimal reproduction project (MRP)

Not really needed but here is a simple MRP:
[MenuButton POT MRP.zip](https://github.com/godotengine/godot/files/14180566/MenuButton.POT.MRP.zip)

**Comment by eddex** [comment]
Just stumbled upon this problem when creating POT files for my settings menu. Great to see that this will be fixed in the next release! 🎉
