### ISSUE TITLE
Localization List Alphabetized

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#8802]
Is there any way we can get the language list in localization remapping alphabetized?  Currently it seems to be a very long list of randomly listed languages.  It would be easier to navigate in order.

Alternatively, and probably more complicated, show only the languages used in the other translation tab.  Though not sure how feasible that is.

**Comment by AndrewPomorski** [comment]
This seems like a fairly simple fix, I could take care of that.

**Comment by Gramps** [comment]
That would be awesome!

**Comment by AndrewPomorski** [comment]
I will have a look this evening :)

**Comment by Gramps** [comment]
That is terrific, thank you, sir!

**Comment by akien-mga** [comment]
It seems to be fixed already (first entry in `en`, then it's alphabetical).
