### ISSUE TITLE
Forced to reimport compute shader .glsl file after every change for the engine to pick up on the new shader code

### ISSUE THREAD

**Issue by blubbers122** [godotengine/godot#88036]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (nvidia; 535.154.05) - Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 Threads)

### Issue description

When working on compute shaders the engine will only notice saved changes after reimporting the .glsl file, either through right-clicking the file and clicking reload or reloading the entire project.

### Steps to reproduce

* create a project with basic compute shader
* make a valid change to the shader code in the .glsl file
* save
* try running the project again to see the project is still using the old version of the shader 

### Minimal reproduction project (MRP)

[compute_shader_reload_bug.zip](https://github.com/godotengine/godot/files/14186307/compute_shader_reload_bug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/72281.
