### ISSUE TITLE
Invalid target platform error for Android while building Godot from sources

### ISSUE THREAD

**Issue by AlekseyKapustyanenko** [godotengine/godot#88030]
### Tested versions

- Reproducible on lates main branch.

### System information

Windows 10.

### Issue description

I am trying to build android export templates from sources using this instruction: [instruction](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html).
I go throgh all steps in this instruction but when I enter this command: `scons platform=android target=template_release arch=arm32` or this command: `scons platform=android target=template_release arch=arm64 generate_apk=yes` I get such error:
```
scons: Reading SConscript files ...
Invalid target platform "android".
The following platforms were detected:

        windows

Please run SCons again and select a valid platform: platform=<string>
```

### Steps to reproduce

Go throgh all steps in this instruction: [instruction](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_android.html):
- Pull Godot repo
- Install Python
- Install SCons
- Install Android SDK
- Install JDK
- Set `ANDROID_HOME` env var
- Install the necessary SDK components
- execute this command: `scons platform=android target=template_release arch=arm32`
- execute this command: `scons platform=android target=template_release arch=arm64 generate_apk=yes`

Expected result:
The resulting APK should be located at bin/android_debug.apk

Actual result:
Invalid target platform "android" error

### Minimal reproduction project (MRP)

(empty)

**Comment by Calinou** [comment]
> Set ANDROID_HOME env var

Did you set the environment variable on your user or system? If it's ser on your user, you need to close and reopen the terminal for changes to apply. If it's set on your system, you need to reboot for changes to apply.

**Comment by alexeykap** [comment]
> > * Set `ANDROID_HOME` env var
> 
> Did you set the environment variable on your user or system? If it's ser on your user, you need to close and reopen the terminal for changes to apply. If it's set on your system, you need to reboot for changes to apply.

Reboot helped me. But now I get another error:

**Comment by AlekseyKapustyanenko** [comment]
Also I tried to do all these steps on stable branch (4.2.1-stable tag). I executed these commands:

**Comment by AlekseyKapustyanenko** [comment]
It seems this https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html guide was updated today. And following new information I finally have built *.apk. Problem solved!

**Comment by AlekseyKapustyanenko** [comment]
It seems this https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_android.html guide was updated today. And following new information I finally have built *.apk. Problem solved!

P.S. Thank Godot Team for great support and so fast help!
