### ISSUE TITLE
Godot Window always steals focus on GNOME with PaperWM

### ISSUE THREAD

**Issue by camtauxe** [godotengine/godot#88037]
### Tested versions

v4.2.1.stable.nixpkgs [b09f793f5]

### System information

NixOS 23.11 - Godot v4.2.1 - GNOME 45.3 (X11) - PaperWM 45.6.0

### Issue description

In the GNOME Desktop Environment with the PaperWM extension, the Godot Editor window always steals focus as soon as the user navigates to another window. This slides the view back to the Godot window, and makes it impossible to use any other window in the same workspace.

This bug was described by other users in the comments on #74378, and experienced by myself. That issue only refers to Xfce 4 and the [latest comment](https://github.com/godotengine/godot/issues/74378#issuecomment-1904690929) implies that it's been fixed. But the issue with GNOME + PaperWM remains, so I have created a new issue for it here.

### Steps to reproduce

- Start the Godot Editor and open a project
- Open another window in the same workspace
- Navigate to the other window (`<Super>+.`)
- PaperWM will immediately slide back to focus the Godot Editor

### Minimal reproduction project (MRP)

Video evidence:

https://github.com/godotengine/godot/assets/19434374/76d28eb1-5d85-4406-aa86-96b91885e755

**Comment by Calinou** [comment]
> This bug was described by other users in the comments on https://github.com/godotengine/godot/issues/74378, and experienced by myself. That issue only refers to Xfce 4 and the https://github.com/godotengine/godot/issues/74378#issuecomment-1904690929 implies that it's been fixed.

These commits haven't been cherry-picked to the `4.2` branch yet (and no 4.2.2 release has been made yet either), so you need to build `master` from source to benefit from these fixes.

**Comment by camtauxe** [comment]
@Calinou Thank you for the quick response!

My mistake then, I misread what that comment was implying. I rebuilt from master ([d335281](https://github.com/godotengine/godot/commit/d3352813ea44447bfbf135efdec23acc4d1d3f89)) and I can confirm that it now works correctly in my GNOME/PaperWM setup. Thanks!
