### ISSUE TITLE
Project settings - Display - Window: Initial Position Type, Initial Position and Initial Screen don't work.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#88038]
### Tested versions

4.2.1

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

None of the options work, the game window when playing in editor is always center on the screen where the Editor is open.

### Steps to reproduce

Try changing the options and pressing the play button to see.
If you want to try the Initial Position don't forget that you need to switch Initial Position Type to Absolute too.

### Minimal reproduction project (MRP)

Not needed.

**Comment by Calinou** [comment]
This is because the window position when running the project from the editor is defined in the Editor Settings instead (**Run > Window Placement** section). The project settings for positioning only affect the exported project.

**Comment by Calinou** [comment]
Reopening, as this should be documented in the class reference.
