### ISSUE TITLE
No way to switch back to the editor window while the game is running

### ISSUE THREAD

**Issue by KUNGERMOoN** [godotengine/godot#88039]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Android - Vulkan (Mobile) - integrated Mali-G78 -  (8 Threads)

### Issue description

In the Android port of the editor, if you run the game, the game window will fill the entire screen, and the only way (I know) to open back the editor window is by fully closing the game. This creates a few problems:
- It's impossible to see the remote scene view
- It's impossible to use breakpoints. If your code hits one, the game freezes (as intended), but you can't step over or continue the execution since you don't have access to the debug panel from the editor window
- If a faulty code causes the game to freeze, it's impossible to just simply close the game window; trying to use the Android's back button (or a gesture) does nothing, and the only thing one can do about it is to close and restart the editor app altogether.

### Steps to reproduce

Running any Godot project in the android editor and failing to go back to the editor window without fully stopping the game

### Minimal reproduction project (MRP)

Any Godot project running in the android editor

**Comment by Calinou** [comment]
> If a faulty code causes the game to freeze, it's impossible to just simply close the game window; trying to use the Android's back button (or a gesture) does nothing, and the only thing one can do about it is to close and restart the editor app altogether.

This one is being tracked in https://github.com/godotengine/godot/issues/77966.
