### ISSUE TITLE
Impossible to import font with path containing accented characters

### ISSUE THREAD

**Issue by Erawpalassalg** [godotengine/godot#8804]
Happened on Windows 7, Godot 2.1.3 (stable)

Couldn't import a font with a path containing accented characters (folder or the font name itself). Preview did not work and the window poped a "Couldn't save font." message when I tried to import the font.

Everything worked fine when I moved the font elsewhere, where it would not have a path with accented characters.

**Comment by bojidar-bg** [comment]
Might be related to #7309

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Erawpalassalg** [comment]
Hi,
Sorry for the delay.

Everything seems to work fine now, accented character or not :1st_place_medal: 

**This issue is not relevant anymore** (tested on Godot 3.0)

**Comment by bojidar-bg** [comment]
Yay, closing as fixed then.
