### ISSUE TITLE
Autocomplete suggestion doesn't suggest quotes for nested nodes with names that start with numeric value

### ISSUE THREAD

**Issue by KristianWahlroos** [godotengine/godot#88059]
### Tested versions

Reproducible in v3.5.3 and v4.2.beta5.official

### System information

Windows 10

### Issue description

Autocomplete suggestion doesn't suggest to add quotes for nested nodes, which start with numerical value. Going through with the incomplete suggestion will lead to an error.

Autocomplete knows how to suggest quotes for unnested nodes, that start with numerical value, but it would be nice to extend this functionality to work with nested nodes as well.

Example of unnested nodes working as intended:
![kuva](https://github.com/godotengine/godot/assets/11396126/a532efcc-3311-4249-8613-48ca54ff6969)

### Steps to reproduce

For example having structure like suggested on the image will lead to an error:
![kuva](https://github.com/godotengine/godot/assets/11396126/2ab9bcef-d0b3-4f67-b7a5-c04989230734)

Error: "Parse error: Invalid numeric constant: 0x"

### Minimal reproduction project (MRP)

[BugTest.zip](https://github.com/godotengine/godot/files/14194916/BugTest.zip)

**Comment by AThousandShips** [comment]
Can you try with 4.2.1? You're on an old beta version for the 4.x branch, would be good to ensure it still occurs in that branch

**Comment by KristianWahlroos** [comment]
I checked. It happens both in newest v3.x stable and in v4.2.1.
