### ISSUE TITLE
Clicking node's script icon does not open its script tab

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88062]
### Tested versions

4.3 36e943b
Does not happen in dev2.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you click a script icon in the scene tree, it will sometimes open the script editor and show a wrong script. This seems to only happen when clicking it while script editor is not currently active. Also if the script is already opened, it will be wrongly selected.

https://github.com/godotengine/godot/assets/2223172/2a5b1c27-cc9d-4aa7-91f8-13fc0bb53b03

EDIT:
Seems like it only happens with built-in scripts.

EDIT2:
Or not? But with file scripts is less common.

### Steps to reproduce

Open the MRP and in Forest scene click the Lake script in the scene tree. Make sure the script is not currently selected in the script editor and the script editor itself is not active.

### Minimal reproduction project (MRP)

[Scriptest.zip](https://github.com/godotengine/godot/files/14195243/Scriptest.zip)

**Comment by AeioMuch** [comment]
I am unable to reproduce this on 81f3d43

**Comment by KoBeWi** [comment]
Likely fixed by #88288
