### ISSUE TITLE
Text doesn't always fit in buttons and labels when using custom display scale

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#88066]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

UI text randomly cuts off at some custom display scale values

All good at **1.5**:

<img width="421" alt="image" src="https://github.com/godotengine/godot/assets/60579014/c85bcf50-7c06-4198-90b1-67f100eb310a">

> <img width="304" alt="image" src="https://github.com/godotengine/godot/assets/60579014/afc40118-840a-4a6d-a10c-73bf35e92305">
> <img width="197" alt="image" src="https://github.com/godotengine/godot/assets/60579014/963a9d96-8927-4700-b8ca-a96e306f9fd0">

Missing letters at **1.65**:

<img width="418" alt="image" src="https://github.com/godotengine/godot/assets/60579014/00e7c578-3fc1-4046-9a8e-be4c60f23b1b">

> <img width="349" alt="image" src="https://github.com/godotengine/godot/assets/60579014/a9dffa5e-ddb0-471b-80b4-9a626313ff0e">
> <img width="244" alt="image" src="https://github.com/godotengine/godot/assets/60579014/9f066f2a-96d3-4f31-afbf-ff086ffa1a73">

### Steps to reproduce

Try setting display scale to a custom value, like **1.65**

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
Should be already fixed https://github.com/godotengine/godot/pull/87335

**Comment by passivestar** [comment]
my bad, didn't check on master. fixed in 4.3
