### ISSUE TITLE
GLES3 Android Performances/Quality regressions of ~50% from Godot 3.5.3 to Godot 4.2.1

### ISSUE THREAD

**Issue by joined72** [godotengine/godot#88070]
### Tested versions

- Reproducible on Godot 4.2.1
- Test Environment: Android 8.0.0+

### System information

Android 8+

### Issue description

The ["light and shadow"](https://github.com/godotengine/godot-demo-projects/tree/master/2d/lights_and_shadows) project of the [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) repository runs fine if compiled with **Godot 3.5.3** and has many Performances (about **50% less performance**) and Quality (**full dark lights**) issues compiled in **Godot 4.2.1**.

**NOTE:** of course I have download the project for **Godot 3.x** and to build for **Godot 4.x** I have full converted and tested it on Desktop, and works fine, isn't a conversion issue, just to be clear. Anyway I have attached both Godot 3.x and Godot 4.x Test Projects.

I have tested **both projects** on 3 different devices...

1. Huawei Honor 9 Lite (GPU: Mali T830)
2. Xiaomi Redmi 10 (GPU: Mali G52)
3. Xiaomi Redmi 12 (GPU: Adreno 610)
 
Following you will find details and screenshots of all my test grouped for devices...

**Xiaomi Redmi 12 (GPU: Adreno 610)**

**Godot 3.5.3 - FPS: 28**
![image](https://github.com/godotengine/godot/assets/19651914/66a23168-e30c-4748-af47-a1db9772811d)

**Godot 4.2.1 - FPS: 13**
![image](https://github.com/godotengine/godot/assets/19651914/445f1670-47d8-4ff0-9a03-23cae9e609f2)

------------------------------------------------------------------------------------------------------------------------------------------------------------

**Xiaomi Redmi 10 (GPU: Mali G52)**

**Godot 3.5.3 - FPS: 37**
![image](https://github.com/godotengine/godot/assets/19651914/29e2ed1c-fcfb-42c7-8dd2-9176a885090f)

**Godot 4.2.1 - FPS: 25 - Dark Lights**
![image](https://github.com/godotengine/godot/assets/19651914/b7235e0a-978a-427c-8bb6-5be573f70997)

------------------------------------------------------------------------------------------------------------------------------------------------------------

**Huawei Honor 9 Lite (GPU: Mali T830)**

**Godot 3.5.3 - FPS: 25**
![image](https://github.com/godotengine/godot/assets/19651914/42dea795-5f8b-496a-9643-488ae151d5e3)

**Godot 4.2.1 - FPS: 10 - Dark Lights**
![image](https://github.com/godotengine/godot/assets/19651914/9db59f0a-5253-42d1-8053-d71e6602de89)

------------------------------------------------------------------------------------------------------------------------------------------------------------

### Steps to reproduce

I have downloaded the ["light and shadow"](https://github.com/godotengine/godot-demo-projects/tree/master/2d/lights_and_shadows) project of the [godot-demo-projects](https://github.com/godotengine/godot-demo-projects) repository for Godot 3.5.3 and copied and converted for Godot 4.x (just to be sure to use same settings and code).

### Minimal reproduction project (MRP)

[Godot 3.5.3 Test Project](https://github.com/godotengine/godot/files/14199508/Godot.3.-.lights_and_shadows.zip)
[Godot 4.2.1 Test Project](https://github.com/godotengine/godot/files/14199510/Godot.4.-.lights_and_shadows.zip)

**Comment by AThousandShips** [comment]
Can you please compare performance with equivalent conditions? All the 4.x screenshots are far further out, just to give a fair comparison

**Comment by AThousandShips** [comment]
Note that Mali T830 is a 8 year old gpu, I'm not sure it can be considered current enough to consider

The general performance can be expected to drop as all renderers for 4.x are more intensive than those in 3.x

Further the performance to begin with in 3.x isn't good so I'm not sure what should be expected other than this, with 25 FPS on a minimal demo project in 3.x I don't think it's unexpected to not handle 4.x

**Comment by joined72** [comment]
@AThousandShips
> Can you please compare performance with equivalent conditions? All the 4.x screenshots are far further out, just to give a fair comparison

There was no resizing, the images are ALL full screen screenshots.

>Further the performance to begin with in 3.x isn't good so I'm not sure what should be expected other than this, with 25 FPS on a minimal demo project in 3.x I don't think it's unexpected to not handle 4.x

And the dark-lights?

**Comment by AThousandShips** [comment]
Please don't tag me when it's just me here :)

The screenshots are very clearly not the same zoom level so they're not comparable, this might be a difference in the two demo projects, but that alone shows also that these are not 1 to 1 comparisons, please attempt to make the examples as identical as possible

The dark lights are part of the same issue likely

**Comment by Calinou** [comment]
AThousandShips is referring to the camera zoom differing between the 3.x and 4.x demos, as opposed to screenshot resolution. Viewport resolution seems identical across 3.x and 4.x so that part is fine.

**Comment by AThousandShips** [comment]
I'm not sure how this is different from your earlier report though:
* https://github.com/godotengine/godot/issues/86112

**Comment by joined72** [comment]
> Also do these devices not fail for 4.x, I thought that's what:
> 
> * [Fix Compatibility Rendering (GLES3) on old and low budget devices. #87352](https://github.com/godotengine/godot/pull/87352)
> 
> Was for, is this the results of that PR applied?

No I haven't applied any fix, just standard templates. Also because I discover that on Adreno 505 the light and shadow demo crashed the device! :(

Until yesterday I thought that it was enough to just ban devices from the Adreno 3XX family, but today I found other bugs in different devices and NOT only from the Adreno family but also Mali, so I don't understand how other Android game developers don't receive reports of bugs when I found so many flaws just by trying the demos. 
I understand that some devices are 8 years old, but if we ban all older devices we will end up cutting the potential customer market in half. 
I don't hide my frustration, with Godot 3.x and GLES2 everything worked perfectly and excluding the Adreno 3XX Family, GLES3 also worked very well. 
I would really like to switch to Godot 4, but I definitely can't afford to ban so many devices on the Google Play Store or receive negative reviews for poor quality (the dark lights are really bad). 
This insistence on pestering the developers of my favorite Engine is just a cry for help, and I still don't understand all the other developers of 2D games for Android how they solve this.

**Comment by AThousandShips** [comment]
> I don't hide my frustration

Please consider the [code of conduct](https://godotengine.org/code-of-conduct/), this is not a place to vent frustration

The fact is simply that there's no guarantee we can support such an old device, it doesn't matter if they are common, and I highly doubt half the potential market has devices eight years or older

You are talking about flaws, how do you know these are faults in the engine? There's at least one case in the different devices where they fail to conform to the basic GLSL standard

If you can find some issue in how we initialize for these devices, then that's great, but otherwise it does seem like these devices simply are not sufficient to work, and that's sad, but not something we can necessarily fix

Godot 4.x is higher end than 3.x, and isn't intended to target the lowest level targets, because that's essentially impossible to do if we want to be able to use a lot of features

The same applies to desktop, you can't expect 4.x to run on very old or very low end desktop hardware either

**Comment by joined72** [comment]
> Godot 4.x is higher end than 3.x, and isn't intended to target the lowest level targets, because that's essentially impossible to do if we want to be able to use a lot of features
> 
> The same applies to desktop, you can't expect 4.x to run on very old or very low end desktop hardware either

OK, I understand, thanks you.

**Comment by AThousandShips** [comment]
Some pointers here

Again if we can establish that there's some bug in how we initialize for these targets then that's a bug to be fixed

But again even for this very simple demo project the oldest devices runs at a mere 25 fps, and another at 28 fps, this device isn't necessarily guaranteed to run any game in 3.x well to begin with, as the demo here isn't exactly a stress test, compare these demos on new hardware and see

**Comment by arkology** [comment]
> very simple demo project

As far as I know lights and shadows was always expensive (that's why most of 2d games for mobile don't use lights), so this actually could be called stress test.

**Comment by Alex2782** [comment]
on `Samsung Tab A6 (2016) SM -T580 / ARM Mali, Android 8.1`
... I found that it works with `Vulkan` Renderer, but with `OpenGL ES` not properly (black lights).  
I put it on my TODO list, first check what has changed there. (maybe in 1 to 2 weeks)

With 3 lights, achieving a full 25 FPS is a good value, with only 1 light source maybe even 60+ fps is possible.

**Comment by AThousandShips** [comment]
Then it might be the initialization for gles that's broken, worth investigating

*But* it could also be that the GLES implementation on this hardware, or drivers, is bad, but not the Vulkan

**Comment by lawnjelly** [comment]
In defence of 4.x, the GLES renderers in 3.x have had an extra 5 years+ of development, bug testing, fixes and most importantly, field testing. Working around differences + hardware / driver bugs on the huge array of mobile devices unfortunately takes time (and of course would be helped by more contributors in this area, this is mostly clay and he has a *lot* on his plate currently).

There are also different trade-offs used in terms of framebuffers, lighting etc, GLES3 in 3.x is afaik totally different to GLES3 in 4.x. Even blank screens are likely to give different FPS.

That said the MRPs might be good for comparisons. Usually it is a good idea to isolate particular things for testing, to identify bugs and performance differences.

Also remember there is no problem with staying on 3.x for low end targets, especially 2D. It is very stable, still being actively developed, and certain features still work better on 3.x (conversely some are only available in 4.x).
