### ISSUE TITLE
Godot crash whenever press save scene (version v4.2.1)

### ISSUE THREAD

**Issue by asianfanboi** [godotengine/godot#88077]
### Tested versions

Godot_v4.2.1

### System information

Window 10 - Godot_v4.2.1-stable_win64.exe - CPU AMD Ryzen 5 5600X - GPU NVIDIA GeForce RTX 3070

### Issue description

Godot crash whenever I press save scene.

![Screenshot (465)](https://github.com/godotengine/godot/assets/159343386/88b63e51-c14c-475a-8663-f6894972aa81)

### Steps to reproduce

![Screenshot (466)](https://github.com/godotengine/godot/assets/159343386/4e282049-e392-453e-8b46-79f9797f53cb)

### Minimal reproduction project (MRP)

N/A

**Comment by RealMadvicius** [comment]
I have tried on Window 10 - Godot_v4.2.1-stable_win64.exe to make a new empty project, then pressed "save" and I couldnt reproduce the crash. It saved perfectly fine. In my project everything is set as default and uses Vulkan API aswell.
Maybe it is more a problem with vulkan drivers not installed on your PC ?
I do have a RTX 2080Ti with latest nvidia drivers. Maybe you are missing the Vulkan runtime?

**Comment by asianfanboi** [comment]
@RealMadvicius Uhhh I have fixed it sometimes later I after posted this (then I kinda forgot about this post sorry). I dont know what specifically fix it but I installed the newer NVIDIA driver > restart the computer > turn off msi afterburner overlay. After that it work just fine.
