### ISSUE TITLE
ColorPicker eyedropper in desktop platforms is inaccurate (but it's accurate in the web export)

### ISSUE THREAD

**Issue by starblinky** [godotengine/godot#88092]
### Tested versions

Godot 4.2.1

Web / Browser version tested on Mac and Windows
Godot Desktop on Mac

### System information

Mac OS Sonoma 14.2.1 (23C71)

### Issue description

Create a sprite. Click modulate. Use eyedropper on same color in Browser Godot and Desktop Godot. Desktop Godot produces wrong result.

I have created this color swapping shader and it only works in Godot Web because of this bug.

```
shader_type canvas_item;
uniform vec4 fromColor : source_color;
uniform vec4 toColor : source_color;

void fragment() {
	vec4 tex = texture(TEXTURE, UV);
	if (tex == fromColor){
		tex = toColor;
	}
	COLOR = tex;
}
```

4.2.1 tested

Godot WEB / Browser
<img width="625" alt="Screenshot 2024-02-08 at 12 35 36 AM" src="https://github.com/godotengine/godot/assets/51274080/3873a65c-1138-4d8c-935b-2d7f4ef8c1df">

Godot DESKTOP
<img width="950" alt="godot desktop" src="https://github.com/godotengine/godot/assets/51274080/af199033-8b75-4154-992a-fdb9181558cd">

### Steps to reproduce

Create a sprite. Click modulate. Use eyedropper on same color in Browser Godot and Desktop Godot. Desktop Godot produces wrong result.

### Minimal reproduction project (MRP)

Just open Godot.

**Comment by Calinou** [comment]
There's likely a sRGB-to-linear conversion step missing somewhere.

Which rendering method is your project using? Is the **HDR 2D** project setting enabled?

PS: Don't rely on exact floating-point comparisons for colors in shader code, as floating-point precision errors *will* throw this off. Instead, perform approximate comparison using epsilon checks: https://github.com/godotengine/godot-proposals/issues/6870

**Comment by starblinky** [comment]
HDR 2D wasn't enabled. I probably shouldn't have tried enabling it in my main project though.. It just corrupted my 2 main scenes just now trying to enable it. So thats great. 

Thanks for the tip though.

**Comment by bruvzg** [comment]
Are you using HDR display and HDR enabled in the OS settings? I can reproduce it on HDR display on macOS, but not on SDR display.

> Godot Desktop on Mac

I assume the desktop version was tested only on macOS, or is it also reproducible on Windows.
