### ISSUE TITLE
Unable to use GDExtension - unable to import .gdextension file

### ISSUE THREAD

**Issue by IAmTraffic** [godotengine/godot#88090]
### Tested versions

4.1 stable
4.2 stable
4.2.1 stable

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I've been following the [GDExtension Tutorial](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html) provided by the documentation.

All was going well, but the gdexample.gdextension file appears to be causing problems.

When I load the project, the GDExample node is not available, and I get the following errors:
`Can't resolve symbol example_library_init, error: "Error 127: The specified procedure could not be found.".`

`core/extension/gdextension.cpp:736 - GDExtension entry point 'example_library_init' not found in library C:/Users/Ivy/Documents/Programming/Godot/godot_cpp_extension_example/demo/bin/~libgdexample.windows.template_debug.x86_64.dll`

`Failed loading resource: res://bin/gdexample.gdextension. Make sure resources have been imported by opening the project in the editor at least once.`

From looking around at other people who have had similar issues in the past, this appears to be an issue with the godot-cpp branch and the godot executable being of incompatible versions. However, I don't think that this is the case here. As mentioned in my system information, I'm running Godot 4.2 stable. And, checking my .gitmodules file in the project, I have the 4.2 branch of the repo.

Since it appears to have always been a versioning issue for people who have previously had these issues, I'm unsure of what to do.

### Steps to reproduce

Opening the attached MRP yields the error I am experiencing. However, as mentioned below, the godot-cpp repo would need to be cloned by you on your machine, as that folder is too big to upload here.

### Minimal reproduction project (MRP)

Unable to upload in its totality due to the size of the godot-cpp clone, but the attached .zip file would otherwise contain a cloned folder of the 4.2 branch of the godot-cpp repo. I also had to delete my .git folder for similar reasons, but the .gitmodules file should be able to confirm the repo branch I cloned.

[godot_cpp_extension_example - mrp.zip](https://github.com/godotengine/godot/files/14205443/godot_cpp_extension_example.-.mrp.zip)

**Comment by ksmit799** [comment]
Your missing the `example_library_init` export in your `register_types.cpp` file. Because of this, Godot has no way of calling into your library. You need to add something like this (from the docs):

```cpp
extern "C" {
// Initialization.
GDExtensionBool GDE_EXPORT example_library_init(GDExtensionInterfaceGetProcAddress p_get_proc_address, const GDExtensionClassLibraryPtr p_library, GDExtensionInitialization *r_initialization) {
	godot::GDExtensionBinding::InitObject init_obj(p_get_proc_address, p_library, r_initialization);

	init_obj.register_initializer(initialize_example_module);
	init_obj.register_terminator(uninitialize_example_module);
	init_obj.set_minimum_library_initialization_level(MODULE_INITIALIZATION_LEVEL_SCENE);

	return init_obj.init();
}
}
```

**Comment by IAmTraffic** [comment]
Welp, I am a fool!! That was totally it. I checked and double checked so many things, but not that! Kicking myself. Thanks!
