### ISSUE TITLE
Function "decompose_polygon_in_convex"  has wrong behavior.

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#88093]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Win 11,CPU amd5600,GPU 5700xt,gl rendering mode

### Issue description

When use "decompose_polygon_in_convex" function to decompose a CollisionPolygon2D, the result owns a shape that likes a line.

### Steps to reproduce

1.Creat a CollisionPolygon2D with data `[(-3, 15), (8, -5), (28, 0), (36, 1), (23, 28), (23, 28)]`.
2. Call `Geometry2D.decompose_polygon_in_convex(collision_polygon_2d.polygon)`
3. The result is `[[(28, 0), (36, 1), (23, 28)], [(23, 28), (-3, 15), (8, -5), (28, 0)], [(23, 28), (28, 0), (23, 28)]]`
4. It should not have the `[(23, 28), (28, 0), (23, 28)]` result.

### Minimal reproduction project (MRP)

NAN

**Comment by AThousandShips** [comment]
Does it work if the input polygon is valid, like so: `[(-3, 15), (8, -5), (28, 0), (36, 1), (23, 28)]`

It should handle these but duplicate points aren't necessarily supported as they don't make a valid polygon

**Comment by AThousandShips** [comment]
Duplicate of https://github.com/godotengine/godot/issues/27197
