### ISSUE TITLE
Running `--doctool` results in error message: `ERROR: unimplemented base type encountered in renderer scene cull`

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#88096]
- *Related to https://github.com/godotengine/godot/issues/64720.*

### Tested versions

- Reproducible in: 4.3.dev cae759949-https://github.com/godotengine/godot/commit/a0106607e889fb0ed4ab5bf84a4b2707c3ac5598, 4.3.dev3
- Not reproducible in: 4.2.1.stable, 4.3.dev2

### System information

Godot v4.3.dev (cae759949) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Running `--doctool` results in this error message:

```
ERROR: unimplemented base type encountered in renderer scene cull
   at: instance_set_base (./servers/rendering/renderer_scene_cull.cpp:636)
```

Despite this, `--doctool` generates correct output.

I can look at bisecting this if needed.

### Steps to reproduce

Run a Godot editor binary with `--doctool` command line argument.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Seems the instance is incorrectly initialized:
https://github.com/godotengine/godot/blob/a0106607e889fb0ed4ab5bf84a4b2707c3ac5598/servers/rendering/renderer_scene_cull.cpp#L623-L638

Unsure if this is specifically due to headless and if it might be something to solve in the dummy setup
