### ISSUE TITLE
Animation function tracks not giving warnings/errors about incorrect paths.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#881]
_Edit:_ Updated link: http://www.godotengine.org/topics/5146

![](http://imgbin.org/images/20893.png)

The entire issue with the above had been that the path for the function track to call the UpdateCreditsRoll function had been incorrect (track should have been looking in ".." as opposed to "."). But Godot, instead of giving a warning or (preferrably) an error about this, silently fails. It also silently fails if the function name given is incorrect.

**Comment by akien-mga** [comment]
What's the status on this issue? Has it been fixed together with the animation editor improvements?

**Comment by vnen** [comment]
There should be some warning when the function called by the animation does not exist, instead of failing silently as still currently happens. This would be useful for debugging.

**Comment by akien-mga** [comment]
When should the error be raised? When defining the method to call, or when actually playing the animation?

**Comment by vnen** [comment]
If it can be raised when defining the method, that would be more user-friendly.

**Comment by akien-mga** [comment]
> If it can be raised when defining the method, that would be more user-friendly.

Actually I wonder, as in theory some users might want to set up their animation before-hand even when the corresponding methods haven't been written yet. The best solution would maybe be to display a visual warning next to the track if the corresponding method is not defined and/or does not accept the number of parameters that were passed + a verbose error on runtime if it still hasn't been corrected when playing the animation.

The second part is likely the easiest to implement, but I'll look into both :)

**Comment by bojidar-bg** [comment]
Given that we have editor-time warnings (called configuration warnings), maybe we might make use of them?

**Comment by akien-mga** [comment]
Still a junior job that should be easy to implement (if not addressed already in the master branch).

**Comment by dherring** [comment]
This issue still exists (custom 3.0 rc build from commit 6a4521d).

**Comment by Sslaxx** [comment]
Does #20259 fix this?

**Comment by akien-mga** [comment]
I think so yes.
