### ISSUE TITLE
Scene tree steals focus from Inspector when pressing Enter on a focused SpinSlider

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#88102]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

So basically when you press Enter on a focused Inspector element, you get value popups for both Inspector element and whatever is the selected node in the Scene dock. And the latter gets the input:

https://github.com/godotengine/godot/assets/60579014/e8075793-0ac8-4c23-924d-35800c56c70f

### Steps to reproduce

1. Click on an input in the Inspector

2. Press Escape to hide the input popup.
The SpinSlider control itself still has the focus. You can use arrow buttons to navigate to other SpinSliders

3. Press Enter to edit
You'll get 2 different input popups in 2 different parts of the editor UI, both of which look visually focused, and the input goes into Scene tree's one

### Minimal reproduction project (MRP)

N/A

**Comment by ajreckof** [comment]
this is not restricted to spin slider whatever is focused pressing enter while a node is selected will always result in renaming the node

**Comment by ryevdokimov** [comment]
Unable to reproduce.

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

**Comment by ajreckof** [comment]
Strange then this might be a Mac or Unix only bug as I can reproduce on my mac

**Comment by akien-mga** [comment]
This is macOS specific due to the custom hotkeys used there, as pointed out by @vnen on RC:

> probably only affects macOS only because Enter is the key to rename nodes. In other platforms it would be F2, which you would not really press to do something else
