### ISSUE TITLE
Godot v4.3.dev3 - android export templates build.gradle validateJavaVersion too strict

### ISSUE THREAD

**Issue by iwangxiaodong** [godotengine/godot#88116]
### Tested versions

v4.3.dev3.mono.official [36e943b6b]

### System information

Godot v4.3.dev3.mono - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.4617) - 12th Gen Intel(R) Core(TM) i5-12490F (12 Threads)

### Issue description

android export templates build.gradle validateJavaVersion too strict:

https://github.com/godotengine/godot/blob/41564aaf7708b0bf594f745dd2448a54dd687cc5/platform/android/java/app/build.gradle#L238-L242

Hope to change it to:
  if (JavaVersion.current() < versions.javaVersion || JavaVersion.current() > JavaVersion.VERSION_20) { /*...*/ }

 Java+Gradle Compatibility - https://docs.gradle.org/current/userguide/compatibility.html#java

Tested: Java 20 + Gradle 8.2.

### Steps to reproduce

none.

### Minimal reproduction project (MRP)

none.

**Comment by m4gr3d** [comment]
Not sure if I agree with relaxing the version check. Version 17 is the current LTS version [officially supported by the Android SDK](https://developer.android.com/build/releases/gradle-plugin#compatibility). 
Until they enable support for higher Java versions I don't see the benefit in doing so ourselves given it'll likely to inconvenience more users (with random compatibility issues) then it's likely to benefit.

In addition this shouldn't be an issue for users with multiple Java sdks installed given we added the ability to explicitly specify the path to Java SDK v17.
