### ISSUE TITLE
Local scope variable generates error 'The variable "a"  was used but never assigned a value.'

### ISSUE THREAD

**Issue by BriarSMC** [godotengine/godot#88117]
### Tested versions

Godot v4.2.1.stable 
Godot v4.2.stable 

Does not compile in V3.5.3

### System information

- Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Mobile) - integrated Intel(R) HD Graphics 530 (SKL GT2) () - Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 Threads)

### Issue description

The following generates the error:
```
extends Node
func _ready():
	var a: Array[int]
	a.resize(16)
	a.fill(0)
	for i in range(16):
		a[i] = i*2
	print(a)
```

However, moving the array declaration out of the local scope  generates no errors:

```
extends Node
var a: Array[int]
func _ready():
	a.resize(16)
	a.fill(0)
	for i in range(16):
		a[i] = i*2
	print(a)
```

### Steps to reproduce

Write single node app with the above code and run  both versions.

### Minimal reproduction project (MRP)

[array_fill_bug.zip](https://github.com/godotengine/godot/files/14214692/array_fill_bug.zip)

**Comment by capnm** [comment]
It's not an error, just one of the many superfluous warnings ;),
IIRC there was a bug report about it somewhere.

You can disable it with
```go
@warning_ignore("unassigned_variable")
var a: Array[int]
```

or in the project settings

![image](https://github.com/godotengine/godot/assets/4047289/80bd7287-2319-4390-b24c-b4eb68deadfb)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/85796.

**Comment by Mickeon** [comment]
In a nutshell, the broader issue here is that methods that directly operate on the declared **Variant** do not count towards the variable being "used".

**Comment by vnen** [comment]
> In a nutshell, the broader issue here is that methods that directly operate on the declared **Variant** do not count towards the variable being "used".

No, that is not an issue. Those do count as the variable being used. The warning in the OP is the variable was never **assigned** before being used, which is technically true.

The question is whether or not relying on the default value is okay or not. If so, then the warning don't have much use. Or at least not for built-in types, since their default is a valid value.
