### ISSUE TITLE
Duplication of tiles is broken in Gridmap 

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#8812]
**Operating system or device - Godot version:**
linux mint 2.1.3

**Issue description:**
I try to use gridmap for a simple project and I find out that when duplicating the area, the way to place the duplicated part is not good, from the image, you can see that I have to point my cursor to somewhere far away to move the target near the original area. I assume this is due to how the origin is set in gridmap? is it better to let the cursor stick to the middle of the duplicated part? 
![2017-05-18 23 06 04](https://cloud.githubusercontent.com/assets/10883749/26209301/fa6276f2-3c1e-11e7-9b40-781a70153268.png)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ZX-WT** [comment]
I tested and I think this issue is solved, so I am closing it now.
