### ISSUE TITLE
Importing glTF with nested structure gives "inconsistent owner" warning

### ISSUE THREAD

**Issue by stevenctl** [godotengine/godot#88125]
### Tested versions

- Reproducible in 4.3-dev3
- Not reproducible in 4.2 stable

### System information

Linux 6.1 - Godot 4.3-dev3 - OpenGL Compat backend

### Issue description

When importing a gLTF file with some nested hierarchy, each child of the scenes root (and nested children) emit the following warning:

```
  scene/main/node.cpp:1432 - Adding 'Rope' as child to 'Mast' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'Sail' as child to 'Mast' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'RearFlag' as child to 'RearFlagPole' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'Door' as child to 'Ship' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'Mast' as child to 'Ship' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'RearFlagPole' as child to 'Ship' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
  scene/main/node.cpp:1432 - Adding 'Wheel' as child to 'Ship' will make owner 'pirateship' inconsistent. Consider unsetting the owner beforehand.
```

This doesn't seem to cause any real issues and ownership ends up being fine. 

### Steps to reproduce

Simply import the glb. You don't need to instance it in a scene or do anything else. 

### Minimal reproduction project (MRP)

[repro.zip](https://github.com/godotengine/godot/files/14216664/repro.zip)

**Comment by Rindbee** [comment]
Related to #78997, which did not take into account the case where the sub-scene root node was `replaced_by`.

**Comment by akien-mga** [comment]
CC @Sauermann
