### ISSUE TITLE
Writing "con" or "con.anything" into img-tag of RichTextLabel freezes the editor if BBCode is enabled and using _console-version of Godot

### ISSUE THREAD

**Issue by GNSS-Stylist** [godotengine/godot#88120]
### Tested versions

- Reproducible in v4.3.dev.custom_build [41564aaf7], 4.2.1, 4.1.3, 3.5.3 (_console-versions)
- Not reproducible in non-console-versions

### System information

Godot v4.3.dev (41564aaf7) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

When editing an img-tag on the Text-field of RichTextLabel, the editor freezes immediately when the tag contents is "con" or starts with "con." (like "con.png" or "con.jpg"). This is very likely windows-specific issue as the source file in the warning-message just before freezing suggests (and con-file has a special meaning in windows). The error message is identical on all Godot-versions mentioned, only the line number varies.

This only happens in _console-versions (like godot.windows.editor.x86_64.console.exe), but not in non-console-versions.

Video:

https://github.com/godotengine/godot/assets/50438441/b2f9939e-38d6-48a7-affb-23ea11b79f4e

### Steps to reproduce

1. Open _console-version of the Godot editor (like godot.windows.editor.x86_64.console.exe)
2. Add RichTextLabel
3. Enable BBCode
4. Write [img]con[/img] into the Text-field of the label. This causes the editor to freeze.

### Minimal reproduction project (MRP)

[RichTextLabelBug_Godot_master.zip](https://github.com/godotengine/godot/files/14215322/RichTextLabelBug_Godot_master.zip)

**Comment by akien-mga** [comment]
Sounds related to #20110, but this one was fixed. RTL image loading might be using a different code path to load the image than FileAccessWindows? CC @bruvzg

**Comment by bruvzg** [comment]
RTL is using `ResourceLoader::load(path)` to load images, it should be generic issue with reserved file names in `FileAccess`.

**Comment by bruvzg** [comment]
Most likely resource loader is adding `res://` to the name, and `is_path_invalid` it checking the whole path not a file name (so it's probably broken in most case).
