### ISSUE TITLE
OmniLight can produce weird shadows when close to objects

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8813]
**Godot version: master ed6baffc7**

**Issue description:**
OmniLight can produce (cool) weird shadows:
![omnibug](https://cloud.githubusercontent.com/assets/10215987/26213577/fc331be8-3bcf-11e7-83ac-70f6315195c9.png)

I refer to the cat eye shaped figure in the shadows, happens with both light modes, cube and dual paraboloid.
My almost null knowledge on 3D scenes may be a problem here too, these are using default settings.

**Steps to reproduce:**
Just put an OmniLight over a cube close to the object.

**Link to minimal example project:**
[omnishadow.zip](https://github.com/godotengine/godot/files/1011639/omnishadow.zip)

EDIT:
Rotating the shadow gives a more impressive effect:
![rotatedomnibuggedshadow](https://cloud.githubusercontent.com/assets/10215987/26214027/5cf75e52-3bd1-11e7-8cd9-d3e6756b216b.png)

**Comment by reduz** [comment]
This is not a bug, it's the shadow set to Dual Paraboloid mode, If set to Cube it gets fixed. I will change the default so it doesn't happen again..

**Comment by eon-s** [comment]
@reduz Shows a little line with cube (at least until 4d50c7ad8)

![omnicube](https://user-images.githubusercontent.com/10215987/27064421-9f555e4c-4fcd-11e7-86fa-6a3706c1c13c.png)

**Comment by reduz** [comment]
might have just fixed that

**Comment by eon-s** [comment]
Well, now noticed an extra thing on cube mode, on the top it draws an extra light (default settings).
Using a8a1f2e2a

![omnishadow-a8a1f2e2a](https://user-images.githubusercontent.com/10215987/27102591-2592169c-505c-11e7-897e-f3915782499d.png)

Should I open another issue for this light mode?
