### ISSUE TITLE
Cannot add icons to a module without forking Godot

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8814]
As a continuation to #4562, AFAIK it's not possible to include custom icons to a module, because they are stored in a separate folder `tools/editor/icons` which is part of the core editor.
It would be great to be able to define icons in modules to make them more independent and easy to install.
This makes me think that, any resource that we bundle in the editor could be added to modules this way instead of a global folder.

**Comment by HumanSheeple** [comment]
It IS possible:

![issue solved](https://user-images.githubusercontent.com/28750624/27001234-3db1077e-4db4-11e7-8e80-c7c673c255e9.png)

What I don't yet know how to do is how to memdelete textures, and Ref<ImageTexture>'s potential issue with memory leaks though

**Comment by Zylann** [comment]
@HumanSheeple as discussed on Discord already, what you did was to write a new script doing that only for your module. A better option IMO would be to be able to use the existing one in Godot's build system.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
I don't remember of anything being done for this. Also, builtin modules still don't have icons in their own folders.

**Comment by avencherus** [comment]
Seems like a nice thing to have.  I just started fiddling around with modules, and having difficulties getting the Node derived classes to acquire an icon in the editor.  

@willnationsdev Seen that you've done some work with icons in the past.  Wondering if you may might have some insight into this.

**Comment by willnationsdev** [comment]
Well, if there is already a way of doing it, as @HumanSheeple described, then isn't the task really just defining a place that wraps that code and provides a method where all we need to do is pass in a filepath and a name?

If we want the data to reside in the modules, but we want the editor to have access to them, then the wrapper code should go somewhere in the Editor codebase. Then the module can, if TOOLS_ENABLED, include the relevant editor code and call the method (probably an independent class's static method).

Are there any issues with that concept that stick out to anyone? Otherwise, it seems like a decent approach.

**Comment by avencherus** [comment]
@willnationsdev Glad I asked.  X)  

Given my current level of understanding the icon handling itself appears arcane, but I can follow the implementation idea you have.  I'm assuming based on what you're saying, there doesn't already exist something to reach into for registering icons.  Having a registry method does sound like the most clear approach.  `register_editor_icon(path)`

What would be the situation with reusing existing editor icons?  I was kind of expecting them to be inherited when extending from a node class.  Maybe I'm missing something there.

**Comment by Xrayez** [comment]
> What would be the situation with reusing existing editor icons? I was kind of expecting them to be inherited when extending from a node class. Maybe I'm missing something there.

I think that's somewhat different issue here. 

I've managed to define custom icons paths per module in the above PR though, it didn't require too much to get it to work!
