### ISSUE TITLE
Editor non responsive when clicking on 'Search Help' for docs within the scripts panel on version 4.3 dev3.

### ISSUE THREAD

**Issue by produno** [godotengine/godot#88140]
### Tested versions

Introduced in 4.3 dev3.

### System information

Godot v4.3.dev3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.4665) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When clicking on the search help button for the documentation within the scripts window, the editor will hang forcing me to have to close and re-open again. This also happens with the Editor Settings, Project Settings and Export. I also have this error show when opening the projects that have this issue.

`editor/export/editor_export.cpp:225 - Condition "!preset.is_valid()" is true. Continuing.`

This only seems to happen with some of my projects however and not all of them.

### Steps to reproduce

Open the scripts tab and click the search help button to search the documentation.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

**Comment by produno** [comment]
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

It looks like i cannot open the editor settings, neither can i open project settings or export.

I do get this error showing on opening the project:

`editor/export/editor_export.cpp:225 - Condition "!preset.is_valid()" is true. Continuing.`
