### ISSUE TITLE
Particle shadows work only with directional light

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8815]
**Godot version: master ed6baffc7 **

**Issue description:**
Particle shadows from omni and spot lights are updated only once (in editor and maybe running, hard to tell), they work fine with directional light. 

![particleshadows](https://cloud.githubusercontent.com/assets/10215987/26214760/f196219a-3bd3-11e7-8254-efad13247167.png)

**Steps to reproduce:**
Create an omni and/or spotlight that makes particles to projects shadows.
Do the same with a directional light.

**Link to minimal example project:**
[particleshadow.zip](https://github.com/godotengine/godot/files/1011715/particleshadow.zip)

**Comment by reduz** [comment]
This bug is great, because it shows shadows are updated when geometry around changes, which is correct and a fanastic feature. Except it seems it's not working for particles, so fixing.
