### ISSUE TITLE
Window dialog title bar's background are not visible on default theme

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8816]
**Ubuntu 17.04 - Godot version: master ed6baffc7**

**Issue description:**
Title bars of window dialogs have a not visible/transparent background (affects editor and respective controls with default theme). 

This is how the project manager looks:
![transparent-title](https://cloud.githubusercontent.com/assets/10215987/26217767/f41be67e-3bde-11e7-929d-36cf959a9116.png)

I think this is a known theme issue but I have not seen it anywhere else.

**Comment by akien-mga** [comment]
Fixed by #8631.
