### ISSUE TITLE
Main editor toolbar icons are blurry

### ISSUE THREAD

**Issue by davthedev** [godotengine/godot#88165]
### Tested versions

- Reproducible on 4.3-dev3

### System information

Godot v4.3.dev3 - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (ICL GT2) () - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

The icons on the main toolbar are blurry.

![image](https://github.com/godotengine/godot/assets/26961646/6c84e904-50b7-4ef6-8d4f-dbbb6552b7fa)

You can compare with those from the side palette which are drawn correctly. The three-dot "more" icon is a good point of comparison.

### Steps to reproduce

Create a new project and see the main editor window. Make sure you run a non-hidpi  setup with 1920x1080 monitor, and OS scaling setting ideally set to 100% for instance, to avoid any default upscaling taking place which would make the issue not visible.

### Minimal reproduction project (MRP)

N/A, sufficient to open an empty project in the editor

**Comment by davthedev** [comment]
Non-integer spacing somewhere?

There has been a complete refactoring of the editor theme generation with emphasis on margins/spacings. Could this be a side effect?

**Comment by Mickeon** [comment]
I can certainly confirm the issue. it is difficult to visualize a comparison, but _something_ has changed and they definitely look blurrier as a result.

[![Image from Gyazo](https://i.gyazo.com/14552384e2568036c9a368e56086fb75.gif)](https://gyazo.com/14552384e2568036c9a368e56086fb75)

**Comment by Maran23** [comment]
Just found this today as well. Also not sure where this comes from, resizing does not fix it.
![image](https://github.com/godotengine/godot/assets/66004280/b41bbe41-55c4-49b8-96be-8efe2fe90ab1)

**Comment by williamsrb** [comment]
A quick comparison of versions:
![image](https://github.com/godotengine/godot/assets/608031/08032192-85f6-46a6-8c80-7a14588f83cd)

My guess is that it's related to SVG_Renderer from Freetype.
It was update here https://github.com/godotengine/godot/commit/008d3de1e9387720c16820adb5858e5a1278762b last time, so since 4.2.1 it's probably an issue.

I'm not a C developer. Maybe @bruvzg could help us confirm this bug is related to Freetype update. By the way, sorry for bothering you (tagging).

**Comment by bruvzg** [comment]
> My guess is that it's related to SVG_Renderer from Freetype (this file, maybe? godot/thirdparty/freetype/src/svg/ftsvg.c)

No, FreeType is not related to the icons in any way. Most likely it's something with icon positions (theme or control changes).

**Comment by davthedev** [comment]
Interesting find!

Then we should look for drawing code that puts images at non-integer coordinates. This is a probable culprit.

UI toolkits of long ago may have had logic that automatically snap images and primitives to the nearest pixel. In Godot, if you draw something between pixels, it gets blurry. Rounding coords to the closest pixel after calculation may be a solution.

One suggestion would be to recommend checking the result on non-hidpi displays every time there is UI code being worked on. Perhaps add a little mention in the developer docs about that? Because someone who only works on 4K/Retina/hidpi or similar screens would never see the issue on his configuration.
