### ISSUE TITLE
Godot not opening

### ISSUE THREAD

**Issue by Mannega** [godotengine/godot#88169]
### Tested versions

4.2.1, 4.2, 4.1.3

### System information

Windows 11, 4.2, 4.2.1, 4.1.2, Mobile

### Issue description

When I launch Godot which was 4.2 it just gives me a grey screen and never shows the logo and directly closes like nothing. I tried to go with Godot 4.2.1 and 4.1.3 which was the first version I ever use it never opens.

### Steps to reproduce

Please Contact me at my email which is again, mo13241234@gmail.com
![red-dot-24](https://github.com/godotengine/godot/assets/122459427/97af6618-2f09-4421-bc81-48940388291b)

### Minimal reproduction project (MRP)

I have no project If you want to Contact me here is my email: mo13241234@gmail.com
![red-dot-24](https://github.com/godotengine/godot/assets/122459427/03428a23-4be0-4513-b395-99642912962c)

**Comment by AThousandShips** [comment]
Please provide details here, you're not going to get an email, this isn't a support channel this is to report bugs

Please provide your system details, not only operating system, this is very likely due to hardware or drivers

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
