### ISSUE TITLE
Strange effect with shadows enabled on DirectionalLight

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8817]
**Godot version: master 32afcbc48 but more recent too**

**Issue description:**
Using default settings, when turning shadows `on` on a DirectionalLight, the editor get some weird effect on textures.
Camera viewport get less noisy output and the running camera even less, but is still there.

![shadowbug](https://cloud.githubusercontent.com/assets/10215987/26223544/f228777c-3bf4-11e7-8e70-736e57facf8c.png)

I think the effect is not present on OmniLight and just at some extent on SpotLight (faces parallel to the light direction). 
This may be a bad default setting issue, but not sure.

**Steps to reproduce:**
Add a directional light to a 3D scene and enable shadows. 

**Link to minimal example project:**

[shadowtest.zip](https://github.com/godotengine/godot/files/1012427/shadowtest.zip)

**Comment by Zireael07** [comment]
Looks very close to my weird flashes from #8651, so chances are the two are related.

**Comment by eon-s** [comment]
This problem doe not exists in a late january build

**Comment by reduz** [comment]
hmm this looks like default shadow bias setting, should investigate

**Comment by eon-s** [comment]
A normal bias (not shadow) of around 0.7 make the strips disappear but not sure if is the correct setting.

**Comment by reduz** [comment]
Rewrote the way bias works in DirectionalLights, this should make it work much better. Also changed default settings so it looks good on the first attempt
