### ISSUE TITLE
same code works fine on a normal c# project but not on Godot 4.2

### ISSUE THREAD

**Issue by maurosorrentino** [godotengine/godot#88174]

**Comment by AThousandShips** [comment]
Please do not clear your issue reports, it just confuses and clutters

**Comment by maurosorrentino** [comment]
ok sorry I didn't know how to delete it, I thought it was a Godot bug but it was a bug in my code. Not sure why it was working on the same c# (not godot) project and I thought code wasn't working when running it with Godot

**Comment by AThousandShips** [comment]
You can't delete issues, nor can we
