### ISSUE TITLE
Thumbnails not visible in filesystem dock 4.3.dev.xx

### ISSUE THREAD

**Issue by Ciapas-Linux** [godotengine/godot#88170]
### Tested versions

Reproductible in all versions 4.3.dev.xx
Not Reproductible in 4.2 and below

### System information

Linux debian based godot 4.3.dev.xx

### Issue description

Hi
As you can see, there are no image thumbnails in the filesystem dock, in all versions 4.3, maybe it's not a bug but I have it enabled in the editor options. Instead, there are some funny icons. In version 4.2 this worked fine.

ERROR: Condition "!cache.has(p_path)" is true. Returning: Dictionary()
   at: get_preview_metadata (editor/editor_resource_preview.cpp:212)

![fs-dock](https://github.com/godotengine/godot/assets/84653835/3431bd59-4219-4573-b82f-f3916e671b94)

I use a Linux system based on Debian, nvidia card, proprietary drivers from nvidia. X11 x.org plus openbox as window manager.

### Steps to reproduce

I download godot, open it and I just don't see the thumbnails.

### Minimal reproduction project (MRP)

I guess it's not necessary in this case.  When I create a new empty project, the same thing happens.

**Comment by capnm** [comment]
I see the same issues on debian 12 / ubuntu, but it updates here after you start some scene...

**Comment by AThousandShips** [comment]
This might be a thread safety issue, but might be some other cause as well

**Comment by capnm** [comment]
> I guess it's not necessary in this case. When I create a new empty project, the same thing happens.

I am actually experiencing that issue, but only when there is a large number of images. When I hover the mouse pointer over an image in the file dock while many thumbnails are still being generated in the background, this error is displayed.

![image](https://github.com/godotengine/godot/assets/4047289/414add5f-fae5-45ea-94dc-f85e3aa289b8)

![image](https://github.com/godotengine/godot/assets/4047289/fcc59dd2-0be5-40c5-92ff-26fa32a25448)


Additionally, I have noticed that I can trigger a UI-deadlock by quickly hovering over an image several times to generate a tooltip and perform a quick right-click. I discovered this issue while investigating open terminal problems. However, I believe this is a  different issue.

**Comment by Rennan24** [comment]
At least on Windows 11 if I set my project to Forward+ / Mobile it has thumbnails, but in compatibility mode it does not work which is a little weird? This issue also happens in the 4.3-dev3! and I get that same cache.has(p_path) error, can you guys try changing it to forward+ or mobile and seeing if it works on Linux 🤔 I'm not brave enough to make the switch to Linux yet 😂

**Comment by DanielSnd** [comment]
> At least on Windows 11 if I set my project to Forward+ / Mobile it has thumbnails, but in compatibility mode it does not work which is a little weird? This issue also happens in the 4.3-dev3! and I get that same cache.has(p_path) error, can you guys try changing it to forward+ or mobile and seeing if it works on Linux 🤔 I'm not brave enough to make the switch to Linux yet 😂

I'm having the same issue on Windows 11 in 4.3-dev3 compatibility mode.

I went digging and found this:
File `godot/editor/editor_resource_preview.cpp`
```c++
void EditorResourcePreview::start() {
	if (DisplayServer::get_singleton()->get_name() == "headless") {
		return;
	}

	if (RSG::texture_storage->can_create_resources_async()) {
		ERR_FAIL_COND_MSG(thread.is_started(), "Thread already started.");
		thread.start(_thread_func, this);
	} else {
		SceneTree *st = Object::cast_to<SceneTree>(OS::get_singleton()->get_main_loop());
		ERR_FAIL_NULL_MSG(st, "Editor's MainLoop is not a SceneTree. This is a bug.");
	}
}
```

It seems that in compatibility mode can_create_resources_async() is returning false, and in the else it just gets a temporary pointer to the scene tree and does nothing with it... I'm assuming whoever did this was going to hook a process_frame callback to do the creation of resources in a sync manner?

In contrast this is the same method from 4.2:

```c++
void EditorResourcePreview::start() {
	if (DisplayServer::get_singleton()->get_name() != "headless") {
		ERR_FAIL_COND_MSG(thread.is_started(), "Thread already started.");
		thread.start(_thread_func, this);
	}
}
```

It seems in 4.2 it was just started threaded no matter what, without any checks.
