### ISSUE TITLE
Can't write Label text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88176]
### Tested versions

Regression from #68420

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/a4a50655-3777-495f-894a-1c21fb9e704d

This is caused by Label calling `update_configuration_warnings()` in `set_text()`:
https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/scene/gui/label.cpp#L909
Which since #68420 will cause inspector update.

I somehow overlooked it while reviewing, I think there should be a separate warning signal that causes inspector update.
CC @RedMser 

### Steps to reproduce

1. Add Label
2. Change `text` property

### Minimal reproduction project (MRP)

N/A

**Comment by kleonc** [comment]
> CC `@redms`

cc @RedMser :upside_down_face:

**Comment by RedMser** [comment]
So when update_configuration_warnings() happens, instead of directly queuing an inspector update, it should instead wait for a time when the user is not interacting with inspector? How would this be detected?

Or do you suggest another update mechanism specifically for updating the config warning icon in the inspector, without updating the rest of the inspector (which sounds a lot harder given the current update logic, it ties itself to the whole inspector's layout)?

**Comment by KoBeWi** [comment]
I mean since your new inspector update is specifically to update configuration warnings that refer to a property, there should be a separate method that updates warnings and the inspector. That way the old method would *not* trigger inspector update, because most warnings don't need inspector update. If a user has a warning referring to a property, they should use the other method.

That's the simplest solution for now. I don't think partial inspector update or the other thing you mentioned is reasonable to implement

**Comment by RedMser** [comment]
Ah that makes sense. Is adding new arguments to a signal a breaking change?
If not, I could give the `SceneTree.node_configuration_warning_changed(Node *p_node)` signal a second argument: an Array of property names that changed on the given node. So inspector would only update if this array is not empty.

**Comment by RedMser** [comment]
I implemented my proposed fix in #88182
