### ISSUE TITLE
Shader parameters for shaders that use vulkan-only features are not included when exporting a project in headless mode

### ISSUE THREAD

**Issue by nikitalita** [godotengine/godot#88187]
### Tested versions

v4.3.dev.custom_build [d3352813ea44447bfbf135efdec23acc4d1d3f89]

### System information

Godot v4.3.dev (d3352813ea44447bfbf135efdec23acc4d1d3f89) - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (12 Threads)

### Issue description

Related:  #66842

While this issue was supposed to be fixed in #87392, it only does so if the shaders do not use any vulkan-specific features ( e.g. certain built-in functions, like `findLSB()`). If the shaders DO use vulkan-specific features, it fails to compile and obliterates any shader parameters.

before/after export:
![image](https://github.com/godotengine/godot/assets/69168929/cfc20bd2-7ab5-4f71-9cf5-b753325a495f)

### Steps to reproduce

`<path_to_editor_bin> --headless --path <retro-post-processing_path> --export-pack test_export_preset test_export.zip`

should see shader compile errors in the output:
```
SHADER ERROR: Built-in function "findLSB(int)" is only supported on high-end platforms.
          at: (null) (:26)
ERROR: Shader compilation failed.
   at: shader_set_code (servers/rendering/dummy/storage/material_storage.cpp:90)
```

Open the zip, look at render_container.tscn, observe that the parameters (and the external resources that were used by those parameters) are removed.

### Minimal reproduction project (MRP)

[retro-post-processing.zip](https://github.com/godotengine/godot/files/14230909/retro-post-processing.zip)

**Comment by clayjohn** [comment]
The dummy rendering server should appear as a high end platform. I think there is just a single function overload for this.

**Comment by nikitalita** [comment]
No, that won't work by itself; there's checks for rendering_method in ShaderLanguage, too:
https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/servers/rendering/shader_language.cpp#L8368

This sort of thing happens in a couple of places; One other place is the ResourceImporterShaderFile:
https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/editor/import/resource_importer_shader_file.cpp#L94-L95

I think what would work best is if there was some sort of override that the exporter could set for the rendering method that these various things look at when they need the `rendering_method`. Like, the desktop oses would set whatever the project config setting is for "rendering/renderer/rendering_method", the android exporter would set "rendering/renderer/rendering_method.mobile", etc.

**Comment by nikitalita** [comment]
After testing, just setting `low_end` will do for this particular issue, because we still set the renderer mode that’s in the project config. However, visual shaders should probably be recompiled based on what the actual renderer_method, and the resourceimportshaderfile compiles for whatever the device driver gives it for the Vulkan parameters (i.e. when it’s headless, it compiles for the lowest Vulkan API version). These are separate issues, though.
