### ISSUE TITLE
Godot claims an EditorImportPlugin implemented in C# hasn't implemented `_get_recognized_extensions`, `_get_importer_name`

### ISSUE THREAD

**Issue by 31** [godotengine/godot#88180]
### Tested versions

- v4.1.1.stable.mono.official [bd6af8e0e]
- v4.2.1.stable.mono.official [b09f793f5]
- v4.3.dev2.mono.official [352434668]
- v4.3.dev3.mono.official [36e943b6b]

### System information

Godot v4.3.dev2.mono - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

Based on https://docs.godotengine.org/en/stable/classes/class_editorimportplugin.html, it seems to me that this should be an ok starting point:

```cs
#if TOOLS
using Godot;
using Godot.Collections;

[Tool]
public partial class TxtImporter : EditorImportPlugin
{
    public override string _GetImporterName() => "Text file importer";
    public override string _GetVisibleName() => "Text file";
    public override string[] _GetRecognizedExtensions() => new[] { "txt" };
    public override string _GetResourceType() => nameof(Resource);
    public override string _GetSaveExtension() => "words";
    public override float _GetPriority() => 1.0f;
    public override int _GetPresetCount() => 0;
    public override int _GetImportOrder() => 0;
    public override bool _GetOptionVisibility(string path, StringName optionName, Dictionary options) => true;

    public override Error _Import(
        string sourceFile,
        string savePath,
        Dictionary options,
        Array<string> platformVariants,
        Array<string> genFiles)
    {
        GD.Print("Reached Import");
        return Error.Ok;
    }
}
#endif
```

However, when I have a plugin enabled that adds this importer, I get ~50 of these errors in the Output dock when the editor starts:

```
Unimplemented _get_resource_type in add-on.
Unimplemented _get_importer_name in add-on.
```

### Steps to reproduce

1. Open the MRP.
2. Hit "ok" for the warning that pops up because the plugin hasn't been built yet.
3. Build Project.
4. Reload Current Project.
5. Open the Output dock.

### Minimal reproduction project (MRP)

[Godot4TryImporter.zip](https://github.com/godotengine/godot/files/14230194/Godot4TryImporter.zip)

**Comment by ArchercatNEO** [comment]
## Can confirm issue on
Godot v4.2.1.stable.mono 

## System information
Debian GNU/Linux 12 (bookworm) 12
Wayland - Vulkan (Forward+)
integrated Intel(R) HD Graphics 4600 (HSW GT2) ()
Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 Threads)

## Additional broken import plugin
[XcfImporter.cs](https://github.com/ArchercatNEO/Sanicball/blob/0fe1c706eac0c44e97b3a0612e77f60e77179cb6/Sanicball/addons/XcfImporter/XcfImporter.cs)

**Comment by raulsntos** [comment]
In `TryImporter.cs` you are creating an instance of the base class `EditorImportPlugin` because you use a target-typed new expression:

```csharp
EditorImportPlugin _importer;

_importer = new(); // This is equivalent to `new EditorImportPlugin()`
```

Instead, you should change the type of the `_importer` field to `TxtImporter` or use the explicit type name in the new expression.

**Comment by 31** [comment]
Can't believe I didn't spot that. Thanks! 😄 

I suppose the error could be more specific, but that's its own thing.
