### ISSUE TITLE
TileSet Exporter does not export nested sprites

### ISSUE THREAD

**Issue by zlsa** [godotengine/godot#8819]
**Operating system or device - Godot version:**

Arch Linux; Godot 2.1.3 official

**Issue description:**

When converting a TileSet scene into a TileSet resource, the exporter requires the sprites to be top-level or one child down. For example, if you had a scene with the hierarchy:

```
+ root
|
+-+ dirt
| +- dirt-center
| +- dirt-top
| +- dirt-bottom
|
+-+ grass
| +- grass-1
| +- grass-2
|
+-+ nuclear-barrel
```

the TileSet exporter would export only `dirt-center`, `grass-`, and `nuclear-barrel`. This is because of the non-recursive nature of the parser.

#5816 is potentially related.

**Steps to reproduce:**

1. Create a new TileSet scene.
2. Create a hierarchy of nodes.
3. Scene > Convert To > TileSet
4. Most of the nested tiles are missing.

The fix for this should be pretty simple. I'm working on one right now, and if it works properly, I'll submit a PR soon.

**Comment by eon-s** [comment]
Tileset resource only accepts one texture per tile.

I'm not sure if make sense to have many textures on a single tile (I have never seen that either).
