### ISSUE TITLE
Running no-threads web export blanks screen once 1000 objects are visible in scene due to threaded culling being incorrectly used

### ISSUE THREAD

**Issue by JyveAFK** [godotengine/godot#88192]
### Tested versions

v4.3.dev3.official[36e943b6b]

### System information

Godot v4.3.dev3 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.2849) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

When running a scene with 1000 objects in a scene in a webexport (both on a server and from the editor), the screen blanks and nothing is visible apart from the background colour of the scene.
With 999 objects, it works;
![image](https://github.com/godotengine/godot/assets/32004318/cfbd32b7-8b4f-44e2-b2ce-b74280a6e0f7)
With 1000 objects, it blanks out everything that was in the scene already.

![image](https://github.com/godotengine/godot/assets/32004318/c4a24c25-2a1b-4758-b994-4428d36b0221)

### Steps to reproduce

Add 1000 objects to a scene.  Run it normally, it'll work.  Add a 'webexport', turn off threading in the export, and hit 'run in browser' and the project exhibits the problem.
![image](https://github.com/godotengine/godot/assets/32004318/26db2ef3-11b5-454d-be95-7ae6cb3828ec)

### Minimal reproduction project (MRP)

[WebExport1000.zip](https://github.com/godotengine/godot/files/14231278/WebExport1000.zip)

**Comment by clayjohn** [comment]
Perhaps this is connected to `rendering/limits/spatial_indexer/threaded_cull_minimum_instances`? Can you try increasing that limit and seeing what happens?

Or conversely lowering the limit and seeing if you can reproduce the issue with fewer objects?

**Comment by JyveAFK** [comment]
That was exactly it.  Bumping it up, gets it working, lowering it down to a 100, stops it working past 99 objects in a scene.  Thank you, hadn't seen that setting/understood what it was used for.   

Is this something I can set in the code/something for a scene property to get it to roughly have an idea when it needs to worry about culling, or just be careful for webexports and check/set it a few % above the amount of objects you think you'll need in the scene?  Is there a way around this, or am I doing something wrong.  

Also tested, when it goes too high and everything disappears, removing nodes WILL make everything re-appear again.  I thought everything in the scene had disappeared, but it was just waiting to get down below that number to display again.

Thanks for the heads up on where to look for this setting.  I'll make note to check on node counts in a scene before webexports.
