### ISSUE TITLE
Volumetric fog doesn't work for lights which were enabled later in game (occurs only with enabled shadows in Light3D) 

### ISSUE THREAD

**Issue by interpol-kun** [godotengine/godot#88225]
### Tested versions

- Reproducible in Godot v4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 Threads)

### Issue description

I have a game project which relies on turning the lights on/off throughout the game. I am using Volumetric Fog for World Environment, but if some of the lights were turned off when the game started, the fog doesn't work for them even if I enable the lights later in game. **The issue is not present when Light3D has no shadows enabled.**

Image for reference: green light were enabled all the time, white light were enabled via game logic.
![image](https://github.com/godotengine/godot/assets/7690603/30b506d3-bbd9-46f8-b917-b44e9df6e756)

### Steps to reproduce

Create sample scene with Volumetric Fog and any light source (e.g. OmniLight3D). Enable shadows for the light source. Disable Light node in editor, launch the game, enable it via inspector, check the game.

### Minimal reproduction project (MRP)

[TestFPS.zip](https://github.com/godotengine/godot/files/14234434/TestFPS.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83685, as this is due to the same cause. (Using `canvas_items` stretch mode and resizing the window fixes the issue – you can also change the 3D resolution scale factor a bit.)
