### ISSUE TITLE
AnimationTree Expressions not working

### ISSUE THREAD

**Issue by nuclear** [godotengine/godot#88223]
### Tested versions

Godot v4.2.1.stable 

### System information

Windows 10- GLES3 (Compatibility)

### Issue description

![image](https://github.com/godotengine/godot/assets/49957150/c0066eb0-73e0-4091-9b6e-4956f4554aea)
### The Problem
It seems that the Advance Expression is being ignored. Similar to #77355 
Even though **warrior_state == "attack"** yields a true, the animation doesnt start.
### Workaround
Switching to the attack animation works when having something like **is_attacking** (true/false) as the expression. This isn't ideal however as it will bloat the code once I want to add more than a couple of states.

### Conclusion
Is this a bug or intended feature? Unfortunately there is no documentation on this.

### Steps to reproduce

Simply define a variable and check if it equals to a string in the AnimationTree

**Comment by TokageItLab** [comment]
Is it only for strings, or is it also the same for int and onther types? Can variables be used correctly with AdvanceExpression in the first place? I am not so familiar with this feature, but I guess it is probably a documentation issue. cc @SaracenOne

**Comment by ratkingsminion** [comment]
I tried this in my own project with a simple AnimationTree and two transitions checking for a String variable for being either "yes" or "no". It works (Godot 4.2.1), so I guess the problem lies somewhere else?

**Comment by nuclear** [comment]
I found the issue:
I did not set the advance_expression_base_node properly, thefore the variable checks all failed of course.

I'd suggest the engine throw an warning if checking variables which dont even exist!
