### ISSUE TITLE
Color Picker on Mobile causes keyboard to popup by default

### ISSUE THREAD

**Issue by Bimbam360** [godotengine/godot#88235]
### Tested versions

v4.3.dev2.official [352434668], likely has existed for longer.

### System information

Pixel 6a Android

### Issue description

When clicking on the color picker button it by default brings up the onscreen keyboard. Likely because the 'Hex' field is active by default.

Why is this a bug? See below:
![Screenshot_20240212-173731](https://github.com/godotengine/godot/assets/11803603/455ee748-d4d5-4d52-8757-102cef0ec689)

Setting hex_visible to false does not work around the issue.

### Steps to reproduce

Add a ColorPickerButton node.
Click it.

### Minimal reproduction project (MRP)

Am not near computer, but can MRP if required later.

**Comment by Calinou** [comment]
This is because the HTML color field is autofocused when opening ColorPicker, and this causes a virtual keyboard to pop up.

**Comment by WhalesState** [comment]
> Is there a way we can have an autofocusing field on Android/iOS without making a virtual keyboard pop up? This would be the ideal solution here, so it still works as expected when you have a hardware keyboard connected.

This may fix the issue https://github.com/godotengine/godot/pull/87674, we can use `grab_focus()` instead of `grab_focus_edit()` on mobile.

**Comment by WhalesState** [comment]
> I don't see `grab_focus_edit` anywhere in the Godot codebase in `master`. Is that a method added by a PR?

It was changed for compatibility, the only way now to `grab_focus()` without editing is to use the arrow keys when focusing the `LineEdit`, so maybe we can send an input action event `ui_up` before using `grab_focus()` to prevent it from entering edit mode.

**Comment by WhalesState** [comment]
The linked pull request will disable editing before focusing the hex `LineEdit` and will enables it again as a hack to only focus without editing, also the `ColorPicker` window will no longer hides when `ui_accept` is pressed, to not prevent any buttons from being pressed with `Enter` key.

**Comment by syntaxerror247** [comment]
@WhalesState I think using has_hardware_keyboard method will be better for this issue

**Comment by WhalesState** [comment]
> @WhalesState I think using has_hardware_keyboard method will be better for this issue. As @Calinou mentioned, this method wil ensure that its Usability will remain unchanged with hardware keyboard on mobile devices.

Yes, I will check for hardware keyboard on ios and android devices only, since it will cause issues on some other platforms.

Yet the hack will be needed to avoid showing the virtual keyboard when the `ColorPicker` popups when no hardware device is connected, since this is the original issue.

> If we use this to return from (LineEdit/TextEdit) show_virtual_keyboard when DisplayServer::get_singleton()->has_hardware_keyboard() is true, it will never show the virtual keyboard on Web (android/ios) since it will always return true on Web.
