### ISSUE TITLE
[3.x] new ORMSpatialMaterial broke gltf file import.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#88232]
### Tested versions

Current version with https://github.com/godotengine/godot/commit/354404db6067997c1db358ba9c50668e93415b07.

### System information

Windows 11 - Godot 3.x build with current head version.

### Issue description

When import .glb file, some of the meshes may failed to import with material.
In console it showed that something like unknow Material3D in file format.
Revert changes in gltf_docment.cpp and .h will fix it.

### Steps to reproduce

Just import gltf file in current version.

### Minimal reproduction project (MRP)

A project with a gltf file to import.

**Comment by clayjohn** [comment]
CC @Ansraer @lawnjelly

**Comment by lawnjelly** [comment]
I'm guessing the ORM PR may have gone too far with global replace for `SpatialMaterial` to `Material3D`.

It's possible as you say that reverting the changes to just these 2 files is enough for now, I'm assuming the GLTF code would need specific modification in the future if it were to be able to _distinguish_ between `SpatialMaterial` and `ORMSpatialMaterial`, but that doesn't seem necessary at this stage.

We should probably have a check whether this same issue could affect any more import flows.

I'll be away at least until thurs so @Ansraer or @harrisyu or anyone else it would be great to fix this. I don't think it should be necessary to revert the ORM PR as the fixes should be fairly simple.

**Comment by lawnjelly** [comment]
Fixed by #88287.
