### ISSUE TITLE
NavigationAgent3D cuts corners and gets stuck

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot#88237]
### Tested versions

Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.4629) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

get_next_path_position() allows agents to path outside of the navigation mesh, inevitably getting stuck on corners of static colliders, or falling off platforms. This happens regardless of any configured parameters such as agent radius, desired distance, etc.

### Steps to reproduce

The MRP has a scene with as many default settings as possible to show a state where a CharacterController3D gets stuck on a corner of a static collider. This isn't an outside case, it's fairly easy for agents to get into this stuck state.
![image](https://github.com/godotengine/godot/assets/1812087/80b75328-09c4-453d-afe1-00c436b8ffc5)

### Minimal reproduction project (MRP)

[navtest.zip](https://github.com/godotengine/godot/files/14236635/navtest.zip)

**Comment by smix8** [comment]
![clip](https://github.com/godotengine/godot/assets/52464204/c973f015-fb3a-4a62-98e1-dda45347fbd3)

> This happens regardless of any configured parameters ....

You do not even need to use a get_next_path_position(). The scene configuration alone will make the actor get stuck. It is visually rather obvious that the navigation mesh has not enough margin baked when the character already clips in your visual mesh and collision shape standing on the navigation mesh edge. So either decrease the size of your character or increase the NavigationMesh `agent_radius` before baking.

**Comment by huwpascoe** [comment]
> It is visually rather obvious that the navigation mesh has not enough margin baked when the character already clips in your visual mesh and collision shape standing on the navigation mesh edge. So either decrease the size of your character or increase the NavigationMesh `agent_radius` before baking.

In the example, the agent_radius is set to 0.5, equal to the radius of the capsule collider. Does this mean agent_radius isn't supposed to represent the radius of the collider?
