### ISSUE TITLE
C# GlobalClass custom nodes inheriting from certain base node types are not registered unless script is in project root directory

### ISSUE THREAD

**Issue by jonashaan** [godotengine/godot#88240]
### Tested versions

- Reproducible in 4.2.stable

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 6800H with Radeon Graphics (16 Threads)

### Issue description

This seems to be an C# specific issue. When inheriting f. ex. RayCast3D, the [GlobalClass] annotated custom class will not be registered as a custom node, unless the C# script is saved in the project root directory. It is not added to the "global_script_class_cache.cfg" inside the ".godot" folder and is not visible inside the "Create new node" dialogue.

Using GDScript, the custom node registers anyway, no matter where it is saved.

For now (until I find more) this is only the case for C# scripts inheriting from RayCast3D. Inheriting from Node3D or CollisionShape3D for example does not trigger this bug.

Folder structure:
![files](https://github.com/godotengine/godot/assets/125254522/fd0c45eb-6249-44bb-aa84-fd48a05bd230)

TestRaycast3D.cs:
```cs
using Godot;

[GlobalClass]
public partial class TestRayCast3D : RayCast3D
{
	[Export]
	public int TestVar { get; set; }

	public override void _Ready() { }

	public override void _Process(double delta) { }
}
```

TestRaycast3D.cs not found inside dialogue (you see the GDScript variant is being registered):
![raycast_csharp_dialog](https://github.com/godotengine/godot/assets/125254522/5551326c-a649-46bf-9d93-574da8012ab0)

TestRayProjectRoot.cs (you see it's identical to the other C# example):
```cs
using Godot;

[GlobalClass]
public partial class TestRayProjectRoot : RayCast3D
{
    [Export]
    public int TestVar { get; set; }

    public override void _Ready() { }

    public override void _Process(double delta) { }
}
```

TestRayProjectRoot.cs is registered and shown in dialogue:
![raycast_in_project_root_csharp_dialog](https://github.com/godotengine/godot/assets/125254522/e2c52a98-33e8-4f69-8cd8-d8a7dd246300)

### Steps to reproduce

- Save the C# script with the [GlobalClass] annotated partial class inheriting from RayCast3D anywhere other than the project root folder

### Minimal reproduction project (MRP)

[Test_Raycast_Bug.zip](https://github.com/godotengine/godot/files/14237584/Test_Raycast_Bug.zip)

**Comment by zaevi** [comment]
Seems your class is TestRay**C**ast3D but the file named TestRay**c**ast3D.

The filename must match to classname and it's case-sensitive.

**Comment by jonashaan** [comment]
Yeah, this works. How in the world did I not see that? Thanks.
