### ISSUE TITLE
GPU Particles have very slow framerate on Wayland

### ISSUE THREAD

**Issue by pracedru** [godotengine/godot#88248]
### Tested versions

- Reproducible in: Godot v4.3.dev3

### System information

Godot v4.3.dev3.mono - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

GPU particles seem to run at something like 1/100 speed.

https://github.com/godotengine/godot/assets/15041324/7f55ec30-684d-4095-b2eb-878529415295

### Steps to reproduce

1. Open Godot with  --display-driver wayland.
2. Open MRP
3. Observe Particle systems

### Minimal reproduction project (MRP)

[mrpwp.zip](https://github.com/godotengine/godot/files/14239404/mrpwp.zip)

**Comment by DarioSamo** [comment]
That's curious because they literally can't run asynchronously from the rest of the rendering loop, and clearly your frame rate is fine. Perhaps the time where it sources the data from is broken in Wayland?

**Comment by pracedru** [comment]
> That's curious because they literally can't run asynchronously from the rest of the rendering loop, and clearly your frame rate is fine. Perhaps the time where it sources the data from for running the compute shader is broken in Wayland?

I was thinking that it wasn't performance related by deltatime related.

**Comment by Calinou** [comment]
This is likely delta time not being set correctly. Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/87750 locally?

**Comment by pracedru** [comment]
> This is likely due to the same cause as #87963. Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) #87750 locally?

I am building this branch now.

**Comment by pracedru** [comment]
Hi @Calinou, I can confirm that particles runs as expected with this branch under wayland.

**Comment by akien-mga** [comment]
I tested both `master` and `#87750, and strangely enough I can't reproduce the bug with the MRP here (but I could reproduce the bug from #87963).

Either way, if it works for @pracedru it's likely good to go anyway :)

**Comment by pracedru** [comment]
> @akien-mga uh right, that's another thing of that issue, it's metastable lol. It will fall in into either state: consistently refresh rate or into the tickrate for some reason.
> 
> Edit: Oh wait you said that you could reproduce the `TIME` thing though. Not sure what's goung on the, as long as it works 🤷

Could my recent change in hardware be the reason why it works on my end?

**Comment by pracedru** [comment]
No I just reproduced the issue with the official dev3 build on my current setup. 
So it seems to have been fixed with this branch.
