### ISSUE TITLE
Tree function get_item_area_rect return wrong value when some item are hiden inside the tree

### ISSUE THREAD

**Issue by didierGuieu** [godotengine/godot#88251]
### Tested versions

- Reproductible in 4.2.1 stable version

### System information

MacOs 14.2.1 Godot 4.2.1 Forward +

### Issue description

the function get_item_area_rect ignore the visibility of the subitem. it calculate the rect without cheking the visibility of the tree items.

### Steps to reproduce

To reproduce: Just run the attached project.

### Minimal reproduction project (MRP)

[tree issue.zip](https://github.com/godotengine/godot/files/14239820/tree.issue.zip)

**Comment by smix8** [comment]
Same as https://github.com/godotengine/godot/issues/88251.

**Comment by didierGuieu** [comment]
Not really. #71997 is related to the theme. This issue is related to a miscalculation in the function.
I agree that we have 2 different bugs inside the same function.

**Comment by FaycalElOuariachi** [comment]
Hi,
I tried to fix it in #88300.
It works with your minimal reproduction project. I hope it'll be accepted (if I didn't do anything wrong) and that it will work on your real project.
