### ISSUE TITLE
[4.3.dev] Drag to Instantiate in 3D will no longer instantiate scene at cursor position.

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#88259]
### Tested versions

v4.3.dev [f317cc713aa4dbcee2efa10db764473a56680be7]

### System information

Godot v4.3.dev (f317cc713) - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Bisected to: https://github.com/godotengine/godot/pull/86659

v4.3.dev [f317cc713aa4dbcee2efa10db764473a56680be7]

https://github.com/godotengine/godot/assets/105675984/f389d92d-7984-4ca3-9302-380d40f9ce73

v4.2.1.stable.mono.official [b09f793f5]

https://github.com/godotengine/godot/assets/105675984/90bc8834-4a3b-47e7-b016-b337d4f1b45a

### Steps to reproduce

Drag a scene into the editor viewport. 

### Minimal reproduction project (MRP)

N/A

**Comment by MajorMcDoom** [comment]
I just pushed a fix here: #88269
