### ISSUE TITLE
Need options for bounding boxes in Editor

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8825]
**Operating system or device - Godot version:**
arch + ubuntu

**Issue description:**
Having many hidden objects in the scene, all the bounding boxes are visible.
Would be good to have the following options:
Dont display bounding boxes
Display bounding box only on selected objects
Display bounding box on visible objects
Display all bounding boxes

![bounding_box](https://cloud.githubusercontent.com/assets/650506/26233446/9994ced2-3c9c-11e7-8195-0faf8072d7fd.jpg)

**Comment by kubecz3k** [comment]
I'm in the process of revisiting old issues. Is this one still valid? I don't know how to enable rendering of the bounding boxes for the models in the first place...

**Comment by KoBeWi** [comment]
I also tried to enable the bounding boxes. The closest I got was enabling visible collision shapes, but that's only the blue ones. The yellow shapes remain a mystery.

@Gibbz 
@hubbyist (from upvote)
I'm closing the issue for inactivity. I could reopen it if you provide more information.
