### ISSUE TITLE
Godot doesn't scale the game loading banner (leaves transparent fields)

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot#88256]
### Tested versions

4.0-4.2 stable

### System information

Godot v4.2.1.stable - Debian12 + sway (wayland with enabled xwayland)

### Issue description

Godot doesn't scale the game loading banner into whole window in sway (I suppose because it doesn't expect to be run in tiling window manager)

![screen-1707725412](https://github.com/godotengine/godot/assets/97330399/43e77293-ff63-45b1-ac9a-53f462928188)

### Steps to reproduce

Just open godot in similar environment

### Minimal reproduction project (MRP)

You even don't need the project. Just open godot in the similar environment

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83693, as this is due to the same cause.
