### ISSUE TITLE
invalid windows executable when dev_build is enabled on windows with mingw64

### ISSUE THREAD

**Issue by enetheru** [godotengine/godot#88261]
### Tested versions

Tested Versions:
v4.3.dev.custom_build [4e990cd7e] - fail
v4.2.2.rc.custom_build [474589eb8] - fail
v4.1.4.rc.custom_build [77598f070] - success

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 6800HS Creator Edition (16 Threads)

### Issue description

Compiling on windows with mingw64 produces an invalid executable only when dev_build=yes is specified.
The compile runs without error, but the result is unusable.
I can successfully run Godot without this flag, including when I specify debug_symbols=yes.
I can successfully run godot with dev_build=yes on 4.1.4
Because there aren't any errors during the compilation, only on running the resulting executable there isn't much to note.

### Steps to reproduce

I remove .gitignore and run git clean -fd to ensure no artifacts from previous builds.
scons dev_build=yes
.\bin\godot.windows.editor.dev.x86_64.exe
```
Program 'godot.windows.editor.dev.x86_64.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .\bin\godot.windows.editor.dev.x86_64.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\bin\godot.windows.editor.dev.x86_64.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Check the executable size, if it's larger than 1.9 GB strip (or use separate, `separate_debug_symbols=yes`) debug symbols. Windows have executable size limited and won't be able to run it if it's above the limit.

**Comment by enetheru** [comment]
OMG, thank you.
