### ISSUE TITLE
DOF enabled disables glow/bloom effect

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8827]
**Operating system or device - Godot version:**
Ubuntu + arch

**Issue description:**
Enable DOF in the world env and notice the bloom dissapears

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by sketchyfun** [comment]
possibly related? #9756

**Comment by djrm** [comment]
i think this was fixed, unable to reproduce

**Comment by reduz** [comment]
ah yeah, it's fixed, closing
