### ISSUE TITLE
LOD system does not recognize when camera enters AABB (solution provided)

### ISSUE THREAD

**Issue by roalyr** [godotengine/godot#88273]
### Tested versions

4.x as of https://github.com/godotengine/godot/commit/2d0ee20ff30461b6b10f6fdfba87511a0ebc6642

### System information

Any platform

### Issue description

In the LOD system:

```
// Get the LOD support points on the mesh AABB.
Vector3 lod_support_min = inst->transformed_aabb.get_support(p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));
Vector3 lod_support_max = inst->transformed_aabb.get_support(-p_render_data->scene_data->cam_transform.basis.get_column(Vector3::AXIS_Z));

// Get the distances to those points on the AABB from the camera origin.
float distance_min = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_min);
float distance_max = (float)p_render_data->scene_data->cam_transform.origin.distance_to(lod_support_max);
```
Both distances are always positive values, so the condition that checks if camera is inside AABB:

```
if (distance_min * distance_max < 0.0) {
	//crossing plane
	distance = 0.0;
}
```

Never triggers.

Video:  https://www.youtube.com/watch?v=j_rp_k5rDPA

## Solution

To fix the issue - supplement `distance_min` with a sign, for example: https://github.com/roalyr/godot-for-3d-open-worlds/commit/afbdb543f6b18a79bd4cc61c597f9604421b042e
Video:  https://www.youtube.com/watch?v=LF21eYlb44Y

I am not opening a PR because I am not sure if this approach is the best.

### Steps to reproduce

Set LOD bias to a really low value (0.1) and move camera inside AABB of a mesh, rotate the view.

### Minimal reproduction project (MRP)

Irrelevant

**Comment by roalyr** [comment]
Also
```
} else if (distance_max <= 0.0) {
					distance = -distance_max;

}
```
needs to be addressed in the same fashion, because `distance_max` doesn't get negative either.

**Comment by roalyr** [comment]
Also
```
} else if (distance_max <= 0.0) {
					distance = -distance_max;

}
```
needs to be addressed in the same fashion, because `distance_max` doesn't get negative either.

In fact, it is questionable why `distance_max` is used at all. Why not origin?

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/79590
