### ISSUE TITLE
The window menu (alt + space menu) is disabled on windows

### ISSUE THREAD

**Issue by ManpreetXSingh** [godotengine/godot#88277]
### Tested versions

- 4.x
- 3.5 stable

### System information

Windows 11

### Issue description

Pressing `alt + space` does not bring up the window menu on windows. It works as expected on linux.
![image](https://github.com/godotengine/godot/assets/63737630/81671865-17f6-40ba-bad8-3e8fd3acaf1b)

It is disabled here:
https://github.com/godotengine/godot/blob/dfe226b93346c208787728eceecc2c64d81a9553/platform/windows/display_server_windows.cpp#L3348-L3351

It appears that this functionality may have been disabled due to the frequent use of the alt and space keys in games. Unfortunately, this limitation makes it extremely challenging for non-gaming applications developed with Godot to incorporate this feature.

### Steps to reproduce

- Open the godot editor
- Press `alt + space`

### Minimal reproduction project (MRP)

Not required

**Comment by Calinou** [comment]
This should probably be toggled with a project setting that is disabled by default, as <kbd>Alt + Space</kbd> is problematic for a lot of games. There should be a way to enable its use for non-game applications still.

**Comment by Mickeon** [comment]
It's definitely unreasonable that this is always disabled in the editor, as well.
