### ISSUE TITLE
Changing Object Class of new Key/Value form dictionary argument while the Object is opened will crash Godot

### ISSUE THREAD

**Issue by ajreckof** [godotengine/godot#88286]
### Tested versions

reproducible in : v4.3.dev.custom_build [71a6ee64a], 4.2.1

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When you change the class of the new value/key of dictionary editor while Object Editor is opened Godot will crash.

https://github.com/godotengine/godot/assets/66184050/e292092b-fa22-4909-bb9b-219d8cb37ff8

### Steps to reproduce

1. create a script that export a dict 
2. on the new key/value change type to Object
3. choose a resource
4. open the editor so that an Inspector is shown
5. change the object to another class of resource 
6. Godot crashes

### Minimal reproduction project (MRP)

N/A

**Comment by oxi-dev0** [comment]
I can reproduce on Windows 11, v4.3.dev.custom_build [a9bb8509f], it only seems to occur in relation to the Translation type. Here is the error:
![image](https://github.com/godotengine/godot/assets/33568643/4d7710ba-f562-4d2e-9b08-650a32cd74dc)

**Comment by oxi-dev0** [comment]
Also, the crash is unreliable, but a consistant internal error every time the type is switched is:
![image](https://github.com/godotengine/godot/assets/33568643/05f84dc9-8289-4971-9e5e-0b94b24ff48f)

**Comment by ajreckof** [comment]
I can reproduce with other types then translation see here. 

https://github.com/godotengine/godot/assets/66184050/a17d32d8-c9c1-41bb-8e73-0ed53dd0ce51

The difference might be due to different memory management between OS but the crash is 100% reliable for me

**Comment by oxi-dev0** [comment]
Yes it seems to be when the object is cleared before the EditorInspector instance's edit method is called, the instance thinks the object is still valid as its pointer has not been cleared, but the object's memory is invalid so it crashes. I don't know the best solution to tackle this problem so I will just leave this to someone else but it seems to be a race condition between the ref for the old object freeing it and the editor inspector receiving the message to edit the new object

**Comment by ajreckof** [comment]
Since this only happens on new key/value it is most likely linked to the fact new key/value are not stored in the dict but on some C++ properties which I guess is not holding the reference right. I'll try and take a look next week.
