### ISSUE TITLE
Editor Global/Custom Font does not work

### ISSUE THREAD

**Issue by insraq** [godotengine/godot#8828]
**Operating system or device - Godot version:**
macOS 10.12.5 / Godot 2.1.3.stable.official

**Issue description:**
Setting the `Global/Custom Font` does not seem to work on Mac (Although I have not tested other OS). `Editor/Font` settings works perfectly.

I have restarted Godot and tried other workarounds (like also setting the deprecated Global/Font settings) but none of them work.

**Steps to reproduce:**
As stated above (also see attached screenshot)

**Link to minimal example project:**
N/A

<img width="1920" alt="jietu20170519-161528" src="https://cloud.githubusercontent.com/assets/608221/26239138/65eff360-3cae-11e7-9c83-07a167d74d6c.png">

￼

**Comment by akien-mga** [comment]
I think that setting expects a TTF font, not a bitmap one.

**Comment by insraq** [comment]
@akien-mga The editor suggests an *.fnt format. And after I set a TTF, it still does not work.
<img width="1920" alt="jietu20170519-163532" src="https://cloud.githubusercontent.com/assets/608221/26239834/43a74d32-3cb1-11e7-8e2f-717e2dcad53b.png">

**Comment by akien-mga** [comment]
How about the "Font" setting further down that list?

**Comment by insraq** [comment]
I've got a Windows machine at home. Will try on Windows later.

**Comment by insraq** [comment]
Tried on Windows. Doesn't work either. Am I doing something wrong?

![screenshot_2](https://cloud.githubusercontent.com/assets/608221/26246888/f1834444-3ccd-11e7-829a-7861f97b8dcf.png)

**Comment by akien-mga** [comment]
I don't know if you're doing something wrong, but at the very least the feature is non-intuitive, if not broken. Can you try to place the font in your project folder and use a `res://` path maybe?

**Comment by insraq** [comment]
@akien-mga Tried that. Not working either.

**Comment by Noshyaar** [comment]
Duplicated by #10866 and fixed by #11512 in 3.0?

**Comment by r3d9u11** [comment]
@Noshyaar Does this feature works? I tried to set custom .tres file:
```
[gd_resource type="Theme" load_steps=3 format=2]

[ext_resource path="res://0_Global/Assets/Fonts/cmunorm.ttf" type="DynamicFontData" id=1]

[sub_resource type="DynamicFont" id=1]

size = 21
use_mipmaps = false
use_filter = false
font_data = ExtResource( 1 )
_sections_unfolded = [ "Font", "Settings" ]

[resource]

default_font = SubResource( 1 )
_sections_unfolded = [ "Font", "Settings" ]

```
And didn't see any effect, default font wasn't changed

**Comment by Noshyaar** [comment]
6c569c9
It's very weird. The custom font is set for a split second:

![screenshot from 2018-08-03 11-45-03](https://user-images.githubusercontent.com/26753932/43624660-1030ba52-9713-11e8-8396-e95bcd95023e.png)

then it reverts to default font. I suspect that it overrides the custom font when it applies editor theme.

![image](https://user-images.githubusercontent.com/26753932/43624569-7977fa94-9712-11e8-84eb-e9a5aba3c228.png)
