### ISSUE TITLE
Jumping to description from help search will scroll to bottom if class page is short

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88281]
### Tested versions

4.3 dev3
Not sure when it started, but I think it's recent.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you search help and jump to member, the page will open scrolled to bottom, regardless where the item is located. This seems to only happen in short pages that load "instantly".

https://github.com/godotengine/godot/assets/2223172/5602b5d8-8f92-4bb1-80ee-3a2b6118aa29

### Steps to reproduce

1. Press F1
2. Search for `is_echo()`
3. Go to method

### Minimal reproduction project (MRP)

N/A

**Comment by Maran23** [comment]
Can confirm, must be a regression introduced after 4.2.1. When left clicking into some documentation from the code editor, I have the same behaviour sometimes.
