### ISSUE TITLE
`SpinSlider`s can't be dragged on some nodes

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#88294]
### Tested versions

Reproducible in master: v4.3.dev.custom_build [e92d55bbf]
**Not** reproducible in v4.2.1.stable.official [b09f793f5]

### System information

macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

For some reason sliders are undraggable on some nodes because they immediately stop being dragged after one frame:

https://github.com/godotengine/godot/assets/60579014/8d3eb35f-fc9e-4bd3-8b82-e108e13c8509

This doesn't happen in 4.2:

https://github.com/godotengine/godot/assets/60579014/2b3cb29f-c723-414f-8894-7bec79fdbc5c

### Steps to reproduce

Create a DirectionalLight3D node and drag any of its transform properties

What's interesting is that it doesn't happen for any node, for example there's no issue when trying to do this with `MeshInstance3D`, but there's an issue with `DirectionalLight3D`. And I saw that in some other nodes too

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Probably related:
* https://github.com/godotengine/godot/issues/88176

Can you try with [41564aa]?

**Comment by passivestar** [comment]
> Can you try with [https://github.com/godotengine/godot/commit/41564aaf7708b0bf594f745dd2448a54dd687cc5]?

This works

> And with: https://github.com/godotengine/godot/pull/88182

This works too 👍
