### ISSUE TITLE
WorldEnvironment nodes stop working after exporting to web

### ISSUE THREAD

**Issue by WilleIshere** [godotengine/godot#88292]
### Tested versions

In editor
![image](https://github.com/godotengine/godot/assets/60477853/52dc44e5-fe89-4374-9837-e0a1e3beeb35)
Exported:
![image](https://github.com/godotengine/godot/assets/60477853/6ece5b05-4617-4d31-b98f-4cbfd7c23fda)

### System information

Windows 10 - Godot 4.3 dev3

### Issue description

It does nothing once exported

### Steps to reproduce

Add worldenvironment node

### Minimal reproduction project (MRP)

.

**Comment by WilleIshere** [comment]
If its not obvious the glow effect disappeared

**Comment by Calinou** [comment]
Glow is currently not supported in the Compatibility rendering method, which is being implemented in https://github.com/godotengine/godot/pull/87360. Compatibility is always used in the web export, no matter which rendering method you use on desktop or mobile platforms.

Closing in favor of https://github.com/godotengine/godot/issues/85375.
