### ISSUE TITLE
Disable anti-aliasing in Script Editor

### ISSUE THREAD

**Issue by luboslenco** [godotengine/godot#883]
Left one is without anti-aliasing and for some reason much easier for me to read. On the picture a Courier New font is imported. I also tried to check 'Disable Filter' in font import settings but the result was the same. Default font in script editor is also anti-aliased.

I believe most of the people prefer anti-aliased fonts but having ability to disable it would be great for the rest of us that struggle with it:)

Running on OS X Yosemite 

Thanks,
Lubos

![scr](https://cloud.githubusercontent.com/assets/3685704/5050401/42ad89e2-6c2e-11e4-840e-c34ed090c238.png)

**Comment by kubecz3k** [comment]
Tried to investigate but I'm blind as a mole. Can you @luboslenco confirm if it's fixed now?

**Comment by akien-mga** [comment]
This might be easier to do now that we're using FreeType and DynamicFonts.

**Comment by akien-mga** [comment]
Should be easy to add an editor option to tweak the default aliasing for FreeType.

**Comment by ivodopiviz** [comment]
So I've been looking at this and I'm not so sure is a junior job really. Adding the setting itself is trivial and even getting the entirety of Godot to disable anti-alias is easy as well, but getting the right place where to put the flag itself and getting the whole thing right isn't.

The important part, at least initially, is to pass FT_RENDER_MODE_MONO to FT_Render_Glyph. This is done by DynamicFontAtSize so we should have a 'antialias' flag there to change the render mode as needed. Should that flag only be set in that class? Does the script editor use its own font?

Those questions aside, the default font currently used by Godot does, in fact, look very bad without anti-alias.

In any case, I'm not sure if it's possible to assign issues to non-team members but I'll work on this :)

**Comment by Calinou** [comment]
> Does the script editor use its own font?

Yes, it uses the [Hack](https://sourcefoundry.org/hack/) font by default.

**Comment by ivodopiviz** [comment]
Oh , that's a good reference, thank you

**Comment by akien-mga** [comment]
Fixed by #23645.
