### ISSUE TITLE
Ensure all Godot API's methods are lower case

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8830]
Almost all methods of the Godot API are lower case, e.g. `set_position()`. There are a few exceptions such as `Object.get_instance_ID()` or `OS.get_unique_ID()` which break this principle (and cause mistakes such as https://github.com/FrogSquare/GodotFireBase/issues/1).

I'd have to check exactly what methods would be concerned, but if it's only 2 or 3, I would propose to rename them in 3.0. So far I saw:
- `Object.XL_MESSAGE()` -> drop it, deprecated
- `Object.get_instance_ID()` -> `get_instance_id()`
- `OS.get_unique_ID()` -> `get_unique_id()`

WDYT?

**Comment by reduz** [comment]
anyone up for this? seems easy

**Comment by akien-mga** [comment]
I'm on it, with some regex-fu it should be easy to spot them all.

**Comment by reduz** [comment]
@akien-mga did you have time to double check? :)

**Comment by akien-mga** [comment]
All fixed AFAICT.
