### ISSUE TITLE
animation in dae causes editor crash

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8831]
**Operating system or device - Godot version:**
ubuntu + arch

**Issue description:**
open a dae with animation
click play
*boom crash*

Some snippet of error from command line:
ERROR: get_parent_class: Condition ' !ti ' is true. returned: StringName()
   At: core/class_db.cpp:274.
ERROR: instance_remove_skeleton: Condition ' !skeleton ' is true.
   At: drivers/gles3/rasterizer_storage_gles3.cpp:5330.

**Comment by Gibbz** [comment]
added animation for testing purpose:

[Animation-BounceAlong-A.dae.zip](https://github.com/godotengine/godot/files/1016052/Animation-BounceAlong-A.dae.zip)

**Comment by ProbDenis** [comment]
I can confirm that. Skeletal animations imported from a .dae sometimes crash with the errors above. Interesting thing is that in my case it didn't happen immediately. I imported a .dae, then played a little with the animations and made a few changes, and everything worked well. At some point though, trying to edit or play the animations started crashing the editor. Animations that don't involve the skeleton could still be selected, others mostly crashed - however, if I just run the game, all the animations work flawlessly.

**Comment by ProbDenis** [comment]
Another interesting observation: Re-importing the .dae file fixed the issue for now.

**Comment by reduz** [comment]
this was fixed, closing
