### ISSUE TITLE
Making definition for multiple Android modules more intuitive in cfg file

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8834]
**Godot version:**
master / 3.0 and later

The current way to define several Android modules in your project.godot file is with a single String of comma-separated identifiers, e.g.:
```
[android]
modules = "org/godotengine/godot/SQLBridge,org/godotengine/godot/FireBase" 
```
The way it is parsed is defined here: https://github.com/godotengine/godot/blob/df61dc4b2bd54a5a40c515493c76f5a458e5b541/platform/android/java_glue.cpp#L943

To make things more intuitive, as used in TSCN files and other INI-like cfg files in Godot, I would suggest to use a proper Array:
```
[android]
modules = ["org/godotengine/godot/SQLBridge", "org/godotengine/godot/FireBase"]
```

This breaks compatibility, so of course only for master/3.0.

**Comment by punto-** [comment]
Are we using the same code to parse the values on tscn and cfg files at the
moment? it'd be nice to be able to use all the types on the cfg file

**Comment by ret80** [comment]
I'm not sure that this is possible with ini files, but it would be great if there was an opportunity to transfer a long string to several.
```[android]
modules = [
"org/godotengine/godot/SQLBridge",
 "org/godotengine/godot/FireBase"
]
```

**Comment by bojidar-bg** [comment]
@ret80 Yes, `.tscn` format already allows this, so I guess it would work fine.

**Comment by akien-mga** [comment]
It's now or never to do this compatibility breakage, if anyone is up to it.

**Comment by Jerome67000** [comment]
I can do that but I'm not familiar with godot modules, someone can make me a small minimal project with more than 1 module so I can test ?

**Comment by Jerome67000** [comment]
@akien-mga to add android modules, the only way is to go at Project Settings and add a Category named "Android" with list of module separated with a `,` in Property ?

**Comment by Jerome67000** [comment]
is it still an junior job if we must add a "Array" type of attribute ? must think about how to display it, new view managing multiple entry ? seems not to be so easy...

**Comment by akien-mga** [comment]
Well arrays are already supported in ConfigFile (and project.godot), see e.g. `gdnative/singletons` or the `input` stuff:
```
[input]

jump=[ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"pressed":false,"scancode":$
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"pressed":false,"scancode":16777$
 ]
duck=[ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"alt":false,"shift":false,"control":false,"meta":false,"command":false,"pressed":false,"scancode":$
 ]
```

The code for Android modules should be streamlined to use the same feature.

**Comment by Jerome67000** [comment]
Yes for this part its OK, but for the UI in the Project Settings, Array aren't supported

**Comment by akien-mga** [comment]
Indeed, so maybe not so junior :D

**Comment by akien-mga** [comment]
Time is running out for this issue :) If we can't do it for 3.0, then we'll have to wait for 4.0, or give up on the idea.

**Comment by Jerome67000** [comment]
IMO it is a lot of work for an little change.

**Comment by akien-mga** [comment]
Yeah I've discussed it with @reduz and the UI part of the change is not worth it. Instead, the should be an Android template builder in the future that can better handle this stuff.
