### ISSUE TITLE
MacOSX scroll wheel UP/DOWN not firing when holding shift

### ISSUE THREAD

**Issue by artvel** [godotengine/godot#88356]
### Tested versions

Reproducible in 4.3.dev3 on MacOSX

It works on Windows

### System information

MacOSX

### Issue description

When holding shift it is not possible to get mouse wheel inputs on MacOSX.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
`Shift + Scroll` will trigger horizontal scroll input events (`WHEEL_LEFT` / `WHEEL_RIGHT`) instead of vertical, this is standard behavior for macOS.

**Comment by artvel** [comment]
It shouldn't interfere with Godot inputs though.

**Comment by artvel** [comment]
I know, but maybe those mac features need to be disabled when Godot is focused and enabled when it is not. Because from a gamers perspective it means that he can't zoom in or out while running without any workarounds.

**Comment by AThousandShips** [comment]
That would break compatibility and user interface, and it is used on all platforms

You can just work around it easily but handling the desired feature is not as easy, also how should it handle actual side scroll like a tilt scroll?

**Comment by artvel** [comment]
The way it is now it is breaking compatibility on my side as I can not play the game on mac the same way as I can on windows.
No side scroll needed so far only `MOUSE_BUTTON_WHEEL_UP` and `MOUSE_BUTTON_WHEEL_DOWN`.
How could I work around it easily?

**Comment by AThousandShips** [comment]
You're right it works differently on windows, but that's something you need to navigate generally

The workaround is to just use the horizontal scroll as well, for those purposes, that just means listening to both types of scroll

**Comment by artvel** [comment]
Sure, I can do that. 
But I don't think having mac specific inputs ingame is the way to go.

If there is no intention of keeping the input behaviour equally over all supported systems, this issue can be considered as `Close as not planned` from my perspective.

Thanks!

**Comment by bruvzg** [comment]
This is how input works on OS level, Godot simply receives a scroll event with X, Y, and Z deltas without any indication what action caused it, you can't enable/disable it. If you want to have non-standard behavior, you should handle it in your project (or allow users to configure it). It's not the only difference, and you can't have exactly the same input on different platforms: e.g., Left click+Control is Right click, there's no Num Lock and Scroll Lock, Mac keyboard have different set of modifier keys in the different order, etc.

**Comment by Mickeon** [comment]
If **MOUSE_BUTTON_WHEEL_RIGHT** and **MOUSE_BUTTON_WHEEL_LEFT** are triggered consistently those two descriptions may be good candidates to fit this note.

Keep in mind @artvel, Godot like many multi-platform applications, do their best to ensure that input is consistent across all platforms. But there are a few exceptions like these. So let's be clear here again, this is behavior that macOS itself is intercepting, and Godot cannot change that...

...But it is possible to work around it in a few different ways.
On top of my head, the simplest one involves checking for **MOUSE_BUTTON_WHEEL_RIGHT** and **MOUSE_BUTTON_WHEEL_LEFT**, instead, if you know **Shift** is being held down. If you want to ensure this only happens on macOS, you can use `OS.has_feature()`.
