### ISSUE TITLE
Exported GDScript: Parse Error: Class "XXXXXX" hides a global script class

### ISSUE THREAD

**Issue by wpbirney** [godotengine/godot#88353]
### Tested versions

- Reproducible in: 4.3-dev [907db8eeb]

### System information

Godot v4.3.dev (907db8eeb) - Void #1 SMP PREEMPT_DYNAMIC Wed Feb  7 19:24:35 UTC 2024 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) () - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When using named classes with:

`class_name SmokePickup`

Works and runs fine in editor but when i export the pck and try to run that i get:

```
SCRIPT ERROR: Parse Error: Class "XXXPlayer" hides a global script class.
          at: GDScript::reload (res://PlayerController.gdc:1)
ERROR: Failed to load script "res://PlayerController.gdc" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2817)
SCRIPT ERROR: Parse Error: Class "SmokePickup" hides a global script class.
          at: GDScript::reload (res://pickups/smoke_pickup.gdc:1)
```

Issue only occurs when running the game with an exported .pck or .zip that has GDScript Export Mode set to Compressed Binary tokens or Binary Tokens. Does not happen when set to Text.

### Steps to reproduce

- Create a empty project 
- Attach a script to a node and give script a class name
- Set a main scene
- export a pck and run directly with a binary built using `scons target=template_release`

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
* Probably related to #87634.

CC @vnen
