### ISSUE TITLE
HTML5 icon needs update

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8836]
**Godot version: 3.0**

**Issue description:**
This :)
"Html5 icon has no highdpi and does not fit (style wise)."

**Comment by Tajnymag** [comment]
I'm guessing [this](https://www.w3.org/html/logo/#downloads) could be used. Simply throwing in a higher resolution version of the image is probably not sufficient though. Better idea would be to use svg formatted logos in all export templates. Unfortunately, I'm not that skilled programmer to do so by myself.

**Comment by Calinou** [comment]
Which HTML5 icon are you referring to?

> Better idea would be to use svg formatted logos in all export templates.

Godot itself does not support SVG rendering or rasterization, as this is a very complex topic. There was ongoing work on integrating [nanosvg](https://github.com/memononen/nanosvg) into the Godot editor (for use with icons), but I'm not sure if there has been any progress on it recently.

**Comment by n-pigeon** [comment]
@Calinou
It refers to HTML5 icon in top bar (play game, play scene, remote and so on).

**Comment by Bugsbane** [comment]
A couple of drafts (complete with glitches):
![html5 logos](https://cloud.githubusercontent.com/assets/401733/26781991/56380f70-49bf-11e7-8a81-c0fb16e6c674.png)

Personally, F is my favorite, although I quite like C too. While including the "HTML" letters looks good when it's displayed at this size, I find them completely unreadable at the size it's presented in the editor (it just looks like a squiggly line).

**Comment by nunodonato** [comment]
I also like the letters, but if the icon is too small its not worth having them.
I'd go with C but perhaps reducing the contrast between the 2 colors just a little bit, its too strong now

**Comment by Bugsbane** [comment]
Yep. I agree. So here's what that looks like:

![html5 logo-f2](https://cloud.githubusercontent.com/assets/401733/26788077/0d3a1280-49da-11e7-854f-47e618ee2d74.png)

So does anyone know what size the final image should be?

**Comment by Bugsbane** [comment]
If anyone can point me to where I'd find the current icon file ( @n-pigeon ?), then I can actually start matching the specs on that and preparing a commit/screenshot for everyone to try/look at.

**Comment by Bugsbane** [comment]
Hmm... So I hunted down where the original file seems to be (the file helpfully named "logo.png" along with a bunch of other logo.png files). I can easily replace this with a monochrome version, which will look better on the main editor window HOWEVER... I suspect this file is probably also used for the export window, where all of the other logos (mac, windows etc) are in color. If both places use the same file, then a monochome version will look out of place there.

![lintemplates](https://user-images.githubusercontent.com/401733/26871255-9528eac4-4b40-11e7-8c48-a75626d9554f.png)

If this is the case, then what we really need is not just to update the image file (which I can do), but to set the icon in the editor for "select device" to use a new icon file (which would be the monochrome version). I'm an artist, not a coder, so changing the code path of the icon in the editor window is beyond my current skills.

**Comment by toger5** [comment]
@Bugsbane If you could provide icons for each platform (maybe all black and white so we can adapt them in code to a theme... thoughts on that?) would be great. Someone will update them. If no-one wants to I also might look into it.
just make sure you get the resolution right. Don't know how HIdpi works with those. Vector graphics would be best so you can render them out in all needed resolutions

**Comment by Bugsbane** [comment]
> just make sure you get the resolution right. Don't know how HIdpi works with those.

The current files appear to be 32x32px png's. Not sure if that's enough for hidpi (probably OK in the editor interface where they're displayed small. Possibly not in the exporter window where they're large).

> If you could provide icons for each platform (maybe all black and white so we can adapt them in code to a theme... thoughts on that?)

I can do it. I'm fine with doing that. The only thing is, from a design perspective, I would suggest that while black and white is best to maintain consistency in the editor window... that the current color icons still work best in the exporter window. I would actually suggest not changing them, and only changing the icon in the editor window.

Designwise, the difference is that in the editor window, the primary content is what's in the main window section (eg 2d/3d/script view), so you want monochrome icons to avoid distracting from that, which is what's done with the other icons. In the exporter window, the platforms you're exporting to is the primary decision, so you want attention drawn to it, thus the large, color icons work better. So Godot 3's current design language is good. The coloured editor window icon just doesn't follow it.

Anyway, to make my long explanation short, I would recommend that we keep the exporter window icons the same and just give the editor window icon it's own separate icon file, which I can provide.

**Comment by toger5** [comment]
maybe we than can at least make them look less outdated:
![](https://www.apple.com/hk/en/macos/images/og.jpg?201705142356+PSCdV4a4uhFWEsZuNVqN9DL1TtCwFs28oh0wQJxs411Iq5W6qyAbdRtZtAN6VAptKI9aiLQ8wmPIWseVNnjvx8hUqCtIyZmXNMQ7Q0NWVKppddEWaHF1qvg0v4XEjRKkqKPWykrL0ei0QWsKNlV4KJfeIysrRqwVzUCnW+8T8zECaE2BLtmwtzPk5UusFu8LOp1cxVEAq1KXNj5ZU5CXlfMYMeY5PqvQlSgGVpXS1qiMF68VlFGnkVfapygTV5KWvjhgVSl9fKgO/11YWPhiaw/rW1O/oFP/UpcoRrQJGij76AR7IUbOWOgCQwYD66UmS4SoFLGd0QM99ggfjy7fVCC9DMIWoeydYz/yvYVfk/HRuGaRBqTFTWfEu7i4+PrRu3fw41d02Iu+Ih3RLihQGEOUHWTo60i9fUwd4WOOzDilItoFOS6rNuRo+eJiuXLLkVzBR0Ym64wKnJ7AHKOumx+XF5c/mgkHqGcUbYMYmz1I2VpcXFw+v9Zkni+jAxZriSLg9ASOIHV7hDQtOlr4lebgr0YcPwcdzoaXI0jUOD9gU9pYvazh5x+Yu+gY0TaIYe4IY9T/EB/GZWp+wM/VtCsSgdNKLYUH3cGuRpqiaCP8zNG5prNE2yDF5dOmqJvYlqTrBn7cVPlms6DsQFy+OBXF/GVra+sXc/LAOxsUbdyB6g7ytbW5if/LWaIIKBs3bm2Kvflka+sJ/rdpc082O9oU86cnY37KYi7RPgjJIFRFeTEmi5nAaLvqpPc76r3j8actVKb/Q6AStSJOU01uQdGmGhY3ygus7YXCP5MB5RMNJn+s5s9Px/ycxVyifRBicmebtrkdatv+VeOdy5gZbYqz/XRn+9Wr7Z2n2w5vnYLR5vJqM3/f2dn53Zw88GqDcpfAq81+9XJn52VFUSr48ZVdaiNBd16/fPkaL2rar/iZo8+GtjnJ4MCyf1tdfb2m4ufq2uvV1d9si2c+SbQNYniiNOy1pdXVVWusyrLQ06U1m2tC0TaI4ckOvfvN0tI3XT3qKybAvEw5J3MEaSwhTzf5Fawhb0sGxw8CzlswHEUV/LixsfFcu9Zkac/RgR8D9hnhvOHnMvcEud/b2Og51vUEkuXgI32fdUYJTCNlb6WK0/v22953d4pc/g4fcxRWbaJdUMCqLfi+1+s9v1eRwXN08HvWMoWkTZGYCH5Y7/XWa8bdo0YNH/0hYJsTztukqCdUWSK0uu2jo3b/gXOlj493LZY5q3A6AuoJLNoM/2h9vf0uIquCd+319SPfeHgmXRugjoAWNwaCd4ft9pEfdco/arcPo4SmI9oEFQyLm98/aLcPupFXKl18rh+pNBlIS9vcnElfpdXDw8ODv2MyKvj7AJ1mmBTKa5QTqCMM/rk8PDiKrcPg6ODw8h/qMq2K9kAJbdvzd48vL4+d2MssB5/fpS1TOPfxIZRVanWRlc5uQjYFux3kjXIXAq1GKavUCN4cXx7vJ9ZgsI+GvAmodiHQanRuTqcJL9jrHB93qolKjCoes0e1vMH5AOoVNDteq/us03nWTylApY9H0ZQprL1uCEU1WZ1Opz4IpBTTwaCOBlJog/N6+A1qrUpIsP+sU3/rpw/039Y7z/YD0nlrUD79cQfS6Pzd+Xp9vkuirYtH7hKMDBFtgAmbLDbJGSIXe0Q5FOwhb0NHIpsZ0osftyALLngzrA//CIhUSMEfaPAbwjIVHT8jNsnq5v9Jk0Bhav5JUqY1oMlGlG4G5XI1WQgNgqGio2cmvZlKqDnWh38RN0dU03+hfHvrp2YnzDYakhpcMEDJUzcISxQjGeiC+UGqaFivT97FrdQSMfq45PpG8iiWayoAbxBuUBK9VSWUOcNBQGOtVgsGqEzrUjXRGqxXdR+QLCBcpxIFPKQ6WQ8TB4mOmxMzId0mXVGis1arSZPuGz+iAu51tvso8dE78+M9GK015Bvv9eadeN/ASxQTW4KTHT+9NXRpeGcRdxrulu2GuG7q780Ph8OElEkA3SwMh/N7MYkKu4teYUd6qzr7g8GAbu9xg9FHF+87kZlcAXtXdZeYXYiPkGopO7toKjUJXx19rgALW0jVqUwNpwgL24TpWatURMeaIe70rBWiHVzhTqlMnUJZm5a3olmbjrfiWZuGtyJaw30hV3FOsbrBLWp5aoP+WlECVSc3CrTLfYiSl7XC3FFFo+ZjDfDbVGSgxpA5hW0Gt9Gztgbvw39MZJtwM5FqIXJ21uD8cnIGuFI20iD9km0muBns4SB+Npcbs8YnrQb+zVBGTI6Mg/ebGhniGmzS4PwfePJCo96OVED+vdbMcXUKcxVQf0soZ1yNaJmrgv3z3fnhaokLnVEqi8dVZat6p2YrVUtWS2MlJSUlJSUlJSUlJY+b/wOI71jY0WmBlgAAAABJRU5ErkJggg==)
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbImsyQ7rGcrL8_2KYkKsBAnw9Xdl9pqhucTwrDRC1PKZOF791LA)
![](https://cdn2.iconfinder.com/data/icons/designer-skills/128/linux-server-system-platform-os-computer-penguin-512.png)

**Comment by nunodonato** [comment]
windows and linux seem ok to me as they are now, only mac os is a bit outdated

**Comment by toger5** [comment]
@nunodonato you are right. just also liked the idea to make all of them circles

**Comment by Calinou** [comment]
The macOS icon definitely needs an update, but the other icons are fine (as they are the official logos).

**Comment by toger5** [comment]
Is blackberry dropped?

**Comment by Zireael07** [comment]
@toger5 I believe so

**Comment by Bugsbane** [comment]
From a design perspective, I wouldn't add circles just for the sake of adding circles. If we wanted to get more consistency between the icons though we could still have a monochrome windows window, tux, apple (not OSX) logo and html5 icon.

I kind of feel like this issue, which is supposedly just about updating the html5 logo, is expanding into unifying logos of all platforms, which seems like a separate issue to me.

**Comment by Bugsbane** [comment]
Why was this closed? Is the html5 icon not needed any more? Is the svg of the new design needed?

**Comment by Noshyaar** [comment]
See #9419

**Comment by toger5** [comment]
@Bugsbane check the pr which was merged. #9419
