### ISSUE TITLE
Alpha Scissors does not apply correctly to textures. Uses incorrect compression/filtering.

### ISSUE THREAD

**Issue by prominentdetail** [godotengine/godot#88377]
### Tested versions

4.2.2.rc

### System information

windows 10

### Issue description

When applying alpha scissors option to a material, it seems to use some sort of compressed or filtered version of the texture to base the alpha clipping off of even though the sampling filtering is set to nearest.
Here is a screenshot of the issue:
![image](https://github.com/godotengine/godot/assets/10412778/e4c120ba-7a61-4068-be68-bbeb2e9cffbf)

### Steps to reproduce

Check the settings in the project. Try to apply alpha scissors to get desired results. You will find it impossible.

### Minimal reproduction project (MRP)

[alphaScissorsBug.zip](https://github.com/godotengine/godot/files/14301550/alphaScissorsBug.zip)

**Comment by prominentdetail** [comment]
I found a way to fix it:
I had to use "force disable mesh compression" in the import settings of the .obj 
Then it will display alphascissors correctly I think.

**Comment by clayjohn** [comment]
For future reference, you need to force disable mesh compression when using UVs with a large range. This model has UVs that extend well over 100 units, so mesh compression needs to be disabled

**Comment by prominentdetail** [comment]
I was confused, because it use to work in older versions of godot. So I assumed it was a regression of some sort. But I guess now it auto compresses it. Why is that necessary though to auto alter the uv data?

**Comment by clayjohn** [comment]
With compression enabled we store UVs using 16 bit floats instead of 32 bits. This cuts the size in half which is really beneficial for performance and memory.

**Comment by prominentdetail** [comment]
Oh ok, that makes sense. Thanks for the info!
