### ISSUE TITLE
GDExtension binary compatibility broken for `_get_configuration_warnings()`

### ISSUE THREAD

**Issue by dsnopek** [godotengine/godot#88379]
### Tested versions

- 4.3.dev [a9bb850]

### System information

Ubuntu 22.04

### Issue description

PR https://github.com/godotengine/godot/pull/68420 changed the return value for `_get_configuration_warnings()` from `PackedStringArray` to `Array`.

This breaks binary compatibility for GDExtension, which means that any GDExtension that implemented `_get_configuration_warnings()` would likely segfault if used with Godot `master` presently.

Suggestions from @akien-mga on RocketChat:

> I think it might be best to revert the signature back and find a different way to handle property warnings. Could be a new virtual method, either for both node and property (deprecating the old one) or one only for property warnings.

### Steps to reproduce

- Install a GDExtension which implements `_get_configuration_warnings()` (for example, [Terrain3D](https://github.com/TokisanGames/Terrain3D))
- In the editor, add a Node that implements `_get_configuration_warnings()` a the scene (for example `Terrain3D`)
- Crash!

### Minimal reproduction project (MRP)

Try the sample in the [Terrain3D extension](https://github.com/TokisanGames/Terrain3D)

**Comment by Mickeon** [comment]
Personal opinion is to bring back the original method as the one being exposed, whose result merges with a new "`_get_configuration_warnings`... whatever name is chosen" used exclusively with arrays of dictionaries.

**Comment by Mickeon** [comment]
Okay, I'm convinced. I hope whoever is at the helm to change this takes this these opinionated changes in mind:

- Bring back `_get_configuration_warnings` the way it was with **PackedStringArray**;
- Add an **internal** `_get_configuration_warnings_dict`. Do **not expose it** yet until further changes;
- Delegate configuration warnings to **Object** itself in some way;
    - See also https://github.com/godotengine/godot-proposals/issues/9098
- Allow associating configuration warnings to properties in a more dynamic way.
    - I'm imagining, right off the bat, associating a property to a Callable. Something akin to `update_configuration_warnings` can then be called when a property changes, passing the property name, and... I think you get the gist.

**Comment by akien-mga** [comment]
I'd opt for reverting #68420 for now to fix the compat breakage, and then have @RedMser redo the PR with the suggested changes to avoid breaking the compatibility. Note that you can use `git cherry-pick` on the original commit to get it re-committed after the revert, then modify it.
