### ISSUE TITLE
Godot's exported Android project 3D rendering bug on devices other than Qualcomm processors.

### ISSUE THREAD

**Issue by dsyze** [godotengine/godot#88397]
### Tested versions

godot4.2.1

### System information

Windows11 - godot4.2.1 - gles

### Issue description

After releasing my project, users reported that apart from the first time it opened with normal 3D rendering, subsequent openings resulted in crashes during 3D rendering. Upon investigation, I found that the issue mainly affected users with MediaTek Dimensity and Huawei Kirin processors. Through my research, I discovered that the problem was caused by enabling shader caching in Godot. Disabling shader caching resolved the issue. I suspect that the Godot development team may have only used Qualcomm processors for Android adaptation, leading to this problem.

### Steps to reproduce

After releasing my project, users reported that apart from the first time it opened with normal 3D rendering, subsequent openings resulted in crashes during 3D rendering. Upon investigation, I found that the issue mainly affected users with MediaTek Dimensity and Huawei Kirin processors. Through my research, I discovered that the problem was caused by enabling shader caching in Godot. Disabling shader caching resolved the issue. I suspect that the Godot development team may have only used Qualcomm processors for Android adaptation, leading to this problem.

### Minimal reproduction project (MRP)

After releasing my project, users reported that apart from the first time it opened with normal 3D rendering, subsequent openings resulted in crashes during 3D rendering. Upon investigation, I found that the issue mainly affected users with MediaTek Dimensity and Huawei Kirin processors. Through my research, I discovered that the problem was caused by enabling shader caching in Godot. Disabling shader caching resolved the issue. I suspect that the Godot development team may have only used Qualcomm processors for Android adaptation, leading to this problem.

**Comment by AThousandShips** [comment]
Please fill in the form properly instead of copying the same text three times

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82419, as this is due to the same cause.
