### ISSUE TITLE
Poor randomness in the 2D CPU particle system.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88393]
### Tested versions

v3.6.beta4.official [93ac21cf8]

### System information

w10 64

### Issue description

The randomness in position should be executed more quickly when the initial speed is increased.

As you can see in the video, when I increase the speed to 3000 long bursts of particles are created located at the same Y coordinate, I suppose this is because the randomness system has not yet assigned a new coordinate for the generation of particles so Particles continue to be created in the old coordinate.

Watch the video.
With the initial speed set to 1000 everything seems correct.
After I set it to 3000, long bursts of particles located at the same Y coordinate are now created.

https://github.com/godotengine/godot/assets/19652075/937af640-fc64-4552-bbdc-398ad56c5206

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

...

**Comment by lawnjelly** [comment]
Just a reminder that if you can, be sure to test previous versions to indicate whether this is a regression, or existing behaviour: there were changes to 2D CPU particles in 3.6 for physics interpolation.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
