### ISSUE TITLE
Global shortcuts doesn't work inside native module

### ISSUE THREAD

**Issue by tamtakoe** [godotengine/godot#88407]
### Tested versions

4.2 stable

### System information

MacOS Sonoma 14.1.2

### Issue description

register_shortcut_action and corresponded code of https://github.com/godotengine/godot/blob/a9bb8509f2faac81bdb995c6c89a5347372f3498/editor/plugins/node_3d_editor_plugin.cpp#L5172
doesn't work inside external native modules

### Steps to reproduce

I have native c++ module and set shortcut inside its constructor
```cpp
...
my_btn->connect("pressed", callable_mp(this, &MyModule::do_smth));
my_btn->set_shortcut(ED_SHORTCUT("my/path", "My Name", KeyModifierMask::CMD_OR_CTRL | Key::M));
add_child(my_btn);
```
It works. But I don't wont to use fake UI element my_btn for this. So I try to use this way https://github.com/godotengine/godot/blob/a9bb8509f2faac81bdb995c6c89a5347372f3498/editor/plugins/node_3d_editor_plugin.cpp#L5172

It doesn't work (no errors, nothing happens).

More stupid way also doesn't work

```cpp
...
Ref<Shortcut> sc = ED_SHORTCUT("my/path", "My Name", KeyModifierMask::CMD_OR_CTRL | Key::M);
EditorSettings::get_singleton()->add_shortcut("my/path" sc);
Ref<Shortcut> sc1 = EditorSettings::get_singleton()->get_shortcut("my/path");
sc->connect_changed(callable_mp(this, &MyModule::do_smth));
}
```
Is there a way to use global shortcuts inside external native module or maybe fix register_shortcut_action and make it public?

### Minimal reproduction project (MRP)

Move register_shortcut_action and corresponded code of https://github.com/godotengine/godot/blob/a9bb8509f2faac81bdb995c6c89a5347372f3498/editor/plugins/node_3d_editor_plugin.cpp#L5172
to the external native module

**Comment by AThousandShips** [comment]
What is the bug here? Is this a feature you are proposing? Then the place for that is [here](https://github.com/godotengine/godot-proposals). If you are asking for support for how to solve this you should ask [here](https://forum.godotengine.org/).

This is for bug reporting only

**Comment by tamtakoe** [comment]
Fine. Sorry for the offtopic. Then another global question. I see a lot of strange places in Godot code.
I see a strong connection between shortcuts and the interface (if I make the UI element invisible, the shortcut won't work).
I see that it requires adding an HTTP module to the UI to work (why? Where is the connection?).
I see a strong connection between interface and logic.
I see that I can make the Dock visible/invisible using `set_tabs_visible`, but I don't have a `set_bottom_panel_visible` method that could make the bottom panel invisible (why? What's the difference between these UI elements?)
etc.

So, these are not bugs or proposals. This looks like bad architecture. Where should I talk about this?

**Comment by AThousandShips** [comment]
You can create a discussion [here](https://github.com/godotengine/godot-proposals/discussions), or talk on the forums

Closing this then as this isn't a bug, please open a discussion or discuss your thoughts and views on the forums :)

**Comment by tamtakoe** [comment]
Ok. Thanks)
