### ISSUE TITLE
Can set_process or set_fixed_process accept custom methods name?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#8840]
**Operating system or device - Godot version:**
ALL

**Issue description:**

For some node, different update logic may needed for different stat,  if only the default update method is allowed, all stat determining logic must be done. 
With custom update method name, we can set different update method for each stat.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
I'm not sure to understand what you want. Could you give an example of how a script using this feature would be like?

`_process` and `_fixed_process` are tied to the game loop and call for all nodes where they are active. If you need to run `_process` for only a few logical elements in your node based on some conditions, you can just do:

```
var process_weapon = true
var process_spells = false

func _ready():
    set_process(true)

func _process(delta):
    if process_weapons:
        # do stuff
    if process_spells:
        # do stuff
```

Or split those elements in their own nodes/scripts, which will therefore have their dedicated `_process` and `_fixed_process`.

**Comment by alexzheng** [comment]
I meant 
set_process(methodname)
if a player got a weapon,It can set the process to method1, then no need to check the conditions if it has weapon in the _process method.
It's just a suggestion.

**Comment by alexzheng** [comment]
the default update method can be _process,but we can replace it with other method by set_process(myownupdatemethod)

**Comment by bojidar-bg** [comment]
@alexzheng What is the issue with splitting the script into multiple nodes, one for each weapon?

**Comment by alexzheng** [comment]
I know each child could have its own script, there is no issue for this.
I just take weapon for example. 
What I meant is, for example, a player may have multiple status, for initial status, it may have a update logic for each frame, and for other status, it may have special logic for each frame, if all these logic is in _process, each status must be checked. With custom process method, we can set the corresponding method when change to each status.

**Comment by volzhs** [comment]
it seems like to attach custom process function.
```gdscript
var func_list = []

func add_process(func_name):
    if func_list.has(func_name) == false:
        func_list.push_back(func_name)

func remove_process(func_name):
    func_list.erase(func_name)

func _process(delta):
    for f in func_list:
        call(f)
```
you can add or remove at any point, and no need to check condition.

**Comment by alexzheng** [comment]
Not so complicated.

set_process(my process), the my process method just replace the default _process

**Comment by groud** [comment]
According to what you are describing, you definitely are looking for a finite state machine behaviour.
And what you are describing is a common implementation of it. 
Have look [here](http://gameprogrammingpatterns.com/state.html) about how to implement it.

I just opened an issue about implementing FSM here: #8847 .

**Comment by eon-s** [comment]
A simple way is to:
 - Create a function for every state
 - on process: if (stateA): processStateA, etc.

Or:
 - Preload the different behaviour scripts
 - on process: if (stateA): scriptA.processState, etc.

Use inheritance and enjoy.

**Comment by alexzheng** [comment]
I just take the player status for example, not refer to this particular situation.

**Comment by raymoo** [comment]
@alexzheng You could modify the code from @volzhs to use just a string variable instead of an array of function names.

**Comment by kubecz3k** [comment]
I'm in the process of reviewing old issues, haven't seen any interest in this discussion for eleven months, so I will close for now. If there will be some fresh interest we will reopen.
