### ISSUE TITLE
Collider gets smashed into other collider when hit by a heavy object

### ISSUE THREAD

**Issue by artlessgames** [godotengine/godot#88410]
### Tested versions

4.2

### System information

Godot v4.2.1.stable (b09f793f5) - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics 730 (Intel Corporation; 31.0.101.4575) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

See the gif
10kg falling onto 1kg
![10](https://github.com/godotengine/godot/assets/79254895/8105e634-872a-4be1-a9b4-7c75b8881813)
100kg falling onto 1kg
![100](https://github.com/godotengine/godot/assets/79254895/d6ad6c3d-b47c-4660-b0fa-7b205ede85a8)
1000kg falling onto 1kg
![1000](https://github.com/godotengine/godot/assets/79254895/26d5dac0-9e3d-446b-9e50-7fbd585652c1)
10000kg falling onto 1kg
![10000](https://github.com/godotengine/godot/assets/79254895/80f5ef35-af30-4200-8590-a71cbe500a0c)

### Steps to reproduce

Run the project

### Minimal reproduction project (MRP)

[.zip](https://github.com/godotengine/godot/files/14313231/default.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8899.

**Comment by artlessgames** [comment]
> Thanks for the report! Consolidating in [godotengine/godot-proposals#8899](https://github.com/godotengine/godot-proposals/issues/8899).

I'm afraid that post doesn't work for me.
That script is supposed to be used on a chracter2d and doesn't take angular momentum into account, which doesn't work in a more general scene.
And we can see from these gifs that different weight causes different bugs. (The smashed into ground one is only the worst of them)

Here's a bug from my game.
![QQ图片20240217004059](https://github.com/godotengine/godot/assets/79254895/9ee61791-8b5b-43d2-a959-3f80a5697ff9)
(Mostly a weird jump, like the second gif)

**Comment by ChknNugz** [comment]
> > Thanks for the report! Consolidating in [godotengine/godot-proposals#8899](https://github.com/godotengine/godot-proposals/issues/8899).
> 
> I'm afraid that post doesn't work for me. That script is supposed to be used on a chracter2d and doesn't take angular momentum into account, which doesn't work in a more general scene. And we can see from these gifs that different weight causes different bugs. (The smashed-into-ground one is only the worst of them)
> 
> Here's a bug from my game's player feedback. ![QQ图片20240217004059](https://private-user-images.githubusercontent.com/79254895/305482261-9ee61791-8b5b-43d2-a959-3f80a5697ff9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjc1NTQsIm5iZiI6MTcxMzEyNzI1NCwicGF0aCI6Ii83OTI1NDg5NS8zMDU0ODIyNjEtOWVlNjE3OTEtOGI1Yi00M2QyLWE5NTktM2Y4MGE1Njk3ZmY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGI0Y2EwMzlhMDllZGEwY2NiODFlMWZjNGRmMTZmODY0NjcwMjA5MGRiNjQ4ZTg4YzE1NTcxMGQ1NjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrKjuxN33N51xcU-MTjuYDoiTuolTJcLnn-IKLXlP1E) [ ![QQ图片20240217004059](https://private-user-images.githubusercontent.com/79254895/305482261-9ee61791-8b5b-43d2-a959-3f80a5697ff9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjc1NTQsIm5iZiI6MTcxMzEyNzI1NCwicGF0aCI6Ii83OTI1NDg5NS8zMDU0ODIyNjEtOWVlNjE3OTEtOGI1Yi00M2QyLWE5NTktM2Y4MGE1Njk3ZmY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGI0Y2EwMzlhMDllZGEwY2NiODFlMWZjNGRmMTZmODY0NjcwMjA5MGRiNjQ4ZTg4YzE1NTcxMGQ1NjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrKjuxN33N51xcU-MTjuYDoiTuolTJcLnn-IKLXlP1E) ](https://private-user-images.githubusercontent.com/79254895/305482261-9ee61791-8b5b-43d2-a959-3f80a5697ff9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjc1NTQsIm5iZiI6MTcxMzEyNzI1NCwicGF0aCI6Ii83OTI1NDg5NS8zMDU0ODIyNjEtOWVlNjE3OTEtOGI1Yi00M2QyLWE5NTktM2Y4MGE1Njk3ZmY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGI0Y2EwMzlhMDllZGEwY2NiODFlMWZjNGRmMTZmODY0NjcwMjA5MGRiNjQ4ZTg4YzE1NTcxMGQ1NjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrKjuxN33N51xcU-MTjuYDoiTuolTJcLnn-IKLXlP1E) [ ](https://private-user-images.githubusercontent.com/79254895/305482261-9ee61791-8b5b-43d2-a959-3f80a5697ff9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjc1NTQsIm5iZiI6MTcxMzEyNzI1NCwicGF0aCI6Ii83OTI1NDg5NS8zMDU0ODIyNjEtOWVlNjE3OTEtOGI1Yi00M2QyLWE5NTktM2Y4MGE1Njk3ZmY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDIwNDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGI0Y2EwMzlhMDllZGEwY2NiODFlMWZjNGRmMTZmODY0NjcwMjA5MGRiNjQ4ZTg4YzE1NTcxMGQ1NjQ3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OrKjuxN33N51xcU-MTjuYDoiTuolTJcLnn-IKLXlP1E)

I am working on adding angular momentum but I'm still having issues with it. Makes sense because I have like little knowledge in dynamic physics.
