### ISSUE TITLE
EditorProgress is incorrectly sized when saving scenes or baking lightmaps

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#88429]
### Tested versions

v4.3.dev.custom_build [a9bb8509f]

### System information

macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

This is what the progressbar looks for me in master atm, it's the same when saving scene and baking lightmaps 🤔

<img width="421" alt="image" src="https://github.com/godotengine/godot/assets/60579014/2c25efca-3def-47db-9a52-dd6af48ac7ab">

### Steps to reproduce

Save a scene

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
This was reported in another issue already (it's a regression in 4.3.dev), but I can't find it right now.

**Comment by arkology** [comment]
> This was reported in another issue already (it's a regression in 4.3.dev), but I can't find it right now.

https://github.com/godotengine/godot/issues/88128

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/88128.
