### ISSUE TITLE
AnimationMixer::_update_caches() broken because of new warnings

### ISSUE THREAD

**Issue by personalmountains** [godotengine/godot#88428]
### Tested versions

master

### System information

Godot v4.3.dev.mono (8ff821670) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4584) - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

https://github.com/godotengine/godot/pull/86608 added warnings to `AnimationMixer::_update_caches()`:

```
if (!parent->has_node_and_resource(path)) {
    if (check_path) {
        WARN_PRINT_ED(mixer_name + ": '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'. This warning can be disabled in Project Settings.");
    }
    continue;
}
```

The `has_node_and_resource()` call is incorrect, it calls `get_node_and_resource()`, but with `false` for `p_last_is_property`.

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by TokageItLab** [comment]
I don't know in what case you are encountering a error. MRP is needed.

**Comment by TCROC** [comment]
Yep.  I can confirm that @personalmountains's suggestion fixes it.  Changing:

```cpp
if (!parent->has_node_and_resource(path)) {
	if (check_path) {
		WARN_PRINT_ED(mixer_name + ": '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'. This warning can be disabled in Project Settings.");
	}
	continue;
}
```

to 

```cpp
if (!parent->get_node_and_resource(path, resource, leftover_path)) {
	if (check_path) {
		WARN_PRINT_ED(mixer_name + ": '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'. This warning can be disabled in Project Settings.");
	}
	continue;
}
```

I'll do the change on my fork so I have it and put in a PR here + credit u @personalmountains  for finding it! :)

**Comment by monxa** [comment]
Thanks @TCROC.
But isn't 
`if (!parent->has_node_and_resource(path)) {
	if (check_path) {
		WARN_PRINT_ED(mixer_name + ": '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'. This warning can be disabled in Project Settings.");
	}
	continue;
}`
simply redundant because right after that we already do
`

				Node *child = parent->get_node_and_resource(path, resource, leftover_path);
				if (!child) {
					if (check_path) {
						WARN_PRINT_ED(mixer_name + ": '" + String(E) + "', couldn't resolve track:  '" + String(path) + "'. This warning can be disabled in Project Settings.");
					}
					continue;
				}
`?
