### ISSUE TITLE
The script list does not save its state.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88433]
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

w10 64

### Issue description

Well, there are a series of things/problems that I am noticing with version 4 dev3, I use 3.6 for my project but I wanted to try the new version.
Even though I close a script that I am not interested in having in the list, when I reload the project the script appears open again.
Shouldn't the script list remain the way I maintain it?

https://github.com/godotengine/godot/assets/19652075/9def0426-c679-4867-9958-45231fea0b2d

### Steps to reproduce

wath the video

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment]
Is this the script attached to the current scene? If so see:
* https://github.com/godotengine/godot-proposals/issues/8372

This is a setting, try turning it off

**Comment by Torguen** [comment]
It's true, so I'm closing it, it's my mistake, apologies.
