### ISSUE TITLE
`TabBar` has a foldable `Tabs` section above properties that do not belong to it

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#88434]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

linux

### Issue description

Another occurence of this problem (see https://github.com/godotengine/godot/issues/88141 and https://github.com/godotengine/godot-proposals/issues/7799).

The `Tabs` section should be below the other options.
![image](https://github.com/godotengine/godot/assets/71937306/8192c4f7-89eb-4edd-a6aa-fc5e392315ec)

### Steps to reproduce

add a `TabBar` to a scene

### Minimal reproduction project (MRP)

any

**Comment by AThousandShips** [comment]
This has the same issue as `OptionButton` and needs a fix that handles the limitations, see:
https://github.com/godotengine/godot/blob/8ff821670561466a5ff72044ad574dcb955b66c2/scene/gui/tab_bar.cpp#L1828-L1829
