### ISSUE TITLE
Area3D inconsistent with Jolt Physics

### ISSUE THREAD

**Issue by Vityy** [godotengine/godot#88441]
### Tested versions

- Reproductible in 4.2.1 Mono with Jolt Physics as 3D physics

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When using Jolt Physics, when a CharacterBody3D enters an Area3D both "Entered" and "Exited" signals are triggered at the same time making it impossible to use Area3D correctly.

The same thing happens with "AreaEntered" and "AreaExited" signals when trying with an Area3D.

Didn't test with RigidBody3D and StaticBody3D

If you move the animatable body that is the parent of the Area3D the characters is detected as exiting and entering multiple times even if it doesn't move and stays stuck on the platform

### Steps to reproduce

-Create an Area3D with a CollisionShape
-Create a moving CharacterBody3D (or Area3D)
-Connect "on_body_entered" and "on_body_exited" signals to a script on the Area3D that trigger a print on debug console
-Playtest, enter the Area3D with the CharacterBody3D
-You'll see both signals triggered at the same time, it considers that your CharacterBody3D is already out of the Area even if it isn't

### Minimal reproduction project (MRP)

https://we.tl/t-4Q5NMSWdq1

Download link (ZIP was more that 25 MB)

**Comment by AThousandShips** [comment]
Jolt is not an official plugin so this should be reported with [Godot Jolt](https://github.com/godot-jolt/godot-jolt)

**Comment by Vityy** [comment]
Oups my bad, I was too hasty when opening the issue, gonna open it on the right repo sorry :)

**Comment by AThousandShips** [comment]
Superseded by:
* https://github.com/godot-jolt/godot-jolt/issues/787
