### ISSUE TITLE
Godot 4.3 Dev3 Mono cannot open C# script with Visual Studio

### ISSUE THREAD

**Issue by J-Ponzo** [godotengine/godot#88447]
### Tested versions

Reproduced with : v4.3.dev3.mono.official [36e943b6b]

***NOT*** Reproduced with : v4.3.dev2.mono.official [352434668]

### System information

Godot v4.3.dev3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 Threads)

### Issue description

When the external editor is set to Visual Studio (Editor Settings => Dotnet => Editor => External Editor), double-clicking a C# script from the FileSystem Dock fails with this error :
```  /root/godot/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs:279 - Error when trying to run code editor: VisualStudio. Exception message: 'An error occurred trying to start process 'D:/GodotEngines/Godot_v4.3-dev3_mono_win64/GodotSharp/Tools\GodotTools.OpenVisualStudio.exe' with working directory 'C:\Users\JPonzo\vs-open-issue'. The system cannot find the file specified.'```

I checked the content of GodoSharp/Tool/ and there is no GodotTools.OpenVisualStudio.exe file indeed. In the Godot_v4.3-dev2_mono_win64 archive the file is there and the bug is not present

### Steps to reproduce

- Launch Godot 4.3 Dev3 Mono and create a new project
- Make sure the External Editor is set to Visual Studio
- Create a new C# script
- Double click the new C# script
    => Visual Studio does not open and the outpout dispalys the error message

### Minimal reproduction project (MRP)

[vs-open-issue.zip](https://github.com/godotengine/godot/files/14319552/vs-open-issue.zip)

**Comment by raulsntos** [comment]
Likely a regression from https://github.com/godotengine/godot/pull/86454
cc @Repiteo

**Comment by cjohnson57** [comment]
There are actually files there, just none of them have the .exe extension
![image](https://github.com/godotengine/godot/assets/30701749/2277a036-84b6-408f-a5bd-90741d111731)

**Comment by cjohnson57** [comment]
FYI I tried placing the .exe and the .exe-config from 4.3-dev2 into the folder. After doing this, trying to open a script won't error but nothing will happen at all.
