### ISSUE TITLE
compilation to uwp using msvc2017 fails ~ missing assembly platform.winmd

### ISSUE THREAD

**Issue by Ahmed0425** [godotengine/godot#8845]
**Operating system or device - Godot version:**
Windows 10 x64 - MSVC2017 all compilers - godot 3 alpha - 93f9a83062dbe74474a4a7928758c5cf5588238e

**Issue description:**

when compiling to uwp I get 2 warnings at the first

> scons: warning: Ignoring missing SConscript 'servers\spatial_sound\SCsub'
File "C:\Users\Ahmed94\Downloads\Compressed\godot-master\servers\SCsub", line 14, in module
[module word inside <>]

> scons: warning: Ignoring missing SConscript 'servers\spatial_sound_2d\SCsub'
File "C:\Users\Ahmed94\Downloads\Compressed\godot-master\servers\SCsub", line 15, in module
[module word inside <>]

then this error before compilation start

> platform\uwp\thread_uwp.cpp: fatal error C1107: could not find assembly 'platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable
scons: *** [platform\uwp\thread_uwp.uwp.debug.64.x64.obj] Error 2

**Steps to reproduce:**
compiled using x86_x64 cross tools command prompt & x64 native tools command prompt

**Link to minimal example project:**

**Comment by Ahmed0425** [comment]
Error mentioned in this article
https://msdn.microsoft.com/en-us/library/mt186164.aspx

**Comment by vnen** [comment]
For what I can gather, VS2017 uses `VCTOOLSINSTALLDIR` environment variable, but the platform configuration script checks only for `VCINSTALLDIR` which was used up to VS2015.
