### ISSUE TITLE
All instances of `MultiMeshInstance2D` are culled if the origin goes off screen

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#88458]
### Tested versions

Reproducible in: 4.3.dev [9283d0d65c42663326f3f6f3d621207b550225ae]
Not reproducible in: 4.3.dev [99fd6ca98c3441b891d4d15b33e52eb3cfd86d7d]

### System information

Godot v4.3.dev.mono (9283d0d65) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When the origin of a `MultiMeshInstance2D` goes off screen, all instances are culled.

According to clayjohn it may be the result of this PR: #79833

Before:

https://github.com/godotengine/godot/assets/21325943/9eb26b76-6b99-4d2c-8506-77e32d861f1c

After:

https://github.com/godotengine/godot/assets/21325943/e9807f4a-8203-4964-8938-d0900f99788d

### Steps to reproduce

Run the MRP and move the camera off screen.

### Minimal reproduction project (MRP)

[MeshTest.zip](https://github.com/godotengine/godot/files/14319947/MeshTest.zip)

**Comment by markdibarry** [comment]
Found the problem area: 
![Clipboard - February 18, 2024 10 33 AM](https://github.com/godotengine/godot/assets/21325943/aac0e890-1a4e-489d-a6db-dee5a6e6fc37)

I think the odd part is that it only calls `_multimesh_re_create_aabb()` if `multimesh->custom_aabb != AABB()`, but the first thing in that method is:
![Clipboard - February 18, 2024 10 42 AM](https://github.com/godotengine/godot/assets/21325943/c5556412-0953-404f-a41b-a5f4add87766)

So it should only call it if the condition is met, but also immediately return?

@puchik I'm not as familiar with this logic, so maybe you can weigh in?

**Comment by rburing** [comment]
In `MeshStorage::_update_dirty_multimeshes` (first screenshot) the condition to re-create the AABB should be when there is no custom AABB, that is `multimesh->custom_aabb == AABB()` (i.e. the opposite of the current condition).

**Comment by puchik** [comment]
@rburing is correct. This check was added immediately before pushing and was reversed by accident. I've made a PR that fixes this. Thanks for catching that!
