### ISSUE TITLE
[Win7] Godot 4.3dev no longer launches (missing d3d12.dll)

### ISSUE THREAD

**Issue by eswartz** [godotengine/godot#88466]
### Tested versions

Reproducible in 4.3 dev3 (I can't find/test older versions of 4.3dev, nor build on this laptop)
Works in 4.2.1-stable
Works in 4.2.2rc1

### System information

Godot v4.3dev3 - Windows 6.1.7601 - Vulkan (Mobile) - dedicated GeForce GTX 970M () - Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 Threads)

### Issue description

Project list and editor and export templates all fail to launch on Windows 7 due to `The program can't start because d3d12.dll is missing from your computer.` (etc, you know the dialog).

It appears there is no support for d3d12.dll on Windows 7 (re:. [this support answer](https://answers.microsoft.com/en-us/windows/forum/all/missing-dll-d3d12dll/a11cca24-47f6-462d-b5a4-e7e28ee1bd18)).

I assume this break in support isn't intentional. I hope dynamic loading or weak linking can make this work (if I didn't miss somewhere any existing compatibility/setup instructions) for the benefit of those of us still entertaining this OS :)

### Steps to reproduce

Try to launch any of the Godot editor or export template executables on Windows 7.

### Minimal reproduction project (MRP)

n/a

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
This is the result of [Direct3D 12 renderer addition](https://github.com/godotengine/godot/pull/70315), it's unlikely feasible to load it fully dynamically. And since extended security support for Windows 7 support ended in October 2023 and for Windows 8 ended in July 2023 it's probably time to finally drop support for these versions.

**Comment by bruvzg** [comment]
There is some version of DX12 for Windows 7 SP1 - https://www.nuget.org/packages/Microsoft.Direct3D.D3D12On7, it's unlikely our renderer will work with it, but it might be enough to load the engine.

**Comment by Calinou** [comment]
In the meantime, you can [build the editor from source](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_windows.html) with the `d3d12=no` SCons optrion.

**Comment by bruvzg** [comment]
We do not need to completely remove old code (to allow custom-builds), but switching to Windows 10 a target for official builds is a most reasonable thing.

**Comment by eswartz** [comment]
Thanks for the tips. I tried the Nuget package and added entries to my PATH but now am missing `CreateDXGIFactory2` from `dxgi.dll`. 

I can build Godot from source on Win10 (excluding d3d12 support) later on.

I fully understand the silliness of continuing Win 7 support and am happy 4.2.2rc* still work fine (fortunately it has gdscript fixes I was relying on from 4.3).

**Comment by eswartz** [comment]
Thanks for resolving this so quickly, I was coming back to post that a build with "d3d12=no" worked just fine for Win7, as expected.

**Comment by eswartz** [comment]
Confirmed that the merged PR also works properly on Win7.
