### ISSUE TITLE
"Command can't have itself as a dependency" floods console with SSIL enabled and set to Very Low

### ISSUE THREAD

**Issue by TheNetherPug** [godotengine/godot#88468]
### Tested versions
4.3 dev3 stable.

### Description

After updating my godot project from 4.2.0, this error began flooding the output, both in editor and in-game.

![image](https://github.com/godotengine/godot/assets/91162221/148151e8-6042-4aec-9f5b-b52b125feb35)

### System information

Windows 11 - Godot 4.3.0dev3 - Forward+ renderer, using Vulkan - Nvidia GTX 1650, Intel i5 9300H Cpu, 8GB of Ram

### Issue description

After updating my godot project from 4.2.0, this error began flooding the output, both in editor and in-game.
I did not change any setting after updating, and did delete the `.godot` folder and reopened the project in an attempt to rectify the issue.

![image](https://github.com/godotengine/godot/assets/91162221/148151e8-6042-4aec-9f5b-b52b125feb35)

```
E 0:00:18:0789   _add_command_to_graph: Command can't have itself as a dependency.
  <C++ Error>    Condition "!resource_has_parent" is true.
  <C++ Source>   servers/rendering/rendering_device_graph.cpp:464 @ _add_command_to_graph()
```

From my testing, this error occurs when `SSIL` is enabled in a WorldEnvironment node, with it's quality set to `Very Low` in project settings.

### Steps to reproduce

1. Add a world environment node with a new environment
2. Enable `SSIL` in the environment
3. Go to project settings with advanced settings enabled.
4. Under `Environment` in project settings, set the SSIL quality to `Very Low`

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/14320456/mrp.zip)

**Comment by TheNetherPug** [comment]
After further testing, this also occurs with SSAO.

**Comment by Calinou** [comment]
cc @DarioSamo

**Comment by DarioSamo** [comment]
This is one of two possibilities:
- The graph validation is erroneous.
- SSIL at low had undefined behavior due to using textures in some way (e.g. overlapping slices).
I'll review during the week which of those two that is, but I felt it was worth pointing out we can start running into situations where it's just exposing existing bugs (we had a few of those when the graph was added).

**Comment by TheNetherPug** [comment]
interesting. Looking forward to a fix for this, as Very Low and Low don't really have a visible difference but do have a performance difference.

**Comment by DarioSamo** [comment]
> After further testing, this also occurs with SSAO.

I missed this comment, I can reproduce this as well. Guessing it's a similar issue.

**Comment by DarioSamo** [comment]
The PR will now fix both SSIL and SSAO. Feel free to point out any more of these issues you run into, it seems the behavior changes quite a bit depending on the quality of these algorithms sometimes so the graph might end up exposing some of the undefined behavior it was doing.

**Comment by TheNetherPug** [comment]
> The PR will now fix both SSIL and SSAO. Feel free to point out any more of these issues you run into, it seems the behavior of these algorithms changes quite a bit depending on the quality so the graph might end up exposing some of the undefined behavior it was doing.

Alright, thank you. Will check out the PR later today when I have the time

**Comment by TheNetherPug** [comment]
@DarioSamo Tested the PR, can confirm that the issue is fixed. Another issue ended up appearing when I opened the PR but I don't think that one requires a github issue opened. Thanks so much for the help!

**Comment by TheNetherPug** [comment]
Will leave this issue opened until the PR gets merged (I think thats how things move around here? I don't create issues often)
