### ISSUE TITLE
Node3D does not inherit transform if its immediate parent is not Node3D

### ISSUE THREAD

**Issue by Awarets** [godotengine/godot#88480]
### Tested versions

Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) R9 390 Series (Advanced Micro Devices, Inc.; 27.20.20913.2000) - Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz (4 Threads)

### Issue description

Node3D only inherits transform information if its immediate parent is a Node3D. It does not inherit transform information from any other Node3D in its parent lineage.

![image](https://github.com/godotengine/godot/assets/8617121/03bb4147-c6c5-4bce-83d8-3e2dc7b0572c)

Pictured: Root node in the center. While it is being moved around, the immediate child (on the left) is moved around correctly, whereas the grandchild with the Node inbetween (on the right) is not moved.

https://github.com/godotengine/godot/assets/8617121/d8850e98-6fd2-4b20-b632-a3471be39881

### Steps to reproduce

Create a series of nodes as follows:

Node3D
->Node
---->Node3D

Translate the root Node3D in any way, and test if the child transform is affected.

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
This is by design afaik, and it's been this way since (at least) Godot 3.

**Comment by AThousandShips** [comment]
I'd say this is something for a [proposal](https://github.com/godotengine/godot-proposals) explaining the use case of this unusual setup, and the need for more complex setups, further being able to disconnect transform by using this method is valuable and would break if this was changed, so this should be discussed as a feature as it's not a bug

**Comment by Awarets** [comment]
Understandable, I've made a proposal here: godotengine/godot-proposals#9122
