### ISSUE TITLE
Very low FPS using Wayland display driver on Linux

### ISSUE THREAD

**Issue by akyoto** [godotengine/godot#88493]
### Tested versions

Reproducible in 4.3.dev3.official.36e943b6b
Reproducible in 4.3.dev.custom_build.5f05e2b9b

### System information

Arch Linux ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000 - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

When running on Wayland, the FPS are fine when I don't include the "--display-driver wayland" flag.
However, when "--display-driver wayland" is added, the framerate is extremely low.
It seems to be a *little* bit better on the bleeding edge build.

### Steps to reproduce

I tested multiple projects and it seems to be reproducible with any project:

---

1. Using `~/projects/game/mrp` (empty project, included below in zip file)

4.3 dev3 **without** Wayland display driver:
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/mrp

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Enabled - FPS will likely be capped to the monitor refresh rate.
 
Project FPS: 165 (6.06 mspf)
Project FPS: 163 (6.13 mspf)
Project FPS: 164 (6.09 mspf)
Project FPS: 164 (6.09 mspf)
Project FPS: 164 (6.09 mspf)
```

4.3 dev3 **with** Wayland display driver:
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/mrp --display-driver wayland

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
WARNING: Can't obtain the XDG decoration manager. Libdecor will be used for drawing CSDs, if available.
     at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3479)
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Enabled - FPS will likely be capped to the monitor refresh rate.
 
WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:587)
Project FPS: 21 (47.61 mspf)
Project FPS: 10 (100.00 mspf)
Project FPS: 10 (100.00 mspf)
Project FPS: 25 (40.00 mspf)
Project FPS: 10 (100.00 mspf)
```

4.3 custom build **without** Wayland display driver:
```
./bin/godot.linuxbsd.template_release.x86_64.llvm ~/projects/game/mrp/project.godot

Godot Engine v4.3.dev.custom_build.5f05e2b9b - https://godotengine.org
Vulkan 1.3.260 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Enabled - FPS will likely be capped to the monitor refresh rate.

Project FPS: 164 (6.09 mspf)
Project FPS: 164 (6.09 mspf)
Project FPS: 163 (6.13 mspf)
Project FPS: 165 (6.06 mspf)
Project FPS: 164 (6.09 mspf)
```

4.3 custom build **with** Wayland display driver:
```
./bin/godot.linuxbsd.template_release.x86_64.llvm ~/projects/game/mrp/project.godot --display-driver wayland

Godot Engine v4.3.dev.custom_build.5f05e2b9b - https://godotengine.org
WARNING: Can't obtain the XDG decoration manager. Libdecor will be used for drawing CSDs, if available.
     at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3493)
Vulkan 1.3.260 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Enabled - FPS will likely be capped to the monitor refresh rate.

WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:591)
Project FPS: 10 (100.00 mspf)
Project FPS: 10 (100.00 mspf)
Project FPS: 12 (83.33 mspf)
Project FPS: 17 (58.82 mspf)
Project FPS: 21 (47.61 mspf)
```

---

2. Using `~/projects/game/vrm` (not included, just providing framerate data) 

4.3 dev3 **without** Wayland display driver:
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/vrm

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Disabled
 
Project FPS: 78 (12.82 mspf)
Project FPS: 79 (12.65 mspf)
Project FPS: 79 (12.65 mspf)
Project FPS: 79 (12.65 mspf)
Project FPS: 79 (12.65 mspf)
```

4.3 dev3 **with** Wayland display driver:
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/vrm --display-driver wayland

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
WARNING: Can't obtain the XDG decoration manager. Libdecor will be used for drawing CSDs, if available.
     at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3479)
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
WARNING: The requested V-Sync mode Disabled is not available. Falling back to V-Sync mode Enabled.
     at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2079)
Requested V-Sync mode: Disabled
 
WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:587)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
```

4.3 custom build **without** Wayland display driver:
```
./bin/godot.linuxbsd.template_release.x86_64.llvm ~/projects/game/vrm/project.godot

Godot Engine v4.3.dev.custom_build.5f05e2b9b - https://godotengine.org
Vulkan 1.3.260 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Disabled

Project FPS: 90 (11.11 mspf)
Project FPS: 89 (11.23 mspf)
Project FPS: 89 (11.23 mspf)
Project FPS: 89 (11.23 mspf)
Project FPS: 90 (11.11 mspf)
```

4.3 custom build **with** Wayland display driver:
```
./bin/godot.linuxbsd.template_release.x86_64.llvm ~/projects/game/vrm/project.godot --display-driver wayland

Godot Engine v4.3.dev.custom_build.5f05e2b9b - https://godotengine.org
WARNING: Can't obtain the XDG decoration manager. Libdecor will be used for drawing CSDs, if available.
     at: init (platform/linuxbsd/wayland/wayland_thread.cpp:3493)
Vulkan 1.3.260 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce GTX 1070
WARNING: The requested V-Sync mode Disabled is not available. Falling back to V-Sync mode Enabled.
     at: swap_chain_resize (drivers/vulkan/rendering_device_driver_vulkan.cpp:2583)
Requested V-Sync mode: Disabled

WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:591)
Project FPS: 50 (20.00 mspf)
Project FPS: 56 (17.85 mspf)
Project FPS: 57 (17.54 mspf)
Project FPS: 55 (18.18 mspf)
Project FPS: 51 (19.60 mspf)
```

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/14322241/mrp.zip)

**Comment by Calinou** [comment]
Does the project actually feel choppy when it runs? Maybe FPS reporting is broken when using Wayland.

**Comment by akyoto** [comment]
> Does the project actually feel choppy when it runs? Maybe FPS reporting is broken when using Wayland.

Just checked again, on my main project I get 1-3 FPS and it really is a slideshow.
Without Wayland driver ~160 FPS.

**Comment by akien-mga** [comment]
Tested on my Linux system with the MRP, I get around 4000 FPS with X11, and 2000 FPS with Wayland. So I do see a difference but on such a simple reproducer I'm not sure it's very significant, would need to see how it scales on something more involved.

I notice that it says this in your logs when using Wayland only:
```
WARNING: The requested V-Sync mode Disabled is not available. Falling back to V-Sync mode Enabled.
     at: swap_chain_resize (drivers/vulkan/rendering_device_driver_vulkan.cpp:2583)
```

So maybe Wayland + Nvidia has sync issues? I haven't used Nvidia recently but I remember seeing a lot of mentions of Nvidia drivers still being a big showstopper for massive adoption of Wayland.

CC @Riteo

**Comment by akyoto** [comment]
> would need to see how it scales on something more involved

Can quickly throw something together, for example 10k Godot logo particles: [mrp2.zip](https://github.com/godotengine/godot/files/14329264/mrp2.zip)

---

Gnome X, mrp2 X
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/mrp2

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Disabled
 
Project FPS: 52 (19.23 mspf)
Project FPS: 48 (20.83 mspf)
Project FPS: 51 (19.60 mspf)
Project FPS: 57 (17.54 mspf)
Project FPS: 67 (14.92 mspf)
```

Plasma Wayland, mrp2 X
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/mrp2

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
Requested V-Sync mode: Disabled
 
Project FPS: 53 (18.86 mspf)
Project FPS: 48 (20.83 mspf)
Project FPS: 51 (19.60 mspf)
Project FPS: 61 (16.39 mspf)
Project FPS: 68 (14.70 mspf)
```

Plasma Wayland, mrp2 Wayland
```
./bin/godot_v4.3-dev3_linux.x86_64 --path ~/projects/game/mrp2 --display-driver wayland

Godot Engine v4.3.dev3.official.36e943b6b - https://godotengine.org
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070
WARNING: The requested V-Sync mode Disabled is not available. Falling back to V-Sync mode Enabled.
     at: _update_swap_chain (drivers/vulkan/vulkan_context.cpp:2079)
Requested V-Sync mode: Disabled
 
WARNING: Icon not supported by this display server.
     at: set_icon (servers/display_server.cpp:587)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
Project FPS: 1 (1000.00 mspf)
```

---

> So maybe Wayland + Nvidia has sync issues?

Yea it seems so, especially if you look at the oddly round `mspf` numbers.

Guess we'll need to ~~boycott nvidia~~ hope for a better future, I don't think there's anything Godot can do here.
Can be closed unless someone has additional comments on the Nvidia/Wayland problem.

**Comment by akyoto** [comment]
> Project FPS: 1 (1000.00 mspf)

I can't reproduce this anymore. Godot projects run at monitor refresh rate now! :tada: 

---

I remember doing an `nvidia-dkms` driver update and I pulled the latest `HEAD` from godot. The problem seems to be gone now. Can anyone else using Linux + Wayland + Nvidia confirm?

**Comment by amorphine** [comment]
Ubuntu 22.04, 
RTX 4080
Nvidia drivers from the default repository (435)
Same issue with games launched under Wayland session (~1 fps at fullscreen). The smaller game window is set, more FPS get.
I tried driver 550 from 3rd party PPA, but no luck.
I do understand the issue is not related to the Godot itself, but can you point out where I should report it, please? Thank you

**Comment by akyoto** [comment]
> Ubuntu 22.04, RTX 4080 Nvidia drivers from the default repository (435) Same issue with games launched under Wayland session (~1 fps at fullscreen). The smaller game window is set, more FPS get. I tried driver 550 from 3rd party PPA, but no luck. I do understand the issue is not related to the Godot itself, but can you point out where I should report it, please? Thank you

I'm not on Ubuntu so take this with a grain of salt but [it looks like you have official options](https://ubuntu.com/server/docs/nvidia-drivers-installation#the-recommended-way-ubuntu-drivers-tool) to install nvidia-driver-550.
Did you try these?

_Side note: Many distros are already on 555 which includes even better Wayland support._

You can run `vulkaninfo --summary` (from vulkan-tools) to confirm the installed driver version.

**Comment by amorphine** [comment]
@akyoto You are absolutely right, it's up to Ubuntu nvidia driver maintainers. It is not shipped with `egl-wayland` package by default so wayland has software rendering with llvm:

```
glxinfo | grep OpenGL
OpenGL vendor string: Mesa
OpenGL renderer string: llvmpipe (LLVM 15.0.7, 256 bits)
```

What it gets with the package :
```
$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2

```
 Having this package installed solves the problem even with driver version 535, games run smoothlu. Thanks for reply and sorry for my off-top.
