### ISSUE TITLE
Node icon misplaced in Create New Scene dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88505]
### Tested versions

4.3 dev3
Does not happen in 4.2.1 (although there was different bug there)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/12a1d277-6d89-4346-a9b1-d4e7c897b786)
Probably regression from some button icon PRs?

Previously it was aligned, but selection was broken:
![image](https://github.com/godotengine/godot/assets/2223172/b9dd3b71-ea82-4632-8fbc-caab4c49941a)
It evolved I guess.

### Steps to reproduce

1. Right click FileSystem dock
2. Create New
3. Scene...

### Minimal reproduction project (MRP)

N/A

**Comment by AegisTTN** [comment]
If I did the bisects correctly, sorry for any mistake new to this, it seems that f29a7d302e0de7eb4b10f57c849d369210c1be55 first changed it to:

![Godot_Scene_Create_Dialogue](https://github.com/godotengine/godot/assets/127440499/368a7143-68f1-4009-9efe-1b17e66f9348)

And then 567e76f9352ba663813ae8d9d8a028a41f84293e changed it to what it currently is

**Comment by KoBeWi** [comment]
CC @Rindbee

**Comment by Rindbee** [comment]
![0](https://github.com/godotengine/godot/assets/30386067/f44b6b7b-d27c-4a42-a767-84ba0ccdf8f6)

This is a question of whether `h_separation` needs to be added between icons when calculating the minimum size. Currently only `h_separation` needs to be added when the text is not empty.

https://github.com/godotengine/godot/blob/652438a3952ae13e12dd4fd40756311fde81a791/scene/gui/check_box.cpp#L69-L71

https://github.com/godotengine/godot/blob/652438a3952ae13e12dd4fd40756311fde81a791/scene/gui/check_button.cpp#L73-L75
