### ISSUE TITLE
Unexpected "Identifier" in Summator custom module

### ISSUE THREAD

**Issue by catwasd** [godotengine/godot#88507]
### Tested versions

v4.3.dev.custom_build [d3352813e]

### System information

macOS 14.3.1 - Godot v4.3.dev.custom_build - Vulkan (Forward+)

### Issue description

Seeing a script error for the `Summator` class:

```
SCRIPT ERROR: Parse Error: Unexpected "Identifier" in class body.
```

### Steps to reproduce

Follow the steps in this doc:
https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/custom_modules_in_cpp.html

Code:

```cpp
// summator.cpp
#include "summator.h"

void Summator::add(int p_value) { count += p_value; }

void Summator::reset() { count = 0; }

int Summator::get_total() const { return count; }

void Summator::_bind_methods() {
	ClassDB::bind_method(D_METHOD("add", "value"), &Summator::add);
	ClassDB::bind_method(D_METHOD("reset"), &Summator::reset);
	ClassDB::bind_method(D_METHOD("get_total"), &Summator::get_total);
}

Summator::Summator() { count = 0; }

// register_types.h
#include "modules/register_module_types.h"

void initialize_summator_module(ModuleInitializationLevel p_level);
void uninitialize_summator_module(ModuleInitializationLevel p_level);

// register_types.cpp
#include "register_types.h"

#include "core/object/class_db.h"
#include "summator.h"

void initialize_summator_module(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}

	ClassDB::register_class<Summator>();
}

void uninitialize_summator_module(ModuleInitializationLevel p_level) {
	if (p_level != MODULE_INITIALIZATION_LEVEL_SCENE) {
		return;
	}
}
```

GDScript:

```gdscript
extends Node2D

var summator: Summator = Summator.new()
summator.add(10)
summator.add(20)
summator.add(30)
print(summator.get_total())
summator.reset()


```

Build command:

```shell
scons target=editor dev_build=yes compile_db=yes
```

### Minimal reproduction project (MRP)

[summator.zip](https://github.com/godotengine/godot/files/14323539/summator.zip)

**Comment by AThousandShips** [comment]
Your GDScript code isn't valid code, it needs to be inside a method

**Comment by catwasd** [comment]
@AThousandShips Thanks! Updated the description. Will close the issue.

Yeah I am just getting myself familiar with GDScript code. Would be good to update the documentation to include the lines in `_ready()`.

**Comment by AThousandShips** [comment]
Again it doesn't have to be in `_ready`, the assumption is that anyone reading this code is experienced enough with GDScript to know to put it in a method, making it specifically `_ready` is too specific IMO
