### ISSUE TITLE
Texture2D in VisualShader doesn't present the image correctly

### ISSUE THREAD

**Issue by FakerDomain** [godotengine/godot#88501]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows10-Godot 4.2.1 stable-Forward+

### Issue description

I just want to use a Texture2D to present an image from my asset, and the color presented is not right, it's too white....

![image](https://github.com/godotengine/godot/assets/13235429/af9e8948-75af-4437-967c-802678aaffa4)

### Steps to reproduce

Under Node2D create a sprite2D and use icon.svg as the default texture. Then make a visualshader for this sprite2D, in the visualshader editor create a Texture2D node and drag an image from my asset to the Texture Box in the Texture2D node. Finally, link Texture2D's color and alph to the output node.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Try change "Data" to "Color"

**Comment by FakerDomain** [comment]
> Try change "Data" to "Color"

Thanks a lot, I really appreciate it!!!!!
