### ISSUE TITLE
Further document that theme does not propagate through Node2D nodes

### ISSUE THREAD

**Issue by bogcow** [godotengine/godot#88534]
### Tested versions

4.2.stable

### System information

Windows 10

### Issue description

![image](https://github.com/godotengine/godot/assets/157412753/f6bf85d2-6c86-4f64-8c27-e02048e6348c)
In this simple scene setup, I have 2 Labels, one is parented to the root Control node, while the other is parented to a Node2D which is parented to the root Control. On the root Control node, I have attached a theme that applies an outline to Label nodes. You can see that the first Label has the proper theme, but the second Label does not, as it is a child of a Node2D rather than a Control node. However, the theme should still propagate through Node2Ds, as this is a common use case.

### Steps to reproduce

Recreate the simple demo scene shown in the screenshot above

### Minimal reproduction project (MRP)

N/A

**Comment by arkology** [comment]
> Recreate the simple demo scene shown in the screenshot above

It costs time which could be spend on fixing this bug. So if you have MRP - just upload it)

**Comment by Cammymoop** [comment]
Based on the documentation of the `Theme` class this doesn't appear to be a bug, so this should probably be opened as a proposal -> https://github.com/godotengine/godot-proposals/issues which is where feature requests are tracked.

**Comment by bogcow** [comment]
There's an old bug report for the same issue in a much earlier version of Godot (#4754 ) that got resolved, which makes me inclined to believe that it is a bug. Though I'm not sure if it was purposefully removed in a future version or not.

**Comment by Cammymoop** [comment]
@bogcow Thanks for linking, this is a likely a regression it seems, and misleading documentation. If you can provide any previous versions where this worked that would be useful information.

**Comment by Mickeon** [comment]
There's an extremely strong possibility this was removed intentionally among the many refactors Theme-related things received in Godot 4. It would be very interesting to trace the steps back and find the rationale.
Where is the "misleading documentation" at?

**Comment by AThousandShips** [comment]
For changes to this please open a [proposal](https://github.com/godotengine/godot-proposals), as this is intended behaviour, will make this an issue to track clarifying the documentation in `Control` to make the behaviour clear (like that in `Theme`)

**Comment by Zireael07** [comment]
@BalmundSM There seems to be no consensus whether the proposed change is a good thing so I doubt this is something you should be tackling if you're new to Godot

**Comment by AThousandShips** [comment]
Note that *this* issue is for improving the documentation as outlined above, for changing this see:
* https://github.com/godotengine/godot-proposals/issues/9132

**Comment by marcospb19** [comment]
@Zireael07 
> I doubt this is something you should be tackling if you're new to Godot

can we pop the "good first issue" then? Balmund might've ended up here because of it.
