### ISSUE TITLE
Tooltip show empty for most properties when hovering

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#88532]
### Tested versions

Godot v4.3.dev (ae51db75e)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

It looks like all properties's tooltip can not be shown correctly when hovering,  I'm using TextEdit as an example below:

https://github.com/godotengine/godot/assets/8315986/ad2709d2-ecc7-484b-a977-4223db7cf55a

### Steps to reproduce

* Add any node to scene
* Hover some properties to check the tooltip

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
Regression from 7b42c245509d1b4c325ff073cb9ef2011000dea7. CC @YeldhamDev
