### ISSUE TITLE
About 2D sprite glow with Shader 

### ISSUE THREAD

**Issue by FakerDomain** [godotengine/godot#88533]
### Tested versions

4.2.1 stable

### System information

Windows10-Godot 4.2.1 stable-Forward+

### Issue description

When I try to make my weapon glow in a 2D sprite, the below problem shows up…

![image](https://github.com/godotengine/godot/assets/13235429/25d64951-c36a-4243-81f3-d313a1db5523)

The above image shows the glow effect, however, I found that in the middle of my weapon, the color is still white, so I changed my shader code from “+” to “*”, the resuslt is shown below

![image](https://github.com/godotengine/godot/assets/13235429/dd7f8b57-39eb-4a67-9a90-2686b4424fe6)

Now, my blade’s color is correct, however what makes me mad is the weapon won’t glow…

If i change the glow strenth or other paramters of WorldEnvironment node, the weapon glows eventually...however....

![image](https://github.com/godotengine/godot/assets/13235429/186b0eca-94c5-491f-988c-63c90549a9bc)

The face glows too, and the other part of the body remains...

My blade_mask only contains blade slash, when I add it to the ori_color, in my mind, the only shining part should be the blade...

Is this a bug or someting?

By the way, I have opened the HDR settings in project setting.

### Steps to reproduce

Create a 2D sprite with ShaderMaterial, and code the shader shown in the picture above, then pass a mask picture for the blade_mask sampler2D in the code.

### Minimal reproduction project (MRP)

N/A

**Comment by Cammymoop** [comment]
This doesn't appear to be bugged, there is a forum where you can ask for help here: https://forum.godotengine.org/

I think multiplying instead of adding is the right approach, but it seems like you are multiplying by a color of Vec4(1.0) which will have no effect, you might try changing the multiplication factor to vec4(2.0) or something around there.

If you have any other questions you can ask them on the forums or other community locations linked on this page https://godotengine.org/community/

**Comment by FakerDomain** [comment]
> This doesn't appear to be bugged, there is a forum where you can ask for help here: https://forum.godotengine.org/
> 
> I think multiplying instead of adding is the right approach, but it seems like you are multiplying by a color of Vec4(1.0) which will have no effect, you might try changing the multiplication factor to vec4(2.0) or something around there.
> 
> If you have any other questions you can ask them on the forums or other community locations linked on this page https://godotengine.org/community/

Yes you are right, it's not a bug, thanks....

By the way I correct this by change the raw value of the uniform color from the inspector, and it works fine...

Thank you again, I really appreciate it...
