### ISSUE TITLE
C#: A script that inherit a type from external C# project is marked as `out of sync` forever

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#88536]
### Tested versions

v4.3.dev.mono.custom_build [8ff821670]

### System information

Godot v4.3.dev.mono (8ff821670) - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When inspecting a node with a `script that inherits a type from external C# project` attached to it, Godot will always show it is out of date, even if the C# project has been built.
![image](https://github.com/godotengine/godot/assets/71481700/4003d971-0f28-49ed-b92a-8800a2234205)

### Steps to reproduce

1. Download and extract the included `InspectorError.zip`
2. Open `InspectorErrorProject` with `Godot Editor`
3. Build the C# project
4. Select the `Node` inside the scene tree
5. Inspect
6. Build the C# project again
7. Inspect

### Minimal reproduction project (MRP)
[InspectorError.zip](https://github.com/godotengine/godot/files/14328038/InspectorError.zip)

**Comment by Delsin-Yu** [comment]
Video is here
https://github.com/godotengine/godot/assets/71481700/8f6744b6-f643-403b-9480-ad2c34a1420a

**Comment by paulloz** [comment]
I don't think this should be tagged as *regression*, since types from external assemblies aren't especially supposed to work as Godot types.

**Comment by Delsin-Yu** [comment]
> I don't think this should be tagged as _regression_, since types from external assemblies aren't especially supposed to work as Godot types.

Should this behavior be documented, or should a separate warning be produced instead of the out-of-sync warning? This can be unclear to users.

**Comment by Delsin-Yu** [comment]
Close as the `mono` module (aka `GodotSharp`) wasn't designed for handling external scripts, and this reminder doesn't enable that support either. Let's wait for the new binding implementation.
