### ISSUE TITLE
Changing the name of an export variable resets its value to its default value.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88542]
### Tested versions

v3.6.beta4.official [93ac21cf8]

4.3 dev 3

### System information

w10 64

### Issue description

You have a bool export variable.
Its default value is false.
export( bool ) var test: bool = false
In the editor you assign the value true.
Then you change its name in the script editor using the replacement tool, now the name is like this:
export( bool ) var test_: bool = false
Now the variable is false (default value) but before you assigned it the value true.
All scenes that have that variable will have lost their assigned value and will now be false.

If you use replace all variables in all scripts with the script editor tool, they will all lose their assigned value.

https://github.com/godotengine/godot/assets/19652075/664255c6-2973-43ea-9b11-7ede43c8c6af

### Steps to reproduce

See the video.

### Minimal reproduction project (MRP)

[testExport.zip](https://github.com/godotengine/godot/files/14329949/testExport.zip)

**Comment by AThousandShips** [comment]
This is not trivial to fix, there's no reliable way to detect *renaming* verses *remove old and add new*

Even if you edit the name in place you can't necessarily assume intent by the user, and if I delete and then add back intending a rename how can the editor tell?

**Comment by Mickeon** [comment]
What has been said above. This would require its own refactoring tools at best, and at worst having the editor guess, which is material for a proposal.

Having the editor make a good guess sounds great on paper, but it would lead to more problems than it is worth in the long run.
It'll not always be correct and the "transferring" of data could potentially be disastrous. At least when changing the property's name the developer is aware that this can happen and can act accordingly on their own.

A dirty "solution" involves keeping old and new variable names in the same script, running the script in `@tool` mode and setting the old variable to the new one for every scene.

```GDScript
@tool

@export old_property: String
@export new_property: String = old_property
```

**Comment by Mickeon** [comment]
With the way Godot works sometimes you _do_ want properties saved on disk that are not consistent defined (the engine does this all the time through `get_property_list`), so making a consistently good guess would be even more difficult.

**Comment by Torguen** [comment]
So would it be okay to open a dialog box when you replace that will notify you of this change?

Something like:
The exported variables will lose the assigned value and will adopt the default value.

At the time of pressing the replace button.
Two options will then be offered.
Replace and cancel.

Just an idea.

**Comment by Deozaan** [comment]
For comparison, Unity "solves" this with an annotation. A Godot equivalent might look something like:

```gdscript
@export_previously_named("old_property")
@export var new_property: String
```

Or perhaps just

```gdscript
@export_previously_named("old_property") var new_property: String
```

Then every scene or resource that has a value saved for `old_property` will have that value stored into `new_property` when it is saved to disk. After all references have been updated you can get rid of the extra annotation if desired.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/3152.
