### ISSUE TITLE
Modifying an ENUM, if used in a custom resource, could change its value

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#88541]
### Tested versions

.

### System information

Windows 10

### Issue description

If you create an enum like enum TEST { ONE, THREE, FOUR }, create a custom resource that `@exports` this enum and choose THREE, then if you add the new value TWO right after ONE, the node will have TWO as its value instead of the previously chosen THREE.

### Steps to reproduce

As written above.

### Minimal reproduction project (MRP)

.

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot-proposals/discussions/9128
