### ISSUE TITLE
Adding community translations is impossible and easier in closed Unreal/Unity

### ISSUE THREAD

**Issue by ghostlyghastly** [godotengine/godot#88555]
### Tested versions

Please stop using the dreadful .translation format for translations by default. Instead make it easy to access the translations by default for modders and community translators.

https://github.com/bruvzg/gdsdecomp/issues/90

### System information

windows 10 any

### Issue description

Godot is harder to mod than Unity/Unreal

### Steps to reproduce

Use https://github.com/bruvzg/gdsdecomp to get translations from compiled game. fail

### Minimal reproduction project (MRP)

Use https://github.com/bruvzg/gdsdecomp to get translations from compiled game. fail.

**Comment by akien-mga** [comment]
This is clearly not following our Code of Conduct: https://godotengine.org/code-of-conduct/

If you're not willing to be constructive, we're not going to waste time on our end.
