### ISSUE TITLE
Program crashed with signal 11. Godot 4.2.1

### ISSUE THREAD

**Issue by bodypheo** [godotengine/godot#88556]
### Tested versions

Godot 4.2.1 Linux
Linux info:
```ini
DISTRIB_ID=neon
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="KDE neon 5.27"
PRETTY_NAME="KDE neon 5.27"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="5.27"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy
```

### System information

Linux Kde neon

### Issue description

Hi I have a problem opening Godot v.4.2.1 on my laptop: Thinkpad x220:
I get this error no matter if I open an existing project or a new one. It is the first time I use godot on this computer:

```
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2236)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7fb077442520] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

Just open the software in my laptop... I can test anything you ask me

### Minimal reproduction project (MRP)

Not applicable

**Comment by bodypheo** [comment]
Add --verbose ouptput of the crash:
Loaded system CA certificates
EditorSettings: Save OK!
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
        SPIR-V offset 21952: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    21952 bytes into the SPIR-V binary
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 147308336
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
        SPIR-V offset 22856: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    22856 bytes into the SPIR-V binary
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 147308336
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
WARNING: GENERAL - Message Id Number: 0 | Message Id Name: ../src/vulkan/runtime/vk_nir.c:56
        SPIR-V offset 22016: SPIR-V WARNING:
    Decoration not allowed on struct members: SpvDecorationInvariant
    22016 bytes into the SPIR-V binary
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 147308336
     at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:264)
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
   at: propagate_notification (scene/main/node.cpp:2236)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f66d4842520] (??:0)
[2] llvm::CmpInst::Create(llvm::Instruction::OtherOps, llvm::CmpInst::Predicate, llvm::Value*, llvm::Value*, llvm::Twine const&, llvm::BasicBlock*) (??:0)
-- END OF BACKTRACE --
================================================================

**Comment by bodypheo** [comment]
I have updated the mesa-vulkan-driver to the vesion:
mesa-vulkan-drivers/jammy-updates,now 23.2.1-1ubuntu3.1~22.04.2
With the same result

**Comment by bodypheo** [comment]
I have tried version Godot_v3.5.3-stable_x11.64  and it starts fine without errors.

**Comment by bodypheo** [comment]
More testing I have tried running Godot with the parameters:
--single-window --> Crash
--editor --> Crash
--render-thread safe --> Crash
--path /path/to/project --> Run the project directly fine, it does not open the editor.
--editor --path /path/to/project  --> Crash

**Comment by monxa** [comment]
This seems to be some vulkan spirv incompatibility. I am not an expert in rendering device, so I cannot reason, that godots interface has nothing to do with it, but it seems more plausible to me, that your driver is at fault or that the graphics chip literally doesn't support the necessary vulkan instructions.

Godot 3.5 does not use vulkan. You could try Godot in compatibility mode.
On project creation:
Renderer -> Compatibility.

**Comment by Rubonnek** [comment]
Try:
```
godot --display-driver x11 --rendering-driver opengl3
```
Or
```
godot --display-driver wayland --rendering-driver opengl3
```

**Comment by Mickeon** [comment]
I have modified your issue's description to be much clearer. Keep in mind GitHub formats certain things with its own [special syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

The next time you send an error log, you can prevent it from accidentally polluting the rest of the text and also make the log easier to read.
You may want to use three consecutive backticks:
\`\`\`
Like this.
\`\`\`
Which will display:
```
Like this.
```

**Comment by bodypheo** [comment]
> I have modified your issue's description and following reply to be much clearer. Keep in mind GitHub formats certain things with its own [special syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
> 
> The next time you send an error log, you can prevent it from accidentally polluting the rest of the text and also make the log easier to read. You may want to use three consecutive backticks: ``` Like this. ``` Which will display:
> 
> ```
> Like this.
> ```

Thank you I will keep that in mind.

**Comment by bodypheo** [comment]
> Try:
> 
> ```
> godot --display-driver x11 --rendering-driver opengl3
> ```
> 
> Or
> 
> ```
> godot --display-driver wayland --rendering-driver opengl3
> ```

Thank you the x11 driver did the trick. The wayland parameter is not supported.
It seems that maybe my old GPU can't run vulkan properly.

**Comment by Torakkaa** [comment]
> > Try:
> > ```
> > godot --display-driver x11 --rendering-driver opengl3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or
> > ```
> > godot --display-driver wayland --rendering-driver opengl3
> > ```
> 
> Thank you the x11 driver did the trick. The wayland parameter is not supported. It seems that maybe my old GPU can't run vulkan properly.

I also had my editor crash every two minutes (not even exaggerating) when working on themes. Your second option helped a lot since now I've been running the editor for about 45 minutes without any crashes! Thanks!
