### ISSUE TITLE
Add support for clang-format 5.0+'s split ObjC and Cpp language settings

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8855]
If I apply clang, it is all spaces.

am I doing something wrong?

**Comment by akien-mga** [comment]
What clang-format version are you using? The unstable version 5.0 is known to cause issues, see #8245. You can use the upstream binaries for version 3.9.0 or 4.0.0 from http://llvm.org/releases/download.html, they should work fine (the website seems down right now, so check later maybe).

**Comment by toger5** [comment]
Using 3.9 fixes it. So I close this one? Or should I rename to: Clang_Format 5.0 not supported for.mm

**Comment by akien-mga** [comment]
Renamed, see also #8795. IMO the right solution is to make all settings language agnostic, apart from the C++-specific ones, and (for now) don't provide any ObjC-specific settings (otherwise clang-format < 5.0, i.e. the current stable branches, will choke).

**Comment by akien-mga** [comment]
Just removing the `Language:        Cpp` line might be enough.

**Comment by reduz** [comment]
@akien-mga what do we do with this?

**Comment by akien-mga** [comment]
I'll work on it, will probably up our requirements to clang-format 5.0 anyway to use its better logic for  reflowing comments.

**Comment by volzhs** [comment]
@akien-mga it's fixed now?

**Comment by akien-mga** [comment]
Indeed, thanks for the reminder.

Fixed by #14332.
