### ISSUE TITLE
Rendering error occurs if roughness is greater than 0 when refraction is enabled in Forward Mobile material

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot#88585]
### Tested versions

4.2.1

### System information

WIn 11

### Issue description

https://github.com/godotengine/godot/assets/52212525/fd42781a-973f-4c10-af5e-a088189b1207

### Steps to reproduce

In Forward Mobile

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/14340713/test.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.3.dev 8f0c20ee8 (Linux, GeForce RTX 4090 with NVIDIA 545.29.06). This doesn't occur on Forward+ where it renders correctly.
