### ISSUE TITLE
RenderingDevice's draw_list_begin_for_screen function causes project to crash

### ISSUE THREAD

**Issue by DevPoodle** [godotengine/godot#88580]
### Tested versions

I tested this in:
- v4.2.1.stable.official [b09f793f5]
- v4.3.dev3.official [36e943b6b]

### System information

Windows 10 - Vulkan (Forward+) - NVIDIA GeForce RTX 3060 - 12th Gen Intel(R) Core(TM)

### Issue description

Calling the RenderingDevice function draw_list_begin_for_screen causes the project to immediately crash without any error message.

### Steps to reproduce

Here's code that should produce the bug:
``` gdscript
func _ready() -> void:
	print("a")
	var rd := RenderingServer.get_rendering_device()
	var draw_list := rd.draw_list_begin_for_screen()
	rd.draw_list_end()
```
The bug also happens if it's in physics_process, and even if you don't include draw_list_end(). Alongside crashing the project, it doesn't print "a" in the console or any error message.

### Minimal reproduction project (MRP)

N/A

**Comment by DarioSamo** [comment]
After dev3 the implementation for this has been completely rewritten so it's probably worth a test in `master`.

However I suspect it still won't work, as a new method needed to be introduced that is not bound to gdscript yet: `screen_prepare_for_drawing` which performs the acquisition of the swap chain image.

That said I'm confused at how actually reliable gdscript is for this: the acquisition of the image and blitting the viewports is done at the very last step of rendering before presentation is performed, so gdscript can't exactly do anything there for a viewport you're actually drawing to. It feels like one of those things that are exposed but never actually worked as it'll surely overwrite the result of whatever you draw with the viewport contents.

**Comment by jsjtxietian** [comment]
> After dev3 the implementation for this has been completely rewritten so it's probably worth a test in `master`.

There is no crash in master.

**Comment by DarioSamo** [comment]
> There is no crash in master.

That's good to know, but I imagine it doesn't do anything useful due to what I pointed out above? I guess we can consider this particular issue solved though.

**Comment by DevPoodle** [comment]
Thanks for testing it! I'll close this issue because my particular problem is solved, but I do think that some extra testing to see if the function works properly would be helpful.
