### ISSUE TITLE
Cull mask ignored for GPUParticlesAttractor3D and GPUParticlesCollision3D

### ISSUE THREAD

**Issue by Szotyi2501** [godotengine/godot#88596]
### Tested versions

4.2.1.stable and v4.3.dev.custom_build [9f4499c10]

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

The Cull Mask property of GPUParticlesAttractor3D and GPUParticlesCollision3D completely ignores the VisualInstance3D.layers property of a given GPUParticles3D object, meaning even with no cull mask is set, they still attract and collide with the GPU particles.

Also the second part of the docs for the GPUParticlesCollision3D.cull_mask is a copy-paste from GPUParticlesAttractor3D.

### Steps to reproduce

n/a

### Minimal reproduction project (MRP)

[GPUParticlesBug.zip](https://github.com/godotengine/godot/files/14345307/GPUParticlesBug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/61014.
