### ISSUE TITLE
CollisionPolygon tool is stuck in 2 axis

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#886]
When creating a 3d CollisionPolygon and then use the pencil to start drawing, each point created or moved will have its Z = 0. Changing the rotation of the node affect the existing but the editor will set the Z of any point that the user moves to 0 again.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by neikeq** [comment]
I just tested in the current master branch. It seems to be still valid (both in editor and game). You can check it with the Platformer 3d demo (stage.xml scene).

**Comment by akien-mga** [comment]
Can someone test and confirm?

**Comment by akien-mga** [comment]
I can't seem to reproduce this, the points are by default all aligned in the Z plan (I don't have much 3D experience, my understanding is that CollisionPolygon allows to draw a 2D polygon in a plane and to extrude a 3D shape out of it). But if I rotate the node, then the points are aligned in the arbitrary plan that I chose, and move the points won't reset their Z value to 0.
