### ISSUE TITLE
Error spam on mobile renderer (usage type error)

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#88606]
### Tested versions

- Reproducable in 4.3 master (1aab6e96b96af734d1fe5979d30d1a4232cb270d)

### System information

Windows 10

### Issue description

When using the mobile renderer without any effects such as glow or dof or usage of screen texture, log is getting spammed with:
```
Tracker can't have more than one type of usage in the same draw list. Draw list usage is 15 and the requested usage is 14.
Tracker can't have more than one type of usage in the same draw list. Draw list usage is 15 and the requested usage is 14.
Tracker can't have more than one type of usage in the same draw list. Draw list usage is 15 and the requested usage is 14.
```

### Steps to reproduce

- Create a new project selecting the mobile renderer
- Using the 3 dots environment settings button, turn OFF glow (on by default):
![image](https://github.com/godotengine/godot/assets/1945449/0fe49f52-c5c9-4429-80e3-bf3dbf19a031)

Watch the errors fly by :)

### Minimal reproduction project (MRP)

n/a

**Comment by BastiaanOlij** [comment]
Note that this is caused by Godot applying a 2 subpass approach when no effects are on for maximum performance.
Subpass 1: Renders 3D content to an RGB10A2 buffer
Subpass 2: Reads from the RGB10A2 buffer, tonemaps and color corrects the result, and writes to our RGBA8 output.
This approach results in the RGB10A2 data never leaving tile memory.

Because subpass 1 writes to the RGB10A2 buffer, and subpass 2 reads from this buffer, the error is falsely given.

**Comment by DarioSamo** [comment]
Important clarification: it only gets logged in dev builds as that's the one that detects the error, it won't happen in release builds. It doesn't actually result in an error because the underlying layout is the same Vulkan, but it's an error nevertheless.

I'll look into some possible solutions soon as it requires adding an exception to the graph for the particular case of the color attachment usage in both write and read only modes.

**Comment by BastiaanOlij** [comment]
> Important clarification: it only gets logged in dev builds as that's the one that detects the error, it won't happen in release builds. It doesn't actually result in an error because the underlying layout is the same Vulkan, but it's an error nevertheless.

You'd be amazed at how many users panic when they see errors, esp if it repeats :)

**Comment by DarioSamo** [comment]
> You'd be amazed at how many users panic when they see errors, esp if it repeats :)

Yeah it should get fixed, just clarifying in case someone wants to reproduce it you can only see it in dev build mode.
