### ISSUE TITLE
Shaders do not get compiled nor encrypted when exporting

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#8860]
**Operating system or device - Godot version:**
2.1.x (tested, but probably 3.0 too)

**Issue description:**
When exporting a project containing a shader saved as a `.tres` file (outside of the scene), the shader gets exported as a text file in the `data.pck`.
I was expecting it to be treated like a script (encrypting it if an encryption key is provided) or at least them to be converted to a binary `.shd` file like it's done with the `.tscn` files that gets converted to a `.scn` file.

**Steps to reproduce:**
1. Create a project containing a shader.
2. Export it
3. Check the data.pck with a text editor, you will see the text shader inside

**Link to minimal example project:**
[text_shader.zip](https://github.com/godotengine/godot/files/1018463/text_shader.zip)

**Comment by kubecz3k** [comment]
I'm not sure, but as far as I know this one is still valid.  Probably when we will have Vulcan backend we will be able to address the issue.

**Comment by Faless** [comment]
Yes, this is still valid, script encryption is also gone, I'm trying to bring it back.

**Comment by Xrayez** [comment]
Script encryption is back since #24582 btw, and there's a WIP PR which adds support for the whole PCK encryption instead: #38308.

**Comment by Calinou** [comment]
@blackbeaf https://github.com/godotengine/godot/pull/38308 added PCK encryption support (if you compile your own export template), but since Android doesn't use PCK files, this isn't supported on Android.

See https://github.com/godotengine/godot-proposals/issues/946 which tracks support for using PCK files on Android.
