### ISSUE TITLE
[4.x]Weird rendering results in godot 4.x

### ISSUE THREAD

**Issue by dszhblx** [godotengine/godot#88619]
### Tested versions

Reproducible in 4.3dev3,4.2.1.stable.Not reproducible in 3.5.stable

### System information

Windows 10 - Gotdot 4.3Dev3

### Issue description

I used some Glb models to stitch the map. One of the models is rendered a little strangely in Godot4.3Dev3. Make two copies of this model, rotate one of them -90 degrees along the Y-axis and join them together. At this time, the surface colors of the two instances are inconsistent. But I used the same method to test in Blender and Godot3.5, and the surface colors obtained were consistent.

the surface colors of the two instances are inconsistent:
![glb_4 3](https://github.com/godotengine/godot/assets/8831593/e9d2a554-abe8-47ef-bbad-8c1ca13b1637)

the surface colors obtained were consistent:
![glb_3 5](https://github.com/godotengine/godot/assets/8831593/91ffcd60-e591-4374-8a23-b5c336258133)

### Steps to reproduce

unzip TestGlb.zip and open the project using godot 4.3dev3 or 4.2
open main.tscn

### Minimal reproduction project (MRP)

[TestGlb.zip](https://github.com/godotengine/godot/files/14354153/TestGlb.zip)

**Comment by dszhblx** [comment]
Blender test:
![blender](https://github.com/godotengine/godot/assets/8831593/875a5d1d-951c-4b7f-8868-0d42ffe5fb6e)

U3D test:
![u3d](https://github.com/godotengine/godot/assets/8831593/6871c1cd-2420-49a3-8199-c2494b0ef6bf)

**Comment by Saul2022** [comment]
This is likely to be , because of the lighting defaults, because in 4.x they were modifed to archieve a better default look. Try tweaking the world enviroment node that is in the 3 dots in the top and https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html

**Comment by dszhblx** [comment]
> This is likely to be , because of the lighting defaults, because in 4.x they were modifed to archieve a better default look. Try tweaking the world enviroment node that is in the 3 dots in the top and https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html
> 
> ![Screenshot_2024-02-21-14-49-58-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/97898580/306645790-391ff09f-cd19-4437-b65b-10cfb762229f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzAwMTgsIm5iZiI6MTcwODU2OTcxOCwicGF0aCI6Ii85Nzg5ODU4MC8zMDY2NDU3OTAtMzkxZmYwOWYtY2QxOS00NDM3LWI2NWItMTBjZmI3NjIyMjlmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAyNDE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiY2JmNzExZjQzOTA2MjZhOTFkNTNiMmNlNWEyMmY4ZjAyNjVjMTg4YTFiM2Y5ZjY1NWNiOWJkNjk0ZWMwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwjwg2WdBMI__yQ4KFoz448qZ7DyLJCqZueAlxrOg3k)
> 
> Edit: It may also might be , because 4.2 uses a optimized, try dissabling it, if something changes.

Completely disable environment settings and only use a Directionallight to illuminate the models, the problem still exists：

![light](https://github.com/godotengine/godot/assets/8831593/a2039795-a164-4b42-b7c8-7f1555d54eba)

**Comment by clayjohn** [comment]
Running locally, it looks like the normals are getting compressed wrong

_This is how the normals look_
![Screenshot from 2024-02-23 11-14-58](https://github.com/godotengine/godot/assets/16521339/b0cff171-e2d3-4890-ac7e-f8ab13e94035)

_This is how the normals should look (captured by disabling mesh compression)_
![Screenshot from 2024-02-23 11-15-04](https://github.com/godotengine/godot/assets/16521339/1893e777-a0c4-41de-bc7a-2ad9d86970ef)

**Comment by dszhblx** [comment]
Godot 4.3 dev 4 fixed this bug. Thanks.
