### ISSUE TITLE
The editor freezes for 2 seconds when you enlarge the text size in the script editor.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88624]
### Tested versions

4.3 dev 3

### System information

w10 64

### Issue description

The editor freezes for 2 seconds when you enlarge the text size in the script editor.

This not happen in 3.x

### Steps to reproduce

Press CTRL + mouse wheel to zoom the text in the script editor
The editor will freeze for approximately 2 seconds.

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/82144
