### ISSUE TITLE
Static callable not fully fixed in #41919

### ISSUE THREAD

**Issue by gshadows** [godotengine/godot#88622]
### Tested versions

Reproduced in stable builds 4.2 and 4.2.1 (Windows 10 x64, without mono)

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 5500 XT (Advanced Micro Devices, Inc.; 31.0.14057.5006) - AMD FX(tm)-6300 Six-Core Processor (6 Threads)

### Issue description

Related issue #41919 PR #77129 seems not fully fixed usage of static function as Callable.
Static callable could not be called when caller method is also static, and was called with class name.
Please see reproduce steps to understand better.
Current test cases not include this behavior: [static_func_as_callable.gd](https://github.com/godotengine/godot/blob/master/modules/gdscript/tests/scripts/runtime/features/static_func_as_callable.gd)

### Steps to reproduce

```gdscript
class_name Test
extends Node

static func some_static_func(a:String):
	return null

static func test_callable_parameter(a:String, test_callable:Callable=some_static_func):
	return null

static func test_callable_direct_1(a:String):
	var test_callable:Callable=some_static_func
	return test_callable.call(a)

static func test_callable_direct_2(a:String):
	return some_static_func.call(a)

func _ready() -> void:
	test_callable_parameter("Hi") # This works
	test_callable_direct_1("Hi") # This works
	test_callable_direct_2("Hi") # This works
	Test.test_callable_parameter("Hi") # Invalid get index 'some_static_func' (on base: 'Nil').
	Test.test_callable_direct_1("Hi") # Invalid get index 'some_static_func' (on base: 'Nil').
	Test.test_callable_direct_2("Hi") # Invalid get index 'some_static_func' (on base: 'Nil').
	get_tree().quit()

```

### Minimal reproduction project (MRP)

[Reproduce.zip](https://github.com/godotengine/godot/files/14355456/Reproduce.zip)

**Comment by dalexeev** [comment]
See:

* #86032
* #86088
