### ISSUE TITLE
Touch events not working on Godot 4.2+ on Android 14 after PR #80644

### ISSUE THREAD

**Issue by devantti** [godotengine/godot#88621]
### Tested versions

Reproducible in: 4.3 dev3, 4.2.1 stable
Not reproducible in 4.1.3

### System information

Godot v4.1.3.stable - macOS 14.3.1 - Vulkan (Compatibility) - Apple M3 Pro - Apple M3 Pro (12 Threads)
(Have been tested on older Mac with Intel silicon)

### Issue description

I am creating a small mobile game. I am using https://github.com/Federico-Ciuffardi/GodotTouchInputManager. I updated Godot from 4.1.3 to version 4.2.1 and touch events stopped working. First I thought that problem was in that asset but then I tested godot native events and they didn't work either.

In included demo project it detects for example touch and drag in 4.1.3 but in 4.2.1 it only detects left mouse button and mouse motion. I have tested it in both emulator and on physical device.

I went through change log and didn't noticed any breaking changes that should affect this.

### Steps to reproduce

I created a clean project and added one small script

```gdscript
extends Node2D

@onready var label = $Label

func _input(event: InputEvent):
	label.text = event.as_text()
	if event is InputEventScreenTouch:
		var touch_position = event.position
		var label_node = Label.new()
		label_node.text = "Touch"
		label_node.position = touch_position
		add_child(label_node)
	elif event is InputEventScreenDrag:
		var touch_position = event.position
		var label_node = Label.new()
		label_node.text = "Drag"
		label_node.position = touch_position
		add_child(label_node)
```

### Minimal reproduction project (MRP)

Whole project can be downloaded from: https://drive.google.com/file/d/1-2dK2HoJXY93pOmdzj7exX7wlihuFy_y/view?usp=sharing

**Comment by brcontainer** [comment]
@devantti created an MRP in version 4.3-dev3, I couldn't reproduce the problem. Your MRP weighs more than 150MB, I recommend that you create an actual MRP that reproduces the problem, as the problem is possibly not in the "_input", it could be a UI element that is obstructing something, or another problem, please provide an Minimal reproduction project.

**Comment by devantti** [comment]
Updated MRP to original message, removed android folder.

**Comment by devantti** [comment]
Any ideas how to fix this?

Booted up finally my Windows machine too. Installed all the stuff. Tested both MRP and created also a fresh project. And alas still no luck with touch events on mobile.

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 6800 XT (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

Does it matter what SDK version I have installed. First installed just what came with Android Studio and then by following the instructions at https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html:
sdkmanager --sdk_root=<android_sdk_path> "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;23.2.8568313"

**Comment by devantti** [comment]
Tested with new versions of Godot. Touch works on 4.1.4 but not on 4.2.2 or 4.3 dev 5.

This is frustrating as in 4.1.x deleting tilemap cells defined as scene collection tilemap doesn't work programmatically and it works in 4.2.x: tile_map.set_cell(<layer_id>, <position>, -1, Vector2(-1, -1), -1.

**Comment by Sauermann** [comment]
I have tested the MRP on Debian Linux and exported it to an Android 13 device with the following Godot versions
- v4.2.1.stable.official [b09f793f5]
- v4.3.dev3.official [36e943b6b]
- v4.3.dev5.official [c9c17d6ca]
- v4.3.dev.custom_build [11d376813]

I was unable to replicate the behavior indicated in the screen recording above. For me dragging on the Android device has the effect, that "Drag" and "Touch" Labels are created.

@grumpOldman from what Operating System did you export the MRP? I would like to find out, why I can't replicate this problem.

**Comment by devantti** [comment]
Could Android studio version and other Android libraries affect if it works or not?

**Comment by brcontainer** [comment]
@devantii using exactly your code in v4.2.2.stable.official [15073afe3]:

``` gdscript
extends Node2D

@onready var label = $Label

func _input(event: InputEvent):
    label.text = event.as_text()
    if event is InputEventScreenTouch:
        var touch_position = event.position
        var label_node = Label.new()
        label_node.text = "Touch"
        label_node.position = touch_position
        add_child(label_node)
    elif event is InputEventScreenDrag:
        var touch_position = event.position
        var label_node = Label.new()
        label_node.text = "Drag"
        label_node.position = touch_position
        add_child(label_node)
```

Running on **Samsung M31** device works fine:

https://github.com/godotengine/godot/assets/4368952/7c84fb97-ae28-4216-a2dc-4344d292d859

**Comment by Sauermann** [comment]
@brcontainer what operating system do you use?

**Comment by brcontainer** [comment]
@Sauermann I'm using Windows 10 to generate the APK.

But keep in mind that I'm not building locally, I'm generating the APK from the export template (mirror: `https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz`)

**Comment by brcontainer** [comment]
@Sauermann @devantti

I installed Android Studio, tested it using the emulator, and was able to reproduce the error. To be more direct, the problem occurs in the device emulator (QEMU: https://developer.android.com/studio/run/emulator).

**Comment by Sauermann** [comment]
I can confirm the bug on Linux when exporting the project to an emulator.

@devantti You have mentioned, that you experience this bug also on a physical device. Can you please verify this and tell, on which physical device you experience this bug? Otherwise it looks like this affects only emulators.

I have bisected this bug to #80644 CC @Distantz

**Comment by devantti** [comment]
@Sauermann: Exported my project to Android on Godot v4.2.2.stable.official [15073afe3] with both use gradle build set on and off. Tested on Samsung Galaxy S23 (SM-S911B/DS) with Android version 14 and it didn't work.

I did also double check and exported Godot v4.1.4.stable.official [fe0e8e557] and it works on same device.

**Comment by Sauermann** [comment]
I have investigated the difference of behavior, when running the MRP on the emulator and on a Sony Android 13 device.

The behavior differs for this code section:

https://github.com/godotengine/godot/blob/6118592c6d88350d01f74faff6fd49754f84a7d0/platform/android/java/lib/src/org/godotengine/godot/input/GodotInputHandler.java#L447-L453

- On the hardware device: `eventSource = 4098` (0x1002)
- On the emulator: `eventSource = 20482` (0x5002)

Looking at https://developer.android.com/reference/android/view/InputDevice we get the following difference between the input events sent from the emulator/device:

| Event source | Emulator  | Hardware Device |
| --- | --- | --- |
| SOURCE_CLASS_POINTER (2^1, 0x2)  | yes | yes |
| SOURCE_TOUCHSCREEN (2^12, 0x1000)  | yes | yes |
| SOURCE_STYLUS (2^14, 0x4000)  | yes | no |

So it looks like the comment https://github.com/godotengine/godot/pull/80644/files#r1297848312 was justified and the change of that PR introduced this issue.

Without a Pen, I can't properly test, if changes to the above function will break https://github.com/godotengine/godot-proposals/issues/735

**Comment by akien-mga** [comment]
Sounds like we may have a difference in behavior between Android 13 and 14 in this API?

**Comment by Sauermann** [comment]
I have tested the MRP on an emulator with both an Android 13 and an Android 14 image.
For me the bug happens on both Android versions.

**Comment by Distantz** [comment]
Apologies, I can't remember the exact circumstances around the removal of that line, but I remember it was effecting stylus events in some way.

**Comment by andrewrexo** [comment]
I can replicate the issue on my Pixel 7 Pro running Android 13. However, my Pixel 6A running Android 14 running Android 14 is unaffected. Touch events are sent as expected.

**Comment by AlexanderO88** [comment]
I can confirm with my FireHD 8 (2020) and Godot 4.2.2. I just use the Godot Editor on Android and doesn't have export my project yet but with Godot 4.2.2 the touch events doesn't work, with Godot 4.1.4 it works.
