### ISSUE TITLE
Editor theme color renames break compatibility for plugins

### ISSUE THREAD

**Issue by Jowan-Spooner** [godotengine/godot#88626]
### Tested versions

4.3 dev3 (colors don't work), 4.3 dev2 (colors still work)

### System information

non-relevant (Windows 10 though)

### Issue description

https://github.com/godotengine/godot/pull/87085 has renamed many of the color theme items of the editor theme, others have been removed (Of course the difference between a removed and a renamed color are hard to tell, but some got obvious replacements).  
It is common practice in editor plugins to make use of the colors/fonts/icons that the editor theme already provides. Any use of these (colors) will now break from 4.2 to 4.3. This is rather annyoing as having a plugin look correct on both of these versions becomes a very unncessary pain. 

As one of the dialogic developers I noticed this change when testing the plugin with 4.3 dev 3. It is not present in 4.3 dev 2

Here are the colors in 4.2.x:
![colors_old](https://github.com/godotengine/godot/assets/42868150/96350e0f-f390-4701-a4a3-0e87c2234a48)
And here in 4.3:
![grafik](https://github.com/godotengine/godot/assets/42868150/175086b4-a960-40de-b68e-499c3826e6dd)

Notable renames are: 
- readonly_font_color -> font_readonly_color
- disabled_font_color -> font_disabled_color
- disabled_highlight_color -> highlight_disabled_color 

Seemingly removed ones:
- highlighted_font_color
- property_color
- readonly_color

There is a small chance this has never been intended to be used, however I find that unlikely as the person who made these changes had previously made a plugin to more easily see and copy these colors for use in plugins. Also they are very clearly accessibly with easy-to-use methods.

I have not checked whether there are also icon, font or stylebox renames/changes. that might break and have only checked the "Editor" section, not specific classes. However it is most likely that the items in the "Editor" category have been used by plugins in my experience.

### Steps to reproduce

Use any of these colors in a project in 4.2 and 4.3 dev 3.

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
> Notable renames are:
> 
> * readonly_font_color -> font_readonly_color
> * disabled_font_color -> font_disabled_color
> * disabled_highlight_color -> highlight_disabled_color

Seems pretty straightforward and doable to introduce aliases for these (and note them as such in the code so they can be safely removed when reasonable).
Not sure how reasonable it is to handle the rest, though, as chances are their removal is justified in someway. Perhaps they were too similar to other colors, potentially redundant or underutilised.
