### ISSUE TITLE
Setting portal active to false results in portal_set_active: Condition "!portal->scenario" is true. error

### ISSUE THREAD

**Issue by herbertmaa** [godotengine/godot#88637]
### Tested versions

- Reproducible in 3.5.3-stable , 3.5.2-stable

### System information

MacOS(ARM64) - Godot v3.5.3-stable

### Issue description

When using portals, you can set portals to be inactive when building your rooms / scenes. However, this results in an error output unless all portals are set to active when the scene is loaded. 
E 0:00:00.295   portal_set_active: Condition "!portal->scenario" is true.
  <C++ Source>  servers/visual/visual_server_scene.cpp:1461 @ portal_set_active()

### Steps to reproduce

Load a scene with portals where at least one portal is set to inactive. 

### Minimal reproduction project (MRP)

[portal_room_no_scenario_godot3.zip](https://github.com/godotengine/godot/files/14363102/portal_room_no_scenario_godot3.zip)

**Comment by akien-mga** [comment]
Fixed by #88807.
