### ISSUE TITLE
Can't select first character with mouse in script editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88632]
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

w10 64

### Issue description

I don't know if this is important or not but I have the following options activated:

![Captura4](https://github.com/godotengine/godot/assets/19652075/91295b87-b620-4158-a575-f263533d6db0)

As you can see in the video, it is impossible to select the first character by dragging the mouse over it.
If I click several times on the text, then the character is included in the selection

https://github.com/godotengine/godot/assets/19652075/d51045d7-1a0e-4237-a719-d66562834a70

### Steps to reproduce

Watch the video

### Minimal reproduction project (MRP)

...

**Comment by akien-mga** [comment]
Fixed by #95301.
