### ISSUE TITLE
Viewport related settings are not updated realtime

### ISSUE THREAD

**Issue by maidopi-usagi** [godotengine/godot#88642]
### Tested versions

Godot v4.3.dev (846d075a2)
Godot v4.3 dev3 (for comparison)

### System information

Godot v4.3.dev (846d075a2) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4592) - 13th Gen Intel(R) Core(TM) i7-13700F (24 Threads)

### Issue description

Tuning parameters that related to 3d viewport, such as scaling ratio and antialiasing options, seems have no effect, until reloading the whole project.
Tested on Godot v4.3 dev3, and everything works fine.

https://github.com/godotengine/godot/assets/33864304/97427428-1c3f-43ab-bdd1-e1444d8c97e7

### Steps to reproduce

1. Open the Minimal Reproduction Project using the latest build
2. Open project settings, and play around Scaling 3D-Scale, and antialiasing options

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14363391/MRP.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.3.dev 846d075a2f2333b4ba4cbca48a96484015b31031 (Linux). I'm bisecting it now.
