### ISSUE TITLE
Inconsistent script switching

### ISSUE THREAD

**Issue by mubinulhaque** [godotengine/godot#88640]
### Tested versions

Tested in v4.2.1

### System information

Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 SUPER (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 Threads)

### Issue description

Selecting a scene should ideally also select the script that was last selected in that scene. Instead, a script is randomly selected from the ones currently open, with no indication as to how this script was selected.

### Steps to reproduce

1. Open multiple scenes
2. Open multiple scripts
3. In each scene, open a different script
4. Switch between scenes
5. Notice how switching between scenes selects a random script each time

This is noted in the video below:

https://github.com/godotengine/godot/assets/80097192/aaaff4a5-b880-47b4-b70f-d74c9f150b84

### Minimal reproduction project (MRP)

N/A - any project with multiple scenes and scripts can reproduce this issue

**Comment by Cammymoop** [comment]
It doesn't pick a random script. When you switch scene tabs, the script attached to the scene root is chosen, and if there isn't one it will search the scene tree for a node with a script attached (this appears to be depth first) and that script is switched to. It also opens that script if it wasn't already opened.

If you want to suggest improving the current functionality please open a proposal here https://github.com/godotengine/godot-proposals/issues

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8372.
