### ISSUE TITLE
Text/icons are slightly moved when hovering buttons if Draw Extra Borders editor setting is enabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#88644]
### Tested versions

- Reproducible in: 4.3.dev 652438a3952ae13e12dd4fd40756311fde81a791
- Not reproducible in: 4.2.1.stable, 4.3.dev 8f0c20ee8

### System information

Godot v4.3.dev (652438a39) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Text/icons are slightly moved when hovering buttons if Draw Extra Borders editor setting is enabled. This editor setting is automatically enabled by the **Black (OLED)** editor theme preset, but you can also enable it separately.

This is likely a regression from https://github.com/godotengine/godot/pull/86378. cc @RobProductions 

### Draw Extra Borders disabled

https://github.com/godotengine/godot/assets/180032/63cc897c-f818-41b7-86ff-6117152921a8

### Draw Extra Borders enabled

https://github.com/godotengine/godot/assets/180032/bef8a337-8cef-4c1c-b160-457cf02ff9f2

### Steps to reproduce

- Switch to the **Black (OLED)** editor theme preset or enable the **Draw Extra Borders** editor setting.
- Hover the MenuButtons at the top-left corner of the editor.

### Minimal reproduction project (MRP)

N/A

**Comment by RobProductions** [comment]
Whoops, apologies for missing the extra borders setting. Is this a result of mismatch in border width between the "hover" and "non-hovered" styleboxes as set [here](https://github.com/godotengine/godot/blob/16d61427cab3a8e43f0a9a8ee724fc176b6433c6/editor/themes/editor_theme_manager.cpp#L545)? Or is it possible some other margin/alignment variable wasn't defined right for the new styles? I can do some experiments later today to narrow it down and will try to whip up a fix unless someone else spots the issue first
