### ISSUE TITLE
A Bug on InputEvent

### ISSUE THREAD

**Issue by FakerDomain** [godotengine/godot#88653]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows10-Godot 4.2.1 stable-Forward+

### Issue description

I set the custum input buttom as:
![image](https://github.com/godotengine/godot/assets/13235429/2821b1f1-f7e6-48af-9c48-33bc441db5c6)

``

I use this code to control my character
`Input.get_vector("move_left", "move_right", "move_up", "move_down")`

At the same time, I supervise other inputs from my keyborad by using:
![image](https://github.com/godotengine/godot/assets/13235429/52429912-6aa2-479d-9da4-d02257229ccf)

When I press 'W' 'S' 'A' 'D' to move my character, everything is just fine, the character can move smoothly to each eight directions around.

The problem is that, when my character is moving to top-left corner by pressing both "W" and "A", at this moment, I press the "normal_attack" key, and nothing happens....even the [print("Attack!!!!")] is not excuted....

However, the code works just fine when the character is moving to top-right (press "W" and "D"), buttom-left (press "A" and "S"), buttom-right ("D" and "S")....the code of "print("Attack!!!!")" is correctly excuted....

Moreover, when I use "Arrow-Right" "Arrow-Up"  "Arrow-Down" and "Arrow_Left"  instead of "W" "S" "A" "D" to move my character, this problem disappeared...

So, is this a bug?

### Steps to reproduce

Write move control (can move eight directions) related code in " func _physics_process(delta: float) -> void: "

Then use " func _input(event: InputEvent) -> void: " to detect other keyboard inputs.

When press "W" and "A" to move the character, at the same time, press another custom button, and check if the pressing can by detected by  " func _input(event: InputEvent) -> void: " 

### Minimal reproduction project (MRP)

N/A

**Comment by Sauermann** [comment]
You might run into the problem of [Keyboard Ghosting](https://en.wikipedia.org/wiki/Key_rollover).
