### ISSUE TITLE
Remote debug on Quest stalls

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#88651]
### Tested versions

- Reproducible on 4.3 652438a3952ae13e12dd4fd40756311fde81a791 - Quest 3

### System information

Quest 3

### Issue description

When starting an XR project from the remote debug button in the IDE, the project is pushed out to the Quest, starts on the Quest and then hangs.
Quitting the IDE at this point will result in the project starting as normal. It looks like the remote debug session is waiting on something that never happens.

I do not know if this is specific to Quest or an issue on other Android devices as well.

### Steps to reproduce

Export a project to the Quest 3 using the remote debug button in the Godot IDE.

### Minimal reproduction project (MRP)

https://github.com/BastiaanOlij/godot_openxr_demo
(note, install android build templates to test!)

**Comment by BastiaanOlij** [comment]
cc @m4gr3d

**Comment by akien-mga** [comment]
You marked this as a regression, I assume it means it worked fine in previous releases. Do you know which releases worked fine?

**Comment by BastiaanOlij** [comment]
> You marked this as a regression, I assume it means it worked fine in previous releases. Do you know which releases worked fine?

No idea, but since I use this nearly daily whenever I test XR stuff on Quest, it is likely a recent change.

**Comment by BastiaanOlij** [comment]
(though come to think of it, I've mostly been testing OpenGL stuff in the last weeks, so if it is something related to Vulkan, it could be in there longer).

**Comment by BastiaanOlij** [comment]
Some more info, just noticed with the developer hub that logcat gets spammed with:
```
USER ERROR: Condition "!_start_success" is true. Returning: false
21:40:37.254
godot
at: start (main\main.cpp:3112)
21:40:37.254
godot
USER ERROR: Condition "!_start_success" is true. Returning: false
21:40:37.254
godot
at: start (main\main.cpp:3112)
21:40:37.254
godot
USER ERROR: Condition "!_start_success" is true. Returning: false
21:40:37.254
godot
at: start (main\main.cpp:3112)
```

That looks awfully familiar.

**Comment by akien-mga** [comment]
Possibly related to #87823 ?
