### ISSUE TITLE
VoxelGI shows incorrect reflections when UV is being modified by a material.

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#88663]
### Tested versions

Reproducible in 
v4.3.dev2.official [352434668]
v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.3.dev2 - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 14:02:33 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 545.29.06) - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

Incorrect lighting is shown when triplanar lighting is enabled.
(screenshots on godot 4.3 dev2)
![image](https://github.com/godotengine/godot/assets/69520693/d33f20d3-d5b5-497c-83be-3a6cded7ce16)
![image](https://github.com/godotengine/godot/assets/69520693/8262db9f-2311-4bf0-98d6-79d5b6b84a51)
A workaround is to completely disable albedo textures before rebaking but i have a feeling it doesnt really fix the issue.
Notably, this is **NOT** a subdivision issue, setting it to 512 still does not fix it.

### Steps to reproduce

In the included minimal reproduction project: 
![image](https://github.com/godotengine/godot/assets/69520693/826d8292-74d3-47cb-b6bf-dacf0f6f2e9d)
(screenshot on godot 4.2.1)
You can clearly see how this doesn't line up.
On godot 4.3 dev2, the issue is mitigated, but not completely.
![image](https://github.com/godotengine/godot/assets/69520693/d96d0124-3e67-4050-a7e0-73349b7796e7)

### Minimal reproduction project (MRP)

[minimal.tar.gz](https://github.com/godotengine/godot/files/14373854/minimal.tar.gz)

**Comment by RadiantUwU** [comment]
![image](https://github.com/godotengine/godot/assets/69520693/1a600121-8a0a-4018-a7af-eddbc8577da9)
From the minimal reproducible project (removed some textures to get size down)

**Comment by RadiantUwU** [comment]
Taking a look at the code, it's quite clear where it should be modified
https://github.com/godotengine/godot/blob/master/scene/3d/voxelizer.cpp
This code doesn't contain any handling for UV modification

**Comment by RadiantUwU** [comment]
NOTE:
This applies only to materials that modify UV, not meshes.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52115.
