### ISSUE TITLE
Regression in InstancePlaceholder behavior, instanced scene missing Node property values

### ISSUE THREAD

**Issue by TheOrioli** [godotengine/godot#88662]
### Tested versions

- Reproducible in 4.3.dev3
- Works as expected in 4.2.1

### System information

Godot v4.3.dev3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When instantiating a node using `InstancePlaceholder.create_instance()` the newly instantiated node is missing exported Node properties.

This is the expected result ( viewed in Remote tab)
![image](https://github.com/godotengine/godot/assets/2500134/2b063f80-948d-498e-adc2-cdeb70ddecaa)
this is what happens instead 
![image](https://github.com/godotengine/godot/assets/2500134/56c06f36-f468-473b-be3a-49a560e90cd7)
( number change is due to me changing it in between screenshots 😅)
Nested scenes are not affected and seem to instantiate with all properties set. Issue appears in both GDScript and C#. 
Everything works as expected on 4.2.1

### Steps to reproduce

Open the attached MRP, and run `main.tscn`
Check the Remote tab and see the properties missing.

For ease of comparison the `Main` node has a bool 
![image](https://github.com/godotengine/godot/assets/2500134/d72eaffd-f415-4435-80e8-9288696dca8a)
which will trigger loading the same scene manually using `InstancePlaceholder.get_instance_path()` instead. This approach works fine.

### Minimal reproduction project (MRP)

[PlaceholderInstanceRepro.zip](https://github.com/godotengine/godot/files/14373332/PlaceholderInstanceRepro.zip)

**Comment by Ratamacue9112** [comment]
I think PR https://github.com/godotengine/godot/pull/83343 introduced the problem.

**Comment by TheOrioli** [comment]
Tested with the latest release, the issue is present on 4.3.dev4

**Comment by akien-mga** [comment]
I can confirm the issue described in the OP with 4.3-dev1 to 4.3-dev4 and current `master`.
A local revert of #83343 solves it, confirming https://github.com/godotengine/godot/issues/88662#issuecomment-1962340872.

CC @warriormaster12 @KoBeWi @RandomShaper

**Comment by warriormaster12** [comment]
Reproduced the bug, I have this pr open https://github.com/godotengine/godot/pull/87387 that maybe will fix this issue. I’ll test at home if I can reproduce this bug with it. If I can then I’ll try to fix this issue in the same pr.

**Comment by akien-mga** [comment]
> Reproduced the bug, I have this pr open #87387 that maybe will fix this issue. I’ll test at home if I can reproduce this bug with it. If I can then I’ll try to fix this issue in the same pr.

Tested #87387, it doesn't seem to solve this bug currently.

**Comment by warriormaster12** [comment]
https://github.com/godotengine/godot/pull/83343/https://github.com/godotengine/godot/pull/83343/files#diff-48f7cbbe79aef11b2e739c2c371700d4baf1e49a8abe3eaf7bfbab004b4d0fcbR84

Found the place that causes this regression. Commenting the if-statement fixes it though it introduces another bug in ```is_property_value_different``` ```function where a == Nodepath``` and ```b == Object```. However, as far as I know it's only related to ui so maybe it could be removed until a better solution is found?

**Comment by Mickeon** [comment]
What's progress on a solution for this issue?

**Comment by warriormaster12** [comment]
Not at the moment. I haven't had that mich to take a look further how to resolve the issue. I only know that somewhere the value changes to null because of the changes that I have made in property_utils.cpp

**Comment by TheOrioli** [comment]
It seems there are a couple of problems with InstancePlaceholders being instantiated.
When instantiating a PackedScene that contains an InstancePlaceholder a couple of things will happen:

1. Node references and Node Arrays will be deferred and will attempt to resolve. This will result in null nodes, since they don't exist yet. 
https://github.com/godotengine/godot/blob/7a42afbba050822a66ea5b4c620f6db1b98c49af/scene/resources/packed_scene.cpp#L316-L325
https://github.com/godotengine/godot/blob/7a42afbba050822a66ea5b4c620f6db1b98c49af/scene/resources/packed_scene.cpp#L511-L528
This will wrongly set null values in the InstancePlaceholder https://github.com/godotengine/godot/blob/7a42afbba050822a66ea5b4c620f6db1b98c49af/scene/main/instance_placeholder.cpp#L36-L42

2. Typed NodePath arrays will not have their type set, while e.g. int and string arrays will. This will cause a failure when type checking the array during PackedScene instantiation https://github.com/godotengine/godot/blob/7a42afbba050822a66ea5b4c620f6db1b98c49af/scene/resources/packed_scene.cpp#L356-L369 and later cause a failure when attempting to set the array property value, since type checking of an untyped Array automatically fails https://github.com/godotengine/godot/blob/7a42afbba050822a66ea5b4c620f6db1b98c49af/modules/gdscript/gdscript_function.h#L75-L100

This is as far as I've gotten with this for now. But it's smelling more and more to me that InstancePlaceholders will need a bit more information to properly set everything up. Naturally, I barely know what I'm doing 🤷‍♂️ Here is my little experimental fork that works with internal node references, but breaks on arrays and external nodes https://github.com/TheOrioli/godot/commit/fe34765cb90fd7d2a162feeb45abe551577edb51

Here is a modified test project that includes even more test cases. I've added both external node references, as well as Node and Nodepath arrays. One of the arrays is mixed, containing both internal nodes and external nodes. As a user I would expect all those references to remain.
[PlaceholderInstanceRepro.zip](https://github.com/godotengine/godot/files/14873297/PlaceholderInstanceRepro.zip)
