### ISSUE TITLE
Editor getting unusable after commit c3baf5e on Lubuntu 17.04

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#8866]
**Operating system or device - Godot version:**
Lubuntu 17.04 (also 16.10) 64bit
Godot from this commit: https://github.com/godotengine/godot/commit/c3baf5eb3cf71c6645e2b721c09d284db0f630b2 and going on.

**Issue description:**
What happened(1): Images loaded as texture/sprite are black squares
What happened (later commits) (2): Create a new project from Project Manager makes godot Crash
What was expected(1): Images should be shown as b69d4eb and previous commits
What was expected(2): Godot should be able to create new project without crash.

**Steps to reproduce:**
for black square:
1. download c3baf5eb3cf71c6645e2b721c09d284db0f630b2 or later commit
2. compile (scons platform=x11) and launch binary
3. create a new project and a new sprite node
4. load the icon.png in the sprite node.
result = black square shown in place of the bitmap

for more recent commit
1.download&compile the latest  commit
2. run godot project manager and create a new project
result = crash when pressing the button [Create] (after creating the directory)

**Link to minimal example project:**
screenshot of the same project running in the two different instances of godot:
https://matrix.org/_matrix/media/v1/download/matrix.org/riHIZCJwKbBemxtmNmUfoEss

link to the compiled binaries:
https://matrix.org/_matrix/media/v1/download/matrix.org/vMRWjGfgXefxjIzHNTZxbdxU

**Comment by Zireael07** [comment]
1) (black images) is a known falloff of the recent changes to Image class.

**Comment by alexwbc** [comment]
Then I should wait and use the older commit before issue more bug report? Becose I am getting other issues as well: like I can't use fonts anymore (commit b69d4eb could use font imported with old godot, but c3baf5e gives "Error Loading File: not a resource" )?

**Comment by eon-s** [comment]
I cannot use the mouse wheel nor type on script window, also random crashes (maybe related to input changes), so we will have to stay with old versions for a while.

**Comment by eon-s** [comment]
About the fonts, on 2e3145de6, with most crashes solved, I can create a new DynamicFont and use a ttf or otf as font data, I can't use the importer to "make" fonts so is not possible to make Bitmap fonts. 

I don't know how should be the new behaviour when (auto)importing fonts.

**Comment by alexwbc** [comment]
With the last commit 2e3145de65257ed39a5d01c5592ea0fb90cd00ba now Godot editor is able to render bitmap and there are no more crashes related to the creation of new project.

Sadly, new bugs emerged (kind keyboard doesn't work in some area: ie, you can't write in script editor or use hotkeys, but still you can rename nodes, use search help etc...).
I guess it's better to close this one to avoid clutter tho.
