### ISSUE TITLE
Inconsistent types for Peer ID in C#

### ISSUE THREAD

**Issue by 3da** [godotengine/godot#88672]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Windows 10

### Issue description

Multiplayer.GetUniqueId()
returns **int**

public delegate void PeerConnectedEventHandler(long id);
Has type **long**

### Steps to reproduce

Not required.

### Minimal reproduction project (MRP)

Not required.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88127
