### ISSUE TITLE
Joypad vibration not working on macOS Sonoma

### ISSUE THREAD

**Issue by Meorge** [godotengine/godot#88674]
### Tested versions

- Reproducible in v4.3.dev3.official [36e943b6b], v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.dev3 - macOS 14.3.1 - Vulkan (Forward+) - dedicated AMD Radeon Pro 5500 XT - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

On macOS, the `Input.start_joy_vibration()` function seems to have no effect. I have tested it with:
- Xbox Wireless Controller (model 1708), both wirelessly and plugged in via Micro-USB
- DUALSHOCK 4 Wireless Controller (model CUH-ZCT2U), both wirelessly and plugged in via Micro-USB

This doesn't seem to be a macOS-side issue, as from the System Settings > Game Controllers menu, I can click "Identify" when either of the controllers are connected and they will vibrate.

**NOTE: This sounds an awful lot like the issue addressed with #80709. It was merged 2 days ago, whereas 4.3-dev3 was from 14 days ago. If I have time soon, I may be able to try building the current `master` branch and seeing if it's fixed.**

### Steps to reproduce

In general, you can include a line like `Input.start_joy_vibration(0, 1.0, 1.0, 1.0)` somewhere, and when run, the controller will not vibrate.

In my MRP, as the game screen suggests, you can press the "east" button (B on Xbox Wireless Controller, Circle on DUALSHOCK 4) to call `start_joy_vibration`. A confirmation message will be printed with the parameters being sent to the function.

### Minimal reproduction project (MRP)

[ControllerVibrationTest-4.3dev3 packaged.zip](https://github.com/godotengine/godot/files/14377579/ControllerVibrationTest-4.3dev3.packaged.zip)

**Comment by Calinou** [comment]
Can you try the latest GitHub Actions build of the `master` branch? https://nightly.link/godotengine/godot/actions/runs/8007280917/macos-editor.zip

Note that CI builds aren't notarized, so you'll have to follow instructions on [Running on macOS](https://docs.godotengine.org/en/latest/tutorials/export/running_on_macos.html).

**Comment by Meorge** [comment]
Just tested it, and controller vibration is indeed working with v4.3.dev.gh [b15105a35]! 😁 

Thanks so much for suggesting that, and I'm sorry I didn't catch that those builds were an option. In the future I'll be sure to check those as well :)

I assume this means the issue can be closed? For now, I'll leave it open just in case either there's other things to tackle or closing issues is only supposed to be done by maintainers. Thanks again!

**Comment by Calinou** [comment]
Closing as the [original issue](https://github.com/godotengine/godot/issues/14634) was resolved by https://github.com/godotengine/godot/pull/80709
