### ISSUE TITLE
`+[NSString stringWithUTF8String:]: NULL cString` is printed on every engine startup

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#88686]
### Tested versions

- Reproducible in: 4.3.dev https://github.com/godotengine/godot/commit/b15105a3585c29c8448f3d2dc8fe20a578a2b41b, 4.2.1.stable, 4.1.3.stable, 4.0.4.stable

### System information

macOS Ventura 13.4.1 - Apple M1 Mac mini 2020

### Issue description

A debug message is printed before every startup of the editor or project, even if `--quiet` is specified:

```
$ godot
2024-02-22 22:22:48.779 godot[1442:13781] *** +[NSString stringWithUTF8String:]: NULL cString
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
OpenGL API 4.1 Metal - 83.1 - Compatibility - Using Device: Apple - Apple M1
```

This only occurs on macOS.

### Steps to reproduce

- Start Godot from a terminal (whether it's inside an .app bundle or not, this occurs regardless).

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
I can't reproduce it, but there are only two calls to this function that are not `utf8().get_data()`, and I suspect the source is `DirAccess::fix_unicode_name`, so `readdir` is returning an entry with null filename (probably some permission issue). In any case, I'll add checks.
