### ISSUE TITLE
GridMap "Painting Tile" Always Visible

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#887]
Hey, there. So basically, if you use a GridMap to paint tiles and then select a new node (thereby "deselecting" the GridMap and "exiting" drawing mode), the last used tile will still be visible where it last was before you switched nodes.

**Comment by kubecz3k** [comment]
Remember this bug. Tried to reproduce with d123c89c5802777e02402108d9271ed2f29368fe it looks like it's fixed now.
