### ISSUE TITLE
Terminal doesn't display translated text in UTF-8

### ISSUE THREAD

**Issue by DidierMorandi** [godotengine/godot#88715]
### Tested versions

Godot Engine v4.2.1.stable.official.b09f793f5

### System information

Windows 10 OpenGL3

### Issue description

Just installed Godot to help me translate the documentation.
When Godot starts, I get this:
![GodotBug](https://github.com/godotengine/godot/assets/10167832/a3d9e690-9b75-4bbb-9ad9-d6a6544c09c1)
Looks like translated messages were not coded in UTF-8.
Advices?

### Steps to reproduce

n/a

### Minimal reproduction project (MRP)

n/a

**Comment by DidierMorandi** [comment]
Should read: "L'import des fichiers blend est activé dans les paramètres du projet, mais aucun chemin vers Blender n'est configuré. Les fichiers blend ne seront pas importés".

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/87591

Which is the same bug
