### ISSUE TITLE
"Documentation Check" GitHub Action always fails: permission denied

### ISSUE THREAD

**Issue by Repiteo** [godotengine/godot#88719]
### Tested versions

N/A

### System information

N/A

### Issue description

One of my PRs #78656 now consistently fails when attempting the documentation check action, preventing further testing and validation of the code itself. Building the engine and creating documentation locally doesn't have this problem, only occuring on the GitHub Actions for the main repo & my forked repo. The error message always returns as:
```
/home/runner/work/_temp/8356b651-e144-48ce-98f0-470ff4690efe.sh: line 2: doc/tools/make_rst.py: Permission denied
Error: Process completed with exit code 126.
```
Unsure if this is a bug specific to GitHub itself, or if something changed in Godot's repo elsewhere to cause this.

### Steps to reproduce

Doesn't seem applicable; appears specific to GitHub Actions

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
It looks like you [changed](https://github.com/godotengine/godot/pull/78656/files#diff-8cfde96f29054d38628a87af04b23d77280174c3d31df0c38a23cbd34bce960a) the file permissions in the PR:

> doc/tools/make_rst.py 100755 → 100644

Also I'm not sure if Python allows you to declare nested functions.

**Comment by Repiteo** [comment]
How in the world did that happen? I haven't touched file perms once. Maybe something went awry in the rebase? Either way, I'll try to fix that, but I've never done perm changes via commit before so hopefully it's not that big of a hurdle.

Also nested functions are supported & already used elsewhere in the repo, not to mention running the file locally works like a charm, so that shouldn't be a factor. If the perm issue doesn't resolve this, it won't hurt to remove the nesting just to see if that's correlated, but it shouldn't have to come to that.

**Comment by Repiteo** [comment]
Took some rebasing, but that fixed the issue! Still no clue why it happened in the first place, but at least I know how to handle this if it crops up again.
