### ISSUE TITLE
Add OS.get_screen_metric()

### ISSUE THREAD

**Issue by fluffrabbit** [godotengine/godot#8871]
Combining OS.get_screen_dpi() with OS.get_screen_size() does not return accurate values for the physical screen dimensions.

Children have IOD's of 6 cm, women in the armed forces have IOD's of 6.2 cm, I have an IOD of 6.35 cm and some giants have IOD's around 7 cm. It's all in a narrow enough range that some error can be tolerated. But screen sizes are not in a narrow range. There are $8 Android devices now with 7.6 cm screens, $25 devices with 11.4 cm screens, and your grandma probably has one with a 15.2 cm screen.

To save players from manually typing things in, any game engine worth its salt should be able to return the physical dimensions of the screen. This would help greatly with mobile VR and would integrate well with related PRs.

I will be indisposed for the next month as work has really caught up with me. This thread serves as a log of mine and others' progress towards getting proper screen size detection in Godot. I am linking [a 2.1 test case](https://github.com/fluffrabbit/TestScreenSize) that does what it can with OS.get_screen_dpi() and OS.get_screen_size().

**Comment by fluffrabbit** [comment]
Working on the Android version of get_display_metric() which is supposed to return a Vector2 of the screen width and height in meters. It turns out display metrics must be retrieved in Java because of course Godot is oldschool and uses the JNI rather than pure C++. Having difficulty returning non-primitive data (2 floats at once) from Java to C++ as I have never used the JNI before due to contempt for the very idea of it, and my contempt is not unfounded. Then again it's not my area of speciality so these aren't really valid complaints.

**Comment by volzhs** [comment]
can other platforms also get this? x11, windows, osx, ios?

**Comment by fluffrabbit** [comment]
@volzhs In theory, yes. This is primarily of interest to VR, so relevant more to displays 6" or smaller. The iOS port would be the next thing. X11, Windows, and OSX would be just like implementing any other cross-platform features, using platform-specific APIs and sending the data to the game. Of course, I am starting with the unit of meters which seems to imply larger displays, and there are much larger displays out there. Generally if you want a rough approximation of the screen size you can do something like OS.get_screen_size().x / OS.get_screen_dpi(), but in the case of Android and anything with non-square pixels the measurements are off.

**Comment by fluffrabbit** [comment]
Well, I have fucked with it beyond all rationality, lost track track of what I was doing, tried a new substance and I now have no idea what anything is, but I remember that this is somehow relevant, for whenever I or someone working in my stead arrives at the proper state of mind (and by the way its build is failing):

https://github.com/fluffrabbit/not-godot/search?q=metric

**Comment by akien-mga** [comment]
Closing as the issue has not received any update in a long time and does not seem to gather much interest from the community. There might be some use in having better metrics on the device screen though, but it's not a priority for the time being.
