### ISSUE TITLE
Trail particles activated before fully initialized

### ISSUE THREAD

**Issue by permelin** [godotengine/godot#88712]
### Tested versions

4.2.1.stable
4.3.dev.custom_build.87d40ba74

### System information

Godot v4.3.dev (87d40ba74) - Debian GNU/Linux - X11 - Vulkan (Forward+)

### Issue description
At the start of emission, `process()` in `GPUParticles3D` process material shaders is called for trail sections where the corresponding frame history is still blank, which means that their `DELTA`, `EMISSION_TRANSFORM` and `EMITTER_VELOCITY` are zero until the history eventually fills up. This can cause positioning and calculations to break.

In the attached project I have a minimal particle shader that just lets the trail follow the moving parent node. When starting the project or reloading the scene in the editor, you can see the glitch where the trail starts at world origin.

```glsl
void process() {
	CUSTOM.y += DELTA / LIFETIME;
	if (CUSTOM.y > 1.0) {
		ACTIVE = false;
	}

	// Uncomment the if-statements to work around the glitch
	// if (DELTA > 0.0 || NUMBER > 0u || INDEX > 0u)
	TRANSFORM[3] = EMISSION_TRANSFORM[3];
}
```

This patch also works around the problem, but I'm sure it breaks something else.

```diff
--- a/servers/rendering/renderer_rd/shaders/particles.glsl
+++ b/servers/rendering/renderer_rd/shaders/particles.glsl
@@ -647,7 +647,7 @@ void main() {
 		}
 	}
 
-	if (particle_active) {
+	if (particle_active && (!params.trail_pass || FRAME.emitting)) {
 #CODE : PROCESS
 	}
 ```

### Steps to reproduce

Run the attached project or reload the scene in the editor to see how the trail starts from world origin. Simply restarting the particle node will not cause the problem.

### Minimal reproduction project (MRP)

[ParticleTrailEmitterTransform.zip](https://github.com/godotengine/godot/files/14387453/ParticleTrailEmitterTransform.zip)

**Comment by permelin** [comment]
OK, now I'm convinced it's a bug, and I know where it is.

In `particles.glsl` there is this line which _should_ delay the activation of the individual sections of the trail:
```c
PARTICLE.flags = PARTICLE_FLAG_TRAILED | ((frame_history.data[0].frame & PARTICLE_FRAME_MASK) << PARTICLE_FRAME_SHIFT); //mark it as trailed, save in which frame it will start
```
The first time this runs, `frame_history.data[0].frame` is zero, which means that when a section particle sees frame number zero in its corresponding history slot, it will activate. That is handled by this line:
```c
if (bool(PARTICLE.flags & PARTICLE_FLAG_TRAILED) && ((PARTICLE.flags >> PARTICLE_FRAME_SHIFT) == (FRAME.frame & PARTICLE_FRAME_MASK))) { //check this is trailed and see if it should start now
```
The problem is that from the start, the history has been memset to zero. So every `FRAME.frame` is zero, which immediately activates all the sections instead of waiting for their number to come up.

This may be why Juan wrote this comment just below that line:
> this appears like it should be correct, but it seems not to be.. wonder why.

**Comment by permelin** [comment]
To fix this, we need a way to distingish a "true" frame number zero from when the entire frame struct is just zeros. (Unless we start counting frames from 1 instead of 0.)

Of all the fields in `ParticlesFrameParams`, `emitting` seems to me to be the best candiate for that. If it's zero (false), I don't think we would ever want to activate the particle that frame anyway. 

I'll wait a few days to see if someone has a better idea, otherwise I'll create a PR.

**Comment by clayjohn** [comment]
> To fix this, we need a way to distingish a "true" frame number zero from when the entire frame struct is just zeros. (Unless we start counting frames from 1 instead of 0.)
> 
> Of all the fields in `ParticlesFrameParams`, `emitting` seems to me to be the best candiate for that. If it's zero (false), I don't think we would ever want to activate the particle that frame anyway.
> 
> I'll wait a few days to see if someone has a better idea, otherwise I'll create a PR.

That makes sense to me. 

Could we also just set the `frame` property to some token value (not zero). I.e. could we set it to 1 or some high value that indicates it hasn't been initialized yet?

**Comment by permelin** [comment]
> Could we also just set the `frame` property to some token value (not zero). I.e. could we set it to 1 or some high value that indicates it hasn't been initialized yet?

Yes, that's probably a better idea. I think 1 would be safe but UINT32_MAX should be even safer while also be less likely to cause some future confusion. Right? I have no experience of C++ nor GLSL and I don't know what the convention is in a case like this.
