### ISSUE TITLE
Script Editor errors are white

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88713]
### Tested versions

4.3 87d40ba
Does not happen in 4.3 dev3.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/2532c064-9ddf-4b4d-a6d1-53c98c94b43f)

### Steps to reproduce

1. Create script
2. Make error

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
Probably introduced in https://github.com/godotengine/godot/pull/88474
If you update the Text Editor > Theme settings it will turn red, so its just not being updated when the editor loads

**Comment by akien-mga** [comment]
CC @MajorMcDoom

**Comment by MajorMcDoom** [comment]
I will get on this shortly.
