### ISSUE TITLE
Toggling a plugin makes its name black

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#88714]
### Tested versions

Likely regression from #88308
CC @Mickeon 

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/127c7fed-5ab3-4fd8-9eb7-83ab8c35f9e5

### Steps to reproduce

1. Have a plugin
2. Go to Plugins tab in project settings
3. Disable and enable it

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
Looks like a really trivial fix. Changing font color instead of bold was not tested properly by yours truly as it was last minute
