### ISSUE TITLE
"Add Type Hints" editor setting resets itself randomly

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#88721]
### Tested versions

Observed in 4.2.1 and 4.3.

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Sometimes (and there seems to be no rhyme or reason to this that I have deduced) the "Add Type Hints" editor setting (`text_editor/completion/add_type_hints`) will reset itself to `false`, despite me putting it back to `true` every time.

### Steps to reproduce

I have no reliable repro, unfortunately, but this happens quite regularly. I have not source-controlled my editor settings or anything like that.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can't replicate by these details, so more details are needed to replicate this

**Comment by KoBeWi** [comment]
The default has changed to enabled, so if you had it enabled in 4.2, it will be removed in 4.3.

**Comment by Calinou** [comment]
Since default values are not saved to editor settings, I don't think there's anything we can do (other than renaming the setting to prevent this behavior on this particular setting).

**Comment by MajorMcDoom** [comment]
This is great to know, I can deal with this with a tool script or something, thank you! :)
