### ISSUE TITLE
FontVariation.tres causes the editor under gl_compatibility to freeze.

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#88728]
### Tested versions

v4.3.dev.mono.custom_build [f814ee0a2]

### System information

Godot v4.3.dev.mono (f814ee0a2) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 17 Feb 2024 20:06:55 +0000 - Wayland - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) () - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

My custom branch only contains this small C# change:#86791
Use the gl_compatibility renderer to create FontVariation resources, but the editor freezes when saving(File saving completed):
![图片](https://github.com/godotengine/godot/assets/52148221/faed5dc4-04b2-4e2b-b6cf-2dd92a398a0a)

Killer godot process, reopen the project, the editor is stuck:
![图片](https://github.com/godotengine/godot/assets/52148221/cb921190-63d1-4c92-9c62-c0ece59b2ce0)

There is no relevant error message in the terminal. Switching to the renderer using vulkan can open the project normally:
![图片](https://github.com/godotengine/godot/assets/52148221/c9a9a7bc-627e-47f2-bb01-353bfa481548)

4.2.1 does not have this problem:
![图片](https://github.com/godotengine/godot/assets/52148221/ae7971de-8e38-4800-9a0f-f754a2ac23fb)

In addition, after using 4.2.1 to open the project once, 4.3 can also be used normally:
![图片](https://github.com/godotengine/godot/assets/52148221/84ff8036-f33b-461e-9e2b-b50514086c5a)

### Steps to reproduce

The above description should be enough.

### Minimal reproduction project (MRP)

N/A

**Comment by scgm0** [comment]
@bruvzg 
The problem seems to occur when generating thumbnails, have you made any progress?

**Comment by clayjohn** [comment]
I have a feeling this is the same root issue as https://github.com/godotengine/godot/issues/88576

Can you test https://github.com/godotengine/godot/pull/88589 and see if it fixes the issue for you?

**Comment by scgm0** [comment]
> I have a feeling this is the same root issue as #88576
> 
> Can you test #88589 and see if it fixes the issue for you?

You are right, it does solve my problem.
