### ISSUE TITLE
Rewrite Godot in Rust

### ISSUE THREAD

**Issue by Serkan-devel** [godotengine/godot#8873]
For switching to Rust might make game creation and games in Godot much safer than on C/C++.

**Comment by MrMaidx** [comment]
I really had to look at the calendar if it's not 1st of April again. :D This is a good one.

**Comment by bojidar-bg** [comment]
Looks related to #6000, though it should have been `#9000` in this case :wink:

**Comment by ducdetronquito** [comment]
![RIIR](https://i.imgflip.com/1pk1bi.jpg)

**Comment by reduz** [comment]
I like the idea, let's do it for Godot 25.0

**Comment by Serkan-devel** [comment]
But I want <a href="https://www.redox-os.org/">Redox</a> support for it without adding an unsafe programming language.

**Comment by akien-mga** [comment]
/me pours some caustic water on the Godot source code.

As writing good C++ is iron hard to achieve, just give it some time and in a matter of years it should all turn to rust automagically.

**Comment by Raj2032** [comment]
Yeah we should I couldn't agree with you more.

**Comment by Airbus5717** [comment]
Give this a try https://amethyst.rs/

**Comment by Raj2032** [comment]
Thanks mate for letting me know.
