### ISSUE TITLE
Cannot save file using FileAccess

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#88757]
### Tested versions

Godot Engine v4.2.stable.mono.official.46dc27791
Godot Engine v4.2.1.stable.official.b09f793f5
### System information

Windows 11 Pro

### Issue description

Creating a new `FileAccess `with the flag `FileAccess.WRITE` always returns null during development.

### Steps to reproduce

```
func _ready():
	var path = "user://configs/data.cfg"
	var file = FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		print("cannot open file to save")
	
	print(ProjectSettings.globalize_path(path))
	print(FileAccess.get_open_error())
```

###### Output
```
cannot open file to save
C:/Users/ASUS/AppData/Roaming/Godot/app_userdata/can_not_save_file/configs/data.cfg
7 => which is ERR_FILE_NOT_FOUND
```

### Minimal reproduction project (MRP)

[can_not_save_file.zip](https://github.com/godotengine/godot/files/14392516/can_not_save_file.zip)

**Comment by AThousandShips** [comment]
What does `FileAccess.get_open_error()` return?

**Comment by nongvantinh** [comment]
Tested with 4.2.1 but still getting errors. The `FileAccess.WRITE` flag is supposed to create a new file for me.

**Comment by AThousandShips** [comment]
Does the parent directory, i.e. `user://configs` exist?

**Comment by nongvantinh** [comment]
![image](https://github.com/godotengine/godot/assets/53887662/56cec8fb-c73f-433d-b70e-292bf67f86d0)

Upon inspecting the directory, there is no `configs` folder in that path. But I expect it to create the folder for me. Am I using it the wrong way?

**Comment by AThousandShips** [comment]
It says "creates the file" it doesn't guarantee the path, try create the directory and see, most of the time there's no guarantee of it creating the full path when dealing with these things, see for example [`DirAccess.make_dir`](https://docs.godotengine.org/en/stable/classes/class_diraccess.html#class-diraccess-method-make-dir)

**Comment by nongvantinh** [comment]
Thank you, it works fine now. I believe it would be helpful to have clear documentation regarding this behavior in the `FileAccess.open` method.

Here is the code:
```

func _ready():
	var path = "user://configs/"
	var filename = "data.cfg"
	var dirAccess = DirAccess.open("user://")
	if dirAccess == null:
		print("DirAccess is null");
	else:
		dirAccess.make_dir(path)
		
	var file = FileAccess.open(path + filename, FileAccess.WRITE)
	if file == null:
		print("cannot open file to save")
	
	print(ProjectSettings.globalize_path(path))
	print(FileAccess.get_open_error())
```
