### ISSUE TITLE
Running a project with a defferent architecture than the android device

### ISSUE THREAD

**Issue by MarouaneMebarki** [godotengine/godot#88760]
### Tested versions

tested in :
4.2.1
4.3.dev2

### System information

Ubuntu 23.10

### Issue description

my Redmi 10A supported architecture are **armeabi-v7a** , unselecting this option from the export/architecture menu
![Screenshot from 2024-02-24 12-45-02](https://github.com/godotengine/godot/assets/129473260/8cf921ff-ca18-4a06-b20c-011311b74712)

and running a remote debug, make this window appear:
![Screenshot from 2024-02-24 12-46-30](https://github.com/godotengine/godot/assets/129473260/422cb857-cad1-4153-ac33-d7a04571265e)

### Steps to reproduce

add a proper warning:

`Please be sure your device architecture meets the Project architecture`

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/86284.
