### ISSUE TITLE
History Dock visibility acting weirdly

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#88779]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Even though I keep the History panel turned off in my preferences, it keep showing up every time I restart Godot. In the attached video, it can be seen that the History panek is visible, but when I open the Editor Features control window, it is obviously unticked.

So after every restart I have to open the Editor / Editor Features panel, turn History on and then turn it back off in order to hide it.

### Steps to reproduce

Open Godot.
Open Editor / Editor Features.
Hide the History Dock.
Close Editor / Editor Features.
Close Godot.
Restart Godot.
…History Dock will be visible again.

### Minimal reproduction project (MRP)

Godot 4.2.1

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88432
