### ISSUE TITLE
CAMERA_POSITION_WORLD inverted in Double Precision builds

### ISSUE THREAD

**Issue by NatGazer** [godotengine/godot#88776]
### Tested versions

Reproducible in: 4.2.1

### System information

Windows 10 - Vulkan (Forward+) - RTX 3060 laptop - AMD Ryzen 5 5600H - 24GB RAM

### Issue description

Any shader using CAMERA_POSITION_WORLD will work differently when a double precision build is used because the vector has x, y and z inverted.

Here's a grid shader that uses this built-in:

Godot 4.2.1 official:
![Godot](https://github.com/godotengine/godot/assets/67602607/e81eb6fc-7407-4117-9aba-8ed1f668a3d8)

Godot 4.2.1 Double Build:
![GodotDouble](https://github.com/godotengine/godot/assets/67602607/d9d466a7-dd8b-4ccf-b8b6-063bae6143cf)

### Steps to reproduce

Run the MRP

### Minimal reproduction project (MRP)

[CAMERA_POSITION_WORLD_bug.zip](https://github.com/godotengine/godot/files/14394145/BugShader.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85711

As this is derived from the `INV_VIEW_MATRIX` this bug covers this case
