### ISSUE TITLE
History Dock leaving an empty hole when it's turned off

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#88782]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

If the History Dock is the only one on the left side of the Godot IDE, turning it off leaves an empty panel that can't be closed.

### Steps to reproduce

https://archive.org/download/ShowFlowFleetingWorld/画面収録%202024-02-24%2020.28.50.mov

### Minimal reproduction project (MRP)

Godot 4.2.1

**Comment by emre0altan** [comment]
It didn't leave any empty space when I tried it with *v4.3.dev*. It may have been fixed in *4.3*.

**Comment by inhalt120g** [comment]
Looks like this is not happening in
v4.3.dev5.official [89f70e98d]
(or at least I can't reproduce it anymore).

Thank you to whoever fixed it!
