### ISSUE TITLE
After enabling NavMesh in Advanced Import Settings it cannot be disabled again.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#88789]
### Tested versions

4.3[2e7fc81]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

In the import dialog (glb or blend doesn't matter) if you set NavMesh to any options other than disabled and reimport then it's impossible to go back to disabled again (you can select it and reimport but the reimport doesn't do anything it stays at the last options you had).

### Steps to reproduce

1. Add a gltf or a blender file with a mesh.
2. Double click it in the FileSystem dock.
3. Select the MeshInstance3D.
4. Change NavMesh setting to anything other then disabled.
5. Reimport.
6. Observe changes in the editor to ensure everything worked.
7. Do 2-5 again but use Disabled instead for the NavMesh Setting.
8. Observer nothing has changed

### Minimal reproduction project (MRP)

You can use this one: [NavigationBakeIssue.zip](https://github.com/godotengine/godot/files/14394764/NavigationBakeIssue.zip) 
It really doesn't matter what model you have or scripts or anything, this is a bug in the import settings so anything as long as it has the above mentioned settings goes.

**Comment by AeioMuch** [comment]
Can't reproduce in 81f3d43

**Comment by viksl** [comment]
Yeah, can confirm it's gone in the today's master.

**Comment by mishkarch** [comment]
This bug is still in stable 4.3. Restarting the editor does not help, I had to delete the *.import file.
