### ISSUE TITLE
Trouble with the documentation and the tilemap editor

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88781]
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

w10 64

### Issue description
This not happen in 3.x
Pressing the M key (shortcut to the select tool) to be able to select a tile rectangle in the tilemap node does not work if you have the pencil selected.
That is, with the tool that is activated with the M key you can select a rectangle of cells.

For it to work you must select the "Selection" tool, that is, the little arrow located to the left of the pencil.

M shortuct not work with the "paint" tool

![Captura5](https://github.com/godotengine/godot/assets/19652075/c4f9d3ab-49a1-4615-a2bd-746f22fdef6d)

M shortcut works with the selection tool

![Captura4](https://github.com/godotengine/godot/assets/19652075/7dd8bafb-8601-4d13-be62-a33a35dffde2)

The documentation indicates that the M key selects the selection tool but the editor indicates that it is the S key.
https://docs.godotengine.org/en/stable/tutorials/editor/default_key_mapping.html#tile-map-editor

![Captura5](https://github.com/godotengine/godot/assets/19652075/418d262a-0233-452c-8cc1-7ed557014920)

### Steps to reproduce

Select the "paint" tool
Press the M key to activate the selection
The selection will not be activated.

### Minimal reproduction project (MRP)

...

**Comment by PaulUlanovskij** [comment]
Opened Pull Request [https://github.com/godotengine/godot-docs/pull/9022](url)
