### ISSUE TITLE
Crash when importing specific OGG file (converted from MP3 via audacity)

### ISSUE THREAD

**Issue by marchare555** [godotengine/godot#88793]
- *Related to https://github.com/godotengine/godot/issues/40320.*

### Tested versions

- 4.2
- 4.2.1 (stable)
- 4.3-dev3

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 with Max-Q Design (NVIDIA; 30.0.15.1169) - Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 Threads)

### Issue description

Godot crashes everytime I import an audio file. It happens during the "re-import" process with .ogg or .mp3 files. I don't see any error message when it happens.

### Steps to reproduce

1. Open Godot
2. Import audio file through file manager or drag'n'drop
3. Wait for Godot to "re-import"

### Minimal reproduction project (MRP)

Any project, even a fresh empty one triggers the crash on my side.

Additional note: sometimes Godot has time to leave "import" files in the folder where the file was imported. Sometimes it doesn't. I can upload an import file if that helps.

**Comment by AkhRani** [comment]
Not seeing this on 4.2.1 (stable) with Windows 10 19045.4046 with 6GB GeForce 1060, 32GB of RAM and AMD Ryzen 9 3900X (12 cores), at least not with the first random .mp3 I tried.

Project is using Forward Plus for the renderer, and default settings for the mp3 importer (and ogg, though I didn't check that)
Tried with a project updated from 4.0 and a new project.

Upload your files and I'll try with them.  Also, maybe try running godot from the command line and see if there are any error messages there?

**Comment by AkhRani** [comment]
Was able to reproduce the crash in 4.2.1 stable with the uploaded .ogg file.  No useful information on the console.  Debug build of the master branch does not crash.  Going to try a debug build of 4.2.1.

**Comment by marchare555** [comment]
I found several more files that work without crash. If it helps I can upload a handful of "crashing" and "non-crashing" files if that helps find a pattern that differs between the two groups.

**Comment by AkhRani** [comment]
Current 4.2.2 tip gives the following console error but does not crash

ERROR: Error during vorbis synthesis -135
   at: (modules\vorbis\audio_stream_ogg_vorbis.cpp:159)

**Comment by marchare555** [comment]
Ok, I tried importing all audio files (2200 of them) and it turns out that it's just that one file that makes Godot crash.

It's literally this file I found on Freesound.org, which was originally in MP3 and I converted to .ogg with Audacity:
https://freesound.org/people/Taira%20Komori/sounds/215015/

Curiously, the untouched MP3 files imports just fine to Godot, so it might be some change in Audacity during the converstion that Godot doesn't seem to like.

**Comment by MJacred** [comment]
@marchare555: So you only have the issue when using an .ogg file? Could you please make a build using PR https://github.com/godotengine/godot/pull/87246 or any later? 4.3-dev3 was before that PR got merged.

**Comment by akien-mga** [comment]
I can confirm the crash in 4.2.1-stable and 4.3-dev3 with the `clenchinghand.ogg` file from https://github.com/godotengine/godot/issues/88793#issuecomment-1964062487

And indeed I can confirm that it's fixed in the `master` branch by #87246, so it's the same bug as #87076.
I'll backport #87246 for 4.2.2 and 4.1.4 so this should be fixed in the next builds.

**Comment by marchare555** [comment]
> @marchare555: So you only have the issue when using an .ogg file? Could you please make a build using PR #87246 or any later? 4.3-dev3 was before that PR got merged.
> 
> (this is possibly a duplicate of #87076)

I tried with 4.3-dev4 and the offending OGG files now imports and plays properly. Thanks a bunch!
