### ISSUE TITLE
Huge lag in new project, 

### ISSUE THREAD

**Issue by thunderyuri** [godotengine/godot#88792]
### Tested versions

- v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 - v4.2.1.stable.official [b09f793f5]

### Issue description

after opening a new project (im starting at godot), everthing just lags at a unusable level. (this only happens when in a project). I maked some test in my notebook, and didnt notice this lag in other apps or games.

### Steps to reproduce

Create a new project, and open it

### Minimal reproduction project (MRP)

N/A happens in ever new project
```[tasklist]
### Tasks
```

**Comment by Zireael07** [comment]
What are your system specs? It's likely you have a GPU issue (e.g. thermal) or broken drivers

**Comment by Mickeon** [comment]
There's not enough information provided in the issue. We cannot really do anything with this, especially without hardware details.
 
If I have to make a light guess, Godot may be running on integrated graphics, which is still not enough for a bug report.

**Comment by thunderyuri** [comment]
@Zireael07 
I use a laptop, he have an Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz, and 8,00 GB RAM. and now im finally capable to see the spec about the laptop, i have to say it is a pretty bad laptop.

Idk if this is the real problem, or not, but can be. sry for dont bring the details :(

**Comment by Mickeon** [comment]
Could you give the specs of your GPU, if any? If you are unable to find them, it is likely using integrated graphics and this kind of lag _sounds_ about right.

> (this only happens when in a project)

I assume this means that the Project Manager is completely fine, which makes sense since it is not really performance-intensive in any way.

**Comment by thunderyuri** [comment]
weel, im using integrated graphics, sorry for wasted your time. so sorry.

**Comment by Calinou** [comment]
Closing, as this issue lacks actionable information for us to be able to do anything.
