### ISSUE TITLE
Unable to bake NavigationMesh for certain meshes but it works through editor menu Mesh - Create Navigation Mesh.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#88790]
### Tested versions

4.3[2e7fc81]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

For some reason when I add NavigationRegion3D I can't bake a navigation mesh for certain objects, no errors just no mesh appears but if I use the same MeshInstance3D and use the built-in menu Mesh - Create Navigation Mesh then it works, obviously this has a disadvantage that you can't change any nav mesh baking settings for it.

Similar thing happened to me on some other meshes too, this one is particularly maybe strange for nav mesh generation so I'm using it as an example (I also don't have any other anymore), it's a partition of sphere, just to be clear even if there wasn't the empty division in between the same issue occurs.

I understand the mesh is probably not standard but it works one way so I'd assume there should be a way to make it work both ways perhaps?

### Steps to reproduce

1. Open the project, there are 3 NavigationRegions, one with the blen scene added the other with MeshInstance3D copied from the openedi inherited blend scene and the third one is the mesh resource saved through the import settings and assigned to a fresh new MeshInstance3D.
2. You can click on any region and at the top of the viewport press Bake NavigationMesh button and observe nothing changes.
3. Now click on the last MeshInstance3D and at the top of the viewport click on Mesh -> Create NavigationMesh and observe a new NavigationRegion3D is created with the mesh as its child and most importantly the navigation mesh is now visible and exists.

### Minimal reproduction project (MRP)

[NavigationBakeIssue.zip](https://github.com/godotengine/godot/files/14394764/NavigationBakeIssue.zip)

**Comment by smix8** [comment]
The MRP is corrupted and missing the blend file to open.

From what I can see with the provided mesh resource alone that is a complete bogus mesh for baking navmesh as it has internal holes and flipped faces.

**Comment by viksl** [comment]
Hm, I downloaded the archive and it does have the blend file, when it comes to errors in the output when you open it I'm not sure why they started appearing but if you press the play button once they will be gone even on successive loads of the project.

I have three questions here if you don't mind:
1. I understand the mesh isn't ideal or anywhere near, as mentioned above I made this one on purpose since I currecnlty don't have any other. I had same issue with spheres and cubes for some reason.
2. Why does it generate the mesh polygon through Import Settings (setting to NavMesh only or NavMesh), does it fail since the mesh is bonkers and then it just loads the mesh data and uses that instead?
3. Same as 2. but this time through Mesh (menu) -> Create Navigation Mesh.

Since all these generate a NavigarionRegion3D I'd expect them all either fail or pass but a mix so where's the bug, is it in the Mesh menu and Import Settings for the mesh or in the NavigationRegion3D's baking instead?

As a side note, I'll take the 1. failure with regular shapes as per your suggestions that maybe there was some corruption, though I haven't found issues with the models before so maybe something during import can under some condition corrupt some data?

**Comment by smix8** [comment]
Except for the actual baking all the navmesh import or conversion options that exist around the Editor are just an array copy.
Not a single of those functions is capable of doing any verification that the mesh data makes any sense for navigation.

**Comment by viksl** [comment]
Thank you, it makes sense. I'm not sure why I had issues with couple models but it might have been just a corruption as you mentioned either in the blend file itself or when it was imported, it wasn't consistent with all my models from the same file at the time though.
Maybe this report could be closed then (or soon if no one else comes with the same issues)?

**Comment by smix8** [comment]
I think we can close this. Feel free to reply if you want to add something or think it should be kept open.
