### ISSUE TITLE
Debug Physics Display

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#888]
Hey, there. A way to be able to see what (and where) physics meshes are currently in-game would be a nice feature to add. 

Also, some more debug stats in general would be nice (number of draw calls, number of objects in existence as well as on-screen, number of scripts running, peak and average FPS, etc). And yeah, it's possible to make these additional stats oneself, but it'd still be nice to have them in the engine.

**Comment by akien-mga** [comment]
If you refer to visual debugging of collision shapes, I believe this feature has been implemented in the current master branch.

Regarding your other suggestions, feel free to open a new issue with some more details about what exactly would be useful.

**Comment by toger5** [comment]
if visual debugging of collision shapes is already implemented can anybody tell me where to find it ?

**Comment by akien-mga** [comment]
Probably in the editor settings.

**Comment by reduz** [comment]
in the remote debug menu in the same list of buttons as play, stop, etc.

**Comment by toger5** [comment]
Okay, should have found it by myself.... Thak you!!
