### ISSUE TITLE
The problem with SConstruct?

### ISSUE THREAD

**Issue by November20** [godotengine/godot#88804]
### Godot Version
3.0

### System information

linux

### Question
```python
# godot-3.0/platform/x11/detect.py 
# line number:152
    if not env['builtin_libwebp']:
        env.ParseConfig('pkg-config libwebp --cflags --libs')
```
What does builtin_ mean?
Is there a libwebp library installed in my system?
Env ['builtin_libwebp'] defaults to true because scons can already search this library?

### Steps to reproduce

```
wy@wy-A320M-S2H:~/godot/godot-3.0cs$ pkg-config libwebp --cflags --libs
Package libwebp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libwebp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libwebp' found
```

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
The message just means you don't have the libwebp development package installed, but that's not a problem since Godot includes it (built-in).

What is the actual issue you are having when compiling Godot? What command do you use to compile, and what is the error output?

**Comment by November20** [comment]
Your explanation is of great help to me.Thank you.
I want to know the third question:
Env ['builtin_libwebp'] defaults to true because scons can already search this library?How does scons tell whether it is a standard installed library or a library in godot-3.0/thirdparty?

**Comment by November20** [comment]
In my opinion, the meaning of these two lines of code is that if you can't find libwebp in the project folder, use the standard installed libwebp and discard the changes to libwebp? Is there any risk in doing so? Is my understanding correct?How did scons discover the built-in library? Automatic? Still need to be configured?

**Comment by akien-mga** [comment]
You did not answer my question so I still don't know what problem you're trying to solve :)

If you're just curious about what these lines do, this is not the right platform to discuss it, GH issues are for bug reports.

If you do run into a bug due to these lines, I'd like to know which so that I can fix it :)

**Comment by November20** [comment]
```python
# godot-3.0/SConstruct 
# line number:186
opts.Add(BoolVariable('builtin_libwebp', "Use the builtin libwebp library", True))
```
Sorry, I didn't see the variable in front.My idea is wrong.

**Comment by November20** [comment]
我以为可以自动发现
