### ISSUE TITLE
Visual Studio styled autocomplete box (improvement suggestion)

### ISSUE THREAD

**Issue by neomonkey** [godotengine/godot#88838]
### Tested versions

Godot 4.2.1 stable, same problem with all versions.

### System information

Windows 10

### Issue description

Godot engine text editor autocomplete box appears straigh below the text line that you are making, and it often gets annoyingly in the way when you are making minor adjustments or longer lines without the need of autocompletion. E.g you are making something new which is not yet created and the autocompletion box doesn't get removed because it wants to suggest something that exists. Now to remove this, I need to move my hand into mouse and click somewhere else or press ESC, because I can't use arrow keys. The arrow keys go into the autocompletion.

There are two problems which needs to be fixed. The easier fix is the placement. In Godot the placement is static and starts from the beginning of centence. With Visual Studio it is dynamic and the autocompletion box moves below and behind the target sentence which is autocompleted. Image as an example to show the difference. The dynamic system would improve the usability a lot.

The bigger fix is that the autocomple will complete a huge amount of functions. For example if you write misspell assert with ssert you get hundreds of autocompleted suggestions. Someone might like this kind of autocompletion, but I don't it gets in the way. So I suggest that there should be few options in the options menu for the Godot autocompletion. First option only suggests the exact keywords which start with what the user has written. For example if I would write "ssert" I would get none, but if I would write "asse" I would get only "assert." Second option could be a middleground of option to have suggestions from searches which has the whole written sentence, but it could be at any part of the word. For example with "ssert" you would get "assert" and "playerAssertion", but not "myStaticSertification." Currently with "ssert" I get suggestions like "VisualShaderNodeVectorRefract", and that is making the UI less intuitive in my opinion, because I need to hit esc or mouse to get rid of the box.

![godot_autocomplete_issue](https://github.com/godotengine/godot/assets/5145163/8285d545-41ca-4768-86c9-97ddacdf8a6a)

------------------------------------
So in this suggestion I suggest that.
1. Autocomplete box would be at the end of the completed keyword and it would move dynamically.
2. There should be 2-3 options for different autocompletion.
        a. Current autocompletion method.
        b. Autocompletion which only autocompletes exact written sentences and only from beginning of the keyword.
        c. Autocompletion which only autocompletes exact written sentences and in any spot of the keyword.

### Steps to reproduce

Just write something and you can see how the autocompletion works.

### Minimal reproduction project (MRP)

extends Node

func _ready():
	ssert

**Comment by ajreckof** [comment]
This looks more like a proposals then a bug. I think it should be made on https://github.com/godotengine/godot-proposals ( maybe one proposal for each point not sure on that). If the second point has enough backing I could work on it as I know autocomplete code well.

**Comment by neomonkey** [comment]
I didn't know this. Sorry :D.

Two proposal issues opened 9181 and 9182.

**Comment by neomonkey** [comment]
This ticket can be closed.
