### ISSUE TITLE
Windows Build Fails - Missing include file

### ISSUE THREAD

**Issue by schmidh** [godotengine/godot#8883]
Latest Godot version as of today (May 23rd 2017)

godot/editor/editor_initialize_ssl.cpp tries to include file _certs_compressed.h_ which is not available.

**Comment by akien-mga** [comment]
Does it work if you retry to build a couple times?

**Comment by schmidh** [comment]
You are replying faster than my machine compiles! ;-)

It works. The trick was to compile it the first time unparallized. Then the include file will be generated and subsequent compiles can run in parallel with the -j option.

Thanks a lot!

**Comment by vnen** [comment]
You can actually build in parallel without a previous build, you just have to retry a few times when it errors.

There's an open issue about this anyway: #5042
