### ISSUE TITLE
Autocompletion does not suggest enum names for core classes

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#88858]
### Tested versions

- Reproducible in: 4.3.dev [99addd6d9c04e38da27c9001376dce920a1b690a] and before

### System information

Windows 11

### Issue description

The completion misses enum names. For example, in Control class there are constant names presented, but not enum names where these constants placed (Anchor, CursorShape etc):

![изображение](https://github.com/godotengine/godot/assets/3036176/a127b4c4-6c6d-42d5-b0d1-58a6052d06a6)

It's wrong because such code is correct and must be a subject for autocompletion:

![изображение](https://github.com/godotengine/godot/assets/3036176/c7c99d2d-1b0c-43a5-b126-b2e05dc0bae8)

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

No need - too trivial to reproduce.

**Comment by HolonProduction** [comment]
How does this relate to [#84509](https://github.com/godotengine/godot/issues/84509)?

**Comment by Chaosus** [comment]
@HolonProduction It's different issue - #84509 was about completion in static type declaration - this is about completion after type assignment.

**Comment by dcaoc03** [comment]
Hi! I'm new here and I would like to try and fix this. Can I be assigned this issue?

**Comment by Zireael07** [comment]
Godot engine does not practice assigning issues, just make a PR
