### ISSUE TITLE
TextEdit `set_line_gutter_icon` does not show an icon in projects

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#88859]
### Tested versions

Latest master as of writing, 4.3-dev 99addd6d9c04e38da27c9001376dce920a1b690a

### System information

macOS 14.2.1, Apple M1 Pro

### Issue description

In TextEdit, `set_line_gutter_icon` does not show an icon when used in projects. However, the similar `set_line_gutter_text` function does show text, so this is evidence that my gutters are set up correctly.

However, the strange part is that `set_line_gutter_icon` is working when called from the editor for use with the script editor's gutter icons, but it does not work when called from user script in a project.

### Steps to reproduce

Download and run the minimal reproduction project, which contains this code:

```gdscript
func _ready() -> void:
	add_gutter(0)
	set_gutter_width(0, get_line_height())
	set_line_gutter_icon(1, 0, preload("res://icon.svg"))
	set_line_gutter_text(2, 0, "hi")
```

This script adds a gutter, sets an icon for line index 1 (line 2), and sets text for line index 2 (line 3).

Expected behavior: The icon is displayed in the gutter, on the second line, to the left of the letter `b`.

Observed behavior: No icon is displayed in the gutter.

<img width="57" alt="Screenshot 2024-02-26 at 4 05 56 AM" src="https://github.com/godotengine/godot/assets/1646875/63b9b68a-b14b-48fc-b9b6-7f1b4fa319b8">

### Minimal reproduction project (MRP)

[TextEditIconBroken.zip](https://github.com/godotengine/godot/files/14402943/TextEditIconBroken.zip)

**Comment by aaronfranke** [comment]
Also, a related bug, it seems that gutter custom draw callbacks are not being run at all:

```gdscript
func _ready() -> void:
	add_gutter(0)
	set_gutter_custom_draw(0, draw_gutter)
	set_gutter_width(0, get_line_height())


func draw_gutter(line: int, gutter: int, area: Rect2) -> void:
	print("draw_gutter")
```

Expected behavior: It prints `draw_gutter` sometimes.

Observed behavior: Nothing is ever printed.

**Comment by AeioMuch** [comment]
It works if you 

> Also, a related bug, it seems that gutter custom draw callbacks are not being run at all:
> 
> ```gdscript
> func _ready() -> void:
> 	add_gutter(0)
> 	set_gutter_custom_draw(0, draw_gutter)
> 	set_gutter_width(0, get_line_height())
> 
> 
> func draw_gutter(line: int, gutter: int, area: Rect2) -> void:
> 	print("draw_gutter")
> ```
> 
> Expected behavior: It prints `draw_gutter` sometimes.
> 
> Observed behavior: Nothing is ever printed.

It works if you add this line `set_gutter_type(0, TextEdit.GUTTER_TYPE_CUSTOM)`
Same for the icon you need to do `set_gutter_type(0, TextEdit.GUTTER_TYPE_ICON)`

I imagine that the custom is when you want to handle both strings and icons at the same time ?

**Comment by aaronfranke** [comment]
Thank you @AeioMuch that was it. I opened PR #88875 to document this.
