### ISSUE TITLE
Navigation Agent doesn't work when the target is a generic Node3D

### ISSUE THREAD

**Issue by rdclzn** [godotengine/godot#88867]
### Tested versions

Only tested in Godot v4.1.3 stable

### System information

Windows 10 Home Single Language version 22H2 - Godot v4.1.3 stable

### Issue description

The issue is that when trying to set the target (who is part of the navigation mesh, but also a Node3d) of an NavigationAgent3D, the Agent goes to the first position, then stops. However, doing the exact same configuration, but using a target that's a scene with a root as a CharacterBody3D, it works flawlessly.
There's a further description of the problem [here](<https://www.reddit.com/r/godot/comments/1b00ess/entity_with_navigationagent3d_doesnt_follow/>) and these are the two target scenes I mentioned, in the attached images.

![image](https://github.com/godotengine/godot/assets/33260162/7010e676-f15d-4320-8f5b-476a4ff62c7f)

![image](https://github.com/godotengine/godot/assets/33260162/9dd737b4-1722-4c48-86d8-1db5795e8d1a)

To make the CharacterBody3D-root scene I literally just simply copy and pasted the original, which means there's no differences in terms of script, or settings of the navagent.

### Steps to reproduce

Create a scene. Go through the effort of setting a player controller and an enemy with navigationagent3D, test it.

### Minimal reproduction project (MRP)

Use this as your base project, this is where I based my scripts on, I'm not making a new scene just for a bug report:
https://github.com/LegionGames/ZombieEnemies

**Comment by AThousandShips** [comment]
> I'm not making a new scene just for a bug report

Please do, a complete project like this is not minimal, it should be specific to help reviewing, not a large project with irrelevant parts

**Comment by smix8** [comment]
> However, doing the exact same configuration, but using a target that's a scene with a root as a CharacterBody3D, it works flawlessly.

If the used target node types makes a difference as describes this is a project specific node setup or scripting bug.

The navigation system and path queries all use global position vectors as targets, nothing there uses or depends on a node (type) as target.

**Comment by rdclzn** [comment]
I'm at a loss on how to proceed here, the project is itself quite large but it has a lot of unnecessary assets.
This is the agent's script for following the player:
`extends CharacterBody3D

var player = null
const SPEED = 5.0

@export var player_path : NodePath

@onready var nav_agent = $NavigationAgent3D

# Called when the node enters the scene tree for the first time.
func _ready():
	velocity = Vector3.ZERO
	player = get_node(player_path)
	# These values need to be adjusted for the actor's speed
	# and the navigation layout.
	nav_agent.path_desired_distance = 0.5
	nav_agent.target_desired_distance = 0.5
	
	nav_agent.set_path_max_distance(0) 
		
	# Make sure to not await during _ready.
	call_deferred("actor_setup")

func actor_setup():
	# Wait for the first physics frame so the NavigationServer can sync.
	await get_tree().physics_frame

	# Now that the navigation map is no longer empty, set the movement target.
	set_movement_target(player.global_position)

func set_movement_target(movement_target: Vector3):
	nav_agent.set_target_position(movement_target)

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _physics_process(delta):
	if nav_agent.is_navigation_finished():
		return
	
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	velocity = Vector3.ZERO
	
	nav_agent.set_target_position(player.global_transform.origin)
	var next_nav_point = nav_agent.get_next_path_position()
	velocity = (next_nav_point - global_transform.origin).normalized() * SPEED
	rotation.y = lerp_angle(rotation.y, atan2(-velocity.x, -velocity.z), delta * 10.0)
	
	move_and_slide()`

This is the player script (which shouldn't bear any form of influence on enemy navigation afaik):
`extends CharacterBody3D

signal player_fired

#consts
const MAXSPEED : float = 10.0        # default: 32.0
const WALKSPEED : float = 5.0       # default: 16.0
const STOPSPEED : float = 10.0       # default: 10.0
const GRAVITY : float = 10.0         # default: 80.0
const ACCELERATE : float = 10.0      # default: 10.0
const AIRACCELERATE : float = 0.25   # default: 0.7
const MOVEFRICTION : float = 2.0     # default: 6.0
const JUMPFORCE : float = 5.0       # default: 27.0
const AIRCONTROL : float = 0.9       # default: 0.9
const STEPSIZE : float = 1.8         # default: 1.8
const MAXHANG : float = 0.2          # default: 0.2
const PLAYER_HEIGHT : float = 3.6    # default: 3.6
const CROUCH_HEIGHT : float = 2.0    # default: 2.0
const LADDER_LAYER = 2

var direction
var deltaTime : float = 0.0
var movespeed : float = 32.0
var fmove : float = 0.0
var smove : float = 0.0
var ground_normal : Vector3 = Vector3.UP
var hangtime : float = 0.2
var impact_velocity : float = 0.0
var is_dead : bool = false
var jump_press : bool = false
var crouch_press : bool = false
var ground_plane : bool = false
var prev_y : float = 0.0
var ladder_normal : Vector3 = Vector3.UP
var _can_fire : bool = false
var _can_fire_counter = 0

enum {GROUNDED, FALLING}
var state = GROUNDED

#bullets
var bullet = load("res://prefabs/rifle_bullet.tscn")
var bulletFX = load("res://prefabs/particles_hit_metal.tscn")
var instances
#vars
@export var sensitivity = 0.10
@export var max_angle = 80
@export var min_angle = -70
var look_rot = Vector3.ZERO
@onready var head = $head
@onready var firesfx = $ShootingSFX
@onready var raycast = $head/RayCast3D
@onready var gun     = $"head/Fps Rig AKM/GunBarrel"

# Get the gravity from the project settings to be synced with RigidBody nodes.
var gravity = ProjectSettings.get_setting("physics/3d/default_gravity")

func _ready():
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
	PlayerAutoload.player = self
	
func _input(event):
	if event is InputEventMouseMotion:
		look_rot.y -= event.relative.x
		look_rot.x -= event.relative.y
		look_rot.x = clamp(look_rot.x, min_angle, max_angle)
	
	movespeed = WALKSPEED if Input.is_action_pressed("shift") else MAXSPEED
	
	if Input.is_action_just_pressed("fire"):
		fire_shot()
	
	# Handle Jump.
	if Input.is_action_just_pressed("jump") and !jump_press:
		jump_press = true
	elif Input.is_action_just_released("jump"):
		jump_press = false

func _physics_process(delta):
	if Input.is_key_pressed(KEY_ESCAPE):
		get_tree().quit()
	deltaTime = delta
	update_fire()
	ground_normal = get_floor_normal()
	# Get the input direction and handle the movement/deceleration.
	# As good practice, you should replace UI actions with custom gameplay actions.
	var input_dir = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	fmove = Input.get_action_strength("move_forward") - Input.get_action_strength("move_backward")
	smove = Input.get_action_strength("move_right") - Input.get_action_strength("move_left")
	direction = (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()
	direction = Vector2(direction.x, direction.z)
		
	#Rotation
	rotation_degrees.y = look_rot.y
	head.rotation_degrees.x = look_rot.x
	
	$AnimationTree.set("parameters/conditions/stop", input_dir == Vector2.ZERO and is_on_floor())
	$AnimationTree.set("parameters/conditions/walk", input_dir == Vector2.UP and is_on_floor())
	$AnimationTree.set("parameters/conditions/right", input_dir == Vector2.RIGHT and is_on_floor())
	$AnimationTree.set("parameters/conditions/left", input_dir == Vector2.LEFT and is_on_floor())
	$AnimationTree.set("parameters/conditions/retreat", input_dir == Vector2.DOWN and is_on_floor())
	$AnimationTree.set("parameters/conditions/right_walk", input_dir.angle() < Vector2.UP.angle() and is_on_floor())
	$AnimationTree.set("parameters/conditions/left_walk", (input_dir.angle() - Vector2.UP.angle() > 0) and input_dir.angle() < Vector2.LEFT.angle() and is_on_floor())
	$AnimationTree.set("parameters/conditions/left_retreat", (input_dir.angle() - Vector2.LEFT.angle() > 0) and input_dir.angle() < Vector2.DOWN.angle() and is_on_floor())
	$AnimationTree.set("parameters/conditions/right_retreat", (input_dir.angle() - Vector2.DOWN.angle() > 0) and is_on_floor())
	$AnimationTree.set("parameters/conditions/jump", (velocity.y != 0) or !is_on_floor())
	$AnimationTree.set("parameters/conditions/landed", is_on_floor())
	
	if(velocity.y != 0 or (!is_on_floor() and !is_on_ceiling())):
		state = FALLING
	elif is_on_ceiling() or is_on_floor():
		state = GROUNDED
	
	
	jump_button()
	check_state()
	
	move_and_slide()


func jump_button():
	if is_dead: 
		return
	if state == GROUNDED and jump_press:
		$JumpSFX.play_sfx()
		$JumpGruntSFX.play()
		state = FALLING
		jump_press = false
		velocity.y += JUMPFORCE

func check_state():
	match(state):
		GROUNDED:
			ground_move()
		FALLING:
			air_move()
			
func ground_move():
	if direction:
		process_footsteps(true)
		var current_horizontal_v = Vector2(velocity.x, velocity.z)
		current_horizontal_v = Vector2(velocity.x, velocity.z).lerp(movespeed * direction, ACCELERATE * deltaTime) 
		velocity.x = current_horizontal_v.x
		velocity.z = current_horizontal_v.y
	else:
		process_footsteps(false)
		var current_horizontal_v = Vector2(velocity.x, velocity.z)
		current_horizontal_v = Vector2(velocity.x, velocity.z).lerp(Vector2.ZERO, MOVEFRICTION * deltaTime) 
		velocity.x = current_horizontal_v.x
		velocity.z = current_horizontal_v.y
		
	impact_velocity = 0

func air_move():
	var wishdir = (global_transform.basis.x * smove + -global_transform.basis.z * fmove).normalized()
	air_accelerate(wishdir, STOPSPEED if velocity.dot(wishdir) < 0 else AIRACCELERATE)
	
	velocity.y -= GRAVITY * deltaTime
	if global_transform.origin[1] >= prev_y: 
		prev_y = global_transform.origin[1]
		
	impact_velocity = abs(int(round(velocity[1])))


func air_accelerate(wishdir : Vector3, accel : float):
	var addspeed     : float
	var accelspeed   : float
	var currentspeed : float
	
	var wishspeed = slope_speed(ground_normal[1])
	
	currentspeed = velocity.dot(wishdir)
	addspeed = wishspeed - currentspeed
	if addspeed <= 0.0: 
		return
	
	accelspeed = accel * deltaTime * wishspeed
	if accelspeed > addspeed: accelspeed = addspeed
	
	velocity[0] += accelspeed * wishdir[0]
	velocity[1] += accelspeed * wishdir[1]
	velocity[2] += accelspeed * wishdir[2]

"""
===============
air_control
===============
"""
func air_control(wishdir : Vector3):
	var dot        : float
	var speed      : float
	var original_y : float
	
	if fmove == 0.0: 
		return
	
	original_y = velocity[1]
	velocity[1] = 0.0
	speed = velocity.length()
	velocity = velocity.normalized()
	
	# Change direction while slowing down
	dot = velocity.dot(wishdir)
	if dot > 0.0 :
		var k = 32.0 * AIRCONTROL * dot * dot * deltaTime
		velocity[0] = velocity[0] * speed + wishdir[0] * k
		velocity[1] = velocity[1] * speed + wishdir[1] * k
		velocity[2] = velocity[2] * speed + wishdir[2] * k
		velocity = velocity.normalized()
	
	velocity[0] *= speed
	velocity[1] = original_y
	velocity[2] *= speed

"""
===============
slope_speed

Change velocity while moving up/down sloped ground
===============
"""
func slope_speed(y_normal : float):
	if y_normal <= 0.97:
		var multiplier = y_normal if velocity[1] > 0.0 else 2.0 - y_normal
		return clamp(movespeed * multiplier, 5.0, movespeed * 1.2)
	return movespeed


func fire_shot():
	if _can_fire:
		#firesfx.play()
		$ShootingSFX2.play_sfx()
		_can_fire = false
		_can_fire_counter = 0
		emit_signal("player_fired")
		instances = bullet.instantiate()
		instances.position = gun.global_position
		instances.transform.basis = gun.global_transform.basis
		get_parent().get_parent().add_child(instances)
		var center_of_camera = get_viewport().get_size()/2
		var ray_origin = head.project_ray_origin(center_of_camera)
		var ray_end    = ray_origin + head.project_ray_normal(center_of_camera)*50
		
		var new_intersection = PhysicsRayQueryParameters3D.create(ray_origin, ray_end)
		var Intersection = get_world_3d().direct_space_state.intersect_ray(new_intersection)
		
		if !(Intersection.is_empty()):
			var shotFX = bulletFX.instantiate()
			get_parent().get_parent().add_child(shotFX)
			shotFX.global_position = Intersection.position
			shotFX.look_at(ray_origin + Intersection.normal, Vector3.UP)
			shotFX.find_child("GPUParticles3D").emitting = true
			shotFX.find_child("GPUParticles3D2").emitting = true
			shotFX.find_child("AudioStreamPlayer3D").play()
			

func update_fire():
	if _can_fire == false:
		if _can_fire_counter > 0.167:
			_can_fire = true
			_can_fire_counter += deltaTime
		else:
			_can_fire_counter += deltaTime

func _on_timer_timeout():
	pass

func process_footsteps(play : bool) -> void:
	if($Timer.is_stopped() and play):
		$Timer.start()
		$PlayerFootstep.pitch_scale = randf_range(0.7,0.95)
		$PlayerFootstep.play_sfx()
	elif !play:
		$Timer.stop()
		$PlayerFootstep.stop()`
		

With either approach the project runs without errors pertaining to navigation

**Comment by AThousandShips** [comment]
Please upload a project instead, and if you are adding code please put it between tripple backticks as per the instructions, like so:
\```gdscript
...
\```

**Comment by rdclzn** [comment]
I'll try to setup a minimum project, this may take a while, if I don't manage to reproduce the error that way I'll close the issue.

**Comment by smix8** [comment]
If you set the path max distance to 0 the agent will query a new navigation path every single update. Since you also rapid-fire the updates every single frame you might easily get your agent stuck this way alone. I now remember this youtube tutorial, it tripped a few other users into problems in the past because it is has basics things wrong, like using the correct process mode for physics nodes.

The documentation has working script templates for NavigationAgents used with common node types that you can find here https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#navigationagent-script-templates.

**Comment by rdclzn** [comment]
@smix8 this minimum distance was set in my desperate attempts to solve the issue, it wasn't explicitly called for in the tutorial. however, despite it not working, it got through the resulting code

**Comment by smix8** [comment]
Well the main problem in that project is that you have 2 "Player" nodes. The one that is tracked by your enemy is the parent node that is never moving. The child node that is moving is not tracked by the enemy.
