### ISSUE TITLE
TileMap.set_cell not work on WorkerThreadPool add_group_task

### ISSUE THREAD

**Issue by CoachRun** [godotengine/godot#88869]
### Tested versions

v4.2.1.stable.official.b09f793f5

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5800U with Radeon Graphics (16 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/20763592/a225c67f-cc94-4fc8-b007-555e84b6fc83)

```gdscript
# Generator.gd
extends Object

class_name Generator

const PER_CHUNK_SIZE = Vector2i(16, 16)
const MAP_CHUNK_COUNT = Vector2i(8, 8)

var tile_map: TileMap
var arr = []

func _init(_tile_map: TileMap):
	self.tile_map = _tile_map
	self.arr.clear()
	for x in range(0, MAP_CHUNK_COUNT.x):
		for y in range(0, MAP_CHUNK_COUNT.y):
			arr.push_back(Vector2i(x * PER_CHUNK_SIZE.x, y * PER_CHUNK_SIZE.y))
	var group_id = WorkerThreadPool.add_group_task(self.thread_generate, arr.size())
	WorkerThreadPool.wait_for_group_task_completion(group_id)

func thread_generate(idx):
	var position = arr[idx]
	for x in range(0, PER_CHUNK_SIZE.x):
		for y in range(0, PER_CHUNK_SIZE.y):
			self.tile_map.set_cell(0, Vector2i(position.x + x, position.y + y), 0, Vector2i(0, 0))
```

```gdscript
# World.gd
extends Control

@onready var tile_map = $TileMap

# Called when the node enters the scene tree for the first time.
func _ready():
	Generator.new(tile_map)	
	pass


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

```

### Steps to reproduce

```gdscript
# World.gd
extends Control

@onready var tile_map = $TileMap

# Called when the node enters the scene tree for the first time.
func _ready():
	Generator.new(tile_map)	
	pass


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

```

### Minimal reproduction project (MRP)

[maptile_demo_2.zip](https://github.com/godotengine/godot/files/14406425/maptile_demo_2.zip)

**Comment by AThousandShips** [comment]
Tile maps are [not thread safe](https://docs.godotengine.org/en/stable/tutorials/performance/thread_safe_apis.html#scene-tree), but please explain how it doesn't work, are you getting an error? Are is breaking?

**Comment by CoachRun** [comment]
not thread safe
Windows MessageBox
`the Instruction at 0x00007ff referenced memory at 0x1f6515, The memory could not be written`
