### ISSUE TITLE
Skeleton3D missing revert button(s) in inspector

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#88877]
### Tested versions

Reproducible in 4.2.1 stable and 4.3 dev.

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

The Skeleton3D class does not allow reverting of its bone tree in the inspector. Nor does it allow reverting of individual bone properties. This means there is no way for a skeleton in a scene instance to be reverted back to its source scene state.

It seems like the node stores every property of every bone individually instead of in arrays:
```
bones/0/name = "pelvis"
bones/0/parent = -1
bones/0/rest = Transform3D( ... )
bones/0/enabled = true
bones/0/position = Vector3( ... )
bones/0/rotation = Quaternion( ... )
bones/0/scale = Vector3(1, 1, 1)
bones/1/name = "leg.R"
bones/1/parent = 0
bones/1/rest = Transform3D( ... )
...
etc.
```
This should make it fairly simple to expose revert buttons like so, consistent with other nodes:
![Screenshot 2024-02-26 115306](https://github.com/godotengine/godot/assets/13228932/7b5e1963-9878-4945-a6df-237ab3830cfb)

### Steps to reproduce

This can be observed on any Skeleton3D node in the inspector.

### Minimal reproduction project (MRP)

N/A

**Comment by emre0altan** [comment]
I did some dive in but couldn't find any explicit way of resetting the values. I suspect that it's being done in a generic way but bone data is stored in a plain struct. So I think either `Bone` struct should be transformed to an `Object` to use the generic way or maybe there could be a another way to reset only for `Bone` which I couldn't find.

**Comment by ydeltastar** [comment]
I often end up with a completely broken `Skeleton3D` while switching between editing and importing animations. It happens when I change the bone hierarchy and reimport while using editable children. The rest poses get messed up, but it looks fine in a new instance.

I found a solution to reset it using an `EditorScript`. It gets the selected Skeleton3D node in the editor and applies the source file's bone rest poses to it.

```gdscript
@tool
extends EditorScript


func _run() -> void:
	var selection = get_editor_interface().get_selection().get_selected_nodes()
	
	for skeleton in selection:
		if skeleton is Skeleton3D:
			var packed_scene = load(skeleton.owner.scene_file_path)
			var original = packed_scene.instantiate()
			
			var original_skeleton:Skeleton3D = original.get_node(skeleton.owner.get_path_to(skeleton))

			for idx in skeleton.get_bone_count():
				var bone_rest = original_skeleton.get_bone_rest(idx)
				skeleton.set_bone_rest(idx, bone_rest)
			
			skeleton.reset_bone_poses()
			
			original.free()
			
			print("Fixed %s rest pose." % skeleton)
```

**Comment by MajorMcDoom** [comment]
> I often end up with a completely broken `Skeleton3D` while switching between editing and importing animations. It happens when I change the bone hierarchy and reimport while using editable children. The rest poses get messed up, but it looks fine in a new instance.
> 
> I found a solution to reset it using an `EditorScript`. It gets the selected Skeleton3D node in the editor and applies the source file's bone rest poses to it.
> 
> ```gdscript
> @tool
> extends EditorScript
> 
> 
> func _run() -> void:
> 	var selection = EditorInterface.get_selection().get_selected_nodes()
> 	
> 	for skeleton in selection:
> 		if skeleton is Skeleton3D:
> 			var packed_scene = load(skeleton.owner.scene_file_path)
> 			var source_scene = packed_scene.instantiate()
> 			
> 			var source_skeleton:Skeleton3D = source_scene.get_node(skeleton.owner.get_path_to(skeleton))
> 
> 			for idx in skeleton.get_bone_count():
> 				var bone_rest = source_skeleton.get_bone_rest(idx)
> 				skeleton.set_bone_rest(idx, bone_rest)
> 			
> 			skeleton.reset_bone_poses()
> 			
> 			source_scene.free()
> 			
> 			print("Fixed %s rest pose." % skeleton)
> ```

This has been my workaround as well. It works, but it's really hacky in that it shouldn't be up to the user to maintain the connection between an instance and the source resource it relies on.
