### ISSUE TITLE
Certain keyboard shortcuts don't seem to be working

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#8887]
**Operating system or device - Godot version:**
Ubuntu 16.04 - 2e3145de65257ed39a5d01c5592ea0fb90cd00ba

**Issue description:**
Certain keyboard shortcuts don't appear to be working (not sure if these are regressions, or if this was never the intent). Examples:
- Hitting `Delete` while having a node selected (either in the scene menu, or in the scene itself) doesn't do anything
- Hitting Ctrl+S doesn't save the scene.
- Etc?

**Steps to reproduce:**
Create a new scene and attempt any of the shortcuts above (and probably some other ones?).

**Comment by reduz** [comment]
this was fixed already, closing
