### ISSUE TITLE
Tangent values ignored from mesh arrays

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#88888]
### Tested versions

4.2.1.stable

### System information

Windows 10

### Issue description

Kind of a follow up from https://github.com/godotengine/godot/issues/88839

```gdscript
var arrays = UNTITLED_MESH.surface_get_arrays(0)

# Can even delete this entire block
arrays[Mesh.ARRAY_TANGENT] = PackedFloat32Array()
for i in arrays[Mesh.ARRAY_VERTEX].size():
    arrays[Mesh.ARRAY_TANGENT].append_array([0, 0, 0, 1]) # <-- You can feed any value here

var mesh = ArrayMesh.new()
mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)

mesh_instance_3d.mesh = mesh
```

Tangents manually added to the array meshes are fully ignored, internally it still needs the size to be `vertices * 4` but the value themselves are ignored.

### Steps to reproduce

see above

### Minimal reproduction project (MRP)

[tangents.zip](https://github.com/godotengine/godot/files/14412746/tangents.zip)

**Comment by clayjohn** [comment]
What do you mean that tangents are ignored? How are you checking that?

**Comment by wagnerfs** [comment]
@clayjohn changing the values of the tanges to anything, even setting it a list of nulls won't change the final render at all like it only checks if the tangets size is 4 times the vertex and then proceed to use built in tangent generation instead of making use of whatever is input to the arrays.
I tested it multiple ways, manually generating tangents, feeding random data and feeding nulls and the result is all the same.

**Comment by clayjohn** [comment]
I have run the MRP locally. The mesh doesn't use tangents because its not using normal mapping or any other feature that relies on tangents. So it is expected that the visual output is unchanged.

You can validate that the tangents are present and correct by adding the following to the end of your script:
```
arrays = mesh.surface_get_arrays(0)
print(arrays[Mesh.ARRAY_TANGENT])
```
