### ISSUE TITLE
Origin lines are no longer visible in the 3D editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#88880]
### Tested versions

- Reproducible in: 4.3.dev 8f0c20ee8
- Not reproducible in: 4.3.dev3 official builds (but can be reproduced in self-compiled builds)

### System information

Godot v4.3.dev (8f0c20ee8) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

With self-compiled optimized builds, nothing is visible. Only grid lines can be seen, with nothing in place of the origin lines.

With self-compiled debug builds, points are visible instead when you look from (mostly) straight up:

![image](https://github.com/godotengine/godot/assets/180032/8f090f57-2cff-474b-8fd5-dbc05180c48b)

It looks like point rendering is used instead of triangle rendering. (Origin lines don't use line primitives anymore since https://github.com/godotengine/godot/pull/83895 was merged.)

With both build types, I can see origin lines being rendered correctly for a split second when the editor opens. This occurs even with fresh editor settings:

https://github.com/godotengine/godot/assets/180032/18590c12-c37f-40f6-b50f-172f3289e7e1

*Right-click and choose **Speed > 0.5×**, or step over the video frame-by-frame.*

### Steps to reproduce

- Open the 3D editor on any project and ensure **View Origin** is enabled in the 3D editor's **View** menu at the top.

### Minimal reproduction project (MRP)

N/A

**Comment by ryevdokimov** [comment]
Can't reproduce on latest master: 

Godot v4.3.dev (bb6b06c81) - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

**Comment by AeioMuch** [comment]
Looks like it was fixed by fd788d7d / df431542

**Comment by ryevdokimov** [comment]
Huh what the heck haha, that's my PR and I wasn't trying to fix it.

**Comment by Calinou** [comment]
I can confirm the issue is resolved as of https://github.com/godotengine/godot/commit/bb6b06c81343073f10cbbd2af515cf0dac1e6549.
