### ISSUE TITLE
Mouse wheel scrolling doesn't work

### ISSUE THREAD

**Issue by voithos** [godotengine/godot#8888]
**Operating system or device - Godot version:**
Ubuntu 16.04 - 2e3145de65257ed39a5d01c5592ea0fb90cd00ba

**Issue description:**
Scrolling via the mouse wheel doesn't seem to work in the editor.

**Steps to reproduce:**
Open project settings and attempt to scroll a panel (e.g. "Sections") via mouse wheel.

**Comment by sdhy** [comment]
I also have this problem with Godot 3.1 Beta 11 Classical build.

macOS High Sierra Version 10.13.6

Left-clicking before scrolling doesn't help.
Neither does pressing the mouse wheel while scrolling.

Page up and down works, though.

**Comment by cbscribe** [comment]
This is a very old issue that has nothing to do with Mac OS.

The problem you are having was reported in #26677 and was fixed in #26707 earlier today.
