### ISSUE TITLE
User is forced to open a project immediately after importing it in Project Manager

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#88891]
### Tested versions

Reproducible in 4.2.1 stable and 4.3 dev.

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Whenever I import a project in the Project Manager window, it gives me the options to `Import & Edit` or `Cancel`.
This denies me the option to import another project, rename the one I imported, or anything else.
If I have 5 projects I want to import, I have to wait for each one to open, close it, restart the Project Manager, and repeat 5x.

The expected behaviour is for the options to be `Import` or `Cancel`, with neither forcibly quitting the Project Manager. There is no reason to batch the two operations together. After the user finishes importing, it's one key or click to start editing the newly imported project.

### Steps to reproduce

Try to import a project in the Project Manager, and observe the dialog that pops up.

### Minimal reproduction project (MRP)

N/A

**Comment by AeioMuch** [comment]
You can drag and drop the projects folders. Tho it would make sense to have an `Import` button as well maybe.

**Comment by MajorMcDoom** [comment]
> > If I have 5 projects I want to import, I have to wait for each one to open, close it, restart the Project Manager, and repeat 5x.
> 
> You can drag and drop the projects folders. Tho it would make sense to have an `Import` button as well maybe.

I had no idea you could do that, very nice. :)

That said, this bug still applies. The user intent is to import when they initiate this operation. An additional button for `Import` would be nice, but personally I don't see any reason why it needs the `Import & Edit` button at all. The `Edit` button is right there, and you can also just press `Enter`, or double-click on the project. It's a strange thing to choose to micro-optimize, I think. In fact, if you really want to optimize, why even have the second dialog at all? After the user has selected the folder from the first dialog, the project should just appear in the list, and be selected. Why bring up another dialog that just has the exact same folder path? If that dialog was meant as the primary point of interaction, then the browse dialog shouldn't be auto-opened. The whole UX flow doesn't make sense.

All that aside, this bug report is just about the lack of an option to not auto-open the newly imported project. Everything else is just UX feedback that could be incorporated into the fix, but not strictly necessary.

**Comment by akien-mga** [comment]
Fixed by #95600.
