### ISSUE TITLE
canvas_item_add_circle does not work

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8889]
**Operating system or device - Godot version:**
osx 3.0 current master

**Issue description:**

the call to `vs-> canvas_item_add_circle();`
does not draw anything in godot 3.0. I think draw polygon also might be broken.

If someone can fix that would be great. I don't have time soon and would love to create a pr with the new style box. I'm finished. But I want to test first. And maybe fix things.
**Steps to reproduce:**
I'm working on FlatStyleBox and implement rounded corners. I'm using circles for that.
I started in godot 2.1 with gd script to create the logic. So I know that the draw circle function works in 2.1
Than I implemented the rounded style boxes in C++. 
To confirm I also tried 3.0 in GDScript. And I can confirm, that the draw circle function also does not work there either.

**Comment by Zylann** [comment]
Could be related to https://github.com/godotengine/godot/issues/7840

**Comment by toger5** [comment]
#8425 this is fixing it. I used the code from this commit. but maybe I should remove it and wait until it is merged.

**Comment by toger5** [comment]
fixed with recent reimplementation of _draw_polygon
