### ISSUE TITLE
"End" Property for Attenuation Curves

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#889]
Hey. I'm finding that properties that require Attenuation curves tend to be a bit lacking. For example, if you want a spot light that doesn't fade out toward the edges, it's pretty much impossible to achieve. Similarly, having fog that starts a certain amount in and completely goes opaque after a distance isn't possible (as far as I can tell). Having a simple "End" property that the attenuation curve interpolates over would assist in this considerably.

EDIT: Actually, it seems like fog in general is broken. It seems like it works on a per-vertex basis rather than a per-pixel basis. The attenuation just changes how dark everything beyond "Begin" gets, not how smoothly it's blended in.

**Comment by akien-mga** [comment]
What's the status on this in the current master branch?

**Comment by akien-mga** [comment]
Closing as such old feature requests lack visibility and might no longer be fully applicable to current Godot versions. If you think this feature is still required, feel free to comment here or open a new issue with the context of current Godot releases (3.0.x, master branch).
