### ISSUE TITLE
Game window centered by default

### ISSUE THREAD

**Issue by coppolaemilio** [godotengine/godot#8890]
Every time I encounter a YouTube tutorial it strikes me as how many times the game window is **manually centered** after running. In the most recent GDquest's tutorials backed by a KickStarter you can see this same behavior: [Example](https://youtu.be/xUSEeXDtwIw?t=34s)

I think that the **default setting** for the game window should be **centered**. It is something that I see MANY people is struggling with and it is hard to find that settings option if you don't know a lot about the program's interface.

I'll try to do a pull request myself but I'm not sure if I'll be able to make it properly.

**Comment by coppolaemilio** [comment]
It might not be the correct place to ask for help but I think I found the file where to edit this. Inside [/editor/editor_settings.cpp line 614 ](https://github.com/godotengine/godot/blob/master/editor/editor_settings.cpp#L614)


Is there any documentation on the source?

**Comment by Zylann** [comment]
Many issues and PRs (some merged!) about this:

https://github.com/godotengine/godot/pull/2110
https://github.com/godotengine/godot/pull/2293
https://github.com/godotengine/godot/issues/2545
https://github.com/godotengine/godot/issues/3578
https://github.com/godotengine/godot/issues/4430
https://github.com/godotengine/godot/issues/5626
https://github.com/godotengine/godot/issues/7477

**Comment by akien-mga** [comment]
All these issues are partly obsolete or confusing due to the mixing of various reports regarding behaviour on 2.0, 2.1, 3.0... It would be worth having someone check what *actually* happens on 2.1 on one hand, and on master on the other hand (separate issues, as it obviously does not behave the same), with the various exiting config options.

**Comment by Gibbz** [comment]
yes agreed. Im a bit fed up with moving the game window every time i launch because it likes to hide behind my task bar instead of center of the screen. (on git-master)

**Comment by CowThing** [comment]
Currently using 2.1.3 official on Windows 10 64bit and my game is centered when I run it.

**Comment by akien-mga** [comment]
See #9418.
