### ISSUE TITLE
[PSA for PR authors] Update your pre-commit hooks to use the newly merged `pre-commit` framework

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#88901]
We just replaced our hand-written shell scripts for pre-commit hooks with a set of hooks defined using the [`pre-commit`](https://pre-commit.com/) Python framework:
- #88866

Previous hooks should still work if you copied the scripts manually from `misc/hooks/`, but if you used to symlink them, they will be broken as of #88866 so you should remove them from `.git/hooks/`.

To use the new system, remove old hooks from `.git/hooks/`, and apply the new hooks with:
```
pip install pre-commit
pre-commit install
```

That's all, it should then automatically download dependencies (currently `clang-format` and `black`) the first time you try to commit, or when running `pre-commit run` manually.

If you want to apply the hooks to all your local changes before committing, you can use `pre-commit run`. You can also apply the hooks to all files in the repository regardless of their changed status by adding the `-a` option (`pre-commit run -a`).

The main workflow difference with the previous set of hooks is that if some changes are needed to pass the checks, they will be made automatically in place (at least for clang-format and black currently). Let's see if that workflow is fine, or if we need to figure out ways to bring back some interactivity.

**Comment by luevano** [comment]
We should also update the godot docs, as they point to the old way: https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#pre-commit-hook and https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#id3; when opening a PR it also points to one of these URLs

**Comment by roookeee** [comment]
I am getting the following errors about encoding on windows when running these:

```
  File "C:\Users\rookee\scoop\apps\python\current\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5068: character maps to <undefined>
```

It seems to read files in cp1252 instead of utf8 which gives me this garbled mess when running `pre-commit run -a`:
![img](https://github.com/godotengine/godot/assets/1199562/2671ed49-c90d-4a98-8d71-e2c7451e065b)

**Comment by AThousandShips** [comment]
Might be either something wrong with your specific file, if you added one you might have accidentally added an encoding to it, check your editor, otherwise this is likely a configuration error in your terminal

**Comment by roookeee** [comment]
I did not touch these files at all. I am running from powershell, I think it's reading the files in the standard platform encoding (which is cp1252 on windows if I recall):

```
Traceback (most recent call last):
  File "D:\dev\godot\misc\scripts\copyright_headers.py", line 92, in <module>
    line = fileread.readline()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rookee\scoop\apps\python\current\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```
 `readline` is not passed any encoding, so it makes sense its trying to use the platform encoding (I am not proficient in python though).

**Comment by AThousandShips** [comment]
Assuming you're working on #89826, can you check that the new file you added is encoded in utf8? Just to double check that isn't throwing it off somehow

I don't know how to alter the encoding in python though, there is an `encoding="utf-8"` directive, this might be missing from our files, I'll take a look

**Comment by roookeee** [comment]
I see you came to the same conclusion as me, that fixed the encoding issues but I am getting these changes added by `copyright_headers` now:
![img](https://github.com/godotengine/godot/assets/1199562/24a4e287-81af-487b-864f-ff5cf7682615)
This doesn't look like an encoding issue and I manually checked said file: its UTF-8 without BOM.

Will dig deeper later, the `encoding = "utf-8"` directive should definitely be added in `copyright_header.py`

**Comment by AThousandShips** [comment]
Could be that you changing that file broke some encoding in it so it has that error now, unsure

**Comment by AThousandShips** [comment]
Now ran into this myself, unsure why it didn't happen before, will look at a fix while I'm working on other code

**Comment by aitorciki** [comment]
Adding here for potential future reference (maybe worth adding a note in the documentation?):

When using msys2 on Windows, directly installing `pre-commit` inside msys2 (either as pre-packaged or using pip) won't work (see https://github.com/pre-commit/pre-commit/issues/3234).

The workaround I've found is installing `pre-commit` under Windows and invoking that binary inside msys2. In a nutshell:
* on Windows: `pip install pre-commit` (having installed Python on Windows first, of course)
* on msys2 add `alias pre-commit='/c/Users/foo/AppData/Local/Programs/Python/Python312/Scripts/pre-commit.exe'` (update to its correct path for each setup) to `~/.bash_profile` or similar
