### ISSUE TITLE
Hex color input field prevents typing when the popup "Enter a hex code ("#ff0000") or named color ("red)"." is showing

### ISSUE THREAD

**Issue by neth392** [godotengine/godot#88929]
### Tested versions

- Reproduceable in Godot v4.3.dev3.official `36e943b6b`
(standalone .exe, not steam)

### System information

Windows 11

### Issue description

When the `Enter a hex code ("#ff0000") or named color ("red)".` popup appears as in the image below, no inputs (typing, backspace, etc) are registered into the Hex text field until you move the cursor to get rid of the popup.

![image](https://github.com/godotengine/godot/assets/3991614/12d40b37-cb9a-4551-a7ce-0ccbc30b6e90)

### Steps to reproduce

Open up the color selection window, click the Hex text field, and start typing/deleting until you trigger the popup. Further inputs then do not work while the popup is present.

### Minimal reproduction project (MRP)

N/A (seems to happen in any project)

**Comment by Sauermann** [comment]
Can you please check if you would agree, that #79500 is describing the same problem?

**Comment by neth392** [comment]
@Sauermann Yes it is; apologies for the duplicate, I searched but didn't notice that one. Thank you
