### ISSUE TITLE
Godot Engine crashes on font change from the editor (using tool)

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#8892]
**Operating system or device - Godot version:**
Windows 10 Home 64bit
Godot Engine 2.1.3 (Steam, stable)

**Issue description:**
If you try to change the font size from within the editor, Godot Engine crashes. 
**set_font_size(value)** (on line 29) in _menu_item.gd_ causes the crash.

It also crashes if you try to use **set("font_size", value)** instead of set_font_value.

**Steps to reproduce:**
Open **menu_item.tscn** or **main_menu_scene.tscn** and change the menu item font size from within the editor (using export). 

**Link to minimal example project:**
[Bugged When Changing Font Size From Editor.zip](https://github.com/godotengine/godot/files/1025414/Bugged.When.Changing.Font.Size.From.Editor.zip)

**Comment by Listwon** [comment]
```
func set_font_size(value):
	# Update value
	font_size = value
	
	# Set button text
	set_font_size(value)
```

It causes infinite loop. It's just a bug in your script, not the bug inside the engine. Calling set("font_size", value) does the same thing, because it also triggers set_font_size(value).

I have no clue what is the point of calling set_font_size(value) at the end of set_font_size(value).

**Comment by eon-s** [comment]
Maybe is missing a dot `.set_font_size(value)` for a parent class function call.

**Comment by ivanskodje** [comment]
set("font_size", value)  still crashes it though. 
Do the setter from the same script code trigger the setget? To my knowledge, the setget should not trigger if you change the values from within the same script.

**Comment by Listwon** [comment]
@ivanskodje wrong assumption ;) It should trigger. Show me your updated script.

**Comment by ivanskodje** [comment]
@Listwon According to the documentation:

> Whenever the value of variable is modified by an external source (i.e. not from local usage in the class), the setter function (setterfunc above) will be called. [(From here)](https://godot.readthedocs.io/en/stable/learning/scripting/gdscript/gdscript_basics.html?highlight=setget)

Which is why I dont think changing them from within code should not trigger setget methods inside the same source.

**Comment by Listwon** [comment]
Local usage as font_size = value, not set("font_size", value), which calls setter explicitly.

**Comment by eon-s** [comment]
What it means is, from outside:
```gdscript
font_object.font_size = something #calls setter
```
From script of font_object (local)
```gdscript
font_size = something #does not call the setter
self.font_size = something #calls setter too
.set_font_size(something)  #calls parent setter if exists
```

**Comment by akien-mga** [comment]
I don't know what you're trying to achieve with this, but it's indeed an infinite loop and the reason for your crash:
```
# Set font size
func set_font_size(value):
	# Update value
	font_size = value
	
	# Set button text
	set_font_size(value)
```
So I don't see it as a bug in the engine itself :)
