### ISSUE TITLE
2D Skeletons not visible in Compatibility Mode

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#88937]
### Tested versions

**in Compatibility Mode**

v4.3.dev.custom_build [4a30fe5e7]

Reproducible on Windows when building at commit 4a30fe5e7c38955f289b9d0e1a945ed206484f27 and any commit after that up to and including Master
Not reproducible when building at commit 35cfbdd840c2025307b83af9ad3475e9cc1750dc

### System information

Godot v4.3.dev (4a30fe5e7) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

2D textures do not appear to show up at all after https://github.com/godotengine/godot/pull/86564 was merged.

### Steps to reproduce

Download Godot's Skeleton2D Demo from https://github.com/godotengine/godot-demo-projects/tree/master/2d/skeleton

Open it and run it **in Compatibility Mode** and the character is not visible on the screen.

![image](https://github.com/godotengine/godot/assets/6188278/3ca1eb12-a5d7-4660-9abe-12adda31c178)

### Minimal reproduction project (MRP)

Use the Godot demo project https://github.com/godotengine/godot-demo-projects/tree/master/2d/skeleton

**Comment by akien-mga** [comment]
CC @godotengine/rendering @Giwayume

**Comment by clayjohn** [comment]
Thanks for the report! Identifying the problematic PR made it a very quick fix
