### ISSUE TITLE
Keyboard in editor unusable in latest code

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8894]
Cant edit code, can click and drag with the mouse, but the keyboard does nothing.

I'm running Linux.

**Comment by rubenjavier** [comment]
Godot 3.0 master commit 2e3145de65257ed39a5d01c5592ea0fb90cd00ba
Tested on Linux 64bits and Windows10 64bits, keyboard in editor is not working on either

**Comment by eon-s** [comment]
I think is not keyboard in editor (because you can use it to move nodes on 2D editor) but Controls that ignore input, all except LineEdit ignore keyboard input and middle mouse/wheel, happens on editor and running projects with Controls.

**Comment by akien-mga** [comment]
Fixed in 3744d9f.
