### ISSUE TITLE
Window mouse_entered signal only emits after the mouse enters and exits once the window

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#88942]
### Tested versions

- Reproducible in: v4.3.dev3.official [36e943b6b], v4.2.1.stable.arch_linux

### System information

Godot v4.2.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Sat Feb 10 09:40:02 UTC 2024 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU () - AMD Ryzen 9 5900HX with Radeon Graphics (16 Threads)

### Issue description

Window `mouse_entered` signal only emits after the mouse has entered and exited the window viewport at least once.

https://github.com/godotengine/godot/assets/483531/6880f12a-213c-4aa4-b1b3-74279cddd589

It also happens with non-embedded windows:

https://github.com/godotengine/godot/assets/483531/9c198a41-8b6e-4360-bd1a-499514838fd4

### Steps to reproduce

- Connect to the Window `mouse_entered` signal.
- Launch the scene and move the mouse into the window
- Notice that the signal has not been emitted
- Leave the window and go back inside
- The signal emits

### Minimal reproduction project (MRP)

[bug_window_mouse_entered.zip](https://github.com/godotengine/godot/files/14429037/bug_window_mouse_entered.zip)

**Comment by Sauermann** [comment]
Bisected to #80334
