### ISSUE TITLE
Vehicle Body Weels are not colliding

### ISSUE THREAD

**Issue by betalars** [godotengine/godot#88955]
### Tested versions

4.2.1 stable

### System information

nixos unstable

### Issue description

Vehicle Body wheels do not collide with the ground, rendering Vehiclebody3D unusable.

### Steps to reproduce

1. Create a vehiclebody
2. Assign a collision shape to the body
3. Add wheels to it
4. add visual instances for better readability (optional)
_See minimum reproduction project._

### Minimal reproduction project (MRP)

[minimal_vehicle_bug.zip](https://github.com/godotengine/godot/files/14434050/minimal_vehicle_bug.zip)
_please note: I use the CSG shapes only to better visualize the error. They are not intended to act as physics object, and adding collision objects to vehicle wheels does not help with the observed clipping issue_

**Comment by AThousandShips** [comment]
Does it work if you [enable collision](https://docs.godotengine.org/en/stable/classes/class_csgshape3d.html#class-csgshape3d-property-use-collision) on the CSG shapes? You haven't in your MRP

**Comment by betalars** [comment]
@AThousandShips 
[Yes I tired to use collision shapes in tires and it just makes them wiggle more while they clip trough the ground.](https://github.com/godotengine/godot/files/14446319/jiggly_tires.zip)
Hence step 4 is optional and only refers to adding visual instances ...

And yes I also tried to just add colliders, and while that makes the tires not wiggle while they clip trough the floor, the tires still clip trough the floor.

**Comment by betalars** [comment]
_And today I learned: when tire collision shapes clip the vehicle body, you get Vehicle Body Space Program_ :laughing:

**Comment by AThousandShips** [comment]
No need to react that way, it was in no way obvious what you refered to by that step, please be constructive...

**Comment by betalars** [comment]
> No need to react that way
Sorry, I was trying to be less ambiguous, I did not mean to be rude.

When I use a box collider instead, it still does not work as expected.

But from what I can tell, this seems to be a duplicate. I just did not think to look for the keyword sink when I tried to see if this has been reported before.

**Comment by betalars** [comment]
Okay, these are actually the same issues and the suggested fixes work for me: However: it is really confusing, that child nodes of the spring to not get moved when the spring compresses. That would have made me realise the true nature of the issue a lot faster.
