### ISSUE TITLE
3D grid snapping activating without holding ctrl after saving

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#88968]
### Tested versions

Godot 4.3 Dev 3 official build

### System information

Godot v4.3.dev3 - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) R7 Graphics (Advanced Micro Devices, Inc.; 27.20.1034.6) - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

After I save or do anything that involves holding CTRL i.e saving scene with **CTRL + S** , it activates 3D grid snapping until pressed again.

https://github.com/godotengine/godot/assets/94475453/71c63912-0cf6-4a5b-b94c-fdb887a1cd0e

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/59687.
