### ISSUE TITLE
Language Server, reports error to VSCode extension when "class_name" is used.

### ISSUE THREAD

**Issue by esklarski** [godotengine/godot#88976]
### Tested versions

Godot: 4.2.1 official
VSCode Extension: Godot Tools: v2.0.0

### System information

Fedora 39

### Issue description

Re: https://github.com/godotengine/godot-vscode-plugin/issues/590

When using VSCode to view GDScript files, using the Godot Tools extension, every instance where I use a "class_name" identifier is reported as "hides a global script class."
![Screenshot from 2024-02-28 09-44-55](https://github.com/godotengine/godot/assets/55821817/1a0d8145-327a-41aa-9f56-c1410c47433a)
![Screenshot from 2024-02-28 10-24-43](https://github.com/godotengine/godot/assets/55821817/1d5a6e6f-2868-4519-8a2d-6959c7678c18)

This happens regardless of the node type extended from. And happens in all of the projects I had to test with (a few, not lots).

In the Godot editor there is no warning and the program works exactly as intended. This seems to be a phantom error as there is no actual conflict in class naming.

### Steps to reproduce

- Extract and open attached MRP
- Install Godot Tools extension in VSCode
- open MRP project folder in VSCode
- view file `error_producing_script.gd`

### Minimal reproduction project (MRP)

[LanguageServer_ErrorTest_MRP.zip](https://github.com/godotengine/godot/files/14438557/LanguageServer_ErrorTest_MRP.zip)

**Comment by dalexeev** [comment]
I couldn't reproduce the bug with Godot 4.2.1 and godot-tools 2.0.0. Could you please describe the steps to reproduce in more detail?

![](https://github.com/godotengine/godot/assets/47700418/be22726f-4a2d-4386-b362-5a992b595b1b)

**Comment by esklarski** [comment]
I don't know if I can. I have 10 projects I've loaded and without fail every file with `class_name` reports this error... It doesn't matter whether I open Godot or VSCode first.

Any suggestions on what more info I can provide?

**Comment by esklarski** [comment]
Okay, I had a break through!

It turns out this was a quirk of my system setup. I have my storage drive mounted to `/mnt/DATA` that I also have symlinked to my home folder as `~/DATA`.

If I open the folder in VSCode as `~/DATA/blah/blah` I get these errors, but if I load the folder as `/mnt/DATA/blah/blah` these errors do not appear!

So a word of warning, ensure your project's folder location matches the VSCode workspace one, ie not symlinked.
