### ISSUE TITLE
Range.ValueChanged signal returns double for C# when documentation says float

### ISSUE THREAD

**Issue by adammikulis** [godotengine/godot#88983]
### Tested versions

Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5161) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

The documentation for HSlider and VSlider indicates that ValueChanged returns a float. This is the case for GDScript, but in C# it returns a double. For those expecting a float, this creates an error that isn't immediately obvious.

Signal in the engine:
<img width="128" alt="image" src="https://github.com/godotengine/godot/assets/27887607/ac88e23e-c4b8-466a-bf94-d1ad014e6188">

Code in Range:
<img width="489" alt="image" src="https://github.com/godotengine/godot/assets/27887607/9d0d6ba5-7e5c-4af9-b0af-106178cb5bb3">

C# code with for Range.ValueChanged with float as the return type (results in error):
<img width="455" alt="image" src="https://github.com/godotengine/godot/assets/27887607/86a417be-646b-4735-8e5c-5246c52aab35">

C# code for Range.ValueChanged with double as the return type (no error):
<img width="402" alt="image" src="https://github.com/godotengine/godot/assets/27887607/99e1069f-c0dd-4d8c-a9b3-8c303cbdf7c1">

A possible solution is to change the signal in the mono build to state that it returns a double, or change the code to return float instead of double to align with the GDScript behavior.

### Steps to reproduce

Attach the ValueChanged signal from an HSlider or VSlider to your C# script. Use float as the return type and observe an error (CS0123 No overload for 'CSharpOnValueChanged' matches delegate 'Range.ValueChangedEventHandler')

```
public partial class HSliderCSharp : HSlider
{
	public override void _Ready()
	{
		ValueChanged += CSharpOnValueChanged;
	}

	private void CSharpOnValueChanged(float value)
	{
		GD.Print($"Value type of {value.GetType()}");
	}

	public override void _Process(double delta)
	{
	}
}
```

Change it to double to resolve the error.
```
public partial class HSliderCSharp : HSlider
{
	public override void _Ready()
	{
		ValueChanged += CSharpOnValueChanged;
	}

	private void CSharpOnValueChanged(double value)
	{
		GD.Print($"Value type of {value.GetType()}");
	}

	public override void _Process(double delta)
	{
	}
}
```

### Minimal reproduction project (MRP)

[RangeSliderError.zip](https://github.com/godotengine/godot/files/14439558/RangeSliderError.zip)

**Comment by raulsntos** [comment]
> This is the case for GDScript

In GDScript `float` means 64-bit, so it's the equivalent of C#'s `double`.

The signals in the editor's Node dock and the class reference in the [documentation](https://docs.godotengine.org/en/stable/) use the GDScript syntax, so you'll see `float` but in C# it probably means `double`.

Notice also that the signal in the editor shows up as `value_changed`, this is the name with which the signal is registered in the engine and also the name used by GDScript, but in C# the signal is renamed to `ValueChanged` to match .NET naming conventions.

For more information see the [_C# API differences to GDScript_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html) documentation page.

> A possible solution is to change the signal in the mono build to state that it returns a double

Users can still use a Mono/.NET build for GDScript-only projects. And the names used all throughout the editor come from Core (which usually matches GDScript), changing them to follow the .NET conventions would not be straightforward and we don't want to couple the editor code to the .NET module.
