### ISSUE TITLE
Node3D::reparent accesses global transform, even if it's not needed

### ISSUE THREAD

**Issue by elementbound** [godotengine/godot#89002]
### Tested versions

- Reproducible in 4.2 stable ( 46dc27791 )

### System information

Godot v4.2.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.161.07) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I have a use case where I spawn two nodes, then take the children of node B and move them under node A. Neither nodes are in the scene tree at this point, I only add them after the setup is done:

```gdscript
	var root_node = stereotype_scene.instantiate() as Unit3D
	root_node.name = name
	
	# Add model
	var model_node = model.instantiate()
	Nodes.take_children_of(root_node, model_node)
	model_node.queue_free()
```

Here's the definition for Nodes.take_children:
```gdscript
static func take_children_of(usurper: Node, target: Node, keep_global_transform: bool = false):
	for child in target.get_children(true):
		child.reparent(usurper, keep_global_transform)
```

Even though `keep_global_transform` is false, I get the following error on each call:
```
E 0:00:07:0517   nodes.gd:84 @ take_children_of(): Condition "!is_inside_tree()" is true. Returning: Transform3D()
  <C++ Source>   scene/3d/node_3d.cpp:343 @ get_global_transform()
  <Stack Trace>  nodes.gd:84 @ take_children_of()
                 unit-resource.gd:98 @ spawn()
                 creep-gen-layer.gd:23 @ _apply()
                 map-gen-layer.gd:23 @ apply()
                 map-generator.gd:69 @ generate()
                 map-gen-layer.gd:505866128 @ apply()
                 trees-gen-layer.gd:505867152 @ _apply()
                 map-gen-layer.gd:505868176 @ rest()
```

This happens because global_transform is accessed, even if it's not needed: https://github.com/godotengine/godot/blob/46dc277917a93cbf601bbcf0d27d00f6feeec0d5/scene/3d/node_3d.cpp#L719

### Steps to reproduce

1. Create two nodes
2. Reparent one node to to the other *before* adding them to the scene tree

### Minimal reproduction project (MRP)

[reparent-mrp.zip](https://github.com/godotengine/godot/files/14447249/reparent-mrp.zip)

**Comment by elementbound** [comment]
I'm happy to open a PR, I think moving the get_global_transform() statement around should fix this:

```gdscript
void Node3D::reparent(Node *p_parent, bool p_keep_global_transform) {
	ERR_THREAD_GUARD;
	# Transform3D temp = get_global_transform(); # Move from here
	Node::reparent(p_parent);
	if (p_keep_global_transform) {
		Transform3D temp = get_global_transform(); # To here
		set_global_transform(temp);
	}
}
```

**Comment by akien-mga** [comment]
Thanks for the report! And congrats for your first merged Godot contribution :tada:

**Comment by elementbound** [comment]
That was fast, thanks @akien-mga!
