### ISSUE TITLE
Linux export presets made in 4.2 do not appear in 4.3 dev, errors with `!preset.is_valid()` (due to renaming platform from "Linux/X11" to "Linux")

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#89012]
### Tested versions

 - Reproducible in v4.3.dev4.official [df78c0636] and v4.3.dev3.official [36e943b6b]
 - Not Reproducible in v4.2.stable.official [46dc27791]

### System information

Godot v4.3.dev3 - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Project -> Export...

4.2
![image](https://github.com/godotengine/godot/assets/6188278/261db0bf-3711-48e3-bb26-431e296bdac9)

4.3 Dev
![image](https://github.com/godotengine/godot/assets/6188278/a3c63739-5efb-4aaa-89a1-d8f67add4e1a)

### Steps to reproduce

 - Start a project in 4.2
 - Add an Export template for Linux
 - Close the project and open it in 4.3
 - The Linux template will not be visible

Web and Windows templates seem to remain.

### Minimal reproduction project (MRP)

This seemed like one of the smallest demo projects so I picked it and added a Linux export template to it.
Open it in 4.2 and you will see it. Open it in 4.3 and you will not.

[pong.zip](https://github.com/godotengine/godot/files/14450361/pong.zip)

**Comment by chrisl8** [comment]
I think the problem may be that the name changed from "Linux/X11" to just "Linux" between 4.2 and 4.3

![image](https://github.com/godotengine/godot/assets/6188278/e03dc203-bf43-4e75-a77c-21cd3a93b61e)

**Comment by akien-mga** [comment]
Yeah this was an intentional change when merging Wayland support, as the platform is no longer X11 specific.

We should check if we can add some compatibility code to still handle old presets gracefully (and e.g. automatically update `platform="Linux/X11"` to `platform="Linux"`), or if we just need to document this as a compat breakage which will require people to re-add a preset manually when migrating to 4.3.

**Comment by chrisl8** [comment]
I bumped into this because I have some scripts that automatically build and deploy games. They all failed because of no Linux export template.

In the GUI it is pretty obvious when the export template is missing, although if you had a lot of special settings in it, it would be annoying to have to rebuild it by hand.

When building from the command line, it is less obvious.

Documenting it as a breaking change seems fine to me, although it will be annoying if you don't remember what settings you had in your old Linux/X11 export template. Those export templates have a lot of possible settings.
People can re-open the game in 4.2 to hand copy stuff over I guess.

**Comment by and-rad** [comment]
Copying over shouldn't be necessary, right? Just tell people in the release notes to open the `export_presets.cfg` file with a text editor and replace all instances of "Linux/X11" with "Linux".

**Comment by akien-mga** [comment]
As per #89023, this also shows an error when opening a project with an old export template:
```
editor\export\editor_export.cpp:225 - Condition "!preset.is_valid()" is true. Continuing.
```
