### ISSUE TITLE
Lock button sometimes does not update

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89016]
### Tested versions

4.3 7d2ca2d

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Apparently Lock button is disabled/enabled in `_draw_viewport()` method, which means that it won't update when selecting nodes does not redraw editor:

https://github.com/godotengine/godot/assets/2223172/7f4aceae-01c0-4bef-bcbb-7851251c6a0c

See how the padlock in the top-right is always disabled until I move cursor over the viewport.

### Steps to reproduce

1. Add Sprite2D
2. Unselect everything
3. Select the Sprite2D
4. Look at Lock button
5. It should be enabled

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
When working on https://github.com/godotengine/godot/pull/88997 I thought It was my bug that caused this behaviour lol.
