### ISSUE TITLE
Custom AABBs on MultiMesh causing mesh distortion (imported Mesh, Mobile Renderer)

### ISSUE THREAD

**Issue by Bimbam360** [godotengine/godot#89028]
### Tested versions

v4.3.dev4.official [df78c0636]

### System information

Godot v4.3.dev4 - Windows 10.0.22000 - Vulkan (Mobile)

### Issue description

I just tried applying https://github.com/godotengine/godot/pull/79833 in 4.3dev4 to my mobile project and get the following behaviour with a basic imported mesh:

**Base and when set to (-1000, -1000, -1000, 2000, 2000, 2000) manually in inspector**
![309115736-d0e40aa6-1843-4f1c-a327-83ea9d35e3b7](https://github.com/godotengine/godot/assets/11803603/ea166f80-d16a-4ed7-856a-4e6866e8c54a)

**When set in GDScript prior to (or after) adding to the scene with** `MM.custom_aabb = AABB(Vector3(-1000, -1000, -1000), Vector3(2000, 2000, 2000))`

![309115710-7751f543-a96b-40b3-ae62-df0c0e47db1d](https://github.com/godotengine/godot/assets/11803603/d64c67bc-df28-4e30-92bc-c5bcda6c6409)

### Steps to reproduce

Load and run the MRP
Toggle comment  'MM.custom_aabb = AABB(Vector3(-1000, -1000, -1000), Vector3(2000, 2000, 2000))' and run again.

### Minimal reproduction project (MRP)

[MRP_Cubes.zip](https://github.com/godotengine/godot/files/14455578/MRP_Cubes.zip)

**Comment by maidopi-usagi** [comment]
Tested the MRP, and I think it may be related to the strategy of mesh LOD picking, as disabling LOD generation seems work right.
