### ISSUE TITLE
Top of screen cut off and mouse Y position off (Windows 10, Intel drivers regression)

### ISSUE THREAD

**Issue by willt** [godotengine/godot#8902]
Windows 10 PRO
Godot 2.1.3 & Latest 3.x
Intel 620 graphics card

When opening a project the top of the screen is cut off. You can't see the top bar where Scene, Import, Tools, etc are.
Mouse y position is off by like half a button width. This happens in the project list and when you open a project. You have to move the mouse below the buttons to click on them. 
I also tried running in self contained mode by create .\_sc\_ 

![godotcutoff](https://cloud.githubusercontent.com/assets/340016/26430918/dabf843a-40a5-11e7-84b1-5374c4697613.png)

**Comment by willt** [comment]
Update
It appears rolling back to a previous video driver made the problem go away
Good: Intel driver version 21.20.16.4565 12/10/2016
Bad: Intel driver version 21.20.16.4639 3/22/2017

**Comment by willt** [comment]
Any thoughts on where I could start looking to track down this bug?
Looking at release notes for the driver it doesn't say anything was really changed except for a fix when plugging into a dock I believe. I did notice this newer drive has the Vulkan API. Not sure if that is relevant or not.

**Comment by bojidar-bg** [comment]
Well, to me it seems like the whole picture somehow gets scaled over both the window and its titlebar, instead of being just constrained to the window.

So, it might be windows-related somehow, though I'm not sure how exactly.

Proof:
![image](https://cloud.githubusercontent.com/assets/5276727/26485744/dab223ba-4200-11e7-9c88-c07f755de538.png)
(done with GIMP using the image in the first comment)

**Comment by Unholypanda** [comment]
I have the same issue with the latest version of the Intel drivers on my XPS 13 9360. Is there any way to fix this on the application end. Using the old drivers is buggy and causes issues on my laptop.

**Comment by akien-mga** [comment]
Unless we can get Intel to fix their drivers, we'll have to find a workaround so that Godot 3.0 isn't broken for half the Windows 10 users.

**Comment by fkossyvas** [comment]
On my XPS 13 9360 updated yesterday with latest (21.10.16.4664) Intel drivers i have the same issue.

**Comment by Unholypanda** [comment]
I installed the latest version of the Intel drivers and it seems fine now. I had to manually install the drivers via the INF file because of Dell's restrictions, but it works.

**Comment by reduz** [comment]
@fkossyvas According to @Unholypanda Intel fixed the drivers, any idea if this works for you?

**Comment by fkossyvas** [comment]
I don't know what @Unholypanda means by _latest_. The latest i found by Dell was the [21.10.16.4664](https://www.dell.com/support/home/en/it/itbsdt1/Drivers/DriversDetails?driverId=M56HN) version (for my Windows 7, the default OS for this notebook is Windows 10). At the Intel site i've only found for the HD 520 graphics card [these ](https://downloadcenter.intel.com/product/88355/Intel-HD-Graphics-520) updates which means that what i have tied to install was the latest one but i doesn't work ok with Godot that is why i had to downgrade it to the previous one.

**Comment by willt** [comment]
I can confirm as well. I just installed the latest (15.4602.4729 driver version  is 22.20.16.4729) Generic Video Drivers from intels website manually and it seems to have resolved the issue. This is on my Yoga 2 from Lenovo with an intel 620.

@fkossyvas If you are installing the latest version from Intels website, perhaps its not fixed for the 520 ?

im closing this as its fixed for me and in my opinion isn't a Godot Issue.

**Comment by fkossyvas** [comment]
@willt : from what i see you are right : Intel has't fixed it for the 520. I've installed all the latest upgrades for my notebook (including Bios) but i had to downgrade the graphics update (again) to make Godot work.
I agree that this is not a Godot bug (but an Intel one) and should have been closed but the existence of this (closed) issue is helpful for others with the same problem.

**Comment by Unholypanda** [comment]
For what it's worth Dell released a driver update on August 14th that fixed it for me. Check you drivers on the website and see if they have an updated version for you card. If there isn't an Intel update though I doubt that dell will have drivers yet.

**Comment by xsellier** [comment]
Why this issue is flagged as closed?

**Comment by Zireael07** [comment]
What is your card? Have you checked with the Dell website that your driver is indeed the newest (Windows loves to misrepresent 'newest')

**Comment by xsellier** [comment]
@Zireael07 Dell laptop with intel iGPU. Windows 8.1, with latest updates (including latest drivers. Still having this issue.
