### ISSUE TITLE
Error Condition "p_value.get_type() != Variant::BOOL" is true. Returning: false on opening editor with project in 4.3

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#89026]
### Tested versions

 - Reproducible in v4.3.dev.custom_build [bd8380db5] and all subsequent commits including master
 https://github.com/godotengine/godot/commit/bd8380db5534af18fb4fab76daac77ef420becb4
- Not Reproducible in v4.3.dev.custom_build [c5e6a5863]
https://github.com/godotengine/godot/commit/c5e6a5863db21ecbcbc6fcd006cb2aac744d39cd

### System information

Godot v4.3.dev (bd8380db5) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Starting with v4.3.dev.custom_build [bd8380db5] https://github.com/godotengine/godot/commit/bd8380db5534af18fb4fab76daac77ef420becb4 Godot appears to throw this error once for each synced variable contained within any MultiplayerSynchronizer in an open scene:
`modules\multiplayer\scene_replication_config.cpp:59 - Condition "p_value.get_type() != Variant::BOOL" is true. Returning: false`

![image](https://github.com/godotengine/godot/assets/6188278/4f3afd73-c4f5-4063-9eae-06c621f50779)

### Steps to reproduce

`gh repo clone chrisl8/space-game`
Open it up with 4.3 bd8380db5 or newer.
Open up the `player` folder
Open the `player` scene

### Minimal reproduction project (MRP)

I was not able to reproduce this with any basic startup project or Godot demo project.
You can clone my project from here and the error is consistent:
https://github.com/chrisl8/space-game

Then open up the `player.tscn` inside of the `player` folder.
It also happens with any other scene with a MultiplayerSynchronizer in it such as most of the scenes in folders under `things`.

**Comment by mr-dreich** [comment]
I have a project I have been working on for a long time, I was curious about 4.3, so I tried it in 4.3-dev3, and that worked fine. But after trying it in dev4, it crashes almost immediately, but works fine in Windows 10. I have tried it in Forward+, Mobile, and Compatibility. 

This error seems really similar to what I am experiencing, but if this actually isn't similar, I don't mind opening my own error.

```
Godot Engine v4.3.dev4.official.df78c0636 - https://godotengine.org
Vulkan 1.2.275 - Forward+ - Using Device #0: Apple - Apple M1
USER WARNING: Invalid/corrupt pipelines cache.
   at: pipeline_cache_create (drivers/vulkan/rendering_device_driver_vulkan.cpp:3832)

USER ERROR: FATAL: Index p_index = 2 is out of bounds (size() = 2).
   at: get (./core/templates/cowdata.h:205)

================================================================
handle_crash: Program crashed with signal 5
Engine version: Godot Engine v4.3.dev4.official (df78c0636d79c9545a283e0e2a926d623998cc27)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] 1   libsystem_platform.dylib            0x000000018872da24 _sigtramp + 56
[2] 2   ???                                 0xffff8001045d4988 0x0 + 18446603340589386120
[3] ItemList::get_v_scroll_bar()
[4] Node::get_tree() const
[5] MultiplayerAPI::is_server()
[6] PlaceholderExtensionInstance::placeholder_class_recreate_instance(void*, void*)
[7] Node::atr_n(String, StringName const&, int, StringName) const
[8] Node::atr_n(String, StringName const&, int, StringName) const
[9] RendererCompositorRD::_create_current()
[10] void rx::mtl::GetMatrixUniformMetal<unsigned int>(unsigned int, unsigned int*, unsigned int const*, bool)
[11] RendererCompositorRD::_create_current()
[12] 12  dyld                                0x000000018837d0e0 start + 2360
-- END OF BACKTRACE --
================================================================
```

**Comment by akien-mga** [comment]
@mr-dreich Your error doesn't appear to be related to the OP. Could you open a new issue?

**Comment by Faless** [comment]
It seems that something changed in the way we set the initial values of resources from a file, and they are now being set twice.
The first time, it all goes well, the second time, the [consistency check in the setter](https://github.com/godotengine/godot/blob/master/modules/multiplayer/scene_replication_config.cpp#L43) now fails.

Adding some prints, it's clear that `_set` is being called 2 times for each properties.

We can probably play around with the check, though this seems like a regression in resource loading?

```
WARNING: Prop num: 0, idx: 0, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 1, idx: 0, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 1, idx: 0, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 1, idx: 1, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 2, idx: 1, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 2, idx: 1, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 2, idx: 2, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 3, idx: 2, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 3, idx: 2, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)

[.....]

WARNING: Prop num: 8, idx: 0, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
ERROR: Invalid value '.:player' for property 'properties/0/path'
   at: _set (modules/multiplayer/scene_replication_config.cpp:60)
WARNING: Prop num: 8, idx: 0, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 8, idx: 0, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 8, idx: 1, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
ERROR: Invalid value '.:position' for property 'properties/1/path'
   at: _set (modules/multiplayer/scene_replication_config.cpp:60)
WARNING: Prop num: 8, idx: 1, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 8, idx: 1, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 8, idx: 2, what: path
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
ERROR: Invalid value '.:linear_velocity' for property 'properties/2/path'
   at: _set (modules/multiplayer/scene_replication_config.cpp:60)
WARNING: Prop num: 8, idx: 2, what: spawn
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)
WARNING: Prop num: 8, idx: 2, what: replication_mode
     at: _set (modules/multiplayer/scene_replication_config.cpp:43)

[...]
```

**Comment by akien-mga** [comment]
> ### Tested versions
> 
> * Reproducible in v4.3.dev.custom_build [[bd8380d](https://github.com/godotengine/godot/commit/bd8380db5534af18fb4fab76daac77ef420becb4)] and all subsequent commits including master
>  [bd8380d](https://github.com/godotengine/godot/commit/bd8380db5534af18fb4fab76daac77ef420becb4)
> 
> * Not Reproducible in v4.3.dev.custom_build [[c5e6a58](https://github.com/godotengine/godot/commit/c5e6a5863db21ecbcbc6fcd006cb2aac744d39cd)]
>  [c5e6a58](https://github.com/godotengine/godot/commit/c5e6a5863db21ecbcbc6fcd006cb2aac744d39cd)

This is the comparison between those two commits: https://github.com/godotengine/godot/compare/c5e6a5863db21ecbcbc6fcd006cb2aac744d39cd...bd8380db5534af18fb4fab76daac77ef420becb4

I tested a local revert and confirmed that this is caused by #85501.

CC @Jordyfel @adamscott

**Comment by Jordyfel** [comment]
https://github.com/godotengine/godot/blob/f2045ba822bff7d34964901393581a3117c394a9/core/io/resource.h#L96

@Faless it seems `SceneReplicationConfig` will need to implement this function.

Doing it lazily like so fixes the issue.
```
void SceneReplicationConfig::reset_state() {
	properties.clear();
	sync_props.clear();
	spawn_props.clear();
	watch_props.clear();
}
```

**Comment by Faless** [comment]
@Jordyfel thanks! I had no clue that function existed , I've opened #89108 with your suggested change.

**Comment by alexeocto** [comment]
I am getting the same error on 4.2. 

Should I just upgrade to 4.3 to take advantage of the proposed fix in https://github.com/godotengine/godot/pull/89108.

**Comment by Jordyfel** [comment]
@alexeocto I've come across this error in 4.2 as well, and since the PR hasn't been cherry-picked, the only way to get rid of it is by upgrading to 4.3, yes
