### ISSUE TITLE
Removing Script Editor feature disables openning scripts with configured external editor

### ISSUE THREAD

**Issue by yosubis** [godotengine/godot#89035]
### Tested versions

- Reproducible in v4.2.1.stable.official.b09f793f5

### System information

Windows 10 - Godot Engine v4.2.1.stable

### Issue description

I have VS Code configured as an external editor. Opening a script for editing, through clicking on the attached script icon in the Scene dock or double-clicking a script file in the Filesystem dock, opens the script in VS Code.

However, disabling the Script Editor disables this functionality. Clicking the attached script icon or double clicking a script file just selects the script file and shows the script standard view in the inspector.

I felt comfortable disabling the Script Editor since in the description box in "Manage Editor Features" it says "Allows to edit scripts using the integrated script editor", so I thought it won't affect the external editor.

### Steps to reproduce

In the editor
Main Menu -> Editor -> Manage Editor Features -> deselect Script Editor
Try to open any script file

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for your report, consolidating in:
* https://github.com/godotengine/godot/issues/59758
