### ISSUE TITLE
ERROR: Condition "actions.default_filter == ShaderLanguage::FILTER_DEFAULT" is true. Returning: String() when running Headless with 4.3 Dev4

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#89031]
### Tested versions

 - Reproducible in: v4.3.dev4.official [df78c0636]
 - Not Reproducible in: v4.3.dev3.official [36e943b6b]

### System information

Godot v4.3.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Repeated errors like this when building in a headless system:

```
ERROR: Condition "actions.default_filter == ShaderLanguage::FILTER_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:279)
```

Note that I'm running this in Linux in WSL2 on Windows, if that matters. Basically, the OS has no video.
I got the same errors on a Digital Ocean droplet (VM) too.

### Steps to reproduce

gh repo clone godotengine/godot-demo-projects

Edit `export_presets.cfg` and change `platform="Linux/X11"` to `platform="Linux"` first.

Then build it from the command line

`Godot_v4.3-dev4_linux.x86_64 --headless --quiet --path $HOME/Clone/godot-demo-projects/3d/platformer --export-release Linux/X11 $HOME/platformer.x86_64`

```
WARNING: Custom cursor shape not supported by this display server.
     at: cursor_set_custom_image (servers/display_server.cpp:514)
ERROR: Condition "actions.default_filter == ShaderLanguage::FILTER_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:279)
ERROR: Condition "actions.default_filter == ShaderLanguage::FILTER_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:279)
ERROR: Condition "actions.default_filter == ShaderLanguage::FILTER_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:279)
ERROR: Condition "actions.default_repeat == ShaderLanguage::REPEAT_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:283)
ERROR: Condition "actions.default_repeat == ShaderLanguage::REPEAT_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:283)
ERROR: Condition "actions.default_repeat == ShaderLanguage::REPEAT_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:283)
ERROR: Condition "actions.default_repeat == ShaderLanguage::REPEAT_DEFAULT" is true. Returning: String()
   at: _get_sampler_name (servers/rendering/shader_compiler.cpp:283)
```

You don't actually have to do a build, also running the game headless, such as as a server on a Linux host.

### Minimal reproduction project (MRP)

This can be reproduced with the Godot 3D Platformer demo project at https://github.com/godotengine/godot-demo-projects/tree/master/3d/platformer

However, you must edit `export_presets.cfg` and change `platform="Linux/X11"` to `platform="Linux"` first.

**Comment by jsjtxietian** [comment]
See https://github.com/godotengine/godot/issues/88990 , already fixed in master

**Comment by akien-mga** [comment]
Thanks for the report. Consolidating in
- #88990
