### ISSUE TITLE
Clearing a TextEdit on action "ui_accept" leaves an additional empty line

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#89037]
### Tested versions

- Reproducible on Godot 4.2, and Master ([7d2ca2d](https://github.com/godotengine/godot/commit/7d2ca2d8ac49cde9767e00b70f9eaf1920eb266d))

### System information

Godot v4.2.1.stable - Ubuntu 22.04 - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (RPL-P) () - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

This might be an expected behavior due to how signals work, but I'm opening an issue just in case it's not.

Use case is to have a chat-like input area, where you can press `Enter` to send the message, and `Shift + Enter` to go to next line without sending a message.

The `TextEdit` node can emit a `gui_input` signal. When listening to `ui_accept` (in this case, `Enter`), running `$TextEdit.clear()` removes the text correctly, but leaves an empty line.

### Steps to reproduce

- Add a `TextEdit`
- Attach the following function to the `gui_input` signal
```gdscript
func _on_text_edit_gui_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept"):
		print("Enter pressed.")
		print("Entered Text : " + $TextEdit.text)
		# Does not work
		$TextEdit.clear()
```
- Run the project, enter some text, and press `Enter`
- Expected behavior : Clear the `TextEdit` and show the placeholder text
- Actual behavior: There is a white line added due to `Enter`, and the placeholder text does not appear, since the field is not empty

Note that using `$TextEdit.clear.call_deferred()` works as expected.

### Minimal reproduction project (MRP)

[textedit.zip](https://github.com/godotengine/godot/files/14460540/textedit.zip)

**Comment by Sauermann** [comment]
Would have to test the MRP, but my preliminary guess is that the code above is missing an `accept_event()` in order to mark the event as handled.

**Comment by hakro** [comment]
That is correct. The following piece worked : 

```gdscript
if event.is_action_pressed("ui_accept"):
	accept_event()
	print("Entered Text : " + $TextEdit.text)
```

Then I guess this is not a bug, but an expected behavior, so I'll close the issue.

Thank you for your help Sauermann :)
