### ISSUE TITLE
Tool mode does nothing

### ISSUE THREAD

**Issue by Tarocco** [godotengine/godot#8903]
Windows 10 x64, Godot 2.1.3 stable, official

Adding tool mode to a script on a Node object in the scene tree should allow it to run in the editor as the current documentation states.

I have

```gdscript
tool
extends Node

func _ready():
	print('henlo')
	set_process(true)

func _process(delta):
	print('henlo again')
```

and I expect `henlo` and `henlo again` to show up in the output before playing the project, but nothing happens until I press play. Then it works as expected, but not working in the editor.

Am I missing something?

**Comment by neikeq** [comment]
I think your issue is the same as #8748

**Comment by Tarocco** [comment]
@neikeq This seems to be the case, and I can see the output in the editor console window. Thank you for pointing this out. Maybe future versions of Godot can address this, or it should be added to the documentation.
