### ISSUE TITLE
Godot Debug Adapter Response is missing required field variablesReference in EvaluateResponse

### ISSUE THREAD

**Issue by dekaravanhoc** [godotengine/godot#89052]
### Tested versions

- Reproducable 4.2.1,stable , 4.2.2.rc1

### System information

Godot v4.2.2.rc1 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Based on the Debug Adapter Protocol Specifications the Response to an Evaluate Request needs the field variablesReference
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate

Currently it is not part of the response:
```
{
  arguments = {
    context = "hover",
    expression = "save_state",
    frameId = 0
  },
  command = "evaluate",
  seq = 24,
  type = "request"
}
[ DEBUG ] 2024-03-01T13:52:07Z+0100 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:951 ]	1	{
  body = {
    result = '{ "metal_upgrade_group": {  }, "health": 2000, "weapon_systems": { "res://game/entities/player_ship/ship_upgrades/weapon_systems/laser_beam/laser_beam.tscn": { "metal_upgrade": { "metal_upgrade_group": {  } }, "current_upgrades_paths": [], "number_of_deployed_turrets": 2 }, "res://game/entities/player_ship/ship_upgrades/weapon_systems/cannon/start_cannon.tscn": { "metal_upgrade": { "metal_upgrade_group": {  } }, "current_upgrades_paths": [], "number_of_deployed_turrets": 2 } }, "combat_modules": { "res://game/entities/player_ship/ship_upgrades/combat_modules/shield_generator/shield_generator.tscn": { "metal_upgrade_group": {  }, "is_deployed": true } } }'
  },
  command = "evaluate",
  request_seq = 24,
  seq = 47,
  success = true,
  type = "response"
}
```

This leads to errors i.e. in the debugger client of nvim - nvim-dap.

### Steps to reproduce

1. Send an evaluate request to the debug adapter

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @rsubtil
