### ISSUE TITLE
Refraction not working on StandardMaterial3D

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot#89057]
### Tested versions

- Reproduceable in: Godot v4.2.1.stable, v4.3.dev.mono.custom_build [a47830c66]

### System information

Godot v4.2.1.stable - Pop!_OS 22.04 LTS - Wayland - Vulkan (Mobile) - dedicated Intel(R) Arc(tm) A750 Graphics (DG2) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Refraction is not working on the standard shader as I would expect it to.  Here are some pics:

## Default Refraction Enabled:

![image](https://github.com/godotengine/godot/assets/24307049/259d16bb-06d5-47a5-9be2-6fac6dccad9f)

## Refraction with 0 scale (which I assumed should be no refraction / be disabled):

![image](https://github.com/godotengine/godot/assets/24307049/4c89d975-7646-4b59-b325-05b5c10edf86)

## Refraction Disabled:

![image](https://github.com/godotengine/godot/assets/24307049/906fcb11-e639-4db8-af76-2150c305397f)

I would have expected the background sphere to be distorted but still visible with refraction enabled.  Something more akin to this:

![image](https://raw.githubusercontent.com/NathanWarden/godot_refraction_shader/main/icon.png)

Image above from this repo: https://github.com/NathanWarden/godot_refraction_shader

### Steps to reproduce

1. Download the MRP.
2. Open the refraction.tcsn scene
3. See the sphere in front behaving cloudy and opaque instead of refracting its background environment.

### Minimal reproduction project (MRP)

[RefractionExample.zip](https://github.com/godotengine/godot/files/14464630/RefractionExample.zip)

**Comment by Calinou** [comment]
Material roughness is 1.0 by default, which means the underlying refraction is very rough (and therefore blurry). If you want the refraction to be sharper, decrease material roughness.

PS: Refraction rendering on the Mobile rendering method is currently broken because of https://github.com/godotengine/godot/issues/88585.

**Comment by TCROC** [comment]
Nevermind, I found the issue:

Roughness defaults to 1 which results in the 100% cloudy behavior.  Reducing the roughness causes the refraction as I expect:

![image](https://github.com/godotengine/godot/assets/24307049/d6fd73df-7f07-44da-a21a-9d287513c535)

Should we add some kind of note / info popup that notes the effect of roughness on refraction?

**Comment by TCROC** [comment]
Lol @Calinou commented at the same time I found this.  Thanks @Calinou ! :)
