### ISSUE TITLE
MeshInstance2D does not update mesh when using custom PrimitiveMesh

### ISSUE THREAD

**Issue by TheArchitect4855** [godotengine/godot#89067]
### Tested versions

Found in: v4.2.1.stable.official [b09f793f5]
Reproducible in:
- v4.3.dev4.official [df78c0636]
- v4.2.2.rc1.official [c7fb0645a]
- v4.1.3.stable.official [f06b6836a]
- v4.0.4.stable.official [fc0b241c9]

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.4633) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 Threads)

### Issue description

When using a custom `PrimitiveMesh` type via GDScript, changing its parameters in the editor does not update the actual mesh until you update another built-in property.

Expected behaviour: Changing the parameters should update the mesh, as with the built-in `PrimitiveMesh` types.

Here is the custom PrimitiveMesh type, for reference:
```gdscript
@tool
class_name CircleMesh
extends PrimitiveMesh

@export var radius := 1.0:
	set(value):
		if radius != value:
			radius = value
			emit_changed()

@export var vertex_count := 32:
	set(value):
		if vertex_count != value:
			vertex_count = value
			emit_changed()

func _create_mesh_array() -> Array:
	var vertices := PackedVector3Array()
	vertices.append(Vector3.ZERO)
	
	var uvs := PackedVector2Array()
	uvs.append(Vector2.ONE * 0.5)
	
	for i in range(0, vertex_count):
		var theta = (2.0 * PI / vertex_count) * i
		var dir = Vector3(sin(theta), cos(theta), 0.0)
		vertices.append(dir * radius)
		uvs.append(Vector2(dir.x, dir.y))
	
	var indices := PackedInt32Array()
	for i in range(0, vertex_count):
		indices.append(i + 1)
		indices.append(i + 2)
		indices.append(0)
	
	indices.append(vertex_count)
	indices.append(1)
	indices.append(0)
	
	var arrays = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = vertices
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	arrays[Mesh.ARRAY_INDEX] = indices
	return arrays
```

### Steps to reproduce

- Open the attached project
- Open `example.tscn`, and select the root node
- Change either "Radius" or "Vertex Count" in the inspector
- The mesh in the scene does not change until you change some other built-in property of the `PrimitiveMesh`

### Minimal reproduction project (MRP)

[PrimitiveMesh Demo.zip](https://github.com/godotengine/godot/files/14465575/PrimitiveMesh.Demo.zip)

**Comment by clayjohn** [comment]
Taking a quick look at PrimitiveMesh, I don't think it is intended for your code to work. 

When properties are changed on a PrimitiveMesh they don't emit the changed signal, they request an update:
https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/scene/resources/3d/primitive_meshes.cpp#L289-L292

https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/scene/resources/3d/primitive_meshes.cpp#L132-L137

From there `_update()` is called:
https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/scene/resources/3d/primitive_meshes.cpp#L44-L51

And emit_changed is called at the end of that function:
https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/scene/resources/3d/primitive_meshes.cpp#L129-L130

So I don't think calling emit_changed is sufficient to have the engine call `_create_mesh_array()` for you. I'm not familiar with the exposed API, but I think you should check and see if you can call `request_update()` or call something else that will result in `_update()` getting called. If that's not possible, then we need to expose it in some way

**Comment by TheArchitect4855** [comment]
I took a look through the source and couldn't find `request_update` exposed to GDScript anywhere, and it doesn't work using it my script either (I tried replacing `emit_changed` with `request_update`), so it looks like it will need to be exposed somehow.

**Comment by clayjohn** [comment]
It looks like TextMesh exposes `request_update()` directly, so we could probably do the same thing for Primitive mesh https://github.com/godotengine/godot/blob/dad6c774b019ef8c5dccb4a1955c6a77b41a323e/scene/resources/3d/primitive_meshes.cpp#L3343
