### ISSUE TITLE
Can't edit exported nodes in array as text

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89065]
### Tested versions

4.3 dev4
But likely existed since much earlier.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When using the Edit option from NodePath's `⋮` menu, when the property is an Array of Nodes
![image](https://github.com/godotengine/godot/assets/2223172/712e03fb-c717-4f75-bc69-e02bab2bce43)
submitting the text results in an error
```
  Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:413 - Condition "!_p->typed.validate(value, "set")" is true.
```

### Steps to reproduce

1. `@export var a: Array[Node]
2. In the inspector, add element to array
3. Use Edit option from `⋮` menu
4. Type something and press Enter

### Minimal reproduction project (MRP)

N/A

**Comment by des54321** [comment]
does it give the same error when its just a Node and not in an array?

**Comment by KoBeWi** [comment]
No.
