### ISSUE TITLE
Godot doesn't respond after running

### ISSUE THREAD

**Issue by P-Star7** [godotengine/godot#8906]
**Operating system or device - Godot version:**
Windows 10 64-bit
x86
Intel HD Graphics 520 + Nvidia GeForce 940M
Godot 2.1.3 Win64
**Issue description:**

I opened the .exe, and a black command line window opened with the following:
EXEC PATHP??: C:\Users\P-Star7\Downloads\Godot_v2.1.3-stable_win64.exe\Godot_v2.1.3-stable_win64.exe
EXEC PATHP??: C:\Users\P-Star7\Downloads\Godot_v2.1.3-stable_win64.exe\Godot_v2.1.3-stable_win64.exe
EXEC PATHP??: C:\Users\P-Star7\Downloads\Godot_v2.1.3-stable_win64.exe\Godot_v2.1.3-stable_win64.exe
DETECTED MONITORS: 1
And the main Godot window has no label and is white, and just never responds. So you have to close it by clicking until Windows asks you to close it.

**Steps to reproduce:**
1. Download the Godot_v2.1.3-stable_win64
2. Run the .exe

**Notes**
I tried to run as administrator, use compatibility troubleshooter, and run with both graphics cards by right-clicking. But nothing changed in any of these methods. Both graphics drivers are fully upgraded. I downloaded the Realtech OpenGL statistics viewer thing and it said that my version was 4.4. I also have DirectX 9.0c and 12 on the computer. The OpenGL statistics reported the version of DirectX as 9.0c but dxdiag reports it as 12. Maybe this is affecting Godot, as it is an OpenGL application?

**Comment by Zylann** [comment]
Are you on a laptop with two graphics chipsets? It could be that Godot ends up running on the weaker one.

**Comment by Ahmed0425** [comment]
perhaps a stupid question but ...
did you highlight any text in the console?
if so, all relevant processes should stop

**Comment by P-Star7** [comment]
1. Yes, I think so. I tried to right click and say run with either card but it doesn't work.
2. Oh no, I didn't click on anything, besides to copy paste this. Running it without doing anything results in it locking up.

**Comment by P-Star7** [comment]
Is there anything that I can do?

**Comment by akien-mga** [comment]
As there was no answer the above request, we're closing this issue as inactive.
If you can still reproduce it, please open a new issue against a currently supported release of Godot.
