### ISSUE TITLE
First mouse click is ignored / does not work

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8907]
**Operating system or device - Godot version:**
osx 3.0 current master

**Issue description:**

The first mouse press gets ignored sometimes -> to click on something I have to double click.

I finally found a pattern so I open the issue, (it was discussed before already. Couldn't find it though...)

This happens when I send input events (click on) to the godot window during loading.

**Steps to reproduce:**
start godot. click on the loading screen. click on any ui element -> you will need to press twice that the button works.

**Comment by toger5** [comment]
this happens when the window is not active. minimising and opening again fixes that state.

**Comment by bojidar-bg** [comment]
@BastiaanOlij I think you reported you can confirm this as well, correct?

**Comment by BastiaanOlij** [comment]
yes, intermittedly but fairly often. Unlike toger5 I haven't figured out a pattern yet but if it happens it remains constant. Often restarting Godot fixes it for a few tries.

**Comment by toger5** [comment]
Also the name in the top bar of the OS X window is grayed out when the bug happens. As mentioned before. minimising and maximising gives the window focus again, makes the top bar active (not graded out) and the input is fixed

**Comment by bruvzg** [comment]
.app bundle or stand-alone executable? This is typical behaviour for non-bundled apps.

**Comment by toger5** [comment]
@bruvzg nice that someone catches up on this one. Yea I'm just starting the executable via console.
so that might be the issue!

how would I bundle it as an .app?

**Comment by bruvzg** [comment]
@toger5 

```
user@host:~/godot$ cp -r misc/dist/osx_tools.app ./Godot.app
user@host:~/godot$ mkdir -p Godot.app/Contents/MacOS
user@host:~/godot$ cp bin/godot.osx.opt.tools.64 Godot.app/Contents/MacOS/Godot
user@host:~/godot$ chmod +x Godot.app/Contents/MacOS/Godot
```

**Comment by bruvzg** [comment]
@toger5 another possible way for stand-alone executable is _TransformProcessType_ / _CPSEnableForegroundOperation_ hack (undocumented and may be outdated).

[www.miscdebris.net](http://www.miscdebris.net/blog/2010/03/30/solution-for-my-mac-os-x-gui-program-doesnt-get-focus-if-its-outside-an-application-bundle/comment-page-1/)
[Tcl/Tk repo](https://github.com/das/tcltk/blob/master/tk/carbon/tkMacOSXInit.c#L282)

**Comment by toger5** [comment]
Thank you!
@bruvzg taking your input this seems to be a developer only issue and not part of the actual app.
We might want to add your console commands to the post compile Xcode script in the docs to improve the developer experience.
I close this one and create a new one in the docs repo.

**Comment by ComancheAk** [comment]
[godot_bundle.zip](https://github.com/godotengine/godot/files/1380648/godot_bundle.zip)
I've made a bash script for bundle

**Comment by akien-mga** [comment]
Maybe something could be added to the "Compiling for OSX" page to mention that making a .app is recommended for optimal experience? http://docs.godotengine.org/en/latest/development/compiling/compiling_for_osx.html

**Comment by akien-mga** [comment]
Yes, as far as I know you can run .app bundles from the command line.
