### ISSUE TITLE
The screen don't display everything in mobile

### ISSUE THREAD

**Issue by Ohcccccccccccccccc** [godotengine/godot#89080]
### Tested versions

4.2.1 The screen don't display everything in mobile

### System information

Mobile

### Issue description

The screen don't display everything in mobile

### Steps to reproduce

The screen don't display everything in mobile

### Minimal reproduction project (MRP)

The screen don't display everything in mobile

**Comment by akien-mga** [comment]
You need to fill in the information we ask for in the issue template, otherwise we can't do anything.

**Comment by Ohcccccccccccccccc** [comment]
When I export in godot and put android it go out of the screen

**Comment by AThousandShips** [comment]
That's solved, see:
* https://github.com/godotengine/godot/issues/85551

Try [4.2.2.rc1](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-1/)

**Comment by Ohcccccccccccccccc** [comment]
Thanks 👍😊
