### ISSUE TITLE
The screen don't display everything in mobile

### ISSUE THREAD

**Issue by Ohcccccccccccccccc** [godotengine/godot#89082]
### Tested versions

4.2.1

### System information

Mobile

### Issue description

When I export in godot and put android it go out of the screen 

### Steps to reproduce

Project settings export Android

### Minimal reproduction project (MRP)

The screen don't display everything in mobile

**Comment by AThousandShips** [comment]
Please do not open a new issue like this, instead communicate on the original one until you get a response, as you can see there you were given a solution
