### ISSUE TITLE
C#: 'RigidBody3D' does not contain a definition for 'SetLinearVelocity'

### ISSUE THREAD

**Issue by Nomicron** [godotengine/godot#89097]
### Tested versions

v4.2.1.stable.mono.official

### System information

Windows 11 Godot 4.2.1

### Issue description

The method "SetLinearVelocity" in C# does not exist in the class "RigidBody3D", despite it working when using GD script. It is of course spelled differently in GD script: "set_linear_velocity", but in C# that spelling does not work either, and the correct spelling of the method is impossible to find anywhere. 
![image](https://github.com/godotengine/godot/assets/161974779/2b521baf-9a5c-4d77-a69c-235f8656fc54)

![image](https://github.com/godotengine/godot/assets/161974779/f25cc91b-b9d9-4a62-91a1-c61ce25b7feb)

The error I recieve when using "SetLinearVelocity" in C# is: 

CS1061: 'RigidBody3D' does not contain a definition for 'SetLinearVelocity' and no accessible extension method 'SetLinearVelocity' accepting a first argument of type 'RigidBody3D' could be found (are you missing a using directive or an assembly reference?)

Is this method specifically spelled differently in C#, compared to the other methods in C# or what?

### Steps to reproduce

Just write the above said code in C# in a RigidBody3D.

### Minimal reproduction project (MRP)

Is not needed

**Comment by AThousandShips** [comment]
In C# you don't get setters and getters, you should use the property directly

**Comment by Nomicron** [comment]
I totally missed that! Sorry I am still new to the engine and programming in general. Thank you so much, it works now!
