### ISSUE TITLE
4.3: RichTextLabel.text = "" no longer clears contents and RichTextLabel.clear() no longer has an effect outside of scene tree

### ISSUE THREAD

**Issue by Nallebeorn** [godotengine/godot#89091]
### Tested versions

Reproduced in 4.3-dev4. Not reproducible in 4.2.1-stable.

### System information

Windows 11

### Issue description

I'm not 100% sure if this is in fact a bug, but it is at the very least an unexpected version incompatibility.

The behaviour of `RichTextLabel.clear()` and `RichTextLabel.text = ""` is different between Godot 4.2 and 4.3.

The context is instantiating a scene with a single RichTextLabel containing some placeholder text, and then immediately clearing the text when adding the instantiated node to the scene tree (the placeholder text is useful for testing the RichTextLabel scene in isolation).

In Godot 4.2:
- When calling `clear()` or setting `text = ""` before the node is added to the scene tree (between instantiating a scene and calling `add_child`), the RichTextLabel will appear empty as expected.

In Godot 4.3-dev4:
- When calling `clear()` before the node is added to the scene tree (between instantiating a scene and calling `add_child`), the RichTextLabel still has the placeholder text from the original scene.
- When setting `text = ""`, either before or after `add_child`, the original text remains visible. This means you essentially have to call both `clear()` and set `text = ""` to fully reset the contents.

### Steps to reproduce

```gdscript
extends Control

const TextLabel := preload("res://rich_text_label.tscn")

# Produces expected behavior in 4.2, but in 4.3

func _ready() -> void:
	var label := TextLabel.instantiate() as RichTextLabel
	label.text = ""
	add_child(label)
	#label.clear() # uncommenting this line will produce the expected behavior in 4.3
	label.text = "" # commenting this line will still produce the expected behavior in 4.2

```

### Minimal reproduction project (MRP)

[RichTextLabel-Bug-4.3.zip](https://github.com/godotengine/godot/files/14470126/RichTextLabel-Bug-4.3.zip)

**Comment by AThousandShips** [comment]
It's due to this code:
https://github.com/godotengine/godot/blob/f2045ba822bff7d34964901393581a3117c394a9/scene/gui/rich_text_label.cpp#L5678-L5681

CC @YeldhamDev
