### ISSUE TITLE
DisplayServer FullScreen is not working correctly

### ISSUE THREAD

**Issue by xiaoxustudio** [godotengine/godot#89107]
### Tested versions

Godot v4.2.2.rc1

### System information

Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4953) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

When I'm maximized, then I set the display mode to full screen, and then I set it to window again, it doesn't set it to window, it sets it to full screen（Project Setting **display/window/stretch/mode** is True）

```gdscript
extends Control

func _ready() -> void:
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MAXIMIZED)


# first run this 
func _on_button_button_down() -> void:
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)

# and run this 
func _on_button_2_button_down() -> void:
	DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)


```

### Steps to reproduce

1. set display/window/stretch/mode to true.
2. set window display mode is DisplayServer.WINDOW_MODE_MAXIMIZED
3. set window display mode is DisplayServer.WINDOW_MODE_FULLSCREEN
4. set window display mode is DisplayServer.WINDOW_MODE_WINDOWED
5. oh ! it is cannot to set DisplayServer.WINDOW_MODE_WINDOWED

### Minimal reproduction project (MRP)

[Uploading test.zip…]()

**Comment by xiaoxustudio** [comment]
This problem persists in dev4 as of 4.3

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70166.
