### ISSUE TITLE
IsInstanceValid not properly tracking disposal when called within a Deferred method (executed on main thread) from an async/multithreaded method

### ISSUE THREAD

**Issue by astrobeef** [godotengine/godot#89105]
### Tested versions

- Only tested in Godot v4.1.1 stable .NET, both with Forward and Compatibility mode

### System information

Windows 10 - Godot_v4.1.1-stable .NET - Compatibility/Forward

### Issue description

The issue is caused by attempting to set the texture of Sprite2D in an await method (separate thread) by using CallDeferred (main thread) when the Sprite2D is disposed. The check IsInstanceValid, when called from the Deferred method running on the main thread, does not properly check if the Sprite2D is valid. It will always see the Sprite2D as still valid and not disposed. But when the texture is set, an error will be thrown that the Sprite2D is in fact disposed.

### Steps to reproduce

1. Create a Sprite2D
2. Attach a C# script to the Sprite2D
3. In the script, create an async method which will load a Texture resource.
4. Use CallDeferred to assign the texture to the Sprite2D
5. Check using IsInstanceValid to see if the Sprite2D has been disposed
6. Get the error: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Godot.Sprite2D'.

`

	private const string TEXTURE_PATH = "res://icon.svg"; // Path to the texture being loaded.
	private static object _setTextureLock = new object(); // Lock object for thread-safe loading.

	/// <summary>
	/// Called when the node enters the scene tree for the first time.
	/// This method initiates the process of setting a texture and then disposing of the sprite.
	/// </summary>
	public override void _Ready()
	{
		SetTextureAndDispose(this);
	}

	/// <summary>
	/// Asynchronously loads a texture and assigns it to the provided sprite, then disposes of the sprite.
	/// </summary>
	/// <param name="spriteDisposed">The sprite that will have its texture set and then be disposed.</param>
	public async void SetTextureAndDispose(Sprite2D spriteDisposed)
	{
		// Load the texture off the main thread.
		Texture2D texture = await LoadImageOffloaded(TEXTURE_PATH, _setTextureLock);
		if (texture == null) throw new NullReferenceException($"Could not find Texture2D by name: {TEXTURE_PATH}");

		// Attempt to set the texture via a deferred call and then dispose of the sprite.
		Call_DeferredSetTexture(spriteDisposed, texture);
		spriteDisposed.QueueFree();
	}

	/// <summary>
	/// Loads a texture in a background thread.
	/// </summary>
	/// <param name="path">Path to the texture resource.</param>
	/// <param name="lockObj">Lock object for synchronization.</param>
	/// <returns>A task that completes with the loaded texture.</returns>
	public Task<Texture2D> LoadImageOffloaded(string path, object lockObj)
	{
		return Task.Run(() =>
		{
			lock (lockObj)
			{
				Texture2D texture2D = ResourceLoader.Load<Texture2D>(path);
				return texture2D;
			}
		});
	}

	/// <summary>
	/// Schedules the texture setting operation to be performed after a delay.
	/// This is used to simulate a scenario where the sprite might be disposed before setting the texture.
	/// </summary>
	/// <param name="sprite2D">The sprite to set the texture on.</param>
	/// <param name="texture2D">The texture to be set on the sprite.</param>
	public async void Call_DeferredSetTexture(Sprite2D sprite2D, Texture2D texture2D)
	{
		// Intentional delay to simulate delayed execution that leads to accessing a disposed object.
		await Task.Delay(1000);
		CallDeferred(nameof(DeferredSetTexture), sprite2D, texture2D);
	}

	/// <summary>
	/// Method intended to be called using CallDeferred to safely set the texture on the main thread.
	/// It checks if the sprite and its parent nodes are valid before setting the texture.
	/// </summary>
	/// <param name="sprite2D">The sprite to set the texture on.</param>
	/// <param name="texture2D">The texture to be set on the sprite.</param>
	private void DeferredSetTexture(Sprite2D sprite2D, Texture2D texture2D)
	{
		// Check for the validity of the node and its parents before setting the texture.
		if (IsNodeAndParentsValid(sprite2D)
		 && Godot.GodotObject.IsInstanceValid(sprite2D))
		{
			sprite2D.Texture = texture2D;
		}
	}

	/// <summary>
	/// Checks if a node and all its parent nodes up to the root are valid (not disposed).
	/// </summary>
	/// <param name="node">The node to start the check from.</param>
	/// <returns>True if the node and all its parents are valid, false otherwise.</returns>
	private static bool IsNodeAndParentsValid(Node node)
	{
		while (node != null)
		{
			if (!Godot.GodotObject.IsInstanceValid(node))
			{
				return false;
			}
			node = node.GetParent();
		}
		return true;
	}
	`

### Minimal reproduction project (MRP)

[ReproduceDisposalCheckIssue.zip](https://github.com/godotengine/godot/files/14471698/ReproduceDisposalCheckIssue.zip)

**Comment by paulloz** [comment]
Hello 🙂 

The error in your MRP does not come from after the `IsInstanceValid()` check. That check is never performed, the error is thrown from the `CallDeferred()` line (right after the `await`) because you're essentially disposing of `this`, so `this.CallDeferred()` is indeed trying to access a disposed object. In addition, the `sprite2D` argument of that call is going to get accessed so it can be marshalled too, leading to the same error. In both cases, the behaviour of `IsInstanceValid()` is not the issue.

**Comment by astrobeef** [comment]
> Hello 🙂
> 
> The error in your MRP does not come from after the `IsInstanceValid()` check. That check is never performed, the error is thrown from the `CallDeferred()` line (right after the `await`) because you're essentially disposing of `this`, so `this.CallDeferred()` is indeed trying to access a disposed object. In addition, the `sprite2D` argument of that call is going to get accessed so it can be marshalled too, leading to the same error. In both cases, the behaviour of `IsInstanceValid()` is not the issue, and everything AFAICS works as intended.

Thank you for taking a look! You're completely right; I added a check just before CallDeferred and that fixed the issue. I was struggling with this for a while and I didn't realize CallDeferred could be the problem.

I'm closing this since it's not an issue and just an oversight by me. Thanks again for the help
