### ISSUE TITLE
Region section is not correctly handled when "#endregion" is set in a string variable inside the region

### ISSUE THREAD

**Issue by TheRealSlander** [godotengine/godot#89115]
### Tested versions

Godot 4.3 dev 4 (probably previous versions as well)

### System information

Manjaro Linux (DE: Cinnamon v6.0.4) 64 bits (but probably all systems)

### Issue description

When using the comment regions in a script, if a string inside a region contains "#endregion" alone on a single line, it triggers the region's end prematurely and then messes the region feature.

### Steps to reproduce

Copy the following code inside a script and try to fold the region TEST (comments are only there to explain the behavior):

```
#region TEST
# This region should be folded up to the EOF comment
func test() -> void:
	# Dummy content
	var testing : String = "" 
	# To trigger the region's end, the string must be the first thing on the line, with or without tabs in front
	# Single quoted or literal strings does the same effect
	testing += """
#endregion
"""
	# Some more content which will not be folded with the region!
	var new_var : int = 3
# The real end of the region, when folding TEST we should not see any of the test() method content
#endregion
# EOF comment
```
The result is a partially folded region (see screenshots below).

Unfolded region:
![Capture d’écran du 2024-03-03 16-29-57](https://github.com/godotengine/godot/assets/102065761/44a01b35-8a3a-47f9-859f-5eae1bc81c02)

Actual folded region:
![Capture d’écran du 2024-03-03 16-30-10](https://github.com/godotengine/godot/assets/102065761/df699329-070d-408d-a82d-85b0681ef5b0)

Expected result:
![Capture d’écran du 2024-03-03 16-42-08](https://github.com/godotengine/godot/assets/102065761/4b6dface-aa3c-4c2c-a127-4fbb784791ab)

### Minimal reproduction project (MRP)

Not necessary.

**Comment by TheRealSlander** [comment]
I tested more in depth and if the string is for example "#region REGION_NAME", the corresponding region is created as well.
In short: if the string contains "#region" or "#endregion" it is interpreted as a real region keyword, where it should not be treated at all. Hope this helps.

**Comment by dalexeev** [comment]
Looks like the editor doesn't take into account language syntax, only comment delimiters. CC @jmb462 @Paulb23

**Comment by RafaelRain18** [comment]
Hi, I'm new here, can I be assigned to this issue? Or is it already assigned to someone else?

**Comment by dalexeev** [comment]
@RafaelRain18 Feel free to start working on it. We usually prefer not to assign issues. Your comment is enough to inform other contributors of your intention. If you need help, you can ask in the [Godot Contributors Chat](https://chat.godotengine.org/). Thanks!
