### ISSUE TITLE
Path3D gizmo: Missing Bezier curve handles for the points

### ISSUE THREAD

**Issue by tailsc** [godotengine/godot#89138]
### Tested versions

4.3 dev 4 when i make a path3d the points dont have the curve points to them so cant give them a curve worked in 4.2.1 

### System information

Godot v4.3.dev4 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

when i make a path3d and make the points they dont have the point in them to make them curve it used to have it for 4.2.1

### Steps to reproduce

add path3d add points no curve thing

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Sounds related to https://github.com/godotengine/godot/pull/87901#issuecomment-1962333611, CC @pohy.

**Comment by BasilYes** [comment]
Have same issue on 4.3.dev4, curves points appear only if In or Out points location != (0, 0, 0) so need to change it's manually before you can edit it in inspector + tilt gizmo have strange behavior  (see video)

https://github.com/godotengine/godot/assets/36816595/e913b7cd-7bd0-4226-a4b7-8f84a2f403ce

**Comment by GreenCrowDev** [comment]
I'm taking a look at this right now. I'll open a draft pr as soon as I have changes.

**Comment by tailsc** [comment]
think it was fixed in 4.3 dev 5 maybe close

**Comment by GreenCrowDev** [comment]
Not fixed, still there on the master branch.

**Comment by tailsc** [comment]
oh yeah rotation was fixed for dev 5 but not curve your right
![Skärmbild 2024-03-24 092834](https://github.com/godotengine/godot/assets/102230735/6ae5236f-4000-4993-b0de-88471fae0df6)

**Comment by Calinou** [comment]
I can confirm this on 4.3.dev https://github.com/godotengine/godot/commit/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89.
