### ISSUE TITLE
Empty folders disapear when closing and reopening project 4.3 dev 4

### ISSUE THREAD

**Issue by tailsc** [godotengine/godot#89139]
### Tested versions

tested with 4.3 dev 4 

### System information

Godot v4.3.dev4 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

if i made folders before started working on project and planed to put stuff in them in future when i came back they were gone 

### Steps to reproduce

make empty new folders and close and reopen godot and they will be gone tryed to reproduce it now before issue but it didnt happend this time 

### Minimal reproduction project (MRP)

N/A

**Comment by brcontainer** [comment]
I was unable to reproduce the problem on v4.3.dev4.official [df78c0636].

Maybe it's something caused by other software, like GIT.
