### ISSUE TITLE
InputEvent's is_action{,_pressed,_released} don't work

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8914]
**Godot version: 3.0 master**

**Issue description:**
`Input.is_action_pressed("action")` is not working :)

**Comment by TristanWLB** [comment]
Indeed, the only thing I have found to work is to use the `_input( event )` function and poll input using `event.is_action()`; `event.is_action_pressed()` and `event.is_action_released()` still do not work, however.

**Comment by alexwbc** [comment]
this issue (on Lubuntu 17.04 64bit) emerged form in the commit 3c175115ebf54bcf5f53ab7a2d4926c6773665db and afterwards.

in the previous commits ( f2a335d0c1da0c2d7c5b7687c91db348ae49eb57 ), the .is_action_[pressed/released]() works fine.

**Comment by bojidar-bg** [comment]
@alexwbc You must be wrong somehow. That commit has nothing to do with Input or InputEvent classes.
