### ISSUE TITLE
tileMap ERROR: No cached rect

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#89144]
### Tested versions

Godot_v4.3-dev4

### System information

windows 10 vulkan foward+

### Issue description

no cache rect for tile coords:
doesnt crash but error will pile up
![bug](https://github.com/godotengine/godot/assets/77213594/7c79a787-1c7f-47d1-8f6f-1bbdc1d79ee1)

### Steps to reproduce

- in scene lvl_b1
- select tileMap node
- deselect ( highlight selected TileMap Layer )
- frist tileMap sheet ex: ( autoTileTest.png )
- select the frist 3 by 3 square group
- paint / rotate(X) / paint / rotate(X) / paint.... 3x
- press select tool icon select all painted tiles
- ctrl + C / then leter D
- paint / rotate(X) / paint rotate(X) / paint... 3x
- press select tool icon select all painted tiles / delete

### Minimal reproduction project (MRP)

[tileCrash3.zip](https://github.com/godotengine/godot/files/14482329/tileCrash3.zip)

**Comment by AThousandShips** [comment]
You already made a report for this issue, please update it instead of making a duplicate issue

**Comment by AThousandShips** [comment]
That doesn't matter, don't make a new issue for each version please
