### ISSUE TITLE
Visual shader warning "Clamp is missing a category" when opening a project and/or adding a node in visual shader editor.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#89152]
### Tested versions

4.3 [01dc5c5b58e93cb893c9c427419eb7838e73ec7d]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

When I add Clamp (perhaps some other nodes I haven't tested too) I get this warning, it also always appears when I open the project.

![image](https://github.com/godotengine/godot/assets/33526847/846eb0ae-c39c-4cd8-808c-b359645c55ec)

### Steps to reproduce

Add visual shader and add a Clamp method or just open the MRP.

### Minimal reproduction project (MRP)

[VisualShaderMRP.zip](https://github.com/godotengine/godot/files/14485865/VisualShaderMRP.zip)

**Comment by AThousandShips** [comment]
Should also affect:
* `VisualShaderNodeDeterminant`
* `VisualShaderNodeDotProduct`

It's a trivial fix I'll write one up
