### ISSUE TITLE
High memory usage on web exports in Safari

### ISSUE THREAD

**Issue by KurzweilTV** [godotengine/godot#89169]
### Tested versions

- Reproducible in: 4.2.1 and 4.3 dev 4

### System information

macOS Sonoma 14.3.1 (23D60)

### Issue description

When exporting for web, memory usage goes up rapidly until safari kills the game for using too much memory. I've seen this. happen in several of my projects as well as several on itch.io

This is happening for me on Safari Version 17.3.1 (19617.2.4.11.12) on a MacMini Apple M2 Pro

### Steps to reproduce

I'm not 100% certain yet. It doesn't happen with an empty project, but I've seen it happen with several other small projects. I wasn't able to reproduce in Chrome on the same Mac. Nor in chrome or edge on a Windows machine, with the same project.

### Minimal reproduction project (MRP)

https://github.com/KurzweilTV/MiniJam153

**Comment by KurzweilTV** [comment]
![Screenshot 2024-03-05 at 07 30 13](https://github.com/godotengine/godot/assets/3179534/f8ec83f2-3c71-456f-882a-af3958a6909e)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/67949.
