### ISSUE TITLE
Godot 4.3.dev4 bug - animation on AnimatedSprite2D not working if frame is present in RESET animation

### ISSUE THREAD

**Issue by ForestGameDev** [godotengine/godot#89163]
### Tested versions

- Reproducible in Godot 4.3.dev4.official
- Not reproducible in Godot 4.3.dev3.official

### System information

Godot v4.3.dev4 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 850M (NVIDIA; 31.0.15.3168) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

AnimatedSprite2D animations not playing based on AnimationPlayer setup.

Consider this setup:
1. An AnimatedSprite2D called X with a couple of animations that loop.
2. An AnimationPlayer with animations that only change the "animation" property of X.
3. An AnimationTree that changes the animations based on a variable that changes based on user input.

I found that, if the AnimationPlayer's "RESET" animation contains the "frame" property of X, then the animations don't play. If you remove the "frame" property then they run fine. Please see the MRP attached.

This used to work in Godot 4.2 and 4.3.dev3, so this is a regression in behavior in 4.3.dev4.

### Steps to reproduce

Described above.

### Minimal reproduction project (MRP)

[BugAnimationPlayer.zip](https://github.com/godotengine/godot/files/14488594/BugAnimationPlayer.zip)

I included 2 scenes, one where the animations don't play, and one where they play fine. The only difference is one has the "frame" property in the RESET animation, and the other does not.

**Comment by ForestGameDev** [comment]
I found that disabling "Deterministic" in the Animation**Tree** seems to be a workaround. Not sure what side effects it may have.

**Comment by Calinou** [comment]
cc @TokageItLab

**Comment by TokageItLab** [comment]
Is it the AnimationPlayer that you want the Animation to eventually play or the AnimationTree?

In 4.3, there are several possible combinations:

- `AnimationPlayer` or `AniamtionTree`
- Deterministic: `true` or `false`
- CallbackModeDiscrete: `Dominant` or `Recessive` or `ForceContinuous`

Probably the only thing that was changed in 4.3 is the default CallbackModeDiscrete of AnimationPlayer, so it is assumed that setting it to `ForceContinuous` will solve the problem. Please check it.

**Comment by ForestGameDev** [comment]
Hi, I tested changing CallbackModeDiscrete in the AnimationTree to `Dominant`, but that didn't work. Disabling `Deterministic` in the AnimationTree does work.

Based on your comment it seems some changes to help blending animations caused issues for cases like mine where I use an AnimationTree to switch between AnimatedSprite2D animations. I know there's a lot of effort right now in 3D stuff, but I do believe this is a valid use case for 2D games. Please check the example project I uploaded, maybe it's not a valid use case and you could tell me what's the right way to have an AnimationTree to switch between AnimatedSprite2D animations. I still think this should be considered a regression.

**Comment by TokageItLab** [comment]
I don't know what state your current project is in, but the case reported as an issue is definitely working correctly with the configuration I described, so this is a documentation issue, not a bug.

https://github.com/godotengine/godot/assets/61938263/9a6e898c-6c9e-4d1d-aa82-1bade23f66e4

If you have additional information, send a new MRP or test case.

**Comment by TokageItLab** [comment]
@ForestGameDev It seems that there is no animation in the MPR that contains the margin movement, even if it is scene_currect; you need to check that the MRP in the Description is correct and send a new MRP.

**Comment by TokageItLab** [comment]
Ah, I understand that AnimatedSprite will not play unless the scene is run. Yep, something may indeed be odd, so I'll look into it.
