### ISSUE TITLE
move_and_collide(Vector2.LEFT) moves character to the right.

### ISSUE THREAD

**Issue by ca3gamedev** [godotengine/godot#89162]
### Tested versions

4.2

### System information

Xubuntu.

### Issue description

move_and_collide using the Vector2.LEFT direction moves my character to the right.
![Captura de pantalla_2024-03-04_18-52-34](https://github.com/godotengine/godot/assets/115381195/070cbd36-ff31-41a8-96c1-621ed67cb6de)

### Steps to reproduce

Check my example, open the player root script.

### Minimal reproduction project (MRP)

[Suburbian Champions 4.zip](https://github.com/godotengine/godot/files/14488326/Suburbian.Champions.4.zip)

**Comment by ca3gamedev** [comment]
I remade from scratch my player, and It works fine now.
I'll leave the bug report, to see if it's a real godot bug.

**Comment by akien-mga** [comment]
This is very unlikely to be an engine bug, thousands of users are using `move_and_slide` without issue.

Please note that this platform is for clearly identified bug report, with a minimal reproduction project. We can't really use it to help users debug issues in their projects, there are other platforms more suitable for this listed on https://godotengine.org/community/
