### ISSUE TITLE
Theming LineItem right_icon has no effect

### ISSUE THREAD

**Issue by graydoubt** [godotengine/godot#89161]
### Tested versions

- Reproducible in Godot Engine v4.0.stable.official.92bee43ad
- Reproducible in Godot Engine v4.1.2.stable.official.399c9dc39
- Reproducible in Godot Engine v4.2.1.stable.official.b09f793f5

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

Using a theme to set a `LineItem.right_icon` has no effect, whereas setting a `Button.icon` works as expected.

I've created a `toolbar.tscn` with a `Button` and a `LineEdit`.

![image](https://github.com/godotengine/godot/assets/36222624/30543d9f-c93f-426b-91b4-45cfb26202e3)

The `PlayButton` node has its `theme_type_variation` set to `Toolbar_PlayButton`:

![image](https://github.com/godotengine/godot/assets/36222624/013de9da-4a78-4c95-a87e-061abc173efc)

The `SearchBox` node has its `theme_type_variation` set to `Toolbar_SearchBox`:

![image](https://github.com/godotengine/godot/assets/36222624/d0f2c01d-3752-4d8e-9f1a-fdf10491abbf)

I've created two themes; one with outlined icons, and one with solid icons.
Both themes define the `Toolbar_PlayButton` and `Toolbar_SearchBox` types.
This is the `theme_outline.tres`:

![image](https://github.com/godotengine/godot/assets/36222624/84d3cf1c-a43d-4a07-8b1a-88c49ce0df66)

The `main.tscn` has two instances of the toolbar; the left is configured to use the outline theme, and the right is configured to use the solid theme.

![image](https://github.com/godotengine/godot/assets/36222624/a07474ec-1526-4fc6-94db-58e6960ba1d8)

The play icon shows correctly, but the search icon does not:

![image](https://github.com/godotengine/godot/assets/36222624/55b1371d-e585-46a5-8d41-045ff3c73f0d)

For comparison, I'd expect the `LineItem`'s `right_icon` to show up as in this example (which was achieved by enabling edit children and setting the icons directly):

![image](https://github.com/godotengine/godot/assets/36222624/878f69f4-6646-481a-9747-c703400fc6c4)

### Steps to reproduce

The minimal reproduction project contains everything and needs no extra steps to see the issue.

### Minimal reproduction project (MRP)

The [Godot LineEdit theming bug](https://github.com/graydoubt/godot-line-edit-theming-bug) repository.

**Comment by graydoubt** [comment]
> `right_icon` is a regular property of LineEdit, not a theme property. So this is expected behavior.

Is this not also the case for a Button's icon property?

**Comment by KoBeWi** [comment]
There was a bug that caused some theme properties to not appear as overrides. It's fixed in Godot 4.3.
![image](https://github.com/godotengine/godot/assets/2223172/e6bdc95e-16e3-46a8-acfe-271952935923)

**Comment by graydoubt** [comment]
Bummer. Thanks for the help, @KoBeWi. I'll file it as a proposal.
