### ISSUE TITLE
Selection windows are self-shrinking

### ISSUE THREAD

**Issue by TamtamHero** [godotengine/godot#89176]
### Tested versions

Tested 4.2 and 4.3-dev4, both have the bug

### System information

KDE Neon, Plasma 6, Wayland

### Issue description

Each time I open a new selection window, it gradually reduces in height. If I try to increase its height again, it reduces gradually again. See this gif for a demo:
https://s4.ezgif.com/tmp/ezgif-4-4c83696946.gif
I suspect this is a Wayland related bug.

### Steps to reproduce

Create a new scene, select "Other Node", watch the selection window shrink by itself.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/75515.
