### ISSUE TITLE
"zero in" node position button/option

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#8917]
I don't know if I'm the only one who would find this useful, but since it seems to such a common task to "zero in" a node's position relative to its parent, especially when using a lot of drag and drop, wouldn't it be nice to have a button or right-click menu entry to quickly set a node's position to zero (i.e. relative to its parent) instead of having to change 2 or 3 values to do the same thing?

**Comment by novemberist** [comment]
Extending on that idea (for the distant future) one could maybe even draw inspiration from "align and distribute" tools many graphics programs like inkscape offer to help making exact arrangements of multiple nodes without having to using code. 
![align_distribute](https://cloud.githubusercontent.com/assets/7927471/26487923/c1cbbb4e-4201-11e7-99a0-d25413759137.png)

**Comment by Yazir** [comment]
I'm surprised that it's not there. There also should be "Fit to parent" option, that would resize the node.

**Comment by novemberist** [comment]
There's actually an "expand to parent" (i guess that's supposed to do what you mean) option under the edit tab in the viewport, though it doesn't seem to have any effect.

**Comment by vnen** [comment]
"Expand to parent" only works for Controls AFAIK.

**Comment by mhilbrunner** [comment]
Even better would be the option to set all values of a collection (array?) at once. Add an "equals" sign button to the left of the input popup that lets you enter all values at once, so you can quickly set all translation/transform values to 0 or 1 or 10 or whatever. More flexible this way.

**Comment by akien-mga** [comment]
This is now fixed in 3.1 as you have revert buttons for all properties with non-default values, so you can reset the translation or the whole transform to their null state.
