### ISSUE TITLE
what is DELTA supposed to be in particle shader?

### ISSUE THREAD

**Issue by Mohammad9760** [godotengine/godot#89187]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Linux Ubuntu 21 - Godot 4.2.1 stable

### Issue description

so I'm using a particle shader to rotate a mesh that is emitted in a GPUParticles3D node.
my shader looks like this:

```
shader_type particles;

#include "res://transform_matrix_util.gdshaderinc"

uniform vec3 rot;
uniform vec3 pos = vec3(0.0);
uniform vec3 size;

void start() {
}


void process() {

	TRANSFORM = translate(TRANSFORM, pos);
	TRANSFORM = scale(TRANSFORM, size);
	TRANSFORM = add_rotation(TRANSFORM, rot * DELTA);
}
```

and, I was expecting that multiplying the rotation angle with DELTA would make it consistent with different FPS in the GPUParticle3D, but it doesn't.

https://github.com/godotengine/godot/assets/79392031/2bb923b8-53c2-4be8-a6d6-6a5f3f299a85

in the video you can see that the GPUParticle3D' Fixed FPS is set to 120 in the beginning and then I reset it back to 30, and the speed changes.

this is probably me not having a good understanding of things, but anyway the expected result for me was to have consistent speed by multiplying by DELTA.

also if you need the gdshaderinc that contains the rotation function I'm using just let me know, I didn't add it here because it was too long.

### Steps to reproduce

try moving or rotating a mesh using a particle shader and multiply the speed with DELTA.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is not the place to ask general support questions, please ask in the [forums](https://forum.godotengine.org/), this is for bug reports

**Comment by Mohammad9760** [comment]
oops, right... my bad.
