### ISSUE TITLE
"Invalid call. Nonexistent function 'rpc' in base 'Callable'." when trying to pause the scene tree with an rpc call

### ISSUE THREAD

**Issue by TheSkyOne** [godotengine/godot#89195]
### Tested versions

Reproducible in 4.2.stable

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

I have seen a few other issues about callables and RPCs, but wasnt sure if this problem is covered by them. apologies if this is a duplicate.
I was trying to sync the scene tree's paused state with an rpc call, so I wrote this
`get_tree().set_pause.rpc()`
which throws the error in the title.
got the same error when doing `timer.start.rpc()` (where `timer` is a reference to a timer node in the tree)

### Steps to reproduce

simply make a new scene with a base node, add a script and in the `_ready` function of the script add the line of code

### Minimal reproduction project (MRP)

[RPC_bug_MRP.zip](https://github.com/godotengine/godot/files/14500155/RPC_bug_MRP.zip)

**Comment by Deozaan** [comment]
You can't just add `.rpc()` to any function to make an rpc call. The function has to be an rpc already with the `@rpc` decorator.

**Comment by AThousandShips** [comment]
Indeed, see the [`rpc`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc) method documentation:
> Methods are not exposed to RPCs by default.

This is documented, and don't think any additional details are needed

**Comment by TheSkyOne** [comment]
I see. how would I add the `@rpc` decorator to a node's predefined method like `get_tree().set_paused()` or `timer.start()`?
Or do I need to wrap that in my own method and add `@rpc` to that?
Other than that I guess this is ok to close?

**Comment by AThousandShips** [comment]
You should create a new method to do your network operations yes, you can't make built-in methods `rpc`

Closing :) Thank you for your report
