### ISSUE TITLE
C++ A deep copy (COW) of TypedArray is sometimes incorrectly made

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#89191]
### Tested versions

Reproducible on 7d2ca2d8ac49cde9767e00b70f9eaf1920eb266d and also on 4.2-stable 46dc277917a93cbf601bbcf0d27d00f6feeec0d5

### System information

Godot v4.3.dev (7d2ca2d8a) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When casting from `TypedArray` to `Array` and back again, a deep copy (COW) will be performed. This seems to also affect nested `Array` occurrences, thus making it impossible(?) to extract a reference to a `TypedArray` as a `TypedArray` from an `Array` or `TypedArray`.

### Steps to reproduce

A simple example is the following. Even though `untypedArray` in this example knows that it is, internally, a typed array, it will still perform a COW deep copy.

```C++
TypedArray<int> typedArray;
typedArray.push_back(1);

Array untypedArray = typedArray;
TypedArray<int> typedArrayCopy = untypedArray; // COW

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

WARN_PRINT(typedArray[0]); // Prints 2
WARN_PRINT(untypedArray[0]); // Prints 2
WARN_PRINT(typedArrayCopy[0]); // Prints 3
```

This behaviour arguably becomes more problematic when dealing with nested `Array` scenarios:

```C++
TypedArray<int> typedArray;
typedArray.push_back(1);

Array parentArray;
parentArray.push_back(typedArray);

Array untypedArray = parentArray[0];
TypedArray<int> typedArrayCopy = parentArray[0];

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

WARN_PRINT(typedArray[0]); // Prints 2
WARN_PRINT(untypedArray[0]); // Prints 2
WARN_PRINT(typedArrayCopy[0]); // Prints 3
```

This second example demonstrates that it is difficult (and maybe impossible?) to extract a `TypedArray` from an `Array` (or `TypedArray`) and put it back into a `TypedArray` container without doing a COW that may not be desirable.

### GDScript
This behaviour does **not** affect GDScript. In GDScript, I can do the following and a COW deep copy will never occur:
```GDScript
var typedArray: Array[int];
typedArray.push_back(1);

var untypedArray: Array = typedArray;
var typedArrayCopy: Array[int] = untypedArray;

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

print(typedArray[0]); # Prints 3
print(untypedArray[0]); # Prints 3
print(typedArrayCopy[0]); # Prints 3
```

```GDScript
var typedArray: Array[int];
typedArray.push_back(1);

var parentArray: Array;
parentArray.push_back(typedArray);

var untypedArray: Array = parentArray[0];
var typedArrayCopy: Array[int] = parentArray[0];

untypedArray[0] = 2;
typedArrayCopy[0] = 3;

print(typedArray[0]); # Prints 3
print(untypedArray[0]); # Prints 3
print(typedArrayCopy[0]); # Prints 3
```

### Minimal reproduction project (MRP)

(See above code snippets. Put them in something that you know will be called in the engine like `register_core_singletons()` of `register_core_types.cpp`)

**Comment by AThousandShips** [comment]
I'm not sure this is a bug, you're operating on extended types and casting them to their parent types, that's not type safe, you're losing typing information, that's why it works with GDScript because it doesn't operate on them in the same way, I'd say

What happens if you do:
```cpp
TypedArray<int> typedArrayCopy;
typedArrayCopy = untypedArray;
```

**Comment by allenwp** [comment]
> What happens if you do:
> 
> ```c++
> TypedArray<int> typedArrayCopy;
> typedArrayCopy = untypedArray;
> ```

Using the code you provided instead does **not** perform a deep copy!

**Comment by AThousandShips** [comment]
Then I'll write some fixes for this, it should work, will see!
