### ISSUE TITLE
Requesting a 3D Raycasting Example

### ISSUE THREAD

**Issue by M4N1AC** [godotengine/godot#892]
Please make an example showing how to use 3D raycasting, and camera.project_ray_<normal,origin>

**Comment by akien-mga** [comment]
What's the status here? Is there an official demo that shows how to handle 3D raycasting?

**Comment by djrm** [comment]
Maybe this should be moved to the demos repo.

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/2
