### ISSUE TITLE
Questions about scons scripts

### ISSUE THREAD

**Issue by November20** [godotengine/godot#89208]
### Tested versions

godot-3.0

### System information

linux

### Issue description

```python
#!/usr/bin/env python
# godot-3.0/thirdparty/zstd/SCsub
Import('env')

thirdparty_zstd_dir = "#thirdparty/zstd/"
thirdparty_zstd_sources = [
	"common/entropy_common.c",
	"common/error_private.c",
	"common/fse_decompress.c",
	"common/pool.c",
	"common/threading.c",
	"common/xxhash.c",
	"common/zstd_common.c",
	"compress/fse_compress.c",
	"compress/huf_compress.c",
	"compress/zstd_compress.c",
	"compress/zstd_double_fast.c",
	"compress/zstd_fast.c",
	"compress/zstd_lazy.c",
	"compress/zstd_ldm.c",
	"compress/zstdmt_compress.c",
	"compress/zstd_opt.c",
	"decompress/huf_decompress.c",
	"decompress/zstd_decompress.c",
]
thirdparty_zstd_sources = [thirdparty_zstd_dir + file for file in thirdparty_zstd_sources]
env.add_source_files(env.core_sources, thirdparty_zstd_sources)
env.Append(CPPPATH=["#thirdparty/zstd", "#thirdparty/zstd/common"])
env.Append(CCFLAGS="-DZSTD_STATIC_LINKING_ONLY")
```
My question is:
```python
env.add_source_files(env.core_sources, thirdparty_zstd_sources)
```
it calls:
```python
# godot-3.0/methods.py

def add_source_files(self, sources, filetype, lib_env=None, shared=False):
    import glob
    import string
    # if not lib_objects:
    if not lib_env:
        lib_env = self
    if type(filetype) == type(""):

        dir = self.Dir('.').abspath
        list = glob.glob(dir + "/" + filetype)
        for f in list:
            sources.append(self.Object(f))
    else:
        for f in filetype:
            sources.append(self.Object(f))
```
The problem is these two compilation options:
```python
env.Append(CPPPATH=["#thirdparty/zstd", "#thirdparty/zstd/common"])
env.Append(CCFLAGS="-DZSTD_STATIC_LINKING_ONLY")
```
These two compile options are executed perfectly even after self.Object(f),self.Object(f) does not compile immediately when executed, but only saves the address of the file. What signal can be used to start compiling?I don't know when to start compiling. I don't know which statement starts compiling immediately? Is this automatic?

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
This platform is for bug reports on currently supported versions of Godot.

It's not for general questions about how to use Godot or its buildsystem, and we no longer support Godot 3.0 (released in 2018) since many years.

**Comment by November20** [comment]
I don't know where to ask... And I think it's easier to get started from the old version.

**Comment by akien-mga** [comment]
Easier to get started doing what?

**Comment by November20** [comment]
Your suggestion makes sense. I'm starting over from the latest version.

**Comment by November20** [comment]
https://godotengine.org/community/
The social tools in here are hard to use in my place.It would be nice if there were people learning the source code to communicate with.

**Comment by November20** [comment]
**Only after SCons has finished reading and parsing the SConstruct script does it start performing the actual compilation and build steps.**
