### ISSUE TITLE
"fluidsynth" fails to load a soundfont

### ISSUE THREAD

**Issue by jlx-286** [godotengine/godot#89213]
### Tested versions

- Reproducible in: v3.5.3.stable.mono.official [6c814135b] (Windows 10)
- Not reproducible in: v3.5.3.stable.mono.official [6c814135b] (Ubuntu 20.04)~~,[.NET 8 (Windows 10)](https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-8.0.100-windows-x64-installer),[.NET Core 3.0 (Windows 10)](https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-3.0.103-windows-x64-installer),Unity 2018.4.13f1~~

### System information

Windows 10,Ubuntu 20.04 - Godot v3.5.3.stable.mono

### Issue description

part of the output in "cmd.exe" (but "audioplugin-fluidsynth-3.dll" works normally)
```
fluidsynth: error: Invalid chunk id in level 0 parse
fluidsynth: error: Failed to load SoundFont "TimGM6mb.sf2"
```

### Steps to reproduce

- enable "fluidsynth command" if not enabled
    + [download FluidSynth](https://github.com/FluidSynth/fluidsynth/releases) and "unzip"
    + add the directory of "libfluidsynth-3.dll" to "`%path%`"
    + reboot
- "run libfluidsynth"
    + run "Godot_v3.5.3-stable_mono_win64.exe" in "cmd.exe" or open "Godot_v3.5.3-stable_mono_win64_console.cmd"
    + "`private const string PluginName = "libfluidsynth-3";`" instead in the "166th" row of the script "<https://github.com/jlx-286/lunatic-rave-3/blob/master/LR3_default(480p)/Scripts/FluidManager.cs> or <https://github.com/jlx-286/lunatic-rave-3/blob/master/LR3_WMIX(720p)/Assets/Scripts/FluidManager.cs>"
    + play the (Godot) project
    + part of the output in "cmd.exe" (`fluid_synth_sfload` returns -1)
    ```
    fluidsynth: error: Invalid chunk id in level 0 parse
    fluidsynth: error: Failed to load SoundFont "TimGM6mb.sf2"
    ```

### Minimal reproduction project (MRP)

<https://github.com/jlx-286/lunatic-rave-3/tree/master/LR3_default(480p)>

**Comment by AThousandShips** [comment]
This sounds like something to report to the plugin, this is for the engine not third party content
