### ISSUE TITLE
3D axes flicker in the distant negative direction 

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#89215]
### Tested versions

v4.3.dev4.official [df78c0636]
doesn't happen in v4.2.1.stable.official [b09f793f5]

### System information

linux, rtx 3070, driver 525.147.05

### Issue description

Axes flicker:

https://github.com/godotengine/godot/assets/71937306/351ddb8c-d4d4-4cae-9489-a563abce1aa9

- it also happens with the y axis (not shown on video).
- if you stop the camera movement while an axis is invisible, it stays that way.

### Steps to reproduce

zoom out a bit and move the view

### Minimal reproduction project (MRP)

any

**Comment by Broken1334** [comment]
Looks like the flickering happens only on negative axes.
