### ISSUE TITLE
Proposal: Add help menu

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8921]
Proposal to add a help menu to Godot. The built-in help is easy to access but many users never find out the rest of the useful websites we have online. This would basically be a way to provide easy shortcuts to said websites.

Right now the structure is as follows:

- class browser (just because it would be strange not to have the built-in stuff too ;))
- online docs : link to docs.godotengine.org
- Q&A : link to q&a site
- Issue Tracker : link to github
- Community : link to https://godotengine.org/community

Optionally, community could be a submenu with direct links to facebook, reddit, twitter, etc...

![help](https://cloud.githubusercontent.com/assets/1642015/26492544/96e47d52-420c-11e7-8d9c-46d5cfca5cb8.gif)

WDYT?

**Comment by reduz** [comment]
I like the idea!

**Comment by nunodonato** [comment]
@reduz do you think with this we would still need to have the help button in the toolbars?

**Comment by reduz** [comment]
I guess probably not

**Comment by nunodonato** [comment]
@reduz the only "problem" to this, is that the help seems to be inside the Script mode. So if the user presses one of these menu options, should it switch to script automatically?

**Comment by Keetz** [comment]
I think it would make sense if the "About" from Editor Settings is moved to this Menu too, it is pretty common for the "About" to be under Help

**Comment by nunodonato** [comment]
@Keetz yes, Akien said the same. I already moved it :)

**Comment by Zireael07** [comment]
Can the help browser entry keep the floatation ring icon that it had? The icon was a great way to spot the built-in help ...

**Comment by nunodonato** [comment]
I dont know.. having just one icon there feels a bit off
![screenshot from 2017-05-26 14-40-34](https://cloud.githubusercontent.com/assets/1642015/26496947/79df54e2-4221-11e7-91dc-0f88be36a8d2.png)

**Comment by akien-mga** [comment]
As I mentioned on IRC, I believe all links to URLs should have an icon marking them as links too, so that you know you're leaving Godot.

**Comment by eon-s** [comment]
I like the class reference on the script panel.

**Comment by nunodonato** [comment]
latest
![screenshot from 2017-05-26 15-07-22](https://cloud.githubusercontent.com/assets/1642015/26497894/0bc11e88-4225-11e7-912c-834780908b47.png)

**Comment by nunodonato** [comment]
ok, final changes, added icons as requested by @akien-mga 
I also changed the "Tutorials" button in the script editor toolbar to be consistent with the help menu. (these become a bit redundant but given the frequency people use them and ease of access when you are typing code, I think they should stay)

Any further requests or should we call it done? :)

![screenshot from 2017-05-26 15-23-27](https://cloud.githubusercontent.com/assets/1642015/26498591/70cbc7e0-4227-11e7-94f3-e7a9b46d1ca9.png)
![screenshot from 2017-05-26 15-23-31](https://cloud.githubusercontent.com/assets/1642015/26498595/73923d7e-4227-11e7-8a35-151213341794.png)

**Comment by n-pigeon** [comment]
Instead `Issue Tracker` call it `Report Bug` :)

**Comment by reduz** [comment]
I think the icons are kinda unnecesary, we don't use them much for these
menus anyway

**Comment by nunodonato** [comment]
@n-pigeon I thought about it, but I dont know if it would be good.. perhaps too easy and the issue tracker would be filled with crappy non-bug reports :) I'm already linking to the issues section instead of the main project page..

@reduz right... @akien-mga suggested the icons for the external links, to hint that something external would be opened. Makes sense, imho. But then the menu looks "unbalanced" if half as icons and half hasn't... :/

**Comment by akien-mga** [comment]
> Instead Issue Tracker call it Report Bug :)

No, Issue Tracker is clearer. We want people to go to check if the *issue* they experience has been *tracked* already. Not to create 5000 duplicate bug reports :°)

**Comment by nunodonato** [comment]
@akien-mga another option to remove icons but to keep a hint that its online, put all those 4 items in an "Online" submenu. I dont like it so much, but...

**Comment by akien-mga** [comment]
I guess let's just go hintless, it's not that bad :)
