### ISSUE TITLE
Custom drawn polygons on the same texture always start with VERTEX_ID of 0 in vertex shader

### ISSUE THREAD

**Issue by Strikefinger** [godotengine/godot#89223]
### Tested versions

- Reproducible in: 4.3.dev4, 4.2.1

### System information

GPU: AMD Radeon RX 5700 XT, Driver Version 23.30.13.01-231128a-398226C-AMD-Software-Adrenalin-Edition

## preface
I'm not sure whether this is just my inexperience with shaders talking.

## the (maybe) bug
Custom polygons on a texture drawn with `CanvasItem.draw_polygon(...)` have their `VERTEX_ID` in the vertex shader start at 0.

What I did was draw triangles on a `Texture2D` and position the vertices in a tiled square pattern. I expected an output something like this:
![expected_output](https://github.com/godotengine/godot/assets/26843180/9660db67-36fa-422e-9b66-3a429a9cbc05)
(the blank at the beginning is where I presume that the four vertices of the texture itself go)
but the output was just all triangles stacked in the upper left corner.

### Steps to reproduce

Put a script on a CanvasItem Node (I used a TextureRect2D):
```
@tool
extends CanvasItem

func _draw() -> void:
  # values of triangle vertices do not matter
  const triangles := [
    [Vector2(10, 10), Vector2(50, 100), Vector2(20, 60)],
    [Vector2(100, 200), Vector2(200, 100), Vector2(200, 200)],
    [Vector2(300, 30), Vector2(300, 100), Vector2(400, 70)],
    [Vector2(350, 30), Vector2(330, 100), Vector2(450, 70)],
  ]
  const uvs: PackedVector2Array = [Vector2(0, 0), Vector2(0, 1), Vector2(1, 0.5)]
  const color := Color(0, 0.5, 0)
  const colors: PackedColorArray = [color, color, color]
  for triangle_points in triangles:
    draw_polygon(triangle_points, colors, uvs)

```

Put a shader on the same CanvasItem Node:
```
shader_type canvas_item;

float when_eq(float x, float y) {
  return 1.0 - abs(sign(x - y));
}

void vertex() {
  // divide vertices into four groups with modulo
  float is_one = when_eq(mod(float(VERTEX_ID), 4.0), 1.0);
  float is_two = when_eq(mod(float(VERTEX_ID), 4.0), 2.0);
  float is_three = when_eq(mod(float(VERTEX_ID), 4.0), 3.0);
  float is_zero = when_eq(mod(float(VERTEX_ID), 4.0), 0.0);
  // position vertices in squares
  VERTEX = (
    is_one * vec2(0.0, 0.0)
    + is_two * vec2(0.0, 100.0)
    + is_three * vec2(100.0, 100.0)
    + is_zero * vec2(100.0, 0.0)
  )
  // move squares to the side ...
    + vec2(200.0, 0.0)
  // ... for every new modulo rollover
    * (float(VERTEX_ID) * 0.25 - fract(float(VERTEX_ID) * 0.25));
}

```

### Minimal reproduction project (MRP)

[PossibleShaderBug.zip](https://github.com/godotengine/godot/files/14514016/PossibleShaderBug.zip)

**Comment by clayjohn** [comment]
This isn't a bug. VERTEX_ID is the ID of the vertex within the draw call. GPUs don't keep track of vertex information across draw calls so what you are trying to do won't work. 

You have a few options:
1. Draw your polygon where you want it instead of using the vertex shader to move it. I.e. use different vertices per polygon. 
2. Combine all your triangles into one big polygon instead of drawing multiple polygons.
