### ISSUE TITLE
No longer possible to run multiple instances via a plugin using project metadata

### ISSUE THREAD

**Issue by jjolmo** [godotengine/godot#89225]
### Tested versions

- Reproducible in 4.3 dev4

### System information

Linux Mint - Godot 4.3 dev 4 - Mobile

### Issue description

In the last version (4.3dev4) the Run Multiple Instances dialog got revamped, but it removed one option to set the amount of debug instances via code, limiting possibilities of plugins

![image](https://github.com/godotengine/godot/assets/43957544/7300d9c8-d1ab-4905-ac6d-96f2be22fb69)

We could create plugins to create different buttons to run multiples instances. This is crucial on networking.

![image](https://github.com/godotengine/godot/assets/43957544/ed624cd5-403d-403c-9444-b1c1e4abe2f1)

In the image I've set several options to run my game in both normal, client or server mode, with 1, 2 or 3 instances. When you clicked in that button it would change the option `run_debug_instances` to set the number of instances to load

```gdscript
func _button1_pressed():
	if Engine.is_editor_hint():
		EditorInterface.get_editor_settings().set_project_metadata("debug_options", "run_debug_instances", 1)
		EditorInterface.play_main_scene()

```
Now this is not possible anymore. I've checked the changed code and I'm not 100% sure but it seemed to me that the option got removed as I don't see any calling to any `debug_option` when iterating the list of running instances

The plugins that were using this option stopped working.

### Steps to reproduce

- Open the demo
- Click on the custom buttons that appear on top
![image](https://github.com/godotengine/godot/assets/43957544/41550c1c-f2e0-4dc6-97c4-aaadd395ceef)
- Check the "addons/SmartButtons/plugin.gd" code to see how I was loading multiple instances

### Minimal reproduction project (MRP)

[TestInstances.zip](https://github.com/godotengine/godot/files/14514472/TestInstances.zip)

**Comment by KoBeWi** [comment]
Project metadata are internal settings used by various editor components. They are not supposed to be accessed by users and other editor components and there is 0 guarantee about the data structure and content.

That said, the instance data is now directly fetched from the Run Instances dialog. If you want a new hack to customize it, use this code (it will work in any `@tool` script):
```GDScript
func set_enable_multiple_instances(enable: bool):
	var run_instances: Node = EditorInterface.get_base_control().find_child("*RunInstancesDialog*", true, false)
	var enable_checkbox: CheckBox = run_instances.find_child("*CheckBox*", true, false)
	enable_checkbox.button_pressed = enable

func set_instance_count(count: int):
	var run_instances: Node = EditorInterface.get_base_control().find_child("*RunInstancesDialog*", true, false)
	var amount_spinbox: SpinBox = run_instances.find_child("*SpinBox*", true, false)
	amount_spinbox.value = count

func set_instance_launch_arguments(instance_id: int, arguments: String):
	var run_instances: Node = EditorInterface.get_base_control().find_child("*RunInstancesDialog*", true, false)
	var instance_tree: Tree = run_instances.find_child("*Tree*", true, false)
	instance_tree.get_root().get_child(instance_id).set_text(1, arguments)
```
But just as before, this can stop working at any time. The only way to have a reliable solution for running multiple project instances is adding it to plugin API, which requires a proper proposal.

**Comment by jjolmo** [comment]
So I'm reporting a bug related to an unlisted functionality. Dang.
I will create a proposal. Many thanks. I don't think this is a bug so I'm closing it
