### ISSUE TITLE
Animation retargeting leads to weird looking animations

### ISSUE THREAD

**Issue by Lunatix89** [godotengine/godot#89244]
### Tested versions

- Reproducable in v4.3-dev

### System information

Godot v4.3.dev.mono (28d895f32) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.14043.7000) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

I'm currently trying to set up a 3D character with 8-directional idle/walk/jog/run animations.
For this, I bought a model from cgtrader as a placeholder model and several locomotion animation packs:

 - [Mocap Online](https://[mocaponline.com/products/mobility?variant=31536237772871](https://mocaponline.com/products/mobility?variant=31536237772871))
 - [Synty Studios](https://syntystore.com/products/animation-base-locomotion)
 - [Movement_MocapAnimPack_2.0](https://assetstore.unity.com/packages/3d/animations/movement-mocapanimpack-2-0-223764)
 - [Mixamo](https://www.mixamo.com/)

And all of them except the Mixamo one are being animated really weird, like the animations are added to their rest pose somehow:
![godot windows editor x86_64 mono_qudoBIHLk6](https://github.com/godotengine/godot/assets/3224400/5272ffad-b664-43c6-bb1e-bcfc3f09dc96)

I've also tried to go down the path of importing them into blender, combining all the animations into one file and then reexport as GLTF but that also proved to be error prone because blenders skeleton system isn't compatible with the one from FBX so most of the animations are working but I got all sort of problems with it like twisted foot / hand, crossed arms or even still the same output sometimes.

The thing is - I and many of us game devs are simply no blender / animation pros, neither do we own a license for expensive Autodesk software so we have to rely on assets from third parties which mostly target Unity and Unreal.
So while I fully understand that the Godot way is to provide already animated characters with correct rest poses to the engine, in practise that's causing a lot of trouble (and wasted money) for the developers.

From what I've seen when importing several animations and fiddling around with them, most if not all of the animation files won't have their rest pose set to "T" or "A", they just use the same pose as the first animation frame.
However, the Mixamo character has all it's bones properly set up, nothing twisted after import and also all separate animation files have their rest pose set to "T" so that's why I'm guessing that the rest pose is the root cause here.

In Unity there is this avatar which will be reused across all the imported animations which is usually set up for the base character model.
This might roughly be the same as setting up a BoneMap in Godot and reusing that one for all animation files so maybe there should be an option to use the rest pose of a reference model to calculate the relative poses when retargeting animations.

### Steps to reproduce

- Create a blank 3D project
- Grab some locomotion animations from one of the many asset creators that mostly target Unity/Unreal
- Import the base model into Godot
  - Import Mode: Scene
  - Trimming: Yes (Some animations don't start at "0" so they have little jumps in them when looping)
  - Skeleton3D: Setup bone map with humanoid profile and save to disk
- Import animation like "run forward"
  - Import Mode: Animation Library
  - Trimming: Yes
  - Skeleton3D: Use bone map from base model
  - Animation: Set loop mode to "Linear"
- Drag base model into scene
- Right click on the node and enable "Editable Children"
- Select animation player
  - Add one if none was imported - for me, the Synty Robot did not have any animations so the animation player was not added
- Click "Animation -> Manage animations"
- Click "Load Library" and select the desired animation
- Select the animation
- Press "Play"

### Minimal reproduction project (MRP)

Unfurtunately I can't provide an MVP since all of the assets are locked behind commercial licenses.
However, Mocap Online offers a free demo pack which can be downloaded for testing purposes so I've set up a small test project but excluded all the FBX files.

One can just download the demo package from Mocap Online [here](https://[mocaponline.com/collections/demo-packs/products/free-mocap-animation-pack](https://mocaponline.com/collections/demo-packs/products/free-mocap-animation-pack)). extract and copy `MCO_Demo_Pack_v2/FBX` to `MocapOnlineDemo/MCO_Demo_Pack_v2/FBX` before opening the project and it should work.

[MocapOnlineDemo.zip](https://github.com/godotengine/godot/files/14523304/MocapOnlineDemo.zip)

**Comment by Lunatix89** [comment]
This looks promising and hopefully gets into Godot soon as it would make live for developers coming from unity so much easier because we could simply reuse our animations we purchased in the asset store.

And I second this comment from @Illauriel:

> Here's how I see my specific workflow with this in my imagination:
>
> - I bought a pack of animations from some store and want to retarget them to my character that has vastly different proportions to Unreal Mannequin or whatever the animation creators used as their base model.
> - I drop the folder with animation FBX files in the project hierarchy, open the file that says T-pose, set BoneMapHumanoid, reimport open it as a scene and export a SkeletonProfile or whatever it will be called from it.
> - I open each of the other animation files' advanced import dialogues, set BoneMapHumanoid, set the exported SkeletonProfile, set a destination to export the animations, reimport.
> - Then I delete the FBX source files and forget about their existence. I don't include them in the version control, I don't bloat my project folder, and feel happy about it.

This sounds almost as in Unity - create an avatar from the base model and reuse that in all the split animations and get a nice library of animations when creating a blend tree for the model.

**Comment by lyuma** [comment]
Wow, thank you for the amazing example project. This is exactly the sort of scenario that #88824 is intended to solve.

With the latest version of the PR, I now use animations to transfer the pose from one model to another.
I tested the workflow and confirmed that it solves the issue here:

Initial version of jog animation, showing the problem:
![image](https://github.com/godotengine/godot/assets/39946030/5669f845-00ec-431f-bda8-526e3010dd79)

I now open up the good t-pose version and export the t-pose animation to a file:
![image](https://github.com/godotengine/godot/assets/39946030/b51da408-c6c9-49dc-ba3d-3b33075b297a)
This is best done using the "Export Skeleton Rest Pose" field on the skeleton, which works in case the model does not contain an explicit t-pose animation and avoids several pitfalls when referencing an AnimationLibrary or other extracted animation.

After reimporting the t-pose model, I can now use the extracted rest-pose animation in another model:
![image](https://github.com/godotengine/godot/assets/39946030/8c17e192-3e7d-473e-99fe-161bb86fd8d5)

And tada! We now have the correct jogging animation, in Godot's humanoid format:
![image](https://github.com/godotengine/godot/assets/39946030/ab82400a-34e0-4209-b7bb-e8d7e9897c5b)

I will re-post this in the PR as well to show the workflow.

**Comment by Lunatix89** [comment]
Wow, you gave me hope back to finally use all those expensive assets I purchased to get nice looking animations in Godot.
I think I'll cherry-pick this into my custom build to test it out :)
