### ISSUE TITLE
3.0 some weird things with viewports

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#8924]
**Operating system or device - Godot version:**
Only tried this on Mac so far, Godot 3.0 todays master

**Issue description:**
Trying to get my stereo camera implementation ported over. Only one of the two viewports ends up being rendered. Also after a few minutes the first viewport stops being updated.
Finally, resizing the viewport doesn't seem to either resize the render texture or how much of the render texture ends up being rendered too.

**Steps to reproduce:**
Create two viewports setup as render targets. Add separate cameras to them. Output them with sprites, oly one renders.

**Link to minimal example project:**
https://www.dropbox.com/s/bnuz655it947682/Test-viewports-3.0.zip?dl=0

**Comment by eon-s** [comment]
This may be related to the reason why the 3D editor viewports are not yet there (you only see the last one).

**Comment by BastiaanOlij** [comment]
Hope not :)

**Comment by BastiaanOlij** [comment]
I've added a simple example project. Just a cube that is rendered with two separate cameras using two viewports. One other issue is that I had to set the render mode to always. 

Funny enough, when I got to the stage where i had added the viewports and sprite objects it rendered the two viewport. When I started moving the sprites into place it stopped working. 
When I added the window resize code it really started to mess up... 

So no idea if this is a bug, if I'm missing something in what has changed in viewports or....

**Comment by BastiaanOlij** [comment]
Ok, simple problem not sure what to do with it.

Our Viewport nodes set_size nicely updates the size of the viewport (and related texture) and emits a "size_changed" signal.

In Godot 2 the viewportsprite was linked to the viewport so it connected to that signal and adjusted itself accordingly.

In Godot 3 we now have a viewporttexture that a normal 2D sprite node can use to render out the resulting texture but this is a resource and just storing a path to the viewport and it thus can't connect to the signal.

In the editor the sprite does at some point seem to react to the size change, though that may be related to it updating its display rectangle as a result to changing any other properties and obtaining the updated size as an after thought.

@reduz any suggestions on how you think this should work? possibly the easiest blunt force approach would be for the sprite to always check its size before it gets rendered. But the nice solution is for the texture to be able to signal the sprite(s) displaying it that its size has changed and for the viewport to signal the texture somehow.

**Comment by BastiaanOlij** [comment]
Note, found a dirty workaround, changing the centered property forces it to update its size information... :)

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by BastiaanOlij** [comment]
I think so, though I'm no longer using a sprite to render out the render texture in the ar/vr server now that we've enabled using the main viewport so I haven't been playing around with it. 

Also looks like the new viewport_container might be the better way to render out a viewport to screen anyway and it gets the size directly from the original viewport solving the issue.

I think the main issue here will be education, people who like me are used to using the old viewportsprite will assume they now need to use a sprite and a viewportexture instead of using the viewportcontainer.

**Comment by reduz** [comment]
This is fixed by e61d547
