### ISSUE TITLE
Tweens have stopped working properly on 4.2

### ISSUE THREAD

**Issue by TechMan06** [godotengine/godot#89243]
### Tested versions

Tested Versions:
- Godot 4.1.1 stable [bd6af8e0e] (Working)
- Godot 4.2 stable [46dc27791] (Broken)

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon R7 200 Series (Advanced Micro Devices, Inc.; 27.20.1034.6) - Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 Threads)

### Issue description

I have migrated a game of mine (it's an open source game, I may send a link if needed) to Godot 4.2 for a few tests, one of the elements in the game has an animation that is entirely composed of tweeners.
I have noticed that the tween animation somehow "resets" after it finishes (or something like that) on 4.2, meanwhile, this does not happen on 4.1.

I have provided 2 small reproduction projects, one for Godot 4.1.1 and another for 4.2, both can be opened interchangeably between versions and are identical though.

Open and run both projects on their correspondent versions and compare how the animation performs, and you'll see what exactly is happening.

### Steps to reproduce

- Open projects and run.

### Minimal reproduction project (MRP)

**Godot 4.1.1 version (working tweeners):**
[Godot_4.1_Tween.zip](https://github.com/godotengine/godot/files/14523272/Godot_4.1_Tween.zip)
**Godot 4.2 version (broken tweeners):**
[Godot_4.2_Tween_Bug.zip](https://github.com/godotengine/godot/files/14523278/Godot_4.2_Tween_Bug.zip)

**Comment by akien-mga** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
I opened the project in both versions and don't see any difference.

https://github.com/godotengine/godot/assets/2223172/41657fb7-7845-4bc5-be97-bf225bad6e8c

Left is 4.2.1, right is 4.1.1.

**Comment by TechMan06** [comment]
Well, for me this is happening instead:

https://github.com/godotengine/godot/assets/132509305/77684afd-3dd7-4c91-8973-125aa14b8335

Left: 4.1.1
Right: 4.2.

**Comment by AThousandShips** [comment]
Please use 4.2.1, 4.2 is not supported, and this might be a bug that was solved there if it happens on 4.2 but not on 4.2.1

**Comment by TechMan06** [comment]
Where can I download 4.2? When did it release? (I didn't know there was a 4.2.1 version at all)
I'll make sure to check though!

**Comment by AThousandShips** [comment]
You just said you used 4.2? The 4.2.1 version is available on the main download page

**Comment by TechMan06** [comment]
Sorry, typo, I meant 4.2.1 on the first part.
I'll be checking, thanks.

**Comment by Lunarexxy** [comment]
I tested this on 4.1.1, 4.2, 4.2.1, and 4.3dev4 for good measure.

The issue in the MRP only shows up on 4.2. Likely fixed by #85681

**Comment by akien-mga** [comment]
Thanks for testing! Closing as fixed by #85681.
