### ISSUE TITLE
AnimationPlayer stop() method does not reset animation tracks before playing new animations.

### ISSUE THREAD

**Issue by yoont4** [godotengine/godot#89269]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4665) - AMD Ryzen Threadripper 3970X 32-Core Processor (64 Threads)

### Issue description

When using an `AnimationPlayer` that has non-overlapping animation tracks between 2 animations, if you stop the previous animation and then play the new one, instead of resetting the non-target tracks to the `RESET` track value, it inherits the first frame of the **_previous_** animation.

i.e. if these are the tracks:
```
RESET:
- scale: (1, 1)
- rotation: 0

SCALE:
- scale: (2, 2) -> (1, 1)

ROTATE:
- rotation: 90 -> 0
```

Switching between `SCALE` and `ROTATE` via `player.stop()` and then `player.play("ROTATE")` will set the scale to `(2, 2)` instead of `(1, 1)`.

Even manually calling `player.play("RESET")` after `stop()` and before the other animation does nothing.

NOTE: this does NOT happen when `deterministic = true`. But I feel it is still a bug based on the description as it says when `deterministic = false`, it should normalize between the last track. But based on the documentation and the way people talk about it, it should be resetting the properties to the `RESET` track immediately. So it should be blending from the RESET track to the new animation (which is the intuitive behavior for me). I tested the case of manually calling `RESET` anyways and it still fails so I'm pretty sure it's a bug.

### Steps to reproduce

- Run sample project with 'F5'
- Press 'q' to trigger scale animation -> only animates scale
- Press 'w' to trigger rotation animation -> inherits scale from previous animation + rotates
- Press 'q' to re-trigger scale animation -> inherits rotation from previous animation + scales

### Minimal reproduction project (MRP)

[AnimationTrackBugRepro.zip](https://github.com/godotengine/godot/files/14532116/AnimationTrackBugRepro.zip)

**Comment by TokageItLab** [comment]
This is the expected behavior and the reason deterministic was implemented into AnimationPlayer. See also https://github.com/godotengine/godot/issues/63465.

Note that the RESET track defines the value when the scene is saved/loaded, and does not have the role to be set to that value by `stop()` when deterministic is off.

**Comment by yoont4** [comment]
Ah I see, thanks for the clarification! I do feel the documentation could be a bit clearer for what it suggests users to do though, as many other threads have misinterpreted the description to mean reset the track values to the `RESET` track. 

I think primarily the misunderstanding is that using `AnimationPlayer` to trigger repeated interruptible animations is a pretty common use case, and none of the documentation or examples really acknowledge that it needs to be handled via that flag (I actually searched through the docs before opening this bug for `deterministic` to see if the property is referenced in any of the Animation posts). As most users figure out that they need to call `stop()` before `play()` to interrupt itself, since calling `play()` on the same animation does nothing if it's already playing, but not that the deterministic flag is responsible for choosing the source animation blend-target when switching animations.
