### ISSUE TITLE
Feature: how about load a texture once a time?

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#8926]
**Operating system or device - Godot version:**
Linux XUbuntu, Godot 2.1.3

**Issue description:**

Well, in this proposal, I want to say that how about to make an unique load from a resource? Like if a had an unique texture loaded, so when create a sprite in the texture option will appear an option where to use an already loaded texture from another sprite, in this way, we just load once a texture. Is this possible?

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Zylann** [comment]
Isn't it the way it works already?

**Comment by volzhs** [comment]
AFAIK, godot works in that way as you wrote in issue description.
do you have any symptom that looks like not using cache?

**Comment by sam-leo** [comment]
Wow, man, I thought that godot doesn't do this. Thanks for the info, I've searching for this.
I just not have the info that godot loads once a time an texture, so, in my game I made an ugly code to load once an texture. Well, if godot can, we can too hehehe
Thank you

**Comment by Zylann** [comment]
Just as a note, in my early days I thought Godot was loading a texture twice when I clicked "Load" in the editor, just because of the naming maybe. Then I eventually figured it out by asking/learning.
