### ISSUE TITLE
Syncing a large Dictionary with MultiplayerSynchronizer causes MTU limit error

### ISSUE THREAD

**Issue by Macklehatton** [godotengine/godot#89262]
### Tested versions

Reproducible in - v4.2.stable.mono.official [46dc27791] and v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 Threads)

### Issue description

When using a MultiplayerSynchronizer node to sync a Dictionary (Vector2i, int) of a size some value larger than 64 I receive the following error.

```
E 0:00:06:0503   _send_sync: Node states bigger than MTU will not be sent (2568 > 1350): /root/Lobby
  <C++ Error>    Condition "size > sync_mtu" is true. Continuing.
  <C++ Source>   modules/multiplayer/scene_replication_interface.cpp:833 @ _send_sync()
```

The only mention of MTU limits in the documentation suggests high-level multiplayer intends to avoid the end user being concerned with the concept. A blog post from 2016 suggests the user should not have to deal with MTU limits manually.

https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html#high-level-vs-low-level-api
https://godotengine.org/article/godots-new-high-level-networking-preview/

### Steps to reproduce

Create an exported dictionary on a node and add ~128 elements to it. Add a MultiplayerSynchronizer and add the Dictionary to the synchronizers properties. The error occurs when replicate is set to Always but not On Change.

In the MRP I use the following code to populate the dictionary.

```
@export var coordinate_dictionary : Dictionary

# Called when the node enters the scene tree for the first time.
func _ready():
	coordinate_dictionary = {}
	if !multiplayer.is_server():
		return
	for i in 128:
		coordinate_dictionary[Vector2i(i,i)] = i
```

### Minimal reproduction project (MRP)

[DictSizeTestPong.zip](https://github.com/godotengine/godot/files/14529008/DictSizeTestPong.zip)

The MRP adds a simple test to the pong demo project found here:
https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_pong

**Comment by conde2** [comment]
Not a bug, just use set_max_sync_packet_size

```
	ClassDB::bind_method(D_METHOD("set_max_sync_packet_size", "size"), &SceneMultiplayer::set_max_sync_packet_size);
```

And change for the value you want.

**Comment by Macklehatton** [comment]
Thank you, it looks like that would solve the issue for my case. However, the documentation for max_sync_packet_size says 

> Maximum size of each synchronization packet. Higher values increase the chance of receiving full updates in a single frame, but also the chance of packet loss. See [MultiplayerSynchronizer](https://docs.godotengine.org/en/stable/classes/class_multiplayersynchronizer.html#class-multiplayersynchronizer).

This doesn't suggest that a smaller value will result in an error as it does. If I can get any kind of confirmation that this is intended behavior I'll close the issue and consider making an improvement proposal and an issue for the docs.

**Comment by AThousandShips** [comment]
This is intended, you should avoid sending large data packets and I don't think what you're trying to do here is supported, synchronisation should be used for properties that needs that kind of updates, not complex large data structures, they should be sent by other means such as rpc calls
