### ISSUE TITLE
Debug Adapter: Console Output should have the "console" category as per specifications

### ISSUE THREAD

**Issue by dekaravanhoc** [godotengine/godot#89279]
### Tested versions

Godot v4.2.2.rc1

### System information

Godot v4.2.2.rc1 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3640) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

At the moment console output is marked as stdoud (All console output including printerr etc.). Thats probably not completly wrong, but there is an explicit "console" category for this, which is also the default, if no category is given. https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output
```
[ DEBUG ] 2024-03-08T12:06:48Z+0100 ] ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:951 ]	1	{
  body = {
    category = "stdout",
    output = "Loaded system CA certificates\r\n"
  },
  event = "output",
  seq = 7,
  type = "event"
}
```
i.e. nvim-dap outputs "console" output to the console and "stdout" output to its REPL interface.
I would expect all console output from Godot to be category "console". 

### Steps to reproduce

Debug a game and look into the logs of your debug client or the output stream of the debug adapter.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @rsubtil

**Comment by rsubtil** [comment]
I'm not sure about this one. The spec states that the `console` category should be used for any output from the debugger (Godot editor), and not the debuggee (the process being debugged):
```
* 'console': Show the output in the client's default message UI, e.g. a
* 'debug console'. This category should only be used for informational
* output from the debugger (as opposed to the debuggee).
```

Currently all `output` events are generated from the debuggee, and the editor does not generate any output itself: https://github.com/godotengine/godot/blob/ffc41fb76df5922321cdd98cce12715a039629b0/editor/debugger/debug_adapter/debug_adapter_protocol.cpp#L1030

**Comment by dekaravanhoc** [comment]
Ah yeah ok. Reading comprehension... :) You are correct. 
But stderr (like printerr()) output should than be marked as such or not?
