### ISSUE TITLE
Infinite loop caused by typed for-loop variable when looping through `PackedDataContainer`

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#89290]
### Tested versions

ffc41fb76df5922321cdd98cce12715a039629b0 - reproducible
4.2.1 - reproducible

### System information

Godot v4.3.dev (55ebf09ea) - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 00:30:36 +0000 - Tty - GLES3 (Compatibility) - AMD Radeon RX 6900 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.7.8-arch1-1) () - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When looping through a `PackedDataContainer` whose members should only be of type `PackedDataContainerRef`, specifying the latter as the type of a for-loop variable will cause an infinite loop when looping through the elements.

### Steps to reproduce

Run the MRP.

The infinite loop is caused by `ref : PackedDataContainerRef `. Replacing that with just `ref` fixes the issue.

### Minimal reproduction project (MRP)

[TypedPDCRBug.zip](https://github.com/godotengine/godot/files/14541453/TypedPDCRBug.zip)

**Comment by AThousandShips** [comment]
While the infinite error shouldn't happen, the data in it isn't guaranteed to just be the ref AFAIK, that's just with nested cases, so that part isn't a bug, the bug is the iteration breaking
