### ISSUE TITLE
AnimatedTexture : No Animation with AtlasTexture

### ISSUE THREAD

**Issue by Donekulda** [godotengine/godot#89291]
### Tested versions

- Reproductible in v4.2.1 Stable

### System information

Windows 10 - Godot v4.2.1.stable -gl_compatibility

### Issue description

TextureRect texture isn't being animated when using AnimatedTexture

### Steps to reproduce

Use TextureRect, Set Texture to AnimatedTexture and for each fframe set atlas texture and set the coordinates and size for each frame, with same size.

### Minimal reproduction project (MRP)

[MRPAnimatedTexture.zip](https://github.com/godotengine/godot/files/14541480/MRPAnimatedTexture.zip)

**Comment by AThousandShips** [comment]
`AnimatedTexture` is deprecated and not supported, you should use other features instead

**Comment by Mickeon** [comment]
I've known about this for a while and the fix would be a bit annoying due of the way texture proxies work. It's a shame there's no proper alternative to AnimatedTexture but it is what it is. Closest thing revolves around a custom shader (which I've done for myself)

**Comment by AThousandShips** [comment]
Indeed just found that too, closing as this is documented, and the class in question is deprecated and isn't getting new features etc.
