### ISSUE TITLE
Failure in exported project when having cross referencing node scripts

### ISSUE THREAD

**Issue by GameDevLlama** [godotengine/godot#89297]
### Tested versions

- Reproducible in 4.3 dev4

### System information

Windows 10 Godot 4.3 dev4

### Issue description

Experiencing a runtime error in exported Godot projects when using class_name for nodes, with scripts cyclically or cross-referencing each other.

The classes function correctly in the editor and while testing the game,
but when starting the exported game, the nodes with these scripts being attached will fail with the error:

**'ERROR: Another resource is loaded from path 'res://xxxx.gd' (possible cyclic resource inclusion).'**

### Steps to reproduce

1. Run the reproduction project locally and investigate the nodes: Cross-Referencing is working as expected.
2. Export the project for desktop (_Compressed binary tokens_ or _binary tokens_ enabled):
![image](https://github.com/godotengine/godot/assets/1180429/c93a59e2-1f4a-477b-b772-c64857725083)

3. Start **"Cyclic-Export.console.exe"**
4. Cross-Referencing scripts won't be loading, showing in the console:

![image](https://github.com/godotengine/godot/assets/1180429/0aac4657-c966-47d6-a2b5-8a7677eded0d)

### Minimal reproduction project (MRP)

[Cyclic-Export.zip](https://github.com/godotengine/godot/files/14543051/Cyclic-Export.zip)

**Comment by GameDevLlama** [comment]
Was this probably also fixed by the fix for #89343 ?

**Comment by AThousandShips** [comment]
Sounds like something that might have been fixed by:
* https://github.com/godotengine/godot/pull/89005

Can someone confirm in latest?

**Comment by ghmart** [comment]
Can confirm, it's fixed in master (tested with 810f127).
Same output without nulls. Compressed binary tokens.
