### ISSUE TITLE
Editor shortcuts aren't displayed

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8931]
(using the current tip)

In the Shortcuts tab of the Editor Settings dialog, no shortcuts are displayed (other than the ones that aren't set).

![screenshot_20170526_101849](https://cloud.githubusercontent.com/assets/16531565/26500792/ecc5051c-41fc-11e7-8859-e3c285f7b129.png)

**Comment by vnen** [comment]
Fixed by 3f2cd75c6f4c199389ad4d9766b5895be414a5f6.
