### ISSUE TITLE
Format strings not printed by printraw()

### ISSUE THREAD

**Issue by Beliriel** [godotengine/godot#89323]
### Tested versions

- Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Windows 11 - Godot 4.2.1 stable

### Issue description

When using format strings printraw does not print them as opposed to print

### Steps to reproduce

1.  Execute the following statements in a gdscript file:

```
var format_string = "Hello %s!" % "World"  
print(format_string)  
printraw(format_string)  
print("End of Program")  
```

Expected console output:
```
Hello World!
Hello World!End of Program
```

Actual console output:
```
Hello World!
End of Program
```

### Minimal reproduction project (MRP)

[example_project_printraw_bug.zip](https://github.com/godotengine/godot/files/14547378/example_project_printraw_bug.zip)

**Comment by thesusian** [comment]
I believe this is expected behavior, check #2233. `printraw()` currently only prints to the OS output. 

If you need to print two strings in the same line your best choice currently is using a variable.
```
var my_string = "Hello World"
my_string += " End of Program"
print(my_string)
```

**Comment by AThousandShips** [comment]
This used to be documented but got lost at some time, see:
* https://github.com/godotengine/godot/pull/33257

I'll see about adding it back in

**Comment by Mickeon** [comment]
It's _already_ documented. Look closely:
> Prints one or more arguments to strings in the best way possible to the OS terminal. Unlike [method print], no newline is automatically added at the end.

a18afb9a56d31a63d07c361070a36658d44fa84e compressed it to avoid the extra note which, I do agree, is superfluous. What _could_ be done is being more explicit about what the OS terminal is.

**Comment by Beliriel** [comment]
> It's _already_ documented. Look closely:
> 
> > Prints one or more arguments to strings in the best way possible to the OS terminal. Unlike [method print], no newline is automatically added at the end.
> 
> [a18afb9](https://github.com/godotengine/godot/commit/a18afb9a56d31a63d07c361070a36658d44fa84e) compressed it to avoid the extra note which, I do agree, is superfluous. What _could_ be done is being more explicit about what the OS terminal is.

I did find that in the docs but yeah apparently the OS terminal is not the same as the console output. I just assumed the normal Godot console is just a wrapper for a background OS terminal. So I was confused why it didn't work. I mean I would think "in the best way possible to the OS terminal" would be MORE flexible then just the normal print function. Not less.  
My goal was to cut the newline character from an output and this was the only documented function that explicitly mentioned NOT adding the newline character.  

It's not a huge issue. It's easily mitigated by a workaround appending to a string variable and then printing it (as mentioned by @thesusian ). But printraw could use a bit more documentation on its behaviour and what exactly it accesses. Or atleast what the difference to print is and if there are caveats depending on the OS.

**Comment by AndersonMartins1** [comment]
Problema:
Ao usar a função printraw no Godot 4.2.1 para imprimir uma string formatada, observa-se que a string formatada não é impressa corretamente.

Passos para Reproduzir:

Execute as seguintes instruções em um arquivo gdscript:

var format_string = "Hello %s!" % "World"
print(format_string)
printraw(format_string)
print("End of Program")

Comportamento Esperado:
Esperava-se que a função printraw imprimisse a string formatada da mesma forma que a função print, resultando em ambas as strings sendo impressas na mesma linha.

Solução Alternativa:
Uma solução alternativa para garantir que ambas as strings sejam impressas na mesma linha é usar uma variável para concatenar as strings e, em seguida, imprimir a variável usando a função print.

Exemplo de código:

var format_string = "Hello %s!" % "World"
var output_string = format_string + " End of Program"
print(output_string)

Consulta à Documentação e à Comunidade:
Para entender melhor o comportamento da função printraw ou resolver a confusão em torno dela, recomenda-se consultar a documentação oficial do Godot e procurar em fóruns e comunidades online.

Relatório do Problema:
Se acredita-se que há um problema real com a função printraw ou sua documentação, é possível relatar o problema para a equipe de desenvolvimento do Godot por meio do fórum do Godot, GitHub ou outras plataformas de suporte.

Espero que essas informações ajudem a esclarecer o problema que você está enfrentando com a função printraw no Godot 4.2.1. Se precisar de mais assistência, não hesite em perguntar!

**Comment by AThousandShips** [comment]
The distinction is not obvious, as this has turned up on several occasions

**Comment by AndersonMartins1** [comment]
Para resolver o problema descrito, em que instâncias que podem ser chamadas de uma função estática, recuperadas diretamente da classe, apresentam comportamentos estranhos e inconsistentes, você pode adotar as seguintes práticas:

Usar a Instância para Acessar Métodos Estáticos:
Em vez de tentar acessar os métodos estáticos diretamente da classe, utilize instâncias para acessá-los. Isso garante um comportamento mais consistente e evita possíveis problemas de nulidade.

Exemplo:

var my_instance = MyClass.new()
my_instance.my_static() # Chamada de método estático usando instância

Evitar Acesso Direto de Métodos Estáticos pela Classe:
Evite acessar métodos estáticos diretamente pela classe, pois isso pode levar a comportamentos inesperados ou erros de nulidade. É mais seguro e mais consistente acessá-los por meio de instâncias.

Verificar a Presença do Método antes de Acessá-lo:
Antes de tentar acessar um método estático por meio de uma classe, verifique se o método está presente na classe para evitar erros de nulidade.

Exemplo:

if "my_static" in MyClass:
    var callable = MyClass.my_static
    callable.call()
Relatar o Problema:
Se você encontrar comportamentos estranhos ou inconsistentes ao lidar com métodos estáticos, considere relatar o problema para a equipe de desenvolvimento do Godot. Isso pode ajudar a melhorar a consistência e a confiabilidade do framework para todos os usuários.

Contribuir com a Documentação:
Se você descobrir insights úteis ou soluções alternativas para lidar com métodos estáticos, considere contribuir com a documentação do Godot para ajudar outros desenvolvedores a evitar problemas semelhantes.

Ao adotar essas práticas, você pode evitar problemas relacionados ao acesso e uso de métodos estáticos no Godot 4.2.1 e garantir um comportamento mais consistente e confiável em seu código.

**Comment by akien-mga** [comment]
@AndersonMartins1 After multiple warnings, I'm have to ban you for some time, as you appear to be spamming our repository with:
- Unsollicited PRs that do not improve anything
- AI generated replies in English
- AI generated replies in Portuguese

I assume that you do want to contribute and are simply not familiar with how to do it and what's the proper etiquette, but for now your behavior is disruptive. Feel free to join the Godot contributors chat to discuss how to contribute constructively.

**Comment by sleepy-day** [comment]
I was taking a look at this issue since it was labelled as a good first issue and i was looking to try and contribute though I'd like to get a bit of clarification on it if that's all good. From what I can see it's working as intended though there's a bit of confusion surrounding where the output is printed, could I check what the change in mind was for this issue here? Sorry if I'm missing something obvious and thanks for the help.

**Comment by Mickeon** [comment]
What needs to be done is to just be more explicit as to where the printing is done. "OS Terminal" is *not* the editor's Console, hence the original issue's confusion.

**Comment by ArceusMaxis** [comment]
Resolved in https://github.com/godotengine/godot/commit/85fb443
