### ISSUE TITLE
iOS exports don't have a Launch Screen (preventing them from using the full screen on iPad Pro)

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#89334]
### Tested versions

Godot 3.4.4+ including Godot 4
I am unable to test older versions due to missing downloads and Xcode limitations
This bug has existed in pretty much every version with iOS support as far as I'm concerned

### System information

iPad Pro 11"

### Issue description

Because the exported Xcode project for iOS builds does not include a Launch Screen (still uses the deprecated Launch Images), Godot applications can not take advantage of the full screen space on devices like the iPad Pro.
![IMG_5740](https://github.com/godotengine/godot/assets/24682280/5f78abaa-aed1-4b7e-aee9-7363d938bece)

### Steps to reproduce

Run any Godot application on iPad Pro, without manually adding a Launch Screen to the Xcode project after it has been exported.

### Minimal reproduction project (MRP)

[BlankProject.zip](https://github.com/godotengine/godot/files/14547761/BlankProject.zip)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Launch images were removed from 4.3 for this reason, and 3.5 / 4.2 have "Use launch storyboard" export option to auto add storyboard instead of deprecated launch images, you do not need to add anything manually.

**Comment by CenTdemeern1** [comment]
> Launch images were [removed](https://github.com/godotengine/godot/pull/86312) from 4.3 for this reason, and 3.2+ / 4.0+ have `Use launch screen storyboard` export option to auto add storyboard instead of deprecated launch images, you do not need to add anything manually.

Oh, I guess I'm        not smart then, apologies

**Comment by akien-mga** [comment]
No worry, as described the default only just changed for the unreleased 4.3, and in 3.x the launch screen feature seems to be opt in.

@bruvzg Should we flip the bool in 3.x and 4.2/4.1 so that launch screen storyboards are used by default?

**Comment by bruvzg** [comment]
Min. supported iOS version in 3.x is 12.0, storyboard is available in iOS 8+ and UILaunchImages is deprecated in iOS 13. So there's no reason to use it at all. Probably should be removed in 3.6 and disabled by default in the cherry-picks.
