### ISSUE TITLE
Game engine crashes when configuring collisions on a tile map in version 4.2.1

### ISSUE THREAD

**Issue by ringbearer14325** [godotengine/godot#89338]
### Tested versions

4.2.1 Stable

### System information

Windows 10 Pro Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.20 GHz Ram 16.0 GB

### Issue description

When I'm creating collisions on a tilemap the engine crashes. I making a large RPG game with lots of tilemap scenes. In the tilesmaps I create 1 physics layer for the collisions. When you fill the little squares on the map the engine randomly closes. I have my command prompt open when i code so I see that the error says fatal error.    

### Steps to reproduce

Configure the collisions on the tile set map after creating a physics layer. 

### Minimal reproduction project (MRP)

[New Game Project2.zip](https://github.com/godotengine/godot/files/14548002/New.Game.Project2.zip)

**Comment by AlexOtsuka** [comment]
Is this related to this at all https://github.com/godotengine/godot/issues/86562?
Are you able to reproduce the bug consistently?

**Comment by AThousandShips** [comment]
Can you try this with [4.2.2.rc1](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-1/)?

**Comment by ringbearer14325** [comment]
The bugs appears when there is a lot of tile sets scenes. Its when you configure the collisions on the tile set map. I'm going to post another zip file with more maps. Sorry for the vague information its my first time posting about a bug.

**Comment by AThousandShips** [comment]
Did you try 4.2.2.rc1?

**Comment by ringbearer14325** [comment]
> g

I just looked at the link you gave me and you are 100% correct. That is the bug that appears is when you delete a point on a layer.

**Comment by ringbearer14325** [comment]
> Did you try 4.2.2.rc1?

Not yet.

**Comment by AThousandShips** [comment]
Please do so before testing any further :) this is most likely solved already

**Comment by ringbearer14325** [comment]
> Please do so before testing any further :) this is most likely solved already

Ok thank you.

**Comment by ringbearer14325** [comment]
I downloaded the 4.2.2 rc1 version.
