### ISSUE TITLE
Typed variable of custom class type in autoload produces error in exported binary

### ISSUE THREAD

**Issue by ghmart** [godotengine/godot#89343]
### Tested versions

- Reproducible in 4.3-dev4.
- Not reproducible in 4.2.1-stable.

### System information

Godot v4.3.dev4 - Debian GNU/Linux 11 (bullseye) 11 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti () - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

Typed variable of custom class type in autoload produces error in exported binary:

_"ERROR: Another resource is loaded from ... (possible cyclic resource inclusion).
   at: set_path (core/io/resource.cpp:75)"_

Running from editor is OK.
Omitting type from variable in autoload makes error gone.

### Steps to reproduce

1. Create autoload script "events.gd" (name "events"):

```
extends Node

signal started

var level: Level
```

2. Create main scene with script:

```
extends Node2D

func _ready():
	events.level = $Level
	events.started.emit()

	print(events.level)
```

3. Create "Level" scene with script:

```
class_name Level extends Node2D

func _ready():
	await events.started
```

4. Instantiate "Level" scene as a child of main scene.

5. Export and run project in terminal.
print(events.level) outputs null.

### Minimal reproduction project (MRP)

[auto.zip](https://github.com/godotengine/godot/files/14548741/auto.zip)

**Comment by lostminds** [comment]
I ran into a similar issue which I think turned out to be this issue https://github.com/godotengine/godot/issues/88796 with the new binary script tokens (enabled by default in exports). Try changing it back to the old default of text script tokens (in export config, far right Scripts tab), and if that fixes it it's probably the same issue.

**Comment by ghmart** [comment]
You are right!
Changing GDScript export mode to text fixes this error.

Thank you!

**Comment by AThousandShips** [comment]
Then this should be fixed in the latest version, if you can compile yourself you can test, otherwise you can see in the next development release

Closing as resolved :)
