### ISSUE TITLE
Threads are unable to wait on user created signals

### ISSUE THREAD

**Issue by AdorianM** [godotengine/godot#89347]
### Tested versions

- Reproductible in: 4.2.1.stable

### System information

Windows 10

### Issue description

At the press of a button I try creating multiple threads which call a coroutine:
```gdscript
@onready var emitter = $Emitter
...
func _on_button_button_up():
	for i in range(0, 3):
		var thread = Thread.new()
		thread.start(coroutine_with_parameter.bind(i))
...
func coroutine_with_parameter(i: int):
	print(i)
	await emitter.some_custom_signal
	print("done")
```
The emitter class emits the signal like this:
```gdscript
extends Node2D
class_name Emitter

signal some_custom_signal

func _ready():
	some_custom_signal.emit()
```

When trying to run the code with this configuration I get this error for each thread:
```
E 0:00:03:0171   main.gd:18 @ coroutine_with_parameter(): Caller thread can't call this function in this node (/root/Main/Emitter). Use call_deferred() or call_thread_group() instead.
  <C++ Error>    Condition "!is_accessible_from_caller_thread()" is true. Returning: (ERR_INVALID_PARAMETER)
  <C++ Source>   scene/main/node.cpp:3640 @ connect()
  <Stack Trace>  main.gd:18 @ coroutine_with_parameter()

```

However, if instead of waiting for the `some_custom_signal` signal with `await emitter.some_custom_signal`, I wait for a signal emitted by a Godot default node, everything works fine. For example, using a timer like this works as expected, printing numbers from 0 to 2 simultaneously and after 1 second, printing "done" three times:
```gdscript
func coroutine_with_parameter(i: int):
	print(i)
	await get_tree().create_timer(1.0).timeout
	print("done")
```

### Steps to reproduce

1. Run the project
2. Press the button which is connected with the main scene through the `button_up` signal
3. Error is thrown
4. Change `await emitter.some_custom_signal` with `await get_tree().create_timer(1.0).timeout`
5. Repeat steps 1 and 2
6. Error is not thrown

### Minimal reproduction project (MRP)

[threads-mrp.zip](https://github.com/godotengine/godot/files/14549552/threads-mrp.zip)

**Comment by AThousandShips** [comment]
That's not equivalent, you're not awaiting a node signal in the second example, `SceneTreeTimer` isn't a `Node`, try awaiting a `Timer` node instead

**Comment by AdorianM** [comment]
You are right, using a Timer node throws the same error.
In the [docs you linked](https://docs.godotengine.org/en/stable/tutorials/performance/thread_safe_apis.html#scene-tree) I didn't notice anything specified about how one could interact with signals in a case like this. I'm guessing that using `call_deferred` works only for functions. I'm also not sending any data between threads, so I think a Mutex would also not be of much help.

Is the behavior I'm expecting achievable?

**Comment by AThousandShips** [comment]
It isn't possible as such, this is a limitation but awaiting things on threads seems a bit weird to begin with to me, await is designed to not block things, which is already what threads do right?

**Comment by AdorianM** [comment]
I agree that it is not intuitive to do so. The reasoning for what I did is that I wanted to have more control over simulating a method that takes more time to execute, for demonstration purposes.

However, I could go with simply looping over a huge amount of numbers or awaiting for a fixed number of seconds.
If there's nothing else you'd like to add, you can consider this as solved for me. Thanks a lot!

**Comment by AThousandShips** [comment]
I'd suggest using other ways of signalling these things, but it's very situation specific and probably something you can solve with the tools described in the manual, such as semaphores

Thank you and I'll go ahead and close this :)

**Comment by AThousandShips** [comment]
See also, awaiting on threads seems to currently have some other issues that makes it not useful:
* https://github.com/godotengine/godot/issues/79637
