### ISSUE TITLE
Colors in autocomplete don't display transparency.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#89355]
### Tested versions

4.3.dev4

### System information

Godot v4.3.dev4 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/c65483cb-24d1-4a19-a480-69bd1b0bdd03)

No checkerboard background, like I'd expect, which makes this misleading.

### Steps to reproduce

`const lmofa = Color("ffffff44")`

Then make another variable and see the autocomplete.

### Minimal reproduction project (MRP)

N/A

**Comment by nongvantinh** [comment]
I have only a limited time to work on this, but I believe I can fix it. However, I'm not sure how to replicate the issue. Having a video recording of your actions would be really helpful.

**Comment by brcontainer** [comment]
Are you referring to the color to the right of the autocomplete?

![image](https://github.com/godotengine/godot/assets/4368952/515da8fb-13f5-43d1-bc6d-595ea6a7612e)

**Comment by MewPurPur** [comment]
Yes

**Comment by brcontainer** [comment]
What do you suggest so that transparency is evident in the menu? After all, it is transparent, so showing the menu background color seems ideal, so far.

**Comment by MewPurPur** [comment]
Transparency is normally accounted for with a checkerboard background.

**Comment by brcontainer** [comment]
It's a good suggestion, but depending on the opacity level, in this way it could hinder the perception. This is not actually a bug, but rather something that could be discussed in the GIPs: https://github.com/godotengine/godot-proposals
