### ISSUE TITLE
Color Picker slider arrows don't align with the mouse

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#89358]
### Tested versions

4.3.dev4, exists in 4.2.1 too

### System information

Godot v4.3.dev4 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

https://github.com/godotengine/godot/assets/85438892/234ab65d-0dd2-4e37-9d8d-a3c19c2bb8a6

The slider is never right under my mouse, it tends to veer off to the side as I drag it further.

### Steps to reproduce

Use any color picker in the Godot editor, like the `modulate` one.

### Minimal reproduction project (MRP)

N/A

**Comment by kleonc** [comment]
Already fixed by #88068.
