### ISSUE TITLE
glTF's Naming Version and Embedded Image Handling import options can't be overridden in Project Settings Import Defaults

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#89379]
### Tested versions

Should be an issue with all versions 4.3 and higher

On 4.2 and below, it worked because *all* Scene importers show the gltf/embedded_image_handling setting.

### System information

Godot v4.3.dev (c5c6f8d43) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

There is a setting for glb embedded textures that projects may wish to change to basis universal (or uncompressed) for certain workflows. The default value extracts textures without asking, and there is no way to change this default in project settings:
![image](https://github.com/godotengine/godot/assets/39946030/03063860-1bd1-48cb-b43c-1687a5dbab36)

This is the setting in the import dock which I want changed.
![image](https://github.com/godotengine/godot/assets/39946030/52d2309a-7be4-4602-a8d7-07fa446084b0)

This means, the only way to include glb files in the project and use their textures embedded is to add them to the project, let it extract the textures, wait for godot to compress the extracted textures, then change the import setting to Embed as Basis Universal, then reimport, and finally delete the extracted textures.
Due tot his issue, this process must be repeated for every single glb in the project, or avoid using glb files.

The one upside is the difficulty in changing this setting encourages users to avoids some workflow pitfalls: Basis Universal has had some issues; uncompressed textures are bad for many reasons; and embedded textures will cause memory duplication when extracting meshes and materials. So maybe it's a good thing that this setting is hard to change ;-)

I believe the same issue is likely to affect blend import settings as well as fbx-specific settings.

On Godot 4.2.x and earlier, it was possible to change gltf settings on all scenes, including ESCN, Blend, FBX and glTF:
![ESCN sample](https://github.com/godotengine/godot/assets/39946030/41f48b0d-5b3d-4975-b5b5-9226d862412e)

The blend settings never showed up in import defaults. only the gltf option seems to be global.

### Steps to reproduce

1. Go to Project Settings -> Import Defaults.
2. Choose "Scene"
3. There is no way to change the default value of Extract Tex

### Minimal reproduction project (MRP)

This is an issue with project settings, so it happens even in a blank project.

**Comment by jamie-pate** [comment]
I used this setting on the regular import panel (not the advanced import panel) and it stuck.. 
![image](https://github.com/godotengine/godot/assets/682658/4462d34d-4abb-4467-915f-baf43ba2fd04)

Afterward the option to set this default in the project settings `Import Defaults` was available!
![image](https://github.com/godotengine/godot/assets/682658/0bc9377b-c076-4e28-bb2b-67c89d26459e)

**Comment by skyace65** [comment]
Jamie is correct and I've tested it in 4.2.2. You can change that in project settings under import defaults and the change stays.

**Comment by caioraphael1** [comment]
I'm also having this issue. I'm using 4.3.beta2. Using Jamie's method didn't work for me, the option didn't appear afterward.

**Comment by Calinou** [comment]
The issue isn't specific to glTF scenes. IT seems mport options that are only available under certain file extensions are not available to be overridden in the Project Settings' import defaults tab. SVG's `svg/scale` import option likely has the same issue, however it may be defined differently - I believe ResourceImporterTexture hides the `svg/scale` property for non-SVG source files, while the glTF importer may define its naming convention and embedded texture handling options differently.

**Comment by caioraphael1** [comment]
> I don't see a good way to resolve this issue, other than adding **glTF Scene** as a separate import default type specifically for glTF scenes. This means all glTF scenes would start using their own defaults, independently from other 3D scene formats.

Would that be an issue? For me it makes more sense to separate 3D objects from normal objects, as it sounded weird to me that the .gltf options were inside the Scene options.

**Comment by Calinou** [comment]
> For me it makes more sense to separate 3D objects from normal objects, as it sounded weird to me that the .gltf options were inside the Scene options.

"Scene" import is only used for 3D scenes. It's used for the following:

- glTF (.gltf, .glb)
- FBX (.fbx)
- Collada (.dae)
- OBJ (.obj, *only if imported as "OBJ as Scene", not "Mesh"*)

SCN/TSCN scenes do not use the import system, as they do not need to be imported to be used in the first place.

**Comment by prominentdetail** [comment]
I just tested, and I have the same issue.
The "Embedded Image Handling" option that is available in 4.2.2 is not available in 4.3.beta2

This forces all the gltf files to have blurry/compressed textures:
![image](https://github.com/godotengine/godot/assets/10412778/f86bd411-ade6-4795-ae8d-4744958948e8)

And this is how they should look when uncompressed:
![image](https://github.com/godotengine/godot/assets/10412778/999b503b-6047-4bfd-a1d4-0dfeac1ee25d)


screenshot of missing option in Import Defaults > Scene:
(4.3.beta2)
![image](https://github.com/godotengine/godot/assets/10412778/c4346554-4b8d-487d-83e4-89d5912e7f6d)

and screenshot of how it should look:
(4.2.2)
![image](https://github.com/godotengine/godot/assets/10412778/369a0fd3-923c-41eb-a5a5-63ebf5cda427)

As you can see the glTF section is missing in 4.3.beta2

**Comment by Calinou** [comment]
I can confirm what @prominentdetail reported – this is indeed a regression from 4.2 to 4.3, which I bisected to 04d43947bff4de9db8d7005862a1d895b6703fbc (cc @fire). OP's statement about this being reproducible since 4.0 is therefore incorrect.

PS: This issue can be also noticed in the **Animation Library** import type.
