### ISSUE TITLE
Window.position property does not set the position of a Window

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#89372]
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

I've tried setting the position of the initial Window but it does not seem to allow it. However I can set the size correctly. In addition `Window.popup_centered()` seem to also not work correctly.

Here is the code which inherits directly from Node. 
```gdscript
extends Node

var view_port:Window

func _ready():
	ProjectSettings.set_setting("display/window/subwindows/embed_subwindows", false)
	view_port=get_tree().get_root().get_viewport()
	view_port.initial_position=Window.WINDOW_INITIAL_POSITION_ABSOLUTE
	view_port.mode=Window.MODE_WINDOWED
	view_port.size *= 0.5
	view_port.position=Vector2i(300,300)
	#view_port.popup_centered()
	pass
```

### Steps to reproduce

See above code

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/14552862/Archive.zip)

**Comment by AThousandShips** [comment]
Have you tried `view_port=get_tree().get_root().get_window()` instead? You're getting a viewport, not a window

Also you probably shouldn't pop the window up again if it's already visible, which the game window will be

**Comment by wyattbiker** [comment]
I tried the get_window() same issue. However if I put the position code in `_process()`, the window positions correctly. I don't know if its a good idea fix there, since that runs constantly. Is there a callback that may at least be a workaround.

Also I found out, if I add breakpoint before the end of `_ready()` method, the window opens in the correct position, but if you continue it reverts back to top left corner. 

```gdscript
extends Node

var view_port:Window

func _ready():
	ProjectSettings.set_setting("display/window/subwindows/embed_subwindows", false)	
	view_port=get_tree().get_root().get_window()
	view_port.visible=true
	view_port.initial_position=Window.WINDOW_INITIAL_POSITION_ABSOLUTE
	view_port.mode=Window.MODE_WINDOWED
	view_port.size *= 0.5
	#breakpoint
	pass

func _process(delta):
	view_port.position=Vector2i(300,300)	
	pass
```

**Comment by AThousandShips** [comment]
Just use
```gdscript
func _update_window()
    ...

func _ready():
    _update_window.call_deferred()
```

**Comment by wyattbiker** [comment]
Perfect workaround. Thanks! For anyone else here test code which also centers the window on the screen:

```gdscript
extends Node

var view_port:Window

func _ready():
	ProjectSettings.set_setting("display/window/subwindows/embed_subwindows", false)	
	view_port=get_tree().get_root().get_window()
	view_port.visible=true
	view_port.initial_position=Window.WINDOW_INITIAL_POSITION_ABSOLUTE
	view_port.mode=Window.MODE_WINDOWED
	view_port.size *= 0.5
	#breakpoint
	_update_window.call_deferred()
	pass

func _update_window():
	#view_port.position=Vector2i(300,300)	
	# Center the display window
	view_port.position=(DisplayServer.screen_get_size() - view_port.size) * 0.5
```

**Comment by AThousandShips** [comment]
This can be closed then, thank you for reporting
