### ISSUE TITLE
Pixel snap not working with half-pixel positioned camera 2d

### ISSUE THREAD

**Issue by cesarizu** [godotengine/godot#89370]
### Tested versions

Tested on v4.3.dev.custom_build [bfa866c31]

### System information

Godot v4.3.dev (bfa866c31) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.5123) - 13th Gen Intel(R) Core(TM) i9-13900HX (32 Threads)

### Issue description

When positioning a `Camera2D` in non-integer positions, more specifically on half pixel positions, the snapping to pixel for a `Sprite2D` and a `TextureRect` differs.

For these examples I set:

```
2d/snap/snap_2d_transforms_to_pixel=true
2d/snap/snap_2d_vertices_to_pixel=true
```

This is the test scene:

![image](https://github.com/godotengine/godot/assets/658725/62402921-936b-4c6e-a148-a60018b11ba3)

This is the result:

![screenshot-1](https://github.com/godotengine/godot/assets/658725/b42b8c70-b1a1-4513-8120-d8113e80b0e3)
![screenshot-2](https://github.com/godotengine/godot/assets/658725/10ba5263-fba7-4f8e-b661-2195b4df5ceb)
![screenshot-3](https://github.com/godotengine/godot/assets/658725/46a96a60-bbc2-469f-9afb-728cf9ec6449)

Also setting those to false causes other visual glitches:

```
2d/snap/snap_2d_transforms_to_pixel=false
2d/snap/snap_2d_vertices_to_pixel=false
```

![screenshot-4](https://github.com/godotengine/godot/assets/658725/d97be8c3-cc7e-4b08-921d-36bb33edaf0b)

This doesn't seem to change any outcome:

```
gui/common/snap_controls_to_pixels=true
```

### Steps to reproduce

Position a `Camera2D` at a half pixel position (e.g. `(0.5, 0)`). The way a `TextureRect` and a `Sprite2D` are snapped seem to be at odds.

### Minimal reproduction project (MRP)

[PixelPerfectTests.zip](https://github.com/godotengine/godot/files/14552598/PixelPerfectTests.zip)

**Comment by markdibarry** [comment]
I'm not entirely understanding from the description what effect you're after, but if you're looking for both the `TextureRect` and `Sprite2D` to snap in the same way, you'd only enable `snap_2d_transforms_to_pixel`. Here's your project with the `Camera2D` animating between position `(0.0, 0.0)` and `(2.0, 0.0)` linearly:

https://github.com/godotengine/godot/assets/21325943/fa096893-cf43-49a6-963e-7a4f36a7a990

`snap_2d_vertices_to_pixel` is deprecated and you shouldn't have both enabled at the same time anyway.

**Comment by cesarizu** [comment]
Thanks. Indeed, without `snap_2d_vertices_to_pixel` I don't see any of the artifacts. (I should've read the docs on those). I still have some other glitches on my game but seem to be unrelated to this. So, I'll close this one.
