### ISSUE TITLE
When using an imported font at its original 8px size, Question Mark (?), Colon (:) and some other glyphs are missing. All other sizes work.

### ISSUE THREAD

**Issue by BrainOnOxygen** [godotengine/godot#89374]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5], v4.1.1.stable.official [bd6af8e0e], v4.1.2.stable.official [399c9dc39]

### System information

Windows 11 - v4.2.1.stable.official [b09f793f5] - Forward+

### Issue description

Issue occurs when the font is set to a font_size of EXACTLY 8px. The font is made as an 8px font, but 8px is the exact size that doesn't work. All other sizes show the missing glyphs (even if blurry).

Visual Example:
![image](https://github.com/godotengine/godot/assets/162939951/a1643524-cba6-4fd5-b4f8-c417b0c6e09c)

EXTRA DETAIL
- Font: https://damieng.com/typography/zx-origins/uncial/ (PS: There's a lot of cool fonts there).
- The .ttf, .woff and .woff2 and also as a SystemFont (since the font is installed) all have the same, unwanted, behavior.
- Fonts were ran through "Font Validator" and seem to work fine.
- Font shows the characters correctly in other software including "MS Word" and "Aseprite".
- Writing a "colon" gives me uppercase "X", and ? gives me lowercase "c"

### Steps to reproduce

I've included an **MRP** below, but here's the very short steps to reproduce...
1. Add label node.
2. Override Theme to a font_size of **8px**
3. Override Them to a the Font Uncial, either as a System font or as .ttf, .woff, .woff2 font file.

### Minimal reproduction project (MRP)

[8px-font-issue.zip](https://github.com/godotengine/godot/files/14553046/8px-font-issue.zip)

**Comment by bruvzg** [comment]
Seems like is a broken font (font contain both 8px embedded bitmap and vector font), and embedded bitmap contains garbage (a lot of missing glyphs and some misplaced).

<img width="1678" alt="Screenshot 2024-03-11 at 12 53 40" src="https://github.com/godotengine/godot/assets/7645683/edbccff7-b3e8-4fa7-8552-fa618d8c51b8">

We can disable loading embedded bitmaps (probably should be an option enabled by default).
