### ISSUE TITLE
Tilemap local_to_map unexpected results with isometric shape

### ISSUE THREAD

**Issue by yesitsmattharris** [godotengine/godot#89423]
### Tested versions

Recreated in Godot 4.1.2 and 4.2.1

### System information

MacOS Ventura 13.3.1 - Godot 4.2.1

### Issue description

I have a simple isometric tilemap set up which I want to be able to move a character around. I want to be able to use the cursor to hover over the tiles and have the respective tile highlighted, and when the mouse is clicked for the character to move towards that tile.

The movement works fine with Astar2D, however the bounds of the tile cell are not accurate. Both the highlighted cell and the cell that the character is moved to is wrong. I assume this is because local_to_map is expecting the tile to not be isometric in shape.

### Steps to reproduce

1. Import an isometric spritesheet and set up tilemap to use this
2. Create a simple floor after setting the shape to isometric and the layout to diamond down
3. Attach a script to the tilemap and in the process function add:
```
var selected_cell = local_to_map(get_local_mouse_position())
print(selected_cell)
```
4. Play the current scene and hover over the cells carefully. Note that the selected_cell is updated whilst moving the cursor around a single cell.

(Add a camera and increase zoom to make this easier)

### Minimal reproduction project (MRP)

[iso_issue.zip](https://github.com/godotengine/godot/files/14574624/iso_issue.zip)

**Comment by kleonc** [comment]
You can see in the editor that you've setup the used tile so its "top" mismatches the tile area within the grid:
![Godot_v4 2 1-stable_win64_XhxGofOlaA](https://github.com/godotengine/godot/assets/9283098/09e4297a-94c4-42c3-be14-ade691e350aa)
![Godot_v4 2 1-stable_win64_Pq9Lfo5FSj](https://github.com/godotengine/godot/assets/9283098/dea5927b-dbea-4620-afe3-0cca2a99c1e0) ![Godot_v4 2 1-stable_win64_Pq9Lfo5FSj](https://github.com/godotengine/godot/assets/9283098/e0468801-d73a-445f-83db-2ebe7dff96ed)


E.g. changing the rendering texture origin for the used tile to make it match the grid fixes "the issue":
![G5665RxH60](https://github.com/godotengine/godot/assets/9283098/69e5f8f7-05bb-4b00-a42c-cd7ac86deeeb)

No bug in here, it works according to your setup. Closing.

**Comment by yesitsmattharris** [comment]
Thanks @kleonc - really appreciate it! How did you get the grid to show? I only get the 2d grid and only when I activate snap?

**Comment by kleonc** [comment]
> How did you get the grid to show?

I've just selected the TileMap (to be clear it's within the editor).

If doesn't show for you then maybe you turned it off:
![WNrssoilYl](https://github.com/godotengine/godot/assets/9283098/8fe8da3d-f4f5-41f1-b091-19e7bf260e6a)

> I only get the 2d grid and only when I activate snap?

These are two different grids, unrelated to each other.

**Comment by yesitsmattharris** [comment]
Thank you so much!
