### ISSUE TITLE
Godot crashes, when you change root node to something unpredictable

### ISSUE THREAD

**Issue by Ambear1337** [godotengine/godot#89425]
### Tested versions

4.2.1 Steam version

### System information

Windows 10

### Issue description

I changed Sprite3D to subviewport, while it was root node and godot just closed instantly

### Steps to reproduce

1. Create scene with Sprite3D as a root node
2. Give it a texture and enable billboard
3. Change Sprite3D to sub-viewport

### Minimal reproduction project (MRP)

It happened once, I tried to make it again, but everything is fine

**Comment by ajreckof** [comment]
I have checked and it is most likely #78372 which is the culprit and it escalated into a crash now.
