### ISSUE TITLE
RichTextLabel's text field does not clear without a space in the string

### ISSUE THREAD

**Issue by ghostradiogames** [godotengine/godot#89435]
### Tested versions

Reproduced in 4.2.3 dev4 (Mono), but does not happen in 4.2.1 stable (Mono).

### System information

Godot v4.3.dev4.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3758) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

In previous versions, you could clear a RichTextLabel object's text field by doing:
label.Text = "";

Now in 4.3.dev4 this no longer works.  You can neither clear it with code, nor does deleting the text in the editor clear what is already there.  You instead now need to put a blank space to clear the existing text, like:
label.Text = " ";

### Steps to reproduce

Create a RichTextLabel, set some text.  Delete the text in the box and note that it hasn't deleted.  Then add a space and the text will disappear then.

In the sample project I uploaded, you can hit enter or space to change the text from code to test it.  You can also check the bool in the scene to switch to setting in code with a space, which now works.  Thank you.

### Minimal reproduction project (MRP)

[TestGame.zip](https://github.com/godotengine/godot/files/14584893/TestGame.zip)

**Comment by bruvzg** [comment]
Should be already fixed by https://github.com/godotengine/godot/pull/89100

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/89091

Which has been solved
