### ISSUE TITLE
shader uniform uint allows negative numbers in inspector panel

### ISSUE THREAD

**Issue by beterfysiek** [godotengine/godot#89436]
### Tested versions

Tested in 4.2 canvas_item shader

### System information

Godot v4.2.1.stable - macOS 14.3.0 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

`uniform uint unsigned_int = 1;`

unsigned_int cannot set to negative 'inside the shader' which is perfect. But the uniform allows to be to set to a negative integer 'inside the inspector panel', that's a bug. It can be set by typing and by using the decrement arrow.

### Steps to reproduce

1. create a Node2D scene
2. Add a `canvas_item` shader to the root node
3. add a uint uniform

```
shader_type canvas_item;
uniform uint unsigned_int = 1;
```

4. go to shader parameter
5a. type a negative number
5b. use arrows to decrease the number below 0

![Screenshot 2024-03-13 at 10 37 21](https://github.com/godotengine/godot/assets/22577709/ec8b638a-6c6e-4869-a3ea-129c89711c94)

### Minimal reproduction project (MRP)

1. create a Node2D scene
2. Add a `canvas_item` shader to the root node
3. add a uint uniform

```
shader_type canvas_item;
uniform uint unsigned_int = 1;
```

4. go to shader parameter
5a. type a negative number
5b. use arrows to decrease the number below 0

![Screenshot 2024-03-13 at 10 37 21](https://github.com/godotengine/godot/assets/22577709/ec8b638a-6c6e-4869-a3ea-129c89711c94)

**Comment by jsjtxietian** [comment]
The type for the info is `INT`:

![image](https://github.com/godotengine/godot/assets/8315986/22308ff9-4453-4bd5-a8ec-e4aa0a2900fc)

Can we somehow add a hint to this?

**Comment by AThousandShips** [comment]
We could add a range hint for it, at least if it's 32 bits

**Comment by AThousandShips** [comment]
Works or at least seems to, so will open a PR soon

**Comment by beterfysiek** [comment]
Great work!
