### ISSUE TITLE
All instances of a GLTF-inherited scene share state

### ISSUE THREAD

**Issue by RudyFisher7** [godotengine/godot#89431]
### Tested versions

4.2.1-stable

### System information

Windows 11, Compatibility

### Issue description

All instances of a GLTF-inherited scene share the same state.

### Steps to reproduce

Export a 3d model, rigged and animated as a glb from Blender.
Create a new inherited scene based on the imported glb file.
Add an AnimationTree and an AnimationNodeAnimation as the root animation node.
Attach a script that plays different animation based on player input, using logic to ensure only one instance should be playing at a time (an exported bool to toggle, for example).
Add debug prints to verify.

(See and run attached minimal reproduced project.)

### Minimal reproduction project (MRP)

[sumo_minimal_gltf.zip](https://github.com/godotengine/godot/files/14580473/sumo_minimal_gltf.zip)

**Comment by narcissawright** [comment]
I think just check Local to Scene on the AnimationTree and it will work.
![image](https://github.com/godotengine/godot/assets/49114816/f485a0cd-6349-4e2f-bc5a-c496358f73fc)

**Comment by RudyFisher7** [comment]
@narcissawright Thanks! It worked. Glad this was user error. I could have sworn I had tried before and it didn't work, but oh well, working now. Going to mark closed.
