### ISSUE TITLE
this engine is too bad

### ISSUE THREAD

**Issue by iamnotmega** [godotengine/godot#89445]
### Tested versions

no

### System information

GodotSucksOS

### Issue description

unity sucks

### Steps to reproduce

delete ur engine

### Minimal reproduction project (MRP)

no shit

**Comment by ryevdokimov** [comment]
Can't reproduce this issue. 

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)
