### ISSUE TITLE
Window resizing is difficult in android version

### ISSUE THREAD

**Issue by nacho00112** [godotengine/godot#89466]
### Tested versions

Godot editor 4 from play store

### System information

samsung a30 android 11

### Issue description

when I want to export my project to build it in my server the export window is so big that the export button is out of the screen, i can only resize horizontally, because the vertical borders are the ones out of the screen, I think there should be some sort of interface to make this easier

### Steps to reproduce

after you choose a preset the window gets bigger automatically, here the problem starts

### Minimal reproduction project (MRP)

any project is enough

**Comment by nacho00112** [comment]
it seems this issue is quite old here but still didn't got attention even though this make the android editor unusable: https://github.com/godotengine/godot/issues/73130

**Comment by akien-mga** [comment]
Indeed that's the same issue as #73130. Consolidating there to keep the discussion focused. Thanks for the report!
