### ISSUE TITLE
[Bug] GraphNode is created instead of Node if selected from Recent list

### ISSUE THREAD

**Issue by indiemaatheus** [godotengine/godot#8947]
**Windows 64bits - v2.1.3**

**Issue description:**
If you add a Node to a scene and select it via the _Recent_ list, it creates a GraphNode instead. Doesn't seem to happen with any other node.

http://i.imgur.com/e2zphKm.gif

**Steps to reproduce:**
Add a new node to a scene (CTRL+A), select Node from the _Recent_ list.

**Comment by bojidar-bg** [comment]
Can confirm.

**Comment by nunodonato** [comment]
can confirm in v3 too
