### ISSUE TITLE
Setting Rotation and GlobalPosition for Control causes runaway Position issues.

### ISSUE THREAD

**Issue by TinkerWorX** [godotengine/godot#89497]
### Tested versions

- Reproducible in: v4.3.dev4.mono.official [df78c0636]

### System information

Godot v4.3.dev4.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.5161) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 Threads)

### Issue description

Setting the GlobalPosition of a control while it's Rotation is non-zero can cause runaway issues with the controls position.

https://github.com/godotengine/godot/assets/1730988/437decae-d74f-44f8-83b3-3e18d1f12c01

### Steps to reproduce

In the repro, hold down left mouse button to see the issue happening.

### Minimal reproduction project (MRP)

[ControlPositionRotationBug.zip](https://github.com/godotengine/godot/files/14609095/ControlPositionRotationBug.zip)

**Comment by kleonc** [comment]
Regression from #87432, fix incoming.
