### ISSUE TITLE
StandardMaterial3D Distance Fade: Object Dither mode not working as expected (problem with model origin)

### ISSUE THREAD

**Issue by gmikhail** [godotengine/godot#89492]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 with Max-Q Design (NVIDIA; 31.0.15.5176) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I'm trying to make a third person character controller. I want that if the camera is very close to the character, it will become translucent. But when using `Distance Fade` in StandardMaterial3D, specifically the `ObjectDither` mode, it does not work like other modes (`PixelAlpha`, `PixelDither`).

**It looks like `ObjectDither` mode uses the origin of the model when calculating the distance to the camera. Which leads to incorrect display if the origin of the model is not in its center.**

Visual demonstration (all modes with the same settings, Min Distance = 0m, Max Distance = 2m):

![2024-03-14 213915](https://github.com/godotengine/godot/assets/4838367/92e6a4b5-8909-4a1e-a35f-244731552c2b)

https://github.com/godotengine/godot/assets/4838367/63b6d1df-517f-4db3-9bbf-3531505a83bb

https://github.com/godotengine/godot/assets/4838367/a45ef66b-a32b-4c6c-b231-62a42e2b95af

https://github.com/godotengine/godot/assets/4838367/b4e90d87-1575-446e-9173-49adbe342b5d

As you can see, only in `ObjectDither` mode when the camera flies above the player, the dithering effect does not occur because the origin of the model is not in its center, but below.

![2024-03-14 214355](https://github.com/godotengine/godot/assets/4838367/d00abbd1-60bd-4813-8f5a-9bd996c80d5f)

### Steps to reproduce

In attached example launch the scene, then in `World -> Player -> Visuals -> capsule -> Circle -> Surface Material Override` play with the `Distance Mode`.

![2024-03-14 215410](https://github.com/godotengine/godot/assets/4838367/d4b7db67-8519-47dc-929c-3e4997a0c30b)

Just in case, I attached a capsule model made in Blender with the required origin to reproduce the bug. The scene uses its local copy.

### Minimal reproduction project (MRP)

[StandardMaterial3D_ObjectDither.zip](https://github.com/godotengine/godot/files/14607339/StandardMaterial3D_ObjectDither.zip)

**Comment by clayjohn** [comment]
This isn't a bug. This is exactly what object dither does. The dithering is based on the distance from the camera to the origin of the object.

**Comment by gmikhail** [comment]
>The dithering is based on the distance from the camera to the origin of the object.

That's the problem. I understand that from a software point of view, such an implementation seems correct, but this is not what the user expects. **Because the origin point may be located outside the model geometry.** And in this case, object dithering does not work correctly (see attached videos in the first message).

Quote from the [Blender documentation](https://docs.blender.org/manual/en/2.80/scene_layout/object/editing/transform/control/pivot_point/individual_origins.html) that origin can be located outside the model:

>The origin does not have to be located in the center of the geometry (e.g. mesh). This means that an object can have its origin located on one end of the mesh or even completely outside the mesh.
>
>![scene-layout_object_editing_transform_control_pivot-point_individual-origins_rotation-around-center](https://github.com/godotengine/godot/assets/4838367/badea2f1-583f-4fee-9c6d-a5d7704bb27a)

Much more expected behavior for the user will be when the object dithering depends on the distance of the camera to the visible geometry. Like in pixel alpha/dither, but only so that it is applied evenly to the entire model.

**Therefore, please reopen this issue because Godot does not handle common standards properly.** Maybe not as a bug, but as an enhancement if you think it's more correct.

For example, in character models the origin is often placed at the bottom (see attached videos in the first message), and although the Godot documentation recommends using Object Dither to hide the character, in practice this does not work correctly.

[Godot documentation](https://docs.godotengine.org/en/stable/tutorials/3d/standard_material_3d.html):
>To hide a character when they get too close to the camera, consider using Pixel Dither or better, Object Dither (which is even faster than Pixel Dither).

**Comment by Calinou** [comment]
> Therefore, please reopen this issue because Godot does not handle common standards properly. Maybe not as a bug, but as an enhancement if you think it's more correct.

Feature proposals are tracked on https://github.com/godotengine/godot-proposals, so please open an issue there.
