### ISSUE TITLE
Global menu items on macOS are mirrored after PR 89273

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#89496]
### Tested versions

Latest master as of writing 0175be8948d68cf90c55ce08e8e5bf46ea29ce40 (4.3-dev)

### System information

macOS 14.3.1 M1 Pro

### Issue description

The global menu entries have their contents mirrored.

<img width="358" alt="Screenshot 2024-03-14 at 4 07 46 PM" src="https://github.com/godotengine/godot/assets/1646875/9e43c59a-4834-4435-ad24-f962ec39a000">

### Steps to reproduce

Open the editor to any project with the latest master.

If #89273 is reverted, the problem goes away.

### Minimal reproduction project (MRP)

N/A, this should happen with any project. You can make a MRP by running `mkdir test; cd test; touch project.godot`.

**Comment by akien-mga** [comment]
The condition just seems to be backward there:
https://github.com/godotengine/godot/pull/89273/files#diff-6e21fc598dffbc265b12379f8253d4950171fa0c99dda1dbb580c13d4eb1e25aR274
