### ISSUE TITLE
Convex decomposition of CollisionPolygon2D creates shapes without transforms

### ISSUE THREAD

**Issue by Technostalgic** [godotengine/godot#89494]
### Tested versions

Produced bug in Godot Version 4.2.1

### System information

irrelevant

### Issue description

Whenever you have a PolygonShape2D that has vertices aligned in such a way that convex decomposition must occur to create the sub-shapes, if you call `shape_owner_get_transform(i)` where `i` is the index of any convex polygon created in the convex decomposition process, there will be an assertion fail logged in the debugger:
```
E 0:00:00:0517   test.gd:6 @ _ready(): Condition "!shapes.has(p_owner)" is true. Returning: Transform2D()
  <C++ Source>   scene/2d/collision_object_2d.cpp:406 @ shape_owner_get_transform()
  <Stack Trace>  test.gd:6 @ _ready()
```
It still gives you a valid default Transform2D object, which works as intended because the convex decomposed parts still share the same transforms as their parent, but the assertion being logged in the console shows there is an issue that should be addressed

### Steps to reproduce

The issue can be reproduced with a simple script:

```gd
extends CollisionObject2D
func _ready():
	var shape_ct = shape_owner_get_shape_count(0)
	for i in range(0, shape_ct):
		# this line fails an assertion on 2 of the 3 shapes because (i assume) the convex 
		# decomposition of the polygon new convex polygon shapes that do not have transforms
		var shape_trans = shape_owner_get_transform(i)
		print_debug(shape_trans.get_origin())
```

and a scene setup with a concave PolygonShape2D with that script attached to it's parent collision object like so:
![image](https://github.com/godotengine/godot/assets/21109782/a4f26b18-5b5d-447c-bc33-46b593feaa59)

you will notice the assertion fails when the game is run:
![image](https://github.com/godotengine/godot/assets/21109782/3a3289b6-cd5c-42e9-851a-e076a4e35918)

### Minimal reproduction project (MRP)

[godot_bug_repro.zip](https://github.com/godotengine/godot/files/14608673/godot_bug_repro.zip)

**Comment by smix8** [comment]
The function `shape_owner_get_transform()` returns the transform of the shape owner, not the transform of the shapes. A shape is a `Resource`, it has no transform. The shape owner is the `CollisionPolygon2D` node instance.

**Comment by Technostalgic** [comment]
Ah yes, I see now. This is just a misunderstanding on my part
