### ISSUE TITLE
Text shadow causes stray shadow-colored pixels

### ISSUE THREAD

**Issue by CenTdemeern1** [godotengine/godot#89498]
### Tested versions

Not reproducible in Godot 2 & 3 because these features work differently
Reproducible in Godot 4.0 & 4.2.1

<details>
<summary>Godot 2</summary>

In Godot 2, you couldn't combine outlines and shadows effectively as far as I can tell
![Screenshot 2024-03-15 at 01 00 25](https://github.com/godotengine/godot/assets/24682280/201a352a-3f57-4657-b58b-74b44bb516d2)

</details>

<details>
<summary>Godot 3</summary>

In Godot 3, shadows were being applied before outlines
![Screenshot 2024-03-15 at 01 09 51](https://github.com/godotengine/godot/assets/24682280/99f239ea-6170-4d47-a5e1-eb0fd85a5520)

</details>

<details>
<summary>Godot 4.0</summary>

![Screenshot 2024-03-15 at 01 13 58](https://github.com/godotengine/godot/assets/24682280/814956ba-6cbf-4c91-8da4-9043419bb9e4)

</details>

<details>
<summary>Godot 4.2.1</summary>

(Edit: added cleaner 4.2.1 screenshot)
![Screenshot 2024-03-15 at 01 26 56](https://github.com/godotengine/godot/assets/24682280/156dc06b-60d4-4ce2-8021-82729eaed2db)

</details>

### System information

Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

On labels with a text shadow greater than or equal to the outline size (must be >= 1) with the shadow directly below the text, odd gaps/stray pixels are visible.

![Screenshot 2024-03-14 at 22 35 55](https://github.com/godotengine/godot/assets/24682280/be478bd0-24ef-4bd8-beea-6b2207cf62ce)

# Here's what it should look like instead (expected behavior)

![Screenshot 2024-03-15 at 00 41 04](https://github.com/godotengine/godot/assets/24682280/98f9a2d0-9821-4ef7-9000-2c009d71bd40)

### Steps to reproduce

Load the provided MRP.

### Minimal reproduction project (MRP)

[TextShadowRepro.zip](https://github.com/godotengine/godot/files/14608928/TextShadowRepro.zip)

**Comment by akien-mga** [comment]
CC @bruvzg
