### ISSUE TITLE
reminder/fr: add missing dependency resolver

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#895]
In case of missing dependency (e.g. scene is missing some external resources or subscenes)
it is nicer to ask user where these might be and report the problem (but still allowing to proceed without
these, just making sure user knows what is missing). Should help when messing around files.

**Comment by akien-mga** [comment]
I'm not sure sure I understand the request 100%, but isn't there already such a system? Or does it only handle files *modified* outside the editor but not missing files?

**Comment by akien-mga** [comment]
There is a dependency resolver in 2.0.
