### ISSUE TITLE
Exporting Windows build as zip with 'Embed PCK' on, causes the exe to be missing from the zip

### ISSUE THREAD

**Issue by ana-rchy** [godotengine/godot#89501]
### Tested versions

4.2.stable

### System information

Godot v4.2.1.stable.mono - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (nvidia; 550.54.14) - AMD Ryzen 5 7600X 6-Core Processor (12 Threads)

### Issue description

exporting a windows build, with 'embed pck' on, and as a zip, causes the exe to be missing from the resulting zip

this cost me a game jam entry...

### Steps to reproduce

1. select windows desktop build
2. enable 'embed pck'
3. export as .zip

### Minimal reproduction project (MRP)

N/A

**Comment by MrPersonDev** [comment]
If you are referring to "Export PCK/ZIP...":

![image](https://github.com/godotengine/godot/assets/83386224/e4557308-69ee-41c5-88a2-ff8aa125e0ad)

This exports just the .pck file for the project, not the executable.

You can read more about this here: https://docs.godotengine.org/en/stable/tutorials/export/exporting_pcks.html

**Comment by ana-rchy** [comment]
> If you are referring to "Export PCK/ZIP...":
> 
> ![image](https://private-user-images.githubusercontent.com/83386224/313051359-e4557308-69ee-41c5-88a2-ff8aa125e0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzE2MDQsIm5iZiI6MTcxMDQ3MTMwNCwicGF0aCI6Ii84MzM4NjIyNC8zMTMwNTEzNTktZTQ1NTczMDgtNjllZS00MWM1LTg4YTItZmY4YWExMjVlMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDAyNTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1Y2E2MWNmMjAwNzQxYTIzMDU1NDA1NzhhMmVmMmRhMDhlODkyNDhlNGUwNmI3MDE3Y2ZlN2YxODc0YjVmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJ7RFeApZGJfa9VyjH-U92lSUK0lUyvKHScMZW-CAnA)
> 
> This exports just the .pck file for the project, not the executable.
> 
> You can read more about this here: https://docs.godotengine.org/en/stable/tutorials/export/exporting_pcks.html
> 
> Perhaps this option could be given a clearer name.

im talking about the 'export project' option, works just fine for linux builds and it doesnt leave out the .x86 there

**Comment by MrPersonDev** [comment]
Oh, I see. I can reproduce this bug.
What is very strange is that when exported with 'Export With Debug' enabled, this is not the case.

**Comment by akien-mga** [comment]
CC @bruvzg
