### ISSUE TITLE
Crash on viewport display menu: View/Settings

### ISSUE THREAD

**Issue by braedenf** [godotengine/godot#8950]
**Operating system or device - Godot version:**
Operating system: Mac OS Sierra 10.12.1
Godot Version: Latest master build

**Issue description:**

On the top menu bar of the viewport under View/Settings Godot crashes. 

![screen shot 2017-05-27 at 4 44 54 pm](https://cloud.githubusercontent.com/assets/7875817/26518104/ddd15f6e-42fc-11e7-833c-081c1d6799b2.png)

**Comment by nunodonato** [comment]
Safe to close, this is a duplicate of #8489

**Comment by bojidar-bg** [comment]
Yeah, closing as dupe of #8489.
