### ISSUE TITLE
Crash when draggin saved animation.tres to AnimationMixer from AnimationPlayer

### ISSUE THREAD

**Issue by conde2** [godotengine/godot#89515]
### Tested versions

v4.3.dev4.mono.official [df78c0636]

### System information

Godot v4.3.dev4.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

When trying to drag and drop a .tres in the animation mixer godot crash.

![image](https://github.com/godotengine/godot/assets/2137569/b89538c8-6114-4606-8455-89d72af8a1e2)

### Steps to reproduce

Just drag and drop the file there, godot will crash. What I was trying to do is saving a TRES using the RMB (Right Mouse Button) on the Animation Mixer Librarie to reuse it later, so I Save As the TRES and after I tried to load it again, and it crashed.

![image](https://github.com/godotengine/godot/assets/2137569/303a83fb-2d0c-49aa-a5a4-76c2c26f8e9f)

To crash just drag and drop the .TRES there like so:

![image](https://github.com/godotengine/godot/assets/2137569/b89538c8-6114-4606-8455-89d72af8a1e2)

### Minimal reproduction project (MRP)

[bug_anim.zip](https://github.com/godotengine/godot/files/14616291/bug_anim.zip)

**Comment by jsjtxietian** [comment]
https://github.com/godotengine/godot/assets/8315986/16d8bce6-8360-4b99-b997-b2cc684f5819

**Comment by jsjtxietian** [comment]
Am I doing it right? I can not reproduce this issue, but it feels extremely laggy —— Godot v4.3.dev (fe01776f0) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)


https://github.com/godotengine/godot/assets/8315986/1d4cfc94-c813-4f09-aa23-036efdb912dd

**Comment by conde2** [comment]
Try dragging where it says dictionary.

**Comment by jsjtxietian** [comment]
It won't let me drag in


https://github.com/godotengine/godot/assets/8315986/71c0e866-8496-4ed8-8d48-f606a7f82b14

**Comment by conde2** [comment]
Looks like it has been fixed in the lastest version dev5, thanks very much.
