### ISSUE TITLE
[4.3 dev 5] Help menu is not displayed correctly

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#89535]
### Tested versions

this happens in 4.3 dev 5, before this the problem was not observed

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When you click on the help menu, the menu does not look the same, also if you click outside the menu area, the button will still remain highlighted

4.3 dev 4:
![bugHelp4 3dev4](https://github.com/godotengine/godot/assets/130399274/c3cd4d08-a6ba-45c2-9ca9-8821e6c71bf3)

4.3 dev 5: 
![bugHelp](https://github.com/godotengine/godot/assets/130399274/09bad0f6-887d-4b23-bd4a-89365ba051d9)

### Steps to reproduce

click on help menu

### Minimal reproduction project (MRP)

.

**Comment by AThousandShips** [comment]
Sounds related to native menus, so:
* https://github.com/godotengine/godot/pull/89273

CC @bruvzg
