### ISSUE TITLE
Incomplete Apache 2.0 license text returned from Engine.get_license_info()

### ISSUE THREAD

**Issue by matmas** [godotengine/godot#89548]
### Tested versions

Reproducible in:
- v3.5.3.stable.official [6c814135b]
- v4.2.1.stable.arch_linux
- v4.3.dev5.official [c9c17d6ca]

### System information

Godot v4.3.dev5 - EndeavourOS #1 SMP PREEMPT_DYNAMIC Fri, 08 Mar 2024 01:59:01 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 550.54.14) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

`Engine.get_license_info()` returns incomplete version of Apache 2.0 license. See https://github.com/godotengine/godot/blob/c9c17d6ca/COPYRIGHT.txt#L567-L578 for the actual text being returned. Apache 2.0 is the only license not included in full, the others seem complete.

Example of a full Apache 2.0 license: https://github.com/godotengine/godot/blob/c9c17d6ca/thirdparty/astcenc/LICENSE.txt

I am not a lawyer.

### Steps to reproduce

Run the reproduction project to see the license

Or just run:
```
printerr(Engine.get_license_info()["Apache-2.0"])
```

### Minimal reproduction project (MRP)

[apache-2.0-license-viewer.zip](https://github.com/godotengine/godot/files/14621815/apache-2.0-license-viewer.zip)

**Comment by clayjohn** [comment]
This appears to be how they recommend citing it (see here https://www.apache.org/licenses/LICENSE-2.0). Is there any reason to think that is insufficient?

**Comment by matmas** [comment]
I found a related discussion on this topic here: https://github.com/licensee/licensee/issues/82#issue-132772719
and https://github.com/licensee/licensee/issues/103

To me it seems that Godot is using boilerplate version intended mainly for source file headers where long text is not practical.

Whether using this version for `Engine.get_license_info()` is sufficient or not would probably depend on use cases of this function.

My use case was to display license information to the end user to read in a game menu UI.

I am not sure if displaying boilerplate version of the license there is sufficient or not (not being a lawyer) but for the sake of consistency it might be better to have all licenses returned from `Engine.get_license_info()` be in full.

Note that `Engine.get_license_info()` already contains CC-BY-4.0 license which is even longer (309 lines) compared to full Apache-2.0 (173 lines).
