### ISSUE TITLE
Godot crashes when profiler graph is clicked

### ISSUE THREAD

**Issue by mcanders** [godotengine/godot#8954]
The wrong input event variable is referenced on line 526 of editor_profiler.cpp and godot segfaults as a result.  This was broken when @reduz made his recent InputEvent changes.  Based on the old version of the code, it looks like the "mb" variable should be "mm".  Using the correct variable restores the old behavior.  I will be putting out a pr shortly.

Related to issue #8938.

**Comment by akien-mga** [comment]
Fixed by #8956.
