### ISSUE TITLE
History Editor comes back when disabled

### ISSUE THREAD

**Issue by moodster321** [godotengine/godot#89549]
### Tested versions

4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 11.7.10 - Vulkan (Forward+) - integrated Intel(R) Iris(TM) Plus Graphics - Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 Threads)

### Issue description

I was trying to move all the editor windows to the left for more room to code, didn't think I needed the history available all the time so I tried removing it by making a profile, but it comes back (also when all the editors are removed from the right side there is a big gap left there instead of the code editor expanding to fill the space) I saw a few other related issues that were marked as completed/merged, wasn't sure if I'm supposed to make a new issue or comment on those.

### Steps to reproduce

-move all editors except history on the right side to the left
-remove the history editor from view by managing the editor feature profile
-move any other editor window to another space
-the history window pops back up and will not leave until you enable then disable it again

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- This is fixed in 4.2.2 and 4.3 in https://github.com/godotengine/godot/pull/84122
