### ISSUE TITLE
[4.3.dev5] Lost UI sharpness on Linux 

### ISSUE THREAD

**Issue by rsau** [godotengine/godot#89541]
### Tested versions

- Reproducible on v4.3.dev5.official [c9c17d6ca]
- Working fine on v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.dev5 - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Mobile) - dedicated AMD RADV POLARIS10 () - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

UI icons have lost some sharpness. It looks like they have been scaled up by a very small amount as well. 

Please check following UI elements in screenshot below to get idea. Project name has version info in screenshot 
- Add Child Node 
- Instantiate Child Scene
- Attach/Detach script 
- 2D, 3D, Script, AssetLib icons and text
- Toolbar to run project and scenes

![image](https://github.com/godotengine/godot/assets/29110027/292709a2-fc80-43fc-b588-4f9d8edf198f)

### Steps to reproduce

Open a new project in both versions and compare

### Minimal reproduction project (MRP)

Please create a default project in both versions

**Comment by Maran23** [comment]
Might be the same as https://github.com/godotengine/godot/issues/88165

**Comment by akien-mga** [comment]
Indeed, consolidating in #88165.
