### ISSUE TITLE
The problem of black edges and stretched images on an Android device 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#89569]
### Tested versions

4.2.1

### System information

Android / Mobile

### Issue description

The problem is when I do it in the project settings and go to windows and activate the size that works on all devices, as in the first image there are black edges and the image becomes stretched or stretched. Even the words in the image are stretched or stretched. I hope that there are no black edges and the image is stretched. I want to The size is for all devices, but the image is not stretched or stretched, as in the following images 
![٢٠٢٤٠٣١٦_١٦٠٨٥٦](https://github.com/godotengine/godot/assets/153130532/b2db385e-01e0-475d-a913-30062aeb42c5)
![٢٠٢٤٠٣١٦_١٦١٠٠٧](https://github.com/godotengine/godot/assets/153130532/6ddafbc5-40c3-4a9e-b077-519dc29cf5f5)
![Screenshot_٢٠٢٤٠٣١٦-١٦٠٣٤٧](https://github.com/godotengine/godot/assets/153130532/9d747417-0f75-4bd9-92a9-09d0eae79b1f)

### Steps to reproduce

/Open the project, go to settings, go to windows, do as you did in the first image, add an image sized like the size of the second image above, open the scene, and you will find the problem of black edges and the stretched or stretched image (note: black edges only in Android devices and phones) 

### Minimal reproduction project (MRP)
I want it to be like PUBG Mobile For example, the PUBG list is not extended and is suitable for all devices. For example, it is square in PUBG, not extended, and there are no black edges. In my project, it is extended and there are Black edges I hope to solve it thank you

**Comment by AThousandShips** [comment]
You already opened an issue for the black edges, what's different in this issue? Please don't open new issues for the same problem

**Comment by Sorshx** [comment]
Elongated screen

**Comment by AThousandShips** [comment]
The black edges are in both, and the same screenshots, what is different?

**Comment by Sorshx** [comment]
The problem was not solved

**Comment by AThousandShips** [comment]
And you opened a new one after 5 days because of that?

Please *do not* do that, I'm closing this as a duplicate and you should update the other issue, and please have patience

**Comment by Sorshx** [comment]
Good
