### ISSUE TITLE
`EditorNode3DGizmo::_is_handle_highlighted` loop index passed as handle id 

### ISSUE THREAD

**Issue by Getriebe** [godotengine/godot#89581]
### Tested versions

v4.2.dev.custom_build [bfd78bb91]

### System information

W10

### Issue description

The member function ```EditorNode3DGizmo::_is_handle_highlighted``` is called with the loop index instead of the handle id, See https://github.com/godotengine/godot/blob/master/editor/plugins/node_3d_editor_gizmos.cpp#L407.
This leads to a discrepancy when comparing it to a custom (internal) highlighted id, saved in ```EditorNode3DGizmo::_get_handle_value```, because the actual handle id, as set by ```EditorNode3DGizmo::_redraw```, is passed there.

### Steps to reproduce

See example code below.

```gdscript
extends EditorNode3DGizmo

func _redraw():
	clear()
	var handles := [Vector3(1,1,1)]
	var handle_ids := [123]
	var material := StandardMaterial3D.new()
	var handle_t : CompressedTexture2D = load("res://icon.svg")
	material.albedo_texture = handle_t
	material.use_point_size = true
	material.point_size = handle_t.get_width()
	material.billboard_mode = BaseMaterial3D.BILLBOARD_ENABLED
	material.vertex_color_use_as_albedo = true
	add_handles(handles, material, handle_ids)

func _is_handle_highlighted(id, secondary):
	return id == 123 # False
```

### Minimal reproduction project (MRP)

[TestGizmo.zip](https://github.com/godotengine/godot/files/14624635/TestGizmo.zip)

**Comment by AThousandShips** [comment]
Should be a trivial fix, will open a PR

**Comment by mohsenph69** [comment]
I have the same problem! is there any news about this?

**Comment by AThousandShips** [comment]
Please don't bump without contributing significant new information. Use the :+1: reaction button on the first post instead.

There's a PR open for this that is waiting for approval, as you can see above
