### ISSUE TITLE
Editor crash when making Multimesh with use_colors turned on unique

### ISSUE THREAD

**Issue by alhimik12** [godotengine/godot#89583]
### Tested versions

- Reproducible in: 4.2.1stable, 4.1.1stable, 4.2.2.rc2

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

the editor crashes when i try to make unique multimesh with use_colors in it set to true. expected editor to not crash so that i could both use colors and have different instance_count values on different instances of one multimeshinstance2d node at the same time

### Steps to reproduce

1. create MultiMeshInstance2D or MultiMeshInstance3D
2. create new Multimesh resource in it
3. in Multimesh set use_colors to true
4. right click Multimesh and press "make unique"

after these steps editor should crash

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can you please try this in [4.2.2.rc2](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/)? This sounds familiar and might be solved.

**Comment by alhimik12** [comment]
crashes on 4.2.2.rc2 too

**Comment by alhimik12** [comment]
crashes on 4.2.2.rc2 too

**Comment by kleonc** [comment]
Crashes in v4.3.dev1.official [9d1cbab1c].
Fixed since v4.3.dev2.official [352434668]. Not sure by which PR (and hence whether it's some small change which could be cherry-picked to 4.2).

**Comment by akien-mga** [comment]
Closing as fixed in 4.3.

If someone can identify which commit fixed it in 4.3.dev2 ([changelog](https://godotengine.github.io/godot-interactive-changelog/#4.3-dev2)), that'd be great so that we can cherry-pick it to 4.2.x.
