### ISSUE TITLE
Live reload does not work with class member variables

### ISSUE THREAD

**Issue by Jackyjjc** [godotengine/godot#8959]
**Operating system or device - Godot version:**
OS: Windows 10
Godot version: 2.1.3

**Issue description:**

I have this bit of code and I was changing the value of the speed variable using the live reload feature. The script got reloaded but the the speed did not change:
```
var speed = 300;

func _fixed_process(delta):
	...
	var motion = move_direction.normalized() * speed * delta
	move(motion)
```

**Steps to reproduce:**

**Link to minimal example project:**

[testgo.zip](https://github.com/godotengine/godot/files/1033557/testgo.zip)

**Comment by Zylann** [comment]
There is a problem with this:

```gdscript

var object = null

func _ready():
	object = SomeObject.new()
	set_process(true)


func _process(delta):
	object.do_stuff()
```

What should happen if you hot-reload this script?
If you expect a member variable to reload, you will get `object == null`, and the script will crash.

**Comment by vnen** [comment]
If you do `export var speed = 300` and change it via editor it works (if `Sync Scene Changes` is also active). For this particular case, I find it a better and more predictable workflow.

**Comment by Jackyjjc** [comment]
Make sense! Sorry I'm new to this engine and haven't gotten familiar with all the nuances. Thank you for the explanation and suggestions. I will make it visible in the editor instead :)
