### ISSUE TITLE
Editor window is scaled using nearest neighbour when moving window to lower DPI monitor

### ISSUE THREAD

**Issue by semirix** [godotengine/godot#89601]
### Tested versions

- 4.2.1
- 4.3.dev4
- 4.3.dev5

### System information

MacOS Sonoma 14.3.1, Macbook Pro M2 Max

### Issue description

I have an ultra-wide 3440x1440 monitor connected to my M2 Max Mac Pro. When I move the editor window to the ultra wide which has a lower DPI it resizes the window using nearest neighbour which aliases horribly. This behaviour does not occur in 4.2.1. I've attached a video to demonstrate.

https://github.com/godotengine/godot/assets/7454145/2a8249a6-e397-4fdc-96d8-3e6461d48727

### Steps to reproduce

- Connect a monitor with a lower DPI than the primary.
- Move the editor window between the two monitors.

### Minimal reproduction project (MRP)

N/A

**Comment by semirix** [comment]
This is still present in 4.3.dev6

**Comment by akien-mga** [comment]
Thanks for the report.

This sounds similar to other existing issues but I couldn't find them with a quick search, maybe @bruvzg would know more.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/89019.
