### ISSUE TITLE
switch case fallthrough crash shader language

### ISSUE THREAD

**Issue by beterfysiek** [godotengine/godot#89605]
### Tested versions

Godot 4.2

### System information

Godot v4.2.1.stable - macOS 14.3.0 - GLES3 (Compatibility) - Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

Copy paste the documentation example about switch case inside a canvas_item shader. ad a 1 as argument, place it inside the fragment function and remove the return. It will instantly crash because of the "// Fallthrough (no `break` or `return`): will run the next `case`." line.

```
// `switch`.
switch (1) { // `i` should be a signed integer expression.
    case -1:
        break;
    case 1: // Fallthrough (no `break` or `return`): will run the next `case`.
    case 2:
        break;
    //...
    default: // Only run if no `case` above matches. Optional.
        break;
}
```

### Steps to reproduce

Copy paste the documentation example about switch case inside a canvas_item shader. ad a 1 as argument, place it inside the fragment function and remove the return. It will instantly crash because of the "// Fallthrough (no `break` or `return`): will run the next `case`." line.

```
// `switch`.
switch (1) { // `i` should be a signed integer expression.
    case -1:
        break;
    case 1: // Fallthrough (no `break` or `return`): will run the next `case`.
    case 2:
        break;
    //...
    default: // Only run if no `case` above matches. Optional.
        break;
}
```

### Minimal reproduction project (MRP)

Open a new project with a Node2D
Add a shader material and a shader to the root node
copy paste this logic (which is from documentation of gdshader language)

```
shader_type canvas_item

void fragment() {
// `switch`.
switch (1) { // `i` should be a signed integer expression.
    case -1:
        break;
    case 1: // Fallthrough (no `break` or `return`): will run the next `case`.
    case 2:
        break;
    //...
    default: // Only run if no `case` above matches. Optional.
        break;
}
}
```

**Comment by Chaosus** [comment]
What do you mean by crash? Does it mean the editor shutdown due to a bug, inside the shader editor parser? I did not see any crash on Windows11/Godot 4.2.1, also you forgot to add a semicolon after `shader_type canvas_item` in your example.

**Comment by beterfysiek** [comment]
Tried it again and I also can't reproduce it anymore. The total editor crashed this morning. Guess it was some kind of hiccup or I overlooked something else. My bad I will remove the ticket. Thanks for your time.
