### ISSUE TITLE
Part of UI widget dragged with sprite when moving camera

### ISSUE THREAD

**Issue by sgt** [godotengine/godot#89603]
### Tested versions

- Reproducible in 4.2.1, 4.2.2-rc2, 4.3-dev5 
- Not reproducible when using Compatibility rendering

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) HD Graphics 620 (Intel Corporation; 30.0.100.9865) - Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 Threads)

### Issue description

A graphical element of the first UI widget on a CanvasLayer is dragged together with the underlying Sprite when the Camera2D is moved. Examples: when the element is a Button, its background is dragged away, when it's a Label, its first letter is dragged away.

### Steps to reproduce

- Create a Sprite, a CanvasLayer and a Camera2D
- Put a UI element (a button, for example) on the CanvasLayer
- Change the camera's position
- Observe a part of the UI element "dragged away" together with the sprite

### Minimal reproduction project (MRP)

[godot-canvas-ui-trouble-0.0.1.zip](https://github.com/godotengine/godot/files/14627032/godot-canvas-ui-trouble-0.0.1.zip)

**Comment by sgt** [comment]
@AThousandShips This is not an editor issue, it's rendering-related. This happens in the game itself.

**Comment by AThousandShips** [comment]
My bad, your use of "dragged" was confusing, as was "widget" :)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/58314
