### ISSUE TITLE
when I change a scale of a instantiated scene be black

### ISSUE THREAD

**Issue by omarfrinjary** [godotengine/godot#89600]
### Tested versions

 4.2.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1650 () - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

When I change a scale using script for a instantiated scene the faces that changed his scale his color be black

https://github.com/godotengine/godot/assets/140391368/b2080054-9bb2-4b09-ac0b-e7612102fd5e

### Steps to reproduce
1. making a scene 
2. making a packed_scene and exported
3. adding the scene into this variable
4. instantiating it
5. changing scale
6. rendering it but when we render it become black

### Minimal reproduction project (MRP)
[HSS.zip](https://github.com/godotengine/godot/files/14861062/HSS.zip)
in this file it has a script folder in this folder it has a script called generator in this script it has a function called render list this is a terrain generator function from the data from arrays it has a function called render_wall this be rendered because when the terrains instantiated it make a space in y axis so it scale the wall and place it but when it scale his color be black

**Comment by AThousandShips** [comment]
> I didn't understand what I will do here

You need to make a project to show this problem, and upload it

**Comment by omarfrinjary** [comment]
I added the zip file and a video describe the issue
