### ISSUE TITLE
Godot (C#) source build frequently crashes on launch

### ISSUE THREAD

**Issue by jonathansty** [godotengine/godot#89610]
### Tested versions

Builds tested:
- Godot Engine v4.3.dev.mono.custom_build.fe01776f0: display frequent crashes on loading project
- Godot Engine v4.3.dev.custom_build.fe01776f0: no issues
- Release candidate v4.3-dev5-mono-win64: no issues
- Godot Engine v4.2.2.rc.mono.custom_build.c61a68614: synced to 4.2 tag and rebuild and this one does not have the issue.

### System information

Windows 11 23H2 - Godot Engine v4.3.dev.mono.custom_build.fe01776f0 (2024-03-16 12:12:53 UTC)

### Issue description

Any custom build I produce locally on my own machine does not reliably launch the editor into a project. Loading up the project manager works fine but as soon as I attempt to load any project the editor occasionally just randomly closes. I did attempt to run dev builds and debug this locally but this issue does not happen when I compile with `dev_build=yes`

I tried forcing symbols on non dev builds by using `debug_symbols=yes` and managed to attach to it but this didn't really help me much as the locations where these crashes were happening changed everytime I tried debugging it. Not sure if this is due to optimization being applied or legit some corruption happening (like a memory stomp).

At first I thought this might have been some of my own changes, however I synced back to the main branch and retried this with an empty project and still get this issue.

I've attached the output I get when running with `--verbose --editor --path <my_project>`. After the last line the editor is not running anymore.

[Godot Engine v4.3.verbose.output.txt](https://github.com/godotengine/godot/files/14627604/Godot.Engine.v4.3.verbose.output.txt)

### Steps to reproduce

1. Follow build steps on [Compiling with dotnet](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_with_dotnet.html)
2. Create an empty project with a `project.godot` file.
3. Run `bin/godot.windows.editor.x86_64.mono.exe --verbose --editor --path <path_to_empty_project>` 

### Minimal reproduction project (MRP)

N/A

**Comment by jonathansty** [comment]
I've been doing some bisecting and testing this. Started from the 4.2.1-stable tag which doesn't have the issue. 

I ended up finding that the last working change was 3cac01034480dcb114a7becd7892d005627b45fd. 
The change after (eccdf1a1e8a972b40d507321b925d756a50c2a9d) has the crash issue.

**Comment by Sauermann** [comment]
CC @dalexeev
