### ISSUE TITLE
Overwriting a scene that is in use crashes Godot and corrupts the scene

### ISSUE THREAD

**Issue by crimsonhawk47** [godotengine/godot#89616]
### Tested versions

- v4.2.stable.official [46dc27791]

### System information

M1 Macbook Pro 16 inch - MacOS Sonoma Version 14.1 (23B74)

### Issue description

I had a "worldmap" scene. The top node was a TileSet and I didn't want it to be the parent. I wanted it (and other things) to be children of a blank node. 

So I made a new scene, copy pasted those things over, and then I saved the new scene over the old `worldmap`. Godot crashed. When I opened it, it said `worldmap` couldn't be found, even though I could see it and was going through the "Fix Dependencies" workflow. 

I believe what's happening is the scene mostly overwrites fine, but the tileset is referencing stale resources. When I open up the scene in a text editor, there's a lot of missing info for the tileset node. 

### Steps to reproduce

- Work on a scene with a tileset as the parent. Put down some tiles. 
- Make another scene (scene2)
- Have them both open. Save scene 2 over scene 1

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can you try this in 4.2.1? Or [4.2.2.rc2](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/)? 4.2 is outdated :)

**Comment by crimsonhawk47** [comment]
I actually can't recreate it now. Not sure how it happened before.

**Comment by crimsonhawk47** [comment]
Here is the unparseable script. It seems to also be importing itself? 

```
[gd_scene load_steps=2 format=3 uid="uid://bj374thgkat64"]

[sub_resource type="NavigationPolygon" id="NavigationPolygon_lyp1e"]
vertices = PackedVector2Array(246, 234, 278, 234, 278, 346, 74, 374, 310, 346, 310, 374, 74, 38, 246, 10, 10, 10, 10, 38)
polygons = Array[PackedInt32Array]([PackedInt32Array(0, 1, 2, 3), PackedInt32Array(2, 4, 5, 3), PackedInt32Array(0, 3, 6, 7), PackedInt32Array(8, 7, 6, 9)])
outlines = Array[PackedVector2Array]([PackedVector2Array(0, 0, 256, 0, 256, 224, 288, 224, 288, 336, 320, 336, 320, 384, 64, 384, 64, 48, 0, 48)])
source_geometry_group_name = &"navigation_polygon_source_group"

[node name="Node2D" type="Node2D"]

[node name="TileMap" parent="." instance=ExtResource("1_d3bwg")]

[node name="NavigationRegion2D" type="NavigationRegion2D" parent="."]
navigation_polygon = SubResource("NavigationPolygon_lyp1e")
```

**Comment by AThousandShips** [comment]
Sounds like a specific error to your project and not an error of the editor then, unless you can replicate it again in a fresh project

**Comment by crimsonhawk47** [comment]
Can't for now, you can close this if you want

**Comment by AThousandShips** [comment]
Feel free to comment here if you can replicate it later :) thank you for reporting
