### ISSUE TITLE
Missing option in contextual menu of the bottom section of the `FileSystem` dock

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#89637]
### Tested versions

- v4.3.dev.custom_build [fe01776f0]
- v4.3.dev4.official [df78c0636]

### System information

linux

### Issue description

When right-clicking an *empty* section of the `FileSystem` dock's lower half (in split mode), the popup menu is missing the last `open in terminal` option.

| upper half (folder tree)                                                                                   | empty space on files half                                                                         |
|-----------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|
| ![image](https://github.com/godotengine/godot/assets/71937306/019bb270-84ca-45d7-b964-5561124d6934) | ![image](https://github.com/godotengine/godot/assets/71937306/064ccf88-a8a0-43e0-a260-76f9c4e1c1b1) |

- it only happens on the menu for when an empty space is clicked,
- it only happens when clicking in the "files" half of the *split view*: the tree-only view works correctly.

### Steps to reproduce

right click on an empty space in the `FileSystem` tab in split mode 

### Minimal reproduction project (MRP)

any

**Comment by kitbdev** [comment]
It's not cut off, it looks like the bottom half of the split mode just doesn't have an `Open in Terminal` option. I'm not sure why this is the case though.
![image](https://github.com/godotengine/godot/assets/10054226/debc2bcc-c079-4c4b-baf2-d0d967f2f297)

**Comment by AThousandShips** [comment]
I think I have a solution, will update
