### ISSUE TITLE
Increasing the size of  `code_completion_prefixes` in `CodeEdit` through inspector returns `Code completion prefix cannot be empty`

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#89685]
### Tested versions

Godot v4.3.dev5

### System information

 TUXEDO OS 2 22.04.4 - X11 - Vulkan (Forward+) - integrated AMD Radeon R7 Graphics (RADV KAVERI) () - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

I was experimenting with the `CodeEdit` node today and when I tried to add an element to the `code_completion_prefixes` through the inspector, i got this error:

![image](https://github.com/godotengine/godot/assets/94475453/b7f2437e-8de4-4a4a-a8fc-25fae8354803)
I m not sure if this is an intended error or a bug. 

### Steps to reproduce

- Add `CodeEdit` Node to a scene
- Increase the `code_completion_prefixes` property through inspector or click `Add Element` button
- You will see the error without anything happening

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/83896
