### ISSUE TITLE
ColorRect with clipping enabled and panel as child renders the screen texture onto it

### ISSUE THREAD

**Issue by jefvel** [godotengine/godot#89689]
### Tested versions

- Reproducible v4.3.dev5.official [89f70e98d]

### System information

Windows 11

### Issue description

When setting a color rect to clip mode, and adding a panel to it as a child, it will render the whole game screen texture onto it.

![image](https://github.com/godotengine/godot/assets/494817/a44ad60c-67fd-4525-ac6e-75ca0f14ab5a)

### Steps to reproduce

Create a 2D scene, add some sprites and stuff to it. Add a ColorRect and set the clip to clip only. Add a panel to it as a child. It will render the screen with sprites added to the scene.

### Minimal reproduction project (MRP)

[weird_viewport.zip](https://github.com/godotengine/godot/files/14657231/weird_viewport.zip)

**Comment by Andre-Tita** [comment]
While working on this realized that it only happens when using Mobile Renderer.

https://github.com/godotengine/godot/assets/151757270/544a26bb-ae75-42d2-b651-c34c65aebad0
