### ISSUE TITLE
Area2D's input_event signal doesn't work on Android in v4.3.dev5.official [89f70e98d] and master [fe01776]

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#89683]
### Tested versions

- Reproducible in v4.3.dev5.official [89f70e98d] and master [fe01776f05b1787b28b4a270d53037a3c25f4ca2]
- Not reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 - Godot 4.3.dev5/master - Forward+ (Vulkan)

### Issue description

Area2D's input_event signal doesn't work on Android in v4.3.dev5.official [89f70e98d] and master.
Works fine in 4.2.1.

### Steps to reproduce

1. Create a new project in latest master or 4.3.dev5.
2. Add a Node2D as root node.
3. Add a simple Label for debugging.
4. Add Area2D with CollisionShape2D. Set it's size.
5. Add script to Area2D and connect `input_event` signal to a new function.
6. Set text of Debug Label in this new function.
7. Install and setup Android templates.
8. Test locally and see it work.
9. One-click deploy to an Android phone.
10. No inputs are detected.

### Minimal reproduction project (MRP)

- Reproducible MRPs:
	- v4.3.dev5.official [89f70e98d] - [Area2DInputTestAndroid-4.3-dev5.zip](https://github.com/godotengine/godot/files/14654874/Area2DInputTestAndroid-4.3-dev5.zip)
	- master [fe01776f05b1787b28b4a270d53037a3c25f4ca2] - [Area2DInputTestAndroid-4.3-master.zip](https://github.com/godotengine/godot/files/14654884/Area2DInputTestAndroid-4.3-master.zip)
- Not reproducible MRPs:
	- v4.2.1.stable.official [b09f793f5] - [Area2DInputTestAndroid.zip](https://github.com/godotengine/godot/files/14654891/Area2DInputTestAndroid.zip)

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/89641

**Comment by Anutrix** [comment]
> Sounds like:
> 
>     * [physics_object_picking_first_only breaks mouse enter/exit/motion events #89641](https://github.com/godotengine/godot/issues/89641)

Looks similar but not sure why it's only seen when exporting to Android in my case.
Will test the MR linked in that ticket when I can.

**Comment by Anutrix** [comment]
MR https://github.com/godotengine/godot/pull/89643 linked to issue https://github.com/godotengine/godot/issues/89641 does not fix my issue.
Tested the changes locally. My issue is still reproduced on Android export(both with and without both `set_physics_object_picking_*` flags enabled) so this is probably a different issue.

**Comment by Anutrix** [comment]
Tested some more and found that all 5 CollisionObject2D(inherited by Area2D) signals don't work on Android. Not just  `input_event` signal.
It also affects StaticBody2D which inherits PhysicsBody2D(that inherits CollisionObject2D like Area2D).

**Comment by Anutrix** [comment]
Finally found it after debugging it by adding and removing `get_tree().quit()` on `viewport.cpp`'s `_process_picking` function. Couldn't find any other way to debug Android only input issue.

The commit since which it broke seems to be https://github.com/godotengine/godot/pull/88992 / 99ba2519eaf79271c86b8a932ce185666fb79a37. A build with that commit reverted worked.

The issue seems to be that on Android, there is no first `NOTIFICATION_VP_MOUSE_ENTER`. That MR expects that notification before events can be enabled but that is not gonna happen on a touchscreen device.
This means `mouse_in_viewport` is stays false and viewport will ignore all possible pickable events.

I guess this makes this ticket same as https://github.com/godotengine/godot/issues/89757.

**Comment by Sauermann** [comment]
From what I can tell, #89757 requires a different solution. So this is not a duplicate.

**Comment by Anutrix** [comment]
> From what I can tell, #89757 requires a different solution. So this is not a duplicate.

Makes sense.
Workaround `get_viewport().notification(NOTIFICATION_VP_MOUSE_ENTER)` works so it's probably same root cause but requires different solution.

**Comment by Alex2782** [comment]
I was able to reproduce it, tested with a BT mouse and with TouchEvents. I will try to debug it in the next few days.

**Comment by fabianPas** [comment]
Do we currently have a workaround for this?

**Comment by Sauermann** [comment]
@fabianPas I can't test this right now, but possibly setting
Input.use_accumulated_input = false
could be a possible workaround.
See https://docs.godotengine.org/en/stable/classes/class_input.html#class-input-property-use-accumulated-input

**Comment by fabianPas** [comment]
@Sauermann Unfortunately, setting `Input.use_accumulated_input = false` does not seem to do the trick for a workaround.

**Comment by fabianPas** [comment]
Based on @Anutrix's comment it seems the following code seems to be a working workaround. Although I'm in doubt whether notifying in the Process method is the correct place.

```
public override void _Process(double delta)
{
    GetViewport().Notification((int)NotificationVpMouseEnter);
}
```

**Comment by Anutrix** [comment]
> Based on @Anutrix's comment it seems the following code seems to be a working workaround. Although I'm in doubt whether notifying in the Process method is the correct place.
> 
> ```
> public override void _Process(double delta)
> {
>     GetViewport().Notification((int)NotificationVpMouseEnter);
> }
> ```

@fabianPas I would suggest doing it in ready instead of process. Process runs every frame.

**Comment by fabianPas** [comment]
Thank you @Anutrix, I was in doubt whether a notification should've happened every frame or not, unaware of the underlying code responsible for this issue.
