### ISSUE TITLE
godot 4.3 dev5 on android is crashing when i try to start it

### ISSUE THREAD

**Issue by derilulzz** [godotengine/godot#89696]
### Tested versions

- reproducible in godot 4.3 dev5 on android

### System information

Android 14 One Ui 6.0

### Issue description

I try to open the godot 4.3 dev5 that I installed in my phone and it just crashes and dont open

### Steps to reproduce

the process i do is: i go to the godot org site and go to see the newest dev, i go install the apk file then i go and i install the apk on my phone, after this when i try to open it just crashes

### Minimal reproduction project (MRP)

its not an in editor bug

**Comment by lyuma** [comment]
If you're able to compile from source, feel free to give PR #89703 a try to see if it fixes it. It only changes java code so it should be possible to test the fix in your android project without recompiling the native libraries.

**Comment by ZachBeauchamp** [comment]
This is happening to me on the release for Godot 4.3. I changed nothing in my project besides updating it. Then on export to android it crashes on launch.

**Comment by Calinou** [comment]
@ZachBeauchamp Please open a new issue *with a minimal reproduction project attached*.
