### ISSUE TITLE
.Net / Windows / Main Branch: Editor Sometimes Crashes in Random Spot non-dev build

### ISSUE THREAD

**Issue by Delsin-Yu** [godotengine/godot#89709]
### Tested versions

Godot v4.3.dev.mono (fe01776f0)

### System information

Godot v4.3.dev.mono (fe01776f0) - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

For mono + non-dev builds, Godot Editor sometimes may crash on startup, furthermore debugging breaks at this line:
![image](https://github.com/godotengine/godot/assets/71481700/9ba8677b-f940-418b-b8eb-cabde245ca80)

Clicking the `Continue` button will show the program paused on exception, which is
![image](https://github.com/godotengine/godot/assets/71481700/fe5c2609-c71b-4d23-af76-162bbc1928ac)

The error code is `STATUS_HEAP_CORRUPTION (A heap has been corrupted.)`.

### Steps to reproduce

I am not sure if this is an OS-specific issue, but the repro is here:
1. Clone the commit `fe01776f0`.
2. Build the source with the mono module and debug symbols enabled according to the documentation.
3. Launch the editor, select and open a project.
4. Inspect the issue happens sometimes.

### Minimal reproduction project (MRP)

N/A

Maybe fixed by 
#89861

**Comment by viksl** [comment]
I can confirm this on windows 11 with latest master too.
it has been happening for about a week or so. The project selection works fine but when trying to open the project it starts opening it, loading something then crashes without loading the editor properly (no matter if it's a new project or an olde one), although at some rare moments (I don't know why, planets aligned or something?) I get into the editor and crash a bit later but that's like 1% of tries.
For me it doesn't happen if debug_symbols are enabled though, again no idea why.

**Comment by Delsin-Yu** [comment]
A short video.

https://github.com/godotengine/godot/assets/71481700/5f8f1a8c-8c70-45d1-8f37-26832cdf6271

**Comment by Delsin-Yu** [comment]
In my second build it starts crashing at another line....
<img width="884" alt="f064bff08e01753d69e6b7bc29c04625" src="https://github.com/godotengine/godot/assets/71481700/3876d196-b84d-4cdc-9760-acc3d0d57ec4">
<img width="1080" alt="fa065fbf455b534b67d6eb9b35ed5c38" src="https://github.com/godotengine/godot/assets/71481700/148b8a4b-c2c9-4746-a48e-844fe02a289f">

**Comment by zaevi** [comment]
Can confirm. And it doesn't happen with `dev_build` enabled.

I removed the code to load certificates at `main.cpp`, then the crash happened elsewhere.

![image](https://github.com/godotengine/godot/assets/12966814/09409b7e-ed51-43ba-a7ef-345190162479)


![image](https://github.com/godotengine/godot/assets/12966814/24dd00fa-5255-470e-86a5-4f40ba6ac32b)

**Comment by Delsin-Yu** [comment]
@AThousandShips request `platform:windows` tag

**Comment by viksl** [comment]
I went through the history building and this is the first where it breaks for me: 77f6e35a8dc34a649f817a9c3e3c2d341fe98457. The one before: 8bfc257e63ee30b18438c3dc7bad3293c8c16b30 works for me just fine.
I hope I did it alright, first time trying this in this IDE but so far that's it from my side.
Is it the same on your side?

**Comment by Delsin-Yu** [comment]
> I went through the history building and this is the first where it breaks for me: [77f6e35](https://github.com/godotengine/godot/commit/77f6e35a8dc34a649f817a9c3e3c2d341fe98457). The one before: [8bfc257](https://github.com/godotengine/godot/commit/8bfc257e63ee30b18438c3dc7bad3293c8c16b30) works for me just fine. I hope I did it alright, first time trying this in this IDE but so far that's it from my side. (by just fine I mean I can launch a project into editor, I haven't spent more time in it so don't know if it would crash at some point later while working with the editor)
> 
> Is it the same on your side?
> 
> EDIT: Also I take back the comment about debug_symbols making it work, it still crashes on me unless I also enable the dev_build. This should probably also have the regression label.
 
I'm doing a range of building/testing, I even went to the commits on March 10, which led me to believe there are some problems on my end, at least on mono build.

**Comment by Delsin-Yu** [comment]
I made 4 builds, and tests them by opening an empty project individually:
- [OK] Dev5 [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]
- [OK] Dev5 Mono [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]
- [OK] Main [fe01776f05b1787b28b4a270d53037a3c25f4ca2]
- [Crash!] Main Mono [fe01776f05b1787b28b4a270d53037a3c25f4ca2]

**Comment by bruvzg** [comment]
> [Crash!] Main Mono [https://github.com/godotengine/godot/commit/fe01776f05b1787b28b4a270d53037a3c25f4ca2]

> Windows 10.0.17763

The only relevant part is probably dark mode detection (Windows build number checks might be off), `17763` seems to be outdated Windows 10 version from 2018 (current supported versions are `19044`/`19045`), so no idea how to test it.

If you are really using this version of Windows, try commenting function calls here one-by-one, to narrow it down.
https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/platform/windows/display_server_windows.cpp#L5512-L5523

**Comment by Delsin-Yu** [comment]
> > [Crash!] Main Mono [https://github.com/godotengine/godot/commit/fe01776f05b1787b28b4a270d53037a3c25f4ca2]
> 
> > Windows 10.0.17763
> 
> The only relevant part is probably dark mode detection (Windows build number checks might be off), `17763` seems to be outdated Windows 10 version from 2018 (current supported versions are `19044`/`19045`), so no idea how to test it.
> 
> If you are really using this version of Windows, try commenting function calls here one-by-one, to narrow it down.
> 
> https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/platform/windows/display_server_windows.cpp#L5512-L5523
> 
> But I'm not sure how it's related to Mono.

I'm using Windows 10 1809, but I aggreed it may not be relevant.

**Comment by viksl** [comment]
Just to be clear, I have the same issues and I'm windows 11.

**Comment by Delsin-Yu** [comment]
Now I'm extra confused since my builds don't seem consistent.

These are the builds I made:

[OK] Dev5 [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]
[OK] Dev5 Mono [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]

[OK] Main-3 [691bd17df819d51e4a4ea2aa304bdd9857d49295]
[Crash!] Main-3 [691bd17df819d51e4a4ea2aa304bdd9857d49295]


[OK] Main-2 [84bdc8d1b0f12c540257878297163698c83c2d0d]
[Crash!] Main-2 [84bdc8d1b0f12c540257878297163698c83c2d0d]

[OK] Main-1 [68ad520da4365c866ceea42e0238b2ea24647289]
[Crash!] Main-1 [68ad520da4365c866ceea42e0238b2ea24647289]

[OK] Main [fe01776f05b1787b28b4a270d53037a3c25f4ca2]
[Crash!] Main Mono [fe01776f05b1787b28b4a270d53037a3c25f4ca2]

This made me rebuilds the dev5 afterward, and:

[OK] Dev5 [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]
[Sometimes Crash] Dev5 Mono [89f70e98d209563abb4dbc1f8cd5d76c81eb7940]

**Comment by Armynator** [comment]
Assuming it's the same problem, for me this is happening since way over a week already. Sometimes it works, but usually it doesn't. I'm not sure when exactly this was introduced, as I'm only rebuilding every 5-10 days. The version I'm currently using is from end of February, which I stayed on because this problem appeared afterwards. Same problem on 2 different machines, Windows 10 and Windows 11. I'm only using Mono builds.

**Comment by Armynator** [comment]
Just went back and tested through all commits. It started happening with [#eccdf1a](https://github.com/godotengine/godot/commit/eccdf1a1e8a972b40d507321b925d756a50c2a9d).

#3cac010 is still working fine for me.

**Comment by Delsin-Yu** [comment]
@AThousandShips request: `regression`, `topic:dotnet`

**Comment by viksl** [comment]
If nothing else the PR linked does seem to resolve the issue I was having with the crashes.
Have you tried it if there're some lingering issues on your end?

**Comment by Delsin-Yu** [comment]
> If nothing else the PR linked does seem to resolve the issue I was having with the crashes. Have you tried it if there're some lingering issues on your end?

Will check soon

**Comment by Armynator** [comment]
https://github.com/godotengine/godot/pull/89861 fixed it for me, yay

**Comment by Delsin-Yu** [comment]
> If nothing else the PR linked does seem to resolve the issue I was having with the crashes. Have you tried it if there're some lingering issues on your end?

Can confirm that #89861 has fixed the issue on my end as well.
