### ISSUE TITLE
Menu hover doesn't work after being clicked once

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8970]
On Godot 3.0 master
Windows 10 64 bits

Hover over a menu, see it has a hover effect:
![image](https://cloud.githubusercontent.com/assets/1311555/26528874/a4d9cbf2-43b4-11e7-9d3f-501204d299be.png)

Click on the menu, click somewhere else to close it.
Now hover the menu again, notice the hover effect doesn't work anymore:

![image](https://cloud.githubusercontent.com/assets/1311555/26528879/c59c4f04-43b4-11e7-846f-9c6ffb718144.png)

**Comment by nunodonato** [comment]
@volzhs anything you might know about? :)

**Comment by Zylann** [comment]
Still there in 3.0 alpha1 :p
