### ISSUE TITLE
When exporting an iOS Project will delete source code

### ISSUE THREAD

**Issue by SAGESSE-CN** [godotengine/godot#89715]
### Tested versions

-  Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 13.6.5 - Vulkan (Forward+) - integrated Intel(R) Iris(TM) Plus Graphics 655 - Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 Threads)

### Issue description

when exporting an iOS Project to the exists directory parent, it will be remove it directly. 

my all code is lost because of this!!!!

expect any warning or confirm or somethink.

### Steps to reproduce

1. create a new project, specify directory `/xxx/project/mygame`
2. create a empty scene
3. export iOS Project, specify export directory `/xxx/project/`
4. you will lose all source code

### Minimal reproduction project (MRP)

- no need this

**Comment by AThousandShips** [comment]
We could for example search for a project file in the path, but it'd still be risky, as it could be in any nested folder, unsure how it could be done reliably, alternatively we could rewire that the folder is either empty (or does not exist) or contains some specific data from exporting

**Comment by bruvzg** [comment]
This code actually is broken and will delete it only if there's no `binary_dir + ".xcodeproj"`:

```c++
if (da->change_dir(binary_dir + ".xcodeproj") == OK) {  // enters dest/binary_dir.xcodeproj
	da->erase_contents_recursive(); 
} 
if (da->change_dir(binary_dir) == OK) { // if previous changedir was sucessfull, enters dest/binary_dir.xcodeproj/binary_dir which will not exist
	da->erase_contents_recursive(); 
}
```
