### ISSUE TITLE
Root position of the saved scene (prefab) ignored after drag and drop into new scene

### ISSUE THREAD

**Issue by gmikhail** [godotengine/godot#89719]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 with Max-Q Design (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I have a scene with an object (for the sake of convenience I will call it prefab). When I drag a prefab into a new scene - the root position of prefab are ignored after the mouse drag is complete. But during the preview, when I can move the prefab around the scene with the mouse, the preview takes into account the root coordinates.

Visual example:

![1](https://github.com/godotengine/godot/assets/4838367/7b51ac55-ce6e-4039-a41a-b72296603528)

Root coordinates of my prefab scene:

![2024-03-20 202829](https://github.com/godotengine/godot/assets/4838367/8cd12e7a-c6a4-4ea8-82d8-1c1043fdff5c)

For the sake of simplicity, I simply moved the sphere up by 0.5m. But during the tests, I discovered that all initial coordinates (XYZ) are ignored.

As you can see, I expect that after releasing the mouse button (complete dragging), the prefab will be in the same place where I currently see it, but it turns out to be in the wrong place.

Currently, as a workaround, I have to create an empty root Node3D with zero coordinates in my prefab scene. But I think that the current behavior is a bug because during the preview everything is displayed correctly.

### Steps to reproduce

1. Open `scene.tscn` from MRP.
2. Drag and drop `prefab.tscn` into the open scene using the mouse.
3. Watch how the final position of the prefab changes when you release the mouse button.

### Minimal reproduction project (MRP)

[PrefabPositionBug.zip](https://github.com/godotengine/godot/files/14671118/PrefabPositionBug.zip)

**Comment by AThousandShips** [comment]
This is by design, and changing this would break existing projects

See also:
*https://github.com/godotengine/godot/pull/81892

**Comment by gmikhail** [comment]
In this case, it would be nice to display a warning so that users can see that changing the root transform is not recommended because it will be overridden.

Otherwise I still consider it a bug. After all, if it is possible to change the root coordinates, and during the preview they are displayed correctly (as an offset relative to the current mouse coordinates), then resetting the coordinates after dragging is completed is not what users expect.

**Drag and drop must be WYSIWYG.**

**Comment by AThousandShips** [comment]
Then the part about it using the original offset when drag-dropping is a bug yes

**Comment by ryevdokimov** [comment]
This is fixed in 4.3 by: https://github.com/godotengine/godot/pull/87126

**Comment by gmikhail** [comment]
MRP behavior in Godot 4.3-dev5:

![GIF](https://github.com/godotengine/godot/assets/4838367/efa98c98-2e88-491d-b1bb-bb2bdeec8f1e)

On one side, drag and drop is now WYSIWYG, just like the users expects.  Now I can set the offset of the root node and it will work as expected.

On the other side, @AThousandShips was against this. But honestly, it’s more convenient for me that the position of the root node of the prefab is taken into account rather than ignored. Therefore, the changes suit me.

---

But I got another bug, I don’t know whether it’s related to this fix or not, but when I drag several prefabs one after another, they are created inside each other. You can see this in the attached GIF.

This is not expected behavior. If I need to drag a bunch of different prefabs, I now have to manually deselect the newly-dragged prefab that was automatically selected in the current scene, whereas before (see GIF in the first post) I could just drag prefabs into the scene without thinking about it.

**Comment by ryevdokimov** [comment]
That behavior was added by: https://github.com/godotengine/godot/pull/87623 

To make them children of the root node you must hold alt.

**Comment by gmikhail** [comment]
Thanks to everyone, in this case I think the issue can be closed as resolved.
