### ISSUE TITLE
PWA versioning not working or missimplemented

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#89713]
### Tested versions

3.5.3.stable

### System information

web

### Issue description

So, when exporting to the web as pwa, one does indeed should have a updater.

I belive this updater works on the 

`const CACHE_NAME = CACHE_PREFIX + CACHE_VERSION;
`
that is inside the service.worker module.

BUT, as reported in https://github.com/godotengine/godot/issues/89455 it is failing to correct detect a new version available.

I noticed that on every instaled "app", when going to the android details about that app, one can find its version.

Its aways "1"

Then, when analisng the export_presets.cfg sctuture, and even on the GUIed editor inside export tab, one can find a versioning when exporting for like, Android in the entries:

```
version/code=3
version/name="1.11"
```

So.... Maybe, thats related? This missing versioning is not being incremented, ergo, the detector is aways seeing a version 1, never returning true to a new version available?

I will force entry this path on the html export and manualy update it while exporting... will report results.

### Steps to reproduce

Check the version of updated PWA apps on the native inspector, it should not change.

### Minimal reproduction project (MRP)

any blank pwa project sucessively re-exported.

**Comment by PeterMarques** [comment]
adding the:

version/code=_number_
version/name="_number_._number_"

to the cfg seens to surge no effects. and after export it is re-instanced and the lines removed by the engine.

Looking for more data about PWA versioning, found several infos, but the overall message is that one CANT sent the version directly, and that is something that is done dinamicaly for every update detected by the patform the PWA is instaled... i cant verify that.

Also, i tried adding a id:"?_number_" in the manifest json, that maybe would make the page looks like its another resource and force a fresh donwload.

But still, as documented in https://github.com/godotengine/godot/issues/69414  the best behaviour i can get is:
After a update, one will open the app 2 times and it will load the old version. on the third time, the new version will load from scratch, and open corretly.

will continue tweaking and i need more info about how the:

`JavaScript.pwa_needs_update():`

Really works on the behind the scenes.

Will try to look at source, maybe i can undestand something there.

**Comment by PeterMarques** [comment]
I think its fixed!!!
Tested with 3 or 4 consecutive updates of the PWA

Every time it loadd the new version instantly
and every new re-launch, it loaded faster, using the already download if latest.


The changes are in the service worker fetch function.

from

`self.addEventListener("fetch", (event) => {
	const isNavigate = event.request.mode === "navigate";
	const url = event.request.url || "";
	const referrer = event.request.referrer || "";
	const base = referrer.slice(0, referrer.lastIndexOf("/") + 1);
	const local = url.startsWith(base) ? url.replace(base, "") : "";
	const isCachable = FULL_CACHE.some(v => v === local) || (base === referrer && base.endsWith(CACHED_FILES[0]));
	if (isNavigate || isCachable) {
		event.respondWith(async function () {
			// Try to use cache first
			const cache = await caches.open(CACHE_NAME);
			if (event.request.mode === "navigate") {
				// Check if we have full cache during HTML page request.
				const fullCache = await Promise.all(FULL_CACHE.map(name => cache.match(name)));
				const missing = fullCache.some(v => v === undefined);
				if (missing) {
					try {
						// Try network if some cached file is missing (so we can display offline page in case).
						return await fetchAndCache(event, cache, isCachable);
					} catch (e) {
						// And return the hopefully always cached offline page in case of network failure.
						console.error("Network error: ", e);
						return await caches.match(OFFLINE_URL);
					}
				}
			}
			const cached = await cache.match(event.request);
			if (cached) {
				return cached;
			} else {
				// Try network if don't have it in cache.
				return await fetchAndCache(event, cache, isCachable);
			}
		}());
	}
});
`


to

`self.addEventListener("fetch", (event) => {
	const isNavigate = event.request.mode === "navigate";
	const url = event.request.url || "";
	const referrer = event.request.referrer || "";
	const base = referrer.slice(0, referrer.lastIndexOf("/") + 1);
	const local = url.startsWith(base) ? url.replace(base, "") : "";
	const isCachable = FULL_CACHE.some(v => v === local) || (base === referrer && base.endsWith(CACHED_FILES[0]));
	if (isNavigate || isCachable) {
		event.respondWith(async function () {
			// Always fetch the newest version from the network on the first visit
			const response = await fetch(event.request);
			return response;
		}());
	}
});`


Will continue testing, but this is the best behaviour so far.

**Comment by AThousandShips** [comment]
Again, please edit your comments :)

**Comment by PeterMarques** [comment]
It was meant to be close with comment, sorry.
