### ISSUE TITLE
Tiny paddings in popup windows

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#89718]
### Tested versions

Reproducible in 4.2.1 and 4.3

### System information

macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

There's basically no space around popup window content on macOS no matter what editor settings I try, this is the default theme:

<img width="416" alt="image" src="https://github.com/godotengine/godot/assets/60579014/b5392fe5-fd75-4a49-8c6d-6d8fcc84166e"><br>

This is on windows:

<img width="416" alt="image" src="https://github.com/godotengine/godot/assets/60579014/b29a6c8b-41f3-4e81-a8ac-7e187fad0854">

The conversation about this started [here](https://twitter.com/YuriSizov/status/1770510255195054089)

_P.S. The default padding could also be increased by ~50%, because even on windows it look a bit too packed_

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/89697.

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
I can't see any difference in the padding on macOS and Windows. What's your editor scale and macOS screen scale?

**Comment by passivestar** [comment]
> I can't see any difference in the padding on macOS and Windows. What's your editor scale and macOS screen scale?

Default system screen scale, 16 inch macbook, in Godot I usually use 1.6 but it doesn't look any different at 2.0 (which is the default)

**Comment by passivestar** [comment]
I just noticed @adamscott doesn't have paddings in his popups too: https://github.com/godotengine/godot/pull/90660

![image](https://github.com/godotengine/godot/assets/60579014/336ba58b-3bc3-4f12-87ab-99b6e09599ea)

Admittedly he has a couple more pixels in there than I do (I counted 4) but it still looks far from great

They need more space:

<img width="602" alt="image" src="https://github.com/godotengine/godot/assets/60579014/99722302-a0f9-4b2b-a9f4-8b6abc0950e9"><br>

So this issue isn't strictly macOS-specific

**Comment by coppolaemilio** [comment]
@adamscott and @passivestar are you using a custom theme at all? Does this happen also in the default one?

**Comment by passivestar** [comment]
@coppolaemilio we do but I have the same problem with the default theme (the first screenshot I attached on top is using the default one). We both seem to be using a high dpi display though

**Comment by coppolaemilio** [comment]
So the paddings might not be getting multiplied by the rendering scale 🤔

**Comment by passivestar** [comment]
> So the paddings might not be getting multiplied by the rendering scale 🤔

Probably yes

But it'd also not be enough. Multiplying **4px** by my editor scale **1.5** would give me **6px** which is practically the same

I had to lift by 12 pixels here for it to look not scuffed:

![image](https://github.com/godotengine/godot/assets/60579014/0482ac00-672c-401e-9632-69466f6f46ef)
