### ISSUE TITLE
_input(event: InputEvent) helptext feels incomplete

### ISSUE THREAD

**Issue by Gallilus** [godotengine/godot#89717]
### Tested versions

4.3.dev5

### System information

Win 10

### Issue description

I was tring to intercept gui events using `_input(event: InputEvent)` i was unaware the Control node has `_gui_input`

Is it possible to add the reference to `_gui_input` similar to `_unhandled_input`

https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/doc/classes/Node.xml#L63-L67

### Steps to reproduce

No MRPproject requierd

### Minimal reproduction project (MRP)

No MRPproject requierd

**Comment by AThousandShips** [comment]
I don't know that `Node` should point to `Control` that might be confusing, I'd say it's expected that people read the [documentation](https://docs.godotengine.org/en/stable/tutorials/inputs/inputevent.html)

**Comment by Gallilus** [comment]
I can live with that.
Lessons learned: I need to use the Online tutorials section
