### ISSUE TITLE
casting INF to int yield negative value

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#89742]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

writing the following:

`var i:int = INF`

aka, making an explicit type cast from the INF which is of type float to i which is of type int causes the value to be negative, which is unexpected. 

It correctly treats:

`var j:int = -INF`

i & j are equal, which is usually wrong. I would expect int(INF) to be a large positive integer, 9223372036854775808 to be precise.

### Steps to reproduce

1. paste the following into any GDScript file: `print(int(INF))`
2. Run said code
3. Get printout "-9223372036854775808"

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for your report, consolidating in:
* https://github.com/godotengine/godot/issues/33017
