### ISSUE TITLE
Accessibility: Tab + Left does not appear in "Built-in actions" (Mac input)

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#89744]
### Tested versions

v4.3.dev4.official [df78c0636]

### System information

Mac Sonoma 14.2.1

### Issue description

When pressing `Tab` + `Left` or `Tab` + `Right` keys on the keyboard the Accessibility kicks in, and the interface switches to next user interface node.

In my case this is an actual window `TabContainer` and I would like to avoid this behaviour.

However, when searching the "Built-in input actions" of the `Project Settings` menu, no such Accessibility options can be seen.

### Steps to reproduce

Open the supplied MRP
Click any button

```
Tab + Left
Tab + Right
```

Then check project settings, **and see if you can prevent behaviour**

### Minimal reproduction project (MRP)

[godot-accessibility-issue.zip](https://github.com/godotengine/godot/files/14695715/godot-accessibility-issue.zip)

**Comment by jsjtxietian** [comment]
On windows it doesn't seem like a problem.

**Comment by tavurth** [comment]
@jsjtxietian Hmm must be a mac issue then, I even have the same effect while holding `SPACE` bar

**Comment by kitbdev** [comment]
By `Tab + Left` and `Tab + Right`, I assume you mean the [keyboard focus](https://docs.godotengine.org/en/stable/tutorials/ui/gui_navigation.html) on the Control.
This can be disabled by either setting the [focus mode](https://docs.godotengine.org/en/latest/classes/class_control.html#class-control-property-focus-mode) to none for each button, or removing inputs from the built-in input actions `ui_focus_next`, `ui_left`, `ui_right`, `ui_up` and `ui_down`.

**Comment by tavurth** [comment]
> This can be disabled by either setting the [focus mode](https://docs.godotengine.org/en/latest/classes/class_control.html#class-control-property-focus-mode) to none for each button

Aha! Yes I'd completely forgotten about those. Will give it a try and close this issue if (probably) fixed

**Comment by tavurth** [comment]
<img width="341" alt="Screenshot 2024-03-24 at 14 23 24" src="https://github.com/godotengine/godot/assets/100964/3d80d435-9bbb-4b15-ad49-a29b64d8ee8e">

Yep for me it was this button in the `TabContainer`, thank you!
