### ISSUE TITLE
Baked shadow is always black [4.3 dev 5 / GL Compatibility]

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#89779]
### Tested versions

Godot 4.3 dev [4,5] / GL Compatibility

### System information

Linux Mint 21

### Issue description

The problem is that you can't adjust the degree of shadowing of objects when using shadow baking.

In version 3.5/3.6, when baking shadows, there is a Min Light parameter that allows you to increase the shading threshold. The new version does not have this property, and the shadows are always very contrasting and black.

I haven't found a way to adjust this since baked shadows will ignore many of the scene settings, creating a very ugly effect.

### Steps to reproduce

Here's how baking works in version 3.5

https://github.com/godotengine/godot/assets/13809475/a6490d32-2b67-42b4-860e-af044dd0af64

And here are the results in version 4.3 [dev. 4 and 5]

https://github.com/godotengine/godot/assets/13809475/2f7f9efd-6067-4752-a1a1-9674f4b22107

Unfortunately, my device only runs the GL compatible version, so I assumed I could recreate the project in Godot 4, but the visuals are very different.

### Minimal reproduction project (MRP)

Here's a project where I'm trying to do this.

[OOM4 (copy).zip](https://github.com/godotengine/godot/files/14721937/OOM4.copy.zip)

**Comment by Calinou** [comment]
Thanks for the proposal! Consolidating in https://github.com/godotengine/godot/issues/50568.

In the meantime, add an OmniLight with the Static bake mode in areas that are too dark (you can hide this light after baking to avoid any performance impact).

**Comment by SkanerSoft** [comment]
It's a shame that this is not planned. Artistic value is lost. Even if we consider that it could be more physically accurate, it looks completely unnatural. And placing a separate light source under each tree is a million-dollar idea... apparently, the time for development has not yet come.

No negativity, just regret that this opportunity was removed deliberately.

I really appreciate and respect the work of all participants in the development. Thank you anyway!
