### ISSUE TITLE
Importing a line only obj crash Godot Editor

### ISSUE THREAD

**Issue by ultrasuperpingu** [godotengine/godot#89776]
### Tested versions

- Reproductible in 4.3-dev5

### System information

Windows 10 - Godot 4.3-dev5 Vulkan (Forward+)

### Issue description

When importing a simple obj with only lines inside, Godot crashes.

### Steps to reproduce

Just import the provided file in a Godot project

### Minimal reproduction project (MRP)

Create a new project and copy the provided obj file into it.
[profil.zip](https://github.com/godotengine/godot/files/14720714/profil.zip)

**Comment by AThousandShips** [comment]
Seems like the importer doesn't handle lines which probably causes the data to be invalid, will look at a fix

**Comment by AThousandShips** [comment]
Found the issue and writing a fix, will open a PR soon

**Comment by ultrasuperpingu** [comment]
Nice. Thanks for the quick fix. I hope this report helped to make Godot more robust. As I understand the comit, loading the resource will result in a null mesh right ? I will not be able to get the vertex positions and lines (obvously for the lines as the Mesh doesn't seems to have lines) ?

Note it not necessarily a problem, it's just to know :)
