### ISSUE TITLE
Adding new points to Path2D and undoing it breaks scene history

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89781]
### Tested versions

Regression from #86542

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you add a new Path2D and add points to it and then undo it, the scene history breaks and you can't do anything until you reload the scene.

### Steps to reproduce

1. Create new scene
2. Add Path2D
3. Ctrl + Click somewhere to add points
4. Undo
5. The scene is unusable

### Minimal reproduction project (MRP)

N/A

**Comment by naturally-intelligent** [comment]
I'm getting basically unusable Path2Ds in 4.3dev5, once I add a point to the path they go dead, ex can't add child nodes to Path2D

**Comment by djrain** [comment]
Not sure if I should make a new issue, but same bug is present in 4.3 stable if you add a point by clicking on the curve with the "select points" tool.

**Comment by Calinou** [comment]
> Not sure if I should make a new issue, but same bug is present in 4.3 stable if you add a point by clicking on the curve with the "select points" tool.

Please open a new issue for this, as the cause may be different.
