### ISSUE TITLE
`randi()` takes up to ~4x longer than `randi_range()`

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#89795]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 v4.2.1.stable.official [b09f793f5] Intel Core i7 2600K

### Issue description

I was looking at some code I wrote and noticed that in some places I used `randi() % 9 + 1` and in other places I used `randi_range(1, 9)` and that got me wondering if it was better to use one or the other, so I benchmarked it and found that using `randi()` consistently takes about 1.25x to 4x longer than `randi_range()`.

The problem is especially bad (consistently takes 2-4x as long) when doing it just a few times. But when repeating the action 10_000 times or more it seems to settle at about 1.25x longer.

The disparity appears to be even worse in 4.1.3 (`randi` takes about ~1.6x-12x longer than `randi_range`) but in reality it seems both `randi` and `randi_range` are generally **faster** (by up to ~2x) in 4.1.3 than in 4.2.1 as far as pure system clock time goes.

### Steps to reproduce

Run the following code on any node. I used a `Control` node:

```gdscript
func _ready() -> void:
	var start: int # start time
	var end: int # end time
	var ri: int # time it took randi in usecs
	var rr: int # time it took randi_range in usecs
	var iterations: Array[int] = [1, 10, 100, 1000, 10_000, 100_000, 1_000_000, 10_000_000]
	for i in iterations.size():
		print("Doing %s iterations:" % iterations[i])
		start = Time.get_ticks_usec()
		for n in iterations[i]:
			randi() % 9 + 1
		end = Time.get_ticks_usec()
		ri = end - start
		prints("\trandi:", ri, "usec", )
		start = Time.get_ticks_usec()
		for n in iterations[i]:
			randi_range(1, 9)
		end = Time.get_ticks_usec()
		rr = end - start
		prints("\trandi_range:", rr, "usec")
		print("\t\trandi() took %sx as long" % (float(ri) / rr))
```

I realize my CPU is pretty old, so your exact measurements will likely vary from mine. On my PC the output looks something like this:

```
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.2.175 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 670
 
Doing 1 iterations:
	randi: 23 usec
	randi_range: 5 usec
		randi() took 4.6x as long
Doing 10 iterations:
	randi: 6 usec
	randi_range: 3 usec
		randi() took 2x as long
Doing 100 iterations:
	randi: 52 usec
	randi_range: 46 usec
		randi() took 1.1304347826087x as long
Doing 1000 iterations:
	randi: 229 usec
	randi_range: 119 usec
		randi() took 1.92436974789916x as long
Doing 10000 iterations:
	randi: 930 usec
	randi_range: 692 usec
		randi() took 1.34393063583815x as long
Doing 100000 iterations:
	randi: 9408 usec
	randi_range: 8032 usec
		randi() took 1.17131474103586x as long
Doing 1000000 iterations:
	randi: 109166 usec
	randi_range: 80347 usec
		randi() took 1.35868171804797x as long
Doing 10000000 iterations:
	randi: 1065092 usec
	randi_range: 814944 usec
		randi() took 1.30695115247183x as long
```

```
Godot Engine v4.1.3.stable.official.f06b6836a - https://godotengine.org
Vulkan API 1.2.175 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 670
 
Doing 1 iterations:
	randi: 12 usec
	randi_range: 1 usec
		randi() took 12x as long
Doing 10 iterations:
	randi: 2 usec
	randi_range: 1 usec
		randi() took 2x as long
Doing 100 iterations:
	randi: 7 usec
	randi_range: 5 usec
		randi() took 1.4x as long
Doing 1000 iterations:
	randi: 72 usec
	randi_range: 56 usec
		randi() took 1.28571428571429x as long
Doing 10000 iterations:
	randi: 749 usec
	randi_range: 489 usec
		randi() took 1.53169734151329x as long
Doing 100000 iterations:
	randi: 7310 usec
	randi_range: 4993 usec
		randi() took 1.46404966953735x as long
Doing 1000000 iterations:
	randi: 75226 usec
	randi_range: 50882 usec
		randi() took 1.47844031288078x as long
Doing 10000000 iterations:
	randi: 824596 usec
	randi_range: 505726 usec
		randi() took 1.63051929305592x as long
```

### Minimal reproduction project (MRP)

N/A

**Comment by sacrificerXY** [comment]
I think this is just due to the slowness of gdscript. Note that this
```gdscript
randi() % 9 + 1
```
is function call, a modulo operation, and an addition while this
```gdscript
randi_range(1, 9)
```
is just a single function call. If I remove the modulo, you get vastly different measurements (`randi() + 1` ~1.25x **faster** than `randi_range(1, 9)` in my machine)

Side note: If you reverse the order (doing `randi_range` before `randi`) the gap seems to decrease which is quite interesting.

**Comment by AThousandShips** [comment]
Indeed this sounds like it's just the fact that one method is run in a compiled language and one in an interpreted one in a virtual machine, so not much that can be done here directly, see:
* https://github.com/godotengine/godot-proposals/issues/6031

**Comment by Deozaan** [comment]
I see. I thought they would both be doing the same thing under the hood and it didn't occur to me that `randi_range` would be faster because it was essentially running C++ code directly while `randi() % x + y` was being interpreted.

Then perhaps this is a documentation issue because [the docs for `randi()`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-randi) suggest using modulo plus some value if you want a value within a range. But clearly it would be better (in many/most cases) to just use `randi_range` instead. The difference is that the value returned by `randi` is unsigned and can be up to (but excluding) 2³² while in `randi_range` it is signed and can be only half that but also negative numbers.

**Comment by AThousandShips** [comment]
It's just an example so it's not really an issue, performance isn't the focus with GDScript, it's only an issue if you assume GDScript to be performance focused, and with randomness performance isn't necessarily a concern generally

**Comment by Deozaan** [comment]
That's all true and I don't disagree. But it would at least point people in the right direction if it said something like "To get a random value within a range, prefer using `randi_range()` when possible."

**Comment by AThousandShips** [comment]
You'd just look right below and see it and see the different use cases I'd say, I don't think people needs to be pointed there

**Comment by Deozaan** [comment]
You're absolutely right. Thank you for your time. 🙂
