### ISSUE TITLE
Control-clicking function to see documentation breaks when in-scope variable has same name as function

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#89813]
### Tested versions

Tested in v4.2.1.stable.official [b09f793f5] and v4.1.3.stable.official [f06b6836a]

### System information

Windows 10

### Issue description

I control-click functions and classes a lot in the script editor to see the relevant documentation. I noticed when making an MRP for #89795 that if I give a variable the same name as a function, then when I control-click the function it takes me to the variable declaration instead of the function's documentation. This appears to happen only if the variable is in scope.

## Global scope example:
```gdscript
var randi: int

func _ready() -> void:
	randi() # control-click takes you to variable declaration a few lines up ⛔
```

## Local scope example:
```gdscript
func _ready() -> void:
	var randi: int
	randi() # control-click takes you to variable declaration one line up ⛔
```

## Out-of-scope example:
```gdscript
func _ready() -> void:
	for randi in 10:
		pass
	# variable is no longer in scope
	randi() # control-click takes you to function documentation ✅
```

### Minimal reproduction project (MRP)

See above.

**Comment by AThousandShips** [comment]
This is is to be expected, you're shadowing the variable, and the code will break as well, this isn't a bug IMO, it works correctly, what's wrong with this? You can't call this method here, you're trying to do it on an `int`

**Comment by Deozaan** [comment]
Once again, you're right. 😅 Or at least mostly right.

I didn't notice that it does give me warnings about shadowed variables/global identifiers. But the code runs as expected without errors.

My apologies and thanks again for your time.

**Comment by AThousandShips** [comment]
In the future please ask in the [forums](https://forum.godotengine.org/) or similar to check that it's bug :)
