### ISSUE TITLE
Touchpad (laptop) scrolling is way too fast in the web editor

### ISSUE THREAD

**Issue by sammonius** [godotengine/godot#89814]
### Tested versions

Tested on Godot 4.3.dev5, but also seen as far back as 3.5

### System information

ChromeOS 118.0, Chrome 118.0

### Issue description

Scrolling in the editor is extremely fast on the web editor from a laptop.

### Steps to reproduce

1. Open the web editor from a laptop (https://editor.godotengine.org/)
2. Open a project and click on any node
3. Scroll through the inspector by dragging 2 fingers up or down on the touchpad

### Minimal reproduction project (MRP)

[N/A]

**Comment by OfficerUrchin** [comment]
Scrolling is impossible without using the scroll bar.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/49873.
