### ISSUE TITLE
Godot 4.2.1 VR XRTools View and charactebody3D spins out of control and flies around like crazy relative to headtracking with no movement code

### ISSUE THREAD

**Issue by TrickyNerdy** [godotengine/godot#89822]
### Tested versions

4.2.1 Mono stable

I also reinstalled windows, the oculus app and steam VR, Other VR games like VRChat work fine

### System information

Windows 11 1660Super Godot 4.2.1 Mono Stable Meta Quest 2

### Issue description

When using XR tools to set up a minimum VR project, the VR view spins like crazy. Rotating my head can change the direction and the player will move along the floor even with no movement code

### Steps to reproduce

Create a project with this out line, all code is unchanged from XRTools, project is too big to upload

The MeshInstance3Ds are a floor plane, I've also tried thin cubes as floors and the other one is a floating cube for visual frame of referance

![Screenshot 2024-03-23 185259](https://github.com/godotengine/godot/assets/116591550/dede3d87-4370-4445-b688-9bdaa3dd2686)

### Minimal reproduction project (MRP)

 project is too big to upload, see outline screenshot

**Comment by Malcolmnixon** [comment]
Issues on the Godot XR Tools asset should be posted in its issue system (https://github.com/GodotVR/godot-xr-tools).

If you follow the demo videos at the bottom of https://godotvr.github.io/godot-xr-tools/docs/player_body/ you'll notice the node configuration is different. It has:
* XROrigin3D
  * XRCamera3D
  * PlayerBody

Putting the XROrigin3D under the PlayerBody results in a feedback where even the slightest movement of the player causes the origin to move, which moves the player, which moves the origin, in an infinite cycle.

**Comment by TrickyNerdy** [comment]
@Malcolmnixon Putting the XROrigin3D under the PlayerBody results in a feedback where even the slightest movement of the player causes the origin to move, which moves the player, which moves the origin, in an infinite cycle.

Wow, this is exactly right, and perfectly fixed everything, thanks so much I'm so hype now to make a VR game

**Comment by TrickyNerdy** [comment]
Fixed
