### ISSUE TITLE
Some components (Filesystem dock, file picker...) sort files incorrectly

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#89854]
### Tested versions

- happens in `v4.3.dev.custom_build` [99ff024f7]
- does *not* happen in `v4.3.dev5.official` [c9c17d6ca]

### System information

linux

### Issue description

Files fail to get sorted by name. When creating them, or when loading a project.
When creating them, it seems that they just get sorted by creation time, regardless of the name.

edit: additionally, it seems that the file picker popups also can't sort files (when creating a new project and trying to pick a destination, the system folders are all unsorted).

### Steps to reproduce

Either open any exisiting project or:

https://github.com/godotengine/godot/assets/71937306/1de9fe95-fdf1-41cf-848e-8d5bedcad2c7

### Minimal reproduction project (MRP)

any

**Comment by AThousandShips** [comment]
Seems to be from:
* #87874

Working on a fix, though I'm not quite sure how it would happen
