### ISSUE TITLE
Setting the POSITION of a vertex in a conditional statement leads to weird behavior

### ISSUE THREAD

**Issue by Dalayeth** [godotengine/godot#89869]
### Tested versions

- Reproducible in: 4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

When setting the POSITION built-in variable in a conditional statement the vertex always seems to be affected. Regardless of the condition. Even when the condition evaluates to false the code is having an effect on the POSITION. After some testing the behavior seems unpredictable. At first even when doing if (false) made the mesh appear in the center of my screen but after some testing it sometimes disappears. Only when commenting out the code that sets the POSITION variable does it not take affect.

### Steps to reproduce

1. Create a new project with the default settings.
2. Create a new scene with a Node3D parent.
3. Create a GPUParticles3D node.
4. Set the ParticleProcessMaterial to a new ParticalProcessMateria, leave the settings the default.
5. Set Draw Passes > Pass 1 to a QuadMesh.
6. Set the QuadMesh's Material to a new ShaderMaterial.
7. Set the ShaderMaterial's Shader to a new shader, name it anything.
8. In vertex function add `	if (false) { POSITION = vec4(-1,-1,-1,-1); }`.

When the code setting the position is not commented out it still affects the particle even when the conditional statement evaluates to false.

### Minimal reproduction project (MRP)

[reproduce.zip](https://github.com/godotengine/godot/files/14737251/reproduce.zip)

**Comment by huwpascoe** [comment]
The W component should be either positive 0 or 1 depending on what's being represented

point = x,y,z,0
vector = x,y,z,1

Does the issue still occur with vec4(-1,-1,-1,1)?

**Comment by jsjtxietian** [comment]
See also the preview window:

![image](https://github.com/godotengine/godot/assets/8315986/5b72a786-4d6d-4225-bf6d-54040c32620c)

![image](https://github.com/godotengine/godot/assets/8315986/7a93e0cb-b49d-4849-973d-4e0d77f62a7a)

**Comment by AThousandShips** [comment]
This sounds like something to document, I even thought it had already been as it's a pretty standard thing in shader code, but needs documenting in the shader reference section I'd say

**Comment by AThousandShips** [comment]
For debugging purposes I'd suggest using the precompiler instead for this btw:
```
void vertex() {
#if 0
    POSITION = vec4(...);
#endif
}
```

**Comment by clayjohn** [comment]
Yes, we need to add documentation here to say that if POSITION is written to anywhere in the shader, it will _always_ be used, so the user becomes responsible for ensuring that it always has acceptable values.
