### ISSUE TITLE
Switching scene tabs duplicates nodes in the scene and eventually also leads to an editor crash.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#89877]
### Tested versions

- Reproducible: 4.3dev master[99ff024f78f65ba0bc54fb409cfeca43ba2008fe]
- Not reproducible: 4.3 dev5

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

When switching scene tabs while running the project some nodes in the scene tree get duplicated and stay in, eventually leading to a crash after couple times of repeating.

**Video:** https://youtu.be/11MNyMQJlh0

### Steps to reproduce

1. Open the MRP.
2. Open the Test.tscn to have two tabs (main and test).
3. Go to main and press save and reload the project (this step is just in case, might not be necessary).
4. Play the project and keep the play window somewhere (doesn't matter).
5. In the editor switch from main to test tab and then back to the main tab.
6. Observe some nodes got duplicated.
(7. Repeat this proces to duplicate more - you might need to always press the stop and play buttons for every duplication - and observe after couple duplications the editor hard crashes)

### Minimal reproduction project (MRP)

[Mrp.zip](https://github.com/godotengine/godot/files/14742291/Mrp.zip)

EDIT(@lyuma + @Illauriel): simpler MRP and repro steps:
Another MRP: [node-dupe-bug.zip](https://github.com/godotengine/godot/files/14821094/node-dupe-bug.zip)
Steps to reproduce:
1. Open node3d.tscn.
2. Open the nested scene.
3. Save the nested scene
4. Return to the original node3d.tscn. it will contain duplicate nodes.

The reason play duplicates nodes is because the play button saves all scenes. Therefore saving is sufficient.

**Comment by AThousandShips** [comment]
Can confirm will try bisect in a bit

**Comment by AThousandShips** [comment]
Regression from:
* https://github.com/godotengine/godot/pull/89447

Unsure if this *caused* it or just exposed an existing issue that didn't fire without this

CC @ajreckof @KoBeWi

**Comment by AThousandShips** [comment]
At a glance I suspect the issue is that the change in timing means the scene editor adds a preview environment or similar incorrectly and then doesn't restore it, could be related to incorrectly not checking ownership as well

**Comment by KoBeWi** [comment]
You don't need to play the project. Just save the instance scene and go back to the parent scene. This causes reloading the scene (to update the instance) and leads to the mentioned bug.

After enough repeats, I got the editor to freeze while spamming `Object was deleted while awaiting a callback.` in the console.

**Comment by viksl** [comment]
In my own project (not the MRP) it duplicates several nodes as seen here (check the Time label is the only one without @ in the name but it was also duplicated).
![image](https://github.com/godotengine/godot/assets/33526847/82e27c94-ebc2-4296-b376-f61985df4ef7)

**Comment by KoBeWi** [comment]
Well the crash seems specific to your scene. The bug is that nodes get duplicated, but depending on nodes, the end result might be different.

**Comment by AThousandShips** [comment]
It's due to an incorrect deletion sequence in the PR, writing a fix right now:
https://github.com/godotengine/godot/blob/2850ce2a15cfc9fdbb0efd69411c0ad7601b6f11/editor/editor_data.cpp#L725-L727

**Comment by akien-mga** [comment]
Indeed, this should go from last to first.

But this approach feels hacky in the first place, maybe we could add a bool to `replace_by` to not copy child nodes?

**Comment by lyuma** [comment]
@Illauriel and I confirmed a bisect of #89447
Another MRP: [node-dupe-bug.zip](https://github.com/godotengine/godot/files/14821094/node-dupe-bug.zip)

Steps to reproduce:
1. Open node3d.tscn.
2. Open the nested scene.
3. Save the nested scene
4. Return to the original node3d.tscn. it will contain duplicate nodes.

I also had a suspicion that an internal node somewhere could cause an issue: I recall from debugging a different issue that the core function `Node::replace_by` may be buggy in the presence of internal nodes (off-by-n error), since it does not properly check indexing, so seeing `replace_by` in the regression PR is setting off that alarm bell as well.

From my notes about replace_by:
```
All nodes have to be added and moved to the same index, one by one. This might make files with thousands of nodes slow.
Calling replace_by on an internal node will malfunction because it does not preserve the internal_node in the add_child call
I do think there's a core bug in that replace_by is incorrect for internal nodes
```

I should try and repro + file the bug about replace_by, since it's probably a separate issue, but wanted to bring it up anyway just in case.

**Comment by Maran23** [comment]
Moving a `GDScript` from one folder to another also reproduced this bug for me.

**Comment by Rindbee** [comment]
It seems that it will appear as long as you save the sub-scene and switch to the main scene.

Nodes will be duplicated only when the nodes meet the following conditions:
1. Is a direct non-internal child node of the main scene root;
2. The node index is an even number.
