### ISSUE TITLE
[C#] Black screen when exporting Android startup

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#89873]
### Tested versions

v4.3.dev.mono.custom_build [5d08c2631]

### System information

HarmonyOS Vulkan/Opengl - integrated Mali-G76 -  (8 Threads)

### Issue description

As the title says, the latest `master` branch with C# build enabled to export Android fails to launch.
logcat:
![图片](https://github.com/godotengine/godot/assets/52148221/dbde031e-1937-44a2-9037-cc9226231e1d)

### Steps to reproduce

1. build the latest `master` branch with `module_mono_enabled=yes`
2. create a C# project
3. export as apk, install and launch, it will only show a black screen.

### Minimal reproduction project (MRP)

N/A

**Comment by zaevi** [comment]
Can confirm on 7c6e85d. Build with `template_debug` and `module_mono_enabled`

**Comment by AThousandShips** [comment]
Closing as resolved, if someone can still replicate this please comment here
