### ISSUE TITLE
Scaling issue with Rigidbody2D

### ISSUE THREAD

**Issue by Hedgestock** [godotengine/godot#89898]
### Tested versions

- Reproductible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Windows 10 and 11 - v4.2.1.stable.mono.official [b09f793f5] - forward+ and gl_compatibility - both vulkan and gles3 - NVIDIA GeForce RTX 4060 Laptop GPU /  NVIDIA GeForce RTX 3060 GAMING OC 8G

### Issue description

When trying to scale a Rigidbody2D, either nothing happens, or the X component of the scale gets used for both X and Y values.
![image](https://github.com/godotengine/godot/assets/16304811/cc2f02e1-f11a-4962-a3c2-18f12666487c)

### Steps to reproduce

Add a Rigidbody2D to a scene, and in it's script, assign the `Scale` during the `Ready()` call.

### Minimal reproduction project (MRP)

[BugTestScale.zip](https://github.com/godotengine/godot/files/14752385/BugTestScale.zip)

**Comment by AlexOtsuka** [comment]
Hi,

Absolutely fantastic high effort MRP. I believe you swapped the vertical and horizontal labels around, no big deal. The behavior is known, however, as the scale of a RigidBody is intended to be 1 in order not to mess up the physics calculations. Your scale actually gets applied, but is immediately modified by the RigidBody (which is the point of a RigidBody, to let it update the object's transform based on how it was affected by the physics system).

Did you manually set the scale for the second row in the inspector? Those don't get scaled at runtime for me either when running your MRP, everything else is the same however.

More info: https://github.com/godotengine/godot/issues/5734, https://github.com/godotengine/godot/issues/79929, https://stackoverflow.com/questions/77590667/godot-physics-resizing-my-sprites-at-runtime

**Comment by Hedgestock** [comment]
Oh okay, if I'm not supposed to touch the RigidBody scale because it takes care of updating stuff by itself, it leaves me with a question.
I'm developping a fishing game, and up until now, the fishes had centered and symetrical hurtboxes, meaning I could flip the sprite to make them swim in the opposite direction and it would not matter.
However, now we are adding fishes with uncentered hurtboxes (by that I mean CollisionShape2D) and I thought I could just scale the whole fish vertically by -1 to get it to flip, but as you explained and as the issues and the SO thread you linked illustrate, RigidBody is not intended to be used this way.
A fish looks like so:
![image](https://github.com/godotengine/godot/assets/16304811/2eb4f7e2-a895-4a24-abde-444a12a21c15)
So for uncentered hurtboxes, my hotfix was to do 
```cs
	public override void _Ready()
	{
		sprite = GetNode<AnimatedSprite2D>("AnimatedSprite2D");
		hurtBox = GetNode<CollisionShape2D>("HurtBox");
		<...>
		sprite.FlipH = flip;
		if (flip)
		{
			Flip(hurtBox);
		}
        	<...>
	}
	
	protected void Flip(Node2D node)
	{
		Vector2 unflipped = node.Position;
		node.Position = new Vector2(unflipped.X * -1, unflipped.Y);
	}
```
which basically moves the position of the CollisionShape without flipping it.
For unsymmetrical CollisionShapes, I could maybe scale it by itself with (-1,1) in addition of doing the `Flip(Node2D node)` trick, but the more children the fish gets, the more stuff we have to track and make sure are correctly flipped, so we would really like a solution where we could scale/flip the whole fish and everything within would follow.

We also considered putting every flip-affected children in a Node2D and flipping that as follows:
![image](https://github.com/godotengine/godot/assets/16304811/f9e7443f-f966-479a-8237-c7db0e0928d3)
But then "This node has no shape, so it can't collide or interact with other objects." was now an issue on the parent RigidBody.

Do you maybe have an elegant solution to our problem ? Otherwise we'll manage with ducktape-code.

Sorry for the long post, and for mixing vertical and horizontal labels, also, I'd run this on more hardware/settings to figure out why the second row in the debug exe does not scale on your machine at runtime, but on mine yes, but since it's not intended for the scale of a rigidbody to be changed from outside anyways I won't bother ^^

Thanks for your time and for the helpful links !

**Comment by Hedgestock** [comment]
Oh right, I could put everything in a container but the CollisionShape then I'd only have to worry about 2 things, IDK how I did not realise that, I was so focused on making it all work in one go that I missed it.

Thank you again for your thoughtful insights !

**Comment by RMadsenG** [comment]
Worrying about 2 things is certainly better than dealing with many, but it would be best if it was only necessary to manage one.

I see this has been closed for 2 years, is this still the best way to do it?
