### ISSUE TITLE
cant copy node path using the right click menu or by shortcuts

### ISSUE THREAD

**Issue by newandtired** [godotengine/godot#89899]
### Tested versions

Godot_v4.2.1-stable_win64

### System information

windows 11 - godot_v4.2.1 forward+ 

### Issue description

issue facing : cannot copy node path using ctrl+shift+c or even using the right click menu to manually click copy node path

expected behaviour : pasting node path, "yellow/coloured/text" in a format like this.

bahaviour shown : it copies the node name as is and not the path to it

![Uploading Screenshot 2024-03-26 005758.png…]()

### Steps to reproduce

go to scene -> open scrip editor -> ctrl+shft+c or rightclick then select copy node path -> paste node path

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Your screenshot didn't upload, please try again and wait until it's done uploading

**Comment by KoBeWi** [comment]
The path copied from scene tree is relative to root node. If you want path relative to the node with script, use drag and drop.

**Comment by AThousandShips** [comment]
Closing due to lack of response, and based on the note above, if you provide the requested information this can be reopened
