### ISSUE TITLE
When Import ETC2 ASTC option is disabled, Remote Debug on Android is still allowed but fails Export with empty error message in Project Run popup

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#89910]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

Android Export requires to check project setting VRAM Compression > Import ETC2 ASTC option (`rendering/textures/vram_compression/import_etc2_astc`), this is well explained in the Export popup when trying to Export for Android:

![image](https://github.com/godotengine/godot/assets/1067772/b4e2f938-7c2a-47e9-82df-b20653b47ea9)

The Export buttons are greyed out until user fixes import settings (with the Fix Import button or directly in Project Settings).

However, the Remote Debug for Android is not disabled, so user can still try it, but it will fail on the Project Run popup:

![2024-03-26 Android remote debug fails with empty error when texture compression has no been fixed](https://github.com/godotengine/godot/assets/1067772/e030174c-aa93-461f-a67a-6fdd1921f391)

> Project export for platform: Android - Failed
[Run]: (no error message)

So failing the export is not the bug. The bug is that Remote Debug for Android is allowed and fails with no clear error.

Instead, the editor should either:
- grey out the Remote Debug Android button with a permanent message or hover tooltip explaining the reason for being unavailable (here, ETC2/ASTC texture compression required)
- or allow it but in the Project Run popup, give a full error message about ETC2/ASTC texture compression

As a bonus there could be a Fix Import button as in the Export popup, but it may be hard to implement inside a tooltip / Project Run console, so suggesting the user to open the Export popup to read the full error message + Fix Import button, or alternatively change project settings manually, may be best.

### Steps to reproduce

1. Create new project
2. Add Export template for Android (but don't Fix Import for ETC2 ASTC yet)
3. Connect Android device
4. Click on top-right button to Remote Debug Android
5. Observe empty error message
6. Go back to Export or Project Settings popup to Fix Import or check ETC2 ASTC
7. Repeat 4 => this time, it works

### Minimal reproduction project (MRP)

N/A

**Comment by gibliald** [comment]
I tried to reproduce this bug on 4.3-beta1 but the remote debug button was grayed out until I activated the ETC2/ASTC option. I guess it's fixed.

**Comment by Calinou** [comment]
Closing per @gibliald's comment. Please comment if you can still reproduce this on 4.3 or later.
