### ISSUE TITLE
rename set_expand_margin_size to set_expand_margin

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8992]
The naming of style box variables are unnecessary long in my opinion.
a couple of names end with size:
```
set_expand_margin_size
set_margin_size
```
which is not consistent to `set_default_margin`

I would like to remove all the `_size` endings to make it consistent and faster to type.

**Comment by kubecz3k** [comment]
Seems to be addressed in 3.0 since I haven't found those functions.
