### ISSUE TITLE
PhysicsDirectBodyState2D: `get_contact_local_position` returns global positions

### ISSUE THREAD

**Issue by stephanbogner** [godotengine/godot#89938]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.1.2 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

#### Problem
`get_contact_local_position` doesn't actually return the local position of the contact.

The documentation even says this: 
> Returns the position of the contact point on the body **in the global coordinate system.**

However, this makes the function name utterly misleading.

#### Solution
1. Rename the function to `get_contact_position` or `get_contact_global_position`
2. Make `get_contact_local_position` return the local position (equivalent to `to_local(state.get_contact_local_position(i))`)

#### Test setup:
<img width="612" alt="Screenshot 2024-03-27 at 09 06 53" src="https://github.com/godotengine/godot/assets/7897006/2d733052-c3d2-4438-93dc-736c9dbf02d3">

#### Reported contact points:
```
Object1: (132, 500.3)
Object2: (827, 500.3)
```

### Steps to reproduce

- Create a rigid body and a static body
- Add code to report contact position (see below)
- Check the reported points

```
func _integrate_forces(state):
	for i in range(state.get_contact_count()):
		var contact_position = state.get_contact_local_position(i)
		print(name, ": ", contact_position)
		var actually_local_contact_position = to_local(state.get_contact_local_position(i))
```

### Minimal reproduction project (MRP)

[bug-local-contact-points.zip](https://github.com/godotengine/godot/files/14770223/bug-local-contact-points.zip)

**Comment by AThousandShips** [comment]
The documentation clarifies this, it might be a bit confusing but it's correct, it doesn't return the "local position", it returns the position of the "local contact", as opposed to the "collider position"

This can't be changed without breaking compatibility, and the rename to "global" is incorrect, as it misses the meaning

Changing the return value is also breaking compatibility, and is incorrect, it should be global

**Comment by stephanbogner** [comment]
@AThousandShips Thanks for clarifying.
I still don't fully understand even after reading through the other issue ... which means I should make a docs enhancing PR once I understand 😅

**Some questions and thoughts:**
1. So what you are saying is that it returns the "global position" of a "local contact" and that is where the name comes from?
2. If so: Does a "global contact" also exist if "local contact" is a term (thinking of RigidBody2D's `get_contact_count` which doesn't say anything about global/local)
3. Is there some place in the docs where it's explained what a "contact_collider" is? This could also be part of where my confusion comes from. ([PhysicsDirectBodyState2D](https://docs.godotengine.org/en/stable/classes/class_physicsdirectbodystate2d.html) only talks about how to use it and I didn't find anything else)

**As additional context:**
Initially I had expected that a function like `RigidBody2D.get_contact_points()` (similar to `get_contact_count()`) would exist to easily access the points without going through PhysicsDirectBodyState2D.

**Comment by stephanbogner** [comment]
**My mental model at the moment:**
- There are bodies, e.g. `body_a` and `body_b`
- When they touch they share a `contact` (with its reported position being global) ... 
- ... which I can access via PhysicsDirectBodyState2D

**Comment by AThousandShips** [comment]
> Does a "global contact" also exist if "local contact" is a term

No, it's complement is [`get_contact_collider_position`](https://docs.godotengine.org/en/stable/classes/class_physicsdirectbodystate2d.html#class-physicsdirectbodystate2d-method-get-contact-collider-position)

It's "collider", as in the position on the object collided with, contrasted with "local" as in local to the body of the state

**Comment by stephanbogner** [comment]
@AThousandShips Thanks for the effort but honestly I still don't understand it ... but that doesn't really matter.
It seems the function does what it should so you can close the issue. Once I understand I might open an issue/PR in the godot-docs repo 🙂
