### ISSUE TITLE
PanelContainer is semi-transparent, when all of the modulate/self-modulates being full white with no transparency

### ISSUE THREAD

**Issue by dragon3025** [godotengine/godot#89932]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 630 (Intel Corporation; 31.0.101.2111) - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

I have a PanelContainer that is showing up semi-transparent. All of the nodes in the scene have modulate/self-modulate that is full none-transparent white (hovering shows R1.00, B1.00, G1.00 A1.00). The PanelContainer itself is using a custom theme and the panel's StyleBoxTexture is full opaque and the modulate is also full none-transparent white.

### Steps to reproduce

You can see it in the editor and in-game. The PanelContainer is semi-transparent instead of fully opaque.

### Minimal reproduction project (MRP)

[Bug Test.zip](https://github.com/godotengine/godot/files/14767635/Bug.Test.zip)

**Comment by timothyqiu** [comment]
> the panel's StyleBoxTexture is full opaque

In the MRP, you added the opaque stylebox to Panel. But you're using a PanelContainer. They are different nodes.
