### ISSUE TITLE
Duplicated node loses its sub-resources

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89947]
### Tested versions

4.3 7d151c8
Does not happen in 4.3 dev5

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you duplicate a node, the duplicate will not have sub-resources. Happens both in editor and from script.

### Steps to reproduce

1. Add CollisionShape2D
2. Add a shape
3. Duplicate the node
4. The new node has no shape

### Minimal reproduction project (MRP)

N/A

**Comment by viksl** [comment]
I can confirm.
I don't know if I udnerstand how this works in my IDE correctly or not but when I go back to f8bae10be6a5d33acf8409b915aba9dd6493dcf6 it does not happen and in the one above it 8c470749f1e93096f794bbf5d51c1f6f9a24d704 it starts happening.

**Comment by KoBeWi** [comment]
@warriormaster12 Seems like https://github.com/warriormaster12/godot/tree/regress-dup fixes this issue too. Feel free to open the PR already.

**Comment by warriormaster12** [comment]
Done
