### ISSUE TITLE
TypedArray does not work with Inheritence

### ISSUE THREAD

**Issue by betalars** [godotengine/godot#89959]
### Tested versions

 - reproducible in v4.2.1.stable

### System information

nixos unstable

### Issue description

When trying to assign a typed array to an array of a parent type, godot will raise an error.

### Steps to reproduce

1. create a new script
2.  write this snippet into the _ready function
```
var node_array: Array[Node]
var node_3d_array: Array[Node3D] = []

node_array = node_3d_array
```
**Expected Result:** 
It is allowed to assign an array of inherited types to a typed array

**Observed result:**
Error: Value of Array[Node3D] cannot be assigned to a variable of type "Array[Node]".

### Minimal reproduction project (MRP)

N/A

**Comment by betalars** [comment]
Btw: This is not a too critical bug, as you can simply use the parent type for your array instead as a workaround.

**Comment by AThousandShips** [comment]
This is a known limitation, see the discussion in:
* https://github.com/godotengine/godot-proposals/discussions/7364

Consolidating there

**Comment by betalars** [comment]
Wait, this is intended? Okay I did not see that coming.

**Comment by AThousandShips** [comment]
See the discussion, it's a known limitation, and being discussed how it should work, it's not intended necessarily, we just need to work out how it should work, you'll see the details there
