### ISSUE TITLE
The problem of the ruined shadow on the model 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#89952]
### Tested versions

4.2.1

### System information

mobile android 

### Issue description

Is there a way to remove the shadow on the walnut-colored object? How can I remove it? 
![Screenshot_٢٠٢٤٠٣٢٧-٢٢٠٣٣٥](https://github.com/godotengine/godot/assets/153130532/66c72c42-ccb8-420a-a7d1-f420a14b1e28)

### Steps to reproduce

this is the problem 

### Minimal reproduction project (MRP)

Thank you

**Comment by des54321** [comment]
I think there is a setting in the model's material that allows you to turn off shadows.

**Comment by Sorshx** [comment]
This error occurs when a smooth object is activated and the color at the bottom of the object occurs

**Comment by AThousandShips** [comment]
Please ask support questions in the [forums](https://forum.godotengine.org/), this is for reporting bugs
