### ISSUE TITLE
AnimationPlayer don't memories time position in editor (red line)

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#8995]
**Operating system or device - Godot version:**
Window 7, v2.1.3.stable.official

**Issue description:**
Red Line from AnimationPlayer go back to 0 time after reselecting.
It looks like animation is on correct position. But you got fooled.

![animationplayer_redline_problem](https://cloud.githubusercontent.com/assets/10463138/26563310/8413510a-44d0-11e7-8c9f-4db09cb4a56c.gif)
It doesn't matter if animation is auto play = on.

I expect red line should be on same place after reselecting animationplayer.

**Link to minimal example project:**
[issue_save_and_animationplayer.gz](https://github.com/godotengine/godot/files/1036877/issue_save_and_animationplayer.gz)

together with #8994 you can get sometimes magically changes :smirk:

**Comment by kubecz3k** [comment]
Checked on Godot 3.0.2, seems to still be the case.

**Comment by DualMatrix** [comment]
Fixed in master, still relevant to 2.1.5

**Comment by akien-mga** [comment]
Thanks, closing as fixed in 3.1 then. At this stage only critical bug fixes will still be considered for the 2.1 branch.
