### ISSUE TITLE
Uninitialized variable is not null after while-if

### ISSUE THREAD

**Issue by Chtobi** [godotengine/godot#89958]
### Tested versions

Reproducible in:
v4.2.1.stable.official [b09f793f5]
v4.3.dev5.official [89f70e98d]

### System information

Windows 10 - GLES3 (Compatibility)

### Issue description

Probably related to [76569](https://github.com/godotengine/godot/issues/76569)

Uninitialized variable in the nested if scope after while loop takes value from some other previous variable.
It doesn't seem to be a text file reading issue, the same code without it will do the same.

### Steps to reproduce

```
extends Control

var save_file = "res://state.txt"
var current_player_str = "test_flag2"
var child_str = "test_flag3"

func read_current_player():
	
	if FileAccess.file_exists(save_file):
		var s_file = FileAccess.open(save_file, FileAccess.READ)

		var cur_player_rgxp = RegEx.new()		
		cur_player_rgxp.compile(r'flag="(' + current_player_str + r')"')
		
		var cur_player
		
		while !s_file.eof_reached():
			var s_string = s_file.get_line()
			cur_player = "yes"
			if s_string.contains(current_player_str):
				cur_player = cur_player_rgxp.search(s_string).get_string(1)
				if cur_player:
					print("Current player:", cur_player)
					break
		
		if cur_player:
			var f_parent # should be null!
			print ("f_parent:",f_parent) # BUG!
					
		else:
			print("Error! No string!")
	else:
		print("File does not exist!")

func _ready():
	pass # Replace with function body.
	read_current_player()
```

It prints:

```
Current player:test_flag2
f_parent:			flag="test_flag2"
```
But f_parent is uninitiallised and should be null.

### Minimal reproduction project (MRP)

[test_project_variables1.zip](https://github.com/godotengine/godot/files/14781193/test_project_variables1.zip)

**Comment by MrPersonDev** [comment]
Here is a minimized script with the same problem:
```
while true:
	var test1 = 3
	break

if true:
	var test2 # should be null
	print(test2) # prints '3'
```
Or with an 'if' statement if you would like:
```
if true:
	var test1 = 3
		
if true:
	var test2 # should be null
	print(test2) # prints 'false'
```
The problem is absent when the second block is a while loop:
```
if true:
	var test1 = 3
	
while true:
	var test2 # should be null
	print(test2) # prints null
	break
```
