### ISSUE TITLE
Saving a scene that is instanced in another open scene causes node duplication

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#89965]
### Tested versions

- happens in v4.3.dev.custom_build [d2f9245dd]
- doesn't happen in v4.3.dev5.official [c9c17d6ca]

### System information

linux

### Issue description

https://github.com/godotengine/godot/assets/71937306/a81b2b11-eff0-4e49-94e2-fb9a6810bc15

- if the containing scene is closed, this doesn't happen
- saving the instanced scene's scene causes duplication (which node is duped is unclear, though seem to be consistent for each setup)
- not shown in the above clip, but it may happen to several nodes (maybe when there's several instanced and open scenes).
![image](https://github.com/godotengine/godot/assets/71937306/6d8bf641-7fe0-4842-9d80-cefa04e6a525)
in this example, with only my `Game` and `Player` scenes open, when saving the player, it duplicates consistently the `Player` and `MainMenu` (empty control) nodes.

### Steps to reproduce

- create scene `instance.tscn`
- create scene `parent.tscn` and instance the instance
- make sure both are open in the editor
- save `instance.tscn` and switch back to `parent.tscn`
- there should be a new node in the tree

### Minimal reproduction project (MRP)

[bug-node-dupe-on-save.zip](https://github.com/godotengine/godot/files/14784009/bug-node-dupe-on-save.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/89877
