### ISSUE TITLE
control text format problem

### ISSUE THREAD

**Issue by Uhako** [godotengine/godot#89976]
### Tested versions

godot 4.2.1 stable

### System information

windows11 godo4.2.1 stable

### Issue description

I want to edit label text in editor and add %s in it to use stringformat.
However, it didn't work in programs.
![image](https://github.com/godotengine/godot/assets/48437004/74098558-7cfe-4ebf-8ac0-605aaf57de9b)
![image](https://github.com/godotengine/godot/assets/48437004/a7d8b2a6-d746-4fcb-9e3d-1962e3ce1293)

### Steps to reproduce

```gdscript
UI_datalevel.text = "%s cm" (edited in editor)

var UI_datalevel:Label
var base_datalevel:float = 10.2
...

print(UI_datalevel.text%str(base_datalevel).pad_decimals(1)) #data is ok
UI_datalevel.text = UI_datalevel.text%str(base_datalevel).pad_decimals(1) #wrong
```

### Minimal reproduction project (MRP)

```gdscript
UI_datalevel.text = "%s cm" (edited in editor)

var UI_datalevel:Label
var base_datalevel:float = 10.2
...

print(UI_datalevel.text%str(base_datalevel).pad_decimals(1)) #data is ok
UI_datalevel.text = UI_datalevel.text%str(base_datalevel).pad_decimals(1) #wrong
```

**Comment by AThousandShips** [comment]
You are calling this method multiple times and you don't restore the text to the format string, this means it won't have any `%s` in it when you run it the second time

You need to make sure the input is correct

In the future please ask support questions in the [forums](https://forum.godotengine.org/), this is for bug reporting and please check that you are seeing a bug and not user error
