### ISSUE TITLE
Viewport mouse position returns incorrect value inside _Process of tooltip RichTextLabel

### ISSUE THREAD

**Issue by dbampersand** [godotengine/godot#89997]
### Tested versions

- Reproducible in Godot v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5186) - 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz (16 Threads)

### Issue description

When using GetViewport().GetMousePosition() inside of a script attached to a RichTextLabel, it only returns the correct position half of the time - the other half, it returns a negative number which moves relative to the mouse. If setting the position of the PopupPanel, it will flicker between the correct position and the incorrect position. 

Edit: Seems to be the entire Viewport object returned is invalid as trying to get Width/Height of it returns 127 when outside of it returns 1152.

Output from GD.Print of the mouse coordinates looks as such (mouse remained static):

```
(-10, -10)
(472, 330)
(-10, -10)
(472, 330)
```

(N.B. There exists a workaround - create a public static Vector2 and assign it in another regular node's _Process function with GetViewport().GetMousePosition())

### Steps to reproduce

I've included a reproduction project: start it and the left button is the broken one, and the right one is the workaround I'm using for now in case any one else comes up against this issue. Mouse over the left one and observe the visibly broken behaviour of the PopupPanel jittering between positions and the console output of the mouse position.

Create a main (runnable) scene and add a Button to it.

Create a new scene with a RichTextLabel as the root node and no other nodes. Attach this script to it:

```
using Godot;
using System;

public partial class Tooltip : RichTextLabel
{
	// Called when the node enters the scene tree for the first time.
	public override void _Ready()
	{
	}

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{
		PopupPanel p = GetParent() as PopupPanel;
		if (p != null)
		{
			Vector2 mouse = GetViewport().GetMousePosition();
			p.Position = new Vector2I((int)mouse.X,(int)mouse.Y);
			GD.Print(mouse);
		}
	}
}
```

In the main scene, attach this script to a Button control, give it a tooltip in the editor, and attach the scene made earlier to the customTooltip variable.  

```using Godot;
using System;

public partial class ButtonWithTooltip : Button
{
	[Export]
	public PackedScene customTooltip;


    public override Control _MakeCustomTooltip(string from)
    {
	RichTextLabel label = (RichTextLabel)customTooltip.Instantiate();
	label.Text = from;
        return label;
    }
    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
    }

	// Called every frame. 'delta' is the elapsed time since the previous frame.
	public override void _Process(double delta)
	{

	}
}
```

Run this, and mouse over the button for half a second. Observe the jitter in the position and the output in the console. 

### Minimal reproduction project (MRP)

[TooltipTest.zip](https://github.com/godotengine/godot/files/14796224/TooltipTest.zip)

**Comment by ajreckof** [comment]
when reporting a bug that is not specific to the mono version please make an MRP and provide code using GdScript as not every contributor has a setup for mono. Here is the MRP in GdScript : [Archive.zip](https://github.com/godotengine/godot/files/14884656/Archive.zip)

**Comment by AThousandShips** [comment]
Closing as per the above, if you are still having issues when using corrected code please open a new issue
