### ISSUE TITLE
Surface Pro and TouchScreenButton do not work

### ISSUE THREAD

**Issue by kattkieru** [godotengine/godot#90]
Hi there,

I found that the Surface Pro's touch screen is not detected by Godot, even when using Emulate Touch Screen in the prefs.  TouchScreenButtons do not seem to receive touches.

On Windows 8, if emulate touch screen is active and you're on a system where multitouch is supported, it'd be nice for Godot to switch and allow the touch screen buttons to work correctly.  However, if emulate touch screen is off, Windows 8 should react as would a regular desktop system.

As an aside, it would also be nice if Surface Pro swipes, pinches, and two-finger pans worked in the editor.  Swiping would scroll lists (which it tries to do currently, but when you release it changes the selected item; scrolling in the code editor with a finger does not work and would be preferable to trying to select), two-fingers would pan viewports, and pinches could be used for zooms.  Perhaps a double-tap with a finger in the game viewport could also return to default zoom.

Thanks!

**Comment by tofuhead** [comment]
any news on progress of this?

I have a Lenovo Flex minilaptop running Windows 8.1...  the screen is also touchscreen, and I have trouble on getting that work with Godot. 

TouchScreenButtons don't appear at all .. OS.has_touchscreen_ui_hint() gives False.. 
regular buttons I can use and click.. but not press and hold for example, because Windows handles Press+Hold+Release as a single event which is right mouse button. just pressing down on touchscreen doesn't emit any signals. 

.b

**Comment by reduz** [comment]
Probably would be better if you want to contribute support for this, as I
dont have the harware to do it

**Comment by punto-** [comment]
I put some code on os_windows to handle touch events a while ago, but it
was using Windows 7 apis so I don't think it was ever tested. I think
windows xp had similar apis tho, at least drawing boards worked on them
(not the same, but pretty close).

https://github.com/okamstudio/godot/blob/master/platform/windows/os_windows.cpp#L640

**Comment by tofuhead** [comment]
if there is something I can help you with just say.... 
for C/C++ code I'm not much for use, but debugging, testing, or giving info... yes. 

i try to check out the current code.. 

.b

**Comment by akien-mga** [comment]
Anybody having a Surface Pro that can check the status of this issue in the current master branch?

**Comment by kattkieru** [comment]
I can try a build this weekend.  Thanks for keeping at this!

**Comment by kattkieru** [comment]
I had a look on the latest nightly from the website.  Results are promising but I want to run some more tests, as I'm not sure if the errors I was getting were from logic in the demo files or from Godot itself.  I'll check back again soon.  Thanks for keeping on this issue!

**Comment by akien-mga** [comment]
Any new results @kattkieru?

**Comment by akien-mga** [comment]
Closing, as the above comments suggest that the Surface Pro's touch screen is now properly detected by Godot. If it's not the case, please comment and I'll reopen. If it's detected but has bugs, feel free to open new issues for each bug so that they can be addressed further.
