### ISSUE TITLE
Enabling blend split on a DirectionalLight with shadows enabled, breaks the light

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9000]
**Ubuntu 17.04 - Godot version: Master 5567e898d **

**Issue description:**
Enabling Blend Split on a directional light, breaks the light.

Output says:

> ERROR: _display_error_with_code: SceneShaderGLES3: Fragment Program Compilation Failed:
> 0(1124) : error C1115: unable to find compatible overloaded function "mix(float, float)"
> 
>    At: drivers/gles3/shader_gles3.cpp:167.
> ERROR: get_current_version: SceneShaderGLES3: Fragment Program Compilation Failed:
> 0(1124) : error C1115: unable to find compatible overloaded function "mix(float, float)"
> 
>    At: drivers/gles3/shader_gles3.cpp:455.
> ERROR: get_current_version: Method/Function Failed, returning: __null
>    At: drivers/gles3/shader_gles3.cpp:463.

The fragment program line with the error (1124) says:

> shadow=mix(shadow, sample_shadow(directional_shadow,directional_shadow_pixel_size,pssm_coord2.xy,pssm_coord2.z,light_clamp));

**Steps to reproduce:**
Enable Shadows and Blend Split on a DirectionalLight.

This works on a late january build (I don't know if the effect is the correct one but it don't break the light).

**Comment by karroffel** [comment]
Booooo, I expected more for the issue 9000...

**Comment by eon-s** [comment]
Ouch!, sorry, I use to ruin the fun :sweat_smile:

**Comment by eon-s** [comment]
Blend splits seems to be working fine now.
