### ISSUE TITLE
`scene\resources\text_paragraph.cpp:420 - Condition "p_font.is_null()" is true. Returning: false` on editor startup

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#90001]
### Tested versions

Starting with Commit 86415f02452dbf6de85325d3321fd7ec7fba9e94 

### System information

Godot v4.3.dev (86415f024) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

I see this error on every startup, even with an empty project:

`scene\resources\text_paragraph.cpp:420 - Condition "p_font.is_null()" is true. Returning: false`

### Steps to reproduce

Start a new empty project with Godot at commit 86415f024 or later

### Minimal reproduction project (MRP)

Any empty project will do it.

**Comment by chrisl8** [comment]
It seems to be this line

https://github.com/godotengine/godot/blob/86415f02452dbf6de85325d3321fd7ec7fba9e94/editor/debugger/editor_debugger_tree.cpp#L44

Removing it makes the error go away, but easter egging here without understanding the ramifications.

**Comment by MarkoSFG** [comment]
Moving the call remote_scene_tree->set_auto_translate_mode(AUTO_TRANSLATE_MODE_DISABLED); from EditorDebuggerTree::EditorDebuggerTree() constructor to the bottom of EditorDebuggerNode:EditorDebuggerNode() fixes the issue, add remote_scene_tree->set_auto_translate_mode(AUTO_TRANSLATE_MODE_DISABLED); to bottom of that EditorDebuggerNode constructor instead.

(in other words the call to prevent auto translate happens too early at the moment)

**Comment by MarkoSFG** [comment]
@akien-mga can you take a look please?

**Comment by timothyqiu** [comment]
Probably the same cause as described in https://github.com/godotengine/godot/issues/89804#issuecomment-2016531885.

`NOTIFICATION_TRANSLATION_CHANGED` could be propagated from parent nodes now, so we either avoid assuming theme caches are ready during the notification, or we avoid changing this property in the nodes' own constructor.

https://github.com/godotengine/godot/blob/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89/scene/gui/tree.cpp#L4350-L4354

The initial theme cache update is in `NOTIFICATION_POSTINITIALIZE`. So moving the call outside the constructor works.
