### ISSUE TITLE
Problems in the demo for 4.2

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#90006]
### Tested versions

Godot 4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

I noticed a few problems with the demo examples.

1. MSAA
In the 3D Graphics Settings example, when I set the settings to maximum, I have a display problem, when I turn off MSAA the problem disappears.
I also noticed that this problem does not occur on the “Low” and lower settings.
![1](https://github.com/godotengine/godot/assets/130399274/52c3d59b-3b43-4b01-b90d-e5a71f68424e)
This problem is also observed when "Multisample Antialiasing" is enabled in the Godot Third-Person Shooter Demo example
![3](https://github.com/godotengine/godot/assets/130399274/48763763-c49e-4d9a-a900-ed5b9955a55b)

2. SDF Global Illumination
in the Physical Light and Camera Units example there is a problem when enabling "SDF Global Illumination".
![2](https://github.com/godotengine/godot/assets/130399274/a6a6468a-4d49-4d2c-8861-b04a09990465)

All these problems are similar to the problems that I discovered earlier #85549, perhaps they will no longer be solved in 4.2 for AMD cards, but still.

### Steps to reproduce

Everything is described above

### Minimal reproduction project (MRP)

All these demos can be installed through Godot itself

**Comment by JekSun97** [comment]
These problems only occur in Forward+ mode

**Comment by clayjohn** [comment]
Thanks for the report! Since this issue has already been fixed, I will close it as fixed. 

For clarity, we don't keep bug reports open for issues that have already been fixed. Even if the bug exists in older versions. We expect that users will update to newer versions if they want to benefit from a bug fix.

**Comment by JekSun97** [comment]
@clayjohn  Unfortunately I have this problem again in 4.4 beta1 :'(, maybe I should open a new issue to increase its priority?

![Image](https://github.com/user-attachments/assets/636d33ad-cba7-4013-9adb-f723c4006be4)
