### ISSUE TITLE
TouchScreenButton node is not working while i am using Camera2D abd focusing on the sprite

### ISSUE THREAD

**Issue by Anythingusable** [godotengine/godot#90008]
### Tested versions

Didn't test

### System information

Godot 4.0- Android

### Issue description

I am on Godot 4.0 in mobile version and i was following a tutorial and added three TouchScreenButtons and now when i am using Camera2D to the CharacterBody2D. The Camera is following the Sprite and not showing the buttons.

### Steps to reproduce

The tutorial i was following was:
https://youtu.be/5V9f3MT86M8?si=afm2SS244jKop-vi
And as i was on mobile, i added three input buttons of TouchScreenButtons(in the main scene) and now when i am using Camera2D the TouchScreenButtons can't be shown

### Minimal reproduction project (MRP)

Hibbjkkn

**Comment by AThousandShips** [comment]
Please try 4.2.1 or 4.1.3, 4.0 is no longer supported

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
