### ISSUE TITLE
Light2D in ADD mode addes alpha channel

### ISSUE THREAD

**Issue by qian2501** [godotengine/godot#90005]
### Tested versions

windows10, 3.5.3

### System information

windows10, 3.5.3

### Issue description

So this is a test setup, a ColorRect with color 0.5 at the bottom, then a Light2D with LightMask, then 2 ColorRect without LightMask with a rough subtraction/threshold shader attached.
The subtraction amount is 0.5(after this the light texture should be the only visible thing), then threshold at 0.6, above is set to 1.0, below to 0.0. then I have this weird image here:

![image](https://github.com/godotengine/godot/assets/51772064/fdf226cf-333f-4ebd-bb9e-e01a0b26380a)

Even the black area of the light texture get lit after the threshold, also after subtraction the light texture is not visible:

![image](https://github.com/godotengine/godot/assets/51772064/0ea7fd5d-0e32-4ed6-8f5d-66584a658632)

None of these behaviour match what "ADD" means. Am I having wrong understanding about these light or shader stuff?

Also quote from doc:

> MODE_ADD = 0
> 
> Adds the value of pixels corresponding to the Light2D to the values of pixels under it. This is the common behavior of a light.

### Steps to reproduce

[test.zip](https://github.com/godotengine/godot/files/14799895/test.zip)

### Minimal reproduction project (MRP)

see test.zip

**Comment by qian2501** [comment]
I just find out that hard coding alpha to 1.0 in the result of subtraction produces the right result, it seems alpha is broken after Light2D.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/49251.
