### ISSUE TITLE
Inconsistent treatment of load() from relative path

### ISSUE THREAD

**Issue by Mercerenies** [godotengine/godot#90029]
### Tested versions

- Reproducible in: Godot Engine v4.2.1.stable.official (b09f793f5)
- Reproducible in: Godot Engine v4.02.stable.official (7a0977ce2)
- Reproducible in: Godot Engine v3.5.stable.official (991bb6ac7)

### System information

Fedora Linux 37 (Workstation Edition) - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 620 (WHL GT2) () - Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 Threads)

### Issue description

Godot seems to treat relative paths in `load()` calls very inconsistently. From [the documentation](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-method-load) for method `load`,

> **Important:** The path must be absolute. A relative path will always return null.

So I would fully expect `load("./SomeScript.gd")` to return `null`. However, it seems to do a sort of secondary load and produces a bizarre object distinct from `load("res://SomeScript.gd")`. See reproduction steps below.

### Steps to reproduce

Define a script file called `SomeScript.gd` whose contents are

```
extends RefCounted # extends Reference on Godot 3
```

Then define the main scene `Main.gd`

```
extends Node2D

const SomeScript = preload("res://SomeScript.gd")

# Called when the node enters the scene tree for the first time.
func _ready():
    # These two lines print the same
    print(load("res://SomeScript.gd"))
    print(load("res://SomeScript.gd"))
    # These two lines print the same, but distinct from the above.
    print(load("./SomeScript.gd"))
    print(load("./SomeScript.gd"))

    print(SomeScript.new() is SomeScript)  # true
    print(load("res://SomeScript.gd").new() is SomeScript)  # true
    print(load("./SomeScript.gd").new() is SomeScript)  # false
```

Based on the documentation, I would expect the `load("./SomeScript.gd")` lines to return `null`. However, if that's not correct, then I would expect them to return the same object as `load("res://SomeScript.gd")`. Currently, the two different `load` calls return distinct and incompatible objects, which just creates confusion.

### Minimal reproduction project (MRP)

[LoadBug.zip](https://github.com/godotengine/godot/files/14809546/LoadBug.zip)

**Comment by AThousandShips** [comment]
This is because of a minor issue probably, the path is converted to `res://./SomeScript.gd`, which is likely cached differently, can see about a fix for that part, it likely needs a normalisation of the path

The documentation should be clarified as well

**Comment by AThousandShips** [comment]
The documentation should probably be updated to say instead that:
Relative paths will be prefixed with `res://` and *not* relative to the script it is called from.

Or similar

**Comment by Mercerenies** [comment]
@AThousandShips That was my first thought as well, since (during the course of debugging this issue) I noticed that Godot _prints_ the path as `res://./SomeScript.gd` even if the `res://` wasn't there in the `load()` call. But if you explicitly load `res://./SomeScript.gd` (with the `res://`), then everything actually works. You get one consistent object, and the `is` checks pass like they should. The problem only occurs if the `res://` is _missing_ from the `load()` call.

**Comment by AThousandShips** [comment]
Indeed, see the linked issue, it's due to a specific path, this ensures that the loaded object is the exact same instance
