### ISSUE TITLE
Editor/Game Freezes with GTX 650 card

### ISSUE THREAD

**Issue by M77mdsD** [godotengine/godot#90023]
### Tested versions

After I installed a Nvidia GTX 650 card the game and the editor started randomly freezing (It freezes mostly in-game).
I was using an Intel HD Graphics 620 and everything was working fine, The only downside is that the old one has 2GB of VRAM and the new one has 1GB only.
I found some people talking about the same issue with Nvidia cards in general but I didn't find a fix on those posts.

### System information

Windows 11 - Godot v4.2.1 - Vulkan

### Issue description

Random Freezes both in-editor and in-game.
the editor will freeze mostly while rotating the camera and doing other actions.
the game freezing seems random to me but they happen every 2 seconds or so.

### Steps to reproduce

Run The editor with a GTX 650 graphics card

### Minimal reproduction project (MRP)

It freezes in new projects too.

**Comment by Calinou** [comment]
Try using the Compatibility rendering method, as Vulkan support on Kepler GPUs is incomplete and has many issues.

**Comment by M77mdsD** [comment]
Compatibility mode works fine, is this something fixed/will be in 4.3?

**Comment by Calinou** [comment]
> Compatibility mode works fine, is this something fixed/will be in 4.3?

You can try [4.3.dev5](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-5/) on your machine, but if it's not fixed there, it's unlikely it ever will. NVIDIA has dropped Kepler support in 2021, so the drivers aren't being updated anymore. To make things worse, laptop Kepler GPUs have never supported Kepler either, so it's always been a desktop-only thing.

**Comment by M77mdsD** [comment]
Yeah, I get it.
Tried it but looks like it isn't helping.
