### ISSUE TITLE
Spot / Omni Light3D is not rendering properly on MeshInstance3D generated using ImmediateMesh

### ISSUE THREAD

**Issue by Dev-Emeraldy** [godotengine/godot#90020]
### Tested versions

- Reproducable in v4.2.stable.official [46dc27791]
- Do not listed as fixed in newer versions

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

Light doesn't work like intended on MeshInstance3D, wich was generated in script like this :

- Creating instance of ImmediateMesh and assign it to something (ex. "obj")

- Calling surface_begin() with parameter Mesh.PRIMITIVE_TRIANGLE_STRIP or Mesh.PRIMITIVE_TRIANGLE (on "obj")

- Then, if we using Mesh.PRIMITIVE_TRIANGLE_STRIP calling surface_add_vertex like this (on "obj") to draw two triangles

```gdscript
	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
	obj.surface_add_vertex( Vector3( 1, 0, 0 ))
	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
	
	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
	obj.surface_add_vertex( Vector3( 0, 0, 1 ))
```	

- Calling surface_end() on "obj"

- Creating instance of MeshInstance3D and assign it to something (ex. "node")

- Setting "node.mesh" parameter to "obj"

- Adding "node" to scene ```$".".add_child(node)```

To be more specific : light cuts from direction of positive z-axis

![image](https://github.com/godotengine/godot/assets/154672921/b1b24d8c-a90f-49a8-b520-f7ff28b8c861)

Even when moving omnilight (so its should emit light in all directions)

![image](https://github.com/godotengine/godot/assets/154672921/811545bf-fe10-45e6-99e9-b8943c959878)

I believe this is a bug....

_(But maybe I am doing something wrong)_

P.S: It works fine on MeshInstance3D with "mesh" set to PlaneMesh from presets

![image](https://github.com/godotengine/godot/assets/154672921/2eafa806-b0ff-43cb-adbf-fa14bd97b793)

### Steps to reproduce

Create a new 3d scene add to it:

- Root Node3D
- OmniLight3D or SpotLight3D
- Camera3D maybe

And attach this script to root node of scene (Node3D)

```gdscript

extends Node3D

func _ready():
	
	var A = 10
	
	var obj = ImmediateMesh.new()
	obj.surface_begin(Mesh.PRIMITIVE_TRIANGLE_STRIP)

	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
	obj.surface_add_vertex( Vector3( A, 0, 0 ))
	obj.surface_add_vertex( Vector3( A, 0, A ))
	
	obj.surface_add_vertex( Vector3( A, 0, A ))
	
	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
	obj.surface_add_vertex( Vector3( 0, 0, A ))
	obj.surface_end()	
	
	var node = MeshInstance3D.new()
			
	node.mesh = obj
	$".".add_child(node, true)

```

### Minimal reproduction project (MRP)

[Bug-project.zip](https://github.com/godotengine/godot/files/14805713/Bug-project.zip)

**Comment by AThousandShips** [comment]
You might need to set up the normals properly

**Comment by Dev-Emeraldy** [comment]
I also tried UV and color. Issue persists

**Comment by AThousandShips** [comment]
You should always have normal normals, so no `(10, 0, 0)`, did you make sure the normal was the correct direction?

**Comment by AThousandShips** [comment]
Try flipping one of the triangles, they look wound the opposite direction:
```gdscript
	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
	obj.surface_add_vertex( Vector3( 1, 0, 0 ))
	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
	
	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
	obj.surface_add_vertex( Vector3( 0, 0, 1 ))
	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
```

**Comment by Dev-Emeraldy** [comment]
> Try flipping one of the triangles, they look wound the opposite direction:
> 
> ```gdscript
> 	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
> 	obj.surface_add_vertex( Vector3( 1, 0, 0 ))
> 	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
> 	
> 	obj.surface_add_vertex( Vector3( 1, 0, 1 ))
> 	obj.surface_add_vertex( Vector3( 0, 0, 1 ))
> 	obj.surface_add_vertex( Vector3( 0, 0, 0 ))
> ```
> 
> Also try just using `PRIMITIVE_TRIANGLE`, the setup you have is not for a triangle strip

Already tried different PRIMITIVEs, issue persists

**Comment by AThousandShips** [comment]
*And* the different order?

**Comment by Dev-Emeraldy** [comment]
Oh i fixed it, i was changing normals AFTER surface_end

THANKS I didnt know it is required to setup normals

**Comment by AThousandShips** [comment]
Good that it worked out!

In the future I'd suggest first bringing up issues like this in the [forums](https://forum.godotengine.org/) to see if there's some issue with how it's done before making a report :) there's usually more time and people to help with such there, so it helps everyone

**Comment by Dev-Emeraldy** [comment]
> Good that it worked out!
> 
> In the future I'd suggest first bringing up issues like this in the [forums](https://forum.godotengine.org/) to see if there's some issue with how it's done before making a report :) there's usually more time and people to help with such there, so it helps everyone

👍
