### ISSUE TITLE
Android Cannot access a file in the destination directory

### ISSUE THREAD

**Issue by gaoyan2659365465** [godotengine/godot#90033]
### Tested versions

4.3.dev5

### System information

Windows10

### Issue description

Android export error
```
editor/export/editor_export_platform.h:182 - 导出: 无法复制并更名导出文件：
  
  
  > Configure project :
  WARNING: The option setting 'android.overridePathCheck=true' is experimental.
  The current default is 'false'.
  
  > Task :copyAndRenameDebugApk FAILED
  
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Execution failed for task ':copyAndRenameDebugApk'.
  > Cannot access a file in the destination directory. Copying to a directory which contains unreadable content is not supported. Declare the task as untracked by using Task.doNotTrackState(). For more information, please refer to https://docs.gradle.org/8.2/userguide/incremental_build.html#disable-state-tracking in the Gradle documentation.
     > Failed to create MD5 hash for file content.
  
  * Try:
  > Run with --stacktrace option to get the stack trace.
  > Run with --info or --debug option to get more log output.
  > Run with --scan to get full insights.
  > Get more help at https://help.gradle.org.
  
  BUILD FAILED in 2s
  1 actionable task: 1 executed
  
  Attempting to parent and popup a dialog that already has a parent.
```

Gradle
If an error occurs in the English path, it can be exported in the Chinese path
The same project can be exported normally in 4.3dev2

### Steps to reproduce

Create a new empty project, direct Android export

### Minimal reproduction project (MRP)

without

**Comment by ReneSerra** [comment]
Same issue (Godot 4.2.2) when exporting an android .apk file.

Workaround : if the export template is also used to "one-click deploy", the similar APK file is created (without error) in the project's sub-directory **android\build\build\outputs\apk\debug** (in any case, it worked for me).

**Comment by Clemkd** [comment]
I'm facing the same issue. 

In my case, restarting Godot Engine as admin worked for me.

**Comment by Gove2004** [comment]
![屏幕截图 2024-05-31 114110](https://github.com/godotengine/godot/assets/150231701/753cf925-4f63-4bbf-a356-a84fbcc5bd8b)
want's  up?Launching Godot as administrator don't work for me.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/90802

**Comment by the-Explorer-fr** [comment]
> Fixed by #90802

i have the same prolem didn't understand how to fix it with this link

**Comment by ReneSerra** [comment]
Try to replace the "bad" Android build template with the new (fixed) : 
- remove res://android/build directory
- Project > Install Android Build Template...

**Comment by Gove2004** [comment]
I don't know what's going on, but when I try again in a few days, I found out that it works.

**Comment by breakmt** [comment]
Have the same in 4.2.2 stable. 
That's why I quit Godot.
