### ISSUE TITLE
ItemList item text is not localized, unless set through code.

### ISSUE THREAD

**Issue by bitegw** [godotengine/godot#90041]
### Tested versions

- Reproducible in v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.4601) - AMD Ryzen 5 5600 6-Core Processor (12 Threads)

### Issue description

ItemList items do not get localized. Can be worked around by calling ```itemList.AddItem(Tr("SOMETHING"));``` (or gdscript equivalent). But it doesn't seem like intended behavior to me.

### Steps to reproduce

1) Create .csv file with
```
keys,en,fi
SOMETHING,"English","Finnish"
```
And save it.
1) In project > Localization select languages you want, eg. Finnish, English. and reference the automatically generated translation files for English and Finnish.
You also have to set the locale in Project settings.
2) Add a Label and give it the key SOMETHING in caps.
3) Add ItemList and add entry to it with the text SOMETHING, again, in all CAPS. 

Run the scene. The label is localized but the itemList isn't.

### Minimal reproduction project (MRP)

N/A

**Comment by saierXP** [comment]
It seems to have been fixed in version [4.3.dev5](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-5/#downloads), can you confirm it again?

**Comment by AThousandShips** [comment]
Closing as confirmed, if it has not please comment here and this can be reopened
