### ISSUE TITLE
Export variable type saved in an inherited scene file is changed from what mentioned in script file causing errors

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#90044]
### Tested versions

4.2.2.rc2

### System information

Windows 11

### Issue description

When you create an exported variable in inherited scene and save it. the type changes in the scene file, causing errors while accessing the variable
When running or opening the scene causes error like 
```
E 0:00:00:0643   assign: Cannot assign contents of "Array[NodePath]" to "Array[StringName]".
  <C++ Error>    Method/function failed.
  <C++ Source>   core/variant/array.cpp:260 @ assign()
```

This is a serious issue as without this it limits a lot of ways development can happen. 
With this bug the project I am working on will have to be redesigned from grounds up again. It will delay a lot.

### Steps to reproduce

Create a Scene (`Parent`)
Create a Scene (`Child`) inheriting from `Parent`

Add two exported variables into `Child` like this:
```gdscript
@export var nodes:Array[NodePath] = []
@export var node_names:Array[StringName] = []
```

when you save the scene it is saved as 
```tscn
[node name="Child" instance=ExtResource("1_xbhsf")]
script = ExtResource("2_ct2j7")
nodes = Array[NodePath]([])
node_names = Array[NodePath]([])
```  

```gdscript
func _ready():
	node_names.append(&"arrat")
will cause the error

#E 0:00:00:0643   assign: Cannot assign contents of "Array[NodePath]" to "Array[StringName]".
#  <C++ Error>    Method/function failed.
#  <C++ Source>   core/variant/array.cpp:260 @ assign()

```

It works if the scenes are not inherited

### Minimal reproduction project (MRP)

Will add a project if there is no duplicates found and it seems like a genuine issue.

For me it is as the type saved in the scene vs type mentioned in script are different, causing the issue.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/81526
