### ISSUE TITLE
Missing Godot Engine Contributors copyright line in the About box

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9005]
Currently, the about box copyright is different from what we have on the code files:

![about](https://cloud.githubusercontent.com/assets/5599796/26610610/fad329ba-457e-11e7-9967-3840cd5f1706.png)

Compared to:

```
/* Copyright (c) 2007-2017 Juan Linietsky, Ariel Manzur.                 */
/* Copyright (c) 2014-2017 Godot Engine contributors (cf. AUTHORS.md)    */
```

They should match.

**Comment by reduz** [comment]
we need to change it to have the full list of contributors

**Comment by noshyaar** [comment]
Some names have special characters and can't be displayed correctly.

![screenshot from 2017-05-31 09-11-35](https://cloud.githubusercontent.com/assets/26753932/26612903/f6ec7398-45e1-11e7-8067-880399ecf2bd.png)

**Comment by reduz** [comment]
that shouldn't be the case, the editor font has most of the meaningful
unicode sets
