### ISSUE TITLE
Scene File 3D Object Missing Transform

### ISSUE THREAD

**Issue by SoapSpangledGames** [godotengine/godot#90051]
### Tested versions

4.2 stable.

### System information

Godot v4.2.stable - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 (nvidia; 470.199.02) - AMD FX(tm)-8350 Eight-Core Processor (8 Threads)

### Issue description

When saving a 3D scene file, I have an object (a door) that always loads at (0,0,0), even though I specify (-2.171, 8.796, -19.122) as its location in the editor:

![image](https://github.com/godotengine/godot/assets/55257920/29067074-53ea-4682-9456-c79bfd436ed9)

That puts the door where it should be (the orange highlight):

![image](https://github.com/godotengine/godot/assets/55257920/ace93652-1d29-46ac-8abe-98993e32bc22)

When I run the game, the door always appears at (0,0,0). I looked in the *.tscn file, and found that this object doesn't have a Transform3D:

![image](https://github.com/godotengine/godot/assets/55257920/e444935f-cc9a-4ee1-823d-3e9f30cf046a)

I exited the editor, copied a transform from another object, entered the correct coordinates, and reloaded Godot and the project. At that point, the object appeared at its proper location. However, when I run the program, and the editor autosaves, the Transform3D entry in the scene file is once again gone.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please provide a minimal project displaying this issue, this isn't sufficient information to tell what's wrong

However, is there an animation player in the sub scene? Does it animate the position of the door? If it does then that's because of the reset on save and reset track, that's not a bug

**Comment by SoapSpangledGames** [comment]
There is indeed an AnimationPlayer in the scene that animates the door. I have other subscenes with AnimationPlayers, and the animations are always relative to the object.

However, all of my other AnimationPlayers animate objects within the scene, and not the scene itself -headsmack-, which is why I wasn't able to reproduce it anywhere else. The minimal project I tried to create didn't have an AnimationPlayer, so it wasn't reproducing the issue -sigh-.

I was trying to rotate the entire scene so the collisions would rotate with it, then forgot I had done that. I'll change my animations, and see if that helps. Thanks!

**Comment by AThousandShips** [comment]
If the animation affects the transform, it has a reset track which will reset the position, this is a known problem, see (among other reports, can't find the others at the moment):
* https://github.com/godotengine/godot/issues/78982
