### ISSUE TITLE
Feature request: Make colons optional in GDScript

### ISSUE THREAD

**Issue by CylonMuffins** [godotengine/godot#9006]
I'd prefer skipping the end of line ":" on functions and control structures if / for /while and so on.
I think it looks neater and saves a lazy key stroke :)

**Comment by akien-mga** [comment]
I don't think it's possible, nor desirable, but I'll let parser experts answer with some technical details.

**Comment by reduz** [comment]
No, I don't think it's possible.. also not really worth it..

**Comment by akien-mga** [comment]
Closing then, it won't happen, sorry.
