### ISSUE TITLE
Area2D with Monitorable off doesn't register StaticBody2D

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot#90077]
### Tested versions

Only tested in v4.2.1

### System information

Godot v4.2.1.stable - macOS 14.3.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

A moving `Area2D` with `monitoring` enabled and `monitorable` _disabled_ registers `CharacterBody2D` and `RigidBody2D` entering its area, but **not** `StaticBody2D`. However, when `monitorable` is _enabled_, it **does** register the `StaticBody2D`.

If this was somehow intentional, this is very much in contrast to the conceptual distinction created by the Area2D's `monitoring` and `monitorable` booleans, which enable the area to look for bodies or be found by bodies respectively – or so you would expect, especially after reading their descriptions.

### Steps to reproduce

1. Run the main scene of the MRP.
2. Notice how the area only prints the `CharacterBody2D` and `RigidBody2D` in the output, and not the `StaticBody2D`.
3. Enable `monitorable ` on the Area2D object in the scene and run the scene again.
4. Notice how the area now prints all bodies entering its area.

### Minimal reproduction project (MRP)

[AreaVsStaticExample.zip](https://github.com/godotengine/godot/files/14817152/AreaVsStaticExample.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/17238
