### ISSUE TITLE
GPUParticles2D#emit_particle's color parameter doesn't work

### ISSUE THREAD

**Issue by ctrlraul** [godotengine/godot#90070]
### Tested versions

4.3.dev5

### System information

Windows10 - Vulkan

### Issue description

The `color` argument appears to be ignored in `GPUParticles2D`'s `emit_particle` method, despite passing the `EmitFlags.EMIT_FLAG_COLOR` flag.

### Steps to reproduce

See MRP

### Minimal reproduction project (MRP)

[particlestest.zip](https://github.com/godotengine/godot/files/14815434/particlestest.zip)

**Comment by AThousandShips** [comment]
Thank you for your report, consolidating in:
* https://github.com/godotengine/godot/issues/76360
