### ISSUE TITLE
GDExtension: `object_set_instance()` does not update object info required for hot reloading

### ISSUE THREAD

**Issue by Bromeon** [godotengine/godot#90085]
### Tested versions

4.2-stable onwards

### System information

Windows 10

### Issue description

In short, GDExtension currently expects class instantiation to always go through `ClassDB::instantiate`, as some book-keeping for hot reloading is not updated otherwise. However, this is quite limiting as it prevents e.g. passing arguments to a newly instantiated class.

From the [godot-rust downstream issue](https://github.com/godot-rust/gdext/issues/543):

> Since Godot 4.2 the engine has extension (hot) reloading. During reloading, the engine [creates a backup of the class properties that have been exposed to godot](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/extension/gdextension.cpp#L1015-L1056) and once the extension has been reloaded [it recreates the extension parts of all the classes](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/extension/gdextension.cpp#L1138-L1150) that have been defined by the extension.
> 
> Important here is that the engine tries to track all the instances which have been created for an extension class so that they can be reloaded later on. This happens in [`ClassDB::instantiate`](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/object/class_db.cpp#L370-L374).
> 
> Unfortunately when gdext is creating classes from inside rust, it never goes through `ClassDB::instantiate`. It rather creates a new instance of the base class via `ClassDB::instantiate` and then assigns the rust instance to that base object via [`object_set_instance`](https://github.com/godot-rust/gdext/blob/92dce9c4787670b7b209d402d4b1feea430eb9cc/godot-core/src/registry.rs#L574). The engine does not track these assignments as new instances of an extension class.
> 
> When the extension is then reloaded, none of the class instances are reloaded as the `instance` list of the `extension_class` is empty.
> 
> [...]
> 
> On the other hand, the engine could also move the instance tracking to `ClassDB::set_object_extension_instance`.

If `Object::set_object_extension_instance` also updates these parts, hot reloading would also work for instances created by the binding that do _not_ go through `ClassDB::instantiate()`.

### Steps to reproduce

1. Instantiate a new class object in a binding, without going through `ClassDB::instantiate`.
2. Wire it up to an extension instance using `object_set_instance` (internally calling `ClassDB::set_object_extension_instance`)
3. Hot-reload Godot
4. The objects are not reloaded, as they haven't been registered 

### Minimal reproduction project (MRP)

N/A

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/90447 which should fix this

@Bromeon Can you test with the Rust bindings and let me know if it fixes it for you? Thanks!
