### ISSUE TITLE
Godot "Help" Menu does not match style of the other menus.

### ISSUE THREAD

**Issue by Visssarion** [godotengine/godot#90084]
### Tested versions

- Reproducible in: v4.3.dev5
- Not reproducible in: v4.2.1.stable

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 750 (NVIDIA; 31.0.15.4633) - Intel(R) Pentium(R) CPU G4500 @ 3.50GHz (2 Threads)

### Issue description

Video demonstration of bug being present in v4.3.dev5:
https://github.com/godotengine/godot/assets/46628714/fcd12bcb-90cc-4f14-8ad8-1e49c1c45918

Video demonstration of bug not being present in v4.2.1.stable:
https://github.com/godotengine/godot/assets/46628714/851aa8c5-ec23-4f03-8336-2f67d5e7b7b1

When hovering over "Help" menu, submenu's appear to look not like Godot's, but like default Windows'. After that, focus of Godot Engine window is lost.

### Steps to reproduce

Hover over help menu.

### Minimal reproduction project (MRP)

Works in a completely empty project.

**Comment by Maran23** [comment]
Also for me, it always appears on the wrong screen.
