### ISSUE TITLE
After a signal is awaited, the code following runs multiple times

### ISSUE THREAD

**Issue by scrahe** [godotengine/godot#90089]
### Tested versions

Tested in 4.2.1.stable

### System information

Godot v4.2.1.stable - macOS 12.6.1 - Vulkan (Forward+) - integrated Intel Iris Pro Graphics - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 Threads)

### Issue description

While awaiting a signal inside of _process() such as the following:

```gdscript
func _process(delta):
	await $"Button".pressed
	print("Message")
``` 

You would expect that "Message" would print once, but it appears that it prints for as many frames as it was left unpressed.

### Steps to reproduce

Run the MRP, and click the button, while reading the output.

### Minimal reproduction project (MRP)

[Await Bug MRP.zip](https://github.com/godotengine/godot/files/14818171/Await.Bug.MRP.zip)

**Comment by timothyqiu** [comment]
`_process()` function is called every frame. Awaiting inside it only suspends the execution of this exact call.

That means, you probably have arranged 60 awaits for each second. And once the `pressed` signal is emitted, these 60 awaits are done and you get 60 "Message" printed.

**Comment by scrahe** [comment]
Ok, that makes sense. Thanks!
