### ISSUE TITLE
Texture arrays and 3D textures in shaders

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9008]
I had a discussion with a shader ninja friend about how to properly texture a terrain, and I learned an efficient way to do it is to use texture arrays, or 3D textures, along with a clever use of blend indices, reducing texture fetches from N (any number of textures) to *always* 4, or 8 depending on your setup.
These features are available in GLES3, maybe even in GLES2.

Given that I plan to contribute a terrain module/plugin (and work on related things such as a voxel-based one), is it planned to have texture arrays support or 3D textures in Godot 3.0? Or is it already supported?

(I also thought a Minecrafty terrain would benefit a lot from this because it would fix the limitations of using an atlas, which currently creates seams due to mipmapping)

**Comment by JTippetts** [comment]
Are there any plans currently to go forward with this? I've been evaluating Godot for some projects, but at the moment the lack of texture array support is a deal-breaker.

**Comment by Chaosus** [comment]
_Closed by bugsquad - 3D textures/arrays was added to Godot by #20597_
