### ISSUE TITLE
`Condition "p_font.is_null()" is true. Returning: false` when opening project

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#90100]
### Tested versions

Godot v4.3.dev (29b3d9e9e)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 () - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

In this version, when open projects with godot it will print: 

```
Godot Engine v4.3.dev.custom_build (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
scene\resources\text_paragraph.cpp:420 - Condition "p_font.is_null()" is true. Returning: false
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
```

![image](https://github.com/godotengine/godot/assets/8315986/75b6038e-930a-4ca3-9ea9-f998bec8582a)

It happens with empty project too.

### Steps to reproduce

Get the latest version, creating an empty project and observe.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/90001
