### ISSUE TITLE
`Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.` Error on project start.

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#90107]
### Tested versions

EDIT: Reproducible with: Godot v4.3.dev (https://github.com/godotengine/godot/commit/29b3d9e9e538f0aa8effc8ad8bf19a2915292a89)

EDIT: I will update with a better starting commit later if this isn't solved before I find it. My previous "working"/"not working" commits were mistaken.
It seems like this error started some time back though.

For sure it does not happen in 4.2.1, so it is a new error for 4.3, at least in this project.

### System information

Godot v4.3.dev (29b3d9e9e) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

New error on code that works in 4.2.1:

```
ERROR: Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.
   at: CallQueue::_call_function (core\object\message_queue.cpp:223)
```

### Steps to reproduce

Start up the Godot Physics-Based Platformer 2D demo project and it shows this error immediately:

```
ERROR: Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.
   at: CallQueue::_call_function (core\object\message_queue.cpp:223)
ERROR: Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.
   at: CallQueue::_call_function (core\object\message_queue.cpp:223)
```

### Minimal reproduction project (MRP)

Use the Physics-Based Platformer 2D demo project found here:
https://github.com/godotengine/godot-demo-projects/tree/master/2d/physics_platformer

**Comment by AThousandShips** [comment]
Can you do a bisect to pinpoint what commit actually introduced this? You're listing a period of 3 months

**Comment by chrisl8** [comment]
> Can you do a bisect to pinpoint what commit actually introduced this? You're listing a period of 3 months
> 
> Also can you try a recent commit? You're testing a 2 months old commit

Sorry I wasn't clear, it happens on Master too, the latest version.

But yes, I can do some more checking to figure out what point it actually happened. I was attempting to do that, but now realize I failed, sorry. I'll update when I find the precise commit.

Again though, it also happens on Master. I was just trying to pinpoint when it started, but clearly didn't do a great job of that.

**Comment by chrisl8** [comment]
FYI: Here it is still happening on Commit 29b3d9e9e538f0aa8effc8ad8bf19a2915292a89

Godot v4.3.dev (29b3d9e9e) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

```
Godot Engine v4.3.dev.custom_build (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  scene\resources\text_paragraph.cpp:420 - Condition "p_font.is_null()" is true. Returning: false
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  core\object\message_queue.cpp:223 - Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.
  core\object\message_queue.cpp:223 - Error calling deferred method: 'PinJoint2D::Joint2D::_update_joint': Method expected 1 arguments, but called with 0.
```

**Comment by AThousandShips** [comment]
It's good to list the current version if you want to make sure people know it's still occurring

**Comment by chrisl8** [comment]
@AThousandShips 

I believe the error messages started at this point:
https://github.com/godotengine/godot/compare/ba96dbb49a73d7b6cf0f108f4449f0fbef999863...087a397477742d0a8cc18fe370835aa0cafcdb6b

Yes, that is some months ago, but building 087a397477742d0a8cc18fe370835aa0cafcdb6b (and later) produces the error when running the demo project, while building from ba96dbb49a73d7b6cf0f108f4449f0fbef999863 (and earlier) does not.

**Comment by ianmckenna87** [comment]
got this bug too

**Comment by akien-mga** [comment]
That would be https://github.com/godotengine/godot/pull/86301, cc @KoBeWi
