### ISSUE TITLE
Alt key conflict between scene drag and drop and 3D navigation scheme

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#90112]
### Tested versions

v4.3.dev5.mono.official [89f70e98d]

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Since https://github.com/godotengine/godot/pull/87623 has been merged the alt key is used as a drag-and-drop modifier to instantiate scenes as a child of root instead of a child of a selected node. However, this now conflicts with none default navigation schemes. 

https://github.com/godotengine/godot/assets/105675984/d69f9cd0-921b-4226-8f18-adeb77bdb0e8

### Steps to reproduce

Change navigation scheme to Maya or Modo.

![image](https://github.com/godotengine/godot/assets/105675984/399956f6-308c-40b7-96a8-7e16dd8a2c13)

Hold Alt while doing drag-and-drop to instantiate scene as a child of root 

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
What modifier should we use instead when using the Maya or Modo navigation schemes? <kbd>Shift</kbd> is already used, and <kbd>Ctrl</kbd> should be avoided as it's used for the grid snapping toggle.

**Comment by ryevdokimov** [comment]
Maybe just have the drag-and-drop override the alt functionality in the viewport? This seems to already be the case with right-click functionality.

**Comment by ryevdokimov** [comment]
I think there is some kind of conflict with right-click as well now that I'm looking into this again. IMO I think it's just better to disable freelook all together when drag-and-dropping.

**Comment by KoBeWi** [comment]
I don't see how the modifiers are conflicting if you need to hold them only on release. So position your node and then hold Alt while releasing the mouse button.

**Comment by ryevdokimov** [comment]
I suppose that people can train themselves to do that, but I don't think it's ideal. I'm personally used to preemptively selecting and holding the modifier keys as I drag especially when doing multiple scenes, otherwise I'll have to do some finger dancing.
