### ISSUE TITLE
Renaming "Physics" tab in Project Settings

### ISSUE THREAD

**Issue by JarLowrey** [godotengine/godot#9012]
Recently [had an issue](https://godotengine.org/qa/15368/default_linear_damp-doesnt-do-anything) where I didn't see the Physics 2D tab and instead used the Physics tab. Any chance this could get renamed to Physics 3D?

![capture](https://cloud.githubusercontent.com/assets/7429786/26658335/56a8249e-4637-11e7-86c9-abecfdfb05ce.PNG)

**Comment by nunodonato** [comment]
In v3 this is already improved
![screenshot from 2017-06-01 07-30-09](https://cloud.githubusercontent.com/assets/1642015/26667270/32773758-469c-11e7-9186-5d26471d39af.png)

**Comment by JarLowrey** [comment]
Sweet! Thanks for letting me know

**Comment by akien-mga** [comment]
To add to what @nunodonato said, I wouldn't want to change it in the 2.1 branch as it would break compatibility. But yes, from 3.0 onwards it's clearer.
