### ISSUE TITLE
StreamTexture to Image 3.0

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9013]
There is no way to get an Image Object

1.The binding for Streamtexture.get_data() is missing.
2.Once the binding is added the returned Image is blank.

I get the same  result with Image.load(path)

OSa: Windows

**Comment by nunodonato** [comment]
did you try doing .unlock() before get_data() ?

**Comment by reduz** [comment]
I was thinking on, as you can select the type of resource you want to
import, and Image is now a resource, that you can choose if you want to
import an image as either an image or a texture.

**Comment by AlexHolly** [comment]
I am using GDScript btw.

Example:
I want to draw a preview(Sprite) and manipulate this Image. Do I need two different resources?

```
func _ready():
	#preview
	var preview = load("res://spritesheet.png")
	
	var sprite = Sprite.new()
	sprite.set_texture(preview)
	add_child(sprite)
	
	#manipulate: for now just saves an subimage but probably also put_pixel and update preview
	var image = Image.new()
	image.load("res://spritesheet.png")
	
	#test pixel data
	image.lock()
	print(image.get_pixel(0,0)) # works
	
	#save sub image
	var rect = Rect2(0, 0, 32, 32)
	print(rect)
	var sub_image = image.get_rect(rect)
	sub_image.save_png("res://test.png") #game crash
```

Image.save_png(path) is also not working

**Comment by AlexHolly** [comment]
Okay looks like save_png is working now and I don't need to use StreamTexture I can directly use ImageTexture for both.
