### ISSUE TITLE
Cannot interact with popups inside the editor

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#90137]
### Tested versions

v4.3.dev.custom_build [29b3d9e9e]

### System information

Godot v4.3.dev (29b3d9e9e) - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX Vega (RADV VEGA10) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

We cannot select text neither interact with it (e.g. click on a link) on an editor popup.

[Capture vidéo du 2024-04-02 10-54-09.webm](https://github.com/godotengine/godot/assets/270928/0164f4b5-a60c-4aa2-bef3-580cc69302ee)

[Capture vidéo du 2024-04-02 10-55-44.webm](https://github.com/godotengine/godot/assets/270928/5dbff900-08f2-4496-9a25-e3cebfc89dc8)

### Steps to reproduce

1. Highlight an inspector entry or a export entry.
2. Try to select text from the popup.

### Minimal reproduction project (MRP)

n/a

**Comment by adamscott** [comment]
Issue introduced with #48186.

**Comment by KoBeWi** [comment]
#48186 just made the tooltips disappear. They were never functional, so until there is actual use in interacting with them, there is no reason to change that.

**Comment by KoBeWi** [comment]
> The biggest UX issue I see about this is when you actually don't want to interact with it. If you by mistake hovered for too long into an element and then you try to move your mouse somewhere else, the popups will likely cover that content and not go away.

The tooltip could be closable with Escape or right-click.

**Comment by adamscott** [comment]
> The biggest UX issue I see about this is when you actually _don't_ want to interact with it.

We could add more time to the delay to show a popup, to make sure the user really wants to see a popup.

**Comment by adamscott** [comment]
@Sauermann I think it's `Viewport` related, isn't it?

**Comment by Sauermann** [comment]
Besides being `Viewport` related, this also affects platform-specific input handling. When the popup is displayed as a separate native OS Window, then it will be necessary to verify, that input events are sent to the correct native OS Window.

**Comment by ajreckof** [comment]
> > The biggest UX issue I see about this is when you actually don't want to interact with it. If you by mistake hovered for too long into an element and then you try to move your mouse somewhere else, the popups will likely cover that content and not go away.
> 
> The tooltip could be closable with Escape or right-click.

I think it would be better do go the other way and have a key to be able to interact with it. I remember seeing this somewhere and it felt really good (maybe baldur's gate?) as it wasn't blocking in any way and a simple click would pin the tooltip for interaction.
