### ISSUE TITLE
When duplicated in Editor, MultiplayerSynchronizer instances have their list of properties linked

### ISSUE THREAD

**Issue by mars9t** [godotengine/godot#90145]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Intel(R) Arc(TM) A750 Graphics (Intel Corporation; 31.0.101.5379) - 13th Gen Intel(R) Core(TM) i5-13500 (20 Threads)

### Issue description

Having a MultiplayerSynchronizer node in a Scene tree view in Editor, when copied via CTRL+C/V or Duplicate, the property lists in a Replication window are linked. Meaning that adding new or changing/removing already existing properties on one list result in the same change on the other.

Since the list is supposedly not a resource and there is no way for it to be ticked as a unique to an instance, I'd expect both lists to be fully independent. Removing all properties from the list still keeps them linked, so there doesn't seem to be a way to unlink them (other than in code, probably).

The issue is not present if MultiplayerSynchronizer node is duplicated before doing anything with the list in a Replication window.

### Steps to reproduce

1. Create new project
2. Add main scene
3. Add MultiplayerSynchronizer node
4. Add synchronization for any property in Replication window
5. Duplicate MultiplayerSynchronizer node
6. Change property list in any way
7. Observe that the other list was changed as well

### Minimal reproduction project (MRP)

[MultiplayerSynchronizerDuplicate.zip](https://github.com/godotengine/godot/files/14842456/MultiplayerSynchronizerDuplicate.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/74381

**Comment by mars9t** [comment]
Oh, great. So I just wasted time reporting it due to search being a total crap and not listing it under:
https://github.com/godotengine/godot/issues?page=5&q=is%3Aissue+is%3Aopen+multiplayer

**Comment by AThousandShips** [comment]
Please don't vent about your own failure to find it by searching, you need to search more critically using relevant words, like "multiplayersynchronizer", there's no worries about making a duplicate

**Comment by mars9t** [comment]
Search failed to show relevant thread. It is my fault. Great response.

**Comment by AThousandShips** [comment]
Please be reasonable and professional, this kind of response is completely disproportionate

The search would be completely useless if it searched for parts of words, what if you search for "free" and it shows "freedom", if you're looking for a full word don't search for the part of it

Have a nice day

**Comment by mars9t** [comment]
I pointed out the issue with search engine. Search engine that failed to find keyword within the title. I would be fine with it failing to find it in the content. But in the title? That's a bad implementation.

Being unprofessional? Of course. As you are. Just acknowledge "yes it seems that search engine is not perfect but don't feel you wasted your time. we appreciate your input and treat it as a +1 for the issue to be resolved". That's a correct response. Not stating "you made a failed search", "learn to search".

I was searching for multiplayer related issues as a whole just in case someone just wrote Multiplayer in the title and not MultiplayerSynchronizer. And I looked through 5 pages to be sure I am not duplicating. And that's what I'm salty about. But I took my lesson and will adjust in the future. So should you.

**Comment by AThousandShips** [comment]
I am sorry that you took my friendly advice so negatively, I was not saying anything of what you're saying, I didn't tell you to "learn to search", but I'm sorry you read it as such, even though I didn't say anything like it

Have a nice day
