### ISSUE TITLE
Unexpected behavior for negative values on Camera2D position_smoothing_speed

### ISSUE THREAD

**Issue by BrixsterPlanet** [godotengine/godot#90154]
### Tested versions

Reproducible on Godot 4 and up. Not tested on Godot 3 and lower

### System information

Godot v4.3.dev3.mono - macOS 14.2.0 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

Setting position_smoothing_speed to a negative value causes Camera2D to infinitely accelerate away from its follow target.

While it's possible that some users may make use of this behavior intentionally, this appears to be undefined behavior with camera smoothing.

https://github.com/godotengine/godot/assets/58347007/28c3d071-2d67-40d0-a84e-fb79b18e2799

### Steps to reproduce

- Attach a Camera2D as a child of a moving Node2D
- Set position_smoothing_speed to a negative value.

### Minimal reproduction project (MRP)

Issue reproduction is trivial. If you absolutely need a project, you can download the 2D platformer demo from the Asset Library and follow the steps to reproduce (open the player scene and change position_smoothing_speed on the child Camera2D)

**Comment by BrixsterPlanet** [comment]
While a simple fix could be to bound the minimum value to zero, I'd like to see negative values allow the camera to move _ahead_ of its target momentum rather than lag _behind_ it. Although this would be more difficult to implement than just setting a minimum value since it would require keeping track of its target's momentum, this is the behavior I was attempting to achieve.

**Comment by markdibarry** [comment]
I think it'd be better to first fix this by giving it a minimum, then make an improvement ticket/proposal so we can discuss how we want it to work. We're already pretty confident this is how we _don't_ want it to work. :grimacing:

**Comment by ajreckof** [comment]
I agree thre should be a minium but I disagree on the negative value having any possible meaning. The value here is the speed at which the camera position go to the nodes position. obviously without any check negative value would move away from the position which leads to this strange behaviour. All of this to say I don't see how negative value would work and I don't think they should be allowed.
