### ISSUE TITLE
Icons not loading up in Group Editor

### ISSUE THREAD

**Issue by dipanshparmar** [godotengine/godot#90157]
### Tested versions

- Reproducible in: v4.2.1.stable.flathub [b09f793f5]

### System information

Godot v4.2.1.stable (b09f793f5) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (RPL-P) () - 13th Gen Intel(R) Core(TM) i5-13420H (12 Threads)

### Issue description

- Icons are not working in the Group Editor.

![image](https://github.com/godotengine/godot/assets/49204837/06f7503e-29fd-42ba-8229-148440cf309d)

### Steps to reproduce

- Try to open the Group Editor and the issue should be there.

### Minimal reproduction project (MRP)

I'm not sure if MRP is required for this bug.

**Comment by AThousandShips** [comment]
Can you please try with [4.2.2.rc2](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/)?

**Comment by dipanshparmar** [comment]
4.2.2.rc2 is working fine.
