### ISSUE TITLE
Unexpected Behavior when Using Both Editor Placed and Script-Instantiated Scene Instances

### ISSUE THREAD

**Issue by ACB-prgm** [godotengine/godot#90158]
### Tested versions

Godot 4.2.1 stable

### System information

Mac OS - Godot 4.2.1 stable - Vulkan Forward +

### Issue description

I am encountering an unexpected behavior in my Godot 4 project where manually/editor placed instances in the scene tree seem to be affected by script-instantiated instances. Specifically, I have a scene (Character.tscn) that I place manually in the editor. In addition, I instantiate this scene programmatically in the _init() function of the root node. Expectedly, this should result in two instances of Character.tscn in the scene tree at runtime. However, only one instance appears (the manually placed one).

### Steps to reproduce

Steps to Reproduce:

1. Create a scene (Character.tscn).
2. Manually place an instance of Character.tscn in the main scene.
2. In the main scene's script, instantiate another Character.tscn instance in the _init() function and add to tree via add_child().
3. Run the game and observe the number of Character instances in the scene tree.

Expected Behavior:
Each instance of Character.tscn (both manually placed and script-instantiated) should be uniquely present and accounted for in the scene tree at runtime.

Actual Behavior:
Only one instance of Character.tscn is present in the scene tree at runtime, suggesting that the manually placed instance is being overlooked or replaced by the script-instantiated instance.

Example:
Tree:
```
Node2d
 - base_enemy
```

Script on Node2d:
```
var test = preload("res://Scenes/Enemies/base_enemy.tscn")


func _init():
	var instance = test.instantiate()
	add_child(instance)
```

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/godotengine/godot/files/14846576/bug.zip)

**Comment by AThousandShips** [comment]
You have to set the owner to be visible, see the [documentation](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-property-owner)
