### ISSUE TITLE
Bug mesh (perhaps the grid has nothing to do with)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#9016]
**Operating system or device - Godot version:**
Ubuntu 16.04
Godot 2.1.3

**Issue description:**
Gaps are visible, which should not be
![2017-06-02 17-13-32](https://cloud.githubusercontent.com/assets/11325733/26721711/763a3124-47bf-11e7-9dff-a705fc1bcbc5.png)

**Steps to reproduce:**
Import scene (.dae) from Blender3d

**Link to minimal example project:**
[Bug mesh.zip](https://github.com/godotengine/godot/files/1047366/Bug.mesh.zip)

**Comment by nunodonato** [comment]
this is a bug(?) in blender, not godot. the vertices have very tiny differences from each other, so its ok that they dont match.
if you open the exported .dae file you can see positions like 5.0000007375

**Comment by Zylann** [comment]
Which is too small for floats to handle btw

**Comment by DimaKiva** [comment]
In some cases, blender script helps
```
import bpy

# выравнивание вертексов
def viravnivanie_verteksov():
    okruglenie = 2# сколько циферок останется после точки
    for ob1 in bpy.context.selected_objects:
        if ob1.type == 'MESH':
            for ob2 in ob1.data.vertices:
                ob2.co = [round(ob2.co[0], okruglenie), round(ob2.co[1], okruglenie), round(ob2.co[2], okruglenie)]

viravnivanie_verteksov()
```
