### ISSUE TITLE
iOS export of C++ GDExtension fails in 4.3-dev5

### ISSUE THREAD

**Issue by ybin64** [godotengine/godot#90168]
### Tested versions

Reproducable in 4.3-dev5, 4.3-dev [29b3d9e]
Works in 4.2.1

### System information

Target iOS 17.4.1, build machine MacOS 14.4.1

### iOS export of a project with a C++ GDExtension fails in Godot 4.3-dev5.

I believe it's related to the following commit [[iOS export] Improve .xcframework exporting.](https://github.com/godotengine/godot/commit/9efd83fe3caba6044a08a8490d202c24b89c7acc)

I had 2 problems.

1. Link problem during export.

    ```sh
     ld: file cannot be mmap()ed, errno=22 path=godot-gdextension-test/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal in
        'godot-gdextension-test/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal'
     clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ```
    
    Fixed in [Fixed link error during export. ](https://github.com/ybin64/godot/commit/c06ce321eed35927a0af3424ce4c3e6bd693fdb2)

2. Runtime error on device, the libgdexample framework isn't found

    Caused by the problem 1 fix.
    
    ```sh
    dyld[6062]: Library not loaded: demo/bin/libgdexample.ios.template_debug.framework/libgdexample.ios.template_debug
      Referenced from: <C5B2228B-F230-351B-B46B-ECED5AACFCEB> /private/var/containers/Bundle/Application/7551DD31-129E-4BF8-8629-FB9A4A2915F9/godot-gdextension-test.app/godot-gdextension-test
      Reason: tried: 
        'demo/bin/libgdexample.ios.template_debug.framework/libgdexample.ios.template_debug' (no such file), 
        '/private/preboot/Cryptexes/OSdemo/bin/libgdexample.ios.template_debug.framework/libgdexample.ios.template_debug' (no such file), 
        'demo/bin/libgdexample.ios.template_debug.framework/libgdexample.ios.template_debug' (no such file)
    ```
    
    Fixed in [ Frameworks converted from .dylib are embedded as "CodeSignOnCopy" in the xcode projet](https://github.com/ybin64/godot/commit/d2f6a7b503c2b2b3ae3c9d1298d466990eda561b)

 
Both fixes are in the following branch. [4.3-dev-ios-gdextension-link-and-dylib-failure-fix](https://github.com/ybin64/godot/tree/4.3-dev-ios-gdextension-link-and-dylib-failure-fix) but I'm pretty sure it's not the correct way to solve the problem, but may be useful for someone until the real fix.

### Steps to reproduce

- Use [4.3-dev5](https://godotengine.org/download/archive/4.3-dev5/) and the matching export templates

- Follow the instructions in [gdextension_cpp_example](https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html)

- Add the following lines to demo/bin/gdexample.gdextension
```
ios.debug = "res://bin/libgdexample.ios.template_debug.universal.dylib"
ios.release = "res://bin/libgdexample.ios.template_release.universal.dylib"
```

- Build the extension

- Export an iOS project, will fail with a link error during the export
```sh
 ld: file cannot be mmap()ed, errno=22 path=godot-gdextension-test/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal in
    'godot-gdextension-test/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal'
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Minimal reproduction project (MRP)

N/A

**Comment by rjgameiro** [comment]
Godot 4.3 RC3 seems to still be suffering from this problem.
Tried the exact same project (**plain GDExtension example from Godot documentation**) with Godot 4.2.2 and Godot 4.3 RC3, and while 4.2.2 succeeds, 4.3 RC3 fails on build on iOS with the error:

    ld: file cannot be mmap()ed, errno=22 path=amber/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal in 'amber/dylibs/bin/libgdexample.ios.template_debug.universal.framework/libgdexample.ios.template_debug.universal'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ** ARCHIVE FAILED **
    The following build commands failed.
    Ld /Users/rgameiro/Library/Developer/Xcode/DerivedData/amber-geepphvxiicnsegpcjbqlufrernb/Build/Intermediates.noindex/ArchiveIntermediates/amber/InstallationBuildProductsLocation/Applications/amber.app/amber normal (in target 'amber' from project 'amber')
    (1 failure)

This is what is getting exported by Godot 4.2.2 (for the GDExtension iOS framework):
<img width="451" alt="GOOD-4 2 2" src="https://github.com/user-attachments/assets/921e30c0-da80-4e60-b5bd-ff473b16d728">

This is what is getting exported by Godot 4.3RC3:
<img width="451" alt="BAD-4 3RC3" src="https://github.com/user-attachments/assets/c4d1cb91-91ca-4c49-9388-0007a184bde6">

Also, the contents of the Info.plist files:

Good Info.plist (Godot 4.2.2)
<img width="825" alt="GOOD-4 2 2-Info" src="https://github.com/user-attachments/assets/0bb5dbc2-c8da-47f5-ba39-16368d8bf776">

Bad Info.plist (Godot 4.3RC3)
<img width="780" alt="BAD-4 3RC3-Info" src="https://github.com/user-attachments/assets/c2d77d7d-d862-4b1c-8458-9ff71def884e">

I can provide more details if asked.

**Comment by akien-mga** [comment]
Could you attach the reproduction project to make testing easier? I know it's derived from our docs but it takes time to reproduce all the setup from the docs. You can remove the compiled objects/libs to keep size low.

CC @bruvzg

**Comment by rjgameiro** [comment]
Here goes... building extension with:
    scons platform=ios custom_api_file=./godot-cpp/extension_api.json
...which was exported from Godot 4.3 RC3.
Removed AppStore Team ID from export settings.

[gdextension_cpp_example.zip](https://github.com/user-attachments/files/16558363/gdextension_cpp_example.zip)

**Comment by bruvzg** [comment]
Most likely something wrong with extension packaging, see `generate_xcframework.sh` in the https://github.com/godotengine/godot-cpp/tree/master/test as an example of building and packing GDExtension for iOS.

In the exported project should look like this:
<img width="598" alt="Screenshot 2024-08-09 at 11 18 48" src="https://github.com/user-attachments/assets/fb5ac7e2-f47f-4197-adae-d52c97085755">

**Comment by fatduckling** [comment]
Hi,
I'm having the same issues with v4.3 RC3. 
Please see #

**Comment by fatduckling** [comment]
I managed to work around this problem by changing my dylibs to the framework format.
Something like:
```
xcodebuild -create-xcframework -library libtbb.dylib -output Tbb.xcframework
xcodebuild -create-xcframework -library libtbbmalloc.dylib -output TbbMalloc.xcframework
```

And in the `.gdextension` file:

```
...
[dependencies]

ios.arm64 = {
    "res://bin/libtbb.xcframework": "",
    "res://bin/libtbbmalloc.xcframework": "",
...
```
