### ISSUE TITLE
Forward+ acts like compatability

### ISSUE THREAD

**Issue by verypleasentusername** [godotengine/godot#90163]
### Tested versions

v4.2.stable.official [46dc27791] tested only

### System information

windows 7 v4.2.stable Forward+ rendering GeForce 540 GT embedded without vulkan support

### Issue description

probably just error absence issue

![image](https://github.com/godotengine/godot/assets/63970682/e3edadaa-d592-4014-9d70-81c2cae8a9bd)
as seen here Volumetric fog is set ot be enabled. settings to default.
![image](https://github.com/godotengine/godot/assets/63970682/7fd3d2d3-d326-4c6c-943c-d8335b0e75ef)
no visible fog in the scene with simple MeshInstance3D in it.
![image](https://github.com/godotengine/godot/assets/63970682/491c22d9-288c-4b9e-9dd3-a97352e61c3a)
![image](https://github.com/godotengine/godot/assets/63970682/d102a41e-74cb-4fc0-a041-46cdd480277a)
(dont mind warning in russian language, its about .blend files)
popup ans console warning of Volumetric fog working only in Forward+(happens with all Forward+ only features)

### Steps to reproduce

Dowload MRP and play it, i guess it works only with non-vulkan graphics card.

### Minimal reproduction project (MRP)

[NewProj2.zip](https://github.com/godotengine/godot/files/14849225/NewProj2.zip)

**Comment by AThousandShips** [comment]
You're not on Forward+, you're running compatibility, you're falling back to it because of a lack of vulkan support

**Comment by verypleasentusername** [comment]
> You're not on Forward+, you're running compatibility, you're falling back to it because of a lack of vulkan support
> 
> Can you please test on a supported version? 4.2 is outdated, try 4.2.1 to see if it displays this clearer

![image](https://github.com/godotengine/godot/assets/63970682/49d36564-3342-4fab-b65d-7a0d7a99b608)
the error is clearly there on load. i dont why, i remember being on 4.2.2rc1. anyway error solved, sorry for time losed on this.

**Comment by AThousandShips** [comment]
No problem at all :)
