### ISSUE TITLE
SVG rendering issue with stroke closing joint

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#90169]
### Tested versions

4.2.2.rc2

### System information

Godot v4.2.2.rc2 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

There is an SVG rendering bug that causes every second stroke closing joint to close incorrectly.

Only one of our icons is affected.

![image](https://github.com/godotengine/godot/assets/85438892/40381323-df16-440b-b141-01239dea69cc)

It's also fixed in latest ThorVG version. I've not checked if it's fixed in our master branch though.

### Steps to reproduce

Check out this icon in the visual shaders editor, or make your own SVG that has the issue, for example `<svg width="64" height="64" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M5 3.5l-2 4.5 5.5-2zM8.5 9.5l.5 3.5 3.5-2.5z" fill="none" stroke="#def" stroke-linejoin="round"/></svg>`

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment]
Can you confirm that cherrypicking https://github.com/godotengine/godot/pull/89591 will close this?

**Comment by akien-mga** [comment]
> Can you confirm that cherrypicking #89591 will close this?

I don't think so, but I confirmed that #90243 fixes it.
