### ISSUE TITLE
 Display issues of refraction and semi transparent objects

### ISSUE THREAD

**Issue by ProgrammerMao** [godotengine/godot#90171]
### Tested versions

It is known that at least from Alpah9 to the nearest Stable4.2.1

### System information

Win10 22H2, NVIDIA GTX1060, Vulkan( Forward+ )

### Issue description

When there is a refracted object and a semi transparent object, the semi transparent object cannot be displayed through the refracted object
![屏幕截图 2024-04-03 220855](https://github.com/godotengine/godot/assets/72609054/7276c320-0165-4dac-8560-83b58d245252)
If I remember correctly, there used to be situations like this between semi transparent objects as well

### Steps to reproduce

Place two Meshinstance3D objects in the scene and set the following settings for surface_matrial_override (all undisclosed parts are the default settings)
Refractive object:
![image](https://github.com/godotengine/godot/assets/72609054/5b2e0d45-7e5d-467d-a3ec-cd0ab7a06b78)
Translucent object:
![image](https://github.com/godotengine/godot/assets/72609054/27f9d674-b777-4d01-8e76-7f3309247ec2)

### Minimal reproduction project (MRP)

This scene was created by Godot4.2.1
[scene.zip](https://github.com/godotengine/godot/files/14853639/scene.zip)

**Comment by Calinou** [comment]
Transparent objects are not included in the `screen_texture` used by refraction. This is already documented here: https://docs.godotengine.org/en/stable/tutorials/3d/standard_material_3d.html#refraction

This mention should be added to the BaseMaterial3D class reference too.
