### ISSUE TITLE
Strange visual effect when using SS Reflections

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9017]
**Operating system or device - Godot version:** Linux, Godot 3 master

This is probably a combination of several factors, so might be hard to track. Take a look at the gif: 
http://i.imgur.com/W811zGQ.gifv

The area right below the hat, in the front and back of the head seems to have a different color, when aligned with the water material (where SSR is stronger). I think it negates the SSR effect and the water looks like the rest where no reflection is present.

extra picture from a different location (harder to see but still visible):
![screenshot from 2017-06-02 12-52-52](https://cloud.githubusercontent.com/assets/1642015/26724629/6f780c26-4792-11e7-854d-dd71dfabbe39.png)

**Comment by honix** [comment]
i'm afraid that it is just implementation artifact, it is just how this shader works with pros and cons

**Comment by reduz** [comment]
This is not a bug, this is common screen space reflection behavior. Welcome to why it's not very good until a scene somehow works for it.
