### ISSUE TITLE
Scenes that preload each other cannot be loaded and cause one of the scripts to fail to load.

### ISSUE THREAD

**Issue by WeaverSong** [godotengine/godot#90185]
### Tested versions

Test and reproduced in v4.3.dev5.official [c9c17d6ca], v4.2.1.stable.official [b09f793f5], and v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Fedora Linux 39 (KDE Plasma) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 550.54.14) - Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 Threads)

### Issue description

When a scene preloads another which eventually preloads the original (cyclic preloading) the scenes and scripts become corrupt/unloadable with a parse error, although no error is shown in the script editor on the lines causing it. This issue does not occur on scripts preloading each other, they have to be preloading each other as scenes.

### Steps to reproduce

Create 2 scenes, attach scripts to them, in each script preload the other scene, then reload the editor or try to run one of the scenes.

Or just open the mrp.

### Minimal reproduction project (MRP)

[CyclicPreloadTest.zip](https://github.com/godotengine/godot/files/14859242/CyclicPreloadTest.zip)

**Comment by Jordyfel** [comment]
This is expected. Non-script resources don't support cyclic loading, so they can't support cyclic preloading.

Probably should be documented somewhere easily reachable.

**Comment by AThousandShips** [comment]
Indeed, please see:
* https://github.com/godotengine/godot/issues/80877
