### ISSUE TITLE
The String Capitalize Function Doesn't Handle Apostrophes Correctly Resulting In Bad Output

### ISSUE THREAD

**Issue by timkrief** [godotengine/godot#90192]
### Tested versions

Tested in 3.5.2 and 4.2.stable

### System information

Latest Ubuntu LTS

### Issue description

In French, if I want to capitalize "le feu" it will output "Le Feu" correctly. But if the word starts with a vowel, the "le" is shortened as "l'", and in that case "l'eau" capitalized should output "L'Eau" but it outputs "L'eau".

### Steps to reproduce

You can just run this line to see the issue:
`print("L'eau ça mouille".capitalize())`

Results in:
`L'eau Ça Mouille`

### Minimal reproduction project (MRP)

```gdscript
extends Node

func _ready():
	print("L'eau ça mouille".capitalize())

```

**Comment by bruvzg** [comment]
`String.capitalize` only handle spaces and `_`.

> capitalized should output "L'Eau" but it outputs "L'eau"

Every app I have tried do exactly the same thing.

For 4.x, it should be possible to expose a language specific variant for this function from ICU used in the `TextServer`, but in this case it's also doing exactly the same.

**Comment by ajreckof** [comment]
I wouldn't expect a word after an apostrophes to be capitalised and that independent of the language. 
On the note of apostrophes and french would you also expect "aujourd'hui" to be capitalised as "Aujourd'Hui"?
