### ISSUE TITLE
Width of bottom dock unchangeable

### ISSUE THREAD

**Issue by Platymek** [godotengine/godot#90206]
### Tested versions

4.2.1.stable.mono

### System information

Godot v4.2.1.stable.mono - SteamOS holo - X11 - Vulkan (Forward+) - integrated AMD Custom GPU 0405 (RADV VANGOGH) () - AMD Custom APU 0405 (8 Threads)

### Issue description

The bottom dock width appears to be unchangeable, which makes it very hard to see the left and right docks as they cannot be stretched further than the limit of the bottom dock, especially hard on lower resolutions. Is there a way to remove categories from the dock? You should generally be able to scroll through it too.

![image](https://github.com/godotengine/godot/assets/38002310/ea594e72-e674-40bf-a681-60ca8158f3ef)
(this is the maximum that the left and right docks can stretched)

### Steps to reproduce

Having a lower resolution than 1080p (in my case 800p) and a custom display scale of 1.5

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
I recall this being reported in another issue already, but I can't find it right now.

**Comment by Platymek** [comment]
I think they should at least be removable, I've never used the audio or search results tab and the shader editor isn't always helpful. Perhaps the specific ones like shader and animation editor should be removable at least and should pop up automatically when you go to use them
