### ISSUE TITLE
Changing Input.mouse_mode while the mouse is outside the window doesn't confine the mouse [Linux/XWayland]

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#90213]
### Tested versions

Godot v4.2.1.stable

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) () - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

When changing `Input.mouse_mode` to `Input.MOUSE_MODE_CONFINED` while the mouse is outside the window doesn't confine it.

### Steps to reproduce

1. Open the MRP;
2. Run the scene with F6;
3. Press space to toggle between `Input.MOUSE_MODE_CONFINED` and `Input.MOUSE_MODE_VISIBLE` (the output window will show which one is currently on);
4. Switch to `Input.MOUSE_MODE_CONFINED` while the mouse is outside the window;

Now `Input.mouse_mode` is set to `Input.MOUSE_MODE_CONFINED` but the mouse isn't confined.

### Minimal reproduction project (MRP)

[test.tgz](https://github.com/godotengine/godot/files/14875110/test.tgz)

**Comment by alvinseptiano** [comment]
I've tested it using x11 works just fine but when I switched to Wayland yes it doesn't work.

**Comment by alvinseptiano** [comment]
> Reading the [Arch wiki](https://wiki.archlinux.org/title/Wayland#Input_grabbing_in_games,_remote_desktop_and_VM_windows) having `wayland-protocols` installed should've fixed the issue, but it's still happening.

I think the problem is from Godot's side. I have looked into `WaylandThread` little bit, maybe has to do with `_wl_pointer_on_enter` or `wl_proxy_is_godot`?

**Comment by alvinseptiano** [comment]
I originally wanted to sugesting using `warp_mouse`, but it seems like the function also not working under Wayland. 
related issue #73461

**Comment by akien-mga** [comment]
> > Reading the [Arch wiki](https://wiki.archlinux.org/title/Wayland#Input_grabbing_in_games,_remote_desktop_and_VM_windows) having `wayland-protocols` installed should've fixed the issue, but it's still happening.
> 
> I think the problem is from Godot's side. I have looked into `WaylandThread` little bit, maybe has to do with `_wl_pointer_on_leave` or `wl_proxy_is_godot`?
> 
> It seems that whenever pointer is outside a window godot loses its proxy tag?

Note that OP uses Godot 4.2.1, which does not include Wayland support (so it's only Xwayland).

Godot 4.3-dev5 have Wayland support, albeit opt-in in the project settings / `--display-driver wayland` option.

CC @Riteo

**Comment by alvinseptiano** [comment]
After using version `4.3-dev5` with `--display-driver wayland` both functions still don't work.

**Comment by em-s-h** [comment]
> That said, if you were to refocus the window, it should properly attempt to confine it and that request should actually go through.

Yep, refocusing the window does confine the cursor properly. Should I close this issue @Riteo ?

**Comment by em-s-h** [comment]
You're welcome!
