### ISSUE TITLE
After exporting the Inputs aren't recognized 

### ISSUE THREAD

**Issue by jrapf32** [godotengine/godot#90220]
### Tested versions

v4.3.dev.custom_build.7e0847701: Yesterday before I git pulled it worked fine

### System information

macOS Sonoma M1 14.2 v4.3.dev.custom_build.7e0847701 

### Issue description

I made an export template for macOS. After exporting my the test project the inputs aren't working
<img width="516" alt="Screenshot 2024-04-04 at 1 53 15 PM" src="https://github.com/godotengine/godot/assets/30359766/a296e2e1-cb68-42ba-9a13-abb262007d74"> But the test project works in the editor.

### Steps to reproduce

Compile export template then export appliction/game that requires input.

### Minimal reproduction project (MRP)

[Test.zip](https://github.com/godotengine/godot/files/14877083/Test.zip)

**Comment by Anutrix** [comment]
Facing same issue here. Issue is reproduced on every project in latest master `https://github.com/godotengine/godot/commit/655e93d5846b2ef8ebb7d22c8878f51b8f22b312`. At least on Android export.

The issue wasn't present on `fe01776f0`(build from few weeks ago).

**Comment by Anutrix** [comment]
I tried to bisect it and found that commits before `ec5cae37d6789ea7a0cbe96c50bf85591f5533d4` don't have the issue.

**Comment by akien-mga** [comment]
CC @dalexeev @Faless

**Comment by jrapf32** [comment]
Ok
