### ISSUE TITLE
Yellow screen 

### ISSUE THREAD

**Issue by Jubrazanime** [godotengine/godot#90222]
### Tested versions

I am new I don't know

### System information

Android 10 - Godot 4.2.1.stable

### Issue description

I am new in Godot I use the mobile version I am using otg to use mouse it easy to click the buttons but when I try to add nodes it showing me yellow screen if I can use mouse it well help me a lot is there any solution ?

https://github.com/godotengine/godot/assets/166066790/faf80d89-7c40-4ad2-b293-94b20326c8b3

### Steps to reproduce

?

### Minimal reproduction project (MRP)

?

**Comment by Calinou** [comment]
@Jubrazanime Which Android device model are you using? Does this occur when you click with the mouse in other apps?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
