### ISSUE TITLE
need to press on pencil after adding empty CollisonPolygon2D node

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#9023]
**Operating system or device - Godot version:**
Window 7, v2.1.3.stable.official

**Issue description:**
usability improvement
![draw_polygon_pencil](https://cloud.githubusercontent.com/assets/10463138/26736537/d736a76c-47c6-11e7-82c5-315db830b21e.gif)

I expect when adding a empty CollisonPolygon2D node the pencil should be automatically selected.

**Comment by saltares** [comment]
This was actually done in fbda0cc45c2f50b9b30175c4f2398b8a73d7bf4a. I think it can be closed.
