### ISSUE TITLE
Physics interpolation: Per node disabling in editor broken

### ISSUE THREAD

**Issue by lubasowo0** [godotengine/godot#90238]
### Tested versions

4.3.dev [29b3d9e9e5] and [06abc86a5f]

### System information

Arch Linux - OpenGL API 4.6 (Core Profile) Mesa 24.0.4-arch1.2

### Issue description

Not the main issue but On and Off in this line are swapped: https://github.com/godotengine/godot/blob/79de2eaae7fb3bb8f13031ac2ec9b19128b6f471/scene/main/node.cpp#L3783

The issue is that enabling Physics Interpolation in the project settings and then disabling it per node in the editor doesn't do anything, probably because `canvas_item_set_interpolated` never gets called at startup. Here are some workarounds I found which fix the issue:

- Commenting out this early return: https://github.com/godotengine/godot/blob/79de2eaae7fb3bb8f13031ac2ec9b19128b6f471/scene/main/node.cpp#L421
- Calling `canvas_item_set_interpolated` manually:
```gdscript
func _ready() -> void:
	RenderingServer.canvas_item_set_interpolated(get_canvas_item(), false)
```
- Setting PHYSICS_INTERPOLATION_MODE_OFF at runtime:
```gdscript
func _ready() -> void:
	#PHYSICS_INTERPOLATION_MODE_OFF is NOT set in the editor, if it is this doesn't work,
	#probably because of early returns
	physics_interpolation_mode = PHYSICS_INTERPOLATION_MODE_OFF
```

### Steps to reproduce

- enable Physics Interpolation and set low ticks per seconds, for example 5
- add Sprite2d with a script to update a position in _process (not _physics_process) to introduce visible jitter with interpolation and low ticks per seconds
- in editor disable the interpolation for the sprite (options are swapped without fixing that line above)
- the sprite still jitters

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/14880068/project.zip)

**Comment by lawnjelly** [comment]
This bug is not present in 3.x, just tested. @rburing 
I'll try and help but may be away for few days. It is probably something very simple.

**Comment by rburing** [comment]
Thanks a lot for catching this during the dev phase! :+1:
