### ISSUE TITLE
SpriteFrames addframes double click on file

### ISSUE THREAD

**Issue by Janosoft** [godotengine/godot#90232]
### Tested versions

- Reproducible in 4.2.1 stable

### System information

Windows 11 - Godot 4.2.1 stable - Compatibility render

### Issue description

When you do a double click selecting a file, it choose the frame where the clic was. It's like it keep one click more

### Steps to reproduce

- AnimatedSprite2D
- SpriteFrames tab
- Select an animation / or create a new one
- Click on Add Frames from sprite sheet button
- Double click on a file

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88442
