### ISSUE TITLE
Invalid/Corrupt Scene when Scene inside SceneCollection has any property of PackedScene

### ISSUE THREAD

**Issue by arran-nz** [godotengine/godot#90249]
### Tested versions

- v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

I have a TileMap Scene with a respective TileSet, I import the TileMap Scene into each Level to have the same settings, layer information etc between Levels. 

Inside the TileSet I have a collection of Scenes I would like to instantiate in each level (typical workflow). However, one of these Scenes is a "Teleport" object, this object contains a property of type `PackedScene`  which can reference another scene of level.

I suspect there may be an error in how TileMaps are loaded, and they're trying to load the PackedScene inside the Scene, inside the SceneCollection, inside the TileSet, inside the TileMap

`PackedScene -> Scene -> SceneCollection -> TileSet -> TileMap`

I would expect that the PackedScene inside the Scene would not be loaded during the Editor launch.

Breadcrumb: 
https://github.com/godotengine/godot/blob/b09f793f564a6c95dc76acc654b390e68441bd01/scene/resources/resource_format_text.cpp#L163

### Steps to reproduce

I have added a MRP, If you try and open the project you will be presented with an error

### Minimal reproduction project (MRP)

[SceneRef.zip](https://github.com/godotengine/godot/files/14882483/SceneRef.zip)

**Comment by AThousandShips** [comment]
I'd say this is not a bug but a non-supported use, you should instead load the target of the teleport when needed, there's no reason for the engine to not load this data

**Comment by arran-nz** [comment]
@AThousandShips 

That's a good point, I think you're right. (The errors caught me offguard and took me a while to narrow down the root cause, which prompted me to share)

For now I'm loading in-game and not in the editor, which acheives the same pratical result.
```
...
@export_file("*.tscn") var target_level_path: String
@onready var target_level: PackedScene = load(target_level_path)
```

**Comment by AThousandShips** [comment]
That's the generally appropriate practice, packed scenes are always loaded, not on-demand, if you're interested in changes to this I'd suggest opening a [proposal](https://github.com/godotengine/godot-proposals/issues) for lazy loading of packed scenes, i.e. not loading sub-resources until instantiation, but otherwise I'd say this is resolved

**Comment by arran-nz** [comment]
Yes, I agree that this is resolved - Let it serve as Issue Documentation incase someone else experiences similar. 

Cheers!
