### ISSUE TITLE
Undo shortcut stops working after scene is updated from instance modification

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#90262]
### Tested versions

4.3 dev5

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

See title and reproduction steps. The bug is rather convoluted, I'm not sure what causes it.

### Steps to reproduce

1. Create scenes: Parent, Instance, Another. Make sure all 3 are opened
2. Instantiate Instance scene in Parent
3. Go to Another and do some modification
4. Check that undo/redo shortcuts are working. Make sure the scene is still marked as modified
5. Go to Instance scene and save it
6. Go to parent scene. Since the Instance was modified, the scene will be updated
7. Go to Another and try using undo shortcut again. It won't function
8. Open and close editor's Scene popup menu
9. The shortcut can be used again

### Minimal reproduction project (MRP)

N/A

**Comment by Rindbee** [comment]
It seems to be related to `EditorNode::_update_undo_redo_allowed()`.

https://github.com/godotengine/godot/blob/029aadef563fb69cf49aa9795b62f27171f8c3f4/editor/editor_node.cpp#L1184-L1188
