### ISSUE TITLE
RichTextLabel fit_content does not work with very thick outlines or shadows with a big offset

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#90275]
### Tested versions

- Reproducible in: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19042 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3141) - AMD A10-7850K Radeon R7, 12 Compute Cores 4C+8G (4 Threads)

### Issue description

When using the Label node the text is correctly displayed regardless of the font size, outline size, shadow offset or shadow outline size.

But when using RichTextLabel with fit_content=true, autowrap_mode=Off and scroll_active=false, the content get's clipped as can be seen in the screenshot bellow

![image](https://github.com/godotengine/godot/assets/5783414/a263bc95-bc7c-42d7-8e90-cb76abcebb34)

### Steps to reproduce

Create a new project, create a new scene, create at least one label and one richtextlabel, set thick borders and a large shadow offset shadow on both and see that the label displays correctly whereas the richtextlabel gets the outline and shadow clipped. OR just open the main scene in the MRP.

### Minimal reproduction project (MRP)

[RichTextLabelOutlineClippingBug.zip](https://github.com/godotengine/godot/files/14889623/RichTextLabelOutlineClippingBug.zip)

**Comment by ArchieVillain** [comment]
![image](https://github.com/godotengine/godot/assets/168238968/4708e811-b434-46a7-86a9-fc9c78809431)

Checking your MRP, it seems the `clip_contents` property of your `RichTextLabel`s is enabled. Disabling it fixes it, as per my screenshot.
