### ISSUE TITLE
Cant run Godot 3.0 with Radeon HD 3650 on Windows

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#9027]
** Operating system or device - Godot version: **
Windows Vista x32, Radeon HD 3650.
Informal build of Godot 3.0 from the site http://fixnum.org/godot/ for May 29. For windows x32. (I also tried the old versions.) But the result is identical.)

** Description of the problem: **
** Playback Actions: **
After launching, a black console window appears, and disappears after a second. Do not report any errors.

**Comment by akien-mga** [comment]
What version of the AMD drivers do you have?

According to http://feedback.wildfiregames.com/report/opengl/device/Mobility%20Radeon%20HD%203650, versions below 6.14.10.8787 support only OpenGL 2.1, and versions above 6.14.10.11653 support OpenGL 3.3 (in between, I don't know).

**Comment by eon-s** [comment]
The 3D didn't worked well with 6250 when I tested a couple of months ago, I don't think 3650 can handle it (specs say OpenGL 2.0).

**Comment by OlexiyKravchuk** [comment]
> akien-МГА прокомментировал 17 hours ago
Какая версия драйверов AMD у вас есть?

The version of the driver that I have ... 8.970.100.7000

**Comment by akien-mga** [comment]
> The version of the driver that I have ... 8.970.100.7000

The version numbers are a bit confusing, but it seems like this would be AMD Catalyst 13.1 (2012). There is a version 13.9 (latest, 2013) available on AMD's website for your card on Vista 32-bit, you could try to upgrade: http://support.amd.com/en-us/download/desktop/legacy?product=legacy2&os=Windows+Vista+-+32

I can't promise it would solve the issue though, I can't find any details about the OpenGL Core Profile version supported by Catalyst 13.9.

**Comment by OlexiyKravchuk** [comment]
>akien-mga commented 3 hours ago
 I can't promise it would solve the issue though, I can't find any details about the OpenGL Core Profile version supported by Catalyst 13.9.

I reinstalled my drivers to the latest version, but it did not change anything, and it seems to me that the problem is not in the video driver.

**Comment by OlexiyKravchuk** [comment]
I ran the test, and there everything is in order, there supports OpenGL 3.3
![image](https://user-images.githubusercontent.com/10380658/26902504-31f58622-4be2-11e7-88e9-b17ce2ecc45e.png)

**Comment by reduz** [comment]
I wish I had hardwardware this old.. in fact I believe I might have a
Radeon HD somewhere but no idea where it is.. and much less a computer
where to test it

**Comment by OlexiyKravchuk** [comment]
> reduz commented 17 hours ago
I wish I had hardwardware this old.. in fact I believe I might have a
Radeon HD somewhere but no idea where it is.. and much less a computer
where to test it

If I can get the data you need, then tell me where. I'll try to do everything in my power ...

**Comment by reduz** [comment]
You should be able to run godot directly from a command line, so whathever
it prints, you can see

**Comment by OlexiyKravchuk** [comment]
I've done it many times, started using the command line, but there, I did not get any data, all as you can see in the photo. And after 1-2 seconds, the second black window disappears.
![image](https://user-images.githubusercontent.com/10380658/26939135-02857e36-4c7f-11e7-9a30-494c74ead579.png)

**Comment by groud** [comment]
I am a windows newbie, but maybe you should try without the "start" command, which according to the manual opens the given program in a new windows.
Maybe try to just type `D:\godot.windows.tools.32(2).exe`

**Comment by akien-mga** [comment]
>  Maybe try to just type `D:\godot.windows.tools.32(2).exe`

Or even best, as in the past there were issues with folders containing non ASCII characters like your user folder, try:
```
cd D:
godot.windows.tools.32(2).exe
```

**Comment by OlexiyKravchuk** [comment]
> groud commented 2 hours ago • edited
Maybe try to just type D:\godot.windows.tools.32(2).exe

It did not work at all ...

> akien-mga commented 2 hours ago
Maybe try to just type D:\godot.windows.tools.32(2).exe
Or even best, as in the past there were issues with folders containing non ASCII characters like your user folder, try:

> cd D:
godot.windows.tools.32(2).exe

And it gave exactly the same result as before ...

**Comment by akien-mga** [comment]
Closing as we dropped support for Windows Vista. See #12596 for further driver issues on the same hardware.
