### ISSUE TITLE
Can't Create An OpenGL 3.3 Rendering Context on GeForce 710M on Windows 7

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#9028]
** Operating system or device - Godot version: **
Windows 7 x64, GeForce 710M.
Informal build of Godot 3.0 from the site http://fixnum.org/godot/ for May 29. For windows x32 & x64. (I also tried the old versions.) But the result is identical.)

** Description of the problem: **
** Playback Actions: **
After running Godot, Windows reported in a new window that (Can't Create An OpenGL 3.3 Rendering  Context) then crashes
After that, I reinstalled the graphics drivers to the latest version, but did not change anything.

**Comment by akien-mga** [comment]
Are you sure that Godot is using the discrete Nvidia card, and not the Intel integrated chipset? (sounds like an Optimus laptop).

**Comment by OlexiyKravchuk** [comment]
> akien-МГА прокомментировал 17 hours ago
Вы уверены, что Годо использует дискретную Nvidia карты, а не интегрированный чипсет Intel? (Звучит как ноутбук 
> Optimus).

Yes there is no integrated adapter, only GeForce 710M.

**Comment by ni-code** [comment]
@OlexiyKravchuk According to the nvidia web site, the geforce 710M comes with the optimus technology (aka integrated chipset) You should have a switch in the nvidia control panel to force an application to run in the powerful one. 
http://www.geforce.com/hardware/notebook-gpus/geforce-710m

**Comment by OlexiyKravchuk** [comment]
> akien-mga commented 2 days ago
Are you sure that Godot is using the discrete Nvidia card, and not the Intel integrated chipset? (sounds like an Optimus laptop).

> ni-code commented 18 hours ago
@OlexiyKravchuk According to the nvidia web site, the geforce 710M comes with the optimus technology (aka integrated chipset) You should have a switch in the nvidia control panel to force an application to run in the powerful one.
http://www.geforce.com/hardware/notebook-gpus/geforce-710m

I conducted an additional investigation and was able to discover that you were completely right. There really was an alternative graphics card. And after switching inside the settings, the driver, to a more powerful one. I managed to get Godot to work.
Thanks for the answers, and sorry for the trouble ...
