### ISSUE TITLE
default_theme.cpp some name incorrect

### ISSUE THREAD

**Issue by aiaimimi0920** [godotengine/godot#90294]
### Tested versions

4.3

### System information

windows 11

### Issue description

https://github.com/godotengine/godot/blob/655e93d5846b2ef8ebb7d22c8878f51b8f22b312/scene/theme/default_theme.cpp#L799C72-L799C91

In these few lines of code, I think the correct code should be:
```
	theme->set_stylebox("title_button_normal", "Tree", make_flat_stylebox(style_normal_color, 4, 4, 4, 4));
	theme->set_stylebox("title_button_pressed", "Tree", make_flat_stylebox(style_pressed_color, 4, 4, 4, 4));
	theme->set_stylebox("title_button_hover", "Tree", make_flat_stylebox(style_hover_color, 4, 4, 4, 4));
```

Or do you have a special purpose for doing this color mapping?

### Steps to reproduce

no

### Minimal reproduction project (MRP)

no

**Comment by akien-mga** [comment]
CC @Calinou @KoBeWi

**Comment by timothyqiu** [comment]
![image](https://github.com/godotengine/godot/assets/372476/d8bc5f78-00f2-4b28-af76-baa39b58cdb4)

I think this is expected.

In the default theme, `Tree` is using `style_normal_color` as its background. Title button's color has to be different.

**Comment by aiaimimi0920** [comment]
If this is expected, then you can close this issue
