### ISSUE TITLE
Area input_event not working on mobile

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#90296]
### Tested versions

Reproducable in Godot 4.3-dev5

### System information

Macbook Pro M2 - Godot 4.3-dev5 - Compability/Forward+

### Issue description

When using the event input_event on a Area2D with a collisionshape, the event is not fired in the game on mobile. It do however work on desktop using the mouse. 

I haven't tested on emulator, it may work there as well. But still, not when exported to android.

### Steps to reproduce

1. Download the MRP
2. Export it to an android device.
3. Try clicking the sprite which has the Area2D attached to it.

No even is fired (the sprite should turn green as it does on desktop)

### Minimal reproduction project (MRP)

[playground.zip](https://github.com/godotengine/godot/files/14893133/playground.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has been fixed, see:
* https://github.com/godotengine/godot/issues/89683
