### ISSUE TITLE
Sliver of the previous frame showing in AnimatedSprite2D

### ISSUE THREAD

**Issue by carsonetb** [godotengine/godot#90292]
### Tested versions

- I've reproduced this in 4.2 which is what I'm using for my game currently.

### System information

Windows 11 - Godot 4.2.1.stable.official - Forward+

### Issue description

When I have an AnimatedSprite2D where the bottom layer of pixels of the previous frame shows up as a little sliver at the top of the current frame:
![image](https://github.com/godotengine/godot/assets/63245844/6f558822-0800-44fc-aefb-edbda6dc4866)
That little sliver at the top shouldn't be there.

I think this is a bug with how Godot renders the AnimatedSprite2D animation and if it is intended then it should be documented.

Disclaimer: I'm new with reporting bugs on Github, please tell me if I've done something wrong.

### Steps to reproduce

Make any animation with two frames where the bottom layer of pixels from the first frame touches the top of the second frame like shown below:
![image](https://github.com/godotengine/godot/assets/63245844/b2b90f43-bd6b-4698-b418-0b0740e208fe)

### Minimal reproduction project (MRP)

[Issue MRP.zip](https://github.com/godotengine/godot/files/14892792/Issue.MRP.zip)

**Comment by lvcivs** [comment]
The hairline effect seen here looks similar to #76435

When I open your MRP, the AnimatedSprite2D has no filter set. When I set Texture > Filter to "Nearest" in the Inspector, the hairline disappears.

**Comment by lvcivs** [comment]
See also #81998

**Comment by AThousandShips** [comment]
Closing due to lack of response, this is likely caused by filtering as explained above
