### ISSUE TITLE
EditorPlugin add_custom_type with base custom not working

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#90291]
### Tested versions

reproducible in 4.2.1.stable 

### System information

Windows 10 - Godot 4.2.1 Stable

### Issue description

I tried to add a few custom types:
```
add_custom_type("A Node","Node",preload("a.gd"),preload("a.svg"))
add_custom_type("B Node","A Node",preload("b.gd"),preload("b.svg"))
add_custom_type("C Node","A Node",preload("c.gd"),preload("c.svg"))
```
the problem is that only `A Node` is added to the Create New Node dialog
but if I add `class_name ANode` in `a.gd` it works, why?

### Steps to reproduce

create a new plugin and add 2 or 3 scripts with names a, b, and c
now try to add custom types
```
add_custom_type("A Node","Node",preload("a.gd"),preload("a.svg"))
add_custom_type("B Node","A Node",preload("b.gd"),preload("b.svg"))
add_custom_type("C Node","A Node",preload("c.gd"),preload("c.svg"))
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can you try with a valid type name? It can't contain spaces

**Comment by DexterFstone** [comment]
> Can you try with a valid type name? It can't contain spaces

still not working

**Comment by AThousandShips** [comment]
But also yes you can't extend a custom class created this way, it's not creating real classes, see [the documentation](https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-method-add-custom-type)

This is a legacy system not designed to be used for complex features, you should use `class_name` instead if you want advanced features, as the documentation says
