### ISSUE TITLE
GPUParticles2d bug using texture() on a shader and HDR2D with Forward+ (compatibility mode works fine)

### ISSUE THREAD

**Issue by francogp** [godotengine/godot#90305]
### Tested versions

can reproduce on 4.2.1

### System information

Windows 11

### Issue description

If I enable HDR 2D on the project and use Forward+ renderer, My GPU particles does not sample the pixels in the right way. They are too bright. But sprites2d version of the texture is OK

HDR 2d + Compatibility enabled on the project
![image](https://github.com/godotengine/godot/assets/2739706/a81898e9-f1f1-4001-97a3-26e5e308506a)

HDR 2d + Forward+  enabled on the project
![image](https://github.com/godotengine/godot/assets/2739706/6c32337f-8c02-4aa1-93dd-6207e60ae10c)
 

### Steps to reproduce

just create a CanvasItem shader on a GPU particle 2D, and use texture() function to sample a uniform texture. Then enable HDR 2D on the project. 
If you use Forward+ engine, the problem appears. If you switch to compatibility engine, or disable HDR2D on the project, the problem disappear

### Minimal reproduction project (MRP)

In this demo, the engine is on Forward+, so the glitch is visible. 
[Particle2dBug.zip](https://github.com/godotengine/godot/files/14893925/Particle2dBug.zip)

**Comment by AThousandShips** [comment]
Does it work with:
```
uniform sampler2D flipbox_texture : source_color;
```

(also please don't include the `.godot` folder, it makes the download much larger)

**Comment by francogp** [comment]
> Does it work with:
> 
> ```
> uniform sampler2D flipbox_texture : source_color;
> ```
> 
> (also please don't include the `.godot` folder, it makes the download much larger)

yes, that solves the problem on Forward+ renderer. Is this a bug or an intended functionality ? but it seems an inconsistent behaviour

**Comment by AThousandShips** [comment]
It's intended, it changes if it uses sRGB, see [here](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#uniforms)

**Comment by AThousandShips** [comment]
Since this is documented and solved should I go ahead and close it?
