### ISSUE TITLE
funcs in Autoload scripts do not correctly return custom types

### ISSUE THREAD

**Issue by NickMakesGames** [godotengine/godot#90319]
### Tested versions

Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Windows 11 Pro, Version 22H2, OS Build 22621.3296 

### Issue description

If a function in an autoload script specifies a return type of a "custom type" (i.e. anything defined using `class_name`), the type will not be returned correctly when other nodes call the function

### Steps to reproduce

Create a new `ArbitraryNode.gd` script:
```
extends Node # issue is reproducible if script extends Resource, as well
class_name ArbitraryNode

func arbitrary_func():
	pass
```

Create a `UtilityFunctions.gd` script and include it as an autoload in the project settings:
```
extends Node

func get_arbitrary_node() -> ArbitraryNode:
	return ArbitraryNode.new()
```

Create a `TestNode.gd` script to test interactions with the `ArbitraryNode` type:
```
extends Resource
class_name TestNode

func test_autoload():
	var arbitrary_node_local := ArbitraryNode.new()
	# I get auto-complete when typing arbitrary_func here.
	# I can also control-click on arbitrary_func to go to its definition
	arbitrary_node_local.arbitrary_func()
	
	var arbitrary_node_func := get_arbitrary_node()
	# I get auto-complete when typing arbitrary_func here.
	# I can also control-click on arbitrary_func to go to its definition
	arbitrary_node_func.arbitrary_func()
	
	var arbitrary_node_autoload = UtilityFunctions.get_arbitrary_node()
	# I do not get auto-complete here,
	# and I cannot control-click on the function to see its definition.
	arbitrary_node_autoload.arbitrary_func()

	
func get_arbitrary_node() -> ArbitraryNode:
	return ArbitraryNode.new()
```

Note that `arbitrary_node_autoload` is not typed as an `ArbitraryNode` and does not provide common editor features for typed variables. Oddly, even if I explicitly type `arbitrary_node_autoload` by writing something like `var arbitrary_node_autoload:ArbitraryNode = UtilityFunctions.get_arbitrary_node()`, I still do not get the editor features I would expect.

Instead, I have to explicitly cast the returned type like so: `var arbitrary_node_autoload = UtilityFunctions.get_arbitrary_node() as ArbitraryNode` 

### Minimal reproduction project (MRP)

N/A

**Comment by HolonProduction** [comment]
Could you try with the latest [dev build](https://godotengine.org/download/preview/) please. There was a fix which might solve this, at least for autoloads written in GDScript.

**Comment by NickMakesGames** [comment]
yeah this seems to be fixed in the latest dev build! Thanks for the tip!
