### ISSUE TITLE
[4.2.1] TabContainer with a large font draws gap between tabs and panels

### ISSUE THREAD

**Issue by sk33z3r** [godotengine/godot#90332]
### Tested versions

Reproducible in v4.2.1.stable.flathub [b09f793f5], another user on Discord also mentions v4.2 but that it didn't occur in a previous version (they did not specify the version number that worked).

Discord forum link for reference: https://discord.com/channels/212250894228652034/1187192074815156364

### System information

Arch Linux (Steam Deck), Godot 4.2.1 Stable

### Issue description

When I make the font size of a TabContainer's tab buttons large, running the scene draws a gap between the tab buttons and their panel. However, the gap is not present anywhere in the Editor (Theme Editor, Theme Preview, 2D Scene).

I expect the tabs to look uniform whether I am running the scene (using F6) or viewing in the Editor.

**_Another quirk of the Editor related to this bug:_** Whenever I reload the Theme Editor Preview, or hide and re-open the Theme Editor panel itself, the tabs are visually separated from the panels for a split second and then they correct themselves and connect to the panels.

### Steps to reproduce

1. Create TabContainer node in any scene
2. Add some UI Control nodes as children to the TabContainer to get a few tabs
3. Edit the theme and make the font size for the tab buttons large (in my case 18)
4. Ensure the content margins are identical across all styleboxes
- Observe: Tab buttons connect with their panels in the Editor
![tabs_01](https://github.com/godotengine/godot/assets/20587571/616a72a6-fa8f-46a0-9887-15531e7db893)
![tabs_02](https://github.com/godotengine/godot/assets/20587571/ac812e00-0bad-4a48-ac83-5082676a4b40)

5. Run the scene (with F6)
- Observe: Tab buttons are separated from their panels
![tabs_03](https://github.com/godotengine/godot/assets/20587571/45ba1278-3ea0-4946-ace2-593baf9aa60c)

### Minimal reproduction project (MRP)

The attached MRP has a single scene, built as described in the reproduction:

- 4 Control nodes as children of a TabContainer
- All Styles setup the same, with Content Margins 20, 20, 20, 20
- Font size set to 18

In Editor, tab buttons are connected. Pressing F6, tab buttons are separated. The large the font, the larger the separation seems to be (but may also be dependent on the font geometry?)

[TabContainerSpacing.zip](https://github.com/godotengine/godot/files/14895764/TabContainerSpacing.zip)

**Comment by AeioMuch** [comment]
Can reproduce in 4.2.1.stable.
Can't reproduce v4.2.2.rc2 or on current master (e5b4ef8e9)

**Comment by sk33z3r** [comment]
@AeioMuch thanks for checking latest versions. I haven't been able to spend time trying to build from source on the Steam Deck, but I had a feeling it might've been an accidental regression that could already be fixed in the next release. I'll try to do that and confirm on my end.

There must be something about my system/gfx driver that causes the Editor to fix itself. I do see the separation in the editor, but only for a split second. No matter since it's probably not an issue anymore.

**Comment by AeioMuch** [comment]
> @AeioMuch thanks for checking latest versions. I haven't been able to spend time trying to build from source on the Steam Deck, but I had a feeling it might've been an accidental regression that could already be fixed in the next release. I'll try to do that and confirm on my end.
> 
> There must be something about my system/gfx driver that causes the Editor to fix itself. I do see the separation in the editor, but only for a split second. No matter since it's probably not an issue anymore.

You can test with 4.2.2.rc2 if you want, you can download it here https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/

**Comment by sk33z3r** [comment]
I might not have searched closed issues just because 4.2.1 is latest stable under releases. I'm used to keeping things open until official release, but looks like it is based on when the PR merges here. Will keep in mind for future.

In any case, I can confirm in 4.2.2 RC2 that it is fixed on my side. Thanks again.
