### ISSUE TITLE
BMFont ignores draw while font less 2 pixels 

### ISSUE THREAD

**Issue by sky94520** [godotengine/godot#90339]
### Tested versions

Godot 4.3dev4

### System information

Mac OS 14.3 - Godot4.3dev4 - Vulkan (Forward+)

### Issue description

I use Pixel fonts to generate BMFont and use it in Godot, but I found it exists issue for those chars such as```,.-'"```, and I found those chars all less 2 pixels.

for example, I input the following string to Label:
```
-+123456789.!`Ii,."
```
the UI is as follows:
<img width="375" alt="image" src="https://github.com/godotengine/godot/assets/37724405/3b0f4a4a-a052-4262-b7d3-de012839d075">

### Steps to reproduce

1. Download [fusion-pixel-font-10px-monospaced-ttf-v2024.04.05.zip](https://github.com/TakWolf/fusion-pixel-font/releases/download/2024.04.05/fusion-pixel-font-10px-monospaced-ttf-v2024.04.05.zip), extracting the zip.
2. Download [fontbm](https://github.com/vladimirgamalyan/fontbm), move usion-pixel-font-10px-monospaced-ttf-v2024.04.05/fusion-pixel-10px-monospaced-zh_hans.ttf to fontbm root directory, compile the source code and execute the following command to generate BM font.
```
./fontbm --font-file fusion-pixel-10px-monospaced-zh_hans.ttf --font-size 10 --output damage-number
```
then move ```damage-number.fnt``` and ```damage-number_0.png``` to Godot project.
3. Create a Label, and set ```Theme Overrides->Fonts``` using ```damage-number.fnt```.
4. Input the following string ```-+123456789.!`Ii,."```.

### Minimal reproduction project (MRP)

[TestBMFont.zip](https://github.com/godotengine/godot/files/14896763/TestBMFont.zip)

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/90349, for previous version in should be fixable by adding 1px padding on each side (usually adding padding is a good idea, since packing glyphs without it will not work well with texture filtering).

**Comment by bruvzg** [comment]
> I use the command to generate a new font file, but it is same as before.

Vertical padding should be set as well: `--padding-up 1 --padding-down 1`

**Comment by sky94520** [comment]
Thank you @bruvzg, I add ```--padding-left 1 --padding-right --padding-up 1 --padding-down 1``` to regenerate font file, it is correct.
<img width="379" alt="image" src="https://github.com/godotengine/godot/assets/37724405/e6a6eaca-a4d7-4e4f-b8f0-f85791a7bd7f">
