### ISSUE TITLE
Debugger stoped with large variable content in the breakpoint stack

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#9034]
**Operating system or device - Godot version:**
Arch Linux - ~~Godot 2.1.3~~ Godot 3.0 alpha1

**Issue description:**

The debugger server stopped and client frazed when break point.

**Steps to reproduce:**

```gdscript
extends Control

func _ready():
	var godot_classes = {}
	var file = File.new()
	if OK == file.open("res://classes.json", File.READ):
		var json_text = file.get_as_text()
                godot_classes.parse_json(json_text)
		breakpoint
```
When the file `res://classes.json` is larger than 64KB the debugger will stoped.

**Comment by Geequlim** [comment]
This problem should be fixed with 2.1 branch but still exist in master but the limit changed to 8MB now with 90a595ac4273dbf79809c810421f1f439c78e452.

**Comment by reduz** [comment]
yeah i think the new limit is a lot more reasonable

**Comment by akien-mga** [comment]
So do we consider this as "fixed" with the new limit, or is a better fix still wanted?

**Comment by reduz** [comment]
i dont know, maybe we should try encoding the variables before sending them and see how big they are, and just send something null if beyond treshold
