### ISSUE TITLE
The editor completely softlocks in weird ways when editing a Curve2D, which forces a reset.

### ISSUE THREAD

**Issue by JHDev2006** [godotengine/godot#90353]
### Tested versions

Only present in 4.3 dev 5

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.4592) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When editing a Path2D and various other nodes (Happens reliably with Path2D, other nodes are not known, but still happens occasionally), the ability to change values, add nodes / remove nodes, etc is completely disabled, regardless of the scene, or if the path2D node is selected. It is incredibly frustrating as i frequently use Curve2D's in my project, and each time i have to reload the editor completely once i've finished editing the curve.

### Steps to reproduce

1. Create a Path2D node
2. Select it, to have the points editor tab show up on the top of the window.
3. Observe how certain actions just cannot be performed, such as pressing the "reset" button next to the curve2D, Setting of values is completely disabled as well as adding and deleting nodes.

### Minimal reproduction project (MRP)

N/A

**Comment by JHDev2006** [comment]
Tested some more. Found out the issue is only persistent if the scene with the Curve2D is present, closing and reopening the scene fixes it, still frustrating.

**Comment by JHDev2006** [comment]
did some more testing, i think its something to do with adding or editing a point on the curve, as simply selecting the curve2D does not cause this issue?

**Comment by AyyZerrAsa** [comment]
I've noticed this, saving the scene also unlocked things for me.

**Comment by JHDev2006** [comment]
Issue #89781 fixes this, thanks guys! ❤️

**Comment by uzkbwza** [comment]
this appears to be happening again in 4.3.beta3 :(

**Comment by akien-mga** [comment]
@uzkbwza Can you give more details on how exactly you're reproducing the issue?

I can't reproduce the issue following the steps in the OP in 4.3.beta3 on Linux.

**Comment by JHDev2006** [comment]
same here, cannot seem to replicate the issue based on what the bug originally was. Interested to see if its a new thing.

**Comment by uzkbwza** [comment]
> @uzkbwza Can you give more details on how exactly you're reproducing the issue?
> 
> I can't reproduce the issue following the steps in the OP in 4.3.beta3 on Linux.

creating a path2D node and adding or editing points breaks the undo functionality for the whole editor, requiring a restart. I'll try to see if I can replicate it with a minimal example when I'm home

**Comment by uzkbwza** [comment]
here is a video of what happens with just a base Path2D node.

https://github.com/user-attachments/assets/e7415033-12a6-4ec5-a63d-1028bca25477
