### ISSUE TITLE
Crash when running project with error `ERROR: Condition "flushing_cmd_queue != nullptr" is true.`

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#90363]
### Tested versions

 - Reproducible in: v4.3.dev.custom_build [e5b4ef8e9]

### System information

Godot v4.3.dev (e5b4ef8e9) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Upon running the [TestCustomTextures](https://github.com/godotengine/godot-demo-projects/tree/master/compute/texture) Demo project it crashes with the error:

```
ERROR: Condition "flushing_cmd_queue != nullptr" is true.
at: WorkerThreadPool::thread_enter_command_queue_mt_flush (core\object\worker_thread_pool.cpp:591)
```

The [TestCustomTextures](https://github.com/godotengine/godot-demo-projects/tree/master/compute/texture) Demo works in 4.2.1 Stable version.

### Steps to reproduce

Open the [TestCustomTextures](https://github.com/godotengine/godot-demo-projects/tree/master/compute/texture) Demo project and attempt to run it.
Note that it opens fine in the editor initially. It only crashes when you attempt to Play it.

### Minimal reproduction project (MRP)

Use the [TestCustomTextures](https://github.com/godotengine/godot-demo-projects/tree/master/compute/texture) Demo project.

### Bisect results

83241ab1393dc4f0cbdf6ac3b4f0aa805c2cc22a is the first bad commit
commit 83241ab1393dc4f0cbdf6ac3b4f0aa805c2cc22a

Date:   Mon Jan 29 14:47:50 2024 -0800

    Enforce calling RenderingDevice code from rendering thread in TextureRD classes

 scene/resources/texture_rd.cpp | 186 ++++++++++++++++++++++-------------------
 scene/resources/texture_rd.h   |   9 ++
 2 files changed, 108 insertions(+), 87 deletions(-)

**Comment by chrisl8** [comment]
❯ git bisect good
eb7741807557924b0ab7dea2cca39bd9584f6a84 is the first bad commit
commit eb7741807557924b0ab7dea2cca39bd9584f6a84
Merge: 5ae4faf555 d8b29efe66

Date:   Tue Feb 13 17:23:37 2024 +0100

    Merge pull request #87006 from AThousandShips/frame_fix

    Fix member names of `AudioFrame` to match extension

**Comment by akien-mga** [comment]
> https://github.com/godotengine/godot/commit/83241ab1393dc4f0cbdf6ac3b4f0aa805c2cc22a is the first bad commit

That's #87721, CC @clayjohn @RandomShaper.

**Comment by clayjohn** [comment]
When I run the demo project with dev 5 I just get this warning:
```
W 0:00:02:0207   setup2: The Multi-Threaded rendering thread model is experimental, and has known issues which can lead to project crashes. Use the Single-Safe option in the project settings instead.
  <C++ Source>   main/main.cpp:2712 @ setup2()
```
Turning off multi threaded rendering solves the issue. 

I'm still compiling latest master, I will update this once I test from latest

**Comment by clayjohn** [comment]
Okay, it is crashing on this line https://github.com/godotengine/godot/blob/9d6bdbc56e0ac99a6cc3aaed1c114a6528cb87fc/core/templates/command_queue_mt.h#L373

With this signal:
```
signal SIGSEGV: address not mapped to object (fault address: 0x0)
```

**Comment by clayjohn** [comment]
This diff fixes the crash, but I don't think it is the correct solution:
```
diff --git a/core/templates/command_queue_mt.h b/core/templates/command_queue_mt.h
index 4056119851..80953ad3cc 100644
--- a/core/templates/command_queue_mt.h
+++ b/core/templates/command_queue_mt.h
@@ -412,7 +412,7 @@ public:
        SPACE_SEP_LIST(DECL_PUSH_AND_SYNC, 15)
 
        _FORCE_INLINE_ void flush_if_pending() {
-               if (unlikely(command_mem.size() > 0)) {
+               if (unlikely(command_mem.size() > 0 && flush_read_ptr == 0)) {
                        _flush();
                }
        }
```
This skips the flush when another flush is occurring, it works because `flush_if_pending` is always called from the same thread. However, I think most likely waiting or yielding is the more correct approach here to preserve the order of function calls.
