### ISSUE TITLE
Implementing `_get_name()` in EditorExportPlugin prevents some resources from being passed to `_export_file()`

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#90364]
### Tested versions

4.3 e5b4ef8

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I was experimenting with EditorExportPlugin trying to achieve empty export. Aside from #67844, I encountered this issue.
In my super small test project I have 2 script files (1 test file and 1 for plugin). If the plugin does not implement `_get_name()` method, there is an error on export, but the script file is normally passed to `_export_file()` and can be skipped. If I implement `_get_name()`, the error disappears, but script files are no longer skipped. They never land in `_export_file()`.

### Steps to reproduce

1. Open MRP
2. Export ZIP
3. The output prints
```
2 res://icon.svg
1 res://Test.tscn
```
(1 comes from `_export_file()`, 2 from `_customize_resource()`)
4. Open `export.gd`
5. Remove `_get_name()` method
6. Export again
7. Now it prints
```
1 res://addons/expor/expor.gd
2 res://icon.svg
1 res://Test.gd
1 res://Test.tscn
```
and the scripts are not included in the ZIP.

### Minimal reproduction project (MRP)

[Testxport.zip](https://github.com/godotengine/godot/files/14899020/Testxport.zip)

**Comment by allenwp** [comment]
It seems that returning an empty `String` as the name behaves similar to not implementing the `_get_name()` function. This can be a workaround that both avoids the error message from not implementing `_get_name()` and also ensures all files are correctly sent to `_export_file()`:

``` GDScript
func _get_name() -> String:
	return ""
```

**Comment by allenwp** [comment]
Not sure when I'll get back to this, but the issue seems to happen at [this line](https://github.com/godotengine/godot/blob/82cedc83c9069125207c128f9a07ce3d82c317cc/editor/export/editor_export_platform.cpp#L1157): When `_get_name()` is empty or not implemented, that condition will be true for each `path`. When `_get_name()` is implemented and non-empty, that condition will be false for some, but not all `path`.

**Comment by KoBeWi** [comment]
Wow I forgot I already reported this 🤦‍♂️
I identified the problem here #93487
Closing as forward duplicate (??)
