### ISSUE TITLE
Editor crashing when exporting to windows on linux

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#90383]
### Tested versions

Godot 4.3 dev 5 (official build)

### System information

Godot v4.3.dev5 - TUXEDO OS 2 22.04.4 - X11 - GLES3 (Compatibility) - AMD Radeon R7 Graphics (radeonsi, kaveri, LLVM 15.0.7, DRM 3.54, 6.5.0-10027-tuxedo) () - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

When exporting to windows on linux (tuxedo os 2), the editor hangs and i cant click anything!

Here's a video showcasing the problem

https://github.com/godotengine/godot/assets/94475453/c0fde5ae-d5b1-4f88-a7a2-1c61b325ebb6

### Steps to reproduce

- Add the windows export
- Export the project
- & Editor crashes...

### Minimal reproduction project (MRP)

N/A

**Comment by AdilDevStuff** [comment]
I switched to zorin os and tested and now it works. It might be some issue with tuxedo os.

**Comment by akien-mga** [comment]
Closing then as it's no longer reproducible.

I believe this might have been a configuration specific issue (maybe with wine/rcedit for editing the Windows PE data?), more than a Tuxedo OS one (CC @hakro who runs Tuxedo OS IINM).

**Comment by hakro** [comment]
> Closing then as it's no longer reproducible.
> 
> I believe this might have been a configuration specific issue (maybe with wine/rcedit for editing the Windows PE data?), more than a Tuxedo OS one (CC @hakro who runs Tuxedo OS IINM).

Yeah, I'm on  Tuxedo OS 3
Tried exporting to Windows using Godot v4.3.rc2 and I did not get any issue or crash.
I don't have Wine or rcedit configured atm though.
