### ISSUE TITLE
Script Editor gets blocked when "´" or "`" is typed

### ISSUE THREAD

**Issue by Mixaffected** [godotengine/godot#90399]
### Tested versions

- Reproducible in version 4.2.1

### System information

Godot v4.2.1.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Thu Apr  4 20:32:38 UTC 2024 - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 Laptop GPU () - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

When you type "´" or "`" character into the script editor you cant type anymore. You need to switch the view to be able to write again but the char is gone.

### Steps to reproduce

1. Create a fresh project
2. Attach a script to a node
3. Write "´" or "`" into the script editor

### Minimal reproduction project (MRP)

[Test_MRP.zip](https://github.com/godotengine/godot/files/14909005/Test_MRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85664
