### ISSUE TITLE
Button pressed style is not showed if button is focused

### ISSUE THREAD

**Issue by GINZUcz** [godotengine/godot#90393]
### Tested versions

4.2, 4.2.1, 4.3 dev5

### System information

Windows 11

### Issue description

I would expect when i click on button when it is focused it just change into **PRESSED** button style which i created.
(it only shows if it is hovered and clicked). Or it meant to do that?

### Steps to reproduce

Idk just do what i wrote upper please.

### Minimal reproduction project (MRP)

I tried it on various versions so if you want to see it just try it on your own..

**Comment by AThousandShips** [comment]
Please provide an MRP so we can tell what's going on, you might have configured something wrong and it's impossible to tell from your description, just from your description I can't replicate what you're describing

**Comment by GINZUcz** [comment]
[PZ-test.zip](https://github.com/godotengine/godot/files/14908213/PZ-test.zip)
OK there it is!

**Comment by KoBeWi** [comment]
Focus style is shown on top of other styles, so if it's opaque, you will see only focus. Check the documentation for `focus` stylebox.

**Comment by GINZUcz** [comment]
I see. thank you!
