### ISSUE TITLE
Godot 4.2.1.mono: "Game.dylib" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by Ciel1996** [godotengine/godot#90397]
### Tested versions

- Reproducible in 4.2.1.mono [b09f793f5], I haven't tried it on other projects and versions of Godot yet, but will if you ask me to

### System information

Godot v4.2.1.stable.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Hi all

I've been struggling for a couple of days now to get my game working after I uploaded it to App Store Connect and downloading it via Test Flight.

The export to macOS App Store Connect works fine and as expected, however, after downloading and running the game via Test Flight, I get the following error (I can click either button, the game will not crash, until later):
![image](https://github.com/godotengine/godot/assets/13202834/0bc59835-35b4-47ad-8b32-3c620dc1b7ba)

I assume this is related to .NET 8 (with AOT, I tried without AOT before, but it was basically the same issue, I asked on the [Discord](https://discord.com/channels/212250894228652034/1226104676827660399/1226104676827660399), but I'm pretty sure I've either found a bug or did overlook something in the docs by now.)

From what little information I can gather is that "Art-Race.dylib" is created into a "Caches" Folder at "/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches" after I start the app. The .dylib is adhoc signed and I suspect that Apple can't check it for malicious software because of this:

```
Executable=/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib
Identifier=Art-Race.dylib
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=138567 flags=0x20002(adhoc,linker-signed) hashes=4327+0 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```

The game launches fine after I dismiss the popup (it appears twice btw). But the moment I click a button which triggers .NET code to be run, the game crashes.

When running the game from terminal I get this on startup until I click the button that causes the crash:
```
.NET: Initializing module...
ERROR: Can't open dynamic library: /Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib.
 Error: dlopen(/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib, 0x0002):
  tried: '/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib' (code signature in <{UUIDv3}> 
  '/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib' not valid for use in process: library load disallowed by system policy),
  '/System/Volumes/Preboot/Cryptexes/OS/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib' (no such file), 
  '/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib' (code signature in <{UUIDv3}> 
  '/Users/{user}/Library/Containers/{BundleIdentifier}/Data/Library/Caches/data_Art-Race_macos_arm64/Art-Race.dylib' not valid for use in process: library load disallowed by system policy).
   at: open_dynamic_library (platform/macos/os_macos.mm:234)
ERROR: .NET: Failed to load hostfxr
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:399)
`
```

My .csproj:
```
<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net7.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'ios' ">net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>ArtRace</RootNamespace>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <!-- Root the assemblies to avoid trimming. -->
    <TrimmerRootAssembly Include="GodotSharp" />
    <TrimmerRootAssembly Include="$(TargetName)" />
  </ItemGroup>
</Project>
```

### Steps to reproduce

1. Export successfully for App Store Distribution (my game required both Network Server and Network Client entitlements in sandboxed mode)
2. Upload to App Store Connect via Transporter
3. Download the game using Test Flight
4. Start the game

### Minimal reproduction project (MRP)

I will provide an MRP as soon as possible and required. Maybe somebody did already solve this problem. :)

**Comment by bruvzg** [comment]
Seems like .Net export is packing native libs to the PCK and extracting it in runtime, this is probably the reason lib is not signed correctly (but it should not be done in general, all libs should be inside bundle). I guess it was never detected before, since ad-hoc signed libs will work on the machine they were built.

https://github.com/godotengine/godot/blob/0c6b5efab329b0e43348b2fd3a291dfae70e96aa/modules/mono/godotsharp_dirs.cpp#L173-L174

**Comment by Ciel1996** [comment]
Interesting enough I'm having the issue on the same machine I'm building the and shipping the game from. Sorry I didn't mention that.

**Comment by bruvzg** [comment]
This seems to be the issue only if `embed build outputs` is selected in the export options (disabled by default), so fixing should be as simple as removing this option for macOS.

<img width="929" alt="Screenshot 2024-04-09 at 09 37 40" src="https://github.com/godotengine/godot/assets/7645683/526c0fd9-e4f1-491a-9237-1a0ae5f26a3d">

**Comment by Ciel1996** [comment]
So it should work if I disable it now? I'll give it a try :)

**Comment by Ciel1996** [comment]
It does indeed not show an error message when starting the app.

However it still crashes when clicking the button.

Also when running via terminal (from *.app/Contents/MacOS using option --verbose), I still get this:

```
ERROR: Can't open dynamic library: /Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib. Error: dlopen(/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib, 0x0002): tried: '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib' (code signature invalid in <{UUIDv3}> '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x010E6C30, codeBlobSize=0x0003BA80), '/System/Volumes/Preboot/Cryptexes/OS/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib' (no such file), '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib' (code signature invalid in <{UUIDv3}> '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/Art-Race.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x010E6C30, codeBlobSize=0x0003BA80).
   at: open_dynamic_library (platform/macos/os_macos.mm:234)
ERROR: .NET: Failed to load hostfxr
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:399)
```

Seems like now the .dylib is not included it all.

I've exported the game with these dotnet settings:
![image](https://github.com/godotengine/godot/assets/13202834/e9f56c37-3949-404a-a81a-048fcef2bc83)

I'm going for another try without anything set here. :)

**Comment by bruvzg** [comment]
There might be another issue with code singing ignoring files not it `Frameworks` as well.

**Comment by Ciel1996** [comment]
Oddly enough the files are there: 
![image](https://github.com/godotengine/godot/assets/13202834/49a7f272-1131-4a74-b7e1-c4e2b4e382c4)

**Comment by bruvzg** [comment]
> There might be another issue with code singing ignoring files not it Frameworks as well.

No, signatures seems to be perfectly fine. I do not see any issues with disabled embedding. Might be something wrong specifically with .Net 8 AOT (I can't get it to run in any conditions, .Net 6 w/o AOT seems to be working fine), or it's App Store / Test Flight doing something with signatures.

**Comment by Ciel1996** [comment]
.NET 6 without AOT and disabled embedding gives me this error when uploading to App Store Connect using Transporter:

![image](https://github.com/godotengine/godot/assets/13202834/bf230319-560f-4c95-84cb-554259b6e5d4)

**Comment by Ciel1996** [comment]
> .NET 6 without AOT and with disabled embedding gives me this error when uploading to App Store Connect using Transporter:
> 
> ![image](https://private-user-images.githubusercontent.com/13202834/320788539-bf230319-560f-4c95-84cb-554259b6e5d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjIwNDUsIm5iZiI6MTcxMjY2MTc0NSwicGF0aCI6Ii8xMzIwMjgzNC8zMjA3ODg1MzktYmYyMzAzMTktNTYwZi00Yzk1LTg0Y2ItNTU0MjU5YjZlNWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDExMjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NjdkZWE0M2Y3MWNlOWYzMDczNDdlYTU5MTYwODEwZjExNDk5Nzg2ZDljM2Q1NjNlN2FjZjgzZmRkMzhhMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JhTFZsmntMZTFKv8S8Fh1aIIfgvEXqWFeOFBd28V7WI)

I also tried .NET 8 without AOT and get the same issue. Seems like exporting for App Store Connect does only work with AOT enabled.
