### ISSUE TITLE
InputEventMouseMotion does not fire with captured mouse mode

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#90392]
### Tested versions

- Reproducible in today's master: 0e50807c55d4cb24a796e7ec2901cb78698e288b
- Not reproducible in Godot_v4.3-dev5

### System information

Godot v4.3.dev (0e50807c55d4cb24a796e7ec2901cb78698e288b) - Windows 10.0.19044 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When using `Input.mouse_mode = Input.MOUSE_MODE_CAPTURED`, no `InputEventMouseMotion` events fire in `_input` or `_unhandled_input`. I believe this to be a regression from previous versions, as I don't see it documented anywhere.

### Steps to reproduce

- Create a Node + Script:

```gd
extends Node

func _ready() -> void:
	# this breaks mouse motion events - change mouse mode to have InputEventMouseMotion print
	Input.mouse_mode = Input.MOUSE_MODE_CAPTURED

func _input(event: InputEvent) -> void:
	print(event)

func _unhandled_input(event: InputEvent) -> void:
	print(event)
	
	# allow quitting via escape
	if event.is_action_pressed("ui_cancel"):
		get_tree().quit()
```

- Run project and try moving the mouse
- There is no prints for mouse movement

### Minimal reproduction project (MRP)

[bug--inputeventmousemotion-not-firing.zip](https://github.com/godotengine/godot/files/14907802/bug--inputeventmousemotion-not-firing.zip)

**Comment by AThousandShips** [comment]
Can you try latest master? Could have been fixed by:
* https://github.com/godotengine/godot/pull/90382

**Comment by RedMser** [comment]
Thanks, it is indeed fixed.
