### ISSUE TITLE
InputEvent: rename axis, scancode and button_index to index in 3.0

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9039]
Is there any reason to have different names for the following variables? They are used in the same context.

InputEventJoystickButton.button_index  -> InputEventJoystickButton.index
InputEventJoystickMotion.axis -> InputEventJoystickMotion.index
InputEventMouseButton.button_index   -> InputEventMouseButton.index
InputEventKey.scancode  -> InputEventKey.index

**Comment by reduz** [comment]
i think it's clearer the way it is, prefer not to rename it
