### ISSUE TITLE
[3.0] ButtonArray is unusable with the new theme if only icons are used

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9042]
I'm trying to make an editor plugin that uses a ButtonArray to select a mode, however I noticed it's impossible to tell which button is selected if they are icons (typical when they are used as exclusive tool buttons):

![image](https://cloud.githubusercontent.com/assets/1311555/26758361/e5539ea2-48db-11e7-8e85-b783ee2eba6a.png)
Here is a ButtonArray with 5 icon buttons, the first one is selected.

ButtonArray is not used in other plugins, which use ToolButtons, manually making them exclusive, which is not nice because ButtonArray exists and should do this job nicely.

**Comment by akien-mga** [comment]
ButtonArray was deprecated in 3.0, so I guess it's "fixed".
