### ISSUE TITLE
Animation `value_track_get_update_mode` error on RESET track using NodePath with property indexing

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#90435]
### Tested versions

- Reproducible in 4.3.dev (a7b860250f305f6cbaf61c30f232ff3bbdfdda0b)
- Not reproducible in 4.3-dev5
- Identified as a regression caused by #89389

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

In a W4 internal demo project, I noticed a regression caused by #89389 on a scene with a simple RESET track.

It seems to choke on the track animating `position:y` of a RichTextLabel, and prints this error:
```
ERROR: Condition "t->type != TYPE_VALUE" is true. Returning: UPDATE_CONTINUOUS
   at: value_track_get_update_mode (./scene/resources/animation.cpp:2690)
```

If I click the value in the timeline to inspect it, I also get this warning:
```
WARNING: Could not determine track hint for 'Control/rtl:position:y' because its base property is null.
     at: _find_hint_for_track (./editor/animation_track_editor.cpp:4315)
```

![image](https://github.com/godotengine/godot/assets/4701338/621aeecb-f87b-4baa-8f81-4a92d0deca15)

Reverting #89389 solves it.

CC @noidexe 

### Steps to reproduce

- Open MRP
- The RESET track is autoplaying, so just opening the scene should trigger the error

### Minimal reproduction project (MRP)

[bug-RESET-track.zip](https://github.com/godotengine/godot/files/14920668/bug-RESET-track.zip)

**Comment by chrisl8** [comment]
I see this error when running [Large World Coordinates](https://github.com/godotengine/godot-demo-projects/tree/master/misc/large_world_coordinates) Demo Project as well.

**Comment by chrisl8** [comment]
v4.3.dev.custom_build [9855ffd2e] fixes the `UPDATE_CONTINUOUS` error, however I am also seeing this error, which was not present in 4.3-dev5 when running [Large World Coordinates](https://github.com/godotengine/godot-demo-projects/tree/master/misc/large_world_coordinates) Demo Project

```
ERROR: Attempted to free invalid ID: 625609231310550
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 625622116212440
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 625635001114330
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 625647886016220
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
```

Is this related, or an entirely different issue?

**Comment by TokageItLab** [comment]
@chrisl8 Thanks for testing! The second error looks rendering issue so it shouldn’t be relevant with this issue.
