### ISSUE TITLE
Can't check the type of event from _input

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#9043]
**Operating system or device - Godot version:**
Debian 9 - Godot 3.0 (Commit 8126a0c)

**Issue description:**
With the changes of InputEvent the syntax for `_input(event)` should be:

    func _input(event):

        print(event)

        # or without the parenthesis, it doesn't work either way.
        if (event extends InputEventMouseMotion):
            print("event is mouse motion!")

But that triggers `error: ':' expected at end of line`, which is not helpful because ':' is present at end of line.

If I use `if event is InputEventMouseMotion:` it works, but then there is no way to get the position of the event.

**Comment by hickop** [comment]
I think what you try to achieve can be done with:
```
if event.is_class("InputEventMouseMotion"):
    print(event.relative) # relative mouse position
```

**Comment by akien-mga** [comment]
> If I use `if event is InputEventMouseMotion:` it works, but then there is no way to get the position of the event.

Well, that's the correct syntax. If you can't get the position, that's another issue (try `.position`, it was just changed).

**Comment by vicguedez** [comment]
@akien-mga Ty.

`event.position` and `event.global_position` works (not as expected but no error is thrown), but they do not work as `node.get_global_mouse_position()` ... I'm using `node.get_global_mouse_position()`... Is that the correct behavior or just a little bug?
