### ISSUE TITLE
GodotCoin

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#9044]
Good day to all!
I've been following the project for a long time. And I see that the team has some financial problems with some periodicity. People donate money more willingly to training material on the engine (beautifully designed) than on the engine itself. And the developers of the engine is always without money. It's time to put an end to it (at least try).

What I suggest:
   1 To create a crypto currency. Crypto-currencies are gaining momentum and this is obvious. They no longer will not go anywhere. Yes, the competition is now huge. But you can still jump in the outgoing car.
   2 Money to spend on the development of the engine, training material and free games for the community
   3 If the project succeeds in sponsoring other open projects (accepting applications from them and allocating money to them)
   4 Maybe something else.

What you need for this:
   1 Crypto currency. For example, based on https: //cryptonote.org
   2 Well-designed advertising company (you can ask Nathan Lovato for the design and submission of the material)
   3 Little bit of luck
Who thinks anything about this?

**Comment by nunodonato** [comment]
@reduz is setting up a Patreon to help fund his work on Godot full-time, it should be launched soon.

**Comment by akien-mga** [comment]
This has nothing to do with game development, we're not crypto currency developers.

**Comment by ret80** [comment]
@nunodonato Patriot - I'm not sure that the profit from it is enough for at least ice cream, not to mention the support and development of a complex product as a game engine.

@akien-mga Everything about funding has a lot to do with game development. No money there are no games.

I propose not to close the topic for 24 hours. If during this time I do not find support from the community, I will close it myself.

**Comment by akien-mga** [comment]
Funding is not meant to be discussed in the issue tracker. The issue tracker is meant for **engine-related** bug reports and feature proposals. A crypto currency has nothing to do with the game engine whatsoever - whether it's a good idea to help bring funds to the developers, that's another topic, but out of place in this issue tracker.

You can use one of the other community channels to discuss such idea: https://godotengine.org/community

**Comment by Omicron666** [comment]
https://en.liberapay.com/on/github/reduz/

**Comment by punto-** [comment]
Now that Akien is gone, when's the ICO?
