### ISSUE TITLE
`Attempted to free invalid ID` Errors from running project.

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#90452]
### Tested versions

v4.3.dev.custom_build [6c5792806]

Does not occur with 4.2.1 Stable

### System information

Godot v4.3.dev (a7b860250) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Regular errors when running the [Large World Coordinates](https://github.com/godotengine/godot-demo-projects/tree/master/misc/large_world_coordinates) Demo Project:

```
ERROR: Attempted to free invalid ID: 616542555348694
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 616555440250584
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 616568325152474
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
ERROR: Attempted to free invalid ID: 616581210054364
   at: RenderingDevice::_free_internal (servers\rendering\rendering_device.cpp:4609)
```

### Steps to reproduce

Open the [Large World Coordinates](https://github.com/godotengine/godot-demo-projects/tree/master/misc/large_world_coordinates) Demo Project
Open the Output Window
Run/Play it.
Switch between the editor and running game screen a few times can spur them on.
Also switch between the Output and Debugger view.
Then close it and these errors appear, sometimes repeatedly.

### Minimal reproduction project (MRP)

Use the [Large World Coordinates](https://github.com/godotengine/godot-demo-projects/tree/master/misc/large_world_coordinates) Demo Project

### Bisect Results

dfa326ef55ee7c973afef6527b42844e7179a0ff is the first bad commit
commit dfa326ef55ee7c973afef6527b42844e7179a0ff
Merged in https://github.com/godotengine/godot/pull/89531 70c05f63daf6fe25d2cd34f051d4fc2a6bdfe6cb
Author: @sullyscience
Date:   Thu Mar 14 16:07:44 2024 -0400

    Fix: Address mobile resource leaks in render

    Update render_forward_mobile destructor to include instance buffers.
    Update render_scene_buffers_rd cleanup to include weight buffers / blur
    textures.

 .../rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp | 5 +++++
 .../rendering/renderer_rd/storage_rd/render_scene_buffers_rd.cpp   | 7 +++++++
 2 files changed, 12 insertions(+)

**Comment by akien-mga** [comment]
Linking the PR: #89531
CC @clayjohn @BastiaanOlij

**Comment by BastiaanOlij** [comment]
I think what might be missing here is that after we free the buffer (`RD::get_singleton()->free(weight_buffer.weight)`), we don't clear the RID, meaning it will try and free it again later only to give the error that it has already been freed.
Usually not a problem when done in a destructor, but in a function like `cleanup` that is also called when buffers have to be recreated, it causes issues.

**Comment by olivatooo** [comment]
This is still happening!
