### ISSUE TITLE
get_collider_metadata missing function / misleading documentation

### ISSUE THREAD

**Issue by Tybobobo** [godotengine/godot#9045]
**Operating system or device - Godot version:**
Godot 2.1.3 Stable Steam

**Issue description:**
Inside the **KinematicBody2D** documentation:
![image](https://cloud.githubusercontent.com/assets/6776092/26761024/037123f4-4928-11e7-9e95-942f5b458e93.png)
It does not seem to be possible to body_set_shape_metadata(). 
(Noshyaar from Discord mentioned it is not bound to GDScript)

Issue may somewhat be related to https://github.com/godotengine/godot/issues/3154

**Comment by eon-s** [comment]
Works fine here, how are you setting the metadata?

**Comment by noshyaar** [comment]
`Physics2DServer.body_set_shape_metadata()` works as expected and you can call it from GDScript. I meant that `Body.set_shape_metadata()` which is called by that function is not exposed in GDScript. (And I think it's not supposed to be.) Sorry for the confusion.

**Comment by Tybobobo** [comment]
Closing due to a misunderstanding
