### ISSUE TITLE
Typed arrays with custom types don't show up in the debugger's variable stack

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#90467]
### Tested versions

v4.3.dev.custom_build [a7b860250]

### System information

linux

### Issue description

```gdscript
var my_array: Array[MyCustomClass] = []
breakpoint
```
at the breakpoint, `my_array` doesn't show up as a local variable in the debugger.

### Steps to reproduce

run the above code and check the debugger

### Minimal reproduction project (MRP)

```gdscript
extends Node

class MyCustomClass:
	pass

func _ready() -> void:
	var custom: Array[MyCustomClass]
	breakpoint
```

**Comment by quirkylemon** [comment]
would it be possible to add a argument to 'encode_variant' that says if it is debug or not? then use my original solution if it is being used for debugging. would that still cause problems?
