### ISSUE TITLE
Unable to get AABB of MeshInstance3D deformed by Skeleton3D bones

### ISSUE THREAD

**Issue by ManasMakde** [godotengine/godot#90465]
### Tested versions

- Reproducable in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (nvidia; 525.147.05) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

when retrieving the [AABB](https://docs.godotengine.org/en/stable/classes/class_aabb.html) using [get_aabb()](https://docs.godotengine.org/en/stable/classes/class_visualinstance3d.html#class-visualinstance3d-method-get-aabb) for a `MeshInstance3D` deformed by `Skeleton3D` it doesn't give the aabb of the deformed mesh but only of the original orientation 

It has been pointed out that it isn't exposed in the scripting languages even though it is [calculated internally](https://github.com/clayjohn/godot/blob/da945ce6266ce27ba63b6b08dc0eb2414594f7cb/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L650)   

![ffrOS](https://github.com/godotengine/godot/assets/73928607/5d46ea86-47c0-4fa5-9968-eb5c77ab56b2)

<h2>Why should it be exposed?</h2>

An example where it would be handy is if the mesh image was needed to be captured using `SubViewport`,  
Knowing the AABB of the deformed mesh would allow for the camera to completely & precisely bring into view the deformed mesh

### Steps to reproduce

1. Import a rigged model from blender
2. Deform the model's mesh via Skeleton3D bones
3. Try and retrieve AABB using get_aabb()

### Minimal reproduction project (MRP)

[Mesh Deform MRP.zip](https://github.com/godotengine/godot/files/14928527/Mesh.Deform.MRP.zip)

**Comment by JekSun97** [comment]
I confirm this problem on 4.2.1 and 4.3 dev 5, I have not checked other versions

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85171
