### ISSUE TITLE
Editor Crashes when typing in the name of a particular custom node

### ISSUE THREAD

**Issue by ThePhantomLemon** [godotengine/godot#90463]
### Tested versions

- Reproducible in: 4.3-dev5, 4.3-stable (only 2 tested)

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

If you have a custom node that contains an error, and inherits from another node, and your custom node's name contains the parent node's name, the editor will crash when you try to search the parent node in the "add node" menu. That's the best I can do. The steps to reproduce should clarify what I'm talking about. It's worth noting that the names don't seem to matter too much, but do seem to need to follow a [name] & [prefix][name] pattern.

### Steps to reproduce

1: Make a new project
2: create these two files:
```gdscript
# S.gd
class_name S
extends Node
```
```gdscript
#AS.gd
class_name AS
extends S

var a: A
```
3: click the add node button and search "s"

### Minimal reproduction project (MRP)

[no-s.zip](https://github.com/godotengine/godot/files/14927535/no-s.zip)

**Comment by Maran23** [comment]
This might be fixed by https://github.com/godotengine/godot/pull/86447.
See also: https://github.com/godotengine/godot/pull/90483

**Comment by Calinou** [comment]
I can confirm this was fixed by https://github.com/godotengine/godot/pull/86447. (I could reproduce the issue before that PR was merged.)
