### ISSUE TITLE
Use Ctrl C & V to duplicate a line in script editor will make the caret move to the first column

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#90462]
### Tested versions

Current master

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 () - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

See this video, when I use Ctrl C and Ctrl V to duplicate a line and the caret moves to the start of the new line, instead of the same as the  duplicated line.

https://github.com/godotengine/godot/assets/8315986/d69f10c5-3c95-47e8-9d43-d48f251d5480

See how vscode handles this:

https://github.com/godotengine/godot/assets/8315986/51dba1e3-501e-4cb6-8232-9a594347c19f

Not sure if it's related to https://github.com/godotengine/godot/issues/90420

### Steps to reproduce

Open the script editor, use Ctrl C and Ctrl V to duplicate a line and observe the cursor/caret

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- mentioned in https://github.com/godotengine/godot/issues/86863#cut
- and fixed by https://github.com/godotengine/godot/pull/86978
