### ISSUE TITLE
It's hard to see if Audio Bus buttons are pressed or not

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9047]
The Solo/Mute/Bypass buttons in the Audio Buses toggle status are too alike, it's very hard to tell if they are on or off.

All on vs all off:
![godot windows opt tools 64 3 0_2017-06-04_14-12-52](https://cloud.githubusercontent.com/assets/5599796/26763791/163fe314-4930-11e7-9b8f-e7ca60823e24.png)

**Comment by groud** [comment]
Agree, I saw that this morning and thought the same.
Can be set as "Junior job" I guess... :)
