### ISSUE TITLE
Exported custom resources aren't initialised at runtime

### ISSUE THREAD

**Issue by jacksterooney** [godotengine/godot#90480]
### Tested versions

- Reproduced in v4.2.1.stable.official [b09f793f5]

### System information

Mac OS 14.4.1, Apple M1 Chip

### Issue description

My goal is to define a custom resource (`block.gd`), and have this as an exported field by a Block Manager. I've defined a custom class name, and am using BlockManager as a Tool.

While I'm able to set it as expected in the editor, when run either in editor or in game, the variable shows as null in code. We are checking in the `_ready` function, where one would expect all exported variables to already be set.

### Steps to reproduce

Run the sample project as is, and note in the console that we are outputting that the block is null, when indeed it has been set.

### Minimal reproduction project (MRP)

[BugRecreation.zip](https://github.com/godotengine/godot/files/14930973/BugRecreation.zip)

**Comment by kleonc** [comment]
Within the MRP the `BlockManager.gd` is added as a `TextureManager` autoload and such instantiated script has `block` with its default value which is `null`. The in-scene `BlockManager` has the `block` correctly assigned.

![Godot_v4 2 1-stable_win64_k4Azd7JMdV](https://github.com/godotengine/godot/assets/9283098/5188fa55-992a-4d31-bbcd-df9df96ef7a8)

The scene tree when running the MRP:
![Ye7oZPVRr9](https://github.com/godotengine/godot/assets/9283098/4ecafe9e-cbcd-4bdf-a32b-6812dc6c8430)

After changing `BlockManager.gd` to:
```gdscript
@tool
extends Node

@export var block: Block

func _ready() -> void:
	prints("self=%-35s path=%-25s block=%s" % [self, get_path(), block])
```
the output is like:
```
self=TextureManager:<Node#23488103616>   path=/root/TextureManager      block=<null>
self=BlockManager:<Node#23739761861>     path=/root/Level/BlockManager  block=<Resource#-9223372013215677240>
```

No bug in here, closing.
