### ISSUE TITLE
Transparency doesn't work with exclusive fullscreen

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#90492]
### Tested versions

-4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.5161) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

Transparent windows doesn't work on exclusive fullscreen but there's a weird thing. When window is not focused transparency is working fine but when focused background gets black.

### Steps to reproduce

-Open transparency
-Open per pixel transparency
-Select window mode to Exclusive Fullscreen
-Run and focus and unfocus the window

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
Pardon my ignorance, but isn't this the definition of exclusive fullscreen? :thinking: 

Afaik it shouldn't be drawing anything in the background, the idea of to shift all the processing towards the exclusive app (for e.g. games). If it was drawing something in the background, it wouldn't be exclusive I think. :man_shrugging: 

When it isn't focused, maybe it isn't running exclusive.

**Comment by NotRabug50** [comment]
> Pardon my ignorance, but isn't this the definition of exclusive fullscreen? 🤔
> 
> Afaik it shouldn't be drawing anything in the background, the idea of to shift all the processing towards the exclusive app (for e.g. games). If it was drawing something in the background, it wouldn't be exclusive I think. 🤷‍♂️
> 
> When it isn't focused, maybe it isn't running exclusive.

idk but i experimenting a game intro that will clock fall into desktop but normal fullscreen is weird i've tried to use that but it dosen't support it

**Comment by Catastrphic** [comment]
i have the same issue but im not in exclusive fullscreen mode, im in borderless window mode with the window set to the same size as the screen

**Comment by Calinou** [comment]
> i have the same issue but im not in exclusive fullscreen mode, im in borderless window mode with the window set to the same size as the screen

Which OS are you on, and which rendering method are you using? Which graphics card model are you using as well?

This is likely because the graphics driver forces the borderless window to become an exclusive fullscreen window as an optimization. This happens automatically if the window size is set to the same width and height as the screen. This is why Godot's fullscreen window mode adds a 1-pixel border on all sides to avoid this.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
