### ISSUE TITLE
Freed nodes are no longer evaluating as truthy (as in they have a value)

### ISSUE THREAD

**Issue by Macksaur** [godotengine/godot#90513]
### Tested versions

- reproducible on: 4.3.dev [83b916bb00]
- not reproducible on: 4.2.1-stable [b09f793]

### System information

Windows

### Issue description

I'm testing out my existing 4.2 project on the latest commit and there are some breaking changes/regressions with freed objects and how to handle them. Code is not being ran in 4.3 when it worked in 4.2.

### Steps to reproduce

I have code like this that no longer works as expected.
```gdscript
var distant_node:Node
distant_node = something;

# ...
func _process(_delta: float) -> void:
  if is_instance_valid(distant_node): # do work with node
   pass # work work work

  elif distant_node: # previously had a value set
    # perform cleanup then set to null
    distant_node = null
```
It works as before if I change the elif to `elif distant_node != null`. But then this happens:
![image](https://github.com/godotengine/godot/assets/86566939/4beafdea-c48b-49f4-a8d2-06b4a54c9e89)
This doesn't look right. I am not sure if this is only debugger/visual. But it doesn't look like a node that has had a value (at some point) set by my code.

I need to reliably check if a variable has/has not been set (`truthy`) and if it still exists (`is_instance_valid`).

Is this a regression or a breaking change in 4.3?

### Minimal reproduction project (MRP)

```gdscript
var node := Node.new()
node.free()
if node: # this could be in another script
  pass # breakpoint here never hits despite never being set to null
```
The assumption here is that `bool(node)` is `true` when I personally have set it with a value.

**Comment by dalexeev** [comment]
> Is this a regression or a breaking change in 4.3?

* See #73896.

**Comment by Macksaur** [comment]
Ah, thank you for the details! I am happy to see `is_instance_valid` go as it were, but this is a very hard change to track down and Ctrl+F all the existing places in my code that rely on `if x` and replace them with `else` checks and initialization flags. I am not happy doing that. It feels very hacky.

Can you confirm the following tri-state will be supported going forward?
```gdscript
if node: # behaves as `is_instance_valid(node)`
  # use node
elif node != null:
  # cleanup freed node
  node = null
else
  # nothing to be done, null
```

This feels like a very big change for 4.3. I have a lot of code to read now.

**Comment by Macksaur** [comment]
I noticed you said `value is Object` is also an error?

![image](https://github.com/godotengine/godot/assets/86566939/51fa680f-0818-4b7c-932a-995042d689cc)

Why are `is` and `as` not simply `null`? I can't discern any benefit as to why an engine error needs to be raised.

I have code elsewhere that behaves like this. Especially if changes are being made to `is_instance_valid`, and the explicit bool of references to nodes, I would like to raise these concerns here:

![image](https://github.com/godotengine/godot/assets/86566939/36c62bb5-ba7d-40f5-ad05-03cafb7002d2)

If the goal is to get rid of unnecessary and discernent of `null` vs. free'd values, it would be nice to also permit these casts to resolve to `null` instead of crashes.

**Comment by dalexeev** [comment]
> I can't discern any benefit as to why an engine error needs to be raised.

* See #87296.

**Comment by dalexeev** [comment]
4.2.2 -> 4.3 dev 6

```text
Stringification
---------------
str(value)                      <null>          <Object#null>   <Freed Object>
var_to_str(value)               null            null            null

Booleanization
--------------
true if value else false        false           false           true -> false
true if not value else false    true            true            true
is_instance_valid(value)        false           false           false

Comparison
----------
value == null                   true            true            true  -> false
value != null                   false           false           false -> true
value == other_obj_null         true            true            true  -> false
value != other_obj_null         false           false           false -> true
value == other_freed            true  -> false  true  -> false  true  -> false
value != other_freed            false -> true   false -> true   false -> true

Strict Comparison
-----------------
is_same(value, null)            true            false           false
is_same(value, other_obj_null)  false           true            false
is_same(value, other_freed)     false           false           false

Type Checking
-------------
typeof(value) == TYPE_NIL       true            false           false
typeof(value) == TYPE_OBJECT    false           true            true
value is Object                 false           false           Error
```
