### ISSUE TITLE
Artifacting while using Directional parameter on LightmapGI

### ISSUE THREAD

**Issue by MarkieMusic** [godotengine/godot#90524]
### Tested versions

-Reproduced in 4.3 dev and 4.2.1 stable

### System information

Godot v4.2.1.stable - Windows 10.0.19041 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.3598) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Baking with LightmapGI using the Directional parameter causes artifacting to appear on all of the meshes. I've tried adjusting many parameters to deal with this, ranging from bake quality, lightmap scale, lightmap hint, and pretty much any other parameter I could find. You can kinda make out the outlines of some of the meshes within the artifacting. The placement and frequency of the artifacting also changes depending on the amount and placement of the meshes.

With Directional:
![image](https://github.com/godotengine/godot/assets/64930747/d4d0ae50-a7ca-419f-83c5-67289ff26d32)
Without Directional:
![image](https://github.com/godotengine/godot/assets/64930747/de03efc8-5d67-4edb-8b90-672ecd13f282)
Directional bake in standard view
![image](https://github.com/godotengine/godot/assets/64930747/a7adcc37-7d08-4970-8b87-b337255260e4)

### Steps to reproduce

Simply enabling or disabling Directional on LightmapGI and baking toggles this issue.

### Minimal reproduction project (MRP)

Can download the project folder here:

https://1drv.ms/u/s!AlF79qys-TaXkPtDrItFZmkPca_erA?e=3HXSOF

**Comment by WickedInsignia** [comment]
In my own experience this issue has been around since 4.0 alpha. I've never been able to use directional maps successfully.
