### ISSUE TITLE
Automatically creates a replication of nodes in the scene when the game is closed

### ISSUE THREAD

**Issue by Aishengmin** [godotengine/godot#90533]
### Tested versions

the master version

### System information

windows 10

### Issue description

https://github.com/godotengine/godot/assets/61172240/56f81779-3247-49b0-a6a0-a7e3a4b5df8a

### Steps to reproduce

Follow the actions in the video

### Minimal reproduction project (MRP)

[test1.zip](https://github.com/godotengine/godot/files/14946722/test1.zip)

**Comment by AThousandShips** [comment]
Your video doesn't work, and please specify what version you are on specifically

**Comment by AThousandShips** [comment]
Also sounds like:
* https://github.com/godotengine/godot/issues/89877

From just the description, without the video

**Comment by Aishengmin** [comment]
> Your video doesn't work, and please specify what version you are on specifically

I don't know why the video won't play, it's just a simple mp4 video, but it can be played after downloading

**Comment by Aishengmin** [comment]
> Also sounds like:
> 
> * [Switching scene tabs duplicates nodes in the scene and eventually also leads to an editor crash. #89877](https://github.com/godotengine/godot/issues/89877)
> 
> From just the description, without the video

This seems to be my problem, thank you

**Comment by AThousandShips** [comment]
Then this problem is solved in the latest version, try building the latest version

If you're still having problems please comment and we can investigate if further
