### ISSUE TITLE
UFBX Multiple animation clips  do not start at frame 0

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#90553]
### Tested versions

4.3.dev4

### System information

Windows 10

### Issue description

UFBX plugin is great!
I export with animations as you can see here using Maya. I created multiple animation clips:
![image](https://github.com/godotengine/godot/assets/37254287/3217ed01-fd78-46b9-9433-fd64168b9788)

So it seems that the keyframes start at the original timeframe. instead of all starting at  0:
![image](https://github.com/godotengine/godot/assets/37254287/4f0afdb6-7cae-4f17-aacb-31005fb2d6ad)

Obviously this one starts at 0, it is the first animation
![image](https://github.com/godotengine/godot/assets/37254287/1a3fe0b1-d2b3-4485-b922-5283283060c6)

This one has keys at the beginning:
![image](https://github.com/godotengine/godot/assets/37254287/90753235-2c30-4454-95b8-6780497d39a9)

![image](https://github.com/godotengine/godot/assets/37254287/32cde3bd-9a7d-432e-b6e1-1bb6c47fe769)

### Steps to reproduce

Import this:
[issue_animation_clips.zip](https://github.com/godotengine/godot/files/14952662/issue_animation_clips.zip)

### Minimal reproduction project (MRP)

Import this:
[issue_animation_clips.zip](https://github.com/godotengine/godot/files/14952662/issue_animation_clips.zip)

**Comment by lyuma** [comment]
Hi, would it be possible to try again using the "Trimming" checkbox under Animation in the import dock? This is what it is designed for.
![image](https://github.com/godotengine/godot/assets/39946030/c5b9c079-2aaf-40f6-9c73-83966d28411e)

The thing that I assume could be improved here is for Godot to make use of the LocalStartTime field in the FBX AnimStack to automatically select the start frame. The question is: should this setting be on by default, and how can it be done without making the system fragile.

There is a way to control the start and end frame precisely, if you input the starting and stopping frame number manually in the import settings:
![image](https://github.com/godotengine/godot/assets/39946030/aa0bb95e-c572-4e21-8d9d-dc7b70013cdf)
But it would be nice if Godot can help out perhaps by showing a range or prefilling these.

**Comment by shafnaz** [comment]
Here is the better file containing the mesh:
[issue_animation_clips.zip](https://github.com/godotengine/godot/files/14959440/issue_animation_clips.zip)

The frame range without slicing is different from the export, if you look at the "action" clip.
<img width="1231" alt="image" src="https://github.com/godotengine/godot/assets/37254287/921feccf-1db8-4849-bbf0-70c3d03aa327">
<img width="793" alt="image" src="https://github.com/godotengine/godot/assets/37254287/87a42ef6-8ec1-4154-8a72-d90c9a4214dd">

**Comment by lyuma** [comment]
@shafnaz based on a conversation with bqq, the correct way to account for time offsets is the Trimming checkbox in the import dock. Slicing should not be necessary. Have you tried enabling trimming?

**Comment by shafnaz** [comment]
I see. There is trimming, and there is slicing. Trimming is just a checkbox and auto offsets the key. Thanks guys!

**Comment by lyuma** [comment]
I think we need to discuss turning trimming on my default for fbx or ufbx. There clearly was a change in behavior here, so it would be good to have an open issue tracking this

**Comment by fire** [comment]
The behaviour for trimming off is suprising so it is a argument for making trimming on the default.
