### ISSUE TITLE
Vector3().inverse() bug

### ISSUE THREAD

**Issue by HeavyRail0451** [godotengine/godot#90568]
### Tested versions

Godot version 4.2.2.rc2.official

### System information

Windows 10

### Issue description

Wrong calculation of Vector3.inverse()

While vector3(1.0 / v.x, 1.0 / v.y, 1.0 / v.z) is work fine.

![image](https://github.com/godotengine/godot/assets/25565355/d20c2291-e301-4522-b3fe-cb1496a600c0)

In image first calculation made by plane.inverse.
Second by ```Vector3.ONE / plane.inverse().abs()```

### Steps to reproduce

```
@tool
extends Node3D

@export var start: bool = false

func _physics_process(delta):
	var plane = Vector3(-2,3,-4)
	if start:
		start = false
		#vector3(1.0 / v.x, 1.0 / v.y, 1.0 / v.z)
		
		var inv = Vector3.ONE / plane.inverse().abs()
		print(plane.inverse())
		print(inv)
```

### Minimal reproduction project (MRP)

[switch_test.zip](https://github.com/godotengine/godot/files/14956387/switch_test.zip)

**Comment by timothyqiu** [comment]
I don't understand. What's the expected output? The two outputs are the result of two different operations.

Also note that your code calls `abs()`.

**Comment by HeavyRail0451** [comment]
I expected inverted value

**Comment by akien-mga** [comment]
If you remove `abs()`, it works fine.\

```
	var plane = Vector3(-2,3,-4)
	if start:
		start = false
		#vector3(1.0 / v.x, 1.0 / v.y, 1.0 / v.z)
		
		var inv = Vector3.ONE / plane.inverse()
		print(plane)
		print(plane.inverse())
		print(inv)
```

```
(-2, 3, -4)
(-0.5, 0.333333, -0.25)
(-2, 3, -4)
```

If you were expecting `plane.inverse()` and `inv` to have the same value, you probably got confused by the variable name you chose. `inv` is the inverse of the inverse, so it's equal to `plane` (after removing the `abs()` which obviously changes the signs).

**Comment by HeavyRail0451** [comment]
No, I thought inverse will invert from (-2,3,-4) to (2,-3,4)

**Comment by akien-mga** [comment]
That would just be `-plane` (those are opposite numbers, not inverted).

Inversion means `1/x`. This is also written explicitly in the documentation for `Vector3.inverse()` :)

**Comment by HeavyRail0451** [comment]
Thanks
