### ISSUE TITLE
Caret invisible in EditorFileDialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#90569]
### Tested versions

4.3 b2f425f
Fine in 4.3 dev5

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/e265cc81-08b4-4ef1-a6ec-46b7d2f5e0a7

Apparently re-focusing the dialog fixes it.

### Steps to reproduce

1. Scene -> Open Scene
2. Type something in **File:** field

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
> Apparently re-focusing the dialog fixes it.

Maybe caused by #84363?

**Comment by KoBeWi** [comment]
Unfortunately I can't test. Reverting this PR breaks compilation :/
```
 scons: *** [platform\windows\display_server_windows.windows.editor.dev.x86_64.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0x88 in position 123: invalid start byte
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\SCons\Taskmaster.py", line 235, in execute
```

**Comment by akien-mga** [comment]
That doesn't make sense, there's no buildsystem change in that PR. How do you revert? It should just be `git revert 9240034d3c6c41fd8e027663f82e61be9386c882`.

**Comment by KoBeWi** [comment]
`git revert --no-commit 9240034d3c6c41fd8e027663f82e61be9386c882`

**Comment by akien-mga** [comment]
You probably need to delete `platform\windows\display_server_windows.windows.editor.dev.x86_64.obj`, MSVC seems confused.

**Comment by KoBeWi** [comment]
Doesn't help. I accidentally destroyed my repo when trying to fix this and in a fresh clone I have the same problem .-.

**Comment by akien-mga** [comment]
Your error sounds like https://github.com/godotengine/godot/issues/90617 and not related to the attempted revert.

**Comment by matheusmdx** [comment]
> > Apparently re-focusing the dialog fixes it.
> 
> Maybe caused by #84363?

I bisected and can confirm the error started after this merge
