### ISSUE TITLE
Web build doesn't support extensions

### ISSUE THREAD

**Issue by ZenRepublic** [godotengine/godot#90563]
### Tested versions

Tested on Godot 4.3 dev 5

### System information

Windows 11 Godot 4.3 Dev 5

### Issue description

Web build doesn't work when i enable extensions for it, getting a bunch of errors 

### Steps to reproduce

in a new fresh project, add html export option, enable "extension support" and go to web debug mode. Inspect console

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/14955175/test.zip)

**Comment by Bromeon** [comment]
@ZenRepublic is this different from the other issue you opened, https://github.com/godotengine/godot/issues/88964?

**Comment by ZenRepublic** [comment]
> @ZenRepublic is this different from the other issue you opened, #88964?

Hey, yes. This one is different.

**Comment by dsnopek** [comment]
What version of Emscripten are you compiling your GDExtension with?

You need to use the same version as the one used to compile Godot, and I think the official Godot builds presently use Emscripten 3.1.39.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
