### ISSUE TITLE
GDExtension virtual method _get_configuration_warnings() not call when this class is Rutime class.

### ISSUE THREAD

**Issue by pupil1337** [godotengine/godot#90561]
### Tested versions

4.3.dev [b2f425f]

### System information

win11

### Issue description

I use GDExtension (godot-cpp) create my game code, In order to avoid running the `_ready()` `_process()` etc.. gdvirtual function in the editor, I make almost all classes are runtime, but I found that the `_get_configuration_warnings()` gdvirtual function was also not called. Need to confirm if this is a issue(This situation occurs 100%, whether the design intention of runtime class is want to call _get_configuration_warnings())

### Steps to reproduce

1. Create a `class A` in gdextension, register it by `GDREGISTER_RUNTIME_CLASS`
2. In `class A` declare `virtual PackedStringArray _get_configuration_warnings() const;` function for check my class setting.
3. Open the engine, let `class A` as root node.
4. Discovered function `_get_configuration_warnings()` was not called

### Minimal reproduction project (MRP)

N/A

**Comment by pupil1337** [comment]
If class is runtime, the extension will replaced with placeholder extension, I tried not to change this logic but let `extension->get_virtual` and `extension->class_userdata` dont change to placeholder. Usually `extension->get_virtual` is to get my cpp-script function(like _ready() _process()), and Usually `extension->class_userdata` is "Class Name" for call cpp-script which class call func. But placeholder extension use the `extension->class_userdata` ref `ClassInfo`. The plan has failed

**Comment by ze2j** [comment]
I am not familiar with GDExtension but you probably need to call Node::update_configuration_warning somewhere to trigger the call to get_configuration_warnings.

**Comment by pupil1337** [comment]
> I am not familiar with GDExtension but you probably need to call Node::update_configuration_warning somewhere to trigger the call to get_configuration_warnings.

This function `get_configuration_warnings` is like `_ready() _process() _input()`, is godot source auto call to gdextension(my cpp-script), can`t call from gdextension to godot source.

**Comment by pupil1337** [comment]
> I am not familiar with GDExtension but you probably need to call Node::update_configuration_warning somewhere to trigger the call to get_configuration_warnings.

Oh, sorry, this function can be called, but the result of calling it will eventually try to call the `get_configuration_warnings` function in my script, so it still doesn't work

**Comment by dsnopek** [comment]
This is the same as with GDScript: if you want `_get_configuration_warnings()` to be called, you need to mark your script as `@tool`.

In GDExtension, normal classes are like `@tool`, and runtime classes are not. So, it's expected that `_get_configuration_warnings()` won't be called on a runtime class.

If you want to avoid specific things happening in the editor with a normal GDExtension class, you need to wrap it in:

```
if (!Engine::get_singleton()->is_editor_hint()) {
  // Do things we don't want to happen in the editor...
}
```

**Comment by pupil1337** [comment]
Thank you for your reply. I understand. This shouldn't be a issues.
