### ISSUE TITLE
Editor: can't edit/create CollisionPolygon2D's polygons

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#9057]
**Operating system or device - Godot version:**
Latest commit of Godot on Linux (Lubuntu 17.04)

**Issue description:**
after selecting a CollisionPolygon2D in the editor and pressing the pencil icon (create polygon from scratch) clicking on the 2d editor window doesn't do anything.

**What it was expected to do**
create and edito polygons for the CollisionPolygon2D

**Steps to reproduce:**
select a CollisionPolygon2D, select pencil icon and attempt to draw polygons

**Comment by HummusSamurai** [comment]
See [this PR](https://github.com/godotengine/godot/pull/9035) and [this issue.](https://github.com/godotengine/godot/pull/8425)

Could be a duplicate.

**Comment by akien-mga** [comment]
Assumed fixed by 41c3ca35.

**Comment by ImFlavo** [comment]
It didn't

**Comment by ImFlavo** [comment]
it didn't @akien-mga

**Comment by reduz** [comment]
tested it, works fine
