### ISSUE TITLE
In C# Return Variant As Specific type from same method to variable

### ISSUE THREAD

**Issue by FloatVip** [godotengine/godot#90577]
### Tested versions

Godot 4.2.1 stable .mono

### System information

windows 10 , Godot 4.2.1 stable , compatibility  

### Issue description

I want to return a variant to int for example
like this :
![Screenshot 2024-04-12 155518](https://github.com/godotengine/godot/assets/164573131/ea469f20-620e-4061-a379-23038a9f9803)

### Steps to reproduce

  public static Variant Var()
   {
      Variant var = new Variant();
      return var.As<int>();
   }

   public void GetTheVar()
   {
      int v = Var();
   }

### Minimal reproduction project (MRP)

..

**Comment by AThousandShips** [comment]
Try `long v = Var()`, or `int v = Var().As<int>()`, `Variant` has a cast to that, see [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_variant.html)

**Comment by FloatVip** [comment]
> Try `long v = Var()`, or `int v = Var().As<int>()`, `Variant` has a cast to that, but `Variant` doesn't store `int`, see [here](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_variant.html)

I know that , But i want put return variable based on type in switch . And the variant has a a lot of type variables , if i want  return several variables depends on type its hard to do that for every variable .

**Comment by AThousandShips** [comment]
That's not supported, only the types listed are stored, you'd need your own system to track sub types

**Comment by FloatVip** [comment]
> That's not supported, only the types listed are stored, you'd need your own system to track sub types
> 
> So this is something you'd have to implement yourself, the type doesn't support general types like that, it only tracks the specific types
> 
> So if you want something like that implemented in the engine itself you'd need to open a [proposal](https://github.com/godotengine/godot-proposals), but otherwise this isn't a bug and it's something that's documented

That's Right , Thank you very much ^_^ ..
