### ISSUE TITLE
Having moved the FileSystem to bottom, using "Show in FileSystem" crashes the editor

### ISSUE THREAD

**Issue by nubels** [godotengine/godot#90572]
### Tested versions

- Reproducible in 4.3.dev5 

### System information

Godot v4.3.dev5 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

While using the "Move to Bottom" option of the FileSystem panel, using the "Show in FileSystem" option of the Node pop up menu crashes the editor.

![Godot_v4 3-dev5_win64_mWdRnJEV2g](https://github.com/godotengine/godot/assets/81755541/705de5ed-04eb-462d-a497-48f75aed37c1)

### Steps to reproduce

1. Move the FileSystem panel to the bottom
2. Right click the root node of a custom scene
3. Left click "Show in FileSystem"

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- fixed by https://github.com/godotengine/godot/pull/88003
