### ISSUE TITLE
Black glitch on volumetric fog with Spotlight3D or Omnilight3D and high attenuation

### ISSUE THREAD

**Issue by TrueJole** [godotengine/godot#90578]
### Tested versions

- Reproducible in 4.2.1
Also in;
- 4.0-stable
- 4.3-dev5
- not in 3.5.3 (there's no volumetric fog)

### System information

Godot v4.2.1.stable (b09f793f5) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 5 3600 6-Core Processor (12 Threads) - Mesa 23.2.0-devel

### Issue description

When you have a volumetric fog and a Spotlight3D or an Omnilight3D in a scene and turn the attenuation to it's maximum, a black glitch will appear which will grow when moving the camera. It goes away if you switch the scene and come back.
Might be related to #87578.

### Steps to reproduce

- create a new Scene3D
- add a volumetric fog and a Spotlight3D or an Omnilight3D
- turn the attenuation of the light to it's maximum (1,000,000)
- move the camera in the editor a bit to see it growing rapidly

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14959054/MRP.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87136.
