### ISSUE TITLE
Occlusion culling no longer works following the Embree 4 upgrade when using `builtin_embree=no`

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#90586]
### Tested versions

- Reproducible in: 4.3.dev 029aadef563fb69cf49aa9795b62f27171f8c3f4
- Not reproducible in: 4.2.1.stable, 4.3.dev5

### System information

Godot v4.3.dev (029aadef5) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 550.67) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Occlusion culling no longer works following the Embree 4 upgrade. It doesn't seem to work in the [Occlusion culling and mesh LOD](https://github.com/godotengine/godot-demo-projects/tree/master/3d/occlusion_culling_mesh_lod) demo either, even though it worked when I was testing the PR.

### 4.3.dev 5 (working)

![image](https://github.com/godotengine/godot/assets/180032/b48f3beb-ddbe-42c6-a897-ae01f02138ff)

### 4.3.dev 029aadef563fb69cf49aa9795b62f27171f8c3f4 (broken)

![image](https://github.com/godotengine/godot/assets/180032/ef6a6324-7cda-46a9-9054-3d721e802e81)

I bisected the regression to c43eab55a417162624f47aed6bbbd0a4bd41c607 (https://github.com/godotengine/godot/pull/88783). cc @Chubercik

### Steps to reproduce

- Open the MRP linked below.
- Switch to the **Overdraw** debug draw mode in the **Perspective** menu of the 3D viewport in the editor.
- Move around in the scene with freelook. Cubes behind the discs should disappear when they are occluded.

### Minimal reproduction project (MRP)

[test_occluder_runtime_bake.zip](https://github.com/godotengine/godot/files/14961620/test_occluder_runtime_bake.zip)

**Comment by AeioMuch** [comment]
Can't reproduce on my side. It look like the first screenshot for me
Godot v4.3.dev (029aadef5) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

**Comment by Chubercik** [comment]
Can't reproduce on my side either, occlusion seems to be working as intended.

- Godot 4.3.dev6 (https://github.com/godotengine/godot/commit/64520fe6741d8ec3c55e0c9618d3fadcda949f63)
- Windows 10.0.19045
- Vulkan 1.3.277 (Forward+)
- dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 552.22)
- 7th Gen Intel(R) Core(TM) i7-7700K @ 4.20GHz (4 cores, 8 threads)

---

![screenshot_1](https://github.com/godotengine/godot/assets/37378746/c5e73543-ec4b-481f-8a5b-3ae986591f1a)

![screenshot_2](https://github.com/godotengine/godot/assets/37378746/38af1516-dcb4-4f2b-930e-b0de6b0b259b)

![screenshot_3](https://github.com/godotengine/godot/assets/37378746/83284614-d418-4e8d-b141-df4589ea0852)

**Comment by Calinou** [comment]
It turns out what broke was `builtin_embree=no`, not Embree itself (`builtin_embree=yes` is the default). I have `embree-devel-4.2.0` installed from the Fedora 39 repositories.

`builtin_embree=yes` makes the occlusion culling work again. Therefore, it appears the issue is that system Embree can no longer be used, even though the `builtin_embree` SCons option is still listed in `scons --help`.

**Comment by Chubercik** [comment]
Might've found the culprit:

https://github.com/godotengine/godot/blob/55b8724bd5188932b69a6ee484ab092cd95d4498/platform/linuxbsd/detect.py#L310-L312

I don't have a setup to test it currently, but changing `embree3` to `embree4` (or maybe `embree`? judging by the Fedora packages website: [embree3](https://packages.fedoraproject.org/pkgs/embree3/embree3/) vs [embree4](https://packages.fedoraproject.org/pkgs/embree/embree/)) should fix the issue.

**Comment by akien-mga** [comment]
Yes it should be `embree4`. But I'm surprised you get a surprisingly non workin build, as opposed to a linking issue.
