### ISSUE TITLE
Orthographic camera gizmo does not respect "keep_aspect" setting

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#90589]
### Tested versions

Reproducible in 4.2

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

The gizmo for orthographic cameras does not respect the `Keep Aspect` setting, and always behaves as though it is set to `Keep Width`. This does not affect the runtime behaviour, although it does mean the gizmo is inconsistent with the runtime behaviour.

### Steps to reproduce

- Make an orthographic camera with `Keep Aspect` property set to `Keep Height`.
- Adjust its `Size` property, preferrably with a visible grid.
- Notice how the gizmo's width, and not its height, will match the size that was set.

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Is the little triangle wrong? Or the whole view cone is wrong? 

![image](https://github.com/godotengine/godot/assets/8315986/93e35d9a-4e3c-48b2-9af1-40aba02165e6)

**Comment by MajorMcDoom** [comment]
The box size is wrong. Look at it in orthographic viewport.
