### ISSUE TITLE
Alpha Antialiasing renders objects in the transparent pipeline for no good reason, resulting in sorting and performance issues

### ISSUE THREAD

**Issue by Rytelier** [godotengine/godot#90595]
### Tested versions

- 4.3 dev4, 4.2.1, 4.1.3, 4.0.3

### System information

Godot v4.3.dev4.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Alpha clip anti-aliasing materials behave like alpha blended materials with similar issues,
- Sorting like in alpha blend materials
- Subsurface scattering stops working
- Screen texture shader displays the material in glitchy way

### Steps to reproduce

- Enable MSAA 3D
- Create mesh instance with material
- Add alpha texture to material
- Set alpha mode to clip
- Enable alpha anti-aliasing

### Minimal reproduction project (MRP)

[Alpha AA bug.zip](https://github.com/godotengine/godot/files/14963846/Alpha.AA.bug.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84242.
