### ISSUE TITLE
Code Editor: Double clicking non-ASCII text has no effect

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#90610]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

In the code editor, double clicking a word selects it… but it stops working if the current string contains non-ASCII characters and instead outputs error messages in the console:
![image](https://github.com/godotengine/godot/assets/106015575/3af2ce51-fea3-409b-ab3e-e8a7061d6123)

### Steps to reproduce

Paste some non-ASCII text in the editor and try to select it:
`# 我非常喜欢吃东西、喝茶、Godot.`
Using doubleclik, you will only be able to select "Godot"
![Godot doesn't select text](https://github.com/godotengine/godot/assets/106015575/3e7cc5e4-59ed-4bbb-a74c-fb41b3cbfd4a)

### Minimal reproduction project (MRP)

Godot code editor

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/75808
