### ISSUE TITLE
Godot 4 splash screen doesn't allow transparency

### ISSUE THREAD

**Issue by NotRabug50** [godotengine/godot#90619]
### Tested versions

-3.5.3.stable
-4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GT 1030 (NVIDIA; 31.0.15.5161) - AMD Ryzen 3 1300X Quad-Core Processor (4 Threads)

### Issue description

I noticed there is no way to use transparency on splash screen in godot 4, I tested on godot 3, godot 3 allowed transparency on splash screen but on godot 4 background was black.
![image](https://github.com/godotengine/godot/assets/78092286/9e822956-2b9b-4936-89ab-8f91fd6bf607)
Also has a weird flashing thing when you resize quick

### Steps to reproduce

-I tried on both Godot 4 and 3
-Godot 4 didn't supports it

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88881
