### ISSUE TITLE
Reverse Z depth broke LightmapGI

### ISSUE THREAD

**Issue by permelin** [godotengine/godot#90627]
### Tested versions

Bisect shows that 69a4ff8996 is the culprit

### System information

Godot v4.3.dev (2886511c1) - Debian GNU/Linux trixie/sid trixie - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (nvidia) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

After #88328 was merged, baking with LightmapGI outputs a tiny and completely black EXR which obviously doesn't provide any GI at all.

At first glance, changing `RD::COMPARE_OP_LESS` to `RD::COMPARE_OP_GREATER` in two places in `modules/lightmapper_rd/lightmapper_rd.cpp` does seem to fix it, but there is more than that going on with depth in that file and I'm not at all familiar with the code so I'll leave a PR to someone else.

### Steps to reproduce

1. Bake anything with LightmapGI.
2. Notice the absolute lack of indirect lighting.

### Minimal reproduction project (MRP)

[lightmapgi-reverse-z-mrp.zip](https://github.com/godotengine/godot/files/14967617/lightmapgi-reverse-z-mrp.zip)

**Comment by akien-mga** [comment]
CC @godotengine/rendering

**Comment by clayjohn** [comment]
This bug is really surprising, looking through the lightmapper_rd code, it doesn't seem to interact with anything that would have been changed by the reverse z PR. 

Your confirmed changes though sound exactly like the lightmapper is using reverse z somehow though, so there must be something I am missing

**Comment by JFonS** [comment]
Had a quick look. The lightmapper uses rasterization to plot the base maps and the depth is hard-coded here (and similarly in `lm_blendseams.glsl`):
https://github.com/godotengine/godot/blob/578d937927ea9735aa7a8e0535f57801406b0b82/modules/lightmapper_rd/lm_raster.glsl#L61

I guess the default clear value for depth has been flipped, so `0.0001` is discarded unless we flip the depth operator. We could also explicitly set the clear depth to 1.0 and call it a day ;)

**Comment by clayjohn** [comment]
That looks like the issue, the default clear value flipped in `draw_list_begin()`:
https://github.com/godotengine/godot/blob/578d937927ea9735aa7a8e0535f57801406b0b82/servers/rendering/rendering_device.h#L1106
We should reverse that and then make sure the proper clear depth is used where it needs to be, or else we are breaking compat for a lot of RD consumers
