### ISSUE TITLE
MeshDataTool get_vertex_count() returns the count of tris instead of verteces.

### ISSUE THREAD

**Issue by rredesigns** [godotengine/godot#9064]
**Operating system or device - Godot version:**
OS: Manjaro 17.0.1 Gellivara
Kernel: x86_64 Linux 4.9.30-1-MANJARO
CPU: Intel Celeron G1840 @ 2x 2.8GHz 
GPU: Mesa DRI Intel(R) Haswell Desktop 
RAM: 1416MiB / 3827MiB

Godot v2.1.3.stable.official

**Issue description:**
When using get_vertex_count() from the mesh generated with create_from_surface() the array returned has almost twice the amount of vertices it should have.

Comparing it to Blender data displayed, the number matches the amount of tris in the mesh, which obviously is way off. When I attempt to place other nodes on the vertices locations there are 2 or 3 copies all grouped in the same location because of this issue.

**Steps to reproduce:**
1. Load a mesh into a meshInstance (or import a scene).
2. Create a new MeshDataTool and mesh_from_surface, then get the vertex count.
3. print the array size and compare.

**Link to minimal example project:**

I can provide one if requested.

**Comment by bojidar-bg** [comment]
Is the mesh flat shaded, per chance?

If it is, then each flat face would get a seperate copy of the vertex (as if you have applied the edge split modifier), so that normals don't get interpolated between faces, as normals are per-vertex.

**Comment by rredesigns** [comment]
I tried with a bunch of different  meshes, the last one I think was flat shaded. I will try again and come back.

**Comment by kubecz3k** [comment]
I will archive this issue, since it seems it's resolved.
