### ISSUE TITLE
Issue cant get Sprite2D to render on top of OptionButton and MenuButton in UI

### ISSUE THREAD

**Issue by Mickstv** [godotengine/godot#90648]
### Tested versions

- Reproducible in : All Godot 4.0 + versions

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated GeForce GTX 1050 () - Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 Threads)

### Issue description

The issue is I have made a Virtual Cursor for UI,  it works fine except for is you want to click on either OptionButton or MenuButton.  The sprite renders under the Button dropdown as can be seen in the picture below.  If I use Godot 3.5.3 I don't have this problem.

![OptionButton Issue](https://github.com/godotengine/godot/assets/166711376/d61f5256-2de2-4ff3-9864-ee0a9c8d775a)

### Steps to reproduce

Simple Control Node and OptionButton and/or MenuButton and Sprite2d All as Children of the Control Node

### Minimal reproduction project (MRP)

N/A

[OptionsDropdown Issue.zip](https://github.com/godotengine/godot/files/14968854/OptionsDropdown.Issue.zip)

**Comment by AThousandShips** [comment]
This is because embedded elements are drawn on a high layer, see [here](https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html#description)

**Comment by Mickstv** [comment]
> This is because embedded elements are drawn on a high layer, see [here](https://docs.godotengine.org/en/stable/classes/class_canvaslayer.html#description)

Thanks for the reply.  I see 1024 and 1025.  I tried putting the Sprite2d into a higher z-index (Also tried as a Child of a Control Node) but it made no difference.  Do you have any ideas what I can do to rectify the problem.  The answer is evading me.....

**Comment by AThousandShips** [comment]
Not z-index, canvas layer index, you need to make a layer

**Comment by Mickstv** [comment]
> Not z-index, canvas layer index, you need to make a layer
> 
> > This order will hold regardless of the CanvasItem.z_index of the nodes within each layer.


Ok I tried this,  two canvaslayers one with the optionbutton on and the other with the sprite2d on and I changed the layer of the second canvas holding the optionbutton but the dropdown is still drawn over the sprite in the second layer.  

Could you please have a look at the project and see what I'm doing wrong then repost it ?  Thanks

[Canvas Layer UI Godot 4.2.zip](https://github.com/godotengine/godot/files/14972107/Canvas.Layer.UI.Godot.4.2.zip)

**Comment by AeioMuch** [comment]
> > Not z-index, canvas layer index, you need to make a layer
> > > This order will hold regardless of the CanvasItem.z_index of the nodes within each layer.
> 
> Ok I tried this, two canvaslayers one with the optionbutton on and the other with the sprite2d on and I changed the layer of the second canvas holding the optionbutton but the dropdown is still drawn over the sprite in the second layer.
> 
> Could you please have a look at the project and see what I'm doing wrong then repost it ? Thanks
> 
> [Canvas Layer UI Godot 4.2.zip](https://github.com/godotengine/godot/files/14972107/Canvas.Layer.UI.Godot.4.2.zip)

You just need one `CanvasLayer` with a script on it, and your `Sprite2D` as a child of it. Then on the script you would have for instance :
`func _ready():
	layer = 1025
`

**Comment by Mickstv** [comment]
> > > Not z-index, canvas layer index, you need to make a layer
> > > > This order will hold regardless of the CanvasItem.z_index of the nodes within each layer.
> > 
> > 
> > Ok I tried this, two canvaslayers one with the optionbutton on and the other with the sprite2d on and I changed the layer of the second canvas holding the optionbutton but the dropdown is still drawn over the sprite in the second layer.
> > Could you please have a look at the project and see what I'm doing wrong then repost it ? Thanks
> > [Canvas Layer UI Godot 4.2.zip](https://github.com/godotengine/godot/files/14972107/Canvas.Layer.UI.Godot.4.2.zip)
> 
> You just need one `CanvasLayer` with a script on it, and your `Sprite2D` as a child of it. Then on the script you would have for instance : `func _ready(): layer = 1025 `
> 
> Your `OptionButton` does not need to be a child of a `CanvasLayer`.


Thanks for the reply.  That worked,  the part I was missing was setting the layer in code for the CanvasLayer.
