### ISSUE TITLE
MainLoop can no longer provide an exit code when it quits.

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#90646]
### Tested versions

- Reproducible in 4.3-dev5
- Reproducible in 4.2.1-stable

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-12700H (14 Threads)

### Issue description

https://github.com/godotengine/godot/commit/60d2c1fd47a0c24a127ea00f09724537f5527dbb removed OS.set_exit_code() but it had a valid use case for setting the exit code from MainLoop.

I suggest adding MainLoop.set_exit_code() since MainLoop has no `.quit()` where you can provide the exit code.

### Steps to reproduce

godot -s main_loop.gd
```
extends MainLoop
func _process(delta):
    # No longer have any way to accomplish this
    # OS.set_exit_code(1)
    # workaround?
    var st := SceneTree.new()
    st.quit(1)
    st.free()
    return true
```

### Minimal reproduction project (MRP)

[main_loop_exit_code.zip](https://github.com/godotengine/godot/files/14968833/main_loop_exit_code.zip)

**Comment by dalexeev** [comment]
See:

* godotengine/godot-proposals#7557
* #89229
