### ISSUE TITLE
glTF files aren't always automatically reimported

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#90659]
### Tested versions

4.2.1
v4.3.beta.custom_build [8bf8f41fc]

### System information

Godot v4.2.1.stable - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Godot automatically reimports gltf if objects are added or removed, if the geometry changes in terms of number of vertices, or if the overall dimensions change. However when vertices are moved inside of the bounding box of the original model, gltf is not automatically reimported and has to be reimported manually by clicking the "Reimport" button. This quirk can be annoying when working on level blockouts in blender because sometimes you move faces without adding any new geometry

### Steps to reproduce

Move some vertices in a model inside of its bounding box (you can scale the middle cube in the MRP in edit mode in blender), export gltf and see that nothing happens in godot

### Minimal reproduction project (MRP)

[MRPGLTF.zip](https://github.com/godotengine/godot/files/14970504/MRPGLTF.zip)

**Comment by viksl** [comment]
I'm in 4.3 [578d937927ea9735aa7a8e0535f57801406b0b82] and can confirm this, though sometimes it does update for me but most of the time it doesn't.

**Comment by passivestar** [comment]
Also doesn't reimport if the animation changes

**Comment by lyuma** [comment]
Can you clarify how you exported the gltf? Are you using gltf separate, gltf embedded or glb binary?

is the issue that only the .bin (binary vertex data and annimation data) changes , but godot is only looking at the .gltf (overall document structure, not data)
