### ISSUE TITLE
Directories containing a `project.godot` file show up as files in the editor's file explorers

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#90657]
### Tested versions

- I believe this has been happening for all of 4.x
- still happens in v4.3.dev.custom_build [578d93792]

### System information

linux

### Issue description

|directory content|how it shows up in the editor's file explorers (once the file extension filter has been set to `All Files (*)`)|
|-|-|
|![image](https://github.com/godotengine/godot/assets/71937306/af9d8927-f826-49e6-a7a1-947f18b2c61a)|![image](https://github.com/godotengine/godot/assets/71937306/8d93e25c-f8b3-43d7-b54d-f2b7274378c6)|

- it only shows up if no file filters are in place
- it can be navigated to by manually inputing the path
- it happens for global file/dir explorer, such as the one for the editor's custom theme or an exported property with `@export_global_file`

### Steps to reproduce

- open any godot project
- from the file explorer at `Editor settings > interface/theme/custom_theme`, navigate to the opened project's parent directory
- disable the file filter and notice it shows up as a file

### Minimal reproduction project (MRP)

any

**Comment by KoBeWi** [comment]
Same issue with `.gdignore`. Might be something wrong with `_should_skip_directory()`.
