### ISSUE TITLE
Unable to generate and propagate custom InputEvent class objects

### ISSUE THREAD

**Issue by majenkotech** [godotengine/godot#90655]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Arch Linux

### Issue description

The way the input system (specifically `Input.parse_input_event()` currently works it appears that it is impossible to create your own derived InputEvent class (such as a sub-class of `InputEventScreenTouch`) and then pass objects of that type to the input event queue through `Input.parse_input_event()`. The event objects go through the queue and propagate fine, but they are stripped of their sub-class identity, since the `parse_input_event()` casts and checks each of its hard-coded classes in turn, then passing that cast variant on to the queue. That makes it impossible to identify the correct event type in any receiving code.

### Steps to reproduce

Create a sub-class of any InputEvent class and pass it to the input queue.

### Minimal reproduction project (MRP)

[HeatTest.zip](https://github.com/godotengine/godot/files/14970450/HeatTest.zip)

**Comment by Sauermann** [comment]
I can confirm, that this is the current behavior and it works as intended.

So your suggested change is more of a feature proposal, then a bug report.
May I redirect you to https://github.com/godotengine/godot-proposals which is a more appropriate place for these and suggest, that you create a proposal for the change there?

**Comment by majenkotech** [comment]
Ok, that's fine then. Proposal generated.
