### ISSUE TITLE
Toggling distraction-free mode selects (or opens) a fixed script in the script list

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#90654]
### Tested versions

- does *not* happen in 4.3 dev 5
- happens in v4.3.dev.custom_build [578d93792]

### System information

linux

### Issue description

- when toggling distraction free mode, a previously opened script is automatically re-opened
  - it happens independently of the number of opened scripts 
- if deleted, it reopens anyway as an unsaved script

- in the clip below, I create a new script and toggle distraction free mode after closing the script: notice how it gets automatically re-openened. Note that I use a shortcut to close the script, which is why it happens quickly.

https://github.com/godotengine/godot/assets/71937306/4ae4a8a9-0dac-455c-9941-d95b7e3c88b2

### Steps to reproduce

- create a script and open it, and close it
- toggle distraction free mode
- notice how the script opens automatically

### Minimal reproduction project (MRP)

any

**Comment by kitbdev** [comment]
- Probably introduced in https://github.com/godotengine/godot/pull/88003. 

It unified all methods that affect docks, so toggling distraction free mode now calls `EditorNode::get_singleton()->edit_current();`. Before, only some methods called edit_current, and I'm not sure if it's necessary.

So, should it not call edit_current or should edit_current be changed?

**Comment by KoBeWi** [comment]
Related:

https://github.com/godotengine/godot/assets/2223172/fc2752a5-b17b-4690-a837-7a3fff7374c9

After you created a script, clicking any dock will open script editor. Extremely annoying.

**Comment by akien-mga** [comment]
Reopening as #90816 was reverted due to a crash.
