### ISSUE TITLE
Signal rebind on a transformed Callable with a .bind() doesn't change arguments

### ISSUE THREAD

**Issue by Haledire** [godotengine/godot#90681]
### Tested versions

Reproducible in 4.3 dev5 and 4.2 stable

### System information

Windows 10, Godot 4.2 stable

### Issue description

When using `get_signal_connection_list()` to obtain a copy of a callable - trying to unbind and rebind a value to this Callable - then disconnecting and connecting to a new version of the Callable obtained in this fashion does not replace the arguments when the signal is emitted

### Steps to reproduce

Sample code:
```
extends Node2D
signal some_signal
func _ready():
	some_signal.connect(_some_test.bind("this"))
	var data = get_signal_connection_list(&"some_signal")
	print(data)
	some_signal.emit()
	some_signal.disconnect(data[0]["callable"])
	print(get_signal_connection_list(&"some_signal"))
	var new_callable = data[0]["callable"].unbind(1).bind("that")
	#var new_callable = Callable(data[0]["callable"].get_object(),
        #                            data[0]["callable"].get_method()).bind("that")
	some_signal.connect(new_callable)
	some_signal.emit()
func _some_test(arg):
	print(arg)
```
Step 1:  create some signal or use an existing signal and connect it to a Callable with a bind(). 
Step 2:  use get_signal_connection_list() to retrieve this Callable
Step 3:  use this Callable, unbind the arguments from it, rebind a new argument, and store it in a new variable
Step 4:  disconnect the callable
Step 5:  connect the new callable
Step 6:  emit the signal and check the argument that was passed
![image](https://github.com/godotengine/godot/assets/164616/60cfd0fa-fc0b-40bf-b3e8-7bce50ec26e8)

Rebuilding an entirely new callable (demonstrated in the commented code) from the object and stringname data solves this problem, but this situation is strange in that unbinding and rebinding a Callable should have the same effect as rebuilding a Callable from scratch.  Somehow despite checking the arguments have changed - using the same source Callable object (one where a value was bound) retains the argument when reconnecting a signal.

This situation also happens if it's not grabbed via `get_signal_connnection_list()` - this was simply the use case someone had brought to my attention in Discord.

ie:
```
    var some_callable = some_func.bind("this")
    signal.connect(some_callable)
    var new_callable = some_callable.unbind(1),bind("that")
    signal.disconnect(some_callable)
    signal.connect(new_callable)
```
this exhibits the same situation - it seems to specifically happen because the callable originally had a bind.

This is likely low priority as this feels like a niche use case - and there is a workaround to solve the issue.

### Minimal reproduction project (MRP)

[SignalIssue.zip](https://github.com/godotengine/godot/files/14973678/SignalIssue.zip)

**Comment by dalexeev** [comment]
`unbind()` **doesn't** remove previously bound argunents from `Callable`. Please read [the documentation](https://docs.godotengine.org/en/stable/classes/class_callable.html#class-callable-method-unbind) more carefully. It's unintuitive behavior and not very good naming, but `unbind()` is **not** the opposite of `bind()`.

`unbind()` _creates_ a wrapper over the base `Callable`. Which, when called, removes the specified number of arguments passed to it and calls the base `Callable`. So `bind`/`unbind` chains should be read _from right to left_:

```gdscript
foo.bind(3, 4).unbind(1).call(1, 2) # Calls foo(1, 3, 4)
# .call(1, 2) -> [1, 2]
# .unbind(1) -> [1]
# .bind(3, 4) -> [1, 3, 4]

some_func.bind("this").unbind(1).bind("that") # Calls some_func("this").
# .bind("that") -> ["that"]
# .unbind(1) -> []
# .bind("this") -> ["this"]
```

**Comment by Haledire** [comment]
So if you stored `some_func.bind("this")` here - even if you check the bound arguments and it no longer contains the original argument - it still has the original argument?
![image](https://github.com/godotengine/godot/assets/164616/239a8734-5fda-4339-8fa1-e5647df72293)

**Comment by dalexeev** [comment]
You misunderstand how `bind()`/`unbind()` work. `Callable` **doesn't** _store_ arguments, which would modify `bind()`/`unbind()`. Instead, a new `Callable` is created that _wraps_ the base `Callable`, creating a modifier. Calling `bind()`/`unbind()` again creates a modifier on top of a modifier, and so on. When `call()` is called, these wrappers are called in reverse order, from outer to inner. Therefore, you should read this entry from right to left.

Here's roughly how it works:

<details>
<summary>Code</summary>

```gdscript
class MyCallableCustom:
    func my_call_custom(_args: Array) -> Variant:
        return null

class MyCallableCustomBind extends MyCallableCustom:
    var _base_callable: MyCallable
    var _bind_args: Array

    func _init(base_callable: MyCallable, bind_args: Array):
        _base_callable = base_callable
        _bind_args = bind_args.duplicate()

    func my_call_custom(args: Array) -> Variant:
        return _base_callable.my_call(args + _bind_args)

class MyCallableCustomUnbind extends MyCallableCustom:
    var _base_callable: MyCallable
    var _unbind_count: int

    func _init(base_callable: MyCallable, unbind_count: int):
        _base_callable = base_callable
        _unbind_count = unbind_count

    func my_call_custom(args: Array) -> Variant:
        args = args.duplicate()
        args.resize(args.size() - _unbind_count)
        return _base_callable.my_call(args)

class MyCallable:
    var _object: Object
    var _method: StringName
    var _custom: MyCallableCustom

    func _init(object: Object = null, method: StringName = &"") -> void:
        _object = object
        _method = method

    func my_call(args: Array) -> Variant:
        if _custom:
            return _custom.my_call_custom(args)
        else:
            return _object.callv(_method, args)

    func bind(args: Array) -> MyCallable:
        var wrapper := new()
        wrapper._custom = MyCallableCustomBind.new(self, args)
        return wrapper

    func unbind(argcount: int) -> MyCallable:
        var wrapper := new()
        wrapper._custom = MyCallableCustomUnbind.new(self, argcount)
        return wrapper

func f(a, b, c):
    prints(a, b, c)

func _ready() -> void:
    MyCallable.new(self, "f").bind([3, 4]).unbind(1).my_call([1, 2])
```

</details>

**Comment by Haledire** [comment]
Ah - so get_bound_arguments() is just getting the arguments from the wrapper I'm calling it on, but the process of cycling through all the wrappers to perform the actual resulting Callable is not figured into that return.  

This isn't something that changes line by line - but call by call regardless where the calls are made (interesting that you can unbind and fall into an argument deficit - I guess that's what happens when I unbind and clear the list - the original bind is just clearing the deficit and is not filling an argument space anymore).

It's actually expected here that if someone were to need to access the original callable, you need to use the get_object() and get_method() functions to rebuild a brand new fresh wrapper (I guess that's why the functions are provided in the first place).

Thank you for the insight.
