### ISSUE TITLE
Saving scripts with the shortcut (CTRL+S) does not work with empty scene

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#9069]
**Operating system or device - Godot version:** 
Ubuntu Linux 16.04 - Godot 3.0 master branch (cloned 4 hours ago)

**Issue description:**

Trying to save scripts with the save shortcut (CTRL+S) does not work until an existing scene is 
opened or a valid scene with root node is saved.
Message: "This operation can't be done without a tree root"

**Steps to reproduce:**

Open an empty or existing project and close all open scenes. Open an empty or existing script in 
the script editor and press (CTRL+S).

**Comment by vnen** [comment]
This is not a bug, <kbd>Ctrl</kbd>+<kbd>S</kbd> saves the scene, which can't be done if there's no scene to save. The shortcut to save script is <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>S</kbd>.

**Comment by kerskuchen** [comment]
Okay but Ctrl+S also saves the currently open script in the script editor, if there is a scene open in the background (that is already saved). So by that logic Ctrl+S is also kind of for saving scripts. I think that this is a mild inconsistency from the user's perspective.
If the editor allows the user to save scripts with Ctrl+S anyway most of the time, why not allow the user to save scripts with Ctrl+S without needing to open a scene first?

**Comment by bojidar-bg** [comment]
Reopening as there seems to be interest for discussion. (and discussing on closed issues is a mess)

**Comment by vnen** [comment]
<kbd>Ctrl</kbd>+<kbd>S</kbd> to save only the script sounds sensible, but this has been discussed a few times and I don't know if something changed since them.

**Comment by eon-s** [comment]
I think context based shortcuts (scene, script, resource) should be the shorter ones and global shortcuts be the more complex combinations (to make it harder to do a global mess).

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by nickcernis** [comment]
I am still able to reproduce this in Godot 3.0.2.stable.official on Mac:

![godot-error2](https://user-images.githubusercontent.com/647669/38320770-c3b08a22-3835-11e8-83cb-e5cf1eaa02d6.png)

Reproducible with the “Kinematic Collision” project:

- Sample project: [demo.zip](https://github.com/godotengine/godot/files/1876645/demo.zip)

1. Close all open scenes.
2. Edit the `player.gd` script.
3. Attempt to save it with <kbd>Ctrl</kbd> / <kbd>Cmd</kbd> + <kbd>S</kbd>.

- Expected behaviour: the modified script is saved.
- Actual behaviour: “this operation can't be done without a tree root” message appears.

I agree with this proposal above:

> I think context based shortcuts (current focused scene/script/resource) should be the shorter ones and global shortcuts be the more complex combinations (to make it harder to do a global mess).

**Comment by Zylann** [comment]
Still happens in 3.0.3

**Comment by dark-penguin** [comment]
I have found even more "usability problems" with this. If I'm editing a script embedded in a scene, a shortcut to "Save script" opens a dialog for saving this script in a separate file. What's more, the extensions are different (see the image).
I understand that this might be "technically correct" at least from some standpoint. But I would have expected the "Save" command to save my script _where is currently is_, and "Save As" to open a dialog. This may be confusing, especially if you don't remember where this script is stored, especially for the new users.

By the way, I remap Ctrl+S to act as both "Save scene" and "Save script", too. And I agree that it really should save what you're currently editing. Unless you are editing a script that's embedded in a scene - then it should understand this and save the scene instead. (Or maybe save the script into the scene, but don't save any other changes in that scene, for consistent behavior?..)

**Comment by d0rf3n** [comment]
Shouldn't the tabs switch to being scripts instead of scenes when using the script editor?
