### ISSUE TITLE
openxr_action_map.tres file gets corrupted after restarting the editor with xr/openxr/enabled = false in project settings.

### ISSUE THREAD

**Issue by DanielSnd** [godotengine/godot#90696]
### Tested versions

v4.2.1.stable.official [b09f793f5]
v4.3.dev.custom_build [0043b4edf]

### System information

Windows 11

### Issue description

I'm running into an issue with trying to keep a project both Non-VR and VR at the same time (Ideally would run VR only when calling it to run VR from command line, and most of the time I'd be working on the project and exporting the project with xr/openxr/enabled = false

My problem is that whenever I restart the project with xr/openxr/enabled = false it corrupts the openxr_action_map.tres file somehow.

This is what a corrupted openxr_action_map.tres file looks like:
![image](https://github.com/godotengine/godot/assets/9072324/7a3039ff-3a24-403c-b9e6-b1f93b68a4a0)
![image](https://github.com/godotengine/godot/assets/9072324/d8a0ba97-1042-4d91-835f-2309666b72ed)

And these are the errors that show up in the output log:
![image](https://github.com/godotengine/godot/assets/9072324/55cda391-891b-4f38-a6be-7db47f604454)

If I try to run a build that was generated with the broken openxr_action_map.tres file this is what I get on the console:
![image](https://github.com/godotengine/godot/assets/9072324/a54731e6-7883-4102-bf77-c44e0644ef1e)

Tagging @BastiaanOlij as requested by them.

### Steps to reproduce

For reproducing the problem exporting isn't necessary at all, here are the steps that reproduce the problem consistently for me:

0 - Make sure you have the OpenXR Vendors plugin installed in the project, the problem can only be reproduced with the openxr vendors plugin installed.
1 - Have a project with a working openxr_action_map (xr/openxr/enabled = true)
2 - Turn off xr/openxr/enabled (xr/openxr/enabled = false)
3 - Restart as requested by the project settings window.
4 - After restarting turn on xr/openxr/enabled (xr/openxr/enabled = true)
5 - Restart as requested by the project settings window.
6 - See errors in output log, go to your openxr_action_map and see it's messed up.
Errors in output log after the last restart following those steps:

![image](https://github.com/godotengine/godot/assets/9072324/e0047a37-10aa-4122-bdd0-6a921b462133)

### Minimal reproduction project (MRP)

N/A

**Comment by ferminLR** [comment]
I am not able to replicate the error in 4.3.dev

**Comment by BastiaanOlij** [comment]
I think that the problem is that we're not building our meta data, so if the tres file ever gets loaded, it can't validate the contents of our action map, and I guess it ends up saving a version where all the data has been removed.

Building the meta data requires setting up far more of the OpenXR module than I'm comfortable with doing when OpenXR is not enabled, so still thinking of a way to circumvent this. Possibly we could skip the validation check if OpenXR is not enabled.
