### ISSUE TITLE
RichTextLabel "Visible Characters" setting does not hide bullet characters for BBCode lists

### ISSUE THREAD

**Issue by Jurgio** [godotengine/godot#90699]
### Tested versions

- Reproducible in: Godot v4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.19044 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5176) - AMD Ryzen 3 3200G with Radeon Vega Graphics (4 Threads)

### Issue description

I am trying to create a textbox with a typewriter effect using the "visible_characters" parameter of a RichTextLabel. Each paragraph of dialog is an item on a list made with BBCode, for aesthetic purposes. The trouble is that the bullets of the list still appear even when visible_characters is low and therefore they shouldn't be visible yet.

I don't know what causes this behaviour, and I can't find anything in the documentation that indicates that this is intended.

Hopefully this screenshot of the included MRP will help you see the problem:
![Capture](https://github.com/godotengine/godot/assets/66727441/c4d5dedc-cd33-4524-b594-def0189acae7)

### Steps to reproduce

Simply run the textbox scene and the bullets should appear immediately despite visible_characters being set to 0 at first.

### Minimal reproduction project (MRP)

[dialogbox.zip](https://github.com/godotengine/godot/files/14980329/dialogbox.zip)

**Comment by bruvzg** [comment]
Should be fixed b y https://github.com/godotengine/godot/pull/90472
