### ISSUE TITLE
Metadata's name is formatted incorrectly and causes confusion

### ISSUE THREAD

**Issue by Walker-BJ99** [godotengine/godot#90697]
### Tested versions

- Reproducible in: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19042 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When I use Metadata in the editor, the Metadata name is formatted incorrectly.

### For example:
CharName -> Char Name
show -> Show
Current_Diff -> Current Diff

### Name seen on the editor:
![image](https://github.com/godotengine/godot/assets/75510566/1f0d6e98-6cca-4774-9194-c16ae36bdcf9)
### The actual name:
```
[node name="Char" type="Node2D"]
metadata/CharDiff = {}
metadata/Height = 0
metadata/Y = 0
metadata/show = true
metadata/Current_Diff = ""
```

I need to constantly consult the metadata of the node, and the editor provides the name of the metadata with the error, which causes a lot of confusion for my coding work.

### Steps to reproduce

Create a metadata in any node and name it in the style shown above, and you can see the metadata whose name is incorrectly formatted

### Minimal reproduction project (MRP)

N/A

**Comment by timothyqiu** [comment]
- The actual name is shown in the tooltip (hover your mouse over the property name)
- Property name style can be changed in Inspector's Wrench menu, setting to Raw disables captialization
- Dragging property into the script editor yields the corresponding property path as a string

**Comment by Walker-BJ99** [comment]
OK, I see it. I didn't find that this was working as expected.

> * The actual name is shown in the tooltip (hover your mouse over the property name)
> * Property name style can be changed in Inspector's Wrench menu, setting to Raw disables captialization
> * Dragging property into the script editor yields the corresponding property path as a string
