### ISSUE TITLE
Origin line renders incorrectly in Compatibility rendering method on Mali GPU

### ISSUE THREAD

**Issue by Lufims** [godotengine/godot#90704]
### Tested versions

- Reproducible 4.2.1 [Stable], and versions from the end of last year, I don't know what version is, but, it happens on a old version too

### System information

Android 14 Godot 4.2.1 Stable Mali GPU

### Issue description

On the editor happens this, just when using compatibility renderer
![Screenshot_20240415_131259_Godot Editor 4](https://github.com/godotengine/godot/assets/73536178/386b60b3-77b3-4619-bc32-44613b6bdd0a)

### Steps to reproduce

Open the Godot on Compatibility renderer with a Samsung Galaxy A13 (Europe version)

### Minimal reproduction project (MRP)

[ShinobiWarSim.zip](https://github.com/godotengine/godot/files/14981818/ShinobiWarSim.zip)

**Comment by clayjohn** [comment]
Most likely a regression from https://github.com/godotengine/godot/pull/83895

**Comment by clayjohn** [comment]
@Lufims Did the issue go away with the latest update?

**Comment by Lufims** [comment]
> @Lufims Did the issue go away with the latest update?

Yes, but now the world grid is doing the same thing, or before it was too, but I didn't see, anyway, now I can make games without being annoyed by a glitch, thanks
