### ISSUE TITLE
Add function to ckeck is GodotSpace3D is or not.

### ISSUE THREAD

**Issue by RonYanDaik** [godotengine/godot#90711]
### Tested versions

4.2

### System information

Win 10

### Issue description

When PhysicsDirectSpaceState3D is not ready for physics calls it returns this error.
**The problem** is that when I'm trying to check is space is accessible or not by calling  `get_world_3d()->get_direct_space_state();`  it also returns same error. 
So there is no way to check if space is accessible already or not at some point.
And if you have a scatter algorithm for example that should spawn 1000s of instances on start, then your console will be flooded with this error.

Could be easily avoided if someone would add a function to check is 3D Space is accessible or not. (to both c++ and gdscript)

### Steps to reproduce

Try to call `get_world_3d()->get_direct_space_state();` on `_ready()` for example (in  c++ )

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot-docs/issues/8420

This is documented [here](https://docs.godotengine.org/en/stable/classes/class_world3d.html#class-world3d-property-direct-space-state):
> When using multi-threaded physics, access is limited to Node._physics_process in the main thread.

**Comment by RonYanDaik** [comment]
> This is documented [here](https://docs.godotengine.org/en/stable/classes/class_world3d.html#class-world3d-property-direct-space-state):
> 
> > When using multi-threaded physics, access is limited to Node._physics_process in the main thread.

Probably my bad saying that its happens on _ready();
It happens also inside _physics_process() if you are using c++ class which always work like a tool.
Also I'm using Jolt engine right now which also can interfere.
More or less the engine has this function:
```
PhysicsDirectSpaceState3D *GodotPhysicsServer3D::space_get_direct_state(RID p_space) {
	GodotSpace3D *space = space_owner.get_or_null(p_space);
	ERR_FAIL_NULL_V(space, nullptr);
	ERR_FAIL_COND_V_MSG((using_threads && !doing_sync) || space->is_locked(), nullptr, "Space state is inaccessible right now, wait for iteration or physics process notification.");

	return space->get_direct_state();
}
```
So having a function that has this check ( `(using_threads && !doing_sync) || space->is_locked()` ) and returns true or false would be very useful.

**Comment by AThousandShips** [comment]
That's pretty important information to omit, that changes things a bit, but it depends on more details, please test with the standard physics (if it doesn't occur then this shouldn't be reported here but at the plugin), and provide an MRP otherwise

**Comment by RonYanDaik** [comment]
> Probably my bad saying that its happens on _ready();
> It happens also in editor inside _physics_process() if you are using c++ class which always work like a tool.
> Also I'm using Jolt engine right now which also can interfere.

I was not paying attention where/when I was calling it. So that was my mistake.
But still a function that will check is space is accessible without error will be nice.

Something like:

```
bool *GodotPhysicsServer3D::space_get_direct_state(RID p_space) {
	GodotSpace3D *space = space_owner.get_or_null(p_space);
	ERR_FAIL_NULL_V(space, nullptr);
	return (using_threads && !doing_sync) || space->is_locked();
}
```

**Comment by RonYanDaik** [comment]
Ok. Closing.
