### ISSUE TITLE
VisualShader if block breaks when unrolled.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#90717]
### Tested versions

4.3[578d937927ea9735aa7a8e0535f57801406b0b82]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

1. The inputs after unrolling don't make sense, Tolerance and b are duplicated, there's only one condition.
2. I have no idea how outputs here are supposed to work so just a question here, are the outputs correct?

Before
![image](https://github.com/godotengine/godot/assets/33526847/76ede16e-ce6e-4a37-8a6b-231487c6e183)
Ater
![image](https://github.com/godotengine/godot/assets/33526847/a6f92f6b-cb9a-42ec-b22b-2eed82dde519)

### Steps to reproduce

Add an If node into VisualShader a press the arrow. Observe the input and outputs change and don't make sense.

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Looks like a bug to me, related code : 

https://github.com/godotengine/godot/blob/658e97c93aa2533cb7b12f05e62dcf6864e7acbe/editor/plugins/visual_shader_editor_plugin.cpp#L928-L957
