### ISSUE TITLE
SCU Web Build

### ISSUE THREAD

**Issue by cemalgnlts** [godotengine/godot#90713]
### Tested versions

Latest

### System information

*Not relevant*

### Issue description

I am having trouble getting a build for the web.

What happens in the first build process:
https://github.com/cemalgnlts/godot/actions/runs/8689267204/job/23826612841#step:7:77

I updated this file to solve this problem:
**scu_builders.py**
```diff
- process_folder(["editor"], ["file_system_dock", "editor_resource_preview"], 32)
- process_folder(["editor/debugger"])
- process_folder(["editor/debugger/debug_adapter"])
- process_folder(["editor/export"])
- process_folder(["editor/gui"])
- process_folder(["editor/import"])
- process_folder(["editor/import/3d"])
- process_folder(["editor/plugins"])
- process_folder(["editor/plugins/gizmos"])
- process_folder(["editor/plugins/tiles"])
```

Then I got a different error:
https://github.com/cemalgnlts/godot/actions/runs/8692834866/job/23838291816

*I customized it a bit to make it work *(Of course, it doesn't matter if I adapt it to suit myself)*: https://github.com/cemalgnlts/godot/commit/76620483bb8ea73b405ce3620bf728224ee0f981*

The error I then received: 
https://github.com/cemalgnlts/godot/actions/runs/8694062013/job/23842187767

### Steps to reproduce

Create a web target with `template_release` on GitHub Actions.

### Minimal reproduction project (MRP)

*(Not relevant)*

**Comment by AThousandShips** [comment]
Scu builds aren't necessarily designed for release builds, does it work correctly for debug builds? It does doe me with latest master

**Comment by cemalgnlts** [comment]
Thanks for the information. I understand better now. When I forked the repo again and tried again, no problem occurred. Changing the branch name and my subsequent actions probably caused the problem thanks.
