### ISSUE TITLE
Non-uniform scaled basis returns wrong euler angles

### ISSUE THREAD

**Issue by jbromberg** [godotengine/godot#90727]
### Tested versions

Reproducible in 4.3.dev5 and earlier

### System information

Godot v4.3.dev5 - macOS 14.1.2 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When a basis has a non uniform scale applied to it, the rotations returned by `get_euler()` are wrong. The issue is seen below:
```gdscript
var basis := Basis.from_euler(Vector3(deg_to_rad(-45), 0, 0)).scaled(Vector3(4, 4, 2))
print(rad_to_deg(basis.get_euler().x)) # Prints -90
print(rad_to_deg(basis.orthonormalized().get_euler().x)) # Prints -26
```

### Steps to reproduce

Run MRP or the code snippet above.

### Minimal reproduction project (MRP)

[basis-euler.zip](https://github.com/godotengine/godot/files/14985253/basis-euler.zip)

**Comment by jbromberg** [comment]
Even the value returned by `get_scale()` is wrong. It returns `(4, 3.162277, 3.162277)`.

**Comment by jbromberg** [comment]
I managed to get it to return the correct euler values, but the workaround is a bit ridiculous. Here's how I got it:
```gdscript
var basis := Basis.from_euler(Vector3(-45, 238, -10) * (PI / 180)).scaled(Vector3(4, 7, 2))
var scale := basis.transposed().get_scale() # Returns the actual scale of (4, 7, 2)
basis = basis.scaled(Vector3.ONE / scale) # Revert the non-uniform scale of the basis
print(basis.get_euler() * (180 / PI)) # Prints (-45, -122, -10) as expected
```

Not entirely sure if this is the expected behavior for the Basis but it's certainly very confusing that the methods named `get_euler()` and `get_scale()` don't necessarily return the values that are being set.

**Comment by AThousandShips** [comment]
I believe this is a natural limitation, there's no way AFAIK to extract the rotation from a non-uniformly scaled transform, it assumes it's a certain form, and even if there is such a formula I suspect it's an expensive one that we shouldn't rely on

So I'd say this is something to document clearly

**Comment by AThousandShips** [comment]
Also: how does it work if you use `Basis.from_euler(...) * Basis.from_scale(...)` instead?

**Comment by jbromberg** [comment]
> Also: how does it work if you use `Basis.from_euler(...) * Basis.from_scale(...)` instead?

It gets the scale right without having to transpose but the angles are still wrong.
```gdscript
var basis := Basis.from_euler(Vector3(-45, 238, -10) * (PI / 180)) * Basis.from_scale(Vector3(4, 7, 2))
print(basis.get_scale()) # Prints (4, 7, 2)
print(basis.get_euler() * (180 / PI)) # Prints (-90, -125.6608, 0)
```

**Comment by AThousandShips** [comment]
Then that side is because of the way `scaled` works, but the Euler angles still apply in the same sense I'd say, because of the limitations on decomposing, what do you get with `Basis.from_scale(Vector3(4, 7, 2)) * Basis.from_euler(Vector3(-45, 238, -10) * (PI / 180))`?

**Comment by AThousandShips** [comment]
It's possible that it's a limitation from performance, what do you get if you unscale it? I.e. do `(basis * Basis.from_scale(basis.get_scale().invert())).get_euler()`, with the first form

**Comment by jbromberg** [comment]
This works correctly:
```gdscript
var basis := Basis.from_euler(Vector3(-45, 238, -10) * (PI / 180)) * Basis.from_scale(Vector3(4, 7, 2))
basis = basis * Basis.from_scale(basis.get_scale().inverse())
print(basis.get_euler() * (180 / PI)) # Prints (-45, -122, -10)
```
But it's still wrong when using scaled:
```gdscript
var basis := Basis.from_euler(Vector3(-45, 238, -10) * (PI / 180)).scaled(Vector3(4, 7, 2))
basis = basis * Basis.from_scale(basis.get_scale().inverse())
print(basis.get_euler() * (180 / PI)) # Prints (-63.08308, -107.3506, -17.16976)
```

Could we first check if the basis has a uniform scale in order to determine which method to use to return the euler angles?

**Comment by jbromberg** [comment]
It's worth noting that this issue reveals itself in the `global_rotation` and `global_rotation_degrees` properties of a Node3D. They are often wrong when the node has a non-uniform scale.
