### ISSUE TITLE
Multithreaded memory leak (4.3 only)

### ISSUE THREAD

**Issue by Cat-Lips** [godotengine/godot#90725]
### Tested versions

 - Reproducible in 4.3
 - Not reproducible in 4.2

### System information

Godot v4.3.dev5.mono - Windows 10.0.22000 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.12027.9001) - Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 Threads)

### Issue description

Found a memory leak when setting shape data, but only if physics multithreading is turned on.  Doesn't happen in 4.2.

### Steps to reproduce

Run attached, memory use increases.
Turn off multithreading & run, no increase.

### Minimal reproduction project (MRP)

[MemTest-cs_gdscript.zip](https://github.com/godotengine/godot/files/14985017/MemTest-cs_gdscript.zip)
[MemTest-gdscript_only.zip](https://github.com/godotengine/godot/files/14985019/MemTest-gdscript_only.zip)

**Comment by Cat-Lips** [comment]
Using standard (non-mono) builds:
 - Reproducible in snapshot 3
 - Not reproducible in snapshot 1
 - (Slightly reproducible in snapshot 2)

**Comment by clayjohn** [comment]
Most likely has the same cause of https://github.com/godotengine/godot/issues/89585 which is https://github.com/godotengine/godot/pull/86587 (merged for dev3)

CC @RandomShaper Here is another MRP for you. 

@Cat-Lips If you can build Godot from source, you can try out this line of code change from Zylann, that might help https://github.com/godotengine/godot/issues/89585#issuecomment-2054165673 in the meantime

**Comment by akien-mga** [comment]
Confirmed on Linux.
