### ISSUE TITLE
[FBX] The position of the feet in the animation is wrong

### ISSUE THREAD

**Issue by dszhblx** [godotengine/godot#90734]
### Tested versions

4.3 Dev5(ufbx), 4.2.2 stable

### System information

Win10

### Issue description

I'm using an FBX model in my project, imported using 4.3dev5(ufbx). In the import settings dialog, the foot position in the walk animation is correct. But when I inherit this fbx to generate a tscn file and play the walk animation in AnimationPlayer, the position of the footsteps is wrong.
![fbx](https://github.com/godotengine/godot/assets/8831593/6e86a280-3ce9-4d55-b055-4336f2bb79df)
![fbx2](https://github.com/godotengine/godot/assets/8831593/ddffefa6-4f02-4d35-a5ce-b080a8f6f308)

### Steps to reproduce

1.open the MRP using Godot 4.3 Dev5
2.use UFBX importer
3.open enemy_2_legs.tscn, play walk animation

### Minimal reproduction project (MRP)

[testfbx.zip](https://github.com/godotengine/godot/files/14987365/testfbx.zip)

**Comment by dszhblx** [comment]
Btw,the .glb version of the model is OK

**Comment by fire** [comment]
I suspect there is IK but maybe @bqqbarbhg  has insight.

**Comment by bqqbarbhg** [comment]
Not immediately sure what it could be and can't check myself at the moment, but might be worth seeing if it also happens if using the FBX2glTF importer from the Import settings.

**Comment by dszhblx** [comment]
> Not immediately sure what it could be and can't check myself at the moment, but might be worth seeing if it also happens using the FBX2glTF importer from the Import settings.

Tested, it also happens using the FBX2glTF importer from the Import settings.

**Comment by bqqbarbhg** [comment]
> Tested, it also happens using the FBX2glTF importer from the Import settings.

Thanks a lot! Seems like it's not a ufbx issue in that case, and someone else can probably help better than I can, as I'm not very familiar with the Godot runtime side of things.

**Comment by fire** [comment]
What is your workflow for generating obj sequences? Want to check something .

**Comment by bqqbarbhg** [comment]
> What is your workflow for generating obj sequences? Want to check something .

If you mean in ufbx tests, I just export them manually from a 3D program that I know behaves correctly for the given file.

**Comment by fire** [comment]
If the ufbx error matches fbx2gltf, I'm not sure to what extent we can change it for for the pending 4.3 release.

**Comment by dszhblx** [comment]
@fire @akien-mga 
godot 4.2.2 also has this problem.
sorry about the title.
![422](https://github.com/godotengine/godot/assets/8831593/1bf5486e-c22a-4ed8-883a-e0ad019676af)

**Comment by fire** [comment]
Can you check if "trimming" works well?

**Comment by dszhblx** [comment]
> Can you check if "trimming" works well? We discussed making it the default for fbx.

Tested，regardless of whether the trimming option is turned on or not, the problem remains, both ufx and fbx2gltf.

**Comment by fire** [comment]
Try disabling the animation optimizer.

**Comment by dszhblx** [comment]
> Try disabling the animation optimizer.
> 
> ![Screenshot 2024-05-07 at 7 24 15 AM](https://private-user-images.githubusercontent.com/32321/328561239-3bab209e-b04b-48ca-830f-9abecc73a603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjY2MDgsIm5iZiI6MTcxNTEyNjMwOCwicGF0aCI6Ii8zMjMyMS8zMjg1NjEyMzktM2JhYjIwOWUtYjA0Yi00OGNhLTgzMGYtOWFiZWNjNzNhNjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDIzNTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDQ5ZDVhYmM3NTEwMjYyYTY5YTU5MjUzM2I3NTdkNzE1MzFkY2IwNTEyMmNkZGYxNTczYTEzODIyMDY5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zXBTTA_aGfJAUShJjZRQseQPdPNswQXYGGWbrVHUY7s)

Disabling the optimizer solved this bug.

**Comment by fire** [comment]
This could be a documentation request, but it does not seem to be a ufbx bug. Thanks!

Let me know what else is needed.

**Comment by dszhblx** [comment]
> This could be a documentation request, but it does not seem to be a ufbx bug. Thanks!
> 
> Let me know what else is needed. I'll close for now.

is this a bug of animation optimizer ?
