### ISSUE TITLE
Y-sort doesn't work properly

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#90739]
### Tested versions

4728ff30c

### System information

Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.171.04) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

Recently noticed that Y-sort seems to be broken.

https://github.com/godotengine/godot/assets/30386067/dbdbc3d8-7855-48d0-83b8-acfecca5e248

In the editor, it seems to be offset relative to the top left corner of the 2D Screen rather than the origin or its parent.

### Steps to reproduce

Add some nodes, enable `y_sort_enabled`, and you can see that the drawing of the nodes is offset.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
It appears to happen when the parent isn't y-sorted but the children are, I've experienced this and that solved it for me

**Comment by akien-mga** [comment]
Is it a regression, i.e. is it reproducible or not in 4.2 or earlier 4.3 dev builds?

**Comment by akien-mga** [comment]
CC @groud @KoBeWi @kleonc

**Comment by Sauermann** [comment]
bisected to 2ed2ccc2d8ff17b97d8ac0fd80fc0190ea47ed00 @rburing 
- #88424

**Comment by rburing** [comment]
Thanks a lot for catching this during the dev phase!
