### ISSUE TITLE
Can't move my character, Godot exits debug window whenever any key is pressed.

### ISSUE THREAD

**Issue by jawaadReza** [godotengine/godot#90735]
### Tested versions

I'm Using Godot 3

### System information

Windows 10 Godot3

### Issue description

I am making an FPS controller using a tutorial from YouTube. I used the exact same code that the YouTube guy was using. But, only the mouse i.e. looking around using the mouse works so far. However after assigning the WASD key binds and making the movement code. It doesn't seem to work in the Debug Window. The character does Not move when the keys are pressed. Instead, The window is exited and there is no way to get back in it.

### Steps to reproduce

I am new to programming so I don't know if there are ways to reproduce this issue.

### Minimal reproduction project (MRP)

idk what this means.

**Comment by akien-mga** [comment]
Hi, this platform is for clear bug reports about problem that are well established to be engine bugs.

What you describe sounds more like a support request, as there's likely an issue in your project/code that you need help with. Please use one of the other community platforms listed on https://godotengine.org/community/ for support.

As a hint, your issue sounds like maybe you assign the Esc key or another one handled for quitting, to your movement bindings.
