### ISSUE TITLE
Text clipping on buttons when using a custom display scale

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#90745]
### Tested versions

Current master v4.3.dev.custom_build [4728ff30c]

### System information

Godot v4.3.dev (4728ff30c) - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

I thought it was fixed but apparently it's back?

<img width="728" alt="image" src="https://github.com/godotengine/godot/assets/60579014/c5a3ce9e-fe05-4fab-a2be-3d11f1921568"><br>

Audi makes nice cars but the tab isn't about them unfortunately

### Steps to reproduce

Just set the display scale to 1.6. No custom theme

### Minimal reproduction project (MRP)

N/A

**Comment by passivestar** [comment]
I thought maybe it would make sense to make some kind of a checklist for testing UI-related PRs to prevent regressions because custom display scale bugs are consistently getting missed. I have these other two opened as well:

https://github.com/godotengine/godot/issues/89482
https://github.com/godotengine/godot/issues/89718

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Seems like a rounding error in the theme element size calculations. In case of "Audio" text buffer return width `61` in the min. size calculation, but after adding and subtracting theme margins and style box sizes only `60.9999961853027` is left for the text.
