### ISSUE TITLE
Tilemap with Y Sort always auto open within first layer when other layers have Y Sort enabled

### ISSUE THREAD

**Issue by zhuyeaini9** [godotengine/godot#90740]
### Tested versions

find in 4.3dev5,but not in 4.2. 

### System information

Godot v4.3.dev5.mono - macOS 14.3.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

tilemap ysort always auto open within first layer when other layers have ysort enabled.

### Steps to reproduce

1. add tilemap node
2. enable ysort in ordering.
3. add some layers.
4. enable some layer's ysort.
5. save and close the scene,then reopen the scene,the tilemap's first layer's ysort is always auto open.

### Minimal reproduction project (MRP)

<img width="1440" alt="image" src="https://github.com/godotengine/godot/assets/37789892/378c6a28-1c81-4dd5-8db7-d5af5fbd07a5">

**Comment by akien-mga** [comment]
If I understand correctly this would be a usability issue with how the TileMap editor infers what context to show?
CC @groud @KoBeWi

**Comment by KoBeWi** [comment]
Doesn't seem like it. I don't get what's this about.

**Comment by akien-mga** [comment]
@zhuyeaini9 The bug report is a bit unclear. Could you provide a project that shows the problem, or a video recording of the issue?

**Comment by AThousandShips** [comment]
Setting y-sort on the `TileMap` *Node* sets it for each layer:
https://github.com/godotengine/godot/blob/89f70e98d209563abb4dbc1f8cd5d76c81eb7940/scene/2d/tile_map.cpp#L376C1-L386C2

The first layer is always present when loading, and the y-sort property is ordered before I suspect, so it sets the y-sort on the single layer when assigning it to the node, and then adds the remaining layers, assigning what ever setup they have

This would only be relevant to 4.2 and before I suspect, it won't affect `TileMapLayer`

**Comment by groud** [comment]
> This would only be relevant to 4.2 and before I suspect, it won't affect TileMapLayer

TileMap should work as it used to in 4.3, even if deprecated.

I believe this is indeed a bug, I think I messed up that with my refactor. Setting the Y-sort on the TileMap node should not affect the layers Y-sort. Basically, we should just remove this I believe:
```
 	for (TileMapLayer *layer : layers) { 
 		layer->set_y_sort_enabled(p_enable); 
 	} 
 ```

**Comment by AThousandShips** [comment]
It seems that there was some error in the refactor, the 4.2 code just forces updates:
https://github.com/godotengine/godot/blob/895f1877fba1cc4176a59f5a0fbeec954dcdd0a6/scene/2d/tile_map.cpp#L3453-L3463

**Comment by zhuyeaini9** [comment]
4月7日.mp4

**Comment by zhuyeaini9** [comment]
> @zhuyeaini9 The bug report is a bit unclear. Could you provide a project that shows the problem, or a video recording of the issue?

1. create one tilemap node.
2. enable the tilemap's ordering's ysort enabled.
3. add some layers to tilemap.
4. disabled first layer's ysort.
5. save the scene,reopen the scene.
6. I find the first layer's ysort always auto enabled even if you disabled it.
