### ISSUE TITLE
Line2D joints rendered "flipped" for a 180 degree angle regardless of "joint_mode" setting.

### ISSUE THREAD

**Issue by m4rr5** [godotengine/godot#90762]
### Tested versions

- Reproducible in 4.3dev5 and 4.0-stable, render mode "Forward+" and "Compatibility" tested. Does not look like a regression.

### System information

Godot v4.3.dev5 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.2824) - Intel(R) Core(TM) i9-14900KF (32 Threads)

### Issue description

<img width="770" alt="joint_mode_1" src="https://github.com/godotengine/godot/assets/446570/4f66b08b-5f94-4b5f-b16a-976f945b24ec">

I have a Line2D object with 3 points, and I've set all the "capping" options to "Round" so I expect everything to be rounded. But it's not at the top, as you can see, and from the inspector you can also see that the line there makes a "180 degree turn".

<img width="143" alt="joint_mode_2" src="https://github.com/godotengine/godot/assets/446570/618bae10-60e0-4c51-8b68-b8473a389995">

Moving a point makes it work.

<img width="240" alt="joint_mode_3" src="https://github.com/godotengine/godot/assets/446570/ad570924-7dda-4f78-8693-14b41f4c274f">

Documentation states it should work (Joint Mode under Capping).

![joint_mode_4](https://github.com/godotengine/godot/assets/446570/7c3374dc-7232-4e89-b6f1-bd8ae95be769)

@clayjohn confirmed in renderdoc the geometry is flipped.

### Steps to reproduce

Create a Line2D as specified in the first screenshot above, or download the MRP below and look at it in 2D mode.

### Minimal reproduction project (MRP)

[godot-bug-line-caps.zip](https://github.com/godotengine/godot/files/14999601/godot-bug-line-caps.zip)

**Comment by clayjohn** [comment]
To clarify what is happening in the image of the geometry, the entire line is flipped in that image, so the bottom cap corresponds to the top cap. You can see that the cap itself is flipped which is why the line appears flat at the top.
