### ISSUE TITLE
`low_processor_mode` setting description seems outdated

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#90774]
### Tested versions

4.3 dev5 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

The description of `low_processor_usage_mode` in Project Settings says:
> This setting only works on desktop platforms.

but then the OS equivalent:
> Can improve battery consumption on mobile.

So either the project setting description is wrong (given it's 5 years old, it's rather likely), or if it's correct, it should be clarified that you need to enable it manually on mobile via OS.

### Steps to reproduce

https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-application-run-low-processor-mode
https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-property-low-processor-usage-mode

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Completed in #90785
