### ISSUE TITLE
Running a project without main doesn't actually run after selecting main

### ISSUE THREAD

**Issue by CylonMuffins** [godotengine/godot#9077]
When you hit run on your new project with no main selected, it prompts you to select a main scene. When you select a main scene, you get thrown back to the editor, and nothing happens. The project should be run automatically after you select a main as prompted.

**Comment by bojidar-bg** [comment]
BTW, I think we might have had a duplicate of this issue (I couldn't find it though), so if anyone happens to see it somewhere, please close it 😃
