### ISSUE TITLE
RichTextLabel broken autowrap

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#9078]
**Operating system or device - Godot version:**
Ubuntu 17.04  x86_64
Godot version: branch **master** and branch **2.1**
_It works fine in the 2.1.3-stable_

**Issue description:**
RichTextLabel doesn't adapt the text to it's size, but it is cutting the words.

**Steps to reproduce:**
Add a RichTextLabel, write lots of words, resize with the mouse or change the size from the inspector.

**Link to minimal example project:**

**Comment by volzhs** [comment]
maybe we should revert #8952 for now.
@akien-mga WDYT?

**Comment by akien-mga** [comment]
Indeed.
