### ISSUE TITLE
Polygon2D clipping generates spurious elements inside masked area

### ISSUE THREAD

**Issue by grunthos-dev** [godotengine/godot#90793]
### Tested versions

Reproducible in: 4.3-dev5, 4.2.1-stable, 4.1.3-stable

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

I am trying to use Polygon2D clipping to mask out an area of the screen. See picture.

When I make a test scene, the clipping polygon (selected) correctly masks the Godot icon. But there are undesired scaled copies of other elements in the scene inside the clip area (green and grey polygons). As you pan the background of the editor around these copies shift around like there is some transform effect.

![PolygonClippingMaskBugAnnotated_17Apr2024](https://github.com/godotengine/godot/assets/167312641/52e458fd-683b-45f6-ac69-cb6df842eb74)

### Steps to reproduce

1. In a 2D scene, create a white Polygon2D with points in a rough circle, called PolygonA.

2. Drag the Godot sprite Icon.svg into the viewport so that it overlaps an edge of PolygonA.

3. Make the icon sprite a child of PolygonA and set PolygonA's Clip Children to Clip Only.

4. This correctly masks the sprite so that it is only visible inside the mask area.

5. Now add a new Polygon2D, called PolygonB, to the scene, move it above PolygonA in the hierarchy. Set it to green and add some points in a rectangle that will encompass PolygonA.

6. You will now see the bug. There is an undesired scaled copy of PolygonB inside the clip area of PolygonA. It also shows any other scene elements inside this clip area, if they are above PolygonA in hierarchy.

7. If you use MMB to pan the editor background, the scene copies move around.

### Minimal reproduction project (MRP)

[PolygonClippingMaskBug.zip](https://github.com/godotengine/godot/files/15010766/PolygonClippingMaskBug.zip)

**Comment by aaronp64** [comment]
Might be related to https://github.com/godotengine/godot/issues/89689

**Comment by grunthos-dev** [comment]
Looks similar since the icons have a squashed ratio like mine. This other bug report also makes a good point. This only happens with the Mobile renderer..
