### ISSUE TITLE
Freelook not deactivatable.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9079]
**Operating system or device - Godot version:**
OS X current master

**Issue description:**

randomly or when right clicking **EDIT** In the viewport! (two finger trackpad click on mac) freelook mode gets started automatically.
I can't deactivate it anymore.

**Comment by Zylann** [comment]
Right click where?

**Comment by toger5** [comment]
in the 3d viewport

**Comment by Zylann** [comment]
I wonder what would cause that, maybe there is a case where it doesn't detects when RMB is released

**Comment by toger5** [comment]
just to be clear: it should use freelook on right click hold?

**Comment by toger5** [comment]
I checkt the os_osx file,
the only difference I could find is here:
	button_mask |= BUTTON_MASK_RIGHT;
	button_mask &= ~BUTTON_MASK_LEFT;


RIGHT
```cpp
- (void)rightMouseDown:(NSEvent *)event {

	button_mask |= BUTTON_MASK_RIGHT;

	Ref<InputEventMouseButton> mb;
	mb.instance();
```
```
- (void)rightMouseUp:(NSEvent *)event {

	button_mask |= BUTTON_MASK_RIGHT;

	Ref<InputEventMouseButton> mb;
	mb.instance();
```

LEFT
```cpp
- (void)mouseUp:(NSEvent *)event {

	button_mask &= ~BUTTON_MASK_LEFT;
	Ref<InputEventMouseButton> mb;
	mb.instance();
```

```cpp
- (void)mouseDown:(NSEvent *)event {

	button_mask |= BUTTON_MASK_LEFT;

	Ref<InputEventMouseButton> mb;
	mb.instance();
```

**Comment by toger5** [comment]
currently compiling... lets see if that is the issue

**Comment by Zylann** [comment]
Yes it should only be active while RMB is held

**Comment by toger5** [comment]
I'm pretty sure the issue is the using the bitwise or instead of the bitwise and...
(Do you want to do the PR? I also can just push that small change. changed it for testing anyways)

**Comment by toger5** [comment]
issue still there...
It is swapped now. So I can move the mouse without looking around when holding right click. when releasing than it is back in freelook mode. when coming form another dock into the 3d viewport I'm also in freelook more immediatly

**Comment by toger5** [comment]
Okay Fail.
turned out that I'm just stupid... that actually was the issue and fixed it. will do a PR.
@Zylann
