### ISSUE TITLE
Project Manager only preserves projects in the projects directory setting

### ISSUE THREAD

**Issue by Spartan322** [godotengine/godot#90824]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]
- Tested but cannot be reproduced in: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.2.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 Series (RADV POLARIS10) () - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I expect that if I import a project or scan project directories, the project manager would remember those projects, not just the ones in the `filesystem/directories/autoscan_project_path` editor setting.

But starting with 4.2.2 the project manager never recalls projects not listed in that path.

### Steps to reproduce

- Start Godot
- Import a project not in the editor path
- Close and restart Godot
- See project is not in list 

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
I don't seem to reproduce the issue on Fedora 39.

I wonder if you were not running Godot 4.2.1 in self-contained mode, which makes it use a different editor settings file than others? There would be a `._sc_` file next to it if so.

**Comment by akien-mga** [comment]
This appears to be a regression from #86271. I think it made a wrong assumption about what to do when using `filesystem/directories/autoscan_project_path`, seems like an easy fix.
