### ISSUE TITLE
"Home" and "End" keys do not work in the editor in MacOS

### ISSUE THREAD

**Issue by pgorley** [godotengine/godot#90826]
### Tested versions

- Reproducible in 3.x/4.x

### System information

Godot v4.2.1.stable.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

The godot editor does not support "Home" and "End" keypresses for macOS.  When pressed, nothing happens.

### Steps to reproduce

Create a new gdscript file. Add some text to a line. 

Press "Home" key.
Expected: cursor moves to the first character in the line
Actual: nothing happens

Move cursor to the first character in the line. Press "End" key.
Expected: cursor moves to the last character in the line
Actual: nothing happens

### Minimal reproduction project (MRP)

[4.2.1_MRP_Home_End_key.zip](https://github.com/godotengine/godot/files/15018746/4.2.1_MRP_Home_End_key.zip)

**Comment by bruvzg** [comment]
Standard shortcuts for this on macOS are Ctrl+A/E and Command+Arrows. You can remap it on the editor settings (`ui_text_caret_line_*` shortcuts).

**Comment by tiloc** [comment]
https://medium.com/@elhayefrat/how-to-fix-the-home-and-end-buttons-for-an-external-keyboard-in-mac-4da773a0d3a2

**Comment by ewrogers** [comment]
It is still a bit strange that the `HOME` and `END` keys have no functionality at all out of the box. Whether it should go to the start/end of the line or the start/end of the script file itself.

THe `PGUP` and PGDN` keys work by scrolling through the script without requiring additional bindings. It is certainly unexpected that `HOME` and `END` do nothing at all.

**Comment by mihe** [comment]
I went ahead and made a pull request to address this. See #94073.
