### ISSUE TITLE
Unable to load jpg format file correctly using load_jpg_from_buffer

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot#90820]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows11 v4.2.1.stable.official [b09f793f5]

### Issue description

![image](https://github.com/godotengine/godot/assets/46812028/8e8496d3-0d1b-474d-a73f-4a2b9928f080)
Unable to load images properly using the load_jpg'from'buffer method,
![image](https://github.com/godotengine/godot/assets/46812028/2494e910-771c-4770-b826-0e7f6528c274)

### Steps to reproduce

no have
I guess it's similar to this question   https://github.com/godotengine/godot/issues/45523

### Minimal reproduction project (MRP)

no have

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/45523, as this is due to the same cause.

**Comment by ModuleCode** [comment]
[min.zip](https://github.com/godotengine/godot/files/15017823/min.zip)
I have selected 2 unsuccessful images and placed them in ZIP. How long will it take to fix this issue

**Comment by Calinou** [comment]
> I have selected 2 unsuccessful images and placed them in ZIP. How long will it take to fix this issue

Thanks :slightly_smiling_face: 

We can't give a date when this will be fixed, as we don't know how difficult it is to resolve the issue. Most contributors are volunteering their time, so we can't give an ETA.
