### ISSUE TITLE
Key input events in Input Map behave strangely after cancelling an edit

### ISSUE THREAD

**Issue by emanresU102396** [godotengine/godot#90833]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4080 Laptop GPU (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

A key input event under an action changes into a keycode event that's incorrectly labeled after canceling an edit and editing it again or editing a different event/action.

![image](https://github.com/godotengine/godot/assets/94582735/4589c4be-d515-46e7-94ef-aa6f71cf1af0)

### Steps to reproduce

1. Add a keyboard input event to an Input Map action in Project Settings. (Any key event is fine, as long as it's one that has a corresponding keycode.)
2. Click the button to edit the event, then click Cancel.
3. Edit the event again (without changing anything) and click OK. (Or edit any other event, or add a new event, or add a new action, or delete an event, or delete an action...)
4. Observe that the event now says "[key] or [key] (Physical) or [key] (Unicode)", and uses a keycode (even if it previously used a physical key or key label).

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Looks like a regression of https://github.com/godotengine/godot/pull/77900

That pr will set the missing keycode, so it changed the origin event.
