### ISSUE TITLE
Autoload scene failing to load when exporting an enum from it in another script. 

### ISSUE THREAD

**Issue by kit-solent** [godotengine/godot#90830]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz (8 Threads)

### Issue description

I am trying to export an enum from my autoload scene in another script but get the error: Could not parse singleton "Core" from "res://core.tscn". 
![image](https://github.com/godotengine/godot/assets/85214318/1e30e220-ad21-44fa-a79f-8dfa9118566d)
Based on the errors shown above it looks like Godot is trying to parse Core.tscn as a script rather than a scene.

### Steps to reproduce

Make an autoload scene with a script attached. 
Ad an enum to the script.
Make another scene with script and try to export the enum from the autoload singleton. 

### Minimal reproduction project (MRP)

[minrep.zip](https://github.com/godotengine/godot/files/15019473/minrep.zip)

**Comment by vnen** [comment]
This is the same as #73109, so I'm closing this one in favor of the older issue. Thanks for the report in any case.
