### ISSUE TITLE
Names of editable children nodes are translated in editor

### ISSUE THREAD

**Issue by rob1gat** [godotengine/godot#90841]
### Tested versions

- Reproducible in v4.3.dev5.official [c9c17d6ca]
- Not Reproducible in 4.2.1 stable

### System information

Godot v4.3.dev5 - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Editable children node names are localized in the editor scenetree : 
![editable_children_names_translated](https://github.com/godotengine/godot/assets/60538144/6750feb9-6eac-47b9-b9b2-2b001098287c)
It does not happen in the scene view : 
![editable_children_names_translated2](https://github.com/godotengine/godot/assets/60538144/ce92ea1c-d842-4baf-a248-3ca138601000)

### Steps to reproduce

* Set language to french (I guess it works with other languages but I've only tested with french).
* Create a scene with children, set their names to words that are translated in your language (for example : target, editor, etc.)
* Add the scene in another scene, make its children editable

### Minimal reproduction project (MRP)

[mrp_editablechildrennamestranslated.zip](https://github.com/godotengine/godot/files/15022527/mrp_editablechildrennamestranslated.zip)

**Comment by akien-mga** [comment]
CC @YeldhamDev @timothyqiu. Might have been fixed already in the `master` branch, needs checking.

**Comment by timothyqiu** [comment]
Yes, the scene tree editor is covered in #89963.

**Comment by akien-mga** [comment]
Fixed by #89963.
