### ISSUE TITLE
Editor settings wiped out when going from latest 4.3.dev to older releases

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#90846]
### Tested versions

4.3[3b1806182a3564736ad64793b203c2c13c251f56]

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

I updated my 4.3 master branch yesterday (previous update was from couple days ago) and after opening the editor all my settings in Editor settings were wiped out.
Shortcuts, anything I had set up (external editor, blender path, everything), editor theme, nothing left the same.
Just to be clear, this project was created in 4.3 (I don't remember when) so it's not a conversion from 4.2 -> 4.3 and it was working just fine just in a couple days old master build.

### Steps to reproduce

1. Create a project in 4.3 master let's say from a week ago.
2. Change editor settings, add shortcuts, change the editor theme, ...
3. Open your project in the 4.3 master updated to 3b1806182a3564736ad64793b203c2c13c251f56.
4. See if the editor settings are still intact.

### Minimal reproduction project (MRP)

N/A - it doesn't seem to be specific to a project in particular, it's related to editor settings.

**Comment by passivestar** [comment]
I noticed the opposite, accidentally opening project in Godot 4.3dev5 after opening it in master wiped all of the editor settings

**Comment by akien-mga** [comment]
Yes it should be like what @passivestar described, and it's expected due to the change of the text resource format after #89186.

We're looking into ways to mitigate this to avoid this kind of annoying errors, but technically it's behaving as expected here.

**Comment by viksl** [comment]
I don't want to talk into this since I don't understand much but the change in the name says going from latest to older but for me it was going from older to latest.

**Comment by akien-mga** [comment]
> I don't want to talk into this since I don't understand much but the change in the name says going from latest to older but for me it was going from older to latest.

Can you reproduce it if you try again with 4.3-dev5 vs latest `master`? The loss of data going from dev5 or earlier to current `master` is very clear and expected, but I don't see any reason to happen the other way around. So I suspect you might have mixed up versions and actually lost data when going from latest to older commits.

**Comment by viksl** [comment]
Yeah, my bad, I just realized before going up I went quickly down disecnting an issue. TY.
