### ISSUE TITLE
Warped UV on Line2D

### ISSUE THREAD

**Issue by francogp** [godotengine/godot#90851]
### Tested versions

Using 4.2.2

### System information

Linux and Windows

### Issue description

If I use a tile texture over a Line2D, it easily warp the UV realted to point count and angles.
![image](https://github.com/godotengine/godot/assets/2739706/2efc7b43-c54b-439a-a643-b6fc931c82e3)

### Steps to reproduce

Create a Line2D with 150 pixels width, create a line with 2 or 3 points, add a tile texture, change the width with a curve to exaggerate the warping

### Minimal reproduction project (MRP)

[Line2DUVBug.zip](https://github.com/godotengine/godot/files/15025310/Line2DUVBug.zip)

**Comment by francogp** [comment]
![image](https://github.com/godotengine/godot/assets/2739706/aecafe83-7cff-484b-877b-a11644eff0c4)
subdividing the line with more points does not fix the issue

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/83306.
