### ISSUE TITLE
FXAA doesn't antialiasing

### ISSUE THREAD

**Issue by 3ttu** [godotengine/godot#90853]
### Tested versions

- Reproducible in Godot 4.x
- Not reproducible in Godot 3.x

### System information

Godot 4.3.dev5; OpenGL3/ANGLE; GPU: Intel HD Graphics 4600

### Issue description

Although the setting is enabled, it doesn't do anything.

### Steps to reproduce

Turn on fast SSAA

### Minimal reproduction project (MRP)

N/A

**Comment by AeioMuch** [comment]
https://docs.godotengine.org/en/stable/tutorials/3d/3d_antialiasing.html#fast-approximate-antialiasing-fxaa

`This is only available in the Clustered Forward and Forward Mobile backends, not the Compatibility backend.`

So it's not a bug.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/69463.
