### ISSUE TITLE
Sugar $ produce syntax error if it contains an expression name

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#9086]
**Operating system or device - Godot version:**
3.0 master Linux

**Steps to reproduce:**
- Create an object named: var, if, continue, onready ...
- Use $ to select said object, example: $buttons/continue
- In this case editor reported error: Expected end of statement (continue)

**Comment by Hinsbart** [comment]
pinging the GDScript wizards, @bojidar-bg @karroffel

**Comment by eon-s** [comment]
You can do $"node name", I think is good to discourage the use of keywords for node names, but give a better error description.

**Comment by bojidar-bg** [comment]
Would be fixed by #8217. Thus, related to #8085.

**Comment by Noshyaar** [comment]
This seems to be fixed.
![image](https://user-images.githubusercontent.com/26753932/28820568-572d91da-76dc-11e7-8b79-4bf2d91058de.png)
