### ISSUE TITLE
2.1 branch release debug, editor crashes

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#9087]
**Operating system or device - Godot version:**
Ubuntu 17.04 x86_64
Godot _**2.1 branch release_debug**_

**Issue description:**
I compiled 2.1 branch with release debug option and the editor crashes randomly, or when I press control-F to search a script or when saving a scene. 

**_On launch terminal prints:_**
_ERROR: move_child: Invalid new child position: 2
   At: scene/main/node.cpp:269.
ERROR: move_child: Invalid new child position: 2
   At: scene/main/node.cpp:269._

It doesn't crash when compiling without target=release_debug

**Steps to reproduce:**
Attach a script and press control - F inside it, or save a scene.

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
Are you using GCC 6 to compile it?

**Comment by santouits** [comment]
Everything is default ubuntu.
version says
**gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406**
and I use this command: **scons platform=x11 target=release_debug -j4**

Maybe I'm doing something wrong?

**Comment by santouits** [comment]
Of course I was. For future reference:

check your version with: gcc --version
if it is 6 something: sudo apt install gcc-5 g++-5
and then compile: scons platform=x11 CC=gcc-5 CXX=g++-5 target=release_debug -j4

closed

**Comment by bojidar-bg** [comment]
Either that or use clang, since we are having some GCC-6 related problems related to getting NULL `this` pointers...

In short, duplicate of #4623
