### ISSUE TITLE
Cannot build Godot for Windows with ANGLE using LLVM MinGW on Debian 13 (VM)

### ISSUE THREAD

**Issue by MBCX** [godotengine/godot#90879]
### Tested versions

- Reproducible in latest master as of [2efbc6bfb3b4f49a6bc75b3d367cfe81eeddbf3a]

### System information

Godot v4.3.dev (68ad520da) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21912.14) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

I cannot get Godot to build with my self-compiled statically linked ANGLE libraries, when it tries to link, it errors with:
```bash
Linking Program bin/godot.windows.editor.x86_64.llvm.exe ...
ld.lld: error: undefined symbol: glad_eglGetProcAddress
>>> referenced by libdrivers.windows.editor.x86_64.llvm.a(gl.windows.editor.x86_64.llvm.o):(.refptr.glad_eglGetProcAddress)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.windows.editor.x86_64.llvm.exe] Error 1
scons: building terminated because of errors.
```
I haven't tested with the pre-compiled ANGLE libraries from [here](https://github.com/godotengine/godot-angle-static/releases/tag/chromium%2F6029), primarily because AFAIK those are compiled with GCC MinGW while I use LLVM MinGW. And I need the `aarch64` ones too.

### Steps to reproduce

1. Clone the godot-angle-static repo.
2. Compile the static libraries using the latest [LLVM MinGW](https://github.com/mstorsjo/llvm-mingw/releases/tag/20240417)
3. Compile Godot `scons platform="windows" use_mingw="yes" use_llvm="yes" angle_libs=<your_compiled_angle_libs>`
4. Wait until it fails to link.

### Minimal reproduction project (MRP)

N/A

**Comment by MBCX** [comment]
So, I was able to successfully compile 4.3.dev5 with ANGLE [89f70e98d], so something was introduce in the latest master that is preventing me to compile with statically linked ANGLE. No idea what could that be though...

**Comment by akien-mga** [comment]
Likely a regression from https://github.com/godotengine/godot/pull/90245.

**Comment by akien-mga** [comment]
I still need to look into why the update introduced this bug, but for now I'm reverting #90245 to fix it.
