### ISSUE TITLE
[4.3] RenderingDevice split caused TextureArray Mipmap rendering artifact

### ISSUE THREAD

**Issue by TokisanGames** [godotengine/godot#90873]
### Tested versions

Bisecting reveals:
* First caused by https://github.com/godotengine/godot/pull/83452
* Improved by https://github.com/godotengine/godot/pull/86855
* Still present in Godot 4.3-dev5
* Not present in Godot 4.2.2

### System information

Windows 11/64, RTX 3070, Vulkan

### Issue description

4.3 introduced a rendering artifact in Terrain3D (the blue). sampler2DArray + Mipmaps causes the problem. Regular sampler, or disabling mipmaps (in import or sampler texture filtering) removes the artifact. Problem PRs found by bisecting.

![image](https://github.com/godotengine/godot/assets/632766/5b8d90a3-b4f6-4f8b-98f6-b30ad36ce473)

Terrain3D uses a sampler2DArray with mipmap filtering to render the terrain. Here it is displaying in 4.2.2 with a flat terrain and a minimal shader.

![image](https://github.com/godotengine/godot/assets/632766/bd3b2f56-5914-4bb7-b3a9-9e10d1de6130)

PR https://github.com/godotengine/godot/pull/83452 caused two rendering artifacts, the green up close and dark far away. Changing UV scale moves the artifacts closer or farther from the camera.

![image](https://github.com/godotengine/godot/assets/632766/59536bd3-6299-490a-a357-c01e72b12a3c)

PR https://github.com/godotengine/godot/pull/86855 improved the artifact by fixing the foreground.

![image](https://github.com/godotengine/godot/assets/632766/8179f731-345c-4dc4-84bd-5d0f040dc472)

* The texture used here is stored in a TextureArray. 
* It is a PNG imported with VRAM Compressed HQ as BPTC. DXT5 RGB also tested. No difference between them.
* With and without mipmaps have been tested. Disabling mipmaps removes the artifact.

* The shader in the three pictures above has been simplified down to this minimal example.
```
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

uniform sampler2DArray _texture_array_albedo : source_color, filter_linear_mipmap_anisotropic, repeat_enable;

void vertex() {
	vec3 v_vertex = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
	UV = round(v_vertex.xz);
}

void fragment() {
	ALBEDO = texture(_texture_array_albedo, vec3(UV*.05, 0.)).rgb;
}
```

* Using this shader, but changing the sampler filtering to linear or nearest without mipmaps removes the artifact, though it's noisy.
* Using this shader, but changing the texture import settings to not generate mipmaps removes the artifact, though it's noisy.

![image](https://github.com/godotengine/godot/assets/632766/caccf891-c72d-4507-9d5c-e0205787ed68)

* Creating a large meshinstance plane 20k x 20k and the same albedo texture file as on the terrain, using the Standard Material and linear filtering with mipmaps does not produce the artifact.
* Using a shadermaterial on the plane with the above shader, with linear filtering w/ mipmaps, but making it a regular Sampler2D instead of a texture array does not produce the artifact.
* Using this sampler2D version of the shader on our terrain meshes does not produce the artifact.

Conclusion, it shows the artifact when using sampler2DArray and textures with mipmaps.

### Steps to reproduce

* Download the release of Terrain3D https://github.com/TokisanGames/Terrain3D/releases/tag/v0.9.1-beta
* Open the demo project in Godot 4.2.2 to see it normally, or 4.3-dev to see the artifact. 
* Restart when prompted, then again after Godot imports to get setup.
* Under `Terrain3D/Material`, enable Shader Override and overwrite it with this minimum shader to see the artifact.
```
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

uniform sampler2DArray _texture_array_albedo : source_color, filter_linear_mipmap_anisotropic, repeat_enable;

void vertex() {
	vec3 v_vertex = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
	UV = round(v_vertex.xz);
}

void fragment() {
	ALBEDO = texture(_texture_array_albedo, vec3(UV*.05, 0.)).rgb;
}
```

* This variation uses sampler2D and does not show the artifact. Attach one of the demo textures to the texture_albedo slot. 
```
shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

uniform sampler2D texture_albedo : source_color, filter_linear_mipmap_anisotropic, repeat_enable;

void vertex() {
	vec3 v_vertex = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
	UV = round(v_vertex.xz);
}

void fragment() {
	ALBEDO = texture(texture_albedo, UV*.05).rgb;
}
```

### Minimal reproduction project (MRP)

See above.

cc: @RandomShaper, @Calinou, @clayjohn

**Comment by clayjohn** [comment]
Taking a look in Renderdoc, I can see that the final mipmap levels of the ArrayTexture are not being filled (2x2 and 1x1) so garbage data is being used. The solution is going to be ensuring that the full mipmap data is transferred to the GPU

**Comment by clayjohn** [comment]
Okay, after some investigation, I have created an MRP for this issue. 

[terrain3dmrp.zip](https://github.com/godotengine/godot/files/15032031/terrain3dmrp.zip)

**Comment by clayjohn** [comment]
Okay, here is a diff that appears to work. Please give this a try. I'm going to double check it in the morning, but I think this should be good:

```
diff --git a/drivers/vulkan/rendering_device_driver_vulkan.cpp b/drivers/vulkan/rendering_device_driver_vulkan.cpp
index 1906d168fe..aeeacafc6e 100644
--- a/drivers/vulkan/rendering_device_driver_vulkan.cpp
+++ b/drivers/vulkan/rendering_device_driver_vulkan.cpp
@@ -1703,7 +1703,7 @@ void RenderingDeviceDriverVulkan::texture_get_copyable_layout(TextureID p_textur
                uint32_t bw = 0, bh = 0;
                get_compressed_image_format_block_dimensions(tex_info->rd_format, bw, bh);
                uint32_t sbw = 0, sbh = 0;
-               r_layout->size = get_image_format_required_size(tex_info->rd_format, w, h, d, 1, &sbw, &sbh);
+               r_layout->size = get_image_format_required_size(tex_info->rd_format, MAX(w, bw), MAX(h, bh), d, 1, &sbw, &sbh);
                r_layout->row_pitch = r_layout->size / ((sbh / bh) * d);
                r_layout->depth_pitch = r_layout->size / d;
                r_layout->layer_pitch = r_layout->size / tex_info->vk_create_info.arrayLayers;
diff --git a/servers/rendering/rendering_device.cpp b/servers/rendering/rendering_device.cpp
:...skipping...
diff --git a/drivers/vulkan/rendering_device_driver_vulkan.cpp b/drivers/vulkan/rendering_device_driver_vulkan.cpp
index 1906d168fe..aeeacafc6e 100644
--- a/drivers/vulkan/rendering_device_driver_vulkan.cpp
+++ b/drivers/vulkan/rendering_device_driver_vulkan.cpp
diff --git a/drivers/vulkan/rendering_device_driver_vulkan.cpp b/drivers/vulkan/rendering_device_driver_vulkan.cpp
index 1906d168fe..aeeacafc6e 100644
--- a/drivers/vulkan/rendering_device_driver_vulkan.cpp
diff --git a/drivers/vulkan/rendering_device_driver_vulkan.cpp b/drivers/vulkan/rendering_device_driver_vulkan.cpp
index 1906d168fe..aeeacafc6e 100644
--- a/drivers/vulkan/rendering_device_driver_vulkan.cpp
+++ b/drivers/vulkan/rendering_device_driver_vulkan.cpp
@@ -1703,7 +1703,7 @@ void RenderingDeviceDriverVulkan::texture_get_copyable_layout(TextureID p_textur
                uint32_t bw = 0, bh = 0;
                get_compressed_image_format_block_dimensions(tex_info->rd_format, bw, bh);
                uint32_t sbw = 0, sbh = 0;
-               r_layout->size = get_image_format_required_size(tex_info->rd_format, w, h, d, 1, &sbw, &sbh);
+               r_layout->size = get_image_format_required_size(tex_info->rd_format, MAX(w, bw), MAX(h, bh), d, 1, &sbw, &sbh);
                r_layout->row_pitch = r_layout->size / ((sbh / bh) * d);
                r_layout->depth_pitch = r_layout->size / d;
                r_layout->layer_pitch = r_layout->size / tex_info->vk_create_info.arrayLayers;
diff --git a/servers/rendering/rendering_device.cpp b/servers/rendering/rendering_device.cpp
index 2b6644e893..855eeabfd5 100644
--- a/servers/rendering/rendering_device.cpp
+++ b/servers/rendering/rendering_device.cpp
@@ -1350,6 +1350,9 @@ Vector<uint8_t> RenderingDevice::texture_get_data(RID p_texture, uint32_t p_laye
                thread_local LocalVector<RDD::BufferTextureCopyRegion> command_buffer_texture_copy_regions_vector;
                command_buffer_texture_copy_regions_vector.clear();
 
+               uint32_t block_w = 0, block_h = 0;
+               get_compressed_image_format_block_dimensions(tex->format, block_w, block_h);
+
                uint32_t w = tex->width;
                uint32_t h = tex->height;
                uint32_t d = tex->depth;
@@ -1365,8 +1368,8 @@ Vector<uint8_t> RenderingDevice::texture_get_data(RID p_texture, uint32_t p_laye
                        copy_region.texture_region_size.z = d;
                        command_buffer_texture_copy_regions_vector.push_back(copy_region);
 
-                       w = MAX(1u, w >> 1);
-                       h = MAX(1u, h >> 1);
+                       w = MAX(block_w, w >> 1);
+                       h = MAX(block_h, h >> 1);
                        d = MAX(1u, d >> 1);
                }
 
@@ -1395,8 +1398,6 @@ Vector<uint8_t> RenderingDevice::texture_get_data(RID p_texture, uint32_t p_laye
                for (uint32_t i = 0; i < tex->mipmaps; i++) {
                        uint32_t width = 0, height = 0, depth = 0;
                        uint32_t tight_mip_size = get_image_format_required_size(tex->format, w, h, d, 1, &width, &height, &depth);
-                       uint32_t block_w = 0, block_h = 0;
-                       get_compressed_image_format_block_dimensions(tex->format, block_w, block_h);
                        uint32_t tight_row_pitch = tight_mip_size / ((height / block_h) * depth);
 
                        // Copy row-by-row to erase padding due to alignments.
@@ -1408,8 +1409,8 @@ Vector<uint8_t> RenderingDevice::texture_get_data(RID p_texture, uint32_t p_laye
                                wp += tight_row_pitch;

```

**Comment by TokisanGames** [comment]
I checked out master and applied these. Though the first one is a really odd diff. I couldn't apply it automatically with patch nor `git apply`. It includes changes across multiple commits, even a duplicate one. I applied it manually.

I see no change to the far dark artifact. I also regenerated the ctex files going to DXT and a new BPTC generation and see no difference.

**Comment by clayjohn** [comment]
Hmmm, maybe something went wrong applying the diffs. Here is a proper patch file with all the changes after rebasing:
[terrain3d.patch.txt](https://github.com/godotengine/godot/files/15042850/terrain3d.patch.txt)

**Comment by TokisanGames** [comment]
This patch applied fine and resolved the artifact, thank you!


btw unrelated but I noticed that on the current master, loading Godot (win/3070) the editor viewport won't render any models until the camera is moved. Wasn't a problem on 4.3dev-5.
