### ISSUE TITLE
C# Exports ignore default values for indirect getters

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#90872]
### Tested versions

Godot v4.3.dev.mono (4728ff30c)

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When an export property has a getter that points to a non-constant value, it defaults to the type's default value. It's understandable why this is difficult to do, but makes tool scripts or plugins difficult to make and use, so this would be a good spot to brainstorm workarounds if a solution can't be proposed.

### Steps to reproduce

Open MRP. Note that the inspector shows the reset button for the `Baz` property, but not `Qux`. When clicking the reset button, it can reset to a possibly invalid value outside the constraints of an export hint.
![image](https://github.com/godotengine/godot/assets/21325943/0577eba4-a3a3-4d0d-8db6-8a5fe9cf83c2)
![image](https://github.com/godotengine/godot/assets/21325943/04cad0a4-aa83-4b31-806b-9da492da5458)

### Minimal reproduction project (MRP)

[defaulttest.zip](https://github.com/godotengine/godot/files/15029360/defaulttest.zip)

**Comment by raulsntos** [comment]
This is expected, the source generator can only figure out the default value for _simple_ properties. See the note in the [_C# exported properties_](https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_exports.html#basic-use) documentation page that was added in https://github.com/godotengine/godot-docs/pull/8859:

> A property's `get` is not actually executed to determine the default value. Instead, Godot analyzes the C# source code. This works fine for most cases, such as the examples on this page. However, some properties are too complex for the analyzer to understand.
>
> For example, the following property attempts to use math to display the default value as `5` in the property editor, but it doesn't work:
>
> ```csharp
> [Export]
> public int NumberWithBackingField
> {
>     get => _number + 3;
>     set => _number = value - 3;
> }
>
> private int _number = 2;
> ```
>
> The analyzer doesn't understand this code and falls back to the default value for `int`, `0`. However, when running the scene or inspecting a node with an attached tool script, `_number` will be `2`, and `NumberWithBackingField` will return `5`. This difference may cause confusing behavior. To avoid this, don't use complex properties.

So in your MRP the default value for `Baz` is determined to be `0`. You can see the generated code adding `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` to your csproj and looking for the `.godot/mono/temp/obj/Debug/generated/Godot.SourceGenerators/DefaultTest.Foo_ScriptPropertyDefVal.generated.cs` file:

```csharp
internal static Dictionary<StringName, Variant> GetGodotPropertyDefaultValues()
{
    var values = new Dictionary<StringName, Variant>();

    int __Baz_default_value = default; // The default value for int is 0.
    values.Add(PropertyName.Baz, Variant.From<int>(__Baz_default_value));

    int __Qux_default_value = 7;
    values.Add(PropertyName.Qux, Variant.From<int>(__Qux_default_value));

    return values;
}
```

**Comment by markdibarry** [comment]
> Why is that difficult?

Sorry, I meant it makes sense why this is difficult to fix, and would be too expensive to do even if we could. The question is: is there a suggested workaround we could suggest in the docs?

My specific use case is for plugins and tool scripts that are meant to provide an interface in the editor to be used by others. In my current project (a fake 2D lighting system), I have a custom node that needs to add another hidden custom node as a child. The user won't see the child and shouldn't interact with it, except through the main node and its export properties. Unfortunately, that means all of the export properties default values misleadingly display as not the default.
![image](https://github.com/godotengine/godot/assets/21325943/904a7eb6-154f-4a8b-afda-02e8a371f993)
If reset, this change can break the node by resetting to values that aren't supported by the export property hint. Or, at best, break it temporarily until you manually set it to a supported value (which the user wouldn't know of).

I've run into this in a few different projects like a dialog system where a nodes often need to expose properties of their children to prevent further complexity for the user. Or, at least, I've run into it enough times over the last few years that it'd be good to have a workaround for since it's not reasonable to support. I've considered making a C++ module instead for these features, but I doubt that's a good suggestion for others. :sweat_smile:

**Comment by raulsntos** [comment]
I see. Would you say explicitly specifying the default value would solve your problem? If so, you can override the `_PropertyCanRevert` and `_PropertyGetRevert` methods.

```csharp
public override bool _PropertyCanRevert(StringName property)
{
    if (property == PropertyName.Baz)
    {
        return true;
    }

    return base._PropertyCanRevert(property);
}

public override Variant _PropertyGetRevert(StringName property)
{
    if (property == PropertyName.Baz)
    {
        return 8;
    }

    return base._PropertyGetRevert(property);
}
```

These methods, along with `_GetPropertyList` and `_ValidateProperty` allow more advanced use cases for exported properties for when the `[Export]` attribute is not enough.

**Comment by markdibarry** [comment]
Oh that works great! I wasn't familiar with these. I think they're pretty self explanatory if we were to link to their definition as part of that note in the docs. I'll make a PR tomorrow.

Thanks for the great insight!
