### ISSUE TITLE
Re-add `Skeleton3D::animate_physical_bones` property and `Skeleton3D::bone_pose_updated` signal

### ISSUE THREAD

**Issue by raulsntos** [godotengine/godot#90880]
### Tested versions

- Reproducible in v4.3.dev.mono.custom_build [2efbc6bfb]

### System information

Pop OS 21.04

### Issue description

As I was looking into the compat break in 4.3 for the migration guide (https://github.com/godotengine/godot-docs/pull/9250) I found these changes in `Skeleton3D` that look like they could be avoided.

The property `animate_physical_bones`:
- It was removed in https://github.com/godotengine/godot/pull/87888.
- The methods `set_animate_physical_bones` and `get_animate_physical_bones` are still available, so they could be used to re-expose the property.

The signal `bone_pose_updated`:
- It was replaced by `skeleton_updated` in https://github.com/godotengine/godot/pull/90575.
- We could re-add the old signal and emit it when `pose_updated` is emitted which seems to be the suggested alternative, so existing user code still works.

### Steps to reproduce

Try to use any of the mentioned members in GDScript or C#.

### Minimal reproduction project (MRP)

N/A

**Comment by TokageItLab** [comment]
bone_pose_updated is quite dangerous and cannot be re-added in the same way as in the past, as it cannot be guaranteed to work in the future. For example, this could be called a lot in the Deffered process, but it could become an obstacle in the future as we support multi-threading, etc. So I think it could be added as an alias for skeleton_updated.

bone_pose_updated is based on the state of Skeleton3D's internal objects (SkeletonSimulator3D), so this cannot be added in the same way as before. I think it is possible to bind it in a state that is not exposed to the editor and is not serialized.

**Comment by raulsntos** [comment]
Sounds good. As long as the methods exist to prevent breaking binary compatibility, and the behavioral changes are kept to a minimum and are well documented I think that's fine.

**Comment by dsnopek** [comment]
> I think it is possible to bind it in a state that is not exposed to the editor and is not serialized.

Yes, this would be `PROPERTY_USAGE_NONE` passed to `PropertyInfo()` when registering the property
