### ISSUE TITLE
ufbx: bake_fps option in importer / FBXDocument api has no effect.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#90888]
### Tested versions

Only in 4.3.dev

### System information

Godot v4.3.dev (2efbc6bfb) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

The ufbx code does not use the `bake_fps` option. This is because the API takes `p_bake_fps` in the `generate_scene` function, but not `append_from_file` where it is needed.

If FBXDocument were a standalone class, we could change the API, but because it inherits from GLTFDocument, we can't change this API.

My recommendation is to add an extra `bake_fps` property in FBXState and assign this in the editor_scene_importer_ufbx. I'm not sure what to do about the `bake_fps` argument to `generate_scene` since it has no effect.

### Steps to reproduce

1. Import an fbx with a 60 fps animation.
2. Select FBX2glTF and set fps to 60.
3. Look at the Animation. it will show extra keyframes: 
![fbx2gltf_60fps](https://github.com/godotengine/godot/assets/39946030/3fe561b9-cb5f-4559-8762-9dc6f98edc92)

5. Select ufbx and set fps to 60.
6. The animation will only have 30 frames per second. The same happens when using a FPS below 30 as well. 
![ufbx_60fps](https://github.com/godotengine/godot/assets/39946030/92eaab82-635b-4f7c-9e50-593f856cb572)

### Minimal reproduction project (MRP)

I do not have any redistributable 60fps FBX file.

**Comment by fire** [comment]
Does https://github.com/godotengine/godot/pull/90894 fix this?

**Comment by lyuma** [comment]
No, this issue has not yet been fixed.

The impact of bake framerate in ufbx is much less than it was on gltf-based importers, because the ufbx importer uses the original keyframes, so bake_fps would only affect the number of additional generated/interpolated keyframes.

That said, it is simple enough to fix that I should do it. Becuase ufbx performs baking prior to the `generate_scene` function, we will solve it by adding an extra property on FBXState, and the EditorSceneImporterUFBX will assign the FBXState,bake_fps property in addition to passing the (unused) bake_fps to append_scene.
