### ISSUE TITLE
Godot chooses a display scale of 1.0 despite I set my my windows to display at 150%

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#90885]
### Tested versions

master

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 () - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

Godot chooses a display scale of 1.0 despite I set my my windows to display at 150%

Sorry for the Chinese here, but you can see I have a 2560 * 1440 monitor and I set my windows to use a 150% display scale

![image](https://github.com/godotengine/godot/assets/8315986/4bf4a042-509d-4abd-b456-a12d8faefed6)

But Godot still thinks 100% is the "Auto" one: 

![image](https://github.com/godotengine/godot/assets/8315986/f3847c9e-fe5e-4a93-a951-11e31e64aed2)

Looking at the code :

https://github.com/godotengine/godot/blob/2543d192c3f74640393f245e48fdf70e241dbe37/editor/editor_settings.cpp#L1522-L1543

My `smallest_dimension` is 1440 and I have a dpi of 144, so it went into the  fallback return : `return 1.0;` 

Not sure if we can add some check to the `else if (smallest_dimension >= 1700)` to something like `else if (smallest_dimension >= 1700 || dpi / 96 >= 1.5)`

### Steps to reproduce

Have the same hardware as mine and observe the auto display scale.

### Minimal reproduction project (MRP)

N/A

**Comment by TeachVoyager** [comment]
Could be the code not correctly identifying the display as high DPI display. 

The condition if (DisplayServer::get_singleton()->screen_get_dpi(screen) >= 192 && smallest_dimension >= 1400) checks for a high DPI display with a certain DPI threshold and screen size. If your display doesn’t meet these criteria, it falls back to the default scale of 1.0.

**Comment by jsjtxietian** [comment]
No offence, but is this a AI generated answer? the tone looks like ai.

**Comment by timothyqiu** [comment]
`DisplayServer` has `screen_get_max_scale()` and `screen_get_scale()` but only implemented on macOS.

I think maybe it's time implement these two methods on Windows with [GetScaleFactorForMonitor](https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor) 😜

**Comment by lostminds** [comment]
Not sure if this bug report is just for the editor, but this proposal might be related for general automatic hiDPI scaling based on system/monitor: https://github.com/godotengine/godot-proposals/issues/7968

**Comment by bruvzg** [comment]
> I think maybe it's time to implement these two methods on Windows with [GetScaleFactorForMonitor](https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor) 😜

Getting and using real scale for monitor will not work without [full DPI scaling support](https://github.com/godotengine/godot/pull/86022)/`SHC_PROCESS_PER_MONITOR_DPI_AWARE` if you have more than one monitor, so implementing `screen_get_scale` without it is pointless, Windows will return false values and rescale it afterwards.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/7968.
