### ISSUE TITLE
OneShot animation in AnimationBlendTree couldn't get back to an original animation when key update mode is discrete

### ISSUE THREAD

**Issue by takanan** [godotengine/godot#90897]
### Tested versions

- 4.2.1.stable and 4.2.2.stable

### System information

Godot v4.2.2.stable - Arch Linux #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 550.67) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

- When OneShot animation ends, it fails to fallback to an original animation

https://github.com/godotengine/godot/assets/1814284/0ef01085-39bd-4c9e-ae4c-a285f3fc1a3d

- This doesn't happen when key update mode is set to continuous

https://github.com/godotengine/godot/assets/1814284/42d87593-a49e-4537-a6f3-6981711a3421

### Steps to reproduce

- create two animations with discrete keyframes
- create AnimationTree with BlendTree root
- create OneShot node and connect two animations
- fire it

### Minimal reproduction project (MRP)

[sample.zip](https://github.com/godotengine/godot/files/15039926/sample.zip)

**Comment by TokageItLab** [comment]
Already fixed in 4.3 by CallbackModeDescrete property.
