### ISSUE TITLE
No tilemap can be created in multiple threads

### ISSUE THREAD

**Issue by VIRTUALXN** [godotengine/godot#90890]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

win

### Issue description

I created a sub-thread in the main thread, created a scene in the sub-thread, and added a new tilemap by the scene. This is not allowed in godot. Although this will be rendered and loaded in the main scene, the console will Continuously reporting errors.
我在主线程创建了一个子线程，在子线程中创建了一个场景，由场景添加 新的tilemap ，这在godot中不被允许，虽然这在主场景中会被渲染和加载，但是控制台会不断报错。

### Steps to reproduce

![`CRI6@YGJNK01ZS4`MD(JCT](https://github.com/godotengine/godot/assets/75050446/420fee40-ff98-46b9-83e2-f6376a69db2b)
![MGF538 X$BDWPD2IPJ@IXG5](https://github.com/godotengine/godot/assets/75050446/880dffbf-0663-4278-949b-575b4ebadd4c)

### Minimal reproduction project (MRP)

[tilemap_test.zip](https://github.com/godotengine/godot/files/15037340/tilemap_test.zip)

**Comment by AThousandShips** [comment]
Please try 4.2.2, this bug should be fixed there

**Comment by VIRTUALXN** [comment]
I have tried using the latest version of godot, and it has no effect. This is the latest error picture.

**Comment by VIRTUALXN** [comment]
I have tried using the latest version of godot, and it has no effect. This is the latest error picture.我已经尝试了使用最新版本的godot ，并且没有效果，这是目前最新的报错图

**Comment by VIRTUALXN** [comment]
> 我尝试使用最新版本的 godot，但没有效果。This is the latest error picture.我已经尝试了使用最新版本的godot ，并且没有效果，这是目前最新的报错图

![%9{P W69E@GSYPMY3%P7X B](https://github.com/godotengine/godot/assets/75050446/09eeca5c-1759-4c1d-afb0-83a03169a760)

**Comment by AThousandShips** [comment]
Oh my bad I couldn't read the error message since it wasn't English, that's something to handle yes, unsure how it should be handled

**Comment by KoBeWi** [comment]
You can use `Thread.set_thread_safety_checks_enabled(false)` (it's unsafe though, so only use it when you know what you are doing).

**Comment by VIRTUALXN** [comment]
> You can use `Thread.set_thread_safety_checks_enabled(false)` (it's unsafe though, so only use it when you know what you are doing).
也就是说，这只是一个警告，并不是报错，我可以正常的使用他，那么我希望这个提示能够修改为警告，而不一个错误等级。
That is to say, this is just a warning, not an error. I can use it normally, so I hope this prompt can be changed to a warning instead of an error level.
