### ISSUE TITLE
Box Emission Shape for GPU and CPU particles is double the size it should be.

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#90891]
### Tested versions

4.2.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7800 XT (Advanced Micro Devices, Inc.; 31.0.24019.1006) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

The box emission shape is twice the expected area.

![image](https://github.com/godotengine/godot/assets/4955051/4459c058-f21c-4308-bbe5-4e89e5b4b93b)
These three all have extends of 1,1,1.

This is easy to fix in the particle processing, but I don't know if we need to wait until a major release  where we are breaking back compat since it will mess up people's existing particle setups.

### Steps to reproduce

Create a particle system and set it to box emission and observe the size of the emission area.

### Minimal reproduction project (MRP)

[particles_box_emission_issue.zip](https://github.com/godotengine/godot/files/15037898/particles_box_emission_issue.zip)

**Comment by Arnklit** [comment]
Ah couldn't find that when I first looked at this because I was unsure if it was on purpose. Thanks @and-rad . We might wanna note it here. https://docs.godotengine.org/en/stable/classes/class_particleprocessmaterial.html#class-particleprocessmaterial-property-emission-box-extents

Found this example explaining it for another engine as well.
![upload_2021-4-3_12-10-24](https://github.com/godotengine/godot/assets/4955051/21cf9663-da13-44aa-873c-67d420aa307d)

**Comment by clayjohn** [comment]
This is sad to see. Before 4.0 we did a pass to try to move everything to "size" instead of "extents" as the difference was confusing a lot of people https://github.com/godotengine/godot/pull/72075

But I guess we missed this one. I think a note in the documentation would be helpful

**Comment by and-rad** [comment]
Did you miss it or did you maybe keep it on purpose because it might have performance implications? I'm just thinking, since it's used in the particles material, storing the information as extents rather than size might make some computations with regards to bounds and overlaps easier?

**Comment by Calinou** [comment]
> This is sad to see. Before 4.0 we did a pass to try to move everything to "size" instead of "extents" as the difference was confusing a lot of people https://github.com/godotengine/godot/pull/72075

We can likely migrate this one without breaking compatibility by adding a new property, deprecating the old one, hiding it from the editor and using `_get()` to assign it to the new property automatifcally.
