### ISSUE TITLE
Creating a rigidbody, setting a mass(Eg. 15) and applying impulse immediately ignores mass

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#90899]
### Tested versions

4.2 stable

### System information

macos air m1

### Issue description

If you create a rigidbody, assign a mass and immediately apply impulse, mass is ignored.

### Steps to reproduce

1. Create a rigidbody
2. Set mass to 15
3. Apply impulse
4. The impulse ignores mass.

If you wait 2 frames after set mass, the impulse is applied correctly.

In the sample below, there is a scene with a script and it exports a checkbox. If you check it, it will wait 0.5s and you should get a different linvel after applying impulse. In one case you have linvel(900,0) in another you have linvel(60,0). The second(after waiting 0.5s) keeps track of mass change, the first one no.

### Minimal reproduction project (MRP)

[bug apply_impulse.zip](https://github.com/godotengine/godot/files/15041541/bug.apply_impulse.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/78866

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by Ughuuu** [comment]
Perfect, will use that. Just wanted to link to something, as in eg. Godot Rapier 2D lib this works as intended, and someone reported it as a bug(since the two behaviours didn't match). Will link other issue(for that person to track).
