### ISSUE TITLE
Windows multiple joysticks support

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#909]
*Bugsquad edit:* Renamed the issue to refer only to point 1) hereafter, since 2) has been fixed in #1359.

I got access to Windows and did some testing with several gamepads. I found these issues.

1) Only one gamepad seems to work at a time, even if you have more than one plugged in at the same time.

2) get_joy_name() always returns the same thing regardless of device, "Microsoft PC-joystick driver". This doesn't match up with what Windows reports (see screenshot).

![gamepads](https://cloud.githubusercontent.com/assets/6351421/5213519/c9c44238-75dc-11e4-9f21-133966b169a4.png)

**Comment by adolson** [comment]
2) appears to be solved by #1359

I'm not sure if 1) is also fixed by this or not? (I use Linux only)

**Comment by adolson** [comment]
I've been told that Windows still only works with one gamepad at a time.

**Comment by UsernameIsAReservedWord** [comment]
Could not test 1) because my PS3 controller is not functional under Windows8.1.

As for 2), the Godot Joystick demo display **"Microsoft PC-joystick driver"** instead of **"Thrustmaster Dual Analog 3.2"**.

**Comment by UsernameIsAReservedWord** [comment]
I've managed to configure a Nintendo Wiimote like if it was a XBOX360 controller thanks to the Touchmote driver (http://touchmote.net/).

So, according to windows, I had 3 game controller (the Thrustmaster, the Wiimote and the fake XBOX360 controller).

The Godot Joystick demo only detected the first one and named it "Microsoft PC-joystick driver".

So according to this test, neither 1) and 2) appear not to be fixed.

**Comment by adolson** [comment]
Does the naming problem go away if you apply pull request #1437 ?

**Comment by UsernameIsAReservedWord** [comment]
yes, the naming problem goes away with PR #1437.

**Comment by UsernameIsAReservedWord** [comment]
As for the "only one gamepad at a time", godot detect only the main controller.

It is possible to change which one is the main controller somewhere into the control panel. and the little dialog that allow that says : "Select the device that will work with ancient programs".

I don't know exactly what they mean by "ancient programs", but maybe Godot uses a joypad API that is being deprecated by microsoft ?

**Comment by Hinsbart** [comment]
Fixed in current master

**Comment by vnen** [comment]
Closing for the reported fix.
