### ISSUE TITLE
Web audio is distorted when using headphones

### ISSUE THREAD

**Issue by kus04e4ek** [godotengine/godot#90906]
### Tested versions

Reproducible: v4.2.dev4.official [549fcce5f], master [9bc49a66bae5e9e506f12df3b3e141c8da13f983]
Not reproducible: v4.1.4.stable.official [fe0e8e557], v4.2.dev3.official [013e8e3af]

### System information

Ubuntu 22.04.4 LTS - Firefox and Chrome

### Issue description

When I connect to bluetooth headphones, I get distorted audio. When using built-in speakers, the audio is correct. Can't reproduce it on other websites.

| 4.2.dev3 | 4.2.dev4 |
|--------|--------|
| <video src="https://github.com/godotengine/godot/assets/118438257/85c28ce8-0a01-4040-96f1-6a38cc454610"> | <video src="https://github.com/godotengine/godot/assets/118438257/03f88bcc-f161-4628-a746-d5eb35d14906"> |

### Steps to reproduce

Connect to bluetooth headphones and play audio on the web export/editor.

### Minimal reproduction project (MRP)

[MRP](https://github.com/godotengine/godot/files/15042856/q.zip)

**Comment by Faless** [comment]
> When I connect to bluetooth headphones, I get distorted audio.

Thank you for reporting this issue, does this only happens if you connect your headphones while the Godot Web instance is already running, or does this also happens if you start the browser (or load the page) after connecting the headphones?

**Comment by kus04e4ek** [comment]
> Does this only happens if you connect your headphones while the Godot Web instance is already running, or does this also happens if you start the browser (or load the page) after connecting the headphones?

Happens either way
