### ISSUE TITLE
iOS sensors have incorrect orientation

### ISSUE THREAD

**Issue by celyk** [godotengine/godot#90901]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

iPadOS 17.4, iPad 9th gen

### Issue description

I'm using SCREEN_SENSOR orientation to automatically rotate my app, and sensor vectors (gravity, accelerometer, magnetometer, gyro) don't maintain their orientation relative to the app. This causes them to point in unpredictable directions. Portrait is the only mode that works properly.

The relevant code is here. According to [this comment](https://github.com/godotengine/godot/issues/8101#issuecomment-288239424), it was meant to correct their coordinate system by a rotation.
https://github.com/godotengine/godot/blob/9bc49a66bae5e9e506f12df3b3e141c8da13f983/platform/ios/godot_view.mm#L452-L477

The 3rd case is wrong and should have been (-x,-y,z) in order to rotate 180 degrees in the xy plane. The other 2 cases may have worked at the time, but not anymore.

### Steps to reproduce

Export the MRP for iOS. The 3D arrow should point down no matter the orientation.

You can also use the official sensors demo: https://github.com/godotengine/godot-demo-projects/tree/master/mobile/sensors

### Minimal reproduction project (MRP)

[down-MRP.zip](https://github.com/godotengine/godot/files/15040909/down-MRP.zip)

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by celyk** [comment]
Some footage of the problem. First, I show that on Android the gravity arrow always points down in real life. At 16 seconds I show what happens on iOS.

https://github.com/godotengine/godot/assets/50609684/13cb33de-b4c3-441c-b890-087037662771

**Comment by bruvzg** [comment]
> The relevant code is here. According to https://github.com/godotengine/godot/issues/8101#issuecomment-288239424, it was meant to correct their coordinate system by a rotation.

I think iPhones and iPads might have different base orientations (or maybe it's different on different models), at least on 10 gen. iPad orientation seems to be flipped (not only sensors but orientation in general).

**Comment by celyk** [comment]
I'm not able to find any sources on that. What appears to be happening is that the sensors are being rotated the wrong way, which is why the combined rotation makes the gravity vector point straight up. 

Tbh I don't think a different base orientation can explain it. Wouldn't that result in all the sensors being rotated 90 degrees in Godot? If your iPad produces different results to mine please say. I also tested on an iPhone 13 Pro and it's the same.

Here's how Apple defines the device coordinate system from https://developer.apple.com/documentation/coremotion/cmmotionmanager
![renderedDark2x-1708363793](https://github.com/godotengine/godot/assets/50609684/b8bef818-f3b9-4a00-bbd3-5e64c65fc65c)

**Comment by bruvzg** [comment]
> I think iPhones and iPads might have different base orientations

Or maybe it's just `UIDeviceOrientation` and `UIInterfaceOrientation` mixed up in some places. I'll test in on different simulators and device.

> Important
> 
> Notice that UIDeviceOrientationLandscapeRight is assigned to UIInterfaceOrientationLandscapeLeft and UIDeviceOrientationLandscapeLeft is assigned to UIInterfaceOrientationLandscapeRight. The reason for this is that rotating the device requires rotating the content in the opposite direction.
