### ISSUE TITLE
Animation Playback tracks don't trigger if keyframe time is at 0

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#90904]
### Tested versions

Reproducible in v4.2.2.rc3.official [16a8334b8] and master [4a01602]

Works fine in v4.2.2.rc2.official [c61a68614]

### System information

Godot v4.3.dev (e330526d2) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

An animation player with an Animation Playback track doesn't trigger the animation if the keyframe is at the very beginning of the timeline (i.e 0 seconds)

If you move the animation clip to say 0.01, it works fine.

### Steps to reproduce

Load the attached project, main.tscn should load up
Click the MainAnimation node, click play in the animation timeline and notice the Godot sprite doesn't move across the screen
Move the animation clip along the timeline slightly so that it's not exactly at 0 seconds and try again, the animation should now work

### Minimal reproduction project (MRP)

[animation_playback_track_bug.zip](https://github.com/godotengine/godot/files/15042154/animation_playback_track_bug.zip)

**Comment by AThousandShips** [comment]
Possibly related:
* https://github.com/godotengine/godot/issues/90864

**Comment by sketchyfun** [comment]
> Possibly related:
> 
> * [AnimationPlaybackTracks no longer functioning as intended #90864](https://github.com/godotengine/godot/issues/90864)

Yeah sorry, that looks like the exact same problem. I did search around, but I didn't search for "AnimationPlaybackTrack" as all one word. Feel free to close it in favour of that one if you like.

**Comment by AThousandShips** [comment]
No worries! It's hard to find some times! Closing this
