### ISSUE TITLE
MultiplayerSynchronizer visibility results in client peer not finding cached object

### ISSUE THREAD

**Issue by graydoubt** [godotengine/godot#90908]
### Tested versions

- Reproducible in v4.2.2.stable.official.15073afe3
- Reproducible in v4.2.2.rc3.official.16a8334b8
- Reproducible in v4.2.2.rc2.official.c61a68614
- Reproducible in v4.2.2.rc1.official.c7fb0645a
- Not reproducible in v4.2.1.stable.official.b09f793f5

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.5176) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

I have a multiplayer setup where characters have limited vision using the MultiplayerSynchronizer's visibility settings.

Characters have two MultiplayerSynchronizers:
- The main "Sync" MS is for the server to sync character properties to clients
- The second "Motion" MS syncs its own properties (`target_position`) from the client to the server, for movement interpolation

![image](https://github.com/godotengine/godot/assets/36222624/023ab143-0b82-4f0f-beb4-4322332003d1)

The "NetworkClientScope2D" and "NetworkScopedObject2D" are Area2D nodes that detect when a character is in range and update the "Sync" MP's visibility for the corresponding peer accordingly.

In Godot 4.2.1, this works as expected.
The Host (on the left) always sees the client.
The client (on the right) only sees the host when they're in range:

![Godot_v4 2 1-stable_win64_2024-04-19_11-31-38](https://github.com/godotengine/godot/assets/36222624/eee3f4cd-4d83-4f88-9672-fe25aea37c59)

In Godot 4.2.2, the visibility setting works once. Upon exiting the visibility range, and re-entering the Area2D, the client can no longer receive updates from the "Motion" MS.

![Godot_v4 2 2-stable_win64_2024-04-19_11-28-20](https://github.com/godotengine/godot/assets/36222624/6f0e04ec-d8c5-4ad4-a4d5-677cd8512220)

Instead, the client will report error messages for each synchronization update:

```
E 0:00:21:0159   get_cached_object: ID 3 not found in cache of peer 1.
  <C++ Error>    Parameter "oid" is null.
  <C++ Source>   modules/multiplayer/scene_cache_interface.cpp:278 @ get_cached_object()
```

and, as a result:

```
E 0:00:21:0167   on_delta_receive: Ignoring delta for non-authority or invalid synchronizer.
  <C++ Error>    Condition "true" is true. Continuing.
  <C++ Source>   modules/multiplayer/scene_replication_interface.cpp:783 @ on_delta_receive()
```

I believe this may be related to [PR 87190](https://github.com/godotengine/godot/pull/87190) ([MP] Handle cleanup of "scene cache" nodes)

### Steps to reproduce

I recommend enabling Visible Collision Shapes from the debug menu

- Launch two instances of the [MRP](https://github.com/graydoubt/422-mp-regression).
- Start one as host, and have the other join as client (The MRP is set up to host and connect to localhost over WebSocket).
- Move the players towards each other (order does not matter) until they're in visibility range.
- Note how both characters correctly sync their positions
- Move the character apart, so they're no longer in visibility range
- Move the characters back together
  - In Godot 4.2.1, this works fine.
  - In Godot 4.2.2 (starting with RC1), the host character can no longer synchronize its position to the client. Instead, the client will report get_cached_object errors.

### Minimal reproduction project (MRP)

https://github.com/graydoubt/422-mp-regression

**Comment by Faless** [comment]
Thanks for the detailed report, I think I understand what is going on, I'll try to get a fix out next week.

**Comment by ntngamedev** [comment]
The same thing happens to me, I'm using 4.2.2.stable.

**Comment by dicarne** [comment]
same error in v4.3 beta2

**Comment by clayjohn** [comment]
> Thanks for the detailed report, I think I understand what is going on, I'll try to get a fix out next week.

@Faless what do you think about this in relation to the release of 4.3? Do you want to fix this before 4.3 releases or should we wait for 4.3.1?

**Comment by mhilbrunner** [comment]
While unfortunate, as this has been ongoing since 4.2.2, I don't think we should block 4.3 release anymore on this at this point. A fix should still be possible in 4.3.1 (and maybe be cherry-picked to 4.2) just the same, unless Fabio disagrees, of course.

**Comment by riazey** [comment]
It's unfortunate that this has been delayed as I've just encountered it while using my load function!
Deleting all my player nodes on a load produces this error, may be related? I am not using a multiplayer spawner.

Can I ignore this error for now or will it cause problems?

![image](https://github.com/user-attachments/assets/2b749224-6cae-4a96-9722-6b8d48e0b294)
![image](https://github.com/user-attachments/assets/6401df59-001f-4871-b2f5-b216d750d114)
![image](https://github.com/user-attachments/assets/773735f5-4ef0-47bf-be80-6a41db04a447)

**Comment by agrimminck** [comment]
I also have this error and don't know how to solve it

**Comment by mhilbrunner** [comment]
@agrimminck This should be "fixed" for now by the revert mentioned in https://github.com/godotengine/godot/pull/94984 (and done in https://github.com/godotengine/godot/commit/3504c98c1233bbd2506e89ce46509bc79afaec17). To see the fix, you'd need to use a build that was done after that commit, so you'd either need to wait for the next Release Candidate or build master yourself to see if the fix works for you.

**Comment by agrimminck** [comment]
okay, thank you! I will waiy for RC2 then

**Comment by Red3Tango** [comment]
In `4.4.1.stable` the behavior of a 2nd client (3rd instance) does not receive updates from "Motion" MS. The visibility is updated accurately, but not the motion. Would this be related, or is it a fault in the way the MRP is written?
