### ISSUE TITLE
How to add Triplanar Sharpness in visualshader 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#90914]
### Tested versions

4.2.1

### System information

Mobile / Android 

### Issue description

How to add Triplanar Sharpness and uv For texture in visualshader I want you to add the Triplanar Sharpness and uv In a list Shader Parameters To control values 

### Steps to reproduce

I want to be added to the list Shader Parameters She added Triplanar Sharpness and Uv And feedstock control 

### Minimal reproduction project (MRP)

I hope I was understood

**Comment by paulloz** [comment]
Hello, this issue tracker is meant to be used for bug reports only. If you have a support questions, use one of the other [community channels](https://godotengine.org/community) instead. Cheers!
