### ISSUE TITLE
Godot 2.1.3 SamplePlayer impossible to remove sound from it

### ISSUE THREAD

**Issue by sam-leo** [godotengine/godot#9091]
**Operating system or device - Godot version:**
Linux XUbuntu 16.04, Godot 2.1.3

**Issue description:**

Godot doesn't remove sound sample when click in the trash icon.

**Steps to reproduce:**
-Create a new project and add a SamplePlayer as subnode
-import sound sample and add to the SamplePlayer
-try to click in trash to remove the sound, it doesn't works

**Link to minimal example project:**

**Comment by HummusSamurai** [comment]
Can confirm this exists on Fedora as well, running the Steam version.

**Comment by bojidar-bg** [comment]
Thanks for the report. That's the same issue as #8486 which was fixed by #8429 (will be in 2.1.4).

(Quoting @akien-mga on https://github.com/godotengine/godot/issues/8678#issuecomment-299690200)
