### ISSUE TITLE
Under Ubuntu, if computer sleeps, can no longer launch project

### ISSUE THREAD

**Issue by TechCowboy** [godotengine/godot#90917]
### Tested versions

Reproducible on ALL versions of Godot 4.x in Ubuntu.  Haven't noticed this issue on Windows

### System information

Godot v4.2.2.stable - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Mobile) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

Godot will no longer launch (play) a project after the desktop locks from inactivity or if you force the desktop to lock (Windows-L)
 

### Steps to reproduce

1) load a project
2) play your project to confirm it runs
3) lock the desktop (Windows-L)
4) log back in
5) You will no longer be able to play your project

Workaround:  Just exit Godot and re-launch

### Minimal reproduction project (MRP)

Create a 2D scene, call it main.tscn, add the following script:
```
extends Node2D

func _ready() -> void:
	print ("Hello, World!")
```

**Comment by AThousandShips** [comment]
Sounds related to:
* https://github.com/godotengine/godot/issues/87394

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87394.
