### ISSUE TITLE
"application/run/disable_stdout" not work runtime

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#90924]
### Tested versions

v4.3.dev5.mono.official [89f70e98d]

### System information

Godot v4.3.dev5.mono - Windows 10.0.17763 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

"application/run/disable_stdout" not work runtime

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/35988767/8e032b80-2247-490b-bcd2-6156cdbd752c)
ADDTION: if disable in ProjectSettings, nothing print.

### Minimal reproduction project (MRP)

[printtest.zip](https://github.com/godotengine/godot/files/15046539/printtest.zip)

**Comment by timothyqiu** [comment]
This is expected behavior. Many project settings are only read when the project starts.

https://github.com/godotengine/godot/blob/4a0160241fd0c1e874e297f6b08676cf0761e5e8/doc/classes/ProjectSettings.xml#L322-L325
