### ISSUE TITLE
VoxelGI: Incorrect reflections after a rebake

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#90956]
### Tested versions

v4.3.dev.custom_build [4a0160241]

### System information

Godot v4.3.dev (4a0160241) - macOS 14.4.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Voxel reflections don't look correct after a rebake. They get fixed after the editor restart though

https://github.com/godotengine/godot/assets/60579014/b4f8cebb-1a55-4f03-9039-bab05d466e6d

### Steps to reproduce

Open the MRP, move the cube and rebake

### Minimal reproduction project (MRP)

[MRP_voxelgi.zip](https://github.com/godotengine/godot/files/15049395/MRP_voxelgi.zip)

**Comment by Calinou** [comment]
I can confirm this on 4.2.1.stable and 4.3.dev b091162a9 (Linux, GeForce RTX 4090 with NVIDIA 550.67).

MRP that can be opened on Godot versions older than 4.3: [MRP_voxelgi_pre_4.3.zip](https://github.com/godotengine/godot/files/15049700/MRP_voxelgi_pre_4.3.zip)
