### ISSUE TITLE
Array of custom Resources with `class_name` is saved using its path and breaks if the script is moved

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#90963]
### Tested versions

4.3 dev 5 and probably earlier, idk if it's a regression

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you have a custom resource with `class_name` and export an array of that resource, the array will be serialized as `Array[Resource("res://path/to/script.gd")]`, completely ignoring `class_name`. When you move the script, the referenced path is not updated and the resource with array can't be loaded anymore.

If script has `class_name`, the array should use class name.
If it doesn't, it should use UID instead (once we have them in scripts).

### Steps to reproduce

1. Open the MRP
2. Open `Resources.tres`
3. It opens
4. Move `ContainedResource.gd` to Folder
5. Restart the project
6. `Resources.tres` no longer opens

### Minimal reproduction project (MRP)

[bugpath.zip](https://github.com/godotengine/godot/files/15049741/bugpath.zip)

**Comment by akien-mga** [comment]
Might be related to recent typed array marshalling changes, cc @dalexeev.

**Comment by dalexeev** [comment]
* Fixed by #85024.

However, you need to save the resource once so that the script path is saved as `ExtResource`.

**Comment by KoBeWi** [comment]
I forgot to test on master, indeed the bug is fixed.

**Comment by moshujsg** [comment]
Is there a workaround for this problem in the meantime?

**Comment by KoBeWi** [comment]
The issue is resolved in 4.3 beta.

**Comment by moshujsg** [comment]
I'm running 4.3 beta2 and still have this issue

**Comment by dalexeev** [comment]
@moshujsg See https://github.com/godotengine/godot/issues/90963#issuecomment-2067927267.
