### ISSUE TITLE
No output when debug port in use

### ISSUE THREAD

**Issue by kewp** [godotengine/godot#9096]
**Operating system or device - Godot version:**

Ubuntu 14.04. Godot 2.1.3

**Issue description:**

No output when running (console).

**Steps to reproduce:**

This seems to happen when something is using the debug port. See reports https://godotengine.org/qa/9453/debugger-and-output-malfunction and https://godotengine.org/qa/630/output-debug-messages-suddenly-stop-working-possible-causes.

No message showing what happened. You just have to know that is the issue (and then change the debug port number in Debug settings).

**Link to minimal example project:**

**Comment by vnen** [comment]
Is it possible to check if the port is already in use? (ping @Faless)

**Comment by Faless** [comment]
Yes, and no, no way to directly know, except trying to bind, if the port is in use binding to the socket will fail.
We can have an error written in the debug console in the editor if the debug server fails to listen, should be an easy fix.
I can make a PR for that.
