### ISSUE TITLE
Contact Monitor does not register contacts as expected

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#9097]
**Operating system or device - Godot version:**
2.1.3 Godot Stable

**Issue description:**

When I hit play and two bodies collide with a RigidBody2D with contact monitoring, and max contacts reported set to 2, it does not register both bodies at the same time.

**Steps to reproduce:**
Download and play project. 
Change to set_max_contacts_reported(3) in order to register both bodies at the same time. 
It is expected to be able to handle 2 collisions when set to 2.

**Link to minimal example project:**
[rigid_body_2d_contact_monitor.zip](https://github.com/godotengine/godot/files/1061134/rigid_body_2d_contact_monitor.zip)

**Comment by eon-s** [comment]
Affects master too, and only 2D bodies, RigidBody (3D) reports the correct number of bodies (at least with 2) on stable and master.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by eon-s** [comment]
Still affects 2.1.5b and master b61021d .

Example ported to Godot 3 format:
[rb2dcontactmonitor.zip](https://github.com/godotengine/godot/files/1877369/rb2dcontactmonitor.zip)

**Comment by eon-s** [comment]
Well, it looks like it works right with a `CircleShape2D` or `CapsuleShape2D`, I wonder if "contacts" are _point_ contacts, while we expect it to be _body_ contacts.

If contacts refer to points, then it needs to be better documented and the methods/signals should report the contact points too.

**Comment by madmiraal** [comment]
As described [here](https://github.com/godotengine/godot/files/1886483/overlappingkinematics.zip):

> This is due to edge collisions (the sides of the colliding rectangle collision shapes are parallel), which report 2 contacts per shape collision: one at each end of the colliding edges. Parallel face collisions in 3D report 4 contacts per shape collision! The important point is: there is a difference between the collisions between shapes and the contacts generated by those collisions. ...

This as not a bug, because there's a difference between contacts and collisions. To ensure that signals from 2 collisions are received, in 2D the number of contacts needs to be set to 4, and in 3D the number of contacts needs to be set to 8. Therefore, removing the bug label and adding the documentation label.
