### ISSUE TITLE
FileSystem shows leaf node as tree root

### ISSUE THREAD

**Issue by kewp** [godotengine/godot#9098]
**Operating system or device - Godot version:**

Ubuntu 14.04. Godot 2.1.3.

**Issue description:**

A leaf node is being registered as the tree root.

The tree in FileSystem is showing twice - in one folder it shows the entire tree again (see 'popup')

http://i.imgur.com/MQ3y3Ui.png

Meanwhile there's nothing in 'popup' besides a script and a scene.

**Steps to reproduce:**

Not sure how to reproduce this.

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
Yet another case of #3662. Closing as duplicate. Hopefully it would get fixed before real (as in not alpha) 3.0 release...
