### ISSUE TITLE
project.godot converted to project.binary on export when `ProjectSettings.editor/export/convert_text_resources_to_binary` is set to false

### ISSUE THREAD

**Issue by ShroudedMuridian** [godotengine/godot#90981]
### Tested versions

- Reproducible in: 4.0-stable, 4.2.1-stable, 4.3-dev5

### System information

Godot v4.2.1 - Windows 10.0.22631 - Vulkan (Mobile)

### Issue description

The documentation for `ProjectSettings.editor/export/convert_text_resources_to_binary` states the following:

> Note: If Editor > Export > Convert Text Resources to Binary is true, @GDScript.load() will not be able to return the converted files in an exported project. Some file paths within the exported PCK will also change, such as project.godot becoming project.binary. If you rely on run-time loading of files present within the PCK, set Editor > Export > Convert Text Resources to Binary to false.

This setting works as expected for all other text-format files; however, project.godot is always converted to project.binary on export, regardless of this setting, which does not match the documentation.

Note that it is still possible to export project.godot to the .pck using Export Filter options during the export process; however, project.binary will always be included, regardless of filters, and takes priority over project.godot during initialization.

### Steps to reproduce

- Create a project
- In Project Settings, turn on Advanced Options
- Under Editor>Export, uncheck the box for "Convert Text Resources to Binary"
- Export the project
- Inspect the exported .pck using debug code or with any available .pck unpacking tool

### Minimal reproduction project (MRP)
For convenience, this project includes a script to print all files in "res://" to the debug console.
[PCK_Test.zip](https://github.com/godotengine/godot/files/15052060/PCK_Test.zip)

**Comment by jsjtxietian** [comment]
Seems like a bug to me:

https://github.com/godotengine/godot/blob/4a0160241fd0c1e874e297f6b08676cf0761e5e8/editor/export/editor_export_platform.cpp#L1406-L1410

**Comment by timothyqiu** [comment]
Project settings is technically not a "resource" :P

**Comment by AThousandShips** [comment]
I'd say it's only an issue because it's mentioned in the docs explicitly, the intention seems to not have been to respect it but always convert it, but wouldn't hurt to make it respect the option as long as the rest of the engine handles it
