### ISSUE TITLE
Help shows wrong location at first use 

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#90982]
### Tested versions

Doesn't work as expected:
- v4.2.2.stable.official [15073afe3]
- v4.3.dev3.official [36e943b6b]
- v4.3.dev5.mono.official [89f70e98d]

Works:
- v4.0.3.stable.official [5222a99f5]

### System information

Godot v4.3.dev5.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 Threads)

### Issue description

When searching for help, the editor view doesn't show the correct location if the help page is not already open. Instead the bottom of the help page is shown.

### Steps to reproduce

1. Make sure help view is not open (or present in script list next to editor view)
2. Press F1 to open "Search Help" window 
3. Type "generate_random_bytes"
4. Click Open button

-> Crypto's help view is opened, but the view is focused to the bottom of the help page.

5. Press F1 again and search "generate_random_bytes" again 

-> Now the view is focused to `generate_random_bytes` function.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been solved:
* https://github.com/godotengine/godot/issues/88281

Though a 4.2 cherry pick would be needed, marked it for cherry picking and closing this
