### ISSUE TITLE
BinaryFormatter can't find type in assembly

### ISSUE THREAD

**Issue by Sahasrara** [godotengine/godot#90997]
### Tested versions

- Reproducible in 4.2.2 Stable

### System information

Windows 11 - Godot 4.2.2 Stable - Forward+ - 4090 RTX

### Issue description

I use BinaryFormatter (shame on me) to serialize data in the editor. At runtime, I try to load up the serialized data and get the following exception:

```
E 0:00:00:0624   System.Reflection.Assembly System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly(): System.Runtime.Serialization.SerializationException: Unable to find assembly 'GameScriptGodot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

My project is called GameScriptGodot, and the type it's trying to load up is called "GameData".

I created a custom SerializationBinder strictly for debugging purposes to find out why this is happening and see that the type it's trying to look up contains the namespace, but if you iterate through the type names in the assembly, they don't contain the namespace. I'm not sure if that's expected or not, but just an observation in case it's helpful.

I don't know C# well enough to understand why this mismatch is happening, but if I run identical code in a non-Godot project, I don't have the issue.

### Steps to reproduce

Serialize a class you've written while running the Godot editor, and then try to deserialize it at runtime.

Here's the class in question:

```
using System;

namespace GameScript
{
    [Serializable]
    public class GameData
    {
        public int test;
    }
}
```

And here's the code I use to deserialize it (note, I'm decompressing it as well):
```
            using (
                FileAccess file = FileAccess.Open(
                    settings.DataFilePathRelative,
                    FileAccess.ModeFlags.Read
                )
            )
            {
                // Compose Response
                byte[] result = file.GetBuffer((long)file.GetLength());
                BinaryFormatter serializer = new() { Binder = new CustomSerializationBinder() };
                using (System.IO.MemoryStream dataStream = new System.IO.MemoryStream(result))
                {
                    using (GZipStream zipStream = new(dataStream, CompressionMode.Decompress))
                    {
                        m_Instance = (GameData)serializer.Deserialize(zipStream);
                    }
                }
            }
```

### Minimal reproduction project (MRP)

I don't have one at the moment, but I'll work on that.

**Comment by raulsntos** [comment]
In Godot we use a custom `AssemblyLoadContext` to load the game assembly, so it's likely that `BinaryFormatter` is not able to find it if it's not in the default one. Try to implement a custom binder that resolves the type manually.

```csharp
class CustomSerializationBinder : SerializationBinder
{
    public override Type BindToType(string assemblyName, string typeName)
    {
        return Type.GetType($"{typeName}, {assemblyName}");
    }
}
```

> if you iterate through the type names in the assembly, they don't contain the namespace.

I'm not sure what you mean by this, opening an assembly in [ILSpy](https://github.com/icsharpcode/AvaloniaILSpy) looks fine to me.

---

Also, keep in mind that `BinaryFormatter` is deprecated and will be removed in .NET 9.0.
- https://github.com/dotnet/announcements/issues/293.

**Comment by Sahasrara** [comment]
> In Godot we use a custom `AssemblyLoadContext` to load the game assembly, so it's likely that `BinaryFormatter` is not able to find it if it's not in the default one. Try to implement a custom binder that resolves the type manually.
> 
> ```cs
> class CustomSerializationBinder : SerializationBinder
> {
>     public override Type BindToType(string assemblyName, string typeName)
>     {
>         return Type.GetType($"{typeName}, {assemblyName}");
>     }
> }
> ```
> 
> > if you iterate through the type names in the assembly, they don't contain the namespace.
> 
> I'm not sure what you mean by this, opening an assembly in [ILSpy](https://github.com/icsharpcode/AvaloniaILSpy) looks fine to me.
> 
> Also, keep in mind that `BinaryFormatter` is deprecated and will be removed in .NET 9.0.
> 
> * [BinaryFormatter is being removed in .NET 9 dotnet/announcements#293](https://github.com/dotnet/announcements/issues/293).

This is actually what I ended up doing, and it does work. So I don't know if this is a bug or not, but I just wanted to mention it in case it is or in case anyone else has the issue.

Here's my binder:
```
    public class CustomSerializationBinder : SerializationBinder
    {
        public override Type BindToType(string assemblyName, string typeName)
        {
            return Assembly.GetExecutingAssembly().GetType(typeName);
        }
    }
```

**Comment by raulsntos** [comment]
This is a bug in `BinaryFormatter` (see https://github.com/dotnet/runtime/issues/42041#issuecomment-690745243) but it's not going to be fixed because it's deprecated, and it will be removed in .NET 9.0 anyway.

**Comment by Sahasrara** [comment]
Oh, I see. Well, I guess it's probably safe to close this ticket. Sorry for the trouble. Hopefully this workaround helps anyone else who runs into the bug.

**Comment by raulsntos** [comment]
Closing as an upstream bug, thanks for reporting nonetheless.
