### ISSUE TITLE
Editor Crashes while Zooming/Rotating 3d Viewer

### ISSUE THREAD

**Issue by FRAG-TOSS** [godotengine/godot#90996]
### Tested versions

Reproducible in version 4.2.2, and in Version 4.1.4.

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 30.0.101.3118) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When I zoom in/out, use the Rotator Thing in the top right (I'm very new to Godot, not sure what it's called), or try moving around a MeshInstance3D, the editor freezes, and has the task has to be ended manually. Sometimes I'm able to Move around/Zoom in/Rotate for a few seconds before it freezes, and sometimes and freezes immediately.

### Steps to reproduce

The issue happens in an empty project, both in 4.2.2 and 4.1.4, so my assumption is that it isn't my code, which is very simple (just a few lines) as this is practically my first day learning to code with the Godot engine.

### Minimal reproduction project (MRP)

Crash happens in an empty Project.

**Comment by huwpascoe** [comment]
> integrated Intel(R) Iris(R) Plus Graphics

That might be the problem. Try using the Compatibility render mode.

**Comment by FRAG-TOSS** [comment]
> > integrated Intel(R) Iris(R) Plus Graphics
> 
> That might be the problem. Try using the Compatibility render mode.

This fixed the issue. Thank you.
