### ISSUE TITLE
Using `multiplayer.disconnect_peer` causes errors with MultiplayerSynchronizer and MultiplayerSpawner

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#91007]
### Tested versions

- Reproducible in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Debian GNU/Linux trixie/sid trixie - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600 (RADV NAVI33) () - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

When one explicitly disconnects a peer from a server using `multiplayer.disconnect_peer(...)`, `MultiplayerSpawner`s and `MultiplayerSychronizer`s will trigger errors in the debug console:

```
E 0:00:10:0993   send_command: Condition "!connected_peers.has(p_to)" is true. Returning: ERR_BUG
  <C++ Source>   modules/multiplayer/scene_multiplayer.cpp:275 @ send_command()
```

In the case of spawners, the error will be triggered once for each previously disconnected peer, each time something is spawned (or unspawned? I've not checked). For synchronizers, the error will be spammed constantly.

Possibly related to https://github.com/godotengine/godot/issues/86814, because with the same project if I just change `multiplayer.disconnect_peer(...)` to `multiplayer.multiplayer_peer.disconnect_peer(...)` I get the error message described in that issue.

### Steps to reproduce

1. Run two or more instances of the attached MRP
2. Click "serve" in one
3. Click "join" in another
4. Click "disconnect someone" on the server instance
5. :eyes: 

### Minimal reproduction project (MRP)

[disconnect_peer-ERR_BUG.zip](https://github.com/godotengine/godot/files/15061638/disconnect_peer-ERR_BUG.zip)

**Comment by dev-bre** [comment]
This is still happening to me. In  particular I am getting: 
```
E 0:00:21:0452   send: Unable to send packet on channel 1, max channels: 0
  <C++ Error>    Condition "p_channel >= peer->channelCount" is true. Returning: -1
  <C++ Source>   modules/enet/enet_packet_peer.cpp:62 @ send()
```
When I disconnect a client from the server calling: 
```
if !multiplayer.is_server():
		multiplayer.multiplayer_peer.disconnect_peer(1)
```
Any idea why?
