### ISSUE TITLE
Godot 4 print output doesn't show up in an exported game on Windows without running through command prompt

### ISSUE THREAD

**Issue by hhyyrylainen** [godotengine/godot#91002]
### Tested versions

- Reproducible in 4.2.2.stable.mono.official.15073afe3
- Not reproducible in 3.5

### System information

Windows 10 and Windows 7, works on Linux (Fedora 39 and Flatpak)

### Issue description

None of messages printed by the game show up in the process output at all (problem is both for stdout and stderr). This is problematic as I want to get some status messages by reading the stdout stream of my game process. Even error prints don't show up at all. 

When running my exported game through command prompt all the game output shows up then, but not if I use another program to start the process and read stdout and stderr. This used to work in Godot 3 perfectly fine (albeit with quite a bit of buffering) but now as I've upgraded my project to Godot 4 this no longer is the case.

Note that all of this works perfectly fine on Linux without issues, the same as it did in Godot 3. Only on Windows it seems Godot 4 behaves differently in this situation. On another computer with Windows 10, I think I saw a few of the engine error prints show up in the output, but none of my `GD.PrintErr` lines showed up. It was on a Windows 7 laptop that I observed no output whatsoever coming through.

### Steps to reproduce

- Have `GD.Print("Stuff");` lines in a game
- Export for Windows
- Run the exported game executable using another program (for example through another c# program using https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo?view=net-8.0) and not command prompt
- Observe how the other process gets no output at all from the game even after the process quits (though my game always crashes on quit due to: https://github.com/godotengine/godot/issues/89941 which may be a factor)

### Minimal reproduction project (MRP)

Unless there's some output disabling settings for Windows, making a MRP should be as easy as taking any blank project and adding  `GD.Print("Stuff");` into it or maybe even `print()` in GDScript (I would assume that the logging function works the same so that the result would be the same).

**Comment by akien-mga** [comment]
CC @bruvzg 

AFAIK this is working as intended _by Microsoft_, and it's not something we can easily support to behave like on Unix.
That's why Windows exports include a `_console.exe` wrapper, which you can use to actually get proper stdout/stderr output.

**Comment by hhyyrylainen** [comment]
I think it should be possible for Godot to check if the stdout and stderr streams are valid even without a command prompt attached. And then just writing to them should get output. Of course that doesn't show up anywhere if there is nothing listening for the input, but in my case I attach streams to the started process from another C# program, so the output should arrive. Even not doing anything and just trying to write to `std::cout` should work just fine on Windows, as long as there isn't any calls done to detach from the current "console" or tweaking the standard stream properties. Godot 3 works just fine, so I suspect that code has been added to Godot 4 to either detach the output streams if a command prompt is not detected (/ allocating a dummy output) or an explicit check to suppress "useless" output.

Way back when I primarily developed on Windows I looked into this, and I remember there being APIs to check if there is an attached command prompt and even an API to open one for even a GUI application after it has been started. So it should be possible to make everything work fine again in Godot 4.

**Comment by bruvzg** [comment]
It should already redirect IO to the parent console, but the issue is Windows console IO is a mess, so it depends on how messages are printed, what terminal is used etc. If you need a fully functional console, you can build the engine with `windows_subsystem=console` flag to make it a proper console app.

**Comment by bruvzg** [comment]
> I want to run Godot sort of like a command line tool. 

That's what `windows_subsystem=console` is for, by default export template is a GUI app without its own console, but it's trying to redirect to the parent process console.

**Comment by hhyyrylainen** [comment]
I am making a game (https://github.com/Revolutionary-Games/Thrive) but I used the command line tool as an example of how I want to process game output text. So it is not a solution for me to use the console subsystem. It would confuse the average player if a console window appeared when they started the game (based on the fact that I've seen even prospective game devs on the Godot subreddit be confused by it).
