### ISSUE TITLE
Pixel perfect font no longer rendering properly in Godot 4.3

### ISSUE THREAD

**Issue by unlessgames** [godotengine/godot#91010]
### Tested versions

Godot v4.3.dev (7529c0bec)

### System information

Linux with X11

### Issue description

Before version 4.3 I was able to use Terminus TTF font in the editor and it would show up nicely. In 4.3 the font looks either blurry or the pixels show up at the wrong spots. Both the Editor Inteface and the built-in code editor is affected.

Below is an image that shows the correct font rendering from 4.2 on the left and the messed up one from 4.3 on the right (with two different antialiasing options). I couldn't make the font look good with any settings.

Make sure you view the image at the exact resolution to properly see the issues.

![godot4 3dev5_font](https://github.com/godotengine/godot/assets/38718816/6fe8c01d-38d3-4047-b5c6-3caa7f2a4abf)

### Steps to reproduce

* Get the [terminus font](https://files.ax86.net/terminus-ttf/)
* Have editor ui scaling at 100% and 1
* Set editor the to use the font as Main Font
* Play with settings to see the issue persist

### Minimal reproduction project (MRP)

The problem is not project specific.

**Comment by bruvzg** [comment]
Might be related to addition of `disable_embedded_bitmaps` property (a lot of fonts seems to have broken embedded bitmaps), which is enabled by default, I guess we should expose it as an editor setting.

**Comment by unlessgames** [comment]
Thank you for the fix, it looks good now! 

Could you share some info about what is broken with embedded bitmaps and how they should be instead? I might forward it to the creator of this font, I am sure they would want to improve it if the issues are clear!

**Comment by bruvzg** [comment]
Bitmaps in the terminus font seems fine. https://github.com/godotengine/godot/issues/89374#issuecomment-1988162916 is an example of broken font (a lot of missing and mixed up characters in the bitmap), I have seen similar issues with some fonts as well, but do not remember exact names.
