### ISSUE TITLE
Amazon In-App Purchase on Godot 4.2.1

### ISSUE THREAD

**Issue by omur-can-altundasar** [godotengine/godot#91029]
### Tested versions

Godot 4.2.1

### System information

Windows 11 - Godot 4.2.1

### Issue description

Hi,
I want to make an in-app purchase for Amazon.
Amazon IAP SDK file : https://developer.amazon.com/docs/in-app-purchasing/iap-get-started.html

But I need codes in GDScript and Amazon's .gdip file to run the plugin. In-app purchase plugin codes for Android and iOS are available in the Godot official documentation, but not for Amazon.
Can you help me?

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment]
Hi, thanks for your interest in Godot. Just a heads up, this space is for reporting bugs only. 

If you need help working with the engine please ask your question on one of the Community Channels (reddit, discord, or the official forum are the best places to ask)
