### ISSUE TITLE
Script editor scrolls back to selected line when resized

### ISSUE THREAD

**Issue by santouits** [godotengine/godot#9103]
**Operating system or device - Godot version:**
Ubuntu 17.04 - Godot 2.1 / 3

**Issue description:**
You have a big script and you click let's say in the second line and then scroll down so you can't see the second line. Then you do something and the script editor is resized, because you expand something like the output or you resize something else and the script editor changes it's size, **the script  editor scrolls back to the position you have clicked**. Wouldn't it be better if it stayed in the same place?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by santouits** [comment]
Yep still happens, though now I made it a habit to click inside the script before resizing anything.

**Comment by KoBeWi** [comment]
Fixed since 3.1
