### ISSUE TITLE
Rigidbodies in linked scenes use linked collision shapes, even if the collision shape is changed in the parent scene

### ISSUE THREAD

**Issue by cart** [godotengine/godot#9105]
**Operating system or device - Godot version:**
Arch Linux - Godot 3.0, sha: d985dd6aedb855b6ea4ffa75756108aa4fee3518

**Issue description:**
In title

**Steps to reproduce:**
1. Create a new scene with a rigidbody and a collision shape under it (SCENE_A)
2. Create another scene (SCENE_B) and add a linked node to SCENE_A
3. Toggle "Editable children" in the linked node in SCENE_B
4. Change the linked node's collision shape to something else
5. Test collision with the linked rigidbody, observe that it uses the original collider from SCENE_A and not the new one defined in SCENE_B

**Link to minimal example project:**
Quick example.  Note that the dropping cube passes through the new, larger platform
[CollisionExample.zip](https://github.com/godotengine/godot/files/1063093/CollisionExample.zip)

**Comment by vnen** [comment]
Seems related to #2314.

**Comment by kubecz3k** [comment]
I think this should be fixed now. Can you recheck?

**Comment by cart** [comment]
Sure thing.  I'll validate when I get home from work

**Comment by cart** [comment]
This is fixed.  In the example linked above, both cubes now hit the first platform, which means the overriding collision shape is used

**Comment by kubecz3k** [comment]
@cart thanks for checking!
