### ISSUE TITLE
Importing .fbx files results in circular dependency errors when trying to instantiate the file in an unsaved scene through the 3D Viewport.

### ISSUE THREAD

**Issue by ByteWiseLogic** [godotengine/godot#91062]
### Tested versions

- Reproduced in 4.3dev5.mono
- Not reproducible in 4.2.stable
- Not reproducible in 4.2.stable.mono

### System information

Godot v4.3.dev5.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.5212) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

I can't drag and drop `.fbx` files into the 3D viewport when editing in a new unsaved scene, due to *Circular Dependencies*. The same issue goes for new scenes that contain the `.fbx` file in the node tree.
I'm supposed to be able to just drag and drop the files into the 3D viewport.

### Steps to reproduce

Make sure to import the provided model using the `ufbx` importer.
1. Drag the provided `FBX` model into the 3D viewport, after which the editor will crash.
2. If you followed step 1. Reopen the editor.
3. Then create a new scene, add any `Node3D` as the root node. But do **not** save the scene yet.
4. Drag any `FBX` into the 3D Viewport. You'll then get an error at the bottom left of the viewport, stating "Can't instantiate: Circular dependency found at SK_Chr_Alien_01.fbx"
5. If you open `MRP.tscn` and drag the `FBX` file into the viewport, you won't run into any issues.

Conclusion: Dragging `FBX` files into the viewport in an unsaved scene, results in a circular dependency error. I have not tested this with other file formats.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/15076967/MRP.zip)
MRP is not needed, however one will still be provided.

**Comment by WorldNulptr** [comment]
It happened to 4.3-dev5 too

**Comment by fire** [comment]
I'm curious if this happens with a gltf file too, I suspect it might be a general issue.

**Comment by fire** [comment]
Need to check if https://github.com/godotengine/godot/pull/92279 fixes this

**Comment by fire** [comment]
Testing on 4.3dev5.mono

1. drag fbx into the empty scene crashes
2. making a new node and dragging into the viewport doesn't crash
3. opening the tscn and dragging into the viewport doesn't crash

**Comment by fire** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/92279
