### ISSUE TITLE
Glow post effect is broken for softlight and screen blend modes (regression from 5567e89)

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#9106]
**Operating system or device - Godot version:**
Windows 10 and Linux Mint

Godot 3.0

**Issue description:**
The glow post effect is giving an incorrect result for screen and softlight blend modes
![glow_bug_comparison](https://user-images.githubusercontent.com/7741669/26965387-e0178280-4d38-11e7-82ac-8db527f1c6d5.jpg)

**Steps to reproduce:**
turn on glow and use screen or softlight

**Link to minimal example project:**
[glow_bug.zip](https://github.com/godotengine/godot/files/1063292/glow_bug.zip)

**Comment by gamergamesz** [comment]
So that is the problem of glow! I thought it was light that was misbehaving!

**Comment by Gibbz** [comment]
same issue here. looks like the shader needs some clamping to preventing it going back into the negatives...

**Comment by Noshyaar** [comment]
Issue first occurs in 5567e89
