### ISSUE TITLE
Path3D tilt handles doesn't account for node transform

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot#91088]
### Tested versions

4.2.1 stable

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 31.0.15.4629) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

If you try to edit a Path3D node when it's in any way translated or rotated from the world origin, the tilt handles become unusable.

### Steps to reproduce

Create a path. Add nodes. Use the tilt handles. See that it works.

Rotate the node, use the tilt handles again. See that they don't match up with the rotation.

Reset the rotation, move the node a few meters away in multiple axis, use the tilt handles. See that they're completely unusable.

### Minimal reproduction project (MRP)

Test project that acts on the same Path3D resource between all the nodes so you can easily compare.
[Path3DTest.zip](https://github.com/godotengine/godot/files/15084459/Path3DTest.zip)

![image](https://github.com/godotengine/godot/assets/1812087/2ae02003-f848-43ab-b200-1b80d0fea66d)

**Comment by kleonc** [comment]
Same in:
- v4.2.2.stable.official [15073afe3],
- v4.3.dev5.official [89f70e98d].
