### ISSUE TITLE
Some Fog parameters don't work

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9108]
**Operating system or device - Godot version:** Linux, 3.0 master

**Issue description:**
Sun color, Sun amount and Depth begin seem to have no effect at all in the fog.
Depth is particularly important because without controlling it, fog looks really bad.

short video showing the (non)effect: https://www.youtube.com/watch?v=QpmcDr1TpYk

**Comment by reduz** [comment]
sun color needs a directional light to work
depth works, but you have to understand that your far plane actually
changes how fog looks, so adjust it in the view -> settings menu to match
the rest of your scene

**Comment by nunodonato** [comment]
I have a directional light :)

about depth.. its not the "far" that is the problem, but the begin. My Z-near is 0.1 (as it should), but fog depth_begin doesnt seem to make the fog start away from the camera

**Comment by gamergamesz** [comment]
Only mesh is getting coloured from the fog, i mean there is no depth to the fog

**Comment by gamergamesz** [comment]
The object far from the camera should become hard to see but they are all the same

**Comment by Zylann** [comment]
I also didn't manage to make the fog behave like the old "typical" one that was based on distance, like, having a setting to make it less opaque nearby, and more opaque in the distance.

![image](https://user-images.githubusercontent.com/1311555/27016017-dfb28540-4f1a-11e7-84f8-ae513ba24741.png)

Not sure what the height curve does, but it seems to make fog appear "above" the ground one, with less density between the two (more noticeable when tweaking the setting)

Also "height enabled" doesn't seem to do anything, the "localized height" of the fog seem to be always active.

**Comment by reduz** [comment]
Fog is working fine, tested height, depth and sun.
![image](https://user-images.githubusercontent.com/6265307/29008718-06885142-7af2-11e7-99b9-370c31207afb.png)
The depth problem reported by @Zylann is right though, will fix asap

**Comment by Zylann** [comment]
Also... are you sure the height fog is affected by depth? (not the depth fog, just the height fog on its own)
Like, it seems to me that an object seen at 1 meter away and another at 100 meters away have the same fog opacity when inside the height fog. Is there a way to give depth to the height fog?

Here exaggerated to show the issue:
![image](https://user-images.githubusercontent.com/1311555/29009899-7d53ff30-7b27-11e7-99a6-3aa2bbd3e593.png)

**Comment by reduz** [comment]
Yes, that's the idea of height fog. It's independent from depth

**Comment by Zylann** [comment]
On its own, it doesn't look realistic though... it would require adding depth fog on top of it, but there will always be some fog that you can't get rid of at any distance then.
