### ISSUE TITLE
Manually Specifying SSL Certificates

### ISSUE THREAD

**Issue by novawerkz** [godotengine/godot#9110]
**Operating system or device - Godot version:**

All platforms - 2.1.3-stable

**Issue description:**

Unless I am mistaken, it seems that all SSL certificates are loaded from a header file that is auto-generated by the build process. This prevents the use of self-signed certificates, which are extremely useful for testing or when using a CA is undesirable. A quick fix would be to bind "StreamPeerSSL::load_certs_from_memory", although a better solution might be to permit specifying a certificates file in the configuration file.

**Comment by vnen** [comment]
I think you can add certificates in the SSL section of Project Settings.

**Comment by novawerkz** [comment]
Right you are, there does appear to be an option. I couldn't find any code connecting it with StreamPeerSSL, but that is probably just an oversight on my part. I'll close this issue for now until I can test it.

**Comment by vnen** [comment]
This option is used in `StreamPeerOpenSSL`: https://github.com/godotengine/godot/blob/2.1/modules/openssl/stream_peer_openssl.cpp#L562

**Comment by novawerkz** [comment]
@vnen I see I wasn't looking at the concrete implementation. It's been a while since I've looked at Godot's code and evidently I've forgotten how it fits together. Thanks for clearing that up :)
