### ISSUE TITLE
Signal callback is not being added into the script when using external editor

### ISSUE THREAD

**Issue by azuloo** [godotengine/godot#91101]
### Tested versions

- Reproducible in: 4.2.1-stable, 4.2.2-stable, 4-3-dev5

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (Intel Corporation; 31.0.101.2115) - Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 Threads)

### Issue description

Using the external editor (e.g. VSCode), if you try to connect to some Node's signal while the editor is **closed** initially -- no code is generated for the selected signal and you get the following error: `modules/gdscript/language_server/gdscript_language_protocol.cpp:312 - Condition "!clients.has(p_client_id)" is true.` . If the editor is opened -- this issue is not reproducing.

### Steps to reproduce

1. Create a project with a Node. Attach a script to the Node.
2. In "Editor Settings" select "Use External Editor" and write down its path in "Exec Path".
3. Make sure your editor is closed.
4. Select a Node. In the "Node" tab choose any signal you wish to connect to and press "Connect".
5. Observe the error in the "Output": `modules/gdscript/language_server/gdscript_language_protocol.cpp:312 - Condition "!clients.has(p_client_id)" is true.` and that no signal callback has been generated in the Node's script.

### Minimal reproduction project (MRP)

N/A

**Comment by paulloz** [comment]
Hello, and thank you for the report. I'm consolidating this in #41283, since this is the same issue.
