### ISSUE TITLE
GridMap does not work

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9111]
**Operating system or device - Godot version:**
Windows 10 - master (b21e68c)

**Issue description:**
The GridMap node does not show any tile. It also does not have the grid in the viewport as it shows on 2.1.

![godot windows opt tools 64 3 0_2017-06-09_22-20-43](https://user-images.githubusercontent.com/5599796/26998901-5b8f487a-4d62-11e7-9f84-46d00c12bf0c.png)

**Comment by Zylann** [comment]
Last time I lurked in GridMap editor plugin I also noticed some functions names were not updated to 3.0 names

**Comment by ARJayDEV** [comment]
I think this may be related to converting a scene to a meshlibrary - When I try this the meshlibrary that gets output is a 1kb file that only contains

`[gd_resource type="MeshLibrary" format=2]

[resource]

`

**Comment by vnen** [comment]
@ARJayDEV  You're right, now that I looked at it, the MeshLibrary exporter is commented out. https://github.com/godotengine/godot/blob/51442988b19d28be551c6ace75c57b50856ed2ad/editor/plugins/cube_grid_theme_editor_plugin.cpp

**Comment by HummusSamurai** [comment]
Seems to be working now.

**Comment by kubecz3k** [comment]
Think it's fixed by https://github.com/godotengine/godot/commit/cb0e357d0b8565fcba6f2cf0ec5ea8e795e3fc2a
