### ISSUE TITLE
Unable to make tiles with this tileset

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#91125]
### Tested versions

- Reproducible in 4.3 dev 5, and 4.2.2

### System information

Windows 10 with the versions mentioned above; dual GPU

### Issue description

Trying to add this image as a tileset atlas causes the following behaviours:

- You're prompted to auto-make tiles. If you click yes, nothing happens.
- You cannot manually create tiles, either.

### Steps to reproduce

Use this image, and add it to a tileset of any tile size.

![tiles](https://github.com/godotengine/godot/assets/31222662/9935b3f1-cfd6-49b6-b5af-51f3f9cabf23)

You can work around the image by tinting the tiles red. This image works fine:

![tiles(1)](https://github.com/godotengine/godot/assets/31222662/15558384-2e29-4173-b304-adbf2ff89ee2)

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @groud @KoBeWi

**Comment by groud** [comment]
Works for me. I've just set up the TileSet to 24x24 and it works out of the box.
[Kooha-2024-04-25-10-07-01.webm](https://github.com/godotengine/godot/assets/6093119/a71a71de-059a-4127-9294-93cb9e9974ea)

**Comment by nightblade9** [comment]
Bummer, it works for me, too (on a new project). Sorry, I guess there's something messed up about my current project.

Even worse (better?) it's now working on my original project and scene now. Very odd.

Sorry for the noise.
