### ISSUE TITLE
`NavigationRegion2D` only respects the first layer of a tilemap when baking source geometry

### ISSUE THREAD

**Issue by cixil** [godotengine/godot#91131]
### Tested versions

Reproducible in 4.2.stable

### System information

Godot v4.2.stable - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

### Issue description

When baking a navigation polygon mesh, a `NavigationRegion2D` should scan its children recursively (or nodes of a group depending on the `source_geometry_mode`) for collision shapes and bake the mesh around them. This should also work for collision shapes that are a part of tiles in tilemaps.

It does work if the tilemap only has one layer, but if it has multiple, only the first layer is respected.

---

![image](https://github.com/godotengine/godot/assets/22418985/d74f9659-4293-4f09-bfc1-34a5b7143545)

In the above image, the lower left square should also be drawn around when the navigation polygon is baked, but it is not because it is on layer 1 of the tilemap.

Note this does not work for any of the source geometry modes.

### Steps to reproduce

1. Create a new 2D scene
2. Add a `NavigationRegion2D`
3. Add a `TileMap` node as a child of the NavigationRegion
4. Set up the tilemap and tileset:
  - Create new tileset
  - Add a physics layer to the tileset
  - Add a layer to the tilemap
  - Drag and drop the godot icon from the FileSystem to create a new atlas for the tileset. Create a single tile and paint a collision shape on it.
5. Now go to the tilemap pane, add some tiles on layer 0 and some on layer 1
6. Click on the NavigationRegion2D Node.
7. Click "New NavigationPolygon"
8. Draw a region around the tiles you placed
9. Click "Bake NavigationPolygon"

### Minimal reproduction project (MRP)

N/A (wouldn't let me upload sorry)

**Comment by smix8** [comment]
PR https://github.com/godotengine/godot/pull/85856 changed the parsing to all layers and should be part of the next 4.3dev release.

**Comment by smix8** [comment]
Closing considering that the PR that changed the parsing was already merged.
