### ISSUE TITLE
BoneAttachment3D nodes generated from blend file are assigned to their own new distinct bone rather than bones defined on the skeleton originally.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#91132]
### Tested versions

v4.2.rc.custom_build [d34f1ec4b]

### System information

Windows 10 - v4.2.rc.custom_build [d34f1ec4b]

### Issue description

When importing my .blend file, I noticed that the meshes which are parented to a single bone create their own BoneAttachment3D node for the mesh (named after the attached mesh), which is fine. What isn't fine though is that this BoneAttachment3D node is not assigned to the actual bone it was originally assigned to within blender.

Instead the BoneAttachment3D is assigned to an additional bone that has been added to the skeleton that is named after the attached mesh.
So my "helmet_mesh" meshinstance has its own "helmet_mesh" bone instead of being attached to the "head" bone.

Aside from being annoying, and adding bloat to the skeleton, this makes the helmet mesh non-transferrable between skeletons with the same bone names without additional code to reparent the helmet back to the head bone.

---
### Questions

- Is this a bug or intentional?
- If it is a bug has this already been addressed at some point?
- Can someone else confirm this behavior? (ty)

### Steps to reproduce

- Within Blender create an armature with a single bone
- create a cube 
- parent that cube to the bone 
    - select cube
    - shift select armature
    - switch to pose mode
    - select bone Ctrl+P > bone
- save file
- drag it into Godot
- create a new scene
- instantiate child scene (blend file) within the new scene
- right click the instanced blend file scene and make it local

Observe that there is now an extra bone within the Skeleton3D node and that the cube's BoneAttachement3D node is assigned to it.

### Minimal reproduction project (MRP)

I'll put more effort into this and update to a stable version for further testing if I can confirm this is a bug.

**Comment by smix8** [comment]
Same as https://github.com/godotengine/godot/issues/75917

As stated in my original issue I still think adding extra bones to "fix" bone index bugs caused by Godots own internals is super sloppy and was the wrong decisions.

If a model has a lot of bone attachments it end up with an exessive amout of unexpected bones that no one intended or needs except the Godot internals.

**Comment by KnightNine** [comment]
@smix8 
So they worked around the bugs instead of fixing it 💀
Wait, why is there no "remove_bone()" function in Skeleton3D for me to correct this programmatically?!?
oh noooooooooooo......

**Comment by KnightNine** [comment]
In terms of looking for a way to remove these extra bones:
- Option 1: I can clear_bones(), can I store a list of all bones (and their transforms) I want kept and re-add them? 
But  will they still be animated after I do this?
- Option 2: I could create a blender file without all the bone attachments and then programmatically assign the BoneAttachment3D nodes from my original file to the duplicate one (though I'd have to keep 2 .blend files in sync with each other manually)

**Comment by TokageItLab** [comment]
Dupliicate of https://github.com/godotengine/godot/issues/75917

I expect that some of the issues that were the original reason for adding this behavior has already removed, so we may need to consider whether we can properly remove the erroneous hack that causes this bone to be duplicated.
