### ISSUE TITLE
Autoload script ignore metadata 

### ISSUE THREAD

**Issue by StanleySweet** [godotengine/godot#91139]
### Tested versions

4.3 dev 5

### System information

Windows 11 - Godot v4.3. Dev5 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia, 2215886848) -Intel Core i7-8750H @ 2.20GHz, 2.21 GHz 12 threads

### Issue description

Like all `RefCounted` objects Scripts expose metadata properties that could be used to set some things at run time like for instance sounds. However in the case of Autoloaded scripts it seems these metadata are unavailable.

```
E 0:00:01:0162   AutoloadedScript.gd:4 @ _ready(): The object does not have any 'meta' values with the key 'MissingField'.
  <C++ Error>    Method/function failed. Returning: Variant()
  <C++ Source>   core/object/object.cpp:1041 @ get_meta()
  <Stack Trace>  AutoloadedScript.gd:4 @ _ready()
```

### Steps to reproduce

Load the MRP and launch the project. Notice there is now an error about metadata not being found.

### Minimal reproduction project (MRP)

[meta-bug-repro.zip](https://github.com/godotengine/godot/files/15106860/meta-bug-repro.zip)

**Comment by timothyqiu** [comment]
Not only Autoloads, but all script resources can't save metadata. See #84653.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/84653

As this is related to all metadata for scripts
