### ISSUE TITLE
Cannot change camera fov from code

### ISSUE THREAD

**Issue by j36e** [godotengine/godot#91146]
### Tested versions

- Reproducible in Godot v4.2.2.stable and Godot v4.2.1 stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

This code will only print 75. The camera FOV does not change. It can be manually adjusted by clicking on the node but no code seem to be able to do it.

```gdscript
extends Camera3D

func _process(_delta: float) -> void:
	fov = 180.0
	print(fov)

	set_fov(180.0)
	print(fov)
```
Here is the scene I am testing this on:

![image](https://github.com/godotengine/godot/assets/147976004/6b9e1d9f-18de-44eb-a0ee-5e7cac3ac45d)

Just a box and a camera

![image](https://github.com/godotengine/godot/assets/147976004/72fa9039-1417-491d-b3e8-530c5da900cc)
![image](https://github.com/godotengine/godot/assets/147976004/829d9ffa-d1a4-42ff-a7cf-e042e8824286)

### Steps to reproduce

- Add a camera to a scene
- Try to set its FOV value in code

### Minimal reproduction project (MRP)

[test.zip](https://github.com/godotengine/godot/files/15108072/test.zip)

**Comment by AThousandShips** [comment]
You're showing screenshots from the editor, does that mean that the issue you're reporting that it won't work while in the editor, and not when running the scene?

If that's the case you need to add `@tool` to your code, see [here](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html)

**Comment by patwork** [comment]
It's all about the available FOV range. The function only accepts values 1..179, so 180 is ignored.

**Comment by j36e** [comment]
Woops @patwork is right, thanks a lot guys and sorry for the bad issue
Have a nice day
