### ISSUE TITLE
Possible Memory leak of unsigned char between PoolVector; ImageLoaderPNG, Ref<Texture> Editor_Icons::make_icon and default_theme.cpp

### ISSUE THREAD

**Issue by HumanSheeple** [godotengine/godot#9114]
**Operating system or device - Godot version:**
Arch linux Godot 3.0 alpha

**Issue description:**

I was working on my terrain module and it crashed at random points, I did some debugging and found an index was 0 I went through my code and couldn't find the leak. I used valgrind, a powerful memory leak tool and ran it in -v (verbose) mode and it looks as though the leak isn't even in my own code. There appears to be some leak somewhere in themes, editor_icons, or the Ref<Image> . Either way the leak in godot is stopping me from developing the terrain module. Can you please have a look at my valgrind log and see what you can do about it?

Here's my valgrind log: https://paste.ee/p/s5NRN

There seems to be not just one or two, but literally thousands of leaks almost all of them to do with icons and themes.

Thank you in advance.

**Steps to reproduce:**
1. Download the buggy alpha copy of terrain editor module: https://github.com/HumanSheeple/godot_heightmap_module
2. copy all the files to modules/hterrain
3. compile in qtcreator/scons for your appropriate OS
4. boot up godot
5. add new node, 3d spatial "heightmap"
6. rotate the camera around so you can see the terrain.
7. adjust the brush bars so you have a big brush and don't set the opacity too high
8. add some terrain, subtract some terrain, smooth some terrain, just generally mess about with it
9. at some random point it will crash the times are not consistent.

***UPDATE***:
I have done another valgrind -v --trace-children=yes --track-origins=yes --leak-check=full with NO TERRAIN module included using today Saturday 10 June 2017 build and valgrind appears to have found the same errors all but one, last nights test showed 954 blocks lost today only 953.
Here is a paste of the latest valgrind, again showing leaks with icons and themes: 
https://paste.ee/p/SrhdY
I hope this confirms this is definately not my code at fault!

***UPDATE 2***
14/06/17 https://paste.ee/p/6j4W6#a4Dm4cApVqpuU0tHiy8DPtmAKcbl6wwc I modified memory.h to output what cpp/h file was being called when a mem alloc and a mem free was done I also included the size of the memory allocations frees

***UPDATE 3***
15/06/17
We have isolated the leak to the resizing of PoolVector's

**Link to minimal example project:**
PoolVector<Vector3> pv;
            pv.push_back(Vector3());

**Comment by Zylann** [comment]
Related to #8225

**Comment by HumanSheeple** [comment]
Zylann fixed the leak: Hurray! https://github.com/godotengine/godot/pull/9204#pullrequestreview-44454740
