### ISSUE TITLE
Black screen in 3D scene after new install

### ISSUE THREAD

**Issue by CptAdventure** [godotengine/godot#91165]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Windows	10.0.19045 Build 19045         NVIDIA GeForce GTX 960M

### Issue description

Downloaded and ran GODOT. Console opened and new project (Forward+) created.
GUI opened 3D scene which was total black. Switching to scene to 2D displays 2D correctly. 3D scene remains total black.

### Steps to reproduce

Deleted project and attempted creation two more times with same result (black 3D scene).

### Minimal reproduction project (MRP)

[test2.zip](https://github.com/godotengine/godot/files/15112803/test2.zip)

**Comment by clayjohn** [comment]
In the output panel at the bottom, do you see any errors printed?

**Comment by brcontainer** [comment]
Your video driver is probably out of date or has a related problem in your operating system. Does the problem occur in Godot4.3 or 4.1?

https://godotengine.org/download/archive/#4.3
https://godotengine.org/download/archive/#4.1.4

**Comment by CptAdventure** [comment]
![2024-04-29_10-21-47](https://github.com/godotengine/godot/assets/62085604/4003b962-aa76-466a-b698-e9a0815e2661)

Output window as requested.

**Comment by brcontainer** [comment]
> ![2024-04-29_10-21-47](https://private-user-images.githubusercontent.com/62085604/326525312-4003b962-aa76-466a-b698-e9a0815e2661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTIxMTUsIm5iZiI6MTcxNDQxMTgxNSwicGF0aCI6Ii82MjA4NTYwNC8zMjY1MjUzMTItNDAwM2I5NjItYWE3Ni00NjZhLWI2OTgtZTlhMDgxNWUyNjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE3MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGMyZjA5NWM4MDBhODYwOTg4Mzg3NGE0MDkzZTJiMzkzMjhhZmUwMmExZDgzYTAyZTY2MGMyYWUyMTJiNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kc7RzebPWaodXLVSfTCW3tIM551XkkKWyRKvcw8LHc8)
> 
> Output window as requested.

The message is just a warning about the additional (optional) tool for importing Blender files.

---

1. Have you tried updating your video driver via the NVidia website?
2. Have you tested Godot4.1.4?
3. Have you tested Godot4.3-dev?
4. Have you tried switching from Forward to Compatibility?

I hope this helps 👍

**Comment by CptAdventure** [comment]
1. Godot 4.1.3 tested.......same problem
2. Video drivers updated.......
                                    Problem resolved!
