### ISSUE TITLE
Windows godot window not working correctly

### ISSUE THREAD

**Issue by drakenshot23** [godotengine/godot#9116]
**Operating system or device - Godot version:**
Windows 10 Godot 2.1.3

**Issue description:**

I can't click the exit resize and minimize buttons of godot editor. I have to go and select godot in the bottom bar of windows then it works back.

**Steps to reproduce:**
To reproduce it you have to click inside the script after that the exit resize and minimize buttons don't work.

**Comment by vnen** [comment]
I have no idea how to reproduce this. One thing I notice is that a `tool` script can call `OS.set_window_resizable(false)` which will disable the resizability of the editor. Is there anything like that in your code?

**Comment by Zylann** [comment]
I encountered this a few times too this year, but never found a repro. It's quite rare.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
Pretty sure this was fixed by #15905 (and #15908 for 2.1). I'm closing in advance, comment if it's not case.
