### ISSUE TITLE
Not adding the signal method in C# script in visual studio 2022 editor 

### ISSUE THREAD

**Issue by Arman-Espiar** [godotengine/godot#91173]
### Tested versions

v4.2.2.stable.mono.offitial[15073afe3]

### System information

windows 10 - visual studio 2022 - godot v4.2.2 mono

### Issue description

I proceed according to [this tutorial](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html). When I add the pressed() signal to sprite2d, no method or code is added to the script. 
### Steps to reproduce

step by step with [this tutorial](https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html)

### Minimal reproduction project (MRP)

; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="Godo Mono Game"
run/main_scene="res://node_2d.tscn"
config/features=PackedStringArray("4.2", "C#", "Forward Plus")
config/icon="res://icon.svg"

[dotnet]

project/assembly_name="Godo Mono Game"

**Comment by Arman-Espiar** [comment]
Also, connecting the signal through the code also encounters the following error:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Comment by paulloz** [comment]
Hello, and thank you for the report. I'm consolidating this in #41283, since this is the same issue.
For C# specifically: this generation never worked reliably, so it was recently removed for 4.3. The editor's UI shows a message saying the code won't be generated.
