### ISSUE TITLE
3D mesh gets abnormal trembling on android devices powered by MediaTek Dimensity and Huawei Kirin processors.

### ISSUE THREAD

**Issue by dsyze** [godotengine/godot#91170]
### Tested versions

4.2.1 stable

### System information

android - godot4.2.1 - gles (MediaTek Dimensity and Huawei Kirin processors)

### Issue description

I have an Android application exported using Godot, which employs OpenGL (compatibility) rendering. The app runs smoothly on devices equipped with Qualcomm processors. However, issues arise when running on devices powered by MediaTek Dimensity and Huawei Kirin processors specifically concerning animations involving mesh binding to 3D skeletons. As demonstrated in the video below, during playback, the mesh models exhibit abnormal trembling when they should be smoothly animating along with their bound 3D skeletons. For comparison, you can observe the correct, jitter-free animation on a device with a Qualcomm processor.

Switching to Vulkan (mobile) rendering resolves the problem on MediaTek Dimensity-based devices, resulting in normal operation. Unfortunately, adopting Vulkan (mobile) causes the application to crash outright and become unrunnable on Huawei Kirin processor-equipped devices.

### Steps to reproduce

1, Make mesh and animations by binding skeleton3D in blender3.6.
2, open the blend file in godot4.2.1 and save the mesh and skeleton3D animation using node Animationplayer.
3, before output to android, close the shader cache to avoid another bug on shder cache on  some android hardwares.
4, switch the renderer(mobile) to gl_compatibility,
5, build the android apk file and run in MediaTek Dimensity devices.
6, play the Animationplayer and the abnormal trembling shows.

### Minimal reproduction project (MRP)

[bugReportProject.zip](https://github.com/godotengine/godot/files/15113389/bugReportProject.zip)

https://github.com/godotengine/godot/assets/59926550/687220a8-a500-4a4e-99df-5416079aa8d7

**Comment by Calinou** [comment]
This is likely a precision issue in the mesh skinning shader, which could be alleviated by adding `highp` in the right location (at a performance cost).

**Comment by dsyze** [comment]
> This is likely a precision issue in the mesh skinning shader, which could be alleviated by adding `highp` qualifiers in the right location (at a performance cost). I'm surprised this occurs on non-Qualcomm GPUs though; usually, it's the opposite.

Thanks, can you tell me more details on how to adding `highp` qualifiers in the right location ?

**Comment by clayjohn** [comment]
@dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)

**Comment by dsyze** [comment]
> @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)

Thank you, sir! I will try.

**Comment by dsyze** [comment]
> @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)

Unfortunately, the issue persists even after using the recompiled editor and the Android export template.

**Comment by clayjohn** [comment]
> > @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)
> 
> Unfortunately, the issue persists even after using the recompiled editor and the Android export template.

Could you share the updated version of the skeleton.glsl file you used so I can verify you changed all the necessary places?

Also, to confirm, you recompiled the editor _and_ the android export template right?

**Comment by dsyze** [comment]
> > > @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)
> > 
> > 
> > Unfortunately, the issue persists even after using the recompiled editor and the Android export template.
> 
> Could you share the updated version of the skeleton.glsl file you used so I can verify you changed all the necessary places?
> 
> Also, to confirm, you recompiled the editor _and_ the android export template right?

[skeleton.zip](https://github.com/godotengine/godot/files/15140811/skeleton.zip)
Thanks a lot.

**Comment by dsyze** [comment]
> > > @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)
> > 
> > 
> > Unfortunately, the issue persists even after using the recompiled editor and the Android export template.
> 
> Could you share the updated version of the skeleton.glsl file you used so I can verify you changed all the necessary places?
> 
> Also, to confirm, you recompiled the editor _and_ the android export template right?

I found out that the method "Engine.set_max_fps() " does not work on MediaTek Dimensity devices too. Perhaps they are related. This method can work normally on Qualcomm devices and desktop Android emulators.

**Comment by Calinou** [comment]
> I found out that the method "Engine.set_max_fps() " does not work on MediaTek Dimensity devices too. Perhaps they are related. This method can work normally on Qualcomm devices and desktop Android emulators.

What value are you using for `Engine.max_fps`? (Note that you can set this directly as a property; no need to use the setter method). Values above the display refresh rate will not be obeyed by Godot, because Android forces V-Sync.

**Comment by dsyze** [comment]
> > I found out that the method "Engine.set_max_fps() " does not work on MediaTek Dimensity devices too. Perhaps they are related. This method can work normally on Qualcomm devices and desktop Android emulators.
> 
> What value are you using for `Engine.max_fps`? (Note that you can set this directly as a property; no need to use the setter method). Values above the display refresh rate will not be obeyed by Godot, because Android forces V-Sync. This prevents FPS from exceeding the display refresh rate by design.

I tried to limit the frame rate to 40, but it still runs at the highest refresh rate of the screen on devices with the MediaTek Dimensity devices.

**Comment by dsyze** [comment]
> > I found out that the method "Engine.set_max_fps() " does not work on MediaTek Dimensity devices too. Perhaps they are related. This method can work normally on Qualcomm devices and desktop Android emulators.
> 
> What value are you using for `Engine.max_fps`? (Note that you can set this directly as a property; no need to use the setter method). Values above the display refresh rate will not be obeyed by Godot, because Android forces V-Sync. This prevents FPS from exceeding the display refresh rate by design.

Sir, I have solved this problem. Previously, I had overlooked the Android build template. I only applied the compiled export template as a custom one in the export options, instead of replacing the main template in the Godot editor settings. The most significant impact should be the Android build template installed for the project, which I had previously ignored. Now, after organizing my thoughts, this issue has been perfectly resolved. Thanks for your work and help. May God bless you.

**Comment by dsyze** [comment]
> @dsyze In this file https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl You would replace all the places where it says `mediump` with `highp`. And then below, in the body of the shader, when a new variable is defined you would add highp as well (e.g. `highp vec3` instead of just `vec3`)

Sir, I have solved this problem. Previously, I had overlooked the Android build template. I only applied the compiled export template as a custom one in the export options, instead of replacing the main template in the Godot editor settings. The most significant impact should be the Android build template installed for the project, which I had previously ignored. Now, after organizing my thoughts, this issue has been perfectly resolved. Thank you for your work and help. May God bless you.

**Comment by clayjohn** [comment]
@dsyze Thank you for following up!

I can reproduce this issue on my device with a Mali G710 GPU.

**Comment by dsyze** [comment]
> @dsyze Thank you for following up!
> 
> I can reproduce this issue on my device with a Mali G710 GPU.

This issue also occurs on iOS devices. I am using Godot 4.3 RC2.

**Comment by dsyze** [comment]
> @dsyze Thank you for following up!
> 
> I can reproduce this issue on my device with a Mali G710 GPU.

I am pleased to inform you that the identical issue on iOS devices can be resolved using the same approach. Following my tests, it appears to work flawlessly, and, in fact, it doesn't significantly affect performance. The device I used for testing is an iPad 6th generation (2018 model) equipped with the A10 processor. And it is by godot-4.3rc after recompiled.

**Comment by clayjohn** [comment]
That's amazing! I'm glad to hear that it is working well

**Comment by dsyze** [comment]
> That's amazing! I'm glad to hear that it is working well

Sir, I noticed that now in godot master rep https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/skeleton.glsl. There   are still many mediump. Not been replaced.

**Comment by dsyze** [comment]
> [@dsyze](https://github.com/dsyze) that is correct. In the end we only needed to change to highp in one place see [#95452](https://github.com/godotengine/godot/pull/95452)

Thank you, I don't quite know OpenGL and C++. I just wanted to remind you this. It's okay if there's no problem. Have a nice day, sir.

**Comment by dsyze** [comment]
> > > [@dsyze](https://github.com/dsyze) that is correct. In the end we only needed to change to highp in one place see [#95452](https://github.com/godotengine/godot/pull/95452)
> > 
> > 
> > Thank you, I don't quite know OpenGL and C++. I just wanted to remind you this. It's okay if there's no problem. Have a nice day, sir.
> 
> It is always possible that our devices behave differently. The fix was merged for Godot 4.4, so if you still see the trembling when using Godot 4.4, please let me know

Sure, no problem.
