### ISSUE TITLE
Model for testing materials in Godot

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#9118]
![selection_128](https://user-images.githubusercontent.com/6152134/27007479-56b05c2e-4e55-11e7-9413-a1dbd93a6c46.png)

Zip with DAE and .blend:
[GodotBall.zip](https://github.com/godotengine/godot/files/1066196/GodotBall.zip)

![selection_127](https://user-images.githubusercontent.com/6152134/27046792-0ec72904-4fa6-11e7-9306-d30ee043ef51.png)

**Comment by HumanSheeple** [comment]
That looks really cool!

**Comment by toger5** [comment]
It has a godot Logo on it !!!

why is the logo a different material. does it has two material channels? (are multiple material channels even supported?)

Why is it an issue? Are you planning to implement this as a default material testing object?

**Comment by n-pigeon** [comment]
@toger5
Yes, multiple materials are supported. If you have single mesh you have to assign to different parts different tmp materials. Then when you export to dae and import to Godot multiple slots for materials will be available in inspector for that mesh resource.

I made issue so it wont get lost and anybody can download. There was idea on IRC to have one of those. Although I don't know for what purpose exactly. xD

**Comment by n-pigeon** [comment]
Oh I had idea to animate one of the parts. Will update DAE soon to support this xD

**Comment by tGuMedia** [comment]
looks nice, except for the stand it's too long and thin.

**Comment by n-pigeon** [comment]
@tGuMedia
I wanted a cone in there ;) No one includes Cones in material previews! No one! We need them : [

**Comment by quantum-entangler** [comment]
That visible UV seam kind of bothers me, but I guess its useful for it helps notice any normal map issues.

**Comment by n-pigeon** [comment]
UV is tiled I just didn't used tiled texture.

![selection_127](https://user-images.githubusercontent.com/6152134/27046747-e70450c2-4fa5-11e7-9f10-2c5919dc8a26.png)

**Comment by quantum-entangler** [comment]
Now that's more like it, now can we have that replace the broken test-cube? 😄

**Comment by DriNeo** [comment]
What if the test cube is replaced by a "test mesh instance" with a primitive as resource ? In the same way as the collision shape gives a choice between several shapes. Is this a good idea ?

**Comment by bojidar-bg** [comment]
@DriNeo Welcome to the party, #8661 is just doing that. 😃

**Comment by reduz** [comment]
this was used already and works great, thanks! 
closing
