### ISSUE TITLE
Crash on adding GPUParticles2D to scene when using Compatibility renderer on macOS

### ISSUE THREAD

**Issue by tanuki-billie** [godotengine/godot#91186]
### Tested versions

- 4.3.dev5
- 4.2.2.stable
- 4.2.1 stable
- 4.1.4 stable

### System information

Godot v4.2.2.stable - macOS 14.4.1 - GLES3 (Compatibility) - Apple M2 - Apple M2 (8 Threads)

### Issue description

While using the Compatibility renderer, if a GPUParticles2D node is added to the scene, the editor crashes.

### Steps to reproduce

1. Create or open a project that is using the Compatibility renderer.
2. Add GPUParticles2D to the scene
3. Voilà, your engine crashes.

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment]
Thank you for your report. This same issue has been reported already and is tracked by https://github.com/godotengine/godot/issues/72469 

We like to keep bug reports in one place, so I'm going to close this issue in favour of https://github.com/godotengine/godot/issues/72469
