### ISSUE TITLE
TabBars are unresponsive to any theme changes

### ISSUE THREAD

**Issue by scratchermatch** [godotengine/godot#91187]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4953) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

TabBars are completely unresponsive to any theme changes in any field. Things like Font Size, Font, StyleBoxTextures for tab selected, etc. will never be set. 

Just to verify this isn't just me, I downloaded some other themes and attempted to load them in. Every single one faced the exact same issue. TabBars are completely unresponsive to theme changes. Manually overriding the theme for the TabBar also does nothing. Setting the theme in Project Settings does nothing. Setting the theme on the parent does nothing.

### Steps to reproduce

- Create a TabContainer and add some TabBars
- Create a new theme
- Set the TabBars to use that theme
- Override any or all of the options for TabBars
- Change any of them to any value
- Nothing will happen

![Screenshot (3)](https://github.com/godotengine/godot/assets/60678063/8dec407d-4c86-4df1-b163-031709d0f90f)

### Minimal reproduction project (MRP)

[MRE.zip](https://github.com/godotengine/godot/files/15122324/MRE.zip)

**Comment by kitbdev** [comment]
TabContainers have an internal TabBar that they use to show the tabs, you don't need to have TabBars as children of it. See [here](https://docs.godotengine.org/en/stable/classes/class_tabcontainer.html#description).
If you add a theme for TabContainer, or add tabs to the TabBars, you should see the it working.

![image](https://github.com/godotengine/godot/assets/10054226/24e5fa8b-3f77-44b4-b97c-001ec6fa5ba7)

**Comment by scratchermatch** [comment]
Thank you for explaining that to me, the tab container makes a lot more sense now!
