### ISSUE TITLE
XBOX ControllerEvents Gets Picked Picked Up By Both Sessions When Using Multiple Sessions

### ISSUE THREAD

**Issue by silvasch** [godotengine/godot#91207]
### Tested versions

- Reproducible in: 4.2.2.stable.official

### System information

Godot v4.2.2.stable - Fedora Linux 40 (Workstation Edition) - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (ICL GT1) () - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 Threads)

### Issue description

I'm currently creating a multiplayer game and have added controls for both keyboard and controller to the input map. To test I run two instances at once.

When I'm using controller input, the events get picked up by the focused **and** the unfocused window (i. e. pressing the "A" button causes both players to jump, not just the player of the currently focused window).

I'm not sure if this is intentional behavior, because #41684 mentions that the game window pickup up a joy pad button press when not focused is "as expected". If that is the case, is there any way I can work around this? Because I'm making a multiplayer game, this is annoying because I'm always moving with two characters at the same time.

### Steps to reproduce

1. Run a game with some controller action configured to do an action in two instances (see MRP below).
2. Press the aforementioned action when not focusing the game window.
3. The action is still executed.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/15128219/MRP.zip)

This MRP has an action called `say_hello` that is mapped to `Joypad Button 0`. The `main.gd` script just checks for that action and then prints "Hello, World!" in the console.

**Comment by AThousandShips** [comment]
This is indeed intended, and [documented](https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html#window-focus), please see there for details on how to work with this

**Comment by silvasch** [comment]
Oh OK, thank you.
