### ISSUE TITLE
Animation tree state machine `switch_mode: immediate` transition doesn't fire when there's a valid `switch_mode: at_end` transition present

### ISSUE THREAD

**Issue by Watersilver** [godotengine/godot#91212]
### Tested versions

- Reproducible in: 4.2.2.stable

### System information

Windows 10

### Issue description

Some state machine node transitions with `switch_mode = immediate` inside the animation tree stop working properly when the node also has other transitions that have `switch_mode = at_end` and an advance_expression that holds true or is empty.

The issue is that the immediate transition doesn't fire immediately, instead if fires at the end of the animation.

There's a video at [this](https://www.reddit.com/r/godot/comments/1canh99/animation_tree_sm_some_transitions_dont_work/) reddit post.

What we see at the video is the issue happening twice: Firstly the animation continues when the character is still though it should transition to idle. Secondly the turn animation should be flipped but doesn't because the flip animations also have `at_end` transitions so the immediate transitions between them don't fire.

Other transitions however don't have this issue. The transition to jump from the run_turn node always fires correctly even though I created the state machine and the code that controls its advance_expressions twice.

The issue gets "fixed" if the `at_end` transition has an expression that returns `false` at the moment the immediate transition needs to fire.

### Steps to reproduce

When you first run the MRP it should run correctly. Left and right arrow keys or A and D move, and X jumps.

Then in the player scene, select the animation tree node and select this transition

![image](https://github.com/godotengine/godot/assets/35609105/e0016720-4043-4890-b70c-79370efb2894)

It should have advance_expression: running. If you either delete this or replace it with a value that is true (like `true or running`) the transition from run_turn to idle should start behaving as if switch_mode was at_end. Deleting this transition should also make run_turn transition to idle correctly, but will obviously make run_turn -> run stop working.

Also, edit run_turn

![image](https://github.com/godotengine/godot/assets/35609105/86d299f8-feaf-409b-96e6-ce9319e55e45)

if you edit the two transitions that point to the end and delete their advance_expressions or make them always true, the two turn animations will not be able to transition between each other anymore.

Despite all that, jumping always works correctly.

The code that controls the transitions is inside player.gd in the method `handle_anim_tree`. Ignore anything to do with `anim_tree_advance_steps`, it's for another issue. Also the final lines can be ignored as they are there just for to print feedback. It's as simple as I can make it while showcasing all issues. The animation tree also has a script that contains exported variables for use in expressions and to look at for sanity checks during gameplay.

The output prints the sprite that is animating, its frame and how long the frame lasted.

### Minimal reproduction project (MRP)

[AnimTreeIssues.zip](https://github.com/godotengine/godot/files/15131732/AnimTreeIssues.zip)

**Comment by TokageItLab** [comment]
I tried to understand, but could not clearly see what is the behavior you are looking for. Please send MRPs with the state problem already occurring, and organize a summary by describing which key and how it is entered that causes the problem.

Is it perhaps a priority issue? May be you could try setting `run_turn->run` to Priority 2.

![image](https://github.com/godotengine/godot/assets/61938263/2fe81e00-f780-42e3-9a20-16003ab2647c)

**Comment by Watersilver** [comment]
Sorry about the confusing explanation, it's difficult for me to explain, so I'll try with videos.

Here's a video with the problem: [https://youtu.be/Bz8TQgL7WvQ](https://youtu.be/Bz8TQgL7WvQ)
Here's a video with the expected behaviour: [https://youtu.be/cMzInaPCwHk](https://youtu.be/cMzInaPCwHk)

Repo with the projects seen in the video: [https://github.com/Watersilver/AnimTreeIssues](https://github.com/Watersilver/AnimTreeIssues)

The second video was actually an attempt to reproduce the issue in a smaller project but it didn't work, so I just simplified the original as much as I could. It now has no code except for the small script that defines the animation tree variables that are used in the advance_expressions.

I have no idea why this is happening. As far as I can tell the two state machines are identical although I've been looking at this so many days that I think it's fried my brain.

The only difference they have are the node types, but that shouldn't matter, right? The "expected" one just has animations as nodes while the "problem" one has state machines that handle facing as nodes. I also checked the "priority" setting as you said and added greater priority to the transition that moves to idle but the issue persisted.

I included the "jump" node and transitions to the original because that transition worked correctly unlike the transition to idle but I think it confused the issue more. I hope I explained it better now.

**Comment by TokageItLab** [comment]
I watched the video and did not see where the problem was at all, as everything seems to be working according to the specified conditions.

To open a problem project, then you click on `transitional` state, if you always want the result of an immediate transition to `state 1` from `transitional` state without waiting for at end, set the priority of `transitional -> state 2` to `2` since transitions to state 1 and state 2 have the same priority, it appears that the transition to state 2 takes precedence. The smaller value of the Priority, the more precedence is given to the transition (it can be a little confusing).

**Comment by Watersilver** [comment]
Ah ok I understand. You're right, it works correctly with the priority.

In both videos I didn't change the priorities though, so I got confused that seemingly the same settings had different behaviours but I guess since I didn't set them it chose randomly and it happened to chose different paths for the different projects.

So, this isn't a bug at all but the actual intended behaviour: When there are two eligible transitions and one is set to only fire `at_end` and the other `immediately`, if the at_end transition has priority then the animation will wait and use the `at_end` transition when ready. I incorrectly assumed that the `at_end` transition only gets *checked* at the end of the animation but it actually gets checked every frame but only *fires* at the end of the animation.

Thank you very much for your help!
