### ISSUE TITLE
`Node.duplicate()` runs about twice as slow since node property duplication fix

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#91230]
### Tested versions

- Reproducible in: 4.3.dev5
- Not reproducible in: 4.2.1.stable

### System information

Godot v4.3.dev (b091162a9) - Fedora Linux 39 (KDE Plasma) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

`Node.duplicate()` runs about twice as slow since node property duplication fix, even on a plain Node with no properties or metadata set.

### Before the fix

```
Iteration 0: 48.979 MB
Iteration 1: 48.984 MB
Iteration 2: 48.994 MB
Iteration 3: 49.014 MB
Iteration 4: 49.054 MB
Iteration 5: 49.132 MB
Iteration 6: 49.290 MB
Iteration 7: 49.606 MB
Iteration 8: 50.266 MB
Iteration 9: 51.588 MB
Iteration 10: 54.099 MB
Iteration 11: 59.252 MB
Iteration 12: 69.558 MB
Iteration 13: 90.169 MB
Iteration 14: 131.391 MB
Iteration 15: 213.836 MB
Done running in 3571 milliseconds.
```

### After the fix

```
Iteration 0: 40.596 MB
Iteration 1: 40.601 MB
Iteration 2: 40.611 MB
Iteration 3: 40.631 MB
Iteration 4: 40.671 MB
Iteration 5: 40.749 MB
Iteration 6: 40.907 MB
Iteration 7: 41.221 MB
Iteration 8: 41.881 MB
Iteration 9: 43.203 MB
Iteration 10: 45.714 MB
Iteration 11: 50.867 MB
Iteration 12: 61.173 MB
Iteration 13: 81.784 MB
Iteration 14: 123.006 MB
Iteration 15: 205.451 MB
Done running in 5207 milliseconds.
```

I bisected the regression to 9851c1bdd893a6194fdbf1820d2fa07449d4f9fb (https://github.com/godotengine/godot/pull/87387).

cc @warriormaster12

### Steps to reproduce

- Use `Node.duplicate()` thousands of times in a project or more in a quick succession. The performance difference is noticeable in both debug and release builds.

### Minimal reproduction project (MRP)

[test_alloc_duplicate.zip](https://github.com/godotengine/godot/files/15135522/test_alloc_duplicate.zip)

**Comment by warriormaster12** [comment]
The pain never ends.

**Comment by warriormaster12** [comment]
My first guess is that it is due to the function ```_duplicate_properties_node``` that I wrote. I'll be testing that theory in a moment.

**Comment by warriormaster12** [comment]
Tested on M3 Pro Macbook Pro 
```
Iteration 0: 58.707 MB
Iteration 1: 58.712 MB
Iteration 2: 58.722 MB
Iteration 3: 58.742 MB
Iteration 4: 58.782 MB
Iteration 5: 58.861 MB
Iteration 6: 59.018 MB
Iteration 7: 59.331 MB
Iteration 8: 59.992 MB
Iteration 9: 61.313 MB
Iteration 10: 63.824 MB
Iteration 11: 68.978 MB
Iteration 12: 79.284 MB
Iteration 13: 99.895 MB
Iteration 14: 141.118 MB
Iteration 15: 223.563 MB
Done running in 2246 milliseconds.
```

After commenting ```_duplicate_properties_node```

```
Iteration 0: 58.383 MB
Iteration 1: 58.388 MB
Iteration 2: 58.398 MB
Iteration 3: 58.418 MB
Iteration 4: 58.458 MB
Iteration 5: 58.537 MB
Iteration 6: 58.694 MB
Iteration 7: 59.008 MB
Iteration 8: 59.668 MB
Iteration 9: 60.989 MB
Iteration 10: 63.501 MB
Iteration 11: 68.654 MB
Iteration 12: 78.960 MB
Iteration 13: 99.571 MB
Iteration 14: 140.794 MB
Iteration 15: 223.239 MB
Done running in 1596 milliseconds.
```
So my theory was correct.
