### ISSUE TITLE
`ERROR: Parameter "env" is null.` with Compatibility renderer

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#91239]
### Tested versions

v4.3.dev.custom_build [6118592c6]

### System information

Godot v4.3.dev (6118592c6) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Repeated errors:

```
ERROR: Parameter "env" is null.
   at: RendererEnvironmentStorage::environment_get_adjustments_enabled (servers\rendering\storage\environment_storage.cpp:787)
ERROR: Parameter "env" is null.
   at: RendererEnvironmentStorage::environment_get_color_correction (servers\rendering\storage\environment_storage.cpp:817)
```

### Steps to reproduce

Run [Godot Demo Pause project](https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause) and start it.

### Minimal reproduction project (MRP)

Use the [Godot Demo Pause Project](https://github.com/godotengine/godot-demo-projects/tree/master/misc/pause)

```
git bisect bad
e8bb0a5719ca78a0b10ab980c4c5c06b5bdf7dbb is the first bad commit
commit e8bb0a5719ca78a0b10ab980c4c5c06b5bdf7dbb
Author: clayjohn
Date:   Thu Apr 25 12:24:51 2024 -0700

    Add adjustments and color correction to Compatibility renderer
```

**Comment by clayjohn** [comment]
Fix incoming
