### ISSUE TITLE
When you click on "attach script" button of a node, the default name for the script doesnt follow the naming convention.

### ISSUE THREAD

**Issue by chexmo** [godotengine/godot#91241]
### Tested versions

Version 4.2.1

### System information

Windows 10 x64 - Godot 4.2.1

### Issue description

AFAIK the naming convention for all files is snake_case and for nodes is PascalCase... However, if the node is in PascalCase, the file name of the script isn't converted to snake_case.

![image](https://github.com/godotengine/godot/assets/30608909/3dc82421-1484-41de-b7f2-7437fdfb3542)

### Steps to reproduce

On any scene:
 - click on a node of the Scene tab
 - click on Attach Script button (or shortcut or whatever)

### Minimal reproduction project (MRP)

Not necessary

**Comment by chexmo** [comment]
To comment... It isn't necessarily important for the engine to work, obviously... but it's important for the developer's quality of life (plus newbies can follow naming conventions easily)

**Comment by KoBeWi** [comment]
Thanks for the report, this is already resolved in 4.3: #78119
