### ISSUE TITLE
Broken layer tiles in `TileMap` that never render anything

### ISSUE THREAD

**Issue by martinsik** [godotengine/godot#91249]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

Windows 11 Pro but happens also on OS X

### Issue description

I have the following test project with a simple TileMap and two layers. I have two sources: Atlas and ScenesCollection.

Somehow one tile in layer named as `layer_0` is broken and never renderes anything when I run the scene. It looks like it's filled but it doesn't work with either atlas or scene tiles.

![Screenshot 2024-04-27 120504](https://github.com/godotengine/godot/assets/238765/26930e99-a492-49dc-b2fd-f08416d10931)

Other layers work fine. You can see the behavior on the following video:

https://github.com/godotengine/godot/assets/238765/180e6d84-be27-4248-b477-c677a6226bed

What's interestign that the broken tile is probably unrelated to the layer itself but rahter its index `0`. When I remove the layer then it's still broken but on layer named `layer_1`. When I create the layer again, it's still broken for the first layer in the list.

I have a different project where I've encountered the same issue but there I can't draw anything into an entire layer.

### Steps to reproduce

I have no idea what caused this behavior.

It might be somehow related to using `TileSetScenesCollectionSource` because I haven't experienced the same thing until I started usign that. But I might be wrong and  `TileSetScenesCollectionSource` is unrelated to this issue.

My second suspicion is that it's related to using `@tool` and maybe `set_cell()` together.

### Minimal reproduction project (MRP)

[godot-tilemap-test.zip](https://github.com/godotengine/godot/files/15138006/godot-tilemap-test.zip)

**Comment by AThousandShips** [comment]
The video you uploaded doesn't work

**Comment by kleonc** [comment]
> Somehow one tile in layer named as `layer_0` is broken and never renderes anything when I run the scene. It looks like it's filled but it doesn't work with either atlas or scene tiles.

You're setting the given cell to an invalid tile:
```gdscript
set_cell(0, Vector2i(1,1), 1, Vector2i.ZERO, 3)
```
The TileSetScenesCollectionSource with `id = 1` has no tile with `id = 3`:
![rwnBvPHL7C](https://github.com/godotengine/godot/assets/9283098/ceded92a-4712-48e1-bdc1-dbd1b0e04e90)


Changing it to either a scene with `id = 1` or `id = 2` works just fine:
| `set_cell(0, Vector2i(1,1), 1, Vector2i.ZERO, 1)` | `set_cell(0, Vector2i(1,1), 1, Vector2i.ZERO, 2)` | `set_cell(0, Vector2i(1,1), 1, Vector2i.ZERO, 3)` |
|--------|--------|--------|
|![Godot_v4 2 2-stable_win64_kiVouqLGee](https://github.com/godotengine/godot/assets/9283098/b1ae3e66-6a8c-4538-b7a7-c9a8b618755c)|![Godot_v4 2 2-stable_win64_XDWwHwt9GO](https://github.com/godotengine/godot/assets/9283098/490a0155-a665-4587-a9f8-ca12283567b0)|![Godot_v4 2 2-stable_win64_lr3enDvQeo](https://github.com/godotengine/godot/assets/9283098/b80f4b2a-9037-4c02-84aa-7188cac61fe6)|

Don't see any bug in here.

**Comment by martinsik** [comment]
@kleonc You're right!, My bad!
