### ISSUE TITLE
Scene tree drag&drop does not work after delay

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#91254]
### Tested versions

- Reproductible in 4.3.dev [e96c61c623] (debug and release build)
- Not Reproductible in 4.3.dev (26e01e41d) (2 weeks ago)
- Not Reproductible in 4.2.1 stable

### System information

Godot v4.3.dev (6118592c6) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

When dragging nodes in the Scene tree over a node, if you wait the node to be marked, and to drop without moving at all, the drop does nothing.
![godot windows editor x86_64_L6iCr15PcU](https://github.com/godotengine/godot/assets/81109165/e9c5ea6a-0ab3-4207-9a52-b293542f50d1)

### Steps to reproduce

- Left click and hold a node
- Drag over another node
- Wait for the node to change text color
- Release left mouse button
- Nothing happens

### Minimal reproduction project (MRP)

Any project will do.

**Comment by Infectious-Smile** [comment]
+1

**Comment by Sauermann** [comment]
Bisected to #90653 CC @ajreckof
