### ISSUE TITLE
Except for white and black, there will be obvious lag in the color panel when the mouse is moved.

### ISSUE THREAD

**Issue by ModuleCode** [godotengine/godot#91268]
### Tested versions

v4.2.2.stable.official [15073afe3]
The problem always existsI still have this problem when testing version v4.3.dev5.official [89f70e98d]

### System information

Win11 AMD Ryzen 7 5800H with Radeon Graphics       GTX1650

### Issue description

I have an obvious problem of not following the color panel when I use it. This situation has existed for a long time.

I don’t know why I can’t publish the video on Github, so I can’t post the video of my problem.

### Steps to reproduce

Create a ColorRect node, and then try to use the mouse to select a color in the box. White and black are not stuck, but other colors will obviously not follow.

### Minimal reproduction project (MRP)

No

**Comment by Calinou** [comment]
> I don’t know why I can’t publish the video on Github, so I can’t post the video of my problem.

Is the video in MP4 or WebM format and smaller than 10 MB? You could try uploading it to YouTube as unlisted and link the video here.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you are able to upload the video this can be reopened, but currently this cannot be investigated as there's not enough detail
