### ISSUE TITLE
Decal Modulate changed in version 4.3

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#91269]
### Tested versions

v4.3.dev.custom_build [6118592c6]

### System information

Godot v4.3.dev (6118592c6) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Godot 4.2 Stable on the left. Latest build from master on the right.
![Screenshot 2024-04-26 232714](https://github.com/godotengine/godot/assets/6188278/29f89a9a-16b5-4d20-b75f-16515442afe0)

This may just be a change, not a bug, but there is an obvious difference in the result between 4.2 and 4.3

### Steps to reproduce

Run the [Decals Godot Demo project](https://github.com/godotengine/godot-demo-projects/tree/master/3d/decals) and start it and cycle over to the Distance Fade demo.

### Minimal reproduction project (MRP)

Use the [Decals Godot Demo project](https://github.com/godotengine/godot-demo-projects/tree/master/3d/decals)

### Bisect
2f0ba1ed3fd0557e0e9d1a716f73d9438fa11ae4 is the first bad commit
commit 2f0ba1ed3fd0557e0e9d1a716f73d9438fa11ae4
Date:   Sun Mar 24 14:59:33 2024 +0100

    Fix decal modulate being passed as srgb instead of as linear color.

 servers/rendering/renderer_rd/storage_rd/texture_storage.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

### Update
This may have nothing to do with the "Distance Fade" and instead be related to how decals (in general or the one in this demo) respond to the Modulate and Albedo Mix parameters in 4.3 vs. 4.2

![image](https://github.com/godotengine/godot/assets/6188278/4950b122-7471-450b-93f7-63442045737b)

I was able to approximate the 4.2 effect in 4.3 by adjusting the Modulate and Albedo Mix parameters, so the regression seems to be in how those are being applied.
![image](https://github.com/godotengine/godot/assets/6188278/e9e85e32-7df8-4182-aa5e-2bb2b7bc4588)

**Comment by clayjohn** [comment]
This is an expected change. The old behaviour was buggy as we were doing a blend between a linear color and an sRGB color and then treating the result as a linear color. All other inputs are converted to linear to ensure proper blending.

See the description in https://github.com/godotengine/godot/pull/89849

**Comment by chrisl8** [comment]
Sounds good to me. You can close this or I can.

My only other thought is to try naming this in away that it will hopefully be found by anyone else running into the issue when searching before making a new issue.

I updated the name to what I would search for, but you might have a better idea.

**Comment by clayjohn** [comment]
The new name looks great to me!
