### ISSUE TITLE
Javascript Moving Loading Icon

### ISSUE THREAD

**Issue by zicklag** [godotengine/godot#9127]
## Summary

The loading page, while a Godot Javascript game export is downloading, should have a moving loading icon.

## Explanation

Users have a hard time believing that a computer is doing something if there is nothing indicating that it is actually getting somewhere. Granted, Godot does say, "Loading Page...", but as it sits there saying that, the page looks completely frozen. If it is a larger game or is it is downloading over a slower network, the user is likely to kill the page because it looks like it hasn't gotten anywhere. It would be nice to have a rotating circle icon or something like that. Even if the icon is a gif and it doesn't actually indicate progress, I think it would make the user feel a lot better.

**Comment by bojidar-bg** [comment]
Also, it should probably who the splash screen as well (if this is doable)
