### ISSUE TITLE
When the project is run, FullRect anchored elements increase in size in scenes opened but not selected

### ISSUE THREAD

**Issue by Gamepro5** [godotengine/godot#91274]
### Tested versions

4.2.2

### System information

Godot v4.2.2.stable unknown - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

https://github.com/godotengine/godot/assets/23440295/2c19998f-add8-48f9-957b-9c82c99d0d7c

When running the project while ui.tscn is in the project tabs, but where ui.tscn is not the currently selected tab, the size of a specific element that is anchored with FullRect fill will increase drastically in size. This does not happen if ui.tscn is not currently open in the tabs or if it is open but is the scene that is selected when the play button is clicked. 

### Steps to reproduce

1. Open both ui.tscn and game.tscn so that both scenes are in your tab view. Click on 2D viewport.
2.  Observe the size of the "PlayBar" node in ui.tscn
3. Select game.tscn such that ui.tscn is still open in your tabs but minimized.
4. Click the F5 run button (the play project button) at the top right of the engine.
5. Close the game
6. Click back on ui.tscn, and observe the size of the "PlayBar" node again.
7. Click on "PlayBar", click on Anchors preset, and click the "undo" button. Then click on the dropdown and select "full rect". this will make it fix itself.

### Minimal reproduction project (MRP)

[AnchorBug.zip](https://github.com/godotengine/godot/files/15141091/AnchorBug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/90079

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
