### ISSUE TITLE
Godot spatial shader behaving very strangely

### ISSUE THREAD

**Issue by toxicrecker** [godotengine/godot#91277]
### Tested versions

Godot_v4.2.1-stable_mono_win64

### System information

Windows 10 - Godot_v4.2.1-stable_mono_win64 - Vulkan (Forward+) - GTX 1650 SUPER

### Issue description

The issue is best described with a video because I cannot come up with words that do it. (I have been brainfucked)

https://github.com/godotengine/godot/assets/62395124/f7544598-a747-4150-9979-5125f6a79e15

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

https://drive.google.com/file/d/1HNx07cFsT0hd72tXpLuJ48pFjO5vfrd-/view?usp=sharing

**Comment by Calinou** [comment]
I don't understand what's going on in the video. Can you describe what's happening and expected behavior?

**Comment by toxicrecker** [comment]
> I don't understand what's going on in the video. Can you describe what's happening and expected behavior?

There were two variables that had different names but same values which had 2 different effects on the shader.
Anyway, turns out I'm just very dumb and the value set in the inspector was overriding the value set in the code so I'm very sorry for not being mindful enough and wasting your time. I'm sorry
