### ISSUE TITLE
Issue adding Inputs to InputMap in tool script

### ISSUE THREAD

**Issue by Dis-One-Games** [godotengine/godot#91302]
### Tested versions

Tested in Godot Engine v4.2.2.stable.official

### System information

Windows 10, Intel i7-8565u, GTX1050mq

### Issue description

When using the `InputMap.add_action()` function from a `@tool` script the action isnt added.

When using this function there wont be any sign of error but the action wont appear in the input map in project settings however. Running `InputMap.has_action()` before `InputMap.add_action()` will return false and running it after will return true telling me that the action was added but nothing appears in project settings including after editor restarts. To get the actions with `InputMap.get_actions()` working in a `@tool` script i had to run `InputMap.load_from_project_settings()` first so i assumed this was the issue but running that before or after doesnt seem to fix it. 

### Steps to reproduce

Create a tool script with a function that used InputMap.add_action() to try and add an action. 
Check the input map in project settings after running it.

### Minimal reproduction project (MRP)

[InputMapIssue.zip](https://github.com/godotengine/godot/files/15146871/InputMapIssue.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this is because you're accessing the editor input map when running in the editor, not the project one, see:
* https://github.com/godotengine/godot/issues/71613

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/25865.
