### ISSUE TITLE
Android Godot editor doesn't take keypresses on Samsung DEX

### ISSUE THREAD

**Issue by maicomstoppa** [godotengine/godot#91317]
### Tested versions

Godot Editor 4 (Google Play)
v4.2.2.stable.official[15073afe3]

### System information

Android 14 / Samsung DEX

### Issue description

Godot Editor doesn't accept any input from the keyboard.

![Captura de tela 2024-04-29 130546](https://github.com/godotengine/godot/assets/10959341/f9c8a105-234a-4a3f-8e29-6227c6ed825c)

### Steps to reproduce

Just click in any text edit and try to type something

### Minimal reproduction project (MRP)

Not applicable.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/81890

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
