### ISSUE TITLE
CanvasItem nodes anchored to any "wide" setting double in size in the editor when compiling from another scene

### ISSUE THREAD

**Issue by MrWolfyer** [godotengine/godot#91316]
### Tested versions

- Reproducible in Godot v4.2.2-stable-win64

### System information

Windows 10 - Godot v4.2.2 - using Mobile Renderer

### Issue description

As the title suggests, CanvasItems keep doubling in size (in the EDITOR) when I run the project outside of the respective CanvasItem scene. Not necessarily run another scene in itself, but simply run the project with another scene opened.

Is there any way I can quickly fix this? I need to deliver a prototype till Saturday and I might need to switch engines.

### Steps to reproduce

- Run the project with the "home" scene opened, everything should be fine.
- Go to the "button" scene, then run the project again.
- Switch to the home scene again.
- Suddenly, the panel in the "home" scene has doubled in size!

https://github.com/godotengine/godot/assets/82157205/3218b67e-6d21-43ee-803c-d2ccdf842f97

### Minimal reproduction project (MRP)

[BUG.zip](https://github.com/godotengine/godot/files/15151237/BUG.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/90079

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
