### ISSUE TITLE
Unable to type into the hex field of colour property when the information prompt pops up.

### ISSUE THREAD

**Issue by SlyBew** [godotengine/godot#91311]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When you attempt to type into the Hex field within a colour property in the inspector, if the information prompt pops up, you are unable to type until you move the mouse away from the text box/

### Steps to reproduce

- Create a new User Interface Scene
- In the Inspector>CanvasItem>Visibility
- Click on the Modulate colour box to open the colour properties
- Click in the Hex text field
- If your mouse is inside the text field, and the info prompt pops up, you will be unable to type..
- If your mouse is outside the text field, and the info prompt disappears, you will be able to type.

This occurs for other colour properties I tested with, including Label Node>LabelSettings>Font>Color.

I do not think this should be the expected behaviour to restrict movement when the info box is shown as the natural movement from a user is to click in the text field to type, and leave the mouse still, not have to move the mouse outside the selected text field in order to type.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/79500

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
