### ISSUE TITLE
TileMap Editor Preview does not respect CanvasItem Texture Filter

### ISSUE THREAD

**Issue by IsaacMarovitz** [godotengine/godot#91328]
### Tested versions

- Reproducible in 4.2.2.stable

### System information

Godot v4.2.2.stable.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

The TileMap editor's preview will always display with `Linear` filtering, regardless of the filtering set on the actual CanvasItem. This can result in blurry previews for pixel-art-based tile sets.

<img width="1440" alt="Screenshot 2024-04-29 at 15 22 05" src="https://github.com/godotengine/godot/assets/42140194/fce5dfc2-11d9-4939-a7ef-c3231b3caa3e">

### Steps to reproduce

1. Create a pixel-art-based tile set
2. Create a TileMap with CanvasItem texture filtering set to `Nearest`
3. Preview adding a tile with any of the editor tools (Paint, Rect, etc...)
4. Observe blurry tile

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/52332

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
