### ISSUE TITLE
C#: Using dynamic object resolving results in `CSC : warning AD0001: Analyzer 'Godot.SourceGenerators.MustBeVariantAnalyzer'`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#91345]
### Tested versions

`<Project Sdk="Godot.NET.Sdk/4.2.2">`
It occurs also on latest dev 
```
   > Godot.SourceGenerators      4.3.0-dev.5   4.3.0-dev.5
   > GodotSharp                  4.3.0-dev.5   4.3.0-dev.5
   > GodotSharpEditor            4.3.0-dev.5   4.3.0-dev.5
```

### System information

Windows 11, ubuntu

### Issue description

I build my own C# unit test framework and have an issue with using dynamic object resolving.

When using dynamic e.g. `public static dynamic AssertThat<TValue>(TValue? current)` in combination with typed methods, it shows a warning.
`CSC: warning AD0001: Analyzer 'Godot.SourceGenerators.MustBeVariantAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [D:\development\workspace\gdUnit4Net\example\exampleProject.csproj::TargetFramework = net8.0]` 

This is a problem when other developers use my API and this type of warning is displayed very often.
As workaround, we can disable the warning in your project, but this should not be the standard.
`<NoWarn>$(NoWarn);AD0001</NoWarn>`

### Steps to reproduce

Download the example project and build.

### Minimal reproduction project (MRP)

[AD001.zip](https://github.com/godotengine/godot/files/15158976/AD001.zip)

**Comment by MikeSchulze** [comment]
@raulsntos It still occurs on `4.3.0-dev.6`, it which version is the fix included?

**Comment by raulsntos** [comment]
It's in `beta1`, you can check the [interactive changelog](https://godotengine.github.io/godot-interactive-changelog/#4.3-beta1).

**Comment by MikeSchulze** [comment]
> It's in `beta1`, you can check the [interactive changelog](https://godotengine.github.io/godot-interactive-changelog/#4.3-beta1).
I can confirm that the warnings have disappeared 👍
