### ISSUE TITLE
Could not resolve SDK "Godot.NET.Sdk"

### ISSUE THREAD

**Issue by uuuus** [godotengine/godot#91355]
### Tested versions

v4.2.2.stable.mono.official

### System information

Windows 10 v4.2.2.stable.mono.official

### Issue description

C# - During build an exception occured. Godot is trying to download sdk from my private nuget source. I can't see where can I set proper nuget source.

### Steps to reproduce

In VS add severeal nuget source addresses. Create project with C# script and run it.
![godot_err](https://github.com/godotengine/godot/assets/14109641/cf7546d8-6c17-4e06-acf7-c12b726a9be2)

### Minimal reproduction project (MRP)

create empty project, add any C# script and run it.

**Comment by akien-mga** [comment]
CC @godotengine/dotnet

**Comment by paulloz** [comment]
Hello. You can list your nuget sources with the following command (run it from the folder containing your `PrinceKiller.csproj` file):
```bash
dotnet nuget list source
```
Those sources are defined either globally in `%APPDATA%\NuGet\NuGet.Config` / `%APPDATA%\NuGet\config\*.Config`, or locally for your project in a `NuGet.Config` in any folder upward of the one containing your `.csproj`.
The restore is failing because you probably disabled the default `api.nuget.org` source, and none of your other sources is actually able to provide `Godot.NET.Sdk`.

**Comment by uuuus** [comment]
No, it's not disabled.
![nuget](https://github.com/godotengine/godot/assets/14109641/2099b3c3-ee52-4fa3-8769-414a120f1d59)

**Comment by paulloz** [comment]
Then your source at `192.168.178.3:5000` is not available. Which would also make the restore fail, since the operation requires all enabled sources to be available. In any case, this is a configuration issue, and not one on Godot's end.

**Comment by uuuus** [comment]
You say godot is looking for its sdk in my local source and it is not an issue? Funny approach to the problem.

**Comment by akien-mga** [comment]
It's not Godot, but dotnet, which has this behavior.

It's arguable whether it's a good behavior for `dotnet restore` to fail if one source is missing instead of falling back to other sources, but that's a problem you should take to the .NET people, not Godot. We can't work it around.

**Comment by paulloz** [comment]
Godot is not particularly looking for `Godot.NET.Sdk` in your local source, that is not how NuGet works. If any of your configured and enabled sources is unavailable, any restore operation will fail, period. This is a documented behaviour (I don't want to backlink issues for nothing, but you can find at least half a dozen of threads about it over on https://github.com/NuGet/Home). Trying to restore any other package (unrelated to Godot) that is not currently in your local cache will end in the same result.
