### ISSUE TITLE
Auto Complete Not Contextually Correct

### ISSUE THREAD

**Issue by MilkBagBoii** [godotengine/godot#91351]
### Tested versions

Reproducible in 4.2.2 Stable 

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (NVIDIA; 31.0.15.4633) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

Autocomplete suddenly isn't Guessing correctly given the context and I don't know why.
![Screenshot 2024-04-30 033919](https://github.com/godotengine/godot/assets/96600173/9d426787-9629-4823-98e4-9135464c0ef7)

look at the screenshot example   

### Steps to reproduce

Create a var from a node 

### Minimal reproduction project (MRP)

.

**Comment by AThousandShips** [comment]
Please show the way you declared `animated_sprite` is it statically typed as its type?

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
