### ISSUE TITLE
Godot 4 - Linux Nvidia Wayland - Editor Lag and Stutters 

### ISSUE THREAD

**Issue by 3DFE** [godotengine/godot#91357]
### Tested versions

- Reproducible in: Godot v4.2.2-stable

### System information

Linux - Godot v4.2.2-stable 

### Issue description

Linux Fedora 39 , 40 KDE
Godot 4  - on Wayland in Editor Lag and Stutters. Godot v4 , v4.1 , last testing Godot v4.2.2-stable
Godot editor stutters in menu and 3d view stutters if any input rotating camera.
Resize window whole window flicker , buttons highlight it takes up to 1 second. 
Is anyone seeing this behavior? ...

Godot 4 - on X.Org Server - X Window System (X11) - All works normally.

This error is probably combination of factors GPU driver and desktop environment.
Wayland Plasma 5 vs Plasma 6 stutters is improve. (Example in Steps to reproduce)
Nvidia Official Driver - 545_29_02 / 550_54_14 / 550_78 (RTX_3070)
Nvidia RPM fusion Driver - same on Nvidia Official Driver website

### Example 1:
Fedora 39 - KDE Plasma 5.27 Wayland - 
Nvidia Drivers - 545_29_02 / 550_54_14 / 550_78
"Godot 4 menu is unusable some buttons highlight it takes up to 1 second.
On start: Godot Engine - Project Manager - 
mouse movement window flicker black and back to graphic 2-3times/second."
OR resize window whole window flicker black and back to graphic. 

### Example 2:
Fedora 40 - KDE Plasma 6.0.4 Wayland - 
Nvidia Driver - 550_78 (RTX_3070)
"Godot 4 in Plasma 6 - Godot 4 much more stable in 3d project BUT still some stutters.
In 2d project stutters same as Plasma 5 strangely 2d for example scrolling
sometimes animate zoom in and out same time infinitely until other scroll."

### Minimal reproduction project (MRP)

[GD4_Hop_TEST.zip](https://github.com/godotengine/godot/files/15161089/GD4_Hop_TEST.zip)

**Comment by 3DFE** [comment]
HERE IS SOLUTION (only in Godot 4.3 ) :
4.3.dev6 > Editor Settings > Run > Platforms > Prefer Wayland >ON<)
Enabled (on) Wayland in 4.3.dev6 save restart. 

Fedora 40 - KDE Plasma 6.0.4 Wayland - Nvidia Driver - 550_78 (RTX_3070)
Now with option "Prefer Wayland" Godot runs rock solid.

On the forum it was pointed out this:
Note that Godot 4.2 also doesn’t have native Wayland support, so it relies on XWayland instead.
Native Wayland support is available in 4.3.dev but needs to be enabled in the Editor Settings.

**Comment by 3DFE** [comment]
SOLUTION ( only in Godot 4.3 ) : enabled in the Editor Settings. (Native Wayland support)
In Godot 4.3.dev6 > Editor Settings > Run > Platforms > Prefer Wayland >ON<

**Comment by Duckapple** [comment]
I'll jump in real quick to post some troubleshooting advice for the meantime before 4.3 is released.

[As detailed on the Arch Wiki](https://wiki.archlinux.org/title/Godot_Engine#UI_freezes_in_Wayland), you can alleviate a lot of the problems by launching Godot 4.2 with `--single-window`, since it will run everything within one window.

Personally, I also needed to set `--rendering-driver opengl3` for some reason. Wasn't needed when running directly without `--single-window`
