### ISSUE TITLE
`ExportAttribute` is ignored when decorating a generated property using source generators from Roslyn

### ISSUE THREAD

**Issue by ydogus** [godotengine/godot#91366]
### Tested versions

Reproducible in 4.2.2.stable [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5222) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

The properties decorated with `ExportAttribute` are not showh in inspector window when the properties are generated by a source generator.
I'm currently using [MVVM Toolkit](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/) to generate automatically properties from fields.

For example, it does help me to generate from:

```csharp
[Tool]
[ObservableObject]
public partial class CustomNode : Node3D
{
    private bool isDirty = true;

    [ObservableProperty]
    [property: Export]
    private int seed = 0;

    public CustomNode()
    {
        PropertyChanged += (sender, args) => isDirty = true;
    }
    ...
}
```

Into:

```csharp
partial class CustomNode
{
    /// <inheritdoc cref="seed"/>
    [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.2.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::Godot.ExportAttribute()]
    public int Seed
    {
        get => seed;
        set
        {
            if (!global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(seed, value))
            {
                OnSeedChanging(value);
                OnSeedChanging(default, value);
                OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.Seed);
                seed = value;
                OnSeedChanged(value);
                OnSeedChanged(default, value);
                OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.Seed);
            }
        }
    }
    ...
}
```

The latter is a copy paste of the generated code. You can see that `ExportAttribute` is added to the property. I don't know how .NET is integrated into Godot so I don't know what could be the reason why I don't see the property in the inspector. But I do confirm that using the reflection, I can see the attribute applied to the property when I look into the assembly.

Maybe there are some other conditions to meet?

### Steps to reproduce

- Create a new project
- Add `CommunityToolkit.Mvvm` package to the .NET project
- Create a new script class derived from `Node3D`
- Decorate the new class with `ObservableObjectAttribute`
- Create a private field (Eg: myField) in the class with `ObservableProperty` attribute and `Export` attribute using `[property: Export]` syntax
- Build the project and check the inspector: The property (Eg: MyField) should be there but it is not.

### Minimal reproduction project (MRP)

[Reproduction-NoPropertyExported.zip](https://github.com/godotengine/godot/files/15166554/Reproduction-NoPropertyExported.zip)

In this project there is a scene with single node which has a script attached with a class named `Custom`. This class has a property generated by source generators from a field. There is a dummy method that I've added to show that the property is well generated and the code compiles.

**Comment by raulsntos** [comment]
Source generators can't consume the output of other source generators:
- https://github.com/dotnet/roslyn/issues/57239.

Closing in favor of https://github.com/godotengine/godot/issues/66597 which already tracks this on the Godot side.
