### ISSUE TITLE
Enable by default 2D motion fix on 2.x

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9137]
**Godot version: 2.1.3**

**Issue description:**
The project setting to fix move on KinematicBodie2Ds is off by default for compatibility but I think it should be enabled on new projects.

The option is on `Project Settings>Physics 2D>motion_fix_enabled`.

**Comment by akien-mga** [comment]
I'm not sure if it's doable to set a new parameter to true on new projects, and false on existing projects.

**Comment by RandomShaper** [comment]
I like the idea of having it as the default for new projects.

I think it would be as easy to add it to the project creation routine,, that is, not actually changing the hard-coded default so old projects without that key defined still get it as `false`.
