### ISSUE TITLE
Modifying procedural sky parameters freezes Godot for a few seconds

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9138]
Latest Godot, Windows 10

I tried ProceduralSky, and it works great. The only problem is, when I change any parameter, the UI freezes for a few seconds, which slows down tweaking parameters, especially those that are "slided".

**Comment by reduz** [comment]
yeah.. generating it seems to take a while, leave this open so I remember
to move generation to a thread.

**Comment by Zylann** [comment]
Any idea why it's taking so long? WebGL demos seemed to work in real time, although Godot probably does more than that
