### ISSUE TITLE
Stream of errors when enabling refraction and SSS [radeon, Windows]

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9139]
**Operating system or device - Godot version:**
Windows - Radeon RX 480 - master (9570fb1)

**Issue description:**
When I enable Refraction or Subsurface Scattering in the SpatialMaterial, I get the same error over and over:

```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL
Type: Performance
ID: 108 Severity: A
Message: glBlitFramebuffer was called with either GL_DEPTH_BUFFER_BIT or GL_STENCIL_BUFFER_BIT set while there was no valid depth/stencil attachment on the draw framebuffer
   At: drivers\gles3\rasterizer_gles3.cpp:123
```

**Comment by vnen** [comment]
This seems to happen only if there's no environment.

**Comment by reduz** [comment]
building myself a test rig, as I have a lot of GPUs laying around

**Comment by reduz** [comment]
does this still happen?

**Comment by vnen** [comment]
No, I can't reproduce anymore.
