### ISSUE TITLE
4.3 dev 5 android editor crashes on opening

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#91397]
### Tested versions

- Reproducible in  4.3 dev 5

### System information

Android 11 - Godot V.4.3.dev5

### Issue description

When I tried to open the app it didn't open

my device specs:
model- Realme RMX2189
ram- 3.0 GB
os- Android 11

### Steps to reproduce

just download and install the app and then try to open it 
https://github.com/godotengine/godot/assets/100587814/73d1778a-d2cf-45bd-b5b6-8d66173f97b1

### Minimal reproduction project (MRP)

non

**Comment by akien-mga** [comment]
Tested on a Pixel 7a, I can confirm that 4.3-dev5 crashes on start.

It seems like this was fixed already, 4.3-dev6 (which I just uploaded) works fine.
