### ISSUE TITLE
Area2D.body_entered unexpected behavior, missing signals

### ISSUE THREAD

**Issue by Sewake** [godotengine/godot#91409]
### Tested versions

- Reproductible in 4.2.2 stable

### System information

Windows 11 - Godot 4.2.2 stable

### Issue description

Any entity which enter an Area2D zone should trigger the `body_entered` signal, no matter who initiated the movement. In my case, the signal is only triggered if the entity with the Area2D node move towards another entity, not the opposite.

### Steps to reproduce

Entity Player & Entity Ennemy with both CollisionShape2D nodes.
Player have an additional node: Area2D with a `body_entered `signal.

1. Move the player towards the enemy using the arrow keys, enter and exit the zone.
2. You should observe print statements similar to: Body entered: Enemy:<RigidBody2D#27481081035>.
3. Next, move the enemy towards the player using the WASD/ZQSD keys; note that no callbacks are triggered.

### Minimal reproduction project (MRP)

https://github.com/Sewake/GodotBodyEnteredBug

**Comment by AThousandShips** [comment]
You shouldn't move `RigidBody` by setting the position constantly, try moving it by modifying the velocity instead, see [here](https://docs.godotengine.org/en/stable/tutorials/physics/rigid_body.html)

**Comment by Sewake** [comment]
@AThousandShips indeed, my bad!

I updated my enemy script to update the velocity instead of the position, and now the signals are working as expected!

Thanks a lot for the help, I was stuck on this issue for so long 🙏
