### ISSUE TITLE
Scenes with GPUParticle2D in compatibility mode crashes the editor on MacOS 14.2

### ISSUE THREAD

**Issue by nubunto** [godotengine/godot#91419]
### Tested versions

4.2.2.stable.official [15073afe3]

### System information

MacOS 14.2, Apple M1 Max

### Issue description

When adding a GPUParticles2D node in any scene, in compatibility mode, the entire editor crashes.

### Steps to reproduce

1. Clone [this](https://github.com/nubunto/godot-4.2-gpu-particles-crash) project
2. Go into Project Settings > Renderer
3. Change the Rendering Method from forward_plus to gl_compatibility
4. Restart the editor
5. Open the "gpu_particles_2d.tscn" scene
6. Editor crashes

### Minimal reproduction project (MRP)

https://github.com/nubunto/godot-4.2-gpu-particles-crash

**Comment by nubunto** [comment]
I can maybe try to fix this if I know where to start, I'm familiar with programming but not C++

**Comment by AThousandShips** [comment]
Are you on 4.2 or 4.2.1 or 4.2.2?

**Comment by AThousandShips** [comment]
Good, it's useful to be specific in the issue report, it's impossible to tell

**Comment by nubunto** [comment]
yup, not able to reproduce my sample project with 4.3.dev6! although the font looks kinda funny, but this would be a separate topic
![image](https://github.com/godotengine/godot/assets/5007727/62d3e247-ab5c-435c-9c8e-2acb68be74b3)

**Comment by AThousandShips** [comment]
Then it seems some bug fix was added there, will see if I can identify some specific fix

**Comment by AThousandShips** [comment]
Seems this is tracked here:
* https://github.com/godotengine/godot/issues/72469

So consolidating there, and feel free to add any additional details you have there, including mentioning it seems to work on 4.3.dev6

**Comment by nubunto** [comment]
amazing, I will do so. Thanks @AThousandShips for the quick response!!
