### ISSUE TITLE
Opening a scene always selects the root node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#91411]
### Tested versions

4.3 dev6 broken
4.3 dev5 works

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you open a scene, root node will be always selected, even if you saved with a different selection. If a different node was selected previously, the scene will be opened with 2 nodes selected.

https://github.com/godotengine/godot/assets/2223172/b26521c0-890f-4bf7-9597-328c728199df

### Steps to reproduce

1. Open a scene
2. Select any node that isn't root, or deselect all
3. Save scene
4. Close
5. Open again

### Minimal reproduction project (MRP)

N/A

**Comment by fire** [comment]
Looks like we need to do a git bisect to find the regression.

**Comment by KoBeWi** [comment]
I'd start by finding the source of the selection (likely using debugger) and blaming the code.

**Comment by AeioMuch** [comment]
Bisected to https://github.com/godotengine/godot/pull/90653
