### ISSUE TITLE
Shader syntax highlighting breaks when preprocessor variable is undefined (regression 4.3-dev6)

### ISSUE THREAD

**Issue by dandeliondino** [godotengine/godot#91424]
### Tested versions

- Reproducible in 4.3-dev6
- Not reproducible in 4.3-dev5

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU (NVIDIA; 31.0.15.4633) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

In 4.3-dev6, checking for an undefined shader preprocessor variable with `#ifdef` causes the remainder of the script to lose its syntax highlighting, starting with the `#endif` line. In 4.3-dev5, the rest of the script would be highlighted as expected. This seems to only affect syntax highlighting, as the shader I discovered this with in my project still compiles and runs correctly.

4.3-dev5
![Screenshot 2024-05-01 142945](https://github.com/godotengine/godot/assets/68911895/142ec7c5-44c3-4a3f-a64b-cab2f109561b)

4.3-dev6
![Screenshot 2024-05-01 143043](https://github.com/godotengine/godot/assets/68911895/0d410567-9e34-4a94-8f9a-aa03dbe4d1cb)

### Steps to reproduce

- Create a new shader script
- Define a shader preprocessing variable using `#define VARIABLE_NAME`
- Place code inside a check for that variable using `#ifdef VARIABLE_NAME` (shader code here) `#endif`
- Comment out the line that contains `#define VARIABLE_NAME`
- Note that, starting with the `#endif` line, the remainder of the script loses its syntax highlighting

### Minimal reproduction project (MRP)

[shader-syntax-highlighting.zip](https://github.com/godotengine/godot/files/15181669/shader-syntax-highlighting.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #90161 as the culprit

![image](https://github.com/godotengine/godot/assets/44306054/38e000c9-7a5a-4229-be7c-b932e6ae3fa4)

**Comment by akien-mga** [comment]
CC @magian1127

**Comment by magian1127** [comment]
Highlighting `/** */` and `/* */` conflicts.
It seems that I need to modify the code highlighting style to match that of GDScript. 
We can start by disabling the highlighting for `/** */` and temporarily using the same color as `/* */`.
If there’s no urgency, I’ll submit a pull request later.
