### ISSUE TITLE
[xcb] Unknown request in queue while dequeuing [xcb]

### ISSUE THREAD

**Issue by shayelorgelly** [godotengine/godot#91434]
### Tested versions

Godot Engine v4.2.2.stable.arch_linux

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:33 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) () - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 Threads)

### Issue description

[xcb] Unknown request in queue while dequeuing
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
godot: xcb_io.c:175: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.

### Steps to reproduce

Crashing at random times when doing anything. Also happens in the projects I run as game.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Yeah it's a variant of the issue tracked in #75308 and https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/199 upstream.

Consolidating in #75308.
