### ISSUE TITLE
Adding uniform sampler2D on shader_type canvas_item, brakes and forceclose godot

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9143]
**Operating system or device - Godot version:**
Linux 64bit Ubuntu 16.04 - Godot 3.0 alpha commit a8a1f2e2a864e6b58d5bcf1c7e53a43cdb6d95d9

**Issue description:**
Adding uniform sampler2D on shader_type canvas_item, brakes and forceclose godot

**Steps to reproduce:**
create a scene with:
.- a Light2D
.- a Sprite with a texture and a Material (ShaderMaterial)

*The Light2D has a texture with alpha (point light from the godot demos)

*The Light2D mode is Add with white color and energy=1

*The texture for the Sprite is a diffuse texture and the ShaderMaterial code is:

shader_type canvas_item;
render_mode blend_add;
uniform sampler2D normal_tex;
void fragment(){
NORMAL = texture(normal_tex,UV).rgb * vec3(2.0,2.0,1.0) - vec3(1.0,1.0,0.0);
}

*The Shader Param "Normal Tex" is used to set the normal_map image of the diffuse texture

***The normal_map code is working, you can check this by:
*1- Chage the sprite texture to its normal_map texture
*2- Comment the line
//uniform sampler2D normal_tex;

*3- Change the code to:
NORMAL = texture(TEXTURE,UV).rgb * vec3(2.0,2.0,1.0) - vec3(1.0,1.0,0.0);

*Then the light and normal_map works but since we are using the normal_map as diffuse, it defeats the purpose, but you can check this way that NORMAL and TEXTURE are working

**Comment by rubenjavier** [comment]
This is sorta fixed now, the editor dont crash when adding an uniform sampler2D, but if the sampler 2D is used to modify "NORMAL" on the fragment, it gets ignored unless you previously set some texture to the new "Normal Map" dropdown on the Sprite GUI properties, as explained in https://github.com/godotengine/godot/issues/9263

**Comment by akien-mga** [comment]
Closing as the crash bug is fixed. The other issue you describe is already in #9263 I guess?
