### ISSUE TITLE
The new TilemapLayer node cannot cooperate with the NavigationRegion2D node to bake polygons

### ISSUE THREAD

**Issue by 874808039** [godotengine/godot#91444]
### Tested versions

Godot v4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5161) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/52156002/72564d13-fd73-42d0-bcce-d2fdef754ab0)
Collider in TilemapLayer cannot be baked with navigation polygons

### Steps to reproduce

As a child node of NavigationRegion2D, TilemapLayer makes some collision bodies and clicks the bake button

### Minimal reproduction project (MRP)

none

**Comment by 874808039** [comment]
Associate these two pulls：
https://github.com/godotengine/godot/pull/89179
https://github.com/godotengine/godot/pull/85856

**Comment by smix8** [comment]
The node parsing is bound to be removed from the navmesh generators and moved to the nodes so they are responsible for their own data.

This includes the new TileMapLayer nodes. Those new node types were added without updating the navmesh generators that still only looks for a TileMap node.

**Comment by 874808039** [comment]
> The node parsing is bound to be removed from the navmesh generators and moved to the nodes so they are responsible for their own data.
> 
> This includes the new TileMapLayer nodes. Those new node types were added without updating the navmesh generators that still only looks for a TileMap node.

Will scanning of TilemapLayer nodes be added in the future? In version 4.3

**Comment by smix8** [comment]
I am working on a PR that moves the parsing code for each node type from the navmesh generators to the actual nodes. That includes the new TileMapLayer nodes.
