### ISSUE TITLE
Godot 4 crash on launch?

### ISSUE THREAD

**Issue by senatabuchi** [godotengine/godot#91442]
### Tested versions

Reprodused in Godot4.2.2+ both NET and standard .
Does not reprodused in Godot LTS 3.5.2 .

### System information

Windows 11 , Godot 4.2.2+ both NET and standard , Forward+

### Issue description

Godot craches when I try to open the project on Godot 4 (including 4.2.2)
and leave the log below .
but it can be succesfully opened sometimes somehow .
LTS, 3.5.2 at this point works just fine on my laptop .
Im using 2021 omen 16 laptop with
AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz
Nvidia rtx3070 laptop gpu .
I,ve tried reinstall amd driver but nothing seems to change .
Someone please help me I really want to use this thing .

```
Source Godot Engine

Summary The application has stopped working.

Date 2024/05/02 11:01

Status Report has been sent.

Description Path of the application facing issues: C:\Users\senatang\Desktop\Godot_v4.3-dev6_mono_win64\Godot_v4.3-dev6_mono_win64\Godot_v4.3-dev6_mono_win64.exe

Problem Signature

Event Name: APPCRASH

Application Name: Godot_v4.3-dev6_mono_win64.exe

Application Version: [4.3.0.0](http://4.3.0.0/)

Application Timestamp: 00000000

Fault Module Name: amdxc64.dll

Fault Module Version: 31.0.21912.14

Fault Module Timestamp: 65cf0826

Exception Code: c0000005

Exception Offset: 00000000000a331f

OS Version: 10.0.22631.2.0.0.768.101

Locale ID: 1041

Additional Information 1: 1df8

Additional Information 2: 1df83248a89c18c140bf3f74642531a4

Additional Information 3: 0aec

Additional Information 4: 0aeca1d843d69be614fc5d8d048ec2a1

Additional Information Bucket ID: 397e82ac8b49196e0e419a4897fcf6c4 (2180193331202291396)
```

### What Ive already tried

1. Both of my cpu and gpu drivers are new .
2. Doesnt matter if I run as Admin .
3. run with command line only shows  
```
Editing project: C:/Users/senatang/Desktop/Godot projects/4.2.2
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org/
```
before the crash .

### Steps to reproduce

open the project manager -> click edit

### Minimal reproduction project (MRP)

[4.2.2.zip](https://github.com/godotengine/godot/files/15183993/4.2.2.zip)

**Comment by huwpascoe** [comment]
Best use the compatibility renderer for now.

Looks like there's some sort of buffer overrun happening with vulkan...

**Comment by senatabuchi** [comment]
> Best use the compatibility renderer for now.
> 
> Looks like there's some sort of buffer overrun happening with vulkan...

You,re right .Compatibility does work .
Its takes a bit more time to launch but acceptable .
Guess I have nothing to do with this issue since nobody know how to solve this .
Thanks for the reply though .It was such a torture digging this problem alone for days .
I feel like I've done my best .

**Comment by senatabuchi** [comment]
https://youtu.be/Rqj7Qn57Ku8?si=wL1tO1_wj5yUYzfd
I found the solution .

**Comment by huwpascoe** [comment]
> https://youtu.be/Rqj7Qn57Ku8?si=wL1tO1_wj5yUYzfd I found the solution .

well done!

Summarizing the video for future ref:

Windows 11 guesses which GPU to run the application on to save battery. There's a barely functional settings page to set this manually per app. Thank you Microsoft.
