### ISSUE TITLE
emission material will still contribute to giprobe when toggled off

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#9144]
**Operating system or device - Godot version:**
Godot 3.0 Win10 and Linux Mint

**Issue description:**
When a material has an energy value over 1 (and a color other than black), but the enabled flag is off it will still contribute light to the giprobe for baking.

![emission_bug](https://user-images.githubusercontent.com/7741669/27068286-a0af8b8e-5052-11e7-9f3b-80e57f158c83.jpeg)

**Steps to reproduce:**

Setup an emissive material as per normal, then toggle off the emission enabled flag. The object with this material will still contribute to gi, but the emissive material will not display on the object.

**Further ideas:**

After discussing this with reduz, it could be a good idea to have a flag (under Emission) that could be toggled to replicate this behaviour intentionally.

If this was taken to the next logical level, it would be very useful to be able to specify how bright the visible emission was, as compared to its gi energy contribution. When turning up the emission energy to get enough light it often results in the visible part of the object clipping to full white and losing any other surface properties (emission color, reflections) of the object.

If it were possible to have the visible emission as a separate slider to the gi contribution ,it would enable a wider variety of glowing and emission effects. While this may not be physically correct, it is more art directable and can look more attractive. If you look at a glowing light bulb in real life, you can still see the form(and writing etc) on the bulb, but in cg this is usually just an clipped/ overbright white.

In this example image, I have baked the scene with the emission energy of the balls material all on 8. After baking I have dialed the energy value down to 8/6/4/2 respectively, which can potentially give a more desired look(particularly the 2nd image) without the visible emission clipping to white. The only problem with doing this, is that upon subsequent rebakes you would have to manually tweak each emissive material back to this value. Not sure if this even possible with PBR but it would be very useful? Could also work the other way around...ie a low gi energy value for baking and then overcranking the visible value for an intentional overbright/clipped look.

![energy_visible_idea](https://user-images.githubusercontent.com/7741669/27068927-c964cb2c-5055-11e7-9387-ae9cddc70c3b.jpeg)

**Link to minimal example project:**

**Comment by reduz** [comment]
this is not a bug, this part of the information is baked. Might be doable in a far future, but definitely not for now. Kicking to 3.1 but it's unlikely to change soon

**Comment by tagcup** [comment]
Still, if the emission texture is disabled during the bake, it shouldn't contribute to GI, right?
The fix should be easy, so is it OK it I submit a PR for that?

**Comment by kubecz3k** [comment]
@Noshyaar not sure if you are the ghost, but maybe you know if something has changed with this issue? :)

**Comment by clayjohn** [comment]
This has been implemented in 4.0 :D 

GiProbes now allow you to dynamically change emission and they will update automatically.
