### ISSUE TITLE
SpriteFrames Close on Change

### ISSUE THREAD

**Issue by prof-nobody** [godotengine/godot#91452]
### Tested versions

- Happening Godot 4.3 dev 6

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.22011.1008) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

In the editor from AnimatedSprites2D opening SpriteFrames, if you create a new set of frames or if you edit the name of the sprite frames the SpriteFrames editor closes. You can reopen and progress is saved but it is still closing creating a not great workflow.

### Steps to reproduce

Create CharacterBody2d
Add child AnimatedSprite2D
Add New SpriteFrames to AnimatedSprite2D
Open the SpriteFrames and rename default

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/15187034/mrp.zip)

**Comment by prof-nobody** [comment]
Addition - if you add frames to the animations it does not continue to close. So it is only if you don't add any animations

**Comment by stephannv** [comment]
This is happening to me too on Mac OS:
Godot Engine v4.3.dev6.official.89850d553 
Vulkan 1.2.275 - Forward Mobile - Apple M1 Max

https://github.com/godotengine/godot/assets/3025661/4180de24-8384-4e32-a894-be2c39123f40

**Comment by liloso123** [comment]
same happens if you have sprites in it and just press the play and pause/stop buttons

**Comment by timothyqiu** [comment]
Thank you for the report, consolidating in:

- https://github.com/godotengine/godot/issues/92600

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
