### ISSUE TITLE
HTTPRequest doesn't work with some https servers.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#9146]
**Operating system or device - Godot version:**
linux 4.8, godot 2.1.3, godot tip

**Issue description:**

I made a simple test page, that demonstrates the effect:
https://www.capitanio.org/tests/godot/
A curl, wget, firefox, chromium, … doesn't have any problem,
so I think it's a godot issue. 

The URL https://www.capitanio.org/tests/godot/ok.html (apache server)
works fine, but the providers apache+php7 server for some reason doesn't
recognizes the godot's (ssl) request:  
```
extends HTTPRequest
request("https://www.capitanio.org/tests/godot/")
```
gives a response:
```
CERT STR: /CN=www.capitanio.org
VALID: 1
CONNECTION RESULT: 1
cert_ok: 1
result: 0
response_code: 400
headers: [Date: Tue, 13 Jun 2017 06:42:29 GMT, Server: Apache/2.4.25 (Unix), Content-Length: 362, Content-Type: text/html; charset=iso-8859-1, Vary: Accept-Encoding, Connection: close]
body.length: 362
body:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
</body></html>
```

This looks IMO correct:
```
diff --git a/thirdparty/openssl/ssl/ssl_lib.c b/thirdparty/openssl/ssl/ssl_lib.c
index 24be376..9e45af7 100644
--- a/thirdparty/openssl/ssl/ssl_lib.c
+++ b/thirdparty/openssl/ssl/ssl_lib.c
@@ -1052,6 +1052,14 @@ int SSL_write(SSL *s, const void *buf, int num)
         SSLerr(SSL_F_SSL_WRITE, SSL_R_PROTOCOL_IS_SHUTDOWN);
         return (-1);
     }
+
+    printf("XXXX SSL_write\n-=-");
+       for (int i = 0; i < num; i++) {
+               printf("%c", ((char *)buf)[i]);
+       }
+       printf("-=-\n");
+
+
     return (s->method->ssl_write(s, buf, num));
 }
```
prints out
```
XXXX SSL_write
-=-GET /tests/godot/ HTTP/1.1
Host: www.capitanio.org:443
User-Agent: GodotEngine/3.0.alpha.custom_build (X11)
Accept: */*

-=-
```

**Link to minimal example project:**

[network-test-gv3-02.zip](https://github.com/godotengine/godot/files/1070590/network-test-gv3-02.zip)

**Comment by bojidar-bg** [comment]
Here is what curl gives with `curl https://www.capitanio.org/tests/godot/ -v`:
```
> GET /tests/godot/ HTTP/1.1
> Host: www.capitanio.org
> User-Agent: curl/7.54.0
> Accept: */*
```

Here is the result of `curl www.capitanio.org:443/tests/godot/ -v` (NOTE: no `https://` in front)
```
> GET /tests/godot/ HTTP/1.1
> Host: www.capitanio.org:443
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Date: Tue, 13 Jun 2017 08:51:46 GMT
< Server: Apache/2.4.25 (Unix)
< Content-Length: 362
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
</body></html>
```

I captured the packed via wireshark (from both curl runs + godot), and it looks like this:
Godot:
![Godot wireshark screenshot](https://user-images.githubusercontent.com/5276727/27075421-bca07954-5032-11e7-8ada-98d87a01475a.png)
Curl proper:
![Curl wireshark screenshot](https://user-images.githubusercontent.com/5276727/27075453-da4ad90e-5032-11e7-9e27-7f0152d8d4c0.png)
Curl unproper:
![Curl wireshark screenshot](https://user-images.githubusercontent.com/5276727/27075467-e75b38c8-5032-11e7-8bec-584b8d5a4067.png)
Chrome:
![Chrome wireshark screenshot](https://user-images.githubusercontent.com/5276727/27075520-1aeefca6-5033-11e7-90e8-6ba8f3663d15.png)
(Note, I F4-ed the Godot game window to end it)

**Comment by capnm** [comment]
Thanks!
Taking a closer look, I see now the difference to the other clients.
Godot always appends the https stndard port to the Host-header
and apparently some 'sensitive?' servers don't like it.

```
curl -v https://capitanio.org:443/tests/godot/
curl -v https://capitanio.org/tests/godot/
```

both gives

```
> GET /tests/godot/ HTTP/1.1
> Host: capitanio.org
> User-Agent: curl/7.47.0
> Accept: */*
```
Somebody should perhaps RTF standards :)
but I think godot should anyway follow the others.
