### ISSUE TITLE
Area2D overlaps_area() bug with monitorable property

### ISSUE THREAD

**Issue by hormoz1** [godotengine/godot#9148]
**Operating system or device - Godot version:**
Godot 2.2 though i think the problem should be there for godot 2.1 too.

**Issue description:**
let's say we have two area2Ds named 1 and 2 and 2 is overlapping with 1.
while 2 is overlapping with 1, set the monitorable property of 1 to false and take 2 to a position that won't overlap with 1 if the monitorable property was set to true and set the monitorable property of 1 to true again.
now if you call the function overlaps_area for 2 for checking if it overlaps with 1 even though it isn't overlapping with 1, it returns true.

**Comment by Noshyaar** [comment]
Confirmed for 3.0-alpha a8a1f2e
The scene file: https://gist.github.com/Noshyaar/12030d240b5fcf55c267bf34efb8388e

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
Fixed by #22933.
