### ISSUE TITLE
Edited value is not reflected in the temporary Euler of the Quaternion Editor

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#91490]
### Tested versions

Don't reproduce in 4.2.2
Reproduce after 4.3.dev1

### System information

Any

### Issue description

Tweaking the Euler editor to change the Quaternion immediately discards the value and reverts back to the value before the change.

https://github.com/godotengine/godot/assets/61938263/bbeebb44-d02e-427c-ad32-fc2bb64d9aeb

### Steps to reproduce

Change Quaternion value with temporary Euler editor.

### Minimal reproduction project (MRP)

[quat.zip](https://github.com/godotengine/godot/files/15195083/quat.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #86266 as the culprit

![image](https://github.com/godotengine/godot/assets/44306054/5240f6d8-c1a9-421c-976d-450f476a5b65)
