### ISSUE TITLE
Allow change of constant Gravity (9.81)

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#9150]
**Operating system or device - Godot version:**
Godot 2.1.3 Steam Stable

It came to my attention that get_weight() is using a constant 9.81 to calculate weight. I would suggest that we allow users to change the gravity constant from within the Project Settings -> Physics 2D (I assume this is also needed in 3D).

**Hardcoded 9.81:**
https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp#L591

**Comment by eon-s** [comment]
If this uses the total gravity instead could be more useful, otherwise one is forced to use a custom integrator or register all the time the areas a body enter and exit to get the "real" weight.
