### ISSUE TITLE
error when changing TileMap to TileMapLayer

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#91504]
### Tested versions

4.3 dev 6

### System information

windows 10 vulkan foward+

### Issue description

Everything disapears 
when changing from tileMap to tileMapLayer

### Steps to reproduce

- add tileMap node
- place tiles on Fayehs
- changetype tileMap node to tileMapLayers

```
scene/2d/tile_map.cpp:415 - Index p_layer = 1 is out of bounds ((int)layers.size() = 1).
scene/2d/tile_map.cpp:139 - Index p_layer = 1 is out of bounds ((int)layers.size() = 1).
scene/2d/tile_map.cpp:415 - Index p_layer = 2 is out of bounds ((int)layers.size() = 1).
scene/2d/tile_map.cpp:139 - Index p_layer = 2 is out of bounds ((int)layers.size() = 1).
```

### Minimal reproduction project (MRP)

[tilelayerconvert.zip](https://github.com/godotengine/godot/files/15197077/tilelayerconvert.zip)

**Comment by groud** [comment]
Alright, so I opened #91760 to close this issue, which should fix the error message.

However, what you are doing is the wrong way to transform a TileMap into a TileMapLayer. Those are two nodes with a different set of properties, and they don't inherit from one another. So this option cannot work for what you seem to be trying to achieve.

What you should use is this option instead:
![Copie d'écran_20240509_142548](https://github.com/godotengine/godot/assets/6093119/4dbaddd9-ec9f-4841-a007-8d9b4c9d0c8b)

**Comment by jonSP12** [comment]
thanks
