### ISSUE TITLE
Renaming folder crashes Godot or message appears that the folder already exists (Godot v4.3 dev 6)

### ISSUE THREAD

**Issue by MatthiasBae** [godotengine/godot#91511]
### Tested versions

- Tested in 4.3 dev 6

### System information

Godot v4.3.dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5222) - 13th Gen Intel(R) Core(TM) i9-13900KF (32 Threads)

### Issue description

Renaming a folder the first time crashes Godot completely. It just closes. After opening and renaming folders again it says that (no matter what name you choose) that the folder already exists. But it still renames the folder

### Steps to reproduce

1. Create a project
2. Create a folder
3. Rename the folder

### Minimal reproduction project (MRP)

[foldertesting.zip](https://github.com/godotengine/godot/files/15200433/foldertesting.zip)

**Comment by MatthiasBae** [comment]
<img width="1179" alt="image" src="https://github.com/godotengine/godot/assets/52577744/484e03f3-5c01-41f5-a394-d5670f30a0a3">

**Comment by spiralhalo** [comment]
Supplementing the issue with my own experience:

- I got "A file or folder with this name already exists." with both folder ***and*** file renaming in `4.3 dev6`. Doesn't happen in `4.3 dev5`.

- The message only shows up if I confirm with ENTER. If I press ESC, the message doesn't show up even though the renaming still took place successfully.

**Comment by AThousandShips** [comment]
This should be solved on latest master after:
* https://github.com/godotengine/godot/pull/91112

**Comment by akien-mga** [comment]
Yes this should be fixed for Windows by #91112.

Still reproducible on Linux however, but I'll open a separate issue.
