### ISSUE TITLE
Visual Profiler logs error messages about capturing timestamps during compute list creation.

### ISSUE THREAD

**Issue by m4rr5** [godotengine/godot#91517]
### Tested versions

Reproducible in:
- v4.3.dev.custom_build [479b2ab77]
- v4.3.dev6.official [89850d553]

Not reproducible in:
- v4.2.2.stable.official [15073afe3]
- v4.0.stable.official [92bee43ad]

### System information

Godot v4.3.dev (479b2ab77) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.2824) - Intel(R) Core(TM) i9-14900KF (32 Threads)

### Issue description

When using the visual profiler, it spits out error messages about capturing timestamps during comput list creation not being allowed. Offending timestamps are "Filter Fog" and "Integrate Fog". The screenshot shows the exact messages and the location in the code.
![image](https://github.com/godotengine/godot/assets/446570/487bd86d-d43c-4b6c-9a1e-5ee0a227326e)

### Steps to reproduce

* Open the MRP.
* Run it.
* Click on the "Debugger" tab at the bottom of the IDE and then select the "Visual Profiler" tab.
* Hit the "Start" button to start the profiler.
* Now you see the errors in the "Errors" tab.
* They stop if you stop profiling or if you go to the WorldEnvironment and disable the "volumetric fog".

### Minimal reproduction project (MRP)

[godot-profiler-bug.zip](https://github.com/godotengine/godot/files/15201755/godot-profiler-bug.zip)

**Comment by clayjohn** [comment]
We've been discussing this on RocketChat and we have a tentative solution here: https://github.com/DarioSamo/godot/tree/timestamp_validation

**Comment by m4rr5** [comment]
I can confirm that the solution that @DarioSamo provided fixes this issue.
