### ISSUE TITLE
Unexpected Game Termination Without Error Indication When Inheriting Class Fails to Implement _get_plural_message Virtual Function

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#91524]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz (8 Threads)

### Issue description

I've been working on a project using the Godot Engine and encountered a potential bug during the customization of localization functionality that I'd like to bring to your attention for timely resolution.

Here's what's happening:
In my custom class MTranslation, which extends from the base Translation class, I have indeed overridden and implemented the _get_message method to suit specific localization needs. However, I did not implement the _get_plural_message virtual function alongside it. Upon running the game, instead of receiving an expected error message about the missing implementation, the engine fails to alert me and simply causes the game to crash without any warning.

### Steps to reproduce

Below is the relevant snippet of code:
```gdscript
extends Label

class MTranslation extends Translation:
	func _get_message(src_message: StringName, context: StringName) -> StringName:
		return &"ME"
	#func _get_plural_message(src_message: StringName, src_plural_message: StringName, n: int, context: StringName) -> StringName:
		#return &"ME"

func _init() -> void:
	var mt = MTranslation.new()
	mt.locale = "zh_CN"
	TranslationServer.add_translation(mt)

func _ready() -> void:
	TranslationServer.reload_pseudolocalization()
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Does it work correctly if you put the translation class in its own file? Inner classes has some problems and it's important to eliminate possible other issues

**Comment by 1419427247** [comment]
> 如果将翻译类放在自己的文件中，它是否能正常工作？内部类存在一些问题，消除可能的其他问题很重要

Oh wait, I just repeated the above steps in a new project, and now it's working properly again😐

**Comment by AThousandShips** [comment]
Then it is probably a bug somewhere else that showed up like this, if you can replicate it again in a new project please add those details, but otherwise I think this can be closed if there isn't any clear case in a new project

**Comment by 1419427247** [comment]
> 那么它可能是其他地方的一个错误，像这样出现，如果你可以在新项目中再次复制它，请添加这些细节，但除此之外，如果新项目中没有任何明确的情况，我认为可以关闭它

What you mentioned, I restarted Godot, and for some reason, this error seems to have disappeared, and I'm unable to reproduce it at the moment.
