### ISSUE TITLE
Running more than one viewport triggers an error in the Visual Debugger because you run out of max_timestamp_query_elements

### ISSUE THREAD

**Issue by m4rr5** [godotengine/godot#91531]
### Tested versions

Reproducible in:

v4.3.dev.custom_build [https://github.com/godotengine/godot/commit/479b2ab777188e21109bcfe803c2599c35bb9042]
v4.3.dev6.official [https://github.com/godotengine/godot/commit/89850d553eeb259e208d0c577cd7bc1eabd3a90a]

### System information

Godot v4.3.dev (479b2ab) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.2824) - Intel(R) Core(TM) i9-14900KF (32 Threads)  Issue description

### Issue description

When I run my game with more than one viewport active (a typical setup for a 3D racing game where another viewport is used to render mirrors and optionally two more for triple screen setups with 3 viewports instead of 1) and activate the Visual Debugger, I run into the issue that by default there are not enough timestamp query elements available (see screenshot). I've talked to @DarioSamo about this while discussing a fix for https://github.com/godotengine/godot/issues/91517 and the solution was to increase the limit from 256 (in rendering_device.cpp:4967 and in utilities.h:183) to 2048. He was not sure why the initial limit of 256 was chosen, so that is one question that needs to be answered. Another option we discussed in RocketChat was to make this setting configurable as a project setting (possibly requiring a restart of the editor). Open to other suggestions too obviously!

<img width="554" alt="capture_timestamp_2" src="https://github.com/godotengine/godot/assets/446570/fefb657b-8c8f-4a99-9849-3dbb2a2f1a4a">

### Steps to reproduce

I did not make a MRP as @DarioSamo claimed it would probably be overkill right now.

### Minimal reproduction project (MRP)

(see steps to reproduce above)

**Comment by clayjohn** [comment]
This line specifically would need to change to a project setting

https://github.com/clayjohn/godot/blob/c371381ffac34019b80968ee99a89b785471ed0c/servers/rendering/rendering_device.cpp#L5016
