### ISSUE TITLE
Open Script on Line number with EditorPlugin

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#9153]
**Operating system or device - Godot version:**
2.1.3 Steam Stable

Using [EditorPlugin](https://godot.readthedocs.io/en/stable/classes/class_editorplugin.html); 
May I suggest we add the option to open a script on a specific line?

This would be useful in the case of [Jahn's TODO plugin](https://github.com/need12648430/godot-todo)  - Instead of just opening the script, we could open it and navigate to a specific line number. :)

**Comment by vnen** [comment]
There's Go to Line already, shouldn't be hard to do.

**Comment by volzhs** [comment]
@vnen yes, but I guess @Tybobobo meant that there is no way to get script editor reference.

**Comment by Zylann** [comment]
Can the script editor be exposed to editor plugins instead of adding more functions to EditorPlugin?

**Comment by kubecz3k** [comment]
It seems we have not `ScriptEditor` that can be fetch from `EditorPlugin -> EditorInterface`. I guess it would be a good place to add such function.

**Comment by kareed44** [comment]
Is this a problem any more? I see that EditorInterface has a public get_script_editor() method that returns the ScriptEditor singleton.

**Comment by Zylann** [comment]
@kareed44 no, because although there is an API for the script editor, it still does not expose a way to open a script at a given line, or even just scroll the current `TextEdit` to that line.
