### ISSUE TITLE
Regression (v4.2.1): AnimationTree: animation_started signal is always emitted twice

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#91532]
### Tested versions

- Reproducible in v4.2.beta4.official [93cdacbb0], v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

This is a reboot of https://github.com/godotengine/godot/issues/80118 which was supposedly fixed in v4.2, but I experienced the issue in v4.2.1. Even v4.2.beta4 has the bug, so I'm not sure the fix really worked - or it worked for a very specific version only.

### Steps to reproduce

1. Download the MWE from https://github.com/godotengine/godot/issues/80118 (just upgrade it to v4.2)
2. Run the scene
3. Press Space / Enter to trigger ui_accept and see the 2x animated started + 1x animation finished message

### Minimal reproduction project (MRP)

Same as https://github.com/godotengine/godot/issues/80118

Here is a direct link for convenience: https://github.com/godotengine/godot/files/12229864/anim_tree_signal_bug.zip

**Comment by hsandt** [comment]
I wonder if the double signal emission is related to switching to RESET animation as an intermediate state... One could try to remove the RESET animation, see if it has any impact.

**Comment by TokageItLab** [comment]
Can't reproduce in master (4.3.dev6)

**Comment by hsandt** [comment]
OK, will build master and try again today.

**Comment by AThousandShips** [comment]
@hsandt does it still occur?

**Comment by oxeron** [comment]
I confirm I still have the issue in 4.2.2

**Comment by TheSofox** [comment]
Was able to confirm in v4.2.1.stable.official [b09f793f5]
![image](https://github.com/godotengine/godot/assets/3089525/38020c05-9f32-4a8e-9494-4836be2d8cd9)

But when trying in latest ( v4.3.beta.custom_build [25ff1306d] ) it doesn't seem present:
![image](https://github.com/godotengine/godot/assets/3089525/a966c9af-acdb-4f09-bbd7-54b3725abf55)

**Comment by TheSofox** [comment]
Unless someone can reproduce this, I recommend this issue be closed
