### ISSUE TITLE
AnimationPlayer "public state" is not updated when triggered by an AnimationTree

### ISSUE THREAD

**Issue by ubitux** [godotengine/godot#91533]
### Tested versions

v4.2.1.stable.arch_linux

### System information

Archlinux

### Issue description

When an `AnimationPlayer` state is changed by an `AnimationTree`, it is not reflected back to the public interface:

- calling `animation_player.is_playing()` always returns `false`
- signals such as `current_animation_changed` are never emitted

...even though the player is definitely playing and changing animations

### Steps to reproduce

- create a 3D scene
- add an animated model
- check `Editable children` on the added node so that its `AnimationPlayer` is visible
- add an animation tree
    + set `Tree Root` to `AnimationNodeStateMachine`
    + set `Advance Expression Base Node` to the root node of the scene
    + set `Anim Player` to the automatically added player
    + build a state machine that triggers an animation or two
- in the script, look at the `AnimationPlayer` state (see below for an example)
- observe that the `is_playing()` is always `false` and signals not emitted, even though the animations are playing

```gdscript
extends Node3D

@onready var anim = $cube/AnimationPlayer

var rotating: bool = false

func _process(delta):
	var is_playing = anim.is_playing()
	if is_playing:
		print("anim is playing")
	
	if Input.is_action_pressed("ui_accept"):
		rotating = not rotating
		print("rotating: ", rotating)

func _on_animation_player_current_animation_changed(name):
	print("current animation changed to: ", name)
```

### Minimal reproduction project (MRP)

[anim.zip](https://github.com/godotengine/godot/files/15204302/anim.zip)

**Comment by TokageItLab** [comment]
Same with https://github.com/godotengine/godot/issues/28311, not a bug; as AnimationTree just refer AnimationPlayer's AnimationList, don't play AnimationPlayer.
