### ISSUE TITLE
Inconsistent delta time from _process() when game window is moved

### ISSUE THREAD

**Issue by nicom7** [godotengine/godot#91548]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3], v4.2.1.stable.mono.official [b09f793f5], v3.5.3.stable.official [6c814135b]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

I noticed that the delta value passed in the `_process()` method in GDScript doesn't always correspond to a manually computed delta (calculated by subtracting current frame and previous frame `get_ticks_usec()` values). This is particularly noticeable when moving the game window or the mouse cursor while it is running.
Happens both when v-sync is enabled or disabled.

### Steps to reproduce

- Open the MRP and run the scene
- Notice how the error value (the difference between manual delta and process delta) in the console often gets over 5 ms when moving the game window continuously

### Minimal reproduction project (MRP)

[bug_process_delta.zip](https://github.com/godotengine/godot/files/15206529/bug_process_delta.zip)

**Comment by huwpascoe** [comment]
There's always going to be accumulated drift with delta time, it's a floating point number that compensates for varying frame rate.

Window movement events are usually costly so it's not surprising to see additional drift there. 

The mouse cursor however, that shouldn't be causing the same drift as a window movement. That's weird.

**Comment by nicom7** [comment]
Yes indeed it's more pronounced when moving the window than when moving the mouse cursor. So maybe that's not an issue if this is as expected.

**Comment by lawnjelly** [comment]
This is expected, the internal delta isn't measured at the same point you are measuring time in your script. It is measured prior to `_physics_process()` and a bunch of processing.

**Comment by AThousandShips** [comment]
Closing as per above, this is expected
