### ISSUE TITLE
Animation tracks at runtime not in same order as within editor.

### ISSUE THREAD

**Issue by KnightNine** [godotengine/godot#91546]
### Tested versions

v4.2.rc.custom_build [d34f1ec4b]

### System information

Windows 10  v4.2.rc.custom_build [d34f1ec4b]

### Issue description

Not sure if anyone noticed this or if it's already fixed in newer versions but the order of animation tracks does not persist when the scene is loaded in my project. The animation tracks that have to do with materials get pushed to the bottom making it hard to get/set the keyframes in these tracks by their index.

E.g. Here is an animation in my project, I marked the keyframe values of the first section/group. The following groups have the same keyframe values except for rotation:
![Animation track order](https://github.com/godotengine/godot/assets/34152090/89c09260-9cd0-48cd-8b68-658bcf9a02b6)

Then I wrote this code to get the order at runtime:
```gdscript
		var anim : Animation = anim_player.get_animation("Impact").duplicate()
		
		var test_val_arr = []
		var i = 0
		while i < anim.get_track_count():
			var j = 0
			var track_vals = []
			while j < anim.track_get_key_count(i):
				track_vals.append(anim.bezier_track_get_key_value(i,j))
				
				j+=1
			test_val_arr.append(track_vals)
			i+=1
		
		print(test_val_arr)
```

This prints out:
![Animation track order print](https://github.com/godotengine/godot/assets/34152090/4418b5b3-cd0f-47f5-b0c0-ee7194983579)

As you can see the [1,0] tracks are all pushed to the back of the array.

### Steps to reproduce

In an AnimationPlayer node:
Create an animation for several mesh nodes that modifies their materials and their transforms.
take note of the order of the tracks in the editor.
See that they are different at runtime using the code above.

### Minimal reproduction project (MRP)

should be easy enough to test.

**Comment by AThousandShips** [comment]
Can you try on an official build or a more recent branch? You're on a custom branch that's some 6 months old
