### ISSUE TITLE
Retargeting resets orientation of unmapped bones when `Overwrite Axis` is enabled

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#91558]
### Tested versions

v4.3.dev.custom_build [7ebc866418b075df58cbe4e31fcf8b0c3acd70a1]

### System information

Windows 11

### Issue description

Unmmaped bone orientations are lost (the `Basis` reset to identity) after import when retargeting if `Overwrite Axis` is enabled. It works as expected for mapped bones.

Left: correct orientation. Right: `Overwrite Axis` enabled

![image](https://github.com/godotengine/godot/assets/133662278/db86c029-43bc-487b-8c7f-1a0f0bccde80) ![image](https://github.com/godotengine/godot/assets/133662278/44010f11-f2fd-4e2a-98f0-2e7dd07a7035)

Disabling this option keeps their orientation but then retargeting is meaningless because differences in mapped bone and animation rotations between characters aren't normalized.

### Steps to reproduce

* In the MRP, open `main.tscn`.
* In the advanced import setting for `bot.glb`, `Skeleton3D > Retarget > Rest Fixer > Overwrite Axis` is enabled. Rotation reset for the unmapped bones with attachments.
* Disable `Overwrite Axis` and reimport. It keeps rotation.

### Minimal reproduction project (MRP)

[overwrite-rotation.zip](https://github.com/godotengine/godot/files/15209810/overwrite-rotation.zip)

**Comment by lyuma** [comment]
Just to be clear, this is not a regression. The same behavior has existed since Godot 4.0 was released through now.

I want to understand the implications of this issue bit better. In particular, bone hierarchies of intermediate bones (e.g. Arm twist) might want to be treated differently from bone hierarchies of attachments (hair, clothing, end/tip bones)

**Comment by ydeltastar** [comment]
The issue is due to treating the bones the same. Loose bones for attachments are treated the same as intermediate bones and reset, despite having no effect on the retargeted pose.
