### ISSUE TITLE
Animation Playback Track not calling Play on target AnimationPlayer with timestamp 0

### ISSUE THREAD

**Issue by TheOrioli** [godotengine/godot#91554]
### Tested versions

- v4.3.dev6.official [89850d553]
- v4.2.2.stable.mono.official [15073afe3]
- v4.1.3.stable.mono.official [f06b6836a] <- issue is not reproducible in this version

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5212) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

It seems that the `AnimationPlaybackTrack` doesn't call Play properly on the targeted AnimationPlayer if the track keyframe is set to 0. 

Adjusting to 0.001 seconds works.
The issue doesn't appear in v4.1.3

### Steps to reproduce

1. Open MRP
2. Using the `PlayThisAnimationPlayer` play the `broken` animations.
3. Notice that the `Label` text doesn't change during the first value in the animation track
4. Play the animation called `non_zero_start_work` 
5. Notice that the `Label` text changes

### Minimal reproduction project (MRP)

[animationtrack-repro.zip](https://github.com/godotengine/godot/files/15209181/animationtrack-repro.zip)

**Comment by AThousandShips** [comment]
Sounds like the same as:
* https://github.com/godotengine/godot/issues/90864

**Comment by TheOrioli** [comment]
Is https://github.com/godotengine/godot/pull/90960 included in v4.3.dev6.official?

**Comment by AThousandShips** [comment]
No it was merged after

**Comment by TheOrioli** [comment]
I'll give this a test tomorrow on `master` in that case 👍

**Comment by TheOrioli** [comment]
Fixed on master 🙌
