### ISSUE TITLE
PS5 controller recognized as "DualSense Wireless Controller" instead of PS5 Controller as described in the SDL2 game controller database

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#91568]
### Tested versions

Tested in 4.3.dev4, 4.3.dev5 and 4.3.dev6,

### System information

macOS Monterey 12.6.5

### Issue description

In Godot 4.2 version, before the rework of controllers, the PS5 controller name was PS5 Controller. In the latest 4.3dev versions, it is DualSense Wireless Controller. It seems to be pretty accurate but it doesn't follow the name in the SDL2 game controller database as described in the Godot documentation, which is PS5 Controller.

### Steps to reproduce

- Plug a PS5 controller
- Print the name in a script by doing this: `print(Input.get_joy_name(0))`
- It will print "DualSense Wireless Controller"

### Minimal reproduction project (MRP)

Any project can reproduce this issue using the small piece of code provided previously.

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/87925 should address this.

**Comment by Cronos87** [comment]
It seems to be related indeed. Thank you for pointing out this issue! I can close this one :)

**Comment by bruvzg** [comment]
macOS (and iOS) uses `GameController` API directly, it's not interacting with SDL database in any way.

**Comment by Cronos87** [comment]
Maybe that would be a good idea to indicate this in the documentation somewhere. Neither on website and in the editor it is indicated that macOS doesn't use the SDL database.
