### ISSUE TITLE
[3.0] Image get_rect

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9156]
get_rect returns incomplete sub image when the rect.position is > (0, 0)
![test](https://user-images.githubusercontent.com/4741886/27092723-8dece64c-5064-11e7-84d8-5126bda11963.png)

It should look like this

![image](https://user-images.githubusercontent.com/4741886/27092746-a8b3976e-5064-11e7-9958-dd4cba3d2979.png)

Part of Spritesheet

![image](https://user-images.githubusercontent.com/4741886/27093078-b14c674c-5065-11e7-8013-76eeb0109ab6.png)

```
func _ready():

	var it = ImageTexture.new()
	it.load("res://spritesheet.png")
	
	#save sub image
	var rect = Rect2(10, 0, 32, 32)
	var sub_image = it.get_data().get_rect(rect)
	sub_image.save_png("res://test.png")
```

OS: windows
master branch

**Comment by akien-mga** [comment]
Fixed by #9175.
