### ISSUE TITLE
Project Manager "Filter Projects" search gets stuck on empty input

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#91562]
### Tested versions

7ebc866
4.3dev6+

### System information

Windows 10

### Issue description

When entering a space " " as the first input inside the "Filter Projects" search the search gets stuck in an endless loop that makes the Godot Project Manager unresponsive.

This also happens after searching and clearing all the input again in the LineEdit.

After minutes of waiting it does still not recover so the only way to get out is to kill the Godot task process.

Just for comparison entering a "valid" single letter in the search results in an instant search finished and I have a few hundred projects for Godot so search.

### Steps to reproduce

Click in the Godot Project Manager "Filter Projects" LineEdit and hit space.

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
Worth checking it isn't one of the bugs fixed in #88943 for 3.x (I gather 4.x is different, but it looks potentially susceptible to invalid iteration of children from a quick look).

**Comment by jsjtxietian** [comment]
Did not reproduce with Godot v4.3.dev (7ebc86641) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

Can this issue be related to certain project names?

**Comment by smix8** [comment]
Issue disappeared after nuking the entire Godot cache. Can't reproduce with a fresh Godot_v4.3-dev6 so closing.
