### ISSUE TITLE
create_multiple_convex_collisions() is ignoring MeshConvexDecompositionSettings.

### ISSUE THREAD

**Issue by eddieataberk** [godotengine/godot#91578]
### Tested versions

Reproducible in 4.2 and 4.3 dev

### System information

Windows 10

### Issue description

create_multiple_convex_collisions always generating a single collision there are no differences when we use the MeshConvexDecompositionSettings either

```
var decomposition_settings :=  MeshConvexDecompositionSettings.new()
decomposition_settings.max_convex_hulls = 16
mesh.create_multiple_convex_collisions(decomposition_settings)
```

and 

`mesh.create_multiple_convex_collisions()`

producing the same result.

### Steps to reproduce

var decomposition_settings :=  MeshConvexDecompositionSettings.new()
decomposition_settings.max_convex_hulls = 16
mesh.create_multiple_convex_collisions(decomposition_settings)

### Minimal reproduction project (MRP)

N/A

**Comment by rburing** [comment]
What is the input mesh? And what is the problem? The method does a decomposition of the mesh into convex shapes, so if the input mesh is convex then the result will be one convex shape...

**Comment by eddieataberk** [comment]
> What is the input mesh? And what is the problem? The method does a decomposition of the mesh into convex shapes, so if the input mesh is convex then the result will be one convex shape...

its the same for all the meshes i tried. calling it from Mesh dropdown menu
![image](https://github.com/godotengine/godot/assets/48696693/d3f912c9-9c67-4bb8-9a20-1ba2c1f509cd)

vs. calling it from code
![image](https://github.com/godotengine/godot/assets/48696693/25dfd086-6cfb-45f7-936a-80793f41b0aa)

**Comment by eddieataberk** [comment]
nvm solved the issue it seems `decomposition_settings.max_concavity = 0` solves the issue. which is set to 1 by default

**Comment by Sauermann** [comment]
Closing according to the previous post.
