### ISSUE TITLE
Dimmed splash screen on Android

### ISSUE THREAD

**Issue by lazyvainglory** [godotengine/godot#91576]
### Tested versions

Reproducible on Godot 4.2.1 stable.

### System information

Windows 11, JDK 17(Also tried JDK 22), Android SDK Build Tools 33 

### Issue description

Exporting to android shows a very dimmed splash screen.

### Steps to reproduce

Create a project with mobile renderer.
Add your android preset in export.
Enable Import ETC2 ASTC in VRAM Compression.
Provide unique package name.
Export the project or run a remote debug.
Launch the app.

Expected Result: Bright or at least color accurate splash screen image would appear when you launch the app.
Actual Result: Very dim splash screen image

### Minimal reproduction project (MRP)

I believe this isn't project dependent but just in case the project below should be dim.

[Dim Splash Screen.zip](https://github.com/godotengine/godot/files/15211843/Dim.Splash.Screen.zip)

**Comment by Alex2782** [comment]
It is probably this function. I'm not sure yet whether it will be activated before the splash screen.

-----------
![Bildschirmfoto 2024-05-05 um 15 01 08](https://github.com/godotengine/godot/assets/41921395/ca21fb62-069b-4363-8f08-1b222c8dd116)

https://github.com/godotengine/godot/blob/7ebc866418b075df58cbe4e31fcf8b0c3acd70a1/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L479

**Comment by lazyvainglory** [comment]
I just tested on version 4.2.2, and the issue also exists there. Someone in the forum suggested changing to gl_compatibility, but it did not work for me. I wonder if there is a temporary workaround.

**Comment by Alex2782** [comment]
Can you also reproduce it if you **override** the splash screen? Use a different image file and display it for longer.  For example 3000 ms, does the splash screen remain dark for 3 seconds?

![Bildschirmfoto 2024-05-07 um 18 44 27](https://github.com/godotengine/godot/assets/41921395/7d47a381-8ed5-4c41-a73b-0ca704423e1d)

**Comment by Calinou** [comment]
>  Enable Import ETC2 ASTC in VRAM Compression.

This may be the issue. I don't think VRAM-compressed splash screen images can be correctly displayed.

Try using lossless compression instead. The difference in memory usage is pretty low since it's just a single image, and it's only displayed during startup.

**Comment by lazyvainglory** [comment]
@Alex2782 So I tried what you suggested, but I extended the duration to 10 seconds just to exaggerate the result. Apparently, the splash image only appears for a split second. When I slowed down the recording, it was visible only until the app became full screen. By the way, it’s also dim during the time it appeared. 

https://github.com/godotengine/godot/assets/45304248/5e9043f8-b80f-4e2a-a9ed-e05e27511021


I also discovered an inconsistency with the splash image size as well. However, since it has already been discussed [here](https://github.com/godotengine/godot/issues/69317), I won’t delve into it any further.

@Calinou I tried both the default and custom splash images. Additionally, I ensured that their compression is lossless, but they still appear dim.

**Comment by Calinou** [comment]
I get what's happening now, based on the video output. The splash screen is actually black all along. The image you're seeing for a split second when opening the app is Android's own placeholder image, which is a static image defined in the APK and not something drawn by Godot.
