### ISSUE TITLE
In 4.3 dev 6, GetTree().Root...missing Node.

### ISSUE THREAD

**Issue by teamjistory** [godotengine/godot#91585]
```
public void StartGameAsMainMenu()
	{
		GameState = Enum_GameState.Main_Menuing;

		if (MainMenu != null && MainMenu.IsInsideTree())
		{
			GetTree().Root.CallDeferred("remove_child", MainMenu);
			MainMenu = null;
		}

		MainMenu = _MainMenu.Instantiate();
		GetTree().Root.CallDeferred("add_child", MainMenu);
	}


GetTree().Root.CallDeferred("add_child", MainMenu);
```

===> MainMenu is null

### System information

GetTree().Root.CallDeferred("add_child", MainMenu);  ===> MainMenu is null

### Issue description

GetTree().Root.CallDeferred("add_child", MainMenu);

===> MainMenu is null

### Steps to reproduce

GetTree().Root.CallDeferred("add_child", MainMenu);

===> MainMenu is null

### Minimal reproduction project (MRP)

GetTree().Root.CallDeferred("add_child", MainMenu);

===> MainMenu is null

**Comment by AThousandShips** [comment]
Please fill in all the sections properly, or ask in the [forums](https://forum.godotengine.org/) if you are looking for support, this is for reporting bugs

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
