### ISSUE TITLE
Exporting an iOS plugin with debug configuration causes symbol not found compile error

### ISSUE THREAD

**Issue by webair** [godotengine/godot#91583]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.4.0 - Vulkan (Mobile) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

I'm creating an iOS plugin for Godot based on the project [godot-ios-inapp-review-plugin](https://github.com/cengiz-pz/godot-ios-inapp-review-plugin) as template. I managed to build the plugin successfully using the 'release' configuration. But unfortunately i am not able to compile the resulting xcode project when exporting with 'debug' configuration. i receive following error:

```
Undefined symbol: ClassDB::bind_methodfi(unsigned int, MethodBind*, bool, char const*, Variant const**, int)
Linker command failed with exit code 1 (use -v to see invocation)
```

I tried to resolve the issue but i am a little lost. Has anyone a hint for me?

### Steps to reproduce

- Create a godot project using godot 4.2.1
- Install export template for ios (Valid 'App Store Team ID' and 'Bundle Identifier' required)
- Download  [ios.zip](https://github.com/godotengine/godot/files/15213560/ios.zip) and extract it in root of project
- In the iOS export settings under plugins activate the 'QrCodeScanner" Plugin
- Export project using "Export with Debug"
- Try to compile with exported Xcode project

### Minimal reproduction project (MRP)

N/A

**Comment by TheOathMan** [comment]
Same issue.

Official ios Plugins was tested with Godot v4.2.2.stable.official, and asset store ones (share plugin)

System:
MacBook Air (13-inch, 2017)
Mac version 12.6.2
Xcode version: Version 14.2

The build failed while building archive in Godot. In Xcode, failed during build (when 'Export Project only' is Enabled from Godot export settings).



`The following build commands failed: 	Ld /Users/main/Library/Developer/Xcode/DerivedData/testingg-gvofzswuhtpjdaeytstoiuocytua/Build/Intermediates.noindex/ArchiveIntermediates/testingg/InstallationBuildProductsLocation/Applications/testingg.app/testingg normal (in target 'testingg' from project 'testingg') (1 failure) `

This is while building on Godot. But Xcode gave extra details:

`clang: error: no such file or directory: '/Users/main/Desktop/Godot_Builds/forXcode/testingg/ios/plugins/SharePlugin.release.a' 
`

**Comment by webair** [comment]
@TheOathMan I think the share library has an other issue. According to the error message it seems like that the static library for SharePlugin.release.a is missing. 

Since I am currently focusing on the iOS plugin build process, I may be able to help resolving the issue here.

**Comment by TheOathMan** [comment]
> @TheOathMan I think the share plugin has an other issue. According to the error message it seems like that the static library for SharePlugin.release.a is missing. 
> 
> Since I am currently focusing on the iOS plugin build process, I may be able to help resolving the issue here.

The issue you have and the issue I have are exactly the same but the error messages isn't clear.
When we try to build an ios plugin, we usually include Godot headers. These headers include c++ definitions that are not implemented in the final build. Specifically from object.h (maybe from other headers as well). So when we include the plugin, and we start the export, the linker starts to look for the implementation for these included definitions but doesn't find them.

Right now, I was able to solve your issues by declaring these macros:

![PXL_20240506_084214664.jpg](https://github.com/godotengine/godot/assets/57967535/314978e1-d4e9-43ce-95fe-7071a73d7583)

**Comment by webair** [comment]
@TheOathMan Thanks for clarification! This actually led me to the solution. ;) I simply needed to add the variable         GCC_PREPROCESSOR_DEFINITIONS="DEBUG_ENABLED=1" in the xcodebuild commands for the debug builds. So my xcodebuild for debug framework looks like this now:

```shell
    xcodebuild clean archive \
        -project "${xcodeproj_dir}" \
        -scheme "${plugin_name}" \
        -archivePath "${out_lib_dir}/ios_debug.xcarchive" \
        -sdk iphoneos \
        SKIP_INSTALL=NO \
        GCC_PREPROCESSOR_DEFINITIONS="DEBUG_ENABLED=1"
```

Thanks again and hope this helps to resovle your issue.
