### ISSUE TITLE
Frame time widget won't stay still when using a custom editor font

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#91586]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

https://github.com/godotengine/godot/assets/60579014/ebcf85b4-2dd8-42ff-b7a2-02eaff3954b2

Doesn't look great because it's flickering even though the number of digits doesn't change. Maybe it needs a minimum width or something like that (Or it could use the monospace font)

### Steps to reproduce

Use the [Inter](https://fonts.google.com/specimen/Inter) font

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Today I learned Noto Sans'[^1] digits are effectively monospace. :eyes: 

[^1]: The default editor font.
