### ISSUE TITLE
TouchScreenButtons ignore Shape when Passby Press is enabled

### ISSUE THREAD

**Issue by Danathus** [godotengine/godot#9159]
**Operating system or device - Godot version:**
Found on Windows & Android w/ Godot 2.1.3 stable.

**Issue description:**

When passby press is enabled, TouchScreenButtons ignore shapes. This is pretty clear in the code -- in `TouchScreenButton::_input()`, `shape` is only referenced in the block where `passby_press` is `false`.

**Steps to reproduce:**
1) Create a TouchScreenButton with a Normal image set.
2) Give it a Shape that should be easy to touch, with an area expanding beyond the image dimensions.
3) Wire something up so that you know when the button is successfully pressed.
4) Make sure Passby Press is disabled.
5) Run/play to confirm that you can press the button successfully, touching anywhere within the Shape boundaries.
6) Enable Passby Press.
7) Run/play again and observe that you can only press the button by touching the Normal image, not by hitting within the Shape boundaries.

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
Ping @RandomShaper.

**Comment by Danathus** [comment]
Pulled tip of 2.1 branch, with this fix applied. Built and ran on Windows with MSVC 2017.

Ran in Windows on debugger -- looks like it works.

Ran on Android, and it _does not work_! Touch area seems to still be derived from the image as before, and NOT to the shape. @RandomShaper

Not sure why the discrepancy between the Windows version and the Android version, but there it is.

**Comment by akien-mga** [comment]
Just to be sure, did you rebuild the android export template with the same commit, and update your installed templates before exporting?

**Comment by RandomShaper** [comment]
Also make sure you are not being affected by a bug in the build system (now
fixed, but with perdurable effects) by removing the Android build dir
completely.

**Comment by Danathus** [comment]
Thanks guys, my problem was indeed not having built for Android. I have now built the 2.1 branch for Android, and hooked up the Godot editor to use that, and now lo and behold the problem is fixed.

Sorry for the newb mistake, and thank you for fixing the bug! I consider this case closed.
