### ISSUE TITLE
Regression 4.3dev6: When selecting multiple MeshInstance3D, menu Mesh is not available

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot#91592]
### Tested versions

4.3dev6

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4626) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

In 4.2.2, we could select multiple MeshInstance3D and use the Mesh menu. This was incredibly useful for batch processing such as creating simple colliders for hundreds of mesh in a modular kit (i.e. for a Gridmap):
![multi-editing-mesh-4 2](https://github.com/godotengine/godot/assets/10520249/fd4fe594-8a8e-4023-9161-1259d59c0f96)

In 4.3dev6, the Mesh menu disapears when we select more than one Mesh; which prevents batch processing:
![multi-editing-mesh-4 3dev6](https://github.com/godotengine/godot/assets/10520249/de4f98ec-e79f-4bdf-8620-ab8f8ff6b645)

I am really excited about #86627 by the way!

### Steps to reproduce

See GIF above.

### Minimal reproduction project (MRP)

You just need to create a couple of MeshInstance3D with a MeshBox as shape.

**Comment by matheusmdx** [comment]
Bisecting leads to #89179 as the culprit

Revert this part of code in editor_node.cpp solves the problem
![image](https://github.com/godotengine/godot/assets/44306054/90aba04c-bb02-4f18-bb67-86e6195d0195)

**Comment by akien-mga** [comment]
CC @groud @KoBeWi

**Comment by KoBeWi** [comment]
The Mesh menu did appear, but only one option is functional with multiple nodes 🙃 This regression can be considered a bugfix.
