### ISSUE TITLE
Dictionaries don't respect insertion order

### ISSUE THREAD

**Issue by Elinvention** [godotengine/godot#9161]
**Operating system or device - Godot version:**
Godot 3.0

**Issue description:**
Dictionaries don't respect insertion order, but 0a59c3c3a6a8c13a5c82d59d9587fca31f900604 claimed they should.

**Steps to reproduce:**
```
var dict = {"C": 1, "B": 2, "A": 3}
print(dict)
(A:3), (B:2), (C:1)
for k in dict:
	print(k)
C
A
B
```

**Comment by Zireael07** [comment]
Have you tried for in in range dict.size() ?

**Comment by PLyczkowski** [comment]
@Zireael07 You mean like:
![shot_170622_122031](https://user-images.githubusercontent.com/7307968/27429721-6109cb0c-5746-11e7-9bab-24a9a6349057.png)
That doesn't work as well.

**Comment by bojidar-bg** [comment]
I think dicts do respect order (when iterated directly), but not when calling `dict.keys()` or printing. Correct?

**Comment by PLyczkowski** [comment]
@bojidar-bg How **do** you iterate directly through a dictionary? I only know of accessing values by keys, or iterating by keys as in example above.

**Comment by bojidar-bg** [comment]
Wait, just tested it myself, doesn't work either... My bad.
```gdscript
var dict = {c = 2, a = 3, b = 1, rainbow = "correct", bowrain = "incorrect", d = 4}
for key in dict:
	print(key)
```
Produces (in a 3.0 build):
```
c
d
a
bowrain
rainbow
b
```
Which is not correct, at all.

**Comment by kaozdl** [comment]
i don't think dictionaries are meant to have an order

**Comment by bojidar-bg** [comment]
They have one in 3.0 though, so, this was closed 😃
