### ISSUE TITLE
LightmapGI: Stripes on curved surfaces

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#91614]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

I'm getting weird stripes when baking some geometry with LightmapGI and I can't get rid of them by tweaking any settings.

I first reported this in https://github.com/godotengine/godot/issues/90929 but I'm opening a separate issue for this as suggested by @lander-vr, because this seems to be a separate issue

<img width="1226" alt="image" src="https://github.com/godotengine/godot/assets/60579014/b5d20e5e-e34b-4146-98f4-988190b7efb6">

<img width="1224" alt="image" src="https://github.com/godotengine/godot/assets/60579014/9c44ef60-4314-451c-8fd1-23391f3850d3">

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[MRP_lightmap_stripes.zip](https://github.com/godotengine/godot/files/15292112/MRP_lightmap_stripes.zip)

**Comment by DarioSamo** [comment]
As I said in the issue, how was the shape generated? Can you compare the result to when you do it from importing an OBJ?

**Comment by lander-vr** [comment]
These are really strange artifacts:
![image](https://github.com/godotengine/godot/assets/31851431/27a43916-b38a-44e6-ae98-cc011b6e6c7e)

It looks like it's happening after denoising and dilation. Changing denoising parameters doesn't affect the shape, but does make it smoother. The dilated pixels themselves look normal to me.

After denoising:
![image](https://github.com/godotengine/godot/assets/31851431/1e6239b0-2fdc-49f2-b1a0-9ef1f616b281)

Using a higher texel scale, those bands remain at the same width of 3 pixels.

**Comment by passivestar** [comment]
> As I said in the issue, how was the shape generated? Can you compare the result to when you do it from importing an OBJ?

I imported gltf. Both gltf and the blend file that it came from are in the MRP

**Comment by DarioSamo** [comment]
> I enabled debug_textures in lightmapper_rd. It seems to happen during the blendseams step.

Interesting. I haven't really delved into the seams blend step yet so I can't give much info about that.

**Comment by passivestar** [comment]
Also encountered it on beveled geometry, so it's not limited to concave shapes. Only sharp edges currently bake with no bugs. Updated the MRP to include this

<img width="1224" alt="image" src="https://github.com/godotengine/godot/assets/60579014/9c44ef60-4314-451c-8fd1-23391f3850d3">

**Comment by lander-vr** [comment]
Paging @reduz since he implemented the lightmapper (along with the blendseams step). Maybe he's got some ideas on what may be happening here. It would be nice to also hear what the blendseams step is trying to achieve.
To me the lightmaps seem to look fine after the secondary pass as is, so it might be worth exploring some bakes without the blendseams step. That said though, that may be a naive suggestion because I don't really understand blendseams.

**Comment by passivestar** [comment]
https://github.com/godotengine/godot/blob/78cce1954ddb6fefb90b33742215f304ec7b0b94/modules/lightmapper_rd/lm_blendseams.glsl#L102

This is what `lm_blendseams.glsl` draws in debug mode:

<img width="500" alt="image" src="https://github.com/godotengine/godot/assets/60579014/2cdbee49-0b13-4bcc-aff3-441c7e2aff32"><br>

The sharp edge might mean that it's using a wrong uv offset when blending

This is the part of the shader that blends lines:

https://github.com/godotengine/godot/blob/78cce1954ddb6fefb90b33742215f304ec7b0b94/modules/lightmapper_rd/lm_blendseams.glsl#L44-L70

These are the stages that blend seams in lines mode using that shader:

https://github.com/godotengine/godot/blob/78cce1954ddb6fefb90b33742215f304ec7b0b94/modules/lightmapper_rd/lightmapper_rd.cpp#L1929-L1939

https://github.com/godotengine/godot/blob/78cce1954ddb6fefb90b33742215f304ec7b0b94/modules/lightmapper_rd/lightmapper_rd.cpp#L1951-L1963

**Comment by passivestar** [comment]
> It would be nice to also hear what the blendseams step is trying to achieve

Without it you get... seams

<img width="400" alt="image" src="https://github.com/godotengine/godot/assets/60579014/8cb2aa70-1eb8-4127-9f67-e643d5c57a16"><br>

BTW even when it's not doing the "same color for the entire stripe" artifact, it's still not doing a super great job at blending seams:

<img width="400" alt="image" src="https://github.com/godotengine/godot/assets/60579014/d47be720-4a6b-4920-8f19-a99e8a8ccd51"><br>

This is what it looks like when you don't blend with original color (if you swap this for `Vector3(0, 0, 1.0)`):
https://github.com/godotengine/godot/blob/78cce1954ddb6fefb90b33742215f304ec7b0b94/modules/lightmapper_rd/lightmapper_rd.cpp#L1918

<img width="400" alt="image" src="https://github.com/godotengine/godot/assets/60579014/dd459ee1-8f70-465b-81db-980e6ed43c41"><br>

I also had some artifacts before where individual triangles of a mesh got outlined with stripes. So there's more than one problem to solve with seam blending

**Comment by Lateasusual** [comment]
> BTW even when it's not doing the "same color for the entire stripe" artifact, it's still not doing a super great job at blending seams
It doesn't seem like the colour actually is the same for the whole stripe, that's an optical illusion due to the gradient :)
The main issue here is that the seam indexing is wrong, and some seams are back to front. Flipping the seam UV on the X axis fixes all the seams in those screenshots, but all the *other* seams broken become broken in the exact same way.

**Comment by passivestar** [comment]
> It doesn't seem like the colour actually is the same for the whole stripe

Yeah you're right I just double checked at 100% opacity, they aren't single color
