### ISSUE TITLE
Godot 4 lighting issue when using shader material

### ISSUE THREAD

**Issue by Foyezes** [godotengine/godot#91626]
### Tested versions

4.3 dev5 and 3.4 dev4. 

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21910.5) - Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 Threads)

### Issue description

when using visual shader to create some grass and using omnilight to light the grass, from most angles it looks very white, but the trees near the grass look fine, those are standard materials. from certain angles the grasses look ok but from other angles they appear very white. like I mentioned this happens only when using shader material and not standard material.

MAIN ISSUE: In the last picture I'm using spotlight and shadermaterial for the grass. There's a clear split between light and darkness. It happens when using directional, omni or spotlight.

![2](https://github.com/godotengine/godot/assets/106163842/560b5b59-0618-4646-884d-5401b7d2157c)
![3](https://github.com/godotengine/godot/assets/106163842/26909fdf-967b-47d7-a5e8-bdf3fa07a173)
![1](https://github.com/godotengine/godot/assets/106163842/4af907f9-42fe-4a06-a13e-de18a18df019)
![4](https://github.com/godotengine/godot/assets/106163842/f58113f9-9aa4-42e4-84ad-1bc3fcf7a5b8)

FIXED (Issue with the alpha map): 

![image](https://github.com/godotengine/godot/assets/106163842/05c0ab38-9386-4955-8475-946d32a32a76)

![image](https://github.com/godotengine/godot/assets/106163842/cf15b6ec-0b65-483b-8aa5-8ead4c21f1db)

![image](https://github.com/godotengine/godot/assets/106163842/33dcdb6d-fd9a-407c-ba6a-1be60f062380)

### Steps to reproduce

creating a shape with shader mat and a directional light will recreate the issue

### Minimal reproduction project (MRP)

screenshots of the MRP can be found in screenshots folder. if the camera is in the center of plane and rotated around the lighting goes from dark to light and when looking at the plane from top down a line can be seen running through the mesh.

[lightingbug.zip](https://github.com/godotengine/godot/files/15224561/lightingbug.zip)

**Comment by Zireael07** [comment]
Please upload an MRP

**Comment by Foyezes** [comment]
Update: It turns out the whiteness of the grass blades is caused by alpha issues, the edges were white so it made it seem the whole blades were white. But there issue when with directional light and shader material still persists. I've updated the screenshots.

**Comment by Foyezes** [comment]
> Please upload an MRP

https://github.com/godotengine/godot/issues/91626#issuecomment-2104516070

**Comment by clayjohn** [comment]
Thank you for adding an MRP. I took a look and quickly found the issue. 

You are writing the normal map into the "normal" property" instead of the "normal map" property. 

![Screenshot from 2024-05-15 12-39-25](https://github.com/godotengine/godot/assets/16521339/81e73d40-001c-4406-b164-6e1c206061dc)

Properly using the "normal map" property fixes the issue
![Screenshot from 2024-05-15 12-39-28](https://github.com/godotengine/godot/assets/16521339/94bf89f1-94a3-4113-9bde-9629f6a708b0)

**Comment by Foyezes** [comment]
> Thank you for adding an MRP. I took a look and quickly found the issue.
> 
> You are writing the normal map into the "normal" property" instead of the "normal map" property.
> 
> ![Screenshot from 2024-05-15 12-39-25](https://private-user-images.githubusercontent.com/16521339/330938454-81e73d40-001c-4406-b164-6e1c206061dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDI5NzQsIm5iZiI6MTcxNTgwMjY3NCwicGF0aCI6Ii8xNjUyMTMzOS8zMzA5Mzg0NTQtODFlNzNkNDAtMDAxYy00NDA2LWIxNjQtNmUxYzIwNjA2MWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE5NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NGRmMGRlYTIwOWE1NGY3OGQ1YzA0YTNmNTYyY2NiNGM5YTNkNzEzNWRhZTQ5Y2E0ZWE1OWQzM2RhN2RiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ACS74wc8QUeex7TfeAX_pr_YEjq1uQGxfSp8q-F1bJs)
> 
> Properly using the "normal map" property fixes the issue ![Screenshot from 2024-05-15 12-39-28](https://private-user-images.githubusercontent.com/16521339/330938451-94bf89f1-94a3-4113-9bde-9629f6a708b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDI5NzQsIm5iZiI6MTcxNTgwMjY3NCwicGF0aCI6Ii8xNjUyMTMzOS8zMzA5Mzg0NTEtOTRiZjg5ZjEtOTRhMy00MTEzLTliZGUtOTYyOWY2YTcwOGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE5NTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNzEwMTFhZTQxZmJlYjRmYjkxNjc4MWVkMzJlYmE4ZjQ1OWIwNWI1YzZhZjFlYzY0MTk4N2FhZDY1NGRkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4vbRpZjDVfTsxsfwMfqfm7ZWd7dagOgl2O8XsU3yP8)

Thank you! I didn't think to change the options even though I noticed it before. What is the difference between the Normal and Normal Map?

**Comment by clayjohn** [comment]
> Thank you! I didn't think to change the options even though I noticed it before. What is the difference between the Normal and Normal Map?

Normal overwrites the per-fragment normal value and is specified in view space.

Normal_map applies a normal map on top of the per-fragment normal and is specified in tangent space (the same space as your normal map texture)
