### ISSUE TITLE
UI elements stop working under Wayland.

### ISSUE THREAD

**Issue by Oglo12** [godotengine/godot#91632]
### Tested versions

- Reproducible in: 4.2.1.stable.arch_linux

### System information

(Provided Via The *Help -> Copy System Info*) `Godot v4.2.1.stable unknown - EndeavourOS #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 - Wayland - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV REMBRANDT) () - AMD Ryzen 7 6800U with Radeon Graphics (16 Threads)`

### Issue description

In Godot, when I use the engine, there are times where the UI just stops working. I have concluded that this is a Wayland issue. Essentially, when I need to do something like change the colors of the editor, I need to click over and over again to get the color picker to show up. And when I try to input a color, it barely works. Sometimes it lets me change the color, and sometimes I can only delete one letter in the color input, and then just not interact with it. It is quite common to just not be able to use keybindings either. I feel like there is an issue with not polling input on Wayland, because if I hit `CTRL + S` once to save something, I can no longer use `CTRL + S` to save the thing. I have to manually use the save button in the menu.

### Steps to reproduce

1. Use a Wayland compositor. (I am using Hyprland which is a `wlroots` based compositor.)
2. Try to change the editor theme in the `Editor -> Editor settings...` menu.
3. If done right, the menu is just going to stop working, and eventually the more you use Godot, the more will stop responding to interactions.

### Minimal reproduction project (MRP)

Luckily, I don't need to provide a project! Because this is simply an issue with the Godot UI.

**Comment by Oglo12** [comment]
> Mh, this feels like a window focus issue to me, since the issues you're having are with popups.
> 
> Note that, unless you explicitly set it, you're still using the X11 backend through XWayland, a compatibility mechanism, which is known to have some issues unfortunately (#78581).
> 
> I'd try forcing single-window mode (`Editor -> Editor settings... -> Interface -> Editor -> Single Window Mode`) and see whether it improves the situation.
> 
> Also, out of curiosity, I'd try the latest pre-release, just in case some fix didn't get backported, although I wouldn't bet on it fixing the issue. Trying doesn't hurt I suppose ;)

Well, the border of my Wayland compositor does update, and it does focus around the popup properly, and this isn't a popup-only issue. This happens with the main window as well. What happens is the elements I use just stop working after a while. I am guessing it is a polling issue.

**Comment by eobet** [comment]
I'm rather new to Linux so how do I know if I'm using the X11 compability layer? I'm on a Fedora 39 based distro using vanilla Gnome Wayland.

Attempting to use the color picker for me makes my Linux desktop more or less unusable (I can move my mouse cursor, but not much else) so I have to force a reboot.
