### ISSUE TITLE
Godot 4.3 NavigationFinished for navigationagent3d requires to return system.action in c#

### ISSUE THREAD

**Issue by meatball133** [godotengine/godot#91668]
### Tested versions

- 4.3.dev 6

### System information

Godot v4.3.dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.5176) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

I try in c# to use the signal `NavigationFinished` for navigationagent3d, but the compiler says the method should return System.action and not void, which I would expect. Is this a bug?

```c#
    public override void _Ready()
    {
        characterNode.navigationAgent3DNode.NavigationFinished += HandleNavigationFinished();   
    }
```

### Steps to reproduce

```c#
    public override void _Ready()
    {
        characterNode.navigationAgent3DNode.NavigationFinished += HandleNavigationFinished();   
    }
```

### Minimal reproduction project (MRP)

```c#
    public override void _Ready()
    {
        characterNode.navigationAgent3DNode.NavigationFinished += HandleNavigationFinished();   
    }
```

**Comment by AThousandShips** [comment]
Please add an MRP project to be able to see the whole setup, at least please add the implementation of `HandleNavigationFinished`

**Comment by meatball133** [comment]
Ahh I forgot about that, thanks

**Comment by AThousandShips** [comment]
I'd suggest asking questions for these things in the [forums](https://forum.godotengine.org/) to catch any errors like that, before opening a report

Thank you for reporting
