### ISSUE TITLE
Incorrect syntax highlighting of inline function body within the argument list of a function call

### ISSUE THREAD

**Issue by radishes** [godotengine/godot#91680]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Windows 10

### Issue description

When an inline function definition within another function's argument list contains an inline `if` statement, the syntax highlighting of the statement following the inline `if` is incorrectly applied.

![image](https://github.com/godotengine/godot/assets/1106565/18154e12-ee2b-4b52-a441-1d855c61c85f)

In this screenshot, the final `my_var` is colored with the color used by types in an argument list. Presumably because the statement comes after the colon `:` character of the `if`, which is the same way a type would be specified in an argument list.

### Steps to reproduce

```
func test():
	var my_var = true
	tree_entered.connect(func(): if my_var: my_var = false)
```

### Minimal reproduction project (MRP)

See steps to reproduce

**Comment by Maran23** [comment]
Is fixed in the latest Godot-4-3-dev-6, probably by https://github.com/godotengine/godot/pull/86176.
