### ISSUE TITLE
Visual Scripting: User defined functions always return "Null"

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9170]
Arch Linux, Godot 3.0 master

**Issue description:**

User defined functions in Visual Script always return Null, even if a return value was specified. I have tested many different kinds of return values and never got anything back when calling the functions.

**Steps to reproduce:**
1. create a node with a visual script
2. define a new functions and make it return a value
3. call the function and check its return value

**Link to minimal example project:**
Here is a minimal example project:
[vs_test.tar.gz](https://github.com/godotengine/godot/files/1074323/vs_test.tar.gz)

**Comment by kubecz3k** [comment]
When this issue will be solved we should check https://github.com/godotengine/godot/issues/6346#issuecomment-243788542
