### ISSUE TITLE
Leaked instances and Orphan StringNames on exiting game on android device when using plugins

### ISSUE THREAD

**Issue by quanixstudio** [godotengine/godot#91739]
### Tested versions

4.2.1 stable
4.2.2 stable
4.3-dev6

### System information

Windows 11 - Godot v4.2.2.stable - Forward+

### Issue description

When running a project on an android device, on exiting it shows a leaked instance for every plugin loaded with Orphan StringNames of all the methods from the plugin that uses @UsedByGodot after calling get_tree().quit().

-- My project
![Schermafbeelding 2024-05-09 000634](https://github.com/godotengine/godot/assets/43936740/f9b2df4a-adb4-489e-894f-aa82730a062b)

-- MRP --
![Schermafbeelding 2024-05-09 023119](https://github.com/godotengine/godot/assets/43936740/ebe3daa9-5126-4556-a780-a16887428c64)

### Steps to reproduce

Create a new project.
Add an android plugin.
Run project on a physical android device and monitor logcat on exiting.

### Minimal reproduction project (MRP)

[TestProject.zip](https://github.com/godotengine/godot/files/15256221/TestProject.zip)

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by quanixstudio** [comment]
When storing the plugin singleton into a variable and on `_exit_tree()` calling `free()` on that variable, the leaked instance and Orphan StringNames are gone.

```
var plugin : Object

func _ready() -> void:
	if Engine.has_singleton("pluginname"):
		plugin = Engine.get_singleton("pluginname")

func _exit_tree() -> void:
	if plugin != null:
		plugin.free()
```
