### ISSUE TITLE
Godot 4.2.2- Linux Mint/Debian - SpriteFrame Editor missing from Godot.

### ISSUE THREAD

**Issue by Jack-Daly-Eng025** [godotengine/godot#91737]
### Tested versions

Tested versions 4.2.1-4.3, will try to find the time to test others out when I have the time. 

### System information

Godot v4.2.2.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Mobile) - integrated AMD Radeon Graphics (RADV RAVEN) () - AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Hi, 

I am new to Game Development and Godot but I am trying my best to learn the ropes. I'm doing a 30 days of Code challenge and Godot is one of the new tools I'd love to have in my toolbox by the end of it as a developer. I was following along the tutorial steps provided by Brackeys on YouTube, when I realised I have no way to edit Spriteframes in the editor.
 The actual popup editor is missing along the bottom half and I am unsure whether I need to roll back to a previous version or if I am missing a trick. I get to the stage where I add a new Sprite Frame in the Inspector view to AnimatedSprite2D.  It could be something to do with Linux, or  my settings, but I have tried running a few different versions now and get the same issue. I even deleted all of the previous versions and tried using the version that's hosted via Steam to only encounter the same issue. Is it a case of bad luck or have I found a bug? 

### Steps to reproduce

Firstly, I guess you need to be using a Linux OS. 

 I am using Linux Mint specifically if that helps things. 

Secondly, just download the current most stable version, open it up, create a empty project etc. 
Or download via Steam , or go to some previous release for Godot 4.0. 

Next, create a player scene. Doesn't matter if it's Area2D, a sprite etc, you'll already notice you can't select any options for SpriteFrames outside of the Inspector view for AnimatedSprite2D.  Or maybe you'll have better luck than me and it will work as intended. 

If anyone does know how to remedy this glitch/bug let me know. Or point me to a version that enables it again? I'm eager to start making my own games and  Godot looks like it would be the most fun as a beginner. 

### Minimal reproduction project (MRP)

[MyFirstGodotGame-main.zip](https://github.com/godotengine/godot/files/15255593/MyFirstGodotGame-main.zip)

I also uploaded the same project directly to my GitHub Profile if that helps.

**Comment by ghmart** [comment]
I think you need to click "SpriteFrames" in Inspector after adding it:

![sprite_frames](https://github.com/godotengine/godot/assets/7192155/83f5e076-1c6d-44e1-a7ed-859cd84c55ee)

This is on Debian bullseye, Godot v.4.2.2

**Comment by Jack-Daly-Eng025** [comment]
Ah! Foiled by the double-click!  I now have access to the SpriteFrame menu that eluded me. I'm excited to get stuck in now!

Well now I just feel silly.  Thanks friend. I don't know why either, maybe he did something to his installation  as a preference?
I won't try to replicate it either way, just gonna try to complete the tutorial.  Thanks for the assistance!
