### ISSUE TITLE
Using the `&=` operator with two bools in GDScript causes runtime error

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#91736]
### Tested versions

- 4.2.1.stable.official [b09f79f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.5186) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

the following code causes a runtime error:

![bild](https://github.com/godotengine/godot/assets/11806563/1ce6312f-5aa9-4515-a8e4-7c69dcd55c36)

### Steps to reproduce

1. Insert:
```gdscript
func _init():
	var val1 = false
	val1 &= true
```
into a script.

2. Call script constructor.
3. Observe error.

### Minimal reproduction project (MRP)

N/a

_Bugsquad edit:_ Fix formatting.

**Comment by dalexeev** [comment]
Note that the `&` operator (and the compound assignment operator `&=`) is bitwise AND, not logical AND. Bitwise operations are defined for `int`, not for `bool`. We just have implicit conversions between `bool`, `int`, `float`. This works if at least one of the operands is `int`, but fails if both operands are not `int`.

Some languages have `&&=` and `||=` compound operators for boolean operations, but this is a bit confusing when combined with short-circuit.

**Comment by vnen** [comment]
This is expected. As @dalexeev said the `&` operator is for bitwise AND. If you want to propose a change, it should be done in the [proposals repository](https://github.com/godotengine/godot-proposals), which also supports discussion threads.
