### ISSUE TITLE
Godot editor freezes when opening a project using Forward+ mode

### ISSUE THREAD

**Issue by crayonape** [godotengine/godot#91730]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Pop_OS_22.04

### Issue description

![image](https://github.com/godotengine/godot/assets/9478533/50affc7e-14fd-4926-889d-48888a28c5f6)
When I open a project in Forward+ mode my Godot editor freezes and this is what the terminal prints out.

### Steps to reproduce

I think versions greater than 22.04 can be reproduced for ubuntu-based operating systems.

### Minimal reproduction project (MRP)

none

**Comment by akien-mga** [comment]
What's your GPU and drivers version?

Most likely the GPU drivers don't support Vulkan properly, or are buggy in that version. Updating to a newer distro/driver version may help.

**Comment by crayonape** [comment]
> What's your GPU and drivers version?
> 
> Most likely the GPU drivers don't support Vulkan properly, or are buggy in that version. Updating to a newer distro/driver version may help.

Sorry, I forgot to reply.
If anyone is experiencing the same problem where the console keeps printing "Early out of date swapchain, recreating", you can try to fix it with this method:

When running Godot in Linux, sometimes the application can't run with a discrete graphics card, you can fix this by right-clicking on the Godot icon and selecting "Run this application with a discrete graphics card", or in the .desktop file using "Exec=env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_ VENDOR_LIBRARY_NAME=nvidia path/to/godot" to force Godot to use a discrete graphics card.

Also, incompatible drivers are also possible, if above doesn't work, you may also take a try.

**Comment by akien-mga** [comment]
Thanks for the details and the workaround.

I'll close this as this isn't something we can solve easily in Godot, the drivers situation on Linux can be tricky, especially with Nvidia.
