### ISSUE TITLE
Can't access EditorFileSystem

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#91756]
### Tested versions

Godot 4.2

### System information

Godot v4.2.2.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 3GB (nvidia; 535.171.04) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

an example from the docs do not work for me:
var editor_settings = EditorInterface.get_editor_settings()
and the same for  EditorFileSystem
It returns error:
![image](https://github.com/godotengine/godot/assets/33228017/1c39ec6c-5f6b-43b6-8f0f-bac76ea4e81c)

### Steps to reproduce

Just copy paste the code I provided and try to run

### Minimal reproduction project (MRP)

[Bug report.zip](https://github.com/godotengine/godot/files/15261701/Bug.report.zip)

**Comment by AThousandShips** [comment]
Try running with `@tool`, this is editor only so won't be available in a running game

**Comment by gravit22** [comment]
> Try running with `@tool`, this is editor only so won't be available in a running game

Ah... Thank you. Didn't see it mentioned in the docs
