### ISSUE TITLE
Derived Motion Vectors broken between 4.3 dev 5 and dev6

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#91758]
### Tested versions

Happens 4.3 Dev 6
Doesn't in 4.3 Dev 5 and earlier

### System information

Windows 11, i3-10105f, RX6600 24.4.1, Forward+

### Issue description

Derived Motion Vectors are Broken resulting in broken FSR2 Behaviors
When zooming out these are the results

![image](https://github.com/godotengine/godot/assets/50302479/46417b55-9ac7-4c15-85a3-bff02d9d8dc9)

Expected

![image](https://github.com/godotengine/godot/assets/50302479/46c5a46d-e94b-463d-b79c-808ba7a117ed)

### Steps to reproduce

Enable FSR and move around, Looking at the Motion Vectors

### Minimal reproduction project (MRP)

N/A

**Comment by DarioSamo** [comment]
The blue motion vectors are derived from the camera and the depth value. Is it possible it's related to reverse depth? I'd try before and after this commit https://github.com/godotengine/godot/commit/69a4ff899618cc40bcf5aed2130d4cb2e3c021d6.

**Comment by clayjohn** [comment]
I can't reproduce this issue. I've tested a basic scene with a plane mesh with Dev 5, Dev 6 and current master. 

Can you upload an MRP that reproduces the issue? There must be something about your mesh that is impacting this

**Comment by DarioSamo** [comment]
> The blue motion vectors are derived from the camera and the depth value. Is it possible it's related to reverse depth? I'd try before and after this commit [69a4ff8](https://github.com/godotengine/godot/commit/69a4ff899618cc40bcf5aed2130d4cb2e3c021d6).

I've tested the commit before and after reverse Z and I can confirm this issue was introduced during that, and it seems to affect the derivation of the motion vectors from depth in particular that is used for FSR2. I'm not entirely sure why it breaks and how to fix it yet, but that's the starting point for this.

**Comment by mrjustaguy** [comment]
https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/effects/motion_vector_inc.glsl maybe?

**Comment by DarioSamo** [comment]
> https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/effects/motion_vector_inc.glsl maybe?

That is independent of the math. I opened this PR that seemingly fixes the issue and it makes enough sense to me at least: https://github.com/godotengine/godot/pull/91799
