### ISSUE TITLE
Game crashing on older android versions despite exceeding minSdk.

### ISSUE THREAD

**Issue by Bendimester23** [godotengine/godot#91773]
### Tested versions

 - Reproducible in 4.2.1 and 4.2.2

### System information

Android 8 - Sony XPERIA XA1 - Mobile renderer

### Issue description

I exported a basic game to Android and installed it on my phone, and it crashed, but when I tried it on an other phone with Android 13, it worked. In the export settings I left minSdk on 24 and my phone is on sdk level 26.

### Steps to reproduce

- Create a project
- Export to Android
- Open app(I tried it on Android 8)
- Crash

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/godotengine/godot/files/15265013/Archive.zip)

**Comment by Bendimester23** [comment]
Here are some logs:
[logcat.txt](https://github.com/godotengine/godot/files/15265070/logcat.txt)
[logcat2.txt](https://github.com/godotengine/godot/files/15265079/logcat2.txt)

**Comment by tiloc** [comment]
WindowInsetsAnimation requires API level 30. If Godot wants to stay on minSDK 24 then it cannot use this. One option would be to use the corresponding compatibility class: https://developer.android.com/reference/androidx/core/view/WindowInsetsAnimationCompat

**Comment by Bendimester23** [comment]
I didn't change anything in the Java code and I could not find where that class is used in the file from the stacktrace.

**Comment by tiloc** [comment]
> I didn't change anything in the Java code and I could not find where that class is used in the file from the stacktrace.

I believe it is this callback here: https://github.com/godotengine/godot/blob/7a3a36ab879294bc7c6f41e8d576d59462645156/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L410

But it seems to be protected with an API check for Android R, which is SDK 30. I still think Godot might benefit from removing the SDK check and using the compatibility class instead.

**Comment by Bendimester23** [comment]
> protected with an API check for Android R

It seems like it tries to load all the classes present in the file even if that part of the code isn't executed.

**Comment by clayjohn** [comment]
Cc @m4gr3d

**Comment by Aquamenti9** [comment]
Hello, I have the same issue, does somebody have a temporary workaround? thx!
