### ISSUE TITLE
Hovering over a node while dragging a node in the tree messes up the operation

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#91798]
### Tested versions

- happens in v4.3.dev.custom_build [c4279fe3e]
- does not happen in 4.3 dev 5

### System information

linux

### Issue description

https://github.com/godotengine/godot/assets/71937306/19bf0302-29fa-44d8-a4a2-ecc5d953c0d6

what happens:
- I start dragging a node, and hover over another node
- when I hover for long enough, the other node is selected
- when dropping the drag operation, it drops the newly selected node, not the old one.

### Steps to reproduce

see above

### Minimal reproduction project (MRP)

any

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/91254

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
