### ISSUE TITLE
3D scene imported via BetterCollada sets point light energy to 8

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#918]
For some reason, when importing 3D scene (*.dae) bettercollada from Blender, the point lights always turn to energy 8, what is to much overexposed. Why 8 anyway?

**Comment by akien-mga** [comment]
What's the status on this issue? Is it still valid with the current BetterCollada / Godot 2.0?

**Comment by akien-mga** [comment]
Is it something that should be fixed in bettercollada (and thus the issue should be moved to the corresponding repo), or should it be fixed in Godot?

**Comment by bojidar-bg** [comment]
Pretty bump again, it would be terrible if this issue stands lingering endlessly.

**Comment by trsh** [comment]
Duno!

**Comment by akien-mga** [comment]
Still valid in the current master branch?

**Comment by akien-mga** [comment]
Closing as no one could confirm the issue in almost a year. If you can still reproduce it, feel free to comment here so that it can be reopened.
