### ISSUE TITLE
MutiplayerSpawner not accepting any callables for custom spawn function

### ISSUE THREAD

**Issue by kylemiller3** [godotengine/godot#91803]
### Tested versions

Godot v4.2.1 [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M2 - Apple M2 (8 Threads)

### Issue description

I want to use a custom spawn function with mutliplayer spawner but it always spawns a null node using custom function

![image](https://github.com/godotengine/godot/assets/5983525/f680bd2d-53ec-49c8-aaf3-64136ea53f74)

### Steps to reproduce

Join a multiplayer session and try to use a custom function to spawn on the authority

```gdscript
	spawner.set_spawn_function(func() -> Node: return Node.new())
	spawner.spawn()
```
I think should work but does not.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/godotengine/godot/files/15277514/Bug.zip)

**Comment by AThousandShips** [comment]
It has to take one method, as per the [documentation](https://docs.godotengine.org/en/stable/classes/class_multiplayerspawner.html#class-multiplayerspawner-property-spawn-function)

So you should do:
```gdscript
spawner.set_spawn_function(func(_data) -> Node: return Node.new())
spawner.spawn()
```

**Comment by kylemiller3** [comment]
That's interesting. My main project actually did have the first parameter used (it sent a string) and still got the message. Let me recheck.

**Comment by kylemiller3** [comment]
![image](https://github.com/godotengine/godot/assets/5983525/7cadf77e-2d0c-4c27-a2c3-a28eed6eb89b)
Unfortunately, I am still getting this problem

**Comment by AThousandShips** [comment]
Have you set it on all clients? Please upload an updated project id the original MRP contained the invalid function

**Comment by kylemiller3** [comment]
Thank you I did not set the function on all clients which was the cause of my error! I might have missed that in the docs.
