### ISSUE TITLE
Color picker in "Raw" mode uses wrong ranges for sliders

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#91810]
### Tested versions

Reproducible in 4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Color picker in "Raw" mode uses wrong ranges for sliders. They should be 0 -> 1, but instead they are using 0 -> 100.

https://github.com/godotengine/godot/assets/13228932/306284c2-70a4-442c-877a-c4b5045b3da7

### Steps to reproduce

Open any color slider, set it to "Raw" mode, move any of the sliders, and observe that the ranges are wrong.

### Minimal reproduction project (MRP)

N/A

**Comment by fire** [comment]
I thought color raw ranges are from 0 to FLOAT_MAX. Maybe someone tried to make raw colors easier to use.

**Comment by MajorMcDoom** [comment]
> I thought color raw ranges are from 0 to FLOAT_MAX. Maybe someone tried to make raw colors easier to use.

Whenever I used raw mode in the past, it's been from 0 to 1. And as you can see in the video, the values are clearly *expected* to be in 0 - 1 range. Setting them with these new ranges gives very washed out results.

**Comment by fire** [comment]
There's a way to change slider properties so they slide from 0 to 1 and then you can enter any value.

**Comment by fire** [comment]
I'll love to hear a better setting for raw colours though.

You mentioned:

1. Raw colours range from 0 - 1.
2. Raw colours can be set to any value.

**Comment by MajorMcDoom** [comment]
> I'll love to hear a better setting for raw colours though.
> 
> You mentioned:
> 
>     1. Raw colours range from (0 - 1) not like (0 - 100)
> 
>     2. Raw colours can be set to any value.

The way I see it, there are three aspects to raw colors:
1. The *actual* range: FLOAT_MIN - FLOAT_MAX
2. The *normal* (non-HDR) range: 0 - 1
3. The UX

The UX, ideally, should allow for setting to any value within the *actual* range, while simultaneously communicating the existence and/or relative placement of the *normal* range.

It's debatable what the ideal UX would look like. It could be anything from using fields instead of sliders, to having helpful labels, to disabling the sliders when a value is explicitly set.

But what I think is bad is the current approach, which:
1. Fails to communicate either type of range (actual or normal)
2. Introduces an arbitrary *third* range (0 - 100) which is meaningless to the actual user task
3. Prevents the user from setting above 100, and prevents the user from setting negative values, both of which should be allowed (it's allowed in code, and is useful for many graphics tricks).

My personal take on a better UX for this would be:
- Make the sliders disabled, and only allow setting component values via the spinners / fields.
- Make the sliders still display using a range of 0 - 1, thus communicating the *normal* range.
- Optionally add indicators for when the values are set beyond the normal range.

**Comment by fire** [comment]
1. Make the sliders read-only but still shown. The raw colour channel property is still editable.
2. show the range of the slider as between 0 and 1 and indicate when exceeding.

@KoBeWi do we have anything in Godot Engine proposals or pull requests that can do this?

**Comment by KoBeWi** [comment]
> Optionally add indicators for when the values are set beyond the normal range.

This exists:

![image](https://github.com/godotengine/godot/assets/2223172/9179f845-6bf1-4c3a-8c83-6670388127e3)

The base color range is 0-1, but higher values are allowed to enable some effects like glow. It's even documented: https://docs.godotengine.org/en/stable/classes/class_colorpicker.html#enumerations

> Make the sliders read-only but still shown.

idk what this would achieve.

> do we have anything in Godot Engine proposals or pull requests that can do this?

There is https://github.com/godotengine/godot/pull/88072

**Comment by MajorMcDoom** [comment]
> > Optionally add indicators for when the values are set beyond the normal range.
> 
> This exists:
> 
> ![image](https://private-user-images.githubusercontent.com/2223172/329693143-9179f845-6bf1-4c3a-8c83-6670388127e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjgzNzcsIm5iZiI6MTcxNTM2ODA3NywicGF0aCI6Ii8yMjIzMTcyLzMyOTY5MzE0My05MTc5Zjg0NS02YmYxLTRjM2EtOGM4My02NjcwMzg4MTI3ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTkwNzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTEyYzc1NTQ0YjI4YzZhNTg5OWJhZjk2ODgwZjVlMTc4MGY2YTc3ZjUwYTE5YzZlMzliYzA3ODFjZmU1OTBiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NEECM9yU1Dfe272bBxUg7NSfYPIKGuGGFJpmKMfDuLg)
> 
> The base color range is 0-1, but higher values are allowed to enable some effects like glow. It's even documented: https://docs.godotengine.org/en/stable/classes/class_colorpicker.html#enumerations
> 
> > Make the sliders read-only but still shown.
> 
> idk what this would achieve.
> 
> > do we have anything in Godot Engine proposals or pull requests that can do this?
> 
> There is #88072

See my last post for all the rationale. I understand the base range, and the higher representational range. The issue here is with the 0 - 100 range.

The disabling of the sliders was really to simplify the implementation, because leaving a slider interactable while allowing out-of-range value representation is quite a complicated change from the current implementation.

**Comment by MajorMcDoom** [comment]
> There is #88072

Thanks for that link though! Will comment there. :)
I don't want this to get derailed into a proposal, because I didn't open this issue intending / prepared to do that. I already closed it.
