### ISSUE TITLE
Crash when importing image as FontData if setting rows to 0

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#91812]
### Tested versions

- Reproducible in: 4.3-dev6, 4.2.1

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700S (Advanced Micro Devices, Inc.; 31.0.24031.5001) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When importing an image as FontData, setting "rows" to 0 in the Import tab and reimporting crashes the editor

### Steps to reproduce

- Open the attacked MRP
- In the Filesystem dock select "TimerNumbers_10.png"
- Go to the Import tab
- Set rows to 0
- Reimport
Expected: An error is shown into the console since 0 is an invalid value
Actual: The editor crashes and the invalid value gets saved in the .import file

This is just an example, you can cause the same crash by setting columns to 0

Other errors, like having a total character range exceeding rows*columns show properly without causing any crashes

### Minimal reproduction project (MRP)

[fontdata-mrp.zip](https://github.com/godotengine/godot/files/15279355/fontdata-mrp.zip)

**Comment by Rubonnek** [comment]
Could you test if it's reproducible in 4.3dev5?

**Comment by noidexe** [comment]
The error seems to be here: https://github.com/godotengine/godot/blob/2ba22d1554ded08094e3869a83bd87487266ad38/editor/import/resource_importer_imagefont.cpp#L98 
columns and rows are used as divisors. There should be an ERR_FAIL_COND if they are 0

**Comment by noidexe** [comment]
> Could you test if it's reproducible in 4.3dev5?

It is.
