### ISSUE TITLE
The grid fades out in an empty project

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9181]
In latest Godot, Windows 10 64 bits

I just created an empty project, and noticed the grid is fading in a weird way:

![image](https://user-images.githubusercontent.com/1311555/27153943-89d2bc18-5153-11e7-85db-abf66f570cc5.png)

It depends on the camera angle, sometimes the grid is fully visible, sometimes it disappears completely.

**Comment by novemberist** [comment]
I can not reproduce this so far having tried a lot of different angles and zoom levels. Also on latest master build, Linux

**Comment by vnen** [comment]
I can reproduce this on Windows (with an RX 480 card)

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
I think it's irrelevant now, I never had this problem since.

**Comment by kubecz3k** [comment]
Thanks for the info. I also haven't encountered it in the stable version. :+1:
