### ISSUE TITLE
Pathfinding produce an incorrect path when using NavigationAgent2D

### ISSUE THREAD

**Issue by pcloves** [godotengine/godot#91838]
### Tested versions

- Reproducible in: 4.3 dev [2042420b],  v4.3.dev6.mono.official [89850d553], v4.2.2.stable.mono

### System information

Windows11 - v4.2.2.stable.mono  - Forward+

### Issue description

The path produced by NavigationAgent2D has incorrect path point that located out of navigation mesh, shown as follows:
<img width="608" alt="PixPin_2024-05-11_23-42-12" src="https://github.com/godotengine/godot/assets/4152188/9a90a38c-cdb6-40e3-b0a8-772617617644">
![PixPin_2024-05-11_23-50-29](https://github.com/godotengine/godot/assets/4152188/8d44a3ec-e970-446f-a553-1696d19533bd)

### Steps to reproduce

Steps to reproduce for MRP
1. toggle on `Debug` -> `Visible Navigation`
2. run  `main.tscn` and click any tile to move the player.
 

### Minimal reproduction project (MRP)

[navigation_4.2.zip](https://github.com/godotengine/godot/files/15283386/navigation_4.2.zip)

**Comment by smix8** [comment]
If you use a NavigationRegion2D disable the TileMap build-in navigation on the TileMapLayer, else you create surface conflicts when both are active.

**Comment by pcloves** [comment]
> If you use a NavigationRegion2D disable the TileMap build-in navigation on the TileMapLayer, else you create surface conflicts when both are active.

Thanks, it works.

**Comment by pcloves** [comment]
close
