### ISSUE TITLE
Not Using SHA Values

### ISSUE THREAD

**Issue by yarkinn** [godotengine/godot#91834]
**📁 File:**
https://github.com/godotengine/godot/blob/master/.github/workflows/linux_builds.yml
**🪲 Smell Description:**
When action from another repository is used and its version is declared without SHA values, this smell is triggered.
**🔧 Fix:**
Use SHA values at job build-linux in line 18 in action path: actions/checkout@v4

🤖 _Auto Generated by CI/CD Plumber_

**Comment by akien-mga** [comment]
This doesn't make much sense to me, `actions/checkout@v4` is the recommended way to use this action.

Sure, one could be more specific to try to avoid a potential supply chain attack, but then someone taking over control of `actions/checkout` (official GH action) could delete whichever tag we target and replace it by a malicious one. We accept the risk by using the GitHub Actions system as it's designed.
