### ISSUE TITLE
[CI] Style checks are broken

### ISSUE THREAD

**Issue by AThousandShips** [godotengine/godot#91831]
### Tested versions

N/A

### System information

N/A

### Issue description

Code style checks are no longer being applied, see for example:
https://github.com/godotengine/godot/commit/82f5bd630c7b693d69e16e4a0f4ac530528a230f

Seems to be a regression from:
* https://github.com/godotengine/godot/pull/91597

All checks are now marked as `skipped` and claims there are no files to check

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
CC @Repiteo @akien-mga

**Comment by akien-mga** [comment]
Indeed the new code run `pre-commit run --verbose`, and by default `pre-commit run` only affects files which have been staged in Git. In a PR or merge CI run, there's no staged files, as the commit was already made. So we still need a way to pass the list of files changed in the commit(s) compared to the base branch.

So we should probably restore the `--files ${{ env.CHANGED_FILES }}` logic, unless the pre-commit action provides a facility for this. (I suppose it doesn't, [the action repo says](https://github.com/pre-commit/action) it's in maintenance mode and they encourage us to use their own hosted CI system.)

**Comment by fire** [comment]
Do we need to host our own https://github.com/pre-commit/action that avoids a host ci system?

**Comment by akien-mga** [comment]
> Do we need to fork our own https://github.com/pre-commit/action that avoids a hosted ci system?

No, that action is a GitHub Action and is therefore "hosted"/run by GitHub in the runners they provide us.
The "pre-commit CI" they mention is a separate, bespoke product that they offer. We don't have to use it is the basic GH action works for us.
