### ISSUE TITLE
Texture import freezes

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#9183]
**Operating system or device - Godot version:**
Windows 10, be3115119994141d3708eb67cfb7db3bc14f84a8

**Issue description:**

I copied 2048x2048 textures into project folder and the editor simply freezes while importing the asset. Console prints this:
`to gen mipmaps w 2048 h 2048 format RGBA8 mipmaps 11 new size is: 22369620`

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by suptoasty** [comment]
This issue also affects Manjaro Linux 64-bit with 1024x1024 textures.
Same error code as UgisBrekis

**Comment by Gibbz** [comment]
REIMPORTING: res://Map/Australia/Australia-Height.png
REIMPORTING: res://Map/Australia/Australia-Normal.png
to gen mipmaps w 1024 h 1024 format RGBA8 mipmaps 10 new size is: 5592404


yep same issue here, but not with all textures....

**Comment by tagcup** [comment]
Assuming that this is caused by etc2comp, we may need to tone down the default quality setting for lossy import. I guess the alternative is to move import stuff to a separate thread.
