### ISSUE TITLE
"Change type" menu item disappeared from node context menu in inherited scenes

### ISSUE THREAD

**Issue by ResidualSludge** [godotengine/godot#91842]
### Tested versions

Occurs in v4.3.dev6.official [89850d553]
Does not occur in v4.3.dev5.official [89f70e98d]

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5212) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

The "change type" menu item is missing from the root node's context menu when creating a new inherited scene from an imported model or from another scene:
![changetypeissue](https://github.com/godotengine/godot/assets/17679847/bef4dd62-e173-4fa6-aed3-f4766eca64d7)

The issue doesn't occur when selecting a node in a scene which has been created via "Create Scene" and not "New inherited scene":
![changetypeissue2](https://github.com/godotengine/godot/assets/17679847/1759e97f-4b96-462e-ad91-31acec669c09)

### Steps to reproduce

1. Create a new project
2. Import a glb/fbx file or create a new scene (_not_ an inherited scene)
3. Right-click on the imported file/the scene => "New inherited scene"
4. Select the root node of the newly created inherited scene
5. Do not find the "Change type" item (which was there in the previous dev5 build)

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment]
This is intended: #90536

**Comment by AThousandShips** [comment]
Closing as per the above, if there's anything else you want to add please reply here, otherwise this has been resolved

**Comment by taylcr** [comment]
What is the alternative to that ? it is intended but is there a way to do the change ?

**Comment by KoBeWi** [comment]
Change the type of base scene.
The option was removed, because it wasn't working properly.
