### ISSUE TITLE
Color Picker Bad hiDPI support

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9184]
**Issue description:**

the color picker top area does not take EDSCALE into account and is sized wrongly when using hiDPI.
HiDpi

<img width="298" alt="screen shot 2017-06-14 at 15 32 55" src="https://user-images.githubusercontent.com/16718859/27157526-c2d1dc98-5116-11e7-9558-ff469080579e.png">

Normal Dpi
<img width="149" alt="screen shot 2017-06-14 at 15 27 00" src="https://user-images.githubusercontent.com/16718859/27157505-a5697ba2-5116-11e7-8801-dce3d2d34221.png">

**Comment by reduz** [comment]
the color picker is working? wow

**Comment by toger5** [comment]
better than ever before but still having issues. Always showing black and white...

**Comment by novemberist** [comment]
yes, one of the latest commits seems to have finally fixed it. great :)

**Comment by toger5** [comment]
but the color in the bar not the right is still inverted

**Comment by novemberist** [comment]
@toger5 and the crosshair is not moving (as is the measuring line in the bar on the right)

**Comment by toger5** [comment]
seems like we could need a tracker for the color picker? all those things are different issues.

**Comment by remorse107** [comment]
I've made a pull request.  It is working completely now.
