### ISSUE TITLE
Custom plugin bottom dock signals won't fire

### ISSUE THREAD

**Issue by pl7y** [godotengine/godot#91841]
### Tested versions

- Reproducible in 4.2.2.stable.official

### System information

macOS Sonoma 14.4.1 (23E224)

### Issue description

Function connected to button press signal doesn't trigger when control is instanced in a bottom docked plugin.

### Steps to reproduce

Basically:
1. Create an empty project
2. Create a new plugin from Settings
3. Create a Control named Dock with a button inside
4. Connect button pressed signal to a Dock function that prints "OK"
5. Configure the plugin to show in bottom dock

When executing the scene on its own, pressing the button prints OK. When pressing the button in the context of the bottom dock, the function doesn't get called (no OK prints).

The Minimal reproduction project shows this.

### Minimal reproduction project (MRP)

https://github.com/pl7y/godot-plugin-bottom-dock-issue

**Comment by kitbdev** [comment]
Looks like dock.gd needs to be a `@tool` script, see the warning [in the docs](https://docs.godotengine.org/en/latest/tutorials/plugins/editor/making_plugins.html#the-script-file).

**Comment by pl7y** [comment]
You are right, issue fixed, thank you so much!!!

I committed the `@tool` addition into the repo and added a minimal readme to point here.

Anyway it's not infrequent to spot  this kind of issues, caused by assumptions in docs which are not enforced in editor (e.g. scaled collision boxes) which drain lots of time debugging. One might wonder if there is a way to enforce this warnings as runtime checks instead.

Thanks again!
