### ISSUE TITLE
Mouse wheel in Visual Script should zoom in/out the editor

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#9185]
**Operating system or device - Godot version:** commit fc04e0b, Linux Mint 18.1
**Issue description:** Instead of zooming, the visual editor scrolls the field horizontally.

**Comment by toger5** [comment]
what computer are u using (laptop?)

**Comment by novemberist** [comment]
I think this is the normal behavior for now, maybe because zooming doesn't really work well with node graphs? There's also an old issue regarding this https://github.com/godotengine/godot/issues/6168

**Comment by toby3d** [comment]
@novemberist Zooming works well by click on +/- buttons in editor.

**Comment by novemberist** [comment]
@toby3d it works, but zooming out even only one step makes everything basically almost unreadable. so rendering of graph should be improved before implementing mouse zoom, i think.

**Comment by kubecz3k** [comment]
It's a duplicate of https://github.com/godotengine/godot/issues/6168
