### ISSUE TITLE
Adding bones to the models of the Android in Godot 4

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#91851]
### Tested versions

4.2.2

### System information

Mobile / Android 

### Issue description

I suffer from a problem when I want to add bones to a model, for example a man or a horse, but I cannot. I have tried all the methods to add bones to the models, but there is no solution. I have tried sites, including mixamo, and there are some problems in order to add bones, but I want to add them freely to any object and issue the figure and its bones. To the Godot 4 engine in the format fbx.glb.dae, which format exports the bones with the model, and I use an Android phone 

### Steps to reproduce

nothing

### Minimal reproduction project (MRP)

nothing

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by Sorshx** [comment]
Ok Thank you
