### ISSUE TITLE
OSX MenuBar fails to render

### ISSUE THREAD

**Issue by ipeerbhai** [godotengine/godot#91855]
### Tested versions

- Reproducible in 4.2.2

### System information

Godot 4.2.2.stable - macOS 14.4.1 Vulkand (Forward+) - Integrated M1 MAX - Apple M1 MAX (10 threads)

### Issue description

MenuBar does not render at all.  Area completely blank.  No way to use menubar controls.

### Steps to reproduce

Run the project at https://github.com/turnrocklabs/GodotBugReport

### Minimal reproduction project (MRP)

https://github.com/turnrocklabs/GodotBugReport

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
On macOS `MenuBar` use native global menu at the top of the screen by default, uncheck `Prefer global menu` in the `MenuBar` properties to use embedded menu instead.

**Comment by shanayyy** [comment]
Create a new project and create any scene, keep the tab open, then wait for 15 seconds, and then click the [add a new scene] button to open a new tab, which will print an error: "Can't remove open menu!"
<img width="715" alt="Screenshot" src="https://github.com/godotengine/godot/assets/13399488/3d7d494d-80b0-4b26-a43d-7fa17f5a5c9b">
macos sonoma 14.5 (23F79)
godot v4.3.beta1.official [a4f2ea91a]
