### ISSUE TITLE
String Format problems without curly braces

### ISSUE THREAD

**Issue by DarkiStar** [godotengine/godot#91865]
### Tested versions

Reproducible in Godot 4.3.dev6

### System information

Windows 10 - Godot 4.3.dev6

### Issue description

If using string format the editor reports an error if there are no curly braces around the parameters (if there are more than one).

Even if it is a number (like in my example) it interprets it as string (at least for the error message).

### Steps to reproduce

```
func test_error() -> void:
	print('test %d' % 20 + 20) # Error at(4,11): Invalid operands to operator +, String and int

func test_ok() -> void:
	print('test %d' % (20 + 20)) # no error`
```

### Minimal reproduction project (MRP)

see steps to reproduce

**Comment by dalexeev** [comment]
The `%` operator has higher precedence than the `+` operator, so you must use parentheses.

```gdscript
# This
print('test %d' % 20 + 20)
# is treated as
print(('test %d' % 20) + 20)
# not as
print('test %d' % (20 + 20))
```

This is not a bug and is documented [here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#operators). 
Thanks for the contribution nonetheless!
