### ISSUE TITLE
Bounding box glitch after selecting different nodes

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#91860]
### Tested versions

v4.3.dev.custom_build [bdc031621] (glitch)

v4.3.dev5.official [89f70e98d] (no glitch)

### System information

Godot v4.3.dev (bdc031621) - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 7 PRO 6850U with Radeon Graphics (16 Threads)

### Issue description

Note origin:

https://github.com/godotengine/godot/assets/105675984/d9baa41d-5bb0-4a0b-bfb0-658de433ee7c

https://github.com/godotengine/godot/assets/105675984/4b230b2c-8c43-491a-96b6-56a7417d741f

### Steps to reproduce

Focus on origin and perform a drag-and-drop to instantiate scene or select via the SceenTree

### Minimal reproduction project (MRP)

N/A

**Comment by ryevdokimov** [comment]
This also happens when you select nodes via the SceenTree, but weirdly not through the viewport.

**Comment by AThousandShips** [comment]
Can you describe how it glitches? I don't see anything wrong in the video, though it's only very brief so hard to see anything

**Comment by ryevdokimov** [comment]
The bounding box appears at the origin, here is a video of it occurring during selection via the SceenTree where it is a lot more obvious.

https://github.com/godotengine/godot/assets/105675984/272bbf42-226c-4e4c-90f0-7bbf3fd657e8

**Comment by ryevdokimov** [comment]
Yeah, I think this is technically a regression that has something to do with selecting different nodes in general. I can replicate this when instantiating, duplicating, selecting via the SceenTree. This is not an issue in 4.3dev5.

**Comment by clayjohn** [comment]
Confirmed in dev6, cannot reproduce in dev5

**Comment by clayjohn** [comment]
Bisected to:
```
48a64768616078f9a6a676e8d2ce7867702675f5 is the first bad commit
commit 48a64768616078f9a6a676e8d2ce7867702675f5
Author: ajreckof <tbonhoure@ymail.com>
Date:   Sun Apr 14 12:56:49 2024 +0200

    Fix going forward backward in editor selection history.

 editor/editor_node.cpp     | 14 +++++++++++---
 editor/multi_node_edit.cpp |  2 +-
 editor/multi_node_edit.h   | 15 ++++++++++++++-
 editor/scene_tree_dock.cpp |  7 +++++++
 editor/scene_tree_dock.h   |  1 +
 5 files changed, 34 insertions(+), 5 deletions(-)
 ```
 cc @ajreckof
