### ISSUE TITLE
Default Environment + Orthogonal View

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9186]
**Operating system or device - Godot version:**
Arch Linux, Godot 3.0 master

**Issue description:**
This is what happens if you switch to orthogonal view with the default environment, making working in orthogonal view potentially very hard. Is this expected behavior? 
(I don't work in orthogonal view much, but just realized this might be an issue)

**Steps to reproduce:**
1. open a new scene with default environment
2. switch from perspective to orthogonal

**Link to minimal example project:**
![orthogonal](https://user-images.githubusercontent.com/7927471/27158345-bff023c2-5166-11e7-9b93-4311f45c2fdc.gif)

**Comment by Zylann** [comment]
I would expect to see only ground if you look down, and only sky when looking up, and seeing both only when looking exactly at the horizon.

**Comment by novemberist** [comment]
Yeah, I know this doesn't look right at all. I was just wondering if the new way of handling skyboxes probably doesn't work in perspective and orthogonal view and you just have to ignore the sky when working in orthogonal.

**Comment by bojidar-bg** [comment]
Probably the sky/skybox code should be fixed to support orthogonal cameras as well?

**Comment by reduz** [comment]
I don't really know how to fix this, maybe in the environment one could set an orthogonal_fov parameter to use when the view is orthogonal?

**Comment by DimaKiva** [comment]
In my view, skybox is not needed in orthographic mode :)

**Comment by reduz** [comment]
In most cases it's not needed, but there were cases in the past where I had
to use it (simple 3D puzzle games). So It's probably best to support it..
