### ISSUE TITLE
Pressing ESCAPE does not cancel renaming file and folder in the editor (4.3 dev6)

### ISSUE THREAD

**Issue by spiralhalo** [godotengine/godot#91878]
### Tested versions

- Reproducible in: 4.3.dev6
- Not reproducible in: 4.3.dev5, 4.2.1

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3118) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

Pressing ESCAPE when renaming a file should cancel it according to previous versions. Instead, the renaming takes place anyway.

### Steps to reproduce

1. Open any project in 4.3.dev6.
2. Rename any file or folder, either by selecting and pressing F2, or right click Rename...
3. Press ESCAPE. Should cancel but instead the rename takes place.

### Minimal reproduction project (MRP)

Any

**Comment by AThousandShips** [comment]
This should be solved on latest master after:
* https://github.com/godotengine/godot/pull/91112
