### ISSUE TITLE
Shadows don't update when changing blend shape values

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#91871]
### Tested versions

Reproducible in 2ba22d1554ded08094e3869a83bd87487266ad38 (custom build from 2 days ago)

### System information

Windows 10.0.19044 - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

If you change a MeshInstance's blend shapes using code `set_blend_shape_value` in e.g. `_process`, then shadows of an OmniLight3D will not update until you also move the mesh (e.g. by nudging the `position` value slightly).

This happens in Compatibility, Mobile and Forward+ renderers.

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

[blend-shapes-dont-update-shadows.zip](https://github.com/godotengine/godot/files/15285844/blend-shapes-dont-update-shadows.zip)

The cube is animated via blend shapes only. Uncommenting the last line in the cube's script will fix shadows not updating. Change renderer to any other and observe the same problem.

**Comment by clayjohn** [comment]
This will need a bit of investigation to track down. But I think there is one of three things to look for:
1. We may need to notify the dependency system that the variable changed like we do for skeletons:
https://github.com/godotengine/godot/blob/c4279fe3e0b27d0f40857c00eece7324a967285f/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L2293
2. We may need to set the instance to dirty some other way when updating blend shapes. Maybe here:
https://github.com/godotengine/godot/blob/c4279fe3e0b27d0f40857c00eece7324a967285f/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L917-L924

For context `instance_set_blend_shape_weight()` will try to update the instance if it is already dirty. 

https://github.com/godotengine/godot/blob/c4279fe3e0b27d0f40857c00eece7324a967285f/servers/rendering/renderer_scene_cull.cpp#L950-L961

If the instance is flagged as dirty, then we will mark the shadows as dirty. But we could also do it manually when blend shapes are modified:
https://github.com/godotengine/godot/blob/c4279fe3e0b27d0f40857c00eece7324a967285f/servers/rendering/renderer_scene_cull.cpp#L884-L889
