### ISSUE TITLE
Mouse doesn't center 

### ISSUE THREAD

**Issue by PixelQuaker** [godotengine/godot#91885]
### Tested versions

4.2.2 current steam version

### System information

Windows 10 pro

### Issue description

I have the same issue where the mouse is visible and isn't centered even after using
```gdscript 
func ready():
	Input.mouse_mode = Input.MOUSE_MODE_CONFINED_HIDDEN
```

The mouse courser isn't hidden and is still on the window screen, I can move the position around but it stops when I hit the end of the window

### Steps to reproduce

head is a 3d node that contains a camera 3d
```gdscript
@onready var head = $head
func ready():
	Input.mouse_mode = Input.MOUSE_MODE_CONFINED_HIDDEN


func _input(event):
	if event is InputEventMouseMotion:
		rotate_y(deg_to_rad(-event.relative.x * mouse_sens))
		head.rotate_x(deg_to_rad(-event.relative.y * mouse_sens))
		head.rotation.x = clamp(head.rotation.x, deg_to_rad(-89), deg_to_rad(89))
```

### Minimal reproduction project (MRP)

Sorry the project is too big, but the nodes for the head can easily be remade

**Comment by kitbdev** [comment]
Try using `Input.MOUSE_MODE_CAPTURED` instead of confined, see [here](https://docs.godotengine.org/en/stable/classes/class_input.html#enumerations).

**Comment by Calinou** [comment]
Your `_ready()` method is missing an underscore, so `Input.mouse_mode = ...` is never being called.

**Comment by PixelQuaker** [comment]
that fixed it thank you so much :DDDD
