### ISSUE TITLE
MultiplayerSpawner can only spawn one of any type of PackedScene (is this a bug or intentional feature?)

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#91881]
### Tested versions

using version 4.22.... this bug/feature has always existed as far as i recall back to 4.0

### System information

windows 10

### Issue description

sorry i can't tell if this is a bug or a feature do to lack of documentation

when i use the MultiplayerSpawner, i can only spawn one of each type of scene... so one type of bullet, one type of player

### Steps to reproduce

when i use the MultiplayerSpawner, i follow as many instructions as i can possibly find... including examples.

parts were undocumented like i had to add chid to the spawner itself, not it's spawn path.... when i add the child to the Spawner on the server, the client also does copy the spawn

however the name of the spawned object is the same as the orginal scene, and never changes... so adding another one on it will be say

DirtBlock1, DirtBlock2 (auto renamed  by godot)

on the client, only DirtBlock1 will spawn

so please confirm is this a feature? is the MultiplayerSpawner limited this way as i need to get right on an code an alternative if so as i need to spawn multiple bullets.... it seems worth mentioning to prospective users on the docs... warning this only supports one of any type of object

### Minimal reproduction project (MRP)

[test_multiplayer_spawn.zip](https://github.com/godotengine/godot/files/15287021/test_multiplayer_spawn.zip)

**Comment by Protowalker** [comment]
You need to add the child to the spawn path, not the spawner; I'm not sure why you're having that behavior. Also, your MRP should be a whole project rather than just a script so we can get the full context. 

What I can say is that it looks like in your script you override spawn_function and then call spawn manually. You only need to do this if you need to do a custom spawn based on some sort of arbitrary data; by default, just adding the entity as a child of the spawn path will replicate it on all clients.  

You can absolutely have multiple instances of a packed scene from a MultiplayerSpawner, I think there's a bug in your code that's causing issues.

**Comment by RichardEllicott** [comment]
> You need to add the child to the spawn path, not the spawner; I'm not sure why you're having that behavior. Also, your MRP should be a whole project rather than just a script so we can get the full context.
> 
> What I can say is that it looks like in your script you override spawn_function and then call spawn manually. You only need to do this if you need to do a custom spawn based on some sort of arbitrary data; by default, just adding the entity as a child of the spawn path will replicate it on all clients.
> 
> You can absolutely have multiple instances of a packed scene from a MultiplayerSpawner, I think there's a bug in your code that's causing issues.

i have tried both, actually no if you add it to the "spawn path" it doesn't work

no i don't call spawn manually... i have just tried everyway.... have you used this spawner and are able to provide an example that confirms we can spawn multiply objects as i request?

**Comment by RichardEllicott** [comment]
i'm also going to make a better minimal reproduction project... one that someone can just load twice then press some buttons

it is difficult to make a reproduction for this due to network part.... it's gonna end up with multiple parts and an autoload

i was hoping for a simple confirmation the Spawner has this limitation... as upong testing it, i find it doesn't send the name accross to the network........ the multiplayer in Godot needs the same names to syncronise nodes

since it needs the same names, and it doesn't send that name it uses the name that is inside the .tscn file (the root node name)..... i assume it's a known limitation so far

**Comment by Protowalker** [comment]
This is definitely not a limitation of the Node currently. I'm using it in my project here:  
https://github.com/Protowalker/3v3-shooter/blob/main/Components%2FWorld%2Fworld.gd#L35

Make sure the code to spawn the entity is only being called on the authority and make sure that the scene is in the MultiplayerSpawner's list of allowed scenes.

**Comment by RichardEllicott** [comment]
thanks for the example i will work through that, we can shut the ticket if required as if your project here is spawning as it is more than one player and bullet, of the same type of scene, it must be something i'm doing

**Comment by RichardEllicott** [comment]
okay thanks i can confirm this is all my missunderstanding, i followed your example and it was how i was handling the naming, i was expecting when i add it and it went say DirtBlock1, DirtBlock2... automaticly, when i was supposed to set the name in advance and make it unique (so i can either count numbers here or make some random name i think)... so extra testing i got it working normally
