### ISSUE TITLE
Vertex Shader Utilizing INV_VIEW_MATRIX not rendering shadows

### ISSUE THREAD

**Issue by svenar-nl** [godotengine/godot#91894]
### Tested versions

- Reproducible in: 4.3-dev6, 4.2.2, 4.0-stable, 3.6-beta4

### System information

Godot v4.2.2.stable - Ubuntu 23.10 23.10 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 545.29.06) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

**Issue Description:**
Creating a vertex bending shader using `INV_VIEW_MATRIX` produces no shadows wile using a different value (for example `TIME`) does produce a shadow.

**Expected Behavior:**
Shadows should be rendered accurately when utilizing the `INV_VIEW_MATRIX` in the vertex shader, similar to how they are rendered when using values like TIME.

![image](https://github.com/godotengine/godot/assets/11473832/32252ed1-2bd4-4560-8309-55d109b1bf1d)
Shader objects left (image):
```glsl
void vertex() {
	VERTEX.y -= pow(length(INV_VIEW_MATRIX[3].zyz - VERTEX.zyz) / 20.0, 4);
}
```
Shader objects right (image):
```glsl
void vertex() {
	VERTEX.y -= pow(length(sin(TIME) * 15.0 - VERTEX.zyz) / 20.0, 4);
}
```
----

This also exists in Godot 3 with the following shader:
```glsl
shader_type spatial;

void vertex() {
	VERTEX.y -= pow(length(INV_CAMERA_MATRIX[3].zyz - VERTEX.zyz) / 20.0, 4);
}
```

### Steps to reproduce

1. Create a MeshInstance3D with a plane mesh
2. Add the following shader to the MeshInstance3D
```glsl
shader_type spatial;
render_mode world_vertex_coords;

void vertex() {
	VERTEX.y -= pow(length(INV_VIEW_MATRIX[3].zyz - VERTEX.zyz) / 20.0, 4);
}
```
3. Add a MeshInstance3D with a cube mesh and the exact same shader and place it above the other
4. Observe no shadows being casted from the cube onto the plane.

### Minimal reproduction project (MRP)

- Godot 4.3-dev6: [curveissue_4.3.zip](https://github.com/godotengine/godot/files/15290636/curveissue_4.3.zip)
- Godot 4.2.2: [CurveIssue.zip](https://github.com/godotengine/godot/files/15290348/CurveIssue.zip)
- Godot 4.0-stable: [CurveIssue_4.0.zip](https://github.com/godotengine/godot/files/15290640/CurveIssue_4.0.zip)
- Godot 3.6-beta4: [CruveIssue_3.6.4.zip](https://github.com/godotengine/godot/files/15290781/CruveIssue_3.6.4.zip)

**Comment by svenar-nl** [comment]
### Follow up
When manually supplying the shader with the position of the active camera the shadows are drawn correctly.
There is no visual difference between `INV_VIEW_MATRIX` and a manual camera position.

![image](https://github.com/godotengine/godot/assets/11473832/57139929-8bbb-4b05-ac0e-9926919c519e)
Left: Manual position
Right: INV_VIEW_MATRIX

### Minimal reproduction project (MRP)
- Godot 4.2.2: [CurveIssue.zip](https://github.com/godotengine/godot/files/15305350/CurveIssue.zip)
Renderer: Compatibility

**Comment by clayjohn** [comment]
In 4.3 we introduced a new built in variable to handle this situation: `MAIN_CAM_INV_VIEW_MATRIX`. Use that instead of `INV_VIEW_MATRIX` as `INV_VIEW_MATRIX` is the matrix used for rendering the object not the matrix from the camera in your scene. 

There is an important distinction here because when rendering shadow maps the camera used is based on the position and orientation of the light.

**Comment by jsjtxietian** [comment]
Sounds like something that need better documentation?

**Comment by clayjohn** [comment]
Fixes by https://github.com/godotengine/godot-docs/pull/9544
