### ISSUE TITLE
Add complete signal for SamplePlayer when voice play finished

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9189]
**Operating system or device - Godot version:**
2.x

**Issue description:**

There is no signal emit when the voice finished, it would be better to emit a signal.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by vnen** [comment]
There's no SamplePlayer in Godot 3, so this would be valid only for 2.x.

**Comment by alexzheng** [comment]
OK, thanks for your reminder,
updated version for 2.* only

**Comment by alexzheng** [comment]
Also for StreamPlayer please

**Comment by alexzheng** [comment]
Also for the AudioStreamPlayer in 3.0 please!

**Comment by kubecz3k** [comment]
I can see that in 3.0 there is `finished` signal in `AudioStreamPlayer`. I'm not sure but I guess it's working in the way how this feature request is suggesting?

**Comment by KoBeWi** [comment]
Well, unless we are going to implement it for 2.1.x, this could be closed.

**Comment by akien-mga** [comment]
Indeed, closing as fixed in 3.0.
