### ISSUE TITLE
ERROR: Condition "space_state" is true. Returning: SceneStringNames::get_singleton()->Master

### ISSUE THREAD

**Issue by chrisl8** [godotengine/godot#91914]
### Tested versions

 - Reproducible in v4.3.beta.custom_build [557f63d03] (Latest build from Master)
 - **Not** Reproducible in v4.3.dev.custom_build [64520fe67] [Godot 4.3 dev 6](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-6/)

### System information

 - Godot v4.3.beta (557f63d03) - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)
 - Godot v4.3.beta (557f63d03) - macOS 14.4.1 - GLES3 (Compatibility) - Apple M2 - Apple M2 (8 Threads)
 - Godot v4.3.beta (557f63d03) - Manjaro Linux  SMP PREEMPT_DYNAMIC Wed Apr 10 20:11:08 UTC 2024 - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 620 (KBL GT2) () - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 Threads)

### Issue description

When running the game, a steady stream of this error is sent to the console:

```
ERROR: Condition "space_state" is true. Returning: SceneStringNames::get_singleton()->Master
   at: AudioStreamPlayer2D::_get_actual_bus (scene\2d\audio_stream_player_2d.cpp:87)
```

### Steps to reproduce

Clone and start the [Physics-Based Platformer 2D](https://github.com/godotengine/godot-demo-projects/tree/master/2d/physics_platformer) Godot Demo.
Run the game.
Start moving the character around and/or firing and jumping.

You will see the errors in the console and/or in the Debug output.

### Minimal reproduction project (MRP)

Use the [Physics-Based Platformer 2D](https://github.com/godotengine/godot-demo-projects/tree/master/2d/physics_platformer) Godot Demo.

### Bisect
**I have a low confidence in this bisect!**
Some of the commits before this wouldn't build, so this might just be the first commit that would build and also had the issue.
I can do some more bisect work if required.

```
7331187090c5236a72d80709c313502cdfc8e9e9 is the first bad commit
commit 7331187090c5236a72d80709c313502cdfc8e9e9
Author: A Thousand Ships <96648715+AThousandShips@users.noreply.github.com>
Date:   Mon May 13 12:35:05 2024 +0200

    Fix `DisplayServer` overrides

 servers/display_server_headless.h | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)
```

**Comment by matheusmdx** [comment]
Bisecting points to #81303 as the culprit:

![Screenshot_28](https://github.com/godotengine/godot/assets/44306054/11aaddbf-32bd-429f-b910-2bdc9a7ff59f)

I took a look on this merge and found something in the file changes, in the scene/2d/audio_stream_player_2d.cpp file in the line 87, the ERR_FAIL_NULL_V was changed to ERR_FAIL_COND_V, looking the other files changed this was the only place the ERR_FAIL_* was changed so i reverted to ERR_FAIL_NULL_V and compiled again, this solved the error.

![image](https://github.com/godotengine/godot/assets/44306054/709b85a9-95dd-4bcf-8676-34f0b94a8903)

**Comment by jsjtxietian** [comment]
Looks like uintentional error (a slip of the pen) : 

![image](https://github.com/godotengine/godot/assets/8315986/352788ca-1a0a-4def-8ec7-1519e9bc1f8b)
