### ISSUE TITLE
Globals.save() fails with error 12

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#9194]
**Operating system or device - Godot version:**
On Android, probably also on other platforms when res:// is pointing to a read/only directory
Godot 2.1.3 stable

The error might not occur if Android is rooted.

**Issue description:**
I want to change a value in the engine.cfg from GDScript.
"Globals" allows this, but on save it files with error 12 (ERR_FILE_CANT_OPEN). This is because it tries to write the config to its initial position in res:// which is read-only on many platforms.

Saving to another location is possible via Globals.save_customs() but the game/app won't read it on startup. So that is useless AFAIK.

I've seen in the source that godot also tries to read/merge a override.cfg on startup, but also... only from res:// or the current directory. A solution for this problem would be when godot searches for an override.cfg (or whatever) in user:// because that is the directory where files are allowed to be written (usually).

**Steps to reproduce:**
var res= Globals.save()
print("Globals save, result: "+String(res))

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by kubecz3k** [comment]
Also, what would happen when `Globals.save()` would be used in exported release PC build of the game? Would it work? Wondering it the behavior is consistent between platforms (but I know that android has it's limitations).

**Comment by akien-mga** [comment]
Saving to `res://` is indeed not supported, as it's a read-only filesystem once exported.
Regarding ways to override project settings, #23799 may implement that.
