### ISSUE TITLE
An AnimationPlayer controlling another AnimationPlayer ignores the first loop of the animation

### ISSUE THREAD

**Issue by theraot** [godotengine/godot#91956]
### Tested versions

- Reproducible in: v4.3.dev6.official [89850d553]
- Not reproducible in: v4.3.dev5.official [89f70e98d]

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.5244) - Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz (8 Threads)

### Issue description

The issue arrises from the setup I mention in https://github.com/godotengine/godot-proposals/discussions/9712

For abstract: I'm using an AnimationPlayer that controls another AnimationPlayer to add tracks to an imported animation without modifying it.

### Steps to reproduce

- Set an AnimationPlayer with a looping Animation (either created in editor or imported).
- Set another AnimationPlayer with another Animation, with an Animation Playback Track that triggers the Animation in the first AnimationPlayer. Make this second animation also a looping Animation.
- Play the Animation from the second AnimationPlayer (the one that controls the other one with an Animation Playback Track).

Result: Playing the Animation from the AnimationPlayer that controls the other one will result in the initial pose frozen until one loop is completed. Afterwards the animation loops correctly.

This is a regression in Godot v4.3.dev6.

### Minimal reproduction project (MRP)

[animation_wrong.zip](https://github.com/godotengine/godot/files/15313014/animation_wrong.zip)

Note: I initially encountered the issue with an imported animation from an FBX. While it is not evident with the cube I used in the minimal reproduction project above, I assure you that it is not simply the animation not playing, instead that the initial pose is held.

**Comment by matheusmdx** [comment]
Bisecting points to #89794 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/ee8cb91c-3f3a-4161-bb87-2fc45011261a)

**Comment by theraot** [comment]
I got some time to look into this, so I got a build from the master branch (v4.3.beta.custom_build [214968243]) and... It seems to be fixed, so I'm closing this.
