### ISSUE TITLE
Double clicking on variable names followed by assignment or compare operators,  includes the right side value

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#91964]
### Tested versions

v4.3.dev6.official [64520fe67]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

In Dev 6, Double clicking on variable names followed by assignment or compare operators,  includes the right side value.
if there is no space separator between them/
Works correctly in dev 5

### Steps to reproduce

Example screen shots
Double click on str highlights past the assignment
![image](https://github.com/godotengine/godot/assets/930478/0068b239-8657-496a-83f1-734caadfc92d)

Double click on major highlights past the compare
![image](https://github.com/godotengine/godot/assets/930478/fa5f396a-1b7c-4b46-b9c0-9c8da3fb4958)

### Minimal reproduction project (MRP)

see screen shots

**Comment by akien-mga** [comment]
CC @kitbdev - didn't bisect but I suspect it could be one of your TextEdit changes.

**Comment by kitbdev** [comment]
I think it was caused by:
- https://github.com/godotengine/godot/pull/90732

Apparently a virtual space grapheme was used to separate them, but virtual graphemes are now skipped.

- Related https://github.com/godotengine/godot/issues/69254

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by wyattbiker** [comment]
Heya wanted to add that this happens if you click on the right hand value as well. 

E.g.
`code=0123
`
So if you click on **0123** it will also highlight **code**

How much code was changed to cause this issue? I guess I am just saying maybe revert back this particular issue for now, so we can keep testing 6 without much fuss.

**Comment by wyattbiker** [comment]
I hope this makes it through into the beta. It's PITA trying to write code.
