### ISSUE TITLE
Point gaps between tiles in a gridmap ... the cause may be an error in the rendering server for surfaces with compression

### ISSUE THREAD

**Issue by opadin** [godotengine/godot#91962]
### Tested versions

- Reproducible in Godot v4.2.2.stable.mono

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 Threads)

### Issue description

There are gaps (seams) between the tiles in a gridmap.

![image](https://github.com/godotengine/godot/assets/22686586/ebd2cbab-6f77-42b0-a2fc-cfeaff7f824b)

### Steps to reproduce

As far as I know, the error cannot be reproduced with simple means in Godot ... because the compression of a surface can only be switched on via an importer (OBJ, GLB/GLFT, COLLADA).

I rebuilt [this example](https://www.youtube.com/watch?v=VjuyfBaryu8) ... with my own models in blender and own textures ... and was able to reproduce the error (the environment setting is important to see the gaps better: Set Background to Custom Color and White and Ambient Light to Background).

### Minimal reproduction project (MRP)

If a test program is really needed, I will be happy to provide one.

What I can provide, however, are the results of my investigations. I installed scons yesterday, pulled the source code from Godot, (checked out the commit with the tag 4.2.2), debugged it in Visual Studio and used RenderDoc for analyzing the representation.

In my opinion, the cause is a bug in the method `RenderingServer::_surface_set_data()`, namely in the calculation of the AABB if the format flag `ARRAY_FLAG_COMPRESS_ATTRIBUTES` is set. (I say "maybe" because I have only been analyzing the source code in depth for two days and the algorithm that leads to the error was implemented by Juan over seven years ago).

The AABB is calculated as follows (lines 455-461):
```
for (int i = 0; i < p_vertex_array_len; i++) {
    if (i == 0) {
        r_aabb = AABB(src[i], SMALL_VEC3);
    } else {
        r_aabb.expand_to(src[i]);
    }
}
```
A default size is introduced for the first vector so that the resulting AABB basically has an extension in all three directions. This is also necessary as this AABB is used in line 515 to generate the compressed vector:
```
Vector3 pos = (src[i] - r_aabb.position) / r_aabb.size;
```
As it is divided by the size here, this must not be zero.

The problem is that with certain constellations (order of the incoming vectors), the AABB results in an incorrect value.

Example:
```
(-0.5, 0,  0.5)
( 0.5, 0,  0.5)
(-0.5, 0, -0.5)
( 0.5, 0, -0.5)

results in an AABB of

position: (-0.5, 0, -0.5)
size: (1.0, 9.99999975e-06, 1.00001001)
```

The problem here is NOT the size.y value (it's not important because of all y-values of the original four vectors are equal).

The problem is size.z ... which is slightly outside the correct AABB and therefore the calculated compressed Vector of the first one (-0.5, 0, 0.5) is (0.0, 0.0, 0.999989986) ... which leads imho to the wrong representation.

I tested a fast simple fix (use Vector3(0,0,0) as base size and after aabb-calculation correct any size==0) and it worked. My imported GLB/GLTF was properly displayed.

Best regards, Opadin.

**Comment by clayjohn** [comment]
Thank you for your in-depth investigation! I suspect you are right and this will help improve the quality of compressed meshes.

Can you share the diff that you used to fix the issue? You can generate a diff from the command line with `git diff` that way a potential contributor doesn't need to reproduce your work from scratch

**Comment by kleonc** [comment]
Looks like a duplicate of / solution for:
- #79081

Some other similar issues to test/check against the mentioned fix (possibly 3.x version of it, as these are old issues):
- #16337
- #25303
- #27837

**Comment by opadin** [comment]
@clayjohn

As you wish, here is the diff ...

```diff
--- a/servers/rendering_server.cpp
+++ b/servers/rendering_server.cpp
@@ -454,11 +454,16 @@ Error RenderingServer::_surface_set_data(Array p_arrays, uint64_t p_format, uint
                                                // First we need to generate the AABB for the entire surface.
                                                for (int i = 0; i < p_vertex_array_len; i++) {
                                                        if (i == 0) {
-                                                               r_aabb = AABB(src[i], SMALL_VEC3);
+                                                               r_aabb = AABB(src[i], Vector3(0, 0, 0));
                                                        } else {
                                                                r_aabb.expand_to(src[i]);
                                                        }
                                                }
+                                               for (int i = 0; i < 3; i++) {
+                                                       if (r_aabb.size[i] == 0.0) {
+                                                               r_aabb.size[i] = CMP_EPSILON;
+                                                       }
+                                               }

                                                if (!(p_format & RS::ARRAY_FORMAT_NORMAL)) {
                                                        // Early out if we are only setting vertex positions.
```
A few comments on this:
* This is just a quick shot and neither elegant nor optimal.
* At the line `r_aabb.size[i] = CMP_EPSILON;` you could also move the position (`r_aabb.position[i] -= CMP_EPSILON/2`) so that the AA polygon is exactly in the middle of the area.
* For the calculation of the AABB, I would personally attach a method to the class that gets a `const Vector<Vector3>&` as parameter and calculates itself from it.
* It may be necessary to fundamentally rethink the algorithms for mesh compression so that it is not necessary to assume expansion in all three dimensions.

@kleonc

Yeah, I scoured the internet for "Godot Seams Gridmap" and found numerous threads, none of which had a real bugfix, but suggestions like changing the environment to the color of the tiles or scaling the tiles a tiny bit. Unfortunately, this is not my way of working. But since it is my daily work to debug complicated bugs ... I did that and I'm happy if I could help.

With that said, kudos to everyone here. Godot is a fine engine that has everything I need for my purposes. I was amazed at how quickly I was able to compile it in Visual Studio. I like the open source code, which is excellently written by the way.

Greetings, Opadin.
