### ISSUE TITLE
SSR, SSAO, DOF far blur and DOF near blur, seem to disable sky contribution.

### ISSUE THREAD

**Issue by tonydomnickriver** [godotengine/godot#91967]
### Tested versions

- Reproducible in: Godot 3.6 beta 5 
- Not reproducible in: Godot 3.6 beta 4 and other versions before.

### System information

Windows 10 Pro - Godot 3.6 beta 5 - OpenglES 3.0
Core i5 3470 3.20 Ghz - Radeon RX 580 2048SP

### Issue description

while preparing a scene for performance test with occlusion culling and the new LOD system, i first added a world environment node to setup some post processing effects, tonemap, auto exposure, SSR, SSAO, DOF far blur and DOF near blur, SSR for some reason seemed to disable the sky contribution, as with SSAO and both DOFs.

this scene just has SSR enabled and sky contribution is fully enabled.
![Capture](https://github.com/godotengine/godot/assets/151951019/3d69371f-5faf-4060-9860-34314cc7d1a9)
 
this is the scene used for the performance test, just updated to show that the issue doesn't exist in the version 3.5.3,
it also has just SSR enabled and sky contribution is normal.
![Captured](https://github.com/godotengine/godot/assets/151951019/4a86237b-a0a7-4b5f-9794-c9e780205eb0)

### Steps to reproduce

first, add a world environment node followed by a mesh instance then just enable one the 4 mentioned post processing effects and, you should see this.

![Captureder](https://github.com/godotengine/godot/assets/151951019/fef89b7a-82df-4bff-a2a2-22fbf3023203)

### Minimal reproduction project (MRP)

same as the steps to reproduce.

**Comment by lawnjelly** [comment]
Will bisect when home. Probably most likely to be ORM PR, or glFragColor change.

**Comment by matheusmdx** [comment]
Bisecting points to #84529 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/1f81c1a1-d135-4db6-bbd4-1664dfab64fb)

**Comment by lawnjelly** [comment]
Ah thanks! That is good as it should be an easy fix as the change is quite simple. 👍

**Comment by lawnjelly** [comment]
Fixed by #92070.

**Comment by tonydomnickriver** [comment]
thanks! :)
