### ISSUE TITLE
Godot window changing style bug

### ISSUE THREAD

**Issue by yunkeon1029** [godotengine/godot#91977]
### Tested versions

- Reproducible in: v4.2.2.stable

### System information

Windows 11 - Godot v4.2.2.stable

### Issue description

<img width="959" alt="스크린샷 2024-05-15 213430" src="https://github.com/godotengine/godot/assets/124570743/3e432a2f-264c-4084-97c1-3c7cdcf1ce2e">

this kind of screen apears

### Steps to reproduce

1. generate a project in godot 4.1.1
2. open the project in godot 4.2.2
3. run the following code 
```
using Godot;
using System;

public partial class Main : Node
{
    public override void _EnterTree()
    {
        DisplayServer.WindowSetMode(DisplayServer.WindowMode.Fullscreen);
        DisplayServer.WindowSetMode(DisplayServer.WindowMode.Maximized);
    }
}
```
4. press the restore down button

### Minimal reproduction project (MRP)

[BugHunt.zip](https://github.com/godotengine/godot/files/15321573/BugHunt.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70166, as this is due to the same cause.
