### ISSUE TITLE
Older versions of SCons are no longer supported

### ISSUE THREAD

**Issue by ultsi** [godotengine/godot#91986]
### Tested versions

Reproducible after this commit https://github.com/godotengine/godot/pull/91792

### System information

20.04.1-Ubuntu - Godot 4.3.dev

### Issue description

Newest master fails to build with `scons v.3.1.2`, which comes with `sudo apt install scons` on Ubuntu 20.04.

The error:
```
$ scons platform=linuxbsd 
scons: Reading SConscript files ...
TypeError: 'SConsEnvironment' object is not a mapping:
  File "/home/ultsi/dev/godot/godot-src/SConstruct", line 368:
    opts.Update(env, {**ARGUMENTS, **env})
```

After removing the old version of scons and installing newest one from pip with `pip3 install scons`, I was able to build Godot again.

Issue probably is that [this step](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_linuxbsd.html#distro-specific-one-liners) in compile instructions will install an older version of SCons on some distros and compiling will fail.

### Steps to reproduce

1. Install some older version of scons (v3.1.2 tested)
2. Try to build

### Minimal reproduction project (MRP)

[empty.zip](https://github.com/godotengine/godot/files/15324574/empty.zip)

zip empty because project not needed.

### See also:

Documentation issue?  https://github.com/godotengine/godot-docs/issues/9380

**Comment by Calinou** [comment]
On Windows, we recommend using pip to install SCons, but the Linux compilation instructions never did that for some reason. The most likely rationale is that `$HOME/.local/bin` is not part of `PATH` by default on most distributions, so you'd need to add it manually to the `PATH` to be able to run pip-installed scons (with `pip install --user`).

**Comment by AThousandShips** [comment]
Would be useful to update the minimum version check for scons to give better messages as well, if we accept the shift in version limitation

**Comment by akien-mga** [comment]
I'll check which SCons version added what we need, and assess whether we want to bump the min requirement.

**Comment by BloodyMess** [comment]
> I'll check which SCons version added what we need, and assess whether we want to bump the min requirement.

I **_really_** think the min requirement should NOT be bumped. I'm building and runnign Godot master branch just fine on an ubuntu 18.0.4 based distro, and the **only** issue I'm having is this change to the required scons version.

The minimum system and tool requirements should be based on what the engine itself actually needs in order to run, and the build process should be kept compatible with those system & tool versions.

**Comment by akien-mga** [comment]
Like all things, it's a tradeoff. If a higher minimum version means we can use more high level features to make the life of contributors easier, saving them a significant amount of time on a regular basis, IMO it's worth it if the counterpart is that users on an EOL distro like Ubuntu 18.04 have to do `pip install scons` once to compile Godot.

**Comment by BloodyMess** [comment]
> you're missing on a lot of performance optimization from using a more modern version of GCC or Clang.

Actually, I'm not missing that. I build Clang from source also. So I have Clang 16.x on my system.

**Comment by akien-mga** [comment]
Then I think you can install SCons 4.7.0 through pip and also enjoy faster build times :)
