### ISSUE TITLE
[4.3] Editor renders pixelated on macOS + external display

### ISSUE THREAD

**Issue by kevicency** [godotengine/godot#91990]
### Tested versions

- Reproducible in 4.3-dev.4-6 (mono and non-mono)
- Not reproducible in 4.3-dev.3 and earlier

### System information

Godot v4.3.dev6.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

When opening a project in the editor everything is pixelated and the font barely legible. This only happens when the editor is open on my external monitor (Alienware AW3423DWF). Moving the editor window to the macbook display fixes the rendering. The editor also renders fine on the external display when running it on my win11 desktop, it only happens on the mac. The project list also renders fine on mac + external display

Mac + external display
![Screenshot 2024-05-15 at 19 21 51](https://github.com/godotengine/godot/assets/649769/fbce145b-aba9-443f-9cec-78cef3240ed6)

Mac + built-in display
<img width="1247" alt="Screenshot 2024-05-15 at 19 22 07" src="https://github.com/godotengine/godot/assets/649769/9655b2c8-d450-420f-80b8-765e042c6d61">

Display Settings
![Screenshot 2024-05-15 at 19 24 39](https://github.com/godotengine/godot/assets/649769/7d02d63a-e17b-47ce-9384-7e8d7ac46e7f)

### Steps to reproduce

- Open any project on mac + external display

### Minimal reproduction project (MRP)

new default godot project

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/89019.

**Comment by kevicency** [comment]
@Calinou It's not only related to the font rendering though, f.e. the lines in the 3d preview are also not fully rendered. I can also see differences in my game (it looks more pixelated on the external screen)

External
![Screenshot 2024-05-15 at 23 46 25](https://github.com/godotengine/godot/assets/649769/a75d8245-1ba8-469f-a6f2-a6598beeaf2a)

Built-in
<img width="223" alt="Screenshot 2024-05-15 at 23 46 06" src="https://github.com/godotengine/godot/assets/649769/d921360b-d4c3-4c94-a720-95ebd2e1c1fc">
