### ISSUE TITLE
Godot C# exports crash on launch if solution/project/assembly names don't match

### ISSUE THREAD

**Issue by AdamLearns** [godotengine/godot#91998]
### Tested versions

- Reproducible in `v4.2.2.stable.mono.official [15073afe3]`

### System information

M2 macOS - Sonoma 14.4.1

### Issue description / repro steps

This is very easy to repro on both macOS and Windows.

- Make a new Godot project named "GodotRepro"
- Make a scene with anything in it (I just added `icon.svg` as a `Sprite2D` to be able to tell that the project launched correctly)
- Attach a C# script to the root of the scene. Use the `Node2D` template, although it's just the existence of C# that matters for this repro.
- Either rename the `.sln` file that got created or rename the `dotnet/project/assembly_name` project setting to "Repro" (_not_ "GodotRepro")

At this point, if you press the ▶️ button in the editor, the game will run, but if you export to macOS or Windows, the resulting app will segfault.

It would be good if Godot could detect that you're in a scenario where your assembly name doesn't match your solution or project and tell you about it. These repro steps were a simplified version of what I had done, which is to make a game for many, many hours and then finally try exporting it only to find that the resulting app would crash. 😢

### Minimal reproduction project (MRP)

[repro.zip](https://github.com/godotengine/godot/files/15327291/repro.zip)

### Other notes

If anyone searching for this issue finds themselves in this situation, the solution is very easy: just make sure your assembly name matches everywhere that it's referenced. For me, I just renamed my `.sln` file and also the project name within it. They're all `Game` now. 😅

**Comment by raulsntos** [comment]
Godot is not building your C# project because it can't find it, so it assumes it's a GDScript-only project. The crash happens because the game tries to load a `.cs` Resource but .NET is not initialized (since the exported game is not a C# game).

In Godot 4.3, you'll get an error if you try to export a game with `.cs` Resources but Godot can't find the C# project.
- https://github.com/godotengine/godot/pull/87829.

**Comment by AdamLearns** [comment]
Ahh, thank you for the explanation! 🙏 I'm glad to hear that it's going to be fixed, too. 🙂
