### ISSUE TITLE
SSR and SSAO seem to stop working when transparent background is enabled.

### ISSUE THREAD

**Issue by tonydomnickriver** [godotengine/godot#91994]
### Tested versions

- Reproducible in: 3.6 beta 1 through 3.6 beta 5.
- Not reproducible in: 3.5.3 stable and other versions before.

### System information

Windows 10 Pro - Godot 3.6 beta 1/2/3/4/5 - OpenglES 3.0
Core i5 3.20 Ghz - Radeon RX 580 8 Gb

### Issue description

while fiddling with godot 3.6 betas, not just finding one, but at least two unnoticed rendering bugs, as it is written in the title, SSR and SSAO seem to stop working when transparent background is enabled, so yeah, that's my 2nd bug report.

here are some images of the 3.6 betas with the issue.

transparent background disabled.
![Capturered](https://github.com/godotengine/godot/assets/151951019/608b140d-6d82-4336-9d12-a6a92ad425dc)
transparent background enabled.
![Captur](https://github.com/godotengine/godot/assets/151951019/bd8b1b5a-80dc-481c-ae08-0b5835418625)
2nd godot beta images.
![Captur2r](https://github.com/godotengine/godot/assets/151951019/66209c1c-852c-4b96-8a32-e70ed387b6c1)

![Capturer2](https://github.com/godotengine/godot/assets/151951019/3e3546ed-4a14-4948-9499-c50afc9b7dae)
transparent background off.
![Capturer3](https://github.com/godotengine/godot/assets/151951019/3ba713cd-03f8-49dd-a365-8c1c26c03e97)
transparent background on.
![Captur3r](https://github.com/godotengine/godot/assets/151951019/4f800e36-21be-4710-8aaa-80c20bbe07d7)

### Steps to reproduce

simply, add a world environment node set it up, followed by adding a mesh instance or multiple mesh instances, enable SSR and SSAO or just one of them, go to project settings rendering/viewport/transparent_background and, enable Transparent Background, you should see the same background color or similar color as the images above.

### Minimal reproduction project (MRP)

same as the steps to reproduce.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/70670.
