### ISSUE TITLE
Rename "sugar" resource extensions to avoid conflicts with established thirdparty extensions

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9199]
Prompted by the fact that OBJ's `.mtl` material extension is the same as Godot's `.mtl` (and we might want to add support for OBJ's `.mtl` in the future), we propose to rename those "sugar" resource extensions (they're synonyms for the actual `.res` binary format) to avoid conflicts.

The idea is to use full names instead of 3-letter short names, so "mtl" becomes "material" and so on.

Proposal (might have missed some extensions, if so comment):

| Old | New |
| --- | --- |
| anm | animation |
| asogg | oggstream(?) |
| atex | atlastexture | 
| cbm | cubemap |
| cvtex | curvetexture |
| fnt | font |
| gt | meshlib |
| ltex | largetexture |
| mmsh | multimesh |
| msh | mesh |
| mtl | material |
| pbm | pbm (standard) |
| res | res (flagship extension) |
| room | room (no change needed) |
| sbx | stylebox |
| scn | scn (flagship extension) |
| sgp | shadergraph |
| shd | shader |
| shp | shape |
| smp | sample |
| tex | texture |
| thm | theme |
| wrd | world |
| xl | translation |

**Comment by vnen** [comment]
There's also `.gd`, `.vs` and `.gdn`, for GDscript, VisualScript and GDNative. I imagine they can remain the same.

**Comment by Zylann** [comment]
This reminds me of https://github.com/godotengine/godot/issues/8461

**Comment by akien-mga** [comment]
> This reminds me of #8461

Though is that case you had troubles with two non-Godot resources, so there's not much we can do in this issue. So they're quite separate :)

**Comment by reduz** [comment]
I suggest the following, which is the same, just a bit shorter for some to
not make typing an extension that much work:
anm anim
asogg oggstr(?)
atex atlastex
cbm cubemap
cvtex curvetex
fnt font
gt meshlib
ltex largetex
mmsh multimesh
msh mesh
mtl material
pbm pbm (standard)
res res (flagship extension)
room room (no change needed)
sbx stylebox
scn scn (flagship extension)
sgp vshader (will rename to VisualSahder to make more sense with
VisualScript)
//shd I would remove this one, want to use a custom resloader/saver for
.shader so it's text
shp shape
smp sample
tex tex (probably best to leave as is)
thm theme
wrd world
xl translation

**Comment by reduz** [comment]
renaming .fnt to .font is a good idea, makes importing of bmfont from a
.fnt possible

**Comment by novemberist** [comment]
Not that it would likely cause any conflicts, but I think .tex is such a common extension for (La)Tex files, that I personally would prefer something else for textures(maybe tx or txr?). but it's probably not a big issue for people who don't use LaTex and/or don't organize or query their files in a specific way.

**Comment by Zylann** [comment]
As expected, it completely broke my test project, and the dependencies dialog didn't help. I guess I have to re-setup everything^^"

**Comment by vnen** [comment]
@Zylann TBH, I did missed some places in the PR but later added a commit fixing it. Maybe if you update your local fork it'll be solved.
