### ISSUE TITLE
Light baking bugs

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#920]
1) Cell subdiv above 8 gives me

ERROR: resize: Condition ' !_ptrnew ' is true. returned: ERR_OUT_OF_MEMORY
   At: core/vector.h:262.

what results in Editor crash

2) Setting Plot size and Energy Mult to 1 results in baker doing nothing at all.

**Comment by akien-mga** [comment]
Are those bugs still reproducible in the current master branch?

**Comment by trsh** [comment]
Yes!

**Comment by akien-mga** [comment]
What about the new current master branch? :P

**Comment by volzhs** [comment]
It's baking with `GIProbe` now. seems fine to me.

**Comment by trsh** [comment]
@akien-mga sorry, I will not have time to test this for months.

**Comment by akien-mga** [comment]
Light baking is obsoleted in 3.0.
