### ISSUE TITLE
2D Runtime-Baked Navigation Mesh Not Working with Agent

### ISSUE THREAD

**Issue by marcol1** [godotengine/godot#92003]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.3210) - 13th Gen Intel(R) Core(TM) i7-13700HX (24 Threads)

### Issue description

I have created a navigation mesh at runtime using the builtin functions. However, my navigation agents - who work with premade navmeshes, but not the runtime-baked ones - appear to not be recognizing these navmeshes, and just path to their global_position and stand in place.

I've tried the following:
- Adding the regions manually to a new navigation map, and adding the agent to this navigation map.
- I've checked the navigation layers of both the agent & the region.
- I've checked that the agent, map, and region are all active.
- I've attempted to create a path using NavigationServer2D, which fails as well.

It's possible this is my error, something small in the code. However, I think even if there's something missing (and I made a mistake), I'd like to propose we make adjustments to the documentation to provide an example of how to get this to work, since I personally found it unintuitive.

I have attached a reproduction project to assist. Thanks! 

### Steps to reproduce

Attached in project.

### Minimal reproduction project (MRP)

[Pathing Test Project.zip](https://github.com/godotengine/godot/files/15329525/Pathing.Test.Project.zip)

**Comment by smix8** [comment]
A NavigationRegion node is a functionality bundle that does a lot of unasked stuff automatically for users. E.g. setting the changed navigation mesh after the bake on both the node and the server region as an update.

When you parse and bake navigation mesh with the NavigationServer functions you do exactly only that, and not a single step extra. So in this case you need to both manually update your node or server region (if you update the node it will update the server region).

The server sync also happens on the physics process, not normal process so those awaits in script should switch to physics process else those function might "miss" the sync and query an empty map.

**Comment by marcol1** [comment]
Hey @smix8, thanks for the quick response

Any high-level guidance on how I might accomplish this?

Also, any objections to having an example of this in the documentation? I think registering baked navmeshes with agents at runtime is a common use case, especially in games with procedural maps.

**Comment by smix8** [comment]
Not sure what you are missing, if you updated the navigation mesh you set it again on the region, either on the NavigationRegion node or directly on the NavigationServer region.

Examples can be found in the navigation mesh documentation [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationmeshes.html)

**Comment by marcol1** [comment]
Sounds good - I'll see if I can figure it out using those links, and close this issue if it ends up being my fault. Thanks!

**Comment by marcol1** [comment]
@smix8 it looks like I just had to set the navigation_polygon after rebaking it. In my opinion, this is unintuitive, any chance we could add this to the docs, or a clearer spot in the docs? 

From an external perspective, I'd interpret the NavigationPolygon to be a reference, and whenever it changes, the region would register the change.
