### ISSUE TITLE
Fog Sky Affect Not Working in Compatibility Renderer

### ISSUE THREAD

**Issue by Qainguin** [godotengine/godot#92019]
### Tested versions

- Reproducible in 4.2.2

### System information

Godot v4.2.2.stable - macOS 14.1.1 - GLES3 (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

The sky affect variable in the WorldEnvironment node does not seem to do anything even when the fog is enabled.

### Steps to reproduce

1. Create a new Project
2. Create a WorldEnvironment Node
3. Put any type of sky in the Sky parameter
4. Enable Fog
5. Try to adjust the sky_affect variable.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/66456.
