### ISSUE TITLE
AnimatedSprite2D default animation changes when I edit an animation

### ISSUE THREAD

**Issue by sanpii** [godotengine/godot#92011]
### Tested versions

- Reproducible in: 4.2.2.stable

### System information

Godot v4.2.2.stable - Arch Linux - Vulkan (Forward+)

### Issue description

When I edit a sprite animation, this also change the AnimatedSprite2D.

It’s very confusing and painful when I just need to edit the animation speed for example.

### Steps to reproduce

- Select an AnimatedSprite2D;
- Select the attached spriteframe ;
- Select an animation different than the current.

![](https://github.com/godotengine/godot/assets/113045/13cb23bd-1e09-4d94-8707-f4bfd9fe6146)

### Minimal reproduction project (MRP)

Don’t modified the default animation.

**Comment by AThousandShips** [comment]
That's not the default animation, that's the current animation, because it plays the animation you're looking at. There's no "default" but there is an autoplay one, which yo select with the little arrow next to the trashcan

**Comment by sanpii** [comment]
Thank you, I missed this button.
