### ISSUE TITLE
Monospace image font import completely broken in 4.3.dev6

### ISSUE THREAD

**Issue by jummy0** [godotengine/godot#92025]
### Tested versions

- Reproducible in 4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon R7 M440 (Advanced Micro Devices, Inc.; 27.20.20913.2000) - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 Threads)

### Issue description

Monospace image fonts completely fail to import under v4.3.dev6.  All characters are placeholder rectangles.  No error in output.  Image fonts from a previous version work fine, but break when re-imported in v4.3.dev6.

### Steps to reproduce

1. import a monospace image font in v4.3.dev6
2. observe the font failing to appear

### Minimal reproduction project (MRP)

[monospace-image-font-import-test-for-v4.3.dev6.zip](https://github.com/godotengine/godot/files/15339226/monospace-image-font-import-test-for-v4.3.dev6.zip)

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/90647
