### ISSUE TITLE
Godot 4.2.2 Android editor Scrollbar width is too big

### ISSUE THREAD

**Issue by quitelight** [godotengine/godot#92036]
### Tested versions

Godot 4.2.2 Android

### System information

Godot 4.2.2 Android

### Issue description

Running this on Samsung Galaxy Tab S9+ 12.4" screen, and also used DEX to output to a 28" monitor.

The scrollbars appear quite wide and the Minimap crosses over into where only the scollbar should be.

I already tried adjusting the scale, regardless it's the same issue.

![Screenshot_20240517_124925_Godot Editor 4](https://github.com/godotengine/godot/assets/139787492/db77df33-6960-44d0-9c3d-a2af7c2116a0)

### Steps to reproduce

Just open godot 4.2.2 editor on android or via DEX.

### Minimal reproduction project (MRP)

N/A

**Comment by m4gr3d** [comment]
@quitelight If you're using mouse + keyboard, you can disable `Increase Scrollbar Touch Area` under `Editor` -> `Editor Settings...`  -> `Interface` -> `TouchScreen` to restore the scrollbars to the same dimension as on desktop.

The size increase is done to facilitate interactions when using the editor with fingers.

**Comment by quitelight** [comment]
Thanks!

**Comment by m4gr3d** [comment]
Closing the issue as resolved!
