### ISSUE TITLE
Ability to set import settings as default for a resource type

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9203]
Currently there's no way to set default import settings for each type of resource. It would be interesting to, e.g. import all textures without filter by default in a 2D pixel art game.

Talking to @reduz on IRC, he suggested a "Set as default" button for this.

**Comment by reduz** [comment]
this was added recently, closing

**Comment by vnen** [comment]
"Set as default" button is in the presets' list. How does that work if I change the "Import as" dropdown? Will it save that setting too? Would also be good to be able to add custom presets there too, now that I think of it.

**Comment by rtroncoso** [comment]
Hi, is it possible that this feature is not working in Godot 3.0.alpha.build1? I see the "Set as default for 'Texture'" button, but when I click it, it just resets the current texture's default values and it doesn't save the default preset.

This can be tested by modifying any property on the imported texture, then clicking the "Set as default" button and see that the modified properties go back to their original values.

**Comment by vnen** [comment]
@rtroncoso if it's not working then it's a bug. Please open another issue to report it.
