### ISSUE TITLE
Lambdas lose context when used with signals and call_deferred()

### ISSUE THREAD

**Issue by HotNoggin** [godotengine/godot#92033]
### Tested versions

- Reproducible in 4.2.2 Stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 6900HS with Radeon Graphics (16 Threads)

### Issue description

When working on my snake project, I had used this lambda in `_ready()`:
```gdscript
func _ready() -> void:
    hurtbox.area_entered.connect(func(area: Area2D) -> void:
	    if area is Collectable:
		    var collectable: Collectable = area as Collectable
		    #CRITICAL This doesn't work without "self". Engine bug?
		    self.add_segment.call_deferred(false)
		    collectable.collect()
    )
```
When the `self` in `self.add_segment.call_deferred(false)` is removed, there is an error, which appears to say that the object calling this method doesn't exist! What the function does isn't too relevant, because a friend reproduced the error with minimal effort (as seen below in the steps to reproduce).

### Steps to reproduce

Simply use this code in your project:
```gdscript
signal test

func _ready() -> void:
    test.connect(func(): do_thing.call_deferred())

func do_thing() -> void:
    print("hello")

func _process(delta: float) -> void:
    if Input.is_action_just_pressed("ui_accept"):
        test.emit()
```

You'll be met with this error when you press the key:
![image](https://github.com/godotengine/godot/assets/143744752/22cf3395-375a-4092-8c5f-d5f4bc97864f)
You'll also notice in the debugger that all of the object's properties are missing (this might not be a part of the bug, though), and only the properties from the lambda are shown.
Adding `self` before `do_thing` will also cause the issue to vanish.

### Minimal reproduction project (MRP)

[Lambda Reproduction Project.zip](https://github.com/godotengine/godot/files/15342622/Lambda.Reproduction.Project.zip)

**Comment by vnen** [comment]
I can reproduce on 4.2.2 but not on master. I assume this has already been fixed.

**Comment by dalexeev** [comment]
> I can reproduce on 4.2.2 but not on master. I assume this has already been fixed.

* Probably it was fixed by https://github.com/godotengine/godot/pull/91412#discussion_r1586629494.
