### ISSUE TITLE
Should editor always open scripts with external editor?

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#9205]
**Operating system or device - Godot version:**
Godot 2.1 and Godot 3.0 for all platform.

**Issue description:**

I usually use [VSCode](https://code.visualstudio.com) as an external editor to view and write scripts. Every time when I click on the script file in godot editor it works really fine to open the script with VSCode.

But when some thing got wrong with my scripts or a break point reached, the godot editor still open the scripts with external code editor to stop me continue debug the script. This force me to switch godot editor window back from the external code editor. Then I press F10 to continue debug and I will lost the debugger window again. This debug experience is so bad.

Do we really want the scripts opened with external code editor without manaully open it?

I hope there is an option in editor setting to manage this behavior.

**Comment by eon-s** [comment]
Instead of something as far as editor settings, could be an option on the script editor panel itself or in the debug menu (if it is just to control debugging behaviour) so it can be turned on or off quickly.

**Comment by Geequlim** [comment]
@eon-s That sounds good.

**Comment by eon-s** [comment]
This is somehow related to #8392 , which has the opposite problem (internal editor opens instead of external).
