### ISSUE TITLE
Engine crashes when connecting Particles2D's finished signal to queue_free in editor

### ISSUE THREAD

**Issue by BowsahBabeh** [godotengine/godot#92051]
### Tested versions

Happened in Godot 4.2.2, Compatibility mode

### System information

Windows 10

### Issue description

I tried connecting a CPUParticles2D's _finished signal to queue_free() in the editor. Seems convenient to auto-delete particles that way. But this crashes the engine if you have that scene open. Instancing it on other scenes just deletes the particles node, no crash.

I'm guessing this happens because Particles run as `@tool` scripts? Since it deletes the root node, Godot gets confused, panics and sets fire to everything.

### Steps to reproduce

Make a CPUPartciles2D scene, connect its finished signal in the editor to its queue_free.

### Minimal reproduction project (MRP)

![Screenshot 2024-05-17 164942](https://github.com/godotengine/godot/assets/116997158/86ab91f0-abf1-472c-bbf9-9ade1e1c9fc6)

![Screenshot 2024-05-17 164407](https://github.com/godotengine/godot/assets/116997158/bde5d8f2-8074-4455-ad48-91dc904851d3)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/87287

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
