### ISSUE TITLE
Godot project crashes when language is not English

### ISSUE THREAD

**Issue by Noel-Em** [godotengine/godot#92057]
### Tested versions

Every version 4.0 >

### System information

Windows 11 - Godot 4.22

### Issue description

When opening a project from the launcher with a language other than English, the project is likely to crash.

### Steps to reproduce

Literally the description of the problem.
After changing the language from Italian to English it stopped crashing.

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment]
Can't reproduce. Does it happen with any project? If it's project-specific please attach a minimal reproduction project that exhibits this issue.

> Every version 4.0 >

Is that true though? Many users use non-English editor and this is probably the first report of this crash.

**Comment by Noel-Em** [comment]
Ok, I've explored this a bit. It's not Godot's problem. It's my problem, it seems that after installing some launcher like GOG, Vulkan gets corrupted and that's what was causing my problem.
I was sure it was a language problem, but after restarting the computer a few times it started happening again.

Sorry for wasting your time, with this comment I close the issue.
