### ISSUE TITLE
Segfault in Object::clear_internal_extension, reproducable on GDExtension hot reload.

### ISSUE THREAD

**Issue by Splizard** [godotengine/godot#92063]
### Tested versions

- Reproducable in Godot Engine v4.2.2.stable.official

### System information

Linux

### Issue description

When attempting to add support for hot-reloading to the Go GDExtension bindings I have been developing, I have run into a segfault which appears to me like it could be a bug in Godot. 

Object::clear_internal_extension derefences `_instance_bindings[0]`, which my debugger tells me is a `nullptr`. 
![image](https://github.com/godotengine/godot/assets/2015791/f52f297e-2d23-4606-ace8-763b1021e0db)

My GDExtension doesn't setup any instance bindings, it's not clear in any documentation that these are required, other parts of this file are checking whether or not `_instance_bindings` is a nullptr.

@dsnopek, I understand you worked on hot reloading in Godot and you are probably best to comment on this, is this a mistake, or are GDExtensions required to setup instance bindings in order to avoid unsafe behaviour?

### Steps to reproduce

Create a hot-reloadable GDExtension, don't setup any instance bindings, register a class, create an instance of your class in the editor, recompile your extension (with the editor open), unregister any extension classes, segfault.

### Minimal reproduction project (MRP)

Available on request.

**Comment by dsnopek** [comment]
> My GDExtension doesn't setup any instance bindings, it's not clear in any documentation that these are required

It is required to set an instance binding. All instances of Godot classes created by a GDExtension binding should call `object_set_instance_binding()` towards the end of their creation process.

We really do need more documentation about these things! @vnen started a documentation page explaining how to use the GDExtension interface from C, and I even [added a note](https://github.com/godotengine/godot-docs/pull/8751#discussion_r1449310035) on the PR about how `object_set_instance_binding()` always needs to be called. :-)

> @dsnopek, I understand you worked on hot reloading in Godot and you are probably best to comment on this, is this a mistake, or are GDExtensions required to setup instance bindings in order to avoid unsafe behaviour?

The instance binding is needed for more than just hot reload. If you don't set it, then it's possible that a new wrapper class could be created in your GDExtension for the same Godot object. Ideally, you want to have a one-to-one relationship between Godot instances and their GDExtension wrappers.

**Comment by Splizard** [comment]
Thanks, have resolved the issue by calling `object_set_instance_binding` with zero value for binding and an empty (zero-initialised `GDExtensionInstanceBindingCallbacks`. ie
```c
GDExtensionInstanceBindingCallbacks callbacks = {};
object_set_instance_binding(extensionClass, extensionToken, nullptr, &callbacks)
```
