### ISSUE TITLE
Problem with renaming resources in the file system

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92069]
### Tested versions

This only happens in Godot 4.3 dev6, before dev6 this problem is not observed

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When you rename any resource in the file system, a window appears that such a file already exists, although it does not exist.
I tested this on png jpg files as well as tscn and mp3 files.
If after renaming we click on another resource to change focus, this window will not appear, if we press ENTER to apply the new name, it will appear
![war](https://github.com/godotengine/godot/assets/130399274/45c7e7f0-68e0-46d3-aaf0-afc7ee997219)

https://github.com/godotengine/godot/assets/130399274/829292b3-c69e-4e99-835c-96916e278dcd

### Steps to reproduce

1. Create a scene in the file manager, or drag and drop a texture
2. Right-click on the resource and select rename
3. Rename and press ENTER

### Minimal reproduction project (MRP)

Not required

**Comment by AThousandShips** [comment]
This should be solved in most recent versions, but wasn't by dev6:
* https://github.com/godotengine/godot/issues/90473

If you are able please try latest version if you can build yourself 

Closing as resolved but if you can still replicate this please comment and we'll reopen
