### ISSUE TITLE
SConstruct script in main branch is broken on windows

### ISSUE THREAD

**Issue by LUK3D** [godotengine/godot#92065]
### Tested versions

- Reproducible in: Master brach

### System information

Windows  11  - Godot Master branch

### Issue description

I just started learning C++ and I was trying to build a visual studio solution from Godot using `scons` by following the documentation but I got an error when running `scons p=windows vsproj=yes`.
This is the error message:

```
bash
scons: Reading SConscript files ...
ArgumentError: argument 1: <class 'TypeError'>: wrong type:
  File "D:\projects\cpp_experiments\godot\SConstruct", line 23:
    stdout_handle = windll.kernel32.GetStdHandle(c_int(-11))
```

The problem sims to be on this code, but I don't know how to fix it because I'm new to cpp and this is something that I don't understand yet.

```python
if sys.platform == "win32":
    from ctypes import windll, c_int, byref
    

    stdout_handle = windll.kernel32.GetStdHandle(c_int(-11))
    mode = c_int(0)
    windll.kernel32.GetConsoleMode(c_int(stdout_handle), byref(mode))
    mode = c_int(mode.value | 4)
    windll.kernel32.SetConsoleMode(c_int(stdout_handle), mode)
```

### Steps to reproduce

Clone the master branch  and run `scons p=windows vsproj=yes`

### Minimal reproduction project (MRP)

The godot source code

**Comment by huwpascoe** [comment]
> ```python
> if sys.platform == "win32":
>     from ctypes import windll, c_int, byref
>     
> 
>     stdout_handle = windll.kernel32.GetStdHandle(c_int(-11))
>     mode = c_int(0)
>     windll.kernel32.GetConsoleMode(c_int(stdout_handle), byref(mode))
>     mode = c_int(mode.value | 4)
>     windll.kernel32.SetConsoleMode(c_int(stdout_handle), mode)
> ```

if you comment out that offending block of code in the SConstruct file, what new (if any) errors occur?

**Comment by LUK3D** [comment]
> > ```python
> > if sys.platform == "win32":
> >     from ctypes import windll, c_int, byref
> >     
> > 
> >     stdout_handle = windll.kernel32.GetStdHandle(c_int(-11))
> >     mode = c_int(0)
> >     windll.kernel32.GetConsoleMode(c_int(stdout_handle), byref(mode))
> >     mode = c_int(mode.value | 4)
> >     windll.kernel32.SetConsoleMode(c_int(stdout_handle), mode)
> > ```
> 
> if you comment out that offending block of code in the SConstruct file, what new (if any) errors occur?

If I comment that code, the command works.
I'm using it that way for now.

**Comment by akien-mga** [comment]
CC @Repiteo
