### ISSUE TITLE
Minor issue with tools when SubViewport is selected

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92072]
### Tested versions

Happens in Godot 4.3 dev, but does not happen in 4.2.2

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When I select a SubViewport node or its child nodes, then select the move or scale or rotation tool, and hold down the mouse, a selection rectangle appears.
This is hardly a significant problem, but it's worth knowing about.
in 4.2 there is no selection.

https://github.com/godotengine/godot/assets/130399274/1c83d577-8871-4ecb-a81a-15bb6d7f80e6

### Steps to reproduce

Select the SubViewport and simulate its movement in the scene using the move tool

### Minimal reproduction project (MRP)

Not required

**Comment by ryevdokimov** [comment]
It's due to https://github.com/godotengine/godot/pull/86804.

I don't think this is a bug. You're not supposed to be able to interact with these type of Nodes (Popups, Timers, Subviewports, etc.) with the editor gizmo, so it defaults to trying to select something that you can.

**Comment by JekSun97** [comment]
> It's due to #86804.
> 
> I don't think this is a bug. You're not supposed to be able to interact with these type of Nodes (Popups, Timers, Subviewports, etc.) with the editor gizmo, so it defaults to trying to select something that you can.

Then it would be more convenient to make sure that when selecting a SubViewport node, unused tools are hidden or inactive.

**Comment by ryevdokimov** [comment]
What do you mean by unused? That PR makes all tools useable in that state by allowing them to select nodes if a node that can use the gizmo isn’t already selected (with the exception of the select tool, which can always select).

**Comment by akien-mga** [comment]
CC @KoBeWi, WDYT?

**Comment by KoBeWi** [comment]
Looks like the tools are not handled correctly when node in viewport is selected. Instead of doing no-op, it does fallback to selection.
