### ISSUE TITLE
is_plugin_enabled seems not to work as expected

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#92074]
### Tested versions

v4.3.dev.custom_build [29b3d9e9e]

### System information

Godot v4.3.dev (29b3d9e9e) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.171.04) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

These files exist:
res://addons/resource_wrangler
res://addons/resource_wrangler/plugin.cfg

The plugin is also enabled in Settings.

This line:
```Python
print( EditorInterface.is_plugin_enabled("resource_wrangler" ))
```
prints `false`

Looking at the source:
https://github.com/godotengine/godot/blob/bd2300d77a6008167043f23fd91bcc562cde0a19/editor/editor_interface.cpp#L198
```C++
bool EditorInterface::is_plugin_enabled(const String &p_plugin) const {
	return EditorNode::get_singleton()->is_addon_plugin_enabled(p_plugin);
}
```

Leads to:
https://github.com/godotengine/godot/blob/master/editor/editor_node.cpp#L3662
```C++
bool EditorNode::is_addon_plugin_enabled(const String &p_addon) const {
	if (p_addon.begins_with("res://")) {
		return addon_name_to_plugin.has(p_addon);
	}

	return addon_name_to_plugin.has("res://addons/" + p_addon + "/plugin.cfg");
}
```

Which seems that at least the file path comparison should return true. (Which is seems not to?) But how does any of that confirm whether the plugin is actually _enabled_?

### Steps to reproduce

All as above.

### Minimal reproduction project (MRP)

All as above.

**Comment by tracefree** [comment]
Hi! So the way this is supposed to work is that `addon_name_to_plugin` is a `HashMap` that uses the path to the plugin.cfg as a key and the corresponding `EditorPlugin` instance as a value for enabled plugins. So the question is why does your plugin not get added to `addon_name_to_plugin` when you enable the plugin in the project settings. The function works as expected for my own plugin, can you maybe upload an MRP?
