### ISSUE TITLE
"ERROR: FATAL: Condition "!rc_owner" is true." on close after using `GetThemeStylebox` in C#

### ISSUE THREAD

**Issue by kevicency** [godotengine/godot#92076]
### Tested versions

4.3-dev.6

### System information

Godot v4.3.dev6.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

After working on an inventory system which made heavy use of `PanelContainer` and `StyleBoxFlat` i ran into the problem where my game and the editor threw an error on close (`ERROR: FATAL: Condition "!rc_owner" is true.`) and the process had to be manually killed every time. 

I was able to somewhat isolate the issue in an MRP but in my actual project there are more issues that i couldn't reproduce. F.e. i have a custom control which extends `PanelContainer` but as soon a i set a theme overwrite for the panel style box in the editor and start the game / close the editor i get the same error and the editor hangs on close (even without any code accessing the style box overwrite)

### Steps to reproduce

- Remove style panel override in `MyPanelContainer` in MRP (https://github.com/kevicency/godot-issue_stylebox/blob/main/MyPanelContainer.tscn#L8)
- Run game
- Try to close it

### Minimal reproduction project (MRP)

https://github.com/kevicency/godot-issue_stylebox/blob/main/MyPanelContainer.cs

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/89188

**Comment by kevicency** [comment]
Yes i saw that issue and it's probably related but i don't have any audio in my game yet

**Comment by matheusmdx** [comment]
I tried to reproduce the issue but nothing happens here:


https://github.com/godotengine/godot/assets/44306054/a199ab0e-1ae1-4874-bd0a-83edf788cc0d

My specs: Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21912.14) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

**Comment by kevicency** [comment]
@matheusmdx i think it only happens on macOS. i just also tried to reproduce it on my win desktop but i also didn't get the error

**Comment by knightofiam** [comment]
Related to #83973,  #89188.

**Comment by AlexanderLangguth** [comment]
Great that you found and fixed the issue.
Is there any chance this will be included in a patch release? Cause it breaks our CI pipelines.
