### ISSUE TITLE
Changing `Window.unresizable` alters `Window.size`

### ISSUE THREAD

**Issue by Justin113D** [godotengine/godot#92077]
### Tested versions

- 4.2.2 stable
- 4.3 dev 6

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4665) - 12th Gen Intel(R) Core(TM) i9-12900KF (24 Threads)

### Issue description

Changing `Window.unresizable` in code changes the value returned by `Window.size`.

A related issue was reported in #72985.

### Steps to reproduce

1. Create new project
2. Attach script to root node with the following code:
```gdscript
extends Node

func _ready():
	var window := get_window();
	print("Window size before: ", window.size);
	window.unresizable = !window.unresizable;
	print("Window size after:  ", window.size);
```
3. Run project

### Minimal reproduction project (MRP)

[BugReport.zip](https://github.com/godotengine/godot/files/15362891/BugReport.zip)

**Comment by AThousandShips** [comment]
I suspect this is to be expected, the change of resizable changes how the window is decorated, and that probably makes the window adjust some size and not others to maintain one size, this might also simply be an OS limitation 

CC @bruvzg

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/81640

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
