### ISSUE TITLE
OpenGL: SpotLight3D shadows occasionally use the wrong texture after moving the camera away from them

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#92091]
### Tested versions

- Reproducible in: 4.3.dev 5708a3a02

### System information

Godot v4.3.dev (5708a3a02) - Fedora Linux 39 (KDE Plasma) - Wayland - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

When using the Compatibility rendering method, SpotLight3D shadows will occasionally start using the wrong texture after moving the camera away from them. This can be seen in the editor:

https://github.com/godotengine/godot/assets/180032/32b47231-9620-46d8-a059-614a61303969

Once the SpotLight3D starts using the wrong texture, this is permanent: reloading the saved scene or toggling shadows on the SpotLight3D won't fix the issue.

It seems the SpotLight3D uses the directional shadow map instead of the positional shadow atlas. This is made evident by the fact that once you enter this glitched state, hiding the DirectionalLight3D will also hide the SpotLight3D:

Working | Broken
-|-
![compatibility_shadow_error_working webp](https://github.com/godotengine/godot/assets/180032/b05552f2-69ba-43a1-86c1-82c1cb15991d) | ![compatibility_shadow_error_broken webp](https://github.com/godotengine/godot/assets/180032/ba670f57-82e6-44fc-bc0c-4d091cf0dcc9)

(The SpotLight3D node has `visible = true` on both screenshots here.)

No errors are visible in the output log. I haven't managed to reproduce this issue on Forward+ or Mobile, so I assume this is Compatibility-specific.

### Steps to reproduce

- Create a 3D scene with a DirectionalLight3D that has shadows enabled and a SpotLight3D that has shadows enabled.
  - An OmniLight3D with shadows enabled *may* be necessary to reproduce the issue as well, but it might not actually be required.

### Minimal reproduction project (MRP)

[truck_town_compatibility_shadow_error.zip](https://github.com/godotengine/godot/files/15366272/truck_town_compatibility_shadow_error.zip)

**Comment by Rudolph-B** [comment]
I am taking a stab at this.

**Comment by Rudolph-B** [comment]
I am busy testing a solution. 

Basically what would happen is when trying to reuse shadow a shadow texture it would sometimes use a previously generated cubemap texture. This caused the shown behavior as well as causing the omni light to stop updating its texture.
