### ISSUE TITLE
Test files polluting AppData/Local directory

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92097]
### Tested versions

4.3 dev f58a96cfa20530268a9b35efc8cd7ddad1900a8b

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Some tests use ResourceSaver (and probably FileAccess) to write some test files. Example:
https://github.com/godotengine/godot/blob/f58a96cfa20530268a9b35efc8cd7ddad1900a8b/tests/core/io/test_resource.h#L79-L82
The problem is that they save it without any subfolder, creating a mess in that directory. On Windows it's `AppData/Local`, which I doubt it's intended for such things.

There could be a helper method that returns a safe cache directory, which could be a sub-directory of the above folder (with ensured existence).

### Steps to reproduce

1. Run tests (`godot.exe --test`)

### Minimal reproduction project (MRP)

N/A

**Comment by huwpascoe** [comment]
Windows has a temporary files folder for this purpose and an alias to access it:
`%Temp%\file.txt` expands to `C:\Users\user\AppData\Local\Temp\file.txt`

More to the point, the tests should clean up after themselves!
