### ISSUE TITLE
Lost controller input after it went to sleep

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9209]
**Operating system or device - Godot version:** XBox UWP (built with Godot 2.2)

**Issue description:**
After a few minutes of inactivity the xbox controller shutsdown to save power (I guess). When turning it back on, the game won't receive input from the controller anymore.

**Comment by nunodonato** [comment]
closing as this is a feature, not a bug ^_^

**Comment by nunodonato** [comment]
re-opening, according to @Hinsbart the device id should not change when the controller goes on/off. It makes sense because if the device id changes, then the default input actions wont work anymore, as they are binded to device 0

**Comment by vnen** [comment]
Test this with 2.1 please. I changed the way the id works.

**Comment by nunodonato** [comment]
will do, but will take some time as I'm away from home (and the xbox) until 4th of july :/

**Comment by nunodonato** [comment]
confirmed this is fixed

**Comment by akien-mga** [comment]
Does the fix still need to be made in master?

**Comment by vnen** [comment]
@akien-mga most likely. Should this issue be kept open until then?

**Comment by akien-mga** [comment]
Good idea.

**Comment by reduz** [comment]
please do the fix in master :)

**Comment by vnen** [comment]
Forgot about this, sorry!
