### ISSUE TITLE
Copy paste a MultiplayerSynchronizer make replication properties not duplicated

### ISSUE THREAD

**Issue by m21-cerutti** [godotengine/godot#92093]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.5244) - 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 Threads)

### Issue description

When copy pasting a MultiplayerSynchronizer, its properties are duplicated (expected behavior), but also linked (bad behavior). It isn't just the replication windows, since when changing multiplayer authority, both synchroniser try to send their data (and make weird synchronisation).

### Steps to reproduce

In general:
- Make a MultiplayerSynchronizer with properties
- Copy paste (Ctrl-C + Ctrl-V)

Expected result:
- Properties are copied but independant

Current result:
- Properties are linked beetween two different MultiplayerSynchronizer 

https://github.com/godotengine/godot/assets/23432929/b0c9ee65-7364-4084-aa2e-07de65c6927e

### Minimal reproduction project (MRP)

Download full projet from https://godotengine.org/article/multiplayer-in-godot-4-0-scene-replication/
[project.zip](https://github.com/godotengine/godot/files/15366802/project.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/74381

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
