### ISSUE TITLE
Light baking - no good quality options (suggestion)

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#921]
It's hard ( I would say impossible ) to hack to make the scene look great (sharp) with FULL baked light. It mostly overexposed, or/and with lower light (energy) or/and Energy Mult. levels it blurs out the scene:

![blurry_bl](https://cloud.githubusercontent.com/assets/3727523/5295253/d7c2ea7c-7b9c-11e4-86c0-0dbee463a8fc.png)

Even after a long bake It's especially obvious in corners. 

I played with all kinds of settings for hours with no success and found that only good results are produced by combing dyn. Light with Indrect+shadows bake.

**Comment by akien-mga** [comment]
Light baking is obsoleted in 3.0.
