### ISSUE TITLE
Issues with new MeshInstance primitives

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9210]
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master
Intel HD4000

**Issue description:**
I just tested the new MeshInstance primitives and noticed 2 issues:

1. The objects can't be selected in the editor viewport but only from the inspector

2. more severe: trying using the sliders to set properties completely freezes godot for me and slows down my computer massively. probably because moving them even a little bit quickly leads to setting insanely high values? there should maybe be a limit of sane values for certain properties. 

**Steps to reproduce:**
1. add a MeshInstance node and fill Mesh slot with a NewCubeMesh
2. try to edit the primitive's Subdivide properties using a slider (beware: this made my desktop environment freeze completely in some instances)

[edit]
While Godot is frozen after using the slider, it quickly eats up all my system memory and my cpu as at constant 100% (thus the massive slowdown)

**Comment by BastiaanOlij** [comment]
Owh that was quick:)

I'll add in sensible limits on the entry fields, that should stop it getting high values, and indeed if you subdivide objects too far it'll bog down in creating the meshes.

need to look into the selection issue, I'm guessing I need to add gizmos to the objects for that to work, have not done that before:)

Thanks for testing!

**Comment by reduz** [comment]
selection should work, i feel something is casting to ArrayMesh when it
shouldn't

**Comment by novemberist** [comment]
@BastiaanOlij actually all the sliders don't seem to work at all. moving them in any direction just inserts some random very high (negative) number, which is not changed when moving the sliders any further. (this doesn't only affect subdivision property, but things like segment count and subdivision lead to an instant crash)

**Comment by BastiaanOlij** [comment]
@novemberist none of the properties have any range limits set so I guess the sliders take some really wild input. I'm adding range limits now.

It is no longer doing crazy things but the sliders do seem to only accept a single change, gonne need @reduz to have a quick look at that cause I'm not sure what could cause that.

**Comment by BastiaanOlij** [comment]
Thats the first fix, I'm off to sleep, more to come :)

**Comment by reduz** [comment]
i see you fixed stuff, is this working now?

**Comment by BastiaanOlij** [comment]
@reduz I never managed to reproduce the selection issue but the sliders are all fine.
