### ISSUE TITLE
Request to add a function to copy a project from the projects title screen

### ISSUE THREAD

**Issue by 3ttu** [godotengine/godot#92118]
### Tested versions

-

### System information

-

### Issue description

If possible, add a button in the control column that will copy the project and give the option to immediately rename it (and only then, after confirmation, Godot will make a copy of the project folder)

The button can be placed at the very top or after “run”

(sorry if I'm writing in the wrong place)

### Steps to reproduce

-

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead. Please make sure to fill in *everything* on the form there, or if you are unable please open a [discussion](https://github.com/godotengine/godot-proposals/discussions) instead.

Closing as this is not the right place for feature proposals, thank you nonetheless.
