### ISSUE TITLE
Rotation of Tile with Navigation mesh using editor causing invalid Polygon data for the mesh

### ISSUE THREAD

**Issue by phill44-source** [godotengine/godot#92125]
### Tested versions

Reproducable in 4.2.2 stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.24002.92) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

when rotating a Tile with at least one point deviating too much from a simple enough shape (unsure) causes the Engine to bake the navigation mesh of the Tile incorrectly.

![grafik](https://github.com/godotengine/godot/assets/56409558/479f9810-f8fd-4410-8e03-2483fac61f50)
In This picture, at the top there are the preconfigured navigation meshes of the tiles, in the lower ones the formers are rotated using the inbuilt tool.

### Steps to reproduce

-Make a Tilemap
-Set the Navigation mesh of a Tile, while deviating from a simple shape, preferably sharp/a lot of corners
-Place the tile, rotated

### Minimal reproduction project (MRP)

[Test-project.zip](https://github.com/godotengine/godot/files/15369904/Test-project.zip)

**Comment by phill44-source** [comment]
New addition of an Error:
![image](https://github.com/godotengine/godot/assets/56409558/d09aea19-79e5-4cab-b6c4-acbbe85e7c13)

**Comment by libklein** [comment]
I can confirm that this is in fact a bug. See the linked PR for details.
