### ISSUE TITLE
Geometry2D.merge_polygons will always return polygons with counter-clock-wise

### ISSUE THREAD

**Issue by RickyYCheng** [godotengine/godot#92146]
### Tested versions

Godot v4.3.dev6.mono

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.2698) - AMD Ryzen 7 5800U with Radeon Graphics (16 Threads)

### Issue description

This code merges two unit (clock-wise / counter-clock-wise) sqaure polygons, but returns the same result. 
The result polygons are counter-clock-wise. 

According to the document, it should returns a cw polygon if it is a boundary and a ccw one if a hole. 

```gdscript
extends Node

func _ready() -> void:
	var poly1 = [Vector2(0, 0), Vector2(0, 1), Vector2(1, 1), Vector2(1, 0)]
	var poly2 = [Vector2(1, 0), Vector2(1, 1), Vector2(2, 1), Vector2(2, 0)]
	print(Geometry2D.is_polygon_clockwise(poly1))
	print(Geometry2D.is_polygon_clockwise(poly2))
	var merged = Geometry2D.merge_polygons(poly1, poly2)
	poly1.reverse()
	poly2.reverse()
	print(poly1)
	print(poly2)
	var reversed_merged = Geometry2D.merge_polygons(poly1, poly2)
	print(merged)
	print(reversed_merged)
	for poly in merged:
		print(Geometry2D.is_polygon_clockwise(poly))
	for poly in reversed_merged:
		print(Geometry2D.is_polygon_clockwise(poly))
	pass

```

logs:
```
true
true
[(1, 0), (1, 1), (0, 1), (0, 0)]
[(2, 0), (2, 1), (1, 1), (1, 0)]
[[(2, 0), (2, 1), (0, 1), (0, 0)]]
[[(2, 0), (2, 1), (0, 1), (0, 0)]]
false
false
```

### Steps to reproduce

Create a node, copy and apply the script, and run. 

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
See #80035 .

**Comment by RickyYCheng** [comment]
> In both cases, it seems to be correctly merging two polygons to form one, there are no holes, so the polygon is returned in the same orientation in each case (counterclockwise it seems).

Yes this it the spirit. 

In my case, I input some cw polygons and expected a cw one. And I don't know why the union of two Clock-Wise polygons will produce a counter-clock-wise polygon. The document just ignore this point, so my solution is to reserve the output array.
