### ISSUE TITLE
Compatibility OmniLight turns everything green, only for XRCamera

### ISSUE THREAD

**Issue by Fire551** [godotengine/godot#92147]
### Tested versions

reproducible in  4.2.1 and 4.3-dev6 at the least

### System information

Windows 10, i5, Geforce 1070, as well as tested on quest3 (BUILD)

### Issue description

do you guys know of a green-shifting error with omnilights in the compatability renderer, only caused with a xr camera?

- error disappears in other renderers.
- only with a xr camera, uses only a origin, a camera, and the given xrtools starter
- tested in different scenes, tested in different project but with the same assets and
- only with omnilights
- anything in its affecting range is shifted green (albedo wise. acts like any color, alpha and darkness affect it)
- only caused when it has a procedural skybox or fog (sky affect to 0 has no affect)
             (custom color and clear color is fine, but fog breaks it if enabled)
- i dont seem to notice any abnormal choices pertaining to rendering in settings
- havent tested cross-devices (but builds have been tested on a quest 3, no difference)
- seems to happen to all shaders in 3d-space atleast
- light doesnt actually emit when error. 😕
- disabled ambient and reflected light has no affect
- disabling fog in the MATERIAL, does not stop the issue in its respective edgecase

PICTURE NOTE : the directional light is fine, i had it turned off to notice the omnilight easier in these pictures. it doesnt seem to affect the bug. also if it was off for the skybox-only it would've been pitch black. the omnilight is on in all these pictures
![8457](https://github.com/godotengine/godot/assets/52729867/3330946b-348c-4258-a533-6df9978e03fd)
![53254](https://github.com/godotengine/godot/assets/52729867/a1c6c6c0-a2d2-4905-86b7-c96719829fae)
![3213](https://github.com/godotengine/godot/assets/52729867/ac6fd9ab-5eba-4ec6-a375-4aef4e25b62e)
![213](https://github.com/godotengine/godot/assets/52729867/3db39f3f-d195-42ad-a9fe-23e478fed956)

### Steps to reproduce

- use compatability renderer
- use monolight in a scene.
- have fog or procedural sky enabled
- have xrcamera rendering

thats the best i got for ya :/

### Minimal reproduction project (MRP)

how the hell do i fit this in 10Mb???

https://drive.google.com/file/d/1CKaiCyspeKlmJxetN3smaXchhZn4tPtQ/view?usp=sharing

**Comment by BastiaanOlij** [comment]
Still no clue whats causing this, but was able to reproduce this without needing XR hardware:
[StereoFogOmniBug.zip](https://github.com/godotengine/godot/files/15384027/StereoFogOmniBug.zip)

![image](https://github.com/godotengine/godot/assets/1945449/26b07bc4-f8e0-41b3-9fcd-ee174d202a4a)

**Comment by BastiaanOlij** [comment]
This took a lot of puzzling but I found it:

For sky we are using uniform location 4 and optionally 5 for respectively out directional light buffer and our multiview buffer.
In our scene shader we've reserved uniform location 4: `SCENE_EMPTY, // Unused, put here to avoid conflicts with SKY_DIRECTIONAL_LIGHT_UNIFORM_LOCATION.`
But uniform location 5 is our omni light buffer.

Ergo, in multiview we're using the wrong buffer

**Comment by Fire551** [comment]
opened the project on my end using 4.2, it was still green, checked again on 4.3, it was blue. downgraded to 4.1, it was green.

heres 4.1
![image](https://github.com/godotengine/godot/assets/52729867/8b08c16e-eff8-4536-a86c-4fa13c68e42a)

how has this never been brought up in detail?? this is such a blatant visual error. wouldn't almost every quest3 dev run into this??



i noticed it doesnt cause a change on a albedo color of (0,0,255) like the grass, but when using a value of (255, 255, 0) it darkens the color?? what operation can cause this?? some kind of averaging?

![image](https://github.com/godotengine/godot/assets/52729867/7cb9de84-3d71-4f13-b932-b1d207089484)


this is light on
![image](https://github.com/godotengine/godot/assets/52729867/2ef3c36f-a2f5-4691-b6aa-6ffdecfbafcd)

this is light off
![image](https://github.com/godotengine/godot/assets/52729867/18e32d17-9ae1-4cd0-ab34-e2fe7747a1db)



back to 4.3
which seems to be different from yours, where it makes it glow.
also worthwhile noting that the grass still isnt affected

weirdly enough ive noticed something.
so apparently, the bug acts completely different depending if shadows are enabled, it seems to be an "additive" force only to anything with a blue hue. affects end result of albedo
![image](https://github.com/godotengine/godot/assets/52729867/4b4b7796-cbd3-4f42-bab3-5966dfe04b62)
![image](https://github.com/godotengine/godot/assets/52729867/05f34e89-5b75-41f9-9bfb-20679ef95887)

**Comment by BastiaanOlij** [comment]
@Fire551 basically it was just getting junk data for Omni lights, using multiview data from the sky shader instead. So the output will be very unpredictable but definitely completely wrong.
I'm pretty sure this bug goes all the way back to Godot 4.0.
