### ISSUE TITLE
Tileset custom data shows as index (not name) in select mode

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot#92149]
### Tested versions

- Reproducible in v4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

In the tileset menu, when setting custom data from the select tab, custom data shows as an index, rather than the name of that data element:
![image](https://github.com/godotengine/godot/assets/43807990/af77a6a4-36a6-4ac4-a574-1c08e81437e7)

 Custom data is correctly shown by name when in the paint tab:
![image](https://github.com/godotengine/godot/assets/43807990/3c937dea-e163-4b2f-83f5-5eea3ed287f3)

I believe this is a regression from 4.2, where custom data layers were always shown by name. I'd imagine that with more custom data layers it may be difficult to tell which is which from the select tab.

### Steps to reproduce

- Create a tileset
- Give the tileset a custom data layer, name it something meaningful
- Open the select tab and unfold the custom data dropdown
- The label for the data shows the index rather than the name you set for the custom data
- In the paint tab, the data is correctly labelled with your custom data name

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @groud @KoBeWi

**Comment by KoBeWi** [comment]
It's not a regression.

**Comment by groud** [comment]
This is not a regression, there was already a PR opened for that feature in 2022: https://github.com/godotengine/godot/pull/66853.  I think the PR was good enough, but it modified PropertyInfo, which is pretty core.

 Anyway, I've opened https://github.com/godotengine/godot/pull/92322 to close this, it modifies the editor only.
