### ISSUE TITLE
Custom features tags are not respected for custom project settings

### ISSUE THREAD

**Issue by KlugeNico** [godotengine/godot#92165]
### Tested versions

Testet in Godot 4.2.2

### System information

Linux

### Issue description

Custom feature tags defined in the export window are not respected for added custom project settings.

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/19239340/b303137f-6b71-4b67-b0bb-d22c12bcbe4e)
![image](https://github.com/godotengine/godot/assets/19239340/cdb2f90e-c1d7-4236-a9fa-ed3f6874c13e)

Create in export window a custom feature tag (e.g. "demo")
Create in Project Settings a custom Setting for the custom feature tag. (e.g. "custom/build_type.demo" as String)

Check the project setting in the exported project in some way:
...
label.text = "Build type: " + ProjectSettings.get_setting("custom/build_type")

### Minimal reproduction project (MRP)

[FeatureTagProjectSettingBug.zip](https://github.com/godotengine/godot/files/15378759/FeatureTagProjectSettingBug.zip)

**Comment by AThousandShips** [comment]
You need to use the correct method, see [`get_setting_with_override`](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-method-get-setting-with-override)

**Comment by AThousandShips** [comment]
Closing as this is expected and documented, if you still are having problems while using the correct method, please comment here and it can be reopened
