### ISSUE TITLE
animation_started signal fires twice in AnimationTree when using a StateMachine in a OneShot node

### ISSUE THREAD

**Issue by jerbrisebois** [godotengine/godot#92166]
### Tested versions

- Reproduced in v4.2.1.stable.mono.official [b09f793f5]
- Reproduced in v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 31.0.15.5244) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

If a StateMachine is used in the "shot" of a OneShot node in an AnimationTree and a function is linked to the AnimationStarted signal then the function will fire twice despite only occurring once.

![image](https://github.com/godotengine/godot/assets/10050106/e2391c6c-c456-4d1e-b640-77b0280cf936)
![image](https://github.com/godotengine/godot/assets/10050106/4381f48d-89d8-424d-b4f9-88a6feed46a5)
![image](https://github.com/godotengine/godot/assets/10050106/3f341c23-64ea-4a8e-bb0b-97c9cb56b64d)
```

public partial class main : Node3D
{
	[Export] public AnimationTree MyAnimationTree;
	public override void _UnhandledKeyInput(InputEvent @event)
	{
		if (@event.IsActionPressed("enter"))
		{
			MyAnimationTree.Set("parameters/OneShot/request", (int)AnimationNodeOneShot.OneShotRequest.Fire);
		}
	}
	
	private void AnimationStarted(string animationName)
	{
		GD.Print($"Animation Started: {animationName}");
	}

	private void AnimationFinished(string animationName)
	{
		GD.Print($"Animation Finished: {animationName}");
	}
}
```

### Steps to reproduce

Using an AnimationNodeBlendTree as the Tree Root for an Animation Tree, add a OneShot node and feed it into the output. For the "In" node of the OneShot feed a default/idle animation. For the "Shot" node of the OneShot feed in a StateMachine. 

The StateMachine just needs to transition to an animation automatically then transition to the End "At End" of the triggered animation.

In the AnimationTree Node's tab, link animation_started and animation_finished to functions that will print to the console to keep track of when they occur. Also add a function to trigger the OneShot request to fire. Code I used is above in the description

### Minimal reproduction project (MRP)

[AnimTest.zip](https://github.com/godotengine/godot/files/15379372/AnimTest.zip)

**Comment by jerbrisebois** [comment]
> Please try 4.2.2, this might already be fixed

Just tested in v4.2.2.stable.mono.official [15073afe3], problem still occurs. Good call though, I should have tested on the latest from the beginning.

**Comment by TokageItLab** [comment]
OneShot time progression has been rewritten in 4.3, so please test 4.3 if possible

**Comment by jerbrisebois** [comment]
> OneShot time progression has been rewritten in 4.3 by #87171, so please test 4.3 if possible.

Just tested in `v4.3.dev6.mono.official [89850d553]` and as far as I can tell this is functional! I converted my 4.2 MRP to 4.3 and loaded it up, ran it and only saw one notification for the animation starting. Looks like I can close this - thanks!
