### ISSUE TITLE
No gamepad control on UWP with current 2.1.4

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9216]
**Operating system or device - Godot version:** UWP(Xbox One), Godot 2.1.4(git)

**Issue description:**
There is no response from the game controller.
However I still get reports of the strange InputEventKey I reported in #9214 , and gamepad connection changes are also reported, just no buttons, axis, etc

**Comment by akien-mga** [comment]
And as @nunodonato mentioned on IRC, it works on 2.2-legacy.

**Comment by vnen** [comment]
Fixed by fbb4107
