### ISSUE TITLE
Animation player not playing animation clips for first time

### ISSUE THREAD

**Issue by nezvers** [godotengine/godot#92160]
### Tested versions

- Reproducible in 4.2.2 stable, 4.3 dev6
- Not reproducible 4.2.1 stable

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Visually it looks like it's stuck on the first frame until something happens (loop, other animation in tracks triggers - not in our production).
At first I thought that freeze happens for each first animation from unique AnimationLibrary (wasn't like that).
In reproduction project that happened only for the first clip. I tried to duplicate a node set and trigger next animation and create a node set from scratch.

### Steps to reproduce

- Create animations
- Trigger those animations from master AnimationPlayer's animation track

### Minimal reproduction project (MRP)

[Animation clip animations.zip](https://github.com/godotengine/godot/files/15377810/Animation.clip.animations.zip)

**Comment by TokageItLab** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/90960, please check if you can.

**Comment by matheusmdx** [comment]
I can confirm the pr #90960 fixes this issue

<br>

v4.3.dev6.official [89850d553] (look in the first seconds nothings happens)

https://github.com/godotengine/godot/assets/44306054/ba8d8fc1-56b8-4885-b6c2-9e2d276b9d92

<br>
<br>

v4.3.beta.custom_build [5833f5978] (now play the first animation correctly)

https://github.com/godotengine/godot/assets/44306054/dfba2d7f-1e59-44f9-ba1b-75ac3caa60d1
