### ISSUE TITLE
get_node() doesn't see node properties

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92185]
### Tested versions

Happens in all versions of Godot 4+, but does not happen in Godot 3.5.3+

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

Previously, when writing code in Godot 3.5.3, I always used code like this:
get_node("AnimationPlayer").play("anim")

Now get_node does not see the functions and parameters of the node specified in the argument, but the $AnimationPlayer method does see the node parameters.

https://github.com/godotengine/godot/assets/130399274/1d8a90d0-37f4-49fb-986f-3fa47a7d98da

### Steps to reproduce

write get_node in the code, specifying any child node as an argument, and try to find the functions of this node in the tooltips

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/86172

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
