### ISSUE TITLE
CircleShape2D radius can only increase/decrease in steps of .5

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#9219]
**Operating system or device - Godot version:**
Debian 9 - 3.0

**Issue description:**
When updating the radius of a CircleShape2D from a CollisionShape2D, the radius can only be increased in steps of .5, so you can only have either 1, 1.5 or 2.

No 1.25 or 1.3 and such, and I would like it to be like the scale property where you can have 0.6850.. I know, that amount of decimals is not a needed function, but still.

**Comment by Zylann** [comment]
Was this initially for being pixel-perfect somehow?

**Comment by vicguedez** [comment]
Uhm no, my sprites get scale up/down very very often, so I need my CollisionShape2D (which has a CircleShape2D) to adjust to the sprite new size, and I want it to be as accurate as possible.

**Comment by bojidar-bg** [comment]
Note, result of #866's fix.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
This is still valid in 3.0, and a bit better in the master branch, as it still increments in .5 but it allows you to type values with .1 of precision.

To properly solve this, a better input workflow is needed where the "common sense" values given for the slider can be more freely overridden by manual input. In the master branch there is a new feature allowing manual input below and above the min and max of the slider range, but no setting to allow more precision than the slider's step. (I'll open a new issue for that though)

**Comment by akien-mga** [comment]
Closing as superseded by #19242.
