### ISSUE TITLE
Text cursor not displaying when duplicating in file system (4.3)

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot#92193]
### Tested versions

- Reproducible in 4.3.dev6

### System information

Godot v4.3.dev6 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

When duplicating assets in the file system dock, the text cursor (the | bar that flashes showing where you're selecting) doesn't display. 

You can highlight chunks of text like normal:
![image](https://github.com/godotengine/godot/assets/43807990/64318748-99a2-4ef0-9b89-61e32a1430ee)

But when not highlighting text, the flashing | doesn't show, so can't tell where text will appear when you type:
![image](https://github.com/godotengine/godot/assets/43807990/b04c98b1-2dd2-40f9-9012-e24d30e3a4e4)

### Steps to reproduce

- Duplicate any asset from the file system dock
- A popup opens asking you to name the duplicate. The text field here doesn't show the text cursor.
- Sometimes the cursor does show, in which case closing then trying to duplicate something again will hide the cursor.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
This is a duplicate of #90569 and was already fixed by #91361 in master branch

![image](https://github.com/godotengine/godot/assets/44306054/aa35de2a-65d7-4348-94db-a0f114f6d2ca)

**Comment by JUSTCAMH** [comment]
Awesome, thanks!
