### ISSUE TITLE
Baking progress lost after closing editor

### ISSUE THREAD

**Issue by trsh** [godotengine/godot#922]
Godot GI has a nice feature for pausing and resuming light baking. Sadly the progress is lost after closing the editor. I think it can be easly tunded so it's not?

**Comment by akien-mga** [comment]
I'm not sure it would be so easy to save such a work-in-progress processing. Should it be added in the scene file?

**Comment by trsh** [comment]
I can't tell you, as I'm not an active godot C developer.

**Comment by akien-mga** [comment]
Closing as wontfix, I don't think we can reasonably support this. And it doesn't appear to be a much request feature either.
