### ISSUE TITLE
[3.0] New way of testing InputEvent type via extends failed

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#9220]
**Operating system or device - Godot version:**
Windows 10 64bits Godot 3.0 last fixnum build

**Issue description:**
While trying to convert my project to early version of 3.0, I am erasing the default InputMap then setting up from configfile.
And with new kind of InputEvent not being core type, I have syntax error:
```
105 print("Loading Key binding")
106 	for action in InputMap.get_actions():
107 		for event in InputMap.get_action_list(action):
108 			if (event extends InputEventKey):
109 				InputMap.action_erase_event(action, event) 
```
error(108,14): Expected ')' in expression

**Comment by karroffel** [comment]
@TotCac the operator got renamed to `is`

`if (event is InputEventKey): ...`

**Comment by TotCac** [comment]
sorry was reading @reduz twitter post about core change.

Closing

**Comment by gtsiam** [comment]
Will make a new issue if no one notices it, but to avoid clutter in the issues tab: the "extends" keyword is still being highlighted in the editor. Maybe remove that highlighting to avoid confusion?

**Comment by akien-mga** [comment]
`extends` is still a keyword used at the top of your script, or when defining inner classes.

**Comment by gtsiam** [comment]
Oh, sorry, forgot about that :stuck_out_tongue:. I'm glad I did not open a new issue for that.
