### ISSUE TITLE
Issue in ParallaxBackground and ParallaxLayer.

### ISSUE THREAD

**Issue by eternityxs** [godotengine/godot#92210]
### Tested versions

4.3

### System information

Windows 10 - Godot Engine v4

### Issue description

Hi all. I am a newcomer studying the creation of 2D platformers in Godot Engine. An error arose when creating the simplest parallax, almost without the use of code. Attached the video. That is, parallax does not work well, the button has fun.

bg.gd:

```
extends ParallaxBackground


var speed = 100


func _process(delta):
	scroll_offset.x-= speed * delta
```

menu.gd:

```
extends Node2D


func _on_play_4_pressed():
	get_tree().quit()
	 # Replace with function body.


func _on_play_5_pressed():
	get_tree().change_scene_to_file("res://level.tscn")
```

### Steps to reproduce

Parallax does not work well, the button broke.

### Minimal reproduction project (MRP)
Project:

[Whispers of Flame.zip](https://github.com/godotengine/godot/files/15392987/Whispers.of.Flame.zip)

Video:

https://github.com/godotengine/godot/assets/170451422/ab81c4ab-2020-4370-ba83-382d95380c53

**Comment by AThousandShips** [comment]
The official language of these channels is English, please make any reports or comments in English, if you do not know English please use some translation software or ask for help.

**Comment by markdibarry** [comment]
Tested in 4.3 and is fixed. I assume it was one of the culling issues we had.
