### ISSUE TITLE
Empty scenetree with unsaved scene

### ISSUE THREAD

**Issue by ultsi** [godotengine/godot#92214]
### Tested versions

- master with custom commits
- Godot v4.3.dev6

### System information

Godot v4.3.dev6 - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Empty scenetree on unsaved scene, when switching from non-initialized unsaved scene. 

### Steps to reproduce

1. Create new scene A
2. Add a 3D root node
3. Create new scene B, don't create a root node
4. Switch back to scene A [unsaved]

Scenetree should now be empty. 

The empty scenetree can be fixed by switching to a saved scene and then back, then the unsaved scenetree appears again. 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can you replicate this on an unchanged branch? The commit you reference isn't part of the repo

**Comment by ultsi** [comment]
@AThousandShips yes was able to repro on Godot v4.3.dev6

**Comment by AThousandShips** [comment]
And on latest master as well? If you're able to test

**Comment by ultsi** [comment]
Yeah sure, let me recompile

**Comment by ultsi** [comment]
https://github.com/godotengine/godot/assets/6347200/81c26e37-06bd-48fb-8edd-c85b9ee38b35

Here's a simple repro video (if it works)

**Comment by AThousandShips** [comment]
I can confirm on latest master

**Comment by matheusmdx** [comment]
This is a regression caused by #86605:

![image](https://github.com/godotengine/godot/assets/44306054/43c3e493-4e93-4d8d-bf95-1d15f5e71579)
