### ISSUE TITLE
Autocompletion of animation names stops working when type hints are added to AnimationPlayer, AnimatedSprite2D and AnimatedSprite3D variables in GDScript

### ISSUE THREAD

**Issue by RayJJ** [godotengine/godot#92219]
### Tested versions

Reproducible in 4.2.2.stable and 4.3.dev6. Was present before 4.2.2 but first appearance not established. Occurs in both MacOS 14 and Windows 11.

### System information

Godot v4.2.2.stable - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

Adding type hints to variables referencing AnimationPlayer, AnimatedSprite2D and AnimatedSprite3D  prevents autocompletion from showing available animation names when editing their respective play() functions. This is true if the type hints are added manually and also if added automatically by Godot when 'add_type_hints' is set true in Editor Settings.
Inferring types with ":=" and using dynamic typing does not prevent autocompletion.

### Steps to reproduce

Add an AnimationPlayer, AnimatedSprite2D and AnimatedSprite3D to an empty scene. 
Assign the node to an @onready variable.
Add a line of code in any GDScript function to call the play() function of the instantiated node.
Note the presence / absence of autocompletion lists of animation names when the @onready declaration assumes a dynamic type or infers a type compared with when it has a type hint.

### Minimal reproduction project (MRP)

[automplete_problem_test.zip](https://github.com/godotengine/godot/files/15394943/automplete_problem_test.zip)

**Comment by RayJJ** [comment]
Added note: For anyone that has been puzzled, as I was, by the lack of, or disappearance of, autocompletion lists on these nodes, the workaround for me was simple: just delete their type hints and autocomplete works as expected.

**Comment by matheusmdx** [comment]
Bisecting points to commit 6f8cc1b8deafa6d7e2ddc22dc71fff672b491f90 (added in #85784) / #79386 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/1311d826-9394-4e72-9d91-74ef306f9f1e)

**Comment by dalexeev** [comment]
^^ CC @HolonProduction

**Comment by HolonProduction** [comment]
This is the second regression on this PR, it's haunting me T_T

To suggest argument options, we need the value of the get node literal but since #79386 we drop it all together if a type was annotated. This should probably only happen if the value has a different type

**Comment by RayJJ** [comment]
Thank you everyone. That was a really impressive turnaround time.

**Comment by Copperplate** [comment]
This bug still affects 4.6.1 and 4.7 beta if "as AnimationTree" is used when declaring the `@onready` variable. I suppose there is no valid reason to declare the variable this way (except to satisfy the "Safe Line" color, although type inference also satisfies it), but nevertheless, the bug still persists in these edge cases:

```
#Works:
@onready var animation_tree: AnimationTree = $AnimationTree
@onready var animation_tree := $AnimationTree

#Breaks:
@onready var animation_tree: AnimationTree = $AnimationTree as AnimationTree
@onready var animation_tree := $AnimationTree as AnimationTree
```

If either of the above broken declarations are used, autocomplete will **NOT** work for the parameter path here:

```
func hurt() -> void:
	animation_tree.set(&"parameters/OneShot/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)
```

Thank you all for your excellent contributions to Godot. :-)

**Comment by matheusmdx** [comment]
@Copperplate Please, open a new issue as this one is already closed a long time ago

**Comment by Copperplate** [comment]
@matheusmdx Thanks for the reply. I certainly could do that, but is it necessary in this case? It seems this is 100% related to the original issue, but is just an edge case that was not included in the original fix. Probably most devs do not add the inline cast during an `@onready ` variable declaration, which is why this issue never showed up during validation.

**Comment by HolonProduction** [comment]
I did infact think about casts when working on this. And at the time I didn't think it should suggest hard coupled options in this case. That's because the only usecase of this cast based asignment I could come up with, was generic code that was supposed to work with arbitrary scenes. (Not a hill I'm going to die on.)

So yes a new issue is necessary to have this conversation propper. Besides we are not going to reopen a 2yr old issue for something that's not even mentioned in the original post.

**Comment by Copperplate** [comment]
@HolonProduction  Okay, thanks for the clarification. I will open a separate report.
