### ISSUE TITLE
Tab Container Children Don't Have Correct Transformations in Scene Editor

### ISSUE THREAD

**Issue by SparkerPlug** [godotengine/godot#92221]
### Tested versions

Reproducible in 4.2.2

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5222) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When creating a tab container and having children with it, the first one appears fine. Both in play mode and scene editor. The second appears fine in play mode, but in scene editor the position/scale/anchor do not appear normal. It's warped and not the correct size, scale, or position.

### Steps to reproduce

Looking at my sample code:
Take a look at the enabled tab 1. Text is readable and takes up the whole container/tab.Take a look at the Tab1->Layout->Transform and take note of the size and position.

Click Run Project. Take a look at tab1 and tab2. Look fine. Stop the running project.

Now disable Tab1 and enable Tab2 in scene view. Take a look at the text. Now look at Tab1->Layout->Transform and take a note of the size and position. It is quite different. 

### Minimal reproduction project (MRP)

[BuggedTabContainer.zip](https://github.com/godotengine/godot/files/15395070/BuggedTabContainer.zip)

**Comment by kitbdev** [comment]
- Looks the same as https://github.com/godotengine/godot/issues/74653
- Fixed in 4.3 by https://github.com/godotengine/godot/pull/87194

**Comment by AThousandShips** [comment]
Closing as per the above
