### ISSUE TITLE
"Parser bug: Mismatched external parser" on exported project with binary resource conversion enabled

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#92233]
### Tested versions

Reproducible in current master (214968243c442c0fdcbdfef23943c1547aeafdbc)

### System information

Arch Linux, Windows

### Issue description

After I export my project I get a `Parser bug: Mismatched external parser` error on this line https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_analyzer.cpp#L909

Disabling "Convert Text Resources to Binary" seems to fix the issue.

After running a bisect, the offending commit appears to be 6b88c86cec1f38934730beca613ee29df5643f6a

Indeed, grabbing current master and reverting the commit seems to fix it.

### Steps to reproduce

I unfortunately haven't been able to reproduce it yet outside of my project, I am trying though, and I think it *may* be related to autoloads and some issue with global classes.

Breaking into the line raising the error with a debugger reveals that the error happens when parsing my project's first autoload and ends up at a chain of global classes, where the last one is HBUserSettings.

### Minimal reproduction project (MRP)

I've been trying for a few days to reproduce it outside my game and unfortunately I haven't been able to, if anyone is feeling adventurous you can try compiling the game with https://github.com/EIRTeam/godot/tree/shinobu_gd4/ and https://github.com/EIRTeam/Project-Heartbeat

I'll keep trying.

**Comment by Glorax** [comment]
I believe this has regressed in 4.3beta2.
<img width="737" alt="Screenshot 2024-07-07 at 10 16 16 PM" src="https://github.com/godotengine/godot/assets/114269106/e624ec62-4bbc-4115-b7af-2650197697ba">

**Comment by akien-mga** [comment]
@Glorax Can you provide a minimal reproduction project?

**Comment by Glorax** [comment]
> @Glorax Can you provide a minimal reproduction project?

I cannot. I am using this project as a basis: https://github.com/Phazorknight/Cogito

I did not write this code myself, and the errors provide essentially no information about what, specifically, is causing them. I don't even know which files are bugged. For all I know, every script could have an issue, or the errors could all be concentrated in a single script. I've done some minimal research into the causes of parser errors, but it's all a bit opaque to me. In short, if I knew how to create a minimal reproduction project, I would likely have already fixed the issue on my end.

The best I can recommend is to just use Cogito as a reproduction project, even if it's not minimal. This is the version of Cogito I'm using, and I can guarantee that the errors will show up on project load when freshly unzipped. I am using the mono version of 4.3.beta2.

The errors won't show up in the COGITO_0_MainMenu scene. They show up when loading scenes 1-4 under "DemoScenes".

[Cogito-main.zip](https://github.com/user-attachments/files/16133868/Cogito-main.zip)

**Comment by akien-mga** [comment]
I can reproduce it when loading that project indeed. It's a different bug though as the one which was fixed here was specific to export projects with binary resource conversion.

The new bug described later happens in the editor itself. So this should be in its own bug report.
