### ISSUE TITLE
Color picker fails to update RGB values when selecting different color properties in the Inspector

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#9224]
**Operating system or device - Godot version:** Windows 10 - Godot Git https://github.com/godotengine/godot/commit/bd33fd0435b2d0dc97a7abb3e68b594185f4e6c3

**Issue description:**
The color picker will fail to update the displayed RGB values when selecting different color properties in the Inspector. It always happens when switching colors, and can thus be reproduced in a consistent manner. Clicking the color property again after switching will display the color's RGB values correctly.

**Steps to reproduce:**

1. Select a node or a resource with at least two color properties, then click on one of the color properties in the inspector. This works fine.

![color_1_working](https://user-images.githubusercontent.com/180032/27242992-137f3706-52e0-11e7-9fe3-909524ccaa07.png)

2. Deselect it, and select another color property in the same node or resource. The correct color is displayed, but notice how the RGB values below it are not the correct ones - they are the values of the previously selected color.

![color_2_broken](https://user-images.githubusercontent.com/180032/27243012-32d701ec-52e0-11e7-8bae-cdb2d190af2f.png)

3. Click on the second color property again, and the RGB values will display correctly.

![color_2_working](https://user-images.githubusercontent.com/180032/27243015-3c9d088e-52e0-11e7-82d5-a232e22dca25.png)

**Comment by remorse107** [comment]
I have a fix for this coming.

**Comment by bojidar-bg** [comment]
Closing as fixed by #9249.
