### ISSUE TITLE
Animation panel plays newly loaded animations inconsistently

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#92249]
### Tested versions

- Reproducible in 4.3.dev bd2300d
- Not reproducible in 4.2.1 or 4.2.2

### System information

Godot v4.3.beta (b53b23be6) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Newly loaded animation libraries will play incorrectly, especially the Hips bone.
Here is the video showing the issue:
https://github.com/godotengine/godot/assets/39946030/a33e1ec8-5332-4912-b3cc-5a23227cb8f3

Scrubbing through the track does not solve the issue. It is necessary to play the bad animation, then switch to another animation then switch back.

The deterministic checkbox does not seem to take effect immediately, but using a scene where deterministic was already checked might avoid the issue. Saving the scene with the animation library already loaded will also avoid the issue.

### Steps to reproduce

ignore main.tscn. The problem does not reproduce if the scene is saved.

- Right click skeleton.fbx -> New Inherited Scene
- Select AnimationPlayer
- Click Manage Animations.
- Click Load Library and choose simplestanding.library.res
- Select the simplestanding animation in the animation panel.
- The hips bone will be locked in place.
- Scrubbing through the timeline and selecting other animations will not fix the issue.
- Play the animation. The hips will slide (gltf) or be locked in place (fbx).
- Select a different animation, then select simplestanding again.
- The animation will now play correctly.
- Load main.tscn. The problem does not happen on a scene that was saved.

### Minimal reproduction project (MRP)

[FirstHumanAnimationWrong.zip](https://github.com/godotengine/godot/files/15401421/FirstHumanAnimationWrong.zip)

**Comment by lyuma** [comment]
Any relation to #91904 or #92160 ?

My build does already have PR 90960 merged so it's not that.

**Comment by matheusmdx** [comment]
Bisecting points to #86715 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/a68639dd-42ba-44bf-a568-c5485da2dbf6)
