### ISSUE TITLE
"Can't find file" error messages when reimporting a gltf scene

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#92250]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Reimporting a gltf file throws a "Can't find file" error message for each texture that it has

https://github.com/godotengine/godot/assets/60579014/b7a8a5be-3021-46f2-bf22-f8b74de88d64

It's possible that it's because textures are getting rewritten, but since all of the files are still there after re-export it shouldn't throw error messages

### Steps to reproduce

Re-export from MRP

### Minimal reproduction project (MRP)

https://drive.proton.me/urls/3RTJBP67YG#kLI0frQNo6Ga

**Comment by huwpascoe** [comment]
This happens on 4.2.2. ...I've got used to ignoring it.
