### ISSUE TITLE
Stuttering regression between Steam and Stable version (from custom build)

### ISSUE THREAD

**Issue by m21-cerutti** [godotengine/godot#92269]
### Tested versions

Regression on :
* Steam: v4.2.2.stable.official [15073afe3]

Versus lastest tested version :
* Custom build : v4.2.stable.custom_build [46dc27791] on Commit: 46dc277917a93cbf601bbcf0d27d00f6feeec0d5

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.5244) - 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz (16 Threads)

### Issue description

Seems that my Steam version and my custom build based on a stable version have a difference of behaviour and make stuttering character movements.
Have tried plugin recommended from documentation, but it is not working https://github.com/lawnjelly/smoothing-addon/tree/4.x.
Maybe related to https://github.com/godotengine/godot/issues/84137

Stable version first, and steam version second where we can see stuttering/jittering.

https://github.com/godotengine/godot/assets/23432929/4540614d-c0d2-4b41-a4b6-b5333da3c025

### Steps to reproduce

Use the minimal reproduction and click on screen.

### Minimal reproduction project (MRP)

[JitterChara.zip](https://github.com/godotengine/godot/files/15409340/JitterChara.zip)

**Comment by m21-cerutti** [comment]
Seems after installing last driver Nvidia it solve the problem, but I don't know why it have happened differently on those two versions.

**Comment by akien-mga** [comment]
My hypothesis would be that the two binaries had different profiles in the Nvidia settings, and someone one of them was misbehaving with that driver version.

Closing as this was solved by updating drivers.
