### ISSUE TITLE
Godot 4 motion blur glitch

### ISSUE THREAD

**Issue by KingGD24** [godotengine/godot#92260]
### Tested versions

4.2.stable

### System information

Windows 10 - Godot v4.2.stable - Vulkan (Forward)

### Issue description

I am trying to add motion blur in my game, so I used this plugin for [motion blur](https://godotengine.org/asset-library/asset/1499) but its not working properly in Godot 4 for any reason, but [motion blur for Godot 3](https://godotengine.org/asset-library/asset/211) working properly, so how can I fix it and why its happening? also I want to off motion blur while walking, here are the images

Godot 3x

![demo](https://github.com/godotengine/godot/assets/156816767/8377cb2f-72a3-4935-a662-9cbf84a50871)

Godot 4x

https://github.com/godotengine/godot/assets/156816767/54a72852-f4dc-4139-8b2b-b9c21757194c

Here the edges of the motion blur are glitchy I means the border of the motion blur in the whole screen are glitchy.

How can I fix it, I think it is a bug of Godot.

### Steps to reproduce

Codes:
-------------------------------

    shader_type spatial;
    render_mode depth_test_disabled, depth_draw_never, unshaded, cull_disabled;
    
    uniform vec3 linear_velocity; 
    uniform vec3 angular_velocity; //rads
    uniform int iteration_count : hint_range(2, 50);
    uniform float intensity : hint_range(0, 1);
    uniform float startRadius;
    
    uniform sampler2D DEPTH_TEXTURE : hint_depth_texture, filter_linear_mipmap;
    uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, filter_linear_mipmap;

    void fragment()
    { 
	    float depth = texture(DEPTH_TEXTURE, SCREEN_UV).r;
	    
	//Turn the current pixel from ndc to world coordinates
	vec3 pixel_pos_ndc = vec3(SCREEN_UV*2.0-1.0, depth*2.0-1.0); 
    vec4 pixel_pos_clip = INV_PROJECTION_MATRIX * vec4(pixel_pos_ndc,1.0);
    vec3 pixel_pos_cam = pixel_pos_clip.xyz / pixel_pos_clip.w;
	vec3 pixel_pos_world = (inverse(INV_VIEW_MATRIX) * vec4(pixel_pos_cam, 1.0)).xyz;
	
	//Calculate total velocity which combines linear velocity and angular velocity
	vec3 cam_pos = inverse(INV_VIEW_MATRIX)[3].xyz; //Correct
	vec3 r = pixel_pos_world - cam_pos;
	vec3 total_velocity = linear_velocity + cross(angular_velocity, r);
	
	//Offset the world pos by the total velocity, then project back to ndc coordinates
	vec3 pixel_prevpos_world = pixel_pos_world - total_velocity;
	vec3 pixel_prevpos_cam =  ((INV_VIEW_MATRIX) * vec4(pixel_prevpos_world, 1.0)).xyz;
	vec4 pixel_prevpos_clip =  PROJECTION_MATRIX * vec4(pixel_prevpos_cam, 1.0);
	vec3 pixel_prevpos_ndc = pixel_prevpos_clip.xyz / pixel_prevpos_clip.w;
	
	//Calculate how much the pixel moved in ndc space
	vec2 pixel_diff_ndc = pixel_prevpos_ndc.xy - pixel_pos_ndc.xy; 
	
	vec3 col = vec3(0.0);
	float counter = 0.0;
	if(length(r) >= startRadius){
		for (int i = 0; i < iteration_count; i++)
		{
			vec2 offset = pixel_diff_ndc * (float(i) / float(iteration_count) - 0.5) * intensity; 
			col += textureLod(SCREEN_TEXTURE, SCREEN_UV + offset,0.0).rgb;
			counter++;
		}
		ALBEDO = col / counter;
	}
	else
		ALBEDO = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0).rgb;
    }

### Minimal reproduction project (MRP)

Nothing

**Comment by Calinou** [comment]
You likely need to add the `repeat_disable` hint on the screen texture, the depth texture, or both.

**Comment by KingGD24** [comment]
Ok and thanks for helping me.
