### ISSUE TITLE
Godot Changing AnimationPlayer Snap Settings in FPS Mode

### ISSUE THREAD

**Issue by SirJordzy** [godotengine/godot#92273]
### Tested versions

Godot 4.2.2 Stable
tested in Godot 3.5.3 Stable and it works correctly

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 SUPER (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When i set my animations to snap to 60fps in the animationplayer, and i close the program, reopen it, it changes the 60fps to 59.9999. for all my animations

### Steps to reproduce

1. create new project
2. create a node
3. add animationplayer to it and create an animation.
4. change snap to 60fps
5. save node as scene
6. close program
7. reopen program to find it changed

### Minimal reproduction project (MRP)

[TestProject.zip](https://github.com/godotengine/godot/files/15410281/TestProject.zip)

**Comment by JekSun97** [comment]
I cannot produce this problem, I repeated the steps described, and when opening the value 60 was preserved
![11](https://github.com/godotengine/godot/assets/130399274/8b25ce09-3229-4ec1-b7b1-716f0eea808f)

**Comment by SirJordzy** [comment]
https://github.com/godotengine/godot/assets/93054887/e93233ab-81cf-4f9b-afbc-5be07018d1db

heres a video of me reproducing it
