### ISSUE TITLE
Control.get_pos returns wrong value when automatically moved by parent Container

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#9227]
**Operating system or device - Godot version:**
Windows 7,  Godot Engine v2.1.3.stable.official

**Issue description:**
get_pos() from Control return false value when inside a Container and automatic moved

I expect get_pos() should always return the position of the node (like in node2d). 

In demo project it should be always Vector2(0,0) and a white rectangle should be draw on the same position of the colorFrame.

![image](https://user-images.githubusercontent.com/10463138/27246041-4e6853ac-52ef-11e7-83d3-b4426cdc7862.png)

**Link to minimal example project:**
[getPosBug.zip.txt](https://github.com/godotengine/godot/files/1082036/getPosBug.zip.txt)

**Comment by kubecz3k** [comment]
I downloaded and tested the provided sample but I cant see any bug with wrongly reported positions here:
![control_container_pos_issue](https://user-images.githubusercontent.com/6129594/27252739-29fd44f6-5366-11e7-8bcc-b8717947853b.gif)

@puppetmaster- what values are you expecting?

**Comment by puppetmaster-** [comment]
@kubecz3k thx for analysing
I have expected the same behavior as in the node2d. So always return internal position.
In the doc it says
> Returns the Control position, relative to the top-left corner of the parent Control and independent of the anchor mode.

But the top-left corner from parent (HBoxContainer2) isn't moving. :confused: 


I will close the ticket, because it works as designed but for me it's still confusing. 

If you are curious. The idea behind, is having a area2D which automatically resize.
![image](https://user-images.githubusercontent.com/10463138/27255527-be1fcd96-539f-11e7-946c-8f7c2590c4e9.png)
and this is the code when colorFrame send resized event
```
func _on_ColorFrame_resized():
	#create new polygon array
	vec2Array = Vector2Array()
	vec2Array.append(Vector2(0,0))
	vec2Array.append(Vector2(0,get_size().y))
	vec2Array.append(get_size())
	vec2Array.append(Vector2(get_size().x,0))

	get_node("Area2D").clear_shapes()
	var _shape = ConvexPolygonShape2D.new()
	_shape.set_points(vec2Array)
	get_node("Area2D").add_shape(_shape,transform)
	#only for debuging
	get_node("Area2D/CollisionPolygon2D").set_polygon(vec2Array)
```
