### ISSUE TITLE
TouchScreen Button Still Under Node2D on 4.2.2 stable.mono

### ISSUE THREAD

**Issue by hafizosina** [godotengine/godot#92286]
### Tested versions

- Reproduce in 4.2.2 stable mono

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4887) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

I know this issue has been raised before at

https://github.com/godotengine/godot/issues/10755
and it seems that this problem has been discussed and approved at
https://github.com/godotengine/godot-proposals/issues/1911

but currently, in Godot version 4.2.2 stable mono,
TouchScreenButton still inherits from Node2D

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/52592893/4d11ae58-a2d7-4bbd-8917-dbe488f24230)

### Minimal reproduction project (MRP)

![image](https://github.com/godotengine/godot/assets/52592893/23bc0e7a-1528-44cb-85c3-127a871e2a30)

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
