### ISSUE TITLE
Polygon2D Node missing inspector items/option to repeat Texture

### ISSUE THREAD

**Issue by Jack-Daly-Eng025** [godotengine/godot#92281]
### Tested versions

Version affected is 4.2.2, not aware of other version issues at this time. 

### System information

Godot v4.2.2.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RAVEN) () - AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Specifically missing the option in inspector to repeat the background.png texture I have selected for polygon 2D. I find there's a lot of difference between Windows Godot tutorials and Linux and everything does eventually work the same, but there's not a good list of those differences unless you're determined to trawl through the internet for them. The option does show up if you search for repeat in the search bar, but it is missing from inspector view.  So is the filter property. Both are searchable in the search bar. 
[Missing_Inspector_Items.zip](https://github.com/godotengine/godot/files/15416913/Missing_Inspector_Items.zip)
 

### Steps to reproduce

Like everything be on Linux, use Godot for Linux, download or via Steam doesn't matter, 4.2.2 is the version affected. 
Create a Area2D, create a Polygon2D and try and add a texture that repeats. Or just click on the node and check inspector view. 

### Minimal reproduction project (MRP)

[LearningGodot2D.zip](https://github.com/godotengine/godot/files/15416956/LearningGodot2D.zip)

Project I was working on as part of a course where I found the error is attached.

**Comment by AThousandShips** [comment]
This option is under `CanvasItem` further down, does that not work?

**Comment by AThousandShips** [comment]
Because they are with the node that create the properties, that's who the inspector is designed, to keep things easy to find

If it works this can be closed

**Comment by Jack-Daly-Eng025** [comment]
Okay no bother. The tutorial I was following may just be outdated I guess because both repeat and filter where in the main inspector view for Polygon2D , not below under Canvas Items. I'll close the issue.

**Comment by AThousandShips** [comment]
You're probably looking at a tutorial for 3.x instead

I'd suggest asking questions in the [forums](https://forum.godotengine.org/) first to make sure it's a bug in the future

**Comment by Jack-Daly-Eng025** [comment]
No bother, will do. :-)
