### ISSUE TITLE
Editor anti-aliasing broken on non-retina displays (4.3.dev6.mono)

### ISSUE THREAD

**Issue by wickworks** [godotengine/godot#92298]
### Tested versions

Looks fine in 4.2.2.mono
Rendering messed up in in 4.3.dev6.mono

### System information

Mac Sonoma 14.5 — 2.3 GHz 8-Core Intel Core i9 — AMD Radeon Pro 5500M 4 GB Intel UHD Graphics 630 1536 MB

### Issue description

I have an external monitor hooked up to my macbook. I've upgraded from 4.2.2 to 4.3.dev6 and the editor is now missing anti-aliasing for text and UI components.

`Apple Thunderbolt Display: 27-inch (2560 × 1440)`
This is what a new project looks like on my external display. Note the near-illegible text on the ruler in the scene preview, and the messed-up "Filter properties" text in the inspector:
![no_retina](https://github.com/godotengine/godot/assets/4574312/c48e208a-19e5-4753-aa2f-4075051f04b4)

`Built-in Retina Display: 16-inch (3072 × 1920)`
Dragging that same window to the built-in laptop screen display anti-aliases lines and text correctly:
<img width="1222" alt="retina" src="https://github.com/godotengine/godot/assets/4574312/d126060d-b986-4207-b84e-f6389b4df6d9">

I'm guessing that the difference between the two is the retina classification as I've seen that cause other differences in rendering in the past, but I don't have more non-retina monitors to confirm that.

### Steps to reproduce

Open an editor on a non-retina display. Anti-aliasing is missing.

### Minimal reproduction project (MRP)

Project-independent; it works with fresh projects made in 4.3.dev6

**Comment by akien-mga** [comment]
CC @bruvzg @Calinou
