### ISSUE TITLE
Allow higher values to be entered then a specified range

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#9229]
PROPERTY_HINT_RANGE allows you to set a range between which the value of a property should lie.

Currently that range is applied both to the precision of the slider and the manual entry of values in the property editor which in many cases is exactly what you want.

But there are fields where large values are possible but which results in the slider becoming too imprecise to be usable and you would like to support a lower range for the slider.

The suggestion is to add a new hint that tells the property editor the specified range only applies to the slider and that a lower or higher value can be entered manually. If a value has been entered outside of this range the slider should just show that it is maxed out.

**Comment by Gibbz** [comment]
yeah this would be great for things like the new rim lighting which needs to go higher than 1, but it doesnt allow you currently to go higher :+1:

**Comment by kubecz3k** [comment]
I assume we don't have any new improvements in the topic of this issue?

**Comment by akien-mga** [comment]
Related to #9431, and fixed the same way (https://github.com/godotengine/godot/issues/9431#issuecomment-389504097) with dfd13316 and the optional `or_lesser` and `or_greater` hints. This still needs to be added manually to the properties where it actually makes sense.
