### ISSUE TITLE
Wrong translation of CollisionShape3D warning in pt_BR

### ISSUE THREAD

**Issue by DanielNovaesDias** [godotengine/godot#92294]
### Tested versions

Tested in godot version: 4.3-dev6.

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.5585) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

When editor is in pt_BR language, the warning for CollisionShape3D when missing a parent derived from CollisionObject3D is wrong. appears as "CollisionShape2D" warning instead.

![image](https://github.com/godotengine/godot/assets/40413365/25c2cb59-10e6-4e95-9b0c-7f34dfa9e6e6)

### Steps to reproduce

- Open Editor
- Change Language to [ pt_BR ]
- Create new 3D root scene.
- insert CollisionShape3D node
- click in warning
- check that the first warning appears as CollisionShape2D

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Thanks for the report. Fixed in Weblate: https://hosted.weblate.org/translate/godot-engine/godot/pt_BR/?checksum=0f918484db359bef

Note that you can also do fixes directly there yourself when you spot such issues.

**Comment by DanielNovaesDias** [comment]
Noted, thank you.
