### ISSUE TITLE
Windows input: Right click drag does not rotate the camera

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#92305]
### Tested versions

-Reproducible in 4.3.beta bd2300d
-Not reproducible in 4.2.1
-Not reproducible in 4.3 2efbc6b

### System information

Godot v4.3.beta (bd2300d77) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

Right click drag does not seem to orbit the camera most of the time on windows.
This issue does not reproduce 100% of the time. Seems to happen under the same conditions in #92304 that Alt-Tab key gets stuck, but it is not necessary to use alt-tab to reproduce this issue.

Some times this issue will reproduce and alt-tab will not be sticky.

### Steps to reproduce

1. Hold right click.
2. Drag the mouse. The camera may rotate for one frame, then stop.
3. If it does not reproduce, open the editor again.
4. One way to improve reproducibility appears to be to open multiple editors at once so that Godot gives the "Please confirm ... newer on disk" popup on some of them. But it might also be random.

### Minimal reproduction project (MRP)

Reproduces on an empty new project

**Comment by roa-nyx** [comment]
Can confirm I didn't have this issue in `4.3.dev6`, and now it's happening in `4.3.beta`

Focusing a different window and then right clicking directly into the editor while keeping the mouse moving results in rotating for a frame again, but then it's stuck again.

**Comment by roa-nyx** [comment]
Thank you @Hilderin this fixes it for me :)

**Comment by matheusmdx** [comment]
This was already solved in latest master [96a386f](https://github.com/godotengine/godot/commit/96a386f3c424af96d950ee5098b4b0e4907c9508) by https://github.com/godotengine/godot/pull/92415 (see https://github.com/godotengine/godot/issues/92759#issuecomment-2148797918)

**Comment by roa-nyx** [comment]
@matheusmdx I managed to trigger this issue again in Godot 4.3-beta2, but I have no idea how.

I basically left Godot 4.3-beta2 on in the background, while I had a long zoom call. When I came back, I set a sky material on an environment node, but when I tried to rotate around, I had the same issue..

**Comment by matheusmdx** [comment]
> @matheusmdx I managed to trigger this issue again in Godot 4.3-beta2, but I have no idea how.
> 
> I basically left Godot 4.3-beta2 on in the background, while I had a long zoom call. When I came back, I set a sky material on an environment node, but when I tried to rotate around, I had the same issue..
> 
> [Edit]: Restarting the editor fixed the issue. Again not sure how I triggered it though..

If you find this issue again, please open a new issue so we'll try to find out what is happening

**Comment by roa-nyx** [comment]
Thanks @matheusmdx, I'll open a new task once I figure out how to reproduce.
