### ISSUE TITLE
Windows input: Godot 3D scene has extremely laggy input

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#92307]
### Tested versions

- Reproducible in 4.3.beta bd2300d
- Reproducible in 4.3.beta f2f67279
- Not reproducible in 4.2.1
- Not reproducible in 4.3 2efbc6b

Probable bisect by @SaracenOne :
[12fda2fc13426799bd4376c1fbd99b179c685559] Windows: Fix WINDOW_EVENT_FOCUS_IN not delivered in some cases
Not 100% sure since this bug reproduces randomly

### System information

Godot v4.3.beta (bd2300d77) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When using things such as right click drag, WASD, scroll zoom or moving around the scene in general, the mouse and keyboard input becomes frequently lagged out, sometimes causing the camera to move in one direction continuously for 5-10 seconds

https://github.com/godotengine/godot/assets/39946030/4263f393-0687-4fa9-a533-f05ed772285a

### Steps to reproduce

1. Open an empty project
2. Hold right click
3. Use WASD
4. Drag the mouse and/or use scroll wheel while doing the above.
5. Try scrolling the mouse wheel separately.
6. If it doesn't reproduce, try another editor. See #92304 and #92306 for reproduction steps that help trigger this issue

### Minimal reproduction project (MRP)

Reproduces on an empty new project

**Comment by SaracenOne** [comment]
I can't be 100%, but I've been doing some bisecting and while it is quite difficult to reproduce, I'm beginning this PR 12fda2fc13426799bd4376c1fbd99b179c685559 might have led to the regression.

**Comment by matheusmdx** [comment]
This issue will be solved by #92742 (see https://github.com/godotengine/godot/issues/92759#issuecomment-2148797918)
