### ISSUE TITLE
Windows input: Editor livelock when alt-tab while right mouse is pressed.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#92306]
### Tested versions

- Reproducible in 4.2.1
- Reproducible in 4.3.beta bd2300d77

### System information

Godot v4.3.beta (bd2300d77) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When the editor is defocused while the mouse is captured due to right click drag in 3D, if the editor pops up an alert, the user will be unable to acknowledge the alert due to mouse being captured by the underneath editor window, but unable to focus the editor window due to the alert.

I show how to escape this in the video but it is extremely difficult and most users will probably be forced to kill godot.

https://github.com/godotengine/godot/assets/39946030/a1a178c2-ad64-4535-885f-c875d65aade5

Unlike other issues I filed today, this is not a new bug, but it is made far more common due to issues such as #92304

### Steps to reproduce

1. Open two copies of the editor in the same project so that Godot pops up a Please Confirm...newer on disk popup. Click Cncel.
2. Hold right mouse button
3. Alt+Tab
4. re-focus the godot editor.
5. The mouse will be captured but there will be a Please Confirm popup on top, but the mouse cannot move.
6. To escape, use another window to position the mouse on top of the cancel button of the blocking dialog, then click left button. Sometimes this is not enough: it might be necessary to press enter while the mouse is held.

### Minimal reproduction project (MRP)

Reproduces in empty project.

**Comment by SaracenOne** [comment]
@bruvzg As posted on the other similar issue, you might want to look at 12fda2fc13426799bd4376c1fbd99b179c685559. While I can't be 100% certain this is it, after a fair amount of bisecting, I'm beginning to reckon this might have caused a regression.

**Comment by matheusmdx** [comment]
I tested this issue in 4.0.4.stable (works normal), v4.1.beta1.official [828ec2c5d] (broken) and latest master v4.3.beta.custom_build [be56cab58] (broken) and bisecting points to #69318 as the culprit:

![Captura 2024-05-27 08-06-18-486864](https://github.com/godotengine/godot/assets/44306054/7e4411c6-ad1c-4813-97fc-bfc98e12cdc7)

Also when the bug happens, you can press alt+f4 that will close the popup, after that press the right mouse button and the mouse will appear again

**Comment by matheusmdx** [comment]
Tested latest master ([96a386f](https://github.com/godotengine/godot/commit/96a386f3c424af96d950ee5098b4b0e4907c9508)) and #92424 already fixed this issue

![image](https://github.com/godotengine/godot/assets/44306054/72e19cc7-abc6-4a71-a7ea-a6faf4ebdb22)
