### ISSUE TITLE
Changing the capitalization of  a folder name causes Godot to crash

### ISSUE THREAD

**Issue by phildoesdev** [godotengine/godot#92318]
### Tested versions

v4.3.dev6.mono.official - The bug is present in this version
Godot v4.2.1.stable - I cannot produce the bug in this version

### System information

Godot v4.3.dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i9-14900K (32 Threads)

### Issue description

Changing the capitalization of a folder name causes Godot to crash. For example, changing a folder from the name 'addon' to 'Addon' causes Godot to crash. Could be related to this: https://github.com/godotengine/godot/issues/89430, I'm not sure.

### Steps to reproduce

1. Create a folder called 'addon'
2. Press F2, rename this folder to 'Addon', changing the first letter from a lower case 'a' to a capital 'A'

### Minimal reproduction project (MRP)

[Filename_Crash_MRP.zip](https://github.com/godotengine/godot/files/15436507/Filename_Crash_MRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/91511

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
