### ISSUE TITLE
Editor: Window node: position preview ignores screen-relative initial position, still uses Absolute position even though hidden - resets to wrong position after hide & show

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#92314]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When editing a Window (or subclass like AcceptDialog), editor should auto-preview position in game by checking the Initial Position.

It works in Absolute mode, where the window can be moved around:

![image](https://github.com/godotengine/godot/assets/1067772/67af25bd-d9f3-49e5-9472-28cf286500cd)

When switching to another mode, relative to a screen, such as Center of Primary Screen, the position is not updated:

![image](https://github.com/godotengine/godot/assets/1067772/d61dc1c6-725b-4e32-8677-ded9f38b5aef)

It's not set to center of expected screen using the current application settings (display/window/size/viewport_width & viewport_height), nor reset to 0, it just keeps using the Absolute Position although the field is hidden, which looks weird.

Of course we cannot predict all sorts of screens, but at least previewing position at the center of the current expected viewport would be a good improvement.

Or, we could let the user freely modify some debug position, that would be shown instead of Absolute Position. In this case I'd suggest also unlocking the Move tool to let the user move the window visually with the mouse, and it would affect that debug position instead of the usual position 2D (only available for Node2D and Control, not Viewport subclass nodes like Window).

### Steps to reproduce

1. Create a Window
2. Modify Initial Position in Absolute mode
3. Switch to another mode like Center of Primary Screen
4. See how position remains unchanged

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Does it occur in 4.2.2?

**Comment by hsandt** [comment]
> Does it occur in 4.2.2?

Yes. Also, I tested again further and found out that the preview position *does change* if you close and reopen the scene, or more simply hide and show the Window node again. However, the position is not expected, and is placed at the center of some fictive screen of dimensions around 1922x1246, so it's very far in the bottom-right for a low-res game.

![image](https://github.com/godotengine/godot/assets/1067772/584d27b3-d3c9-4596-b48d-2b88f2bd2c7f)

It is possible to switch back to Absolute mode just to see the new position:

![image](https://github.com/godotengine/godot/assets/1067772/2fca0b37-1e05-4bf7-8f6d-9ab901071eb0)

This prevented me for keeping a position of (0, 0) to be able to preview at all times.
