### ISSUE TITLE
No option to *not* save the scene when played

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9232]
**Operating system or device - Godot version:**
Godot `master`, but also applies to 2.1.

**Issue description:**
There isn't a "No" option in the alert that asks you whether to save the scene you try to run it before saving.

![godot windows opt tools 64 3 0_2017-06-16_21-49-53](https://user-images.githubusercontent.com/5599796/27248831-73699090-52df-11e7-8883-1fc428bf68d4.png)

Of course, you can just close the alert, but it smells like bad usability for me.

**Comment by reduz** [comment]
It's a very persuasive dialog, you have to admit. It makes look like your
decision..

**Comment by aswinmohanme** [comment]
I would like to work on this.

**Comment by aswinmohanme** [comment]
And apparently, I was late.

**Comment by karroffel** [comment]
Yup :)
