### ISSUE TITLE
Crash on Android - vulcan - stack trace

### ISSUE THREAD

**Issue by 777Pixels** [godotengine/godot#92327]
### Tested versions

- From Godot 4.1 android export

- Report on phone model :

 [samsung a05s (Galaxy A05s)]   [ vivo V2342 (Y100) ] [ Redmi tapas (Redmi Note 12) ]  [ TECNO TECNO-KG5k (TECNO SPARK 8C) ]

- On Android Version 

[Android 14 (SDK 34)]  [Android 13 (SDK 33)]  [Android 11 (SDK 30)]

### System information

Godot 4.1 (stable)

### Issue description

Multiple crashes , impacting about 10% of users on Google Play.

I only have the crash report from Google Play Console.
Never had this issue locally. 

I can't bring any other information. Sorry.

### Steps to reproduce

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 19534 >>> ca.pixels777.bacb <<<

backtrace:
  Unknown
  #01  pc 0x00000000026d6054  /data/app/~~2wEnTMcbG5v47NHBf-yvXg==/ca.pixels777.bacb-nf_zFBDiNzs7m9gYx13oOA==/split_config.arm64_v8a.apk!libgodot_android.so
  #02  pc 0x0000000000b7c944  /data/app/~~2wEnTMcbG5v47NHBf-yvXg==/ca.pixels777.bacb-nf_zFBDiNzs7m9gYx13oOA==/split_config.arm64_v8a.apk!libgodot_android.so
  #03  pc 0x0000000000b55480  /data/app/~~2wEnTMcbG5v47NHBf-yvXg==/ca.pixels777.bacb-nf_zFBDiNzs7m9gYx13oOA==/split_config.arm64_v8a.apk!libgodot_android.so (Java_org_godotengine_godot_GodotLib_step+252)
  #04  pc 0x000000000001ea3c  /data/app/~~2wEnTMcbG5v47NHBf-yvXg==/ca.pixels777.bacb-nf_zFBDiNzs7m9gYx13oOA==/oat/arm64/base.odex (art_jni_trampoline+108)
  #05  pc 0x000000000004f674  /data/app/~~2wEnTMcbG5v47NHBf-yvXg==/ca.pixels777.bacb-nf_zFBDiNzs7m9gYx13oOA==/oat/arm64/base.odex (org.godotengine.godot.vulkan.VkThread.run+900)
  #06  pc 0x000000000033b3a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #07  pc 0x000000000023a5d0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #08  pc 0x0000000000539b2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600)
  #09  pc 0x00000000005394dc  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8)
  #10  pc 0x00000000000fd004  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #11  pc 0x0000000000096928  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)

### Minimal reproduction project (MRP)

sorry, no hints on how to reproduce.

**Comment by Calinou** [comment]
Devices that only have Vulkan 1.0 support in their drivers generally have broken Vulkan support. I recommend using the Compatibility rendering method instead.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
