### ISSUE TITLE
FileSystem dock won't show any file / folders, and has performance issues when loading large folders

### ISSUE THREAD

**Issue by FaerDerr** [godotengine/godot#92335]
### Tested versions

Tested in 4.2.2 stable, 4.3 beta 5, 4.3 beta 6.

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5186) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I tried loading this sprite database : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
It's around ~1Go of .png (1025 pokemons + shinies, all in pixel art), saved in 1025 folders.

Here's the exhaustive list of what I encountered while trying to import that across three versions:
- It took any version tested 10+ minutes to import everything
- IF the import is successful, I need to Alt+F4 / task manager to exit godot
- While open, the editor seems to run fine. I can create empty new scenes, save, load and play them.
- I don't see any file nor folder in the FileSystem Dock, but I see them using the load window.

![image](https://github.com/godotengine/godot/assets/20193149/943e7c2d-3055-47f6-aa4c-3663b53569fa)
![image](https://github.com/godotengine/godot/assets/20193149/01ededa3-c108-4b89-87b2-78bab0875f5f)

- Reloading the whole project fixes this last issue, but takes 10+ minutes of reimport and I need to do that every time I open godot.
- Alternatively, creating a folder will trigger a scan (taking again ~10min) and it will fix the problem, until you need to close / reopen the engine

![image](https://github.com/godotengine/godot/assets/20193149/c5e55ab8-2fa0-4076-97c1-258ea6ef5e79)

- When the issue is fixed after reimporting, the filesystem dock will lag & jitter, making it hard to use
---

**Expected behaviour :** 
- Load the big folder (takes some time to import, but should be less than 10 minutes)
- After import, all the files can be seen in the filesystem dock without decreased performance
- We can close the engine whithout relying on task manager

### Steps to reproduce

- Create an empty project
- Try to import the sprite folder from provided link : https://github.com/PMDCollab/SpriteCollab/tree/master/sprite
- If successful, either godot will crash, or you won't be able to see the folder architecture after import
- If that's not the case, close godot and reopen it : all the folders should be gone from the filesystem dock

### Minimal reproduction project (MRP)

I can't upload the project here, as it weight too much.
It's an empty project with just the mentioned file above, no scripts, no editor settings, no scenes.

**Comment by FaerDerr** [comment]
Maybe related issues : https://github.com/godotengine/godot/issues/38668

**Comment by Calinou** [comment]
> - When the issue is fixed after reimporting, the filesystem dock will lag & jitter, making it hard to use

This is because the entire list of files is displayed at once in the FileSystem dock. Without manual pagination or [controls suited for displaying large lists](https://github.com/godotengine/godot-proposals/issues/9678), this can't be fixed.

**Comment by Jordyfel** [comment]
Probably the same as https://github.com/godotengine/godot/issues/47053

**Comment by FaerDerr** [comment]
> Probably the same as #47053 (at least the part about filesystem not showing up for a long time)

I saw this one but the topic and bug seems to be targeted at godot 3.x versions, I didn't saw any issue report for 4.x versions !

I think calinou has the right call here : I'm pretty sure most of these issues could be fixed if [#9678](https://github.com/godotengine/godot-proposals/issues/9678) is implemented. 

Not for the import part, but a faster FileSystem might be the way.
Having an option to not show the content of certain folders while still importing their contents might be an "easy" temporary fix
