### ISSUE TITLE
Godot doesn't respond after running (Win64 Debug 5/19/17)

### ISSUE THREAD

**Issue by P-Star7** [godotengine/godot#9233]
**Operating system or device - Godot version:**
Windows 10 64-bit
x86
Intel HD Graphics 520 + Nvidia GeForce 940M
The debug Win64 version of Godot from http://fixnum.org/godot/#latest_complete as of this writing

**Issue description:**
What happened: 
![image](https://user-images.githubusercontent.com/26371167/27249362-5c248972-52d9-11e7-9c7b-970a62244465.png)
What I expected: Godot to run normally
After my previous issue, a kind user pointed me to the debug builds, but the debug build locks up upon startup, but this issue has different text.
Also, running with either graphics card or running as administrator makes no difference to the error.

**Steps to reproduce:**
N/A

**Comment by akien-mga** [comment]
Is there really no more information than that in the terminal? The screenshot shows only normal output, no error message.

**Comment by vnen** [comment]
Also: is there any text selected in the terminal? Selection mode stops the buffer output which causes Godot to freeze.

**Comment by P-Star7** [comment]
Nope, no more. The main Godot window with the Godot title and icon is also open, but all that is displayed is white within the window's bounds. If you click on it several times, the mouse changes to the round waiting icon, the whole window (not just inside) is tinted white and Windows didplays the usual kind of "this application is not responding, close the application or wait" dialog.

**Comment by marcelofg55** [comment]
I think I'm getting this bug also with an Intel HD Graphics card, godot tries to start the project and then stops responding, the Intel Graphics Utility icon reports that the driver crashes and recovers up but godot never starts. I've tried updating the driver to the latest version with the same results.

![godot_driver_crash](https://user-images.githubusercontent.com/10578225/27843809-d6e44fe4-60ee-11e7-8afc-c5426f7821bb.png)

**Comment by P-Star7** [comment]
This bug still happens if all antivirus functions of Webroot are disabled.

**Comment by vnen** [comment]
Can you test with a more recent build? You can download one from https://bintray.com/calinou/godot/editor

**Comment by mhilbrunner** [comment]
This should be closed as there was no more feedback. Can be reopened when someone can confirm that this still happens with versions more recent than 5 months ago. :)
