### ISSUE TITLE
Error: Not all code paths return a value.

### ISSUE THREAD

**Issue by uxerror** [godotengine/godot#92341]
### Tested versions

Godot-4.2.2

### System information

Windows 11

### Issue description

I do not understand why the error occurs, because I have not found any possibilities in which the value is not returned.

### Steps to reproduce

The code causes an error: Not all code paths return a value.

```gdscript
var deck: Deck
var general_power: int:
	get: _get_power_score

func _get_power_score() -> int:
	var cards_power: int = 0
	for card in deck.field_cards:
		cards_power+= card.power
	return cards_power
```

If you fix the code like this, the error disappears.

```gdscript
var deck: Deck
var general_power:
	get: _get_power_score

func _get_power_score() -> int:
	var cards_power: int = 0
	for card in deck.field_cards:
		cards_power+= card.power
	return cards_power
```

### Minimal reproduction project (MRP)

[Gwent.zip](https://github.com/godotengine/godot/files/15440329/Gwent.zip)

**Comment by uxerror** [comment]
I found a way not to cause an error while maintaining static typing. The error disappears if you change the code in this way. But I still don't understand why it occurs in the first case.

```gdscript
var deck: Deck
var general_power: int :
	get = _get_power_score

func _get_power_score() -> int:
	var cards_power: int = 0
	for card in deck.field_cards:
		cards_power+= card.power
	return cards_power

```

**Comment by timothyqiu** [comment]
Your original code snippet is equivalent to:

```gdscript
var general_power: int:
    get = _getter

func _getter() -> int:
    _get_power_score

func _get_power_score() -> int:
	var cards_power: int = 0
	for card in deck.field_cards:
		cards_power+= card.power
	return cards_power
```

`_getter()` does not return anything.

**Comment by KoBeWi** [comment]
It should be
```GDScript
var general_power: int:
	get = _get_power_score
```

**Comment by uxerror** [comment]
Thank you all. I realized the mistake.
