### ISSUE TITLE
Potential bug getting tangents and bone weights from meshes 

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9236]
Related to PR #9230. I found a lot of the decompression code trying to decompress by taking the value and applying the equation: x * 2 - 1
I had to take this out for vertex colours and normals to mirror how they were being compressed and I think tangents and bone weights will likely also have this problem.
I have no data that uses these so cannot test if this is the case or not.

**Comment by reduz** [comment]
i merged this fix, so it should be working fine now, closing
