### ISSUE TITLE
Godot fails to import blend files from Blender 4.2

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#92365]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

It's a simple scene with a cube and nothing else in it

<img width="800" alt="Screenshot 2024-05-25 at 22 24 22" src="https://github.com/godotengine/godot/assets/60579014/92049bc8-acdb-4f1f-bc40-51c3ec4a69aa">
<img width="800" alt="Screenshot 2024-05-25 at 22 24 29" src="https://github.com/godotengine/godot/assets/60579014/84707bc6-e70e-41ec-bc4f-d1ad2539a0e8">

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[MRP_blend_fail.zip](https://github.com/godotengine/godot/files/15444571/MRP_blend_fail.zip)

**Comment by akien-mga** [comment]
CC @godotengine/import

**Comment by fire** [comment]
Testing with the "blender" daily build channel on steam.

Will report back.

**Comment by fire** [comment]
The api for Blender broken compatibility by removing vertex colours in 4.2.

There's been significant debate over the merits of the vertex color change in the gltf blender io github issue.

**Comment by fire** [comment]
```patch
--- a/20-29 Tools/21 Godot 21/21.01 Godot/modules/gltf/editor/editor_scene_importer_blend.cpp
+++ b/20-29 Tools/21 Godot 21/21.01 Godot/modules/gltf/editor/editor_scene_importer_blend.cpp
@@ -188,11 +188,11 @@ Node *EditorSceneFormatImporterBlend::import_scene(const String &p_path, uint32_
        } else {
                parameters_map["export_lights"] = false;
        }
-       if (p_options.has(SNAME("blender/meshes/colors")) && p_options[SNAME("blender/meshes/colors")]) {
-               parameters_map["export_colors"] = true;
-       } else {
-               parameters_map["export_colors"] = false;
-       }
+       // if (p_options.has(SNAME("blender/meshes/colors")) && p_options[SNAME("blender/meshes/colors")]) {
+       //      parameters_map["export_colors"] = true;
+       // } else {
+       //      parameters_map["export_colors"] = false;
+       // }
        if (p_options.has(SNAME("blender/nodes/visible"))) {
                int32_t visible = p_options["blender/nodes/visible"];
                if (visible == BLEND_VISIBLE_VISIBLE_ONLY) {
```

**Comment by lorddevereux** [comment]
I think this PR https://github.com/godotengine/godot/issues/83320 is also relevant to this discussion, with some debate over how to manage specular colours from gltf.

**Comment by tumblewed** [comment]
This still occurs on 4.3rc2.
