### ISSUE TITLE
Looking multiple nodes in remote list causes crash 

### ISSUE THREAD

**Issue by ipatavatsizz** [godotengine/godot#92369]
### Tested versions

- Tested in: v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 27.20.11022.14001) - AMD Ryzen 5 4600H with Radeon Graphics (12 Threads)

### Issue description

Creating lots of nodes, in my case procedural world generation with each pixel is a Sprite2D, 64x64 scaled nodes.

Generating world (200, 200)
Total created blocks 36615

When I press 'Remote' to inspect nodes, the app freezes. I assume a crash.

### Steps to reproduce

Start the game in MRP
The game will create lots of nodes
Click the 'Remote' panel

### Minimal reproduction project (MRP)

MRP file [DemoProjects.zip](https://github.com/godotengine/godot/files/15445038/DemoProjects.zip)

**Comment by matheusmdx** [comment]
I downloaded your MRP but i can't start the game becaues some errors throw up when i open the project, you create WorldGenerato global class in two scrripts, call a function not declared anywhere, try to use a variable not declared anywhere, are you sure that is the correct MRP?

![image](https://github.com/godotengine/godot/assets/44306054/28d3caf2-8dc5-45d6-b432-48f9e5c78d66)

**Comment by ipatavatsizz** [comment]
Caching problem I assume, can you remove `worldgenerator.gd` script. In my FileSystem is way already removed.
A lot of code has changed since I posted this issue. So I cannot provide extra details but it should work when you delete.

**Comment by matheusmdx** [comment]
I did the test with the 4.2.2,stable and latest master v4.3.beta.custom_build [be56cab58], in my case the editor didn't crash but freeze for a time (become white and unsresponsive) and after a time unfreeze for 2 seconds and freeze again and keep this loop

**Comment by Zireael07** [comment]
I have what seems to be a very similar issue on 4.2. I get crashes with no output if I run my project from the editor but none if I run from project manager

**Comment by ipatavatsizz** [comment]
Here is what I get, remote panel cannot handle listing 40k nodes.

https://github.com/godotengine/godot/assets/37545799/76fbddbb-6e30-4f99-a312-7d6bdee9e2e2

**Comment by ipatavatsizz** [comment]
It may relate to my computer's capacity, so I close the issue. Thanks for helping.
