### ISSUE TITLE
A way to re-initialise the renderer to apply changed settings without restart

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9237]
A way to re-initialise the renderer to apply changed settings without restart.
Currently, to change the shadow quality one must restart the game. Other options are probably setup like this as well. 
It would be good to be able to reboot systems to apply changes without having to restart the game.

**Comment by fracteed** [comment]
I have also noticed this and was going to post an issue about it. The need to restart to update the directional shadow quality setting only seems to happen under Linux for me. Works fine in Win10, without having to do restart/reload.

**Comment by reduz** [comment]
You can do all this from the Viewport API, what you see in Project Settings are just the default values.
As this is already supported (just use get_viewport().set_shadow_blabla), closing this issue
