### ISSUE TITLE
Crash when trying to clear dictionary input

### ISSUE THREAD

**Issue by scrahe** [godotengine/godot#92375]
### Tested versions

Tested in 4.2.1.stable

### System information

Godot v4.2.1.stable - macOS 12.6.1 - Vulkan (Forward+) - integrated Intel Iris Pro Graphics - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When opening a dictionary input and putting the key as an object, then clearing the input, Godot crashes.

### Steps to reproduce

1. Open New Project
2. Create new node with following code:
   ```gdscript
   @export var test : Dictionary
   ``` 
3. Select object as the key
4. Go into the object context menu and clear the object
5. Crash

### Minimal reproduction project (MRP)

Look above at steps to reproduce

**Comment by AThousandShips** [comment]
Can you try with 4.2.2? To make sure this occurs on a supported version

**Comment by matheusmdx** [comment]
I tried to reproduce the crash but nothing happens

https://github.com/godotengine/godot/assets/44306054/d14077d7-b251-48ad-9dce-b36a60889ea5

**Comment by scrahe** [comment]
I just tried, but I haven't been able to reproduce the crash either.
