### ISSUE TITLE
windows key + d to goback to the desktop crashes the program

### ISSUE THREAD

**Issue by chen9916** [godotengine/godot#92378]
### Tested versions

godot 4.22

### System information

windows 10 godot 4.22

### Issue description

when ever i pushes windows key + d to go back to the desktop godot shuts down 

### Steps to reproduce

1,open godot 
2,create a new project
3,hit windows key + d 
4,godot shuts down

### Minimal reproduction project (MRP)

1,open godot 
2,create a new project
3,hit windows key + d 
4,godot shuts down

**Comment by AThousandShips** [comment]
Can't confirm on latest development version on Windows 10

**Comment by chen9916** [comment]
> Can't confirm on latest development version on Windows 10

cound't reproduce the result after i rebooted,only happens after a while and the computer gets laggier,maybe because of something else..
