### ISSUE TITLE
Autoload functions in @tool script not found on scene reload

### ISSUE THREAD

**Issue by lindsaypj** [godotengine/godot#92376]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 Laptop GPU (NVIDIA; 32.0.15.5585) - 13th Gen Intel(R) Core(TM) i9-13900HX (32 Threads)

### Issue description

When reloading the scene, functions that should be autoloaded are not recognized in `@tool.` script

Scope:
 - The linter does not indicate a problem, and the functions autocomplete when typed
 - When running the game, the functions do actually run

The issue occurs when using (Scene -> Reload Saved Scene)
```
Invalid call. Nonexistent function 'test' in base 'Node (autoload.gd)'.
```

I am new to Godot, so this may be expected in `@tool` scripts. If so, it seems difficult to extract generalized static functions to be reused elsewhere, while being able to run them in-editor.

### Steps to reproduce

1. Create new project
2. Add a node to scene
3. Save scene and give it a name
4. Add a script to the node
5. Above `extends Node`, add `@tool`
6. Create an additional script to be autoloaded
7. Add a function to test autoload
8. Add second script to Autoload (Project  -> Project Settings... -> Autoload)
       - I use the file select and keep the generated 'Node name'
9. In the First script that was added to the node, call the autoloaded function (```Autoload.test()```) inside the `func _ready()`
10. use (Scene -> Reload Saved Scene) to reload the scene which should call the function, but the following error occurs:
![error](https://github.com/godotengine/godot/assets/98486346/ce0fffce-adfc-4d04-92e4-2a51d0816557)

### Minimal reproduction project (MRP)

[autoload-bug.zip](https://github.com/godotengine/godot/files/15445682/autoload-bug.zip)

**Comment by AThousandShips** [comment]
> Add second script to Autoload

I assume this is also `@tool`?

**Comment by lindsaypj** [comment]
> I assume this is also `@tool`?
Actually, I had not considered that. That is very intuitive in hindsight.

I just tested in a few projects and it did not seem to work at first just saving and reloading the scene, but after reloading the project it did work!

I suppose this means this is not an issue, just user error.

Thank you for your help!
