### ISSUE TITLE
LSP method `show_native_symbol_in_editor` does not work

### ISSUE THREAD

**Issue by fthycl** [godotengine/godot#92385]
### Tested versions

- Reproducible in 4.3.dev[b7feeb], and 4.2[stable]

### System information

Godot v4.3.beta (b7feebefa) - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Mobile) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i7-1260P (16 Threads)

### Issue description

The LSP method `textDocument/show_native_symbol_in_editor` does not work. This is the corresponding function:

```cpp
void GDScriptTextDocument::show_native_symbol_in_editor(const String &p_symbol_id) {
	ScriptEditor::get_singleton()->call_deferred(SNAME("_help_class_goto"), p_symbol_id);
	DisplayServer::get_singleton()->window_move_to_foreground();
}
```

When I call this LSP method via my LSP client, it in fact moves the window to foreground, but never opens the help page. When I ran this through gdb, it never hit `_help_class_goto` function either.

I replaced the call to `_help_class_goto` with the public version of the same method, `goto_help`, and then it works fine. However, when I made `_help_class_goto` itself a public method, it still does not work.

### Steps to reproduce

I use this method through neovim's builtin LSP client using the following code:

```lua
vim.lsp.buf.show_native_symbol_in_editor = function()
	local params = { "class_name:MeshInstance3D" }
	request("textDocument/show_native_symbol_in_editor", params, vim.print)
end
vim.api.nvim_create_user_command(
	"GdShowNativeSymbolInEditor",
	vim.lsp.buf.show_native_symbol_in_editor,
	{ desc = "Godot Show Native Symbol in Editor" }
)

```

Then, after neovim connects to the godot LSP server, I run the command `GdShowNativeSymbolInEditor`.

I know this is not very helpful for people who are not using neovim, but I am not sure how to reproduce this elsewhere. (The official vscode plugin does not use this method.)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is due to an outdated method being used, will write a fix
