### ISSUE TITLE
global_script_class_cache doesn't update when using class xx extends Node2d:

### ISSUE THREAD

**Issue by HarperCT** [godotengine/godot#92381]
### Tested versions

- Found in Godot_v4.2.2-stable_win64.exe 
- Tested Godot_v4.0-stable_win64.exe

### System information

Windows 10 - Godot_v4.2.2-stable_win64.exe

### Issue description

Unsure if "bug" or maybe a potential new feature...
Trying to use classes (with below syntax) in Godot and have the ".godot/global_script_class_cache.cfg" update doesn't seem work. With support for this syntax it would be nice if we could get all the features.

``` class TestClass extends Node2D: ```

### Steps to reproduce

initialize godot environment.
Create scripts/ and test_script.gd
insert below:
class TestClass extends Node2D:
    pass

Check the .godot/global_script_class_cache.cfg and confirm no new updates.

To confirm does work without it:
change to:
extends Node2D
class_name TestClass
pass

Check the .godot/global_script_class_cache.cfg and confirm TestClass now exists.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
I think you're misunderstanding how the `class` and the `class_name` works, `class` is to create a inner class, a class inside a class and `class_name` is the keyword to create a global class, so your first example should be: `class_name TestClass extends Node2D` (without the ":"), after you save that global_script_class_cache.cfg will update

**Comment by HarperCT** [comment]
Thanks for the explanation @matheusmdx. I have seen the `register_inner_classes()` before so I guess that is the workaround if you want to use multiple classes in the same file?
My inheritance hierarchy for file was very python-y like:
```
File1
class1 extends Node2D
class2 extends Node2D

File2
class3 extends class1

File3
class4 extends class2
```
But having it like this the global_script_class_cache.cfg wouldn't update (as you mentioned it is thinking these are all inner classes).
Maybe this could turn into a feature to register all class types to update into global_script_class_cache.cfg ?

All that being said happy to close this as non-issue... Reading through some more of the docs looks like it was never designed to be like this.

**Comment by dalexeev** [comment]
I don't think this is a bug either. Only outer classes can be registered as global. Basically GDScript takes "one class one file" approach. Inner classes are mainly intended for "structures" and small helper classes.

> Unsure if "bug" or maybe a potential new feature...

> Maybe this could turn into a feature to register all class types to update into global_script_class_cache.cfg ?

If you want to propose a new feature, see [godot-proposals](https://github.com/godotengine/godot-proposals) instead. Thanks for the contribution nonetheless!
