### ISSUE TITLE
Empty mesh causes SurfaceTools::generate_tangents to fail an assertion which doesn't make sense.

### ISSUE THREAD

**Issue by pl7y** [godotengine/godot#92395]
### Tested versions

- Reproducible in 4.2 stable

### System information

OSX Sonoma 14.4.1 (23E224)

### Issue description

The following error is shown in console:
```
E 0:00:01:0467   test.gd:22 @ _ready(): Condition "!(format & Mesh::ARRAY_FORMAT_TEX_UV)" is true.
  <C++ Source>   scene/resources/surface_tool.cpp:1151 @ generate_tangents()
  <Stack Trace>  test.gd:22 @ _ready()
```

If empty meshes are allowed, assertion should not be triggered.
If empty meshes are not allowed, assertion should be checked only if there is some mesh set.

### Steps to reproduce

Create a node and add this code to the `_ready()` function:

```gdscript
func _ready():
  var st = SurfaceTool.new()
  st.begin(Mesh.PRIMITIVE_TRIANGLES)
  st.generate_normals()
  st.generate_tangents()
  var mesh = st.commit()  
```

### Minimal reproduction project (MRP)

See "steps to reproduce".

**Comment by AThousandShips** [comment]
This fails because you need to have UV to generate tangents as they are related to textures

**Comment by clayjohn** [comment]
I agree, the error should be expanded to include a clear message saying that UVs are required to generate tangents.

**Comment by Maski0** [comment]
(This is my First time Contributing) @clayjohn I would like take up this Issue.
Currently for The Error `ERR_FAIL_COND(!(format & Mesh::ARRAY_FORMAT_TEX_UV));`  Macro is being
I will be simply using `ERR_FAIL_COND_MSG` Macro with message saying  **_"UVs are required to generate tangents"_**
is the above approch good, or is there any better approch.  And also if we change the above do i have to change anything else(like documentation)

**Comment by clayjohn** [comment]
> (This is my First time Contributing) @clayjohn I would like take up this Issue. Currently for The Error `ERR_FAIL_COND(!(format & Mesh::ARRAY_FORMAT_TEX_UV));` Macro is being I will be simply using `ERR_FAIL_COND_MSG` Macro with message saying **_"UVs are required to generate tangents"_** is the above approch good, or is there any better approch. And also if we change the above do i have to change anything else(like documentation)

Your suggested approach is correct and you don't need to change anything else :)

**Comment by Maski0** [comment]
> Your suggested approach is correct and you don't need to change anything else :)

Ok thank you sir, also a rookie question I am guessing I will have to create a pr for the master itself or for 4.2 branch as the tested version mentioned above.

**Comment by clayjohn** [comment]
You only need to make a PR for the master branch. We can "cherrypick" the change to the 4.2 branch automatically.
