### ISSUE TITLE
Axis Red lines don't get removed and persist in every scene

### ISSUE THREAD

**Issue by Necrosis000** [godotengine/godot#92393]
### Tested versions

4.2.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.5222) - Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 Threads)

### Issue description

So I came across a bug where if you try to move the anchors it creates red lines that don't go away and persist in every scene. This can be very frustrating as I have not encountered a way to fix this. 
![image_2024-05-26_132726718](https://github.com/godotengine/godot/assets/57779109/6e3d3c7a-7be9-418a-a78d-f7bc095df127)
![image_2024-05-26_132741052](https://github.com/godotengine/godot/assets/57779109/6a815c31-8677-454e-ba5c-c96fde67e0c7)

### Steps to reproduce

- Move anchor to center of button, image, any kind of gui
- Red lines show up and don't disappear

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Tested with 4.0.3,stable, 4.2.2.stable and latest master v4.3.beta.custom_build [be56cab58] and i can confirm the problem, as workaround the red lines dissapear if you drag any node a bit (even if you drag a node in another scene)


https://github.com/godotengine/godot/assets/44306054/ddc23f00-69b9-4bb4-bb4d-48763bf92e00

**Comment by Necrosis000** [comment]
Is this gonna be fixed in a newer version?

**Comment by Necrosis000** [comment]
Is there a version with this fixed?

**Comment by Calinou** [comment]
@Necrosis000 Please don't bump issues without contributing significant new information. We can't give an ETA on when the issue will be resolved as we don't know what's causing it in the first place.

**Comment by akien-mga** [comment]
This still seems to be a valid issue based on @matheusmdx's testing, so it shouldn't be closed until it's solved.
