### ISSUE TITLE
Inconsistent behaviour of overridden Node methods 

### ISSUE THREAD

**Issue by mberdev** [godotengine/godot#92394]
### Tested versions

4.2.2 stable

### System information

Windows 10

### Issue description

See reproductions steps

### Steps to reproduce

create following class : 
```

extends Node
class_name MyClass

func _ready():
    print("Class is now ready as '" + self.get_class() + "'") # <-- displays "MyClass"
  
func get_class():
    return "MyClass"
```

then do this whever you want (I do it in the activation of a plugin): 

```
var c = MyClass.new()
get_tree().get_root().add_child(c)
```

and then : 

```
for child in get_tree().get_root().get_children():
     	print(child.get_class()) # <-- displays "Node"
	print(child.call("get_class")) # <-- displays "MyClass"
```

Calling .get_class() directly will call the method of the parent class instead of the overridden method.
Calling via .call will call the overridden method.

I understand that there's probably a very logical explanation to this. 
I'm guessing that get_children has  return type of Node[], therefore calling it will implicitly give type "Node" to variable "child". 
It results in forcing the call to "get_class" on "child _as a Node_" instead of making it happen on "child _as whatever actual type it currently has_"

But this is very awkward, especially when the cast gets ignored when calling .call("get_class")

### Tests

Out of curiosity I tried this : 

```
for child in get_tree().get_root().get_children():
       var x:MyClass = child as MyClass
       if x != null:
     	    print(x.get_class()) # <-- STILL DISPLAYS "Node" !
	    print(x.call("get_class")) # <-- displays "MyClass"
```

**Comment by AThousandShips** [comment]
You can't override this method, this isn't supported, the behaviour is unclear what it should do exactly, but you simply shouldn't override this method

**Comment by mberdev** [comment]
No, I did not disable any errors. I'm using Godot 4.2.2 out of the box with a minimal project that contains more or less only this.

Where and when is this error supposed to appear? When I save the script in the Godot editor? When it gets loaded and parsed? When it tries to execute get_class ? etc.

**Comment by AThousandShips** [comment]
I will test it myself, but this is supposed to be an error

**Comment by AThousandShips** [comment]
I can't confirm this, it prints a clear error for me:
> The method "get_class()" overrides a method from native class "Object". This won't be called by the engine and may not work as expected. (Warning treated as error.)

Can you please upload a minimum reproduction project to help testing this, it causes a clear bug in 4.3

**Comment by mberdev** [comment]
Where and when is this error supposed to appear? When I save the script in the Godot editor? When it gets loaded and parsed? When it tries to execute get_class ? etc.

**Comment by AThousandShips** [comment]
In the editor like any other error, a red cross at the bottom, and a red line on the `func get_class():` line

Please upload an MRP to help testing this, as this is a bug if it doesn't produce an error correctly

**Comment by mberdev** [comment]
[MRP.zip](https://github.com/godotengine/godot/files/15448853/MRP.zip)

Please note that I run Godot with Godot_v4.2.2-stable_win64_console.exe

**Comment by AThousandShips** [comment]
Ah, you didn't mention the script was in an add-on, that was pretty important information. The checks are not run in add-ons (unless enabled with a setting)

(Also in the future, please do not include the `.godot` folder in an MRP)

**Comment by AThousandShips** [comment]
I can't run your MRP as it does invalid things, calling `add_child` on `_enter_tree` when the parent node isn't ready (you should get an error for this as well)

It also doesn't run because the main scene `res://addons/myplugin/myplugin.tscn` doesn't exist

So this MRP isn't helpful I'm sorry

> I would encourage the Godot team to run the checks on addons too. As a "regular Joe", to me a script is a script.

This is done by design to prevent unhelpful errors in plugins, if you want errors you need to turn them on yourself, but if you download someone elses plugin it won't help if they don't work, you can't fix them

Though so far errors *have* occured for me, just that they're not the ones you're facing, because the MRP isn't working

**Comment by mberdev** [comment]
You were not supposed to "run that MRP", only open it and check why the error message does not appear on the forbidden method.

**Comment by AThousandShips** [comment]
> You were not supposed to "run that MRP", only open it and check why the error message does not appear on the forbidden method.

I didn't, but the main scene is checked anyway, and you should always make sure the MRP works correctly

**Comment by AThousandShips** [comment]
But the error shows up correctly when enabled, the question here is if *errors* should still occur, otherwise this is as expected and the specific behavior is clearly documented. So beyond the discussion if errors should be printed from add-ons this isn't a bug
