### ISSUE TITLE
Error on export on macOS

### ISSUE THREAD

**Issue by JEB67** [godotengine/godot#92399]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

macos Big Sur v. 11.7.10 - Godot v4.2.2.stable.official [15073afe3]

### Issue description

When compiling for macOS (whether with or without debug) in production, it neither detects nor warns about erroneous scene preloads. While the engine runs the project perfectly with a warning regarding this, when compiled, the scene containing the preload error does not instantiate. The only place to detect what this error is about is by running the DMG and viewing the resulting log.

### Steps to reproduce

var projectile_scene = preload("res://escenes/projectile.tscn")  #This is ok
var projectile_scene = preload("res://escenes/Projectile.tscn")  #This is error (not problem in engine play)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is a [documented](https://docs.godotengine.org/en/stable/tutorials/scripting/filesystem.html#drawbacks) operating system limitation

**Comment by lostminds** [comment]
@JEB67 Perhaps this could instead be turned into a [proposal](https://github.com/godotengine/godot-proposals/) to add a warning somewhere in resource loader if it successfully loads a file with a case-mismatched path? 

For example in your case 
`var projectile_scene = preload("res://escenes/Projectile.tscn")` 
could result in a warning like:
`Warning: loading path 'res://escenes/Projectile.tscn' case mismatch with file path 'res://escenes/projectile.tscn'. This will break on export to case-sensitive file systems.`

**Comment by Chaosus** [comment]
Closed since its resolved. Please open a proposal if the implementation of warning is needed.
