### ISSUE TITLE
Make generated .h files with some common extension

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#9240]
**Issue description:**
As evidenced by #9223, various autogenerated `.h` files are gitignored individually, which leads to some slight issues when switching between branches and the like.

I propose that we make up some more complex extension for them (like `.gen.h`), so that we can ignore them all at once, or even, put them in some special `generated/` folder.

**Comment by akien-mga** [comment]
I think using a `.gen.h` extension is a good idea.

**Comment by vnen** [comment]
👍
