### ISSUE TITLE
Editing light_specular is not available in the DirectionalLight3D inspector settings

### ISSUE THREAD

**Issue by mishkarch** [godotengine/godot#92400]
### Tested versions

4.2.2 stable

### System information

Windows (I think it's not matter)

### Issue description

Hello. According to the documentation, Light3D has a light_specular property. DirectionalLight3D inherits from it, however, when added to the scene, in the inspector properties it is not possible to edit light_specular. (At the same time, the official tutorial on fake global illumination directly advises creating a DirectionalLight3D and setting to zero its specular.)
OmniLight3D and SpotLight3D are fine in this regard.

### Steps to reproduce

Create a scene, add DirectionalLight3D.

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
Looks like it's not implemented:

![изображение](https://github.com/godotengine/godot/assets/3036176/cfc53af1-0941-4ddd-a91d-8e1076537c14)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/80737.
