### ISSUE TITLE
SRC_VERTEX is empty in vertex shader

### ISSUE THREAD

**Issue by gtsiam** [godotengine/godot#9241]
**Operating system or device - Godot version:**
KDE neon 5.10 64-bit (GPU: AMD Radeon R9 285/380) - Godot custom build from master on the 16th of June

**Issue description:**
To test this, I made this setup:
![screenshot_20170617_223548](https://user-images.githubusercontent.com/7459196/27255740-622e9838-53ad-11e7-87dd-ca01f511e9fd.png)
Obviously black is not the expected output.

**Steps to reproduce:**
 Just remake the setup shown above: A sphere with the shown shader applied to it.

[Link to minimal example project](https://github.com/godotengine/godot/files/1082725/GodotTest.tar.gz)

Note that you may encounter another bug: the shader material seems to not be applied upon reloading a project, even though it is set in the properties. Just reapply it for a short term fix (Though an actual fix would be nice :wink:) - Edit: This seems to be related to #9234

**Comment by reduz** [comment]
SRC_VERTEX is gone, use VERTEX instead.
