### ISSUE TITLE
GDScript: assigning to a static variable from a lambda fails silently unless accessing through `self`

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#92434]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

```gdscript
@tool
extends Node

var instance_var : bool
static var static_var : bool

func _enter_tree() -> void:
	instance_var = false
	static_var = false

	var fn = func():
		instance_var = true
		print(instance_var) # -> true

		static_var = true
		print(static_var) # -> false

		self.static_var = true
		print(static_var) # -> true

	fn.call()
```

This looks like a bug since it works for the instance variable with no `self` but the static one requires `self`

### Steps to reproduce

Save the above script to a file and Ctrl+Drag it into the scene tree

### Minimal reproduction project (MRP)

N/A

**Comment by theraot** [comment]
I can confirm this behavior happens on:

- v4.3.dev6.official [89850d553]
- v4.2.2.stable.official [15073afe3]
- v4.2.1.stable.official [b09f793f5]
- v4.2.stable.official [46dc27791]

However, it works correctly on:

- v4.1.2.stable.official [399c9dc39]
- v4.1.1.stable.official [bd6af8e0e]
- v4.1.stable.official [970459615]

**Comment by matheusmdx** [comment]
Bisecting points to #79880 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/e4fb7635-1cf1-494a-9209-95e0e9920ec9)

**Comment by dalexeev** [comment]
* Probably #92241 fixes this, I'll check soon.
