### ISSUE TITLE
Tool scripts don't work if they're using inner classes

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#92448]
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

A tool script code isn't executed when the project is opened if that script is using an inner class. Adding script to the scene results in an error `Cannot get class''`.

Opening it in script editor, making any change (even adding an empty line) and saving the script solves the problem. Until the next editor restart

https://github.com/godotengine/godot/assets/60579014/9183d467-edcb-49bc-932c-d3e986da1054

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[MRP_tool_inner_class.zip](https://github.com/godotengine/godot/files/15462044/MRP_tool_inner_class.zip)

**Comment by dalexeev** [comment]
It looks like the bug is not reproducible on the current master. Probably, it is fixed by #90601. Please test the master branch if you can or wait for 4.3 beta 1.

**Comment by passivestar** [comment]
Indeed this doesn't happen in master, closing
