### ISSUE TITLE
"Animation not found" error message when creating the first animation in the animation editor

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#92471]
### Tested versions

v4.3.dev6.official [89850d553], v4.3.beta.custom_build [be56cab58]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

https://github.com/godotengine/godot/assets/60579014/f08ce8eb-20ae-436d-855b-8bdbd08b6ab5

### Steps to reproduce

Create an AnimationPlayer and create a new animation in it

### Minimal reproduction project (MRP)

N/A

**Comment by patwork** [comment]
Exact lines in build `v4.3.beta.custom_build.be56cab58`:
```
ERROR: Index p_idx = -1 is out of bounds (items.size() = 0).
   at: get_item_text (scene/gui/popup_menu.cpp:1859)
ERROR: Animation not found: "".
   at: get_animation (scene/animation/animation_mixer.cpp:387)
```

**Comment by matheusmdx** [comment]
Bisecting points to #90894 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/bcc3d078-a171-4f1f-be1b-7b0d8b779b5f)
