### ISSUE TITLE
Vector3().snapped() goes wrong with negative numbers

### ISSUE THREAD

**Issue by karolgotowala** [godotengine/godot#9247]
Godot Engine 2.13.stable.official win8

Snapping Vector3 returns wrong values when snapping negative values

Little showcase of problem:
[https://www.youtube.com/watch?v=q5LYH9HRsSw&feature=youtu.be](https://www.youtube.com/watch?v=q5LYH9HRsSw&feature=youtu.be)

**Comment by eon-s** [comment]
Quick example:
`Vector3( 1, 1.5, 2.1).snapped(0.5) = (1, 1.5, 2)`

`Vector3(-1,-1.5,-2.1).snapped(0.5) = (-0.5, -1, -1.5)`

This was solved by #6399 but seems that returned for some reason on 2.1.2

**Comment by eon-s** [comment]
By the way, `Vector2.snapped` uses a Vector2 as parameter and `Vector3.snapped` uses a float, that may need to be fixed (to work as Vector2) at least for Godot 3.

**Comment by eon-s** [comment]
@akien-mga the fix (using stepify) is already on master https://github.com/godotengine/godot/blob/master/core/math/vector3.cpp#L64 
It needs to be added on 2.1 too (maybe got lost during renderer migration).

The problem on master is another, the syntax inconsistency of Vector2 and Vector3 (I can open another issue for that).

**Comment by akien-mga** [comment]
Indeed, the fix was 23ababd and as I pointed out there, a bad git practice made it difficult to cherry-pick so I overlooked it for 2.1.1 and later. I'll have a look at it again, in the meantime yes another issue for the syntax inconsistency would be good :)

**Comment by akien-mga** [comment]
Fixed with 026c580.
