### ISSUE TITLE
Compatibility Positional Shadow Allocation is Broken

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#92486]
### Tested versions

4.3 dev 6

### System information

Windows 11, i3-10105f, RX6600 24.5.1, Compatibility

### Issue description

Positional Shadows occasionally Break and take wrong Shadow map
Seems to happen with a lot of mixed omni-spot lights changing across the screen, however unable to narrow it down right now

In some cases it seems to take a different positional Shadow Map, and in the case in this screenshot the Spot Light is Taking the Directional Shadow map's shadow

![image](https://github.com/godotengine/godot/assets/50302479/a1430ded-5ffa-42c5-a67d-e85c7003d5b5)

### Steps to reproduce

Play around with a bunch of different lights for a while, and observe how some lights start having wrong shadow maps

### Minimal reproduction project (MRP)

Unable to Create MRP, as I haven't figured out exactly how to trigger it, it just happens, and I haven't been able to narrow it down yet, will update if I figure out how to trigger, and the results change when restarting the editor.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92091.
