### ISSUE TITLE
Unable to disconnect signal in editor

### ISSUE THREAD

**Issue by Piratux** [godotengine/godot#92483]
### Tested versions

Reproducible: 
- v4.2.2.rc.custom_build [c57002e0b]
- v4.2.2.stable.custom_build [15073afe3]

### System information

Windows 10

### Issue description

I have a signal on a node (`tree_exited`) that is marked in yellow colour that I cannot disconnect.

When this issue happened for first time:
- I noticed there was *.tmp file.
- When I tried to close the editor, I constantly got the popup "Save changes ... before quitting" even when I clicked "Save & quit".

I've tried to remove .godot folder, restart the editor, but I still cannot disconnect the `tree_exited` signal.

![image](https://github.com/godotengine/godot/assets/58703216/e78adc8e-1eff-4c1e-bce7-365c10f6cfe0)

### Steps to reproduce

Unfortunately I can't recall exact steps I performed to have this issue happen.

I just remember, that I:
- Attempted to swap `tree_exited` signal to `tree_exiting` signal.
- Edited the script
- Ran the program
- Tried to save something in the editor
- Got the popup for a split second that mentioned my file is locked (Something along the lines of this: https://github.com/godotengine/godot/blob/1e6b11dcd4ad3abb7c621674674b718f5e0a2278/editor/editor_node.cpp#L5548 )

### Minimal reproduction project (MRP)

I don't think it will be much of help, because after `git stash`'ing my changes, issue still persists.
Before I started making changes, there was no issue.

**Comment by huwpascoe** [comment]
If the file is actually locked, the simplest way to unlock it is to restart Windows.

Is the scene inherited? If so then the yellow indicates that it needs to be removed from the base scene. 

If the above don't help then an MRP can show why it's broken. 

IMO the editor shouldn't disable the disconnect button, it should show a clear warning **why** disconnecting could fail and attempt to disconnect anyway if the user forces it.

**Comment by Piratux** [comment]
> If the file is actually locked, the simplest way to unlock it is to restart Windows.
Currently none of the files are locked.
The file locked popup was shown to me just once and never again.

> Is the scene inherited? If so then the yellow indicates that it needs to be removed from the base scene.
Ah it seems that this could be the case then.
I made simple example to check and I see Disconnect signal button being disabled.
So it just seems I hadn't noticed it before.

![image](https://github.com/godotengine/godot/assets/58703216/8c3e548f-9c66-4630-b03e-65694f9832e6)

> IMO the editor shouldn't disable the disconnect button, it should show a clear warning why disconnecting could fail and attempt to disconnect anyway if the user forces it.
Agree with this part. Current solution seems non-intuitive.

Anyway looks like it was false alarm on my part. All is good now.
