### ISSUE TITLE
Addon requires editor restart to become functional

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92493]
### Tested versions

4.3 dev6
any version tbh

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Technically part of #84811
I have a plugin with example project. When you download it and open, on first launch it will not be functional. The custom screen is empty and spams errors. You can disable and enable the addon, but it doesn't help.

My current workaround is automatic restart of the editor, as there is no other way to make it work.

### Steps to reproduce

1. Download zip of this branch: https://github.com/KoBeWi/Metroidvania-System/tree/bug_branch
2. Open the included project
3. Once it loads, go to MetSys main screen
4. The screen is empty and spams errors in the output

### Minimal reproduction project (MRP)

See above.

**Comment by TokisanGames** [comment]
Is this issue asking to address GDScript addons only, or GDExtensions as well?
