### ISSUE TITLE
Collisionshape2d handle bug in Android version  

### ISSUE THREAD

**Issue by panjerehsoft** [godotengine/godot#92491]
### Tested versions

godot 4 for android 

### System information

android phone

### Issue description

The collisionshape2d size adjustment handles are not movement   

### Steps to reproduce

_

### Minimal reproduction project (MRP)

_

**Comment by AThousandShips** [comment]
Please provide the complete version, and please add some more detail, this is not enough to evaluate

**Comment by panjerehsoft** [comment]
Godot engine v4.0.2.stable.official [7a0977ce2] android editor

**Comment by AThousandShips** [comment]
Please use a more recent version, 4.0 is no longer supported, please try 4.1.4 or 4.2.2

Also please explain what is not working and how it's supposed to work

**Comment by panjerehsoft** [comment]
The problem was solved by updating to the latest version.  Thankful
