### ISSUE TITLE
Sometimes the Show Desktop button makes the editor crash

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#92510]
### Tested versions

4.2.1

### System information

Windows 10

### Issue description

Sometimes when I press the Show Desktop button, the editor crashes. Minimizing seems to work just fine.

### Steps to reproduce

Press the button, retry many times.

### Minimal reproduction project (MRP)

Sorry, I can't upload the project.

**Comment by AThousandShips** [comment]
Please try in 4.2.2 to make sure this hasn't already been fixed

**Comment by HerrSersch** [comment]
Duplicate of  #76709. I can confirm that it still happens in 4.2.2. I've added a comment with more details to the linked issue.
