### ISSUE TITLE
Area2D not triggering body_entered.

### ISSUE THREAD

**Issue by bleedweedsuz** [godotengine/godot#92512]
### Tested versions

Godot 4.2.2 (15073afe3)

### System information

Mac OS 14.5 (23F79)

### Issue description

Area2D not triggering body_entered signal if other Area2D node collide.

### Steps to reproduce

Simple test code Project included in MRP section
```
extends Node2D

@onready var area_2d = $Area2D
@onready var area_2d_2 = $Area2D2
@onready var static_body_2d = $StaticBody2D

func _ready():
	area_2d.monitoring = true
	area_2d_2.monitoring = true
	
	area_2d_2.connect("body_entered", Callable(self, "_bodyEnter"))
	area_2d.connect("body_entered", Callable(self, "_bodyEnter2"))

func _bodyEnter(body):
	print("Area2D2 detected body: ", body)
	
func _bodyEnter2(body):
	print("Area2D detected body: ", body)
	
func _physics_process(delta):
	area_2d.position.x += delta * 100  # Adjust speed if necessary
	area_2d_2.position.x -= delta * 50  # Move Area2D2 in the opposite direction
```

### Minimal reproduction project (MRP)

Test Project

[TestCollision.zip](https://github.com/godotengine/godot/files/15483672/TestCollision.zip)

**Comment by bleedweedsuz** [comment]
Holy mother of god how did i miss that. 
wasted 4 hrs

**Comment by AThousandShips** [comment]
The documentation is your friend! It's a good habit to develop to read it when ever something doesn't work out
