### ISSUE TITLE
Very slow to connect debugger

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#92515]
### Tested versions

v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

I'm print time in _physics_process. 
![image](https://github.com/godotengine/godot/assets/35988767/bfa38bc0-08fd-4c93-af58-e5afa49285f4)

look at output int the GIF, it take about 15s then start print.
![GIF 2024-5-29 21-52-25](https://github.com/godotengine/godot/assets/35988767/7f240123-1a58-4b93-a525-eb2c96d91b87)

### Steps to reproduce

In my project, it always take long time to print or debug (use a other pc was this isssue too).
but I can't found a MRP, maybe it was because my project was too large or too much gds. it about 3G.

### Minimal reproduction project (MRP)

None

**Comment by AThousandShips** [comment]
This is very hard to evaluate with the details you've given, more details are probably required to do anything with this, like what tool you're using to debug, what setup, etc.

**Comment by CsloudX** [comment]
very like https://github.com/godotengine/godot/issues/93104
before run a scene, it save scene first. and I'm test for only save scene. it freeze a while.

**Comment by akien-mga** [comment]
Fixed by #93147.
