### ISSUE TITLE
Adding Shortcut for Remote Debug adds but doesn't works.

### ISSUE THREAD

**Issue by mcdz** [godotengine/godot#92522]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.3758) - AMD Ryzen 3 3100 4-Core Processor (8 Threads)

### Issue description

Can't use shortcut for remote debug.

### Steps to reproduce

add shortcut in settings / shortcuts for remote debug.
try the shortcut.

### Minimal reproduction project (MRP)

any project would do.

**Comment by bruvzg** [comment]
> Can't use shortcut for remote debug.

What are you trying to do? And which shortcut are you setting, `editor/deploy_with_remote_debug`? This action will only toggle `Debug->Deploy with Remote Debug` menu option, it's not for starting remote debug (there's no action for it since different export platforms have different one-click-deploy options).

**Comment by mcdz** [comment]
> > Can't use shortcut for remote debug.
> 
> What are you trying to do? And which shortcut are you setting, `editor/deploy_with_remote_debug`? This action will only toggle `Debug->Deploy with Remote Debug` menu option, it's not for starting remote debug (there's no action for it since different export platforms have different one-click-deploy options).

Ah, I see. I wanted to use shortcut to run on android. Could be great if such option is available, or is added somewhere in export view.
Thanks for clearing the confusion. 👍  :)
