### ISSUE TITLE
Toggling distraction-free mode with external script editor enabled opens a new editor every time.

### ISSUE THREAD

**Issue by Nomkid** [godotengine/godot#92529]
### Tested versions

- Reproducible in v4.3.dev6.official [64520fe67], unable to test other versions at the moment.

### System information

Godot v4.3.dev6 - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Wed Apr  3 13:29:04 UTC 2024 - Wayland - GLES3 (Compatibility) - Mesa Intel(R) HD Graphics 2000 (SNB GT1) - Intel(R) Pentium(R) CPU B940 @ 2.00GHz (2 Threads)

### Issue description

When using external editors, I use Godot with distraction-free mode enabled so I can read the builtin docs. When toggling that mode on and off, a new instance of my editor is opened and takes focus. This is undesirable behavior as I have to close the second editor every single time.

### Steps to reproduce

1. Enable an external script editor
2. Open any script
3. Toggle the distraction-free mode on and off

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- Looks related to https://github.com/godotengine/godot/issues/90654
- should be fixed by #91168

**Comment by AThousandShips** [comment]
Please try [beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/) and see if it's fixed

**Comment by Nomkid** [comment]
Yes, issue is fixed in beta1.
