### ISSUE TITLE
Autocompletion fails when script is attached in the current scene

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92527]
### Tested versions

v4.3.beta.custom_build [8bf8f41fc]

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/b97d1cae-f6b1-4808-ac53-8c10192d0888

### Steps to reproduce

1.
```GDScript
extends Node

func _ready() -> void:
	var dup := duplicate()
	
```
2. Make a new scene and attach this script
3. Try autocompleting `dup` methods while the scene is opened

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
I can reproduce it, but easily fixes by saving a scene (pressing CTRL+S by default).
