### ISSUE TITLE
Resource on dictionary not represented correctly in the inspector. It shows as a number instead of an object 

### ISSUE THREAD

**Issue by zzzamo** [godotengine/godot#92533]
### Tested versions

Issue is present in Godot_v4.3-dev6
I tested on Godot_v4.2.2-stable and it works Ok

### System information

Windows 10 - Godot_v4.3-dev6

### Issue description

Whenever I try adding Resource to a Dictionary it brings me this error

`editor/editor_properties.cpp:1328 - Cannot reliably represent '-9223372002008496859' in the inspector, value is too large.`

### Steps to reproduce

1. Add new Node
2. Add a new script to the node
3. Add 2 exports to the script and use _ready to assign resource to a value in the dictionary
```
extends Node

@export var dictionary:Dictionary
@export var resource:Resource

func _ready() -> void:
	dictionary[0] = resource
```
4. create new tres file from a Resource
5. put newly created tres file on the inspector under resource variable on node
6. run the application
7. go to remote tab on scene
8. select the node and look for the dictionary variable
9. expand it
10. you'll get the error mentioned before

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/godotengine/godot/files/15493859/new-game-project.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #88231 as the culprit: 
![image](https://github.com/godotengine/godot/assets/44306054/7d52009e-0e9e-4b0f-8012-0682d889ffef)

<br>

Here is how the inspector would look in a normal build:
![Captura 2024-06-07 19-17-47-625220](https://github.com/godotengine/godot/assets/44306054/de5d7737-9c0a-425e-aec4-f20a9aa75d99)

<br>

And here how is looking with this bug:
![Captura 2024-06-07 19-18-45-399819](https://github.com/godotengine/godot/assets/44306054/f2ee4d22-b82b-4468-891c-dc81414602ff)

<br>

And the warning spam:
![Captura 2024-06-07 19-18-51-999889](https://github.com/godotengine/godot/assets/44306054/9a772947-d7c7-4f68-b140-d775cfa48b79)

**Comment by dalexeev** [comment]
CC @ajreckof @KoBeWi

**Comment by ajreckof** [comment]
I'm on vacation en and can't debug it. I'll handle it when coming back on the 20. But if someone wish to look into it before hand this looks like an object being represented as RID and the inspector not detecting it properly and dealing with it as a number hence the warning.

**Comment by zzzamo** [comment]
Changed the title on the bug to be more detailed

**Comment by KoBeWi** [comment]
It only happens at runtime. The Resource shows correctly in the editor.
