### ISSUE TITLE
Missing "Manage Groups" Button in "Scene -> Node -> Groups" Menu

### ISSUE THREAD

**Issue by layton7362** [godotengine/godot#92547]
### Tested versions

Latest master Build
Git commit hash: e7dd6f11ed1ed4d72186d3a90d5f4ef42e79c4d0

### System information

Windows 11, Godot 4.3-latest

### Issue description

Manage Button is missing in current master branch:

![grafik](https://github.com/godotengine/godot/assets/43618510/9e3cf014-83e3-44eb-9bec-ba6c061a8b96)

It should be like this:

![grafik](https://github.com/godotengine/godot/assets/43618510/d36eb4c9-c9f4-4aaf-8789-f7358d6ee059)

In 4.2 it works fine.

### Steps to reproduce

Just create a scene and click on a Node -> Tab Node -> Groups

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Removed in https://github.com/godotengine/godot/pull/60965

**Comment by layton7362** [comment]
Ah ok. The [documentary](https://docs.godotengine.org/en/stable/tutorials/scripting/groups.html) is out of date. I'll open an issue for it.
