### ISSUE TITLE
Vehicle physics behave strangely (regression)

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#9254]
I know that the physic engine is changing; so it should expected that some features will behave differently, so this may not be actually a bug.

from the https://github.com/godotengine/godot-demo-projects/tree/2.1/3d/truck_town demo I've stripped the basic car, then exported the GD2 project to GD3 (I had just to rename the godot.project file); and made a video on how differently the car behave in the two engine.

https://matrix.org/_matrix/media/v1/download/matrix.org/eMBwSLTXeDijwgVENfuLZjfH

file project are here: https://matrix.org/_matrix/media/v1/download/matrix.org/CsfnnmOhTPOBZXHanolAeHPV

**Comment by Zireael07** [comment]
Aha, so it's not just me! I was going to report this but I thought I did something wrong when exporting.

@alexwbc: you might want to edit the title to say "Vehicle physics behave strangely" so that it's obvious it refers to the car physics and not some other part of the physics engine.

**Comment by adtofaust** [comment]
It also seems that providing any non zero value to Steering works like a brake.

**Comment by Zireael07** [comment]
Bump. 

From my poking around when I made a PR, the vehicle code looks roughly the same in 2.1 and 3.0 excepting the function renames. Maybe the January Maths revisions (changing the order of rotations etc.) are at fault there?

**Comment by Zireael07** [comment]
I made a quick repro in 3.0 alpha. Car's settings and the body of the script used to control came from the 2.1. truck town demo. Just drive around on the plane to see it bounce around. If you come to a stop, it doesn't, instead continues to jitter diagonally to the position it was in when you tried to stop.

[car repro.zip](https://github.com/godotengine/godot/files/1214291/car.repro.zip)

**Comment by adtofaust** [comment]
I can confirm bugs mentioned by @Zireael07  (latest build 81dde26):
- jittering
- it's definitely too easy to overturn the car when turning left/right
- car doesn't stop on brake and is turning 180 degrees in Y axis with camera not rotating with it (which also means that camera doesn't respect angle limits)

**Comment by Zireael07** [comment]
I am beginning to suspect that the ultimate cause of this bug is the joint code.

Enabling Bullet (#10013) fixes the issue and Andrea did not touch the actual car code. Furthermore there is an open issue about joints being broken.

**Comment by Zireael07** [comment]
Fixed by #12641 !!!
