### ISSUE TITLE
KinematicBody2D move() pushes too far outside of collider

### ISSUE THREAD

**Issue by Silvea12** [godotengine/godot#9255]
**Operating system or device - Godot version:**
Arch Linux x86_64, Godot 2.1.3

**Issue description:**

When running move() in a way that would move a kinematicbody2d into a tilemap (which I assume uses a staticbody2d), the move will move you out of the collider too far, causing you to float a short distance (less than 0.05 units for shorter moves) outside of the collider, rather than moving directly onto its surface. This causes jitteryness when handling gravity and wall collisions, and can even cause things like accidental jump boosts when hugging walls, if working on a small scale (in this case, 512x512 window size running at 0.125x scale)

**Steps to reproduce:**
Place a square with a staticbody2d and any collider with a flat surface (square works nicely).
Create a kinematicbody2d with a collider (square works nicely).
Put into `_fixed_update()` code to run `move()` that causes it to run into the collider head-on.
Watch it micro-jitter like hell.

**Link to minimal example project:**

[game.zip](https://github.com/godotengine/godot/files/1083324/game.zip)
Controls: w/d + space, or left+right+up
In this, a high jump can be achieved by uncommenting the `move()` in the collision check for `res://scripts/player.gd`, and then hugging the walls as you jump

**Comment by eon-s** [comment]
Not sure if is a bug because by default is always pushing it 0.08 from the hit points.
In this example project you can get a better floor movement with a collision margin of 0.05 and a better wall hit effect with 0.04.

**Comment by Silvea12** [comment]
@eon-s Oh shit, I completely missed that. Would be nice though if we could move right on top of it, but yeah that works. Thanks, I'll close the bug.
