### ISSUE TITLE
PackedStringArray missing methods

### ISSUE THREAD

**Issue by Vlad-Zumer** [godotengine/godot#92562]
### Tested versions

- Reproductible on v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 10 - v4.2.2.stable.mono.official

### Issue description

Methods missing on the `PackedStringArray` (and I believe on all the packed arrays). 

They can be implemented by the user with the available methods but I believe it's a good idea to have consistent APIs.

For a `Packed Array` containing the type `T` (`PackedArray<T>`) the following methods need to be implemented:
 
```c++

bool all ( Callable method ) const
bool any ( Callable method ) const
PackedArray<T> filter ( Callable method ) const
Array<Variant> map ( Callable method ) const
Variant reduce ( Callable method, Variant accum=null ) const
void sort_custom ( Callable func )
int bsearch_custom ( T value, Callable func, bool before=true ) const
T back ( ) const
T front ( ) const
T pick_random ( ) const
void erase ( T value )
T pop_at ( int position )
T pop_back ( )
T pop_front ( )
void push_front ( T value )
void shuffle ( )

```

### Steps to reproduce

Attach this script to any node.

```gdscript
extends Node

func _ready() -> void:

	# Works
	# var arr : Array[String] = ["1","2","3","4","5","10","20","30","40","50","100","200","300","400","500","1000","2000","3000","4000","5000"]

	# Does not work
	var arr : PackedStringArray = ["1","2","3","4","5","10","20","30","40","50","100","200","300","400","500","1000","2000","3000","4000","5000"]
	
	arr.all(func (item: String) -> bool: return item.length() >= 2)
	arr.any(func (item: String) -> bool: return item.length() == 0)
	arr.back()
	arr.front()
	arr.erase("1")
	arr.filter(func (item:String) -> bool: return item.length() == 3)
	arr.map(func (item:String) -> int: return int(item))
	arr.pick_random()
	arr.pop_at(2)
	arr.pop_back()
	arr.pop_front()
	arr.push_front("0")
	arr.reduce(func (acc: String, item: String) -> String: return acc + item, "")
	arr.shuffle()
	arr.sort_custom(func (item1: String, item2: String) -> bool : return item1.length() < item2.length())

```

### Minimal reproduction project (MRP)

[PackedArrayMissingMethods.zip](https://github.com/godotengine/godot/files/15503557/PackedArrayMissingMethods.zip)

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

**Comment by Vlad-Zumer** [comment]
Is this not a bug, or are `Packed Arrays` not supposed to be a better version of the normal `Array`?

**Comment by AThousandShips** [comment]
They're designed to be tighter and more performant storage, not a plain superior version, implementing these features would require writing new dedicated methods for them, as they do not exist in the underlying type, unlike `Array`

So this isn't a missing intended feature, but something that can be discussed as an improvement

**Comment by AThousandShips** [comment]
The `Packed*Array` types are primarily designed to do two things:
* Store data efficiently, by not storing `Variant` but the real data type
* Pass data back and forth between scripting and the engine, especially for servers, in a way that avoids having to constantly convert between `Array` and what ever specific data type is required

Internally they just use an engine data type called `Vector`, which lacks a lot of the features `Array` does, the special methods in `PackedByteArray` for example is only available to scripting on `PackedByteArray` and are implemented in the bindings, not on the `Vector<uint8_t>` type itself. The same would likely have to be done for the suggested methods, as they would not be very relevant to `Vector` itself as we don't use those methods in the engine core

The one exception really would be `sort_custom` which already exists, but it'd have to be bound in a custom way as the built-in one doesn't take a `Callable` but a comparator

Further the `pop` methods have been suggested before but can't be trivially implemented, as they'd be unable to return a value, unlike `Array` where they can return `Variant()` there's no way really to return clearly a `null` for `int` for example. See:
* https://github.com/godotengine/godot/pull/83000

**Comment by Vlad-Zumer** [comment]
Thanks for the in-depth explanation of what is the desired purpose of the `Packed Arrays` is. I will open a proposal instead.

Still, I think most of the proposed methods (execpt the `pop` group) make sense to be implemented for `Packed Arrays` as well. (I'm going to try my hand at it.)

**Comment by AThousandShips** [comment]
Closing as per the above
