### ISSUE TITLE
Null references not working as intended in Godot 4.3 dev6?

### ISSUE THREAD

**Issue by jktrctt** [godotengine/godot#92569]
### Tested versions

Reproducible in 4.3 dev6 

### System information

Windows 10, Godot 4.3 dev6, Vulcan dedicated

### Issue description

In 4.3 dev6, null references to objects that were freed do not work in the same way they did in 4.2. For example, if a variable contains a reference to an object and the object is freed, the statement:
`if object_reference != null`
no longer returns false. 

### Steps to reproduce

Run this project in both 4.2 and 4.3 dev6 and you will see that it behaves differently. 

Or just run this code in a blank scene with a Node2D in it: 

```
extends Node2D


var reference : Node2D


func _ready():
	reference = $Node2D
	print(reference)
	reference.queue_free()
	

func _process(delta):
	if reference != null:
		print(reference)

```

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/15505540/MRP.zip)

**Comment by akien-mga** [comment]
This was an intentional change in 4.3, see #73896 and #90513 for details.
