### ISSUE TITLE
No way to get available audio driver names in Godot 4

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#92589]
### Tested versions

4.3.beta1

### System information

Linux mint

### Issue description

Hy, i'm updating a project (it's a pixelorama extension) from Godot 3 to 4 and i am unable to find any equivalent of
```
OS.get_audio_driver_count()
OS.get_audio_driver_name()
```
please add them if they aren't, or tell me about the equivalents of the above methods
(I know that you can set the audio server from command line but it'll become annoying for the users of my extension so i prefer not to use it)

### Steps to reproduce

(none)

### Minimal reproduction project (MRP)

(none)

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

**Comment by Calinou** [comment]
Proposal opened: https://github.com/godotengine/godot-proposals/issues/9858
