### ISSUE TITLE
Project manager lists unavailiable update for "4.3-4.3"

### ISSUE THREAD

**Issue by parsadaj** [godotengine/godot#92593]
### Tested versions

happens in Godot_v4.3-beta1
not happens in Godot_v4.3-dev6

### System information

Windows 11 - Godot_v4.3-beta1

### Issue description

when I open Godot, the bottom of the Project Manager is written: "Update available: 4.3-4.3.".
When I click on it it brings me to https://godotengine.org/download/archive/4.3-4.3 where I encounter a 404 error.

### Steps to reproduce

open Godot_v4.3-beta1_win64.exe after unzip.

### Minimal reproduction project (MRP)

there is no need for this because the bug is not related to any project

**Comment by parsadaj** [comment]
![screenshot](https://github.com/godotengine/godot/assets/53321170/531138bf-926e-4618-b477-ef73f5d2cef1)

**Comment by SpockBauru** [comment]
Can confirm this behavior. After enable the "online" mode I'm getting the exact same issue as op.
Using Godot v4.3.beta1.official [a4f2ea91a] on Windows 11 23H2.

**Comment by passivestar** [comment]
same

<img width="383" alt="image" src="https://github.com/godotengine/godot/assets/60579014/dccfe829-daf3-472f-a594-69db240dc74e">
