### ISSUE TITLE
AnimatedSprite2D bottom panel closes when adding/removing animation

### ISSUE THREAD

**Issue by chriztheanvill** [godotengine/godot#92600]
### Tested versions

Only in 4.3 dev 6 and 4.3-beta-1
This not happens in 4.2.x

### System information

Godot v4.3.beta1 - openSUSE Tumbleweed 20240524 - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

When creates a new Animation in AnimatedSprite2D, closes the bottom panel. I thought it was Wayland so, switched to original config, and still.

### Steps to reproduce

- Create a new AnimatedSprite2D
- Click in SpriteFrames <empty>
- New SpriteFrames
- Click in SpriteFrames to show the botton panel SpriteFrames
- Here, After click: Add Animation or Delete Animation, Closes the Botton panel "Sprite Frames".

![image](https://github.com/godotengine/godot/assets/37992958/10e20a94-f25f-402a-8a61-dc440e728f3c)

### Minimal reproduction project (MRP)

With a new project

**Comment by matheusmdx** [comment]
Tested with 4.3,dev6 and latest master v4.3.beta.custom_build [705b7a0b0], bisecting points to #90815 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/3a158c0b-f61d-4033-a323-ffd6a07b330a)

A thing i noticied is if you click in another scene tab or click in the node/history tab, the bug stops until you create another SpriteFrames resource

https://github.com/godotengine/godot/assets/44306054/7e24a3c9-4b5d-4093-b664-eb447c08fdbc
