### ISSUE TITLE
4.3 beta 1 Button theme / content margin

### ISSUE THREAD

**Issue by alberto-mco** [godotengine/godot#92602]
### Tested versions

- Not reproducible in Godot 4.3 dev6
- Reproducible in Godot 4.3 Beta 1

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.5244) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

After updating to Godot 4.3 beta 1 from 4.3 dev 6, I noticed that the content margin in a StyleBoxTexture is not applied.

https://github.com/godotengine/godot/assets/70795945/ec45967f-9101-41c4-b8d5-814a08d4dc9a

https://github.com/godotengine/godot/assets/70795945/31c27d5e-14db-4baf-aa88-17095e31035b

### Steps to reproduce

- Create a button
- Create a new theme
- Assign the styles in StyleBoxTexture
- Modify the "content margin" when the button is pressed

I have prepared an example zip

### Minimal reproduction project (MRP)

[button_theme.zip](https://github.com/user-attachments/files/15517854/button_theme.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #92009 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/ebaad838-8d54-4790-8602-bf823bc6c407)
