### ISSUE TITLE
Tooltips are drawn outside of screen on web builds, making them cut off / cropped and unreadable, when stretch mode is set to viewport

### ISSUE THREAD

**Issue by skeddles** [godotengine/godot#92601]
### Tested versions

- v4.2.1

### System information

Windows 10 - Godot v4.2.1

### Issue description

Here is what a tooltip looks like on my windows build, it stays within the screen
<img width="764" alt="Godot_v4 2 1-stable_win64_2024-05-31_14-46-20" src="https://github.com/godotengine/godot/assets/2721332/cc7b8d47-8beb-4eaf-a66d-1290897e21c3">

Here is what the same tooltip looks like on the same game, built for HTML5
<img width="841" alt="firefox_2024-05-31_14-50-58" src="https://github.com/godotengine/godot/assets/2721332/ed7d12e9-9681-4853-9f82-636adc792c4b">

And again with my example project:
<img width="270" alt="firefox_2024-05-31_15-02-21" src="https://github.com/godotengine/godot/assets/2721332/8cc07ea9-7584-457c-a452-c5b00615a06a">
<img width="151" alt="Godot_v4 2 1-stable_win64_2024-05-31_15-02-30" src="https://github.com/godotengine/godot/assets/2721332/128bbca7-e83b-41a6-aed5-955503ffbf92">

It does not seem to recognize that the tooltip is too close to the edge of the screen, and needs to be moved over. This happens even if I resize the window to fit the game view. 

### Steps to reproduce

1. in settings under display > window, set stretch mode to viewport
2. put a button or other element with a tool tip near the right side of the screen
3. build for web

### Minimal reproduction project (MRP)

View export online: https://skeddles.itch.io/godot-tooltip-broken-web-exmaple?secret=FcL5R2zAnAJCuXxvirEsvGHDkBQ

[TooltipsBrokenExample.zip](https://github.com/user-attachments/files/15517751/TooltipsBrokenExample.zip)

**Comment by patwork** [comment]
This is not exclusive to web export.

![set](https://github.com/godotengine/godot/assets/224215/9aced0f8-5490-44a5-b99a-5c9d4b3876a9)

![off](https://github.com/godotengine/godot/assets/224215/c2b29b44-4cd6-4c66-98f9-25a345f77bba)
