### ISSUE TITLE
Invalid call. Nonexistent function 'reload' in base 'GDScript'.

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#92610]
### Tested versions

v4.3.beta1.mono.official [a4f2ea91a]

### System information

Godot v4.3.beta1.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Coding like this:
```
extends Node

var obj = RefCounted.new()
var gds = GDScript.new()

func _ready():
	gds.source_code = "func a():return 100"
	gds.reload()
	obj.set_script(gds)
	var rs = obj.a()
	prints(rs)

```

![image](https://github.com/godotengine/godot/assets/35988767/424d7e95-1ace-4721-8c0a-e8ff08ce994f)
This code work before 4.3dev6 and output 100.

### Steps to reproduce

run the MRP, it report error

### Minimal reproduction project (MRP)

[gdstest.zip](https://github.com/user-attachments/files/15519573/gdstest.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #92035 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/b70d0bc5-0c16-4079-9961-30868a6cf103)

**Comment by matheusmdx** [comment]
Cherry-picked #92609 and seems to solve this issue

**Comment by rune-scape** [comment]
this is probly bc if there were any errors compiling (possibly another gdscript bug related to built-in scripts), sets the script as not 'valid', then https://github.com/godotengine/godot/pull/92035 restricted GDScript member functions too much so that `reload` wasnt a valid function if the script isnt valid, thats what https://github.com/godotengine/godot/pull/92609 fixes

**Comment by CsloudX** [comment]
Oh no, this issue was broken my project. but it not fixed in 4.2beta2, so I can't update to beta2 for test my project, it make me so sad.
Can this issue fixed in the next version(4.3beta3)?

**Comment by akien-mga** [comment]
@CsloudX There's a PR pending review: #92609. If you can test it and confirm it fixes your issue, that helps the review process to have confidence that it covers potentially more complex cases than the ones in MRPs. See https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html for instructions on how to test a PR.

**Comment by CsloudX** [comment]
> @CsloudX There's a PR pending review: #92609. If you can test it and confirm it fixes your issue, that helps the review process to have confidence that it covers potentially more complex cases than the ones in MRPs. See https://docs.godotengine.org/en/stable/contributing/workflow/testing_pull_requests.html for instructions on how to test a PR.

Thanks, but like this pull request date-outed.
https://github.com/godotengine/godot/issues/92610#issuecomment-2182257111

**Comment by matheusmdx** [comment]
@CsloudX Here, i compiled the latest master with pr 92609 cherry-picked (i'm assuming you're a windows user): https://drive.google.com/file/d/1JO2erXW6G8r70B8ECaL1keojdFmHOwrk/view?usp=sharing
