### ISSUE TITLE
[4.3 Beta 1] AnimationPlayer animation list scroll bar disappears after first use.

### ISSUE THREAD

**Issue by MisterWob** [godotengine/godot#92614]
### Tested versions

- Reproducible in 4.3 Beta 1
- not reproducible in 4.3 dev 5, 4.3 Dev 6

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 SUPER (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

An AnimationPlayer node with an animation list long enough to warrant a scrollbar will have its scrollbar disappear, forever until project restart, after you click off the animation list for the first time. Scrolling with a mouse no longer works but using the arrow keys to select animations will still work but you won't be able to see the animation you're selecting if it's off screen.

First time opening the animation list:
![1st_Click](https://github.com/godotengine/godot/assets/42462432/19d15786-2d7f-420e-98fa-ee89a9805877)

Second time opening the animation list:
![2nd_Click](https://github.com/godotengine/godot/assets/42462432/76eb3f47-917c-4574-b38d-96e76f96136e)

### Steps to reproduce

In a new or existing project.
- Add an AnimationPlayer Node
- Create as many animations as you need for a scrollbar to appear
- Once there is a scrollbar, click off the animation list menu so that it disappears
- Click the animation list so the menu appears again
- There should now be no scrollbar and scrolling through animations should no longer be possible.

### Minimal reproduction project (MRP)

[AnimationPlayerScrollTest.zip](https://github.com/user-attachments/files/15519771/AnimationPlayerScrollTest.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #91613 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/a59100ca-5a30-4866-a22d-09fd459d12c2)
