### ISSUE TITLE
Buttons with textures do not work correctly (pixel art)

### ISSUE THREAD

**Issue by dpnnl** [godotengine/godot#92613]
### Tested versions

Godot 4.3 beta 1

### System information

Windows 11 - Godot 4.3 beta 1

### Issue description

I'm using buttons with texture (pixel art), there are two textures: normal and pressed. Note that in Godot 4.2 when pressing the button the button text is also pressed, which does not happen in 4.3. This problem also occurs with icons on buttons.

[
![Captura de tela 2024-05-31 215114](https://github.com/godotengine/godot/assets/84047200/8f57a85b-db54-44a3-8f5d-7d34e8ba1e45)
![Captura de tela 2024-05-31 215150](https://github.com/godotengine/godot/assets/84047200/e311e3df-2a35-4962-99e9-553b7d4b4996)
](url)

Godot 4.2:

https://github.com/godotengine/godot/assets/84047200/e79b8ca9-554b-4d39-a1c7-bd2c038217a8

Godot 4.3

https://github.com/godotengine/godot/assets/84047200/fe7b2918-69f7-4732-a15b-1e074a1a81fb

### Steps to reproduce

Add two textures (pixel art) for buttons and change the region of the button texture when clicked.

### Minimal reproduction project (MRP)

[Button Test.zip](https://github.com/user-attachments/files/15519729/Button.Test.zip)

**Comment by matheusmdx** [comment]
Testing with 4.3.dev6 and works as expected, this looks to be a similar/duplicate issue from #92602 and probably has the same cause: #92009, Im bisecting another issue now but i'll confirm later if is a regression from #92009

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92602

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
