### ISSUE TITLE
Control Show/Hide Background size bug

### ISSUE THREAD

**Issue by sky94520** [godotengine/godot#92618]
### Tested versions

- Reproducible in 4.3.beta1 [[a4f2ea91a](https://github.com/godotengine/godot/commit/a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0)]

### System information

Windows 11 Professional - Godot v4.3.beta1 - Compatible

### Issue description

While I show and hide Control, the background will no correct size.
First, move mouse to first image, the tooltip shows correctly.
![image](https://github.com/godotengine/godot/assets/37724405/30e13b7e-a2c4-4bd2-8091-39f003508a53)

Second, move over and in again, the tooltip hide and show, it is false:
![image](https://github.com/godotengine/godot/assets/37724405/cdc44479-df34-4e4c-9adc-0e7277141304)

While I move mouse to second sprite, the tooltip show correctly again.
![image](https://github.com/godotengine/godot/assets/37724405/6d3fec92-9fd3-438b-9098-d00349a9c3d9)

### Steps to reproduce

Please execute the following program and move the sprite again.

### Minimal reproduction project (MRP)

[ShowAndHide.zip](https://github.com/user-attachments/files/15520160/ShowAndHide.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #91613 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/6834c4f6-a67c-497b-9b11-a4011f413647)
