### ISSUE TITLE
Editor re-starts (specifically executing _enter_tree() on tools) scenes when reimporting anything

### ISSUE THREAD

**Issue by Bonkahe** [godotengine/godot#92623]
### Tested versions

Reproducible in: 4.3 beta 1 (I don't know which commit sorry)

### System information

Windows 10

### Issue description

When updating to 4.3 beta 1, I noticed an issue with importing or re-importing any resource, this results in the scene your currently running within the editor to be reloaded, executing enter scene as if the scene has been loaded for the first time.
I currently have been working on a terrain system for 6 months, and it loads on the build, while generating the terrain it bakes to disc, this immediately resulted in an infinite loop of baking terrain, then reloading the scene and starting again.

I am unsure specifically if this is intended behavior or not, it is prohibitive to my project if it is and I would like to protest the decision to include this if so.

Thanks for any help.

### Steps to reproduce

1. Create new project
2. Create a tool script with gd.print("Test") in the enter tree func
3. Restart to let tool script be picked up by editor
4. Run scene with the tool script present
5. re-import the icon.svg default to godot projects

### Minimal reproduction project (MRP)

[reimporttesting.zip](https://github.com/user-attachments/files/15520766/reimporttesting.zip)

**Comment by Rindbee** [comment]
Currently, exiting and re-entering the scene root tree is required:
1. To process data related to scene history, we need to ensure that the scene is in the tree;
2. Different scene roots may have the same name, so ensuring that only one scene is in the tree at the same time is necessary to ensure that the node path is correct.

If your code only needs to process when the tree is first entered, you can use a flag. 
```
var first_enter_tree = true

func _enter_tree() -> void:
	if first_enter_tree:
		first_enter_tree = false
		# Put the code that needs to be processed for the first time here.
```
Or try putting it in `_ready()` if possible.

**Comment by Bonkahe** [comment]
Closing due to worked around, and it's not a bug.
