### ISSUE TITLE
The match() method of the String type fails even on simple patterns

### ISSUE THREAD

**Issue by sancho2** [godotengine/godot#92624]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

Godot v4.2.stable - Windows 6.1.7601 - GLES3 (Compatibility) - GeForce 8600 GTS () - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

The match() method of the String type uses regex to return a bool if a pattern is matched in the string. This method failed to find any matches when the pattern used a list ie [ ]      
I tested this on Windows 7 and also on Ubuntu 24.x.    
I tested the regex expressions on regex101.com and they all work there.  
I tested these regex expressions in Python script and they work as expected there.   

### Steps to reproduce

```
func _ready() -> void:
	printt("3".match("3"), "3".match("[1234]"), "3".match("[3]"), "3".match("*"), "3".match("[123]*"))
	printt("a".match("a"), "a".match("[abcde]"), "a".match("[a]"))

```    
This outputs:
```
true	false	false	true	false
true	false	false
```    
All of these should have produced true.   

### Minimal reproduction project (MRP)

```
func _ready() -> void:
	printt("3".match("3"), "3".match("[1234]"), "3".match("[3]"), "3".match("*"), "3".match("[123]*"))
	printt("a".match("a"), "a".match("[abcde]"), "a".match("[a]"))

```

**Comment by AThousandShips** [comment]
It doesn't support this syntax, it says what it supports in the documentation, where did you see it mentioned it supports that?

It doesn't use a regex to do this, to do that you need to use `RegEx` instead

**Comment by sancho2** [comment]
I understand now. Please mark this as Not A Bug.
