### ISSUE TITLE
Remote Debugger: Connection failed with status 3

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#9262]
On commit a912ae57623d4b82b391fd011c233c453ce8fc61.
It could be helpful if, instead of an error code, the failure showed an error message (if that's possible).

**Comment by vnen** [comment]
Any way to reproduce this?

**Comment by Ovnuniarchos** [comment]
Run any demo on a Debian SID updated this Sunday.

**Comment by eon-s** [comment]
Debugger does not work in general in 2.1/HEAD, no remote debugger, sync scenes or anything.

**Comment by Zireael07** [comment]
It does work in 2.1.3 stable, though.

**Comment by eon-s** [comment]
@Zireael07 right, may need to be a separate issue

**Comment by eon-s** [comment]
Well, debugger seems to have been fixed today on 2.1 (tested with Ubuntu).

**Comment by Ovnuniarchos** [comment]
Tested, too on SID.

**Comment by vnen** [comment]
It works now or not?

**Comment by Ovnuniarchos** [comment]
It works.

**Comment by akien-mga** [comment]
Might be worth opening an new issue for it, the cause may be different (especially if it's a recent regression).
