### ISSUE TITLE
Console application print_rich() BBCODE color problems in windows 10

### ISSUE THREAD

**Issue by kuligs2** [godotengine/godot#92635]
### Tested versions

Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA RTX A2000 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

Hello, problem is that firstly:
```
# this works, both in editor console and godot console/cmd in windows
print_rich("[color=red] sum tex [/color]")

# this does not work, both in editor console and godot console/cmd in windows
print_rich("[color=#9837d3] sum tex [/color]")
```

Secondly weird behavior:

When you put the `[/color]` after`\n` in editor console output it prints out the thing, but in cmd console it does not.

![image](https://github.com/godotengine/godot/assets/2693224/c4add808-6ed1-4ac3-825d-5bf9f5e84c21)

### Steps to reproduce

Run the console version of the editor.
Create node scene
Add script:
```
extends Node


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	print_rich("[color=yellow]# ---------------------------------------------- \n [/color]")
	print_rich("[color=yellow]# ---------------------------------------------- [/color]\n")
	print_rich("No no\n")
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass

```
Run current scene

Look at editor output
Look at console output

![image](https://github.com/godotengine/godot/assets/2693224/a3382864-a7ed-41cb-9b52-db94c238b0bd)

### Minimal reproduction project (MRP)

See above

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87899.

This limitation is already documented in `print_rich()`'s class reference description.
