### ISSUE TITLE
C# export is broken on 4.3.beta1

### ISSUE THREAD

**Issue by cmdexecutor** [godotengine/godot#92630]
### Tested versions

-Reproducable in v4.3.beta1.official [a4f2ea91a]
-Works in v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.beta1 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M3 Max - Apple M3 Max (16 Threads)

### Issue description

Exported project with C# scripts results in runtime errors:

```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
Vulkan 1.2.275 - Forward+ - Using Device #0: Apple - Apple M3 Max

2024-06-01 16:13:07.558 test_build[18513:6954146] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
ERROR: No loader found for resource: res://GameManager.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:289)
ERROR: Can't load dependency: res://GameManager.cs.
   at: parse_variant (core/io/resource_format_binary.cpp:461)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:505)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:492)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-3070c538c03ee49b7677ff960a3f5195-main.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:282)
ERROR: Failed loading scene: res://main.tscn.
   at: start (main/main.cpp:3860)
```

But works in previous version (4.3.dev6)

### Steps to reproduce

1. Create new project
2. Add a C# script and put in on the scene
3. Export the project to test_build.app
4. Run and observe the game crashes

### Minimal reproduction project (MRP)

[broken_build_43beta1.zip](https://github.com/user-attachments/files/15521154/broken_build_43beta1.zip)

**Comment by giabao** [comment]
Same errors for Godot v4.3.beta1 - gl_compatibility on both:
+ iPhone SE (3rd generation) emulator, xcode 15.4, MacBookPro15,1 Sonoma 14.5
+ and iPhone 12 Pro Max 17.5.1

works in 4.2.2

**Comment by fuwaneko** [comment]
I got similar error for both macOS & Windows exports from macOS.

```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
Vulkan 1.3.277 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4070 SUPER

ERROR: No loader found for resource: res://level/Level.cs (expected type: Script)
   at: (core/io/resource_loader.cpp:289)
ERROR: No loader found for resource: res://enemies/Enemies.cs (expected type: Script)
   at: (core/io/resource_loader.cpp:289)
ERROR: No loader found for resource: res://enemies/EnemyData.cs (expected type: Script)
   at: (core/io/resource_loader.cpp:289)
ERROR: Can't load dependency: res://enemies/EnemyData.cs.
   at: (core/io/resource_format_binary.cpp:461)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-9cf05ca6b5ec0f125e9b3f8704f6dae4-melee.res. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:281)
ERROR: No loader found for resource: res://Player/PlayerController.cs (expected type: Script)
   at: (core/io/resource_loader.cpp:289)
ERROR: Can't load dependency: res://level/Level.cs.
   at: (core/io/resource_format_binary.cpp:461)
ERROR: Error when trying to parse Variant.
   at: (core/io/resource_format_binary.cpp:505)
ERROR: Error when trying to parse Variant.
   at: (core/io/resource_format_binary.cpp:492)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-6581cd44ca730c421bddc3302d6ce6cc-root.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:281)
ERROR: Failed loading scene: res://root.tscn.
   at: (main/main.cpp:3860)
```

```
Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org
Vulkan 1.2.275 - Forward+ - Using Device #0: Apple - Apple M2 Pro

ERROR: No loader found for resource: res://level/Level.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:289)
ERROR: No loader found for resource: res://enemies/Enemies.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:289)
ERROR: No loader found for resource: res://enemies/EnemyData.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:289)
ERROR: Can't load dependency: res://enemies/EnemyData.cs.
   at: parse_variant (core/io/resource_format_binary.cpp:461)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-9cf05ca6b5ec0f125e9b3f8704f6dae4-melee.res. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:282)
ERROR: No loader found for resource: res://Player/PlayerController.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:289)
ERROR: Can't load dependency: res://level/Level.cs.
   at: parse_variant (core/io/resource_format_binary.cpp:461)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:505)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:492)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-6581cd44ca730c421bddc3302d6ce6cc-root.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:282)
ERROR: Failed loading scene: res://root.tscn.
   at: start (main/main.cpp:3860)
```

**Comment by akien-mga** [comment]
Are you sure there you're using the "mono" build? I believe it should be listed as "v4.3.beta1.mono.official" but your version is "v4.3.beta1.official" in the logs.

**Comment by oxygen** [comment]
> Are you sure there you're using the "mono" build? I believe it should be listed as "v4.3.beta1.mono.official" but your version is "v4.3.beta1.official" in the logs.

I've used the .net download link and have the same issue.

When executing on Mac it runs all C# just fine.

Only exported to iOS it doesn't.

Same version, v4.3.beta1.official.

**Comment by akien-mga** [comment]
Thanks, I can confirm that there's something broken with the 4.3-beta1 build. The "`.mono`" part of the version string is indeed missing.

It's likely a regression from one of my recent SConstruct refactoring PRs. CC @godotengine/buildsystem

**Comment by AThousandShips** [comment]
Can confirm that it does indeed not add the mono build suffix on Windows as well

**Comment by akien-mga** [comment]
So the exports are broken because the editor downloads the wrong export templates (the non-"mono" ones) because the mono module build suffix is missing.

I tried to bisect the regression but failed so far. Initially I could reproduce the missing `.mono` suffix with a local build, but now I can't reliably anymore.

**Comment by akien-mga** [comment]
Ok I found how to reproduce the bug, one needs to build first with `module_mono_enabled=no` (default), then enable the module.

It doens't properly recreate `core/version_generated.gen.h` when it should.

It's a regression from #91624, CC @Repiteo.

Similar to #92325, though it's not a race condition here a priori, just a missing dependency. That makes me question whether the change in #91624 was correct, as it seems to have broken a chain of dependency that used to work in SCons.

**Comment by Repiteo** [comment]
I see where the problem is arising: the check to see if `core/version_generated.gen.h` needs to be recreated was using `version.py`, but that didn't account for changes in the module config. I'll change it so it instead validates against the version info value directly, something I wasn't aware I could've done at the time.
