### ISSUE TITLE
Scroll wrap in 2D editor sometimes doesn't work

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92634]
### Tested versions

4.3 beta1 broken
4.3 dev6 works

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

The cursor doesn't wrap around the edges.

https://github.com/godotengine/godot/assets/2223172/aba911fb-851c-46c1-8432-8acbc2715112

Not sure what causes it, it doesn't always happen.

### Steps to reproduce

1. Open 2D editor
2. Hold middle mouse button and move around
3. If it doesn't happen, use the editor a bit and try again later

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment]
I can't reproduce this problem @KoBeWi 

https://github.com/godotengine/godot/assets/130399274/5c9182f8-635e-4113-9f38-e58864d5796b

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

**Comment by KoBeWi** [comment]
Suddenly it's fixed, idk

**Comment by KoBeWi** [comment]
I have this issue again. Seems like it doesn't happen consistently, so I guess it's less priority. But it wasn't happening before 🤔
No idea what caused it btw.

**Comment by JekSun97** [comment]
@KoBeWi  Try to recreate this error on an empty scene, like in my video above, maybe it depends on the structure of the scene, between nodes

**Comment by KoBeWi** [comment]
It doesn't, I had this occur and not occur in the same scene. Though in each case when this happened a TileMapLayer was on the scene, idk if it's related.

**Comment by KoBeWi** [comment]
After a bit of investigation, it appears that the issue is project-specific. No idea what causes it, but it happens in any scene (even empty) in a specific project.

**Comment by KoBeWi** [comment]
It's #92304

**Comment by KoBeWi** [comment]
Reopening, because I'm still seeing it on master. It wasn't that issue in the end.

**Comment by KoBeWi** [comment]
This might be related to some more broad window input/focus issues. Aside from wrap not working, the 3D editor freelook is broken and script editor will always show caret even when the window is unfocused. I still don't know what causes it.

Broken freelook:

https://github.com/godotengine/godot/assets/2223172/7a47b56f-3c82-4e08-a0bd-8f50c0e05e4d

Mouse disappears when I right-click, but mouse movement is ignored.

Script editor bug:

https://github.com/godotengine/godot/assets/2223172/4c311025-f5a4-410e-8756-392155e03841

The caret should disappear when window is unfocused, however the editor continues to update.
