### ISSUE TITLE
Copied resources aren't duplicated anymore

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92641]
### Tested versions

4.3 beta1 broken
4.3 dev6 works

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/ae07a63f-0b74-4118-af87-1e685ab76e20

2 things to note here:
- when you copy a shape to another scene, it still references the original shape
- when you reload the original scene, the shape is reset in both scenes

Also interesting is that modifying the shape in another scene will mark the original scene as unsaved (which might come from #90531, not really a bug I think?).

### Steps to reproduce

1. Create CollisionShape2D with a shape
2. Copy the node to another scene
3. Modify the shape in another scene
4. Go back to original scene

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment]
Similarly #86525, as far as I understand, this is not a bug

**Comment by AThousandShips** [comment]
That's different, this is related to how the copying of a local resource is shared, which is a bug as it can't be shared in the file, but is incorrectly shared in the editor

**Comment by JekSun97** [comment]
So this is still a problem that has been present since version 3.x =)

**Comment by AThousandShips** [comment]
No, this is completely different and is a regression, what you're talking about isn't a bug, so please stay on topic here thank you

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/scene/main/node.cpp#L2792-L2802

Seems to be related to #91329 which caused properties to possibly not use `p_resource_remap`.

The resources are overwritten in `_duplicate_properties` after `remap_node_resources`.

**Comment by akien-mga** [comment]
CC @warriormaster12

**Comment by warriormaster12** [comment]
Could be a case of functions called in a wrong order. One moment, I’ll check.
