### ISSUE TITLE
Display turns completely black for a few seconds when gsync is enabled

### ISSUE THREAD

**Issue by bnuybunbun** [godotengine/godot#92658]
### Tested versions

- 4.2.2 (Mono)
- 4.3 Beta 1

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 SUPER (NVIDIA; 32.0.15.5585) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads) 

### Issue description

The Display turns completely black for a few seconds.

Dual Monitor:
144hz 4k (DP)
144hz 1440p (DP)

### Steps to reproduce

- It happens everytime I rapidly move my cursor
- Only when Gsync is enabled (doesn't matter if it's on enable for fullscreen or fullscreen + windowed mode)
- Problem disappeared when i set the Monitor Technology to "Fixed Refresh Rate" in the Nvidia Control Panel under "Manage 3D Settings".

### Minimal reproduction project (MRP)

Default Settings all around, completely empty project

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/86585.
