### ISSUE TITLE
Gridmap selection only follows world grid and not gridmap

### ISSUE THREAD

**Issue by sighlessm** [godotengine/godot#92655]
### Tested versions

- Reproducable in 4.2 stable, 4.3 dev6, and 4.3 beta1

### System information

Windows 11

### Issue description

I offset my gridmap so that the world origin would align with the center of a tile (the GridMap node's transform position is 1, 0, 1). However, when I shift-select, the base of the selection remains aligned with the original world grid and not the gridmap which has an offset position. 
![gridmapselectionerror](https://github.com/godotengine/godot/assets/86335202/8fc61c7d-a071-4645-a99e-899a180e3450)

### Steps to reproduce

1. Add GridMap node
2. Change transform position
3. Shift+click and drag to see the selection box and outline

### Minimal reproduction project (MRP)

[gridmap.zip](https://github.com/user-attachments/files/15522928/gridmap.zip)

**Comment by Hiiamwilliam** [comment]
Also happens in 3.x. Note that the selection box (transparent blue) works correctly. The white outline (whose position is indeed wrong) just displays the intersection between the selection box and the currently edited floor.

**Comment by akien-mga** [comment]
Fixed by #96922.
