### ISSUE TITLE
Minimum window width slightly too wide

### ISSUE THREAD

**Issue by mattblack** [godotengine/godot#92657]
### Tested versions

Present in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Fedora Linux 40 (Workstation Edition) - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (CML GT2) () - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

When I drag the Godot window to the left or right side of the screen it should snap to the left or right side of the screen.

I have a monitor 1920 pixels wide, which is a common horizontal resolution. Because Godot's minimum horizontal resolution appears to be slightly more than 1920/2=960 pixels, this doesn't work.

To resolve it would appear that Godot's minimum horizontal resolution should be 960 pixels or less.

### Steps to reproduce

-Open the main godot editor on a monitor 1920 pixels wide
-Grab the Godot main window title bar
-Drag to the right side of the screen
-Expected result: Godot editor window will snap to the right side of the screen
-Actual result: Godot editor window does not snap to the right side of the screen

### Minimal reproduction project (MRP)

No project necessary.

**Comment by Calinou** [comment]
This would require redesigning parts of the editor so it can collapse to more narrow widths without cutting off docks on the right.
