### ISSUE TITLE
godot 4.3 beta 1 mobile is rendering inversely to the screen.

### ISSUE THREAD

**Issue by Rpgdelve** [godotengine/godot#92662]
### Tested versions

4.3 beta 1

### System information

Android 10, opengl es 3.0, qualcomm snapdragon 425, Adreno  (TM) 308, 32 bits, armeabi-v7

### Issue description

When I open Godot 4.3 beta 1 the rendering window is inverted in relation to my screen. and this bug also occurs when creating games.

### Steps to reproduce

1 example: the window renders inversely to my screen.
![1 exmplo](https://github.com/godotengine/godot/assets/171452240/2ff8a443-8773-422f-9beb-a1cde0ff09c4)

2 example: when I click on the "Remover Ausente" option, the "Criar" option is selected instead.
![2 exemplo](https://github.com/godotengine/godot/assets/171452240/e3f2e4e7-9326-4b60-aa5b-789fca8a655d)
![2 exemplo 2 0](https://github.com/godotengine/godot/assets/171452240/40fc2588-05e4-4021-b0ec-69eea6f451ba)

### Minimal reproduction project (MRP)

I can't say specifically why this bug occurs.

**Comment by Calinou** [comment]
Can you reproduce this in 4.2.2?

**Comment by Rpgdelve** [comment]
> Can you reproduce this in 4.2.2?

are you asking me if this bug occurs in Godot 4.2.2? If that's the case, no, this bug only occurs in this version.

**Comment by akien-mga** [comment]
I don't reproduce the issue on a Pixel 7a, it might be a driver specific issue.

**Comment by akien-mga** [comment]
CC @Alex2782 who has access to some older Adreno devices too.

**Comment by Rpgdelve** [comment]
⁷Maybe this is the case, my cell phone is a Samsung J6+

**Comment by Rpgdelve** [comment]
But is there any possibility of this bug being fixed?

**Comment by Alex2782** [comment]
> my cell phone is a Samsung J6+.

**SM-J610F ?** _(on Amazon: Samsung SM-J610F Galaxy J6+)_

https://opengles.gpuinfo.org/
`SM-J610F` i can find there, but only Adreno 308.

-----------------

> But is there any possibility of this bug being fixed?

**Yes** (i think), 3 months ago we added some workarounds for `Adreno 3xx`, Flip-Y bug was also included. 
https://github.com/godotengine/godot/pull/87352

I have `LG Nexus 5X (Adreno 418)`, but **Arm64** (Android 8).
I'll check later if the Y-Flip bug is now reproducible with version 4.3-beta 1. (no 3 month ago)

**Comment by Alex2782** [comment]
ok `Snapdragon-425` is a `Adreno 308` [Link](https://www.qualcomm.com/products/mobile/snapdragon/smartphones/snapdragon-4-series-mobile-platforms/snapdragon-425-mobile-platform)


I have also `Nexus 7 (Adreno 320)` and there are some devices on Firebase Test Lab

**Comment by Rpgdelve** [comment]
> > my cell phone is a Samsung J6+.
> 
> **SM-J610F ?** _(on Amazon: Samsung SM-J610F Galaxy J6+)_
> 
> https://opengles.gpuinfo.org/
> `SM-J610F` i can find there, but only Adreno 308.
> 
> -----------------
> 
> > But is there any possibility of this bug being fixed?
> 
> **Yes** (i think), 3 months ago we added some workarounds for `Adreno 3xx`, Flip-Y bugfix was also included. 
> https://github.com/godotengine/godot/pull/87352
> 
> I have `LG Nexus 5X (Adreno 418)`, but **Arm64** (Android 8).
> I'll check later if the Y-Flip bug is now reproducible with version 4.3-beta 1. (no 3 month ago)
> 
> 

Yes, it's an Adreno (TM) 308; sorry for not informing you correctly.

**Comment by Alex2782** [comment]
@joined72: Which `Adreno 3xx` devices can you test again? Maybe we need to check the driver version behind the OpenGL version. 

@Rpgdelve: please try: [OrientationTest.zip](https://github.com/user-attachments/files/15526113/OrientationTest.zip)
If possible on PC via Remote Debug (USB cable) and `adb logcat -s godot`. _(If the logs are not displayed in the editor)_

<details><summary>Screenshots</summary>

---------------------

![Bildschirmfoto 2024-06-02 um 19 19 17](https://github.com/godotengine/godot/assets/41921395/b0405b2c-cfd5-4b20-b904-1c8de2b81a73)

![image](https://github.com/godotengine/godot/assets/41921395/38ba45c7-9faf-4214-a74a-d7c9a3d0ed0d)


What happens when you press `2 - REVERSE_LANDSCAPE`? 

```gdscript
func _on_button_reverse_landscape_pressed():
	DisplayServer.screen_set_orientation(DisplayServer.SCREEN_REVERSE_LANDSCAPE)
	pass # Replace with function body.
```

![image](https://github.com/godotengine/godot/assets/41921395/15428f2a-50ec-496a-b09b-f04f949805fb)


---------------------

</details>

Please try also: https://github.com/godotengine/godot/releases
- **4.2.2**-stable _(only orientation bug?)_
- **4.2.1**-stable _(no crash?)_




--------------------

I could not reproduce it, all `Adreno 3xx` devices we tested 3 months ago still need this bugfix.  

https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/drivers/gles3/rasterizer_gles3.cpp#L201



----------------
**gpuinfo:** [Nexus 7 vs. Samsung J6+](https://opengles.gpuinfo.org/compare.php?reports=4986,730)


`GL_VERSION` / `video_adapter_api_version`
- OpenGL ES 3.0 V@**127.0** AU@ (GIT@I96aee987eb) 
- OpenGL ES 3.0 V@**415.0** (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)

**Comment by Rpgdelve** [comment]
Ok, I'll check these versions.

**Comment by Rpgdelve** [comment]
**_Report Godot 4.2.2_**
**screen rendering.**
From what I see, the Godot 4.3 beta 1 bug only happens in this version. Because Godot 4.2.2 works normally. version.https://github.com/godotengine/godot/assets/171452240/dcddf9a8-4aa6-4180-84d7-93b58120f072

**compilation**
When I run Godot, the screen is also not inverted.
https://github.com/godotengine/godot/assets/171452240/6ede2f90-81d4-4792-80db-2f85d8cedb12

**bug**
There's a bug I forgot to mention: when I click to open a window, if I'm not careful, that window can end up being rendered outside of my screen.
https://github.com/godotengine/godot/assets/171452240/603b0c68-be72-42c1-b81c-5e9a9a758158
But I discovered a way to get around this problem, which was to increase the rendering screen.
**Perhaps an important detail.**
![important_information_godot_4.2.2.jpg](https://github.com/godotengine/godot/assets/171452240/5b97693f-0cfe-4ad6-8272-24f2fbb105e9)

**sorry**
Unfortunately, I don't have access to a computer and was unable to run the command to check further correctly.

**Comment by Rpgdelve** [comment]
**_Report Godot 4.2.2_**
**screen rendering.**
From what I see, the Godot 4.3 beta 1 bug only happens in this version. Because Godot 4.2.2 works normally. version.https://github.com/godotengine/godot/assets/171452240/dcddf9a8-4aa6-4180-84d7-93b58120f072

**compilation**
When I run Godot, the screen is also not inverted.
https://github.com/godotengine/godot/assets/171452240/6ede2f90-81d4-4792-80db-2f85d8cedb12

**bug**
There's a bug I forgot to mention: when I click to open a window, if I'm not careful, that window can end up being rendered outside of my screen.
https://github.com/godotengine/godot/assets/171452240/603b0c68-be72-42c1-b81c-5e9a9a758158
But I discovered a way to get around this problem, which was to increase the rendering screen.
**Perhaps an important detail.**
![important_information_godot_4.2.2.jpg](https://github.com/godotengine/godot/assets/171452240/5b97693f-0cfe-4ad6-8272-24f2fbb105e9)

**sorry**
Unfortunately, I don't have access to a computer and was unable to run the command to check further correctly.

**summary.**
For me this version is great and stable.

**Comment by Alex2782** [comment]
> Unfortunately, I don't have access to a computer and was unable to run the command to check further correctly.

Thanks, this information is also sufficient, it is identical to the information on the homepage. I'll try to create a new 'PR' in the next few days. I will deactivate `adreno_3xx_compatibility`, starting with driver version **331.0**

--------------------------

**Android 10:** https://opengles.gpuinfo.org/displayreport.php?id=4986
`OpenGL ES 3.0 V@415.0 (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)`

**Android 9:** https://opengles.gpuinfo.org/displayreport.php?id=4696
`OpenGL ES 3.0 V@331.0 (GIT@35e467f, Ice9844a736) (Date:04/15/19)`

**Comment by Rpgdelve** [comment]
> > Unfortunately, I don't have access to a computer and was unable to run the command to check further correctly.
> 
> Thanks, this information is also sufficient, it is identical to the information on the homepage. I'll try to create a new 'PR' in the next few days. I will deactivate `adreno_3xx_compatibility`, starting with driver version **331.0**
> 
> --------------------------
> 
> **Android 10:** https://opengles.gpuinfo.org/displayreport.php?id=4986
> `OpenGL ES 3.0 V@415.0 (GIT@d39f783, I79de86aa2c, 1591296226) (Date:06/04/20)`
> 
> **Android 9:** https://opengles.gpuinfo.org/displayreport.php?id=4696
> `OpenGL ES 3.0 V@331.0 (GIT@35e467f, Ice9844a736) (Date:04/15/19)`
> 
> 
> 

Thank you for your attention.

**Comment by Alex2782** [comment]
> Because Godot 4.2.2 works normally. 

@Rpgdelve could you please also test `GPUParticles`, crash?

**Godot 4.3 beta 1**  Should display an error message:`"Due to driver bugs, GPUParticles are not supported on Adreno 3XX devices. Please use CPUParticles instead."` 
https://github.com/godotengine/godot/pull/92741#discussion_r1635017424

If there is no crash on your device then we can reactivate it.

**Comment by Rpgdelve** [comment]
Okay, I'll do a test.

**Comment by Alex2782** [comment]
I tried it today, no crash but 'invisible' on Adreno 3xx and old driver
https://github.com/godotengine/godot/pull/92741#issuecomment-2166042785

**Comment by Rpgdelve** [comment]
**_Godot report 4.2.2 GPUParticles _**

**CPUParticles2D**
_Test_

After running the scene, I didn't identify any errors. The FPS seems stable.

**Observation.**

I ran all the scenes for 20 seconds.

_FPS_
![1_test_cpu_2D.jpg](https://github.com/godotengine/godot/assets/171452240/71549515-efb2-4a74-8193-79984437d9c6)

**GPUParticles2D**

_test_

It also doesn't seem to have any issues with FPS drops, but there is a bug that occurs when editing GPUParticles, but when running it doesn't occur.

_Bug_

interface.

https://github.com/godotengine/godot/assets/171452240/208b7735-7772-4b80-850e-4e90aa937c39

executed.

https://github.com/godotengine/godot/assets/171452240/805e4bd0-b4b1-4c50-b480-7aa198423ee0

_FPS_

![Test_gpu_2D.jpg](https://github.com/godotengine/godot/assets/171452240/acc5414c-0f24-4c18-b738-2d1df0781d89)

**CPUParticles3D**

_test_

I also didn't identify any bugs, but the FPS ended up dropping.

_FPS_

![Test_cpu_3D.jpg](https://github.com/godotengine/godot/assets/171452240/2aa34faa-2253-4933-b5ad-b0ce41f7f428)

**GPUParticles3D**

_test_

For some reason, GPUparticles has a bug that occurs in the layout and execution screen.

_Bug_

https://github.com/godotengine/godot/assets/171452240/558dfa79-847c-49e8-81b0-5cb9f1b5e390

**Comment by Rpgdelve** [comment]
**_report update_**

I think I discovered the cause of the bug I reported earlier. This bug was caused by the fidex FPS, which was at 30 fps. Well, when I lowered it to 10 fps, the bug stopped happening.

**GPUParticles2D**

https://github.com/godotengine/godot/assets/171452240/c3184b63-d183-4bd7-a59f-648e4f65e5ed

**GPUParticles3D**

https://github.com/godotengine/godot/assets/171452240/598a9aaa-02ba-4997-86c3-ccfe52163482
