### ISSUE TITLE
Opening any Object While Encountering any Error in The Debugger Will Crash The Editor!

### ISSUE THREAD

**Issue by jFIreW01F** [godotengine/godot#92672]
### Tested versions

Occurs In Godot  v4.3.dev6.official [89850d553] and v4.3.beta1.official [a4f2ea91a]

Other Versions are Unaffected.

### System information

Godot v4.3.beta1 - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.4032) - 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 Threads)

### Issue description

When Opening Arrays, Dictionaries or other Objects in The Debugger While In The Middle of an Error, The Editor Crashes!

### Steps to reproduce

Create an array.
Then Make an Error Occur, Simplest way to do this is with an invalid operation on the array! 'array += 1'

Upon Opening the Object In The Debugger While being in an Error State (Not a Breakpoint) The Editor Crashes.

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
I tested in 4.3.dev6, 4.3.beta1 and latest master [705b7a0b0] and i can't reproduce this issue

https://github.com/godotengine/godot/assets/44306054/5a944274-b68c-45e9-8985-adb951b07941

**Comment by akien-mga** [comment]
@jFIreW01F Could you provide a minimal reproduction project to reliably trigger the error?

**Comment by jFIreW01F** [comment]
@akien-mga Ah I Found The Problem.. I Think, It's a GDExtension Called 'Godot Gameplay Tags' mb!
