### ISSUE TITLE
Custom mouse cursors using AtlasTexture are broken in 4.3 beta1

### ISSUE THREAD

**Issue by rob-williams** [godotengine/godot#92671]
### Tested versions

- Reproducible in 4.3.beta1
- This worked fine in previous 4.3 alpha versions

### System information

MacOS Sonoma 14.4.1 - Godot v4.3.beta1 - forward_plus - vulkan

### Issue description

In previous 4.3 (and 4.2, etc) builds, I could use an AtlasTexture to set a Texture2D value to be set as a custom mouse cursor with `Input.set_custom_mouse_cursor`. This no longer works, and the entire atlas is rendered on screen as the cursor.

See the attached video showing the problem.

https://github.com/godotengine/godot/assets/2903406/8aadda38-f6e0-489e-8b77-349b26a721be

### Steps to reproduce

1. Set two exported Texture2D values using an AtlasTexture.
2. Use those Texture2D values to set the default custom mouse cursor and the pointing hand custom mouse cursor using `Input.set_custom_mouse_cursor`.
3. Run the project and see that the entire atlas is rendered as the mouse cursor, not just the texture selected within the atlas.

This picture shows the simple repro setup required:

<img width="333" alt="Screenshot 2024-06-02 at 10 40 45 AM" src="https://github.com/godotengine/godot/assets/2903406/31c58a1b-d06d-461e-894e-b8634a4600d4">

The code to reproduce is also simple:

```
extends Control

@export var default_mouse_cursor: Texture2D
@export var pointing_hand_mouse_cursor: Texture2D


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	Input.set_custom_mouse_cursor(default_mouse_cursor)
	Input.set_custom_mouse_cursor(pointing_hand_mouse_cursor, Input.CURSOR_POINTING_HAND)
```

### Minimal reproduction project (MRP)

Just run this project to see the behavior
[mouse-cursor-bug-repro.zip](https://github.com/user-attachments/files/15524072/mouse-cursor-bug-repro.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #88970 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/d1053df3-9bf0-46ff-b290-1acc0af97012)
