### ISSUE TITLE
Failed loading Mesh ressource after updating to 4.3 beta1

### ISSUE THREAD

**Issue by Nodragem** [godotengine/godot#92675]
### Tested versions

4.3 beta1 after updating from 4.3dev6

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.4626) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

After starting the attached project that contains a mesh in Godot 4.3 beta1, I get the error:
```
File 'res://assets/Can_A.mesh' can't be loaded, as it uses a format version (6) or engine version (4.3) which are not supported by your engine version (4.3).

Failed loading resource: res://assets/Can_A.mesh. Make sure resources have been imported by opening the project in the editor at least once.
```

### Steps to reproduce

Open the attached project in Godot 4.3 beta1, you will get the error.

Afte that, you can try to drag and drop the mesh in the 3d viewport in `simple3d_scene.tscn` and you will get the same error.

### Minimal reproduction project (MRP)

[testing_assets_4.3_tobeta.zip](https://github.com/user-attachments/files/15524689/testing_assets_4.3_tobeta.zip)

**Comment by matheusmdx** [comment]
In my test the inverse is happening, the MRP works without errors on beta1 but give errors on dev6

Dev6:

https://github.com/godotengine/godot/assets/44306054/101f2a3d-53c7-4044-b97d-3eb43fdf2c35


<br>

Beta1:

https://github.com/godotengine/godot/assets/44306054/222e7c24-959f-4778-918b-6aab421d468b

**Comment by akien-mga** [comment]
Indeed, what @matheusmdx described is expected behavior. 4.3-beta1 adds support for PackedVector4Array, which breaks forward compatibility for dev6 and earlier which can't read binary files with that new type.
