### ISSUE TITLE
AnimationPlayer/AnimationTree high process large framedrops

### ISSUE THREAD

**Issue by Duskitten** [godotengine/godot#92693]
### Tested versions
Confirmed by me:
- Large frame drops in any build past 4.2.x (4.3 (be56cab58c056c074d1e02cd0b38641204e39f41))
- FPS heavily inconsistent in 4.2.2/4.2.1

Confirmed by other people:
- Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.24027.1012) - Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz (16 Threads) - Large frame drops
### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.4629) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

Upon the creation of many animation players + animation trees (in this case 1024) with animation indexes, but no actual keyframes the engine proceeds to drop frames or fps becomes incredibly unstable due to high process call ms being added (goes from 16ms to 25-30ms)

### Steps to reproduce

Create a new object, put give it an AnimationPlayer + AnimationTree (keep the animation running) and animate it, but remove the actual keyframe, and duplicate it 1024 times, fps becomes unstable or process ms doubles and causes consistent framedrops.

Disabling animation playback returns to stable 60fps.

### Minimal reproduction project (MRP)

[AnimationTimer.zip](https://github.com/user-attachments/files/15526017/AnimationTimer.zip)
This simply duplicates a pre-made character 1024 times to sit in a 3D scene, with an animation with 0 keyframes running and performance begins to hurt in master branch.

Disabling animation playback returns to stable 60fps.

**Comment by Calinou** [comment]
With such an high number of animation players, you'd need SceneTree multithreading to achieve reasonable performance. However, this isn't finalized yet.

Your best bet for now is to disable animation playback for nodes that are far away, or set their process mode to Manual and step through their animation less often (e.g. once ever y2 farmes). This is a common approach in AAA games.

**Comment by Zireael07** [comment]
The manual process mode trick should be documented somewhere

**Comment by jitspoe** [comment]
Since I've been delving into performance stuff, here's a shot of Tracy profiling of animations with my fairly simple low-poly enemies in KOOK:
![image](https://github.com/godotengine/godot/assets/7751182/91557634-b28b-4507-a9b0-64d68551453c)

So the average _process_animation takes around 40 microseconds.  With 100 enemies, that's like 4ms, which isn't super great.

Here's the tracy file if anybody wants to poke around:
[kook trace 20240621.zip](https://github.com/user-attachments/files/15923065/kook.trace.20240621.zip)

Most of the time is spent in AnimationMixer:_blend_process followed by _blend_calc_total_weight.  About 20 microseconds and 9 microseconds there.

If manually stepping is the solution, it would be nice to have some sort of built in system to prioritize closer/in view objects so they update every frame and then have a max number of animations played per frame or something.

I do feel like some optimizations could be done, though, outside of that and multithreading.

**Comment by WOLFxxxxxx** [comment]
![GLEcxYwW4AA8ufD (1)](https://github.com/godotengine/godot/assets/128394802/fa45d532-c96f-4a73-bbcc-47e9875b9e53)
![GLEcGh1XkAA2-YX (1)](https://github.com/godotengine/godot/assets/128394802/10c18562-f348-41ab-8761-8387d77edac7)

Animation does not support multi-core

**Comment by Calinou** [comment]
> Animation does not support multi-core

This is expected for now, as SceneTree multithreading isn't finished yet. Work on this started in 4.1 but it's only applied to a few parts of the engine, so I don't think AnimationTree is able to work in a thread-safe manner currently.

**Comment by Saul2022** [comment]
> ![GLEcxYwW4AA8ufD (1)](https://private-user-images.githubusercontent.com/128394802/344403551-fa45d532-c96f-4a73-bbcc-47e9875b9e53.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzU3NzUsIm5iZiI6MTcxOTczNTQ3NSwicGF0aCI6Ii8xMjgzOTQ4MDIvMzQ0NDAzNTUxLWZhNDVkNTMyLWM5NmYtNGE3My1iYmNjLTQ3ZTk4NzViOWU1My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDgxNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQ4Zjg4NWNlNTJkMWY2ODY3OTJiZWNiNmQ4YmM3Y2JhOTY5ZDA3N2JlMTUwYTZkNjIyNzI1NjI2MDAzN2U4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5uUIPqQDVjl3IIQv6ytGNmoLcgtDHWvBs7nCMjB5Lwk) ![GLEcGh1XkAA2-YX (1)](https://private-user-images.githubusercontent.com/128394802/344403557-10c18562-f348-41ab-8761-8387d77edac7.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MzU3NzUsIm5iZiI6MTcxOTczNTQ3NSwicGF0aCI6Ii8xMjgzOTQ4MDIvMzQ0NDAzNTU3LTEwYzE4NTYyLWYzNDgtNDFhYi04NzYxLTgzODdkNzdlZGFjNy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMDgxNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWI1YWI4NWE2NjI0ZTMxOGJjYTRlOWE2OTc1YzNiMWIxYjEyNThkMTViZGMzMjM1NzFhMTRmYWY5NTJmZWNkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uiUyMfJEt7p14_ABGLus_RX-iboBzxmGuUiH_azmCg8)
> 
For more  performance minimize or close the editor windows as that is alos consuming fps , and also what calinou said and make the debug screen fullscreen , as they are not the same size as flax so it not quite fair as a comparison...
