### ISSUE TITLE
Faster instance placement workflow via hotkeys and mouse/key-based selecting

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#927]
I've been using Godot for several days now, and one thing I notice is that things seem to not be optimal in terms of moving and creating large numbers of instances. Basically, I would like to see a workflow that doesn't require selection from the node tree and doesn't require the use of the manipulators (though those would still be there for people that need them.

Rundown of a fast workflow (similar to what 3D programs do)
-------------------------------------------------------------

 - Left click to select an instance and it will be highlighted in the viewport, alternatively, you should be able to press 'B' to make a box selection.
 - Hotkeys for actual manipulation; 'G' for translate, 'R' for rotate, and 'S' for scale
 - Use the X,Y,Z keys to constrain manipulation to an axis, alternatively, press shift beforehand to disable an axis from being used.
 - Press 'ctrl' to enable snapping during a manipulation, if snapping is enabled, it disable it
 - selection highlighting; Could be an outline around the object in the normal view, a changed hue for the overdraw view, or a wire re-coloring in the wire view

If these things can be implemented, it will make the workflow a lot faster in general in terms of level building (especially with large numbers of instances involved). If Godot already has something like this, then I apologize in advance.

I hope others find it a good idea.

**Comment by akien-mga** [comment]
Looks like most of those are implemented and documented already, so archiving this issue. Feel free to open a new issue with more specifics about what is still missing and would have to be implemented if need be.
