### ISSUE TITLE
Button can not display

### ISSUE THREAD

**Issue by ippan** [godotengine/godot#9270]
**Operating system or device - Godot version:**
Commit [0288be1]

OS: MacOS
Display: NVIDIA GeForce GT 755M

**Issue description:**
Button can not display after update to commit [0288be1]
it can display on commit [969fa3c]
![button](https://user-images.githubusercontent.com/2070604/27290405-b6148afa-553f-11e7-8683-e39f7e42182a.png)

**Comment by reduz** [comment]
eck, seems i screwed this up. I'm rewriting how ninepatch textures are
drawn currently, so hope this is fixed today or tomorrow

**Comment by akien-mga** [comment]
Fixed (presumably by f27d2a3).
