### ISSUE TITLE
Parallax2D's Sprite2D child stops rendering while scaled and zoomed on

### ISSUE THREAD

**Issue by paflya** [godotengine/godot#92705]
### Tested versions

- Reproductive in: 4.3 beta 1

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.5176) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

The `Sprite2D` node stops rendering in the scene in Editor/in Game while being a child to `Parallax2D` node under these conditions:
* `Parallax2D`'s `repeat_times` property is more than 1 
* `Parallax2D`'s `repeat_size` is big enough to make children spaced out from each other
* Childs `Sprite2D` `scale` property under `Node2D` is bigger than 2 (in my tests around 2,5 - 3) 

While all of these apply, zooming to the origin of `Sprite2D` will result in it not rendering. That happens on less levels of zoom when the `repeat_time` in `Parallax2D` is bigger. Propably has something to do with all repetitions not in view.
Oddly enough, zooming to the edges of repetition will be okay.  

### Steps to reproduce

Included minimal reproduction project. Also includind the [video](https://github.com/godotengine/godot/assets/98214439/2393e301-ba36-47cd-a973-4936e2335180) of the problem captured in MRP.

To reproduce the problem:
1. Open the project or/ recreate the conditions described in the issue description.
2. Zoom in on the `Sprite2D` origin

### Minimal reproduction project (MRP)

[parallax2d-mrp.zip](https://github.com/user-attachments/files/15526763/parallax2d-mrp.zip)

**Comment by markdibarry** [comment]
I just checked the MRP, and it does look to be an issue with culling specifically with the repeat times setting, though weirdly I don't recall it doing this when it was originally merged, so I'll have to see if something has changed since then. On the bright side, all the cases in the MRP seem to be scenarios that wouldn't be used in an actual parallax scene, but I'd still like to investigate and get it fixed.

**Comment by markdibarry** [comment]
Figured it out! It was totally a mistake on my part. I forgot to take scale into consideration with the positioning when increasing the repeat times *only* with the culling. Fun fact: you can see the canvas cull boundaries if you put your canvas item in a `CanvasGroup` and add a shader to make all transparent areas a different color! The bounds were positioned wrong so the items would seemingly disappear at random zoom levels or scrolling. You can see it in play here:

https://github.com/godotengine/godot/assets/21325943/24800173-3ff5-4b18-83bf-02db4fed38bb

"Goodbye, my icon people need me..."

Here it is after the fix:

https://github.com/godotengine/godot/assets/21325943/eb20531e-774c-4f37-9078-b5fd86bde18a

I'll make a PR today. Thanks again for the catch!
