### ISSUE TITLE
GPUParticle2D jitter, while rotating the Parent, when Physics Interpolation is true  Godot 4.3 beta 1 

### ISSUE THREAD

**Issue by Silvanuz** [godotengine/godot#92700]
### Tested versions

 Godot 4.3 beta 1 

### System information

Windows 10 -  NVIDIA GeForce RTX 4060

### Issue description

With Physics Interpolation TRUE: 
If you add GPUParticle2D to a Parent and rotate that Parent, the Particles jitter.

It works fine when you turn off the Physics Interpolation

https://github.com/godotengine/godot/assets/36472149/2f782532-bb3a-487b-b53f-0edbbed31337

### Steps to reproduce

1. Make 2DScene
2. Add the Godot Icon as Sprite2D
3. Add GPUParticle2D as a child from the Godot Icon
4. Set the Process Material of this GPUParticle2D to a new ParticleProcessMaterial
5. In the ParticleProcessMaterial > Spawn > Position > Emissionshape = Sphere AND Emission sphere Radius = 138
6. Add a script for the Sprite2D
7.  in func_process > look_at(get_global_mouse_position())

### Minimal reproduction project (MRP)

[Project.zip](https://github.com/user-attachments/files/15526511/Project.zip)

**Comment by JekSun97** [comment]
I confirm that this problem exists

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92006.
