### ISSUE TITLE
Editor Tooltip has transparency background with transparent font color.

### ISSUE THREAD

**Issue by hydescarf** [godotengine/godot#92712]
### Tested versions

- Reproducible: v4.3.dev6, v4.3.beta1
- Non-reproducible: v4.2, v4.3.dev1, v4.3.dev4, v4.3.dev5

### System information

Godot v4.3.beta1 - Windows 10.0.22631 (Windows 11) - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3734) - 12th Gen Intel(R) Core(TM) i5-12400 (12 Threads)

### Issue description

Tooltip has color issue, but I was not able to identify the problem through Editor Theming.
Removing Godot folders from AppData (Local & Roaming) does not fix the problem.
On the other hand, my old laptop runs v4.3.dev6 without issues. I suspect this to be related to system components (GPU?)
Old laptop specs:
- `Windows 10.0.19045 - GLES3 (Compatibility) - GeForce 820M () - Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 Threads)`

### Steps to reproduce

1. Fresh install of Godot v4.3.dev6 / beta1, with related folders in AppData deleted.
2. Hover to icons and stuff to pop up the tooltip.

During dark mode, background is transparency.
![image](https://github.com/godotengine/godot/assets/56707567/14d1fd39-8aa1-4b65-983a-b0a542994424)
During light mode, text is fully transparent.
![image](https://github.com/godotengine/godot/assets/56707567/e7985f58-e54e-405f-a5c3-fef3964ec2be)

Compare to previous versions ~v4.3.dev5 (working normal colors):
![image](https://github.com/godotengine/godot/assets/56707567/5929b8b1-cd1c-41ba-9a40-2f1318d5d74e)
![image](https://github.com/godotengine/godot/assets/56707567/2097adc6-60f2-4704-9126-4d4d664697f2)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
I can't confirm on Windows 10 with Compatibility or Forward+, so this seems like it'd be hardware specific

**Comment by Calinou** [comment]
It looks like tooltips are using window transparency now (which is a good thing, so their rounded corners can actually be seen). However, premultiplied alpha is used for window transparency in 4.x. This means that transparent black is invisible, but transparent white is visible as pure additive white. See https://github.com/godotengine/godot/issues/83939.

**Comment by hydescarf** [comment]
Update:
In case if anyone needs a temporary solution:
After exploring https://github.com/godotengine/godot/issues/94189#issuecomment-2221704190 and https://github.com/godotengine/godot/issues/94615#issuecomment-2243021688, enabling `Single Window Mode` fixed the issue, but that also means multi-window mode cannot be used at the meantime.

**Comment by akien-mga** [comment]
I can't reproduce the issue on Linux (AMD GPU) with either Compatibility or Forward+ renderers:

![image](https://github.com/user-attachments/assets/5ffb3f88-cbca-4071-baf1-1e35d850cce8)

Might be Windows specific, CC @bruvzg.

**Comment by hydescarf** [comment]
Further testings:
- Enabling `Single Window Mode (SWM)` fixes the issue on beta-1 & rc-1.
- If you have **only one** monitor, regardless of the SWM and the above version differences, tooltips are never in transparency.
- If you have **two** monitors, issue persists as usual if SWM is not enabled. (Extra: the tooltips sometimes show up for 0.1s and disappear)

**Comment by kitbdev** [comment]
I can reproduce.
Godot v4.3.dev6.official [89850d553] and v4.3.rc (3978628c6) - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)
Only happens on Compatibility.
Single window mode must not be enabled. It happens even if there is only one monitor.

Likely caused by this line from #86553 when the popup window is made:

https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/main/viewport.cpp#L1486-L1487

![image](https://github.com/user-attachments/assets/12a524ac-c286-439e-b31e-c9f39ca14336)

**Comment by akien-mga** [comment]
It's not clear to me why this was added in that PR, but ai think we could revert that flag change.
