### ISSUE TITLE
Duplicating menu items in the FBX import menu

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#92710]
### Tested versions

This happens since version 4.3 dev4+, 4.3 beta1

### System information

Godot v4.3.dev4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When we select any FBX file in the file manager, the menu presets are duplicated in the import tab.
This only happens with FBX files, there is no such problem with GLTF/GLB.
![import](https://github.com/godotengine/godot/assets/130399274/7cae7c9b-1499-4a10-97cd-93ca39880f56)

### Steps to reproduce

Move any fbx file to the project, select the import tab, click on the button with presets

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This has not been completed yet as the PR is not merged, it should be kept open until it's fixed
