### ISSUE TITLE
Poor animation performance

### ISSUE THREAD

**Issue by WOLFxxxxxx** [godotengine/godot#92724]
### Tested versions

4.3

### System information

Windows 10

### Issue description

The animation performance is very bad. The rest of the engines are 5 times better in performance
Please do well 🤕
![1](https://github.com/godotengine/godot/assets/128394802/9f9b2adb-6f31-45fb-903b-b0cd6bdaf5cc)
![324183392-8c49c03c-e34a-472a-963f-08cf6431a0e0](https://github.com/godotengine/godot/assets/128394802/25c27b5d-223a-4c4e-ad9e-ded796d1b941)

### Steps to reproduce

Q

### Minimal reproduction project (MRP)

[anm.zip](https://github.com/user-attachments/files/15533350/anm.zip)

**Comment by AThousandShips** [comment]
You already reported exactly this before:
* https://github.com/godotengine/godot/issues/90943

Why did you open a new report?

**Comment by WOLFxxxxxx** [comment]
I added a ZIP project

**Comment by AThousandShips** [comment]
That should have been added to the original instead, but I don't think this changes anything, there was already an explanation there in the original

**Comment by WOLFxxxxxx** [comment]
My game development depends on animation optimization

**Comment by AThousandShips** [comment]
Yes, that's understood, but the cause of this issue was already explained in the original issue report, see the comment I linked, is that not relevant? If so then please explain how it is different from that

**Comment by AThousandShips** [comment]
That's okay, please use translation software or have someone help you, but it doesn't help if you ignore the things people tell you

**Comment by WOLFxxxxxx** [comment]
The old report was stopped without solving the problem 

You open a new report

**Comment by AThousandShips** [comment]
> The old report was stopped without solving the problem

No, the explanation was given, please read this https://github.com/godotengine/godot/issues/90943#issuecomment-2067741724

You don't open a new report just because the answer wasn't what you wanted

**Comment by WOLFxxxxxx** [comment]
Thank you for your help so I can repeat this plan again

**Comment by JekSun97** [comment]
@WOLFxxxxxx  There is no doubt that godot skeletal animation is not the most productive, but it also depends on your equipment, my FPS is stable
![anmp](https://github.com/godotengine/godot/assets/130399274/14e7e081-e318-4f50-b91f-07f9ed86c85f)

**Comment by JekSun97** [comment]
I doubled the number of skeletons for a total of 200 skeletons and the fps remained stable
![anmp2](https://github.com/godotengine/godot/assets/130399274/88cb3302-65ac-496e-a24f-446f93c59e54)

**Comment by JekSun97** [comment]
@AThousandShips I noticed an error in the console when duplicating a scene with a skeleton, should I open an error about this?
![err](https://github.com/godotengine/godot/assets/130399274/0e405180-5832-4247-a007-4892f462684f)

**Comment by AThousandShips** [comment]
That's a reported case already I think, related to instanced scenes, search for it and see

**Comment by WOLFxxxxxx** [comment]
![Capture](https://github.com/godotengine/godot/assets/128394802/ff6ffaf2-f515-4e6d-aa29-0bc475c46713)
![2](https://github.com/godotengine/godot/assets/128394802/77c31335-5b49-4824-9f0c-4ce693a8172b)
The problem is with the CPU

**Comment by WOLFxxxxxx** [comment]
There is a bottleneck

gpu 18%
cpu 31%

fps 15 - 30 ?????

**Comment by AThousandShips** [comment]
Yes, that's what you were told in the original issue report, and you were told how to go forward with that

**Comment by WOLFxxxxxx** [comment]
https://guillaumeblanc.github.io/ozz-animation/samples/multithread/

![33](https://github.com/godotengine/godot/assets/128394802/c3b6ad2a-9942-4cd3-89ae-148cbead03d0)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/92693, which is more detailed and actionable.
