### ISSUE TITLE
Unloading plugin results into crash on `macOS` and `Linux` at Godot exit

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#92727]
### Tested versions

v4.2.2.stable.official [15073afe3] macOS

### System information

macOS  Sonoma 14.1.1

### Issue description

My plugin is crashing at Godot exit on macOS and Linux, it works without any issues on Windows and Linux systems.

There is an issue when using `free` at `__exit_tree` inside the `EditorPlugin`, using `queue_free` helps but ends up with a lot of orphan resources at exit, so I prefer to use `free`.
Using `queue_free` with afterward `await get_tree().process_frame` do also crash in my plugin.

### Steps to reproduce

Use the attached example project (a strictly reduced version of my plugin, includes only the inspector)
- start Godot do enable it
- exit
sometimes the Godot editor is hangs and needs manually to kill, sometimes it ends with signal 11

### Minimal reproduction project (MRP)

[plugin_free.zip](https://github.com/user-attachments/files/15536109/plugin_free.zip)

**Comment by coppolaemilio** [comment]
After consulting on the issue, it appears that the problem lies with the plugin cleanup logic, not an engine bug. The plugin attempts to remove a node from the tree and free control in `_exit_tree` while the scene tree is in the process of being deleted. This causes the `remove` call to fail with a "Parent node is busy adding/removing children" error, and the `free` call to delete a node that is still referenced in the scene tree.

The entire cleanup logic should be moved to `_disable_plugin` (to remove the dock when the plugin is disabled from the settings). There's no need to call this from `_exit_tree` since it's part of the tree and will be deleted recursively with it.

If you think something else should be done feel free to comment and I can reopen the issue. Thanks!

**Comment by MikeSchulze** [comment]
> The entire cleanup logic should be moved to `_disable_plugin` (to remove the dock when the plugin is disabled from the settings). There's no need to call this from `_exit_tree` since it's part of the tree and will be deleted recursively with it.

@coppolaemilio That not work because `_disable_plugin ` is never called when closing the editor.
So I have to use `_exit_tree ` this is a bug, please reopen this issue

**Comment by bruvzg** [comment]
> So I have to use _exit_tree this is a bug, please reopen this issue

Why are you trying to free it? There's no reason to free any of the plugin nodes from `_exit_tree` at all, nodes are part of the editor scene tree and will be freed automatically.

**Comment by MikeSchulze** [comment]
> > So I have to use _exit_tree this is a bug, please reopen this issue
> 
> Why are you trying to free it? There's no reason to free any of the plugin nodes from `_exit_tree` at all, nodes are part of the editor scene tree and will be freed automatically.

From the plugin documentation, it is recommended.
https://docs.godotengine.org/de/4.x/tutorials/plugins/editor/making_plugins.html
![image](https://github.com/godotengine/godot/assets/347037/5e16b972-6a31-4fd4-a521-bd9d96813e73)


And if I'm not freeing the resource, the Editor closes with a lot of memory leaks.

**Comment by bruvzg** [comment]
For custom resources yes, but it should not be necessary for nodes.

I guess if it's documented like this we probably shouldn't add an extra step to unload all plugins before quitting the editor. I'll take another look.

**Comment by MikeSchulze** [comment]
> For custom resources yes, but it should not be necessary for nodes.

From the example, this is a scene added to a dock, and I guessing it is a Control Node.
>I guess if it's documented like this we probably shouldn't add an extra step to unload all plugins before quitting the editor. I'll take another look.

Yes, thanks please check this

**Comment by bruvzg** [comment]
> And if I'm not freeing the resource, the Editor closes with a lot of memory leaks.

I can't reproduce any leaks when node removal is missing (at least with MRP).

> I'll take another look.

Opened PR that should fix it - https://github.com/godotengine/godot/pull/93238, will fully test it tomorrow.

**Comment by MikeSchulze** [comment]
# update
I was able to fix now my segmentation faults and memory leaks at exit, it works for Windows and macOS, Linux needs still to be tested.
