### ISSUE TITLE
FileDialog in Open Folder mode prevents from selecting anything (folders and files) on Linux Mint

### ISSUE THREAD

**Issue by Hokome** [godotengine/godot#92754]
### Tested versions

- v4.2.2.stable.mono.official [15073afe3]

### System information

Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 5500M (RADV NAVI14) () - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

When using the FileDialog node in "Open folder" mode, it greys out everything in the dialog. I cannot select folders or files. I can still use the sidebar to access Documents, Videos etc. I can still create a new folder and it'll automatically go inside, but I cannot select or manually edit the path.

![image](https://github.com/godotengine/godot/assets/44882056/bab51eed-942b-4237-8186-cec1be88a794)

### Steps to reproduce

- Use Linux Mint (probably)
- Create FileDialog node
- Set File Mode to "Open Folder"
- Set Use Native Dialog to true
- Set Access to "File System"
- Make it pop up in script

### Minimal reproduction project (MRP)

[BugProject.tar.gz](https://github.com/user-attachments/files/15550444/BugProject.tar.gz)
Not ZIP because it's likely a Linux only problem

**Comment by JonShard** [comment]
I'm experiencing the same issue on Ubuntu 22.
The same code to open the dialog works on my Macbook Air 2020 running Sonoma.
Switching to use Godot's built-in File Dialog works, but it's not nearly as good as the OS's native version.

**Comment by Piotr-Wieczorek** [comment]
Still is an issue with Linux Mint 22 (Wilma)

**Comment by akien-mga** [comment]
Fixed by #96203.
