### ISSUE TITLE
Visual shader nodes are not deleted with hotkey

### ISSUE THREAD

**Issue by Nordsoft91** [godotengine/godot#92776]
### Tested versions

Godot v4.2.2.stable

### System information

macOS 12.6.7 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

Graph nodes cannot be deleted with hotkey in visual shader editor. Once delete key is pressed, deletion for scene node is triggered. This behavior is noticed for custom GraphEdit/GraphNode too.

### Steps to reproduce

1. Create new resource -> visual shader
2. Open visual shader editor
3. Create any node
4. Select node created
5. Press delete (Cmd+Backspace)

Expected: graph node is deleted
Actual: pop-up window about deletion of scene node appears

### Minimal reproduction project (MRP)

Empty project

**Comment by Calinou** [comment]
This is due to one of two reasons:

- An input focus issue where the visual shader editor is missing a shortcut context.
- The shortcut for deleting GraphNodes on macOS isn't set to <kbd>Cmd + Delete</kbd>, so it mismatches the Delete Node shortcut and doesn't override it accordingly.

**Comment by Nordsoft91** [comment]
Both tested:
- other shortcuts, like copy-paste work fine
- I added explicitly cmd+backspace into project settings ui_graph_delete and it still doesn't work

**Comment by rllyy97** [comment]
I'm not sure the cut nodes pr (#97229) fixed this issue, I'm still able to reproduce the original issue in 4.7.1, can't delete visual shader editor nodes via keyboard commands
