### ISSUE TITLE
Compatibility Renderer: Environment's reflected_light_source property does not display light properly on "Disabled" if it is not set to "Background" or "Sky" modes beforehand.

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#92779]
### Tested versions

Godot v4.3.beta1 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### Issue description

Environment has a property called "reflected_light_source" which accepts an enum value with the following values:
![image](https://github.com/godotengine/godot/assets/40964335/f779ee49-1dc7-492d-8b30-8484104394cf)
I'm going to set these values in editor, then run the project, and show the results:
![image](https://github.com/godotengine/godot/assets/40964335/da04886a-21a8-4688-aadb-48bd4f6a8d8a)
![image](https://github.com/godotengine/godot/assets/40964335/579a0b5d-42fa-4901-85fc-ca91e4afeb60)
![image](https://github.com/godotengine/godot/assets/40964335/dc66d1eb-7b3b-40c0-88a7-c86cf2c7de63)
![image](https://github.com/godotengine/godot/assets/40964335/4229021b-e84c-440d-aee3-95c301a049c1)
![image](https://github.com/godotengine/godot/assets/40964335/14b624c6-5bc6-4219-8225-3083792eb045)
![image](https://github.com/godotengine/godot/assets/40964335/10d94699-b7e1-41e5-beda-4ea8f40a8a00)

As you can see, when you set the backround to disabled in the editor, it totally breaks the light and makes the shadows totally dark.
But this isn't the case if you have set the value to REFLECTION_SOURCE_BG or REFLECTION_SOURCE_SKY, and THEN it displays properly.
![firefox_GnjVFeAqnc](https://github.com/godotengine/godot/assets/40964335/ebaf3061-d047-4b14-926c-9434961ef38c)
As you can see here, it started out with broken lighting on "REFLECTION_SOURCE_DISABLED". But when I switched it to the other modes, then switched it back, it displayed as it correctly should.

### Steps to reproduce

1. Make an environment.
2. Set the environment reflected_light_source property to ReflectionSource::REFLECTION_SOURCE_DISABLED 
3. Start the project
4. Observe that the lighting is broken
5. set reflected_light_source to any of the other enum values
6. set reflected_light_source back to ReflectionSource::REFLECTION_SOURCE_DISABLED 
7. Observe that the lighting in this mode now displays as it should

### Minimal reproduction project (MRP)

[New Compressed (zipped) Folder.zip](https://github.com/user-attachments/files/15572675/New.Compressed.zipped.Folder.zip)

**Comment by FireCatMagic** [comment]
Update: it also do this if you start the editor with the node already in "ReflectionSource::REFLECTION_SOURCE_DISABLED", then you have to do the same thing to make it display properly in editor

**Comment by Calinou** [comment]
Does this occur in Forward+ or Mobile as well?

**Comment by FireCatMagic** [comment]
> Does this occur in Forward+ or Mobile as well?

Nope, only compatibility.
