### ISSUE TITLE
Script-Created Bones Can't Be Found

### ISSUE THREAD

**Issue by Fire551** [godotengine/godot#92771]
### Tested versions

Tested in 4.2 and 4.3 snapshots

### System information

Windows 10 - Godot 4.2

### Issue description

![image](https://github.com/godotengine/godot/assets/52729867/8adff247-8d2d-43cc-afdb-2448058aee2c)

every single bone made through script cannot be found. 
animation mixer cant find a track matching it. when it uses the exact same name 
node finder cant find it through the skeleton

skeleton doesn't play animation either.

im encountering this issue because im making an armor-core mech builder. it copys data from 4 different skeletons and merges it into one. names are kept nice and compatible through a bonemap.
i do see a few hypothetical issues, but i want to actually get through the saloon-door before i get to that bar fight.
my model isn't skinning correctly through the code too, but thats a tad off topic. and likely a modelling error.

### Steps to reproduce

- have animation using bone with specific name
- use add_bone() with exact same specific name
- watch your hopes and dreams burn.

### Minimal reproduction project (MRP)

[ProceduralAnimationError.zip](https://github.com/user-attachments/files/15569646/ProceduralAnimationError.zip)

**Comment by Fire551** [comment]
https://github.com/godotengine/godot/issues/39213#issuecomment-1826779241

the last sent message seems to have stumbled on the same issue as me, however-
![image](https://github.com/godotengine/godot/assets/52729867/f4a55bab-1677-4f7e-b23e-f4e2a8bd5e49)
it seems they named their nodes incorrectly, which could cause their issues.

**Comment by TokageItLab** [comment]
The thing to remember about them is that mixing unique and non-unique paths can cause problems because they are considered to be different track paths when caching animations.

As a result, is the right essence of the issue “there is a problem when specifying a unique path for a packed scene on the Animation trackpath” or "is there a problem with the unique path regardless of the packed scene"?

**Comment by Fire551** [comment]
neither seem to be the issue, it was just me not fully understanding the unique name :/ was right there too.
and because all the animations come from the same place i shouldn't have issues with differing tracks.
issue seems to be closed, better be ready for godot armorcore, thanks alot for the help!
