### ISSUE TITLE
Anchoring Control nodes doesn't take scale into account

### ISSUE THREAD

**Issue by popcar2** [godotengine/godot#92786]
### Tested versions

- Reproducible in 4.3beta1, 4.2.2 stable

### System information

Godot v4.2.2.stable - Nobara Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU () - AMD Ryzen 7 7735HS with Radeon Graphics (16 Threads)

### Issue description

Choosing an anchor preset doesn't take the Control's scale into account. Trying to center a Panel with a scale of 5 to the left for example causes a huge offset. Scaling a panel then trying to center it via anchors causes a huge offset for example. It should instead take scale into account and try centering it properly. 

![Screenshot_24_06_05_2](https://github.com/godotengine/godot/assets/16920817/bf425075-aca1-4f63-a9f6-a5bb66045453)

I know scaling Controls isn't good practice but there are some situations where it would be useful to do so, like scaling up 9 patch rects so their borders are larger.

### Steps to reproduce

1. Scale a control node
2. Try anchoring it
3. See unexpected results

### Minimal reproduction project (MRP)

[TestAnchor.zip](https://github.com/user-attachments/files/15585190/TestAnchor.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/19068

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
