### ISSUE TITLE
Text in drop-down menu next to tabs is blank

### ISSUE THREAD

**Issue by jfrederickson** [godotengine/godot#9278]
**Operating system or device - Godot version:**

Debian 9 - Godot v2.1.3.stable.official

**Issue description:**
When I click the arrow next to a tab in the editor, I get a drop-down menu with a few boxes in it, but no text - it's very unclear what these options will do.

![screenshot_2017-06-19_18-33-45](https://user-images.githubusercontent.com/1923178/27308747-539b869c-551e-11e7-8beb-9606a514ee06.png)

This is the full console log from an editor instance in which this problem appeared:

```
jon@terralibre:~$ godot
WARNING: initialize: Could not find cursor theme
   At: platform/x11/os_x11.cpp:346.
OPENING: /home/jon/sources/godot-demo-projects/2d/platformer (::home::jon::sources::godot-demo-projects::2d::platformer)
WARNING: initialize: Could not find cursor theme
   At: platform/x11/os_x11.cpp:346.
jon@terralibre:~$ WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:66.
```

**Steps to reproduce:**

Download and run Godot v2.1.3.stable.official on a Debian 9 system. (Unfortunately this is the only such system I have available at the moment, so I don't know if this is universal.)

**Comment by karroffel** [comment]
This is for the placement of the current dock.

The gray boxes are the possible dock positions inside the editor.

The white small line above the one gray box indicates *the current dock* you're looking at.

If you click on of the other gray boxes the dock will move to that place. Also if there is more than one dock in one docking position you can set the order using the small arrows on the top.

------

I can see how that can be confusing as there is no indicator to what it's actually doing, but if you were to just press it you'd immediately see what it does.

I guess a small and subtle hint to what it does would be awesome though!

**Comment by jfrederickson** [comment]
Ah! Now that I play around with it some more I can see what's going on, but yeah - a label would be helpful.

**Comment by AlexHolly** [comment]
Maybe something like this?

![image](https://user-images.githubusercontent.com/4741886/31853906-213ba91e-b691-11e7-871f-35a20e77ff0d.png)
