### ISSUE TITLE
Error "Can't remove open menu!" when closing and opening scenes in editor on macOS

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#92789]
### Tested versions

- Reproducible in 4.3dev5, 4.3dev6, 4.3beta1
- Not reproducible 4.3dev4

### System information

Godot v4.3.beta1 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

When opening or closing scenes (using middle mouse button or the close-button on the scene tabs) I after a while  consistently get the following error in the console:
`Can't remove open menu!`

The error doesn't appear the first time you open or close a scene, but once it has started appearing it will appear every time you open or close a scene, seemingly regardless of what scene it is.

The error seems related to the macOS native menus and is thrown here:
https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/platform/macos/native_menu_macos.mm#L1093
So I'm guessing that something is going wrong at some point closing a scene making the editor think some menu is open somewhere that it's trying to close when then subsequently switching scenes? 

### Steps to reproduce

In my testing to reproduce this I've not managed to 100% isolate what causes the error to start appearing, but it never appears the first time you open a scene. However, in any test project I've tested it on it always starts appearing after opening more than one scene closing and then re-opening some of them again.

### Minimal reproduction project (MRP)

I've been able to reproduce this with scenes in any project I've tried it on. But here's a simple project with two scenes for reproducing a different bug. But it also works for this issue, just open and close the parent.tscn and child.tscn scenes a couple of times and the error shows up for me. 
[test project.zip](https://github.com/user-attachments/files/15585645/export-overrid-test.zip)

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/92781
