### ISSUE TITLE
Godot 4.3 C#/Mono build on Linux comes without the necessary mono descriptor and therefore wants the wrong export template

### ISSUE THREAD

**Issue by blubberdiblub** [godotengine/godot#92791]
### Tested versions

* Godot v4.3.beta1.official (Mono build) [a4f2ea91a]

### System information

Ubuntu 24.04 LTS 24.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 950M (nvidia; 555.42.02) - Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 Threads)

### Issue description

The Mono build on Linux comes without the mono descriptor (Godot v4.2.2 does have it) and therefore it wants the wrong export template (the one not intended for the Mono build)

And yes, I'm sure chose the correct download. I verified. The build also takes attached C# scripts fine, so it appears to be the correct one.

![godot_4_3_mono_without_mono_descriptor_1](https://github.com/godotengine/godot/assets/69097/b0b1e96a-ca60-408e-a368-918d4912fad1)

![godot_4_3_mono_without_mono_descriptor_2](https://github.com/godotengine/godot/assets/69097/46f28281-3890-4ed0-a91d-c38f5f172291)

### Steps to reproduce

* Download https://github.com/godotengine/godot-builds/releases/download/4.3-beta1/Godot_v4.3-beta1_mono_linux_x86_64.zip
* (optionally) Download https://github.com/godotengine/godot-builds/releases/download/4.3-beta1/Godot_v4.3-beta1_mono_export_templates.tpz

* Unpack the Godot archive
* Start the unpacked Godot
* go into a project (new or otherwise)
* check `Help` -> `About Godot ...` or the lower right corner and see that it's missing the `mono` tag/descriptor (that the Godot v4.2.2 Mono build did have)

* go to `Editor` -> `Manage Export Templates ...`

If you downloaded the export templates earlier:
* install the downloaded export template
* see that actually wants the non-mono template rather than the installed mono template

Or if you didn't download the export template earlier:
* click on `Download and Install`
* see that it installs the non-mono template rather than the mono enabled one

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This has already been solved (and is a pinned issue):
* https://github.com/godotengine/godot/issues/92630

**Comment by blubberdiblub** [comment]
Oh, I see, sorry for the noise. I didn't even know Github has pinned issues, so I went to the issues tab with "Banner blindness", if you know what I mean.

Thanks for mentioning it, good to know.

**Comment by AThousandShips** [comment]
It's also helpful to search before opening an issue, including closed ones

**Comment by blubberdiblub** [comment]
Well, yeah, I can see them clearly **now**, thanks to you making me aware of their existence.
And yes, I should have included closed issues in my search. Will do better in the future.
