### ISSUE TITLE
Run project opens window always at the center of the main screen

### ISSUE THREAD

**Issue by reimgrab** [godotengine/godot#92794]
### Tested versions

Reproducible in 4.2.2.stable
Not reproducible in 3.x

### System information

Godot v4.2.2.stable.mono - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.171.04) - Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 Threads)

### Issue description

As title says, no matter what I try, I cannot change the initial window position when running a project from the editor.
I would like to run my projects fullscreen on my second monitor like I did in 3.x but I cannot even change the window position on my main screen.
-Center of other screen does nothing
-Initial screen set to 1 does nothing
-Absolute with any position does nothing

### Steps to reproduce

-open any project
-change Initial Position Type to center of other screen or absolute with any value or set Initial Screen to 1
-run the project it will start in the center of the main screen

### Minimal reproduction project (MRP)

any project

**Comment by AThousandShips** [comment]
You need to use the editor setting, the project setting affects the exported project, use `run/window_placement` settings

**Comment by reimgrab** [comment]
Sorry, for being stupid

**Comment by AThousandShips** [comment]
No worries, can be hard to find
