### ISSUE TITLE
Error 'canvas_item_add_polygon: Condition "pointcount < 3" is true.' caused by TextureProgressBar with clockwise mode

### ISSUE THREAD

**Issue by KUEII** [godotengine/godot#92790]
### Tested versions

-Reproducible in: 4.2.stable [46dc27791]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

When setting a very small value(small ratio compare to max_value) to TextureProgressBar with clockwise mode and a step of 0,
Godot will throw the error 'canvas_item_add_polygon: Condition "pointcount < 3" is true.' from RenderServer.
![image](https://github.com/godotengine/godot/assets/49547609/83dbe24a-319c-4d42-a702-aab82176ef8c)
I have tried counter-clockwise and the other modes, but only clockwise mode has this issue.

### Steps to reproduce

1. Create a scene.
2. Add TextureProgressBar as child.
3. Set texture_progress as any texture.
4. Set max_value to 3.
5. Set step to 0.
6. Write a script to set the value of TextureProgressBar as `0.000000005`

### Minimal reproduction project (MRP)

[Test.zip](https://github.com/user-attachments/files/15585891/Test.zip)

**Comment by AThousandShips** [comment]
Please try 4.2.2, to make sure this isn't already solved

**Comment by KUEII** [comment]
Still reproducible with v4.2.2.stable.official.15073afe3.
