### ISSUE TITLE
[Regression] Editor gets stuck when opening Sprite2D uv dialog

### ISSUE THREAD

**Issue by beicause** [godotengine/godot#92807]
### Tested versions

Reproducible since 241d45d063060cfddf77093d2cf0aad087118e35, related to https://github.com/godotengine/godot/pull/92731

### System information

Linux Mint 21.3 (Virginia) - X11 - Vulkan (Mobile) - integrated AMD Unknown (RADV RENOIR) () - AMD Ryzen 7 4800U with Radeon Graphics (16 Threads)

### Issue description

Godot editor gets stuck ( seems infinite loop ) when opening Sprite2D uv dialog.

### Steps to reproduce

1. Add a Sprite2D to scene and attach a texture to it ( e.g. icon.svg ).
2. Click any of the following options:
![2024-06-06 01-26-54屏幕截图](https://github.com/godotengine/godot/assets/75941842/fe82e9b7-31ce-4f4b-8b77-40f78cf51102)

3. Then editor is stuck.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92804, as this is due to the same cause.
