### ISSUE TITLE
Opening color picker or Sprite2D UV dialog hangs the editor

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#92804]
### Tested versions

I bisected it, first affected commit is 9fb96609122471e50a07478bd37b17d7c4482284.

### System information

Windows 11, local dev build from master

### Issue description

When I open a color picker anywhere in the editor, the editor hangs and has to be closed by force.

### Steps to reproduce

Open a project in the editor and try to select a color anywhere using the color picker. I tested the inspector and project settings and both reproduce this.

### Minimal reproduction project (MRP)

N/A

**Comment by wpbirney** [comment]
Same here on void linux, reverting 9fb96609122471e50a07478bd37b17d7c4482284 fixes it for now

**Comment by aaronp64** [comment]
I'm seeing the same on Windows 10/latest master.  If I leave it running long enough, I get a bunch of the messages below printed out:

```
Failed method: CanvasItem::_redraw_callback. Message queue out of memory. Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_mb' in project settings.
Object was deleted while awaiting a callback.
Object was deleted while awaiting a callback.
Object was deleted while awaiting a callback.
Object was deleted while awaiting a callback.
Object was deleted while awaiting a callback.
...
```

Also saw `EditorNode::_print_handler_impl` instead of `CanvasItem::_redraw_callback`

**Comment by Calinou** [comment]
cc @bruvzg
