### ISSUE TITLE
Firefox swaps X and Y buttons on controller for WebGL builds

### ISSUE THREAD

**Issue by MichaelMacha** [godotengine/godot#92811]
### Tested versions

Reproducible in: 4.3.beta1.official

### System information

KUbuntu 22.04.4 LTS

### Issue description

When exporting to WebGL using the Compatibility backend, controllers do work; however, when loaded on Firefox, the X and Y buttons are completely swapped. That is, Y does what is assigned to X, and X what is assigned to Y.

On Chromium, and on desktop builds, I have not had this issue.

### Steps to reproduce

Assign distinctive actions to Input Mappings, with the X button and Y button mapped to them accordingly. Export for web, and try it in Firefox browser; note that the actions are swapped. Try again in Chromium or on a desktop build, and note that they behave as intended.

Discovered with a Logitech F710. There's a possibility that this is a Firefox issue, or a Logitech issue, but this seems like the first and best place to look. Note in the example project that the mapped keyboard keys work as assigned in either browser, but the actual controller buttons are swapped.

### Minimal reproduction project (MRP)

Note that the bug can also be seen through my original game at https://vikinghelmet99.itch.io/froojarspootz-the-cleaning-monster

[Gamepad Bug.zip](https://github.com/user-attachments/files/15595305/Gamepad.Bug.zip)

**Comment by Calinou** [comment]
Can you test the controller on https://gamepad-tester.com/ on both Firefox and Chromium? If mappings appear inverted there as well, I don't think we can do anything about it.

**Comment by MichaelMacha** [comment]
@Calinou OK, I tested it out on gamepad-tester, and again the buttons are inverted. It would make sense that this might be a Firefox issue, then. I'll close this and report accordingly, thank you!

**Comment by MichaelMacha** [comment]
Closing due to replication on gamepad-tester.com
