### ISSUE TITLE
Add BoneAttachment3D programmatically gives wrong GlobalPosition

### ISSUE THREAD

**Issue by DiegoSynth** [godotengine/godot#92813]
### Tested versions

Reproducible in 4.1.2.stable.mono.official

### System information

Windows 10, 
4.1.2.stable.mono.official
4.2.2.stable.mono.official
4.2.2.stable.official

### Issue description

A) BoneAttachment3D created in the editor = all good
B) BoneAttachment3D created in the code = its GlobalPosition is wrong (different to when created in editor)

![boneAttachment3D](https://github.com/godotengine/godot/assets/19650031/f049dbfb-a779-4cbd-b784-55021f1c229c)

### Steps to reproduce

[A or B] then C

A) create BoneAttachment3D in editor. Get it in the code. Show its GlobalPosition:
`BoneAttachment3D boneAttachment = skeleton.GetNode<BoneAttachment3D>(new NodePath("BoneAttachment3D"));
GD.Print("boneAttachment : " + boneAttachment.GlobalPosition);`

B) create BoneAttachment3D in code. Set a bone_index. Add to skeleton as child. Show its GlobalPosition:
`BoneAttachment3D boneAttachment = new BoneAttachment3D();
boneAttachment.BoneIdx = boneId;
skeleton.AddChild(boneAttachment);
GD.Print("boneAttachment : " + boneAttachment.GlobalPosition);`

At this point, the boneAttachment.GlobalPosition in B is different than in A.

C) create a MeshInstance3D. Add it to the BoneAttachment3D as a child. Change the mesh's GlobalPosition = it's positioned wrongly.

### Minimal reproduction project (MRP)
Find here a sample project:
[BugReport.zip](https://github.com/user-attachments/files/15823643/BugReport.zip)
[project files updated: 2024/06/13]

This was also reported by other people (see 4th reply here):
[https://forum.godotengine.org/t/instantiating-by-code-and-editor/44875/3](url)
```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment]
Please upload an MRP still, it helps a lot and the steps you give are very vague

**Comment by DiegoSynth** [comment]
Alright, I made a Minimum project. It took me 3 hours (created a skeleton, 3d model, skinned it and made a full Godot project from scratch), but here it is.
[Uploading BugReport.zip…]()

In the example there are two scenes, they both contain the same 3D model with bones.

Scene Body_000 (script attached: **Body_000.cs**) - contains:
-Model
-BoneAttachment3D
 -Area3D
  -CollisionShape3D

Scene Body_001 (script attached: **Body_001.cs**) - contains:
-Model
 
Both scenes' script inherit from Body.cs which has the main code.
I don't know how I can explain further, but I think it's very clear already, specially launching the project and checking Body.cs, Body_000.cs and Body_001.cs

Please mind that this is an enormous amount of time and work that I'm dedicating for this bug to be taken care of, and I'm very grateful that you are already having a look at it.

Kind regards,
Diego

**Comment by DiegoSynth** [comment]
> @DiegoSynth I have specially prepared a project for you, please create your problem on it and attach it (this project is for version 4.3) [ProjectBone.zip](https://github.com/user-attachments/files/15670537/ProjectBone.zip)
> 
> Before sending, delete the .godot folder if Github complains about the file size

Oh, our replies crossed each other.
Thanks for your help with the sample project; I anyway made a project, I hope it's good, but if anything, please let me know.

**Comment by donpers** [comment]
I also noticed this issue half year ago, since then my project is frozen.

In my case i couldnt even tell if there is something i was doing wrong because i find the Mesh button in the tabs menu is very intransparent - and you cant tell what is really happening under the hood and how to properly reproduce it in code.

Any work around ideas?

**Comment by DiegoSynth** [comment]
@donpers  No work around coming to my mind. I've tried a lot of things with no luck.
I've found that the Transform matrix is different for BoneAttachment3D if created in code vs editor.

![transform](https://github.com/godotengine/godot/assets/19650031/50ab695c-9dbf-40af-9081-bb7fb4885b0a)

There must be something else the editor is doing in the background with the transforms. I believe just adding the BoneAttachment3D to the skeleton by code (addChild) is not enough. But setting the correct Transform3D manually is not solving the issue either (probably it's not refreshing, or who knows what).

I guess our only hope is to wait until someone knowledgeable in the Editor comes to help.

Hey @AThousandShips, any update on this?
@JekSun97 ?

**Comment by AThousandShips** [comment]
No update yet no, no one has looked into this yet as far as I know

**Comment by donpers** [comment]
I just noticed your using the mono version of godot, the same bug is happening with the gdscript version.

**Comment by DiegoSynth** [comment]
@donpers Thanks, I've updated the main post. I've previously tested it in 4.1.2 and after migrating I see that it's still the same in 4.2.2.

I wonder if there's any way to reach to any Editor developer / contributor. I could help in the solving process, but if this post stays in stage zero, it will fall into oblivion.

It would be nice if the ticketers could actually fill in the info and create a case, as I've very much done my part...

**Comment by AThousandShips** [comment]
This is the place you get in touch with the developers and contributors, but please don't rush, the info has been filled in, this *is* the issue case, and issues aren't assigned unless there's some specific issues

Further testing to identify what exactly is causing this is needed by someone who can test the animation code

**Comment by DiegoSynth** [comment]
I have figured out the following:

When creating for example this structure:

- BoneAttachment3D
  - Area3D
    - CollisionShape3D
      - MeshInstance3D
       
and setting a position delta for the first child of BoneAttachment3D (Area3D), if this delta is calculated **before** creating (and attaching) the mentioned Nodes, the delta will not have the expected value, whereas if the Nodes are created and attached first, and then the delta is calculated, the delta will be correct:

**Bad:**

```
int[] children = this.skeleton.GetBoneChildren(boneId);

// ---------- CALCULATE DELTA POSITION:
vectorBoneGlobal = this.skeleton.ToGlobal(this.skeleton.GetBoneGlobalPose(children[0]).Origin) - this.skeleton.ToGlobal(this.skeleton.GetBoneGlobalPose(boneId).Origin);
position = vectorBoneGlobal / 2f;

// ---------- CREATE AND ATTACH NODES TO SKELETON:
BoneAttachment3D bone = new BoneAttachment3D();
Area3D area = new Area3D();
MeshInstance3D mesh = new MeshInstance3D();
CollisionShape3D collider = new CollisionShape3D();

bone.BoneName = boneName;

skeleton.AddChild(bone);
bone.AddChild(area);
area.AddChild(collider);
collider.AddChild(mesh);
```

**Good:**

```
int[] children = this.skeleton.GetBoneChildren(boneId);

// ---------- CREATE AND ATTACH NODES TO SKELETON:
BoneAttachment3D bone = new BoneAttachment3D();
Area3D area = new Area3D();
MeshInstance3D mesh = new MeshInstance3D();
CollisionShape3D collider = new CollisionShape3D();

bone.BoneName = boneName;

skeleton.AddChild(bone);
bone.AddChild(area);
area.AddChild(collider);
collider.AddChild(mesh);

// ---------- CALCULATE DELTA POSITION:
vectorBoneGlobal = this.skeleton.ToGlobal(this.skeleton.GetBoneGlobalPose(children[0]).Origin) - this.skeleton.ToGlobal(this.skeleton.GetBoneGlobalPose(boneId).Origin);
position = vectorBoneGlobal / 2f;
```

I don't know if this is "intended" to be like this, or if there's any rational explanation, but this seems to "solve" the issue. I will continue testing it.

**Comment by DiegoSynth** [comment]
Alright, for anyone, in the future; this works:


1)  create **ALL** bone attachments.
2)  create **ALL** Area3D, CollisionShape3D, MeshInstance3D, etc.
3)  addChild one to each other, and boneAttachment3D to the skeleton.

_AFTER all that structure is done and added to the skeleton (ALL BONE ATTACHMENTS and children nodes):_

4)  reposition, resize anything as desired.


This works, so I'm closing this case.
