### ISSUE TITLE
Can't use enum alias

### ISSUE THREAD

**Issue by deonix37** [godotengine/godot#92816]
### Tested versions

4.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 Threads)

### Issue description

Have match_settings.gd
```gdscript
class_name MatchSettings
extends Node

enum InstantCardMode {AFTER_TARGET, BEFORE_TARGET}
```
Have something.gd
```gdscript
var InstantCardMode = MatchSettings.InstantCardMode

var something: InstantCardMode
```
Can't make variable `something` of type InstantCardMode:
```
"InstantCardMode" is a variable but does not contain a type.
```

### Steps to reproduce

See description

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment]
Try `const InstantCardMode`.
