### ISSUE TITLE
TextureRegion Editor LMB Not changing selected region

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#9282]
**Operating system or device - Godot version:**
Manjaro 64bit Godot 3.0

**Issue description:**

When I try to edit the texture region of a sprite in the texture-region tab I can't get the frame to move or resize without changin the values in the property panel

**Steps to reproduce:**
1) make a sprite
2) load a normal map with sprite
3) enable region selection
4) open texture-region tab
5) try to change animate your sprite using regions....groan showing your level of irritation...slap self in forehead.

**Link to minimal example project:**

[2dtests.zip](https://github.com/godotengine/godot/files/1086879/2dtests.zip)

possibly related to #9281
@Zylann do you know if your PR will fix this bug?

**Comment by Zylann** [comment]
My PR won't fix it, it's not related to docks or even 2D stuff.

**Comment by MarianoGnu** [comment]
patch available on PR #9293
