### ISSUE TITLE
"Small Deploy with Network" with .local domain fails in Godot 2.1.3 & iOS (regression)

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#9283]
**Operating system or device - Godot version:**
iOS 10.1.3 - Godot 2.1.3

**Issue description:**
Using the "Small Deploy with Network" requires the argument "-rfs <IP>". 
In earlier versions, setting the argument "-rfs MacBook.local" (the Mac's name is "MacBook") worked, since it resolves for the Mac's IP which may change every time you connect to a network. In Godot 2.1.3 it no longer works, and crashes, unless you set the IP, which you have to update every now and then manually

**Steps to reproduce:**
1.- Run a Godot Project and enable Small Deploy With Network.
2.- Downloading the export templates, uncompressing the iOS template and installing the Xcode project with Arguments Passed On Launch set to "-rfs <Mac'sName.local>" will crash on launch
3.- Replacing the executable (godot_debug.iphone) with an earlier version runs perfectly well (I'm not sure if the version I used for replacing is 2.1.1 or 2.1.2, it has a modified date of November 16, 2016)

**Comment by bojidar-bg** [comment]
Ping @Faless @punto- , this might be related to IPv6 changes (even though that's a bit far-fetched).

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by lexum0** [comment]
Seems to be working now on Godot 2.1.4

**Comment by kubecz3k** [comment]
Thank you for checking
