### ISSUE TITLE
When Camera2D zoom isn't at default value, PopupMenus in MenuBars within CanvasLayers appear offset incorrectly

### ISSUE THREAD

**Issue by bugbard-cryptid** [godotengine/godot#92834]
### Tested versions

- Reproducible in: v4.2.1-stable, v4.2.2-stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.4617) - AMD Ryzen 3 2200G with Radeon Vega Graphics (4 Threads)

### Issue description

When you change the zoom of a Camera2D from (1, 1), PopupMenus in MenuBars contained in a CanvasLayer will appear offset incorrectly; moving down as you zoom in, and up as you zoom out. They also appear to get wider as you zoom in. 

Here's a video of what it looks like:

https://github.com/godotengine/godot/assets/61643906/8304a1d1-501f-48fe-809f-6b927501e967

### Steps to reproduce

1. Create a CanvasLayer
2. Add a MenuBar as a child, and a PopupMenu as a child of that MenuBar
3. Create a Camera2D, and change zoom from 1 (it does not matter if it is changed through code or through the inspector)
4. Click on the PopupMenu

### Minimal reproduction project (MRP)

[PopupMenu bug.zip](https://github.com/user-attachments/files/15611359/PopupMenu.bug.zip)

**Comment by stephen-berry** [comment]
Thanks @kleonc! Didn't consider the x value or canvas transformer 😳 glad you found the root of the problem 👍
