### ISSUE TITLE
Playing backwards discrete animation will begin with the first keyframe

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92840]
### Tested versions

4.3 beta1
not sure when it started exactly

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I have a door that uses the same animation for opening and closing, and the animation is played forward and backward.
It looks more or less like this:
![image](https://github.com/godotengine/godot/assets/2223172/c98fe4bd-479d-4e9e-96d5-bc00eafbad65)
Notice the empty space between last frame and end of the animation. When playing backwards, the empty space is filled with the first frame:

https://github.com/godotengine/godot/assets/2223172/05790cca-624c-496b-85ac-8cd8abe3889a

It works correctly when I repeat the last frame at the end:

![image](https://github.com/godotengine/godot/assets/2223172/54d81c69-a6b8-493a-b047-e76d1903c15b)

https://github.com/godotengine/godot/assets/2223172/1d34e49e-7eef-4034-b48a-90ceaccde682

This wasn't necessary before.

### Steps to reproduce

Run the MRP.

### Minimal reproduction project (MRP)

[discretebug.zip](https://github.com/user-attachments/files/15632115/discretebug.zip)

**Comment by JekSun97** [comment]
This happens starting from version 4.3 dev4, which I also noticed, this only happens in a running project, I don’t see this problem in the editor
