### ISSUE TITLE
Adjustments don't do anything unless glow or 3d_scale is used

### ISSUE THREAD

**Issue by bs** [godotengine/godot#92853]
### Tested versions

- Reproducable in 4.3beta 1, 4.2.2.stable

### System information

Godot v4.2.2.stable - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

With the Compatibility renderer on Mac, adjusting `WorldEnvironment.environment.adjustment_brightness` has no effect on the brightness of the screen.

Switching to Forward+ works as expected.

Compatibility mode:
![brightness_compat](https://github.com/godotengine/godot/assets/68/62437152-33c6-47e9-bb55-d513540f55cd)

Forward+:
![godot_brightness_forward](https://github.com/godotengine/godot/assets/68/f0e408db-b0b0-47b4-aa5a-54033261668d)

### Steps to reproduce

Create a new project with the Compatibility renderer on my Mac. Create an HSlider to adjust brightness.

### Minimal reproduction project (MRP)

[brightness_setting.zip](https://github.com/user-attachments/files/15699376/brightness_setting.zip)

**Comment by jsjtxietian** [comment]
See the note here:

![image](https://github.com/godotengine/godot/assets/8315986/6cb32c73-06b0-477f-b361-066cdbf3cede)

**Comment by AThousandShips** [comment]
What other documentation could be updated? That tooltip is from the documentation

**Comment by bs** [comment]
Ah, the places I checked were:

- https://docs.godotengine.org/en/stable/classes/class_environment.html#class-environment-property-adjustment-brightness (under the brightness property, specifically)
- https://docs.godotengine.org/en/stable/tutorials/3d/environment_and_post_processing.html
- And of course scouring the internet.

While it might be nice to add this as a note to each property for visibility, that also might be redundant and a bit fragile.

**Comment by clayjohn** [comment]
The docs should be updated to remove the note about not being supported as adjustments were added to the compatibility renderer in https://github.com/godotengine/godot/pull/91176

They should be available in the beta 1 version

**Comment by bs** [comment]
Thanks @clayjohn! I tested in beta 1 and brightness adjustments weren't applying.

**Comment by clayjohn** [comment]
> Thanks @clayjohn! I tested in beta 1 and brightness adjustments weren't applying.

Thank you for confirming. That means we are dealing with a bug (maybe only on MacOS) _and_ and documentation issue. Both could be fixed at the same time

**Comment by bs** [comment]
Reproduction in 4.3 just to make sure I'm not trippin:
[brightness-settings-4.3.zip](https://github.com/user-attachments/files/15750025/brightness-settings-4.3.zip)

https://github.com/godotengine/godot/assets/68/07d86a21-d8fd-4ca0-82e9-bc09e965b300

**Comment by clayjohn** [comment]
Confirmed on an M2 Mac. We should test on non MacOS devices too.

**Comment by clayjohn** [comment]
I've taken another look. Adjustments appear to work just fine in any other project. There is something unique to that MRP that is making it not work. I suspect that the real bug is actually in the canvas background mode, not in the adjustments
