### ISSUE TITLE
Resource duplication bug(error).

### ISSUE THREAD

**Issue by teamjistory** [godotengine/godot#92854]
### Tested versions

godot 4.3.beta 1 (mono, c#)

### System information

Win 10, desktop, c#

### Issue description

When duplicating a Resource (.tres) , there are cases where the uid is copied as is, resulting in duplication in Godot Editor(File system panel). This needs to be resolved.

### Steps to reproduce

When duplicating a Resource (.tres) , there are cases where the uid is copied as is, resulting in duplication in Godot Editor(File system panel). This needs to be resolved.

### Minimal reproduction project (MRP)

When duplicating a Resource (.tres) , there are cases where the uid is copied as is, resulting in duplication in Godot Editor(File system panel). This needs to be resolved.

**Comment by AThousandShips** [comment]
How did you duplicate it? By using the editor interfaces with duplicate?

**Comment by teamjistory** [comment]
In FileSystem Panel doc => Ctrl+D

**Comment by AThousandShips** [comment]
Please add some more details on what is going on, what type of resources, which uid is it? The one of the resource itself?

**Comment by teamjistory** [comment]
> Please add some more details on what is going on, what type of resources, which uid is it? The one of the resource itself?

Yes, custom Resource.

![image](https://github.com/godotengine/godot/assets/80578519/c29f99b4-7689-420f-b98b-336e19207a5b)

**Comment by AThousandShips** [comment]
And the old file has the same UID? This is the new file?

**Comment by teamjistory** [comment]
> And the old file has the same UID? This is the new file?


Yes, Old and New file is same the UID that it.

**Comment by teamjistory** [comment]
> Can you show the old file as well?

Maybe you can try Ctrl+D to inherit your own resource node and create tres as a c# file source.

**Comment by AThousandShips** [comment]
> Maybe you can try Ctrl+D to inherit your own resource node and create tres as a c# file source.

I have and so far I haven't been able to replicate this, what's the problem with showing the old file?

**Comment by teamjistory** [comment]
1. [gd_resource type="Resource" load_steps=2 format=3 uid="uid://ddtr5uohh8nwk"]

[ext_resource type="Script" path="res://JIStudio/JistyBase/Player/PlayerJISSkill/DataModel/PlayerJISSkill_ResDataModel.cs" id="1_aliqo"]

[resource]
script = ExtResource("1_aliqo")
SkillName = "Base Treatment"
SkillDescription = "Recovers 1D2 player character Life Energy."
RoleSpecific = 4
RaceSpecific = 0
FunctionType = 1
UsingType = 1
PlayType = 1
CostEnergyType = 2
CostEnergyValue = 1

2.
[gd_resource type="Resource" load_steps=2 format=3 uid="uid://gaj2r5l26xks"]

[ext_resource type="Script" path="res://JIStudio/JistyBase/Player/PlayerJISSkill/DataModel/PlayerJISSkill_ResDataModel.cs" id="1_t58pg"]

[resource]
script = ExtResource("1_t58pg")
SkillName = "Quick Step"
SkillDescription = "Gain 1D3 movement points."
RoleSpecific = 1
RaceSpecific = 0
FunctionType = 1
UsingType = 1
PlayType = 1
CostEnergyType = 1
CostEnergyValue = 1

**Comment by AThousandShips** [comment]
I tested again and it doesn't happen for me, I don't use C# but I doubt that would be causing anything

So you need to provide more clear steps when this happens because I can't replicate this, more information is needed

It would help if you could make a minimal project where this happens, and also try if it happens without C#

**Comment by teamjistory** [comment]
Here, c# script.
using Godot;
using WoovDungeon.JIStudio.JistyBase.Player.PlayerJISSkill;
using WoovDungeon.JIStudio.ShareBase.Code.Enum;

public partial class PlayerJISSkill_ResDataModel : Resource, IPlayerJISSkill_StandardModel
{
    [Export] public string SkillName { get; set; }
    [Export] public string SkillDescription { get; set; }

    [Export] public Enum_PlayableRole RoleSpecific { get; set; }
    [Export] public Enum_PlayableRace RaceSpecific { get; set; }

    [Export] public Enum_JISSkill_FunctionType FunctionType { get; set; }
    [Export] public Enum_JISSkill_UsingType UsingType { get; set; }
    [Export] public Enum_JISSkill_PlayModeType PlayType { get; set; }

    [Export] public Enum_SoulEnergyType CostEnergyType { get; set; }
    [Export] public int CostEnergyValue { get; set; }

    [Export] public Texture2D SkillIcon { get; set; }

**Comment by teamjistory** [comment]
d
