### ISSUE TITLE
LightmapGI: Directional lights do not bake in in compatibility renderer

### ISSUE THREAD

**Issue by wojtekpil** [godotengine/godot#92863]
### Tested versions

- First reproducibility in 4.3dev6. Still present in 4.3beta1 and at 5f1184e93fe1021c86520460dc0a6619bff3c1fb
- Last working version: 4.3dev5

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon RX 6800S (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 6800HS with Radeon Graphics (16 Threads)

### Issue description

Lightmaps baked using editor in compatibility renderer do not reflect directional light influence anymore. 
This seems to be a regression in recent 4.3 builds:
Expected result baked from Godot 4.3dev5, contains indirect information from red cube on ground:
![Zrzut ekranu 2024-06-07 130028](https://github.com/godotengine/godot/assets/1286923/75e99f4f-bb7d-42af-bd12-2a10da52ecca)

Same scene baked in Godot 4.3beta1/dev6:
![Zrzut ekranu 2024-06-07 130233](https://github.com/godotengine/godot/assets/1286923/faf2f5cf-cbe9-400e-a684-07b98832f040)

The issue is not present with Vulkan (Forward+)

### Steps to reproduce

1. Open MRP and try baking a lightmap from a LightmapGI node in Godot 4.3beta1
2. Do same thing with  Godot 4.3dev5 to confirm the issue is not present there.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/15738258/mrp.zip)

**Comment by Summersay415** [comment]
If you can, try to [bisect](https://docs.godotengine.org/en/stable/contributing/workflow/bisecting_regressions.html) which commit introduced this regression.
You know it appeared between 4.3dev5 and 4.3dev6, you can use their hashes to greatly reduce range of bisecting.
4.3dev6 commit hash: 64520fe6741d8ec3c55e0c9618d3fadcda949f63
4.3dev5 commit hash: 89f70e98d209563abb4dbc1f8cd5d76c81eb7940

**Comment by wojtekpil** [comment]
So it seems like reverse-z commit broke lightmap baking in compatibility: 
```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d950f5f83819240771aebb602bfdd4875363edce] Use Reverse Z for the depth buffer
```

**Comment by wojtekpil** [comment]
Interesting observation is that at d950f5f83819240771aebb602bfdd4875363edce it is also not working on Vulkan, so my assumption regarding projection is obviously incorrect. But LightmapGI  it is working on Godot 4.3dev6 again. So seems like ReverseZ PR is breaking both renderers, but Vulkan is fixed in some commit, before dev6 release. Probably needs to be bisected again
