### ISSUE TITLE
GDScript import plugins are not working properly

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9286]
Custom import plugins are misbehaving most of the time.

- ~~Custom resources does not appear on the FileSystem dock at first. They appear if you reimport something then unfocus/refocus the editor, and even then only the current folder shows. Deleting the `.import` folder also seems to work but only the first time, so it does not help when the editor is reopened.~~
- ~~They also don't reappear if you deactivate and reactivate the plugin.~~
- ~~The import presets does not appear on the list.~~
- ~~The editor crashes on exit if the plugin is active.~~

Tested again (2017-11-08) and above issues are solved, but there are a couple that remain:
- Adding a custom importer for an existing resource doesn't seem to make a difference. The "Import As" dropdown doesn't seem to do anything.
- If the plugin is active when the project is opened, custom resources don't appear on the FileSystem dock at first, but they do appear if unfocus/refocus the editor window.

**Comment by Hinsbart** [comment]
> Adding a custom importer for an existing resource doesn't seem to make a difference. The "Import As" dropdown doesn't seem to do anything.

Seems like importer selection isn't implemented at all currently. (The `item_selected` signal of that [menu](https://github.com/godotengine/godot/blob/master/editor/import_dock.cpp#L319-L321) is not connected to anything).

> The editor crashes on exit if the plugin is active.

Did you call `EditorPlugin::remove_import_plugin` in `_exit_tree()`? I guess we should look into how to do that automatically.

**Comment by vnen** [comment]
> Did you call EditorPlugin::remove_import_plugin in _exit_tree()? I guess we should look into how to do that automatically.

Yes, I did call the function on `_exit_tree`. The crash does not always happen though, I'll try to find a way to reproduce consistently.

**Comment by vnen** [comment]
I can't make it crash anymore. It does crash if I remove the `remove_import_plugin()` call. I think it was crashing before I added the line and confused things.

I noticed that `get_recognized_extensions()` of my plugin is getting called but it does not make a difference in the FileSystem dock. I believe some update routine is missing there, though I couldn't figure out which.

**Comment by vnen** [comment]
I note that it still crashes if I disable/reenable the plugin a few times in the session.

----
I changed the line [here](https://github.com/godotengine/godot/blob/6fd4311/editor/editor_plugin.cpp#L287) to call `scan()` instead of `scan_changes()` and it now works when reactivating the plugin. However when the editor is just opened, there's already a scan thread in the background so this call gets ignored. This causes the custom resources to not appear if the plugin is already active when the editor is opened.

**Comment by vnen** [comment]
Major hacked workaround:

```gdscript
tool
extends EditorPlugin

var import_plugin = null

func get_name():
	return "My Plugin"

func _enter_tree():
	get_resource_filesystem().connect("filesystem_changed", self, "update_resources")
	import_plugin = preload("my_import_plugin..gd").new()
	add_import_plugin(import_plugin)

func _exit_tree():
	remove_import_plugin(import_plugin)
	import_plugin = null

func update_resources():
	get_resource_filesystem().disconnect("filesystem_changed", self, "update_resources")
	get_resource_filesystem().scan()
```

**Comment by reduz** [comment]
@vnen is this relevant given the fix above?

**Comment by vnen** [comment]
@reduz yes, my fix was only partial. I don't quite remember now, but there are some cases that the scan didn't work. The crash still happens but only if I edited the enabled plugin.

I will test again soon.

**Comment by vnen** [comment]
Tested again with current master. Updated the OP with the current issues.

**Comment by reduz** [comment]
I think the drop down of import as was fixed

**Comment by phil123456** [comment]
I get "Base is not EditorPlugin" with the latest ersion
