### ISSUE TITLE
Physics interpolation doesn't interpolate Skeleton2D animation correctly, resulting in wobbly visuals

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#92872]
- Possibly related to https://github.com/godotengine/godot/issues/71974.

### Tested versions

- Reproducible in: 4.3.dev b7feebefa, 3.6.beta 945a49064f862a939fdfbc12f63e36ecfea0c8d4

### System information

Godot v4.3.dev (b7feebefa) - Fedora Linux 39 (KDE Plasma) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 550.78) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Physics interpolation doesn't interpolate Skeleton2D animation correctly, resulting in wobbly visuals.

I've tried disabling interpolation on specific nodes on the SkeletalPlayer scene, but the only thing that fixes the issue is disabling interpolation on the entire CharacterBody2D – which makes any movement not interpolated. I've also tried changing the process mode of the AnimationPlayer and/or AnimationTree to Physics instead of Idle, but that didn't help either.

This issue is still noticeable at 60 tps on a 120 Hz display, so it's not just at low physics FPS.

*All videos were recorded at 60 FPS.*

### 10 ticks per second, physics interpolation enabled

https://github.com/godotengine/godot/assets/180032/0a6ca1fa-c869-4091-be9c-b2e7144cb039

### 10 ticks per second, physics interpolation disabled

*Skeleton updates at the rendered framerate, so does it actually need to be interpolated here? I've tried disabling interpolation on the skeleton/AnimationPlayer/AnimationTree/Polygon2D nodes and it didn't help though. I've also tried changing the process mode of the AnimationPlayer and/or AnimationTree to Physics instead of Idle.*

https://github.com/godotengine/godot/assets/180032/dca4dfb3-a908-4f2f-85e3-bbb4c055bf2f

### 10 ticks per second, physics interpolation enabled, AnimationPlayer + AnimationTree using Physics callback mode

https://github.com/godotengine/godot/assets/180032/d84f7e84-9685-4755-809c-aa79fd4b4727

### 120 ticks per second, physics interpolation enabled

*At this stage, it looks pretty much the same whether interpolation is enabled or not.*

https://github.com/godotengine/godot/assets/180032/093d91df-396a-47f7-9cde-8aa9c8f0e530

### Steps to reproduce

- Create an animation that uses Skeleton2D.
- Enable physics interpolation and set physics ticks per second to 10.

### Minimal reproduction project (MRP)

[skeleton.zip](https://github.com/user-attachments/files/15741150/skeleton.zip)

**Comment by lawnjelly** [comment]
Ah this is interesting, I hadn't noticed that.

It's likely it will need to the interpolated transform somewhere in the relative xforms, will investigate. :+1:

**Comment by lawnjelly** [comment]
Have figured this out, took a while debugging the numbers but wasn't as bad a problem as I feared.
Will prepare PR, as it will be good to have this fixed in 3.x and 4.x.

**Comment by lawnjelly** [comment]
Fixed by #93309.

**Comment by akien-mga** [comment]
This still needs to be fixed in 4.3 IIUC?

**Comment by lawnjelly** [comment]
> Possibly, I'll be looking at this with @rburing .

There are significant differences in the 2D skinning in 4.x if I remember right, so we'll have to see whether the same issue / fix is needed.

**Comment by lawnjelly** [comment]
Re-opening as still needs to be done in 4.x (my mistake).
