### ISSUE TITLE
Some buttons on panels don't return to normal image and stay with a selected/clicked one

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9288]
**Godot version: master**

**Issue description:**
Buttons on editor panels don't get the image updated after being selected.
Add node icon on the scene panel stays gray, other like the gear on the inspector (to do things like copy/paste params) disappears after using an option.

**Steps to reproduce:**
Use the buttons on editor panels.

**Comment by reduz** [comment]
Sorry, issue description makes no sense to me, no matter how hard I try to understand it..

**Comment by eon-s** [comment]
The issue is slightly different now but the effect is the same, I'll add a gif and change the title to reflect the current status.

Basically, some buttons on panels never return to the "normal" image.

This is on the alpha 1, look at the buttons that stay blue, and stay that way until the editor is closed:
![badbuttons](https://user-images.githubusercontent.com/10215987/29480851-ec7d3178-8451-11e7-8116-e878d8d2ea9b.gif)

**Comment by eon-s** [comment]
I cannot reproduce on Master so it seems that is fixed.
