### ISSUE TITLE
Import panel should show options when selecting resource from inspector

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9289]
**Godot version: 3**

Import panel should show the import data when a valid resource is selected.

Example: select the texture of a sprite, it opens on the inspector but nothing can be done from there, you need to navigate the filesystem and find the corresponding file to edit import options.

**Comment by Zylann** [comment]
Duplicate of https://github.com/godotengine/godot/issues/8139 ?

**Comment by eon-s** [comment]
yup @Zylann
