### ISSUE TITLE
Setting frame duration to 1. does not automatically resolve to 1.0 (SpinBox/Expression bug)

### ISSUE THREAD

**Issue by tioalexis** [godotengine/godot#92895]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

MacOS Sonoma 14.5 - v4.2.2.stable.official [15073afe3]

### Issue description

When setting the frame duration of a frame to an incomplete value (e.g. `1.` instead of `1.0`), the program does not accept the input and will not update the value correctly.

https://github.com/godotengine/godot/assets/83507082/2fd84a44-58ce-4f04-bbfa-30027a106c61

### Steps to reproduce

1. Create an `AnimatedSprite2D` node.
2. Add a new `SpriteFrames` resource to it.
3. In the `SpriteFrames` panel, add frames from sprite sheet.
4. Select one of the frames and modify the frame duration to `1.5`.
5. Press return or deselect the frame and select it again.
6. Set the frame duration to `1.` (no decimal number).
7. Press return and observe.

**Observed Behaviour**
- The frame remains set to `1.5`.
- The text box does not get deselected and the text entry does not get accepted.

**Expected Behaviour**
- The string is automatically parsed as `1.0`.
- The frame duration is set to `1.0` and the value takes effect.
- The text box is deselected.

### Minimal reproduction project (MRP)

[frame-duration-bug.zip](https://github.com/user-attachments/files/15747038/frame-duration-bug.zip)

**Comment by dalexeev** [comment]
I think this is a bug of `SpinBox` or the string to number function.

**Comment by Calinou** [comment]
I can reproduce this on 4.3.beta2 in the SpinBox node (with **Step** set to 0), so this is not an editor-specific issue.
