### ISSUE TITLE
Same file returns different modified time in different Godot builds

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92911]
### Tested versions

v4.3.beta1.official [a4f2ea91a]
v4.3.beta.custom_build [a4f2ea91a]

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I noticed that whenever I open my project in a custom build, the scene groups are being re-scanned for no reason. Then it happens again when I use official build. Turns out that's because the 2 builds for some reason return different modified time for a file, which causes filesystem timestamp mismatch.

I made a simple editor script to illustrate the issue. I run it in 2 Godot instances build from the same commit, but one is official and one isn't:

https://github.com/godotengine/godot/assets/2223172/b2c4c3ba-588c-4e58-8736-0b294cf86058

I tested it with 2 files. One was a scene that belongs to a project, the other one was a random file I had in my downloads folder. The issue did not occur in case of the other file.

### Steps to reproduce

1. Print a modified time of a scene file that belongs to a different project
2. Compare results from official and custom builds

### Minimal reproduction project (MRP)

```GDScript
@tool
extends EditorScript

func _run() -> void:
	print(FileAccess.get_modified_time("path/goes/here.tscn"))
```

**Comment by AThousandShips** [comment]
And the modified time of the actual file in the OS is unchanged between the two checks?

**Comment by KoBeWi** [comment]
Yes, the file was last modified 3 months ago.

**Comment by bruvzg** [comment]
> v4.3.beta.custom_build

MinGW or MSVC? Might be some difference in `_wstat` implementation.

**Comment by KoBeWi** [comment]
MSVC

**Comment by AThousandShips** [comment]
What's the results between official builds, custom build, and https://github.com/godotengine/godot/pull/74830

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot/pull/74830 does not seem to change anything.
However the issue might be DST-related, as the file was last modified on 25 of March.

**Comment by AThousandShips** [comment]
Which case does it match? The custom build or the official?

**Comment by KoBeWi** [comment]
Nervermind, I checked again and the time matches official build.

**Comment by AThousandShips** [comment]
That would make sense, was confused over the first result there, then that means that the MinGW `_wstat` handles DST correctly unlike MSVC
