### ISSUE TITLE
Stop (Re)Import process

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9291]
Is it possible to stop the (Re)Import process?(I don' want to kill the process when I know the current import is not needed).

It would also be nice to run it in the background.

I know the importer is in early state but it is taking in some cases quite some time.

Are the .import files going to be hidden files or placed together in the .import folder?

**Comment by reduz** [comment]
no, it's not and must not be possible to stop the process.
What we discussed in another issue (don´t remember which) is to at least make textures import on background, so it takes less time. This is being discussed in #10059, so closing this one as duplicate.

**Comment by Zireael07** [comment]
> must not be possible to stop the process

Why?

**Comment by AlexHolly** [comment]
What about the .import files in the folders can you hide them?

**Comment by reduz** [comment]
@Zireael07 because otherwise resources won't even load, and all sort of dependency errors will happen.
