### ISSUE TITLE
[Android Editor] Gridmap doesn't render and causes crash when renderer is set to `compatibility`

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#92910]
### Tested versions

- Reproducible in Godot 4.3 beta 1 Android Editor
- Not reproducible in Godot 4.2.2 stable Android Editor

### System information

Android 12, Android 14

### Issue description

When the renderer is set to `compatibility`, gridmap nodes in the Godot Android Editor v4.3 beta 1 don't render and cause the editor to crash. 
From looking at profiling data, it looks like the editor keeps allocating memory in an attempt to render the gridmap until it crashes.

Here's a recorded [heap profiler data](https://perfetto.dev/docs/data-sources/native-heap-profiler): https://drive.google.com/file/d/1vC9a9WKFRVWiWP5EnnnuGK7O8sfUH8Ob/view?usp=sharing

The issue doesn't occur in the Godot Android Editor v4.2.2 stable.

### Steps to reproduce

- Download or build the Godot Android Editor v4.3 beta 1
- Load the attached mrp project (based off [Kenney's city builder starter kit](https://godotengine.org/asset-library/asset/2174) with the renderer set to `compatibility`).
- Once the project is opened, notice that the gridmap doesn't render. Zooming in-out will cause the editor to crash because of unbounded memory allocations.

### Minimal reproduction project (MRP)

[starter-kit-city-builder-mrp.zip](https://github.com/user-attachments/files/15748791/starter-kit-city-builder-mrp.zip)

**Comment by m4gr3d** [comment]
cc @clayjohn @BastiaanOlij

**Comment by rburing** [comment]
Can you check if a MultiMesh has the same issue?

**Comment by matheusmdx** [comment]
Bisecting points to #88645 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/1bcd5de8-8796-4fe1-917c-0d572b22b7c3)

**Comment by clayjohn** [comment]
CC @KoBeWi

**Comment by matheusmdx** [comment]
I tested the beta 2 and the issue was fixed there, so i did a bisect to found where was fixed and points to pr #93060.

![Captura 2024-06-20 16-49-22-092913](https://github.com/godotengine/godot/assets/44306054/4bcdd3d9-8382-4fa1-906f-2b5d77ad8386)

<br>

Reading the pr details i saw a line talking about a msaa memory leak and i remembered here also talks about a memory leak, so i checked the mrp settings and i saw the mrp uses 3d msaa 2x, so i tested the mrp again in beta 1 but when i disabled the 3d msaa the bug stops, editor render everything again and drag to zoom doesn't crash the engine.

Also you can reproduce the bug with an empty 3d scene, just needs the 3d msaa actived, so maybe that was the hidden bug?

**Comment by clayjohn** [comment]
@matheusmdx thank you for the excellent investigation. That indeed sounds like the hidden bug I was describing. 

@m4gr3d can you test again to confirm that the crash is gone with beta 2? Just to confirm we aren't dealing with 2 different crashes here

**Comment by clayjohn** [comment]
@m4gr3d I just tested locally using your MRP on a custom dev build of 4.3 beta 1 on a Pixel 4 and could not reproduce the crash. 

When you have a minute, please test again with Beta 2 and confirm whether this has been fixed

**Comment by m4gr3d** [comment]
> @matheusmdx thank you for the excellent investigation. That indeed sounds like the hidden bug I was describing.
> 
> @m4gr3d can you test again to confirm that the crash is gone with beta 2? Just to confirm we aren't dealing with 2 different crashes here

Tested on beta 2 and the issue is indeed fixed! Closing this issue.

> @m4gr3d I just tested locally using your MRP on a custom dev build of 4.3 beta 1 on a Pixel 4 and could not reproduce the crash.

@clayjohn In order to repro the issue, you also had to change the renderer to `compatibility` (it's `mobile` by default), and ensure that `MSAA 3D` is enabled.
