### ISSUE TITLE
Control anchor does not get applied when position is set on resized

### ISSUE THREAD

**Issue by namooTH** [godotengine/godot#92929]
### Tested versions

- Reproducible in: v4.3.beta1.official [a4f2ea91a]

### System information

Windows 10 - Godot Engine v4.3.beta1.official.a4f2ea91a - Vulkan 1.3.277 - Forward Mobile - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3050 Laptop GPU

### Issue description

In the control node theres a "resized" signal that gets called everytime the node gets resized

Now when you have a child that has an anchor (e.g. anchor of the full size of the parent) when the parent is resized the child size would normally also get changed.

The issue is, when you set the position of that child to anything when the "resized" signal is called, the child size wont get changed according to its anchor.

Note that the anchor works just fine if you set the position of the child on every frame

![image](https://github.com/godotengine/godot/assets/73419369/b279eae6-59bb-4894-8caf-c13ad7e09f27)

### Steps to reproduce

```gdscript
func on_resized():
    get_children()[0].position = Vector.ZERO
```
child size wont get changed according to its anchor when the parent is resized

```gdscript
func process():
    get_children()[0].position = Vector.ZERO
```
works just fine when the parent is resized

### Minimal reproduction project (MRP)

[on_resize-bug.zip](https://github.com/user-attachments/files/15751010/on_resize-bug.zip)

**Comment by ghmart** [comment]
Had similar problem in the past and did like this (applied to your code):

~~~
func _on_resized() -> void:
	await get_tree().process_frame
	$ColorRect.position = Vector2.ZERO
~~~

**Comment by EAinsley** [comment]
I can confirm this on v4.3.beta.custom_build [4ab8fb809]. 
It seems the anchor and the size was updated normally, but it was not redrawn after that. 
If you add
```
$ColorRect.size = size
```
The ColorRect will be redrawn.

https://github.com/godotengine/godot/assets/63407648/d5ea485b-3d55-43cd-8e7b-cce61958014d

[on_resize-bug-updated.zip](https://github.com/user-attachments/files/16045035/on_resize-bug-updated.zip)

**Comment by EAinsley** [comment]
```diff
diff --git a/scene/gui/control.cpp b/scene/gui/control.cpp
index 0682c11a9b..c22f74d838 100644
--- a/scene/gui/control.cpp
+++ b/scene/gui/control.cpp
@@ -1744,10 +1744,10 @@ void Control::_size_changed() {
                        // so an up to date global transform could be obtained when handling these.
                        _notify_transform();

+                       item_rect_changed(size_changed);
                        if (size_changed) {
                                notification(NOTIFICATION_RESIZED);
                        }
-                       item_rect_changed(size_changed);
                }

                if (pos_changed && !size_changed) {
```
I suspected it was caused by the execution order. I originally thought that might be the user script was executed before all the data updated (but it is not).

I have changed the code above, and the problem seems to be solved, but I don't really know why. This should only change the order of notification and redraw, but not the actual computation result.
