### ISSUE TITLE
Image put_pixel -> set_pixel

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9292]
Image has `get_pixel` but to set a pixel you need to use `put_pixel`.

Image.put_pixel -> Image.set_pixel

Edit:
Maybe we can also add Image.set_pixel(Vector2, color)?

Edit2:
And Image.get_pixel(Vector2)?

**Comment by ducdetronquito** [comment]
Should we close this issue :) ?

**Comment by akien-mga** [comment]
Fixed by #9541.
