### ISSUE TITLE
Nav agent is not restricted to the 'connecting' area when traversing between two nav regions

### ISSUE THREAD

**Issue by Cwazywierdo** [godotengine/godot#92924]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5], v4.1.1.stable.official [bd6af8e0e], v4.0.3.stable.official [5222a99f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz (4 Threads)

### Issue description

When there are two navigation regions connected via `edge_connection_margin`, agents have to leave the nav mesh in order to move from one region to another. When they are outside of the mesh though, they are not restricted to the connecting area (pink), causing them to cut corners.

A path where the agent does NOT traverse between regions, and correctly stays within the nav mesh:
![image](https://github.com/godotengine/godot/assets/42323315/97f0c64c-d370-49b8-a78a-b14ca93130ab)
A path where the agent DOES traverse between regions, and leaves the nav mesh and connecting area;
![image](https://github.com/godotengine/godot/assets/42323315/3326f061-de47-40cd-8d9e-a2b193f380a0)

### Steps to reproduce

The following instructions are also viewable inside the MRP:

Ensure that Debug>Visible Navigation is enabled in the editor
Press number keys to set nav target
1 - Top Left
2 - Top Right
3 - Bottom Left
4 - Bottom Right

Try pressing 1, then 3 and see how the agents path stays within the nav mesh bounds
Then try pressing 4, then 2 to see how the agent leaves the nav mesh at the point where the two regions connect.

### Minimal reproduction project (MRP)

[Pathfinding Between Regions OOB MRP.zip](https://github.com/user-attachments/files/15750345/Pathfinding.Between.Regions.OOB.MRP.zip)

**Comment by AThousandShips** [comment]
Can you confirm this on 4.2.2? Or 4.1.4? There might have been fixes in the more recent versions

**Comment by smix8** [comment]
The edge connection margin is not a replacement for missing polygons. It is intended to "glue" together edges that dont have the same edge length or have very small misalignment due to sloppy editor placements. The default 0.25 is already too generous, pushing it to 1.0 basically results in what you see here. This is not a bug.
