### ISSUE TITLE
Unexpected indenting behavior when passing lambda functions as Callable nested parameter in GDScript 

### ISSUE THREAD

**Issue by leopeltola** [godotengine/godot#92938]
### Tested versions

Found in Godot v4.3 beta 1 mono. Reproduces in Godot 4.2-stable (non-mono), did not try other versions.

### System information

Godot v4.3.beta1.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

The following code has unexpected indenting behavior. 

```gdscript
class TestClassHolder:
	func _init(_test_classes: TestClass) -> void:
		pass

class TestClass:
	func _init(_callable: Callable) -> void:
		pass


var test_class_holder := TestClassHolder.new(
	TestClass.new(
		func(): 
			pass,
	) # THIS LINE ERRORS
)

var test_class := TestClass.new(
	func():
		pass
) # This works fine
```

![image](https://github.com/godotengine/godot/assets/49021946/a250eab7-9ece-4c39-b086-e0a3a0d0b3fa)

I found 2 fixes for this error, neither of them pretty:

![image](https://github.com/godotengine/godot/assets/49021946/d8dae0e7-8ef7-47dc-a0f8-d16b86ec07ca)
![image](https://github.com/godotengine/godot/assets/49021946/de2460dc-0b13-4507-8c18-8c35ecadbb86)

### Steps to reproduce

Copy the following code to any gdscript file. An error should pop up.

```gdscript
class TestClassHolder:
	func _init(_test_classes: TestClass) -> void:
		pass

class TestClass:
	func _init(_callable: Callable) -> void:
		pass


var test_class_holder := TestClassHolder.new(
	TestClass.new(
		func(): 
			pass,
	) # THIS LINE ERRORS
)

var test_class := TestClass.new(
	func():
		pass
) # This works fine
```

### Minimal reproduction project (MRP)

[lambda-indent-bug.zip](https://github.com/user-attachments/files/15752636/lambda-indent-bug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/71109

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
