### ISSUE TITLE
Godot 4.3 Beta 1 - Vive Focus 3 OpenXR fails to start. Unable to locate library.

### ISSUE THREAD

**Issue by Psychophylaxis2** [godotengine/godot#92979]
### Tested versions

Reproducable in Godot 4.3 Beta 1 down to Godot 4.1
Worked in Godot 4.0.2 with manual manifest updates

### System information

Android on HMD - Godot 4.3 Beta 1 Mobile render

### Issue description

Using the Godot OpenXR Tools demo
Set the vendor library to Khronos
Export to Android Kronos
On the headset it reports a failure to start OpenXR and it runs the application as a 2D app instead.

Debugger reports failure to find libopenxr_loader.so, but it is in the apk file.

![image](https://github.com/godotengine/godot/assets/101484647/2936733a-2ce7-485e-a138-907db261dd56)

------------------------
```
debug log:
E 0:00:00:0146   open_dynamic_library: Can't open dynamic library: libopenxr_loader.so. Error: dlopen failed: library "libopenxr_loader.so" not found.
  <C++ Error>    Parameter "p_library_handle" is null.
  <C++ Source>   platform/android/os_android.cpp:240 @ open_dynamic_library()

E 0:00:00:0146   openxr_loader_init: OpenXR loader not found.
  <C++ Error>    Condition "error_code != OK" is true. Returning: false
  <C++ Source>   modules/openxr/openxr_api.cpp:1480 @ openxr_loader_init()

W 0:00:00:0146   initialize_openxr_module: OpenXR was requested but failed to start.
Please check if your HMD is connected.
Godot will start in normal mode.

  <C++ Source>   modules/openxr/register_types.cpp:151 @ initialize_openxr_module()

E 0:00:02:0993   start_xr.gd:102 @ _setup_for_openxr(): OpenXR: Failed to initialize
  <C++ Source>   core/variant/variant_utility.cpp:1092 @ push_error()
  <Stack Trace>  start_xr.gd:102 @ _setup_for_openxr()
                 start_xr.gd:66 @ initialize()
                 start_xr.gd:58 @ _ready()
```

### Steps to reproduce

Using the Godot OpenXR Tools demo for 4.3
Set the vendor library to Khronos version 2.0.4
Export to Android Kronos
Install on the headset

### Minimal reproduction project (MRP)

I cannot get the zip file size down to 10 meg. Even stripping the OpenXR demo down to bare minimum for the splash screen and no build files its a 90meg zip

**Comment by BastiaanOlij** [comment]
Make sure you use the vendor library v3.0.0 (beta), 2.0.4 does not work properly with 4.3

I've had this running fine on an HTC XR Elite, so I'm assuming it would also run on a Focus 3.

**Comment by Psychophylaxis2** [comment]
Very happy to confirm that on Godot 4.3Beta2 with Vendor library 3.0.0 Beta 2 I can successfully run the OpenXR Tools demo natively on the Focus 3. Thanks for all the hard work getting this going its a game changer for my company.
