### ISSUE TITLE
Save progress popup's content is too small

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92971]
### Tested versions

4.3 beta 32eba1ee17555fbc4f4d348a568b6d9d391de9a5
Not happening in 4.3 beta1.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/6a595116-6c23-40c7-8e19-3504a731781c

Happens every time.

### Steps to reproduce

1. Open scene
2. Save scene

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Bisecting points to #92645 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/16f837d1-4c11-4885-9ac2-ea60d1f84f3c)
