### ISSUE TITLE
Can't edit StreamTexture flags

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#9298]
**Operating system or device - Godot version:**
Godot master - 3c1fd26
Linux Mint 18.1 Cinnamon x64

**Issue description:**
The ability to set flags for a StreamTexture resource in the Inspector hasn't been implemented. Editing the flags manually via the .import files does work, so the functionality is there, but it isn't possible to do through the editor.

You can replicate this easily by adding a Sprite node and loading an image as a Texture, say, a .png file. In Godot 2.x an ImageTexture would be automatically created from the image, which has a Flags dropdown. In master it instead creates a StreamTexture, which has no Flags menu. Ideally it would have the same Flags dropdown as an ImageTexture resource.

Additionally, there doesn't seem to be a way to disable image filtering through the Project Settings menu anymore, but maybe that's for another issue.

**Comment by vnen** [comment]
I'm guessing you missed the Import dock. It's at the right of the Scene dock and is activated when you select a file on the FileSystem dock.

**Comment by homer666** [comment]
Ah, I see. Guess I should close this, sorry for the inconvenience. Would it be worth opening an issue about the last point I brought up or am I missing something there too?

**Comment by vnen** [comment]
Currently there's no way to set the import settings as default (such as texture filtering), but there's already an open issue about this: #9203

**Comment by homer666** [comment]
Alright, thanks! I'll be keeping my eye on it.
