### ISSUE TITLE
Input Map: cannot map joypads with device numbers above zero

### ISSUE THREAD

**Issue by mcanders** [godotengine/godot#9299]
**Operating system or device - Godot version:**
Arch Linux, godot 3.0 f919be936b366f23388a8bcd99941d1fcd7cba73

**Issue description:**
Device numbers are reset to zero when saving joypad input mappings with device numbers above zero.  This is because:

1) InputEvents are serialized using the new generic Variant::Object serialization approach, which writes an object's member variables in a json-ish format (see variant_parser.cpp)
2) The device number is not written or read because it is set and retrieved using functions (InputEvent.get_device() and InputEvent.set_device(device))

I would fix this by making InputEvent.device a public variable, but if I did that I would probably also want to remove get_device and set_device because they are redundant, which would be a breaking change.

We should discuss the best way to fix this case, but we should probably also talk about how we will generically solve the "serializing/deserializing getters and setters" class of problems.

Semi-related question: Are there guidelines for when member variables should be hidden behind getters and setters in the godot codebase?  In the case of "device", get_device() just reads InputEvent.device and set_device(device) just writes to InputEvent.device.  Why does InputEvent.device need getters and setters, but public member variables like InputEvent.pressed don't?

**Steps to reproduce:**
1. map non-zero joypad in "Input Map" screen
2. save project 
3. reopen project
4. observe that the mapping is saved, but the device number is set to zero

**Comment by bojidar-bg** [comment]
Can confirm with 00e5ba314393ce2cc4df883bc1742306007ed117 (yesterday build, I think).

**Comment by mcanders** [comment]
Looks like @bojidar-bg discovered that  the problem is that "device" is not registered as a property, not that it isnt a public member variable.  I should have a looked at variant_parser.cpp a little closer.  

@bojidar-bg: sorry if i lead you astray 😄.  It looks like you've got this!

**Comment by bojidar-bg** [comment]
@mcanders Don't worry, I ignored what you wrote the moment I read it 😃

**Comment by mcanders** [comment]
That is usually a wise choice :)
