### ISSUE TITLE
Connecting a signal to an already existing function in editor causes a C++ error

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#92995]
_Edit: The connecting doesn't fail, it just prints the error._

### Tested versions

- Reproduces in v4.3.beta1.official [a4f2ea91a]
- Doesn't reproduce in v4.3.dev6.official [89850d553]

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

When a signal is connected to an already existing function and there's no undo history, the following error is printed in the output:

```
scene/gui/text_edit.cpp:3905 - Condition "undo_stack.is_empty()" is true.
```

### Steps to reproduce

Open MRP in editor and try to connect any signal to the `do_something()` function.

### Minimal reproduction project (MRP)

[undo-stack-is-empty.zip](https://github.com/user-attachments/files/15777208/undo-stack-is-empty.zip)

**Comment by jsjtxietian** [comment]
For me the connection seems to succeed despite the error printed.

It seems the regression comes from https://github.com/godotengine/godot/pull/86978, in `add_callback` , it uses `end_complex_operation` which will err fail if `TextEdit` has no `undo_stack`

**Comment by anniryynanen** [comment]
> For me the connection seems to succeed despite the error printed.

Oo... you're right. Good to know it's not as bad as I thought. I'll edit the issue.

**Comment by akien-mga** [comment]
CC @kitbdev
