### ISSUE TITLE
Adding button shortcut using Mouse Input doesn't work.

### ISSUE THREAD

**Issue by conde2** [godotengine/godot#93001]
### Tested versions

v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Trying to bind a shortcut that is a mouse input doesn't call Pressed event in the Button Node.

![image](https://github.com/godotengine/godot/assets/2137569/d3601a36-1cd7-4c7b-b694-2d897ad9ce93)

I tried binding an action and after binding directly the InputEventMouseButton, none of them worked.

![image](https://github.com/godotengine/godot/assets/2137569/629512d0-88e4-447a-aecf-6e1ed5b5dd49)

### Steps to reproduce

Just add a shortcut to a button and bind the action as any mouse input (Left click, middle button etc)

The button pressed event will not be called.

### Minimal reproduction project (MRP)

[test-mouse.zip](https://github.com/user-attachments/files/15779299/test-mouse.zip)

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/90516

**Comment by conde2** [comment]
The mentioned issue is definitely related. Should we keep the conversation in the other issue or should I wait it to be tested here first?

**Comment by AThousandShips** [comment]
If it matches what you're experiencing we can focus the conversation there, but if you're unsure we can keep it open and someone else can confirm that it's either the same or something separate

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/90516.
