### ISSUE TITLE
Improve error logic when trying to import a texture larger than 16384 pixels on either axis

### ISSUE THREAD

**Issue by NoamRothschild** [godotengine/godot#93018]
### Tested versions

Any version of Godot

### System information

Windows 11 - Godot v4.2.2-stable Forward+

### Issue description

# This occurred on (v4.2.2-stable)
## When importing long images (ex. 256/35,000) godot will fail to load images (not showing any error) & instead repeat and stretch a texture for the whole image.
**The error:**
```drivers/gles3/storage/texture_storage.cpp:1118 - Condition "p_height <= 0 || p_height > 16384" is true.```

### Example:
![image](https://github.com/godotengine/godot/assets/98104540/ad34f2e4-7f1b-4d3e-a1f8-9335b3bc3efa)

### Steps to reproduce

Drop a long image into godot

### Minimal reproduction project (MRP)

[ExampleProject.zip](https://github.com/user-attachments/files/15784909/ExampleProject.zip)

**Comment by AThousandShips** [comment]
This is a hardware limitation and documented [here](https://docs.godotengine.org/en/stable/classes/class_image.html#description)

Unsure how this process could be improved however to prevent glitches and just block the import

**Comment by akien-mga** [comment]
The error is expected, as the message conveys:
```
drivers/gles3/storage/texture_storage.cpp:1118 - Condition "p_height <= 0 || p_height > 16384" is true.
```

16384 is the max texture height (and width) supported by most GPUs.

We should see how to improve the UX of reporting this issue. The error message can at least be given a user-friendly message in English, and we should make sure it appears in the editor (and ideally doesn't trigger an import failure loop).

**Comment by AThousandShips** [comment]
Meant this:
>  The maximum image size is 16384×16384 pixels due to graphics hardware limitations. Larger images may fail to import.

**Comment by Calinou** [comment]
Reopening, as we should improve the error message (or perhaps resize the image on import if it exceeds the limitation, with a warning printed).

**Comment by Calinou** [comment]
I can confirm this on 4.3.beta 8a6c1e8f5 (Linux).

However, the textures *are* successfully imported on my end (unless you use the Lossy or Basis Universal compression modes, due to WebP/Basis Universal format limitations). It's just that the output is incorrect.

It also turns out the limitation in texture height isn't 16384 pixels, at least on modern GPUs (such as NVIDIA Turing and later).

Textures import correctly if their height is 32768 pixels or lower (in both Lossless and VRAM Compressed modes). As soon as the height is 32769 pixels or more, all compression modes break.

![image](https://github.com/godotengine/godot/assets/180032/31c12f85-0ffc-444a-a7a1-17562111f667)

**Comment by NoamRothschild** [comment]
So is there anything I can do to make it work?

**Comment by akien-mga** [comment]
@NoamRothschild You need to cut the texture in smaller ones, this is a GPU limit.

**Comment by AThousandShips** [comment]
Then those engines use some other trick to accomplish this, like breaking it into smaller parts or scaling it down, behind the scenes, or some other way, because this isn't engine specific

**Comment by AThousandShips** [comment]
Again let's keep this open until we've resolved the documentation and usibility side

**Comment by Zireael07** [comment]
Which engines are "all other game engines"? Have you checked on the exact same machine?
