### ISSUE TITLE
Editor MinGW build on Windows crashes upon opening a project

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#9301]
**Operating system or device - Godot version:** Windows 10 - MinGW-w64 7.1.0 32-bit (posix, seh) - Godot Git https://github.com/godotengine/godot/commit/3c1fd26bb0c2e97b927343e5488aa6d646e2e27c

**Issue description:**
After starting the project manager (which works as expected), opening any project with Godot compiled using MinGW will cause the editor to crash. The crash does not occur immediately after clicking the "Edit" button – it occurs a few seconds later.

Note that a 64-bit MSVC 2017-based build of the same commit does not have this issue.

**Steps to reproduce:**
Add a 32-bit MinGW-w64 installation to your `PATH`, then compile Godot using `scons platform=windows tools=yes target=release_debug bits=32`, then run the project manager and edit a project.

**Comment by supagu** [comment]
This issue may also be the same issue as #9300. I've found a release_debug or release build of godot is crashing for me on linux in a very similar fashion.

**Comment by Calinou** [comment]
Seems to be fixed as of https://github.com/godotengine/godot/commit/5d85108f9448ac47b871f19c8af4652b7d3dea9d (it probably was fixed earlier, but I don't know which exact commit fixed this).

Both 32-bit and 64-bit editors compiled using MinGW-w64 7.1.0 (provided by [MSYS2](http://www.msys2.org/)) seem to function normally (editing and running a project).
