### ISSUE TITLE
Warning message about V-Sync not being supported on OpenGL is confusing

### ISSUE THREAD

**Issue by tobydjones** [godotengine/godot#93027]
### Tested versions

- Reproducible in Godot Engine v4.2.2.stable.mono.official [15073afe3] on Ubuntu/Xfce

### System information

Ubuntu 22.04.4 LTS / Xfce 4.16

### Issue description

I am running Godot on a Ubuntu VM on Azure. I am connecting from a Windows PC using RDP.

While using Godot I get this warning:
`platform/linuxbsd/x11/gl-mananger_x11.cpp:374 - Could not set V-Sync mode. V-Sync is not supported`
As I'm running a VM on RDP, this is correct, but it repeats every few minutes, which is irritating.

To stop the warning, I set `Project > Project Settings > Display > Window > V-Sync Mode` to `Disabled`, but this does not work.
I also get the warning if I start godot from a terminal with `godot --disable-vsync`

I asked about this problem [here](https://forum.godotengine.org/t/turning-off-v-sync-doesnt-stop-v-sync-is-not-supported-warning/65090) and "njamster" suggested:

> Sounds like a bug to me. The warning is stemming from [here](https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/platform/linuxbsd/x11/gl_manager_x11.cpp#L344), where it will be issued no matter what value p_use is provided.

ie `godot/platform/linuxbsd/x11/gl_manager_x11.cpp`, line 344, `void GLManager_X11::set_use_vsync(bool p_use)`

### Steps to reproduce

Run Godot on a Ubuntu VM using Xfce and connect from a Windows PC via RDP

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
> The warning is stemming from [here](https://github.com/godotengine/godot/blob/96a386f3c424af96d950ee5098b4b0e4907c9508/platform/linuxbsd/x11/gl_manager_x11.cpp#L344), where it will be issued no matter what value p_use is provided.

To be fair, the warning *is* correct but poorly worded. *Changing* V-Sync mode is not supported if none of the calls succeed, but V-Sync itself may be forced by the OS.

**Comment by synkarius** [comment]
I get this same message in WSL Ubuntu 22.04.

**Comment by tobydjones** [comment]
> To be fair, the warning _is_ correct but poorly worded. _Changing_ V-Sync mode is not supported if none of the calls succeed, but V-Sync itself may be forced by the OS.

I don't want to change V-Sync. I only disabled it to try to stop the warning.

There are three issues: I don't understand the warning, I can't do anything about it, and seeing it repeatedly is annoying.

So, it seems two steps are needed to fix this issue:
1. Change the warning so it is better worded.
2. Either let me silence the warning, or only show the warning once, on startup.

**Comment by Calinou** [comment]
We can change the warning to `WARN_PRINT_ONCE()` at least, so it can only be printed once per session.
