### ISSUE TITLE
Meshlib creation popup content is misaligned

### ISSUE THREAD

**Issue by dominiks** [godotengine/godot#93024]
### Tested versions

v4.3.beta.custom_build [62a056aa5]

### System information

Godot v4.3.beta (62a056aa5) - openSUSE Tumbleweed

### Issue description

Exporting a scene as a meshlib opens a popup to show progress while preview images are generated. In 4.3 the content of the popup is not centered but left aligned.

![grafik](https://github.com/godotengine/godot/assets/109005/d4f2e252-7e65-4b2b-b373-349ecd1bb647)

### Steps to reproduce

Create scene with (many) meshes inside, Go to Scene->Export->Meshlib and export as meshlib.

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92971

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
