### ISSUE TITLE
Particles2D: Explosivness = 0 and Emit Timeout <= Lifetime - never emit

### ISSUE THREAD

**Issue by splite** [godotengine/godot#9302]
**Operating system or device - Godot version:**
Windows 10
Godot 2.1.3 - stable (current steam version)

**Issue description:**
When i set `Particles2D.Explosivness` to 0 (for some reason, any other value work, see workaround) and `Emit_Timeout` to <= `Lifetime`, emitter will not produce any particles when you call `set_emitting(true)`  (with exception of calling directly from `_ready()`)

**Steps to reproduce:**
- add Particles2D node
  - set `Lifetime` to x (lets say 3)
  - set `Explosiveness` to 0
  - set `Emit_Timeout` to anything <= x (let say 3 so `Emit_Timeout` = `Lifetime` or 2.9 so `Emit_Timeout` < `Lifetime`)
- add and enable (lets say, it works as expected from `_ready()`...) `_unhandled_key_input(key_event)`
- call `get_node("Particles2D").set_emitting(true)` from script function `_unhandled_key_input(key_event)` (added in prev step) - again, NOT from `_ready()` - that works.

Btw - when i was creating minimal example project, i noticed that if you set `Emit_timeout` to any float >= `Lifetime` (in my example, lets say 3.1) it looks like it start AFTER `Emit_Timeout` (3.1 sec) and i have strong feeling that it is related.

**Link to minimal example project:**
quick and dirty example: [buggy_emit.zip](https://github.com/godotengine/godot/files/1091268/buggy_emit.zip) - press space to emit.

**Workaround:**
Set Explosivness to 0.01 (difference is unnoticeable)

**Comment by homer666** [comment]
Yeah, I'm getting this too.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by splite** [comment]
We dont have `Emit_Timeout` anymore...
