### ISSUE TITLE
Akien was supposed to be on vacations

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9303]
**Operating system or device - Godot version:** all versions

**Issue description:**
Akien was supposed to be on vacation, but he still shows up in godot meetings, IRC and comments on issues. This is a serious case of godot-addiction (godotitis in medical terms)

**Steps to reproduce:**
1. send Akien on vacation
2. notice that he is still around

**Comment by groud** [comment]
Have you tried to compile with clang instead of gcc ?

**Comment by bojidar-bg** [comment]
I think we should use jQuery for this anyway.

**Comment by StraToN** [comment]
Does this happen on every Linux flavour ?

**Comment by Noshyaar** [comment]
Duplicate of #8524

**Comment by Zylann** [comment]
@StraToN no it happens on Windows too. I tried to update my browser and graphics driver but he keeps appearing.

**Comment by groud** [comment]
@Zylann have you tried to delete System32 ?

**Comment by Shockblast** [comment]
> This is a serious case of godot-addiction (godotitis in medical terms)

There is no cure or any medication for that.

**Comment by bojidar-bg** [comment]
@Shockblast I've heard that limiting the amount of vacations would cover up the symptoms though.

**Comment by karroffel** [comment]
![image](https://user-images.githubusercontent.com/5209613/27392849-070bce28-56a8-11e7-893b-1e46cdb877e7.png)

credit @sheepandshepherd

**Comment by karroffel** [comment]
I cannot reproduce as I don't have enough money. 

Maybe someone with enough money can send him on a vacation and post the billing details here so we can figure out what's wrong.

**Comment by nunodonato** [comment]
@karroffel #9044 would solve these kind of problems. we need to discuss this!

**Comment by punto-** [comment]
Does it happen with all of his repos? maybe he's just a workaholic (or
maybe he knows we're hopeless without him :p )

**Comment by reduz** [comment]
Just push Akien on vacation directly to master

**Comment by gamergamesz** [comment]
😂😂😂

**Comment by akien-mga** [comment]
> I cannot reproduce as I don't have enough money.

Flagging this as adult-only content for our younger readers.

**Comment by MarianoGnu** [comment]
I don't expect this to happen soon, actually

**Comment by nunodonato** [comment]
Closing to boost our progress stats, more closed issues, yay!!
(also, Akien is back from vacations, so.... :P )

**Comment by aaronfranke** [comment]
This issue has shown up again today. It's very hard to reproduce though as it's quite uncommon, so keeping this closed.

**Comment by aaronfranke** [comment]
We've finally solved the issue, we had a big meeting with dozens of maintainers and there was no Akien in sight.
