### ISSUE TITLE
Completion does not always add StringNames when it should

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#93034]
### Tested versions

4.3 beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

From #66481

https://github.com/godotengine/godot/assets/2223172/d1dca573-3af7-4ba2-a29e-b0ef7c5f9bd2

Seems like some methods use a different autocompletion type.

### Steps to reproduce

0. Enable `text_editor/completion/add_string_name_literals` editor setting
1. Add `_input()` method in a script
2. Do `event.is_action(`
3. Notice how it suggests a plain String

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
CC @MewPurPur @HolonProduction
