### ISSUE TITLE
Editor settings tooltips have a huge bottom margin with compact spacing preset

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#93031]
### Tested versions

Reproduces in:
- v4.3.beta1.official [a4f2ea91a]
- v4.3.dev6.official [89850d553]

Doesn't reproduce in:
- v4.3.dev5.official [89f70e98d]

### System information

Windows 10.0.22631 - GLES3 (Compatibility) - AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24033.1003) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

![huge-bottom](https://github.com/godotengine/godot/assets/8843118/4e0cb412-59c7-4205-8d4f-c757decbd62e)

### Steps to reproduce

- Open editor settings
- Go to Interface -> Theme
- Select "Compact" in the spacing preset dropdown
- Hover a setting label, for example the "Spacing Preset" text

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Confirmed on Linux (Fedora 40, KDE) in 4.3.beta1 and 4.3.beta (a7aa8356b9288fb6de1cef2980465703c63102ea).
