### ISSUE TITLE
Ruler tool stuck after right click

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#93043]
### Tested versions

4.3 beta1 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/85199fc5-ee42-434d-9797-84aa957efd4d

### Steps to reproduce

1. Go to 2D editor and enable ruler tool (R)
2. Start measuring by holding LMB
3. While still holding the button, right-click to open context menu
4. Left click to close the menu
5. The ruler is still visible despite no buttons pressed

### Minimal reproduction project (MRP)

N/A

**Comment by MannyFluss** [comment]
would this be a good issue to try and solve for a first time contributor?

**Comment by KoBeWi** [comment]
I think the fix simply involves handling and accepting right-click event while using ruler tool, so it *should* be good.

**Comment by MannyFluss** [comment]
cool, ill give it a swing tomorrow thanks

**Comment by MannyFluss** [comment]
I haven't been able to solve it, the right click input is filtered out before it reaches the ruler function.

first I tried adding in the right click event here

`
bool CanvasItemEditor::_gui_input_ruler_tool(const Ref<InputEvent> &p_event) {
	if (tool != TOOL_RULER) {
		ruler_tool_active = false;
		return false;
	}

	Ref<InputEventMouseButton> b = p_event;
	Ref<InputEventMouseMotion> m = p_event;

	Point2 previous_origin = ruler_tool_origin;
	if (!ruler_tool_active) {
		ruler_tool_origin = snap_point(viewport->get_local_mouse_position() / zoom + view_offset);
	}
        // this never gets activated ever
	if (b.is_valid() && b->get_button_index() == MouseButton::RIGHT) {
		if (b->is_pressed()) {
			print_line("right click pressed");
		}
	}

	if (b.is_valid() && b->get_button_index() == MouseButton::LEFT) {
		if (b->is_pressed()) {
			ruler_tool_active = true;
		} else {
			ruler_tool_active = false;
		}

		viewport->queue_redraw();
		return true;
	}

	if (m.is_valid() && (ruler_tool_active || (grid_snap_active && previous_origin != ruler_tool_origin))) {
		viewport->queue_redraw();
		return true;
	}

	return false;
}
`

then I realized that the input may have been getting filtered out here

`void CanvasItemEditor::_gui_input_viewport(const Ref<InputEvent> &p_event) {
	bool accepted = false;

	Ref<InputEventMouseButton> mb = p_event;
	bool release_lmb = (mb.is_valid() && !mb->is_pressed() && mb->get_button_index() == MouseButton::LEFT); // Required to properly release some stuff (e.g. selection box) while panning.
	// I added in this, but this also never is true
	bool release_rmb = (mb.is_valid() && !mb->is_pressed() && mb->get_button_index() == MouseButton::RIGHT);
	if (release_rmb){
		print_line("detected right click thing");
	}

	if (EDITOR_GET("editors/panning/simple_panning") || !pan_pressed || release_lmb || release_rmb) {
		accepted = true;
		if (_gui_input_rulers_and_guides(p_event)) {
			// print_line("Rulers and guides");
		} else if (EditorNode::get_singleton()->get_editor_plugins_over()->forward_gui_input(p_event)) {
			// print_line("Plugin");
		} else if (_gui_input_open_scene_on_double_click(p_event)) {
			// print_line("Open scene on double click");
		} else if (_gui_input_scale(p_event)) {
			// print_line("Set scale");
		} else if (_gui_input_pivot(p_event)) {
			// print_line("Set pivot");
		} else if (_gui_input_resize(p_event)) {
			// print_line("Resize");
		} else if (_gui_input_rotate(p_event)) {
			// print_line("Rotate");
		} else if (_gui_input_move(p_event)) {
			// print_line("Move");
		} else if (_gui_input_anchors(p_event)) {
			// print_line("Anchors");
		} else if (_gui_input_select(p_event)) {
			// print_line("Selection");
		} else if (_gui_input_ruler_tool(p_event)) {
			// print_line("Measure");
		} else {
			// print_line("Not accepted");
			accepted = false;
		}
	}
`

but the right click input never reaches this point either, so I looked one more step up

`
viewport = memnew(CanvasItemEditorViewport(this));
viewport_scrollable->add_child(viewport);
viewport->set_mouse_filter(MOUSE_FILTER_PASS);
viewport->set_anchors_and_offsets_preset(Control::PRESET_FULL_RECT);
viewport->set_clip_contents(true);
viewport->set_focus_mode(FOCUS_ALL);
viewport->connect(SceneStringName(draw), callable_mp(this, &CanvasItemEditor::_draw_viewport));
viewport->connect(SceneStringName(gui_input), callable_mp(this, &CanvasItemEditor::_gui_input_viewport));
viewport->connect(SceneStringName(focus_exited), callable_mp(panner.ptr(), &ViewPanner::release_pan_key));
`
Don't really know what any of this means, this is where I have currently given up. Ill probably try again tomorrow. My guess is that the pop up for creating the add node button is blocking the right mouse button input from reaching anything else. let me know if you have any suggestions.

**Comment by KoBeWi** [comment]
The menu is spawned here
https://github.com/godotengine/godot/blob/680e489189796af2c34f06df49e19b17dec5c6fc/editor/plugins/canvas_item_editor_plugin.cpp#L2363
The condition could check if left button is not pressed.

**Comment by MannyFluss** [comment]
hahaha I finally got it, I have never been so proud for writing like 3 lines of code, I had to make the ruler tool higher input check higher was the main culprit

**Comment by KevinSailema** [comment]
@MannyFluss Hello, congratulations for fixing the error, I wanted to ask you, once the error is fixed, how do you check the executable and verify?

**Comment by MannyFluss** [comment]
> @MannyFluss Hello, congratulations for fixing the error, I wanted to ask you, once the error is fixed, how do you check the executable and verify?

I was just recompiling the exe and and then testing my changes (which I am pretty sure is a naive way of testing changes), is there a better way to test?

**Comment by KevinSailema** [comment]
Thanks for the information, I was just asking to know what method is used, I also thought about that genuine method, since I am still a newbie I thought there was some other faster way to try it

**Comment by MannyFluss** [comment]
Im guessing there is, I know about unit tests but I have never written them before and dont know how to use them. To compile takes 30 seconds for me on my computer so im sure there has to be a better way.

**Comment by KoBeWi** [comment]
30 seconds is a normal time for subsequent compilations. With C++ there is no better way.

**Comment by MannyFluss** [comment]
on my macbook it was a 6 second for subsequent compiles which was cool. Is there a way to make it so that you dont have to close and reopen the godot instance between compiles?

**Comment by KoBeWi** [comment]
No.

**Comment by Calinou** [comment]
> on my macbook it was a 6 second for subsequent compiles which was cool. Is there a way to make it so that you dont have to close and reopen the godot instance between compiles?

You could get faster iteration times by configuring your IDE to compile Godot after you save a file (and restart SCons first if a build is already ongoing), so you don't need to manually hit a keyboard shortcut to do this.

We don't have documentation on doing this, but it would be worth looking into for sure.
