### ISSUE TITLE
Calling method from Resource-derived class cause error in @tool script

### ISSUE THREAD

**Issue by ndbn** [godotengine/godot#93045]
### Tested versions

4.2.2
4.3.beta1

### System information

Windows10 x64

### Issue description

Calling method declared in Resource - derived class not available in `@tool` script.
For example:
`test_func_call.gd`:
```gdscript
extends Resource
class_name TestFuncCall

@export var a: float

@export var b: float

func get_diff()->float:
  return a - b
```

`Test .tres file`
![image](https://github.com/godotengine/godot/assets/2904562/61e04405-bc6e-4419-b6db-b352350c550d)

`Test scene script`
```gdscript
@tool
extends Node3D


@export var test: TestFuncCall


func _ready() -> void:
  print(test.get_diff())
```

when scene with this script opened in editor (or run with F5/F6) output has error:
`res://TestScene.gd:9 - Invalid call. Nonexistent function 'get_diff' in base 'Resource (TestFuncCall)'.`
![image](https://github.com/godotengine/godot/assets/2904562/21149519-a006-4403-a861-83711d385ec9)

But without `@tool` result will printed.
![image](https://github.com/godotengine/godot/assets/2904562/a5c40fd2-a9e0-4540-b992-2970e5ae265a)

### Steps to reproduce

MRP

### Minimal reproduction project (MRP)

[test_method_call_resource.zip](https://github.com/user-attachments/files/15792702/test_method_call_resource.zip)

**Comment by KoBeWi** [comment]
Your Resource also needs `@tool`.

**Comment by ndbn** [comment]
> Your Resource also needs `@tool`.

It works. 

But not obviously requirement, IMO

**Comment by KoBeWi** [comment]
Yeah this is already tracked by #36592
Closing.

**Comment by AThousandShips** [comment]
Note that `@tool` isn't required in the running project, but it is required if called from within the editor, and in this case it likely gets called on reloading the scene or on save due to the scene being reinitialized or similar, so it looks like the error comes not from the running game but the editor itself *when* running due to this, specifically because it's in `_ready`

**Comment by ndbn** [comment]
> Note that `@tool` isn't required in the running project, but it is required if called from within the editor, and in this case it likely gets called on reloading the scene or on save due to the scene being reinitialized or similar, so it looks like the error comes not from the running game but the editor itself _when_ running due to this, specifically because it's in `_ready`
> 
> So make sure you always use tool with tool, or don't use it if you don't want/expect it to run in the editor

Thank you for explanation, I understand that it not required, but documentation explain `@tool` like for run some specific functions, like _ready, _process, etc. I use it to dynamically build scene based on resource, it very handy in my case.
Anyway all scripts parsed and tokenized(for language server for ex.), it seems (for me) like it only in-code restriction(calling method from not tool-annotaded script), becouse even if you call something like `print(test.get_method_list())` the "Nonexistent function" will exists in print result.
