### ISSUE TITLE
Scrolling up & down in the in-editor Documentation is not smooth

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#93053]
### Tested versions

- Reproducible in 4.3.beta1, but I think it's actually in all Godot 4.x versions

### System information

Godot v4.3.beta1 - TUXEDO OS 3 22.04.4 - Wayland - Vulkan (Forward+) - integrated Intel(R) Graphics (RPL-P) () - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

The code editor and documentation screens have different scroll smoothing.
The code editor is very smooth and feels nice.
Scrolling in a builtin documentation page however feels heavier, and jumps by around 4 lines at each mouse scroll.

### Steps to reproduce

- Open a `.gd` script big enough to scroll, and then scroll up & down using the mouse. It's smooth.
- Press `F1`, and open any documentation big enough, then scroll up & down using the mouse. It feel a bit more sluggish, and jumpy. There is no smoothness.

In isolation, it might have not been noticeable, but those 2 types of screens (code editor and documentation pages), share the same spot in the window, and usually you have to jump from one to the other quickly when typing some code. This makes the lack of smoothness in the documentation quite noticeable

### Minimal reproduction project (MRP)

No need. This is related to the built-in documentation editor.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/5386.

**Comment by kitbdev** [comment]
- related https://github.com/godotengine/godot-proposals/issues/5386
