### ISSUE TITLE
Texture3D node in shader editor creates a Shader Parameter

### ISSUE THREAD

**Issue by ThePywon** [godotengine/godot#93051]
### Tested versions

- Reproductible in: v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.5212) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

Texture3D node in shader editor, when affecting the final shader output will create a parameter for materials using that shader that have to be set manually. This behavior is not consistent with the Texture2D node of the shader editor.

### Steps to reproduce

Create a visual shader and open the shader editor.
Create a Texture3D node in the shader editor and assign it a texture (the texture doesn't matter).
Connect the Texture3D node to the albedo output.
Create a ShaderMaterial resource and assign it the shader.
Under Shader Parameters will be a parameter named something similar to say "Tex 3d Frg 2" that is unset by default despite the shader editor's values.

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Looks like tex3d has a null default texture here:

https://github.com/godotengine/godot/blob/292e50e17e3f6e2509d3178a00204f964a907460/scene/resources/visual_shader.cpp#L2886-L2890

and in `Shader::get_shader_uniform_list`, if it doesn't have a default texture, the property will show in the inspector.

**Comment by Chaosus** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/95126

**Comment by ThePywon** [comment]
The issue can still be reproduced in v4.3.stable.official [77dcf97d8]
