### ISSUE TITLE
set() or object assignment looks for more specific type than returned by typeof()

### ISSUE THREAD

**Issue by za3k** [godotengine/godot#93067]
### Tested versions

Found in Godot 4.2.2.

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 - Tty - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (nvidia; 550.78) - Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz (24 Threads)

### Issue description

I'm filing a usability bug. I think everything below is working as designed, I'm just running into some problems with parts of the design being inconsistent, and it making Godot less usable in practice.

---

When using: `self[k] = v`, it appears the type has to match exactly. Not just `Array`, but `Array[int]`. That's fine.

However, there doesn't seem to be an easy way to actually do the conversion, because `typeof()` returns only the Variant.Type `Array`, and `type_convert()` also looks only at Variant.Type. So if you start with untyped data, which you perhaps know the type of, I'm not sure of a way to add typing information. This is a usability bug.

Below is a short reproduction case of the issue. (For this sample code, it's also relevant that you can't annotate the types of individual dictionary values.)

Note that for the related built-in function `set()`, the same failure happens. Instead of a user-visible error, typed Array values are silently skipped (when assigned value is of type `Array`), which is the original bug I dug into.

Ideally, I would like the final reproduction code to work, whether because the []= operator becomes more permissive about typed arrays, or the convert() operator starts accepting more specific types.

    self["cannot_be_set"] = type_convert(constants["cannot_be_set"], typeof(self["cannot_be_set"]))

Also relevant:
- https://github.com/godotengine/godot/pull/71336
- https://github.com/godotengine/godot-proposals/discussions/7364 (**Edit**: Note that this report will remain a usability bug even after the addition of typed array constructors, because in this case the type is not hardcoded, and `typeof()` does not return it.)

### Steps to reproduce

```
extends Node2D

var can_be_set : int
var cannot_be_set : Array[int]

var constants = {
	"can_be_set": 1,
	"cannot_be_set": [2, 3, 4],
}

func _ready():
	# Works
	self["can_be_set"] = constants["can_be_set"]
	
	# Fails
	self["cannot_be_set"] = constants["cannot_be_set"]
	
	# Fails
	var t1 := typeof(cannot_be_set)
	self["cannot_be_set"] = type_convert(constants["cannot_be_set"], t1)

	# Fails
	var t2 := typeof(self["cannot_be_set"])
	self["cannot_be_set"] = type_convert(constants["cannot_be_set"], t2)
```

### Minimal reproduction project (MRP)

[bug-repro.zip](https://github.com/user-attachments/files/15796826/bug-repro.zip) same code as above

**Comment by dalexeev** [comment]
> I'm filing a usability bug. I think everything below is working as designed, I'm just running into some problems with parts of the design being inconsistent, and it making Godot less usable in practice.

This tracker is intended for engine or documentation bugs. If you want to propose a new feature or change to functionality that works as designed, please use [godot-proposals](https://github.com/godotengine/godot-proposals) instead.

You raised several questions at once:

1. Type casting when assigning a typed variable, passing a typed argument to a function, and so on. Some types are implicitly convertible (like `int` and `float`), some require an explicit cast/conversion.
2. Array literals (`[]`) are untyped by default, but in a typed context they are implicitly converted to typed arrays. There is no convenient typed array constructor, however you can use `[] as Array[int]` or `Array([], TYPE_INT, &"", null)`.
3. Lack of a unified type system; you cannot explicitly cast a value to a type regardless of its kind (built-in types, native and custom classes, typed arrays).

However, I think all these questions are already known, documented or being discussed:

* [Class reference - Array](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-constructor-array)
* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* godotengine/godot-proposals#7364
* #54311 
* #72627
* #21789
* godotengine/godot-proposals#6502
* And other closed issues.

**Comment by za3k** [comment]
> This tracker is intended for engine or documentation bugs. 

That is fair, we can close this if it doesn't feel "bug-like" enough.

> If you want to propose a new feature or change to functionality that works as designed, please use [godot-proposals](https://github.com/godotengine/godot-proposals) instead.

I'm not sure I'm knowledgeable enough to make a proposal for a change myself. That might have to wait a year. (For example, I wasn't even aware of the `as` keyword--I'm a total newbie.)

If there was a place to add use-cases in the context of discussion I would do that, but there's not. I do think there are some minor additions here. This is the first request I've noticed for "convert to the same as" or of wanting a function to return the GDScript type of an array. Most of the other requests are using hardcoded types. Other than that, I would agree that the individual components have been discussed.

I don't feel I'm educated enough to request a specific right solution to this problem, and I agree this isn't a pressing specific bug, so I'll close it.
