### ISSUE TITLE
Dictionary suggests its methods in `[]` autocompletion

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#93062]
### Tested versions

4.3 beta1
I don't remember it happening before.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/043ca345-1edd-467f-a1a9-e90aa785f5a4)
The `[]` operator can be used on Object to access its properties and methods (as Callables), and apparently Dictionary is treated the same way.

### Steps to reproduce

1.
```GDScript
var d: Dictionary
d["
```
2. Put caret after `"` and press Ctrl+Space

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Actually this happens since 4.0 alpha 1, at least in alpha 1 the autocompletation show the keys, because between 4,0 alpha 1 and 4,0 beta 1 something changed and now only show the dictionary methods

![image](https://github.com/godotengine/godot/assets/44306054/9b54a634-74d5-48e5-b0d0-0cb464a67b8e)

**Comment by akien-mga** [comment]
Related to https://github.com/godotengine/godot/issues/76955 and https://github.com/godotengine/godot/pull/79378.

**Comment by KoBeWi** [comment]
Showing known keys is expected, showing methods is not, because they can't be accessed this way.
