### ISSUE TITLE
Inspector dropdowns may require scrollbars in some cases

### ISSUE THREAD

**Issue by jmf** [godotengine/godot#9306]
**Operating system or device - Godot version:**
Linux 4.11.3, Godot 3c1fd26bb0c2e97b927343e5488aa6d646e2e27c

**Issue description:**
Some dropdowns in the Inspector are too long and should get a scrollbar or scroll feature to work correctly.
Scrolling would be needed to confirm #7278.

**Steps to reproduce:**
* Add a Node
* Add the script as shown in the screenshot
* Select the node and click on the dropdown shown in the screenshot
* The list is too long, it exceeds the screen

![The list is too long](https://lut.im/vGmJs89NoQ/EmcmiA5YFfixKcmV.png)

**Comment by toger5** [comment]
It might even be a good idea to create a popup. like the nodes popup for all resources...
The list just makes no sense for that many options. searching is a necassity anyways and than it is much easier to make a popup instead of improving the dropdown with a scrollbar.

**Comment by bojidar-bg** [comment]
@toger5 It should fallback to popup only when the list has too much (say, more than 10) items.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by jmf** [comment]
The list can now be scrolled with mouse wheel so the bug isn't relevant any more.
