### ISSUE TITLE
UI responsiveness delay in multiple native windows

### ISSUE THREAD

**Issue by jx3openplayer** [godotengine/godot#93071]
### Tested versions

- Reproduced in 4.3.beta1
- Works fine in 4.3.dev6

### System information

Windows11

### Issue description

4.3.beta1 creates multiple windows in the scene and uses the Windows native window style (not embedded). When switching between windows, the UI response inside has serious delays. The game's frame rate is normal, but the UI response is unacceptably slow.
This problem does not exist in 4.3.dev6.

### Steps to reproduce

https://github.com/godotengine/godot/assets/160569414/2df322ca-4819-445c-8765-085cc85c40fe

1. As shown in the video, when only one window A is opened, the hover event of the button in the new window responds very sensitively. 
2. Then open window B, and you can see that the hover of the button in window B is a bit slow. 
3. Finally, switch back to window A, and you can see that the hover switching becomes very slow.

In the actual project, if more UI controls are included, the delay will reach more than ten seconds.

### Minimal reproduction project (MRP)

[window_bug.zip](https://github.com/user-attachments/files/15799505/window_bug.zip)

**Comment by Chaosus** [comment]
cc @bruvzg

**Comment by matheusmdx** [comment]
Can you take a look this comentary (https://github.com/godotengine/godot/issues/92954#issuecomment-2158618652) and do the mentioned test to check if your issue is the same?

**Comment by dicarne** [comment]
> Can you take a look this comentary ([#92954 (comment)](https://github.com/godotengine/godot/issues/92954#issuecomment-2158618652)) and do the mentioned test to check if your issue is the same?

The PR mentioned there can fix this issue!

**Comment by jx3openplayer** [comment]
yes, it solved!
