### ISSUE TITLE
Dragging mouse to select text in script editor may randomly change selection range and trigger drag

### ISSUE THREAD

**Issue by alvinhochun** [godotengine/godot#93078]
### Tested versions

- Reproducible in: 4.3 (5241d30 GHA Windows editor), 4.3 (2fb296a GHA Windows editor)
- Not reproducible in: 4.3 beta1 (Windows editor), 4.3 (a4f2ea9 GHA Windows editor)

### System information

Windows 10 - Godot v4.3.beta (5241d30bf)

### Issue description

When dragging the mouse cursor in the script editor from outside selected text (or when there isn't a text selection), sometimes (seemingly randomly) the selection range will suddenly extend to the mouse down location and initiates an unwanted drag operation. This happens without touching any keyboard keys.

[capture.webm](https://github.com/godotengine/godot/assets/2397650/6f5354ce-df5c-4f00-af14-f76f867d3b54)

### Steps to reproduce

1. Open a script
2. Keep using the mouse to select ranges of text
3. Sometimes also include clicking to cancel text selection

### Minimal reproduction project (MRP)

N/A

**Comment by AeioMuch** [comment]
Bisected https://github.com/godotengine/godot/pull/92424 as the first bad commit.

**Comment by kitbdev** [comment]
I can't reproduce (Godot v4.3.beta (475248d99) - Windows 10.0.22631 - Vulkan (Forward+)).
But it looks like TextEdit is receiving mouse unpressed and pressed notifications when you didn't actually release the mouse button.
Does this also affect actions like panning or selecting in the scene view or is it only the script editor?

**Comment by alvinhochun** [comment]
> Bisected #92424 as the first bad commit.

Thanks for bisecting. I suspect it is because the patch uses [`GetAsyncKeyState`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate) instead of [`GetKeyState`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate). Hypothetically, if one press the mouse button while moving the cursor, the window could be receiving these messages (pseudo code):

1. MouseMove, buttons=None, xy=(100, 100)
2. MousePress(Left), buttons=LeftMouse, xy=(101, 101)
3. MouseMove, buttons=LeftMouse, xy=(102, 102)

When the application processes the first message, it is possible that the user has already pressed the mouse button so `GetAsyncKeyState(VK_LBUTTON)` may indicate the mouse button is pressed, different from what the message represents. More importantly it would indicate the mouse button being held down before the MousePress message had been processed. If the control relies on the MousePress message to initialize states related to text selection, it could explain the bug. (This is just a hypothesis -- I haven't checked what is happening within Godot.)

I think it really should use `GetKeyState` instead.

---

> I can't reproduce [...]. But it looks like TextEdit is receiving mouse unpressed and pressed notifications when you didn't actually release the mouse button. [...]

In my capture, when the selection stops changing I definitely released the left mouse button. If my hypothesis above is correct, then the key point is that the mouse must be moving when pressing the mouse button to reproduce the bug.

If you really need to verify, I can make a capture with an OSD showing the mouse buttons (though I don't currently have a tool for this so I'll need to hunt for one).

**Comment by KoBeWi** [comment]
Can confirm in v4.3.beta.custom_build [475248d99]
Windows 10.0.19045

**Comment by kitbdev** [comment]
I misunderstood earlier, I can reproduce it now while moving the mouse.

Adding logpoints show that a mouse motion event with the left mouse button down is being sent before the mouse pressed event.

![image](https://github.com/godotengine/godot/assets/10054226/662402f3-199e-4838-a7f7-a5389f75593e)

Created a PR https://github.com/godotengine/godot/pull/93105 that uses GetKeyState as suggested.
