### ISSUE TITLE
TextEdit border style doesn't work and corner radius doesn't do anything

### ISSUE THREAD

**Issue by hhyyrylainen** [godotengine/godot#93081]
### Tested versions

- Reproducible in 4.2.2.stable.mono
- If I remember right, this *may* have worked in 3.x, but I'm not sure. I do remember first noticing this problem when porting my project from 3 to 4 and fixing up the theme. I was able to fix every other theme element except this.

### System information

Godot v4.2.2.stable.mono - Fedora Linux 40 (Workstation Edition) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) () - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Trying to apply a style with borders to a TextEdit seems to do nothing. The background colour applies, but border doesn't. 

Here's how the TextEdit looks with the theme editor having a stylebox with borders set on it:

![kuva](https://github.com/godotengine/godot/assets/3796411/9c4a6790-3f36-4083-a568-a8ae7a3ebb71)

I tried to look for existing issues but I didn't find any exactly about this, I only found these kind of related problems with TextEdit styling:
- https://github.com/godotengine/godot/issues/74445
- https://github.com/godotengine/godot/issues/59639
- https://github.com/godotengine/godot/issues/29163

### Steps to reproduce

- Create a theme and add a new StyleBoxFlat for `normal` in TextEdit
- Try to specify a border width, corner radius, and border colour
- Observe how the style does not apply for some reason, and how the same stylebox works for example with LineEdit

### Minimal reproduction project (MRP)

Here's my exact theme file in case it matters: https://github.com/Revolutionary-Games/Thrive/blob/a83a0d0a3211b07f9968adca63fd86b32f74fc19/src/gui_common/thrive_theme.tres

**Comment by kitbdev** [comment]
Your TextEdit theme color `theme_override_colors/background_color` is set to full opacity black, this is covering the StyleBox. You can remove the override or set the opacity to 0, the border should work.

**Comment by hhyyrylainen** [comment]
Thank you so much. That was exactly the case and removing that style part made the stylebox work. I had tried the exact same stylebox on a LineEdit and that worked fine, which is why I opened this issue. Interestingly it looks like that background color property doesn't even exist for a LineEdit so it is a TextEdit specific feature for some reason.

**Comment by MattParkerDev** [comment]
@kitbdev how are you meant to set the background color of the TextEdit then? Without covering the border?

Edit: Nvm, I overrode the Normal Style and that worked.
