### ISSUE TITLE
Awkward gap in Create New Scene dialog

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#93088]
### Tested versions

4.3 beta 2fb296a
Does not appear as big in beta1

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/47d337d1-7826-490e-ba18-2a04068aecef)
Seems to come from button being big:
![image](https://github.com/godotengine/godot/assets/2223172/ceb7f2d3-06d3-4db0-a039-bdb1115ae8f9)

In beta1 the gap is also there, but noticeably smaller:
![image](https://github.com/godotengine/godot/assets/2223172/34544ae7-9070-46dc-bac9-158344e568b4)
Perfectly, the LineEdit should be aligned with above labels.

### Steps to reproduce

1. Create new scene from FileSystem dock

### Minimal reproduction project (MRP)

N/A

**Comment by passivestar** [comment]
Kind of a same problem with a checkbox here I guess:

<img width="400" alt="Screenshot 2024-06-12 at 22 03 07" src="https://github.com/godotengine/godot/assets/60579014/d4547032-87c5-437b-b8bb-b8daffb25ab2">

**Comment by KoBeWi** [comment]
Seems to be caused by #92701
