### ISSUE TITLE
Inverse lifetime draw order option for Particles/Particles2D

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9309]
**Godot version: 3**

On Particles and Particles2D, Draw order "lifetime" draws older particles first and younger particles stay on top, an option to set the inverse order as "lifetime" could be useful for emission effects that face the screen (in fact, it may be more useful than lifetime and index draw orders for general use).

**Comment by reduz** [comment]
this is pretty much impossible to do, unfortunately, because draw order is
the same of the instances, which is the same of the particle array.

**Comment by eon-s** [comment]
@reduz I see, so can only be done by a custom emitter that draws in reverse.
Killing this then.
