### ISSUE TITLE
A warning emits at opening any GLTF animated model

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#93092]
### Tested versions

4.3 dev (475248d99df89fc29032a42f1d29ad4cef49c8b5)

### System information

Windows 11

### Issue description

Opening any animated model will generate the warning:

![model_warning](https://github.com/godotengine/godot/assets/3036176/dc800149-0108-4f8b-8641-c21c69b1de4d)

With a test project, it will be:
```
scene\main\node.cpp:1573 - Adding 'Machinegunner_Body' as child to 'Skeleton3D' will make owner 'machinegunner' inconsistent. Consider unsetting the owner beforehand.
```

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

[testmodel.zip](https://github.com/user-attachments/files/15808282/testmodel.zip)

**Comment by JekSun97** [comment]
I confirm, this only happens with GLB/GLTF files

**Comment by jsjtxietian** [comment]
Looks like the warning is triggered here:

https://github.com/godotengine/godot/blob/475248d99df89fc29032a42f1d29ad4cef49c8b5/modules/gltf/gltf_document.cpp#L6330-L6332

Callstack:

```
Node::add_child(Node * p_child=0x0000021ffc6e17e0, bool p_force_readable_name=true, Node::InternalMode p_internal=INTERNAL_MODE_DISABLED) Line 1573	C++
GLTFDocument::_process_mesh_instances(Ref<GLTFState> p_state={...}, Node * p_scene_root=0x0000021fb22c8530) Line 6332	C++
GLTFDocument::generate_scene(Ref<GLTFState> p_state={...}, float p_bake_fps=30.0000000, bool p_trimming=false, bool p_remove_immutable_tracks=false) Line 7304	C++
EditorSceneFormatImporterGLTF::import_scene(const String & p_path={...}, unsigned int p_flags=74, const HashMap<StringName,Variant,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Variant>>> & p_options={...}, List<String,DefaultAllocator> * r_missing_deps=0x0000000000000000, Error * r_err=0x000000dc091fa380) Line 79	C++
ResourceImporterScene::pre_import(const String & p_source_file={...}, const HashMap<StringName,Variant,HashMapHasherDefault,HashMapComparatorDefault<StringName>,DefaultTypedAllocator<HashMapElement<StringName,Variant>>> & p_options={...}) Line 2786	C++
SceneImportSettingsDialog::open_settings(const String & p_path={...}, bool p_for_animation=false) Line 735	C++
FileSystemDock::_select_file(const String & p_path={...}, bool p_select_in_favorites=false) Line 1237	C++
FileSystemDock::_tree_activate_file() Line 1282	C++
```

**Comment by akien-mga** [comment]
This seems to be a regression introduced in 4.3-dev1 and cherry-picked to 4.2.2. It's not reproducible in 4.2 or 4.2.1.

**Comment by akien-mga** [comment]
The warning was introduced by ba23081eb758e9f4b8a5a2e10bd742bba41f04c4, but it's not a regression in the end, it's just a new warning which is now pointing out at a pre-existing bug.
