### ISSUE TITLE
NormalMaps (NORMAL) not working on Tilesets

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9310]
**Operating system or device - Godot version:**
Linux 64bit Ubuntu 16.04 - Godot 3.0 alpha commit f27d2a3355b8c577fccd961d28dd6085887623c2

**Issue description:**
When creating the tiles for a tilemap, every Sprite has a "Texture" and a "Normal Map" but the lights ignore them set on the Sprite GUI dropdowns, save teh scene and convert to Tileset

**Steps to reproduce:**
Create a new scene, create the tiles for a tilemap (Sprites), every Sprite has a "Texture" and a "Normal Map", save the scene and convert to Tileset, now use the tileset on another scene with Light2D.
The Light2D works like only the Texture is set and no Normal Map is set
Even tried creating a shaderMaterial for the tiles and setting NORMAL on the fragment, also is ignored when used as Tileset.

**Comment by rubenjavier** [comment]
@bojidar-bg @karroffel  , this is not an enhancement, materials and shaders used to work on Tilesets on v2.x, thats why I put the [3.0] on the original title

**Comment by bojidar-bg** [comment]
@rubenjavier I marked it as enhancement because it is similar to #3637. I do understand that it might be seen as a bug as well though.

The fix should be a simple one anyway...

**Comment by rubenjavier** [comment]
@bojidar-bg  got it, but retain its material like it used to, is way easier and faster to implement (and draw) than all the properties that are asked on the other issue
Thanks
