### ISSUE TITLE
Web export doesn't work correctly with binary GDScript

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#93102]
### Tested versions

4.3 Beta 1

### System information

Ubuntu 22.04

### Issue description

After exporting the game, it does not work in the browser, the console is filled with errors.

This happens randomly in different projects when editing a script.
Even adding comments to the code has an effect.

I found a solution for myself, but I think it's a mistake.

The solution is to select text GDScript when exporting.

![image](https://github.com/godotengine/godot/assets/13809475/2005bca5-e38b-4f9c-b425-d35849a23c3d)

These are the errors that go to the browser console and are repeated many times. The project itself does not respond to anything.

![image](https://github.com/godotengine/godot/assets/13809475/8c1c85ac-ae28-41d9-97d9-d7127e43de23)

### Steps to reproduce

This happens randomly in any project.

### Minimal reproduction project (MRP)

None

**Comment by Hilderin** [comment]
I think this issue is the same as #92233 and #92021 ??

**Comment by Alex2782** [comment]
I have not yet been able to reproduce it.

Do static variables have to be used? `static var label_cache := {}`
https://github.com/godotengine/godot/issues/92021#issuecomment-2116289580

**Comment by AThousandShips** [comment]
Please upload an MRP with code that triggers this case

**Comment by SkanerSoft** [comment]
@AThousandShips 

Unfortunately, I can't replicate this in a minimal project, but it happens in all my production projects.

Criteria, which may be:
- there are static functions
- there are singletons
- have their own classes
- there is inheritance
- there are built-in scripts

An error occurs when there are different combinations of these points, as well as in the absence of some of them.

**Comment by AThousandShips** [comment]
Then please see with either a custom build with the latest `master` or check when beta2 comes out to confirm that this has been fixed, otherwise please create a new issue report with more details to help identify it, but only if you can still identify it with a version after the fix above was merged
