### ISSUE TITLE
 Grass performs poorly 

### ISSUE THREAD

**Issue by WOLFxxxxxx** [godotengine/godot#93103]
### Tested versions

4.3

### System information

Android //VK mobile 

### Issue description

Grass performs poorly on the Android platform

### Steps to reproduce

.
![Screenshot_٢٠٢٤-٠٦-١٣-٠٠-٥٦-٤٩-٣٨٨_com example dude_2024](https://github.com/godotengine/godot/assets/128394802/4f978a27-fa4a-4830-9dc5-02b25b33248b)
![Screenshot_٢٠٢٤-٠٦-١٣-٠٠-٥٧-٢٧-١٨٩_com example dude_2024](https://github.com/godotengine/godot/assets/128394802/cfee404a-628e-4ddb-af37-feda9069df74)

### Minimal reproduction project (MRP)

.

**Comment by Calinou** [comment]
Please don't ask support questions here, as this issue tracker is meant to be used for bug reports only. Use one of the other [community channels](https://godotengine.org/community) instead.
