### ISSUE TITLE
Bug when downloading export templates and re-open the template manager

### ISSUE THREAD

**Issue by lemtea8** [godotengine/godot#93121]
### Tested versions

4.3 beta 1

### System information

Fedora 38

### Issue description

When downloading export templates from editor, click download templates in the Export Template Manager, it happens to corrupt some editor units.

What happens in the editor:
![image](https://github.com/godotengine/godot/assets/124504469/51155cc8-336b-42d3-ab0c-f4959430d983)

What should it looks like:
![image](https://github.com/godotengine/godot/assets/124504469/290cb71f-131c-4ea8-8895-469b9c19f6ae)

Error message in the editor console:
```console
scene/main/http_request.cpp:536 - Condition "get_http_client_status() != HTTPClient::STATUS_DISCONNECTED" is true.
scene/main/http_request.cpp:507 - Condition "get_http_client_status() != HTTPClient::STATUS_DISCONNECTED" is true.
HTTPRequest is processing a request. Wait for completion or cancel it before attempting a new one.
```

### Steps to reproduce

1. Open Export Template Manager.
2. Download export templates.
3. Close the Export Template Manager before download is complete, it says it will download in background.
4. Re-open the Export Template Manager before download is complete.
5. Wait a few seconds, error happens.

### Minimal reproduction project (MRP)

It's editor bug.

**Comment by akien-mga** [comment]
Confirmed in 4.3-beta1 and latest `master` (1567a498cbe0d2aeb73a9d2a67d3ac6b22b340a1).

It's also partially reproducible in 4.2.2-stable (same errors in the terminal), but there isn't the GUI layout error which makes the download bar disappear there. Instead it shows an error briefly in place of the download bar (too fast, didn't manage to screenshot it) and then resumes properly.
