### ISSUE TITLE
Is just mentioning 1.9.8.4 a cardinal sin in Godot?

### ISSUE THREAD

**Issue by RakibRyan** [godotengine/godot#93122]
### Tested versions

.

### System information

.

### Issue description

It's a game engine why'd I be shoved some ideology where I have no opinion about any of it. Alright for some reason core members decided it needs a separate community. Ok I can understand that. But why would a open source game engine community ban someone for just mentioning 1.9.8.4. For some reason if someone finds it offensive just ban from chat/ issue a temporary ban. Why'd I get banned from the whole other part of Godot . Did it stop being open source or is it the new agenda of Godot to embracing propaganda and banning people who don't agree with it?
![Screenshot_2024_0613_134841](https://github.com/godotengine/godot/assets/85598032/6b011acf-d1c6-4ce5-804c-31c4d780a29c)

### Steps to reproduce

Mention 1.9.8.4

### Minimal reproduction project (MRP)

.

**Comment by akien-mga** [comment]
1984 is a great book, you may want to read it again.

Being homophobic or transphobic however is not great, and that's indeed something that will get you a ban as per the Godot Code of Conduct: https://godotengine.org/code-of-conduct/

On GitHub too, which is absolutely not the right platform to complain about a ban on Discord - you have a ban appeal form you can use for that.

So :hammer:
