### ISSUE TITLE
[4.2] Ukrainian translation output window contains a warning with Russian text

### ISSUE THREAD

**Issue by PanShmark** [godotengine/godot#93139]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3] and v4.2.2.stable.flathub [15073afe3]

### System information
Godot v4.2.2.stable - Linux Mint 21.3 (Virginia) - X11 - GLES3 (Compatibility)

### Issue description

The warning is as follows:
![Screenshot](https://github.com/godotengine/godot/assets/170368754/80eaf5e7-78da-482e-9719-931fbd35acb6)
`modules/gltf/register_types.cpp:63 - Импорт файлов Blend включен в настройках проекта, но в настройках редактора не указан путь к Blender. Файлы Blend не будут импортированы.`

If I was to switch to English translation it says:
`modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.`

I would expect all warnings to be in Ukrainian or at least in English if the translation is not completely perfect.

The issue persists between projects, flatpak and the official versions, Linux Mint 21.3 Cinnamon installations.

### Steps to reproduce

- Launch Godot
- Set the language to Ukrainian
- Open any project
- Look at the Output menu

### Minimal reproduction project (MRP)

[0.zip](https://github.com/user-attachments/files/15828531/0.zip)

**Comment by Alex2782** [comment]
https://hosted.weblate.org/projects/godot-engine/godot/uk/
Would probably have to be adapted there if `'ru'` is not used as a fallback language. 

https://docs.godotengine.org/en/stable/contributing/documentation/editor_and_docs_localization.html

**Comment by akien-mga** [comment]
Yes this is just a translation error, which should be fixed on Weblate. The strings will then be updated in Godot next time I sync with Weblate.

**Comment by timothyqiu** [comment]
Note that the original message is from here:

https://github.com/godotengine/godot/blob/15073afe3856abd2aa1622492fe50026c7d63dc1/modules/gltf/register_types.cpp#L62-L65

But it's removed in 4.3 (#85448) which means you can't find it on Weblate anymore.

**Comment by akien-mga** [comment]
I fixed it manually by removing the translations for these two warnings which seemed indeed to be in Russian.

While at it, I did a full sync of 4.2 translations with the 4.3 strings from Weblate which are compatible: https://github.com/godotengine/godot/commit/07cf36d21c9056fb4055f020949fb90ebd795afb
