### ISSUE TITLE
AnimationTree StateMachine transition animation reset behaves weird depending on blend position

### ISSUE THREAD

**Issue by Rooni** [godotengine/godot#93136]
### Tested versions

- Reproducable on Godot Engine v4.3.dev6.official [89850d553]

### System information

Windows 11

### Issue description

A BlendSpace2D with a transition configured to `reset` the animation, does not reset the animation depending on if the `blend_position` changed.
Whenever the blend_position stays the same, the animation is properly started at 0, if the blend_position is different, the animation is started somewhere inbetween the start and end, causing keyframes to not trigger, in this case a texture only gets set after the animation restarts naturally.

### Steps to reproduce

1. Create an AnimationPlayer and set up some animation that set a texture on the first keyframe.
2. Create an AnimationTree with two BlendSpace2Ds, for `idle` and `moving`. Set up the blendspaces with animations for each direction. Set the blend mode to `CA` (`BLEND_MODE_DISCRETE_CARRY `)
3. Set up a script that sets the blend position and a way to transition between the two states.
4. Run the project and see that the texture only changes when the blend position remains the same between states.

### Minimal reproduction project (MRP)

This project demonstrates the issue with a progress bar (the progress in the animation), and two color changing cubes with a different color for each direction.

The top cube is a ColorRect, and the bottom a Sprite2D.
Animations with keyframes are set up to change the appearance of both cubes, but the Sprite2D only changes whenever the animation actually passes the keyframe, to demonstrate it changing only after the animation ended and starts to loop.

The expected behavior is that both cubes instantly change color (through the keyframe at 0), whenever any direction is pressed.
What actually happens is, the animation doesn't start from 0 when the blend position changes.

Pressing only one direction (eg. right, right, right, right), shows the animation properly resetting to 0.
Alternating directions causes the animation to not start from 0, causing the color change to be delayed until the animation loops.

[mrp-blend-position-bug.zip](https://github.com/user-attachments/files/15827262/mrp-blend-position-bug.zip)

**Comment by TokageItLab** [comment]
Although the behavior of dev6 and the current master is different, I found a bug in the force continous behavior nonetheless, so I sent a fix as https://github.com/godotengine/godot/pull/93185.
