### ISSUE TITLE
RigidBody3D wrong physics behavior

### ISSUE THREAD

**Issue by alparslanahmed** [godotengine/godot#93130]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

Windows 11 - Godot v4.2.2 - Vulkan API 1.3.278 - Forward Mobile - NVIDIA GeForce RTX 3060 Ti

### Issue description

In Godot how can I compress rigidbodies between kinematic versions of them so they can hang on the air. In Unity and Unreal engine when i intertwine rigidbodies they are hanging. And when i apply impulse they fall which is expected behavior. But i couldn't achieve same effect with Godot. I also tried Jolt Physics extensions but result is same.

Expected behavior: 

- Intertwined cubes must hold each other on the air
- When impulse applied to non-kinematic cube in the center it must fall

Purpose: Building [this](https://www.youtube.com/shorts/0ywdy38e19c) game on mobile

Unreal Engine 5

https://github.com/godotengine/godot/assets/5161926/32c2afbf-deb1-4aa8-a147-e44f2a3b5103

Unity

https://github.com/godotengine/godot/assets/5161926/8f6cb5b9-53c4-4fb1-82ec-12094e9ed6e5

Godot Physics

https://github.com/godotengine/godot/assets/5161926/130baf11-72a1-487d-9ba5-406b23a169d3

Godot Jolt

https://github.com/godotengine/godot/assets/5161926/c3f68797-bbce-4962-9fd1-034c42a53054

### Steps to reproduce

- Create 2 cubes as RigidBody3D on the air, make them kinematic
- Create 2 cubes as RigidBody3D in between kinematic ones which will be affected by gravity
- Intertwine positions of the all cubes so their collision shapes will overlap

### Minimal reproduction project (MRP)

[Bricks.zip](https://github.com/user-attachments/files/15820431/Bricks.zip)

For Jolt you have to install addon which is too big for uploading here.

**Comment by JekSun97** [comment]
This physical phenomenon is called contact pressure, the forces acting between the contacting cubes are pressure forces created by compression, I also tried to implement a similar physical phenomenon, but it seems that it is not provided for in Godot, correct me if I’m wrong, I remember that I could implement this in Box2D

**Comment by alparslanahmed** [comment]
I achieved expected result by adding friction to cubes with Jolt Physics. Thanks to https://github.com/godot-jolt/godot-jolt

https://github.com/godotengine/godot/assets/5161926/40bd0981-19b2-4b85-8cf8-cfc4a6968cde
