### ISSUE TITLE
`NavigationServer3D.map_get_closest_point_to_segment` only returns correct result if segment intersects nav mesh

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#93138]
### Tested versions

Reproducible in 4.3.beta1

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

`NavigationServer3D.map_get_closest_point_to_segment` only returns correct result if segment intersects the nav mesh. If both endpoints of the segment are above or below the nav mesh, then it will return the *closest point on an edge*. The expected result would be to return the closest point on the nav mesh, period.

In the GIF below, you can see the two blue points representing the endpoints of the segment. The red represents the output of `NavigationServer3D.map_get_closest_point_to_segment`. As you can see, it lands directly on an edge:

![closest_point_to_segment_edge](https://github.com/godotengine/godot/assets/13228932/f594afb6-8e06-45cf-b3a1-086372cd2e43)

The expected result is for it to land right beneath the lower of the two blue points, like this:

![closest_point_to_segment_edge_correct](https://github.com/godotengine/godot/assets/13228932/04b9d0a5-aef4-4d31-a3ed-964826eb5670)

When the two blue points are on opposite sides of the nav mesh (the segment intersects the nav mesh), the function produces the correct result, with the red point being on the surface of the nav mesh, at a position where the segment crosses it.

![closest_point_to_segment_edge_intersects](https://github.com/godotengine/godot/assets/13228932/b207ee3a-188a-4d54-b494-2435cc0c45a5)

### Steps to reproduce

- Open the attached project.
- Turn on `Debug > Visible Navigation` in the menu.
- Run the project or scene.
- Observe the results.
- Rearrange `endpoint_A` and `endpoint_B` and repeat, and note that the error only happens when the segment does not intersect the nav mesh.

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/15827967/bug-report.zip)

**Comment by smix8** [comment]
The closest edge and face check in the `modules/navigation/nav_map.cpp` file and function `NavMap::get_closest_point_to_segment()` needs to be fixed and tested.
