### ISSUE TITLE
Code signing on macOS and Windows

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#9313]
Just capturing this as we briefly discussed this on IRC today. 

Mac OS X is getting stricter when it comes to deploying applications. Ever since the introduction of gatekeeper in OS X 10.9, and the rules being more strictly enforced since OS X 10.11 deploying an application on Mac OS X requires code signing to be effortless.

The approach Godot currently uses to deploy a zipped application bundle results in Mac OS X marking the application as quarantined after unzipping.

You can work around this by either turning off gatekeeper, manually clearing the quarantine flag, or after Mac OS X instructs you to do so, going to System Preferences->Security and selecting run anyway (this last option doesn't always work consistently I've found). 

The nicer option would be to properly code sign the application. Apple no longer requires you to pay a $100 yearly fee to code sign unless you are deploying through the Apple store but the code signing process is only available on Mac OS X (though I have read somewhere you can export the signature as PKCS12 and apply the code signing on windows, worth investigating).

On OSX, provided the signatures are installed in your keychain you can simply use the [codesign](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/codesign.1.html) command.

The other thing that was mentioned was to enabling creating a DMG instead of ZIP if we're running on Mac OS X and only use ZIP when exporting on another platform.

**Comment by reduz** [comment]
Calinou was investigating what is necesary for signing our editors (export
templaes should not be signed), so we ask Conservancy to help us with this.
Think you could give him a hand?

**Comment by lexum0** [comment]
Maybe I can help with this

**Comment by BastiaanOlij** [comment]
@reduz Code signing the editor bundle shouldn't be hard seeing there is almost nothing in the bundle. We're a bit spoiled on OS X with XCode just applying the logic but I'll do some reading up on the manual process.

The templates may be a bit of an issue, not signing the package in which they come may result in the files being marked for quarantine and I'm not sure if that gets cleared if you then code sign the application after exporting your game project. But it shouldn't be a hassle to code sign the container, copying out the files to create the final application bundle on export shouldn't be hindered by that.

Another option that is worth thinking about is, for Mac only, placing the templates in editor.app/Contents/Resources/Templates and pointing the template folder there instead of to ~/.godot/templates/version if the resources folder exists. That should allow us to secure the files when we code sign the editor application bundle.

It may also be an idea to reach out to Apple. I'm pretty sure they'll have a program for wavering the $100 a year fee for free open source development tools that target Mac OS X and iOS if we'd want to make a free copy of Godot downloadable on the Mac Store.

@lexum0 if you have experience with this, all help is much appreciated. In my day job I end up code signing our application installers but there aren't any pitfalls there.

**Comment by lexum0** [comment]
I've been thinking about this all day and even though my first solution was to publish through  the App Store, I don't think its going to be possible because of Sandbox. Sandbox makes everything impossible and would hinder the engine's magic. Unless we prepare it for Sandbox and for that I think we would need Xcode

If we were able to edit the code and compile from Xcode we would solve everything, from publishing to signing, engine and game development, custom APIs, iCloud, In-App Purchases and more 
Every year Apple improves everything and the APIs are constantly changing as well as the publishing processes and Xcode handles all of that.
If we can make it run in Xcode we would solve a lot of problems for free.

I have the $99 developer account, if I can help sign the code I'm up for it and help make distribution smooth.

As a side note, I've never had any problems with Godot, but I agree it's important if the code can be signed.
I don't think Apple will wave away the $99 price but you never know. If Godot was presenting on stage with them like Unity and Unreal I'm sure they would xD

**Comment by lexum0** [comment]
We should start by deploying DMGs instead of ZIPs

If it's possible to integrate with Xcode it would be great, if not stick to just signing it

**Comment by BastiaanOlij** [comment]
I'm not sure if sandboxing is a real concern. Obviously we have three separate things we're talking about here:
- deploying the Godot editor with which you build games, similar to how its currently deployed over steam
- deploying a game you've created with Godot to Mac OS X
- deploying a game you've created with Godot to iOS

With then the option for all 3 to submit to the app store.

All that XCode offers you here is convenience in doing so instead of manually going onto the developer portal to setup all the certificates and provisioning profiles.

The sandboxing is simply a matter of recording meta data about what your app will do, does it use a network connection? does it need access to the camera, does it do xyz and that gets locked down when the app gets code signed so the OS knows something is wrong when the app tries to do something its not supposed to.

The only part where I am very unsure is GDNative. For runtime deployment the dylibs simply need to go into the right folder inside of the app bundle and get codesigned along with the main executable. But when you're developing your own GDNative extensions and adding them to an already code signed Godot editor bundle, Mac OS X might get upset. That said, during development you leave these dylibs in the user folder alongside the game project you're building so this may not be an issue.

@karroffel that reminds me, have you given thought about how GDNative libraries are deployed? We may need to add support to the export classes so each platform can handle the best way for the libraries to be added to the deliverable.

**Comment by lexum0** [comment]
The 3 things are the same in the eyes of the App Store, and Sandbox is something much more complex than what you say. You get 0 access to everything, you ask for permission in code for everything, you don't have access to really cool stuff, accessing files is a hassle, your play area is reduced and you require to code things differently. Its not just about adding metadata 

Xcode also involves code editing, code completion and so on, its not just a tool for generating profiles instead of the portal. It also is the door for publishing to the App Store

**Comment by BastiaanOlij** [comment]
@lexum0 , so that means that the code needs to be added to ask for permission if its not already there, which would surprise me as that is something you add as you build in support for the various APIs or they wouldn't work in the first place. That is all involved in building the platform code, take a look for instance at the game centre implementation. 

That said, as far as I'm aware the sandboxing itself is controlled by the .entitlements plist file XCode generates for you and that file simply needs to be supplied to codesign. Given I only have theoretical knowledge here so I may be completely wrong.

The compiling of Godot is handled by scons, but scons calls the same compiler XCode calls. You can still use Xcode to edit the Godot source code if you want and have all the syntax highlighting etc. Compiling the Godot source code from XCode however, there are a lot of issues there. Most of the development for Godot is being done on Linux and Windows. That means that all that work that has impact on the build system we suddenly have to fix up as Mac developers if we start using XCode projects instead of using Scons. My biggest beef at the moment with not using XCode is that debugging becomes a drag. XCode does not like it if it's not in full control.

For deploying of the application you'll see that for iOS the current approach is to use an XCode project into which you place the compiled binaries and your exported game.pck file, but we then leave it up to XCode to code sign and upload it to iOS. It all works already and allows XCode to do its thing but it is clunky and unfriendly.

In the end there are two separate goals here:
1) properly code sign the Godot editor so that if someone downloads it, it will work instead of OS X complaining the application can't be trusted because it has been downloaded from an unknown source. Being able to install Godot from the Mac Store is a bonus
2) being able to deploy games you make with Godot in a way that you don't have to go through all the clunky steps but instead embedding that logic into Godot. It very well may be that the end result is creating the XCode project you currently create manually and starting XCode and have it do the final deployment (this is how fusetools does it, another development environment I use) or if at all possible, see if we can do the deployment directly from Godot.

**Comment by lexum0** [comment]
It's not all about the .entitlements file. I have first hand knowledge.

The development is being done in Linux and Windows, and that's because the Mac developers can't develop it with Xcode. Add Xcode support and you'll see the numbers go up, starting with me. Right now Xcode doesnt do much besides syntax coloring because it doesnt know the project.

As you said, the process for compiling iOS is very clunky and unfriendly, and doesnt let you do anything. Compiling from Xcode would be clean and easy and even help you add code, native frameworks, Objective-C, Swift, and more. Its the best in the long run

If scons uses the same compiler as Xcode half of the problem is already solved

Xcode would solve the 2 problems you mentioned, + also enable the path for the Mac App Store

**Comment by karroffel** [comment]
@BastiaanOlij haven't really thought about it, but I'll probably keep it simple and just copy the libraries to the project or something. Would need to discuss that with reduz I think.

**Comment by lexum0** [comment]
I just discovered Godot does support Xcode. I'm trying it and it even added my license to sign the code. 

It shouldn't be a problem to sign Godot

**Comment by BastiaanOlij** [comment]
@lexum0 compiling definitely shouldn't be a problem, it's making sure the xcode project stays up to date that will be a hassle :)

Good to hear you've got it running.

**Comment by lexum0** [comment]
Xcode automatically suggests to update the project every time there's something new, not sure if that helps...

How about taking the templates directly from Xcode?

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by akien-mga** [comment]
I can confirm this is still needed (on Windows too).

**Comment by hpvb** [comment]
I've requested a code signing certificate in the name of my company that will be used, at least until SFLC can provide something. I expect to be able to sign 3.0.5 with it. I'm still investigating osx but windows will happen for sure.

**Comment by BastiaanOlij** [comment]
@hpvb did you manage to automate the code signing on Windows? I'm now code signing stuff at work so have a bit of hands on experience.

**Comment by hpvb** [comment]
Windows binaries are signed now. An explanation for what's happening with macOS is here: https://github.com/godotengine/godot/issues/11984
