### ISSUE TITLE
Popup menu with rounded corners has a rectangular background

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#93156]
### Tested versions

Reproduces in v4.3.beta1.official [a4f2ea91a].

### System information

Arch Linux <span>#</span>1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 - Tty - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Popup menus with rounded corners have an extra background with square corners.

Expected:

![expected](https://github.com/godotengine/godot/assets/8843118/4bfbf72c-669d-4fb5-adec-43a2f4594922)

Actual:

![actual](https://github.com/godotengine/godot/assets/8843118/36d3879d-3a45-4001-8ec6-a5f68d7a6bc1)

### Steps to reproduce

Run MRP and open the popup menu.

### Minimal reproduction project (MRP)

[popup-menu-corners.zip](https://github.com/user-attachments/files/15837235/popup-menu-corners.zip)

**Comment by AThousandShips** [comment]
Have you enabled transparency on the popup?

**Comment by anniryynanen** [comment]
I forgot all about that. ^^;; Thanks, that fixes this.
