### ISSUE TITLE
physics tick rate effects UI elements

### ISSUE THREAD

**Issue by LunarShadow01** [godotengine/godot#93158]
### Tested versions

- Reproducible in: 4.2 stable win64

### System information

Windows 10 22H2, forward+

### Issue description

when setting the physics ticks per second to a different value it will also effect the **mouse wheel** scrolling update rate of the script editor window vertically

### Steps to reproduce

1) change the physics tick per second to a smaller integer, (1 for the most noticeable effect)
2) restart the project / quit to project select and go back / quit the editor entirely and start up again
3) open a script long enough to have a scroll bar
4) use the mouse scroll wheel to scroll up and down the script

### Minimal reproduction project (MRP)

any project will do.
even a freshly created project opened on the tested build
tested without any addons or other settings modifications

**Comment by AThousandShips** [comment]
Please try with 4.2.2 to make sure this hasn't already been resolved

**Comment by LunarShadow01** [comment]
> Please try with 4.2.2 to make sure this hasn't already been resolved

negative, the issue persists in 4.2.2

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/28385.

> Because RichTextLabel uses the wrong processing mode for internal updates.

This is a difficult issue to fix, and it's actually part of TextEdit. See discussion starting from https://github.com/godotengine/godot/pull/92865#issuecomment-2154666260.
