### ISSUE TITLE
`global_script_class_cache` fails to rebuild properly if a script's `class_name` is used in another global script

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#93157]
### Tested versions

Reproducible in v4.2.2.stable.official [15073afe3]
Reproducible in v4.3.beta1.official [a4f2ea91a]

### System information

Linux/Manjaro

### Issue description

I had an issue in one of my projects where the global script cache was not clearing files that don't exist, throwing errors in the console on things like the Add Node dialog, so I removed the `global_script_class_cache.cfg` file from the `.godot` folder. Upon restarting the editor, all scripts were throwing errors. Opening the newly created `global_script_class_cache.cfg` file showed that it was not rebuilding the cache.

The project in question uses a lot of `class_name`s, so this is another preload cache issue.

### Steps to reproduce

1. Create two scripts, give them both `class_name`
2. Use one script's global class name in another
3. Remove the `global_script_class_cache.cfg` file and restart the editor

### Minimal reproduction project (MRP)

[global_script_cache_bug.zip](https://github.com/user-attachments/files/15837264/global_script_cache_bug.zip)
Opening this project should trigger the bug

**Comment by Hilderin** [comment]
This issue should be fixed by #92303 
I tested the MRP with this PR and it load without any error.

**Comment by akien-mga** [comment]
Fixed by #92303.
