### ISSUE TITLE
[4.3.beta1] Editor becomes slow to unusable when running a separate plugin-based window next to it

### ISSUE THREAD

**Issue by SnekOfSpice** [godotengine/godot#93169]
### Tested versions

- Reproducable in v4.3.beta1.official [a4f2ea91a]
- Does not occur in v4.3.dev5.official [89f70e98d] or v4.3.dev6.official [89850d553]

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Starting with 4.3.beta1, a plugin I've been working on became unusable. It creates a separate window that the user will use like its own application (see mrp equivalent image below). Something in beta1 makes this setup perform really really badly.

![grafik](https://github.com/godotengine/godot/assets/69637995/13ef9478-3240-4e7c-8e7f-013c237eec36)

Here I only added a small slider and some code from my own codebase to give the editor something to struggle with, as this does seem to scale with scene complexity. (I couldn't reproduce this with an empty window, with the setup above, it took about 2 minutes until this drop in performance was reached, and with my full plugin the editor can barely switch script tabs in under 30 seconds)

- 0:03 - the hover effect of the different menu items breaks
- 0:14 - the different tab buttons all have a delayed hover effect
- 0:20 - drag-clicking to highlight console text breaks
- 0:52 - double clicking on console text to highlight it works unreliably
- 1:00 - windows open and close with heavy delay

https://github.com/godotengine/godot/assets/69637995/2c078a3e-3f13-4622-bd90-5143365e7f6c

While looking for related issues I came across #93155, which seems to be the only other editor performance-related issue for 4.3.beta1 so far?

### Steps to reproduce

- Import the project and ensure the plugin is enabled (reload the editor if needed)
- Open the window with the "Test" Button in the top right, kill some time by playing with the slider or just wait around
- After some time, the main Godot editor should become laggy like in the video
- (This only happens when the window is open, if you never click the button, the editor is fine)

### Minimal reproduction project (MRP)

[beta-1-bad-performance.zip](https://github.com/user-attachments/files/15840596/beta-1-bad-performance.zip)

**Comment by JekSun97** [comment]
I confirm that productivity drops greatly.
I noticed that when we comment out window.popup() -> #window.popup(), the editor stops freezing, something with laggy_window

**Comment by matheusmdx** [comment]
This seems to be another victim of https://github.com/godotengine/godot/pull/91361, you don't need to wait for reproduce the issue, just move the opened window a bit and will be enough to trigger the lag

https://github.com/godotengine/godot/assets/44306054/93c15453-544d-4a0a-8095-2b3daf32c35a

<br>

Also as the other similar issues, pr [#92742](https://github.com/godotengine/godot/pull/92742/checks) seems to solve this issue too, but just to make sure, @SnekOfSpice can you check this comentary (https://github.com/godotengine/godot/issues/92954#issuecomment-2158618652) and do the steps to confirm?

https://github.com/godotengine/godot/assets/44306054/6fa8806b-ca0b-4a2a-9c73-14d6f7f1fc4f

**Comment by SnekOfSpice** [comment]
Thanks for the pointer @matheusmdx! This does indeed seem to fix the issue. Closing this issue then :)

**Comment by matheusmdx** [comment]
@AThousandShips This is the third issue opened after the fix, at this point shouldn't be a good idea let one of these issues open and pin them?

**Comment by AThousandShips** [comment]
All of the issues linked in the PR have very very different descriptions so I don't think people will identify based on the issue if we pin it (and pinned issues aren't very effective either, for example the C# export issue has two duplicates opened after it was pinned)
