### ISSUE TITLE
Godot Project Manager Update Available has broken link

### ISSUE THREAD

**Issue by terrybader** [godotengine/godot#93197]
### Tested versions

Reproduceable in 4.3 Beta1

### System information

Windows 11

### Issue description

From 4.3 beta 1 Official

On the Project List page at the bottom there is Update Available: 4.3-4.3 in Yellow which opens
https://godotengine.org/download/archive/4.3-4.3

Returns 404

![Screenshot 2024-06-15 121655](https://github.com/godotengine/godot/assets/46571842/56780b07-2ed6-4b95-9f62-484a521b86d1)

### Steps to reproduce

Open Godot_v4.3-beta1_win64_console.exe

View Project List

Click Update Available 4.3-4.3 at bottom in yello

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92593

This has already been solved
