### ISSUE TITLE
Godot 4.3.beta1 `can_instantiate` results in `Invalid call. Nonexistent function 'can_instantiate' in base 'GDScript'.`

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#93193]
### Tested versions

v4.3.beta1.mono.official [a4f2ea91a]

### System information

Windows 11

### Issue description

I run into this error after upgrading to beta1.

On my tooling i have a function to evaluate the given argument is type e.g. a Class type
```
static func is_type(value :Variant) -> bool:
	# is an build-in type
	if typeof(value) != TYPE_OBJECT:
		return false
	# is a engine class type
	if is_engine_type(value):
		return true
	# is a custom class type
	if value is GDScript and value.can_instantiate():
		return true
	return false
	
static func is_engine_type(value :Object) -> bool:
	if value is GDScript or value is ScriptExtension:
		return false
	return value.is_class("GDScriptNativeClass")	
```

But it is broken now with Godot 4.3.beta1

`Invalid call. Nonexistent function 'can_instantiate' in base 'GDScript'.`

### Steps to reproduce

Use the code to reproduce, assigning the script instance to a Variant results into this error now.

```
	var script :Variant = GDScript.new()

	script.can_instantiate()
```

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92610

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by MikeSchulze** [comment]
@AThousandShips looks like the same root cause, yes.
So far I understand an assign to an un-typed variable is internal handled as a Variant, right?

**Comment by AThousandShips** [comment]
It is yes the underlying data is `Variant`

**Comment by MikeSchulze** [comment]
Ok so than the beta1 breaks a lot :(, o need to wait for the next iteration
