### ISSUE TITLE
Float rounding and precision

### ISSUE THREAD

**Issue by 10bag** [godotengine/godot#9319]
Windows 7, Godot 2.1.3.0 Steam version

Why are my floats here being automatically rounded? Is this intended behaviour? 
Using them as-is or float()ing them produces the same, rounded, result.
How can I create accurate Vector2s from these array values?

	var points = [[ -7641742.9734278414, -6891032.3691751538 ], 
	[ -7640489.5277312668, -6891460.7849851009 ], 
	[ -7618662.6263543591, -6893579.913525274 ], 
	[ -7591951.2935277065, -6892344.3927164907 ]]
	
	var vec2array = Vector2Array()
	var vec2farray = Vector2Array()
	
	for i in range(0, points.size()):
		vec2array.append(Vector2(points[i][0], points[i][1]))
		vec2farray.append(Vector2(float(points[i][0]), float(points[i][1])))
		
	print("v2 array: ", vec2array)
	print("v2 f array: ", vec2farray)

Console output:
```
v2 array: [(-7641743, -6891032.5), (-7640489.5, -6891461), (-7618662.5, -6893580), (-7591951.5, -6892344.5)]
v2 f array: [(-7641743, -6891032.5), (-7640489.5, -6891461), (-7618662.5, -6893580), (-7591951.5, -6892344.5)]
```

**Comment by groud** [comment]
I think this might come from the way float are printed by default.
With another string formating maybe this would be ok ?

**Comment by 10bag** [comment]
Like this? 

`print("%1.3f" % points[0][0], ", ", "%1.3f" % points[0][1])`

Output:
`-7641743.000, -6891032.500`

**Comment by groud** [comment]
So I guess you are limited by the floating point precision. Have you tried with lower numbers ?

**Comment by bojidar-bg** [comment]
3.0 result:
```
print("%1.3f" % points[0][0], ", ", "%1.3f" % points[0][1])
```
Output:
```
-7641742.973, -6891032.369
```

Reason: in 2.1.x floats() are single-precision floats, while in 3.0 they are going to be double precision.

According to [wikipedia](https://en.wikipedia.org/wiki/IEEE_754-1985#Single_precision) (check the graph around the heading), single-precision floats have around 7-8 significant digits of precision, while double-precision floats have around the precision of 16-17 significant digits.

**Comment by groud** [comment]
That's what I was thninking about. :)
I guess this wont be fixed for 2.1.

**Comment by 10bag** [comment]
Surely I must be doing something wrong, or this isn't a floating point precision issue, because even with just two decimal places it's still rounding the floats.

`	var points = [[ -6763470.35, -6893947.12 ], [ -6764361.06, -6893250.95 ], 
	[ -6765635.16, -6891743.65 ], [ -6766629.11, -6891017.05 ], 
	[ -6767657.13, -6890756.92 ], [ -6789871.97, -6888148.28 ]]
	
	print("%1.2f" % points[0][0], ", ", "%1.2f" % points[0][1])`

Output:
`-6763470.50, -6893947.00`

**Comment by groud** [comment]
This has to do with the total number of digits, not how many numbers are after the dot. Try with lower numbers (around 100 maybe), and it should work.

**Comment by 10bag** [comment]
Ah that makes sense, thanks. I'm not very good at maths. I'll switch to Godot 3 when it's stable.

**Comment by Zylann** [comment]
@bojidar-bg I thought it was actually decided to keep float in 3.0?

**Comment by bojidar-bg** [comment]
@Zylann I can't remember such a thing. Variant is now double, and most of the api is switched to real_t...
