### ISSUE TITLE
Kerning Pairs (monospace image font) can affect the kerning of subsequent characters, off by one pixel

### ISSUE THREAD

**Issue by DarkMarmot** [godotengine/godot#93199]
### Tested versions

- Reproducible in: Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When using kerning pairs, the space between two characters can be affected by the character that came before them. It appears there is some kind of rounding layout issue, not sure if this is a bug in kerning or in the rendering pipeline.

![image](https://github.com/godotengine/godot/assets/1878563/d1758218-ca57-4683-92e4-e41b334ce28e)

In the example, A and B have different kerning offsets when followed by p. The space between u and p then differs between them.

### Steps to reproduce

Open the project and the layout issue is visible in the main scene for preview and run.

Note that this affect can be achieved by changing things like character margins as well to generate inconsistent layouts.

### Minimal reproduction project (MRP)

[kerning_layout_issue.zip](https://github.com/user-attachments/files/15848756/kerning_layout_issue.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
The issue seems to be how HarfBuzz apply kerning, half is applied to the previous glyph advance, half to the next glyph offset. This works with normal fonts, but with `1px` kerning it will result in `0.5` pixel offsets and rounding errors.

**Comment by DarkMarmot** [comment]
@bruvzg thanks for working on such quick fixes for this feature! As someone relatively new to Godot, I really appreciate it!

**Comment by capnm** [comment]
If I hit those 3 buckets and reimport, your issue is fixed for me (Linux).

![Screenshot from 2024-06-17 18-56-25](https://github.com/godotengine/godot/assets/4047289/e42f83c3-12e9-47fb-b85b-f8af0bb86b7e)

![Screenshot from 2024-06-17 18-56-38](https://github.com/godotengine/godot/assets/4047289/e4ddcb88-3e4a-4b5a-b9f6-2c13708165ac)

**Comment by DarkMarmot** [comment]
@capnm That deletes the kerning pairs, thus removing character specific kerning entirely. This bug report is about the usage of the kerning pairs feature itself.

**Comment by capnm** [comment]
> @capnm That deletes the kerning pairs, thus removing character specific kerning entirely. This bug report is about the usage of the kerning pairs feature itself.

Kerning pairs for monospace fonts? This is IMO a bug – you shouldn't use kerning here at all.

**Comment by DarkMarmot** [comment]
> Kerning pairs for monospace fonts? This is IMO a bug – you shouldn't use kerning here at all.

The datatype will probably be renamed to bitmap image fonts or such since this feature allows them to no longer be exclusively monospace.

**Comment by capnm** [comment]
I thought you also needed the *.fnt file for kerning the bitmap files? No?

**Comment by bruvzg** [comment]
> I thought you also needed the *.fnt file for kerning the bitmap files? No?

You can manually specify kernings and custom glyph offsets/advanced in the image import settings, importer should be renamed it was monospace when it was first added, but this is no longer the case.

**Comment by capnm** [comment]
I guess that's then the implemented spec...

[bmfont](https://www.angelcode.com/products/bmfont/doc/file_format.html) -> Block type 5: kerning pairs

https://calligro.ideasalmanac.com/
