### ISSUE TITLE
Godot forces me to restart over and over after installing a WORKING addon

### ISSUE THREAD

**Issue by logslmao** [godotengine/godot#93194]
### Tested versions

- Reproducible in 4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 (11) - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.4680) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

I installed orchestrator two ways, via the plugin install AND manually, godot instead spits out "Please restart and save to apply plugins".

### Steps to reproduce

Install an addon, in this case Orchestrator

### Minimal reproduction project (MRP)

[project.zip](https://github.com/user-attachments/files/15847866/project.zip)

**Comment by Haydoggo** [comment]
I can't seem to replicate your issue with the information provided. This issue is likely an issue with your particular installation of the Orchestrator plugin rather than with the Godot Engine

**Comment by AThousandShips** [comment]
Closing as a likely issue with either the plugin or how it was installed, and not a Godot issue
