### ISSUE TITLE
Exported on Android: Error: dlopen failed: library "libstdc++.so.6" not found

### ISSUE THREAD

**Issue by klasterstorm** [godotengine/godot#93201]
### Tested versions

Godot_v4.2.2-stable_mono_win64

### System information

Windows 10; Godot_v4.2.2-stable_mono_win64; 

### Issue description

Crash log from Android device
```
18:35:19.591 godot         E  USER ERROR: Can't open dynamic library: /data/data/com.klaster.swordshard/cache/data_Rune Sword II_android_arm64/libhostfxr.so. Error: dlopen failed: library "libstdc++.so.6" not found: needed by /data/data/com.klaster.swordshard/cache/dynamic_libraries/1718465600000/libhostfxr.so in namespace classloader-namespace.
18:35:19.591 godot         E     at: open_dynamic_library (platform/android/os_android.cpp:200)
18:35:19.595 godot         E  USER ERROR: Can't open dynamic library: /data/data/com.klaster.swordshard/cache/data_Rune Sword II_android_arm64/Rune Sword II.so. Error: dlopen failed: library "Rune Sword II.so" not found.
18:35:19.595 godot         E     at: open_dynamic_library (platform/android/os_android.cpp:200)
18:35:19.595 godot         E  USER ERROR: .NET: Failed to load hostfxr
18:35:19.595 godot         E     at: initialize (modules/mono/mono_gd/gd_mono.cpp:400)
```

System info
```
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.302\

.NET SDKs installed:
  8.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

JDK:
jdk-22_windows-x64
```

Export from ```Godot_v3.5.3-stable_mono_win64``` work fine

### Steps to reproduce

1) Export a project to Android
2) Run APK
3) Crash on start

### Minimal reproduction project (MRP)

[Original log.txt](https://github.com/user-attachments/files/15849180/Log.txt)

I cannot reproduce, because catch another fatal error 
[Another fatal error.txt](https://github.com/user-attachments/files/15849233/Another.fatal.error.txt)

**Comment by raulsntos** [comment]
Can you provide the APK and some information about the Android device that it was running on? (e.g.: OS version, architecture, etc.) Also, please provide the export preset configuration (or even better the [minimal reproduction project](https://github.com/godotengine/godot/blob/4c1f11944ebfe1204f21c6ac488c7a2294e1d520/CONTRIBUTING.md#provide-a-simple-example-project) to make it easier to troubleshoot) 

Also, in your second txt you are getting this:

> Error: Can't run project: no main scene defined in the project.

Make sure to set a main scene.

**Comment by klasterstorm** [comment]
Device:
![image](https://github.com/godotengine/godot/assets/8971579/f111f5b1-e905-481e-8423-1f51f9b0ea13)
Try to open APK to another device, but its still crash

APK Build larger then allowed 25MB. Upload on Google disk
https://drive.google.com/file/d/1dqLQHzEV_uDvycXjmtkiKhAF5FXnhQFy/view?usp=sharing

**Comment by raulsntos** [comment]
Your csproj targets `net6.0`, I guess you created this project with a version of Godot before 4.2. Android requires at least .NET 7.0, see the [_C# platform support_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/index.html#c-platform-support) documentation.

**Comment by klasterstorm** [comment]
Thx, its work! 
Switch .net 6 to .net 8, and all work fine
