### ISSUE TITLE
VisualShaderNodeVaryingGetter breaks the preview of visual shader nodes

### ISSUE THREAD

**Issue by Grandro** [godotengine/godot#93203]
### Tested versions
- 4.2.2
- 4.3-dev6

### System information

Windows 10

### Issue description

When activating the preview on visual shader nodes that have an input path to a `VarryingGetter` node, the preview doesn't work and an error is generated on the console:

![image](https://github.com/godotengine/godot/assets/48568096/ea3fc2ab-927e-4d83-85ee-14f1445e1a2e)

The Varying shows as `0,0` in the editor and should therefore produce the color black in the preview.

![image](https://github.com/godotengine/godot/assets/48568096/c6d8cbf7-0a71-4fc5-9313-6d151aed79ca)

The error looks like this:
```swift
 :8 - Unknown identifier in expression: 'Test'.
  Shader compilation failed.
--Main Shader--
    1 | shader_type canvas_item;
    2 | 
    3 | 
    4 | 
    5 | 
    6 | void fragment() {
    7 | 
E   8->  float n_out2p0 = Test;
    9 | 
   10 | 
   11 | 
   12 |  float n_out3p0 = floor(n_out2p0);
   13 | 
   14 | 
   15 |  COLOR.rgb = vec3(n_out3p0);
   16 | }
   17 | 
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Parameter "version" is null.
  ./servers/rendering/renderer_rd/shader_rd.h:165 - Parameter "version" is null.
```
To me it looks like the code generated for the preview misses to define the needed varying.
Note that the shader runs fine.

### Steps to reproduce

1) Create a new project
2) Create a VisualShader, apply it to a Material and the Material to a Sprite
3) Add a `VaryingGetter` node and connect it to any fitting node with a preview
4) Whenever you toggle the preview to visible the bug occurs

### Minimal reproduction project (MRP)

[Varying_Unknown_Identifier.zip](https://github.com/user-attachments/files/15849317/Varying_Unknown_Identifier.zip)

**Comment by Chaosus** [comment]
To properly show the preview for varying getter and the nodes it's used it needs to reflect whole setter which is not possible currently (for example spatial shader preview needs to be coded via spatial shader_mode not canvas_item), in #93219 I've added a boilerplate code to just set it to zero.

PS: I wonder why varying are displayed in properties names in the inspector - they should be internal and changed via shader.
