### ISSUE TITLE
Multiple gettext plural forms in tr_n() have unexpected results

### ISSUE THREAD

**Issue by Visssarion** [godotengine/godot#93208]
### Tested versions

- Reproducible in Godot Engine v4.1.stable.official.970459615, v4.2.1.stable.official.b09f793f5, v4.3.beta1.official.a4f2ea91a

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 750 (NVIDIA; 31.0.15.3623) - Intel(R) Pentium(R) CPU G4500 @ 3.50GHz (2 Threads)

### Issue description

When making a russian localization ``.po`` file in PoEdit, you need to have different plural forms:
- Case 1: If number ends with a 1, but not with 11
- Case 2: If number ends with a 2, 3, 4, but not with 12, 13, 14
- Case 3: If number ends with a 5, 6, 7, 8, 9, 0 or if it ends on 11-19
![image](https://github.com/godotengine/godot/assets/46628714/9880160c-f4b8-4f26-9b09-e14a885b1ce2)
PoEdit has an innate support for that and also an option to change an expression that calculates what case it is.

When using that ``.po`` file in Godot, however, results differ.
Here's ``C++`` code and its results to show off expected behaviour:
```c++
#include <iostream>
#include <string>

int default_poedit(int n){
    return (n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2);
}

int mine_equation(int n){
    return (n%100>=11 && n%100<=19 ? 2 : n%10>=2 && n%10<=4 ? 1 : n%10==1 ? 0 : 2);
}

int main()
{  
  for(int n = 0; n < 35; n++){     
    std::cout << n << ": " << default_poedit(n) << " " << mine_equation(n) << std::endl;
  }
}

/*
msgstr[0] "Есть %d яблоко"  -- case 0
msgstr[1] "Есть %d яблока"  -- case 1
msgstr[2] "Есть %d яблок"   -- case 2
*/
```
Both PoEdit and my expressions provide same expected results
![firefox_9G9sW1mlKp](https://github.com/godotengine/godot/assets/46628714/3fdc5198-4b06-46c8-bb8f-fb0f180f8685)

Here's the Godot's behavior:
- Quick comparison table (explanation afterwards)
![image](https://github.com/godotengine/godot/assets/46628714/f5d1d1b4-1ee4-4f42-a906-28275c995a64)

- Default PoEdit
``(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2)``
Counts 15-20 and 25-30 return case 1, when expected behavior is 2
![Godot_v4 2 1-stable_win64_8SGLdrCKrp](https://github.com/godotengine/godot/assets/46628714/77f31d2c-5b7e-426e-9246-f324e976a092)

- My expression
``(n%100>=11 && n%100<=19 ? 2 : n%10>=2 && n%10<=4 ? 1 : n%10==1 ? 0 : 2)``
Counts 11-19 return case 0, when expected behavior is 2
Counts 1, 21, 31 return case 2 , when expected behavior is 0
![Godot_v4 2 1-stable_win64_8JdqlMSFzO](https://github.com/godotengine/godot/assets/46628714/65eba742-c607-4faa-8153-40d60e280de5)

### Steps to reproduce

In the MRP add either of the localization files from the ``translations`` folder.
![Godot_v4 2 1-stable_win64_LuseHwT9OM](https://github.com/godotengine/godot/assets/46628714/18abc5ac-c0ef-444a-b494-a329282633cc)
After that run the project.

### Minimal reproduction project (MRP)

[TranslationPOTest.zip](https://github.com/user-attachments/files/15849645/TranslationPOTest.zip)

**Comment by Visssarion** [comment]
So, looking at implementation of evaluating expression for plurals:
- Caching the long expression into small one (used to break up ternary operators):
https://github.com/godotengine/godot/blob/71699e08c9df78b7203fa4ef9cede28e995d6ace/core/string/translation_po.cpp#L164-L180
- Executing those small expressions
https://github.com/godotengine/godot/blob/71699e08c9df78b7203fa4ef9cede28e995d6ace/core/string/translation_po.cpp#L137-L162

Code don't really look at left part of a ternary operation!
Code assumes that it goes like ``{comparison} ? 0 : {comparison} ? 1 : {comparison} ? 2 : {comparison} ? 3 : ...``
Which explains why my expression wasn't working (``n%100>=11 && n%100<=19 ? 2 : n%10>=2 && n%10<=4 ? 1 : n%10==1 ? 0 : 2``)

So I wrote new expression that follows these rules: ``(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && n%100/10!=1 ? 1 : 2)``. It provides correct results!
![image](https://github.com/godotengine/godot/assets/46628714/b7a2e003-1209-4d8a-ad25-6fdce2dcd705)

However, original PoEdit expression ``(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : 2)`` does follow the structure, but doesn't work. *The structure seems to be not the only problem*. 

When I used new expression with PoEdit, it didn't liked it because it had division. So I switched ``n%100/10!=1`` with ``(n%100<10 || n%100>19)``, which *should* provide same result. PoEdit does show that, it does in fact work as intented. However, when used in Godot, it provides wrong results:
(``New`` column = ``(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>19) ? 1 : 2)``)
![image](https://github.com/godotengine/godot/assets/46628714/4b06550f-865e-476f-83cd-890ffe2cd6ed)

It repeats the pattern of default PoEdit formula (exception are cases 15-19, but only because PoEdit formula would compare with >14)

**Comment by Visssarion** [comment]
Expression class when used in Godot directly does provide correct results through.

```gdscript
@tool
extends EditorScript

var expression: Expression = Expression.new()

func _run():
	expression.parse("n%10>=2 && n%10<=4 && (n%100<10 || n%100>19)", ["n"])
	print(expression.execute([4])) # Prints true
	print(expression.execute([13])) # Prints false
	print(expression.execute([22])) # Prints true
	print(expression.execute([26])) # Prints false
	expression.parse("n%10>=2 && n%10<=4 && (n%100/10!=1)", ["n"])
	print(expression.execute([26])) # Prints false
```

**Comment by bruvzg** [comment]
Ternary operator splitting probably should use some sort of tree structure to keep both branches instead of vector.

**Comment by bruvzg** [comment]
There's also another issue, it's removing all brackets (instead removing only brackets on the edges).

**Comment by bruvzg** [comment]
Made a draft for a bit better handling (seems to work with all rules mentioned in this issue) - https://github.com/godotengine/godot/pull/93262, probably will still fail on some complex nested bracket cases.
