### ISSUE TITLE
VisibilityEnabler2D does not take effect when it is added to scene tree.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9321]
**Operating system or device - Godot version:**
Godot 2.1.3

**Issue description:**

When a scene with a VisibilityEnabler2D  is add to the scene tree outside of the screen, VisibilityEnabler2D will not take effect, it only take effect when it enter screen and then exit screen. 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment]
NoBody care about this issue? Or am I using this node in a wrong way?

**Comment by alexzheng** [comment]
Also I have tried this in 3.0, it's the same.

**Comment by alexzheng** [comment]
Maybe I should not call set_fixed_process(true) or set_process(true) in _ready.
Just let the VisibilityEnabler2D call it.

If it's not bug, it can be closed

**Comment by alexzheng** [comment]
But it would be better to disabled it when added to screen tree outside of the screen, no matter whether it's on or off.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by alexzheng** [comment]
This new feature is still NOT provide in 3.0!

**Comment by alexzheng** [comment]
Still relevant

**Comment by akien-mga** [comment]
Relevant code in `scene/2d/visibility_notifier_2d.cpp` if anyone wants to debug further.

**Comment by FlavioFS** [comment]
# I can confirm this still in 2019

**Godot version:**
Godot Engine v3.1.beta2.official

**OS/device including version:**
Sony VAIO SVE14A15FBW:  
- Windows 10 x64
- Intel(R) Core(TM) i5-2450M @ 2.5GHz (4 CPUs)
- 6GB RAM
- AMD Radeon HD 7600M
- XBOX 360 wired gamepad

**Issue description:**
VisibilityEnabler2D doesn't disable elements that start off-screen until they (enter>>exit) the screen for the first time.  
> This behavior defeats the purpose of the node, since you must manually disable everything at start, which is already the scope of Visibility**Notifier**2D.

**Steps to reproduce:**  
1. Create a scene.  
2. Set the root node to whatever type you like, even PhysicsBody2D or AnimationPlayer.  
3. Create a child node of type Visibility**ENABLER**2D, mark all of its checkboxes.  
4. Create a built-in script, print anything at process.  
5. Instance one or many copies of it in another scene, position them **OUT OF SCREEN**.  
6. Hit play. Print text will be displayed below at the output, even for elements out of screen.
7. Move the camera as to show the VisibilityEnabler2D's, then move away to hide them.
8. Print messages will stop.

**Minimal reproduction project:**
[VisibilityNotifier2D Bug.zip](https://github.com/godotengine/godot/files/2926676/VisibilityNotifier2D.Bug.zip)

### At very start:
![image](https://user-images.githubusercontent.com/4502942/53738913-4582c200-3e6f-11e9-98f0-e93754a7736e.png)

### After enter>>exit:
![image](https://user-images.githubusercontent.com/4502942/53738932-53d0de00-3e6f-11e9-933e-dd62b161f1cf.png)
