### ISSUE TITLE
Brazilian Portuguese mistranslation on the Settings windows

### ISSUE THREAD

**Issue by GustavoAlvess** [godotengine/godot#93213]
### Tested versions

Godot Engine v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable

### Issue description

While using the pt_br language, the search bar in either the "Project Settings" or "Editor Settings" windows was translated from "Filter Settings" to "Configurações de Filtro" rather than "Filtrar Configurações".

In other words, the translator thought "filter" was a noun and not a verb, as if there was a filter that could have settings.

### Steps to reproduce

Just open one of those menus with the language set as Brazilian Portuguese

### Minimal reproduction project (MRP)

I don't think I should do that for a mistranslation
```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment]
The translations are handled on [webplate](https://hosted.weblate.org/projects/godot-engine/godot/) and the best way to fix this is to provide a better translation

**Comment by GustavoAlvess** [comment]
> The translations are handled on [webplate](https://hosted.weblate.org/projects/godot-engine/godot/) and the best way to fix this is to provide a better translation

Thanks! I'll check it out!

**Comment by Chaosus** [comment]
Since this is not resolvable on bugtracker, I'll close it.
