### ISSUE TITLE
Project closes on start 

### ISSUE THREAD

**Issue by trevorwinser** [godotengine/godot#93212]
### Tested versions

Windows 11 - Godot 4.2.2

### System information

Windows 11 - Godot 4.2.2
Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: AMD - AMD Radeon(TM) Graphics

### Issue description

As title says, projects randomly stopped opening. Looked into people having similar problems and found #54076 which was solved by #55924 but for some reason is still happening for me.

### Steps to reproduce

1. Install Godot on Steam
2. Click Edit on one of your projects
3. Project crashes and closes with no error report

### Minimal reproduction project (MRP)

This was happening for new projects as well.

**Comment by trevorwinser** [comment]
Side note, there is no error report when I execute in terminal, simple the following:

OpenGL API 3.3.0 Core Profile Context 24.3.1.240216 - Compatibility - Using Device: ATI Technologies Inc. - AMD Radeon(TM) Graphics

Editing project: C:/Users/trevo/OneDrive/Documents/Godot/PP
Godot Engine v4.2.2.stable.official.15073afe3 - https://godotengine.org

**Comment by trevorwinser** [comment]
I was able to run my project after attempting to open it in fast succession to seemingly slow down my computer. It seems this causes it to run in an unstable fashion as the game sometimes runs and sometimes closes (the game not the project).

**Comment by adamscott** [comment]
@trevorwinser Does it happen with a new project?

**Comment by trevorwinser** [comment]
> @trevorwinser Does it happen with a new project?

Yes. My Drivers are up to date, Windows 11 is up to date, and I am running Godot from Steam

**Comment by trevorwinser** [comment]
Current status:

1. Godot launcher opens.
2. Godot editor crashes with no error most of the time. Still not sure why it opens sometimes
3. Godot scene preview in editor crashes with no error half of the time.

**Comment by ZJX54959** [comment]
I had the same problem before. Have you tried the solution from [this webpage](https://nvidia.custhelp.com/app/answers/detail/a_id/5182)?

**Comment by trevorwinser** [comment]
> I had the same problem before. Have you tried the solution from [this webpage](https://nvidia.custhelp.com/app/answers/detail/a_id/5182)?

This fixed it!!! Thank you so much.

**Comment by mp3file64-netizen** [comment]
> I had the same problem before. Have you tried the solution from [this webpage](https://nvidia.custhelp.com/app/answers/detail/a_id/5182)?

what was your specs? i still got the problem and i cant fix it
