### ISSUE TITLE
`@icon` not works with PNG on the FileSystem

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#93221]
### Tested versions

v4.3.dev6.mono.official [89850d553]

### System information

Windows 11

### Issue description

I have tested around using custom resource icons and find it is not working with PNG as image.
The File System is not showing the icon, but the Node inspector it shows.

![image](https://github.com/godotengine/godot/assets/347037/48686829-0746-40e2-a55e-a4020a02421f)

### Steps to reproduce

Create a simple script and use a PNG format icon 
```
@icon("res://test-suite.png")
class_name ScriptWithIcon
extends Node
```

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/92942

**Comment by dalexeev** [comment]
> I have tested around using custom resource icons and find it is not working with PNG as image.

Does this work with SVG or some other format? Or does the FileSystem dock not display class icons at all (which might make sense since FileSystem displays file/resource types, not classes)? Please describe the problem more precisely, avoid details that are not important. Thanks!

**Comment by MikeSchulze** [comment]
Sorry for the confusion, I was guessing the `@icon` works in general and not only for resources.

I rebuild my examples as resource and saved, and it works for SVG and PNG
![image](https://github.com/godotengine/godot/assets/347037/e6c6a425-f6c9-46cd-8abc-f6cba2b02e43)


But I would swear that I had seen one of my GDScripts in the FileSystemDock with the icon when testing with Godot 4.3.beta1, only the extended classes did not have the icon.
The GDScript is just defined like:
```gdscript
@icon("res://addons/XXX/logo.png")
class_name ByClass
extends Node
```
But I can't reproduce it anymore. I have no idea what's going on here ;)
The resource file with the icon is working, so I close this issue.
