### ISSUE TITLE
Exporting project for iOS might overwrite files without warning

### ISSUE THREAD

**Issue by davidpdrsn** [godotengine/godot#93222]
### Tested versions

- Reproducible in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

I'm new to godot and had a project I wanted to export for iOS. During the export process you have to choose where to save it. Not knowing exactly which files would be created I thought I didn't want to pollute my project directory so instead I chose to save the files in the parent directory of where my project is. This resulted in godot creating a directory with the same name as the project itself, thus overwriting the project directory and deleting all the files. I don't have a backup so pretty sure I've lost two months of work 🙃

I think a warning that something is about to be overwritten would be good.

### Steps to reproduce

1. Make a project. Whats it contains shouldn't matter.
2. Export the project for iOS to the parent directory of where the project is. So if `project.godot` is at `/foo/bar/project.godot` then export to `/foo`.
3. The `bar` directory containing all the files has now been overwritten and contains part of the Xcode project. The project itself is gone.

Not sure that one must export for iOS but thats the only target I tested.

### Minimal reproduction project (MRP)

Works in any project but here is one that just contains a label:

[Export Overwrite Demo.zip](https://github.com/user-attachments/files/15857159/Export.Overwrite.Demo.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/89715

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by Calinou** [comment]
> I don't have a backup so pretty sure I've lost two months of work 🙃

You can probably look into using file forensic tools (not sure what's popular on macOS nowadays), although you won't be able to recover filenames or their metadata, only their contents. Make sure to do this before writing too much stuff on the disk, or you won't be able to recover all files anymore.
