### ISSUE TITLE
Unload assemblies of .NET failed

### ISSUE THREAD

**Issue by Andres-Perez-Leonis** [godotengine/godot#93234]
### Tested versions

Version: 4.2.2

### System information

Ubuntu 24.04 - Godot 4.2 - .Net 6.0 - AMD Ryzen™ 7 5700U with Radeon™ Graphics × 16

### Issue description

When I trying to build my Godot project, the error of assemblies always appears.   
modules/mono/mono_gd/gd_mono.cpp:529 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/mono_gd/gd_mono.cpp:529 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/mono_gd/gd_mono.cpp:529 - .NET: Failed to unload assemblies. Please check https://github.com/godotengine/godot/issues/78513 for more information. (User)
  modules/mono/mono_gd/gd_mono.cpp:513 - .NET: Giving up on assembly reloading. Please restart the editor if unloading was failing. (User)
  
  I don`t use any external library like System.Text.Json. I checked every ideas of the github error and nothing. I want to give more information but i can not contribute anything. The error appears from one day to the next. 

### Steps to reproduce

Click in build button.

**Comment by AThousandShips** [comment]
Please comment on the issue that you're directed towards, closing as there's an issue open for this
