### ISSUE TITLE
Inspector does not set 'float' or 'int' values until you click outside of the Field

### ISSUE THREAD

**Issue by z4gon** [godotengine/godot#93245]
### Tested versions

Reproducible in: 4.3.beta1.official [a4f2ea9]

### System information

macOS Sonoma 14.1.1 - OpenGL API 4.1 Metal - 88 - Compatibility - Using Device: Apple - Apple M1 Pro

### Issue description

Given a custom Resource like this:
```gdscript
class_name MyCustomResource
extends Resource

@export var my_float: float = 100.1
@export var my_int: int = 100
@export var my_string: String = "bye"
```

And a scene with a script like this:
```gdscript
class_name MyNode
extends Node

@export var my_custom_resource: MyCustomResource

func _ready() -> void:
	print("my float = ", my_custom_resource.my_float)
	print("my int = ", my_custom_resource.my_int)
	print("my string = ", my_custom_resource.my_string)
```

When running the scene, the output console will show the values in the resource.
Changing the `string` value and then immediately running the scene works as expected, the new value is shown.
If you change a `float` and `int` value in the Inspector and run the scene again immediately, you see the wrong values:
![video](https://github.com/godotengine/godot/assets/4588601/711a9f5a-644d-4617-a192-7069cab22155)

The `float` and `int` fields only commit the values to the `.tres` file when you click outside of the Field (into other fields, the code editor, or the scene tree)

### Steps to reproduce

1. create an empty project
1. create a `script` extending `Resource`, give it `class_name MyCustomResource`
1. make it `@export` a `float`, an `int` and a `string`
1. create a `my_custom_resource.tres` resource with the script `MyCustomResource`
1. double click `my_custom_resource.tres` to edit its exported values on the Inspector
1. change the string value, observe how the the output console immediately says `Set my_string` as you type in characters
1. change the float or int value, observe how the the output console only says `Set my_float` or `Set my_int` if you click outside of the Field

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
I believe this is intentional, so that entering certain values will not make the editor slow down to a crawl (e.g. if real-time processing is required by the node).

**Comment by z4gon** [comment]
Oh I see, that makes sense.
I guess what surprised me the most was that hitting play wouldn't commit what I had as a "draft" either.

**Comment by Deozaan** [comment]
Pressing play or saving the scene should save the value, IMO.

**Comment by AThousandShips** [comment]
> And Ctrl + S is also ignored until I click outside the Field.

That's an existing bug report:
* https://github.com/godotengine/godot/issues/74557

**Comment by z4gon** [comment]
closing in favor of #74557
which is more comprehensive
