### ISSUE TITLE
Switching from 4.2 to 4.3: constantly getting a "Can't remove open menu!" message

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#93241]
### Tested versions

v4.3.beta1.official [a4f2ea91a]
Works without issues in 4.2

### System information

Godot v4.3.beta1 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

A perfectly working project (a very simple project, tested hundreds of times in 4.2) in 4.3 constantly spams
![image](https://github.com/godotengine/godot/assets/106015575/36e08641-9fcf-458e-a0d9-e5b3ffd557a5)

I tested the same project again in 4.2 and it works just fine (in case it's related: in 4.3 the same project also becomes buggy, for example at one point a super simple scene with 10 lines of code just freezes, but I can't isolate it).

### Steps to reproduce

I can't figure out what's causing it. I usually notice it after I click on something in the Scene Tree but it might as well be that it appeared earlier but I missed it.

### Minimal reproduction project (MRP)

Happens only in projects, while working and switching between nodes / scenes.

**Comment by bruvzg** [comment]
Should be already fixed by https://github.com/godotengine/godot/pull/92781

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92789. The fix will be available in the next beta, or you can [compile](https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html) the `master` branch right now to benefit from it.
