### ISSUE TITLE
application/run/disable_stderr does not work

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#93244]
### Tested versions

4.3.beta1

### System information

Windows 11 - Godot 4.3.beta1 - Forward+

### Issue description

When changing the application/run/disable_stderr setting to true, it does keep printing errors to the console even when reloading the project.

### Steps to reproduce

Create a node, attach a script to it, add the lines
```
extends Node

@onready var node = get_node("hi")
```
Turn the application/run/disable_stderr to true, reload the project and the error will print anyway.

### Minimal reproduction project (MRP)

[minimal_project.zip](https://github.com/user-attachments/files/15860058/minimal_project.zip)

**Comment by AThousandShips** [comment]
Can't replicate, no error is printed to the console (it is printed in the debugger though, is this what you mean?)

**Comment by agrimminck** [comment]
Yes, I meant the debugger, there are no errors then, sorry!

**Comment by AThousandShips** [comment]
Easy mistake!
