### ISSUE TITLE
[4.3-beta1] Floating script editor breaks 3D viewport

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#93253]
### Tested versions

- Reproducible in 4.3-beta1
- NOT reproducible in 4.3-dev6

### System information

Windows 11, geForce 4080, Godot 4.3-beta1, Forward+

### Issue description

Making the script editor floating causes the 3D viewport to become unresponsive.

### Steps to reproduce

- Open any project
- On the 'Script' tab click the 'Make the script editor floating.' button at top right to enable floating script editor
- Move the script window onto a second monitor
- Try to move in the 3D viewport back on the first monitor with your mouse. For example hold middle mouse button down and move your mouse.

It seems to be an input related issue. Framerate in the viewport remains perfectly fine. It's just mouse input that seems to not work anymore.

### Minimal reproduction project (MRP)

N/A. Happens in any and all projects.

**Comment by smix8** [comment]
Not reproducible for me with those steps on either beta1 or Godot master.

**Comment by Flynsarmy** [comment]
I found a potential missing step. This problem only occurs if I move the script tab to a second monitor before trying to rotate in 3D viewport. I've updated the set of steps above.

I had someone on linux try and he couldn't replicate. Perhaps this is a Windows only bug? I'm on Win11 with and RTX 4080 geforce v555.99 drivers. Both monitors are 4K. Godot is on primary, script editor is moved to secondary.

**Comment by matheusmdx** [comment]
This looks like another case of bug caused by pr https://github.com/godotengine/godot/pull/91361, @Flynsarmy can you check the comentary (https://github.com/godotengine/godot/issues/92954#issuecomment-2158618652) and do the steps to confirm?

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by Flynsarmy** [comment]
I can confirm the issue is fixed in https://github.com/godotengine/godot/pull/92742

**Comment by matheusmdx** [comment]
> I can confirm the issue is fixed in #92742. Since that ones already been merged are we good to close this issue?

Yep, no problem in close
