### ISSUE TITLE
The value of INV_VIEW_MATRIX in double build version is different from usual

### ISSUE THREAD

**Issue by Khasehemwy** [godotengine/godot#93259]
### Tested versions

4.3.dev [71699e08c9df78b7203fa4ef9cede28e995d6ace]

### System information

Windows10[22H2] - godot.windows.editor.dev.double.x86_64.exe - Vulkan(Forward+)

### Issue description

The INV_VIEW_MATRIX value is different in double build version, it looks wrong.
double build: godot.windows.editor.dev.double.x86_64.exe
regular build: godot.windows.editor.dev.x86_64.exe

Use Nsight Graphics 2024.1.0, Get the render info, I see the INV_VIEW_MATRIX is different in double version.

the regular version:
![normal](https://github.com/godotengine/godot/assets/57032017/79387954-976b-4143-bf4c-470cc6d4b018)

the double version:
![double](https://github.com/godotengine/godot/assets/57032017/27b44b28-b8c3-4188-addb-5a9b8ac9554c)

### Steps to reproduce

1. use `scons platform=windows dev_build=yes precision=double` build a double version and `scons platform=windows dev_build=yes` build a regular version.
2. create a scene, place some mesh.
3. use this shader for screen quad mesh (postprocess):
```gdshader
shader_type spatial;
render_mode unshaded;

uniform sampler2D DepthTex : hint_depth_texture;

void vertex() {
	// Called for every vertex the material is visible on.
	POSITION = vec4(VERTEX.xy, 1.0, 1.0);
}

void fragment() {
	// Called for every pixel the material is visible on.
	float depth_ndc = texture(DepthTex, SCREEN_UV).x;
	vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth_ndc);
	vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	view.xyzw /= view.w;
	vec4 world = INV_VIEW_MATRIX * view;
	ALBEDO = world.xyz;
}
```

4. run scene with double version and regular version, the two render results are different:

the scene:
![scene](https://github.com/godotengine/godot/assets/57032017/eeb2d5ea-6aff-43c4-98bd-fdb1dd9fdd0f)

regular:
![normal_display](https://github.com/godotengine/godot/assets/57032017/925a1e38-f7f4-4128-9cc7-fd5d3bbccb9a)

double:
![double_display](https://github.com/godotengine/godot/assets/57032017/f8e7679b-4981-40b7-a9d3-3ceb4072f487)

### Minimal reproduction project (MRP)

[inv_view_test.zip](https://github.com/user-attachments/files/15864199/inv_view_test.zip)

**Comment by Khasehemwy** [comment]
I guess it's because of the extra minus sign here, but after the modification, the editor window screen will be reversed.
![code](https://github.com/godotengine/godot/assets/57032017/7be1c756-9492-4933-b263-651ea8beb4f4)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85711

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by clayjohn** [comment]
@Khasehemwy Can you test https://github.com/godotengine/godot/pull/93108 and confirm it it fixes the problem you are seeing?

**Comment by Khasehemwy** [comment]
> @Khasehemwy Can you test #93108 and confirm if it fixes the problem you are seeing?

Yes, it fixed. I also deleted the minus sign before, but did not modify the glsl code, it causes the editor  window to look flipped.
