### ISSUE TITLE
[Feature Request] Disable and Enable Collision of a CollisionShape2d

### ISSUE THREAD

**Issue by balfrog** [godotengine/godot#9326]
An checkbox in the node inspector and a new method for CollisionShape2d and 3d maybe so you can disable and enable the collision in runtime and not deleting it and re instancing it to a scene. 

For example an attack animation where the hitbox collision is enabled in certain frames or a wall/door where the collision is disabled or enabled pressing a button

EDIT: with disable collision I mean It disables all kind of information that can be send and received. Not only for colliding with another body that makes it to stop moving

**Comment by Ovnuniarchos** [comment]
A shape (of any kind) can be set to Trigger to not be taken into account for collision. (although it still can detect enter/exit conditions)

**Comment by balfrog** [comment]
Yes but I meant not to be detected at all, I was trying to do an attack animation and I had to put the CollisionShape2d in an Area2d node so I can disable the monitoring in the area2d and enable it in certain frames

**Comment by eon-s** [comment]
Removing it from all the layers is not enough?

**Comment by balfrog** [comment]
That's a solution but not the best one, I mean having to disable it in every layer and enabling it every time its needed in a big game its a bit messy and a bit annoying, with an option to disable it so it doesn't bother anything I thinks its better :) I'm suggesting a feature.

**Comment by balfrog** [comment]
That's a solution but not the best one, I mean having to disable it in every layer and enabling it every time its needed in a big game its a bit messy and a bit annoying, with an option to disable any kind of collision so it doesn't bother anything and it doesn't worry about everyone else I thinks its better :) I'm suggesting a feature so someone who gets in the same as me, has the solution in only a click or a line of code.

**Comment by balfrog** [comment]
That's a solution but not the best one, I mean having to disable it in every layer and enabling it every time its needed in a big game its a bit messy and a bit annoying, with an option to disable any kind of collision so it doesn't bother anything and it doesn't worry about everyone else I thinks its better :) I'm suggesting a feature so someone who gets in the same as me, has the solution in only a click or a line of code.

This is useful for hitbox attacks in a melee combat or enemies that does certain timing attacks like in darksouls

**Comment by reduz** [comment]
i was actually working on this feature, will commit it briefly, so closing this. thanks for your work though!
