### ISSUE TITLE
SubViewportContainers with mouse filter PASS and no children mark input as handled

### ISSUE THREAD

**Issue by jedesjardins** [godotengine/godot#93272]
### Tested versions

- Reproducible in 4.3.beta1, 4.2.2.stable

### System information

Godot v4.3.beta1 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When there are two overlapping SubViewportContainers, the top SubViewportContainer seems to consume mouse inputs, even when it is empty. Both SubViewportContainers have Mouse Filter set to PASS.

### Steps to reproduce

Here's an example node structure 
```
Control
|-SubViewportContainerA
| |-SubViewportA
|   |- Node2D
|-SubViewportContainerB
  |-SubViewportB
```

The Node2D has the following script attached:
```
extends Node2D

func _input(event):
    if event is InputEventMouseButton and event.is_pressed():
        print("%s: input" % name)

func _unhandled_input(event):
    if event is InputEventMouseButton and event.is_pressed():
        print("%s: unhandled input" % name)
```

In this example, neither print statement occurs.
If you reparent the Node2D to SubViewportB, both print statements are hit.

### Minimal reproduction project (MRP)

[subviewportcontainerfailure.zip](https://github.com/user-attachments/files/15875013/subviewportcontainerfailure.zip)

**Comment by KoBeWi** [comment]
This is not a bug. Mouse filter PASS only passes the events to its parents, not siblings. See #55432
