### ISSUE TITLE
AtlasTexture as a cursor uses full image

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#93277]
### Tested versions

does not work in. Godot v4.3.beta1 works in Godot 4.3dev4

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### Issue description

Using an AtlasTexture as a cursor uses the entire image, i swear this was an issue before that was fixed? i cant find the post though

https://github.com/godotengine/godot/assets/40964335/89f03a23-2340-45f4-ae8f-fc20a7cb4846

Had to use this crappy video because for some reason when I screen record it inaccurately makes the cursor appear really tiny.

### Steps to reproduce

call DisplayServer.cursor_set_custom_image with an atlast texture

### Minimal reproduction project (MRP)

[New Compressed (zipped) Folder.zip](https://github.com/user-attachments/files/15877454/New.Compressed.zipped.Folder.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92671. This is fixed in the latest `master` branch (and the upcoming 4.3.beta2).
