### ISSUE TITLE
Tileset editor paint properties popup is using project's clear color

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#93278]
### Tested versions

v4.2.2.stable.official
v4.3.beta1.official [a4f2ea91a]

### System information

Godot v4.3.beta1 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Forwarding [this issue](https://github.com/passivestar/godot-minimal-theme/issues/7) here because this appears to be an engine bug

With minimal theme (it has transparent tree backgrounds and that popup is drawing a Tree):

<img width="500" alt="image" src="https://github.com/godotengine/godot/assets/60579014/17f13308-936b-41a6-a3d6-54360b0019e0"><br>

<img width="500" alt="image" src="https://github.com/godotengine/godot/assets/60579014/c5638b64-24c5-4ed7-80b4-34de7c0d4fa5"><br>

With default theme (notice pink corners):

<img width="500" alt="image" src="https://github.com/godotengine/godot/assets/60579014/3f978e21-f922-419f-bc4f-1c9b1397c4f7">

### Steps to reproduce

1. Set `rendering/environment/defaults/default_clear_color` to something bright
2. Open the "Select a property editor" popup and notice the bright corners

### Minimal reproduction project (MRP)

N/A

**Comment by Gnumaru** [comment]
Notice that this is not a godot 4.3 bug. I was using **v4.2.2.stable.official [15073afe3]** on windows 10 x64 when I first reported it.

**Comment by passivestar** [comment]
Same pink corners when not using a custom theme:

<img width="300" alt="image" src="https://github.com/godotengine/godot/assets/60579014/88b61ca2-423a-4515-8792-80b94757db6d">
