### ISSUE TITLE
MultiplayerSpawner throws error when more than one scene is attached

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#93283]
### Tested versions

4.3.beta1

### System information

Windows 11 - Godot 4.3.beta1 - Forward+

### Issue description

It is very straightforward, if the MultiplayerSpawner has more than one scene attached, the second one can not spawn on the client's side. I tried this also with two different MultiplayerSpawners, each one with one scene attached, still the same. I also tried with public and non-public visibility on, still the same.

### Steps to reproduce

Attach 2 scenes to a MultiplayerSpawners and try to instantiate them on the server. One of them will not get spawned on the client and will give errors.

### Minimal reproduction project (MRP)

[minimal project.zip](https://github.com/user-attachments/files/15878901/minimal.project.zip)

**Comment by agrimminck** [comment]
If possible, I would like to know if I would be able to use the godot with this issue resolved, right now I can not keep progress until this is corrected

**Comment by hakro** [comment]
Looking at the MRP, I think it's just a `MultiplayerSpawner` misconfiguration in the project.

In `server.tscn`, the spawner's list contains `res://entity_server.tscn` and `res://entity_server_2.tscn`

But in `client.tscn`, the spawner is configured with `res://entity_client.tscn` and `res://entity_client_2.tscn`, which does not match with the server's spawner list. Changing those to `res://entity_server.tscn` and `res://entity_server_2.tscn` in the client makes it work.

I'm not sure I understand what you're trying to make, but if your goal is to have 2 server entities, and, 2 client entities in the game, then both spawners should have all four entity scenes in their Auto Spawn List.

No need to have multiple spawners as you mentioned. Only one should work fine.

**Comment by agrimminck** [comment]
So putting the same scene is what it is meant to work for? I thought you could use them while having a "duplicate" scene of your server, but doing everything with client side scripts and nodes. That's how I structured the minimal project. Thank you for the aclaration of this topic. I will close this issue.

**Comment by agrimminck** [comment]
> But in `client.tscn`, the spawner is configured with `res://entity_client.tscn` and `res://entity_client_2.tscn`, which does not match with the server's spawner list. Changing those to `res://entity_server.tscn` and `res://entity_server_2.tscn` in the client makes it work.

I tried your approach and it does not work on my side. I created a minimal project that has fewer scenes, it's not sepparated into client and server and that does not work either.


[minimal project.zip](https://github.com/user-attachments/files/15893800/minimal.project.zip)

**Comment by agrimminck** [comment]
> I'm not sure I understand what you're trying to make, but if your goal is to have 2 server entities, and, 2 client entities in the game, then both spawners should have all four entity scenes in their Auto Spawn List.

No, I tried to sepparate the client and the server into different scenes and scripts. But doing it without dividing them also works for me, but as I mentioned before, it does not work on my side.

**Comment by hakro** [comment]
Ok. This seems to be another bug where the `MultiplayerSynchronizer` tries to send data even if there are no properties to synchronize.

In your case, both synchronizers are indeed empty. Adding any property to both fixes the issue. You'll need to do that anyway, otherwise the `MultiplayerSynchronizer` can be removed.


![Screenshot_20240619_113620](https://github.com/godotengine/godot/assets/3624853/eafb351b-54be-4ace-90d5-03b9f3244c49)

That bug is already logged in here https://github.com/godotengine/godot/issues/91225

**Comment by agrimminck** [comment]
> That bug is already logged in here #91225

Thank you so much and sorry for the duplicate! Case closed.
