### ISSUE TITLE
Bitmap font from image doesn't line up with other fonts in RichTextLabel.

### ISSUE THREAD

**Issue by mageowl** [godotengine/godot#93282]
### Tested versions

Godot v4.3.dev6, Godot v4.3.beta1

### System information

Godot v4.3.dev6 - Linux Mint 21.1 (Vera) - X11 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Plus Graphics (ICL GT2) () - Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 Threads)

### Issue description

When importing a pixel font from a png or other image, the glyphs do not line up properly with other fonts using a ttf.
The smaller font was imported from a png, wheras the larger one is a ttf file.

## Rich text label
![2024-06-17_1726x644](https://github.com/godotengine/godot/assets/32573897/9f56c515-9261-47ab-be82-1f1b4cbd7a2d)
## Import settings
![2024-06-17_762x880](https://github.com/godotengine/godot/assets/32573897/08c6090f-ad7e-44d4-816b-21e71e97c73c)

### Steps to reproduce

1. Import a font from an image. ([example file](https://github.com/godotengine/godot/assets/32573897/323c7f5d-262f-41d2-b050-6e20f3af112b))
2. Apply one font to a RichTextLabel's italics font.
3. Turn on BBCode
4. Enter example text: `[i]123[/i]123`
5. Notice that the two fonts do not line up.

### Minimal reproduction project (MRP)

[minimal-reproduction-project.zip](https://github.com/user-attachments/files/15878650/minimal-reproduction-project.zip)

**Comment by bruvzg** [comment]
It's aligned the way you have drawn it in the image, there's no way to tell where baseline is automatically. If you want to adjust it, you can set character margins (part of the characters that is cut) and glyphs drawing offsets (per range, add 3 space separated numbers to the end of range string: advance, x offset, y offset).

<img width="693" alt="Screenshot 2024-06-18 at 07 59 00" src="https://github.com/godotengine/godot/assets/7645683/793a7a7b-1e16-4d05-8b95-3d45c4ff69cc">

**Comment by mageowl** [comment]
Thank you!
