### ISSUE TITLE
using Godot 4.0 Android plugins on Godot 4.2+ makes the game crash instantly 

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#93290]
### Tested versions

reproducible in: 4.2.2.stable, 4.2.1.stable

### System information

Windows 10 - Godot 4.1.4 - 4.2.2 -Stable

### Issue description

I have an Android plugin from Godot 4.0, but the game instantly crashes when I try to run it on Godot 4.2+.
one more thing I tested, I replaced the Android export template 4.1.4 (from the export_templates folder) with 4.2.1 and the problem is solved.
so the problem is on Androdi Export template 4.2+

### Steps to reproduce

- open the attached project and run it in Godot 4.2+
- Install Android build Template
- run it on an Android phone

### Minimal reproduction project (MRP)

[AdiveryTest.zip](https://github.com/user-attachments/files/15880693/AdiveryTest.zip)

**Comment by dorjoosoft** [comment]
As I have created Godot plugins for Android, it is necessary to rebuild your plugin with the new .aar file provided for each major, and some minor engine version updates. This process as I know resolves the problem.

**Comment by DexterFstone** [comment]
> As I have created Godot plugins for Android, it is necessary to rebuild your plugin with the new .aar file provided for each major, and some minor engine version updates. This process as I know resolves the problem.

I understand what you mean, but as far as I remember, it was said in a part of the document that plugins written with v1 will still work with v2.

**Comment by dorjoosoft** [comment]
This is from Godot docs page [here](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html).

> Android plugin[¶](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html#android-plugin)
> Version 1 (v1) of the Android plugin system was introduced in Godot 3 and compatible with Godot 4.0 and 4.1. That version allowed developers to augment the Godot engine with Java, Kotlin and native functionality.
> 
> Starting in Godot 4.2, Android plugins built on the v1 architecture are now deprecated. Instead, Godot 4.2 introduces a new Version 2 (v2) architecture for Android plugins.
