### ISSUE TITLE
Incorrect shadow with no culling

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9330]
**Operating system or device - Godot version:** Godot master, Linux

**Issue description:**
Even with culling disabled, light seems to pass through the object. The object should catch that light and not let it pass through.

![screenshot from 2017-06-23 12-06-23](https://user-images.githubusercontent.com/1642015/27479653-abdb0aee-580c-11e7-88f7-f9ed9ab870ef.png)

**Link to minimal example project:**
[shadowbug.zip](https://github.com/godotengine/godot/files/1097582/shadowbug.zip)

**Comment by gamergamesz** [comment]
yeah problem is same with  omni light too only spotlight gives some good result

**Comment by gamergamesz** [comment]
i think shadow is still a mess

**Comment by reduz** [comment]
@gamergamesz care to elaborate? I tested all cases and it seems to be working

**Comment by gamergamesz** [comment]
i will report an issue with test file and screenshot soon!
