### ISSUE TITLE
AnimationTrackKeyEdit inspector not displayed on click of bezier key, only on click and drag

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#93308]
### Tested versions

- Reproducible in: v4.3.dev4.official [df78c0636], v4.3.beta1.official [a4f2ea91a], v4.3.beta.gh [0ca0b462e]
- Not reproducible in: v4.2.2.stable.official [15073afe3], v4.3.dev3.official [36e943b6b]

Regression between 4.3.dev3 and 4.3.dev4.

### System information

Godot v4.3.beta (0ca0b462e) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5123) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When clicking on a bezier track key in the curve editor, the key edit inspector is not displayed.

### Steps to reproduce

1. Open provided MRP.
2. Open node_3d.tscn
3. Click on the AnimationPlayer.
4. In the Animation editor panel, select the MRP animation.
5. Click the toggle to enter the bezier curve editing mode.
6. Click on a key in the editor (make sure to only click, not click and drag).

See that the inspector panel does not update to show the info of the selected key.

### Minimal reproduction project (MRP)

[bezier_select.zip](https://github.com/user-attachments/files/15887250/bezier_select.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #88459 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/3b8c958a-1f55-432e-89ab-f2cd06241a82)

**Comment by akien-mga** [comment]
CC @CookieBadger @TokageItLab

**Comment by CookieBadger** [comment]
looking into it
