### ISSUE TITLE
Unable to select nodes created in GDscript, in a editor @tool 

### ISSUE THREAD

**Issue by Ross-Carran** [godotengine/godot#93306]
### Tested versions

- Reproducible in 4.3 beta, 4.3 commit:e2fc6d38c
- Works in 4.2.2-stable

### System information

Godot v4.3.beta (e2fc6d38c) - Asmi 24.04 24.04 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (nvidia; 555.52.04) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Unable to select nodes created from gdscript as part of a node as a tool using @tool.
godot renders the nodes in the 3d display but the only node that is select able is the parent node.

### Steps to reproduce

create nodes with a gdscript that is used as a tool @tool

### Minimal reproduction project (MRP)

[godot-BSPTree.zip](https://github.com/user-attachments/files/15886968/godot-BSPTree.zip)

**Comment by KoBeWi** [comment]
Remember to set the `owner`.

**Comment by akien-mga** [comment]
This is an intentional change done in #92188, as it was unexpected to be able to select nodes which aren't part of the scene tree view. Setting the `owner` will add them to the scene tree and make them selectable.
