### ISSUE TITLE
1/3 = 0 but 1.0/3 = 0.333333

### ISSUE THREAD

**Issue by hkh777uk** [godotengine/godot#93315]
### Tested versions

Tested in v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4314) - 13th Gen Intel(R) Core(TM) i7-1360P (16 Threads)

### Issue description

If you print the value of 1/3, you get 0, but printing 1.0/3, you get 0.333333. I know about integer division and how int/int = int, but I just don't see how this is useful. It creates wasted time debugging an issue caused by default behaviour.

### Steps to reproduce

Just type "print(1/3)" in the _ready function.

### Minimal reproduction project (MRP)

```
extends Node


func _ready():
       print(1/3)
```

**Comment by AThousandShips** [comment]
This is because `1/3` is integer division, see [here](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#operators) under the notes

**Comment by dalexeev** [comment]
Thanks for your input!

This is not a bug, but _expected behavior_ (this means that it _works as intended_, not whether users expect it or not). Yes, this looks confusing to some users (including me) coming from Pascal, Python, JavaScript and many other languages​. However, this matches C++ and some other languages. There are probably also technical reasons why it was implemented this way initially (GDScript uses `Variant` a lot, including for evaluating expressions).

The most important, we have already discussed this issue and could not reach a consensus (opinions were divided approximately 50 to 50), see godotengine/godot-proposals#1866. Therefore, we decided to maintain the status quo.

We have no plans to revisit the issue in 4.x as it would break compatibility. Which would be even worse than the current situation. This fact has already been [properly documented](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#operators), users are widely aware of it, and the behavior is often mentioned in various tutorials. Yes, at first you may not be aware of this or may often make mistakes. But over time, you somehow discover it and get used to it.
