### ISSUE TITLE
Skeleton3D with bones causes continuous editor update

### ISSUE THREAD

**Issue by stoofin** [godotengine/godot#93321]
### Tested versions

Does not occur in 4.2
Does not occur in 4.2.2
Does occur in 4.3beta1

### System information

Godot v4.3.beta1 - Ubuntu 24.04 LTS 24.04 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

The editor redraws constantly when a Skeleton3D with at least 1 bone is present
(Editor Settings/Interface/Editor/Update Continuously is unchecked)

### Steps to reproduce

Open a rigged model or add one to the open scene.  Enable the Update Spinner and watch it spin.

### Minimal reproduction project (MRP)

This scene triggers it:
```
[gd_scene format=3 uid="uid://brl1aoxyriojm"]

[node name="rigged-cube" type="Node3D"]

[node name="Skeleton3D" type="Skeleton3D" parent="."]
bones/0/name = "Bone"
bones/0/parent = -1
bones/0/rest = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0)
bones/0/enabled = true
bones/0/position = Vector3(0, 0, 0)
bones/0/rotation = Quaternion(0, 0, 0, 1)
bones/0/scale = Vector3(1, 1, 1)
```
[editor-spinning-min.zip](https://github.com/user-attachments/files/15890877/editor-spinning-min.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #87888 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/3dc9dec4-08b0-4bee-a891-f665252377b8)

**Comment by TokageItLab** [comment]
This depends on the existence of the internal PhysicalBone simulator and should not occur if the compatibility mode is disabled.
