### ISSUE TITLE
CharacterBody3D.move_and_slide() doubles in speed as "physics ticks per second" gets higher (when sliding against wall and floor simultaneously)

### ISSUE THREAD

**Issue by LightningStorm0** [godotengine/godot#93334]
### Tested versions

- Reproducible in v4.2.2.stable.official [15073afe3]

### System information

Windows 10 - Godot v4.2.2.stable.official [15073afe3] - Vulkan (Forward+)

### Issue description

When a CharacterBody3D is sliding against a wall and a floor at a very shallow angle and certain speeds, it will go twice as fast as it should. This starts happening at anything above 60 physics ticks per second, and becomes more constant the higher the ticks per second is raised.

https://github.com/godotengine/godot/assets/32445729/97781b50-7b51-4fdb-b96a-43c3e5448883

![before contact](https://github.com/godotengine/godot/assets/32445729/7679b51c-05c5-4798-9b3c-e73b717c7579)

![during contact](https://github.com/godotengine/godot/assets/32445729/c4fdb7ba-7884-4e00-a95f-4053f2493f1b)

![after contact](https://github.com/godotengine/godot/assets/32445729/51747b91-25c7-4947-a99c-bf0ba7c7583a)

The cube turns red when it is_on_wall() and is_on_floor()

### Steps to reproduce

Place 2 static bodies, one wall and one floor. (I used BoxShapes)

Create a CharacterBody3D. (Again I used a BoxShape)

Place the CharacterBody3D so it is almost touching the 2 static bodies. (I did it 0.01 away on the y and z axes)

Set the velocity so it will barely brush up against the wall and floor while moving across them. (Vector3(-4.999919, -0.125, -0.028451) worked for me as this was in the range of velocities causing me issues in another project)

Set your Physics Ticks Per Second to a value higher than 60. (120 works, but it is easiest to observe at about 240)

### Minimal reproduction project (MRP)

[move_and_slide_bug.zip](https://github.com/user-attachments/files/15895453/move_and_slide_bug.zip)

**Comment by rburing** [comment]
Not reproducible in 4.3-beta1. I think this was already fixed by https://github.com/godotengine/godot/pull/90915 (cherry-picked for 4.2.3).

**Comment by LightningStorm0** [comment]
It looks like an even more specific issue with this problem is #66249. Glad to see this is already fixed in 4.3!
