### ISSUE TITLE
Distance Fade PixelDither and ObjectDither does not work when usign Compatibility Rendering

### ISSUE THREAD

**Issue by LBranco27** [godotengine/godot#93356]
### Tested versions

- Reproducible in: 4.2.2.stable and 4.3.beta1 [a4f2ea91a]

### System information

Arch Linux - Godot v4.2.2.stable - OpenGL (Compatibility) - dedicated NVIDIA GeForce GTX 3070 (nvidia, 550.90.07) - AMD Ryzen 9 5900X 12-Core Processor

### Issue description

Distance Fade PixelDither and ObjectDither does not work when using Compatibility Rendering.
It should work or at least show a warning indicating that this feature isn't working at the moment.

https://github.com/godotengine/godot/assets/33069140/8a185959-2a86-46e7-87c1-deb65d780a0f

### Steps to reproduce

MeshInstance3D with material as StandardMaterial3D's Distance Fade configured to use PixelDither or ObjectDither 

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/15902896/mrp.zip)

**Comment by mews6** [comment]
I'll be taking a look into this, if nobody opposes. It might take a while for me to figure out, but I'll share whatever i find here. Would it be a good idea to leave the warning somewhere while we come up with a sound solution as a first step?

**Comment by LBranco27** [comment]
> I'll be taking a look into this, if nobody opposes. It might take a while for me to figure out, but I'll share whatever i find here. Would it be a good idea to leave the warning somewhere while we come up with a sound solution as a first step?

I think it would be good to leave a warning if this ends up taking too much time to find a solution. I could make this warning if I knew how.

**Comment by Calinou** [comment]
There's already a PR addressing his: https://github.com/godotengine/godot/pull/89528

**Comment by LBranco27** [comment]
> There's already a PR addressing this: #89528

I can confirm that this PR solves the issue!
