### ISSUE TITLE
AnimationPlayer: Keyframing doesn't work

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#9337]
**Operating system or device - Godot version:**
Arch Linux, Godot 3 master

**Issue description:**

Setting keyframes to animate objects currently doesn't seem to work in Godot 3. 

**Steps to reproduce:**
1. Set up a simple scene with an AnimationPlayer
2. Add a new animation and try to animate a sprite (e.g position) using keyframes
3. The properties of the previous keyframes are ignored (hence no animation)

**Link to minimal example project:**
The following example works in Godot 2.1.3 but not in Godot 3:

![godot_anim](https://user-images.githubusercontent.com/7927471/27502470-92c03076-5874-11e7-90fb-b5f54dedaea7.gif)

**Comment by nunodonato** [comment]
You can use the key icon in the inspector until the fix is merged. 
Thanks

**Comment by novemberist** [comment]
Thanks for the tip. I feel a little stupid for not trying that myself before, though.
