### ISSUE TITLE
[Emscripten/Javascript] Missing path slashes on windows during emscripten linking.

### ISSUE THREAD

**Issue by Mustard867** [godotengine/godot#9338]
Windows 10 Pro Insider Preview Build 16215.rs_prerelease.170603
Current godot master branch version

I tried to build the godot binary using the steps detailed in the web build instructions in the "latest" version of the documentation. The compilation works fine, aside from warnings, but it can't find the .bc files for linking because the path it looks in has all the slashes removed. Here's the relevant output:

```
emcc @c:\users\cjb86\appdata\local\temp\tmp_ojvbg.lnk
C:/Emscripten/clang/e1.37.9_64bit\llvm-link: C:Userscjb86ROAGOgodotmodulesregister_module_types.javascript.opt.bc: error: Could not open input file: no such file or directory
C:/Emscripten/clang/e1.37.9_64bit\llvm-link: error loading file 'C:Userscjb86ROAGOgodotmodulesregister_module_types.javascript.opt.bc'
Traceback (most recent call last):
  File "C:\Emscripten\emscripten\1.35.0\\emcc", line 1201, in <module>
    shared.Building.link(linker_inputs, specified_target)
  File "C:\Emscripten\emscripten\1.35.0\tools\shared.py", line 1432, in link
    assert os.path.exists(target) and (output is None or 'Could not open input file' not in output), 'Linking error: ' + output
AssertionError: Linking error:
scons: *** [modules\libmodules.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

Steps to reproduce:

1) Setup the javascript build prerequisites according to the guide. ( http://docs.godotengine.org/en/latest/development/compiling/compiling_for_web.html )
2) Run "scons platform=javascript tools=no target=release" in powershell in the root godot directory.
3) Observe link error.

**Comment by eska014** [comment]
Does this only happen with Powershell? Does a normal command line work better?

Also try changing `\\\\` to `/` in lines 41 and 44 of `platform/javascript/detect.py`: https://github.com/godotengine/godot/blob/693eb0fa06a5be6e9664f7a413199f0100b7d289/platform/javascript/detect.py#L41-L44

**Comment by Mustard867** [comment]
Tried it with the classic command line both with and without the changes to detect.py and the results are the same.

**Comment by eska014** [comment]
Perhaps there's no need for TempFileMunge on Windows 10, please try replacing

    if (os.name == 'nt'):

with

    if (False):

in line 60 of `platform/javascript/detect.py` to disable it.

There's also apparently a legacy mode for the normal cmd, have you tried toggling that? http://tweaks.com/windows/67123/enable-new-command-prompt-features-in-windows-10/

**Comment by eska014** [comment]
I streamlined the build scripts in #17760, there shouldn't be any problems with this any more.
