### ISSUE TITLE
Update available indicator shown for the currently in-use version

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#93390]
### Tested versions

- Reproducible in v4.3.beta2.official [b75f0485b]
- Note; v4.3.beta1.official [a4f2ea91a] had a different issue with the indicator (it would show a non-existent update).

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5123) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Update available indicator shown for 4.3.beta2 while already on 4.3.beta2.

### Steps to reproduce

1. Open the project selector.
2. See 
 
![image](https://github.com/godotengine/godot/assets/5222656/0de50f44-ab26-462b-a907-3fffada72d6c)

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
![изображение](https://github.com/godotengine/godot/assets/3036176/83d760a6-ca64-4a64-ace9-2edec86776f6)

Looks like It's still to be presented in beta 2.

**Comment by nanodeath** [comment]
This might already be covered, but another case to watch out for is the .net version string:
![image](https://github.com/godotengine/godot/assets/10625/38ff7fb7-5b98-47e4-9d6b-ed675b1b4c06)
