### ISSUE TITLE
CPUParticles3D causes stutter if selected on the scene tree

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#93394]
### Tested versions

-Reproducible in: 4.3.beta2

### System information

Android 11 - Godot V.4.3.beta2- compatibility renderer

### Issue description

when i add a CPUParticles3D and assigning a mesh for it , it works fine and first
.But if I expand the mesh drop-down for the particle it becomes so slow and laggy. If i deselect the CPUParticles3D in the scene tree everything works normally again

https://youtu.be/2dX27d-Arv0?si=QxO0TXgYS6zcYDmg

### Steps to reproduce

create a project in compatibility renderer. add a CPUParticles3D,give it a mesh, expand the mesh drop-down.

### Minimal reproduction project (MRP)

N/A
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by Calinou** [comment]
My guess is that the mesh inspector preview is re-rendering when it doesn't need to. It's interactive so it can't just use the **Once** update mode, but it should either use the **When Changed** update mode if it's not doing so already (it's the Viewport default), or it should switch to the **Once** update mode at startup and once the user stops interacting with it.

**Comment by shahriarlabib000** [comment]
i think the stutter has been fixed in 4.3.beta3. CPU time seems ok. now only issue is camera view doesn't update which is most probably related to #93357. Thank you very much 😊
