### ISSUE TITLE
World Grid Glitch

### ISSUE THREAD

**Issue by Elsarques** [godotengine/godot#93405]
### Tested versions

- Reproducible in: 4.2.2 Stable

### System information

Android 14 Godot 4.2.2 Stable Mali GPU

### Issue description

The world grid is glitchy
![Screenshot_20240620_143102_Godot Editor 4](https://github.com/godotengine/godot/assets/168835907/9d10c2ac-410b-4784-ab74-1958968b8314)

### Steps to reproduce

Open Godot

### Minimal reproduction project (MRP)

[VendedorAuto.zip](https://github.com/user-attachments/files/15917754/VendedorAuto.zip)

**Comment by Chaosus** [comment]
Duplicate of https://github.com/godotengine/godot/issues/37016, and was fixed at master.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/73763.
