### ISSUE TITLE
AStarGrid2D allow_partial_path returning no path when there should be

### ISSUE THREAD

**Issue by femiaf13** [godotengine/godot#93409]
### Tested versions

- Reproduced in v4.3.beta2.official [b75f0485b]

### System information

Godot v4.3.beta2 - Fedora Linux 40.20240619.0 (Kinoite) - Wayland - GLES3 (Compatibility) - AMD Radeon RX 7900 XTX (radeonsi, navi31, LLVM 18.1.6, DRM 3.57, 6.9.4-200.fc40.x86_64) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

get_point_path() with allow_partial_path set to true in AStarGrid2D returns an empty array instead of a partial path like it should

### Steps to reproduce

- Click on empty space, pathfinding works
- Click on an obstacle tile, nothing happens
  - What _should_ happen is the ship gets a partial path and traverses it 

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/15919982/MRP.zip)

Attached is the AStarGrid2D demo from the asset library. The only change I made was in `pathfind_astar.gd` where I set allow_partial_path to true

**Comment by femiaf13** [comment]
I found https://github.com/godotengine/godot-proposals/issues/277#issuecomment-2177234313 so it seems like I'm not alone with there being some confusion

**Comment by Calinou** [comment]
> I found [godotengine/godot-proposals#277 (comment)](https://github.com/godotengine/godot-proposals/issues/277#issuecomment-2177234313) so it seems like I'm not alone with there being some confusion on how partial path is meant to work

https://github.com/godotengine/godot/pull/88047's description says:

> **Note:** This will not return a partial path to a location not in the AStar point list, the destination point still has to be a point. This is especially helpful for games where points may become disconnected due to other points being disabled during play while still permitting a path that gets close to the destination point.

cc @theashtronaut

**Comment by theashtronaut** [comment]
So while technically a disabled/solid point _is_ part of the point list, if the end point is disabled (or "solid" for the `AStarGrid2D` class) `_solve` returns early which means even when asked to return the partial path the path is still an empty array as no actual pathfinding was done yet. You can see this early return here

https://github.com/godotengine/godot/blob/master/core/math/a_star_grid_2d.cpp#L453

The original issue that the partial path implementation was for was for non-disabled points that are in the point list, finding a path close to those even if there are obstacles preventing a complete path. The picture from the original proposal (https://github.com/godotengine/godot-proposals/issues/277) showcases that intention
![image](https://github.com/godotengine/godot/assets/112137107/34417860-9b87-48c3-bd16-754ee2f221a8)

I did not change/modify the early termination present when the destination is itself disabled, however I can see the merit in having this functionality too. The main issue is this change would, unless I dragged in the partial path option into the `_solve` function to modify the early termination (which could be done if desired), mean that even for users who are not desiring a partial return the extra "processing" would happen to find that partial path even though we would then discard that result and return the empty array.

This short circuit was added as part of https://github.com/godotengine/godot/pull/27506 when disabling points became an option, as it represents a much more performant way to temporarily add/remove points from pathfinding without having to actually run the more expensive add/remove point functions. I believe the specific part of having it in `_solve` was just for the optimization of not trying to pathfind when the destination was "invalid", though this is speculation on my part as the intention wasn't directly stated anywhere.

Curious to here other's thoughts on it as well!

**Comment by RilicTheFox** [comment]
I was personally caught out by this just now. The documentation of the current behaviour in the AStarGrid2D doc lead me to believe that it would find the closest non-solid tile to a solid tile. It's very understandable why this isn't the case upon reading into it, though!

That said, I do think it should be considered inside the `_solve` function, since it makes sense in my head for `allow_partial_path` to perform the way I originally thought it would. I'll work around it in the meantime!
