### ISSUE TITLE
Black get_texture() from viewport on desktop, works fine on mobile.

### ISSUE THREAD

**Issue by Bimbam360** [godotengine/godot#93422]
### Tested versions

- Reproducible in v4.3.beta1.official [a4f2ea91a] and v4.3.beta2.official [b75f0485b]

### System information

Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility)

### Issue description

This code (based on the [sample in the docs](https://docs.godotengine.org/en/stable/classes/class_viewporttexture.html#class-viewporttexture)) successfully produces screenshots on Android mobile:
```	
	await RenderingServer.frame_post_draw
	var tex = Globals.main_viewport.get_texture().get_image().get_region(region)
	tex.save_png("user://creator/level_"+str(Globals.creator_level_id)+".png
```	
This works fine on Android:	
![image](https://github.com/godotengine/godot/assets/11803603/2506f27c-330d-47df-af47-9f2cf0408d9b)

But on Desktop:
![image](https://github.com/godotengine/godot/assets/11803603/72f37f80-da0b-41b6-b7dc-61902cb1aa0c)

This was also present on Windows 11, but am now on PopOS.

This seems to be caused by enabling Use HDR 2D, but it is unclear why it behaves differently for desktop.

### Steps to reproduce

See description.

### Minimal reproduction project (MRP)

Will make one if required.

**Comment by matheusmdx** [comment]
Tested on latest master [04bf7d4ca] and i can confirm the issue, also the forward and mobile rendering mode shows a different behaviour with HDR and get_viewport().get_texture().get_image().save_png()

![HDR Test](https://github.com/godotengine/godot/assets/44306054/6a3f5381-188a-470a-840c-b37149d10282)

<br>

In editor and playing the scene the image is rendered normally, like the no hdr image, but saving the viewport texture show the results in the image above.

I bisected the issue and found a culprit for the compatibility issue and another for the forward/mobile

<br>

Compatibility culprit: #87360

![Captura 2024-06-22 19-51-56-322391](https://github.com/godotengine/godot/assets/44306054/a0bdaa64-9fb9-41bd-8942-ea15a33a18fa)

<br>

Forward/mobile culprit: #80215

![Captura 2024-06-23 02-06-16-261316](https://github.com/godotengine/godot/assets/44306054/62a066a0-100a-40c6-9672-aa1216e65dcc)

**Comment by clayjohn** [comment]
@matheusmdx Great work!

The output of the Forward+ and Mobile renderers are what is expected with the HDR2D mode enabled as the image is stored in an HDR format in linear space, instead of in an LDR format in sRGB space. https://github.com/godotengine/godot/pull/92496 documents this requirement and adds a helpful `linear_to_srgb()` function to make converting the texture easier. 

For the compatibility renderer it seems like it is copying from the wrong texture when doing the screen copy. We will likely need to add some logic to the function that copies the screen texture to ensure that it is copying from the correct texture

**Comment by ChristopheClaustre** [comment]
@matheusmdx thanks you for introducing me to the `git bisect` command I didn't know and it seems awesome.
Did you take the correction of the wrong texture copied in compatibility as @clayjohn mentionned or can I look at it ?

Also @clayjohn is HDR feature available in compatibility ?

**Comment by matheusmdx** [comment]
> Did you take the correction of the wrong texture copied in compatibility as @clayjohn mentionned or can I look at it ?

I don't know where this adjust needs to be done so feel free to take a look
