### ISSUE TITLE
`AudioStreamPlayer3D.is_playing()` spams "Parameter p_playback is null"

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#93420]
### Tested versions

- Not reproducible in: 4.3 beta 1
- Reproducible in: 4.3 beta 2

### System information

Ubuntu 22.04.3 LTS

### Issue description

`AudioStreamPlayer3D.is_playing()` spams the following error in the Debugger > Errors tab:

```
E 0:00:05:0325   game.gd:5 @ _physics_process(): Parameter p_playback is null.
  <C++ Error>    Condition "p_playback.is_null()" is true. Returning: false
  <C++ Source>   servers/audio_server.cpp:1834 @ is_sample_playback_active()
  <Stack Trace>  game.gd:5 @ _physics_process()
```

### Steps to reproduce

Start the example project

### Minimal reproduction project (MRP)

[aud_bug.zip](https://github.com/user-attachments/files/15924605/aud_bug.zip)

_Bugsquad edit:_ Added details.

**Comment by akien-mga** [comment]
Godot 3.4 beta 2 is no longer supported. It was superseded by 3.4-stable, 3.4.4-stable, and now the 3.5 and 3.6 branches are the only ones supported.

Please try to upgrade to 3.5.3 or 3.6-beta5 and see if the bug is still reproducible.

**Comment by DimaKiva** [comment]
Sorry, I mixed up the version. I fixed it.

**Comment by AThousandShips** [comment]
Please describe the issue in more detail, the MRP is useful but having a good detailed description is necessary for a bug report

**Comment by akien-mga** [comment]
This is a regression introduced between 4.3-beta1 and 4.3-beta2, and reproducible in current `master` (04a530f91fc83b41112007dbd2ce02e9528df682). I haven't bisected but I'd suspect #91382 @adamscott

**Comment by adamscott** [comment]
Found the issue, fix inbound.
