### ISSUE TITLE
FlowContainer Scale also scales the wrap breakpoint

### ISSUE THREAD

**Issue by JDLRx** [godotengine/godot#93439]
### Tested versions

Tested in 4.3.beta1

### System information

Godot v4.3.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

If you have a Control > H/VFlowContainer 
and you add 2 or more childs,(more childs make it more obvious)
everything works as intended if you now change the size with dragging the x or y value of the FlowContainer
![image](https://github.com/godotengine/godot/assets/105598698/e75bdda1-8443-4955-83b7-caa1dba66f2d)

But if you now scale the FlowContainer to for example 0.5 all childs wrap at half of the size of the FlowContainer

![image](https://github.com/godotengine/godot/assets/105598698/92851d79-cb43-4be5-a15c-41bb9f744c0a)

### Steps to reproduce

setting up takes 10 seconds

Make a new scene with a flow container
add at least 2 childs, more is better.
child should have a size I tested with just ColorRect custom minimum size (50,50)

Change scale of FlowContainer to example 0.5 
then drag/resize the FlowContainer window with mouse and you will see the problem

### Minimal reproduction project (MRP)

N/A

**Comment by Sluggernot** [comment]
![image](https://github.com/godotengine/godot/assets/6569742/c850e0a0-be0d-4c0a-b6f8-d7687fbf675e)
![image](https://github.com/godotengine/godot/assets/6569742/9752b986-8632-4729-b3e9-ddc6b09dfd8a)

Not seeing it with my setup. No ideas why.
AMD Radeon 5700XT, Forward+, 4.3 beta

**Comment by JDLRx** [comment]
@Sluggernot Your Scale is 0.6 so the break point will be at 60% of the width on your selection which you just barely did not reach
if you reprocude this with a lower scale for example 0.2 it should be very obvious

**Comment by Sluggernot** [comment]
I'm just bad. I should have stated I did lots of testing with different values. I only saw wrapping when expected. That is, shrinking the right side over until a ColorRect must wrap to not be obfuscated.
