### ISSUE TITLE
Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 4096. Falling back on maximum buffer size. at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1115)

### ISSUE THREAD

**Issue by kuligs2** [godotengine/godot#93456]
### Tested versions

Godot Engine v4.3.beta2.official.b75f0485b

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA RTX A2000 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

It shows up before you load up any project.

Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 4096. Falling back on maximum buffer size. at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1115)

### Steps to reproduce

Open Godot_v4.3-beta2_win64_console.exe and it shows up in the console before you load up any project

### Minimal reproduction project (MRP)

it shows up before you load up any project

**Comment by kuligs2** [comment]
![image](https://github.com/godotengine/godot/assets/2693224/7dc82671-74c8-4d4f-81d6-6da046eef090)

**Comment by patwork** [comment]
duplicate https://github.com/godotengine/godot/issues/93453
