### ISSUE TITLE
Texture Progress Bar does not render the progress texture correctly when using an Atlas Texture in clockwise and counter clockwise fill modes

### ISSUE THREAD

**Issue by peter-rocchio** [godotengine/godot#93462]
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b] and earlier betas
- Not Reproducible in: v4.2.2.stable.official [15073afe3] and earlier 4.2

### System information

Windows 11 - Forward +

### Issue description

Texture Progress Bar does not render the progress texture correctly when using an Atlas Texture in clockwise and counter-clockwise fill modes.
![image](https://github.com/godotengine/godot/assets/25456663/3b025311-0cb0-4519-bc19-eb7bc7b17b25)

### Steps to reproduce

1. Create a TextureProgress Node
2. Set fill mode to clockwise or counter clockwise
3. Create a texture atlas
4. Add the texture atlas to under and progress textures and set a region smaller than the texture
5. Observe the under texture renders correctly
6. Change the value to between the min-max
7. Observe the progress texture does not render correctly

### Minimal reproduction project (MRP)

[texture_progress_bug.zip](https://github.com/user-attachments/files/15936192/texture_progress_bug.zip)

**Comment by anniryynanen** [comment]
Looks straightforward, I'll try to fix this.

**Comment by kleonc** [comment]
That's a regression from #91724, the uvs are remapped twice now for TextureProgressBar as its own remapping was not removed in that PR.
https://github.com/godotengine/godot/blob/8a6c1e8f5232ff3b3a5eac024d590e7479b29e90/scene/gui/texture_progress_bar.cpp#L525-L553
