### ISSUE TITLE
Containers do not correctly resize to their contents when their visibility is toggled

### ISSUE THREAD

**Issue by peter-rocchio** [godotengine/godot#93464]
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b] and earlier betas
- Not Reproducible in: v4.2.2.stable.official [15073afe3] and earlier 4.2

### System information

Windows 11 - Forward +

### Issue description

Containers will correctly resize to fit their contents when in the editor and the first time they are made visible while the application is running.  However, if the container is hidden, and then shown again, the container will shrink and not resize properly when shown again.  This is easiest to see with panel containers.
![image](https://github.com/godotengine/godot/assets/25456663/08b3ac1f-36be-47a5-95c9-f72cd5c74247)
![image](https://github.com/godotengine/godot/assets/25456663/da15630a-5280-4314-937d-3bb8815837b9)
![image](https://github.com/godotengine/godot/assets/25456663/6be1bfca-d662-430a-a402-2bdb412d2151)

### Steps to reproduce

1. Create a control scene and add a script to this node
2. Add a panel container, a grid container as a child, and buttons as children to the grid container
3. Add a button as the child of the root control node, link its pressed signal to the root script
4. Have the button's signal turn the panel container's visibility on and off
5. Observe that the panel container does not consider its child contents when it determines its size after being shown again

### Minimal reproduction project (MRP)

[container-visibility.zip](https://github.com/user-attachments/files/15936382/container-visibility.zip)

**Comment by anniryynanen** [comment]
Probably related to #93386. That fixes it for grids, but not other containers.

**Comment by anniryynanen** [comment]
I can change the other containers too, but should it be `SortableVisbilityMode::VISIBLE` or `SortableVisbilityMode::IGNORE`? I used `VISIBLE` to fix the grids, but going through the others I see some use `IGNORE`.

**Comment by huwpascoe** [comment]
This happens to me in 4.2. I know there was some kind of workaround I had to do for an overlay.

**Comment by kitbdev** [comment]
> I can change the other containers too, but should it be `SortableVisbilityMode::VISIBLE` or `SortableVisbilityMode::IGNORE`? I used `VISIBLE` to fix the grids, but going through the others I see some use `IGNORE`.

I think they should use VISIBLE in the minimum size checks so that it matches behavior from before #91613
