### ISSUE TITLE
mouse_get_position: Mouse is not supported by this display server

### ISSUE THREAD

**Issue by kuligs2** [godotengine/godot#93461]
### Tested versions

Godot Engine v4.3.beta2.official.b75f0485b - https://godotengine.org

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA RTX A2000 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

Setting --headless in Project settings > General > Editor > Run  - throws this error

### Steps to reproduce

![image](https://github.com/godotengine/godot/assets/2693224/47358d2b-c318-4aa1-a757-7b36a0825f0d)
Any scene, any script.

I dont remember seeing this in beta1, or dev6

### Minimal reproduction project (MRP)

Create scene, 
Set project settings
![image](https://github.com/godotengine/godot/assets/2693224/47358d2b-c318-4aa1-a757-7b36a0825f0d)

Run scene

![image](https://github.com/godotengine/godot/assets/2693224/3daa10a4-8cb9-4121-b2ff-1ac6c31d84a9)

```
E 0:00:00:0207   mouse_get_position: Mouse is not supported by this display server.
  <C++ Error>    Method/function failed. Returning: Point2i()
  <C++ Source>   servers/display_server.cpp:497 @ mouse_get_position()
```

**Comment by bruvzg** [comment]
That's expected behavior, and should be the same in all previous versions, `--headless` switches to the dummy implementation of the display server so none of the display server functions will work.

**Comment by kuligs2** [comment]
> That's expected behavior, and should be the same in all previous versions, `--headless` switches to the dummy implementation of the display server so none of the display server functions will work.

But like i said its not the same. I dont get that error in Godot Engine v4.3.beta1.official.a4f2ea91a - https://godotengine.org, version.

**Comment by bruvzg** [comment]
Are you calling this function, or are you getting the error when running the empty scene?

**Comment by kuligs2** [comment]
You tell me.

Beta1

https://github.com/godotengine/godot/assets/2693224/b662c8bb-97ea-4950-9f66-93d635ce93b9

Beta2

https://github.com/godotengine/godot/assets/2693224/6599325b-6479-4480-84b3-dcb54142dc69

**Comment by kuligs2** [comment]
The script that runs is this:
```
extends Node


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	#print_rich("[color=yellow]# ---------------------------------------------- \n [/color]")
	#print_rich("[color=yellow]# ---------------------------------------------- [/color]\n")
	#print_rich("No no\n")
	## this works, both in editor console and godot console/cmd in windows
	#print_rich("[color=red] sum tex [/color]")
#
## this does not work in godot console/cmd in windows
	#print_rich("[color=#9837d3] sum tex [/color]" +" /n")
	#
	##printraw("c[45m" + "lol" +" /n")
	##print("[45m" + "lol" +" /n")
	##print("[0,45m" + "lol" +" /n")
	##print("[0,35m" + "lol" +" /n")
	##printraw("[0;45m" + "lol" +" \n")
	print("smelly")
	print("1lol" +" \n")
	printraw("[1;,35m" + "lol" +" \n")
	printraw(''+"[0m")
	print("2lol" +" \n")
	printraw(''+"[0m")
	printraw("[31m" + "lol" +" \n")
	print("3lol" +" \n")
	
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	pass
```
