### ISSUE TITLE
Iterate over both keys and values of a dictionary.

### ISSUE THREAD

**Issue by ducdetronquito** [godotengine/godot#9346]
Hi ! 👋

I regularly face the situation where I want to iterate over the values of a dictionary.

```gdscript

var data = {}

for key in data:
    data[key]
```

With Python, there is a simple API for this:

```python
data.keys()
data.values()
data.items()
```

With JavaScript, too:

```javascript
for (let [key, value] of data) {
  console.log(value);
}
```

Do you think it would be useful to have these types of shortcuts ?

Have a great weekend 🎉

**Comment by neikeq** [comment]
Don't we have [values()](http://docs.godotengine.org/en/stable/classes/class_dictionary.html?highlight=Dictionary#class-dictionary-values) too?

**Comment by bojidar-bg** [comment]
@neikeq Yea, but sometimes you need both value and key.

Note that this will be useful for arrays too, converting this:
```gdscript
var i = 0
for x in array:
    i += 1
# OR:
for i in range(array.size()):
    var x = array[i]
```
Into:
```gdscript
for i, x in array:
    pass
```

Also, the call to `values()` would create a useless temporary array.

**Comment by ducdetronquito** [comment]
@neikeq Thanks ! 

Do I need to rename the title of this issue ?
> [Feature Request] [GDScript] Iterate over the **items** of a dictionary

@bojidar-bg Would be definitely cool to have this feature on arrays to !

**Comment by bojidar-bg** [comment]
> Do I need to rename the title of this issue ?

No longer 😄

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by ducdetronquito** [comment]
Hey @kubecz3k ,

Here it is a feature request, but I haven't checked if it has been implemented in the latest release of Godot 3.

Have a good day :)

**Comment by kubecz3k** [comment]
Do we need something else than `keys()` and `values()`?
Would we have some performance improvements if we would have some special expression for this instead of doing:
```
var keys = dict.keys();
for key in keys: 
   val = dict[key];
```
I understand the use case but while it's not very rare it's not frequent either I think, @bojidar-bg what do you think?

**Comment by ducdetronquito** [comment]
As a daily Python user, I can tell that having a `ìtems` method to iterate on both keys and values of a dictionary is really enjoyable.

```python
for player, score in scoreboard.items():
    # Do stuff
```

**Comment by akien-mga** [comment]
For the reference, a PR attempted to add this feature a while ago, but we couldn't reach consensus on the implementation details: #15496

**Comment by cgbeutler** [comment]
Was this ever added to the new issue tracker? If so, could someone provide a link. (I can't seem to find it, but seems like one that should exist.)

**Comment by Killfrra** [comment]
https://github.com/godotengine/godot-proposals/issues/1965

**Comment by nerdbeard** [comment]
Python has tuple unpacking and Godot does not.  This means items() does not really save any finger or CPU work.

**Comment by Calinou** [comment]
Please continue the discussion in https://github.com/godotengine/godot-proposals/issues/1965.
