### ISSUE TITLE
Bitmap Font resources display correctly in editor, but not at runtime

### ISSUE THREAD

**Issue by CookieCapuchin** [godotengine/godot#93484]
### Tested versions

Reproducible in: 4.2.1.stable and 4.3.beta2

### System information

Windows 10, Godot 4.3.beta2, compatibility mode

### Issue description

I have tried both the "Allegro Font Importer: abfi" and the "Texture Fonts" plugins in both Godot 4.2.1 and 4.3b2. The plugins **display characters perfectly in the editor**, but **don't display resources properly at runtime**. Godot's built in Font Data (monospaced) importer works just fine, but the two plugins display only missing character glyphs or a fallback font. Any help is appreciated.

### Steps to reproduce

1. Generate a font resource using either the "Allegro Font Importer" plugin or "Texture Fonts" plugin.
2. Create a label node and add the font to the theme override. (Everything works great here.)
3. Run the scene. (Everything still works fine.)
4. Go to project settings:
   change the Display/window/viewport height-width to 480x270
   change the window width-height override to 1280x720
   change the stretch mode to canvas_items
5. Run the scene again. (At this point Allegro will display missing character glyphs, while Texture Fonts displays a fallback font.)

### Minimal reproduction project (MRP)

[bitmapfont_err.zip](https://github.com/user-attachments/files/15938112/bitmapfont_err.zip)

**Comment by bruvzg** [comment]
This is a custom importer issue, it's not disabling oversampling when configuring the font (should do it before setting up textures):

Add `font.oversampling = 1.0` to the importer code, like this:

<img width="583" alt="Screenshot 2024-06-23 at 20 43 51" src="https://github.com/godotengine/godot/assets/7645683/8c6a05a6-1452-4f44-9575-f19e451b144f">

**Comment by CookieCapuchin** [comment]
Omg, works like a charm!  I'm fairly new to Godot, so this was way above my head. You're amazing and thank you!
