### ISSUE TITLE
"SharedArrayBuffer is not defined" error after a web build with a custom export template and Thread Support disabled

### ISSUE THREAD

**Issue by depmots** [godotengine/godot#93508]
### Tested versions

- Reproductible in b75f0485b

### System information

Godot v4.3.beta (b75f0485b) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

I'm trying to reduce the size of a web export in order to upload the game to Poki. To do this I pulled the godot source code of the 4.3 beta 2 release and made a custom export template with only 3d disabled. I made sure to disable Thread Support and enable Cross Origin Isolation.

Despite this, I get a "SharedArrayBuffer is not defined" error in the console.
**When using the default web export template it works fine**

### Steps to reproduce

Pull commit b75f0485b of the godot repo. (4.3 beta 2)
Make a custom web export template with 
`scons platform=web tools=no target=template_release` (using emscriptem 3.1.61)
Use the newly compiled export template to export your game. Disable Thread Support and enable Cross Origin Isolation

When I upload the game here https://inspector.poki.dev/, I get the "SharedArrayBuffer is not defined" in the browser's console

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
As far as I know the thread support is not something that can be turned on and off on the specific template, you need to compile it with the correct option as it's part of the compiled code

**Comment by akien-mga** [comment]
Indeed, you need to compile with `threads=no`. The checkbox impacts which _official_ export template is used, but if using a custom one, you have to make sure it's built with the matching option.

@adamscott We need to add instructions for re: `threads` to https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_web.html

**Comment by AThousandShips** [comment]
That's done in:
* https://github.com/godotengine/godot-docs/pull/9392

**Comment by depmots** [comment]
This seems to have done the trick! Thanks for the quick response! Closing
