### ISSUE TITLE
RigidBody2D randomly stuck between TileMap tiles

### ISSUE THREAD

**Issue by kkurczewski** [godotengine/godot#93509]
### Tested versions

Godot Engine v4.2.2.stable.official.15073afe3

### System information

Godot v4.2.2.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 960 (nvidia; 535.171.04) - Intel(R) Core(TM)2 Duo CPU     E8600  @ 3.33GHz (2 Threads)

### Issue description

I have basic setup of `CharacterBody2D` (player), `RigidBody2D` (box) and `Tileset`. When I hold arrow and push a box over a floor made of tiles then box can randomly stuck between tiles. Despite being random in nature bug is easily reproducible.

Notes:
* problem doesn't occur when using `StaticBody2D` as floor, even multiple joined together. 
* problem doesn't occur when `Lock rotation` on `RigidBody` is disabled so probably there is some friction on the ground.

### Steps to reproduce

Run the example project and hold right arrow to push box from the left to right, box will stuck in middle of tiles (added checkboard pattern for easier inspection).

For comparison, left side uses `StaticBody` as floor and pushing works correctly, even on junctions.

### Minimal reproduction project (MRP)

[bug-report-rigid-body.zip](https://github.com/user-attachments/files/15944868/bug-report-rigid-body.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/89458

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by kkurczewski** [comment]
I think this is the same root issue, I wonder if example from here may be useful though - that is, if my example is reproducible on other machines as well - to be confirmed by someone.

**Comment by AThousandShips** [comment]
Please add it to the other issue and see

**Comment by KoBeWi** [comment]
I can reproduce the issue using your project, but the cause and the potential fix are already known. The main problem is implementing the fix properly.
