### ISSUE TITLE
Web Export - Unable to adjust AudioServer volume 

### ISSUE THREAD

**Issue by mr-dreich** [godotengine/godot#93513]
### Tested versions

Godot v4.3.beta2

### System information

Godot v4.3.beta2 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 - Apple M1

### Issue description

After exporting for Web and uploading to Itch.io or using Godot Editor "Run in Browser", you can't change the AudioServer volume.

I have tested this in Safari, Firefox, and Chrome.

### Steps to reproduce

This is a simple Node2D scene with a AudioStreamPlayer that auto plays crickets and a HSlider that allows you to adjust the AudioServer volume.

### Minimal reproduction project (MRP)

[audiovolumetest.zip](https://github.com/user-attachments/files/15945357/audiovolumetest.zip)

**Comment by adamscott** [comment]
@mr-dreich Thanks for your bug report!

**Comment by symbol24** [comment]
Still occurring for default Master BUS on web in 4.4.1
