### ISSUE TITLE
Mobile VR: Bad tracking

### ISSUE THREAD

**Issue by Kiskadee-dev** [godotengine/godot#93525]
### Tested versions

Reproducible in 4.2.2 ---> [MobileVrInterface docs](https://docs.godotengine.org/en/4.2/classes/class_mobilevrinterface.html)

Not reproducible on 3.2 (working fine out of the box)

### System information

Linux pop-os 22.04  I5 5200U - GT940M

### Issue description

Phone: Redmi Note 8

Deploying on android native (cardboard-like phone thing) results in broken tracking, maybe it's using the wrong phone sensors, the Godot sensors demo project works almost fine, there, the left cube is very shaky (similar to the XR tracking result)  while the right one (Gyro + Grav) is smooth.

Additionally, in the XR, the yaw doesn't work at all.

![image](https://github.com/godotengine/godot/assets/10299707/16e808e8-adae-46e2-95bf-026bf04cbba2)

In Godot 3.2 the ([same code](https://docs.godotengine.org/en/3.2/classes/class_mobilevrinterface.html?highlight=MobileVRInterface)) works fine out of the box

![image](https://github.com/godotengine/godot/assets/10299707/46d0e61b-b488-4634-9ba8-ed310c7220be)

https://github.com/godotengine/godot/assets/10299707/f6d572ff-4b85-41df-a1f8-c9f3c8d3d2df

### Steps to reproduce

Build a simple 3d scene with a XROrigin3D and XRCamera3D, activate the MobileVRinterface as the docs say, deploy to android using the default export options and see the tracking issues.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/15946590/MRP.zip)

**Comment by Kiskadee-dev** [comment]
a sidenote, the docs need some update due to `get_viewport().xr = true` becoming `get_viewport().use_xr = true`, if there are other changes then it might be very outdated

**Comment by BastiaanOlij** [comment]
Please test this in 4.3 beta2, it is likely already fixed, I remember working on this awhile back.

**Comment by AThousandShips** [comment]
Closing as assumed fixed, if you can still reproduce this in 4.3 please comment and this can be reopened
