### ISSUE TITLE
Can't reselect node in scene tree after viewing a resource in the inspector

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#93534]
### Tested versions

Reproduces in:
- v4.3.beta2.official [b75f0485b]
- v4.3.beta1.official [a4f2ea91a]

Doesn't reproduce in:
- v4.3.dev6.official [64520fe67]

### System information

Arch Linux <span>#</span>1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 - Tty - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

After viewing a resource in the inspector, it's not possible to re-inspect the node selected in the scene tree without unselecting it first.

### Steps to reproduce

- Inspect a node by clicking it in the scene tree
- Inspect a resource by double clicking it in the file system dock
- Try to return to inspecting the same node by clicking it in the scene tree

### Minimal reproduction project (MRP)

N/A

**Comment by anniryynanen** [comment]
I'll make a PR for this.

**Comment by akien-mga** [comment]
Would be good to identify which PR introduced the regression in 4.3.beta1, to make sure that whichever fix we make doesn't regress on what the original PR aimed to solve.

**Comment by anniryynanen** [comment]
> Would be good to identify which PR introduced the regression in 4.3.beta1

It was broken in #91435, I tested the issues discussed there and I think they're still fixed.

**Comment by anniryynanen** [comment]
The only thing that I found that doesn't work is recovering a multi-selection after closing and reopening a scene, but I'm not sure if that worked before either.
