### ISSUE TITLE
Shader doesn't appear to be taking input from inspector correctly.

### ISSUE THREAD

**Issue by remorse107** [godotengine/godot#9354]
In the below example, I am setting the Modulate to 1.0, 0.0, 0,0, 0,0. With the expecation that my mesh will be red.  However, the shader appears to be taking the input vectors x (or red) component and applying it to both the red and blue components of the uniform variable.

![capture3](https://user-images.githubusercontent.com/7462993/27512431-dfd8259a-5904-11e7-90f7-c3758bba1098.PNG)

![capture](https://user-images.githubusercontent.com/7462993/27512427-d1a65d3e-5904-11e7-9ddc-1eb76aa4f27c.PNG)

By manually adjusting the code so that only the red component is used I get what I expect to see.

![capture2](https://user-images.githubusercontent.com/7462993/27512439-47986456-5905-11e7-93ad-02e2a06a1a57.PNG)

**Comment by nunodonato** [comment]
what's the light color?

**Comment by remorse107** [comment]
White.  But that shouldn't matter in the example I provided.  I clearly
show two different results when the albedo values should be the same.

**Comment by nunodonato** [comment]
can't reproduce it, works fine in here

**Comment by remorse107** [comment]
I thought maybe it worked fine for me initially too.  There maybe something
residual in the system not clearing state properly.

I noticed that my model also appeared to not by culling properly after I
added a rendering mode statement.  But removing the statement didn't seem
to reset things back.
