### ISSUE TITLE
running on draw without start the run - print function !?

### ISSUE THREAD

**Issue by catafest** [godotengine/godot#93542]
### Tested versions

v4.3.beta2.official [b75f0485b], tested with this stable version: v4.2.stable.official [46dc27791]

### System information

Windows 10 Pro, NVIDIA GeForce GTX 950 

### Issue description

I see the print function is running on the draw section of the source code without starting the run scene 
Maybe because I used beta versions or is it for another reason ... !?
Anyway, this is good to know, see the archive with the project I added.

### Steps to reproduce

simple test project from this video tutorial https://www.youtube.com/watch?v=TtziEJZtWXc

### Minimal reproduction project (MRP)

[radialmeniu_001.zip](https://github.com/user-attachments/files/15953652/radialmeniu_001.zip)
I tested with : v4.2.stable.official [46dc27791] same error 
![image](https://github.com/godotengine/godot/assets/2210118/3cbe093c-7cc4-4ae1-bc2c-1789ea52ec1a)

**Comment by AThousandShips** [comment]
Because it's a `@tool` script, it runs in the editor, see [here](https://docs.godotengine.org/en/stable/tutorials/plugins/running_code_in_the_editor.html)

**Comment by catafest** [comment]
I commented on stable Godot the @tool source code and I tried with :

`push_error("test error", draw_pos)`
To see the **draw_pos** result , you can see is random on vectors ...

![image](https://github.com/godotengine/godot/assets/2210118/1f7a889e-952a-4a0f-b777-9445e6f7ca17)

**Comment by AThousandShips** [comment]
Have you reloaded the editor after changing?

**Comment by AThousandShips** [comment]
In either case the original issue isn't a bug, please ask in the forums and if you have another bug report it as a separate bug after getting support on the forums
