### ISSUE TITLE
Visibility AABB affects 3D particle collision

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#93567]
### Tested versions

- v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Steps to reproduce

I have set up two identical GPU particle systems. Both have a `GPUParticles3DCollisionbox` below them.  The particles are set up to use rigid collision. However collision does not seem to work at all for them:

https://github.com/godotengine/godot/assets/327257/cc90c084-78d7-4407-a30b-ab094a11a082

Now if I change the visibility AABB of one of the particle systems to enclose the `GPUParticles3DCollisionbox` below it, the collision suddenly works:

https://github.com/godotengine/godot/assets/327257/f2e31851-56e2-416c-a970-d6abfde32f75

### Minimal reproduction project (MRP)

[reproducer.zip](https://github.com/user-attachments/files/15960291/reproducer.zip)

**Comment by clayjohn** [comment]
Reclassifying this as a documentation issue. The behaviour is certainly annoying, but its not a bug per se. Godot uses the AABB of the particles to determine what area the particles will reach. Because of the disconnect between GPU data and CPU data, it is possible to create particles that extend outside there AABB. 

This creates numerous problems:
1. As described here, particles won't register with the collision shape and so the particles will fail to collide
2. Particles won't register with lights and so they won't cast shadows
3. Particles will become invisible if the AABB is not on screen

_MRP where the camera is looking slightly down_
![image](https://github.com/godotengine/godot/assets/16521339/3e1ae914-8f80-44a2-b4a7-1385b841aced)

All these issues come down to the same fundamental problem: if the AABB isn't an accurate representation of the area covered by your particle effect, then things will break. 

I think we should document this problem in more places so that users are aware that they need to manually tweak the AABB when working on custom particle effects

**Comment by derkork** [comment]
Well interestingly enough if you use a height field collision, it will work even if you don't increase the AABB. At least the behaviour should be consistent there, shouldn't it?

**Comment by clayjohn** [comment]
> Well interestingly enough if you use a height field collision, it will work even if you don't increase the AABB. At least the behaviour should be consistent there, shouldn't it?

The behaviour should be consistent, yes. The AABB of the heightfield collider needs to overlap the AABB of the Particles node.

I ran a quick test and can confirm that the height field collision AABB does indeed need to overlap the Particles AABB, just like the other Collision shapes.

_Using the same size as the box collider_
<img width="1431" alt="Screenshot 2024-06-24 at 6 28 39 PM" src="https://github.com/godotengine/godot/assets/16521339/04e577a7-c1a0-4174-9c28-31aa8db91233">

_Overlapping AABBs_
<img width="1418" alt="Screenshot 2024-06-24 at 6 28 54 PM" src="https://github.com/godotengine/godot/assets/16521339/6a1d4a5e-17e7-4147-8673-3d5699c32b91">

**Comment by derkork** [comment]
Thank you very much for the explanation! I was referring to this setup, where the particle system AABB  and the height field size overlap, but the collision point is actually outside of the particle system AAAB. In this case the collision seemingly still seems to work:

![image](https://github.com/godotengine/godot/assets/327257/06d23c9d-fe48-4b37-9fe9-c07a207ca0f2)

Until the AABB leaves the camera at which time the particle simulation seems to be partially halted (note how the particles are not drawn anymore but their shadows are). 


https://github.com/godotengine/godot/assets/327257/1861020e-f6d0-4618-8e67-fc17e1be3abc


So maybe a checklist for the developer could look like this:

- Make sure your particle system AABB is large enough to enclose all surfaces that you want your particles to interact with.
- If you use a height field, its size and positioning should match the AABB of your particle system.

There are probably some other items on the list for tweaking the FPS to prevent tunneling, and I'm also not sure about the the SDF based collision yet, but I'll clarify these in https://github.com/godotengine/godot/issues/93570 as to not convolute the discussion here. Again thanks a lot for explaining this!

**Comment by derkork** [comment]
Another question related to that is how AABBs of subemitters are handled. Should they have the same AABB as their parent emitter or do they "inherit" their parent's AABB and their own AABB doesn't matter?

**Comment by Calinou** [comment]
> Another question related to that is how AABBs of subemitters are handled. Should they have the same AABB as their parent emitter or do they "inherit" their parent's AABB and their own AABB doesn't matter?

Subemitters need to have their AABBs correctly configured, just like their parent. They do **not** inherit their parent's AABB.

**Comment by derkork** [comment]
That is good to know, thank you very much!
