### ISSUE TITLE
Error output misleading

### ISSUE THREAD

**Issue by warcaninos** [godotengine/godot#93569]
### Tested versions

It happens to me on 4.2.2 i did not test any other version

### System information

Godot v4.2.2.stable unknown - Garuda Linux #1 ZEN SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:18 +0000 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (RADV NAVI10) () - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

I am currently learning to use the EditorScenePostImport and for now i've been quite successful in doing what i want  but while everything work as i wanted the "output" still give this error.

Invalid owner. Owner must be an ancestor in the tree.

Is this an error on my part or is godot being overzealous on who has to be the owner ?

### Steps to reproduce

Trying to set owner of added children to blend files with an import script

### Minimal reproduction project (MRP)

[ReporductionProject.zip](https://github.com/user-attachments/files/15960303/ReporductionProject.zip)

**Comment by AThousandShips** [comment]
It's an error on your part if the owner isn't answering ancestor, is it?

**Comment by AThousandShips** [comment]
You are setting the owner of `static_body` even if you don't add it as a child of `node`, that looks like this is a perfectly valid error, try instead:
```gdscript
		#Check if "only" the collision should be imported and only import collision shape because the meshinstance3D
		#is replaced by a StaticBody3D
		if node.name.contains("only"):
			node.add_child(collision_shape)
		#Else add a static body
		else:
			static_body.add_child(collision_shape)
			node.add_child(static_body)
			static_body.set_owner(owner)
			
		#Set the owner of the nodes so they appear in the NodeTree
		collision_shape.set_owner(owner)
```

**Comment by warcaninos** [comment]
My bad the n the only thing it was doing was outputing this error because the node was not created, i feel dumb, sorry for the annoyance.

I can confirm that i do not have the error anymore.

**Comment by AThousandShips** [comment]
Always good to listen to error messages and look at what might cause them, most of the time they aren't wrong

But asking in the forums is usually much more helpful, more people there with more time to help with things, and if it still won't work it's time to make an error report!

And no worries, have a nice day! Happy we could solve it
