### ISSUE TITLE
[4.2] Blendspace2D discrete carry not working as intended 

### ISSUE THREAD

**Issue by JF-Werewolf** [godotengine/godot#93561]
### Tested versions

- Reproducible in 4.2.2 stable, but i have seen reports in other versions online. 

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4665) - Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 Threads)

### Issue description

Blendspace2D discrete carry still not working as intended.
Spritesheet animations setup on AnimationPlayer will reset to frame zero when blended in Blendspace2D despite discrete carry being selected as blend mode.
Apparently this is a somewhat old issue supposedly fixed multiple times, last time reported in #86984 and tackled in #87171.
Had no problem with discrete carry in version 3.something around a year ago, but it's not working now (again).

### Steps to reproduce

Setup spritesheet animations in an AnimationPlayer node and blend them in a Blendspace2D in an AnimationTree node. Every time the animation switches, it is started at frame zero, despite any animation configuration and carry being selected in blend mode. 

### Minimal reproduction project (MRP)

[carry_bug.zip](https://github.com/user-attachments/files/15959124/carry_bug.zip)

**Comment by AThousandShips** [comment]
That change is specific to 4.3 so it won't be in 4.2, it hasn't been fixed there because the fix wasn't safe to bring over, a fix that *doesn't* break compatibility would be needed for 4.2 which isn't simple

**Comment by JF-Werewolf** [comment]
Uhhhh
Ok. Guess I will have to write a bit more code for now then.
Thanks!

**Comment by akien-mga** [comment]
Closing as fixed in 4.3.
