### ISSUE TITLE
[Web] Uncaught TypeError: AudioNode.connect: Argument 1 is not valid for any of the 2-argument overloads.

### ISSUE THREAD

**Issue by awhiskin** [godotengine/godot#93574]
### Tested versions

- Reproducible in 4.3-beta2
- Not reproducible in 4.3-beta1

### System information

Godot v4.3.beta2 - macOS 14.5.0 - Vulkan (Mobile) - integrated Apple M3 - Apple M3 (8 Threads)

### Issue description

When exporting a web build in Godot 4.3-beta2, the resulting project encounters the following Javascript error in the console:

`Uncaught TypeError: AudioNode.connect: Argument 1 is not valid for any of the 2-argument overloads.`

This only seems to occur when building in 4.3-beta2, if I go back a version to 4.3-beta1 then the same project works fine.

The console shows the following error message:

```
Uncaught TypeError: AudioNode.connect: Argument 1 is not valid for any of the 2-argument overloads.

Uncaught DOMException: AudioScheduledSourceNode.stop: Start has not been called on this AudioBufferSourceNode.
```

### Steps to reproduce

Unclear what exactly causes this behavior; in my project it is when you shoot an arrow which hits a target.

This normally results in:
- A GPUParticles2D emitting
- An AudioStreamPlayer playing a sound
- A GDScript signal being emitted

I've tried removing the AudioStreamPlayers from the project and re-exporting but curiously the behaviour persists.

### Minimal reproduction project (MRP)

To reproduce the issue:

1. Open the project in Godot 4.3-beta2
2. Export the project using the Web (Runnable) preset
3. Either upload the project to somewhere like Itch.io or otherwise run a local server to be able to play the web build
4. Shoot an arrow at the other archer (or, easier to reproduce - shoot directly upwards at 90º) - when the arrow strikes a target the game will freeze
5. Observe the web console for errors

[SampleProject.zip](https://github.com/user-attachments/files/15961453/SampleProject.zip)

**Comment by adamscott** [comment]
Fixed by #93362
