### ISSUE TITLE
Script editor no longer scrolls when you move line with Alt+Up/Down

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#93588]
### Tested versions

Reproducible in 4.3.beta2

### System information

Godot v4.3.beta2 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Script editor doesn't scroll to the caret when you press Alt+Up/Down. Works on any GDScript file opened in Godot. Used to function correctly in 4.2.2

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Haven't bisected but might be a regression from:
* https://github.com/godotengine/godot/pull/86978

As it touched the relevant code

CC @kitbdev
