### ISSUE TITLE
Changing root viewport size while in fullscreen mode leads to weird results

### ISSUE THREAD

**Issue by DissonantVoid** [godotengine/godot#93582]
### Tested versions

4.2.1.stable

### System information

Windows10 all renderers

### Issue description

While the window mode is Fullscreen under any of the 3 StretchModes and any Renderer if the base resolution of the viewport is changed the viewport will snap to the top left (bottom left when using opengl) instead of remaining in the center and will scale in a weird way:

https://github.com/godotengine/godot/assets/69814029/c5fd563d-39bc-44d9-a635-9a873fba4177

as can be seen the viewport doesn't remain centered instead snapping to the corner. this can be solved by toggling fullscreen off then on again but it is annoying when having a resolution setting in some menu in your game.

### Steps to reproduce

(see minimal reproduction project)

go into fullscreen and then change the viewport base resolution through code.

### Minimal reproduction project (MRP)

[viewport_bug.zip](https://github.com/user-attachments/files/15962756/viewport_bug.zip)

**Comment by Calinou** [comment]
I can't reproduce this on:

Godot v4.3.beta (25ff1306d) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 550.78) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

**Comment by DissonantVoid** [comment]
using `get_viewport().content_scale_size` rather than `get_viewport().size` fixes the issue, it was a misunderstanding from my end, I did some asking around but it seems the people I asked also had a misunderstanding. thank you for clarifying.
