### ISSUE TITLE
add node path autocompletion for get_node outside of a method

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9359]
**Operating system or device - Godot version:**
ALL

**Issue description:**

when write code
onready var node = get_node() outside of a method, there is no node path autocompletion.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by novemberist** [comment]
Can confirm this. Autocompletion works with the new alternative syntax for get_node() $node_name or $"path_to_node

**Comment by akien-mga** [comment]
I can confirm too.
