### ISSUE TITLE
Fonts with LCD Subpixel Antialiasing do not respect control's Modulate when using Forward+ or Mobile renderer

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#93606]
### Tested versions

- Reproducible from 4.0 beta 6 (earliest I had easy to test) up to master

### System information

Windows 10 & macOS 

### Issue description

When a font is imported as LCD Subpixel and rendered in Vulkan Forward+ or Mobile, the modulate color (self or total, on the control or inherited by its parent) is completely ignored. 

### Steps to reproduce

1. Import a font and update it's advanced import settings to use LCD Subpixel antialiasing
2. Use a Vulkan renderer
3. Modulate any control using it, via theme, theme override, label settings, etc. 

### Minimal reproduction project (MRP)

[lcdsubpixelmodulate.zip](https://github.com/user-attachments/files/15976158/lcdsubpixelmodulate.zip)

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by cridenour** [comment]
> Does the issue occur in Compatibility?

It does not.
