### ISSUE TITLE
"pressed" signal sometimes fails to be emitted for Button and CheckBox in Android export

### ISSUE THREAD

**Issue by daveTheOldCoder** [godotengine/godot#93612]
### Tested versions

Occurs in v4.3.beta1.official [a4f2ea91a], v4.3.beta2.official [b75f0485b], v4.3.beta3.official [82cedc83c], v4.3.rc1.official [e343dbbcc], v4.3.rc2.official [3978628c6], v4.3.rc3.official [03afb92ef].
Does not occur in v4.3.dev6.official [64520fe67].

### System information

Godot v4.3.rc3 - Pop!_OS 20.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

Android device info: Galaxy S9 (Model SM-G960U), Android 10

### Issue description

I observed this problem in an Android export of a complex project in Godot 4.3 (see **Tested versions** above).  It does not occur when running in the Editor.

For reference, here's the comparison of Godot 4.3-dev6 to Godot 4.3-beta1:
https://github.com/godotengine/godot/compare/64520fe..a4f2ea9

The symptom is that when a Button or CheckBox control is touched in an Android export, sometimes the connected action does not occur. The "button_down" and "button_up" signals are always emitted. But the "pressed" and "toggled" signals are not emitted when the problem occurs.

### Steps to reproduce

The problem occurs if I set the BaseButton action_mode property to ACTION_MODE_BUTTON_RELEASE, but does not occur when the property is set to ACTION_MODE_BUTTON_PRESS.

I've only observed the problem when the controls are in a PackedScene that's loaded and instanced at runtime.

### Minimal reproduction project (MRP)

I'm attaching an MRP. However, it does not consistently exhibit the problem. If I can create another MRP that consistently exhibits the problem, I'll attach it.

The deep structure and node types in the scene tree in the MRP replicates the scene tree in the project where I observed the problem. 

[fg_debug1.zip](https://github.com/user-attachments/files/15980819/fg_debug1.zip)

**Comment by akien-mga** [comment]
Can you still reproduce this issue in 4.3.rc2 or later?

**Comment by daveTheOldCoder** [comment]
Yes, it still occurs in 4.3.rc2.

I've been to work around it for Button's by using the _button_up_ signal instead of the _pressed_ signal. I haven't yet figured out a work-around for CheckBox's.

I'd like to help find the cause, but I don't know where to start.

**Comment by akien-mga** [comment]
I tested the MRP on a Pixel 7a with 4.3.rc2 and couldn't reproduce the issue sadly.

From the changes in 4.3-beta1 where you report the regression starting, I mostly notice this PR which sounds related:
- #84331

If you can build Godot from source, I would suggest trying to build from the latest `master` branch with that PR reverted locally to see if that solves the issue on your more complex reproduction project.

CC @Alex2782 @m4gr3d

**Comment by Alex2782** [comment]
After 10 minutes of testing I could not reproduce it yet.

I have extended the `info` function to visually separate the event output:

```gdscript
func info(signal_name: String) -> void:
	if (signal_name == "button_down"): print("-------------------------------")
	print("%s/%s/%s" % [name, signal_name, "is pressed" if button_pressed else "is not pressed"])
```

`adb logcat -s godot`

On Android always 4 events as in the editor with `pressed` and `toggled` events:

<details><summary>logcat</summary>

```
08-08 12:03:48.483 13232 13336 I godot   : CheckBox2/button_down/is pressed
08-08 12:03:48.515 13232 13336 I godot   : CheckBox2/toggled off/is not pressed
08-08 12:03:48.515 13232 13336 I godot   : CheckBox2/pressed/is not pressed
08-08 12:03:48.515 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:03:49.116 13232 13336 I godot   : -------------------------------
08-08 12:03:49.116 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:03:49.181 13232 13336 I godot   : CheckBox2/toggled on/is pressed
08-08 12:03:49.181 13232 13336 I godot   : CheckBox2/pressed/is pressed
08-08 12:03:49.181 13232 13336 I godot   : CheckBox2/button_up/is pressed
08-08 12:03:49.269 13232 13336 I godot   : -------------------------------
08-08 12:03:49.269 13232 13336 I godot   : CheckBox2/button_down/is pressed
08-08 12:03:49.339 13232 13336 I godot   : CheckBox2/toggled off/is not pressed
08-08 12:03:49.339 13232 13336 I godot   : CheckBox2/pressed/is not pressed
08-08 12:03:49.339 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:03:49.430 13232 13336 I godot   : -------------------------------
08-08 12:03:49.430 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:03:49.497 13232 13336 I godot   : CheckBox2/toggled on/is pressed
08-08 12:03:49.497 13232 13336 I godot   : CheckBox2/pressed/is pressed
08-08 12:03:49.497 13232 13336 I godot   : CheckBox2/button_up/is pressed
08-08 12:03:49.572 13232 13336 I godot   : -------------------------------
08-08 12:03:49.573 13232 13336 I godot   : CheckBox2/button_down/is pressed
08-08 12:03:49.644 13232 13336 I godot   : CheckBox2/toggled off/is not pressed
08-08 12:03:49.644 13232 13336 I godot   : CheckBox2/pressed/is not pressed
08-08 12:03:49.644 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:03:49.714 13232 13336 I godot   : -------------------------------
08-08 12:03:49.714 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:03:49.781 13232 13336 I godot   : CheckBox2/toggled on/is pressed
08-08 12:03:49.782 13232 13336 I godot   : CheckBox2/pressed/is pressed
08-08 12:03:49.782 13232 13336 I godot   : CheckBox2/button_up/is pressed
08-08 12:03:49.850 13232 13336 I godot   : -------------------------------
08-08 12:03:49.850 13232 13336 I godot   : CheckBox2/button_down/is pressed
08-08 12:03:49.922 13232 13336 I godot   : CheckBox2/toggled off/is not pressed
08-08 12:03:49.923 13232 13336 I godot   : CheckBox2/pressed/is not pressed
08-08 12:03:49.923 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:03:50.007 13232 13336 I godot   : -------------------------------
08-08 12:03:50.007 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:03:50.081 13232 13336 I godot   : CheckBox2/toggled on/is pressed
08-08 12:03:50.081 13232 13336 I godot   : CheckBox2/pressed/is pressed
08-08 12:03:50.081 13232 13336 I godot   : CheckBox2/button_up/is pressed
08-08 12:03:50.141 13232 13336 I godot   : -------------------------------
08-08 12:03:50.141 13232 13336 I godot   : CheckBox2/button_down/is pressed
08-08 12:03:50.226 13232 13336 I godot   : CheckBox2/toggled off/is not pressed
08-08 12:03:50.226 13232 13336 I godot   : CheckBox2/pressed/is not pressed
08-08 12:03:50.226 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:03:50.249 13232 13336 I godot   : -------------------------------
08-08 12:03:50.249 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:03:50.306 13232 13336 I godot   : CheckBox2/toggled on/is pressed
08-08 12:03:50.306 13232 13336 I godot   : CheckBox2/pressed/is pressed
08-08 12:03:50.306 13232 13336 I godot   : CheckBox2/button_up/is pressed

```
</details>



![image](https://github.com/user-attachments/assets/5a12ffe3-9422-4d45-97ce-4c90d6cd034f)

**Comment by Alex2782** [comment]
maybe now? video see below
`drag` issue / regression ? sometimes without `pressed` and `toggled` events

```
08-08 12:24:01.697 13232 13336 I godot   : -------------------------------
08-08 12:24:01.697 13232 13336 I godot   : CheckBox2/button_down/is not pressed
08-08 12:24:03.796 13232 13336 I godot   : CheckBox2/button_up/is not pressed
08-08 12:24:09.339 13232 13336 I godot   : -------------------------------
08-08 12:27:05.835 13232 13336 I godot   : Button2/button_down/is pressed
08-08 12:27:08.052 13232 13336 I godot   : Button2/button_up/is not pressed
08-08 12:27:09.109 13232 13336 I godot   : -------------------------------
```


https://github.com/user-attachments/assets/73bc68d7-87f3-4590-8a3a-4a69ea144f01

**Comment by daveTheOldCoder** [comment]
> normal 'touch' events could be interpreted as 'drag' events

That's interesting.

I haven't had time to investigate all the information in the recent replies yet. But in my original complex project, the problematic controls were inside draggable panels. When I changed the BaseButton action_mode property from ACTION_MODE_BUTTON_RELEASE to ACTION_MODE_BUTTON_PRESS. and then touched a problematic control, the panel started moving as if I were dragging it.

**Comment by Alex2782** [comment]
PR #84331 there is no longer a threshold value for when a `drag` event starts. ([src](https://github.com/godotengine/godot/pull/84331/files#diff-d9881111f9d2a09397eac545bc4cf04cdb84ca5fa2301063fcdeef4ed8bdd9c5R202))

Here is the official Android API for comparison:
<details><summary>androidx.core sources</summary>

![image](https://github.com/godotengine/godot/assets/41921395/a4d26f13-f018-4932-aa8c-47fdbb5531a0)
![image](https://github.com/godotengine/godot/assets/41921395/068ddd49-1697-4835-97e7-4a238e040dc9)
</details>

I'll try to find time next week to find solutions for this. I think it should work like `mouse drag events`. If I hold the left mouse button and move the mouse pointer like in the video, the `pressed` events are still triggered when I release the mouse pointer inside the button.

**Comment by daveTheOldCoder** [comment]
>If you can build Godot from source, I would suggest trying to build from the latest master branch with that PR reverted locally to see if that solves the issue on your more complex reproduction project.

I haven't build Godot recently, although I keep a local copy of the repository up to date.

I assume this is still the correct command (from my notes) for building. If it's wrong, please let me know.
`scons -j8 --debug=time platform=x11`

**Comment by daveTheOldCoder** [comment]
>If you can build Godot from source, I would suggest trying to build from the latest master branch with that PR reverted locally to see if that solves the issue on your more complex reproduction project.

I rebuilt the engine from the latest master branch commit 739019e4e4a6e4763e37adfd9883a1c85d5f6249, manually reverting that PR's changed file to the previous version https://github.com/Alex2782/godot/blob/e04a38775b45d25155d7658d3914d4eef2b9fd42/platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt

That did not fix the issue in the Android export.

I used the official prebuilt 4.3-rc3 export templates. Do they need to be rebuilt? I tried to rebuild them, but got errors.

**Comment by Alex2782** [comment]
1. `godot-github % scons platform=android target=template_debug arch=arm64`
2. `cd ./platform/android/java`                           
3. `./gradlew generateGodotTemplates`
4. use `Custom Template`, with V4.3-rc2 or V4.3-rc3 Editor
![image](https://github.com/user-attachments/assets/e03a1100-6563-4123-a8ca-59ed35a2ef58)

**Comment by daveTheOldCoder** [comment]
@Alex2782

Do I need to build custom Android templates after manually reverting your PR?

**Comment by Alex2782** [comment]
@daveTheOldCoder  

> after manually reverting your PR

How did you do that? A function is not found: `handleMotionEvent`, file: `GodotGestureHandler.kt`

```
> Task :lib:compileTemplateDebugKotlin FAILED
e: file:///home/dave/github/godot/platform/android/java/lib/src/org/godotengine/godot/input/GodotGestureHandler.kt:65:21 Unresolved reference: handleMotionEvent
```

> Do I need to build custom Android 

Yes, if you want to test the projects on Android. I use the normal Editor, last versions 'rc', 'beta' or 'dev' extra compiling the editor should not be necessary.

**Comment by daveTheOldCoder** [comment]
> How did you do that?

I downloaded the previous version of GodotGestureHandler.kt, and copied it over the new version of the file.

I now see that could fail if there were interdependencies with other files.

Should I use the _git revert_ command to do that? I was just looking at its documentation, but I'm not sure which parameters and options to use.

**Comment by Alex2782** [comment]
please try: https://github.com/Alex2782/godot/tree/master_without_pr_84331

[compare](https://github.com/godotengine/godot/compare/master...Alex2782:godot:master_without_pr_84331)

<details><summary>details / how to</summary>

--------------------------

I'm no Git guru, but `revert` seems to be the right solution. After that I solved all conflicts with `VS Code`. 
<details><summary>screenshot: VS Code</summary>

![image](https://github.com/user-attachments/assets/37ef6fed-1cec-4d22-85a3-4a2727ce9aaf)
</details>

But it was not enough, I had to change one line. 
_(I used Android Studio to find the error `Unresolved reference: handleMotionEvent`.)_

**from:**
![Bildschirmfoto 2024-08-09 um 18 04 48](https://github.com/user-attachments/assets/248315f4-3530-4516-83c2-d9a938d0a226)

**to:**
![image](https://github.com/user-attachments/assets/c1fa0849-35e4-4c2a-8475-9fa78d20f714)

</details>

**Comment by daveTheOldCoder** [comment]
Okay, I'll try that next.

Right now, I've checked out the parent of your PR's commit, and am building the Android templates from that:
`git checkout 40b4130`

**Comment by daveTheOldCoder** [comment]
>git checkout 40b4130

Using the Android templates built from that, the problem I reported in the original post _does **not** occur_.
To export to Android, I used Godot editor v4.3.rc3.official [03afb92ef] and the custom Android templates.

>master_without_pr_84331

Would it help if I tried that too?

**Comment by daveTheOldCoder** [comment]
>I have tested MRP again and could not find any issues / regression.

That MRP is not very good. I can try to improve it, but suggestions would be helpful. Maybe I should try using a larger piece of the original project.

**Comment by Alex2782** [comment]
> Maybe I should try using a larger piece of the original project.

It would be no problem for me to use the original project. It is sufficient if the project navigates directly to the scene where the issues occur at startup.

**Comment by daveTheOldCoder** [comment]
I've made a copy of the original project, and am removing as much as I can from it, without changing the issue symptoms.

I'll post it here when I'm finished, which may take a day or so. I'll include instructions on using it.

**Comment by daveTheOldCoder** [comment]
Here's the new MRP. The project folder includes a README file with instructions.

Let me know if you have any questions.

[issue_93612_mrp1.zip](https://github.com/user-attachments/files/16570405/issue_93612_mrp1.zip)

**Comment by Alex2782** [comment]
> 3b. The Cleaning Log page displays a scrolling list of panels. Each panel has a checkbox labeled Delete. Touching a checkbox should toggle it between the checked and unchecked states. But in an Android export, the checkboxes do not respond to touches.

`v4.3.rc2.official [3978628c6]`

Test: https://youtu.be/dLyGqLA8avk on Samsung Tab S7 (11" Display)

I am not sure if I have tested it correctly. The list can also be scrolled "slightly" horizontally if you do not touch the display cleanly and swipe, then the "drag" event is executed earlier because of PR #84331  (i think)

Out of approx. 100 touches, the checkboxes were not switched a maximum of 3 times, and you also have to wait approx. 500 milliseconds after each touch.

**Comment by daveTheOldCoder** [comment]
Did you test the next item (3c. The Edit Profile page...)?

Do you have any idea why I get different results on my Samsung Galaxy S9? And why the problem occurs only when the PR is applied?

**Comment by daveTheOldCoder** [comment]
> The list can also be scrolled "slightly" horizontally if you do not touch the display cleanly and swipe, then the "drag" event is executed earlier because of PR https://github.com/godotengine/godot/pull/84331 (i think)

THAT WAS IT!

If I set the ScrollContainer's Scroll Deadzone property to 10 (it was 0), the problem does not occur. :grinning: 

I confirmed this in both the MRP and the original project.

**Comment by Alex2782** [comment]
I have now also tried it on my `Pixel 4a` (5" display) without `Scroll Deadzone`, it also works well (3b and 3c). It is only smaller and harder to hit the checkboxes.

I didn't know `Scroll Deadzone` until now, there already seems to be a configuration option, **can this issue report be closed?**

PR #84331 bypasses the "natural" deadzone in the Android API "onScroll" event. 
So that gaming controls work better: comment from issue #84138
>I'm attempting to have fine control of a screen element on mobile using touch. Specifically for controlling a pick in a lock picking mini-game. Current testing is on Android.

>But regardless of the input methods I've tried after pressing on the pick there is no motion until the pick suddenly catches up with the touch once it has moved 20+ pixels from the starting location.

**Comment by daveTheOldCoder** [comment]
>can this issue report be closed?

If you're asking me, it can be closed as far as I'm concerned.

**Comment by daveTheOldCoder** [comment]
>can this issue report be closed?

If you're asking me, it can be closed as far as I'm concerned.

**Comment by daveTheOldCoder** [comment]
>can this issue report be closed?

If you're asking me, it can be closed as far as I'm concerned.

**Comment by daveTheOldCoder** [comment]
>can this issue report be closed?

If you're asking me, it can be closed as far as I'm concerned.

**Comment by akien-mga** [comment]
Thanks both for debugging this thoroughly!

**Comment by daveTheOldCoder** [comment]
I'll just note that although I'm satisfied with this solution, it's the first time I've needed to use a non-default value for a ScrollContainer deadzone. Other users might run into this same issue.

**Comment by Alex2782** [comment]
If at some point more users should have problems, then we could perhaps also increase the default value for Android. 

https://github.com/search?q=repo%3Agodotengine%2Fgodot+scroll_deadzone&type=code

**Comment by Alex2782** [comment]
@daveTheOldCoder 
If you find time please try https://github.com/godotengine/godot/issues/95532#issuecomment-2299776861  with your productive projects.

**Comment by daveTheOldCoder** [comment]
Do you mean use the Android template android_debug_base_button.apk linked there with Godot 4.3-stable? Okay, I'll do that within the next few days.

**Comment by Alex2782** [comment]
yes please with `scroll_deadzone` between 0 and 3

**Comment by daveTheOldCoder** [comment]
I tested android_debug_base_button.apk with Godot 4.3-stable, using the project on which I originally opened this issue.

I tested Android exports on a Samsung Galaxy S9 and a Google Pixel 8.

I tested with scroll_deadzone values of 0 and 3.

There were no problems. The buttons and checkboxes worked correctly in all cases.
