### ISSUE TITLE
Inconsistent and Broken Skipping Cursor in Editor - Godot 4.3 Beta 2 Custom

### ISSUE THREAD

**Issue by mirage3d** [godotengine/godot#93618]
### Tested versions

- Reproducible in v4.3.beta.custom_build [6b281c0c0]
- I have not tested this issue in prior versions, but I don't remember this behavior in Beta 1 or any previous version of Godot
- Custom build is for the double-precision flag

### System information

Godot v4.3.beta (6b281c0c0) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.3598) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

The built-in GDScript editor's cursor behaves unexpectedly, inconsistently, and incorrectly, compared to previous versions and editor norms.

Clicking Ctrl-Left and Ctrl-Right makes the cursor skip several tokens at once. Not all code lines suffer from this, and this only happens in "code" lines and not inside comments as far as I can tell.

### Steps to reproduce

- Create or open an existing  script
- Navigate to lines that contain code
- Click Ctrl-arrow keys and watch the cursor erratically; Sometimes skipping 1 token and at other times skipping several tokens at once.

You can use this as an example line:
```gdscript
expect(red.has_method("deactivate")).to.be.truthy("Some generic description of the test")
	red.deactivate()
```
Positioning the cursor at the start of the `expect` token then Ctrl-Right Arrow clicking shifts the cursor to the end of the word `"Some` skipping all the tokens and spaces in between.

### Minimal reproduction project (MRP)

[editor-skip-tokens-bug.zip](https://github.com/user-attachments/files/15983094/editor-skip-tokens-bug.zip)

**Comment by Calinou** [comment]
This may be a regression from https://github.com/godotengine/godot/pull/92514.

cc @vgezer

**Comment by vgezer** [comment]
Yes, indeed. Added a quick fix for it. Appearently DEFAULT PUNCTUATION BLOCK does not contain the basic punctuation.
