### ISSUE TITLE
Godot Engine icon on Steam is only 32x32px

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot#9362]
**Operating system or device - Godot version:**
2.1.3 Steam Release

**Issue description:**

Very low definition of icon, appearing very blurry on windows desktops.
![](http://i.imgur.com/ijpYSw9.png)

**Steps to reproduce:**
Create Godot Engine shortcut from Steam client menus.

**Link to minimal example project:**
Icon stored here
`C:\Program Files (x86)\Steam\steam\games\557bb7b58ccc28fd9e617f4ba49190acf3211480.ico`

**Fix:**
Use a 256x256 version.

**Comment by akien-mga** [comment]
CC @punto-.

**Comment by timoschwarzer** [comment]
We can use the icon from the Windows platform directory https://github.com/godotengine/godot/blob/master/platform/windows/godot.ico
I updated it some days ago and it should have a 256x256 version.

**Comment by akien-mga** [comment]
This should now be fixed for macOS and Windows, using respectively .icns and .ico files which go up to 256x256. This was already good for Linux so no change there.
