### ISSUE TITLE
String does not seemed to be passed by copy when passed through a signal?

### ISSUE THREAD

**Issue by bmer** [godotengine/godot#9365]
**Windows 10. Godot 2.1.3 (official binary).**

**Steps to reproduce:**

1) Open up a new project, and switch to 2D view.

2) Make a Control node as the root of a new scene, call it "Container".

3) Make a Label node (call it "Display"), and a LineEdit node (call it "InputBar").

4) Attach the following script to InputBar:
```

extends LineEdit

signal enter_hit(input_text)

func _ready():
	# Called every time the node is added to the scene.
	# Initialization here
	set_process_input(true)
	connect("enter_hit", get_node("/root/Container/Display"), "display_input")
	
func _input(event):
	if (event.type == InputEvent.KEY):
		if event.scancode == KEY_RETURN:
			emit_signal("enter_hit", get_text())
			get_tree().set_input_as_handled()
			clear()
```

5) Attach the following script to Display:

```
extends Label

var display_text

func _ready():
    display_text = ""

func display_input(text):
    display_text = text
    set_text(display_text)
```

**Issue description:**

Expected behaviour: every time you hit the return key after typing something into the InputBar, InputBar should be cleared of any text, and that text should instead be displayed in Display. 

What happens instead is that the text passed to Display is only momentarily displayed, before disappearing. It seems the issue is the call to `clear()` in InputBar's `_input()` function. If that call is commented out, then things behave as expected BUT InputBar's text is not cleared out after hitting Enter. 

Replacing `clear()` with `set_text("")` does not fix the issue (the same thing happens). 

Assuming that this is because of some issue due to passing-by-reference when there should be a pass-by-copy, I tried replacing `emit_signal("enter_hit", get_text())` with `emit_signal("enter_hit", String(get_text()))` and `emit_signal("enter_hit", str(get_text()))`, with no success.

**Link to minimal example project:**

https://github.com/bmer/godot-string-issue/archive/master.zip

**Comment by akien-mga** [comment]
> https://github.com/bmer/godot-string-issue/archive/master.zip

That repo is empty :)

**Comment by bmer** [comment]
@akien-mga Ah sorry! Try now?

**Comment by akien-mga** [comment]
It's not a bug, it's just that your input processing does not protect itself against repeat/echo events, so you assign the text, clear it, then rerun the same logic several times with the empty text. This fixes it:
```
diff --git a/InputBar.gd b/InputBar.gd
index c898bb6..d3dec7a 100644
--- a/InputBar.gd
+++ b/InputBar.gd
@@ -9,7 +9,7 @@ func _ready():
        connect("enter_hit", get_node("/root/Container/Display"), "display_input")
        
 func _input(event):
-       if (event.type == InputEvent.KEY):
+       if (event.type == InputEvent.KEY and event.is_pressed() and !event.is_echo()):
                if event.scancode == KEY_RETURN:
                        emit_signal("enter_hit", get_text())
                        get_tree().set_input_as_handled()
```

**Comment by bmer** [comment]
@akien-mga Thank you very much!
