### ISSUE TITLE
Add alternative shortcut to Ctrl + Alt + M (Align Transform with View) due to GeForce Experience conflict

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#93668]
### Tested versions

- Reproducible in 4.3 (7907ef835d17cd01c14203c239dc017cbe8605a3)

### System information

Windows 11

### Issue description

When I attempt to press this combination, the connected shortcut doesn't work (currently it's bound to `Align Transform To View` function within 3D editor). All other combinations are working (including `Control+M` or `Alt+M`).

Note: I'm using a mechanical keyboard that should work correctly.

### Steps to reproduce

It's easily can be checked in that window (it's not registering that combination):

![изображение](https://github.com/godotengine/godot/assets/3036176/7d10ff84-ade5-4e3b-9ce0-667aee585d1a)

### Minimal reproduction project (MRP)

No need, too easy to reproduce

**Comment by Calinou** [comment]
I noticed <kbd>Ctrl + Alt + M</kbd> is occasionally ignored by the 3D editor as well (on Linux).

**Comment by Chaosus** [comment]
It's confusing - because it does not work in other applications as well, and if you check it on https://keyboard-test.space/ it behaves differently when pressing compared to other buttons.

**Comment by Chaosus** [comment]
Ah, it's bounded to the NVidia Geforce Experience, which intercepting that keyboard combo. After removing this from its settings, it starts to work correctly.

**Comment by Calinou** [comment]
> Ah, it's bounded to the NVidia Geforce Experience, which intercepting that keyboard combo. After removing this from its settings, it starts to work correctly.

This might be a good reason to find a different default, if it's the default in GeForce Experience.
