### ISSUE TITLE
AnimationTree causes performance drops even if no animation is running

### ISSUE THREAD

**Issue by conde2** [godotengine/godot#93663]
### Tested versions

v4.3.beta2.mono.official [b75f0485b]

### System information

Godot v4.3.beta2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

Whenever using Animation Tree (adding it to scene) even if no animation is running, it drops the FPS by ~50, so if you have 20, that is not much it will drop 1000 FPS.

![image](https://github.com/godotengine/godot/assets/2137569/fa7cfd52-01ad-498c-a5a5-7391763fd332)

Without Animation Tree
![image](https://github.com/godotengine/godot/assets/2137569/dcd5de27-146a-42a2-844e-d233af3009bf)

With Animation Tree (20 nodes)
![image](https://github.com/godotengine/godot/assets/2137569/d5a110d2-5723-4bbd-ad89-626146a1da5d)

### Steps to reproduce

I have a sample project that reproduces it run with the AnimationTrees and press F3 (Thanks @Calinou for the awesome plugin)

And after that delete the AnimationsTrees node and run it again and press F3.

![image](https://github.com/godotengine/godot/assets/2137569/5ce90fd5-5195-4ff2-afac-b4bd81ce2b07)

### Minimal reproduction project (MRP)

[anim_tree.zip](https://github.com/user-attachments/files/16016153/anim_tree.zip)

**Comment by Calinou** [comment]
FPS is not a linear measurement. For example, a drop of 1,000 FPS isn't the same thing at all if you drop from 1050 to 50 FPS (19 mspf difference) compared to dropping from 3050 to 2050 FPS (0.16 mspf difference).

This is why graphics programmers generally never refer to rendering measurements as FPS and always talk in frametime instead (milliseconds per frame, also known as "mspf"). This is a proper linear measurement.

**Comment by conde2** [comment]
![image](https://github.com/godotengine/godot/assets/2137569/9b6f9df4-d645-46e4-965b-0ab2d52d3929)


Thanks for clarification, althought this concept is still weird to me, I will learn more about it before making more assumptions.

If you mean setting this to false, yes I still can reproduce the FPS drop and the increase of mspf.

![image](https://github.com/godotengine/godot/assets/2137569/bec5db68-bff3-4407-92e3-3b2e982b184d)

**Comment by fire** [comment]
What calinou is saying is if enabling AnimationTree drops the frame time from 30 milliseconds to 60 milliseconds it is a very different problem than dropping 30 millisecond to 1 millisecond.

Since you mentioned frame drops one possible interpretation is a 0.1 ms drop to a 0.2 ms drop which is hard to justify work so we need to check in milliseconds per frame units.

**Comment by Calinou** [comment]
> What calinou is saying is if enabling AnimationTree drops the frame time from 30 milliseconds to 60 milliseconds it is a very different problem than dropping 30 millisecond to 31 millisecond.

While the FPS drop might be small here, it has the potential to be larger in a game that has a lot of animated characters, **even if you disable animation processing when far away**. That's the issue we should aim to resolve if possible :slightly_smiling_face: 

I ran some profiles with HotSpot using an optimized (`optimize=speed lto=full`) editor build:

### Top-down view with AnimationTree processing expanded

![Top-down](https://github.com/godotengine/godot/assets/180032/5cb02723-f1b0-4b2e-953c-d7f49e2473a8)

### Flamegraph (full view)

![Flamegraph 1](https://github.com/godotengine/godot/assets/180032/c59cc7b7-b3f0-4828-b050-70cf34884650)

### Flamegraph zoomed on `AnimationTree::_blend_pre_process()`

![Flamegraph 2](https://github.com/godotengine/godot/assets/180032/13f2d265-7ad0-4182-8160-4ef8bcf797ac)

### Flamegraph zoomed on `AnimationTree::_blend_apply_()`

![Flamegraph 3](https://github.com/godotengine/godot/assets/180032/fd043a53-674c-4241-aa13-e14fe234b2af)

**Comment by conde2** [comment]
![Captura de Tela (9)](https://github.com/godotengine/godot/assets/2137569/5bf82ca5-a357-4baf-9a23-80a92153f1d7)

My game has a few creatures in the screen, and its enought to notice that frame time going up. I aim to publish it to mobile, so I was procupied that this could hit the performance on this low end graphic cards devices.

Just to notice thats how I've setup my AnimationTree using AnimationNodeBlendTree with a StateMachine

![image](https://github.com/godotengine/godot/assets/2137569/bff459ea-0406-48e0-9598-cbc10bffb81e)
![image](https://github.com/godotengine/godot/assets/2137569/d08531b2-195d-4faf-9337-a80b891910da)
