### ISSUE TITLE
When inheriting `EditorSceneFormatImporter`, cannot call the parent class' virtual function "_import_scene()" because it hasn't been defined

### ISSUE THREAD

**Issue by arocull** [godotengine/godot#93688]
### Tested versions

- Reproducible in 4.3.beta2, 4.2.2.stable, 4.2.1.stable, 4.2.stable, 4.2.beta1, 4.2.dev6
- Not reproducible in 4.2.dev5, 4.2.dev4, 4.2.dev1, 4.1.1.stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 Threads)

### Issue description

Goal: Create a plugin that inherits `EditorSceneFormatImporterGLTF`, using `super._import_scene(...)` to import the scene, before modifying the scene afterward during the import step, while listed as a separate Scene Format drop-down option.

Issue: GDScript will not let me call the parent `_import_scene(...)` function despite letting me override it.
`Parse Error: Cannot call the parent class' virtual function "_import_scene()" because it hasn't been defined.`

Caveats: Intellisense knows the signature of the function I'm overriding, and provides auto-complete for both the function header and the parent function call (pictured). By control+clicking the function `super._import_scene(...)`, it leads me directly to the function in documentation. When writing this code in Godot 4.1.1, GDscript does not throw an error.

![godot_bug_report](https://github.com/godotengine/godot/assets/23199632/6bafd023-b3b5-4863-976e-af8db66e3ed7)

Expected: I should be able to call the parent function inside my override.

### Steps to reproduce

1. Create a GDScript that extends EditorSceneFormatImporter (or EditorSceneFormatImporterGLTF)
2. Override the `_import_scene(...)` function
3. Attempt to call `super._import_scene(...)` (this line will error)

```gdscript
extends EditorSceneFormatImporter

func _import_scene(path: String, flags: int, options: Dictionary) -> Object:
	super._import_scene(path, flags, options)
	return null
```

### Minimal reproduction project (MRP)

[BugReport-EditorSceneFormatImporter.zip](https://github.com/user-attachments/files/16023301/BugReport-EditorSceneFormatImporter.zip)

Open `scene_importer.gd`, and you will get a parsing error

**Comment by arocull** [comment]
Thinking more on this, not sure if it's actually _intended_ to behave this way as `EditorSceneFormatImporter` would not have a defined function anyhow, but I _would_ expect `EditorSceneFormatImporterGTLF` to have an existing definition.

**Comment by huwpascoe** [comment]
[EditorScenePostImport](https://docs.godotengine.org/en/stable/classes/class_editorscenepostimport.html) is probably what you're after
```gdscript
@tool # Needed so it runs in editor.
extends EditorScenePostImport

# This sample changes all node names.
# Called right after the scene is imported and gets the root node.
func _post_import(scene):
	# Change all node names to "modified_[oldnodename]"
	iterate(scene)
	return scene # Remember to return the imported scene

func iterate(node):
	if node != null:
		node.name = "modified_" + node.name
		for child in node.get_children():
			iterate(child)
```

**Comment by arocull** [comment]
I am familiar with the PostImport script workflow, but thanks! If this is functioning as intended, then the issue can be closed.

I was hoping to find a work-around so I do not have to set import scripts on every file I import, and could instead create a few presets with minimal configuration using this menu (pictured) by creating custom SceneFormatImporters using plugins.

![image](https://github.com/godotengine/godot/assets/23199632/405fbb9e-4e7b-4a06-94ba-eecc8f196ded)

I haven't been able to find a way to create presets other than the default one, despite the Presets button being there.

**Comment by huwpascoe** [comment]
In that case there's the more advanced [EditorScenePostImportPlugin](https://docs.godotengine.org/en/stable/classes/class_editorscenepostimportplugin.html#class-editorscenepostimportplugin-private-method-get-internal-import-options).

As for the technical issue of not being able to call from super class, these virtual functions are stubs for script callback. If the base class wasn't implemented in script, chances are there's no function available to call.

**Comment by arocull** [comment]
Closing as this seems to be working as intended then. Thanks!
