### ISSUE TITLE
Preparing for 2.1.4-stable

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9368]
Same deal as #8087, but for 2.1.4.

> This issue is meant to gather initial feedback on pre-release binaries, so that we can spot regressions (either from new developments or from bad cherry-picks I might have done).
>
> Note: as always I'm only interested in regressions (i.e. bugs that did not affect earlier 2.1.x versions), including to some extent bugs in new features if there are any. Packaging issues with the templates, etc., are of course also interesting :)

**Comment by akien-mga** [comment]
Current binaries for 2.1.4-beta (June 25), please test: http://op.godotengine.org:81/downloads/2.1.4/beta/

The 32-bit Linux editor and template binaries are missing due to Travis and Ubuntu randomly failing, but that should be solved prior to the stable release.

**Comment by ObaniGemini** [comment]
### CRASH on Debian 9

When running Godot 2.1.4 from the "Téléchargements" folder, I get that error :

> SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends
>    At: res://src/game.gdc:2.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gd_script.cpp:682.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gd_script.cpp:1757.
> ERROR: load: Failed loading resource: res://src/game.gd
>    At: core/io/resource_loader.cpp:210.
> ERROR: start: Can't autoload: res://src/game.gd
>    At: main/main.cpp:1354.
> SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends
>    At: res://src/database.gdc:2.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gd_script.cpp:682.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gd_script.cpp:1757.
> ERROR: load: Failed loading resource: res://src/database.gd
>    At: core/io/resource_loader.cpp:210.
> ERROR: start: Can't autoload: res://src/database.gd
>    At: main/main.cpp:1354.
> SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Expected end of statement after extends
>    At: res://src/global.gdc:2.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gd_script.cpp:682.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gd_script.cpp:1757.
> ERROR: load: Failed loading resource: res://src/global.gd
>    At: core/io/resource_loader.cpp:210.
> ERROR: start: Can't autoload: res://src/global.gd
>    At: main/main.cpp:1354.
> SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Unexpected token: ':':CanvasLayer
>    At: res://src/transition.gdc:2.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gd_script.cpp:682.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gd_script.cpp:1757.
> ERROR: load: Failed loading resource: res://src/transition.gd
>    At: core/io/resource_loader.cpp:210.
> ERROR: poll: Can't load dependency: res://src/transition.gd
>    At: core/io/resource_format_binary.cpp:717.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: core/io/resource_loader.cpp:137.
> ERROR: load: Failed loading resource: res://src/transition.tscn
>    At: core/io/resource_loader.cpp:210.
> ERROR: start: Can't autoload: res://src/transition.tscn
>    At: main/main.cpp:1354.
> SCRIPT ERROR: GDScript::load_byte_code: Parse Error: Unexpected token: ':':Control
>    At: res://src/screens/menu/menu.gdc:2.
> ERROR: load_byte_code: Method/Function Failed, returning: ERR_PARSE_ERROR
>    At: modules/gdscript/gd_script.cpp:682.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: modules/gdscript/gd_script.cpp:1757.
> ERROR: load: Failed loading resource: res://src/screens/menu/menu.gd
>    At: core/io/resource_loader.cpp:210.
> ERROR: poll: Can't load dependency: res://src/screens/menu/menu.gd
>    At: core/io/resource_format_binary.cpp:717.
> ERROR: load: Condition ' err != OK ' is true. returned: RES()
>    At: core/io/resource_loader.cpp:137.
> ERROR: load: Failed loading resource: res://src/screens/menu/menu.tscn
>    At: core/io/resource_loader.cpp:210.
> ERROR: start: Failed loading scene: res://src/screens/menu/menu.tscn
>    At: main/main.cpp:1402.
> ERROR: free: Attempt to free invalid ID
>    At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
> ERROR: free: Attempt to free invalid ID
>    At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:595.
> WARNING: cleanup: ObjectDB Instances still exist!
>    At: core/object.cpp:1845.

**Running from an other folder, it works normally**. I checked if it was related to "é" "è" characters but it doesn't seem to be.

**Comment by karroffel** [comment]
@ObaniGemini did you update the export templates?

**Comment by karroffel** [comment]
Oh, you're loading a .gdc file. That's a compiled GDScript, you need to recompile those, the byte code changed.

Usually this shows when you forgot to update the export templates. In this case it could just be outdated compiled script files.

**Comment by ObaniGemini** [comment]
AnimationPlayer : on deleting an animation, a screen appears to confirm saying "duplicate animation", not "delete animation". It's not a regression, it was already there in 2.1.3

**Comment by bojidar-bg** [comment]
@ObaniGemini Open another issue for this, it is clearly not a regression (and thus has no place here).

**Comment by akien-mga** [comment]
FYI, I deleted unrelated comments to get this issue focused on actual regressions... :)

**Comment by josempans** [comment]
I'm not getting Output information in the editor, I can see my print() stuff in shell console, but not in the "Output" tab, or debug: "Remote Debugger: Unable to connect"
Another thing I can see is that when you close the game, the "Play" icon doesn't change, and shows the "Restart" icon.

**Comment by ObaniGemini** [comment]
> Question : on 2.1.4, with AnimatoinPlayer and with discrete points, it now seems that the first value you set will be the value set at the beginning of the anim
> Which means that if you want to make an animtion, for example, based on parst going from visible(false) to visible(true), you have to init all your anim tracks with visible(false)
> It doesn't start with the value the node had
> Is that an intended new behaviour or a regression ?

> Using the value the node had before sounded like a good idea actually
> Makes animation less "hardcoded", they can be played from multiple situations

I'm putting this here so it can be kept alive and "studied".

Should this then be considered as a regression or as a feature ?

**Comment by bojidar-bg** [comment]
@ObaniGemini That seems like a regression, since it would break older projects using 2.1.3..

**Comment by ObaniGemini** [comment]
@josempans : I don't have your bug with the Play icon, even by forcing quitting the game

**Comment by josempans** [comment]
![screens](https://user-images.githubusercontent.com/2577640/27557428-f9db89f0-5a8f-11e7-907f-a9de275f8340.jpg)
Ok, here are a pair of screens... no output information (I have a few prints), and the play button won't change to "restart"... this only happen with a force quit (closing the window, not pressing the Stop)
I've downloaded the beta from the website, and I also build one.

**Comment by ObaniGemini** [comment]
OS ?

**Comment by vnen** [comment]
@josempans anything on the console window?

**Comment by josempans** [comment]
Windows 10. I can read the print output in the console shell.

**Comment by vnen** [comment]
@josempans oh, I meant if there's a relevant error message. Usually connection errors are printed there. Also, try to change the Remote Port in the Debug category of project settings (you have to run the project once for it to appear).

**Comment by josempans** [comment]
Yes, yes... sorry, I thought I've wrote about that... in the console shell I get a message about a connection problem with the debugger

**Comment by Zireael07** [comment]
@josempans: There should be an issue or two about debugger connection problems.

**Comment by cowhand214** [comment]
I am also seeing the behavior @josempans has mentioned. I too am using Win 10. When opening the project in the 2.1.3 stable x64 I see data in the output window from several print statements. However, opening the same project in in the 2.1.4 version I do not see anything in the output window within the editor. I do see the expected print output in the console window. 

I'm a little confused as to the Debug connection exchange above. Is there somewhere I should be checking some settings to enable this behavior? Or other information I can provide? It may be the issue has been resolved and I'm just not clear on how so I apologize if I'm re-raising this unnecessarily.

**Comment by eon-s** [comment]
If somebody else can replicate this issue #8581 (run on android), I have no clue of what happens there.

**Comment by vnen** [comment]
@cowhand214 do you have more than one instance of Godot running, regardless of version? If you open two instances, the second one won't be able to connect to the debugger. You can also try to change the debug port, as I mentioned earlier.

**Comment by josempans** [comment]
Sorry for the delay, last time I've tried the debug connection problem was there. Tomorrow I'll make a new build, and try to find where is the issue. I've built 2.1.3 and 2.1.4, and the .4 has that problem.

**Comment by Dodgetgo** [comment]
Raycast Arrows are turned wrong way while the lines are in correct direction 
![image](https://user-images.githubusercontent.com/14287132/27990040-6e7b83a4-640f-11e7-95e5-961270d1217e.png)

**Comment by akien-mga** [comment]
@Dodgetgo Please make a new bug report for it so that it's easier to track down.

**Comment by josempans** [comment]
@vnen Ok, I know what was going on. No problems with source, it seems the editor was trying to connect with other address than 127.0.0.1. So, I changed that in Editor Settings, and the debugger was able to connect without problem.

**Comment by RebelliousX** [comment]
In the beta of Godot v2.1.4, I also have the same issue as @josempans debugger output not shown. Only shown in console. Running one instance of Godot and v2.1.3 works fine. Changing "Remote Port" in project settings didn't help. Console window doesn't show any debugger connection error. It is worth mentioning that when starting Godot, it displays the copyright notice, but once you run a game, output disappears.

Even if there is some setting that can alleviate this issue, it is still a regression nevertheless.

Also, exiting game by clicking on the [x] on the top corner of the window, Godot does not terminate execution. I have to manually click on stop at the top of Godot.

**Comment by akien-mga** [comment]
@RebelliousX Can you try to compile the 2.1 branch from source? It might have been fixed recently.

**Comment by RebelliousX** [comment]
@akien-mga No luck, I just compiled it and same behavior. Though, I am getting "Remote Debugger" connection failed now.
![capture](https://user-images.githubusercontent.com/1888186/28639668-a55697a8-720e-11e7-9a16-0618ed0a535d.PNG)

**Comment by RandomShaper** [comment]
Yes, https://github.com/godotengine/godot/commit/0aa6b4aac74971addd98ab3ed465b0febc4633d9 should be reverted. It would be a good thing if it had been always the case, it's good for 3.0, but a breaking change for 2.1. My own game heavily relies on the "unfixed" behavior.

**Comment by RandomShaper** [comment]
My #8999 included a point:
> Implement index shifting (or marking as -1) for shapes indices in collision pairs shapes are removed.

I'm not completely sure that is needed. If @reduz confirms, I'll port that point to 3.0 to make #9832 complete.

If he says that's not needed, I'll revert that only point from 2.1 because it might impact performance.

**Comment by brenttaylor** [comment]
Not a regression, but seeing as Visual Studio 2015 is no longer being offered for download and Godot 2.x doesn't support Visual Studio 2017 yet I think #9902 should be considered for inclusion of the next release.  It's just a build script update and doesn't touch Godot itself.

**Comment by eon-s** [comment]
@brenttaylor I have only seen MSVC 2015 but was unable to make it work so a patch for 2017 may be needed.

**Comment by brenttaylor** [comment]
@eon-s There were some changes to the build scripts in the master branch that added support for VS2017.  I'll try and poke at it tomorrow and see if I can get the 2.1 branch compiling against VS2017 properly and if I can get the master branch working against the VS2015 build tools.  Should be an easy fix.  Famous last words, I know.

**Comment by eon-s** [comment]
@brenttaylor I can compile 2.1 with 2017 but for 32bit only (no matter which console I use, it does not detect 64), I have not tried master yet.

**Comment by RandomShaper** [comment]
I've been able to build 2.1 (64-bit) with MSVC 2017 just by cherry-picking 14a982a0c2100a2a406421f017b11340f7a38316.

**Comment by RandomShaper** [comment]
The only thing I'm not being able to achieve is generating a VS project with `vsproj=yes`  (neither in _2.1_ nor _master_). And this time it does look as an issue with SCons VS 2017 support, doesn't it?

**Comment by vnen** [comment]
@RandomShaper AFAIK this commit broke the build with VS 2015, so there was a follow-up (#8876). And yes, SCons does not support VS 2017 yet. Never tested the project generation with 2017, but it worked with earlier versions.

**Comment by RandomShaper** [comment]
#9922 is here to fix Android debug/run issues!

**Comment by eon-s** [comment]
After 9922 gets merged could be good to have another beta/rc to test official builds and templates, because there were lot of fixes since the last beta.

**Comment by eon-s** [comment]
Another bug on the new debugger #10030 (beta 2)

**Comment by akien-mga** [comment]
All good, let's roll this 2.1.4-stable.
