### ISSUE TITLE
Signal tooltip doesn't go away when moving mouse to another signal in single window mode

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#93698]
### Tested versions

- Reproducible in: v4.3.beta2 (with ```--single-window```), v4.3.beta1 (with ```--single-window```).
- Not reproducible in: v4.3.beta2 (normal), v4.3.beta1 (normal), v4.2.2.stable

### System information

Godot v4.3.beta2 - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:49:19 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

When hovering over a signal in the editor the tooltip will stay in place even when hovering over another signal, multiple
tooltips of the same signal can be stacked by moving from one signal to the other.

![24-06-28_09-43-23](https://github.com/godotengine/godot/assets/120836609/77901617-bc80-437d-af9f-e0d5e30a9a20)

Tooltips will go away when moving the mouse outside the signals tab.

### Steps to reproduce

- Run Godot with the ```--single-window``` flag;
- Go to any node's signal tab and hover over a signal;
- Hover over another signal without moving the mouse out of the signals tab.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
> ### Tested versions
> 
>     * Reproducible in: v4.3.beta2 (prefer_wayland enabled), v4.3.beta1 (prefer_wayland enabled).
> 
>     * Not reproducible in: v4.3.beta2 (prefer_wayland disabled), v4.3.beta1 (prefer_wayland disabled), v4.2.2.stable

Do you reproduce the issue with `prefer_wayland` disabled, but `--single-window` on the command line?

That should help clarify whether it's a Wayland specific or a single window mode specific issue (which is the only supported mode for Wayland currently).

**Comment by em-s-h** [comment]
After testing it seems that ```--single-window``` is the cause as disabling or enabling ```prefer_wayland``` doesn't fix the issue, but only on the beta versions

**Comment by matheusmdx** [comment]
This a regression from pr https://github.com/godotengine/godot/pull/89058 (see https://github.com/godotengine/godot/issues/92382#issuecomment-2132279871)

**Comment by akien-mga** [comment]
CC @dalexeev @KoBeWi
