### ISSUE TITLE
Normal values gets changed even when using `skip_vertex_transform` render_mode

### ISSUE THREAD

**Issue by Mohamed-Kr** [godotengine/godot#93693]
### Tested versions

4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When creating an ArrayMesh with custom values in the normal channel, these values get changed even with the ```skip_vertex_transform``` render_mode. This happens with all three renderers.

![image](https://github.com/godotengine/godot/assets/43796250/dbc1a7c2-d0bb-4cf9-b400-7b436425723c)

### Steps to reproduce

Create two array meshes
one with uv's in the color channel that should appear correct.
and one with uv's in the normal channel that should appear distorted.

The bug reproduction scene below contains this setup.

### Minimal reproduction project (MRP)

Here is the scene reproducing the bug with all resources built-in.

[BugRepro.zip](https://github.com/user-attachments/files/16026222/BugRepro.zip)

**Comment by huwpascoe** [comment]
Normals and colors are compressed data. Ever seen a normal map turn yellow after importing? Compression. Using color for UV will probably also glitch once the atlas size exceeds 256x.

There's no efficiency or memory saving to be had avoiding ARRAY_TEX_UV. If only ARRAY_VERTEX and ARRAY_TEX_UV have data, the vertex buffer will essentially have a stride of 5 floats if interleaved. The driver will work out the most efficient layout.

**Comment by Mohamed-Kr** [comment]
@huwpascoe I was trying to use multiple different channels with custom values for a complex thing, where parts of the mesh would be billboarded, other parts not but would have a different custom behaviour and it would give different 'triangle types' in the end.
for example NORMAL.x could indicate the type of the current vertex, and then NORMAL.y for example for the x coordinate of the billboard pivot when the type is billboard and if the type is different some other information relevant to that behaviour ect.

From what I understood CUSTOM.x for example can only have 255 different values and it is not sufficient for my use case, that's why I'm doing this with the NORMAL channel.

but anyways, I knew normal map textures and albedo textures could be compressed but here I'm using the NORMAL vectors channel, I didn't think these could get compressed, and same for the COLOR vectors channel, as I'm not using a texture but a PackedColorArray.

**Comment by huwpascoe** [comment]
Rest assured that the custom channels *can* be other types via the flags parameter of [add_surface_from_arrays](https://docs.godotengine.org/en/stable/classes/class_arraymesh.html#class-arraymesh-method-add-surface-from-arrays)! A full vec4 can be stored if the channel is configured as ARRAY_CUSTOM_RGBA_FLOAT.

**Comment by Mohamed-Kr** [comment]
@huwpascoe Oh I see, thanks a lot !

**Comment by clayjohn** [comment]
Normals are normalized Vector3s. It can't be used as a general purpose data storage channel since it is heavily compressed and assumes that the content is normalized. 

We should add a note to the docs here to explicitly say that the normal needs to be normalized (and will get normalized by the engine if it isn't) https://docs.godotengine.org/en/latest/classes/class_mesh.html#class-mesh-constant-array-normal

As the other commentors have pointed out, we provide custom attributes for custom data, you can even choose your data format, so they are always a better option.

**Comment by akien-mga** [comment]
Fixed by #93872.
