### ISSUE TITLE
Due to malformed Mach-o file, cannot run Godot app on Apple Silicon Mac

### ISSUE THREAD

**Issue by Heisenberg-me** [godotengine/godot#93692]
### Tested versions

v4.2.2.stable

### System information

macOS 14.2.1 - Godot v4.2.2.stable - M1 Pro

### Issue description

I downloaded the zip of Godot v4.2.2.stable and unzipped it.

During the process of unzipping by The Unarchiver app, the app sent the error message "Unable to archive from 'Godot_v4.2......'". But it also unzipped it and the app appeared on my desktop.

I ran Godot, but macOS sent the message "Cannot run the app".

I found the file "/Applications/Godot.app/Contents/MacOS/Godot". It should be a Unix Executable file, but it wasn't. Then I used `chmod +x ./Godot` to let it be an executable file.

But macOS still sent the message "Cannot run the app".

I used `open /Applications/Godot.app`, the Terminal app said `The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10810 "kLSUnknownErr: Unexpected internal error" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=3057, NSUnderlyingError=0x600000496e20 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600000496f40 {Error Domain=NSPOSIXErrorDomain Code=88 "Malformed Mach-o file" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}}}`

I used `/Applications/Godot.app/Contents/MacOS/Godot`, the Terminal app said  `zsh: malformed Mach-o file: ./Godot`

I can't continue trying to solve this problem; I want to know the answer.

### Steps to reproduce

=Issue description

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
The most likely scenario is that your download was corrupted.

You can calculate the SHA512 sum with `shasum -a 512 path/to/zip` and compare it with the value in https://github.com/godotengine/godot-builds/releases/download/4.2.2-stable/SHA512-SUMS.txt

Redownloading the file would likely fix the issue.

**Comment by Heisenberg-me** [comment]
Thanks. My friend downloaded it and sent to me. It can be used now.
