### ISSUE TITLE
Godot 4.3-beta2 can't import blender files on macOS

### ISSUE THREAD

**Issue by frklan** [godotengine/godot#93719]
### Tested versions

Not working in v4.3.beta2.mono.official [b75f0485b] nor v4.3.beta2.official [b75f0485b]

Works as intendent in v4.2.2.stable.mono.official [15073afe3]

### System information

macOS 14.5, M1 Max

### Issue description

When I add a bleder file to my project, Godot asks for the path to the blender app, the 'confirm path' is disabled whatever I enter.

![bild](https://github.com/godotengine/godot/assets/761696/5fa929e3-b050-4e71-87cc-ef2dd9557da3)

Perhaps I'm doing something wrong?

### Steps to reproduce

- Create new project
- Add blender file

### Minimal reproduction project (MRP)

n/a

**Comment by patwork** [comment]
Did you try to search for another path? Why there's a letter "C" or "O" after MacOS in your path? It seems like it should be "B" 

`"/Applications/Blender.app/Contents/MacOS/Blender"`

https://github.com/godotengine/godot/blob/25de53e147a04ba15afc461b3ad4aa1884ff927d/modules/gltf/editor/editor_scene_importer_blend.cpp#L406-L460

**Comment by frklan** [comment]
Yeah, I accidentally entered the path multiple times 🤯. Sorry about the mistake. Thank's for the help @patwork.
