### ISSUE TITLE
Color Picker eyedropper tool selects Node instead of picking color in single window mode

### ISSUE THREAD

**Issue by bogcow** [godotengine/godot#93718]
### Tested versions

4.3.beta2

### System information

Windows 10

### Issue description

https://github.com/godotengine/godot/assets/157412753/c51c5838-9fb5-40e0-8f18-e904d461cc80

In the video, I try to use the eyedropper tool of the ColorPicker, but whenever I select the red color (which is a ColorRect), instead of properly changing the color, the red ColorRect is selected instead. This behavior seems much more consistent when you are on single window mode, but it also occurs when you are not on single window mode as well.

### Steps to reproduce

- Download the sample project
- Change editor settings to enable single window mode
- Try to change the modulate property of the white ColorRect by using the color picker eyedropper onto the red area

### Minimal reproduction project (MRP)

[Test.zip](https://github.com/user-attachments/files/16036512/Test.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #74962 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/55cafd6e-d106-4d22-b17a-93795e2a1235)

<br>

I also tried to reproduce the issue without --single-window but wasn't able to replicate.

**Comment by cjmaxik** [comment]
Still reproducible in 4.3-rc1

**Comment by akien-mga** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
It's worse than that. When another node gets selected, the color change is not stored in undo history.
