### ISSUE TITLE
[Regression] Script classes instantiated manually in a variable can't call their own instance functions anymore

### ISSUE THREAD

**Issue by reflexguru** [godotengine/godot#93715]
### Tested versions

- Reproducible in `4.3 beta 1` and `4.3 beta 2`
- Not reproducible in `4.3 dev 6` and `4.2.2 stable`

### System information

Linux - Freedesktop SDK 23.08 (Flatpak runtime) - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) () - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Starting from `4.3 beta 1`, there's a weird issue that prevents the scripts instantiated in a variable from calling their own instance functions (method not found error). However, it "works" when you make the function static. Our project relies on that and doesn't work at all now.

While the functions can't be called in `4.3 beta 1` and newer, they can be printed to console just fine.

I have searched for a similar issue here, but with no results. If it's a duplicate, please close the issue.

Screenshots and minimal reproduction project are attached below

`4.3 dev 6`, works fine:
![Screenshot from 2024-06-28 22-40-32](https://github.com/godotengine/godot/assets/31435600/226c7c31-9c99-460d-a74f-8c01c130d6e8)

`4.3 beta 2`:
![Screenshot from 2024-06-28 22-40-59](https://github.com/godotengine/godot/assets/31435600/4df0c8cd-9430-443d-a0c7-50bf170c2ab5)

### Steps to reproduce

- Create a class that extends the GDScript class with abstract methods for `_ready`, `_process`, `_physics_process`, etc
- Try calling _ready from _init as an example
- Try assigning it to a variable of your object
- See it break in `4.3 beta 1` or newer versions

### Minimal reproduction project (MRP)

[gd-bug-reproduction.zip](https://github.com/user-attachments/files/16036238/gd-bug-reproduction.zip)

This project is built in `4.2.2 stable`, so you can test it in 4.2.x as well

**Comment by matheusmdx** [comment]
Tested on latest master [811ce36c6] and this issue was already fixed, probably was the same problem from #92610 and was fixed by https://github.com/godotengine/godot/pull/92609

**Comment by reflexguru** [comment]
tested in beta 3, works fine now
