### ISSUE TITLE
RegEx::search should return an empty RegExMatch in mis-matching cases versus a null Object.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9372]
**Context**
Windows 10
Visual Studio 2015
Godot 3.0 (current build)
I'm relatively new to messing around with the Godot internals, so I apologize if I simply don't understand something.

**Issue description:**
RegEx::search supposedly returns a null object when it fails to match something and a RegExMatch object when it successfully makes a match (in GDScript). However, I'd suggest that the returned object from the function be a RegExMatch object regardless. Just have an "empty" one with no matched content.

**Suggested Action**
I believe the only change that needs to occur is line 1375 of `modules/regex/regex.cpp`, however I'm not sure what to change it to (from NULL) that would be most efficient and prevent memory leakage.

My guess is that returning `Ref<RegExMatch>(memnew(RegExMatch()))` is inefficient, but when I tried updating it to `Ref<RegExMatch>(nullptr)` or the former on a branch in my fork, neither appeared to fix the problem.

**Comment by akien-mga** [comment]
CC @leezh

**Comment by willnationsdev** [comment]
Note that one could always force a RegExMatch result by doing...

`var expr = "("+expr+"|.*)"`

...which would automatically capture everything as a last result if it failed to match other cases you've defined. However, the bigger issue is that the return value being Object prevents the GDScript editor from doing any auto-complete / Intellisense-type stuff for the returned RegExMatch object which becomes a usability issue.

**Comment by leezh** [comment]
If it's about getting auto-complete, it's a simple fix: https://github.com/godotengine/godot/compare/master...leezh:regex_bind_fix

But if there's another reason, it should be do-able. We can do this by ignoring the check at `modules/regex/regex.cpp:1373` and `return res;` no matter the condition. However, we'd also need to add in an additional function like `has_match()`.

The biggest downside is that it would break existing scripts out there (the handful of us) that does `search() == null` in gdscript or `res.is_valid()` in C++.

**Comment by leezh** [comment]
I mean, in principle returning null is not such a big deal; `get_texture` does it when no texture is set. By returning null, we are making it explicitly clear that there is nothing that can be done with the data.

**Comment by willnationsdev** [comment]
Ah, yeah it might be a bad idea to break so many other scripts, especially if there's already a convention with textures. It doesn't seem like that fix has been merged into the master branch yet and it's mainly the auto-complete that's been bothering me as a user. Appreciate the guidance @leezh.
