### ISSUE TITLE
Input event gets fired for all instances of node

### ISSUE THREAD

**Issue by gyrosp** [godotengine/godot#9374]
**Windows 7 / Godot 2.1.3**

**Input event gets fired for all instances of node**
I dynamically add nodes to a GridContainer during runtime. I was expecting, that an Mouse-Input-Event is only fired for the node that is below the mouse but events are fired for all nodes.

**Steps to reproduce:**
**-Create a scene with a GridControler**
**-Create another scene with a Control and add some instances of the Control into the GridController**
**-Implement a simple input-handling-function in the Control like this**
```
func _input(event):
	if (event.is_action_pressed("touch")):
		printt("touched ",  mPosInGrid.x,  " / ",  mPosInGrid.y)
```

**Link to minimal example project:**
[Test.zip](https://github.com/godotengine/godot/files/1100633/Test.zip)

**Comment by reduz** [comment]
yes, _input is a global handler. Use _input_event instead, or _gui_input in
3.0

**Comment by gyrosp** [comment]
Thanks for the answer :). I've changed to _input_event but now I have the problem,that the clickable area of the Control is very small in the upper left corner. I don't get it to resize to the childs background-icon size. 

Whats the way to go to set the clickable size of the root-Control to the same size as the child node programmatically.

**Comment by akien-mga** [comment]
> now I have the problem,that the clickable area of the Control is very small in the upper left corner. I don't get it to resize to the childs background-icon size.

That's probably a good question for the Q&A, if not answered there already: https://godotengine.org/qa
