### ISSUE TITLE
multiplayer.multiplayer_peer.get_connection_status() always returns 2

### ISSUE THREAD

**Issue by TomSomerville** [godotengine/godot#93741]
### Tested versions

Godot 4.2.2

### System information

Windows 10 - Godot Engine v4.2.2.stable.official.15073afe3 -Vulkan API 1.3.277 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

multiplayer.multiplayer_peer.get_connection_status() Always returns 2, no matter the actual connection status. 

### Steps to reproduce

Simply print multiplayer.multiplayer_peer.get_connection_status()
I created a new project,  added a button, added a script to the button, connected the _on_pressed signal, print get_connection_Status()

![image](https://github.com/godotengine/godot/assets/24684648/7efff75d-418c-4af1-b730-1e570b22409d)

### Minimal reproduction project (MRP)

[playground.zip](https://github.com/user-attachments/files/16040793/playground.zip)

**Comment by AThousandShips** [comment]
This is because the multiplayer API defaults to using an `OflineMultiplayerPeer` if none is assigned

**Comment by TomSomerville** [comment]
Additionally, if you set multiplayer.multiplayer_peer = null (as recommended in godot docs to terminate networking), multiplayer.multiplayer_peer.get_connection_status() will crash out your program "cannot call method 'get_connection_status' on a null value

**Comment by TomSomerville** [comment]
> This is because the multiplayer API defaults to using an `OflineMultiplayerPeer` if none is assigned

What is the appropriate way to determine if your game is connected to the HLMultuiplayer network then?

**Comment by AThousandShips** [comment]
> multiplayer.multiplayer_peer.get_connection_status() will crash out your program "cannot call method 'get_connection_status' on a null value"

If you've set it to `null` then it will obviously crash if you try to operate on it, that's expected, you need to check that it's not null

> What is the appropriate way to determine if your game is connected to the HLMultuiplayer network then?

Check that it's not an `OfflineMultiplayerPeer`, like so:
```gdscript
multiplayer.multiplayer_peer is not OfflineMultiplayerPeer
```

**Comment by TomSomerville** [comment]
> Check that it's not an `OfflineMultiplayerPeer`, like so:
> 
> ```gdscript
> multiplayer.multiplayer_peer is not OfflineMultiplayerPeer
> ```

Is there more to this you did not mention? As written this doesnt appear to work either. Implementing "if multiplayer.multiplayer_peer != OfflineMultiplayerPeer" doesnt appear to be able to recognize that it is an offlinemultiplayerpeer. (even though when you print multiplayer.multiplayer_peer, it states that it is.)

![image](https://github.com/godotengine/godot/assets/24684648/5fc61674-afec-4277-be2b-d701c0d5e116)

**Comment by AThousandShips** [comment]
Nothing more except that you ignored my suggestion and used your own code, it's `is not` not `!=` 🙃

**Comment by TomSomerville** [comment]
Ahhhhhh "`is not`" isnt implimented in 4.2, however `"if not multiplayer.multiplayer_peer is OfflineMultiplayerPeer:`" works.

when the IDE highlighted the operand saying it was not an expected specifier, I switched it to != because gdscript is so similar to python.


This code block appears to be working:

```
if not multiplayer.multiplayer_peer is OfflineMultiplayerPeer:
    print(multiplayer.multiplayer_peer)
    print("Online")
elif multiplayer.multiplayer_peer is OfflineMultiplayerPeer:
    print(multiplayer.multiplayer_peer)
    print("Offline")
```
    

I'll still say, the documentation makes it sound like `get_connection_Status()` should produce a 0 if not connected to a multiplayer network.

 Maybe maintainers would be willing to implement a different ConnectionStatus code and differentiate between OfflineMultiplayer and HighLevelMultiplayer connections.

I would also recommend that get_connection_Status() implements an if null check. since setting multiplayer.multiplayer_peer is the recommended way to terminate networking, being able to handle a null state should be native to any code that checks/interacts with multiplayer.multiplayer_peer

**Comment by AThousandShips** [comment]
> Maybe maintainers would be willing to implement a different ConnectionStatus code and differentiate between OfflineMultiplayer and HighLevelMultiplayer connections.

That would break compatibility

> I would also recommend that get_connection_Status() implements an 'if null check'.

That doesn't work, the method can't be called on a null, so you need to check it, you should always do null checks anyway, that's good basic practice, *especially* since this is the recommended way to terminate networking

**Comment by TomSomerville** [comment]
> That doesn't work, the method can't be called on a null

That is a good point I dont know why I overlooked. Is it possible to set multiplayerr_peer back to OfflineMultiplayerPeer?

**Comment by AThousandShips** [comment]
Yes just use `multiplayer.multiplayer_peer = OfflineMultiplayerPeer.new()`

**Comment by TomSomerville** [comment]
Thank you, Ill Edit the initial post here on this ticket to TLDR everything we have discussed.

**Comment by AThousandShips** [comment]
Since this is intentional and there's already another issue tracking the broader aspect of the offline peer default I'll consolidate in that and close this:
* https://github.com/godotengine/godot/issues/92066
