### ISSUE TITLE
[2.1.4 Beta] UWP exporting issues

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#9375]
**Operating system or device - Godot version:**

Godot Engine 2.1.4 Beta, Windows 10

**Issue description:**

After I installed the export templates to the Godot engine, I went into the export tab to see if all the export options are clear and ready to export, but when I clicked on the "Windows Universal" Export it says that no export templates are found, please download and install the templates.

**Steps to reproduce:**

Download the Godot 2.1.4 Beta and the Export Templates and install both of them, then click on the export menu to check the Windows Universal if the export template isn't found.

**Comment by akien-mga** [comment]
Yeah I forgot to pack them :D

**Comment by akien-mga** [comment]
Could you test those templates? http://op.godotengine.org:81/downloads/2.1.4/beta/Godot_v2.1.4-beta_20170625_export_templates_winrt.zip

It's not the usual .tpz file, you should unzip it and put the 6 resulting `godot_winrt_*.zip` zips in your `%appdata%/Godot/templates` folder.

**Comment by nunodonato** [comment]
@akien-mga according to vnen those templates were defective :) can you leave an updated link here for some new ones? I'll try tomorrow :)

**Comment by akien-mga** [comment]
Uploaded new templates which should be better packed, same link: http://op.godotengine.org:81/downloads/2.1.4/beta/Godot_v2.1.4-beta_20170625_export_templates_winrt.zip

**Comment by nunodonato** [comment]
the export works, but the exported file doesnt seem to work at all. this is what I get:

![failappx](https://user-images.githubusercontent.com/1642015/27520325-656527f2-5a00-11e7-954d-f87ab2d1117f.PNG)

tried with both debugging and release.
any luck @vnen ?

**Comment by Corruptinator** [comment]
Sure!

**Comment by Corruptinator** [comment]
HMMMM.... Bugs will be bugs.

**Comment by vnen** [comment]
@nunodonato I got this error only with the ARM export. x86 and x64 worked fine.

**Comment by nunodonato** [comment]
damn that is so odd! :/

I tried running the certification program to validate for the store, this is what I get with both x86 and x64
![certfail](https://user-images.githubusercontent.com/1642015/27526728-a1fdd3aa-5a3f-11e7-95e7-ce5faf3e8478.PNG)

**Comment by vnen** [comment]
@nunodonato can you extract the .appx (it's just a zip file) and post the contents of the AppxManifest.xml file?

**Comment by nunodonato** [comment]
@vnen pasted it here: https://gist.github.com/nunodonato/f898cdab00fb2954b60f34cc593386fb

**Comment by vnen** [comment]
@nunodonato I think it's because your Publisher id does not conform with the X.500 standard. If I use the same publisher id as you, I get the same error. Try changing the "Publisher" property in the export dialog from "Nuno Donato" to "CN=Nuno Donato".

**Comment by nunodonato** [comment]
@vnen tried it, still no success :( same results

**Comment by vnen** [comment]
@nunodonato then I don't really know. If you can, send me the whole .appx and I'll see if it works for me.

**Comment by nunodonato** [comment]
will do!

a bit off-topic but... if I try to manually set the debug/release export template, the file dialog that opens seems to only accept .APPX files, while the UWP export templates come in zips. is this intended?

**Comment by vnen** [comment]
@nunodonato oops, I think in the beginning I was going to use .appx templates but changed later and forgot to change the custom templates.

**Comment by vnen** [comment]
I figured out, .appx format doesn't like spaces. I need to fix the exporter to URL-encode the file names.

**Comment by vnen** [comment]
Fixed the problems in 92ac3869d3e51d4941ea0cc88f79457c08a46da1.
