### ISSUE TITLE
[3.0] No is_colliding() in KinematicBody2D

### ISSUE THREAD

**Issue by Nermit** [godotengine/godot#9376]
Godot version 3.0

is_colliding() seems to be missing from KinematicBody2D in Godot 3.0.
It is in the docs, but does not appear to be in the actual engine.

**Comment by reduz** [comment]
It's gone, use move_and_slide(), which works for all cases.

For the old API you can do

var d = move(vec)

if (not d.empty)):
   #similar to is_colliding, you can get all collision info in d as a
dictionary

**Comment by Nermit** [comment]
Thank you!

**Comment by reduz** [comment]
Also just adding that the return value in the old move() function is now in d.remainder
here's the specific code, until documentation is rewritten:
		Dictionary d;
		d["position"] = col.collision;
		d["normal"] = col.collision;
		d["local_shape"] = col.local_shape;
		d["travel"] = col.travel;
		d["remainder"] = col.remainder;
		d["collider_id"] = col.collider;
		if (col.collider) {
			d["collider"] = ObjectDB::get_instance(col.collider);
		} else {
			d["collider"] = Variant();
		}

		d["collider_shape_index"] = col.collider_shape;
		d["collider_metadata"] = col.collider_metadata;
`
`

**Comment by rubenjavier** [comment]
@reduz @akien-mga 
the Dictionary on physics_body_2d seems to be wrong,
position and normal returns the same, I think I cant move my character manually because the dot product with the normal is not correct.

Also I used to be able to do get_collider().has_meta("c_type") (for example), how can I get that with the new collider_metadata
Thanks

**Comment by rubenjavier** [comment]
@reduz @akien-mga 
It would be great to also have on the Dictionary "collider_vel" like move function has internally

**Comment by bojidar-bg** [comment]
@rubenjavier About the metadata, use `d.collider.has_meta(..)`

**Comment by rubenjavier** [comment]
@bojidar-bg @reduz @akien-mga 
Thanks, Ive already tested on my local source a modification on the dictionary to have 
		d["normal"] = col.normal;
		d["collider_velocity"] = col.collider_vel;

and it works, the two remainig missing features for the manual movement is revert_motion() equivalent to avoid sliding on slopes, and that in OneWay collisions you can't set how far you can go inside the CollisionShape2D, and for moving platforms going upward, you always go trought the platform and fall, when the moving platform is moving downward or horizontally, you dont fall

Thanks
