### ISSUE TITLE
Nodes added in PostImport script do not appear

### ISSUE THREAD

**Issue by thmasn** [godotengine/godot#93761]
### Tested versions

v4.2.stable.official [46dc27791]

### System information

MacOs Sonoma 14.5

### Issue description

if we want to extend import behaviour with additional [import hints](https://docs.godotengine.org/en/4.1/tutorials/assets_pipeline/importing_scenes.html#import-hints), we would do so using an [post import script](https://docs.godotengine.org/en/4.2/classes/class_editorscenepostimport.html). But nodes added in a PostImport script do not appear in the scene tree.

### Steps to reproduce

p.e. lets say we want to add an AudioStreamPlayer3D to all nodes named "soundSource". we would add the following code to the import script example:
```gdscript
if node.name == "soundSource":
	print("adding node")
	var sound = AudioStreamPlayer3D.new()
	node.add_child(sound)
	print("children: " + str(node.get_child_count()) )
```
The Console output is as expected: 
```
adding node
children: 1
```
But the created node does not appear in the scene tree:
<img width="261" alt="Bildschirmfoto 2024-06-29 um 22 48 20" src="https://github.com/godotengine/godot/assets/20150151/9482ebe6-864b-4a4e-8da0-94bb630cdb02">

### Minimal reproduction project (MRP)

MRP: https://github.com/thmasn/postImportTest shows a project with the above example code.

**Comment by KoBeWi** [comment]
You need to set `owner`.

**Comment by thmasn** [comment]
oh snap! you are right, i completely missed that. when the `owner` is set to the scene root, it works:
```gdscript
	iterate(scene, scene)
...

func iterate(node:Node, owner:Node):
	if node != null:
		if node.name == "soundSource":
			var sound = AudioStreamPlayer3D.new()
			node.add_child(sound)
			sound.set_owner(owner)
		node.name = "modified__" + node.name
		for child in node.get_children():
			iterate(child, owner)
```
