### ISSUE TITLE
Invalid new child position: 2

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9377]
Godot 2.1.4 and Godot 3.0, Windows 64 bits

I get this error when opening an empty project:

```
DETECTED MONITORS: 1
ERROR: Invalid new child position: 2
   At: scene\main\node.cpp:269
unicode error: invalid skip
ERROR: Invalid new child position: 2
   At: scene\main\node.cpp:269
```

**Comment by volzhs** [comment]
I got this error too. I can confirm this.

**Comment by akien-mga** [comment]
That's a bug introduced by d4082a8d92240ab3403ac93da423e613154fc889.
