### ISSUE TITLE
Camera3D as child not following Player

### ISSUE THREAD

**Issue by IndieDev99** [godotengine/godot#93772]
### Tested versions

Godot 4.3 Beta 2. Camera3D if added as child node of Player. Its not following player.

### System information

Windows 10 Godot 4.3 Compatibility Renderer 

### Issue description

Godot 4.3 Beta 2. Camera3D if added as child node of Player. Its not following player.

### Steps to reproduce

Godot 4.3 Beta 2. Camera3D if added as child node of Player. Its not following player.

### Minimal reproduction project (MRP)

Godot 4.3 Beta 2. Camera3D if added as child node of Player. Its not following player.

**Comment by AThousandShips** [comment]
This is not the place to ask support questions, please ask in the [forums](https://forum.godotengine.org/) instead

**Comment by IndieDev99** [comment]
Sorry. It's bug report. but i'm busy. please fix it. Fix 3D Camera. Test it

**Comment by AThousandShips** [comment]
Then you need to fill in the details, you've not given any details, please follow the instructions, if you do this can be reopened, otherwise we can't

I'm sorry you're busy, but you can't ignore the details needed, so please take the time to do it properly

**Comment by IndieDev99** [comment]
Sorry. I can't I have no time. Leave it. people will report it to devs. may be
