### ISSUE TITLE
Cant hide left panel on Shader Editor

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#93784]
### Tested versions

- Reproducible in: any 4.x version.

### System information

Windows 11

### Issue description

Hide the left panel on shader code editor.

### Steps to reproduce

![Captura de tela 2024-06-30 1226382](https://github.com/godotengine/godot/assets/166422533/80e85b1f-fcfc-45ab-a6bd-b995800cea23)
 

### Minimal reproduction project (MRP)

Simple start any propject, create a gdshader and open the built-in shader editor.

**Comment by AThousandShips** [comment]
This isn't a bug, it's just a missing feature, please open a [proposal](https://github.com/godotengine/godot-proposals) instead, this is for bug tracking, important to keep apart

**Comment by almoandrioli** [comment]
Can you point me the source file that control this? I opened the "editor_native_shader_source_visualizer.cpp" and commented the lines that shows the minimap, but cant see anything that control the left panel.

**Comment by kitbdev** [comment]
- Since it exists in the script panel already, related https://github.com/godotengine/godot/issues/28607

Also, this is in `editor\plugins\shader_editor_plugin.cpp`.

**Comment by Borges-IST-2003** [comment]
Is anyone implementing this?
I want to try and do it.

**Comment by Calinou** [comment]
> Is anyone implementing this?
> I want to try and do it.

To my knowledge, nobody is currently working on implementing this feature. Feel free to give it a try :slightly_smiling_face:

**Comment by Borges-IST-2003** [comment]
I started working on this, I was able to toggle the panel, however I couldn't adjust the width of the code editor so far and the icon only appears when after I press the button.
Does anyone have some pointer as far as the width issue goes?
Thanks
[minimize_shader_panel](https://github.com/godotengine/godot/compare/master...Borges-IST-2003:godot:minimize_shader_panel)

**Comment by Calinou** [comment]
> and the icon only appears when after I press the button.

Setting the icon should be done in `_notification()` (specifically `NOTIFICATION_THEME_CHANGED`), so that it automatically updates when switching from a dark theme to a light theme or vice versa.

**Comment by kitbdev** [comment]
- duplicate of https://github.com/godotengine/godot-proposals/issues/5017

**Comment by AThousandShips** [comment]
Consolidating in the proposal
