### ISSUE TITLE
Godot not launch on my computer!

### ISSUE THREAD

**Issue by Aruvelut-123** [godotengine/godot#93781]
### Tested versions

4.1.stable.official [970459615]
4.1.4.stable.official [fe0e8e557]
4.2.dev1.official [0c2144da9]
4.2.dev2.official [da81ca62a]
4.2.dev3.official [013e8e3af]
4.2.dev4.official [549fcce5f]
4.2.dev5.official [e3e2528ba]
4.2.dev6.official [57a6813bb]
4.2.rc1.official [ad72de508]
4.2.rc2.official [1ba920fad]
4.2.stable.official [46dc27791]
4.3.beta2.official [b75f0485b]

### System information

Windows 11 26244.5000 - Godot v4.3.beta2 - OpenGL 3.3(because it cannot use my vulkan) - AMD RX 6600 - Intel i3-12100F

### Issue description

First, i'm chinese, so i hope you guys can forgive my poor English.
I tried so many versions and found that, version that above 4.2.dev6 cannot start up, only leaves version message in console and also not close, keeps running in background. And in old versions that can start up, i found that they cannot dected my graphics card's vulkan and uses opengl to renderer which cause not responding after a couple of secounds. So i hope u guys can fix it!!!
(I think it may because i'm using canary channel of windows 11 version)
Anyways, my graphics driver is up-to-date, and vulkan can dected in gpu-z which shows up vulkan 1.3. Minecraft's vulkan mod also usable too.
In task manager, it will shows suspend when i start with administrator, but other time just stay there, even no resource use increased.

### Steps to reproduce

Start Godot_v*.*_console.exe and will stuck on version info.

### Minimal reproduction project (MRP)

Nothing.

**Comment by RealMadvicius** [comment]
Hello, you could try to install the latest Vulkan SDK and runtime from their official website:

[https://vulkan.lunarg.com/sdk/home](https://vulkan.lunarg.com/sdk/home)

There are a lot of game engine and even games that wont run properly or at all if you dont have it installed. So with some luck, just installing could fix your issue.

**Comment by brcontainer** [comment]
Doesn't sound like a bug. Do the following:

1. Open CMD or another type of terminal you use and navigate to the folder where the executable is located, example: `cd C:\Programs\Godot`
1. Run the command `Godot_v4.2.2-stable_win64.exe --rendering-driver opengl3` (if using 4.2)
1. Create a project and check the Compatibility option, see image:
![image](https://github.com/godotengine/godot/assets/4368952/f8ea0765-f11a-429f-a6c8-41b5caf4f595)

That should resolve it.

---

To make things easier, you can create a shortcut `--rendering-driver opengl3`, like this:

![image](https://github.com/godotengine/godot/assets/4368952/ba48d018-07d1-47be-b49e-eaf8234a7fd4)

**Comment by Aruvelut-123** [comment]
> Hello, you could try to install the latest Vulkan SDK and runtime from their official website:
> 
> [https://vulkan.lunarg.com/sdk/home](https://vulkan.lunarg.com/sdk/home)
> 
> There are a lot of game engine and even games that wont run properly or at all if you dont have it installed. So with some luck, just installing could fix your issue.
> Also make sure your drivers are updated ( so your gpu and your iGPU aswell if you got one )

I will try that later

**Comment by Aruvelut-123** [comment]
> Doesn't sound like a bug. Do the following:
> 
> 1. Open CMD or another type of terminal you use and navigate to the folder where the executable is located, example: `cd C:\Programs\Godot`
> 1. Run the command `Godot_v4.2.2-stable_win64.exe --rendering-driver opengl3` (if using 4.2)
> 1. Create a project and check the Compatibility option, see image:
> ![image](https://github.com/godotengine/godot/assets/4368952/f8ea0765-f11a-429f-a6c8-41b5caf4f595)
> 
> That should resolve it.
> 
> More details: https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html
> ---
> 
> To make things easier, you can create a shortcut `--rendering-driver opengl3`, like this:
> 
> ![image](https://github.com/godotengine/godot/assets/4368952/ba48d018-07d1-47be-b49e-eaf8234a7fd4)
> 

yeah, I will try that later. if works then thanks

**Comment by Aruvelut-123** [comment]
> > Doesn't sound like a bug. Do the following:
> > 
> > 1. Open CMD or another type of terminal you use and navigate to the folder where the executable is located, example: `cd C:\Programs\Godot`
> > 1. Run the command `Godot_v4.2.2-stable_win64.exe --rendering-driver opengl3` (if using 4.2)
> > 1. Create a project and check the Compatibility option, see image:
> > ![image](https://github.com/godotengine/godot/assets/4368952/f8ea0765-f11a-429f-a6c8-41b5caf4f595)
> > 
> > That should resolve it.
> > 
> > More details: https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html
> > ---
> > 
> > To make things easier, you can create a shortcut `--rendering-driver opengl3`, like this:
> > 
> > ![image](https://github.com/godotengine/godot/assets/4368952/ba48d018-07d1-47be-b49e-eaf8234a7fd4)
> > 
> 
> yeah, I will try that later. if works then thanks

I tried it, still remains in background, no window shows up.

**Comment by Aruvelut-123** [comment]
> > Hello, you could try to install the latest Vulkan SDK and runtime from their official website:
> > https://vulkan.lunarg.com/sdk/home
> > There are a lot of game engine and even games that wont run properly or at all if you dont have it installed. So with some luck, just installing could fix your issue.
> > Also make sure your drivers are updated ( so your gpu and your iGPU aswell if you got one )
> 
> I will try that later

It shows this.
![Screenshot 2024-07-01 054921](https://github.com/godotengine/godot/assets/87363371/83bceb38-8055-4781-aff4-79559cbee344)
And my driver should be up-to-date, but my amd software is broken so idk right now.

**Comment by brcontainer** [comment]
Are your drivers Intel? If it is Intel then check if the drivers are up to date using the following tool:

https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html

**Comment by Aruvelut-123** [comment]
My graphics card is amd's not intel
