### ISSUE TITLE
BezierTrack is not playing without RESET animation after updating to 4.3 beta2

### ISSUE THREAD

**Issue by filkata** [godotengine/godot#93782]
### Tested versions

Occurs after converting from 4.2 stable to 4.3 beta 2

### System information

Windows 10, Godot 4.3 beta2, Nvidia 3060 12 GB

### Issue description

I noticed an animation (or rather some tracks of it) not playing in my project after updating form 4.2 stable to 4.3dev5.
The animation in question is played from a AnimationPlayerNode, has a few keyframes that modify the scale property.
I have tried my best to isolate it in a minimal example in the attached project.

Note that I tried to make a very simple test from scratch on 4.3 beta2 playing a animation that modifies the scale property from an AnimationPlayer node and all worked correctly.

### Steps to reproduce

- Open attached project with **4.2 stable** and play
- Hover over circle, notice the scaling animation and sound playing
- Open the same project with **4.3 beta2**
- Hover again and notice the scaling animation doesn't play, however the sound still plays (it is a different track but part of the same animation)

### Minimal reproduction project (MRP)

[Anim4.2Minimal.zip](https://github.com/user-attachments/files/16044984/Anim4.2Minimal.zip)

**Comment by AThousandShips** [comment]
Please try in a recent version like [beta2](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-2/)

**Comment by filkata** [comment]
The same issue is present if I try to update the attached project to 4.3 beta2. i have updated the bug description accordingly.

**Comment by TokageItLab** [comment]
I found that there is a problem with the bezier track initialization on caching. I don't know why this was working in 4.2, but the issue may have become visible in 4.3 due to changes in deterministic behavior.

I sent https://github.com/godotengine/godot/pull/93785 as a fix.
