### ISSUE TITLE
Image format conversions are rounded incorrectly

### ISSUE THREAD

**Issue by Oman395** [godotengine/godot#93797]
### Tested versions

Reproducible in 4.2.1 stable, 4.2.2 stable

### System information

Arch linux kernel 6.9.5-arch1-1, wayland, hyprland, I5-1240P w/ integrated graphics (Iris XE)

### Issue description

Images either imported without HDR or with HDR but converted to an integer format (i.e. FORMAT_R8) are innacurate, most likely because the conversion is using floor() instead of round().

### Steps to reproduce

Import an image through the editor, then call Image.convert() on it to an integer type-- the data in the integer image will be inaccurate.
```gdscript
# texture is an @export to the editor
var texture_image := texture.get_image()
var raw_data := texture_image.get_data()
for i in range(raw_data.size()):
    print(raw_data.decode_u8(i)) # In the demo project, it should be either 199,199,199,255 or 0,0,0,255, but instead is 198,198,198,255 and 0,0,0,255
```

### Minimal reproduction project (MRP)

[image_issue.zip](https://github.com/user-attachments/files/16046390/image_issue.zip)

**Comment by Mickeon** [comment]
Tested the MRP on v4.3.beta.custom_build [4ab8fb809] and judging by the above description, the issue still occurs.
![image](https://github.com/godotengine/godot/assets/66727710/d5cc864c-7d82-4ade-b5e4-5641f4fd3973)

**Comment by AThousandShips** [comment]
Sounds similar to:
* https://github.com/godotengine/godot/issues/59983

**Comment by Oman395** [comment]
> Sounds similar to:
> * https://github.com/godotengine/godot/issues/59983

Sounds like it might be the same issue-- this issue might need to be marked as duplicate, it's different behavior but the same root cause (as far as I can tell, I could be wrong)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/59983.
