### ISSUE TITLE
Bezier handles are too long on short animations

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#93807]
### Tested versions

4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4633) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Handles on Bezier keys are always 0.25 seconds long. This causes problems when working with short animations where the bezier curve will end up with an unwanted shape and you won't be able to get at the handles since they might be outside the view.

https://github.com/godotengine/godot/assets/4955051/415fa752-b176-42ed-869d-e56e1543c6e7

New key Handle length should at least be clamp to animation length, but something like half or quarter of animation length might be better. This would also be somewhat improved if the default handle type of new keys could be specified. It might make sense to have a default bezier handle type in editor settings.

### Steps to reproduce

See video above
OR
1. Create an animation and set the length to 0.2 seconds.
2. Create a bezier anaimation with a key at the beginning and end of the animation and observe the curve and handles.

### Minimal reproduction project (MRP)

NA

**Comment by TokageItLab** [comment]
Since there is already an autobegier function that depends on key spacing, it would be fine to have an option to enable it by default.

**Comment by Arnklit** [comment]
> Since there is already an auto bezier function that depends on key spacing, it would be fine to have an option to enable it by default.

How does the Auto Bezier function work? I don't know about it and can't easily find it in the docs or UI.

**Comment by TokageItLab** [comment]
By right-click:

![image](https://github.com/godotengine/godot/assets/61938263/be96cc51-7ae9-4a67-98b7-e22be5a9ee91)
