### ISSUE TITLE
Projects 4.2 error after opening 4.3 editor

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#93806]
### Tested versions

Godot 4.2.2

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

After opening the 4.3 beta2 editor, opening the 4.2.2 editor with a project developed on 4.2.2, an error appears:
![err](https://github.com/godotengine/godot/assets/130399274/b7e16f9c-6336-479d-9156-517f4de2e29c)

` File 'C:/Users/FireRun/AppData/Local/Godot/editor_doc_cache.res' can't be loaded, as it uses a format version (6) or engine version (4.3) which are not supported by your engine version (4.2).
  Failed loading resource: C:/Users/FireRun/AppData/Local/Godot/editor_doc_cache.res. Make sure resources have been imported by opening the project in the editor at least once.
  Safe save failed. This may be a permissions problem, but also may happen because you are running a paranoid antivirus. If this is the case, please switch to Windows Defender or disable the 'safe save' option in editor settings. This makes it work, but increases the risk of file corruption in a crash.`

### Steps to reproduce

1. Open the 4.3 beta 2 editor, close it.
2.Open the old project for 4.2.2 in Godot 4.2.2.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
This is expected, as the error message says, the editor doc cache generated by 4.3 is incompatible with 4.2 due to changes to the binary resource format.

The message isn't very relevant for end users though, so we could look for a way to silence it. And/or also make the `editor_doc_cache.res` minor version specific, like the editor settings.

**Comment by brcontainer** [comment]
@akien-mga It's something I always pay attention to, as I fluctuate between 4.1 and 4.3, before opening one of the editors I clear the data related to Godot in AppData. I imagine that in the future some program data could be separated by folder, based on version (only `<major>`.`<minor>`). Another more practical suggestion would be that in case of errors like those in the image, the editor itself would clear the cache data and restart. These are just suggestions.

~ Godot 4.3 is wonderful
