### ISSUE TITLE
Sprite3D Frame Coords bug

### ISSUE THREAD

**Issue by Rogemcy** [godotengine/godot#93810]
### Tested versions

4.2.2 Stable Official
4.3 beta custom build  ,  godot-master 2024_06_30 ， scons use_llvm=yes platform=windows target=editor

### System information

Win10 64bit  

### Issue description

![QQ截图20240701203443](https://github.com/godotengine/godot/assets/14737837/a8c99fe2-179c-454f-938b-ec98acd8dd85)

**I also found it in 4.2.2 Stable .**

![4 2 2 Stable](https://github.com/godotengine/godot/assets/14737837/3afc20c1-e1ea-4d49-9a7d-a1dace823934)

### Steps to reproduce
1, add a Node3D as root node;
2, add a child Sprite3D , load a texture ;
3, check the Sprite3D Animation property -> FrameCoords (should have up/down arrows like other properties for keying).
4, add a AnimationPlayer node , add a new animation ; 
5, keying for the Sprite3D's Frame Coords , check the UpdateMode property(should be Discrete by default)

## # Minimal reproduction project (MRP)

[sprite3d_frame_coords_issue.zip](https://github.com/user-attachments/files/16060603/sprite3d_frame_coords_issue.zip)

**Comment by AThousandShips** [comment]
Please add *some* details to your report, this is not enough

**Comment by Rogemcy** [comment]
> Please add _some_ details to your report, this is not enough
Thanks ！ I've uploaded a MRP
