### ISSUE TITLE
Some files get saved without change

### ISSUE THREAD

**Issue by qian2501** [godotengine/godot#93811]
### Tested versions

4.2.2

### System information

Windows10

### Issue description

I'm using p4 as my VCS, and it has a behaviour that all files that is not opened for edit will be locked, thus Godot will prompt "Unable to write to file XXX, file in use, locked or lacking permission."  Most of the time this is not an issue, but with this setup I find that some files is getting saved at some strange point:

`project.godot` is saved right after project is opened,
`*.tres` is saved everytime that any scene is saved, even though I didn't modify them.

This is not causing some actual problem, just a little annoying and can generate some .tmp file in this particular setup.

### Steps to reproduce

1. have a p4 setup, submit a project with a scene and a tres file (maybe just remove the permission from these file to simulate the situation, don't know if that works)
2. without any file opened for edit in p4, reopen Godot and ctrl+s on any scene, you should see the prompt on all the files I mentioned during the process

### Minimal reproduction project (MRP)

Not necessary, a newly created project can meet all requirements.

**Comment by AThousandShips** [comment]
I suspect this is simply an issue based on the behavior of this third-party software, and it sounds like *it* is the cause of this, and that Godot isn't really responsible for compensating for that, I don't know what Godot could do differently if *that* software is holding these files as in use

**Comment by qian2501** [comment]
It's not about the prompt thing, it's the save action seems wrong. Why write those files when they are not modified?

**Comment by AThousandShips** [comment]
Are you sure they aren't updated for other reasons? The `project.godot` file is regularly updated with data and checks, please verify that they aren't written to for a reason. I'd also say it's reasonable to just mark them as written to update most recently updated as you actively save, if you press save I'd expect the editor to actually save

**Comment by qian2501** [comment]
Yes, the version control diff gives no difference, also those files only get below 10 revisions, if they are actually modified all the time I would already have hundreds revisions on them.

And yes, this is just a minor detail thing.

**Comment by qian2501** [comment]
Well, you could say that, it's just kind of thing I would fix in my development so I filed this issue. I'm sort of perfectionist for sure. It's totally reasonable to ignore this minor detail.

**Comment by AThousandShips** [comment]
If you can work out a solution to it you're very welcome to open a PR to see what people think, but I think there are enough reasons to allow saving to be done when the user explicitly wants it to not change it

The changing of `project.godot` might be something to consider, but that might matter for sorting recent projects etc., so would need to be looked into

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/31186 and https://github.com/godotengine/godot/issues/63324, as this is due to the same cause.
