### ISSUE TITLE
RegEx captures grab too much

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9382]
**Operating system or device - Godot version:**
Windows 10
Visual Studio 2015
Godot 3.0 (current build)

**Issue description:**
RegEx of "(ab)(solve)" with the input "absolve" results in the following captures in get_group_array() returning `[absolve, solve]` instead of `[ab, solve]`.

**Steps to reproduce:**
Make a root node with a built-in script:
`extends Node`
`var regex = "(ab)(solve)"`
`var expr`
`func _ready():`
`expr = RegEx.new()`
`expr.compile(regex)`

Then connect a child TextEdit's on_text_changed event to a function on the root node:
`func on_TextEdit_text_changed(content):`
`var obj = expr.search(content)`
`if obj != null:`
`print(obj.get_group_array()`

The resulting list will have both entries with "absolve".

**Comment by leezh** [comment]
Yup. Can reproduce. Debugging right now.
