### ISSUE TITLE
GraphNode raises excessive `resized` events 

### ISSUE THREAD

**Issue by Naros** [godotengine/godot#93832]
### Tested versions

4.3.beta2

### System information

Windows 11

### Issue description

When using the `GraphEdit` scroll bars to change the scroll position within the graph canvas, all `GraphNode` instances on the canvas emit a `resized` event.  As the `GraphNode` is not being resized and only the scroll offset is being adjusted, it makes no sense why a `GraphNode` raises a `resized` event.

This only seems to apply to `GraphNode` instances within the viewport of the GraphEdit canvas.  Once the node has left the view of the canvas, it stops emitting the signal. 

In Godot 4.3, there is the new `resized_end` event; however, for code that needs to be compatible with Godot 4.2, this signal isn't possible for Godot 4.2 and the only viable option is `resized`.

### Steps to reproduce

1. Create a GraphEdit 
2. Add a GraphNode to the canvas
3. Connect a signal callback to the `resized` signal of the GraphNode
4. Move the scroll bars in the GraphEdit, the `resized` events are fired for the node instances.

### Minimal reproduction project (MRP)

N/A

**Comment by Geometror** [comment]
I will investigate this, but depending on your usecase you can look into the `resize_request` signal.

**Comment by Naros** [comment]
> I will investigate this, but depending on your usecase you can look into the `resize_request` signal.
> 
> Edit: Does this also happen when panning via the middle mouse button?

Yes it does @Geometror.

**Comment by Geometror** [comment]
Could you confirm that #93908 fixes this issue?

**Comment by Naros** [comment]
Hi Geometror, I'll continue the conversation on the PR, but there seems to be a new problem introduced w/the change.
