### ISSUE TITLE
GraphNode `resize_request` signal emitted with incorrect min sizes

### ISSUE THREAD

**Issue by Naros** [godotengine/godot#93834]
### Tested versions

4.2.1.stable & 4.2.2.stable, and 4.3.beta2

### System information

Windows 11

### Issue description

When connecting to the `GraphNode` signal `resize_request`, the signal is emitted even when the size of the `GraphNode` can no longer shrink due to content, including to the point where it can emit `(-x,-y)` if the user continues to draw to the top-left and beyond of the node's rect area.

### Steps to reproduce

1. Add a GraphEdit canvas.
2. Add a GraphNode to the `GraphEdit`, enabling resizability on the GraphNode
3. Connect a signal to the `resize_request` event to track the supplied size.
4. Drag the bottom right corner of the GraphNode toward the top-left, continuing to move the cursor even after the node stops shrinking, noticing that the signal continues to emit events, including negative X/Y values.

https://github.com/godotengine/godot/assets/3255568/fd33b3b0-291a-4ccc-83e3-fbf32d0cc016

### Minimal reproduction project (MRP)

N/A

**Comment by Geometror** [comment]
Ok, I think this is not a bug, but a design choice. `resize_request` is a request to be handled by the user, not a signal that indicates a node has been resized. Before 4.3 the use was required to fully implement resizing themselves, but that changed with 4.3 (a default callback was added). However, you can still connect your own callback to the signal and add some logic on top. In case there is demand for fully overwriting the behavior we could do that.

With the current behavior you could quickly implement something like a gesture for minimizing nodes.

**Comment by Geometror** [comment]
Can this issue be closed?

**Comment by Naros** [comment]
It can @Geometror, thanks for the explanation.
