### ISSUE TITLE
[Windows] Incorrect UI scaling based on primary monitor

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#93835]
### Tested versions

- Reproducible in 4.3-beta2, 4.2.2-stable

### System information

Windows 11, geForce 4080, Godot 4.3-beta2, Forward+

### Issue description

On Windows I have a 1440p monitor set to 100% scale and a 4k monitor set to 150% scale. Depending on which of the two is set to be my primary monitor, Godot's scaling is wildly different no matter which monitor it's on.

Example:
With the 4k monitor set to primary, this is what my 1440p screen looks like:
![image](https://github.com/godotengine/godot/assets/334808/264a6b69-1a68-4c0f-86bb-df67e5bc081c)

But with the 1440p monitor set to primary, this is what the screen looks like on the same monitor:
![image](https://github.com/godotengine/godot/assets/334808/989d9ae6-5e1c-4f34-8dad-c19f388a7725)

It doesn't matter if I drag the windows between monitors, they don't rescale to be their correct scale for the current monitor.

### Steps to reproduce

- Have two monitors of varying resolutions and scales
- Open Godot with one monitor being the Windows primary monitor
- Repeat with the other monitor being the Windows primary monitor

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for th ereport! Consolidating in https://github.com/godotengine/godot/issues/56341.
