### ISSUE TITLE
Node events such as pressed(), created using the UI do not bind the correct Nodepath selection.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#93839]
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

When creating a node event such as Button Pressed from the UI Signals Inspector, if you select Nodepath as a bind parameter, and choose from the list the nodepath to pass, even though it shows the nodename, what is passed is actually a relative path. In the case attached it is passed the "." . This cannot be used to get the actual event sender, unless one hard-codes the path.

### Steps to reproduce

See screen shot below:

1. Make a Control node scene and add Buttons nodes
2. Create an empty script in the Control node.
3. Choose a Button then go to Signals in the inspector.
4. Connect the `pressed() `signal from the UI to the default event function
5. Enable Advanced
6. Assign a Nodepath parameter and Assign it the Button from the pick list.
7. When you run it, you will get a "." as the parameter.

What should be happening is getting the actual nodepath of the button. E.g. Button2 or Panel/ButtonPanel depending which control is being clicked.

![image](https://github.com/godotengine/godot/assets/930478/2f851c26-0c9b-4f3f-be53-7214f17f9760)

### Minimal reproduction project (MRP)

See the screen shot

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/83700, which is more detailed.
