### ISSUE TITLE
 GPUParticles3D often crashes godot on Android (PowerVR gpu)

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#93848]
### Tested versions

- Reproducible in 4.2.2.stable

### System information

Android 11 - Godot V.4.2.2.stable - CPU:	Octa-core (4x2.3 GHz Cortex-A53 & 4x1.8 GHz Cortex-A53) - GPU :PowerVR GE8320

### Issue description

https://github.com/godotengine/godot/assets/100587814/4302f46e-8b97-47f8-ae5c-1c5591511e2d

### Steps to reproduce

just create a CPUParticles3D and convert to GPUParticles3D 

### Minimal reproduction project (MRP)

N/A

**Comment by shahriarlabib000** [comment]
This might be related to shader caching same as in #93406. As I exported with shader cache disabled and it didn't crash anymore

**Comment by clayjohn** [comment]
Thanks for confirming! Closing as fixed by https://github.com/godotengine/godot/pull/94835
