### ISSUE TITLE
Some weird behaviour involving CanvasLayer, Viewport and World2D

### ISSUE THREAD

**Issue by qian2501** [godotengine/godot#93864]
### Tested versions

4.2.2

### System information

Windows10

### Issue description

I'm trying out some design when I encontered this.

In Main.cs:
```
public override void _Ready()
{
	SubViewport vp1 = GetNode<SubViewport>("/root/Main/SubViewportContainer/SubViewport");
	SubViewport vp2 = GetNode<SubViewport>("/root/Main/SubViewportContainer2/SubViewport");

	vp2.World2D = vp1.World2D;
}
```

First I have this:
![2](https://github.com/godotengine/godot/assets/51772064/c4716dcd-10cf-4a99-8e87-4b230333b22e)
 The top-right one is Rect5. Then I tried parent stuff under a CanvasLayer, it becomes this:
![1](https://github.com/godotengine/godot/assets/51772064/81aac1b4-4e0f-4c6f-91eb-0363e1b865e5)
And I also tried switch visibility of the two viewport:
![3](https://github.com/godotengine/godot/assets/51772064/6c30fb97-5fd9-47ba-8773-03b9de11dd2e)
I was expecting without the top-right one (Rect5)

So the question is:
1. Why does stuff become invisible under CanvasLayer
2. Why does Rect5 keeps rendering when it's viewport should be invisible?

### Steps to reproduce

test project

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16069473/test.zip)

**Comment by AThousandShips** [comment]
This sounds like a support question, not a bug report, please explain what the bug is and what's wrong, if you need help instead please use the [forums](https://forum.godotengine.org/), post here if you have a clear bug report, not questions

**Comment by qian2501** [comment]
True, but I never used the forum or reddit before and the rules are preventing me from posting this with a new account. Here is the only place I can go.
