### ISSUE TITLE
Godot doesn't pop up with options when right clicking file system windiw

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#9386]
**Operating system or device - Godot version:**
os: win 7 ultimate 64 bit
ver: v2.1.3

**Issue description:**

I right click on the file system window and no options for it appears

**Steps to reproduce:**
right click on the file system

**Link to minimal example project:**

[ZII.zip](https://github.com/godotengine/godot/files/1100813/ZII.zip)

**Comment by homer666** [comment]
If you're talking about the folder view, that functionality isn't in 2.1.3. I'm not sure if it'll be in 2.1.4 either, but the functionality has been implemented in master and will be in 3.0. See #8503 for more info.

**Comment by akien-mga** [comment]
If someone wants to backport the various related commits of the master branch to the 2.1 branch, feel free to give it a try, but I wouldn't make it a priority (I prefer contributors spend time helping fixing bugs on the upcoming 3.0 than implementing too many enhancements in 2.1).
