### ISSUE TITLE
Log chinese error.

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#93882]
### Tested versions

v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 5GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/85f67b53-5d82-44d2-a725-f0b7dfd73c40)
when print chinese, the output window was ok, but the godot.log was error.

### Steps to reproduce

run the MRP

### Minimal reproduction project (MRP)

[logtest.zip](https://github.com/user-attachments/files/16077844/logtest.zip)

**Comment by AThousandShips** [comment]
Please try with [beta2](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-2/), you are two months behind and several improvements have been made since then

**Comment by alvinhochun** [comment]
Just an observation, the UTF-8 code units of "中文测试" is `E4 B8 AD E6 96 87 E6 B5 8B E8 AF 95`, which when misinterpreted as Latin-1 is exactly `ä¸­ææµè¯`.

**Comment by AThousandShips** [comment]
This might very easily be a windows error with notepad just reading it wrong indeed, the console log doesn't have BOM added afaik

**Comment by alvinhochun** [comment]
I just tested and I can confirm that Godot is writing the UTF-8 code units of `ä¸­æ��æµ�è¯�` to the log file itself. So it is not an issue with the text editor used but actually some erroneous encoding conversion inside Godot.
