### ISSUE TITLE
PhysicsShapeQueryParameters3D's exclude array seems to be ignored in PhysicsDirectSpaceState3D intersect_shape func.

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#93895]
### Tested versions

v4.3.beta.custom_build [e2fc6d38c]

### System information

Godot v4.3.beta (e2fc6d38c) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Explanation
I want to exclude a Node (self) from the collision test but it continues to be present. The MRP shows it all.

I have a RigidBody3D (a fish).
The fish has two CollisionShape3D nodes:
One is directly under the RigidBody3D (bumper) and is for collision with other fish.
The other is under an Area3D and is called 'ahead'. It is meant to look ahead and to the sides BUT NOT be part of the collisions with other fish.

I am using PhysicsDirectSpaceState3D and intersect_shape to get whatever 'ahead' may be overlapping. HOWEVER I do not want it to detect the fish itself, which it is doing.

I have tried various ways to exclude the RigidBody3D from the intersect process, but it just won't work.

Not sure if this is a bug or my own miscomprehension.

## Some code
With a RigidBody3D that has two CollisionShape3D nodes that overlap and this code:
```gdscript
q = PhysicsShapeQueryParameters3D.new()
q.exclude.append(self.get_rid()) # is not working later
q.collide_with_bodies = true
q.collision_mask = 2
q.shape = %senses/ahead.shape # my fish's "eyes"
q.margin = 0
```

```gdscript
# nf is an Array. It should be empty but is not. The (ahead) "eyes" see the main bumper collider.
# ss is the space state. 
nf = ss.intersect_shape(q, 2) 
```

### Steps to reproduce

Open the MRP, from Gitlab. Run the main scene. A fish will do a thing, but watch the output. The code is also commented. (issue.gd)

### Minimal reproduction project (MRP)

https://gitlab.com/dbat/fishy/-/tree/issue?ref_type=heads

**Comment by AThousandShips** [comment]
Does it work if you do `get_rid` *outside* of `_ready`?

**Comment by donn-xx** [comment]
> Does it work if you do `get_rid` _outside_ of `_ready`?
I tried that too. I did it just before using ss.intersect_shape() and it still had no effect.

**Comment by huwpascoe** [comment]
I think the exclude is a replace-don't-edit type property. Does it work if passed a complete array?
```gdscript
q.exclude = [self.get_rid()]
```

**Comment by AThousandShips** [comment]
That's indeed the case!

**Comment by donn-xx** [comment]
Well, good grief! That works. How weird though. Should this be a documentation thing or is it an Array bug?

**Comment by AThousandShips** [comment]
It's a documentation thing, it's not a bug, it's because the data is copied:
https://github.com/godotengine/godot/blob/6a13fdcae3662975c101213d47a1eb3a7db63cb3/servers/physics_server_3d.cpp#L307-L315

**Comment by donn-xx** [comment]
> I think the exclude is a replace-don't-edit type property. Does it work if passed a complete array?
Thanks! And love your apropos user icon :D

**Comment by donn-xx** [comment]
Will one of you bounce this over to the docs peeps, or must I do a thing?

**Comment by AThousandShips** [comment]
It belongs here as it's for the class reference which is in this repo
