### ISSUE TITLE
"Create New Node" dialog main scrolling area is not scrolled up to the top when summoning it

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#93899]
### Tested versions

- Not reproducible in:
  - v3.6.beta5.official [2a347ab86]
- Reproducible in: 
  - v4.0.4.stable.official [fc0b241c9]
  - v4.1.4.stable.official [fe0e8e557]
  - v4.2.2.stable.official [15073afe3]
  - v4.3.beta.custom_build [6a13fdcae]

### System information

Godot v4.3.beta (6a13fdcae) - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M3 Max - Apple M3 Max (16 Threads)

### Issue description

<img width="920" alt="Capture d’écran, le 2024-07-03 à 10 53 13" src="https://github.com/godotengine/godot/assets/270928/31abe272-ca5a-499b-8cbb-e91eba468727">

### Steps to reproduce

1. Click on the Add Node button.
2. See the offsetted scroll in the Create Node dialog.

### Minimal reproduction project (MRP)

n/a

**Comment by jsjtxietian** [comment]
Create resource suffers from the same problem.
