### ISSUE TITLE
Disabling (integrated) script editor through 'Manage Editor Features' also disables ability to open external script editor.

### ISSUE THREAD

**Issue by pusio** [godotengine/godot#93905]
### Tested versions

- Reproducible in: 4.3.beta2.mono , 4.3.beta1.mono
- Not reproducible in: 4.2.2.stable.mono

### System information

Godot v4.3.beta2.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (nvidia; 555.52.04) - 13th Gen Intel(R) Core(TM) i9-13900KF (32 Threads)

### Issue description

If you disable `Script Editor` using `Manage Editor Features` you can no longer open scripts in external editor.
`Script Editor` feature is described as `Allows to edit scripts using the integrated script editor.`. This implies to me, that disabling this feature should only remove integrated script editor, it should not have any effect on external editor.

https://github.com/godotengine/godot/assets/6397311/fd465973-a097-4e3e-8f6c-ade2eafb088e

The issue is not limited to `Open script` button in the scene tree. Double clicking a script in FileSystem tab will also do nothing.

### Steps to reproduce

1. In `Editor > Editor Settings > Text Editor > External` set `Use External Editor` to `On`.
2. In `Editor > Editor Settings > Text Editor > External` point `Exec Path` to VSCode.
3. Create any c# script.
4. Attach it to any node in scene tree.
5. You can now click `Open script` button in the scene tree in order to confirm that it open external editor. So far all works as intended.
6. In `Editor > Manage Editor Features` create a new profile. Uncheck `Main Features > Script Editor`. Click `OK`.
7. Clicking `Open script` button in the scene tree will no longer open external editor.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/59758

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
