### ISSUE TITLE
[2.1.4 Beta] OUYA console works now but the OUYA Controller is broken.

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#9390]
**Operating system or device - Godot version:**

Godot Engine 2.1.4 Beta, Windows 10, OUYA/Android(Release 4.1.2)

**Issue description:**

When I saw that a new patch #4944 by Marcelo Fernandez has been applied for the 2.1.4 Beta release of Godot, I knew that there wouldn't be any further problems for the OUYA to crash when using the controller. After uploading one of the template projects to see how good it runs the game works and the controls are operational.

Well, the controls barely works. The joysticks and the trigger buttons (L2 & R2) does not work right whatsoever. the Left joystick uses joy axis 1 and 3 while the Right joystick does not use any axis number at all. Then the (L2 & R2) buttons are not responding when I push the button in. The other buttons work but other than that, I do see progress that exporting to the console is more tollerable. However, this controller issue needs to be dealt with.

I have uploaded a new demo project "OUYA_Debug" so then everyone can clone it and open it in the Godot Engine to export and run it on the Android Console to test the controls.

**Steps to reproduce:**

This is an Android Console but there is a lengthy setup to get the game project exported to OUYA
1. On the OUYA's dev website, Cortex Devs: (https://devs.ouya.tv/developers/docs/env_setup) read the Environment Setup to allow the game console to connect to your computer with the right configuration to the adb.exe and google usb connection software. [PLEASE NOTE THAT THE INSTRUCTIONS SAYS THAT IT WORKS ON WINDOWS AND MAC. CAN'T GUARANTEE LINUX SUPPORT FOR INSTALLING OUYA. SORRY.]

2. On the Godot Docs, the documentation is explanatory if you need info or a refresh on how to export games to android: http://docs.godotengine.org/en/stable/learning/workflow/export/exporting_for_android.html

LENGTHY yes, but it does work.

**Link to minimal example project:**
https://github.com/Corruptinator/OUYA_Debug (Use this to export to OUYA)

**Comment by Corruptinator** [comment]
Interesting Update: I noticed that there is a usb port behind the OUYA console so I decided to pull out my Logitech F310 game controller usb and plugged it into the console and to my surprise, the game on the OUYA console actually responds to the USB controller. This is interesting because it makes me curious to what other controllers can work on the OUYA, but on the other hand I can easily confirm one thing:

The OUYA controller's hardware must have a different firmware than any other modern game controllers.

**Comment by kubecz3k** [comment]
Do I understand correctly that to reproduce this issue I need to run the game on OUYA console? 
Or having OUYA pad and running on PC is enough?

**Comment by Corruptinator** [comment]
Either or, I found out that the OUYA console, as mentioned earlier is that the Logitech f310 controller makes the game work on OUYA. Therefore, the OUYA controller is the culprit. The OUYA is a bluetooth controller so I don't think that would be any problem in trying to get it to work on the computer. Therefore, I think to debug the controller, it's best to use the OUYA controller on PC for economical reasons.

**Comment by Corruptinator** [comment]
But if you do happen to have an OUYA by any chance that would be fine as well. Otherwise, I'd be up for volunteering to try out any prototype builds on my OUYA console, considering that if anybody does provide a patch build so then I can test run it.

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by Corruptinator** [comment]
Has anybody figured out this bug yet by any chance?

**Comment by vnen** [comment]
It might be a problem with the [controller mapping](https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L574), it may be missing or incorrect. I notice there's no OUYA mapping for Android, but there is a Logitech F-310 mapping, which might explain why one doesn't work but the other do.

Just a guess though, as I don't have a console to test.

**Comment by Corruptinator** [comment]
Is there a way to update the controller mapping?

**Comment by Corruptinator** [comment]
Actually, I do have an OUYA and I am willing to test out any patches or updates that could get the controller to work. Otherwise, I know I am not much of an expert in source code patching but how hard would it be to implement a new mapping in the [Controller Mapping](https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L574)?

**Comment by Corruptinator** [comment]
Alright so I've mapped out the OUYA buttons and the axis joystick, the only problem is getting the GUID for the controller device. I'm starting to wonder if there is an android app that can detect and generate the GUID for the OUYA controller?

**Comment by BastiaanOlij** [comment]
@Hinsbart , would you mind giving this a quick look? 

Android I think was never updated with the latest controller handling changes so it still uses the older approach. I'm not sure how much that effects what we're experiencing here but I did notice there are some shortcuts that were made in the Android implementation.

**Comment by Corruptinator** [comment]
Alright, I've managed to fetch the GUID and Joy name from OUYA. Hopefully this works for the Controller Mapping:

`"4f5559412047616d6520436f6e74726f,OUYA Game Controller,leftx:a0,lefty:a1,dpdown:b9,rightstick:b7,rightshoulder:b5,rightx:a3,start:b16,righty:a4,dpleft:b10,lefttrigger:b12,x:b1,dpup:b8,back:b14,leftstick:b6,leftshoulder:b4,y:b2,a:b0,dpright:b11,righttrigger:b13,b:b3,"`

**Comment by Corruptinator** [comment]
I've updated the input_default.cpp for version 3.0, hopefully there isn't any problems in merging the patch for to allow the OUYA Game Controller to be responsive on Android.

**Comment by Corruptinator** [comment]
I'm having trouble compiling 2.1 to test out the patch. Might have to wait till the official build is uploaded.

**Comment by Corruptinator** [comment]
Nevermind 2.1 is now compiling, I'll test out the patch shortly.

**Comment by Hinsbart** [comment]
@Corruptinator you can also test mappings without recompiling by using `Input.add_joy_mapping(mapping_string, true)`

**Comment by Corruptinator** [comment]
-_-"

Things that I was never aware of. lol.

**Comment by Corruptinator** [comment]
Now I am stumped, the thorough testing has resulted in the OUYA controller still not working. UGH.

**Comment by Corruptinator** [comment]
input_default.cpp has now been updated to have functional OUYA Game Controllers for Android devices, including the OUYA. Closing...

**Comment by nsrosenqvist** [comment]
Hey @Corruptinator, sorry for hijacking this issue but I wanted to ask you something. I've been researching how to communicate with the OUYA Controller to set the proper player number on the LEDs. Now on Linux, no matter the number of controllers connected you have the LEDs, every controller showing that it's player one, which is incorrect. Do you have any idea how to tell the controller what player number it is? I've been trying to find docs and find information through the `bluetoothctl` command but finding nothing. Anything helps, thanks!
