### ISSUE TITLE
Lambda functions cannot assign to variables defined in the same function

### ISSUE THREAD

**Issue by ZeroLikviz** [godotengine/godot#93922]
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b], v4.2.2.stable.official [15073afe3], v4.2.stable.official [46dc27791], v4.0.stable.official [92bee43ad].
- Not reproducible in: did not found.

### System information

Xiaomi pad 5, 6/128, Android 13, Snapdragon 860, Vulkan mobile.

### Issue description

Lambda functions called and created inside a function cannot assign anything to variables that were defined inside the function. That includes not only simple types, but classes as well.
I expected it to assign values to variables inside the function, but it didn't. However, it can call functions that belong to those variables.

### Steps to reproduce

copy-paste code below:
```GDScript
var global_value : int = 0

func change_value() -> void:
	var value : int = 0
	var array1 : Array = []
	var array2 : Array = []
	var function = func() -> void:
		array1 = [0,0,0,0,0]
		array2.resize(5)
		value = 1
		global_value = 1
	function.call()
	print("array1: ", array1)
	print("array2: ", array2)
	print("value: ", value)
	print("global value: ", global_value)

func _ready() -> void:
	change_value()
```

output:
```
array1: []
array2: [<null>, <null>, <null>, <null>, <null>]
value: 0
global value: 1
```

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16093506/MRP.zip)

**Comment by dalexeev** [comment]
This is not a bug, but an limitation. See the following issues for details:

* #69014
* #85559
* #93070
* godotengine/godot-proposals#8558

In master branch we added the warning `CONFUSABLE_CAPTURE_REASSIGNMENT`:

![](https://github.com/godotengine/godot/assets/47700418/d4986dc1-e023-4b16-8dab-1da8bcbf8807)
