### ISSUE TITLE
Geometry not rendering correctly in right eye in WMR headset with Compatibility renderer

### ISSUE THREAD

**Issue by skyace65** [godotengine/godot#93921]
### Tested versions

- Reproducible in Godot 4.3 Beta  2 with the OpenXR (Only happens with Compatibility renderer)
- This does NOT Happen in Godot 4.2.

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 6950 XT (Advanced Micro Devices, Inc.; 31.0.24033.1003) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I noticed this when testing the hand tracking demo. In this specific project, when using the compatibility renderer Geometry is not rendered to the right eye of my VR headset. Mobile and Forward+ Will render geometry correctly

![HandIssue](https://github.com/godotengine/godot/assets/6080368/4e2eb3a7-bfcf-4ec6-a867-b1ced429a930)

I wanted to try recreating this with a different project so I used the XR Tools Demo. I'm getting GDScript errors when opening most of the actual scenes, So I added a cube to the title scene and the cube is rendering in the right eye, but it's behind the text which is incorrect. I'm guessing there's something unique about how that scene is setup causing this to behave differently.

![Issue Part 2](https://github.com/godotengine/godot/assets/6080368/dd09879f-3421-49a4-8cc6-bac09904de7b)

I also tested this scene in Godot 4.2 and the issue did not happen.

I'm using a Samsung Odyssey+ (WMR) and Steam VR. If I change to the mobile renderer everything is fine in the right eye. My AMD Graphics Driver is on the latest available version (24.5.1). Other people who tested the demo have not reported this issue, based on that I'm assuming this is either specific to WMR headsets or AMD Graphics Cards in some way.

### Steps to reproduce

Open Any OpenXR project (Using the compatibility renderer) with a WMR headset and or AMD Graphics card and look at Geometry

### Minimal reproduction project (MRP)

The OpenXR hand tracking demo from this PR: https://github.com/godotengine/godot-demo-projects/pull/973

**Comment by BastiaanOlij** [comment]
I wonder if this is in any way related to our Reverse-Z changes. That when clearing the Z buffer it's only writing the correct depth in the left eye layer and zeroing it out in the right eye layer. The text renders because it might be ignoring depth.

If you can do a frame capture in renderdoc you could have a look at the content of the depth buffer right after its cleared. I suspect that the left image will show white (or red) and the right image black.

**Comment by BastiaanOlij** [comment]
Ok, just continueing from the test I posted in https://github.com/godotengine/godot-demo-projects/pull/973

> I took your demo project and changed it to the compatability renderer since that's the one with issues. Still having the problem
> 
![image](https://github.com/godotengine/godot/assets/1945449/14f3dee7-b65c-4cfe-a041-7171ec8ff304)

Ok that proves this is an issue unrelated to OpenXR and purely an issue in stereo rendering on this hardware.

It's also clear in this screen that it IS rendering seeing we are seeing the background. There seems to be an issue with how it is interpreting the depth buffer.

If you have access to renderdoc, it would be good to see the status of the depth buffer on both layers (each render target will have a layer for each eye). Also here we would be able to see whether the geometry renders and the sky is drawn over it, or if the geometry doesn't render at all. 
 
> Also I'm assuming this isn't supposed to output to the headset, because it's not
This is correct, that is why I wanted you to test the test project. This is a project that purely does stereo rendering in engine and rules out any external influences like OpenXR, SteamVR, or the headset you are using. 

For others who wish to test, I'll add the test project here as well.
[teststereovrs.zip](https://github.com/user-attachments/files/16123024/teststereovrs.zip)

**Comment by dsnopek** [comment]
> Otherwise, we issue one draw call for each object and we only draw to the left eye.

I think it's supposed to only be a single draw call, since we are rendering both eyes at the same time via multiview: the render target is a texture array, and we render the left eye to index 0 and the right eye to index 1. In RenderDoc, do you see it as a texture array? If not, then perhaps that's a clue as to the cause?

**Comment by BastiaanOlij** [comment]
@clayjohn that documentation refers to the old stereo support in OpenGL way before Multiview was even a thing
