### ISSUE TITLE
[4.2] Unsaved BlendSpace2D crashes editor when changing to discrete mode

### ISSUE THREAD

**Issue by terminalmax** [godotengine/godot#93924]
### Tested versions

- Godot Engine v4.2.2.stable.official.15073afe3
- Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1070

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

Editor crashes when a new AnimationTree is added to the scene and the blend mode is changed to discrete. This happens if the scene tree is not saved after adding the AnimationTree (having a different scene with an animation tree working may alter behavior). On saving the scene tree or adding a point on the blend space, the issue resolves itself, for that particular scene.
![crash](https://github.com/godotengine/godot/assets/68583762/a7bb97f8-e672-4726-a4b0-7900bb256916)

### Steps to reproduce

1. Create Node2D root node (you _may_ save the scene).
2. Create AnimationTree child node (do _**not**_ save the scene)
3. Create new BlendSpace2D in the AnimationTree.
4. Change the blend mode to discrete.

Note: Saving at different stages alters behavior. If a different scene has AnimationTree working, then this might not reproduce the crash. 

### Minimal reproduction project (MRP)

N/A (Project Independent)

**Comment by TokageItLab** [comment]
Fixed by https://github.com/godotengine/godot/pull/92636 in 4.3

**Comment by akien-mga** [comment]
Fixed for 4.2.3 by #93938 (already fixed in 4.3).
