### ISSUE TITLE
All Godot windows completely blank after reopening laptop lid.

### ISSUE THREAD

**Issue by maakuarc** [godotengine/godot#93923]
### Tested versions

- Reproducible in v4.2.2.stable.arch_linux

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 - Wayland - GLES3 (Compatibility) - zink Vulkan 1.3(NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA_PROPRIETARY)) () - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

Only effects Godot windows. Has happened to the Project Manager, Editor, and running projects. 

When a game is running the log file ends with-
```
ERROR: 1 RID allocations of type 'N5GLES37TextureE' were leaked at exit.
USER ERROR: Texture with GL ID of 13: leaked 4 bytes.
   at: ~Utilities (drivers/gles3/storage/utilities.cpp:79)
```
-but I'm uncertain if it's related.

If there is any better information I could give, please let me know.

### Steps to reproduce

- Open Godot
- Close laptop lid
- Reopen laptop
- Blank windows

### Minimal reproduction project (MRP)

Doesn't even need a project, it happens outside of them as well.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52738. This is a NVIDIA issue we can't fix on our end without [large sweeping changes](https://github.com/godotengine/godot-proposals/issues/6423). All other applications using Vulkan on Linux run into the same issue unless they can restart their rendering context entirely in a clean manner (preferably without losing any data).

You may try following the advice on this page at your own risk: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend
