### ISSUE TITLE
[3.0] with the changes to physics_body_2d, I see no way to get the collision on a KinematicBody2D

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9392]
**Operating system or device - Godot version:**
Linux Ubuntu 64bit commit 8caa21a4a939dbb8d7b8a7fa14ca8b5a32fc1be9

**Issue description:**
since the dissapearance of "is_colliding" and the modifications on physics_body_2d.h and .cpp, I can make a KinematicBody2D work correctly, since all the new modified functions require the ID of the collision to work, like get_collision_normal() or get_collider()
#before:
```
if (is_colliding()):
		var n = get_collision_normal()
```
#now:
```
#not sure if the following line works
if( get_collision_count() != 0 || get_collision_count() != null ):
		var n = get_collision_normal( THE_COLLISION_ID )
```

I have not been able to find away to get the collision or if there is a collision after a KinematicBody2D "move()", this feels like a chicken and egg situation

**Comment by reduz** [comment]
if you want to still use the old manual system, you can give a check to #9376. It's still there but changed syntax a bit.

In the new system,the body is sled a few times automatically, and you can find the collision info for each slide with get_collision* API. They are in order from first to last slides.
