### ISSUE TITLE
Wrong node in inspector after drag&drop in tree and a delay

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#93935]
### Tested versions

- Reproducible in 4.3 master (https://github.com/godotengine/godot/commit/e6448ca0aa050b71cb40d9658b7233b8ec7f7382)

### System information

Test Godot v4.3.beta.mono (6a13fdcae) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

When drag&dropping a node over a container, sometimes, the inspected node is still the container in the inspector.

I think it's a follow up of #91254

https://github.com/godotengine/godot/assets/81109165/47269015-1171-4406-90b8-e54d12b4525c

### Steps to reproduce

- Drag a node over the bottom of a container
- Wait for the highlight to appear on the destination node
- Drop the node
- In the inspector, the combo with the name correspond to the dragged node but the properties are the properties  the container node. I think it should display the properties if the dragged node (the select node)

### Minimal reproduction project (MRP)

[test-godot-crash-drag-drop.zip](https://github.com/user-attachments/files/16099134/test-godot-crash-drag-drop.zip)

**Comment by akien-mga** [comment]
CC @KoBeWi @AeioMuch @ajreckof
