### ISSUE TITLE
Error when opening 4.3 game in --headless mode

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#93946]
### Tested versions

4.3.beta2

### System information

Windows 11 - Godot 4.3.beta2 - Forward+

### Issue description

When you play a game in --headless mode, it throws an error about the mouse

### Steps to reproduce

Play the game and observe the error

### Minimal reproduction project (MRP)

[minimal-project.zip](https://github.com/user-attachments/files/16101553/minimal-project.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been solved, see:
* https://github.com/godotengine/godot/issues/93461

Will be in beta3

**Comment by agrimminck** [comment]
Thank you! I tried to search for it but couldn't find it, sorry!
