### ISSUE TITLE
macOS: Dragging editor between screens sometimes causes the window to move erratically

### ISSUE THREAD

**Issue by Grublady** [godotengine/godot#93955]
### Tested versions

Latest 4.3 master branch

### System information

Godot v4.3.beta (fe11def75) - macOS 15.0.0 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Sometimes while dragging the editor across displays, the window rapidly switches between two locations as it approaches the boundary.
After a while—or if the editor is resized to be fairly small—this erratic behavior does not occur, and the window simply switches screens based on its midpoint.

https://github.com/godotengine/godot/assets/29121925/94064812-484e-4657-837e-09192942819c

(This recording shows only the left screen; when the editor window disappears, it is on the second screen)

### Steps to reproduce

- Ensure `interface/editor/expand_to_title` is disabled
- Launch/relaunch the Godot editor
- Move the editor window between displays by dragging the title bar

### Minimal reproduction project (MRP)

N/A

**Comment by lostminds** [comment]
I'm not seeing this behavior on Godot 4.3b3 my M2 mac on macOS 14.5, could this be an issue with the pre-release version of macOS 15 you seem to be using?

I have however seen a related issue where if I start a window on my secondary monitor and move it over to the primary monitor window it will sometimes resize unexpectedly, but only once after the move is done. The issue does not occur if I move the window the other way and start it on the main monitor, and it only happens once. So it might be there is some underlying issue with window sizing when switching monitors that has just become more aggressive in macOS 15 compared of 14.5.

**Comment by Grublady** [comment]
Closing as fixed by #99642
