### ISSUE TITLE
get_argument_count() on Callable class reporting nested lamda calls as additional arguments.

### ISSUE THREAD

**Issue by DraconicMentalist** [godotengine/godot#93952]
### Tested versions

- Reproducible in: 4.3 beta 2, not sure how to test the earlier development versions after this method was introduced.

### System information

Arch Linux

### Issue description

As stated above, get_argument_count() reports the incorrect number of arguments when calling a lamda within another lamda. The issue doesn't seem to occur when calling a lamda within a normal function, or vise-versa. The number of extra arguments reported seems to correspond to the number of unique lamda functions called to.

```gdscript
var test_lamda_1 = func():
	test_call()
		
var test_lamda_2 = func():
	test_call_with_param("Called!")

var test_lamda_3 = func():
	test_lamda_1.call()
	
var test_lamda_4 = func():
	test_lamda_1.call()
	test_lamda_1.call()
	test_lamda_2.call()
```

In this example code, test_lamda_3 returns 1, and test_lamda_4 returns 2.

### Steps to reproduce

- Create 2 lamdas functions and assign each to variables.
- Call the second one from the first one.
- Call get_argument_count on the second one.
- get_argument_count will return the incorrect number of arguments.

### Minimal reproduction project (MRP)

[callable-argument-count-bug.zip](https://github.com/user-attachments/files/16102285/callable-argument-count-bug.zip)

**Comment by dalexeev** [comment]
Should be `function->get_argument_count() - captures_amount`. CC @AThousandShips

https://github.com/godotengine/godot/blob/4d984b63697d840f2c823608d2c46740fb44651a/modules/gdscript/gdscript_lambda_callable.cpp#L81-L88

https://github.com/godotengine/godot/blob/4d984b63697d840f2c823608d2c46740fb44651a/modules/gdscript/gdscript_lambda_callable.cpp#L201-L208

**Comment by AThousandShips** [comment]
Will write up a fix tomorrow
