### ISSUE TITLE
VehicleBody collision issues (2.1.4b)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9395]
**Ubuntu 17.04 - Godot version: 2.1.4 beta**

**Issue description:**
In Truck Town demo, sometimes collisions seem to fail against the terrain.

**Steps to reproduce:**
Run Truck Town demo and drive around until collisions fail and truck falls into oblivion.

**Comment by Zireael07** [comment]
Leaving this for reference (I'm using physics copied from the truck town demo):
https://gfycat.com/AltruisticAcrobaticAlbino

Falling through seems to be related to angles (see how the 2nd AI falls but the 1st one stays where it should)

**Comment by eon-s** [comment]
May be affecting just vehicles, tried with a couple of dozens of things with spheres and cube shapes and everything worked ok.

@Zireael07 can you test with regular objects on that scene too?

**Comment by Zireael07** [comment]
@eon-s: I suck at setting up rigidbodies unfortunately but I could give it a try sometime today or tomorrow.

**Comment by eon-s** [comment]
After throwing cars against a lot of colliders I think that VehicleBody is the problem.

**Comment by akien-mga** [comment]
For the reference, likely related to #8999 too (to confirm, you could try reverting it locally and check if it fixes the issues).

**Comment by eon-s** [comment]
This seems to be fixed by #9518.

@Zireael07 if you can, check your projects to see if there is another issue on vehicles or collisions.
