### ISSUE TITLE
VisibilityEnabler2d breaks when _process() is present with print statement

### ISSUE THREAD

**Issue by LeeWannacott** [godotengine/godot#93961]
### Tested versions

- Tested 4.3 beta 2

### System information

Godot v4.3.beta2 - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 15.0.7, DRM 3.57, 6.8.0-76060800daily20240311-generic) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

When you have a `_process()` present on nodes being effected by visibilityEnabler2D. If you go in and out of that area with your character at some point it will break and continue to print not only what is in `process()` but what also what is in the `_physics_process()`. 

### Steps to reproduce

Just move  (WASD) the colorRect on and off screen (which has a VisibleOnScreenEnabler2d on it) and at some point (usually 1-3 times) it'll break and start printing what is in process() and also prints what is in the physics_process() . If you comment out process and just have physics_process() it will not break.

https://github.com/godotengine/godot/assets/49783296/f1a54691-ec52-4472-997a-168fd493f6a4

Breaks (continues to print when off screen):
![image](https://github.com/godotengine/godot/assets/49783296/e6e6c356-34ac-4615-92eb-9c3cfe04d279)

Does not break (stops printing):
![image](https://github.com/godotengine/godot/assets/49783296/50e697b3-aae4-478e-bcb2-fecf001f0f55)

### Minimal reproduction project (MRP)

[enabler2d_test.zip](https://github.com/user-attachments/files/16104674/enabler2d_test.zip)

**Comment by LeeWannacott** [comment]
Maybe its only with print statements in the process()? in which case an exported game would be stripped of that? so its not an issue :thinking: ???

**Comment by theraot** [comment]
It is too many prints. See https://github.com/godotengine/godot/issues/4192

By the way, by default - on PC - the print statements would go to log files, so they are not necesarily stripped on release. And you might want more helpful logs.

**Comment by AThousandShips** [comment]
Currently, or until further testing is done, I'm agreeing with the points in the comment above with too much printing, including performance with printing, but will re-add bug to this issue if it is confirmed to be a bug

**Comment by theraot** [comment]
I see, the editor keeps printing. Godot 4 does that... You can increase `run/output/max_lines` in Editor Settings so it can room to print everything at once. Then you should see it stop.

---

By the way, since the goal seems to be to check if `_process` is running, I tried modifying the code like this:

```
func _process(_delta: float) -> void:
	get_window().title = str(Engine.get_process_frames())
```

This updates the title of the window instead of printing. And you will see it stop updating when the `VisibleOnScreenEnabler2D` goes offscreen.

This works as expected on my end.

**Comment by LeeWannacott** [comment]
@theraot Looks you are right increasing `run/output/max_lines` shows its not a bug; thanks for your help. I shall close the issue...
