### ISSUE TITLE
Rider shows fake errors after pressing "Run Project"

### ISSUE THREAD

**Issue by SirRobbe** [godotengine/godot#93969]
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Linux, Godot v4.2.2.stable.mono - Ubuntu Core 22 - X11 - Vulkan (Forward+) - (software emulation on CPU) llvmpipe (LLVM 15.0.7, 256 bits) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

While working on my project each time run the project in the editor, after the editor builds the dotnet project Rider reports many (up to 1000, probably depends on the size of the project) errors in the solution. These errors however are not real errors. Simply invalidating the cache or rebuilding the project in Rider removes all of them. However, it is still cumbersome to do this each time after running the project. It only did occur in a project that has scripts that use the `[Export]` attribute.

### Steps to reproduce

- Create a new project
- Create a new scene
- Attach appended script to the scene root that has a property with the `[Export]` attribute
- Open the solution in Rider
- Run project with the created scene as start up scene
- Switch to rider
- Solution should now contain many reported errors
- Rebuild solution
- No errors should be left

### Minimal reproduction project (MRP)

[godot-bug-test.zip](https://github.com/user-attachments/files/16108618/godot-bug-test.zip)

**Comment by akien-mga** [comment]
You should report this to Jetbrains, as we can't provide support for a thirdparty integration we're not involved in.

If it turns out to be a Godot bug, the Jetbrains developers can open a bug report here with details about what they're doing and why Godot is causing an issue for them.
