### ISSUE TITLE
Improve internationalization support for projects via gettext

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#9398]
Currently, the Godot editor uses `.po` files (gettext), and projects use [CSV](https://en.wikipedia.org/wiki/Comma-separated_values).

CSV has a few downsides compared to `.po` or other more common formats for localization:

- it is not very VCS-friendly (having a large amount of different languages in a single file makes it worse),
- it is not compatible with most localization platforms (like [Transifex](https://www.transifex.com/) or [Weblate](https://weblate.org/))

Using a more advanced format could also bring support for advanced i18n features like plurals.

**Comment by Geequlim** [comment]
There is a problem with gettext translations for polysemy words.

For example the `Project Manager` can mean a person @akien-mga  or the tool to management the projects. But it is not allow to translate as diffrent text with gettext. Many of the languages can't translate them to the same text.

So I think it is required to keep the CSV support.

**Comment by akien-mga** [comment]
Well CSV should be kept, but PO should also be supported.

**Comment by Calinou** [comment]
> For example the Project Manager can mean a person @akien-mga or the tool to management the projects. But it is not allow to translate as diffrent text with gettext. Many of the languages can't translate them to the same text.

gettext covers this since it lets you define contexts for each string (which can also be displayed in translation platforms to ease the work of translators).

**Comment by akien-mga** [comment]
Well well well... Turns out we already support PO files for translations, even in Godot 2 :)
See e.g. https://github.com/KOBUGE-Games/minilens/commit/da068b27f1ad55adf72fa10ac1a8e10c8d918ce8

UX could be improved, but that's beyond the scope of this issue.

**Comment by r3d9u11** [comment]
@akien-mga Hi. Is it possible to use .po files for project translation (Godot 3.0.5)?

**Comment by mysticfall** [comment]
I wonder if we can support Gettext specific features like plural forms, for example:
* https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms

**Comment by akien-mga** [comment]
> Is it possible to use .po files for project translation (Godot 3.0.5)?

Yes, just load a .po file in Project Settings > Localization.

> I wonder if we can support Gettext specific features like plural forms

It should be possible, though I doubt the current implementation we have supports it (`core/io/translation_loader_po.cpp`).

**Comment by r3d9u11** [comment]
@akien-mga it [doesn't work](https://github.com/godotengine/godot/issues/20375) for me, I don't understand why :(
I have es_ES.po file:
```
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: YEAR-MO-DA HO:MI+ZONE\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: \n"
"Plural-Forms: nplurals=1; plural=0;\n"

msgid "New Game"
msgstr "Juego Nuevo"
```
But nothing happens after locale changed. I have broken file format?

**Comment by Calinou** [comment]
If anyone stumbles upon this issue via a Web search, note that the process of localization using gettext is now documented here: https://docs.godotengine.org/en/latest/tutorials/i18n/localization_using_gettext.html
