### ISSUE TITLE
Type hinting Array values requires exact match, instead of default inheritance behavior

### ISSUE THREAD

**Issue by InspectorCaracal** [godotengine/godot#93984]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5], 4.3beta2 (current commit?)

### System information

Debian 12

### Issue description

Type hinting a parameter as `Array[Class]` results in IDE errors when passing in an `Array[SubClass]`, while type hinting a parameter as `Class` allows passing in a `SubClass`.

Possibly related: #73005

### Steps to reproduce

Create the following classes:
```gdscript
class Vehicle extends Node

var year : int = 1992
```
```gdscript
class Car extends Vehicle
```

This script works:
```gdscript
extends Node2D

@export var car:Car

func _ready()
    test_automobile(car)

func test_automobile(vehicle:Vehicle):
    print(vehicle.year)
```

This script raises type errors:
```gdscript
extends Node2D

@export var cars:Array[Car]

func _ready()
    test_automobile(cars)

func test_automobile(vehicles:Array[Vehicle]):
    for vehicle in vehicles:
        print(vehicle.year)
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot-proposals/discussions/7364

**Comment by InspectorCaracal** [comment]
Aha, I searched a whole bunch but didn't think to look in discussions. Since this is already covered I'll close the issue.
