### ISSUE TITLE
GDScript bug (please report): Invalid value of lambda capture at index 0

### ISSUE THREAD

**Issue by mizuto** [godotengine/godot#93990]
### Tested versions

4.2.1

### System information

Windows 10

### Issue description

I have several lambdas that produces the following error during runtime:
`GDScript bug (please report): Invalid value of lambda capture at index`

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/user-attachments/files/16117127/Bug.zip)

Note: I was able to fix this by removing the "**[String]** " in the method signature.

**Comment by AThousandShips** [comment]
Can you please try with 4.2.2 to make sure this hasn't already been fixed

**Comment by dalexeev** [comment]
> ```gdscript
>  buff_func.callv([null, -1, null])
> ```

You are calling a one argument function with three arguments. I couldn't reproduce the bug with the provided snippet, please add more details.

```gdscript
func create_function(tokens: Array[String]):
    var buff_func = func do_stuff(entity: Object) -> void:
        prints(tokens, entity)
    buff_func.callv([null, -1, null])

func _ready() -> void:
    create_function([""])
```

By the way, the error is not displayed with `callv`, only with `call` (i.e. `buff_func.call(null, -1, null)`):
![](https://github.com/godotengine/godot/assets/47700418/985e38d0-49fa-491d-ae8a-190231263ebc)

**Comment by mizuto** [comment]
[Bug.zip](https://github.com/user-attachments/files/16117121/Bug.zip)
Sorry about that. I went and created a new project with this bug. The project produces the bug locally

![02975b87d29a7c20cef101b1f7008503](https://github.com/godotengine/godot/assets/1930459/54075ba8-445b-4164-be70-1f53f3855bfb)

**Comment by mizuto** [comment]
Tried it with 4.2.2, same result.
