### ISSUE TITLE
Updating from 4.2 to 4.3 overwrites Settings

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#94011]
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Newest macOS

### Issue description

I was using 4.2 until recently, and switched to v4.3.beta2.official [b75f0485b] a few weeks ago. Usually, such upgrades would carry over all the settings from old Godot builds, but this time at least one setting was overwritten with new build (I have the "Text Editor / Completion / Add Type hints" set to "off", but the new build set it to "on").

There might be other settings that got overwritten (this one was easy to spot).

**Edit**: Another thing that got overwritten is at least one of the custom theme colors, for example now I noticed orange color is used in some places.

### Steps to reproduce

Download the newest build, overwrite the old build in the Apps directory? Not sure. This never happened when I was upgrading from 4.1 to later builds.

### Minimal reproduction project (MRP)

v4.3.beta2.official [b75f0485b]

**Comment by Calinou** [comment]
> but this time at least one setting was overwritten with new build (I have the "Text Editor / Completion / Add Type hints" set to "off", but the new build set it to "on").

This is because default values are not saved to editor settings. Since the default was previously `false` and it became `true` in https://github.com/godotengine/godot/pull/88026, it became `true` in your installation because your `editor_settings-4.tres` file previously did not have a setting stored for the **Add Type Hints** editor setting (unless it was `true`).

**Comment by inhalt120g** [comment]
I understand the explanation and am happy it's not supposed to happen in the future, it's a nuisance. Thank you for linking the relevant issues and providing the info!
