### ISSUE TITLE
Ctrl-space shortcut not working when in script editor

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#94017]
### Tested versions

Godot 4.3 master

### System information

Godot v4.3.beta (b97110cd3) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

I added a shortcut for toggling the bottom panel to "Ctrl-Space" which is the default one in Unreal.
When in the Script Editor, the shortcut does not work at all.
When using the default shortcut (Ctrl-J), it works.

![image](https://github.com/godotengine/godot/assets/81109165/ee494b1d-0a1d-4891-bb7e-80e66cc7237b)

### Steps to reproduce

- Customize the shortcut for "Toggle Last Opened Bottom Panel" the "Ctrl-Space".
- Open an GDScript in Script Editor
- Try toggling the Bottom panel with Ctrl-Space
- Nothing happens

### Minimal reproduction project (MRP)

Any project will do.

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot/issues/93631

**Comment by Hilderin** [comment]
My bad, Ctrl-Space is used for Completion Query. Changing that shortcut make it works.

**Comment by Hilderin** [comment]
I'm closing this issue.

**Comment by kitbdev** [comment]
I noticed that when toggle bottom panel is set to ctrl space and completion query is unbound, a space still gets inserted into the script editor.

**Comment by Hilderin** [comment]
I just created a issue and a PR for that: #94031
