### ISSUE TITLE
Animation key button in property inspector fails to register click sometimes

### ISSUE THREAD

**Issue by mihe** [godotengine/godot#94030]
### Tested versions

Reproducible in 4.3.beta [b97110cd307e4d78e20bfafe5de6c082194b2cd6]

### System information

Windows 11 (10.0.22631)

### Issue description

The symptoms of this issue are fairly straight-forward. Sometimes when you click the key button in the property inspector (after having selected an `AnimationPlayer` node with at least one animation) you'll find that the click doesn't always register.

I have yet to pin down exactly when or why it happens, but at least one consistent repro is if you let the tooltip of the property itself show up before you click, in which case the click will only dismiss the tooltip but not actually register as a click of the key button, thereby failing to add a new keyframe.

You should be able to see that in this video:

https://github.com/godotengine/godot/assets/4884246/4b1dd288-5e5c-4dfd-a8e5-8f33f505dce0

There may very well be other cases where this happens as well, which might speak to a bigger problem with the button in general.

### Steps to reproduce

1. Open the MRP
2. Select the `AnimationPlayer` node
3. Select the `Sprite` node
4. Hover over the key button for the `position` property
5. Wait for the tooltip to show up
6. Click the button
7. Note how no keyframe is added in the Animation dock

### Minimal reproduction project (MRP)

[key-button-fails-to-register.zip](https://github.com/user-attachments/files/16119562/key-button-fails-to-register.zip)

**Comment by matheusmdx** [comment]
Related issue: #92382
