### ISSUE TITLE
First time of Toggle Last Opened Bottom Panel opens Output panel

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#94038]
### Tested versions

Godot v4.3.beta.mono (f20ee48fc)

### System information

Godot v4.3.beta.mono (f20ee48fc) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Issue description

When the editor starts and the FileSystem is docked at the bottom, when I press the shortcut "Toggle Last Opened Bottom Panel", the Output panel is displayed. It should close the FileSystem.

https://github.com/godotengine/godot/assets/81109165/f82928da-efd2-4a68-9194-66484f030592

### Steps to reproduce

- Open the Editor
- Put the FileSystem at the bottom
- Open the FileSystem
- Press the "Toggle Last Opened Bottom Panel" shortcut to close the bottom panel
- Restart the editor
- Press the "Toggle Last Opened Bottom Panel" shortcut

### Minimal reproduction project (MRP)

Any project.

**Comment by Calinou** [comment]
I can confirm this on 4.3.beta 92c8e87cd.
