### ISSUE TITLE
Rename ItemList.select(idx) to ItemList.set_selected(idx) 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9403]
Since almost everything is using set maybe we can also replace ItemList.select or add an additional ItemList.set_selected(idx)

**Comment by bojidar-bg** [comment]
I agree. Also, Tree should get this.

**Comment by AlexHolly** [comment]
Should ItemList.unselect also be renamed to ItemList.set_unselected(idx)?

**Comment by bojidar-bg** [comment]
`set_unselected` is not well-sounding IMO (plus there is no `get_unselected`, is there?). I guess we might keep `unselect()`/`deselect()`, but we should also allow them to be done via `set_selected(null)`, if possible.

**Comment by AlexHolly** [comment]
Maybe rename at least deselect to unselect or unselect to deselect?

**Comment by reduz** [comment]
I think the way it is makes more sense, it's an action that by default affects all items (selects one and deselects all others). set_select would be misleading and make you think it only affects one.

**Comment by AlexHolly** [comment]
I see two reasons to add `set_selected`

1. If you use `get_selected` you expect a `set_selected` to be there.
2. If you want to set something(in this case selected) most of the time you write set and look for auto completion and this will not show `select`.

Another solution could be to add a second function `set_selected` and keep `select`

**Comment by reduz** [comment]
1. There is no get_selected() so not expecting a set_selected
2. I understand, but itemlist list logic does not even work by default in a way where you would expect to select individual items, you have to enable this.

I suggest just leaving ItemList as is, as I don't believe it needs to be fixed

**Comment by akien-mga** [comment]
Keeping the API as is was also the general consensus at yesterday's meeting, so closing.
