### ISSUE TITLE
Can''t import png files

### ISSUE THREAD

**Issue by MICHIFUBRUNO** [godotengine/godot#94051]
### Tested versions

4.2.2 and 4.2.1

### System information

Windows 11

### Issue description

When i try to import a png file, it loads a 

### Steps to reproduce

Importing a png file

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16120661/MRP.zip)

**Comment by daveTheOldCoder** [comment]
"When i try to import a png file, it loads a" ?

**Comment by AThousandShips** [comment]
Please add more details, you should explain what isn't working and what happens instead, and what you expect to happen instead

**Comment by bruvzg** [comment]
PNG is too large, maximum texture size is `16384x16384` and your PNG is `16599x4114`.

**Comment by AThousandShips** [comment]
Consolidating in:
* https://github.com/godotengine/godot/issues/93018

As this is the same issue, see there for more

**Comment by MICHIFUBRUNO** [comment]
Ok! Thanks!
