### ISSUE TITLE
Turning a tile into 1-side collision gives unexpected result (2.1.4b)

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9406]
**Godot version: 2.1.4 beta**

**Issue description:**
The one side tiles do not work as expected, for example [0,1] can allow to step on the lower part of the collision shape.

![onesidetile](https://user-images.githubusercontent.com/10215987/27563118-44e329e2-5aa6-11e7-8b64-b79c7a221fd7.gif)

**Steps to reproduce:**
Turn into one side (like [0,1]) an existing tile of a tileset and try to land in the middle of it.
Changing to different depth values does not alter anything on this behaviour.

**Link to minimal example project:**
Platformer demo can be used for this.

**Comment by akien-mga** [comment]
CC @RandomShaper

**Comment by eon-s** [comment]
Just checked a bit more, seems that the player script is the problem, the ray shape to be more precise.

**Comment by RandomShaper** [comment]
Will check ASAP. Please keep reporting your findings.

**Comment by eon-s** [comment]
The simple Kinematic character demo works fine.
Tested casting some rays and looks like rays ignore the 1 side settings of rectangle shape colliders, but the issue does not affect the collision polygons (that may be why one side platforms on the platformer demo works fine).

**Comment by RandomShaper** [comment]
Will you check if that's then an issue with RayCast by setting up a little
test with RigidBodies, for instance?

If it showed the same behavior, we'd know this is not related to the new
TileMap OWC functionality and a new issue about RayCasts could be opened.

**Comment by eon-s** [comment]
@RandomShaper normal rigidbodies and kinematics controlled by move are ok so it looks like is not the TileMap, and maybe is an old issue with rays.

I'll close this and will do more tests tomorrow.

**Comment by RandomShaper** [comment]
@eon-s, thank you for your updates on this! You're being really helpful.
