### ISSUE TITLE
`Callable.get_method()` does not fully work on lambda functions if they access member variables

### ISSUE THREAD

**Issue by elmarhoppieland** [godotengine/godot#94074]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (Intel Corporation; 27.20.100.9415) - Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 Threads)

### Issue description

```gdscript
extends Node

var member := 3

func _ready() -> void:
    var callable1 := func test() -> int:
        return member
    var callable2 := func test() -> int:
        return 0

    print(callable1.get_method()) # error, prints nothing
    print(callable2.get_method()) # no error, prints 'test'
```
For lambda functions that access variables from the object that the function was defined on, `Callable.get_method()` does not work. Instead, an error is printed and an empty `StringName` is returned.
```
E 0:00:01:0170   Test.gd:11 @ _ready(): Can't get method on CallableCustom "test(lambda)".
  <C++ Error>    Method/function failed. Returning: StringName()
  <C++ Source>   core/variant/callable.cpp:393 @ get_method()
  <Stack Trace>  Test.gd:11 @ _ready()
```
There is already a closed issue about a very similar bug (#80434), but the solution did not fix `get_method()` for these lambda functions, only when they don't access member variables.

As a workaround, you can declare a static variable and access the members from there:
```gdscript
var member := 3
static var this: Node

func _ready() -> void:
    this = self

    var callable1 := func test() -> int:
        return this.member
    var callable2 := func test() -> int:
        return 0

    print(callable1.get_method()) # no error anymore, prints 'test'
    print(callable2.get_method()) # no error, prints 'test'
```
I did a bit of digging and it seems like there was/is big code duplication between 2 kinds of lambda functions: 1 that does not access member variables and 1 that does. So it seems like the fix from #80434 may have only changed 1 and not the other. Though I'm no expert when it comes to C++ and the godot source code.

### Steps to reproduce

See above

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This looks like a simple oversight, will make a PR for this
