### ISSUE TITLE
Errors in editor\editor_node.cpp Godot cant compile 

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9407]
**Operating system or device - Godot version:**
Windows 10 64 bit Godot 3-0 commit f28f2b6ce8364b07dac797c1a9e335cb1d331b63

**Issue description:**
Error compiling godot 3.0 commit f28f2b6ce8364b07dac797c1a9e335cb1d331b63

**Steps to reproduce:**
git pull to godot 3.0 commit f28f2b6ce8364b07dac797c1a9e335cb1d331b63
try to compile with scons as usual, get an error
editor\editor_node.cpp(1500) : error: 'r' identifier not declared 
editor\editor_node.cpp(1500) : error: left operand of '->get_path' must signal the type class/struct/union/generic the type is unknown-type

**Comment by novemberist** [comment]
Same problem here, on Linux. I have already commented here https://github.com/godotengine/godot/pull/9402 and @akien-mga is already aware of the issue.

**Comment by akien-mga** [comment]
Yeah, compiling a fix locally to make sure it works.

**Comment by rubenjavier** [comment]
Thanks man,
working fast ;)
