### ISSUE TITLE
Internal Script Editor's 'Discard Local Changes and Reload' Does Not Work Reliably

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#94080]
### Tested versions

Godot v4.3.beta.mono (bf9648fae)

### System information

Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.5161) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

When a script is opened in both the internal script editor and an external editor, making changes in the external editor and then returning to the Godot editor causes the `Files have been modified on disk` dialog to appear. However, the option `Discard Local Changes and Reload` does not reload the script in the internal script editor.

### Steps to reproduce

Editor -> Editor Settings -> Dotnet -> External Editor -> Disable, then open the script in internal editor. Afterwards, set it with Visual Studio Code and open the script in vscode.

https://github.com/godotengine/godot/assets/53887662/a6d53af0-b231-43f1-a0b0-12fa17261fbc

### Minimal reproduction project (MRP)

You just need to create a single *.cs script.

**Comment by AThousandShips** [comment]
I'm not sure how reliable editing like this would be, having both internal and external editing

**Comment by nongvantinh** [comment]
In the past, this option would reload changes made externally. It worked basically the same as other text editors. However, when I tested it recently, it failed to do so.

**Comment by akien-mga** [comment]
Seems to caused by the same issue as #88399.
