### ISSUE TITLE
Inspector is cleared when play/stop the game

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9408]
**Operating system or device - Godot version:**
Windows 10 - master (f28f2b6)

**Issue description:**
The inspector is cleared out when the scene/game is played. It comes back to normal when I reselect a node but it's cleared again when the game is stopped.

![godot windows opt tools 64 3 0_2017-06-26_19-37-14](https://user-images.githubusercontent.com/5599796/27564292-089a6f66-5aad-11e7-98b4-fee81ba43824.png)

**Comment by akien-mga** [comment]
Same here on Linux.

**Comment by vnen** [comment]
This is a problem in 2.1 as well.

**Comment by ricpelo** [comment]
Still present in 3.0 alpha1.
