### ISSUE TITLE
Project Manager looks like it is reporting an error when importing a new project

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#94081]
### Tested versions

- Reproducible in v4.3.dev5.official [89f70e98d] onward
- Not reproducible in v4.3.dev4.official [df78c0636] and earlier

Looking at the commit log, I suspect that this change might have been introduced by https://github.com/godotengine/godot/commit/2130f1121a4d4bbc8c812ac6bea78cae1203c7ad

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 980 Ti (NVIDIA; 31.0.15.3598) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

When first clicking the Import button on the Project Manager, it appears as if an error message with red text is presented to the user, but then is quickly covered by the file selection window.

In previous versions of Godot, this error message and its red text was not shown until after a folder was selected:

https://github.com/godotengine/godot/assets/17506573/c091ddf7-b1eb-4d47-881e-dc87e4582aab

Personally, the red text of this error message caught my eye and made me think that there was an error happening with the project manager. This was not an issue previously because the red text error message would only appear after the user selected an invalid project or folder.

### Steps to reproduce

- Click the Import button in the Project Manager

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
:ooks like it related to this comment:
```
void ProjectDialog::ask_for_path_and_show() {
	// Workaround: for the file selection dialog content to be rendered we need to show its parent dialog.
	show_dialog();
	_browse_project_path();
}
```
