### ISSUE TITLE
"Parser bug: Mismatched external parser" due to autoload path including unnecessary `./`

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#94098]
### Tested versions

- Reproducible in 4.3.beta (16f98cd7079c2b22248ec358371f17bca355e42e)
- Reproducible in 4.3.dev4 to 4.3.beta2
- Not reproducible in 4.3.dev3 and earlier dev snapshots, or 4.2.2.stable

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Copying @Glorax's report from #92233, which was another bug with similar symptoms.
But this one happens straight in the editor.

The [Cogito](https://github.com/Phazorknight/Cogito) project template raises a bunch of parser errors in 4.3.dev4 and later.

<img width="737" alt="Screenshot 2024-07-07 at 10 16 16 PM" src="https://github.com/godotengine/godot/assets/114269106/e624ec62-4bbc-4115-b7af-2650197697ba">

```
resolve_class_member: Parser bug: Mismatched external parser.
<C++ Error>    Condition "!parser_ref->get_parser()->has_class(p_class)" is true.
<C++ Source>   modules/gdscript/gdscript_analyzer.cpp:909 @ resolve_class_member()
```

### Steps to reproduce

- Open Cogito project with zip linked below
- After initial import, restart
- See "Parser errors" on the main scene or when loading one of the demo scenes

### Minimal reproduction project (MRP)

Not minimal, but triggers the error: [Cogito-main.zip](https://github.com/user-attachments/files/16133960/Cogito-main.zip)

Could be reduced further.

**Comment by akien-mga** [comment]
I bisected this to #87124, CC @rsubtil @godotengine/gdscript 

I added some debug prints around the added `simplify_path()`, and indeed the reproduction project has some paths saved in scenes which are not "simple", and the mismatch seems to trigger this error.

```
script path before: res://addons/quick_audio/./Audio.gd
script path after: res://addons/quick_audio/Audio.gd
---
script path before: res://addons/quick_audio/Audio.gd
script path after: res://addons/quick_audio/Audio.gd
ERROR: Parser bug: Mismatched external parser.
   at: resolve_class_member (./modules/gdscript/gdscript_analyzer.cpp:909)
ERROR: Parser bug: Mismatched external parser.
   at: resolve_class_member (./modules/gdscript/gdscript_analyzer.cpp:909)
ERROR: Parser bug: Mismatched external parser.
   at: resolve_class_member (./modules/gdscript/gdscript_analyzer.cpp:909)
```

This seems to come from the autoload:
```
project.godot
25:Audio="*res://addons/quick_audio/./Audio.gd"
```

Removing the extra `./` from that line solves the issue in the linked project.

So that's a workaround for affected users, but the parser bug still needs to be addressed anyway.

**Comment by Glorax** [comment]
On my iMac, whenever I press the command key while the script editor is open, it immediately adds two "Parser bug: Mismatched external parser." errors to the output log. This also triggers when using Command + Tab.

**Comment by dalexeev** [comment]
MRP: [autoload-path-mrp.zip](https://github.com/user-attachments/files/16143106/autoload-path-mrp.zip)

**Comment by Baptiste81** [comment]
It seems that it has been merged for 4.3-RC1 ? 
If yes, i'm always having the problem. Cf screenshot. 

![image](https://github.com/user-attachments/assets/901adb94-c7d7-454e-9e21-9c688a813367)

**Comment by akien-mga** [comment]
Do you have autoloads with a non simplified path? If not, this would be a different bug, and we'd need a reproduction project to debug further.

**Comment by zaftnotameni** [comment]
> Do you have autoloads with a non simplified path? If not, this would be a different bug, and we'd need a reproduction project to debug further.

what would qualify a "non simplified path" ?

I'm also having this in 4.3rc1

```
ERROR: Parser bug: Mismatched external parser.
   at: (modules/gdscript/gdscript_analyzer.cpp:909)
ERROR: Parser bug: Mismatched external parser.
   at: (modules/gdscript/gdscript_analyzer.cpp:909)
```

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/issues/94098#issuecomment-2215409999

You can just look in `project.godot` how the oath to your autoloads look like.

But again, this bug was fixed, so most likely what you are both experiencing is an unrelated parser bug. It would be best that you each open an issue with a reproduction project.

**Comment by akien-mga** [comment]
And see https://github.com/godotengine/godot/issues/94244 for a still open know parser but with this error message.
