### ISSUE TITLE
DisplayServer.clipboard_get_image() on Windows not working

### ISSUE THREAD

**Issue by VampireSqu1d** [godotengine/godot#94094]
### Tested versions

- Reproducible in Godot v4.2.2.stable - Windows

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.5152) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

The function DisplayServer.has_feature() returns true, DisplayServer.clipboard_has() returns false when there is image on the clipboard and true when I have a string, clipboard_has_image() returns false always, clipboard_get_image() never returns the image on the clipboard. This same code does work on linux I tested it on the same machine.

```
func paste_image_from_clipboard():
	if DisplayServer.has_feature(DisplayServer.FEATURE_CLIPBOARD):
		if DisplayServer.clipboard_has():
			var path = DisplayServer.clipboard_get().split("\n")[0]
			var file_format = get_file_format(path)
			print("file path: " + path)
			
			if DisplayServer.clipboard_has_image():
				var image = DisplayServer.clipboard_get_image()
				var image_texture = ImageTexture.new()
				image_texture.set_image(image)
				%ImagePreview.texture = image_texture
			else:
				if file_format in SingletonObject.supported_image_formats:
					set_image_preview(path)
					%ImageDropPanel.visible = false
					%ImagePreview.visible = true
				else:
					print("file format not supported :c")
		else:
			print("no image to put here")
	else: 
		print("Display Server does not support clipboard feature")
```

### Steps to reproduce

using the functions is enough, I tried it on multiple projects `DisplayServer.clipboard_has_image()`, ` DisplayServer.clipboard_get_image()`, 

### Minimal reproduction project (MRP)

[DisplayServerTest.zip](https://github.com/user-attachments/files/16133816/DisplayServerTest.zip)

**Comment by bruvzg** [comment]
> when there is image on the clipboard and true when I have a string

What's the source of the image in the clipboard? Godot supports PNG and DIB clipboard formats (which should cover most cases), but some apps might use [different one](https://learn.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats).

**Comment by VampireSqu1d** [comment]
I tried PNG, JPEG, JPG and SVG I did think I might have been a format thing, but none of them worked

**Comment by matheusmdx** [comment]
I can confirm the problem, i also did some tests and put some prints in these two parts 

https://github.com/godotengine/godot/blob/82cedc83c9069125207c128f9a07ce3d82c317cc/platform/windows/display_server_windows.cpp#L764-L773

https://github.com/godotengine/godot/blob/82cedc83c9069125207c128f9a07ce3d82c317cc/platform/windows/display_server_windows.cpp#L845-L848

and `IsClipboardFormatAvailable(png_format))` always return 0 so that is the reason for clipboard_has_image and clipboard_get_image always fail. 

I don't know if that matters but when i check the clipboard history using `winkey + v` i don't see any of the png images i copied (using both ctrl + c or the mouse right click and selecting copy) but i can see all copied text and also i can see any image copied from PrintScreen button and that makes clipboard_has_image and clipboard_get_image works too (in that case `IsClipboardFormatAvailable(CF_DIB)` prints true)

**Comment by bruvzg** [comment]
> using both ctrl + c or the mouse right click and selecting copy

Are you trying to copy image files? I do not think this will put the image to the clipboard, so this is not supposed to work, only actual image copied from any image editing/viewing app should do.

**Comment by bruvzg** [comment]
I was not able to reproduce any issues with images in clipboard, everything that is pastable to Paint is also reading correctly in Godot.

**Comment by Calinou** [comment]
@matheusmdx Which Windows version (including build number) are you using? Press <kbd>Windows + R</kbd> and enter `winver` to check.

**Comment by matheusmdx** [comment]
> > using both ctrl + c or the mouse right click and selecting copy
> 
> Are you trying to copy image files? I do not think this will put the image to the clipboard, so this is not supposed to work, only actual image copied from any image editing/viewing app should do.

Sorry, i misunderstand how this function works. I redid the test but now copying an image from edge browser and indeed that worked as expected

**Comment by VampireSqu1d** [comment]
It does work the way @bruvzg describes the image I was trying to paste image from  file explorer, I guess I misunderstood how the function was supposed to work, thanks for clearing things out, I apologize for the inconvenience. I'll close the issue now.
