### ISSUE TITLE
Problems when compiling Godot from source code

### ISSUE THREAD

**Issue by arwasairl** [godotengine/godot#94111]
### Tested versions

Godot v4.2.2 source code

### System information

Windows 11, Godot v4.2.2, Core i9-14900K

### Issue description

When compiling Godot from source, multiple issues arise. When using MSVC++ (either v142 or v143) the compiler errors out with a C1001 error, or sometimes the computer locks up or blue screens (I personally had a computer lockup once with MSVC 142 when compiling Godot and I had a CLOCK_WATCHDOG_TIMEOUT blue screen once when compiling with v143.) When using MingW, it says that MingW cannot be found (even though MINGW_PREFIX is set with it set to the correct mingw bin folder). However, when using MSYS2's MingW bash, it does start to compile, but errors out again at the end with too many errors to count. Or, it errors out with a generic error (Error 3221225477). 

DISM and sfc were performed on the host machine, but I have also tried a Windows 10 virtual machine with the same results as above (minus the locking up and blue screening). Neither of these actions made differences when compiling Godot. I have also tried the source code in Main but it results in the same issues as described above.

### Steps to reproduce

1. Install python 3.12
2. Install scons with pip
3. Install Visual Studio 2022 with the following packages: "Desktop development with C++", "Windows application development", "Mobile development with C++", "Game development with C++".
5. Download and extract the Godot v4.2.2 source code.
6. Open a command prompt window in the extracted directory.
7. Use the scons command to start to compile Godot. (Supplying any parameters with scons leads to the same result)

### Minimal reproduction project (MRP)

Not Applicable

**Comment by arwasairl** [comment]
After further testing, this appears to be a bug specific to my CPU. Compiling on an i5-11400 had no issues. It is errors so closely ingrained within either the CPU or the compiler that it is most likely not Godot (I've personally had the CPU increment the RIP register incorrectly, who knows what other slew of issues this thing has at the machine level...)

**Comment by Calinou** [comment]
>  It is errors so closely ingrained within either the CPU or the compiler that it is most likely not Godot (I've personally had the CPU increment the RIP register incorrectly, who knows what other slew of issues this thing has at the machine level...)

If you've undervolted or overclocked your CPU, try running at stock configuration.

**Comment by arwasairl** [comment]
> > It is errors so closely ingrained within either the CPU or the compiler that it is most likely not Godot (I've personally had the CPU increment the RIP register incorrectly, who knows what other slew of issues this thing has at the machine level...)
> 
> If you've undervolted or overclocked your CPU, try resetting to the stock configuration recommended by Intel (not the motherboard manufacturer). If that doesn't suffice, reduce the power limit or the thermal limit in the UEFI (I use 90°C myself).
> 
> Raptor Lake (and Raptor Lake Refresh) CPUs are notorious for having this kind of issue due to their very high power consumption at stock – I speak from experience with my i9-13900K.

While I didn't overclock, the motherboard's default PL1 and PL2 was something insanely high (4096W). Dropping it to 253 watts and 400 amps for the current seemed to have made it compile properly now. Thanks!
