### ISSUE TITLE
RichTextLabel push_url() method missing

### ISSUE THREAD

**Issue by agorangetek** [godotengine/godot#94128]
### Tested versions

4.3.beta2

### System information

Windows 11

### Issue description

The RichTextLabel push_url() method is missing.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
It's called [push_meta](https://docs.godotengine.org/en/stable/classes/class_richtextlabel.html#class-richtextlabel-method-push-meta), because it allows you to embed any Variant in text, not just URL strings.

Closing.
