### ISSUE TITLE
Using a `double` type in GLSL cause a lot of rendering errors on macOS

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#94123]
### Tested versions

v4.3.beta2.official [b75f0485b]
v4.3.beta.custom_build [16f98cd70]

### System information

Godot v4.3.beta (16f98cd70) - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

This comes from testing the motion blur implementation by @sphynx-owner. As nobody in the motion blur discord workgroup knows what exactly causes the issue I was advised to report it as is:

![image](https://github.com/godotengine/godot/assets/60579014/0fe64ca8-bc82-4ff4-8423-4d0979fa280e)
![image](https://github.com/godotengine/godot/assets/60579014/8aa43a21-113c-43c6-86dc-c9106b70374d)
![image](https://github.com/godotengine/godot/assets/60579014/b829c8da-49df-4c12-86b7-b3e029b8c022)

Discussion has started here:
https://discord.com/channels/809721752019402762/1250813037221384245/1259859226336034916

### Steps to reproduce

Run the motion blur demo from the link below on an apple silicon mac

### Minimal reproduction project (MRP)

https://github.com/sphynx-owner/JFA_driven_motion_blur_demo

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/70772 where the same error code was reproduced.

Does the shader use doubles? This won't work on Metal (and therefore MoltenVK): https://github.com/godotengine/godot/issues/70772#issuecomment-1371379333

**Comment by clayjohn** [comment]
Looks like at least one shader uses doubles https://github.com/sphynx-owner/JFA_driven_motion_blur_demo/blob/e3ba524e62bd933e725c49edec305dd72e76260f/MyJumpFloodIteration/jfp_backtracking_experimental.glsl#L84

**Comment by Chaosus** [comment]
As stated in the meeting, the solution here is to add a preprocessor for the glsl files to warn users to not use the doubles when they use a Mac.

**Comment by akien-mga** [comment]
We'd need to inform users who use doubles on Windows and Linux too, so they're aware that they're losing macOS / iOS compatibility by doing so.

But it needs to be done in a way that users can discard if they decide that their project doesn't aim to support macOS/iOS.

**Comment by adamscott** [comment]
@passivestar If you replace all the `double` references to `float` (see diff) and clear the shader cache in the user dir of the project, it fixes this issue.

<details>
<summary>diff</summary>

```diff
diff --git a/MyJumpFloodIteration/jfp_backtracking_experimental.glsl b/MyJumpFloodIteration/jfp_backtracking_experimental.glsl
index ad0268d..bb4db19 100644
--- a/MyJumpFloodIteration/jfp_backtracking_experimental.glsl
+++ b/MyJumpFloodIteration/jfp_backtracking_experimental.glsl
@@ -81,9 +81,9 @@ void set_value(bool a, ivec2 uvi, vec4 value, ivec2 render_size)
 float get_motion_difference(vec2 V, vec2 V2, float parallel_sensitivity, float perpendicular_sensitivity)
 {
 	vec2 VO = V - V2;
-	double parallel = abs(dot(VO, V) / max(DBL_MIN, dot(V, V)));
+	float parallel = abs(dot(VO, V) / max(DBL_MIN, dot(V, V)));
 	vec2 perpen_V = vec2(V.y, -V.x);
-	double perpendicular = abs(dot(VO, perpen_V) / max(DBL_MIN, dot(V, V)));
+	float perpendicular = abs(dot(VO, perpen_V) / max(DBL_MIN, dot(V, V)));
 	float difference = float(parallel) * parallel_sensitivity + float(perpendicular) * perpendicular_sensitivity;
 	return clamp(difference, 0, 1);
 }
@@ -103,19 +103,19 @@ vec4 sample_fitness(vec2 uv_offset, vec4 uv_sample)
 //		uv_offset = normalize(sample_velocity) * FLT_MIN;
 //	}
 
-	double velocity_space_distance = dot(sample_velocity, uv_offset) / max(FLT_MIN, dot(sample_velocity, sample_velocity));
+	float velocity_space_distance = dot(sample_velocity, uv_offset) / max(FLT_MIN, dot(sample_velocity, sample_velocity));
 
-	double mid_point = params.motion_blur_intensity / 2;
+	float mid_point = params.motion_blur_intensity / 2;
 
-	double absolute_velocity_space_distance = abs(velocity_space_distance - mid_point);
+	float absolute_velocity_space_distance = abs(velocity_space_distance - mid_point);
 
-	double within_velocity_range = step(absolute_velocity_space_distance, mid_point);
+	float within_velocity_range = step(absolute_velocity_space_distance, mid_point);
 	
 	vec2 perpen_offset = vec2(uv_offset.y, -uv_offset.x);
 
-	double side_offset = abs(dot(perpen_offset, sample_velocity)) / max(FLT_MIN, dot(sample_velocity, sample_velocity));
+	float side_offset = abs(dot(perpen_offset, sample_velocity)) / max(FLT_MIN, dot(sample_velocity, sample_velocity));
 	
-	double within_perpen_error_range = step(side_offset, params.perpen_error_thresh * params.motion_blur_intensity);
+	float within_perpen_error_range = step(side_offset, params.perpen_error_thresh * params.motion_blur_intensity);
 
 	return vec4(absolute_velocity_space_distance, velocity_space_distance, uv_sample.z, within_velocity_range * within_perpen_error_range);
 }

```

</details>

**Comment by passivestar** [comment]
> @passivestar If you replace all the double references to float (see diff) and clear the shader cache in the user dir of the project, it fixes this issue

Yes, that's correct. I just confirmed it on discord to the author

**Comment by passivestar** [comment]
Closing as it turned out to be the same as issue as https://github.com/godotengine/godot/issues/70772
