### ISSUE TITLE
Running a project from a nonexisting path prints spurious error message about a benchmark key not being found

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#94132]
### Tested versions

- Reproducible in: 4.3.dev 82cedc83c9069125207c128f9a07ce3d82c317cc
- Not reproducible in: 4.2.2.stable, 4.3.beta2

### System information

Godot v4.3.beta (82cedc83c) - Fedora Linux 40 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 550.90.07) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Running the following command (which points to a non-existing folder):

```
bin/godot.linuxbsd.editor.x86_64 --path non_existing_folder
```

Results in:

```
ERROR: Benchmark key 'Startup:Core' doesn't exist.
   at: benchmark_end_measure (./core/os/os.cpp:658)
```

Previously, this did not result in that particular error being printed, only the "project not found, aborting" message. That message is still displayed, but there's a spurious error message alongside it now.

I bisected the regression to https://github.com/godotengine/godot/pull/93933. cc @m4gr3d 

### Steps to reproduce

Run this from a command line in the Godot repository root:

```
bin/<godot_executable_name> --path non_existing_folder
```

### Minimal reproduction project (MRP)

N/A

**Comment by permelin** [comment]
On beta 3:
```
% godot --version
4.3.beta.custom_build.82cedc83c
ERROR: Benchmark key 'Startup:Core' doesn't exist.
   at: benchmark_end_measure (./core/os/os.cpp:658)
```
