### ISSUE TITLE
SSAO renders reversed in orthographic Camera3D

### ISSUE THREAD

**Issue by mertkasar** [godotengine/godot#94139]
### Tested versions

- Reproducible in: v4.3.beta2.official [b75f0485b], v4.3.beta1.official [a4f2ea91a], v4.3.dev6.official [89850d553]
- Not reproducible in: earlier v4.x.x snapshots

### System information

Godot v4.3.dev6 - Ubuntu 24.04 LTS 24.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.183.01) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

SSAO renders reversed in Camera3D set in orthographic projection. Looks like the issue was introduced in v4.3.dev6.official [89850d553] Earlier versions work correctly.

<img width="420" alt="ssao_on" src="https://github.com/godotengine/godot/assets/2726562/cb3eca9d-3733-445c-ad89-0d3bc65cb55e">

### Steps to reproduce

You can toggle the camera preview in the editor or play the main scene.

### Minimal reproduction project (MRP)

[ssao_orthographic_mrp.zip](https://github.com/user-attachments/files/16145975/ssao_orthographic_mrp.zip)

**Comment by akien-mga** [comment]
@godotengine/rendering Probably another reverse Z victim?

**Comment by clayjohn** [comment]
> @godotengine/rendering Probably another reverse Z victim?

Yep. Most likely. Should be an easy fix in that case
