### ISSUE TITLE
Why drag and drop an image to the Inspector to set a texture is not available in 3.0?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9414]
**Operating system or device - Godot version:**
3.0

**Issue description:**

It's a vey handy feature to set a texture property for nodes such as Sprite, TextureButton.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by reduz** [comment]
i think it broke

**Comment by akien-mga** [comment]
Duplicate of #8676.
