### ISSUE TITLE
Godot is not finding methods in script (3.6.rc1)

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#94152]
### Tested versions

3.6.rc1.official.cfc4a0eff

### System information

Mac Sonoma 14.4.1 (23E224)

### Issue description

I was testing [GUT](https://github.com/bitwes/Gut/tree/godot_3x) with 3.6.rc1.official.cfc4a0eff.  Upon first launch it complained that it could not find a setter in [gut.gd at line 38](https://github.com/bitwes/Gut/blob/godot_3x/addons/gut/gut.gd#L38):
```
error(38,1):  The setter function isn't defined.
```
The setter exists.  I commented out everything from `setget` forward and it complained about the next one.  I commented out all the `setget` clauses and it ran, but then quickly errored stating different functions could not be found.

I have not tested any of the previous 3.6 versions.  This works fine in 3.5.3 and the repo has not changed in awhile.

### Steps to reproduce

1.  Open the following repo in 3.6.rc1.official.cfc4a0eff.
2. Open `addons/gut/gut.gd`
3. Notice that it says the setter is not defined.

https://github.com/bitwes/Gut/tree/godot_3x
or 
`git clone -b godot_3x https://github.com/bitwes/Gut`

### Minimal reproduction project (MRP)

See steps to reproduce

**Comment by timothyqiu** [comment]
I bisected this regression to #61993

Reverting 5bcc3d476cd06c9e9edd00e63a221d77d9ff7c0b fixes the issue.

**Comment by kdiduk** [comment]
I would revert it now and make a better fix after 3.6 is released. Indeed we are at RC, the original issue was minor and the fix is prone to regressions. Meanwhile I will try to investigate it ASAP.

**Comment by akien-mga** [comment]
Fixed by #94386.
