### ISSUE TITLE
Unable to access android editor while in play mode

### ISSUE THREAD

**Issue by Saul2022** [godotengine/godot#94159]
### Tested versions

Reprocible in godot 4.3 beta 1 and most likely the older versions

### System information

Sansung s23+ qualcom adreno 740

### Issue description

(Putting as bug, because it does not look intended at first glance)

It seems when trying to run  the game in play mode while you can play it alright on android, in the moment when you want to make any changes in games or lets say debug the  errors you had or profiling, it turns out theres no editor window, when usually on pc you have both the editor and game window to adjust your stuff etc..

![Screenshot_20240710_065308_One UI Home](https://github.com/godotengine/godot/assets/97898580/3e4edc32-ada4-4cbe-93ad-2f1a04929f1c)

This makes it  way harder to know  what may  cause the error in your code or  not know where to optimized, because you can't really set things up  before game window pops out, and while clicking the right arrow for returning to editor mode(closing the game window in the process), sometimes in larguer project( 200mb) it can quit the whole app itself. 

### Steps to reproduce

Open the project

Set play mode

Notices how you can"t  edit anything in editor as there is no window for it. 

### Minimal reproduction project (MRP)

[tests-android.zip](https://github.com/user-attachments/files/16155349/tests-android.zip)

**Comment by ayanchavand** [comment]
Have you tried remote debugging? if not you can enable it from from Debug -> Deploy with Remote Debug and make changes while the app runs on your phone

**Comment by Saul2022** [comment]
> Have you tried remote debugging? if not you can enable it from from Debug -> Deploy with Remote Debug and make changes while the app runs on your phone

WDYM? The main issue is that thre´s only one window and that only for the ingame one, which means theres only ingame window  , you can´t profile or anything just by code and if some code has an error you would have to close the window, because it not letting do anything.

**Comment by Saul2022** [comment]
>  just like how you would during the pc play mode so I don't see what's the problem.

Um doesn't seem to work , eanbled it first and then tried, with the same results and then with the reduced one and it kind of the same in my bigger project. 

![Screenshot_20240710_171528_Godot Editor 4](https://github.com/godotengine/godot/assets/97898580/8a3b2752-8128-4d9c-a868-48f478388962)

**Comment by ayanchavand** [comment]
ohh you are developing on android itself? yeah that's an issue. sorry about the misunderstanding

**Comment by Saul2022** [comment]
> ohh you are developing on android itself? yeah that's an issue. sorry about the misunderstanding

It alright, though that was on the title itself 😅, i can't on pc , becajse mine is dead.

**Comment by Saul2022** [comment]
I think it might be fine to close this or stay it open as m4gr3d mentioned tyou can do it on phones on editor/run/window_placement and select side by skde or editor( though this seems more unstable as it can sometimes not show up), though take into account that on big project ( as my experience statement) it can  take minutes to just go from play window to editor as it might be a bug or an android scoped storage issue.

**Comment by Alex2782** [comment]
`multi-window support` already seems to be included when debugging is activated in the GdScript. Perhaps it could also be made configurable for `Play Mode`

https://godotengine.org/article/android_godot_editor_play_store_beta_release/

<details><summary> Screenshot </summary>

![image](https://github.com/user-attachments/assets/e4762442-4225-465a-a023-d066ed69c5ee)
</details>

**Comment by Saul2022** [comment]
> > Note: The debugger functionality is only available on large form factor Android devices with multi-window support, due to the need to have the running project [side-by-side]

That what i'm doing on my s23+ and it works well, what does not is the same as editor  option , that sometimes doesn't work, or the editor get frozen due to a bug  prob related to this https://github.com/godotengine/godot/issues/94416#issue-2409969513

**Comment by AkzinNoob** [comment]
Its ACTUALLY easy to solve this problem i had it before you and took me too long to find the way out so i ll just share it with u first click on Editor then Editor setting then under the run group click on the window placement android window should be showing in front of u click on its property and chose side by side ..


![Screenshot_2024-08-01-23-04-47-856_org godotengine editor v4](https://github.com/user-attachments/assets/35368c1a-2352-497d-b571-03fef5364a1a)



 In case its didn't work try to activate the developer options on your device (you can watch shot video in yt if u don't know how to activate it)
From the developer options u need to go to the apps group and activate two options the first one is (Force activities to be resizable) and the second one is(enable non-resizable in multi window)


This two developer options with the Editor setting side by side should make the game testing when click play split the screen in two halfs one for the Editor and one for the game 
!!!(For me the Editor show only half of it i didn't find solution to make it show fully on the half of the screen)
Last thing this should shows the changes happening in the Editor like moving object in Editor will change its place in the game played too 
But i am not sure about the play test sending the informations to the Editor (u can print the any thing and check your self if its work probably or not)

**Comment by AkzinNoob** [comment]
Example for the Editor ahowing only half of it
![Screenshot_2024-08-01-23-30-42-064_org godotengine editor v4](https://github.com/user-attachments/assets/33c011aa-e7fc-4725-935e-cfa9bb435691)

See when i gave it larger amount of the screen its show more of my Editor 
![Screenshot_2024-08-01-23-30-48-396_org godotengine editor v4](https://github.com/user-attachments/assets/65b2a9f9-7d4c-4297-a1b3-b9446fba03dd)

**Comment by m4gr3d** [comment]
The issue should be mitigated by https://github.com/godotengine/godot/pull/95700 which will be available in the next 4.4 and 4.3 releases.
