### ISSUE TITLE
Non-smooth face normals on `CSGSphere3D`'s poles

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#94174]
### Tested versions

v4.3.beta.custom_build [97b8ad1af]

### System information

Windows 11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.4633)

### Issue description

The poles on a `CSGSphere3D`'s mesh aren't shaded smooth when `smooth_faces` is true.

`CSGSphere3D` on the left and `MeshInstance3D` with an equivalent `SphereMesh` on the right. The top and bottom where the segments meet aren't shaded smoothly on the csg.

![image](https://github.com/godotengine/godot/assets/133662278/3288d28e-3c84-447e-b6d2-4b87e28f87d1)

### Steps to reproduce

* Create a `CSGSphere3D`

### Minimal reproduction project (MRP)

N/A

**Comment by fire** [comment]
Feel free to close if you're satisfied with https://github.com/godotengine/godot/pull/94321 fixing this bug.

**Comment by akien-mga** [comment]
Fixed by #94321.
