### ISSUE TITLE
Tooltips do not display on hover on multi-monitor setups

### ISSUE THREAD

**Issue by ShawnHardern** [godotengine/godot#94189]
### Tested versions

Reproducible in: v4.3.beta3.mono, v4.2.2.stable.mono, Godot v4.2.1.stable.mono, Godot v4.2.stable.mono

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.5599) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads)

### Issue description

Tooltips fails to appear in the editor interface when hovering over editor buttons.

I have examined the Signals tab, Scene tab, and Movement Controls tab, but tooltips do not display in any of these areas.

Tooltips function correctly on a Linux laptop, suggesting the problem may be specific to Windows or related to my multi-monitor configuration

### Steps to reproduce

- Run Godot
- Hover mouse over an editor tile where tooltip is expected to show

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?

Also, can you reproduce this after disabling that setting, but switching to the **Compatibility** rendering method in the top-right corner of the editor?

**Comment by ShawnHardern** [comment]
> Can you reproduce this after enabling **Single Window Mode** in the Editor Settings then restarting the editor?
> 
> Also, can you reproduce this after disabling that setting, but switching to the **Compatibility** rendering method in the top-right corner of the editor?

Yeah unfortunately able to reproduce in both cases

**Comment by ShawnHardern** [comment]
completely restarting the application after applying Single Window Mode brings the tooltips back

**Comment by Calinou** [comment]
> Also once they have returned, disabling Single Window Mode and restarting the application tooltips seem to be back permanently

Are you sure single-window mode is effective after restarting? You should notice the Editor Settings dialog having a different appearance when it's enabled (OS-native window borders are not used when it's active).

**Comment by ShawnHardern** [comment]
> Are you sure single-window mode is effective after restarting? You should notice the Editor Settings dialog having a different appearance when it's enabled (OS-native window borders are not used when it's active).

Yes, I have observed the different appearance of the Editor Settings dialog when Single Window Mode is enabled, as you described.

Disabling and re-enabling Single Window Mode in conjunction with restarting the application has permanently restored the tooltips.

**Comment by Caffeinix** [comment]
I can reproduce this in Godot 4.2.2 stable on Windows 11.  **This appears to be a problem with multiple displays.**  If I disable my secondary display, the editor tooltips come back.  I have no better workaround than that, however.

**Comment by ShawnHardern** [comment]
As @Caffeinix has pointed out, when I disable my additional monitors in the Windows display settings, leaving only one active, the tooltips function as expected

**Comment by jadoc** [comment]
I'm not sure if this is related, but I also had problems with tooltips on multi-monitor displays.  In my case, however, I found that the underlying problem was actually how Godot suppresses tooltips when `WM_MOUSEMOVE` events are firing, even if the mouse isn't actually moving. I filed #95845 to document that particular cause and proposed #95846 as the fix. The people on this thread might want to test if that change improves their observed symptoms.

**Comment by akien-mga** [comment]
Reopening for now as the closing keyword in #95846 was a "maybe", so we should get it confirmed first.

**Comment by ShawnHardern** [comment]
@jadoc @akien-mga, I will try give this a test as soon as I can 👍🏻

**Comment by ShawnHardern** [comment]
@akien-mga @jadoc did a build from master and this definitely seems to have done the trick 

![Screenshot 2024-08-27 234411](https://github.com/user-attachments/assets/9497144a-dfd0-4034-8163-d262fd011541)

I tested dragging between different screens as I would usually, as well as open and closing external code editor, editing nodes etc and the tooltips remained

![Screenshot 2024-08-27 234141](https://github.com/user-attachments/assets/fee2e165-0d1f-4323-94b9-543421798a94)

![Screenshot 2024-08-27 233950](https://github.com/user-attachments/assets/82231b3e-e57b-48c0-ac45-51a0a9fd0799)

![Screenshot 2024-08-27 234207](https://github.com/user-attachments/assets/7d241fd6-71f5-447d-ac7d-38532b5540f9)

**Comment by akien-mga** [comment]
Great, thanks for confirming!

Fixed by #95846.
