### ISSUE TITLE
Trouble building Godot 3.6 pre-releases from xz tarball on aarch64/arm64

### ISSUE THREAD

**Issue by Zishan-Rahman** [godotengine/godot#94182]
### Tested versions

- Reproducible in build snapshots from 3.6-beta3 onwards using tar.xz source archive(s).
- **Not** reproducible in 3.6-beta2 or 3.6-beta1.

### System information

Flathub's Buildbot servers (work with Flatpak manifest done on Linux Mint 21.3)

### Issue description

I currently help to maintain [org.godotengine.Godot3](https://github.com/flathub/org.godotengine.Godot3) and [org.godotengine.Godot3Sharp](https://github.com/flathub/org.godotengine.Godot3Sharp) on Flathub. I have [a PR opened for the former Flatpak's beta branch](https://github.com/flathub/org.godotengine.Godot3/pull/5), which is currently stuck at 3.6-beta2. Since 3.6-beta3, every time I try to build the test build, the x86_64 build succeeds, while the aarch64/arm64 build fails, and it always fails at building Embree 3, even though the most recent 3.x version of Embree gained aarch64 support. At the time, I tried building the Embree module separately, since it's apparently supposed to work on aarch64/arm64, but _that_ failed on aarch64/arm64 too, and at least _one_ of the other modules also relied on Embree. Eventually I reset everything and hoped this issue would be resolved by subsequent development build releases, but it hasn't yet, and I regret not filing this issue earlier, but I wasn't sure if here was the right place to file this issue, and I'm not exactly sure if this problem exists on other aarch64/arm64 systems, since I don't have another aarch64/arm64 system to test the building of Godot 3 from source on.

A workaround _could_ be to just download the binary file(s) from GitHub/TuxFamily and use _those_, since somehow there's a prebuilt aarch64/arm64 binary and I don't know how it was built successfully (yet), but that's not ideal for a project that can be built from source, and, in the case of org.godotengine.Godot3Sharp, it would be impossible to do so without ditching aarch64/arm64 support, since there's currently no prebuild aarch64/arm64 binary for the Mono build of Godot 3 yet. This isn't an ideal situation for me to be in as a maintainer of both of those Flatpaks, especially since earlier versions of Godot 3, and also Godot 4 (both normal and C#/.NET versions) build just fine on both of Flathub's supported architectures.

If there is anything I'm missing with building Godot 3.6 for aarch64/arm64, please let me know, since it is indeed possible but I haven't achieved it yet. If the build can somehow be done, I'd like to amend the Flatpak manifest in my PR so that the build can be successfully done on both architectures. I look forward to your help and advice.

Here's the last test build that failed: https://buildbot.flathub.org/#/builders/6/builds/132297

### Steps to reproduce

- Go to https://github.com/flathub/org.godotengine.Godot3/pull/5
- Type "bot, build"
- Wait for the build to fail (the Flathub bot will denote in a comment that the build has failed)

### Minimal reproduction project (MRP)

N/A (this issue is to do with building Godot 3 itself)

**Comment by lawnjelly** [comment]
Looks like something to do with Neon.

Might need @akien-mga to take a look, he's our resident build guru.

**Comment by Zishan-Rahman** [comment]
I just realised that [the beta branch for the Godot 3 Flatpak (the normal one) is stuck at 3.5.3 RC 1](https://github.com/flathub/org.godotengine.Godot3/blob/d60f7c0bb1825fb066c5ed8e686e07bd49a369c4/org.godotengine.Godot3.yaml#L74). I'll try and build 3.6 Beta 1 from source to see if the problem actually starts from _there_. I'll report back here when I've determined something.

**Comment by akien-mga** [comment]
Yeah I would expect 3.6-beta1 to fail too then. Most 3.6 changes were made prior to beta 1, and that includes updating embree from 3.13.1 to 3.13.5: https://github.com/godotengine/godot/pull/69144

That update did cause issues building for Linux arm64 which were fixed by https://github.com/godotengine/godot/pull/70108. The linked issue report sounds like the exact same problem you're having here.

I did backport this fix to `3.x` with dede8d384f6.

The `3.x` branch's arch handling logic is pretty brittle, to be able to compile properly you need to use the `arch=arm64` argument, which I expect will fix it. Inferring it from `CC` isn't done properly.

Note that Godot uses its own `arch` names which may differ from the ones in macros provided by the flatpak toolchain. For Fedora packaging, here's the conversion function I use: https://src.fedoraproject.org/rpms/godot/blob/rawhide/f/godot.spec#_203

**Comment by Zishan-Rahman** [comment]
Indeed building Godot 3.6 Beta 1 fails with aarch64/arm64 for the same reason subsequent pre-release builds fail on aarch64/arm64. I added the `arch=arm64` to https://github.com/flathub/org.godotengine.Godot3/pull/5 just now. The build _should_ succeed now. I hope it does :pray:

**Comment by Zishan-Rahman** [comment]
[The test build succeeds now](https://github.com/flathub/org.godotengine.Godot3/pull/5#issuecomment-2221687867)! @lawnjelly  @akien-mga (sorry for the ping) thank you so much for your help and guidance on this issue that I've been stuck on for so long! I really appreciate it. I can safely merge https://github.com/flathub/org.godotengine.Godot3/pull/ now, and I'll remember to make sure the `arch=arm64` argument is also used for the _stable_ Godot 3 and Godot 3 C#/.NET/Mono Flatpaks when 3.6 inevitably gets an official release :+1:
