### ISSUE TITLE
Android game freezes and crashes at launch using Godot 4.3 beta 3

### ISSUE THREAD

**Issue by owlnewworlds** [godotengine/godot#94197]
### Tested versions

- Godot 4.3 beta 3 release

### System information

Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.4255) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

I was running my Android game through USB just fine with Godot 4.2.1 and decided to give the latest Godot 4.3 beta 3 release a go. But when I launched my game, it froze on the app icon. If I try to touch the back button, it does nothing, mostly but then it can display a Godot startup error like attached.

![WhatsApp Image 2024-07-11 à 08 42 48_efca4b52](https://github.com/godotengine/godot/assets/156072785/1e9899b2-ae15-4e9a-a76b-0ccabb6323dc)

### Steps to reproduce

- Install Godot 4.3 beta 3 Android export template
- Go to Project Settings and change the rendering_method to Mobile
- Change the rendering_method.mobile to gl_compatibility
- Connect your Android smartphone to your computer through USB
- Launch the game using Godot editor remote debugging
- Game freezes on the app icon and doesn't respond, when it does, it displays the error message shown in the issue description.

### Minimal reproduction project (MRP)

[test-godot-4.3-beta-issue.zip](https://github.com/user-attachments/files/16172648/test-godot-4.3-beta-issue.zip)

**Comment by owlnewworlds** [comment]
Can be fixed replacing rendering_method.mobile to mobile instead of gl_compatibility.
So don't know if it's considered as an issue.

**Comment by AThousandShips** [comment]
Changing the `rendering_method` option doesn't affect mobile, that's why the override exists, if it works when using the correct option this isn't a bug

**Comment by owlnewworlds** [comment]
> Changing the `rendering_method` option doesn't affect mobile, that's why the override exists, if it works when using the correct option this isn't a bug

I've just edited my comment, I also have the issue with the mobile rendering_method.mobile.

**Comment by owlnewworlds** [comment]
> This might simply be that your phone doesn't support gles3 correctly, but that would likely be a hardware compatibility issue rather than a bug

It's a Samsung Galaxy S24 Ultra from January 2024, if it has compatibility issues with GLES 3 then 99% of the current smartphones have issues too.

**Comment by AThousandShips** [comment]
Can you test with [beta2](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-2/)?

**Comment by owlnewworlds** [comment]
> Can you test with [beta2](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-2/)?

I'm trying to test but I had an issue where my Android export settings were reset. But I don't think it's related to Godot 4.3 beta 2, it's more related to me LOL I'm sorted it all and I will reply to you with how it went with beta 2. Sorry for the delay.

**Comment by AThousandShips** [comment]
No worries, it's more to try help pinning down when it happened, if we can show it happens in beta3 and not beta2 it would help a lot, but it isn't critical if you're unable

**Comment by owlnewworlds** [comment]
> No worries, it's more to try help pinning down when it happened, if we can show it happens in beta3 and not beta2 it would help a lot, but it isn't critical if you're unable

Looks like with beta 2 it literally crashes at game launch, no error, no output, I see the game quickly launching on the smartphone and then it closes immediately. Even Android doesn't show a popup like "App didn't run properly, do you want to wait or quit"

So far :
- Godot 4.3 beta 2 : crashing at launch
- Godot 4.3 beta 3 : freezing on app icon display, not responding and can show the error message attached in the description.

(Each time, I'm trying with both rendering_method.mobile values "mobile" and "gl_compatibility" so it must not be the origin of the issue.

Let's go trying with beta 1!

**Comment by owlnewworlds** [comment]
Same results with beta 1 as with beta 2. It seems beta 3 prevents the game from crashing at launch but instead, it freezes (and show an error when you try to back/quit the app with the bottom screen Android buttons).

**Comment by AThousandShips** [comment]
Thank you! That'll help a lot I think, the improvements could be related to:
* https://github.com/godotengine/godot/pull/93933

CC @m4gr3d

**Comment by owlnewworlds** [comment]
With the help of adb logcat, I finally understood what was the problem. I THINK.
Since I had to remove my android/build folder and download/install the new Android export template, I forgot a key metadata in the AndroidManifest.xml file. I saw explicitly the crash with adb logcat. When I fix the AndroidManifest.xml file, it's running again. Even if with Godot 4.3 beta 3

BUT I don't understand how I was able to reproduce the issue with an empty project then. So maybe there's still an issue after all? I don't want to waste people's time (which may already be the case, so sorry) with a fake issue so I don't really know there.

**Comment by m4gr3d** [comment]
@owlnewworlds can you provide the logs where you saw the crash when it was missing the admob id.

Does your project use a plugin? That could be the cause of the crash on start when the id was missing.

**Comment by owlnewworlds** [comment]
> @owlnewworlds can you provide the logs where you saw the crash when it was missing the admob id.
> 
> Does your project use a plugin? That could be the cause of the crash on start when the id was missing.

Logs attached ^^

I'm using a plugin, yes. AdMob by Poing Studios. I don't know if it's the plugin itself which generates the java exception and/or if Godot can do something so that it'd not be a runtime exception but a build exception like with the plugin I'm using for Google Play Services (GodotPlayGameServices by Jacob Ibanez Sanchez) which makes the build fail if you forgot the Google ID.

[adb_logcat_exception.txt](https://github.com/user-attachments/files/16179815/adb_logcat_exception.txt)

**Comment by m4gr3d** [comment]
Thanks for the logs!

The crash is indeed caused by the plugin. Looking at the logs, the plugin seems to introduce another dependency, which is the one responsible for throwing the exception and crashing the game when the admob id is missing.

I'd suggest reporting the issue to the plugin developers so they can try to address it. With the plugin apis we provide, the developers should be able to automatically insert the admob id in the manifest, so that issues like the one you ran into can be avoided.

**Comment by owlnewworlds** [comment]
> Thanks for the logs!
> 
> The crash is indeed caused by the plugin. Looking at the logs, the plugin seems to introduce another dependency, which is the one responsible for throwing the exception and crashing the game when the admob id is missing.
> 
> I'd suggest reporting the issue to the plugin developers so they can try to address it. With the plugin apis we provide, the developers should be able to automatically insert the admob id in the manifest, so that issues like the one you ran into can be avoided.

Thank you for your answer. I'll get in touch with them to see what they can do and I won't make the same mistake twice.
Sorry for your time lost.

**Comment by ckidwell** [comment]
> > Thanks for the logs!
> > The crash is indeed caused by the plugin. Looking at the logs, the plugin seems to introduce another dependency, which is the one responsible for throwing the exception and crashing the game when the admob id is missing.
> > I'd suggest reporting the issue to the plugin developers so they can try to address it. With the plugin apis we provide, the developers should be able to automatically insert the admob id in the manifest, so that issues like the one you ran into can be avoided.
> 
> Thank you for your answer. I'll get in touch with them to see what they can do and I won't make the same mistake twice. Sorry for your time lost.

Can you link the github issue you report to them? I believe I'm  having the same issue and would like to keep track of it?  Thanks!
