### ISSUE TITLE
MacOS laggy and unresponsive

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#94191]
### Tested versions

4.3 beta 3

### System information

M1, MacOS 14.5, 16GB ram

### Issue description

 Engine is very laggy and unresponsive and needs to be Force Quit to close. in MacOS on an M1. Tried on a Intel Macbook Pro and M2 Macbook Air and it worked correctly. The video shows how it is acting.

https://github.com/godotengine/godot/assets/4334870/98da9a03-e5ce-4b17-a8c8-03b794660405

### Steps to reproduce

Start 4.3 on macOS with M1

### Minimal reproduction project (MRP)

n/a

**Comment by Calinou** [comment]
Can you [start the editor from a terminal](https://docs.godotengine.org/en/stable/tutorials/editor/command_line_tutorial.html) and look at the console output? I wonder if it's falling back to software rendering of some kind.

Are you using Godot through a remote desktop session?

**Comment by Morokiane** [comment]
Here is the output. If I click the .app it is now sometimes doing the freezing up. Running it through the command line it always run as it should.

`Godot Engine v4.3.beta3.official.82cedc83c - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Using "default" pen tablet driver...
OpenGL debugging not supported!
Shader 'CanvasSdfShaderGLES3' SHA256: d2ee5600e77200b912a5bf96dcf0aa635b319146e12b705283fc6a6224e7da19
Shader 'SkeletonShaderGLES3' SHA256: 33658ee8981cccec8650d930b17246276f4819f218daabf318b911d0a08bd971
Shader 'ParticlesShaderGLES3' SHA256: 174b8f91ad1b4f75f542e3c4b2f91b30b017865543c00f25eaaa2eb4443a4454
Shader 'ParticlesCopyShaderGLES3' SHA256: 19f80e2bcaf8af08a3c3ceb5094cf99f10c08e983141878b3807e7a6091c4ee4
Shader 'CopyShaderGLES3' SHA256: 4961d4dca13cd7df78a0d8d416714b8804feb658457d242234169059f0894c4f
Shader 'CubemapFilterShaderGLES3' SHA256: 4c16259e24e00c96f04f7a3f45134ad6613afbb8705351b4ec57d697298b367a
Shader 'GlowShaderGLES3' SHA256: e6d75eae67449d5a15a2d05a04f11dc8935bade272ee0b3ee9ecb4ea7c83b47e
Shader 'PostShaderGLES3' SHA256: fb8dbad0b452513f7567ebab2a472cc7998bf308f4da6d27934739f1f564bc31
Shader 'CanvasShaderGLES3' SHA256: 2ac8566021e38ddd9b28bc4b7d2e1f7fba279ccbf629ddd1f4a799b95da5f67d
Shader 'CanvasOcclusionShaderGLES3' SHA256: 03eec6a0086549de733a4a335f2d60e6374a6950c5f33f4db7227b27cfd555b4
Shader 'SceneShaderGLES3' SHA256: 8b4b3d9939e590bb83d5791c2bc6057502297045b406fa00a74c47a70e031252
Shader 'SkyShaderGLES3' SHA256: 84315550169209f1caf0ab0388e64de5f83be6fa9ff7869a330da9bc86abd298
OpenGL API 4.1 Metal - 88.1 - Compatibility - Using Device: Apple - Apple M1
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
CORE API HASH: 172506318
EDITOR API HASH: 2434908857
EditorSettings: Load OK!
EditorTheme: Generating new theme for the config '1087744999'.
EditorTheme: Generating new icons.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
Loaded system CA certificates
EditorSettings: Save OK!`

**Comment by Morokiane** [comment]
I reset my Mac and now Godot 4.3 is behaving correctly. If there is nothing else that might be looked into on this issue I can close it.

**Comment by akien-mga** [comment]
We haven't had other similar reports so this was likely an interaction with a thirdparty application or a messed up driver/system component. Let's close as that's not a Godot bug (a priori) and can't be debugged further.
