### ISSUE TITLE
c# script file in autoload list and display error when opening project

### ISSUE THREAD

**Issue by eventidez** [godotengine/godot#94207]
### Tested versions

- Reproducible in: Godot v4.3 beta3 only

### System information

Godot v4.3.beta3.mono - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

  file 'res://src/App.cs' in autoload list, open the project when no '.godot' folder

Error message:
```
Cannot open file 'res://src/App.cs'.
  Failed to read file: 'res://src/App.cs'.
  Cannot load C# script file 'res://src/App.cs'.
  Failed loading resource: res://src/App.cs. Make sure resources have been imported by opening the project in the editor at least once.
  Failed to create an autoload, can't load from path: res://src/App.cs
```

### Steps to reproduce

Delect folder '.godot', and open project

### Minimal reproduction project (MRP)

[GodotBeta3.zip](https://github.com/user-attachments/files/16174587/GodotBeta3.zip)

**Comment by AThousandShips** [comment]
Does it still happen when you open again after this, deleting the `.godot` folder isn't something you generally should do and there's always some checks that need to be done when it has been deleted and it should all work after you've restarted

**Comment by eventidez** [comment]
> 在此之后再次打开时是否仍然发生这种情况，删除文件夹通常不是您应该做的事情，并且在删除文件夹时总是需要进行一些检查，并且重新启动后它应该都可以正常工作`.godot`

because of 'the custom resource cannot be displayed properly in the quick load resource list', I have to delete the folder '.godot' before opening the project every time
can be referenced: https://github.com/godotengine/godot/issues/86060

**Comment by eventidez** [comment]
> Does it still happen when you open again after this, deleting the `.godot` folder isn't something you generally should do and there's always some checks that need to be done when it has been deleted and it should all work after you've restarted

I can't find custom resource files in the quick load resource list after restarted, so I have to delete the folder `.godot` before opening the project every time.
Referenced: #86060

these and #93424 are workflow killers for me.

I can't delete `.godot` folder, and can't without deleting `.godot` folder.

**Comment by raulsntos** [comment]
Your MRP doesn't contain the file `res://src/App.cs`. Did you accidentally exclude it or does the file not exist? Make sure that the file exists and, since it's a C# file, make sure the C# project is built. Removing the `.godot` folder will also remove the C# built artifacts so the project will have to be re-built.
