### ISSUE TITLE
4.3 beta2 and beta3 don't start on MacOS Mojave (10.14.6)

### ISSUE THREAD

**Issue by neoascetic** [godotengine/godot#94200]
### Tested versions

- Reproducible in: 4.3 beta2, 4.3 beta3

### System information

MacOS Mojave 10.14.6 - Godot 4.3 beta2+

### Issue description

I am not sure about minimal MacOS version requirements for Godot, but 4.3 beta1 works perfectly on my desktop. I've tried on Macbook and Macmini, both running MacOS Mojave.

Regarding requirements, docs say:

> Native editor: macOS 10.13 (Compatibility) or macOS 10.15 (Forward+/Mobile)

But I am unable to even start the project launcher.

### Steps to reproduce

```
❯ ~/Downloads/Godot.app/Contents/MacOS/Godot --display-driver opengl3
dyld: Symbol not found: _OBJC_CLASS_$_CAEDRMetadata
  Referenced from: /Users/pavel/Downloads/Godot.app/Contents/MacOS/Godot
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Users/pavel/Downloads/Godot.app/Contents/MacOS/Godot
zsh: abort      ~/Downloads/Godot.app/Contents/MacOS/Godot --display-driver opengl3
```

### Minimal reproduction project (MRP)

Any project

**Comment by bruvzg** [comment]
> --display-driver opengl3

It's `--rendering-driver opengl3`, so you might be running with Vulkan renderer.

`CAEDRMetadata` is referenced by MoltenVK, probably caused by MoltenVK update or tool chain update.

**Comment by neoascetic** [comment]
I’ve tried with ‘--rendering-driver’, doesn’t work either. Even simple ‘--help’ doesn’t work (assuming it doesn’t involve any rendering at all).
