### ISSUE TITLE
Godot v4.3 beta3 displays an error when passing the --help flag

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#94202]
### Tested versions

- Reproducible in Godot v4.3 beta3.
- Not reproducible in Godot v4.3 betas 1 & 2, and Godot v4.2

### System information

Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) () - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

Passing the ```--help``` flag will print the normal help message and this error at the end of it:

```
ERROR: Benchmark key 'Startup:Core' doesn't exist.
   at: benchmark_end_measure (core/os/os.cpp:658)
```

### Steps to reproduce

Run ```./Godot_v4.3-beta3_linux.x86_64 --help``` in the terminal.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Seems like a leftover benchmark, will write a fix
