### ISSUE TITLE
Curve loading is broken

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#9421]
@Zylann This check seems wrong

ERROR: set_data: Condition ' input[i + 3].get_type() != Variant::INT ' is true.
   At: scene/resources/curve.cpp:733.

Also, this does not really make much sense in curve.h:

#ifdef TOOLS_ENABLED
	bool _disable_set_data;
#endif

Just put this boolean in the curve editor so it does not update, not in curve.

**Comment by reduz** [comment]
other than that, the curve editor seems super good!

**Comment by Zylann** [comment]
Oh dear, I forgot to update `get_data`... silly me^^

This boolean is the famous "dirty boolean" I told you about in IRC, and I can't put it in the curve editor (as it was before) because undo/redo calls directly `set_data` on the `Curve`, including when I do `commit_action`. I don't want `commit_action` to call `set_data` at this time because the curve is already in a correct state, and there is no need to re-apply it.

**Comment by reduz** [comment]
Ah I see, but why not using the undoredo properly to do the relevant
changes in the curve editor, or make the curve editor simply set the whole
array via undoredo every time you edit something?


On Jun 27, 2017 7:05 PM, "Marc" <notifications@github.com> wrote:

Oh dear, I forgot to update get_data... silly me^^

This boolean is the famous "dirty boolean" I told you about in IRC, and I
can't put it in the curve editor (as it was before) because undo/redo calls
directly set_data on the Curve, including when I do commit_action. I don't
want commit_action to call set_data at this time because the curve is
already in a correct state, and there is no need to re-apply it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/9421#issuecomment-311499713>,
or mute the thread

**Comment by Zylann** [comment]
Because that would be a bit silly, in fact^^
All the curve editor does is just calling functions of `Curve` to move its points (same API as a ingame), and it only uses `get_data` and `set_data` to serialize the state of the curve for undo/redo.
