### ISSUE TITLE
`bytes_to_var_with_objects` fails to decode custom classes on threads in v4.3.beta3

### ISSUE THREAD

**Issue by yukinogatari** [godotengine/godot#94220]
### Tested versions

Regression introduced in v4.3.beta3.official [82cedc83c]
Works as expected in v4.3.beta2.official [b75f0485b]

### System information

Godot v4.3.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

Deserializing custom classes with `var_to_bytes_with_objects` sometimes fails when run on a separate thread. Attempting to do so inconsistently results in the engine spitting out a bunch of `Can't load script at path: 'res://custom_resource.gd'.` errors. 

### Steps to reproduce

1. Run the MRP in v4.3.beta3.official [82cedc83c]
2. Click the `Run Threaded` button: it fails to properly deserialize the data ~60% of the time
3. Click the `Run Unthreaded` button: it produces no deserialization failures

### Minimal reproduction project (MRP)

[threaded-deserialization-bug.zip](https://github.com/user-attachments/files/16180002/threaded-deserialization-bug.zip)

**Comment by AThousandShips** [comment]
Are you able to test with this PR?
* https://github.com/godotengine/godot/pull/94169

CC @RandomShaper could you take a look

**Comment by yukinogatari** [comment]
That PR does indeed appear to fix the problem!

**Comment by RandomShaper** [comment]
Fixed by #94526.
