### ISSUE TITLE
Godot Editor freezing after playing scene only on Wayland on Godot 4.3 Beta 3

### ISSUE THREAD

**Issue by a-collado** [godotengine/godot#94228]
### Tested versions

Reproducible in: 4.3-beta3. - Not reproducible in: 4.3-beta2, 4.3-beta1, 4.3-dev6

### System information

Godot v4.3.beta3 - Arch Linux #1 SMP PREEMPT_DYNAMIC TKG Fri, 21 Jun 2024 13:02:41 +0000 - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 555.58.02) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

When I use the Godot Editor under a Wayland session on KDE Plasma, the editor freezes after I push the "Run the Project" or the "Remote Depuration" button. The game windows works fine, but the editor is completely frozen. It doesn't seem to produce a crash, and I can close it with the close button.

If I use the `--display-driver x11` flag, the editor works fine and doesn't freeze. The same happens if I try it in a X11 session.

I've used `WAYLAND_DEBUG=1` flag to make a log

[wayland.log](https://github.com/user-attachments/files/16182611/wayland.log)

Here's a sceen record of how it looks like:

https://github.com/user-attachments/assets/91a361b2-c0dc-4240-90dc-dc5c9e121b1a

### Steps to reproduce

- Install Godot 4.3 beta3
- Open the project
- Run the project

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16182649/MRP.zip)

**Comment by a-collado** [comment]
Thank you!!!
I've just tried and it seems to be working fine now. 
The editor doesn't freeze anymore when starting a scene.

**Comment by refrogerator** [comment]
I seem to be having this issue aswell with Godot 4.4-dev1 on bazzite-deck-gnome on my steam deck.

**Comment by refrogerator** [comment]
even on gnome xorg which is weird
