### ISSUE TITLE
[4.3 beta 3] AudioStreamPlayer does not work correctly during web export

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#94226]
### Tested versions

Godot 4.3 Beta 3

OpenGL API OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)) - Compatibility - Using Device: WebKit - WebKit WebGL

### System information

 Linux Ubuntu 22.04

### Issue description
There are the following problems with web export:

- For a sound that has been played at least once, the playing variable is always true
- It is impossible to set the volume of audio channels, even Master
- Cannot add effects to channels (they are ignored)

### Steps to reproduce

- Add an AudioStreamPlayer node to the scene
- Add WAV sound to it
- Play sound
- Check the $node.playing variable for the sound, it will be true even when the sound stops playing.

### Minimal reproduction project (MRP)

[audiodemo.zip](https://github.com/user-attachments/files/16190772/audiodemo.zip)

_Bugsquad edit: added the MRP_

**Comment by adamscott** [comment]
Please create an MRP for such projects, even if it seems simple to you.

**Comment by SkanerSoft** [comment]
MRP: 
[audiodemo.zip](https://github.com/user-attachments/files/16190772/audiodemo.zip)

**Comment by adamscott** [comment]
> * Cannot add effects to channels (they are ignored)

For this, this is as designed for the moment. There will maybe be a way to implement basic effects, but custom ones are out of the question. If you need badly effects, you'll need to use streams instead.

**Comment by anniryynanen** [comment]
#94269 may fix some of these issues.

**Comment by adamscott** [comment]
Reopening as #94268 had a typo that prevented the fix to work.

#94800 should fix the issue.
