### ISSUE TITLE
Window file drag and drop operations incorrectly feedback as failed on macOS

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#94223]
### Tested versions

4.3b3

### System information

macOS 14.5

### Issue description

Native Windows currently support dropping in (any) files from the file system, and when you do they emit the `files_dropped` signal. However, on macOS it seems Godot is incorrectly reporting the drag operation as a failure to the macOS drag system, causing it to show the failed drop animation where the dragged file animates back to where you dragged it from.

(Related proposal for some further improvements to drag and drop: https://github.com/godotengine/godot-proposals/issues/10178)

### Steps to reproduce

- Drag a file into a running Godot game window on macOS.
- Regardless of it you've connected the files_dropped signal or not, the files will bounce back to their origin, indicating the drag operation failed.

My guess is that in the macOS window drag operation delegate implementation 
`- (BOOL)performDragOperation:(NSDraggingInfo)sender;` is incorrectly always returning `false`, signaling the drag operation failed instead of `true` as it should when it is successful. 

### Minimal reproduction project (MRP)

Any Godot native window should do.

**Comment by bruvzg** [comment]
> My guess is that in the macOS window drag operation delegate implementation - (BOOL)performDragOperation:(NSDraggingInfo)sender; is incorrectly always returning false, signaling the drag operation failed instead of true as it should when it is successful.

Indeed, it's always returning `false`.

**Comment by bruvzg** [comment]
> Regardless of it you've connected the files_dropped signal or not, the files will bounce back to their origin, indicating the drag operation failed.

Native window is connected to the internal `Window` callback (always valid) without return value, so fixing it will make it accept drop regardless of user connected callback, this probably should be changed in future versions, but will be compatibility breaking (or require a new callback to check if DND is supported).

**Comment by lostminds** [comment]
> fixing it will make it accept drop regardless of user connected callback, this probably should be changed in future versions

Right, but that's an improvement at least. Thanks for the quick fix on this! And perhaps this check for connected files_dropped signal could be included along with file format filtering as proposed in https://github.com/godotengine/godot-proposals/issues/10178 that will also require some reference to the internal window object properties in evaluating the drag operations.
