### ISSUE TITLE
Rendering errors on Mobile and Compatility renderer using Godot 4.3 Beta 3

### ISSUE THREAD

**Issue by a-collado** [godotengine/godot#94225]
### Tested versions

- Reproducible in: 4.3-beta3.  - Not reproducible in: 4.3-beta2, 4.3-beta1, 4.3-dev6

### System information

Godot v4.3.beta3 - Arch Linux #1 SMP PREEMPT_DYNAMIC TKG Fri, 21 Jun 2024 13:02:41 +0000 - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 555.58.02) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

When I launch the game using the Mobile or the compatibility renderers, he game renders with darker colors. It looks like if the light is not being correctly rendered. When I launch the game in my Android phone via remote depuration, it renders incorrectly in both rendererers, and in my computers it only looks wrong in Compatiblity one. This is only happening in Godot 4.3-beta3

This is the game running in Godot 4.3-beta2
![Screenshot_20240711-201748](https://github.com/godotengine/godot/assets/57129654/43484ac4-dd67-4f53-bfef-d478bc3c31b8)

And this is in Godot 4.3-beta3
![Screenshot_20240711-200738_TFG](https://github.com/godotengine/godot/assets/57129654/aaa95cb2-300e-4d70-b112-01bfc759d355)

### Steps to reproduce

- Install Godot 4.3 beta3
On phone:
- Set the renderer to Mobile or Compatibility
- Connect the phone via USB
- Start remote depuration on any scene
On PC:
- Set the renderer to Compatibility
- Start the game on any scene

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16182393/MRP.zip)

**Comment by clayjohn** [comment]
Bisected to 637f4a10ed34ae40686fd26e095fcf3a9bb61042

CC @m4gr3d
