### ISSUE TITLE
Code Editor scrolling with Mouse Wheel affected by Project Physics Ticks per Second

### ISSUE THREAD

**Issue by CubeFusion** [godotengine/godot#94248]
### Tested versions

- Reproducible in 4.2.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.5612) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

The Code Editor in Godot seems to be affected negatively if a low value is set in the projects Physics Ticks per Second. This seems unintentional - as I would normally only expect the Physics Ticks per Second value to effect values within the game, not the Editor UI. It's possible other aspects of the UI are also affected, but I haven't stumbled on any blindly yet.

### Steps to reproduce

1. Make sure to change "General -> Physics -> Common -> Physics Ticks per Second" in Project Settings
to something absurdly small (like 1) from the default 60. 
2. Scene -> Save All Scenes (Might be unnecessary - the goal is to make sure the Physics Ticks per Second change sticks).
3. Project -> Reload Current Project (Necessary, the Godot UI only seems to snag the Physics Ticks per Second variable on project startup.)
4. Open a document in the Code Editor (I've tested both .txt and .gd)
5. Scroll the mouse wheel up or down, latency will be through the roof and scrolling will feel unresponsive.

### Minimal reproduction project (MRP)

[Scrolling_physics_test.zip](https://github.com/user-attachments/files/16188487/Scrolling_physics_test.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/28385

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
