### ISSUE TITLE
Laggy dock resizing, dragging split in editor low fps

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9426]
**Operating system or device - Godot version:**
current master
macOS

**Issue description:**

dragging the split to resize different editor docks is slow/laggy compared to 2.1

**Steps to reproduce:**
Open godot 3.0 resize the right or left dock section. It will render with less than 10 fps.

## Things we know (would be good to know):
 - [x] This issue is not existing in the 2.1 version from the website
 - [x] Also present in release compile
 - [x] drawing texture style boxes needs less number calculations on the cpu when redrawn. (styleBoxFlat needs to calculate the size and position for multiple rectangles. This gets even more complex with the new style boxFlat (rounded borders)
 - [x] there is no noticeable difference in performance when I test it with the more complex calculations of the new style box. (taking all that into consideration, it does not seem like the lag has anything to do with the actual style box drawing)
 - [ ] the lag was introduced when switching to the new renderer in the viewport.
 - [x] the lag is much bigger when resizing the editor in a way that the main viewport gets resized.
 - [x] **probably has something to do with the input system**
I marked things in the list which I know. the rest are more or the less questions which, when answered would help finding the issue for the low performance.

@volzhs maybe you have already discovered additional information.

**Comment by Zylann** [comment]
Just to make sure, did you compile with `release_debug` flag?

**Comment by toger5** [comment]
I'm pretty sure I did yea.

**Comment by toger5** [comment]
Just compiled with `release_debug` still equally bad performance.

**Comment by toger5** [comment]
In the most recent master 82298e9 the performance increased increased. but only when resizing docks other than the main viewport

**Comment by Zylann** [comment]
I still get really bad performance with the 3.0 alpha1, even if I think it's a release build. It feels like 5 times slower than 2.1.3, the biggest slowdown being when the main viewport is affected.

**Comment by reduz** [comment]
the reason is probably that it's not merging input events or something else... will have to investigate eventually

**Comment by toger5** [comment]
@reduz so this was introduced with the rewrite of the inputs? this actually could be right... I think it started to get laggy around that time. can't say for sure though.

**Comment by toger5** [comment]
@reduz this seems to have improved?

**Comment by akien-mga** [comment]
Yes, fixed by bf1f83ed.
