### ISSUE TITLE
Unexpected difference in Draw Calls when using SubViewport to display GUI in 3D when using Compatibility vs Moble renderer

### ISSUE THREAD

**Issue by nikywilliams** [godotengine/godot#94264]
### Tested versions

v4.3.beta3.mono.official [82cedc83c]

### System information

Godot v4.3.beta3.mono - Windows 10.0.19042 - Vulkan (Mobile) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21912.14) - AMD Ryzen 5 7600X 6-Core Processor (12 Threads)

### Issue description

This behavior may be expected, but I was unsure. I did take time to search for this behavior, but was unable to find anything that confirmed that it was expected.

When displaying a GUI on a 3D world using a SubViewport, the draw calls on the Moble and Forward+ renderer are much higher than expected. When changing to the Compatibility renderer, the draw calls are more of what I'd expect.

This is while using the Moble renderer (Same behavior for Forward+):
![image](https://github.com/user-attachments/assets/8fe17bb7-0e7e-4cd6-bfea-aae6152a59ae)

And this is while using the Compatibility renderer:
![image](https://github.com/user-attachments/assets/e32ea717-3791-4bc6-8027-a2cf3e14d5ca)

### Steps to reproduce

MRP is attached. Just swap between the Mobile/Forward+ and Compatibility renderer to see the behavior described

### Minimal reproduction project (MRP)

[Sandbox.zip](https://github.com/user-attachments/files/16194923/Sandbox.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/71084.

This will be resolved by https://github.com/godotengine/godot/pull/92797.
