### ISSUE TITLE
InstancePlaceholder doesn't assign Resource to instance

### ISSUE THREAD

**Issue by crapola** [godotengine/godot#94266]
### Tested versions

These versions work fine:
v4.2.2.stable.official [15073afe3]
v4.3.dev1.official [9d1cbab1c]
v4.3.dev2.official [352434668]
v4.3.dev3.official [36e943b6b]
v4.3.dev4.official [df78c0636]
v4.3.dev5.official [89f70e98d]
v4.3.dev6.official [89850d553]

Bug appears with:
v4.3.beta1.official [a4f2ea91a]

### System information

Windows 11 - v4.3.beta3.official [82cedc83c]

### Issue description

Node instantiated via InstancePlaceholder is missing Resource assigned in editor. 

### Steps to reproduce

A node that is a scene root has an export var that defaults to null such as
`@export var res:Resource`
That scene is placed in the editor in another scene, marked 'Load as Placeholder', and there we assign a new resource to 'res'.
After using create_instance on it at runtime, we observe the assigned resource is null.

### Minimal reproduction project (MRP)

[instanceplaceholder_bug.zip](https://github.com/user-attachments/files/16194922/instanceplaceholder_bug.zip)

Run and read console.

**Comment by matheusmdx** [comment]
Bisecting points to #90306 as the culprit:

![image](https://github.com/user-attachments/assets/290166ce-9253-4f43-b1f1-2389891a09a5)
