### ISSUE TITLE
3.0 is slower that 2.1.3

### ISSUE THREAD

**Issue by sergey-push** [godotengine/godot#9429]
**Operating system or device - Godot version:**
Godot 3.0, 2.1.3, Windows 10 x64

**Issue description:**
Godot 3.0 is 2-3 times slower than 2.1.3
Created a project with the same logic:
300 objects initialized from scene : Path -> PathFollow -> Sprite
190fps vs 90fps.
![image](https://user-images.githubusercontent.com/26034850/27619567-67d6f15e-5b91-11e7-85fd-afacf35d53b7.png)

3.0 is a lot more beautiful, but still

**Comment by vnen** [comment]
Both builds in release mode?

**Comment by sergey-push** [comment]
amazing point. used the build from here http://fixnum.org/godot/
Seems like it is compiled in debug mode "-DDEBUG_ENABLED".

Recompiled with release_debug and the results are slightly better: 250 fps vs 200 fps, which is still 20% behind.
![image](https://user-images.githubusercontent.com/26034850/27636057-af1a11cc-5bd7-11e7-9101-88c88c2c535a.png)

**Comment by reduz** [comment]
I don't think this is currently a problem, and there are many factors that might be contributing to this, including the debug opengl context and higher resolution framebuffers.
More closer to release date it would be interesting to check again.

**Comment by akien-mga** [comment]
Let's keep this open to remember to check before releasing 3.0.

**Comment by reduz** [comment]
Kicking to 3.1, will not really be solved until a GLES2 backend is reimplemented

**Comment by akien-mga** [comment]
I think we can close this issue, there are many factors that can impact how well Godot 3.x can perform compared to 2.x, and this issue doesn't focus on any specific ones that could be benchmarked/worked on. The GLES3 renderer is higher end, so it's normal that on the same hardware it may perform worse, yet produce better results. The GLES2 renderer in 3.1 should perform similarly to Godot 2.1's renderer, but there are many other changes between the two versions that can impact performance (using Bullet for physics, dozens of new features, etc.).
