### ISSUE TITLE
VisibilityNotifier2D.is_on_screen always return False in _ready method.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9430]
**Operating system or device - Godot version:**
ALL

**Issue description:**

In _ready, it always return false, even if it's inside of the screen.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by alexzheng** [comment]
Another related issue is VisibilityEnabler2D can not disable nodes when it is added outside of the screen #9321

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by vnen** [comment]
(If this hasn't changed since) the node probably needs a frame or two before it can determine whether or not it's on the screen. While this could be made `true` by default, if the node is spawned outside the screen it'll have a wrong value too.

You can try adding a `yield` to wait a frame before checking the value.

**Comment by akien-mga** [comment]
Based on what @vnen wrote, I think it's not a bug and just needs to be better documented (if not the case already).
