### ISSUE TITLE
list of animations in anim player drop down can't be scrolled

### ISSUE THREAD

**Issue by ianmckenna87** [godotengine/godot#94318]
### Tested versions

4.3 beta 1

### System information

windows 11

### Issue description

the animation list in the drop down menu of animation player can't be scrolled if populated by enough animations

### Steps to reproduce

populate animation player with animations imported from various animation libraries

### Minimal reproduction project (MRP)

[anim list scroll issue.zip](https://github.com/user-attachments/files/16202879/anim.list.scroll.issue.zip)

**Comment by AThousandShips** [comment]
Please test with [beta3](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-3/), to make sure it still occurs

**Comment by ianmckenna87** [comment]
> Please test with [beta3](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-3/), to make sure it still occurs

Yeah.. just tested and it's fixed! Many thanks!

**Comment by ianmckenna87** [comment]
fixed in beta3
