### ISSUE TITLE
ITMS-90426: Invalid Swift Support - AOT xcframework iOS export problem

### ISSUE THREAD

**Issue by roonskipp** [godotengine/godot#94317]
### Tested versions

- Reproducible in: v4.2.2.stable.mono.official [15073afe3]

### System information

Sonoma 14.3 - Godot v4.2.2.stable.mono.official [15073afe3]

### Issue description

Cannot upload a build of iOS game to Appstore connect. It results in the error delivered by mail within a few minutes of distributing to appstore connect: 

TMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it. 

### Steps to reproduce

Steps to reproduce:

1. A project is created with .NET C#.
2. Create the .NET solution
3. Export for iOS

The third step creates a file called ```>project_name<_aot```,  and is an "xcframework" in the Frameworks folder of the exportred project. 

When archiving the xcode project for publishing the error is sent by mail after upload is completed. I tried creating a project without generating the .NET solution first, and this does not create the >project_name<_aot xcframework file. This successfully uploads the build to appstore connect so it is _very likely_ that the aot xcframework file is the culprit. 

### Minimal reproduction project (MRP)

[TestFolderGodot.zip](https://github.com/user-attachments/files/16202820/TestFolderGodot.zip)

**Comment by roonskipp** [comment]
It seems that the archived projects has a "Frameworks" folder inside the .app file. This Frameworks folder contians a .dylib file. Reading https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543-CH1-PROJ_CONFIG-APPS_WITH_DEPENDENCIES_BETWEEN_FRAMEWORKS it seems to indicate the dylib files outside of framework bundles is not supported. 

Some other stackoverflow threads with loosely related issues suggest changing the dylib (dynamic library) to a static library. I don't know how to do this or if this is the correct workaround, but I will look into it.

**Comment by bruvzg** [comment]
What's the name of the `dylib` file you get? Godot should auto convert all `dylib`s to Frameworks during export.

**Comment by roonskipp** [comment]
The name of the dylib is the godot project name, so <godot-project-name>.dylib. 

I'll download the 4.3 beta and have a look if it is fixed.

**Comment by roonskipp** [comment]
Tested on 4.3 beta 3 now. It works like a charm. Thanks @bruvzg. I will close this issue now.
