### ISSUE TITLE
Scene Tree: A node gets selected even without being selected

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#94319]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Newest MacOS / Mac mini M1

### Issue description

A node in the Scene Tree gets randomly selected if other Nodes / Scenes are dragged around.

### Steps to reproduce

Make a scene tree like in the image:
![image](https://github.com/user-attachments/assets/f4bb337b-5dc8-4b3a-9f06-c7db620a31bb)
Select the "CollisionShape2D" (click on it once)
Now click on the camera (at this point the CollisionShape2D will automatically get deselected as expected) and drag it like in the gif below.
After you finish dragging, the CollisionShape2D will be automatically selected too.
Now click and hold on the camera node and drag it somewhere else. The CollisionShape2D will get dragged with it too and the "level top" node will break.

![godot selects a node too much](https://github.com/user-attachments/assets/94ae8139-7b4f-4c4c-8e44-a16766a8de6a)

### Minimal reproduction project (MRP)

Godot IDE

**Comment by inhalt120g** [comment]
Same thing, but in this case I drag the camera from top to bottom and in the end two nodes end up selected:
![godot selects a node too much](https://github.com/user-attachments/assets/425e6cc6-f9e3-45ea-a868-1f47b08c745f)

**Comment by KoBeWi** [comment]
Sounds similar to #93935
