### ISSUE TITLE
Can't disable the 3D transform gizmo in the editor

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#94312]
### Tested versions

v4.3.beta.custom_build [82cedc83c]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

There is an option to disable all gizmos in the editor's 3D view at `Perspective > View Gizmos`. However, the transform gizmo is the only one that doesn't hide.

Also, there is no option to hide only the transform gizmo in the scene's toolbar `View > Gizmos`. For reference, the 2D view has options to disable all or specific transformation gizmos.

### Steps to reproduce

* Create or select any `Node3D`.
* 3D scene view: `Perspective > View Gizmos`

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is more of a missing feature than a bug, and is being implemented in:
* https://github.com/godotengine/godot/pull/87793
