### ISSUE TITLE
Issue using sprite node

### ISSUE THREAD

**Issue by Tomshon2** [godotengine/godot#94313]
### Tested versions

Godot Engine v4.2.2.stable.official

### System information

Windows

### Issue description

When importing an png it shows as size 0x0 and unvailabel to use! It also shows full white when using.

### Steps to reproduce

Impor
![Captura de ecrã 2024-07-13 145406](https://github.com/user-attachments/assets/79bd587d-937f-4500-9076-c11bb85bd8c7)
![Captura de ecrã 2024-07-13 145406](https://github.com/user-attachments/assets/20a44603-11f3-406b-b0ba-94b7468d57e9)
t PNG and or use it!

### Minimal reproduction project (MRP)

[2.zip](https://github.com/user-attachments/files/16202384/2.zip)

**Comment by AThousandShips** [comment]
Consolidating in:
* https://github.com/godotengine/godot/issues/93018

Thank you for reporting, this is because the image is too big, the linked issue covers improving the message when importing invalid textures

**Comment by Tomshon2** [comment]
Ty you so much!
