### ISSUE TITLE
AnimationTree's AnimationMixer fields arbitrarily becoming uneditable

### ISSUE THREAD

**Issue by Pshy0** [godotengine/godot#94316]
### Tested versions

- Reproducible in v4.3.beta3.official [82cedc83c]

### System information

Ubuntu 24.04 LTS

### Issue description

When no node is having focus and an AnimationTree is selected, some of the AnimationMixer fields becomes grayed out and not editable.
Selecting another node and selecting the AnimationTree back makes the properties editable again.

Video:

https://github.com/user-attachments/assets/4b704f8f-d8d8-477a-9049-6ee41a70b1ae

### Steps to reproduce

In the MRP, in the main scene...
- Unselect all nodes then select the AnimationTree: AnimationMixer have some fields grayed out.
- Select the AnimationPlayer then select back the AnimationTree: fields are no longer grayed out.

### Minimal reproduction project (MRP)

[mrp-animation-mixer-arbitrary-property-graying.zip](https://github.com/user-attachments/files/16202527/mrp-animation-mixer-arbitrary-property-graying.zip)

**Comment by Pshy0** [comment]
This bug can be also be seen in the video from https://github.com/godotengine/godot/issues/93455 but was not mentioned in that issue.

**Comment by TokageItLab** [comment]
It is just a property of the dummy animation player that is not allowed to be changed.
