### ISSUE TITLE
Scene Tree: a Node gets deselected and another one gets selected if the drag / drop is performed in a particular way

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#94320]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Newest MacOS / Mac mini M1

### Issue description

When dragging a node, stopping over another Node without releasing dragging selects that node for potential selecting for cases where the dragging didn't go through.

### Steps to reproduce

Just do like in this gif, and you'll end up with a "" selected even though you never selected it.
![godot selects a hovered over node](https://github.com/user-attachments/assets/dc35eb4d-7a8b-4329-b275-ce58281fa344)

Basically while dragging, stop over any Node without dropping, and the hovered over node will turn blue (at this point the Inspector will start showing info of the hovered over Node).
Now finish dragging and dropping the node you started the operation with, for example drag and drop it into the "empty" space of the Scene Tree.
The Node you hovered over will get selected and the original node will be in the original position and deselected (I'd expect the end result to be the original node to end up on the bottom and stay selected without any other nodes getting selected).

### Minimal reproduction project (MRP)

Godot IDE.

**Comment by AThousandShips** [comment]
Same bug as:
* https://github.com/godotengine/godot/issues/91254

Which seems to somehow have resurfaced *again*
