### ISSUE TITLE
debug release does not compile

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9432]
**Operating system or device - Godot version:**
**macOS** (OSX) Xcode

**Issue description:**

can't compile with `debug_release`. the error:
api_generator.cpp line 264
```cpp
	if (method_bind && method_bind->get_return_type() != StringName()) {
		method_api.return_type = method_bind->get_return_type();
```
`get_return_type()` does not exist.
it's declared here:
method_bind.cpp line 208
``` cpp
#ifdef DEBUG_METHODS_ENABLED

	_FORCE_INLINE_ void set_return_type(const StringName &p_type) { ret_type = p_type; }
	_FORCE_INLINE_ StringName get_return_type() const { return ret_type; }

	_FORCE_INLINE_ Variant::Type get_argument_type(int p_argument) const {

		ERR_FAIL_COND_V(p_argument < -1 || p_argument > argument_count, Variant::NIL);
		return argument_types[p_argument + 1];
	}

	PropertyInfo get_argument_info(int p_argument) const;

	void set_argument_names(const Vector<StringName> &p_names);
	Vector<StringName> get_argument_names() const;
#endif
```

Seems like this part hasn't been touched since clang-format so it is probably not the issue.

**Comment by akien-mga** [comment]
CC @karroffel, it's in GDNative

**Comment by toger5** [comment]
@akien-mga @karroffel seems like this was a temporary issue. I compiled with `debug` worked, and than also debug_release worked. (maybe it even was a user error. Could be possible that I'm missing something...)
sorry for wasting your time
