### ISSUE TITLE
Simplify 3D KinematicBody

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9433]
Just a reminder for @reduz to do the 3D changes corresponding to bc509ac7b for 2D.

**Comment by reduz** [comment]
yes no worries, when I port the 3D demos, will have no choice but to change
this for the kinematic 3D demo

**Comment by eon-s** [comment]
KB needs proper layer and mask behaviour too, if that can be fixed too would be great.

**Comment by akien-mga** [comment]
> KB needs proper layer and mask behaviour too, if that can be fixed too would be great.

Well it has those already since it inherits PhysicsBody:
- http://docs.godotengine.org/en/latest/classes/class_kinematicbody.html
- http://docs.godotengine.org/en/latest/classes/class_physicsbody.html#class-physicsbody

**Comment by eon-s** [comment]
@akien-mga move is broken, layer/mask wise #7227 .

**Comment by reduz** [comment]
this is done, other bugs remain but this can be closed
