### ISSUE TITLE
Exported windows application named "Godot Engine" instead of Product name set in export settings

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#94343]
### Tested versions

4.3b3, not in 4.2.x

### System information

Windows 10

### Issue description

There seems to have been a regression regarding the naming of exported applications/games in 4.3 on windows. 

Previously exported projects were correctly assigned the set Product name, but now it is just set to "Godot Engine". The name can be seen by right-clicking the game when it's running in the task bar for example, and multiple other places in the OS when it's referring to the application.

Running app exported with 4.2.x (correct)
![Screenshot 2024-07-14 120216](https://github.com/user-attachments/assets/c996b3c4-9f3f-466c-aeae-12e7689ba084)

App exported with 4.3.b3 (incorrect name)
![Screenshot 2024-07-14 115711](https://github.com/user-attachments/assets/182ca6aa-914b-499a-86cf-6d77ac2f48b9)
![Screenshot 2024-07-14 115642](https://github.com/user-attachments/assets/877fe1bc-d92d-40d6-b7a2-99a63628c748)

### Steps to reproduce

- Export a project to windows with a product name set.
- Inspect running exported app by right-clicking the icon in the task bar and see it's named Godot Engine instead of the set product name

### Minimal reproduction project (MRP)

I do not think this is project specific.

**Comment by Calinou** [comment]
Is rcedit configured in your Editor Settings? Editor settings are split per minor version since 4.3.

**Comment by lostminds** [comment]
> Is rcedit configured in your Editor Settings? Editor settings are split per minor version since 4.3.

Yes, it's configured and appears to run fine on export. As you can see the icon is set correctly. And inspecting the properties of the .exe file I can see that the other properties RCEdit sets seem to be in there as well, including the Product name:

![Screenshot 2024-07-14 190629](https://github.com/user-attachments/assets/50255732-4fb8-4c0a-8a4b-e28d2c357045)

However, for some reason this information is not used by windows as shown in the previous screenshots. So maybe it's being overridden by some other properties set elsewhere? Or for some reason these set properties are incorrectly formatted or named?

**Comment by KoBeWi** [comment]
Could be related to #89068

**Comment by lostminds** [comment]
I think I found what is causing the issue, based on [this](https://stackoverflow.com/questions/70667770/godot-rename-application-name-used-by-file-explorer-in-open-with-menu) it seems that at some point Windows for some reason copies two entries from the file version info into the system registry to:
`HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache\<PATH_TO_EXE>.ApplicationCompany` and `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache\<PATH_TO_EXE>.FriendlyName`
And if this key is set the .FriendlyName is used by Windows instead of the Product Name information in the .exe file. The problem is that apparently this registry entry doesn't seem to update on changes to the .exe file it refers to (including removing/moving it). 

So if you make a first build with the default "Godot Engine" product name (or description?) this will be copied to the .FriendlyName registry entry. But if you then make a new build with a different product name, but using the same .exe path, the registry entry will be unchanged. And result in the issue above. 

If you remove the registry entry Windows then falls back and reuses the application set Product name. So, at least the issue shouldn't follow built .exe files to any other systems, since it's a problem local to the system. And therefore this is a much smaller issue.

**Comment by akien-mga** [comment]
> Could be related to #89068

Sounds similar indeed, so likely also a regression from #85905.
