### ISSUE TITLE
How to add auto smoothness in Godot in Android 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#94342]
### Tested versions

4.1.2

### System information

Mobile / Android

### Issue description

How to add auto smooth to objects in Godot 4 on an Android device As in Blender, because on Android there is no auto smoothness option in any 3D modeling application 

### Steps to reproduce

‌nothing

### Minimal reproduction project (MRP)

‌nothing

**Comment by AThousandShips** [comment]
This isn't the place to ask support questions, please use the other [community channels](https://godotengine.org/community/) instead

**Comment by AThousandShips** [comment]
This isn't the first time you've opened reports here for support questions and been told not to, please do not do this again

**Comment by Sorshx** [comment]
Sorry, I will stop doing that, thank you
