### ISSUE TITLE
Missing: "Always Close Output on Stop"

### ISSUE THREAD

**Issue by eimfach** [godotengine/godot#94350]
### Tested versions

- Reproducible in v4.3.beta3.official [82cedc83c]
- Not reproducible in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.beta3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (Advanced Micro Devices, Inc.; 31.0.24026.1002) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

Going from 4.2.2 to current 4.3.beta3 I can not find the option in _Editor Settings > Run > Always Close Output on Stop_ (also _Always Open Output on Play_) anymore.

4.2,2:
![Screenshot 2024-07-14 151452](https://github.com/user-attachments/assets/6d408262-3e59-47f6-9a57-2ae3a3946d62)

4.3.beta3:
![Screenshot 2024-07-14 151520](https://github.com/user-attachments/assets/9322aba5-d01a-484a-b3b9-65ce80a961c7)

### Steps to reproduce

Go to Menu then _Editor Settings > Run_

### Minimal reproduction project (MRP)

[editor_settings_output_regression.zip](https://github.com/user-attachments/files/16227598/editor_settings_output_regression.zip)

**Comment by timothyqiu** [comment]
These options are replaced with Action on Play and Action on Close in Run > Bottom Panel.

**Comment by eimfach** [comment]
Can confirm, closing
