### ISSUE TITLE
[4.3.beta3] NavigationAgent not working properly when baking at runtime. 

### ISSUE THREAD

**Issue by Jaete** [godotengine/godot#94358]
### Tested versions

- Reproduced in: v4.3.beta3 (Failing); v4.2.2.stable (OK)

### System information

Godot v4.3.beta3.mono - Ubuntu 24.04 LTS 24.04 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 550 Series (RADV POLARIS11) - AMD Ryzen 7 PRO 1700 Eight-Core Processor (16 Threads)

### Issue description

NavigationAgent2D is completely ignoring the new hole on the NavigationMesh when baked at runtime. It's like isn't updating or something.

I've tested both on C# and GDScript. Both are with the same problem. I'm not using the NavigationServer or anything, just the expected procedure to bake at runtime. Not using NavigationLayers on Tileset too. Also not trying to merge Meshes. Just a simple hole with a StaticBody2D CollisionPolygon nested at the NavigationRegion.

The StaticBodies are just to make the hole on the mesh, they're in different collision layers, as isn't intended to collide with player.

I've also tested with Polygon2D. Same problem.

### **The pre-baked staticBody works just fine.**
![image](https://github.com/user-attachments/assets/7c58e678-5ea6-4032-975a-480aebea829e)
### **The baked at runtime doesn't.**
![image](https://github.com/user-attachments/assets/376a11ea-5a79-4aca-b78c-0a139fd15f77)
### **Before baking:**
![image](https://github.com/user-attachments/assets/b5e79af7-4863-4214-85ca-5912ba63aecd)
### **I've baked the second StaticBody on the engine and now works fine.**
![image](https://github.com/user-attachments/assets/dd15fbb7-929d-45e3-b22c-b0378802e265)

### Steps to reproduce

Just open the project on both versions and see the difference. There's a pre-baked hole and the 4.3 works just fine. So it can be something when the rebaking occurs.

You just have to click on the "bake" button, the project is already set to bake the other StaticBody when you do.

Make sure to check the debug visibilities.

### Minimal reproduction project (MRP)

Here's a MRP i've made just for the issue. (Technically would be N/A here, but I've spared you the work to set this scenario.)

[testNav.zip](https://github.com/user-attachments/files/16228439/testNav.zip)

**Comment by iakihsoug** [comment]
Great job! I encountered the same issue an hour ago.
