### ISSUE TITLE
`CSGShape3D` wireframe is still visible when disabling gizmos

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#94375]
### Tested versions

v4.3.beta.custom_build [97b8ad1af]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

`CSGShape3D` displays a wireframe when selected. However, when `use_collision` is true, it will always display the wireframe with no way to disable it. It doesn't hide when I deselect, disable the CSG gizmo at `View > Gizmos > CSGShape3D` or global gizmo view.

### Steps to reproduce

* Add a CSG node.
* Enable  `use_collision`.
* Disable gizmos at `View > Gizmos > CSGShape3D` or `Perspective > View Gizmos`.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87919.
