### ISSUE TITLE
Help > Copy System Info from Godot gives me incorrect OS version

### ISSUE THREAD

**Issue by henkehedstrom** [godotengine/godot#94370]
### Tested versions

Reproducible in Godot 4.2.2.stable

### System information

Windows 11 

### Issue description

When I use "Help > Copy System Info" like you recommend I get: "Godot v4.2.2.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700F (20 Threads)"

However, I have Windows 11 not Windows 10. Attached a screenshot of what I get from winver
![image](https://github.com/user-attachments/assets/d397b2fa-6d59-4a35-a3fa-3120ad707c9f)

### Steps to reproduce

1. Help > Copy System Info

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
The actual version number of Windows 11 is still 10.something. It's like Windows 7; it wasn't actually the seventh version of Windows. Instead, it was… Windows 6.1.
