### ISSUE TITLE
Alignment setting in draw_string doesn't do anything

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#94394]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Newest MacOS / Mac mini M1

### Issue description

I'm trying to align a string drawn in `_draw` using `HORIZONTAL_ALIGNMENT_LEFT` etc but none of them has any effect.

### Steps to reproduce

Paste the code from the MRP field. This is what it looks like on my end, as it can be seen all three strings are aligned to the left despite the different settings:
![image](https://github.com/user-attachments/assets/0a9f3223-9784-4f43-9d3f-c18a44a5293a)

### Minimal reproduction project (MRP)
Edit: whoops it looks like the MRP field doesn't support code tags?

Just paste this into a freshly opened project into an empty Node2d:
`extends Node2D

var default_font
var default_font_size

func _ready():
	default_font = ThemeDB.fallback_font
	default_font_size = ThemeDB.fallback_font_size

func _process(_delta):
	queue_redraw()

func _draw():
	draw_string(default_font, Vector2(64, 100), "Hello LEFT", HORIZONTAL_ALIGNMENT_LEFT, -1, default_font_size)
	draw_string(default_font, Vector2(64, 200), "Hello RIGHT", HORIZONTAL_ALIGNMENT_RIGHT, -1, default_font_size)
	draw_string(default_font, Vector2(64, 300), "Hello CENTER", HORIZONTAL_ALIGNMENT_CENTER, -1, default_font_size)
`

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/80163

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
