### ISSUE TITLE
Panel widths are not loaded upon opening/creating projects

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#9439]
Editor layouts do save the widths of each panel correctly, but when opening up a project they don't seem to be applied. For the saved width information to be loaded you must manually load the layouts upon opening the project each time. Even saving the layout as Default doesn't fix this. This happens on both 2.1.3 and 3.0.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by homer666** [comment]
Completely forgot about this issue. It still happens very rarely under circumstances I haven't been able to discern, but a fix had been implemented a while ago, which works just fine otherwise. Tested on 3.0.2-stable.

Also, I do recall that this problem was occurring on my Linux Mint 18.2 Cinnamon partition, but **not** on a Windows 10 partition on the same machine. This went for both 2.1.3 and whatever version of 3.0-alpha I was using at the time. I really should've mentioned this in the OP...

Regardless, this is old and irrelevant now, so closing.
