### ISSUE TITLE
Font hinting causing chunky fonts

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9441]
godot 3.0 on linux.

![chunky_fonts](https://user-images.githubusercontent.com/11153232/27677133-b9e32d3c-5cef-11e7-9241-67ddd99a7b95.png)

Discussing with Akien:
Most likely we need to initialize a freetype parameter that changed its default value. If the editor is not affected, it might be that it inits it properly, but not the non-tools runtime.

Probably something connected with this commit: https://github.com/godotengine/godot/commit/0f8cc0fa5b6bc53b81fbf3fe52c15be987dfd7c2

**Comment by supagu** [comment]
Akin also suggested building against builtin_freetype=yes to see if this affects it. 

I am running Manjaro, arch linux running freetype2 2.8-2
fontconfig 2.12.3-1

**Comment by supagu** [comment]
building with builtin_freetype=yes did not result in any difference - problem still exists

**Comment by bojidar-bg** [comment]
@supagu I assume you aren't using viewport scaling, are you?

**Comment by supagu** [comment]
Test available here:
https://drive.google.com/open?id=0B_nQZvJoqbFmQmhvcVpxVXpfNm8

I just setup a new project add a rich text field and hts chunky. It views chunky in the editor window, but the editor itself does not have chunky fonts.

Viewport scaling? Not unless its a default option.

**Comment by volzhs** [comment]
I'm not sure but is this related?
https://github.com/godotengine/godot/blob/master/editor/editor_fonts.cpp#L88

**Comment by reduz** [comment]
No.. i saw this, I think it might be my fault when added uv clipping for
drawing texture regions

**Comment by akien-mga** [comment]
> Test available here:
https://drive.google.com/open?id=0B_nQZvJoqbFmQmhvcVpxVXpfNm8

I confirm it looks bad on Mageia 6 x86_64, latest master build against system Freetype 2.7.1.

> No.. i saw this, I think it might be my fault when added uv clipping for drawing texture regions

Ah good, so it's not FreeType.

**Comment by kekie1** [comment]
I'm having this same issue in 2.1.3.
