### ISSUE TITLE
match expression is not working, where the if expression is working

### ISSUE THREAD

**Issue by hothex** [godotengine/godot#94418]
### Tested versions

- Reproduceable in Godot_v3.5.3-stable_win64.exe
- Godot_v3.6-rc1_win64.exe
- Godot_v3.6-beta3_win64.exe

### System information

Windows 11 - GLES3

### Issue description

The comparsion value in a match expression is changed by to_json and parse_json in a way that the match expression fails.
I put an if clause with the same logical expression in front and it is executed correctly.
After all the testing and searching I'm not sure if this is a bug per se. The issue for me is that it is very hard to debug and discover. A stricter strong typing directive would also help in this case. If there are expressions, which are very strict about types, it would be helpful that the debugger/the UI show the details.

#######Workaround:
As a workaround (Both work, I tried):
1. Either use "if, else-if" expression, instead of "match"
2. or cast the expected datatype (here Integer) in the deserialization function like that:
`buff.calc_type = int(_dict_2["calc_type"])`
The second is better imo because the datatype and the comparsion is exactly defined if you cast it as the expected datatype.

[MainGame.tscn - AgainstAllOdds - Godot Engine 2024-07-16 06-38-14.zip](https://github.com/user-attachments/files/16243207/MainGame.tscn.-.AgainstAllOdds.-.Godot.Engine.2024-07-16.06-38-14.zip)

```gdscript
#########buff.calc_type is 0
#########BuffDebuff.MODIFICATION.ADD is 0

func register_buff(buff:BuffDebuff):
    if buff.calc_type == BuffDebuff.MODIFICATION.ADD:
        print ("Hi") #######<--- is executed

    match buff.calc_type:
        BuffDebuff.MODIFICATION.ADD:
            total_modification_add += buff.value #<--- is **NOT** executed
        BuffDebuff.MODIFICATION.MULTIPLY:
            total_modification_multiply += buff.value / 100.0
        BuffDebuff.MODIFICATION.MULTIPLY_TOTAL:
            total_modification_multiply_total += buff.value / 100.0
```

### Steps to reproduce

It is the parse_json and to_json. It does something that is not debugable for me. It does not show any difference. Something happens in the background. If you substitute _dict_2 with _dict_buff you bypass the to_json and parse_json and it works. For  me nothing changes in the debug window. I can not observe that something is wrong with the datatypes.

This is the MRP:
[MRP_match.zip](https://github.com/user-attachments/files/16250272/MRP_match.zip)
Go to src/Definitions/Attribute.gd for the match buff.calc_type
The MRP is "F5" able. And then you click the button.

The important code is in main.gd:

```
extends Node2D


# Declare member variables here. Examples:
# var a: int = 2
# var b: String = "text"
var _dict_buff:Dictionary = {}
var _dict_2:Dictionary = {}

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	_dict_buff["some_number2"] = 0.9
	_dict_buff["id"] = String("hoijuhapsdofhjapf")
	_dict_buff["calc_type"] = 0
	_dict_buff["loosing_my_mind"] = true
	_dict_buff["some_number"] = 0.9
	
	var _buffer_fake_save:String = to_json(_dict_buff)
	
	_dict_2 = parse_json(_buffer_fake_save)
	
	
	

func _on_Button_button_up() -> void:
	var _item:ItemBase = load("res://src/dummy_ItemBase.tscn").instance()
	
	#Simulation of the load game deserialization
	var buff:BuffDebuff = BuffDebuff.new()
	buff.calc_type = _dict_2["calc_type"] ##<---- Bypass the (de)serialization by using _dict_buff and it works
	var stat:Stat = Stat.new()
	
	for _stat in _item.rolled_stats:
		_stat.buff = buff
		
		
	add_child(_item)
```

### Minimal reproduction project (MRP)
Here is a MRP to observe the bug. Go to src/Definitions/Attribute.gd for the match buff.calc_type. The MRP is "F5" able. And then you click the button.

[MRP_match.zip](https://github.com/user-attachments/files/16250284/MRP_match.zip)

_Bugsquad edit:_ Fix formatting.

**Comment by dalexeev** [comment]
@hothex Please use three backticks to format code blocks:

    ```gdscript
    Your GDScript code here...
    ```

Regarding the issue, please check the exact type of the expression. Note that `match` [uses a stricter comparison](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#match) than the `==` operator. For example, `match` treats `1` and `1.0` as different, while the `==` operator treats them as equal.

**Comment by hothex** [comment]
> @hothex Please use three backticks to format code blocks:
> 
> ```
> ```gdscript
> Your GDScript code here...
> ```
> ```
> 
> Regarding the issue, please check the exact type of the expression. Note that `match` [uses a stricter comparison](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#match) than the `==` operator. For example, `match` treats `1` and `1.0` as different, while the `==` operator treats them as equal.

Thank you for the hint with float int. I checked it. Here is the thing:
I set the value of the buff.calc_type in the resource. I created an enum export property of the same type I compare it to:
'''match buff.calc_type: #<--- same type (enum) like BuffDebuff.MODIFICATION.ADD
        BuffDebuff.MODIFICATION.ADD:
'''
Thus the type of the buff.calc_type should be exactly the same type: Here some screenshots to show what I mean:
Here the dropdown shows ADD, this is a value of the enum MODIFICATION:
![Screenshot 2024-07-16 093225](https://github.com/user-attachments/assets/50a91151-6d51-4ec4-83e4-9816d137e8d7)

Here is the code of the property declaration:
![Screenshot 2024-07-16 092921](https://github.com/user-attachments/assets/268e82b5-5507-4cba-8d16-625f9b78b92d)

Additionally I checked the values in the debugger if there is a type issue. But I'm not sure how to interpret the enum to dictionary difference and impact:
![Screenshot 2024-07-16 092824](https://github.com/user-attachments/assets/f84a68b5-18ea-4856-85a9-60d01213d0cb)

I will continue to check if there is some other modification to the buff resource happening somewhere in the stack frames.

**Comment by hothex** [comment]
Holy Lord Baby Jesus. Partytime. Three hours of searching and it paid off:
1. I imitated the whole stack frame calls. Did not help.
2. The error was chased to the save game serialization - deserialization. The MRP now also includes this part in a faked version

It is the parse_json and to_json. It does something that is not debugable it does not show the 0.0 I mean. Something happens in the background. If you substitute _dict_2 with _dict_buff you bypass the to_json and parse_json and it works. For the me nothing changes in the debug window. I can not observe that something is wrong with the datatypes.

This is the MRP:
[MRP_match.zip](https://github.com/user-attachments/files/16250272/MRP_match.zip)


The important code is in main.gd:

```
extends Node2D


# Declare member variables here. Examples:
# var a: int = 2
# var b: String = "text"
var _dict_buff:Dictionary = {}
var _dict_2:Dictionary = {}

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	_dict_buff["some_number2"] = 0.9
	_dict_buff["id"] = String("hoijuhapsdofhjapf")
	_dict_buff["calc_type"] = 0
	_dict_buff["loosing_my_mind"] = true
	_dict_buff["some_number"] = 0.9
	
	var _buffer_fake_save:String = to_json(_dict_buff)
	
	_dict_2 = parse_json(_buffer_fake_save)
	
	
	

func _on_Button_button_up() -> void:
	var _item:ItemBase = load("res://src/dummy_ItemBase.tscn").instance()
	
	#Simulation of the load game deserialization
	var buff:BuffDebuff = BuffDebuff.new()
	buff.calc_type = _dict_2["calc_type"] ##<---- Bypass the (de)serialization by using _dict_buff and it works
	var stat:Stat = Stat.new()
	
	for _stat in _item.rolled_stats:
		_stat.buff = buff
		
		
	add_child(_item)
```

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/42224.

Consider adding type hints to your exported variables to avoid this, or cast the `match` value  to `int()` to ensure match's strict type equality works.

**Comment by hothex** [comment]
Impressive feedback time again. Thank you.
