### ISSUE TITLE
dedicated_server feature tag does not enable GODOT_SERVER preprocessor define

### ISSUE THREAD

**Issue by warent** [godotengine/godot#94414]
### Tested versions

Godot v4.3.beta3.mono

### System information

Godot v4.3.beta3.mono - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU (NVIDIA; 31.0.15.4680) - 12th Gen Intel(R) Core(TM) i7-12650H (16 Threads)

### Issue description

When running an instance with the `dedicated_server` feature tag, it runs headless as expected. However, the C# GODOT_SERVER preprocessor define does not work. I would expect that to be enabled.

### Steps to reproduce

1. Create C# project
2. Configure run instance with `dedicated_server` feature tag
3. Run some code with `#if GODOT_SERVER`
4. Observe that code is never reached

### Minimal reproduction project (MRP)

![image](https://github.com/user-attachments/assets/87ad654b-44fa-4f8f-9786-8f297f213c60)
[preprocessorrepro.zip](https://github.com/user-attachments/files/16241068/preprocessorrepro.zip)

**Comment by warent** [comment]
I've been looking into the engine and think I have a better understanding of the problem now.
* There is no such `GODOT_SERVER` preprocessor define, so the docs here seem to be incorrect: https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_features.html#full-list-of-defines
* Feature tags like `dedicated_server` this are only passed into the instance _after_ build via OS environment `GODOT_EDITOR_CUSTOM_FEATURES`, so there can be no `GODOT_SERVER` define based on these tags.
* Furthermore, in order to support a `GODOT_SERVER` compiler define based on `GODOT_EDITOR_CUSTOM_FEATURES`, we would have to compile a separate executable for _every_ run instance which is currently not done.

I'd be happy to help with trying to apply a patch for this, but given the above, I think it requires architectural decisioning. Let me know what y'all think!

**Comment by warent** [comment]
@AThousandShips I'm not sure if anyone will see my comments above so just tagging someone here to make sure it's on the Godot team's radar!

**Comment by AThousandShips** [comment]
Please don't tag random people, it helps no one, I'll tag this but it would have been processed regardless

**Comment by warent** [comment]
> Please don't tag random people, it helps no one

Hmm not to be difficult, I don't think that's mentioned in the contributor guidelines, which is confusing to me. (Also for what it's worth, I didn't consider you a "random person" here)

My communication style is very different. I always appreciate a ping (at work or outside!) because I can just look at it later at my earliest convenience. So, to me, it's just a good measure of bridging communication (overcommunication is better than gaps).

Now I understand it looks like that's not how things are done here, which is okay, it's just not really clear or obvious to me. It's very possible I just missed it though if it is mentioned or clarified somewhere. Otherwise maybe I can create a ticket suggesting updating communication guidelines somewhere?

**Comment by AThousandShips** [comment]
I wasn't admonishing or criticizing, just advising, and that issues will get checked out as soon as they can, this was opened less than a day ago so there's no rush. And people already have things on their plate and random pings aren't always useful, that's all my point is. This isn't a rule or anything, just an observation on the process of triage.

So no worries, just stating my point and some constructive feedback on the process from someone who has experience with the triage process

**Comment by warent** [comment]
Understood! Thank you for the feedback and your help 🙏

**Comment by raulsntos** [comment]
Regarding the `GODOT_SERVER` preprocessor define, AThousandShips is correct. Server was a platform in Godot 3.x but was removed in 4.0 (see https://github.com/godotengine/godot/pull/64846 for the removal of the platform from the .NET module). So the documentation is outdated.

Since you also mention feature tags. Rather than using `#if`, you can check for feature tags using the [`OS.HasFeature`](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-has-feature) API.

**Comment by aldocd4** [comment]
> Regarding the `GODOT_SERVER` preprocessor define, AThousandShips is correct. Server was a platform in Godot 3.x but was removed in 4.0 (see #64846 for the removal of the platform from the .NET module). So the documentation is outdated.
> 
> Since you also mention feature tags. Rather than using `#if`, you can check for feature tags using the [`OS.HasFeature`](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-has-feature) API.

Hello, I have the same issue here, this solution is not viable.
I will make it simple: I'm building a MMORPG using Godot RPC, and I don't want to share the server-side code. So I have `#if GODOT_SERVER || TOOLS || DEBUG` on almost all my server-side files and RPC functions. 

When exporting a build, the assembly is built using one of the VS configuration generated by godot (Debug, ExportDebug, ExportRelease). You can't add a custom preprocessor in Godot (https://github.com/godotengine/godot/blob/e684d126ed605899267ee37cc143f072b93b4d04/modules/mono/godotsharp_dirs.cpp#L58).

The solution I use right now is to configure the C# project manually before doing exporting the server build.
![image](https://github.com/user-attachments/assets/d01c1832-3cfa-44aa-affe-967855d8ca5f)

It works, but I think that we should have an easier way to add this preprocessor on godot side when exporting (I will soon build the server/client builds using a CI for example, I don't know yet how I'm gonna do that).

**Comment by AThousandShips** [comment]
I think we need to separate the question of allowing a feature like this (which in an enhancement, covered by https://github.com/godotengine/godot-proposals/issues/10028) and the now obsolete and completely unrelated `GODOT_SERVER` define that has nothing to do with the dedicated server mode as explained above

So *this* issue is about how the documentation is outdated, not about the broader feature, that's covered by that proposal
