### ISSUE TITLE
[RFE] Animation Player emit events

### ISSUE THREAD

**Issue by ficoos** [godotengine/godot#9442]
Allow adding points in an animation that will emit a signal from the player. This will allow you to attach code to be invoked at certain points in the animation.

Example of feature from Spline 2D:
https://youtu.be/gPj9ZkSb0gU

**Comment by bojidar-bg** [comment]
Well, isn't this exactly what "call_func" tracks do? You can potentially use them to call `emit_signal` as well, if that's what you want... (I use them to call `queue_free` at the end of an explosion animation, for example)

**Comment by ficoos** [comment]
I actually didn't know about call_func tacks. Still this means that the signals are not part of the animation but part of another node this means that you can't reuse the animation player without having each node using the animation. It's actually an inverse of the requested feature. You don't want the animation tightly coupled with the node. I guess I could add a script to the animation player node itself and add signals there and have it emit it's own signals for the same effect.

I guess it's a very minor QOL upgrade in that case. Can be closed if people don't think it's worth the work.

Sorry for the trouble and thanks for the response.

**Comment by bojidar-bg** [comment]
@ficoos Well, if you can arrange for someone to call `add_user_signal` on the animationplayer, or (even better) have a script on the animation player which uses the `signal` keyword to register the signals, I think it gets pretty much the same.

The question here is should we bother to support this, or is it too complex to be worth the gain.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*
