### ISSUE TITLE
Passing sampler from array as parameter to non-built-in function throws error.

### ISSUE THREAD

**Issue by operation404** [godotengine/godot#94447]
### Tested versions

Reproducible in 4.3 beta3 and 4.2.1 stable.

### System information

Godot v4.3.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.5612) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

When writing a shader function that takes a sampler as an argument, calling that function while indexing into an array of samplers results in an error. The shader seems to still work fine, as the error only results in continuing the current loop iteration of the shader parsing. The error in question is triggered at line 5550 of servers/rendering/shader_language.cpp.

It seems that the shader parser expects sampler function arguments to only ever be referred to by variable identifiers representing a single sampler and not elements of an array of samplers. In my experience this error only ever triggers for user-defined functions, not built-ins.

### Steps to reproduce

```glsl
shader_type canvas_item;

uniform sampler2D textures[1];

vec4 sampleTex(sampler2D tex, vec2 uv) {
    return texture(tex, uv);
}

void fragment() {
    COLOR = sampleTex(textures[0], UV); 
}
```

### Minimal reproduction project (MRP)

https://github.com/operation404/ShaderSamplerArrayBugMRP

**Comment by clayjohn** [comment]
Could you add the text of the error to your report?

**Comment by Calinou** [comment]
> Could you add the text of the error to your report?

Here it is:

```
servers/rendering/shader_language.cpp:5550 - Condition "n->type != Node::NODE_TYPE_VARIABLE" is true. Continuing.
```
