### ISSUE TITLE
The default Toggle Bottom Panel shortcut also sends an extra keystroke "j"

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#94456]
### Tested versions

v4.3.beta2.official [b75f0485b]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

This is the Editor Settings > Shortcuts, default key `ctrl+j` to toggle the bottom panel.
If you are editing a script and press it, the bottom panel will toggle but in addition the character "j" will be inserted into the script.
![image](https://github.com/user-attachments/assets/5b6333ad-6de8-49aa-8d6c-adc6b5988ce5)

Seems to be a problem with any key change I tried.

### Steps to reproduce

na

### Minimal reproduction project (MRP)

na

**Comment by kitbdev** [comment]
- related https://github.com/godotengine/godot/issues/94032

Can you reproduce in 4.3 beta 3?
I can't reproduce (Godot v4.3.beta (97b8ad1af) - Windows 10.0.22631).

**Comment by wyattbiker** [comment]
Updated to V4.3 Linux. No longer an issue. Thanks.
