### ISSUE TITLE
`AnimationMixer` signal don't emit when using custom timeline and time scale stretch

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#94459]
### Tested versions

v4.3.beta.custom_build [97b8ad1af0f2b4a216f6f1263bef4fbc69e56c7b]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

Animation nodes in state machines have a `use_custom_timeline` and a `stretch_time_scale` that lets scale the animation to a custom length.

However, it breaks the `animation_finished` signal. Depending on the custom length I set, it becomes frame-dependent emitting on a 160hz monitor but not on a 60hz when the values are close, eg original length 0.4667 and custom length 0.4, or it doesn't emit at all the higher the difference, which in my tests, a few decimal places lower or higher.

### Steps to reproduce

* In the MRP, "rotate_left" and "rotate_right" play and then transition to each other.
* Run. It should be printing "Animation finished rotate_right" every time "rotate_right" finishes but it doesn't work.
* Go to the state machine in the `AnimationTree` in "main.tscn", select the "rotate_right" animation node, and disable `use_custom_timeline`
* The signal now works and it prints.

### Minimal reproduction project (MRP)

[animation-signals.zip](https://github.com/user-attachments/files/16258920/animation-signals.zip)

**Comment by TokageItLab** [comment]
I think it is a floating point issue, similar to the problem I mentioned in https://github.com/godotengine/godot/pull/94420. For the code related to Animation, we may need a Math method for comparisons that takes into account the error of the double.
