### ISSUE TITLE
GDScript: Not all code paths return a value, despite all code paths returning a value

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#94464]
### Tested versions

Latest 4.3 beta, haven't tried earlier but it should be present in all versions

### System information

Linux

### Issue description

```gdscript
static func dummy_function() -> int:
	var test_array: Array[int] = [5,7,9] #Practically this is this function's input parameter instead of being declared here

	if (test_array.size() == 0):
		return -1

	for picked_int: int in test_array:
		return 0

	#It never reaches here, yet demands it
	return -1

```

If I remove the above last 2 lines, it gives the error:
`Not all code paths return a value` but it's obvious that it can never reach there.
With a static compiler (e.g. Rust) it would detect this, but here it forces me to add code which will never run.

In a real example in my project, the function doesn't return int, but a Dictionary, so I have to do:
```gdscript
var empty_dictionary: Dictionary
return empty_dictionary
```

where it should be

``` 
```

### Steps to reproduce

Copy-paste the above code in any project, and run it

### Minimal reproduction project (MRP)

Not needed, copy-paste the above code
[mrp.zip](https://github.com/user-attachments/files/16261953/mrp.zip)

**Comment by dalexeev** [comment]
See also:

* #71763
* #86521
* #92341
* godotengine/godot-proposals#8994

Currently, GDScript does not even analyze always true/false conditions in control flow. Your example requires an even higher level of static analysis:

1. Neither condition is always true/false, you have two interrelated opposite conditions. The presence of a return value is only exhaustive if we obtain a guarantee that `test_array` does not change between these points.
2. To check the above we need a complex analysis of constancy, local assignments, passing reference types to a function, etc.
3. GDScript needs to somehow know the relationship between checking the array size and iteration (that the `return` in the loop will be achieved if `test_array` is not empty).

Thus, this is not a bug, but a limitation. To request a feature, you should open a proposal/discussion instead.

**Comment by wyattbiker** [comment]
I don't think comparing to Rust is a good paradigm. Maybe better to C#.
