### ISSUE TITLE
AnimationPlayer has both playback_* and playback/* properties

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9446]
**Operating system or device - Godot version:**
All, current master branch.

**Issue description:**
AnimationPlayer has two "Playback" categories in the inspector:
![spectacle ns2442](https://user-images.githubusercontent.com/4701338/27700308-81bd819c-5cfd-11e7-9077-30153043c4f7.png)
It's due to it have properties prefixed by `playback_` (new style properties) and others by `playback/` (old style properties):
```
playback_process_mode
playback_default_blend_time
playback/active
playback/play
playback/speed
```

It should probably be fixed by making the `playback/` stuff use the new style, but it apparently implies messing around with SceneStringNames.

**Comment by akien-mga** [comment]
Probably all those SceneStringNames occurrences should be fixed too:
```
$ rg StaticCString::create\\\(.*/.*\\\)
scene/scene_string_names.cpp
48:     shader_unshaded = StaticCString::create("shader/unshaded");
49:     shading_mode = StaticCString::create("shader/shading_mode");
145:    transform_pos = StaticCString::create("transform/pos");
146:    transform_rot = StaticCString::create("transform/rot");
147:    transform_scale = StaticCString::create("transform/scale");
161:    play_play = StaticCString::create("play/play");
181:    playback_speed = StaticCString::create("playback/speed");
182:    playback_active = StaticCString::create("playback/active");

modules/gdscript/gd_script.cpp
1875:   strings._script_source = StaticCString::create("script/source");
```

**Comment by akien-mga** [comment]
Some other related old-world properties:
```
$ rg rect/
editor/plugins/canvas_item_editor_plugin.cpp
2863:                                           AnimationPlayerEditor::singleton->get_key_editor()->insert_node_value_key(ctrl,"rect/size",ctrl->get_size());
3600:           editor_data->get_undo_redo().add_do_property(child, "rect/size", texture_size);
```

**Comment by reduz** [comment]
the animations one are alright, as it uses a custom way to get/set. The others i´m fixing but many of them are not accessible as properties anyway.
