### ISSUE TITLE
No warning given for FSR 1 on the mobile renderer like there is for FSR 2

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#94463]
### Tested versions

4.2

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000 - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) () - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

FSR 1.0 does not work in the mobile renderer, I presume this is known and intended.

When I enable FSR 2 on a mobile renderer project, I get a little pop up in the editor about how it is only compatible with the forward+ renderer, as well as an error in the output tab. But such warnings are missing for FSR 1. I presume the same thing applies for the compatibility renderer.

### Steps to reproduce

1. make a new project with mobile renderer
2. change the project settings to enable FSR 1
3. see no warning pop up and no errors in the output tab
4. change the project settings to enable FSR 2
5. see the warning pop up and and no errors in the output tab

### Minimal reproduction project (MRP)

Easy to reproduce from a new empty project

**Comment by akien-mga** [comment]
CC @Calinou
