### ISSUE TITLE
Getting False Positive "..Invalid call. Nonexistent function..." when running an EditorPlugin

### ISSUE THREAD

**Issue by Lking03x** [godotengine/godot#94499]
### Tested versions

4.2.2 stable

### System information

Godot v4.2.2.stable - Windows 10.0.22621 - GLES3 (Compatibility)

### Issue description

The add-on instantiate `AddonControl` (which inherits from `Control`) and add it to the dock. `AddonControl` define a `_ready` and `initialize` function, the first calls the later, in the source.

When running the `AddonControl` scene in via (F6) the scene works properly, but running the add-on triggers `res://addons/BugIsHere/addon_main.gd:17 - Invalid call. Nonexistent function 'initialize' in base 'Control (AddonControl)'.`

The Facts:
- `.has_method("initialize")` returns true on the instance of `AddonControl`
- The `_ready` function seems to not be called at all

See "BUG" comments in the project

### Steps to reproduce

Enable the plugin

### Minimal reproduction project (MRP)

[BugNonExistingMethod.zip](https://github.com/user-attachments/files/16279674/BugNonExistingMethod.zip)

**Comment by Lking03x** [comment]
Oddly setting the texture directly in the `_enter_tree` function works (`_ready` is never called!)
```gdscript
addon_control.get_node("TextureRect").texture = AddonUtils.get_first_image_texture()
```

**Comment by huwpascoe** [comment]
The other gdscript files need to start with `@tool` to run in the editor.

**Comment by Lking03x** [comment]
Thanks a lot.
It also solved the error about "Nonexistent function"
