### ISSUE TITLE
Inverted shadows on web export when running in Safari

### ISSUE THREAD

**Issue by jrrmt** [godotengine/godot#94515]
### Tested versions

- Reproducible in: 4.3beta3

### System information

Godot v4.3.beta3 - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

When running a web export on Safari, both on MacOS and iOS, shadows/lights seem to be inverted.

Example of what I is expected, and happens when running in the editor, firefox and chrome:
![CleanShot 2024-07-18 at 18 05 42@2x](https://github.com/user-attachments/assets/00406001-92fa-4863-af8b-d5e880a60b58)

What happens on Safari:
![CleanShot 2024-07-18 at 18 05 57@2x](https://github.com/user-attachments/assets/c31235d3-0c38-4780-8680-9755eca244b5)

### Steps to reproduce

Run the web export of the MRP on Safari.

### Minimal reproduction project (MRP)

[shadow-safari.zip](https://github.com/user-attachments/files/16286753/shadow-safari.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/93537 (possible duplicate, likely due to the same cause).
