### ISSUE TITLE
macOS: App signing fails when using C#

### ISSUE THREAD

**Issue by LeonardoDemartino** [godotengine/godot#94516]
### Tested versions

Reproductible in: Godod 4.3.beta3.mono, Godod 4.3.beta2.mono

### System information

macOS 14.5, Godod 4.3.beta3.mono

### Issue description

Codesign fails as soon as you add a .cs (c#) script:

editor/export/editor_export_platform.h:179 - Code Signing: Code signing failed, see editor log for details.
codesign (../project.app/Contents/Resources/data_project_macos_x86_64/./createdump):

This makes impossible to upload macOS apps that use C# to the App Store.

### Steps to reproduce

1) Create a new Godot project.
2) Configure export template for macOS.
3) Export an empty project without adding any .cs. It builds and run fine.
4) Add a .cs script anywhere in the project.
5) Building fails with the error mentioned above.

### Minimal reproduction project (MRP)

[macossign 2.zip](https://github.com/user-attachments/files/16288468/macossign.2.zip)

**Comment by bruvzg** [comment]
> This makes impossible to upload macOS apps that use C# to the App Store.

- App Store require sandboxing, it is disabled in your config.
- Distribution type in your config is set to `Distribution`, which is intended for distribution of signed and notarized apps outside App Store (and can be done without sandboxing).

The signing error seems to be a bug specific to signing .NET helper executable as if it was sandboxed (even when it's not sandboxed).

**Comment by LeonardoDemartino** [comment]
Thanks for the feedback @bruvzg!

Still something is off with singing apparently.
After turning on sandboxing and set the config to `Distribution` as you suggested, I get now a .pkg and no errors from Godot (that's the good part). The bad part is that after installing, when I run the .app this popup appears:
<img width="301" alt="Screenshot 2024-07-18 at 6 06 23 PM" src="https://github.com/user-attachments/assets/ed61b740-6bf3-4613-a509-41a6c131652c">

If I set the "codesign" to DISABLED it runs fine, so I guess more changes are needed to fix code signing when C# is ON.

**Comment by LeonardoDemartino** [comment]
It even uploads fine to macOS TestFlight but crashes at startup as well (exporting locally without singing runs just fine).
It would be cool if somebody could test this on their side so we can figure out if this is a problem of my signing configuration or something else.

**Comment by LeonardoDemartino** [comment]
It looks like another case of: https://github.com/godotengine/godot/issues/91469
