### ISSUE TITLE
`godot --headless --import` hangs indefinitely the first time it is run

### ISSUE THREAD

**Issue by DanielKinsman** [godotengine/godot#94555]
### Tested versions

4.2.2

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 18 Jul 2024 18:06:13 +0000 - Wayland - Vulkan (Mobile) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) () - AMD Ryzen 7 5800X3D 8-Core Processor (16 Threads)

### Issue description

The first time I run it, it hangs forever until I give up and ctrl-c it. Running it a second or subsequent time works in less than 30 seconds. It is probably something wrong in my imports or project settings but I would at least expect it to die with an error rather than hang.

### Steps to reproduce

1. `git clone git@gitlab.com:DanielKinsman/whos-a-good-boy.git`
2. `cd whos-a-good-boy`
3. `rm -rf .godot`
4. `godot --headless --verbose --import`
5. wait a bit then give up and ctrl-c
6. `godot --headless --verbose --import`

### Minimal reproduction project (MRP)

https://gitlab.com/DanielKinsman/whos-a-good-boy/-/commit/4cd6b56b1ea580021d538a49249a08911e6a44c3

Unfortunately I couldn't reproduce in a newer, emptier project, sorry, but it is only 100mb.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/92833.

**Comment by DanielKinsman** [comment]
Removing the godot-jolt addon seems to fix the problem... https://gitlab.com/DanielKinsman/whos-a-good-boy/-/commit/0eda2d1e3a8875ce8de8db24da139cadab2fb7c3

**Comment by DanielKinsman** [comment]
Yeah they mention the hang foreverness in #92833 so I will close as a dupe.
