### ISSUE TITLE
Options to Disable the Editor from Maximizing Do Not Work

### ISSUE THREAD

**Issue by Byron1c** [godotengine/godot#94568]
### Tested versions

4.22
4.21

### System information

Windows 10, Godot 4.22, RTX3070, i7 12th Gen

### Issue description

Whenever opening any project from the list, the editor will not honour the setting to not put it in the Maximized window state. I have tried multiple fixes and supposed options, from the CLI (-W, or -R XXxYY), and from the Editor Settings screen in MultiWindow. Godot will always ignore the last state the window was in too, and always goes back to Maximized. 
The same happens when creating a new project. 

### Steps to reproduce

Fresh install
Open Godot
Select the project from the Project Manager
Editor appears full screen / Maximized

### Minimal reproduction project (MRP)

Create a new project and it does the same
[TEST.zip](https://github.com/user-attachments/files/16322970/TEST.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8358.

>  from the CLI (-W, or -R XXxYY), 

In 4.3.beta, the following works on my end: `--resolution 1280x720 --windowed`
