### ISSUE TITLE
"Always closes output on exit" option not work (replaced by new option)

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#94577]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

w10 64

### Issue description

There's not much to say, the option doesn't work.

https://github.com/user-attachments/assets/2dcb87e2-9861-490f-9e9c-e165698eaca1

### Steps to reproduce

...

### Minimal reproduction project (MRP)

...

**Comment by Hilderin** [comment]
This option does not exist anymore after the PR [#91033](https://github.com/godotengine/godot/pull/91033)

The new option is `Action on stop` in `Run > Bottom Panel`.

![Image](https://github.com/user-attachments/assets/5aceaf0c-aef8-4309-8b7e-f6621d02d8a0)

In this PR, I originally created a conversion to copy the old setting to the new, but I was asked to remove it. The problem with the Godot settings is that settings that are removed are still present in the setting window if they were modified.

 I could create a new PR for the setting conversion to prevent a lot of questions from users migrating from 4.2 to 4.3.

**Comment by geowarin** [comment]
This is probably a very naive questions from someone who's not really familiar with the codebase but: Why are we displaying properties that are not linked to anything in the code?

Wouldn't the simple solution be to discard all unknown properties?

**Comment by Hilderin** [comment]
The problem arises from the fact that plugins can create settings, and they can do so not only at startup. Therefore, removing settings that are not from Godot would also remove settings from plugins. There is a proposal about this: https://github.com/godotengine/godot-proposals/issues/4444
