### ISSUE TITLE
[Android Editor] Import button does not show folder content until Create button is pressed

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#94570]
### Tested versions

4.3 custom debug build from master

### System information

Android 14 - Samsung A14

### Issue description

In the Project Manager, when I press the `Import` button, the `File dialog` is at the root and I see no file or folder. When I press on `Create` and cancels that popup, I can press the `Import` button and the `File dialog` shows the correct files and folders.

In the logcat, I see this error:
```
07-20 22:29:40.247 23290 23354 E godot   : USER ERROR: Condition "id == 0" is true. Returning: ""
07-20 22:29:40.247 23290 23354 E godot   :    at: get_next (platform\android\dir_access_jandroid.cpp:67)
```

The other problem I see is when I select "SD Card" from the dropdown on the right corner, it does nothing. It always go back to "Internal shared storage". In fact, the files that are displayed in the File Dialog are from my SD Card even if "Internal shared storage is selected" so I don't known what this dropdown does exactly.

First Import press:
![1000012161](https://github.com/user-attachments/assets/53bb76e7-ac21-4486-9b3c-a72039583876)

Second Import press after Create popup:
![1000012162](https://github.com/user-attachments/assets/8171df6b-df1c-48ef-8001-e5cdbcdf75be)

### Steps to reproduce

- Open Godot on Android
- Press Import
- No files or folders are displayed

### Minimal reproduction project (MRP)

No project.

**Comment by akien-mga** [comment]
I've seen that do while doing some tests a week or two ago.

I first thought it was a mismatch in scoped storage between a debug editor build and official release editor builds, the latter having access to Documents and the unsigned debug build being limited to app storage only.

But based on this report it seems that my hypothesis was wrong and I was just lucky to get it working in some builds and not in another.

**Comment by m4gr3d** [comment]
I randomly ran into this issue yesterday. I'm traveling today so will try to take a look tomorrow.

**Comment by m4gr3d** [comment]
The regression seems to start with the first release candidate. Beta 3 does not exhibit the described issue.

**Comment by m4gr3d** [comment]
The root cause of the issue is https://github.com/godotengine/godot/pull/94113 and I have a tentative fix in https://github.com/godotengine/godot/pull/95086. I'm not familiar with that logic however so feedback are welcome on what the best resolution path would be.
