### ISSUE TITLE
Draggging/moving the game window exhibits choppiness/stuttering

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#94576]
### Tested versions

Found in:
4.3 beta3 (builds: yes, editor: no)
4.1.1 stable (builds:yes, editor:yes)

### System information

Godot v4.3.beta3.mono - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia; 535.183.01) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

Under Ubuntu (22.04.4), dragging the (build/editor) window is choppy, jumpy (as if at much lower framerates).

with --verbose on, it prints "Using present mode: Enabled" repeatedly while dragging, that leads to RenderingDeviceDriverVulkan::swap_chain_resize
which suggests to me that with 4.3.beta3 the build wrongly handles dragging also as resizing.

In 4.1.1 it also occurs when dragging the editor window, 
in 4.3beta3 moving the editor window interestingly doesn't exhibit the issue.

### Steps to reproduce

Hit play on any project, move the build window, move the editor window, compare the smoothness

### Minimal reproduction project (MRP)

(Any empty project)

**Comment by Calinou** [comment]
Does this occur if you disable **Allow Flipping** in nvidia-settings? See https://github.com/godotengine/godot/issues/39222.

**Comment by Flavelius** [comment]
> Does this occur if you disable **Allow Flipping** in the **OpenGL Settings** section of nvidia-settings? See #39222.

Yes, it still occurs, and still prints the same present mode message in --verbose

**Comment by Flavelius** [comment]
But this seems to be a duplicate then, so i'll just add my info in the other issue
