### ISSUE TITLE
Array with inner class type(`Array[InnerClass]`) breaks debug with `failed to encode a path`

### ISSUE THREAD

**Issue by GustJc** [godotengine/godot#94583]
### Tested versions

-Reproductible in: v4.3.beta3.mono.official [82cedc83c]

### System information

Windows 10 - Vulkan (forward+) - dedicated

### Issue description

Having a var that has a type of `Array[InnerClassType]` breaks debug with `failed to encode path`

When using a breakpoint, it spits out errors. Still works, but won't show the type on the debug console.
It'll keep spitting out the same errors every time the debug tries to show the variable.
And it won't show the class runtime debug when selecting the node inside the remote tab.

### Steps to reproduce

1.
- Put a breakpoint anywhere inside a class that uses an Array[InnerClassType]
- Play the game
Result: Errors spit in console. Don't break, but can't show array of innerclass variable. Trying to select `self` in debug spits errors again.
2.
- Select the node inside the remote tab while the game is running
Result: The node is not shown/selected. Errors spit in console

Errors:
![error](https://github.com/user-attachments/assets/aee58a33-c647-489c-afa2-5e5bf2b87d8a)

Min code:
![min_example](https://github.com/user-attachments/assets/5a2bad5c-ef32-4aac-9596-ee55aeb0bd9d)

### Minimal reproduction project (MRP)

Min project:
[MRP_has_inner_class.zip](https://github.com/user-attachments/files/16323640/MRP_has_inner_class.zip)

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/90467

Which has been solved

**Comment by GustJc** [comment]
Indeed it has. Just tested on the latest build (v4.3.beta.gh-94503 [34fd39e8e])
And it is now fixed.

Sorry for this. I'll make sure to test on the latest dev build before opening issues again.

**Comment by AThousandShips** [comment]
No worries! It would be very helpful if you are able to build the engine yourself to verify
