### ISSUE TITLE
Every other word blurry in checkbutton with linear texture / pixel font 

### ISSUE THREAD

**Issue by markim** [godotengine/godot#94591]
### Tested versions

- Reproducible in 4.3 Beta 3

### System information

Windows 10 - Godot 4.3 Beta 3 - Vulkan (Forwad+)

### Issue description

I am using the pixellocale font here https://fontstruct.com/fontstructions/download/1765530 , I included the license from the download in the zip for the project in this issue. I haven't had issues in any other control nodes, but for some reason I get blurry font on every other word with the CheckButton, see image

![image](https://github.com/user-attachments/assets/71be8591-5968-4877-bb8c-3900c53d0681)

My apologies if this is a user error / font understanding issue. It only seemed like an issue with this control, so I filed the bug report

### Steps to reproduce

- Make new project
- Set rendering for textures to linear in project settings for pixel font
- Created a CheckButton node
- Attached pixellocale font to node
- Set size to correct font size (9)
- add text to CheckButton
- see every other word blurry

### Minimal reproduction project (MRP)

[font_issue_4.3b3.zip](https://github.com/user-attachments/files/16325309/font_issue_4.3b3.zip)

**Comment by bruvzg** [comment]
Disable `subpixel positioning` in the font import settings and reimport it, it's incompatible with pseudo-pixel fonts like this (since it's not a real bitmap font, but a vector font with a straight line shapes, there's no reliable way to auto-detect it).

**Comment by markim** [comment]
That fixed the issue 😅 

So fast to reply, thanks for the help!
