### ISSUE TITLE
project.godot changes each time the editor is run

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#9459]
under 3.0 the project.godot file is constantly changing due to editor_pid changing each launch. This is a pain for those using git or any version control. 

not sure why there are 2 listings of each? from top of my project file:
config_version=3
editor_pid=2173
config_version=null
editor_pid=2173

**Comment by HummusSamurai** [comment]
Is there a specific reason that the editor's process ID is saved?

**Comment by reduz** [comment]
hmm this is used to allow focus stealing, but it should not go via project.godot, should be command line instead
