### ISSUE TITLE
Multiple Run Instances takes a long time to start

### ISSUE THREAD

**Issue by warent** [godotengine/godot#94605]
### Tested versions

Godot v4.3.beta3.mono

### System information

Godot v4.3.beta3.mono - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3090 Ti (NVIDIA; 32.0.15.6070) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When running two instances, the first instance takes many seconds to run any nodes or enable profiler attachment, but the second one starts immediately.

At first, I thought that I had some global node that was blocking something, but then I realized that none of the nodes enter_tree during this entire "lag" period, and the profiler doesn't attach. In fact, when clicking on the "Remote => Scenes" tree view to see the nodes in the remote, only one instance shows its node tree. The lagging instance shows a blank tree (or a copy of the running instance)

https://github.com/user-attachments/assets/192a9bd3-fc6f-4978-93e0-cd6c3fc35cab

### Steps to reproduce

Unfortunately, I'm actually not sure how to reproduce this issue or even debug it. I've tried to do the following:
1. Create a new Mono project.
2. Create a global node with a console log
3. Define two run instances, one of which is a dedicated server.
4. Run the project

The global node logs from both instances very quickly, and the profilers have no issue connecting. So, something beyond this or in addition to this is causing the issue.

### Minimal reproduction project (MRP)

I've tried to reproduce this with a minimal project and cannot

**Comment by Calinou** [comment]
Which port does your dedicated server listen on? Does the issue occur if you make it no longer listen on any port (i.e. comment out the part that creates the dedicated serer)?

**Comment by warent** [comment]
Actually, just found the problem. It's because I have a very poorly optimized, expensive operation happening in the constructor of a global node.

I think the profiler should pick up on something like this, but at this point it might be more of a feature request than a bug report. Feel free to close this ticket!

**Comment by warent** [comment]
Err... wait... No, that isn't it.

The program just suddenly pauses partway through the constructor logic for no clear reason, which is weird because that might mean whatever thread the constructor is being run on is being blocked from some external source.

I'm going to see if the port listening is related to this and try to find other potential causes.

**Comment by warent** [comment]
Okay, I see now it's getting stuck on a call to load a resource
```cs
GD.Load<PackedScene>(filePath);
```
and it pauses there for like 5 seconds before eventually succeeding. The strange thing is that this only happens to one of the instances, but they're both loading the same scene.

**Comment by warent** [comment]
I'm so dumb, finally found the issue.

The lagging instance is making a long network call on `_Ready` which takes about 5 seconds to resolve, and then it awaits it. During this time, the main game thread is blocked (which apparently is also blocking the profiler?)

Meanwhile, I guess the C# constructors are running on a separate thread, so when I call `GD.Print` from a constructor, the print doesn't actually make it through until the game thread is unblocked again. This gives the _illusion_ that the constructor itself is blocked, but it isn't.

The moral of the story here is to basically never put logic inside C# constructors. It's kind of a trap which causes weird issues like this.
