### ISSUE TITLE
line endings of text files differ on windows and linux

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9460]
line endings in .import files differ on windows and linux
its causing git to want to see every .import file as changed!

actually, this isn't limited to .imoprt files, its also affecting other files such as my .tscn files.

**Comment by Calinou** [comment]
When saving files, most softwares tend to default to CRLF line endings when run on Windows, and LF line endings when run on Linux or macOS. While almost all third-party software is fine with opening files with LF line endings on Windows, this is not the case of built-in utilities like the Notepad.

Perhaps we can force the usage of LF line endings on all platforms by default, but there may be other downsides than not being able to view the files properly in the Windows Notepad.

PS: You should be adding `.import/` to your `.gitignore`, as these assets do not belong to version control systems (they can be re-imported on each developer machine easily).

**Comment by akien-mga** [comment]
> PS: You should be adding .import/ to your .gitignore, as these assets do not belong to version control systems (they can be re-imported on each developer machine easily).

I thought that first but I think here it's about `*.import` files (import flags for assets) and not the `.import/` folder.

**Comment by sergey-push** [comment]
I think the problem is not related to godot, it is git configuration. Try https://help.github.com/articles/dealing-with-line-endings/

**Comment by supagu** [comment]
sergey is correct. It was a git setting.

I added a .gitattributes file with the following:

# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.c text
*.cpp text
*.h text
*.gd text
*.tscn text
*.import text
*.godot text
*.md text
*.py text
*.sh text

# Declare files that will always have CRLF line endings on checkout.
*.sln text eol=crlf

# Denote all files that are truly binary and should not be modified.
*.png binary
*.jpg binary
