### ISSUE TITLE
Popup window is closed by tooltips of other components on X11

### ISSUE THREAD

**Issue by Cliear** [godotengine/godot#94615]
### Tested versions

Godot_v4.3-beta1_linux.x86_64

### System information

WSL Version： 2.2.4.0     Kernel Version： 5.15.153.1-2       WSLg Version： 1.0.61          MSRDC Version： 1.2.5326            Direct3D Version： 1.611.1-81528511                         DXCore Version： 10.0.26091.1-240325-1447.ge-release             Windows Version： 10.0.19045.4651

### Issue description

X11 popup window is closed when the mouse hovers over other components with tooltip

### Steps to reproduce

![tooltip](https://github.com/user-attachments/assets/23039f1c-c52e-4546-9ce4-52324f3f99af)

### Minimal reproduction project (MRP)

N/A

**Comment by Cliear** [comment]
All other platforms are  running correctly, except for X11.

**Comment by Cliear** [comment]
This is linux 4.3 beta3

![tooltip_beta3](https://github.com/user-attachments/assets/e565907b-12d6-4afe-8c47-ddca34713d6c)


And this is windows 4.3 beta3
![tooltip_windows](https://github.com/user-attachments/assets/790c239e-b456-4450-938a-2f27816deda8)

By the way, Wayland can run correctly.

**Comment by Giganzo** [comment]
On 4.2.2 this doesn't happen

**Comment by akien-mga** [comment]
I can confirm the issue on Fedora 40 KDE Wayland using the X11 display server in multi window mode. It's not reproducible in single window mode or with the Wayland display server (which only supports single window mode).

The issue doesn't happen in 4.3.dev6 and seems reproducible in 4.3.beta1 onwards.

**Comment by Calinou** [comment]
> The issue doesn't happen in 4.3.dev6 and seems reproducible in 4.3.beta1 onwards.

I can reproduce this on 4.3.dev6 personally, but not 4.3.dev5 and earlier on Fedora 40 KDE X11.

**Comment by akien-mga** [comment]
Hacking the custom tooltip system is the gift that keeps on giving :)

**Comment by Cliear** [comment]
It seems that all popup window can be closed by this method
![any_popup](https://github.com/user-attachments/assets/79efb480-b0d4-4f01-8a27-efede3909688)
