### ISSUE TITLE
Android Play Billing library version update ?

### ISSUE THREAD

**Issue by owlnewworlds** [godotengine/godot#94627]
### Tested versions

Godot 4.3 beta 3

### System information

Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.4255) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

Uploading a package exported from Godot 4.3 beta 3 to Google Play Console makes it display a critical error about how the app uses Billing Library 5.2.1 which will deprecated in a few months.

https://developer.android.com/google/play/billing/deprecation-faq

### Steps to reproduce

- Export an Android app with custom permission "com.android.vending.BILLING" (/!\ Can't we have a checkbox for that, like all the other permissions ?)
- Upload this app bundle into Google Play Console
- Google Play Console displays a blocking error saying that the app uses Play Billing Library 5.2.1 which will be deprecated in a few months and prevents from publishing the app.

### Minimal reproduction project (MRP)

N/A

**Comment by kus04e4ek** [comment]
It's a known issue, see godotengine/godot-google-play-billing#65

**Comment by AThousandShips** [comment]
Closing in favour of the above, as it is the proper place for reporting bugs for this plugin, thank you for reporting

**Comment by owlnewworlds** [comment]
Hum OK Thank you for closing BUT the above issue doesn't seem to have a solution, it even feels like it's dead, right ? Someone seems to have made his own addon whereas there's an official plugin inside Godot for that (referred by the official documentation).

So well, I don't have any information if this issue WILL be OFFICIALLY fixed by Godot ?

**Comment by owlnewworlds** [comment]
OK thank you, just posted another message on one of these issues, I'm afraid it was forgotten or a ghost issue no one cares about.
