### ISSUE TITLE
Changes to RigidBody2D's position through script don't apply until accessing the same property again

### ISSUE THREAD

**Issue by SunkenPotato1** [godotengine/godot#94633]
### Tested versions

 - Reproducible in: v4.3.beta3.official [82cedc83c], v4.2.stable.official [46dc27791], v4.0.stable.official [92bee43ad], v4.0.alpha15.official [432b25d36]

### System information

Godot v4.2.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (nvidia; 535.183.01) - Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 Threads)

### Issue description

When changing RigidBody2D position through script, the changed value will not apply until you call get_global_position() directly or indirectly.

If the RigidBody2D is sleeping when you change the position, it visually moves but the moment it isn't sleeping, it's position reverts to the original location before every position change

e.g. this changes the position correctly
```gdscript
@onready var camera_2d: Camera2D = %Camera2D

func _process(delta: float) -> void:
	if Input.is_action_just_pressed("lmb"):
		self.get_global_position()
		self.position = camera_2d.get_local_mouse_position()
``` 
but this does not
```gdscript
@onready var camera_2d: Camera2D = %Camera2D

func _process(delta: float) -> void:
	if Input.is_action_just_pressed("lmb"):
		self.position = camera_2d.get_local_mouse_position()
```

if get_global_position() is called after changing the position it sometimes works sometimes doesn't, if its called before, it works consistently 

### Steps to reproduce

Click anywhere on screen to set the Rigidbody2D position to the cursor position
Can uncomment "#self.get_global_position()" in the script to fix the buggy behavior

### Minimal reproduction project (MRP)

[bug_report.zip](https://github.com/user-attachments/files/16337758/bug_report.zip)

**Comment by Chaosus** [comment]
You should not change the physic body position in `_process`. Instead, you should use `_integrate_forces` method.

![изображение](https://github.com/user-attachments/assets/08efd600-227d-4f64-958d-a6293ebd6d88)

**Comment by Chaosus** [comment]
Checked and its fixed when used `_integrate_forces` instead of a `_process`. Closed since its resolved.
