### ISSUE TITLE
delta time in _process() is incorrect (never lower than ~0.11) at low frame rates

### ISSUE THREAD

**Issue by simonschreibt-code** [godotengine/godot#94632]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Windows 10, v4.2.2.stable.official [15073afe3]

### Issue description

When I spawn many enemies and make the frame rate drop (intentionally), I noticed that the given delta value never goes below ~0.11 which means it will never show a value below 6-7 FPS.

Calculating the time manually by using `Time.get_ticks_msec()` works very well, though.

**VIDEO explaining the issue**:
https://youtu.be/FkTF7sDQMME?si=9lPKdSul_MELgulX

**Code Example**

func _process(delta : float) -> void:

❌Does not work
```
func _process(delta : float) -> void:

	text = str(int(1.0 / delta))
```

✔Works
```
func _process(delta : float) -> void:

	time_before = Time.get_ticks_msec() - time_after
	time_after = Time.get_ticks_msec()
	real_delta = time_before * 0.001

	text = str(int(1.0 / real_delta))
```

### Steps to reproduce

1. Open the project
2. Open `fps.gd`
3. Change line 17 from `text = str(int(1.0 / real_delta))` to text = `str(int(1.0 / delta))` (to disable my fix and see the bad behavior)
4. Start the project (F5)
5. Click quickly several times on the "spawn" button to create many enemies which will drop the frame rate quickly

You will see that the FPS never goes below 6-7 even though clearly the game renders only one frame evera 2-3 seconds.

### Minimal reproduction project (MRP)

[process_delta_time_issue_at_low_fps.zip](https://github.com/user-attachments/files/16337562/process_delta_time_issue_at_low_fps.zip)

**Comment by Calinou** [comment]
If framerate drops lower than `physics_ticks_per_second / max_physics_steps_per_frame`, the entire game will intentionally slow down to prevent "spiral of death" performance issues.

You can adjust the **Physics Ticks per Second** and **Max Physics Steps per Frame** project settings to adjust this.

**Comment by simonschreibt-code** [comment]
Thank you very much for the explanation! ❤
