### ISSUE TITLE
Updating .blend file does not reflect in @export variable PackedScene

### ISSUE THREAD

**Issue by ManasMakde** [godotengine/godot#94647]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (nvidia; 535.183.01) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

Updating a .blend file in blender does not reflect changes in the `@export variable:PackedScene`
rather it creates a `PackedScene` of the old .blend file

### Steps to reproduce

I have an exported variable as such:
```
@export var my_blend_scene:PackedScene
```
and I've passed a blend file as a scene into it as such:

![Editor Screenshot 1](https://github.com/user-attachments/assets/80e64b73-5f95-4f3e-ac01-5ef1aa7dbc5b)

but whenever I update & save the .blend file in blender (**version 3.6.9**) and then open godot again, the export variable does not update rather it creates a PackedScene of the old blend file:

![Editor Screenshot 2](https://github.com/user-attachments/assets/29438bf1-e24d-43c9-8c78-09973c87120b)

If this is the intended behaviour, then is there any other way to keep the exported variable in sync with the .blend file?

### Minimal reproduction project (MRP)

[Blend File Export (MRP).zip](https://github.com/user-attachments/files/16344572/Blend.File.Export.MRP.zip)

**Comment by fire** [comment]
Can you check behavior in 4.3 beta3 I suspect that there were some bugfixes.

**Comment by ManasMakde** [comment]
@fire yep it's fixed in v4.3.beta3.official [82cedc83c],  

when I `Open Scene` via the `@export my_blend_scene` in the inspector it shows the updated version, **However** when I view the instantiated `$Main/cube` it no longer updates

https://github.com/user-attachments/assets/749f01ea-d435-4eea-85c6-7c52264cb1b7

so this seems to be a new bug now :/

**Comment by fire** [comment]
I noticed you didn't save the instantiated `$Main/cube` so it no longer updates so I suspect it isn't being tracked for reloading as designed?

**Comment by ManasMakde** [comment]
@fire could you elaborate what you mean by "save the instantiated `$Main/cube`" ? Do you mean like save it as a separate scene? or do you mean save the entire `Main` scene (as in just pressing Ctrl + s)?

Also after some testing I found out that if I pass the `cube.blend` as an argument to `my_blend_scene` then the `$Main/cube` does not update **BUT** if I remove it as an argument then it starts tracking updates

https://github.com/user-attachments/assets/943f9523-9352-452e-b5a6-135640211dce

Not sure but maybe some issue with the reference count?

**Comment by yahkr** [comment]
@ManasMakde This issue appears to be resolved in v4.3.rc.custom_build [3e0c10d39] can you confirm?

**Comment by ManasMakde** [comment]
@yahkr yep it seems to be resolved now, closing this issue
