### ISSUE TITLE
Static properties are not documented as static

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#94640]
### Tested versions

4.3 beta3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Script:
```GDScript
extends Node

static var foo: int

static func bar():
	pass
```
The generated documentation is:
![image](https://github.com/user-attachments/assets/956bef0c-a191-4d9b-989e-fd16b1bc7921)
The property is not marked as static.

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

See above.

**Comment by dalexeev** [comment]
* See #78195.
