### ISSUE TITLE
Consistent spikes in process time/idle process after a few seconds of opening project (Steam)

### ISSUE THREAD

**Issue by adrianznur** [godotengine/godot#94659]
### Tested versions

Godot Engine v4.2.2
-Reproducible on Steam version
-Have not been able to do so in Standalone, works fine

### System information

MacOS Sonoma 14 - Godot Engine v4.2.2.stable.official - Vulkan API 1.2.231 - Forward+

### Issue description

After a few seconds upon running the project (About 10-15) the idle process skyrockets to usually between 22 ms-28 ms, regardless of if anything happens in-game. This happens consistently on Steam version, and for context to background apps are running to hinder my CPU.

I have tried many things to try and identify what was causing it. All my scripts were fine and there were no timers that go off after 10 seconds. I checked if it was the commonly reported vsync issue for mac, changing window types, and tampered with other possible project settings but that didn't solve it. I even tried removing all nodes including all enemies, the player, and the tilemap from the main scene. With only 4 collision boxes it was still reproducing the issue. I even made a brand new project with absolutely nothing as a main scene and it still had the spikes after 15 seconds.

I have searched online high and low and tried everything but nothing seemed to work. I was about to chalk it up to my device being faulty, when I decided to try the project on the standalone 4.2.2, and to my surprise it worked perfectly well, no stuttering or frame drops at all. This problem didn't even start after a Godot update or me changing anything in my project either, I closed Godot one night after finishing an enemy and it worked perfectly fine with no stutter. The next morning I decide to playtest before adding a new tileset and the spikes just started happening, seemingly for no reason.

### Steps to reproduce

No steps really, simply just have a project open for a couple seconds and close to the 1000 ms frame it will start producing the spikes. My device is a macOS Sonoma 14, and this bug only happens on the Steam version of Godot.

I attached videos that display the spikes (Or lack thereof), with the project in Standalone version, Steam version, and an empty project on Steam version.

https://github.com/user-attachments/assets/98005bab-997d-406b-98dc-eec1d549df91

https://github.com/user-attachments/assets/c888f59c-2999-4758-9eb5-7b5c4705fc6a

https://github.com/user-attachments/assets/f4d00350-e0bc-4483-b4c8-f792f44de0b0

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
> when I decided to try the project on the standalone 4.2.2, and to my surprise it worked perfectly well, no stuttering or frame drops at all

This sounds like a Steam overlay issue. Does this occur if you disable the Steam overlay in the Steam settings?

Note that disabling Steam overlay does not disable the actual hooking of Steam DLLs into the game process. It only disables the shortcut and some functionality.

**Comment by adrianznur** [comment]
> > when I decided to try the project on the standalone 4.2.2, and to my surprise it worked perfectly well, no stuttering or frame drops at all
> 
> This sounds like a Steam overlay issue. Does this occur if you disable the Steam overlay in the Steam settings?
> 
> Note that disabling Steam overlay does not disable the actual hooking of Steam DLLs into the game process. It only disables the shortcut and some functionality.

I've had Steam overlay disabled since I installed the Steam version since the overlay shortcut (Shift + Tab) can mess up/overlap with some of the script editor's keyboard shortcuts. I've always used the Steam version and this problem is new and out of the blue.

I haven't made any changes to the project, my Steam settings, or opened (Only closed a few afterwards) any new programs since the day BEFORE the issue started happening, and when I playtested that day it worked fine. While I was researching the issue yesterday I came across some other posts that shared similar issues and most of them did have solutions (Most involving project settings), but nothing worked for me.

In case this info helps as well, all of the scripts I have so far in the project use _physics_process instead of _process, and I've only installed one plugin about a month ago which hasn't had any recent updates and doesn't seem to directly correlate to this issue either since the nodes it affects are also gone in the empty project.

The only clue I have is that it starts to happen close to the 1000 frame mark and since it also happens on an empty project it doesn't give me much help. Is there a background process that updates during runtime that could be causing this?

**Comment by Calinou** [comment]
> Is there a background process that updates during runtime that could be causing this?

Not that I know of.

**Comment by adrianznur** [comment]
Well it's embarassing to say but it was actually pretty simple to solve. I tried restarting Steam and it doesn't seem to be reproducing for now, must have had something to do with the cache.

Strange that it persisted when I reset my computer though, since that also obviously restarts Steam. But regardless, I'm guessing the Steam cache had something to do with it, thank you @Calinou for the quick replies and help!

**Comment by adrianznur** [comment]
Well it's embarassing to say but restarting Steam seemed to work, the issue hasn't happened afterwards so far, must have something to do with the cache. Strange since it persisted even after restarting my computer which also restarts Steam, but regardless this should be the fix if nothing else works.
