### ISSUE TITLE
Property values not changing after adding keyframe in the AnimationPlayer

### ISSUE THREAD

**Issue by VicPrzz00** [godotengine/godot#94669]
### Tested versions

4.3 beta 3

### System information

Godot v4.3.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

The animation player stopped playing a keyframed animation properly after a few mixamo animations were added, in this case I was working on Crouching so I animated the capsule height and position. Since it was no longer working, I decided to delete the animation and make a new one, only for the values to not change at all (any keyframed value would get locked on some random value) and I did nothing in the meantime for any of this to happen other than import and delete the rig animations

https://github.com/user-attachments/assets/03a45a94-3daf-43ea-b1a5-6fcb333f5575

### Steps to reproduce

I don't know really

### Minimal reproduction project (MRP)

[switchable controller.zip](https://github.com/user-attachments/files/16362931/switchable.controller.zip)

**Comment by AThousandShips** [comment]
Once you have worked out some way to reproduce this bug please upload an MRP, asking in the [forums](https://forum.godotengine.org/) is a good way to find help with pinning down what's wrong, or identifying some user error or lacking documentation

**Comment by VicPrzz00** [comment]
[switchable controller.zip](https://github.com/user-attachments/files/16362916/switchable.controller.zip)

same thing happens when I try to animate the values elsewhere so unfortunately i dont know how to reproduce, but here is the project

**Comment by TokageItLab** [comment]
It seems that the AnimationPlayer side preview is just always overwritten because the AnimationTree is Active.
