### ISSUE TITLE
GPUParticles2D and GPUParticles3D have inconsistent property order in inspector

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#94687]
### Tested versions

- v4.2.2.stable.mono.official [15073afe3]
- v4.3.beta2.mono.official [b75f0485b]

### System information

Godot v4.3.beta2.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

GPUParticles3D and GPUParticles2D have inconsistent order of their properties in the inspector. This makes it confusing to work with particles in 2D and 3D because in 3D you have to scroll up to change time settings when you were working on the process material while in 2D you have to scroll down.

![image](https://github.com/user-attachments/assets/5050162a-55d2-46f0-a661-ae84d8328653)

It would be nicer if both particle systems had the same order of properties, e.g. GPUParticles2D could look like this:

![image](https://github.com/user-attachments/assets/85641b58-ecee-4800-9541-385eb66af5bb)

### Steps to reproduce

Add a GPUParticles2D and a GPUParticles3D to a scene and compare the inspectors.

### Minimal reproduction project (MRP)

N/A

**Comment by LeonStansfield** [comment]
I have noticed a couple other inconsistencies regarding the listing of parameters in the inspector:
 - interp_to_end are at different locations in the list between gpu_particles_3d and gpu_particles_2d
 - lifetime has exponential flag in its range slider on the gpu_particles_3d, which isn't the case in gpu_particles_2d.
 - preprocess has exponential flag in its range slider on the 3d version, which isn't the case in the 2d version
 - Draw order is set to index by default in gpu_particles_3d but lifetime in gpu_particles_2d

Some of these inconsistencies are across the cpu_partciles_2d and 3d as well:
- lifetime has exponential flag in its range slider on the cpu_particles_3d, which isn't the case in cpu_particles_2d.

I am drafting a PR that could be used to fix these inconsistencies.

**Comment by Calinou** [comment]
I have a PR for this, but it went stale: https://github.com/godotengine/godot/pull/48385
