### ISSUE TITLE
The Material property track does not work correctly when using the AnimationPlayer node, but it does in the editor

### ISSUE THREAD

**Issue by Asw015** [godotengine/godot#94690]
### Tested versions

4.3 beta3

### System information

Godot v4.3.beta3 - Windows 10.0.19041 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 3GB (NVIDIA; 32.0.15.5612) - Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 Threads)

### Issue description

![image](https://github.com/user-attachments/assets/e7bfdf3e-911d-4d79-a482-9da3f034961c)
![image](https://github.com/user-attachments/assets/c7b35c2b-a184-42dc-86a1-bbb8f2dbfff1)
It doesn't work after setting

### Steps to reproduce

Does not work properly after setting material properties on an animation player node

### Minimal reproduction project (MRP)

[bug-test (2).zip](https://github.com/user-attachments/files/16360322/bug-test.2.zip)

**Comment by AThousandShips** [comment]
What doesn't work? Please explain what you expect to happen or how you expect it to behave, and then explain how it does actually behave, or in what way it doesn't behave correctly

**Comment by AThousandShips** [comment]
You need to configure it for smooth transition, please see the [documentation](https://docs.godotengine.org/en/latest/tutorials/animation/introduction.html#doc-introduction-animation)

You can't smoothly transition between two materials, you have to change the properties instead

**Comment by Asw015** [comment]
No, not two materials.
I'm only transitioning one value of the shader in one material

**Comment by AThousandShips** [comment]
No you are animating two different materials in your MRP, or did you upload the wrong file?

**Comment by Asw015** [comment]
sorry，What is MRP，my English is poor，Can you explain？

**Comment by Asw015** [comment]
![image](https://github.com/user-attachments/assets/f388c064-cf37-4aca-b9b1-a466694747ce)
There's only one track here, so what are two materials?

**Comment by Asw015** [comment]
ok，I solved it.this problem.thanks，is not a bug，just my setting problem
