### ISSUE TITLE
Dopesheet for animation editor

### ISSUE THREAD

**Issue by poy360** [godotengine/godot#947]
It will be nice to have a dopesheet in animation editor

**Comment by akien-mga** [comment]
That sounds typically like something that you would do using an external tool, Godot is not really designed for that.

**Comment by punto-** [comment]
what is it tho? I've heard of them related to photography, but not digital
animation

**Comment by vnen** [comment]
I belive @poy360 meant something like the [3ds Max dope sheet](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/3DSMax/files/GUID-AFAD34E3-2851-43F4-A7DA-6F3286F83606-htm.html), though I'm sure how much it differs from the functionality that the animation editor already provides.
