### ISSUE TITLE
NavigationAgent2D gets stuck if you and it are on the opposite sites of an obstacle

### ISSUE THREAD

**Issue by D0DGEDwarvenStudios** [godotengine/godot#94709]
### Tested versions

- Reproducible in v4.2, 4.2.2 (both stable) and I have also tested it in v4.3beta3

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) RX Vega 11 Graphics (Advanced Micro Devices, Inc.; 31.0.14046.0) - AMD Ryzen 5 2400G with Radeon Vega Graphics (8 Threads)

### Issue description

The Enemy, when on the opposite side of an obstacle to you, will try to match your X or Y axis by moving along the edge, and then it will start rapidly changing directions, in the code, the direction is decided by the ```get_next_path_position()``` function (a Vector2 with it subtracted by the enemies position).

However, it should just pick a path, because in every scenario there IS a better path to go by.

Note that this approach, as seen in the project, also has context based steering on top of the pathfinding. However, even without it, it does not work.

This is the code without steering:
```gdscript
extends CharacterBody2D

@export var speed = 200  
@export var smoothValue = 2

var directionArray = [Vector2(0, -1), Vector2(1, -1), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1), Vector2(-1, 1), Vector2(-1, 0), Vector2(-1, -1)]

@onready var raycastArray = []
@onready var best_direction = null





@onready var global_vector_label = $"../CharacterBody2D/Camera2D/HUD/GlobalVectorLabel"
@onready var normalised_vector_label = $"../CharacterBody2D/Camera2D/HUD/NormalisedVectorLabel"

var global_vector_ref
var normalised_vector_ref
var dot_product_array_ref
var dangers_array_ref
var context_map_ref
var max_value_ref

@onready var NavAgent: NavigationAgent2D = $NavigationAgent2D
@onready var Player

func update_label(label_to_update: Label, text):
	if label_to_update != null and text != null:
		if label_to_update.text != text:
			label_to_update.text = text

func _ready():
	raycastArray = [$"1", $"2", $"3", $"4", $"5", $"6", $"7", $"8"]
	# Ensure all raycasts are enabled
	for raycast in raycastArray:
		raycast.enabled = true

func _physics_process(delta):
	if Player != null:
		NavAgent.set_target_position(Player.global_position)  # Correctly sets the target position
		
		if NavAgent.get_current_navigation_path() != null:
			var target_position = NavAgent.get_next_path_position()
			var global_vector = target_position - global_position
			
			global_vector_ref = global_vector.normalized()
			
			# Update velocity based on the direction to the target
			velocity = velocity.lerp(global_vector_ref * speed, smoothValue * delta)
			move_and_slide()
			
			# Update debug labels
			update_label(global_vector_label, str(global_vector))
			update_label(normalised_vector_label, str(global_vector_ref))

func _on_vision_area_body_entered(body):
	if body.name == "CharacterBody2D":
		Player = body

func _on_vision_area_body_exited(body):
	if body.name == "CharacterBody2D":
		Player = null
```

https://github.com/user-attachments/assets/428e7d56-ef95-44b6-8bce-83038de65589

And here is the code with and a video preview of how it looks:
```gdscript
extends CharacterBody2D

@export var speed = 15
@export var smoothValue = 2

var interestObjArray = []  
var directionArray = [Vector2(0, -1), Vector2(1, -1), Vector2(1, 0), Vector2(1, 1), Vector2(0, 1), Vector2(-1, 1), Vector2(-1, 0), Vector2(-1, -1)]

@onready var raycastArray = []
@onready var best_direction = null

func _ready():
	raycastArray = [$"1", $"2", $"3", $"4", $"5", $"6", $"7", $"8"]

	for raycast in raycastArray:
		raycast.enabled = true

@onready var global_vector_label = $"../CharacterBody2D/Camera2D/HUD/GlobalVectorLabel"
@onready var normalised_vector_label = $"../CharacterBody2D/Camera2D/HUD/NormalisedVectorLabel"
@onready var dot_product_array_label = $"../CharacterBody2D/Camera2D/HUD/DotProductArrayLabel"
@onready var dangers_array_label = $"../CharacterBody2D/Camera2D/HUD/DangersArrayLabel"
@onready var context_map_label = $"../CharacterBody2D/Camera2D/HUD/ContextMapLabel"
@onready var max_value_label = $"../CharacterBody2D/Camera2D/HUD/MaxValueLabel"
@onready var direction_line = $"../CharacterBody2D/Camera2D/HUD/DirectionLine"

var global_vector_ref
var normalised_vector_ref
var dot_product_array_ref
var dangers_array_ref
var context_map_ref
var max_value_ref

@onready var NavAgent: NavigationAgent2D = $NavigationAgent2D

func update_label(label_to_update: Label, text):
	if label_to_update != null and text != null:
		if label_to_update.text != text:
			label_to_update.text = text

func get_wrapped_index(index, array_size):
	return (index + array_size) % array_size

func _physics_process(delta):
	if not interestObjArray.is_empty():
		for interest_obj in interestObjArray:
			if interest_obj != null:
				var position_reference = interest_obj.global_position
				
				NavAgent.set_target_position(position_reference)
				
				
				if NavAgent.get_current_navigation_path() != null:
					var target_position = NavAgent.get_next_path_position()
					var global_vector: Vector2 = target_position - self.position
					var normalised_vector = global_vector.normalized()
					
					global_vector_ref = global_vector
					normalised_vector_ref = normalised_vector

					var dotArray = []
					for directionVector in directionArray:
						var dotProduct = normalised_vector.dot(directionVector)
						dotArray.append(dotProduct)
					
					dot_product_array_ref = dotArray
					
					var dangersArray = [0, 0, 0, 0, 0, 0, 0, 0]
					var array_size = dangersArray.size()
					for raycast in raycastArray:
						if raycast.is_colliding() == true and raycast != null:
							var current_raycast_index = raycastArray.find(raycast)

							if dangersArray[current_raycast_index] != 5:
								dangersArray[current_raycast_index] = 5
							
							for offset in range(1, 2):
								var left_index = get_wrapped_index(current_raycast_index - offset, array_size)
								var right_index = get_wrapped_index(current_raycast_index + offset, array_size)
								
								if dangersArray[left_index] == 0:
									dangersArray[left_index] = 3 - offset
								if dangersArray[right_index] == 0:
									dangersArray[right_index] = 3 - offset
							
							print(raycast.name, " is colliding with ", raycast.get_collider())
							
					dangers_array_ref = dangersArray
	
					var context_map = []
					
					for i in range(8):
						context_map.append(dotArray[i] - dangersArray[i])
				
					context_map_ref = context_map
					
					var max = context_map[0]
					var max_index = 0
					for i in range(8):
						var current = context_map[i]
						if current >= max:
							max = current    
							max_index = i
					
					max_value_ref = max
					
					best_direction = directionArray[max_index]
					
	if best_direction != null:
		var desired_velocity = best_direction * speed
		var steering_force = desired_velocity - velocity
		velocity = velocity.lerp(desired_velocity, smoothValue * delta)
	else:
		print("Best direction is null.")
		velocity = Vector2.ZERO
	
	move_and_slide()

func _on_vision_area_body_entered(body):
	if body.name == "CharacterBody2D":
		interestObjArray.append(body)
		print(body.name + " is interesting!")

func _on_vision_area_body_exited(body):
	if body.name == "CharacterBody2D":
		if interestObjArray.has(body):
			interestObjArray.erase(body)
		print(body.name + " is NOT interesting anymore!")

func update_direction_line(direction: Vector2):
	var start_point = Vector2(800, 100)  
	var end_point = start_point + direction.normalized() * 100  

	direction_line.points = [start_point, end_point]

func _on_update_timer_timeout():
	update_label(global_vector_label, "Global Vector: " + str(global_vector_ref))
	update_label(normalised_vector_label, "Normalised Vector: " + str(normalised_vector_ref))
	update_label(dot_product_array_label, "Dot Product Array: " + str(dot_product_array_ref))
	update_label(dangers_array_label, "Dangers Array:" + str(dangers_array_ref))
	update_label(context_map_label, "Context Map Array: " + str(context_map_ref))
	update_label(max_value_label, "Max Value: " + str(max_value_ref))
	if best_direction != null:
		update_direction_line(best_direction)

```

https://github.com/user-attachments/assets/379aec01-6ca4-4265-9b40-029779184078

NOTE: The direction line switched WAY faster in actuality, but I didnt want to accidentally cause someone an epilepsy attack so I slowed it down, in reality it switches every frame I believe (thats how it looks like at least), just decrease the time on the timer if you want to see it in game.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

Version with the HUD present in the video:
[BugTesting (with the HUD).zip](https://github.com/user-attachments/files/16366988/BugTesting.with.the.HUD.zip)

Version without it:
[BugTesting (without the HUD).zip](https://github.com/user-attachments/files/16366990/BugTesting.without.the.HUD.zip)

**Comment by smix8** [comment]
Avoidance is based on velocities. It has no relation to paths or pathfinding from the navigation mesh system. You set a velocity in your own script to get a "corrected" velocity calculated based on other agents and their velocities among other properties.

Expecting the avoidance to "find better paths" does not work because that is not what it does. The pathfinding is based on the navigation mesh surface and only on that surface.

**Comment by D0DGEDwarvenStudios** [comment]
But the first approach doesnt use any kind of avoidance or steering, yet it still cannot decide in which direction to go? What kind of pathfinding cant go around obstacles thats definetly not intended

> RVO avoidance is based on velocities. It has no relation to paths or pathfinding from the navigation mesh system. You set a velocity in your own script to get a "corrected" velocity calculated based on other agents and their velocities among other properties.
> 
> Expecting the avoidance to "find better paths" does not work because that is not what it does. The pathfinding is based on the navigation mesh surface and only on that surface.

**Comment by ydeltastar** [comment]
I'm not sure if I understand the MRP. The nagivation region has no colliders or meshes, so it is flat with no holes. The pathfinding will always be a direct line to the target because the big object doesn't exist in the navigation polygon.

There is some confusion going on here between the obstacle and avoidance terms, pathfinding, and character/static bodies. You problably want the big object as a static body, child of the region, and bake it. See https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationmeshes.html#baking-a-navigation-mesh-with-a-navigationregion

**Comment by D0DGEDwarvenStudios** [comment]
I may have 

> I'm not sure if I understand the MRP. The nagivation region has no colliders or meshes, so it is flat with no holes. The pathfinding will always be a direct line to the target because the big object doesn't exist in the navigation polygon.
> 
> There is some confusion going on here between the concepts of obstacle/colliders, avoidance/pathfinding, and character/static bodies. You problably want the big object as a static body, child of the region, and bake it. See https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationmeshes.html#baking-a-navigation-mesh-with-a-navigationregion

I may have made it wrong, my apologies.
Yes I most likely have done the obstacle wrong, I will try what you suggested and read the doc. Thank you!

**Comment by D0DGEDwarvenStudios** [comment]
> I'm not sure if I understand the MRP. The nagivation region has no colliders or meshes, so it is flat with no holes. The pathfinding will always be a direct line to the target because the big object doesn't exist in the navigation polygon.
> 
> There is some confusion going on here between the concepts of obstacle/colliders, avoidance/pathfinding, and character/static bodies. You problably want the big object as a static body, child of the region, and bake it. See https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationmeshes.html#baking-a-navigation-mesh-with-a-navigationregion

Indeed I was! Thank you so much! Btw I will read the doc now, but if it isnt there and you are willing, could you point me to some recources on how I could make tiles static so I could use pathfinding on them as well. Thank you again.

**Comment by D0DGEDwarvenStudios** [comment]
> > I'm not sure if I understand the MRP. The nagivation region has no colliders or meshes, so it is flat with no holes. The pathfinding will always be a direct line to the target because the big object doesn't exist in the navigation polygon.
> > There is some confusion going on here between the concepts of obstacle/colliders, avoidance/pathfinding, and character/static bodies. You problably want the big object as a static body, child of the region, and bake it. See https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationmeshes.html#baking-a-navigation-mesh-with-a-navigationregion
> 
> Indeed I was! Thank you so much! Btw I will read the doc now, but if it isnt there and you are willing, could you point me to some recources on how I could make tiles static so I could use pathfinding on them as well. Thank you again.

Ok I found one, https://youtu.be/ztX4OV6Syn8?si=WWlFwZGqHvGraz15
This excellent tutorial helped a lot though I dont know how to use tiles well so I didnt do it properly, but the behaviour is there.
