### ISSUE TITLE
Polyphonic Audio Stream doesn't stop in HTML export in 4.3 beta (Sample playback type)

### ISSUE THREAD

**Issue by tr-afa-ret** [godotengine/godot#94724]
### Tested versions

- Reproducable in 4.3 beta3 [82cedc83c]

### System information

Chrome and Edge on Windows, Chrome on Android

### Issue description

stop_stream() method of AudioStreamPlaybackPolyphonic, doesn't stop audioStreams

### Steps to reproduce

- create a project in 4.3 beta3
- add AudioStremPlayer
- add AudioStreamPolyphonic as stream
- through script use [play_stream()](https://docs.godotengine.org/en/stable/classes/class_audiostreamplaybackpolyphonic.html#class-audiostreamplaybackpolyphonic-method-play-stream) to play and audiostream and add stream ID to a variable. 
- use [stop_stream()](https://docs.godotengine.org/en/stable/classes/class_audiostreamplaybackpolyphonic.html#class-audiostreamplaybackpolyphonic-method-stop-stream) with same stream ID to stop the audio stream

observe that the audio stream starts and stops when running from the editor
however the stream will not stop in HTML export

### Minimal reproduction project (MRP)

[polyphonichtmlproblem.zip](https://github.com/user-attachments/files/16372173/polyphonichtmlproblem.zip)

**Comment by akien-mga** [comment]
This may be the same issue as #94226, in which case it would be fixed by #94268 (in upcoming 4.3.rc1).

**Comment by akien-mga** [comment]
Doesn't seem fixed yet, I can confirm the bug in 4.3.rc2.

**Comment by akien-mga** [comment]
I tested and confirm that the issue comes from Web audio now default to "Sample" playback type, which is new in 4.3.
Overriding it to "Stream" (i.e. like in 4.2.2) works around the issue.

![image](https://github.com/user-attachments/assets/88cba463-fdd3-4de2-addc-157603cb3a0c)
