### ISSUE TITLE
Moving and then unhiding a Node2D makes it flicker with physics interpolation enabled

### ISSUE THREAD

**Issue by KerekesDavid** [godotengine/godot#94736]
### Tested versions

Reproducible in: 4.3 Beta3

### System information

Godot v4.3.beta3 - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (CML GT2) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

Moving a Node2D and then unhiding it right away makes it show up in it's previous position for a frame when Physics Interpolation is enabled.

Also happens if deferring the show() function with call_deferred.

This is especially annoying when instantiating a new Node2D that I want to show in a certain position, because then I don't have control over the previous position at all. (For example spawning a one-time effect.)

### Steps to reproduce

- Enable Physics Interpolation in the settings.
- Move a Node2D by setting it's global position.
- Show it in the same frame. 
```
func move_and_show() -> void:
	global_position = Vector2(randf_range(0, 500),randf_range(0, 500))
	show()
```

https://github.com/user-attachments/assets/6ac34eab-f687-4c82-b939-08e4c8d3352f

Disabling physics interpolation fixes the problem:

Edit:
Now I see that the problem actually shows up in the recorded video even with physics interpolation disabled, but it goes away when viewed directly on my screen.

https://github.com/user-attachments/assets/034ecb40-5e51-42c6-8692-af3ae6d78ab9

### Minimal reproduction project (MRP)

[phys_interpolate_flicker.zip](https://github.com/user-attachments/files/16377580/phys_interpolate_flicker.zip)

**Comment by KerekesDavid** [comment]
Interestingly, recording with OBS shows the correct behavior with Physics Interpolation disabled, the same that I can see on my screen:

https://github.com/user-attachments/assets/5d13c7ed-b1d7-41af-82fd-b37f21bf46ee

**Comment by lawnjelly** [comment]
Away from home right now, but you probably need to call 'reset_physics_interpolation()'.
This is detailed in 3.6 docs.

**Comment by KerekesDavid** [comment]
That fixes it, thanks for the quick reply! Couldn't find it anywhere in the 4.3 docs, it should probably be included there as well.

**Comment by KerekesDavid** [comment]
One caveat for this, calling `reset_physics_interpolation()` after setting `global_position` works in the MRP. In my original project, where the sprite is an AnimatedSprite2D I have to call `reset_physics_interpolation()` after `show()`.

So the following still flickers:
`global_position = Vector2(randf_range(0, 500),randf_range(0, 500))
self.play(&"default")
reset_physics_interpolation()
show()`

While this one fixes the problem:
`global_position = Vector2(randf_range(0, 500),randf_range(0, 500))
self.play(&"default")
show()
reset_physics_interpolation()`

**Comment by lawnjelly** [comment]
Yes, there are some subtleties with different node types.
We are gradually adding auto-resets where possible (entering tree is one), but hide / show is not yet dealt with.
