### ISSUE TITLE
Can't load C# scripts when exporting a build on macOS

### ISSUE THREAD

**Issue by AdamLearns** [godotengine/godot#94750]
### Update

Update (~15 minutes after filing the issue): someone alerted me that an official `4.3-rc1` build [was released today](https://godotengine.github.io/godot-interactive-changelog/#4.3-rc1), and my issue does _not_ repro there. I think it's safe to conclude that I'm doing something wrong when it comes to building my own export templates, although I still don't know what that might be. However, that would be a separate issue from this, so I'll close this one. 

### Tested versions

Reproducible in 4.3-rc (testing on commit 91eb688e178fe32f28aebfbec01137abefd75413).

### System information

M2 macOS - Sonoma 14.5

### Issue description

#94631 was fixed very recently, so I wanted to see if I could now produce ARM builds for macOS. However, when I export the attached MRP, it fails to run:

```
ERROR: No loader found for resource: res://Script.cs (expected type: Script)
   at: _load (core/io/resource_loader.cpp:291)
ERROR: Can't load dependency: res://Script.cs.
   at: parse_variant (core/io/resource_format_binary.cpp:461)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:505)
ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:492)
ERROR: Failed loading resource: res://.godot/exported/133200997/export-10ee2b14ed3c73b7308a09b7f9f06a5a-Scene.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:284)
ERROR: Failed loading scene: res://Scene.tscn.
   at: start (main/main.cpp:3892)
```

Note: the game runs successfully from the editor, just not when exported.

### Steps to reproduce

I built Godot using the following steps with a repo synced to 91eb688e178fe32f28aebfbec01137abefd75413:

```
brew install scons
scons platform=macos arch=arm64 module_mono_enabled=yes
./bin/godot.macos.editor.arm64.mono --headless --generate-mono-glue modules/mono/glue
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --push-nupkgs-local ~/MyLocalNugetSourceForGodot
scons platform=macos target=template_release arch=x86_64
scons platform=macos target=template_debug arch=x86_64
scons platform=macos target=template_release arch=arm64
scons platform=macos target=template_debug arch=arm64
lipo -create bin/godot.macos.template_release.x86_64 bin/godot.macos.template_release.arm64 -output bin/godot.macos.template_release.universal
lipo -create bin/godot.macos.template_debug.x86_64 bin/godot.macos.template_debug.arm64 -output bin/godot.macos.template_debug.universal

cp -r misc/dist/macos_template.app .
mkdir -p macos_template.app/Contents/MacOS
cp bin/godot.macos.template_release.universal macos_template.app/Contents/MacOS/godot_macos_release.universal
cp bin/godot.macos.template_debug.universal macos_template.app/Contents/MacOS/godot_macos_debug.universal
chmod +x macos_template.app/Contents/MacOS/godot_macos*
zip -q -9 -r macos.zip macos_template.app
```

Then I ran these steps:

- Move `macos.zip` → `~/Library/Application Support/Godot/export_templates/4.3.rc.mono/macos.zip`
- Export the attached project for macOS
- Run

From what I can find in other issues, it seems like the export templates may be broken, which is probably my fault somehow, but I can't figure out what I've done wrong. 😓

### Minimal reproduction project (MRP)

The minimal project is just any project with a C# script, e.g. [this one](https://github.com/user-attachments/files/16382566/Archive.zip).

**Comment by bruvzg** [comment]
> scons platform=macos target=template_release arch=x86_64
> scons platform=macos target=template_debug arch=x86_64
> scons platform=macos target=template_release arch=arm64
> scons platform=macos target=template_debug arch=arm64

You are building templates without .NET support, add `module_mono_enabled=yes`.

**Comment by AdamLearns** [comment]
> You are building templates without .NET support, add module_mono_enabled=yes.

Ahh, this is very helpful, thank you! 🙏 I thought I only needed it for the editor itself (I misunderstood [the documentation](https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_with_dotnet.html)), but it makes sense that it's needed for the export templates. I'll update my notes.
