### ISSUE TITLE
get_surface_override_material_count returns '1' even when its property is set to '0'

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#94757]
### Tested versions

Godot version 4.3-RC1

### System information

Windows 11

### Issue description

calling get_surface_override_material_count on a MeshInstance3D returns that a material is assigned even when the property value is empty.

### Steps to reproduce

call get_surface_override_material_count() on A mesh with surface material override property empty, but has a surface material assigned.

### Minimal reproduction project (MRP)

N/A

**Comment by smix8** [comment]
The documentation of that function already makes it very clear that this returns the equivalent of the surface count of the mesh and not "used slots" if that is what you assumed for whatever reasons.

**Comment by clayjohn** [comment]
For reference, here is the docs page: https://docs.godotengine.org/en/latest/classes/class_meshinstance3d.html#class-meshinstance3d-method-get-surface-override-material-count
