### ISSUE TITLE
`AnimationNodeStateMachineTransition.break_loop_at_end` is unreliable

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#94767]
### Tested versions

- Reproducible in: v4.3.rc1.official [e343dbbcc]
- Not reproducible in:   v4.3.beta1.official [a4f2ea91a], v4.3.beta2.official [b75f0485b], v4.3.beta3.official [82cedc83c]

### System information

Godot v4.3.rc1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5123) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When setting break_loop_at_end for a state transition through the editor, it is unreliable. Specifically, an At End transition will not always occur at the end of the first loop, and may not even occur for multiple cycles.  Oddly, when in this failing state, manipulating the game window occasionally causes the transition to finally occur.

This occurs in a running instance of the game, but can also sometimes be seen in the editor preview.

Video of the bug in action (the cube should simply move in a square, when it gets stuck repeating on the right hand edge, that's the bug):

https://github.com/user-attachments/assets/3b00a785-0a94-4a32-ab1c-4b35a9a77da2

### Steps to reproduce

1. Open MRP.
2. Run project.
3. Watch the cube move in a square. If at any point, the movement down the right side of the square repeats additional times before moving to the next edge of the square, you are seeing the bug in action.

If you do not see the issue occurring after two full cycles around the square, relaunch the game.  The behaviour is not consistent.

When the issue does occur, note that you can likely get out of the broken state and back into a good one by clicking and dragging the title bar of the game window to reposition the window.

### Minimal reproduction project (MRP)

[anim_tree_loop.zip](https://github.com/user-attachments/files/16385615/anim_tree_loop.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #94554 as the culprit:

![image](https://github.com/user-attachments/assets/16758a0e-bbbb-4fff-b99c-652cd82ace22)

**Comment by TokageItLab** [comment]
I think https://github.com/godotengine/godot/issues/94768 is actually the problem in the first place, and https://github.com/godotengine/godot/pull/94554 just brought the problem to the surface, and the areas that need to be corrected are the same as https://github.com/godotengine/godot/issues/94768.
