### ISSUE TITLE
[4.3 RC 1] AudioStreamPlayer does not work correctly during web export

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#94761]
### Tested versions

Godot 4.3 RC 1

OpenGL API OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)) - Compatibility - Using Device: WebKit - WebKit WebGL

### System information

Linux Ubuntu 22.04

### Issue description

The following issues occur with web export:

~~For a sound that has been played at least once, the "playing" variable is always true.
The volume of individual channels does not work correctly. Randomly it SOMETIMES works as configured and SOMETIMES the volume settings are ignored.~~

In the minimal project this is clearly visible; I tried to comply with all the conditions under which this occurs.

### Steps to reproduce

- Add multiple AudioStreamPlayers to the scene
- Add them WAV sounds and OGG Music
- Launch them
- Check the playing status

In addition, the "finished" signal is not called either.

### Minimal reproduction project (MRP)

[audiodemo.zip](https://github.com/user-attachments/files/16384435/audiodemo.zip)

_**Bugsquad edit:** relates to #94226_

**Comment by SkanerSoft** [comment]
View in Browser: https://pn-games.com/play/test_audio/

See Debug Console.

**Comment by adamscott** [comment]
@SkanerSoft I don't know why you're saying that the master bus is ignored on the web export, it is not.
Here's the proof: [audiodemo-with-slider.zip](https://github.com/user-attachments/files/16392197/audiodemo-with-slider.zip)

**Comment by SkanerSoft** [comment]
This doesn't bother me as much since in my project the volume is the same for all sounds. But the problem with the fact that I can’t get them to finish and start again is really critical.

**Comment by SkanerSoft** [comment]
I'll try to keep track of this situation and report back as soon as I can figure out a pattern. This is indeed a rare occurrence and probably deserves its own bug report.

**Comment by SkanerSoft** [comment]
I crossed out the unnecessary things that are not worth paying attention to. The rest needs fixing. Thank you for taking the time to do this! For me, there is no one who can help the way Godot developers do. This is a colossal job!

**Comment by adamscott** [comment]
Closing issue as it's a duplicate of closed #94226. I'll reopen the later as #94268 had a typo that prevented the fix from working.

The next time, please comment and ask to reopen a closed issue if the fix doesn't fix it instead of reopening a new issue with the same bug.

**Comment by adamscott** [comment]
> ![image](https://private-user-images.githubusercontent.com/13809475/352553140-75675f34-5f09-4a0f-a565-3dd22fb25878.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDMwMDMsIm5iZiI6MTcyMjAwMjcwMywicGF0aCI6Ii8xMzgwOTQ3NS8zNTI1NTMxNDAtNzU2NzVmMzQtNWYwOS00YTBmLWE1NjUtM2RkMjJmYjI1ODc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0MDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZmE0MTlhODcwMmFkN2NhN2I4MDE0MzFhN2JjMTQ0YmYzODgwMjJiMTFmMzk3YjAxZTliYmYzNDMxOTljYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gefb9nmFH1877yzh_Jvg4ye8XiDYLjk6xyxIqbJQFqk)
> 
> I'm sorry, I just phrased it wrong. I didn't mean Master, its Music. Sometimes the reduced volume is ignored. In my minimal example, I misspelled Master. It was necessary to write Music.
> 
> Otherwise, you can download my example and see for yourself.

I can't reproduce. If I set "Music" to `-Infinity`, the music is muted. And it sounds exactly as the desktop version.

**Comment by SkanerSoft** [comment]
`I can't reproduce. If I set "Music" to -Infinity, the music is muted. And it sounds exactly as the desktop version.`
I'll pay more attention to this in the future! The rest of the questions are all clear, thank you very much for your work!

**Comment by TinyTakinTeller** [comment]
I can replicate in 4.3 (bus works on desktop but broken on web export) like this:

```
	var player = AudioStreamPlayer.new()
	var stream = AudioStreamPolyphonic.new()

	player.stream = stream
	player.process_mode = process_mode
	player.bus = "Music"

	player.stream.polyphony = 1
	player.max_polyphony = 1

	add_child(player)

	player.play()

	var playback = player.get_stream_playback() as AudioStreamPlaybackPolyphonic

	var stream_id = playback.play_stream(load(path) as AudioStream)
```

reopen issue?

**Comment by Sketh14** [comment]
​If anyone stumbles upon this, for the web builds settings the Playback Type to "Stream" makes the audio work for me. Neither "Sample" nor "Default" worked for me. The same goes for Polyphonic AudioStream, passing the "AudioServer.PLAYBACK_TYPE_STREAM" in play_stream() does the job, just setting it in the editor didnt work for me. I have tested this on Godot 4.6.3 stable.
