### ISSUE TITLE
It should be impossible to delete predefined global properties in project settings

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#9478]
It would be nice to have a have pop-up warning to confirm before you delete a global property. I have deleted global properties on accident several times by mis-clicking and hitting the 'Del' button when going to exit out of the Project Settings window. As it is right now, they are instantly deleted with no warning, and nothing in the console telling you what happened or what was deleted.

**Comment by curly-brace** [comment]
but it would be hard to delete multiple variables if each generates popup

**Comment by kubecz3k** [comment]
Also not sure if it's the best idea to allow delete buildin properties

**Comment by Miziziziz** [comment]
@curly-brace Maybe it could be possible to select multiple properties by doing Ctrl+click?

@kubecz3k Not sure whose comment you're referring to, but my problem was that is possible to delete predefined properties.

**Comment by kubecz3k** [comment]
@Miziziziz So maybe main problem is in the fact that it's possible to delete **predefined** properties? If so then title is little misleading (it's possible to define your own properties so it's good this ability exists generally - just not sure if there is scenario in which someone might want to delete predefined global property).

**Comment by Miziziziz** [comment]
@kubecz3k yes you're right, that's the main problem; I'll change the title. But, it would also be nice if the console did make a note of what you deleted in case it was an accident; perhaps I should open a separate issue on that?

**Comment by kubecz3k** [comment]
@Miziziziz I think it's a good idea, I will change the title of current issue little more so it will be more self explanatory

**Comment by bojidar-bg** [comment]
Is this still the case on master/3.1? Project settings were refactored a bit, from what I remember.

**Comment by KoBeWi** [comment]
Fixed since 3.1
