### ISSUE TITLE
Web export fails to run

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#9479]
**Operating system or device - Godot version:**
e63c64e256bc77618e4ea5ab13ecba6306ced0e6

i've created simple project to test performance, but failed to run it in browser. but templates compile fine tho.

asm.js gives following in godot console:
**ERROR**: run() called, but dependencies remain, so not running
**ERROR**: pre-main prep time: 230 ms
let it go dude!
**ERROR**: Calling stub instead of sigaction()
**ERROR**: missing function: pthread_rwlock_wrlock
-1
**ERROR**: -1
**ERROR**: warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
Successfully populated IDB file system
**ERROR**: At: main/main.cpp:1039:start() - Condition ' !_start_success ' is true. returned: false

wasm gives just that in the browser console:
Uncaught TypeError: Module.asm is not a function at test.js:3

**Comment by eska014** [comment]
afbb5261e660acf08dd62f698d353e95fc7fb6bb works on my end, have you tried Ctrl+F5/clearing your cache?
You didn't specify what browser you're using, but if it's Firefox, it uses a a separate cache for asm.js, here are instructions to delete that:

> Note: to clear out the asm.js cache for a given origin, click the [Site Identity Button](https://support.mozilla.org/en-US/kb/how-do-i-tell-if-my-connection-is-secure) → More Information → Permissions → (scroll down) → Clear Storage.
>https://blog.mozilla.org/luke/2014/01/14/asm-js-aot-compilation-and-startup-performance/

**Comment by curly-brace** [comment]
i've tried with vivaldi (my main browser) and after getting errors, i've installed firefox.
i'm confused a little bit, may be i'm doing something wrong then.
here is the link with asm.js build, may be you can test it?
http://fb7920ne.bget.ru/

**Comment by volzhs** [comment]
I got same error with chrome Version 59.0.3071.115 (Official Build) (64-bit) on ubuntu 16.04

**Comment by eska014** [comment]
Yeah, that link gives the error log above.
I downloaded the `.pkg` file, ran it with my own template and it works.

Your version of Emscripten is probably too old. Emscripten 1.36.1 was released in August 2016 and added several no-op implementations for pthread functions. These are missing in your build, causing issues.

You can use `$EMSCRIPTEN_ROOT/emcc -v` on Unix or `%EMSCRIPTEN_ROOT%\emcc -v` on Windows to print your Emscripten version. Of course you need to define `EMSCRIPTEN_ROOT` as you do before building web templates.

If your distributions' Emscripten package is unmaintained or not updated enough, you're better off using Emscripten's `emsdk` to install Emscripten: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#windows-osx-and-linux-installing-the-portable-sdk

---

Anyway, would be nice if this error was fixed properly by avoiding any calls to pthread functions when building a Unix platform with the `-DNO_THREADS` flag. The problem in this issue originates here: https://github.com/godotengine/godot/blob/e4b42a5da0f5fe067210bee224595f64206f86c4/core/object.cpp#L1899

**Comment by curly-brace** [comment]
many thanks, eska. i'm glad that this is not a bug.
i've installed latest emscripten yesterday. Actually i was compiling templates under linux and exporting project under windows (june 6 version, because latest doesnot compile). But today i've tried exporting under linux, the same version as was used to build templates. and it failed too, but asm.js with different error:
**ERROR**: pre-main prep time: 83 ms
**ERROR**: Invalid function pointer called with signature 'ii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
**ERROR**: Build with ASSERTIONS=2 for more info.
69
**ERROR**: 69
**ERROR**: warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling
Successfully populated IDB file system

page freezes forever before the last message (that message appears only after killing the page). the build is under the link above if it is of some help.

again i'm happy that this is not a bug. seems like i'm doing something wrong.
i'd better then wait before alpha is released that has right export templates.

**Comment by curly-brace** [comment]
i think that was my fault, because now i somehow made it work. closing this. btw great work! performance is amazing comparing to 2.x
