### ISSUE TITLE
Need to load ninja tool before issuing ninja-related SetOption

### ISSUE THREAD

**Issue by mwichmann** [godotengine/godot#94805]
### Tested versions

git HEAD as of 26 Jul (607b230ffe was the last commit).

### System information

Tested on a Fedora Linux 40 build platform.

### Issue description

If ninja mode is selected, the SConstruct logic issues a `SetOption` call to SCons to disable automatically calling ninja to build. Since SCons 4.8.0, an option defined to the build (`AddOption`) can designate that the option is settable via `SetOption`. Prior to 4.8.0, a few option names were hardcoded to be settable, `disable_execute_ninja` was one of those.  In 4.8.0 that option became settable and the hardcoded name was removed:
```py
diff --git a/SCons/Tool/ninja/Utils.py b/SCons/Tool/ninja/Utils.py
index 126d5de0a..cdce92895 100644
--- a/SCons/Tool/ninja/Utils.py
+++ b/SCons/Tool/ninja/Utils.py
@@ -45,6 +45,7 @@ def ninja_add_command_line_options() -> None:
               metavar='BOOL',
               action="store_true",
               default=False,
+              settable=True,
               help='Disable automatically running ninja after scons')
```
However, since that option is defined in the ninja tool, you can't refer to that option *before* the tool is loaded, and the engine loads it after.  This trivial diff fixes it:
```py
diff --git a/SConstruct b/SConstruct
index 7deafa7ecd..a1f28b1fc6 100644
--- a/SConstruct
+++ b/SConstruct
@@ -1025,14 +1025,13 @@ if env["ninja"]:
         Exit(255)
 
     SetOption("experimental", "ninja")
+    env.Tool("ninja")
 
     # By setting this we allow the user to run ninja by themselves with all
     # the flags they need, as apparently automatically running from scons
     # is way slower.
     SetOption("disable_execute_ninja", True)
 
-    env.Tool("ninja")
-
 # Threads
 if env["threads"]:
     env.Append(CPPDEFINES=["THREADS_ENABLED"])
```

### Steps to reproduce

Add `ninja=yes` to a build line, e.g.

```bash
$ scons -j10 tools=yes ninja=yes target=template_debug platform=linuxbsd
```
leading to:
```
scons: *** This option is not settable from an SConscript file: 'disable_execute_ninja'
```

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment]
Makes sense, thanks for the heads-up!

Feel free to submit that diff as a PR to the `master` branch it you want, otherwise I'll take care of it on Monday.
