### ISSUE TITLE
CSV with semicolon delimiter can't be imported / import settings not accessible

### ISSUE THREAD

**Issue by stephanbogner** [godotengine/godot#94817]
### Tested versions

Godot v4.2.2.stable

### System information

macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

1. I exported a CSV with Mac Pages (but bug happens when creating the file manually as well)
2. (For whatever reason) this creates a CSV that use semicolons as delimiter
3. The file will show up with a red X and the import options are not available (where the delimiter type could be changed otherwise)
<img width="978" alt="Screenshot 2024-07-26 at 23 11 18" src="https://github.com/user-attachments/assets/b61b26ad-1e04-45e1-a805-d4b51737bfac">

### Steps to reproduce

1. Create a simple CSV:
```
keys;en
hero;JJ
NPC1;Mickey
```

2. Import it
3. See it appear as red

### Minimal reproduction project (MRP)

[translation-test.zip](https://github.com/user-attachments/files/16396709/translation-test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/82002.

**Comment by stephanbogner** [comment]
Ah! Didn't discover that one, thanks @Calinou
