### ISSUE TITLE
Android export failing with custom keystores and no JDK setup in the OS environment

### ISSUE THREAD

**Issue by ChrisBase** [godotengine/godot#94815]
### Tested versions

- Reproducible in:  v4.3.rc1.official [e343dbbcc](https://github.com/godotengine/godot/commit/e343dbbcc1030f04dc5833f1c19d267a17332ca9)
- Tested on: Windows 11 Pro, Version 23H2, Build 22631.3880

### System information

Windows 11 - Godot  v4.3.rc1.official

### Issue description

Export for Android fails on Windows if there is no path to a JDK set in the PATH environment variable and debug and/or release keystores have been set in the options dialg of the export window.
The error messages printed in the console looks like this:
```
Could not create child process: keytool -list -keystore ******** -storepass ******** -alias ********
Error: There was a problem validating the keystore username and password
```

The reason for this is that the static function **has_valid_keystore_credentials** in ```platform/android/export/export_plugin.cpp``` runs the hardcoded **"keytool"** command instead of using **get_keytool_path** to get the correct path that uses the ```export/android/java_sdk_path``` setting.

### Steps to reproduce

Tested on Windows

1. Ensure your PATH variable doesn't contain any JDK binary directoy
2. In Godot open ```Project > Export ...``` and select an Android export
3. Specify a Debug and/or Release keystore
4. Execute ```Export Project...```

### Minimal reproduction project (MRP)

Should be reproducable with any project

**Comment by mcdz** [comment]
![image](https://github.com/user-attachments/assets/a907bd5e-3caf-490a-9300-c81ebd57fe3f)
This error happens. Tried in RC1

**Comment by ChrisBase** [comment]
> ![image](https://private-user-images.githubusercontent.com/25784180/352778262-a907bd5e-3caf-490a-9300-c81ebd57fe3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxMjQ5NzYsIm5iZiI6MTcyMjEyNDY3NiwicGF0aCI6Ii8yNTc4NDE4MC8zNTI3NzgyNjItYTkwN2JkNWUtM2NhZi00OTBhLTkzMDAtYzgxZWJkNTdmZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDIzNTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZjY2ODVlZGM4Njg3YzA4NjczMDc5NWI4YmI4YjhlYWE2YWZiYzEyOTAyMWVmNDA2OTViNmFmODYzNGIzMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z7eAHOHyk7O-iALzVhaYjxxRQTK8KcVeU7EnHuJVGmo) This error happens. Tried in RC1. Same happened in Beta 2 & 3. not sure about B1.

You can workaround this issue by adding the path to the bin folder of a JDK is in your PATH environment variable.

**Comment by tambunancoder** [comment]
same here
