### ISSUE TITLE
Area's Ray Pickable not work in SubViewport

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#94827]
### Tested versions

v4.3.rc1.mono.official [e343dbbcc]

### System information

Godot v4.3.rc1.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

Scene Tree:
![image](https://github.com/user-attachments/assets/6638d090-d142-417d-800f-0d5f91a7ef4c)

connect Area's mouse enter and exit signal:
![image](https://github.com/user-attachments/assets/ddde899a-d772-4c93-9ca9-cbe97ba98a42)

Run:
![GIF 2024-7-27 15-41-49](https://github.com/user-attachments/assets/3b072082-13a6-436e-a2c3-688f5ae314d6)

In main viewport, it work. but in the subviewport. it can't trigger the mouse enter and exit signals.

### Steps to reproduce

Please run the MRP

### Minimal reproduction project (MRP)

[MouseTest.zip](https://github.com/user-attachments/files/16398626/MouseTest.zip)

**Comment by Chaosus** [comment]
Object Picking property should be enabled in `SubViewport` to achieve this:

![изображение](https://github.com/user-attachments/assets/e9a2bc29-65dd-48cf-9eba-861444a4a5a1)

**Comment by CsloudX** [comment]
Oh, @Chaosus Thank you so much.
