### ISSUE TITLE
The Polygon2D UV Editor's Bones not same as Skeleton bons.

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#94822]
### Tested versions

v4.3.rc1.mono.official [e343dbbcc]

### System information

Godot v4.3.rc1.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

My skeleton like this:
![image](https://github.com/user-attachments/assets/9cc84180-2d7e-4342-b9d8-60f10a725dd7)

In Polygon2D UV editor, the bones like this:
![image](https://github.com/user-attachments/assets/7e0cc723-2d61-40c6-8e1b-e0ca38a0d664)

I think it should be like this:
![image](https://github.com/user-attachments/assets/57c9160b-a0dc-4607-a473-0b155040602b)

### Steps to reproduce

Plese run open MRP and open the CharacterBody2D.tscn

### Minimal reproduction project (MRP)

[AnimStudy.zip](https://github.com/user-attachments/files/16397675/AnimStudy.zip)

**Comment by Castro1709** [comment]
As someone who has experienced that bug, the bones are wrong only at the end of each bone chain and it looks like the only property that is not well reflected is the rotation.
With that said looks like it's a dup of #87211. but looks like 2d bones / 2d skeletons are not priority at the moment
