### ISSUE TITLE
There is no PhysicalBone3D/SkeletonModifier3D migration document

### ISSUE THREAD

**Issue by Kovacs-3d** [godotengine/godot#94831]
### Tested versions

Reproducible in v4.3.rc1.official [e343dbbcc], v4.3.rc1.mono.official [e343dbbcc], 4.3 beta 3

### System information

Godot v4.3.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5186) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

In 4.2 it works great, but unfortunately in 4.3 it's completely broken. I tried several settings with **PhysicalBoneSimulator3D** and I also tried enabling **Deprecated animate_physical_bones** in Skeleton3D.
The angular velocity may be the problem. How should it be set to get it right? Could it be a bug?
**The script was based on this tutorial:**
https://www.youtube.com/watch?v=0MHY2TDeMLM

**Here Godot 4.2 work version video:**

https://github.com/user-attachments/assets/f6bbd4dd-ef78-4783-a98d-b77b753e1469

**And this video shows the 4.3 non-functional version.**

https://github.com/user-attachments/assets/338594ad-8996-4dbf-b1d5-7f3f97fc27a2

### Steps to reproduce

1.Open active_ragdoll_4.3.zip using v4.3.rc1.official [e343dbbcc] or v4.3.rc1.mono.official [e343dbbcc]，Run，wait 1 second
2.Open active_ragdoll_4.2.zip using v4.2.2.stable.mono.official [15073afe3]，Run，wait 1 second
3.Compare the differences between the two

### Minimal reproduction project (MRP)

[active_ragdoll_4.3.zip](https://github.com/user-attachments/files/16400262/active_ragdoll_4.3.zip)
[active_ragdoll_4.2.zip](https://github.com/user-attachments/files/16400264/active_ragdoll_4.2.zip)

**Comment by akien-mga** [comment]
CC @TokageItLab

**Comment by TokageItLab** [comment]
This is never a bug. Here is fixed project [active_ragdoll_4.3_fixed.zip](https://github.com/user-attachments/files/16414372/active_ragdoll_4.3_fixed.zip).

Poses modified by SkeletonModifier should be retrieved in the signal. Documentation on this https://github.com/godotengine/godot-website/pull/854 has already been written but not yet proofed and merged. cc @clayjohn @adamscott

**Comment by Kovacs-3d** [comment]
Thank you, and sorry for the inconvenience.

**Comment by Calinou** [comment]
I can confirm this on 4.3.rc e343dbbcc (Linux). I bisected the regression to 04dd299cbac614c0ff2306b8d3cd60dcd86abd8e. cc @TokageItLab
