### ISSUE TITLE
Error on the command `scons platform=linux`

### ISSUE THREAD

**Issue by DexterFstone** [godotengine/godot#94830]
### Tested versions

reproducible in 4.2.stable

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - ANGLE (AMD, AMD Radeon HD 5570 (0x000068D9) Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433) () - Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 Threads)

### Issue description

Hi, I'm working on GDExtension, when I run the command `scons platform=linux`, I get the error.
I don't know if it is a bug or if I miss something.
```
PS C:\Users\Dexter\Documents\gdextension_cpp_example> scons platform=linux
scons: Reading SConscript files ...
Auto-detected 2 CPU cores available for build parallelism. Using 2 cores by default. You can override it with the -j argument.
Building for architecture x86_64 on platform linux
scons: done reading SConscript files.
scons: Building targets ...
Linking Static Library godot-cpp\bin\libgodot-cpp.linux.template_debug.x86_64.a ...
scons: C:\Windows\System32\cmd.exe: No such file or directory
scons: *** [godot-cpp\bin\libgodot-cpp.linux.template_debug.x86_64.a] Error 127
scons: building terminated because of errors.
```

### Steps to reproduce

1. create a GDExtension
2. run the command `scons platform=linux`

### Minimal reproduction project (MRP)

N/A

**Comment by kus04e4ek** [comment]
If this is only reproducible when building [godotengine/godot-cpp](https://github.com/godotengine/godot-cpp) you should open an issue there instead

**Comment by DexterFstone** [comment]
> If this is only reproducible when building [godotengine/godot-cpp](https://github.com/godotengine/godot-cpp) you should open an issue there instead

Sorry my bad
