### ISSUE TITLE
global_position and linear_velocity somewhat intertwined

### ISSUE THREAD

**Issue by gandor999** [godotengine/godot#94846]
### Tested versions

Not sure if it was during current release

### System information

Windows x64

### Issue description

```gdscript
extends RigidBody2D

@onready var radius = ($CollisionShape2D.shape as CircleShape2D).radius

# Called when the node enters the scene tree for the first time.
func _ready():
	print(radius)
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	var mouse_x = get_global_mouse_position().x
	var mouse_y = get_global_mouse_position().y
	
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		print(global_position)
		global_position = Vector2(mouse_x, mouse_y)
		#linear_velocity = Vector2(0, 0)
		return
	pass

func _input(event):
	pass

```

I was expecting the `linear_velocity` not to increase as the mouse is held (input down left button long press) but if I run this code it does not seem that way.

I do not know if this is a bug or this is just what Godot is expected to do be on `func _process()`

### Steps to reproduce

Run this code snippet:

```gdscript
extends RigidBody2D

@onready var radius = ($CollisionShape2D.shape as CircleShape2D).radius

# Called when the node enters the scene tree for the first time.
func _ready():
	print(radius)
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	var mouse_x = get_global_mouse_position().x
	var mouse_y = get_global_mouse_position().y
	
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		print(global_position)
		global_position = Vector2(mouse_x, mouse_y)
		#linear_velocity = Vector2(0, 0)
		return
	pass

func _input(event):
	pass

```

### Minimal reproduction project (MRP)

[practice.zip](https://github.com/user-attachments/files/16401464/practice.zip)

**Comment by adamscott** [comment]
> ### Tested versions
> 
> Not sure if it was during current release

What do you mean?

**Comment by adamscott** [comment]
Please read [the notes](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#description):
> **Note:** Changing the 2D transform or [linear_velocity](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-property-linear-velocity) of a **RigidBody2D** very often may lead to some unpredictable behaviors. If you need to directly affect the body, prefer [_integrate_forces](https://docs.godotengine.org/en/stable/classes/class_rigidbody2d.html#class-rigidbody2d-private-method-integrate-forces) as it allows you to directly access the physics state.

Closing.
