### ISSUE TITLE
Touch gestures (pinch/pull zoom and scroll) and scroll wheel not working in tile editor

### ISSUE THREAD

**Issue by CyberSkull** [godotengine/godot#94849]
### Tested versions

v4.1.4.stable.mono.official [fe0e8e557], v4.2.2.stable.mono.official [15073afe3], v4.3.rc1.mono.official [e343dbbcc], v4.3.rc2.mono.official [3978628c6]

### System information

macOS 14.5 (23F79), M2 Max, v4.2.2.stable.mono.official [15073afe3]

### Issue description

The editor for tile polygons does not take either scroll wheel or trackpad touch (scroll, pinch/pull zoom in/out) gestures. It will take right or middle clicks to drag, but this is very awkward to do with a trackpad.

### Steps to reproduce

1. Create a `TileMap`, add a `TileSet`, then load a sprite sheet to and make an atlas.
2. Add any layer type, like physics for the sake of this report.
3. Select a tile to add a polygon for the layer with the `Select` tool.
4. Start editing the polygon. Try to scroll with a mouse wheel or use the trackpad scroll or zoom gestures. They do not work. It does not matter if it is the small form window or the large work area window.

### Minimal reproduction project (MRP)

[Touch gestures test for TileMap.zip](https://github.com/user-attachments/files/16401532/Touch.gestures.test.for.TileMap.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/85672.

**Comment by bypie5** [comment]
> * Related to [macOS mouse zoom (control+scroll) does not work in 2D #85672](https://github.com/godotengine/godot/issues/85672).

@Calinou the issue you linked seems resolved in 4.3

**Comment by bruvzg** [comment]
Trackpad gestures produce `InputEventMagnifyGesture` and `InputEventPanGesture` events, and neither seems to be handled by TileMap editor.
