### ISSUE TITLE
AnimationTree toggle something faster.

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#94857]
### Tested versions

v4.3.rc1.mono.official [e343dbbcc]

### System information

Godot v4.3.rc1.mono - Windows 10.0.17763 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.2849) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

My GDS like this:
![image](https://github.com/user-attachments/assets/11e6457e-d4ac-4b60-b585-5ca3d1b953c5)

Make a animation like this:
![image](https://github.com/user-attachments/assets/114f0d72-d6de-45f8-9160-c098610dc630)
Note the Node2D's flag, the key frame was "a" and "b"

when use AnimationPlayer, everything was OK.
![GIF 2024-7-28 13-41-15](https://github.com/user-attachments/assets/60e43916-7104-4064-afe3-0b5be3243045)

But when use AnitionTree:
![image](https://github.com/user-attachments/assets/4ec1292c-fd02-4539-8db7-55039b64178f)

![GIF 2024-7-28 13-46-44](https://github.com/user-attachments/assets/986ff92b-cad5-4502-8367-478f5178a947)
The Sprite2D's animation work OK, but the Node2D's flag like trigger so fast.

### Steps to reproduce

Please run the MRP

### Minimal reproduction project (MRP)

[AnimTest2.zip](https://github.com/user-attachments/files/16402343/AnimTest2.zip)

**Comment by TokageItLab** [comment]
Set CallbackModeDiscrete to `Recessive` or `Dominant` on AnimationTree
https://godotengine.org/article/migrating-animations-from-godot-4-0-to-4-3/#callbackmodediscrete
