### ISSUE TITLE
"W" Key Acting VERY Strange with Input Actions While Holding CTRL

### ISSUE THREAD

**Issue by Pixelmusement** [godotengine/godot#94866]
### Tested versions

- Reproduceable In: v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.4629) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Before I go on: This is only SOMETIMES happening to me and for the moment it seems entirely random each time I boot up the Godot Engine development environment as to if it will or won't happen. If the problem does occur it will ALWAYS occur until I close the Godot Engine entirely, then it seems to be another roll of the dice when I start it back up.

Basically, when this issue occurs, if you're holding down either CTRL key on the keyboard and attempt to push the W key to trigger an Input Action, it will not occur, though the problem is actually a little more involved depending on which keys you press/release in what order:

**Press W:** Input action occurs as intended.

**Hold CTRL -> Press W:** Nothing happens.

**Hold CTRL -> Hold W -> Release CTRL:** Nothing happens for about half a second, then the input action occurs.

**Hold CTRL -> Hold W -> Quickly Release CTRL, Hold CTRL, Release CTRL:** Nothing happens even though you're now holding W and not CTRL.

This problem seems to ONLY affect the W key. I haven't tested all 100+ keys on the keyboard but I can confirm the other 25 letters do not have this issue.

### Steps to reproduce

At present it seems entirely random if this problem will occur or not upon starting the Godot Engine. There's almost certainly a reason but I can't even remotely figure out what it is. The problem WILL persist until completely shutting down the Godot Engine; even going back to the project list doesn't resolve it.

### Minimal reproduction project (MRP)

1. Start a new project.
2. Make a 2D scene and add a Sprite2D object using the default icon.svg included in the project.
3. Open your Input Map and add in a new action which uses the W key on the keyboard. For the code below I named this action "W Key".
4. Attach a script to the Node2D for the scene and give it the following:
```
extends Node2D

func _process(delta):
	if Input.is_action_pressed("W Key"):
		$Sprite2D.set_visible(true)
	else:
		$Sprite2D.set_visible(false)
```
Now just run the project. Pressing W should theoretically always make the sprite appear but if this problem is occurring, holding either CTRL will prevent the W key from doing anything, releasing CTRL while holding W will make the sprite appear half a second later, and holding CTRL, then holding W, then releasing and quickly tapping and releasing CTRL again should prevent the sprite from appearing at all until you release W and try pressing it again.

**Comment by huwpascoe** [comment]
Do you have languages installed that use Input Method Editor? ![image](https://github.com/godotengine/godot/assets/1812087/6650378f-8b19-4920-82ac-9f411417e75b)

**Comment by Calinou** [comment]
To add to @huwpascoe's comment, also check if you have sticky keys or slow keys enabled in Windows' accessibility settings.

**Comment by Pixelmusement** [comment]
I do have the Japanese language installed which uses IME, but I rarely ever turn it on. I looked through my Windows settings just now to see if there's any hotkeys associated with the languages options but they're all blank, so I don't understand why that would have an effect on the W key specifically?

Also, ALL accessibility keys are turned off because you really can't have a gaming computer with those enabled unless you never touch the keyboard! That said, I do not have an option anywhere for "Slow Keys". If I try to search for it Windows brings me to the rest of the accessibility key settings and it's not in there.

**Comment by Pixelmusement** [comment]
OK nevermind, I finally found another game this occurs in which is NOT a Godot Engine game, meaning it's not a Godot Engine problem and thus something I need to figure out on my own. It's weird that it's so random though. :/
