### ISSUE TITLE
Console should display what was deleted when deleting a project global property

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#9488]
When deleting a global property in project settings, it would be nice if the console would output what was deleted and what value it had. I've deleted properties on accident before and this would make it a lot simpler to correct that, as otherwise I don't even know what was deleted.

**Comment by kubecz3k** [comment]
Or alternatively we could have confirmation dialog there.

**Comment by Miziziziz** [comment]
Someone in a different discussion mentioned that a confirmation dialog would make it annoying to delete multiple properties. Just restating that since it's relevant.

**Comment by kubecz3k** [comment]
Maybe if this confirmation could would have `yes` button highlighted by default so it could be accepted quickly by pressing keyboard Enter button?

**Comment by groud** [comment]
Agree with @kubecz3k, I do not see when someone would need to mass delete global properties.
A confirmation dialog seems a good idea to me.

**Comment by dalexeev** [comment]
@Miziziziz @EricEzaM 

In #45716 I delete the confirmation because deleting a setting is a cancellable action and similar confirmations are not used in other tabs of the Project Settings.
