### ISSUE TITLE
Press "S" key close any window 

### ISSUE THREAD

**Issue by Kolthas** [godotengine/godot#94892]
### Tested versions

From version 4.0.4-rc1 to Godot 4.3 rc1 (the last one you can download).

### System information

Godot v4.3.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon(TM) RX 6500 XT - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

In any window, since the program is running, every time I press the “S” key on my keyboard, the current window closes. As if I press the command ctrl+Q. Occurs in the project selection window as well.

### Steps to reproduce

Open it, press "S" key...

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can't replicate based on these instructions

**Comment by KoBeWi** [comment]
Maybe you have S assigned in `ui_cancel`.

**Comment by RingoutRingers** [comment]
I think you assigned S to a shortcut that quits the software.
