### ISSUE TITLE
Cant export games on phone.

### ISSUE THREAD

**Issue by skillz-cell** [godotengine/godot#94895]
### Tested versions

4.2 Stable

### System information

Android 14.0

### Issue description

The export table is too big, it hides the export buttons and you cant export the game as an APK.
![Screenshot_20240729_032709_Godot Editor 4](https://github.com/user-attachments/assets/e0b1bd40-7904-4dea-ba1f-30f8fdeb5810)

### Steps to reproduce

Make the table smaller.

### Minimal reproduction project (MRP)

?

**Comment by kus04e4ek** [comment]
Fixed in 4.3: #73130. However, exporting from Android is not yet supported, the support will come with this PR: #93526
