### ISSUE TITLE
How can I package all the referenced Android .so files into the APK when exporting an Android package in Godot 4 using C# so that the APK runs correctly?

### ISSUE THREAD

**Issue by bestvcboy** [godotengine/godot#94901]
### Tested versions

In my .NET project, I have referenced some third-party components that include Android packages. However, when packaging and exporting in Godot 4, the referenced .so files are not found. How can I conveniently handle this issue

### System information

Android

### Issue description

APK 

### Steps to reproduce

APK 

### Minimal reproduction project (MRP)

APK

**Comment by AThousandShips** [comment]
This is not the place to ask support questions, please use the [other community channels](https://godotengine.org/community/)
