### ISSUE TITLE
NormalizedOffset parameter for sprite

### ISSUE THREAD

**Issue by cutepig49** [godotengine/godot#9490]
Now there is only *Offset* for sprite, it is a little complex to put anchor at a sprite's feet since I need to check the height of the image to type the Y value.

How about a *NormalizedOffset* parameter? It is in range 0-1, and (when *Centered* checked)  I just need to set it (0, 0.5) to move the anchor to the sprite's feet.

**Comment by bojidar-bg** [comment]
Note: in PIXI,js, it is called `anchor`.

**Comment by mattiascibien** [comment]
I like `anchor` too

**Comment by TwistedTwigleg** [comment]
I have started working on this.
(If someone else has already started working on this, please let me know. No reason to have a duplicate pull request :sweat_smile: )

**Comment by reduz** [comment]
You can change the pivot visually in the editor without typing any number.. or did I get something wrong?

**Comment by cutepig49** [comment]
it's not only about rotation.
for example, sometimes I want to define the Y:0 as ground line, then I would put the character sprite's feet, and the ground sprite's top, at Y:0.
It would be convinient with this feature!

**Comment by mhilbrunner** [comment]
@bojidar-bg This can be closed as it was decided in #9522 not to implement this.
