### ISSUE TITLE
Editor quick open no longer allows for skipped characters, instead requires substrings

### ISSUE THREAD

**Issue by brevven** [godotengine/godot#94907]
### Tested versions

- Reproducible in v4.3.rc1.mono.official [e343dbbcc], v4.3.dev6.mono.official [89850d553]
- Not reproducible in v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.3.rc1.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Ti SUPER (NVIDIA; 31.0.15.5244) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

The "Quick Open...", "Quick Open Scene...", and "Quick Open Script..." functionality in the Godot editor will now only show results if the text entered is a substring of the name of the file. Previously, skipped letters, underscores, slashes, etc were allowed.  (eg. `node2` would show a file called `node_2d.tscn` as in the MRP below, but now it does not)

### Steps to reproduce

1. Start quick open (default `Shift + Alt + O`)
2. Start typing the name of a file, but skip one or more letters (eg. for `node_2d.tscn` type `node2`)
3. Notice that the expected file does not show up in the list (in this case `node_2d.tscn`)

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16410524/new-game-project.zip)

**Comment by KoBeWi** [comment]
This was changed in #88660
The search now uses separate words that you can write in any order instead of an occurrence substring. So instead of `node2` write `node 2`.

**Comment by brevven** [comment]
Thanks @KoBeWi  I'll close this issue.
