### ISSUE TITLE
Error previewing image in Godot:  core/io/image.cpp:2486 - Loaded resource as image file, this will not work on export.

### ISSUE THREAD

**Issue by riazey** [godotengine/godot#94905]
### Tested versions

Noticed it in 4.3 and up, including 4.3RC1 where this MPR is from.

### System information

Godot v4.3.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 Threads)

### Issue description

Engine throws an error every time I double click this texture file (Icon.png in this case) and sometimes on load, it's flooding me these days. It's also not an Image file it SHOULD be a texture2D.

I am NOT loading the image anywhere through code, and contrary to its statement it does in fact work on exports.

### Steps to reproduce

I am unsure how to reproduce this as it seems the images would just randomly break while I was using them like while making new atlas textures from my sheets with AtlasTexture for example. I noticed the errors at varying times while working on my project so it's difficult to pinpoint. Left all project settings as they are currently in my main game.

EDIT: MRP removed because it no longer contained the problem, there's probably some interaction with another asset or file or something going on hmm...

### Minimal reproduction project (MRP)
No MRP.

**Comment by AThousandShips** [comment]
You accidentally included your `.git` folder, this adds to the size and might leak sensitive information

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue with the MRP.

You mentioned issues with `icon.png` but it's not included in the MRP, the only PNG is `Graphics/HUDIcons/Game_Icons.png` but I've tried double clicking it and loading it in various nodes without errors so far.

Testing on Fedora 40 with 4.3.rc1.

**Comment by riazey** [comment]
> You accidentally included your `.git` folder, this adds to the size and might leak sensitive information
Woops, thanks for the heads up- them 4am vibes! Luckily this is a public version. I'll remove it for the next one.

> I can't seem to reproduce the issue with the MRP.
> You mentioned issues with `icon.png` but it's not included in the MRP, the only PNG is `Graphics/HUDIcons/Game_Icons.png` but I've tried double clicking it and loading it in various nodes without errors so far.

Interesting, once I closed an reopened the MRP AND the error stopped happening, I thought that was because I deleted the import but now it seems it may be connected to more than just the image., I'll do some more testing by slowly deleting things and restarting until it disappears to try and narrow it down. This project isn't the first time I've seen this error in 4.3 so I'll leave this up for now!

**Comment by riazey** [comment]
I found the source for this scenario, it's an addon called Sprite painter- easy fix turn it off when not in use! It accidentally got turned back on during testing when I did a hard reset from git. I hadn't considered that with the timing they may be separate issues from my previous projects. Ah bugcrushing.

**Comment by akien-mga** [comment]
This should likely be reported to the Sprite Painter issue tracker then, as it's likely not a Godot bug. The addon is likely loading images in a way that trigger this warning.
