### ISSUE TITLE
Editor takes a long time to load project with large amount of media files

### ISSUE THREAD

**Issue by sanlor** [godotengine/godot#94917]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce MX230 (NVIDIA; 31.0.15.3209) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

When opening an existing project with a lot of sprites, sound effects and music, the editor takes some time to open. It usually opens an empty project then it opens the actual project.
It doesn't seems to matter the size or type of the media file. If you have a lot of them, it is going to be slow. 

Using the MRP, the delay is noticeable with 22000 image files.

### Steps to reproduce

- Open the MRP.
- Take note of the time it took to open
- Run the project and generate 22000 images.
- Stop the project and wait for the files to be imported.
- Reopen the MRP
- Take note of the time it took to open

### Minimal reproduction project (MRP)

[Uploading delay.zip…]()

**Comment by AThousandShips** [comment]
> the delay is noticeable with 22000 image files.

That is an enormous number of images for any project IMO

Also you didn't upload the MRP properly, please try again and don't click away until it's finished uploading

**Comment by AThousandShips** [comment]
Five minutes to import or for it to respond? There might be some interface issues to make it more responsive but processing that many files is always going to be slow

Can you try with [rc1](https://godotengine.org/article/release-candidate-godot-4-3-rc-1/) there's been some improvement to some of the workflow 

But your message makes it a bit more clear what you are asking, the original issue didn't make it clear that the issue was more the responsiveness of the editor, importing 22 thousand files is always going to be slow, no matter how efficient we make it (even if a file takes just a few milliseconds to load it still takes several minutes)

**Comment by sanlor** [comment]
> I will check the MRP using the rc1 and see if there are any changes on the performance.

It seems that it still takes a while to load using the rc1, but now its possible to see a loading screen (which is a big improvement!)

![image](https://github.com/user-attachments/assets/57a67413-4a81-44ec-957c-bb0bc7166fbd)

```
took 67959 msecs to start.
There are 20001 files.
```

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/47053.

Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) https://github.com/godotengine/godot/pull/93064 locally? It should improve project loading speeds in projects with lots of files.

**Comment by sanlor** [comment]
> * Related to [Large projects seem frozen/crashed for several minutes on startup with poor editor feedback #47053](https://github.com/godotengine/godot/issues/47053).
> 
> 
> Can you [test](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) #93064 locally? It should improve project loading speeds in projects with lots of files. (Note that CI-provided builds are not fully optimized, so official binaries featuring would be faster.)

Thanks, I will give it a try later.

Just a quick update, I tried the MRP on a more powerful device and the loading time is still noticeable, but a lot faster. Both PCs are using SSDs.

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated Radeon (TM) RX 480 Graphics (Advanced Micro Devices, Inc.; 31.0.12042.4) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

``took 40589 msecs to start.
There are 44001 files.``

**Comment by Jordyfel** [comment]
https://github.com/godotengine/godot/issues/47053#issuecomment-2143560862

Try setting a windows defender exception for the project folder, it made a huge difference for me

**Comment by sanlor** [comment]
So, I was able to compile the #93064 , both on Windows and Linux (running under WSL on the same PC):

On Windows was still very slow, but on Linux was surprisingly fast on 4.2, 4.2 RC1 and the custom build. Not sure why.
Windows Defender was disabled for all tests below.

Godot v4.3.rc (6eddde16f) - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce MX230 (NVIDIA; 31.0.15.3209) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)
v4.3.rc.custom_build [6eddde16f]
```
took 57445 msecs to start.
There are 24000 files.
```

Godot v4.3.rc (6eddde16f) - Kali GNU/Linux Rolling 2024.2 - Vulkan (Mobile) - (software emulation on CPU) llvmpipe (LLVM 17.0.6, 256 bits) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)
v4.3.rc.custom_build [6eddde16f]
```
took 16782 msecs to start.
There are 24000 files.
```

Godot v4.3.rc1 - Kali GNU/Linux Rolling 2024.2 - Vulkan (Mobile) - (software emulation on CPU) llvmpipe (LLVM 17.0.6, 256 bits) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)
v4.3.rc1.official [e343dbbcc]
```
took 20992 msecs to start.
There are 22001 files.
```

Godot v4.2.2.stable - Kali GNU/Linux Rolling 2024.2 - Vulkan (Mobile) - (software emulation on CPU) llvmpipe (LLVM 17.0.6, 256 bits) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)
v4.2.2.stable.official [15073afe3]
```
took 17557 msecs to start.
There are 22001 files.
```

**Comment by Saul2022** [comment]
> . Not sure why. Windows Defender was disabled for all tests below.

You checked on task manage to see if there was something that was running on windows that bottleneck your loading times?

> Godot v4.3.rc1 - Kali GNU/Linux Rolling 2024.2 - Vulkan (Mobile) - 
> took 20992 msecs to start.
> There are 22001 files.

> 
> Godot v4.2.2.stable - Kali GNU/Linux Rolling 2024.2 - Vulkan (Mobile) 

> ```
> took 17557 msecs to start.
> There are 22001 files.
> ```

Interesting though why the custom build has more files in it that the  other and it weird there was not much substantial improvement aside from  better feedback on loading. The most surprising is why is 4.3 rc 1 slower than 4.2.2 stable in linux, might be the scanning stuff or something else? You can check it too on windows if it happens the same?

**Comment by Hilderin** [comment]
@sanlor can you try with your project with a build from this PR: https://github.com/godotengine/godot/pull/95678
