### ISSUE TITLE
Mouse visibility not updating until mouse is out of window.

### ISSUE THREAD

**Issue by NullNeska** [godotengine/godot#9491]
**Operating system or device - Godot version:**
Windows 10, Godot 3.0

**Issue description:**
Mouse did not become visible until i moved the mouse out of window

**Steps to reproduce:**
set mouse mode to visible after being previously confined.

**Comment by mattiascibien** [comment]
May be related to #4596 but I cannot understand what do you mean with *set mouse mode to visible after being previously confined*. Can you provide an excample project or code?

**Comment by XexisKhan** [comment]
Okay I know what you mean NullNeska.

So if you are in a scene that has default mouse mode, then switch to a scene that has MOUSE_MODE_CONFINED the cursor is no longer visible, though active.

What Null means by out of window is even if you set MOUSE_MODE_VISIBLE AFTER the set CONFINED instruction the mouse is still invisible though no longer captured so you can move it off screen to say a 2nd monitor and when the OS API picks it up it becomes visible again and when you move it back into game screen/window it is visible and functioning.

My solution was to make sure to Input.set_mouse_mode(Input.MOUSE_MODE_CONFINED) BEFORE get_tree().change_scene(new_scene_with_confined_mouse) and you won't need to set it as confined in the new scene you load, as it will stay confined.

my scenes were full screen and on windows 10 and I have 2 monitors

**Comment by Calinou** [comment]
@NullNeska Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
