### ISSUE TITLE
Atlas textures don't work with Sprite3Ds

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#9493]
**Operating system or device - Godot version:**
2.1.4-beta, at least on Linux

**Issue description:**
When setting a Sprite3D's texture property to an *.atex file, it isn't displayed properly. Sometimes you can see other parts of the texture atlas than your *.atex file represents.

**Comment by kubecz3k** [comment]
I don't think Sprite3D have support for atlas textures. Instead you should probably just load ordinary texture and have couple different uv mappings.

**Comment by timoschwarzer** [comment]
Isn't that the entire purpose of an AtlasTexture?

**Comment by kubecz3k** [comment]
@timoschwarzer afaik AtlasTexture is supporting only 2d nodes.

**Comment by KoBeWi** [comment]
Any reproduction project?
Doesn't seem to happen for me in 3.1.1

**Comment by akien-mga** [comment]
Closing as per above comment.
