### ISSUE TITLE
Game Preview Window Becomes Unresponsive on Script Error Due to Duplicate Function Declaration

### ISSUE THREAD

**Issue by calsbrook** [godotengine/godot#94962]
### Tested versions

- Reproducible in Godot Engine v4.2.2.stable.official.15073afe3

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3950X 16-Core Processor (32 Threads)

### Issue description

When running a game preview in Godot the preview window becomes unresponsive if there is an error in a script being run, such as declaring a function twice. Instead of the window becoming unresponsive in explorer.exe, it should exit more gracefully with an error message or even prevent the window from starting in the first place. The error is present in the editor before the preview has started.

### Steps to reproduce

- Make a simple 2D scene and add a script.
- In the script define the same function twice.
Example:
```gdscript
func test():
	print("Hello")
	
func test():
	print("World")
```
- Observe that the game window becomes unresponsive and must be force closed.
![image](https://github.com/user-attachments/assets/863b634c-a8ee-4ab9-9fea-d142205d9b8e)

### Minimal reproduction project (MRP)

[DeclarationCrashingDemo.zip](https://github.com/user-attachments/files/16432959/DeclarationCrashingDemo.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/69622

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
