### ISSUE TITLE
Select between overlapping nodes with Alt + Right click doesn't work in 3d

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#94963]
### Tested versions

Godot v4.3.rc1
Godot v4.3.beta1

### System information

Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) 

### Issue description

Select between overlapping nodes with Alt + Right click doesn't work in 3d. Popup menu is not showing. 

Works in 2d.
This change in behavior seems to have happen after 4.3dev6

In 4.3dev6:
![image](https://github.com/user-attachments/assets/58b7940f-8744-434f-a9d3-6834d8ebc7c3)

### Steps to reproduce

In 3d view have nodes that are overlapping. Try to select between them with Alt + Right click, no popup menu will show up.

### Minimal reproduction project (MRP)

[3d_overlap.zip](https://github.com/user-attachments/files/16433635/3d_overlap.zip)

**Comment by Giganzo** [comment]
Looking through the changelog for 4.3beta1 I found a  mention about this PR https://github.com/godotengine/godot/pull/94387 
Sounds like that should fix this

**Comment by akien-mga** [comment]
Tested, confirmed fixed by #94387.
