### ISSUE TITLE
`OS.is_process_running()` returns false for a process created with `OS.create_instance()`

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#94974]
### Tested versions

v4.3.rc1.official [e343dbbcc]

### System information

Godot v4.3.rc1 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When creating a new godot process with `OS.create_instance()` and trying to monitor its lifecycle with `OS.is_process_running()` the latter method always return false. I'm trying to find a way to wait for the child process to finish before executing more logic code, but since `OS.is_process_running()` is always returning `false` it seems impossible

This is the code that the MRP is running:

```gdscript
@tool
extends Node

func _ready():
	var path := "res://child_project/"
	var absolute_path := ProjectSettings.globalize_path(path)

	var pid := OS.create_instance(["-e", "--path", absolute_path])
	print(OS.is_process_running(pid))

	await get_tree().process_frame
	print(OS.is_process_running(pid))

	await get_tree().create_timer(1.0).timeout
	print(OS.is_process_running(pid))

	await get_tree().create_timer(5.0).timeout
	print(OS.is_process_running(pid))
```

And this is the output:

<img width="741" alt="Screenshot" src="https://github.com/user-attachments/assets/21860b34-90a4-410f-abbf-13adb6a9dbe8"><br>

The child project itself runs fine. The editor window with the correct project opens with no problem

### Steps to reproduce

1. Open the MRP project
2. It will immediately open a new editor window with another project
3. Close the editor with that project and go to the first window
4. Look at the output. It prints `false` 4 times

### Minimal reproduction project (MRP)

[MRP_is_process_running.zip](https://github.com/user-attachments/files/16440023/MRP_is_process_running.zip)

**Comment by AThousandShips** [comment]
Does it work correctly with `create_process`? The description of `is_process_running` specifically says it:
> `pid` must be a valid ID generated from `create_process`.

So either this documentation description is wrong (and something is broken) or the description is correct (and we might want to clarify this further)

**Comment by akien-mga** [comment]
> Does it work correctly with `create_process`? The description of `is_process_running` specifically says it:
> 
> > `pid` must be a valid ID generated from `create_process`.
> 
> So either this documentation description is wrong (and something is broken) or the description is correct (and we might want to clarify this further)

`create_instance` is a wrapper for `create_process`, so the documentation is correct, but exposing an implementation detail.

**Comment by passivestar** [comment]
@AThousandShips
> Also is this running from an app bundle?

Yes, this is `rc1` bundle from the website

With this substitution it works correctly, prints `true` all 4 times:
```gdscript
var pid := OS.create_process(OS.get_executable_path(), ["-e", "--path", absolute_path])
```

However, docs say that `OS.get_executable_path()` isn't cross-platform, which is why I went for `create_instance()`:

<img width="858" alt="image" src="https://github.com/user-attachments/assets/95309522-aaed-426b-bc3d-1b064458cc5d"><br>

I wonder if it means that it's somehow not guaranteed to work in some cases. Git blame points to this commit by @AdamLearns: https://github.com/godotengine/godot/commit/d7f4b07adc85e4a2de99b470380dfd65946ec1a8

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Seems like Unix `is_process_running` was changed to use PID map (in #90358), but it's not accounted when launching using macOS specific code.

**Comment by bruvzg** [comment]
> I wonder if it means that it's somehow not guaranteed to work in some cases. Git blame points to this commit by 

You can use `OS.get_executable_path()` on macOS, but launching the executable from a bundled GUI app directly can have some negative effects, e.g., main window can be unfocused on start, and app missing permissions, so it's not recommended.

**Comment by passivestar** [comment]
> You can use OS.get_executable_path() on macOS, but launching the executable from a bundled GUI app directly can have some negative effects, e.g., main window can be unfocused on start, and app missing permissions, so it's not recommended

I see. I would actually prefer to run it headlessly because I just want to parse some scripts in the child process and quit, so opening the editor window at all isn't ideal for what I'm trying to do. But unfortunately `--headless` doesn't seem to work with the editor flag, it just gets ignored. So as far as I can tell there's no way to run code headlessly with access to editor APIs. It could be useful for all sorts of automation tasks

**Comment by akien-mga** [comment]
`--headless` was broken by a regression in 4.3.rc1, but it should work in `master` or beta3.

**Comment by passivestar** [comment]
> --headless was broken by a regression in 4.3.rc1, but it should work in master or beta3.

ooh good to know, will test it out later 👍
