### ISSUE TITLE
Godot editor hangs after being idle for some time.

### ISSUE THREAD

**Issue by Jack-023** [godotengine/godot#95007]
### Tested versions

v4.2.2.stable.arch_linux

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 555.58.02) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

After leaving the editor open for a while and not interacting with it it will completely lock up. The UI becomes unresponsive and I need to restart the editor. It does seem to close upon clicking the x at the top of the window (as long as it doesn't see unsaved changes). If there are unsaved changes the popup window to confirm if you want to save appears but is visually glitched out so it can't be used. I don't have a screenshot of this but I will capture one the next time it happens.

Initially I thought this was related to screen locking but I have since experienced it while being at my PC the whole time (mostly working in an external editor or working on youtube). I have been able to work in the editor for hours without this happening so I can confirm that it is only occuring when the editor window is idle for a while. I have no idea how long before it will hang but it does happen consistently.

### Steps to reproduce

Open the editor. Leave it for some time (I think 30 mins is enough but it is obviously hard to accurately determine). Try interacting with any UI element, eg selecting nodes, panning scene view, etc. The editor does not respond at all.

### Minimal reproduction project (MRP)

I have experienced this in a project that I created to test something another person was having an issue with on Discord which had a single scene with a single node in it so it appears to be unrelated to anything in the project.

**Comment by Jack-023** [comment]
Was able to get some screenshots of this happening again. 

Here you can see the app has visual bugs when trying to resize the window after it has locked up.
![visual-bug](https://github.com/user-attachments/assets/69cffd28-35d2-411b-9db8-b4587941f572)

I also noticed that CPU% stays around 100% once it has locked up. Output from top below.
![top-cpu](https://github.com/user-attachments/assets/a2bd21a4-c0c3-4045-9a67-24967885d9a4)

**Comment by Jack-023** [comment]
I believe this issue was caused by a problem with my DE.

**Comment by bx-sa1** [comment]
I have the same problem, but in XFCE, with Xmonad as my WM. Did you ever find out what the problem with your DE was?

**Comment by Jack-023** [comment]
Sorry I don't remember what it was that tipped me off on it being related to my DE. I was looking at hyprland anyway at the time and I haven't had this since I switched.
