### ISSUE TITLE
Simple calculations in inspector integer/float inputs

### ISSUE THREAD

**Issue by xdeadmonkx** [godotengine/godot#9500]
It will be nice if inspector could understand simple calculations like 64 + 64 + 10 resulting into 138 but not 64. It will help to place GUI and other game elements faster (if you need to set it by hand in scene).
i am at version 3.0 alpha

**Comment by CowThing** [comment]
It already does this in 2.1.3, and I'd assume 3.0 as well. Addition, subtraction, multiplication, and division all work.

**Comment by akien-mga** [comment]
Actually it seems to be broken in 3.0, but since @xdeadmonkx did not respect the issue template and did not state what Godot version they were referring to, not much I can do to triage this better...

**Comment by xdeadmonkx** [comment]
i am at 3.0 version now and it is not working

**Comment by reduz** [comment]
i disabled it because something broke.. but i think a real evaluator should be made eventually :\
