### ISSUE TITLE
Child Scene's Unique Names Prevent Access to Parent Scene's Unique Names

### ISSUE THREAD

**Issue by enadream** [godotengine/godot#95018]
### Tested versions

Godot Engine v4.2.2.stable.official.15073afe3

### System information

Windows 10 - Vulkan API 1.3.242 - Godot Engine v4.2.2.stable.official.15073afe3

### Issue description

Whenever there is a unique name in the child scene, the child scene's scripts cannot access the parent scene's unique names. However, when I remove the unique names from the child scene, it starts to access the parent scene's unique names. I have attached four different photos that demonstrate the situation. There is an access problem when the child scene has its own unique names.

![setted as normal _2](https://github.com/user-attachments/assets/e3a6c014-9c17-492d-9496-e64b23d3d177)
![setted as normal](https://github.com/user-attachments/assets/147d19cd-4f99-4e33-83c0-4cbb8e2c1664)
![setted as unique _2](https://github.com/user-attachments/assets/4c5472b5-0a51-42e3-a2ed-fa3ae8a8aa38)
![setted as unique](https://github.com/user-attachments/assets/4e5f7278-f1ae-4199-9630-2522cbc0a86c)

### Steps to reproduce

1- Create a parent scene and add a node with a unique name.
2- Create another scene as a child.
3- In the child scene, create a script and try to access the unique names from the parent scene.
4- Append the child scene to the parent scene.
5- Create a unique name in the child scene and check if the parent scene's unique names can be accessed.

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/user-attachments/files/16456975/bug.zip)

**Comment by KoBeWi** [comment]
When running the attached project everything looks correctly:
![image](https://github.com/user-attachments/assets/c25706c9-064e-4870-a838-106ff08e8351)

**Comment by enadream** [comment]
Oh, really? It's still the same on my computer. Could this be related to my processor or Vulkan version?

![Capture](https://github.com/user-attachments/assets/2a76d6e5-e299-4f82-8858-2bd61b117f63)

**Comment by KoBeWi** [comment]
Maybe it's related to engine version. Try in 4.3 rc1.

**Comment by enadream** [comment]
I switched to 4.3 RC1, and my problem has been solved. Thank you! <3
