### ISSUE TITLE
Focus on global text search

### ISSUE THREAD

**Issue by nmalo80** [godotengine/godot#95010]
### Tested versions

Godot 4.2.2 Stable

### System information

Nobara Linux 40

### Issue description

When i launch the global search (CTRL + SHIFT + F) to search for text within the project, a popup window is opened. It lloks like the popup window gets the focus but the focus doesn't go to the search textfield. This is annoying as the only way to search (as far as I know) is to manually set the focus by clicking with the mouse on the search textfield.
I find myself often starting typing and realising I'm not writing.
Nothing major but it is a bit annoying.
Many thanks in avance for your help!
Fed

### Steps to reproduce

Presse CTRL + SHIFT + F
Start typing
=> you are not typing any text

### Minimal reproduction project (MRP)

Any project with at least a script in it

**Comment by LeonStansfield** [comment]
This seems like it could be a good first issue. I would like to try fixing this as a first issue if that would be okay?

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88847

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened 

This has already been fixed, please check [4.3.rc1](https://godotengine.org/article/release-candidate-godot-4-3-rc-1/) to confirm

**Comment by nmalo80** [comment]
The ticket looks good. Thank you for the very prompt reply.
