### ISSUE TITLE
ERROR: Condition "peer > 0 && !connected_peers.has(peer)" is true

### ISSUE THREAD

**Issue by makeryangcom** [godotengine/godot#95015]
### Tested versions

Godot Engine v4.3.rc1.official.[e343dbbcc]

### System information

Centos8 x86_64

### Issue description

Can confirm this problem still exists in Godot Engine v4.3.rc1.official.e343dbbcc 

![1722511842492](https://github.com/user-attachments/assets/74bdc6a0-3d5d-4bc2-9608-fc936200c48a)

```
...
multiplayer.multiplayer_peer = server_peer
multiplayer.peer_connected.connect(_on_peer_connected)
multiplayer.peer_disconnected.connect(_on_peer_disconnected)
...

func _on_peer_disconnected(client_id: int) -> void:
	print("[server:client:disconnected]", str(client_id))
	if data["players"][str(client_id)]:
		var players_node = get_parent().get_node("Players")
		if players_node.has_node(str(client_id)):
			var player_node = players_node.get_node(str(client_id))
			player_node.queue_free()
			data["players"].erase(str(client_id))
			print("[server:client:disconnected:remove]", str(client_id))
			rpc("on_remove_player", client_id)
```

### Steps to reproduce

This error only occurs when there are multiple players connected to the server; if the last player leaves the game, there are no errors.

### Minimal reproduction project (MRP)

not

**Comment by makeryangcom** [comment]
Need help！！！

**Comment by makeryangcom** [comment]
@Faless 

To facilitate your troubleshooting, my players invoke the following functions when they exit the game. Additionally, has this bug existed since 2022 and remained unaddressed? If I have 1,000 or 10,000 players, the log display will be a disaster.

```
func _on_out_game_pressed() -> void:
	print("[interface:on:out:game]")
	multiplayer.multiplayer_peer = null
	Client.on_close()
	get_tree().quit()
```

**Comment by Chaosus** [comment]
Note: If you want to help the developers to fix it faster you should create and attach a MRP.

**Comment by AThousandShips** [comment]
Where was this bug originally reported? Can you please link to any issue to see other progress in triaging this?

**Comment by makeryangcom** [comment]
@Chaosus Let me see how I can create a smaller MRP; my project is too large.

@AThousandShips his bug occurs on the server side, just as I described.

**Comment by AThousandShips** [comment]
What are you replying to? I didn't ask anything about server or client side

You said this was a long standing bug, and I assumed that this meant you had other reports on this, which would be relevant information, or do you mean you've had this bug for a long time yourself?

**Comment by makeryangcom** [comment]
@AThousandShips https://github.com/godotengine/godot/issues/70505

**Comment by AThousandShips** [comment]
Then I'll consolidate in that report, no need for a separate report, that one already has more details, please do not open duplicate reports

**Comment by makeryangcom** [comment]
@AThousandShips @Chaosus I have uploaded the minimal MPR. Please check it here: https://github.com/godotengine/godot/issues/70505

**Comment by makeryangcom** [comment]
@AThousandShips Has there been any progress on this bug? If you won't be focusing on fixing it in the short term, I won't wait any longer!

**Comment by AThousandShips** [comment]
We're focusing on releasing 4.3 which means fixing regressions introduced in that work, and please keep the discussion in the other report, or it'll be hard to track things
