### ISSUE TITLE
[AnimationPlayer] Discrepancy between 'current_animation_position' and 'current_animation_length' when animation is finished

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#95021]
### Tested versions

4.3 rc 1

### System information

Windows 11

### Issue description

There is a slight discrepancy in the properties 'current_animation_position' and 'current_animation_length' of AnimationPlayer when an animation has finished playing. 

These properties should be equal, and this was the behavior in the previous 4.3 beta 3. 

### Steps to reproduce

Create an animation in AnimationPlayer, of any arbitrary length. 

In your process function, check if the position of the animation is equal to the length of the animation. 

This value will always be false, even after the animation has finished. 

### Minimal reproduction project (MRP)

[broken-animations.zip](https://github.com/user-attachments/files/16457940/broken-animations.zip)

**Comment by akien-mga** [comment]
Probably caused by the approximate comparisons added recently.

**Comment by TokageItLab** [comment]
Since approximation should be used as the comparison method in most cases, so I believe the correct direction is to fix that cases where exact matching should be assumed, such as finished, to snap current_position to animation_length instead of using exactness in the comparison method.

**Comment by LakshayaG73** [comment]
does this bug also affect the finished signal?

**Comment by TokageItLab** [comment]
I sent https://github.com/godotengine/godot/pull/95023, check it if you can.

One possible change from pre-4.2 is that the end signal will be given only one frame earlier.

However, this means that prior to 4.2, Animation was only advancing the animation by a decimal point error at the end of the animation, meaning that there was one frame at the end of the animation where no change actually occurred. So now the signal should be fired on more accurate timing as end of the animation.

**Comment by LakshayaG73** [comment]
The original issue seems to be fixed with this PR. 

It fixes this scenario and I don't see any other issues for now.
