### ISSUE TITLE
Project manager erases project name after browsing for project path when creating a new project

### ISSUE THREAD

**Issue by mattsullentrup** [godotengine/godot#95038]
### Tested versions

- Reproducible in 4.3rc1 and rc2.
- Not reproducible in 4.3beta3 and earlier.

### System information

Godot v4.3.rc2 - Arch Linux #1 SMP PREEMPT_DYNAMIC Sat, 27 Jul 2024 16:49:55 +0000 - Wayland - GLES3 (Compatibility) - AMD Radeon RX 6600 (radeonsi, navi23, LLVM 18.1.8, DRM 3.57, 6.10.2-arch1-1) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

The project name reverts back to "New Game Project" after browsing for a project path. Also the text is highlighted after closing the browse window but nothing on the "Create New Project" window is focused. It happens on linux with the editor set to either x11 or wayland.

### Steps to reproduce

- Press "Create" button in project manager
- Type new project name
- Press "Browse" button

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Seems to be a regression from #94113, CC @jsjtxietian @KoBeWi.

I also see this error in the console when following the steps to reproduce:
```
ERROR: Attempting to make child window exclusive, but the parent window already has another exclusive child. This window: /root/@ProjectManager@1111/@EditorFileDialog@1253, parent window: /root, current exclusive child window: /root/@ProjectManager@1111/@ProjectDialog@697
   at: _set_transient_exclusive_child (./scene/main/window.cpp:949)
```

Reverting #94113 solves the error and the reported regression.

**Comment by jsjtxietian** [comment]
I will take a look asap.
