### ISSUE TITLE
Display scale has not had its settings in the settings section of the main menu on Android for several versions  

### ISSUE THREAD

**Issue by lolakQ** [godotengine/godot#95037]
### Tested versions

4.3 rc2

### System information

Android latest godot version

### Issue description

None

### Steps to reproduce

Nonevdbdbrbr

### Minimal reproduction project (MRP)

None

**Comment by Calinou** [comment]
Can you take a screenshot of the area of the editor you're referring to? I can still see **Display Scale** in the Interface > Editor section of the Editor Settings.

Are you referring to the project manager?

**Comment by lolakQ** [comment]
![Screenshot_20240801_225249](https://github.com/user-attachments/assets/2e48c910-ccd8-4f83-9733-1ef47715ac70)

**Comment by Calinou** [comment]
I can see it on Windows on 4.3.rc2:

![image](https://github.com/user-attachments/assets/25bc38d9-40de-41a8-bfdc-1949d202c295)

This does not appear to be a language-specific issue (here's the same setup but in Polish):

![image](https://github.com/user-attachments/assets/66a18e9d-80eb-49d0-9f12-438aff13924d)

cc @m4gr3d

**Comment by lolakQ** [comment]
except it's a mobile device
