### ISSUE TITLE
audio bus doesn't work when project is running

### ISSUE THREAD

**Issue by ianmckenna87** [godotengine/godot#95033]
### Tested versions

godot 4.3 release candidate 1

### System information

Godot v4.3.rc1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.5222) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

setting a bus on an audiostreamplayer appears to work correctly when playing an audio in the editor but the requested bus is ignored when project is running

### Steps to reproduce

1. add a bus from the bottom audio panel
2. create an audio stream node
3.  set the node's bus to the desired one 
4. run the project

### Minimal reproduction project (MRP)

https://github.com/user-attachments/assets/e5a687cd-e368-4682-82b5-e2bd4d51830a

**Comment by AThousandShips** [comment]
Thank you for reporting, this is a missing feature and is tracked here:
* https://github.com/godotengine/godot-proposals/issues/1186

Consolidating there

**Comment by ianmckenna87** [comment]
> Thank you for reporting, this is a missing feature and is tracked here:
> 
> * [Make the editor's audio bus editor affect the running project in real-time godot-proposals#1186](https://github.com/godotengine/godot-proposals/issues/1186)
> 
> Consolidating there

just to understand, the audio buses have no effect on audio in a project?

**Comment by AThousandShips** [comment]
My bad missed that it wasn't being edited live, reopening

**Comment by ianmckenna87** [comment]
> My bad missed that it wasn't being edited live, reopening

No worries, I'm not sure what I was doing wrong but I deleted the bus, restarted project and edited the default bus and it appears to be working now

**Comment by MJacred** [comment]
@ianmckenna87: How is it going for you? Did you have any more issues?

**Comment by AThousandShips** [comment]
Assuming this was a temporary problem, comment if you end up experiencing this again, but please add an MRP if you do so

**Comment by RedRoosterMobile** [comment]
I did some renaming with the bus and I still have that problem. it get's completely ignored. does it need to have a specific name?

**Comment by sysl-dev** [comment]
> ok, will do later:
> 
> just in case anybody has the same problem now:
> 
> I had to delete this from the .project and use the default name for the bus (default_bus_layout.tres)
> 
> [audio] buses/default_bus_layout=""

Thank you for this, I found out you can also fix this from the project settings.

Saving out a bus set with a different name appears to sometimes cause the default bus to blank?
