### ISSUE TITLE
Drag_n_Drop Broken??

### ISSUE THREAD

**Issue by New-Codeer** [godotengine/godot#95035]
### Tested versions

Pretty sure I'm using the latest version (4.0.3)

### System information

Windows 10

### Issue description

Made an asset in a separate scene and now I can't drag and drop from the node tree to the main scene in any of my new or saved projects.
Cursor icon changes to that "red not allowed circle" when I try to drag_n_drop.
already tried deleting the asset and all of its code but error still persists.

### Steps to reproduce

I have no idea what caused this but I was messing with node placement on the tree beforehand so maybe connected?
Not sure how it affected all of the saved projects though

### Minimal reproduction project (MRP)

N/A

**Comment by New-Codeer** [comment]
Extra Info: I can still make nodes that automatically enter/apply to the scene at 0,0,0 and duplicate existing nodes like normal.
I just can't drag and drop copies in any project I make or have saved which seems really weird to me

**Comment by ModularNucleus** [comment]
> Pretty sure I'm using the latest version (4.0.3)

You are not. 4.2.2 is the latest stable version. I would suggest to try with that version first, as your issue may be a bug that has already been fixed.

Also, the title of the issue is not the most helpful, I would say.

Best of luck.

**Comment by New-Codeer** [comment]
> You are not. 4.2.2 is the latest stable version. I would suggest to try with that version first, as your issue may be a bug that has already been fixed.
> 
> Also, the title of the issue is not the most helpful, I would say.
> 
> Best of luck.

My mistake I actually am using 4.2.2 not sure why I thought is was 403

Title was just my first thought because it's affecting all of my unrelated saved projects somehow

**Comment by huwpascoe** [comment]
Please can you show a full screenshot of the dragging and the red circle?

**Comment by Chaosus** [comment]
> Please can you show a full screenshot

Better if you can do a screencast using app like ScreenToGIF (https://www.screentogif.com/) and attach the resulting GIF to the post.

**Comment by New-Codeer** [comment]
Evidently my pc has hardware limitations preventing screenshots somehow, gonna look into that later

but hopefully this will work...


![Error 1](https://github.com/user-attachments/assets/997bff5f-bd38-4bc4-800a-880bcf94cf16)

**Comment by huwpascoe** [comment]
Would it be possible to get a shot of the entire Godot screen? Can't really see anything from that

**Comment by New-Codeer** [comment]
> Would it be possible to get a shot of the entire Godot screen? Can't really see anything from that

Screenshot issue fixed itself but it doesn't show the red circle bit from dragging.

![Screenshot (1)](https://github.com/user-attachments/assets/8847e3b3-abf5-4706-ab1e-e531c32df251)

![Screenshot (3)](https://github.com/user-attachments/assets/39dfba30-cca1-410a-8003-16f526b944ae)

**Comment by huwpascoe** [comment]
What's supposed to happen normally?

If instantiating a new coin in the scene, that should be coin.tscn dragged from the filesystem panel.

**Comment by New-Codeer** [comment]
> What's supposed to happen normally?
> 
> If instantiating a new coin in the scene, that should be coin.tscn dragged from the filesystem panel.

So, what's supposed to happen is I click-n-drag something from the "SceneTree" to the "World" and it would drop a new instance into the world
(coin/camera/block/floor/etc)

What's happening instead is that "red no circle" in the first pic with nothing dropping and it's happening in every project I have new and old.

After testing with blender 3.6 I found out I can take things from the "FileSystem"(lower left) and drag-n-drop it to the "World" and that'll put it into the main "SceneTree", but I get the same problem if I try dragging it directly from FileSystem to SceneTree which I was able to do before but not now.

**Comment by huwpascoe** [comment]
Perhaps a features profile was accidently created.
https://docs.godotengine.org/en/stable/tutorials/editor/managing_editor_features.html

If true, then remove profile, reset to default, etc.

**Comment by New-Codeer** [comment]
> Perhaps a features profile was accidently created. 

Just checked and there's nothing there

![Screenshot (4)](https://github.com/user-attachments/assets/b3cce222-ea83-4189-b832-2405aee5498a)

**Comment by New-Codeer** [comment]
Update:
Discovered I can't right click on anything in the world scene
I can left click normally and drag things about but nothing happens when I right click
Unsure if it's a new or related issue

**Comment by huwpascoe** [comment]
Taking everything into consideration and testing extensively, here's what I think:

Godot 3.0 default layout originally had the FileSystem dock on the left side, the Scene dock on the right.
![image](https://github.com/user-attachments/assets/80d07a37-a3a3-4247-a130-09139d2e3a33)

Either by upgrading to a new version of Godot or by resetting the layout, the FileSystem dock is now placed in the current default position: bottom-left. Breaking the familiar workflow. Dragging from the Scene into the world was never a valid action, it never instantiated a copy of the selected node - unless any long time Godot users can confirm otherwise?


Regarding the other things:

> I get the same problem if I try dragging it directly from FileSystem to SceneTree which I was able to do before but not now.

The cursor only shows disallowed if dragging on empty space, if dragging over an existing node (the root node if nothing else) then it should be allowed.

> Discovered I can't right click on anything in the world scene

Based on the screenshots, I can see that both the 2D and 3D view are being used. In 2D view, right-click brings up a context menu, in 3D view, right-click moves the camera.

**Comment by New-Codeer** [comment]
> Godot 3.0...
> Either by upgrading to a new version of Godot or by resetting the layout...

4.2 is the only one I've used and only for a few days before post and I don't think I reset the layout in the middle of using the software but idk so maybe.
If drag_n_drop from tree to world isn't normal then I'm even more confused because I know I did it a bunch before messing around in my 2D project

> The cursor only shows disallowed if dragging on empty space, if dragging over an existing node (the root node if nothing else) then it should be allowed.

I could've been mistaken on that but it's weird I remember the open tree space being a valid area.

> Based on the screenshots, I can see that both the 2D and 3D view are being used. In 2D view, right-click brings up a context menu, in 3D view, right-click moves the camera.

Actually only using the 3D view in all but 1 project which is solely 2D. The 2D view above has always been there by default upon startup.
but I do I think I'm just misremembering what right click did besides camera in 3D .


Now, I am using moderately old hardware with old OS as well so at this point I'm just thinking godot wasn't supposed to work like I saw before and randomly fixed itself halfway in.

**Comment by huwpascoe** [comment]
> 4.2 is the only one I've used

Earlier you were saying "After testing with blender 3.6 I found[...]", what was meant by that?

> Now, I am using moderately old hardware with old OS as well so at this point I'm just thinking godot wasn't supposed to work like I saw before and randomly fixed itself halfway in.

There is an "activate windows" watermark on those screenshots too, so not a typical setup... Is it just Godot, or have other things been unusual?

**Comment by New-Codeer** [comment]
> Earlier you were saying "After testing with blender 3.6 I found[...]", what was meant by that?
> There is an "activate windows" watermark on those screenshots too, so not a typical setup... Is it just Godot, or have other things been unusual?


4.2 godot and 3.6 blender are the only ones I'm using on the device and I didn't use blender until after the supposed error occured so it was a test to see if it worked right.
The rest of the system has worked as expected so far.
