### ISSUE TITLE
Add secondary alignment to BoxContainer

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#9504]
**Operating system or device - Godot version:**

The parameter `alignment` of BoxContainer works perfectly in the GUI layout.  But we still hard to control the *secondary* alignment of child nodes in BoxContainers. Like the picture shows

![BoxContainer for now](https://user-images.githubusercontent.com/6964556/27854197-60f38700-6198-11e7-8406-4b5b8043aa0c.png)

Neither the horizental alignment of nodes in VBoxContaoner nor the vertical alignment of nodes in HBoxContainer could be changed. The secondary alignment is always be `center`.

So I hope we can have another parameter to control this layout behavior like `align-items` in flexbox

![image](https://user-images.githubusercontent.com/6964556/27854502-959b5be4-6199-11e7-83d9-d40e938fdeb1.png)

**Comment by hubbyist** [comment]
Combining VBoxContainer and HBoxContainer to a BoxContainer class and calling adding a "Main alignment axis" property may make things simpler I think.

like
    MainAxis:Horizontal, Alignment:Center, SecondaryAlignment:Begin
    MainAxis:Vertical, Alignment:Center, SecondaryAlignment:End

This would simplify tree structure in complex UI designs.

WDYT?

**Comment by groud** [comment]
I don't agree, splitting VBoxContainer and HBoxContainer is more readable IMHO.

**Comment by ObaniGemini** [comment]
Adding a new argument to BoxContainers may make loose readability.

I thought like you, @Geequlim, unless I understood that anchors were handled by control nodes themselves, and that you could change their size for it fits to the (V/H)BoxContainer nodes.

This way, you handle anchors with control nodes and BoxContainer nodes does not interfere with that, and I don't see a particular case where it would be useful to have this instead of that (maybe hack-ish) solution.
I just think that this solution should be written in the docs (if it's not already done), or at least that the alignment problem/feature gets its place in the docs.

If you find a proper counter-example, then I'm for it. For now, it's a 50-50 to me (and I would choose the less time expensive solution on devs side).

**Comment by ObaniGemini** [comment]
![answer](https://lut.im/EnC8WBQ63Q/sZeg9AaxR9gDwE1p.png)

**Comment by Geequlim** [comment]
Implemented with few LOCs with #9509 for 2.1

**Comment by Geequlim** [comment]
@ObaniGemini Is the outline of the nodes in container means the size of the nodes in your pictures?

**Comment by groud** [comment]
@ObaniGemini, you mean you have to resize individually all child nodes to get them aligned ?

**Comment by Geequlim** [comment]
This feature should works with nodes in BoxContainer that  size_flag/fill is not enabled in the secondary direction.

**Comment by Geequlim** [comment]
@hubbyist I thinks it's not a good idea to remove these classes.
there are so much code in editor use VBoxContainer and HBoxContainer we don't have to change that much with this new features.

**Comment by ObaniGemini** [comment]
@groud : yes, multinode edit helps doing that

**Comment by groud** [comment]
In any case, I think the suggested feature is a good idea. Containers are here to handle their children position, having them resized is a little tricky :)

**Comment by reduz** [comment]
This came up a few times already, and I proposed an alternate solution,
which is exposing more fill options in in control, so instead of
SIZE_EXPAND|SIZE_FILL

we could use

SIZE_EXPAND,
//begin is default
SIZE_END,
SIZE_CENTER,
SIZE_FILL

**Comment by reduz** [comment]
this has the advantage that it would work in all other similar containers
automatically, as all do a call to Container::fit_rect for this.

**Comment by groud** [comment]
This may also make the CenterContainer obsolete I guess ?

**Comment by reduz** [comment]
well, there is no alternative, so I'm not sure

**Comment by groud** [comment]
I mean, having a node in a generic container, with both size flags at center.
This would be equivaltent to a node in a CenterContainer.
But I might be missing something...

**Comment by Geequlim** [comment]
BoxContainer is one of the most frequently used control type when I making gui in godot.
As it provide most of functionality like the layout solution called `Flexbox` in CSS3 or `LinearLayout` in Android.
Some feature are like this will make it better to make GUI in general conception.

**Comment by naturally-intelligent** [comment]
FYI I've found that using a second BoxContainer inside the first can solve this.  For example, when you want to align children in a VBox to the right when the default is left, you can add an HBox container first, set alignment to ALIGN_END, then add your child to the HBox.  This seems necessary if you want different children to be aligned to left or right, for example in a phone text message dialog, the left conversation is the other person and the right conversation is you.
