### ISSUE TITLE
Vector2 cannot be clamped unless both vectors are outside of the clamp

### ISSUE THREAD

**Issue by Collcroc123** [godotengine/godot#95040]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - macOS 14.5.0 - GLES3 (Compatibility) - Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

When attempting to clamp a Vector2, I expected to be able to change the vectors until EITHER X or Y was outside of the clamp's bounds. However, it continues to change and does not clamp the vectors until BOTH X and Y are outside of the clamp's bounds. I am unsure why this would be the intended behavior, unless there is a specific use case for it or an alternative feature like the one I'm attempting. Is this an intended feature or a bug?

It might be related to how Godot compares Vectors. During testing I found that "if" statements consider a Vector2 of (1, 1) to be greater than a Vector2 of (0, 200). I think it's comparing the smallest values of the vectors?

### Steps to reproduce

Place this code into a new script, attach the script to a new Node2D, then run the project and read the output.
```gdscript
func _ready():
	var vector = Vector2(0,0)
	var direction = Vector2(1,3)
	print("vector will increase by 1,3 until both numbers are 100")
	while vector != Vector2(100,100):
		vector += direction
		vector = clamp(vector, Vector2(0,0), Vector2(100,100))
		print(vector)
		await get_tree().create_timer(0.05).timeout
	print("vector was finally clamped!")
```

### Minimal reproduction project (MRP)

N/A

**Comment by BlackShift** [comment]
Still a bug with the built in clamp in global scope, but a workaround for those reading is this:
`vector = vector.clamp(Vector2(0,0), Vector2(100,100))`

I reproduced this on 4.2.1 stable

**Comment by clayjohn** [comment]
See the documentation for `clamp()`. In particular, this final note:
> Note: When using this on vectors it will not perform component-wise clamping, and will pick min if value < min or max if value > max. To perform component-wise clamping use the methods listed above.

The "method listed above" is `Vector2.clamp()` as suggested by BlackShift

**Comment by Collcroc123** [comment]
Ah, thank you. I was not aware that clamp() and Vector2.clamp() worked differently, apparently I didn't scroll down far enough to see the note 🤦‍♂️
