### ISSUE TITLE
The function information remains on the screen even if the code does not match.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#95056]
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

w10 64

### Issue description

Watch this video, the information for the "clamp" function appears.
Then I scroll using a bookmark and the information remains on the screen.

https://github.com/user-attachments/assets/618d343e-97a5-420c-ad6a-e81ec7d2024e

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

...

**Comment by hydescarf** [comment]
Reproducible on 3.5.2.stable as well. Might be an very old unnoticed bug.
