### ISSUE TITLE
The multi comment doesnt work 

### ISSUE THREAD

**Issue by Ragenorth** [godotengine/godot#95055]
### Tested versions

![Screenshot (506)](https://github.com/user-attachments/assets/6f3cd5c0-8910-4f57-b269-7ef4560ed2de)
4.2.2 The multi line comment doesn't work

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti with Max-Q Design (NVIDIA; 31.0.15.4584) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

The multi line comment doesn't work.
/* This is a comment */
This should make the above line a comment and undetected by the algorithm but it doesn't

### Steps to reproduce

Write a comment using this anywhere on any script, it should've been greyed but it won't be grey

/* hello */

### Minimal reproduction project (MRP)

[FYP PART 1.zip](https://github.com/user-attachments/files/16467331/FYP.PART.1.zip)

**Comment by Chaosus** [comment]
> /* hello */

This is syntax from C-based languages, in Godot only python-like syntax is allowed: `#`. If you want to propose the new syntax for multi-comment you should create a proposal on https://github.com/godotengine/godot-proposals rather than create it on bugtracker.

**Comment by Ragenorth** [comment]
Thank you for your explanations haha
