### ISSUE TITLE
Severe performance regression when loading many GDScript files

### ISSUE THREAD

**Issue by mihe** [godotengine/godot#95076]
### Tested versions

- Reproducible in: 4.3.rc [3978628c6cc1227250fc6ed45c8d854d24c30c30]
- Reproducible in: 4.3.beta [1ebd12ac5fdd2e99123ba00197e5d60bed541e1d]
- Not reproducible in: 4.3.beta [9db1a963beae8056cbd30d692d4160d09c10b2dc]

### System information

Windows 11 (10.0.22631)

### Issue description

After bisecting it looks like this regression was caused by #92616.

The relevant circumstances surrounding this regression aren't very clear just yet, but it seems that when manually loading a relatively big batch (hundreds) of GDScript files from within another GDScript file, using the `load` shorthand, and `new()`-ing said scripts after each `load`, there has been a significant regression both in terms of memory usage and CPU time in Godot 4.3 compared to Godot 4.2.2.

The amount of extra memory usage in the affected project is enough to cause out-of-memory crashes on certain mobile devices.

The code that seems to trigger the issue looks something like this:

```gdscript
class_name MyBaseClass
extends Resource

static func load_a_bunch_of_scripts() -> Array[MyBaseClass]:
    const scripts_root: String = "res://scripts/"

    var scripts: Array[MyBaseClass] = []
    for script_file_name in DirAccess.get_files_at(scripts_root):
        scripts.append(load(scripts_root + script_file_name).new())

    return scripts
```

The scripts being loaded mostly look like this:

```gdscript
class_name SomeClass
extends MyBaseClass

func _init() -> void:
    # Initialize a few base/super properties, maybe reference some other global classes
```

There is however likely more to the story than just that. I have tried to replicate this in a smaller project but have so far been unsuccessful, so I don't have an MRP to share just yet. It's possible that the dependency graph of these scripts play into the issue somehow.

I do however have some profiling data to share, which hopefully proves that there's some kind of regression.

Here is what [MTuner](https://github.com/RudjiGames/MTuner) reports from 9db1a963b (the parent of #92616):

![memory-good-9db1a963b](https://github.com/user-attachments/assets/8d2569c7-3b6a-4e51-912a-a22d14b08079)

Here is what MTuner reports from 1ebd12ac5 (#92616):

![memory-bad-1ebd12ac5](https://github.com/user-attachments/assets/35ee26c2-943a-4f05-a1aa-64981cdfa3f2)

Here is what MTuner reports from 3978628c6 (latest `master` as of writing this):

![memory-bad-3978628c6](https://github.com/user-attachments/assets/6f7ce2f0-75ac-4627-a458-1fd56a2ac20f)

All of these profiling sessions use largely the exact same project, and run up until the same-ish point in the application flow.

What's noteworthy is both the statistics pane up to the left, as well as the timeline pane (especially its scale) at the bottom. You should hopefully be able to see that after #92616 the memory usage is on a constant climb, and much more memory is being allocated, with a peak memory usage that's about 8x higher. When looking at the stack traces for the allocations with the highest peaks they all seem to originate from `GDScriptParser` AST constructs, such as `IfNode`, `IdentifierNode`, `FunctionNode`, etc.

The stack traces shown in the screenshots above are meant to be from the allocation that had the highest peak usage, but I've found MTuner's stack traces to be somewhat unreliable/inaccurate, at least in optimized builds like this, so I wouldn't look at them too closely.

This may also be a false lead, but MTuner does also report all of these allocations as having "leaked", meaning they were not freed by the time the application was killed (forcefully), which seems like they definitely should have been. I have tried to prove this in a debugger, but have not been able to, so take this with a grain of salt.

When looking at this from a sampling CPU profiler (like [Superluminal](https://superluminal.eu/)) it's also clear that much more CPU work is happening as well. Prior to #92616 the work done loading all these scripts took about 3 seconds on my machine, involving roughly 13,000 calls to `FileAccess::open`, which made up about 50% of the time spent. After #92616 this work instead takes about 25 seconds, with 100,000 calls to `FileAccess::open`, similarly making up about 50% of the time spent. These `FileAccess::open` calls seem to mostly be coming from `GDScriptCache::get_depended_parser_for` and `GDScriptParserRef::raise_status`, which are almost always being called from `GDScriptAnalyzer::make_global_class_meta_type`.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @vnen @rune-scape 

At this stage after two release candidates, I think we need to be more conservative and look into reverting these changes for 4.3, and rework them for 4.4.

I believe that would imply reverting:
- #92616
- #94871 (follow-up to fix a regression from the above)

I don't know if we should also revert:
- #90601 (which 92616 says to be a simple follow-up to)
or if that change is still good enough as is, and does not introduce risk of performance regressions like #92616.

**Comment by rune-scape** [comment]
ill be working on a fix for this but i definitely agree with considering reverting, i would like to fix the code that i wrote but i understand these are some unacceptable and chaotic regressions, the GScriptCache wasn't designed for this

**Comment by rune-scape** [comment]
i have a suspicion that https://github.com/godotengine/godot/issues/80637 is related

and i have a possible solution at https://github.com/rune-scape/godot/tree/fix-invalidated-parser

this is based on a suspicion that too many parsers are getting 'removed' or 'invalidated' in the cache (not so consistent naming oops)
when a parser ref gets destructed (may hapen alot when calling `load` many times), it calls `GDScriptCache::remove_parser()`
but its references are all gone, bc its a RefCounted, so it doesn't need to call that

**Comment by mihe** [comment]
@rune-scape That branch does seem to resolve most of the regression. In terms of peak memory usage and CPU time it's pretty much equivalent to the revert in #95085. There is however still an almost doubling of allocations and frees compared to the revert in #95085, or put differently, a reduction from 10x to 2x when compared to current `master`. Clearly that isn't showing any terribly detrimental effects on my Windows machine though, but I can't speak for other platforms right now.

**Comment by mihe** [comment]
When taking a closer look at the increase of `Memory::alloc_static` calls in Superluminal it seems that a big chunk of these extra allocations are coming from the `String` allocations in `vformat`. More specifically [this](https://github.com/godotengine/godot/blame/3978628c6cc1227250fc6ed45c8d854d24c30c30/modules/gdscript/gdscript_analyzer.cpp#L317) call in `GDScriptAnalyzer::resolve_class_inheritance` and [this](https://github.com/godotengine/godot/blame/3978628c6cc1227250fc6ed45c8d854d24c30c30/modules/gdscript/gdscript_analyzer.cpp#L302) call `GDScriptAnalyzer::get_class_node_current_scope_classes`.

Both of these seem to have been introduced by #94871.

I'm not sure if this is something worth trying to optimize away in the first place, given that the memory and CPU time problems seem to be largely fixed (on my machine at least) but it seems unfortunate that these context strings are being allocated even in non-error cases.

**Comment by rune-scape** [comment]
i can easily remove these calls to `vformat` while keeping the most useful info in the errors
the allocations do seem excessive, even if this is an extreme case..

PR on the way..

I think the call to `GDScriptCache::remove_parser()` in `~GDScriptParserRef()` may have been responsible for how common the regressions of these PRs were,,, not that https://github.com/godotengine/godot/pull/94871 doesn't fix anything, but i suspect it brought out the edgecases much more

**Comment by kus04e4ek** [comment]
> When taking a closer look at the increase of `Memory::alloc_static` calls in Superluminal it seems that a big chunk of these extra allocations are coming from the `String` allocations in `vformat`.

See #94558
