### ISSUE TITLE
Add a 'child_offset' attribute in the control node.

### ISSUE THREAD

**Issue by groud** [godotengine/godot#9507]
**Operating system or device - Godot version:**
3.0

Hi,
While going through the code of GraphEdit, I figured out that it did use a special offset value to place each node (the `offset` attribute within GraphNode). Consequently, this forces EditorGraph to handle GraphNodes, but no other kind of control. This is, in my humble opinion, quite a limitation. Any kind of control should be displayable on such a scrolling area.

Thus, I was wondering why not use the position value instead, but the fact is that it is used to draw each control relatively to its parent. And as its position may be a fixed value (the GraphEdit does not move), it is not easy to move of child nodes.

To simplify all of this, I wanted to suggest a new `child_offset` attribute in a control node, this would display all child nodes with the given offset. This would also enable a scrollable area with arbitrarily placed nodes (without the container, which automatically resizes the child nodes).

What do you think ?

**Comment by kubecz3k** [comment]
Not sure if I fully understand, but is it by any chance a duplicate of https://github.com/godotengine/godot/issues/5245 ?

**Comment by groud** [comment]
Hum not really, the offset I suggest would only affect the children nodes, not the drawing of the node itself.
I guess that is #5245 is more like an anchor for rotation/scaling for the node itself.

**Comment by groud** [comment]
Just to precise a little more.
The positioning of a node is, in the current system, handled from the child node using its margin and anchor values. This feature would add a part of the positioning into the parent node, which I realized may not be a proper implementation.

What I could do is use a single movable child node, with all other nodes I wanted in the container as children of this node. This would act as an offset for all those nodes.

However, this would not be very practical, as I would need to retrieve the child node every time I want to add it a child. :/ Have to think about it...

**Comment by groud** [comment]
Ok, figured out after working on the CanvasItemEditor that it does not make that much sense, and would break the current design. Closing. :)
