### ISSUE TITLE
[3.0] Ice from the material tester flashing black

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#9508]
**Operating system or device - Godot version:**
Windows 10 - Godot 3.0 build from 2017-07-05 (_bugsquad comment:_ probably 7263137dba86cd308afc2016fafcb2793c3d9073)
GPU: GTX 460
Processor: AMD Phenom II X4 965

**Issue description:**
In the material tester demo, when moving the camera around the ice (first tester from the right), it sometimes flashes black for a single frame.
It happens both in the editor and in-game.

![ice](https://user-images.githubusercontent.com/10258315/27864812-7d0b2664-6166-11e7-82a4-64081d07bb55.png)
![ice 1](https://user-images.githubusercontent.com/10258315/27864990-37eaa1da-6167-11e7-8118-6c98ddc0e75e.gif)

**Demo downloaded from here:**
https://github.com/godotengine/godot-demo-projects/archive/master.zip

**Comment by kubecz3k** [comment]
I reproduced this in 58320b7f6cfe17ad3793a9ce6981b8ce0e50ad6a on linux , gpu: GeForceGTX 1060

**Comment by kubecz3k** [comment]
seems like 1a857c514961eff16f0848a5a8b819618053e0df fixed the problem
