### ISSUE TITLE
Compatibility renderer has lower-quality (ir)radiance map generation than Forward+ and Mobile

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#95091]
### Tested versions

4.3 rc2

### System information

Windows 11

### Issue description

On forward renderer the simple `MeshInstance` with a `SphereMesh` looks like this (which is correct):

![изображение](https://github.com/user-attachments/assets/73404bbd-0b11-429e-8b35-b890fd6fc638)

On compatibility renderer it has blurpy artifacts:

![изображение](https://github.com/user-attachments/assets/b576232a-3bae-4a26-aedc-539f26337a78)

IDK if this is already reported, feel free to close if then.

### Steps to reproduce

Create a `MeshInstance3D` and assign a `SphereMesh` to it, and run that scene on Compatibility Renderer.

### Minimal reproduction project (MRP)

[TestSphere.zip](https://github.com/user-attachments/files/16478459/TestSphere.zip)

**Comment by Calinou** [comment]
This is probably just the radiance map generation being lower quality, particularly for higher roughness mipmaps. I'm not sure if much can be done about this.

**Comment by F3der1co** [comment]
> Try disabling **Texture Array Reflections** in the Project Settings, restart the editor and look at how the ambient light looks when using Forward+.

Forward renderer with Texture Array Reflections turned off:
![image](https://github.com/user-attachments/assets/fc77a9ea-4d7f-4374-be18-3915910e8ce7)
While worse still looks worlds better than on Compatability. (to me it seems like it uses a much lower resolution mip-map, which hides the blobbiness. Just a guess)

**Comment by clayjohn** [comment]
To confirm, this comes from calculating Radiance directly within the mipmaps of a single cubemap texture. In the other RD rendering methods we using a Texture array so the quality can be significantly higher. 

I suspect that we can get the same quality just by taking more samples at the lower mip levels. Effectively the reason it looks so much better is we take more samples when using texture arrays (its the same number of samples per pixel, but we have more pixels, therefore more samples). 

I'll run a quick test and see
