### ISSUE TITLE
Unable show chinese tilemap name on webbuild

### ISSUE THREAD

**Issue by rakibryan100** [godotengine/godot#95099]
### Tested versions

reproducable in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Intel(R) HD Graphics 4400 () - Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 Threads)

### Issue description

if you set the name of a tilemap using chinese characters and for some reason want to display the name in web build it shows weird characters.

### Steps to reproduce

add a chinese named tilemap > call a function to show that name in a rich text format > make a web build using compatibility settings you'll find the name is not shown

running in engine
![Screenshot (63)](https://github.com/user-attachments/assets/6aa116fc-6e15-4586-8342-3755be4e70eb)
scene tree
![Screenshot 2024-08-03 184357](https://github.com/user-attachments/assets/0aed8c19-e35d-4dfa-a8e9-b2e96e69a84e)
web build
![Screenshot (64)](https://github.com/user-attachments/assets/2b2427df-2e4d-4113-b041-d7d9cc2678d2)

### Minimal reproduction project (MRP)

[is this cell taken 2.06.07.zip](https://github.com/user-attachments/files/16481124/is.this.cell.taken.2.06.07.zip)

**Comment by rakibryan100** [comment]
Let me add if the name of tilemaps is a mixed use of english and chinese only the english part is showed properly and the cchinese part becomes like that

**Comment by Calinou** [comment]
System fonts are not supported in web builds due to browser API limitations. This is documented in [Using fonts](https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#doc-using-fonts-system-fonts).
