### ISSUE TITLE
In script view, opening scene tabs does not open their scripts

### ISSUE THREAD

**Issue by bbroens** [godotengine/godot#95094]
### Tested versions

Godot v4.3.rc2 - bug did not yet exist in 4.2.2 stable. Or at least I have not encountered it in 4.2.2

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 SUPER (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

In 4.2 the behavior was that, in script view, you could select a scene tab and then the script for that scene would appear. In other words; the displayed script would follow the active tab.

In 4.3 rc2, when I am in script view, clicking a tab does not change the displayed script into the selected scene. It just stays on whatever script it was on.

### Steps to reproduce

It should be easy to reproduce: 
1. Have any scene open in script view
2. ctrl+shift+o to open another scene
3. pick any, and the scene tab will open but the script won't.

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16479267/new-game-project.zip)

**Comment by AThousandShips** [comment]
This is by design, see:
* https://github.com/godotengine/godot-proposals/issues/8372

You need to enable this setting to restore the old behavior
