### ISSUE TITLE
Editor: Some text displays with incorrect color when Script Editor window is floating

### ISSUE THREAD

**Issue by Grublady** [godotengine/godot#95114]
### Tested versions

Reproducible in 4.3-dev6 through 4.3-rc2 and current master (3978628) on macOS 15.1 Beta (24B5009I).
Not reproducible in 4.3-dev5, prior 4.3 dev releases, or 4.2.2-stable.
Bisected to 12f39befa973ddafdfe1fef10887887b6b2442f6.

### System information

Godot v4.3.rc2 - macOS 15.1.0 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

While the Script Editor is floating in its own window, some text in the main Editor window—such as the title bar and context menu entries—appear sometimes in a black font, whereas a white font is expected.

This screen recording shows the usual (correct) behavior that occurs when the Script Editor is not floating, then the incorrect behavior that occurs when it is floating:

https://github.com/user-attachments/assets/298619f7-87c1-495e-a6f2-bde9791b9847

This recording was made on 4.3-rc2 with the editor theme set to Default.

On light themes, the effect is not noticeable because the text is already black.

### Steps to reproduce

- Open a project in the editor, using a dark theme (eg. Default)
- Pop the Scripts panel out to its own window
- Open a context menu and observe the entries' text color

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Can't reproduce it. Since it related to https://github.com/godotengine/godot/commit/12f39befa973ddafdfe1fef10887887b6b2442f6, it might be caused by corrupted theme date in the config file.

**Comment by akien-mga** [comment]
> Can't reproduce it. Since it related to [12f39be](https://github.com/godotengine/godot/commit/12f39befa973ddafdfe1fef10887887b6b2442f6), it might be caused by corrupted theme date in the config file.

Indeed, this commit just means that when you're testing a binary after that commit, it's using `editor_settings-4.3.tres`, and when testing a binary before that commit, it's using `editor_settings-4.tres`. So the difference between the two files would explain the bug.

Could you locate them and attach them here? They should be in `~/Library/Application Support/Godot/`.

**Comment by Grublady** [comment]
[editor_settings-4.tres.txt](https://github.com/user-attachments/files/16515369/editor_settings-4.tres.txt)
[editor_settings-4.3.tres.txt](https://github.com/user-attachments/files/16515370/editor_settings-4.3.tres.txt)
For uploading to GitHub I’ve added the .txt extension, and I’ve also replaced my home folder with `~` for privacy.

I see that there are differences in the theme, so perhaps that is the source of the issue.

Unfortunately I’m away from my main machine for a while so it’ll be a few days before I can try anything, but maybe someone can reproduce the behavior with these.

**Comment by Grublady** [comment]
Deleting the editor_settings files solved the issue, one of the theme settings must have been somehow corrupted.
