### ISSUE TITLE
Animation Frames For TileMaps Are Not Being Added

### ISSUE THREAD

**Issue by NathanNgo** [godotengine/godot#95127]
### Tested versions

- Reproducible in: `v4.2.2.stable.official [15073afe3]`
- Reproducible in: `v4.1.stable.official [970459615]`

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4629) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When attempting to configure animations for cells within a TileMap, they are not added and run into either:
```
editor/plugins/tiles/tile_set_atlas_source_editor.cpp:269 - Cannot add frames to the animation, not enough room in the atlas to layout 2 frames.
```
or
```
editor/plugins/tiles/tile_set_atlas_source_editor.cpp:230 - Cannot change the number of columns to 2 for tile animation. Not enough room in the atlas to layout 2 frame(s).
```
Neither of these I find to be true, as the Atlas does clearly contain enough room.

You can find an attempt here. There are two issues presented in the video below:
1. You can clearly see that when I set the number of columns to 1, and the *X* separation to 1, it selected the frame directly below it.
2. You can see that when I change the number of columns to 8, and the *X* separation to 2, then attempt to add the frames, it does not. Even accounting for the separation and the number of columns, this Atlas should contain enough room. 

https://github.com/user-attachments/assets/845c5574-e717-48bb-b8b5-74838130954c

### Steps to reproduce

1. Create a Tilemap. 64px by 64px.
2. Import the "Foam.png" image as an Atlas, letting it auto-fill the Atlas.
3. Attempt to create any amount of animated frames using column 8 and x separation 2.

### Minimal reproduction project (MRP)

[New Game Project.zip](https://github.com/user-attachments/files/16487400/New.Game.Project.zip)
![Foam](https://github.com/user-attachments/assets/7515cbae-59c3-4067-af06-fc3d8fbffb20)

**Comment by NathanNgo** [comment]
Nevermind, I misunderstood what was happening. You need to ensure the atlas doesn't have a created tile in the location you want the new frame to be.

**Comment by dreamAviator** [comment]
> Nevermind, I misunderstood what was happening. You need to ensure the atlas doesn't have a created tile in the location you want the new frame to be.

Oh my god thank you that was exactly my issue
