### ISSUE TITLE
AudioStreamPlayer not returning position on get_playback_position() on HTML5

### ISSUE THREAD

**Issue by togie14** [godotengine/godot#95128]
### Tested versions

-reproducible in v4.3.beta3.official [82cedc83c]
-not reproducible in v4.2.2.stable.official [15073afe3]

### System information

Windows 11 Godot v4.3.beta3.official [82cedc83c]

### Issue description

HTML5 export returns same value no matter what position song is at while using AudioStreamMP3, changed the AudioStreamPlayer type to the new synchronized and now i am getting correct results on exported project.  

Side note, it seems that it always returning 0.00290249427781 regardless of which song is played.

### Steps to reproduce

Create new project and add AudioStreamPlayer and Label to scene
Attach mp3 to AudioStreamPlayer and set autoplay to true
Create script that updates label.text with AudioStreamPlayer.get_playback_positon() in _process
Export to web build and test

### Minimal reproduction project (MRP)

This is a fairly easy project to create..

**Comment by AThousandShips** [comment]
Please confirm with a recent version like [rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/)

**Comment by akien-mga** [comment]
I can confirm the issue in 4.3.rc2, with both OGG and MP3 files.

MRP: [testtt.zip](https://github.com/user-attachments/files/16510010/testtt.zip)

**Comment by adamscott** [comment]
So I can confirm this issue as it cannot be implemented as is right now.*

The WebAudio API for [`AudioBufferSourceNode`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode) doesn't have a playhead parameter. The only guarantee is that we know whether a `AudioBufferSourceNode` is playing or not.

There's an existing [WebAudio API issue](https://github.com/WebAudio/web-audio-api/issues/2397).

There's a way to know that "playhead" parameter though, if we use the code that is mentioned here: https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-1193254844 ([along with a fix](https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-1887161919)).

But implementing this is 4.4 material, maybe cherry-pickable for 4.3.1.

*I know about #95197, see my comment: https://github.com/WebAudio/web-audio-api/issues/2397#issuecomment-1887161919

**Comment by akien-mga** [comment]
@adamscott If this can't be fixed for 4.3, this should be documented in the description of `get_playback_position`, so users understand why it doesn't work.

And it should probably return a sentinel value (0 or -1) instead of (seemingly?) uninitialized memory.

**Comment by adamscott** [comment]
> @adamscott If this can't be fixed for 4.3, this should be documented in the description of `get_playback_position`, so users understand why it doesn't work.
> 
> And it should probably return a sentinel value (0 or -1) instead of (seemingly?) uninitialized memory.

@akien-mga I need to test @yahkr PR, as they implemented what I wanted to do but didn't had the time to do so the last days (being not available/time with my family). I'll do this for tomorrow, so maybe this can be fixed for 4.3.
