### ISSUE TITLE
Filling values inside VS switch block is broken

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9513]
**Operating system or device - Godot version:**
Linux, 00afca31c65812ecc5dfe6c4c92627c476ea8ea5

**Issue description:**
After adding switch block it's impossible to fill case values. 
Strangely after:
```
1. Connecting input String value
2. Removing String connection 
```
it suddenly started to works as expected:
![vs_switch_case_input](https://user-images.githubusercontent.com/6129594/27869784-489b31fe-61a1-11e7-99ef-76f69b20d32a.gif)

But immediately after connecting the String input it's not working again:
![vs_switch_case_input2](https://user-images.githubusercontent.com/6129594/27870060-257911ae-61a2-11e7-8908-a5512eb47977.gif)

Also please note that I haven't found any way to fill value for `int` (and other types) inputs

**Steps to reproduce:**
Add any Switch VS Block and try to fill it's inputs for comparison.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Is this still reproducible in the current master branch?

**Comment by kubecz3k** [comment]
It seems its working correctly now
