### ISSUE TITLE
Tripled key inputs after wake from sleep using "prefer Wayland"

### ISSUE THREAD

**Issue by eobet** [godotengine/godot#95144]
### Tested versions

4.3 rc2

### System information

Godot v4.3.rc2 - Nobara Linux 40 (GNOME Edition) - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

This is me typing "test" after opening the lid on my laptop with "prefer wayland" toggled on:

![Screenshot from 2024-08-04 20-10-18](https://github.com/user-attachments/assets/48766046-5904-492a-bb3b-1a8729eaa462)

This does not always happen, but has never happened with "prefer wayland" toggled off.

No other application is affected by this (as evident from me typing this).

Typing functionality in Godot can be returned to normal by restarting the editor.

### Steps to reproduce

* Use a laptop with Linux.
* Toggle the "prefer Wayland" option on in Godot & restart.
* Put the laptop to sleep.
* ???
* Type something in the Godot editor.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
cc @Riteo

**Comment by eobet** [comment]
Here is the log.

During the session, I typed "test" into the scene search then cleared it. Closed the lid on the laptop for a while. Opened it and again typed "test" into the search (and saw "ttteeesssttt", cleared it and closed Godot.

[waylanddebug.log](https://github.com/user-attachments/files/16532912/waylanddebug.log)

**Comment by eobet** [comment]
Vacation is more important than fixing bugs! 🤍
