### ISSUE TITLE
Popup menu does not popup at indicated location

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#95151]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

v4.2.1.stable.official [b09f793f5]

### Issue description

I am trying to write a script that causes a PopupMenu to open at the location where the user right clicks the mouse.  This is an editor addon, and the popup menu is opening nowhere near the point I'm indicating.  In my original program, it wasn't even opening on the correct monitor.  In the test case I'm attaching, it is opening on the correct monitor, but no where near the point where the mouse is located.

### Steps to reproduce

Install the attached addon to the Godot editor.  Expand the `Popup Test` tab in the bottom center dock and right click in the window area.  My PopupMenu will be displayed, but in the top left hand corner of the screen.  I've tried lots of combinations of popup(), popup_on_parent() and show(), but the popup menu always opens relative to the top left corner of the screen, not the control.

### Minimal reproduction project (MRP)

[popup_location.zip](https://github.com/user-attachments/files/16489752/popup_location.zip)

**Comment by AThousandShips** [comment]
Please try with 4.2.2 to make sure this hasn't already been fixed in a supported version

**Comment by detomon** [comment]
Events in `_gui_input` are in local coordinates. `PopupMenu.popup()` expects global coordinates. Changing the code to something like this should work:

```gdscript
%PopupMenu.popup(Rect2i(get_global_transform() * e.position, Vector2i.ZERO))
```

**Comment by Calinou** [comment]
> PopupMenu.popup() expects global coordinates. Changing the code to something like this should work:

Note that this varies depending on whether embedded subwindows are enabled in the Project Settings. This can certainly catch users off-guard, which makes me wonder if we should have a `popup_relative()` method that always makes the coordinates relative to the main window's top-left corner. This way, you can have consistent operation regardless of whether single-window mode is enabled.

**Comment by blackears** [comment]
I've upgraded to 4.2.2 and am now using:

```
%PopupMenu.popup(Rect2i(get_global_transform() * e.position, Vector2i.ZERO))
```

While this is now giving me the correct vertical position on my popped up window, the popup is on the far left of the monitor regardless of the X position of the mouse.  And in my other project, the `get_global_transform() *` is not doing anything and the popup is still displaying on the wrong monitor.

**Comment by blackears** [comment]
I've modified the code to be 
```
func _on_gui_input(event):
	if event is InputEventMouseButton:
		var e:InputEventMouseButton = event
		
		if e.button_index == MOUSE_BUTTON_RIGHT:
			if e.pressed:
				print("get_global_transform() ", get_global_transform())
				print("e.position ", e.position)
				%PopupMenu.popup(Rect2i(get_global_transform() * e.position, Vector2i.ZERO))
```

I am getting this output

```
get_global_transform() [X: (1, 0), Y: (0, 1), O: (290, 758)]
e.position (572, 81)
```

**Comment by kleonc** [comment]
> I've upgraded to 4.2.2 and am now using:
> 
> ```
> %PopupMenu.popup(Rect2i(get_global_transform() * e.position, Vector2i.ZERO))
> ```

AFAICT it should be:
```gdscript
%PopupMenu.popup(Rect2i(get_screen_transform() * e.position, Vector2i.ZERO))
```
(at least seems to work)

---

Regarding event locality:

- `InputEventMouse.position` docs are clear/precise about this:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/InputEventMouse.xml#L20-L23

- `Control._gui_input` docs mention this (line 151):
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/Control.xml#L119-L152
but could be improved as Control's origin is just a single point, so _"Event position is relative to the control origin"_ doesn't say anything about the orientation/scale. It says to what point/position it's relative to but not how. Like two different Controls can have the same origin but completely different scale/rotation, and thus they would get completely different event positions.

- `Control.gui_input` (used in the MRP) docs don't mention it at all. Probably need adding a note about locality of the event, or a _"See also: ..."_ link to some more detailed docs shown above:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/Control.xml#L1094-L1099

---

Regarding `Window.popup{...}` methods I'd say none of the docs are clear about in what coordinate spaces the arguments are meant to be, with regards to the [2D coordinate systems and 2D transforms](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/2d_coordinate_systems.html#doc-2d-coordinate-systems) docs:
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/doc/classes/Window.xml#L368-L452
