### ISSUE TITLE
Strings in option buttons aren't exported when generating POT file

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [godotengine/godot#95160]
### Tested versions

v4.2.2.stable.flathub [15073afe3]

### System information

v4.2.2.stable.flathub [15073afe3]

### Issue description

POT files are automatically generated, but you have to select which scene/script you want strings to be extracted from (Btw, it would be very useful to have a search bar and an option to import folders directly. It's terrible when you have many scenes and scripts in different folders)

However, the strings used in the Text value of the button's items are not exported, thus it's impossible to localize them.

### Steps to reproduce

1. Create an optionbutton in a scene.
2. Add items with text.
3. In the project settings, localization, add your scene
4. export
5. open your POT file
6. Witness

The MRP can help you with witness.

### Minimal reproduction project (MRP)

[localization_issue.zip](https://github.com/user-attachments/files/16493367/localization_issue.zip)

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Oh great! Thanks.
I will test it when it's pushed on the stable branch.

**Comment by AThousandShips** [comment]
This isn't currently marked for cherry picking, needs to be evaluated if it's safe to do so

**Comment by Calinou** [comment]
Closing per @bruvzg's comment.
