### ISSUE TITLE
macOS complains about run project quitting unexpectedly, despite working as intended

### ISSUE THREAD

**Issue by vbettaque** [godotengine/godot#95167]
### Tested versions

- tested in v4.3.rc2 (.NET)
- not present in v4.3.rc1 (.NET)

### System information

Godot v4.3.rc2.mono - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

When I try to run/quit my project from the editor, macOS sometimes claims that it quit unexpectedly despite no signs of malfunctions. This doesn't seem to happen consistently and ultimately it is just an annoyance when debugging. The issue appeared first in v4.3r2 and was not present in v4.3r1 (using the same project). The error report that macOS provided can be found [here](https://github.com/user-attachments/files/16500196/report.txt).

### Steps to reproduce

Create a new project with a scene of any type. Running and quitting that scene repeatedly will cause the issue eventually.

There seems to be no consistent pattern for when the error occurs. Sometimes it occurs when the project is run, sometimes it occurs when the project is quit (with no changes made). Issue seems to occur in all projects.

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Seems to be caused by https://github.com/godotengine/godot/pull/94978, seems like for some unknown reason editor is trying to kill running process even if it's exiting normally (and unlike `SIGKILL`, `forceTerminate` result in crash message).

**Comment by akien-mga** [comment]
EditorRun seems to rely on `OS::kill` to stop the running project:
```cpp
void EditorRun::stop_child_process(OS::ProcessID p_pid) {
        if (has_child_process(p_pid)) {
                OS::get_singleton()->kill(p_pid);
                pids.erase(p_pid);
        }
}

void EditorRun::stop() {
        if (status != STATUS_STOP && pids.size() > 0) {
                for (const OS::ProcessID &E : pids) {
                        OS::get_singleton()->kill(E);
                }
                pids.clear();
        }

        status = STATUS_STOP;
        running_scene = "";
}
```

**Comment by bruvzg** [comment]
It's calling `kill` it even if you close the running project window, not only when using `Stop` button in the editor.
