### ISSUE TITLE
Ability to right-click resource box in the Inspector to access its menu

### ISSUE THREAD

**Issue by homer666** [godotengine/godot#9517]
Version: Godot 3.0 (master)

![screenshot from 2017-07-06 02-40-35](https://user-images.githubusercontent.com/27100585/27875256-e1eead8c-61f5-11e7-930a-3e2c956422ff.png)

Right now that menu is only accessible by clicking on the little arrow, but I think adding the ability to just right-click the entire box would help a little with productivity. I'm not necessarily saying the arrow should be removed, but having a sort of context menu appear upon being right-clicked would be fairly intuitive to most.

**Comment by suptoasty** [comment]
I also mentioned this here #9052. It was assigned as a junior job.

**Comment by homer666** [comment]
Yikes, can't believe I missed that. Sorry, closing this.
