### ISSUE TITLE
Saving imported mesh to .tres changes geometry

### ISSUE THREAD

**Issue by aristides86** [godotengine/godot#95177]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Win10

### Issue description

When importing obj made in Blender, making it unique and saving as .tres geometry becomes slightly warped. Location of vertices changes and meshes no longer align together.
![image](https://github.com/user-attachments/assets/c244344d-4654-46af-8c07-6bc8f8ca7ccb)

### Steps to reproduce

[Terrain_01_GEO.zip](https://github.com/user-attachments/files/16504234/Terrain_01_GEO.zip)
Import obj into Godot 
![image](https://github.com/user-attachments/assets/54ce59d4-3b18-4216-9633-0a0eb6eb2e3e)
Place the mesh into a new scene. From inspector make the mesh unique. Save it as .tres 
In the project I collect meshes into a mesh library for a gridmap. Original objs align perfectly, but new treses produce gaps between tiles.

### Minimal reproduction project (MRP)

no need

**Comment by AThousandShips** [comment]
Does this occur with "optimize mesh" turned off?

**Comment by aristides86** [comment]
Looks like that's the problem. It doesn't seem to warp the mesh with Optimize disabled.

**Comment by Calinou** [comment]
> Looks like that's the problem. It doesn't seem to warp the mesh with Optimize disabled.

I don't see why that would happen, considering that import option does literally nothing: https://github.com/godotengine/godot/pull/94100

**Comment by aristides86** [comment]
You probably right. I'm trying to recreate it again and it's not happening anymore.
