### ISSUE TITLE
Cannot animate more than one property on AnimatableBody2D with Sync to Physics enabled

### ISSUE THREAD

**Issue by afterlightgames** [godotengine/godot#95188]
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

Godot v4.3.rc2 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.5599) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When attempting to animate more than one property of an AnimatableBody2D node (eg position and rotation), only one animation track will ever play as long as Sync to Physics is enabled on that AnimatableBody2D. This is detrimental as the Sync to Physics property is important for snapping CharacterBody2Ds to AnimatableBody2Ds without them lagging behind slightly, which can cause undesirable side effects for moving platforms in 2D games for example.

### Steps to reproduce

- Add an AnimatableBody2D to the scene.
- Add a collision shape to it for visual reference.
- Create an AnimationPlayer and keyframe some different positions and rotations for the AnimatableBody2D at different times.
- Enable Autoplay on Load for the animation.
- Play the animation in the editor; it plays as expected.
- Save and run the project with visible collision shapes enabled; Only one of the animation tracks will ever play.
- Uncheck Sync to Physics on the AnimatableBody2D and run the project again; animation plays normally.

### Minimal reproduction project (MRP)

[AnimatableBody2D MRP.zip](https://github.com/user-attachments/files/16507020/AnimatableBody2D.MRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/76287

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
