### ISSUE TITLE
EditorInterface.get_selected_paths() does not return selected files while in split mode

### ISSUE THREAD

**Issue by imberny** [godotengine/godot#95181]
### Tested versions

4.2.2.stable

### System information

Manjaro Linux - Godot 4.2.2.stable

### Issue description

While the editor's filesystem dock is in split mode, selected files in the lower dock can't be gotten be EditorInterface.get_selected_paths(), only the selected directories above can.

### Steps to reproduce

- In the MRP, enable the filesystem dock's split mode.
- Open the get_selected_paths.gd editor script. It prints all selected paths.
- Open the "directory" directory.
- Select "file1.gd" in the lower dock.
![image_2024-08-05_230819229](https://github.com/user-attachments/assets/4a0a64b1-4d52-4abe-9187-b49ad14e4785)

- Run the editor script.

Result: only "res://directory" is printed
Expected: "res://directory/file1.gd" should be printed.

Personally, I think the selected files should have priority, i.e. when both a directory in the upper dock and files in the lower dock are selected, only the files should be returned by get_selected_paths().

### Minimal reproduction project (MRP)

[get_selected_paths.zip](https://github.com/user-attachments/files/16504687/get_selected_paths.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/88228

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
