### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by makeryangcom** [godotengine/godot#95182]
### Tested versions

v4.3.rc.custom_build [3978628c6]

### System information

Centos8

### Issue description

I used Ubuntu 20.04.5 to export a dedicated server, and when running the exported game server on CentOS 8, the following error occurred:

```shell
-- Logs begin at Sat 2024-08-03 08:26:07 CST. --
Aug 06 11:58:04 game systemd[1]: Started Engine.
Aug 06 11:58:04 game engine.x86_64[2935612]: /data/wwwroot/engine/engine.x86_64: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /data/wwwroot/engine/engine.x86_64)
Aug 06 11:58:04 game systemd[1]: engine.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 11:58:04 game systemd[1]: engine.service: Failed with result 'exit-code'.
Aug 06 11:58:04 game systemd[1]: engine.service: Service RestartSec=100ms expired, scheduling restart.
Aug 06 11:58:04 game systemd[1]: engine.service: Scheduled restart job, restart counter is at 5.
Aug 06 11:58:04 game systemd[1]: Stopped Engine.
Aug 06 11:58:04 game systemd[1]: engine.service: Start request repeated too quickly.
Aug 06 11:58:04 game systemd[1]: engine.service: Failed with result 'exit-code'.
Aug 06 11:58:04 game systemd[1]: Failed to start Engine.
```

```shell
# Ubuntu 20.04.5
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

```shell
# Centos8
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Which version of the operating system should I use for compilation?

### Steps to reproduce

I used Ubuntu 20.04.5 to export a dedicated server, and when running the exported game server on CentOS 8

### Minimal reproduction project (MRP)

not

**Comment by qarmin** [comment]
This is expected.
You should create binary on system with lowest glibc version as possible and you will be able to run app on systems with same or greater version of glibc 
```
    Ubuntu:
        Ubuntu 18.04 LTS (Bionic Beaver): glibc 2.27
        Ubuntu 20.04 LTS (Focal Fossa): glibc 2.31
        Ubuntu 22.04 LTS (Jammy Jellyfish): glibc 2.35

    Debian:
        Debian 9 (Stretch): glibc 2.24
        Debian 10 (Buster): glibc 2.28
        Debian 11 (Bullseye): glibc 2.31
        Debian 12 (Bookworm): glibc 2.36

    CentOS:
        CentOS 7: glibc 2.17
        CentOS 8: glibc 2.28
        CentOS Stream 8: glibc 2.28
        CentOS Stream 9: glibc 2.34

    Fedora:
        Fedora 33: glibc 2.32
        Fedora 34: glibc 2.33
        Fedora 35: glibc 2.34
        Fedora 36: glibc 2.35

    RHEL (Red Hat Enterprise Linux):
        RHEL 7: glibc 2.17
        RHEL 8: glibc 2.28
        RHEL 9: glibc 2.34
```

**Comment by makeryangcom** [comment]
> This is expected. You should create binary on system with lowest glibc version as possible and you will be able to run app on systems with same or greater version of glibc
> 
> ```
>     Ubuntu:
>         Ubuntu 18.04 LTS (Bionic Beaver): glibc 2.27
>         Ubuntu 20.04 LTS (Focal Fossa): glibc 2.31
>         Ubuntu 22.04 LTS (Jammy Jellyfish): glibc 2.35
> 
>     Debian:
>         Debian 9 (Stretch): glibc 2.24
>         Debian 10 (Buster): glibc 2.28
>         Debian 11 (Bullseye): glibc 2.31
>         Debian 12 (Bookworm): glibc 2.36
> 
>     CentOS:
>         CentOS 7: glibc 2.17
>         CentOS 8: glibc 2.28
>         CentOS Stream 8: glibc 2.28
>         CentOS Stream 9: glibc 2.34
> 
>     Fedora:
>         Fedora 33: glibc 2.32
>         Fedora 34: glibc 2.33
>         Fedora 35: glibc 2.34
>         Fedora 36: glibc 2.35
> 
>     RHEL (Red Hat Enterprise Linux):
>         RHEL 7: glibc 2.17
>         RHEL 8: glibc 2.28
>         RHEL 9: glibc 2.34
> ```

This is very detailed; thank you for your help. Additionally, I would like to ask if there are any relevant documents for compiling on CentOS 8, as the official documentation seems not to cover the compilation methods for CentOS.

**Comment by Chaosus** [comment]
Closed since its resolved.
