### ISSUE TITLE
Event metadata is missing in `_input()` when events are passed through `Input.parse_input_event()`

### ISSUE THREAD

**Issue by dhoverml** [godotengine/godot#95205]
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

Ubuntu 20.04 LTS

### Issue description

See title.

### Steps to reproduce

Create a node, attach the following script, and run
``` gdscript
func _ready():  
  var test = InputEventMouseButton.new()
  test.set_meta("test", 123)
  Input.parse_input_event(test)

func _input(event: InputEvent):
  if event is InputEventMouseButton:
    print(event.get_meta("test", "(nothing)"))
```

Output:
```
(nothing)
```

**Note**
This occurs due to the event being cloned with `xformed_by()` (like [here](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1328) and [here](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1760)), but `xformed_by()` does not copy the metadata.
Some overrides of `xformed_by` [copy the pointer](https://github.com/godotengine/godot/blob/master/core/input/input_event.cpp#L94) (this is technically a bug, since it looks like callers expect a new instance), while others do a copy but forget to copy the metadata, like [InputEventMouseButton::xformed_by](https://github.com/godotengine/godot/blob/master/core/input/input_event.cpp#L736)

### Minimal reproduction project (MRP)

N/A

**Comment by Yelloween10** [comment]
Hi! I'm currently working on fixing this issue and have made some progress. However, I'm a bit confused by the note regarding xformed_by() not copying the metadata. I’ve looked into InputEventMouseButton::xformed_by() and added the necessary metadata copying, but I'm unsure of how I can continue or where else I should focus my attention to fully resolve the problem.

Should I be focusing specifically on ensuring metadata is preserved across all event types, or is there a particular part of Input.parse_input_event() that might need further investigation?

**Comment by dhoverml** [comment]
> Should I be focusing specifically on ensuring metadata is preserved across all event types

This issue occurs with every input event, not just `InputEventMouseButton`.
So I believe if every override of `xformed_by` copies the metadata, then this bug is fixed.

I suggest to add a public method to `Object` or a protected method in `InputEvent`, and call that method in `xformed_by`, to avoid redundant code.  Though I'm not a maintainer and there could be other opinions.

Additionally, and not exactly this bug, I think every override of `xformed_by` should be reviewed.  I suspect that callers expect a copy of the input event, and some of the implementations ref-count the pointer instead.

**Comment by Yelloween10** [comment]
I've applied metadata copying to all `xformed_by()` overrides in `InputEvent`, but I have a couple of questions for clarification:

For overrides like `InputEvent::xformed_by()` that currently copy the pointer:
Should these be creating new instances of the input event with transformations applied? Or is there a specific reason they return the same pointer? What would be the correct approach here?

For `InputEvent` functions that don’t have an `xformed_by()` override:
Should these functions also involve metadata copying, or are they unrelated to the transformations being handled by `xformed_by()`?

Apologies for the questions, this is my first issue and I want to make sure that I don't mess up.

**Comment by dhoverml** [comment]
> For overrides like InputEvent::xformed_by() that currently copy the pointer:
Should these be creating new instances of the input event with transformations applied? Or is there a specific reason they return the same pointer? What would be the correct approach here?

I think they should do a copy, and not ref count the pointer.  Changing this _will_ change existing behavior, for better or worse.  I don't know the right call here.  We may need a maintainer to chime in.

> For InputEvent functions that don’t have an xformed_by() override:
Should these functions also involve metadata copying, or are they unrelated to the transformations being handled by xformed_by()

I think they should be; it would have to be added to `InputEvent::xformed_by`

**Comment by Sauermann** [comment]
@Yelloween10 

> Hi! I'm currently working on fixing this issue and have made some progress. However, I'm a bit confused by the note regarding xformed_by() not copying the metadata. I’ve looked into InputEventMouseButton::xformed_by() and added the necessary metadata copying, but I'm unsure of how I can continue or where else I should focus my attention to fully resolve the problem.

Thank you for putting effort into this!
Every `InputEvent***::xformed_by` function, that instantiates a new input event, needs to be adjusted, so that it copies the metadata to the new object.

> Should I be focusing specifically on ensuring metadata is preserved across all event types, or is there a particular part of Input.parse_input_event() that might need further investigation?

In `Input::_parse_input_event_impl` there are 4 places regarding mouse<->touch event emulation. These 4 instances should also contain code, that preserves the meta-data.

> For overrides like `InputEvent::xformed_by()` that currently copy the pointer:
> Should these be creating new instances of the input event with transformations applied? Or is there a specific reason they return the same pointer? What would be the correct approach here?

I believe it is fine, that they don't create a new instance. It is simply faster, than creating a new instance and simply copy everything without changing anything.

> For `InputEvent` functions that don’t have an `xformed_by()` override:
> Should these functions also involve metadata copying, or are they unrelated to the transformations being handled by `xformed_by()`?

Some input event types don't have an `xformed_by` override, so they use `InputEvent::xformed_by`. Since that function returns a pointer to the original object, no adjustments are necessary, because it already contains the metadata.

**Comment by Yelloween10** [comment]
Thanks for the clarification! I'll start working on it when I'm available.

**Comment by Yelloween10** [comment]
I'll continue working on this, I'm interested and I was just waiting for clarification.
