### ISSUE TITLE
Control node enhancement

### ISSUE THREAD

**Issue by groud** [godotengine/godot#9520]
After a discussion with @kubecz3k on the IRC, we came with several enhancements that could be made to the Control node. Most are inspired from the Unity Rect Transform component (https://docs.unity3d.com/Manual/UIBasicLayout.html).

- [x] Add a pivot point for both rotation and scale
- [x] Replace anchors begin/center/end by a float value between 0 and 1 (should break compatibility :/) 
- [x] This probably means keeping the margin the same sign. For now the margin is set as the distance to the right side when anchored right. This should be negative, as it left to the right side.
- [x] Add a visualization for the anchor
- [x] Allow the anchors to be dragged
- [x] Add a vizualisation for the pivot point
- [x] Add a grow direction (Done, but I can't understand what this does... ^^) ?

Related: #5245, #5775, #4339, and maybe #7654, #8525, #2965

**Comment by Zireael07** [comment]
Oh yeah, pivot please!

**Comment by reduz** [comment]
A rotation pivot should be rather easy to implement. Also an anchor visualization is a pretty good idea.
We had ratio anchoring before begin/center/end and it was removed because it sucked and was not that useful. Current approach is probably good enough, as for more complex behaviors Containers are better.

**Comment by reduz** [comment]
What is actually missing from this list IMO is the following:

-More options for container fitting (fill/begin/end/center)
-Expand Direction for anchors, so controls anchored to the right can expand to the left.

**Comment by groud** [comment]
> We had ratio anchoring before begin/center/end and it was removed because it sucked and was not that useful. Current approach is probably good enough, as for more complex behaviors Containers are better
I don't agree on that, in some (specific, I agree ^^) situations this can be useful. 
A floating anchor would make sense if the visualization tool could also make available the anchor dragging. The shift key could also be used to snap the anchor to begin/center/right while dragging it (or maybe the default could be snapping, and the shift key for fine adjust). Note that the anchor menu keeps most basic alignements simple, that does not change.

Actually, I allready implemented it. By defining the ANCHOR_BEGIN, ANCHOR_END and ANCHOR_CENTER as float constants this also keep the code part simple and understandable. 
It just adds more flexibility :)

> -More options for container fitting (fill/begin/end/center)
Ok with that, maybe we could replace the flags by an enum of possible behaviour ? Something like:
- Fill
- Expand
- Anchor to begin
- Anchor to center
- Anchor to end
Because the begin/end/center flags would mutually exclude :)

> -Expand Direction for anchors, so controls anchored to the right can expand to the left.
I dont get this one

**Comment by groud** [comment]
Btw, this is my humble opinion, but the way the control system is built is now becoming quite complicated... I might be the only one to think that, but now that we have the fill/expand/begin/center/end  flags for the container, this flags system starts to look like the anchoring system. This introduce a kind of redundancy which does not help understanding the control system.

So I was thinking that maybe this flag system could be removed, and replaced by the base anchor system. I explain myself:
- We keep the expand flag and the size ratio, to notify a container that the node should take as much space as possible, and how much if multiple are present.
- We remove the fill/begin/center/end flags
- Instead, we use the anchoring system to place the node into a rect given by the container. What this means is that the parent rect used to position the anchors would be instead replaced by another rect given by the parent.
Also,
- Maybe we could also provide a set of helpers to position a node, like the anchor menu but that would move the node

This would create a lot more flexibility into the system, and should remove some options in several controls, such as the secondary alignment into BoxContainers.

What do you think ?

**Comment by groud** [comment]
Most of this issue have been adressed by #9889. Closing.
