### ISSUE TITLE
[WebSocket] "Unable to set TCP no delay option" error on Windows

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#95217]
### Tested versions

Reproducible in Windows 4.3rc2; Not reproducible in Windows 4.3beta3

Not reproducible on MacOS 4.3rc2.

### System information

Windows 10

### Issue description

The error is thrown on Windows only, not MacOS.

The error happens with or without calling `WebSocketPeer.set_no_delay(true)`

In #94618, reverting the `p_tcp->set_no_delay(true);` at line 115 in `WSLPeer::Resolver::try_next_candidate()` to its previous location at line 102 eliminates the error.

```
E 0:00:12:0447   client.gd:197 @ poll(): Unable to set TCP no delay option
  <C++ Source>   drivers\unix\net_socket_posix.cpp:708 @ set_tcp_no_delay_enabled()
  <Stack Trace>  client.gd:197 @ poll()
                 client.gd:285 @ _process()


E 0:00:12:0530   client.gd:142 @ connect_to_server(): Unable to set TCP no delay option
  <C++ Source>   drivers\unix\net_socket_posix.cpp:708 @ set_tcp_no_delay_enabled()
  <Stack Trace>  client.gd:142 @ connect_to_server()
```

### Steps to reproduce

Connect to a server via WebSocketPeer.connect_to_url() with `TLSOptions` not null and poll the client. I have not tested without TLS.

### Minimal reproduction project (MRP)

NA

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
Seems like yet another case of Windows having a completely broken socket stack: https://github.com/redis/hiredis/issues/785 .
