### ISSUE TITLE
Deadzone slider not working in input map menu

### ISSUE THREAD

**Issue by Castro1709** [godotengine/godot#95223]
### Tested versions

Tested in 4.3 rc2 and 4.2.2

### System information

Windows 11, CPU/GPU AMD Ryzen 7 5700U

### Issue description

When you go to the input map menu, where you set up the input actions of your game, every input action has a deadzone parameter.
The UI of this parameter is a spin box but, there's also a slider when you click the deadzone value.
This slider doesn't work (meaning it doesn't change the deadzone value) but it looks like it only works in the first click.

https://github.com/user-attachments/assets/170a5352-b68e-4113-b246-826e78e0f29f

### Steps to reproduce

* Go to project -> project settings -> Input map
* Add a new action
* Click the deadzone value and move around the slider

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.3.rc 33fe10c06 (Linux X11).

**Comment by Giganzo** [comment]
There is a comment here https://github.com/godotengine/godot/issues/80556#issuecomment-1699555579 that I believe is about the deadzone slider

**Comment by Calinou** [comment]
> There is a comment here [#80556 (comment)](https://github.com/godotengine/godot/issues/80556#issuecomment-1699555579) that I believe is about the deadzone slider

My guess is that the input map editor automatically saves whenever *any* change is made, so clicking the deadzone slider changes the value and causes a settings save, which causes the popup to be closed.

**Comment by kerstop** [comment]
Ive been looking at this issue, and yes the problem is that any change to the slider causes a save. Saving causes the action list to be rebuilt which causes a reference contained in `Tree::popup_edited_item` to become null. In the next few days I will try to make the popup only save when it is closed.
