### ISSUE TITLE
Import existing project isn't working properly

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#95234]
### Tested versions

4.3 rc2

### System information

Windows 11

### Issue description

Any attempt to import any project is prevented by this dialog with an error message:

![изображение](https://github.com/user-attachments/assets/9b372a1e-b444-45b3-bb1d-e55fb732e22c)

Scanning or opening it directly are the only options now to import it to project list.

### Steps to reproduce

Try to import an existed project through Project Manager.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
I can't seem to reproduce the issue in 4.3.rc2. The "Create Folder" button isn't present in the Import dialog for me:

![image](https://github.com/user-attachments/assets/b71ad57b-a76c-4303-ac01-3418af959e3f)

**Comment by akien-mga** [comment]
Bisected to 116a457542d48ea11339edb25da6eef76de34226 / #95062, CC @KoBeWi.
