### ISSUE TITLE
PhysicalBoneSimulator3D child being added to Skeleton3D by Engine always

### ISSUE THREAD

**Issue by samsface** [godotengine/godot#95238]
### Tested versions

4.3-rc2: bug happens 
4.3-dev-5: does not

### System information

Ubuntu 22.04.2 LTS with Godoto 4.3-rc2

### Issue description

When you instance a scene with a Skeleton3D, the engine automatically adds a PhysicalBoneSimulator3D as a child of the Skeleton3D.

This caused issues in my project because my code was iterating over the Skeleton3D's children, expecting their types to match those shown in the editor scene tree.

![image](https://github.com/user-attachments/assets/89247776-12af-44c5-adff-2ecdeafd840d)

### Steps to reproduce

1. Add a Skeleton3D to a scene in the editor.
2. Add MeshInstance as a child to the Skeleton3D in the editor.
3. Run the scene

Expected:
- The remote scene tree should show a Skeleton3D with just a MeshInstance as the only child.

Actual:
- The remote scene tree shows there has been a PhysicalBoneSimulator3D added.

### Minimal reproduction project (MRP)

[bug-repo.zip](https://github.com/user-attachments/files/16521386/bug-repo.zip)

**Comment by AThousandShips** [comment]
This should have been made internal as it was listed as internal in the documentation, will write a fix
