### ISSUE TITLE
various issues with obj importer

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#9524]
**Operating system or device - Godot version:**
Linux Mint and Win10

**Issue description:**
Bug 1: 
When obj meshes are imported there is a visible shading discontinuity along the uv seams. However the same mesh imported as a dae/collada is fine. The meshes have been exported from blender.
See project file and image below.

Bug 2:
Most likely related to the above issue, but while this model has no uv's, the vertex normal information is not importing from the obj correctly. It looks similar to if the model in blender has the "autosmooth" normals button turned off. That is, it has smooth shading on, but the normals are being auto detected rather than using the custom normals information. As a test I imported this obj (from blender) into Unity, Substance, Cinema 4d, Houdini as well as back into blender. They all imported it correctly.
See project file and image below.

Feature Request:
The ability to import material groups/polygon selections via the obj importer. Blender and other packages support obj export via the "material groups" flag in the exporter. This allows 2 or more polygon/material selections for a single mesh.

Ideally Godot would be able to import a single obj mesh into a scene and expose these material groups, in the same manner that dae import works. This would allow separate materials for each material group. As far as I can tell, the material selection poly faces are tagged in the .obj file and the .mtl is not actually required unless there is need for the actual material(color, spec, etc) information.

I have included a basic blender file with an object split into 3 material groups. These should import into blender as the same 3 groups, and with the color (red, green, blue) information if there is also a .mtl file. The .mtl file should be considered as optional, since the user may not need the original material properties just to get the material group selections. Having a .mtl for every .obj file could clutter up a project, so it should be up to the user.

![basic_obj_material_selections](https://user-images.githubusercontent.com/7741669/27942104-d93ba398-6317-11e7-83fd-ef56ef264b15.jpeg)
[basic_obj_material_selections.blend.tar.gz](https://github.com/godotengine/godot/files/1129914/basic_obj_material_selections.blend.tar.gz)

**Steps to reproduce:**
Import an obj mesh and add material and environment.

**Link to minimal example project:**
Bug1: This scene shows a sphere on left imported as dae with no artifact. The sphere on right is from obj importer and shows the uv seam artifact.

![obj_seams](https://user-images.githubusercontent.com/7741669/27893421-e5f9ee16-6248-11e7-8a33-9dfdeca12e9a.jpeg)

[uvseam_test.tar.gz](https://github.com/godotengine/godot/files/1126607/uvseam_test.tar.gz)

Bug2: This screencap shows Blender(far left is the model as it should be with correct normals, next to it is the same model with "autosmooth" normals toggled off) and Godot3 (displaying the model imported as an obj with incorrect normal information). The zip file contains the blender file and the exported .obj

![cubish2_compare](https://user-images.githubusercontent.com/7741669/27981607-d0c19ab4-63d1-11e7-8893-14cbbed196a7.jpeg)

[cubish_obj_normals_comparison.tar.gz](https://github.com/godotengine/godot/files/1132671/cubish_obj_normals_comparison.tar.gz)

**Comment by reduz** [comment]
I can no longer reproduce any of these issues in master, so closing
![image](https://user-images.githubusercontent.com/6265307/29524419-24ec1ac2-8666-11e7-88c9-b398da505fc1.png)
![image](https://user-images.githubusercontent.com/6265307/29524427-2b1f6a7a-8666-11e7-8d64-f1fedf2ad101.png)
