### ISSUE TITLE
MODELVIEW_MATRIX in visual Shader not working properly

### ISSUE THREAD

**Issue by ClintochX** [godotengine/godot#95248]
### Tested versions

4.3 beta 2

### System information

Windows 10, Intel core i5 (2 cores @2.8Ghz), Intel HD Graphics 4000. 

### Issue description

the MODELVIEW_MATRIX shader is not working properly, tested in compatibility renderer and mobile Renderer. please fix it 

### Steps to reproduce

just use the MODELVIEW_MATRIX and see 

### Minimal reproduction project (MRP)

just try it, please

**Comment by AThousandShips** [comment]
Please explain what is wrong and add some details, to make sure this is a bug and not incorrect assumptions

Also please try on a recent development version like [rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/), beta2 is over a month old

**Comment by ClintochX** [comment]
> Please explain what is wrong and add some details, to make sure this is a bug and not incorrect assumptions
> 
> Also please try on a recent development version like [rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/), beta2 is over a month old 

my apologies, I didn't do it correctly, I now understand
