### ISSUE TITLE
Godot 3.6-rc1 `TouchScreenButton` node doesn't work using `_physics_procces()`

### ISSUE THREAD

**Issue by avirahmandev** [godotengine/godot#95240]
### Tested versions

v3.6.rc1.official [cfc4a0eff]

### System information

Linux openSUSE Tumbleweed

### Issue description

TouchScreenButton node doesn't work using `Input.is_action_just_pressed()` with `_physics_process()`. Still work with keyboard input but not with touch from pointer or android device.

Already tested in v3.5.3-stable still work
 

### Steps to reproduce

1. Download the MRP
2. Make sure `emulate touch from mouse` is enabled and `InputMap` has registered actions `left` & `right`

### Minimal reproduction project (MRP)

[InputHandleTest.zip](https://github.com/user-attachments/files/16521419/InputHandleTest.zip)

**Comment by rburing** [comment]
Thank you for your report. This issue is already fixed in the current `3.x` branch, thanks to this PR:

- https://github.com/godotengine/godot/pull/94421

which came just after 3.6.rc1, so the issue will be fixed in the next release candidate and/or the eventual 3.6 release.
