### ISSUE TITLE
SDFGI does not react to HDRI rotation

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#95243]
### Tested versions

4.2.2.stable and 4.3.rc2

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4633) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

SDFGI does not react to HDRI rotation

### Steps to reproduce

1. Create a 3D scene with a world environment with SDFGI enabled and set the environment to a panorama sky with an HDRI.
2. Rotate the HDRI in the sky settings, observe that the SDFGI light does not change.

https://github.com/user-attachments/assets/b6d3aaa6-754f-428d-a2c3-0062630f3bb3

### Minimal reproduction project (MRP)

Note: the sample project is 5mb as it contains an HDRI.
[rotate_hdri_sdfgi_issue.zip](https://github.com/user-attachments/files/16522354/rotate_hdri_sdfgi_issue.zip)

**Comment by Arnklit** [comment]
May be related to https://github.com/godotengine/godot/issues/56135

**Comment by viksl** [comment]
SDFGI does not take into account sky rotation, it's a bug: https://github.com/godotengine/godot/issues/62793

**Comment by Arnklit** [comment]
Ah thanks @viksl . don't know why I didn't find that when I searched. Closing as dupe.

**Comment by Arnklit** [comment]
Ah thanks @viksl . don't know why I didn't find that when I searched. Closing as dupe.
