### ISSUE TITLE
Adding Blend Shape Track to an AnimationPlayer wrongly prepends "blend_shapes/" into the track's path

### ISSUE THREAD

**Issue by goatchurchprime** [godotengine/godot#95244]
### Tested versions

This issue appears in 4.2.2.stable might have been fixed on 4.3.rc2 (though there is no reference to it).
I suspect people have acquired the habit of using Property Tracks as a work-around instead (having found Blend Shape tracks too unreliable), so it would be good to put this issue on record that it may have been fixed. 

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

In v4.2.2 if you load a GLTF file and create an AnimationPlayer to animate its blend shapes by adding a Blend Shape Track, the property name in the track path is of the form ":blend_shape/[shapekeyname]".  You can add keys but it doesn't animate.   There is an error:
> ERROR: AnimationMixer: 'AnimateBlend', blend shape track points to a non-existing name:  'blend_shapes/frame_0001'.

(In V4.3 the trackpath is of the form ":[shapekeyname]" and it does animate.)

In v4.2.2 you can edit the trackpath by double-clicking on it to remove the "blend_shape/" part and then it animates.  However the UI doesn't think it is valid and gives an error when you try to insert a key:

> ERROR: Condition "(p_key.get_type() != Variant::FLOAT) && (p_key.get_type() != Variant::INT)" is true. Returning: -1

I suspect the habit-forming work-around is to use the general-purpose Property Track, which doesn't have this bug.  If this bug has been noticeably fixed (as opposed to disappearing briefly), then people could be tempted back to using the more efficient blend shape animations.

### Steps to reproduce

Load the project, add an animation, set to looped.
* Add Track type Blend Shape.  
* Select Paint_001 then blend_shapes/frame_001
* Right click at two places to add two keys into the blend_shape track, edit the values to be 0 and 1, and prove it doesn't animate
* Double-click on the name of the track and change it from: "unit_conversion_scaling/Root/Paint_001:blend_shapes/frame_0001" to "unit_conversion_scaling/Root/Paint_001:frame_0001"
* Now the fish will animate when you play it
* Note that you cannot add in any new keys to the track now 

### Minimal reproduction project (MRP)

[blendshapeanimation.zip](https://github.com/user-attachments/files/16522337/blendshapeanimation.zip)

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/94737

Which is marked for cherry picking

**Comment by goatchurchprime** [comment]
So much for my capability to find what I want using the Github issue search.  

The following searches did not find that issue: "blend shape track", "blend shape", "blendshape" and "blend_shapes" 

Only searching for "blendshapetrack" gets it.

Could mark mine as duplicate so that more search terms point to it?
