### ISSUE TITLE
server keyword for calling rpc on server

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#9526]
I have some network code where the clients are the master and the server is but a slave. This is for my primary player controller class.

Now, often I'm finding I still want the server to be in control of a lot of things even though the each client is really the master.

I propose another keyword for gd script "server" which guarantees the rpc will only be called on the server regardless of who the master is.

**Comment by Chaosus** [comment]
What do you think about it @Faless ?

**Comment by Faless** [comment]
@Chaosus I would say either use sub-nodes with `network_master=1` (probably best) or use the `remote` keyword and guard it with `if get_tree().get_rpc_sender_id() != 1: return`

**Comment by Faless** [comment]
Closing, there is no much activity in this issue. If there's still interest it should probably go through the godot proposal repository.
In general, I don't like the idea of adding an architecture-dependent keyword to the high level multiplayer API, which as of now can be peer to peer if desidered,
