### ISSUE TITLE
Engine becomes unstable when renaming or moving files while using external editors.

### ISSUE THREAD

**Issue by FBalerio** [godotengine/godot#95266]
### Tested versions

Reproducible in 4.3.rc2

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.3713) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

While working with the latest RC I noticed renaming an item or moving a file causes the engine to behave strangely. The most notorious issue is external editors stop recognizing renamed classes (they used to do just fine before RC2). 

I haven't managed to encounter this issue when using the in-engine text editor so far and I'm currently using VSCode as an external editor using the godot-tools extension.

When renaming a file, VSCode highlights an error on usages of the renamed file's class, and it displays this error: 
`Parser bug: Could not find external parser. (Trying to resolve class inheritance of "{ClassName}")`

Attempting to reload the editor in this state causes the editor to close instead of reloading properly. 

This stops happening if you revert the name or location change.

### Steps to reproduce

1. Open a project in Godot
2. Set VSCode as an external editor using the [godot-tools ](https://marketplace.visualstudio.com/items?itemName=geequlim.godot-tools) extension.
3. From the Godot editor (not VSCode) rename or move a file that contains a class_name
4. Open in VSCode a file that references or inherits that file's class
5. Attempt to reload the project via Project > Reload Current Project

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16537027/mrp.zip)

**Comment by dalexeev** [comment]
I think this is a consequence of recent `GDScriptCache` fixes, but it's probably a minor issue at this point, given that a similar bug exists in 4.2.

CC @rune-scape @Hilderin

**Comment by dalexeev** [comment]
> When renaming a file, VSCode highlights an error on usages of the renamed file's class, and it displays this error:
> `Parser bug: Could not find external parser. (Trying to resolve class inheritance of "{ClassName}")`

I can confirm this in the current `master` (03afb92ef).

> Attempting to reload the editor in this state causes the editor to close instead of reloading properly.

Can't reproduce it, after restarting the editor it looks correct.

**Comment by Hilderin** [comment]
I'm not able to reproduce it with Godot 4.3 rc2

Maybe I did not follow correctly the steps??

https://github.com/user-attachments/assets/b8fa34d7-aad6-4a42-b4fb-f8cd2e198a73

**Comment by Hilderin** [comment]
Ok, I'm able to reproduce it but effectively, reloading the editor fixes the problem.

![image](https://github.com/user-attachments/assets/3c0c7854-0a8c-4eee-ac06-b4da81b87511)
