### ISSUE TITLE
Improper saving of the project after deleting the main scene

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#95260]
### Tested versions

- 4.3 rc 2

### System information

Windows 11

### Issue description

When you delete the main scene and then save the Project > Run configuration shows it has saved by clearing the value, but it is not.
Now if you reopen the project, the run configuration will have the value of the deleted scene. 

### Steps to reproduce

Create a Project and a Scene
Set the Scene as Main Scene and Save the Scene and Project
Now delete the Main Scene in the file system editor
Save project 
Do not save the Scene if it is opened, otherwise file will be recreated
Now check the configuration Project Settings >> Application >> Run >> Main Scene property will be empty. indicating it cleared the value.
Now restart the project., by closing and opening again
check the configuration Project Settings >> Application >> Run >> Main Scene property will have the value of the delete scene.
No errors shown in the output window

Now in some complicated cases where you delete multiple files, then it will cause some error that file not found in output window.

### Minimal reproduction project (MRP)

Not Required, but if needed will be provided

**Comment by KoBeWi** [comment]
Related code is here:
https://github.com/godotengine/godot/blob/4bef4d9808848c38c3f285edb300b4f3a843e543/editor/dependency_editor.cpp#L587-L589
It modifies the setting, but does not save ProjectSettings afterwards.

**Comment by Lunarisnia** [comment]
Is simply adding `ProjectSettings::get_singleton()->save();` at the end of `DependencyRemoveDialog::ok_pressed` okay? it seems to  solve the problem?
https://github.com/Lunarisnia/godot/blob/ca01eb8344a1724037946e4bde0cde3f5deba200/editor/dependency_editor.cpp#L658-L659

**Comment by tokengamedev** [comment]
let me add the second part of the problem which I could not reproduce earlier, but now I can. It is part of the same save problem.

When you delete a scene (which is open in the scene tabs) which may or may not be main scene and then immediately close the editor.
The editor will ask if you want to save the file or not before exiting. Since you have deleted and do not want that file. 

You select `Don't Save`. now the editor will close. 
If you reopen the editor. It will have the following issue when started
```
  Cannot open file 'res://node_2d.tscn'.
  Failed loading resource: res://node_2d.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:885 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:750 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:691 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
```
Expected to remove the file from the opened list of files, but it is not doing it, causing the error

Let me know if you want me to create a separate issue, I can quickly create it, but IMO it is part of the same problem, but it is up to you to decide.

The other points that I have noticed, which might not be related to issue. 
1. The open scenes list is stored in the `editor_layout.cfg` to my surprise. 
It may be right, but I was not expecting there.

2. The whole .godot folder needs to be streamlined. While just testing few scenes, it created a mess there. Settings are stored in .cfg files as well as files without extensions. It created lot of files that are not needed than the actual files.
I believe, it will improve performance of startup, if .godot folder is streamlined and structured.

**Comment by KoBeWi** [comment]
The scene issue's related code is located somewhere else and they aren't really related.

**Comment by tokengamedev** [comment]
Thanks @KoBeWi , I have created the issue https://github.com/godotengine/godot/issues/95326 for the error. Ignore the other comments as it should go under proposal.
