### ISSUE TITLE
Classes go missing from the built-in help after restarting the editor

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#95271]
### Tested versions

- Reproducible on the latest master as of writing, 4.3 rc 92212946532450494683929b82c450e95851a0bf
- Reproducible on 4.3 beta 1
- Reproducible on 4.2.1 stable
- Reproducible on 4.1.4 stable
- Reproducible on 4.0.4 stable
- Not applicable for 3.5.3 stable (it never shows up in the docs)

### System information

macOS 14.5

### Issue description

For custom classes defined with `class_name`, they appear in the built-in help / documentation occasionally, but they go missing from just restarting the editor. This happens even with a nearly empty project (just the one script and icon.svg). See the reproduction steps and minimal reproduction project below for details.

### Steps to reproduce

1. Open the minimal reproduction project.
2. Open the help page, search for "seat", and you will see this:
<img width="655" alt="Screenshot 2024-08-07 at 11 46 34 PM" src="https://github.com/user-attachments/assets/0d31f913-5d3e-460c-a4da-2dd1ee4ffb66">

3. Restart Godot.
4. Open the help page, search for "seat", and you will see this:
<img width="655" alt="Screenshot 2024-08-07 at 11 47 15 PM" src="https://github.com/user-attachments/assets/fd19d3b8-c713-4395-a30c-45896aca28e6">

### Minimal reproduction project (MRP)

[missing-doc-bug.zip](https://github.com/user-attachments/files/16538974/missing-doc-bug.zip)

**Comment by dalexeev** [comment]
See:

* #72406
* #86577
