### ISSUE TITLE
Error printed in output when creating new resource or selecting main scene on Linux X11 (EditorFileDialog on top of modal dialog)

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#95282]
### Tested versions

From 4.3dev3
Godot v4.3.rc2 

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - (software emulation on CPU) 

### Issue description

Clicking on create in "Create New Resource" window opened from FileSystem menu "New Resource" prints this error: platform/linuxbsd/x11/display_server_x11.cpp:1879 - Condition "!windows.has(p_window)" is true. Returning: ObjectID()

[Screencast_20240808_154206.webm](https://github.com/user-attachments/assets/5348cc7d-5f64-40e1-8cc3-10b20c429bea)

This doesnt happen when editor is set to use single window mode
Also if you select Shader in the resource window the error doesn't happen either, so it might be the linked to the "Save Resource As" window?

### Steps to reproduce

In FileSystem right click and select "New Resource..." 
Click on Create
Look at error in Output

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
As seen in #97486, this also happens when selecting a main scene, so I edited the title accordingly.
