### ISSUE TITLE
godot won't load image textures (Compressed texture file is corrupt (Bad header).)

### ISSUE THREAD

**Issue by jannelau** [godotengine/godot#95284]
### Tested versions

4.22, Godot v4.3.rc2

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3770) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Godot refuses to load any image files at all, with the error Compressed texture file is corrupt (Bad header). Attempted with multiple different versions of godot.

### Steps to reproduce

- Create a node that uses an image file (sprite3d)
- Attempt to add a compressed texture 2d file
- Get error message and no image (sad)
This worked fine just some time ago, now it seems to fail even on an empty project. No idea what the issue could be (I am on windows 11)

### Minimal reproduction project (MRP)

[import texture.zip](https://github.com/user-attachments/files/16549532/import.texture.zip)

**Comment by AThousandShips** [comment]
What 4.3 pre-release version specifically did you test on?

**Comment by jannelau** [comment]
(i was doing it wrong, tried using a compressedtexture instead of directly loading the image?)

**Comment by HugoDevy** [comment]
hello i am facing same issue do u have a seloution?

**Comment by HugoDevy** [comment]
the seloution for this is simply to open the icon.svg in folder manager 

![Image](https://github.com/user-attachments/assets/4a42027d-b92f-4975-880e-9f1e520d58ec)

then u gonna change its header to ".svg" 
this would resolve it
