### ISSUE TITLE
Area3D shape doesn't follow CollisionShape3D

### ISSUE THREAD

**Issue by eobet** [godotengine/godot#95280]
### Tested versions

4.3rc2

### System information

Godot v4.3.rc2 - Nobara Linux 40 (GNOME Edition) - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

This orange box should align with the blue box, I'm told.

(Also, the blue box is very, very faint... it's very difficult for me to see it.)

![Screenshot from 2024-08-08 13-02-24-1](https://github.com/user-attachments/assets/6b6e9fc3-829c-49d3-aa6a-73edef749328)

### Steps to reproduce

1. Create a new Scene with Area3D as root node
2. Add a CollisionShape3D which uses the built in box shape
3. Move the CollisionShape3D using the red dot handles only

(Oh, another comment here, I can't seem to find a button that hides the big transform gizmo, so sometimes I transform using that gizmo rather than the red dots... a UX papercut.)

### Minimal reproduction project (MRP)

[area3dtest.zip](https://github.com/user-attachments/files/16542046/area3dtest.zip)

**Comment by AThousandShips** [comment]
The orange box is the bounds of the node, this includes various things, in this case collision shapes doesn't have any bounds to use, so it just takes the origin of that node, I'm not sure how it is supposed to work, not sure if this is a bug or not as it normally covers visible nodes

**Comment by smix8** [comment]
That is the "remember to not scale your collision shapes, resize them" box.

... sly jokes aside this is the default Node3D spatial gizmo AABB box, tiny by default, and only really visible when you start to scale stuff.

**Comment by eobet** [comment]
Ok, thanks for the quick replies. Guess it's just a slightly unintuitive thing we just have to live with (it starts making sense once you add meshes to scene, so not sure of the value of seeing it until you do that). I'm not the only one puzzled by it, because I asked in the official Godot Discord and seems this is new for 4.3?

**Comment by AThousandShips** [comment]
Well if it's new in 4.3 that's more implying it is a bug (would be good information to add to the report), if you can confirm this then that's something to investigate

**Comment by Giganzo** [comment]
It seems its changed around 4.3dev3
Maybe https://github.com/godotengine/godot/pull/87132

**Comment by smix8** [comment]
What changed is that previously when a node was inherited from VisualInstance (which many nodes do), it would just straight use the visual instance aabb. This aabb ended up being zero size most of the time. Without a size it had no real visible geometry to render.

The change in the linked PR fixed parts of a wrong aabb calculation and made all zero sized aabbs fall back to the default size. There was always a default AABB, by default the size is 0.4 units when the Node3D had no parent.
