### ISSUE TITLE
Kerning Pairs property for Bitmap Image Font Data uses Unicode internal values as characters

### ISSUE THREAD

**Issue by DarkMarmot** [godotengine/godot#95293]
### Tested versions

Reproducible in - Godot v4.3.rc3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### System information

Godot v4.3.rc3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 (NVIDIA; 31.0.15.5176) - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

When setting up kerning pairs in the bitmap image font editor, Unicode values (added to support things like spaces, e.g. \u0020) will have their internal characters erroneously encoded as pairs.

The tokenizer needs something like `i+=5` in the loops to skip forward past the Unicode characters once decoded.

### Steps to reproduce

See Kerning pairs import property in attached file.
\0020 will have u, 0, and 2 get erroneously encoded as pairs.

### Minimal reproduction project (MRP)

[kerning_unicode_issue.zip](https://github.com/user-attachments/files/16552030/kerning_unicode_issue.zip)

**Comment by bruvzg** [comment]
It's `\u0200` not `/u0200` and it's `Ȁ` not space.

**Comment by DarkMarmot** [comment]
> It's `\u0200` not `/u0200` and it's `Ȁ` not space.

Sorry, that was a typo -- it's true for any Unicode character.
