### ISSUE TITLE
Godot booth/talk/workshop on Kieler Open Source und Linux Tage?

### ISSUE THREAD

**Issue by m23project** [godotengine/godot#9529]
Hi,

I didn't find any contact information for the Godot project, so I try it here :-)

We are organising our 15th "Kieler Open Source und Linux Tage" (northern of Germany, www.kielux.de), a conference with 4 parallel tracks with talks and workshops and a smal exhibition for open source community projects and companies.

Is there anybody who would like to hold a talk and/or give a Godot workshop and/or make a booth on our event (14th - 16th September)?

Please answer by eMail to kontakt @ kilux.de .

PS Your register dialog for the forum seem to be broken. Says "Please re-read Terms of Service" but "I agree to the terms of service" was ticked and the TOS page was opened before. Tested with Firefox and Chromium.

Cu Hauke

**Comment by akien-mga** [comment]
Moin Hauke,

Thanks for the invitation! We have various contributors in Germany, so we'll check if we have volunteers to hold a booth or propose a talk/workshop at Kielux this year.

I'll answer by email once we have decided on something.

Regarding our contact details, you might have missed the contact page on the website? https://godotengine.org/contact
Don't hesitate to provide feedback about it if it's not clear enough/too hard to find from the homepage.

Regarding the forum, it's maintained by community members and not directly by Godot developers; I'll forward them your feedback though.

**Comment by m23project** [comment]
Moin together,

Am 07.07.2017 um 10:41 schrieb Rémi Verschelde:
> Thanks for the invitation! We have various contributors in Germany, so we'll
> check if we have volunteers to hold a booth or propose a talk/workshop at Kielux
> this year.
great :-)

> Regarding our contact details, you might have missed the contact page on the
> website? https://godotengine.org/contact
> Don't hesitate to provide feedback about it if it's not clear enough/too hard to
> find from the homepage.
I didn't see that "Contact us" is a link, I took it for a title. Just saw
Twitter and Co. . Maybe you could put a ">" in front to make it look like the
other links (News, Features, ...).

Cu  Hauke

**Comment by akien-mga** [comment]
Closing, this is being further discussed by email.

To any curious user, yes, Godot will have a booth at the Kieler Open Source und Linux Tage :)
