### ISSUE TITLE
Clicking on Unique Name % symbol in Scene Tree should not turn it off.

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#95315]
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

I accidentally clicked on the % symbol of a node that was set as unique name and it was turned off. Unexpected behavior, since I click on nodes many times to select or rename them. I barely noticed it.

I don't see any use for this, since one cannot click on that same spot and enable unique names. At best it should just give a message.

![image](https://github.com/user-attachments/assets/01ef8c24-d9fd-4ca8-8913-3d1d754f40bc)

### Steps to reproduce

See above

### Minimal reproduction project (MRP)

see above

**Comment by huwpascoe** [comment]
Yeah, there should probably be a confirmation dialog.

**Comment by Giganzo** [comment]
Looks like the other buttons that behave the same (removes the setting, and button) is after the eye icon, like Lock/Group selected nodes. So one idea could be to move % "Unique Name" to come after the eye too. That could possible make the chance for accidentally clicks less. 

I can make a PR with this change if this would be desired. 
 
![Screenshot_20240809_123247](https://github.com/user-attachments/assets/d216cd25-d26c-4ab9-889f-f87e967bb326)

**Comment by dalexeev** [comment]
> So one idea could be to move % "Unique Name" to come after the eye too.

In my opinion this is worse, since the eye icons become unaligned. I would prefer a confirmation dialog with a Don't Show Next Time checkbox.

**Comment by Giganzo** [comment]
> 
> In my opinion this is worse, since the eye icons become unaligned. I would prefer a confirmation dialog with a Don't Show Next Time checkbox.

The eye icon already gets unaligned by the Lock and Group icons. Should they be moved to the other side too then and also have the same dialog?

**Comment by Giganzo** [comment]
The behavior of the Lock and Group Icons coming after the eye icon have changed after 4.3.dev4, https://github.com/godotengine/godot/pull/86268

**Comment by dalexeev** [comment]
> The eye icon already gets unaligned by the Lock and Group icons. Should they be moved to the other side too then

In my opinion, yes. I would prefer to have the eye icon always on the right. But this probably requires a proposal. I have seen a discussion about the icon order somewhere, I will try to find it.

It is just especially noticeable in your screenshot, when the position of the eye icon varies from 0 to 3. Now in real cases the icon is either 0 or 1, since Lock and Group are rarely used together.

> and also have the same dialog?

Lock and Group are only needed for the editor UX, usually nothing bad happens if you accidentally disable them. In contrast, Scene Unique Names are important for script logic.
