### ISSUE TITLE
Default _draw usage

### ISSUE THREAD

**Issue by xdeadmonkx** [godotengine/godot#9531]
**Operating system or device - Godot version:**
Windows 8.1 , Godot 3.0 alpha

It would be great if i could draw Control node same as if _draw not overriden. I need it to draw some graphics over texture sprite but following code don't work

extends Control

func _draw():
    ._draw() // calling of nonexistanf function ( Gamemaker analog of draw_self() )
    // draw my lines

**Comment by reduz** [comment]
No need to call base function, node is drawn anyway

**Comment by xdeadmonkx** [comment]
Thanks, closed!
