### ISSUE TITLE
Lock and Group icons comes after Visibility icon

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#95328]
### Tested versions

from 4.3.dev4

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) 

### Issue description

In 4.2.2:
![image](https://github.com/user-attachments/assets/2d9466b2-f754-416c-93fa-3c43275fe763)

In 4.3rc3:
![image](https://github.com/user-attachments/assets/63934a0e-769a-47d8-ab2a-d859f413f9c8)

This causes the eye icon to not be aligned. 

Probably after https://github.com/godotengine/godot/pull/86268

### Steps to reproduce

Change lock or group setting of a node in the scene tree

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
* See #95315 for a context.

> Probably after #86268

I haven't found a discussion why the change was made, so I think it's an accidental regression.
