### ISSUE TITLE
LightMapGI does not correctly apply GI information to inherited GridMap scenes when reopening scenes

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#95327]
### Tested versions

Reproducible on 4.2.2.stable and 4.3.rc3

### System information

Godot v4.3.rc3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4633) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

LightMapGI does not correctly apply GI information to inherited GridMap scenes when reopening scenes

Logs errors like:
```modules/gridmap/grid_map.cpp:1326 - Index p_idx = 0 is out of bounds (baked_meshes.size() = 0).```

![image](https://github.com/user-attachments/assets/8001b116-9e69-47e5-b49e-b41e53afeca2)

Related to https://github.com/godotengine/godot/issues/56030

### Steps to reproduce

1. Bake light in a scene where a gridmap is in a child scene. Note that the GI is applied correctly.
2. Close and open the scene again. note that the GI data is no longer applied to the child gridmap scene and errors are printed.

### Minimal reproduction project (MRP)

[test_lightmapgi_gridmap_2.zip](https://github.com/user-attachments/files/16560856/test_lightmapgi_gridmap_2.zip)

**Comment by hakro** [comment]
I think this is fixed in master (currently https://github.com/godotengine/godot/commit/0eadbdb5d0709e4e557e52377fa075d3e2f0ad1f)

https://github.com/user-attachments/assets/4b741cd8-d648-4098-b4b5-cab85869dc73

**Comment by Calinou** [comment]
Closing per the above comment. Please comment if you can still reproduce this on `master`.
