### ISSUE TITLE
Unacceptable GPU usage simple project

### ISSUE THREAD

**Issue by Anyeos** [godotengine/godot#95334]
### Tested versions

- Reproducible in Godot 4.2.2-stable

### System information

Ubuntu 20.04 - Godot 4.2.2 (stable) - Vulkan (Forward+) - EVGA Nvidia RTX 3070 TI

### Issue description

My GPU is at average of 30% usage when a single new project of Godot is running, regardless of the Editor itself. 
The problem started when I wanted to make a game and trying to optimize it I noted that I never can got less than 40% of GPU usage. And then I have the idea of testing a completely empty project with an empty scene to check if it is the engine and for surprise of me it was the engine itself who consumed a lot of GPU doing nothing.

I run Steam games and a complete game running in medium graphics does not use more than 28% of the same GPU.
I monitor GPU frequently because I want to know how is the usage. So I am aware of how games consumes GPU and what graphic option is more or less expensive. And in this case Godot is not competitive because it is using a lot of GPU showing nothing. 
Maybe the Godot shaders (SSAO, SSIL, Fog, etc) are always processing something regardless of user option because most of the options are setteable runtime. Maybe that run expensive shader code always.

![Captura de pantalla de 2024-08-09 12-02-56](https://github.com/user-attachments/assets/9d76d736-360a-41e3-b2f1-bbffd6130615)

### Steps to reproduce

Create a new project, dont need to change anything, dont need to write any code, only put a Node3D make that the main scene and that is all.
Now run the project and monitor the GPU usage. You can export the project and the same result regardless of DEBUG or RELEASE.

### Minimal reproduction project (MRP)

Empty default new project with a Node3D only.

**Comment by Calinou** [comment]
> Maybe the Godot shaders (SSAO, SSIL, Fog, etc) are always processing something regardless of user option because most of the options are setteable in realtime. Maybe that run expensive shader code always.

No, this is not the case. In fact, if you don't have a Camera3D node, then no 3D buffers are created.

**Comment by Anyeos** [comment]
Thank you for your answer, everyday I learn something new.

Ok, I thought the card "knew" how much its maximum capacity was and that the percentage was based on its maximum capacity and not the clock it was on at the time.

Now I put my GPU at "Prefer Maximum Performance" and:
![Captura de pantalla de 2024-08-09 12-22-17](https://github.com/user-attachments/assets/333b2fdb-3cbb-4fc9-af25-069b905cb108)
I hope this helps others understand how it works. If it is not an issue then can someone please put it on the correct place?? Thank you.
