### ISSUE TITLE
#include "platform_config.h" file not found in typedefs.h

### ISSUE THREAD

**Issue by owlnewworlds** [godotengine/godot#95355]
### Tested versions

- Godot 4.3 RC3

### System information

N/A

### Issue description

I'm trying to create an iOS plugin on my own for the iOS version of my game, so I'm trying to create the static library with XCode. But when building, I have an error saying at the line
#include "platform_config.h"
saying that file is not found (I can find it at platform/ios/platform_config.h) but I'm not sure if it's the right fix for that because it all depends on what someone is creating a library for...

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Creating a separate static library without the `SCons` toolset isn't really supported, you are missing a lot of configuration

This isn't the place to ask general support questions however, please use the other [community channels](https://godotengine.org/community/) instead

Closing and good luck finding a solution

**Comment by owlnewworlds** [comment]
That was a bit quick! Lol but okay, I'm using SCons so maybe I'm using it wrong, or maybe there is a real issue, who knows? I'm using it like the documentation says.

**Comment by AThousandShips** [comment]
My bad, assumed you building as a static library meant you used XCode directly, but please explain your steps for doing this

**Comment by owlnewworlds** [comment]
I created an XCode project "static library" and put Godot source code directory in the header path. I have the entry points for the plugin and when building it throws this error. But yes, I assume that I'm not doing it right. And I'm sorry if it's not an issue, I'm not using this as a support or what.

I'm following this video of a Godot dev who managed to make iOS plugins.
https://www.youtube.com/watch?v=Y6Iq71zZO10

Must admit he doesn't always know what he's doing but that's the closer I can get to something working. The official documentation isn't really precise of the steps. But I will request help on Discord and point to this thread to explain myself.

**Comment by AThousandShips** [comment]
Please upload some code examples instead, a video is hard to test

But I'd suggest asking in other channels and come back here if you find something that is broken, or clear up that it's a configuration error

**Comment by dalexeev** [comment]
I encountered a similar issue when setting up `clangd` for my text editor. The setting solved most problems for me:

```
CompileFlags:
  Add: [-I/home/danil/godot-src, -I/home/danil/godot-src/platform/linuxbsd, -DDEBUG_ENABLED, -DTOOLS_ENABLED]
```

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
