### ISSUE TITLE
Raycast didn't work in _ready function

### ISSUE THREAD

**Issue by wolfsmith520-github** [godotengine/godot#95354]
### Tested versions

Version : 4.2.2 stable Steam Version

### System information

System : Windows 11 Godot 4.x vulkan rtx4060laptop

### Issue description

The raycast detection does't not work in the _ready function using Gdscript ( C# not tested )

### Steps to reproduce

I setup a raycast like this, it is colliding with this cube
![image](https://github.com/user-attachments/assets/7431bc3f-8566-44a2-bb98-07d80654b100)
then I write a simple detect script in the _ready function
![image](https://github.com/user-attachments/assets/33eba9a7-b357-4d77-90d0-63b8f10d987a)
But when I run this, nothing happened
![image](https://github.com/user-attachments/assets/c374c8dc-5b1a-405b-821d-bc7bb38d801c)
I tested in other game engine like Unreal and Unity, they all work, is this a bug?

### Minimal reproduction project (MRP)

[raycast.zip](https://github.com/user-attachments/files/16569655/raycast.zip)

**Comment by AThousandShips** [comment]
`RayCast3D` needs at least one physics frame to compute the data, it is not ready in `_ready`, generally physics isn't ready as no physics has happened yet

Can you try if [`force_raycast_update`](https://docs.godotengine.org/en/latest/classes/class_raycast3d.html#class-raycast3d-method-force-raycast-update) helps?

This is something to document a bit more clearly, beyond the existing details

**Comment by wolfsmith520-github** [comment]
> `RayCast3D` needs at least one physics frame to compute the data, it is not ready in `_ready`, generally physics isn't ready as no physics has happened yet
> 
> Can you try if [`force_raycast_update`](https://docs.godotengine.org/en/latest/classes/class_raycast3d.html#class-raycast3d-method-force-raycast-update) helps?
> 
> This is something to document a bit more clearly, beyond the existing details:
> 
> > `RayCast3D` calculates intersection every physics frame

![image](https://github.com/user-attachments/assets/d0f66806-0ba7-4506-9e09-2c707348f1e8)
Thank you very much, I should read more document
