### ISSUE TITLE
Auto translate inherit mode does not work beyond first parent when attempting to use disabled mode

### ISSUE THREAD

**Issue by LunaCapra** [godotengine/godot#95357]
### Tested versions

- 4.3.rc2 (.NET)
- 4.3.rc3
- 4.3.rc3 (.NET)
- master ([`88f3b5f`](https://github.com/godotengine/godot/commit/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279))

### System information

Nobara Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+)

### Issue description

When using a setup along the lines of
- Control
  - Control2
     - Control3
       - Label

and setting `Control2`'s auto translation mode to disabled, while keeping every other node's mode as inherit, the label's text still gets added to the auto generated POT file when generating it from the project settings with the scene added.

### Steps to reproduce

1. Download the MRP.
2. Check `control.tscn` for reference. (The first node under the root node has auto translate set to disabled.)
3. Go to `Project Settings > Localization > POT Generation` and press the "Generate POT" button in the top right.
4. Find a message id of "Should not be in POT" in the generated .pot file.

### Minimal reproduction project (MRP)

[Minimal reproduction project](https://github.com/user-attachments/files/16569744/mrp.zip)

**Comment by akien-mga** [comment]
CC @YeldhamDev
