### ISSUE TITLE
JSON Parser Breaks with Large Integers

### ISSUE THREAD

**Issue by dev-mico** [godotengine/godot#95360]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.3210) - 13th Gen Intel(R) Core(TM) i7-13700HX (24 Threads)

### Issue description

JSON parsing seems to break with large integers. Probably something to do with the precision of the ints used under the hood. However, I would expect this to work, as in other languages (e.g., Python which is a common reference), arbitrarily large numbers are supported by native parsers.

### Steps to reproduce

Here's an entire script you can copy-paste to see the issue:

```
extends Node

func _ready():
	
	var broken1 = {
		"steamid": 36561198138808038
	}

	var broken2 = {
		"steamid": 765611981388080789
	}

	## JSON string representing player data.
	var broken1String = JSON.stringify(broken1) # "{\"steamid\": 76561198138808038}"
	var broken2String = JSON.stringify(broken2) # "{\"steamid\": 76561198138808038}"

	print("Original data (broken1 dict):", broken1)
	print("Original data (broken2 dict):", broken2)
	print("Original data (broken1 string json):", broken1String)
	print("Original data (broken2 string json):", broken2String)
	
	# Parse the JSON string
	var json = JSON.new()
	var err = json.parse(broken1String)
	
	assert(err == OK)
	
	var broken1Parsed = json.get_data()

	# Repeat for broken2
	err = json.parse(broken2String)
	assert(err == OK)
	var broken2Parsed = json.get_data()

	# Print the parsed data to verify
	print("Parsed dict (broken1):", broken1Parsed)
	print("Parsed dict (broken2):", broken2Parsed)
```

As you can say, the values in the input & output aren't the same (pay close attention to the final digits). The system output is as follows (on my machine):

```
Original data (broken1 dict):{ "steamid": 36561198138808038 }
Original data (broken2 dict):{ "steamid": 765611981388080789 }
Original data (broken1 string json):{"steamid":36561198138808038}
Original data (broken2 string json):{"steamid":765611981388080789}
Parsed dict (broken1):{ "steamid": 36561198138808040 }
Parsed dict (broken2):{ "steamid": 765611981388080770 }
```

### Minimal reproduction project (MRP)

see 'steps to reproduce.' just throw this in an autoload script & run!

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/24119

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
