### ISSUE TITLE
Why can't I modify the CollisionShape2D node attribute value radius, AnimationPlayer node time length, etc. when I create a new scene inheritance?

### ISSUE THREAD

**Issue by ice-ko** [godotengine/godot#95362]
### Tested versions

Godot_v4.3-rc2

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.5599) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

Are the properties of the newly created inherited scene nodes allowed to be modified in the child scene? If all node properties cannot be modified, does inheritance lose its meaning?

### Steps to reproduce

no

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16570255/test.zip)

**Comment by smix8** [comment]
Resources are shared by default and a CollisionShape2D node uses a Shape2D resource which is shared across all scene instances by default.

If you dont want that you need to duplicate the resource, set it to local_to_scene, to create a unique copy of it.

**Comment by smix8** [comment]
Closing as this was just a knowledge-gap and the resource system is already documented.
