### ISSUE TITLE
NSException: Joypad playerIndex

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#95365]
### Tested versions

Godot 4.3rc3.

### System information

Mac M1, macOS 14.5, Logitech Gamepad F310

### Issue description

I can get a ton of errors in 4.3rc3. Sometimes at startup it will freeze with gamepad plugged in. Other times it will start project fine then sometimes when I go to play the game it'll freeze up and display these errors run: NSException: -[Joypad playerIndex]: unrecognized selector sent to instance 0x6000037fc990

Did not see this is issue in rc2. 

![Screenshot 2024-08-10 at 12 28 37](https://github.com/user-attachments/assets/1bc2ca4b-40c9-4070-84b4-55c209560b07)

### Steps to reproduce

Not sure if just happens when the Logitech F310 is plugged in.

### Minimal reproduction project (MRP)

NA

**Comment by akien-mga** [comment]
CC @bruvzg

**Comment by bruvzg** [comment]
Can't reproduce it with XBox Wireless controller and DualSense controllers. Isn't F310 an 360 clone? macOS should not recognize it at all.

**Comment by Morokiane** [comment]
macOS has no problem recognizing the controller. There is an issue with the select button but overall it works as expected. For my game in Godot it performs exactly as it does on Windows.
