### ISSUE TITLE
VBoxContainer seems to have become a duplicate of HBoxContainer.

### ISSUE THREAD

**Issue by ComfyZenny** [godotengine/godot#95383]
### Tested versions

- Reproducible in 4.3 rc2 and rc3. Have not checked others, but I never had problems until rc2. (Linux client, had rc1 on Windows but hadn't touched VBox Containers during that time, only previously, worked as expected so I know what's wrong, not when.)

### System information

Manjaro KDE, Wayland. cpu 5800X, gpu 6900XT, compatability mode rendering, persists in other modes.

### Issue description

Indistinguishable behaviour, does NOT arrange vertically, but horizontally.
Once reproduced;
-Notice it appears to the side of the previous node, not below/above.
-Notice the expand property only appears for width, not height.

![image](https://github.com/user-attachments/assets/1b8ff5d4-99ee-41e2-ad6d-cb9527de0bd1)

### Steps to reproduce

-Creating a new scene with control
-Add BoxContainer child
-Add VboxContainer child
-Duplicate/add another as sibling of previous VboxContainer.
-Notice it appears to the side of the previous node, not below/above.
-Notice the expand property only appears for width, not height.

### Minimal reproduction project (MRP)

MRP
[Archive.zip](https://github.com/user-attachments/files/16573478/Archive.zip)

**Comment by lostminds** [comment]
I think you're misunderstanding HBoxContainer and VBoxContainer, they arrange their child nodes horizontally and vertically, not themselves in some other container.

**Comment by ComfyZenny** [comment]
> I think you're misunderstanding HBoxContainer and VBoxContainer, they arrange their child nodes horizontally and vertically, not themselves in some other container.

omgosh you're right. I had the biggest brain-fart and didn't realise I was doing this. I conditioned myself to think it worked this way because of a past project's scene tree.
Silly me, thank you!
