### ISSUE TITLE
[3.0] Editor crash when using a function with a string argument as a match pattern

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#9539]
**Operating system or device - Godot version:**
Windows 10 - [Godot-Windows-x86_64-2017-07-07.3f3deb0](https://bintray.com/version/files/calinou/godot/editor/2017-07-07.3f3deb0)

**Issue description:**
When using a function as a match pattern, the editor correctly tells you that you can't use functions in patterns, but as soon as you add a string as an argument within that function the editor crashes.

**Code example:**
```
func tester(arg = "bla"):
    match arg:
        begins_with("b"):
```
begins_with("b") is used as an example here but any function with a string argument crashes the editor too.

**Comment by xdeadmonkx** [comment]
is it proper way to do?
3rd line becomes - if arg == begins_with("b") which is not proper

**Comment by AWKgamedev** [comment]
No, the code isn't supposed to work, I'm simply reporting the crash.

**Comment by vnen** [comment]
Can't reproduce with 3.0.5. It probably was fixed along the way.
