### ISSUE TITLE
AnimationPlayer flickering when scrubbing backwards on Discrete tracks

### ISSUE THREAD

**Issue by estroBiologist** [godotengine/godot#95391]
### Tested versions

- Reproducible in: 4.3.rc3
- Not reproducible in: 4.2.x

### System information

Godot v4.3.rc3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

As of Godot 4.3, scrubbing backwards on AnimationTracks set to Discrete causes the animated values to rapidly flicker back and forth between the nearest two keyframes, as opposed to using the left keyframe's value.

This does not happen when playing the Animation either forwards or backwards, and seems to be an editor-only bug.

![flickering](https://github.com/user-attachments/assets/2bd66b67-9a1f-46f9-bbc3-781e778bc46c)

### Steps to reproduce

- Create a project
- Add an AnimationPlayer Node and create a new Animation
- Add another Node, add any of its properties to the Animation
- Set the track's Update Mode to Discrete if it isn't already
- Add some keyframes, then scrub back and forth to see the flickering

### Minimal reproduction project (MRP)

[AnimationFlickerMRP.zip](https://github.com/user-attachments/files/16574091/AnimationFlickerMRP.zip)

**Comment by estroBiologist** [comment]
Hey, so while the linked PR seems to have resolved the flickering, it's still using the wrong keyframe value when scrubbing backwards?

![wrong_keyframe](https://github.com/user-attachments/assets/a67e95d9-77b2-4912-aa73-b006829d05a9)

**Comment by akien-mga** [comment]
Seems to be wrongly interpolated as if it was Continuous instead of Discrete.

**Comment by TokageItLab** [comment]
No, that is the intended behavior. The behavior is different from past versions, but consistent with actual playback. When seeking backwards, the previous value is retrieved. If you do not want that, use InterpolateContinuous+Nearest.
