### ISSUE TITLE
Opening a native file dialog disconnects you from the server

### ISSUE THREAD

**Issue by mr-dreich** [godotengine/godot#95394]
### Tested versions

Godot v4.3.rc3 - macOS and Windows 10/11

### System information

Godot v4.3.rc3 - Windows 11

### Issue description

After connecting to a server, if you open a native file dialog to browse files you will be disconnected after a few seconds. I have tested this on MacOS and Windows, and it seems to only happen on Windows. It works just fine when not using native file dialogs.

Unless I am totally botching the implementation of creating and connecting to a server. The provided project is as simple as I could get it.

### Steps to reproduce

Host a server; using an export or multiple instances, connect to the server then open a native file dialog and wait.

### Minimal reproduction project (MRP)

[network_test.zip](https://github.com/user-attachments/files/16574203/network_test.zip)

**Comment by mr-dreich** [comment]
@AThousandShips thanks for checking this issue out, but I think tagging this as macOS is wrong as I stated I could only get it to happen while testing in Windows.

**Comment by AThousandShips** [comment]
My bad the formatting made it harder to tell you used different OSs in one line

**Comment by Calinou** [comment]
This likely happens because opening a native file dialog blocks project execution, which causes the client to timeout since it can't respond to the server's packets.
