### ISSUE TITLE
Timeline changed error in AnimationPlayer

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#95399]
### Tested versions

4.3rc2, 4.3rc3
Tested on Mac and Windows

### System information

Mac M1/M2, macOS 14.5 / AMD Ryzen 9, Windows 11

### Issue description

When keying animation on a sprite frame everytime the key button is pressed this error will show up.

 core/object/object.cpp:1200 - Error calling from signal 'timeline_changed' to callable: 'AnimationPlayerEditor::AnimationPlayerEditor::_animation_key_editor_seek': Method expected 3 arguments, but called with 2.

### Steps to reproduce

Create a sprite2d/3d and AnimationPlayer. Key frame or frame coordinates. The error will show up in Output.

It doesn't do it on anything else in the sprite properties only frame and frame coordinates.

### Minimal reproduction project (MRP)

NA

**Comment by AThousandShips** [comment]
Writing up a fix, simple error
