### ISSUE TITLE
Allow us to set a default/template/skeleton project

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#954]
Every time I make a new project I have to go through the settings and change everything in there, then in the input map, etc. It would be nice to let us create a project template, then save it somewhere in ~/.godot/skeleton/ or something, and have that used as the defaults whenever we start a new project.

Bonus: let us edit the default GDScript template as well.

**Comment by mamarilmanson** [comment]
@reduz ~ this is the thing I was talking about before but you rejected my words... :'(

**Comment by kubecz3k** [comment]
Closed because https://github.com/godotengine/godot/issues/1343 is similar and it seems that discussion there was more vivid (sorry!)

**Comment by ShawkMusic** [comment]
This issue should be opened again. #1343 isn't really what this issue is about and it got closed when the Asset Library was added, which doesn't really solve the problem.

**Comment by Calinou** [comment]
@ShawkMusic This repository is now used for bug reports only. Feature proposals should be submitted to the [Godot proposals](https://github.com/godotengine/godot-proposals) repository after searching for duplicates there.
