### ISSUE TITLE
Ignore option does not appear on warning for unused signals

### ISSUE THREAD

**Issue by Proggle** [godotengine/godot#95403]
### Tested versions

v4.3.rc2.official [3978628c6]

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5241) - 12th Gen Intel(R) Core(TM) i9-12900 (24 Threads)

### Issue description

The documentation says that you can ignore warnings by clicking on the ignore link to the left of the warning's description

> To ignore specific warnings in one file, insert an annotation of the form @warning_ignore("warning-id"), or click on the ignore link to the left of the warning's description. Godot will add an annotation above the corresponding line and the code won't trigger the corresponding warning anymore:

However, in a regression from Godot 3, the 'ignore' link does not trigger for the unused signal warning.  This is kind of annoying.  It should add the
@warning_ignore("unused_signal")
as documented.

### Steps to reproduce

Reproduce by putting a not-obviously-used signal into a file.
```gdscript
signal foo
```

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
I can't reproduce this in 4.3.rc 33fe10c06:

https://github.com/user-attachments/assets/d97f742f-e262-4303-b962-053aeed2c948

**Comment by Proggle** [comment]
Ah, I see.  It looks like Godot 4 added a feature to the debugger so that signal warnings now show up in the debugger 'errors' tab (while in G3 that wasn't possible).  These duplicate messages include the option of jumping to the warning, but don't have the option of ignoring it that's present in the original location.  

If these messages are being presented in multiple locations they probably ought to have the same functionality in every location they're sent (especially since it still has the option to jump to the line in question). Still, I guess that's closer to an improvement than a bugfix since it's a new feature behaving inconsistently with the old one rather than an old feature getting worse, so I'll close this and see about putting in a proposal.
