### ISSUE TITLE
TileMapLayer loads wrong tiles in Firefox

### ISSUE THREAD

**Issue by daph** [godotengine/godot#95412]
### Tested versions

v4.3.rc3.official [03afb92ef]

### System information

Godot v4.3.rc3 - Arch Linux #1 ZEN SMP PREEMPT Sun, 11 Aug 2024 21:17:34 +0000 - Wayland - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 555.58.02) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I have a little project I'm using to get used to godot and use the new TileMapLayer node for the background. When I export to web and load the project in Firefox (129.0 Linux), the game plays fine but the TileMapLayer seems to load tiles from the wrong part of the tile set. When I play in chrome it is fine. 

Firefox:
![image](https://github.com/user-attachments/assets/8dea2ea0-c039-406e-8b96-27ba7a3e6726)

Chrome:
![image](https://github.com/user-attachments/assets/77be52c7-916c-4bde-bb15-f6c26fcaba70)

### Steps to reproduce

I've included my project here in full as it is still pretty small (and using CC0 assets from Kenney). Open the project in Godot 4.3 and export to web, serve with serve.py from the godot repo, and then load the game in Firefox

### Minimal reproduction project (MRP)

[shootzombieman.zip](https://github.com/user-attachments/files/16576941/shootzombieman.zip)

**Comment by akien-mga** [comment]
I can't reproduce the issue on Fedora 40 with Firefox 128.0.3 (Fedora package), using AMD iGPU.

**Comment by groud** [comment]
This sounds very weird, could it be a cache issue? 
Have you tried clearing your browsers cache? Maybe try refreshing the web page with Ctrl + F5 ?

**Comment by daph** [comment]
Okay, sorry for the false alarm. I did some more testing and this appears to have been caused by my having [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker) installed and forgetting that it can cause weird stuff like this to happen. Once I disabled it the game started working again.
