### ISSUE TITLE
Round corners don't take effect on some EditorAudioBus.

### ISSUE THREAD

**Issue by hayahane** [godotengine/godot#95410]
### Tested versions

4.3 rc 3

### System information

Windows 11

### Issue description

![image](https://github.com/user-attachments/assets/2913ef3f-80bb-4a7f-a28d-78f9a50543c2)
Except for the master audio bus, all audio buses didn't have round corners in the top-left and top-right corners. and the popup didn't align well.

### Steps to reproduce

Open editor and open audio bus editor.

### Minimal reproduction project (MRP)

Doesn't need one mrp, this is an editor ui issue.

**Comment by AThousandShips** [comment]
The bottom of the name inputs is by design:
https://github.com/godotengine/godot/blob/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279/editor/themes/editor_theme_manager.cpp#L1172-L1174

The non-master bus is also using one with no rounding on top, that might not be intentional though

**Comment by hayahane** [comment]
Seems the editor uses a unique way of making this PanelContainer focusable. The none master audio buses is using a different StyleBox.
https://github.com/godotengine/godot/blob/88f3b5f9d52f740b24fabfb8bc01b8b7026ba279/editor/editor_audio_buses.cpp#L124-L131

> The non-master bus is also using one with no rounding on top, that might not be intentional though

It seems that's done by design. However the result is not that obvious and I mistook that as a bug. Is there a better option? IMHO, corner radius should be unified and if there is a special need we shall make it obvious.
