### ISSUE TITLE
LineEdit shortcut_keys_enabled=false does not disable up/down arrow shortcut

### ISSUE THREAD

**Issue by OffsetMOSFET** [godotengine/godot#95411]
### Tested versions

4.2.dev

### System information

Ubuntu 22.04.4 LTS 64-bit

### Issue description

Setting LineEdit's shortcut_keys_enabled to false does not disable the up/down arrow shortcut functionality. They are listed as shortcuts in the documentation. (Other shortcuts disable correctly)

I'm not sure if this is an issue with the documentation or the implementation.

As an aside, it would be nice to be able to disable it regardless for cases where it's inside a VBoxContainer or something similar.

### Steps to reproduce

disable shortcut_keys_enabled

### Minimal reproduction project (MRP)

[LineEdit.zip](https://github.com/user-attachments/files/16576747/LineEdit.zip)

**Comment by AThousandShips** [comment]
This is by design, see the code, limited to conventional shortcuts, not navigation:
https://github.com/godotengine/godot/blob/c2a4942850404d97d0e5d5b99e03361cebf2a54c/scene/gui/line_edit.cpp#L516-L554

This should be clarified in the documentation

**Comment by OffsetMOSFET** [comment]
I think the first secton of LineEdit's documentation should not list up/down arrow as "shortcuts", if they aren't affected by shortcut_keys_enabled.
