### ISSUE TITLE
Found a bug when deleting file in the filesystem

### ISSUE THREAD

**Issue by Wolve-3DTech** [godotengine/godot#95423]
### Tested versions

- Reproductible in Godot 4.3rc3

### System information

Godot v4.3.rc3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When i  delete a file, in the filesystem, sometimes the file does no disappear, until I save the project or I exit and re-enter the folder it were located, as shown in the video. You'll see that for Scene1, everything is okay, bu for Scene2, it is not.

https://github.com/user-attachments/assets/4d661ae0-5af6-4ba9-979b-742643ac204e

### Steps to reproduce

This issue has only happened in my project, so it'll be hard to reproduce in another project.

### Minimal reproduction project (MRP)

Not available

**Comment by akien-mga** [comment]
Thanks for the report!

For the record, I'm assigning the 4.4 milestone as the 4.3 release is imminent so we likely won't have time to fix this regression in time, but it can hopefully be fixed shortly after and backported to 4.3.1.

**Comment by ilpolemico** [comment]
Yes, same problem. Only with 4.3 (with 4.2 there is not the problem). If you have many files in the project,  the FileSystem Dock become very slowly. 
If you try to remove/move files, the problem arises.

**Comment by ilpolemico** [comment]
> Thanks for the report!
> 
> For the record, I'm assigning the 4.4 milestone as the 4.3 release is imminent so we likely won't have time to fix this regression in time, but it can hopefully be fixed shortly after and backported to 4.3.1.

Ok, so for now I have to stick with version 4.2. I hope a patch comes out soon for this issue :-)

**Comment by akien-mga** [comment]
CC @KoBeWi @Hilderin

**Comment by Wolve-3DTech** [comment]
Glad to see that i'm not alone ;). Yes the project i'm currently working on has a huge amount of files, and in the same time Godot filesystem has become slower, especially when moving or renaming files. As for file deletion, i've noticed, based on 4 trials, that the problem does not appear when project is empty.
I acknowledge that it is extremely frustrating when you're making prototypes of things in your game.

P.S: I've also noticed these 2 other issues (I know it shouldn't be the place to discuss it but ...) : 


https://github.com/user-attachments/assets/8307c8b9-83b5-4393-8f45-a535d800dd86

**Comment by Hilderin** [comment]
I will look into it in the next couple of days, I'm currently busy on something else.

**Comment by Hilderin** [comment]
Finally, I got a little bit of time to check this issue.

@Wolve-3DTech @ilpolemico can you try this build and see if the problem of file deletion is fixed in your project:
For Windows: https://github.com/godotengine/godot/actions/runs/10395973773/artifacts/1813779682
For other OS: https://github.com/godotengine/godot/actions/runs/10395973773?pr=95533

@Wolve-3DTech You should create another issue for the problem in your video. That way, it could be fixed separately. Thanks.

**Comment by CsloudX** [comment]
> Glad to see that i'm not alone ;). Yes the project i'm currently working on has a huge amount of files, and in the same time Godot filesystem has become slower, especially when moving or renaming files. As for file deletion, i've noticed, based on 4 trials, that the problem does not appear when project is empty. I acknowledge that it is extremely frustrating when you're making prototypes of things in your game.
> 
> P.S: I've also noticed these 2 other issues (I know it shouldn't be the place to discuss it but ...) :
> 
>  Animation_Player_Bug_Showcase.mp4

Yes, samething for me. everytime for move/rename/delete file, 4.3 will rescan all files. it so slow. i'm not sure report it a bug or a 
 proposal.

**Comment by Hilderin** [comment]
I agree, I never quite understood why renaming/removing/moving files needs a full project rescan. I'm not sure it's really a proposal, so I would suggest to create a bug. Tag me in it so I could take a look.

**Comment by KoBeWi** [comment]
It's already reported https://github.com/godotengine/godot/issues/50576

**Comment by Wolve-3DTech** [comment]
> Finally, I got a little bit of time to check this issue.
> 
> @Wolve-3DTech @ilpolemico can you try this build and see if the problem of file deletion is fixed in your project: For Windows: https://github.com/godotengine/godot/actions/runs/10395973773/artifacts/1813779682 For other OS: https://github.com/godotengine/godot/actions/runs/10395973773?pr=95533
> 
> @Wolve-3DTech You should create another issue for the problem in your video. That way, it could be fixed separately. Thanks.

For now, the issue seems to be fixed on my first trials. I'll communicate you my results after an intense test.
Thank you for giving your time :D

**Comment by ilpolemico** [comment]
Thanks a lot! Works fine now!

**Comment by Wolve-3DTech** [comment]
Great !!
