### ISSUE TITLE
Editing external resources should not mark current edited scene as unsaved

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#9543]
**Operating system or device - Godot version:**
Antergos x86_64 - Godot master branch

**Issue description:**

Expected: edited external *resource* to be marked as unsaved, not the *current scene*
Happened: the current scene is marked as unsaved, even one with no root node (empty) ~~which crashes the engine upon closing~~

**Steps to reproduce:**
1. New project
2. Open icon.png, change its name property. OR Audio > Set bus volume
3. The current scene tab is now `[empty](*)`, ~~closing it will crash the engine. (Fixed)~~

**Comment by KoBeWi** [comment]
Related to #6797

**Comment by akien-mga** [comment]
This is still valid in the current `master` branch, but it's not really a bug and more a design quirk of Godot being first and foremost a scene editor. Changes to external resources or project settings are reflected on the currently edited scene, as it's the action of saving it which will also save the other changed items.

Given that this issue didn't get much traction and OP is a ghost, I'll close this one, but a follow-up could be opened on godot-proposals (if there isn't one already) to discuss how the unsaved state of non-scene resources could be better conveyed.
