### ISSUE TITLE
Still if you copy and paste a TileMap it deletes hours of work just cause

### ISSUE THREAD

**Issue by Casbian** [godotengine/godot#95441]
### Tested versions

etwgds does not matter this is known scince 2/3 years

### System information

wegtsd

### Issue description

etwgds

### Steps to reproduce

wtegs3d

### Minimal reproduction project (MRP)

twe3s

**Comment by akien-mga** [comment]
Please respect the work of contributors by providing details in your bug reports. This isn't actionable in any and just a rant, which is a breach of our [Code of Conduct](https://godotengine.org/code-of-conduct/). Consider this a first warning.

**Comment by Casbian** [comment]
could u answer me a question ? is there a pure code version of godot
without the annoying gui that deletes my work at random when it just feels
like it (cause it constantly tries to change states of animations or
anything just cause u pressed save) ?


Am Mo., 12. Aug. 2024 um 22:34 Uhr schrieb Rémi Verschelde <
***@***.***>:

**Comment by Calinou** [comment]
> is there a pure code version of godot

Godot is meant to be used with its editor. While you could technically write a minimal scene file by hand and do everything through scripts, it's not what the engine's APIs were designed for. If you go through this route, expect usability to be rough. You would also need to figure out a way to import tilesets and tilemaps from external programs without opening the Godot editor, which can be a challenge on its own.

If you don't want to use an editor, you may prefer pure code-based game development frameworks such as MonoGame, LÖVE or Phaser.
