### ISSUE TITLE
Need a way to set a custom AABB per visual instance

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9544]
In latest Godot 3.0 I didn't find any function to set a custom AABB on MeshInstances and various other objects, except particles. It's useful to have this so that visuals transformed using shaders won't get culled wrongly.

I currently need it in my HeightMap module because all chunks of the map re-use the same mesh for memory efficiency, and the Y component of the vertices is offset in the vertex shader from a height map texture. But because the AABB of the mesh is still a flat zero Y, holes suddenly appear in the map because they get culled.

**Comment by kubecz3k** [comment]
What about `VisiblityEnabler` and `VisiblityNotifier`?

**Comment by Zylann** [comment]
I believe they are based on those AABBs too, the root of the issue lies in the culling system itself, in VisualServer. I'm also not even using nodes in my module.

**Comment by kubecz3k** [comment]
Ok in 2.x there indeed was `Mesh.set_custom_aabb( AABB aabb)` method. In 3.0 I cant find anything like that in gdscript. 
On the c++ site there is `surface_set_custom_aabb(int p_surface, const Rect3 &p_aabb); //only recognized by driver` (https://github.com/godotengine/godot/blob/master/scene/resources/mesh.h#L190)
But surface api is not exposed. Not sure if it should be or what is the workflow for that in 3.0. 
@reduz would be great if you would give us a hint, maybe someone will be able to contribute.

**Comment by Zylann** [comment]
Actually, as I explained in the issue, I need a custom AABB on the instances, not the mesh itself.

**Comment by kubecz3k** [comment]
@Zylann but  MeshInstances are nodes that are providing interface for the mesh resource which they are holding..?

**Comment by Zylann** [comment]
Read my issue again :)
I need custom AABBs per instance because they all re-use the same mesh, which is displaced in a shader in different ways depending on world position. So I just can't use an AABB that comes from the mesh.

**Comment by kubecz3k** [comment]
@Zylann Oh, yeah, right! :+1:

**Comment by Zylann** [comment]
What is the status on this?
