### ISSUE TITLE
Data partially lost when iterating through a deserialized Dictionary

### ISSUE THREAD

**Issue by gturri** [godotengine/godot#95445]
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 11

### Issue description

I create a `Godot.Collection.Dictionary<Vector2I, Vector2I>`, fill it with some values, and serialize it (with `Json.Stringify`). So far so good.
I then deserialize it with `json.Parse` and cast it back to a `Godot.Collection.Dictionary<Vector2I, Vector2I>`.
At this point calling `.ToString()` on this deserialized value shows the expected content. But looping (with a `foreach`) on this variable get me key and values that are all `Vector2I.Zero`

### Steps to reproduce

Run the following code (which is pretty much the code from the [Saving games](https://docs.godotengine.org/en/4.2/tutorials/io/saving_games.html) documentation page):

```
        // Serialize data
        var d = new Godot.Collections.Dictionary<Vector2I, Vector2I>
        {
            { new Vector2I(1, 2), new Vector2I(3, 4) },
        };

        foreach (var (k, v) in d) // This loop displays '(1, 2) -> (3, 4)' as expected
        {
            GD.Print($"{k} -> {v}");
        }


        var s = Json.Stringify(d);
        GD.Print($"serialized dict: {s}"); // This line displays 'serialized dict: {"(1, 2)":"(3, 4)"}' as expected


        // Deserialize data
        var json = new Json();
        var parsedResult = json.Parse(s);
        if (parsedResult != Error.Ok)
        {
            GD.Print($"failed to parse"); // just to know if we have an
            return;
        }

        // Parse deserialized data
        var d2 = new Godot.Collections.Dictionary<Vector2I, Vector2I>((Godot.Collections.Dictionary)json.Data);
        GD.Print($"deserialized dict: {d2}"); // this line displays 'deserialized dict: { "(1, 2)": "(3, 4)" }', which is  expected
       
        foreach (var (k, v) in d2)
        {
            GD.Print($"{k} -> {v}");
        }
       // /!\  This loop displays '(0, 0) -> (0, 0)' which is clearly wrong! /!\
```

The expected behavior is that the last line of this code prints `(1, 2) -> (3, 4)`, but the actual behavior is that it displays `(0, 0) -> (0, 0)`.

### Minimal reproduction project (MRP)

[clone.zip](https://github.com/user-attachments/files/16591903/clone.zip)

**Comment by gturri** [comment]
Thanks for that explanation.
Indeed, the "Saving games" documentation page turns the position to `int` instead of keeping it as a `Vector2I`, I'm afraid I overlooked it.
Thanks also for the recommendation to avoid using this in C#.

What is not clear to me now is whether I should close this bug report (considering that I was misusing this API), or if it should still be considered a bug considering that the [godot documentation for json](https://docs.godotengine.org/en/4.2/classes/class_json.html) says:

> The JSON enables all data types to be converted to and from a JSON string

and does not mention any such limitation.
(or perhaps it's the doc that should be "fixed", by not saying "all data types" but mentioning this limitation?)

**Comment by raulsntos** [comment]
As explained by @atlasapplications, Godot's JSON serializer only supports [JSON data types](https://www.json.org) (string, number, object, array, bool, and null). There's already a proposal to add support for all Godot engine types:
- https://github.com/godotengine/godot-proposals/issues/9510

I can see how the [JSON](https://docs.godotengine.org/en/4.2/classes/class_json.html) documentation could be misleading, although later in the documentation it seems to vaguely mention some of these limitations. Pull requests to improve the documentation are welcomed :slightly_smiling_face:

**Comment by gturri** [comment]
Thanks for this feedback.
Given that other opened issue, and given that anyway bug report for the doc are supposed to be on https://github.com/godotengine/godot-docs instead, I'll close that issue (and I keep in mind that it would make sense that I take the time to propose a PR to improve the doc ^^)
