### ISSUE TITLE
Assigned shader ignored on mesh

### ISSUE THREAD

**Issue by eobet** [godotengine/godot#95442]
### Tested versions

4.3 rc3

### System information

Godot v4.3.rc3 - Nobara Linux 40 (GNOME Edition) - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3050 Ti Laptop GPU - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 Threads)

### Issue description

As you can see in this screenshot, the material on the mesh should be bright pink, but it's dark green:

![image](https://github.com/user-attachments/assets/3fb246b7-adee-42c6-8f43-57290ad582af)

### Steps to reproduce

1. Use the shader option in the inspector and either clear it or choose something different.

Result: Nothing happens.

Expected: The mesh should update?

### Minimal reproduction project (MRP)

[shadertest.zip](https://github.com/user-attachments/files/16591441/shadertest.zip)

**Comment by clayjohn** [comment]
You have an [override material ](https://docs.godotengine.org/en/latest/classes/class_geometryinstance3d.html#class-geometryinstance3d-property-material-override)set on that mesh instance

![image](https://github.com/user-attachments/assets/6ba6b1ac-6e25-4a67-9f55-c3a3c061ae19)

Override materials override all other materials set on that node. Removing the override material is enough for the surface material to become visible

**Comment by eobet** [comment]
@clayjohn I'm sorry but doesn't my screenshot show precisely that override material? And isn't that override material pink? Could you please explain in more detail what I'm missing here, because the UI seems a bit ambiguous to me...

**Comment by eobet** [comment]
Sorry, I did not realize there are _two _different__ material overrides...

...why are there two different material overrides? 😅

**Comment by clayjohn** [comment]
One overrides each surface individually. One overrides all surfaces and all meshes of the MeshInstance3D. They have different use-cases basically.
