### ISSUE TITLE
iOS version of the game crashes on iPad, due to no support for image cube array (Apple A10 GPU)

### ISSUE THREAD

**Issue by a-milosavljevic** [godotengine/godot#95448]
### Tested versions

- Reproducible in: 4.3 RC3

### System information

iPad (6th generation) - iPadOS 17.6.1

### Issue description

An iOS version of a 2D platformer game using Godot 4.3 RC3 crashes on iPad immediately after starting, while working without issues on iPhone 11 (iOS 17.6.1). It was installed using TestFlight on both devices and built using Xcode by exporting the project from Godot. I am attaching the TestFlight feedback file:
[testflight_feedback.zip](https://github.com/user-attachments/files/16592177/testflight_feedback.zip)

### Steps to reproduce

Just start the app on the iPad, and the splash screen briefly appears, and then the app crashes.

### Minimal reproduction project (MRP)

I assume that it is not up to the project, since it works fine on iPhones (tested on two devices). Only iPads (tested on two devices) seem problematic.

**Comment by a-milosavljevic** [comment]
@akien-mga I created a simple test project that only has one scene displaying the Godot default icon. Here you may find the project:
[godot-test.zip](https://github.com/user-attachments/files/16597825/godot-test.zip)

I wanted to upload the exported Xcode project, but it wasn't possible due to Github's attachment size limitation, so you may find it here:
[godot-test-ios.zip](https://spritecity.com/godot-test-ios.zip)

When I run this project from Xcode directly on my iPad, I get the following error on the screen and after that, the app crashes:
![IMG_0469](https://github.com/user-attachments/assets/85011c6a-0b79-47fb-8892-63acba3bffce)

Regarding testing hardware, I already mentioned, it is an iPad (6th generation) with iPadOS 17.6.1.
I also tried running the app on the iPad (7th generation) with iPadOS 16.3.1 with the same result.

I also tested it on two iPhones and it worked without any issues: iPhone 11 (iOS 17.6.1) and iPhone 13 mini (iOS 17.5.1).

I also want to mention that, based on the error, I suspected that iPad versions are using desktop renderer instead of mobile. I tried setting "mobile" as the renderer for the desktop configuration also, but it didn't make any difference.

**Comment by bruvzg** [comment]
A10 is likely too old for Vulkan, I do not have anything older than A14 to test, but cube map arrays are supported only on A11+ (Apple4 GPU family), see [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

**Comment by a-milosavljevic** [comment]
@bruvzg It's ok as far as I'm concerned. However, for some reason, the app crashed immediately after the message appeared, so I wasn't able to see it unless I ran the app from Xcode. It would be nice if that could be fixed.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/74227.
