### ISSUE TITLE
Editor camera position is overridden by Freelook after being set via Addon

### ISSUE THREAD

**Issue by rossunger** [godotengine/godot#95459]
### Tested versions

4.1, 4.2, 4.3 rc2

### System information

windows 10

### Issue description

I'm writing a plugin which needs to set the 3d editor camera position.

This works great until the user tries to free-look -> this resets the camera position to what it was before my plugin changed it.

I was digging around in the cpp code and I think has something to do with camera cursors, but I'm not familiar enough with the code to have a proper understanding

### Steps to reproduce

Create a new editor plugin

get the camera through:
`var camera = EditorInterface.get_editor_viewport_3d(0).get_camera_3d()`

set the position:
`camera.position = Vector3(0,0,0)`

then in the 3d view, enter free-look (right click + drag, or whatever your shortcut is) aka mouse-look.

At this point the camera has returned to whatever position it was in before the changes

### Minimal reproduction project (MRP)

[EditorCameraIssue.zip](https://github.com/user-attachments/files/16593532/EditorCameraIssue.zip)

**Comment by rossunger** [comment]
That makes sense. What are the next steps to making this happen? 

Should I post a proposal in godot-proposals and see if there's enough support? 

I feel like the most basic implementation of this would only take a few lines of code (for someone who knows that they're doing, which is not me... i could draft some pseudo code maybe)

Are there any consequences to controlling the editor camera that I should be aware of? was I correct in my assumption about camera_cursor being the missing piece of the puzzle?

**Comment by AThousandShips** [comment]
First step would be to get someone knowledgeable in the editor camera system to give their opinion, I'm just guessing here but I think this is a limitation that's just there, the editor is likely not going to be able to guess that you want to control the camera instead of it

**Comment by rossunger** [comment]
That sounds like a good idea. 

How do we invite someone knowledgeable in the editor camera system to give their opinion? Is there anything I can do to make this happen? 

Thank you for your help!

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/3287, as this depends on that proposal being implemented.
