### ISSUE TITLE
Callback function _make_custom_tooltip() does not get called when used in a plugin control as a Built-In

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#95457]
### Tested versions

v4.3.rc3.official [03afb92ef]

### System information

Linux Kubuntu 24.04 KDE Plasma Version: 5.27.11 KDE Frameworks Version: 5.115.0 Qt Version: 5.15.13 Kernel Version: 6.8.0-39-generic (64-bit) Graphics Platform: X11 Processors: 16 × 12th Gen Intel® Core™ i7-1260P Memory: 15.3 GiB of RAM

### Issue description

 _make_custom_tooltip() does not work for plugins. https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-private-method-make-custom-tooltip

I added the function to a control, but never gets called when it's a plugin. However works on a normal application.

### Steps to reproduce

See project attached and screen shots:

![image](https://github.com/user-attachments/assets/a94127c1-db80-4299-98a0-e82f376343c2)

![image](https://github.com/user-attachments/assets/7b26129b-599a-4e6e-aece-d79958b6aa2b)
```
extends Label

func _make_custom_tooltip(for_text):
	print("SHOULD PRINT for_text", for_text)
	var richLabel=Label.new()
	richLabel.text="SHOULD SHOW THIS: HERE IS RICH LABEL"
	return richLabel
```

### Minimal reproduction project (MRP)

[Archive.zip](https://github.com/user-attachments/files/16592986/Archive.zip)

**Comment by wyattbiker** [comment]
Amendment. Works when the script is external and has @tool at the top. Will not work for built-n scripts. I apologize for missing that.

So the script above should be as below but as a built-in

@tool
extends Label

func _make_custom_tooltip(for_text):
	print("SHOULD PRINT for_text", for_text)
	var richLabel=Label.new()
	richLabel.text="SHOULD SHOW THIS: HERE IS RICH LABEL"
	return richLabel

**Comment by KoBeWi** [comment]
It should work as built-in too. You might need to restart the editor, because `@tool` tends to fail when it's just added.

**Comment by wyattbiker** [comment]
Verified that after restarting editor the @tool works. Thanks. Closing
