### ISSUE TITLE
Bottom Panel (Output, etc.) keeps opening after every run. 

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#95467]
### Tested versions

v4.3.rc.custom_build [4359c28fe]

### System information

Godot v4.3.rc (4359c28fe) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

The bottom panel will constantly open when coming back from running a scene. When I close it, it should remain closed. I am having to hit Alt-O or click the 'output' button way too often now.

If there is printing/output going on, it makes sense for that panel to open, but can there be some way the user to say, "Nope! I will open you when I want to see that stuff."?

### Steps to reproduce

Just close the panel, run a scene and return.

### Minimal reproduction project (MRP)

None

**Comment by AeioMuch** [comment]
The settings to change the behaviours on Play and on Stop are in : 
Editor Settings -> Run -> Bottom Panel

**Comment by akien-mga** [comment]
Indeed, this is intended behavior out of the box but you can customize it with the settings pointed out by @AeioMuch.
