### ISSUE TITLE
get_remote_sender_id returns different identifiers

### ISSUE THREAD

**Issue by RyanRemer** [godotengine/godot#95462]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.5186) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

multiplayer.get_remote_sender_id() returns different identifiers for the same multiplayer peer. I have a code example down below.

### Steps to reproduce

I am trying to run a basic multiplayer example. I want to send a number to the server and have it print in the console.
```
func _process(delta):
	if Input.is_action_just_pressed("ui_accept"):
		count += 1;
		_get_packet.rpc_id(1, count);

@rpc("any_peer")
func _get_packet(data):
	print(str(multiplayer.get_unique_id()) + ": Recieved " + str(data) + " from " + str(multiplayer.get_remote_sender_id()))
```

When I have 1 server and 1 client, the "get_remote_sender_id" returns different values every time "ui_accept" is pressed.
```
1: Recieved 1 from 732659611
1: Recieved 2 from 1272802499
1: Recieved 3 from 590123181
1: Recieved 4 from 1866160547
1: Recieved 5 from 1857839317
```

The documentation says this function "Returns the unique peer ID of this MultiplayerAPI's multiplayer_peer." 

I would expect the remote sender ID to be the same for the same client. (Using the ENetMultiplayerPeer for both server and client). I think this is a bug. 

### Minimal reproduction project (MRP)

I think this file should be sufficient, you just need two buttons, one for host and one for join. I can provide the full project if needed. 

[multiplayer_ui.gd.txt](https://github.com/user-attachments/files/16594073/multiplayer_ui.gd.txt)

**Comment by AThousandShips** [comment]
CC @Faless

**Comment by AThousandShips** [comment]
Just a single script is likely not enough to test this, please upload a complete MRP

**Comment by RyanRemer** [comment]
Huh, I tried it out again today and everything works as expected. Feel free to close it.

Here is the project https://github.com/RyanRemer/multiplayer_722.

**Comment by AThousandShips** [comment]
Closing as per the above, if you have issues with this again please comment here and this can be reopened

**Comment by RyanRemer** [comment]
> Closing as per the above, if you have issues with this again please comment here and this can be reopened

Thanks for looking into it! I'm so confused what changed. I'll reopen if I run into it again.
