### ISSUE TITLE
AnimationPlayer timeline error

### ISSUE THREAD

**Issue by pmoosi** [godotengine/godot#95479]
### Tested versions

Reproducible in 4.3 after commit [29a0e51]

### System information

Godot v4.3.rc.mono (f7f202345) - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated AMD Unknown (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Trying to do anything with the animation players timeline since #95400 results in  

```
core/object/object.cpp:1200 - Error calling from signal 'timeline_changed' to callable: 'AnimationPlayerEditor::AnimationPlayerEditor::_animation_key_editor_seek': Method expected 3 arguments, but called with 4.
```

### Steps to reproduce

Create a AnimationPlayer node, an animation and click anywhere in the timeline.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @TokageItLab @AThousandShips

**Comment by AThousandShips** [comment]
I'll take a look, that's very weird

**Comment by AThousandShips** [comment]
Seems the signal was *declared* with two arguments, but is called *some times* with three, will write up a fix

**Comment by akien-mga** [comment]
The `timeline_changed` signal is emitted sometimes with 2 args and sometimes with 3 in `AnimationTrackEditor`.

So I guess we need to remove the `bind(false)` and manually add `false` to all the emits that only have 2 args.

**Comment by AThousandShips** [comment]
Will do and update the signature so it matches what it actually does

**Comment by akien-mga** [comment]
Thanks @pmoosi for the quick testing and regression report btw!

**Comment by pmoosi** [comment]
Thank you for the quick fix. You guys are doing amazing work :).
