### ISSUE TITLE
Tilemap shows only one custom data?

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#95478]
### Tested versions

v4.3.rc3.official [03afb92ef]

### System information

w10 64

### Issue description

I don't know if this is a bug but it seems strange to me that the information for only one of the custom data is shown and the data string "nombre_flag" does not show its value.

![Captura6](https://github.com/user-attachments/assets/78c6e898-8265-4920-b178-08ee5c0f980b)

### Steps to reproduce

See the image

### Minimal reproduction project (MRP)

...

**Comment by kleonc** [comment]
This is intended, the on-tile preview shows only the currently edited/focused property. If you'd select/focus `nombre_flag` then it should be shown over the tiles instead of the currently selected `vector_fuearzas`.
