### ISSUE TITLE
Strange lock behavior

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#9547]
**Operating system or device - Godot version:** Linux Mint XFCE 18.2 (64_86x), Godot Engine 3.0.alpha.custom_build (8b362b50)
**Issue description:** While editing the skeleton, I encountered a strange behavior of blocking nodes, an example in GIF (look at `leg_left` and `leg_right`):
![bug](https://user-images.githubusercontent.com/5412322/27982660-0a510a0a-63c1-11e7-9c9c-c6c883105c64.gif)

**Comment by toby3d** [comment]
The problem disappears after the editor is reloaded (completely close / kill the process and start again). But it manifests itself again after some time of the editor's continuous work. A bug can occur more than once in the same scene (2 random nodes, 4 nodes, 6 nodes, and so on).

**Comment by eon-s** [comment]
The lock is disabled on the editor too or just the icon?

**Comment by toby3d** [comment]
@eon-s I just encountered this bug again. Yes, this behavior locks the nodes.

**Comment by hpvb** [comment]
Can you attach a project that has this problem? Or if you don't want to make it public send it to me? (my email address is on my github page)

**Comment by bojidar-bg** [comment]
Can reproduce with ease:
1) Create a root node (any type), and a child node (CanvasItem, thus Node2D or Control)
2) Lock the child
3) Duplicate the locked child
4) Unlock or lock the duplicate -> both are locked/unlocked together

**Comment by hpvb** [comment]
Ah, I did not catch that the nodes needed to be duplicated for the effect to become visible. Thanks.
