### ISSUE TITLE
AudioStreamPlayer leak at exit 

### ISSUE THREAD

**Issue by ndbn** [godotengine/godot#95484]
### Tested versions

4.2, 4.3

### System information

Windows 10, x64

### Issue description

Posible releated #76745 #67589 #84398 , but a bit different error log

Only seen if whole godot run from console and with `--verbose` flag
Error log:
```
`WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:2209)
Leaked instance: AudioStreamPlaybackMP3:9223372060577760454
Leaked instance: AudioStreamMP3:9223372060309324999 - Resource path: res://Make a Choice.mp3
Hint: Leaked instances typically happen when nodes are removed from the scene tree (with `remove_child()`) but not freed (with 
`free()` or `queue_free()`).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:492)
Resource still in use: res://Make a Choice.mp3 (AudioStreamMP3)
Orphan StringName: _mix (static: 0, total: 1)
Orphan StringName: _stop (static: 0, total: 1)
Orphan StringName: _setup_local_to_scene (static: 0, total: 1)
Orphan StringName: _get_beat_count (static: 0, total: 1)
Orphan StringName: _mix_resampled (static: 0, total: 1)
Orphan StringName: _get_stream_sampling_rate (static: 0, total: 1)
Orphan StringName: _get_playback_position (static: 0, total: 1)
Orphan StringName: _get_stream_name (static: 0, total: 1)
Orphan StringName: _start (static: 0, total: 1)
Orphan StringName: _has_loop (static: 0, total: 1)
Orphan StringName: _is_playing (static: 0, total: 1)
Orphan StringName: _get_bar_beats (static: 0, total: 1)
``` 

### Steps to reproduce

Call `get_tree().quit()` when sound plaing
tested with differens stream types.

~~[IMO problem is here](https://github.com/godotengine/godot/blob/master/scene/audio/audio_stream_player.cpp#L290)
Internal player memory just freed and posible fix can be just add
`internal->stream = nullptr;`
so RefCounted can do job~~

### Minimal reproduction project (MRP)

[audiostream_leaked_mrp.zip](https://github.com/user-attachments/files/16599973/audiostream_leaked_mrp.zip)

**Comment by AThousandShips** [comment]
The clearing of the internal stream is handled automatically when destroying `AudioStream`, `Ref` handles reference counting, this is probably cased by something else, some instance being kept around in the server most likely

**Comment by ndbn** [comment]
Also seems AudioStream* resources stored even between scenes

**Comment by ndbn** [comment]
I log(stdout) Resource construction and Ref instances create, there is no difference between leaked `quit` and non-leaked quit, all refs unreferenced.

**Comment by Splizard** [comment]
Why was this closed as "not planned"? Seems like something that would be nice noise to resolve when debugging Orphan StringNames.

**Comment by barthy-koeln** [comment]
Verified to happen with `v4.5-stable` on MacOS.
