### ISSUE TITLE
Bones move without dependencies

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#9548]
**Operating system or device - Godot version:** Linux Mint XFCE 18.2 (64_86x), Godot Engine 3.0.alpha.custom_build (8b362b50)
**Issue description:**
![](https://user-images.githubusercontent.com/5412322/27982887-944f0d22-63c8-11e7-9a21-40f8e3896a5b.png)
![](https://user-images.githubusercontent.com/5412322/27982876-49e77a26-63c8-11e7-8621-cd44c86ef52c.gif)
**Steps to reproduce:**
1) [Make skeleton](http://docs.godotengine.org/en/stable/learning/features/animation/cutout_animation.html#completing-the-skeleton)
2) [Add bones](http://docs.godotengine.org/en/stable/learning/features/animation/cutout_animation.html#skeletons) and [IK-bones](http://docs.godotengine.org/en/stable/learning/features/animation/cutout_animation.html#ik-chains)
3) Try move the limb for the sprite or the bone itself

**Comment by toby3d** [comment]
And, yes, I do not understand how to remove the uneven edges of the sprite region, if this is not in the resource and should not be due to hard edges.
![image](https://user-images.githubusercontent.com/5412322/27982920-ea083e5e-63c9-11e7-8d9f-d4b3ae6be0cd.png)
![image](https://user-images.githubusercontent.com/5412322/27982926-12a73716-63ca-11e7-908b-81d6dc4d2c46.png)

**Comment by toby3d** [comment]
I thought that the bones in the editor should have worked like this:
![](http://docs.godotengine.org/en/stable/_images/tutovec_torso5.gif)

**Comment by gregersn** [comment]
I experience the same problem, as I was going through the cutout-tutorial. 
Is it the tutorial that is missing some information, or is there a problem in Godot?

**Comment by toby3d** [comment]
Commit 76005a8, still not moving as bones.

**Comment by Sslaxx** [comment]
That commit also affects #9982. These issues could be related.

**Comment by casd82** [comment]
This issue also occurs on 2.1.4

**Comment by casd82** [comment]
This issue also occurs in 2.1.4.

**Comment by Sslaxx** [comment]
Deleting and re-adding the comment won't get this looked at any faster.

**Comment by casd82** [comment]
Yo, I'm sorry, cause I thought I detected the issue in 2.1.4, but instead it was 2.1.3, so I deleted the comment.
However, then I installed 2.1.4 (Aug 17th), and found the exactly same issue, so I re-commented.
I'm not urging the devs to look at this faster at all, since its not a core feature or anything super important.

**Comment by toby3d** [comment]
The bug is still stored at the time to commit 3ea0943.
