### ISSUE TITLE
TileMaps with layers cannot be duplicated

### ISSUE THREAD

**Issue by suni-masuno** [godotengine/godot#95489]
### Tested versions

Reproduced in 4.3

### System information

Godot v4.3.dev3 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

Any TileMap containing multiple layers cannot be duplicated, or copy pasted.

When you attempt it the output window minimizes. If re-opened it contains the message below.
```
Class 'TileMapLayer' or its base class cannot be instantiated.
scene/main/node.cpp:2523 - Parameter "obj" is null.
editor/scene_tree_dock.cpp:755 - Condition "!dup" is true. Continuing.
```

### Steps to reproduce

1. Create a clean new project
2. declare the first scene a 2d
3. add 1 tilemap
4. add a second layer to the tilemap
5. attempt to duplicate that tilemap with ctrl-d or copy paste or ctrl-c/ctrl-v

### Minimal reproduction project (MRP)

[TilemapDupeTest.zip](https://github.com/user-attachments/files/16601524/TilemapDupeTest.zip)

**Comment by suni-masuno** [comment]
Apologies, you are correct. Importing the test into rc3 shows the issue resolved. 🙇 sorry about that.

**Comment by AThousandShips** [comment]
In the future make sure to include the commit hash in your report if you use a development branch it helps judging where you are (in this case `4.2` without `beta` or `rc` makes it just somewhere between last November and February)
