### ISSUE TITLE
The number of draw calls keeps showing a zero when using the overdraw debug draw mode in Forward+

### ISSUE THREAD

**Issue by gongpha** [godotengine/godot#95494]
### Tested versions

4.2.2-stable, 0e9caa2d9cb20737f8dcf08b75fcf2a78d980569

### System information

WIndows 11 - Vulkan Forward+

### Issue description

Forward+ rendering mode failed to count draw calls properly when using "Overdraw" mode (And `RENDER_TOTAL_OBJECTS_IN_FRAME`). It keeps showing a zero instead of one or more. but it does count some rendering calls like shadows

Occurs both in an editor and a runtime. but doesn't occur in Mobile and Compatibility mode

![image](https://github.com/user-attachments/assets/f9e58e38-c7c8-4abf-b87d-2f6ed989e4f4)
![image](https://github.com/user-attachments/assets/de1444af-205c-4dd2-a641-b400fee7aad8)

### Steps to reproduce

Switch to the Forward+ rendering mode (if using other modes)

1. Add some MeshInstances3D to the scene.
2. Changing to Overdraw mode (Top-left button in a viewport > "Display Overdraw")
3. Enable "View Information" (Top-left button in a viewport > "View Information")
4. Observe the number of draw calls in the right-bottom panel of a viewport.

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment]
For context for whoever wants to work on this, here is where we track draw calls in the Forward+ renderer https://github.com/godotengine/godot/blob/06fbc8395b3c0ec6fa38588caea2ee94837f7b97/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L770

**Comment by kevinkuo52** [comment]
small findings so far:

elements for RENDER_LIST_OPAQUE `rl->elements.size()` is 0, so element_total is 0,  thus VIEWPORT_RENDER_INFO_DRAW_CALLS_IN_FRAME doesnt get incremented.
![image](https://github.com/user-attachments/assets/56304724-0d75-4eea-8163-7e65aa8b02be)

https://github.com/godotengine/godot/blob/ee363af0ed65f6ca9a906f6065d0bd9c19dcf9e4/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L1033C1-L1042C7

> but doesn't occur in Mobile and Compatibility mode

fyi object count doesnt seem correct either for me on all display mode of Mobile and Compatibility Mode:
![image](https://github.com/user-attachments/assets/e5081d15-c330-4711-a962-7b22e4490145)

will update when I understand more

**Comment by gongpha** [comment]
> fyi object count doesnt seem correct either for me on all display mode of Mobile and Compatibility Mode

AFAIK, the gizmos and grid lines inside the editors are also counted in the draw call counter in Mobile and Compatibility modes. I don't know if this was intentional. You may open another issue for these.

**Comment by Calinou** [comment]
> AFAIK, the gizmos and grid lines inside the editors are also counted in the draw call counter in Mobile and Compatibility modes. I don't know if this was intentional. You may open another issue for these.

There's already an open issue: https://github.com/godotengine/godot/issues/49820
