### ISSUE TITLE
Find in Files doesn't search in `.cs` files out of the box in Mono build

### ISSUE THREAD

**Issue by alakoring** [godotengine/godot#95496]
### Tested versions

Reproducible in 4.3 RC3
Not reproducible in 4.2

### System information

Godot v4.3.rc3.mono - macOS 12.7.6 - GLES3 (Compatibility) - Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

After I updated to 4.3 RC3, Find in Files no longer returns any results.

### Steps to reproduce

Using not-menu-bar, **Search** > **Find in Files** (or shift+command+F).
Enter text you can see
Click **Find…**

Search results are empty and show 0 matches in 0 files.
<img width="1398" alt="Screen Shot 28" src="https://github.com/user-attachments/assets/533471c0-abb9-4887-9f5e-78a3e4053362">

### Minimal reproduction project (MRP)

My sincere apologies, this did work with a new project. It repeatedly fails with my large project (unless I go back to 4.2). So I can’t provide an MRP. I do want to make you aware of the bug, however.

**Comment by bruvzg** [comment]
Is it text in the `cs` files? I do not see `cs` in the filter list, so it's possible that https://github.com/godotengine/godot/pull/94680 has not fixed all .NET detection cases (project settings might too early to check for the class type)

**Comment by alakoring** [comment]
I found #52789 which seemed to suggest `.gdignore` was responsible. If I remove this file, Find in Files works as expected.

If I create a brand new project with one Control and one attached GDScript script, I cannot find the text in that script after I create a `.gdignore` at the top level.

**Comment by alakoring** [comment]
This is a mixed GDScript/C# project, so not sure why .cs isn’t showing up as an option. However, I am using Godot to search my .gd files, which is what is failing.

**Comment by raulsntos** [comment]
> If I create a brand new project with one Control and one attached GDScript script, I cannot find the text in that script after I create a `.gdignore` at the top level.

That seems to be intentional, directories with a `.gdignore` file are ignored.
- https://github.com/godotengine/godot/pull/51081
- https://github.com/godotengine/godot/pull/85943

**Comment by alakoring** [comment]
Fair enough, I’ll have to see why I wanted to exclude files from res:// (probably to keep ReadMe.txt from cluttering the Godot editor file list), and if there’s a different way to do it.

**Comment by akien-mga** [comment]
To be clear, `.gdignore` excludes the whole folder it's in. It's not a pattern-based exclusion list like `.gitignore`, just the presence of the file (empty) means the folder is excluded.

**Comment by alakoring** [comment]
In fact, everything worked in 4.2 with a top-level `.gdignore`, and it looked like only Find in Files stopped working in 4.3 RC3. (But I don’t think any of files I didn’t want to see were actually excluded from the file list!) I removed it as that seems to be the intent.

Not sure if I should close the issue though, it does seem odd that none of the `.cs` files could be searched.

**Comment by akien-mga** [comment]
> Not sure if I should close the issue though, it does seem odd that none of the `.cs` files could be searched.

I repurposed the issue to keep track of that, which should be fixed when #95502 is merged.
