### ISSUE TITLE
Editor crash without any logs when re-importing empty obj file

### ISSUE THREAD

**Issue by xbelanch** [godotengine/godot#95515]
### Tested versions

Reproducible in v4.2.2.stable.arch_linux

### System information

Godot v4.2.2.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 11 Aug 2024 16:19:06 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (nvidia; 555.58.02) - Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (28 Threads)

### Issue description

Attempting to open a scene containing an empty obj file as asset  crashes the editor without any logging.

### Steps to reproduce

1. Re-export from Blender an empty scene to obj file format (or with models but without "Selection Only" marked)
2. Open scene from Godot Editor that includes this asset (obj file).

### Minimal reproduction project (MRP)

[Bug-obj.zip](https://github.com/user-attachments/files/16611105/Bug-obj.zip)

**Comment by AThousandShips** [comment]
Sounds like a duplicate of:
* https://github.com/godotengine/godot/issues/89776

Which has been solved, please try with [4.3.rc3](https://godotengine.org/article/release-candidate-godot-4-3-rc-3/) to confirm, a fix will appear in a future 4.2.x version

**Comment by xbelanch** [comment]
Confirmed it works with [4.3.rc3](https://godotengine.org/article/release-candidate-godot-4-3-rc-3/).
