### ISSUE TITLE
Editor crash when editing project with a specific GDExtension

### ISSUE THREAD

**Issue by alittlewhitey** [godotengine/godot#95522]
### Tested versions

4.2 stable with godot-cpp 4.2

### System information

Linux Mint 21.3 x86_64

### Issue description

When I use gdextension to write my app , I got a crush. This BACKTRACK print looks so special and I could hardly find the reason.
![error](https://github.com/user-attachments/assets/ba023a90-be6f-44d8-b2ed-fdd051669516)
Because it had not entry godot execution I guess this is a bug
And normal crash should be like this:
![normal](https://github.com/user-attachments/assets/64023558-4ddd-4bb4-a9e3-a7d197309dba)

### Steps to reproduce

none

### Minimal reproduction project (MRP)

I even can't find the code that cause this error 
but I make a copy of my wrong codes and upload it to:
https://github.com/alittlewhitey/MyGDEXTENSION_Bug
I bless it is a truly bug......

**Comment by AThousandShips** [comment]
Can't test this specifically right now but looking at some of the code this could be related to this:
* https://github.com/godotengine/godot-cpp/issues/1326

Can you please show the options you used when building?

**Comment by alittlewhitey** [comment]
This issue does not look like problem I had meet. I just downloaded godot from official website. I just use this Cmakelists with Environment var

**Comment by alittlewhitey** [comment]
This issue does not look like problem I had meet. I just downloaded godot from official website. I just use this Cmakelists with Environment var GalEnvironment as 0.

**Comment by alittlewhitey** [comment]
I had finished code changing.
Now please use 

cmake . -DGalEnvironment=0
make

to finish build.
Thanks for your help

**Comment by alittlewhitey** [comment]
Thanks, I got help from others and found that it was a misunderstanding. I will now close this issue.
