### ISSUE TITLE
Incorrect warning; SkeletonModifier3D has no option to set external skeleton

### ISSUE THREAD

**Issue by Flynsarmy** [godotengine/godot#95537]
### Tested versions

- Reproducible in 4.3-rc3

### System information

Windows 11, geForce 4080, Godot 4.3-rc3, Forward+

### Issue description

When adding a `SkeletonModifier3D` node not as a child of a `Skeleton3D` a warning appears requiring, amongst other options, the dev sets a path to an external skeleton on it:
![image](https://github.com/user-attachments/assets/f8beb06a-a10a-4bb7-97c3-aabe578528ac)

however the node has no option to set an external skeleton:
![image](https://github.com/user-attachments/assets/f0719cb1-6b0a-4ce4-ad1b-cb4227b8ccae)

### Steps to reproduce

- Create a script that extends `SkeletonModifier3D`. Give it a class name and nothing else:
`
extends SkeletonModifier3D
class_name MySkeletonModifier
`
- Add an instance of the node anywhere except as a child of `Skeleton3D`
- The warning will display but there is no option to set an external skeleton

### Minimal reproduction project (MRP)

[skeletonmodifier3d.zip](https://github.com/user-attachments/files/16621504/skeletonmodifier3d.zip)

Open main.tscn.

**Comment by Flynsarmy** [comment]
The two options available to fix this are to 
1. Change the warning message to remove the reference to setting an external skeleton or
2. Add the same external skeleton options available on BoneAttachment3D: 
![image](https://github.com/user-attachments/assets/fc4c5213-222a-4afa-a330-d73774896fac)

IMO 2 is preferable as it keeps things consistent across skeleton attachment nodes.

**Comment by fire** [comment]
I believe @TokageItLab had technical reasons to remove the external skeleton feature. I'll try to get some details.

**Comment by TokageItLab** [comment]
It was planned in the past, but was removed after discussions with @reduz. See also https://github.com/godotengine/godot/pull/87888#issuecomment-2016758350.

When setting up an external Skeleton, the process and physics process must be registered on the SkeletonModifier side, not on the Skeleton, which can cause performance issues. Moreover if the deferred process is registered on the SkeletonModifier side, there may be confusion in the update process.

**Comment by Flynsarmy** [comment]
Is it correct to close this issue when the warning message is still wrong?

**Comment by TokageItLab** [comment]
Ah right, warning should be fixed.
