### ISSUE TITLE
Suggestions for the 'for' statement with Array

### ISSUE THREAD

**Issue by ProgrammerMao** [godotengine/godot#95531]
### Tested versions

v4.2.2 stable

### System information

Win10 22H2, NVIDIA GTX1060

### Issue description

Run the following code in the script
```
var array = ["a", "b", "c"]
for i in array:
	print("now index: ", array.bsearch(i))
	print("now item: ",i)
	print("--")
	array.erase(i) #The execution of this sentence resulted in an incorrect outcome
```
The following output will be obtained
```
--wrong--
now index: 0
now item: a
--
now index: 1
now item: c
--
```
My expectation is to traverse all the content and get this output
```
--wrong--
now index: 0
now item: a
--
now index: 1
now item: b
--
now index: 1
now item: c
--
```
Although this is something that users should pay attention to, I think it can be optimized to make it easier to use

### Steps to reproduce

Same issue description

### Minimal reproduction project (MRP)

[for_item_in_Array.zip](https://github.com/user-attachments/files/16618818/for_item_in_Array.zip)

**Comment by Calinou** [comment]
Arrays and dictionaries should not have entries erased during iteration. Otherwise, undefined behavior occurs as described here.

Closing in favor of https://github.com/godotengine/godot/issues/32261.
