### ISSUE TITLE
Build failure with MSVC in platform/iphone/export/export.cpp: 'chmod': identifier not found

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#9554]
**Operating system or device - Godot version:**
Windows 10 with VS2015

**Issue description:**
platform\iphone\export\export.cpp(265): error C3861: 'chmod': identifier not found
scons: *** [platform\iphone\export\export.windows.tools.64.obj] Error 2
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
Regression from @BastiaanOlij's #9511.
