### ISSUE TITLE
[3.0] String.match() not found.

### ISSUE THREAD

**Issue by ducdetronquito** [godotengine/godot#9556]
**Operating system or device - Godot version:**
Ubuntu 17.10 - Godot v3.0-alpha.custom_build

**Issue description:**

I compiled the master branch yesterday evening and I am not able to use the String.match() function anymore.

Whatever parameter I pass, it raises the following error:
> error(9, 13): Expected identifier as member

The String.matchn() function seems work though.

It's weird because the ustring.cpp code has not been touched for a long time :confused: 

**Steps to reproduce:**

```gdscript
extends Node

func _ready():
	var title = 'Hello world!'
	print(title.match('Hello*'))
```

**Comment by volzhs** [comment]
I guess it is because "match" became keyword.
there is related issue for this.

**Comment by vnen** [comment]
Seems like a duplicate of #8085.

**Comment by hubbyist** [comment]
@karroffel noted same method here https://github.com/godotengine/godot/issues/8085#issuecomment-290711293

**Comment by Noshyaar** [comment]
This seems to be fixed in the latest master.

**Comment by akien-mga** [comment]
Indeed, fixed by @bojidar-bg.
