### ISSUE TITLE
uid:// Paths Fail to Load at Editor Startup

### ISSUE THREAD

**Issue by mpewsey** [godotengine/godot#95562]
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8]
- Not reproducible in v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 11 v4.3.stable.mono.official [77dcf97d8]

### Issue description

In Godot 4.3.0, when opening a project that loads a resource by a uid:// path at startup, the resource fails to load.

The attached MRP uses the following plugin script to load a resource at startup:

```.gd
@tool
extends EditorPlugin


func _enter_tree():
	var uidPath = "uid://dr1hds7vve78t";
	var resPath = "res://resource.tres";
	var uidResource = ResourceLoader.load(uidPath);
	
	if uidResource == null:
		printerr("Resource is null, meaning it couldn't be loaded by uid:// path.")
	else:
		print("Resource could be loaded by uid:// path.")

	var resResource = ResourceLoader.load(resPath);

	if resResource == null:
		printerr("Resource is null, meaning it couldn't be loaded by res:// path.")
	else:
		print("Resource could be loaded by res:// path.")

```

With this, I get the following errors at startup:

```
Godot Engine v4.3.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
  core/io/resource_uid.cpp:132 - Condition "!unique_ids.has(p_id)" is true. Returning: String()
  Resource file not found:  (expected type: )
  Error loading resource: 'uid://dr1hds7vve78t'.
  Resource is null, meaning it couldn't be loaded by uid:// path.
Resource could be loaded by res:// path.
```

This issue does not occur with the MRP using v4.2.2.stable.mono.official [15073afe3], so there seems to be a regression between 4.2.2 and 4.3.0.

I believe the issue in #95535 may be related.

Once the editor has fully started up, if you toggle the plugin to invoke the `_enter_tree` method again, Godot is able to successfully load the resource by uid:// at that point.

### Steps to reproduce

* Open the MRP in Godot 4.3.0.
* The error should appear in the log. If it doesn't, enable the GdDummy plugin from the `Project > Project Settings > Plugins` tab.

### Minimal reproduction project (MRP)

[GodotUidBug-main.zip](https://github.com/user-attachments/files/16626169/GodotUidBug-main.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #92303 as the culprit: 

![image](https://github.com/user-attachments/assets/8226e2eb-5720-4106-81e6-87b35bc2cd78)

**Comment by akien-mga** [comment]
CC @Hilderin
