### ISSUE TITLE
Tilemap Node Depreciation warning is incorrect

### ISSUE THREAD

**Issue by Tekuzo** [godotengine/godot#95565]
### Tested versions

Tested in 4.3 official release

### System information

MacOS 14.5 Apple M3 Pro

### Issue description

The warning that is displayed on the, now depreciated, tilemap node states that the tool to convert this node into tylemaplayer nodes is at the top right of the tilemap bottom panel, when it is at the top left.
![Screenshot 2024-08-15 at 10 45 11 AM](https://github.com/user-attachments/assets/fc6f4cf1-54eb-40eb-bf7b-232f13ff6200)

### Steps to reproduce

This is an issue with the editor. There are no steps to reproduce.

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16626561/new-game-project.zip)

**Comment by AThousandShips** [comment]
It's on the top right if the window isn't too small

**Comment by Tekuzo** [comment]
Thank you

**Comment by Tekuzo** [comment]
Thank you. my mistake
