### ISSUE TITLE
Incorrect date of project in Android Editor 

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#95576]
### Tested versions

- Reproducible in 4.3.stable ,4.3rc2

### System information

Android 11 - godot4.3.stable - redmi 10 2022

### Issue description

The dates of every project looks really wrong
![Screenshot_2024-08-15-23-20-24-534_org godotengine editor v4](https://github.com/user-attachments/assets/fde76930-7b5f-4ee2-a1bb-bc8ff6db68d3)
![Screenshot_2024-08-15-23-30-38-383_org godotengine editor v4](https://github.com/user-attachments/assets/07c5fb6b-efe7-4d14-b5f3-c2db83a63d70)

### Steps to reproduce

Just create a new project. Quit to project list. See the date.
Another info that I don't know the relevance of, I installed the 4.3.stable as an update.
Meaning i didn't uninstall the previous version before installing 4.3.stable.

### Minimal reproduction project (MRP)

N/A

**Comment by rossbridger** [comment]
Fresh Godot 4.3 installation from Google play also has the same issue

**Comment by AThousandShips** [comment]
To clarify 4.2.2 does *not* have this issue?

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by shahriarlabib000** [comment]
> To clarify 4.2.2 does _not_ have this issue?

4.2.2.stable doesn't even show the date or time
![Screenshot_2024-08-16-00-50-21-000_org godotengine editor v4](https://github.com/user-attachments/assets/cee3346d-6c5c-44b9-ac3a-4e524dad81f0)

**Comment by shahriarlabib000** [comment]
Seems like the time is wrong as well.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/godotengine/godot/pull/95586; it was a simple unit conversion error.
