### ISSUE TITLE
Compile failure VS2015: cannot convert argument 1 from 'Image' to 'const Ref &'

### ISSUE THREAD

**Issue by AnomalyAces** [godotengine/godot#9557]
**Operating system or device - Godot version:**
Windows 10 - Godot 3.0

**Issue description:**

Compile failure as follows:
scons: *** [editor\editor_initialize_ssl.windows.tools.32.obj] Error 2
editor\editor_icons.cpp(5943): error C2664: 'void ImageTexture::create_from_image(const Ref<Image> &,uint32_t)': cannot convert argument 1 from 'Image' to 'const Ref<Image> &'
editor\editor_icons.cpp(5943): note: Reason: cannot convert from 'Image' to 'const Ref<Image>'
editor\editor_icons.cpp(5943): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
scons: *** [editor\editor_icons.windows.tools.32.obj] Error 2
scons: building terminated because of errors.

**Steps to reproduce:**
pull down current master branch
compile code using scons platform=windows in the Developer Command Prompt for VS2015 at the root directory of the godot project

**Comment by vnen** [comment]
`editor_icons.cpp` is a generated file and had the name changed (#9334). You need a clean clone to build correctly.

**Comment by AnomalyAces** [comment]
Hey I grabbed the latest from the repository.  attempted to run it using the Developer Command Prompt for VS2015 and got the following error

scons: Building targets ...
rc /Icore /Icore\math /Ieditor /Idrivers /I. /Iplatform\windows /Ithirdparty\zstd /Ithirdparty\zstd\common /Ithirdparty\zlib /Ithirdparty\rtaudio /Ithirdparty\glad /Ithirdparty\freetype /Ithirdparty\freetype\include /Ithirdparty\libpng /foplatform\windows\godot_res.windows.tools.32.obj platform\windows\godot_res.rc
'rc' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [platform\windows\godot_res.windows.tools.32.obj] Error 1
scons: building terminated because of errors.

**Comment by vnen** [comment]
This is odd, `rc` should be available in the VS prompt. Did you install all the C++ tools?

**Comment by RandomShaper** [comment]
Are you using by any chance the standalone MSVC 2015 toolchain provided with VS 2017? 

It has issues to be solved by Microsoft. I have a workaround and can tell you what to do if that's the case.

**Comment by reduz** [comment]
haven't seen similar reports in a while, so i guess this is fixed since some time
