### ISSUE TITLE
Selecting an existing resource in the "Save Resource As..." dialog changes label of the save button from "Save" to "Open"

### ISSUE THREAD

**Issue by spalose** [godotengine/godot#95589]
### Tested versions

Reproducible in Godot v4.2.1.stable.official [b09f793f5]

### System information

Windows 11 - Godot v4.2.1.stable.official - Vulkan (Compatibility)

### Issue description

When attempting to save a resource, I often click the name of an existing, similar resource to populate its file name into the Save dialog. I do this primarily to shortcut typing time and to maintain my own naming conventions. Today I tried to do this with a LabelSettings resource, but when I clicked on the resource I wanted to fetch the file name of, the "Save" button turned into an "Open" button.

This felt strange to me, because I haven't noticed this ever happening before for other save/open dialog boxes. My expectation was either that the dialog would allow me to overwrite the selected resource, or simply use its file name as a shortcut for typing out a new one.

![godot_bug_saveas](https://github.com/user-attachments/assets/91c36e82-a7a8-4052-9689-a48bbfa73ccf)

### Steps to reproduce

1. Add a **Label** node to your scene.
2. Create a new **LabelSettings** resource through the Inspector and expand it.
3. Modify the label settings in some way.
4. Click the down arrow button next to LabelSettings to open the flyout, then click _"Save As"_.
5. Give the resource a name and click _"Save"_.
6. Duplicate the **Label** node in the scene tree, then click on it to bring up its inspector parameters.
7. Expand the **LabelSettings** parameter for the new node and make any adjustment to the settings values.
8. **Repeat step 4** to open the _"Save As"_ dialog.
9. Take note of the _"Save"_ button at the bottom of the dialog.
10. Click the resource you created in **step 5**.
11. ---> The file name of the resource you clicked will properly populate in the text field, but the _"Save"_ button will turn into an _"Open"_ button.

### Minimal reproduction project (MRP)

[MRP_SaveResourceAsBug.zip](https://github.com/user-attachments/files/16629960/MRP_SaveResourceAsBug.zip)

**Comment by AThousandShips** [comment]
Please try with a supported version like 4.2.2 or 4.3 to confirm this hasn't already been fixed

**Comment by spalose** [comment]
Looks like it's displaying properly in 4.3.0 - sorry about that!
