### ISSUE TITLE
False positive on unused signal warning (UNUSED_SIGNAL)

### ISSUE THREAD

**Issue by therealrottis** [godotengine/godot#95587]
### Tested versions

The bug was not present in 4.2

### System information

Windows 10 - Godot v4.3.stable

### Issue description

Example of script that gives warning:

W 0:00:00:0761   The signal "finished" is declared but never explicitly used in the class.
  <GDScript Error>UNUSED_SIGNAL
  <GDScript Source>grassanimation.gd:4

```gdscript
class_name GrassAnimation
extends Sprite2D

signal finished

var ppcc : int = 0
## set by animate_grass
var layer : Ground.LAYER

var ground : Ground

func _ready() -> void:
	ground = $"../"

func _physics_process(_delta : float) -> void:
	ppcc += 1
	if ppcc % 4 == 0:
		if frame >= hframes - 1:
			emit_signal("finished")
			ground.foliage_sprites.erase(self)
			self.queue_free()
			return
		frame += 1
```

The signal is then used in another script:
```gdscript
	#...
	animation.hframes = 9
	
	await animation.finished # here
	tilemap.set_cell(layer, pos, 0, atlas_for(grassname))
```

### Steps to reproduce

- Create new project
- Attach a script to any node
- Script:
```gdscript
extends Node2D

signal my_signal

func _ready() -> void:
	emit_signal("my_signal")
```

### Minimal reproduction project (MRP)

[new_game_project.zip](https://github.com/user-attachments/files/16629475/new_game_project.zip)

**Comment by therealrottis** [comment]
Workaround: change emit_signal("signal_name") to signal_name.emit()

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/89632

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened (please try searching for other issue reports before opening your own in the future)
