### ISSUE TITLE
C# GlobalClass icons (using IconAttribute) no longer allow relative paths

### ISSUE THREAD

**Issue by Maximilian-Seitz** [godotengine/godot#95592]
### Tested versions

Reproducable starting: 4.3 (mono) dev [5815d1c] (this is the exact commit that introduced the bug)

### System information

All systems

### Issue description

A custom node/resource icon, in C#, used to accept relative paths (to the script file), but now all icon paths are treated as absolute (from `res://`). Relative paths still work in GDScript.

Notes: The code for resolving relative paths used to be in `modules/mono/csharp_script.cpp`, in the `CSharpLanguage::get_global_class_name` method, but has been deleted without replacement.

### Steps to reproduce

Create a `GlobalClass` `Node` or `Resource` with an `Icon` attribute with a relative path. Move this script to a sub-directory of `res://`, and place the icon file relative to the script (according to the path). This will fail to resolve the icon, and try to find it starting from `res://`, rather than the script file path.

### Minimal reproduction project (MRP)

With the following script in a file `res://scripts/MyNode.cs`:

```C#
using Godot;

[GlobalClass]
[Icon("./MyNode.svg")]
public partial class MyNode : Node { /* code */ }
```

The icon path now resolves to `res://MyNode.svg`, whereas it used to resolve to `res://scripts/MyNode.svg`.

**Comment by sirjoehighton** [comment]
Upvote!

**Comment by Calinou** [comment]
@sirjoehighton Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
