### ISSUE TITLE
Signals with typed arrays cannot be emitted with empty arrays

### ISSUE THREAD

**Issue by KaDokta** [godotengine/godot#95596]
### Tested versions

Reproducible in 4.3.stable, 4.1.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

Emitting a signal that has a typed array as a parameter with an empty array gives the error "`Cannot convert argument from Array to Array`" if the signal is connected. Works with untyped array. 

Might be related to the issues described in proposal [#7364](https://github.com/godotengine/godot-proposals/discussions/7364).

A simple type safe workaround is to create a new class containing that typed array as a member and just emit that (or null).

### Steps to reproduce

1. Emitter class:
```gdscript
extends Node

signal test(value: Array[String])

func _ready() -> void:
	test.emit([])
```
2. Receiver class:
```gdscript
extends Node

func _on_node_test(value: Array[String]) -> void:
	pass

```
3. Connect emitter to receiver class.
4. See error in debugger: 
```
E 0:00:01:0996   Test.gd:6 @ _ready(): Error calling from signal 'test' to callable: 'Node2D(TestReceiver.gd)::_on_node_test': Cannot convert argument 1 from Array to Array.
  <C++ Source>   core/object/object.cpp:1200 @ emit_signalp()
  <Stack Trace>  Test.gd:6 @ _ready()
```

### Minimal reproduction project (MRP)

[testarray.zip](https://github.com/user-attachments/files/16630783/testarray.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92215, as this is due to the same cause.
