### ISSUE TITLE
Environment fog does not affect sky, even with "Sky Affect" set to 1 (Vulkan)

### ISSUE THREAD

**Issue by JulianHeuser** [godotengine/godot#95591]
### Tested versions

- Reproducible in 4.3.stable
- Not present in 4.2.2.stable

### System information

Godot v4.3.stable - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (RADV NAVI23) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

The Sky Affect property for fog in an Environment should make the fog color affect sky. In 4.2, this is what happened, but in 4.3 this is broken, and Sky Affect has no effect.

This may be related to [66456](https://github.com/godotengine/godot/issues/66456), although this issue occurs with Vulkan. I haven't tested OpenGL.

Before:
![image](https://github.com/user-attachments/assets/54bd2f45-6854-4999-b3ff-516bc4209cf9)

After:
![image](https://github.com/user-attachments/assets/d13c7439-c4cf-4cc1-aaab-a99270f4f83a)

### Steps to reproduce

1. Create a 3D scene with a world environment
2. Add an environment
3. Give the environment a background
4. Enable fog (give it a recognizable color)
5. Change the "Sky Affect" value to 1
6. If no other objects are present in the scene, the fog won't be visible
7. If you insert a meshinstance3d, the fog will be visible on the object.

### Minimal reproduction project (MRP)

[GodotFogIssue.zip](https://github.com/user-attachments/files/16630218/GodotFogIssue.zip)

**Comment by JulianHeuser** [comment]
Found out that this works as intended with the "Background Mode" set to "Sky" and a sky added.

![image](https://github.com/user-attachments/assets/68f345a5-308f-4a51-94c3-2afc25f5f1e1)

**Comment by clayjohn** [comment]
Looks like the problem is only in the Forward+ Renderer. In the Compatibility renderer `fog_sky_affect` never worked.

**Comment by clayjohn** [comment]
Regression from https://github.com/godotengine/godot/pull/91642. I should have a fix ready in a few minutes

**Comment by JulianHeuser** [comment]
Thanks! I literally just found that myself so good timing lol.

> Regression from #91642. I should have a fix ready in a few minutes

**Comment by clayjohn** [comment]
PR is up! We will aim to have this fixed for 4.3.1 and 4.4
