### ISSUE TITLE
GDShader compiler crashes when typing a non-`flat` integer-like `varying` field in code

### ISSUE THREAD

**Issue by geekley** [godotengine/godot#95599]
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8], v4.2.2.stable.flathub [15073afe3]

### System information

Godot v4.3.stable.mono - Ubuntu 24.04 LTS 24.04 - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 Threads)

### Issue description

On Godot 4.3 for me, this shader "crash" makes the editor freeze for a while before logging lots of error output.
On boolean types, this doesn't happen, it's just a normal error in code.
Is `varying [smooth]` allowed on integer types?
- If yes, must fix compiler
- If not, must gracefully show error like in boolean;
    - Arguably, it may be worth to consider changing language semantics to default to `flat` on integer types when the interpolation qualifier is absent (reflecting it in docs too).

### Steps to reproduce

```glsl
shader_type spatial;

// OK; adding flat or smooth gives graceful error
varying bool vb;
varying bvec2 vba;

// Remove flat (or change to smooth) in any of these to crash
varying flat int vi; //CRASH
varying flat highp uint vu; //CRASH
varying flat lowp ivec3 via; //CRASH
varying flat uvec4 vua; //CRASH
```

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
Did not reproduce in  Godot v4.4.dev (ee363af0e) , I suppose it's already fixed in master.

![image](https://github.com/user-attachments/assets/7ec8b0d0-6160-4090-bd60-8fa4f2942c22)

**Comment by geekley** [comment]
@jsjtxietian no, remove `flat` and leave only `varying`

**Comment by jsjtxietian** [comment]
Oh sorry, my bad, it crashed lol.

**Comment by geekley** [comment]
I'm curious about why does boolean varying types allow neither `flat` nor `smooth`. Why is that, and how does it work exactly? Does that mean there's a third varying mode specific to booleans? Is it different than `flat` used in integers?
