### ISSUE TITLE
Editor viewport hotkeys don't work when property inspector has focus

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#95607]
### Tested versions

- Reproducible in 4.3.stable
- Not reproducible in 4.2.2.stable

### System information

Windows 10 - Godot 4.3.stable - Vulkan (Forward+)

### Issue description

None of the viewport hotkeys (like Numpad_1, Numpad_3, F) work when anything on the property inspector has focus.

![image](https://github.com/user-attachments/assets/cb5c12b1-6ad6-412d-ab80-929d1e5bcec9)

The issue seems to be related viewport not gaining focus once the mouse has left the inspector panel towards the viewport, on 4.2 the view would automatically gain focus as soon as the mouse is over it

### Steps to reproduce

- Click any property on the property inspector (like scale)
- Press Enter or Escape
- Move the mouse over the view and try any hotkeys

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
I'd say this is desired, I wouldn't want or expect the viewport to update when focused in the inspector, I'd consider *that* a bug rather

**Comment by wagnerfs** [comment]
@AThousandShips can't agree, you have to basically click the viewport to be able to change angles for example, that quickly becomes counterproductive when you just want to update inspector values like position using the mouse or a specific typed in value, let's say, to try and center a `MeshInstance3D` to the origin, then having to click back to the view, most likely deselect the said `MeshInstace3D` and lose the entire inspector you were fiddling with just a second ago.

On top of that, since the auto focus isn't working on 4.3, clicking on the `MeshIsntance3D` on the scene tree view won't focus the view either, which means you'd STILL need to click on the view to be able to change angles or doing any hotkeys, and again, unless you had to precisely click on said `MeshInstance3D` within the view (that surely won't scale well on large scenes), you'd most likely deselect the node again.

**Comment by AThousandShips** [comment]
Since it changed between 4.2 and 4.3 it'd be important to identify when it was changed, will try identify it, and from there there would be two paths:
* If it was accidental this should be discussed, but I don't think that change would obviously be a bug
* If it was intentional then a proposal for controlling this with a setting should be opened [here](https://github.com/godotengine/godot-proposals/issues) instead

Will respond when I've found when this was changed

**Comment by Calinou** [comment]
- Possibly related to https://github.com/godotengine/godot/issues/95639.

@wagnerfs Can you try following the same steps on 4.3 dev/beta/RCs to determine when the regression started? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.3/).

**Comment by wagnerfs** [comment]
@Calinou just tested, RC1 was the one that broke it, Dev6 was working fine.

**Comment by matheusmdx** [comment]
Bisecting points to #93165 as the culprit:

![image](https://github.com/user-attachments/assets/451c2640-dd7e-4201-acba-d78852d7b0ff)

**Comment by wagnerfs** [comment]
@matheusmdx if you talk only about the focus then absolutely, only a click away, productivity wise it's a mess, I've explained it here though: https://github.com/godotengine/godot/issues/95607#issuecomment-2293425305

**Comment by wagnerfs** [comment]
I got a bit of time to check that PR and indeed, that was the issue, I managed to get it fixed by instead of having `EditorSpinSlider::is_text_field` always returning `true`, change the return to `value_input_popup && value_input_popup->is_visible();` since it's when and only when the spin field has "become" a text field, so it doesn't rollback that PR at all.

I'll probably get a PR with the fix ready when I get some free time.
