### ISSUE TITLE
Compiling editor without X11 support causes OpenXR to stop the compilation

### ISSUE THREAD

**Issue by xana43** [godotengine/godot#95608]
### Tested versions

- First seen in godot 4.3 stable

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) () - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

when compiling a custom editor/template, if the openXR module is enabled and X11 is disabled then an error occurs doing compilation

`In file included from modules/openxr/extensions/platform/openxr_opengl_extension.cpp:31:
modules/openxr/extensions/platform/openxr_opengl_extension.h:71:16: error: 'XrGraphicsBindingOpenGLXlibKHR' does not name a type; did you mean 'XrGraphicsBindingOpenGLWaylandKHR'?
   71 |         static XrGraphicsBindingOpenGLXlibKHR graphics_binding_gl;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                XrGraphicsBindingOpenGLWaylandKHR
modules/openxr/extensions/platform/openxr_opengl_extension.cpp: In member function 'virtual void* OpenXROpenGLExtension::set_session_create_and_get_next_pointer(void*)':
modules/openxr/extensions/platform/openxr_opengl_extension.cpp:184:17: error: 'graphics_binding_gl' was not declared in this scope
  184 |         return &graphics_binding_gl;
      |                 ^~~~~~~~~~~~~~~~~~~
In file included from ./modules/openxr/openxr_api.cpp:53,
                 from modules/openxr/scu/scu_modules_openxr.gen.cpp:1:
./modules/openxr/extensions/platform/openxr_opengl_extension.h:71:16: error: 'XrGraphicsBindingOpenGLXlibKHR' does not name a type; did you mean 'XrGraphicsBindingOpenGLWaylandKHR'?
   71 |         static XrGraphicsBindingOpenGLXlibKHR graphics_binding_gl;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                XrGraphicsBindingOpenGLWaylandKHR
`

### Steps to reproduce

disable X11 support in the scons options, enable OpenXR if disabled and try to compile

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Related to #70199 and #73504.

**Comment by juanjp600** [comment]
I believe this might've been fixed by #97771. As of 61accf060515416da07d913580419fd8c8490f7b I'm able to compile without error using `scons x11=no module_openxr_enabled=yes`
