### ISSUE TITLE
[3.0] During Import Process of Assets Engine Crashes

### ISSUE THREAD

**Issue by AnomalyAces** [godotengine/godot#9560]
**Operating system or device - Godot version:**
Windows 10
Godot 3.0

**Issue description:**

When the engine starts it tries to auto import resources. During this process I receive the following errors:

This error occurs throughout the import process:
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: Error has been generated. GL error GL_INVALID_OPERATION in DisableVertexAttribArray: (ID: 3860911800) Generic error

+And this last error is what i get before it crashes: 
ERROR: alloc_static: Condition ' !mem ' is true. returned: __null
   At: core/os/memory.cpp:67

**Steps to reproduce:**
Have about 11MB worth of pngs in the res:// location to import.

Start the engine and let the auto import process at the beginning run

**Comment by vnen** [comment]
Are you using a recent commit? What is your graphics card? Does it really crash or it just freezes and stops responding? If the import takes a long time, the editor will be unresponsive while it happens.

**Comment by akien-mga** [comment]
> Are you using a recent commit? What is your graphics card? Does it really crash or it just freezes and stops responding? If the import takes a long time, the editor will be unresponsive while it happens.

Bump.

**Comment by Zylann** [comment]
I got the same error, but a little while after the import process, and it spams at every editor frame:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.
   At: drivers\gles3\rasterizer_gles3.cpp:123
mesege
```

**Comment by AnomalyAces** [comment]
I was using the latest commit from the master branch.  My graphics card is NVIDIA GeForce GTX 970M. It actually crashes.... Windows brings up the message saying godot has stopped working with the only option given to me is to stop the program

Hope this helps!

**Comment by bkeys** [comment]
Can confirm it happens here too

**Comment by KoBeWi** [comment]
> Have about 11MB worth of pngs in the res:// location to import.
> Start the engine and let the auto import process at the beginning run

I tried this in 3.0 with twice more data and the crash doesn't happen.

@AnomalyAces Any chance you are still alive and can test it in 3.1? Was the crash consistent?

**Comment by AnomalyAces** [comment]
@KoBeWi whoa! what a blast from the past. I am still alive and kicking but after issues I was facing a couple of years ago I started to port my project to a different platform. I may still my old project files and if I do I can update to 3.1 and give it a shot.

**Comment by vnen** [comment]
This is an old issue and no one else commented with a confirmation. Let's close this for now.

@AnomalyAces if you can test on a recent Godot version and confirm it still happens, we can reopen and investigate.
