### ISSUE TITLE
`InputEventJoypadButton` and `InputEventJoypadMotion` do not have common base type (no abstract type `InputEventJoypad`)

### ISSUE THREAD

**Issue by jolexxa** [godotengine/godot#95615]
### Tested versions

All versions

### System information

n/a

### Issue description

`InputEventJoypadButton` and `InputEventJoypadMotion` do not have common base type (no abstract type `InputEventJoypad`). This is trivial, but flagging anyways since it seems like a simple oversight.

Other related input events share a type hierarchy which allows for convenient pattern matching with inputs.

For example, `InputEventMouseMotion` and `InputEventMouseButton` share a common base type, `InputEventMouse`. This allows mouse events to be easily disambiguated with pattern matching, and, more importantly, be stored under their related base type while still being more specific than just `InputEvent`.

Reasoning: currently working on some input utilities and it would be nice to store related joypad input events under a less specific `InputEventJoypad` type rather than resorting to just `InputEvent`.

### Steps to reproduce

Nothing to reproduce — this is simply the lack of an abstract base class. Not worth proposing a feature over as it seems like an oversight.

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead. While this might be an oversight it's not necessarily a bug, and the situation is arguably different as the shared mouse event type has data shared by the types (the positions), the joypad events share no such information

**Comment by akien-mga** [comment]
Indeed, `InputEventMouse` exists not to provide as common base types for mouse events (though I understand how it can be convenient), but because they share a member variable. There wasn't such a need to share member variables for joypad events (beyond `InputEvent` itself) so that's why it doesn't exist.

**Comment by AThousandShips** [comment]
Closing in favour of the proposal
