### ISSUE TITLE
Strange artifacts on the mesh (Godot 3.0)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#9562]
**Operating system or device - Godot version:**
Ubuntu 16.04, GTX 965M, Godot 3.0

**Issue description:**
Blender
![blender](https://user-images.githubusercontent.com/11325733/27985577-c7074b42-641f-11e7-901d-99797c5e2243.png)

Godot
![godot](https://user-images.githubusercontent.com/11325733/27985584-e653310a-641f-11e7-92af-e65ef1f16ad3.png)

**Steps to reproduce:**
Open content.dae in Godot

**Link to minimal example project:**
File
[Model.zip](https://github.com/godotengine/godot/files/1132974/Model.zip)

**Comment by quinnyo** [comment]
The .dae you uploaded doesn't do that for me (latest master branch). Proprietary nvidia linux on geforce 950. Different config somewhere for your test or driver issue perhaps? You can try usual mesh improvements - fix the UVs, better normals / edge split, planar quads, etc, something might pop up.

**Comment by reduz** [comment]
I can't reproduce.. would be interesting to know your GPU model and driver..
![image](https://user-images.githubusercontent.com/6265307/29544758-bf8084ba-86c0-11e7-937f-305ab0817fd6.png)

**Comment by tagcup** [comment]
I was able to reproduce this using current master on Intel 4770K (Haswell) on up-to-date Arch Linux (mesa 17.1.6)

![screenshot_20170821_215933](https://user-images.githubusercontent.com/16531565/29545394-0e2aaeb0-86bc-11e7-8957-87bd5295c89a.png)

**Comment by reduz** [comment]
can you test same chipset on Windows?

**Comment by tagcup** [comment]
I don't have Windows on my desktop PC, sorry

**Comment by reduz** [comment]
damn, so many intel bugs i can't test...

**Comment by tagcup** [comment]
In case you missed it in the email (I edited my original post), it turned out to be a false alarm, I don't think I'm seeing this on Haswell.

**Comment by reduz** [comment]
Well, doesn't look loke that to me, so it seems broken

**Comment by reduz** [comment]
Well, doesn't look loke that to me, so it seems broken

**Comment by eon-s** [comment]
Ubuntu, AMDGPU R5
I guess it should not look like this with a directional light.

![buggysuzzie](https://user-images.githubusercontent.com/10215987/29548314-3eba3b76-86d6-11e7-9397-48b5b1fcfbfd.png)

**Comment by tagcup** [comment]
Ah, that's good to hear. I'll try asking someone with Haswell to test it on Windows
