### ISSUE TITLE
Gizmo elements are affected by Environment and Camera effects, and they affect scene lighting

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#95621]
### Tested versions

4.3 Stable
Any 3.x and 4.x

### System information

Windows 10 22H2

### Issue description

Gizmo elements are being affected by World Environment and Camera effects, such as DOF, SSR, SDFGI, and more. They are also affected by overall sky lighting in the scene. It seems, they are being rendered as some sort of emissive materials.

Which makes very inconsistent UI experience within Godot editor. Instead, all scene UI and controllers (grid, gizmo) should not be affected by any rendering settings or effects.

![image](https://github.com/user-attachments/assets/68592ba1-f791-4ede-8fd4-30191b2146ba)
**(Gizmo just lit up the whole interior on the right)**

![image](https://github.com/user-attachments/assets/c6709b2f-5b1a-4cd1-bc85-2b47b656d3d7)
**(Gizmo elements are being blurred out by DOF)**

### Steps to reproduce

Use any Godot 3/4 version and add World Environment or Camera Attributes to define DOF, SSR, SDF, etc. These features will change the look of Gizmo and Grid. But also Gizmo and Grid will affect the scene elements (they are emissive, and they are being reflected).

### Minimal reproduction project (MRP)

Not required

**Comment by Rinocrosser** [comment]
For comparison, such elements are not being affected by lighting or DOF in any other major engine, they are just there as separate entities. Obviously, they are not impacting light and not being reflected:

![image](https://github.com/user-attachments/assets/06c5d18d-3206-420f-b973-db9a441a888c)

**Comment by AThousandShips** [comment]
Thank you for reporting, this is a missing feature, see:
* https://github.com/godotengine/godot-proposals/issues/2138

Consolidating there
