### ISSUE TITLE
4.2 project getting lagged after 4.3 update

### ISSUE THREAD

**Issue by mini-fox-dz** [godotengine/godot#95636]
### Tested versions

4.3 dev

### System information

windows 10 godot 4.3 dev
CPU: intel i3-3120M
GPU: intel HD 4000

### Issue description

my 4.2 project was getting better fps like 400 or 120 fps but after 4.3 update my game getting 33 - 42 fps

![image](https://github.com/user-attachments/assets/ff5dbbed-1732-4786-ab27-53ee74642630)

### Steps to reproduce

just switched my 4.2 project to 4.3

### Minimal reproduction project (MRP)

cannot convert it

**Comment by akien-mga** [comment]
Please add information about your GPU and GPU drivers.

You can also try to disable vsync in the editor settings and see if that makes a difference.

**Comment by mini-fox-dz** [comment]
disabled V-Sync and i got the same result

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
