### ISSUE TITLE
Tooltip doesn't work behind control node?

### ISSUE THREAD

**Issue by TheWrightDev** [godotengine/godot#95644]
### Tested versions

- Reproducible in v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5161) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

Have an node with a tooltip value, when covered by a control node even with the mouse filter set to pass the tooltip never appears.

### Steps to reproduce

Start with working tooltip.
![image](https://github.com/user-attachments/assets/5021105e-6ee2-4a77-90e9-acb809cb3130)

Add a control node (HUD) over it and set the anchor full rect or size it over your hover element:
![image](https://github.com/user-attachments/assets/a0439537-f8a3-4c6a-82d9-921c4a1e96e8)

Can even try changing the mouse filter on HUD:
![image](https://github.com/user-attachments/assets/fdb28b04-360a-478b-ba03-e5971ab9c6ea)

The tooltip still won't work anymore.

### Minimal reproduction project (MRP)
[ControlTooltip.zip](https://github.com/user-attachments/files/16638952/ControlTooltip.zip)

**Comment by AThousandShips** [comment]
What is the canvas layer or z index of the node? Please upload an MRP to help with testing this, there's too little information here

**Comment by TheWrightDev** [comment]
> What is the canvas layer or z index of the node? Please upload an MRP to help with testing this, there's too little information here

Whatever the defaults are? This is in a fresh project, no adjustments made to any layers. Even messing with that just gives:
![image](https://github.com/user-attachments/assets/ed4ae3c1-6ca3-4f93-a7fd-ded2d710330a)
So I'm not sure how that could have an effect.

Added the MRP all the same, hope it clears it the confusion.

**Comment by AThousandShips** [comment]
My bad misread it as the tooltip was behind

**Comment by AThousandShips** [comment]
It works correctly with `ignore`, I think this is as intended, as it says:
> If this control does not handle the event, the parent control (if any) will be considered, and so on until there is no more parent control to potentially handle it.

But with `ignore` it works correctly and it handles the input, as `pass` transfers it up in the tree

**Comment by TheWrightDev** [comment]
https://docs.godotengine.org/en/stable/classes/class_control.html#enum-control-mousefilter

That is very much not clear from what I was reading in the docs. Especially since with `pass` all normal mouse events still fire (you can buttons through the HUD, just not trigger tooltips). But I guess thanks for the guidance all the same.

**Comment by AThousandShips** [comment]
The documentation specifically mentions the enter/exit events, and specifically says it passes the event to the parent, not any node behind it, so beyond explicitly stating "this does not pass the event to nodes behind it" I'm unsure how to make it clearer

But if you're interested in improving the descriptions please make any suggestions you might have, otherwise we can consider this resolved (also generally it helps testing different options if things don't work immediately, before making a report)
