### ISSUE TITLE
Inconsistent Copy Behavior in Script Editor when Using Wayland Display Driver

### ISSUE THREAD

**Issue by dekotale** [godotengine/godot#95649]
### Tested versions

- Reproducible in: 4.3.stable (Wayland) using GNOME DE.
- Not reproducible in: Windows or with display driver X11, or by using the KDE DE

### System information

Godot v4.3.stable - openSUSE Tumbleweed-Slowroll 20240803 - Wayland - GLES3 (Compatibility) - AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.57, 6.10.3-1-default) - AMD Ryzen 7 7700X 8-Core Processor (16 Threads). GNOME 46.2 DE.

### Issue description

When using the `--display-driver wayland` flag in Godot, there is an inconsistent behavior when copying text from the script editor. The first copy action works as expected, but the second attempt to copy fails. When you try to paste the content nothing sticks, but if you copy something again and try to paste it, then yes... it's like the “even” times you copy don't work, but the “odd” times work.

### Steps to reproduce

1. Launch Godot with the `--display-driver wayland` flag.
2. Open any script in the script editor.
3. Select some text and copy it using Ctrl+C or right click > copy (first copy should works).
4. Paste the text in anywhere and check. (the text must have been pasted correctly)
5. Copy the text one more time (this copy will fail)
6. Paste the text in anywhere and check. (no text should have been pasted)

### Minimal reproduction project (MRP)

[mrp_copy_behaviour.zip](https://github.com/user-attachments/files/16639444/mrp_copy_behaviour.zip)

**Comment by DanielKinsman** [comment]
I can reproduce this when using GNOME, but not when using KDE.

**Comment by dekotale** [comment]
> I can reproduce this when using GNOME, but not when using KDE.

Right, I forgot to mention that my desktop environment is GNOME 46... I didn't remember to try another DE. I'll add this information, thank you very much @DanielKinsman

**Comment by reamicku** [comment]
I can confirm the same behavior on GNOME 46.4

**Comment by esklarski** [comment]
I thought at first I was going crazy and forgetting to press ctrl-c when trying to copy text; when I'd then use ctrl-v there would be no text on the clipboard.

But it does seem there's something wrong with copy/paste when using the editor under Wayland.

I too am on Gnome 46.

**Comment by esklarski** [comment]
I had an update for Gnome's `mutter` come through last night, and this problem seems to be gone.

Not sure what fixed it, but on an up to date Fedora system this is no longer an issue.

**Comment by dekotale** [comment]
@esklarski That's great news! This bug is still happening for me on my fresh Arch Linux install. My **Mutter** version is **47.1-1** from **Oct. 19, 2024**. I'll keep an eye out for updates in the next few days to see if the bug goes away. Thanks for the report!

**Comment by esklarski** [comment]
I used Godot all morning and it didn't happen once. I'd gotten used to it failing, lol.

But on second thought it might not have been mutter... when I check my version I get 46.6. The mystery continues.
