### ISSUE TITLE
AnimationPlayer's default snap value is 0.0333 

### ISSUE THREAD

**Issue by Tugay72** [godotengine/godot#95651]
### Tested versions

- Reproducible in : 4.3.stable (newest version on Steam)

### System information

Windows 11- Godot v4.3.stable - Vulkan API 1.3.224 - Forward+ - NVIDIA GeForce RTX 3060 Laptop GPU

### Issue description

Ever since I upgraded my project to **4.3** I was feeling like something was wrong when using **AnimationPlayer**. While inserting key, I noticed that it wasn't exactly placed at points like 0.1 and 0.5. The fact that it is **0.0333** is very disturbing for me. If the problem is caused by me, it can be changed in the editor or if this is the way it is used anymore, close this title directly. In my personal opinion, the old value of **0.1** was much more useful. The situation is the same for all newly added nodes, including existing nodes. Just created new project and the situation is still same.

![Screenshot 2024-08-16 195448](https://github.com/user-attachments/assets/2610842e-8909-4ed8-8ca4-dedefce479fc)

### Steps to reproduce

Add AnimationPlayer node to your scene and then check the default snap value 

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16639650/new-game-project.zip)

**Comment by AThousandShips** [comment]
This value is more generally useful, 30 FPS is far more common than 10 FPS I'd say

Also this was changed intentionally in:
* https://github.com/godotengine/godot/pull/90894/files

So changing it back *again* makes little sense IMO

**Comment by Tugay72** [comment]
Thank you for the fast respond! If this is the new usage, there is no problem, I can manually reset it to the old value when I need it.
