### ISSUE TITLE
Duplicate Function should include dependencies with corrected pathways

### ISSUE THREAD

**Issue by DatHacksGaming** [godotengine/godot#95674]
### Tested versions
If I take FolderA and duplicate it all to FolderA-1 then the script paths on any nodes inside that duplicate should be FolderA-1/scriptname.gd ... but it's still FolderA/scriptname.gd. This should be fixed, any scenes/nodes/scripts etc within the duplicated folder should have the paths updated to match the duplicated folder not the original.

### System information
Windows 10, Godot 4.2.2.stable

**Comment by AThousandShips** [comment]
Thank you for your report!

Please do not remove parts of the issue template

Please add more information and an MRP to showcase the behavior

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened, in that case please restore the template
