### ISSUE TITLE
Severe input lag in editor with enabled V-sync. 

### ISSUE THREAD

**Issue by orriginalo** [godotengine/godot#95694]
### Tested versions

- Reproducible in v4.3.dev4.official [df78c0636] and later.
- Not reproducible in v4.3.dev1.official [9d1cbab1c], v4.3.dev2.official [352434668], v4.3.dev3.official [36e943b6b].

### System information

Godot v4.3.stable - Windows 10.0.22631 - d3d12 (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 32.0.15.6081) - Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 Threads)

### Issue description

Reproducible on both d3d12 (Forward+) and Vulkan (Forward+) and is also reproducilble on Vulkan (Mobile) and d3d12 (Mobile), but not on Compitability renderer.
In Godot 4.2, when V-sync is enabled, there is an input lag in the editor, and when V-sync is disabled, the input lag disappears. But in Godot 4.3, when V-sync is disabled, the input lag does not disappear.

### Steps to reproduce

1. Create a new project in godot v4.3.dev4.official [df78c0636] or later.
2. Hold RMB or MMB in "viewwindow space" and move mouse.
3. You will see input lag.
4. Disable V-sync in editor settings and reload project.
5. Try steps 1-3 again, and input lag does not disappear.

### Minimal reproduction project (MRP)

Empty project.

**Comment by orriginalo** [comment]
I just noticed that this input lag is prominent not only in the 2/3d preview but also in the whole editor, for example when dragging files around in the filesystem.

**Comment by Calinou** [comment]
> But in Godot 4.3, when V-sync is disabled, the input lag does not disappear.

In 4.3, V-Sync in the editor is governed by an editor setting, not the project setting.

**Comment by orriginalo** [comment]
Turning off V-Sync in the editor fixed the input lag. Thank you.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/79290 and https://github.com/godotengine/godot/issues/90871.
