### ISSUE TITLE
Locked frame and frame_coords on Sprite2D node after closing and opening the project

### ISSUE THREAD

**Issue by Ale-uwu** [godotengine/godot#95695]
### Tested versions

- Happened on Godot 4.3 stable after updating, worked on same project 4.2.2 stable and never happened. After it happenned, tried reproducing on godot 4.2.2 stable but couldn't reproduce it

### System information

Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org Vulkan 1.3.278 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 3050

### Issue description

Im using to build a scene of a character a CharacterBody2D with the following nodes: Sprite2D, CollisionShape2D, AnimationPlayer and AnimationTree. 

What I wanted to do was adding new animations to this scene. To do it, I select the spritesheet of the character as the texture in the Sprite2D node, set the Hframes property to 28 (number of sprites in the spritesheet). Then at the moment of creating a new animation in the AnimationPlayer Node, when I want to add a keyframe to the actual frame_coords.x, It doesnt add the keyframe and doesnt changes. 

Back to the sprite2D Node (without the animation timeline showing) I try to change the actual frame or frame_coords but it doesnt changes although I can freely change the texture, hframes or vframes

The only solution i found was deleting the Sprite2D Node and adding a new one

Important: It only happens the first time I open godot after turning on the PC, if I do what I said in the previous line (deleting the Node and adding a new One) it will work until I restart my PC, but if i dont do that, and keep opening and closing godot it wont work. 

### Steps to reproduce

Restart your PC
Have a godot project with a saved scene
Open the scene set the texture to the Sprite2D node, set the hframes, and try changing the frame or frame_coords

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/16645035/mrp.zip)

**Comment by TokageItLab** [comment]
I remember fixing the property of the frame coord type from float to int, so old tracks may not be compatible with the key type.

**Comment by TokageItLab** [comment]
I have looked at MRP but I can't figure out what the problem. Can you send a video of what is the problem and what is the behavior you want?

**Comment by Ale-uwu** [comment]
Hey I recorded this video, after turning on the pc:

https://github.com/user-attachments/assets/96e380f6-c091-43c6-b5dc-03720a38c76b

(I sped up the video so that the file size is less than 10mb, I hope it is not difficult to watch the video)

The behavior I want is for the editor to allow me to go between the frames of the spritesheet to be able to do the animations, but there is no way. And I say it as before, this has not happened to me in godot 4.2.2, only when updating and moving the project from the previous version to 4.3

**Comment by TokageItLab** [comment]
It looks like just the AnimationTree is enabled and update your editing object. In 4.3, AnimationTree will do continuous updates by default due to the implementation of CallbackModeDiscrete, so it will solve by setting it to "Recessive" or "Dominant". Or simply disable AnimationTree when editing.

![image](https://github.com/user-attachments/assets/e8e5a6e3-d8cc-4bec-8049-8cd05d854d2a)
