### ISSUE TITLE
Editor Settings take a long time to close when using the `X` button on the window

### ISSUE THREAD

**Issue by AeioMuch** [godotengine/godot#95696]
### Tested versions

- Reproduible in v4.4.dev.custom_build [01b87a9a9] and subsequent
- Not reproducible in v4.4.dev.custom_build [a7200cedb] and prior

### System information

Godot v4.4.dev (1bd740d18) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6081) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

Closing the Editor Settings window by pressing the `X` button takes ~7 seconds everytime. The editor can also freeze for a bit after the Editor Settings window is not visible anymore. 

I tried to do a checkout of the commit just before a7200cedb and prior, and the slowdown disappeared : closing the window by pressing the `X` button is instant. Then checkout 01b87a9a9 or everything after and the slowdown is back.

The slowdown is fixed for the session if you make a change in the Editor Settings then press the `X` button.
The slowdown is fixed for the session just by pressing the `Close` button instead, without the need of doing changes (tho it will still freeze once after the window disappear); until you restart Godot.

### Steps to reproduce

1. Use Godot v4.4.dev (01b87a9a9) or subsequent
2. Make sure `editor_settings-4.4.tres` is removed/renamed.
3. Start Godot and open the Editor Settings.
4. Click the `X` button to close the window
5. Witness it takes a while

### Minimal reproduction project (MRP)

N/A (a new empty project will do)

**Comment by AThousandShips** [comment]
CC @KoBeWi

**Comment by KoBeWi** [comment]
I tried printing `changed_settings` and for some reason after #95171 literally every setting is marked as changed.
