### ISSUE TITLE
Set value inside a sub scene in inspector isn't work

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#957]
I put instance a node from scene file to the scene and set Show Children.
List of children appear I can change value in inspector but when I play the scene value isn't change.

**Comment by hitjim** [comment]
Am I correct in believing that this Issue already represents the problem I'm hitting when trying to modify the "bounce" or changing scale etc on an instance of the ball in the instancing tutorial? https://github.com/okamstudio/godot/wiki/tutorial_instancing

**Comment by akien-mga** [comment]
Subscene editing has been implemented for 2.0, so it should now work.
