### ISSUE TITLE
Connecting signal does not generate their method in C# script

### ISSUE THREAD

**Issue by tvardero** [godotengine/godot#95703]
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 11 Pro

### Issue description

External editor: Jetbrains Rider.
.Net installed:
```
> dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

> dotnet --list-sdks
8.0.301 [C:\Program Files\dotnet\sdk]
```

Connecting node signal to a non-yet-existing method does not create the method in C# scene script.

Might be related: https://github.com/godotengine/godot/issues/18721

### Steps to reproduce

1. Create a scene of any node type;
2. Add C# script;
3. Add any child node that can produce a signal (for example Area2D);
4. Save .tscn and .cs files;
5. Select any signal and try to connect it.

Expected: method is created in C# class, signal is connected in .tscn file to that method.
Actual: method is _not_ generated, however signal is now connected to non-existing method in .tscn file.

### Minimal reproduction project (MRP)

[Connecting signal issue.zip](https://github.com/user-attachments/files/16645672/Connecting.signal.issue.zip)

**Comment by tvardero** [comment]
https://github.com/user-attachments/assets/95061117-4a01-4a32-8583-f954f1c9da16

**Comment by tvardero** [comment]
Ah, found this one: https://github.com/godotengine/godot/pull/87952

However, need to note that **warning was not displayed**, neither in my project, nor in MRP project.

**Comment by raulsntos** [comment]
That warning was added in 4.3, but you are using 4.2.2 and the PR hasn't been cherry-picked yet.

**Comment by AThousandShips** [comment]
Thank you for reporting, closing and consolidating in:
* https://github.com/godotengine/godot/issues/18721

Should be cherry picked to a future 4.2.x version, or you can use 4.3
