### ISSUE TITLE
_enter_tree() of AddOn Autoloads is being called unexpectadely.

### ISSUE THREAD

**Issue by betalars** [godotengine/godot#95702]
### Tested versions

v4.2.2.stable.nixpkgs [15073afe3]

### System information

 Operating System: NixOS 24.11 KDE Plasma Version: 6.1.3 KDE Frameworks Version: 6.4.0 Qt Version: 6.7.2 Kernel Version: 6.10.2 (64-bit) Graphics Platform: X11 Processors: 12 × AMD Ryzen 5 2600X Six-Core Processor Memory: 31.3 GiB of RAM Graphics Processor: AMD Radeon RX 6800 Manufacturer: Micro-Star International Co., Ltd. Product Name: MS-7A33 System Version: 2.0

### Issue description

`_enter_tree()` of autoloads created in a plugin seems to be called out of expected order.

I stumbled across this as I tried to load a setting while initializing an auto-load.

I need to initialize Project Settings at `_enter_tree()` in the plugin, as settings on their default values will return null in the editor when only initialized in` _activate_plugin()`.

So I initialize the Project settings before I load the autoload, however when _enter_tree() is first called, the settings are not initialized.

May be related to #48557

### Steps to reproduce

1. Download Minimum Reproduction Project
2. Run the Project
3. The Assertion Fails in awesome Autoload
4. set breakpoint in plugin script to double check settings being initialized
5. breakpoint isn't reached

### Minimal reproduction project (MRP)

[unexpected_enter_tree.zip](https://github.com/user-attachments/files/16645586/unexpected_enter_tree.zip)

**Comment by betalars** [comment]
Okay, I genuinely feel gas-lit right now:

```
const use_custom_font_path:String = "accessibility/closed_captions/use_custom_font"

func _enter_tree():
	_initialise_project_settings()
	ProjectSettings.set_setting("settings_initialised", true)
	add_autoload_singleton("CaptionTheme", "res://addons/closed_captions/caption_theme.gd")

func _initialise_project_settings():
	print("initialising!") # not reached
	
	if !ProjectSettings.has_setting(use_custom_font_path):
		ProjectSettings.set_setting(use_custom_font_path, "font name")
		ProjectSettings.add_property_info({
			"name": use_custom_font_path,
			"type": TYPE_STRING,
			"hint": PROPERTY_HINT_NONE,
		})
		ProjectSettings.set_initial_value(use_custom_font_path, "font name")
		print("initialised_me") #not reached

```
```
func _on_project_settings_update(): #called in _enter_tree()
	if ProjectSettings.has_setting("settings_initialised"):
		var font_name:StringName = ProjectSettings.get_setting(CaptionPlugin.use_custom_font_path) #Fails, because  setting returns null.
```

Why is this happening?

Full context: https://github.com/betalars/godot-closed-captions

**Comment by betalars** [comment]
I found a Workaround btw:
```
func _enter_tree():
	_initialise_project_settings()
	add_autoload_singleton("CaptionTheme", "res://addons/closed_captions/caption_theme.gd")
	CaptionTheme.setting_initialized = true
```

```
var setting_initialized:bool = false:
	set(ini):
		setting_initialized = ini
		if ini:
			_on_project_settings_update()

func _on_project_settings_update():
	if setting_initialized:
		var font_name:StringName = ProjectSettings.get_setting(CaptionPlugin.use_custom_font_path)
```

**Comment by betalars** [comment]
Ah, I think I understand the issue:
Because this is an Editor Plugin, the Autoloads are also loaded in the Project Settings:
![image](https://github.com/user-attachments/assets/f910a3c0-fb9d-432d-9e0d-5320001539a3)

So they get loaded twice, once by the editor and once by the plugin.

You can prevent this with code by only loading the Autoloads when `!OS.has_feature("Editor")` but that means the Autoload Names are not known to the editor.

I a possible workaround to this is to check if an autoload script has a plugin in it's directory or parent directory and then postpone its loading until after the plugin has been initialized, also checking if it has at this point already loaded.

**Comment by KoBeWi** [comment]
Adding autoload will add it permanently, will be stored in project settings as if added from the project settings dialog, until you remove it. Instead of adding the autoload later, you can delay its initialization, e.g. with `await`.

**Comment by betalars** [comment]
> Instead of adding the autoload later, you can delay its initialization, e.g. with `await`.

Okay, thanks for that different workaround.

Thinking about this made me realize the intended way of adding autoloads is probably this:

```
func _enable_plugin():
	_initialise_project_settings()
	add_autoload_singleton("CaptionTheme", "res://addons/closed_captions/caption_theme.gd")
	
func _enter_tree():
	_initialise_project_settings()
	CaptionTheme.load_settings()
	add_custom_type("Caption", "Resource", preload("res://addons/closed_captions/caption.gd"), preload("icons/Caption.svg"))
```

Okay, this makes using Project settings in Autoloads a bit annoying, but I kind of get this being intended behaviour.

When I am done with my AddOn I will probably take a close look at the documentation and see how many of my frustrations fall into the category rtfm and how many fall into needs better docs ...
