### ISSUE TITLE
Creating a Shader Material in a Spatial Material's NextPass Crashes the Editor

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#9570]
**Operating system or device - Godot version:**
Manjaro 64bit godot 3.0

**Issue description:**

When I make a new Spatial Material then go to NextPass and try to make a Shader Material the editor crashes. 
**NOTE:**

 This only happens with a Shader Material being made In the NextPass of a Spatial Material. Making a Shader Material in the NextPass of any other Material type still works fine.

**Steps to reproduce:**
1) Make a Spatial Material
2) Find Next Pass
3) Make a new Shader Material

Also I am using the latest material tester demo

**Comment by mcanders** [comment]
I ran into this too.  Its segfaulting because m->shader is null in RasterizerSceneGLES3::_add_geometry_with_material.
