### ISSUE TITLE
Audio bus update error when exporting as web Godot 4.3

### ISSUE THREAD

**Issue by Baptiste81** [godotengine/godot#95713]
### Tested versions

Reproductible in Godot v4.3-stable, 4.3.rc3
Previous version not tested.

### System information

Windows 10 + Windows 11 with Godot v4.3.stable + 4.3rc3

### Issue description

"Index out of bound" or "invalid bus index "-1"" (don't know how to get one or the other) error message when playing an export build when it works perfectly in, at least, windows export and in editor.
![screen1](https://github.com/user-attachments/assets/4c67a3c9-f9c8-41ce-9b15-056c71bd1224)
![screen2](https://github.com/user-attachments/assets/07030bfb-a4e8-4f30-bcc8-d146efaff069)

### Steps to reproduce

- Create a project with a Control root node
- Add a button
- Add an AudioStreamPlayer
- Code something to play the sound when clicking the button (for test purpose)
- In Audio panel at the bottom, add a bus (ie "General"), then another (ie "Sounds). 
- Plug the AudioStreamPlayer to the "Sound" audio bus. 
- Plug the "Sound" audio bus into "General" bus and "General" into "Master"
- Delete the "General" bus, now "Sound" bus will be plug into "Master" bus.
- Launch the scene, it works when you click the button, the sound is played.
- Export the project as web. Doesn't work anymore.

Minimal project has to be used as : 
Launch the project : it works
From "export" folder use either the files or the zip to put in on webserver and try launching the game it doesn't work.

I noticed that in default_bus_layout.tres file the "bus/1/send" property is not well filled and is always set to "General" where in Godot GUI is the to "Master" (cf screenshot). Even if I click on "Master" in bus send then "Save as"
![Capture d’écran 2024-08-17 221847](https://github.com/user-attachments/assets/37b91131-ea41-4639-98bf-10ad8b5a956e)

### Minimal reproduction project (MRP)

[AudioBusBug.zip](https://github.com/user-attachments/files/16646422/AudioBusBug.zip)

**Comment by Calinou** [comment]
cc @adamscott

**Comment by Baptiste81** [comment]
> cc @adamscott

Trying to understand how the code is organized. Is it a problem of web export as your label seems to show ? Or an update of the layout file ? Because the default_bus_layout.tres is not updated when I delete a bus used by another. Is the tres only used by web export and this could explains why in Editor and Windows export it's working ?

At first time I though about calling [EditorAudioBuses::_server_save()](https://github.com/godotengine/godot/blob/a1acd38c35781181cde726b039eb8a9a0b6aa79f/editor/editor_audio_buses.cpp#L1216 ) in [EditorAudioBuses::_rebuild_buses()](https://github.com/godotengine/godot/blob/a1acd38c35781181cde726b039eb8a9a0b6aa79f/editor/editor_audio_buses.cpp#L1038)

But yeah, maybe it's in [JS remove_sample_bus](https://github.com/godotengine/godot/blob/a1acd38c35781181cde726b039eb8a9a0b6aa79f/platform/web/js/libs/library_godot_audio.js#L1425) and needs to check if any buses has the deleted one set as a send.. ?

**Comment by TaofeekS** [comment]
Hi,
I had the same issue.
But I was able to solve it, by clearing my existing web preset in the export window and creating a new web preset

**Comment by TaofeekS** [comment]
> Hi, I had the same issue. But I was able to solve it, by clearing my existing web preset in the export window and creating a new web preset

This is not right 

you need to enable Debug when you export it works

**Comment by Dar1on05** [comment]
> you need to enable Debug when you export it works

how do i do that?

**Comment by 8Rube** [comment]
this was my problem too, for some reason having other audio bus than Master break the web build, I erase the extra 2 and it works, but I lost the audio buses (later I fix it, not sure how but maybe happen when I put an export debug present and then erased)
