### ISSUE TITLE
Parse Error when defining function called "set_zoom" on Camera2D

### ISSUE THREAD

**Issue by alanmelloni97** [godotengine/godot#95726]
### Tested versions

- Reproducible in 4.3

### System information

Windows 11

### Issue description

when defining a function called "set_zoom" on a Camera2D the following errors appear:

 _res://aaaa.gd:4 - Parse Error: The function signature doesn't match the parent. Parent signature is "set_zoom(Vector2) -> void".
  res://aaaa.gd:4 - Parse Error: The method "set_zoom()" overrides a method from native class "Camera2D". This won't be called by the engine and may not work as expected. (Warning treated as error.)_
  
  despite class Camera2D having no such function. This function existed on Camera2D only on Godot 2.1. This doesn't happen on Camera3D.

### Steps to reproduce

Add a script to a Camera2d with this code:

```gdscript
extends Camera2D

func set_zoom():
	pass
```

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
`zoom` is a property of Camera2D and as a property it has two accessors which are `set_zoom` and `get_zoom`:

![изображение](https://github.com/user-attachments/assets/5023408b-6f25-4fd3-b117-ad298cdab642)

**Comment by alanmelloni97** [comment]
sorry, my bad
