### ISSUE TITLE
Android Editor: GLB Model Texture Missing.

### ISSUE THREAD

**Issue by UnderGamer05** [godotengine/godot#95731]
### Tested versions

Godot 4.3.stable, Android Editor,

### System information

Android 11 - Computability Rederer, Godot 4.3

### Issue description

In Godot Android Editor When Trying to Import a glb model the texture of model is missing. But when I tried Godot 4.2.2 everything is normal.

![Screenshot_20240818-104126](https://github.com/user-attachments/assets/470629a0-09d1-4a51-8d9b-249dd7f900cf)

### Steps to reproduce

Just downloaded a glb model from online and imported in godot

**Comment by aaronfranke** [comment]
What model? Does this occur on desktop or web? Please provide a minimal reproduction project.
