### ISSUE TITLE
Ghost-Effect Material: Simply using Rim and Refraction to get an eerie invisible-glow effect. Also, suggestions for enhancing the Rim options.

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#9573]
**Operating system or device - Godot version:**

Godot 3.0 Pre-Alpha Build, Windows 10

Lately I've been messing around with the Spatial material to try to create a invisible/phantom/glowing membrane like material and was able to make this:

![godot_ghost_effect](https://user-images.githubusercontent.com/5027750/27992575-b6509826-644c-11e7-8675-acbf477bc8c9.png)

Utilizing Rim to get the glowing edges and Refraction for the invisible distortion, this was the most impressive (or probably a not-bad, first time attempt) in recreating the effect. For Rim it turns out that despite the "Tint" adjustment goes up to 1 in maximum, there is no limit to how low the minimum is required. For example: adjust Tint to -100 and you have a blended glowing edge on your object!

Refraction is simple enough to utilize to get the invisble effect.

The idea and main point in this is that the Rim has the potential to be enhanced further so then it can be utilized in maybe creative ways. For example, ghosts or creepy, invisible membrane like object (Sorta like how Metroids have a near invisisble but glowing membrane)

What extras Rim should/could have:

- Make the Rim colorable, so then it does not use the same white glow,
- An adjustment bar or boolean for the rim glow to be "emittable", (Turns out you need a light source or directional light to get the glow, would be awesome if the rim was made emittable without a light source. Better if using an adjustment bar for animation or programming purposes.)
- Make an adjustment bar to adjust the width or visibility of the glowing rim so then typing -100 into the "tint" isn't used.
- And allow a boolean option whether different objects with rims appear behind the other invisble/rim objects (As you can see in the example image, the rims does not overlap or merge completely within another object.)

**Steps to reproduce:**

Add a new mesh to the scene, make a new material:

-Add a directional light to get the Rim glow.
-Adjust the Albedo's Alpha adjustment bar so then refraction can work,
-Set the Metallic to 0 and the Metallic Specular to 0 to avoid glassy reflections in refraction,
-Set Roughness to 0
-Enable Rim, set rim to "1", and type in the tint adjustment: "-100", trust me it works despite breaking limitations. (P.S. Unless there is an option to adjust the with of the rim, don't patch it.)
-Enable Refraction, set scale to 0.07. This allows distortion in invisibility
-(OPTIONAL): You can try to use Normalmapping to add details.

I can already imagine a lot of ghosts/spirits/souls flying around in a game project involving jumpscares, ghost hunting, or etc.

**Comment by gamergamesz** [comment]
and it would be great if clearcoat could use refraction map as clearcoat also make rough surface shine

**Comment by reduz** [comment]
One of the interesting features of the new SpatialMaterial is that it can (or should be, option needs to be done) be converted to shader code with a single click. This way you can easily add features to a material, even if you are not a shader expert. Could leave this issue open as a reminder that this feature needs to be done..

**Comment by Corruptinator** [comment]
Nice! A quick conversion to shading code sounds awesome!

**Comment by reduz** [comment]
yeah leave this open so i don't forget

**Comment by vnen** [comment]
Conversion to shader is already possible. Is this issue still relevant?

**Comment by akien-mga** [comment]
I assume that @reduz meant that he doesn't want to implement proposed changes in the main shader, but that those who need it should be able to do it with the conversion to shader feature. Since it's implement, I'll assume this issue can be closed. Feel free to comment if this doesn't seem sufficient.
