### ISSUE TITLE
.glb and .fbx file names can't be found in directory (HTML5 export)

### ISSUE THREAD

**Issue by augustvc** [godotengine/godot#95741]
### Tested versions

- Reproducible in Godot 3.5.3 stable (mono)

### System information

Windows 10 - Google Chrome

### Issue description

I expect any resource file that is marked to be exported to be visible through usage of the Directory class. However, this doesn't seem to work for .glb and .fbx files (both file types for 3D models).

This is unexpected, because it looks like you're able to include them in the export, through some settings. The .glb.import files and .fbx.import files are found, but not the files themselves.

### Steps to reproduce

- Add any .glb or .fbx file to the project in the res:// folder
- Add some code to a node's "Ready" function that prints out all files within the res:// folder:
```csharp
var dir = new Directory();
dir.Open("res://");
dir.ListDirBegin();

string fileName = dir.GetNext();
while (fileName != "")
{
    GD.Print("Found " + fileName);
    fileName = dir.GetNext();
}
```
- Create an HTML5 export preset, and include the file from your res:// folder (for example, by adding a checkmark in Export selected resources)
- Build and run the HTML5 export using Godot's built-in web debugging server
- Look at the console and see the files that are printed

### Minimal reproduction project (MRP)

[GLBExportTest.zip](https://github.com/user-attachments/files/16647801/GLBExportTest.zip)

**Comment by Calinou** [comment]
These files are imported by Godot, so the source files are not included in your exported project anymore.

To avoid this, change the files' import type to **Keep (Export)** in the Import dock.
