### ISSUE TITLE
Unhandled mouse events while captured cause endless objects to be created

### ISSUE THREAD

**Issue by quinnyo** [godotengine/godot#9575]
**Operating system or device - Godot version:**
Arch Linux, LXQt (OpenBox)
Godot master 0bf88e4 amd_64 release_debug

**Issue description:**
While the mouse is captured (only `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)`), Performance monitors `OBJECT_COUNT` and `MEMORY_STATIC` increase (forever?) with any mouse input event that isn't handled with `set_input_as_handled()`.

The object count / memory returns to normal as soon as the mouse mode is changed.

Now I should actually be consuming the events in most cases, but the behaviour when you don't seems undesirable regardless.

**Steps to reproduce:**
I wrote a quick script to test this. Scene is just a Node with a Label child.
```
extends Node

func _input(event):
	if event is InputEventMouseMotion:
		#get_tree().set_input_as_handled()
		pass
	elif event is InputEventMouseButton:
		#get_tree().set_input_as_handled()
		pass
	elif event is InputEventKey:
		if event.scancode == KEY_ESCAPE:
			Input.set_mouse_mode(0)
		elif event.scancode == KEY_SPACE:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	
	$Label.set_text("objects: %d\nstatic mem: %d" % [Performance.get_monitor(Performance.OBJECT_COUNT), Performance.get_monitor(Performance.MEMORY_STATIC)])
```

**Comment by vnen** [comment]
It does the same for me on Windows 10.

**Comment by RandomShaper** [comment]
I'll check this.

**Comment by RandomShaper** [comment]
PR submitted for this.
