### ISSUE TITLE
Sliders/scroll bars can't be dragged in native unfocusable windows

### ISSUE THREAD

**Issue by gb2dev** [godotengine/godot#95754]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Windows 10 - v4.3.stable.official - Compatibility

### Issue description

When you create a Window node with the "Unfocusable" and "Force Native" flags and put a Slider or ScrollContainer with ScrollBar in it, you can click the Slider/ScrollBar once to move it, but you can't drag it around.

### Steps to reproduce

- Create a new Window node
- Check the Flags "Unfocusable" and "Force Native"
- Put a Slider node in it
- Run the project and try to drag the slider

### Minimal reproduction project (MRP)

[scrollbarunfocusable.zip](https://github.com/user-attachments/files/16648942/scrollbarunfocusable.zip)

**Comment by tetrapod00** [comment]
Confirmed on Windows 10. Seem like there are multiple issues with focus on Windows since 4.3. Possibly related to https://github.com/godotengine/godot/issues/95639 or https://github.com/godotengine/godot/issues/95577.
