### ISSUE TITLE
Screenshot in readme shows Godot 3.5

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot#95761]
### Tested versions

4.3

### System information

Screenshot taken on Windows 10

### Issue description

As pointed out in https://github.com/godotengine/godot-docs/issues/9765, the screenshot on the main repo's readme shows version 3.5. This isn't a huge deal but it's nice to fix, so I went ahead and remade the screenshot in Godot 4.3.

New screenshot, PNG, 2.64 MB:
![editor_tps_demo_screenshot_43_1920_1080](https://github.com/user-attachments/assets/a1d710a6-117f-48de-9a9f-4f9d0e09f2c7)

New screenshot, JPEG, 100% quality exported from Krita, 1.28 MB:
![editor_tps_demo_screenshot_43_1920_1080](https://github.com/user-attachments/assets/51f9aafd-b91d-4f37-83b9-bd1ce1558417)

Old screenshot:
![editor_tps_demo_1920x1080](https://github.com/user-attachments/assets/9dc74e69-8c0c-496e-907c-503d26938a0d)

I imported the master (4.x) branch of the TPS demo and moved some things around to match the old screenshot. I also turned on SSAO, SSIL, SDFGI, Volumetric Fog, and Glow on mostly default settings. Unfortunately, the particles on the core don't look like 3.5beta anymore. I tried turning up the max number of particles on each emitter but it didn't help.

I would make the PR myself, except I don't know where images are meant to be stored. I can also make more tweaks to the screenshot if there are easy improvements.

### Steps to reproduce

Look at https://github.com/godotengine/godot/blob/master/README.md. Observe that the screenshot shows version 3.5.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
> I would make the PR myself, except I don't know where images are meant to be stored

This editor screenshot is located in https://github.com/godotengine/godot-design/tree/master/screenshots

However, I'd like to have a 4K version available (with the editor scale set to 200%). If you don't have a 4K monitor, you can create this screenshot by using DSR/VSR on the whole desktop your graphics card's control panel

**Comment by tetrapod00** [comment]
Ah, thanks! I missed the godot-design folder, I thought it was a link to a godot-design repo for some reason.

So the formats we need are a 4K PNG with high quality, and a 1080 JPG that's reasonably optimized without reducing quality?

Are there any other visual changes you'd make to the environment settings or anything else?
