### ISSUE TITLE
OmniLight3D volumetric fog shadows shows in front of the object, and makes a rounded shape in the occluded area.

### ISSUE THREAD

**Issue by dalzott0** [godotengine/godot#95785]
### Tested versions

Reproducible in 4.3.dev6, 4.3.beta1, 4.3.beta2, 4.3.beta3, 4.3.rc1, 4.3.rc2, 4.3.rc3 and the 4.3.stable.
Also tested on Vulkan and DirectX3D backends.

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 32.0.11029.1008) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

The volumetric fog shadows of a OmniLight3D show in front the mesh, starting in the center of the light. And behind the mesh, the shadow makes a rounded shape close to the end of the light radius.

#### With a Volume Size of 512:
![image](https://github.com/user-attachments/assets/5a31f4c1-2339-438e-b4e9-d21ff24a31bb)
![image](https://github.com/user-attachments/assets/50fcaedc-aa4b-4d6a-b734-ad9d289bc2f0)

#### With a Volume Size of 128:
![image](https://github.com/user-attachments/assets/8a9ba08f-1c30-4715-ba7c-9b3d238ea698)

#### With a Volume Size of 64 (almost not visible):
![image](https://github.com/user-attachments/assets/e9024306-448f-4b8f-85dc-c4a05135052d)

### Steps to reproduce

Add a OmniLight3D node to a scene with Volumetric Fog activated in a WorldEnviroment node.

The problem can be more visible by: 
- Increasing the Volume Size in the Settings (in the MRP is set to 128), in the default value of 64 is visible too, barely. Higher values make more visible;
- Increasing the Volumetric Fog Energy in the OmniLight3D;
- Using black ambient and sky color.

### Minimal reproduction project (MRP)

[light-test.zip](https://github.com/user-attachments/files/16661226/light-test.zip)

**Comment by dalzott0** [comment]
Maybe the very high Volume Size is making the crashing, I tested in a GTX 1050TI and the project almost not opened either. I'm going to reduce the value in the MRP to make it more approachable.

**Comment by Calinou** [comment]
> Every time I try to open the MRP my computer crashes.

I'm surprised you get crashes when volume size is raised higher than the default on a RX 6600. Back when I had a GTX 1080, I could easily use a volume size of 256 or even 384 without any troubles (although it was slow).
