### ISSUE TITLE
NavigationAgent2D emits velocity_computed when disabled

### ISSUE THREAD

**Issue by Houtamelo** [godotengine/godot#95796]
### Tested versions

- Reproducible in v4.3.beta3.official [82cedc83c]

### System information

Godot v4.3.beta3 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1080 Ti (NVIDIA; 32.0.15.5599) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

NavigationAgent2D nodes emits the `velocity_computed` signal every frame, regardless of its `process`/`physics_process` configurations. 

The MRP bellow shows this with the agent's `process_mode` set to `DISABLED`.

This can be worked around by setting `avoidance_enabled = false`.

### Steps to reproduce

- Open MRP project
- Run scene
- See that velocity computed is printed every frame

### Minimal reproduction project (MRP)

[navigation_agent_2d_bug.zip](https://github.com/user-attachments/files/16659529/navigation_agent_2d_bug.zip)

**Comment by AThousandShips** [comment]
I think this is part of a larger question and possible confusion over what `process_mode` *actually* does, and I think this is a case of that not being documented clearly enough, `process_mode` isn't a complete "turn everything off" thing but is primarily about the direct processing methods

**Comment by smix8** [comment]
You need to change the processing on the parent node, not on the NavigationAgent node.

**Comment by smix8** [comment]
Closing as agents react to the SceneTree pause and there are also the mentioned dedicated functions to actually pause an agent.

The node `process_mode` is for script processing callbacks on `_process()` and `_physics_process()` on nodes.
