### ISSUE TITLE
`GPUParticles` not rendered in Web Export or Windows ANGLE with `AMD Radeon RX Vega 6-7` GPU

### ISSUE THREAD

**Issue by Maran23** [godotengine/godot#95797]
### Tested versions

- Reproducable in Godot 4.3.dev6 -> Godot 4.3

### System information

Windows 10, AMD Ryzen 5 4500U (GPU: AMD Radeon RX Vega 6 (Ryzen 4000/5000))

### Issue description

**EDIT:**
**Solution 1**
-
I found a settings in Chrome that actually fixes the `GPUParticles`: (chrome://flags/)
![image](https://github.com/user-attachments/assets/de22bab1-a01a-4f3d-bffb-3768c0d29915)
This is set to `Default`,- if it is set to `OpenGL`, everything works. If it is set to `D3D11` or `D3D11on12`, it doesn't for the below mentioned AMD hardware combinations.

As also written in the description, `D3D11` seems to be used as the default for most Windows machines, but it will break `GPUParticles` for some hardware combinations.

**Solution 2**
-
Turning off `graphic acceleration` in Google Chrome fixes the issue as well (although `GPUParticles` will lag now)
![image](https://github.com/user-attachments/assets/89c827b5-004c-4d1f-b983-cf0788b63c00)

---

- After testing my game on different Hardware, there seems to be a problem with AMD GPUs when rendering `GPUParticles` on a Web Build.
- The Browser doesn't matter, it doesn't work with every Browser (Edge, Chrome, Firefox)
- There are no errors in the console
- There is still the typical particle render lag the first time it should be shown, but nothing is rendered

`GPUParticles` are not rendered in a Web Build for the following Hardware:

```
CPU: AMD Ryzen 5 4500U
Integrated GPU: AMD Radeon RX Vega 6
```

```
CPU: AMD Ryzen 5 5600U
Integrated GPU: AMD Radeon RX Vega 7
```

```
CPU: AMD Ryzen 7 5825U
Integrated GPU: AMD Radeon RX Vega 8 
```

This combination however works:

```
CPU: AMD Ryzen 7 5700U
Integrated GPU: AMD Radeon RX Vega 8
```

The native binary works and renders the `GPUParticles` (which uses Forward+ (Vulkan)).

It seems that every other Hardware works as of now.
Tested with Intel (iGPU) and Nvidia GPU.

If there is anything I can try, let me know.

### Steps to reproduce

- Open the project, particles should not visible in the editor, also when running

OR

- Run in your Browser: https://maran23.itch.io/space-heist - Start a level, compare with the screenshots

### Minimal reproduction project (MRP)

[ParticleBug.zip](https://github.com/user-attachments/files/16789243/ParticleBug.zip)
OR
Open and run in your Browser: https://maran23.itch.io/space-heist

**Comment by Maran23** [comment]
> Are all these GPUs on Windows machines? Do they all run the latest AMD drivers?

Yes. 
I just updated the issue, I found a solution for the problem. It looks like it has something to do with ANGLE graphics backend.

**Comment by clayjohn** [comment]
Could you test those same devices but using the ANGLE backend on desktop? We support running ANGLE natively by setting `rendering/gl_compatibility/driver.windows` to `opengl3_angle`

**Comment by Maran23** [comment]
> Could you test those same devices but using the ANGLE backend on desktop? We support running ANGLE natively by setting `rendering/gl_compatibility/driver.windows` to `opengl3_angle`

Just tested and it is indeed also broken on 'native' Windows when switch to `opengl3_angle`.
![image](https://github.com/user-attachments/assets/3cc8a8ea-43da-4ccd-9fd5-fc1edc7c26e9)

**Comment by ollie-d** [comment]
I just wanted to add that CPUparticles are also broken for me on web exports. Both CPU and GPU particles render fine on web export in 4.2.2, but neither render at all on 4.3. Doesn't work on Firefox or Chrome.

Processor: i7-12700K
GPU: AMD RX 6900 XT

**Comment by Maran23** [comment]
I can agree that it works on Godot 4.2.2 with the complete same setup. So it must be some kind of regression in Godot in combination with ANGLE and AMD it looks like.

**Comment by akien-mga** [comment]
Would you be able to bisect between 4.3.dev5 (89f70e98d209563abb4dbc1f8cd5d76c81eb7940) and 4.3.dev6 (64520fe6741d8ec3c55e0c9618d3fadcda949f63)?

**Comment by Maran23** [comment]
> Would you be able to bisect between 4.3.dev5 ([89f70e9](https://github.com/godotengine/godot/commit/89f70e98d209563abb4dbc1f8cd5d76c81eb7940)) and 4.3.dev6 ([64520fe](https://github.com/godotengine/godot/commit/64520fe6741d8ec3c55e0c9618d3fadcda949f63))?

Yes, we are already bisecting now! :)
On a side note, the axis lines also disappeared in that version. So it's not just Particles it looks like. (Show Origin is turned on, worked in Godot 4.2.2 as well)

![image](https://github.com/user-attachments/assets/ee965811-4896-4275-919b-8a6f54b239d2)

**Comment by akien-mga** [comment]
CC @Alex2782 @clayjohn

**Comment by Alex2782** [comment]
I think PR #88816 was only there to prevent the project from crashing on `Android - Adreno 3xx`, the GPU particles are invisible / not possible there either. https://github.com/godotengine/godot/blob/e439154407721b2e053c38decaa77cb520d22a12/drivers/gles3/storage/particles_storage.cpp#L125


-------------------
> On a side note, the axis lines also disappeared in that version. So it's not just Particles it looks like. (Show Origin is turned on, worked in Godot 4.2.2 as well)

[gpuparticles.zip](https://github.com/user-attachments/files/16785457/gpuparticles.zip)

We need a MRP first, does `GPUParticles` node still need to have certain settings?
It is not reproducible on my Windows11 Mini-PC with an AMD CPU/GPU. Angle version etc. could perhaps also be important. What exactly do you see displayed? @Maran23 


`OpenGL API OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 468fcbe033fa) - Compatibility - Using Device: Google Inc. (AMD) - ANGLE (AMD, AMD Radeon 780M Graphics (0x000015BF) Direct3D11 vs_5_0 ps_5_0, D3D11-32.0.11029.1008)
`

![image](https://github.com/user-attachments/assets/8d4f6f86-a43d-4571-b18a-1f839e779365)

**Comment by Maran23** [comment]
> We need a MRP first, does `GPUParticles` node still need to have certain settings? It is not reproducible on my Windows11 Mini-PC with an AMD CPU/GPU. Angle version etc. could perhaps also be important. What exactly do you see displayed? 

Forgot to attach the project we were using when bisecting, thanks. Did now.
But there are no special settings, just a plain `GPUParticles2D` will do.

> Angle version etc. could perhaps also be important.

I used the newest release in https://github.com/godotengine/godot-angle-static

> What exactly do you see displayed?

Nothing, all particles are not visible at all.

Note that I can not reproduce it on my AMD machine either with AMD Ryzen 9 5900X and AMD Radeon RX 6900 XT.

I will hopefully do some more tests later, e.g. partially reverting the changes. But I always need the help of my friend to test as he can only reproduce it. So it may take a while. :D

**Comment by Alex2782** [comment]
> Angle version etc. could perhaps also be important. What exactly do you see displayed?

> Nothing, all particles are not visible at all.

I mean this informations (Screenshot: Godot Editor - Output Tab) 
Please share, maybe important :-)   `ANGLE` version etc. 


![image](https://github.com/user-attachments/assets/e19c0d84-2c88-44c0-9054-d9fe99bef830)

**Comment by Maran23** [comment]
with yesterdays' master:

![image](https://github.com/user-attachments/assets/41327697-8db2-4e59-ab93-a99bfd7c1839)

**Comment by Maran23** [comment]
Also note that the mentioned PR did change stuff in the `glsl` files and the other similar issue https://github.com/godotengine/godot/issues/96030 which was closed as duplicate has some interesting information as well:

> In the specified Godot 4.3 versions, CPUParticles2D and GPUParticles2D nodes' particles do not render at all on web export, unless given a shader that overrides their COLOR. For example, this would suffice to fix it:

> On web, they now also render, though their color information appears to be wrong: white particles show up magenta, and yellow particles show as red. It appears that the green channel appears to be constantly zero.
My theory is that the alpha channel is also constantly zero, which would explain why the particles are invisible with the default shader.

Looking at this information, maybe the changes broke something with the colors in general for older AMD GPUs. Thats why it is not visible.

**Comment by Maran23** [comment]
Reverting all changes in the `stdlib_inc.glsl` makes the particles work again. But I'm not familiar with the `godot_unpack` methods there. (https://github.com/godotengine/godot/pull/88816/files?diff=unified&w=1#diff-add88400a9e91b99215a8cfc356779f0a7d5fb14aacc6a18c63e1ca83a1443ee)
Maybe @clayjohn has an idea?

**Comment by Alex2782** [comment]
> Do they all run the latest AMD drivers?

![image](https://github.com/user-attachments/assets/e0abb6f0-393e-4c97-9ac7-4fa8b8a0300b)

`D3D11-32.0.11029.1008` (amd driver, on my minipc windows 11)

Newer drivers cannot be installed? What versions do the other PCs have where it works?

**Comment by Maran23** [comment]
It looks like this (german):
![image](https://github.com/user-attachments/assets/b6940010-dc75-40d9-b9c1-53046c76f66b)
Not sure if there is any update, but it doesn't look like so.
The Driver & Software Panel looks different to mine, where everything works:
![image](https://github.com/user-attachments/assets/39d59dd1-df98-43ce-bf98-b17ba4098c70)


Also one thing: I changed the `unpack` and `pack` method to the one provided in https://github.com/godotengine/godot-proposals/issues/3187#issuecomment-906088616 and now everything works again. So I'm pretty certain that something in the Godot `pack`/`unpack` methods is wrong, and due to PR: https://github.com/godotengine/godot/pull/88816, we are using them now (instead of the 'native' ones)

**Comment by Maran23** [comment]
Looks like there was a similar error already:
https://github.com/godotengine/godot/issues/73320 caused by https://github.com/godotengine/godot/pull/72914 and fixed by https://github.com/godotengine/godot/pull/73332

Citing:

> For some reason the radeon drivers really don't like the h_e == uint(0x0000) comparison. Replacing it with (h_e >> uint(10)) == uint(0) works though.

I now reverted `half2float` and `float2half` before change https://github.com/godotengine/godot/pull/72914, and it works.

**Comment by Alex2782** [comment]
I would also try to download the driver update from the homepage again, maybe the update software is defective or the update is deactivated in the settings? The question is also what effects it has on other systems and drivers. On Android, users cannot update the drivers as easily as on PCs :-)


> GPUParticles are not rendered

CPU: AMD Ryzen 7 5825U       `<--- Release Date: Jan 2022`
Integrated GPU: AMD Radeon RX Vega 8    


>This combination however works:

CPU: AMD Ryzen 7 5700U    `<--- Release Date: Jan 2021`
Integrated GPU: AMD Radeon RX Vega 8

**Comment by Maran23** [comment]
Now only reverted `half2float` and it still works.

While a driver update may help, it is still something we should aim to fix, no?
The Updater might be deactivated, we found this problem on company laptops as they all have an AMD GPU, so it was broken for pretty much every laptop. But also for some friends that have e.g. an AMD Radeon RX 580, which is much older.

**Comment by Alex2782** [comment]
> The question is also what effects it has on other systems and drivers. On Android, users cannot update the drivers as easily as on PCs :-)

I have an `Adreno 3xx` (Android) device and could try your changes.


https://github.com/godotengine/godot/blob/fd7239cfab228c50777cd54a8bf6eb279a02ef81/drivers/gles3/shaders/stdlib_inc.glsl#L2-L8

**Comment by Maran23** [comment]
> If the `godot_ - renames` is only necessary for `Adreno`, then maybe we can add `#if defined`?

That was there previously, but changed in https://github.com/godotengine/godot/pull/88816 due to buggy Adreno implementation of the packed methods. We may can fix the problem by fixing `half2float` so that is works for those AMD GPUs as well as for everything else. This is unfortunately beyond my knowledge. But I will try some things in the next days, maybe I can fix it 'by accident' and someone more experienced can review it.

Also good to know that you have access to an `Adreno 3xx` device! :-)

BTW: We just checked the Radeon RX 580 Series Driver, it is indeed the newest driver and it still suffers from the problem
![image](https://github.com/user-attachments/assets/eb1188fb-279b-40e7-820d-4453e35cb04f)

**Comment by ZenRepublic** [comment]
Hey um.. I am on godot 4.3, seemingly newest official one. Ryzen 7 6800HS doesn't display particles still. On my PC particles show up nicely on web!
