### ISSUE TITLE
wierd bug when you change node name

### ISSUE THREAD

**Issue by mini-fox-dz** [godotengine/godot#95801]
### Tested versions

godot 4.3

### System information

windows 10 - godot 4.3 - compatibility - open gl 3 i guess

### Issue description

https://github.com/user-attachments/assets/5d65f52b-19c3-45a0-a3a8-f284f70a8de5

### Steps to reproduce

duble click on node and scroll down that all

### Minimal reproduction project (MRP)

you don't need file to see

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85257

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
