### ISSUE TITLE
RayCast2D does not work in tool mode in the editor

### ISSUE THREAD

**Issue by poohcom1** [godotengine/godot#95802]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.5599) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

RayCast2D doesn't work in the editor when in tool mode, even if the bodies/areas it's colliding with is also a tool.

Not sure if it's expected to work, but it's not mentioned in the [RayCast2D documentation](https://docs.godotengine.org/en/stable/classes/class_raycast2d.html), so this may just be a documentation issue.

### Steps to reproduce

1. Create a raycast2d in the editor.
2. Add a script to make the raycast2d a tool.
3. Print the raycast's collision point and collider.
4. Make the raycast collide with another body in the editor.
5. **The collision will always be (0,0) and null.**
6. Run the scene.
7. **The collision will be the correct values.**

### Minimal reproduction project (MRP)

[raycast-tool-mrp.zip](https://github.com/user-attachments/files/16661053/raycast-tool-mrp.zip)

**Comment by AThousandShips** [comment]
This is indeed a limitation by design, and should be documented, consolidating in the relevant documentation issue(s) instead

Thank you for reporting
