### ISSUE TITLE
SSR won't render on moving object

### ISSUE THREAD

**Issue by Re-drem** [godotengine/godot#95814]
### Tested versions

-Reproducible in: 4.3 stable - rc(s) - beta(s) - dev(s) 2 and above
-Not reproducible 4.3 dev1, 4.2.2 and below

### System information

Windows 10 - Godot v4.3.stable - Vulkan/d3d12 Forward+

Tested on: RTX 4070Ti, Iris Xe Graphics, GTX 1660Ti

### Issue description

When object is moving in any way, ssr won't render on it.

### Steps to reproduce

Add new scene, add "WorldEnvironment" node, add new "Environment", turn on SSR.

Add new mesh instance with reflective material and the floor to see the reflection.

(reflection really clear with metallic on 1 and roughness on 0 material)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16664109/MRP.zip)

https://github.com/user-attachments/assets/ee431b25-c8e6-496d-a8c3-9a755147c6ac

**Comment by clayjohn** [comment]
This has the same root issue as https://github.com/godotengine/godot/issues/95388 which was fixed by https://github.com/godotengine/godot/pull/95438. 

I tested both with 4.3-stable and current master to ensure that it was fixed.

The fix will be in both 4.4-dev1 and 4.3.1!
