### ISSUE TITLE
View Grid setting is not remembered between sessions

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot#95818]
### Tested versions

- Reproducible in 4.3stable (self-contained); 4.3.stable.mono (normal)
- 4.2 does not have `View Grid` in this menu

### System information

Godot v4.3.stable (using self-contained mode) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

The checkbox settings to see views in the 3d workspace are all remembered between editor sessions, except for `View Grid`, which defaults to `ON`.

It looks like these settings are stored per-scene, and `View Grid` was added in 4.3. So the mismatched behavior is likely because storing the value was either done differently or not done at all.

### Steps to reproduce

Make a new Node3D scene. Save it.

Click on `Perspective`:
![Godot_v4 3-stable_win64_hErGzIcxgB](https://github.com/user-attachments/assets/8162c2a5-9203-407e-9519-cb0b06704d51)

Set all views `OFF`: 
![Godot_v4 3-stable_win64_Zl7CPhYk5A](https://github.com/user-attachments/assets/7f51b2d9-b289-4f69-83c0-972fd058fe97)
Save the scene and restart the editor. After editor restart. Note that `View Grid` is still `ON`:
![Godot_v4 3-stable_win64_H4oYj1laPb](https://github.com/user-attachments/assets/59eabb19-6ff3-4382-b449-19b22131e568)

Set all views `ON`:
![Godot_v4 3-stable_win64_Jhqz7RbROv](https://github.com/user-attachments/assets/2641ea24-84e2-452d-951c-8ebcf31941f1)
Save the scene and restart the editor. After editor restart:
![Godot_v4 3-stable_win64_a9w18Iu7a8](https://github.com/user-attachments/assets/dec62992-a114-468d-a0ea-2eff7fc169b1)

### Minimal reproduction project (MRP)

N/A

**Comment by tetrapod00** [comment]
Unless this is specifically intended behavior, I'm going to try to make a PR for this.

**Comment by Calinou** [comment]
For reference, **View Grid** was implemented in https://github.com/godotengine/godot/pull/88584.

cc @ryevdokimov
