### ISSUE TITLE
struck at splash screen after adding child inside _draw() function

### ISSUE THREAD

**Issue by syntaxerror247** [godotengine/godot#95810]
### Tested versions

- Reproducible in 4.3.stable
- Not Reproducible in 4.2.2.stable

### System information

Godot v4.3.stable

### Issue description

When adding a child inside _draw(), it gets called infinitely. I think adding new child is calling _draw() again and a new child is added and it goes on and on....
This issue was not present in godot 4.2.2 and new child was added without any problem

### Steps to reproduce

- create a new control scene
- add a script
```gdscript
extends Control
func _draw() -> void:
	print("draw func called")
	var n = Label.new()
	add_child(n)
```
- run your scene

### Minimal reproduction project (MRP)

null

**Comment by syntaxerror247** [comment]
As a workaround, I created a can_draw variable and made it true after a process_frame, now adding child is not triggering _draw() func. 
So maybe, it only occurs if _draw() is called(or child is added ) in same process_frame as _ready()

This is my workaround code
```gdscript
extends Control
var can_draw = false
func _draw() -> void:
	if not can_draw: return
	print("draw func called")
	var n = Label.new()
	add_child(n)

func _ready() -> void:
	await get_tree().process_frame
	can_draw = true
	queue_redraw()
```

**Comment by AThousandShips** [comment]
To me this isn't very surprising, but since it changed since 4.2 it's something to investigate, but I don't expect there to be any reasonable use case for adding nodes in `_draw` without doing some tracking, so this code isn't really valid generally IMO

But this should probably be prevented in some way

**Comment by AThousandShips** [comment]
The immediate redraw is a bug, though the provided code is still invalid, or generally not appropriate as it'll add an infinite number of children as it'll redraw itself each time

So the error with immediate redraw is an issue, but is already tracked above, so this should probably focus on the possibility of documenting that adding children redraws (though I'd say that should be expected)

**Comment by syntaxerror247** [comment]
> though the provided code is still invalid, or generally not appropriate as it'll add an infinite number of children as it'll redraw itself each time

I am drawing a pie chart inside _draw() and adding new labels ( which are Label nodes) everytime it redraws(or changes) and delete previous one and it was working fine in 4.2.2

**Comment by AThousandShips** [comment]
Well that would be decent code, but your example doesn't include any removal so that's what I based my statement on 😆

The redrawing should block any queueing happening, so unsure what is broken here, if done during the draw, so unsure why this happens, will try testing it tomorrow

**Comment by syntaxerror247** [comment]
> I created a can_draw variable and made it true after a process_frame, now adding child is not triggering _draw() func.

Why _draw() is not called repeatedly in this case??

**Comment by matheusmdx** [comment]
Bisecting point to #87530 as the culprit

![image](https://github.com/user-attachments/assets/0614b017-6ea8-43a5-882f-ca41b87f6251)

<br>

How @AThousandShips said this can be a invalid code i'll not ping the pr author, so she can decide what should be done here.

**Comment by AThousandShips** [comment]
The code in this report isn't necessarily appropriate in itself, but the result of it is still invalid, so I'll go ahead and ping and I'll also take a look at the code soon, I have an idea what it might be and will do some tests

CC @YeldhamDev

**Comment by AThousandShips** [comment]
Can confirm that auto translation is the cause of this, changing `auto_translate_mode` to `disable` on the root node prevents this, will try see what kind of issue is sparking this, I suspect it is caused by translation causing resizing which enters some kind of recursion

**Comment by AThousandShips** [comment]
I have a tentative fix but need to identify some more details and what exactly is happening in it
