### ISSUE TITLE
Godot project manager continuously steals focus on i3

### ISSUE THREAD

**Issue by voylin** [godotengine/godot#95824]
### Tested versions

Happens in 4.3, didn't happen in 4.2

### System information

Arch Linux, linux-lts kernel, i3-wm

### Issue description

https://youtu.be/pEWb0VJnhkQ
I filmed what exactly happens, basically when using the mouse to focus other windows, or my keyboard shortcuts, Godot keeps taking/stealing the focus for itself. There is also quite a lot of lag when using the startup screen of Godot, the focus on buttons and presses takes a long second or 2 to actually register, but I think this might be a separate issue?

Edit: This does not happen when inside a project, only on the project select screen.

### Steps to reproduce

Open the editor, and try to use other windows.

### Minimal reproduction project (MRP)

Not needed

**Comment by Rindbee** [comment]
After git bisect, it was found that it was a regression introduced by #93682.

**Comment by Calinou** [comment]
cc @dsnopek

**Comment by Rindbee** [comment]
The issue seems to be related to the following code:

https://github.com/godotengine/godot/blob/e3550cb20f5d6a61befaafb7d9cbdb57b24870e4/scene/gui/line_edit.cpp#L1090-L1093

`has_focus()` does not check if the `viewport(window`) still has focus, and `NOTIFICATION_APPLICATION_FOCUS_OUT` does not clear `gui.key_focus`.

**Comment by dsnopek** [comment]
Thanks for the report!

What version of i3 are you using? I'm using v4.22, and can't seem to reproduce the issue.

**Comment by Naynuza** [comment]
I'm getting this on windows when importing a ton of assets

**Comment by Rindbee** [comment]
I'm using v4.23, it's easy to reproduce.

**Comment by Zireael07** [comment]
@Naynuza This is linux AND i3 specific, whatever you're experiencing is not this

**Comment by voylin** [comment]
> Thanks for the report!
> 
> What version of i3 are you using? I'm using v4.22, and can't seem to reproduce the issue.

I'm using version 4.23-4.
Already updated Godot to the 4.3-3 package and still experiencing the same bug.

**Comment by dsnopek** [comment]
I updated to i3 v4.23 and still can't reproduce it on my main machine, which is Ubuntu 22.04.

However, I just tried in a Fedora 40 VM, and I _can_ reproduce it there! So, that's a start. :-) I'll dig into it and see what I can figure out.

**Comment by voylin** [comment]
> However, I just tried in a Fedora 40 VM, and I _can_ reproduce it there! So, that's a start. :-) I'll dig into it and see what I can figure out.

If you need more information or help, feel free to ask ^^

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/96829 which fixes this issue in my testing. Please test and let me know if it works for you!

**Comment by voylin** [comment]
Your PR #96829 seems to fix the issue for me as well ^^
