### ISSUE TITLE
TextureAtlas region not working in Albeto StandardMaterial3D, and pixel values of texture are broken

### ISSUE THREAD

**Issue by djkato** [godotengine/godot#95823]
### Tested versions

![image](https://github.com/user-attachments/assets/2558c089-ad60-4b94-8c92-419b90950b06)
v4.2.2.stable.fedora [15073afe3]

### System information

Godot v4.2.2.stable (15073afe3) - Fedora Linux 40 (Workstation Edition) - Wayland - GLES3 (Compatibility) - AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.6, DRM 3.57, 6.10.4-200.fc40.x86_64) () - AMD Ryzen 5 7530U with Radeon Graphics (12 Threads)

### Issue description

The texture atlas doesn't work as albeto texture map neither set programatically through script nor through gui.  Also, the pixels of my pixel art are completely mis-colored. I got my pixel art sprite sheet from https://piskelapp.com, exported as atlas png.

### Steps to reproduce

1. export from piskelapp random pixel art atlas
2. create characterBody3d > MeshInstance3D
3. atlas texture in mesh material albeto
4. try to set region of mesh

### Minimal reproduction project (MRP)

[MRP-atlastexture.zip](https://github.com/user-attachments/files/16666402/MRP-atlastexture.zip)

**Comment by AThousandShips** [comment]
This is a limitation that is undocumented, `AtlasTexture` only works in specific contexts, see also:
* https://github.com/godotengine/godot/issues/95507

**Comment by AThousandShips** [comment]
Thank you for reporting, this is a missing feature and the proposal is tracked here:
* https://github.com/godotengine/godot-proposals/issues/1708

**Comment by Calinou** [comment]
> Also, the pixels of my pixel art are completely mis-colored.

Set the compression mode for the image to **Lossless** in the Import dock.
