### ISSUE TITLE
OptionButton prevent events in "_input" from showing

### ISSUE THREAD

**Issue by MarcelisG** [godotengine/godot#95829]
### Tested versions

- Reproducible in: 4.2.2.stable

### System information

Godot v4.2.2.stable (15073afe3) - Nobara Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (nvidia; 560.31.02) - 13th Gen Intel(R) Core(TM) i5-13600K (20 Threads)

### Issue description

When the popup is open for the OptionButton, if you print the event's from the "_input" from the inputEvent function it will not print any event until the popup is closed. On my system specifically when pressing the controller button that is bind to "ui_select", it does not select the focused option in the popup but the key press does. 

### Steps to reproduce

Create an Empty Project
Make an OptionButton as root node
Add 2 Items to the popup
Run Scene, click to open popup
Attempt to click joypadbutton for "ui_select"

### Minimal reproduction project (MRP)

Test Project
[COPYME.zip](https://github.com/user-attachments/files/16667175/COPYME.zip)

**Comment by AThousandShips** [comment]
The popup will capture any input when it has focus (and it will close when losing focus), so I'd say this is as intended, and as desired IMO, generally you wouldn't want input to be sent when doing this

If you want the input you can connect to the input signal of the menu, with [`get_popup`](https://docs.godotengine.org/en/stable/classes/class_optionbutton.html#class-optionbutton-method-get-popup)

**Comment by MarcelisG** [comment]
So I made a new project same version and system information. Made a OptionButton root node attached a built-in script to the node. Edited in the code below, and when the popup is open and I press the "ui_select" joy pad button and it still doesn't register that an id was pressed on both signals. It does obviously call the "id_focused" signal. Is that intended? 
![Screenshot_20240820_104621](https://github.com/user-attachments/assets/8318c51e-7136-461e-952b-ab5c006f143f)

**Comment by AThousandShips** [comment]
I think that's intentional yes, you need to press it for it to activate, which is `ui_accept` I'd say

**Comment by MarcelisG** [comment]
Ok, now i see the issue I had lol. Should've checked .cpp for it. Thanks for the help.
