### ISSUE TITLE
`Aabb.Merge(someAabb)` does not create Aabb that surrounds both Aabbs.

### ISSUE THREAD

**Issue by yosimba2000** [godotengine/godot#95836]
### Tested versions

Godot 4.3 .Net

### System information

Win10 x64 22H2

### Issue description

`Aabb.Merge(someAabb)` does not create Aabb that surrounds both Aabbs.

### Steps to reproduce

1) Create any mesh. I'll just use a CSGBox3D with default transforms.
2) Print `box's Aabb.Size`. It should produce (1,1,1).
3) Create new Aabb during runtime, and merge it with box's Aabb with `Aabb.Merge()`.
4) Print `merged Aabb.Size`. It should produce (1,1,1) but actually produces (0,0,0).

Maybe related to https://github.com/godotengine/godot/issues/95051

### Minimal reproduction project (MRP)

[aabb.zip](https://github.com/user-attachments/files/16667815/aabb.zip)

**Comment by raulsntos** [comment]
You are ignoring the return value of the `Merge` method.

**Comment by yosimba2000** [comment]
> You are ignoring the return value of the `Merge` method.

I am so sorry :*(
