### ISSUE TITLE
webgl/compatibility broken on mac in chrome

### ISSUE THREAD

**Issue by graphific** [godotengine/godot#95832]
### Tested versions

- reproducible in 4.3 rc1 to 4.3 stable

### System information

mac m1 = IOS - Godot 4.3 stable

### Issue description

Issue while developing a web build that quite often a webgl context loss, or webgl features missing pops up when using a mac (m1 air in my case), and running chrome.
Turns out that a lot of this is not a problem on safari or firefox, so more a chrome issue (but since thats about 66% of all internet users thats quite a lot).

This is a simple project (https://github.com/awnagel/Godot-Thief-Controller) that has this issue specifically [here](https://github.com/awnagel/Godot-Thief-Controller/blob/master/addons/thief_controller/scripts/player/light_detector.gd#L45)
which is a worse case issue as theres no warnings thrown that things dont work here

### Steps to reproduce

- create a viewport with a camera
- img = _viewport_top.get_texture().get_image() = throws an error on chrome

MRP below gives the "WebGL context lost, please reload the page" error from trying to show a subviewport in a texturerect, something very common to do and I'm pretty sure this used to work with earlier chrome versions which now also means older games are broken. This one for instance doesnt work for me anymore on chrome: https://graphific.itch.io/bird-ruckus

### Minimal reproduction project (MRP)

[web-issue.zip](https://github.com/user-attachments/files/16667196/web-issue.zip)

**Comment by clayjohn** [comment]
Since this is a regression from a recent version of chrome, have you reported this bug to the chrome developers as well?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/95206.
