### ISSUE TITLE
PopupMenu ID 0 is replaced by its index position.

### ISSUE THREAD

**Issue by Ketei** [godotengine/godot#95847]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility)

### Issue description

When using a PopupMenu (via MenuButton) and trying to use the assigned ID, if that ID is 0 it'll be replaced by the index.

https://github.com/user-attachments/assets/f42970d5-c5f3-4e12-8517-a1aecec92b67

### Steps to reproduce

1. Create MenuButton.
2. Create 2 or more items each with a unique ID.
3. Move item with ID 0 to any index but 0.
4. Connect id_pressed signal.
5. That menu item ID 0 will be replaced by its index on the call.

### Minimal reproduction project (MRP)

[popupmenubug.zip](https://github.com/user-attachments/files/16669870/popupmenubug.zip)

**Comment by kleonc** [comment]
This is a regression from #88306. cc @KoBeWi

`id = 0` is no longer force-saved within the scene file (same for e.g. OptionButton).

After saving a scene with:
![Godot_v4 2 2-stable_win64_0XX8wcrDxR](https://github.com/user-attachments/assets/1f734a3e-d705-44ef-9333-a9580df5fefe)

`.tscn` contents:
- v4.2.2.stable.official [15073afe3]
```
...
popup/item_0/text = "ID 1"
popup/item_0/id = 1
popup/item_1/text = "ID 0"
popup/item_1/id = 0
popup/item_2/text = "ID 2"
popup/item_2/id = 2
...
```
- v4.3.stable.official [77dcf97d8]
```
...
popup/item_0/text = "ID 1"
popup/item_0/id = 1
popup/item_1/text = "ID 0"
popup/item_2/text = "ID 2"
popup/item_2/id = 2
...
```
