### ISSUE TITLE
[C#] Control Node do change Name correctly when name has "@" [Version 4.3]

### ISSUE THREAD

**Issue by theicecrystal** [godotengine/godot#95859]
### Tested versions

Test on version 4.3 + 4.2.2

### System information

Windows 11 - Godot v4.3.stable - Vulkan (Forward+) - Editor

### Issue description

I has a code that send object name to control node but name auto gen.
So end up I encounter with this bug that name do not properly change.
.
![Untitled](https://github.com/user-attachments/assets/a5e23d73-f25c-4c38-a661-eef4678832ce)
![Untitled](https://github.com/user-attachments/assets/da392f2f-f7d4-4cbb-9d99-01c61207a48c)

### Steps to reproduce
```cs
	public void Add_UI(string name)
	{
		GD.Print("Add_UI|" + name);

		Button_Panel Cache = UI_Human.Instantiate<Button_Panel>();//Button_Panel is Control node Inheritance

		AddChild(Cache);

		Cache.Name = name;

		Cache.variant = name;

		Cache.GetChild(0).GetChild<Label>(0).Text = name;

		GD.Print("Name Result|" + Cache.Name);
	}
```
	
print log

```
Add_UI|_01_human
Name Result|_01_human
Add_UI|@Node3D@2
Name Result|_Node3D_2
Add_UI|@Node3D@3
Name Result|_Node3D_3
Add_UI|@Node3D@4
Name Result|_Node3D_4
```

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16675070/new-game-project.zip)

**Comment by AThousandShips** [comment]
You need to change your code to:
`AddChild(Cache, true)`

See the documentation for [`AddChild`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-add-child)

**Comment by theicecrystal** [comment]
![image](https://github.com/user-attachments/assets/a241c9e9-f28f-4944-8882-bd0deec9eb4f)

after change to

	public void Add_UI(string name)
	{
		Button_Panel Cache = UI_Human.Instantiate<Button_Panel>();

		Cache.Name = name;

		Cache.variant = name;

		AddChild(Cache, true);

		Cache.GetChild(0).GetChild<Label>(0).Text = name;
	}

still bug

**Comment by AThousandShips** [comment]
What isn't working? What are you expecting the names to be?

Please explain what you want it to look like

**Comment by theicecrystal** [comment]
(string name)//name gen from Node3D

My point is the name is generate from Node3D and it work fine.
I use to it to call all function on the game so naming to is so important.
Right now I'm just create a random number so it work.

**Comment by akien-mga** [comment]
This is the problem and the minimal MRP:
```gdscript
func _ready():
	var node1 = Node.new()
	add_child(node1)
	print(node1.name)  # @Node@2
	var node2 = Node.new()
	add_child(node2)
	print(node2.name)  # @Node@3
	var node3 = Node.new()
	node3.name = node2.name
	add_child(node3)
	print(node3.name)  # _Node_3
```

Godot itself can name a node with `@` when you don't name it uniquely and don't use `force_readable_name`. But you can't reuse that name to name another node as `@` symbols get removed when calling `set_name` from GDScript (while the engine uses another version that allows `@`).

**Comment by akien-mga** [comment]
To be clear this could still be considered a valid bug. But honestly I'm not sure how we would solve it.

So indeed what should be done for this use case is to give readable names to the first nodes, so that those names can be reused from code to name new nodes.

**Comment by theicecrystal** [comment]
I love that idea that give readable names to the first nodes.
