### ISSUE TITLE
Help wanted: New site aim to make godot more popular in china

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#9585]
Dear developers of godot game engine,

Thanks for your hard working with the open source game engine. Godot is really a good game engine. I love the engine and I think all developers would love it after using it. Unfortunately, most game developers in China do not know the existence of this excellent engine.

We (some godoters in china) are tring to share the engine with others. A lot of developers joined us to try the new engine. The group could be called as the Chinese community and it is growing up.

But there always problems when we share godot with others:
1. The official site is blocked by the evil fire wall in some area.
2. The official site and documentation page is too slow to open in some area.
3. People are poor of english like me to understand the advantages of the engine and documentations.

To solve these problems we setup a translated website here:
http://godot.studio

We hope we can get support from the official godot community.
Could you please redirect the domains below to our site to make us likes more official so we could be more confident to share with others.

* cn.godotengine.org
* zh.godotengine.org

And maybe add a link in the official site.

Thanks for your reading.

Geequlim

**Comment by fightbear** [comment]
well done!

**Comment by gdtdftdqtd** [comment]
good~~~

**Comment by gtd138** [comment]
It must be necessity！

**Comment by sanikoyes** [comment]
good job!

**Comment by Chaosus** [comment]
Sorry, but I should close this issue - links are not fixed, and site is not existed. If you fixed the links then reopen it, and I will remove the archived tag
