### ISSUE TITLE
`Directional` property on `LightmapGI` node causes invalid pixels.

### ISSUE THREAD

**Issue by EMBYRDEV** [godotengine/godot#95875]
### Tested versions

4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 32.0.15.6070) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Switching on directional lightmapping can lead to invalid pixels that when paired with autoexposure can completely corrupt the scene.

LightmapGI non-directional: 
![image](https://github.com/user-attachments/assets/4dcc59a5-8925-48ec-a0c5-5f17153774d4)

LightmapGI directional:
![image](https://github.com/user-attachments/assets/dd8ca4c7-d495-4d31-af61-94dd881e2b54)

Directional with moved camera:
![image](https://github.com/user-attachments/assets/0b24c315-1d28-451d-94e6-166572b447c0)

### Steps to reproduce

1. Download project: https://github.com/perfoon/Abandoned-Spaceship-Godot-Demo
2. Enable autoexposure in the Hangar's world environment
3. Bake lightmap using OIDN (havent tested with JNLM)
4. Observe lack of artifacting
5. Bake lightmap with `Directional` enabled.
6. Observe massive bloom and severe artifacting when rotating camera.

### Minimal reproduction project (MRP)

https://github.com/perfoon/Abandoned-Spaceship-Godot-Demo

**Comment by clayjohn** [comment]
I wonder if this is the same as https://github.com/godotengine/godot/issues/81556. We could be getting NaNs that get propagated by the auto exposure

**Comment by EMBYRDEV** [comment]
> I wonder if this is the same as #81556. We could be getting NaNs that get propagated by the auto exposure

Potentially, I'm getting some similar looking specular in some parts of the scene 
![image](https://github.com/user-attachments/assets/d5242dac-03a7-4d25-86a0-924ac86312df)

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/95888 doesn't seem to fix the issue completely on the MRP. Baking with **Directional** enabled still creates a brighter overall lightmap with flickering occuring when Glow is enabled:

Directional OFF | Directional ON
-|-
![image](https://github.com/user-attachments/assets/59db7ebc-94e6-4a65-a58c-03e1c5a54b0a) | !
![image](https://github.com/user-attachments/assets/3969334d-446d-473b-9588-ba02d95040cf)

Probes also have negative-looking artifacts not present when Directional is disabled:

Directional OFF | Directional ON
-|-
![image](https://github.com/user-attachments/assets/d8e37c4d-bf3a-4520-9173-1366f5bb753e) | ![image](https://github.com/user-attachments/assets/9f6c3b62-2ff8-4043-8362-f04f62a54181)

Dynamic objects themselves look fine though, so maybe this is just an issue with the visualization.

**Comment by BlueCube3310** [comment]
> but that PR still seems to struggle with baked light on alpha-tested materials. Baking with **Directional** enabled still creates a brighter overall lightmap with flickering occuring when Glow is enabled:

These look like banding artifacts that occur due to sampling the SH lightmap's lower hemisphere, which has negative colors.
