### ISSUE TITLE
Interface goes beyond the aisles of the screen [Android Editor]

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#95878]
### Tested versions

Godot 4.3 stable (Android)

### System information

Godot v4.3.stable - ArrowOS Arrow-v11.0-vayu-OFFICIAL-20210928-GAPPS - Vulkan (Mobile) - integrated Adreno (TM) 640 -  (7 Threads)

### Issue description

When the script editor is selected, as well as the shader editor, the entire lower part of the interface goes beyond the screen.
If one of these editors is not selected, the interface looks fine.
![Screenshot_20240821-055551](https://github.com/user-attachments/assets/4c49465f-5dc3-4404-a063-a58b545b3100)

### Steps to reproduce

1. Open Godot Engine on your phone
2. Select the script editor in the upper panel and the shader editor in the lower panel.

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment]
This also happens if the Audio editor is selected on the bottom panel

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/26835.
