### ISSUE TITLE
mac build / get_parent is returning boolean

### ISSUE THREAD

**Issue by georgesboris** [godotengine/godot#9587]
when using the latest mac build (july 9th) get_parent is returning a boolean type.
this also happened in the previous build (july 8th) and those were the only ones that I've tried.

my project is just a blank scene with 2 node2D objects. the child one is calling get_parent() on _ready(). really easy to reproduce. I think this is exclusive to the mac build since other linux users where not able to reproduce it.

**Comment by groud** [comment]
Where did you get the build from ?
Have you tried compiling from source ?

**Comment by georgesboris** [comment]
Hi. I've got the build from fixnum. Will try to compile from software and post the results here.

**Comment by groud** [comment]
From what I read, the fixnum OS X build is broken : 

> Notes
> I currently can't build for iOS. OS X builds are generated with osxcross, using Xcode 7.3.1. 
> Prior to June 10, 2016 I was unable to produce builds for OS X as well. tonymtbird helped out by making sporadic builds of the tools and templates on his Mac to be provided here. Note that these builds might not correspond to the exact commit of the other platforms. 

Try compiling from source.

**Comment by akien-mga** [comment]
Please attach a zip of the project you use to reproduce this bug. I don't see how it could be a platform-related bug, a compiler wouldn't change a return type automatically from `Node` to `bool`: https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L1575

**Comment by akien-mga** [comment]
>> From what I read, the fixnum OS X build is broken :
>
> Notes
I currently can't build for iOS. OS X builds are generated with osxcross, using Xcode 7.3.1.
Prior to June 10, 2016 I was unable to produce builds for OS X as well. tonymtbird helped out by making sporadic builds of the tools and templates on his Mac to be provided here. Note that these builds might not correspond to the exact commit of the other platforms.

This actually says that iOS builds are broken, not OS X ;) The part about pre-June 2016 is likely outdated by now.

**Comment by groud** [comment]
Ok. But well, I don't see other reason how a Node* could be converted into a bool but from a problem in the code version. As the fixnum builds are "unofficial", I assumed the problem should probably come from the build. But I might be wrong... ^^ 
Also, this cannot be reproduced on ubuntu.

**Comment by georgesboris** [comment]
Just built it from source and the issue remains.
There are some errors on the console though: 

<img width="602" alt="captura de tela 2017-07-10 as 11 16 16 am" src="https://user-images.githubusercontent.com/3660797/28022326-3a11e704-6561-11e7-8c26-e02d30c6d3e1.png">

Here's a barebones project that reproduces the error:

[godot_get_parent_issue.zip](https://github.com/godotengine/godot/files/1135784/godot_get_parent_issue.zip)

I'm using macOS Sierra in a macbook pro retina mid 2012.

**Comment by marcelofg55** [comment]
I've just tested your project with latest master and I can confirm this too a OS X Yosemite.

**Comment by akien-mga** [comment]
Some paranormal activity on OS X :D

**Comment by Sslaxx** [comment]
Runs as expected (returns position) using latest build from Git master, Ubuntu Linux 17.04 64-bit.

**Comment by Julianobsg** [comment]
I made a build yesterday from master and got the same problem.

**Comment by BastiaanOlij** [comment]
Ditto here.... doesn't make any sense..

**Comment by groud** [comment]
![1sbb33](https://user-images.githubusercontent.com/6093119/28066358-eed34fd0-663c-11e7-8ef7-f73a1344377f.jpg)

**Comment by reduz** [comment]
Does this still happen? Could anyone confirm?

**Comment by marcelofg55** [comment]
Just re-tested with latest master and its fixed :D

**Comment by groud** [comment]
\o/
Closing.
