### ISSUE TITLE
White line in 3D view in editor using Metal on MacOS

### ISSUE THREAD

**Issue by Snowdaw** [godotengine/godot#95896]
### Tested versions

Happens in v4.4.dev.custom_build [3b3d622]
It says custom due to my spotty internet not being able to successfully git clone the repository. I used the ZIP download which doesn't include the .git folder. This is just a normal build using 3b3d622.

### System information

Godot v4.4.dev unknown - macOS 14.3.1 - Metal (Mobile) - integrated Apple M1 (Apple7) - Apple M1 (8 Threads)

### Issue description

When loading in a newly created project a white line can be seen in the 3D view.
<img width="597" alt="image" src="https://github.com/user-attachments/assets/15fd948c-b9d9-4e13-96b6-400c223c01c2">

### Steps to reproduce

1. Use an editor build with Metal on MacOS (3b3d622 in my case)
2. Create a new project
3. Observe the white line

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
CC @stuartcarnie @clayjohn @bruvzg

**Comment by Snowdaw** [comment]
Hi @stuartcarnie I can confirm that it does not happen when launching with `--rendering-driver metal`
I assumed that Metal would be enabled by default as is written in https://github.com/godotengine/godot/pull/88199
Together with the rather confusing `OpenGL API 4.1 Metal` message when using OpenGL and just `Metal 3.1` when using Metal. I just assumed it was using Metal when I saw it in the first message.

Is it correct behaviour that OpenGL is used by default even when Metal is available?

**Comment by stuartcarnie** [comment]
@clayjohn ahh TIL! Sorry for the confusion.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/91107.

**Comment by bruvzg** [comment]
Help -> System Info shows the driver and method only based on project settings and ignore command line arguments/fallback (should be fixed by https://github.com/godotengine/godot/pull/95887)

And macOS native OpenGL renderer does have Metal in the name at least on Apple Silicon. So it might be confusing.
