### ISSUE TITLE
my texture has a weird rectangle as compression artifact on godot 4.3

### ISSUE THREAD

**Issue by Bowser04** [godotengine/godot#95907]
### Tested versions

in godot 4.3

### System information

Windows 11 Godot 4.3 Forward+

### Issue description

in godot :
![image](https://github.com/user-attachments/assets/15ef85cc-94cf-43d6-b6b7-40dc2e75ad44)

in paint.net:
![image](https://github.com/user-attachments/assets/8bb60577-6359-4f79-ac0d-bc95df602e87)

original file:
![exemple](https://github.com/user-attachments/assets/797ba67d-27db-4bf0-a7c9-f166cc5a56c2)

### Steps to reproduce

add this texture on a object in 3d or a sprite in 2d on godot 4.3
![exemple](https://github.com/user-attachments/assets/f2d42ff2-909c-4f32-a66d-b6342ead71a3)

### Minimal reproduction project (MRP)

Minimal reproduction project :
[texture_bug_project_MBR.zip](https://github.com/user-attachments/files/16694203/texture_bug_project_MBR.zip)

**Comment by Calinou** [comment]
This is an expected artifact of VRAM compression. Change the compress mode to **Lossless** in the Import dock for the source image.
