### ISSUE TITLE
A negative scale (caused by a mirror action in Blender) makes the strange phenomenon on light casting (the back is lightened wrongly) 

### ISSUE THREAD

**Issue by PiYuanZhouLv** [godotengine/godot#95901]
### Tested versions

- Reproduced in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Unknown AMD GPU () - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

To simplify my work on modeling, I use "Mirror" action to cut down some unnecessary work in Blender. But when I turned the light on, I found some desk worked correct while others wrong.
![图片](https://github.com/user-attachments/assets/f95c1a5a-38c0-41f2-bc62-fe31062e8e3c)
After I researched a bit more, I figured out that the wrongly rendered ones have the surface be lightened on the bottom!
![图片](https://github.com/user-attachments/assets/fc58d73a-ab85-4a16-b7b2-f20a9ff171d0)

### Steps to reproduce

To reproduce the bug:

## Way A (a bit more complex, but it explains why I need this to fix)
1. Open Blender, and attach some texture on the block, then copy it and mirror it.
![InBlender](https://github.com/user-attachments/assets/0e7f9644-e172-4352-b0f6-3404e87440f4)
2. Then export it into glTF 2.0 format
3. Create a project in Godot and then import the scene.
<img width="674" alt="InGodot" src="https://github.com/user-attachments/assets/642818c0-bd1d-4739-8a5c-87252915be13">

## ~~Way B (more simple)~~ (seems works correct)
1. Create a project in Godot and add a "MeshInstance3D" as a block.
2. Then copy it and move them into a proper place.
3. Simply set one blocks "scale" to -1 or other negative value

### Minimal reproduction project (MRP)

[BugTest.zip](https://github.com/user-attachments/files/16690817/BugTest.zip)

**Comment by PiYuanZhouLv** [comment]
**I'm sorry for my carelessness! The "Way B" worked properly, this problem seemed to happen in the imported scene or something like that.**

Additionally, the impact can influence the children nodes.

**Comment by AThousandShips** [comment]
Sounds similar to:
* https://github.com/godotengine/godot/issues/86131

Can you test with 4.3?

**Comment by PiYuanZhouLv** [comment]
I tried to export with targets and forced to disable the compression, but it didn't work as well - not like the one in [#86131](https://github.com/godotengine/godot/issues/86131#issuecomment-1938731240).

By the way, when I conduct this experiment, I export a model without normals at first mistakenly and found the effect invert, which makes me think the normals are to be blamed for this problem.
![图片](https://github.com/user-attachments/assets/206adb0e-d245-4244-a847-931bdc3ec3e1)

Hope this can help you!   : )

**Comment by PiYuanZhouLv** [comment]
Thanks for dealing with my problem, hope you can solve it soon!

(By the way, I discovered a solution to my _own_ issue: **Nobody told me to "Apply the transform" before I export**, which would make all scale to 1 thus it can help me avoid this bug!)
![图片](https://github.com/user-attachments/assets/537f30f7-75ff-4d0c-9c38-9e6a0d6fd064)
