### ISSUE TITLE
Godot crashes when importing project data

### ISSUE THREAD

**Issue by anderlli0053** [godotengine/godot#95918]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Windows 10, 64-bit, 22H2 OS BUILD: 19045.3996 - Compatibility rendering (OpenGL3)

### Issue description

I am working on a quite big test project, my project data (3D models, audio, ....) contain around 3GB of such files.

Now when the editor starts, it begins "scanning the files" as can be seen in the file panel, when it comes to 100% it begins importing them and after a few second at around ~7% - 10 % it just freezes, crashes and then this error is shown:

![err](https://github.com/user-attachments/assets/472c4f02-d54f-44a4-8b78-755deca07ffd)

I do not know how to debug it any further, since i have tried with `--verbose` , `--debug` `--trace` ( `godot.exe --debug --verbose --trace` ).

I also know that there are so called "debug builds" for Godot3 -> https://github.com/Calinou/godot-debug-builds , but i couldn't find any for Godot 4.

I have around 14,3 GB of free space on my disk (out of allegedly 237 GB )

![err2](https://github.com/user-attachments/assets/3f472ac2-3a71-4857-b07f-8c3d57f98906)

This is my example folder structure:

https://pastebin.com/EyBUZBau

and my OS info:

![osinfo](https://github.com/user-attachments/assets/71f35d16-d692-4d83-a0b8-ca0aced5b260)

I thought that this is the issue of my RAM, but it is not since the Godot processes only take about 1 GB of RAM max!

Are there any other debugging/stacktrace solutions, like the aforementioned Calinou's debug builds?

### Steps to reproduce

I cannot recreate the steps nor can i create the MRP. It works well with any other project that i open/edit, but this.

I've tried to create MRP from the existing one, but it always work, what cannot be said to the original full sized project.

### Minimal reproduction project (MRP)

I cannot recreate the steps nor can i create the MRP. It works well with any other project that i open/edit, but this.

I've tried to create MRP from the existing one, but it always work, what cannot be said to the original full sized project.

**Comment by matheusmdx** [comment]
Without a project to test and no steps to reproduce will be hard to help, in this case you can [compile the engine](https://docs.godotengine.org/en/stable/contributing/development/compiling/index.html) with debug symbols to get a backtrace and give us some hint or if possible upload the entire project so we can try reproduce the bug

**Comment by anderlli0053** [comment]
Finally i got the backtrace from a custom build:


BACKTRACE:

```
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.4.dev.custom_build (568589c9d8c763bfb3a4348174d53b42d7c59f21)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] CowData<unsigned char>::_get_size (C:\Users\ander\Desktop\godotsrc\godot\core\templates\cowdata.h:128)
[1] CowData<unsigned char>::_get_size (C:\Users\ander\Desktop\godotsrc\godot\core\templates\cowdata.h:128)
[2] CowData<unsigned char>::size (C:\Users\ander\Desktop\godotsrc\godot\core\templates\cowdata.h:181)
[3] Vector<unsigned char>::size (C:\Users\ander\Desktop\godotsrc\godot\core\templates\vector.h:94)
[4] Image::detect_alpha (C:\Users\ander\Desktop\godotsrc\godot\core\io\image.cpp:2534)
[5] FBXDocument::_parse_materials (C:\Users\ander\Desktop\godotsrc\godot\modules\fbx\fbx_document.cpp:1240)
[6] FBXDocument::_parse_fbx_state (C:\Users\ander\Desktop\godotsrc\godot\modules\fbx\fbx_document.cpp:2187)
[7] FBXDocument::_parse (C:\Users\ander\Desktop\godotsrc\godot\modules\fbx\fbx_document.cpp:2111)
[8] FBXDocument::append_from_file (C:\Users\ander\Desktop\godotsrc\godot\modules\fbx\fbx_document.cpp:2254)
[9] EditorSceneFormatImporterUFBX::import_scene (C:\Users\ander\Desktop\godotsrc\godot\modules\fbx\editor\editor_scene_importer_ufbx.cpp:81)
[10] ResourceImporterScene::import (C:\Users\ander\Desktop\godotsrc\godot\editor\import\3d\resource_importer_scene.cpp:2940)
[11] EditorFileSystem::_reimport_file (C:\Users\ander\Desktop\godotsrc\godot\editor\editor_file_system.cpp:2471)
[12] EditorFileSystem::reimport_files (C:\Users\ander\Desktop\godotsrc\godot\editor\editor_file_system.cpp:2760)
[13] EditorFileSystem::_update_scan_actions (C:\Users\ander\Desktop\godotsrc\godot\editor\editor_file_system.cpp:804)
[14] EditorFileSystem::_notification (C:\Users\ander\Desktop\godotsrc\godot\editor\editor_file_system.cpp:1496)
[15] EditorFileSystem::_notificationv (C:\Users\ander\Desktop\godotsrc\godot\editor\editor_file_system.h:141)
[16] Object::notification (C:\Users\ander\Desktop\godotsrc\godot\core\object\object.cpp:870)
[17] SceneTree::_process_group (C:\Users\ander\Desktop\godotsrc\godot\scene\main\scene_tree.cpp:1020)
[18] SceneTree::_process (C:\Users\ander\Desktop\godotsrc\godot\scene\main\scene_tree.cpp:1097)
[19] SceneTree::process (C:\Users\ander\Desktop\godotsrc\godot\scene\main\scene_tree.cpp:582)
[20] Main::iteration (C:\Users\ander\Desktop\godotsrc\godot\main\main.cpp:4234)
[21] OS_Windows::run (C:\Users\ander\Desktop\godotsrc\godot\platform\windows\os_windows.cpp:1666)
[22] widechar_main (C:\Users\ander\Desktop\godotsrc\godot\platform\windows\godot_windows.cpp:180)
[23] _main (C:\Users\ander\Desktop\godotsrc\godot\platform\windows\godot_windows.cpp:206)
[24] main (C:\Users\ander\Desktop\godotsrc\godot\platform\windows\godot_windows.cpp:220)
[25] WinMain (C:\Users\ander\Desktop\godotsrc\godot\platform\windows\godot_windows.cpp:234)
[26] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[27] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

**Comment by anderlli0053** [comment]
AI is giving me this info about this backtrace:

This crash report points to an issue with the FBX file import process in Godot, specifically related to parsing materials and detecting alpha channels. Here's a breakdown of the key points in the backtrace:

FBX Importer Issue: The error occurs while Godot is parsing an FBX file. FBX files contain 3D models, animations, and other data used in game development. The crash seems to happen during the material parsing phase (`FBXDocument::_parse_materials`).

**CowData** and **Vector** Issues: The crash happens inside the **CowData** and **Vector** templates, which are used to manage dynamic arrays of data (likely pixel or texture data in this case). The function _Image::detect_alpha_ is being called, which checks if an image has an alpha (transparency) channel. Something about the data being processed here is causing the crash.

Godot Editor Process: The crash is triggered during an attempt to import a scene or resource (possibly an FBX file), and it happens when the editor is scanning and re-importing files (`EditorFileSystem::_reimport_file`).

If you're comfortable with it, you could debug the Godot engine code around `fbx_document.cpp` and `image.cpp` to pinpoint the cause of the crash. This would involve analyzing how the materials and alpha channels are being handled.

**Comment by anderlli0053** [comment]
I do have VS2022 Community, yes

**Comment by anderlli0053** [comment]
I have tried with WinDBG, x64DBG, VS2022 and VSCodium and it always just prints out this:


The editor process is a separate thing from the project manager, even if i try to attach the debugger to already running process (godot) it closes prematurely, godot exits with no trace being logged or they both crash (the debugger and godot binary)

**Comment by matheusmdx** [comment]
You need to open your project directly using "--editor --path absolute_path_to_your_project", in VS Code will be like that:
 
![image](https://github.com/user-attachments/assets/5f84c08d-1021-42a0-bd29-c5b7fdb54fbf)

**Comment by Saul2022** [comment]
Can you reproduce it with 4.2 and how much is the size of the mesh? For example a 700 glb files crashes for me when importing, so that might be the issue.

**Comment by anderlli0053** [comment]
> Can you reproduce it with 4.2 and how much is the size of the mesh? For example a 700 glb files crashes for me when importing, so that might be the issue.

I have around at least ~1000 different models in various formats, FBX, GLB, DAE and BLEND, subsequently that also means that there are many textures, including PBR and ORM ones.

**Comment by anderlli0053** [comment]
> You need to open your project directly using "--editor --path absolute_path_to_your_project", in VS Code will be like that:
> 
> ![image](https://private-user-images.githubusercontent.com/44306054/360635568-5f84c08d-1021-42a0-bd29-c5b7fdb54fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjA2ODAsIm5iZiI6MTcyNDM2MDM4MCwicGF0aCI6Ii80NDMwNjA1NC8zNjA2MzU1NjgtNWY4NGMwOGQtMTAyMS00MmEwLWJkMjktYzViN2ZkYjU0ZmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDIwNTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmODg2N2U5ZWU0MTkyYmM2NjY2Y2NjZTY1N2ZmYTExNDU0NDI0YzdhNjY1M2U3NzJlNWQyMzQwYzUzMWVlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rv2R5Z6ZMSi4S1IVQwNA9V490LqYDZEQnYw201FZv-w)

I have no `cppvsdbg`... 

I figured, since VSCodium as a fork of VSCode it [cannot be used with that](https://github.com/microsoft/vscode-cpptools/issues/4707) so i need to install actual VSCode.

**Comment by matheusmdx** [comment]
You can open in other IDE's too, you just need to pass this args to make godot bypass the project manager

**Comment by anderlli0053** [comment]
I used VSCODE and came up with the following terminal output and debug console outputs, then the Godot Freezed after it achieved 100% importing and stayed there for like 2 hours. The debugger was not paused it was still going.

![123](https://github.com/user-attachments/assets/42c297b3-9c7b-425d-8d40-e92aef70364d)


also this was the only **launch.json** combination that worked:

```
{
    "version": "0.2.0",
    "configurations": [
        {   
            
            "type": "cppdbg",
            "request": "launch",
            "name": "Launch Project",
            "program": "${workspaceFolder}/godot.windows.editor.dev.x86_64.exe",
            "args": ["--debug", "--editor", "--path", "C:\\Users\\ander\\Desktop\\Mrp"],
            "cwd": "${workspaceFolder}",
            //"stopOnEntry": false,
           // "console": "internalConsole",
            "preLaunchTask": "build"

        }
    ]
}
```



Here are the files, since the output is too big to paste in here:


[debug_console.txt](https://github.com/user-attachments/files/16719358/debug_console.txt)
[terminal_output.txt](https://github.com/user-attachments/files/16719359/terminal_output.txt)

**Comment by RadiantUwU** [comment]
We kinda needed a memory dump to be able to track all locals/variables everything inside the program. We need the EXE compiled with debug symbols alongside the memory dump to be able to properly see how it went wrong.

**Comment by RadiantUwU** [comment]
![image](https://github.com/user-attachments/assets/4e3835b6-6a30-4f8e-bdc6-fa624496db37)

You sure you got it to break on exceptions?

**Comment by RadiantUwU** [comment]
![image](https://github.com/user-attachments/assets/bff236d1-10c3-4be5-9f93-d654d0c0b2bc)
In the above screenshot it seems like you have not set it to do that.

**Comment by anderlli0053** [comment]
> ![image](https://private-user-images.githubusercontent.com/69520693/360711079-bff236d1-10c3-4be5-9f93-d654d0c0b2bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MDA2NTEsIm5iZiI6MTcyNDQwMDM1MSwicGF0aCI6Ii82OTUyMDY5My8zNjA3MTEwNzktYmZmMjM2ZDEtMTBjMy00YmU1LTlmOTMtZDY1NGQwYzBiMmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA4MDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTBkYmUwYTU2NTQyZmQwMmUyODA0YjExZDkyNTliOGE3YWFlZjk5MWZhNGU2NTM5ZjM3YjJkMzllYzgwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Du6_ZTirk0WIw8xRmkOWAzcBMIS8UWnr0xh9WInmAG4) In the above screenshot it seems like you have not set it to do that.

Oh, i did not see that... Thanks, i'll retry

**Comment by anderlli0053** [comment]
I have turned **All C++ Breakpoints** on and it did crash again, but where is the memory dump? it is not located in the **CWD (C:\Users\ander\Desktop\godotsrc\godot\bin)**  and neither in **%SystemRoot% (C:\\Windows)**

This are the outputs of a _debug console_ and _terminal_ from VSCode, from which i can see that there is access violation being made:

[debug_console.txt](https://github.com/user-attachments/files/16727963/debug_console.txt)
[terminal.txt](https://github.com/user-attachments/files/16727964/terminal.txt)

**Comment by anderlli0053** [comment]
I've ticked the **All C++ exceptions** and re-run it, it did crash again and here are the **dumps** and **debug_console** and  **terminal outputs**

[debug_console.txt](https://github.com/user-attachments/files/16728129/debug_console.txt)
[terminal.txt](https://github.com/user-attachments/files/16728130/terminal.txt)



DUMPS:

https://file.io/PQAC7IO7dakk

**Comment by RadiantUwU** [comment]
![image](https://github.com/user-attachments/assets/69efd961-8b20-44ee-b23a-7db12bdf798a)

**Comment by Saul2022** [comment]
I have the feeling this may be related to  https://github.com/godotengine/godot/issues/93587 as both seem big.

**Comment by anderlli0053** [comment]
> ![image](https://private-user-images.githubusercontent.com/69520693/360954387-69efd961-8b20-44ee-b23a-7db12bdf798a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjIyNDUsIm5iZiI6MTcyNDQyMTk0NSwicGF0aCI6Ii82OTUyMDY5My8zNjA5NTQzODctNjllZmQ5NjEtOGIyMC00NGVlLWIyM2EtN2RiMTJiZGY3OThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNmZkYWQyZGJkNzdlMGVmNjYzM2JhMWI5N2RjMjFlZWZjZGVjN2M1ZjU1NGJjODEzZjhmZGZmMTVhZDNkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ahFzujZ08ZpVYbB2Kv2gA_mU5UydVs5n_jaY0kAgOa8)

https://uploadnow.io/files/MDvnFH3

**Comment by Zireael07** [comment]
That site seems to require login

**Comment by anderlli0053** [comment]
What the hell?? I could normally download from all sites!!??

**Comment by Sauermann** [comment]
Closing as resolved according to the previous message.
