### ISSUE TITLE
Massiv Lag in editor when working with tile maps / tile map layers (Godot 4.3 stable release, Windows 11)

### ISSUE THREAD

**Issue by Brakatuta** [godotengine/godot#95942]
### Tested versions

- reproducable in godot 4.3 stable (the version i used, did not test in beta versions of 4.3)

### System information

Windows 11, Godot 4.3 (stable release), Components: intel i5 6600K, NVIDEA GEFORCE GTX 1060 6GB, Vulcan supported

### Issue description

I turned my Godot 4.2.2 stable project into a Godot 4.3 stable project following the recommended steps. This also included converting the old TileMap instances into TileMap layer instances using the extractor tool. When I was done extracting, I wanted to experiment a bit with these new TileMap layers.

However, when I try to interact with the TileMap layers (move them in the explorer, place or remove tiles, zoom in or out), the game engine freezes, crashes, or lags massively.

One thing I might want to add is that my game currently consists of multiple TileMaps with several layers (background, foreground, and so on). Before Godot 4.3, everything related to tiles worked perfectly fine.

Another thing I noticed is that even without converting the TileMaps to the new TileMap layer instances, the old TileMaps also lag massively when interacting with them. I had no lag at all in Godot 4.2.2 (the version I converted to Godot 4.3 stable) when working with TileMaps.

![Screenshot (464)](https://github.com/user-attachments/assets/e7723e5a-8f17-4fb2-b157-978fc66fd2f9)
![Screenshot (465)](https://github.com/user-attachments/assets/a034a316-1fed-49f6-9cc2-cda2d86ad12a)

### Steps to reproduce

I dont know if this realy is a problem of my machine only but here are my steps which produced it:
- first converting a larger 2d game to godot 4.3 (must have a lot of tilemaps)
- extract the tile map layers from the tilemaps
- interacting with the tilemap instances causes massiv lag, freezes or crashses

### Minimal reproduction project (MRP)

At this state i dont know if the problem is related to my specific engine or has something to do with the game engine itself

**Comment by kleonc** [comment]
Does it freeze only when the bottom TileSet/TileMap panel is shown? If yes, then it might be a duplicate of #72405.

**Comment by Brakatuta** [comment]
the visibility of the panels isnt necesary for the lag, i just need to select the tilemap / tilemap layer and it lags
i had this bug/problem in no other version

**Comment by KoBeWi** [comment]
> when it is related to the TileSets, why did everything work in Godot 4.2 smoothly

There were some changes to TileMap internals. TileSet was just a guess, the issue might be caused by scene layout or some other factors. It would be helpful if you could make a minimal project.

**Comment by Brakatuta** [comment]
alright i will post a minimal 4.3 version with only the tilemaps

**Comment by Brakatuta** [comment]
Another info: moving something in a scene in the editor while the scene has some tilemap/tilemap layer isntances creates lag (even if the scene is small)

**Comment by kleonc** [comment]
As mentioned:

> It would be helpful if you could make a minimal project.

Otherwise we can be pretty much only guessing.

**Comment by Brakatuta** [comment]
i tryed to solve it myself... anyways because i have rly no clue what could cause it i basicly attached the whole project (excluding android build)
the file is toom big so here is the link to the download: https://github.com/Brakatuta/Terra-Tales/releases/tag/tets

**Comment by Brakatuta** [comment]
the rellevant trouble makers are the scenes called test_level and prolog_level, both have a diffrent scene structure

**Comment by Brakatuta** [comment]
I found the problem: some files inside of  res\.godot\editor where broken. I deleted the folder and the project now runs smooth again
