### ISSUE TITLE
MultiMeshInstance3D completely broken LOD

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot#95948]
### Tested versions

Godot v4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 32.0.15.6081) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

MultiMeshInstance3D rendering of LOD is completely broken.
LOD selection changes randomly depending on the camera angle. In some cases, LOD level is reversed and results in increased detail the further away the node is from view.

### Steps to reproduce

Open the MRP and navigate the 3D viewport. The MultiMeshInstance3D is completely erratic LOD.
The MeshInstance3D control shows the same mesh resource with LOD working correctly.

### Minimal reproduction project (MRP)

[multimesh_lod_mrp.zip](https://github.com/user-attachments/files/16710877/multimesh_lod_mrp.zip)

![image](https://github.com/user-attachments/assets/3651dd89-a45a-43a6-a117-5091aad299a8)

**Comment by Calinou** [comment]
LOD in MeshInstance3D adjusts the LOD of all instances at once. To my knowledge, this is based on the distance between the camera and the MultiMeshInstance3D node's origin. I'm not sure if the AABB's size is taken into account (if it was, it would probably take the size of one instance into account, not the entire MultiMeshInstance3D's AABB).

**Comment by clayjohn** [comment]
Just a heads up, I think https://github.com/godotengine/godot/pull/92290 fixes this issue. I need to test it a bit more, but we should merge it for 4.4
