### ISSUE TITLE
Debugger does not open external text editor on error/breakpoint

### ISSUE THREAD

**Issue by immails** [godotengine/godot#95957]
### Tested versions

Reproducible in: 
- v4.3.stable.official [77dcf97d8]
- v4.3.rc3.official [03afb92ef]
- v3.6.rc.custom_build [b58d16f0b] (No code changes. Tested on other Windows machine)
- v3.6.rc1.official [cfc4a0eff] (Tested on other Windows machine)

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Mobile) - integrated AMD Radeon(TM) Vega 8 Graphics (Advanced Micro Devices, Inc.; 31.0.21916.2) - AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Debugger does not open the script in the external editor, but in internal. This causes conflicts with the Internal Editor and External Editor (e.g. Godot's Internal Editor discards changes made in External Editor). Tested with External Editors such as VSCodium or Visual Studio Code. I believe this is not intended behavior and is an error.

Here's the visual example:

https://github.com/user-attachments/assets/8d3156fd-1db5-43c7-927d-7821a7f4e48e

### Steps to reproduce

0. Use any project or create a new one (does not depend on project)
1. Set `text_editor/external/use_external_editor` to **True** and `text_editor/external/exec_path` to _desired text editor_ in Editor Settings.
2. Define a breakpoint or make an error in some script.
3. Start the scene with the script. (At this point Godot Editor already opens the problematic script in the **Internal Editor**)
4. Click on the stack frame. (Editor opens this script in the **Internal Editor**. Expected **External Editor**!)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Have you [enabled this](https://docs.godotengine.org/en/stable/tutorials/scripting/debug/overview_of_debugging_tools.html#script-editor-debug-tools-and-options)?

**Comment by immails** [comment]
> Have you [enabled this](https://docs.godotengine.org/en/stable/tutorials/scripting/debug/overview_of_debugging_tools.html#script-editor-debug-tools-and-options)?

No. But **this fixes the issue**. I'm sorry
