### ISSUE TITLE
Problem when try to use font with distance field.

### ISSUE THREAD

**Issue by kubaxius** [godotengine/godot#9595]
**Operating system or device - Godot version:**
2.1.3

**Issue description:**

Bug shows up when I try to load the same font second time in the same scene, for example to use it in label. After starting the game everything turns white, and one error pops up: "No loader found for resource: res://...". Adding something that updates constantly (like a particle emitter) "hides" the bug, just like turning off "Distance Field" on font.

**Steps to reproduce:**
1. Import font with distance field
2. Add two labels to your scene
3. Change labels font to that imported at the beginning
4. Write something in the labels
5. Run the project

**Link to minimal example project:**

[example.zip](https://github.com/godotengine/godot/files/1136860/example.zip)

**Comment by eon-s** [comment]
I've got this bug on 2.1.2 on a complex scene but was unable to find what was causing it. 

Turning visibility off on the parent does not hide the bug either, is the element containing the text the one that needs to be disabled (weird).

This affects 2.1.4b too, I was unable to make this happen on 3 but will need a better test (I'm not sure if I understand how fonts work on 3).

**Comment by Calinou** [comment]
Can anyone still reproduce this on 3.2beta3 or later? If so, please upload a minimal reproduction project and link it here.

**Comment by eon-s** [comment]
Here is the converted project from the OP but does not show any problem
Fonts are not imported the same way so it may not be possible to reproduce the error on 3.2+ anymore.

[dffbug.zip](https://github.com/godotengine/godot/files/3935603/dffbug.zip)

**Comment by Calinou** [comment]
@eon-s Thanks for providing an updated project :slightly_smiling_face: I'll close this as resolved then.
