### ISSUE TITLE
Sprite3D and ImmediateGeometry doesn't show any geometry

### ISSUE THREAD

**Issue by Sipaha** [godotengine/godot#9596]
**Operating system or device - Godot version:**
OS: Windows 10
Version: last build from master

**Issue description:**
Sprite3D and ImmediateGeometry render doesn't work

**Steps to reproduce:**
1. Create new project
2. Add Sprite3D to scene
3. Add texture to sprite

**Example project**
[Test3d.zip](https://github.com/godotengine/godot/files/1137033/Test3d.zip)

**Comment by TwistedTwigleg** [comment]
I've also had this issue with Sprite3D and AnimatedSprite3D in Ubuntu Linux
