### ISSUE TITLE
Area2D node not detecting StaticBody2D nodes entering it

### ISSUE THREAD

**Issue by DustyBagel** [godotengine/godot#95963]
### Tested versions

-v4.2.2.stable.official [15073afe3]
-v4.3.stable.official [77dcf97d8]

### System information

Windows 11 home x64 Godot v4.3 and v4.2.2 Forward+

### Issue description

The Area2D node isn't detecting when a StaticBody2D node is entering its CollsionShape2D node. For some reason, it will detect it if the Area2D node is being moved or if the monitoring property is flipped on and off in which case it works for a very short time. The Area2D node is still able to work with the AnimatableBody2D and CharacterBody2D nodes.

### Steps to reproduce

See MRP Below. This should be very self-explanatory.

### Minimal reproduction project (MRP)

[collsion_test.zip](https://github.com/user-attachments/files/16719577/collsion_test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/17238 and https://github.com/godotengine/godot/issues/74300.
