### ISSUE TITLE
popupmenu/optionbutton:about word distortion of item

### ISSUE THREAD

**Issue by eeyzs1** [godotengine/godot#95966]
### Tested versions

4.3 stable

### System information

Godot v4.3.stable (41b17e249) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

The words in items of popupmenu/optionbutton was distorted when compare with words in other nodes with same font size
like the below image showed:
![popupmenu word](https://github.com/user-attachments/assets/e9fa5091-78c7-4ac8-ac37-2acd1bb26e75)

as showed in this picture, the 1920x1080 in the popup item is distorted when compare with the 1918x1078 in the button

### Steps to reproduce

2 ways:
1. got an OptionButton and add items with texts, then change the selected of OptionButton
2. add one PopupMenu, add item then text, and add another node like label with text, then compare

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/54030.
