### ISSUE TITLE
Unexpected Screen Depth behaviour on macOS

### ISSUE THREAD

**Issue by aristides86** [godotengine/godot#95970]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

MacOS 14.5

### Issue description

The depth calculations work as expected on Win10, but porting on Mac I'm getting this behaviour. The problem seems to be with color blending based on screen depth and camera angle.
![image](https://github.com/user-attachments/assets/c06816c9-8dc1-4f0b-b22c-105a2c34e948)

### Steps to reproduce

Open the attached project

### Minimal reproduction project (MRP)

[DepthTest.zip](https://github.com/user-attachments/files/16720692/DepthTest.zip)

**Comment by Calinou** [comment]
Can you test 4.3 which uses [reverse Z](https://godotengine.org/article/introducing-reverse-z/)? Note that you will need to change your shader code a bit to accomodate for this change, as described in the link.

You could also test 4.4.dev1 once it's released as it'll have native Metal support, so it will no longer need to run Forward+/Mobile through MoltenVK.

**Comment by aristides86** [comment]
Thank you. So I have ported the project to 4.3 and modified the shader for it to work as it should, however the problem is still there. I'm getting different results in Win vs Mac. I have Apple M1 chip on mine.

**Comment by Calinou** [comment]
@aristides86  Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:

**Comment by aristides86** [comment]
No, I just modified the shader to look right on macOS. I'm not sure if shaders are supposed to behave in the same way on Win and Mac, or is there some math that works differently and hense gives different results. So developers are supposed to tweak the project when porting to apple system.

**Comment by Calinou** [comment]
> So developers are supposed to tweak the project when porting to apple system, in which case it's not a bug.

What did you have to tweak in the shader? Could you post a code sample here?

**Comment by aristides86** [comment]
Line 162
`float foam_mix = clamp(pow((1.0 - (depth + VERTEX.z) + foam_noise), 8.0), 0.0, 1.0);`
becomes
`float foam_mix = clamp(pow((0.25 / (depth + VERTEX.z) + foam_noise), 8.0), 0.0, 1.0);`

0.25 is now a variable that controls the amount of foam. I have now migrated to 4.3 and shader is different, this one change is only to make it work in 4.2. As seen on the top screenshot, for some reason on macOS it also takes into account distant depth as well as shallow depth to calculate the amount of foam.
