### ISSUE TITLE
HTTPRequest.set_tls_options to TLSOptions.client_unsafe() isn't working anymore in Godot 4.3

### ISSUE THREAD

**Issue by D2klaas** [godotengine/godot#95988]
### Tested versions

reproducible in Godot 4.3
not reproducible in Godot 4.2.2

### System information

Window 10

### Issue description

HTTPRequest.set_tls_options( TLSOptions.client_unsafe() ) should disable TLS handshake validation.
But when calling a Server with a self signed certificate the error "E 0:00:02:0815   _do_handshake: TLS handshake error: -9984
  <C++-Quelle>   modules/mbedtls/stream_peer_mbedtls.cpp:89 @ _do_handshake()" appears.

That wasn't so ingodot 4.2.2

### Steps to reproduce

```
extends HTTPRequest

func _ready() -> void:
	var opts =  TLSOptions.client_unsafe()
	print("Unsafe:", opts.is_unsafe_client())
	set_tls_options( opts )
	request("https://URL_TO_UNSAFE_SERVER", [], HTTPClient.METHOD_POST, "")
```

### Minimal reproduction project (MRP)

[issue.zip](https://github.com/user-attachments/files/16728945/issue.zip)

**Comment by Faless** [comment]
Fixed in https://github.com/godotengine/godot/pull/96172 , see https://github.com/godotengine/godot/issues/96170 for details.
