### ISSUE TITLE
Subviewport's render_target_update_mode keep setting itself to Always

### ISSUE THREAD

**Issue by depmots** [godotengine/godot#95985]
### Tested versions

- Reproductible in 4.3 stable

### System information

Godot v4.3.stable - macOS 14.5.0 - Vulkan (Mobile) - integrated Apple M1 Pro - Apple M1 Pro (10 Threads)

### Issue description

`render_target_update_mode` keep setting itself to `Always`. If I change it to `When Visible`, save and reload the project, it's back to `Always`

<img width="547" alt="image" src="https://github.com/user-attachments/assets/3b269aad-75bf-47c4-8a00-9bc0e3e26629">

### Steps to reproduce

Create a scene, Add a Control node, add a SubviewportContainer as a child and a SubViewport as a child of that container.
Then change the update mode (or leave it at `When Visible`), then reload the project and the Update Mode will have set itself to `Always` 

### Minimal reproduction project (MRP)

[MMR.zip](https://github.com/user-attachments/files/16726237/MMR.zip)

**Comment by AThousandShips** [comment]
This is handled by the container and is probably something to document rather than a bug

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/23729

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by depmots** [comment]
Thanks for clarifying!
