### ISSUE TITLE
Argument hint does not appear

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#95986]
### Tested versions

Broken 4.4 dev a1acd38
Works 4.3 stable

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/user-attachments/assets/29faeb75-96d5-489c-bc30-73f3851960f4

While in stable:

https://github.com/user-attachments/assets/9374e893-cf5f-4b44-a8d7-44529eb084d4

### Steps to reproduce

1. Open script editor
2. Type some method name
3. The argument list does not appear

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Strange, im using the same version and the editor show the args normally

https://github.com/user-attachments/assets/36cc0a4c-11be-48c0-b71c-3b09eaaad784

<br>

Can you show the entire code? Maybe is like #92226 that happens in specific cases depending on the code position.

**Comment by b3lon9** [comment]
Hi @KoBeWi 
If you are stuck and can not find a solution but need to develop quickly,
I recommend trying out different tools.
You could work on your script in VSCode.
It has various plugins available, including 'Copilot' and 'gdscript', which might be helpful.

I hope this suggestion helps!
Thanks!

**Comment by HolonProduction** [comment]
I can't reproduce as well on v4.4.dev.custom_build [e3550cb20], would be great if you shared the script.

On a different node could you see whether the regression stems from #94082 (0abd0ae3641bc121451acdc99cf268ded0de96ce).

**Comment by KoBeWi** [comment]
It's because I have `text_editor/completion/auto_brace_complete` disabled. I get the hint when I add closing brace.
![image](https://github.com/user-attachments/assets/9788fbcc-1219-480f-a959-f932f2c60403)
![image](https://github.com/user-attachments/assets/5611dc11-6aec-4c51-8998-82e72391e173)
