### ISSUE TITLE
The latest version(Godot_v4.3-stable_win64) causes the Windows IME to crash frequently

### ISSUE THREAD

**Issue by acccccccb** [godotengine/godot#96001]
### Tested versions

Godot_v4.3-stable_win64

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.3889) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 Threads)

### Issue description

- When I run Godot_v4.3-stable_win64, the Godot interface will become unresponsive every 1-2 minutes, and the IME icon of the windows system tray will change to (x), and it will return to normal after about 10~20 seconds. 
- During this time, I recorded a sharp rise in the CPU temperature
- Godot_v4.2.2-stable_win64 does not have this problem

***********

- 当我运行Godot_v4.3-stable_win64时，每隔大约1~2分钟，godot界面将会失去响应，同时系统托盘的windows输入法图片变更为(x)，大约十几秒后恢复正常，在此期间，我记录到cpu温度急剧上升。

- Godot_v4.2.2-stable_win64没有这个问题

### Steps to reproduce

just run Godot_v4.3-stable_win64 on windows11 and wait 1~2 mins

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
This was likely fixed already by #95849, which will be in 4.3.1.
