### ISSUE TITLE
Run problem in 4.3 

### ISSUE THREAD

**Issue by GomaaDevs** [godotengine/godot#96004]
### Tested versions

since 4 version i can´t run projects using forward+ or movil mode, i have a Dell E5440 12 gb ram, intel core i5, windows 11.

i want run Godot 4.3 using dx12 because of no vulkan support en my laptop but i dont know what to do, no open editor, just can run using the compatibility mode.

Can you help me?

### System information

Windows 11 - Intel Core i5 - No Vulkan Support

### Issue description

since 4 version i can´t run projects using forward+ or movil mode, i have a Dell E5440 12 gb ram, intel core i5, windows 11.

i want run Godot 4.3 using dx12 because of no vulkan support en my laptop but i dont know what to do, no open editor, just can run using the compatibility mode.

Please... Can you help me?

### Steps to reproduce

i select forward+ or movil mode option and i can´t run editor

### Minimal reproduction project (MRP)

directory is create but no run

**Comment by matheusmdx** [comment]
First of all, github is only for technical reports like bugs, to ask question you can use [godot forum](https://forum.godotengine.org/) or [godot reddit](https://www.reddit.com/r/godot/).

<br>

For enable directx12 you need to compile the engine with directx enabled, all the steps for do that can be found in these links:

https://docs.godotengine.org/en/stable/contributing/development/compiling/introduction_to_the_buildsystem.html
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_windows.html#compiling-with-support-for-direct3d-12

**Comment by octanejohn** [comment]
4.3 doesnt need a custom build to use dx12, u change the windows driver from vulkan to dx12 in the godot menu

https://godotengine.org/releases/4.3/#display

also your laptop gpu doesnt support dx12 shader model 6.0, you can switch to linux to use vulkan or stay with compatibility mode

https://www.techpowerup.com/gpu-specs/hd-graphics-4400.c2470

**Comment by AThousandShips** [comment]
Closing from the above
