### ISSUE TITLE
Left click not working correctly after scroll and click outside PopupMenu 

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#96008]
### Tested versions

Godot v4.3.stable 
Godot v4.1.2.stable 

### System information

Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) 

### Issue description

Left click not working correctly after scroll and click outside PopupMenu. Hover works.

[Screencast_20240823_223826.webm](https://github.com/user-attachments/assets/f534a6f4-bf7b-4c28-b4b1-fec13dab69d3)

If you right click again and then click outside without scrolling first it goes back to normal. Or if you use scroll wheel up/down again it also goes back to normal.

Could not recreate this issue on Windows or with single window mode on
 

### Steps to reproduce

Open a PopupMenu
Scroll outside the popup and then click outside
Try to click on any other control in the editor

### Minimal reproduction project (MRP)

N/A

**Comment by Hilderin** [comment]
I'm able to reproduce on Godot v4.3.stable - Ubuntu 23.10 23.10 - Wayland - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL-N) - Intel(R) N100 (4 Threads)

To reproduce, I need to use the mouse wheel on the popup menu and outside the popup menu before trying to click elsewhere.

This PR seems to fix this problem: #95044
I tried with the artifact of the PR, if you want to test it @Giganzo: https://github.com/godotengine/godot/actions/runs/10518622500/artifacts/1845227344

**Comment by Giganzo** [comment]
Yeah, seems like it fixes the issue
