### ISSUE TITLE
Scene Thumbnails not correct after saving, problem for devs with trouble reading; accessability bug.

### ISSUE THREAD

**Issue by GeminiSquishGames** [godotengine/godot#96015]
### Tested versions

Currently an issue in 4.3 but has been like this for a while in 4.x.

### System information

Windows 10 

### Issue description

Thumbnails for scenes don't save correctly in the File system. I rely more on the thumbs since I have dyslexia and can see the item much faster than I can often read things, especially when I try to order things by type and they share a common first name or the same name in many places. The problem I'm having is they don't save from the origin point and seem to try using the viewport but not in the center, so I have to re-position the editor viewport if I want a good thumbnail, but they also often save a thumb from a different scene entirely or are getting them confused in the cache maybe. It may not be a problem for many devs but it would be nice to have this as I always have my thumbs on to tell what something is as it works almost instantly for me.

### Steps to reproduce

Observe the scene thumbnails that are created on save in any project in a scene that has visually descriptive content and you can see how they save.

### Minimal reproduction project (MRP)

This should be present in any project and observed by watching the FileSystem dock as you save scenes.

**Comment by AThousandShips** [comment]
Thank you for your report, consolidating in the relevant proposal as this is not a bug:
* https://github.com/godotengine/godot-proposals/issues/7232
