### ISSUE TITLE
Can't build android templates (open_xr error)

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#96019]
### Tested versions

- reproduced in
v4.3.stable.official [77dcf97d8]

### System information

Ubuntu 22.04.4 LTS, GTX1060 6GB, NVIDIA 535.183.01, Compatibility mode

### Issue description

can't build android templates with disabled `open_xr` module, both arm32 and arm64 fails with following:

```console
[100%] progress_finish(["progress_finish"], [])
[100%] Linking Shared Library bin/libgodot.android.template_debug.arm64.so ...
ld: error: undefined symbol: XRServer::get_xr_mode()
>>> referenced by java_godot_lib_jni.cpp
>>>               platform/android/java_godot_lib_jni.os:(Java_org_godotengine_godot_GodotLib_step)
>>> referenced by java_godot_lib_jni.cpp
>>>               platform/android/java_godot_lib_jni.os:(Java_org_godotengine_godot_GodotLib_step)
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/libgodot.android.template_debug.arm64.so] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:14.21]
```

### Steps to reproduce

compile android templates with following:
```console
scons platform=android arch=arm64 target=template_debug generate_apk=yes build_profile="game.build"
```

game.build
```json
{
	"disabled_build_options": {
		"disable_2d_physics": true,
		"disable_3d": true,
		"disable_3d_physics": true,
		"disable_navigation": true,
		"openxr": false,
		"vulkan": false
	},
	"disabled_classes": [
	],
	"type": "build_profile"
}
```

### Minimal reproduction project (MRP)

- n/a

**Comment by matheusmdx** [comment]
Bisecting points to #94799 as the culprit, @m4gr3d

![image](https://github.com/user-attachments/assets/f28c714d-c40e-43d1-87b5-f2330f5d8f00)

**Comment by akien-mga** [comment]
> ### Tested versions
> 
> * reproduced in
> v4.3.stable.official [[77dcf97](https://github.com/godotengine/godot/commit/77dcf97d82cbfe4e4615475fa52ca03da645dbd8)]

For the record, please make sure the version you list is accurate. Two regression reports you filed were actually only affecting the `master` branch (4.4) but were reported as affecting 4.3.stable, so I've spent some time unnecessary trying to cherry-pick those PRs to 4.3 and failing.
