### ISSUE TITLE
Top part of application hidden by the window title bar

### ISSUE THREAD

**Issue by MRFaria** [godotengine/godot#9601]
**Operating system or device - Godot version:**
Dell XPS - WIndows 10
Steam version of Godot

**Issue description:**
Since this morning Godot starts with this issue where the menu bar, run button and other things are hidden by the application/window title bar. My resolution is 1920x1080

**Link to minimal example project:**

**Comment by eon-s** [comment]
If the graphics card is Intel, this may be duplicate of #8902

**Comment by MRFaria** [comment]
Ah sorry, didn't see that. In fact it is the same graphics card

**Comment by akien-mga** [comment]
Closing as duplicate of #8902 then. Sounds like Intel released buggy drivers on Windows 10...
