### ISSUE TITLE
2D Particles jitter when physics interpolation is enabled.

### ISSUE THREAD

**Issue by Playersaturn0** [godotengine/godot#96022]
### Tested versions

All of 4.3 dev releases and 4.3 STABLE

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 5500 (12 Threads)

### Issue description

Adding a 2D particle to a scene (both GPUParticle2D and CPUParticle2D), either atached to a moving node or moving by itself and enabling physics interpolation in the project settings makes the particles move in a jittery way.

https://github.com/user-attachments/assets/51942c7f-6ed5-49ba-b1bf-876928277866

### Steps to reproduce

Add a 2D particle to the scene, either a gpu or a cpu particle, make it move around and enable Physics Interpolation, to use the example simply run it.

### Minimal reproduction project (MRP)

[jitter-problem.zip](https://github.com/user-attachments/files/16734918/jitter-problem.zip)

**Comment by Mickeon** [comment]
Oooooh, nasty. CC @rburing

**Comment by rburing** [comment]
Physics interpolation for 2D particles is not implemented yet in `master`, but it is planned. For now, you can turn off physics interpolation for the particular node by setting `physics_interpolation_mode = PHYSICS_INTERPOLATION_MODE_OFF`; in the inspector it's near the bottom, under Node > Physics Interpolation > Mode, set it to Off.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/92006.
