### ISSUE TITLE
spatial Shader working in 4.2.2 but not 4.3

### ISSUE THREAD

**Issue by CaelRowley** [godotengine/godot#96039]
### Tested versions

Reproducible in v4.3 but not in v4.2.2

### System information

Windows 11 - Godot v4.3 - Vulkan (Forward+) - dedicated

### Issue description

I am using a shader based on StayAtHomeDev water shader: https://godotshaders.com/shader/water-shader/
This is applied to a MeshInstance3D with a QuadMesh on it.

In Godot 4.2.2 this shader is working to create water, but in 4.3there are some issues. There is no error in the console, only visual errors you apply the shader.

### Steps to reproduce

Just view the scene in the editor in 4.3 and 4.2.2

### Minimal reproduction project (MRP)

https://github.com/CaelRowley/godot-shader-error

**Comment by arkology** [comment]
Shader code should be changed due to reverse z (https://godotengine.org/article/introducing-reverse-z/)

**Comment by CaelRowley** [comment]
@arkology ok thanks for the link, I was searching the change logs to see if they altered shaders and couldn't find anything and I didn't get any warning about the breaking change like the article describes, but I should be able to fix it now, thanks!
