### ISSUE TITLE
Godot 4.3 Web Export: CPU and GPUParticles2D do not render with default shader

### ISSUE THREAD

**Issue by a-soulspark** [godotengine/godot#96030]
### Tested versions

- Reproducible from 4.3.dev6 to 4.3.stable (tested with the Godot web editor)

### System information

Godot v4.3.stable - Web - GLES3 (Compatibility) - WebKit WebGL -  (2 Threads)

### Issue description

In the specified Godot 4.3 versions, CPUParticles2D and GPUParticles2D nodes' particles do not render at all on web export, unless given a shader that overrides their COLOR. For example, this would suffice to fix it:

```c
shader_type canvas_item;

void fragment() {
	COLOR = texture(TEXTURE, UV);
}
```

### Steps to reproduce

1. Create a new project
2. Add CPUParticles2D node
3. Export to web
4. They should not render

If you use the web editor, you can even skip step 3. as the particles won't show up in the editor's viewport anyway.

### Minimal reproduction project (MRP)

N/A

**Comment by a-soulspark** [comment]
On a further note, it seems like the shader I specified above is not a full workaround: the particles appear without coloring, even on desktop.

On PC, a variation of this shader can fix the lack of coloring, by obtaining the color information in the vertex shader:
```c
shader_type canvas_item;

varying vec4 MODULATE;

void vertex() {
	MODULATE = COLOR;
}

void fragment() {
	COLOR = texture(TEXTURE, UV) * MODULATE;
}
```
However, this causes the particles to become invisible on web again, so I tried a variation of this shader that only copies the color information's RGB channels:

```c
// snip

void fragment() {
	vec4 textureColor = texture(TEXTURE, UV);
	COLOR.rgb = textureColor.rgb * MODULATE.rgb;
	COLOR.a = textureColor.a;
}
```
This version renders on PC, though of course it lacks the alpha value from the particle color.

On web, they now also render, though their color information appears to be wrong: **the green channel appears to be constantly zero** (white particles show up magenta on web, and yellow particles show as red)
My theory is that not just the green channel, but also the alpha channel is also constantly zero, which would explain why the particles are invisible with the default shader.

**Comment by Maran23** [comment]
Maybe related to https://github.com/godotengine/godot/issues/95797

**Comment by akien-mga** [comment]
Seems to be the same as #95797 indeed, consolidating there.

**Comment by ZenRepublic** [comment]
Same issue with iOS web builds (tested an android web build as well, particles look all good there)
