### ISSUE TITLE
TrueType Font Rendering Artifacts

### ISSUE THREAD

**Issue by MartinHaeusler** [godotengine/godot#96042]
### Tested versions

- Reproducible in: 4.2.2.stable
- Reproducible in: 4.3.stable

### System information

Godot v4.2.2.stable (15073afe3) - Linux Mint 22 (Wilma) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 (nvidia; 535.183.01) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I'm facing some issues with TrueType font rendering in my game. I'm seeing some weird artifacts which are not part of the font. Here's what it looks like in the editor and in the game:

![image](https://github.com/user-attachments/assets/9666760c-eb1c-43dd-a06d-8105d6139bb0)

... and here's what the icons *should* look like (in this case I'm using LibreOffice Writer):

![image](https://github.com/user-attachments/assets/feb9c5b0-e155-44b3-be4d-710fd27eaef0)

Note the "bleeding" on the sword hilt and the weird dots at the center and lower left corner of the heart. 

I already tried to disable the font outline in godot, but the issue persists even without the outline. It also makes no difference if I use a `Label2D` or a `Label3D`, the issue is the same.

I've noticed that this issue seems to be linked *somehow* to the underlying Operating System. I tested the same project on an older Linux Mint, and there it worked nicely. But that doesn't really make sense because the fonts work as intended when I use them on my current OS in LibreOffice...

Any clues? 

### Steps to reproduce

If anyone wants to replicate this, here are the fonts (you can also grab the files directly from the minimal reproducer attached below):

- the sword is from RpgAwesome: https://nagoshiashumari.github.io/Rpg-Awesome/
- the heart is from FontAwesome: https://fontawesome.com/

I've imported the TTF files into godot, created a combined font (regular TTF font as base with the aforementioned ones as fallbacks), and copied the glyphs into a `Label3D`.

### Minimal reproduction project (MRP)

[ttfReproducer.zip](https://github.com/user-attachments/files/16737832/ttfReproducer.zip)

Open the `testScene.scn` and you should see the `Label3D`.

**Comment by bruvzg** [comment]
You have MSDF enabled for the fonts, this type of artifacts happen when font has self intersection.

**Comment by MartinHaeusler** [comment]
@bruvzg interesting, I didn't know that. Some online forum post recommended enabling MSDF to improve 3D font rendering when the label is further away from the camera. So should I simply disable MSDF again?

**Comment by bruvzg** [comment]
> Some online forum post recommended enabling MSDF to improve 3D font rendering when the label is further away from the camera. So should I simply disable MSDF again?

MSDF is better for 3D, but it's picky about the fonts. The options are either disable it, use a different font, or edit the outlines in the font to remove intersections.

**Comment by MartinHaeusler** [comment]
I see. I guess I'll disable it for the time being. Thanks for the insights!

**Comment by Calinou** [comment]
Closing, as this is already documented in https://docs.godotengine.org/en/latest/tutorials/ui/gui_using_fonts.html#doc-using-fonts-msdf

The main issue is tracked in https://github.com/godotengine/godot/issues/61207.
