### ISSUE TITLE
Vulkan: Godot Engine 4.4.dev crashes on startup on Windows

### ISSUE THREAD

**Issue by Hilderin** [godotengine/godot#96057]
### Tested versions

Reproductible on custom build master 364f916f3f0141c247e32e63624b063905d66b02 #90993 @darksylinc
Not reproductible with the commit just before: 6e9bcc0f18becbed199ad48d3dec01621dc39237 

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Build Godot and start it, it will crash when loading a project.
![image](https://github.com/user-attachments/assets/cceca289-bbe7-4e9f-a670-be294262d89c)

### Steps to reproduce

Build using `scons p=windows target=editor` or using Visual studio 2022 with project generated with `scons platform=windows vsproj=yes dev_build=yes`.
Just start the compiled version in debug or directly with the .exe and load an empty project. Godot editor will crash when loading the project.

The problem is just reproductible on my laptop. It's not reproductible on my desktop computer: Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6070) - 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz (12 Threads)

### Minimal reproduction project (MRP)

Any empty project.

**Comment by huwpascoe** [comment]
Best rename the issue to something like: HeapFree crashes on master branch

**Comment by darksylinc** [comment]
Duplicate of #95967.

We didn't know it was happening on Windows too, but it's not fully surprising given that it appears the problem could be in the Vulkan Loader.

It will be fixed by #96044

**Comment by Hilderin** [comment]
Thanks, I'm closing this issue since it's a  duplicate.
