### ISSUE TITLE
Audio samples leaks

### ISSUE THREAD

**Issue by blam23** [godotengine/godot#96068]
### Tested versions

- Reproducible in 4.3-stable, 4.3beta2, and 4.3beta3
- Does not occur in 4.3beta1, or 4.2.2-stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Playing an AudioStream in a web build in 4.3 causes objects to be created that are not freed. A windows build of the same code doesn't cause the same leaks. I could not reproduce this with 4.3beta1, only the release 4.3 build (v4.3.stable.official [77dcf97d8]).

In games with lots of audio, this will lead to an eventual crash when the object count gets too high for the wasm/webgl buffer code to handle.

### Steps to reproduce

Create any kind of AudioStream node, and call `play` on it.
On web, the object count goes up and never goes back down. Check using `Performance.OBJECT_COUNT`.

### Minimal reproduction project (MRP)

MRP: [web-leak-repro.zip](https://github.com/user-attachments/files/16740338/web-leak-repro.zip)

I've uploaded this to itch here with debug symbols and gdscript as text: https://blambear.itch.io/godot-web-audio-leak-bug the password is `godot`.

You can see the object count keep going up and up.

(Note the pop.mp3 file in here is an audio file I recorded, it's MIT licensed)

**Comment by blam23** [comment]
Examples below of crash error output when the object count gets too high, for me this happens when the object count hits around 50k.

## Firefox
![image](https://github.com/user-attachments/assets/17eb672d-980c-4946-a2f9-ba2c0456be41)

> Uncaught TypeError: WebGL2RenderingContext.bufferData: Argument 2 can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB

## Chrome
![image](https://github.com/user-attachments/assets/ad668a07-1838-4bdc-87e9-9554d91aec21)

> index.js:474 USER ERROR: Parameter "mem" is null.
> index.js:474 USER ERROR: Out of memory

**Comment by blam23** [comment]
Tried with 4.3beta2 and 4.3beta3, both seem to reproduce the issue with the object count going up and up. So it seems the issue was introduced between beta1 and beta2.

**Comment by akien-mga** [comment]
4.3-beta2 is the release where audio sample playback was added for the web platform, so that's probably where the bug originates.

**Comment by wheatear-dev** [comment]
> 4.3-beta2 is the release where audio sample playback was added for the web platform, so that's probably where the bug originates.

I can reproduce on 4.3-beta1 😅 

My specs:

- MacOS Sonoma `14.6.1 (23G93)`
- Chrome `Version 128.0.6613.85 (Official Build) (arm64)`

The only possible confounding variable is that I exported all 3 tested betas (1, 2, and 3) from 4.3-stable.

https://github.com/user-attachments/assets/8cb10e92-ddad-4687-9eaf-5e36d58bd7f8

**Comment by akien-mga** [comment]
> The only possible confounding variable is that I exported all 3 tested betas (1, 2, and 3) from 4.3-stable.

This isn't supported, you'd be mixing incompatible binaries and JS code.

Please make sure to use the same editor version as the export templates you're using.

**Comment by RainbowCemetery** [comment]
changing the audiostreamplayer playback type to sample has the same leaked object behavior when run in the editor

**Comment by blam23** [comment]
Just for reference, I've uploaded versions exported from 4.3-beta1 and 4.3beta-2 to itch.io:

https://blambear.itch.io/web-leak-test-4-3-beta1
https://blambear.itch.io/web-leak-test-4-3-beta2

Password for both is again `godot`.

On my machine, in Firefox (131.0a1) and Chrome (128.0.6613.86), I get a stable object count in beta1 and a consistently increasing object count in beta2.

**Comment by wheatear-dev** [comment]
I can reproduce this, using the first of the two itch.io links (`4.3-beta1`), on Safari for both macOS and iOS.

Chrome does _not_ reproduce for this version, for me, on macOS.

https://github.com/user-attachments/assets/964b961a-2bf4-456d-9b3f-b1027fc35e60

**Comment by wheatear-dev** [comment]
Okay `git-bisect` took a while! 😅 

Good luck everyone, it's a big diff! 😌 

```
52fa4f05f3945fdf511c249adede9b6d07c51beb is the first bad commit
commit 52fa4f05f3945fdf511c249adede9b6d07c51beb
Author: Adam Scott <ascott.ca@gmail.com>
Date:   Thu Apr 18 10:50:34 2024 -0400

    Add samples playback support
```

<details>
  <summary>Methodology</summary>

  ## Steps
  - Enable _autoplay_ always `alias ogc='open -a Google\ Chrome --args --autoplay-policy=no-user-gesture-required'`
  - Build both MacOS editor and Web template_debug each time
  - Manually export
  - Open chrome (`ogc` alias), and confirm presence/absence of bug
  
  ## Observations:
  - Only “bad” revisions seem to play sound at all?!
  - Before force enabling _autoplay_:
      - all locally built revisions would apparently demonstrate this memory leak
      - even those that were "good" when I tried again
      - but stop on a mouseclick (and maybe other interactions)
  - Something _else_ is going on with Safari 🤔
      - it broke a lot earlier, at or before `4.3-beta1` 
</details>

**Comment by adamscott** [comment]
@wheatear-dev Yes, it's when I added samples support. I'll investigate this beginning of next week.

**Comment by adamscott** [comment]
#96572 should fix this issue. Now, the MRP's object numbers stay stable, whether the game runs on a desktop (with samples forced) or on the Web.

**Comment by PureAsbestos** [comment]
This is a pretty serious bug with 4.3, will it be cherry-picked for a patch?

**Comment by blam23** [comment]
This is in 4.4.dev2, tested and it's fixed for me.

**Comment by thedinosoar** [comment]
I think think may still be an issue, I just experienced the same thing. Trying to reproduce and will update if it's not just a fluke
