### ISSUE TITLE
Weblate has conflicting entries for Chinese (Hong Kong): zh_HK and zh_Hant_HK

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#9606]
**Issue description:**
I continue to translate godot for zh_HK and I don't know why there is now a Chinese(Hong Kong), if I click on zh_HK, it redirects me to https://hosted.weblate.org/projects/godot-engine/godot/zh_Hant_HK/ which has 0% translation. I have no idea how weblate handles locale and stuff. Could someone please tell me how to fix it, should I delete one and continue the translation?
![2017-07-11 21 27 10](https://user-images.githubusercontent.com/10883749/28070514-c4153efa-667f-11e7-8805-9f9cf48870ba.png)

**Comment by akien-mga** [comment]
Maybe @nijel from the Weblate team could help shed some light about it, it seems the classical `zh_{CN,HK,TW}` was obsoleted and modified recently to use instead `zh_{Hans,Hant{,_HK}}`: https://github.com/WeblateOrg/weblate/commit/189401fb9dc82158d36362cd5516191889dba5ce
But somehow `zh_HK` is still there and adds conflicting names.

**Comment by nijel** [comment]
Sounds like a bug - the old code should not be used at all in the Weblate UI (it can be still used in the source code and Weblate should map it to new ones for UI).

**Comment by akien-mga** [comment]
Thanks! Should I move this to an issue on https://github.com/WeblateOrg/weblate then?

**Comment by nijel** [comment]
Should be fixed on Weblate side now. I've also removed (not translated) zh_Hant_HK.po from the Weblate repo.

**Comment by akien-mga** [comment]
Thanks a lot!
