### ISSUE TITLE
Re-importing font causes `Parameter "fd" is null` error.

### ISSUE THREAD

**Issue by em-s-h** [godotengine/godot#96073]
### Tested versions

- Reproducible in: Godot v4.3.stable
- Not reproducible in: Godot v4.2.stable

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 - Wayland - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 Threads)

### Issue description

Whenever I re-import the font I'm using in my project 700+ ```Parameter "fd" is null``` errors show up in the console.

### Steps to reproduce

Simply opening the MRP should trigger the bug, otherwise re-importing the font will also trigger it.

### Minimal reproduction project (MRP)

[mrp.tgz](https://github.com/user-attachments/files/16740882/mrp.tgz)

**Comment by akien-mga** [comment]
Related to #94339, cc @bruvzg.

**Comment by matheusmdx** [comment]
Bisecting points to #92514 as the culprit, @vgezer:

![image](https://github.com/user-attachments/assets/9d3d8736-aef7-49c8-84de-ed7050e81a27)

<br>

Commeting this line stops the error
https://github.com/godotengine/godot/blob/28a72fa4344befeae251d8e9b11b84acd601a244/scene/gui/text_edit.cpp#L210

**Comment by mh114** [comment]
I was just about to report this with a repro project, I guess I'll just attach the project here: [FontBug.zip](https://github.com/user-attachments/files/16929113/FontBug.zip).

In my case the slow font import happens **only** when the font in question is set as the default theme font in project settings (`gui/theme/custom_font`). When reimporting another font that is not the default, it works normally. Also: this particular issue happened in **4.2.2** as well for me, now in **4.3**.

Spits out 1024 of these:
```  modules/text_server_adv/text_server_adv.cpp:2608 - Parameter "fd" is null.
  modules/text_server_adv/text_server_adv.cpp:2464 - Parameter "fd" is null.
  modules/text_server_adv/text_server_adv.cpp:2640 - Parameter "fd" is null.
  modules/text_server_adv/text_server_adv.cpp:2464 - Parameter "fd" is null.
  modules/text_server_adv/text_server_adv.cpp:2608 - Parameter "fd" is null.
  modules/text_server_adv/text_server_adv.cpp:2464 - Parameter "fd" is null.
  ...
```

**Comment by javideas** [comment]
This error appeared to me in 4.3 when renaming a saved and in use styleboxflat in the "Titlebar Selected" of a GraphNode. It disappeared when I reponed Godot.

**Comment by matheusmdx** [comment]
@javideas This issue was already fixed and closed. You can get the fix in Godot 4.4 dev 3 or higher.

**Comment by Noctunus** [comment]
Ran into the same (or maybe similar?) issue with 4.4-beta1:

```
reimport: begin: (Re)Importing Assets steps: 99
	reimport: step 0: Executing post-reimport operations...
ERROR: Parameter "fd" is null.
   at: _font_get_ascent (modules/text_server_adv/text_server_adv.cpp:2689)
ERROR: Parameter "fd" is null.
   at: _font_get_spacing (modules/text_server_adv/text_server_adv.cpp:2544)
ERROR: Parameter "fd" is null.
   at: _font_get_descent (modules/text_server_adv/text_server_adv.cpp:2723)
ERROR: Parameter "fd" is null.
   at: _font_get_spacing (modules/text_server_adv/text_server_adv.cpp:2544)
```

**Comment by matheusmdx** [comment]
@Noctunus This issue is already closed, i recommend you open a new issue to investigate that.

**Comment by DeanLemans** [comment]
im getting this issue when select 'Upgrade Project Files' in 4.5.

<img width="1336" height="167" alt="Image" src="https://github.com/user-attachments/assets/fb5fd9bd-a86e-47be-b318-e5d7aa5d2958" />

**Comment by matheusmdx** [comment]
@DeanLemans Please open a new issue as this one is already closed.
