### ISSUE TITLE
Godot closes the autocomplete box automatically when I use "super."

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#96082]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

w10 64

### Issue description

Watch the video. Godot only shows the autocomplete box for half a second and then closes it automatically immediately when I type the first character. That first character has matches so the box should not close.

https://github.com/user-attachments/assets/aade3ec9-05e2-4531-8629-21168c76501f

### Steps to reproduce

See the video

### Minimal reproduction project (MRP)

...

**Comment by Mickeon** [comment]
CC @HolonProduction

**Comment by matheusmdx** [comment]
This issue was already fixed in master by #94082:

![image](https://github.com/user-attachments/assets/b002f363-32a7-4414-9534-e704c299eb1d)

**Comment by Shura-Joy** [comment]
I'm still running into this bug.
v4.4.stable.official [4c311cbee]
System Information
Windows 11 (build 26100)

**Comment by matheusmdx** [comment]
@Shura-Joy I opened a new issue about this here: #104499
