### ISSUE TITLE
Color picker RAW mode has incorrect slider bounds

### ISSUE THREAD

**Issue by kerstop** [godotengine/godot#96083]
### Tested versions

Reproducable in: v4.2.2.stable.mono.official [15073afe3]

### System information

Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1060 3GB (NVIDIA; 31.0.15.3742) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

If you open up the color picker and switch to RAW mode you are able to select color values far outside of sensible range. 

### Steps to reproduce

- Open a color picker and switch to raw mode
- Drag any slider up to 100
- switch over to HSV mode to checkout the bugged sliders

### Minimal reproduction project (MRP)

any

**Comment by kerstop** [comment]
I was also wonder if there is any use case for the raw selection mode when rgb selection already exists?

**Comment by yahkr** [comment]
This should be fixed by https://github.com/godotengine/godot/pull/88072

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/62894

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
