### ISSUE TITLE
Split segment in Path2D breaks scene editing

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#96081]
### Tested versions

- reproducible in: 4.3
- NOT reproducible in: 4.2.2

### System information

macOS

### Issue description

Using the "split segment" tool to add a point to the Path2D breaks the scene history and editing. Similar to #89781.

### Steps to reproduce

- make a Path2D, add 2 points
- use first tool in toolbar to split the segment (click on the curve between 2 existing points to add a third)
- scene editing is now broken - cannot change visibility, add/delete nodes, etc.
- upon save and reload the scene, error prints: `core/object/undo_redo.cpp:457 - Condition "action_level > 0" is true.`

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Bisecting points to #93087 as the culprit, @KoBeWi (now we need the "path_to_even_less_bugs" branch):

![image](https://github.com/user-attachments/assets/ba94df29-53a4-4eff-93b0-3d0f238c2c44)

**Comment by flex-chillrsn** [comment]
Also experiencing this same issue. Reproduced as OP described, however I don't get the `core/object/undo_redo.cpp:457 - Condition "action_level > 0" is true.` in the console on saving and reloading the scene. The message seems to only appear for me when trying to undo a point created by trying to split a segment with "Select Points" tool selected. Quitting to project list and reloading the project seems to fix the issue until splitting a segment again.

**Comment by kenan238** [comment]
Same here.

**Comment by artbarte** [comment]
I have the same problems. Path2D is glitching the editor

**Comment by lmsonic** [comment]
Same here, splitting the path doesn't count as an action in the UndoRedo system

**Comment by SaffronStreams** [comment]
Same problem. Path2D being very hard to work with right now, sometimes not reacting to moving the base node, once curve points get added, it seems impossible to remove them, cannot delete path2D node from scene.

**Comment by matheusmdx** [comment]
@SaffronStreams This issue is already fixed and closed, you can get that in Godot 4.4 dev 2 or higher or wait the 4.3.1.

**Comment by BiLLz-Devs** [comment]
Same issue here (Godot 4.3). I just found the bug and though my level was cursed. Glad to see it is already fixed in future versions! Thanks Godot team!

**Comment by AThousandShips** [comment]
This was reported for 4.3, and will be in 4.3.1
