### ISSUE TITLE
Save warning doesn't show when you save a built-in resource as an external resource

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#96087]
### Tested versions

- Reproducible in: 4.3.stable

### System information

Godot v4.3.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When you close a scene after saving a built-in resource as an external resource, you don't get a warning to save your scene and you lose your modifications.

https://github.com/user-attachments/assets/7ad74d07-d5ef-4657-82e8-8547f7f37ca7

I expected a confirmation dialog like this after saving external resource and closing scene:

<img width="474" alt="Screenshot 2024-08-25 at 6 43 42 PM" src="https://github.com/user-attachments/assets/0a9e5c72-77e6-49b4-8200-a1b7559d07f9">

### Steps to reproduce

- Open a scene containing a built-in resource
- Save the resource as an external resource
- Close the scene
- You don't get a warning to save your scene
- Your scene keeps using a built-in resource instead the external resource

### Minimal reproduction project (MRP)

N/A

**Comment by stephannv** [comment]
> ### Tested versions
> * Reproducible in: 4.3.stable
> 
> ### System information
> Godot v4.3.stable - macOS 14.2.1 - Vulkan (Mobile) - integrated Apple M1 Max - Apple M1 Max (10 Threads)
> 
> ### Issue description
> When you close a scene after saving a built-in resource as an external resource, you don't get a warning to save your scene and you lose your modifications.
> 
>  pb21.mp4 
> 
> I expected a confirmation dialog like this after saving external resource and closing scene:
> 
> <img alt="Screenshot 2024-08-25 at 6 43 42 PM" width="474" src="https://private-user-images.githubusercontent.com/3025661/361260799-0a9e5c72-77e6-49b4-8200-a1b7559d07f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTU5MDAsIm5iZiI6MTcyNDcxNTYwMCwicGF0aCI6Ii8zMDI1NjYxLzM2MTI2MDc5OS0wYTllNWM3Mi03N2U2LTQ5YjQtODIwMC1hMWI3NTU5ZDA3ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMjM0MDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA3OWM0YjJjNWRiNGY5OWRlZGFiZjA1YzI0OWNjZjc0Y2YxNWNjYzA1ZGYyNmNkOTY1NDliYWJkYzIwMjhkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s-mcjbhuSmyRn4GmbQyJpnfJzFlG7m5lh2RsyUNa-rM">
> ### Steps to reproduce
> * Open a scene containing a built-in resource
> * Save the resource as an external resource
> * Close the scene
> * You don't get a warning to save your scene
> * Your scene keeps using a built-in resource instead the external resource
> 
> ### Minimal reproduction project (MRP)
> N/A

**Comment by Hilderin** [comment]
I was able to reproduce 4.3.stable and 4,4 dev master.
