### ISSUE TITLE
Godot 3.0 not recognizing old fonts

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#9610]
Arch Linux - Godot 3.0

Issue description:
Godot 3.0 does not recognize Godot 2.1.3 .fnt files as fonts. Godot 3.0 looks for a .font file, and if you try to make it load a .fnt file it spits out that it not a resource. Found while converting Godot 2.0 project to Godot 3.0. 

[FlappyGodot3.zip](https://github.com/godotengine/godot/files/1140087/FlappyGodot3.zip)

**Comment by reduz** [comment]
yeah, unfortunately this was needed so we can add supprot for bmfont .fnt
files without godot trying to recognize them.
I suppose the exporter should rename those extensions..

**Comment by vnen** [comment]
For me it does not work even after renaming. The editor doesn't recognize it as a resource.

**Comment by akien-mga** [comment]
Confirmed, I've implemented renaming the .fnt files to .font but they don't load. :/

**Comment by rcurtis** [comment]
Running into the same issue.  Can't find a way to get Godot 3.0 to recognize BMFont files.

**Comment by stubbsy345** [comment]
has anybody found an answer to this problem?

**Comment by BrainBlasted** [comment]
@stubbsy345, should be fixed by #11869

**Comment by BrainBlasted** [comment]
@stubbsy345, should be fixed by #11869
