### ISSUE TITLE
Clip children extremely slow on Android

### ISSUE THREAD

**Issue by felipejfc** [godotengine/godot#96131]
### Tested versions

4.3 Stable

### System information

Godot 4.3 Android ARM64

### Issue description

A simple 2d Menu with some buttons with clip children enabled will have poor performance on Android phone. Even on good models. Testing on iOS I didn't observe the same.

### Steps to reproduce

Create a button add a style like round corners, put either a label or a texture inside the button and make it clip children. See FPS drop by a lot.

### Minimal reproduction project (MRP)

[testproject.zip](https://github.com/user-attachments/files/16753444/testproject.zip)

**Comment by felipejfc** [comment]
Clip enabled and disabled difference

![Screenshot 2024-08-26 at 17 13 09](https://github.com/user-attachments/assets/0cd6090b-765b-46b8-9e73-c7e73b90f7db)
![Screenshot 2024-08-26 at 17 12 17](https://github.com/user-attachments/assets/02eab927-e885-4eca-bdd5-8f1d932857de)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/79439

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
