### ISSUE TITLE
Cannot build on Windows with MSVC

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#96132]
### Tested versions

52a2836861a4e544ce58908c50e457b18656239e 

### System information

Windows 11

### Issue description

Trying to build Godot with the auto-generated MSVC build on Windows 11 results in the following errors:
`initalizer is not constant` on lines 67 to 69 of `quant_bands.c` opus/celt. My current version of Visual Studio is 2022, version 17.11.1.

Bisecting reveals 52a2836861a4e544ce58908c50e457b18656239e to have caused this regression, and reverting it allows it to be built successfully. I believe the issue is that the patches to deal with floating point contraction in `sharpyuv_gamma.c` also need to be applied here too.

### Steps to reproduce

Execute scons with the argument `vsproj=yes` and then use the generated VS Project to build the engine. The build will fail with the errors previously mentioned.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
> Trying to build Godot with the auto-generated MSVC build on Windows 11 results in the following errors: `initalizer is not constant` on lines 67 to 69 of `quant_bands.c` opus/celt.

We don't have Opus in upstream Godot, are you building a fork maybe?

**Comment by SaracenOne** [comment]
Ah...my apologies. Yeah, this was actually a mix-up with custom builds. I'll close this now.
