### ISSUE TITLE
Image file imported incorrectly

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#96145]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Windows 11

### Issue description

When I try to import this GLB file, the diffuse map of the rock texture is incorrect.  It should be grey, not yellow.

### Steps to reproduce

Import the attached GLB file and add it to a scene.

### Minimal reproduction project (MRP)

https://drive.google.com/file/d/1pwfFcOOVAP-w48dDqpVXYzBAZOsmWBJv/view?usp=sharing

**Comment by yahkr** [comment]
After changing the import settings on your diffuse textures to not be imported as Normal Maps the texture looks more correct:

![image](https://github.com/user-attachments/assets/14d49645-de02-4dba-be45-bbd84daa5625)

**Comment by clayjohn** [comment]
Thanks for checking yahkr. Closing as the issue is comes from a misconfigured import setting, not a problem with the engine

**Comment by blackears** [comment]
Okay.  I never touched that setting, though.  I'm not sure why the importer decided to import that as a normal map - other gltf viewers treat it as diffuse.
