### ISSUE TITLE
After importing a GLB file with animations using a Bone Map, some animation data seems to be lost

### ISSUE THREAD

**Issue by diegopau** [godotengine/godot#96153]
### Tested versions

- Reproducible in  Godot 4.3.stable

### System information

Windows 10 - Godot v4.3.stable - Vulkan (Forward+) - AMD Radeon 6700XT

### Issue description

My goal is to assign a Bone Map to my character so I can later on bring a slightly different character and move the animations over to that new one.

My character is a simple voxel based character so it just doesn’t have all the bones that full humanoid character would have. However, if I understood how Bone Maps work (and animation retargeting), as long as all the bones in imported model are mapped to a bone in the SkeletonProfileHumanoid profile (and they all show in green) I should be able to use this. I would expect to have the same bones with just different names.
And this is partially what happens except that some animation tracks are missing. In the screenshots you can see how all the rotation tracks are there but the movement tracks (apologies if these are not the right naming, I mean the tracks with the orange icon showing 4 arrows and a center dot) are all missing except the first one (Hips, which was previously the “base” bone).

![image](https://github.com/user-attachments/assets/4fdf5579-1e46-40b4-8cba-b7e702b90d7e)
![image](https://github.com/user-attachments/assets/4547a569-a1c1-48a5-a6e2-6835a1b28041)

### Steps to reproduce

This might not happen with every single GLB file that contains animations. You can test this with the project files and GLB files provided in the Minimal reproduction project.
When opening that project you can check the advance import options for the "character with bone map.glb" to see how the BoneMap is assigned, it will look like this:

![image](https://github.com/user-attachments/assets/962251a1-014f-4c6a-a3f6-0fc86df46bfb)

You can then open both .tscn files available to compare how the character animations look like when the BoneMap is assigned and when not. I see missing animation tracks in the animation player for the character with a BoneMap assigned and I have no logical explanation for it because only some tracks are missing and it seems to affect to tracks related with movements (translation) but not those related to rotation.

### Minimal reproduction project (MRP)

Here you have a project that you can open an easily see 2 scenes, one with a character imported with that Bone Map assigned and the other one without any Bone Map assigned.

You can check the advance import options for the "character with bone map.glb" to see how the BoneMap is assigned.

[animation-retargeting-test.zip](https://github.com/user-attachments/files/16758912/animation-retargeting-test.zip)

**Comment by lyuma** [comment]
I believe this is a feature, not a bug (this behavior can be configured during import).

From my understanding, the tracks that are removed are position tracks which are not targeting the skeleton root.

These are removed because of the setting "Unimportant Positions" (default on) in the Remove Tracks section of the importer when a BoneMap is used.

The idea is that position animations on one model often do not work properly on other models, and hence for the purpose of retargeting, it is often desirable to remove most position tracks.

Let me know if turning off Unimportant Positions solves the issue for you.

I would be interested to know more about your usecase: If you do retargeting, why is it important to have this specific track be animationd. If not for retargeting, what is the usecase for renaming bones with the bonemap?

**Comment by diegopau** [comment]
@lyuma Good catch! it was indeed the default "Unimportant Positions" checkbox that was leaving some of the tracks behind. I feel a bit embarrassed now for not exploring that option.

I partially forgot the exact thing I was testing here but it was mostly an attempt to reuse as much as a I can from the Mixamo animations you can download at www.mixamo.com (and other animations that I got from some other resources) for my character that has a more simple skeleton, with less bones. The first step to achieve this would be to use a common set of bone names that all those animations will use in Godot, then test, and manually edit some of the animations as needed.
 
I believe It does actually help to have those position tracks imported so for instance for a jump or a fall animation, I would get a closer result if I keep those position tracks (maybe not perfect) than if they are removed and I have to manually add all the positioning myself.
In any case it allows me to at least manually select which ones to remove if I think it is better to remove them than to try to edit it so they work with my character.

**Comment by diegopau** [comment]
I am closing the issue since my initial problem is resolved. Thanks again!
