### ISSUE TITLE
Lightmap capture for dynamic objects don't work

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#96165]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Lightmap capture for dynamic objects don't work. Right after baking lightmaps, they'll look correct in the editor, but after launching the game, or reloading the project, dynamic objects look dark/unlit and broken.

Right after baking:

![Screenshot (43)](https://github.com/user-attachments/assets/8c9729dc-032a-4958-96a7-9461313a0990)

After running the game or reloading the project:

![Screenshot (44)](https://github.com/user-attachments/assets/f190a83f-aeb8-485f-b4c5-5aede1e56469)

### Steps to reproduce

1. Setup static objects with lightmap unwrapping
2. Setup dynamic objects
3. Add a Lightmap GI node to the scene
4. Bake the lightmap - notice everything looks fine in editor
5. Run the game or restart the project - notice dynamic objects look black

### Minimal reproduction project (MRP)

[lightmap_broken.zip](https://github.com/user-attachments/files/16762796/lightmap_broken.zip)

**Comment by clayjohn** [comment]
Seems to be the opposite problem from https://github.com/godotengine/godot/issues/77167 

I can spot a few other related issues too, so it seems like we need to do a deep investigation
https://github.com/godotengine/godot/issues/91431
https://github.com/godotengine/godot/issues/94825
https://github.com/godotengine/godot/issues/88101

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77167.
