### ISSUE TITLE
Not possible to deselect Dropdown list with activated Single Window Mode

### ISSUE THREAD

**Issue by hsvfan-jan** [godotengine/godot#96191]
### Tested versions

- 4.3 stable

### System information

Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

Single Window Mode introduces an issue where clicking with a mouse or the trackpad results in another click for some Dropdown lists. Tapping on the trackpad works normally.

E.g. when I want to select the down_arrow (v) of the Shape in the Inspector of a CollisionShape2D node, it opens. When I click it again, it closes and immediately opens again. Also happens for ->Node->Script-> (v). Can be worked around by clicking somewhere else.

Doesn't happen e.g. for ->CanvasItem->Texture->Filter-> (v) or switching between Forward+ and the other renderers. Also doesn't happen with the three-vertical-dot symbols.

Since activating Single Window Mode seems to be a current solution for the issues I mentioned in https://github.com/godotengine/godot/issues/96186, deactivating it would simply reintroduce other issues.

### Steps to reproduce

Activate Single Window Mode and inspect the issue

### Minimal reproduction project (MRP)

Happens in empty projects

**Comment by KoBeWi** [comment]
Seems caused by #94930
