### ISSUE TITLE
Build with MSYS2+MingW64 fails to find required DLLs

### ISSUE THREAD

**Issue by danila-zol** [godotengine/godot#96190]
### Tested versions

- Reproducible at commit `142d33211cb4276dee6f797117981af983471b9e`

### System information

Windows 11

### Issue description

MingW64 build fails with:
cc1plus.exe - System Error
"The code execution cnnot proceed because libisl-23.dll was not found. Reinstalling the program may fix this problem"

### Steps to reproduce

1. Do a clean install of MSYS2 into a directory `C:\foo\bar\msys64`
2. Install Godot build dependencies for MingW64 toolchain:
```bash
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-python-pip make
pip3 install scons
```
3. Invoke scons:
```powershell
scons use_mingw=yes mingw_prefix="C:\foo\bar\msys64\mingw64\"
```

### Minimal reproduction project (MRP)

Build issue, not applicable

**Comment by akien-mga** [comment]
This is likely a problem with your MSYS2 install / the package manager.

Can you compile a hello world project with the installed compiler?

```cpp
// main.cpp
int main() { return 0; }
```
```
C:\foo\bar\msys64\mingw64\bin\x86_64-w64-mingw32-g++ main.cpp
```
(or whatever is the path to the `g++` binary)

**Comment by danila-zol** [comment]
The toolchain works correctly in my case, it's just the Godot issue. Additionally, for me the issue is reproducible on a fresh MSYS2 install.

**Comment by danila-zol** [comment]
I was able to fix the problem. You have to manually add the toolchain `bin` directory into the global `$PATH` on Windows otherwise it will not be able to locate the toolchain DLL dependencies when not invoked from MSYS2 shell.

**Comment by danila-zol** [comment]
Not specifically a Godot issue, fixed
