### ISSUE TITLE
Mouse wheel paste doesn't work on Wayland editor

### ISSUE THREAD

**Issue by Cykyrios** [godotengine/godot#96214]
### Tested versions

v4.3.1.rc.custom_build [ff9bc0422]

### System information

Godot v4.3.1.rc (ff9bc0422) - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Aug  7 16:19:28 UTC 2024 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XT (RADV NAVI31) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

On Linux (kernel 6.9, Manjaro KDE Plasma 6.0.5), when enabling the Prefer Wayland editor setting, pasting text using the mouse wheel does not work. The issue does not occur when disabling this setting.

### Steps to reproduce

1. Copy text via Ctrl+C or selecting text with the mouse
2. Try pasting using the mouse wheel click
3. Nothing happens on Wayland, text is copied properly on X11

### Minimal reproduction project (MRP)

N/A

**Comment by hunterkepley** [comment]
Made an MR for a fix, was able to replicate the issue on Fedora 39 with KDE Wayland

Issue was the way it was grabbing the clipboard when using middlemouse vs ctrl+v

Used the same function used for ctrl+v and it works fine

**Comment by hunterkepley** [comment]
This also fixes line editing such as searching for projects, you will be able to use middle mouse there as well
