### ISSUE TITLE
Unable to import FBX model in 4.4.dev

### ISSUE THREAD

**Issue by takethebait** [godotengine/godot#96223]
### Tested versions

- Reproducible in 4.4.dev [108c603f9]
- Not reproducible in 4.3.stable [77dcf97]

### System information

Godot v4.4.dev.mono (108c603f9) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

When importing a mixamo character as an FBX in 4.4.dev, its not possible to instantiate it in a scene. The import process itself runs without issues however when attempting to drag the model into the scenes the output log is spammed with the following errors:

![Errors](https://github.com/user-attachments/assets/5a5b14a4-d19d-4434-81c4-b3f518f94f33)

To note may be that when importing the same model in 4.3.stable the following warnings are logged:

![Warnings 2](https://github.com/user-attachments/assets/13ae7d78-01a0-43d6-b18b-c2ec5f7efb99)

I don't know if that is relevant, I just wanted to mention it in case there are issues with the model itself. 

It was possible to import the character without issues in 4.3.stable. It was also possible to instantiate the model in 4.4.dev when performing the import in 4.3.stable and then opening the project in 4.4. 

The models I've tested were the X-Bot as well as the Alien Soldier with both failing with the same errors.

Also I'm using the following props in my custom.py:
```
production = "yes"
module_camera_enabled = "no"
module_mobile_vr_enabled = "no"
module_mono_enabled = "yes"
module_openxr_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
```

### Steps to reproduce

- Create a new project
- Import a mixamo character exported as FBX Binary into the project
- Attempt to drag it into the scene

### Minimal reproduction project (MRP)

N/A

**Comment by ydeltastar** [comment]
I bisected it to 7a20ba9b63561f1d2e54b7557a5b53ba99bed83a.
It happens with glTF as well and causes a `Scene file 'scene.tscn' appears to be invalid/corrupt` when trying to open scenes with an instance of the model.

**Comment by akien-mga** [comment]
This was likely already fixed by #96207, can you confirm?

**Comment by takethebait** [comment]
Yes, building [f648de1a83cf006dbfdaa075219ad4348628e58f] the issues seems to be fixed for FBX and gLTF!

**Comment by ydeltastar** [comment]
Yes, that pr fixes it. May require deleting the cache folder to fix the corrupt scene error.
