### ISSUE TITLE
Certain autocomplete of literals causes editor crash

### ISSUE THREAD

**Issue by AinaVT** [godotengine/godot#96239]
### Tested versions

- Reproducible in: 4.4.dev1
- Not reproducible in: 4.3.stable and earlier.

### System information

Godot v4.4.dev1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Certain autocomplete requests of literals causes a crash in the editor. This mainly occurs when trying to insert literal values as parameters to function calls for Autoload scripts, Static functions, and regular functions in specific circumstances.

Examples:

Assuming the Autoloaded script:
```gdscript
extends Node


func test_call(num):
	print(num)
```

and the call from another node:
```gdscript
extends Node3D


func _ready():
	AutoloadScript.test_call(10) # Crashes the editor while typing the number literal
```
The editor crashes when attempting to make a completion request while typing the literal value "10".

A similar problem happens with static functions:
```gdscript
class_name StaticScript
extends Object


static func test_call(num) :
	print(num)
```
```gdscript
extends Node3D


func _ready():
	StaticScript.test_call(10) # Crashes the editor while typing the number literal
```

This also happens when trying to type literal as parameters for function calls of scripts instantiated in the same scope as the call:
```gdscript
class_name RegularScript
extends RefCounted


func test_call(num: int):
	print(num)
```
```gdscript
extends Node3D

var regular_member = RegularScript.new()

func _ready():
	regular_member.test_call(10) # Does NOT crash the editor
	
	var regular_scoped = RegularScript.new()
	regular_scoped.test_call(10) # Crashes the editor thile typing the number literal
```

The examples above are using `int` literals, but it seems to be triggered by any kind of literal:
- Any `int` and `float` literal after giving enough of a brief pause while typing
- Any `string`, seems to immediatelly crash when opening double quotes
- Any keyword literal, like `null`, `true`, or `false`, which seems to trigger as soon as you finish typing the word

## Autoload scripts
- Create a script with a function and set it up as an Autoload
- In another script, try to call that function while attempting to type a literal value as a parameter
- Editor should crash

## Static functions
- Create a script with a `class_name` and a static function
- In another script, try to call that static function while attempting to type a literal value as a parameter
- Editor should crash

## Regular functions
- Create a script with a function
- In another script, instantiate and call the function in the same scope while attempting to type a literal value as a parameter
- Editor should crash

### Minimal reproduction project (MRP)

[crash-reproduction.zip](https://github.com/user-attachments/files/16787853/crash-reproduction.zip)

**Comment by AinaVT** [comment]
Out of curiosity, I attempted to clone the godot repository and tried to debug to see if I could see what was triggering this issue, since the editor itself wasn't giving any logs.
It seems to be caused by the method `GDScriptParser::override_completion_context` not setting the parser to the `CompletionContext`, which ends up causing an access violation later.
Adding this line to that method before setting the `completion_context` variable seems to stop the crash:
```cpp
context.parser = this;
```
But i'm not sure if this will cause any other issues, as i'm not familiar at all with godot's codebase.

**Comment by HolonProduction** [comment]
You are right it should be set there :+1:
I guess missed that since `context.parser` was introduced after I made the `override_completion_context` PR

Feel free to make a PR if you want to, otherwise I'll fix it together with some other regression from #94082
