### ISSUE TITLE
Quick Open when looking for files with multiple words not working as before

### ISSUE THREAD

**Issue by jsladovic** [godotengine/godot#96241]
### Tested versions

Reproducible in 4.3, did not occur in 4.2 as far as I can remember.

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 Threads)

### Issue description

Let's say I have two files in my system: dialog_box.gd and dialog_text.gd. I want to use the Quick Open (Ctrl+P) to go to the dialog_text.gd file. I have to enter "dialog_t" for the search to select my file. Otherwise, I can write "dia" and use the keyboard or mouse to move down to my file.

Now, in Visual Studio Code, I can enter "dt" and it will go to the correct file. I'm also pretty sure older versions of Godot worked like this, but I can't confirm.

### Steps to reproduce

Simply create two files (don't have to be .gd files) with the same first word and different second word in the title. Then try to use the Quick Open feature to move to the second file alphabetically.

### Minimal reproduction project (MRP)

This can be reproduced with any project with multiple files.

**Comment by AThousandShips** [comment]
This is an intentional change, see:
* https://github.com/godotengine/godot/issues/94907

Thank you for your report, consolidating there
