### ISSUE TITLE
Is it possible to add "many" Light2D nodes to the scene?

### ISSUE THREAD

**Issue by crayonape** [godotengine/godot#96263]
### Tested versions

4.3

### System information

MacOS Monterey 12.7.5

### Issue description

My game requires adding many (more than 16) light2D nodes to the scene, but when the number of Light2D nodes exceeds 16, some unexpected shadows appear.

![Screen Shot 2024-08-29 at 04 31 18](https://github.com/user-attachments/assets/7397a88f-8df6-4b8f-b27c-4fdc9fb44af7)

I searched for this situation and found that there is a limit of 16 when using Light2D nodes. Although the documentation says that I can use Sprite2D as an alternative, the effect is very bad when the environment is very dark.
Currently I can use a big light texture to solve the above problem, but I know that my game will have a dark map in the future where the player can shoot many fireballs. So, I better think about this problem sooner.
My question is: How can I add many "lighting" nodes to the scene? It doesn't have to be Light2D, because I don't need shadow functionality.

### Steps to reproduce

More than 16 light2D will have this problem.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is for reporting bugs, not for asking support questions, please ask in the [other community channels](https://godotengine.org/community/) instead in the future

There are limitations to how many lights can affect a single canvas item, see:
* https://github.com/godotengine/godot/issues/92952

Closing as per the above and consolidating in that report
