### ISSUE TITLE
Tileset physic shapes not showing on editor

### ISSUE THREAD

**Issue by anis-mahsoume** [godotengine/godot#96264]
### Tested versions

- Reproducible in 4.2, 4.3
- Not tested with other releases

### System information

Windows 10

### Issue description

In TileSet Paint tab, upon selecting in Paint Properties Physics Layer 0, the physic shapes are not shown for any of the tiles:
<img width="644" alt="image" src="https://github.com/user-attachments/assets/b07a5f43-656d-48a0-b449-1cf807fe960c">

Although shapes are existing and shown properly upon tile selection:
![image](https://github.com/user-attachments/assets/899fed34-9742-4087-8731-e50aee64af6d)

### Steps to reproduce

Download my minimum reproducible scenario:
https://github.com/anis-mahsoume/tileset_physics_not_showing_in_editor

- Open the project in godot editor 4.3
- Open the scene test_tilemap.tscn
- Select TileMap node in the scene, and go to TileSet tab > Paint
- Select Physics Layer 0, then try to paint anything

### Minimal reproduction project (MRP)

MRP on github:
https://github.com/anis-mahsoume/tileset_physics_not_showing_in_editor

Or in attached zip:
[tilemap_issue_min_reproducible.zip](https://github.com/user-attachments/files/16792991/tilemap_issue_min_reproducible.zip)

**Comment by kleonc** [comment]
You have set a transparent debug shape color in the project settings:

![Godot_v4 3-stable_win64_zC77aUjm1R](https://github.com/user-attachments/assets/7519332c-a9fa-4e4c-939f-bd56fa7bfc49)

In `project.godot`:
```
[debug]

shapes/collision/shape_color=Color(0, 0.6, 0.701961, 0)
```

No bug in here.

**Comment by anis-mahsoume** [comment]
> You have set a transparent debug shape color in the project settings:
> 
> ![Godot_v4 3-stable_win64_zC77aUjm1R](https://private-user-images.githubusercontent.com/9283098/362628874-7519332c-a9fa-4e4c-939f-bd56fa7bfc49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODU2NTQsIm5iZiI6MTcyNDk4NTM1NCwicGF0aCI6Ii85MjgzMDk4LzM2MjYyODg3NC03NTE5MzMyYy1hOWZhLTRlNGMtOTM5Zi1iZDU2ZmE3YmZjNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDIzNTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY0ZDVjYWQwMTA1M2I2YWFjNjQxNDgwMmE0Y2I4NGEwM2VmZDliMjA3ZWFmZjU2YThhZmUxNzRjM2UwNzc5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qqkk5OibsnWO1maOg391rHDQu609oSWfHfVizJJscpw)
> 
> In `project.godot`:
> 
> ```
> [debug]
> 
> shapes/collision/shape_color=Color(0, 0.6, 0.701961, 0)
> ```
> 
> No bug in here.

Oh my.. Thank you so much!
