### ISSUE TITLE
SVG does not render correctly in master as of PR #96167 (works in 4.3 stable)

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#96262]
### Tested versions

- Reproducible in 4.4-dev commit ce8a837aab2568f9cdc41b4b410c478b0cd711fc (latest master as of writing)
- Reproducible in 4.4-dev commit 1e41bf6a085
- Reproducible in 4.4-dev commit bd04f687f0a
- Reproducible in 4.4-dev commit a2f097d6035
- Reproducible in 4.4-dev commit fe024443e36 PR #96167
- Works fine in 4.4-dev commit b4eacfe0cec
- Works fine in 4.4-dev commit 1ead46e78250b6b6a040f362ce48b7b1b93b7f65
- Works fine in 4.4-dev commit 8ae2c3a0006
- Works fine in 4.4-dev commit 08ffa5d89e4
- Works fine in 4.3-stable

### System information

macOS 14.6.1 arm64

### Issue description

As of PR #96167, this SVG does not render correctly. There is a defect on the left of the image.

Incorrect image:
<img width="270" alt="Screenshot 2024-08-28 at 9 10 47 PM" src="https://github.com/user-attachments/assets/7012737f-ef09-4eb5-970e-5255b2e85053">

Correct image:
<img width="270" alt="Screenshot 2024-08-28 at 9 10 53 PM" src="https://github.com/user-attachments/assets/83ebd186-247b-42e9-8ec7-6096eb5038c7">

### Steps to reproduce

Open the below SVG in the latest Godot master branch.

### Minimal reproduction project (MRP)

Here is the SVG: ![icon](https://github.com/user-attachments/assets/2aa83a36-3715-4c8d-95fc-86aa81508329)

**Comment by akien-mga** [comment]
Confirmed. On the other hand I don't reproduce it on https://thorvg.github.io/thorvg.viewer/ which also claims to use 0.14.7, so there might be an issue with how we're using ThorVG.

I tested intermediate ThorVG releases between 0.14.2 (our previous version) and 0.14.7, and it appears that the regression was introduced in 0.14.6.

I'll open an upstream bug report later today, but CC @mgrudzinska @hermett @capnm FYI.

**Comment by akien-mga** [comment]
I bisected the regression in thorvg to https://github.com/thorvg/thorvg/commit/fdc45edf32820b7e0979ed7f8a48a14d2adc8103 cc @mgrudzinska.

**Comment by mgrudzinska** [comment]
I'm on it, reproduced

**Comment by capnm** [comment]
Note++: The fundamental issue is still WIP  https://github.com/thorvg/thorvg/pull/2711 ...

![image](https://github.com/user-attachments/assets/1191ac03-3dba-453b-9634-e27a7acee26a)

**Comment by akien-mga** [comment]
Yeah that's why I finally opted for reverting the Bézier precision change (which was motivated by Lottie which we don't use yet), restoring the pre-regression behavior. We can wait for ThorVG to find a good solution and then confirm it works in Godot.

**Comment by capnm** [comment]
> _Edit:_ to be clear, the SVG you shared should also be broken in earlier versions of Godot/ThorVG, right? If it's not a regression I don't think we need to track it here, just an upstream bug report is enough.

I have now tested some older stable versions; it renders correctly in 4.1.4 but is broken in v4.2.2, along with everything that follows.  As you mentioned, it's already a known issue, and I agree. You could, I suppose, produce a lot of such floating-point precision-related SVGs...

![editor_screenshot_2024-09-07T120003](https://github.com/user-attachments/assets/f8e403df-8ef2-436a-98ec-1b9d6ccf7a36)
