### ISSUE TITLE
Exported Vars: Cannot clear item from array when hint is Array[Node]

### ISSUE THREAD

**Issue by KccbzZ** [godotengine/godot#96273]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+)

### Issue description

When exporting a variable with the hint `Array[Node]` and adding an item to it, then on that item clicking the 3 dots then clicking `Clear`, this will show the following error:

```
 Attempted to set a variable of type 'NodePath' into a TypedArray of type 'Object'.
  core/variant/array.cpp:429 - Condition "!_p->typed.validate(value, "set")" is true.
```

### Steps to reproduce

1. Create a new project (v4.3.stable is the only one I tested)
2. Add a node
3. Add a script
4. Write `@export var test : Array[Node]`
5. In the inspector, add an item to the array (select any node)
6. Now clear that item only using `3 Dots` > `Clear`
7. The error above should display in `Output`

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
CC @ajreckof
