### ISSUE TITLE
A missing project still displays an invalid timestamp in the Project Manager

### ISSUE THREAD

**Issue by Mickeon** [godotengine/godot#96274]
### Tested versions

- Reproducible in 4.3

### System information

Windows 10

### Issue description

When a project goes missing, the Project Manager still displays a timestamp, which is invalid because... the project does not exist.

![image](https://github.com/user-attachments/assets/ce68c5a7-e77f-4ff3-af99-048c653f2edd)

Not only is this timestamp actually useless, but it actually makes it more difficult to view the missing project's path.
You can argue the "Unsupported features" warning is also just as useless and should not appear in this case.

### Steps to reproduce

Add a project to the project manager, close the Project Manager, and rename its folder. Then look again.

### Minimal reproduction project (MRP)

<img src=https://github.com/user-attachments/assets/23a50edf-5e81-4fc6-85bd-c76b429f3c96 width=1%>

**Comment by AThousandShips** [comment]
Already fixed in:
* https://github.com/godotengine/godot/pull/96162

**Comment by Mickeon** [comment]
Alright, now time to get rid of that pesky warning, too
