### ISSUE TITLE
Changing UV via shader breaks on OpenGL via Angle on Windows

### ISSUE THREAD

**Issue by IsaqueS** [godotengine/godot#96277]
### Tested versions

Bug found on: Godot 4.3 Stable, Godot 4.2.2 Stable

The project was not tested on godot 4.1 because the angle compatibility on windows was introduced on version 4.2

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2050 (NVIDIA; 32.0.15.6070) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

While I was checking my game using the Angle compatibility layer (on Windows).

I discovered a bug in the way UV changes are made by the shader, using Angle on windows.

**I did this by using this shader code on a ColorRect Node:**

```
shader_type canvas_item;

uniform sampler2D SCREEN_TEXTURE: hint_screen_texture;
uniform sampler2D NOISE: hint_anisotropy;
uniform float NOISE_EFFECT_STRENGTH: hint_range(0.0, 0.1, 0.0001) = 0.0032;

uniform float mix_strength: hint_range(0.0, 1.0, 0.05) = 0.15;
uniform vec3 tint_color : source_color;
uniform bool use_rgb_noise = false;

void fragment() {
	vec2 distorded_uv = SCREEN_UV + texture(NOISE, SCREEN_UV).r * (NOISE_EFFECT_STRENGTH); // / (screen_scale * tree_d_scale));
	
	vec4 screen_color = texture(SCREEN_TEXTURE, distorded_uv);
	
	COLOR = mix(screen_color, screen_color * vec4(tint_color, screen_color.a), mix_strength);
			
}
```

**And using an noise texture like this:**

![noiseTexture](https://github.com/user-attachments/assets/d7cfa6a7-06e0-47ba-b7c0-b8e06a2ed34d)

Here are some pictures.

> **OpenGL 3.3:** _complex scene_

![opengl](https://github.com/user-attachments/assets/24c05421-2893-429b-ae43-d8a126a22d9a)

> **Angle (Via Windows)** _complex scene_

![angle](https://github.com/user-attachments/assets/4eabf673-c0a4-4ae5-9672-0de87f5c904a)

> **OpenGL 3.3:** _simple scene_
![opengl testproject](https://github.com/user-attachments/assets/72bad6d7-cd80-4736-a85e-7266c6559f40)

> **Angle (Via Windows)** _simple scene_
![angle testproject](https://github.com/user-attachments/assets/55932110-5439-4308-a226-ff7dc40aab0d)

Apparently instead of reading the value with the entire spectrum within 0.0 to 1.0, it is "rounding" giving this strange pixelated effect.

### Steps to reproduce

First create a project _(on Windows)_, use compatibility mode.

Then create a scene where the effect will be applied, a simple 2D scene will be enough.

Then **apply the shader** that is in the description to a **ColorRect Node**, fill the screen with the ColorRect, and **add a noise** texture to the parameters.

After the effect appears, **change the option** in the project settings in the OpenGL section that allows the **Angle** to be the version used.

### Minimal reproduction project (MRP)

Godot 4.3 Project: 
[angle-uv-test - Godot 4.3.zip](https://github.com/user-attachments/files/16798078/angle-uv-test.-.Godot.4.3.zip)

Godot 4.2.2 Project: 
[angle-uv-test - Godot 4.2.2.zip](https://github.com/user-attachments/files/16798094/angle-uv-test.-.Godot.4.2.2.zip)

**Comment by clayjohn** [comment]
Initial testing seems like its a mipmapping issue. 

Changing the screen texture lookup to `vec4 screen_color = textureLod(SCREEN_TEXTURE, distorded_uv, 0);` is enough to make the issue go away. You can do that as a workaround while we investigate this more.

**Comment by IsaqueS** [comment]
THANKS SO MUCH!!! ;D

you are my hero! 🙌⭐
