### ISSUE TITLE
Node3D with any attached scripts showing polygon 3d editor regardless of class.

### ISSUE THREAD

**Issue by AinaVT** [godotengine/godot#96312]
### Tested versions

- Reproducible in: 4.4.dev [fd7239c]
- Not reproducible in: 4.4.dev1 and earlier

### System information

Godot v4.4.dev (fd7239cfa) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.4617) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

In the 3D editor, selecting any Node3D (and any node that inherits from it) in the scene that have a script attached to it results in the polygon 3d editor tool showing up, even if the node doesn't support it.

https://github.com/user-attachments/assets/cffd59ee-e367-44f6-9344-d47cf7006921

### Steps to reproduce

- Add any kind of Node3D to the scene that does not support polygon editing.
- Attach a script to the node.
- Next time you select the node, the polygon editor will become visible and "functional".

### Minimal reproduction project (MRP)

[polygon-3d-editor-bug.zip](https://github.com/user-attachments/files/16811185/polygon-3d-editor-bug.zip)

**Comment by passivestar** [comment]
Can confirm I have this too on master

**Comment by Hilderin** [comment]
Bisected to 2d8f6c1b1d984222d1690f8afd504faed9f303be @dalexeev 
![image](https://github.com/user-attachments/assets/69697cb6-65ba-47f5-8135-e056824f316e)
