### ISSUE TITLE
Godot doesn't quit

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9631]
Godot 2.1.3 Windows 10 64 bits
Same in Godot 2.1.4 alpha

I am in a state where Godot doesn't close. If I try to close the window, it asks if I want to quit, I press "quit", and nothing happens. Same when clicking "Quit to project list", the project manager opens but Godot stays open in the background.

I don't know how to reproduce this yet, all I did was to open Godot, search for some docs, click a link in the doc, open a script... then close.

The only error I have in the console is:
```
ERROR: RichTextLabel::scroll_to_line: Index p_line out of size (main->lines.size()).
   At: scene\gui\rich_text_label.cpp:1729
```
Which has happened before I quit and doesn't happen again when I retry to quit.

EDIT: I restarted Godot, did nothing, tried to quit: it still doesn't close.
This time the only error is:
```
ERROR: PopupMenu::set_item_checked: Index p_idx out of size (items.size()).
   At: scene\gui\popup_menu.cpp:659
```

**Comment by eon-s** [comment]
I have this problem sometimes when playing with adb (on Windows and Linux), killing adb let Godot close.

**Comment by neikeq** [comment]
> ```
> ERROR: RichTextLabel::scroll_to_line: Index p_line out of size (main->lines.size()).
>    At: scene\gui\rich_text_label.cpp:1729
> ```

I can also experience this error sometimes. The editor freezes and prints it constantly.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
