### ISSUE TITLE
Typed array access methods (e.g. back, front, but not operator[]) fail to infer returned type as member type (Parser Error: The variable type is being inferred from a Variant value) and manual typing still doesn't enable autocomplete

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#96324]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 860M (nvidia; 535.183.01) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

I have a typed array:

```gd
var nodes: Array[Node2D]
```

I want to access some element of that array using an accessor method, and deduce the returned type as the member type (Node2D), not Variant:

```gd
var node := nodes.back()
```

This fails with:

> Parser Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)

I can disable the warning, but that won't help me with autocompletion. In this case it doesn't matter much for an int, but for a class with methods I want to use, autocomplete is quite useful.

One workaround is not to type at all:

```gd
var node = nodes.back()
```

but then we lose autocompletion).

Another way is to manually type:

```gd
var node: Node2D = nodes.back()
```

then we *should* be able to autocomplete, but oddly enough, here spawns a _second bug_ that _prevents autocompletion_ anyway:

```gd
node.pos # Ctrl+Space doesn't show autocomplete popup at all
```

So there is basically no way to make autocomplete work on any variable obtained by accessing an Array element this way.

You may think that we can, at last resort, re-assign the variable, but no, the error propagates to the next variable:

```gd
var node = nodes.back() # don't bother typing here, since we're gonna type on next line
var node2: Node2D = node
node2.pos # Ctrl+Space doesn't show autocomplete popup at all
```

The only way I found was to create an expression that the parser would not try to interpret/optimize as "always `node`" by using this ridiculous ternary:

```gd
var node = nodes.back() # don't bother typing here, since we're gonna type on next line
var node2: Node2D = node if true else null # obviously always node but enough to trick the parser
node2.pos # Ctrl+Space works and shows autocomplete popup!
```

The bug triggers with all accessor methods:
```gd
back()
front()
max()
min()
pick_random()
pop_at(0)
pop_back()
pop_front()
reduce(callback)
```

### Steps to reproduce

Bug 1: Array accessor return type inferred as Variant

1. Make sure that Project Setting: debug/gdscript/warnings/inference_on_variant is true so warning is treated as error and pops up
2. Copy the code snippet:

```gd
var nodes: Array[Node2D]
var node := nodes.back()
```

and check the warning treated as error:

> Parser Error: The variable type is being inferred from a Variant value, so it will be typed as Variant. (Warning treated as error.)

Bug 2: Manual typing still fails

1. Try manual typing:

```gd
var nodes: Array[Node2D]
var node: Node2D = nodes.back()
```

2. Try to autocomplete:

```gd
node.pos # press Ctrl+Space
```

and note that no autocomplete popup appears

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/59721

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

See there for more details and answers
