### ISSUE TITLE
seems the Dependencies of gdextension  cant be exported properly?

### ISSUE THREAD

**Issue by eeyzs1** [godotengine/godot#96325]
### Tested versions

4.3

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.5186) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

I was used the latest plugin of https://github.com/3ddelano/epic-online-services-godot/releases/latest
and tried to export the project with standard template and found the 2 dependencies:EOSSDK-Win64-Shipping.dll and  xaudio2_9redist.dll didnt appear with the exe file every time. Though libeosg.windows.template_debug.dev.x86_64.dll and libeosg.windows.template_release.x86_64.dll were appeared every time. Below is the extension file I was did a quick check that at the beginning I thought maybe the prefix matters, but after change the name it didnt work, so I raised this ticket

```
[configuration]

entry_symbol = "eosg_library_init"
compatibility_minimum = 4.1

[libraries]
windows.debug = "bin/windows/libeosg.windows.template_debug.dev.x86_64.dll"
windows.release = "bin/windows/libeosg.windows.template_release.x86_64.dll"

[dependencies]
windows.debug = ["res://addons/epic-online-services-godot/bin/windows/EOSSDK-Win64-Shipping.dll", "bin/windows/x64/xaudio2_9redist.dll"]
windows.release = ["bin/windows/EOSSDK-Win64-Shipping.dll", "res://addons/epic-online-services-godot/bin/windows//x64/xaudio2_9redist.dll"]
```

### Steps to reproduce

1. get a test project
2. Download the epic-online-services-godot-windows-622d832c1f13cd7a65ee243b93580d9dcc9ef5b6.zip from https://github.com/3ddelano/epic-online-services-godot/releases/latest
3. Extract the zip file and copy the `addons/epic-online-services-godot` folder into the `res://addons/` folder of your project. If the `res://addons` does not exist, create it.
4. In the Godot editor, goto `Project->Project Settings->Plugins` and enable the `Epic Online Services Godot 4.2 (EOSG)` plugin.
5. Restart the godot editor, then try export

### Minimal reproduction project (MRP)

N/A

**Comment by dsnopek** [comment]
Thanks!

> [dependencies]
> windows.debug = ["res://addons/epic-online-services-godot/bin/windows/EOSSDK-Win64-Shipping.dll", "bin/windows/x64/xaudio2_9redist.dll"]
> windows.release = ["bin/windows/EOSSDK-Win64-Shipping.dll", "res://addons/epic-online-services-godot/bin/windows//x64/xaudio2_9redist.dll"]

This isn't the right format for the `[dependencies]` section. This should look like:

```
windows.debug = {
  "res://addons/epic-online-services-godot/bin/windows/EOSSDK-Win64-Shipping.dll": "",
  "bin/windows/x64/xaudio2_9redist.dll": ""
}
windows.release = {
  "bin/windows/EOSSDK-Win64-Shipping.dll": ""
  "res://addons/epic-online-services-godot/bin/windows//x64/xaudio2_9redist.dll": "",
}
```

Note: the switch from square brackets (`[]`) to curly brackets (`{}`), and having `: ""` after each file.

I'm not sure why two of the entries use `res://` and the others don't? But so long as the files are at the paths referred to, they should work.

**Comment by eeyzs1** [comment]
Oh, great! Many thanks, Ill let 3ddelano know.
