### ISSUE TITLE
Godot core build fails with an error `llvm-ar.exe: error: unknown option -` when using llvm (llvm-mingw) prior to v14

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#96336]
### Tested versions

- Reproducible in 4.34.dev1(2730d703a83bd2bd6aae7788c1d27333e1882026)
- Not reproducible in 4.4.dev1(da230f384b90360ec108ce1be2347a327d68ca07)
- Regression by ~https://github.com/godotengine/godot/pull/94845~ https://github.com/godotengine/godot/pull/94747

### System information

Win10

### Issue description

input:
```
scons platform=windows target=editor -j 16
```

result:
```
ERROR: llvm-ar.exe: error: unknown option -
```

### Steps to reproduce

Build godot with above command.

### Minimal reproduction project (MRP)

N/A

**Comment by TokageItLab** [comment]
@alvinhochun I couldn't figure it out since the merged branch contained multiple commits. And I see that #94747 is definitely the culprit.

Then, I checked the llvm version and it was 11.0.1, so I updated it to latest (with scoop) and it works, thanks. But as you add in that PR, it seems to me that it would be better to support older versions of LLVM. Or it should output an error due to version checking.

**Comment by TokageItLab** [comment]
Oh sorry, I was on the wrong branch to build and it wasn't actually fixed, I still get the same error after updating llvm to 18.1.8.

**Comment by akien-mga** [comment]
If `--thin` is the problem, you should be able to check the compiler version with `methods.get_compiler_version` to only enable it if it's 14+.

**Comment by alvinhochun** [comment]
#96373
