### ISSUE TITLE
export_range step argument 1.0 disables the range slider

### ISSUE THREAD

**Issue by twoco** [godotengine/godot#96338]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Windows 11

### Issue description

```gdscript
# Shows a range slider.
@export_range(0, 100, 0.1, "or_greater", "or_less") var my_value_1 := 20.0

# Shows no range slider.
@export_range(0, 100, 1.0) var my_value_1 := 20.0

# Shows a range slider.
@export_range(0, 100, 1.00001) var my_value_1 := 20.0
```

It seems that the value of `1` in step disables the range slider.

| Expected | Actual |
| --- | --- |
|![expected](https://github.com/user-attachments/assets/58e9d18e-df34-4739-ba7a-e01f313de6ff)|![actual](https://github.com/user-attachments/assets/70048306-502b-4e18-bdc2-a8e980dad4f2)|

Put the line in a project and test it.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/42809

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
