### ISSUE TITLE
The script button in the node inspector disappeared

### ISSUE THREAD

**Issue by Ciapas-Linux** [godotengine/godot#96334]
### Tested versions

4.4.dev from 30-08- 2024, 17:19:54

### System information

Godot Engine v4.4.dev.custom_build.a5830f6eb (2024-08-30 09:43:13 UTC) - https://godotengine.org OpenGL API 3.3.0 NVIDIA 470.239.06 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GT 740M

### Issue description

The script button in the node inspector disappeared, it disappeared in the last builds from the developer version, maybe it's not a bug but a temporary issue. But I'm only reporting it because I see that no one has reported it. Under Linux.

### Steps to reproduce

just build a new version from github from sources

### Minimal reproduction project (MRP)

just create a new project, and then add a script to the node and it is not visible in the inspector, but nodes without a script have the option to add a script.

**Comment by AThousandShips** [comment]
Regression from:
* https://github.com/godotengine/godot/pull/94511

CC @dalexeev
