### ISSUE TITLE
Exporting to older devices on 4.x

### ISSUE THREAD

**Issue by GreatNateDev** [godotengine/godot#96345]
### Tested versions

- Godot 4.3

### System information

Engine Arch x64 platform Amazon fire 7th gen from 2017 running os based on android 5.1

### Issue description

Game crashes right at start of app

### Steps to reproduce

exporta blank project with just a control node to that device

### Minimal reproduction project (MRP)

just add a control node and export it

**Comment by AThousandShips** [comment]
Does the device actually support Godot 4.x? It's a 7 year old device with an incredibly old version of Android

Please confirm it's actually supported

**Comment by GreatNateDev** [comment]
> Does the device actually support Godot 4.x? It's a 7 year old device with an incredibly old version of Android (about 6-7 years)
> 
> 
> 
> Please confirm it's actually supported 
> 
> 
> 
> By the official requirements you have to have at least Android 6.0, see [here](https://docs.godotengine.org/en/stable/about/system_requirements.html#id2)

Oh so what's the latest version that supports android 5.1?

**Comment by AThousandShips** [comment]
3.x supports 4.4 I believe, but no version of 4.x supports such an old version

**Comment by GreatNateDev** [comment]
Cool just tried it on godot 3.5.3 worked great missing all the 4.x features but whatever thanks man!
