### ISSUE TITLE
Not able to print any Output [macOS Sierra]

### ISSUE THREAD

**Issue by pakchano** [godotengine/godot#9635]
**Operating system or device - Godot version:**
- **Device:** MacBook Pro (Retina, 15-inch, Mid 2014)
- **OS:** macOS Sierra 10.12.5 (16F73)
- **Godot version:** v2.1.3.stable.official

**Issue description:**

Not able to print any text in the _Output tab_

![godot-no-output](https://user-images.githubusercontent.com/9617583/28182906-940ac83a-67db-11e7-8472-59ce285900b1.gif)

**Steps to reproduce:**
1. Created a script attached to an object.
2. Declared a print() function with some text.
3. The function gets called but no Output text gets rendered.

**Link to minimal example project:**

[godot-no-output.zip](https://github.com/godotengine/godot/files/1146318/godot-no-output.zip)

**Comment by vnen** [comment]
Looks like the debugger is not connecting, may be a problem like #8563.

**Comment by akien-mga** [comment]
Looks like #8563 indeed, could you run the editor from a terminal and see if you also get an error about the Remote Debugger?

**Comment by pakchano** [comment]
Yeah, I was following @tooldoctor 's directions on #8563 
It's not doing anything different for me.
How do I run the editor from a terminal @akien-mga to help out?

**Comment by akien-mga** [comment]
>  How do I run the editor from a terminal @akien-mga to help out?

Open a terminal, go to the directory where you have your Godot binary with `cd` (e.g. `cd /Users/pakchano/Godot`), and run the binary with `./name_of_binary`.

**Comment by pakchano** [comment]
Got the following
```bash
arguments
0: ./Godot
ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:38.
nscreen count 2
```
Godot opened up immediately after.
Went to my file and tried to play the scene again.

```bash
OPENING: /Users/park/game/godot/godot-no-output (::Users::park::game::godot::godot-no-output)
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: -path
2: /Users/park/game/godot/godot-no-output
3: -editor
ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:38.
ERROR: free_static: Condition ' !MemoryPoolStatic::get_singleton() ' is true.
   At: core/os/memory.cpp:59.

nscreen count 2

running: /Applications/Godot.app/Contents/MacOS/Godot -path /Users/park/game/godot/godot-no-output -rdebug localhost:3000 -epid 34253 -p 928x581 res://stage_1.tscn
arguments
0: /Applications/Godot.app/Contents/MacOS/Godot
1: -path
2: /Users/park/game/godot/godot-no-output
3: -rdebug
4: localhost:3000
5: -epid
6: 34253
7: -p
8: 928x581
9: res://stage_1.tscn
ERROR: create: Condition ' !create_func ' is true. returned: 0
   At: core/os/mutex.cpp:38.
ERROR: _resolve_hostname: getaddrinfo failed!
   At: drivers/unix/ip_unix.cpp:106.
ERROR: connect: Condition ' !p_host.is_valid() ' is true. returned: ERR_INVALID_PARAMETER
   At: drivers/unix/stream_peer_tcp_posix.cpp:140.
Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
Remote Debugger: Connection failed with status: 0'', retrying in 1 sec.
Remote Debugger: Unable to connect
nscreen count 2
Say Hello
Say Hello
Say Hello
Say Hello
Say Hello
Say Hello
Say Hello
Say Hello
```

Looks like it's printing on the terminal.

**Comment by BastiaanOlij** [comment]
Actually I've noticed this for awhile but didn't think anything off it. It's actually printing empty strings into the debugger log for me and indeed outputting the print properly to the terminal. 

I'm only getting the debugger connection fail once I think, I'll check when I'm home tonight.

**Comment by Faless** [comment]
The culprit is:

> ERROR: _resolve_hostname: getaddrinfo failed!

Is the machine connected to the internet? Seems again the problem with OS not resolving `localhost`?

This should be gone in the current `2.1` branch since we use don't use `localhost` anymore, but the machine IP for the debugger.

Will need double check though

**Comment by Faless** [comment]
> I think this could be closed

ping @akien-mga
