### ISSUE TITLE
[MP] MultiplayerSynchronizer crashes networking profiler

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot#96354]
### Tested versions

Reproducible in 4.3

### System information

Windows 10 Godot 4.3 stable

### Issue description

Having a variable being watched by MultiplayerSynchronizer with a "Spawn" and "Change Only" option while you change value with variable timings leads to crash of the editor with a launched networking profiler.

### Steps to reproduce
Take a small script like this:
```gd
extends Label
var VarTimer : float = 0.0
@export var Counter : float = 1000.0
func _process(delta: float) -> void:
	text = str(Counter)
	if(!is_multiplayer_authority()): return
	VarTimer += delta
	if VarTimer > 0.5:
		Counter += 360.0
		VarTimer = 0.0
```
And attach it to a label. Then create MultiplayerSynchronizer, point it to a "Counter" variable, set "Spawn" and "Change Only" for this variable. When you will open a game, launch profiler and get another player to connect you will get a crash like this:

![image](https://github.com/user-attachments/assets/0ba2e364-f5f0-476e-9300-aae9debe0f74)

### Minimal reproduction project (MRP)

[multiplayer_pong.zip](https://github.com/user-attachments/files/16830808/multiplayer_pong.zip)

**Comment by Withaust** [comment]
@Faless do you perhaps know what might have caused this? Where should I be looking in order to debug this?

**Comment by Withaust** [comment]
I have narrowed it down to MultiplayerSynchronizer's different replication types. It does not crash on `Never` and `Always`. This only happens on `Change Only`. Investigating further.

**Comment by Withaust** [comment]
@Faless What should I try to debug in order to find which piece of code sets this faulty SyncInfo?

**Comment by Withaust** [comment]
I have a feeling that this might be due to a new variant encoding / delta encoding figuring out that no value was changed, hence no size, but still triggering an outgoing send.

**Comment by Withaust** [comment]
I have added some warns to understand what is happening:
```cpp
for (const KeyValue<ObjectID, MultiplayerDebugger::SyncInfo> &E : frame.infos) {
	WARN_VERBOSE(vformat("ObjectID: %d incoming_syncs: %d incoming_size %d outgoing_syncs %d outgoing_size %d", E.value.synchronizer,
			E.value.incoming_syncs, E.value.incoming_size, E.value.outgoing_syncs, E.value.outgoing_size));
	profiler->add_sync_frame_data(E.value);
}
```
Here is the result:
```
modules\multiplayer\editor\multiplayer_editor_plugin.cpp:69 - ObjectID: 35181823443 incoming_syncs: 0 incoming_size 0 outgoing_syncs 0 outgoing_size 0
modules\multiplayer\editor\multiplayer_editor_plugin.cpp:69 - ObjectID: 35181823443 incoming_syncs: 0 incoming_size 0 outgoing_syncs 1 outgoing_size 0
modules\multiplayer\editor\multiplayer_editor_plugin.cpp:69 - ObjectID: 35181823443 incoming_syncs: 0 incoming_size 0 outgoing_syncs 1 outgoing_size 0
modules\multiplayer\editor\multiplayer_editor_plugin.cpp:69 - ObjectID: 35181823443 incoming_syncs: 0 incoming_size 0 outgoing_syncs 1 outgoing_size 0
modules\multiplayer\editor\multiplayer_editor_plugin.cpp:69 - ObjectID: 35181823443 incoming_syncs: 0 incoming_size 0 outgoing_syncs 0 outgoing_size 0
```

**Comment by Withaust** [comment]
I have managed to replicate this issue with a modified pong example. I have attached MRP to the main post.

**Comment by Faless** [comment]
Hi @Withaust thank you for the detailed report and MRP.

I was able to confirm the crash and opened https://github.com/godotengine/godot/pull/96464 which should fix the issue.
