### ISSUE TITLE
Exported C# project crashes on macOS when quit with CMD + Q

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [godotengine/godot#96353]
### Tested versions

4.3 stable

### System information

macOS Sonoma 14.6.1

### Issue description

When I quit my exported game with CMD+Q, I get a pop-up window telling me the game has quit unexpectedly. This only happens for the exported game - the version that runs in the editor doesn't have this problem. This is a problem, as it means end users will experience this.

[Exported Crash Report.txt](https://github.com/user-attachments/files/16822260/Exported.Crash.Report.txt)

The main error appears to be a Segmentation Fault coming from the InputMap destructor:

Thread 0 Crashed:: MainThrd Dispatch queue: com.apple.main-thread
0   libc++abi.dylib               	    0x7ff80e3981d7 __dynamic_cast + 23
1   GameName         	       0x106933c7c RefCounted::unreference() + 204
2   GameName         	       0x1069ad801 0x103612000 + 54114305
3   GameName         	       0x10668165d 0x103612000 + 50787933
4   GameName         	       0x10667f3be InputMap::~InputMap() + 542
5   GameName         	       0x103f6326d Main::cleanup(bool) + 1341
6   GameName         	       0x103f25542 main + 402
7   dyld                          	    0x7ff80e053345 start + 1909

When running the game from the command line, I get this additional error, which may or may not be related:
> ERROR: 1 RID allocations of type 'N26RendererEnvironmentStorage11EnvironmentE' were leaked at exit.
zsh: segmentation fault  ./bin/mac/GameName.app/Contents/MacOS/GameName

### Steps to reproduce

Not sure. This error doesn't occur on simple projects I've tested. Since it's related to the InputMap, I've tested my game with all action key bindings removed, and it still occurs. Granted I am modifying them at runtime, overwriting the defaults with what I find in the save file. The methods I'm calling from InputMap are:
- ActionGetEvents
- ActionEraseEvents
- ActionAddEvent
- ActionEraseEvent

However since the problem occurs even with no keybindings set in the save file, I suspect it's only affected by ActionGetEvents, ActionEraseEvents and ActionEraseEvent.

### Minimal reproduction project (MRP)

No. This error does not occur on simple projects I've tested. And unfortunately, my game is not something I can distribute.

**Comment by Avantir-Chaosfire** [comment]
Oh, this also happens when quitting the game by emitting the NotificationWMCloseRequest notification. It doesn't need to be by CMD+Q

**Comment by raulsntos** [comment]
Sounds similar to other issues that have been fixed recently. Can you try [Godot 4.4-dev.1](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-1/)?

**Comment by Avantir-Chaosfire** [comment]
@raulsntos I can confirm this issue is fixed in 4.4-dev.1. Thanks! Closing.

**Comment by raulsntos** [comment]
Thanks. Then it was probably fixed by https://github.com/godotengine/godot/pull/93172.

**Comment by Avantir-Chaosfire** [comment]
This was fixed on 4.4-dev1 (confirmed a second time) but this bug has returned on 4.4.0 and 4.4.1.

Edit: Still on Sonoma 14.6.1

Edit 2: This time I think I can get a working binary that reproduces the issue, but I still can't provide a minimal reproduction project.

**Comment by raulsntos** [comment]
Are you getting the exact same error as the original report?

Also, there were many releases between 4.4-dev1 and 4.4.0. Would you be able to test other 4.4 preview releases to try and find the first version that reintroduces the bug? Here are the versions you could try:

- [4.4-dev2](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-2/)
- [4.4-dev3](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-3/)
- [4.4-dev4](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-4/)
- [4.4-dev5](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-5/)
- [4.4-dev6](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-6/)
- [4.4-dev7](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-7/)
- [4.4-beta1](https://godotengine.org/article/dev-snapshot-godot-4-4-beta-1/)
- [4.4-beta2](https://godotengine.org/article/dev-snapshot-godot-4-4-beta-2/)
- [4.4-beta3](https://godotengine.org/article/dev-snapshot-godot-4-4-beta-3/)
- [4.4-beta4](https://godotengine.org/article/dev-snapshot-godot-4-4-beta-4/)
- [4.4-rc1](https://godotengine.org/article/release-candidate-godot-4-4-rc-1/)
- [4.4-rc2](https://godotengine.org/article/release-candidate-godot-4-4-rc-2/)
- [4.4-rc3](https://godotengine.org/article/release-candidate-godot-4-4-rc-3/)

**Comment by AThousandShips** [comment]
@Avantir-Chaosfire Have you been able to test this?

**Comment by shana** [comment]
@Avantir-Chaosfire Closing it as fixed, we can't repro without an MRP and we don't know if your new crash is the same as the old one. If you have new crash info for us, feel free to reopen.
