### ISSUE TITLE
PBD renaming functionality assumes file is present when it shouldn't

### ISSUE THREAD

**Issue by ryevdokimov** [godotengine/godot#96350]
### Tested versions

Since: https://github.com/godotengine/godot/commit/e73f40e26067cf265e311bbb895b80853574cd93

### System information

N/A

### Issue description

In short, https://github.com/godotengine/godot/pull/87117 makes the assumption mentioned in the title resulting in error like this, which is now possible after this PR https://github.com/godotengine/godot/pull/93972: 
![image](https://github.com/user-attachments/assets/932e6eb0-c892-41fa-8149-84c57c90d26e)

See comments here for details: https://github.com/godotengine/godot/pull/93972#issuecomment-2321833260

![image](https://github.com/user-attachments/assets/62e1cd98-2c20-4bc3-9642-397f17aae368)

### Steps to reproduce

Build: https://github.com/godotengine/godot/commit/f0ee0bdd376c7d32adb83754e4ae5899dba37f91
Add a plugin like Godot-Jolt that has an entry for PBD in the header (may have to build this for 4.4)
Make sure .godot folder is deleted
Open the project

### Minimal reproduction project (MRP)

N/A

**Comment by Christian-Haag-Fernandez** [comment]
Having the same issue in 4.3 stable. 
![Screenshot 2024-08-30 141400](https://github.com/user-attachments/assets/5d08b5c9-de22-47dd-85a4-efdac0b0fc7e)

tried reinstalling Jolt but no luck. Also tried renaming the dll to pdb for kicks and that just produced more errors.

**Comment by mihe** [comment]
If the errors bother you then you can just download the debug symbols for Godot Jolt [here](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) and extract them alongside the DLLs.

**Comment by Christian-Haag-Fernandez** [comment]
> If the errors bother you then you can (until this is fixed) just download the debug symbols for Godot Jolt [here](https://github.com/godot-jolt/godot-jolt/releases/tag/v0.13.0-stable) and extract them alongside the DLLs.

It does bother me a bit, so I'll go ahead and do this. Thank you!
