### ISSUE TITLE
RayCast2D arrows displayed wrong

### ISSUE THREAD

**Issue by pjlg** [godotengine/godot#9636]
** Ubuntu 14.04 - 2.1.4-BETA :**

**Issue description:**

RayCast2D arrows will displayed wrong in the editor.

**Steps to reproduce:**
Just create a new RayCast2D object. The arrow will be displayed wrong, 90 degrees counterclockwise.

**Comment by bojidar-bg** [comment]
(Should be) fixed by #10054.
