### ISSUE TITLE
OmniLight3D Won't Cast Shadows Past a Distance of ~171 Units

### ISSUE THREAD

**Issue by The-Raphie** [godotengine/godot#96361]
### Tested versions

- Tested in and reproducible in: v4.3.stable.official [77dcf97d8], v4.2.stable.official [46dc27791], v4.1.stable.official [970459615]

### System information

Godot v4.3.stable - EndeavourOS #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (nvidia; 555.58.02) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

When casting a shadow with an `OmniLight3D` with a distance more than ~171 units from the object being casted on, and an `omni_attenuation` of 0, the shadow becomes too unclear to the point of it not being able to be seen. With an `omni_attenuation` greater than 0, the shadow becomes unclear with an even shorter distance from the object.
![image](https://github.com/user-attachments/assets/23c274d8-96c2-4700-aaa5-62d4cb8041a2)

### Steps to reproduce

1. Create a 3D scene.
2. Add a `MeshInstance3D` node as a child of root with its `mesh` being a `PlaneMesh`.
3. Add another `MeshInstance3D` node as a child of root with its `position` being (0,1,0), and its mesh being a `BoxMesh`.
4. Add an `OmniLight3D` node as a child of root with its `omni_range` being 300, its `omni_attenuation` being 0, its `position` being (0,171,0), and its `shadow_enabled` property toggled on.
5. Toggle off preview sunlight in the scene.

### Minimal reproduction project (MRP)

[godot-issue.zip](https://github.com/user-attachments/files/16823052/godot-issue.zip)

**Comment by passivestar** [comment]
Related: https://github.com/godotengine/godot/issues/92551

**Comment by The-Raphie** [comment]
Which version should this bug be patched by?

**Comment by AThousandShips** [comment]
We don't know what's wrong yet and haven't identified a solution so we don't know yet

**Comment by The-Raphie** [comment]
Wait, could it have anything to do with the limited size of shadow maps?
