### ISSUE TITLE
Glow effect doesn't work on non-opaque alpha-enabled materials

### ISSUE THREAD

**Issue by Mudley** [godotengine/godot#9637]
**Ubuntu 17.04, Windows 7 - Godot version: 2.1.4**

**Issue description:**
When an alpha-enabled material has an alpha channel inferior to 255, no glowing will show up.

**Comment by kubecz3k** [comment]
I'm sorry but I don't think this one will be fixed in 2.x branch. Part of the reasoning behind writing new renderer in 3.0 was to finally fix that kind of bugs.
