### ISSUE TITLE
Can't handle/store Animation

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#96374]
### Tested versions

- Reproducible 4.4.dev1 (a5830f6eb9fe25fbb7e58a723dbea8509aec8a85)

### System information

Win10

### Issue description

Fails to save animation. Also, editing the animation does not seem to be working well, and references to the animation resource from the editor seem to be corrupted.

![image](https://github.com/user-attachments/assets/40af555e-0209-4196-a4b4-74e883505897)

### Steps to reproduce

1. Open any scene
2. Add AnimationPlayer or Tree
3. Add Animation
4. Save

### Minimal reproduction project (MRP)

[make-anim.zip](https://github.com/user-attachments/files/16824162/make-anim.zip)

However, the animation is empty because it cannot be saved properly.

**Comment by AThousandShips** [comment]
Can't replicate on latest master it seems, can you confirm? Might have been fixed by:
* https://github.com/godotengine/godot/pull/96344

Fixed a number of weird regressions

**Comment by TokageItLab** [comment]
@AThousandShips The problem occurs even in the latest version. I don't think it is an environment-dependent problem, but I will check again as soon as bisecting is finished.

**Comment by AThousandShips** [comment]
Tested right now with latest master and I can't replicate at all from the instructions above, the version you listed is older than that fix

**Comment by TokageItLab** [comment]
I checked the latest (61598c5c88d95b96811d386cb20d714c35f4c6d7) but reproducible.

**Comment by AThousandShips** [comment]
Weird then the steps aren't sufficient to reproduce it

**Comment by TokageItLab** [comment]
Ah I see! The bin output path has changed due to an update of llvm, so current master may be fixed it.

**Comment by TokageItLab** [comment]
Fixed by https://github.com/godotengine/godot/pull/96344
