### ISSUE TITLE
Copy System Info shows incorrect rendering method when overriden on command line

### ISSUE THREAD

**Issue by alvinhochun** [godotengine/godot#96380]
### Tested versions

- Reproducible on v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - dedicated Intel(R) UHD Graphics 620 (Intel Corporation; 31.0.101.2128) - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 Threads)

### Issue description

When opening a project in the editor with the rendering driver and/or rendering method specified in the command line, 

### Steps to reproduce

- Run:  
```
Godot_v4.3-stable_win64_console.exe --rendering-driver d3d12 --path D:/empty --editor
```
- Select "Copy System Info" from menu
- Paste the value somewhere and check that it contains "GLES3 (Compatibility)"

### Minimal reproduction project (MRP)

[empty.zip](https://github.com/user-attachments/files/16824466/empty.zip)

**Comment by bruvzg** [comment]
Should be fixed by https://github.com/godotengine/godot/pull/95887
