### ISSUE TITLE
[Windows] New files are not being detected by editor

### ISSUE THREAD

**Issue by yahkr** [godotengine/godot#96397]
### Tested versions

Reproducible in
v4.4.dev1.mono.official [28a72fa43]
v4.4.dev.custom_build [da230f384b90360ec108ce1be2347a327d68ca07]

Not Reproducible in:
v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.4.dev1.mono - Windows 10.0.22631 - Intel(R) Core(TM) i9-14900K (32 Threads)

### Issue description

New files are not being detected by the editor when created outside of the editor (via file explorer, saving from blender etc)

### Steps to reproduce

1. Open project in editor.
2. Switch to file explorer  
3. Duplicate icon.svg using file explorer.
4. Switch back to editor
5. Notice icon.svg - Copy is not detected/imported.

Shutting down the editor and re-opening it detects the new icon.svg copy

### Minimal reproduction project (MRP)

default project

**Comment by JekSun97** [comment]
I also observed this problem when migrating my project to 4.3
