### ISSUE TITLE
Node Duplication enhancement

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#964]
This  is a small request to provide a better usability for duplicating nodes within godot.

Right now when you duplicate a set of nodes they will always be placed at the end of the scene tree. This may give problems with drawing order and you the first thing I always did was to move the duplicated nodes up to the original node. This can take some time especially if you have lots nodes you are duplicating.

Recommended bahavior would be to place the duplicates directly below the node you wanted to duplicate and then select that node. This way you keep the order of the overall scene tree.

**Comment by akien-mga** [comment]
I agree, though it's not a huge bother to me as I don't have so many nodes, I would find it natural that duplicated nodes are inserted just after the nodes that are being copied.

**Comment by akien-mga** [comment]
I _think_ this might be relatively easy to implement, so labelling as a junior job. Feel free to prove me wrong :D

**Comment by akien-mga** [comment]
I've had a quick look, and it's not as easy as I thought, since it relies on ```Node::add_child(Node *p_child)``` which does not seem to have support for _inserting_ a child between two existing children, but simply does a push_back instead.
