### ISSUE TITLE
Compiling Godot engine from source using emscripten and scons

### ISSUE THREAD

**Issue by kalio12** [godotengine/godot#96432]
### Tested versions

Tested version: 4.3

### System information

tried compiling on Ubuntu 22.04.3

### Issue description

Hey guys, im attempting to compile the godot engine from source using emscripten and scons, but i am getting the following error. I am using the following command: scons platform=web target=template_release
```
error: failure to execute js library "/home/XXXX/godot/platform/web/js/libs/library_godot_audio.js": SyntaxError: Unexpected token '?',
error: use -s VERBOSE to see more details
Internal compiler error in src/compiler.js!
Please create a bug report at https://github.com/emscripten-core/emscripten/issues/
with a log of the build and the input files used to run. Exception message: "SyntaxError: Unexpected token '?'" | SyntaxError: Unexpected token '?'
at Object.load (eval at load (/usr/share/emscripten/src/compiler.js:38:8), :206:14)
at runJSify (eval at load (/usr/share/emscripten/src/compiler.js:38:8), :75:20)
at Object. (/usr/share/emscripten/src/compiler.js:81:3)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47
em++: error: '/usr/bin/node /usr/share/emscripten/src/compiler.js /tmp/tmpw9npogwl.json' failed (returned 1)
scons: *** [bin/godot.web.template_release.wasm32.js] Error 1
scons: building terminated because of errors.
```

Does anyone know what is causing this?

### Steps to reproduce

install scons and emscripten, navigate to root folder of godot source code folder, and run the following command: 

scons platform=web target=template_release

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
What version of emscripten are you using?

**Comment by kalio12** [comment]
im using the most recent version- i pulled it down last night.

**Comment by kalio12** [comment]
im using the most recent version- i pulled it down last night.

**Comment by AThousandShips** [comment]
Try using `3.1.64`, that's the most recent version with confirmed support

**Comment by kalio12** [comment]
that seems to have worked, however now after adding an encryption key in the 'export' section of godot (as well as using that same encryption key when compiling the template), i get the following error:
Godot couldnt load project data at path ".". Is the .PCK file missing?

**Comment by AThousandShips** [comment]
Please check the instructions or ask in the [other community channels](https://godotengine.org/community/) for support

Closing as the compilation issues have been solved, thank you for your report
