### ISSUE TITLE
Add script editor shortcut to delete current line

### ISSUE THREAD

**Issue by xPucTu4** [godotengine/godot#9643]
**Operating system or device - Godot version:**
Godot 3 - Any platform
May also be applied to godot 2.1.4 while still in beta (i hope)

**Issue description:**
Must code editors have shortcut to delete the current where the cursor is and moving all lines below that line up.
By default:
Notepad++: ctrl-l
Visual Studio: ctrl-l
Eclipse: ctrl-d
VS Code: ctrl-shift-k
Atom: ctrl-shift-k
Vanilla notepad: none (can be emulated with Home, Shift-End, Del)

**Steps to reproduce:**
In the editor settings, in the shortcuts tab there is no option to bind a key to delete the current line.
Note that ctrl-x may look as a possible solution, but you loose the clipboard content that way.

**Suggestion:**
Because by default ctrl-l is go-to-line, you can use ctrl-d or just leave it blank so the users can choose one.

**Comment by BeayemX** [comment]
For the moment you can use ctrl-x (without text being selected) to cut the entire line.

**Comment by xPucTu4** [comment]
As i noted in the original post, ctrl-x will override the content of the clipboard.
Also the code to fix this would be identical to the ctrl-x code, but without copying the line to clipboard.
So i hope it would be easy to add this functionality.

I am sure that many people will benefit from this addition that is standard in many editors.

**Comment by vnen** [comment]
Well, Ctrl + L in Visual Studio and Notepad++ also puts the line in the clipboard. Not that we should copy them, but there's precedents to the current Ctrl + X.

In any case, an option with an unassigned shortcut might be useful.

**Comment by timoschwarzer** [comment]
All IntelliJ-based editors have Ctrl+Y to delete the current line without overriding the clipboard, Ctrl+X to cut the line and Ctrl+D to duplicate the current line.
