### ISSUE TITLE
Reflecftionprobes not influenced by reflectionatlas size

### ISSUE THREAD

**Issue by snektailmeat** [godotengine/godot#96433]
### Tested versions

reproducable in 4.3 not in 3.5

### System information

win 11 vulkan

### Issue description

like the title says change the atlas size in the project setting seem to not affect probes

### Steps to reproduce

just change atlas size and look at a mirror ball or smth idk
![Screenshot 2024-09-01 143522](https://github.com/user-attachments/assets/84c15229-0cd0-4ad9-8309-d999d55e8e07)
no change in quality
![Screenshot 2024-09-01 143845](https://github.com/user-attachments/assets/7f3277fc-f6b4-468b-955d-44312808a1ee)

### Minimal reproduction project (MRP)

[reflectest.zip](https://github.com/user-attachments/files/16828921/reflectest.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92518

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
