### ISSUE TITLE
Dropdown menu to select method

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#9644]
Hello there, so I was tweaking the engine to see if I could help improve it, and since I was struggling when I had to connect signals to methods, and I found some cool usages for that, I was thinking about improving the connection menu. My ideas were:

1. Add a dropdown menu to select a list of all the currently available methods of the node
1. When selecting an already existing method automatically add the needed arguments
1. Be able to edit an already connected signal

Seems like someone tried this before but for some reason he/she commented the code as we can see in [connections_dialog.cpp](https://github.com/godotengine/godot/blob/master/editor/connections_dialog.cpp#L116-L143)

I can try to implement it myself and make a pull request, but I'll need some guidance on that  :>

Then I designed this just for concept
![new_connection_concept](https://user-images.githubusercontent.com/10171059/28215710-4b3202a4-6885-11e7-9e84-30bb0719faea.png)

**Comment by vnen** [comment]
> Seems like someone tried this before but for some reason he/she commented the code as we can see in connections_dialog.cpp

Well, this code is there since the [dawn of time](https://github.com/godotengine/godot/blame/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/tools/editor/connections_dialog.cpp#L117-L143) (0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac).

**Comment by henriiquecampos** [comment]
I don't understand cpp very well, but is there an error/bug with this block of code? It seems like it works pretty well

**Comment by henriiquecampos** [comment]
@reduz with the current implementation of Animations' tab, is it possible to also add this? I saw that we can add "Function Tracks" that recognizes custom methods, so...I'm just wondering if this can be added as well

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/239, as feature proposals are now tracked in the Godot proposals repository.
