### ISSUE TITLE
Typing second parameter in Node.reparent() on static node crashes editor

### ISSUE THREAD

**Issue by TAGames** [godotengine/godot#96442]
### Tested versions

Reproducable in v4.4.dev1.official [28a72fa43]

Not reproducable in 4.3 stable

### System information

Godot v4.4.dev1 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 32.0.15.6081) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

Had a hard time finding an appropiate title. See steps to reproduce.

### Steps to reproduce

Type true/false as second parameter in `.reparent()` and Godot crashes.
Does not crash when pasting the complete script with second parameter already written.
Does not crash for non static nodes.

```
extends Node3D
class_name Singleton

static var Instance

func _ready() -> void:
	Singleton.Instance.reparent(get_tree().root,   ) 
```

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
This issue was already fixed in master by #96243

![image](https://github.com/user-attachments/assets/c96ed107-f5ee-45a2-8530-941204ec9539)

**Comment by TAGames** [comment]
Thanks and sorry for creating another post.

**Comment by matheusmdx** [comment]
> Thanks and sorry for creating another post.

Don't worry, is better a duplicate/solved issue than a issue not reported.
