### ISSUE TITLE
Can't drag items from FileSystem module to floating script window

### ISSUE THREAD

**Issue by PIZZA-ALERT** [godotengine/godot#96454]
### Tested versions

- Reproducible in Godot 4.3.stable
- Unsure of other versions

### System information

Windows 11 23H2

### Issue description

A quick way to reference an item from the FileSystem in a script is to click+drag it from the FileSystem module into the script editor. Holding Ctrl during this produces a pre-formatted result as well. It's an awesome feature.

Unfortunately, if the script editor has been set to floating by clicking the "make the script editor floating" button at the top-right of the script editor, this click+drag function (with or without Ctrl) does not work. It seems to not even be able to register in the 2nd window that you're trying to drag something in.
![image](https://github.com/user-attachments/assets/69952943-9f5d-4c8e-9031-af49e1ef34d2)

I have multiple monitors, and using the floating script editor is a great way for me to see everything at once. Having the functionality in either floating or not floating should be a thing!

### Steps to reproduce

1) Open a project with multiple scenes, files, etc. ("items") in the res:// folder.
2) View a script in the Script Editor screen.
3) Locate an item in the FileSystem module, typically either found on the lower-left or bottom of your Godot window.
![image](https://github.com/user-attachments/assets/f220c762-7b5d-4d9e-91dd-84d04532bd7b)
4) Click-and-drag this item into the script, with or without Ctrl. Observe that something appeared in your script and how seamless that was.
![image](https://github.com/user-attachments/assets/e30857e6-7441-492d-9e1a-a1d53d4b1a48)
5) Click the "Make the script editor floating" button at the top-right of the script editor. A second window of the script editor should appear.
![image](https://github.com/user-attachments/assets/c1ca2f7d-9196-481a-88a3-056389386114)
6) Somehow make it so you can see both the original window and the new script window (easier with multiple monitors, but splitting down the middle of a 16:9 monitor should be fine).
7) Repeat steps 3 and 4, but into the script editor 2nd window. Or at least, attempt to. Notice how it doesn't work.

### Minimal reproduction project (MRP)

Basic process, any project will do.

**Comment by AThousandShips** [comment]
Thank you for your report, this has already been fixed in the latest version and a fix will be added to 4.3.1, to confirm you can test using [4.4.dev1](https://godotengine.org/article/dev-snapshot-godot-4-4-dev-1/)

Consolidating in the original report for the same problem:
* https://github.com/godotengine/godot/issues/95639
