### ISSUE TITLE
Resetting the pivot of a sprite with the "set rotation pivot tool", resets the temp pivot, not the actual pivot.

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#96461]
### Tested versions

4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4683) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When you use this function, it resets the temp pivot, not the actual pivot, so the tool tip is wrong. The current description makes it sounds like you would be moving the pivot point back to the center of the sprite (0,0 offset) while leaving its position intact.

![image](https://github.com/user-attachments/assets/5fd41b01-7749-4aa7-b90e-6f465a0c9d71)

Current:
Click this button while holding Shift to put the rotation pivot in the center of the selected nodes.
Expected:
Click this button while holding Shift to put the temporary rotation pivot in the center of the selected nodes.
OR
Shift-click this button to put the temporary rotation pivot in the center of the selected nodes.

*Note: I think it would be great to also have the option to reset the main pivot point back to the center of the sprite while leaving it's global position intact*

### Steps to reproduce

1. Create a 2D scene with a Sprite2D.
2. Select the pivot tool and click somewhere, note the red pivot is set to that location.
3. Shift click somewhere else to set the temporary blue pivot point somewhere else.
4. Shift click the button, note that the blue temporary pivot point moves to the "center" red pivot point.

https://github.com/user-attachments/assets/f4fd6a58-9327-4672-8bef-c1e21f766635

### Minimal reproduction project (MRP)

NA

**Comment by KoBeWi** [comment]
It says "rotation pivot", but I guess "temporary rotation pivot" is clearer and consistent with above line.
The behavior is as intended.

**Comment by Arnklit** [comment]
@KoBeWi well the entire tool says "Click to change the object's rotation pivot", so "rotation pivot" does not refer to the temporary pivot in that context since you can change the main pivot with the tool.

**Comment by KoBeWi** [comment]
The tool was just reused for temporary pivot, since they are similar. You can reset the regular pivot in the inspector.

**Comment by Arnklit** [comment]
> The tool was just reused for temporary pivot, since they are similar. You can reset the regular pivot in the inspector.

Well if you reset the pivot in the inspector the sprite "moves" when the offset is cleared right? It would be nice to have the option to recenter the actual pivot on the sprite while leaving the sprites final position in place.

**Comment by KoBeWi** [comment]
That should be a separate proposal. Currently you can do that by manually placing the pivot in the center using the pivot tool.
