### ISSUE TITLE
Add ability to receive iOS APNS notifications

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#96474]
### Tested versions

4.3

### System information

Macos

### Issue description

Currently iOS godot can't register/receive APNS notifications

### Steps to reproduce

Just try to get APNS

### Minimal reproduction project (MRP)

Current `AppDelegate` implementation doesn't have `didRegisterForRemoteNotificationsWithDeviceToken`
 handler https://github.com/godotengine/godot/blob/master/platform/ios/app_delegate.mm#L69

 below is swift portion of currently working implementation:
 ```
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let tokenParts = deviceToken.map { data in String(format: "%02.2hhx", data) }
        let token = tokenParts.joined()
        os_log(.debug, "didRegisterForRemoteNotificationsWithDeviceToken: \(token)")
        apnsTokenRegister(token: token)
    }
```

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

**Comment by theromis** [comment]
https://github.com/godotengine/godot-proposals/issues/10633
created
