### ISSUE TITLE
`TooltipLabel` looks blurry when `content_scale_factor > 1`

### ISSUE THREAD

**Issue by AdamLearns** [godotengine/godot#96495]
### Tested versions

-Reproducible in `v4.2.1.stable.official [b09f793f5]`
-Reproducible in `v4.3.stable.official [77dcf97d8]`

### System information

M2 macOS - Sonoma 14.6.1

### Issue description

When you modify `content_scale_factor` (e.g. by setting it to `4`), the regular labels look crisp, but `TooltipLabel`s in particular look blurry:

<img width="812" alt="image" src="https://github.com/user-attachments/assets/56da6aa0-ef7b-43fb-9cab-90afa0a8fe88">

This happens even when using an MSDF font (the minimal repro uses Google's Roboto font).

### Steps to reproduce

- Add a tooltip to any control
- Set `content_scale_factor` to 4
- Hover over the control and look at the tooltip

### Minimal reproduction project (MRP)

[repro.zip](https://github.com/user-attachments/files/16841198/repro.zip)

**Comment by Giganzo** [comment]
Sounds like it’s same issue as https://github.com/godotengine/godot/issues/54030 ?

**Comment by akien-mga** [comment]
Indeed, consolidating in #54030.

**Comment by AdamLearns** [comment]
Ah, thank you both! 🙏
