### ISSUE TITLE
VisualScript: Godot 3.0, no literal values

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9649]
There should be a way to create a literal primitive in VisualScript. So far as I can tell, this is currently impossible. You first have to create a member or local variable and then you can create a Variable / LocalVarGet node that retrieves it via name. However, it would be nice if I could just make a Literal node, set the type to String (or have respective StringLiteral, IntLiteral, etc. nodes), and then set the value to "Hello, World", or even an entire paragraph of content (in a TextEdit).

**Comment by Hinsbart** [comment]
Isn't that what the "Constant" node does?
![const_vs](https://user-images.githubusercontent.com/8281916/28237741-c993014a-6946-11e7-9b52-f34f420906c1.png)

Note that you don't specifiy the type and value in the graph-node itself, but in the inspector.

**Comment by willnationsdev** [comment]
Ah, I see. That was confusing. "Constants" are usually integer-only and as such I never realized that you could edit them in the Inspector.
