### ISSUE TITLE
Game crashes when AudioStreamPlayer2D plays sound after reloading scene

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot#96506]
### Tested versions

- Reproducible in 4.3.stable
- Reproducible in 4.2.1.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6094) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

A godot game crashes with this fairly specific combination of features:
- The scene has been reloaded via get_tree().reload_current_scene()
- A subviewport has its world set to share with the main viewport
- A sound is played by an AudioStreamPlayer2D
- Happens occasionally, often after a handful of scene reloads / sounds played

This does not occur if:
- The scene hasn't first been reloaded.
- You use an AudioStreamPlayer instead of an AudioStreamPlayer2D
- If play is never called on the AudioStreamPlayer2D

When the game crashes, there are usually no errors printed to the log, however sometimes before crashing, you get the following error printed multiple times:
```
E 0:00:03:0399   affine_invert: Condition "det == 0" is true.
  <C++ Source>   core/math/transform_2d.cpp:51 @ affine_invert()
```

There's some discussion of this bug in the forums here: https://forum.godotengine.org/t/game-crashing-on-audiostreamplayer2d-play/50531

### Steps to reproduce

- Load the MRP below.
- Enter play mode, press R to reload the scene (the particles are there to show reload working)
- Press space to play a sound.
- After pressing R and space for some random number of times, the game will silently crash without printing any error. This sometimes takes a while to crash and sometimes happens quickly, usually within a handful of restarts and many sounds played

### Minimal reproduction project (MRP)

[audio-crash-bug.zip](https://github.com/user-attachments/files/16843453/audio-crash-bug.zip)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I didn't reproduce a crash on Linux with 4.4.dev (8120e032) in the MRP, but I did manage to get an error to show up:
```
Played sound!
Restarted scene!
Played sound!
Restarted scene!
ERROR: Parameter "data.tree" is null.
   at: get_tree (./scene/main/node.h:471)
Restarted scene!
Played sound!
Restarted scene!
Played sound!
Restarted scene!
Played sound!
Restarted scene!
Played sound!
Restarted scene!
ERROR: Parameter "data.tree" is null.
   at: get_tree (./scene/main/node.h:471)
```

I'm using a dev editor build, this may be a crash in a release export.

**Comment by akien-mga** [comment]
Thanks! Consolidating in #89212.
