### ISSUE TITLE
Latest master build is not executable

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#9651]
**Operating system or device - Godot version:**
Antergos x86_64 - Godot master br b1ca62a

**Issue description:**

Built binary is `application/x-sharedlib` instead of `application/x-executable`
Still run when launched from terminal

**Steps to reproduce:**
`scons p=x11 builtin_openssl=yes -j 8`

**Comment by akien-mga** [comment]
Can't reproduce on Mageia 6 x86_64, same commit:
```
$ file bin/godot.x11.tools.64
bin/godot.x11.tools.64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2bf6a99c69dc519b3eaa3eac668896b0c3c7c008, not stripped
$ mimetype bin/godot.x11.tools.64
bin/godot.x11.tools.64: application/x-executable
```

**Comment by Noshyaar** [comment]
```
$ file godot.x11.tools.64    
godot.x11.tools.64: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=fcd15f293a5d97129f6df54384fdfef287d2dbd9, with debug_info, not stripped
$ mimetype godot.x11.tools.64
godot.x11.tools.64: application/x-sharedlib
```

**Comment by Calinou** [comment]
I was able to reproduce this, long time ago (back when I was using Fedora 23); I don't know what causes this, though.

**Comment by vnen** [comment]
Could that be some problem with SCons? What is your SCons version?

**Comment by Noshyaar** [comment]
```
SCons by Steven Knight et al.:
	script: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
	engine: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
	engine path: ['/usr/lib/python2.7/site-packages/SCons']
```

**Comment by eon-s** [comment]
I'm always getting this when not doing an LLVM build (*buntu 16.10/17.04, same scons as previous answer), can run it by the console, though.

**Comment by Noshyaar** [comment]
I tried `use_llvm=yes` but the binary is still a sharedlib.
![image](https://user-images.githubusercontent.com/26753932/28317267-68d680c8-6bf0-11e7-987a-64b4b08a3918.png)

**Comment by BrainBlasted** [comment]
Reproduced with `scons platform=x11 use_llvm=yes builtin_openssl=yes`. Running chmod +x on the generated file allows it to run, but the editor crashes if you try to edit any project, and opens a duplicate main menu if you hit run.

**Comment by vnen** [comment]
Apparently this is not a bug:

- https://stackoverflow.com/questions/34519521/gcc-creates-a-shared-object-instead-of-an-executable-binary
- https://stackoverflow.com/questions/41398444/gcc-creates-mime-type-application-x-sharedlib-instead-of-application-x-applicati

It's just the way that the compiler links the binary versus the way `file`/`mimetype` works. There's a "solution" to add `--no-pie` in the linker flag but it's not recommended.

**Comment by BrainBlasted** [comment]
Hmm, shouldn't that problem not happen if you use 'use_llvm=yes', since that compiles with Clang instead of gcc, or am I mistaken?

**Comment by vnen** [comment]
Clang would do the same thing, AIUI.

**Comment by eon-s** [comment]
With 'use_llvm=yes' (on Ubuntu 16.10 and 17.04 at least) the result is this:

> godot.x11.tools.64.llvm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped

There must be something different on Antergos and Mageia and Ubuntu and etc...

**Comment by Noshyaar** [comment]
I think it's because of ["Enable-SSP-and-PIE-by-default.patch"](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/llvm&id=787823616bc31184c5fc4b2eb21ec9d899e0029f) in Arch Linux repositories, since this issue happens at around the same time clang updating from 4.0.1-3 to 4.0.1-4

**Comment by eon-s** [comment]
And this on Ubuntu https://wiki.ubuntu.com/SecurityTeam/PIE , clang here is 4.0.0-1

**Comment by BrainBlasted** [comment]
Ah, forgot to mention that I am using Arch, clang version 4.0.1-4

**Comment by akien-mga** [comment]
So, not a bug actually, as mentioned above by @vnen.

If you're affected by this, it's just that your distro decided to build all binaries as `-pie`, and running `file` on stuff in `/usr/bin` would likely list many of them as shared libraries too, unless those projects specifically pass `-no-pie`. I don't see a reason why we should override it, so we'll live with it :)

**Comment by marcelofg55** [comment]
Sorry for commenting on a closed issue but this is still a problem on for example Ubuntu. Godot exported projects can't be run from the File Manager due to being detected as a shared library. If I compile the templates with `-no-pie` the exported project gets detected correctly and can be run as expected on the File Manager.
So is there a drawback on adding the `-no-pie` flag? Maybe we can add it as an option? Like `enable_no_pie`?

**Comment by eon-s** [comment]
I think that the `-no-pie` option should be added because many systems have it as `-pie` by default now and is a bit annoying to fix.

**Comment by Calinou** [comment]
For future reference, this issue was originally fixed by https://github.com/godotengine/godot/pull/23542 but it was eventually reverted by https://github.com/godotengine/godot/pull/50737 for security reasons.
