### ISSUE TITLE
 OS.get_environment("something") delivers correct value despite OS.has_environment("something") reports false

### ISSUE THREAD

**Issue by Franz-Inc** [godotengine/godot#96521]
### Tested versions

- Reproducible in 4.3 stable, 4.2 stable, 4.1.1 stable

### System information

Windows 11 x86_64 · 64 bit (not tested on .net version). This bug not reproducible on MacOS.

### Issue description

After using OS.set_environment to set a custom variable to a value, OS.has_environment still results in false, despite OS.get_environment still delivers the set value.

### Steps to reproduce

Reproduce using the following code (as included in the MRP):

```
extends Node

func _ready() -> void:
	OS.set_environment("something", "hello")
	print("called OS.set_environment for 'something' with value 'hello'.")
	print("OS.has_environment('something'): ", OS.has_environment("something"))
	print("OS.get_environment('something'): ", OS.get_environment("something"))
```
	
Outcome is:

```
called OS.set_environment for 'something' with value 'hello'.
OS.has_environment('something'): false
OS.get_environment('something'): hello
```

### Minimal reproduction project (MRP)

[environment-test.zip](https://github.com/user-attachments/files/16847979/environment-test.zip)

**Comment by akien-mga** [comment]
CC @bruvzg
