### ISSUE TITLE
OmniLight3D & SpotLight3D Attenuation field - Curve and Presets are missing

### ISSUE THREAD

**Issue by pixeltrain3D** [godotengine/godot#96537]
### Tested versions

Godot 4.3 stable and newer

### System information

Godot v4.3.stable - macOS 13.6.9 - Vulkan (Forward+) - dedicated AMD Radeon Pro 580 - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

As you see in this screenshot, the attenuation field has no curve in the field and also no presets under the right mouse button:

<img width="356" alt="Missing options in Godot 4 3 stable" src="https://github.com/user-attachments/assets/876ca733-65d6-4a12-9ed5-f04b4ec2a7d4">

In comparision the expected behavior:

<img width="298" alt="Bildschirmfoto 2024-09-03 um 18 25 50" src="https://github.com/user-attachments/assets/a69511f5-3ff6-451d-ae84-4277c38dfa1f">
<img width="306" alt="Presets" src="https://github.com/user-attachments/assets/f265fb95-634b-4817-9fe8-a9a5d876aa0d">
a+

### Steps to reproduce

Make an OmniLight3D
Go to the Light-Settings

### Minimal reproduction project (MRP)

[lightattenutation.zip](https://github.com/user-attachments/files/16852673/lightattenutation.zip)

**Comment by AThousandShips** [comment]
This was done by design to fix a number of issues:
* https://github.com/godotengine/godot/pull/87583

This change shouldn't be reverted I'd say

**Comment by pixeltrain3D** [comment]
Ok, I see. Read the thread and I agree!
