### ISSUE TITLE
[macOS] Double click on any Run button resizes the editor window

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot#96534]
### Tested versions

4.3 stable

### System information

Godot v4.3.stable - macOS 14.6.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

Double click on the top of the editor window resizes it to full screen or the last known size, which is expected behavior. However, it also applies this behavior when you click on any of the _buttons_ situated on the top of the window – like the play, pause, and stop buttons, for instance. 

This would not be so annoying if it wasn't for the fact that running a game puts the focus on the game's window, and to click any button at all in the Editor it needs focus – which happens with a click. So one click brings back focus, while another click actually pressed the button underneath my mouse.... and together, they are a double click that ALSO resizes the window.

https://github.com/user-attachments/assets/bb801c43-d3d1-435c-a81b-47ce3f423263

### Steps to reproduce

Double click on the play or stop buttons in the right top corner of the Godot editor.

### Minimal reproduction project (MRP)

n/a

**Comment by bruvzg** [comment]
Can't reproduce it, it's possible to accidentally maximize the window by clicking exactly in between 2D/3D/Script buttons (and might be possible to do the same with button separators, but default theme seems to have no space there).

What's "Demo" menu? Is it from the plugin? Maybe adding it do something with the button container bounding box.

**Comment by AdriaandeJongh** [comment]
This behavior also happens for me in an empty project, so it doesn't seem to have anything to do with plugins. **However**, your comment did remind me that I use a tool on Mac (as are many other power Mac users) that helps with window management called BetterSnapTool, and loathe and behold: 

![Screenshot 2024-09-04 at 11 44 50](https://github.com/user-attachments/assets/ad1a068f-0f62-47dd-becb-f5cd81f65f64)


After disabling that, the behavior described in this issue no longer happens.

Sorry about the false alarm @bruvzg – I see you did make a PR that at least addresses this partially, so I'm happy I didn't completely waste your time.
