### ISSUE TITLE
Animation lost when opening projects created in 4.3

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#96553]
### Tested versions

- Reproducible: master[e2dd56bea7a1aa13fe74fd6eac049e4cbde0434c]
- Not reproducible: 4.4.dev1

### System information

Arch Linux

### Issue description

When opening a project created in 4.3, animations in AnimationPlayers are lost with this error:

```
ERROR: Condition "p_animation_library.is_null()" is true. Returning: ERR_INVALID_PARAMETER
   at: add_animation_library (scene/animation/animation_mixer.cpp:281)
```

Probably an regression from #70096

### Steps to reproduce

- Create a project in 4.3, add an AnimationPlayer in the scene and create a new Animation in it.
- Open the project with an editor built from master.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16862562/test.zip)

**Comment by akien-mga** [comment]
> Probably an regression from #70096

Confirmed, a local revert of that PR solves the issue (on top of 906a4e9db91c2c6b17a0cb1cddf2a96f64114646).

CC @rune-scape @godotengine/core @godotengine/animation

**Comment by rune-scape** [comment]
the underlying issue is that the hash for an empty String is different than the hash for an empty StringName
and the default animation library is an empty string
so when the String key is converted to a StringName, it hashes differently
making a PR
