### ISSUE TITLE
[C#] Can't attach debugger when launching project.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#96558]
### Tested versions

- Reproducible in: v4.4.dev.mono.custom_build.e2dd56bea (2024-09-03 15:38:17 UTC)
- Not reproducible in: 4.3.stable (still works now)

### System information

Godot v4.4.dev.mono (e2dd56bea) - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 (NVIDIA; 31.0.15.5123) - 13th Gen Intel(R) Core(TM) i5-13400F (16 Threads)

### Issue description

Unable to attach debugger when launching project on latest build.

It's OK to attach to a running instance.

![image](https://github.com/user-attachments/assets/07ebb916-9e7d-4fa1-b9b7-55d1ac21f15f)

My `launch.json` config for VSCode:
```jsonc
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(C#)Launch",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "dotnet: build",
            "program": "${env:GODOT}", // my path to latest godot build
            // "program": "C:\\Dev\\Godot\\4.3.stable\\Godot_v4.3-stable_mono_win64.exe",
            "args": [
                "--verbose"
            ],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "justMyCode": false,
            "stopAtEntry": false,
        },
        {
            "name": "(C#)Attach",
            "type": "coreclr",
            "request": "attach",
        },
    ]
}
```

### Steps to reproduce

Debug any project (by launching) on 4.4.dev.

### Minimal reproduction project (MRP)

Mrp with vscode `launch.json`: 

[DebuggerMRP.zip](https://github.com/user-attachments/files/16868241/DebuggerMRP.zip)

**Comment by AThousandShips** [comment]
Closing as fixed, if it returns please comment here and this can be reopened, and if you can identify when this was fixed adding that would be great information!
