### ISSUE TITLE
change `editor description` of a child scene causing multiple `open in editor` buttons in the Scene tab

### ISSUE THREAD

**Issue by conradax** [godotengine/godot#96567]
### Tested versions

Godot V4.4 dev1.official
Godot V4.4 dev[906a4e9db91c2c6b17a0cb1cddf2a96f64114646]

### System information

Godot v4.4.dev1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 590 Series (Advanced Micro Devices, Inc.; 31.0.21905.1001) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

In editor's Scene tab, a node of instanced scene has a button "open in editor"

What's wrong: there will be multiple "open in editor" buttons after changing the "editor description" of an instanced scene.

What's expected: there should be only one "open in editor" button and it already exists

P.S. I found this when i'm poking a instanced `.glb` scene's editor description.

### Steps to reproduce

1. create a scene
2. create another scene
3. add one scene into another
4. change instanced scene node's editor description

https://github.com/user-attachments/assets/0006fbcb-8dd8-43bc-9762-809c030fc12c

### Minimal reproduction project (MRP)

N/A

**Comment by Giganzo** [comment]
Can reproduce it in v4.3.stable too

**Comment by AThousandShips** [comment]
I've identified the code responsible for this, will take a look at fixing it

**Comment by Giganzo** [comment]
> I've identified the code responsible for this, will take a look at fixing it

Nice! Is it #82916?

**Comment by AThousandShips** [comment]
That's indeed the PR that introduced it, thank you for finding it!

**Comment by bikemurt** [comment]
Someone else will probably beat me to it, but here is what I found:

https://github.com/godotengine/godot/blob/139f9989e6afcc9376c1c3551cc410ce04981163/editor/gui/scene_tree_editor.cpp#L519

We are adding the "Open in Editor" button every time the scene tree node tooltip is updated (signal gets emitted from the UI for description, in this case)

```
		p_item->add_button(0, get_editor_theme_icon(SNAME("InstanceOptions")), BUTTON_SUBSCENE, false, TTR("Open in Editor"));
```

This is only for inherited scenes or if `can_open_instance` is true - not sure what that would signify yet.

So there should be a way to check if `p_item` already has an "open in editor" button, and only add it if it is missing.

**Comment by AThousandShips** [comment]
Indeed, see the fix above :)
