### ISSUE TITLE
Transform of RayCast2D behaviour

### ISSUE THREAD

**Issue by timlilleoen** [godotengine/godot#96605]
### Tested versions

Godot Engine v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Not sure if bug or i am missing something.

I tried to make a 2d-rigidbody with raycast2d's at predefined height-points of my character using position (transform) and TargetPosition

![{6463F4C7-45B4-4F4C-9C17-E76D11AA8BE8}](https://github.com/user-attachments/assets/10e8f9fa-37f0-4ef9-8f77-485d3733b30b)

Added a simple script to these RayCast2D's to draw a line of the raycasts. 

![{0D768AA2-6A49-44F5-B3A4-82BDAE89B96C}](https://github.com/user-attachments/assets/69bac3c5-a40e-49a6-887b-9ad9c2d23c2f)

The result ended up like this:

![{696EC3C6-57E6-40D5-B1C2-1BB6BB2272FC}](https://github.com/user-attachments/assets/bf310a3f-ceb1-4339-84c7-6dfe0aed3699)
It seems like the position.y is applied to the position.x in this scenario (if my drawline is not wrong).
I also added a print(position) to print the positions of the raycasts, and as you can see in the screenshot, the position.x is 0 on all of them.

Also, if i try to adjust the Position.X to compensate for the offset i have made, it rotates the ray.

![{36B2B919-3004-4C07-B175-B8399CA0804D}](https://github.com/user-attachments/assets/2870ede6-2e01-416c-beaa-453746426714)

The same thing happens if i do not use Roration (rotation = 0) and use target_position.x instead, like this:

![{8AF61FCD-C1D3-499E-A9DF-CD6B4EB0187B}](https://github.com/user-attachments/assets/e3e8e9b2-d6d9-4d24-bb93-4062bf22ab1d)

Again, it seems like the x-value is applied twice. 

Is this a bug, or am i doing something wrong here?

### Steps to reproduce

1. Set up a barebone 2d project
2. Create a RigidBody2D
3. Add RayCast2D
4. Attach Script to RayCast2D
5. Add Signal _on_draw() -> void:
6. Draw line using position to target_position

### Minimal reproduction project (MRP)

[projectFun.zip](https://github.com/user-attachments/files/16888453/projectFun.zip)

**Comment by timlilleoen** [comment]
Here is the transform of the Parent, CharacterBody2D

**Comment by AThousandShips** [comment]
The target position is relative to the ray cast, try `position + target_position`

**Comment by timlilleoen** [comment]
Ahh i see. So its actually the draw-line that is incorrect and the actuall rays work as intended. 

I added the line of code. The Y-axis is still off but the X-values seems correct. Also, the picture verifies the rays atleast works as intended as you can see the ones that are colliding or not. Judging by my eye-sight, its seems correct that the top two rays should not collide in this scenario. 

![{45476563-F083-4301-B3E2-A47C7F4EB080}](https://github.com/user-attachments/assets/77b7378d-eb6a-4caf-add8-8e5831f47b0d)

![{18EB5579-4B07-4FEE-8875-35231F76501C}](https://github.com/user-attachments/assets/c9cff2d6-7e78-4109-9003-723f4dda85ab)

So the bug i created here is not a bug, its just my incompetence. I will try to solve my issue with the Y-axis for the drawing :) Thank you very much!

**Comment by timlilleoen** [comment]
This bug is not a bug!

**Comment by kleonc** [comment]
- `CanvasItem.draw_x` methods work in the given CanvasItem's local coordinate space (by default, you could apply additional transform with `CanvasItem.draw_set_transform{_matrix}`). See [Custom drawing in 2D](https://docs.godotengine.org/en/latest/tutorials/2d/custom_drawing_in_2d.html#coordinates-and-line-width-alignment).
- `RayCast2D.target_positions` is in the RayCast2D's local coordinate space.
- `Node2D.position` is in the Node2D's parent coordinate space. Position of the given CanvasItem in its own local coordinate system is always `Vector2(0, 0)`.

So correct would be:
```gdscript
draw_line(Vector2.ZERO, target_position, Color.RED if is_colliding() else Color.GREEN, 1)
```
