### ISSUE TITLE
methods for converting ints, floats, vectors, etc to / from their byte representations in a PoolByteArray (or RawArray in 2.1)

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#9661]
`PacketPeer` offers a way to send `PoolByteArray` packets with `put_packet`. However this is not currently very useful because it is difficult to work with `PoolByteArray`s.

Part of this is because there are no built-in methods for converting primitive types into their byte format. With `int`, you can at least do it inefficiently with arithmetic, but float is more complicated (though still possible) and even less efficient. It should be possible to insert and get values of these types from `PoolByteArray`s, represented in the array with their byte pattern. Something like this in `PoolByteArray`
s methods:
```
int get_int(int start_idx) # Decode the bytes at start_idx as an int
bool set_int(int start_idx, int value) # Insert the byte pattern of value at start_idx, returning false if it ran off the end of the array
```
and similar for other primitive types.

**Comment by raymoo** [comment]
whoops, wrote `put_var` when I meant `put_packet`

**Comment by raymoo** [comment]
This is fulfilled by `StreamPeerBuffer` in 3.0. I will close this issue and open one for porting it to 2.1.

**Comment by Zylann** [comment]
Well... what about the use case where you don't necessarily want to use StreamPeerBuffer? (plain serialization for example?)
It was asked here: https://godotengine.org/qa/17288/how-to-convert-float-to-byte-array-in-godot-3-0
I still don't know the answer myself in a general case, since Godot only provides domain-specific methods.

**Comment by raymoo** [comment]
I don't think that `StreamPeerBuffer` is specifically network-related, it just happened to be a child of them because they already have a stream-like interface. Really conceptually it would make more sense for `StreamPeer` to just be called `Stream` or something.
