### ISSUE TITLE
PoolByteArray method for copying data between arrays

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#9662]
It should be possible to copy data between `PoolByteArray`s with similar behavior to C `memcpy`, except hopefully with more memory safety (error on failure?).

One thing this would allow is a GDScript implementation of a `PoolByteArray`-builder, by creating an `Array` of `PoolByteArray`s and copying them all into a final `PoolByteArray`.

**Comment by Zylann** [comment]
This is what Read and Write structures are for (take a look at PoolVector and the way it is used), I remember asking for a way to expose them to GDNative to avoid locking at every single index access^^" maybe that can benefit to GDScript too

**Comment by Faless** [comment]
> by creating an Array of PoolByteArrays and copying them all into a final PoolByteArray.

You can already do that easily with [PoolByteArray.append_array](http://docs.godotengine.org/en/latest/classes/class_poolbytearray.html)
`append_array ( PoolByteArray array )`

**Comment by raymoo** [comment]
@Faless This is not efficient though, because resizing of PoolByteArray is linear in time, and must be done for every append, resulting in a total running time quadratic in the number of strings to append.

Anyways, my use case is covered by StreamPeerBuffer as mentioned in #9663, in case anyone cares.

**Comment by raymoo** [comment]
Actually `StreamPeerBuffer` already allows byte array copying, through the `StreamPeer` method `put_partial_data` (after seeking to the spot to copy to).

**Comment by Faless** [comment]
> This is not efficient though

You are right.

> Actually StreamPeerBuffer already

I was just thinking of that.

I think this can be closed then. The only thing left seems to be backporting it to `2.1` in case.

**Comment by akien-mga** [comment]
> I think this can be closed then. The only thing left seems to be backporting it to 2.1 in case.

Which is requested in #10230, so closing.

**Comment by raymoo** [comment]
Yes, thanks, I just forgot to hit close.
