### ISSUE TITLE
PoolByteArrayBuilder or ByteStream or similar

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#9663]
`PacketPeer` offers a way to send `PoolByteArray` packets with `put_packet`. However this is not currently very useful because it is difficult to work with `PoolByteArray`s.

Part of this is that it is hard to build up a `PoolByteArray` incrementally (like you can with C++ output streams).

There should be something similar to C++ IO streams for building / reading `PoolByteArray`s to make it easier to handle custom data formats, as in network protocols.

**Comment by Faless** [comment]
Isn't `StreamPeerBuffer` enough for your needs? [docs here](http://docs.godotengine.org/en/latest/classes/class_streampeerbuffer.html)
```
func _ready():
	var buf = StreamPeerBuffer.new()
	buf.resize(20)
	buf.put_u8(2)
	buf.put_utf8_string("abcdefg")
	buf.put_16(1)
	buf.put_float(.2)
	print(Array(buf.get_data_array()))
```

**Comment by raymoo** [comment]
Yes, that would work perfectly. Thank you for finding it.
