### ISSUE TITLE
Memory Access Violation Error in Godot Engine

### ISSUE THREAD

**Issue by umutbalkan** [godotengine/godot#96630]
### Tested versions

4.1.4

### System information

Godot v4.1.4.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5222) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

Godot was sitting idle at the background for at least 1 hour before the error showed up. Opening the same scene does not reproduce it, and the scene is not corrupted.  I've got a feeling it's because of the filesystem's autoscan/import feature. Does this mean that some malformed file corrupted Godot, through the auto-importing (e.g. tga, fbx etc.), or can it be an addon with editorscript?
![Screenshot 2024-09-05 185558](https://github.com/user-attachments/assets/c2afdaab-ac62-418a-bd9f-841db0136f1f)

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
Without *some* information on what caused this we can't really do anything, so please try to narrow down what might be causing this

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
