### ISSUE TITLE
Editor crashes when re-importing GLTF scene while Animation window is open

### ISSUE THREAD

**Issue by LordMcMutton** [godotengine/godot#96631]
### Tested versions

Occurs in v4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated GeForce GTX 1060 6GB - Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 Threads)

### Issue description

Seems to be a resurgence of https://github.com/godotengine/godot/issues/82962

Re-importing a .GLTF file while its own Animation window is open causes a crash.

Reopening Godot brings up a blank Load Error window:
![image](https://github.com/user-attachments/assets/63073605-c196-4122-9f00-efd6d81abb86)

Oddly enough, I've had this happen before, but it only started corrupting the character model's file today. Now it corrupts it consistently, every time it occurs 

Annoyingly, Godot refuses to make any new godot.log files, but I think I have the errors that are related:

```
USER ERROR: Can't load dependency: res://Visual/Characters/Player/Animations/Locomotion/Idle.
   at: parse_variant (core/io/resource_format_binary.cpp:461)
USER ERROR: Error when trying to parse Variant.
   at: parse_variant (core/io/resource_format_binary.cpp:492)
USER ERROR: Failed loading resource: res://.godot/imported/GeorunnerPlaceholder_Armature_Animate.glb-8a77c65cabb5d93d556367ad1a91200a.scn. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:283)
USER ERROR: Failed loading resource: res://Visual/Characters/Player/GeorunnerPlaceholder_Armature_Animate.glb. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:283)
USER ERROR: res://Engine/Scenes/Test.tscn:804 - Parse Error: [ext_resource] referenced non-existent resource at: res://Visual/Characters/Player/GeorunnerPlaceholder_Armature_Animate.glb
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:159)
USER WARNING: Node 'PlayerBase/VISUAL/PlayerModel/GeorunnerPlaceholder_Armature_Animate' was modified from inside an instance, but it has vanished.
   at: instantiate (scene/resources/packed_scene.cpp:254)
USER WARNING: Parent path './PlayerBase/VISUAL/PlayerModel/GeorunnerPlaceholder_Armature_Animate' for node 'AnimationPlayer' has vanished when instantiating: 'res://Engine/Scenes/Test.tscn'.
   at: instantiate (scene/resources/packed_scene.cpp:179)
USER WARNING: Node './AnimationPlayer' was modified from inside an instance, but it has vanished.
   at: instantiate (scene/resources/packed_scene.cpp:254)
USER ERROR: Parameter "p_node" is null.
   at: get_path_to (scene/main/node.cpp:2168)
```

This feels like the Animation window is freaking out when the source of its contents disappears for a second

It also feels like it may be related to my issues here: https://github.com/godotengine/godot/issues/95870, where reimporting a character model can break links to an AnimationTree's Root Motion Track reference- perhaps there's a larger issue with the way Godot handles dependencies when reimporting stuff?

(Please, I'm dying- this is the third time I'll have to redo all of the Animation Slice settings uuuuuuuugh)

### Steps to reproduce

-Import a character model with animations
-Select its Animation Player, and open the Animation window
-Reimport the character model whose Animation window is open

### Minimal reproduction project (MRP)

[RootMotionMRP.zip](https://github.com/user-attachments/files/16901399/RootMotionMRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/95744
* https://github.com/godotengine/godot/issues/95769

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
