### ISSUE TITLE
No longer able to export macOS builds as .app from Windows

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#96659]
### Tested versions

Godot 4.3

### System information

Windows 10 - Vulkan 1.3.242 - Forward+ - NVIDIA GeForce RTX 2060

### Issue description

In Godot 3 you could export mac builds as .app files, in Godot 4 that option is no longer there.

![mac export g3](https://github.com/user-attachments/assets/631101c2-445a-4b3e-8c2b-3d6e9d5ef919)
![mac export g4](https://github.com/user-attachments/assets/a41bbc31-0604-4018-9695-6d3e4a3529ac)

### Steps to reproduce

make any project and add a mac export option, then do Export Project

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

**Comment by akien-mga** [comment]
> Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.

This is a feature that used to work and there would be no reason for not being able to export `.app` which is the format for applications on macOS, so this is a bug.

That being said, I can't reproduce it on Linux, I can export `.app` fine:

![image](https://github.com/user-attachments/assets/5ee5f5ff-c7ae-4c73-9341-2026217fab50)

Note that `.app` is not a file, but a directory. So to distribute an `.app` you need to zip it to be able to send it. So it might be worth double checking that what you can export only as `.zip` isn't the `.app` folder in a zip.

CC @bruvzg

**Comment by bruvzg** [comment]
It's only disabled on Windows, there's no symlinks for GDExtension frameworks, and it can't set +x flag for the executable, so the result will be unusable without extra manual changes.

I guess we can re-enable it and add a warning instead.
