### ISSUE TITLE
signal.emit() doesn't function properly when conditioned behind InputEvent & the Input gets set as handled

### ISSUE THREAD

**Issue by fandfandfand** [godotengine/godot#96652]
### Tested versions

v4.3.stable.official [77dcf97d8], v4.4.dev1.official [28a72fa43], v4.2.2.stable.official [15073afe3]
(reproducible in all versions mentioned)

### System information

Godot v4.4.dev1 - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+)

### Issue description

Putting a signal, which connects two nodes (in separate scenes) together, inside an input conditional leads to strange behavior.

Simply emitting the signal and doing nothing else works without issue. However, when the input is marked as handled, suddenly the signal never actually emits (Or rather, the node it is connected to never receives it).

Interestingly, if the recipient node is a child of the node sending the signal this issue cant be reproduced.

Frankly, im not sure if im supposed to use signals like this, but it works without setting input as handled so...

### Steps to reproduce

Create 2 Scenes with 1 node inside each.

Create a signal in node 1 & emit this signal if a certain input is pressed. Mark this input as handled via set_input_as_handled() (before or after, does not seem to matter)

Connect the signal to a function inside node 2

if the input is not set as handled the signal will function perfectly fine, if it is, the signal will not work. 

### Minimal reproduction project (MRP)

(2 Scripts in separate Scenes)
```
extends Node

signal test


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("debug"):
		test.emit()
		get_viewport().set_input_as_handled()           
```

```
extends Node

func _ready() -> void:
	GlobalInput.test.connect(test_out)

func test_out():
	print("Success")
```

**Comment by fandfandfand** [comment]
[test.zip](https://github.com/user-attachments/files/16910064/test.zip)
its just autoloading the other scriptbut here u go

**Comment by kleonc** [comment]
> [test.zip](https://github.com/user-attachments/files/16910064/test.zip)
> its just autoloading the other scriptbut here u go

That's your exact issue / misunderstanding. You're adding both scenes as autoloads obtainable via "global variable" (`1.tscn` as `one`, `2.tscn` as `two`), and there's another scene instance which is the "running scene". So:

- If you run `1.tscn` then:
[Remote tree](https://docs.godotengine.org/en/4.3/tutorials/scripting/debug/overview_of_debugging_tools.html#remote-in-scene-dock) (SceneTree at runtime) is:
![MnqseTGh13](https://github.com/user-attachments/assets/20d44efb-f294-4edf-ab90-8e05189e560a)
`two.test_out` method is connected to `one.test` signal, on `"debug"` input action `1._unhandled_input` handles it and emits `1.test` signal. Hence `two.test_out` is never called, as expected.


- If you run `2.tscn` then:
[Remote tree](https://docs.godotengine.org/en/4.3/tutorials/scripting/debug/overview_of_debugging_tools.html#remote-in-scene-dock) (SceneTree at runtime) is:
![71lhX3FlXh](https://github.com/user-attachments/assets/e4c0b1c5-1544-4df1-ac2e-1626206e4bf6)
Both `two.test_out` and `2.test_out` methods are connected to `one.test` signal, on `"debug"` input action `one._unhandled_input` handles it and emits `1.test` signal. Which results in two calls (`two.test_out()`, `2.test_out()`), as expected.

---

It works as expected, no bug in here, that's a user error. Closing.

If you're not sure if you're facing a bug please try asking for help in other [community channels](https://godotengine.org/community/) first (forum etc.), before reporting a bug in here.
