### ISSUE TITLE
AudioStreamPlayer3D doesn't stop processing when out of range

### ISSUE THREAD

**Issue by masterthdev** [godotengine/godot#96670]
### Tested versions

Reproducible in 4.3 stable and 4.2.1. Didn't test in older versions.

### System information

Godot v4.3.stable - Windows 10.0.22000 - Vulkan (Forward+) - dedicated AMD Radeon RX 5600M (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

According to [documentation](https://docs.godotengine.org/en/stable/classes/class_audiostreamplayer3d.html#class-audiostreamplayer3d-property-max-distance), AudioStreamPlayer3D should stop mixing audio and save cpu resources when listener is out of range. In my tests all AudioStreamPlayer3Ds in the whole game continues processing, even after leaving their range and staying outside for a long time.

I profiled MRP to see how processing time changes when leaving range of AudioStreamPlayer3Ds. Processing time of Audio Driver is below 0.05 ms on my machine. Processing time of Audio Server is 6 ms for wav, 150 ms for ogg and 22 ms for mp3 streams. Leaving the range of AudioStreamPlayer3Ds do not have any impact on process times.

When an AudioStreamPlayer3D is playing but listener is out of range, it should only track time instead of wasting cpu resources for decoding and mixing audio.

### Steps to reproduce

- Add lots of AudioStreamPlayer3Ds to a scene, load a stream and set max_distance
- Add a Camera3D next to the players and profile
- Move the camera far away and wait. Processing time won't change.

 MRP 
- There are export variables to control file type, range of players, distance between players and player count. 
- When max_distance   and distance_between_players are equal, only one player is hearable. 
- There are 2 buttons to move the camera while profiling.

### Minimal reproduction project (MRP)

[audiostreamplayer3d-range-mrp.zip](https://github.com/user-attachments/files/16913239/audiostreamplayer3d-range-mrp.zip)

**Comment by Wierdox** [comment]
I can confirm, running the MRP I saw no change in performance with `max_distance` being used. I checked out the source, and found this...
```cpp
float dist = local_pos.length(); // See that it isn't used below...
[...]
if (max_distance > 0) {
	float total_max = max_distance;

	if (area && area->is_using_reverb_bus() && area->get_reverb_uniformity() > 0) {
		total_max = MAX(total_max, listener_area_pos.length());
	}
	if (total_max > max_distance) {
		continue; //can't hear this sound in this listener
	}
}
```
The code never compares the `dist` with the `max_distance`, so it doesn't do the optimization. Luckily, this looks like an easy one line fix, like so: `if (dist > total_max || total_max > max_distance)`. And after compiling, there is a noticeable speedup(in profiler ms) when using `max_distance`. Will open a PR soon.
