### ISSUE TITLE
Pixel-perfect centering issue for odd-sized sprites

### ISSUE THREAD

**Issue by Baba-Yagan** [godotengine/godot#96686]
### Tested versions

- reproducible in v4.3.stable.official.77dcf97d8

[seems to exist since at least 2018]( https://github.com/godotengine/godot/blame/master/scene/2d/sprite_2d.cpp#L95)

### System information

Godot v4.3.stable - Debian GNU/Linux 12 (bookworm) 12 - X11 - GLES3 (Compatibility)

### Issue description

Issue description

When working with low-resolution pixel art sprites that have an odd number of pixels in width or height, centering the sprite can cause sub-pixel positioning, which breaks pixel-perfect rendering.

Currently, when a sprite is centered, Godot uses the following code to calculate the destination offset:

https://github.com/godotengine/godot/blob/master/scene/2d/sprite_2d.cpp#L96
```cpp
	Point2 dest_offset = offset;
	if (centered) {
		dest_offset -= frame_size / 2;
	}
```

For sprites with odd dimensions, this results in half-pixel offsets (e.g., x.5 or y.5). This causes inconsistent rendering, as the sprite may snap to different pixel positions frame-to-frame.

Expected behavior:
When working with pixel art and pixel snap enabled, centered sprites should always align to whole pixels, maintaining pixel-perfect rendering.

Proposed solution:
One potential fix could be to round the picture center to a full pixel when calculating the offset for centered sprites.

Pictures from the MRP
![image](https://github.com/user-attachments/assets/993bde1c-98e4-4abe-9a9c-ff67f060abef)
![image](https://github.com/user-attachments/assets/90e1e0af-2250-48bd-b07d-8771512e0e2c)

### Steps to reproduce

1. Create a new project in Godot
2. Add a sprite with an odd-sized texture (e.g., 25x25 pixels)
3. Enable centering for the sprite

Additional context:
This issue is particularly noticeable in low-resolution pixel art games.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16918877/MRP.zip)

the reproduction of the bug is not project dependent.

**Comment by markdibarry** [comment]
This is already implemented as the [Snap 2D Transforms To Pixel](https://docs.godotengine.org/en/stable/classes/class_projectsettings.html#class-projectsettings-property-rendering-2d-snap-snap-2d-transforms-to-pixel) project setting.
