### ISSUE TITLE
Android Editor Touch Screen Bug

### ISSUE THREAD

**Issue by chronoreaper** [godotengine/godot#96689]
### Tested versions

- Reprodusable in 4.2.2 android stable

### System information

Samsung Galaxy 23FE - Godot v4.2.2.stable - Android - GLES3 (Compatibility) - Adreno (TM) 730 -  (8 Threads)

### Issue description

Taping the screen on the editor in android causes the editor to add tabs. This happens even with auto indentation turned off. Trying to use auto indent will not fix the indentation. It seems to be copying lines or text.

https://github.com/user-attachments/assets/dcfcc623-2abe-4f0b-8fe8-c86016608324

### Steps to reproduce

Create a new project and add a node with a script and start editing. Try clicking the screen.

### Minimal reproduction project (MRP)

Create a new project and add a node with a script and start editing. Try clicking the screen.

**Comment by shahriarlabib000** [comment]
What keyboard is that?

**Comment by chronoreaper** [comment]
The default samsung one

**Comment by shahriarlabib000** [comment]
Maybe try Gboard and see if it shows a similar problem? Couldn't replicate it myself with Gboard.(My device isn't samsung)

**Comment by chronoreaper** [comment]
Seems like that helps

**Comment by chronoreaper** [comment]
Switching to g board resolves the issue.
