### ISSUE TITLE
Scene export duplication error

### ISSUE THREAD

**Issue by DragonMaster14545** [godotengine/godot#96709]
### Tested versions

reproducable in v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.3820) - Intel(R) Core(TM) i9-14900HX (32 Threads)

### Issue description

Hi, so I experienced a similar issue a few times already, but I never was motivated to get a MRP up and running since I don't have any idea why this happens. So, this has to do something with creating a new node on runtime, adding it to the scene tree, propperly setting the owner and then going to the remote tree and saying export as scene on the root node or the node directly below it. This will give the following errors:
```E 0:00:05:0239   get_child: Index p_index = 0 is out of bounds ((int)data.children_cache.size() = 0).
  <C++-Quelle>   scene/main/node.cpp:1688 @ get_child()
```
```E 0:00:05:0239   _duplicate_properties: Child node disappeared while duplicating.
  <C++-Fehler>   Parameter "copy_child" is null.
  <C++-Quelle>   scene/main/node.cpp:2926 @ _duplicate_properties()
```
The export itsself is fine, but the through code added node is gone
This is verry anoying, because I often want to open my scene in the editor for debugging, and having a lot of stuff missing kinda defeats that purpose.
Thanks in advance

### Steps to reproduce

Open the MRP, just click play, then go to the remote scene tree, right click either the root node or the Node3D node on the top, and the click export as scene and click ok

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/16922378/MRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/96246

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by DragonMaster14545** [comment]
@AThousandShips I just tested, my issue is not only with the model, I just swapped out the model loading with a simple Node3D, exact same error
[MRP new.zip](https://github.com/user-attachments/files/16929274/MRP.new.zip)

**Comment by AThousandShips** [comment]
It's the same issue with the same origin, please test the PR:
* https://github.com/godotengine/godot/pull/89442

And add any new information to the other report
