### ISSUE TITLE
RichTextLable: Indent table error

### ISSUE THREAD

**Issue by Calador-t** [godotengine/godot#96720]
### Tested versions

Bug in: v4.3.stable.offical [77dcf97d8] & v4.2.2.stable.mono.offical [15073afe3]

### System information

Ubuntu 24.04.1

### Issue description

When using Tables inside an indented block they indent to much.

### Steps to reproduce

Add RichTextLable with BBCode = true. 
Text:
`[table=1][cell]a[/cell][cell]3[/cell][/table]:
[indent][table=1][cell]a[/cell][cell]3[/cell][/table]:[/indent]`

![image](https://github.com/user-attachments/assets/e7b90ba1-769e-47b6-8bf3-8cd8daab438c)

The unindented table is before the double dot, but the indented is not.

### Minimal reproduction project (MRP)

[tableIndentBug.zip](https://github.com/user-attachments/files/16923152/tableIndentBug.zip)

**Comment by dalexeev** [comment]
* May be related: #67026.
