### ISSUE TITLE
EditorUndoRedo returned UndoRedo doesn't commit the action

### ISSUE THREAD

**Issue by AnidemDex** [godotengine/godot#96738]
### Tested versions

v4.3.stable.official [77dcf97d8]

Works in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Wed Aug  7 16:19:28 UTC 2024 - X11 - GLES3 (Compatibility) - Mesa Intel(R) UHD Graphics 600 (GLK 2) - Intel(R) Celeron(R) N4020 CPU @ 1.10GHz (2 Threads)

### Issue description

In working in a custom editor for custom resources in runtime and in editor. I wanted to hook edit operations to godot global history when is in editor, so I used `editor_undoredo.get_history_undo_redo(editor_undoredo.get_object_history_id(...))`. It always used `0 (GLOBAL)` or higher numbers.

Before 4.3, the plugin editing operations worked without issues and operations were added to global history. Now it uses id `1` and doesn't apply the operation.

### Steps to reproduce

Try to use UndoRedo operations directly, not EditorUndoRedo, for custom objects.

My specific case was https://github.com/AnidemDex/Blockflow/pull/172 , but I managed to replicate it with a single plugin script applying a single operation to a dummy resource created in runtime. In my specific case I use resources that are already saved in file system, so `EditorUndoRedo` should _at least_ return the global undoredo and commit the action there

### Minimal reproduction project (MRP)

Create a new plugin and paste this code. Enable it after that, you should see a new dock with a `Do` button. Click the button, color should change.

- It does change in godot 4.2
- It doesn't change in godot 4.3 (unless you modify the script, forcing the global history. Even then, operation is not added to global history)

I don't care about the action being added to history (because this mrp will probably not add something to that history), I'm worried that it doesn't even commit the action.
```swift
@tool
extends EditorPlugin

class FakeResource extends Resource:
	var color:Color:
		set(value):
			color = value
			emit_changed()

var fake_dock:Control
var fake_resource:FakeResource

var color_rect: ColorRect

func _enter_tree() -> void:
	add_control_to_dock(EditorPlugin.DOCK_SLOT_RIGHT_BL, fake_dock)


func _exit_tree() -> void:
	remove_control_from_docks(fake_dock)

func button_do() -> void:
	var editor_undoredo := get_undo_redo()
	var undo_redo = editor_undoredo.get_history_undo_redo(editor_undoredo.get_object_history_id(fake_resource))
	#undo_redo = editor_undoredo.get_history_undo_redo(0) #<- Force global history
	#print("using ID:%s UndoRedo"%editor_undoredo.get_object_history_id(fake_resource))
	
	undo_redo.create_action("Change Color")
	undo_redo.add_do_method(change_color.bind(Color(randf(), randf(), randf())))
	undo_redo.add_undo_method(change_color.bind(fake_resource.color))
	undo_redo.commit_action()

func change_color(with)->void:
	fake_resource.color = with

func _fake_resource_changed() -> void:
	color_rect.color = fake_resource.color
	

func _init() -> void:
	var hb = HBoxContainer.new()
	
	color_rect = ColorRect.new()

	var do_button = Button.new()
	do_button.text = "Do"
	do_button.pressed.connect(button_do)
	
	hb.add_child(color_rect)
	hb.add_child(do_button)
	hb.propagate_call("set", ["size_flags_horizontal",Control.SIZE_EXPAND_FILL])
	hb.propagate_call("set", ["size_flags_vertical",Control.SIZE_EXPAND_FILL])
	hb.propagate_call("set", ["custom_minimum_size", Vector2(16,16)])
	
	tree_exiting.connect(hb.queue_free)
	
	fake_resource = FakeResource.new()
	fake_resource.changed.connect(_fake_resource_changed)
	fake_dock = hb
```

**Comment by Crystalwarrior** [comment]
Can confirm this issue is present on Windows 10 as well.

**Comment by KoBeWi** [comment]
Can't reproduce. The color changes when using the provided script:

https://github.com/user-attachments/assets/9abae497-3b96-4811-87ed-dc5395604ca5

Any reason why you are using UndoRedo instead of EditorUndoRedoManager? When integrating with editor undo history, the latter should be always used.

**Comment by AnidemDex** [comment]
> Any reason why you are using UndoRedo instead of EditorUndoRedoManager?

Editor* classes doesn't exist in runtime, my use case is an editor that work both in editor and in game, so it uses UndoRedo.


I'll experiment a little to see if I can make a more precise project with the bug, if I can't replicate it I'll close the issue, maybe is something that worked in 4.2 due a bug and now in 4.3 was fixed

**Comment by KoBeWi** [comment]
Well you can't make it work the same in editor and in game, unless you handle UndoRedo yourself. Hooking up into editor's history is not possible without EditorUndoRedoManager.

The script will break only if you refer to the class. You can use the object without specifying its type. EditorUndoRedoManager and UndoRedo have almost the same API, so you can even use them interchangeably.

**Comment by AnidemDex** [comment]
For some reason I can't replicate it now even using this script :melting_face: 

Gonna close it for now, thank you for taking a look at the issue, kobewi
