### ISSUE TITLE
Can't change screen when window is maximized

### ISSUE THREAD

**Issue by dombeek** [godotengine/godot#96733]
### Tested versions

**Reproducible in**  
- v4.3.stable.steam [77dcf97d8]
- v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 Threads)

### Issue description

When windows is maximized, switching to a different screen using DisplayServer.window_set_current_screen() does not work.

```
DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MAXIMIZED)
DisplayServer.window_set_current_screen(1)
```

**Expected Behavior:** 
The window should maximize and move to the second screen.

**Observed Behavior:** 
The window maximizes and stays on first screen.

### Workaround: 

1. Switch to windowed (non-maximized) mode.
2. Move window to second screen by updating its position.
3. Switch to maximized mode.

```
DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
DisplayServer.window_set_position(DisplayServer.screen_get_position(1))
DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MAXIMIZED)
```

### Steps to reproduce

Run attached project on multi-monitor setup.

### Minimal reproduction project (MRP)

[window_mode_maximized.zip](https://github.com/user-attachments/files/16923648/window_mode_maximized.zip)

**Comment by tetrapod00** [comment]
Confirmed on Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads).

I also tried adding this snippet to the MRP, and confirmed that it will switch screens every frame if the game is windowed and not switch if the game is maximized.
```gdscript
func _process(delta: float) -> void:
	DisplayServer.window_set_current_screen((DisplayServer.window_get_current_screen() + 1) % DisplayServer.get_screen_count())
```

**Comment by angelrubio** [comment]
My workaround is a little different:
`
func change_screen(screen_number: int) -> void:
	if DisplayServer.window_get_mode() == DisplayServer.WINDOW_MODE_MAXIMIZED:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
		DisplayServer.window_set_current_screen(screen_number)
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_MAXIMIZED)
	else:
		DisplayServer.window_set_current_screen(screen_number)
`
