### ISSUE TITLE
ERROR: Failed to initialize driver for device. Intel HD 2500

### ISSUE THREAD

**Issue by ahqsoftwares** [godotengine/godot#96755]
### Tested versions

Godot_v4.3-stable_win64.exe

### System information

Device name	AHQ-PC Processor	Intel(R) Core(TM) i3-3210 CPU @ 3.20GHz   3.20 GHz Installed RAM	12.0 GB (11.9 GB usable) Device ID	23BFFD3F-DA76-487C-A217-0D7F0AA571DD Product ID	00331-10000-00001-AA787 System type	64-bit operating system, x64-based processor Pen and touch	No pen or touch input is available for this display

### Issue description

```
PowerShell 7.5.0-preview.4
PS I:\godot> I:\godot\Godot_v4.3-stable_win64.exe
PS I:\godot> Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
WARNING: Your video card drivers seem not to support the required OpenGL 3.3 version, switching to ANGLE.
     at: DisplayServerWindows (platform/windows/display_server_windows.cpp:6055)
OpenGL API OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 468fcbe033fa) - Compatibility - Using Device: Google Inc. (Intel) - A)

Editing project: E:/games/hello
Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
ERROR: Required extension VK_KHR_surface not found.
   at: (drivers/vulkan/rendering_context_driver_vulkan.cpp:153)
ERROR: Condition "err != OK" is true. Returning: err
   at: initialize (drivers/vulkan/rendering_context_driver_vulkan.cpp:594)
WARNING: Your video card drivers seem not to support Vulkan, switching to Direct3D 12.
     at: DisplayServerWindows (platform/windows/display_server_windows.cpp:5985)
ERROR: D3D12CreateDevice failed with error 0x887a0004.
   at: (drivers/d3d12/rendering_device_driver_d3d12.cpp:6302)
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: initialize (drivers/d3d12/rendering_device_driver_d3d12.cpp:6670)
ERROR: Failed to initialize driver for device.
   at: (servers/rendering/rendering_device.cpp:5372)

================================================================
CrashHandlerException: Program crashed with signal 11
Engine version: Godot Engine v4.3.stable.official (77dcf97d82cbfe4e4615475fa52ca03da645dbd8)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] error(-1): no debug info in PE/COFF executable
[2] error(-1): no debug info in PE/COFF executable
[3] error(-1): no debug info in PE/COFF executable
[4] error(-1): no debug info in PE/COFF executable
[5] error(-1): no debug info in PE/COFF executable
[6] error(-1): no debug info in PE/COFF executable
[7] error(-1): no debug info in PE/COFF executable
[8] error(-1): no debug info in PE/COFF executable
[9] error(-1): no debug info in PE/COFF executable
[10] error(-1): no debug info in PE/COFF executable
[11] error(-1): no debug info in PE/COFF executable
[12] error(-1): no debug info in PE/COFF executable
[13] error(-1): no debug info in PE/COFF executable
[14] error(-1): no debug info in PE/COFF executable
[15] error(-1): no debug info in PE/COFF executable
[16] error(-1): no debug info in PE/COFF executable
[17] error(-1): no debug info in PE/COFF executable
[18] error(-1): no debug info in PE/COFF executable
[19] error(-1): no debug info in PE/COFF executable
[20] error(-1): no debug info in PE/COFF executable
[21] error(-1): no debug info in PE/COFF executable
[22] error(-1): no debug info in PE/COFF executable
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

na

### Minimal reproduction project (MRP)

na

**Comment by clayjohn** [comment]
It looks like the project manager worked successfully for you, but crashes when running the project, is that right?

**Comment by ahqsoftwares** [comment]
yes

**Comment by bruvzg** [comment]
> WARNING: Your video card drivers seem not to support Vulkan, switching to Direct3D 12.

You are trying to open a project with "Forward+"/"Mobile" renderer which require either Vulkan or DX12, and neither is supported by your GPU. Try switch to "Compatibility" renderer.

> Your video card drivers seem not to support the required OpenGL 3.3 version, switching to ANGLE.
> Intel HD 2500 supports OpenGL 4 > OpenGL 3.3

OpenGL driver quality on ancient Intel GPU is awful and mostly unusable, so Godot use ANGLE over DX11 instead of OpenGL.

**Comment by ahqsoftwares** [comment]
> > WARNING: Your video card drivers seem not to support Vulkan, switching to Direct3D 12.
> 
> You are trying to open a project with "Forward+"/"Mobile" renderer which require either Vulkan or DX12, and neither is supported by your GPU. Try switch to "Compatibility" renderer.
> 
> > Your video card drivers seem not to support the required OpenGL 3.3 version, switching to ANGLE.
> > Intel HD 2500 supports OpenGL 4 > OpenGL 3.3
> 
> OpenGL driver quality on ancient Intel GPU is awful and mostly unusable, so Godot use ANGLE over DX11 instead of OpenGL.

Yep compatibility indeed worked
but I think HD 2500 has vulkan support? or am I missing something?

**Comment by akien-mga** [comment]
I don't think Intel HD 2500 supports Vulkan on Windows (maaaybe on Linux with Mesa, but with very limited support that probably wouldn't work well enough for Godot).

But the logs look like it's falling back to Direct3D 12, and then also failing at that:
```
WARNING: Your video card drivers seem not to support Vulkan, switching to Direct3D 12.
     at: DisplayServerWindows (platform/windows/display_server_windows.cpp:5985)
ERROR: D3D12CreateDevice failed with error 0x887a0004.
   at: (drivers/d3d12/rendering_device_driver_d3d12.cpp:6302)
```

I'm not sure Intel HD 2500 supports D3D12.

**Comment by ahqsoftwares** [comment]
Thanks a lot of clarifying though. I guess I can just use the compatibility code as I'll be only making 2d games. For 3d games, I think I can utilize my 11th gen laptop?
