### ISSUE TITLE
Animation tree no longer lets property settings "fall through"

### ISSUE THREAD

**Issue by ErwinBr** [godotengine/godot#96754]
### Tested versions

- Reproducible in 4.3 stable
- Not reproducible in 4.2.2 stable

### System information

Windows 11, Godot 4.3 stable

### Issue description

I'm working with Sprite Sheets where either the left or right direction is a mirror of the other side. I have an Animation Tree set up with an AnimationNodeStateMachine.

In the AnimationPlayer I have a dedicated animation for an Idle state, in which the property "flip h" is set to TRUE on the WEST animation, and FALSE on the EAST animation.

All the other connecting animations on either WEST or EAST side, are just copies from the opposing side that actually have sprites.

Because the animation is traveling through Idle, where the "flip h" is set, the duplicates remained playing in that direction.

This is a huge time saver and very efficient because you don't need to have dedicated animations for each direction, save for the Idle animation.

This used to work in all prior versions of Godot, except no longer in 4.3.

![tree_bug](https://github.com/user-attachments/assets/568738b6-37a7-49d5-8aed-b0885bed2162)

### Steps to reproduce

1. Create AnimationPlayer and a Sprite(3D) with a texture of a spriteheet with an idle and walking animation.
2. Create animations Idle_EAST and Idle_WEST. Create keyframe of the frame number, and set "flip" on for the WEST animation, and off for the EAST animation. (Assuming the spritesheet has an EAST facing sprite)
3. Create animation Walk_EAST, set only the frame properties, don't touch "flip" property.
4. Create AnimationTree with State Machine
5. Add the animations Idle_EAST, Idle_WEST and Walk_EAST
6. Add again the animation Walk_EAST. This duplicate can then be renamed Walk_WEST.
7. Connect the animations so we can travel from Idle_EAST to Idle_WEST and back.
8. Connect Walk_EAST with Idle_EAST and Walk_WEST with Idle_WEST and back. Ensure that when moving from Idle to Walk, that this connection's switch mode is set to "At End", so that it does not skip Idle and therefore not set the Flip property.
9. Test the animation tree by clicking on Walk EAST and then clicking Walk WEST. Observe that even though we travel through Idle_WEST, where we flip the sprite, the flipping is ignored when we're playing Walk_WEST. Even though that animation does not override the flip setting. For a brief moment, it will flip the sprite, if the Idle animation is long enough to observe it, but then it gets reset.

### Minimal reproduction project (MRP)

[animation_tree_repro.zip](https://github.com/user-attachments/files/16931244/animation_tree_repro.zip)

**Comment by matheusmdx** [comment]
I think this is one of the things that changed in the animation tree/player revamp. Changing this option like the photo bottom solves the issue:

![image](https://github.com/user-attachments/assets/1d75df92-c0cf-4f4d-b92d-7a75c097ccc9)

See more in: https://godotengine.org/article/migrating-animations-from-godot-4-0-to-4-3/

**Comment by ErwinBr** [comment]
Thank you! Turning off the Deterministic option also worked. Since I don't need it, I opted for that. I wish that changes would be implemented "not breaking" by default, because it's hard to debug this and now I have to go through a couple of Animation Tree objects to adjust. The latter is no biggie, it's more a matter of principle.

Anyway, I will close the issue. THANKS! :)
