### ISSUE TITLE
Setting warnings on startup

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#96769]
### Tested versions

4.4 27552a2
Does not appear in 4.3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Every time I open project I see these warnings:
```
WARNING: Property not found: xr/openxr/enabled.editor
WARNING: EditorSettings::_get - Property not found: asset_library/available_urls
WARNING: EditorSettings::_get - Property not found: _script_setup_templates_dictionary
```
The first one is weird, because the condition checking for setting looks wrong and the setting itself is never defined.
The others seem to appear when settings are being loaded, which makes no sense.

### Steps to reproduce

1. Open Godot (either project manager or editor)

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
Bisecting points to #78656 as the culprit, @Repiteo

![image](https://github.com/user-attachments/assets/ac2a1315-44e5-4e86-b406-44574f1f96a6)


```
Godot Engine v4.4.dev.custom_build.9853a6914 (2024-09-04 15:27:26 UTC) - https://godotengine.org
OpenGL API 3.3.0 Core Profile Context 24.7.1.240618 - Compatibility - Using Device: ATI Technologies Inc. - AMD Radeon RX 580 2048SP

WARNING: EditorSettings::_get - Property not found: asset_library/available_urls
     at: EditorSettings::_get (editor\editor_settings.cpp:224)
WARNING: EditorSettings::_get - Property not found: _script_setup_templates_dictionary
     at: EditorSettings::_get (editor\editor_settings.cpp:224)
WARNING: EditorSettings::_get - Property not found: metadata/script_setup_templates_dictionary
     at: EditorSettings::_get (editor\editor_settings.cpp:224)
```

**Comment by bruvzg** [comment]
Seems to be triggered during loading of `editor_settings-4.4.tres` (removing the file only temporary fixes it until it is recreated).

**Comment by akien-mga** [comment]
> The first one is weird, because the condition checking for setting looks wrong and the setting itself is never defined.

It is defined here:
```
modules/openxr/openxr_api.cpp
276:                    return GLOBAL_GET("xr/openxr/enabled.editor");
```

**Comment by bruvzg** [comment]
The first one seems to be unregistered at all, for the rest, loader is trying to match dictionary (and array, but I guess none of the editor settings are arrays) type with default value, but since editor settings have settings registered dynamically, there's no default at the load time.
