### ISSUE TITLE
Android export failing on Windows

### ISSUE THREAD

**Issue by devloglogan** [godotengine/godot#96762]
### Tested versions

Experienced this bug in:
- Master [d0dc3896a]
- [78883a52c64adbab56aaa363138a9f661a67d48e]

Bug does not take place in:
- 4.3-stable

### System information

Godot v4.4.dev (d0dc3896a) - Windows 10.0.22631 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 4070 (NVIDIA; 31.0.15.3161) - Intel(R) Core(TM) i7-14700K (28 Threads)

### Issue description

When attempting to export an XR project to my Quest 3, the export fails and I get the following error:

```
C:\Users\langl\workspace\godot\editor\export\editor_export_platform.h:227 - Export: Building of Android project failed, check output for the error:
  
The system cannot find the path specified.

Cannot remove non-existent file or directory: C:/Users/langl/AppData/Local/Godot/tmpexport.1725898406.apk
```

### Steps to reproduce

Just export the project to an android device, in my case, from Windows to Quest 3.

### Minimal reproduction project (MRP)

I'm testing using the demo project from the [OpenXR Vendors Repo](https://github.com/GodotVR/godot_openxr_vendors).

**Comment by AThousandShips** [comment]
Please list the version this *doesn't* occur in as well for context (as you marked it as a regression I assume you know it used to work in this specific case)

**Comment by devloglogan** [comment]
@AThousandShips apologies, added that. In the process of finding the commit that introduced the regression.

**Comment by dsnopek** [comment]
I can reproduce this issue on Windows on https://github.com/godotengine/godot/commit/d0dc3896ad6fe039e4ad0607d901c81197cb3a3b (`master` from yesterday), however, it works fine for me on Linux.

**Comment by devloglogan** [comment]
https://github.com/godotengine/godot/pull/91902/ seems to be the PR that introduced this issue
cc: @bruvzg

**Comment by bruvzg** [comment]
Seems like Windows does not like long paths for a `.bat` scripts.

**Comment by devloglogan** [comment]
Can confirm this does fix the issue for me! :)
