### ISSUE TITLE
Top-level 3d nodes unable to be selected if their children have "editable children" toggled on

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#96764]
### Tested versions

- Bisected the issue to bf9fdc5b (#84831)
- Issue not present in 4.3.stable
- Issue present in 4.4.dev1
- Issue still present on 4.4.dev (master)

### System information

Godot v4.4.dev (27552a2f2) - macOS 14.6.1 - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 Threads)

### Issue description

When selecting a 3D node, it selects the MeshInstance3D underlying instead of top the parent node, even when "editable children" is not toggled on.

### Steps to reproduce

1. Import a 3D model
2. Create an "editable" scene
3. Create a "non-editable" scene
4. In the "editable" scene, drag the 3d model inside it and toggle on "editable children"
5. In the "non-editable" scene, drag the 3d model inside it and do nothing else
6. Load both of these scenes in a main scene
7. Discover that you cannot select directly the "editable" scene node, as it selects the underlying `MeshInstance3D`. But there's no such issue when clicking on the "non-editable" scene node.

### Minimal reproduction project (MRP)

~~[node3d-select.zip](https://github.com/user-attachments/files/16934368/node3d-select.zip)~~
[node3d-select.zip](https://github.com/user-attachments/files/16934633/node3d-select.zip)

**Comment by AThousandShips** [comment]
This sounds like something my PR fixes:
* https://github.com/godotengine/godot/pull/87615

At least testing with it it seems to solve it, if the bug is that the node isn't selected in the scene tree, might be accidental though

**Comment by adamscott** [comment]
@AThousandShips I have a PR that reverts in some way https://github.com/godotengine/godot/pull/84831. I don't know why the use of `_select_ray()` was ditched. It simply needed a check if the node was locked or not.

**Comment by AThousandShips** [comment]
That's a good starting point indeed
