### ISSUE TITLE
[3.0] Shaders: DISCARD can't be set from float / why is DISCARD a variable?

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9677]
In Godot 3.0 master, there is a DISCARD boolean variable available in fragment shaders. However, it can only be set to `true` or `false` explicitely, float conversion doesn't work, and using explicit cast `bool(step(x, y))` breaks the whole rendering with `GL_INVALID_OPERATION`.

Having DISCARD being a variable looks like the Cg way of doing things, where no `if` is needed (as far as I know, I take this from Unity shader examples).
However, in GLSL `discard` is a statement, and then requires an `if`.

Then, why is DISCARD a variable? Should it be converted to a `discard` statement?

Edit: actually, even using DISCARD correctly breaks rendering on my PC:
![image](https://user-images.githubusercontent.com/1311555/28284579-c4c4535c-6b31-11e7-99c8-19feb4119d38.png)

Here is the top of the mesege:
```
ERROR: _display_error_with_code: SceneShaderGLES3: Fragment Program Compilation Failed:
0(1050) : error C1008: undefined variable "_discard"

   At: drivers\gles3\shader_gles3.cpp:167
ERROR: ShaderGLES3::get_current_version: SceneShaderGLES3: Fragment Program Compilation Failed:
0(1050) : error C1008: undefined variable "_discard"

   At: drivers\gles3\shader_gles3.cpp:459
ERROR: ShaderGLES3::get_current_version: Method/Function Failed, returning: 0
   At: drivers\gles3\shader_gles3.cpp:467
ERROR: ShaderGLES3::bind: Condition ' !version ' is true. returned: false
   At: drivers\gles3\shader_gles3.cpp:122
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: d:\projets\info\godot\engine\godot_fork\drivers\gles3\shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: d:\projets\info\godot\engine\godot_fork\drivers\gles3\shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: d:\projets\info\godot\engine\godot_fork\drivers\gles3\shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: d:\projets\info\godot\engine\godot_fork\drivers\gles3\shader_gles3.h:376
ERROR: ShaderGLES3::_get_uniform: Condition ' !version ' is true. returned: -1
   At: d:\projets\info\godot\engine\godot_fork\drivers\gles3\shader_gles3.h:376
mesege
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. No active program.
   At: drivers\gles3\rasterizer_gles3.cpp:123
mesege
```

**Comment by HumanSheeple** [comment]
![deepinscreenshot_select-area_20170717172600](https://user-images.githubusercontent.com/28750624/28285980-370b4918-6b26-11e7-9b39-75e319ca1400.png)
![deepinscreenshot_select-area_20170717173133](https://user-images.githubusercontent.com/28750624/28285984-394ed8ac-6b26-11e7-8ff3-8c231812e13f.png)
Yeah I also want to confirm this issue because I can't make my alpha pixels disappear properly, also if I use ALPHA=0.0 there's another bug with faces appearing in front of others when they shouldn't.
