### ISSUE TITLE
SSAO darkens viewport borders in the editor and running projects

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#9678]
**Operating system or device - Godot version:** Windows 10 (on NVIDIA)

**Issue description:** The SSAO effect will darken the viewport borders, both in the editor and in a running project. See the screenshot below (which is the corner of a running project's window):

![godot_2017-07-17_22-36-59](https://user-images.githubusercontent.com/180032/28288742-7a1b6a8e-6b40-11e7-8d73-544e090a2298.png)

**Steps to reproduce:** Enable SSAO.

**Comment by Zylann** [comment]
I also raised this issue in https://github.com/godotengine/godot/issues/8120

**Comment by gamergamesz** [comment]
plus it would be great to implement bar for blur value

**Comment by reduz** [comment]
Maybe you guys are smarter than I am..  I cant find why this happens, as the position is properly clamped:
https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/ssao.glsl#L114

**Comment by reduz** [comment]
oh... the bug was in the filter, not the SSAO
