### ISSUE TITLE
AnimationTree only execute method track once

### ISSUE THREAD

**Issue by Levrault** [godotengine/godot#96799]
### Tested versions

- Reproductible in Godot Engine v4.3.stable

### System information

Godot v4.3.stable - Nobara Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i7-1270P (16 Threads)

### Issue description

Using AnimationTree with a blend2 or add2 withing a tween will cause the method track inside the animationplayer to only be called once.

```
extends Node3D

var is_reloading: bool = false

@onready var animation_tree: AnimationTree = $AnimationTree


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("reload") and not is_reloading:
		is_reloading = true
		var tween: Tween = create_tween()
		tween.tween_property(animation_tree, "parameters/Reload/add_amount", 1.0, .5)
		tween.tween_property(animation_tree, "parameters/Reload/add_amount", 0.0, .5)
		tween.tween_callback(
			func() -> void:
				is_reloading = false
		)

	if event.is_action_pressed("shoot"):
		animation_tree.set("parameters/Shoot/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)


func test() -> void:
	print_debug("this should be called")
```

https://github.com/user-attachments/assets/531f2952-6c8d-417c-9cb3-56ca33098b17

![image](https://github.com/user-attachments/assets/ca005020-ce8d-4252-b8ed-789487ac4863)
![image](https://github.com/user-attachments/assets/c9649f51-6cea-4380-a621-373ce6d13c38)

### Steps to reproduce

- Create a new Project
- Add a script with a single method
- Add an AnimationPlayer node
- Create an animation with a method track
- Call the previously created method
- Add an AnimationTree
- Create a new AnimationNodeBlendTree
- Create an animation (reset) 
- Add an Add2 node
- Make the add2 node play the animation with the method track
- Change the add_amount in the code between value 0 and 1
- Method will only be called once

### Minimal reproduction project (MRP)

[animation_tree_method_track_issue.tar.gz](https://github.com/user-attachments/files/16947168/animation_tree_method_track_issue.tar.gz)

**Comment by AThousandShips** [comment]
It works fine if you set the animation to repeat, if you don't it won't repeat, but that's expected as it isn't set to repeat. With it set to repeat it prints correctly

**Comment by Levrault** [comment]
My real world case scenario is; 
- the player shoot with a revolver
- The player reload
- I play the reload animations on the revolver (open the cylinder with add_amount)
- The reload animation call my reload method

I would inspect a way the reset the add2 to make it trigger my reload method everytime. What would you recommand instead?

**Comment by AThousandShips** [comment]
The animation is only played once so it won't play again after it has finished, the reason it *looks* like it reloads is because it blends between the shoot state and the reload state

**Comment by Levrault** [comment]
thanks for the help, I'm closing the issue
