### ISSUE TITLE
String.trim() String.left_trim() String.right_trim()

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#968]
Hi,

This is a minor request. I missed those methods into the String API : trim(), left_trim(), right_trim() to remove white space around the string.

**Comment by mattiascibien** [comment]
As whitespace do you want to count even ```\n``` and ```\r```?

**Comment by bojidar-bg** [comment]
Note that there is a `strip_spaces` or similar method that is basically trim on both sides.

**Comment by mattiascibien** [comment]
@bojidar-bg this is good. thank you. Sould the new ones be named like ```strip_spaces_left``` and ```strip_spaces_right``` for coherence?

**Comment by akien-mga** [comment]
I'd prefer have us implement the same API as Python for this, and maybe deprecate ``strip_spaces`` for the Python-like equivalent if need be. The fact that someone asks for ``trim*()`` methods when ``strip_spaces`` already existed shows that our API is confusing (at least to Python users, but IMO the closer we stick to Python, the better).

**Comment by SuperUserNameMan** [comment]
@mattiascibien : this request is from two years ago, so I don't remember why I needed these methods :-/

@bojidar-bg : yes, you're right, there is a strip_edges() method.

**Comment by mattiascibien** [comment]
So i guess that strip_edges should be called trim? maybe making it like this?
```
trim()
{
  trim_left(trim_right())
}
```

so basically splitting strip_edged in two and them rebuild the string?

**Comment by akien-mga** [comment]
I think the Python-like version would be ``split()``: https://docs.python.org/3/library/stdtypes.html#str.split
Also ``lsplit()`` and ``rsplit()`` for left and right.

**Comment by mattiascibien** [comment]
@akien-mga I think that also some optimization can be done in ```strip_edges``` as ```length()``` is called 3 times in a row while we still have the ```len``` variable is already populated with length and therefore does not change [link](https://github.com/godotengine/godot/blob/master/core/ustring.cpp#L2872)

**Comment by mattiascibien** [comment]
Some progress on [my fork](https://github.com/mattiascibien/godot/tree/new-string-methods)

**Comment by bojidar-bg** [comment]
@mattiascibien ~ BTW, it would be nice if they accept a string of characters to skip :smile:

**Comment by mattiascibien** [comment]
@bojidar-bg can you give me an example?

**Comment by bojidar-bg** [comment]
@mattiascibien 
````gd
func example():
    var x = "XXXXXstringYYY  "
    assert(x.strip_edges("XY ") == "string")
````

**Comment by mattiascibien** [comment]
@bojidar-bg Why not doing ```replace(replace(str, 'X', ''), 'Y'Y, '')``` ? Anyway I'd rather hear from the devs before going through this @godotengine .

**Comment by akien-mga** [comment]
Well as I said, the best would be IMO to have the same API as Python: https://docs.python.org/3/library/stdtypes.html#str.strip
Which supports specifying a list of characters to strip:
```
>>> '   spacious   '.strip()
'spacious'
>>> 'www.example.com'.strip('cmowz.')
'example'
```

**Comment by mattiascibien** [comment]
@akien-mga in order to maintain compatibility should I create new functions and wrap or is it enough to  rename those?

**Comment by akien-mga** [comment]
I think the best would be to add new functions, make ``strip_edges`` use ``strip`` internally, and have it print a warning about the ``strip_edges`` function getting deprecated and being removed in future versions. We've discussed how to add such warnings efficiently in #4397, feel free to add your input there :)

**Comment by reduz** [comment]
we could make it like strip_edges(left=true,right=true) by default, what do you think? should remain compatible..

**Comment by mattiascibien** [comment]
@reduz I really like this idea. Seems also very easy to implement (no idea on how to make default parameters in gdscript, I am still scratching the surface)

**Comment by akien-mga** [comment]
Yeah we could keep ``strip_edges`` if you prefer. Personally I'd tend to try to make the API closer to Python to reduce needless confusion, hence the proposal to rename the function and keep the old one with a message that it's deprecated. But I don't mind keeping the existing name either. At least people familiar with Python's .strip() would find it via autocompletion.

We should support the String parameter of characters to strip like Python though, so if we want to make an all in one it should be ``strip_edges(String chars, bool left=true, bool right=true)``.

**Comment by mattiascibien** [comment]
I am open to discussion... Meanwhile I am adding the left and right parameters.

**Comment by bojidar-bg** [comment]
@akien-mga ~ What about using flags and constants? :smile:

**Comment by akien-mga** [comment]
Yeah I thought about flags too. But we'd have to expose them, and document them :p

**Comment by mattiascibien** [comment]
@akien-mga @reduz https://github.com/mattiascibien/godot/commit/7fe1c071012cdaf605cd6714b0767105d6ee122e
