### ISSUE TITLE
dotNet version creates many unnecessary log files on Project run

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#96803]
### Tested versions

Godot_v4.3-stable_mono_win64

### System information

Win10, Nvidia,   dotnet-sdk-6.0.400-win-x64

### Issue description

Godot creates a new log file in temp, everytime project is run.
Turning off logging (in Project &  Editor settings) does not stop them being created.

The logs are created in  _AppData\Local\Temp_,     see screenshot:
![files_workloadscreenshot](https://github.com/user-attachments/assets/34a13455-5012-4a96-8cb8-14eb45a2abb3)

### Steps to reproduce

Create a new  Godot .net project. 
Add Node, attach a .cs script file, save.

Hit F5 to run.
Look at temp dir  AppData\Local\Temp

### Minimal reproduction project (MRP)

None req

**Comment by raulsntos** [comment]
That's not one of Godot logs. It's probably the .NET SDK, there's already a reported issue upstream that sounds like the same thing:
- https://github.com/dotnet/sdk/issues/36441
