### ISSUE TITLE
AssetLlib should be able to filter plugins by compatibility with Godot version

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9680]
**Issue description:**
Since 3.0 is coming, we should have ability to filter plugins compatibility by engine version in AssetLib. We probably should display some kind of warning when user will decide to install plugin in non-matching version of the editor.
Also there should be a way for plugin creators to declare in which versions of the engine given plugin will work without problems.

**Comment by vnen** [comment]
It would be great if it were possible to upload different versions of the plugin for different versions of Godot.

**Comment by eon-s** [comment]
Duplicate/related to this badly spelled issue #7147

**Comment by neikeq** [comment]
Maybe related. Now that we also have more scripting languages, it would be great to also filter plugins automatically by available languages.

**Comment by kubecz3k** [comment]
closing as duplicate of https://github.com/godotengine/godot/issues/7147
