### ISSUE TITLE
[4.4.dev2, Windows] Changes to exports are only shown after relaunching the editor

### ISSUE THREAD

**Issue by a-johnston** [godotengine/godot#96810]
### Tested versions

- Tested as broken in 4.4.dev2 and 4.4.dev2.mono on Windows 10
- Tested as working in 4.4.dev1.mono on Windows 10 and working in 4.4.dev2 on Linux

### System information

Godot v4.4.dev2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6070) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

For both gdscript and c# objects, changes to exports only are updated in the editor after relaunching entirely. Testing in 4.4.dev1, gdscript changes are updated immediately and c# changes are updated after building as expected.

### Steps to reproduce

1) Add a new export to some custom class (I was testing nodes in the scene tree)
2) If on c#, build
3) See that exports are unchanged
4) Relaunch editor and see that exports are changed

### Minimal reproduction project (MRP)

N/A, bug dependent on changes done to a project rather than a fixed state

**Comment by a-johnston** [comment]
This potentially shares a root cause with https://github.com/godotengine/godot/issues/96812 if last modified timestamps on windows are always 0, resulting in the editor not being able to track when files are changed. However unlike the other issue I do not see verbose logs indicating that the editor has failed to read timestamps for files while the editor is running.

**Comment by TAGames** [comment]
> This potentially shares a root cause with #96812 if last modified timestamps on windows are always 0, resulting in the editor not being able to track when files are changed. However unlike the other issue I do not see verbose logs indicating that the editor has failed to read timestamps for files while the editor is running.

Would this break import too? I need to reload project in order to import new assets.

**Comment by a-johnston** [comment]
I'm not super familiar with the codebase but looking through https://github.com/godotengine/godot/blob/master/editor/editor_file_system.cpp it does appear that the last modified timestamp is used in a few ways to determine if a reimport/refresh should occur. I wouldn't be surprised if the issues are related given how important the last modified timestamp is.

**Comment by akien-mga** [comment]
CC @Hilderin

**Comment by Hilderin** [comment]
This issue is definitively caused by #96812
I'm investigating.
