### ISSUE TITLE
Autocompletion is broken when entering `@rpc()`

### ISSUE THREAD

**Issue by MarkoGrbec** [godotengine/godot#96818]
### Tested versions

Reproducible in 4.4.1dev and 4.4.2dev
Not reproducible in 4.3

### System information

Linux manjaro and android

### Issue description

When you type:
`@rpc()`
It works fine
But when you type: rel
It doesn't suggest reliable but everything else.
It should suggest reliable

### Steps to reproduce

Type:
`@rpc(rel)`

### Minimal reproduction project (MRP)

`@rpc("reliable")
func test():
    pass`

**Comment by dalexeev** [comment]
CC @HolonProduction

**Comment by matheusmdx** [comment]
Just to record, this is a regression from #94082

![image](https://github.com/user-attachments/assets/f2dc4dc7-e944-4070-8654-5c2e919ed1cf)

**Comment by HolonProduction** [comment]
The necessary fix is already part of #96693

**Comment by MarkoGrbec** [comment]
It is still broken in 4.4dev3

**Comment by HolonProduction** [comment]
The fix isn't part of the dev3 build, you will have to wait for dev4.
