### ISSUE TITLE
[4.4.dev2, Windows] Project manager list uses unix time 0 for all projects

### ISSUE THREAD

**Issue by a-johnston** [godotengine/godot#96812]
### Tested versions

- Tested as broken in 4.4.dev2 and 4.4.dev2.mono on Windows
- Tested as working in 4.4.dev1.mono on Windows and 4.4.dev2 on Linux

### System information

Godot v4.4.dev2.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 32.0.15.6070) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

All projects in the 4.4.dev2 project manager show up with a last edited time of 1970-01-01 00:00:00 causing the default sorting of the list to be effectively random:
![image](https://github.com/user-attachments/assets/95d77116-f651-400c-af8b-7afa1e055ced)

Notably, projects saved in 4.4.dev2 and then reopened with 4.4.dev1 show the correct last edited time for the project so it's likely the project manager is just using the wrong value, or reading the value incorrectly:
![image](https://github.com/user-attachments/assets/a2385a81-b6b9-494f-963e-64d89749690a)

### Steps to reproduce

Open the project manager and look at timestamps / try to sort projects by Last Edited

### Minimal reproduction project (MRP)

N/A, issue is with the project manager

**Comment by a-johnston** [comment]
This is potentially related to https://github.com/godotengine/godot/pull/96398; the verbose log is full of `Failed to get modified time for:  C:/Users/<user>/Documents/godot/<project name>/project.godot`

**Comment by Hilderin** [comment]
Strangely, I'm able to reproduce the problem with 4.4 dev 2 but not in dev build on master or using the commit from the dev 2: 97ef3c8
I have a lot of "Failed to get modified time for:" in verbose log.

**Comment by matheusmdx** [comment]
> Strangely, I'm able to reproduce the problem with 4.4 dev 2 but not in dev build on master or using the commit from the dev 2: [97ef3c8](https://github.com/godotengine/godot/commit/97ef3c837263099faf02d8ebafd6c77c94d2aaba)

I'm trying to bisect this rn and something i noticied is this issue doesn't happen compiling with vs2022 but shows the problem when compiled with mingw.

<br>

This is godot compiled with msvc2022:

![image](https://github.com/user-attachments/assets/0af433d4-1f0a-49b1-bb7e-042072e7fa74)


<br>

This is godot compiled with mingw:

![image](https://github.com/user-attachments/assets/35cc9e58-01fb-422d-9b2a-0da7da857a4a)

**Comment by Hilderin** [comment]
Oh!!! That probably explain why the artefact from Github CI seems to work fine.

**Comment by a-johnston** [comment]
Ah good catch! Yeah I can confirm that when compiling 97ef3c8 with msvc I don't see any `Failed to get modified time for` and the regressions described in this issue as well as https://github.com/godotengine/godot/issues/96810 and https://github.com/godotengine/godot/issues/96828 are no longer present

**Comment by Hilderin** [comment]
Check that: https://stackoverflow.com/questions/76611362/wstat-for-extended-length-path-prefixed-with-in-mingw64

**Comment by bruvzg** [comment]
Modification time should be fixed by https://github.com/godotengine/godot/pull/74830
