### ISSUE TITLE
[4.4.dev2, Windows] New assets not recognized, requires project reload to import

### ISSUE THREAD

**Issue by TAGames** [godotengine/godot#96828]
### Tested versions

v4.4.dev2.mono.official [97ef3c837]

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 32.0.15.6081) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

New assets require to reload the project to get recognized.

### Steps to reproduce

Place new file (.fbx, .wav etc.) in filesystem -> nothing happens. 
Reload project -> import happens.

### Minimal reproduction project (MRP)

N/A

**Comment by a-johnston** [comment]
Not sure why github didn't add a link but this potentially shares a root cause (last modified timestamp on windows always being 0) with https://github.com/godotengine/godot/issues/96810 and https://github.com/godotengine/godot/issues/96812
