### ISSUE TITLE
Kanji/Hanzi characters use the same font in editor, disregarding localization

### ISSUE THREAD

**Issue by chocola-mint** [godotengine/godot#96838]
### Tested versions

- Reproducible in: 4.3 stable
- Note that in 3.5.2 stable the editor always uses Droid Sans Japanese (which looks correct in Japanese but would look weird in Chinese instead)

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.5268) - 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 Threads)

### Issue description

When the editor language is set to Japanese, in the editor interface (right) the Japanese Kanji uses the Droid Sans Fallback font (which uses the Simplified Chinese variation), whereas the default ingame (left) font uses the Droid Sans Japanese font.
![image](https://github.com/user-attachments/assets/79db14d8-6565-4e19-ad5c-4821f404cb52)

The core issue here is that Kanji/Hanzi share the same unicode code points, so if we were to address this issue, we need to use different fonts for these code points.

Ideally, the editor should be able to override the default fonts based on the current editor language, as part of the editor localization system.

See also: https://heistak.github.io/your-code-displays-japanese-wrong/

### Steps to reproduce

1. Open any Godot project.
2. Go to Editor Settings, enable Localize Settings, and select `ja` as the Editor Language. Restart the editor when prompted.
3. Select any node whose inspector contains a Text Edit node. (For example: A Label node)
4. Copy and paste the following characters into the Text Edit: `刃直`.

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
> whereas the default ingame

Game have Latin only font, and use whatever system font it found. Editor use `Droid Sans` which does not support different variants. You can set a custom font in the editor settings, and it should pick the correct variant (e.g., Noto CJK).

**Comment by chocola-mint** [comment]
I believe that the user shouldn't have to fix the editor font manually for their locale, though I can also understand that installing all of the Noto CJK fonts would introduce a lot of undesirable bloat to the editor binary.

An option to install the fonts on-demand wouldn't be too unreasonable, though. Maybe as part of issue https://github.com/godotengine/godot-proposals/issues/3421. I'll look into that instead for now.

**Comment by timothyqiu** [comment]
@bruvzg I'm not sure what `Droid Sans Fallback` contains. But since we already included  `Droid Sans Japanese` for Japanese, is it reasonable to move that font before `Droid Sans Fallback` when editor's language is Japanese?

**Comment by bruvzg** [comment]
> I'm not sure what Droid Sans Fallback contains. But since we already included Droid Sans Japanese for Japanese, is it reasonable to move that font before Droid Sans Fallback when editor's language is Japanese?

It will likely work (for Japanese, it won't have different variants for simplified/traditional Chinese), but we should probably switch to Noto CJK instead. It's +20 MB, but I do not understand why do we care about editor size at all, it might be important for web export template, but not for everything else.

**Comment by timothyqiu** [comment]
Tried adjusting the priorities:

| ja | zh_CN |
|---|---|
| ![ja](https://github.com/user-attachments/assets/d8640833-ae6f-4d07-bb15-ee8ff755a21a) | ![zh_CN](https://github.com/user-attachments/assets/dd1e1516-00c0-4085-a448-afacac566b34) |

<details><summary>Patch</summary>

```diff
diff --git i/editor/themes/editor_fonts.cpp w/editor/themes/editor_fonts.cpp
index c50d1237e0..72ee31d64e 100644
--- i/editor/themes/editor_fonts.cpp
+++ w/editor/themes/editor_fonts.cpp
@@ -31,6 +31,7 @@
 #include "editor_fonts.h"
 
 #include "core/io/dir_access.h"
+#include "core/string/translation_server.h"
 #include "editor/editor_settings.h"
 #include "editor/editor_string_names.h"
 #include "editor/themes/builtin_fonts.gen.h"
@@ -149,6 +150,8 @@ void editor_register_fonts(const Ref<Theme> &p_theme) {
 			break;
 	}
 
+	const bool use_japanese_for_cjk = TranslationServer::get_singleton()->get_tool_locale() == "ja";
+
 	// Load built-in fonts.
 	const int default_font_size = int(EDITOR_GET("interface/editor/main_font_size")) * EDSCALE;
 	const float embolden_strength = 0.6;
@@ -168,8 +171,14 @@ void editor_register_fonts(const Ref<Theme> &p_theme) {
 	Ref<FontFile> tamil_font = load_internal_font(_font_NotoSansTamilUI_Regular, _font_NotoSansTamilUI_Regular_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks);
 	Ref<FontFile> telugu_font = load_internal_font(_font_NotoSansTeluguUI_Regular, _font_NotoSansTeluguUI_Regular_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks);
 	Ref<FontFile> thai_font = load_internal_font(_font_NotoSansThai_Regular, _font_NotoSansThai_Regular_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks);
+	Ref<FontFile> japanese_font = load_internal_font(_font_DroidSansJapanese, _font_DroidSansJapanese_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false);
+	if (use_japanese_for_cjk) {
+		fallbacks.push_back(japanese_font);
+	}
 	Ref<FontFile> fallback_font = load_internal_font(_font_DroidSansFallback, _font_DroidSansFallback_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks);
-	Ref<FontFile> japanese_font = load_internal_font(_font_DroidSansJapanese, _font_DroidSansJapanese_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks);
+	if (!use_japanese_for_cjk) {
+		fallbacks.push_back(japanese_font);
+	}
 	default_font->set_fallbacks(fallbacks);
 	default_font_msdf->set_fallbacks(fallbacks);
 
@@ -188,8 +197,14 @@ void editor_register_fonts(const Ref<Theme> &p_theme) {
 	Ref<FontFile> tamil_font_bold = load_internal_font(_font_NotoSansTamilUI_Bold, _font_NotoSansTamilUI_Bold_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks_bold);
 	Ref<FontFile> telugu_font_bold = load_internal_font(_font_NotoSansTeluguUI_Bold, _font_NotoSansTeluguUI_Bold_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks_bold);
 	Ref<FontFile> thai_font_bold = load_internal_font(_font_NotoSansThai_Bold, _font_NotoSansThai_Bold_size, font_hinting, font_antialiasing, true, font_subpixel_positioning, font_disable_embedded_bitmaps, false, &fallbacks_bold);
+	Ref<FontVariation> japanese_font_bold = make_bold_font(japanese_font, embolden_strength);
+	if (use_japanese_for_cjk) {
+		fallbacks_bold.push_back(japanese_font_bold);
+	}
 	Ref<FontVariation> fallback_font_bold = make_bold_font(fallback_font, embolden_strength, &fallbacks_bold);
-	Ref<FontVariation> japanese_font_bold = make_bold_font(japanese_font, embolden_strength, &fallbacks_bold);
+	if (!use_japanese_for_cjk) {
+		fallbacks_bold.push_back(japanese_font_bold);
+	}
 
 	if (OS::get_singleton()->has_feature("system_fonts")) {
 		PackedStringArray emoji_font_names;
```
</details>

Yeah, this is just a quick fix for Japanese, the underlying issue is still there. The only way to solve this is to use a dedicated font.

**Comment by bruvzg** [comment]
Another option is using system fonts, checking all fonts can be slow, but we can specifically check for "Noto CJK" and load it instead of `Droid Sans` if it is found.
