### ISSUE TITLE
[4.4 dev 2] Projects are not saved in the project manager

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#96848]
### Tested versions

4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

Projects created in 4.4 dev2 are not saved in the project manager, when the engine starts they are not in the list

### Steps to reproduce

1. Create a project in 4.4 dev2
2. Go back to the project manager
3. The project is not listed

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
Can't reproduce on Linux, likely Windows specific.

Possibly a duplicate of #96812, can you check if the project is just further down the list if you have a lot of projects and they're all wrongly sorted due to broken timestamps?

**Comment by JekSun97** [comment]
> Possibly a duplicate of #96812, can you check if the project is just further down the list if you have a lot of projects and they're all wrongly sorted due to broken timestamps?

I found a project in the middle of the list and it didn't seem to be sorted because it didn't fit any of the sorts in the sort list

**Comment by matheusmdx** [comment]
Tested with latest master v4.4.dev.custom_build [4788f54d9] and compiled with mingw, the issue was already solved, so that was a duplicate of https://github.com/godotengine/godot/issues/96812
