### ISSUE TITLE
[4.4-dev2] Editor layout is messy coming from 4.3.stable

### ISSUE THREAD

**Issue by Cronos87** [godotengine/godot#96843]
### Tested versions

- Reproductible in 4.4.dev2

### System information

macOS Sonoma 14.6.1

### Issue description

After opening a project, the editor layout looks very messy. It can be changed for sure, but this is the first time I have encountered this.

This is not critical, but we must be sure it won't happen on a fresh install; it can deter a new user. I didn't encounter this with the 4.4.dev1.

Here is my layout in 4.3:

![CleanShot 2024-09-11 at 09 27 10@2x](https://github.com/user-attachments/assets/4c5352e7-02c2-4598-959e-4762821909c2)

Here it is when freshly opened in 4.4.dev2:

![CleanShot 2024-09-11 at 09 26 22@2x](https://github.com/user-attachments/assets/7c628746-bd94-432f-ab00-8aaa315858fd)

Looks like all panes have the same width 🤔

### Steps to reproduce

I'm not quite sure how to reproduce this. I simply tried the new dev version coming from 4.3. In general, I don't play too much with the layout; we can say it's the default one.

### Minimal reproduction project (MRP)

Any project can reproduce it.

**Comment by brandonrbridges** [comment]
Dropping a note here to say I encountered exactly the same thing about 10 minutes ago. 

- Had 4.3 stable installed. 
- Installed 4.4dev2 and I got the same layout as you.

**Comment by Cronos87** [comment]
That's good to know I am not an isolated case; which means something broke between the 2 builds.

**Comment by passivestar** [comment]
This is a side effect of [a bugfix](https://github.com/godotengine/godot/pull/96343) that affects HiDPI users. This happens because the way the dock width is stored has changed in 4.4. This won't happen on a fresh install. You can only encounter this once when switching from 4.3

**Comment by Cronos87** [comment]
Many thanks for the explanation! I was worried it could happen on a fresh installation. Can it be considered closed then?

**Comment by akien-mga** [comment]
I'm afraid this might cause a lot of duplicate bug reports and bad first impressions on upgrade, so if we could find a way to handle the transition in a better way, that might be good.

**Comment by Cronos87** [comment]
Yeah, like me, my first impression was something went wrong. With the explanation it makes sense, but not everyone will know it.

**Comment by brandonrbridges** [comment]
From how successful the 4.3 update was, a large number of people will definitely encounter this bug when upgrading to 4.4.

**Comment by passivestar** [comment]
I'm not familiar with how Godot migrates projects, but I'm assuming since this window exists it's possible to run code when opening in a new version for the first time. If so it should be easy to reset docks in `editor_layout.cfg` when 4.3->4.4 migration happens

<img width="390" alt="image" src="https://github.com/user-attachments/assets/fbc916b1-812b-4cbb-b8e9-68d93c5ad512">

**Comment by akien-mga** [comment]
CC @KoBeWi

**Comment by Cronos87** [comment]
I'm not sure resetting the layout is a good solution. In my case, I don't mind because I use the default one, but people have changed it, and seeing it reset when opening the 4.4 would be a bad surprise. What do you think?

**Comment by passivestar** [comment]
> I'm not sure resetting the layout is a good solution. In my case, I don't mind because I use the default one, but people have changed it, and seeing it reset when opening the 4.4 would be a bad surprise. What do you think?

Sure, it could just divide dock widths by editor scale, no need to reset to default values

**Comment by Cronos87** [comment]
Understood, I read too fast sorry! Thank you for the explanation!

**Comment by KoBeWi** [comment]
> I'm assuming since this window exists it's possible to run code when opening in a new version for the first time.

It's possible, but currently there is no support for that, so it'd have to be implemented. The relevant code is in `project_list.cpp`.

**Comment by passivestar** [comment]
There probably should be a separate class for handling migrations that `ProjectManager::_open_selected_projects_ask()` could call when it detects changes, it needs to be easy to scale for the future editor versions. We may also want to have a way to apply multiple migrations at once in case user switches between several editor versions

Since this is a somewhat big change I'll leave it to long-term contributors to figure out, but it seems like a needed system to have

**Comment by Cronos87** [comment]
In case some people want to reproduce it, use the 4.3 version, reset to the default layout, then open the 4.4.dev2, and the issue will be present.

**Comment by Cronos87** [comment]
Many thanks for the fast fix @KoBeWi 🙏🏻
