### ISSUE TITLE
"Index p_track = 0 is out of bounds (tracks.size() = 0)" Error on new bezier track creation in AnimationPlayer

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#96849]
### Tested versions

Reproducible in Master (97ef3c837263099faf02d8ebafd6c77c94d2aaba), not present in 4.3.

### System information

Godot v4.4.dev (97ef3c837) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7800 XT (Advanced Micro Devices, Inc.; 31.0.24019.1006) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

When creating a new bezier track the following errors are printed in the console:

`scene\resources\animation.cpp:1496 - Index p_track = 0 is out of bounds (tracks.size() = 0).`
`scene\resources\animation.cpp:1496 - Index p_track = 1 is out of bounds (tracks.size() = 0).`

![image](https://github.com/user-attachments/assets/291df10e-b34c-42b9-8ca1-2182cd90f067)

Note: The `track hint` warnings are also present in 4.3, but not the error.

### Steps to reproduce

1. In a new 2D scene 
2. Create an animation player and a sprite 
3. Create a new animation and key the positions of the sprite and choose bezier curves.

### Minimal reproduction project (MRP)

NA

**Comment by Arnklit** [comment]
Bisected. Issue was introduced in 0f7c4d8375e5066500ad9a44402adbb197d1c1a2
https://github.com/godotengine/godot/pull/91854

**Comment by akien-mga** [comment]
CC @ImpishOaths @TokageItLab

**Comment by ImpishOaths** [comment]
I tested last night and #96789 seems to fix the issue. Can anyone else confirm?
