### ISSUE TITLE
Error compiling Fragment shader when assigning a negative value to either of the expressions in a terniary conditional operator

### ISSUE THREAD

**Issue by cslfrd** [godotengine/godot#96842]
### Tested versions

- Reproducible in: 4.4.dev2.official [97ef3c837].
- Not reproducible in: 4.4.dev1

### System information

Godot v4.4.dev2 - macOS 14.5.0 - Metal (Forward+) - integrated Apple M1 (Apple7) - Apple M1 (8 Threads)

### Issue description

Screenshot of code that reproduces issue:

<img width="265" alt="Skjermbilde 2024-09-10 kl  23 30 20" src="https://github.com/user-attachments/assets/7a3a536a-0a67-4083-a1b7-65e34a9d2985">

When assigning a negative value using a terniary conditional operator, the editor freezes for a couple of seconds and outputs 15.172 lines of errors. It seems like it’s the same errors of about 3.800 lines repeating several times:

```
servers/rendering/renderer_rd/shader_rd.cpp:298 - Error compiling Fragment shader, variant #2 (
# define MODE_RENDER_DEPTH
# define MODE_RENDER_NORMAL_ROUGHNESS
).
servers/rendering/renderer_rd/shader_rd.cpp:299 - Failed parse:
WARNING: 0:79: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
         "precision mediump int; precision highp float;"
ERROR: 0:2323: '--' :  l-value required (can't modify a const)
ERROR: 0:2323: '--' :  wrong operand type no operation '--' exists that takes an operand of type  const float (or there is no acceptable conversion)
ERROR: 0:2323: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.



servers/rendering/renderer_rd/shader_rd.cpp:302 - code:
```

Screenshot of error:

<img width="967" alt="Skjermbilde 2024-09-10 kl  23 32 37" src="https://github.com/user-attachments/assets/3da204c8-8a65-4c0a-96f6-66f4bd7fcbc4">

If using absolute values, it compiles without problem.
If assigning the negative value to a variable and then assigning the variable in the terniary conditional expression, it also comiles without problem. Eg.:

<img width="356" alt="Skjermbilde 2024-09-10 kl  23 29 19" src="https://github.com/user-attachments/assets/161cbd64-7784-47d7-a9fa-e6ec4ec2f185">

### Steps to reproduce

1. Create a new project in Godot 4.4-dev2
2. Add a MeshInstance3D
3. Add a new ShaderMaterial
4. Add a new Shader
5. In the fragment() function, write the following code `float value = true ? 1.0 : -1.0;`

The editor will freeze for a few seconds. The Output tab will print 15.172 lines of errors, seems like it’s the same errors of about 3.800 lines repeating several times.

### Minimal reproduction project (MRP)

[terniary-conditional-operator.zip](https://github.com/user-attachments/files/16959006/terniary-conditional-operator.zip)

**Comment by akien-mga** [comment]
Could you attach the log of the whole 3800 lines of code dump (this is generated shader code based on Godot's internal shaders and your shader code injected in it)? In particular the lines around 79 and 2323 are where the syntax errors are present.

CC @stuartcarnie

**Comment by cslfrd** [comment]
Here's the full log: 
[godot.log](https://github.com/user-attachments/files/16959753/godot.log)

**Comment by stuartcarnie** [comment]
Thanks!

The generated GLSL shader code appears to be incorrect, as you can see it has added `--`:

```glsl
2321 | 	{
2322 | 		float m_value=(true?1.0:--1.0);
2323 | 	}
```

Incidentally, we can see other blocks of code in the shader that use the ternary operator with `-1`:

```glsl
**1952 | vec2 octahedron_wrap(vec2 v) {
1953 | 	vec2 signVal;
1954 | 	signVal.x = v.x >= 0.0 ? 1.0 : -1.0;
1955 | 	signVal.y = v.y >= 0.0 ? 1.0 : -1.0;
1956 | 	return (1.0 - abs(v.yx)) * signVal;
1957 | }
```

I'll take a look, but I don't believe it is a Metal-specific issue.

**Comment by stuartcarnie** [comment]
I wonder if it is related to #93822

**Comment by stuartcarnie** [comment]
Yes, it appears when evaluating a scalar with a unary operator, it negates the value by does not remove the OP_NEGATE outer node per the following debug session:

1. Note the `op` is `OP_NEGATE`
2. So the `code` generated will convert the `OP_NEGATE` to a string `-`
3. Next the `_dump_node_code` will be called for the `arguments[0]`
4. Noting that it is a `ConstantNode` and
5. the `real` value is `-1`, so the resulting code will be

```
--1.0
```

![CleanShot 2024-09-11 at 18 37 57@2x](https://github.com/user-attachments/assets/fb85c9b6-e6e6-4c96-8972-f5b801eaf127)
