### ISSUE TITLE
Dependency checking is not working

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9685]
**Operating system or device - Godot version:**
Windows 10 – Godot master (bbada82)

**Issue description:**
The checking of dependencies inside the editor is not working.

- The "Edit Dependencies" option in the FileSystem dock's RMB menu shows nothing, even when the file is a dependency. (Also, maybe this name is a bit confusing, as it should show what depends on the file, so "Edit Dependents" would be more accurate).
- Deleting a file from the FileSystem dock isn't warning if the file is used somewhere.
- The "Orphan Resource Explorer" is showing "0" to everything.

**Comment by reduz** [comment]
Just checked and this is working now, it seems recent fixes I did made it work again
