### ISSUE TITLE
Godot crashes when minimizing floating script window

### ISSUE THREAD

**Issue by StickyWormLL** [godotengine/godot#96853]
### Tested versions

- Reproducible in 4.3.stable, 4.2.2.stable - I'm not sure about the other versions.

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Intel(R) HD Graphics 4600 (Intel Corporation; 20.19.15.5126) - Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 Threads)

### Issue description

![2024-09-11 13-47-20](https://github.com/user-attachments/assets/b8f96884-0a71-42c1-9250-cd2ee3edc892)
![2024-09-11 13-49-35 (1)](https://github.com/user-attachments/assets/6057410f-2211-435d-8c3c-9b063950ac31)
I have two screens and I've been experiencing this error for a while, when I make the floating script in another window when minimizing the window the entire project closes, I've been investigating and this should not close the entire program, if more details are needed contact me I will be happy to help more, I have attached two gifs because the size of the videos where very heavy

### Steps to reproduce

Step 1 - Create a Godot project
Step 2 - Go to the script tab
Step 3 - Select the option to make the script float
Step 4 - Make the tab large and minimize

### Minimal reproduction project (MRP)

Can be reproduced in any godot project
[bug_proyect.zip](https://github.com/user-attachments/files/16963247/bug_proyect.zip)

```[tasklist]
### Tasks
```

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92148

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
