### ISSUE TITLE
Cyclic dependencies aren't check when saving the scene, causing crashes

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9686]
**Operating system or device - Godot version:**
Windows 10 – Godot master (bbada82)

**Issue description:**
If there's a cyclic dependency on instanced scenes, Godot detects and stops it from happening. But if you that before saving, the editor crashes when you save all scenes.

**Steps to reproduce:**
* Create two scenes (say A and B) and save them.
* Open both scenes inside the editor.
* Instance B inside A, and A inside B (without saving)
* Click on Scene > Save all Scenes
* Watch Godot crashing.

Funny that I tried this in stable, and the editor let's you do this without crashing... until you play the scene.

**Comment by reduz** [comment]
Task for grabs, seems like it will need some smart hinking..

**Comment by hpvb** [comment]
I'll look at this, no promises yet :)

**Comment by bd339** [comment]
Obviously it shouldn't crash, but what should it do? Give an error that there's a cyclic dependency between A and B, when saving?

**Comment by vnen** [comment]
Yes, it should show an error popup. Godot does it, but only when you try to instance something that would cause a cyclic dependency, it doesn't check when saving. In this case it should avoid to save the scenes and show the message.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by SeleckyErik** [comment]
Wouldn't forcing a scene save before it can be instanced in another scene be an effective, yet simple solution to this problem? Or is there some hidden problem I didn't spot?

**Comment by SeleckyErik** [comment]
^ @akien-mga?

**Comment by vnen** [comment]
@SeleckyErik there's no need to ping akien specifically. He probably saw the comment already and if he didn't comment is probably because he has nothing to add. Especially since he never commented specifically about the issue in question.

Now about the point, if you mean don't let the user instance if the scene is not saved, it might be a solution. The simplest way to know is just trying it out. If you mean to auto-save when instancing, then I don't like because the user may have meant to not save it (e.g. they did only a temporary change).

**Comment by reduz** [comment]
This needs a lot of discussion, should saving be avoided? should somehow checking that a cyclic dependency exists when assigning a resource? What would be the best way to fix this?

**Comment by Shadowblitz16** [comment]
This still exists
