### ISSUE TITLE
Scripts for re-generation of textures for the editor don't work

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#9687]
**Operating system or device - Godot version:**
Mageia 6 
Godot 3.0 69a4ea34c4f630c1ca353a135d768872bb54cd41

**Issue description:**
![image](https://user-images.githubusercontent.com/1289207/28302391-432f4d5e-6b8d-11e7-830f-028268e74997.png)
edit: This glitch is actually the "ERROR" image repeating over. I'll check if something is wrong with my build.

**Steps to reproduce:**
Create a new project and copy-paste assets from another folder to the new project folder. Switch to Godot editor while importing so you can see the import popup.

**Link to minimal example project:**
N/A

**Comment by djrm** [comment]
That happens because the Icons header is not updated, i remember that before it could be commited, but now it does not get pushed when i regenerate it. to fix simply call the SVGS_2_PNGS script

**Comment by tofuhead** [comment]
I have the same issue.. tried running the script but didn't help...

**Comment by djrm** [comment]
maybe if you manually call make_headers.py in editor/icons folder?

**Comment by StraToN** [comment]
I tried to run both scripts:
- `misc/scripts/SVGS_2_PNGS.py` complains about "No module named 'rsvg'` (on Mageia6)
- `scene/resources/default_theme/make_headers.py` fails at line 12 with `TypeError: a bytes-like object is required, not 'str'`
I was able to fiw by re- `git clone` and recompile from scratch.

**Comment by StraToN** [comment]
I guess I'll close the issue since the problem is known, and scripts exist to fix it. Or maybe I should re-title it so it concerns the scripts that won't work instead?

**Comment by Noshyaar** [comment]
Have you tried running `make_headers.py` using `python2.7`?

**Comment by djrm** [comment]
@Hinsbart i had the same problem when i added those textures to the icons folder, however in my case regenerating the icons was enough for scons to regenerate editor_icons_gen.cpp, i would suggest you to check that file and see if you are able to locate the missing textures, if they are not there, it means that the file is not being correctly generated, the reason for it not being generated should be examined.

**Comment by Hinsbart** [comment]
Alright, deleting `editor_icons_gen.cpp` did the trick. I thought I did this before but I removed the old `editor_icons.cpp` instead, not knowing the file has been renamed :P

**Comment by reduz** [comment]
We really should integrate nanosvg and generate icons for the right resolution on the fly.. no one is up for this? :\ I could give it a try, but have so many things to do/fix..

**Comment by reduz** [comment]
icons are now generated on the fly, so closing this.
