### ISSUE TITLE
Animation compression has incorrect rotation

### ISSUE THREAD

**Issue by fire** [godotengine/godot#96882]
### Tested versions

- Reproducable in 4.3-stable

### System information

Mac Mini, Apple Silicon

### Issue description

With animation compression the animation glitches and jumps at certain points. With animation optimization done it does not.

https://github.com/user-attachments/assets/c0aaf8e3-3ab6-4b0e-843b-1dd4bfe02b27

### Steps to reproduce

1. Open project
2. Disable animation optimization.
3. Switch import to animation compression enabled
4. Scrub the animation timeline and you will see near 6.1 s the animation flips.

### Minimal reproduction project (MRP)

[animation-compression-game-project.zip](https://github.com/user-attachments/files/16970111/animation-compression-game-project.zip)

From @Malcolmnixon

**Comment by fire** [comment]
@TokageItLab @lyuma if you have any ideas

**Comment by TokageItLab** [comment]
Just a guess, but the compression converts rotation to axis angle, so the ambiguity may be causing problems when the next angles are around 180 or 360 degrees.

**Comment by fire** [comment]
Any idea how to solve? Can we directly get axis ambiguity?

**Comment by TokageItLab** [comment]
I confirmed that changing the block size value from 8kb will change where the glitching occurs, so I think there is some problem with the data packet boundaries.

**Comment by fire** [comment]
Do you think running a cubic / slerp interpolation between the end and the start will work?

**Comment by fire** [comment]
> There is definitely still work to be done, but IMO the stutter still looks better than the glitch, so I think it is acceptable to merge this PR and postpone the work to eliminate the stutter in the later.

From tokage
