### ISSUE TITLE
Set_owner via script(with tool) add connected signals of instance in .tscn but it is already connected( or no more) in the .tscn instance

### ISSUE THREAD

**Issue by DOGamedev5** [godotengine/godot#96886]
### Tested versions

- Reproducible in godot 3.6.stable

### System information

Fedora 40 - Godot v3.6.stable - Opengl 2.0

### Issue description

it might be related with issue #89359 

I made in my game a class that inherits from tilemap called 'TileProps', is a tool class that only run on editor, that  a use as tool for helping to add scenes props (like coins or blocks) into a scene in a way that I can save on the project files with the props.

the script that add the childs to scene works like this:
```gdscript
if i in [0, 1, 3, 4]:
   parents["blocks"].add_child(newProp)

elif i in [2]:
   parents["stairs"].add_child(newProp)

elif i in [7]:
   parents["coins"].add_child(newProp)

else:
   parent.add_child(newProp)

newProp.set_owner(get_parent())
```
in game works well, but when I see the debugger, it have 100 of errors that looked like this:
'connect: Signal "area_entered" from "coin[Area2D<id>]" is already connected to given method "_on_coin_area_entered" in [...]'

and I only was connecting by the editor, I ever tried to make the scripts local, and made in just connect via script, but I opened the .tscn file of the level and I see this:
![image](https://github.com/user-attachments/assets/01452aeb-0b0c-471c-b190-c657b1025773)
what, but isn't already connected in the .tscn file of the coin?

so, for curiosity, I removed the connect on the script and in the editor, and run the game, and... no errors, and the coin still working like it still have the signal connected.

so removing the connects of .tscn file and connecting back the signal via script, the coins still connected and no errors.

resuming, the set_owner connect signals that is already connected in the PackedScene of the instance, mading the signal being connected two times. And sorry for my bad english.

### Steps to reproduce

uising my project as reference
- open a room in 'worlds/<worldName>/rooms/room<id>.tscn' or 'dimensions/<worldName>/rooms/room<id>.tscn', (recomend using room 'worlds/sandDesert/especialRooms/welcome/welcome.tscn' for easy acess and testing)
- adding a node TileProps class
- setting some coins (the shiny blue thing, and maybe you wanna turn off the tileset pallete puglin off) 
![image](https://github.com/user-attachments/assets/3c183ab4-c942-486f-ac28-80bc5c0b489d)
- setting the export variable 'setup' to true/false
- run the game and go to the room
- closes the game and check debug log

### Minimal reproduction project (MRP)

[project2.zip](https://github.com/user-attachments/files/16971127/project2.zip)
[project1.zip](https://github.com/user-attachments/files/16971026/project1.zip)

**Comment by kleonc** [comment]
You'd need to pass `PackedScene.GEN_EDIT_STATE_INSTANCE` when calling `PackedScene.instance` if you want it to be properly recognized/treated as an instance of external scene.

So change:
```gdscript
var newProp = props[i].instance()
```
to:
```gdscript
var newProp = props[i].instance(PackedScene.GEN_EDIT_STATE_INSTANCE)
```
and there should be no duplicated connections created etc. when saving the containing scene.

**Comment by DOGamedev5** [comment]
> You'd need to pass `PackedScene.GEN_EDIT_STATE_INSTANCE` when calling `PackedScene.instance` if you want it to be properly recognized/treated as an instance of external scene.
> 
> So change:
> ```gdscript
> var newProp = props[i].instance()
> ```
> to:
> ```gdscript
> var newProp = props[i].instance(PackedScene.GEN_EDIT_STATE_INSTANCE)
> ```
> and there should be no duplicated connections created etc. when saving the containing scene.

thank you so much, I didnt know that, sorry for making a issue for this, a really thinked it as a bug.

**Comment by DOGamedev5** [comment]
I will try this, if something happen I will say here

**Comment by DOGamedev5** [comment]
it worked! thank you very much, and sorry for making a issue for this
