### ISSUE TITLE
Default Sky shader doesn't render correctly

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#96890]
### Tested versions

- Reproducible in current master ([2c136e6](https://github.com/godotengine/godot/commit/2c136e6170a40f58f2dfb89d32eadfca7156ef37))
- Not reproducible in 4.4-Dev2

### System information

Godot v4.4.dev (606eedb0c) - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

The default sky looks totally broken in master. A quick check through the history and basic testing shows that https://github.com/godotengine/godot/pull/96858 is the culprit CC @Chaosus 

_Master_
![Screenshot from 2024-09-11 17-34-14](https://github.com/user-attachments/assets/7eba58ef-3dca-4759-a18d-24685b30f441)
_After reverting https://github.com/godotengine/godot/pull/96858_
![Screenshot from 2024-09-11 17-32-18](https://github.com/user-attachments/assets/02169ca3-0718-4d4d-a288-1a11c8d2ae69)

### Steps to reproduce

1. Open a new 3D scene
2. OR add a new ProceduralSkyMaterial to a Sky
3. OR add a new PhysicalSkyMaterial to a Sky

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
Yep, sorry about that, I did not test it with a default sky.
