### ISSUE TITLE
Native file dialog visibility

### ISSUE THREAD

**Issue by jjalexander** [godotengine/godot#96896]
### Tested versions

- Reproducible in v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

I have a scene containing only a FileDialog node. It has "Use Native Dialog" checked and is marked as visible.
When opening the project, the native file dialog pops up and is now marked as not visible.
If I un-check "Use Native Dialog", it does not show up when opening the project and is still marked as visible.

### Steps to reproduce

- Setup a project that only contains one file dialog
- Mark it as visible 
- Check the "Use Native Dialog" checkbox
- Reload current project

### Minimal reproduction project (MRP)

[filedialogtext.zip](https://github.com/user-attachments/files/16974201/filedialogtext.zip)

**Comment by Giganzo** [comment]
Same as https://github.com/godotengine/godot/issues/95199
