### ISSUE TITLE
CollisionShape3Ds children of AnimatableBody3D don't move by using PathFollow3D

### ISSUE THREAD

**Issue by azur-wolf** [godotengine/godot#96901]
### Tested versions

Any 4.x version.

### System information

Linux

### Issue description

![2024-09-12 10-19-17](https://github.com/user-attachments/assets/76788d76-3da5-446c-9fe0-ab0526ee4f34)
using `PathFollow3D.progress` and `progress_ratio` will move all its children with it, except `CollisionShape3D`.

Only happens with Animatable, the rest of `CollisionBody3D` types work well.

It looks like Animatable as its meant to be used with animation player, the physics engine isn't aware of the position changes done by `PathFollow`, so `CollisionShape` children doesnt move.

I assume that with 2D is the same.

### Steps to reproduce

run the project attached and manipulate either `PathFollow3D.progress` or `progress_ratio`

### Minimal reproduction project (MRP)

[example.zip](https://github.com/user-attachments/files/16975618/example.zip)

**Comment by smix8** [comment]
An `AnimatableBody3D` is a physics body. In general all physics bodies needs to be updated in `physics_process` and not `process` by default to function correctly.

The AnimatableBody3D is set to `sync_to_physics` at its very first inspector property which is what makes it special over just a normal static body. That property makes sure that any transform change that happens outside of physics_process callbacks gets rejected.

The documentation is literally `If true, the body's movement will be synchronized to the physics frame.` which in turn means any other transform change outside of that physics step window will be rejected.

If you toggle that property off you can move it like any other static body node but it will no longer do what it is supposed to do, be 100% in sync with physics steps for moving other bodies reliable with predicted velocity.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/67257

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by azur-wolve** [comment]
> See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

In my case i was using a tool script to update the position of an entity on a map made with an external editor.

I perform a raycast to put the `AnimatableBody3D` on top of the floor on map build time (FuncGodot) to automate such instead of perfectly align it on the map editor every time.

But yes, such function wasn't called on `_physics_process()` so thats the why.

**Comment by AThousandShips** [comment]
Please add any information to the other issue
