### ISSUE TITLE
Build problem with recent Clang releases

### ISSUE THREAD

**Issue by migueldeicaza** [godotengine/godot#96918]
### Tested versions

- Reproducible with Godot master (4.4 - 83d54ab2ad476ae265b323c2b88f4623b922f4c6)

### System information

MacOS 14.6.1 - Xcode Version 16.0 (16A242 - Release Candidate)

### Issue description

It seems that a stricter Clang is triggering a problem in Godot.

The issue seems to be that Objective-C++ code includes vulkan.h, which uses an `extern 'C'` block and then includes the C `stdint.h`, but for some reason recent Clang++ map '#include stdint.h' into importing the C++ module 'std_stdint_h', which is not allowed to be done from C.

The build error is like this:

```
In file included from platform/ios/keyboard_input_view.mm:33:
In file included from platform/ios/display_server_ios.h:42:
In file included from platform/ios/rendering_context_driver_vulkan_ios.h:36:
In file included from ./drivers/vulkan/rendering_context_driver_vulkan.h:46:
In file included from thirdparty/vulkan/include/vulkan/vulkan.h:11:
In file included from thirdparty/vulkan/include/vulkan/vulkan_core.h:8325:
In file included from thirdparty/vulkan/include/vk_video/vulkan_video_codec_h264std.h:24:
thirdparty/vulkan/include/vk_video/vulkan_video_codecs_common.h:25:5: error: import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c,15]
   25 |      #include <stdint.h>
      |      ^
thirdparty/vulkan/include/vk_video/vulkan_video_codecs_common.h:17:1: note: extern "C" language linkage specification begins here [2]
   17 |  extern "C" {
      |  ^

```

I am using this workaround, which seems a bit like brute force, hence why this is not a PR:

```
diff --git a/platform/ios/SCsub b/platform/ios/SCsub
index cf565db049..1ee114e59e 100644
--- a/platform/ios/SCsub
+++ b/platform/ios/SCsub
@@ -95,6 +95,8 @@ else:
 # (iOS) Enable module support
 env_ios.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])
 
+env_ios.Append(CCFLAGS=["-Wno-module-import-in-extern-c"])
+
 
 def combine_libs(target=None, source=None, env=None):
     lib_path = target[0].srcnode().abspath
```

### Steps to reproduce

To reproduce this issue you need a recent clang, like the one that was just released for Xcode 16.0.

Build Godot on MacOS, like this:

```
scons p=ios
```

### Minimal reproduction project (MRP)

None is needed, just upgrading Xcode 16.0

**Comment by kisg** [comment]
FYI we have a fix for this issue, just need to replace the usual vulkan inclusion block with this:

```cpp
#ifdef USE_VOLK
#include <volk.h>
#else
#include <stdint.h>
#define VK_NO_STDINT_H
#include <vulkan/vulkan.h>
#endif
```

If this is acceptable, then we can provide a PR.

**Comment by akien-mga** [comment]
> FYI we have a fix for this issue, just need to replace the usual vulkan inclusion block with this:
> 
> ```c++
> #ifdef USE_VOLK
> #include <volk.h>
> #else
> #include <stdint.h>
> #define VK_NO_STDINT_H
> #include <vulkan/vulkan.h>
> #endif
> ```
> 
> If this is acceptable, then we can provide a PR.

This seems like a workaround. I think the issue should be fixed in the Vulkan headers if they're doing something illegal - or in Clang if it's misled.

How should one import for the C `stdint.h` in C code used from Obj-C++ with that Clang version? That's something that should be reproducible in a minimal example and can be discussed upstream with LLVM. It would seem weird to me that the solution is to stop using `stdint.h` in C code.

**Comment by migueldeicaza** [comment]
This is not a limitation with Objective-C++, it happens with plain C++ with newer clang.

Simple repro:

demo.cpp:
```
extern "C" {
#include <stdint.h>
}
```

Compile with:

```
$ c++ -c -fcxx-modules -fmodules demo.cpp
a.cpp:2:1: error: import of C++ module 'std_stdint_h' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c]
    2 | #include <stdint.h>
      | ^
a.cpp:1:1: note: extern "C" language linkage specification begins here
    1 | extern "C" {
      | ^
1 error generated.
```

The combination that triggers this is `-fcxx-modules` and `-fmodules`.

I found the documentation here:

https://clang.llvm.org/docs/Modules.html

**Comment by akien-mga** [comment]
Thanks, I can reproduce it on Fedora 40 too with Clang 18.1.6 and the above demo, with just `clang++ -fmodules demo.cpp`:
```
demo.cpp:2:1: error: import of C++ module '_Builtin_stdint' appears within extern "C" language linkage specification [-Wmodule-import-in-extern-c]
    2 | #include <stdint.h>
      | ^
demo.cpp:1:1: note: extern "C" language linkage specification begins here
    1 | extern "C" {
      | ^
1 error generated.
```

**Comment by akien-mga** [comment]
It seems like just changing `#include <stdint.h>` to `#include <cstdint>` fixes it?

**Comment by TCROC** [comment]
I just updated xcode on my mac and am also now encountering this issue.  Do we have a fix or recommended workaround while this is being looked into?

**Comment by zaddok** [comment]
I have manually applied this patch to my checkout of the 4.3 branch and I can confirm for people on 4.3, that this patch does allow building on MacOS 15.1 using Xcode 16.1.
