### ISSUE TITLE
"register" keyword

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#9691]
I was looking at new commits and found `register` keyword in e089989. This keyword is deprecated since C++11 and will be removed in C++17, so probably it's not needed there.

**Comment by RandomShaper** [comment]
Yes, I used it to align to what was already there.

Actually, we should open soon the debate about upgrading the C++ standard used in Godot.

In fact, from C++11 we wouldn't even need all the atomic stuff there.

**Comment by RandomShaper** [comment]
I wouldn't remove `register` just from this file. It's anyway probably used in many other places.

Instead, I've opened an issue (#9694) to discuss the future of Godot in terms of C++ support and `register` is listed there so it becomes a candidate for removal throughout the full code base.

**Comment by Marqin** [comment]
@RandomShaper so maybe reopen this if #9694 is not to happen?

**Comment by RandomShaper** [comment]
Let's see if at least we come to some agreement about certain points. If the `register` issue ends up disregarded, we'll reopen this to discuss it isolatedly here.
