### ISSUE TITLE
KinematicBody2D with two collision shapes crashes on run

### ISSUE THREAD

**Issue by tofuhead** [godotengine/godot#9692]
_bugsquad edit:_ 
it seems it was observed on 79d85b7ff67e6edc700336ac112dad35e07fe102
Sample project is inside third comment.

-------------------------------------------------

**Operating system or device - Godot version:**
Kubuntu 17.04, Godot git master compiled today 

**Issue description:**
if a KinematicBody2D, with two collision shapes collides with a StaticBody2D with just one collision shape on it, crashes on run.  if you remove the second collision shape from KinematicBody2D it works just fine. if you add another collision shape to the StaticBody2D it works.

this I get on console: 
ERROR: operator[]: FATAL: Index p_index out of size (size()).
   At: core/vector.h:146.

**Comment by RandomShaper** [comment]
Godot version?

**Comment by tofuhead** [comment]
[collision_bug.tar.gz](https://github.com/godotengine/godot/files/1155598/collision_bug.tar.gz)

example scene for quick testing.

**Comment by pwab** [comment]
> Godot version?

According to the screenshot it is a `v3.0.alpha.custom_build`

**Comment by RandomShaper** [comment]
When I looked at this for the first time, there was no description at all.

Someone is gaslighting me... :)

**Comment by tofuhead** [comment]
@RandomShaper yes sorry about that.. when I started entering the report I somehow managed to publish it before I had typed anything on the description :(   so I quickly filled that but you were even quicker to respond :) 



.b

**Comment by eon-s** [comment]
Quickly tested some fixnum builds (before-after big shape changes), the one at july 3 is when starts failing.
