### ISSUE TITLE
Panel container does not fit to content after making it visible

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#96932]
### Tested versions

4.4 dev2 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I have a scene like this
![image](https://github.com/user-attachments/assets/3399ef87-4517-4dbd-8aab-7caa0a19dd1a)

Toggling visibility of the PanelContainer makes it glitched:

https://github.com/user-attachments/assets/8f20eafb-37a4-475c-8576-8fdc4cfdcfdf

It becomes smaller than its children. However resizing it will first cause jump to correct size and then you can't shrink it past the children size. Most often it happens at runtime when toggling visibility of a panel.

### Steps to reproduce

1. Make a scene with PanelContainer
2. In certain configuration, hiding and showing it will break its size

### Minimal reproduction project (MRP)

[EditorRepro.tscn.txt](https://github.com/user-attachments/files/16985087/EditorRepro.tscn.txt)
Scene from the example.

**Comment by kitbdev** [comment]
Probably TabContainer or another Container's minimum size uses visible in tree instead of visible.
