### ISSUE TITLE
No option to specify the map in `NavigationLink2D/3D`

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#96945]
### Tested versions

4.3-stable

### System information

Windows 11

### Issue description

`NavigationLink2D/3D` are constrained to a single map in the navigation server. However the `NavigationLink2D/3D` nodes do not expose any option to specify for which map they are valid. Instead they are just always added to the default navigation map.

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
Please open a [proposal](https://github.com/godotengine/godot-proposals) instead, this is very much not a bug but a potentially missing feature and is not handled well by the bug report template (as you can see when you need to ignore the steps listed in it)

So please open a proposal instead
