### ISSUE TITLE
There is no `NavigationMapInstance2D/3D` node

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#96946]
### Tested versions

4.3-stable

### System information

Windows 11

### Issue description

According to the [docs](https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_different_actor_types.html), supporting different actor types is done by using multiple navigation maps. However, there is currently no `Node` for navigation map's which means you can only add multiple maps through code. This makes it quite cumbersome to edit these maps, like rebaking them in editor or adding navigation links.

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
Please open a [proposal](https://github.com/godotengine/godot-proposals) instead, this is very much not a bug but a potentially missing feature and is not handled well by the bug report template (as you can see when you need to ignore the steps listed in it)

So please open a proposal instead
