### ISSUE TITLE
Editor is blinking with strange color lines in Compatibility mode

### ISSUE THREAD

**Issue by jackycute** [godotengine/godot#96943]
### Tested versions

- Reproduce in Godot v4.4.dev2 - Windows 10.0.22631 - OpenGL 3 (Compatibility) - Intel(R) UHD Graphics (Intel Corporation; 32.0.101.5972) - 12th Gen Intel(R) Core(TM) i5-1240P (16 Threads)

### System information

Godot v4.4.dev2 - Windows 10.0.22631 - OpenGL 3 (Compatibility) - Intel(R) UHD Graphics (Intel Corporation; 32.0.101.5972) - 12th Gen Intel(R) Core(TM) i5-1240P (16 Threads)

### Issue description

I tried to open my previous project and the editor shows strange color lines on 2D scene UI and AnimationPlayer tracks.
Those line color changes whenever I move my mouse.
![Screenshot 2024-09-13 111855](https://github.com/user-attachments/assets/df122982-5165-48a3-b05e-2821aa7a3bda)
![Screenshot 2024-09-13 112144](https://github.com/user-attachments/assets/187574f6-4314-4d0b-b827-085112e26baf)

### Steps to reproduce

Open any new project in Godot 4.4 dev-dev2 can reproduce this.

### Minimal reproduction project (MRP)

Open any new project in Godot 4.4 dev-dev2 can reproduce this.

**Comment by akien-mga** [comment]
Can you reproduce the issue in 4.3.stable?

**Comment by jackycute** [comment]
> Can you reproduce the issue in 4.3.stable?

No, 4.3 stable doesn't have this issue.

**Comment by akien-mga** [comment]
This is most likely a bug with ANGLE, which was enabled by default for old Intel processors after the 4.3 release. CC @bruvzg @clayjohn

**Comment by clayjohn** [comment]
It could also have been introduced by https://github.com/godotengine/godot/pull/96413 (or a combination of both)

**Comment by clayjohn** [comment]
@jackycute Can you try disabling the [`rendering/gl_compatibility/fallback_to_angle`](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-gl-compatibility-fallback-to-angle) project setting?

**Comment by jackycute** [comment]
> @jackycute Can you try disabling the [`rendering/gl_compatibility/fallback_to_angle`](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-rendering-gl-compatibility-fallback-to-angle) project setting?

Thanks for the reply.
I tried to disable `rendering/gl_compatibility/fallback_to_angle` in project settings but the blinking color lines are still there.
But if I choose to use `opengl_angle` for `rendering/gl_compatibility/driver.windows`, the blinking color lines are gone, but the project re-importing every assets again and again (maybe this is another issue?).

**Comment by bruvzg** [comment]
> UHD Graphics

None of `UHD Graphics` cards should be in the ANGLE fallback list, so it should not be ANGLE related.

**Comment by Maran23** [comment]
Is it also reproducable at 4.4 dev1?

**Comment by jackycute** [comment]
> Is it also reproducable at 4.4 dev1?

No, I can't reproduce this at 4.4 dev1, only reproducable at 4.4 dev2.

**Comment by Maran23** [comment]
Hm, this really sound like it is caused by https://github.com/godotengine/godot/pull/96413.
I wonder if we should rather not overwrite any of that shader methods at all.
Only do that for the broken adreno devices, if that is possible.

**Comment by clayjohn** [comment]
I can't reproduce with Godot v4.4.dev2 - Windows 10.0.22631 - OpenGL 3 (Compatibility) - Intel(R) UHD Graphics 620 (Intel Corporation; 27.20.100.8681) - Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 Threads)

So this seems to be a problem with that specific device/driver version.

**Comment by oxygen** [comment]
Upgraded to same Godot version as OP. 

Strange colored blinking squares for the 3D world on iOS 18 on gl_compatibility (forward+ works; mobile doesn't show 3D world at all). 2D works fine.

iOS 17 works fine.

**Comment by clayjohn** [comment]
> Upgraded to same Godot version as OP.
> 
> Strange colored blinking squares for the 3D world on iOS 18 on gl_compatibility (forward+ works; mobile doesn't show 3D world at all). 2D works fine.
> 
> iOS 17 works fine on gl_compatibility.
> 
> I'm not super sure but the fps seems much lower too (iOS 17 XS Max) on gl_compatibility than godot 4.3. I'll do more t tests.
> 
> Confirmed issue with 4.4 as 4.3dev5 works fine on gl_compatibility on the new iOS 18 (max fps for my project).

A few follow up questions:
1. What devices are you testing with?
2. Have you compared to 4.3 stable? 4.3 dev 5 is from back in March. So it doesn't help us narrow things down

**Comment by oxygen** [comment]
@clayjohn 
I edited the comment you replied to. Let me know if you think a separate bug with a repro project is needed for this one
