### ISSUE TITLE
In Godot 4.2.2, making bools true or false doesn't work in code.

### ISSUE THREAD

**Issue by Jordan4Longshaw** [godotengine/godot#96952]
### Tested versions
- Reproducible in v4.2.2.stable.official [15073afe3]
- 
![Bools not working - snapshot 001](https://github.com/user-attachments/assets/1995352e-e4cd-46a3-a894-d244559bf7c7) 

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated Radeon RX 5500 XT (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

I've tried in the ready function of my player character, in functions that get called when I do specific inputs. But "bool_name = true", "bool_name == true" (and the same for making them false) does nothing. The bools just stay either "true" or "false" 24/7. Depending on what I set them too when I declared them as a variable.

NOTE: I haven't tried to replicate this in any version of Godot that's later than 4.2.2. This is because I've only ever downloaded the one version, and worry that if I download a newer version, that my old projects will be impacted. I worry about this because I don't know what happens to my old projects when a new version gets downloaded. Do they instantly migrate to the new version? Can I still load them ok? Etc etc

Sorry if this is an inconvenience, but I can't find anything online regarding this, and don't want to risk all the effort I've put into my current and old projects.

### Steps to reproduce

Boot up a project that in 4.2.2, and attach a script to any node, create a bool variable and make it an `@export` one to see it not turning off or on when the code runs. In the "ready()" function, write the name of your bool like this "bool_name = true" or "bool_name = false" (depending on what you want). Then press play with the screen windowed, so you can see that the booleans tick box in the inspector remains unchanged.

### Minimal reproduction project (MRP)

[Godot project - Test 004 (Desktop).zip](https://github.com/user-attachments/files/16992426/Godot.project.-.Test.004.Desktop.zip)

**Comment by WhalesState** [comment]
```gdscript

@export var is_dead: bool:
  set(value):
    is_dead = value
    print("is_dead = %s" is_dead)

```

Initializing an exported variable without a variable is fine because it will not call the setter when it's changes, this code should print `is_dead = true` when the game starts, test it.

**Comment by AThousandShips** [comment]
Please attach an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by 0x0ACB** [comment]
Its `_ready` not `ready`

**Comment by AThousandShips** [comment]
Didn't even notice that in the screenshot, that's why pasting the code as text and providing an MRP is very important 

Does it work with the correct method?

**Comment by Jordan4Longshaw** [comment]
> Its `_ready` not `ready`

In a separate project I have it as "_ready". And as shown in the screenshot I attached to this comment

![Bools not working - snapshot 002](https://github.com/user-attachments/assets/0b124ac7-8f40-4c0b-adf0-0591101f2ba2)
, the issue is replicated

**Comment by 0x0ACB** [comment]
You are supposed to paste the code as text. Not screenshots...

**Comment by Jordan4Longshaw** [comment]
> You are supposed to paste the code as text. Not screenshots... And post a minimal example that reproduces the issue

I have it as  `_ready():` in a new project. With the whole code in the entire project as

`extends Node3D

@export var bool_name : bool = false

# Called when the node enters the scene tree for the first time.
func _ready():
	bool_name = true`

Think the code is pasted as text now. But won't know till I hit send. First time posting

**Comment by Jordan4Longshaw** [comment]
> Please attach an MRP to make this easier to test:
> 
> * A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
> * Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
> * Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
> * **Note for C# users:** If your issue is _not_ C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

MRP should be attached to the OP now, first time trying, so let me know if any more issues

**Comment by AThousandShips** [comment]
It works perfectly fine, the boolean shows as `true` when inspected

But from your screenshot it looks like you're looking at the *local* inspector, you need to switch to "Remote" where it says "Remote" and "Local" above the node tree

**Comment by Jordan4Longshaw** [comment]
> It works perfectly fine, the boolean shows as `true` when inspected
> 
> But from your screenshot it looks like you're looking at the _local_ inspector, you need to switch to "Remote" where it says "Remote" and "Local" above the node tree

So it does. Strange, in another project the player won't die even when bool `is_dead` becomes true. The death function is set to play when that happens. But even with the below code, the death animation I have linked up doesn't even play.

`func die():
	anim_tree.set("parameters/NDeath/request",AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)`

But there's a lot more code in that one, so posting it here might not be best. Thanks for your help so far
