### ISSUE TITLE
Pressing any accent key in editor using Portuguese (Brazil ABNT2) keyboard blocks any further input

### ISSUE THREAD

**Issue by Dowsley** [godotengine/godot#96963]
### Tested versions

- Reproducible in Godot 4.2-stable x86_64 in Linux
- Reproducible in Godot 4.3-stable x86_64 in Linux
- Seems to also be reproducible in the latest master commit (hash 5675c76461e197d3929a1142cfb84ab1a76ac9dd) in Linux

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - Wayland - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

I am using Portuguese (Brazil ABNT) keyboard layout. When in the script editor, if I press any of the relevant accent keys that can create accented letters (`^`, `´`, etc), the accent appears as a character in the editor with an underline score, which would normally mean it is waiting for a further input, but **instead**, I am unable to further input anything. Any keypress after this is ignored, even for actions outside of just typing (e.g. saving with Ctrl+S). The rest of the UI is responsive to the mouse, but even after closing the script and re-opening it, or other scripts, my keypresses remain ignored. Restarting Godot seems to be the only solution for me.

Suffice to say the expected behaviour would be to type the accent, see it appearing on the screen with an underline indicating it expects further input, then press a character and one of the following happens:
1 - Type a valid letter, and see it become its accented character version. e.g. `^ + a` turns into  `â`.
2 - Or type a non-letter character, and have the character accent get inserted by itself, without any underscore.

This is specially inconvenient because this key is close to the P key on most keyboards, and most of the times I press accents accidentally, and am forced to restart my application.

Here's a [video](https://youtu.be/cxOJha5w-9c) demonstrating this.

### Steps to reproduce

- Have a Portuguese (Brazil ABNT) keyboard layout (physical and or operating system layout).
- Create a new project or open an existing one
- Open script editor
- Input any accent key that can create an accented letter character
- Try to input more characters. Will fail.

### Minimal reproduction project (MRP)

Should be reproducible in any blank, new project.

**Comment by Dowsley** [comment]
Relevant to say I couldn't reproduce this in my Windows 10 machine.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/85664

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
