### ISSUE TITLE
Android code editor indents heavily for interacting

### ISSUE THREAD

**Issue by SalticHash** [godotengine/godot#96964]
### Tested versions

- Reproducible in 4.3.stable of android

### System information

Android 14

### Issue description

When you select lines in the code editor, a lot of out of place indentation appear, making the code have lots of indentation errors.

### Steps to reproduce

Open a script and star selecting lines.
Example video appended.

https://github.com/user-attachments/assets/320f946e-693a-45d1-9c37-c6c5b42cd390

### Minimal reproduction project (MRP)

N/A

**Comment by HolonProduction** [comment]
How are you changing the cursor position? Are you clicking the edit or changing it using the soft keyboard?

**Comment by SalticHash** [comment]
> How are you changing the cursor position? Are you clicking the edit or changing it using the soft keyboard?

I am just touching the screen with my finger.

**Comment by akien-mga** [comment]
Thanks for the report. This appears to be the same bug as reported in #70751, so consolidating it there as that's where debugging is happening.
