### ISSUE TITLE
Swap position of editor toolbars?

### ISSUE THREAD

**Issue by Geequlim** [godotengine/godot#9697]
**Operating system or device - Godot version:**
Godot Editor 3.0 for all supported platforms

**Issue description:**

![image](https://user-images.githubusercontent.com/6964556/28320700-d848b706-6c03-11e7-94e7-e4fead222f18.png)

* To adapting to new layout changes is painful for who is using the old editor every day like me.
* In my opinion the toolbar contains `Run/Pause` buttons is used more frequently than the one contains `2D/3D` as we don't need to change the 2D/3D editor too much in real development.
* I think the time it takes to submit this issue is so short relative to change my habit to fit the new layout.

**Comment by akien-mga** [comment]
I'm not for a full swap as I think it's still pretty common to switch between 2D and Script, or 3D and Script respectively. But I agree that I haven't gotten used to the play buttons to the far right yet either :)

There were proposals to put all of them in the middle which looked quite good IMO; the only drawback is that there is nothing to the right then ;)

**Comment by MrMaidx** [comment]
This was discussed a lot before in many issues and people agreed that the new way is better (buttons should be close to things they are affecting).
If you want to be truly effective you should use keyboard shortcuts (F5 is to play a whole project, F6 to play a scene, ...)

**Comment by kubecz3k** [comment]
I think we should wait some time, and see if people will get used to this change. When it comes to putting 2d/3d/Script on the right, that would be more worse in my opinion.

**Comment by pwab** [comment]
Wasn't this discussed in detail here #8865 ?

> I think the time it takes to submit this issue is so short relative to **change my habit to fit the new layout**.

Well... I think the change was made for a **reason**. And I also think that every major release can come up with those *veteran-heartbreaking-revamps* - especially when it comes to ui and api changes.

**Comment by reduz** [comment]
IMO This would be ideal, and we just get rid of the "main screen" editor plugins. Asset lib can go somewhere else or be a floating window, it won't change much. It's some work though..

![image](https://user-images.githubusercontent.com/6265307/28329756-57a02144-6bc1-11e7-8bd3-0d73381f80ed.png)

**Comment by reduz** [comment]
Yes, I know it takes space from the list of scenes. For small screens remember these should be condensed to just icons (already works this way in fact).

**Comment by MrMaidx** [comment]
Maybe there could be a poll with pictures of all possibilities? We could let Facebook group decide, there is enough people there to consider their vote as a will of all. :)

**Comment by akien-mga** [comment]
> Yes, I know it takes space from the list of scenes. For small screens remember these should be condensed to just icons (already works this way in fact).

There is enough free space in the top section that we don't need to clutter the tabs. We could do this instead:
![28329756-57a02144-6bc1-11e7-8bd3-0d73381f80ed](https://user-images.githubusercontent.com/4701338/28330230-128ace98-6bed-11e7-937a-ffa5fead0d58.png)

> Maybe there could be a poll with pictures of all possibilities? We could let Facebook group decide, there is enough people there to consider their vote as a will of all. :)

No, that's a terrible idea :) Never ask the crowd to make design decisions, it would turn in an endless bikeshedding.

**Comment by djrm** [comment]
I really dont see the point in having 2D and 3D buttons, since the viewport type is based on the node selected, also drag and drop works under the same premise, in that sense the only relevant toggle is script and view, since a scene can have code and graphical elements.

**Comment by akien-mga** [comment]
> I really dont see the point in having 2D and 3D buttons, since the viewport type is based on the node selected

Well it's relevant if you have a scene with both 2D and 3D elements (e.g. GUI + 3D), and you want to toggle the view without having to select a node of the corresponding type in the scene tree.

**Comment by reduz** [comment]
> There is enough free space in the top section that we don't need to clutter the tabs. 

It's not about free space, it's about discoverability. The priorities should always be in this order:
1) Discoverability
2) Usability
3) Aesthetics

**Comment by akien-mga** [comment]
>>  There is enough free space in the top section that we don't need to clutter the tabs.
>
> It's not about free space, it's about discoverability. The priorities should always be in this order:
>
> 1. Discoverability
> 2. Usability
> 3. Aesthetics

I don't think that my proposal goes against this. Having the View/Script/Expand buttons on the top of the screen next to the play buttons is very discoverable, usable and looks good :)

**Comment by Zylann** [comment]
I find script/view menus on the top bar easier to "aim for", rather than being in the menu bar where there can be quite a lot of menus sometimes. But that must be because I got used to it, so it felt natural.

**Comment by pwab** [comment]
I'm not sure how to measure and decide which one of the last two proposals is better in the sense of discoverability, usability and aesthetics. Is an editor setting an option so you could activate the proposal of @akien-mga ?

Or even a responsive layout which adapts to the editor width?

I think this topic is kind of a black hole for dicussions because for all 3 points you will find someone who is convinced, that the other proposal is besser. Reminds me of the introduction of the ribbon interface in ms office...

**Comment by akien-mga** [comment]
>  Is an editor setting an option

Nope, there are way too many editor options already, and it's not a significant enough difference to warrant that. We just need to pick one style :) For me both proposals are exactly the same in terms of discoverability and aesthetics, and mine is IMO slightly better for usability for the reason mentioned by @Zylann as well as the fact that this bar gets easily cluttered by tabs.

**Comment by kubecz3k** [comment]
I also more like what Akien proposed more, dont see how that proposition would harm discover-ability, and in short I agree with @Zylann.  But I must say I kind of like even how it's handled currently.

**Comment by pwab** [comment]
> Nope, there are way too many editor options already, and it's not a significant enough difference to warrant that. We just need to pick one style :)

If this is the case, then I can't decide, which should be chosen. The difference (in the sense of the 3 points) between these two can't be measured (A/B testing would be beyond insanity) and so it is a matter of taste (can be counted by the use of *IMO* in the UI related issues).

UI of modern huge software systems (ie IDEs) is a thing of personality and everything which I can't change I'm getting used to.

So for now maybe we could also toss a coin? And if there are issues coming up because there is not enough space or things are hidden or something like that because of this UI decision we could come back to this later?

> > Maybe there could be a poll with pictures of all possibilities? We could let Facebook group decide, there is enough people there to consider their vote as a will of all. :)

> No, that's a terrible idea :) Never ask the crowd to make design decisions, it would turn in an endless bikeshedding.

Aren't we doing now this right here? 😄

**Comment by reduz** [comment]
> I don't think that my proposal goes against this.

I do, it makes it look like they are related when they are not.

So, given we still can't reach an agreement, let's just leave he current design. I would only change one thing, which is removing the panel around the play buttons. This will hopefully make it less confusing.

![image](https://user-images.githubusercontent.com/6265307/28337254-6d01b538-6bdb-11e7-9bee-c13cb0922884.png)

That said, I honestly don't understand why you guys want it in the middle so bad. Only Unity that I know of uses this, every other engine doesn't. Let's try not to be like Unity for no reason.

Here's some examples:

![image](https://user-images.githubusercontent.com/6265307/28337301-98f2c7fe-6bdb-11e7-8305-8ada0dc8cdf1.png)
![image](https://user-images.githubusercontent.com/6265307/28337356-c091cdb4-6bdb-11e7-9fa6-79069838a142.png)
![image](https://user-images.githubusercontent.com/6265307/28337406-f438aa0c-6bdb-11e7-91fe-d6e3110279cc.png)
![image](https://user-images.githubusercontent.com/6265307/28337459-12eda89e-6bdc-11e7-8ba5-e3b631fedf40.png)
![image](https://user-images.githubusercontent.com/6265307/28337496-2f04362e-6bdc-11e7-8bc0-79677268a277.png)

**Comment by TeddyDD** [comment]
How hard it would be to make this optional?

**Comment by akien-mga** [comment]
> How hard it would be to make this optional?

Not hard, but as I said making everything optional is not an option :)

Either there is a usability issue, in which case it should be addressed. Or there is just a resistance to change/some muscle memory to relearn, in which case you guys will just have to live with it for a couple weeks and then be fine with the new placement :)

**Comment by TeddyDD** [comment]
Yeah, I'm completely fine with current 3.0 UI, I just like "customize everything" approach :)

**Comment by groud** [comment]
If on day we implement a feature discovery (the kind of tutorials that pop in front of the interface showing you the main features). I can imagine how the message will be :

**Comment by AlexHolly** [comment]
I like the current ui it doesn't feel wrong. I cant see any downsides and got instantly used to it not like the Project,Scene order :D twice! Is it possible to add themes with the assetlib/plugin system so that the editor settings stay clean?

**Comment by vnen** [comment]
I'm fine with any choice, but I do want to be able to make custom main screen plugins.

**Comment by willnationsdev** [comment]
I second @vnen and @TeddyDD here. The current look feels and is used fine by me and it's really nice to be able to create new buttons in the top section that changes the main viewport for anything custom.

**Comment by reduz** [comment]
will be closing this for now given no better solution could be found
