### ISSUE TITLE
Undo after add point on path2d breaks undo

### ISSUE THREAD

**Issue by MichaelTheHuman** [godotengine/godot#96997]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Windows 11 Pro - v4.3.stable.official [77dcf97d8]

### Issue description

Bug description:
1. Undo on path2d after adding a new point on an existing line breaks the application
2. The Undo and further Undo actions will not work
3. Points on the path can no longer be deleted
4. New Nodes cannot be added (Output says: `Condition "!p_node->is_inside_tree()" is true.`)

Restarting the application seems to help.

Console Output after trying to undo:
```
  core/object/undo_redo.cpp:471 - Condition "action_level > 0" is true. Returning: ""
  core/object/undo_redo.cpp:426 - Condition "action_level > 0" is true. Returning: false
```

### Steps to reproduce

1. Create a new path 2d
2. Add bunch of points to create a path
3. Create a new point on an existing path
4. Press Ctrl-Z to Undo

### Minimal reproduction project (MRP)

It only happens after you try to undo. Loading a project after it happened doesn't have the issue. 
[undo_path_bug.zip](https://github.com/user-attachments/files/17002482/undo_path_bug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/96081

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened 

This has already been fixed and will be in a future 4.3.x version
