### ISSUE TITLE
autoload dictionary is broken

### ISSUE THREAD

**Issue by MarkoGrbec** [godotengine/godot#96990]
### Tested versions

Reproducible in 4.4.dev2
not reproducible in 4.3 stable

### System information

Linux manjaro

### Issue description

in auto load it sets the dictionary but it doesn't read it

if I try reading from autoload it doesn't want to read it
I check if it's present in autoload with inspector and wala there it is but it doesn't read it

![image](https://github.com/user-attachments/assets/c4dc4ce8-541f-4130-8487-8c4a64fe3e42)

it should read the dictionary

### Steps to reproduce

1. make autoload
2. make dictionary inside
3. go to some else script try adding something to it
4. try to receive data from that dictionary -> error

```
var dict_id__entity_client = {} # local dictionary it's not related
func test1():
	g_man.dict_id__entity_client[1] = "WTF"
	var asdf = dict_id__entity_client[1]
	print(asdf)
```
error:
`Invalid access to property or key '1' on a base object of type 'Dictionary'.`
```
var dict_id__entity_client = {} # local dictionary it's not related
func test1():
	dict_id__entity_client[1] = "WTF"
	var asdf = dict_id__entity_client[1]
	print(asdf)
```
works fine

so it means dictionary is broken at auto load

### Minimal reproduction project (MRP)

```
var dict_id__entity_client = {} # local dictionary it's not related
func test1():
	g_man.dict_id__entity_client[1] = "WTF"
	var asdf = dict_id__entity_client[1]
	print(asdf)
```

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test and to get the full picture of what is going on

**Comment by MarkoGrbec** [comment]
sorry yesterday I was in a bit of a hurry and didn't tested it properly and didn't have enough time for making MRP I tested it again today and it works. there was a bug somewhere else in a code of mine that it didn't work properly but. but at testing I forgot to add g_man. at pulling out value.

sorry for your time.

**Comment by AThousandShips** [comment]
Happy it ended up working for you! Closing and if you have any further issues feel free to open a bug report, but you can get faster feedback if you're uncertain if something is a bug by asking in the other [community channels](https://godotengine.org/community/) like the forums

Good luck in your developing!
