### ISSUE TITLE
No alpha in RenderTargetTextures

### ISSUE THREAD

**Issue by Micha0** [godotengine/godot#970]
It seems alpha is not displayed when using RenderTargetTextures.

How to reproduce:
Take the viewport/gui_in_3d demo.
Change the StyleBoxTexture of the Panel (gui) to a texture which has bigger rounded corners than the default.
Optionally add some objects behind the quad to make the lack of alpha more apparent.
The result would look something like this:
![](http://www.michavk.dds.nl/pub/ONTBIL7Es2ItRjTuKtdh/godot_alpha_issue_run_.jpg)

**Comment by tommy3** [comment]
i found the method RasterizerGLES2::clear_viewport(...) which clears always to a non-transparent color. i changed this to use the transparent-background-flag (current_rt_transparent) and then clear to a transparent color. seems to work and the flag "Transparent Bg" in the editor also reacts immediately.

i'm really clueless about the side effects of it and if it's a useful fix.

@Micha0 if you like, clone my repo from https://github.com/tommy3/godot (branch **viewport-transparency**) and give it a try if it works also for you!

**Comment by Micha0** [comment]
@tommy3: Sounds legit to me. Will have a look at your code soon.
I must ask: "Transparent Bg" in the editor reacts immediately?? In my Godot, RenderToTexture only works when I run the scene. And only after some code which sets the diffuse texture to the Viewport's render_target_texture. How did you get it to "run" in the editor?

**Comment by tommy3** [comment]
i played around without scripts... look at these two screenshots:

i've created a scene with a texture frame with clouds as background and a control + viewport to clip a sprite inside of it...

with "Transparent Bg" = OFF the area of the viewport is opaque:

![viewport1](https://cloud.githubusercontent.com/assets/7785953/5651755/79b823d8-96aa-11e4-9d57-72ab4606121b.jpg)

immediately after changing the flag "Transparent Bg" the area of the viewport gets transparent:

![viewport2](https://cloud.githubusercontent.com/assets/7785953/5651759/85ae3632-96aa-11e4-97f7-754df623d523.jpg)

that's what meant as i said the editor reacts immediately to changes of the flag.

**Comment by akien-mga** [comment]
What's the status on this issue? @tommy3, do you want to make a pull request with a76a8f99?

**Comment by tommy3** [comment]
@akien-mga i've retested this issue with nightly-build 10/30/2015 12:25 AM and it seems to me it's still an issue. i don't believe that my changes are a good fix (it was a quick-hack) because in the latest version of the source the function i mentioned now uses the alpha-channel of the clear-color. in my opinion this issue has to be fixed elsewhere.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Is it still valid in the current master branch?

**Comment by reduz** [comment]
This works fine, tested it a few weeks ago. You can even use MSAA on it and it looks nicer
