### ISSUE TITLE
render_target_update_mode is reseted when running project

### ISSUE THREAD

**Issue by dpnnl** [godotengine/godot#97019]
### Tested versions

Reproducible in: 4.3, 4.4 dev 1 and 2

### System information

Godot v4.3.stable - Windows 10.0.26120 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 32.0.101.5967) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

It is possible to set the render_target_update_mode of a SubViewport through the editor, and the values are:

- UpdateMode UPDATE_DISABLED = 0 - Do not update the render target.
- UpdateMode UPDATE_ONCE = 1 - Update the render target once, then switch to UPDATE_DISABLED.
- UpdateMode UPDATE_WHEN_VISIBLE = 2 - Update the render target only when it is visible. This is the default value.
- UpdateMode UPDATE_WHEN_PARENT_VISIBLE = 3 - Update the render target only when its parent is visible.
- UpdateMode UPDATE_ALWAYS = 4 - Always update the render target.

However, when setting a differente value (UPDATE_DISABLED, UPDATE_ONCE etc)  it through the editor and, in some cases, even through code, the setting automatically changes to UPDATE_ALWAYS (4), as can be observed in the log.

This issue has been significantly affecting my project, as I want to display items with animations and lights, but in the preview, they are being constantly updated, causing lag. I would like them to be updated only the first time they are displayed

### Steps to reproduce

Set render_target_update_mode to any option except UPDATE_ALWAYS in the editor.

### Minimal reproduction project (MRP)

[viewport-test.zip](https://github.com/user-attachments/files/17003968/viewport-test.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/23729

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by dpnnl** [comment]
I believe this problem has been completely forgotten, since it has existed since Godot 3. Furthermore, it is a behavior of the engine and editor that simply does not work as it should.

**Comment by AThousandShips** [comment]
It hasn't been forgotten, it's just hard to pinpoint how to solve it, it's been engaged with as recently as this year

**Comment by TypeOverride** [comment]
Have run into the same issue. Hoping for a fix on that.

**Comment by AThousandShips** [comment]
See https://github.com/godotengine/godot/issues/23729, this is a duplicate
