### ISSUE TITLE
LightmapGI only works on Forward+ Renderer, but doesn't work on Forward Mobile Renderer and Compability Renderer

### ISSUE THREAD

**Issue by YuWongXX** [godotengine/godot#97017]
### Tested versions
4.3 stable

### Issue description
GIProbe (for dynamic objects, of course) only works on Forward+ and even Compability Renderer, but doesn't work on Forward Mobile Renderer.
The thing is that the document doesn't mention that mobile doesn't support lightprobeGI. And even the lower end Compability Renderer works well. So I assume this is a bug.

Even the lightmap itself, it flashes on Forward Mobile Renderer, but the problem dissapear on Forward+ and Compability Renderer.
![微信图片_20240915062549](https://github.com/user-attachments/assets/a4594dee-2189-489f-99d4-d773b73afd83)

![微信图片_20240915062411](https://github.com/user-attachments/assets/fb1b34d7-60d9-4b85-bbe7-423b5266f27f)

### Minimal reproduction project (MRP)
[GIProbe BUG.zip](https://github.com/user-attachments/files/17003882/GIProbe.BUG.zip)

**Comment by YuWongXX** [comment]
I also find that LightmapGI is overall buggy only in Mobile Renderer

**Comment by clayjohn** [comment]
This is expected. VoxelGi is a Forward+ only feature. 

See the documentation of VoxelGi https://docs.godotengine.org/en/latest/classes/class_voxelgi.html#description

**Comment by AThousandShips** [comment]
This is not about `VoxelGI` but `LigthmapGI` though

**Comment by akien-mga** [comment]
> This is not about `VoxelGI` but `LigthmapGI` though

Confirmed by checking the MRP. The OP got the terms confused though and referred to `GIProbe`, which is the 3.x name of `VoxelGI`. But indeed the MRP is only using `LightmapGI`.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84846.

**Comment by YuWongXX** [comment]
After struggling a few days, I'm sure this is a bug.
