### ISSUE TITLE
Editor theme accent color does not adjust render engine text color, it stays blue

### ISSUE THREAD

**Issue by Cigam-HFden** [godotengine/godot#97023]
### Tested versions

v4.4.dev2.official [97ef3c837]
v4.2.2.stable.official [15073afe3]

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6081) - 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 Threads)

### Issue description

Changing Editor Interface Theme Accent Color, does not change the render engine text color of: Compatibility, Mobile, Forward+

### Steps to reproduce

Editor > Settings > Interface > Theme > Accent Color changed

### Minimal reproduction project (MRP)

![image](https://github.com/user-attachments/assets/c2197e9a-234e-4764-a790-697146f538ee)

**Comment by tetrapod00** [comment]
The renderer uses three different colors depending on which renderer you're using. They became themable with https://github.com/godotengine/godot/pull/93229, so you can change them with a custom editor theme. I'd take a look at passivestar's theme for an example of how to do so: https://github.com/passivestar/godot-minimal-theme

**Comment by Cigam-HFden** [comment]
Ah ok, thank you for the info and links. I guess I should close the issue. I forgot the colors changed dependant on which you used, I always use compatibility. Changing its color is not a huge issue for me, just figured it was a bug, but I guess not. Seems weird with it not matching the accent color, but I guess coloring that for the render engine has some reason.

**Comment by tetrapod00** [comment]
Yeah, I'm not actually sure why the current renderer has different colors. It's not something that changes a lot moment-to-moment while you're using the editor, so I'm not sure why it stands out so much. Maybe it's to make it immediately legible in screenshots what renderer is used? I know that using the wrong renderer is a big source of confusion, support questions, and bug reports.

**Comment by Cigam-HFden** [comment]
Interesting, thank you for the link and answer on that. I will close the ticket then. Have a good one. Cheers!
