### ISSUE TITLE
Gltf nodes using "matrix" instead of TRS have incorrect bone rest

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#97022]
### Tested versions

- Reproducible in 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 Threads)

### Issue description

A bug in this if statement in gltf_document.cpp causes nodes with matrix not not assign the correct bone rest transform.

```cpp
		if (n.has("matrix")) {
			node->transform = _arr_to_xform(n["matrix"]);
		} else {
			if (n.has("translation")) {
				node->set_position(_arr_to_vec3(n["translation"]));
			}
			if (n.has("rotation")) {
				node->set_rotation(_arr_to_quaternion(n["rotation"]));
			}
			if (n.has("scale")) {
				node->set_scale(_arr_to_vec3(n["scale"]));
			}

			Transform3D godot_rest_transform;
			godot_rest_transform.basis.set_quaternion_scale(node->transform.basis.get_rotation_quaternion(), node->transform.basis.get_scale());
			godot_rest_transform.origin = node->transform.origin;
			node->set_additional_data("GODOT_rest_transform", godot_rest_transform);
		}
```

Also of note, skin_tool.cpp blindly uses the GODOT_rest_transform withouot checking if it exists.
```
			skeleton->add_bone(node->get_name());
			Transform3D rest_transform = node->get_additional_data("GODOT_rest_transform");
			skeleton->set_bone_rest(bone_index, rest_transform);
			skeleton->set_bone_pose_position(bone_index, node->transform.origin);
			skeleton->set_bone_pose_rotation(bone_index, node->transform.basis.get_rotation_quaternion());
			skeleton->set_bone_pose_scale(bone_index, node->transform.basis.get_scale());
```

This is where the identity transform is coming from.

Originally filed by @fire at V-Sekai/godot-vrm#105

### Steps to reproduce

1. Rename the attached .vrm to instead be .glb extension.
2. Import to Godot
3. Double-click the glb to open the advanced importer. all bones have 0,0,0 position in a ball.
4. Reimport the scene with the glb in it. the bones are reset to rest.
5. Click on bones in the Skeleton3D and expand bone rest. the matrix is identity.

### Minimal reproduction project (MRP)

https://github.com/user-attachments/files/16056290/viverse_avatar_model_101119.vrm.zip

**Comment by fire** [comment]
Will need to check if FBXDocument has the same bug

**Comment by fire** [comment]
I moved the statement out in https://github.com/godotengine/godot/pull/97938
