### ISSUE TITLE
Shortcut `matches_event` ignores `pressed` flag

### ISSUE THREAD

**Issue by Jowan-Spooner** [godotengine/godot#97048]
### Tested versions

- Reproducable in godot 4.3.0

### System information

Windows 10

### Issue description

When checking whether a shortcut is pressed by calling `shortcut.matches_event()` in `_input()`, it will always fire twice for InputEventKey's (a very common shorcut event type). 

I assume that godot control nodes do some additional checking or don't use matches_event in the first place. This feels like it makes the method a bit useless. If this is intended it should at LEAST be included in the documentation I think.

Thanks :)

### Steps to reproduce

Put this code in a simple scene:

```gdscript
extends Node

var shortcut := Shortcut.new()


func _ready() -> void:
	var event := InputEventKey.new()
	event.keycode = KEY_A
	shortcut.events.append(event)


func _input(event:InputEvent) -> void:
	if shortcut.matches_event(event):
		print(event)
```

Play the scene, press `A`. The result is this:
```
InputEventKey: keycode=65 (A), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=65 (A), mods=none, physical=false, location=unspecified, pressed=false, echo=false
```

### Minimal reproduction project (MRP)

[mrp-shortcutmatchevent.zip](https://github.com/user-attachments/files/17006508/mrp-shortcutmatchevent.zip)

**Comment by AThousandShips** [comment]
I'd say this is expected, there are *many* cases where you want to match to a *released* event, the only option here IMO would be to add a second argument which forces it to be pressed, but you can very easily work around this without the issues created by this:
```gdscript
func _input(event:InputEvent) -> void:
	if event.is_pressed() and shortcut.matches_event(event):
		print(event)
```

Also in your example it would be surprising if the event would be matched with pressed as the event you add *doesn't* have `pressed == true`

**Comment by Jowan-Spooner** [comment]
Yes, maybe my example was confusing as it is checking for a released event, I did it like this to make the code as short as possible. In my example I would of course expect it to ONLY match the event when pressed is false. I never meant to say it should always match on `pressed == true`, just that it should never match BOTH.

Of course there are just as many cases where you'd want to match a released event but then you would have pressed as false in the InputEventKey that you've setup (like in my example). Having a pressed flag on InputEventKey and then having to check it again in code seems annoying and counter intuitive (even more so if you set it up through the UI which I skipped in my example for simplicity).

Maybe this is intended (feels strange to me, but what do I know) but I could not find any mention of it anywhere, so at the very least it should be documented.

`InputEvent.is_action()` has an optional second argument `exact_match`, maybe something like this could be introduced to avoid compatibility breaking, if the current behaviour is decided to be intentional/desired.

**Comment by AThousandShips** [comment]
`exact_match` doesn't check that, you need `is_action_pressed/released`, but for your example just use:
```gdscript
func _input(event:InputEvent) -> void:
	if not event.is_pressed() and shortcut.matches_event(event):
		print(event)
```

But a shortcut mixing pressed and released doesn't really make sense so it wouldn't be relevant to be able to check that

**Comment by Jowan-Spooner** [comment]
I do understand that this is easy to workaround (I already did so in my project). Maybe I should've mentioned it above. This is not a critical bug. But something can be easy to work around and still be a bug, right? 

What I don't understand is why this would be intended and if so, never mentioned. It does absolutely not feel intuitive to me to set up an action that has a pressed flag (likely to differentiate between the pressed and released moments) and then ignore that when evaluating a shortcut (which to me the `matches_event` method seems to be intended for). I'd never want a shortcut to trigger twice. Buttons cannot even do this at all (react to both pressed and released) and shortcuts are most likely used on button-like elements.

> exact_match doesn't check that, you need is_action_pressed/released, but for your example just use:

Sure, it was just an idea to make this (imo more correct behaviour) optional to avoid compatibility breaking if this is a concern. I understand that exact_match in the method I mentioned works a bit differently.

> But a shortcut mixing pressed and released doesn't really make sense so it wouldn't be relevant to be able to check that

Not sure what you mean here. Why would it not be relevant if unless I do this the shortcut is triggered twice. Why would I want it to trigger twice?

Again, I don't care much if this is fixed soon, it's easy to workaround and I had already implemented the workaround before I posted this. I still though mentioning this confusing behaviour here would be useful.

**Comment by AThousandShips** [comment]
> But something can be easy to work around and still be a bug, right?

I don't think this is a bug, I'd say that this should be documented, and you can open a [proposal](https://github.com/godotengine/godot-proposals) to change the behavior or add a new parameter to control this

But the `InputEvent.is_match` method *also* doesn't check for matching `pressed`, so this is the "standard"

But regardless this would break compatibility if we changed it, so it's not simple to just do, and I don't think it's a bug or valid to "fix" it

So I'll leave this open to look at documenting it, and if you want to change this behavior please open a proposal to do so!

**Comment by Jowan-Spooner** [comment]
Alright, thanks! I will make a proposal then. I get this is hard to adjust now as it's compatibility breaking and it might not be worth it. Interesting to see that other methods do this too. I assume it must have it's use-cases. 

Thank you for your time.

**Comment by AThousandShips** [comment]
So to clarify what I think should be documented here:
* The `Shortcut.matches_event` method should mention `InputEvent.is_match` (though this *is* an implementation detail it should be mentioned even if we choose to change how it is implemented to add further specificity)
* The `InputEvent.is_match` should clarify that it *doesn't* care about `is_pressed()`, `is_released()`, `is_echo()`, etc.

This is relatively simple to do so this is a good first contribution for anyone interested, the files to edit are under `doc/classes` here in this repo (**not** in godot-docs)

**Comment by SkylerGoh-dev** [comment]
Hi, I would like to try contributing to this!

**Comment by AThousandShips** [comment]
Would be great! Look [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#doc-updating-the-class-reference) and [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html)
