### ISSUE TITLE
Allow InputEventJoypadMotion to have an Invalid Axis without error messages.

### ISSUE THREAD

**Issue by JulianHeuser** [godotengine/godot#97046]
### Tested versions

- Reproducable in v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.stable - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (RADV NAVI23) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

I'm implementing optional SteamInput support, so I need a way to unbind all joystick controls without removing them, since I rely on the index to be kept in place.

For InputEventJoypadButton, I can set the button_index to JOY_BUTTON_INVALID (-1), and this effectively unbinds the input event. I can do the same for InputEventJoypadMotion by setting event.axis to JOY_AXIS_INVALID (-1), but this produces the following error:
```
E 0:00:00:0604   ControlsManager.gd:243 @ _ready(): Condition "p_axis < JoyAxis::LEFT_X || p_axis > JoyAxis::MAX" is true.
  <C++ Source>   core/input/input_event.cpp:1019 @ set_axis()
  <Stack Trace>  ControlsManager.gd:243 @ _ready()
```

Removing this error in this case would help. I would also suggest adding a check for if button_index is between JOY_BUTTON_INVALID and JOY_BUTTON_MAX, to make behavior between the two more consistent.

### Steps to reproduce

Create and add this script to a node in a new project:

```
func _ready() -> void:
	var event = InputMap.action_get_events("ui_left")[2]
	event.axis = JOY_AXIS_INVALID
```

Run the project and check the errors tab in the debugger

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17006379/test.zip)

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
