### ISSUE TITLE
[MP] Wrong validation in creating client or server in WebRTCMultiplayerPeer and adding as peer

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#97043]
### Tested versions

4.3 Stable

### System information

Windows 11

### Issue description

It seems the validation in the start of the method `add_peer `in `webrtc_multiplayer_peer.cpp` doing the inverse of what is supposed to validate

```c
	ERR_FAIL_COND_V(network_mode == MODE_CLIENT && p_peer_id != 1, ERR_INVALID_PARAMETER);
	ERR_FAIL_COND_V(network_mode == MODE_SERVER && p_peer_id == 1, ERR_INVALID_PARAMETER);
```
As per the documentation here 
https://docs.godotengine.org/en/stable/classes/class_webrtcmultiplayerpeer.html#class-webrtcmultiplayerpeer
Server should have id of 1 and client between 2 to 2**31

I may be totally wrong, but it seems to me it is doing the opposite

### Steps to reproduce

Create a `WebRTCPeerConnection `/ `WebRTCLibPeerConnection `add it as peer to the `WebRTCMultiplayerPeer`, it fails the above logic. As it does not allow to create a server with id of 1 or client with id > 1

### Minimal reproduction project (MRP)

N.A

**Comment by blam23** [comment]
Looks correct to me, `network_mode` here refers to the `NetworkMode` of the _current_ peer, not the peer being added (it's not prefixed with `p_` for parameter).

So:
- adding a peer that isn't a server (id != 1) to a CLIENT isn't valid either (only mesh connections can connect to each other)
- adding a peer that is a server (id  ==1) to a peer that is already a SERVER isn't valid

**Comment by AThousandShips** [comment]
This explanation is indeed correct 

Closing as per the above, please make sure something doesn't actually work when looking at code that seems weird, especially for something that would so obviously fail if it was wrong

**Comment by tokengamedev** [comment]
Here is the code for creation of a single server / client
```gdscript
func create_chat_session():
	chat_peer = WebRTCMultiplayerPeer.new()
	var error = chat_peer.create_server()
	if error != OK:
		print("Error Creating Chat", error)
		return

	multiplayer.multiplayer_peer = chat_peer
	var new_chat_peer = ChatPeer.new()
	chat_peer.add_peer(new_chat_peer.peer, 2, 2)
	print("Created:", multiplayer.get_peers()) # returns []
	print("Created:", chat_peer.get_peers()) # returns { 2: { "connection": WebRTCLibPeerConnection, "connected": false, "channels": [WebRTCLibDataChannel, WebRTCLibDataChannel, WebRTCLibDataChannel] } }


func connect_chat_session ():
	chat_peer = WebRTCMultiplayerPeer.new()

	var error = chat_peer.create_client(2)
	if error != OK:
		print("Error Joining Chat", error)
		return

	multiplayer.multiplayer_peer = chat_peer
	var new_chat_peer = ChatPeer.new()
	chat_peer.add_peer(new_chat_peer.peer, 1, 2)

	print("Created:", multiplayer.get_peers()) # returns []
	print("Created:", chat_peer.get_peers()) # returns Created:{ 1: { "connection": WebRTCLibPeerConnection, "connected": false, "channels": [WebRTCLibDataChannel, WebRTCLibDataChannel, WebRTCLibDataChannel] } }

```
I am not sure it is the right approach. I tried to search through demos but I could not find projects using WebRTCMultiplayerPeer.

my assumption was as soon as you create a Server it will create an instance of WebRTCPeerConnection and setup Data channels accordingly, which it does not do like other MultiplayerPeers. 
So, you have to add a peer to act as a server, but there are no signal callbacks from `multiplayer` instance. 

I will drop this approach rather use the given way for RTC which is non multiplayerAPI compliant.
