### ISSUE TITLE
[3.0] Scene with a large amount of nodes takes a long time to save

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#9704]
**Operating system or device - Godot version:**
Windows 10 - [Godot-Windows-x86_64-2017-07-18.0962871](https://bintray.com/calinou/godot/download_file?file_path=Godot-Windows-x86_64-2017-07-18.0962871.zip)

**Issue description:**
Making a scene with nothing but a bunch of nodes with an empty script in them is enough to freeze up the editor every time the script is saved (or autosaved), the freezing happens with both plain nodes and instanced scenes and even if the script had no changes. 
I set autosave to 10 seconds so the editor freezes every 10 seconds even if I don't have the Scripts tab open, making it pretty unusable in large scenes unless I close either the scene or the script file.
The test scene has 500 nodes which freeze up the editor for about 4 seconds in my PC, making it 1000 nodes freezes for 40 seconds.
Disabling "Auto Reload and Parse Scripts on Save" in Editor Settings->Text Editor->Files stops the freezing.

**Link to minimal example project:**
[Editor test.zip](https://github.com/godotengine/godot/files/1157032/Editor.test.zip)

**Comment by reduz** [comment]
I've seen this before, though not sure why it might be. Could be a good
idea to profile it at some point

**Comment by Zylann** [comment]
Another occurrence of https://github.com/godotengine/godot/issues/5289 ?

**Comment by reduz** [comment]
The reason this happens is because scenes are scanned to find stuff when saving, both in the editor and the save system.. this is not really bug and it could be optimized. 

It's not really a bug but an enhacement (optimization) that would be nice to do. Anyone up for debugging the reason of the slowness?

**Comment by hpvb** [comment]
I'll look at this.

**Comment by reduz** [comment]
Fixed, this was an entirely different problem and the fault was the scripts.
