### ISSUE TITLE
Add auto code format for gdscript

### ISSUE THREAD

**Issue by Saitama-web** [godotengine/godot#97047]
### Tested versions

4.4 dev 2

### System information

Windows 11

### Issue description

add auto code format for gdscript

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Consolidating in:
* https://github.com/godotengine/godot-proposals/issues/3630

Please also in the future make sure to fill things in properly
