### ISSUE TITLE
ProjectSettings.save_custom("override.cfg") raises an error

### ISSUE THREAD

**Issue by xorblo-doitus** [godotengine/godot#97050]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]
- Not reproducible in: v4.2.2.stable.official [15073afe3], v4.2.stable.official [46dc27791]

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.5612) - 13th Gen Intel(R) Core(TM) i7-13620H (16 Threads)

### Issue description

The following code used to work fine:
```gdscript
ProjectSettings.save_custom("override.cfg")
```

It now raises the following error:
```
E 0:00:02:0638   run_me.gd:5 @ _on_pressed(): Condition "dir.is_null()" is true. Returning: false
  <Source C++>   core/config/project_settings.cpp:986 @ _csproj_exists()
  <Pile des appels>run_me.gd:5 @ _on_pressed()
```

(But project's settings are still written to the file, it only pollutes the debugger's output)

### Steps to reproduce

MRP's main scene has a button that calls `ProjectSettings.save_custom("override.cfg")`.

### Minimal reproduction project (MRP)

[save_custom_to_override_cfg.zip](https://github.com/user-attachments/files/17006528/save_custom_to_override_cfg.zip)

**Comment by KoBeWi** [comment]
Not sure what changed to cause this error now, but you should be using `res://override.cfg`.

**Comment by xorblo-doitus** [comment]
> you should be using `res://override.cfg`.

Oh, thank you. I didn't think it would accept a path. It might be good to rename the parameter from `file` to `path` or `file_path`.

**Comment by Calinou** [comment]
Can you try following the same steps on 4.3 dev/beta/RCs to determine when the regression started? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.3/).

**Comment by xorblo-doitus** [comment]
It started in v4.3.dev6.official [89850d553]
It was _probably_ introduced by 4324d01c8e7d53718d0f2232d781098650c75f05
