### ISSUE TITLE
`interface/editor/editor_screen` setting has no effect once window position is remembered

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#97051]
### Tested versions

4.4 dev2

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

There is `interface/editor/editor_screen` editor setting, which defines where the editor should appear at startup. After #76085, the editor will use the last window position (including screen), making the setting effectively useless. It has effect only when a project is opened for the first time.

Maybe we should just remove this setting now.

### Steps to reproduce

1. Change `interface/editor/editor_screen` to Screen 1
2. Restart the editor while it is on screen 2
3. It starts on screen 2

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
We can either remove the setting, or change it to default to "Auto" that would be remembering the last position, and the other options should be treated as overrides.

**Comment by bits-by-brandon** [comment]
I like the idea of an "Auto" setting. Perhaps we can merge in the separate `interface/editor/remember_window_size_and_position` setting into this "Auto" option?
Also some alternatives names for "Auto"
- Persist
- Remember

**Comment by bits-by-brandon** [comment]
I have a really rough PR of what this might look like. https://github.com/godotengine/godot/pull/97333/files
I'm a total C++ beginner though, so it's not entirely functional yet 😅
