### ISSUE TITLE
[4.4 dev2] ResourceLoader: load() and load_threaded_request() causes hang when called from a non-main thread in certain cases

### ISSUE THREAD

**Issue by raccoon-path** [godotengine/godot#97052]
### Tested versions

- Reproducible: v4.4.dev2.official [97ef3c837]
- Not reproducible: v4.4.dev1 and earlier

### System information

Vulkan 1.3.280 - Forward+ INVIDIA GeForce RTX 4070, AMD Ryzen 7 2700 3.20 GHz, Windows 10 Pro 22H2

### Issue description

When calling load() or load_threaded_request() methods from a non-main thread, it sometimes hangs without throwing an error in certain cases in version 4.4-dev2, whereas it works fine in 4.4-dev1.

It's possible that a deadlock(?) occurs in certain cases during the resource loading and caching process, depending on the loading sequence and combination of resources in the scene(?)
__P.S.__ Based on my observations, if a scene contains a 3D-GUI (created following the 'GUI in 3D' tutorial), the probability of hanging in __4.4-dev2__ is close to 100%. Additionally, if a scene contains complex CSG geometry (with a large number of combiners), hanging also occurs, but rarely and random. In __4.4-dev1__, I did not experience a single hang during the entire testing period.

### Steps to reproduce

- Open project in __4.4-dev2__. Run Level1, Level2 directly from editor (Always OK). Now, play and try to load levels from the main menu. The Level1 button works, Level2 loading hangs, Level2 (load_threaded_request) works. Transition between Level1 и Level2 - hangs (because loading initiated from non-main thread)
- Open the attached project in __4.4-dev1__. Run the scenes by pressing buttons in main menu. The Level1, Level2, and Level2 (load_threaded_request) buttons work as expected, all loading fine and transitions between locations work correctly.

### Minimal reproduction project (MRP)

[240915_MRP_loadbug.zip](https://github.com/user-attachments/files/17006981/240915_MRP_loadbug.zip)

**Comment by AThousandShips** [comment]
This project is very much not minimal, please upload a minimal project with everything unnecessary stripped

**Comment by RandomShaper** [comment]
#96904 fixed this.

**Comment by raccoon-path** [comment]
I can confirm, v4.4.dev.custom_build #97077.
