### ISSUE TITLE
[4.4-dev] Metal render incorrectly renders label font colors when using LCD Subpixel AA

### ISSUE THREAD

**Issue by cridenour** [godotengine/godot#97056]
### Tested versions

- Reproducible in 4.4-dev 1 and 2, on macOS and iOS

### System information

macOS & iOS - Metal (Mobile & Forward+) v4.4.dev2.official [97ef3c837]

### Issue description

Using the new renderer, labels are using a black font color for default state and only change color in hover and selected states. 

Applies to both Mobile and Forward+, on macOS and iOS.

Metal (mobile):
<img width="480" alt="Screenshot 2024-09-15 at 4 00 47 PM" src="https://github.com/user-attachments/assets/583369fa-4c97-4327-a81a-58d4c2ebb81d">
Vulkan (mobile):
<img width="481" alt="Screenshot 2024-09-15 at 4 00 31 PM" src="https://github.com/user-attachments/assets/1468805c-3d02-443a-ae01-0a64c207097f">

### Steps to reproduce

1. Load 4.4-dev1 or later on macOS using default rendering devices. 

### Minimal reproduction project (MRP)

Any project.

**Comment by bruvzg** [comment]
Do you have font LCD antialiasing enabled?

**Comment by cridenour** [comment]
Ah yes. Considering I opened #93606 I probably should have thought to check :joy: 

Works OK on grayscale both in editor and in game.

**Comment by stuartcarnie** [comment]
#97217 closes this issue
