### ISSUE TITLE
Pressing CTRL+X in visual shader editor deletes node in tree rather than cutting out node in visual editor

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#97064]
### Tested versions

- v4.3.stable.mono.official [77dcf97d8]
- v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 32.0.15.5599) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When I press CTRL+X to cut a node from the visual shader editor and put it into the clipboard instead the currently selected node in the scene tree is cut.

https://github.com/user-attachments/assets/bacd561f-c03b-4ec3-8b5f-efaca70ca8dc

### Steps to reproduce

- Create or open any visual shader, add any node you want to cut.
- Select a node in the scene tree that is not the root. 
- In your visual shader, select a node and press CTRL+X to cut it out.
- Instead of the visual shader node the currently selected node from the scene is cut out.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/92776

This is likely due to context issues with the shader editor
