### ISSUE TITLE
Can't drag and drop other formats than obj into a meshinstance in the inspector

### ISSUE THREAD

**Issue by rubberduck9999** [godotengine/godot#97085]
### Tested versions

4.3 stable

### System information

Windows 10

### Issue description

Trying to drag and drop other formats than obj into a meshinstance in the inspector doesn't work and shows the :no_entry_sign: symbol instead. I can add these all by dragging them directly into the viewport, but not into an existing mesh instance

I encountered this issue already multiple times in the past and feels a bit annoying

https://github.com/user-attachments/assets/c382a920-9570-4651-8e3f-057bb128f9f0

### Steps to reproduce

easy, try to put other file formats that obj into a mesh instance, it won't work

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test with, it can be a bit annoying to have to source different file formats for this so it'd help

**Comment by AThousandShips** [comment]
However this is to be expected as those aren't meshes, they are scenes, so why would you be able to drop a scene in a `MeshInstance3D`? It accepts meshes, not scenes

**Comment by rubberduck9999** [comment]
yeah, you are right, it is the problem, that these are scenes in godot, even though they are just .obj, gltf, .fbx etc files. it just feels weird

**Comment by AThousandShips** [comment]
Those types are imported as scenes though (except `obj`, by default) but that makes sense, they support complex scene stuff, you can't import a complex scene as a mesh

**Comment by rubberduck9999** [comment]
Maybe it can be closed as a duplicate, it is there in form of an improvement proposal, so that 3D model files could be imported as mesh too. I think though it should also be documented, what data or information may get lost, or at least what is different when importing them as a mesh

**Comment by AThousandShips** [comment]
It is documented, right [here](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_3d_scenes/available_formats.html) and in the interface saying it imports it as a scene, it says so explicitly here:
> Godot works with scenes. This means that the entire scene being worked on in your favorite 3D modeling software will be transferred as close as possible.

Closing and consolidating in that proposal, thank you for your report
