### ISSUE TITLE
Files suddenly not opening at all

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9709]
**Operating system or device - Godot version:**
Windows 10
Godot 3.0 pre-alpha

**Issue description:**
For whatever reason, when I fast-forwarded to master in my fork, files no longer opened properly. Every call to a File's .open method returns zero now. I've already tried it with a variety of file types and file modes.

**Steps to reproduce:**
`var file = File.new()`
`print(file.open("user://save_game.dat", file.WRITE))`

Output:
`0`

**Comment by BastiaanOlij** [comment]
Could be totally unrelated but there were a few changes to the projects file format so your settings may not be listened to. If that results in it looking in the wrong location to open your files...

If that is the case, edit project settings to make sure the correct entries are added and then edit the project.godot file to clean up any old settings that are now unused. If not, then I'm barking up the wrong tree :)

**Comment by vnen** [comment]
AFAIK `File.open()` always returned 0 on success (it is equivalent to the `OK` constant).

**Comment by willnationsdev** [comment]
Oh wow...that's right. I just completely forgot that the if statements should be comparing against `OK` instead of `if file.open(...):`. Nevermind me. I just had a massive brainfart all evening.
