### ISSUE TITLE
OS X 10.10.1 current head (be4e40e90a) segfault

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#971]
Hi. I've got system error twice. First was segfault when I triend to open attached project (it's pong from tutorial, made some time ago, maybe .scn is not compatible?), but project opened. Next I've tested that pong and closed game - there was second segfault.

Project: http://youkai.pl/godot/pong.tgz
Error log: http://pastebin.com/k6UCqmUb

**Comment by akien-mga** [comment]
Due to the age of the issue and lack of further comments I'll assume that it's not reproducible anymore, so archiving.
