### ISSUE TITLE
Crash starting up on OSX from AudioDriverOSX::init()

### ISSUE THREAD

**Issue by ezabba** [godotengine/godot#9710]
macOS Sierra 10.12.5 - Godot 2.1.3

This is a replica of this closed issue https://github.com/godotengine/godot/issues/45
Basically what happens is that Godot crashes if I try to open it.
Sadly there isn't more to say, it simply doesn't open at all, no messages, no alerts, just the icon appears in the dock and disappear after a couple of seconds.

this is the crash log:
[Godot.txt](https://github.com/godotengine/godot/files/1158784/Godot.txt)

Thanks

**Comment by akien-mga** [comment]
Is there anything worth noting about your audio setup on OSX? (drivers, connected audio output devices, etc.)

**Comment by ezabba** [comment]
I have an external audio unit called UX1 from Line6

**Comment by akien-mga** [comment]
There were improvements made to the audio init on OSX a couple days ago by @marcelofg55 (#9668) in the master branch, do you think you could build Godot from source to see if it works better?

**Comment by akien-mga** [comment]
Alternatively you could try Calinou's macOS build from yesterday, which should contain that fix: https://bintray.com/calinou/godot/editor/_latestVersion#files

**Comment by ezabba** [comment]
Since I have no experience in compiling anything I will give a try to the yesterday binaries. If it doesn't work I will think about the source compilation, are there any instructions to follow for a newbie?

**Comment by ezabba** [comment]
The @Calinou build seems to work, the project selection window opens up.
I will try this for a couple of days just to see how it behave because the 2.1.3 version worked for some days and then stopped. and the UX1 was already there.

**Comment by ezabba** [comment]
This build is still working, it opens and basically works, but this is a version 3 alpha and pretty unstable, obviously, so I think I must wait for a new release of the version 2 with the fix in to have a stable version to work with.
