### ISSUE TITLE
Animation Bezier Editor only uses half the view

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#97108]
### Tested versions

Master - Regression in master caused by 86fc8ef99b6b3befb7ac604ece31354f0244892f

### System information

Godot v4.4.dev (86fc8ef99) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4683) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Bezier view only uses half the view. Regression caused by https://github.com/godotengine/godot/pull/96902

https://github.com/user-attachments/assets/b0d39a06-3786-47ba-b3a5-d73b866975de

### Steps to reproduce

Make an animation with bezier keys and enter the bezier view

### Minimal reproduction project (MRP)

NA

**Comment by WhalesState** [comment]
@SaracenOne `scroll->set_v_size_flags(SIZE_EXPAND_FILL);` was replaced with `scroll->set_anchors_and_offsets_preset(PRESET_FULL_RECT);` while the scroll is a child of a container, so reverting this line back should fix the issue.

**Comment by SaracenOne** [comment]
Good catch, sorry about that 👍
