### ISSUE TITLE
Error: _queue_monitor_update: Parameter "get_space()" is null. when deleting an Area3D affecting a SoftBody3D

### ISSUE THREAD

**Issue by LucidTaZ** [godotengine/godot#97116]
### Tested versions

Reproducible in 4.3-stable

Not reproducible in 4.2.2-stable

### System information

Godot v4.3.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M2 Max - Apple M2 Max (12 Threads)

### Issue description

When deleting an Area3D that blows wind on a SoftBody3D, the below error is printed:

```
E 0:00:01:0112   _queue_monitor_update: Parameter "get_space()" is null.
  <C++ Source>   servers/physics_3d/godot_area_3d.cpp:214 @ _queue_monitor_update()
```

The Area3D is deleted through a `queue_free()` call.

### Steps to reproduce

Scene contains:
- SoftBody3D with a mesh (QuadMesh works)
- Area3D with a CollisionShape3D
- Both can be at default settings (layer, mask, etc.) as long as the SoftBody3D is inside the Area
- I found this issue in my Area3D's that cause wind to blow on the SoftBody3D, although it also happens when the wind parameters are left on the defaults

### Minimal reproduction project (MRP)

[softbody3d-wind-issue-reproduction.zip](https://github.com/user-attachments/files/17028783/softbody3d-wind-issue-reproduction.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #81809 as the culprit, @Rindbee

![image](https://github.com/user-attachments/assets/33614176-4f15-46ab-b3b7-5735449dfd87)

**Comment by Rindbee** [comment]
It seems that the `soft_body` was forgotten when adding the space check code in `GodotArea3D::remove_*_from_query()`.
