### ISSUE TITLE
[4.4] Can't compile template_release for Windows with mono enabled

### ISSUE THREAD

**Issue by Armynator** [godotengine/godot#97114]
### Tested versions

4.4 mono master (https://github.com/godotengine/godot/commit/02b16d2f544e323b7b7f57e6e992b0b8e5d8b954)

### System information

Godot v4.4.dev.mono - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (nvidia; 535.183.01) - Intel(R) Core(TM) i9-14900K (32 Threads)

### Issue description

Looks like https://github.com/godotengine/godot/pull/88803 broke release template compilation for Windows when the mono module is enabled.

Tested building on Linux Mint 22 (based on Ubuntu 24.04), Ubuntu Server 22.04 and Windows 10.
template_release with platform=windows always fails, building template_release for Linux works fine.
Editor is building fine for Windows and Linux.

After reverting https://github.com/godotengine/godot/pull/88803 locally, building works again as expected.

### Steps to reproduce

1. run this command: scons p=windows arch=x86_64 module_mono_enabled=yes target=template_release
2. notice error message

![grafik](https://github.com/user-attachments/assets/789e2baf-cfb3-4838-8afe-34f0d338abf6)

### Minimal reproduction project (MRP)

no MRP, clone latest master and try building

**Comment by raulsntos** [comment]
My bad, I only tested building the templates for Android and Linux where `char_t = char`. It's only on Windows that `char_t = char16_t` so I missed this.

It looks like the [`coreclr_initialize`](https://github.com/dotnet/runtime/blob/3992788b124867a8ce1d762ea2d6536b8a98f08a/src/coreclr/hosts/inc/coreclrhost.h#L41-L48) and [`coreclr_create_delegate`](https://github.com/dotnet/runtime/blob/3992788b124867a8ce1d762ea2d6536b8a98f08a/src/coreclr/hosts/inc/coreclrhost.h#L112-L118) always use `char` on every platform (unlike the hostfxr APIs that use `char_t`).
