### ISSUE TITLE
Dragging and dropping files from 7zip into a Godot project fails.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#97128]
### Tested versions

5d62e12fcbd46034dd06f91c2b20bdd366f3a0c9

### System information

Windows 11

### Issue description

Windows and third-party software specific issue:
Dragging and dropping files from an archive with 7zip currently does not work. It appears that 7zip will create a copy of the files being dragged from the archive in the Windows temp folder, and delete it once the action has finished. It seems the APIs being used to give drag and drop awareness on Windows are only responsive after 7zip deletes this temp file, resulting in an error.

While not a huge issue, its a minor usability snag and raises the question if there are alternative APIs we could or should be using on Win32 which are more compatible with the behaviour of software like 7zip. Certain other applications do appear to allow dragging files from 7zip on Windows, so it may be worth researching.

My interest in this stems from my usual concern of the beginner user experience; I imagine a lot of new developers might start learning by opening a zip file full of starter graphics/sounds/whatever, and it would be nice to make this process a bit more elegant.

### Steps to reproduce

- Create a new project
- Get any .zip file.
- Use 7zip to drag the contents of the .zip file into the Godot editor application.
- Observe the error which references the /temp/ path which not longer exists.

### Minimal reproduction project (MRP)

N/A

**Comment by Maran23** [comment]
Note that dragging something from inside the `.zip` from the normal Windows Explorer also does not work, but there is at least no error.
