### ISSUE TITLE
TabContainer tabs move on select, but TabBar tabs do not [Regression]

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#97133]
### Tested versions

- Reproducible in https://github.com/godotengine/godot/commit/129332e3b99eb8249da6ce7e52d676dd7f2a5c5a (Regression from #82468)
- Not reproducible in 35da70f953f6eeba6ba7b13795029d7a134a61fd

### System information

Arch Linux, kernel 6.10.9-arch1-2

### Issue description

See video:

First element is `TabBar`, second element is `TabContainer`

https://github.com/user-attachments/assets/88ca62dd-e064-4bd5-bf79-f1f02a82e0cf

Tentative workaround in `NOTIFICATION_RESIZED`:

```diff
diff --git a/scene/gui/tab_bar.cpp b/scene/gui/tab_bar.cpp
index 90a6626b74..28bd03ff06 100644
--- a/scene/gui/tab_bar.cpp
+++ b/scene/gui/tab_bar.cpp
@@ -381,7 +381,6 @@ void TabBar::_notification(int p_what) {
                        int max_old = max_drawn_tab;
 
                        _update_cache();
-                       _ensure_no_over_offset();
 
                        if (scroll_to_selected && (offset != ofs_old || max_drawn_tab != max_old)) {
                                ensure_tab_visible(current);
```

### Steps to reproduce

- Launch MRP
- press right arrow
- select a tab

### Minimal reproduction project (MRP)

[test_tab_container.zip](https://github.com/user-attachments/files/17037666/test_tab_container.zip)

**Comment by akien-mga** [comment]
CC @kitbdev
