### ISSUE TITLE
ERROR: Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#97138]
### Tested versions

Does not happen in 4.3 stable
Does happen in 4.4-dev (commit 48403b5358c11ffff702da82c48464db8c536ee3)

### System information

Godot v4.4.dev (48403b535) - Ubuntu 22.04.5 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

Developing a plugin. Trying to save any changes to my gdscript files causes the error:

`ERROR: Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE`

This does not happen in 4.3 stable.

### Steps to reproduce

Try the MRP. Very simple addon. See notes in `bug_test.gd`

Sample output on run:
```
Godot Engine v4.4.dev.custom_build.48403b535 (2024-09-16 23:05:57 UTC) - https://godotengine.org
Vulkan 1.3.242 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 2060

YES:true
bug ready!
1. ERROR: Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE
   Any change here produces that error ONCE (so far).
2. After that, no changes in the code are reflected in the execution of this script.
3. Restarting the project gets you back to work, but goto 2.
YES:false <-- clicked the fail control a few times
YES:true
YES:false
YES:true <-- after this made a code change and used Ctrl+S

ERROR: Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE
   at: reload (modules/gdscript/gdscript.cpp:747)
```

### Minimal reproduction project (MRP)

[MRP](https://gitlab.com/godot-things1/already-in-use-bug#)

**Comment by donn-xx** [comment]
MRP added.

**Comment by KoBeWi** [comment]
Changing this line to `reload(true)` (similar to what #92177 did)
https://github.com/godotengine/godot/blob/84dcdde9088d512efebb0033fb881d8f7fd9c107/core/object/script_language.cpp#L194
fixes it. But again, it's suspicious.

**Comment by ryevdokimov** [comment]
Bisected to: https://github.com/godotengine/godot/commit/9fd431f078d7560835da2642c9efe9e235618fe9

@Hilderin
