### ISSUE TITLE
FileDialog returns path with lowercase drive

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#97147]
### Tested versions

4.4 dev2
Works correctly in 4.3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you select a file in FileDialog, the path provided by `file_selected` signal will have drive letter in lowercase.

Uppercase:
![image](https://github.com/user-attachments/assets/0f1c2989-8106-4930-a98e-3d4efe7bc092)

Also uppercase:
![image](https://github.com/user-attachments/assets/932915fa-748c-4a67-bf36-66a3489e8e60)

Lowercase (printed result):
![image](https://github.com/user-attachments/assets/5edf2ce3-5613-40c4-b7a9-993a708db1e5)

### Steps to reproduce

1. Add FileDialog
2. Connect `file_selected` signal to some method that prints `path`
3. Run and select file

### Minimal reproduction project (MRP)

N/A

**Comment by Giganzo** [comment]
> Lowercase (printed result): ![image](https://private-user-images.githubusercontent.com/2223172/368612923-5edf2ce3-5613-40c4-b7a9-993a708db1e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzIxNDYsIm5iZiI6MTcyNjY3MTg0NiwicGF0aCI6Ii8yMjIzMTcyLzM2ODYxMjkyMy01ZWRmMmNlMy01NjEzLTQwYzQtYjdhOS05OTNhNzA4ZGIxZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMTUwNDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmE2MmMxYjdlM2I3ZTY0ODBjMGRmNWMxNWJlNWYyZjE4ZjBjMWM1NzkyZTY3YzU2ZTNjMmFiMGJiZmRmMjEyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dSYIZ8nYvrbWQ0xkjmIo1TaQcdTDiOobptGVXz5MPdY)

Looks like C is uppercase in the image?

**Comment by KoBeWi** [comment]
Ok for whatever reason I only have this bug in my project, but I confirmed that it's fixed on master, so whatever.

**Comment by KoBeWi** [comment]
Update: this is NOT fixed. The issue only happens when Godot is launched using godot-tools for VS Code. The path is correct otherwise.

https://github.com/user-attachments/assets/04078e55-af61-459e-b873-ca7e658f5798

In both cases I'm running the same build. Not sure if this is addon's bug for some reason or engine's.

Project for reference:
[PathBug.zip](https://github.com/user-attachments/files/17080097/PathBug.zip)

**Comment by bruvzg** [comment]
It's probably returning it in the same case as was set in `--path` argument (and to set current working directory). Not sure why it is an issue, drive letter is case-insensitive.

**Comment by KoBeWi** [comment]
Reported it as bug in VS Code plugin.
It's case insensitive when navigating, but in my case I had to compare paths as Strings and it failed.
