### ISSUE TITLE
Undo/Redo does not work in Bezier Animation Editor when moving keys

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#97146]
### Tested versions

In Master, not in 4.3. Regression introduced in 9d0944b673414249ef7af4476679827a09274677

### System information

Godot v4.4.dev (9d0944b67) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 31.0.15.4683) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

Undo/Redo does not work in Bezier Animation Editor when moving keys

https://github.com/user-attachments/assets/a579c534-7626-4abe-83cf-ad3de61a1397

Regression introduced in https://github.com/godotengine/godot/pull/96753

### Steps to reproduce

Create a bezier animation and try to edit the keys and undo/redo

### Minimal reproduction project (MRP)

NA

**Comment by akien-mga** [comment]
CC @Dowsley @TokageItLab

**Comment by Dowsley** [comment]
taking a look

**Comment by Dowsley** [comment]
Fix with explanation: https://github.com/godotengine/godot/pull/97169
