### ISSUE TITLE
2to3 Converter is unable to convert some models imported from dae file

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9715]
**Operating system or device - Godot version:**
2.1.x - 63a9b0213187abf3cc0d42372dd4beeb3c68b812
3.0 - 45b498c4e056e313e06b169d64f991b32db30423

**Issue description:**
Firstly I must say **majority of the models are being converted** by the converter (only materials are missing), few are not, I can't find any rules for what will convert ok and what will not.

After converting scene, the model is invisible in 3.0, but armature (in editor) is being drawn. After clicking on Skeleton and then AnimationPlayer node editor will crash, with Segmentation Fault error in rasterizer_storage_gles3.cpp:4409
![dae_convert](https://user-images.githubusercontent.com/6129594/28377278-91d27204-6cac-11e7-8e78-51b0379fe3e2.png)

**Steps to reproduce:**
1. Download minimal reproduction project.
2. Open it in newest 2.x branch, convert to 3.0
3. Open converted project in 3.0.
4. Open RaccoonModel.tscn
5. Observe that model is not rendered. 
6. Click on Armature node and then on AnimationPlayer node to crash editor.

**Link to minimal example project:**
[Model2to3ConvertTest.zip](https://github.com/godotengine/godot/files/1159731/Model2to3ConvertTest.zip)

**Comment by kubecz3k** [comment]
It seems this issue might be a duplicate of https://github.com/godotengine/godot/issues/9955, we will need to check if it's still valid after closing #9955

**Comment by kubecz3k** [comment]
Checked today. It's no longer crashing but the model still don't render after converting the project to 3.0

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by OvermindDL1** [comment]
Wasn't the issue with this one strictly related to the version 3 branch, and not 2?

**Comment by akien-mga** [comment]
It was about an issue which happens only when converting a 2.x project to 3.x using the 2 to 3 converter, so the problem lies in the converter itself (which is in 2.1).
