### ISSUE TITLE
Can't open scene with missing script

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#97153]
### Tested versions

4.4 dev 694d3c2
Works in 4.3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Trying to open scene with missing script results in error:
![image](https://github.com/user-attachments/assets/bb04af08-5cc5-4b7a-be74-691caccd3b6c)
This is printed in the console:
```
  Attempt to open script 'res://TheScriptHeNeeds.gd' resulted in error 'File not found'.
  Failed loading resource: res://TheScriptHeNeeds.gd. Make sure resources have been imported by opening the project in the editor at least once.
  C:\godot_source\scene/resources/resource_format_text.cpp:284 - Parse Error: File unrecognized. [Resource file res://INeedScript.tscn:6]
  Failed loading resource: res://INeedScript.tscn. Make sure resources have been imported by opening the project in the editor at least once.
```

### Steps to reproduce

1. Create scene
2. Attach a script
3. Close scene
4. Delete script file
5. Try to open scene again
6. Select "Open Anyway" on missing dependencies

### Minimal reproduction project (MRP)

[wherescript.zip](https://github.com/user-attachments/files/17048320/wherescript.zip)

**Comment by akien-mga** [comment]
I also saw this weird "saved in a newer format" error, I don't remember the circumstance, but the message in itself is completely wrong so that part is a bug too.

**Comment by matheusmdx** [comment]
Bisecting points to #95508 as the culprit, @Summersay415

![image](https://github.com/user-attachments/assets/cb94fc66-aca4-44fb-9070-69168ce475ca)

**Comment by KoBeWi** [comment]
So the option could be ignore ERR_UNRECOGNIZED when opening scene, but that would require to change error when newer format is used (#90571).

**Comment by akien-mga** [comment]
Based on this regression, I think #95508 was wrong, as it claimed to add an error only when no ResourceFormatLoader is found, but that is evidently not the case.

I'll revert it for now, and we can revisit how to signal that there is no ResourceFormatLoader in a safer way.
