### ISSUE TITLE
option to disable freelook

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9716]
**Operating system or device - Godot version:**
3.0

**Issue description:**
I would appreciate if we could have a way to disable free-look in 3.0 editor. Unfortunately it's interfering with tools which we are using in our project (We are using right mouse button for all activities that demand dragging on the scene, can't use any other mouse key since it would interfere with editor too much).

**Comment by Zylann** [comment]
If the problem is input conflict, would you like a rebind option to still be able to use freelook while having custom tools?

**Comment by kubecz3k** [comment]
@Zylann I will be happy with any solution, rebinding freelook to something else sounds cool since that's feature that it's nice to use, but if this is to much work I will be happy with simple option to disable :)

**Comment by kubecz3k** [comment]
Also there is possibility I wrote those tools in wrong way, and I should consume input events somehow. So I think I should probably investigate this subject more, but I think additional option would not do any harm :) (I hope)

**Comment by kubecz3k** [comment]
@Zylann thank you!
