### ISSUE TITLE
RigidBody2D cannot move in editor when using Rapier

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#97162]
### Tested versions

- Happens in 4.3, doesnt happen in 4.2.

### System information

Macbook air m1

### Issue description

After enable Rapier2D, the RigidBody2D node (not CollisionShape2D) in editor cannot move.

Building Godot locally I can see that it calls the PhysicsServer2D.body_set_state with transform that doesnt change(always same value).

Possibly its from sync issue or something is done wrong in the Rapier plugin?

Rapier issue for reference:
https://github.com/appsinacup/godot-rapier-physics/issues/257

### Steps to reproduce

Move the RigidBody2D node in editor

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
This is likely a plugin issue, please first confirm this *is* a bug in the engine, if it is this can be reopened, but any bug involving plugins or third party content should be investigated there first

**Comment by Ughuuu** [comment]
Sure thing, that's fair. Opened it to see if there might be any ideas from Godot on what could it be, as I'm not really 100% sure what changed between 4.2 and 4.3 that might cause this. I thought of this more of a discussion than a bug. My bad for opening it.

**Comment by AThousandShips** [comment]
No worries! Just good to avoid trying to solve things in multiple places, it no longer working after 4.3 might be a bug in the engine or simply the plugin failing to account for some change, so good to get details on that, and could be something we should document even if it isn't a bug in the engine

**Comment by Ughuuu** [comment]
@larspet noticed the issue. I was executing flush_queries even if the server was not active. Interestingly enough, in 4.3 this happens yet in 4.2 it did not. Could be some execution difference with physics state and editor. In any case, not calling the callbacks in flush_queries fixes it.
