### ISSUE TITLE
GDShader compiler crash when a void function returns a "void" value (void function call)

### ISSUE THREAD

**Issue by geekley** [godotengine/godot#97172]
### Tested versions

- Reproducible in v4.3.stable.flathub [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 Threads)

### Issue description

The editor is allowing a void function to have "void" return values (like calling a function returning void), but this seems to not be allowed in GLSL, causing a long editor freeze followed by lots of error output with GLSL code.

### Steps to reproduce

No errors are raised by the code editor in Godot:
`void-return-bug.gdshader`
```glsl
shader_type spatial;
void g() {}
void f() {
	return g();
}
void fragment() {
	f();
}
```
The relevant part of the compiled GLSL code:
```glsl
void m_g()
	{
	}

void m_f()
	{
return m_g();	} // ERROR here
```
```
ERROR: 0:672: 'return' : void function cannot return a value 
ERROR: 0:672: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Assuming this is something that isn't supported in GLSL this should probably be fixed by forbidding it in GDShaders as well
