### ISSUE TITLE
Pasting selection when using 3D GridMap deselects the node.

### ISSUE THREAD

**Issue by divinebeam** [godotengine/godot#97178]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.6081) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When pasting a selection of tiles in the GridMap, on left click in the world, the GridMap node is deselected. This is an issue because users want to continue working on the GridMap, having to constantly reselect the GridMap is an issue.

### Steps to reproduce

1. Create a 3d project with a GridMap
2. Import some meshes
3. Paint a bunch where-ever
4. Make a selection with Shift+Left Click
5. CTRL + C to copy the selection
6. Click to paste the selection and notice the GridMap is deselected.

### Minimal reproduction project (MRP)

[gridmapdeselectbug.zip](https://github.com/user-attachments/files/17054997/gridmapdeselectbug.zip)

**Comment by AThousandShips** [comment]
Thank you for your report, consolidating in:
* https://github.com/godotengine/godot/issues/52608

This has already been solved in 4.4 and will be in 4.3.1
