### ISSUE TITLE
The taskbar shows an empty window every time a tooltip pops up.

### ISSUE THREAD

**Issue by magian1127** [godotengine/godot#97177]
### Tested versions

4.3 stable , master [694d3c2]

### System information

Windows 11( 23H2) - Vulkan (Forward+) - GTX 3080 (561.09)

### Issue description

An empty window should not appear.

### Steps to reproduce

When the mouse hovers over any property in the detector, a tooltip pops up, and the issue occurs.
![image](https://github.com/user-attachments/assets/283a2dab-e035-4a4d-baad-92c48bcdf27d)

Switching to `gl_compatibility` resolves the issue, suggesting that it might be caused by a certain PR in Vulkan.

### Minimal reproduction project (MRP)

NOT REQUIRED

**Comment by AThousandShips** [comment]
Tooltips *are* windows but it seems they aren't properly hidden

**Comment by KoBeWi** [comment]
Can't reproduce on Windows 10

https://github.com/user-attachments/assets/20e2e671-7306-42e8-8901-94f5c408c1b4

**Comment by AThousandShips** [comment]
Also can't confirm on Windows 11 in 4.4.dev [694d3c2930bdfb43fd93e1e6641f66c4f19a5c77]

**Comment by Giganzo** [comment]
Related or same as https://github.com/godotengine/godot/issues/95863 ?

**Comment by magian1127** [comment]
I also used StartAllBack, and it seems to be in conflict with it.

**Comment by akien-mga** [comment]
Thanks for confirming, consolidating in #95863.
