### ISSUE TITLE
Support HTTP Proxy for WebSocketPeer

### ISSUE THREAD

**Issue by metamuffin** [godotengine/godot#97189]
### Issue description

Affected version: 4.3.stable

Godot currently only supports HTTP proxying for HTTPClient but not WebSocketPeer and WebSocketMultiplayerPeer interfaces that also use HTTP internally. It should expose the same set_http_proxy and set_https_proxy methods that HTTPClient has.

### Steps to reproduce

Try to use Godot to connect with Websocket through a proxy.

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead.
