### ISSUE TITLE
Font subpixel antialiasing results in artifacts

### ISSUE THREAD

**Issue by mihe** [godotengine/godot#97195]
### Tested versions

- Reproducible in 4.4.dev [694d3c2930bdfb43fd93e1e6641f66c4f19a5c77]
- Reproducible in 4.4.dev [2c136e6170a40f58f2dfb89d32eadfca7156ef37]
- Not reproducible in 4.4.dev [14a7e0abb313915fc5e4f36b34f9169b1d45774c]

### System information

Godot v4.4.dev (2c136e617) - Windows 11 (10.0.22631) - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6109) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

As best I can tell (using `git bisect`) this looks to be a regression caused by #92797.

When using the "LCD Subpixel" value of the editor setting `interface/editor/font_antialiasing`, on Windows 11 in my case, I end up getting rendering artifacts around a lot of the text in the editor, which looks like this:

![Subpixel](https://github.com/user-attachments/assets/b3540aa0-e1b0-412b-a75c-5b53cecc9e95)

This is what it looks like when using the default grayscale antialiasing:

![Grayscale](https://github.com/user-attachments/assets/02d43e97-fad4-4ab7-b3ea-26e749e9eeae)

Here's what subpixel antialiasing looks like up close:

![image](https://github.com/user-attachments/assets/3d8d7305-fa48-454d-aff4-06f7087b6a71)

Here's what the grayscale equivalent looks like up close:

![image](https://github.com/user-attachments/assets/16f87634-3148-409d-aaee-fe541bbd1fd9)

### Steps to reproduce

- Open the editor.
- Set the `interface/editor/font_antialiasing` editor setting to "LCD Subpixel".
- Wait for the editor to update everything.
- Note the artifacts.

### Minimal reproduction project (MRP)

N/A

**Comment by stuartcarnie** [comment]
Can confirm I'm seeing oddities, so I'll take a look. Thanks for the report!

**Comment by stuartcarnie** [comment]
![CleanShot 2024-09-20 at 13 32 29@2x](https://github.com/user-attachments/assets/66ff3d36-4adb-4edf-9004-83f03f9c9ab1)

Found the issue, and is fixed in #97217
