### ISSUE TITLE
Export of GDExtension files that were excluded still appears in extension_list.cfg resulting in errors during startup

### ISSUE THREAD

**Issue by markeel** [godotengine/godot#97207]
### Tested versions

Problem found on v4.3.stable.official [77dcf97d8]
This problem appears to have existed in earlier version as well

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 770 (ADL-S GT1) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

When an export is performed with a GDExtension that extension is listed in the extension_list.cfg file in res://.godot

Even if the files that go into that extension are excluded from export (such as would be done for the Git plugin (which is editor only)) this file causes the exported binary to look for that extension.  It cannot be found and an error is output.

This has been reported against the godot-git-plugin, but the real issue is the way an export ignores the exclusion filters for the contents of the extension_list.cfg

### Steps to reproduce

1. Create a project that includes a GD Extension that is for the editor only (such as the official Git plugin), 
2. Export that project and exclude the plugin folder by doing Resources->Export Mode = "Export all resources in the project except resources checked below", and clicking "addons/godot-git-plugin" folder
3. Run the exported project and observe the error: "ERROR: Error loading GDExtension configuration file: res://addons/godot-git-plugin/git_plugin.gdextension"

### Minimal reproduction project (MRP)

There are 2 cases 
1. Where the only GDExtension is the add-on that is excluded
2. Where there is a GDExtension in addition to the add-on that is excluded.
[one-extension.zip](https://github.com/user-attachments/files/17067456/one-extension.zip)
[gdextension_example_cpp.zip](https://github.com/user-attachments/files/17067478/gdextension_example_cpp.zip)

**Comment by timkrief** [comment]
I'm glad this was fixed on 4.4, is there any way to avoid this issue on 4.2 ?
