### ISSUE TITLE
Renaming nodes broken on X11

### ISSUE THREAD

**Issue by pmoosi** [godotengine/godot#97211]
### Tested versions

Reproducible in 4.4 after #96829

### System information

Godot v4.4.dev.mono (1d3e9b368) - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

Renaming nodes in the editor with F2 (or the context menu) does not work properly on X11 since #96829. It usually works once after the editor was started. After that when renaming, the text-field opens, text can be entered, but it cannot be confirmed until the text-field is clicked again.

### Steps to reproduce

Open a project and try to rename any node with F2. This works the first time, but the second time, it needs to be refocused.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
I can confirm the issue on X11 / XWayland. I don't have the issue with the Wayland DisplayDriver or X11 in single-window mode.

CC @dsnopek 

(For the record the "System information" in the OP state that you're using Wayland, but I guess this was copied over from another instance?)

**Comment by pmoosi** [comment]
I'm on a Wayland machine but use the XWayland version where the bug happens. I should have specified that more clearly.

**Comment by akien-mga** [comment]
> I'm on a Wayland machine but use the XWayland version where the bug happens. I should have specified that more clearly.

Actually it's my bad, I thought the "Copy System Info" would mention what display driver is used by Godot, but it's indeed only reporting what is the session type at the OS level.

Mine is also:
```
Godot v4.4.dev (0a4aedb36) - Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)
```

I'll open a proposal about this because it's confusing and we always lack the proper info for Linux bug reports to know whether it's an X11 client on an X11 host or a X11 or Wayland client on a Wayland host.

**Comment by dsnopek** [comment]
Thanks!

I've finally managed to figure out why I haven't been able to reproduce some of these focus issues on my Ubuntu system, and I can now reproduce this one locally without having to test in a Fedora VM.

Anyway, I'm looking into it!
