### ISSUE TITLE
modules/text_server_adv/text_server_adv.cpp:3486 - Condition "!_ensure_cache_for_size(fd, fd->msdf ? Vector2i(fd->msdf_source_size, 0) : Vector2i(16, 0))" is true. Returning: false   FreeType: Error loading font: ''.

### ISSUE THREAD

**Issue by 18677664100** [godotengine/godot#97219]
### Tested versions

4.3.stable

### System information

Apple - Apple M1 Max -Godot Engine v4.3.stable.official

### Issue description

modules/text_server_adv/text_server_adv.cpp:3486 - Condition "!_ensure_cache_for_size(fd, fd->msdf ? Vector2i(fd->msdf_source_size, 0) : Vector2i(16, 0))" is true. Returning: false
  FreeType: Error loading font: ''.

Yesterday, after upgrading my Mac to macOS Sequoia, I encountered this error when entering or creating a project, even though I didn't make any changes.

### Steps to reproduce

![QQ20240920-143341](https://github.com/user-attachments/assets/db1b1f47-8d77-4635-abe4-9aafd385b31b)

### Minimal reproduction project (MRP)

This situation occurs as soon as I create a new project.

**Comment by JoyFYan** [comment]
<img width="1470" alt="截屏2024-09-21 14 37 48" src="https://github.com/user-attachments/assets/a91789a9-58f2-40f2-ae48-25fc82f2298f">
Same problem after upgrading my Mac to macOS Sequoia

**Comment by JoyFYan** [comment]
> ### Tested versions
> 4.3.stable
> 
> ### System information
> Apple - Apple M1 Max -Godot Engine v4.3.stable.official
> 
> ### Issue description
> modules/text_server_adv/text_server_adv.cpp:3486 - Condition "!_ensure_cache_for_size(fd, fd->msdf ? Vector2i(fd->msdf_source_size, 0) : Vector2i(16, 0))" is true. Returning: false FreeType: Error loading font: ''.
> 
> Yesterday, after upgrading my Mac to macOS Sequoia, I encountered this error when entering or creating a project, even though I didn't make any changes.
> 
> ### Steps to reproduce
> ![QQ20240920-143341](https://private-user-images.githubusercontent.com/11057282/369289214-db1b1f47-8d77-4635-abe4-9aafd385b31b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MDE1MzIsIm5iZiI6MTcyNjkwMTIzMiwicGF0aCI6Ii8xMTA1NzI4Mi8zNjkyODkyMTQtZGIxYjFmNDctOGQ3Ny00NjM1LWFiZTQtOWFhZmQzODViMzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDA2NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMzg4YjFkYTgyMzJlYmYwOThlOWFjZGRkOTYyYTdiOWUxYThiNWQwMGRkNjk1ODM5YWViNGI0MTQwZThlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G7J4xDDC4JfzREOyfGM9hdeZEpcxDNiF4PZaJlvw-RY)
> 
> ### Minimal reproduction project (MRP)
> This situation occurs as soon as I create a new project.

I solved it by changing language from Chinese to English.

**Comment by 18677664100** [comment]
@JoyFYan Certainly! The translation of the sentence is: "Also, all your Chinese labels will become garbled, you can encapsulate all the labels with a Chinese font for processing."
![QQ20240920-161942](https://github.com/user-attachments/assets/680edd22-4ff8-473f-9304-90082ae258b9)
![QQ20240920-161959](https://github.com/user-attachments/assets/31803018-3c74-4632-b9a6-e792c23839db)

**Comment by akien-mga** [comment]
Duplicate of #96101.
