### ISSUE TITLE
Tool scripts modified from the in-engine script editor don't update

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#97238]
### Tested versions

454251660c4c227121be6a6bab67b2998ffbf81a

### System information

Windows 11

### Issue description

It seems a recent PR, while intended to fix updating script properties when editing script properties from external editors, caused similar issues when updating scripts from the in-engine editor, including the entire script failing to update, not just the property panel.

The problem seems to actually be specific to tool scripts, and the behaviour is only noticed after a regular script is converted to a tool script and the project is reloaded. After this point, it becomes impossible to update the script. The error `Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE` is also visible upon saving this script for the first time.

Bisected to a regression in commit 46edd6df5581098d8494f9b51a9791dcdabd0ee4

### Steps to reproduce

- Open the project and test scene
- In the script assigned the root node, modify the name of the `test1` property to something else.
- Save the script and observe the error.
- Click on another node in the scene tree and back to the root node.
- The root node's inspector may have changed, but repeat the step of renaming the exported property once again and observe that the inspector will stop updating, becoming stuck after the first attempt to update it.

### Minimal reproduction project (MRP)

[gdscript_test.zip](https://github.com/user-attachments/files/17076970/gdscript_test.zip)

**Comment by ryevdokimov** [comment]
@Hilderin 

Maybe: https://github.com/godotengine/godot/pull/97168 will fix the issue, it at least resolves the error.

**Comment by Hilderin** [comment]
Yes, #97168 will fix the error message and the fact that tool scripts are not reloaded anymore.

**Comment by SaracenOne** [comment]
Yes, can confirm that that PR does indeed fix this issue.
