### ISSUE TITLE
Multiple ScrollContainer nodes under a TabContainer show warning messages

### ISSUE THREAD

**Issue by Odiobill** [godotengine/godot#97233]
### Tested versions

- Reproducible in 4.3.stable

### System information

CachyOS Linux (Arch based), kernel 6.11.0-2-cachyos (64-bit)

### Issue description

Adding multiple ScrollContainer nodes under a TabContainer shows yellow triangles with the warning message:
- ScrollContainer is intended to work with a single child control.

The warning will appear for every ScrollContainer after the first one.

![Screenshot_20240920_121644](https://github.com/user-attachments/assets/8a7bd9c9-7770-4bbf-a417-6ff47d0e9325)

### Steps to reproduce

- Create a new UI scene
- Add a TabContainer node
- Add a ScrollContainer node under the TabContainer
- (expected) the ScrollContainer will show the warning because it doesn't have any child
- Add any control node under the ScrollContainer
- (expected) the warning will disappear
- Duplicate the ScrollContainer, or add a new one with a single control child, to create another tab
- Newly added (or duplicated) ScrollContainer nodes will keep showing the warning message

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This sounds like it duplicates it's own scroll bars incorrectly when duplicating, making it fail the check which checks for the scroll bars, will do some digging and test

**Comment by AThousandShips** [comment]
This is caused by an oversight in the checks for the scroll container check:
https://github.com/godotengine/godot/blob/0a4aedb36065f66fc7e99cb2e6de3e55242f9dfb/scene/gui/scroll_container.cpp#L535-L557

This should probably use: `as_sortable_control(get_child(i), SortableVisbilityMode::VISIBLE);`

CC @KoBeWi

**Comment by daveTheOldCoder** [comment]
In 4.4-dev4, the warning messages are no longer present.
