### ISSUE TITLE
Can't build Android exports

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#9723]
ArchLinux 64b godot3.0 

error:
UnboundLocalError: local variable 'can_vectorize' referenced before assignment:
  File "/root/Godot-nightly/godot/SConstruct", line 286:
    detect.configure(env)
  File "./platform/android/detect.py", line 95:
    if (can_vectorize):

**Comment by Noshyaar** [comment]
#9772 is merged recently. I think it supposed to fix this. Try pulling master branch and rebuild.

**Comment by vnen** [comment]
Yeah, this fixed by #9722.
