### ISSUE TITLE
Can't push_back into a Vector2Array inside a Dictionary

### ISSUE THREAD

**Issue by argent0** [godotengine/godot#9726]
**Operating system or device - Godot version:**
Linux 64bits, godot 2.1.3

**Issue description:**

I pushed a Vector2 into a Vector2Array but nothing was inserted.

**Steps to reproduce:**

     func _ready():
        var d = {}
        d["goo"] = Vector2Array()
        d["goo"].push_back(Vector2(0,0))
        assert(d["goo"][0]==Vector2(0,0))

**Comment by reduz** [comment]
Yes you cant, they are atomic. Also pushing back in those is slow. Just
resize to max size, set all elements and then ads it to the dictionary

**Comment by argent0** [comment]
Ok, thanks for the quick reply

**Comment by voithos** [comment]
Just curious, what does "atomic" mean here? Do you mean "immutable"? If so, should it generate an error if used incorrectly?

**Comment by Zylann** [comment]
Related to https://github.com/godotengine/godot/issues/8409 ?

**Comment by reduz** [comment]
@voithos yes, i'm sorry, not sure of the right word. their reference is not shared when you pass them around.
