### ISSUE TITLE
animations by AnimationPlayer are shared between scene and inherited scene?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9728]
**Operating system or device - Godot version:**
2.X and 3.X

**Issue description:**

Since the animations are shared, it's impossible to customize animation in inherited scene.
All modifications made to the animation in inherited scene will also effect the original scene.
It's possible to add feature to support override property for animation?

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by RandomShaper** [comment]
As with anything being a `Resource` you can `duplicate()` your `Animation`s, do whatever to them and call `AnimationPlayer.add_animation()` for each to make them available to the player. Maybe you have to do first `AnimationPlayer.removeAnimation()` to avoid name clashes (not sure right now).

**Comment by alexzheng** [comment]
I mean by editor, by code is too complicated.

**Comment by kubecz3k** [comment]
Closing as a dulicate of https://github.com/godotengine/godot/issues/6169
