### ISSUE TITLE
Area2d _on_body_entered Signal activation on scene load when body is in the same scene

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [godotengine/godot#97285]
### Tested versions

Happens consistently in 4.3 project, not reproducible on any other project

### System information

Godot v4.3.stable - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 560.35.03) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

When CharacterBody2D and Area2D are in the same scene, the signal _on_body_entered always activates, weather they are colliding or not 

### Steps to reproduce

1 - Have a characterBody2D and Area2d in the same scene
2 - Signal to Node2d _on_body_entered
3 - run scene

### Minimal reproduction project (MRP)

[operationbirthday (copy).zip](https://github.com/user-attachments/files/17084664/operationbirthday.copy.zip)

**Comment by AThousandShips** [comment]
The bodies are colliding though? The `Ava` area and the `Collision` static body area colliding, if you move either of the collision shapes away it stops happening, I don't see any issue here

It doesn't collide with the body, it collides with the `Collision` static body, check with:
```gdscript
func _on_ava_body_entered(body: Node2D) -> void:
	#get_tree().change_scene_to_file("res://Scenes/SecretAva.tscn")
	print("Hello ", body)
```
And you will see that it prints: `Hello Collision:<StaticBody2D#XXX>`

It still happens regardless if the `Player` body is in the scene

**Comment by AThousandShips** [comment]
You're welcome! In the future I'd suggest asking in the other [community channels](https://godotengine.org/community/) to make sure something is actually a bug
