### ISSUE TITLE
Disable Enet in web builds

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#97287]
I'm surprised [ENet is also compiled in web builds](https://github.com/godotengine/godot/blob/2f2d1a7e68d315e5f26cde30532a51087536c9f6/modules/enet/config.py#L1-L2), considering web browsers can't send or receive UDP packets (which is ENet's only transport layer). Disabling it on the web platform would help reduce the default binary size a bit.

_Originally posted by @Calinou in https://github.com/godotengine/godot/issues/92371#issuecomment-2251444764_

**Comment by AThousandShips** [comment]
Feature proposals are tracked [here](https://github.com/godotengine/godot-proposals), this is for bugs. Please open a proposal instead. 

Also don't edit the template, it should be left as is

**Comment by AThousandShips** [comment]
This could technically be seen as a bug, but should be discussed as a proposal IMO, but if it should be treated as a bug the template needs to be restored properly

**Comment by Swarkin** [comment]
Oh sorry, I considered it as a bug because enet cannot be used in web. I'll make an issue in the proposals repo

**Comment by AThousandShips** [comment]
I'd say now to make a bug report as I realized it was a bug
