### ISSUE TITLE
Godot Editor Not Updating Exported Properties From C#

### ISSUE THREAD

**Issue by zachbugay** [godotengine/godot#97296]
### Tested versions

- Reproducible in: v4.4.dev2.mono.official [97ef3c837] and NOT reproducible in v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 32.0.15.6109) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Using the latest v4.4.dev2.mono release, the Godot Editor Inspector is not updating after Exports have been added to a C# file, and the Godot Editor Builds the Project.

Rather, the whole Godot Editor needs to be closed, and relaunch for the properties to be seen.

![image](https://github.com/user-attachments/assets/19631379-8bb8-40d4-9ba8-6ba2e9b5f77f)
![image](https://github.com/user-attachments/assets/96a73442-a46e-4425-bb20-60bdc159e90a)

### Steps to reproduce

1. Launch Godot_v4.4-dev2_mono_win64.exe
2. Create a new project, named anything you want stored anywhere.
3. Editor => Editor Settings =>Dotnet => Editor => Visual Studio
    1. External Editor Visual Studio
4. Click "3D Scene" under Create Root Node
5. Click Attach a new or existing script to the selected node.
6. Select Language: C#
7. Template Node: Default
8. Save the scene
```c#
	[Export]
	public int Foo { get; set; }
```
10. In the Godot Editor, click "Build Project"

### Minimal reproduction project (MRP)

https://github.com/zachbugay/godot-ui-not-updating-4.4-dev2

**Comment by raulsntos** [comment]
This sounds similar to https://github.com/godotengine/godot/issues/97060. And it looks like that issue may be the same as https://github.com/godotengine/godot/issues/96828 which was fixed by https://github.com/godotengine/godot/pull/74830.

**Comment by Hilderin** [comment]
I was able to reproduce with 4.4 dev 2 but the issue is now fixed in master. I agree with raulsntos, it's most certainly related to #96828

I'm closing the issue since it's now working in master.

**Comment by VVander** [comment]
I just had this happen to me in v4.3.stable.mono.official, but once I reloaded the project, it updates appropriately after a build now.

**Comment by CraigBartle** [comment]
This appears to still be an issue in v4.4.1 stable mono.
