### ISSUE TITLE
No code completion for sub-properties

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#9732]
**Operating system or device - Godot version:**
Godot 3

**Issue description:**
There's no autocompletion when accessing sub-properties of script properties.

**Steps to reproduce:**
Try to access a sub-property or method on a property, like `texture.` on a `Sprite` Node.

**Comment by eon-s** [comment]
Works fine on 45b498c4e

Autocompletion only fails if the scene (where the script is) is closed or is not the currently displayed on the tree.

**Comment by vnen** [comment]
Works for me too with a recent build:

![godot engine_2017-07-20_11-32-24](https://user-images.githubusercontent.com/5599796/28422671-22793864-6d3f-11e7-9216-59a4bc910dfd.png)

**Comment by Hinsbart** [comment]
Ah yes, that's working for me as well. I meant sub-properties, edited the original post.

**Comment by reduz** [comment]
oh, I fixed this yesterday, so closing..
