### ISSUE TITLE
Encrypted web games doesn't work

### ISSUE THREAD

**Issue by kopeek** [godotengine/godot#97334]
### Tested versions

4.4-dev2, 4.3 stable

### System information

Windows 10

### Issue description

I need a encryption for my web games, and with that encryption I need also a custom build. I used a custom template but it only works, when I'm not using encryption. And when I'm using encryption with that custom template I got that error:
"Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension)."
Every file after the export has the name "index" and also after export ther is a .pck file

### Steps to reproduce

- Build your custom web template
- Use that custom web template with Encryption
- Export project
- Run it (in browser, not in Editor)

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This sounds like user error and not a bug, I'd suggest asking in the other [community channels](https://godotengine.org/community/) to make sure

**Comment by kopeek** [comment]
but when I compile templates ther aren't errors, so I think that it is a bug, and also without encryption it works fine

**Comment by AThousandShips** [comment]
Did you use the same encryption key correctly? Just because there isn't a bug in the compilation doesn't mean anything 

But please ask in the forums or elsewhere to make sure you're not missing something

**Comment by kopeek** [comment]
I setted Key in the export and in the Windows (What in the Godot tutorial it says)

**Comment by kopeek** [comment]
I found a fix: You need to disable index encrypting, and it works now :)
