### ISSUE TITLE
Better custom nodes workflow for Visual Script

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#9735]
Custom nodes for Visual Scripts are not in really good state right now (despite the fact that documentation is absent and it causes some crashes). The workflow is a bit convoluted, especially because it is geared towards people with lesser programming experience.

For those who don't know, adding a custom node to a visual script requires these steps:

- Add a `Custom Node` to the VS, from the `Custom` category.
- Select (in the Inspector) the right script with the custom node code.
- ~Close and reopen the VS, because it does not reload.~ (fixed by #9741)
- Use the new node.

This is how I think custom nodes should be added:

- Find the wanted custom node in the `Available Nodes` panel.
- Drop it into place and use it.

My suggestion to make this work is quite simple: add some `EditorPlugin` function that adds a custom node to the VS editor. Then it'll just be a matter of calling `add_custom_vs_node(name, category, script)` from a plugin to be able to use it in the scripts.

The VS editor would just automate the process that is currently done manually.

**Comment by vnen** [comment]
BTW, I fixed the "close and reload" step with #9741, which makes it hundred times easier to use custom nodes. Still, I think that having them available in the list would be better.

**Comment by reduz** [comment]
feel free to work on it if you want, seems like it would not be that hard to implement
