### ISSUE TITLE
Bodies collide but are not affected otherwise on certain collision mask setups (2D physics)

### ISSUE THREAD

**Issue by stephanbogner** [godotengine/godot#97354]
### Tested versions

Reproducible in Godot v4.2.2.stable

### System information

Godot v4.2.2.stable - macOS 14.6.1 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Setup:
- I have a basic setup with **ball** and **platform** that can move (connected with a soft pin joint)
- I expect the **ball to push the platform down** when landing on it
- In **all cases** the bodies **collide**, but in **some** the **"pushing down“ aspect doesn’t work** (case 2)

### Confusion:
It works depending on the collision layer and mask setup, but I’d have expected for case 2 to work as well (because also the collision works).

<img width="816" alt="Bildschirmfoto 2024-09-23 um 10 54 43" src="https://github.com/user-attachments/assets/211c290f-8a12-4dba-aa5e-df3e088014eb">

### Context:
I am not sure if this **a bug or intended behaviour**, because they do collide but not interact as expected. The [documentation](https://docs.godotengine.org/en/stable/tutorials/physics/physics_introduction.html#collision-layers-and-masks) says the following but only about colliding:
> This describes what layers the body will scan for collisions. If an object isn't in one of the mask layers, the body will ignore it. By default, all bodies scan layer 1.

So if it’s not intended it might also be a joint bug.

Might be related to other issues such as #70671 

### Steps to reproduce

For the „fail“ case:
1. Create ball with a RigidBody2D (set collision layer to 2 and collision mask to 1 and 2)
2. Create a platform with a RigidBody2D (leave collision settings at 1)
3. Create a StaticBody2D as well as a PinJoint2D
4. Connect the pin joint to the platform and the static body
5. Set the joint’s softness to 16
6. Watch the bodies collide but without the platform moving
7. **Note:** Whether the static body you connect joints to has a collision shape or not doesn’t matter

### Minimal reproduction project (MRP)

[physics-layer-test.zip](https://github.com/user-attachments/files/17094872/physics-layer-test.zip)

**Comment by Torguen** [comment]
Case 2 still doesn't work even if you apply the settings from Case 1 or Case 3.

**Comment by stephanbogner** [comment]
> Case 2 still doesn't work even if you apply the settings from Case 1 or Case 3. v4.4.dev2.official [[97ef3c8](https://github.com/godotengine/godot/commit/97ef3c837263099faf02d8ebafd6c77c94d2aaba)]

Could you elaborate?
Because if I set PlatformCenter’s collision mask to 1 and 2 it functions exactly like case 3 (in 4.2.2)
Or does it only happen for you in 4.4?

**Note:** I didn’t even know 4.3 was already released. Will check this as well.

**Comment by Torguen** [comment]
Sorry, I was wrong.
It does work if you apply settings 1 and 3 to case 2.

**Comment by pmoosi** [comment]
As far as I know, this is expected behavior. In your second example, the platforms scans for collisions on layer 1, but the ball is on layer two. Therefore, the platform never detects a collision and won't react. 
The ball stops, since it detects the collision with the platform (it scans for layer 1, i.e., the platform layer).

**Comment by stephanbogner** [comment]
@pmoosi 
Thanks for clarifying this. Then this issue could be closed.

I have to think about how the docs could be enhanced to explain this situation as I stumbled upon it many times now. It always causes me to scratch my head, changing weights and trying things before realising it has to do with masks and layers.
