### ISSUE TITLE
exported int variables in the editor inspector tab display incorrect values for high integers

### ISSUE THREAD

**Issue by Chuck-ie** [godotengine/godot#97364]
### Tested versions

- Reproducable in 4.3.stable

### System information

Godot v4.3.stable - Fedora Linux 39 (Workstation Edition) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (RADV NAVI22) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

If you define a custom Resource with an exported int value I expect the editable field in the Inspector tab to allow the same range of values as the datatype which for an int, [according to this documentation](https://docs.godotengine.org/de/4.x/classes/class_int.html), should be 2^63 to 2^63 - 1 i.e. -9223372036854775808 to 9223372036854775807. 

The current behaviour  however is that pasting high values of that range into the Inspector changes the displayed value to something else.

example value: (input -> output)
2^63 - 1 (9223372036854775807) -> -2^63 (-9223372036854775808)
2^62 (4611686018427387904) -> 2^62 (4611686018427387904)
2^61 (2305843009213693952) -> 2^61 - 256 (2305843009213693696)

These are just 3 examples, however I tried other numbers which sometimes result in the correct or incorrect value.

One more thing to mention is that this issue doesn't occur for numbers that are slightly above the int32 limit of 2147483647 e.g. 2^34 or 2^35.

One more issue that occurs in combination with the previous one is that the increment and decrement button of the exported int field also stop working. (not sure if this really deserves a separate issue so I'm including it here for now)

### Steps to reproduce

- download my minimal example repository [here](https://github.com/Chuck-ie/godot-editor-int64-bug) or from the attached .zip file
- double click ```example_resource.tres```
- copy and paste different values into the exported Int Value field in the Inspector tab
- use the increment/decrement arrow buttons inside the exported Int Value field

![image](https://github.com/user-attachments/assets/0aa5b9fa-c447-47b6-8554-6b01d2f2c4d9)

### Minimal reproduction project (MRP)

[godot-editor-int64-bug-main.zip](https://github.com/user-attachments/files/17098995/godot-editor-int64-bug-main.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/79633
* https://github.com/godotengine/godot/issues/94686
* https://github.com/godotengine/godot/issues/33095

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
