### ISSUE TITLE
v4.4.dev2 endless error messages "WebGL: INVALID_OPERATION: texParameter: no texture bound to target" on the web

### ISSUE THREAD

**Issue by tvister091** [godotengine/godot#97369]
### Tested versions

- Reproducible in: v4.4.dev2.official [97ef3c837]
- Not reproducible in: v4.4.dev1.official [28a72fa43]

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - GeForce GT 740M - Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 Threads)

### Issue description

When starting remote debugging on the web, messages "WebGL: INVALID_OPERATION: texParameter: no texture bound to target" pop up endlessly

![1](https://github.com/user-attachments/assets/a7ef1a30-169f-42d3-987a-ae810ec19b7d)

![2](https://github.com/user-attachments/assets/1c3e675c-9529-4f30-80fd-49b48ee6aef5)

![3](https://github.com/user-attachments/assets/5d7db1e8-cc3f-441f-9849-bc260ea667a1)

console log:
[localhost-1727107488266.log](https://github.com/user-attachments/files/17100760/localhost-1727107488266.log)

### Steps to reproduce

Create a project.
Run the game in remote debugging mode in the browser.

### Minimal reproduction project (MRP)

[testweb.zip](https://github.com/user-attachments/files/17100798/testweb.zip)

**Comment by clayjohn** [comment]
I confirmed locally. This issue is pretty bad, but it doesn't seem to break anything. It should be fixed ASAP though
