### ISSUE TITLE
`Color::lerp()` produces darker colors than expected

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#97375]
### Tested versions

- Since Godot's inception!

### System information

Godot v4.4.dev (4254946de) - macOS 14.6.1 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads)

### Issue description

The algorithm used to lerp colors is plain wrong. It interpolates the color values directly, but this is naive at best.

https://github.com/godotengine/godot/blob/4254946de93bab0cc1fb36a7b9039c9ec43be924/core/math/color.h#L106-L113

It's wrong because color values are square root values (for storage reasons). And the reality is that the sum of square roots divided by two is less than the square root of a sum divided by two.

$$
\frac{\sqrt{x} + \sqrt{y}}{2}
\leq
\sqrt{\frac{x + y}{2}}
$$

For the color lerp to be correct, it is imperative to raise to the power of two the color values, then lerp, then square root the result.

$$
\sqrt{\frac{x^2 + y^2}{2}}
$$

See here how the "dumb" result looses the luminance of the two merged colors, and how the accurate one keeps it:

<img width="688" alt="Capture d’écran, le 2024-09-23 à 14 08 35" src="https://github.com/user-attachments/assets/2c7c93d9-4ce5-44f2-852a-1a580bada541">

For more info and for my source, see [MinutePhysics 9 years old video](https://youtu.be/LKnqECcg6Gw?si=DvkPd0NE9yytQf-Y&t=153).

### Steps to reproduce

1. Try lerping color values

### Minimal reproduction project (MRP)

~~[accurate-lerp.zip](https://github.com/user-attachments/files/17102295/accurate-lerp.zip)~~
~~[accurate-lerp 2.zip](https://github.com/user-attachments/files/17102392/accurate-lerp.2.zip)~~
[accurate-lerp 3.zip](https://github.com/user-attachments/files/17102630/accurate-lerp.3.zip)

**Comment by adamscott** [comment]
The solution here is obviously not to replace the actual `Color::lerp()`, but instead exposing a `Color::accurate_lerp()` that would fix this issue.

**Comment by clayjohn** [comment]
@adamscott Color isn't inherently in any particular color space. What you have discovered is the difference between interpolation in linear sRGB vs. gamma sRGB. 

The proper solution is to call either srgb_to_linear() or linear_to_srgb() before interpolation depending on the desired behaviour

**Comment by adamscott** [comment]
Converting the color values from SRGB to linear, then interpolating (and converting back to SRGB) doesn't give the same results, but it's pretty close.

<img width="688" alt="Capture d’écran, le 2024-09-23 à 14 38 11" src="https://github.com/user-attachments/assets/76ee472c-6129-4f31-839b-9ef86d9a184c">

**Comment by adamscott** [comment]
> What you have discovered is the difference between interpolation in linear sRGB vs. gamma sRGB.

Just saw that the square root is actually an approximation. So the following is correct:
1. Convert your colors from SRGB to linear (using `Color::srgb_to_linear()`)
2. Lerp colors using `color_one_linear.lerp(color_two_linear, lerp_value)`
3. Convert back the result to SRGB (using `Color::linear_to_srgb()`)

**Comment by clayjohn** [comment]
Also note that a linear blend is not necessarily more "correct" either. In some cases it has nice properties, but often when working with colors, what you want is a "perceptual" blend. Which is where things like OKLab come from

See here for a nice explanation: https://bottosson.github.io/posts/colorwrong/

**Comment by JoNax97** [comment]
It might be worth adding this explanation to the color space docs
