### ISSUE TITLE
GDExtension classes inheriting from Resource are not using icons in FileSystem

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot#97387]
### Tested versions

4.3 dev 1

### System information

Windows 10 Godot 4.3 dev 1 Vulkan

### Issue description

I am aware there is https://github.com/godotengine/godot/issues/32706, but it does not seem to cover GDExtensions.

Currently, GDExtension classes inheriting from Resource are not using icons in FileSystem. It seems to work in every other place, but not in FileSystem for some reason.

![image](https://github.com/user-attachments/assets/28a07008-ec8c-4b08-aa89-a9b28d53a613)
![image](https://github.com/user-attachments/assets/ddc5cd3e-52eb-4cc3-8924-2260ef8b8e8b)
![image](https://github.com/user-attachments/assets/c54ef2b9-d3c7-4965-9754-f9f28ebb657c)

### Steps to reproduce

1. Create a class in GDExtension that inherits Resource
2. Assign an icon in .gdextension file to said class
3. Observe how FileSystem is using default icon for this class, while the property viewer is displaying everything as expected

### Minimal reproduction project (MRP)

You can see an example in the root of the project here
![image](https://github.com/user-attachments/assets/11c3a17a-5ef4-4189-b7b7-505a6c721c22)
[IconTest.zip](https://github.com/user-attachments/files/17106236/IconTest.zip)

**Comment by SaNeOr** [comment]
I tested it and found the same problem when using gdscript to inherit **resource** subclasses.
