### ISSUE TITLE
LightmapGI has no Min Light setting

### ISSUE THREAD

**Issue by NatePlays95** [godotengine/godot#97391]
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 32.0.15.5599) - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

Since a few versions ago the "Min Light" setting of the LightmapGI node has been removed.
It was super useful as it was the only way to achieve a "global ambient light" effect with GI.
Currently, regardless of your Environment settings, areas without access to external light will be completely black inside the Lightmap.

## Desired Effect
For artistic reasons I want to control the light color at the darkest areas. Ambient Light is the obvious option as it works with VoxelGI. Like with Real Time and Voxel this shouldn't introduce outdoors light.

### vvv Comparison with VoxelGI, with Ambient Light 0, 1 white and 1 blue respectively.
![image](https://github.com/user-attachments/assets/6a7a9c67-1ec0-42e0-8d24-c7c56567999d)
![image](https://github.com/user-attachments/assets/e0b80c8a-27b9-4ad4-a3a0-7ed738cc96db)
![image](https://github.com/user-attachments/assets/92f62fd4-5bec-4ba6-a8e7-60c756807598)

## Observed Effect
Changing Ambient Light has no effect on Lightmap, shadow areas stay pitch black. Creating a "Custom Color Environment" setting inside the Lightmap makes the shadow areas not pitch black but introduces artifacts, light leakage and changes outdoors lighting.

### vvv No Lightmap, Ambient Light as Color, Energy = 0
![image](https://github.com/user-attachments/assets/fce7432b-066e-4108-a07e-b10bb05844d5)

### vvv No Lightmap, Ambient Light as Color, Energy = 1
![image](https://github.com/user-attachments/assets/b0b092d1-a02d-45f9-a01a-0c9a7d91a5f4)

### vvv Baked after Ambient Light energy was set to 0
![image](https://github.com/user-attachments/assets/7a810590-0ecf-41ca-956f-bf66967e17d2)

### vvv Baked after Ambient Light energy was set to 1
![image](https://github.com/user-attachments/assets/d3fc3018-ca1e-4dba-b070-fb4e16938da6)

### vvv Baked with custom color setting (exaggerated to 4), light comes from the window, which is not the desired effect. Light leaks through the floor.
![image](https://github.com/user-attachments/assets/dadcd7a6-52bb-4e2a-8c52-db7fd80f659b)

### vvv Baked with custom color setting, exits blocked of with MeshInstances with UV2 and Static GI. Light leaks through the floor.
![image](https://github.com/user-attachments/assets/e115badd-da7b-4fbe-897a-563b2a1fbc47)

### vvv Custom Color also changes the outdoors, which is not the desired effect. The desired effect is a "min light" setting.
![image](https://github.com/user-attachments/assets/8fbd9b0d-b1f0-4b78-a043-b99df588855c)

### vvv Baked the last image after toggling "Indoors". No change, environment hasn't been ignored.
![image](https://github.com/user-attachments/assets/86606f25-1cd2-4636-a54d-9b5d098c63d9)

### Steps to reproduce

- Make a closed room with Blender and add to the project (as CSGs don't work with lightmaps)
- Add an Environment node, Ambient Light to any desired value (for example, Source = Color, Color = White, Energy = 1)
- Add a lightmap, Environment node to Scene, bake.
- Room stays pitch black.

### Minimal reproduction project (MRP)

---

**Comment by AThousandShips** [comment]
This has never been in 4.x, are you talking about something that was available in 3.x?

If it is then this is something that should be a proposal, as this isn't a bug but a missing feature, please open a proposal [here](https://github.com/godotengine/godot-proposals) instead

**Comment by NatePlays95** [comment]
Yeah, I'm thinking of the 3.x feature. A bummer, will look into writing a feature proposal.

I think the "Interior" toggle is an actual bug. Should I open a separate issue just for that and close this one?

**Comment by AThousandShips** [comment]
Open a separate one to keep things focused

Closing this and looking forward to a proposal!

**Comment by Calinou** [comment]
For future reference, see https://github.com/godotengine/godot/pull/50572.
