### ISSUE TITLE
duplicating an animation doesn't copy next auto-queue

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#974]
If you duplicate an animation, the copy should copy everything, including the next auto-queue (in Blend dialog)

also, would be nice if the next auto-queue option was a dropdown menu instead of a text box, unless there's a reason we would want a text box?

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by adolson** [comment]
Yes. The next auto-queue option still does not get copied to the duplicated animation, and it is still a textbox, not a dropdown menu.

**Comment by akien-mga** [comment]
Related to #148, fixing this issue might help fixing the other.
