### ISSUE TITLE
Node Name Casing setting is not applied when creating a new node under Create Root Node

### ISSUE THREAD

**Issue by Jedzkie** [godotengine/godot#97409]
### Tested versions

- Reproducible in v4.3.stable.official (https://github.com/godotengine/godot/commit/77dcf97d82cbfe4e4615475fa52ca03da645dbd8)

### System information

Windows 11 (22631.4169) - Godot v4.3.stable - Vulkan (Forward+) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics

### Issue description

Node name casing setting is not applied if the node is created under `Create Root Node`.

https://github.com/user-attachments/assets/135f5606-7d1e-4179-8ee6-0923355a5368

### Steps to reproduce

- Create a new project
- Set the node name casing in project settings (Editor -> Naming -> Node Name Casing)
- Choose either `camelCase` or `snake_case`
- Create a new node under `Create Root Node`

### Minimal reproduction project (MRP)

[test2.zip](https://github.com/user-attachments/files/17114901/test2.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/87652

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
