### ISSUE TITLE
[Android Editor] Editor displays blank screen on opening project with Mobile Renderer

### ISSUE THREAD

**Issue by 777joe** [godotengine/godot#97403]
### Tested versions

Reproducible in Godot v4.4.dev (4254946de)
Not reproducible in Godot v4.4.dev2

### System information

Godot v4.4.dev (4254946de) - Android 14 - Single-window, 1 monitor - OpenGL ES 3 (Compatibility) - Adreno (TM) 618 -  (8 threads) - Galaxy Tab S6

### Issue description

On the current master branch, on opening/creating a project with the Mobile Renderer selected, the Godot Editor loads with the logo and loading wheel as usual, but then turns competely blank with a grey screen, and becomes unresponsive.
This does not happen with the Compatibility Renderer, or on 4.4.dev2 with the Mobile Renderer.

On master:
![Screenshot_20240924_154342](https://github.com/user-attachments/assets/86ee2faa-6c56-4b15-8d76-6c33de5fbe31)

On 4.4.dev2:
![Screenshot_20240924_154425](https://github.com/user-attachments/assets/1311f4f1-f658-4d69-ad0d-86c440467cba)

### Steps to reproduce

Create a new project or change renderer of existing project to Mobile Renderer.

### Minimal reproduction project (MRP)

Just create a new project with Mobile renderer.

**Comment by AThousandShips** [comment]
This might be the same as:
* https://github.com/godotengine/godot/issues/97341

But without any further info it's hard to tell

**Comment by matheusmdx** [comment]
I can confirm this is the same case as #97341, i get the same error and my bisect also points to the same culprit: #92797

![image](https://github.com/user-attachments/assets/77b75e98-0214-4a4f-8371-fddc1e2827e4)

<br>

Using adb logcat i get a spam of these errors:

```
ERROR: Number of uniform sets is larger than what is supported by the hardware (4).
at: shader_compile_binary_from_spirv (drivers\vulkan\rendering_device_driver_vulkan.cpp:3125)

ERROR: Attempting to bind a descriptor set (4) greater than what the hardware supports (4).
 at: draw_list_bind_uniform_set (servers\rendering\rendering_device.cpp:3937)

ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
at: draw_list_set_push_constant (servers\rendering\rendering_device.cpp:4051)

ERROR: Condition "shader_data.is_empty()" is true.
at: _compile_variant (servers\rendering\renderer_rd\shader_rd.cpp:309)

ERROR: Condition "rid.is_null()" is true. Returning: rid
at: _allocate_from_uniforms (.\servers/rendering/renderer_rd/uniform_set_cache_rd.h:130)

ERROR: No render pipeline was set before attempting to draw.
at: draw_list_draw (servers\rendering\rendering_device.cpp:4070)

ERROR: Attempted to use an unused shader variant (shader is null),
at: get_render_pipeline (.\servers/rendering/renderer_rd/pipeline_cache_rd.h:75)

ERROR: Parameter "shader" is null.
at: uniform_set_create (servers\rendering\rendering_device.cpp:2816)

ERROR: Parameter "uniform_set" is null.
at: draw_list_bind_uniform_set (servers\rendering\rendering_device.cpp:3947)

ERROR: Parameter "pipeline" is null.
at: draw_list_bind_render_pipeline (servers\rendering\rendering_device.cpp:3859)

```

**Comment by AThousandShips** [comment]
Please add this comment in #97341 

Closing this in favour of it
