### ISSUE TITLE
Imported file is not showing in FileSystem

### ISSUE THREAD

**Issue by AdilDevStuff** [godotengine/godot#97401]
### Tested versions

v4.4.dev2.official [97ef3c837]

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) R7 Graphics (Advanced Micro Devices, Inc.; 27.20.20913.2000) - AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G (4 Threads)

### Issue description

When I drag n drop any asset in godot, it doesn't show up inside of the godot's file system, but if I open the directory in file manager, its present there. I have to reload the project again in order to get the import working. The main issue i think is that the `.import` file is not being created for files when file is being drag n dropped. (See the video)

https://github.com/user-attachments/assets/e620ef00-33de-4db3-89ac-640b603a34f8

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
This issue is already solved in master (see #96828 and #96812)
