### ISSUE TITLE
C#: Exported 'long' field gets unnecessarily clamped / overflows via editor

### ISSUE THREAD

**Issue by juse4pro** [godotengine/godot#97402]
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Windows 11, AMD Ryzen 9 7900X (12 Cores)

### Issue description

In a project where I defined an exported field like this:
```
[GlobalClass]
public partial class NewScript : Resource
{
    [Export]
    public long MyExportField;
}
```

and I try to set the value of this field via editor to a large value in long-range like `1067787023969675464` it gets clamped on save to `1067787023969675520`.

When I set the value via code:
```
using Godot;

public partial class Start : Node
{
	[Export] public NewScript MyResource;
	
	public override void _Ready()
	{
		GD.PrintT(1067787023969675464,this.MyResource.MyExportField);

		this.MyResource.MyExportField = 1067787023969675464L;
		
		GD.PrintT(1067787023969675464,this.MyResource.MyExportField);
	}

}
```

the value doesn't get clamped.

Additional side node: When I try to set the value via editor to the Int64 max value `9223372036854775807` it becomes value `-9223372036854775808`. Which I assume is an integer overflow.

The documentation states that exported integer values are stored as 64-bit integers anyway. So the behavior is not expected.

### Steps to reproduce

* Create an empty project
* Create a resource script (NewScript.cs) like this:
```
using Godot;

[GlobalClass]
public partial class NewScript : Resource
{
    [Export]
    public long MyExportField;
}
```
* Create a Node script (Start.cs) like this:
```
using Godot;

public partial class Start : Node
{
	[Export] public NewScript MyResource;
	
	public override void _Ready()
	{
		GD.PrintT(1067787023969675464,this.MyResource.MyExportField);

		this.MyResource.MyExportField = 9223372036854775807L;
		
		GD.PrintT(1067787023969675464,this.MyResource.MyExportField);
	}
}
```
* Create a scene and assign the Start.cs script to the root
* Select newly created scene as start scene
* Try to set the `MyResources` to an embedded resource and set `MyExportField` to a high value like `1067787023969675464`
* Run and check the console

### Minimal reproduction project (MRP)

* Download example project 
[LongExportBug.zip](https://github.com/user-attachments/files/17112322/LongExportBug.zip)
* Run and check the console

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/79633
* https://github.com/godotengine/godot/issues/94686
* https://github.com/godotengine/godot/issues/33095

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
