### ISSUE TITLE
Button text gets cut off when using canvas_items stretch mode and font oversampling

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#97417]
### Tested versions

Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Debian GNU/Linux trixie/sid trixie - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600 (RADV NAVI33) - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

If a `Button` is sized as small as it can be (eg. when using "center" anchors), the final character of the text gets cut off at certain scaling values when using `canvas_items` scaling and font oversampling.

Seems similar to https://github.com/godotengine/godot/issues/81624, but now happening only when there isn't any "extra" space around the text.

![Screenshot_20240924_181621](https://github.com/user-attachments/assets/fc697556-1c19-4a27-89a6-cf96f25dd903)
![Screenshot_20240924_181639](https://github.com/user-attachments/assets/5bd4782f-5edf-4b6b-abfe-62728d90b713)

### Steps to reproduce

1. Set project's stretch mode to `canvas_items`
2. Create a button, give it some text, and center it using anchors
3. Run the project/scene
4. :eyes: Scale the window

### Minimal reproduction project (MRP)

[qui.zip](https://github.com/user-attachments/files/17118000/qui.zip)

**Comment by WhalesState** [comment]
@bruvzg I already have fixed this on a local build, should i open a pull request with the fix ?
