### ISSUE TITLE
Cannot modify CodeHighlighter's dictionary properties in inspector

### ISSUE THREAD

**Issue by Phoenixkaze** [godotengine/godot#97411]
### Tested versions

Reproducible in:

* v4.3.stable.mono.official [77dcf97d8]
* v4.4dev2

Not reproducible in 4.2.1.stable

### System information

Windows 10/11

### Issue description

For some dictionary properties of `CodeHighlighter` like `keyword_colors` and `member_keyword_colors`, I cannot modify them in inspector.

The editor keeps setting the dictionary to an empty dict after modifying the pairs(**when trying to add more than one pair**):

![Godot_v4 3-stable_mono_win64_P0KpBaGgls](https://github.com/user-attachments/assets/beaeb09e-363e-46bb-b19d-a859909ff57e)

I've not come up with any other built-in resources/nodes which have similar properties yet, so I'm not sure if it's specific to `CodeHighlighter`.

### Steps to reproduce

Create a new `CodeHighlighter`
Modify the dictionaries in inspector
Try adding more than one key/value pair

### Minimal reproduction project (MRP)

[codehighlighterdictionaryissue.zip](https://github.com/user-attachments/files/17116156/codehighlighterdictionaryissue.zip)

**Comment by AThousandShips** [comment]
The immediate solution to this is simple but unsure if it has some unintended side effects, will test some and open a PR if it works out

**Comment by AThousandShips** [comment]
Introduced by:
* https://github.com/godotengine/godot/pull/88231

Likely an unforeseen consequence of the changes there, but might be good to check if anything else might have broken because of it

Opening a PR to fix this problem

**Comment by matheusmdx** [comment]
@AThousandShips I think this is the same case as #9564 and if is, that issue already has a pr to fix: #96623

**Comment by AThousandShips** [comment]
Will test that PR and see if it fixes this

**Comment by AThousandShips** [comment]
It does not fix this bug so opening a PR for this
