### ISSUE TITLE
Font glyph contours for TTF are incorrect , OTF renders properly.

### ISSUE THREAD

**Issue by diiiv9** [godotengine/godot#97420]
### Tested versions

- Reproducible in Godot 4.4dev2

### System information

MacOS , 15.0 (24A335) 

### Issue description

`TextServer::font_get_glyph_contours ` can be used to retrieve a font glyph's contours. We can use this to draw a font. The OTF fonts are rendered correctly , however the TTF font **don't** render correctly. The TTF dictionary returned does not follow the convention mentioned in the [source](https://github.com/godotengine/godot/blob/0bcc0e92b3f0ac57d4c4650722f347593a258572/scene/resources/primitive_meshes.cpp#L2722) . The `ContourPointTag` value of `0` is used for a conic , however the TTF  uses it like a cubic.  There are also some points missing (as indicated in the figure) : 
![FontBug](https://github.com/user-attachments/assets/8a9067d3-c8af-4e4d-8af8-97f354e13dbe)

### Steps to reproduce

Run sample project. I have tested this on a few TTF files , all render incorrectly, while the OTF fonts render properly

### Minimal reproduction project (MRP)

[fontbug.zip](https://github.com/user-attachments/files/17118509/fontbug.zip)

**Comment by bruvzg** [comment]
Everything seems to be working as expected, this function return contour points exactly as it's stored in the font.
TTF format do not have any support for the cubic curves (it's OTF only feature), so it's fully expected to only get `1`, `0` type points. Two `0` conic points imply virtual ON point in between OFF points - see https://freetype.org/freetype2/docs/glyphs/glyphs-6.html (this should be added to the function documentation).

**Comment by diiiv9** [comment]
Thanks ! A new ON point  that is the midpoint between two consecutive OFF points  needs to be added , while rendering a Conic (quadratic bezier). There are some other edge I encountered, such the contour may start with one or even two OFF points.

**Comment by diiiv9** [comment]
@bruvzg  Am I right in saying that `Curve2D` in Godot only works for cubic beziers ?
