### ISSUE TITLE
OSX Right-Click (Ctrl-Click) doesn't work.

### ISSUE THREAD

**Issue by fahall** [godotengine/godot#9744]
**Operating system or device - Godot version:**
MacOS Sierra 10.12.5
MacBook Pro (Retina, 15-inch, Late 2013)
Godot Engine v2.1.3.stable.official

**Issue description:**
*Expected Behavior:* `Ctrl-Click` on a node opens context menu. `Ctrl-Click` on OSX should give the same result as Right-Click on Windows. 

*Actual Behavior:* `Ctrl-Click` behaves exactly like `Left-Click` (i.e. holding `Ctrl` while clicking has no effect)

**Steps to reproduce:**

1. Open New Project
2. Add any node to scene.
3. `Ctrl-click` the node in the Scene dock
4. No context menu...

No example project included. Steps to reproduce will work on a new empty project.

**Comment by marcelofg55** [comment]
This should be fixed by #9778, could you confirm it?

**Comment by akien-mga** [comment]
Fixed in 2.1.4.
