### ISSUE TITLE
OS.get_video_adapter_driver_info() returs empty array

### ISSUE THREAD

**Issue by sajibsrs** [godotengine/godot#97445]
### Tested versions

- Version Godot 4.3

### System information

Mac Mini m2, MacOS Sequoia 1.0, Godot 4.3 stable, vulkan

### Issue description

OS.get_video_adapter_driver_info() returns empty array

### Steps to reproduce

Call OS.get_video_adapter_driver_info() anywhere in your script file

### Minimal reproduction project (MRP)

```gdscript
extends Label

var os_name = OS.get_name()
var physical_memory = OS.get_memory_info().physical
var cpu_name = OS.get_processor_name()
var cpu_count = OS.get_processor_count()
var gpu_name = RenderingServer.get_video_adapter_name()
var renderer = OS.get_video_adapter_driver_info()  # <-- Issue here


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	physical_memory = byte_to_mega_byte(physical_memory)


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta: float) -> void:
	var fps = Engine.get_frames_per_second()
	var frame_time = String.num(delta, 4)
	var memory_uses = byte_to_mega_byte(OS.get_static_memory_usage())
	var texts = "FPS: %s
		Time: %s
		OS: %s 
		Memory (MB): total %s, uses %s
		CPU: %s, core %s
		GPU: %s, %s"
	
	set_text(texts % 
		[
			fps, 
			frame_time,
			os_name, 
			physical_memory, memory_uses, 
			cpu_name, cpu_count,
			gpu_name, renderer
		])
		
func byte_to_mega_byte(bytes):
	return bytes / 1024 / 1024

```

**Comment by AThousandShips** [comment]
Yes this is [documented](https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-video-adapter-driver-info):
> This method is only supported on Linux/BSD and Windows when not running in headless mode. On other platforms, it returns an empty array.

**Comment by AThousandShips** [comment]
I'm not sure check the methods in `RenderingServer` to see if any fits

**Comment by Calinou** [comment]
> Is there anyway to get those info on macos? Specially if its renderer name (opengl, vulkan etc)?

Getting the *actual* rendering driver in use (in a way that obeys automatic fallbacks and CLI argument overrides) isn't currently exposed, there's a PR for it: https://github.com/godotengine/godot/pull/85430

You can still read the project setting though: `ProjectSettings.get_setting_with_override("rendering/rendering_device/driver")`

**Comment by sajibsrs** [comment]
@Calinou Thank you so much! Should I close this?

**Comment by Calinou** [comment]
> @Calinou Thank you so much! Should I close this?

Yes, as this limitation is already documented.
