### ISSUE TITLE
"ERROR: Cannot set format, error: 16." on Linux after merge of Camera implementation (#53666), when webcam is busy

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#97454]
### Tested versions

- Reproducible in 4.4.dev (2834dd6a2a4510901c70a98d587045b0f102c8e0) after merge of #53666 
- Not reproducible in 4.3.stable or 4.4.dev2

### System information

Godot v4.4.dev (2834dd6a2) - Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

The following is printed to the terminal output when opening any project on Linux:
```
ERROR: Cannot set format, error: 16.
```

### Steps to reproduce

- Have the webcam busy (e.g. from a Jitsi meeting)
- Open Godot from a terminal
- Open a project

### Minimal reproduction project (MRP)

Any project.

**Comment by akien-mga** [comment]
CC @pkowal1982

**Comment by akien-mga** [comment]
So I must have been testing this while in a meeting yesterday with my webcam enabled. If my webcam is off I don't reproduce the issue.

I adjusted the steps to reproduce. We may consider that this isn't a bug, but the error message should likely be improved to make it clear that the webcam is busy, instead of a cryptic "cannot set format" error.

Additionally, I wonder whether it's correct that we attempt to initialize a camera feed on start even when there's no usage of any camera API in the project. This seems like a potential significant privacy issue here, which my freak out some users, even if we're just checking whether we _can_ use the camera.

**Comment by pkowal1982** [comment]
@akien-mga Thanks for giving it another try. I can reproduce this behavior on Ubuntu, it will be easier to analyze now.

**Comment by pkowal1982** [comment]
Fixing the error I've noticed that CameraFeed::get_format() is not exposed in the APIs.
If it was not intentional probably there should be another small PR for this.
