### ISSUE TITLE
Back and Forward arrows in the script editor have unintuitive behavior

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#97482]
### Tested versions

4.3 dev

### System information

MacOS 13.6.7

### Issue description

<img width="310" alt="Screenshot 2024-09-26 at 10 27 16" src="https://github.com/user-attachments/assets/6f8d9873-80c6-4a59-a352-b80a34f8bd7f">

I don't know if this is a bug or the intended behavior, but the Back and Forward buttons in the scripts editor have very unintuitive behaviors and it is unclear where you'll end up when clicking on them.

I can't even explain how they currently behave because the behavior is completely erratic to me. I think it has to do with the latest script you edited, but that doesn't seem consistent.

**Expected result**
I expect the buttons to navigate through the "shown-script-history" where you can quickly jump between previously shown script tabs. For example:
- I am currently in Script A
- I change script in the scripts list to Script B
- From Script B I Ctrl+click a class name and go to the definition in Script C
- From here I Ctrl+click a native class name and go to the documentation.
- From here I click on Script A again in the script list to the left.

If I now click the back button I expect to go from Script A (where I am currently) -> Documentation -> Script C -> Script B -> Script A. And the same but in reverse if I click Forward.

This behavior would be the most intuitive and also helpful in situations where you quickly want to jump back and forth between two/three scripts.

### Steps to reproduce

Open a few scripts, go between them and use the back and forward buttons. Where you are taken is inconsistent and doesn't necessarily take you back or forward to the latest open script.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/97031
