### ISSUE TITLE
`ERROR: Condition "!windows.has(p_window)" is true.` when showing main scene selection dialog on Linux X11

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#97486]
### Tested versions

- Reproducible in 4.4.dev (a4c1804cab2ace8c7496390132c8cdc019b55078)
- Reproducible in 4.3.stable
- Not reproducible in 4.2.stable
- Seems to have been first introduced in 4.3.dev3

### System information

Godot v4.4.dev (a4c1804ca) - Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

When a project doesn't have a main scene selected, and you press Play / F5, the following dialog is shown:

![image](https://github.com/user-attachments/assets/5f06c88d-8612-4013-931b-728f8475cc91)

If you press "Select", it opens a file dialog to let you pick the main scene, which, at least on Linux X11 (multi-window), triggers the following error:

```
ERROR: Condition "!windows.has(p_window)" is true. Returning: ObjectID()
   at: window_get_attached_instance_id (platform/linuxbsd/x11/display_server_x11.cpp:1879)
```

The dialog still works fine, it's just a cosmetic annoyance.
![image](https://github.com/user-attachments/assets/39c68724-f2c5-4c18-85ca-4b261f621270)

Might be reproducible on Windows and macOS too, but it's possibly DisplayServer dependent.

### Steps to reproduce

- Create new project
- Add a scene but don't set it as main scene
- Press Play
- Click the "Select" button in the dialog asking to pick a main scene

### Minimal reproduction project (MRP)

[new-test-project.zip](https://github.com/user-attachments/files/17147725/new-test-project.zip)

**Comment by Giganzo** [comment]
Sounds similar to this https://github.com/godotengine/godot/issues/95282

**Comment by akien-mga** [comment]
Indeed, consolidating in #95282.
