### ISSUE TITLE
`Sprite2D` plugin can't generate ring shaped `CollisionPolygon2D`

### ISSUE THREAD

**Issue by shahriarlabib000** [godotengine/godot#97485]
### Tested versions

- Reproducible in: 4.3.stable

### System information

Godot v4.3.stable - Android - GLES3 (Compatibility) - Mali-G52 -  (8 Threads)

### Issue description

I was trying to generate a ring shaped collision polygon for my `Sprite2D` but it created a circular polygon shape. It wasn't hollow in the middle like the `Sprite2D`

![Screenshot_2024-09-26-16-00-05-228_org godotengine editor v4](https://github.com/user-attachments/assets/9822b1a8-c518-4e7f-816c-7f245fc42f4e)

### Steps to reproduce

Try to generate a collision polygon 2d for a ring like sprite png

### Minimal reproduction project (MRP)

[ring.zip](https://github.com/user-attachments/files/17146665/ring.zip)

**Comment by AThousandShips** [comment]
This is not, as far as I know, a supported feature, as collision shapes are generally not hollow, does it say anywhere that this is supported or that it will be the result?

**Comment by shahriarlabib000** [comment]
Didn't know it was not supported. I couldn't find anything about hollow shapes in the collisionpolygon2d docs. Do I close the issue?

**Comment by AThousandShips** [comment]
The shape itself supports holes, but the method to decompose a shape into polygons does not normally, so this is related to the way the editor works

I'd say this would be best as a [proposal](https://github.com/godotengine/godot-proposals) unless the editor says it supports this
