### ISSUE TITLE
plugIN undoRedo not working

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#97502]
### Tested versions

4.2

### System information

windows 10 vulkan foward+

### Issue description

undoRedo resets or restarts EditorInspectorPlugin
- runs the function ( _parse_begin ) like the script is starting for the frist time
- undoRedo doesnt seem to work in EditorInspectorPlugin ( the script restarts )

### Steps to reproduce

- create EditorPlugin and get the "get_undo_redo()"   / add a node ( add_custom_type )
- create an EditorInspectorPlugin script
- In add_custom_type Node script add the undo redo from EditorPlugin

### Minimal reproduction project (MRP)

dfdsfsd

**Comment by RedMser** [comment]
You are calling `notify_property_list_changed()` which forces a rebuild of the inspector to show the updated property infos. It is not unexpected behavior, so if you don't want to lose state, your inspector plugin should remember its state in some place (e.g. node metadata, or a singleton).
