### ISSUE TITLE
draw() signal is emitted twice on Control Nodes but not Node2d

### ISSUE THREAD

**Issue by gitsomebit** [godotengine/godot#97507]
### Tested versions

- Reproducable in 4.3 stable
- not present in 4.2 stable

### System information

Windows 10 - Godot 4.3

### Issue description

The draw signal is emitted twice instead of once for Control nodes. 
For Node2d it is still emitted once (like in previous version 4.2 stable).

### Steps to reproduce

create a new scene with a Control node and bind the draw signal to a function. it will emitt twice

```gdscript
extends Control

func _ready() -> void:
	$".".draw.connect(control_is_drawn)

func control_is_drawn() -> void:
	print("control_is_drawn")
```

### Minimal reproduction project (MRP)

MRP: [double_draw_4.3.zip](https://github.com/user-attachments/files/17153996/double_draw_4.3.zip)

**Comment by gitsomebit** [comment]
I did some more investigation to see if other signals have changed. The sorting of container signal changed as well with sorting twice as much as well. 

MRN: [node_sorting.zip](https://github.com/user-attachments/files/17165890/node_sorting.zip)

the output for the same script in 4.2 and 4.3 is:
![4 2](https://github.com/user-attachments/assets/9d7f3c85-6650-48bb-b291-7bf9942fe42d)
![4 3](https://github.com/user-attachments/assets/5b52535b-3b23-4e8f-8030-a7568444f0f0)

This indicates that there was a regression in 4.3, through which all control nodes are drawn twice

**Comment by gitsomebit** [comment]
I did some more investigating and found that the behaviour of the sorting signal changed as well from 4.2 to 4.3 with less sorting taking place in 4.3 (maybe to the detrement of more drawing)

MRP: [node_sorting.zip](https://github.com/user-attachments/files/17166026/node_sorting.zip)

running the MRP will result in diffrent output for 4.2 and 4.3:
![4 2](https://github.com/user-attachments/assets/a9a51349-7410-4dc9-ad2f-33fc1205d319)
![4 3](https://github.com/user-attachments/assets/f7b6c05d-d069-49fb-ae09-b315985128de)

**Comment by AThousandShips** [comment]
Should be fixed by:
* https://github.com/godotengine/godot/pull/97328

Please confirm

**Comment by AThousandShips** [comment]
The double draw is fixed by:
* https://github.com/godotengine/godot/pull/97328

Please open a separate issue for the sorting part
