### ISSUE TITLE
APK doesn't work on mobile devices (constantly splash screen)

### ISSUE THREAD

**Issue by Xs1v3** [godotengine/godot#9750]
**Operating system or device - Godot version:**
Android 4.0.3 - 5.0
Godot 2.1.3 - 2.1.4 (beta) win10 x64

**Issue description:**

The application does not go beyond the screen saver (splashscreen)

**Steps to reproduce:**
export Android from godot 2.1.3 or godot 2.1.4 (beta) -> Try to run (profit)

If you use godot 2.1.2 all works

**Link to minimal example project:**

[godot issue.zip](https://github.com/godotengine/godot/files/1165490/godot.issue.zip)

p.s. sorry for my bad english

**Comment by eon-s** [comment]
Are you using the correct export templates?
Templates need to be the same version as the editor (the best is to use the self contained mode if you want to have many versions).

**Comment by Xs1v3** [comment]
Thank you so much. It's work :). I didn't know that for each version you need to use different templates.

**Comment by Noshyaar** [comment]
I suppose this issue can be closed now?

**Comment by Noshyaar** [comment]
I think only the issue opener and repository members can close an issue.

**Comment by Xs1v3** [comment]
Sorry. I close this issue. Thank you :)
