### ISSUE TITLE
Animation's data in *.tscn file always change keys order in Dictionary

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#97522]
### Tested versions

- Reproducible in v4.4.dev2.official [97ef3c837]

### System information

Windows 11, Vulkan API 1.3.205 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

When save (without any modification) a scene which contains AnimationPlayers, .tscn file always change for the StringName keys of Dictionary has changed. It's not friendly to version control.

<img width="1223" alt="屏幕截图 2024-09-27 112244" src="https://github.com/user-attachments/assets/641f56ae-f1f1-42ce-a5b6-8b80ed201fa8">

### Steps to reproduce

create a scene contains a AnimationPlayer, and make some animation. Save the scene and open the saved tscn file with other txt editor and remember the data( dictionary )'s keys order. Then back to the engine and save the scene again, then recheck the data's keys order.

### Minimal reproduction project (MRP)

NA

**Comment by jinyangcruise** [comment]
Update: not only the data of AnimationLibrary changes keys order, the order between several Animation also changes. It may due to the keys order has changed in AnimationLibrary's data.

<img width="1233" alt="屏幕截图 2024-09-27 115429" src="https://github.com/user-attachments/assets/54cc4837-a903-4868-acd4-52bc284d0e47">

**Comment by AThousandShips** [comment]
Haven't tested in older versions but I suspect this is a regression from:
* https://github.com/godotengine/godot/pull/70096

Similar to:
* https://github.com/godotengine/godot/issues/96889

**Comment by jinyangcruise** [comment]
dev1 is good

**Comment by AThousandShips** [comment]
Then this is likely from that PR, and due to that `StringName` are sorted by pointers, so special treatment needs to be done when serialising this, might need some changes to the core feature

CC @rune-scape

**Comment by AThousandShips** [comment]
Thinking more on this I think this is indeed more serious, and the solution might be to change the serialisation of Dictionaries instead of adding workarounds

**Comment by jinyangcruise** [comment]
I find it's pretty hard to reproduce this issue by a simple MRP with dev2, maybe due to the pointers' creation time are unsure in complex circumstances. Anyway, if  "StringName are sorted by pointers"(in Dictionary?) is true, then it is surely a problem.

**Comment by KoBeWi** [comment]
I was about to report the same bug.
Made MRP:
[animationshuffle.zip](https://github.com/user-attachments/files/17164473/animationshuffle.zip)
Look at the order of animations every time the scene is reopened and saved.

**Comment by dalexeev** [comment]
* Likely related: #58878.

In `.tscn`/`.tres` it's here:

https://github.com/godotengine/godot/blob/76a135926aef1f02f27e4e09093787f2c670956d/core/variant/variant_parser.cpp#L2246-L2248

**Comment by AThousandShips** [comment]
I'll write up a fix for the sorting to make this workable

**Comment by dalexeev** [comment]
See also:

* #96915.

https://github.com/godotengine/godot/blob/76a135926aef1f02f27e4e09093787f2c670956d/core/io/json.cpp#L123-L125

https://github.com/godotengine/godot/blob/76a135926aef1f02f27e4e09093787f2c670956d/core/io/packed_data_container.cpp#L282

**Comment by AThousandShips** [comment]
Will see about a unified fix and will add a helper class, starting in the variant parser code to save it and looking at the remaining cases as well, will initially keep the sorting of `StringName` and `String` apart as opposed to how things were done in #96915 but can change either that approach or change the code in that PR to use the same solution depending on opinions

Will push soon

**Comment by MrModez** [comment]
I'm still experiencing this problem on 4.4 dev3
