### ISSUE TITLE
Nothing appears when drawing vertexes on the ImmediateGeometry node

### ISSUE THREAD

**Issue by Mudley** [godotengine/godot#9753]
**Ubuntu 17.04 - Godot version: Godot 3 - Build: 0962871**

**Issue description:**
The ImmediateGeometry node doesn't seem to be drawing any vertexes that have been set.

**Comment by TwistedTwigleg** [comment]
Probably Related to #9596

**Comment by kubecz3k** [comment]
Closing as a duplicate of https://github.com/godotengine/godot/issues/9596
