### ISSUE TITLE
CollisionPolygon2D doesn't expose an RID property

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#97544]
### Tested versions

4.3

### System information

macos

### Issue description

It is impossible to get the `RID` of a `CollisionPolygon2D` right now. Any other thing has a way to get RID property, which let you access directly the `PhysicsServer2D` if you want with that RID. Except the `CollisionPolygon2D`.

### Steps to reproduce

Create a `CollisionPolygon2D` node.
There is no `get_rid()` property.

### Minimal reproduction project (MRP)

-

NOTE:

I need this as I try to serialize and deserialize the state of the Physics Server, and want a way to match objects after I save them. For this I need to be able to match RID and node path.

**Comment by Ughuuu** [comment]
As a workaround I try to get the RID by doing something like this: 
```gdscript
var parent = node.get_parent()
if parent is CollisionObject2D:
var idx = 0
for child in parent.get_children():
	if child == node:
		break
	idx += 1
rid = PhysicsServer2D.body_get_shape(parent.get_rid(), idx)
```
However this doesn't work for cases where the shape isn't parented to a CollisionObject2D or when it's disabled.

**Comment by smix8** [comment]
A `CollisionPolygon2D` does not have a `get_rid()` function because it has no `RID` as it is not a `CollisionObject2D`.

A CollisionPolygon2D is a helper node for a parent CollisionObject2D node, so it is mostly dysfunctional without such parent.

**Comment by Ughuuu** [comment]
That does not answer the issue however. I am interested in making a custom Physics Server 2D extension that has serializing capabilities. For this I need to match shapes after a scene reload (eg. initially a RigidBody2D has RID 123, then second time has RID 234).
In order to do matching of shapes to know where to reload the state, I use the RID to communicate with the Physics Server. However for the CollisionPolygon2D I have no good way to get that.

So, it would be dysfunctional for UI use case, but for programatic access it would be useful (eg using the RIDs to access the PhysicsServer2D).

**Comment by Ughuuu** [comment]
@rburing: Loop over CollisionObject2D `get_shape_owners` -> if the result of `shape_owner_get_owner` equals your CollisionPolygon2D -> loop over indices less than `shape_owner_get_shape_count` -> use `shape_owner_get_shape` to get a Shape2D.

This works I am able to get the RID's. Also it's nice that the order of polygons is deterministic (Based on owner_id).
