### ISSUE TITLE
DOF Far/Near Blur causes artifacts when glow is enabled

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#9756]
**Operating system or device - Godot version:**
Windows 7 64bit
Godot 3.0 built from July 18th source (although I've seen this in earlier versions)
Running on a GeForce GTX 760

**Issue description:**
When you have both DOF Far Blur (or Near Blur) and Glow enabled, the glow texture becomes corrupted, as seen in the gif below:

![image](https://media.giphy.com/media/3oeHLtzvvp9xro7UD6/giphy.gif)

**Steps to reproduce:**
Just enable DOF Far Blur and Glow at the same time

**Comment by kubecz3k** [comment]
for me on 4fe6b2a6744c4852cd3fdf0bc7a3437f8a16645f with those settings on, on linux and GeForce1060 it looks better but also not good: 
![doof blur](https://user-images.githubusercontent.com/6129594/28500754-238df3c0-6fce-11e7-9169-c7116b409dd8.png)

**Comment by Noshyaar** [comment]
Just wondering, is `glow_bicubic_upscale` enabled? I've seen a similar issue with this option enabled.

**Comment by sketchyfun** [comment]
@kubecz3k this is a separate issue I think. The values need capping otherwise it wraps around and causes the strange colours. If you change the glow mode to Additive, it works, it's just the other modes that are broken at the moment

**Comment by sketchyfun** [comment]
@Noshyaar yes, but if I disable it, I don't get the glow effect at all (it used to work when I tested it many months ago)

**Comment by Noshyaar** [comment]
@kubecz3k That's #9106 I think.

**Comment by vnen** [comment]
Likely fixed by f5277e3. Let us know if it's not the case.
