### ISSUE TITLE
unicode characters did not show on iOS 18 and Mac OS 15

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#97568]
### Tested versions

4.3 stable

### System information

Mac OS 15, iOS 18

### Issue description

after updating to Mac OS 15, unicode characters did not work.
also on iOS 18 the same issue.
before this ,all works fine on both platforms.

### Steps to reproduce

1. add a label
2. set some Chinese characters for the text
3. leave all other properties as default
4. the characters did not show correctly.

### Minimal reproduction project (MRP)

<img width="1433" alt="Screenshot 2024-09-28 at 11 53 24" src="https://github.com/user-attachments/assets/5769c651-7b1c-4ebe-b982-4efc29e5070f">

**Comment by Zireael07** [comment]
Most likely issue with system font and/or system config

**Comment by ByHatcker** [comment]
Something familiar. In my opinion, I have faced such problems. I don't remember the solution anymore, but something has to do with crc tables (if I'm not mistaken)

**Comment by akien-mga** [comment]
Consolidating in #96101, which turned out to be an Apple/FreeType issue.
