### ISSUE TITLE
Dividing 1 results in incorrect numbers.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#97591]
### Tested versions

4.3

### System information

Windows 11 - Vulkan - Nvidia RTX 4070 - intel i5 13600KF

### Issue description

When dividing 1 (in my example I do 1/2) the result is not 0.5, depending on field it can be different results, in the example the result was 0 or so, if some other fields (for example on particles) I got different results (0.001) none of which are correct. I tried couple different numbers but they seem to be fine.
(I don't know if any other numbers or any other operations also give incorrect results since there's infinite number of combinations)

You can check it in the video below:
https://github.com/user-attachments/assets/4812b028-5f94-4929-aa9a-90208fc224da

### Steps to reproduce

Add a Node3D into your scene, go to Transform (or any other number input as far as I can tell), set X to 1/2 and observer a wrong result.

### Minimal reproduction project (MRP)

Not needed.

**Comment by AThousandShips** [comment]
Thank you for your report!

This is not a bug, you are performing integer division, not floating point, you need to use `1/2.0`

See:
* https://github.com/godotengine/godot-proposals/issues/5344
* https://github.com/godotengine/godot-proposals/issues/1888
* https://github.com/godotengine/godot/issues/49579
* https://github.com/godotengine/godot/issues/25856

Please see there
