### ISSUE TITLE
Error compiling module written using Enet in godot 2.1.3

### ISSUE THREAD

**Issue by PerduGames** [godotengine/godot#9759]
Debian - Godot 2.1.3

I am getting several notes and errors when compiling my module written using Enet. I compile the module perfectly, but with godot, I get those errors that are in the file. I do not quite understand what Godot does underneath, so I do not even know where to start fixing things.

[error_comp_module_simplep2p_godot.txt](https://github.com/godotengine/godot/files/1167140/error_comp_module_simplep2p_godot.txt)

**SCsub**

```
# SCsub
Import('env')

module_env = env.Clone()
module_env.add_source_files(env.modules_sources,"*.cpp")
module_env.Append(CXXFLAGS='-lenet')
```
**register_types.cpp**

```
/* register_types.cpp */

#include "register_types.h"
#include "object_type_db.h"
#include "simplep2p.h"

void register_simplep2p_types() {
        ObjectTypeDB::register_type<SimpleP2P>();
}

void unregister_simplep2p_types() {
//not
}
```

**Comment by Faless** [comment]
I think you are binding a method with more than 5 parameters which is not supported in godot 2.1

`error: no matching function for call to 'create_method_bind(int (SimpleP2P::*&)(const char*, int, int, int, int, int, int))'`

There appears to also be other errors in you code eg. `core/method_bind.h:64:10: error: conversion from 'const Variant' to 'const char*' is ambiguous`.

Not really a Godot issue here...

**Comment by PerduGames** [comment]
Yes, there were actually methods with more than 5 parameters, I corrected.

I was being dumb, passing Enet types as a parameter, that would not work, is that in my head I intended to abstract in another class in gd, but I will abstract everything here before then, it will give more work, but it will be worth.

Since I have not yet understood this other "const char conversion" error, I do not get it when compiling separate from godot, what I'm doing in this method is passing a const char * _adress, so the user can give me a host creation address , It takes, I can not get the ip directly, because I do not think only of multiplayer in local network. And I do not really understand these notes with the variant.h class?

[log_comp_godot.txt](https://github.com/godotengine/godot/files/1167372/log_comp_godot.txt)

**Comment by Faless** [comment]
You should use the godot `IP_Address` struct for that.
Anyway, if you are looking for an enet implementation for `2.1` have a look at the `2.1` branch of my enet module (I'm using it for my game, works pretty well):
https://github.com/Faless/godot-enet-better/tree/2.1

If that solution does not fit you, you can still have a look at how I bind the methods and deal with IP addresses and packets there

**Comment by PerduGames** [comment]
There is already an XD module, I will look yes, and probably use it, but for now I really want to see what I wrote working.

Does your module compile in godot 2.1.3?

**Comment by Faless** [comment]
> Does your module compile in godot 2.1.3?

Nope, it needs a patch that is in the current `2.1` main branch so it will be included in `2.1.4`

**Comment by Faless** [comment]
If you feel like cherry-picking:
bd26eacc59cdcd1cb408c736292e0c61b8226010
3044d0aed3f281a4d63d1591c5e82bbf094e0d2a

should be straight forward from 2.1.3-stable tag.

**Comment by PerduGames** [comment]
Thank you, I've compiled here, I'm going to study your module now.

**Comment by kubecz3k** [comment]
@PerduGames I will close this issue since as far as I understand there is no problem with Godot.  Feel free to continue discussion, or reopen/let me know if that's not a case.
