### ISSUE TITLE
Typed functions do not type check correctly when bound with arguments

### ISSUE THREAD

**Issue by mathgeniuszach** [godotengine/godot#97608]
### Tested versions

- Reproducible in 4.4.dev2, 4.3.stable, 4.2.2.stable, 4.1.4.stable, and 4.0.4.stable

### System information

Godot v4.3.stable (77dcf97d8) - NixOS #1-NixOS SMP PREEMPT_DYNAMIC Wed Sep 18 17:24:10 UTC 2024 - X11 - GLES3 (Compatibility)

### Issue description

Consider the following code:
```gdscript
extends Node

func a(data: Array):
	print(data)

func b(data: Array[int]):
	print(data)

func _ready():
	# Calling it works fine
	a([1, 2])
	b([1, 2])

	# Binding and calling the function with the untyped array works
	a.bind([1, 2]).call()

	# Binding and calling the function with the typed array doesn't.
	b.bind([1, 2]).call()
```
Executing it produces this error in the editor:
> Invalid type in function 'Control(Test.gd)::b (Callable)'. Cannot convert argument 1 from Callable to Array.
When the code should not result in any errors.

Similarly, If you use the following code instead, you can get an even funnier message:
```gdscript
func c(function: Callable):
	function.call()

func _ready():
	c.bind(4).call()
```
> Invalid type in function 'Control(Test.gd)::c (Callable)'. Cannot convert argument 1 from Callable to Callable.
These may be different issues - the second bit of code should throw an error, but the error should really be:
> Invalid type in function 'Control(Test.gd)::c (Callable)'. Cannot convert argument 1 from int to Callable. 

### Steps to reproduce

1. Create a function which takes a typed array as an argument
2. Bind an array with the right type to the function and run `.call()` on it.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17177582/test.zip)

**Comment by mathgeniuszach** [comment]
Tested with https://godotengine.github.io/godot-commit-artifacts/ under https://github.com/godotengine/godot/commit/ae45d19ad69d4a23146ab04c85adca00188a0d94 through wine, the issue still seems to exist there. The Linux build failed to compile through nix.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/92215

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by mathgeniuszach** [comment]
@AThousandShips There is the minor detail that the error message always seems to report the type as "Callable" despite what the object is. Which causes weird messages such as "cannot convert Callable to Callable". I'll edit my message down to just that issue instead, unless it can also be consolidated into the other issue as well.

Also, I'm blind. I do search for these issues beforehand with a bunch of keywords but I guess I don't search hard enough...

**Comment by AThousandShips** [comment]
That is arguably part of the same issue, but if it isn't I'd say to open a new issue to be clear what it is

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/issues/97433

**Comment by mathgeniuszach** [comment]
I think I'll leave it be for now, as on further overview you already explicitly mention this in that post.
