### ISSUE TITLE
Terrible memory leak when importing a large git cloned repository.

### ISSUE THREAD

**Issue by cryoboltinteractive** [godotengine/godot#97610]
### Tested versions

Reproducible in - v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2050 (NVIDIA; 32.0.15.5612) - 11th Gen Intel(R) Core(TM) i5-11260H @ 2.60GHz (12 Threads)

### Issue description

A Large Godot Project hosted on a Git server (4 GB of Assets,  >50,000 Files) when cloned and imported without the (.godot) folder, in a machine with 16 GB of RAM will use all system memory and will 100% of the time result in a full system crash, not just the godot Engine. This happens at around 96% to 97% of the import.
Tested on the following Machines
Macbook Pro 15 inch 2017
(Core i7 - 7820HQ, 16GB DDR4 RAM, Radeon Pro 560) (System Crashed) (5 Attempts)
Asus Zepherus G14
(AMD Ryzen 7 6800HS, 16GB DDR5, RTX 3060 ) (BSOD) (4 Attempts)
Asus TUF F15
(Intel Core i7 11260H, 16 GB DDR4, RTX 2050) (System Crashed) (2 Attempts)

Asus TUF F15 (After Upgrade)
(Intel Core i7 11260H, 32 GB DDR4, RTX 2050) (Import Success) (First Attempt)
Desktop 1
(AMD Ryzen 5 5600, 32 GB DDR4, RTX 3070) (Import Success) (First Attempt)
Desktop 2
(AMD Ryzen 5 3600, 32GB DDR4, RTX 2070) (Import Success) (First Attempt)

However even on 32GB of RAM it uses all resources and even after importing, it will continue to use in excess of 22GB RAM
![image](https://github.com/user-attachments/assets/2765235b-d071-4521-9a55-5ef828ef20c6)
but if you restart Godot after importing everything, it will not use more than 2GB of RAM
![image](https://github.com/user-attachments/assets/b693dc56-98bd-49e2-90de-637111accaa7)

### Steps to reproduce

We cannot unfortunately share steps as it is just importing an existing project

### Minimal reproduction project (MRP)

~~We cannot provide an MRP as the licenses on certain assets do not allow us, how ever we are always available on discord call to talk and maybe help rectify the issue.~~

Equivalent MRP is provide below (Comment 5)

**Comment by cryoboltinteractive** [comment]
@Nazarwadim Can you confirm if it was on import? Our issue was raised on importing a projected, you have mentioned on export, so we're just trying to clarify.
On our internal test with the TPS demo, on import it uses 1.4 GB of RAM and on restart it uses ~750MB. Probably not a huge deal, but on large projects this issue is multiplied.

**Comment by Nazarwadim** [comment]
Yes on import. Made a typo

**Comment by cryoboltinteractive** [comment]
Project imported on the Asus G14 with 40GB of RAM, (8GB Soldered + 32GB DIMM), it also used 97% of total RAM to import.
So I guess it uses all the RAM Available? This is kinda concerning as the total project size is under 4GB.

**Comment by cryoboltinteractive** [comment]
[ImportCrashTest.zip](https://github.com/user-attachments/files/17278076/ImportCrashTest.zip)

Created an Equivalent MRP with the same issue, 100 MB project will use more that 6GB of RAM to import and stay at that usage until engine restart. 

Credits Kenney.nl for the CC0 Assets.
The files are similar to how we have our files

The real issue happens when we set the Mesh Paths in the import settings, only then the Insane RAM usage happens.

**Comment by cryoboltinteractive** [comment]
Hi just to add another behavior observed
The RAM usage does go down like after 5 mins after importing.
could be a delay with GC?

**Comment by cryoboltinteractive** [comment]
![image](https://github.com/user-attachments/assets/16e5c110-3105-401e-a296-1950f02c3b3d)
not only is RAM getting maxed out even pagefile (Commited memory) is being hammered.
This is using 4 Synty packs only
even with ufbx, this issue will be a big no no for 3D game develpments.
again this only happens during import, not when using the engine.

**Comment by nikitalita** [comment]
Attempted this myself, the editor froze and I got this in the console output:

```
Blender 4.1.0 (hash 40a5e739e270 built 2024-03-26 00:46:24)
Read prefs: "/Users/nikita/Library/Application Support/Blender/4.1/config/userpref.blend"
Exception in thread Thread-1 (xmlrpc_server):
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 9, in xmlrpc_server
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/xmlrpc/server.py", line 594, in __init__
    socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/socketserver.py", line 472, in server_bind
    self.socket.bind(self.server_address)
    ```
    
Same thing using Blender 3.6:

```
Blender 3.6.17 (hash f26e6dc62a7b built 2024-10-14 23:31:02)
Device with name Apple M2 Pro supports metal minimum requirements
Exception in thread Thread-1 (xmlrpc_server):
Traceback (most recent call last):
  File "/Applications/Blender 3.6.app/Contents/Resources/3.6/python/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Applications/Blender 3.6.app/Contents/Resources/3.6/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 9, in xmlrpc_server
  File "/Applications/Blender 3.6.app/Contents/Resources/3.6/python/lib/python3.10/xmlrpc/server.py", line 605, in __init__
    socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/Applications/Blender 3.6.app/Contents/Resources/3.6/python/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/Applications/Blender 3.6.app/Contents/Resources/3.6/python/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```

Combined with the fact that this is part of a memory leak issue, my first instinct is that it seems to be starting up additional blender processes before the previous processes actually finish; it looks like it doesn't listen for the SIGCHLD signal when those previous processes actually finish, thus becoming zombie processes that stick around in active memory. 
If the processes don't finish fast enough, this causes a race condition where the previous processes are still listening on the port while the next process starts up, causing it to throw the above error.

**Comment by cryoboltinteractive** [comment]
@Nazarwadim , once imported it doesn't use much RAM. The memory usage happens during Import only.
About the the OS.get_static_memory_usage I'm not sure

@nikitalita , our issue happens even with other file formats like glb and fbx (using ufbx).
But thank you for the insights!

**Comment by Nazarwadim** [comment]
I FOUND IT. I will make a PR soon.

**Comment by cryoboltinteractive** [comment]
Congratulations! 
@Nazarwadim You worked real hard on this
So this update will come in 4.4 I'm guessing?

**Comment by Nazarwadim** [comment]
> So this update will come in 4.4 I'm guessing?

Yes
