### ISSUE TITLE
Fire your shitty community manager on X

### ISSUE THREAD

**Issue by anthonywww** [godotengine/godot#97615]
### Tested versions

![image](https://github.com/user-attachments/assets/820fd3ab-4c2e-46f2-9352-7fab9f52bb53)

### System information

X

### Issue description

![image](https://github.com/user-attachments/assets/ef92c043-e911-48ee-bf77-ce3fb36fe251)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/84837a45-1cd4-46a9-9341-243ca899dc25)

### Minimal reproduction project (MRP)

![image](https://github.com/user-attachments/assets/48311885-7c2e-416a-8f58-6f7c8902b1b4)

**Comment by GodotHan** [comment]
Sir, please remain calm. This is the place to discuss code, just as we cannot post personal preferences on official Twitter.

**Comment by QbieShay** [comment]
Blocks and bans are appealed via the Code of Conduct team https://godotengine.org/code-of-conduct/
