### ISSUE TITLE
Can't access ScrollContainer inside PopupMenu OptionButton

### ISSUE THREAD

**Issue by PxlHeartDev** [godotengine/godot#97623]
https://github.com/godotengine/godot/issues/43878#issuecomment-1264782496_
This code doesn't seem to work in v4.3.stable.steam.77dcf97d8

I can't access the guts of an OptionButton. My end goal is to enable `use parent material` or apply the shader material directly.

![image](https://github.com/user-attachments/assets/3dcbd0cd-143e-4300-bacb-2a4829e966c3)
![image](https://github.com/user-attachments/assets/4b7c7ad9-d76c-4b6e-a905-171995ebe3f1)

**Comment by PxlHeartDev** [comment]
Ideally there would be some way to set it so that all nodes use their parent material by default, but being able to access the nodes I need would also work.

**Comment by AThousandShips** [comment]
There's already a proposal for this, consolidating there:
* https://github.com/godotengine/godot-proposals/issues/1859
