### ISSUE TITLE
Godot 4.3 Randomly generating new theme 5+ times

### ISSUE THREAD

**Issue by Inedible-Hulk** [godotengine/godot#97630]
### Tested versions

-Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 32.0.15.6109) - AMD Ryzen 5 3600X 6-Core Processor (12 Threads)

### Issue description

The editor becomes unresponsive for a few seconds, (usually less than 5) most often after a subwindow is opened or when the editor regains focus but sometimes in the middle of typing or making any changes in the editor. When running the project in verbose, these lines appear when the editor becomes responsive.

EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Can keep old icons, copying.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.

![2024-09-29 (1)](https://github.com/user-attachments/assets/db30e742-4665-4d02-bbc1-2b23b7f3de3d)

### Steps to reproduce

- Open the editor

At this point any of the following could trigger this behavior (though not reliably) and the time the editor has remained open seems to be a factor. (The following is meant as an exhaustive list.)
-    Add Nodes
-    Remove Nodes
-    Edit settings in the Inspector
-    Edit Script
-    Change Viewport
-    Switch to other open program and then back to the editor
-    Edit Project Settings

### Minimal reproduction project (MRP)

Not sure if this will help as the problem occurs in _any_ project using in version 4.3 but I will include this in case I'm not seeing something.
[theme-generation-mrp.zip](https://github.com/user-attachments/files/17181626/theme-generation-mrp.zip)

**Comment by bruvzg** [comment]
Should be already fixed in 4.4 - https://github.com/godotengine/godot/pull/95849
