### ISSUE TITLE
TileMapLayer (and TileMap) don't give option to get shapes RID's

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot#97634]
### Tested versions

4.3

### System information

macos

### Issue description

It is impossible to get the `RID` of a `TileMap` right now. Any other thing has a way to get RID property, which let you access directly the `PhysicsServer2D` if you want with that RID. Except the `TileMap`.

### Steps to reproduce

Create a `TileMap` node.
There is no way to get shapes.

NOTE:

I need this as I try to serialize and deserialize the state of the Physics Server, and want a way to match objects after I save them. For this I need to be able to match RID and node path.

### Minimal reproduction project (MRP)

-

**Comment by AThousandShips** [comment]
Please open a [proposal](https://github.com/godotengine/godot-proposals) instead. This is for bugs not missing features
