### ISSUE TITLE
Creating a script/a folder using Rider or adding a new [Export] var using it doesn't cause Godot to refresh its cache.

### ISSUE THREAD

**Issue by CantyCanadian** [godotengine/godot#97650]
### Tested versions

- Reproductible in 4.4 on [multiple machines](https://www.reddit.com/r/godot/comments/1fswj02/comment/lpo3j8d/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
- Not reproductible in 4.3.

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Using the latest version of Rider with the 4.4 dev2 Godot version, I've been creating new folders, files and exported variables. Every time, Godot doesn't recognize the changes and requires a full project reboot to have it detect and import everything. This is only a recent issue, and was unable to reproduce in 4.3.

### Steps to reproduce

1. Create a C# Godot project and open the solution in Rider.
2. Create a script or folder using Rider.
3. Switch to Godot and the file will be missing from the File Explorer, as well as from the Create Node menu (if the script is a new Node).

### Minimal reproduction project (MRP)

Can be achieved using a new project.

**Comment by The-Cyber-Captain** [comment]
Related to #74830 perhaps?

**Comment by CantyCanadian** [comment]
Probably. I tried building the engine with branch 4.3, which seems to have that cherry-picked fix, but it crashes on opening, so I can't really test it.
