### ISSUE TITLE
Exits the editor

### ISSUE THREAD

**Issue by Samuel-serna** [godotengine/godot#97665]
### Tested versions

In the 4.3 stable

### System information

Xiaomi mi 8 lite snapdragon 660

### Issue description

I'm in the 3D tab either adding the player script when suddenly it exits godot

### Steps to reproduce

The problem is not in the code but in the editor

### Minimal reproduction project (MRP)

I just don't understand what you're referring to.

**Comment by clayjohn** [comment]
Can you please provide more information?

Also, please write responses in English (a machine translation is fine). This is an English speaking community, so we ask that everyone use English to interact.

**Comment by AThousandShips** [comment]
Thank you for your report, but there isn't enough information here to do anything with this report, so I am closing this issue

If you provide more information this can be reopened
