### ISSUE TITLE
AStar2D does not return a partial path when the last point is disabled

### ISSUE THREAD

**Issue by ditiem-games** [godotengine/godot#97679]
### Tested versions

- Reproducible: 4.3.stable.official. I suspect it fails in many other versions (I was using 4.2.stable) because I was hunting this bug and I could not demonstrate it till now.

### System information

Windows 10 - Godot 4.3.stable - Forward+

### Issue description

I have a path like A-B-C-D, where C is disabled. I want to compute the path form A to D and get [A, B]. This should be possible by calling `get_id_path` with the third argument (`allow_partial_path`) set to true.

### Steps to reproduce

Here is the code:

```
	var t = AStar2D.new( )
	t.add_point( 13, Vector2( 1, 0 ) )
	t.add_point( 15, Vector2( 2, 0 ) )
	t.add_point( 11, Vector2( 3, 0 ) )
	t.add_point( 10, Vector2( 4, 0 ) )
	t.add_point( 12, Vector2( 5, 0 ) )
	t.add_point( 14, Vector2( 6, 0 ) )

	t.connect_points( 13, 15 )
	t.connect_points( 13, 11 )
	t.connect_points( 11, 10, false )
	t.connect_points( 10, 12 )
	t.connect_points( 12, 14 )

	var ok_path = t.get_id_path( 13, 12 )
	t.set_point_disabled( 12 , true )
	var should_be_empty_path = t.get_id_path( 13, 12 )
	var partial_path = t.get_id_path( 13, 12, true )
	print( "OK_PATH ", ok_path, " should be empty ", should_be_empty_path, " partial ", partial_path )
```

output:
`OK_PATH [13, 11, 10, 12] should be empty [] partial []`

### Minimal reproduction project (MRP)

[astar2d.zip](https://github.com/user-attachments/files/17199997/astar2d.zip)

**Comment by AThousandShips** [comment]
Marked this for cherry picking for 4.3 so it'll be evaluated for that, closing this report, thank you for reporting

**Comment by theashtronaut** [comment]
> Checking the code I saw that @theashtronaut has committed a change to fix it 3 weeks ago. But there is a case that also has to be checked in these lines (get_id_path, around line 774 - I dont know why I cannot past the github reference):
> 
> ```
> if (a == b) {
> 	Vector<int64_t> ret;
> 	ret.push_back(a->id);
> 	return ret;
> }
> ```
> 
> https://github.com/godotengine/godot/blob/e3213aaef5e0e72b8272e65d989d3d8222be17ca/core/math/a_star.cpp#L774C1-L778C3
> 
> The things is that if `!a->enabled` and that `if (a==b)` would not be there, the function would return an empty path, which is not the case.

I'm not sure I understand. Point A = start, point B = end. If point A and point B are the same point, when point A is disabled, point B would be as well since they are the exact same point. Even if the agent is on this disabled point, they're already at their destination and don't need to move to any other node to reach their destination. Which means if you're deciding on it's path, and empty array should make more sense then returning it's current position in the array.

Am I missing something or maybe misunderstanding what you mean?

**Comment by ditiem-games** [comment]
> Am I missing something or maybe misunderstanding what you mean?

You got it correctly. The path from A to A should be empty array.
