### ISSUE TITLE
`step` in gdshader works differently with NaN values between Web and Desktop

### ISSUE THREAD

**Issue by suhankins** [godotengine/godot#97692]
### Tested versions

Godot v4.3.stable (77dcf97d8) 

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 32.0.101.5972) - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 Threads)

### Issue description

`step` in gdshader works differently with NaN values between Web and Desktop.
On desktop `step(0.1, nan)` returns 1, but on Web it returns 0.
![image](https://github.com/user-attachments/assets/f7a2ef38-5123-4759-8a58-2d23cb4edec7)

### Steps to reproduce

1. Create a gdshader that takes a float uniform and uses it in `step` function, i.e.
```gdshader
shader_type canvas_item;

uniform float test = 0.0;

void fragment() {
	COLOR = vec4(step(0.1, test), 0.0, 0.0, 1.0);
}
```
2. Pass NAN to this shader via Gdscript

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17210985/test.zip)

**Comment by clayjohn** [comment]
This is unfortunately expected. Stepping by NaN is undefined behaviour in GLSL which means that GPU driver vendors get to decide how it is handled, Godot has no control over this behaviour.
