### ISSUE TITLE
Godot editor stop PC to go on sleep mode on Windows 11 when openned

### ISSUE THREAD

**Issue by niokasgami** [godotengine/godot#97697]
### Tested versions

It seems that error was always there since Godot V4 

but my current version is : v4.3.stable.mono.official [77dcf97d8]

### System information

OS Name	Microsoft Windows 11 Home - Version	10.0.22631 Build 22631

### Issue description

When using Godot and if I let the editor open , my pc wont go on sleep mode or  save energy mode by itself. 
I need to close the godot editor for my pc to go on sleep mode when I leave it inactive.

What should be expected?
my pc should be able to go on idle sleep mode and consume less energy.

### Steps to reproduce

Open the godot editor
Leave your pc go on idle / sleep mode
the screen will go black but your pc will still be *running* like it was fully running.
(a good example of the error happening my rgb light will not close meaning its not on idle or sleep mode)

### Minimal reproduction project (MRP)

Any new project using the version above will reproduce this bug

**Comment by c6nabors** [comment]
Looks like this is due to https://github.com/godotengine/godot/issues/28039

**Comment by niokasgami** [comment]
> Looks like this is due to #28039

this is a weird behaviour they have yet to fix... how would be a workaround? force mute the editor?

**Comment by c6nabors** [comment]
> > Looks like this is due to #28039
> 
> this is a weird behaviour they have yet to fix... how would be a workaround? force mute the editor?

Currently no workaround. Audio server still runs when nothing is playing

**Comment by AThousandShips** [comment]
Consolidating in the above issue, thank you for reporting
