### ISSUE TITLE
Ternary if/else does not work as expected inside Expression

### ISSUE THREAD

**Issue by Agecaf** [godotengine/godot#97713]
### Tested versions

- Reproducible in: 4.3, 4.2.1, 4.0

### System information

Arch Linux

### Issue description

The ternary if/else operator does not behave as expected inside `Expression`s; it returns the first value no matter what the condition evaluates to.

The expression will parse and execute without throwing errors, but the behavior is different from expressions in GDScript that are not interpreted through `Expression`.

### Steps to reproduce

This is the simplest code that shows it, and can be reproduced by adding it to the `_ready()` method of the main node:

```gdscript
print(0 if false else 1) # prints 1

var expr = Expression.new()
expr.parse("0 if false else 1")
print(expr.execute()) # prints 0 instead of 1
```

And this is another example;
```gdscript
print(0) if false else print(1) # prints 1

var expr = Expression.new()
expr.parse("print(0) if false else print(1)")
expr.execute() # prints 0 instead of 1
```

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/73816
* https://github.com/godotengine/godot/issues/88121

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
