### ISSUE TITLE
Area2D causes huge frame spikes and stutter, attributed to "setup/solve constraints"

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#97715]
### Tested versions

Reproduced in 4.3 stable, 4.2.2. stable (haven't tested other versions)

### System information

macOS, Windows

### Issue description

We noticed our game having serious intermittent stutters in Godot 4.3. They were seemingly random, and checking the profiler I saw large spikes usually in Physics2D category "setup constraints" and occasionally in "solve constraints". I reproduced the issue in a small project consisting of just one Area2D moving around a bunch of other Area2Ds. "run on separate thread" is disabled for physics.

https://github.com/user-attachments/assets/02d3a9b7-70d3-4aa5-a5bb-b0a18828192b

and here's one of the biggest spikes I've seen (this time in Godot 4.2.2)

<img width="814" alt="Screenshot 2024-10-01 at 3 08 17 PM" src="https://github.com/user-attachments/assets/3d3b0fb6-e168-44e8-ba94-8a283477a5ac">

### Steps to reproduce

run MRP, start profiler and check "Physics2D" to see the graph. Within a few minutes you should see some large frame spikes that coincide with the FPS dropping.

### Minimal reproduction project (MRP)

[physics-2d-stutter.zip](https://github.com/user-attachments/files/17216906/physics-2d-stutter.zip)

**Comment by rburing** [comment]
I don't manage to reproduce this on Linux (Ubuntu 24.04.1) on my machine:

![Screenshot_20241002_193813](https://github.com/user-attachments/assets/ab2a9ad3-6cf4-4160-b797-42c33c75a377)

Do you have any program(s) running in the background that could be causing this?

Can you test other machines and/or a Linux (live) distribution?

**Comment by passivestar** [comment]
Not getting spikes, either with or without vsync

Godot v4.3.stable - macOS 14.5.0 - GLES3 (Compatibility) - Apple M1 Max - Apple M1 Max (10 Threads)

<img width="1236" alt="s" src="https://github.com/user-attachments/assets/f31bbeb4-05b4-4225-948c-1cd84fac830f">

**Comment by GuyUnger** [comment]
also no spikes on my windows pc
![Godot_v4 2 2-stable_win64_SfJirj63iw](https://github.com/user-attachments/assets/e1b3f390-a2db-49d4-97d5-758c56cce0b8)

**Comment by djrain** [comment]
Well I'm not sure what was causing it exactly, but after a machine restart the issue seems to be gone. (could've sworn I tried that already). Apologies for the trouble and thanks all for testing!
