### ISSUE TITLE
`rendering/environment/defaults/default_environment` environment isn't applied by default in the editor

### ISSUE THREAD

**Issue by adamscott** [godotengine/godot#97731]
### Tested versions

- Not reproducible in 3.x (tested in 3.6.stable)
- Reproducible in 4.x (tested in both 4.0.4 and 4.4.dev)

### System information

Godot v4.4.dev (8c9139f31) - macOS 14.6.1 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads)

#### 3.x
[default_env_3x.webm](https://github.com/user-attachments/assets/6022d320-e967-49f3-b8cf-5a3587f48eaf)

#### 4.x
[default_env_44.webm](https://github.com/user-attachments/assets/81da5849-5585-4028-9446-051207356b41)

### Steps to reproduce

1. Create a new project
2. Create a new `Environment` resource at the root of the project
3. Set `rendering/environment/defaults/default_environment` to your new environment
4. Modify the default environment resource
5. See that changes in the environment are not applied to the 3D viewport

### Minimal reproduction project (MRP)

[3.x-default-env.zip](https://github.com/user-attachments/files/17230729/3.x-default-env.zip)
[4.x-default-env.zip](https://github.com/user-attachments/files/17230731/4.x-default-env.zip)

**Comment by Calinou** [comment]
Does it work after restarting the editor?

**Comment by adamscott** [comment]
> Does it work after using **Scene > Reload Saved Scene** or restarting the editor?

I tried reloading the editor, with no luck.

**Comment by clayjohn** [comment]
I thought we removed the default environment in 4.0? Is there still code that handles it?

**Comment by adamscott** [comment]
> I thought we removed the default environment in 4.0? Is there still code that handles it?

There's all the code handling the "fallback environment". From what I saw, it's because the editor sets the preview environment as it doesn't see any set environment. The default environment is set as a fallback environment in the RenderingServer (`scenario->fallback_environment`), so it doesn't count and gets overridden.

**Comment by clayjohn** [comment]
Just tested the MRP locally. It seems to be working correctly actually

![image](https://github.com/user-attachments/assets/a651c9dd-4405-4416-96ab-02079f35def6)

**Comment by adamscott** [comment]
@clayjohn Forgot to add that I wanted the result in the editor.

I see that the preview environment popup "replaces" the default environment in the editor.

<img width="569" alt="Capture d’écran, le 2024-10-02 à 12 29 10" src="https://github.com/user-attachments/assets/36a6c0de-36be-4b27-b8f8-be9365db6bde">

But the problem is that the settings clash with toon shaders. (i.e. the sky ambient lighting applies to the model, see the weird shadows in the model)

<img width="420" alt="Capture d’écran, le 2024-10-02 à 12 29 15" src="https://github.com/user-attachments/assets/7474e79d-1c63-470e-ba40-4ca4a4a5fcc9">

**Comment by clayjohn** [comment]
Just turn off the preview environment!

![image](https://github.com/user-attachments/assets/ae565b50-e6f1-4b3b-bd34-28e09ce4efc3)

**Comment by adamscott** [comment]
> Just turn off the preview environment!

<img width="442" alt="Capture d’écran, le 2024-10-02 à 12 37 35" src="https://github.com/user-attachments/assets/29017aba-0720-4ade-a0f0-d5e76bc703af">

😬
