### ISSUE TITLE
Extension singleton not found when running project after exporting with another Godot instance

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#97735]
### Tested versions

Reproducible in 4.4 dev3
Might be a regression, but I didn't test earlier versions.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

I'm exporting project from command line. When I do it while editor is running, the extension gets broken and it won't work when running the project from the editor. In the extension's folder there are some changes with `~` files.

### Steps to reproduce

1. Open the MPR
2. Run it; should be fine
3. Open a terminal in the project's directory (don't close the editor)
4. Export the project with `godot --export-debug "Windows Desktop" --headless`
5. You will see errors in the console about "Failed to open", "Error copying library", "Can't open GDExtension dynamic library" etc.
6. Go back to the editor and run the project
7. Godot complains that singleton does not exist

### Minimal reproduction project (MRP)

[bugstension.zip](https://github.com/user-attachments/files/17231072/bugstension.zip)

**Comment by GGalizzi** [comment]
Having same issue, errors out here https://github.com/godotengine/godot/blob/4c4e67334412f73c9deba5e5d29afa8651418af2/platform/windows/os_windows.cpp#L412

Can't make a new copy for the temp file.
