### ISSUE TITLE
Drag preview is affected by `CanvasLayer` offset

### ISSUE THREAD

**Issue by peter-kish** [godotengine/godot#97748]
### Tested versions

- Reproducible in: v4.4.dev2.official [97ef3c837], v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - X11 - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 Threads)

### Issue description

Dragging a Control node that is located within a CanvasLayer that has an offset results in the drag preview having the same offset:
![Peek 2024-10-02 20-56](https://github.com/user-attachments/assets/de36a4ac-d27a-49be-a434-a93aa2c19c37)

### Steps to reproduce

1. Create a `CanvasLayer` node and set its offset to a non-zero value
2. Create a `Control` node (e.g. `TextureRect`) with the `CanvasLayer` as its (direct or indirect) parent
3. Attach a script to the `Control` node and implement `_get_drag_data`. E.g.:
```gdscript
func _get_drag_data(_at_position: Vector2) -> Variant:
    set_drag_preview(self.duplicate())
    return self
```
4. Run the scene and drag the `Control` node around

### Minimal reproduction project (MRP)

[dragndropbug.zip](https://github.com/user-attachments/files/17234826/dragndropbug.zip)

**Comment by Sauermann** [comment]
Reproducible in v4.0.stable.official [92bee43ad]
