### ISSUE TITLE
Lobby System with Godot 2.2

### ISSUE THREAD

**Issue by ducklin5** [godotengine/godot#9775]
**Windows 7 x64 - Godot version: v2.2**

I'm working on a lobby system so I need all peers to know the name and ID of all other peers. I loosely followed this guide: http://docs.godotengine.org/en/latest/learning/features/networking/high_level_multiplayer.html

**Issue description:**
 rpc("register_player", get_tree().get_network_unique_id(), player_name) was expected to run for every peer on the network, therefore adding the the new player's id and name to all already connected peers but instead it only ran on the server and locally.

[Lobby.zip](https://github.com/godotengine/godot/files/1167515/Lobby.zip)
to test this project file just export the project, then run a single instance of the game and click "Host". Then 2 or 3 instances and click "Join" for each. It is configured to join the server on "127.0.0.1"

**Comment by Calinou** [comment]
Can anyone still reproduce this on 3.2beta or later? If so, please upload a reproduction project and link it here.

**Comment by ducklin5** [comment]
I think this issue can be closed. RPCs work correctly in 3.1.
