### ISSUE TITLE
Inaccurate depth buffer texture?

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#97751]
### Tested versions

- Reproductible in v4.3.stable.steam [77dcf97d8]

### System information

Windows 10 - v4.3.stable.steam [77dcf97d8]

### Issue description

I honestly have no clue where the problem lies, I basically followed this https://www.youtube.com/watch?v=jH0MD8obOCQ for a metaballs-ish approach and I'm manually setting the spheres positions using spawned rigidbodies.
Someone else has followed the exact same process from the video that should supposedly work but did not so I assume something changed from past versions to 4.3.

Camera from far:
![image](https://github.com/user-attachments/assets/bd05f905-f121-4f5c-b401-1013ca41d542)

Camera near:
![image](https://github.com/user-attachments/assets/60978cc3-ad94-426a-a574-92e022cb4c78)

Seen someone on Reddit with the same issue:

https://github.com/user-attachments/assets/53430bec-aaea-4e8e-99ed-690b3a594ed7

Link: https://www.reddit.com/r/godot/comments/1dza1sm/issue_with_reading_depth_buffer_for_raymarching/

### Steps to reproduce

Teste scene and shader included in the minimal reproduction project.

### Minimal reproduction project (MRP)

[metaballs.zip](https://github.com/user-attachments/files/17235835/metaballs.zip)

**Comment by stoofin** [comment]
Try `length(view)` instead of `-view.z` in the shader.  `d` isn't a view-space depth, but a world-space distance, so comparing with depth will only appear correct near the center of the view. `length(view)` should give you a view-space distance to camera instead.

**Comment by wagnerfs** [comment]
@stoofin you're right, that fixed it, thanks a lot!
