### ISSUE TITLE
--main-pack option does not show up in get_cmdline_args()

### ISSUE THREAD

**Issue by Ryhon0** [godotengine/godot#97766]
### Tested versions

4.3

### System information

Godot v4.3.stable.mono unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Sat, 14 Sep 2024 23:49:02 +0000 - X11 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (nvidia; 560.35.03) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Running Godot with the `--main-pack` option does not show up when calling `OS.get_cmdline_args()`. The option is parsed properly as the main pack is executed. To my knowledge, there is no API to get the main pack path, you have to infer it from the executable name or the `--main-pack` option.

### Steps to reproduce

* Run a PCK using `--main-pack`
* Print out the result of `OS.get_cmdline_args()`

### Minimal reproduction project (MRP)

[MainPack.zip](https://github.com/user-attachments/files/17243755/MainPack.zip)

**Comment by KoBeWi** [comment]
Same as #92831
