### ISSUE TITLE
`GraphEdit's connection_layer removed` warning when close editor

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot#97772]
After #96309 every time I close the editor (with opened project) I see following warning:

```
WARNING: GraphEdit's connection_layer removed. This should not be done. If you like to remove all GraphElements from a GraphEdit node, do not simply remove all non-internal children but check their type since the connection layer has to be kept non-internal due to technical reasons.
     at: remove_child_notify (scene/gui/graph_edit.cpp:656)
```

It is not visible in the editor itself but if you run it from the terminal you will definitely see it there which is annoying.

Sometimes (very rare) this error happens even when you only open project but I don't understand what is special conditions cause it at start

**Comment by Chaosus** [comment]
This also happens on editor startup. Full list of error of opening+exited the empty project:

![изображение](https://github.com/user-attachments/assets/857f3c44-bf7c-4a00-a46d-42157218021b)

**Comment by dustdfg** [comment]
I don't get first two errors, but anyway do you see the graph edit warning every time you run project or only sometimes?

**Comment by Chaosus** [comment]
Nvm, I have a damaged project in the list, after removing in from the project manager the output is simple:

![изображение](https://github.com/user-attachments/assets/13a3f7f9-7aae-47e8-b26f-a48a9c4ce267)
