### ISSUE TITLE
Breakpoints width is far too low, making it easily overlooked

### ISSUE THREAD

**Issue by hsvfan-jan** [godotengine/godot#97786]
### Tested versions

4.3 stable

### System information

Godot v4.3.stable - macOS 15.0.0 - Vulkan (Forward+) - integrated Apple M2 Pro - Apple M2 Pro (10 Threads)

### Issue description

When opening the Debugger -> Stack Trace, the width of the Breakpoint channel is so small that it's very hard to see.
<img width="1037" alt="Screenshot 2024-10-03 at 22 26 43" src="https://github.com/user-attachments/assets/6d747abf-9ef5-4340-9c62-0ac9ce8275d4">
Additionally, when the panel width is adjusted, it can be seen that its height is below "Thread" and "Filter Stack Variables"
<img width="669" alt="Screenshot 2024-10-03 at 22 27 41" src="https://github.com/user-attachments/assets/778c617b-1e22-4b11-a817-455e150e55dc">

### Steps to reproduce

Open -> Debugger -> Stack Trace. Then look at it

### Minimal reproduction project (MRP)

New empty project

**Comment by Norrox** [comment]
Can confirm this also happens in master branch

**Comment by kitbdev** [comment]
- will be fixed by https://github.com/godotengine/godot/pull/90439

But could be fixed separately, since that PR is waiting for another that is still in progress.
