### ISSUE TITLE
@export array[ResourceCustom] on exported resource is empty on export build

### ISSUE THREAD

**Issue by pixel-boy** [godotengine/godot#97782]
### Tested versions

The bug seems to appear in version 4.4.dev2 (it's not present in version 4.4.dev1) and still present in 4.4.dev3

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6109) - AMD Ryzen 7 2700X Eight-Core Processor (16 threads)

### Issue description

When an exported resource itself contains an @export Array[ResourceCustom] property the resources assigned to it in the inspector appear when the game is launch through the editor, but in the exported version (debug and release) the array is empty.

### Steps to reproduce

1- Create 2 custom resources (ex: **resource_list.gd** and **resource_embed.gd**)

2 - In **resource_list.gd** add:
`@export var list:Array[ResourceEmbed]`

3 - In the main scene script add:
`@export var resource_list:ResourceList`

4 - Via the inspector add resources in the **list** of the **resource_list**

5- **print** the value of list, in the editor it contains the added resources, in the exported version it will be empty

### Minimal reproduction project (MRP)

[bug_resource_embed.zip](https://github.com/user-attachments/files/17249015/bug_resource_embed.zip)

**Comment by FireCatMagic** [comment]
Can confirm, this is happening to me in my game.
![image](https://github.com/user-attachments/assets/ab9bb3ab-1085-410f-b2b0-7a891306d611)
Had to make them all normal arrays in the meantime
![image](https://github.com/user-attachments/assets/c626cb2e-c949-422b-812e-eec21d0a14be)

**Comment by matheusmdx** [comment]
This is a regression from #96780 and was already fixed by #97817
