### ISSUE TITLE
GeometryInstance3D.transparency overrides GPUParticle3D's alpha color curve (for quad mesh)

### ISSUE THREAD

**Issue by TheYellowArchitect** [godotengine/godot#97783]
### Tested versions

- Reproducible in 4.4 dev2 and dev3. Haven't tested earlier versions but I assume this exists in earlier versions too because `GPUParticles3D` is new

### System information

Linux - Vulkan (Forward+)

### Issue description

I cannot make any particle start opaque and fade into transparency. The color curve -> alpha curve, is completely ignored!
`GeometryInstance3D.transparency` (it exists on the inspector and is clamped between 0 and 1) exists as a flat value for **all** particles within the `GPUParticles3D`, and completely overrides the above alpha curve :sweat: 

I don't even know if this is a bug or its a proposal, as `GPUParticles3D` is quite a fresh feature (introduced in 4.3 if I recall right)

### Steps to reproduce

1. Create a `GPUParticle3D` node.
2. Draw Passes -> Quad Mesh (dont forget to rotate the entire node so the face of the quad faces the camera)
3. Geometry Instance 3D -> Geometry -> Material Override -> Instead of `ShaderMaterial`, make `StandardMaterial3D`
4. Albedo -> Give it a `CompressedTexture2D`
5. Transparency -> Alpha (and cull mode disabled)
6. ParticleProcessMaterial` -> Display -> Color Curves -> Alpha Curve -> Go under 1.0 aka transparent ![alpha-curve](https://github.com/user-attachments/assets/c93cdbed-10f0-471e-9cda-fc80245cf3b0)

8. Keep the `GeometryInstance3D` at default value (0.0)

On step 3, even if I put the `StandardMaterial3D` not under GeometryInstance3D -> Geometry -> Material Override, but as `StandardMaterial3D` to the quad mesh in Draw Passes, the transparency bug persists. Despite having no material override, as seen here:
![quad-mesh-gpu-particles](https://github.com/user-attachments/assets/a3224bbb-6597-41d6-af32-b20871906b62)
![quad-mesh2](https://github.com/user-attachments/assets/292bd772-6a4d-44d2-af01-ca94220f3b85)

### Minimal reproduction project (MRP)

[smoke-grenade-room.zip](https://github.com/user-attachments/files/17249076/smoke-grenade-room.zip)
Arrow keys to zoom out the camera

Btw, as a workaround, I tried changing the world's lighting, in the following way (yet still failed):
Hide (eye icon) the `DirectionalLight3D`, and showing the `OmniLight3D` node named "Ground World Light" which is hidden by default. It makes the visuals look better, but again, it doesnt have transparency, it only becomes black hence fades into the background -_-

**Comment by Galena-Dragon** [comment]
I had a look at your MRP and noticed that the `StandardMaterial3D` you use has `vertex color`->`use as albedo` set to `Off` / `false`.
If you want your `ParticleProcessMaterial`'s `alpha_curve` to affect your particles, `vertex_color_use_as_albedo` needs to be set to `true`

Althought this is written in the `ParticleProcessMaterial`'s docs as a note, the editor itself doesn't give you this warning.

**Comment by TheYellowArchitect** [comment]
Thank you very much, you are right. I didn't notice the folded `vertex color` options. Should I open a new issue, or change the title for this, so as to have an editor warning if you have a GPU particle with alpha color curve, but disabled `use as albedo` (which is by default false) ?
