### ISSUE TITLE
Smooth shadow fading

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9779]
It would be nice to have an option to enable smooth 3D shadow fading. Currently when shadows exceed the configured distance, they abruptly disappear:

![image](https://user-images.githubusercontent.com/1311555/28494383-07de6322-6f2d-11e7-8b26-1e69da5c7afe.png)

Smooth fading in Unity:

![image](https://user-images.githubusercontent.com/1311555/28494403-ba20dccc-6f2d-11e7-9fbb-1de4b9c1d398.png)

**Comment by reduz** [comment]
this should be easy to add, thanks for the reminder

**Comment by Zireael07** [comment]
Yaaay, thanks @reduz
