### ISSUE TITLE
Godot editor preventing mac from sleep 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#97795]
### Tested versions

all versions

### System information

Mac OS 15

### Issue description

after close the lid of the MacBook, it will not sleep when godot edior is running. 
In the activity monitor, the preventing sleep column is yes for godot.

### Steps to reproduce

just open godot and close the MacBook. 

### Minimal reproduction project (MRP)

the MacBook will run all night and get very hot if you just close the lip.

**Comment by RedMser** [comment]
Can you narrow down "all versions" under tested versions? Which is the oldest and the newest ones you've tried?

Also please check both the Project Settings and the Editor Settings for an option called `keep_screen_on` and see if it is set to true or false.

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/28039

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by alexzheng** [comment]
godot 3.6,  4.3

**Comment by alexzheng** [comment]
I have a question: 
I have used godot for years, I just noticed this issue after upgrading to Mac OS 15, it not always keep the fan running and heat the device after close the lid. 
Is it safe to just close the lid with the godot open? will it always drain the power?

**Comment by AThousandShips** [comment]
Please ask in the other issue to keep things in one place
