### ISSUE TITLE
2D mesh drawing is broken

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#97793]
### Tested versions

Bisect: [e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231]

### System information

Godot v4.4.dev (98deb2a00) - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.3699) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

### Issue description

After #90400 drawing 2D meshes (`CanvasItem.draw_mesh()`, `RenderingServer.canvas_item_add_mesh()`, `Polygon2D`, `MeshInstance2D` etc.; haven't tested all) is broken. Some errors are spammed varying a little depending on what is being tried to draw:
```
E 0:00:00:0662   RenderingDevice::render_pipeline_create: Shader vertex input location (0) not provided in vertex input description for pipeline creation.
  <C++ Error>    Condition "!found" is true. Returning: RID()
  <C++ Source>   servers\rendering\rendering_device.cpp:3477 @ RenderingDevice::render_pipeline_create()

E 0:00:00:0662   RendererCanvasRenderRD::CanvasShaderData::_create_pipeline: Condition "pipeline.is_null()" is true.
  <C++ Source>   servers\rendering\renderer_rd\renderer_canvas_render_rd.cpp:1459 @ RendererCanvasRenderRD::CanvasShaderData::_create_pipeline()

E 0:00:00:0662   RenderingDevice::draw_list_bind_render_pipeline: Parameter "pipeline" is null.
  <C++ Source>   servers\rendering\rendering_device.cpp:4087 @ RenderingDevice::draw_list_bind_render_pipeline()

E 0:00:00:0662   RenderingDevice::draw_list_set_push_constant: This render pipeline requires (0) bytes of push constant data, supplied: (16)
  <C++ Error>    Condition "p_data_size != dl->validation.pipeline_push_constant_size" is true.
  <C++ Source>   servers\rendering\rendering_device.cpp:4299 @ RenderingDevice::draw_list_set_push_constant()
```

### Steps to reproduce

↕

### Minimal reproduction project (MRP)

[pipeline-bug.zip](https://github.com/user-attachments/files/17251145/pipeline-bug.zip)

**Comment by DarioSamo** [comment]
See https://github.com/godotengine/godot/pull/97792

**Comment by Lielay9** [comment]
:/ Had I started writing 5 minutes later...
