### ISSUE TITLE
2D MSAA breaks rendering.

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#97800]
### Tested versions

e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231

### System information

Godot v4.4.dev (65f3df592) - Windows 10.0.22631 - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

### Issue description

Bisected to e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231
Running a project with any 2D MSAA setting will cause the screen rendering to break as demonstrated in this screenshot
![godot windows editor dev x86_64_pzu6DHWfXf](https://github.com/user-attachments/assets/38837d43-f1a4-4d08-aff9-308a061fd634)
(2D MSAA 2x)
![godot windows editor dev x86_64_P15ChHlYvV](https://github.com/user-attachments/assets/06da82a4-3cbf-41a1-9f4d-9164a6ce45dc)
(2D MSAA 8x)

It can be observed on Forward+ and Mobile renderers, but does not appear to affect the Compatibility renderer.

### Steps to reproduce

- Open a project
- Set any 2D MSAA render setting in the project settings.
- Restart the editor

### Minimal reproduction project (MRP)

N/A

**Comment by DarioSamo** [comment]
Can confirm the regression on Mac as well, and it presents itself as the 2D elements being semi-transparent. Haven't determined yet where the actual difference shows up however.

**Comment by DarioSamo** [comment]
I've spotted the issue, will make a PR soon.

**Comment by DarioSamo** [comment]
https://github.com/godotengine/godot/pull/97811 fixes the issue for me, could you please confirm if it does for you as well?
