### ISSUE TITLE
EditorPlugin continues to receive input after closing scene

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9783]
Godot 3.0

I don't know if it's expected by design:

1) Select the node my EditorPlugin can handle
2) Now my editor plugin receives events through `forward_spatial_gui_input` 
3) I close my scene without saving
4) My editor plugin still receives events (and logs errors since I expected my node to exist, but now is null)
5) Selecting any other node stops my plugin to receive events (even an empty `Node`).

**Comment by kubecz3k** [comment]
What will happen if you close scene with saving? Is it any different?

**Comment by Zylann** [comment]
It happens too if the scene doesn't have to be saved. I didn' tried when saving but I assume it doesn't matter.

**Comment by Calinou** [comment]
@Zylann Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Zylann** [comment]
It still happens.
Reproduction project: 
[PluginInputAfterNodeDeleted.zip](https://github.com/godotengine/godot/files/4742339/PluginInputAfterNodeDeleted.zip)

**Comment by aaronfranke** [comment]
Does this still occur in the master branch or the latest 4.0 release candidate?

**Comment by akien-mga** [comment]
Seems fixed as of 4.0 RC 3.

Updated MRP:
[PluginInputAfterNodeDeleted.zip](https://github.com/godotengine/godot/files/10802183/PluginInputAfterNodeDeleted.zip)
