### ISSUE TITLE
3D occluders

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9786]
I thought it would be interesting to have a way to cull 3D objects in addition to basic frustum culling.
In busy scenes, it can happen that many things are in the frustum, slowing FPS down, but maybe only half can actually be seen, because they can be hidden by a wall, by a hill, litterally anything.

2.x had Rooms and Portals, but I feel like they are a bit too specific to interiors. If all you need is just a quad to occlude what's behind a wall or a hill, rooms aren't suited for that. Also rooms don't work in 3.0 (I tried to set an Area but it produced an error).
I noted Unity also has this feature, which seems to do a great job, be it for interior or exterior scenes.

An alternative to manually place occluders in a scene is occlusion queries (which work for any kind of scene or procedural terrain), but I don't know if they are doable with the GLES3 renderer.

**Comment by reduz** [comment]
i have on my todo list a bunch of pretty cool culling techniques, but as
always out of time for 3.0

**Comment by Zireael07** [comment]
Bump, any hope of getting occlusion culling in 3D?

**Comment by Dudemanjude** [comment]
@Zireael07 See here, it says it is expected for 3.2. https://www.patreon.com/posts/17595598

**Comment by HeadClot** [comment]
Thanks for the information @Dudemanjude :)

**Comment by name-here** [comment]
Is this still being worked on?  It seems pretty important.

**Comment by clayjohn** [comment]
@name-here it's planned for 4.0

**Comment by HeadClot** [comment]
@clayjohn Who will be working on it for 4.0 or has that not been hammered out yet?

**Comment by clayjohn** [comment]
reduz I guess. Unless there is someone out there who knows how to do it really efficiently and really wants to do.

**Comment by Calinou** [comment]
Closing in favor of #22048, which has more information on the subject.
