### ISSUE TITLE
Is this engine Wokot now ?

### ISSUE THREAD

**Issue by fnaith** [godotengine/godot#97865]
### Tested versions

All Platform - All Version

### System information

All Platform - All Version

### Issue description

I put years on making Godot extension.
But it seems is affacted by politics now. see https://x.com/LifeArtStudios/status/1840230152254509067
And any question well let me banned by your community manager.

### Steps to reproduce

- Use Godot
- Become Wokot

### Minimal reproduction project (MRP)

https://x.com/godotengine/status/1839656658932306395

**Comment by Lielay9** [comment]
Now? Bisected to 0e49da1687bc8192ed210947da52c9e5c5f301bb 
💋💋💋 Always been mega Slayyyyy~~~💅
Just like my favorite woke 🏳️‍🌈LGBTQ+🏳️‍🌈 lesbian⚢ pairing Lyra x Bon Bon from 🦄 My Little Pony™️🦄
I'm sow happye they married  😭😭😭~~

![lyrabon_wedding_by_doraeartdreams_aspy_ddjwvdk-fullview](https://github.com/user-attachments/assets/42308cb3-7692-4140-ad5f-0904db159716)

If you think Wokot®️ unjustly banned you on ✖️ you can msg them privately so they can say sowwy and un🛑 you~~~ (The linked accounts don't seem to belong to you.)

& as much as I ❤️to gush about things on WokeHub (Sowwy 🤪 ehe~) both of us can keep chatting either on ✖️ or any of https://disboard.org/servers/tag/mlp and not waste the time of all [2600+](https://github.com/godotengine/godot/graphs/contributors) contributors who having nothing to do with it.
