### ISSUE TITLE
Lightmapping leaks skylight completely

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#97869]
### Tested versions

- Reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6590) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Ambient skylight leaks through completely when lightmapping, applying a consistent, flat, light blue glow to everything.

In a completely enclosed space:
![Screenshot (51)](https://github.com/user-attachments/assets/7f3258f4-e62f-4454-b2d2-f3952f5b817b)

This is what it looks like inside the enclosed space when using lightmapping:
![Screenshot (52)](https://github.com/user-attachments/assets/8758396c-db1f-46b1-b5fe-0fb140cfb4fd)

For reference, this is what it *should* look like (using SDFGI to show):
![Screenshot (53)](https://github.com/user-attachments/assets/fb46500c-7cc2-4d2f-ad43-7bda01f58328)

### Steps to reproduce

- Create an enclosed space of static objects with lightmap UV2 unwrapped.
- Setup an environment with background mode set to sky.
- Create a directional light and enable shadows.
- Add a lightmap GI node and bake lightmaps.
- Move editor camera inside enclosed space and observe light leaking.

To compare to a reference GI system that *does* handle this correctly, delete the lightmap GI node and enable SDFGI in environment.

### Minimal reproduction project (MRP)

[lightmapleak.zip](https://github.com/user-attachments/files/17268330/lightmapleak.zip)

**Comment by clayjohn** [comment]
What is the cull mode of the box? Could this be a caused by blackface culling?

Also, it's possible that the lightmapper treats everything as it if it has blackface culling enabled, which would be a problem.

**Comment by Jamsers** [comment]
> What is the cull mode of the box

The boxes are just default MeshInstance3D boxes, no custom materials on them or anything. I assume the cull mode is the default "back" mode?

**Comment by spookto** [comment]
Not sure if this helps but setting "reflected_light_source" to disabled in the environment removes the ambient lighting and makes the indoors completely dark.

[Texel Scale = 1]
![image](https://github.com/user-attachments/assets/2c2039b9-9492-4bc3-8242-d8d1cff2725f)
![image](https://github.com/user-attachments/assets/8e1bb4e0-4ee0-44df-9428-929871efff11)

[Texel Scale = 16, reduces light leaking but is excessive and unnecessary]
![image](https://github.com/user-attachments/assets/69d6b78d-3823-448e-81d2-1aceddbf802e)
![image](https://github.com/user-attachments/assets/7e912513-4968-44bc-b008-db43007eaaee)

**Comment by Jamsers** [comment]
Oh that helps a lot, it's not a lightmapping issue then. I've also been able to replicate your fix by adding a reflection probe with origin inside the box, setting `enable_shadows` to on, and making the extents huge to work around the [reflection probe sky leaking](https://github.com/godotengine/godot-proposals/issues/3013) issue

**Comment by Calinou** [comment]
This appears to be within expected bounds relative to the lightmap resolution. The light leaking you're seeing is caused by the reflection (i.e. a lack of specular occlusion), which https://github.com/godotengine/godot/pull/86102 addresses by using the lightmap as a source of specular occlusion.
