### ISSUE TITLE
NoiseTexture3D Index out of bounds crash. Forward+

### ISSUE THREAD

**Issue by actuallyduck** [godotengine/godot#97879]
### Tested versions

Reproducible in v4.4.dev3.official [f4af8201b]
Not reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 threads)

### Issue description

When trying to set density texture of a FogVolume node as NoiseTexture3D it produces the error: 
ERROR: FATAL: Index p_index = 31 is out of bounds (size() = 4).
at: get (./core/templates/cowdata.h:205)

In the project i discovered this it also made a node not found error which i didn't have before.

https://github.com/user-attachments/assets/7914dd6e-4b99-46f5-a767-467d53f3b6c8

### Steps to reproduce

Open a project and create a FogVolume node. Create a FogMaterial and set the density texture to a NoiseTexture3D. 

### Minimal reproduction project (MRP)

[noisecrash.zip](https://github.com/user-attachments/files/17269082/noisecrash.zip)

**Comment by Lielay9** [comment]
Thanks for the MRP and narrowing the versions~! ❤️  Bisected issue to: 0e948fa7e0b23266d2e67a7d09c39ae37699cbe4

**Comment by clayjohn** [comment]
Cc @BlueCube3310
