### ISSUE TITLE
No fixed yet. Godot v2.1.3.stable.official Cannot display CJK properly on Linux. issue #2491

### ISSUE THREAD

**Issue by JunShiozawa** [godotengine/godot#9787]
**Operating system or device - Godot version:**
Operating system:Ubuntu Linux 16.04.2 LTS(64bit)
Intel Celeron G3900(Skylake)Intel x86_64bit
Mozc IME
Godot v2.1.3.stable.official

**Issue description:**

Firstly, I am Japanese. I am not a native speaker of English , So I am sorry if my English is hard to understand.

No fixed yet.Godot v2.1.3.stable.official Cannot display CJK properly on Linux. issue #2491

akien-mga commented on 30 May 2016 say. 

>Fixed by 3e8eb39 \o/

however

It is no fixed yet Godot v2.1.3.stable.official.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by vnen** [comment]
If you copy text from other sources and paste in the editor, does it work? Note that there's no IME support for now. If you are trying in game, make sure your imported font contains the correct Unicode range.

**Comment by JunShiozawa** [comment]
Hi,vnev.

paste in the editor non-ascii "出来ない"

it does not work.

\u51fa\u6765\u306a\u3044

>Note that there's no IME support for now.

This is a serious bottleneck(problem) in non-ascii country(for example Japan).

**Comment by volzhs** [comment]
It does not work by copying & pasting from gedit, but works from chrome. don't know why.

**Comment by JunShiozawa** [comment]
Oh! It works by copying & pasting Japanese character string(non-ascii) from "Chromium for Ubuntu Linux" on "Godot for Linux"!
Thank You volzhs!

**Comment by JunShiozawa** [comment]
I found hint of cause webpage.

https://unix.stackexchange.com/questions/255592/where-is-the-clipboard-file-located

**Comment by JunShiozawa** [comment]
I found hint of fcitx-mozc IME develop webpage.

http://rio.la.coocan.jp/lab/xlib/012xim.htm

http://qiita.com/shibukawa/items/add9a4bb1b1f959aa1fb

**Comment by vnen** [comment]
Godot 3 should have a primary support for IME (Linux only, cf. #9396), the code likely won't be available in the 2.1.x releases though.

> This is a serious bottleneck(problem) in non-ascii country(for example Japan).

Yes, we are all very aware of that. But none of the lead devs work with non-latin writing system. We need contributors from those places to actually fix this issue (it is the same for RTL languages).

Godot *does* support UTF-8, so the characters themselves should not be a problem.

**Comment by JunShiozawa** [comment]
On Godot_v3.0-alpha1_x11.64(Linux 64bit)
This bug was fixed.
I appreciate you.
