### ISSUE TITLE
Cannot move Godot window if previously unfocused

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#97877]
### Tested versions

v4.4.dev3.official

### System information

Godot v4.4.dev3 - Windows 10.0.26100 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 32.0.12011.1036) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 threads)

### Issue description

https://github.com/user-attachments/assets/6c78ef03-3c9b-4d6f-a304-ece52279c1ac

### Steps to reproduce

unfocus any godot window (editor or game)
try to move it

### Minimal reproduction project (MRP)

N/A

**Comment by Hilderin** [comment]
That should be fixed by #95972
