### ISSUE TITLE
OpenGL: Depth fog renders incorrectly in 4.4.dev

### ISSUE THREAD

**Issue by goodbyesquare** [godotengine/godot#97875]
### Tested versions

- Reproducible in Godot 4.4 dev 2 and 4.4 dev 3.
- Not reproducible in Godot 4.3.

### System information

Windows 11, RTX 4080, i9-13900k, Compatibility Renderer

### Issue description

There is a rendering issue with Depth fog that creates a band effect in a circular radius around the camera at certain distances. If the material is textured then it corrupts the texture within the band area. This only affects the compatibility renderer, it doesn't seem to appear in the Forward and Mobile renderers from what I've tested and it doesn't seem to occur in Godot 4.3, just the 4.4 dev versions so I'm guessing some kind of regression happened? It appears in both the editor and in game. I'm honestly surprised nobody else has noticed and reported it as it's extremely obvious.
![DepthFogRenderIssue](https://github.com/user-attachments/assets/a953af51-062a-482d-8138-1111e553c4dc)

### Steps to reproduce

Create a world environment and use depth fog at a specified distance eg. Depth start 50m, Depth end 200m and move the camera around until the halo effect appears. 

### Minimal reproduction project (MRP)

[DepthFogRenderBug.zip](https://github.com/user-attachments/files/17268919/DepthFogRenderBug.zip)

**Comment by SourceOfHTML** [comment]
Still reproduceable on the latest as of now build (v4.4.dev.custom_build [842f98239]), and messing with the numbers makes me think that this is more closely tied to depth_begin, since that more directly affects the band.

The closer depth_end is to depth_begin, the more the band is blurred, which I'm assuming is perfectly normal behavior.

I reckon this was the result of a dev debugging some other issue and forgetting to delete some debugging lines.

**Comment by SourceOfHTML** [comment]
I don't trust myself enough with rendering to continue on this, apologies. Another, more experienced dev will have to take over.

**Comment by matheusmdx** [comment]
Bisecting points to #96413 as the culprit, @Maran23

![image](https://github.com/user-attachments/assets/af21ef30-d494-4a2f-828d-50fc599c13a3)

**Comment by clayjohn** [comment]
Looks like we need to revert #96413 and try again :( Drivers are so finicky.

**Comment by clayjohn** [comment]
This is the same underlying problem as https://github.com/godotengine/godot/issues/96943
