### ISSUE TITLE
OpenGL Compatibility Mode Shadows - Goes Brighter

### ISSUE THREAD

**Issue by wooooooosh** [godotengine/godot#97880]
### Tested versions

4.3

### System information

4.3

### Issue description

When Shadows are enabled on the Sun,

Instead of the shadow area getting darker,

The lit area gets brighter, and goes way bright.

### Steps to reproduce

Use the shadow feature and find out?

### Minimal reproduction project (MRP)

...

**Comment by clayjohn** [comment]
Duplicate of https://github.com/godotengine/godot/issues/90259

Please see the discussion there. For clarity, this is a known limitations of the Compatibility renderer, but this limitation needs better documentation. 

I'll close this issue so that the problem can be tracked in one place.
