### ISSUE TITLE
Right padding missing in `ItemList`

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#97886]
### Tested versions

- Reproducible: master[db66bd3]
- Not reproducible: 4.4.dev3

### System information

Arch Linux

### Issue description

The right padding of `ItemList` is missing in recent builds of master.

| Bad (current) | Good |
|---|---|
|![after](https://github.com/user-attachments/assets/f42cf811-b260-4bc9-abda-6c7cb4eac4bd) | ![before](https://github.com/user-attachments/assets/3ad07206-0dfd-4d6c-9b5f-8450d257d58a) |

Bisected to 6a9e50b941d52cf671626eb4fdb919df3d8ebf28 (#97439)
CC @Gamemap

### Steps to reproduce

Open any EditorFileDialog (e.g., the "Save Scene" dialog) and select an item in the Recent or Favourite list.

### Minimal reproduction project (MRP)

N/A

**Comment by parkour-brbfr** [comment]
Hmm, is that in the new godot 4.4.dev3?

**Comment by Gamemap** [comment]
@timothyqiu Thank you for informing me about the problem. Could you try my pr to see if it fixes the problem correctly?
