### ISSUE TITLE
Unable to build Windows release template (ld.lld: error: duplicate symbol: PKEY_Device_FriendlyName)

### ISSUE THREAD

**Issue by TibAverus** [godotengine/godot#97882]
### Tested versions

4.3-stable 77dcf97d82cbfe4e4615475fa52ca03da645dbd8 pulled from GitHub

### System information

Windows 11 (23H2), llvm-mingw version 19.1.1

### Issue description

Trying to build a release template from source will fail near the end with the following exception:
```
[100%] ERROR: ld.lld: error: duplicate symbol: PKEY_Device_FriendlyName
>>> defined at libdrivers.windows.template_release.x86_64.llvm.a(audio_driver_wasapi.windows.template_release.x86_64.llvm.o)
>>> defined at /home/runner/work/llvm-mingw/llvm-mingw/install/llvm-mingw/x86_64-w64-mingw32/include/functiondiscoverykeys_devpkey.h:21
>>>            libuuid.a(lib64_libuuid_a-uuid.o)
clang-19: error: linker command failed with exit code 1 (use -v to see invocation)

scons: *** [bin\godot.windows.template_release.x86_64.llvm.mono.exe] Error 1
scons: building terminated because of errors.
```

Command used to build:
```
scons platform=windows use_llvm=true use_mingw=yes mingw64_prefix=x86_64-w64-mingw32- arch=x86_64 target=template_release module_mono_enabled=yes
```

### Steps to reproduce

- Clone the godot source files
- Switch to the 4.3-stable tag
- Build using the following command: ```scons platform=windows use_llvm=true use_mingw=yes mingw64_prefix=x86_64-w64-mingw32- arch=x86_64 target=template_release module_mono_enabled=yes```

### Minimal reproduction project (MRP)

Not applicable

**Comment by not6** [comment]
Same issue here on Windows 10 22H2 and llvm-mingw 19.1.2
`scons platform=windows target=template_release use_mingw=yes use_llvm=yes production=yes`

**Comment by not6** [comment]
Builds fine with regular MinGW-w64

**Comment by TibAverus** [comment]
> Builds fine with regular MinGW-w64

Can you tell me what you mean by this? I would really like to get it working as my release is held back by this, as I'm not able to encrypt my assets without a custom release template.

**Comment by not6** [comment]
> > Builds fine with regular MinGW-w64
> 
> Can you tell me what you mean by this? I would really like to get it working as my release is held back by this, as I'm not able to encrypt my assets without a custom release template.

I mean regular MinGW with GCC rather than LLVM/Clang. Builds just fine for me, it just takes a while to link but no errors or any other issues

**Comment by AeioMuch** [comment]
I have the same bug and that's with regular MinGW GCC no LLVM/Clang. It was working before but I guess it probably broke after I updated it ?

It is not hard to workaround tho. Just open `audio_driver_wasapi.cpp` and remove the `PKEY_Device_FriendlyName` define part.

**Comment by roalyr** [comment]
Getting the same error cross-compiling for windows both ways: https://github.com/godotengine/godot/issues/98822
