### ISSUE TITLE
MenuButton Popop id_pressed and index_pressed signals not emitting

### ISSUE THREAD

**Issue by betalars** [godotengine/godot#97889]
### Tested versions

v4.3.stable.custom_build [41b17e249]

### System information

nixos-unstable

### Issue description

I am trying to use the MenuButton to show some menus depending on witch item is being selected by the user. However, none of the signals exposed by the popup seem to emit.

### Steps to reproduce

1. Create a MenuButton
2. add some items to it
3. attach script

```
extends MenuButton

func _ready() -> void:
	mouse_entered.connect(func(): print("mouse_entered"))
	get_popup().id_pressed.connect(func(): print("id_pressed"))
	get_popup().index_pressed.connect(func(): print("id_pressed"))
	get_popup().id_focused.connect(func(): print("id_focused"))
```
EXPECTED:
The print statements are being executed when you run the scene to play with the button.

OBSERVED:
only the `mouse_enter` print shows up

### Minimal reproduction project (MRP)

n/a

**Comment by timothyqiu** [comment]
This is expected. These signals have one argument, but the receiving lambdas accept no arguments.

You should see errors like this:

> ERROR: Error calling from signal 'id_pressed' to callable: 'GDScript::<anonymous lambda>': Method expected 0 arguments, but called with 1.
   at: emit_signalp (core/object/object.cpp:1213)

**Comment by betalars** [comment]
:facepalm:
