### ISSUE TITLE
global_config.h missing

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#9792]
OS Linux, commit 001fe3eac1447ff6f8bd7dc19efca2de4edd8d1d

global_config.h has changed to project_settings.h
But not changed the include in:
script_encryption_key.cpp
global_defaults.cpp

After change it manually, Godot works.

**Comment by Noshyaar** [comment]
script_encryption_key.cpp and global_defaults.cpp are generated files (which should be *.gen.cpp)
Try cleaning your git directory and rebuild.

**Comment by neikeq** [comment]
Yup, just remove the files as mentioned above.
