### ISSUE TITLE
Silent failure on attempting to import non-valid audio files.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#9793]
**Operating system or device - Godot version:**
Linux (Ubuntu 17.04) 64-bit. Godot master pull version 38c417b.

**Issue description:**

Attempting to import a non-valid audio file does not generate any errors or warnings when running a program. It does generate errors/warnings on the command line when initially attempting to import.

It also appears to crash Godot on trying to exit the project and/or program. Reloading the project afterwards appears to have the stream on the AudioStreamPlayer object set to null.

**Steps to reproduce:**
Create a non-valid audio file, add it to a project structure, set up an AudioStreamPlayer with the stream set to said file and set it playing/autoplay.

**Link to minimal example project:**
[Audio_Import_Issues.zip](https://github.com/godotengine/godot/files/1168102/Audio_Import_Issues.zip)

**Comment by Sslaxx** [comment]
Attempting to set the stream to a non-valid file causes errors.

```func _ready():
	$AudioStreamPlayer.stream = preload ("res://Assets/Audio/Sound/I_AM_TEST.ogg")	# Crashes here.
	$AudioStreamPlayer.stream = preload ("res://Assets/Audio/Sound/Act_Clear.ogg")
	$AudioStreamPlayer.play()
	return```

As the source file indicates it crashes at the line indicated.

**Comment by carlosfvieira** [comment]
On current master - 592ce20 can reproduce the silent error when running the application, but can't reproduce the crash of the editor on any situation related to this.

Also, right after setting an invalid stream file, the stream is set to <null> immediately. In the output window we have this errors shown:

![image](https://user-images.githubusercontent.com/8830610/33966568-f7f09af6-e057-11e7-8ab1-69461b893b72.png)

But, this is no different from we have for example, with Sprite... if we try to set an invalid Texture file, is set to <null> and no message is shown also... when running the application there is also no warning, etc...

So, it appears to be normal behavior...

**Comment by akien-mga** [comment]
Can you still reproduce this one in the current master branch? As per @carlosfvieira's comment, it looks like it's now properly reporting the invalid stream?

**Comment by robfram** [comment]
The last [demo](https://github.com/godotengine/godot/issues/9793#issuecomment-317757242) provided running in 184b2fe21bbc5fcd3c577ca6d079f6f5f70b7943 outputs this in console and debug/error window, but it plays correctly the second audio (the good one).

```
ERROR: set_data: Condition ' ogg_stream == __null ' is true.
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:201.
ERROR: instance_playback: Condition ' data == __null ' is true. returned: ovs
   At: modules/stb_vorbis/audio_stream_ogg_vorbis.cpp:137.
ERROR: set_stream: Condition ' stream_playback.is_null() ' is true.
   At: scene/audio/audio_player.cpp:162.
Running
Still running
```

The code is:
```
func _ready():
	$AudioStreamPlayer.stream = preload ("res://Assets/Audio/Sound/I_AM_TEST.ogg")	# Errors here.
	print ("Running")
	$AudioStreamPlayer.stream = preload ("res://Assets/Audio/Sound/Act_Clear.ogg")
	print ("Still running")
	$AudioStreamPlayer.play()
	return
```

**Comment by akien-mga** [comment]
Thanks, looks correct then.

**Comment by akien-mga** [comment]
Actually no, it's still the same. In the editor it doesn't show anything wrong, apart from the fact that clicking playing does nothing.
