### ISSUE TITLE
Glow seems to be broken (regression from 772485c)

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#9797]
**Operating system or device - Godot version:**
Fedora, NVidia GTX900 series, Propietary drivers, Godot version cf286ed28765606fc6834e7fdbaf5550159454b4

**Issue description:**

Enabling glow on 3d scene causes some weird environment tinting artifacts

glow off
![screenshot from 2017-07-23 12-01-42](https://user-images.githubusercontent.com/1103897/28501314-1985d110-6f9f-11e7-871a-adbf95da3278.png)
glow on
![screenshot from 2017-07-23 12-01-32](https://user-images.githubusercontent.com/1103897/28501315-1b1a2670-6f9f-11e7-836c-5ca095a51cb9.png)

**Steps to reproduce:**
Just enable glow, in your environment.

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
Related issue: https://github.com/godotengine/godot/issues/9756

**Comment by Noshyaar** [comment]
Can confirm, issue comes with 772485c.
However, before that commit, glow option makes this artifact (image by kubecz3k)
![image](https://user-images.githubusercontent.com/26753932/28517511-d1338eac-708e-11e7-9710-28cee7dc5747.png)

**Comment by djrm** [comment]
aparently glow works when DOF is enabled

**Comment by reduz** [comment]
what, we reverted?

**Comment by djrm** [comment]
@reduz  im not sure if it was working before under the same conditions.
