### ISSUE TITLE
AnimatedSprite2D played twice

### ISSUE THREAD

**Issue by baoenzhao** [godotengine/godot#97972]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 Super (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 Threads)

### Issue description

AnimatedSprite2D is not set to loop, but sometimes it plays twice. This bug occurs randomly.

![微信截图_20241008212602](https://github.com/user-attachments/assets/8e6774f9-03aa-4975-8b0a-682040b392b6)
![微信截图_20241008212738](https://github.com/user-attachments/assets/04a13948-933e-474a-a63d-2091ded8f443)

The following is test code.
```
var current_frame = 0

func Enter(message: String=""):
    animated_sprite.play('jump_attack')

func _process(delta: float) -> void:
    if current_frame != animated_sprite.frame:
        current_frame = animated_sprite.frame
        print(current_frame)
```

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test and fix, other parts of the configuration is important to know what is going on!

**Comment by baoenzhao** [comment]
My mistake, the frame count has been reset in the signal.

```
func _ready() -> void:
	super()
	character_body.OnReadyJump.connect(_on_ready_jump)
	character_body.OnJustJump.connect(_on_just_jump)

func _on_ready_jump():
	animated_sprite.frame = 0

func _on_just_jump():
	animated_sprite.frame = 1
```
