### ISSUE TITLE
world environment scrolls to top when i enable options

### ISSUE THREAD

**Issue by loafbrr** [godotengine/godot#97973]
### Tested versions

-happens in godot 4.3 stable, does not happen in 4.2 stable and 4.4 dev 3

### System information

windows 10 - godot 4.3 stable  - vulkan forward+

### Issue description

world environment scrolls to top when i enable ssr,ssao,ssil.. etc.

### Steps to reproduce

add world environment, select environment, enable any option, then it scrolls to top

### Minimal reproduction project (MRP)

i upload video 

https://github.com/user-attachments/assets/1c57658d-d0d4-41ab-83d3-ef8049ef876b

https://youtu.be/4KWNeuoB_M8

**Comment by AThousandShips** [comment]
Sounds like:
* https://github.com/godotengine/godot/issues/96489

Which has been fixed and will be cherry picked for a future 4.3.x

Closing as, as you say, the same issue is fixed in 4.4 so should be the same issue and the same solution should solve that as well, when cherry picked
