### ISSUE TITLE
Tabs add_tab make default icon null

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9798]
Is there a reason why Tabs.add_tab is forcing me to add an icon?

`Tabs.add_tab("Test", null)`

Why not Tabs.add_tab(String title, Texture icon=null)

`Tabs.add_tab("Test")`

**Comment by bojidar-bg** [comment]
Seems like someone forgot a DEFVAL on [line 796](https://github.com/godotengine/godot/blob/537cd79fc8f2b6d5f8a7941c58d6bcaed507579f/scene/gui/tabs.cpp#L796). (Compare: [`tabs.h:107`](https://github.com/godotengine/godot/blob/537cd79fc8f2b6d5f8a7941c58d6bcaed507579f/scene/gui/tabs.h#L107))

**Comment by AlexHolly** [comment]
Looks like this woks.
```ClassDB::bind_method(D_METHOD("add_tab", "title", "icon:Texture"), &Tabs::add_tab,DEFVAL(""),DEFVAL(Ref<Texture>()));```
