### ISSUE TITLE
Rendering issues on mac 

### ISSUE THREAD

**Issue by chancemcdonaldsims** [godotengine/godot#97980]
### Tested versions

I only testing with godot 4.3

### System information

mac os 15.0.1 Godot 4.3

### Issue description

Some materials cause graphics issue that are hard to work around. 
![image](https://github.com/user-attachments/assets/b71a79de-d689-482a-a91e-d2cb11dd3194)

### Steps to reproduce

the issues have happed when things involve transparency. In the photo included it is created with CSG volumes. When working with one the graphics issues happen. The artifacts are high frequency and hard to work with. 

### Minimal reproduction project (MRP)

[issue.zip](https://github.com/user-attachments/files/17296396/issue.zip)
 Rotating around scene shows graphic issues. Could be around z fighting issues.

**Comment by AThousandShips** [comment]
Please provide more system information, you can copy this information to your clipboard by using `Help > Copy System Info` at the top of the editor window.

**Comment by chvanin** [comment]
LGBT govno. You engine govno.

**Comment by bruvzg** [comment]
Reproducible on both macOS and Windows. There's some visible Z-fighting between selected CGSBox and resulting shape.

The interference pattern is different (squares on M1 Mac, stripes on NVIDIA/Windows), but this is the same effect.
<img width="388" alt="Screenshot 2024-10-08 200549" src="https://github.com/user-attachments/assets/20d9bb1e-5620-4d8b-9d5b-04227fc3dfb6">

**Comment by chancemcdonaldsims** [comment]
> Reproducible on both macOS and Windows. There's some visible Z-fighting between selected CGSBox and resulting shape.
> 
> The interference pattern is different (squares on M1 Mac, stripes on NVIDIA/Windows), but this is the same effect. <img alt="Screenshot 2024-10-08 200549" width="388" src="https://private-user-images.githubusercontent.com/7645683/374656284-20d9bb1e-5620-4d8b-9d5b-04227fc3dfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDkxNTgsIm5iZiI6MTcyODQwODg1OCwicGF0aCI6Ii83NjQ1NjgzLzM3NDY1NjI4NC0yMGQ5YmIxZS01NjIwLTRkOGItOWQ1Yi0wNDIyN2ZjM2RmYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTczNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAwNDcxY2UwMDAwM2I1Njc3Zjk0YmE3ZWI2Yzg1MzNlNDM3MjE2ZDNhYTQ0MGVkNWY1N2FlZDdmNGJlNTljNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6zokATdT3AsooO_nLFjiOiU9Uust2qAe8yjGzGk86g0">



> Please provide more system information, you can copy this information to your clipboard by using `Help > Copy System Info` at the top of the editor window.

Godot v4.3.stable - macOS 15.0.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

**Comment by chancemcdonaldsims** [comment]
> Reproducible on both macOS and Windows. There's some visible Z-fighting between selected CGSBox and resulting shape.
> 
> The interference pattern is different (squares on M1 Mac, stripes on NVIDIA/Windows), but this is the same effect. <img alt="Screenshot 2024-10-08 200549" width="388" src="https://private-user-images.githubusercontent.com/7645683/374656284-20d9bb1e-5620-4d8b-9d5b-04227fc3dfb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MDkxNTgsIm5iZiI6MTcyODQwODg1OCwicGF0aCI6Ii83NjQ1NjgzLzM3NDY1NjI4NC0yMGQ5YmIxZS01NjIwLTRkOGItOWQ1Yi0wNDIyN2ZjM2RmYjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMTczNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzAwNDcxY2UwMDAwM2I1Njc3Zjk0YmE3ZWI2Yzg1MzNlNDM3MjE2ZDNhYTQ0MGVkNWY1N2FlZDdmNGJlNTljNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6zokATdT3AsooO_nLFjiOiU9Uust2qAe8yjGzGk86g0">

@bruvzg So is it a bug or not? I don't know if this is avoidable but I don't recall any issues with CSG in past. I also had similar rendering issues with skinned meshes in Godot 4.3 when the meshes had transparency enabled.

**Comment by chancemcdonaldsims** [comment]
https://github.com/user-attachments/assets/5abdf3d7-f699-4c2b-9a9b-0f5c15e6c2bb

Just to provide more context this video provide more information on experience. It is actually sickening to watch this effect for me. I have a large monitor 43" and it produces a flashing effect that may effect people with disabilities more (like epilepsy). I actually having to switch to Blender to prototype because I can't endure effect anymore. 

https://github.com/user-attachments/assets/45c102e6-2c04-49a5-8064-3a390059fca3

This is an imported model from mixamo. It has a similar effect so I think this is more than z fighting.

**Comment by bruvzg** [comment]
> So is it a bug or not? 

Yes, I would consider it a bug (just not a macOS specific).

> This is an imported model from mixamo. It has a similar effect so I think this is more than z fighting.

This might be something completely different, in case of `CGSBox` it's likely cause by selection and shape having face in the same plane (both are generated from the same data, so this is expected, we probably should add some offset to the selection), there's no obvious reason for the model case (and seems like no transparency involved), not sure what's going on.

**Comment by kebabskal** [comment]
https://github.com/user-attachments/assets/e238da45-13cc-4573-9b9d-2d0f1227e41e
I'm also affected by this. Makes it very uncomfortable to work with 3D. 
I don't remember having this problem, at least not to this extent, on earlier versions.

**Side note:**
In this particular example I'm using a CSGBox with collision turned on, where the collision shape more or less by definition is going to have coplanar faces. Do we really even need to draw the collision mesh? Even when working correctly I find the collision mesh be distracting and covering up my object. Turning off "Draw Gizmos" also hides the resize handles so that's not an option.

**System information**
Godot v4.4.dev5 - macOS 15.1.1 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M4 (Apple9) - Apple M4 (10 threads)
