### ISSUE TITLE
Reparenting the parent of an imported model stops the `MeshInstance3D` from skinning properly

### ISSUE THREAD

**Issue by sstarbright** [godotengine/godot#97982]
### Tested versions

- Reproducible in v4.4.dev3.official [f4af8201b]
- Not Reproducible in v4.4.dev2.official [97ef3c837]

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3623) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

Only in v4.4.dev3, when you reparent the parent of a node containing an imported model, it will no longer be skinned.
![godot_4 4_dev3_noskin](https://github.com/user-attachments/assets/45156ae0-211b-474b-876e-62015b7fc024)

### Steps to reproduce

1. Open the MRP in both v4.4dev2 and v4.4dev3 and run the project.
2. Make a single mouse click, and the parent node will move to another node in the tree.
3. In v4.4dev2, nothing visible will happen. In v4.4dev3, the model will stop skinning.

### Minimal reproduction project (MRP)

[MRP_ImportedModelReparenting.zip](https://github.com/user-attachments/files/17296667/MRP_ImportedModelReparenting.zip)

**Comment by matheusmdx** [comment]
Bisecting points to #97489 as the culprit, @TokageItLab

![image](https://github.com/user-attachments/assets/08112152-1bc3-4fde-ad1c-38b1b10dfa0d)
