### ISSUE TITLE
Animation detach on scene change. 

### ISSUE THREAD

**Issue by UnderGamer05** [godotengine/godot#98001]
### Tested versions

Godot 4.4.dev3 - Compatibility renderer 

### System information

Android 14

### Issue description

animation get detach from mesh when changeing scene. It also happening when changeing animation player property. But the animation is working well when playing in game. 
![Screenshot_20241009_092135](https://github.com/user-attachments/assets/9b2a25fb-cc66-4ecf-9bb2-4947717746d6)
![Screenshot_20241009_093040](https://github.com/user-attachments/assets/3e18cba3-6baf-41f6-b4fa-3d274bbefcb6)

### Steps to reproduce

Added .glb model animation.
Made it local.
Renamed a animation. 
Changed the scene.

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test and fix

**Comment by UnderGamer05** [comment]
> Please upload an MRP to make this easier to test and fix

Sure. Here is the project. 
[first-person-controller.zip](https://github.com/user-attachments/files/17306674/first-person-controller.zip)
