### ISSUE TITLE
Object#has_user_signal with signal keyword

### ISSUE THREAD

**Issue by rosshadden** [godotengine/godot#9800]
**Operating system or device - Godot version:**
Arch Linux - 3.0 [25678b187]

**Issue description:**
Using `Object#has_user_signal` does not work for signals using the `signal` keyword.  It requires them to be explicitly added via `Object#add_user_signal`.

**Steps to reproduce:**

For example this prints `false`:

```gdscript
signal foo
func _ready():
	print(self.has_user_signal("foo"))
```

while this prints `true`:

```gdscript
signal foo
func _ready():
	self.add_user_signal("foo")
	print(self.has_user_signal("foo"))
```

Of course the `signal foo` line is unnecessary in the second case, but this is the new syntax as I understand it.

**Comment by rosshadden** [comment]
My workaround to avoid redundancy is using `node.get_signal_connection_list("foo").size() > 0`, which does look worse than my example above that uses `add_user_signal`, but I'm trying to use what I think is the newer API for signals and avoid the legacy 1.x way.

**Comment by bojidar-bg** [comment]
Maybe we should add an additional `has_signal` method?

**Comment by Faless** [comment]
> Maybe we should add an additional has_signal method?

What is the difference between a user signal and a script signal? Why do we need 2 different functions?
Can't we register script signals as user signals when initing?

**Comment by reduz** [comment]
The right way to fix this is with node.get_script().has_script_signal() . It was not available in GDScript, so adding it right now..

**Comment by HummusSamurai** [comment]
I'm with @Faless on this and don't understand the user vs script signal distinction.

**Comment by Zylann** [comment]
Same here, just had the same issue when working on a 2.1.4 project, I wonder why there isn't just a `has_signal`...
