### ISSUE TITLE
Debug CanvasItem Redraw is not available

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#98005]
### Tested versions

a657ea42f1e656695f502a0e5f50ea9e0e041c3e

### System information

Godot v4.4.dev (842f98239) - Linux Mint 22 (Wilma) on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.183.01) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 threads)

### Issue description

Debug CanvasItem Redraw is unavailable since #92797.

### Steps to reproduce

Run the editor from the command line with the `--debug-canvas-item-redraw` option.

Or enable `Debug -> Debug CanvasItem Redraw` in the editor menu first, then run the scene.

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
cc @stuartcarnie

**Comment by stuartcarnie** [comment]
I ported the GLES3 code, and see that it isn't supported there either, which is why it didn't come across. I'll take a look to see what is required to re-introduce it to batching.

**Comment by stuartcarnie** [comment]
Re-implemented debug-draw support for batching. I believe this is what it should look like (@Calinou / @clayjohn):

![CleanShot 2024-10-11 at 06 51 47](https://github.com/user-attachments/assets/4a397fac-1e64-4768-b886-77d5dbf4301d)

**Comment by clayjohn** [comment]
@stuartcarnie that's right!

**Comment by stuartcarnie** [comment]
Will be fixed by #97340
