### ISSUE TITLE
Dynamic exported NodePath

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#9801]
Example:
Create hierarchy -
Node A
-Node B
--Node C
Add script to Node A with export(NodePath) var node_c
Assign Node C to the exported node_c var
Reparent Node C so that Node A is the new parent
Current behavior: exported Node Path stays "Node B/Node C"
Suggested behavior: exported NodePath updates to become "Node C"

**Comment by PLyczkowski** [comment]
Candidate for 3.1 maybe?

**Comment by KoBeWi** [comment]
Fixed in 3.1™
