### ISSUE TITLE
2D editor view does not highlight selected nodes when scene extends a Dialog class

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#98011]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5]
- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (Intel Corporation; 30.0.101.1404) - Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 Threads)

### Issue description

When editing a scene that extends AcceptDialog or any of its descendent classes in the 2D view, selecting a node in the Scene tree does not show the red "selected" border around the selected node.

### Steps to reproduce

Create a new Scene from top Menu or FileSystem RBM
Select AcceptDialog as the Root Type
Enter new scene name
Click OK
Double click the new scene in the Filesystem tree
Switch to the Scene tree
Click the "Toggle Visibility" button on the scene root node
Select the 2D editor
Add any child control to the Dialog (e.g. LineEdit)
Select the child control node in the Scene tree

The selected control is not indicated in the 2D editor window

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/79289

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
