### ISSUE TITLE
Property, Method, Interval and Callback Tweeners are missing methods kill, pause and stop

### ISSUE THREAD

**Issue by ssparna** [godotengine/godot#98024]
### Tested versions

- Reproducible in Godot version 4.3

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 32.0.11029.1008) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When trying to tween a nodes position and stopping it I realized that the tween was missing the ```kill()``` method. While the example in the documentation works when using the ```Tween```  class, that class isn't what's created when using ```create_tween().tween_property(...)```  instead a PropertyTweener is created which is missing the ```kill()``` method.
It looks like the ```PropertyTweener```  does not Inherit from the ``` Tween```  class but instead the ```Tweener``` abstract class. The Documentation states that ```Tweener``` is "used by ```Tween```" however the page for ```Tween``` shows the Inheritance hierarchy which does not contain ```Tweener```. I'm also not sure what the ```Tween``` class is actually used for.

### Steps to reproduce

- create a tween and tween any property 
- attempt to stop the tween

### Minimal reproduction project (MRP)

[propertytweener_mrp.zip](https://github.com/user-attachments/files/17310134/propertytweener_mrp.zip)

**Comment by AThousandShips** [comment]
> The Documentation states that Tweener is "used by Tween"

This doesn't imply it derives from `Tween`, in fact it would imply it *isn't*, or it would say so IMO, also the documentation doesn't use `kill` anywhere so not sure what is misleading here?

**Comment by ssparna** [comment]
The documentation implies its use 
![here](https://github.com/user-attachments/assets/2299e170-f435-4263-b17c-0f24b8278a29) and there is no other way to stop a tween from animating.

**Comment by AThousandShips** [comment]
That is very clearly a `Tween` though, not a `Tweener`?

**Comment by AThousandShips** [comment]
We could make this easier by making `Tweener` expose `get_tween`, but that's something for a [proposal](https://github.com/godotengine/godot-proposals)

**Comment by ssparna** [comment]
My problem is that I have no way of stopping the animation whereas in previous version I could in fact call 
```var tween = create_tween().tween_property(...)
...
tween.kill()```
