### ISSUE TITLE
Refraction is broken (regression from 772485c)

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#9803]
**Operating system or device - Godot version:**
Fedora 26, NVidia GTX900 Series, Propietary Driver

**Issue description:**

Enabling Refraction turns the material to an opaque pink color

![screenshot from 2017-07-23 19-59-34](https://user-images.githubusercontent.com/1103897/28504748-cfff55c8-6fe1-11e7-98f2-7a8f8696ba75.png)

**Steps to reproduce:**
Just enable refraction on a non opaque material.

**Link to minimal example project:**

**Comment by vnen** [comment]
Have this problem too and I'm still suffering from #9139.

**Comment by rubenjavier** [comment]
Have the same problem, the ice on the godot-demo-projects for master [3.0] is broken.
Linux Ubuntu 16.04 64bits

**Comment by Noshyaar** [comment]
Can confirm, same driver.
The issue comes with 772485c.

**Comment by djrm** [comment]
This seems to partially work when DOF is enabled:

![peek 2017-07-25 14-30](https://user-images.githubusercontent.com/1103897/28589955-e691fc5e-7145-11e7-9eed-6ee07f4f9c0a.gif)

**Comment by djrm** [comment]
This one was fixed as well, probably by f5277e347df4228fc875acaa3acb9581a30ab43e, im unable to reproduce it.
