### ISSUE TITLE
GLTFDocument loader returns Freed Object at runtime

### ISSUE THREAD

**Issue by huwpascoe** [godotengine/godot#98038]
### Tested versions

4.3

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 960 (NVIDIA; 32.0.15.6081) - Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4 Threads)

### Issue description

GLTFDocument is unable to load scenes at runtime if the gltf file contains "GODOT_single_root".

The resulting node is`<Freed Object>`.

### Steps to reproduce

Save a gltf file with root_node_mode set as default (ROOT_NODE_MODE_SINGLE_ROOT), then load it and call generate_scene.

### Minimal reproduction project (MRP)

[gltfdocsave.zip](https://github.com/user-attachments/files/17319207/gltfdocsave.zip)
![image](https://github.com/user-attachments/assets/965abb5f-e3de-4d09-8abc-acc1dfb6c267)
![image](https://github.com/user-attachments/assets/304bda8b-5c82-40e3-932e-ce759d097eac)

**Comment by aaronfranke** [comment]
Thank you for reporting this bug. This is a regression introduced by me in Godot 4.2 in PR https://github.com/godotengine/godot/pull/81851. I've fixed it in PR #98048 (master), PR #98049 (4.3), and PR #98051 (4.2).
