### ISSUE TITLE
[Master] Creating a new folder inside a subfolder displays the res:// root directory.

### ISSUE THREAD

**Issue by saierXP** [godotengine/godot#98045]
### Tested versions

v4.4.dev.custom_build [4c4e67334]

### System information

win10

### Issue description

Creating a new folder inside a subfolder displays the res:// root directory

![godot-4 4dev-10-10_0OPfSB7Txy](https://github.com/user-attachments/assets/36128b9c-ad6e-4987-b4bd-70174cc4dae5)
Renaming the folder shown in this error will cause a crash.

In addition, minimize the window first and then maximize it, and then return to normal.

Git bisect shows :
- #80473

### Steps to reproduce

Use the latest commit version.
Creates a new folder inside any subfolder.

### Minimal reproduction project (MRP)

Above

**Comment by dalexeev** [comment]
CC @KoBeWi
