### ISSUE TITLE
black screen after Godot 4.3 stable startup

### ISSUE THREAD

**Issue by suupic** [godotengine/godot#98053]
### Tested versions

v4.3.stable、v4.3.stable.mono、v4.2.2.stable.mono、 v4.1.4.stable

### System information

windows 10 22H2 v19045.5011 - AMD RX580 v24.9.1

### Issue description

After launching Godot, all the windows only display a black screen, and buttons can actually be operated (for example, you can open the "Create New Project" window), but they remain black.

![godot2](https://github.com/user-attachments/assets/426c5aae-b1ef-4219-86e6-8579aab89737)

```
PS D:\dev\Godot_v4.3-stable_mono_win64> .\Godot_v4.3-stable_mono_win64_console.exe -v
Godot Engine v4.3.stable.mono.official.77dcf97d8 - https://godotengine.org
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
Native OpenGL API detected: 3.3: ATI Technologies Inc. - Radeon RX 580 Series
Using "winink" pen tablet driver...
Shader 'CanvasSdfShaderGLES3' SHA256: c149263803dc5b859c3141221dfc0c29418e59133256b85a6c81726909946074
Shader 'SkeletonShaderGLES3' SHA256: 26ff81087d64a6287adcbf10b1be2c8ee311cd55b888eb387e392103d2280770
Shader 'ParticlesShaderGLES3' SHA256: 41d6d468ac327bfdbac5f2ffc31770b92d06e3d6842711c6bc42b544bc631337
Shader 'ParticlesCopyShaderGLES3' SHA256: 63d616c97b513a9f1a73a254f79ed202852f2e0f7000d7e51c747437987de689
Shader 'CopyShaderGLES3' SHA256: 5a31a028ea2c2f24617616b25776dff6f6c78b31d61218b4872a20bc3a6f02fd
Shader 'CubemapFilterShaderGLES3' SHA256: c8d881a469f800cdb19fc01313730c7107a2ea774eae5cb75808268f2a6a03cb
Shader 'GlowShaderGLES3' SHA256: fec09c206ea5644e07ff438c27be89770bbd49f58e19d796dafac09ec096356b
Shader 'PostShaderGLES3' SHA256: 4753bf9f05a0ce3f2ecdf5068f97fdd50956c562a026537b94fcb72777843496
Shader 'CanvasShaderGLES3' SHA256: 5a4c7ee5b5b8874fcf508e17d73144852d2a9e58cfe966fad5fc84925add4cc4
Shader 'CanvasOcclusionShaderGLES3' SHA256: 4b4886a946b5de0dd3038ca080ef3e04d3e405180f507e8801cd660b465ddb01
Shader 'SceneShaderGLES3' SHA256: 40ee49f6ead648094897c6a93287d06ebdcf75d18b33ab12ae4de557ce0c0223
Shader 'SkyShaderGLES3' SHA256: fdfcc76ec3c3b24a3683d835230678bd0bafab9655d55f6cc45eaba4b49fcd80
OpenGL API 3.3.0 Core Profile Context 24.9.1.240813 - Compatibility - Using Device: ATI Technologies Inc. - Radeon RX 5s
WASAPI: Activated output_device using IAudioClient3 interface
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: mix_rate = 48000
WASAPI: fundamental_period_frames = 32
WASAPI: min_period_frames = 128
WASAPI: max_period_frames = 480
WASAPI: selected a period frame size of 480
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 480 calculated latency: 10ms

TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
.NET: Initializing module...
Found hostfxr: C:\Program Files\dotnet\host/fxr/8.0.8/hostfxr.dll
.NET: hostfxr initialized
.NET: GodotPlugins initialized
CORE API HASH: 4070621931
EDITOR API HASH: 591096730
EditorSettings: Load OK!
EditorTheme: Generating new theme for the config '66886095'.
EditorTheme: Generating new icons.
EditorTheme: Generating new fonts.
EditorTheme: Generating new styles.
MbedTLS: Some X509 certificates could not be parsed (9 certificates skipped).
Loaded system CA certificates
EditorSettings: Save OK!
```

### Steps to reproduce

just run Godot_v4.3-stable_mono_win64_console.exe -v

### Minimal reproduction project (MRP)

It happened before creating or opening any project, so no MRP

**Comment by SourceOfHTML** [comment]
Could not reproduce, but a line-by-line check of the differences in what the console prints made me realize that this line:
`MbedTLS: Some X509 certificates could not be parsed (9 certificates skipped).`
Does not appear in my version. All other lines are exactly (or almost exactly) the same. Hell, I even have the same graphics card

Any more info you can give while I try to figure this out? Did you do anything between this time and the last time you ran Godot?

**Comment by suupic** [comment]
> Could not reproduce on Windows 10, but a line-by-line check of the differences in what the console prints made me realize that this line: `MbedTLS: Some X509 certificates could not be parsed (9 certificates skipped).` Does not appear in my version. All other lines are exactly (or almost exactly) the same. Hell, I even have the same graphics card
> 
> Any more info you can give while I try to figure this out? Did you do anything between this time and the last time you ran Godot?

Thank you.

I have resolved the issue.

I noticed that some discussions mentioned certain apps on Windows would show black screen during runtime, which was similar to my issue, and they mentioned graphics card drivers.

I restarted into Safe Mode and found that Godot worked normally. There were two AMD software on the system, one of which was AMD Chipset Software v3.10.08, installed in 2020, long overdue for expiration. I don't know why it wasn't removed when I installed the new drivers. So I uninstalled all AMD software and reinstalled amd-software-adrenalin-edition-24.9.1.

After restarting, Godot is now working properly.
