### ISSUE TITLE
`PopupMenu`'s shortcuts do not work with mouse events

### ISSUE THREAD

**Issue by OverloadedOrama** [godotengine/godot#98057]
### Tested versions

- Reproducible in 4.3-stable, 4.4-dev3

### System information

Godot v4.4.dev3 - openSUSE Tumbleweed 20241007 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1060 6GB (nvidia) - AMD Ryzen 5 1600 Six-Core Processor (12 threads)

### Issue description

`PopupMenu`s items completely ignore shortcuts with mouse events, while keyboard and gamepad buttons work as intended. For example, if we add a `InputEventMouseButton` with its `button_index` set to the right mouse button, and then add it to a `Shortcut` that gets added to a `PopupMenu` item, clicking the right mouse button will not activate that item, even though the text next to it does writes "Right Mouse Button".
![image](https://github.com/user-attachments/assets/04f7132a-82fb-4d37-9a38-d4f174abd3f0)

The same issue occurs when adding an `InputEventAction` that contains mouse events. The keyboard and gamepad events work fine, but the mouse ones have no effect. This completely stops us from setting shortcuts such as the mouse thumb buttons, to common actions such as undo and redo. Related issue: https://github.com/Orama-Interactive/Pixelorama/issues/1070

### Steps to reproduce

- Create a scene with a `MenuButton`, and attach a script to it.
- Add the following lines to the script:
```
func _ready() -> void:
	var new_shortcut := Shortcut.new()
	var event := InputEventAction.new()
	event.action = "test"
	new_shortcut.events.append(event)
	get_popup().add_shortcut(new_shortcut, 0)
	get_popup().set_item_text(0, "Test")
	get_popup().id_pressed.connect(_on_id_pressed)


func _on_id_pressed(id: int) -> void:
	print(id, " has been pressed!")
```
- Go to the input map, and add a new action named "test". There, add as many mouse button events and keyboard or gamepad events as you like.
- Run the project, and activate the input actions you set. The keyboard and gamepad events will work fine, but the mouse ones will have no effect.

### Minimal reproduction project (MRP)

[popupmenu-mouse-shortcut.zip](https://github.com/user-attachments/files/17329450/popupmenu-mouse-shortcut.zip)

**Comment by AThousandShips** [comment]
Shortcuts don't support these types, see [the documentation]:
> Called when an InputEventKey, InputEventShortcut, or InputEventJoypadButton hasn't been consumed by _input or any GUI Control item.


This needs to be documented better though

Consolidating in:
* https://github.com/godotengine/godot/issues/90854

Which covers the same broad issue
