### ISSUE TITLE
RichTextLabel BBCode bgcolor covers inline image

### ISSUE THREAD

**Issue by Arkaein** [godotengine/godot#98070]
### Tested versions

- Reproducible in v4.3.stable.mono.official

### System information

Godot v4.3.stable.mono - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated Quadro RTX 4000 (nvidia; 535.183.01) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

When using a BBCode in a RichTextLabel with bgcolor tags wrapping an inline image, the bgcolor completely covers the image

### Steps to reproduce

1. Create a RichTextLabel and toggle bbcode_enabled
2. Insert an image by using the [img] tag
3. Wrap the image in [bgcolor][/bgcolor] tags

See the image covered by a rectangle of the bgcolor.

### Minimal reproduction project (MRP)

[bbcodeimgbgcolorbug.zip](https://github.com/user-attachments/files/17333288/bbcodeimgbgcolorbug.zip)

**Comment by bruvzg** [comment]
Should be fixed in 4.4 (https://github.com/godotengine/godot/pull/96247).

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/96224, which will be fixed in the next 4.4.dev release.
