### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by prfiredragon** [godotengine/godot#98077]
### Tested versions

- Reproducible in: v4.4.dev.custom_build
- not reproducible on : 4.3 Stable

### System information

v4.4.dev.custom_build foward+

### Issue description

Hi, Just to let you know. 

the first problem was that the plugin don't load but with the #98041 now I have the plugin working. but now the fps has drop from 141 in my case to 25. If I am not wrong the issue began after i sync the sources Yesterday.

If i build a test scene with a Terrain 3d Default terrain, a label for de fps and a camera I get 60 fps.

![20241010_20h35m21s_grim](https://github.com/user-attachments/assets/a1e86225-adad-418a-a0b7-dae919a0018e)

### Steps to reproduce

If i build a test scene with a Terrain 3d Default terrain, a label for de fps and a camera I get 60 fps. 

code:
`extends Node3D
@onready var label: Label = $Label

func _process(_delta: float) -> void:
	label.text = ("%s FPS" % str(Engine.get_frames_per_second()))
	pass
`

### Minimal reproduction project (MRP)

[fps-test.zip](https://github.com/user-attachments/files/17336006/fps-test.zip)

**Comment by fire** [comment]
Can you check if this fails on 4.4 dev 3?

**Comment by prfiredragon** [comment]
> Can you check if this fails on 4.4 dev 3?


![20241011_03h24m12s_grim](https://github.com/user-attachments/assets/70992459-5d99-4148-bc36-b483b814d4fb)
![20241011_03h24m23s_grim](https://github.com/user-attachments/assets/d240038f-cac0-459e-b3ab-f492b42f622a)

**Comment by prfiredragon** [comment]
with Engine.set_max_fps(0)

![20241011_03h32m42s_grim](https://github.com/user-attachments/assets/2c2c1963-c852-45fb-a582-aaf370bda6ac)
![20241011_03h35m25s_grim](https://github.com/user-attachments/assets/accc6cdb-af16-43df-95a1-71ca3899a41d)

**Comment by clayjohn** [comment]
Are you comparing a custom build to the official build? Remember that official builds are compiled with many optimizations that you have to specify manually in your scons build command. 

Custom builds are therefore expected to be much slower than stable builds. 

Can you test from a manually compiled version of 4.3 stable to rule out the regression coming from build settings?

**Comment by prfiredragon** [comment]
> Are you comparing a custom build to the official build? Remember that official builds are compiled with many optimizations that you have to specify manually in your scons build command.
> 
> Custom builds are therefore expected to be much slower than stable builds.
> 
> Can you test from a manually compiled version of 4.3 stable to rule out the regression coming from build settings?

![20241011_11h03m01s_grim](https://github.com/user-attachments/assets/6e300abc-7d04-418a-92bc-1d2ff7ecc67a)
![20241011_11h03m22s_grim](https://github.com/user-attachments/assets/0ab5ff53-bf80-4eed-a5af-af1dd9659ce8)

**Comment by prfiredragon** [comment]
![20241011_11h03m01s_grim](https://github.com/user-attachments/assets/158b9a16-5dea-4b99-ab4f-f1652524c58f)
![20241011_11h03m22s_grim](https://github.com/user-attachments/assets/e95d6a78-4ca9-4c27-95de-3b536c79bb6c)

**Comment by prfiredragon** [comment]
![20241011_21h22m58s_grim](https://github.com/user-attachments/assets/981834b3-149b-487b-ac1e-047e770502f2)
![20241011_21h23m12s_grim](https://github.com/user-attachments/assets/c1e8e167-8303-456e-b947-07162916a176)

**Comment by prfiredragon** [comment]
Ok, I changed to MTerrain and now the FPS is the same.
