### ISSUE TITLE
Change window size at runtime will shrink viewport size in android

### ISSUE THREAD

**Issue by AllenDang** [godotengine/godot#98088]
### Tested versions

4.3 Stable

### System information

Android

### Issue description

I'm implementing a viewport setting for my game, to let user select and change the viewport size at runtime.

With following project settings of window
![image](https://github.com/user-attachments/assets/7f0c9d51-9c0e-40a6-b70a-97f03d7a401a)

Change window.size and window.scaling_3d_scale at runtime, will shrink the viewport size, but when I put the game in background and switch back, viewport size will scale to full screen size.

Here is the code I used

```gdscript
        var viewport_width := 960
	var viewport_height := 540
	var scale := 1.0

	match visual:
		HM_VISUAL.VISUAL_LOW:
			viewport_width = 960
			viewport_height = 540
			scale = 1.0
		HM_VISUAL.VISUAL_MED:
			viewport_width = 1280
			viewport_height = 720
			scale = 1.33
		HM_VISUAL.VISUAL_HIGH:
			viewport_width = 1920
			viewport_height = 1080
			scale = 2.0

	var win := get_window()
	win.size = Vector2i(viewport_width, viewport_height)
	win.scaling_3d_scale = scale
```

Here is a video to show the effect

https://github.com/user-attachments/assets/7eaac904-aa4b-4409-8b3d-d739e80e98be

### Steps to reproduce

Like the video shows

1. change the visual to 'low'
2. put the game in background
3. switch back to the game

### Minimal reproduction project (MRP)

[repoissue98088.zip](https://github.com/user-attachments/files/17349086/repoissue98088.zip)

**Comment by Calinou** [comment]
Which Android device model did you test this on, and which rendering method are you using in the project?

Also, I'm curious why you need to change both the viewport size and the 3D scaling property. Typically, you change the viewport size (for 2D games) or the 3D scaling (for 3D games), not both.

**Comment by UnderGamer05** [comment]
> ### Tested versions
> 4.3 Stable
> 
> ### System information
> Android
> 
> ### Issue description
> I'm implementing a viewport setting for my game, to let user select and change the viewport size at runtime.
> 
> With following project settings of window ![image](https://private-user-images.githubusercontent.com/18550/375768233-7f0c9d51-9c0e-40a6-b70a-97f03d7a401a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjI0MzAsIm5iZiI6MTcyODY2MjEzMCwicGF0aCI6Ii8xODU1MC8zNzU3NjgyMzMtN2YwYzlkNTEtOWMwZS00MGE2LWI3MGEtOTdmMDNkN2E0MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE1NTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NjNhMWVhOTQ0ZmQ3ZTgzMmM0ZmRkM2MyNTM1OTRjMjliOTkxOGE4MWMwYTIyYjUyY2E0OWEzMWUxYmJjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bHdnqKOjmyXgAxitTBTt44KaUXlAcAyccWoCwvYqvyo)
> 
> Change window.size and window.scaling_3d_scale at runtime, will shrink the viewport size, but when I put the game in background and switch back, viewport size will scale to full screen size.
> 
> Here is the code I used
> 
> ```
>         var viewport_width := 960
> 	var viewport_height := 540
> 	var scale := 1.0
> 
> 	match visual:
> 		HM_VISUAL.VISUAL_LOW:
> 			viewport_width = 960
> 			viewport_height = 540
> 			scale = 1.0
> 		HM_VISUAL.VISUAL_MED:
> 			viewport_width = 1280
> 			viewport_height = 720
> 			scale = 1.33
> 		HM_VISUAL.VISUAL_HIGH:
> 			viewport_width = 1920
> 			viewport_height = 1080
> 			scale = 2.0
> 
> 	var win := get_window()
> 	win.size = Vector2i(viewport_width, viewport_height)
> 	win.scaling_3d_scale = scale
> ```
> 
> Here is a video to show the effect
> 
>  20241011-211821.mp4 
> ### Steps to reproduce
> Like the video shows
> 
> 1. change the visual to 'low'
> 2. put the game in background
> 3. switch back to the game
> 
> ### Minimal reproduction project (MRP)
> N/A

Provide a example project to test.

**Comment by AllenDang** [comment]
> > ### Tested versions
> > 4.3 Stable
> > ### System information
> > Android
> > ### Issue description
> > I'm implementing a viewport setting for my game, to let user select and change the viewport size at runtime.
> > With following project settings of window ![image](https://private-user-images.githubusercontent.com/18550/375768233-7f0c9d51-9c0e-40a6-b70a-97f03d7a401a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjI0MzAsIm5iZiI6MTcyODY2MjEzMCwicGF0aCI6Ii8xODU1MC8zNzU3NjgyMzMtN2YwYzlkNTEtOWMwZS00MGE2LWI3MGEtOTdmMDNkN2E0MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE1NTUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NjNhMWVhOTQ0ZmQ3ZTgzMmM0ZmRkM2MyNTM1OTRjMjliOTkxOGE4MWMwYTIyYjUyY2E0OWEzMWUxYmJjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bHdnqKOjmyXgAxitTBTt44KaUXlAcAyccWoCwvYqvyo)
> > Change window.size and window.scaling_3d_scale at runtime, will shrink the viewport size, but when I put the game in background and switch back, viewport size will scale to full screen size.
> > Here is the code I used
> > ```
> >         var viewport_width := 960
> > 	var viewport_height := 540
> > 	var scale := 1.0
> > 
> > 	match visual:
> > 		HM_VISUAL.VISUAL_LOW:
> > 			viewport_width = 960
> > 			viewport_height = 540
> > 			scale = 1.0
> > 		HM_VISUAL.VISUAL_MED:
> > 			viewport_width = 1280
> > 			viewport_height = 720
> > 			scale = 1.33
> > 		HM_VISUAL.VISUAL_HIGH:
> > 			viewport_width = 1920
> > 			viewport_height = 1080
> > 			scale = 2.0
> > 
> > 	var win := get_window()
> > 	win.size = Vector2i(viewport_width, viewport_height)
> > 	win.scaling_3d_scale = scale
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is a video to show the effect
> > 20241011-211821.mp4
> > ### Steps to reproduce
> > Like the video shows
> > 
> > 1. change the visual to 'low'
> > 2. put the game in background
> > 3. switch back to the game
> > 
> > ### Minimal reproduction project (MRP)
> > N/A
> 
> Provide a example project to test.

Sure, I added the MVP project in the post, you can also download it here.
[repoissue98088.zip](https://github.com/user-attachments/files/17349088/repoissue98088.zip)

**Comment by UnderGamer05** [comment]
Ok, this is happening with me either.

**Comment by AllenDang** [comment]
Any update?

**Comment by syntaxerror247** [comment]
@AllenDang `window_set_size` is not supported on Android. The viewport size change is a bug. I’ll work on a fix and submit a PR soon.
