### ISSUE TITLE
Compiling Godot Master "ar.exe" error

### ISSUE THREAD

**Issue by X-DOOM-TV** [godotengine/godot#98087]
### Tested versions

Godot master-branch 4.4

### System information

Window 7 x64 Bit

### Issue description

- I Use Mingw64 13.2.0 To Compile Godot I Installed From WinLabs: https://winlibs.com
- When Run : scons platform=windows target=template_release arch=x86_64 use_mingw=yes use_llvm=yes
- At First Give Me Warning : WARNING: Couldn't parse version of `ar`.
- Then Cruch.
![Sans titre](https://github.com/user-attachments/assets/5052937e-9f25-4124-a109-73fd5f864095)
When I Selecte Branch 4.3 And Compile It I Don,t See Previews Errors

### Steps to reproduce

# A first-level heading
Try Change "ar.exe" Argument

### Minimal reproduction project (MRP)

Godot Source Code

**Comment by AThousandShips** [comment]
See:
* https://github.com/godotengine/godot/pull/96407#issuecomment-2380594553

In the meantime you can update mingw as this is seemingly a bug in mingw that has been solved in recent versions
