### ISSUE TITLE
Android Editor: FPS and GPU Time doesn't update on Android Editor. 

### ISSUE THREAD

**Issue by UnderGamer05** [godotengine/godot#98096]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Android 11 - Compatibility renderer

### Issue description

![Screenshot_20241011_220457](https://github.com/user-attachments/assets/35baec3d-a71a-41e0-8a67-eb41d4871e3c)

FPS and GPU Time is not updating. This happing with most of the android device. 

### Steps to reproduce

enabled view frame time. 

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
> 100,000 FPS? Some people have said that mobile phones/tablets would totally replace laptops and desktop, but I didn't think it would be so soon.

This happens because GPU time reporting doesn't work on Android (at least in OpenGL), and the GPU time readout is clamped to 0.01 ms to avoid division by zero.

https://github.com/godotengine/godot/pull/75512 would partially address this issue.
