### ISSUE TITLE
No value/invalid value serialized for unset exports with range

### ISSUE THREAD

**Issue by nanodeath** [godotengine/godot#98092]
### Tested versions

Reproduces in 4.3.stable.mono and 4.4.dev3.mono.

### System information

Godot v4.4.dev3.mono - Ubuntu 22.04.5 LTS 22.04 on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Mobile) - integrated AMD Unknown (RADV GFX1103_R1) - AMD Ryzen 9 7940HS w/ Radeon 780M Graphics (16 threads)

### Issue description

If the editor shows a value for an exported field, I expect to get that same value when reading it from code. However, this isn't the behavior we get for `@export_range`-type where the lower-bound doesn't match the default null value for that type. For example, if you create an int export with a range [1,12], it'll show `1` in the editor, but `0` if you read it from code. This is very misleading behavior as a user. This is verified (and in the MRP) for GDScript, C#, and C# custom resources.

For GDScript and C#, if the value is unchanged from the default, the scene file doesn't persist any value at all for the export:
```
[node name="GDNode" type="Node" parent="."]
script = ExtResource("1_sb3ek")

[node name="C#Node" type="Node" parent="."]
script = ExtResource("2_najg7")
MonthResource = SubResource("Resource_yqifb")
```

For custom resources (C# in my case), it does persist a value, but it's a value that's out of range:
```
[sub_resource type="Resource" id="Resource_yqifb"]
script = ExtResource("3_hftao")
Month = 0
```

---

FWIW, I do see and understand why it works the way it does now (ranges are just hints), but I want to reiterate that it's very confusing to see one value in the editor and another value in the code. That shouldn't be a possible situation.

---

Workaround:

```gdscript
# Change this
@export_range(1, 12) var month: int

# To this
@export_range(1, 12) var month: int = 1
```

```cs
// Change this
[Export(PropertyHint.Range, "1,12")] public int Month;

// To this
[Export(PropertyHint.Range, "1,12")] public int Month = 1;
```

### Steps to reproduce

Create any `@export_range` field where the lower bound of the field is not the default value for that type, i.e. 0 in most cases.

![image](https://github.com/user-attachments/assets/5930ed21-cd4d-424e-a516-8a17e8f9eb1a)
![image](https://github.com/user-attachments/assets/2210bd32-5f44-40b3-abc3-357edce89ffd)
![image](https://github.com/user-attachments/assets/199d669c-0f07-4327-9763-9fd6a85dab26)

### Minimal reproduction project (MRP)

This is a C# project targeting Godot 4.4.dev3. I can attach a GD project if needed.

[ExportRangeBug.zip](https://github.com/user-attachments/files/17344759/ExportRangeBug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/75555

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by nanodeath** [comment]
Figured this would be a dupe. Thanks for checking.
