### ISSUE TITLE
Loading custom resources does not work as expected 

### ISSUE THREAD

**Issue by mgollmer** [godotengine/godot#98098]
### Tested versions

Reproducable in v4.3.stable.official [77dcf97d8]

### System information

Ubuntu 24.04, Windows 11

### Issue description

Loading a custom Resource in any way (load,preload, ResourceLoader) produces an unexpected result. 

![image](https://github.com/user-attachments/assets/58b762e5-bf0a-4ba7-b884-1cb25d3ad03e)

![image](https://github.com/user-attachments/assets/b36d5697-f348-4f5b-931f-a189db95ef8e)

### Steps to reproduce

- Create a simple custom resource to filesystem
- Load/Preload Resource anywhere in script

### Minimal reproduction project (MRP)

[testres.zip](https://github.com/user-attachments/files/17345269/testres.zip)

**Comment by FireCatMagic** [comment]
what's the issue? is it "foo" being 213 (implying uninitialized memory) or did you set it to that and i'm missing something?

**Comment by mgollmer** [comment]
Hi there,

Thanks for replying.

My expectation  at this point is to have loaded object of my `MyCustomResource` and yes I set it to that value. But unfortunately value from `tres` file isnt written to `foo` but to `members/foo`. So when Im trying to access it later on it does not work.

Maybe I do something wrong but I have tested the behaviour in several example projects and it occurs everytime.

**Comment by mgollmer** [comment]
SORRY, I found an Error in my code, producing the very failure. During my test I expected the same behaviour, because of the debugging results. 

sorry for the inconvenience
