### ISSUE TITLE
[Possible Forgotten Feature] No ability to extend ``EditorExportPlatform`` in GDScript

### ISSUE THREAD

**Issue by NovaDC** [godotengine/godot#98103]
### Tested versions

4.4-dev3

### System information

Windows 11

### Issue description

It appears that there currently is no way to extend ``EditorExportPlatform`` in a meaningful way in GDScript, spite the ``add_export_platform`` and ``remove_export_platform`` functions being exposed in ``EditorPlugin``. This appears (at least to me) to be an oversight, and I could not find any reference to issues or branches exposing or creating any type of virtual methods or other means that allow GDScript to make a ``EditorExportPlatform``. If this isn't the case and it is not planned for ``EditorExportPlatform`` to be extendable, I'll close this issue and open a proposal instead, however with ``add_export_platform`` and ``remove_export_platform`` being exposed, it at least appears to be a oversight in the process of expanding GDScript's capabilities with handling export platforms.

### Steps to reproduce

None

### Minimal reproduction project (MRP)

None

**Comment by AThousandShips** [comment]
I'm not sure how making a platform strictly in scripting would make sense, there's a lot more involved that I don't know would be possible in GDScript

**Comment by bruvzg** [comment]
It is possible, you should extend [EditorExportPlatformExtension](https://docs.godotengine.org/en/latest/classes/class_editorexportplatformextension.html), not base `EditorExportPlatform`. Documentation for it currently is incomplete, I'm working on a proper tutorial for it, but it is not done yet.

**Comment by AThousandShips** [comment]
Note that this type wasn't available before 4.4

**Comment by NovaDC** [comment]
Ah perfect! Also yes this was tested on 4.4-dev3 .

**Comment by NovaDC** [comment]
Closing as there appears to be a documented way to create a ``EditorExportPlatform`` now.
