### ISSUE TITLE
Godot 4.4dev3: shader compilation error when "Disable Receive Shadows" is Enabled

### ISSUE THREAD

**Issue by Lod6** [godotengine/godot#98102]
### Tested versions

- Reproducible in 4.4 dev3

### System information

Windows 11 - (rendering method: Mobile)

### Issue description

When I check "Disable Receive Shadows" in the material settings, the following error occurs during shader compilation:

`  servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp:193 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.
  servers/rendering/renderer_rd/shader_rd.cpp:300 - Error compiling Fragment shader, variant #0 ().
  servers/rendering/renderer_rd/shader_rd.cpp:301 - Failed parse:
  WARNING: 0:79: '' : all default precisions are highp; use precision statements to quiet warning, e.g.:
           "precision mediump int; precision highp float;" 
  ERROR: 0:2519: 'i' : undeclared identifier 
  ERROR: 0:2519: '' : missing #endif 
  ERROR: 0:2519: '' : compilation terminated 
  ERROR: 3 compilation errors.  No code generated.
  
`

### Steps to reproduce

1. Create a new StandardMaterial3D resource
2. Check "Disable Receive Shadows" in Shadows tab

### Minimal reproduction project (MRP)

[receiveshadowsbug.zip](https://github.com/user-attachments/files/17346557/receiveshadowsbug.zip)

**Comment by tetrapod00** [comment]
Confirmed on 4.4.dev3. Can't reproduce on 4.4.dev2.

**Comment by matheusmdx** [comment]
Bisecting points to #83360 as the culprit, @ywmaa

![image](https://github.com/user-attachments/assets/50d0b1a1-79a7-4bc0-ae68-d6c3adfbf17a)

**Comment by ywmaa** [comment]
Does this issue happen with Vulkan mobile only ?

**Comment by matheusmdx** [comment]
> Does this issue happen with Vulkan mobile only ?

Tested rn and seems to affect only vulkan mobile.
