### ISSUE TITLE
Image.blit_rect_mask add optional use_alpha 

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9811]
I need to draw with an transparent color this is currently not possible so I added this with default value false

https://github.com/godotengine/godot/blob/master/core/image.cpp#L1687

```
void Image::blit_rect_mask(const Ref<Image> &p_src, const Ref<Image> &p_mask, const Rect2 &p_src_rect, const Point2 &p_dest, bool use_alpha) {

...

if ( (!use_alpha && msk->get_pixel(src_x, src_y).a != 0) || (use_alpha && msk->get_pixel(src_x, src_y).a == 0)) {
```

---

Another thing, calculating `src_y` on the inner for looks like it could be done only once in the outer for(line 1681) or am I seeing something wrong?

https://github.com/godotengine/godot/blob/master/core/image.cpp#L1685

Master branch

**Comment by bojidar-bg** [comment]
Are you sure you don't want blend_rect_mask instead? #9251

**Comment by AlexHolly** [comment]
Hmm I tried `blend_rect_mask` and `blend_rect` and I don't get the same result. Even if it would work it looks a lot slower. Using a color with Color.a==0 is drawing nothing with blend methods.

Small preview how it works with blit_rect_mask and use_alpha

![peek 2017-07-24 15-45](https://user-images.githubusercontent.com/4741886/28526258-510ef81c-7087-11e7-85c8-274eb381f887.gif)
