### ISSUE TITLE
Emoji are not displayed correctly in Godot Editor online and when exporting to HTML

### ISSUE THREAD

**Issue by Lyumih** [godotengine/godot#98110]
### Tested versions

4.3

### System information

windows 11 - Godot 4.3

### Issue description

Emoji are not displayed correctly in Godot Editor online and when exporting to HTML

Emoji copied to a project from https://emojidb.org/ are displayed correctly in a local project and when running on Windows, but when exporting to HTML or Godot Editor online they break.

## Steps for repoduce
1. Add label to scene
2. Copy and past some emoji from https://emojidb.org/health-emojis
3. For example emoji:
```
Значки:
Игра: 🧬
Меню:⚙️📶💲🛍️🧺🎒🥋🏋️‍♂️🌍🗺️📗📖📚🧾📜🪞🔭🎁📦🎣⚛🕸️⚖️🧑🏻‍💻💻🚧☢️
Действия: ⚠️⛔✅🆔🆙🔄↪️🔙➕✔️♾️⁉❓♻️🗑️⏳🕒⏲⌚👁️✏️🪶📸🔎🔍🏳️🏴󠁧󠁢󠁷󠁬󠁳󠁿🔧🗝️🔒📁💾🔗💊🎁🖕
Персонажи:👤🕵🏼‍♀️👷🏻‍♀️👩🏼‍⚕️🧟‍♂️🥷🏽🧛🧙🏼‍♂️🧙🏼👩‍🎓
Характеристики: 💎⭐🌟🪙❤️💓💖💘❤️‍🔥💙💚💚💛🖤🧠🔮🗡️⚔️🪄👟🏹🎯💪🏽🛡️🔥⚡❄️💧🧊🍃👊🌈🍀🔦🪐🔷☔
Эффекты: 🤕💣💢🌀💥💡💬💞💋🫧🧬💀☠️☠︎🦴⚕👑💤🎲🧩⚕️🌊🕶️🌓🕸✡️⚓🦠☢️💯☯
Предметы: 🛠️⚒️🪛🔧🔨🪓⛏️⛏🗡️⚔️🔱🪃🏹🔫🪖⛑️🩲
Враги: 🐈🐕🦀🐶🦎☃️👻👾🐲🦇🐼🐪🦬🐥🐝🐺🛸🦕🦑🦈🐨
Земля: 🌳🌲🌵🌴🌱🌿🏺🏔️🧱🗝️🗿⛲
Здания: 🏚️⛩️⛪🏰🛕🏨🏦🎪🚃
Расходники:🎁🧪🍽️🎂🍍🥯🌽☕🧉🍫🥖🍿🍗🍑🍈🥩🍎🍺🍄
```

## Godot Editor Online
1. Open Godot Editor Online
2. Create new project
3. Repeat steps 1-3 for reproduce
![image_2024-10-12_08-11-32](https://github.com/user-attachments/assets/0f0ef380-95c0-4804-89eb-a4b4b9d261ad)

## Export project local as HTML and start
1. Local create project
2. Repeat steps 1-3 for reproduce
3. Export project as html
5. In the folder with game open terminal and start comand `npx serve .` - start local server with index.html

## See on itch.io
1. Repeat steps 1-3 for reproduce and export on itch.io
2. Run game on itch.io.
3. Temporary link with my project (until I find a way to fix emoji) https://milis-frontend.itch.io/gen-demo and github with gane 
4.
![image](https://github.com/user-attachments/assets/8254496c-ee10-4a60-8d07-c1757b852fb2)
![image](https://github.com/user-attachments/assets/692a5c1e-c508-4c4a-b384-7b18047ec41e)

### Minimal reproduction project (MRP)

1. project on itch.io https://milis-frontend.itch.io/gen-demo (maybe fix later)
2. my project https://github.com/Lyumih/gen_godot
3. gen-export.zip - archive for deploy on itch.io
4. extract gen-export.zip localy and start comand `npx serve .` in terminal folder for locali start server html

Archive: 
[gen-export.zip](https://github.com/user-attachments/files/17348905/gen-export.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/84590, as this is due to the same cause.
