### ISSUE TITLE
Unable to delete tile in TileSet editor using hotkey

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#98123]
### Tested versions

4.3 stable, 4.4 dev3

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads)

### Issue description

I'm trying to delete a tile in the TileSet editor using the "Delete" hotkey, but instead of deleting the tile, it tries to delete the last selected node in the scene.
![err](https://github.com/user-attachments/assets/f22e13f0-b80f-4f79-996e-62e7e8dbd691)

### Steps to reproduce

1. Select TileMapLayer
2. Go to TileSet editor
2. Create new tiles with left mouse button if there are none
3. Select these tiles and try to delete them with "Delete" key

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/83638

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
