### ISSUE TITLE
The editor may shake when showing/hiding the property tooltips popup on i3wm

### ISSUE THREAD

**Issue by Rindbee** [godotengine/godot#98135]
### Tested versions

Reproducible in: v4.3.dev6.official [64520fe67], v4.4.dev.custom_build [92e51fca7]
Not reproducible in: v4.3.dev5.official [c9c17d6ca]

### System information

Godot v4.3.dev6 - Linux Mint 22 (Wilma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.183.01) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

This might be an i3wm specific issue. When there are multiple tiled windows, the property tooltips popup may cause the editor to shake when it is displayed or hidden.

https://github.com/user-attachments/assets/4875a32f-f27a-4dcf-acd2-9a6e0f3bea29

First reproduced after #89058 was merged. CC @dalexeev 

https://github.com/godotengine/godot/blob/92e51fca7247c932f95a1662aefc28aca96e8de6/editor/editor_help.cpp#L3871

Adding a popup to the root window when the root window is tiled seems to cause jitter, even if the popup is hidden.

Can `tooltip` be added as a child node of `p_target`? 

### Steps to reproduce

This might be an i3wm specific issue. i3 version 4.23 (2023-10-29) 

Cannot reproduce with only one editor window open on screen. Reproducible when opening an editor window and other tiled windows on the screen:

1. Hover the mouse over the property in the Inspector dock.
2. Move the mouse away to hide the tooltips popup.

### Minimal reproduction project (MRP)

N/A

**Comment by bikemurt** [comment]
>This might be an i3wm specific issue.
I think this might be the case. I'm not seeing the issue on Windows (Win11/Godot 4.3.dev6).

**Comment by Rindbee** [comment]
> I think this might be the case. I'm not seeing the issue on Windows (Win11/Godot 4.3.dev6).

This is caused by the actual width of the editor window being less than the lower limit of `1024`. This situation is more common in tiling window managers such as i3wm and sway. I reproduced it in sway (version 1.9).
