### ISSUE TITLE
 Can not load ttf fonts, also can not import

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#9813]
ArchLinux 64b, Godot3.0

**Issue description:**
When I try to import ttf fonts the editor does not recognize the format, I also can not import the font.

**Steps to reproduce:**
Try loading dynamic fonts

**Comment by Noshyaar** [comment]
Please fill the issue template.

**Comment by yuyoDev** [comment]
Yes, I tried the formats otf, pfb, afm, none was recognized

**Comment by akien-mga** [comment]
Did you close it by mistake, or did you solve the issue?

If the former, could you provide a font file that reproduces the issue?

**Comment by eon-s** [comment]
I don't see a way to use fonts directly either and can't create a bitmap fonts.

The only way I have to use font files is by creating a new dynamic one and then assign the ttf there.

**Comment by Noshyaar** [comment]
Isn't that how you suppose to do it? TTF files are DynamicFontData. You need to create new DynamicFont and add one or more DynamicFontData(s) to it.

**Comment by eon-s** [comment]
@Noshyaar shouldn't be able to import as bitmap font and set other details like on 2.1?

**Comment by Noshyaar** [comment]
Probably deprecated in Godot 3? [EditorFontImportPlugin](https://github.com/godotengine/godot/blob/master/editor/io_plugins/editor_font_import_plugin.cpp) is commented out. Not sure if it'll be reimplemented back.

**Comment by yuyoDev** [comment]
A thousand apologies, I closed the subject by mistake. And what I've tried to do is create a dynamic font and then load the font. The editor does not recognize the font format.
And probably in Godot3.0 the fonts work as @Noshyaar explains.

I provide the font
[joystix monospace.zip](https://github.com/godotengine/godot/files/1173324/joystix.monospace.zip)

**Comment by Noshyaar** [comment]
The editor recognizes TTF as DynamicFontData as shown by the pink T icon.
![image](https://user-images.githubusercontent.com/26753932/28575690-e240afde-717b-11e7-8b78-63d2b0b929b1.png)

DynamicFontData can't be used directly and must be added to a DynamicFont first.
![image](https://user-images.githubusercontent.com/26753932/28575639-b8095edc-717b-11e7-9d67-f281fe2be64f.png)

**Comment by Sslaxx** [comment]
Would there be any usecase for allowing DynamicFontData to be used directly anywhere?

**Comment by mhilbrunner** [comment]
I think this can be closed? Seems to be explained above by others: You need to use DynamicFont with DynamicFontData, can't use DynamicFontData directly.

**Comment by yuyoDev** [comment]
yes, the issue is solved!
