### ISSUE TITLE
Several missing translations in Finnish Localization in Toolbar

### ISSUE THREAD

**Issue by SamKallio** [godotengine/godot#98148]
### Tested versions

- Reproducable in v4.3 Stable windows version

### System information

Windows 11, Desktop PC, Ryzen 7 4800h, RTX 3050Ti

### Issue description

Projects Tab:

- "Project Settings"  should be "Projektinhallinta" or "Projektiasetukset"

- Debug Tab should be called "Virheenjäljitys"

- Under debug tab "Keep Debug Server Open" should be "Pidä virheenjäljitys palvelinta auki"

- Under debug tab "Customize run instances" should be "Muokkaa suoritus instansseja"

- Under "Editori/Editorin ulkoasu" there is "Delete Layout" which should be "Poista asettelu" and "Add Layout" should be "Lisää asettelu"

- Under "Ohje" there is "Search Help" which should be "Etsi apua" and "About Godot" should be "Lisää Godotista"

There may be more, but kept it simple by only including toolbar. This issue was made for educational purposes in a testing course. 

### Steps to reproduce

- Install v4.3 Stable windows version
- Create new project
- Set Editor language to FI
- View toolbar for issues described in the Issue description

### Minimal reproduction project (MRP)

[testproject.zip](https://github.com/user-attachments/files/17356584/testproject.zip)

**Comment by Vovkiv** [comment]
Translation is done by community members, specifically on Weblate platform: https://hosted.weblate.org/projects/godot-engine/godot/
And it seems that Finnish is around ~61% done https://hosted.weblate.org/projects/godot-engine/godot/fi/
If you can and want to, you could help with translation there. (I think you could use your GitHub profile to sign-in)

**Comment by SamKallio** [comment]
> Translation is done by community members, specifically on Weblate platform: https://hosted.weblate.org/projects/godot-engine/godot/ And it seems that Finnish is around ~61% done https://hosted.weblate.org/projects/godot-engine/godot/fi/ If you can and want to, you could help with translation there. (I think you could use your GitHub profile to sign-in)

Good to know! Thank you!

**Comment by timothyqiu** [comment]
Closing as per the above, if you have issues with this again please comment here and this can be reopened.
