### ISSUE TITLE
Variable with setter gets set every frame when keyframe of it exists and animation player is linked to a state machine animation tree

### ISSUE THREAD

**Issue by hipturre** [godotengine/godot#98174]
### Tested versions

- Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i7-13700KF (24 Threads)

### Issue description

I originally stumbled across this issue trying to set enums during attack animations in another project. I'm fairly certain this is a bug. If you create a variable with a setter, create an animation with a keyframe of that variable, and link that animation player to an animation tree with root of a state machine, then that variable will be set every frame. Nothing even has to be inside the animation tree, it just happens.

### Steps to reproduce

Create a new 3D Scene with Node3D as the root.

Create a script and exported variable of type int for the Node3D.

Add a set(): to the variable and put a print in there.

Add an animation player as a child of the Node3D and create an animation that has a property track for the variable and insert at least one keyframe.

Add an animation tree as a child as the Node3D and set its root to a state machine and set the animation player to the one created.

Run the project, and you will see constant prints in the output, despite the animation not even playing.

### Minimal reproduction project (MRP)

Here's the MRP.

[anim_tree-test - Copy.zip](https://github.com/user-attachments/files/17365769/anim_tree-test.-.Copy.zip)

**Comment by AThousandShips** [comment]
You need to use the discrete callback mode, see:
* https://github.com/godotengine/godot/issues/96531

Thank you for your report

**Comment by hipturre** [comment]
I am on the discrete callback mode;

![image](https://github.com/user-attachments/assets/2aaed296-e4b6-48f4-8d89-ac7794e66be1)

**Comment by AThousandShips** [comment]
Okay thank you for clarifying (you didn't mention it) reopening for testing

**Comment by AThousandShips** [comment]
The animation tree isn't really set up to do anything so it is unclear what is supposed to happen here, but if you change the callback mode in the tree to something other than "Force Discrete" it works correctly

**Comment by AThousandShips** [comment]
My bad meant "Force Continuous"

Not sure what's intended here, or how it would be handled when adding a real use case for the tree

**Comment by hipturre** [comment]
Well as I said in my issue description, I stumbled across this issue with an actual tree that had state machines and states inside of it. In that case I have three variables that are altered by animations. Setting the tree callback to dominant or recessive causes only one ( the same one) to update constantly. I can attempt to make a MRP of that whole scene but it might take a while finding what breaks the behavior and what doesn't.

**Comment by AThousandShips** [comment]
Not sure what is to be expected there, or how to solve it, let's see what the animation team says

CC @TokageItLab

**Comment by TokageItLab** [comment]
This is the expected behavior. There are some duplicate issues as https://github.com/godotengine/godot/issues/95684, so this is closed. There is a PR in https://github.com/godotengine/godot/pull/95711 that makes it warn.
