### ISSUE TITLE
[WebSockets] Very slow put packet in server->client direction when using TLS WebSocket connection

### ISSUE THREAD

**Issue by Koyper** [godotengine/godot#98176]
### Tested versions

Reproducible in 4.3 builds and earlier. Tested using current wsl_peer.cpp master for 4.4.

### System information

MacOS 13.6.5

### Issue description

When a `WebSocketPeer` is connected using `StreamPeerTLS`, the speed of putting a packet in the direction of server->client is MUCH slower than in the client->server direction. Without TLS, the speeds are the same in both directions.

I'm using the latest improvements that should be ensuring TCP_NODELAY is always set, but could this not be propogating when using `StreamPeerTLS`? I'm also redundantly setting `set_no_delay(true)` in the MRP and that doesn't change the behavior.

In the MRP when using TLS, transferring a 215kb packet client-to-server takes 5msec, and up to 167msecs server-to-client. Without TLS, the transfer is symetrical at about 2msecs in both directions.

The delay/slowdown is consistant regardless of the max packet size or size of the packet, although the delay increases the larger the packet.

I modified the WebSocket Chat demo project to transfer a binary packet in both directions and report the transfer time. The TLS option can be toggled on an off for the `WebSocketServer` class using the Inspector.

Here is WITHOUT TLS:

https://github.com/user-attachments/assets/a59bcee5-9bae-46fa-bc89-fec50ed7852f

And here is WITH TLS:

https://github.com/user-attachments/assets/b7d0ba0d-2503-490b-93c7-ffefc556b65d

### Steps to reproduce

See MRP.

### Minimal reproduction project (MRP)

[websocket_chat_TLS_transfer_speed_bug.zip](https://github.com/user-attachments/files/17366947/websocket_chat_TLS_transfer_speed_bug.zip)

**Comment by Koyper** [comment]
Unlike `StreamPeerTCP`, `StreamPeerTLS` has no `set_no_delay()` method. Does this mean that after the connection is opened, calls to `set_no_delay` have no effect? Is this a matter of exposing this setting for mbedTLS?

**Comment by Faless** [comment]
> Unlike `StreamPeerTCP`, `StreamPeerTLS` has no `set_no_delay()` method. Does this mean that after the connection is opened, calls to `set_no_delay` have no effect? Is this a matter of exposing this setting for mbedTLS?

`set_no_delay` is an option of the TCP socket which is why there is no such option for the TLS stream.

The WSLPeer is setting that option automatically for both server and client since Godot 4.3, no matter if it's using TLS or not (in the case of TLS, it's setting it in the underlying TCP connection).

So the issue might be somewhere else.

**Comment by Faless** [comment]
@Koyper I've opened https://github.com/godotengine/godot/pull/98995 which should fix this issue, let me know if you have a chance to try it out.
