### ISSUE TITLE
TileSet won't create big tiles

### ISSUE THREAD

**Issue by c-bec-k** [godotengine/godot#98170]
### Tested versions

- Reproduceable in 4.3.stable
- Worked in 4.2.stable

### System information

macOS 15.0.1

### Issue description

When in the TileSet editor the tooltip says "Hold shift to create big tiles" but, unlike in version 4.2, I am unable to create big tiles in 4.3.stable.

You'll notice in the key cast that I'm holding SHIFT while clicking and nothing's happening.

https://github.com/user-attachments/assets/80cfcd93-b839-412c-be89-c0981af230a2

### Steps to reproduce

Create a `TileMapLayer`, add a new `tile_set`, import a sprite sheet, and attempt to create a big tile with the shift key.

### Minimal reproduction project (MRP)

N/A

**Comment by groud** [comment]
You cannot create big tiles on top of already creates tiles. You need to remove the underlying tiles first.

**Comment by groud** [comment]
Closing this issue as what this video shows isn't really a bug. I purposefully prevented creating a tile over existing tiles to avoid data loss. 

I don't think this behavior should be changed but you may open a proposal instead if that behavior is very unexpected to you.

**Comment by c-bec-k** [comment]
> Closing this issue as what this video shows isn't really a bug. I purposefully prevented creating a tile over existing tiles to avoid data loss.
> 
> I don't think this behavior should be changed but you may open a proposal instead, if you believe this behavior is very unexpected.

I’m pretty sure that I was able to make big tiles from existing ones in 4.2, but I’m away from my computer and I’ll have to check later. Thanks for the information!
