### ISSUE TITLE
Custom editor font artifacts at high zoom

### ISSUE THREAD

**Issue by eobet** [godotengine/godot#98188]
### Tested versions

4.4 dev 3

### System information

Godot v4.4.dev3 - Nobara Linux 40 (GNOME Edition) on Wayland - Wayland display driver, Single-window, 1 monitor - Vulkan (Mobile) - integrated Intel(R) Xe Graphics (TGL GT2) - 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 threads)

### Issue description

I'm using the freely available Roboto Condensed font for Google, and the bold version looks like this:

![Screenshot from 2024-10-14 23-22-42](https://github.com/user-attachments/assets/0ca2c1cc-2eee-4464-b71c-3731e6f9c837)

This does not happen in 4.3:

![Image](https://github.com/user-attachments/assets/09a5e545-5a1d-46a2-a4bf-fd8bec9a9d15)

### Steps to reproduce

Just set the custom editor font to be Roboto Condensed Bold.

Zoom in (shader editor easiest).

Maybe you need 200% display scaling as well, I'm not sure.

### Minimal reproduction project (MRP)

N/A

**Comment by fire** [comment]
Reminds me of the signed distanced field artifacts with incorrect fonts.

https://github.com/godotengine/godot/pull/61555

![image](https://github.com/user-attachments/assets/8db479c9-637d-436b-b3e7-548cefdff739)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/61207, as this is due to the same cause.
