### ISSUE TITLE
Add a cosmetic empty line after the config_version=3 hint in project.godot

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9818]
**Operating system or device - Godot version:**
Any OS, master branch.

**Issue description:**
Godot now saves `config_version=3` as a (non mandatory) compatibility hint in project.godot, it looks like this:
```
config_version=3
[application]

config/name="Platformer"
config/icon="res://icon.png"
run/main_scene="res://stage.tscn"
```

It would look much cleaner like this:
```
config_version=3

[application]

config/name="Platformer"
config/icon="res://icon.png"
run/main_scene="res://stage.tscn"
```

;)

**Comment by zatherz** [comment]
I think this would look even better:
```
config_version=3

[application]
config/name="Platformer"
config/icon="res://icon.png"
run/main_scene="res://stage.tscn"
```

**Comment by RichyHBM** [comment]
You beat me to it zatherz! :)
Was going to mention the misspell in custom_features, wasn't sure if it needed to be part of the same PR as it isn't actually being used yet it seems
