### ISSUE TITLE
Parser error Unable to iterate on value of type Array[TYPE]

### ISSUE THREAD

**Issue by patriksima** [godotengine/godot#98198]
### Tested versions

- reproducible 4.3.stable
- it works for 4.2.2.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Mobile) - integrated AMD Radeon (TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12046.24001) - AMD Ryzen 5 7530U with Radeon Graphics (12 Threads)

### Issue description

Basically if i need inheritance in arrays, it works for 4.2.2 but not for 4.3 due to _const_ constraint I guess. see attached example.

### Steps to reproduce

Let's we have PARENT class (extends Resource) and CHILD class (extends PARENT) and some settings in the array of PARENT.  Once we load an setting using _preload_ and want to iterate array it works in 4.2.2, but not in 4.3. I found out it's the _const_ keyword. As soon as we use _var somethinh = preload..._ it works for 4.3.

### Minimal reproduction project (MRP)

[inheritancetest.zip](https://github.com/user-attachments/files/17375685/inheritancetest.zip)

**Comment by dustdfg** [comment]
4.3 prints error that it couldn't load file, 4.2.2 really doesn't do it. I would test it further but honestly I didn't understand whats intended to happen :sweat_smile:

**Comment by matheusmdx** [comment]
This is a duplicate of #95568, as workaround you can untype the array in `wrapper.gd` or don't use a const variable for preload the `wrapper` resource in the `test.gd`.

**Comment by patriksima** [comment]
Thank you.
