### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by DDAN-17** [godotengine/godot#98190]
### Tested versions

4.3.stable.official

### System information

Godot v4.3.stable - macOS 15.0.0 - Vulkan (Forward+) - integrated Intel Iris Pro Graphics - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 Threads)

### Issue description

Godot crashed, I don't know why, but it looks like a corrupted pointer within [Object::_disconnect](https://github.com/godotengine/godot/blob/af77100e394dcaca609b15bef815ed17475e51ed/core/object/object.cpp#L1482)

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Godot [35704]
Path:                  /Applications/Godot 4.3.app/Contents/MacOS/Godot
Identifier:            org.godotengine.godot
Version:               4.3 (4.3)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-14 19:36:56.2712 -0500
OS Version:            macOS 15.0 (24A335)
Report Version:        12
Anonymous UUID:        9F5014BD-EF5C-616E-FEB4-13996028AF78

Sleep/Wake UUID:       77C448ED-6D82-4679-A47B-9B5E8CC41F3F

Time Awake Since Boot: 91000 seconds
Time Since Wake:       2543 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   Godot [35704]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4310597616
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100ee8000-107992000    [106.7M] r-x/r-x SM=COW  /Applications/Godot 4.3.app/Contents/MacOS/Godot

Application Specific Information:
abort() called

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff81abccb52 __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff81ac06f85 pthread_kill + 262
2   libsystem_c.dylib             	    0x7ff81ab27b19 abort + 126
3   Godot                         	       0x1017cee69 0x100ee8000 + 9334377
4   libsystem_platform.dylib      	    0x7ff81ac3be9d _sigtramp + 29
5   ???                           	               0xa ???
6   Godot                         	       0x1059462ad 0x100ee8000 + 77980333
7   Godot                         	       0x105938daa Object::_disconnect(StringName const&, Callable const&, bool) + 138
8   Godot                         	       0x105943df1 Object::~Object() + 673
9   Godot                         	       0x103737f43 Node::_notification(int) + 1475
10  Godot                         	       0x105932a57 Object::_predelete() + 119
11  Godot                         	       0x103737f33 Node::_notification(int) + 1459
12  Godot                         	       0x105932a57 Object::_predelete() + 119
13  Godot                         	       0x103781d3d SceneTree::_flush_delete_queue() + 189
14  Godot                         	       0x103781f22 SceneTree::process(double) + 274
15  Godot                         	       0x101838ed1 Main::iteration() + 1089
16  Godot                         	       0x1017c9e1a OS_MacOS::run() + 154
17  Godot                         	       0x1017f8ef3 main + 387
18  dyld                          	    0x7ff81a8792cd start + 1805

Thread 1:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10551ff1b _IP_ResolverPrivate::_thread_function(void*) + 171
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 7:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 8:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 9:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x10598823e WorkerThreadPool::_thread_function(void*) + 270
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 10:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	    0x7ff81abc5e0e mach_msg2_trap + 10
1   libsystem_kernel.dylib        	    0x7ff81abd4622 mach_msg2_internal + 84
2   libsystem_kernel.dylib        	    0x7ff81abccf16 mach_msg_overwrite + 649
3   libsystem_kernel.dylib        	    0x7ff81abc60ff mach_msg + 19
4   CoreFoundation                	    0x7ff81acecc48 __CFRunLoopServiceMachPort + 143
5   CoreFoundation                	    0x7ff81aceb6cd __CFRunLoopRun + 1393
6   CoreFoundation                	    0x7ff81aceab6c CFRunLoopRunSpecific + 536
7   AppKit                        	    0x7ff81e774d6d _NSEventThread + 127
8   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
9   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 11:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	    0x7ff81abc5d8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff825ee9cf1 caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff825ee9c1c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff825ee995e void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 12:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	    0x7ff81abc5d8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff825ee9cf1 caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff825ee9c1c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff825ee995e void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 13:: caulk::deferred_logger
0   libsystem_kernel.dylib        	    0x7ff81abc5d8a semaphore_wait_trap + 10
1   caulk                         	    0x7ff825ee9cf1 caulk::semaphore::timed_wait(double) + 151
2   caulk                         	    0x7ff825ee9c1c caulk::concurrent::details::worker_thread::run() + 30
3   caulk                         	    0x7ff825ee995e void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 41
4   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
5   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 14:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x1023306ac 0x100ee8000 + 21268140
4   Godot                         	       0x10233051d 0x100ee8000 + 21267741
5   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 15:
0   libsystem_kernel.dylib        	    0x7ff81abc8876 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff81aab6cf1 nanosleep + 199
2   Godot                         	       0x102670fcb OS_Unix::delay_usec(unsigned int) const + 59
3   Godot                         	       0x1027e4142 EditorExportPlatformAndroid::_check_for_changes_poll_thread(void*) + 8450
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 16:
0   libsystem_kernel.dylib        	    0x7ff81abc8876 __semwait_signal + 10
1   libsystem_c.dylib             	    0x7ff81aab6cf1 nanosleep + 199
2   Godot                         	       0x102670fcb OS_Unix::delay_usec(unsigned int) const + 59
3   Godot                         	       0x102842dc2 EditorExportPlatformIOS::_check_for_changes_poll_thread(void*) + 11298
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 17:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x1035d8c7b TilesEditorUtils::_thread() + 2907
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 18:
0   libsystem_kernel.dylib        	    0x7ff81abc89aa __psynch_cvwait + 10
1   libsystem_pthread.dylib       	    0x7ff81ac077a8 _pthread_cond_wait + 1193
2   libc++.1.dylib                	    0x7ff81ab4ba04 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
3   Godot                         	       0x102bff4ab EditorResourcePreview::_thread() + 171
4   Godot                         	       0x1053e65bb Thread::callback(unsigned long long, Thread::Settings const&, void (*)(void*), void*) + 91
5   Godot                         	       0x1053e6924 0x100ee8000 + 72345892
6   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
7   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 19:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	    0x7ff81abc5d96 semaphore_wait_signal_trap + 10
1   caulk                         	    0x7ff825f03315 caulk::mach::semaphore::wait_signal_or_error(caulk::mach::semaphore&) + 23
2   CoreAudio                     	    0x7ff81d57f861 HALC_ProxyIOContext::IOWorkLoop() + 5515
3   CoreAudio                     	    0x7ff81d57dad8 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 148
4   CoreAudio                     	    0x7ff81d72b041 HALC_IOThread::Entry(void*) + 73
5   libsystem_pthread.dylib       	    0x7ff81ac07253 _pthread_start + 99
6   libsystem_pthread.dylib       	    0x7ff81ac02bef thread_start + 15

Thread 20:
0   libsystem_pthread.dylib       	    0x7ff81ac02bcc start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib       	    0x7ff81ac02bcc start_wqthread + 0

### Steps to reproduce

Unknown how to reproduce

### Minimal reproduction project (MRP)

N/A

**Comment by Chaosus** [comment]
Sorry, but without reproduction steps and MRP this issue is malformed and developers can't help you.
