### ISSUE TITLE
Support for RTL input and display

### ISSUE THREAD

**Issue by xsoh** [godotengine/godot#982]
The editor doesn't recognize the non-latin characters (it writes nothing) even with changing the font of the editor. Also trying to paste a word of non-latin will print the Unicode representation (e.g. \u2320\u3433...etc) not the real word (e.g. سلام).

**Comment by reduz** [comment]
by the way, what do you guys use for text input? do you need a special IME popup or the keyboard just inserts the right characters directly?

**Comment by Evi1M4chine** [comment]
@reduz: Arabs have just [normal keyboard layouts](http://en.wikipedia.org/wiki/Arabic_keyboard). The font rendering is a bit special though, as the characters combine into something that looks different.
But I don’t think it matters, because I have an [advanced German keyboard layout](http://www.neo-layout.org/), and for all the unusual characters, when I press the key, Godot simply does nothing.

**Comment by reduz** [comment]
what platform are you on? maybe it has something to do with that, for me it
works with english and spanish

**Comment by Evi1M4chine** [comment]
@reduz: Might be. This is

* amd64 platform,
* Linux 3.18.1,
* Xorg 7.4 (server 1.16.2.901, but with nVidia drivers 340.65),
* KDE 4.14.3,
* GCC 4.8.3 (LLVM 3.5.0 is installed too)
* Python 2.7.8 (3.3.5 is installed too, but disabled via eselect, as Godot doesn’t work with it)
* SCons 2.3.4
* Mesa 10.3.5
* ALSA libs 1.0.28
* Freetype 2.5.4
* OpenSSL 1.0.1j
* pkgconfig 0.28
* and Godot is obviously self-compiled from the latest git sources.

I just tested it a bit (trying to enter special characters in a label text field and found at least one character for each mod key combination that worked. It seems to be a case of a limited character set.
It also apparently seems to slow down, because the invisible characters still count. So when using the cursor or pressing backspace, it may look like nothing happened, or as if it was hanging. This was really hard to find out. As for rendering them in the scene: I could not find a character that showed up in the text field but not in the scene. Probably because I imported and used my own full Unicode font. (I know that font works, because I use it for the rest of the system.)

I could not test advanced layout things though (like Arab or Thai scripts)…

Anyway, this is not *that* important to me. I’m just interested in having GDscript identifiers with Unicode characters in them, and the basic German letters. Everything special can be done by making my own images. :)

**Comment by okamstudio** [comment]
question, what do you do with the NEO keyboard layout with shortcuts such
as ctrl-z, ctrl-s, etc?


On Fri, Jan 2, 2015 at 7:02 PM, Evi1M4chine <notifications@github.com>
wrote:

> @reduz <https://github.com/reduz>: Might be. This is
>
>    - amd64 platform,
>    - Linux 3.18.1,
>    - Xorg 7.4 (server 1.16.2.901, but with nVidia drivers 340.65),
>    - KDE 4.14.3,
>    - GCC 4.8.3 (LLVM 3.5.0 is installed too)
>    - Python 2.7.8 (3.3.5 is installed too, but disabled via eselect, as
>    Godot doesn’t work with it)
>    - SCons 2.3.4
>    - Mesa 10.3.5
>    - ALSA libs 1.0.28
>    - Freetype 2.5.4
>    - OpenSSL 1.0.1j
>    - pkgconfig 0.28
>    - and Godot is obviously self-compiled from the latest git sources.
>
> I just tested it a bit (trying to enter special characters in a label text
> field and found at least one character for each mod key combination that
> worked. It seems to be a case of a limited character set.
> It also apparently seems to slow down, because the invisible characters
> still count. So when using the cursor or pressing backspace, it may look
> like nothing happened, or as if it was hanging. This was really hard to
> find out. As for rendering them in the scene: I could not find a character
> that showed up in the text field but not in the scene. Probably because I
> imported and used my own full Unicode font. (I know that font works,
> because I use it for the rest of the system.)
>
> I could not test advanced layout things though (like Arab or Thai scripts)…
>
> Anyway, this is not *that* important to me. I’m just interested in having
> GDscript identifiers with Unicode characters in them, and the basic German
> letters. Everything special can be done by making my own images. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/982#issuecomment-68566711>.
>



-- 

*OkamStudio*

**Comment by Evi1M4chine** [comment]
Well, the Ctrl, Alt and Win keys are still available. Maybe the fact that in Germany the Ctrl key is called “Strg” was confusing.

So I just press them like normal.

[Just that of course I have more other combinations available, as I could set shortcuts to `Ctrl-Alt-Mod3-Mod4-(someletter)` if I was crazy. ;) Even KDE, and Gnome sometimes fail to handle those correctly though.]

**Comment by mohaalak** [comment]
for supporting RTL and Arabic scripts , we can use http://www.freedesktop.org/wiki/Software/HarfBuzz/ ,

**Comment by mohaalak** [comment]
@reduz  I contacted for licensing issue on Fribidl , I am waiting for an answer.

**Comment by reduz** [comment]
That looks o,k, though I don't really understand how it's supposed to work.
As far as I understand, the font engine must support the following?
1) RTL and LTR characters, for switching direction? (as far as I understand
it's like characters are pushed, then retrieved in the opposite direction?)
2) Ligatures between different types of character combinations

Is there anything else?

**Comment by mohaalak** [comment]
1 - in RTL langauges all character go from left to right but digits and LTR characters should go from left to right (it's not  like align left)
2- yeah correct the combination of characters should print something else.

you think we can create from ground up this feature without using any library?

if you point me in right direction I think I can make it work at least for Farsi and Arabic.

should I change 
https://github.com/okamstudio/godot/blob/master/scene/resources/font.cpp

draw function?

.

**Comment by reduz** [comment]
Ok, but as far as I understand Unicode by default is LTR, so if unicode
supports RTL it *must* have some sort of character that tells you "ok from
now on, following text is RTL" and then something to also tell "ok from now
on, following text is LTR again".

**Comment by mohaalak** [comment]
every text editor that support RTL has a button to make text RTL or LTR. 
we should add a property that make control is on RTL or LTR.

**Comment by reduz** [comment]
oh so this is external to the text.. you mean that label should have a
button that says "Use RTL Text"

However, if we were dealing with game translations and we wished to support
RTL languages, how is this handled?

**Comment by xsoh** [comment]
This project might be good for understanding Bidi 
https://github.com/salshaaban/BidiRenderer

**Comment by mohaalak** [comment]
it's a little tricky , when I want to use it on web , after translation we should set direction to RTL , here we should have a system that if this language is RTL or not , if it is RTL the Controller should change from LTR to RTL and every object that inherit this should become RTL.

in some softwares when you change your layout from LTR to RTL everything change from left to right,
like when in a form,   labels is left and inputs are in front , in right  of screen , when change to RTL mode in some softwares it change all things , labels goest to right of screen, inputs go to left of screen .

It's living in  hell to write multi-language software when RTL language is concerned :D

I think just labels and text edits can support RTL is fine.


@xsoh this code comes from a library called Unicode bidirectional algorithm , and this algorithm is GPL. I don't know much about licensing but @reduz say we can't use it cause in android , ios , consoles you can't use GPL

**Comment by lostdj** [comment]
> this is opengl, so we can't use truetype.

Yes you can. :)

**Comment by xsoh** [comment]
@mohaalak Does the algorithm it self (I don't mean the code. I mean the algorithim) has licensing?  What I meant for BidiRenderer is just for understanding not using the code it self.

**Comment by mohaalak** [comment]
I read in fribidI that algorithm has license too. I don't get these
licensing issues and after a little research Fribidi might not be our best
option . There is another library named harbuzz it use true type and it has
'old MIT'.
with Cairo library we could support true type fonts but I think it's too
much work to change how fonts draws now and there will be lots of bugs and
compatibility issue with older version of godot.
after reading source code of harfbuzz I think I could change it to use
BMfonts .I think it gets only size of each glyph from ttf .  I could pass
size from BMfonts to harfbuzz . it should be interesting.

**Comment by mohaalak** [comment]
I have good news and bad news.
### Good News : 

- implement RTL support for Godot in this gui interfaces:
    - label
    - text edit
    - line edit 
    - button
- another good news is that if you write RTL language , it will automatically change to RTL mode. @reduz so I think in translation everything is safe

![screenshot from 2015-03-22 01 26 15](https://cloud.githubusercontent.com/assets/891975/6766802/c30c53f8-d032-11e4-895e-a3738532d7c2.png)

### Bad News :
 I could not work with harfbuzz , it needs true type support and  for that we should use cairo library and font is gonna be change fundamentally. I think @reduz  and other main developers should discuss about this change (I could do it but first let's discuss it ) , [a post about cairo and bmfonts](http://wildfiregames.com/forum/index.php?showtopic=17365)

I used Fribidi ,it's license is  LGPL,  it means that you can't release it to Android , iOS or anywhere else unless , users can change just Fribidi library ,link it to your code and everything else works again. it can be done.
1. you can open source your game ( not a great idea for everyone)
2. you can export a release mode from godot and let's anyone that wants, compile  godot from repository with their changes and use your released datapack( I don't know if it's doable or not)
3. you can  change scons to build a Static Library for Fribidi and ship your game with this library I know it works in [android](http://programmers.stackexchange.com/questions/205925/use-of-lgpl-libraries-in-closed-source-android-software)  , windows , linux  but for ios I just found this (link) [http://multinc.com/2009/08/24/compatibility-between-the-iphone-app-store-and-the-lgpl/], short answer is that you should ask permission of Fribidi to use it under iOS, I don't know anything about other consoles.

you can clone my repository and work with it if you want , I don't open a pull request I don't think @reduz  wants this changes into main repository.

**Comment by mohaalak** [comment]
by the way we can use [BIDI algorithm](http://unicode.org/reports/tr9/) but I don't know much about licensing , it does not mention anything here about any license but I think I read somewhere in fribidi doc that algorithm is LGPL also.
I found this [source codes](http://www.unicode.org/Public/PROGRAMS/BidiReferenceCpp/v25g/)  for bidi algorithm , I will work with this sample code too , maybe I can make something out , but if we use truetype it's gonna be better.

**Comment by mohaalak** [comment]
above algorithm work for RTL support but we need Ligatures for other languages. I can make something for arabic and persian but I don't know about other languages.

**Comment by mohaalak** [comment]
ok I found something for reshaping [here](ftp://ftp.unicode.org/Public/UNIDATA/ArabicShaping.txt). 
yess!!! I think I can make this work without any licensing issues. 
I will update in a few days.

**Comment by okamstudio** [comment]
Algorithm should work fine, no licensing issues unless it's a library. For
ligatures, maybe freetype handles this as special cases of character
combinations?

On Sat, Mar 21, 2015 at 7:51 PM, Mohammad Hadi Aliakbar <
notifications@github.com> wrote:

> ok I found something for reshaping here.
> yess!!! I think I can make this work without any licensing issues.
> I will update in a few days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/982#issuecomment-84466190>.
>



-- 

*OkamStudio*

**Comment by mohaalak** [comment]
@okamstudio unfortunately freetype does not handle this but unicode.org shared a [text](https://github.com/roozbehp/unicode-data/blob/master/ArabicShaping.txt) that list all joining types in Arabic, Syriac, N'Ko, Mandaic, and Manichaean , Mongolian, Phags-pa, and Psalter Pahlavi  , I think I can work something out with this info.

**Comment by reduz** [comment]
wait, so basically unicode provides all shaping types as different
characters? so you need to basically depending on the character and next
character use a different character code?

**Comment by mohaalak** [comment]
yeah , I should check next and previous character to decide what  character code I should use.
look at this 
ت‎	ـت‎	ـتـ‎	تـ‎
all of this letters above is spelled T in arabic 
first one isolated, 
second one is  joined from left , 
third joined from both side , 
forth one joined from left

look at [this](http://en.wikipedia.org/wiki/Template:Arabic_alphabet_shapes/joining)

but there is more :smiley: 
sometimes two characters combine and produce one character this way your string size will change. 
س ل ا م
سـ لا م

there should be a map for all of this combinations.

**Comment by reduz** [comment]
from what you say, all points to the fact that there should be a method in
String, something like: "String normalize(bool start_rtl) const" or
probably that goes through the string and replaces characters and
combinations to make them correct, so it works properly with draw_text()...

we could try implementing this first, then see how to use this method in
Label, Button and other controls

**Comment by mohaalak** [comment]
yeah we need that function in String , in my implementation of fribidi in Godot I created a class with a static function , but you are right it should be in String.
I think we should add another string for label  , button and other control , a string variable that what client can see , and an original text.
1. you want to call normalize just one time when set_text called
2. when a text is normalized if you call normalize again it generates some nonesense ( that was the case in Fribidi , I don't know maybe it was a bug from Fribidi)
3. sometimes the length of strings will change , when user remove one character you should have remove from originalText then update VisualText
4. when get_text called you should return the original text 

look at my changes in (line_edit)[https://github.com/mohaalak/godot/blob/fd92a754f66132447617da9504be22c547a8fdbb/scene/gui/line_edit.cpp#L330] 
(sorry for bad indenting)

also in  _notifiacation, drop_selected , _input_event.

**Comment by lostdj** [comment]
I have no idea how complete the support is https://github.com/mosra/magnum-plugins/tree/master/src/MagnumPlugins/HarfBuzzFont
And it still will require FT support.

**Comment by lostdj** [comment]
@okamstudio 
> no licensing issues unless it's a library
Except there are. FriBidi used by @mohaalak is GPL. IANAL, but it's risky to depend on it, even if your game depends on a library with permissive license (Godot) and is opensource, which depends on a library with copyleft license.
And that's not counting the issues with *GPL licenses vs. Apple.

**Comment by mohaalak** [comment]
@lostdj harfbuzz needs freetype fonts and Godot does not support freetype, it uses ttf to make a bitmap font and use it afterwards. Fribidi uses LGPL but yes our problem is license issues and I am working to code from ground up without needing any GPL library.

**Comment by akien-mga** [comment]
Renamed the issue for clarity as most of the discussion revolves around RTL input.

**Comment by reduz** [comment]
there is PR for this that works pretty well, but depends on a large
external library for a single function. The function should be just be
extracted or rewritten

**Comment by behdad** [comment]
> there is PR for this that works pretty well, but depends on a large external library for a single function. The function should be just be extracted or rewritten

Note that that single function is exercises most of the library, if FriBidi is the library you are talking about.

If licensing is a problem, I was going to convince you to rewrite based on HarfBuzz, but if you call FriBidi "large", then HarfBuzz is HUGE!

**Comment by reduz** [comment]
It seems Unicode has a simple source code reference of he bidirectional algorithm:
http://www.unicode.org/Public/PROGRAMS/BidiReferenceCpp/v25g/
anyone that understands enough could adapt it?

**Comment by akien-mga** [comment]
> It seems Unicode has a simple source code reference of he bidirectional algorithm:
http://www.unicode.org/Public/PROGRAMS/BidiReferenceCpp/v25g/
anyone that understands enough could adapt it?

Actually there's a version 26 of that algorithm too: http://www.unicode.org/Public/PROGRAMS/BidiReferenceCpp/v26/

To anyone interested in tackling this, please check #2886 as a reference for a WIP implementation using the ICU library. We believe that we'd be better off without adding a big library like ICU just for that, hence the proposal to use the Unicode Bidi reference, but at the same time most of us are not RTL experts and might miss something.

**Comment by mohaalak** [comment]
it's 1 year that I don't make any games with godot, but I hope for Version 3.0 it will support RTL, I don't have time to implement it but I can test it if you want, please make this happen

**Comment by reduz** [comment]
@mohaalak Gandhi once said "Be the change you want to see in the world". If we don't get help from someone who understands how RTL is used, we simply can't do it.

**Comment by khaledhosny** [comment]
Proper Arabic/Indic/etc and RTL support will require a punch of extra dependencies as it is a rather huge amount of work to do from scratch or fork and bundle existing libraries. Are such dependencies something the maintainers are open to?

**Comment by akien-mga** [comment]
@khaledhosny Up to now the general feeling is that the less additional dependencies, the better. We were under the impression that it should be possible to reimplement the BiDi algorithm directly (or via a lightweight library) - but actually the more time passes, the more I think there might be a reason why RTL libraries are so big (especially as Arabic letters need to support mutating based on their context).

So if a RTL-aware dev could do some research about what would be a minimal set of dependencies/features needed to support RTL and text shaping properly on all platforms, that would help bringing this issue closer to a fix.

**Comment by khaledhosny** [comment]
Minimal dependencies would be FriBiDi for bidirectional support, HarfBuzz for font shaping, FreeType for font rasterization (not a hard requirement) and some code to glue everything together ([Raqm](https://github.com/HOST-Oman/libraqm) can be that glue but it is not absolutely needed). If FriBiDi license is an issue then ICU is another replacement, but otherwise I recommend against just using the sample code from Unicode unless someone has the time an interest in actively maintaining it in this code base.

This should give you support for Arabic, Hebrew, lots of Indic and South Asian scripts and more.

**Comment by akien-mga** [comment]
FriBiDi is licensed under the LGPL, which is (AFAIU) a bit tricky when you link it statically as we do in Godot for our thirdparty libraries. I think it *may* be fine, but we'd have to double check with a lawyer:

> A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.

The problem of ICU is that it's huge and provides a lot more than just the BiDi algorithm, so it would bloat the engine unnecessarily.

An alternative could be the Apache-licensed [SheenBidi](https://github.com/mta452/SheenBidi).

For FreeType, it's included already. HarfBuzz could be added, it seems to be the go-to solution for font shaping.

**Comment by khaledhosny** [comment]
I have no experience with using SheenBidi and it seems relatively new, but in principle any conforming UBA implementation should be fine.

**Comment by khaledhosny** [comment]
I looked into the text layout code briefly and I’m afraid it is not an easy task since the code seem to be written with the assumption that text is laid sequentially from left to right, which is obviously not the case for most complex scripts. Fixing that will require quite some refactoring and deeper understanding of the code.

**Comment by mohaalak** [comment]
ICU implmentation and Fribidi was pull reqeuested before but denied cause of license and huge library,
 I don't know if it's possible to add ICU as extensioin using GDNative or not? 
I didnot read GDNative docs yet

**Comment by akien-mga** [comment]
Just mentioning that this is still a wanted feature, but it's a complex one to implement properly (especially font shaping). Current WIP in #10546 with discussion on how it should be done with the minimal impact for languages which can print chars one by one as done currently.

**Comment by nightblade9** [comment]
I am also interested in this. Just tried a custom font with Arabic letter support and it shows up broken and left-to-right. (I didn't read this entire thread, just the top few and bottom few posts.)

If anyone's interested, this is how it looks in Godot 3.0.4:

![image](https://user-images.githubusercontent.com/31222662/42139210-23965ee2-7d57-11e8-90d4-8733be236f4b.png)

This is how it should appear:

القرآن الكريم

**Comment by nightblade9** [comment]
I just realized that the ICU-support WIP sample [here](https://github.com/godotengine/godot/pull/10546) sort of works. Is there any possibility of merging it in and swapping it out later?

If we wait for proper support of this feature, we may end up waiting a long time; this WIP would at least get us something we can use for now (even if it's not well-supported or ideal).

**Comment by g--o** [comment]
Hopping on this issue, other RTL languages suffer here as well with the same original flipped text problem.
So there's localization to the editor but it's just useless when the entire thing is flipped!

**Comment by golddotasksquestions** [comment]
Maybe these guys can help: https://www.arabeyes.org/Translation_requests

**Comment by mbnoimi** [comment]
This is really frustrated. 
This bug opened since forever and GD gurus unable to fix it!

**Comment by Calinou** [comment]
@nbnoimi Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by akien-mga** [comment]
As we're moving all feature requests to the new [godot-proposals](https://github.com/godotengine/godot-proposals) repository, I'll close this as superseded by godotengine/godot-proposals#4.

Note that fixing these issues is one of our priorities for Godot 4.0, as we can take the opportunity of a compatibility breakage to properly rethink our text layout controls to accommodate the requirements of RTL display and font shaping.
