### ISSUE TITLE
Godot crash on Control.move_child

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9820]
```
ERROR: insert: Index p_pos out of size (size() + 1).
   At: core/vector.h:400.
ERROR: operator[]: FATAL: Index p_index out of size (size()).
   At: core/vector.h:137.

```

Master branch

**Comment by JuanIsAFuckingAlpaca** [comment]
damn, looks like  the 3.0 release is coming along nicely, let's hope for a smooth stable release

**Comment by AlexHolly** [comment]
Looks like removing the +1 solves the issue, any reason why its there?

https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L306

**Comment by RandomShaper** [comment]
Can you provide instructions on how to reproduce it?

**Comment by AlexHolly** [comment]
Something like this
`parent.move_child(parent.get_children()[0], parent.get_children()[1].get_position_in_parent()+1)`

parent.get_children()[1] is the last child.

Showing the exact case is too much work I hope this works.

**Comment by RandomShaper** [comment]
More than enough! Fixed!
