### ISSUE TITLE
Spatial Shader without Colors flickers in weird colors

### ISSUE THREAD

**Issue by bnjmntmm** [godotengine/godot#98223]
### Tested versions

- Reproducible in 4.3.stable and 4.4.dev3 [f4af8201b]

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 32.0.11027.1003) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

A spatial shader without Color has weird fragments and starts flickering. Also a weird glow sometimes happens. 
It happened to me on accident but I would have expected an error like "color variable has no data set " or something similar

https://github.com/user-attachments/assets/cc677e5a-7f96-40c6-b80b-6e119c3d9e35

### Steps to reproduce

Create MeshInstance3D, select QuadMesh as Mesh, create new Shader at GeometryInstance3D Material Override.
In Shader Code:
```gdscript
vec4 color_variable;
ALBEDO = color_variable.rgb;
ALPHA = color_variable.a;
```
Flickering begins

### Minimal reproduction project (MRP)

N/A

[bug_test.zip](https://github.com/user-attachments/files/17392771/bug_test.zip)

**Comment by AThousandShips** [comment]
This is to be expected I'd say, and something to document, unassigned variables have undefined value for performance reasons, you need to assign a value to it or it'll be random memory

We could consider adding a warning for unassigned values but I'm not sure it's worth the work to perform that analysis, or if it is even trivial to do so, for example:
```
vec4 color_variable;
if (foo) {
    color_variable = vec4(1, 0, 0, 1);
}
ALBEDO = color_variable.rgb;
ALPHA = color_variable.a;
```
Would also need to be caught, and the static analysis of that is pretty complex

**Comment by tetrapod00** [comment]
Ideally this *should* be a warning. But in the meantime, I added a note to the shading language page: https://github.com/godotengine/godot-docs/pull/10105.

Adding a warning should be tracked as a separate proposal, probably?
