### ISSUE TITLE
Camera3D does not draw shadows casted by objects on other render layers

### ISSUE THREAD

**Issue by DillonSteyl** [godotengine/godot#98231]
### Tested versions

4.3.stable

### System information

Windows 11

### Issue description

I'm uncertain if this should be a _feature proposal_ or not, but I seem to recall older versions of Godot supporting what I want to do here so I thought I would raise as a bug first.

A common solution to the "gun clipping" issue in FPS games is to use a separate camera to render the weapon mesh. This also allows us to modify the FOV of the player without distorting the look of the weapon mesh.

In Godot, we can accomplish this by having the gun mesh be on Render Layer 2, and having a separate "gun camera" which culls all render layers _except_ Layer 2.  However, with this setup, the gun mesh will **not receive shadows correctly.**

To illustrate this, I have set up a scene where the world is on Render Layer 1, and the weapon is on Render Layer 2.
Here's what it looks like with a single camera, culling no layers.
![{0A8BE2C5-455A-4D66-8113-C6613AB447D3}](https://github.com/user-attachments/assets/6fbe6a78-0233-4295-acec-486b056658cb)

Here's what it looks like with the setup described above:
![{0ACCCE5C-64B4-49F5-8342-29E884F57894}](https://github.com/user-attachments/assets/abd9dce8-78f1-40a2-9846-2817bb4d36e5)

### Steps to reproduce

1. Set up "world" meshes, and ensure they are drawn on Render Layer 1.
2. Add a directional light with shadow casting **on**.
3. Create another mesh on Render Layer 2. Position it so that it is in the shade casted by the "world" meshes from Step 1.
4. Add a camera to the scene so that everything is in view, and preview it
5. Note that culling Render Layer 1 removes all shadows from the mesh on Render Layer 2.

### Minimal reproduction project (MRP)

[test-viewport-shadows.zip](https://github.com/user-attachments/files/17394651/test-viewport-shadows.zip)

**Comment by AThousandShips** [comment]
Related:
* https://github.com/godotengine/godot-proposals/issues/3606

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/77383

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened
