### ISSUE TITLE
FileAccess store_line() overwriting files instead of appending to files without seek_end()

### ISSUE THREAD

**Issue by aaron-bigadventurecrew** [godotengine/godot#98243]
### Tested versions

Reproducible since 4.3-beta3 up until now 4.4-dev3

### System information

Windows 10 Pro - Godot v4.3.stable.steam [77dcf97d8]

### Issue description

Per the docs, FileAccess' store_line() method is defined as:

> void store_line(line: String)
> Appends line to the file followed by a line return character (\n), encoding the text as UTF-8.

The use of _Appends_ here would imply that it would just add to a file ending with a trailing _\n_. However, the use of WRITE, WRITE_READ, and READ_WRITE cause the file to be overwritten completely. The only way to truly _append_ a file with `store_line()` is to use the `seek_end()` method first.

The Ask: Either (1) Update the docs to more accurately explain what `store_line()` does, or (2) Revisit the engine code for `store_line()` and confirm whether it should actually _append_ to a file.

Docs Link: [https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-line](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-line)

### Steps to reproduce

```
extends Node

func _ready() -> void:
	var file_no_seek: FileAccess
	var file_with_seek: FileAccess
	
	if !FileAccess.file_exists("user://no-seek.txt"):
		file_no_seek = FileAccess.open("user://no-seek.txt", FileAccess.WRITE_READ)
		print("no-seek.txt created at: " + OS.get_user_data_dir() + "/no-seek.txt")
	else:
		file_no_seek = FileAccess.open("user://no-seek.txt", FileAccess.READ_WRITE)
		print("no-seek.txt opened from: " + OS.get_user_data_dir() + "/no-seek.txt")
	
	file_no_seek.store_line(Time.get_datetime_string_from_system() + " - Attempt to increment no-seek.txt")
	print("no-seek.txt file contents:\n" + file_no_seek.get_as_text())
	file_no_seek.close()
	print("Successfully closed no-seek.txt")
	
	if !FileAccess.file_exists("user://with-seek.txt"):
		file_with_seek = FileAccess.open("user://with-seek.txt", FileAccess.WRITE_READ)
		print("with-seek.txt created at: " + OS.get_user_data_dir() + "/with-seek.txt")
	else:
		file_with_seek = FileAccess.open("user://with-seek.txt", FileAccess.READ_WRITE)
		print("with-seek.txt opened from: " + OS.get_user_data_dir() + "/with-seek.txt")
	
	file_with_seek.seek_end()
	file_with_seek.store_line(Time.get_datetime_string_from_system() + " - Attempt to increment with-seek.txt")
	print("with-seek.txt file contents:\n" + file_with_seek.get_as_text())
	file_with_seek.close()
	print("Successfully closed with-seek.txt")
	
	return
```

Note the following `print()` outputs:

> no-seek.txt opened from: C:/Users/$ME/AppData/Roaming/Godot/app_userdata/StoreLineRepro/no-seek.txt
> no-seek.txt file contents:
> 2024-10-16T10:15:55 - Attempt to increment no-seek.txt
> 
> Successfully closed no-seek.txt
> with-seek.txt opened from: C:/Users/$ME/AppData/Roaming/Godot/app_userdata/StoreLineRepro/with-seek.txt
> with-seek.txt file contents:
> 2024-10-16T10:15:37 - Attempt to increment with-seek.txt
> 2024-10-16T10:15:46 - Attempt to increment with-seek.txt
> 2024-10-16T10:15:55 - Attempt to increment with-seek.txt
> 
> Successfully closed with-seek.txt

This shows `store_line()` does end with a trailing _\n_, but even in READ_WRITE it overwrites the file without the use of `seek_end()` first.

### Minimal reproduction project (MRP)

MRP made in v4.3.stable.steam:

[StoreLineRepro.zip](https://github.com/user-attachments/files/17400494/StoreLineRepro.zip)

**Comment by syntaxerror247** [comment]
@aaron-bigadventurecrew see this PR #98238

**Comment by aaron-bigadventurecrew** [comment]
@syntaxerror247 That PR encapsulates the need well, this issue can be closed once merged. My intention of raising the issue was to give a simple MRP for the team's review anyways since explaining it can be a bit much. Thank you!

**Comment by aaron-bigadventurecrew** [comment]
Still pending the live docs page to be updated reflecting the PR Merge:

[https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-line](https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-line)

**Clear browser cache (Ctrl+Shift+R):**
```
Request URL:
https://docs.godotengine.org/en/stable/classes/class_fileaccess.html
Request Method:
GET
Status Code:
200 OK
Referrer Policy:
strict-origin-when-cross-origin

access-control-allow-methods:
HEAD, OPTIONS, GET
access-control-allow-origin:
*
age:
6402
cache-control:
max-age=1200
cdn-cache-control:
public
cf-cache-status:
DYNAMIC
content-encoding:
zstd
content-type:
text/html; charset=utf-8
date:
Wed, 16 Oct 2024 20:08:51 GMT
last-modified:
Fri, 04 Oct 2024 03:31:29 GMT
```

**Follow-up normal refresh:**
```
Request URL:
https://docs.godotengine.org/en/stable/classes/class_fileaccess.html
Request Method:
GET
Status Code:
304 Not Modified
Referrer Policy:
strict-origin-when-cross-origin

access-control-allow-methods:
HEAD, OPTIONS, GET
access-control-allow-origin:
*
age:
6615
cache-control:
max-age=1200
cdn-cache-control:
public
cf-cache-status:
DYNAMIC
date:
Wed, 16 Oct 2024 20:12:24 GMT
etag:
W/"fefc62705638391dc44bb2e0341f4c50"
last-modified:
Fri, 04 Oct 2024 03:31:29 GMT
```

**Comment by bruvzg** [comment]
> Still pending the live docs page to be updated reflecting the PR Merge:
>
> https://docs.godotengine.org/en/stable/classes/class_fileaccess.html#class-fileaccess-method-store-line

This is a link to the `stable` docs, it will only be updated when PR is cherry-picked for 4.3, new changes applied to the `latest` docs. But `sync class reference` GitHub action is set to only run every Saturday, so `latest` docs won't be updated until then.

**Comment by aaron-bigadventurecrew** [comment]
@bruvzg Oh ok sounds good then! You can mark this as resolved whenever you'd like, the changes to the wording in the PR make sense to me and explain why my reported behavior happened.

**Comment by GitExcel** [comment]
is this fixed on godot 4.4? Im on 4.2 and having this exact issue

**Comment by syntaxerror247** [comment]
@GitExcel It was a documentation error, which has now been corrected. The behavior of store_line() overwriting the file is expected. To append data instead, you can use seek_end() first.

**Comment by Scraprogrammer** [comment]
Hey! I'd like to leave a code snippet here for those like me who struggled with appending lines to a file. I think the whole process should have been a lot easier/straightforward, but maybe I'm overlooking something real simple here...

My objective was:
- Create a directory if it does not exist
- Create a file if it does not exist
- Always append a line at the end of the file

Below worked for me:

```gdscript
# Define a directory to a file
var dir_path = "user://your_folder_name/some_sub_folder_name"

# Create a directory
DirAccess.make_dir_recursive_absolute(dir_path)

# define a path to your file using previous dir_path
var file_path = dir_path + "/your_file_name.json"

# Some json line you want to write
var data = { "your": "data" }

# WRITE will override the whole file, but can create a new file.
# READ_WRITE will make it so you can append lines at the end of the file without overriding whole contents, but will fail if file does not exist yet.
# So, we choose appropriate access depending on whether file exists or not
var access = FileAccess.READ_WRITE if FileAccess.file_exists(file_path) else FileAccess.WRITE

# Open the file
var file = FileAccess.open(file_path, access)

# turn your Dictionary into a JSON string
var json_string = JSON.stringify(data)

# Jump to the end of the file to append the data at the end
file.seek_end()

# write the stringified JSON string at the end of a file
file.store_line(json_string)

# Close the file and persist the changes
file.close()
```

**Comment by bruvzg** [comment]
> READ_WRITE will make it so you can append lines at the end of the file without overriding whole contents, but will fail if file does not exist yet.

You can use `WRITE_READ` mode, it will open or create a file for both reading and writing (but cursor starts at the start of the file, so you need `seek_end` to append).

**Comment by Scraprogrammer** [comment]
Double-checked, and unfortunately, I can't use WRITE_READ . If I use WRITE_READ - it truncates the existing file and writes a new one. I want to persist files and data between file operations.

Also a piece from the [docs](https://docs.godotengine.org/en/4.4/classes/class_fileaccess.html#enum-fileaccess-modeflags) for WRITE_READ:
> The file is created if it does not exist, and **truncated if it does.**

As far as I can see, there is no explicit access mode that will say `The file is created if it does not exist, and does not truncate the file if it already exists.`. Having such an explicit Access option would definitely help if it would be added in the future :)
