### ISSUE TITLE
Headless import without gpu crashes

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot#98246]
### Tested versions

Reproduceable in 4.4.dev[92e51fca7247c932f95a1662aefc28aca96e8de6]

### System information

Linux Pop OS 22.04

### Issue description

**NOTE**

This is different from this other similar issue I put in and also have a PR for: https://github.com/godotengine/godot/issues/98062

**Description**

When importing with the ``--headless`` argument on an actual headless server without a gpu, godot crashes with:

```
ERROR: Condition "!tasks.has(p_task)" is true. Returning: canceled
   at: task_step (editor/progress_dialog.cpp:203)
ERROR: Condition "!tasks.has(p_task)" is true.
   at: end_task (editor/progress_dialog.cpp:226)
WARNING: UID duplicate detected between res://submodules/BlockyBallOT-Art/BlockBall/Skin_Materials/Skin_Magma_RedRock.tres and res://material_maker/BlockyGuy/Skin_Magma/Skin_Magma.material.tres.
     at: _process_file_system (editor/editor_file_system.cpp:1272)
ERROR: Cannot import custom .glsl shaders when running in headless mode.
   at: import (editor/import/resource_importer_shader_file.cpp:95)
ERROR: Error importing 'res://addons/proton_scatter/src/modifiers/compute_shaders/compute_relax.glsl'.
   at: _reimport_file (editor/editor_file_system.cpp:2884)
ERROR: Required extension VK_KHR_surface not found.
   at: _initialize_instance_extensions (drivers/vulkan/rendering_context_driver_vulkan.cpp:487)
ERROR: Condition "err != OK" is true. Returning: err
   at: initialize (drivers/vulkan/rendering_context_driver_vulkan.cpp:928)
ERROR: FATAL: Index p_index = 0 is out of bounds (count = 0).
   at: operator[] (./core/templates/local_vector.h:177)
Error: nu::shell::coredump_error

  × program coredump error
     ╭─[/home/vsts/work/1/s/submodules/godot-src/godot/godot.nu:142:5]
 141 │     print $"Running godot command: ($config.godot_bin) ($rest | str join ' ')"
 142 │     run-external $config.godot_bin ...$rest
     ·     ──────┬─────
     ·           ╰── to nushell `Value`invalid entry, dup11
 143 │ }
     ╰────

```

^
My pipeline executes within a nushell script.  The nushell script was simply catching the coredump / crash and displaying it.  Just to clarify on the last error.

Upon investigating the code, some changes went through that are causing godot to attempt loading gpu libs even tho the ``--headless`` arg was passed.  I made some slight changes in my fork to fix this and will have a PR in shortly.

### Steps to reproduce

1. Make sure you are running from within a headless server without a gpu.  Easily accomplished with a Docker container or Podman container.
2. Import a godot project with the --headless argument.
3. If that doesn't work, try ensuring that a glsl shader is in the project as well.
4. See that Godot crashes

### Minimal reproduction project (MRP)

N/A

**Comment by clayjohn** [comment]
When was this issue introduced? Is it just in 4.4 dev, or can you reproduce it in 4.3 as well?

**Comment by TCROC** [comment]
> When was this issue introduced? Is it just in 4.4 dev, or can you reproduce it in 4.3 as well?

Just 4.4. I was previously working on 4.3 without issue.  We recently updated to 4.4 to get the new ssl fix for mono android builds.  That was when we discovered this.

**Comment by Maran23** [comment]
> Just 4.4. I was previously working on 4.3 without issue. We recently updated to 4.4 to get the new ssl fix for mono android builds. That was when we discovered this.

You can check which 4.4-dev version introduced this. Will help when finding the cause.

**Comment by TCROC** [comment]
@Maran23 I did not bisect it to find the specific commit, but I did put in a PR with a fix: https://github.com/godotengine/godot/pull/98247
