### ISSUE TITLE
[OpenGL Compatibility] 3D Decal node support

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#98259]
### Tested versions

- v4.4.dev

### System information

Debian GNU/Linux trixie/sid x86_64 - Vulkan Forward +

### Issue description

The compatibility renderer does not support 3D decals nodes

### Steps to reproduce

1. Create a new project
2. Add a decal node

### Description

This is more a question than a bug tho. I wonder is there any plan to support 3D decal node for the compatibility renderer in the future or should I use a shader (ie: https://godotshaders.com/shader/decal-shader-for-4-3-compatibility-renderer-transparency-support-no-repeat/ )

Thanks

**Comment by Calinou** [comment]
Closing, as feature proposals should be discussed on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository. This repository is now used for bug reports only.

Make sure to follow the proposal template when opening a new proposal – don't just copy and paste the text you wrote in this issue.

To clarify, there are plans to have decal support in Compatibility, but it will have limitations compared to the implementation in Forward+/Mobile (such as a lower decal count and/or less flexibility in texturing or options).

**Comment by xsellier** [comment]
Thanks for answering @Calinou !

Now if someone search for decals and OpenGL, then will and on this ticket and know that's the support is planned but not for sure <3

Cheers
