### ISSUE TITLE
Auto Brace Complete editor setting is incorrectly described

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#98260]
### Tested versions

4.3.stable

### System information

macOS 15.0.1

### Issue description

The editor setting` text_editor/completion/auto_brace_complete` description doesn't really explain what it currently does. I think it's working as intended, so the description should be changed to make it easier to find user that want to change this behavior:

Current implementation:
![Screenshot 2024-10-17 at 11 12 54](https://github.com/user-attachments/assets/693cfcca-052e-4196-9bc5-0d158916835c)

- This doesn't mention that it also inserts a closing single or double quote, not just parentheses/braces
- It says it completes braces during code completion, but it just inserts additional characters directly when typing and it seems to be completely unrelated to the more advanced code completion functionality. 

A more accurate description could be something like
_"If true automatically inserts a closing brace, parentheses or quote after the cursor when typing one of these characters"_

### Steps to reproduce

Take a look in the editor settings and compare this to how the setting works.

### Minimal reproduction project (MRP)

Just editor needed

**Comment by kitbdev** [comment]
- will be fixed by #97656
