### ISSUE TITLE
I have more than 20 years of programming experience, some groups guide about c++ engine?

### ISSUE THREAD

**Issue by WorkEveryday1** [godotengine/godot#98274]
### Tested versions

I have more than 20 years of programming experience, some groups guide about c++ engine?

### System information

Godot Engine v4.3

### Issue description

I have more than 20 years of programming experience, some groups guide about c++ engine?

### Steps to reproduce

I have more than 20 years of programming experience, some groups guide about c++ engine?

### Minimal reproduction project (MRP)

I have more than 20 years of programming experience, some groups guide about c++ engine?

**Comment by syntaxerror247** [comment]
This is for bug reports. You can ask your question on Godot Forum: https://forum.godotengine.org

**Comment by AThousandShips** [comment]
Indeed this is for reporting bugs, please ask in the forums or [other community channels](https://godotengine.org/community/)
