### ISSUE TITLE
Attempting to install an invalid export template file does not display error messages

### ISSUE THREAD

**Issue by cadence-s** [godotengine/godot#98285]
### Tested versions

4.4.dev [1435247de] and 4.3.stable

### System information

Godot v4.4.dev (1435247de) - macOS 14.7.0 - Multi-window, 1 monitor - Metal (Mobile) - integrated Apple M2 (Apple8) - Apple M2 (8 threads)

### Issue description

Trying to install an invalid export template file ~(very easy to do, how on earth do I properly install custom export templates)~ prints a DisplayServer warning and opens a window titled "Warning!" with nothing in it. No error message for the invalid export template file is printed or displayed.
`scene/main/window.cpp:735 - Entering a window while a window is hovered should never happen in DisplayServer.`
<img width="523" alt="Screenshot" src="https://github.com/user-attachments/assets/f350a9c2-bde1-443f-b6f9-55f3112be56a">
~For some reason in 4.3.stable it doesn't print the console warning but still has the issue (except the window is smaller).~ Never mind, this is just because of dev_build=no, oops. The warning could be an entirely separate issue.

### Steps to reproduce

1. Open Editor > Manage Export Templates
2. Pick Install from File
3. Select anything that's not a valid export template file

### Minimal reproduction project (MRP)

N/A, editor issue

**Comment by syntaxerror247** [comment]
Duplicate https://github.com/godotengine/godot/issues/85862

**Comment by cadence-s** [comment]
Thanks, I don't know why I didn't see that
