### ISSUE TITLE
Runtime errors open script in editor when External Editor is enabled

### ISSUE THREAD

**Issue by bits-by-brandon** [godotengine/godot#98280]
### Tested versions

4.3 stable

### System information

MacOS

### Issue description

When Godot hits a runtime error, it will open the source (gdscript) of the error in the editor. Normally this isn't an issue, but when working with an external editor this becomes quite tedious. When a script is open in both an external editor (or at least VSCode) and Godot at the same time, they tend to overwrite each other's changes. I've spent a good deal of time trying to figure out why changes were not applied, just to realize that a few scripts were opened in the editor and preventing any external changes.

The behavior I expect would be that Godot would open the external editor on error if one is set.

### Steps to reproduce

1. Set an external editor
2. Write buggy code (You know you are an expert at this one)
3. Run Godot
4. Encounter runtime error

### Minimal reproduction project (MRP)

Any project that can produce errors is an MRP. i.e any project.

**Comment by AThousandShips** [comment]
Does it work when checking "Debug with External Editor" under "Debug" in the script editor?

**Comment by bits-by-brandon** [comment]
Oh it does 😅 
I wouldn't of guessed to look there. Thanks!
