### ISSUE TITLE
Animation blending to wrong positions

### ISSUE THREAD

**Issue by SuperMatCat24** [godotengine/godot#98295]
### Tested versions

Tested in 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti - Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz (8 Threads)

### Issue description

When blending between animations, the feet of my character move to (0, 0) before blending to the correct position. There are no keys telling it to reset, and the animations work fine in the animation player. The head also resets t0 (0, 0) when jumping from the idle animation.

https://github.com/user-attachments/assets/8029b678-b855-451d-9b30-c1465b92af3e

https://github.com/user-attachments/assets/8a69eb89-c8e8-4d6d-a1e7-d823bfa384c0

### Steps to reproduce

1. Run the node_2d scene of reproduction project
2. Move around using space and arrow keys and the animations will blend incorrectly

### Minimal reproduction project (MRP)

[Maou Test Project.zip](https://github.com/user-attachments/files/17436196/Maou.Test.Project.zip)

**Comment by TokageItLab** [comment]
There is no bug. You just mixed up value track and bezier track those have different paths. Although it is not recommended, adding the initial value of the missing bezier track to the reset animation solves this problem.

![Image](https://github.com/user-attachments/assets/b25b3414-6a16-4373-9ee0-27458bd8cff2)

Just be aware that the value and bezier tracks with different paths cannot be xfade. As long as you do not use xfade, the solution described above should work.

[Maou.Test.Project_fixed.zip](https://github.com/user-attachments/files/17824178/Maou.Test.Project_fixed.zip)
