### ISSUE TITLE
Can't assign typed array with new array from another class

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#98290]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

MacOS 13.6.7

### Issue description

If I am trying to assign a typed array from another class it will throw an error:
Invalid assignment of property or key 'a_typed_array' with value of type 'Array' on a base object of type 'RefCounted (MyClass)'.

Not sure if this is intended but I don't think so. It works if the Array is not typed.

### Steps to reproduce

Run the code below and it will throw error:
Invalid assignment of property or key 'a_typed_array' with value of type 'Array' on a base object of type 'RefCounted (MyClass)'.

### Minimal reproduction project (MRP)

```
extends Node

var variable: Object

func _ready() -> void:
	variable = Object.new()
	test()


func test():
	var my_class = MyClass.new()
	my_class.a_typed_array = [variable]


class MyClass:
	var a_typed_array: Array[Object] = []
```

**Comment by AThousandShips** [comment]
This is a current limitation, you should use `assign` to get around this for the time being:
```gdscript
my_class.a_typed_array.assign([variable])
```

See:
* https://github.com/godotengine/godot-proposals/discussions/7364

Closing this as it is a known issue, see the discussion above for the work on figuring out how to solve this, thank you for reporting
