### ISSUE TITLE
Manitaining Changelogs

### ISSUE THREAD

**Issue by rishavs** [godotengine/godot#983]
Hi

Can we start maintaining change logs for each release?

Also it will be nice if we start to organize the issues in the tracker by milestone. It gets difficult to follow the project otherwise.

thanks
RS

**Comment by akien-mga** [comment]
The project now uses labels and milestones, so this is partly addressed. An ordered changelog for the upcoming 2.0 release would indeed be a very good thing, I'll create an OpenProject task about that.

**Comment by Calinou** [comment]
We can follow this guide: http://keepachangelog.com/
