### ISSUE TITLE
Wrong lock informations on Image.copy_from

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9831]
I think there is something buggy/missing when Image.copy_from is used. It is not showing an missing .lock() call in the following case

 ```
extends Control

var i = Image.new()
var i2 = Image.new()

func _ready():
	
	i.load("res://transparent.png")
	i.convert( Image.FORMAT_RGBA8 )
	i.lock()
	
	i.set_pixel(0,0,Color(1,0,0,1))
	
	i2.load("res://transparent.png")
	i2.convert( Image.FORMAT_RGBA8 )
	i2.lock()
	i2.copy_from(i)
	#i2.lock() #this lock is needed to get the right colors. I get no error message, get pixel is used without lock()

func _input(event):
	print(i2.get_pixel(0,0))
```

This bug :angry: 

Kubuntu 17.04
Master branch

**Comment by RandomShaper** [comment]
I'm getting the following error message:

> ERROR: Image must be locked with 'lock()' before using get_pixel()
>    At: core\image.cpp:1904

But it appears only in the console window, not in the editor's output pane.

**Comment by RandomShaper** [comment]
@AlexHolly, have you looked at the console window? Do you see the message there?

**Comment by AlexHolly** [comment]
There is no message in console

**Comment by reduz** [comment]
i changed so errors in editor _are_ redirected to the editor console, so you should see them now.
Will close this issue becaue of that.
