### ISSUE TITLE
Editor doesn't remember which screen it was open on

### ISSUE THREAD

**Issue by KingSupernova31** [godotengine/godot#98310]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Mac OS 10.14.8

### Issue description

On a computer with two screens, Godot seems to always open new windows on the primary screen rather than the screen Godot is on.

### Steps to reproduce

1. Open Godot to the project list page.
2. Drag it onto another screen.
3. Click on a specific project to load it.
4. The new window that opens for the project will not be on the same screen as the project list was.

### Minimal reproduction project (MRP)

Any.

**Comment by AThousandShips** [comment]
Solved in:
* https://github.com/godotengine/godot/pull/76085

Will be available in 4.4!

**Comment by KingSupernova31** [comment]
Just upgraded to 4.4, looks like this has indeed been fixed for the editor itself, thanks! However it has not been fixed for the project list, that still always appears in the middle of the primary screen. I've opened a new issue, #103739.
