### ISSUE TITLE
Project-wide find-in-scripts excludes arbitrary files

### ISSUE THREAD

**Issue by KingSupernova31** [godotengine/godot#98311]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Mac OS 10.14.8

### Issue description

The project-wide search dialog for script contents will frequently not find files. In the main project I'm working on, it currently excludes *all* files, returning no results. In some test projects I created, it would sometimes exclude no files, sometimes only some.

I have been unable to figure out what causes this. It doesn't matter whether I search the whole project in `res://` or only some subdirectly, the error can occur in both cases. I've verified that there is no .gdignore file in the folders I'm trying to search.

### Steps to reproduce

1. Download the MRP below and open it in Godot.
2. Go to the "script" tab.
3. Click search > find in files
4. Search for "extends" and get no results.
5. Go to the built-in script on foo.tscn and verify that it contains the string "extends".

Alternatively, it seems pretty easy to cause this issue from scratch. Open a new project, then create a script somewhere, and see if it shows up in the search. If it does, make some minor change like adding a new node or a new script, and repeat. In short order you'll find that one or more of the scripts is not showing up in the search results.

### Minimal reproduction project (MRP)

[search-bug.zip](https://github.com/user-attachments/files/17440053/search-bug.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting! This is a current limitation, please see:
* https://github.com/godotengine/godot-proposals/issues/9436

As there's a proposal open for this I will close this and keep things in one place
