### ISSUE TITLE
3d scene not loading

### ISSUE THREAD

**Issue by Fishfromthemeditrean** [godotengine/godot#98333]
### Tested versions

For some reason when I make a 3d scene add an environment I will see pitch black in the 3d display thing where you see your mesh and things 

### System information

Android Infinix HOT 10 Play Infinix X688B Android 11

### Issue description

Help me in the scene editor where you see the mesh and stuff displays a black screen

### Steps to reproduce

Idk to type here

### Minimal reproduction project (MRP)

Idk what to type here

**Comment by matheusmdx** [comment]
1° This is a place for technical problems related to the engine (aka bugs), not for common questions about how to do stuff, use the official [forum](https://forum.godotengine.org/c/help/6) and [reddit](https://www.reddit.com/r/godot/) for that.

2° You added some light source for the scene? `DirectionalLight3D`, `OmniLight3D`, `SpotLight3D`, setted the sky in `WorldEnvirioment` node?

**Comment by Fishfromthemeditrean** [comment]
I added a world environment a mesh gave it the visual thing so u can see it but u can't see anything in the place where u see the mesh and world environment

**Comment by matheusmdx** [comment]
Please upload some images from what is happening and your godot project to help us pinpoint your problem.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
