### ISSUE TITLE
Custom resource changed by @export_tool_button doesn't mark the resource file as unsaved

### ISSUE THREAD

**Issue by spiralhalo** [godotengine/godot#98331]
### Tested versions

- Reproducible in: v4.4.dev3.official [f4af8201b]
- Not reproducible in: n/a

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 32.0.15.5613) - AMD Ryzen 5 5600H with Radeon Graphics (12 threads)

### Issue description

I'm making a custom Resource using the new tool button.

When the button is pressed, the value of another property is changed, but the Editor doesn't detect the change (i.e. "*" in the title bar) so saving the project does not save the changes on the resource.

By contrast, if I set the same property via a `bool` setter, the Editor will detect the change, presumably since the user changes the bool value, making the overall resource changes saveable.

I tried `emit_changed()` and `notify_property_list_changed()` but to no avail.

Note that the resource is indeed changed, not just a "runtime copy" of it, because if another direct manipulation is done in the inspector after the button derived manipulation, both changes are properly detected. So the expected outcome is that that changes are detected properly without direct manipulation of values in the inspector.

### Steps to reproduce

1. Make a custom class that extends `Resource` and is a `@tool`
2. Make an `@export_tool_button("Click me") var my_button` and another `@export var my_property`
3. Change `my_property` in `my_button`'s callable
4. Make a custom resource file using the custom resource class
5. In the file's inspector, press the button
6. Observe lack of change detection ("*" in editor title bar)
7. Save the project (Ctrl+S) observe lack of change to the file in an external app or git diff

### Minimal reproduction project (MRP)

[mrp-custom-resource-button.zip](https://github.com/user-attachments/files/17442741/mrp-custom-resource-button.zip)

**Comment by AThousandShips** [comment]
You need to use undo/redo, see the [documentation](https://docs.godotengine.org/en/latest/classes/class_%40gdscript.html#class-gdscript-annotation-export-tool-button)

**Comment by spiralhalo** [comment]
@AThousandShips I see! In that case, is it considered working as intended?

**Comment by AThousandShips** [comment]
Yes, or rather that's the system required to track the saved status

**Comment by spiralhalo** [comment]
Well it does work as I wanted with the extra code in place. Thanks for pointing it out!

Closing the issue now...
