### ISSUE TITLE
Godot Editor Crash if base = 0 or 1 [String.num_uint64(number, base, capitalize_hex)]

### ISSUE THREAD

**Issue by LightGardenLudus** [godotengine/godot#98347]
### Tested versions

Godot v4.3.stable (77dcf97d8)

### System information

Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 Threads)

### Issue description

Running a script with the base set to zero or one e.g. "String.num_uint64(15, 0, false)" will either instantly crash or freeze the Godot editor. I don't see how it's useful to set the base to either zero or one, but I expected it to return an error instead of crashing/freezing Godot.

Initially I wanted to find a way to convert binary numbers, and after finding this method I tested it and found it was crashing the editor. 
Note: Base set to a negative integer initially returned an error, but opening Godot after a crash and looping through (e.g. 0-1000) gives me 0-9, A-Z, some common symbols, a-z, more symbols etc. I don't know if this is important or not.

Godot Docs:
https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-num-uint64

### Steps to reproduce

```
@tool
extends EditorScript

func _run() -> void:
	test()

#This will instantly crash Godot
func test() -> void:
	var a:String
	a = String.num_uint64(15, 0) #When base = 0

#This will freeze Godot
func test() -> void:
	var a:String
	a = String.num_uint64(15, 0) #When base = 1
```

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Seems like there are no check for valid base, it should be limited to 2-36 range (functions will only work with standard positional system, and use 0-9, A-Z characters).

Relevant code:
https://github.com/godotengine/godot/blob/44fa552343722bb048e2d7c6d3661174a95a8a3c/core/string/ustring.cpp#L1852-L1859

https://github.com/godotengine/godot/blob/44fa552343722bb048e2d7c6d3661174a95a8a3c/core/string/ustring.cpp#L1890-L1895
