### ISSUE TITLE
Parse error when using custom signals with parameter

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9835]
**Operating system or device - Godot version:**
303370d03d71ad7ea194250fdfc94f7f1928fb47

**Issue description:**
It's impossible to define signal with parameter by using `signal` keyword. 
There is parser error: Expected identifier in signal argument
![signal_param](https://user-images.githubusercontent.com/6129594/28562677-91886a44-7123-11e7-907f-9424ae9c9efc.png)

**Steps to reproduce:**
1. Create new script.
2. Paste this:
```
extends Node
signal param_signal(param1, param2);
```
3. Save

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
There is very slight chance it's related to #9816

**Comment by kubecz3k** [comment]
It seems this commit is the culprit 1936e1d2be1bd4d31803c0ad64cc44951ddda35b

**Comment by kubecz3k** [comment]
Ups, it's not that one

**Comment by Noshyaar** [comment]
Maybe e00630b ?

**Comment by kubecz3k** [comment]
yes, @Noshyaar is right, I can confirm that e00630bfcaef58a8e6d1454e2eaae35bf2848bf4 is guilty 
@bojidar-bg could you take a look?

**Comment by akien-mga** [comment]
Fixed by #9846.

**Comment by bojidar-bg** [comment]
Sorry about that, I guess I should have ran it on some games to check for breaking changes...
