### ISSUE TITLE
4.3: `@export var texture_var := Texture2D` export all classes

### ISSUE THREAD

**Issue by llama-nl** [godotengine/godot#98355]
### Tested versions

4.3.stable

### System information

Android 14 - Compatibility Renderer

### Issue description

https://github.com/user-attachments/assets/adf7a038-a64d-45d1-a43d-3dcbe2e3d4f5

`@export var texture_name := Texture2D` export all the classes. Even when loading resources from file system. filter shows all the file type (`.png, .mesh, ...`)

### Steps to reproduce

Write `@export var texture_name := Texture2D` in script

**Comment by dalexeev** [comment]
It's incorrect (you are using a class as a value):

```gdscript
@export var texture_name := Texture2D 
```

Should be:

```gdscript
@export var texture_name: Texture2D 
```
