### ISSUE TITLE
Transparency on low poly objects is broken

### ISSUE THREAD

**Issue by lw64** [godotengine/godot#98377]
### Tested versions

godot 4.3

### System information

Arch linux

### Issue description

I have a low poly modeled object, where you can see some faces also from the backside. I use a transparent material on it, some parts are opaque, some parts are translucent depending on the texture. I tried multiple alpha modes, of which the depth pre-pass should work in this situation as far as I have read the docs correctly- But there are not only sorting issues. sometimes some faces behind an translucent face are completely missing, sometimes the translucency is directly layered over the sky, or only the backside of opaque faces, with faces in between missing.

### Steps to reproduce

Here is a screen recording, only the red parts of the bottle are fully opaque.

### Minimal reproduction project (MRP)

[Bildschirmaufzeichnung vom 2024-10-20 20-38-52.webm](https://github.com/user-attachments/assets/09c4109d-6124-420a-a037-bf94adbb2a67)

**Comment by cryoboltinteractive** [comment]
Could you please provide this model? The issue needs to be checked with the engine.

**Comment by lw64** [comment]
[bottle.zip](https://github.com/user-attachments/files/17509149/bottle.zip)
here is the model together with the texture

**Comment by cryoboltinteractive** [comment]
![image](https://github.com/user-attachments/assets/ef4034f1-aa84-444d-9872-234648098630)

Opened the file in blender, seems like this is a very weird way of dealing with alpha. Usually you'd have the lid as a separate object and the liquid also as a separate object. Even blender will struggle to achieve a desired look.
There will be Z fighting as Alpha is calculated per face and not on UV pixels. and this is true for any 3D Program.
The standard material will not work for this model and texture, unless you separate out the Lid, Liquid and the Jug.

**Comment by lw64** [comment]
I see. Do you think having two separate passes, the first one with alpha clip, the second with alpha depth prepass, would fix it?

**Comment by cryoboltinteractive** [comment]
It won't as the second alpha depth pass will be calculated on the faces and not on the alpha clip data.
You could write a custom shader, but I'm not too sure about that, and whether it would be optimized.

**Comment by lw64** [comment]
I see, thanks for the really helpful advices!! :)

**Comment by lw64** [comment]
That depth is per-vertex, and therefore dividing faces might help

**Comment by Zireael07** [comment]
That is pretty standard for any 3d engine out there

**Comment by lw64** [comment]
Well I didnt know it, and I think godot targeting beginners its not that useless, but I am not an expert here :)
