### ISSUE TITLE
Loading a saved packed TileMapLayer with scenes duplicates the scenes

### ISSUE THREAD

**Issue by IZ-sandwich** [godotengine/godot#98371]
### Tested versions

reproducible in v4.3.stable.official [77dcf97d8]

### System information

windows 11 Home 23H2

### Issue description

When saving a TileMapLayer as a packed scene and reloading it any scene that were present on the tilemap layer are duplicated. One set comes of scenes is the ones who's owner is changed (to be saved) and another from the tilemap layer itself - it saves the original properties of the scenes and when loaded instantiates new ones.

While I see this being a feature - you want to somehow save the original state of the TileMapLayer, to me it comes across as a bug as the scenes from the TileMapLayer are instantiated again when loading a saved TileMapLayer producing twice the amount of scenes. Perhaps there should be a flag on the TileMapLayer to indicate whether you want to save original scene state.

### Steps to reproduce

Can open the attached project or create a brand new one with steps below:
- create a tile map layer and tile set
- create a tile scene with a 2d sprite
- add the tile scene to the tileset
- place the tile scene on the tile map layer
- add a script which changes the owner of the tile map layer and its children to the root (such that all is saved)
- add two buttons, one to save scene, one to delete and load scene
```
func set_owner_recursive(node:Node, new_owner: Node):
	for child in node.get_children():
		child.owner = new_owner
		set_owner_recursive(child, new_owner)

func _on_save_button_pressed() -> void:
	set_owner_recursive(test_scene, test_scene)

	var scene = PackedScene.new()
	scene.pack(test_scene)
	ResourceSaver.save(scene, test_save_path)

func _on_load_button_pressed() -> void:
	remove_child(test_scene)
	test_scene.queue_free()

	var new_node = load(test_save_path).instantiate()
	add_child(new_node)
```
- run, press save, then press load
- observe in 'remote' that the tile scene has been duplicated

### Minimal reproduction project (MRP)

[testtilemapduplication - Copy.zip](https://github.com/user-attachments/files/17452320/testtilemapduplication.-.Copy.zip)

**Comment by IZ-sandwich** [comment]
My current workaround is to delete the TileMapLayer containing the scenes while saving the child scenes temporarily, and recreate the TileMapLayer and add back the child scenes before assigning the owners and saving/packing.

with the example the workaround look like this:
```
func _on_save_button_pressed() -> void:
	var temp_array: Array[Node] = []
	for node in tile_map_layer.get_children():
		temp_array.append(node)
		tile_map_layer.remove_child(node)
	test_scene.remove_child(tile_map_layer)
	tile_map_layer.queue_free()

	var new_tile_map_layer = TileMapLayer.new()
	for node in temp_array:
		new_tile_map_layer.add_child(node)
	test_scene.add_child(new_tile_map_layer)

	set_owner_recursive(test_scene, test_scene)
	...
```

This means any properties need to be copied over for the new TileMapLayer, but I think the workaround should work for now.

**Comment by KoBeWi** [comment]
That's because you are setting owner of instantiated scenes. You should skip them in your method.

**Comment by IZ-sandwich** [comment]
That is intentional. The instantiated scenes can have updated state that I want to save, as opposed to the the default state saved within the TileMapLayer.

**Comment by KoBeWi** [comment]
The TileMapLayer keeps references to its scenes internally. They are not saved, so every time the TileMapLayer is created, it assumes it's a "fresh" one and re-creates the scenes again. You can prevent that by disabling the layer or removing scene tiles, then only your copies will remain.

**Comment by IZ-sandwich** [comment]
I think removing scene tiles will do the trick for now, thanks for the explanation. What did you mean by disabling the layer?

**Comment by KoBeWi** [comment]
Setting `enabled` to false when loading. Only viable if you have separate layer for only objects.
