### ISSUE TITLE
The StreamPeerTCP on the web sends a string of data when the connection is successful

### ISSUE THREAD

**Issue by TsubakiLoL** [godotengine/godot#98389]
### Tested versions

- v4.3.stable (77dcf97d8)

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.2756) - Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz (8 Threads)

### Issue description

When the Godot  program is running on the web, StreamPeerTCP will send the following string of data after the connection is successful:
    [0, [71, 69, 84, 32, 47, 32, 72, 84, 84, 80, 47, 49, 46, 49, 13, 10, 72, 111, 115, 116, 58, 32, 49, 50, 55, 46, 48, 46,]
Using the ASC II code to translate, the result is as follows:
    GET / HTTP/1.
There is no such behavior on Windows(exe),what causes this?

### Steps to reproduce

You can open the following project(MRP) and run the project on the Windows (with console) and the web side, and click "server" in the project running on the Windows side, click "client" in the project running on the web side, and view the console of the project running on the desktop side, and you can see the received data

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17463180/test.zip)

**Comment by timothyqiu** [comment]
I believe that's the WebSocket handshake[^1].

Emscripten emulates POSIX TCP Sockets over WebSockets[^2].

[^1]: https://en.wikipedia.org/wiki/WebSocket#Opening_handshake
[^2]: https://emscripten.org/docs/porting/networking.html#emulated-posix-tcp-sockets-over-websockets
