### ISSUE TITLE
Shrink image to fit a max Vector2 size

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#9840]
Suggestion for a feature that would be really handy for image resizing control.
A way to easily set a maximum height & width on a texture, and make the image automatically "fit" within that maximum size.

_For example, you have a picture of x: 1000 and y: 100, and you want to make sure it can fit in a 100x100 square window, it would turn it to a x: 100, y:10 sized image in order to fit the window.

The **GDScript** equivalent would be something akin to the following;

```
# Update image to prevent size to exceed max_size.
# Vector2 image_size, Vector2 max_size
func update_image_size(image_size, max_size):
	# Picture ratio
	var ratio = null
	
	# If texture height is greater than the parent, set to fit parent
	if(image_size.y > max_size.y):
		# Update ratio
		ratio = max_size.y / image_size.y
		
		# Fit height to parent height
		image_size.y = max_size.y
		
		# Fit width to match aspect ratio
		image_size.x *= ratio
	
	# If texture width is greater than the parent, set to fit parent
	if(image_size.x > max_size.x):
		# Update ratio
		ratio = max_size.x / image_size.x
		
		# Fit height to parent height
		image_size.x = max_size.x
		
		# Fit width to match aspect ratio
		image_size.y *= ratio
	
	# Return the updated image size
	return image_size
```

This is something that would benefit any 2D game developer working with textures and UI. :)
(Perhaps something equivalent could be made for resizing 3D models as well - if it is not already available)

**Comment by Noshyaar** [comment]
TextureRect can already do this?

**Comment by KoBeWi** [comment]
Yep, you can do this using TextureRect with Expand enabled and Stretch Mode set to Keep Aspect.

**Comment by ivanskodje** [comment]
@akien-mga Perhaps this issue can be locked, if everyone agree that we can use TextureRect.
Otherwise this would be a neat thing to have on a Sprite node. 
Opinions?

**Comment by akien-mga** [comment]
Given that the mentioned use case was for textures in UI, it seems that it's what TextureRect was designed for indeed, so let's close.

If there's a use case where a Control is not cutting it and Sprite would need such feature, we can probably open a new issue to discuss it.
