### ISSUE TITLE
Script Editor undo breaks after saving

### ISSUE THREAD

**Issue by quinnyo** [godotengine/godot#9841]
**Operating system or device - Godot version:**
3.0 master branch - since a couple of weeks ago at least
tested on windows and linux, multiple projects

**Issue description:**
After saving, undo behaves strangely and any undo history that should be there is gone. I've been noticing this occasionally for a while but only just realised it happens once I've saved. This happens regardless of if I've edited the script.

It's a bit weird but it goes like this:

<Save script and/or scene>
Ctrl-Z - last line of open script is cleared/erased
Ctrl-Z - last line re-appears, next line up clears
Ctrl-Z - repeat for each line, going up from the bottom

Redo reverses the process (I guess as it should).

**Comment by AWKgamedev** [comment]
I was having the same problem and I think found out what causes the undo bug, it's the "Convert Indent On Save" option in Editor Settings > Text Editor > Indent, unchecking the option fixes the undo.

**Comment by akien-mga** [comment]
cc @Paulb23

**Comment by quinnyo** [comment]
Just confirming that turning off convert indent (and then restarting the editor) has stopped it happening.
