### ISSUE TITLE
Errors compiling for X11 32bits

### ISSUE THREAD

**Issue by PerduGames** [godotengine/godot#9842]
Debian, Godot 2.1.3

I am trying to compile X11 32bits and I get all these errors:

```
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lXinerama
/usr/bin/ld: cannot find -lXcursor
/usr/bin/ld: cannot find -lXrandr
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lfreetype
/usr/bin/ld: cannot find -lpng16
/usr/bin/ld: cannot find -lasound
/usr/bin/ld: cannot find -lpulse-simple
/usr/bin/ld: cannot find -lpulse
/usr/bin/ld: cannot find -lz
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.opt.debug.32] Error 1
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
This is not Godot-specific, please refer to your Debian documentation on cross-compilation: https://wiki.debian.org/CrossCompiling

Please keep in mind that this is not a support forum, but an issue tracker for bug reports and feature proposals of the engine. For support requests you can use one of the many other community channels: godotengine.org/community

**Comment by akien-mga** [comment]
Here's how we handle cross-compiling for 32-bit Linux from Ubuntu 14.04: https://github.com/GodotBuilder/godot-builds/blob/master/.travis.yml#L122-L128

**Comment by PerduGames** [comment]
Thanks, I think installing will resolve.
