### ISSUE TITLE
Enter Key does not save Property values in Inspector

### ISSUE THREAD

**Issue by plangworthy** [godotengine/godot#9843]
**Operating system or device - Godot version:**
MacOS 10.12.6
Godot 2.1.3.stable.official

**Issue description:**

When editing values in the Inspector, pressing the Enter key (on the number pad) does not save the edited value.

Pressing the Enter key should save the new property value the same way as using the Return key.

**Steps to reproduce:**
Alter a property value in the Inspector and press the Enter key on the Number pad.

Given that most properties are numeric, anyone with a full NumPad keyboard will encounter this issue almost immediately.

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Can't reproduce on Linux (Mageia 6) with either Godot 2.1.3-stable and the current master branch, so assuming it is macOS-specific.

**Comment by bruvzg** [comment]
NumPad Enter works on Windows 10 (keycode==KEY_RETURN) and Linux Debian 9 (keycode==KEY_ENTER), doesn't on macOS 10.12.5 (keycode==KEY_KP_ENTER).

**Comment by reduz** [comment]
@BastiaanOlij could you give a check to this one? seems OSX related

**Comment by akien-mga** [comment]
Fixed already by @bruvzg in #9872.
