### ISSUE TITLE
Error spam when using textures in RichTextLabel

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#98430]
### Tested versions

4.3 stable, 4.4 dev3

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When opening a project, I get various texture loading errors. The project was originally developed on 4.2, but when opening in 4.3, a spam of errors.
![bug](https://github.com/user-attachments/assets/1cf2cd12-6c73-4cc8-9d08-07ef21ed40af)

`Resource file not found: res:// (expected type: Texture2D)`

### Steps to reproduce

Download and open MRP

### Minimal reproduction project (MRP)

[bug.zip](https://github.com/user-attachments/files/17482268/bug.zip)

**Comment by JekSun97** [comment]
The problem turned out to be in RichTextLabel, the error says that the texture is not found in BBCode, but it is found and displayed as it should be

**Comment by timothyqiu** [comment]
This is because there are two `[img]` tags in the BBCode and the first one does not have path specified.

```
[center]1235[img=center,top][img=20x16]res://ico/mn.png[/img]
```

You can change it to something like this:

```
[center]1235[img=center,top,20x16]res://ico/mn.png[/img]
```

**Comment by JekSun97** [comment]
@timothyqiu When I use your version, the texture goes beyond the text
![asd](https://github.com/user-attachments/assets/3372f0e4-45a0-4ebc-8599-39975a7ad226)
I tried removing "top" from the code, but it didn't solve the problem

**Comment by bruvzg** [comment]
> When I use your version, the texture goes beyond the text

That's how it should work: `center,top` is the center of the image aligned to the top of the text.

**Comment by AThousandShips** [comment]
See the description in the [documentation](https://docs.godotengine.org/en/latest/tutorials/ui/bbcode_in_richtextlabel.html#doc-bbcode-in-richtextlabel-image-and-table-alignment)
