### ISSUE TITLE
Lower toolbar tooltips flickering

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#98449]
### Tested versions

- Not reproducible in 4.3 stable
- 4.4 dev (b3bcb2dc14691f7729984128dca26a844f662fa1)

### System information

Windows 11, GTX 4080

### Issue description

![editor_tooltip_flickering](https://github.com/user-attachments/assets/ba7a5a06-bef7-4b7d-873b-635f297ebf4f)

### Steps to reproduce

^^

### Minimal reproduction project (MRP)

No need - too easy to reproduce in any project

**Comment by timothyqiu** [comment]
I can't reproduce this.

> Godot v4.4.dev (533c616cb) - Arch Linux #1 SMP PREEMPT_DYNAMIC Sun, 20 Oct 2024 18:20:12 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (nvidia; 560.35.03) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads)

**Comment by matheusmdx** [comment]
Bisected to #97961, @timothyqiu 

![image](https://github.com/user-attachments/assets/c5347132-39b8-4fff-8742-819a282dff34)

<br>

> I can't reproduce this.

Maybe is a windows specific regression?

Godot v4.4.dev (eaadb467c) - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

**Comment by matheusmdx** [comment]
Yes, seems to affect some other controls, but i didn't find a pattern yet, some tooltips flick, others simple don't appear and others works as expected.

https://github.com/user-attachments/assets/1dfbcda9-41f6-47a6-8690-8c243e9bde49
