### ISSUE TITLE
Canvas Layer "Follow Viewport" property does the opposite of what it is supposed to

### ISSUE THREAD

**Issue by verity147** [godotengine/godot#98463]
### Tested versions

Godot: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 Ti (NVIDIA; 32.0.15.6109) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

This is moreso a case of unexpected behaviour or bad description but either way it wasted a lot of my time today.

Project setup is a 2d scene with basic top down character controller, a camera moved via remote transform on the character and a CanvasLayer with ColorRect because I am trying to learn screen reading shaders.

**Issue:**
When enabling "Follow Viewport" on the CanvasLayer, it stops following the camera and stays in its default position. When disabling "Follow Viewport", it follows the camera.

In this screenshot the ColorRect is just white and not following the player (small icon in the center) even though the option is enabled.
![Screenshot 2024-10-23 162223](https://github.com/user-attachments/assets/21d2a63b-bdc4-45c5-ab0a-00ab001a19b5)

**Why I think this is a bug:**
From the docs of "Follow Viewport": "If enabled, the CanvasLayer will use the viewport's transform, _so it will move when camera moves_ instead of being anchored in a fixed position on the screen."
I thought I had to enable it to make it follow the camera as the name also indicates, but it works exactly opposite.

Either the name and description need to change or the bool is flipped.

### Steps to reproduce

Use the MRP below and turn Follow Viewport on and off and observe the behaviour detailed above.

### Minimal reproduction project (MRP)

[Follow Viewport.zip](https://github.com/user-attachments/files/17494175/Follow.Viewport.zip)

**Comment by TheSpartanK** [comment]
I was also going to post exactly this report yesterday. Even though it works, it's totally counter-intuitive. I would also request this is swapped around

**Comment by DiddyRiese** [comment]
I can confirm I have the same issue in my project. Currently, `CanvasLayer, Follow Viewport, Enabled = true` **_stops_** the camera from following the viewport, which is _the exact opposite behavior_ as what's described in the tooltip.

At least the good news, as I suspect, is that this will be a very easy fix :)
