### ISSUE TITLE
Remove empty line after header section in config files

### ISSUE THREAD

**Issue by RichyHBM** [godotengine/godot#9848]
**Operating system or device - Godot version:**
Any OS, master branch.

**Issue description:**
Following on from #9818, it has been suggested that the config files would be neater if there were not a new line after the [] section header

From:
```
config_version=3

[application]

config/name="Platformer"
config/icon="res://icon.png"
run/main_scene="res://stage.tscn"
```

To:
```
config_version=3

[application]
config/name="Platformer"
config/icon="res://icon.png"
run/main_scene="res://stage.tscn"
```

**Comment by RichyHBM** [comment]
PR available if this is deemed wanted :)

**Comment by akien-mga** [comment]
I'm not convinced yet about the change, any other opinions?

**Comment by groud** [comment]
I personally prefer the new version, as I like compact code.
But it is not that important... ^^

**Comment by RandomShaper** [comment]
I like the proposal. Maybe it's .ini file nostalgia.

This way, related things are together in compact blocks. As with any formatting decision, this is tied to how your brain is wired for pattern matching.

Mine is more used to this new style.

**Comment by akien-mga** [comment]
TOML (which inspired TSCN) also uses this proposed style it seems: https://en.wikipedia.org/wiki/TOML

**Comment by Noshyaar** [comment]
Personally I'd like the section header to stand out, but either way is fine.

**Comment by akien-mga** [comment]
We've discussed this briefly on IRC, and though there is no strong opposition, there is also no strong agreement - the consensus seems to be that we like the current style with section headers standing out.
