### ISSUE TITLE
Getting height or width of image returns 0 on android.

### ISSUE THREAD

**Issue by karolgotowala** [godotengine/godot#9849]
Android 4.0 Godot 2.13

Functions `get_width()` and `get_height()` returns `0` only on Android platform.

Call `get_width()` or `get_height()` on any image thru Android platform to see it happen.

[YT showcase](https://youtu.be/45iVtimD9zA)

**Comment by vnen** [comment]
Duplicate of #2997. This is a limitation of the GLES2 backend, so it can't be fixed.

**Comment by karolgotowala** [comment]
Could be written in "Method Description" at engine built-in search help function, but still thanks for your time. :]
