### ISSUE TITLE
C#: GD0102 error when making a class that inherits Resource

### ISSUE THREAD

**Issue by InkONat** [godotengine/godot#98507]
### Tested versions

4.4.dev3

### System information

Windows 11 - Godot 4.4.dev3

### Issue description

I have created a class PlayerStats for my game that inherits Resource:

![Screenshot_20241024_231925](https://github.com/user-attachments/assets/5c9a34a3-eea1-4d90-901d-1b998c0646f5)

When trying to export a property with that class, the project fails to build because of the GD0102 error:

![image-159](https://github.com/user-attachments/assets/3c6e3111-2f18-4404-a82e-35c444a20527)
![image-59](https://github.com/user-attachments/assets/38bee375-32aa-4a36-8406-b7893907af21)

Expected behavior should be the project being able to successfully build, with no errors, since PlayerStats inherits Resource and should act like any other custom resource made in gdscript.

### Steps to reproduce

- Make a new cs script
- Create a new class that inherits Resource and is a GlobalClass
- Make a new scene with any node with another cs script
- Export a new property that is of that new class
- Try building the project

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
Use typed arrays (`Godot.Collections.Array`) instead of C# arrays. See also:

* [Variant-compatible types](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_variant.html#c-sharp-variant-compatible-types)
* [Similar issues](https://github.com/godotengine/godot/issues?q=is%3Aissue+GD0102)

**Comment by InkONat** [comment]
> Use typed arrays (`Godot.Collections.Array`) instead of C# arrays. See also:
> 
> * [Variant-compatible types](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_variant.html#c-sharp-variant-compatible-types)
> * [Similar issues](https://github.com/godotengine/godot/issues?q=is%3Aissue+GD0102)

That fixed the issue :D
