### ISSUE TITLE
Godot 4.3, error messages: scene/main/node.h:446 - Parameter "data.tree" is null , when open a scene with SoftBody2D node (SoftBody2D plugin) 

### ISSUE THREAD

**Issue by minamichandevs** [godotengine/godot#98517]
### Tested versions

- Reproducible in Godot v4.3.stable.official [77dcf97d8]

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.4502) - 12th Gen Intel(R) Core(TM) i5-12450H (12 Threads)

### Issue description

The editor gives 2 error messages: scene/main/node.h:446 - Parameter "data.tree" is null , every time I open a scene with a SoftBody2D node. 

![image](https://github.com/user-attachments/assets/1f7f0bf6-b18d-4a2c-abcc-337270c73365)

### Steps to reproduce

Start a new project
Install SoftBody2D plugin from the AssetLib
Create a scene with Node2D as scene root
Add a SoftBody2D node
Load a .PNG image to the property: SoftBody2D - Polygon2D - Texture. 
Close and then Open the scene in the editor will trigger the error messages. 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
This is likely a bug in the plugin, not in the engine, please report this to the plugin author to confirm it is not a bug there
