### ISSUE TITLE
[Documentation Generation] make_rst.py fails to generate rst files for any gdscript generates xml files.

### ISSUE THREAD

**Issue by NovaDC** [godotengine/godot#98526]
### Tested versions

4.3.3 - master clone
4.2 - stable clone

### System information

Window 11, Python 3.12.3

### Issue description

NOTE: The following example gdscript I used here was named ```parse_script.gd```

When using a xml documentation file generated using the ```--doctool``` and ```--gdscript-docs```, the generated xml doc file cannot be written to disc. Instead it gives an output like this:
```Checking for errors in the XML class reference...
Generating the RST class reference...
Traceback (most recent call last):
  File "C:\Users\Me\Godot\make_rst.py", line 2638, in <module>
    main()
  File "C:\Users\Me\Godot\make_rst.py", line 814, in main
    make_rst_class(class_def, state, args.dry_run, args.output)
  File "C:\Users\Me\Godot\make_rst.py", line 913, in make_rst_class
    with open(
         ^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Me\\Godot\docoutputtest\\classes\\class_"parse_script.gd".rst'
```

More importantly, it appears that when using ```--dry-run``` with ```make_rst.py```, no errors are found.

Upon further inspection this appears to be fixed when editing the xml doc file's ```<class name="&quot;parse_script.gd&quot;" ...``` to remove the ```&quot;```s.

Most likely this is due to the fact that whenever is used to determine the file name of the .rst file uses the ```class```'s ```name``` attribute directly, instead of filtering it for characters impossible to use in filenames.

Instead of fixing this directly I'm making this a issue because:
1. I'm not confident enough in my skills to directly make a pr for a large project's doc generation script like this.
2. I'm not sure if this would break an expected naming or other formatting conventions expected with Godot's .rst doc formatting.

**Comment by dalexeev** [comment]
* @NovaDC Please test #98533.

**Comment by dalexeev** [comment]
> Should the issue be closed now?

No, the issue should be open until the PR is merged.
