### ISSUE TITLE
(4.4-dev3) Bad spacing in Text Editor when Code Folding is disabled

### ISSUE THREAD

**Issue by caioraphael1** [godotengine/godot#98521]
### Tested versions

4.4-dev3

### System information

Windows 10, Ryzen 3 3300x, 16gb RAM 2666mhz, GTX 1660 6gb.

### Issue description

I'm not sure if this is a bug, or is intended, so I apologize in advance. Either way, I dislike the new look.

When Code Folding is disabled, there's no spacing between the number and the code.

4.4-dev3
![image](https://github.com/user-attachments/assets/1f276f4b-31b1-4df9-bdea-a7ad237bcbbe)

4.3-stable
![image](https://github.com/user-attachments/assets/5ed8e705-4610-4725-a912-ad8b6699643e)

Also, if possible, I'd like to understand the changes in the overall theme in the editor. Why does everything seem bold and brighter?

4.4-dev3
![image](https://github.com/user-attachments/assets/ddf97621-9cf0-409e-a5d2-a7a86bc56c6e)

4.3-stable
![image](https://github.com/user-attachments/assets/3ad5491c-8cac-4375-953c-b955025d4b74)

I personally didn't like at all the theme changes.

### Steps to reproduce

Don't apply.

### Minimal reproduction project (MRP)

Don't apply.

**Comment by AThousandShips** [comment]
Do you mean 4.4.dev3? Otherwise please try a more recent version like 4.3.stable or 4.4.dev3

**Comment by caioraphael1** [comment]
I have downgraded the project from 4.4-dev3 to 4.3-stable, and the line spacing was fixed, but the high saturation colors in the editor was not. 

After messing around, I've decided to disable 2D HDR and it worked. For some reason the 2D HDR is affecting the colors in the editor as well, which I don't think is intended

**Comment by matheusmdx** [comment]
Bisecting points to #92865 as the culprit, @rune-scape

![image](https://github.com/user-attachments/assets/3f62e03b-3db7-4e89-9e5c-6055a329a433)

**Comment by Calinou** [comment]
The brightness issue is due to https://github.com/godotengine/godot/issues/80868. It could be fixed by using different opacity values in the editor theme when HDR 2D is enabled in the project settings, but the alpha factors need to be caredully chosen.
