### ISSUE TITLE
Wireframe Shader bugged in Forward+, does not work at all in Compatibility

### ISSUE THREAD

**Issue by tetrapod00** [godotengine/godot#98532]
### Tested versions

Master (4.4.dev.gh [6732a0fd8])
4.3

### System information

Godot v4.4.dev (6732a0fd8) - Windows 10.0.19045 - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 threads)

### Issue description

Tested this simple wireframe shader:
```glsl
shader_type spatial;
render_mode wireframe;
uniform vec3 line_color = vec3(1.0, 0.0, 0.0);
void vertex() {}
void fragment() {
    ALBEDO = line_color;
}
```

**It renders inconsistently in the renderers:**
I suspect that Forward+ looks wrong due to a bug, possibly hardware specific. 
Compatibility may not work at all due to an undocumented limitation. The spatial shader docs for the `wireframe` render mode only say "Geometry draws using lines.", and make no mention of renderer limitations.

**Forward+. Hard to see, but there are red firelies within the black.**
![godot windows editor x86_64_VYdb63Y79v](https://github.com/user-attachments/assets/6910dd3f-9ff9-440d-9070-081b1534c0f4)

https://github.com/user-attachments/assets/1f00d3ad-63e7-46fa-995a-fe907a1d2eca

**Mobile:**
![godot windows editor x86_64_ST6W4tB9BX](https://github.com/user-attachments/assets/8447704a-e5ca-41b8-993c-1c6e61c0b60c)

**Compatibility:**
![godot windows editor x86_64_ymLhaglzHH](https://github.com/user-attachments/assets/c0a1ddb0-e545-4d46-8203-8ae12b580103)

**The `Display Wireframe` option does work in all three renderers:**
**Forward+:**
![godot windows editor x86_64_IKQYLnt73t](https://github.com/user-attachments/assets/eeff30ed-699f-45b5-8f43-ea6180bb0e3c)

**Mobile:**
![godot windows editor x86_64_KX2kGbp74N](https://github.com/user-attachments/assets/90424ffd-dfc1-4cb7-865d-da1936036fd1)

**Compatibility:**
![godot windows editor x86_64_pz33ranYSk](https://github.com/user-attachments/assets/323f7f1d-9942-4b79-863e-106113745cdc)

### Steps to reproduce

Add a `MeshInstance3D` with a capsule mesh. Give it a `ShaderMaterial` with this shader. Try the various renderers.
```glsl
shader_type spatial;
render_mode wireframe;
uniform vec3 line_color = vec3(1.0, 0.0, 0.0);
void vertex() {}
void fragment() {
    ALBEDO = line_color;
}
```

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
This occurs because wireframe doesn't disable the depth prepass, but it should. Mobile doesn't use a depth prepass, so it works there.

**Comment by tetrapod00** [comment]
Is the fact that compatibility doesn't work simply a limitation that should be documented?

**Comment by Calinou** [comment]
> Is the fact that compatibility doesn't work simply a limitation that should be documented?

Yes, wireframe rendering isn't implemented there yet.

**Comment by clayjohn** [comment]
Looks like two different issues:
1. Forward plus is ignoring the wireframe mode when doing the depth prepass
2. Compatibility is ignoring the render mode for wireframe. 

Both should be easy fixes

**Comment by CodeSmith32** [comment]
Oddly enough (and for those who need a fix right now), setting the transparency of the MeshInstance to something like 0.5 fixes the black material.

Good enough for my case since I'm just debugging. (Glad I randomly decided to fiddle with transparency.)
