### ISSUE TITLE
Add/Remove Folders & Files File System

### ISSUE THREAD

**Issue by Abystus** [godotengine/godot#9854]
**Operating system or device - Godot version:**
Windows 10 64 bit - Godot 2.1.3

**Issue description:**
Unable to add/remove folders and files from the File System window. Folders and files must be manually created/deleted outside of the application. A right-click menu would fit perfectly here to provide the desired functionality.

**Comment by gizaha** [comment]
Hello Abystus. I'm searching a way to extract the 360 sprites from killer instinct arcade character select screen. I want to inject them to snes KI. I don't know the compression nor i can easily use the mips mame debugger. Sorry i mentioned it here, but i didn't find nowhere in internet a way to contact you. 
You can contact at gizaha1@gmail.com. Thank you.

**Comment by KoBeWi** [comment]
This is already implemented. Linked PR didn't reference here properly. (as for creating files, 3.1 added New Resource button)

**Comment by akien-mga** [comment]
Thanks, closing.
