### ISSUE TITLE
Colored icons are tinted with editor accent color

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#98540]
### Tested versions

v4.4.dev.custom_build [61accf060]

### System information

Godot v4.4.dev (61accf060) - macOS 14.5.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

The yellow circle of the output button indicates a warning:

![1](https://github.com/user-attachments/assets/c30338d5-ed3a-4e7b-ab76-cdb6808fdf60)

However, when the button is pressed it turns pale green:

![2](https://github.com/user-attachments/assets/a6eec5e5-21df-4fa5-a5ea-05b76c7e85ed)

If the icon saturation is set to 2 it gets bright green:

![3](https://github.com/user-attachments/assets/27b8d75c-01f5-4df5-a7f3-174e4e6612de)

This changes the meaning of the icon to the opposite and can be confusing to users because green means success. Which is why I'm reporting this as an issue

Same happens in log filter buttons:

![4](https://github.com/user-attachments/assets/866806c3-be0d-478c-823e-91b7dfd736c2)

Buttons with colored icons should have special treatment and never be tinted. Tint only makes sense for monochrome icons

### Steps to reproduce

Set icon saturation to 2. You can also experiment with different accent colors, personally I use a more saturated shade of blue which makes the problem more noticeable

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
This should likely be fixed by adding theme type overrides to buttons that use fully colored icons.

I'd keem the modulation for monochrome icons that only have a small part of the icon colored (e.g. "Add resource" icons where only the + is green).
