### ISSUE TITLE
Hardware performance issues cause items to be lost

### ISSUE THREAD

**Issue by Rundll86** [godotengine/godot#98550]
### Tested versions

the newest, v4.3

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - GeForce GT 240 - AMD Athlon(tm) II X2 250 Processor (2 Threads)

### Issue description

My computer is so bad that I can't use the forward+ mode of Godot 4.3, and now the engine crashes when I open the editor for this rendering mode, but I accidentally set a project that was originally rendered in compatibility mode to forward+ rendering, and now I can't open the editor and I can't fix the rendering mode.

### Steps to reproduce

1. getting your computer old and making sure it performs can't be rendered using the forward+ mode
2. open a project that is rendered in compatibility mode
3. convert it to forward+ rendering mode
4. follow the pop-up window to restart the editor
5. editor crashed

### Minimal reproduction project (MRP)

Any project (including empty projects with nothing) can trigger this bug, this is [my full project](https://github.com/Rundll86/Mind-s-try)

**Comment by AThousandShips** [comment]
To fix this you can edit the project file, starting with 4.4 this is solved by switching the rendered automatically if not supported, see:
* https://github.com/godotengine/godot/pull/97142

You can also open it directly from the command line with `godot --rendering-driver opengl3 project.godot`

**Comment by Rundll86** [comment]
it works,thanks so much!
