### ISSUE TITLE
I can't export project to mac on mac m1 15.0.1 godot 4.3

### ISSUE THREAD

**Issue by pyharbor** [godotengine/godot#98573]
### Tested versions

mac m1 15.0.1 - godot 4.3 - forward+

### System information

mac m1 15.0.1 - godot 4.3.stable.official [77dcf97d8] - forward+
I have installed xcode and run the command
sudo xcodebuild -license accept

### Issue description

Whenever I try to export the project it freezes at this point
<img width="1390" alt="Screenshot 2024-10-27 at 1 59 21 AM" src="https://github.com/user-attachments/assets/90877dab-5fa5-4680-bf37-af8574602c0b">

### Steps to reproduce

1. install the export templates
2. click the Project > Export > macOs (runnable) > Export Project
3. The first bar appears to prepare many assets, files, and/or scenes and then gets stuck on the second bar never making progress
<img width="1390" alt="Screenshot 2024-10-27 at 1 59 21 AM" src="https://github.com/user-attachments/assets/7f56dad7-1d68-49e0-a615-545239d069a2">

### Minimal reproduction project (MRP)

The project is too large to supply here
Upon loading the project there are 300 warnings and 0 errors.
Despite this it still fails to export
<img width="1725" alt="Screenshot 2024-10-27 at 2 07 42 AM" src="https://github.com/user-attachments/assets/fbe3aa18-ae3d-4f1f-80ff-bebd866892be">

**Comment by pyharbor** [comment]
I let the screen run for a prolonged period of time (despite it not giving any logs or notifications) and it did complete and produce a functional .dmg file!

**Comment by Walter909** [comment]
> I let the export function run for a prolonged period of time (despite it not giving any logs or notifications) and it did complete and produce a functional .dmg file!

Were you able to get it to work?
