### ISSUE TITLE
GodotExtension:memdelete StreamPeerTLS and StreamPeerTCP and HTTPClient will cause corruption

### ISSUE THREAD

**Issue by chenjie199234** [godotengine/godot#98575]
### Tested versions

4.3 stable

### System information

windows 11 Godot 4.3.stable

### Issue description

program corruption,debug stopped Unexpected

### Steps to reproduce

here is the c++ code in GodotExtension
```
auto tcppeer = memnew(StreamPeerTCP);
auto tlspeer = memnew(StreamPeerTLS);
tcppeer->connect_to_host();
tlspeer->connect_to_stream(tcppeer,"xxhost name");
tlspeer->disconnect_from_stream();
tcppeer->disconnect_to_host();//corruption happened here
```
```
auto tcppeer = memnew(StreamPeerTCP);
auto tlspeer = memnew(StreamPeerTLS);
tcppeer->connect_to_host();
tlspeer->connect_to_stream(tcppeer,"xxhost name");
memdelete(tlspeer);
memdelete(tcppeer);//corruption happened here
```
```
auto tcppeer = memnew(StreamPeerTCP);
auto httpclient = memnew(HTTPClient);
tcppeer->connect_to_host();
httpclient->set_connection(tcppeer);
memdelete(tcppeer);
memdelete(httpclient);//corruption happened here
```

### Minimal reproduction project (MRP)

code above

**Comment by AThousandShips** [comment]
You shouldn't use `memdelete` for these, they are `RefCounted`, instead use `Ref<StreamPeerTCP> tcppeer = memnew(tcppeer);` and do not delete it, you should just use scope for it

**Comment by AThousandShips** [comment]
No because it's a reference counted type, it's protected by scope

**Comment by chenjie199234** [comment]
@AThousandShips thanks.i think it works like c++'s new and delete.
but the disconnect is still wrong.
i can't disconnect on tcp and tls peer together

**Comment by AThousandShips** [comment]
Please fix your code to use the correct types and upload a minimal project to test this

**Comment by chenjie199234** [comment]
@AThousandShips tested by myself
use memnew with Ref,works fine.
sorry,i think the memnew is like the c++'s new

**Comment by AThousandShips** [comment]
It is like `new` but this type is reference counted, like `std::shared_ptr`
