### ISSUE TITLE
[3.0] Godot wont run, Error: Could not obtain an OpenGL 3.3 context

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#9859]
**Operating system or device - Godot version:**
Linux Ubuntu 16.04 64 bits Godot 3.0 master commit edacc986d6bd14602e32e0fba95a6bb1738b423b

**Issue description:**
godot master was working yesterday, 
after updating Godot with a git pull, compile and try to open godot, I get the following errors:

ERROR: initialize: Could not obtain an OpenGL 3.3 context!
   At: platform/x11/context_gl_x11.cpp:149.
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/project_settings.cpp:841.
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/project_settings.cpp:841.
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:163.
Segment violation

**Steps to reproduce:**
git pull origin master
scons platform=x11 bits=64 -j 4
bin/./godot.x11.tools.64

**UPDATE:**
Could this be realted to me removing some unused i386 versions of the libraries?, like:
libxrender1:i386
libxrandr2:i386
libfreetype6:i386

**Comment by akien-mga** [comment]
That's weird. Does it work again if you revert f5277e347df4228fc875acaa3acb9581a30ab43e ?

**Comment by rubenjavier** [comment]
Tried reinstalling the i386 versions, and recompiling with scons, but getting the same errors,
Im gonna try reverting to commit f5277e347df4228fc875acaa3acb9581a30ab43e as @akien-mga says

**Comment by rubenjavier** [comment]
@akien-mga same errors after compiling in f5277e347df4228fc875acaa3acb9581a30ab43e
Im doing a compile from zero starting with a clean
git clone https://github.com/godotengine/godot

**Comment by akien-mga** [comment]
I meant reverting that commit, not reverting to it. Alternatively, checkout the previous one: d2d48e2a7a7ed04331597bcfd7b6c719da2b67c3

**Comment by rubenjavier** [comment]
Tried a clean check out and a checkout to d2d48e2a7a7ed04331597bcfd7b6c719da2b67c3
in both cases got the errors when runing godot:

ERROR: initialize: Could not obtain an OpenGL 3.3 context!
   At: platform/x11/context_gl_x11.cpp:149.
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/project_settings.cpp:841.
ERROR: set_custom_property_info: Condition ' !props.has(p_prop) ' is true.
   At: core/project_settings.cpp:841.
ERROR: initialize: Error initializing GLAD
   At: drivers/gles3/rasterizer_gles3.cpp:163.

**Comment by akien-mga** [comment]
Thanks. Do you remember when you last compiled it and got it working? Also, did something change on your system? (graphic drivers update for example?)

**Comment by rubenjavier** [comment]
Thank @akien-mga 
My last compilation was yesterday morning, 24Hrs ago aprox. not sure about the exact commit, today I did apt-get update, apt-get upgrade (but also did it yesterday). Yesterday godot was working but the "ice" PBR material on the new demo was not working, like everyone else
wich commit from the last 48 to 24hrs did you recomment to do some testing?

**Comment by rubenjavier** [comment]
@akien-mga 
I purged and reinstalled the graphics drivers, and no more GLES errors, godot master is working
Im so, sorry for the trouble, the rest of the applications and desktop was working O.K.
please close this report, and thank you for your help

**Comment by akien-mga** [comment]
Good news :)
