### ISSUE TITLE
The game window is on top by default

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#98599]
### Tested versions

v4.4.dev.mono.gh-97745 [16528f0fa]

### System information

Godot v4.4.dev.mono (16528f0fa) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 00:18:38 +0000 on Wayland - Wayland display driver, Single-window, 1 monitor - OpenGL 3 (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CFL GT2) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 threads)

### Issue description

https://github.com/user-attachments/assets/5045ff66-c729-4aad-8c5b-6d6af8eaf4e5

The project window run from the editor is pinned to the top, and the exported project has no tests.

### Steps to reproduce

Running project from editor

### Minimal reproduction project (MRP)

N/A

**Comment by timothyqiu** [comment]
I can't reproduce this issue.

Judging from the screen record, it seems that you are using my MRP for https://github.com/godotengine/godot/pull/97745#issuecomment-2440334619. It does have "Alway on Top" enabled for editor.

**Comment by scgm0** [comment]
> I can't reproduce this issue.
> 
> Judging from the screen record, it seems that you are using my MRP for [#97745 (comment)](https://github.com/godotengine/godot/pull/97745#issuecomment-2440334619). It does have "Alway on Top" enabled for editor.

Wow, it seems that I misunderstood that setting. I thought it took effect on the editor, but it actually takes effect on projects run from the editor.
