### ISSUE TITLE
Include filters are ignored during export

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#9860]
**Operating system or device - Godot version:**
macOS Sierra 10.12.5, Godot f55211ae0dc202cc015c247495af8e05af81b24b

**Issue description:**
Export dialog provides include filter field, but nothing is done with it in the code. So in the end only resources known by Godot are exported. This makes it impossible to export projects that use NativeScript, because one has to export .dll/.so/.dylib files with them which are not resources.

**Steps to reproduce:**
1. Add a file with non-resource extension (.json, .txt) to your project.
2. Specify the corresponding include filter in the export dialog (`*.json, *.txt`)
3. Export the project and observe non-resource files matching the filter are not exported.

**Comment by reduz** [comment]
fix is good, but @karroffel i guess still has to implement properly exporting in GDNative
