### ISSUE TITLE
Image class does not work (feels like fever dream)

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#98600]
### Tested versions

3.6 works
4.3 does not works

### System information

linux

### Issue description

By runing the self-contained code in the steps to reproduce, one get on: 

Godot 3:
--- Debugging process started ---
Godot Engine v3.6.rc1.official.cfc4a0eff - https://godotengine.org
OpenGL ES 2.0 Renderer: Mesa Intel(R) UHD Graphics 600 (GLK 2)
 
[Image:1277]	100	100	RGB8
--- Debugging process stopped ---

But;

Godot 4:
Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 24.2.4 (git-6be16b08cd) - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics 600 (GLK 2)

<Image#-9223372012276153081>	0	0	Lum8
--- Debugging process stopped ---

What i am doing really wrong? trying to acess image directly asks for it to be instanced via .new(), so it was not something on this liking.

LIke said, this feels odd, i am certaing to have worked with images in godot, maybe not in 4? is this a trivial mistake or a real bug?

### Steps to reproduce

run the code on a Node.

extends Node
func _ready() -> void:
	var ima = Image.new()			
	ima.create(100,100,true,Image.FORMAT_RGB8)
	printt(ima,ima.get_width(),ima.get_height(),ima.data.format)

### Minimal reproduction project (MRP)

N/A

**Comment by timothyqiu** [comment]
> extends Node
> func _ready() -> void:
> var ima = Image.new()
> ima.create(100,100,true,Image.FORMAT_RGB8)
> printt(ima,ima.get_width(),ima.get_height(),ima.data.format)

Note that `create()` is a static method that __returns__ the created image in 4.x.

**Comment by clayjohn** [comment]
Yes the code should be
```
var ima = Image.create(100,100,true,Image.FORMAT_RGB8)
```

**Comment by PeterMarques** [comment]
OH!

in 3.x it is a void func:
● void create(width: int, height: int, use_mipmaps: bool, format: Format)

but in 4.x it returns a image:
● Image create(width: int, height: int, use_mipmaps: bool, format: Format) static

Should pay more atentention to debugging, indeed.. Thanks.
