### ISSUE TITLE
Regression in Image3D uploads in RenderingDevice

### ISSUE THREAD

**Issue by basicer** [godotengine/godot#98601]
### Tested versions

- Reproducible in master after commit e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231
- Not reproducible in 4.3, 4.4-dev3 

### System information

Tested on MacOS, Windows 11

### Issue description

After commit e2c6daf7eff6e0b7e2e8d967e95a9ad56e948231, shaders reading from Image3ds seem to read the values at the wrong coordinates. 

### Steps to reproduce

- Load the attached project.  Under Vulkan after the problem commit, the box will appear jumbled.  On opengl, metal, and on Vulkan before the problem commit, you'll see a box with a barcode on the side and yellow stripes. 

### Minimal reproduction project (MRP)

[repro.zip](https://github.com/user-attachments/files/17537143/repro.zip)

![image](https://github.com/user-attachments/assets/b286b217-3fca-44e1-bd32-733beb518304)
![image](https://github.com/user-attachments/assets/8a31015c-a089-4f17-aacf-5f425dbff799)

**Comment by basicer** [comment]
CC: @DarioSamo

**Comment by clayjohn** [comment]
I doubt this is a shader issue. This most be a problem with how the texture is uploaded to VRAM.

**Comment by basicer** [comment]
> I doubt this is a shader issue. This most be a problem with how the texture is uploaded to VRAM.

Yeah, my wild guess is that it assumes that there are mipmaps when there aren't.

**Comment by DarioSamo** [comment]
Try out #98612 and let me know if it fixes the issue for you.

For additional context, it wasn't that Texture3Ds were broken entirely, but this particular case exhibited an issue with the alignment logic I built to handle them when the dimensions are not exactly what was expected.

**Comment by basicer** [comment]
Seems to have fixed it!  Thanks!
