### ISSUE TITLE
Error while loading some of the scenes

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9861]
**Operating system or device - Godot version:**
Ubuntu Linux, f55211ae0dc202cc015c247495af8e05af81b24b

**Issue description:**
It's impossible to open some of the scenes in newest build:
![error loading scene](https://user-images.githubusercontent.com/6129594/28609606-b55851a6-71e5-11e7-8f0c-a306e2bf0c17.png)

**Steps to reproduce:**
1. Download reproduction project
2. Try to open Enemy.tscn

**Link to minimal example project:**
[FSMDemo3.zip](https://github.com/godotengine/godot/files/1175777/FSMDemo3.zip)

**Comment by kubecz3k** [comment]
72436956ddcdfdcb9edea5c447363391c23552c4 is the first bad commit

**Comment by Noshyaar** [comment]
Enemy.tscn contains `PoolFloatArray` which should be `PoolRealArray`

IMO it's not an issue because `Pool*Array` is introduced in 3.0.

**Comment by akien-mga** [comment]
Yes, that should be one of the last scene-breaking changes for 3.0 :) The `PoolFloatArray` was wrong, it's `PoolRealArray` everywhere else in the source, so it was changed accordingly.

Run `s/PoolFloatArray/PoolRealArray/g` on your scene files and it should work fine.

**Comment by kubecz3k** [comment]
oh I see, thank you guys :+1:
