### ISSUE TITLE
Script editor stops accepting any input after I type ^ (circumflex accent)

### ISSUE THREAD

**Issue by gamourao** [godotengine/godot#98630]
### Tested versions

- Reproducible on v4.3.stable.official [77dcf97d8] and v4.0.2.stable.official [7a0977ce2]
-Not reproducible on v3.5.3.stable.official [6c814135b]

### System information

Ubuntu 24.04.1 LTS

### Issue description

After typing the accent anywhere within a code script (including comments or inside strings), the engine won't accept any more text inputs unless I close and reopen the project (in which case the script will work as expected even while maintaining the accent). The engine itself keeps working (I can change screens, open scenes etc), but it's impossible to write any code.
![Captura de tela de 2024-10-28 02-00-16](https://github.com/user-attachments/assets/2ffd410a-0d37-460c-832b-8ee4b6bf2100)

### Steps to reproduce

- Create a new project
- Create a new script
- Type "^" anywhere in the script

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/17551499/MRP.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this issue has been reported already, and we prefer to keep things tracked in one place, so closing this in favour of:
* https://github.com/godotengine/godot/issues/85664

If this is not the same issue, or you have some questions, please write here. If something is missing in the other report please comment there with any new information
