### ISSUE TITLE
Archive for Godot 3.6.0 has not been uploaded to Maven

### ISSUE THREAD

**Issue by cengiz-pz** [godotengine/godot#98632]
### Tested versions

Godot 3.6.0

### System information

Android 13 - Godot v3.6.stable

### Issue description

Gradle build fails with "Could not find org.godotengine:godot:3.6.0.stable." error.

### Steps to reproduce

Search Maven repository for Godot 3.6.0 archive.  https://search.maven.org/artifact/org.godotengine/godot

### Minimal reproduction project (MRP)

https://search.maven.org/artifact/org.godotengine/godot

**Comment by m4gr3d** [comment]
@lawnjelly The [3.x build scripts](https://github.com/godotengine/godot-build-scripts/tree/3.x/build-android) look correct; did we run them for the 3.6 stable release?

**Comment by m4gr3d** [comment]
I'll manually generate the missing build for now and push it to the maven repo.

**Comment by m4gr3d** [comment]
I resolved the issue by manually building and uploading the 3.6.0 archive to the Godot maven repo

https://repo1.maven.org/maven2/org/godotengine/godot/3.6.0.stable/
