### ISSUE TITLE
Quick Open Scene/Script dialog is very slow on bigger projects.

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9864]
**Operating system or device - Godot version:**
This issue is present since 2.0, still valid in 3.0. 

**Issue description:**
If a project is bigger (usually something like 100 scripts/scenes is enough to notice this, above 200 it's a problem), the Quick Open dialog is very slow, in my current project searching for some scenes/scripts might take I think approximately a minute. 
_**Here is a video:**_ https://youtu.be/buhCvzhT4-A
Project is however little artificial (600 scenes with enemy in name), but you will notice interesting property: if in that environment we are searching for 'enemy' it's super fast. If for something that's a lot less popular it's very slow. In my own project search speed for some scenes is bearable, but others take dozens of seconds (to the point that it looks very similar how 'some' search is performed on this video, at the same time project have a lot less files, but a lot greater variety of names).

I don't have idea that's the reason of that but I'm suspecting it's the way how fuzzy search is working. As far as I noticed it's doing fuzzy search on full file path not only on a name, this also can be  confusing on a bigger projects since quite often after typing something the results are not so helpful as they could be: 
![coin](https://user-images.githubusercontent.com/6129594/28615144-5cf86894-71f8-11e7-9556-ec66876e1d6a.gif)

I don't know how to solve this issue, but maybe for the begging we could start with an option to do fuzzy search only on filenames? 

**Steps to reproduce:**
1. Download reproduction project.
2. Try to search for 'some' scene or script

**Link to minimal example project:**
[SlowQuickOpen.zip](https://github.com/godotengine/godot/files/1176180/SlowQuickOpen.zip)

**Comment by akien-mga** [comment]
cc @vnen

**Comment by reduz** [comment]
The search should probably be optimized and, if it cant be made faster,
moved to a thread..

**Comment by vnen** [comment]
Never thought it would be that slow 😞

**Comment by kubecz3k** [comment]
After some investigation it seems I have localized concrete lines that makes it so slow, after commenting lines that as far as I understand are responsible for proper positioning of items on the list in https://github.com/godotengine/godot/blob/8f30c52a3751586edab6d7482425075aef8de6e3/editor/quick_open.cpp#L176 it works very fast again. 
![fast_filtering](https://user-images.githubusercontent.com/6129594/29979718-f07cba78-8f46-11e7-852f-23d59e0f0f66.png)
Not sure how to fix it properly however, I think `List.instert()` might be directly responsible for slowdown.

**Comment by vnen** [comment]
It might be faster to just add all the files and sort later. I made it already insert in the correct place, but this `while` loop there might be too slow on larger lists.

**Comment by kubecz3k** [comment]
Yay! @vnen thanks, it was a good hint! In the end it turned out, that computing score was performed as many times as many subfolders there was in the project, and also comparison was computed every time between each item on the list. 
I managed to improve search time significantly, here is gif from the search that was on the video, the one that previously took nearly 2 minutes:
![quick_search](https://user-images.githubusercontent.com/6129594/29996047-828267fa-8ff7-11e7-8961-d113c0f99df4.gif)
Will push pr as soon as I clean the code
