### ISSUE TITLE
"No animation in cache" errors and skipping animation when playing capture tracks in `AnimationPlayer`

### ISSUE THREAD

**Issue by ydeltastar** [godotengine/godot#98647]
### Tested versions

4.4.dev

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

After https://github.com/godotengine/godot/pull/92554, I'm getting errors from `AnimationMixer`. They spam when it's an animation with capture tracks and only when `$AnimationPlayer.play("animation")` is called then stop.

> E 0:00:04:0571   AnimationMixer::_blend_calc_total_weight: No animation in cache.
>   <C++ Error>    Condition "!animation_track_num_to_track_cashe.has(a)" is true. Continuing.
>   <C++ Source>   godot\scene/animation/animation_mixer.cpp:1109 @ AnimationMixer::_blend_calc_total_weight()
> 
> E 0:00:04:0571   AnimationMixer::_blend_process: No animation in cache.
>   <C++ Error>    Condition "!animation_track_num_to_track_cashe.has(a)" is true. Continuing.
>   <C++ Source>   godot\scene/animation/animation_mixer.cpp:1159 @ AnimationMixer::_blend_process()

### Steps to reproduce

The MRP plays a "deactivate" animation which has capture tracks when pressing Enter.
```gdscript
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept"):
		$AnimationPlayer.play("deactivate")
```
Previously, it would animate going to the deactivated pose as expected without errors.
Now it skips the animation and instantly changes to the last frame of the "deactivate" while printing errors.
> [!NOTE]
> The errors don't occur if the animation is played from `AnimationTree`'s state machine. Enable `AnimationTree`'s `active` property, remove the `$AnimationPlayer.play("deactivate")` and run the project to test.

### Minimal reproduction project (MRP)

[animation-error.zip](https://github.com/user-attachments/files/17588461/animation-error.zip)

**Comment by Nazarwadim** [comment]
Does the animation work the same as before, but just the error message pops up?

**Comment by ydeltastar** [comment]
It doesn't work like before.
Considering the project starts with the turret in this pose (equal last frame of "activate"):

![image](https://github.com/user-attachments/assets/90fc5b44-6d22-423e-b836-44e661e45107)

The final frame of "deactivate" looks like this:

![image](https://github.com/user-attachments/assets/b2a9e38c-0823-40cf-9992-69f48ac9f089)

And I play the animation like this:
```gdscript
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept"):
		$AnimationPlayer.play("deactivate")
```
### Before
Playing it will animate the turret going to the final pose of "deactivate" as expected with no errors.

### After
Playing it will skip the animation and the turret will instantly change to the final pose and errors are printed.
If I queue both animations, it does animate as before but errors are printed.
```gdscript
$AnimationPlayer.queue("activate")
$AnimationPlayer.queue("deactivate")
```
