### ISSUE TITLE
Will I get banned for not using inclusive language in Issues, PRs or community support ?

### ISSUE THREAD

**Issue by SaladinAyyub** [godotengine/godot#98648]
### Tested versions

All platforms

### System information

All Platforms

### Issue description

So as inclusive includes everyone except religious people speaking especially for my Muslim and Christian brothers, will we get banned ?

How does Godot refers the term "inclusivity" ? Or should I say how it is identified as ? Sorry but I am bad at speaking "inclusive" language. Just need some clarification as I would need to ask questions when I have doubt.. or when implementing a feature where I need some help. Is it important for me to speak the language that was introduced in recent years ? If yes then I would prefer to abstain as I am not willing to learn this language which has million pronouns. Almost all languages that I have learned usually have 1-5 pronouns, or at most 10 like some languages have different pronouns for singular/ plural stuff and for respect etc.. but I think it will get complicated if singular started identifying as a plural.. Its hard for me to comprehend with my sane mind how that works. So I won't be learning the language that is required for PRs, issues or community support. I would rather use a fork like Redot as I can speak my language and get the support I need. Also an additional question I have is that, do I need to dye my hair blue and become overweight ? Just asking for someone who reads this because I can't do both its haram.

Just wanted to confirm.
Thanks !

### Steps to reproduce

- Not knowing the inclusive language 
- getting banned
- No community support

### Minimal reproduction project (MRP)

All projects.

**Comment by clayjohn** [comment]
Hi, this space is for bug reports only. It is not a platform to ask any questions you have about the community. This question is more appropriate for the contact email address contact@godotengine.org

You may also be interested in reading our Code of Conduct which explicitly lays out the expectations we have for people participating in official Godot community spaces https://godotengine.org/code-of-conduct/

To answer your question in short, people are banned from community platforms if they have clearly breached the code of conduct. In most cases, bans are temporary unless the user repeatedly breaches the code of conduct. A ban from a community space does not stop you from using Godot, accessing the latest versions, or even accessing the source code and modifying it yourself. It just stops you from interacting in the community space that you were banned from. 

If you have further questions, please follow up by contacting the email address above.
