### ISSUE TITLE
Corrupted mesh data after import of a specific .blend file

### ISSUE THREAD

**Issue by pgrit** [godotengine/godot#98650]
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8] 

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - Blender 4.1

### Issue description

Importing one specific .blend results in what seems to be a broken index buffer. Geometry displays fine in the preview, but not when loaded into a scene. Other .blend files (so far) import fine.
![Screenshot](https://github.com/user-attachments/assets/c358756d-f867-4a94-b343-2b4bb05751e4)

Interestingly, when the camera is within the bounding box of the mesh, it renders fine. The below screenshot is taken in the same scene with the camera moved slightly.
![Screenshot3](https://github.com/user-attachments/assets/b9be6fa2-7b62-4dac-8ee6-6b8f39e918cc)

Doing any of the following "fixes" the issue:
1. Manually exporting to .glb with default settings in Blender, importing that .glb in godot
2. Using smooth normals instead of flat shading in Blender
3. Disabling normals in the import settings for the .blend
4. Converting all quads to triangles in Blender
5. Deleting the rig in Blender

### Steps to reproduce

MRP contains the `Hand.blend` file that fails to import and an inherited scene (`hand.tscn`)

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/17562742/MRP.zip)

**Comment by RedMser** [comment]
Try disabling LODs on the model, it sounds a lot like they're responsible.

**Comment by pgrit** [comment]
> Try disabling LODs on the model, it sounds a lot like they're responsible.

Yep, disabling LOD generation fixes the issue.
