### ISSUE TITLE
"Reparent to New Node" changes the position of the child in the hierarchy

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#98651]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

MacOS 13.6.7

### Issue description

When wrapping a child node with a new node using the "Reparent to New Node" the child node moves down to the bottom of the hierarchy of children. The expected outcome is for the child node to get wrapped with the new node, and the new node to take the child's old position in the hierarchy of children.

### Steps to reproduce

Make a hierarchy of nodes in the SceneTree. Right-click a node in the middle and chose to reparent it to a new node. The child, now wrapped in a new node, and the new node has moved to the bottom of the hierarchy.

### Minimal reproduction project (MRP)

-

**Comment by RedMser** [comment]
https://github.com/godotengine/godot/pull/79209

Fixed in 4.3.1 and 4.4
