### ISSUE TITLE
[Suggestion] Drag support for TabContainer

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#9865]
**Operating system or device - Godot version:**
2.1.3 or master +

Was thinking this could be a good quality of life improvement for the TabContainer. Also would be a nice UX feature in the editor.

Example of dragging a tab over to the left:
![](https://i.gyazo.com/3b6109f4bdfacb2adb722a91e70956b9.gif)

**Comment by Noshyaar** [comment]
Master branch already has this feature.

**Comment by groud** [comment]
Implemented by #9510 on 3.0. Not sure if it worth doing that on to 2.*

**Comment by Dillybob92** [comment]
WOW, freaking awesome! LOL
