### ISSUE TITLE
call_deferred doesn't seem to work on Resource

### ISSUE THREAD

**Issue by MrRevington** [godotengine/godot#98658]
### Tested versions

v4.4.dev.gh [08f9cba0f]

### System information

Godot v4.4.dev (08f9cba0f) - Windows 10.0.22631 - Multi-window, 2 monitors - OpenGL 3 (Compatibility) - AMD Radeon RX 7800 XT (Advanced Micro Devices, Inc.; 32.0.12019.1028) - AMD Ryzen 9 5900X 12-Core Processor (12 threads)

### Issue description

Anything that is to be called with call_deferred on a Resource isn't called.
Interestingly if one changes the Resource to extend from Object the call works for resource_b, which is confusing because a Resource is an Object. With resource_a (ResourceLoader.load) call_deferred never works.

### Steps to reproduce

In MRP it should print TestResource::_post_init but it doesn't.

### Minimal reproduction project (MRP)

[call_deferred_init.zip](https://github.com/user-attachments/files/17564765/call_deferred_init.zip)

**Comment by fire** [comment]
I don't see how call_deferred would work on resources, resources don't _process or _physics_process.

**Comment by MrRevington** [comment]
> I don't see how call_deferred would work on resources, resources don't _process or _physics_process.
> 
> Only class extending `Node` class `_process` or `_physics_process`.

I wondered that too but as I wrote it works for Object, even not being inside the Scene Tree so _process / _physics_process wouldn't get called anyway.

**Comment by fire** [comment]
Can you let me know what type the object is which you're calling call_deferred from?

**Comment by MrRevington** [comment]
> Can you let me know what type the object is which you're calling call_deferred from?
> 
> Object is a base class so it does nothing.

like in resource.gd in the MRP.
updated to this with self.reference() the  call_deferred works.
```GDSCRIPT
extends Resource
class_name TestResource

@export var name : String = "DefaultName"

func _init() -> void:
	print("TestResource::_init")
	self.reference()
	_post_init.call_deferred()
	print("TestResource::_init end")
	

func _post_init() -> void:
	print("TestResource::_post_init")

extends Resource
class_name TestResource

@export var name : String = "DefaultName"

func _init() -> void:
	print("TestResource::_init")
	self.reference()
	_post_init.call_deferred()
	print("TestResource::_init end")
	

func _post_init() -> void:
	print("TestResource::_post_init")

```

**Comment by ydeltastar** [comment]
The resource isn't being used anywhere so it is never loaded. Trying loading it or using it in an @export.
```gdscript
const NEW_RESOURCE = preload("res://new_resource.tres")
```

**Comment by fire** [comment]
My thought was the call deferred uses the message queue system. I don't know that much about it but your reasoning makes sense it should work.

**Comment by KoBeWi** [comment]
Resources are reference counted. If nothing is referencing them, they are freed automatically. Message Queue does not keep reference to RefCounted objects, so if they get dereferenced, the deferred call will be silently dropped.

**Comment by MrRevington** [comment]
> Resources are reference counted. If nothing is referencing them, they are freed automatically. Message Queue does not keep reference to RefCounted objects, so if they get dereferenced, the deferred call will be silently dropped.

This! Just tested it with updating the MRP and it works fine with your corrections.
Thank you both for your help! :)
