### ISSUE TITLE
[4.4dev1] Godot editor crashes when using global signal or global function. 

### ISSUE THREAD

**Issue by DuncanTls** [godotengine/godot#98674]
### Tested versions

Reproductible in : v4.4.dev1.official [28a72fa43]
Not Reproductible in : v4.3.stable

### System information

Windows 10 - Godot v4.4.dev1.official [28a72fa43] - Any mode (compatibility/forward+/...)

### Issue description

Godot editor (i.e the code editor) crashes when using global signal or global function with a parameter.
The global signal signal or function must have been declared before in a script, and this script must be global in the project parameters.  

It always happens when : 
- The parameter is a primitive type (int, float) or a literal string
The crash occurs immediately after the pamareter is typed. 

If does not happen : 
- When the parameter is an Object
- When the parameter is passed through a variable 
Thus, using a intermediate variable is a workaround. 
Maybe something to do with the autocompletion ? 

### Steps to reproduce

1) Create a new project
2) Create a new script 'global_signals.gd', and make it global  
3) Create a function or signal with a parameter

```
extends Node

signal test_signal(number : int)
```

4) Create a scene 'main.tscn' with a 'Main' node. Associate a new script to this node. 
5) Create a function in this script, using global signal created before : 

```
extends Node3D

func test_func():
    GlobalSignals.test_signal.emit(1)
```

When typing '1', the editor crashes. 
However, the following code will not crash:

```
extends Node3D

func test_func():
    var number : int = 1
    GlobalSignals.test_signal.emit(number)
```

### Minimal reproduction project (MRP)

[testgodot.zip](https://github.com/user-attachments/files/17575965/testgodot.zip)

**Comment by ghmart** [comment]
Seems this bug was fixed since 4.4 dev2.

**Comment by girdenis-p** [comment]
Yeah this bug seems fixed. I was able to replicate it on 4.4.dev1 but not on 4.4.dev3 or on the latest source build 8004c7524

**Comment by HolonProduction** [comment]
Closing as fixed by https://github.com/godotengine/godot/pull/96243
