### ISSUE TITLE
Spatial shaders with Screen Texture have no information on ANY reflections (both SSR and SDFGI)

### ISSUE THREAD

**Issue by ArseniyMirniy** [godotengine/godot#98677]
### Tested versions

4.3 Stable

### System information

Windows 10 x64

### Issue description

A typical Canvas Item has only 8-bit frame without proper information on its original luminosity.

Passing Screen texture to spatial shader allows getting 32-bit information that gives full control over the color and luminosity, but unfortunately, it also completely removes any reflections, like you see on the screenshot and [like already discussed here](https://github.com/godotengine/godot/issues/79074) — it kinda makes the material transparent and should've excluded itself from reflections, but it excludes ANYTHING from reflections, anything behind it as well.

![image](https://github.com/user-attachments/assets/afd99598-125c-4756-9cbb-5a6c50029e20)

There should be a way to overcome this, right?
I need to get both: reflections and the original 32-bit frame without making it overcomplicated.

### Steps to reproduce

Use Spatial shader for screen effects on any scene that has noticeable SSR or SDFGI reflections.

### Minimal reproduction project (MRP)

N/A

**Comment by tetrapod00** [comment]
This is a known limitation, see https://github.com/godotengine/godot/issues/79074#issuecomment-1623781581.

It's still not fully documented, though.

**Comment by ArseniyMirniy** [comment]
### Workaround:

In Godot you can use Canvas shaders with HDR by enabling 2D HDR in Rendering > Viewport settings of Godot Project Settings. It will affect the default Viewport, but you will also need to enable it in any other viewports. You need 2D HDR for 3D games screen canvas item shaders too.

![image](https://github.com/user-attachments/assets/1d941b2d-3c25-4395-8b88-5e4da39e4e2c)

#### The image will be slightly different from your Spatial shader
Which means, a lot of fixes and fine-tuning will be needed
