### ISSUE TITLE
[4.4dev1] "Preload" autocompletion doesn't work

### ISSUE THREAD

**Issue by DuncanTls** [godotengine/godot#98676]
### Tested versions

- Reproductible in : v4.4.dev1.official [28a72fa43]
- Not reproductible in : v4.3

### System information

Windows 10 - Godot v4.4.dev1.official [28a72fa43]

### Issue description

Some built-in Gdscript functions offer autocompletion based on file paths within the project's file system. 
However this functionnality seems to be broken for 'preload' function. 

It keeps working for 'load', 'change_scene_to_file' and some other similar functions, though 

### Steps to reproduce

Just use 'preload' function in GdScript editor. 

### Minimal reproduction project (MRP)

MRP not necessary.

**Comment by ghmart** [comment]
Tested on Linux bullseye. You right, autocomplete for preload doesn't work. But 4.4 dev1 is outdated. Why use it at all when 4.4 dev3 is here for a month already? Autocomplete works with it just fine.

**Comment by HolonProduction** [comment]
Closing as fixed by #96243
