### ISSUE TITLE
Duplicating export preset doesn't copy over GDScript Export Mode

### ISSUE THREAD

**Issue by AdriaandeJongh** [godotengine/godot#98722]
### Tested versions

4.3.stable

### System information

Godot v4.3.stable - macOS 15.0.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

When duplicating export presets, the GDScript Export Mode is reset to default (the default being 'Compressed binary tokens') instead of being copied over from the original into the duplicate.

I haven't thoroughly checked the other properties of the exports, but perhaps there are more properties that don't get copied over. I noticed that the export path is also empty in duplicates, but I can see the logic in that: every export preset exports to a different folder. I don't think that same reasoning makes sense for GDScript Export Mode though.

### Steps to reproduce

Make an export preset, set the GDScript Export Mode to anything other than the default, duplicate the preset, and notice that the GDScript Export Mode in the duplicate reseted to the default.

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Encryption settings are not duplicated as well.
