### ISSUE TITLE
Extremely low performance when a LightOccluder2D node with high vertex count is selected

### ISSUE THREAD

**Issue by demolen** [godotengine/godot#98730]
### Tested versions

reproducible on 4.4 dev

### System information

macOS 15.1 , godot 4.4 dev - forward+/mobile, m2 gpu

### Issue description

selecting a lightoccluder2d node with high vertex count causes godot to become unresponsive. the mere existence of these in the scene when the node is not selected is not a problem and the 2d light also behaves as it should. the problem seems to have to do with editor trying to render the occlusion geometry when the node gets selected.

### Steps to reproduce

In the attached project select the lightoccluder2d node

### Minimal reproduction project (MRP)

[lightoccluder2d-bug.zip](https://github.com/user-attachments/files/17602741/lightoccluder2d-bug.zip)

**Comment by demolen** [comment]
[godot-performance.trace.zip](https://github.com/user-attachments/files/17602878/godot-performance.trace.zip)

trace file for Xcode instruments profiler. the spikes are happening as I move the mouse on the other editor elements when the lightoccluder2d node is selected.

**Comment by demolen** [comment]
what I think is that godot is redrawing/rebuilding the lightoccluder2d geometry each time the editor window has to be updated. I don't know why is that necessary but maybe caching the geometry would be a solution. I haven't looked at the code and never did anything serious in godot internally so I leave it to you.

**Comment by demolen** [comment]
just figured out this is nothing new. there is this orphan issue reporting the same thing from 2021!:
#52703

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/52703.
