### ISSUE TITLE
Shaders: Editor freeze/crash when processing mat4 struct properties with certain names

### ISSUE THREAD

**Issue by Jordandionduval** [godotengine/godot#98740]
### Tested versions

- Reproductible in: 4.3.stable.official.77dcf97d8

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When creating a struct in a shader file, adding `mat4` properties with similarly named to existing builtins like `model_matrix` (where the only difference is letter case), the editor slows down drastically when processing the shader. Using differently named `mat4` properties will not cause this issue.

In the MRP project provided, the worse we get is a much longer processing time when shader is modified, but I've also gotten a crash in my personal project (I have yet to confirm why that is, but it might just be that we have more textures, assets, etc.)

This only happens with shaders used in a shader material in a loaded scene. Doing this inside a `gdshader`/`gdshaderinc` file not currently used is safe, but will cause the same issue if put to use.

**Crash Log:**
```
Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 4070

USER ERROR: Condition "p_image.is_null()" is true.
   at: texture_2d_initialize (servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:793)
USER ERROR: Condition "p_image.is_null()" is true.
   at: texture_2d_initialize (servers/rendering/renderer_rd/storage_rd/texture_storage.cpp:793)
ERROR: 2 RID allocations of type 'N10RendererRD14TextureStorage7TextureE' were leaked at exit.
```

I didn't get a log for when the editor freezes, so best I can do is this Output dump (only errors 1361-3779 appear, but 15164 errors were raised).
[Output_Dump.txt](https://github.com/user-attachments/files/17604585/Output_Dump.txt)

### Steps to reproduce

Requirements:
- Shader must be spatial
- Shader has to be in use in the scene, inside a shader material (on a MeshInstance3D)

Steps:
1. Open new Scene (in the MRP, this is `Scene_FREEZE.tscn`. You can also open `shader_CRASH.gdshader` and skip to step 5 if using the MRP.)
2. Make sure the MeshInstance3D geometry has a shader material applied using our shader.
3. (Optional) Add ifdef/endif clause around our issue, otherwise editor will slow down with each property added.
```GLSL
#ifdef TEST_ISSUE
    // insert struct here...
#endif
```
4. Inside the shader file, create a struct with the following properties:
```GLSL
struct _ISSUE {
	mat4 model_matrix;
	mat4 inv_view_matrix;
	mat4 view_matrix;
	mat4 projection_matrix;
	mat4 inv_projection_matrix;
};
```
5. If struct is in a ifdef/endif clause, add the required define (otherwise skip to next step).
```GLSL
#define TEST_ISSUE

#ifdef TEST_ISSUE
    struct _ISSUE {
	mat4 model_matrix;
	mat4 inv_view_matrix;
	mat4 view_matrix;
	mat4 projection_matrix;
	mat4 inv_projection_matrix;
    };
#endif
```
6. BUG! Editor will slow down significantly for around a minute. In a scene with other assets/shaders, this might cause a crash instantly.

### Minimal reproduction project (MRP)

[crash_matrixstruct.zip](https://github.com/user-attachments/files/17604470/crash_matrixstruct.zip)

**Comment by Chaosus** [comment]
Looks like it's somehow triggered on the name of "projection_matrix" and "inv_projection_matrix" - if you remove them from your code - everything will be fine.

**Comment by Chaosus** [comment]
I guess that's because the internal shader file contains `#define projection_matrix` and its conflict with a struct member name, the solution is to add a prefix to the struct member names..
