### ISSUE TITLE
Script editor "Find in files..." does not search Built-in scripts

### ISSUE THREAD

**Issue by sanlor** [godotengine/godot#98762]
### Tested versions

- Reproducible in v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

While in the script editor, the option "Find in files" only searches *.gd files. Built-in scripts are excluded from these searches.

### Steps to reproduce

open the MRP
Script > Find in Files...
search for "var my_variable"
only on match is found.

### Minimal reproduction project (MRP)

[godot_bug.zip](https://github.com/user-attachments/files/17607568/godot_bug.zip)

**Comment by arkology** [comment]
See https://github.com/godotengine/godot-proposals/issues/9436

**Comment by AThousandShips** [comment]
Thank you for reporting, see the related proposal and linked issues, closing this to keep things in one place
