### ISSUE TITLE
When trying to send an Array that is typed with a custom type a type error is emitted and no data is sent.

### ISSUE THREAD

**Issue by TizWarp** [godotengine/godot#98783]
### Tested versions

Reproducible in 4.3.stable

### System information

Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 20:11:06 +0000 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7700S (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

I have a multiplayer game it requires clients to send some extra info, like usernames etc. I have a custom class that holds this info. I have created a typed array that hold all connected players. This info needs to be sent to the client instances and so I have an rpc like so :

```
var players : Array[Player] = []

@rpc("authority")
func send_data(data : Array[Player]):
  players = data
```

I get the following error when executing this rpc
 ``` 
E 0:00:00:0359   _process_rpc: RPC - 'Node2D(game.gd)::data_rpc': Cannot convert argument 1 from Array to Array
  <C++ Source>   modules/multiplayer/scene_rpc_interface.cpp:290 @ _process_rpc()
```

when inspecting the node that hold the player array it is empty

### Steps to reproduce

Create new project.
Setup basic Multiplayer functionality 
Open a server and a client instance. 
```
func createServer():
  var peer = EnetMultiplayerPeer.new()
  peer.create_server(6643)
  multiplayer.multiplayer_peer = peer

func createClient():
  var peer = EnetMultiplayerPeer.new()
  peer.create_client("127.0.0.1", 6643)
  multiplayer.multiplayer_peer = peer
```
Create Custom class and create a Typed array that is of that type
```
class Player:
  var id : int;
  var username : String;

var players : Array[Player] = []
```

Create rpc function that attempts to sync the array:

```
@rpc()
func data_rpc(data : Array[Player]):
  players = data
```

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/17608723/mrp.zip)

**Comment by AThousandShips** [comment]
The provided MRP is not complete, you need to make a complete project with the scene involved, please update your MRP to contain everything needed to run this code

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
