### ISSUE TITLE
Solution in Division Operator. / Solución en Operador de División.

### ISSUE THREAD

**Issue by Kanopola** [godotengine/godot#98799]
### Tested versions

I assume it is reproducible in all versions because I have the 4.3 stable and I consider that it has been dragging on from the previous ones.

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Supongo que es reproducible en todas las versiones porque tengo la 4.3 stable y considero que se viene arrastrando desde las anteriores.

### System information

Windows 10, Godot Engine v4.3.stable.official.77dcf97d8 - OpenGL API 3.3.0 NVIDIA 392.67 - Compatibility - Using Device: NVIDIA - Quadro K2000M.

### Issue description

Thank you for the course, it is very good and the sacrifice you make is appreciated. And since we must help each other, I want to share with you and others this help on something that could be considered an error and that I discovered in the division operator part; and if it deals with the following:

If we put 2 integers to divide, when the result is a decimal or floating number, it will not show it.

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Gracias por el Curso, está muy bueno y se valora el sacrificio que hacen. Y como debemos ayudarnos, quiero compartir con ustedes y los demás esta ayuda sobre algo que podría considerarse un error y que descubrí en la parte del operador de división; y si trata de lo siguiente:

Si ponemos 2 números enteros a dividir, cuando el resultado sea un número decimal o flotante, no lo mostrará.

### Steps to reproduce

Consulting with ChatGPT about this, I found the following solutions:

1.- Using a Floating Literal in the variable value, so that the result is floating. For example: 7.0 / 2 or 7 / 2.0.

2.- Convert one of the values ​​into floating using float(), in case you don't want to change the value declared in the variable. Example: ...float(number_1) / number_2)... and vice versa.

Since I'm new to this and I'm just getting through that part of the Course, I don't know if there are other ways or if they teach you how to do it later, but I wanted to make this contribution and I hope it helps someone who has the same curiosity.

Thank you for your time.

Grace and Peace.

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Consultando con ChatGPT al respecto, encontré las siguientes soluciones:

1.- Usando un Literal Flotante en el valor de la variable, para que el resultado sea flotante. Por ejemplo: 7.0 / 2 ó 7 / 2.0.

2.- Convertir uno de los valores en flotantes usando float(), por si no se quieres cambiar el valor declarado en la variable. Ejemplo: ...float(numero_1) / numero_2)... y viceversa.

Como soy nuevo en estoy y a penas voy por esa parte del Curso, no sé si habrán otras formas o si más adelante enseñan cómo hacerlo, pero quise hacer este aporte y espero que le sirva a alguien que tenga la misma curiosidad.

Gracias por tu tiempo.

Gracia y Paz.

### Minimal reproduction project (MRP)

[operadores-aritmeticos.zip](https://github.com/user-attachments/files/17611409/operadores-aritmeticos.zip)

**Comment by AThousandShips** [comment]
Thank you for your report!

This is not a bug, you are performing integer division, not floating point, you need to use `1/2.0`

See:
* https://github.com/godotengine/godot-proposals/issues/5344
* https://github.com/godotengine/godot-proposals/issues/1888
* https://github.com/godotengine/godot/issues/49579
* https://github.com/godotengine/godot/issues/25856

Please see there, closing
