### ISSUE TITLE
Typed Array in Resource empty when loaded in exported project.

### ISSUE THREAD

**Issue by nonchip** [godotengine/godot#98798]
### Tested versions

Reproducable in: 4.4dev3, not reproducable in: 4.3stable

### System information

`Godot v4.4.dev3 - Void #1 SMP PREEMPT_DYNAMIC Sun Jul 28 07:18:17 UTC 2024 on Wayland - Wayland display driver, Single-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (nvidia; 555.58.02) - AMD Ryzen 5 5600X 6-Core Processor (12 threads)`

### Issue description

when trying to load a Resource with an `@export`ed `Array[String]`  in an exported project, the resulting array is empty.
setters do not run if they exist.

### Steps to reproduce

* declare a Resource type with a typed array
* create a `.tres` file of its type
* give the array some values
* they load correctly when run from the editor, but it's empty when exported (and attached setters wont run)

### Minimal reproduction project (MRP)

[broken_tres.zip](https://github.com/user-attachments/files/17611313/broken_tres.zip)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been reported and we prefer keeping things in one place, so closing in favour of:
* https://github.com/godotengine/godot/issues/98495

Please see there for more details
