### ISSUE TITLE
tutorial_vector_math: A much better explanation of the dot product.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#988]
Hi, the section says the dot product is hard to understand and makes no sense.
But I’ve found a really nice and intuitive way to think about it:

> The dot product simply is the indicator for how much two vectors have in common.
> The bigger, in relation to their magnitudes, the more two vectors have in common.
> Simple. :)

I think that it’s hard / makes no sense is a false meme,
and it’s just the explanation we learned it from that has always been bad,
which instilled fear, and *caused* us to have trouble understanding it *in the first place*.

So I hope you can add the above explanation,
and remove the lines about it being hard or making no sense. :)

**Comment by akien-mga** [comment]
Assigning to @reduz who wrote the tutorial. It's true that calling the dot product meaningless is a bit harsh, at least for everyone who had math in high school and learned a bit about vector calculus :)
Now I wouldn't oppose to call the curl and Laplacian operators hard to understand, but I wouldn't make the dot product _THE_ difficulty that would break everyone's dreams to make games :)

**Comment by akien-mga** [comment]
Moved to godot-docs repo.
