### ISSUE TITLE
Maybe a regression 2.1.2 -> 2.1.3 in Android export template for the LineEdit node when using predictive keyboard and select_all.

### ISSUE THREAD

**Issue by Procyon3** [godotengine/godot#9880]
**Operating system or device - Godot version:**
It works in Godot 2.1.2 (with 2.1.2 templates) exported to Android, but not in 2.1.3. The export is done on Linux 64 bit.

**Issue description:**
When the LineEdit node has some text and it's selected with select_all(), then the expected behavior is that that text is cleared on backspace or when typing. This works fine in 2.1.2 on Android with a predictive keyboard.

But in 2.1.3 what happens is that with a predictive keyboard only one character is removed with backspace (while the entire text is selected) or characters are appended to the current text with typing. Also when there are two words and they are both selected (with select_all()) and backspace is pressed, the first word is deleted and 1 character is removed from the second word.

**Comment by volzhs** [comment]
maybe it's regression from #7936
but I can't take a look for a few weeks.

**Comment by akien-mga** [comment]
Is this issue still valid in Godot 2.1.4? And if so, in the current 2.1 branch (2.1.5 RC2 builds on op.godotengine.org:81/downloads/2.1.5/rc2 )?

**Comment by akien-mga** [comment]
Also the exporter seems to pickup any strings that has the word ".remove" and converts to ".remove_and_collide" or something similar.
