### ISSUE TITLE
Deep Parallax causes artifacts when not using with TAA/FSR2

### ISSUE THREAD

**Issue by izarii-dev** [godotengine/godot#98810]
### Tested versions

- Reproducible in any version

### System information

Godot v4.4.dev unknown - Windows 10.0.26100 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated Radeon (TM) RX 480 Graphics - AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 threads)

### Issue description

This issue present when using Deep Parallax with detailed textures
using low roughness makes it look even worse, Roughness Limiter doesn't make this any less visible

TAA and FSR2 disabled
![image](https://github.com/user-attachments/assets/31043ade-b070-40a3-8a0c-4ef475ded8d6)

TAA
![image](https://github.com/user-attachments/assets/3e814684-33fb-4c5c-95c8-1414ce4bc519)

FSR2
![image](https://github.com/user-attachments/assets/49aa0c58-878e-414b-9461-d51d0b861dab)

### Steps to reproduce

1. Use Deep Parallax with any detailed PBR textures

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
This is specular aliasing made more prominent with deep parallax, which can't be fixed without temporal antialiasing (or supersampling, but it's very slow). See [3D antialiasing](https://docs.godotengine.org/en/latest/tutorials/3d/3d_antialiasing.html) in the documentation.
