### ISSUE TITLE
_shape_run: Parameter "fd" is null when changing font on rich text label

### ISSUE THREAD

**Issue by BrianBHuynh** [godotengine/godot#98819]
### Tested versions

- Reproduceable in godot 4.3 stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

There seems to be a strange error where when updating a font for rich text labels from a global variable there is a weird error which appears about fd being null, however when using the same signal and pulling from the same global variable for a button, the error is not present. This seems to be very strange behavior which I'm somewhat confused about and is likely unintentional 

### Steps to reproduce

Button signals to script to change the globalvar font to a new font, then signal for all text labels to update their fonts pulling from globalvar font.

error

but reproduction can be seen in the MRP bellow, just press button for error

### Minimal reproduction project (MRP)

[bugReproduction.zip](https://github.com/user-attachments/files/17620443/bugReproduction.zip)

**Comment by akien-mga** [comment]
Likely the same issue as #94339.

**Comment by BrianBHuynh** [comment]
From what I can tell they're not the same error since I'm not changing any themes (just theme font override) and then happen on the first button press

At the same time I never got the first error and the fd null error happens every time

So the behaviors are different it seems although likely caused by similar things

**Comment by BrianBHuynh** [comment]
Also if it helps this error can be solved for this script by adding an await for 1 second, although I cannot figure out why this would be a problem here and not for buttons

**Comment by bruvzg** [comment]
Can't reproduce it with current 4.4, so likely already fixed.

**Comment by BrianBHuynh** [comment]
Oh okay thankyou for checking! I'll close the issue for now then and try to test it as well when I can on a newer version
