### ISSUE TITLE
The value of an exported property is not updated if you press "Play" without losing focus

### ISSUE THREAD

**Issue by mhalttu** [godotengine/godot#98827]
### Tested versions

4.3.stable.official

### System information

OS X Sonoma

### Issue description

When you change the value of an exported property in the editor and run the project, the value of the property is not updated until you intentionally change the focus to another input field.

### Steps to reproduce

1. Define a scene such as a player
2. Add a property such as move speed, set a default value and export it
3. Select the property in the editor
4. Change the value of the property
5. Press Play

What should happen: The value of the property is updated (i.e. takes effect) and the game starts.
What happens instead: The game starts but the old value is used until you manually click another property and the focus is lost 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting! This has already been reported in:
* https://github.com/godotengine/godot/issues/74557

Closing as we prefer to have bugs tracked in one place, see there for more details
