### ISSUE TITLE
2D particles are glitchy in Platformer demo

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9884]
**Operating system or device - Godot version:**
Mageia 6 x86_64 with proprietary NVIDIA drivers (375.66), Godot 3.0.alpha.build1 (f55211ae)

**Issue description:**
2D particles (at least in the Platformer demo) are rendered black:
![vlvjwsg](https://user-images.githubusercontent.com/4701338/28634818-b66b03ec-7238-11e7-9b05-d5cb2e732c5a.png)

**Steps to reproduce:**
- Run the 2D platformer demo, shoot bullets, kill enemies

**Link to minimal example project:**
https://github.com/godotengine/godot-demo-projects/tree/master/2d/platformer

**Comment by MrMaidx** [comment]
I've seen this also on KaOS Linux. With Mesa 17 drivers.

**Comment by reduz** [comment]
ah, this was working before and broke at some point...

**Comment by eon-s** [comment]
I think the problem is in the particles settings but that demo is currently broken and can't open any scene.

**Comment by eon-s** [comment]
The Particles2D has a material with color ramp with empty gradient.

**Comment by ISylvox** [comment]
I guess this is more about unpolished 2D Platformer demo in Godot 3.0, instead of Particles2D node bug. I've done small tweaks to the 2D Platformer demo, and it was as good as I would expect.

**Comment by ISylvox** [comment]
I guess this is more about less polished 2D Platformer demo in Godot 3.0, instead of Particles2D node bug. I've done small tweaks to the 2D Platformer demo, and it was as good as I would expect.

**Comment by akien-mga** [comment]
> I guess this is more about less polished 2D Platformer demo in Godot 3.0, instead of Particles2D node bug. I've done small tweaks to the 2D Platformer demo, and it was as good as I would expect.

That's good news :) If you can make a PR to fix the demo, we can then close this issue.

**Comment by ISylvox** [comment]
> If you can make a PR to fix the demo, we can then close this issue.

Indeed, that was my plan. :-)

**Comment by akien-mga** [comment]
Bump :)

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/58.
