### ISSUE TITLE
Orthogonal view in a newly created project

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#98844]
### Tested versions

v4.4.dev.custom_build [b00e1cbf7]

### System information

Godot v4.4.dev (b00e1cbf7) - macOS 14.5.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

A newly created project is using orthogonal view instead of perspective:

![1](https://github.com/user-attachments/assets/936532f2-a374-45d2-8d15-cb6e1e6749a4)

When opening the same project for the second time (without making any changes) both Perspective and Orthogonal radio buttons are active (orthogonal is still the one used):

![2](https://github.com/user-attachments/assets/f7375914-42ae-495d-a579-e1dc85f8ef13)

### Steps to reproduce

Build from master and create a new godot project

### Minimal reproduction project (MRP)

N/A

**Comment by ryevdokimov** [comment]
I can replicate this issue on latest master as well.

**Comment by aaronfranke** [comment]
This regression is introduced by PR #97257.
