### ISSUE TITLE
AltGr button does not work correctly on QWERTZ keyboard

### ISSUE THREAD

**Issue by gitsomebit** [godotengine/godot#98854]
### Tested versions

- Reproducable in 4.3 stable and 4.2 stable

### System information

Windows 10 - Godot 4.3 - Compatibility - QWERTZ keyboard

### Issue description

I am working on a input remapping system for my game. 
As you know when AltGr is pressed together with another key, the key should have the modifiers of Ctrl and Alt. 
This is not the case for all keys as it works for some and for some it does not.

### Steps to reproduce

create a new scene with a control node and use the _input() function:
```gdscript
func _input(event: InputEvent) -> void:
	if event is InputEventKey and event.pressed and not event.is_echo():
		match event.physical_keycode:
			KEY_CTRL, KEY_SHIFT:
				pass
			_:
				print(event)
```
When holding down AltGr and pressing the toprow number keys one after another produces the following results (some have mods, some dont):

InputEventKey: keycode=4194328 (Alt), mods=Ctrl, physical=false, location=right, pressed=true, echo=false
InputEventKey: keycode=49 (1), mods=Ctrl+Alt, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=50 (2), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=51 (3), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=52 (4), mods=Ctrl+Alt, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=53 (5), mods=Ctrl+Alt, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=54 (6), mods=Ctrl+Alt, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=55 (7), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=56 (8), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=57 (9), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=48 (0), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=91 (BracketLeft), mods=none, physical=false, location=unspecified, pressed=true, echo=false
InputEventKey: keycode=93 (BracketRight), mods=Ctrl+Alt, physical=false, location=unspecified, pressed=true, echo=false

### Minimal reproduction project (MRP)

MRP_Godot-4.3: [AltGr_Bug.zip](https://github.com/user-attachments/files/17635072/AltGr_Bug.zip)

**Comment by gitsomebit** [comment]
QWERTZ keyboard layout:![image](https://github.com/user-attachments/assets/409bedf1-ec0a-4494-9be7-4c803a3daf54)

**Comment by bruvzg** [comment]
> As you know when AltGr is pressed together with another key, the key should have the modifiers of Ctrl and Alt.

`Ctrl`+`Alt` can be used as substitute for `AltGr` (on Windows), not sure if reverse should be always true.

The keys that do not have modifiers set seems to keys with associated third level character values (blue), so it's likely cause by processing characters:
<img width="712" alt="Screenshot 2024-11-05 at 19 57 54" src="https://github.com/user-attachments/assets/9e4175ce-ab36-48cb-a535-de75e55a9848">

**Comment by gitsomebit** [comment]
I think you are right. I find it a little strange that there are no mod keys, but then this seems to be the intended behaviour. 
Will close this issue then.

**Comment by bruvzg** [comment]
We actually deliberately unset modifiers for key events like this:
https://github.com/godotengine/godot/blob/87318a2fb7fffeb72adca934e31915be077c3d1f/platform/windows/display_server_windows.cpp#L5441-L5444

It was like added in https://github.com/godotengine/godot/pull/189, before proper IME support, and might unnecessary.
