### ISSUE TITLE
exported dictionary property can't be saved in .tscn file

### ISSUE THREAD

**Issue by jinyangcruise** [godotengine/godot#98857]
### Tested versions

- Reproducible in v4.4.dev3.official [f4af8201b]

### System information

Windows 11, Vulkan API 1.3.280 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060 Ti

### Issue description

If a property is an `@export` Dictionary, after modifying this property and save, it's value is not stored in .tscn file.

<img width="1099" alt="屏幕截图 2024-11-06 004808" src="https://github.com/user-attachments/assets/e223759a-164e-4336-bf53-0d468390cd13">
<img width="1077" alt="屏幕截图 2024-11-06 005000" src="https://github.com/user-attachments/assets/5963affe-6f77-4193-8086-ec229f5da2fc">

Only test Dictionary type and not sure whether other type like Array has such issue.

### Steps to reproduce

1. open MRP
2. open foo.tscn
3. modify the exported property
4. save scene
5. open foo.tscn file with other text editor to check if the value is stored.
6. ---------
7. open bar.tscn
8. modify the exported property of foo
9. save scene
10. open bar.tscn file with other text editor to check if the value is stored.

### Minimal reproduction project (MRP)

[test_export_dictionary.zip](https://github.com/user-attachments/files/17635941/test_export_dictionary.zip)

**Comment by matheusmdx** [comment]
Just to be sure, are you clicking in `Add key/value pair` before save? Because i tested rn and seems to work as expected in 4.4 dev 3

![image](https://github.com/user-attachments/assets/8856d42a-6788-40c0-b81b-1a5667a5112c)

![image](https://github.com/user-attachments/assets/197dd520-7fc0-4a3b-8597-9200177554c6)

**Comment by jinyangcruise** [comment]
You are right. I made a mistake. I thought I need to click `Add Key/Value Pair` first then modify the `New Key` and `New Value` but the correct way is to modify the `New Key` and `New Value` then click `Add Key/Value Pair`.
