### ISSUE TITLE
Android Editor: `This shader has been modified on disk.` always apear after exit the game. 

### ISSUE THREAD

**Issue by llama-nl** [godotengine/godot#98876]
### Tested versions

4.3.stable - Compatibility renderer - Android Editor

### System information

Android 14

### Issue description

`This shader has been modified on disk.` popup  without any reason after exit the game. It is only happing with in 4.3

![Screenshot_20241106_084557](https://github.com/user-attachments/assets/ec954766-bbba-4351-8cfa-b439ed9d0ca8)

https://github.com/user-attachments/assets/e52b1ba1-fe86-45d7-b2ca-9442a21a2fac

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by JayTropper** [comment]
@llama-nl Try to activate the auto reload option in the editor settings.
Go to Editor -> Editor Settings -> General -> Text Editor -> Behavior. The second option is called "Auto Reload Scripts on External Change". After activating it, the dialog didn't pop up for me again.

**Comment by JayTropper** [comment]
@llama-nl A first fix would be to activate the auto reload option in the editor settings.
Go to Editor -> Editor Settings -> General -> Text Editor -> Behavior. The second option is called "Auto Reload Scripts on External Change". After activating it, the dialog didn't pop up for me again.

**Comment by llama-nl** [comment]
@JayTropper ok it is fix now. Don't know why it is not turned on default.
