### ISSUE TITLE
[Documentation] Complete the documentation of all script classes & functions of 1.0 before adding features.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#989]
I’ve seen many functions whose functionality, input and output parameters are not explained. Even whole classes. (Like SceneTree.)

Also certain things do not turn up in the code completion, even though they are documented.

So in terms of being usable, there’s no point in adding new features, if the old ones can’t even be used properly due to lacking documentation.

That’s why I really hope you complete the documentation as a high priority. (Preferably by having the code documented, and generating the wiki pages (and code completion data) from that.
(Showing short descriptions of the functionality and parameters right in the code completion would of course be even cooler.)

I also hope bug can serve as a marker for complete documentation of everything up to the 1.0 release. 

Thank you. :)

**Comment by reduz** [comment]
class info still misses stuff, but code completion should work much better, did you give it a check?

**Comment by akien-mga** [comment]
Completing the classes documentation is an ongoing effort and has high priority for the upcoming 2.0 release, so I'll archive this issue.
