### ISSUE TITLE
SpinBox: setting step / min_value / value in wrong order adds min_value to value

### ISSUE THREAD

**Issue by Huraqan** [godotengine/godot#98922]
### Tested versions

Reproducible in v4.3.stable.official [77dcf97d8]

### System information

Android 12

### Issue description

Setting **step** on a SpinBox after having set its **min_value** and **value** to floats will add **min_value** to **value**. If step is set first, then there is no problem.

### Steps to reproduce

```gdscript
	var sb = SpinBox.new()
	
	sb.min_value = 0.42
	sb.value = 1.0
	sb.step = 0.01
	
	add_child(sb)
```

Displays "1.42"

### Minimal reproduction project (MRP)

[https://www.dropbox.com/scl/fi/8cqdoygfrpjeowozr1epp/spinbox_min_value_step_bug.zip?rlkey=5ofopr0lv1jsdxycorcl4nd34&st=42y86n27&dl=0](url)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been reported in:
* https://github.com/godotengine/godot/issues/91482

And we prefer to keep things in one place, so I will go ahead and close this.

See there for more details, if you think this is a different bug please comment here and this can be reopened
