### ISSUE TITLE
Bounding box gizmo gets distorted

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9894]
Godot 3.0 alpha1 official
Windows 10 64 bits

Bounding boxes are distorted when non square and rotated in some way:
![image](https://user-images.githubusercontent.com/1311555/28648491-768105c0-726e-11e7-9362-c0b26863fed1.png)

**Comment by reduz** [comment]
@tagcup Any idea on this?
I can't get this to happen, so steps to rerpdouce the problem would be useful!

**Comment by Zylann** [comment]
1) Create a MeshInstance
2) Create a BoxMesh (procedural) in its mesh property
3) Click on the mesh and set its size to (2,1,1)
3.1) Resize the editor's window to get rid of the fullscreen-black-with-thumbnail-on-bottom-left bug
4) Rotate the MeshInstance on the Z axis:

![image](https://user-images.githubusercontent.com/1311555/29589185-92b2a92a-8794-11e7-8a91-4b4beb370ede.png)

**Comment by tagcup** [comment]
I first though this might be due to a piece of code that I didn't properly change when I fixed the scaling and rotation, but actually I'm even seeing shearing.

@reduz, can you point me to the code which determines the shape of the bounding box?
