### ISSUE TITLE
String.pad_zeros() doesnt work correctly with hex

### ISSUE THREAD

**Issue by sanlor** [godotengine/godot#98959]
### Tested versions

v4.3.stable.steam [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 5700G with Radeon Graphics (16 Threads)

### Issue description

I believe that the behavior of the String.pad_zeros() is not working correctly.
It behaves great with binary and decimal numbers, but with hexadecimal numbers it just appends the number at the end.

### Steps to reproduce

Fun the following script:
```
print( String.num_int64(0, 16) )
print( String.num_int64(9, 16) )
print( String.num_int64(10, 16) )
print( String.num_int64(255, 16) )

print( String.num_int64(0, 16).pad_zeros(2) )
print( String.num_int64(9, 16).pad_zeros(2) )
print( String.num_int64(10, 16).pad_zeros(2) )
print( String.num_int64(255, 16).pad_zeros(2) )
```
Replacing the `String.num_int64(10, 16).pad_zeros(2)` with `str("%x" % 10).pad_zeros(2)` yields the same result.

The output is:
```
0
9
a
ff

00
09
a00
ff00
```

The expected output is:
```
00
09
0a
ff
```

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Not sure if it's a bug, `pad_zeros` is intended for decimals. For hex, you can use `.lpad(2, "0")` instead.

**Comment by sanlor** [comment]
> Not sure if it's a bug, `pad_zeros` is intended for decimals. For hex (or any other string), you can use `.lpad(2, "0")` instead.

Got it. I guess I was too used to pad_zeros from previous projects. After seeing the weird behavior, I thought it was a bug. The lpad() function works perfectly. Thanks.
