### ISSUE TITLE
Native EditorFileDialog with options not showing on Gnome 47

### ISSUE THREAD

**Issue by HolonProduction** [godotengine/godot#98950]
### Tested versions

- v4.3.stable.flathub [77dcf97d8]
- v4.4.dev.custom_build [36e6207bb]

### System information

Fedora 41, Gnome 47

### Issue description

Since upgrading to Fedora 41 (and thus Gnome 47, which brings a new Nautilus based system file picker) native file dialogs with options don't work anymore. If there are no options the native dialog shows just fine. With options only the builtin dialog pops up, when using the native mode nothing happens at all, rendering certain functionality (like exporting) useless, especially from the Flatpak version which always uses native dialogs.

I assume we are using some portal for this, so it might also be a Gnome issue.

### Steps to reproduce

- Enable native file dialogs in the editor settings
- Open any project (a new one will also do)
- Open the export menu
- Add an export platform if none exists
- Click on "Export PCK/ZIP"
- Observe that nothing happens

### Minimal reproduction project (MRP)

A new project will do

**Comment by bruvzg** [comment]
> Seems like GNOME 47 do no handle bool options.

Or it's handling it sometimes (seems like it doesn't handle ID's with spaces, which can be fixed on our side). Also, file filter display behaves strange.
