### ISSUE TITLE
Windows builds with mingw-gcc on Linux get the `.exe` extension twice (`godot.windows.editor.x86_64.exe.exe`)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#98967]
### Tested versions

- Reproducible in 4.4-dev (36e6207bb48fafd43b98a458d0c461ad982b4e68)
- Not reproducible in 4.3-dev3 or earlier

### System information

Fedora Linux 41 (KDE Plasma) on Wayland - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

Building for Windows from Linux with mingw-gcc seems to have regressed as it now doubles the `.exe` extension on the produced binaries.

```
scons p=windows
```
gives:
```
$ ls bin -l
total 123360
-rwxr-xr-x. 1 akien akien    188928 Nov  8 16:26 godot.windows.editor.x86_64.console.exe.exe
-rwxr-xr-x. 1 akien akien 126126080 Nov  8 16:26 godot.windows.editor.x86_64.exe.exe
```

### Steps to reproduce

On Linux with mingw-gcc:
```
scons p=windows
```

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment]
Regression from #98105, CC @Repiteo @bruvzg.

But more than a bug in this PR, I think the PR fixed a bug and made an old hack redundant:

https://github.com/godotengine/godot/blame/master/platform/windows/detect.py#L722-L723

We can likely just remove those two lines.

**Comment by bruvzg** [comment]
I can confirm the same on macOS as well (have not noticed it when testing #98968, since I was not running executables built on Mac).

**Comment by bruvzg** [comment]
> I can confirm the same on macOS

#98968 do fix it.
