### ISSUE TITLE
All projects are "Unnamed project", even though they do have a name

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9896]
Godot 3.0 alpha1 official
Windows 10 64 bits

The project manager shows "Unnamed project" on all projects, but when I open project settings I can see a name (which is obviously not "Unnamed project"):

![image](https://user-images.githubusercontent.com/1311555/28648795-bdf9aad6-7270-11e7-8b0c-9118f6685f89.png)

Opening a project also doesn't open the main scene, I think it used to do that before. Maybe there is an issue with the parsing of config files in the project manager?

The config file for the one under `/Test3`:

```
config_version=3

[application]

name="Test3"
main_scene="res://main.tscn"
icon="res://icon.png"

[display]

stretch/mode="viewport"

[memory]

multithread/thread_rid_pool_prealloc=60

[rendering]

viewport/default_clear_color=Color( 0.407806, 0.628906, 0.618542, 1 )
shadows/directional_shadow_size=4096
```

**Comment by RandomShaper** [comment]
That's because `name` and `icon` now are prefixed with `config/`. You can edit all your __`project.godot`__ files and do the change manually.

**Comment by Noshyaar** [comment]
This will only affect projects created in unstable master branch. New projects will have their name displayed correctly. IMO this doesn't need to be fixed.

**Comment by Zylann** [comment]
Note that I edited my project file to force Godot to save it, but that didn't fixed it.

**Comment by RandomShaper** [comment]
Close Godot and edit the files with a text editor.

The wrongly named properties belong to a transient state of Godot, so as long as that works for you, everything's alright.

**Comment by Zylann** [comment]
I set them all to null, then they disappeared. I named the new ones accordingly.

**Comment by akien-mga** [comment]
Also `main_scene` should become `run/main_scene`.
