### ISSUE TITLE
Nested typed collections are not supported.

### ISSUE THREAD

**Issue by MarkoGrbec** [godotengine/godot#98986]
### Tested versions

reproducible in 4.4dev-3, 4.4dev-4

### System information

Linux 6.10.11-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Sep 26 03:28:26 UTC 2024 x86_64 GNU/Linux

### Issue description

Nested typed collections are not supported.
it should have ability to have nested typed arrays or dictionaries

### Steps to reproduce

just write a sample code:
```
enum some_enum
{
    test,
    test1
}


var dict: Dictionary[int, Array[int]]
var array: Array[Array[int]]

var dict: Dictionary[int, Array[some_enum]]
```

an error should be given:
`Nested typed collections are not supported.`

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
This is not a bug, but a known and documented limitation of the current implementation. To support nested types, we will need significant refactoring.

See also:

* https://github.com/godotengine/godot-proposals/discussions/10022
* https://github.com/godotengine/godot-proposals/issues/10807#issuecomment-2366926108
* Other proposals/discussions with keywords unified type system and first-class types.

Thanks for the contribution nonetheless!
