### ISSUE TITLE
Boolean property says "activated" but the checkbox isn't

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9898]
Godot 3.0 alpha1 official
Windows 10 64 bits, language french

The checkbox here isn't ticked, but the label says "activated" in french. Checking or unchecking doesn't change the label.
![image](https://user-images.githubusercontent.com/1311555/28649893-6a44f938-7278-11e7-980c-363d4486e262.png)

**Comment by Noshyaar** [comment]
In English, it says "On" regardless of its checking state.
[Weblate](https://hosted.weblate.org/translate/godot-engine/godot/fr/?checksum=f6e34571a47aa13b)

**Comment by akien-mga** [comment]
Needs to be fixed here: https://github.com/godotengine/godot/blob/25678b1/editor/property_editor.cpp#L3144

**Comment by vnen** [comment]
Never thought of this as a bug, just interpreted that "On" is only the case if the box is ticked. Changing labels always confuse me because if it says "Off", but the box in unticked, I never know if it means that it is actually off or it'll turn off when I tick the box. I've seen different behaviors in other software.

**Comment by akien-mga** [comment]
Hm, that's a good point. I'm not sure which logic is the best for such a checkbox.

**Comment by Zylann** [comment]
@vnen now that you say this... I realize the "On" everywhere in Godot 2.1.3 never bothered me, but for some reason it did when the editor started showing it in my mother tongue...

**Comment by Noshyaar** [comment]
TBH I'm more comfortable with previous behavior where label never changed. (that's why I put weblate link there because I think it's more of a translation bug)

Feel free to revert. :)

**Comment by akien-mga** [comment]
> (that's why I put weblate link there because I think it's more of a translation bug)

Well if we agree that the previous behaviour was correct, then the translation was correct too. "Activé" means "activated", it's an ok translation for "On".

**Comment by Noshyaar** [comment]
Maybe if we make "On" or "Activé" text a bit darker when property is false, it might be less confusing to user?

**Comment by akien-mga** [comment]
I've reverted the PR since we apparently misunderstood the feature.

> Maybe if we make "On" or "Activé" text a bit darker when property is false, it might be less confusing to user?

That could work yeah.
