### ISSUE TITLE
EditorFeatures enum is incorrectly ordered after new 'Game View' feature has been added

### ISSUE THREAD

**Issue by ev13bird** [godotengine/godot#98981]
### Tested versions

- Reproducible in: 4.4.dev4.mono

### System information

Godot v4.4.dev4.mono - Windows 10 - Vulkan (Forward+)

### Issue description

In `Editor -> Manage Editor Features...`, the addition of the new 'Game' main feature has caused each feature's displayed name to be mismatched with the actual connected feature.

Relevant issue: #97257

Relevant changes seem to be with changes to the enums at:
- `editor/editor_feature_profile.cpp:46`
- `editor/editor_feature_profile.cpp:58`
- `editor/editor_feature_profile.cpp:70`
- `editor/editor_feature_profile.cpp:313`

### Steps to reproduce

- Open `Editor -> Manage Editor Features...` to the Manage Editor Feature Profiles window.
- Disable 'Game View' feature, and note that the 'Asset Library' feature is disabled instead.
- Disable 'Asset Library' feature, and note that the 'Scene Tree Editing' feature is disabled instead.

### Minimal reproduction project (MRP)

N/A

**Comment by snougo** [comment]
reproduce
<img width="980" alt="截屏2024-11-09 16 05 48" src="https://github.com/user-attachments/assets/ef9be1ab-7f57-40a1-a45f-0702e74d5173">
