### ISSUE TITLE
[4.4-dev-4] VoxelGI baking crash

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#98994]
### Tested versions

- Reproducible in 4.4-dev-4
- Debian GNU/Linux
- AMD Ryzen 7 5800X
- NVIDIA GeForce RTX 3070

### System information

Debian GNU/Linux trixie/sid x86_64 - Vulkan Forward +

### Issue description

Baking lightmap crash

### Steps to reproduce

- Download attached tar.gz
- Create empty project
- Extract tar.gz into the new project
- Import GLTF
- Add VoxelGI to the project
- Bake lightmap
- Crash I get one of these:
    - free(): invalid next size (normal)
    - malloc(): invalid size (unsorted)

It used to work, but it doesn't since the 4.4-dev4. I have other environnment to bake, but they also crashes with different errors (malloc and stuff)

https://github.com/user-attachments/assets/2a47aa72-4560-4b1e-aa7b-26610ac46a4d

### Minimal reproduction project (MRP)

[surrounding-to-delete.tar.gz](https://github.com/user-attachments/files/17688500/surrounding-to-delete.tar.gz)

**Comment by matheusmdx** [comment]
I was unable to reproduce the issue, maybe only happens with nvidia gpu?

Godot v4.4.dev4 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 threads)

**Comment by snougo** [comment]
it doesn't crash on Mac M3Max 4.4 dev4

**Comment by xsellier** [comment]
Closing it since it works with Godot 4.4-dev5 !
