### ISSUE TITLE
[4.4-dev4] Floats and decimal in UI when integers should be used

### ISSUE THREAD

**Issue by 4X3L82** [godotengine/godot#99000]
### Tested versions

- Reproducible in 4.4-dev4

### System information

Godot v4.4.dev4 - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:11:08 UTC 2024 on X11 - X11 display driver, Single-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU - AMD Ryzen 9 5900HX with Radeon Graphics (16 threads)

### Issue description

In the `Monitors` of the debugger there are many values that apparently are floats and which with [this pull](https://github.com/godotengine/godot/pull/47502) now turned a bit ugly/unnecessary:
![image](https://github.com/user-attachments/assets/a93043b9-1b23-4a9c-bf6b-21734e702477)

I don't expect that the number of nodes or draw calls could be anything other than an integer? *Many* items in the Monitor list should either be an integer or not display the decimal. Besides the values, the same goes for the little graphs containing floats (Nodes: 31.0, **23.25**, **15.5**, **7.75**).

### Steps to reproduce

Open up *any* project and go to Monitors to have a look at the values & graphs.

### Minimal reproduction project (MRP)

Not relevant.

**Comment by Trekkan** [comment]
This still appears to be a problem with the release of 4.4.  Same repro steps, etc.

**Comment by 4X3L82** [comment]
> This still appears to be a problem with the release of 4.4. Same repro steps, etc.

I'm running v4.4.stable.official [4c311cbee] and everything looks correct on my side.
