### ISSUE TITLE
Unable to access instanced scene menu options on an instanced inherited scene

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#9901]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 3.0 Alpha 1

**Issue description:**
If a scene is inherited from one scene and is instanced in another scene, there will be no options to discard instancing (only clear inheritance), or to make children editable, or to load the instance as a placeholder.

[Screenshot of menu with instanced scene](http://i.imgur.com/JASWcX5.png)
[Screenshot of menu with instanced inherited scene](http://i.imgur.com/MaszPV7.png)

**Comment by akien-mga** [comment]
CC @kubecz3k
