### ISSUE TITLE
Crash while adding fbx file to scene

### ISSUE THREAD

**Issue by MarkoGrbec** [godotengine/godot#99019]
### Tested versions

reproducible in 4.4Dev-4
not reproducible in 4.4Dev-3

### System information

Linux 6.10.11-2-MANJARO, Intel Core i7-4700HQ, NVidia Geforce GTX 850M

### Issue description

Importing seems to work but when I drag and drop fbx file to scene it crashes

it's same for glb and gltf files

do not know why but some other FBX files were working flawlessly could be because they were very small

### Steps to reproduce

simply drag and drop fbx file to scene

### Minimal reproduction project (MRP)

[animation IK testing.zip](https://github.com/user-attachments/files/17691287/animation.IK.testing.zip)

**Comment by JekSun97** [comment]
I don't have this problem on Windows 10
Godot v4.4.dev4 - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads)

**Comment by fire** [comment]
It doesn't crash for me on v4.4.dev.gh-94321 [93112d811]

**Comment by snougo** [comment]
it doesn't crash on Mac M3Max 4.4 dev4

**Comment by MarkoGrbec** [comment]
I just made a fresh install on 2 devices was hoping to have a system problem but it seems I have a hardware problem

device with crash:
Intel Core i7-4700HQ
NVidia Geforce GTX 850M

device with no crash: 
AMD Dual-Core processor E450
AMD Radeon HD 6320

**Comment by MarkoGrbec** [comment]
I don't get crash on 4.4-Dev6.

so I'm closing.
