### ISSUE TITLE
Some shaders got darker when loading project in dev-3 (still present in dev-4) 

### ISSUE THREAD

**Issue by AlexanderParker** [godotengine/godot#99011]
### Tested versions

- Reproducible in 4.4 dev-3 (official) and 4.4 dev-4 (official)
- Not reproducible in 4.4 dev-1 (official), 4.4 dev-2 (official)

### System information

Godot v4.4.dev4 - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 32.0.15.6081) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 threads)

### Issue description

**Describe your issue briefly. What doesn't work, and how do you expect it to work instead?**

I built the project initially in 4.3, and moved to 4.4 Dev 1 without any graphical issues.

After a few months hiatus, I opened the project in 4.4 and saw that the shaders were darker than usual. The 4 screenshots below are in order are from 4.4 dev 1 (correct), dev2 (correct), dev3 (issues) and dev4 (issues). I'd expect to see the same output when moving between different versions of the editor.

The lighting of the scene is consistent (just a single global sun light), no changes to code or scenes made between these screenshots, just opening the project in a different version of the editor.

**4.4 Dev-1 (correct)**

<img width="620" alt="4 4-dev1" src="https://github.com/user-attachments/assets/8a07e67c-803e-45b9-95b4-e1c7657e6766">

**4.4 Dev-2 (correct)**

<img width="616" alt="4 4-dev2" src="https://github.com/user-attachments/assets/fe115380-ca23-4dd4-afc3-02106a04e0dd">

**4.4 Dev-3 (issues - darker crystals and ship, missing texture on asteroids)**

<img width="617" alt="4 4-dev3" src="https://github.com/user-attachments/assets/aa07af3c-4944-40c4-9d89-b2b8a65b5b3d">

**4.4 Dev-4 (issues - darker crystals and ship, but texture is fixed on asteroids)**

<img width="617" alt="4 4-dev4" src="https://github.com/user-attachments/assets/a404faae-5ced-440a-b2b6-5ccd54e464f8">

### Steps to reproduce

1. Open the MRP in Godot 4.4 Dev 2 (official) (NOTE: Dev 1 works but with load errors that aren't related to the bug, I think it's something to do with onedrive locally.).
3. Run the scene and observe the single object and its shading, which is "correct" visually:

<img width="48" alt="repro 4 4 dev2" src="https://github.com/user-attachments/assets/e817ac93-799c-41a9-88ee-3d01972f1d53">

5. Open the MRP in 4.4 Dev 4
6. Run the scene and observe the difference / darker color shading, which appears "incorrect" (darker) visually.

<img width="41" alt="repro 4 4 dev4" src="https://github.com/user-attachments/assets/deb72290-2223-4622-ade1-cd03b3d9ecf5">

### Minimal reproduction project (MRP)

[Shader-Bug-Repro.zip](https://github.com/user-attachments/files/17690231/Shader-Bug-Repro.zip)

**Comment by Lippanon** [comment]
I had a look. Your material is selected to use "Per-Vertex" shading, however this was only implemented recently in https://github.com/godotengine/godot/pull/83360.
If you mouseover that property it says "Not implemented yet" (it is now implemented but that note will get removed soon in https://github.com/godotengine/godot/pull/97917/). I didn't check the dates but I suspect in dev2 it would fallback to the "Per-Pixel" mode, and in dev4 it actually does something so you see this different behaviour.

Simply change the material's shading mode to default to get your "old dev" behaviour, which is per-pixel shading:
![image](https://github.com/user-attachments/assets/5f4b4779-a8e2-46be-8eb7-d68e4e4dda08)

**Comment by AlexanderParker** [comment]
@Lippanon thank you for taking a look. I was unaware per-vertex shading wasn't implemented before (I guess I never checked the mouseover text), but that timeline with the versions makes sense. Changing to per-pixel fixed my problem, thanks.

I'm wondering if this happens to others whether 1it might be worth adding a message shown when loading a project that was made before vertex shaders were implemented if any shaders are detected using the setting as I'd notice an error in the message window more.

Anyway thanks again for the quick fix, I probably would not have worked this out for a long time so you're a life saver :)
