### ISSUE TITLE
Diraccess has problems with accessing files when exported

### ISSUE THREAD

**Issue by BrianBHuynh** [godotengine/godot#99047]
### Tested versions

- Reproducible Godot v4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 4070 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

Diraccess seems to have a few problems with accessing files once exported, this has been observed to happen when trying to get the name of files within a directory. In my main project I can use get_files_at() to get the names of all the files in a directory, however once trying to do that in the export it only exports part of 3 file names.

In the minimum reproducible project on 4.3 stable, the folder is not found at all 

![image](https://github.com/user-attachments/assets/019d524c-b6f3-45f7-937a-c0ea428c6671)
![image](https://github.com/user-attachments/assets/910ddc3d-9c1c-4c8a-b5e6-f84fcff503b5)

### Steps to reproduce

Diraccess get files at --> folder

then export

either the folder won't be found or the file names listed will be incomplete

### Minimal reproduction project (MRP)

[newGameProject.zip](https://github.com/user-attachments/files/17697512/newGameProject.zip)

**Comment by BrianBHuynh** [comment]
This is what it looks like in my current project in the editor:
![image](https://github.com/user-attachments/assets/b009418f-bc22-451b-a9ba-8fd7db4b99d0)

and this is what it looks like in the windows exported console
![image](https://github.com/user-attachments/assets/25cf14a1-6f83-4b99-88c3-c7fd9cf66960)

Note how the file name is just cutoff for opendyslexic-regular.otf.imp

**Comment by addmix** [comment]
the res:// filesystem is imported/converted into godot internal format during the export process. 
.import files contain the mapping information of the source file path to the imported internal file (imported files are .scn for scenes, .ctex for textures). 

You should be able to load data from the .import files using ConfigFiles, reading the `[deps]: source_file` string, which you can then pass to `load()`. Though, more easily being able to explore/dynamically load items in folders at runtime is a very useful feature.

I know there are at least a couple other issues and proposals relating to the exported project filesystem, but I can't seem to find them.

**Comment by BrianBHuynh** [comment]
Thanks for the clarification o7 I think a warning being shot out when using diraccess get_files and etc might be a good idea then if the prefix is res
