### ISSUE TITLE
Main thread sometimes deadlocks when allocating textures on a separate thread

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#99043]
### Tested versions

4.4 0f5f3bc9546b46b2029fc8896dc859697f1eab97

### System information

Arch Linux (RADV), Windows 11, Windows 10 (AMD Proprietary, AMD Open Source, Nvidia Proprietary).

### Issue description

Trying to run ImageTexture.create_from_image from another thread sometimes causes a deadlock.

Specifically, the deadlock seems to occur when trying to lock the transfer worker pool. In this line:

https://github.com/godotengine/godot/blob/master/servers/rendering/rendering_device.cpp#L5106

I wonder if this may be related to the new transfer queue stuff?

### Steps to reproduce

Load up the MRP's control.tscn

Spam F1 until it hangs. (A rotating image is provided to better show when it has hanged).

### Minimal reproduction project (MRP)

[hang_bug.zip](https://github.com/user-attachments/files/17695003/hang_bug.zip)

**Comment by clayjohn** [comment]
Can you clarify whether it hangs or deadlocks? Is this a temporary pause, or is the game deadlocking and needs to be force closed?

Cc @DarioSamo

**Comment by EIREXE** [comment]
> Can you clarify whether it hangs or deadlocks? Is this a temporary pause, or is the game deadlocking and needs to be force closed?
> 
> Cc @DarioSamo

Oh yeah my bad, it deadlocks completely.

**Comment by DarioSamo** [comment]
Can you confirm if https://github.com/godotengine/godot/pull/99066 fixes the issue? I was able to reproduce and fix it on my end using the provided MRP. although I had to artificially lower my processor count in the code and switch the task dispatch to be on every frame instead. That led to reproducing it fairly quickly. It's been running on my end for quite a few minutes like this already.

**Comment by EIREXE** [comment]
> Can you confirm if #99066 fixes the issue? I was able to reproduce and fix it on my end using the provided MRP. although I had to artificially lower my processor count in the code and switch the task dispatch to be on every frame instead. That led to reproducing it fairly quickly. It's been running on my end for quite a few minutes like this already.

Just tried it, seems to fix it!
