### ISSUE TITLE
Godot Editor Crash in export overwrite panel

### ISSUE THREAD

**Issue by eliacanavera1111** [godotengine/godot#99053]
### Tested versions

- Reproducible in 4.3 stable

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

If you try exporting a project in the same folder of a file with the same name, when you click on "Export the project" and then "Save", as expected you'll be asked if you want to overwrite that file. But if, instead of clicking Ok or Cancel, you click again on the Save button, the editor crashes and you are forced to terminate the process.

### Steps to reproduce

Open a project, go to "Project", "Export...", "Export the project...", "Save". Do it again without changing names and folders, and when you're asked to overwrite the existing file, instead of clicking "Ok" or "Cancel" click again on "Save".

### Minimal reproduction project (MRP)

any project

**Comment by matheusmdx** [comment]
I tried to reproduce the issue but worked as expected


https://github.com/user-attachments/assets/e9eb7456-3c3d-4dfa-8d2a-702fa4338341

<br>

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

**Comment by eliacanavera1111** [comment]
Try clicking 2 times the Save button (don't use Ok / Cancel buttons) @matheusmdx

**Comment by syntaxerror247** [comment]
I also cannot reproduce this issue.
@eliacanavera1111 I tried clicking on save button twice. It doesn't crash for me.

**Comment by eliacanavera1111** [comment]
Interesting @syntaxerror247 , on my pc it happens every time I click Save more than once, but I tried on a different pc with the same godot version and it's not doing the same. Since it's not happening to you and for the nature of the issue, easily avoidable, I close it now. Thanks for testing.
