### ISSUE TITLE
4.4_dev4: round(), ceil(), floor() functions return floating-point numbers with spurious ".0" at the end.

### ISSUE THREAD

**Issue by ProfCJLee** [godotengine/godot#99056]
### Tested versions

Reproducible in 4.4_dev4, No errors on 4.4_dev3

### System information

Windows & Mac OS

### Issue description

Simple test of round(), ceil(), floor() functions return floating-point numbers instead of integers by attaching ".0" at the end of the numbers.
![godot4 4d4](https://github.com/user-attachments/assets/eaf2235c-ac67-4602-be4b-3078dab2580f)

### Steps to reproduce

Create any project. print(round(2.5)) etc. gives 3.0 not 3. Other numbers return the same +".0" at the end of the value.

### Minimal reproduction project (MRP)

[basic_tests.zip](https://github.com/user-attachments/files/17699997/basic_tests.zip)

**Comment by RedMser** [comment]
This is an intentional change: https://godotengine.org/article/dev-snapshot-godot-4-4-dev-4/#always-add-decimal-when-converting-float-to-string

In most math libraries, round/floor/ceil return float btw.

**Comment by timothyqiu** [comment]
These functions used to return floats as well.

Printing a float requires that it be converted to a string first. What has changed is the strategy for converting float to string. It has nothing to do with functions like `ceil()`, `round()`, etc.

**Comment by ProfCJLee** [comment]
Hmmm. Let's compare with other languages.
[Other languages.txt](https://github.com/user-attachments/files/17710651/Other.languages.txt)

**Comment by Chaosus** [comment]
Since it is not a bug but intended behavior, if author think that it should be changed - the proposal should be created instead of issue.
