### ISSUE TITLE
Fail to build mono glue

### ISSUE THREAD

**Issue by HKunogi** [godotengine/godot#99069]
### Tested versions

- Tested in 0f5f3bc9546b46b2029fc8896dc859697f1eab97

### System information

Windows 11 Pro

### Issue description

After the latest commits on godot (it used to build fine before that) the mono glue fails to be built with the following errors:
` Godot.SourceGenerators.Internal succeeded (1.3s) → glue\GodotSharp\Godot.SourceGenerators.Internal\bin\Debug\netstandard2.0\Godot.SourceGenerators.Internal.dll
  GodotSharp failed with 3 error(s) and 7 warning(s) (6.2s)
    D:\Source\Other\gd-engine\modules\mono\glue\GodotSharp\GodotSharp\Compat.cs(35,12): error CS0246: The type or namespace name 'AnimationMethodCallMode' could not be found (are you missing a using directive or an assembly reference?)
    D:\Source\Other\gd-engine\modules\mono\glue\GodotSharp\GodotSharp\Compat.cs(51,12): error CS0246: The type or namespace name 'AnimationProcessCallback' could not be found (are you missing a using directive or an assembly reference?)
    D:\Source\Other\gd-engine\modules\mono\glue\GodotSharp\GodotSharp\Compat.cs(62,12): error CS0246: The type or namespace name 'AnimationProcessCallback' could not be found (are you missing a using directive or an assembly reference?)`
This is most surely caused by the new errors that popped in during the glue generation procedure which  are all as this following one:
`Cannot reference editor type 'EditorImportPlugin' in documentation for core type 'ImageTexture'
Generating ImageTexture3D.cs...
Generating ImageTextureLayered.cs...
ERROR: Cannot resolve method reference in documentation: 'Image.create'.
   at: BindingsGenerator::_append_xml_method (modules\mono\editor\bindings_generator.cpp:1151)`
This does happen quite a few times on other areas, like:
`ERROR: Cannot resolve method reference in documentation: 'Skeleton3D.clear_bones_global_pose_override'.
   at: BindingsGenerator::_append_xml_method (modules\mono\editor\bindings_generator.cpp:1151)`
and
`ERROR: Cannot resolve method reference in documentation: 'make_polygons_from_outlines'.
   at: BindingsGenerator::_append_xml_method (modules\mono\editor\bindings_generator.cpp:1151)
ERROR: Cannot resolve method reference in documentation: 'make_polygons_from_outlines'.
   at: BindingsGenerator::_append_xml_method (modules\mono\editor\bindings_generator.cpp:1151)
ERROR: Cannot resolve method reference in documentation: 'make_polygons_from_outlines'.
   at: BindingsGenerator::_append_xml_method (modules\mono\editor\bindings_generator.cpp:1151)`

### Steps to reproduce

Simply use latest commit to build from source with mono support, it will build the engine but fail to generate/build the mono glue.

### Minimal reproduction project (MRP)

Build issue.

**Comment by raulsntos** [comment]
I'm unable to reproduce, please provide the commands you are using to build the engine.

**Comment by raulsntos** [comment]
> I found out that the given error only happens when using `deprecated = "no"` on the `custom.py`, in case of using `deprecated = "yes"` the error does not occurs.

If you are building Godot without deprecated API, you also need to build the .NET assemblies without deprecated API (using the [`--no-deprecated`](https://github.com/godotengine/godot/pull/96570) flag). It doesn't look like you are doing that from the commands you listed, it should be something like this:

```
python ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --push-nupkgs-local=%NUGET_PACKAGES%..\sources --no-deprecated
```

> Also I noticed this at the beginning of the mono glue generation:
`WARNING: Unknown command line argument "--generate-mono-glue". User arguments should be passed after a -- or ++ separator, e.g. "-- --generate-mono-glue".`
Did the command for it change?

No, this is a false positive due to a recent change: https://github.com/godotengine/godot/pull/98895 (cc @Calinou). It seems the command still works despite the warning.

**Comment by HKunogi** [comment]
> > I found out that the given error only happens when using `deprecated = "no"` on the `custom.py`, in case of using `deprecated = "yes"` the error does not occurs.
> 
> If you are building Godot without deprecated API, you also need to build the .NET assemblies without deprecated API (using the [`--no-deprecated`](https://github.com/godotengine/godot/pull/96570) flag). It doesn't look like you are doing that from the commands you listed, it should be something like this:
> 
> ```
> python ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --push-nupkgs-local=%NUGET_PACKAGES%..\sources --no-deprecated
> ```
> 
> > Also I noticed this at the beginning of the mono glue generation:
> > `WARNING: Unknown command line argument "--generate-mono-glue". User arguments should be passed after a -- or ++ separator, e.g. "-- --generate-mono-glue".`
> > Did the command for it change?
> 
> No, this is a false positive due to a recent change: #98895 (cc @Calinou). It seems the command still works despite the warning.

I see, i did not know that, ill give a try right now and post the results.

**Comment by raulsntos** [comment]
> The generating of .cs files part stills gave the errors of things not being found in documentation, are there any flag for the .cs file generation script as well?

Some documentation may reference deprecated API and the compiler will complain it can't find it. But these should be warnings, and can be safely ignored.
