### ISSUE TITLE
Possible race condition with animated sprites

### ISSUE THREAD

**Issue by joaobgoode** [godotengine/godot#99076]
### Tested versions

Reproduced in:
Godot 4.3 - stable, with mostly crashes, if not, flood of errors ,and almost never not happening 
Godot 4.2.2 - stable , with doesn't crash as often, and it doesn't happen more often than on 4.3, but istill happens 
Godot 4.1.4 - stable, same as 4.3

also tested on Windows 10 machine, same results

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4953) - 13th Gen Intel(R) Core(TM) i5-1335U (12 Threads)

### Issue description

Possible race condition when using tool script and setting animation on a sprite2d, when opening the editor in a scene with a child scene with these conditions either it crashes or it opens but the console is flooded if a error that has the message "!has_animation(p_name)" is true

### Steps to reproduce

1. Create a Area2d scene
2. Add a node2d child
3. Add a AnimationPlayer2d child
4. Add spritesheet to the sprite
5. Add a couple of animation involving frames
6. Add a collisionshape2d child and give it a shape
7. Add a script with the following:

```gdscript
@tool
extends Area2D

enum animations {animation1, animation2}
@export var animation : animations = animations.animation1 : set = _set_animation

func _set_animation(new_aniamtion):
	animation = new_aniamtion
	if animation == animations.animation1:
		$AnimationPlayer.play("animacao 1")
	elif animation == animations.animation2:
		$AnimationPlayer.play("animacao 2")
```

8. Save the scene
9. Add another scene
10. Add the first scene as a child
11. Pick a animation in the inspector
12. Save it
13. Open the 2d visualization
14. Leave the editor with that tab open
15. Attempt to open again

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/user-attachments/files/17704585/MRP.zip)
![Captura de tela 2024-11-11 124515](https://github.com/user-attachments/assets/82ae909e-1c9e-492d-86db-b0c0ff664dc4)

**Comment by PhairZ** [comment]
I tried reproducing it myself and also tried using the mrp.zip file and I can't seem to get the engine to crash in neither 4.3.stable nor 4.4.dev4.

**Comment by joaobgoode** [comment]
> I tried reproducing it myself and also tried using the mrp.zip file and I can't seem to get the engine to crash in neither 4.3.stable nor 4.4.dev4.

Before sending the issue i tested on 3 different computers and on 3 different versions, all of them it crashed, tested with multiple reproductions from the start as well, now i cant reproduce either, even though all the files i tested still crashes. That made me think something could be up on my  .godot folder, so i deleted from one of the tests, and it worked, it doesn't crash anymore. 

Sorry if this is nothing and i wasted people's time, I won't pretend I know how any of this works

**Comment by PhairZ** [comment]
Thats great to hear.
I guess we can close the issue.
