### ISSUE TITLE
Editor crashed when using msaa x16

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#9908]
**Operating system or device - Godot version:**
windows 10 (hd7850)
OS X (Intel(R) Iris(TM) Graphics 6100)

**Issue description:**

The editor crashes when setting the project settings to rendering>quality>msaa = x16 as soon as you open the 3d viewport.

**Comment by bruvzg** [comment]
macOS 10.12 (AMD FirePro D300); 3.0 - master

Crashes with:
>ERROR: _render_target_allocate: Condition ' status != 0x8CD5 ' is true.
>   At: [drivers/gles3/rasterizer_storage_gles3.cpp:6064](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L6064)

**Comment by bruvzg** [comment]
MSAA x16 works fine on Windows 10; NVIDIA GTX 960M
