### ISSUE TITLE
Changing a property of a duplicated item affects the other copies.

### ISSUE THREAD

**Issue by Syntrait** [godotengine/godot#99093]
### Tested versions

- Reproducible in: v4.3.stable

### System information

Godot v4.3.stable - Debian GNU/Linux trixie/sid trixie - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1650 Ti (nvidia) - AMD Ryzen 5 4600HS with Radeon Graphics (12 Threads)

### Issue description

Background was made first, then it was duplicated, to create SecondFloorBelowBackground
When I change the size of the Background/CollisionShape3D to match the size of the Background/CSGBox3D, SecondFloorBelowBackground/CollisionShape3D's size also gets changed.
I think this can be regarded as a bug, because if we truly wanted the duplicates (of different sizes) to have the same collision box size, a scene could have been used.

### Steps to reproduce

1.  Load the Godot project.
2. Open home_base.tscn
3. Change the size of Background/CollisionShape3D to 50,50,0.5
4. Change the size of SecondFloorBelowBackground/CollisionShape3D to 10,5,0.5
5. Background/CollisionShape3D has now a size of 10,5,0.5

### Minimal reproduction project (MRP)

[bug_report.zip](https://github.com/user-attachments/files/17708669/bug_report.zip)

**Comment by Rindbee** [comment]
This is not a bug because you are using the same resource (`BoxShape3D`) instance. 

![001](https://github.com/user-attachments/assets/76aa77be-f8ad-4c3d-ad4e-89c1e88bb1a5)

Make Unique is what you need.

**Comment by Syntrait** [comment]
Thank you, this worked. I am new to Godot, so I didn't know Make Unique was a thing.
