### ISSUE TITLE
Cannot use .obj files as meshes after opening a project in vanilla setup

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9910]
Godot 3.0 alpha1 official
Windows 10 64 bits

I ran Godot 3.0 for the first time on a new PC, and opened the project I linked here for the first time: https://github.com/godotengine/godot/files/1178454/Test3.zip 
(same working project as an earlier issue https://github.com/godotengine/godot/issues/9899#issuecomment-318240670)

For some reason, assets got re-imported even though there was an import folder already.
Then I realized the main scene wasn't showing any mesh anymore. All MeshInstances' `mesh` properties were set to `null`. 
I tried to create a new scene, add a MeshInstance, but I was unable to choose any obj file. When I click on them in the inspector, I am shown this message:

![image](https://user-images.githubusercontent.com/1311555/28670706-d3d45d72-72d1-11e7-994a-fb4c28ca58df.png)
These meshes are not scenes, they are... just meshes. I don't want to create scenes out of importing them.
So I went to the Import dock and noticed I could only import it as a scene Oo
What is going on?

![image](https://user-images.githubusercontent.com/1311555/28670784-1ea10d78-72d2-11e7-836c-d2a574ae826e.png)

Edit: the only way I could assign meshes back was to go into the .import folder and choose meshes from there instead of the obj file.

**Comment by akien-mga** [comment]
Yes, @reduz changed the workflow so that .obj files are always treated as scenes, like .dae. Not sure what's the recommended workflow to do what you need though.

**Comment by reduz** [comment]
OBJ files unfortunately are scenes, so the previous workflow avoided to
import them properly.
An alternative is to import a full scene and make it generate objects or
sub-scenes, check the "Preset.." menu in your picture

**Comment by Zylann** [comment]
How is an obj containing only one object a scene, in Godot terms? I don't understand why there isn't simply a choice in the list to import it as a normal Mesh just like it worked before. It sounds like I have to do a workaround now for every mesh I want to import the classic way, I liked the way it could be decided, not forced like now.
Importing "as separate objects" is the closest to what I expected, but it creates new folders with only one `.mesh` file inside...

**Comment by reduz** [comment]
In any case, I was thinking of eventually adding back the OBJ workflow, so you can select the type of file when importing (and default OBJ to mesh)

**Comment by eon-s** [comment]
Related to #9445? 
I guess the new presets didn't made into the alpha.

**Comment by Zylann** [comment]
Presets shown in #9445 are available, also they concern importing as Scene, while I'm referring to importing as Mesh.

**Comment by eon-s** [comment]
Right, is there, it does not name the mesh files (maybe is overwriting all in .mesh), names only works if imported as scene.

**Comment by rminderhoud** [comment]
The preset "Import as separate objects" seems to be a decent workaround for now. However, as @Zylann pointed out, reimporting the obj creates a file called `.mesh`. Unfortunately it can't be renamed because the reimport button will simply create another `.mesh` again.

**Comment by rredesigns** [comment]
I had some trouble with scene importing too in 3.0. I can't edit my opened scene (which is kinda stupid, since you open stuff in the "editor" to "edit", is not a scene viewer) and creating a new inherited scene only unlocks the root node, the rest remains uneditable.

The import process in 2.x was just perfect, you should have never changed it. Also, I didn't find a way to stop the automatic import process. I stash some scenes in my project folder, but I want those imported when I want only, not all the time at any change (which stalls the whole GUI in the mean time).

**Comment by reduz** [comment]
I guess this needs to be further improved. 

@rrdesigns what do you find is not editable in inherited scenes besides not being able to delete nodes?

**Comment by reduz** [comment]
I guess this needs to be further improved. 

@rrdesigns what do you find is not editable in inherited scenes besides not being able to delete nodes?

**Comment by rredesigns** [comment]
I can change values, so I can edit I guess. But if I want to delete the Animation Player or other unwanted node I can create inhereted scenes to eternity and never be able to do that. 

But, I just tried something else. And guess what? Reparenting unlocks the nodes and can be deleted. xD

**Comment by djrm** [comment]
This can be closed, since godot now imports OBJs as meshes
