### ISSUE TITLE
Sub Viewports don't render anything

### ISSUE THREAD

**Issue by Wolf17777** [godotengine/godot#9912]
**Operating system or device - Godot version:**
Windows 7 64bit - Godot 3.0 alpha1

**Issue description:**

Sub Viewports don't render anything.

**Steps to reproduce:**
-Create new project
-Add Control node and resize it so its visible in the game
-Add Viewport node to the Control node
-Add Something to the Viewport node, e.g. a Button
-Launch the game. The Button should be visible, but isn't.

**Comment by reduz** [comment]
oh, you need to use ViewportContainer, putting a viewport in a control is no longer supported.

**Comment by toger5** [comment]
Why do the viewports (without container) exist than? if they don't work alone. isn't that bad ux?
would it be possible to just remove vieport container and the viewport does everything the container handled before ?

**Comment by bojidar-bg** [comment]
@toger5 You can use them as standalone render targets, without rendering them to the screen.

**Comment by toger5** [comment]
@bojidar-bg that makes sense! Ty

**Comment by eiszfuchs** [comment]
It might be a good idea to update the documentation then. 🤔 
https://godot.readthedocs.io/en/latest/tutorials/viewports/viewports.html#sub-viewport
