### ISSUE TITLE
Exiting a running game with a texture bound to a global shader parameter causes a hang and an error.

### ISSUE THREAD

**Issue by bbbscarter** [godotengine/godot#99129]
### Tested versions

- Reproducible in Godot Engine v4.3.stable.mono.official
- Using C#.

### System information

MacOS 15.1, any renderer

### Issue description

Exiting the game causes a hang and the following error:
```
ERROR: FATAL: Condition "!rc_owner" is true.
   at: _instance_binding_reference_callback (modules/mono/csharp_script.cpp:1237)
```

This starts happening after using C# to create a texture and bind it to a global shader parameter.

### Steps to reproduce

1. Create a global shader parameter of type sampler2D called "texture_test" in the editor.
2. Create and bind a texture to it in code:
```
public override void _Ready() {
  var _testImage = new Image();
  _testImage = Image.CreateEmpty(256, 256, false, Image.Format.Rgba8);
  var _testTexture = ImageTexture.CreateFromImage(_testImage);

  RenderingServer.GlobalShaderParameterSet("texture_test", _testTexture);
}
```

3. Run the game and try to exit by pressing the red quit button. Notice the game hangs. 

4. Put in the following code and notice the hang goes away:
```
public override void _ExitTree() {
  RenderingServer.GlobalShaderParameterSet("texture_test", new Variant());
  base._ExitTree();
}
```

### Minimal reproduction project (MRP)

[hang-on-exit.zip](https://github.com/user-attachments/files/17718759/hang-on-exit.zip)

**Comment by matheusmdx** [comment]
This look like the same problem as #89188, try test Godot 4.4 dev 1 or higher to see if the crash stops. You can download them officially here: https://godotengine.org/download/archive/
