### ISSUE TITLE
Infinite loop between AspectRatioContainer and TextureRect

### ISSUE THREAD

**Issue by HeySora** [godotengine/godot#99130]
### Tested versions

- Reproducible in v4.3.stable.mono.official [77dcf97d8]

### System information

Godot v4.3.stable.mono - macOS 15.0.1 - GLES3 (Compatibility) - Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

The editor will hang indefinitely when both an AspectRatioContainer and a TextureRect have modes doing calculations on the width or height.

### Steps to reproduce

**From a brand new project**
1. Make a new scene, pick the "User Interface" root node
2. Add an AspectRatioContainer as a child
3. Change its ratio to anything that's not 1 (e.g. 0.5), and its Stretch Mode to "Width Controls Height"
4. Add a TextureRect as a child of the AspectRatioController
5. Give the TextureRect a texture (anything)
6. Change its Expand Mode to "Fit Width"

**From the MRP below**
Focus on the TextureRect and change its Expand Mode to "Fit Width"

### Minimal reproduction project (MRP)

[MRP-AspectRatioCrash.zip](https://github.com/user-attachments/files/17718934/MRP-AspectRatioCrash.zip)

**Comment by Schkimansky** [comment]
I was to reproduce this on my linux machine, Hanged for a while and then the editor started being really buggy. Although for me it didint hang indefinitely

**Comment by matheusmdx** [comment]
This is a known issue from `TextureRect` and is explained in the property tooltip, for now the only workaround is avoid use the problematic mode when `TextureRect` node is inside a container

![image](https://github.com/user-attachments/assets/27d09a6f-68eb-49e1-8de9-02605dfa9407)

**Comment by AThousandShips** [comment]
Thank you for reporting, this is indeed a known issue, we prefer keeping things in one place so merging with:
* https://github.com/godotengine/godot/issues/73071

Thank you for reporting, see there for more details
