### ISSUE TITLE
"Cannot open file" error being produced when exporting with web template.

### ISSUE THREAD

**Issue by girdenis-p** [godotengine/godot#99151]
### Tested versions

- Reproducible in 2ac562cdf8 and later
- Not reproducible in 4.4.dev4

### System information

Ubuntu 24.04.1 LTS - Firefox 132.0.1 (64-bit)

### Issue description

After building a template with `scons platform=web target=template_debug` and exporting to web. The game errors with "Cannot open file {insert main scene here}".

### Steps to reproduce

1. Open any project
2. Export to web using build made using `scons platform=web target=template_debug`
3. Run export in browser

### Minimal reproduction project (MRP)

N/A

**Comment by bruvzg** [comment]
Not specific to the web export, all exports seem to be broken (fail to load main scene).

```
ERROR: Cannot open file 'res://test.tscn'.
   at: load (scene/resources/resource_format_text.cpp:1389)
ERROR: Resource file not found: res://test.tscn (expected type: )
   at: _load (core/io/resource_loader.cpp:332)
ERROR: Failed loading scene: res://test.tscn.
   at: start (main/main.cpp:4203)
```

Bisects to 2ac562cdf8366876381902a0667fec704e357495
