### ISSUE TITLE
Right-click menu missing items when Asset Library feature is disabled

### ISSUE THREAD

**Issue by NickWaanders** [godotengine/godot#99153]
### Tested versions

Found and tested Godot v4.4-dev4_mono_win64

### System information

Godot v4.4.dev4.mono - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 32.0.15.6590) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 threads)

### Issue description

Right click menu is missing many items, such as  `Add Child Node...`. This appears to happen if you disable the Asset Library feature in `Manage Editor Features...`

### Steps to reproduce

- Create a new scene in Godot v4.4 dev 4, choose any type of root node. 
- Select `Editor>Manage Editor Features...` and create a new profile. 
- In the list of features, disable 'Asset Library' 
- Close the window and try to add a child node to the existing scene root-node.
- Notice that right clicking the node opens up a popup menu that is missing many options, 'Add Child Node...' being one of them. 

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Thank you for reporting, this has been reported and solved, see:
* https://github.com/godotengine/godot/issues/98981
