### ISSUE TITLE
Smearing border at ogv playback

### ISSUE THREAD

**Issue by andreas-volz** [godotengine/godot#99154]
### Tested versions

v4.3.stable.official [77dcf97d8]

### System information

Linux Mint 21 (Vanessa) - X11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (nvidia; 535.183.01) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

I convert a video file to ogv and play in a godot VideoStreamPlayer. It seems to work, but the borders of the video are smearing at the border. It may be a encoder specific issue as I don't have this problem with other videos.

### Steps to reproduce

ffmpeg -y -i <file.smk> -codec:v libtheora -qscale:v 31 -codec:a libvorbis -qscale:a 15 -pix_fmt yuv420p <out.ogv>

### Minimal reproduction project (MRP)

only the video. just put into a new project and load into a VideoStreamPlayer
[nlcfid00.ogv.zip](https://github.com/user-attachments/files/17724277/nlcfid00.ogv.zip)

screenshot broken in Godot:
![image](https://github.com/user-attachments/assets/431d353f-dd1e-4b4a-96c5-571c2342ad24)

screenshot ok in video player application:
![image](https://github.com/user-attachments/assets/eff55538-5f59-4bbd-bf19-9d7dc292079c)

I made more research and found two things:
1) it seems the minimal automatic detected size in VideoStreamPlayer is 64x64 (real video size is 60x56).
2) even if I encode and scale a (similar) video it detects wrong size: fmpeg -y -i tscfid02.smk -vf scale=120:112 -codec:v libtheora -codec:a libvorbis -pix_fmt yuv420p tscfid02.ogv
godot size detection is 128x112.

**Comment by andreas-volz** [comment]
I would start to search at this place:
https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/modules/theora/video_stream_theora.cpp#L342

		int w;
		int h;
		w = ((ti.pic_x + ti.frame_width + 1) & ~1) - (ti.pic_x & ~1);
		h = ((ti.pic_y + ti.frame_height + 1) & ~1) - (ti.pic_y & ~1);
		size.x = w;
		size.y = h;
		
But I've no setup for compiling and debugging Godot. I hope someone else with more knowledge starts with debugging until I find the time to setup a workspace.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/62752.
