### ISSUE TITLE
Unshaded models aren't sorted correctly.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#9917]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 3.0 Alpha 1

**Issue description:**
If a material is set to unshaded it will not sort correctly. Here are some screenshots.
The 3D Platformer demo:
![](http://i.imgur.com/J787MWR.png)

My own model:
![](http://i.imgur.com/W3Qsxv4.png)

What the model looks like with shading, being rendered correctly:
![](http://i.imgur.com/yPlS8A3.png)

While testing I noticed that the issue with unshaded materials is the same problem that the "On Top" option has, I don't know how related this is:
![](http://i.imgur.com/H4xuKIM.png)

**Steps to reproduce:**
The materials of the player and enemies in the 3D platformer demo can be set to unshaded to reproduce this effect.

**Comment by reduz** [comment]
oh yeah.. seen this
