### ISSUE TITLE
Expose the asset library URLs property from editor settings

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#99175]
### Tested versions

4.3

### System information

win10

### Issue description

Trying to make an addon to support a custom asset store and I want to use godot's built in interface for this. unfortunately there are some problems. I am unable to use the property to add or remove the link. I must set the dictionary manually in the editor.

![image](https://github.com/user-attachments/assets/93a863ce-add1-4bcc-a6d7-26fa1232c334)

### Steps to reproduce

open editor settings, go to Asset Library.

the EditorSettings class does not have this exposed.

### Minimal reproduction project (MRP)

n/a

**Comment by Calinou** [comment]
> the EditorSettings class does not have this exposed.

It does:

```gdscript
EditorSettings.set_setting("asset_library/available_urls", dictionary)
```

You must set the entire dictionary at once, so retrieve it first using `EditorSettings.get_setting()`.

**Comment by yankscally** [comment]
> > the EditorSettings class does not have this exposed.
> 
> It does:
> 
> ```gdscript
> EditorSettings.set_setting("asset_library/available_urls", dictionary)
> ```
> 
> You must set the entire dictionary at once, so retrieve it first using `EditorSettings.get_setting()`, modify it and set the setting to the new copy of the dictionary.

you are right, it does work, thank you!
