### ISSUE TITLE
Issues with programmatically adding custom URLs to the Asset Library

### ISSUE THREAD

**Issue by yankscally** [godotengine/godot#99179]
### Tested versions

4.3

### System information

win10

### Issue description

when disabling the assetlib, it doesn't work as expected. I haven't tested the others.

### Steps to reproduce

it says the AssetLib tab should disappear if I do this:

```swift
@tool
extends EditorPlugin

func _enter_tree():
	var profile = EditorFeatureProfile.new()
	profile.set_disable_feature(EditorFeatureProfile.FEATURE_ASSET_LIB, true)
```

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
You haven't applied the feature, you're just creating one, not using it

**Comment by yankscally** [comment]
> You haven't applied the feature, you're just creating one, not using it, see [`EditorInterface.set_current_editor_profile`](https://docs.godotengine.org/en/stable/classes/class_editorinterface.html#class-editorinterface-method-set-current-feature-profile)

Right, I see now.


I was just attempting something like this until I read your edit, and then I see what you mean. I was actually doing this as a hack to refresh the assetlib. when you add a new URL to it, it doesn't update in this dropdown, even when reloading


```swift
@tool
extends EditorPlugin

var icosa_endpoint = {"icosa-gallery.com" : "https://icosa-gallery.com/api/v1/assets"}

func add_endpoint():
	var settings = EditorInterface.get_editor_settings()
	var urls = settings.get_setting("asset_library/available_urls")
	if not (icosa_endpoint.keys()[0] in urls):
		urls[icosa_endpoint.keys()[0]] = icosa_endpoint.values()[0]
		settings.set_setting("asset_library/available_urls", urls)

func remove_endpoint():
	var settings = EditorInterface.get_editor_settings()
	var urls = settings.get_setting("asset_library/available_urls")
	if icosa_endpoint.keys()[0] in urls:
		urls.erase(icosa_endpoint.keys()[0])
		settings.set_setting("asset_library/available_urls", urls)
```

To make this issue worthwhile, I will change the name to "no way to programmatically add Asset Library URL".

It's not worth trying to re-use current the asset library. I will just make a new interface.

**Comment by AThousandShips** [comment]
Please open a new issue report outlining your issue
