### ISSUE TITLE
AudioStreamInteractive transition `fade_beats` is an integer while being handled as float everywhere

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#99172]
### Tested versions

- 4.4.dev [277cb68e1a743efb14a8b8be1e63e9fba14bc6dc]

### System information

Godot v4.4.dev (277cb68e1a743efb14a8b8be1e63e9fba14bc6dc) - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:35 +0000 on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated Intel(R) Arc(tm) A770 Graphics (DG2) - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 threads)

### Issue description

- `fade_beats` is stored as `int` internally [here](https://github.com/godotengine/godot/blob/277cb68e1a743efb14a8b8be1e63e9fba14bc6dc/modules/interactive_music/audio_stream_interactive.h#L103)
- In [`add_transition`](https://github.com/godotengine/godot/blob/277cb68e1a743efb14a8b8be1e63e9fba14bc6dc/modules/interactive_music/audio_stream_interactive.cpp#L249) and the [editor plugin](https://github.com/godotengine/godot/blob/277cb68e1a743efb14a8b8be1e63e9fba14bc6dc/modules/interactive_music/editor/audio_stream_interactive_editor_plugin.cpp#L68) it's handled as `float`.
- The GUI input in the editor plugin also allows entering decimal values, which get silently dropped.

### Steps to reproduce

- Create an `AudioStreamInteractive` and try to add a transition with e.g. 1.5 beats of transition time. The 1.5 get truncated to 1. You notice when reopening the transition dialog.

### Minimal reproduction project (MRP)

N/A

**Comment by PhairZ** [comment]
should we assume that fade_beats can only take whole beats?

**Comment by timoschwarzer** [comment]
From what I can see [here](https://github.com/godotengine/godot/blob/76fa7b291455a8ba24c50005072ebdb58f8a5984/modules/interactive_music/audio_stream_interactive.cpp#L716) that is not the case. Float values should work just fine.

**Comment by PhairZ** [comment]
Well, I checked it and fixing it is as easy as changing the fade_beats in [here](https://github.com/godotengine/godot/blob/277cb68e1a743efb14a8b8be1e63e9fba14bc6dc/modules/interactive_music/audio_stream_interactive.h#L103) to float

**Comment by timoschwarzer** [comment]
@PhairZ do you want to open a PR or should I do it?

**Comment by PhairZ** [comment]
I'd be happy to open it. @timoschwarzer
