### ISSUE TITLE
Godot Compatibility Renderer textures appear significantly brighter than intended

### ISSUE THREAD

**Issue by UnderGamer05** [godotengine/godot#99174]
### Tested versions

Godot 4.x+

### System information

Godot v4.4.dev4 - Android - Single-window, 1 monitor - Vulkan (Mobile) - integrated Adreno (TM) 610 -  (8 threads)

### Issue description

the textures appear significantly brighter than intended. This brightness increase affects the appearance of the model, making it look washed out and lacking depth. The brightness issue may be linked to how lighting and material reflections are handled differently in compatibility mode.

Mobile Renderer:
![Screenshot_20241113_204649](https://github.com/user-attachments/assets/cd12c7af-d14a-44fe-a2d4-4ab5de5bcdf5)
Compatibility Renderer:
![Screenshot_20241113_204610](https://github.com/user-attachments/assets/89397303-28a5-4d36-948b-d3a35c949df8)

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/17734513/test.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/90259.
