### ISSUE TITLE
Changing the pitch gives the wrong effect (Godot 3.0 alpha1)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#9918]
**Operating system or device - Godot version:**
Ubuntu 16.04, Godot 3.0 alpha1

**Steps to reproduce:**
Add audio effect PitchShift
Change the value slightly (for example 1.2)
Listen

**Link to minimal example project:**
[Bug pitch shift.zip](https://github.com/godotengine/godot/files/1180227/Bug.pitch.shift.zip)

**Comment by Jerome67000** [comment]
Hi, can you explain the problem a little bit more please ?

for information (maybe a must create a new issue for that) :
_PitchShift scale is a bit strange for now : 1 = no change, 0.01 = one octave lower, 2 = one octave higher.
So you can pitch from -1 to +16 octave that is crazy. For me a scale wich 1 unit = 1 semi tone is a greater solution, -12 = one octave lower, +12 = one octave higher_

**Comment by reduz** [comment]
I am wondering whether we should change it to semitones

**Comment by DimaKiva** [comment]
There's nothing to suggest about tone.

About buses. In version 2.x, pitch was tied to every player (instance), and in my opinion it was more convenient and quicker to change the tone of a particular character, car, blast ... No extra body.

**Comment by reduz** [comment]
Closing this because it seems like a misunderstanding. PitchShift (just a regular pitch shifter) is not the same kind of effect of sampler player. What needs to be added eventually is some pitch scale parameter to AudioStreamPlayer eventually. Please open a separate issue about this
