### ISSUE TITLE
Sky is not rendering for right eye in VR (4.4.dev4)

### ISSUE THREAD

**Issue by funkysandwich** [godotengine/godot#99193]
### Tested versions

Not reproducible in v4.3.stable.mono.official [77dcf97d8], v4.4.dev1.mono.official [28a72fa43], v4.4.dev3.mono.official [f4af8201b]
Producible in v4.4.dev4.mono.official [36e6207bb]
I was not able to get VR to work at all on v4.4.dev2.mono.official [97ef3c837], it would hang on the Godot splash. 

### System information

Windows 11 - Godot 4.4 dev4 mono - Vulkan (Forward+) - AMD Ryzen 7 3800x - NVIDIA RTX 3070 Ti with driver 566.03

### Issue description

The sky is not visible for the right eye in VR. (4.4.dev4)
![Screenshot](https://github.com/user-attachments/assets/a6c17090-13d7-48a7-8159-4aa479cb708d)
The sky should be visible for both eyes. (4.4.dev3)
![Screenshot](https://github.com/user-attachments/assets/63fa8a0b-1cb3-4bbd-94e5-0927ad5f271b)

### Steps to reproduce

1. Create and open a new project
2. Enable OpenXR and XR shaders
3. Create a new scene with a WorldEnvironment with Background set to Sky and set a new material for the sky. I used a PhysicalSkyMaterial.
4. Create an XROrigin node, and a XRCamera as a child
5. Attach a script to the scene root that enables XR for the viewport
```gdscript
extends Node3D
func _ready() -> void:
	get_viewport().use_xr = true
```
6. Run the project

### Minimal reproduction project (MRP)

[skyrepro.zip](https://github.com/user-attachments/files/17738256/skyrepro.zip)

**Comment by BastiaanOlij** [comment]
I'll have a look as soon as I can, if someone has time to do a bisect in the meanwhile that would help greatly. This must be a pretty recent break.

I can reproduce this on master with my stereo test project:
![image](https://github.com/user-attachments/assets/92329839-45a5-4848-ae9d-f8548dfd0709)

So you need neither Mono nor XR hardware to test this. This is the test project I used:
[teststereo.zip](https://github.com/user-attachments/files/17813680/teststereo.zip)

**Comment by BastiaanOlij** [comment]
Did manage to do a bisect, it points to this as the culprit: https://github.com/godotengine/godot/pull/86138
