### ISSUE TITLE
Ability to add Metadata via Node Menu

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#9919]
Currently, Metadata can only be added via scripts via set_meta()
It would be a huge enhancement for usability if Metadata could be set via the Node Menu simlarly to Groups.
![node menu groups](https://user-images.githubusercontent.com/20967774/28676186-e8c1651c-72e1-11e7-8e3b-289f9062de6a.png)

**Comment by vnen** [comment]
Duplicate of #5433.
