### ISSUE TITLE
Cannot build with `builtin_miniupnpc=no`

### ISSUE THREAD

**Issue by darksylinc** [godotengine/godot#99196]
### Tested versions

Latest master

### System information

Godot v4.4.dev (-) - Ubuntu 24.04.1 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Mobile) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

PR #99171 breaks when `builtin_miniupnpc=yes` on Ubuntu 24.04 LTS

This is because:

```bash
pkg-config miniupnpc --cflags --libs
-lminiupnpc
```

Returns those flags, but Godot does:

```cpp
#include <miniupnpc.h>
#include <upnpcommands.h>
// etc
```

However the official package expects the following:

```cpp
#include <miniupnpc/miniupnpc.h>
#include <miniupnpc/upnpcommands.h>
```

Before the PR, it compiled fine because Godot explicitly added:

```py
env.Prepend(CPPPATH=["/usr/include/miniupnpc"])
```

### Steps to reproduce

Compile with:

```bash
pyston-scons platform=linuxbsd builtin_embree=yes builtin_enet=no builtin_freetype=yes builtin_graphite=yes builtin_harfbuzz=yes builtin_libogg=no builtin_libpng=yes builtin_libtheora=no builtin_libvorbis=no builtin_libwebp=no builtin_mbedtls=no builtin_miniupnpc=no builtin_pcre2=no builtin_zlib=yes builtin_zstd=no linker=mold optimize=none debug_symbols=True tests=False dev_mode=True dev_build=True use_llvm=yes use_lld=yes  opengl3=no openxr=no -j 24
```

### Minimal reproduction project (MRP)

N / A

**Comment by Calinou** [comment]
I can confirm this on Fedora 41 (I was able to build with `builtin_minipupnpc=no` previously).
