### ISSUE TITLE
GUI Button cannot be pressed if keyboard is pressed, or for a second after

### ISSUE THREAD

**Issue by 3l3m01** [godotengine/godot#99202]
### Tested versions

- Reproducible in 4.1.1-stable, 4.3-stable and 4.4-dev4

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics (Intel Corporation; 31.0.101.2114) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

After pressing any keyboard button, even ones that are not bound to actions, GUI Buttons cannot be pressed and remain inactive for about another second. 
This may be intended behavior, but I found nothing in the documentation to indicate it.
Modifier keys such as shift work fine.
Mouse enter events work as well.
Tried to set it to the right mouse button but got the same result.

### Steps to reproduce

- Create a new project
- Add a Button.
- Connect the pressed signal to a function that prints a message
- Start the project
- Press a button, such as a number (Modifier keys such as Shift do not produce this behavior)
- Try pressing the button
- The function will not be called while the button is pressed, or for some time after.

### Minimal reproduction project (MRP)

[GUIButtonTest.zip](https://github.com/user-attachments/files/17744137/GUIButtonTest.zip)

**Comment by PhairZ** [comment]
Had no issue trying to reproduce this in v4.4.dev.custom_build [277cb68e1]. Try making a MRP and check if its a problem with your project.godot.

**Comment by 3l3m01** [comment]
Just found out it's not Godot-specific, and my laptop is just going crazy, doing the same in other programs as well. At least it's not me who is going crazy...
Sorry for the false alarm.

**Comment by 3l3m01** [comment]
For anyone who is the same kind of dumb as me: It was Windows's palmcheck feature.
