### ISSUE TITLE
Image loading is broken in editor

### ISSUE THREAD

**Issue by syntaxerror247** [godotengine/godot#99221]
### Tested versions

- Reproducible in master: v4.4.dev.custom_build [76fa7b291]
- Not reproducible in v4.4.dev4

### System information

Windows 11

### Issue description

I am cannot load images in editor.
I tried setting adaptive icons in android export and boot splash in project setting, both failed with similar error: `load_image: Error opening file 'uid://bjaelxrg45jgj'`

### Steps to reproduce

- Go to project settings
- Set a boot splash image (clear it if already set and select again)
- Run your project and see error in debugger.

### Minimal reproduction project (MRP)

N/A

**Comment by syntaxerror247** [comment]
After setting icons (loading icons) in master build, I opened same project in dev4 and it is showing `uid` insted of file path.
![image](https://github.com/user-attachments/assets/4d23087b-4c66-45ef-bcbf-b80a43f12dc9)

**Comment by KoBeWi** [comment]
Likely coming from #97912

**Comment by syntaxerror247** [comment]
Thank you for referencing the PR—it’s definitely due to that. I also wanted to add that when I set the image in dev4 and then switch to the current master build, it works without errors.

I hope this gets fixed soon since my upcomming PR, which requires loading images in the export settings, is affected by this. For now, as a workaround, I’m currently using dev4 to load images 😅 and then continuing my work or tests in the master build.

**Comment by KoBeWi** [comment]
I'm already working on a fix.

**Comment by syntaxerror247** [comment]
@KoBeWi My issue is still not resolved. I rebuilt the editor and even tried downloading the editor from your PR, but I’m still encountering the same error. (I was quite busy yesterday, so didn't got time to test locally)

![image](https://github.com/user-attachments/assets/e0e3ff93-913b-41d2-a92d-201ac4f75c4f)

**Comment by akien-mga** [comment]
Did you try to re-select the boot splash image in the settings? Your project settings probably have the uid path already saved from the previous buggy state.

**Comment by syntaxerror247** [comment]
> Did you try to re-select the boot splash image in the settings? Your project settings probably have the uid path already saved from the previous buggy state.

Yes I did, I even tried with a fresh project, still same error.
