### ISSUE TITLE
ReloadSceneFromPath not reloading the scene

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#99232]
### Tested versions

Godot v4.3.stable.mono 

### System information

Linux Mint 21 (Vanessa) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti - AMD FX(tm)-9590 Eight-Core Processor (8 Threads)

### Issue description

editorInterface.ReloadSceneFromPath(pathToTscn); from script does not reload the scene in the editor as manually clicking Scene - Reload Saved Scene does.

### Steps to reproduce

Use provided mrp:

To use it build from source, then enable the addon in Project Settings - Plugins. Then open the Scene1 in the Scenes folder.  
When you press the button in the addons panel the root node in the open scene is renamed by replacing the root nodes name in the tscn file. The change only shows when Scene - Reload Saved Scene is pressed, the tab is closed and the tscn reopened or if Godot notices that the file has changed and opens the dialog to keep or overwrite the scene file.  

If you want to redo the action unpack and overwrite the Scene1 from the Scene1.tscn bkp.zip archive.

### Minimal reproduction project (MRP)

[reloadscenemrp.zip](https://github.com/user-attachments/files/17749618/reloadscenemrp.zip)

**Comment by raulsntos** [comment]
This is not exclusive to C#, I've been able to reproduce after porting the MRP to GDScript.

[reloadscenemrp_gd.zip](https://github.com/user-attachments/files/17757130/reloadscenemrp_gd.zip)

**Comment by amarsero** [comment]
I tested the MRP and `EditorInterface::reload_scene` expects a scene file path (`res://Scenes/Scene1.tscn`), not an absolute path (`C:/Projects/reloadscenemrp/Scenes/Scene1.tscn`).
In the MRP, if you use the `sceneFilePath` you already have from `node.GetTree().EditedSceneRoot.SceneFilePath` it works.

**Comment by BrahRah** [comment]
I've tested it too and can confirm that when using editorInterface.ReloadSceneFromPath with a  res:// path instead of absolute path the reload works.
