### ISSUE TITLE
Empty type option in Shader Globals editor

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#99233]
### Tested versions

- Reproducible: 4.4.dev3, 4.4.dev4, master[76fa7b291455a8ba24c50005072ebdb58f8a5984]
- Not reproducible: 4.4.dev2

### System information

Arch Linux

### Issue description

In the Shader Globals editor, the uniform type dropdown has a new option with empty description. Using it adds a nil editor.

![image](https://github.com/user-attachments/assets/d9cddd46-8c9a-46ba-bf9e-b347e47a2f92)

Probably since #96982.

### Steps to reproduce

Open any project and go to Project Settings > Globals > Shader Globals, then click the Type dropdown.

### Minimal reproduction project (MRP)

N/A

**Comment by JekSun97** [comment]
I can confirm that this happens on 4.4 dev5
