### ISSUE TITLE
Raycast2D not colliding with tile

### ISSUE THREAD

**Issue by creutzerb** [godotengine/godot#9923]
**Operating system or device - Godot version:**
Microsoft Windows Education Version	10.0.14393
Godot_v2.1.4-beta_20170625_win64

**Issue description:**

`is_colliding()` method of Raycast2D returns false when a tile is in a TileMap

**Steps to reproduce:**

I made a tileset following this tutorial : [http://docs.godotengine.org/en/stable/learning/features/2d/using_tilemaps.html](url) 
The raycast keeps on returning false when it should be hitting a tile from the tilemap, but gives the expected result when the tile is directly in the scene.

**Link to minimal example project:**

[raycast2D_tilemap.zip](https://github.com/godotengine/godot/files/1180643/raycast2D_tilemap.zip)
I made a tile, and put one in the tilemap using a tileset, and the other directly in the scene.
You can swap the direction of the raycast between the tiles by pressing space. (enable visible collision shapes in the debug option to see where the raycast is pointing)
The console is printing the result of `is_colliding()` in  `_fixed_process`.

**Comment by RandomShaper** [comment]
The problem is that the `TileMap`'s `collision/layers` doesn't include the layer 2 (bit 1), which is the only the `RayCast2D` is setup to collide against.

If you change that, you'll get a positive collision result on the `TileMap`.

**Comment by RandomShaper** [comment]
Anyway, let me applaud your conduct about this issue: first asking in Q&A in case it was something solvable there and then raising a bug report with a nice self-contained test project.

**Comment by creutzerb** [comment]
Thanks, I still kinda feel bad for not solving this problem myself...

I did not expect to find collision layers in the TileMap. I do not know what they can be useful for since the collision layers are already specified in the tiles themselves. If this was indeed a useless feature, i would suggest to remove them, but I may be missing something.

**Comment by RandomShaper** [comment]
Well, only a subset of the individual tile's properties are exported to the `TileSet` and, if I'm not mistaken, collision layer/mask doesn't belong to them.

So you have to set them globally for the whole `TileMap`.

**Comment by creutzerb** [comment]
Ok, good to know, thank you.
