### ISSUE TITLE
Recent input change breaks existing input maps

### ISSUE THREAD

**Issue by Gaktan** [godotengine/godot#99243]
### Tested versions

Reproducible in v4.4.dev.custom_build [76fa7b291]
Not reproducible in Reproducible in v4.4.dev.custom_build [0a4aedb36]

### System information

Windows 10 - Vulkan

### Issue description

Found this bug after updating my godot fork, I didn't investigate what change caused this.

Previously set input events had a "-1" device value in my project. I don't know if it was previously an expected behaviour or not. But the new behaviour expects the device value to be >= 0.

For example, an input event define in my project settings as:
```
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":84,"physical_keycode":0,"key_label":0,"unicode":116,"location":0,"echo":false,"script":null)
```

Existing values should be converted to the new expected value if possible. Otherwise users must be warned to make the manual change.

### Steps to reproduce

Add the following `skip` action into your project:
```
[input]

skip={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":84,"physical_keycode":0,"key_label":0,"unicode":116,"location":0,"echo":false,"script":null)
]
}
```

Catch the action in your code using `Input.is_action_pressed("skip")`
Attempt to trigger the action by pressing 'T'.
Notice is_action_pressed never returns true.

### Minimal reproduction project (MRP)

N/A

**Comment by Meorge** [comment]
Sorry I don't have more concrete info to add here, but I did want to mention that I think this bug (or a very similar one) caught me when I tried running a 4.4-dev3 project on 4.4-dev4. I think I remember in my case it set the device ID for my input map to `-3`? Luckily, I was able to revert the changes using Git, but it definitely still got me off guard.

**Comment by Jarwhal3** [comment]
I have this issue as well, it updated my 4.3 project input maps from -1 to -3. It's not just a project upgrade issue though.

I just created a new, empty 4.4 dev 3 project and added an input action to it, and it set the device to -3 instead of the previously expected -1.

![image](https://github.com/user-attachments/assets/a11c2ea9-d8b7-467b-8b27-dafc94f32cc5)

**Comment by Meorge** [comment]
The change from -1 to -3 is due to this PR, I discovered: https://github.com/godotengine/godot/pull/97707

I haven't had the chance to experiment much with how this impacts the actual device usability though
