### ISSUE TITLE
text not centered in godot3 gui button

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#9927]
**Operating system or device - Godot version:**
Windows 7, Godot 3 alpha1

**Issue description:**
Text in Godot3 gui button not centered. Screenshot compare Godot2 vs. Godot3.
![image](https://user-images.githubusercontent.com/10463138/28686648-3267da64-730c-11e7-92e5-6ebfb5cb4c48.png)

**Comment by akien-mga** [comment]
cc @djrm @toger5 @volzhs
