### ISSUE TITLE
Partial regression: missing audio-related signals.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#9928]
**Operating system or device - Godot version:**
Ubuntu 17.04 64-bit. Godot version 3.0 pull 3c53b35.

**Issue description:**
AudioStreamPlayer lacks signals related to audio files starting, stopping,etc. 2.1.x had at least a signal for StreamPlayer which indicated when its stream finished. Both 2D and 3D versions of AudioStreamPlayer also lack any such signals.

Names could be something like "stream_started", "stream_looped" etc.

**Comment by vonflyhighace2** [comment]
Also There's no option to loop an audio file. AudioStreamSample has a loop begin and a loop end but those does nothing like what you would believe it should.

**Comment by reduz** [comment]
Loop is an import option

On Jul 28, 2017 2:14 PM, "vonflyhighace2" <notifications@github.com> wrote:

Also There's no option to loop an audio file. AudioStreamSample has a loop
begin and a loop end but those does nothing like what you would believe it
should.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/9928#issuecomment-318711188>,
or mute the thread

**Comment by vonflyhighace2** [comment]
That's a weird way to present the option. Does that mean you're limited to the choice at import time. Or can we toggles this during runtime?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vonflyhighace2** [comment]
I say it's weird because Godot automatically imports files once they are in the project folder meaning not everyone will check how things are imported especially audio files.

**Comment by vonflyhighace2** [comment]
Did some more playing around with the 3D audio Node. Looks like .wav audio samples can't be set to loop? it automatically disables looping at run-time. Not sure if this is intentional or a bug.

**Comment by Sslaxx** [comment]
@vonflyhighace2 - Stuff about looping/not looping should be made into its own issue.

**Comment by Sslaxx** [comment]
Out of curiosity, is there (or would it be useful to have) a tracker for listing which node types should have signals exposed but currently don't?

**Comment by reduz** [comment]
@Sslaxx looping can be changed via code, but the default setting is changed via import. I don't think this is a problem.

**Comment by Sslaxx** [comment]
You mean @vonflyhighace2.

It would be nice to have signals for starting playing, pausing/resuming and looping though. It'd allow more flexibility than the old signals (or the "finished" signal implemented currently).
