### ISSUE TITLE
Inspector tooltips are blinking

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#99287]
### Tested versions

4.4 dev5
Does not occur in dev4.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/user-attachments/assets/c6d04223-47cc-478f-afef-09e9586b7598

### Steps to reproduce

Hover property in the inspector.

### Minimal reproduction project (MRP)

N/A

**Comment by Radivarig** [comment]
Just to note that for me and another user #99509 it works fine on dev-4 but not on dev-5.

**Comment by KoBeWi** [comment]
Re-tested with dev4 and the issue indeed does not occur. I mistakenly tested with a custom build, sorry.

**Comment by kitbdev** [comment]
- It is fixed when I try reverting https://github.com/godotengine/godot/pull/95972

Probably Windows only.

- Seems to be fixed by https://github.com/godotengine/godot/pull/95044

**Comment by passivestar** [comment]
> Probably Windows only.

sometimes it'd blink _one_ time on mac. probably just because of micro mouse movement, maybe there could be some small movement delta threshold before the tooltip disappears. nothing remotely similar to what windows reports show though, so not the same issue
