### ISSUE TITLE
Cannot save 3D Scenes due to Alert: Requested file format unknown. Both Collada and Wavefront meshes.

### ISSUE THREAD

**Issue by NoGodDamnName** [godotengine/godot#9929]
**Operating system or device - Godot version:**
Godot 3.0 latest master build: 246b574
Manjaro Linux 17.0.2 64-bit

**Issue description:**
Upon saving a 3D Scene with emmision materials, An alert is displayed, and the scene cannot be saved.

**Steps to reproduce:**
Simply create a 3D scene and try to save it. Also happens when running the game.
![deepinscreenshot_select-area_20170727163035](https://user-images.githubusercontent.com/28677151/28691939-9f5ccf0a-72ec-11e7-9189-3baefa6f83fc.png)

**Comment by Sslaxx** [comment]
To be clear, the scene saves if you remove emission materials? Does the command line/terminal display anything?

**Comment by NoGodDamnName** [comment]
There are 2 (but 3) error reports. These errors appear when the game is run, but they do not popup when saving. When running the game the same Alert dialog is shown, and nothing is displayed this time. Even when there is a camera in the scene.

If this helps, my GPU is NVIDIA Geforce 660 TI 3GB VRAM.
![deepinscreenshot_select-area_20170727170658](https://user-images.githubusercontent.com/28677151/28692322-0e7654be-72ee-11e7-8990-79eac60fdb89.png)

**Comment by NoGodDamnName** [comment]
A little update: These errors above are most likely not related to the actual issue experienced with 3D scenes. Even running a 2D project gives me the same error reports.

**Comment by bojidar-bg** [comment]
BTW, how are you trying to save the scene? Godot uses an internal format (.tscn or .scn) for saving scenes, and can't save to .dae (thus your error). Are you trying to overwrite an imported scene?

**Comment by NoGodDamnName** [comment]
It looks like it was the problem. Using "Saving As..." to save it as .tscn and .scn works. I have the habit of doing Ctrl+S. So it could mean that Godot is indeed trying to overwrite the .dae/.obj scene. Yet i always expect for my imported scenes to be saved or, attempt to be saved, as a Godot .tscn/.scn/.res file.

If you think this is normal, feel free to close the issue.
My bad :/

**Comment by Sslaxx** [comment]
Could do with it defaulting to .tscn/.tres then, or some notification that it cannot be saved as .dae.

**Comment by reduz** [comment]
This is not a bug, when you opened the scene to edit it you were warned that you would not be able to save it.

**Comment by reduz** [comment]
If this was not the case, please reopen the issue.. but .dae scenes can not be saved, as they are automatically reimported.
