### ISSUE TITLE
Distance fog isn't world-space

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#9933]
Godot 3.0 alpha1 official
Windows 10 64 bits

In Godot 2.1.3, distance fog was distance based, so when looking around it didn't change the color of a given object seen far away as long as you stay where you are, no matter where you look at.

In 3.0 objects in fog suddenly become more visible depending on where you look at. It looks a bit messy on some fog setups that are usually fine in distance-based versions:

https://www.youtube.com/watch?v=TwkdifkfbyE&feature=youtu.be

**Comment by reduz** [comment]
this is fixed now, closing
