### ISSUE TITLE
Color picker in `ColorRect` node flickers rapidly until the color wheel is clicked for the first time.

### ISSUE THREAD

**Issue by Henry-DorsettCase** [godotengine/godot#99368]
### Tested versions

Issue can be reproduced in Godot v4.3.stable. I also tested Godot 4.4 dev snapshot 4 and 4.2.2 stable; the issue is also present in both of those releases.

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti SUPER (nvidia; 550.120) - Intel(R) Core(TM) i9-14900KF (32 Threads)

### Issue description

When I use the color picker to select a color from the `ColorRect`' s color wheel, the color flickers rapidly. Even when I don't move the mouse at all, the flashing persists. Clicking once on the wheel causes all flickering the stop.

Here's a video I recorded (in v4.3) that demonstrates the behavior. (**Warning: flashing lights.**)

[Screencast from 2024-11-17 19-24-34.webm](https://github.com/user-attachments/assets/e6924267-625e-40e8-962d-39350bb9709c)

Around fifteen seconds into the video, I clicked on the wheel. This put an end to the flickering.

### Steps to reproduce

1. Create a new project; select Forward+.
2. Create a new scene and add a `ColorRect` node.
3. In the inspector, open the color wheel.
4. Click on the color picker button.
5. Place the mouse anywhere on the wheel. This should cause flickering.
6. Optional: click once anywhere on the wheel to make the flickering stop.

### Minimal reproduction project (MRP)

[color_picker_bug.zip](https://github.com/user-attachments/files/17791970/color_picker_bug.zip)

**Comment by syntaxerror247** [comment]
Color picker button is not used like that. It is used to pick color from the screen, not from "wheel". You can directly select color from color wheel.
