### ISSUE TITLE
Can't set a custom theme through editor settings

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#99375]
### Tested versions

v4.4.dev.custom_build [5efd124ca]

### System information

Godot v4.4.dev (5efd124ca) - macOS 15.1.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

Godot is now trying to store the theme path as a UID but it should probably always be an absolute path (?)

Trying to select a theme fails:

<img width="748" alt="1" src="https://github.com/user-attachments/assets/5f20eafd-804a-4bad-a080-a490d1100754"><br>
<img width="528" alt="2" src="https://github.com/user-attachments/assets/33e16a2f-1dc1-4e59-bc80-3ed5f3752911">

I missed this bug before because when I work on a theme I have it symlinked in the current project, and when the theme is in the project it has no problem loading it (it displays the relative `res://` path in that case)

### Steps to reproduce

Select any theme in editor settings (Interface -> Theme -> Custom Theme). You can use [mine](https://github.com/passivestar/godot-minimal-theme/releases/tag/1.6.0) if you don't have any

### Minimal reproduction project (MRP)

N/A

**Comment by adamscott** [comment]
cc. @KoBeWi

**Comment by adamscott** [comment]
Surely relates to #99286
