### ISSUE TITLE
Project crashes after not having opened it for some time

### ISSUE THREAD

**Issue by MaddyMurder** [godotengine/godot#99373]
### Tested versions

Happened in 4.2, still happens after upgrading 4.3.

### System information

Originally i was using windows 10, the issue now appears when using windows 11.

### Issue description

After not having opened my project in some time, it now crashes on startup. no log is produced and the backtrace appears useless.
[after running it with console.txt](https://github.com/user-attachments/files/17792700/after.running.it.with.console.txt)

### Steps to reproduce

Open the provided project in godot 4.3

### Minimal reproduction project (MRP)

[cloud-attempt-1.zip](https://github.com/user-attachments/files/17792699/cloud-attempt-1.zip)
the entire project is very simple and has barely anything, it was just a shader test. and i wouldnt know how to make the project any smaller while still having the issue

**Comment by justofisker** [comment]
Reproduced this in 4.3 release, but tested it on the latest commit in 4.3 branch and seemingly it has been fixed.

**Comment by akien-mga** [comment]
Closing then as already fixed by #95503, and that fix was already cherry-picked for 4.3.1. That version just needs to be released one day 🙃
