### ISSUE TITLE
huge speedup possible: meshes are regenerated unnecessarily when settings (eg radius) are set to their existing value

### ISSUE THREAD

**Issue by lighttroupe** [godotengine/godot#99414]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Ubuntu 22.04

### Issue description

Mesh (such as a Sphere) is regenerated, wasting work, when the result will be exactly the same.

### Steps to reproduce

Add this to a _process():
> mesh.radius = 0.5

(in a real-world app, the value is calculated every frame based on user settings, but when the value is not changing, it still rebuilds the mesh)

### Minimal reproduction project (MRP)

https://github.com/godotengine/godot/blob/fd4c29a189e53a1e085df5b9b9a05cac9351b3ef/scene/resources/3d/primitive_meshes.cpp#L1904

I'm wondering if a line like this would be appropriate:
> if is_equal_approx(radius, p_radius) { return }

Otherwise, the app has to do it in GDScript, which is much slower than C++, duplicated work across godot apps, etc.

I think this easy optimization should be added everywhere in Godot when changing a setting triggers heavy work.

If this is not implemented, then the docs should be updated to warn about the performance hit "even if setting to the same value".

**Comment by carsonetb** [comment]
I'd be interested in helping with this ... it seems like a very easy optimization. 

I could start working on a PR if you don't want to do it yourself, it seems like you've already found a lot of the source code.

**Comment by lighttroupe** [comment]
Please do go ahead!  I think all the mesh types could use this speedup.

I'm not sure the process in this project, doesn't anyone need to greenlight this?

I'm not sure if is_equal_approx is needed, but in the GDScript version (new_radius != mesh.radius) it IS needed, as the value you get back is slightly different than the value you set the previous frame (because floating point).

**Comment by carsonetb** [comment]
According to the [godot docs](https://docs.godotengine.org/en/stable/contributing/workflow/first_steps.html) anyone can submit a pull request ... I think the main process for creating one is someone should submit an issue, and the pull request fixes that issue.
