### ISSUE TITLE
No max function into documentation shading language

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#9942]
![error-max-fuction-name](https://user-images.githubusercontent.com/24534/28703077-1b1827ea-7327-11e7-8376-83ffc59a5ee1.png)

http://docs.godotengine.org/en/stable/learning/features/shading/shading_language.html

**Comment by akien-mga** [comment]
Please report documentation bugs on the documentation repository next time: https://github.com/godotengine/godot-docs

This was a simple typo, fixed by https://github.com/godotengine/godot-docs/commit/74758c3c3e4baf9ffa112cfa24649c4bb4e16634
