### ISSUE TITLE
Function draw_mesh() doesn't work

### ISSUE THREAD

**Issue by tntscreed** [godotengine/godot#99422]
### Tested versions

- Reproducible in: 3.6.stable, 4.2.2.stable, 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 Threads)

### Issue description

`draw_mesh` should be drawing a mesh to the screen. Instead, it throws errors.

When calling the function, the following error is thrown many times a second (in Godot 4 versions):
`mesh_get_surface_count: Parameter "mesh" is null.`
`<C++ Source>   servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp:632 @ mesh_get_surface_count()`

In Godot 3, the following is thrown:
`getornull: Condition "!id_map.has(p_rid.get_data())" is true. Returned: nullptr`
`<C++ Source>  ./core/rid.h:151 @ getornull()`

### Steps to reproduce

The following code attached to a plain Control node is enough to reproduce the issue. The last three lines work as expected, showcasing that the mesh is correct.

The code is for Godot 4. It works very similarly in 3.

Expected behaviour here is that the upper left half of the Control node is covered by a triangle with a margin.

```gdscript
extends Control

func _draw():
	var mesh = ArrayMesh.new()
	var mesh_vertices: PackedVector2Array = []
	
	var margin = 20
	
	mesh_vertices.append(Vector2(0 + margin, 0 + margin))
	mesh_vertices.append(Vector2(size.x - margin, 0 + margin))
	mesh_vertices.append(Vector2(0 + margin, size.y - margin))
	
	var mesh_data = []
	mesh_data.resize(ArrayMesh.ARRAY_MAX)
	mesh_data[ArrayMesh.ARRAY_VERTEX] = mesh_vertices
	
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, mesh_data)
		
	var texture2d = preload("res://icon.svg")
	draw_mesh(mesh, texture2d) # doesn't work
	
	
	#var mesh_instance = MeshInstance2D.new()
	#mesh_instance.mesh = mesh
	#add_child(mesh_instance) # works, though duplicates every time there's a redraw

```

### Minimal reproduction project (MRP)

The attached project is for 4.2.2.stable. After creating the project, a single Control node was added covering the screen, to which the script was attached.
[DrawMeshBug.zip](https://github.com/user-attachments/files/17813244/DrawMeshBug.zip)

**Comment by smix8** [comment]
The issue here is that you are creating a new Resource within the scope of a function so when the function is finished it deletes itself as a RefCounted object.

You need to store that Arraymesh somewhere. Functions like draw_mesh() will not store your resources and prevent them from b eing freed.

**Comment by copygirl** [comment]
Apologies for commenting on this old issue, but I had a question:
If `draw_mesh` uses the resource at a later point, why can't it increase the ref count until then?
