### ISSUE TITLE
deleting default_env.tres is not a good idea

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#9945]
**Operating system or device - Godot version:**
Windows 7, Godot 3 alpha1

**Issue description:**
Godot 3 alpha1 let me delete the **default_env.tres** file and spam the console with error messages.
**Suggestion:** Is it possible to automatically recreate it when missing?

I don't have tested if there is also the same problem with **default_bus_layout.tres**.
Deleting **icon.png** magically works. 😄

**Comment by eon-s** [comment]
Instead of recreate it, would not be better to just stop trying to use it? I mean, maybe you want to remove it.

**Comment by reduz** [comment]
@eon-s This is what happens already, but after restart when no longer found... so guess i have to figure out what the error spam is first
