### ISSUE TITLE
Texture Region Editor (for NinePatchRect) does not support undo / redo shortcuts

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#99470]
### Tested versions

4.3.stable
Master - Godot v4.4.dev (a0cd8f187)

### System information

Godot v4.4.dev (a0cd8f187) - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Laptop GPU (NVIDIA; 32.0.15.6103) - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 threads)

### Issue description

Nothing happens when pressing Ctrl + Z and Ctrl + Shift + Z in the Texture Region Editor

### Steps to reproduce

1. Create a scene with a NineTextureRect
2. Press the Edit Region button
3. Move the regions around and try to undo / redo with the keyboard shortcuts

### Minimal reproduction project (MRP)

NA

**Comment by mihe** [comment]
@AThousandShips Somewhat nitpicky, but seeing as how #88412 (which is largely the same problem) was labeled a bug, shouldn't this also be considered one? The undo/redo support is there already, but the shortcut isn't propagated from the dialog to the editor properly, as I understand it.

**Comment by AThousandShips** [comment]
The undo/redo support is available in the entire editor, the missing thing are the shortcuts, but I think the difference is minimal, if the editor team thinks this is a bug they can adjust the tagging
