### ISSUE TITLE
[4.4 dev5] Tooltip flickers

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#99507]
### Tested versions

4.4 dev5, Doesn't happen in 4.4 dev4

### System information

Godot v4.4.dev5 - Windows 10.0.19045 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads)

### Issue description

Some Tooltips are flickering

https://github.com/user-attachments/assets/076401db-7c70-4305-af45-bcc67054fe8b

### Steps to reproduce

Hover your mouse over the parameter name in the inspector to display a tooltip

### Minimal reproduction project (MRP)

N/A

**Comment by kitbdev** [comment]
- same as https://github.com/godotengine/godot/issues/99287

**Comment by JekSun97** [comment]
> * same as [Inspector tooltips are blinking #99287](https://github.com/godotengine/godot/issues/99287)

I tested and didn't find this problem in 4.4 dev4

**Comment by KoBeWi** [comment]
Thanks for the report, closing as duplicate.
