### ISSUE TITLE
Button "Discard local changes and reload" is confusing

### ISSUE THREAD

**Issue by manuq** [godotengine/godot#99502]
### Tested versions

- Reproducible in 4.3 stable and in 4.4 dev4

### System information

Endless OS 6

### Issue description

I'm mentoring in a game-dev program, where learners are using Git for collaboration. When they switch Git branches, the "Files have been modified on disk" dialog always appear. The title and message of the confirmation dialog are informative. But the options paralyze them.

In a Git switch, the "Discard local changes and reload" is what they want, because they are intentionally changing the files. But the label is confusing. What do "local changes" mean? Of course I know that it's "Discard changes made in Godot" but it can get confused by the Git local/remote concepts. Also maybe you didn't do any "local changes" to these files, it's just that the files changed on disk (exactly what the dialog title says).

Also, having Cancel as third option is confusing. Hopefully these buttons can have shorter labels. Something like "Are these external changes intended? Yes / No" or "Would you like to reload the files? Reload / Cancel" and after cancelling, let the user save each modified file instead of providing the "Keep local changes and overwrite" option.

![Image](https://github.com/user-attachments/assets/92324420-4612-4205-a19c-18cc4d0d8d81)

### Steps to reproduce

- Work on a project versioned with Git
- Create a new branch
- Open Godot, make some changes to the project. Commit changes
- Switch to another branch in Git while Godot is open, see the "Files have been modified on disk" dialog appear.

### Minimal reproduction project (MRP)

N/A

**Comment by manuq** [comment]
Same issue although in a different situation: https://github.com/godotengine/godot/issues/96930

**Comment by tetrapod00** [comment]
I am also frequently slightly confused by these, even as an experienced user. Since https://github.com/godotengine/godot/pull/97461 was merged, I think this dialogue should at least be changed so that "What action should be taken?" is on a new line, like the other dialogue.

**Comment by Manik2607** [comment]
I’d like to work on this issue.

I think the button labels can be made simpler and more intuitive by:
- Replace "Discard local changes and reload" with "Reload Files".
- Replace "Keep local changes and overwrite" with "Keep Changes".

This makes the dialog shorter, easier to understand, and consistent with Git terminology. 
I am not sure if this would be consistent with other dialogue across godot.

**Comment by tetrapod00** [comment]
Oh, I should have checked, this is actually already fixed by https://github.com/godotengine/godot/pull/97461 in master/4.4dev5. I thought that there were two separate places this dialogue was implemented.

Sorry for wasting everyone's time
