### ISSUE TITLE
JSON files produce `*.uid` files

### ISSUE THREAD

**Issue by produno** [godotengine/godot#99514]
### Tested versions

Godot 4.4 dev 5.

### System information

Godot v4.4.dev5 - Windows 10.0.22631 - Single-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6614) - 13th Gen Intel(R) Core(TM) i7-13700K (24 threads)

### Issue description

I use JSON files for mod support and these get imported when starting up the game. However, it's creating uid's for all of these files and will not load due to errors.

eg:
`Expected 'true','false' or 'null', got 'uid'. in res://Scenarios/Scenario_1.json.uid at line 0.
`

I'm not entirely sure if this is a bug but it seems to be an oversight. As now i will need to write extra code to handle this and all my mod files will be cluttered.

I did go through and remove them all and whilst the game will actually load, it takes several minutes longer than it should.

### Steps to reproduce

Have JSON files within your game files and they will all be given a uid.

### Minimal reproduction project (MRP)

N/A

**Comment by KoBeWi** [comment]
JSON files are Resources since #65295, so this is expected.

**Comment by produno** [comment]
> JSON files are Resources since [#65295](https://github.com/godotengine/godot/pull/65295), so this is expected.

Does this mean this will not be addressed? I see there is a linked pull request that still needs to be reviewed.

**Comment by KoBeWi** [comment]
> Does this mean this will not be addressed?

Not necessarily.
