### ISSUE TITLE
Marking all properties of a `Group/Category` as `Favorite` crashes the editor

### ISSUE THREAD

**Issue by TinyMatt** [godotengine/godot#99528]
### Tested versions

Reproducible in: 4.4.dev5, v4.4.dev.mono.custom_build [549157e6d]

### System information

Godot v4.4.dev.mono (549157e6d) - macOS 15.1.1 - Multi-window, 2 monitors - Metal (Mobile) - integrated Apple M1 (Apple7) - Apple M1 (8 threads)

### Issue description

Marking all properties from a Group/Category crashes the editor. 

Editor won't properly start over after this without clearing the `.godot/editor/favorite_properties` file.

https://github.com/user-attachments/assets/f5158811-9885-4b58-98e9-71ddf037ce12

### Steps to reproduce

Select any node and start marking properties as favorite. See the video attached.

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
This is likely a good first issue for new-ish contributors. I would suggest trying to reproduce the bug with a build that has debug symbols, and get a stacktrace.

Looking at the PR which implemented the favorites feature #97415 should also give a good indication of what code is involved (and maybe make the bug evident in hindsight).
