### ISSUE TITLE
Godot4.4-dev4: Spaming loading messages if --verbose enabled.

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#99535]
### Tested versions

- v4.4.dev4.mono.official [36e6207bb]
- v4.4.dev5.mono.official [9e6098432]

### System information

all

### Issue description

If verbose enabled, resource loading is now spamming loading messages.
![Image](https://github.com/user-attachments/assets/3e979ae8-81eb-40cd-afda-ca1f0a72fee9)

![Image](https://github.com/user-attachments/assets/a6b5661e-d645-4323-9da9-db6a9be15622)

I use `ResourceLoader.load(<script_name>, "GDScript", ResourceLoader.CACHE_MODE_REUSE)` to preload and force reuse scripts to mimimize loading times in my test framework. So I use explicit `CACHE_MODE_REUSE`.
But from the new log messages looks like the script is load again and again.

This spamming messages is filling my console when running my CI workflows now.
Godot4.4-dev5
![Image](https://github.com/user-attachments/assets/0464ed42-e92d-40f7-b386-693539018b5b)
Godot4.3-stable
![Image](https://github.com/user-attachments/assets/d125766c-ce23-4ad4-8012-98f8b34d71e2)

### Steps to reproduce

Use the script and attach it to a scene to reproduce.
```gd
extends Node2D


func _ready() -> void:
	load_test()
	get_tree().quit()


func load_test() -> void:

	for i in 10:
		ResourceLoader.load("res://test/example_script.gd", "GDScript", ResourceLoader.CACHE_MODE_REUSE)

```
* run the scene on Godot4.4.dev4 and Godot4.4.dev5:
output:
```
Loading resource: res://test/test.tscn
Loading resource: res://test/test.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
Loading resource: res://test/example_script.gd
--- Debugging process stopped ---

```
* run on Godot4.3-dev3
```
Loading resource: res://test/test.tscn
Loading resource: res://test/test.gd
Loading resource: res://test/example_script.gd
--- Debugging process stopped ---
```

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/94920 - this brought back the behavior from 4.1 which some users were missing. Those prints hadn't been removed on purpose, so they were added back.

CC @RandomShaper

**Comment by MikeSchulze** [comment]
But I use the flag `CACHE_MODE_REUSE` where indicates the resource should only load if not already cached.
So spamming the load message is not correct in this case.
