### ISSUE TITLE
Godot4.4-dev5: String presentation of float Vector types has changed and inconsistent

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#99541]
### Tested versions

v4.4.dev5.mono.official [9e6098432]

### System information

all

### Issue description

After upgrade my CI workflow, I run into a lot of test failures according to string formatting changes for float vector types.
I welcome the new format of float vectors, which now also displays floating point notation for integer values
Now Vector2.ONE => "(1.0, 1.0)" before (1, 1)
But it is not consistent over all vector types.

	prints(Vector2(2, 2)) => "(2.0, 2.0)"
	prints(Vector3(2, 2, 2)) => "(2.0, 2.0, 2.0)"
	prints(Vector4(2, 2, 2, 2)) => "(2, 2, 2, 2)"

Vector4 shows the old formatting

### Steps to reproduce

```gd
func print_vectors() -> void:

	prints(Vector2(2, 2))
	prints(Vector3(2, 2, 2))
	prints(Vector4(2, 2, 2, 2))
```
output:
```
(2.0, 2.0)
(2.0, 2.0, 2.0)
(2, 2, 2, 2)
```

### Minimal reproduction project (MRP)

n/a

**Comment by akien-mga** [comment]
CC @KoBeWi, it looks like we forgot to do the changes for Vector4 (maybe also worth checking other recent Variant types like PackedVector4Array or Projection).

**Comment by MikeSchulze** [comment]
>  too breaking and should be rolled back before 4.4.

To visualize float value this is the right solution, I wouldn't expect it to break projects as it only affects string presentation here.
In my case I had used hard coded texts to validate expected test error messages. I have fixed them by creating the expected message by using now the `str(<vector>) to build the expected failure message.
