### ISSUE TITLE
Setting RigidBody into Kinematic mode breaks physic engine

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9954]
**Operating system or device - Godot version:**
Ubuntu Linux, 246b574909f3ae1610001927b773d5b0f2c887e8 

**Issue description:**
Since two days I'm trying to hunt down this bug. Can't track it down but at least I have reproduction reproduction project. 
In my project after setting Hero into KINEMATIC_MODE physic engine goes nuts. Hero position is reseted to the position at which he was loaded, all other bodies are starting to sink through terrain:
![kinematicissue](https://user-images.githubusercontent.com/6129594/28727634-db060524-73c5-11e7-812b-e5be5eea0891.gif)

_**video with small additional note:**_ https://youtu.be/rKwi4QlmnM0

I have seen this bug for the first time in in 3.x branch

**Steps to reproduce:**
1. Download `prev` reproduction project.
2. Run it.
3. Wait

Sorry don't know more direct way to 

**Link to minimal example project:**
current: [RigidBodyInKinematicv2.zip](https://github.com/godotengine/godot/files/1267146/RigidBodyInKinematicv2.zip)
prev: [RigidBodyInKinematic.zip](https://github.com/godotengine/godot/files/1183752/RigidBodyInKinematic.zip) (still valid, reproduction steps are for this one)

**Comment by kubecz3k** [comment]
Also I should add that I was unable to sink all the objects when in `StaticBody` there was a `BoxShape`  (the one in the demo is a `ConcavePolygonShape`). But that weird position reset is always there.

**Comment by kubecz3k** [comment]
Also it seems that RigidBody which mode is about to change, need to be on the ground (also probably it can't sleep) for issue to happen.

**Comment by kubecz3k** [comment]
Updated demo to work with current master:
[RigidBodyInKinematicv2.zip](https://github.com/godotengine/godot/files/1267111/RigidBodyInKinematicv2.zip)
I also checked it with bullet branch, but the behavior for me is quite strange, after changing mode to kinematic and again to character, the body seems to disappear. 
You can test this by:
1. Downloading updated demo, 
2. Change physic engine to bullet
3. Clicking `1` and then `2` on keyboard (mode change is binded to those keys).

**Comment by kubecz3k** [comment]
cc @AndreaCatania

**Comment by AndreaCatania** [comment]
Fixed with last commit https://github.com/godotengine/godot/pull/10013/commits/8c94a1e7c4c20b7746ecdf0f3adf912cb3dfd379

**Comment by AndreaCatania** [comment]
Hey @kubecz3k! can you please close this?
