### ISSUE TITLE
Crash when importing model with unattached armature

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#9955]
**Operating system or device - Godot version:**
Godot 3.0 Alpha1
Windows 10 pro
**Issue description:**

importing any skeletal mesh's result in a crash.

**Steps to reproduce:**
import a rigged model/skeletal mesh.

**Link to minimal example project:**

**Comment by kubecz3k** [comment]
Probably related: https://github.com/godotengine/godot/issues/9715

**Comment by kubecz3k** [comment]
@vonflyhighace2 can you upload sample project? I'm able to import models with armature in 246b574909f3ae1610001927b773d5b0f2c887e8

**Comment by vonflyhighace2** [comment]
@kubecz3k sorry was not at my PC until recently. I've tried ripping the file apart, removing each aspects to see what might be causing the crash. circles don't seem to be supported and something about a rigged skeletal seems to cause the crash as well.
[Test Skeletal File.zip](https://github.com/godotengine/godot/files/1184577/Test.Skeletal.File.zip)

**Comment by kubecz3k** [comment]
@vonflyhighace2 as far as I can tell this model is broken at blender level. Familiar graphic designer told me your model don't have any armature attached: 
![parent](https://user-images.githubusercontent.com/6129594/28746002-3510c3e2-7484-11e7-84fb-0eaff9407ca2.png)
Which also can be seen when you try to mode any bone:
![noarmatureattached](https://user-images.githubusercontent.com/6129594/28746012-63d0def6-7484-11e7-8a56-c6ed4e733f51.gif)

Also your node tree is wrong, instead it should look something like this:
![out](https://user-images.githubusercontent.com/6129594/28746020-8b2e90c4-7484-11e7-81c9-53eae404acc9.png)

**Comment by kubecz3k** [comment]
And finally even with those bugs I'm unable to reproduce your problem it's opening just fine on b276d92c8a63887df011032bc95d98bbb9c51c70:
![screen](https://user-images.githubusercontent.com/6129594/28746094-c0b2add8-7485-11e7-9deb-d99a09ab4cec.png)

Please in the future, when posting an issue attach sample project, and proper reproduction details that will save us a lot of time.

**Comment by vonflyhighace2** [comment]
@akien-mga I'm not using the latest build that you are. I'm using the alpha1 build that was posted a few days back, which seems to be out dated in terms of stability. I advise you to update it since most if not all will be using that build as a base for 3.0 testing. Also I know that the model was not parented to the armature. I wanted to know if I was even able to export a armature to the aplha1 build. My character needs a more advanced rigg than what you might think in terms of animations that needs to be done. You don't need a my project. Use the Alpha1 build, create a new project, and try to export that file to the project folder, which more than likely will cause a crash since I tested with the same scenario before writing this long life story :)

**Comment by vonflyhighace2** [comment]
For a more insightful picture. https://youtu.be/gkxiz9EuFkg

**Comment by akien-mga** [comment]
I don't remember any fix since alpha1 that would be related to this issue, so I doubt the version mismatched is the root of the different experiences. It would be nice if @kubecz3k could try with 3.0-alpha1 to confirm.

**Comment by kubecz3k** [comment]
I will check tomorrow, but from the video I can see you are not exporting with our plugin. Original blender implementation of collada export is broken.

**Comment by vonflyhighace2** [comment]
I didn't think that better collada plugging was updated  with support . I will give it a try and report back.
________________________________

**Comment by vonflyhighace2** [comment]
So it seems that blenders collada exporter is broken as @kubecz3k said. it works with the better collada plugin. Blenders version has a bug with exporting  bones and some primitives.
