### ISSUE TITLE
3.0 documentation for InputEvent class

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#9956]
**Operating system or device - Godot version:**
Godot 3.0 Alpha1

**Issue description:**
InputEvent class missing Numeric Constants for polling event types. No way to get which events are being fired off.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
That's not a regression, that's how the new API works. InputEvents are now Objects, so you check there type with e.g. `event is InputEventKey` or `event is InputEventMouseButton`.

**Comment by vonflyhighace2** [comment]
aaahhh. So this is a documentation issue. Will update documentation with this.

**Comment by FeralBytes** [comment]
This seems quite well documented:
[Input Event Tutorial](http://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html?highlight=Input)
I suggest closing this.
