### ISSUE TITLE
Remove Type in Theme Item Management Removes All Listings

### ISSUE THREAD

**Issue by Temmie19** [godotengine/godot#99574]
### Tested versions

Reproducible in Stable 4.3

### System information

Godot v4.3.stable - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Mon Sep 30 19:15:46 UTC 2024 - X11 - GLES3 (Compatibility) - AMD Radeon RX 5700 (radeonsi, navi10, LLVM 18.1.8, DRM 3.49, 6.1.112-1-MANJARO) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

When attempting to remove a single item from a theme in the Manage Items pop up menu, the button to remove one item from the list removes every item from the list.

### Steps to reproduce

1. Create a theme
2. Add at least two types of nodes to the theme
3. Go to Manage Items
4. Click "Remove Item" icon next to one of the items in the list

### Minimal reproduction project (MRP)

[Archive.tar.gz](https://github.com/user-attachments/files/17878572/Archive.tar.gz)

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been reported and we prefer to keep things in one place, closing this, please see:
* https://github.com/godotengine/godot/issues/64859
