### ISSUE TITLE
Using "Show in File Manager" causes a lockup

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#9957]
**Operating system or device - Godot version:**
Godot 3.0 Alpha
Windows 10 pro

**Issue description:**
trying to open the file manager using the option under the resource tab results in a editor lockup.

**Steps to reproduce:**
Under the resource tab right click a file and use 'show in file manager'.

**Link to minimal example project:**

**Comment by vnen** [comment]
I imagine you meant "FileSystem" tab, since there's no "resource tab". In any case, the option works for on Windows.

**Comment by vonflyhighace2** [comment]
@ven I meant the resource view section under the fileSystem. They are apart of the same panel but different functionality in my opinion. on my windows 10 pro x64 system it causes the editor to hang.

**Comment by vonflyhighace2** [comment]
@vnen here is a short clip of be reproducing the bug. https://youtu.be/uaQnT6_izBM

**Comment by reduz** [comment]
I cant reproduce this either on Windows, and its just a ShellOpen call, should not freeze.. maybe there is a dialog or something asking for authorization from the OS?

**Comment by ronroniv** [comment]
I'm having exactly the same problem (Windows 7 64bit, Godot 3.0 beta1. Also can confirm with Godot 2.1.4 beta and 2.1 stable.)

For test, I made a Button node that executes GDScript `OS.shell_open("file://...")` when pressed, and it also shows the same lockup on the result program. Links to `http://...` URLs are working normally.
