### ISSUE TITLE
Tooltip blinking bug

### ISSUE THREAD

**Issue by Wolve-3DTech** [godotengine/godot#99580]
### Tested versions

Reproductible in Godot 4.4 dev4 and 4.4 dev5.

### System information

Godot v4.4.dev5.mono - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6614) - AMD Ryzen 7 5800X 8-Core Processor (16 threads)

### Issue description

This video will showcase the issue i'm currently facing : 
https://github.com/user-attachments/assets/0722bf8a-f72f-4d12-9503-d34299208d5d

### Steps to reproduce

Open Godot. Create a scene of your choice. Hover over properties in the Inspector.

### Minimal reproduction project (MRP)

Reproductible in any project.

**Comment by AThousandShips** [comment]
Thank you for reporting, this has already been reported (and is a pinned issue at the top), closing as we prefer to have a single issue to track things in

See
* https://github.com/godotengine/godot/issues/99287
