### ISSUE TITLE
Native FileDialog adds wrong extension to path

### ISSUE THREAD

**Issue by RedMser** [godotengine/godot#99591]
### Tested versions

- Reproducible in any commit after 934549e2a0822a90ef07a727b95543affaf5c57a

### System information

Godot v4.4.dev (aed94926c) - Windows 10.0.19044 - Multi-window, 3 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2080 (NVIDIA; 32.0.15.5585) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 threads)

### Issue description

Due to the new "All Recognized" entry in native FileDialogs after https://github.com/godotengine/godot/pull/99266 there is now an off-by-one in the logic for adding file extension.

Example: create a "Save file" filedialog. Set filters property to

```
*.foo,*.bar;Foo
*.txt,*.doc;Text
```

so the native filedialog has following dropdown items in filter

```
All Recognized (*.foo,*.bar,*.txt,*.doc)
Foo (*.foo,*.bar)
Text (*.txt,*.doc)
All Files (*) (*.*)
```

(btw the `(*) (*.*)` rendering like that in the All Files feels like a bug as well)

Open the file dialog and experiment with filters and filename:

- Selecting `All Recognized` and typing `test.txt` into the filename textfield results in `file_selected` to emit `test.txt.foo`
- Selecting `Foo` and typing `test.foo` into textfield results in `file_selected` to emit `test.foo.txt`
- Selecting `Text` allows for *any* file extension to be valid

### Steps to reproduce

See above.

### Minimal reproduction project (MRP)

[auto-file-extension-native-dialogs.zip](https://github.com/user-attachments/files/17882069/auto-file-extension-native-dialogs.zip)

It opens a dialog every second so you can try different file name, filter selections and see the result in an alert dialog.

**Comment by RedMser** [comment]
CC @bruvzg as it seems to have been caused by changes in #99266

**Comment by RedMser** [comment]
https://github.com/godotengine/godot/blob/master/scene/gui/file_dialog.cpp#L152

This should use `processed_filters` I think?

**Comment by bruvzg** [comment]
> (btw the (*) (*.*) rendering like that in the All Files feels like a bug as well)

Can't reproduce it (on Windows 11 and Wine), might be something Windows 10 specific:

![Image](https://github.com/user-attachments/assets/6dff3b99-44b9-4631-837c-818c8c6dd529)

**Comment by RedMser** [comment]
Thanks for the quick fix. I'll make a new ticket for the (*) thing to avoid confusion ^^
