### ISSUE TITLE
Huge CPU consumption comparing in 4.4.dev5 compared to 4.3.stable

### ISSUE THREAD

**Issue by caioraphael1** [godotengine/godot#99593]
### Tested versions

v4.3-stable to 4.4-dev5

### System information

Ryzen 3300x, 16gb RAM, GTX 1660, Windows 10, installed on a SSD

### Issue description

I have some extremely simple projects to open and join a High-level multiplayer server with ENet.
Both projects only have a _ready function to connect to each other and are set in Compatibility Render.

In v4.3, the editor and the app running both consume ~0.1% CPU, as shown at the top of the screenshot.

Meanwhile, in v4.4-dev5, each project consumes 15-18% CPU while in the editor or with the project opened, for a total of 30-36% CPU consumption if considering the editor and project together. This is shown at the bottom of the screenshot.
If I tried exporting the project in v4.4-dev5 for win10, the consumption of the exported app is the same.

![Image](https://github.com/user-attachments/assets/9ba7dabf-190f-418f-8644-ba4fd5de73ae)

I downgraded the projects back to v4.3-stable and the consumption dropped back to 0.1%.

This is happening in 4 different projects, with a mix of Forward+ and Compatibility.

I have to keep some of my projects in 4.4-dev5, as I new some of the new features for my network setup.

### Steps to reproduce

Upgrade to 4.4-dev5

### Minimal reproduction project (MRP)

The projects contain sensitive data.

**Comment by xiaoliang6669** [comment]
Yes, that's the case for me too

**Comment by Lippanon** [comment]
Please consider stripping down one of the projects down to a reasonable minimum that still displays the regressive behaviour, or if you can build from source, [bisecting it](https://docs.godotengine.org/en/stable/contributing/workflow/bisecting_regressions.html), otherwise it is very difficult to locate the regression source.

**Comment by caioraphael1** [comment]
[demo_gateway.zip](https://github.com/user-attachments/files/17893422/demo_gateway.zip)

I've removed the DTLS certificates and reduced the project to a minimum. The bug still happens.

**Comment by caioraphael1** [comment]
[demo_gateway.zip](https://github.com/user-attachments/files/17893431/demo_gateway.zip)

I've removed the DTLS certificates and reduced the project to a minimum. The bug still happens.

**Comment by YYF233333** [comment]
I can reproduce this in an empty project. Here is what I got from VS profiler:

![Image](https://github.com/user-attachments/assets/d8f4b6d3-5ee8-4495-9fac-7dfdf70be5fe)

#99178 change the implementation of `OS_Windows::delay_usec`, previously it use `Sleep`, now it use a loop wait. Tested locally, this (`df3367f334`) is the first commit it appear.

**Comment by Lippanon** [comment]
Copying relevant snippet from the PR:

> "Still, this is the most precision we can possibly get here.
> 
> The problem with this is that spin-locking eats up CPU time and does absolutely nothing. This time could have been better used by other threads that actually have usefull work to do. Or if no other threads are running, the CPU core could have been switched into low-power mode in order to save power and battery life on mobile systems."
> 
> https://blog.bearcats.nl/accurate-sleep-function/

This trade-off of CPU usage for precision is likely expected, but perhaps it would be sensible (if possible) to have a project setting to toggle implementations?

**Comment by caioraphael1** [comment]
> This trade-off of CPU usage for precision is likely expected, but perhaps it would be sensible (if possible) to have a project setting to toggle implementations?

I don't know if the change in this PR is vital, but at least I don't think this should be enabled by default. Opening 2 simple projects editor and running both is making me go to 100% CPU consumption. I can't actually work on any of those projects, it's extremely laggy.

**Comment by YYF233333** [comment]
Doing a quick search and I understand the situation. Win 10 has [Waitable Timer](https://learn.microsoft.com/en-us/windows/win32/sync/waitable-timer-objects) which is efficient and precise, but we need to support Win 7, so a loop with `YieldProcessor()` is used, hoping it will release CPU. (seems not work on my computer)

I'd suggest use Waitable Timer for Win 10 and above, use busy wait only for Win 7.

**Comment by YYF233333** [comment]
Doing a quick search and I understand the situation. Win 10 has [Waitable Timer](https://learn.microsoft.com/en-us/windows/win32/sync/waitable-timer-objects) which is efficient and precise, but we need to support Win 7, so a loop with `YieldProcessor()` is used, hoping it will release CPU. (seems not work on my computer)

I'd suggest use Waitable Timer for Win 10 and above, use busy wait only for Win 7.

@caioraphael1 In case you need it, this is master branch with #99178 reverted: https://drive.google.com/file/d/1fjvpnflQ-taHSkgLCZX86xfz9bQzbICv/view?usp=sharing

**Comment by caioraphael1** [comment]
@YYF233333 Thank you!!! CPU consumption is now at 25-35%, under the same conditions.

**Comment by clayjohn** [comment]
@YYF233333 The results are very interesting. In theory the change in https://github.com/godotengine/godot/pull/99178 should never spin with `YieldProcessor()` for more than 1.2 ms per frame. 

Although, now that I am looking at the usages of `delay_usec()`, it seems like the audio driver often tries to delay by exactly 1ms. With this change, instead of sleeping for 1 ms, we spin for 1 ms because the threshold is 1.2 ms now. 

I guess the proper solution will be to lower the threshold so that we actually sleep in such cases

What do you think @mrsaturnsan?

**Comment by YYF233333** [comment]
> In theory the change in [#99178](https://github.com/godotengine/godot/pull/99178) should never spin with `YieldProcessor()` for more than 1.2 ms per frame.

Actually, no more than 2.02 ms (you need to sleep at least 1 ms).

And I think the threshold is problematic. The precision of `Sleep()` is about 15.6 ms by default, means `Sleep(x)` actually sleep between x ms ~ x + 15.6 ms. So if you want to sleep 15ms or shorter, you cannot afford even once `Sleep()`. That `tolerance` should be `15000(us)`.

**Comment by stesproject** [comment]
I add that the problem only occurs from dev5. I used dev4 until the other day and there wasn't this huge CPU consumption with the previous build.

**Comment by YYF233333** [comment]
By the way, @mrsaturnsan I'd like to ask what's the original purpose of #99178? It doesn't link to an issue, and I haven't ran into problem with framerate, looks a bit odd to me. Why we need so stable frametime?

**Comment by Calinou** [comment]
> Why we need so stable frametime?

Unstable frametimes result in [jittery motion](https://docs.godotengine.org/en/stable/tutorials/rendering/jitter_stutter.html). VRR displays can attenuate this somewhat but you get [VRR flicker](https://www.youtube.com/watch?v=pLkyrR-eUnM) when frametimes are unstable, due to the gamma curve constantly changing ever so slightly as the monitor adjusts its refresh rate.

**Comment by YYF233333** [comment]
> I guess the proper solution will be to lower the threshold so that we actually sleep in such cases

Back with test results, run 10k times for each case, `Period` is the delay specified, and `Tolerance` is that param in the code. 

Worst case seems to have no difference, for P99 you can see that max error is 1ms - `tolerance`.

![Image](https://github.com/user-attachments/assets/6bf974e3-d461-4b92-8dca-dd4c0cac8f2d)
![Image](https://github.com/user-attachments/assets/f72d0fb9-85aa-4d4d-bdfa-8cfbf2ad4ca8)
