### ISSUE TITLE
Compiling with `scu_build=yes` takes the double of the time to compile in 4.4 dev 4

### ISSUE THREAD

**Issue by matheusmdx** [godotengine/godot#99607]
### Tested versions

- Reproducible: 4.4 dev 4 and 5
- Not reproducible: 4.4 dev 3

### System information

Godot v4.4.dev4 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 580 2048SP (Advanced Micro Devices, Inc.; 31.0.21921.1000) - AMD Ryzen 5 3600 6-Core Processor (12 threads)2 threads)

### Issue description

SCons 4.8.1, Python 3.12, MSVC 2022 17.9.6

While bisecting some issues between 4.4 dev 3 and dev 4 i noticed my compiling time was slower than the normal sometimes and others compiled in the expected time, after some investigation i ended finding that started after pr #98888. Before the cited pr i was able to compile from zero with `dev_build=yes scu_build=yes` in about 4 minutes, after that pr my compile time jumped to 8:30.

 CC @dustdfg

### Steps to reproduce

Compile with `dev_build=yes scu_build=yes` and compare the time before and with pr #98888

### Minimal reproduction project (MRP)

N/A

**Comment by lawnjelly** [comment]
To be honest I don't know why this change was made, it is "tinkering", and managed to break the existing implementation (which has been tested multi-platform).

**Comment by dustdfg** [comment]
`¯\_(ツ)_/¯` so just revert it. It works the same on linux though

**Comment by dustdfg** [comment]
@anvilfolk just interesting can you reproduce it too? IIRC you said that SCU was broken on windows in some way

**Comment by matheusmdx** [comment]
The thing i noticed is the time to compile without scu is almost the same of using scu after the pr, its looks like the command is not having effect. I also did a test printing the string that `section_name` holds in `methods.py` and the amount of paths is the same but they use different slashes, #98888 was using "\" (core\os) while before #98888 was "/" (core/os), so i did a `section_name = section_name.replace("\\", "/")` and that worked, i know windows can be annoying about the slashes but that makes sense in this case?

**Comment by AThousandShips** [comment]
I think we should try to resolve this rather than just revert it, much more sustainable solution

**Comment by lawnjelly** [comment]
> and the amount of paths is the same but they use different slashes

It will probably be the backslashes or OS specific and not finding files in the hashtable, this is why it was done like this originally (we had to work through a few such issues when it was first added).

**Comment by dustdfg** [comment]
`os.path.normpath()`?

**Comment by dustdfg** [comment]
> > and the amount of paths is the same but they use different slashes
> 
> It will probably be the backslashes or OS specific and not finding files in the hashtable, this is why it was done like this originally (we had to work through a few such issues when it was first added).

You mean that it will be in one format in `_scu_folders` and in another depending on which OS is used? There is `ntpath` and `posixpath` python modules

**Comment by AThousandShips** [comment]
I can confirm that the engine simply is built without SCU currently, will investigate fixes
