### ISSUE TITLE
Add HarfBuzz for text shaping (complex scripts, font ligatures)

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#9961]
Change `DynamicFont` to use [HarfBuzz](https://github.com/behdad/harfbuzz) (MIT license) to handle:

1. Context-sensitive shaping and ligatures for complex scripts (Arabic, Devanagari, Thai etc.);
2. Programming ligatures with fonts like [Iosevka](https://github.com/be5invis/Iosevka) & [Fira Code](https://github.com/tonsky/FiraCode) in script editor.

![fonts](https://user-images.githubusercontent.com/7645683/28739597-ddbc6558-7404-11e7-8a73-572f94e62cff.png)

Related: #3081

**Comment by reduz** [comment]
Would be ideal to just adapt the relevant code instead of using a pretty big library for it

**Comment by bruvzg** [comment]
This is far from finished and a hell of a mess, but here's early in-progress screenshot (bidi display, language specific shaping, OT typographic features).

**Test build:**
![test](https://user-images.githubusercontent.com/7645683/29452414-fbc36c8a-840e-11e7-83d3-4d71d6d355c2.png)

**3.0 alpha 1:**
![test3a](https://user-images.githubusercontent.com/7645683/29452844-653ed2c0-8410-11e7-80b3-9071429fabd8.png)

I'll probably make WIP PR next week.

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-proposals#4.
