### ISSUE TITLE
Blend space 1D sync option doesn't do anything

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#99616]
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Kubuntu 24.04

### Issue description

I am trying to blend between two animations however the sync option in animationtree's blend space 1d doesn't seem to do anything.

### Steps to reproduce

- Download project
- Open human.tscn
- Open AnimationTree
- Try blending between walk and run (0.5 - 1.0)

### Minimal reproduction project (MRP)

[spacetest.zip](https://github.com/user-attachments/files/17892123/spacetest.zip)

**Comment by TokageItLab** [comment]
Not bug. The Sync option does not have the ability to align the animation length, so you should use NodeAnimation's CustomTimeline to align the length of the animation. See also https://github.com/godotengine/godot/pull/87171#issuecomment-2192692141.

```gdscript
func _process(delta: float) -> void:
	set("parameters/TimeScale/scale", remap(get("parameters/Movement/blend_position"), 0.5, 1.0, 1.0, 2.0))
```

[spacetest_fixed.zip](https://github.com/user-attachments/files/17892963/spacetest_fixed.zip)
