### ISSUE TITLE
Native FileDialog in "Open Folder" mode grays out all directories

### ISSUE THREAD

**Issue by Variable-ind** [godotengine/godot#99627]
### Tested versions

- Reproducible in 4.3.stable

### System information

Godot v4.3.stable - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 620 (KBL GT2) - Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 Threads)

### Issue description

The native file dialog grays out all folders when i enable `Use Native Dialog` and set the file mode to `Open Folder`

![Image](https://github.com/user-attachments/assets/01aa4861-76ef-4681-8a09-d8dafe2bf706)

from my tests, it seems to happen only in `Open Folder` mode and for me the initial directory is ALWAYS `/home/{username}` regardless of the mode i chose in `Access`.

### Steps to reproduce

- make a new project.
- add a Filedialog to the scene.
- enable `Use Native Dialog` and set **File Mode** to `Open Folder`
- popup the dialog when you run the scene

For detailed steps see the video below:

https://github.com/user-attachments/assets/f40cbea6-50f4-41e5-99af-e76d92e45ecd

### Minimal reproduction project (MRP)

[dialogtest.zip](https://github.com/user-attachments/files/17893265/dialogtest.zip)

**Comment by RadiantUwU** [comment]
Couldn't reproduce on v4.3.beta2.official [b75f0485b], v4.4.dev3.official [f4af8201b]

Godot v4.4.dev3 - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1650 (nvidia; 565.57.01) - AMD Ryzen 7 8700F 8-Core Processor (16 threads)

WM: KWin

DE: Plasma 6.2.4

**Comment by Variable-ind** [comment]
> Couldn't reproduce on v4.3.beta2.official [[b75f048](https://github.com/godotengine/godot/commit/b75f0485ba15951b87f1d9a2d8dd0fcd55e178e4)], v4.4.dev3.official [[f4af820](https://github.com/godotengine/godot/commit/f4af8201bac157b9d47e336203d3e8a8ef729de2)]
> 
> Godot v4.4.dev3 - Arch Linux [#1](https://github.com/godotengine/godot/issues/1) SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 on X11 - X11 display driver, Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1650 (nvidia; 565.57.01) - AMD Ryzen 7 8700F 8-Core Processor (16 threads)
> 
> WM: KWin
> 
> DE: Plasma 6.2.4

I can confirm that this has indeed been fixed in `Godot 4.4 dev 6` (at least it doesn't happen for Mint anymore)
--- Thanks 😁

(In the video below, you see me running the MRP in `Godot v4.3.stable` and then in `Godot 4.4 dev 6`)

https://github.com/user-attachments/assets/64039747-f4e8-4263-99d9-6e929deb6be2
