### ISSUE TITLE
`gltf2` model importing error

### ISSUE THREAD

**Issue by Sandstorm-mt** [godotengine/godot#99625]
### Tested versions

Latest version

### System information

Forward+, 1050ti, i5-4990 or something like that, 8gb

### Issue description

when imported, model significantly differs from what blender viewport shows
![Image](https://github.com/user-attachments/assets/d40fc41c-8f02-45ee-99cd-c6c57b604aeb)
![Image](https://github.com/user-attachments/assets/8e632e1f-38e8-4f28-a428-d09273680730)

### Steps to reproduce

import the model, add it to scene.

model:
https://drive.google.com/file/d/1-s3SC7Bm1ORXljxeOmLLqB4LlZiKS4tz/view?usp=sharing
(trying loading it to github giving me errors)

### Minimal reproduction project (MRP)

N/A

**Comment by fire** [comment]
Loading into https://gltf-viewer.donmccurdy.com/ gives this result.

![Image](https://github.com/user-attachments/assets/3ea5c815-275e-4eec-bc98-d2d9c4f665e4)

**Comment by fire** [comment]
![Image](https://github.com/user-attachments/assets/4cb8f4cb-1932-4eef-bf0f-58437c111e24)

Blender is giving similar results.

**Comment by Sandstorm-mt** [comment]
so that means thats probably a problem on my side
