### ISSUE TITLE
get_accelerometer, get_gravity(), get_magnetometer(), and get_gyroscope() don't work on Godot v4.4.dev4.official - Android

### ISSUE THREAD

**Issue by TheOathMan** [godotengine/godot#99643]
### Tested versions

Godot v4.4.dev4.officia - Android

### System information

Godot Editor; Windows 11 - Build Platform : Android - Godot v4.4.dev4.official - Compatibility - RTX3070

### Issue description

The [Mobile Sensors Demo](https://github.com/godotengine/godot-demo-projects/tree/4.2-31d1c0c/mobile/sensors) doesn't work on Godot v4.4.dev4.official Android, but works fine on Godot v4.3.stable.
These functions in particular returns Vector3.ZERO on android 14:
```
var acc = Input.get_accelerometer()
var grav = Input.get_gravity()
var mag = Input.get_magnetometer()
var gyro = Input.get_gyroscope()
```

### Steps to reproduce

Using Godot v4.4.dev4.official, download [Mobile Sensors Demo](https://github.com/godotengine/godot-demo-projects/tree/4.2-31d1c0c/mobile/sensors) project. Run the demo on an android device, then you will notice all 'Input' function return zero.

### Minimal reproduction project (MRP)

 Run [Mobile Sensors Demo](https://github.com/godotengine/godot-demo-projects/tree/4.2-31d1c0c/mobile/sensors).

**Comment by TheOathMan** [comment]
never mind, I debug the code, it turns out it has to be enabled from project settings. This should be added as a note in the docs.

**Comment by kelteseth** [comment]
@TheOathMan thanks had the exact same issue!
