### ISSUE TITLE
Threading errors when threading is not used.

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#99660]
### Tested versions

- Not reproducable in Godot 4.3 stable
- Reproducable in Godot 4.4 master (9e6098432aac35bae42c9089a29ba2a80320d823)

### System information

Windows 11 - Forward+ - NVidea 4070Ti

### Issue description

Opening an existing project that has been working since Godot 3 days in latest master floods the log with `Moving child node positions inside the SceneTree is only allowed from the main thread. Use call_deferred("move_child",child,index).`

![Image](https://github.com/user-attachments/assets/11446b6a-7995-4d61-8fc8-bd04fbd38ec5)

Note that these errors are given just opening this scene in the editor. To my knowledge the only place threading is used in this project is that its using the `ResourceLoader` but this only effects runtime.

Note that at the same time the console within VSCode gets flooded with:
![Image](https://github.com/user-attachments/assets/7febba55-4f9d-4363-9876-bc1c0219fcca)

The error not referring to what code leads to this issue means we're looking for a needle in a haystack and with the editor becoming unresponsive, it's a challenge.

My best guess is that this is caused by this project using `@tool` scripts that hook into the `changed` signal of a 3D curve which both triggers the CSG polygon that build the track updating, as well as reposition various other elements.

### Steps to reproduce

As right now it's impossible to pinpoint the cause of this, the only way to reproduce is to open the effected project.

### Minimal reproduction project (MRP)

https://github.com/BastiaanOlij/vehicle-demo/pull/15

**Comment by BastiaanOlij** [comment]
Well, I'm stumped. After going through a full bisect, the problem has just disappeared. I'm at a loss to explain it.. Even resetting the project back to freshly cloned from GIT..

**Comment by theraot** [comment]
Perhaps related to Godot rebuilding cache, or changes in internal formats from one version to another?

**Comment by BastiaanOlij** [comment]
> Perhaps related to Godot rebuilding cache, or changes in internal formats from one version to another?

Definitely a possibility, this project has lots of generated geometry that may have been stored in an old format and failed to update nicely.
