### ISSUE TITLE
Caller thread can't call this function in this node. Error when setting a mesh for a MeshInstance2D

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#99661]
### Tested versions

v4.4.dev5.official [9e6098432]

### System information

Fedora Linux 40 (KDE Plasma) on Wayland - X11 display driver, Single-window,

### Issue description

https://github.com/user-attachments/assets/7646fb70-c660-46f0-9d68-11deacab0c69

```
Caller thread can't call this function in this node (/root/@EditorNode@18000/@Panel@13/@VBoxContainer@14/DockHSplitLeftL/DockHSplitLeftR/DockHSplitMain/@VBoxContainer@25/DockVSplitCenter/@VSplitContainer@52/@VBoxContainer@53/@EditorMainScreen@98/MainScreen/@CanvasItemEditor@10010/@VSplitContainer@9834/@HSplitContainer@9836/@HSplitContainer@9838/@Control@9839/@SubViewportContainer@9840/@SubViewport@9841/Node2D/MeshInstance2D). Use call_deferred() or call_thread_group() instead.
```

### Steps to reproduce

Add a mesh to MeshInstance2D

### Minimal reproduction project (MRP)

[2dmesh.zip](https://github.com/user-attachments/files/17896603/2dmesh.zip)

**Comment by matheusmdx** [comment]
Bisected to #97770, @tdaven 

![Image](https://github.com/user-attachments/assets/fca151b4-ee96-45ac-90dc-18db299069fc)

**Comment by matheusmdx** [comment]
@clayjohn I just opened a project i have to test bugs, added a `MeshInstance2D` in the tree and setted the `mesh` property


https://github.com/user-attachments/assets/3d1e8243-4ae6-4a04-b561-063b3a719c2e

**Comment by tdaven** [comment]
I'll try to reproduce.

**Comment by tdaven** [comment]
I've been able to reproduce, I'll investigate later today when I get a chance.

**Comment by tdaven** [comment]
This is triggered by the MeshEditorPreviewPlugin's generate function which is working to update the mesh preview.  It calls the get_rid (and later get_aabb) on the primitive mesh.  PrimitiveMesh is interesting in these methods because they are not just getters, they also update if there is something pending.

**Comment by tdaven** [comment]
A quick fix could be to follow what mesh_instance_3d does and call get_rid before connecting to the changed signal.  See https://github.com/godotengine/godot/blob/d09d82d433b03bb3773fd2a8cc8d6ccc2f8739ce/scene/3d/mesh_instance_3d.cpp#L112.

Seems to fix the issue.  Longer term though, seems it would be best to fix primitive mesh to notify of changes  correctly so get_rid and get_aabb rather then having special hacks in locations.

Thoughts?

**Comment by tdaven** [comment]
It's also possible just removing those updates from getters can be done now that mesh_instance_2d connects to changed signal.  Seems to work but unsure if there are side affects not seen yet.
