### ISSUE TITLE
Issue with Accent Marks (Diacritics)

### ISSUE THREAD

**Issue by kerenskybr** [godotengine/godot#99678]
### Tested versions

Not present:
Godot v4.2.stable

Present:
Godot v4.3.stable
Godot_v4.4-dev5

### System information

Godot v4.3.stable - Ubuntu 24.04.1 LTS 24.04 - X11 - Vulkan (Forward+) - integrated AMD Radeon Vega 8 Graphics (RADV RAVEN) - AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

Adding Accent Marks freeze the engine

I.e. ( # Continuaç~ -> engine freezes here (Trying to write # Continuação
Accent marks that freezes the engine -> ~, ^, ´, `

Still present on Godot_v4.4-dev5

### Steps to reproduce

Try to write a comment using accent marks

### Minimal reproduction project (MRP)

Not necessary

**Comment by AThousandShips** [comment]
Thank you for reporting! This has already been reported and we prefer to keep things in one place, so I'm closing this

Please see:
* https://github.com/godotengine/godot/issues/85664
