### ISSUE TITLE
Custom tooltip showing when no tooltip text is set

### ISSUE THREAD

**Issue by filkata** [godotengine/godot#99675]
### Tested versions

Reproducible in 4.4-dev5, 4.4-dev4
Not reproducible in 4.4-dev3, 4.3 stable

### System information

Godot v4.4.dev3 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 1500X Quad-Core Processor (8 threads)

### Issue description

Previously if a node had a custom tooltip setup using _make_custom_tooltip() but has no tooltip text set -> no tooltip would be shown. In 4.4-dev4 and 4.4-dev5 an empty tooltip is shown.

### Steps to reproduce

Hover over the TextureButton in the MRP.

### Minimal reproduction project (MRP)

[tooltip_bug.zip](https://github.com/user-attachments/files/17903329/tooltip_bug.zip)

**Comment by timothyqiu** [comment]
This is an intended change, see #97961.

Now `_make_custom_tooltip()` takes full control of the tooltip logic and is called regardless of whether `get_tooltip()` returns an empty string.

To obtain the old behavior, check the argument at the beginning of `_make_custom_tooltip()` and return `null` if it's an empty string.

**Comment by Mickeon** [comment]
While this is intentional, should not be denoted as a somewhat breaking change?

**Comment by filkata** [comment]
I wonder if this warrants a mention in the documentation?

**Comment by timothyqiu** [comment]
> While this is intentional, should not be denoted as a somewhat breaking change?

Indeed. How should this be denoted?

**Comment by Mickeon** [comment]
First of all, I think we should tag the original PR as breaking compatibility(???). So that, when it's time, a page like [Upgrading from Godot 4.2 to 4.3](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.3.html) can include this change, as well.
