### ISSUE TITLE
2D Multi Object Scale unwanted behavior

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#99673]
### Tested versions

Master - 0c45ace15

### System information

Godot v4.4.dev (0c45ace15) - Windows 10.0.22631 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7800 XT (Advanced Micro Devices, Inc.; 32.0.12019.1028) - AMD Ryzen 9 7900X 12-Core Processor (24 threads)

### Issue description

While the new multi object scale works great when setting a temp pivot point. It acts poorly when scaling each object about it's own pivot.

https://github.com/user-attachments/assets/29d1a904-a88a-4d33-8e72-833fc5c742d1

It appears the scaling amount is based on the distance from the center of each object to the mouse, meaning the scaling will be different for each object, maybe even inverted when the mouse is between the objects. I think it should be based on the distance from the beginning of the mouse drag to the current mouse position or the distance from a central point to the current mouse position, so the scaling to each object is the same like in Blender when set to individual origins.

https://github.com/user-attachments/assets/0f501440-1b1c-447f-9b8f-f18904afc2bd

### Steps to reproduce

Create some sprites and try to scale them at the same time

### Minimal reproduction project (MRP)

NA

**Comment by Giganzo** [comment]
See https://github.com/godotengine/godot/issues/99505 and the linked PR

**Comment by Arnklit** [comment]
> See [#99505](https://github.com/godotengine/godot/issues/99505) and the linked PR

Thanks @Giganzo ... Tested the PR as well and it solves it. Nice work. Closing.
