### ISSUE TITLE
Text Editor: Copying without selection (Ctrl+C) erases the clipboard contents

### ISSUE THREAD

**Issue by berarma** [godotengine/godot#99670]
### Tested versions

- Reproducible in: 4.3stable

### System information

Debian GNU/Linux 12.7

### Issue description

Copying without having some text selected (Ctrl+C) in the text editor erases the clipboard contents. It's annoying because pressing accidentally Ctrl+C instead of Ctrl+V erases what was going to be copied.

Pressing Ctrl+X does the same and also removes the current line. This is even more surprising.

What these commands do when there's no selection is auto-select the current line, even if it's empty. I think this isn't documented anywhere and it isn't intuitive. I haven't seen this behavior in any other text editor. It's totally unexpected and becomes very annoying when doing mistakes while using the clipboard shortcuts.

Could we have a more agnostic behavior and maybe add a setting for the current one?

### Steps to reproduce

- Select some text in the text editor and press Ctrl+C.
- Move the cursor to another place without selecting text.
- Press Ctrl+C, nothing seems to happen.
- Press Ctrl+V, the text copied previously doesn't get pasted.

### Minimal reproduction project (MRP)

Not needed.

**Comment by syntaxerror247** [comment]
There is already a setting available to turn off this behavior. Go to `Editor Settings -> Text Editor -> Behaviour` and turn off `Empty Selection Clipboard`.
![Image](https://github.com/user-attachments/assets/0d53104c-b27e-4fd8-ac4e-5c6b8bdaac50)

**Comment by AThousandShips** [comment]
I had missed that that was implemented already

Closing as already solved, thank you for your bug report nonetheless!

**Comment by berarma** [comment]
Thanks. That's good. Waiting for the final release.
