### ISSUE TITLE
Navigating an OptionButton's PopupMenu using keyboard or controller causes flashing items

### ISSUE THREAD

**Issue by Xander5522** [godotengine/godot#99681]
### Tested versions

Godot_v4.3-stable, Godot_v4.4-dev5

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+ [This bug also appears using the compatibility renderer]) - dedicated NVIDIA GeForce RTX 4070 (NVIDIA; 32.0.15.6590) - AMD Ryzen 5 7600 6-Core Processor (12 Threads)

### Issue description

Navigating an OptionButton's PopupMenu with a keyboard's arrow keys or a controller ocationally causes the items in the menu to quickly flash before settling on a seemingly random item. This glitchy behavior only happens durring the first input on that menu.

This issue is similar #42230

### Steps to reproduce

Use a keybaord's arrow keys to navigate an OptionButton's PopupMenu. 
This can be quickly done in Godot's project manager in the top right where it says: "Sort: Last Edited".
Reproducing this bug is inconsitant so it may take a few attempts.

### Minimal reproduction project (MRP)

N/A

**Comment by Giganzo** [comment]
Sound to be same as this issue https://github.com/godotengine/godot/issues/94712#issuecomment-2282093214

**Comment by Xander5522** [comment]
Thanks for sending that link Giganzo, I belive this is the same issue as the one you mentioned.
I searched and searched for a long time but coudln't find anyone with the same issue.
This issue could probably be closed / merged with the one you mentioned unless anyone has anything else to add to this.
