### ISSUE TITLE
No way to add an item to 'tools button' (EditorPlugin.add_tool_menu_item)

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#9969]
**Operating system or device - Godot version:**
b276d92c8a63887df011032bc95d98bbb9c51c70

**Issue description:**
It seems since 0aa7242624fcd74eaf13db006274829c284fab3b logic to do this task is non existent.

**Steps to reproduce:**
1. Download Godot sources.
2. Open EditorPlugin.cpp 
3. Check bindings near 400 line, 
4. See that `add_tool_menu_item` and `remove_tool_menu_item` bindings are commented, try to find their logic.
5. See that `add_tool_submenu_item` has some commented logic, and don't seems to do anything.

**Link to minimal example project:**

**Comment by neikeq** [comment]
Why was this removed?

**Comment by neikeq** [comment]
@reduz I asked you about this the other day, and you said you thought this feature was removed. Is this feature meant to be gone and why? Was there any problem with it?

**Comment by reduz** [comment]
Oh no, i did not realize that it was moved, but it's still there

**Comment by neikeq** [comment]
@reduz but, as stated by OP, the logic for these methods was removed by 0aa7242. Why?

**Comment by mhilbrunner** [comment]
@reduz Why was this commented out? Needed this & stumbled upon this issue

**Comment by vnen** [comment]
This was likely changed when the menus got rearranged. Tools used to be a top-level menu, now it's a submenu of Project. The code to add the menu may need some change in logic, I don't think it's just a matter of uncommenting it.

**Comment by mhilbrunner** [comment]
Thanks for the explanation, makes sense :)

**Comment by neikeq** [comment]
Would love to see this added back. I don't like to have the Mono menu button on a corner :worried:
