### ISSUE TITLE
Godot v4.4.dev5 breaks MultiplayerSpawner: Condition "!ResourceLoader::exists(p_path)" is true.

### ISSUE THREAD

**Issue by DomiStyle** [godotengine/godot#99706]
### Tested versions

Reproducible in: Godot v4.4.dev5.mono
Not reproducible in: Godot v4.3.stable.mono

Only tested with C#.

### System information

Godot v4.4.dev5.mono - Freedesktop SDK 24.08 (Flatpak runtime) on Wayland - Wayland display driver, Single-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) - AMD Ryzen 7 5800X3D 8-Core Processor (16 threads)

### Issue description

A MultiplayerSpawner where the Auto Spawn List is assigned in Godot 4.4 will not replicate nodes to clients. The Auto Spawn List is reset every time the editor reopens with the following error message:

```
modules/multiplayer/multiplayer_spawner.cpp:108 - Condition "!ResourceLoader::exists(p_path)" is true.
```

In addition any MultiplayerSynchronizer errors out on the client with:

```
ERROR: Node not found: "Game/Network/Player/MultiplayerSynchronizer" (relative to "/root").
   at: get_node (scene/main/node.cpp:1873)
ERROR: Parameter "node" is null.
   at: process_simplify_path (modules/multiplayer/scene_cache_interface.cpp:118)
```

View in Godot 4.4 (left is host, right is client):
![Image](https://github.com/user-attachments/assets/416e7402-8542-49c8-9abe-d4e283f16308)

View in Godot 4.3:
![Image](https://github.com/user-attachments/assets/9c1a5fde-d77e-4b1f-9bc3-e880c749adc6)

(Pill in the back is already present in scene to show that peers are connected)

dev5 should contain https://github.com/godotengine/godot/pull/99137, so that didn't seem to fix it.

### Steps to reproduce

1. Open a Godot 4.3 project containing a `MultiplayerSpawner` in Godot 4.4
2. Start two instances and observe that everything is working
3. Clear the `Auto Spawn List` of the `MultiplayerSpawner` and assign it again
4. Start two instances and observe that scenes are not spawned on the client

This works in both directions. An `Auto Spawn List` assigned in Godot 4.4 will not load correctly in Godot 4.3 until the `Auto Spawn List` is reassigned.

### Minimal reproduction project (MRP)

In the MRP, everything is working as expected since it was edited in Godot 4.3.

To break it: Open the `Game.tscn` scene and reassign the `Auto Spawn List` on the `MultiplayerSpawner`. Add `res://Player.tscn`.

[MultiplayerSpawnerTest.zip](https://github.com/user-attachments/files/17917858/MultiplayerSpawnerTest.zip)

**Comment by akien-mga** [comment]
CC @KoBeWi @Faless
