### ISSUE TITLE
[Editor] setting the preview environment to all black still leaves the horizon

### ISSUE THREAD

**Issue by hpvb** [godotengine/godot#99701]
### Tested versions

Reproducable on current master [d09d82d433b03bb3773fd2a8cc8d6ccc2f8739ce]

### System information

Godot v4.4.dev (779fe8da4) - Fedora Linux 41 (Workstation Edition) on Wayland - X11 display driver, Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon RX 6950 XT (RADV NAVI21) - AMD Ryzen Threadripper PRO 5975WX 32-Cores (64 threads)

### Issue description

When setting the editor environment to all black, a white horizon remains.

![Image](https://github.com/user-attachments/assets/22636b8e-1baa-4243-a44e-e66ba3076578)

![Image](https://github.com/user-attachments/assets/d477b439-c4c7-40f4-b769-7139c9ec9eee)

### Steps to reproduce

Set editor environment to all black, with 0% sun.

Observe that the editor still has a white horizon

### Minimal reproduction project (MRP)

N/A

**Comment by hpvb** [comment]
Note that this is *not* the grid going into the distance.

![Image](https://github.com/user-attachments/assets/6c498924-a50c-4412-a6d9-80525e17e98f)

**Comment by clayjohn** [comment]
This isn't a bug _per se_. The horizon color was never exposed to this menu since the menu is just intended for quick edits to the overall color of the scene. That's also why it only exposes a few options from the WorldEnvironment.

**Comment by hpvb** [comment]
@clayjohn I would argue that at the very least this is really surprising. I found this issue while doing my new hobby of "watching random Godot streamers", and one of them was trying to setup an editor environment they could use to test their particle system.

It looked like a reasonable thing to want to do to me.

**Comment by clayjohn** [comment]
Sure. I'm just providing context so no one goes investigating to find the root of the bug.
