### ISSUE TITLE
`Engine.max_fps` has bad frame pacing due to inaccurate OS sleep functions

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#99728]
### Tested versions

- Reproducible in: 4.3.stable, 4.4.dev5

### System information

Godot v4.3.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6603) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

`Engine.max_fps` has bad frame pacing due to inaccurate OS sleep functions. This means the built-in FPS limiter isn't as stable as external solutions such as RTSS or Special K can be. This in turn leads to a bad player experience.

This is most noticeable on Windows where its sleep functions are known to be inaccurate compared to other operating systems. Nonetheless, even on other OSes, frametime graphs aren't quite a flat line even when the CPU and GPU are far from being fully utilized.

Possible avenues for improving this include:

- Perform hybrid busywaiting and sleeping, so we get more precise sleep durations but without increasing CPU utilization too much.
- On Windows 10 1803 and later, use `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION ` as mentioned in https://blog.bearcats.nl/perfect-sleep-function/.

With good frame pacing, the graph should look like this:

![Screenshot 2024-11-16 154908](https://github.com/user-attachments/assets/b19753cf-f70e-49f0-b399-57f6a94e1fb5)

But in `master`, it looks like this instead:

![Screenshot 2024-11-16 154705](https://github.com/user-attachments/assets/bb5001f6-8df0-48d9-a4ec-939284322d42)

See https://github.com/godotengine/godot/pull/99178 and https://github.com/godotengine/godot/pull/99656.

### Steps to reproduce

Run the MRP and look at the frametime graph with various `Engine.max_fps` values.

### Minimal reproduction project (MRP)

[test-frame-pacing.zip](https://github.com/user-attachments/files/17786922/test-frame-pacing.zip)

**Comment by Faless** [comment]
Some screenshots from my tests on Linux.

System: Debian GNU/Linux 12 (bookworm), Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 980 (NVIDIA; 32.0.15.6603) - Intel® Core™ i7-7700K × 8

![Image](https://github.com/user-attachments/assets/354bbb62-63eb-4c55-9733-086903d4e684)
![Image](https://github.com/user-attachments/assets/72ab1f87-ca27-4f00-af1a-d6aa00c81b35)
![Image](https://github.com/user-attachments/assets/07827afc-a81a-4ced-89c5-5de5a6235f31)


So, at least on Linux, there doesn't seem to be any specific issues with the sleep functions and frame pacing, and the (small) fluctuations happens in any case, even with unlimited max_fps and the loop is just regulated by vsync (i.e. we add no frame delay).

Am I missing something?

**Comment by clayjohn** [comment]
> Am I missing something?

I think its best to treat this as a Windows issue. We know that frame pacing is bad on Windows due to the `Sleep` function being inaccurate. Your screenshots show that Linux also isn't able to achieve a stable frame rate, but the fluctuations are much smaller and the root cause likely isn't from the OS sleep function. 

We really shouldn't be blocking fixing this just because Linux handles sleep better than Windows though.

**Comment by adamscott** [comment]
On my MacBook Pro M3 Max: 
> Godot v4.4.dev (f128f383e) - macOS 15.1.1 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 threads)

![Image](https://github.com/user-attachments/assets/94799085-d16b-4ef8-bc91-85f9f9e36fcf)
![Image](https://github.com/user-attachments/assets/b716ef79-0672-4e16-b906-6b0b1fcf1979)

Fullscreen seems to be the same results.

@Calinou As the resolution/graph is inconsistent, can you add a label that could sum up the variation or something like that? Like the median difference in values.

**Comment by adamscott** [comment]
We should test iOS and Android too, to see if there's issues there too.

**Comment by clayjohn** [comment]
> We should test iOS and Android too, to see if there's issues there too.

Metal and Android both have frame pacing solutions that we integrate on the graphics driver level. 

Android will have the issue when Swappy is disabled, but it won't have the issue when Swappy is enabled. iOS will be the same as macOS. 

The question is really just about Windows and Linux. Linux seems to be pretty good, but not perfect, while Windows is really bad and needs a solution

**Comment by clayjohn** [comment]
Ultimately we just need to take the changes from https://github.com/godotengine/godot/pull/99178 and apply them only on Windows and only from within `add_frame_delay()`

**Comment by adamscott** [comment]
> The question is really just about Windows and Linux. Linux seems to be pretty good, but not perfect, while Windows is really bad and needs a solution

I don't understand. macOS seems as bad as Windows, unless I misunderstand.

**Comment by clayjohn** [comment]
> I don't understand. macOS seems as bad as Windows, unless I misunderstand.

MacOS has a different solution that is even better using Metal.
