### ISSUE TITLE
Incorrect atlas texture display of specific tiles

### ISSUE THREAD

**Issue by xdeadmonkx** [godotengine/godot#9973]
**Operating system or device - Godot version:**
Windows 8.1 Godot 3.0

duplicated column of pixels added at upper-right tile in the editor , but texture is correct and numbers given in texture atlas is correct (32x32 tile and 256 of x axis)
it is easy to reproduce on small textures without filtering for example 364x32 with 32x32 tiles

![image](https://user-images.githubusercontent.com/4668980/28747945-ba5b277a-74b3-11e7-8738-576fa402a562.png)

**Comment by bojidar-bg** [comment]
Duplicate / Related to #9925?

**Comment by xdeadmonkx** [comment]
maybe maybe, but #9925 was about tilesets

**Comment by reduz** [comment]
oh, AtlasTexture needs a filter clip property to disable this behavior
