### ISSUE TITLE
How can I find this send function

### ISSUE THREAD

**Issue by altarrok** [godotengine/godot#99744]
I have looked everywhere, but still couldn't find the implementation of this send function. This function is failing for no apparent reason, so I need to find the function implementation to understand what is going wrong. Thank you in advance for your guidance is very much appreciated.

Here is the line: https://github.com/godotengine/godot/blob/bbc54692c05ff6a85a6aeefbf5b9c87de91983d8/modules/websocket/websocket_peer.cpp#L101

**Comment by AThousandShips** [comment]
This is for reporting bugs, please ask support questions in the [other community channels](https://godotengine.org/community/) instead
