### ISSUE TITLE
Can't create new Image in 3.0?

### ISSUE THREAD

**Issue by Wiering** [godotengine/godot#9974]
Using Godot_v2.1.4-beta_20170625_win64 on Windows 10, I could use the code below to create a new image and set it as the texture of a sprite (with _RGBA instead of _RGBA8).
In Godot_v3.0-alpha_win64, I get the following error message on line 4

Invalid call. Nonexistent function 'Image' in base 'Sprite (sprite.gd)'.

```
extends Sprite
var img
func _ready():
	img = Image(256, 256, false, Image.FORMAT_RGBA8)
	for i in range(0, 256):
		for j in range(0, 256):
			var r = i / 255.0
			var g = j / 255.0
			var b = (i + j) / 255.0
			img.put_pixel(i, j, Color(r, g, b, 1))
	var tex = ImageTexture.new()
	tex.create_from_image(img)
	set_texture(tex)
	pass
```

**Comment by vnen** [comment]
Not a bug, just a change in the API. `Image` is not a built-in type anymore, so you have to do something like this:

**Comment by Wiering** [comment]
Okay, thanks
