### ISSUE TITLE
Double-clicking a file updates whole FileSystem tree

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#99760]
### Tested versions

4.4 dev5
The relevant code seems to exist since forever, but I don't remember it being that slow before.

### System information

Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 32.0.15.6603) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 threads)

### Issue description

When you double-click a file, the whole editor freezes for a couple of seconds. Also if you had anything in filter, it will be ignored.
https://github.com/user-attachments/assets/7a9eb54b-8e0a-4345-9605-c878dc4f6e5e
For some reason it might also unfold every folder.

I checked the code and double-clicking makes the dock navigate to the file, which causes update of the whole tree.

### Steps to reproduce

1. Open big project
2. Double-click a file, preferrably image
3. ![Image](https://github.com/user-attachments/assets/4e0b47fe-6cd7-43b1-8c81-b0f71b02e297)

### Minimal reproduction project (MRP)

N/A

**Comment by Mickeon** [comment]
I don't recall anything like this. Is this a regression?

**Comment by KoBeWi** [comment]
Doesn't seem to happen in 4.3.

**Comment by matheusmdx** [comment]
I was unable to reproduce the engine freeze but the unfolding and the filter ignore was caused by #95107, @KoBeWi 

![Image](https://github.com/user-attachments/assets/67d8cd38-57a2-46ea-a604-7221319c0ba6)

**Comment by kitbdev** [comment]
I've noticed the filters get ignored in many cases, I assume its every time the tree updates. Saving the scene, moving the filesystem dock, changing split mode, changing sorting, and opening a file all cause it.
When in split mode, it only seems to happen to the tree part.
I did not notice the editor freezing though.

**Comment by KoBeWi** [comment]
The freezing happens only when you have lots of files.
I checked in dev4 and the freeze and filter bug are separate issues (though they share their cause).
