### ISSUE TITLE
Looping issues with .wav files

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#9977]
**Operating system or device - Godot version:**
Windows 10 x64 pro - 3.0 alpha1

**Issue description:**
wav audio files does not seem to adhere to the loop settings.

**Steps to reproduce:**
use the loop option on a wav file.

**Link to minimal example project:**
Link to video showing the bug. https://youtu.be/0oRmWxG-ksE

**Comment by timoschwarzer** [comment]
Which Godot version?

**Comment by vonflyhighace2** [comment]
There is a video that shows me recreating the bug. You will see that it's 3.0 alpha1
________________________________

**Comment by akien-mga** [comment]
> There is a video that shows me recreating the bug. You will see that it's 3.0 alpha1

It's still good to specify it in clear in the original post, that makes things much easier. I've edited it for you.

**Comment by reduz** [comment]
This is not really a bug, import flags are linked to the filesystem dock file seleted, not to the scene tree node. Nodes are unrelated to files in Godot (unless instanced from a scene). In fact, in your own video you can see that the import dialog always points to the same file, which is always the .ogg

![image](https://user-images.githubusercontent.com/6265307/29922638-d7298242-8e2c-11e7-8b1e-f506f91f71b1.png)

We try to always improve usability as much as possible, but in this specific case I guess it's just lack of familiarity with the engine, so closing it.
