### ISSUE TITLE
Problem with non-triplanar UV2 in SpatialMaterial

### ISSUE THREAD

**Issue by RodZill4** [godotengine/godot#9979]
*Bugsquad edit:* Windows, Godot 3.0-alpha1

There seems to be a problem with the shader that is generated when a SpatialMaterial uses non-triplanar UV2 (the following message: ":24 - Invalid arguments to operator '*' :vec2 and vec3"). The following seems to fix the problem (scene/resources/material.cpp, ine 510): [uv2problem.diff.txt](https://github.com/godotengine/godot/files/1185558/uv2problem.diff.txt).
Only tested under Windows, but I guess it applies to other platforms.

**Comment by akien-mga** [comment]
Just a side note, please add the Godot version and OS information at the top of your issue and not in the title, as requested of you by the issue template.
