### ISSUE TITLE
EXR Loses Alpha in VRAM Compressed

### ISSUE THREAD

**Issue by ettiSurreal** [godotengine/godot#99804]
### Tested versions

Reproducible in: v4.4.dev5.official [9e6098432], v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev5 - Windows 10.0.26100 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 32.0.15.6614) - 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz (12 threads)

### Issue description

I am working on a prototype that utilizes EXR images for the graphics in 3D, however I ran into an issue that when compression mode is set to VRAM Compressed, the texture loses its alpha channel.
This is a huge issue on my end because making every texture lossless inflates the file size of the game by ~15x. In my case I could probably switch to using separate images for the alpha channel, but since I couldn't find this documented anywhere I assumed this is a bug.

![Image](https://github.com/user-attachments/assets/3e7c4a67-6a1e-4eb9-a013-0d11cab38c65)
![Image](https://github.com/user-attachments/assets/2862c0a5-d545-4b07-b975-0522f972b18f)

### Steps to reproduce

Import an EXR image that has transparency, and set the compression mode to VRAM Compressed.

### Minimal reproduction project (MRP)

[alphacompression.zip](https://github.com/user-attachments/files/17951294/alphacompression.zip)

**Comment by mrjustaguy** [comment]
This is expected behavior, VRAM compressed HDR formats don't support Alpha.
