### ISSUE TITLE
Animating a skeleton that has a BoneAttachment node will crash the editor.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#9982]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 3.0 Alpha 1

**Issue description:**
If you add a BoneAttachment node to a skeleton and then animate the skeleton in the editor with the AnimationPlayer or the AnimationTreePlayer, the editor will crash. However it seems like running it in-game does not crash the game.

Edit:
I just changed the AnimationPlayer and AnimationTreePlayer process mode to "fixed", and the editor crashing stopped. After switching the process mode back to "idle" it still doesn't crash. I'm not sure if this was just a problem with this demo then.

After deleting the BoneAttachment and adding it again the editor crashing started again. Looks like maybe the BoneAttachment only crashes after it's added for the first time, or something.

**Steps to reproduce:**
Open the 3D Platformer demo, open the Player scene, add a BoneAttachment to the skeleton, and try to animate the player. The editor will crash. But if you run the game, the game will not crash.

**Comment by kubecz3k** [comment]
I can reproduce on 76005a8e75d4e63ad0477e11dbc8cc1c86666875 Worth to mention that for me the most certain way of reproducing was to run animation in `AnimationTreePlayer`.

**Comment by reduz** [comment]
just fixed this, closing

**Comment by akien-mga** [comment]
For the reference, fixed in 2a6cdfa.
