### ISSUE TITLE
Thread can deadlock when using a worker thread to load a C# script with a generic base class

### ISSUE THREAD

**Issue by preslavnpetrov** [godotengine/godot#99839]
### Tested versions

- Reproducible in: 4.4dev5

### System information

Godot v4.4.dev5.mono - Windows 10.0.26100 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 Super with Max-Q Design (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 threads)

### Issue description

Currently, if we use either a worker thread with ResourceLoader::load() or use ResourceLoader::load_threaded_request(), and try to load any resource with a dependency on a script that inherits a generic C# class, we run into a _scriptTypeBiMap.ReadWriteLock deadlock.

This happens in a very specific circumstance:

1. The script and its base hasn't been loaded before, so it's not populated into the BiMap
2. Calling the load from a worker thread will make the ResourceLoader::load() call from inside godot_sharp_internal_script_load to spin up a separate worker thread to load the dependency base script
3. This secondary worker thread will try to get the script from the BiMap unsuccessfully, since it hasn't been populated yet, and will then fall back to creating the script bridge. While doing so, it will try to lock the already locked BiMap ReadWriteLock from when we were loading it's child script

### Steps to reproduce

1. Download the MRP
2. Launch the project with a build of Godot4.4dev5 with the --verbose arg
3. Click the Attempt Repro button several times while looking at the log. 
4. Eventually you should see the load stall at the first generic csharp:// script and not manage to print "Loaded successfully"

### Minimal reproduction project (MRP)

[thread-lock-mrp.zip](https://github.com/user-attachments/files/17961809/thread-lock-mrp.zip)

**Comment by preslavnpetrov** [comment]
Hey folks, after testing the changes from £99539 with the mrp, I've found that the merged pull request didn't actually resolve the issue, and the same deadlock can still be achieved. I've tweaked the mrp a little to make it easier to use by adding a keyboard shortcut for attempting a repro (space bar) and attached it here.

Can we please reopen this issue as it's not fixed?

[thread-lock-mrp.zip](https://github.com/user-attachments/files/18280405/thread-lock-mrp.zip)

**Comment by conde2** [comment]
I still can confirm that the merged pull request doesn't address the issue. I'm still getting the deadlock.

**Comment by dougVanny** [comment]
Is there any known workaround for this? I could not reproduce the issue with the mrp but I believe I am falling in the same scenario as the debugger tells me I'm always deadlocked in the _scriptTypeBiMap.ReadWriteLock. My code is too massive for me to pinpoint exactly what is causing it, but this started to happen randomly once I started to use multithreading to load and instantiate some PackedScenes in an attempt to free my main thread.

**Comment by conde2** [comment]
@dougVanny please check 
https://github.com/godotengine/godot/issues/99128

There is more information there, and we can focus the discussion there
