### ISSUE TITLE
Fix the documentation (saving games) for godot 3

### ISSUE THREAD

**Issue by Elmapul** [godotengine/godot#9984]
**Operating system or device - Godot version:**
Ubuntu 14.04 Godot 3.0 alpha

i'm not sure if that is specific of godot 3, i was following this tutorial:
http://docs.godotengine.org/en/stable/learning/features/misc/saving_games.html
http://docs.godotengine.org/en/latest/learning/features/misc/saving_games.html
and got this error
Invalid call. Nonexistent function 'to_json' in base 'Dictionary'.
i took me a while to figure out that insted of:

  savegame.store_line(nodedata.to_json())
i should do that:
savegame.store_line(to_json(nodedata))

**Comment by Noshyaar** [comment]
It's specific to Godot 3. There has been some API changes. Although I think this issue is related more to the [Godot Docs repository](https://github.com/godotengine/godot-docs/) than this one.

**Comment by Elmapul** [comment]
oh, sorry, i thought i might be at the wrong place, so i opened another tab to post there, and end up posting here instead.
in any case "It's specific to Godot 3. " so the only link that should be fixed is the lastest one.
