### ISSUE TITLE
Autowrap breaks button size.

### ISSUE THREAD

**Issue by viksl** [godotengine/godot#99878]
### Tested versions

4.3

### System information

Win 11, i513600kf, RTX 4070.

### Issue description

When autowrap is set it breaks the size of buttons with Godot's automatic sizing in games as well as in plugins.
Video: https://youtu.be/f-Zi81_Ocsw

1. Early in the video you can observe no issues when autowrap is disabled.
2. In the video you can see that if you move slowly the buttons get properly resized but if you move quickly you can break it.
3. In the second half you can watch the same issue with an Editor plugin I added which is automatically resized by Godot and not me which means it's not just an issue of moving mouse too quickly.

In the video everything had its custom size set for X, after the video I also set it to Y (with a more than enough of a value) - for the plugin part of the video the buttons as well as other elements have both X and Y minimum sizes set properly with enough buffers - but it still breaks.

(It breaks with any autowrap option other then Off)

### Steps to reproduce

Add couple buttons, assign text to them which spans couple words so you can test the wrapping, to a HBoxContainer, set custom min sizes to buttons as well as the container, set the anchors and offset values to Left Wide then grab the HBoxContainer right side handle and move around to shrink/enlarge the box until you observe the issues as in the video, for comparison you can move slowly to see how it works properly or when broken you can change the custom min size to some value just barely above/below your so Godot automatically resizes everything correctly.

Second option, add an EditorPlugin as described above to the viewport, resize the viewport to make sure it doesn't span the entire viewport and then just got Project Settings - Plugins and enable and disable the plugin just like I did in the video, this way you can see how the size gets messed up, if you move the viewport handle then even by just a pixel it properly resizes again.

### Minimal reproduction project (MRP)

[AutoWrapMrp.zip](https://github.com/user-attachments/files/17966211/AutoWrapMrp.zip)

**Comment by JamesC01** [comment]
I'm also having issues with autowrap and button sizes, but it's a bit different. If I dynamically create a button (with autowrap on) and put it inside a VBoxContainer, if the text is more than one line, the text will flow outside of the button, but weirdly, if you hide and show the button, it fixes the size. But it has to be seen in game first before it will fix itself, so I've spent hours just trying to get it work correctly. Also on 4.3. It only seems to happen when the font is bigger than the default one, though.

But, I tested it in the latest 4.4 dev build, and it works fine! So at least my problem has been, fixed, maybe check to see if your issue has been fixed.

**Comment by viksl** [comment]
I have no idea, after opening the project in 4.4 I couldn't reproduce it with the MRP and after that I reopened it in 4.3 (after importing the project into 4.4) and could not reproduce it either.
I'm not sure if something changed with import to 4.4 or where the problem actually is, you can see the issue in the video recorded where I was able to reproduce it in multiple projects so honestly I don't know exactly what triggers it, just that there's an issue.
I didn't have much time to test it throughouly with the plugin and such so I'll test that and see in the future but I'm busy currently.
For now the best I can provide is the recorded video of the problem in different projects as described. :'(

**Comment by BrianBHuynh** [comment]
I can confirm that I ran into this problem in 4.3 but once updating to 4.4 I did not have this problem

**Comment by BrianBHuynh** [comment]
From what I can tell @timothyqiu fixed this problem here https://github.com/godotengine/godot/commit/0f98b3244805d61ef9edcfa4671ab77c1c5167a7 which has already been pushed to the main branch

**Comment by akien-mga** [comment]
Fixed by #97389.
