### ISSUE TITLE
Rename `_add_child_below_node` to `add_child_below_node`

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#9988]
```
extends Control
 
func _ready():
   
    var c0 = Control.new()
    c0.set_name("Control0")
    add_child(c0)
   
    var c1 = Control.new()
    c1.set_name("Control1")
    add_child(c1)
   
    var c2 = Control.new()
    c2.set_name("Control2")
    add_child(c2)
   
    var c3 = Control.new()
    c3.set_name("Control3")
    add_child(c3)
 
func _process(delta):
    set_process(false)
    move_child($Control3,$Control0.get_position_in_parent()+1)
    move_child($Control3,$Control1.get_position_in_parent()+1)#this line is moving Control3 to the last pos but it should be after Control1
   
    for n in get_children():#This also print wrong order remove line 22 and see
        print(n.get_position_in_parent())
```
As a workaround I use this

```
remove_child(c3)
_add_child_below_node($Control1,c3)
```

Can we rename `_add_child_below_node` to `add_child_below_node` ?

**Comment by akien-mga** [comment]
Please don't forget to mention your Godot version, I don't want to have to infer it from the usage of `$Control3` in your code snippet... There's a reason why we have an issue template.

**Comment by akien-mga** [comment]
I don't think there is a bug in the first place.

Your `_ready` gives the following:
```
pos 0: Control0
pos 1: Control1
pos 2: Control2
pos 3: Control3
```

Then the first `move_child` evaluates to `move_child($Control3, 0 + 1)`, so:
```
pos 0: Control0
pos 1: Control3
pos 2: Control1
pos 3: Control2
```

And the second `move_child` evaluates to `move_child($Control3, 2 + 1)` (yes, you moved $Control1 too by inserting a node before it :)):
```
pos 0: Control0
pos 1: Control1
pos 2: Control2
pos 3: Control3
```

So all good, the bug is in your logic.

> Can we rename _add_child_below_node to add_child_below_node ?

Sounds good. I'll edit the issue for that.

**Comment by neikeq** [comment]
Is `_add_child_below_node` even exposed to GDScript?

**Comment by Noshyaar** [comment]
It seems to be, for UndoRedo to function I guess.
```
$ grep -rI _add_child_below_node

editor/scene_tree_dock.cpp:
editor_data->get_undo_redo().add_do_method(parent, "_add_child_below_node", node, dup);

scene/main/node.cpp:
ClassDB::bind_method(D_METHOD("_add_child_below_node", ...
```

**Comment by neikeq** [comment]
Yes, but methods that begin with underscore are not exposed to GDScript/documentation unless they are virtual. @reduz maybe we should have a warning in debug builds when someone tries to call these?

**Comment by saltares** [comment]
Taking a look

**Comment by bojidar-bg** [comment]
@saltares seems like you forgot to make a PR?
