### ISSUE TITLE
vs2013 compile error 

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#9989]
**Operating system or device - Godot version:**

godot 3.0

scons p=windows

core\global_defaults.cpp(1) : fatal error C1083: 无法打开包括文件: “global_conf
ig.h”: No such file or directory
scons: *** [core\global_defaults.windows.tools.32.obj] Error 2
scons: building terminated because of errors.

**Comment by akien-mga** [comment]
Remove your `core/global_defaults.cpp` file, it's from an old build and changed name in new builds.
