### ISSUE TITLE
Installing export template fails and displays empty "Warning!" window

### ISSUE THREAD

**Issue by Meorge** [godotengine/godot#99907]
### Tested versions

- Reproducible in: 4.4.dev [893bbdfde]

### System information

Godot v4.4.dev (893bbdfde) - macOS 15.1.1 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated AMD Radeon Pro 5500 XT - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 threads)

### Issue description

I'm unable to add an export template file to Godot 4.4.dev. Attempting to do so results in a blank window that says "Warning!" in the title bar and has no content.

https://github.com/user-attachments/assets/3fd9071d-6ba0-4207-bdac-f7ad1192ea1a

### Steps to reproduce

Build an export template:
```
scons platform=macos target=template_release arch=x86_64 generate_bundle=yes
```

Open a project in Godot, then go to "Editor > Manage Export Templates..." In the window that appears, choose "Install from File". Choose the built export template.

A small blank window will appear, with the title "Warning!". Clicking on the window may cause it to close (I haven't determined exact criteria for this).

### Minimal reproduction project (MRP)

N/A

*Edit: I realized the version I originally reported this with was my own feature branch. I went back to `master` and verified the bug still occurs there.*

**Comment by AThousandShips** [comment]
Thank you for reporting! This was already reported in:
* https://github.com/godotengine/godot/issues/85862

Closing to keep things in one place
