### ISSUE TITLE
VisualScript LocalVarSet not holding values when playing scene

### ISSUE THREAD

**Issue by doug-orchard** [godotengine/godot#9992]
**Operating system or device - Godot version:**
MacOS 10.12.1 / Godot v3.0.alpha.build.1

**Issue description:**
VisualScripting local vars loose properties on run scene and or when closing and reopening file. 

**Steps to reproduce:**
New project,
Add Node,
Add child Node2D of Node,
Attach VisualScript script to Node2D,
Create '_ready' function,
Add LocalVarSet to _ready,
duplicate LocalVarSet,
set LocalVarSet's to Vector2,
rename LocalVarSet's to 'one' and 'two' respectable,
set LocalVarSet ( "one" ) to Vector2(0,1),
set LocalVarSet ( "two" ) to Vector2(1,0),
Link _ready to the LocalVarSet's in a chain ( _ready -> LocalVarSet ( "one" ) -> LocalVarSet ( "two" )  ),
Press play Scene.

The local vars should now change and have the same value. 

i found this but trying to compare the key presses code ( eg. 'w' -> 87 ) but the numbers would always revert to one of the keys i was trying to compare with. think i had to rewrite the codes a min 6 times before they got stuck and didn't change when i hit the play scene button.

**Link to minimal example project:**
[test.8 - bug reporting VS.zip](https://github.com/godotengine/godot/files/1186931/test.8.-.bug.reporting.VS.zip)

**Comment by bojidar-bg** [comment]
Can't seem to reproduce this on master anymore, closing unless someone else can reproduce it. (I'm still sure I could reproduce it a few weeks ago, probably someone unwillingly fixed it)
