### ISSUE TITLE
AnimationPlayer not working when testing scene

### ISSUE THREAD

**Issue by damarindra** [godotengine/godot#9994]
**Operating system or device - Godot version:**
Windows 10, master branch

**Issue description:**
Want to make moving platform with kinematicBody2D, using AnimationPlayer. While using the editor is normal, but when testing by running the scene, AnimationPlayer is not started. Trying with previous godot build is still working. 

I also trying to using AnimationTreePlayer, result still the same. 

I'm not sure this is real bug, or just me who can't setup it with the new build, test project included.

**Link to minimal example project:**
[Animation.zip](https://github.com/godotengine/godot/files/1187150/Animation.zip)

**Comment by kubecz3k** [comment]
What was the mentioned previous working build?

**Comment by damarindra** [comment]
Okay, just figured out this is my fault.

So, I just build the master branch and open my old testing project (build from 11 July), My whole scene with AnimationPlayer can't be open again in this version, I can only open scene without any AnimationPlayer node (I don't know why). So I replicate my scene. The animation is not playing because I forgot to activate autoplay, stupid of me.
