### ISSUE TITLE
Viewport's "Clear on new frame" not working

### ISSUE THREAD

**Issue by MakeGodotGreatAgain** [godotengine/godot#9995]
**Operating system or device - Godot version:**
3.0 alpha

**Issue description:**
[testgamedeletemenow.zip](https://github.com/godotengine/godot/files/1187418/testgamedeletemenow.zip)

for example, the bottom right viewport, the light2d should paint across the canvas because clear on new frame is disabled.

![](https://i.gyazo.com/4cceccd2a96e177beecebb9426347935.png)

**Comment by MakeGodotGreatAgain** [comment]
Culprit, https://github.com/godotengine/godot/blob/62464839ad2326099203f1b851d0ef27e630cbe7/scene/main/viewport.cpp#L1265 ?

**Comment by akien-mga** [comment]
> Culprit, https://github.com/godotengine/godot/blob/62464839ad2326099203f1b851d0ef27e630cbe7/scene/main/viewport.cpp#L1265 ?

According to the git blame, it was commented out in the first commit porting Godot to GLES 3.0 10 months ago - then I guess it was just forgotten and never fixed.

You could try uncommenting it and see what happens; I guess there might be some build issues if it references a method that was not properly ported to the new renderer.

**Comment by MakeGodotGreatAgain** [comment]
ya, thanks akien.

looks like viewport_set_clear_on_new_frame is not found anywhere else though

![](https://i.gyazo.com/cda449722d92d0c941d70f5cdc180eb6.png)

i'd be scared to compile again, but i can try xD

**Comment by akien-mga** [comment]
Actually don't bother trying to compile, all the `clear_on_new_frame` stuff is commented out in https://github.com/godotengine/godot/blob/master/servers/visual/visual_server_raster.cpp

So we need input from @reduz to know if it's meant to be reimplemented, or to go away.

**Comment by reduz** [comment]
I see what is going on, the API changed in the VisualServer and it was never exposed back
