### ISSUE TITLE
`TreeItem` Button willl not press on a scaled `Tree`

### ISSUE THREAD

**Issue by Sloyd** [godotengine/godot#99954]
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Tested on Windows 11 and Linux

### Issue description

If a `Tree` or its Parent is scaled, the tree item button would not press.

### Steps to reproduce

1. Create a `Tree`
2. Add a `TreeItem`
3. Add a button to that `TreeItem`
4. Set the Tree scale to 2

If we listen to the button firing signals before scaling the tree, they fire. If after, they dont fire.
Note: the problem arises even if we scale the container

### Minimal reproduction project (MRP)

You can attach this script to a CanvasLayer totest

```csharp
public partial class TreeTest : Node
{
	[Export] private Control _container;
	
	[Export] private Texture2D _texPlus;
	[Export] private Texture2D _texMinus;

	private Tree _tree;

	public override void _Ready()
	{
		_container.Scale = Vector2.One * 2;

		_tree = new Tree();

		_tree.CustomMinimumSize = new Vector2(200, 200);

		var root = _tree.CreateItem();
		root.SetText(0, "root");

		var item1 = _tree.CreateItem(root);
		item1.SetText(0, "itm 1");
		item1.AddButton(0, _texMinus);
		item1.AddButton(0, _texPlus);

		var item2 = _tree.CreateItem(root);
		item2.AddButton(0, _texMinus);
		item2.AddButton(0, _texPlus);
		item2.SetText(0, "itm 2");

		_tree.ButtonClicked += ButtonClicked;

		_container.AddChild(_tree);
	}

	private void ButtonClicked(TreeItem item, long column, long id, long mouseButtonIndex)
	{
		GD.Print($"ButtonClicked: {item.GetText(0)} col:{column} id:{id}");
	}

}
```

**Comment by Sauermann** [comment]
I was able to reproduce this bug in v4.3.stable.official [77dcf97d8].
This bug is no longer reproducible in v4.4.dev.custom_build [0f20e67d8].

It got fixed in #98299.

This project showcases also another aspect: buttons can't be hovered by mouse. This got implemented in #88530

So I'm closing this issue as already resolved in master for the upcoming 4.4.
