### ISSUE TITLE
The material assigned to a tilemap should take effect unless overwritten by tile material.

### ISSUE THREAD

**Issue by Asmageddon** [godotengine/godot#9996]
As it is, assigning materials to tilemaps is extremely counterintuitive. Ideally, it should also be possible to set a tilemap-wide material, as well.

EDIT: This is in 2.1 btw.

**Comment by RandomShaper** [comment]
That depends on how you look at it. If you assume that a null material actually means 'the default material', then everything makes sense.

But your point opens a possible feature proposal about being able to override the tiles' material for the whole `TileMap` for tiles with no explicit material or even for the whole map as another option.

Nonetheless, I'm not sure that would be of great interest as long as you can always do it pretty easily by script and it doesn't look as something so widely needed for being implemented as a builtin feature.

**Comment by Asmageddon** [comment]
It's extremely counterintuitive that a material assigned to the tilemap node does not have any effect.

**Comment by RandomShaper** [comment]
Two options here:
- try to remove that property from the `TileMap` to avoid confusion (difficult because it's a subclass of `CanvasItem`);
- let it do something, like overriding every individual tile material.

Can you tell a bit more about your use case?

**Comment by Asmageddon** [comment]
I created a mask for which areas should be affected by light/shadows(I have tall walls), and a shader that applies it, I thought I could assign it to the TileMap, but apparently no, so I had to assign it manually to every tile.

**Comment by RandomShaper** [comment]
I'm working on a PR for this.

**Comment by RandomShaper** [comment]
@Asmageddon, have a look at #10361.

**Comment by Asmageddon** [comment]
I'm not a Godot developer, so this doesn't mean much to me, I just reported the issue since it seems like the least I can do for the project :P
